### ISSUE TITLE
Add f-droid releases

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#10]
Just as the title says add f-droid to the app stores we release the app to.

@tobiasKaminsky I just assigned the issue to you since you know your way around f-droid's mechanisms on how to get apps into their app store.

**Comment by tobiasKaminsky** [comment]
So I can release 1.0.0?

**Comment by AndyScherzinger** [comment]
Yes, I already made a release/tag https://github.com/nextcloud/android/releases
And it has been published to the Google Play store yesterday: https://play.google.com/store/apps/details?id=com.nextcloud.client

**Comment by tobiasKaminsky** [comment]
currently in review process:
beta: https://gitlab.com/fdroid/fdroiddata/merge_requests/1461
normal: https://gitlab.com/fdroid/fdroiddata/merge_requests/1464

**Comment by AndyScherzinger** [comment]
Nice! :tada:

**Comment by tobiasKaminsky** [comment]
Beta is merged and should be available this or the next night.

**Comment by AndyScherzinger** [comment]
Sweet! :tada:

**Comment by GIJack** [comment]
awesome. I use owncloud app on F-Droid now. Its also great for people with custom roms that don't use google play. Especially good for secure installs that can't have google play.

**Comment by xenithorb** [comment]
Hi, please do this. I have become accustomed to using ownCloud's app through F-droid, so it would be nice to also see nextcloud here as well. That way we can truly phase-out ownCloud.

**Comment by AndyScherzinger** [comment]
Hi @xenithorb as described above we are already in the making :rocket: So it shouldn't take too long for Nextcloud to pop up in f-droid.

**Comment by xenithorb** [comment]
Excellent, you guys rock. Per the news about the new release I'm already reading the manual to move my server over! Thanks!

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky the beta is now online, the stable is still missing. Not sure if there is still some issue though

**Comment by tobiasKaminsky** [comment]
Official app is still in progress...
I hope that it will be merged today.

**Comment by tobiasKaminsky** [comment]
Aaaaaaaaaaand official client is merged.
Should be available tomorrow or the day after.
