### ISSUE TITLE
Celebration

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#1000]
This is #1000 since our fork and we (I hope I am allowed to speak also for @mario and @AndyScherzinger) want to thank all of you to support the app by reporting bugs, contributing translations, contributing PR, and many more.
Together we will make the app even better 

Thank you Community, you rock :tada:!

**Comment by nickvergessen** [comment]
Yeah, let me join in here. I like it that the Android app replaces more and more of my usages of the web UI on my phone.
Once activity and notifications are there, I don't need the UI anymore on my phone! Good work!

**Comment by AndyScherzinger** [comment]
also joining in.... Thanks everyone who participates in the Nextcloud development and especially in the Android client!

Happy to be a part of the 🥇 community! 🚀

**Comment by mario** [comment]
:)

Let's do next celebration once we have 0 issues :P
