### ISSUE TITLE
Different debug release

### ISSUE THREAD

**Issue by aishahsf** [nextcloud/android#10005]
on emulator:
(https://user-images.githubusercontent.com/98502301/159430733-31dcc6b8-9cba-43e6-b580-1c58c67d0d07.PNG)

on device:
(https://user-images.githubusercontent.com/98502301/159431213-8677112b-b700-405a-9353-8aa777ab144b.jpeg)

DEVICE:
android: 11
brand: samsung
model: SM.A515F
Id: RP1A.200720.012
Product: a51nsxx

**Comment by AlvaroBrey** [comment]
Can you be more specific? What version are you deploying in both cases? The string "Keep your data safe" is nowhere in our source code.

**Comment by aishahsf** [comment]
EMULATOR:
* Pixel 2 API 24
* ANDROID 7.0


When I run android project in android emulator (Pixel 2 API 24) it shows the correct layout "keep your data safe". but if I run the project in Hardware device (Samsung a51) it shows different output which is "keep your data secure and under your control".

**Comment by AlvaroBrey** [comment]
The correct string is "Keep your data secure and under your control". Not sure where you're pulling "keep your data safe" from.
