### ISSUE TITLE
Remove the included file browser

### ISSUE THREAD

**Issue by RokeJulianLockhart** [nextcloud/android#10031]
### Is your feature request related to a problem? Please describe.
It wastes space, so addition https://github.com/nextcloud/android/issues/3001#issuecomment-1066705023 demonstrates that this is not necessary.

### Describe the solution you'd like
Removal of the included browser of filesystems.

### Describe alternatives you've considered
What exists currently is the sole alternative option.

**Comment by AlvaroBrey** [comment]
This may be considered in the future, but it definitely is not a waste of space. It allows us to do more things than the system browser

- Has consistent UI throughout different phones, which system browser does not.
- Allows for inclusion of UI elements (like choosing if you want to remove the file after upload), which system browser does not
- Is customized with server colors
- etc

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@AlvaroBrey, the 2nd reason is rationale that I affirm, but none of the rest rationalises inclusion of it, especially not the colourative adaptation; that is silly.

**Comment by joshtrichards** [comment]
> This may be considered in the future, but it definitely is not a waste of space. It allows us to do more things than the system browser

For the time being... I'm classifying this as "won't fix".
