### ISSUE TITLE
latest version contains binary libopencv_java4.so, disabled in F-Droid

### ISSUE THREAD

**Issue by jspricke** [nextcloud/android#10046]
The latest version contains a number of binaries which is not allowed in F-Droid. I've disabled it, therefore:
https://gitlab.com/fdroid/fdroiddata/-/commit/d38e919a682bf6f46ac6858d39d6e6648f3b50d4

Can you please drop or build them from source?

Thanks!

**Comment by tobiasKaminsky** [comment]
Can you share some background info why this is forbidden? Scan library and openCV are both open source and "trust able" as all other libraries out there.

Which part would be needed to be built from source? Document scanner lib or openCV?

**Comment by jspricke** [comment]
Tiny-OpenCV would need to build OpenCV from source:
https://github.com/zynkware/Tiny-OpenCV/tree/master/openCV440/src/main/jniLibs/armeabi-v7a

**Comment by jspricke** [comment]
To give some more backround: F-Droid requires everything build from the source. We have some trusted repositories, like Maven central and jitpack but only if their components are build from source. The Tiny-OpenCV contains only the binary modules, there is no guarantee that it is actually build from the OpenCV sources and I don't see any information how to reproduce it.

**Comment by AlvaroBrey** [comment]
We'll disable the functionality for Fdroid for now, as we can't find a suitable replacement that builds openCV from source.

**Comment by linsui** [comment]
I also disabled the `com.nextcloud.android.beta` which uses the versionDev flavour. Could you please maybe add another flavour? Thanks!
