### ISSUE TITLE
Incorrect `uses-feature` found in AndroidManifest

### ISSUE THREAD

**Issue by chirayudesai** [nextcloud/android#10045]
### Steps to reproduce
1. Download Nextcloud 3.20.0 RC1 and 3.19.1
2. `androguard axml file.apk` to see the AndroidManifest.xml in the built apk
3. Look for uses-feature.

### Expected behaviour
- APK should not require this feature.

### Actual behaviour
- `android.hardware.camera2` is present in 3.20.0 RC1 which doesn't actually exist AFAICT.
- `android:required="false"` is also not set for it unlike the other two in your manifest.

Reference: https://developer.android.com/guide/topics/manifest/uses-feature-element

### Can you reproduce this problem on https://try.nextcloud.com?
- Not a server side issue

### Environment data
Android version: 12

Device model: Pixel 5

Stock or customized system: Customized

Nextcloud app version: 3.20.0 RC1

Nextcloud server version: N/A

Reverse proxy: N/A

#### Web server error log
N/A

#### Nextcloud log (data/nextcloud.log)
N/A

**Comment by AlvaroBrey** [comment]
Thanks @chirayudesai !
