### ISSUE TITLE
(old) usernames with a single quote lead to "Server not availabe" while reading files

### ISSUE THREAD

**Issue by SpatMan05** [nextcloud/android#10053]
### Steps to reproduce
Nextcloud Android app 3.19.1 installed
Seems to be same issue as https://github.com/nextcloud/android/issues/9331
And maybe some others special chars may be concerned...

Useraccount is of form "word1'word2" (with a single quote in it) example: "Spat'Man"

**Comment by AlvaroBrey** [comment]
Thanks @SpatMan05 !
