### ISSUE TITLE
Integrated document scanner in app and home screen widget

### ISSUE THREAD

**Issue by lukegackle** [nextcloud/android#10067]
### Is your feature request related to a problem? Please describe.
Transitioning from Google Drive I really miss the convenience of a single tap to start capturing a document and saving to Google Drive, I wish Nextcloud had these features 

### Describe the solution you'd like
The addition to the Nextcloud app for document scanning functionality

### Describe alternatives you've considered
Unsure, continue using Gdrive, or look into ways to automatically copy files in Gdrive to Nextcloud

### Additional context
![Screenshot_20220408-234239](https://user-images.githubusercontent.com/33621585/162453666-ff45e84b-58f3-4e19-a8fa-57daefc2ac24.png)
![Screenshot_20220408-234258](https://user-images.githubusercontent.com/33621585/162453700-5a9db02a-283b-4631-9cee-b09e810f5e0c.png)

**Comment by AlvaroBrey** [comment]
Document scanning is available in 3.20.0 RC2. #9717

**Comment by lukegackle** [comment]
> Document scanning is available in 3.20.0 RC2. #9717

Oh wow I didn't realise this was being worked on, that's fantastic, can't wait to try it out! A widget would still be nice to have it's just a couple less steps to scan but if the core functionality of document scanning is being added that's awesome 😁

**Comment by boyddensmore** [comment]
I don't know much about Android development so I don't know if this is feasible or reasonable but I'll mention it anyway.

I've been using an app called Shortcut Maker to... make shortcuts... to intents and activities and such within different application.  For example I could create a shortcut to "Add new card" in the Nextcloud Deck app.  When I tap the shortcut I'm prompted for some values and the card is created.

Could something similar be done with Scan?

This is the activity that handles that in the Deck app.
https://github.com/stefan-niedermann/nextcloud-deck/blob/master/app/src/main/java/it/niedermann/nextcloud/deck/ui/preparecreate/PrepareCreateActivity.java

**Comment by joshtrichards** [comment]
Fixed in #9717 
Released in v3.20.0

@boyddensmore Please open a dedicated issue for that. :-)
