### ISSUE TITLE
How to refresh the list without synchronising? Or how to do it with syncing? Full manual needed also!

### ISSUE THREAD

**Issue by injesus-k** [nextcloud/android#1007]
Hi

In a folder after clicking refresh account nothing happens. The list of files and folders stays the same. What to do?

Where is the main manual online to explain all the colors and behavior? Who can explain to me? I am quite disappointed not to find this online?

Sincere,
Klaus

**Comment by tobiasKaminsky** [comment]
For refreshing a directory it is enough to enter it, or if you want te refresh while you are in it, you can pull down to refresh.
There is no online manual as the whole app should be self explaining.
What design/UI problems/questions do you have? Maybe we can solve them in a way that it is clearer for new users.

cc @jancborchardt

**Comment by joshtrichards** [comment]
Related: #1152
