### ISSUE TITLE
Copy operation overwrite (same) file with zero byte

### ISSUE THREAD

**Issue by cnleo** [nextcloud/android#10078]
### Steps to reproduce
If you copy a file to the same folder it will overwrite itself with 0 Bit/Byte. File exist but the data is lost.
This should not be the default behavior. Instead, there should be a prompt to duplicate the file or cancel the operation. Or instead, simple ignore the copy operation.

### Expected behaviour
This should not be the default behavior. Instead, there should be a prompt to duplicate the file or cancel the operation. Or instead, simple ignore the copy operation.

### Actual behaviour
 File exist but the data is lost.

### Can you reproduce this problem on https://try.nextcloud.com?
login does not work (unknown pw)

### Environment data
Android version:
10
Device model: 
Aquaris X2
Stock or customized system:
stock
Nextcloud app version:
3.19.1
Nextcloud server version:
23.0.3

**Comment by AlvaroBrey** [comment]
Can't reproduce. For me, copying a file to the same folder does nothing.

**Comment by cnleo** [comment]
Oh, it happens only in the top/root level (where the folder Documents, Notes...). if you select a file out of some sub-folders and copy->choose the same "root-level" (simple, do nothing else touch "copy", touch "choose" done), the file is now 0bit.

**Comment by AlvaroBrey** [comment]
Still can't reproduce.

What I'm trying:
1. Go into subfolder
2. Tap on a file's 3 dot menu
3. Tap "Copy"
4. Tap "Choose"

The file is then copied to the root folder correctly.

Have you tried the latest RC version to see if the bug persists?

**Comment by cnleo** [comment]
Yeah, now I have problems to reproduce it, too. Looks like if the app crashes sometimes in combination with a copy or move operation after restart sometimes I lost the data. Sometimes not. Last time with an mp3 file. Have posted the crash log in an other issue. https://github.com/nextcloud/android/issues/10096
I try to test it with screen record on.
Now I have it with "open with" after that they lost the data.

https://user-images.githubusercontent.com/843262/164015738-8e1ef87b-5711-4876-a131-90af1e22bb78.mp4

**Comment by cnleo** [comment]
Maybe it is a SD-Card problem? I have read in other Issues they related and fixed they used the internal storage instead the external-SD-Card. I will test it. But I am not sure witch one I should use:

(A recommendation would be nice)
- /storage/emulated/0/Android/media/com.nextcloud.client _(current selected)_ 
- /storage/1234-5678/Android/media/com.nextcloud.client
- /data/user/0/com.nextcloud.client/files
- /storage/emulated/0/android/data/com.nextcloud.client/files

**Comment by joshtrichards** [comment]
Are you still experiencing this @cnleo?
