### ISSUE TITLE
Upload failed: You are not permitted to upload to this folder

### ISSUE THREAD

**Issue by Zugschlus** [nextcloud/android#10081]
### Steps to reproduce

I do not have a reliable reproducer. I am a new user using the Android App on a Nokia 7.2 phone, writing to a dockerized local nextcloud installation. Trying to do the initial upload of my pictures, and I get a lot (> 50) of notifications saying "Upload failed: You are not permitted to upload to this folder."

### Expected behaviour

I would expect the app to at least say WHICH folder it tried to write to. That would be incredibly helpful in finding the issue.

### Actual behaviour

The error message "You are not permitted to upload to this folder" is not helpful at all.

### Can you reproduce this problem on https://try.nextcloud.com?

I am not trying to do that, I'd need to upload hundreds of private pictures. I guess it can be reproduced by setting a directory in the server-side file directory to 000 permissions and trying to upload.

### Environment data

Android version: 1

Device model:  Nokia  7.2

Stock or customized system: Stock

Nextcloud app version: 3.19.1

Nextcloud server version: 23.0.3

Reverse proxy: none

**Comment by AlvaroBrey** [comment]
> Trying to do the initial upload of my pictures

Is this an autoupload folder? If so, can you check if the `InstantUpload` folder exists in your server user, and what its permissions are?
