### ISSUE TITLE
Send not working

### ISSUE THREAD

**Issue by subesokun** [nextcloud/android#1009]
### Actual behaviour
- When trying to share an image (*.JPG) via the "send" function to a WhatsApp contact then the error "unsupported file format" gets thrown within WhatsApp. Also other messaging applications are failing to send the image.
- If I direct access the nextcloud data folder with some other file browser app I can successfully send the image so the image itself is ok.

### Expected behaviour
- Image should have been shared with WhatsApp so that it can be send to one of the WhatsApp contacts.
 
### Steps to reproduce
1. Open image
2. Select "send" in the options
3. Select WhatsApp (or some other app)

### Environment data
Android version:
7.1.2
Device model: 
Nexus 5X
Stock or customized system:
Stock
Nextcloud app version:
1.4.2
Nextcloud server version:
11.0.3

**Comment by tobiasKaminsky** [comment]
This is happening if the file suffix is "JPG" and not "jpg".
I will fix it.

**Comment by tobiasKaminsky** [comment]
I tried it with an identical image, once with ".jpg", the other with ".JPG":
JPG:
mimetype: image/jpeg
uri: content://org.nextcloud.files/external_files/emulated/0/nextcloud/tobi%40tobi-laptop%252Fnc/allTypes/image.JPG

jpg:
mimetype: image/jpeg
uri: content://org.nextcloud.files/external_files/emulated/0/nextcloud/tobi%40tobi-laptop%252Fnc/allTypes/image.jpg

"jpg" is working fine. This seems to be a problem of the receiving app (whatsapp or others).

@mario @AndyScherzinger do you have an idea how to proceed here?

**Comment by mario** [comment]
If the file is on SD card, then we can lowercase the file extension.
Otherwise that is not safe.

**Comment by tobiasKaminsky** [comment]
I am against changing the original file...
(where is the difference if the file is on sdcard or not?)

**Comment by mario** [comment]
I'm not for changing the original file, just passing in the lowercase extension to other apps where needed :)

The difference is that SDCards are usually formatted with case-insensitive filesystems, while internal storages are mostoften formatted with case-sensitive filesystems.

**Comment by tobiasKaminsky** [comment]
This is handled via Uri and ContentResolver, I am unsure if we can change it to lower case.
Additionally, the reporter of this issue is using a nexus 5x without sdcard

**Comment by tobiasKaminsky** [comment]
@subesokun please open this issue on the receiving apps as this is not the fault of the sending app.
You can of course link to this issue and if there is a chance we can help solving this, just let us know.
