### ISSUE TITLE
100% to 0% battery within one hour if nextcloud unable to connect to server

### ISSUE THREAD

**Issue by thinkloop** [nextcloud/android#10091]
### Steps to reproduce
1. Connect to nextcloud on local wifi using internal hostname
2. Set some folders to backup when on wifi
3. Go to foreign wifi that cannot access the internal hostname (fail to connect)

### Expected behaviour
- Nextcloud should fail to connect gracefully backing off attempts or similar

### Actual behaviour
- Battery dies within an hour
- phone runs very hot
- seems stuck in a loop using as many resources as possible

### Can you reproduce this problem on https://try.nextcloud.com?
did not try

### Environment data
Android version: 11

Device model: OnePlus 7 Pro

Stock or customized system: Oxygen OS 11.0.6.1.GM21AA

Nextcloud app version: Android App 3.19.1

Nextcloud server version: Snap 20.0.3snap1

Reverse proxy: no

**Comment by AlvaroBrey** [comment]
Should be partially fixed by #10996 but more research is needed

**Comment by joshtrichards** [comment]
Hi @thinkloop - The fix was merged in v3.23.0. Are you still experiencing this issue?
