### ISSUE TITLE
Beta  20160621 - Behaviour

### ISSUE THREAD

**Issue by hitam4450** [nextcloud/android#101]
Hi Andy,
enclosed you'll find some details about a first, quick testrun!

On ANDROID 4.4.2 I do have the following issues:

  Mixed language (English, German) menu Description
  Does not show ALL Files, not even after refreshing
  Selecting Storage path:    Selecting External SD Card    Error while migrating

regards, hitam4450

PS. After selecting ALL Files in the (left side) menu panel, I could see & access ALL Files!

**Comment by AndyScherzinger** [comment]
CC @przybylski and @tobiasKaminsky 

The mixed language is simply due to the fact that English is the fallback so all features not being part of the upcoming stable release haven't been translated yet.

**Comment by hitam4450** [comment]
I like the app. e.g. moved a large number of images from SofortUpload to other folders ! With Multi Select feature, this is very easy and nice, since the number of files left are displayed and updated after each finished move! 

Very nice, very user friendly!

Keep on Going NEXTCLOUD!

Regards, hitam4450

PS. Please notify me, if there is an updated beta version available! i am glad to help and test!

Regards, hitam4450

**Comment by przybylski** [comment]
Changing storage path is a complicated process and even though I tried to handle all exceptions some are displayed as "Error while migrating", those are errors which requires more insight in moving process.
Are you able to provide logs for this migration session?

**Comment by hitam4450** [comment]
The problem as described is due to the ANDROID 4.4.2 bug - writing on external devices.

I installed the beat on an ANDROID 5.0.2 device (Galaxy Tab S 8.4) selecting the Ext-SD-Card was easy and without any complaints!

regards, hitam4450

**Comment by AndyScherzinger** [comment]
@hitam4450 thanks for the update. The latest beta is from 8th Aug. Can you reproduce the "Selecting Storage path: Selecting External SD Card Error while migrating" issue and send post the log from the app here (basically clean it before, reproduce the error, post the then created log). That would help us a lot to get a hold of this.

Thanks! Andy

**Comment by fhempeter** [comment]
Hi Andy, I hit the same issue - writing to SDcard on Android 4.4.2 and I sent in the logs. Anyting else I can do to help ? Would be great to get this working. Regards Peter

**Comment by AndyScherzinger** [comment]
Hi @fhempeter not at the moment I think, will have to wait for @tobiasKaminsky since he is the one receiving the logs :)

**Comment by tobiasKaminsky** [comment]
@fhempeter sorry for coming back so late, is this issue still a problem?

**Comment by tobiasKaminsky** [comment]
No response within the last month, therefore closing.
Please feel free to reopen with additional infos, if the problem still exists.
