### ISSUE TITLE
Cannot connect with space in login on 3.20.0

### ISSUE THREAD

**Issue by JujuBickoille** [nextcloud/android#10170]
### Steps to reproduce
1. Install 3.20.0
2. Have a space in login
3. You can't connect " server unavailable" 
Exactly same as #9331 on version 3.18.0
### Expected behaviour
- Tell us what should happen
If I use other account without space, it work, if I downgrade apk, it work too

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AlvaroBrey** [comment]
Thanks for the report @JujuBickoille, fix is up in the linked PR. We'll get it merged for next release

**Comment by JujuBickoille** [comment]
> 

Thank you so much @AlvaroBrey and NC's team ! :]
