### ISSUE TITLE
Contacts restore option in newer phone not available

### ISSUE THREAD

**Issue by imjarp** [nextcloud/android#1018]
### Actual behaviour
-The user with device "X" select the option backup contacts, then the same user with the same account opens the app in device 'Y', the restore option is not showing

### Expected behaviour
-When a user moves from device X to Y expects to restore contacts.
*Maybe the option `Last backup` its ok to see it as `never` because this configuration belongs to the current device. 
**Edit: It works if i browse in the `/.Contacts-Backup/` folder  

### Steps to reproduce
1. From device X select the option backup contacts
2. From device Y open the backup activity, restore option is not available

### Environment data
Android version: 7.0 | 6.0

Device model:  Huawei P10 | LG-H542 

Stock or customized system:

Nextcloud app version:1.4.2 both

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Good finding!
I have enhanced it in the way, that always a refresh of this folder is done.
Additionally if you select a file that is not downloaded, this will also handled correctly.

**Comment by mario** [comment]
Should be solved.
