### ISSUE TITLE
Feature request: Select "ALL" Files within a folder

### ISSUE THREAD

**Issue by hitam4450** [nextcloud/android#102]
Feature request:

Select "ALL" files within a folder for file operation e.g. copy, move, delete, etc.

regards, hitam4450

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky @jancborchardt what do you think? Imho makes sense. We do have the (de-)select all menu item for the upload file listing but it would also make sense to have this in the regular file listing. We do have multi select action, but in case you want to select all files (and folders?) within one folder you need to click though all files...

**Comment by tobiasKaminsky** [comment]
Yeah, great idea and should not be hard to implement.
Only question: should we show this as an icon, directly visible? Or put it in the overflow menu?

**Comment by AndyScherzinger** [comment]
Waiting for feedback from the @nextcloud/designers / Jan. Since we started putting everythin into the overflow menu and also put (de)select-all into the overflow menu for the upload screen I think we should put it in the overflow menu.

Remaining question is: Should the select-all then also select the folders or just files?

**Comment by tobiasKaminsky** [comment]
cc @jancborchardt @eppfel

**Comment by eppfel** [comment]
Select-all: Select-**all**
overflow-menu: 👍 

Go for it!

**Comment by Hanzei** [comment]
I think the overflow-menu is already quite overloaded. At the moment it contains 10 items. I propose to add a select-all icon to the top bar, if one file or folder got selected. We can use the standart material design icon for select-all ![icon](https://storage.googleapis.com/material-icons/external-assets/v4/icons/svg/ic_select_all_black_24px.svg)

**Comment by AndyScherzinger** [comment]
@Hanzei the Designers decided that all menu items have to be in the overflow menu and are never displayed as icons in the toolbar.

**Comment by mario** [comment]
I'd prefer a select-all icon as well, but oh well...

**Comment by AndyScherzinger** [comment]
Well, we had this exact logic (even with icon animation) and it is implemented like that for contacts at the moment. I'd say we could show it since it is not the "normal" selection action not an action triggered for the selected items ;)

What do you think @jancborchardt @eppfel

**Comment by tobiasKaminsky** [comment]
In ContactList this is because it is the one and only option, which makes an overflow menu useless I think.

**Comment by eppfel** [comment]
The dogma to put everything without exception into the overflow should have this limit, but the exception has to be well thought through. I question that select-all is used often enough to justify this much prominence, but I the overflow menu is becoming crammed indeed.

**Comment by jancborchardt** [comment]
Closing as this has been implemented. Will open an issue about cleaning up the overflow menu separately.
