### ISSUE TITLE
Speed up up drone by disabling emulator as no tests are run

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#1022]
Currently we do not run any test on the emulator or did I overlooked something?
Therefore we now could disable the whole emulator stuff and "just" build?

**Comment by AndyScherzinger** [comment]
:+1: Agreed :)

**Comment by tobiasKaminsky** [comment]
@mario also d'accord?

**Comment by mario** [comment]
Well .... do it.
