### ISSUE TITLE
Wrong user indication for activities (groupfolders)

### ISSUE THREAD

**Issue by XueSheng-GIT** [nextcloud/android#10237]
### Steps to reproduce
1. Create a groupfolder
2. Create a markdown file within the groupfolder
3. Edit this markdown file within nextcloud android app

### Expected behaviour
- Activity stream of the file should indicate which user did edit the file

### Actual behaviour
- Activity stream does show "remote user" instead of the actual user who edited the file:
- Editing the same file in the webif does show the correct user who edited the file!
- Related to the following issue? https://github.com/nextcloud/android/issues/10234

![Groupfolder_activity_user_2022-05-12](https://user-images.githubusercontent.com/4077683/168096983-4d5ebdff-4d95-4ff1-8f13-bd855f571ab2.PNG)

### Can you reproduce this problem on https://try.nextcloud.com?
- imho this issue can't be tested on try.nextcloud.com

### Environment data
Android version: 10

Device model: Huawei Mate 40 Pro

Stock or customized system: stock

Nextcloud app version: 3.20.1

Nextcloud server version: 24.0.0

Reverse proxy: yes (nginx)

### Logs
No logs available

**Comment by mjanssens** [comment]
Hi, I noticed the same. NC 24.0.1. app 3.20.1 (f-droid).
But not using groupfolders, it happens in a regular folder.
Also this seems related to editing text files, inside the android app.
Editing an .odt file with collabora online server from within the android app gives activity stream messages for the actual user.
Also renaming the file gives the right messages.
Editing .txt or .md files gives "remote user" message.
Creating an .md file (text file) inside the android app gives right message, but typing some text in the new opened file gives "remote user".

**Comment by Jerome-Herbinet** [comment]
> Hi, I noticed the same. NC 24.0.1. app 3.20.1 (f-droid).
> But not using groupfolders, it happens in a regular folder.
> Also this seems related to editing text files, inside the android app.
> Editing an .odt file with collabora online server from within the android app gives activity stream messages for the actual user.
> Also renaming the file gives the right messages.
> Editing .txt or .md files gives "remote user" message.
> Creating an .md file (text file) inside the android app gives right message, but typing some text in the new opened file gives "remote user".

Same for me.
