### ISSUE TITLE
Nextcloud on Android 12 doesn't show app in file manager

### ISSUE THREAD

**Issue by EasyNetDev** [nextcloud/android#10249]
### Steps to reproduce
1. Install Nextcloud Android
2. Login
3. Go to an app like KeePassDX and tap on "open an existing database" 
4. In the list of "open from" or "browse files on other apps" there is no Nextcloud. 

### Expected behaviour
- on my wife's OnePlus 7 with Android 11 I can find this option using the same steps. 

### Actual behaviour
- no nextcloud app in file browser 

### Environment data
Android version: 12

Device model: OnePlus 8

Stock or customized system: Stock

Nextcloud app version: 3.20.1

Nextcloud server version: 23.0.3

Reverse proxy: no

#### Web server error log
```
N/A
```

#### Nextcloud log (data/nextcloud.log)
```
N/A
```

**Comment by AlvaroBrey** [comment]
Duplicate of #9906

**Comment by EasyNetDev** [comment]
Hi,

Here is the issue I'm taking about.
1. OnePlus 7 with Android 11
![IMG_20220516_120829](https://user-images.githubusercontent.com/1823016/168579426-80b96ec0-b28b-4af3-88ca-8f912c0a8fda.jpg)
2. OnePlus 8 with Android 12
![IMG_20220516_120205](https://user-images.githubusercontent.com/1823016/168579679-ca5547c4-4878-4b5b-bf69-e3d3fa803aeb.jpg)

**Comment by EasyNetDev** [comment]
I think Nextcloud client doesn't register itself as a share drive in the Android 12 OS.

**Comment by mrleerkotte** [comment]
Experiencing some problem on S22 Ultra, Android 12

**Comment by mitohund** [comment]
I've had this issue with both Android 11 and Android 12 on my OnePlus 7. The solution ended up being completely unintuitive, but super easy: set "App passcode" to "None" in the Nextcloud Android app settings.

Credits due [here](https://www.reddit.com/r/NextCloud/comments/d83ksd/comment/iw8pvqw/?utm_source=reddit&utm_medium=web2x&context=3).

In a way, this makes sense. If you turn passcode on, it means you don't want other potential phone users to access your files. So access is also blocked via the file manager.

Maybe a simple info line underneath "App passcode" options would suffice to make life a lot easier for a lot of people (I have found discussions on this in many places).

**Comment by PhilippHomann** [comment]
I've tried the same with the Dropbox app, which results in the same.
So I think this is nothing that can be fixed 
Maybe there should be a hint in the settings dialog.

**Comment by EasyNetDev** [comment]
I notice something interesting. After I uninstalled Nextcloud Android Client and reinstall it I saw that Nextcloud shows in File Manager.

![Screenshot_2023-03-08-20-47-14-92_5734e8eb49b4234b62f913f831715b0f](https://user-images.githubusercontent.com/1823016/223828962-b014cc81-07b5-437c-b780-e05f9220aa84.jpg)

Now I can use my keepass file directly from Nextcloud and all changes are uploaded by default in my cloud.

**Comment by AlvaroBrey** [comment]
@EasyNetDev does your experience match what the above commenters are saying?  (visible only if passcode is NOT enabled)

**Comment by EasyNetDev** [comment]
Hi @AlvaroBrey ,

Indeed. I tested with pass code and it was removed from File Manager. After I disabled the pass code the app appears in File Manager. So simple solution but undocumented.

Thanks.

**Comment by Minos2020** [comment]
@mitohund Damn thank you so much !! 🙏
Had the exact same issue and you definitely saved me a lot of time.
When you know it's quite logical but it really should be mentioned somewhere indeed...
