### ISSUE TITLE
Switch to new dav / enhance chunked uploading

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#1026]
Currently we are storing successful uploaded chunks client side.
This can now be enhanced to reduce client code:

- use new dav:  /dav/uploads/userx/<YOURRANDOMID>/
- list shows already uploaded chunks
  - iterate over them and check file size, if chunk is completely uploaded
- upload (remaining) chunks
- move from /dav/uploads/userx/<YOURRANDOMID>/.file to /dav/files/userx/<PATH>

**Comment by rullzer** [comment]
:+1: 
I would suggest first that you move to the new webdav endpoint for all file related stuff. And then start with this.
