### ISSUE TITLE
Some bugs with end-to-end encryption

### ISSUE THREAD

**Issue by PoisonFrog** [nextcloud/android#10291]
I have been trying the Android app with an old phone and ran into 2 bugs. My phone is very old and running LineageOS so maybe it is an issue with my phone, but I do not have another Android phone to test it.

### 1) Trying to upload to an encrypted subfolder using the "Share" mechanism makes Nextcloud client crash.

> Steps to reproduce
1. Go to any app or the web
2. Select any media and use the Share function
3. Select Nextcloud, go to your encrypted folder then try to go to a subfolder of the encrypted folder.

> Expected behaviour

Being able to enter the subfolder and upload the content.

> Actual behaviour

When using any application and trying to share content I select Nextcloud and go to my end-to-end encrypted folder. If I upload to the encrypted root folder there are no issues, but if I tap a subfolder of the encrypted root the app crashes.

### 2) Nextcloud having issues to write to end-to-end encrypted folder.

Even though uploading content to the encrypted root usually works with the Share mechanism when I tried using KeePassDX witth a database in the encrypted root folder I was able to open the database but the app was not successful at uploading the changes I made on the Android phone.

> Steps to reproduce
1. Store a database in the encrypted folder
2. Open it on KeePassDX and make changes to the database
3. Save the changes

> Expected behaviour

Being able to synchronize database changes like I can outside the end-to-end encrypted folder.

> Actual behaviour

Nextcloud Android client app fails to upload changes if the database is inside the encrypted folder.

__________________________

**Android version:**
Android 10

**Stock or customized system:**
LineageOS

**Nextcloud app version:**
Latest from F-Droid

**Nextcloud server version:** 
Latest from stable repos (Nextcloud 23.0.5, Ubuntu 20.04 server)

**Comment by Dingsd4** [comment]
Same problem here:
1) NextCloud Server updated to 25.0.2
2) E2EE activated
3) Folder encrypted with windows client
4) Folder is seen and can be accessed on other windows clients (after setting up the passphrase)
5) Folder is seen in Android (3.23.1) but cannot be accessed. 
  Error message (german): **Ende-zu-Ende Verschlüsselung ist auf diesem Server deaktiviert.**

I assume the android client does not detect the active E2EE.

**Comment by joshtrichards** [comment]
The E2E code base has had significant changes made to it since this report. Are you still experiencing one or both of these matters?
