### ISSUE TITLE
Beta 20160621 - (Sub)-Option missing

### ISSUE THREAD

**Issue by hitam4450** [nextcloud/android#103]
Hi to Andy and ALL,

Below  the Option **Immediate Upload**  (SofortUpload).
I miss the Sub-option 

Use Subfolders
_Store in subfolders based on year and month_

as being offered in the published Version 1.1!

I think this is a pretty neat feature to better organize the "sometimes huge number " of Uploads!

regards, hitam4450

**Comment by tobiasKaminsky** [comment]
Yeah, beta is currently out of sync as there are too many changes :/
I hope to get a real beta update soon.

**Comment by tobiasKaminsky** [comment]
@hitam4450 please upgrade. 
Now your desired feature and much more is available.
