### ISSUE TITLE
Broken link to "create bug report"

### ISSUE THREAD

**Issue by topo03** [nextcloud/android#10337]
### Steps to reproduce
1. In Nextcloud app go to community
2. Tap button "create bug report"

### Expected behaviour
- Open correct website on GitHub

### Actual behaviour
- Blank page with error "can't load this page"

### Environment data
Android version: 12

Device model: Samsung Galaxy S22

Stock or customized system: stock

Nextcloud app version: 3.20.1

Nextcloud server version: 23

Reverse proxy: no

**Comment by AlvaroBrey** [comment]
Thanks @topo03 !
