### ISSUE TITLE
Auto upload only on certain wifi networks

### ISSUE THREAD

**Issue by johnnyasantoss** [nextcloud/android#10342]
### Is your feature request related to a problem? Please describe.
Yes. I have my Nextcloud instance running privately on my home network, so it is not acessible everywhere. I want it to dump all my documents when I get home and put my phone to charge.

### Describe the solution you'd like
Have a global option for auto upload to only upload docs when connected to a configurable network (wifi name)

### Describe alternatives you've considered
None.

**Comment by AlvaroBrey** [comment]
Duplicate of #8481, thanks @tribut
