### ISSUE TITLE
directory overlay pictures

### ISSUE THREAD

**Issue by koebi80** [nextcloud/android#10340]
### Steps to reproduce
1. Add group directories
1. Connect to an NextCloud Server
2. Change Design Color on the NextCloud Server
3. overlay pictures are gone

### Expected behaviour
- Only the color of the directory symbol must change. The overlay pictures should still be displayed in white.

### Actual behaviour
- After changing the design color all directory overlay picture are no longer displayed.

### Can you reproduce this problem on https://try.nextcloud.com?
- No. There it is not possible to change the color of the design

### Environment data
Android version: 
9

Device model:
GT-I9195

Stock or customized system:
customized (lineageos)

Nextcloud app version:
3.20.1

Nextcloud server version:
24.0.1

**Comment by AlvaroBrey** [comment]
@koebi80 can you specify what you mean by "overlay pictures"? Attach comparison screenshots if possible (feel free to blur names)

**Comment by XueSheng-GIT** [comment]
Same as https://github.com/nextcloud/android/issues/10234, right?

**Comment by koebi80** [comment]
Yes, I think it's the same bug.

**Comment by joshtrichards** [comment]
Duplicate of #10234 (and since fixed)
