### ISSUE TITLE
FR: Deck integration

### ISSUE THREAD

**Issue by JSoko** [nextcloud/android#1036]
Feature request:
IMHO Deck https://github.com/nextcloud/deck seams to become a great peace of software.
AFAIK, the developer is integrating an api at the moment...
...especialy if you could handle your decks offline.

So will there be a chance in future to integrate deck into the Nextcloud-App?

Would be a great feature...

**Comment by tobiasKaminsky** [comment]
I would rather create a new app for this and use our authenticator to directly access the nc server without entering the credentials over and over.
This has the benefit that the current app stays somehow "small".

**Comment by raxetul** [comment]
I think Android app can be switched into an Android Instant App to support features like these can be imported as plugin like structure.
Instant apps can be in a single managed nextcloud address so that security would not be a problem.

**Comment by jakobroehrl** [comment]
This Issue could be closed since there is a deck Android App (alpha state):
https://f-droid.org/de/packages/it.niedermann.nextcloud.deck/
