### ISSUE TITLE
Crashed for some reason when opening the app

### ISSUE THREAD

**Issue by stillie** [nextcloud/android#10369]
### Steps to reproduce
1. Opened the app? 
2. 
3. 

### Expected behaviour
- Tell us what should happen
App should open 🤣

### Actual behaviour
- Tell us what happens
App doesn't open 🤣

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AlvaroBrey** [comment]
Hello and thanks for taking the time to report a bug.  However more information is required; please fill in the "Environment data" section and then reply so I can reopen this issue.

**Comment by stillie** [comment]
Cleared app data and it sorted the issue out
