### ISSUE TITLE
Auto Upload with Use Subfolders: Add options for how to organize files

### ISSUE THREAD

**Issue by duanenewman** [nextcloud/android#10374]
### Is your feature request related to a problem? Please describe.
I can either auto-upload my camera roll to a single folder or break it out with the "Use Subfolders" option to add Year/Month folders. The problem for my use case is that not using subfolders creates too much volume in a single folder, but taking it to the month level makes using the android gallery app a little painful as over time I end up with several folders listed for each month (i.e. if I have files from 2019-2022 I end up with 4 folders named "06" in my gallery and no way of knowing which one is june 2022 without looking).

### Describe the solution you'd like
I would like "Use subfolders" change from a checkbox to a dropdown with the options:
* No
* Yes - stored based on year
* Yes - stored based on year and month

`No` would match the current unchecked state
`Yes - stored based on year and month` would match the current checked state

### Describe alternatives you've considered
Currently to solve this I have to at some point (usually the end of the year) move my files on nextcloud server from all the month folders up to the year folder and then wait for my phone to sync all these changes, this works, but is not ideal as I really don't care to see the files split by month, and if I do there are other views to achieve this. 

### Additional context
While I can use the gallery app and just go to the "pictures" tab to view them all sorted by date this is inconvenient because 1) it includes images downloaded by apps or things such as screenshots which clutter what I'm looking for and 2) using an app like facebook or instagram only lets you view by folder, so only have the option of checking each matching month folder until I find the correct one.

**Comment by joshtrichards** [comment]
Fixed in #11852
