### ISSUE TITLE
unnecessary and confusing content-descriptions in file activity

### ISSUE THREAD

**Issue by henningoschwald** [nextcloud/android#1037]
### Actual behaviour
In the main file and folder activity, every file or folder name has a contend description set which prepends the layout type to the file name. For example if you have a file named testfile.txt in your Nextcloud, the contend-description for this entry is "LinearLayout-testfile..txt".

The purpose of content-descriptions is to add text descriptions for graphical UI elements such as image buttons. This information is then used e.g. by screen readers such as Talkback which enables blind or visually impaired users to work with the app by utilizing text-to-speech or braille displays.

When using the Nextcloud app together with Talkback, talkback reads the content description instead of the visible file name as described above, which is quite annoying and confusing. 

Since file and folder names consist of text, there is no need for them to have content-descriptions at all. Funny enough, there are also graphical buttons in the same activity i.e. to create a new folder, which are graphical only and would need contend-descriptions to be announced in a meaningful way, but don't have them set. I will however open a separate issue for this.

I am not a Java coder, but by looking into the code it seems to me the content-descriptions have been set mainly to use them in automation testing, not considering end users also see this information in some cases.

### Expected behaviour
Content-descriptions should only be set where needed to add textual descriptions for graphical elements. Furthermore the contained information must be valuable and informative to the end user.

### Steps to reproduce
Either use debugging tools to view the content-descriptions or enable Talkback from the assistive technologies screen in the global android settings and try to navigate the Nextcloud app. Be warned however talkback changes the touchscreen behaviour, which is confusing for sighted persons. When touching an element, no action is performed, instead the touched element is beeing read via text-to-speech. To actually trigger the focussed element, you need to double-tab it.

### Environment data
Android version: all supported versions

Device model: BQ Aquaris X5 Plus

Stock or customized system: stock Android 7.1.1

Nextcloud app version: 1.4.3

Nextcloud server version: 12.0

**Comment by henningoschwald** [comment]
I've now installed the development build 20170524 and found the weird contend-descriptions in file and folder names are gone, so there is almost no reason to keep this issue open. Additionally now also the file size is shown, which is really cool! The only odd description I found so far is the one set in src/main/res/layout/files.xml, that one should also be removed.

Looking forward to the stable release. Thanks so much for all your work!

**Comment by tobiasKaminsky** [comment]
It would be great when you can give us some more infos what we should enhance to get it work better with talkBack or other accessibility programs.

**Comment by jancborchardt** [comment]
@henningoschwald I also opened a new issue about testing with TalkBack at https://github.com/nextcloud/android/issues/2780, your input is appreciated :)

**Comment by AndyScherzinger** [comment]
@jancborchardt should this issue that be closed and would be superseded by your issue or is this a separate aspect not covered by your new issue?
