### ISSUE TITLE
Autoupload configuration page loads indefinitely

### ISSUE THREAD

**Issue by ThaChillera** [nextcloud/android#10375]
### Steps to reproduce
1. Configure a fresh autoupload folder with lots of files
2. While uploading, try to open the autoupload settings page
3. settings load take forever, phone gets very hot

### Expected behaviour
- Settings should just load
- 
### Actual behaviour
- Loading takes forever

### Environment data
Android version: 11

Device model: Fairphone 3+

Stock or customized system: LineageOS MicroG

Nextcloud app version: 3.20.1

Nextcloud server version: 24.0.1

Reverse proxy: nginx

**Comment by ThaChillera** [comment]
Update/correction: I got through the autoupload queue, but this issue still persists. I attached a debugger but didn't see any log lines that looked relevant

**Comment by ThaChillera** [comment]
I'm still experiencing this issue, 2 months later! any tips/info?

**Comment by ThaChillera** [comment]
Update: reset the app, configured auto upload again, issue still exists.

**Comment by moritzgloeckl** [comment]
I'm having the same issues would be glad if there was a solution! It seems though that auto sync is working in the background.

**Comment by joshtrichards** [comment]
> Configure a fresh autoupload folder with lots of files

How, precisely, did you configure it? There are numerous option combinations. Knowing this is important for reproducibility and bug triaging. Thanks!

Oh, and what do you mean by "lots"? 100, 1000, 10000? Etc.

Also, a log would still be helpful (either from inside a Dev version of the app under *Settings->Logs* or via LogCat with a standard version of the app).

Feel free to redact using search & replace as needed.
