### ISSUE TITLE
Saving contacts to nextcloud from Google Contacts app

### ISSUE THREAD

**Issue by 2PieceCombo** [nextcloud/android#10409]
When creating contacts on android via the Google Contacts app, you are able to select nextcloud accounts directly as a save location. These contacts do not actually show up in nextcloud, but rather seem to be stored on the phone directly.

I have the default contacts app as well as Google Contacts app installed on my phone. Lets say I wanted to add a new contact via the default app, I would chose where to save the contact (SIM/Phone/google accounts/etc) and I would select the DAVx5 account associated with my nextcloud account. It creates the contact and I can then see it in nextcloud.

Now lets say I wanted to add a contact via the google contacts app. When selecting where to save it, it shows the DAVx5 option, as well as the nextcloud account directly. If I chose DAVx5, it creates the contact as normal, and I can see it's been created in Nextcloud. But if I chose to save the contact to the nextcloud account, it does NOT show up in nextcloud. If I go back to the default contact app and view the contact, it shows that it is saved directly on the phone.

As I understand it, the Android NC app has no direct way to interact with contacts, which is why DAVx5 is required. So why is the nextcloud account showing up as a valid place to save contacts? Is this the fault of the NC app? Or google contacts app?

**Comment by joshtrichards** [comment]
I cannot replicate this behavior. Can you provide a screenshot where the Nextcloud app/account shows up directly by chance?
