### ISSUE TITLE
Fix lint config for drone CI builds

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#1040]
At the moment drone doesn't pick up a lint config:

> Warning: Configuration file /drone/src/github.com/*****/android/lint.xml does not exist

**Comment by tobiasKaminsky** [comment]
Yes, it just uses the default one, which is fine enough.
You probably only need a custom lint.xml if you want to disable specif tests.

**Comment by tobiasKaminsky** [comment]
there was once upon a time a lint.xml in https://github.com/nextcloud/android/blob/f1465210f01482304141f57d0bb88a0336630679/lint.xml which was empty...

**Comment by mario** [comment]
The issue is that build fails without it...

**Comment by tobiasKaminsky** [comment]
When and where?
https://drone.nextcloud.com/nextcloud/android/4634/3 has the warning about missing lint.xml, but drone built fine.
