### ISSUE TITLE
This image cannot be shown

### ISSUE THREAD

**Issue by duckulaj** [nextcloud/android#1044]
### Actual behaviour
Clicking on a photo displays black screen with warning triangle with caption This image cannot be shown 

### Expected behaviour
Display the photograph
 
### Steps to reproduce
1. Click on an image to view
2. 
3. 

### Environment data
Android version:
7.0
Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
closed as duplicate of #1045
