### ISSUE TITLE
No autouploads anymore

### ISSUE THREAD

**Issue by N8schatten** [nextcloud/android#10442]
### Steps to reproduce
1. Folder for autoupload for photos
2. (Manuel uploads working fine)
3. 

### Expected behaviour
Taken photos should be autoupload to server

### Actual behaviour
No autouploads since two month.

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 10

Device model: samsung s9

Stock or customized system: no

Nextcloud app version:3.20.3

Nextcloud server version: 24.0.2

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AlvaroBrey** [comment]
Duplicate of https://github.com/nextcloud/android/issues/10200
