### ISSUE TITLE
Can't get to install properly with my Android phone 

### ISSUE THREAD

**Issue by nmuniz66** [nextcloud/android#10451]

**Comment by AlvaroBrey** [comment]
Hello and thanks for taking the time to report a bug.  However more information is required; please fill in the [issue template](https://github.com/nextcloud/android/issues/new?assignees=&labels=bug&template=bug_report.md) with a description of the error, version info, and steps to reproduce, and reopen this issue when that's done. 

Please also make sure that the issue title is descriptive of the issue and not just "Bug" or "Crash" or similar.

Thank you!
