### ISSUE TITLE
Other apps cannot use the nextcloud account [FP4]

### ISSUE THREAD

**Issue by codeling** [nextcloud/android#10456]
### Steps to reproduce

1. Install nextcloud client app on an android device
2. Set up account connection to (self-hotsed) server with "alternative authentification via app token"
3. Install another nextcloud app (notes / news) on same device
4. Select the existing account

### Expected behaviour

- The other apps (notes/news) should get access to the nextcloud account

### Actual behaviour

- There is a very strange error message (german android - my own attempted translation in parenthesis):
  - Title: Benötigt keine Übersetzung. Für Android wird nur die formelle Über... (my translation: Does not need translation. For android only the formal trans...)
  - Message: Benötigt keine Übersetzung. Hier wird nur die formelle Übersetzung verwendet (de_DE). https://play.google.com/store/apps/details?id=com.nextcloud.client (my translation: Does not need translation. Here only the formal translation is used (de_DE). ...)
  -  pop-up notification below: attempt to invoke vitual method 'java.lang.String anrdoid.content.Intent.getStringExtra(java.lang.String)' on a null object reference

### Can you reproduce this problem on https://try.nextcloud.com?

Yes, same issue.

### Environment data

Android version: 11
Device model: Fairphone 4
Stock or customized system: Stock
Nextcloud app version: 20220421 (nextcloud news: 0.9.9.74; nextcloud notes: 3.5.00)
Nextcloud server version: 24.0.2
Reverse proxy: no

#### Web server error log
Nothing relevant (no entries at all in the days where this was tried).

#### Nextcloud log (data/nextcloud.log)
Nothing relevant as far as I could see

### Other things
- I have searched in the notes android app issue tracker and here, but haven't found an issue with a similar description; sorry if I've missed a relevant one, then I'd be glad if someone could point me in the right direction!
- With news app, I can set up an alternate account (i.e., not use the nextcloud app account, but set up a separate account from within the news app); for the notes app, this doesn't work, the app tells me that there already is an account for this server and username; which means that the notes app is unusable
- I've tried to clear memory (cache + other) of nextcloud and nextcloud notes app, [as mentioned in the android notes app FAQ](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/FAQ.md#nextcloudapinotrespondingexception), and tried to set them up again - same issue.

**Comment by AlvaroBrey** [comment]
Can't reproduce this; I've just successfully logged into a Notes app without any problem. This points to some sort of device-specific problem.  Can you get a logcat from your device? [Instructions here](https://github.com/nextcloud/android#getting-debug-info-via-logcat-mag)

**Comment by codeling** [comment]
I tried with the LogCat app from f-droid (works with local network adb connection); it shows the following messages (filtered for containing 'nextcloud'):
```
07-01 08:02:52.152 D/AccountChooser(24121): selected account Account {name=myaccount@mycloud.info, type=nextcloud}
07-01 08:02:52.200 I/ActivityTaskManager( 1352): START u0 {cmp=com.nextcloud.client/com.owncloud.android.ui.activity.SsoGrantPermissionActivity (has extras)} from uid 10213
07-01 08:02:52.282 E/com.nextcloud.android.sso.AccountImporter(26709): Attempt to invoke virtual method 'java.lang.String android.content.Intent.getStringExtra(java.lang.String)' on a null object reference
07-01 08:02:58.189 I/ResolverListAdapter(24121): Add DisplayResolveInfo component: ComponentInfo{com.nextcloud.android.beta/com.owncloud.android.ui.activity.ReceiveExternalFilesActivity}, intent component: ComponentInfo{com.nextcloud.android.beta/com.owncloud.android.ui.activity.ReceiveExternalFilesActivity}
07-01 08:05:53.984 E/ClipboardService( 1352): Denying clipboard access to com.nextcloud.android.beta, application is not in focus nor is it a system service for user 0
```
I have all nextcloud-related apps installed via f-droid, if that is relevant.

While checking above messages I noticed the 'beta' - seems I accidentally installed the dev version! I'll try again with the stable one, thanks for the help!

**Comment by codeling** [comment]
With the non-dev version it works! Thanks for the support!
