### ISSUE TITLE
Creating a new document on satellite internet results in a crash

### ISSUE THREAD

**Issue by DetroitLibertyPenguin** [nextcloud/android#10466]
### Steps to reproduce
1. Launch nc
2. Select create new dic
3. Wait

### Expected behaviour
- new doc created 

### Actual behaviour
- crash

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:stock

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AlvaroBrey** [comment]
@DetroitLibertyPenguin can you reproduce this reliably? Additionally, please fill the version info in the template.

**Comment by DetroitLibertyPenguin** [comment]
Greetings,

I'm certainly able to reproduce this week. I haven't bene able to even
successfully connect to try.nextcloud. Currently I'm staying at my
mother-in-laws home in Bennington, OK. Out  here internet speeds aren't
what we expect in the city. The only option they have is satellite
internet. According to speedtest she's getting around 2.0 mb/s download and
0.04 mb/s upload. I'm guessing that much of this is related to timeout on
the server.

If my conjecture is accurate, do timeouts rely within the Nextcloud
software, or is this something configurable on the server end and I should
contact the admin of my instance @ libranet.de


Jim Fulner
22100 Armada Ridge Rd.,
Armada, MI 48005-3204
(P) 248-971-0259
(M) 248-765-7458
(H) 586-473-7007

Telephony eliminates confusion

**Comment by strugee** [comment]
@DetroitLibertyPenguin when the app crashes, it _should_ show a crash screen with a lot of debugging information. Can you please copy and paste that information into this ticket?
