### ISSUE TITLE
Dev version and stable version can't be concurrently installed due to conflicting provider name

### ISSUE THREAD

**Issue by strugee** [nextcloud/android#10477]
### Steps to reproduce
1. Have Nextcloud dev 20220216 installed from F-Droid
2. Have Nextcloud stable 3.20.3 installed from Google Play
3. Try to upgrade to either Nextcloud dev 20220421 or 20220629 (these are the only two versions available after 20220216 due to https://gitlab.com/fdroid/fdroiddata/-/issues/2707)

### Expected behaviour

The install should work

### Actual behaviour

The install fails with an "unknown error". `adb logcat` reveals this exception:

```
07-04 16:11:52.091  1014  1046 I ActivityManager: Force stopping com.nextcloud.android.beta appid=10252 user=-1: installPackageLI
07-04 16:11:52.092  1014  1046 I ActivityManager: Killing 8158:com.nextcloud.android.beta/u0a252 (adj 700): stop com.nextcloud.android.beta due to installPackageLI
07-04 16:11:52.094  1014  1077 W PackageManager: Scanning Failed.
07-04 16:11:52.094  1014  1077 W PackageManager: com.android.server.pm.PackageManagerException: Can't install because provider name org.nextcloud (in package com.nextcloud.android.beta) is already used by com.nextcloud.client
07-04 16:11:52.094  1014  1077 W PackageManager: 	at com.android.server.pm.ComponentResolver.assertProvidersNotDefinedLocked(ComponentResolver.java:1172)
07-04 16:11:52.094  1014  1077 W PackageManager: 	at com.android.server.pm.ComponentResolver.assertProvidersNotDefined(ComponentResolver.java:465)
07-04 16:11:52.094  1014  1077 W PackageManager: 	at com.android.server.pm.PackageManagerService.assertPackageIsValid(PackageManagerService.java:12192)
07-04 16:11:52.094  1014  1077 W PackageManager: 	at com.android.server.pm.PackageManagerService.scanPackageNewLI(PackageManagerService.java:11123)
07-04 16:11:52.094  1014  1077 W PackageManager: 	at com.android.server.pm.PackageManagerService.scanPackageTracedLI(PackageManagerService.java:10882)
07-04 16:11:52.094  1014  1077 W PackageManager: 	at com.android.server.pm.PackageManagerService.installPackagesLI(PackageManagerService.java:16975)
07-04 16:11:52.094  1014  1077 W PackageManager: 	at com.android.server.pm.PackageManagerService.installPackagesTracedLI(PackageManagerService.java:16346)
07-04 16:11:52.094  1014  1077 W PackageManager: 	at com.android.server.pm.PackageManagerService.lambda$processInstallRequestsAsync$22$PackageManagerService(PackageManagerService.java:14512)
07-04 16:11:52.094  1014  1077 W PackageManager: 	at com.android.server.pm.-$$Lambda$PackageManagerService$9znobjOH7ab0F1jsW2oFdNipS-8.run(Unknown Source:6)
07-04 16:11:52.094  1014  1077 W PackageManager: 	at android.os.Handler.handleCallback(Handler.java:938)
07-04 16:11:52.094  1014  1077 W PackageManager: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-04 16:11:52.094  1014  1077 W PackageManager: 	at android.os.Looper.loop(Looper.java:223)
07-04 16:11:52.094  1014  1077 W PackageManager: 	at android.os.HandlerThread.run(HandlerThread.java:67)
07-04 16:11:52.094  1014  1077 W PackageManager: 	at com.android.server.ServiceThread.run(ServiceThread.java:44)
07-04 16:11:52.094  1014  1046 W ActivityTaskManager: Force removing ActivityRecord{41a91de u0 com.nextcloud.android.beta/com.owncloud.android.ui.activity.FileDisplayActivity t22171 f}}: app died, no saved state
```

### Can you reproduce this problem on https://try.nextcloud.com?

N/A

### Environment data
Android version: LineageOS 18.1-20220423-NIGHTLY-bonito based on Android 11

Device model: Pixel 3a XL

Stock or customized system: customized; LineageOS + GApps

Nextcloud app version: see STR

Nextcloud server version: N/A

Reverse proxy: N/A

### Logs

N/A; see above for the relevant exception

**Comment by AlvaroBrey** [comment]
This shouldn't happen as the dev version has a different authority (http://github.com/nextcloud/android/blob/e8d2989295041eb4087b56994deb38855e91c65a/app/src/versionDev/res/values/setup.xml#L10-L10)

Can you reproduce this by installing the dev APK built by us? https://download.nextcloud.com/android/dev/latest.apk
I can't reproduce it with this APK and the latest Google Play APK; both can be installed at the same time without issue.

**Comment by gityeti** [comment]
Hello, I think I do have the same bug.
Android 9 on Fairphone 3 
/e/ version  0.23-p-20220412177701-dev-FP3
Installed from f-droid stable version (nextcloud 3.20.3) and dev version (nextcloud 20220311). Both work perfectly.
Trying to upgrade dev version (nextcloud 20220709) doesn't work anymore, I get "unknown error".
 Logs : PackageParser
 Unknown element under <manifest>: queries at /data/user/0/org.fdroid.fdroid/cache/apks/f-droid.org--1/com.nextcloud.android.beta_20220709.apk Binary XML file line #75
 I tried to install the dev APK built by you https://download.nextcloud.com/android/dev/latest.apk, I get the same "unknown error".
 Logs : PackageParser
Unknown element under <manifest>: queries at /storage/emulated/0/Download/latest.apk Binary XML file line #81

**Comment by strugee** [comment]
Ack, sorry I never got back to this issue, but I can no longer reproduce with dev installed from F-Droid and stable installed from Google Play.
