### ISSUE TITLE
Automatic upload, no remote folder selectable

### ISSUE THREAD

**Issue by Schneehexe** [nextcloud/android#10485]
Nextcloud on Android, version "Nextcloud Android App 3.20.3".
Device Samsung S9
Android 10
Serverversion: Always fresh!

Here is the problem I would like to describe: On my mobile devices I want to synchronize the uploads per device to a separate remote auto upload directory. This means that I can't use the default directory "/SofortUpload/Camera/ " (in German), because the directories have to differ depending on the device to not lose the mappings.

So I have set up appropriate directories on the server and want to choose them. But this does not work.

Although I can see these directories in the AutoUpload > Remote Folder settings, I cannot effectively select them.

Also under the function "Create a setup for your own folder" it doesn't work - even if I actually select the local and the remote - folder.

The Issues 622, 2034, 2611, 2462, 3137, 3763, 3382, 3384 treat the problem, but do not solve it.

Moreoveer, I can say that this must have worked earlier, as it was set up and works on the other devices earlier.
A difference may be, that I used to get the App from the Playstore and now only from F-Droid.

**Comment by Schneehexe** [comment]
After switching from the stockrom to /e/OS, dialing remote directories worked - for 2 days. Since today there is the same problem again.

Except InstantUpload/.... nothing can be selected.

What is this just aggressive thing and why no one can say anything about it?

The behavior is exactly the same again!

**Comment by Schneehexe** [comment]
First, I open the Auto Upload settings for screenshots, for example.
![Screenshot_20220720-163341_Nextcloud](https://user-images.githubusercontent.com/36819426/180010761-1f58e87d-714c-4493-aa23-55e213747beb.png)

Then I select the setting for the remote folder here 
![Screenshot_20220720-163303_Nextcloud](https://user-images.githubusercontent.com/36819426/180011211-bafdd7ac-d920-422d-99a9-f9e6d282c08d.png)

Then I select the setting for the remote folder and finally the shared folder "SofortUpload-hbc63".
I then get view of the subfolders and also see "Screenshots". I select this and get back to the settings menu.
![Screenshot_20220720-163234_Nextcloud](https://user-images.githubusercontent.com/36819426/180011959-24f1d1f0-d3e6-418e-9727-f75d1508cc4e.png)

Under Remote-Folder the folder I chose was not set.
That is actually all. It just does not work.

**Comment by AlvaroBrey** [comment]
Interesting, as I said it works without problem for me. Can you get logs from the app and attach them? Info here: https://github.com/nextcloud/android#getting-debug-info-via-logcat-mag You may want to anonymize them by looking for references to your username and server URL and replacing them with placeholders.

**Comment by Schneehexe** [comment]
Thanks a lot for taking care of this problem.
I have installed the ADB and Fastboot, but I cannot use it because I get an error message.

USB debug is of course enabled and permission is granted on the device.

![image](https://user-images.githubusercontent.com/36819426/180605150-89f2ff35-c666-456d-9fe9-d9b2ddd2f4f4.png)

On the release I get the following:

![image](https://user-images.githubusercontent.com/36819426/180605214-b2004296-2994-4cd8-b26c-3d37015cb7e6.png)

Everywhere only hurdles.....

**Comment by Schneehexe** [comment]
Thanks first of all that you deal with this problem!

I have started the log and performed the procedure again.

The log says the following:

```
--------- beginning of crash
07-23 15:18:58.200 12717 12717 E AndroidRuntime: FATAL EXCEPTION: main
07-23 15:18:58.200 12717 12717 E AndroidRuntime: Process: com.nextcloud.client, PID: 12717
07-23 15:18:58.200 12717 12717 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Index: 2, Size: 0
07-23 15:18:58.200 12717 12717 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:437)
07-23 15:18:58.200 12717 12717 E AndroidRuntime: 	at com.owncloud.android.ui.adapter.SyncedFolderAdapter.get(SyncedFolderAdapter.java:200)
07-23 15:18:58.200 12717 12717 E AndroidRuntime: 	at com.owncloud.android.ui.activity.SyncedFoldersActivity.onSaveSyncedFolderPreference(SyncedFoldersActivity.kt:646)
07-23 15:18:58.200 12717 12717 E AndroidRuntime: 	at com.owncloud.android.ui.dialog.SyncedFolderPreferencesDialogFragment$OnSyncedFolderSaveClickListener.onClick(SyncedFolderPreferencesDialogFragment.java:556)
07-23 15:18:58.200 12717 12717 E AndroidRuntime: 	at android.view.View.performClick(View.java:7259)
07-23 15:18:58.200 12717 12717 E AndroidRuntime: 	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1131)
07-23 15:18:58.200 12717 12717 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7236)
07-23 15:18:58.200 12717 12717 E AndroidRuntime: 	at android.view.View.access$3600(View.java:801)
07-23 15:18:58.200 12717 12717 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:27892)
07-23 15:18:58.200 12717 12717 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
07-23 15:18:58.200 12717 12717 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
07-23 15:18:58.200 12717 12717 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
07-23 15:18:58.200 12717 12717 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
07-23 15:18:58.200 12717 12717 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-23 15:18:58.200 12717 12717 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
07-23 15:18:58.200 12717 12717 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
```

**Comment by Schneehexe** [comment]
The log is posted.
Even with version 3.21.0 the problem persists.

**Comment by Schneehexe** [comment]
Hello,

is anyone here still interested in this? There is never an answer. I can't fix this error myself.
 
At the moment, since no one cares about this bug, I'm forced to try Syncthing, which actually works fine.

**Comment by joshtrichards** [comment]
Since the remote folder you are trying to upload to  (`/SofortUpload-hbc63/Screenshots`) has the name subfolder name as the one you're trying to change here's something to try: Does it work if  the subdirectory (`Screenshots`) is instead called something like `MoreScreenshots` by chance?

**Comment by Schneehexe** [comment]
Hello again and thanks for the replies.


But the error was somewhere else. Namely in the Android mobile phone, in the developer options.

The effect I described only appears when "Do not save activities" is activated there. This setting deletes the information in the field as soon as you leave the input - that's why it is then finally no longer available for transfer.
