### ISSUE TITLE
Dialog crashes while switching dark mode

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#10488]
### Steps to reproduce
1. open a dialog (tested with SetStatusDialogFragment, GalleryFragmentBottomSheetDialog)
2. toggle dark/light mode in system settings (via notification area), so that app is still in foreground
3. see crashes

### Expected behaviour
No crash

**Comment by joshtrichards** [comment]
Fixed by #10489 

(Unless I'm mistaken; I think it just wasn't linked fully to this issue when it got merged to auto-close it)
