### ISSUE TITLE
German translation (just German descreption inside)

### ISSUE THREAD

**Issue by Bullnados** [nextcloud/android#1049]
In Transifex finde ich eine Übersetzung nicht, die ich gerne ändern würde. 
Es geht um "Wiederholung fehlgeschlagen" in der Uploadliste. Diese sollte besser "Wiederholung Fehlgeschlagene" oder "Fehlgeschlagene wiederholen" heißen.
@AndyScherzinger

**Comment by JSoko** [comment]
@Bullnados 
Steht in Transifex seit einem Monat auf "Fehlgeschlagene erneut versuchen"
https://www.transifex.com/nextcloud/nextcloud/translate/#de_DE/$/91098383?qt=fehlgeschlagene

**Comment by AndyScherzinger** [comment]
Den aktuellen Stand der Übersetzungen siehst du am Besten in der Dev Variante der App: https://f-droid.org/repository/browse/?fdfilter=Nextcloud&fdid=com.nextcloud.android.beta

**Comment by Bullnados** [comment]
Danke für die Info, dachte nur, da eine neue Version im Playstore erschienen ist, dass auch gleihc die aktuellste Übersetzung genommen wurde

**Comment by AndyScherzinger** [comment]
Die 1.4.3 ist lediglich ein Hotfix wegen der Login-Änderungen in Nc12. Normallerweise wäre das so ja. In diesem Fall jedoch nicht, da der Master bereits auf Entwicklungsstand 1.5.0 ist aber noch nicht entsprechend stabil, dass man damit ein 1.5.0er Release hätte vorziehen können/sollen. So gesehen richtig gedacht, aber 1.4.3 ist eine Ausnahme gewesen.
