### ISSUE TITLE
Client not detecting modified images to replace previous auto uploaded images 

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/android#10505]
### Steps to reproduce
1. Take a photo
2.  It get automatically uploaded 
3.  Open the the photo and remaster it. I'm using Samsung galaxy 

### Expected behaviour
- The client should detect that a photo has been modified and uploaded to server

### Actual behaviour
- Client not detecting change 

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:
Android 12
Device model: 
SM-G996U1
Stock or customized system:
Stock
Nextcloud app version:
3.20.3
Nextcloud server version:
NC 24.0.2
Reverse proxy:

**Comment by joshtrichards** [comment]
Can you provide the auto-upload settings used for the source folder in question?

**Comment by AndyXheli** [comment]
Auto upload settings used would be the auto detect camera folder was created by the phone when a photo was taken

**Comment by joshtrichards** [comment]
There are a variety of settings for an auto-upload folder. Behavior rules regarding whether to delete existing files, etc. Those are the settings needed.
