### ISSUE TITLE
What is the difference betwen Nextclod Android and the gplay-release?

### ISSUE THREAD

**Issue by Schneehexe** [nextcloud/android#10502]
Hello Android Users and Developers,

my question totay is about the difference between the small nextcloud.apk and the bigger gplay-release.apk.
What is the difference?

![image](https://user-images.githubusercontent.com/36819426/178143639-33a85979-2441-4361-9fd3-f1f29d0e56f6.png)

Best regards, Schneehexe

**Comment by AndyScherzinger** [comment]
The GPlay version supports push notification and ships a document scanner
