### ISSUE TITLE
Automatic resolution of "conflicts" with Instantupload

### ISSUE THREAD

**Issue by wsw70** [nextcloud/android#10501]
### Is your feature request related to a problem? Please describe.

I often have a bunch of "conflicts" when using autoupload (automatic upload of photos send videos) when the**exact same files** are available on both the phone and the server.

### Describe the solution you'd like

The possibility to preemptively decide on the phone app configuration whether I always want to keep the local, the remote, the newer, ... file.

### Describe alternatives you've considered

There are no alternatives except for clicking and clicking and clicking.

**Comment by AlvaroBrey** [comment]
This is already possible. Check the three dot menu next to the autoupload folder title.

![photo_2022-07-11_15-25-19](https://user-images.githubusercontent.com/8677743/178274560-9515414f-8aa8-4525-b042-13c5c7e2f202.jpg)
