### ISSUE TITLE
[3.21.0 RC1] Settings window theme

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/android#10517]
### Steps to reproduce
**I.**

1. Launch the app.
2. Go to app settings.
3. Change the theme.

**II.**

1. Launch the app.
2. Go to app settings.

### Expected behaviour
Change the theme.

### Actual behaviour
**I.** Theme is not being changed correctly for the settings menu window. When you change the theme setting, a light theme appears for a dark one, and vice versa.

**II.** When the application is launched for the first time, the theme for the settings window is not compatible with the theme that was set.

### Environment data
Android version: 10
Nextcloud app version: 3.21.0 RC1

@tobiasKaminsky @AndyScherzinger It would be good to fix it 😉.

**Comment by tobiasKaminsky** [comment]
Tested, and indeed this happens, but only when setting theme manually to dark/light…
