### ISSUE TITLE
Recieve deck notifications on a lan with no internet access (nextcloud services wont open deck app)

### ISSUE THREAD

**Issue by mstyp** [nextcloud/android#10526]
### Is your feature request related to a problem? Please describe.
For years I have not received notifications because of relience on google services, which would be fine, but google services requires internet access in order to work and my tablet and server dont ever touch the internet. 

Nextcloud Services app only partially solves this problem, it works for notifying me, it cant do what I want it to do, which is open the deck app directly to the relevent card that comes due. 

There has to be a way for me to get a notification when a card comes due, click on that notification, and open the relevent card. 

### Describe the solution you'd like
I want to be able to click on a notification and open the relevent deck card

### Describe alternatives you've considered
I've tried nextcloud services, and I've looked into nextcloud push but It involves a bunch of complicated steps and I dont even know if it would work. 

### Additional context
I use stock nextcloud app from playstore and stock nextcloud. I should be able to get notifications. Matrix Element app and fairemail send me push notifications just fine (idk how, but they do). Nextcloud is the last remaining holdout with notification issues.

**Comment by mstyp** [comment]
I'm posting here rather then in nextcloud deck android repo because nextcloud deck relies entirly on nextcloud app for notifications.

**Comment by mstyp** [comment]
This is a very wordy / niche problem that I am not sure I am doing a good job of explaining, but is really, really frustrating me, because I cant find a better task manager then nextcloud deck, but I cant use nextcloud deck the way I want to becasue notifications dont work properly, and Its starting to take a real toll on my productivity.

**Comment by joshtrichards** [comment]
Hi @mstyp - If I'm I understanding your request correctly, you're asking for the following:

1. a different push notification method that isn't reliant on Google Services 
2. the ability to click on a Deck related notification and end in the appropriate place in Deck

Item 1 (push notifications) is covered by #5510, #8684, #11898, and [others](https://github.com/nextcloud/android/labels/hotspot%3A%20push%20notifications) (currently in the midst of re-organizing and reviewing these overlapping issues)
Item 2 (deck notifications) is covered by #6389 and stefan-niedermann/nextcloud-deck#498

So I encourage you to subscribe to one or more of the referenced issues, as well as give your preferred ones a :+1: to help with prioritization.

If I'm misinterpreted your request, feel free to respond/re-open.
