### ISSUE TITLE
Is there a version that works on android 2.2?

### ISSUE THREAD

**Issue by Jonathan-92** [nextcloud/android#1052]
### Actual behaviour
- App incompatible with my phone which has android 2.2

### Expected behaviour
- I don't really expect it but it would be nice if there was a version that works on android 2.2
 
### Steps to reproduce
1. 
2. 
3. 

### Environment data
Android version: 2.2

Device model: HTC Gratia

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
Hi @Jonathan-92,

I'm sorry to disappoint you but like you guess correctly the Nextcloud client (and all other third-party apps I am aware of) doesn't support 2.2 and requires at least 4.0.x. So you are limited to the use of the web app via a browser..
