### ISSUE TITLE
Adding integration with ZeroTier SDK

### ISSUE THREAD

**Issue by doryashar** [nextcloud/android#10530]
ZeroTier is an open source solution that provides network control and P2P functionality.
In other words, it's a VPN service allows to create a remote network as if the nodes are in the same local LAN.

ZeroTier has SDK for apps integration, well documented in https://github.com/zerotier/libzt.

i would like to suggest a feature to allow clients use zerotier network specific on nextcloud app instead of having to download the zerotier client for android alongside the nextcloud app.

**Comment by AlvaroBrey** [comment]
Hello @doryashar , thanks for the suggestion, but this is far outside of the scope of the Nextcloud app.
