### ISSUE TITLE
Folder sync leads to adverse UX

### ISSUE THREAD

**Issue by dest4** [nextcloud/android#10534]
### Steps to reproduce
1. Open a folder with more than 10 files in it, so that you can scroll the list
2. Sync spinning icon appears
3. Scroll in the file list
4. Sync ends

### Expected behaviour
- File list should not move, so that selecting a file would be reliable

### Actual behaviour
- File list is offset by the top menu that re-appears, after being hidden during scroll
![image](https://user-images.githubusercontent.com/9466937/179582965-d0843bd7-3c6e-4c34-96bb-de0532cb86b7.png)

### Can you reproduce this problem on https://try.nextcloud.com?
Created an account on a web browser, but do not find a way to see which password is used, so cannot test on my Android phone. Issue is unlikely related to client-server interaction, it's mostly UI.

### Environment data
Android version: 10

Device model: SM-A520F

Stock or customized system: LineageOS

Nextcloud app version: 3.20.3

Nextcloud server version: 24.0.2

Reverse proxy: nginx

**Comment by joshtrichards** [comment]
This does not appear to be the case any longer today. If you can still reproduce this behavior, let me know and I'll re-open this.
