### ISSUE TITLE
NavigationBar  Title 

### ISSUE THREAD

**Issue by aleister09** [nextcloud/android#1054]
### Actual behaviour 
NavigationBar doesn't show the current Directory Name and the back button 

### Steps to reproduce
1. Open App
2. Open a Directory

### Environment data
Android version:7.1.2

Device model: Nexus 5X

Nextcloud app version:Master

### Logs
![device-2017-05-30-114905](https://cloud.githubusercontent.com/assets/25756086/26594743/72e65e1e-452e-11e7-9d6b-bbd4f01113d4.png)

**Comment by MorrisJobke** [comment]
@tobiasKaminsky @AndyScherzinger any news on this?

**Comment by MorrisJobke** [comment]
cc @oparoz @mario

**Comment by AndyScherzinger** [comment]
@MorrisJobke afaik still an open issue, I am not aware that anyone had a look into it and created a patch yet. Correct me if I am wrong @mario.

**Comment by mario** [comment]
I'll look into this today if I can fix all other things that need to be done today...

**Comment by MorrisJobke** [comment]
> I'll look into this today if I can fix all other things that need to be done today...

This is already fixed by @aleister09 😉

**Comment by MorrisJobke** [comment]
> This is already fixed by @aleister09 😉

Only the PR against our repo is missing.

**Comment by mario** [comment]
Ah, ok, I'll wait for it and review it then! ;)
