### ISSUE TITLE
Nextcloud Dev: Is there a way to export account settings in order to make a clean install and reload those settings back.

### ISSUE THREAD

**Issue by OlivierS1** [nextcloud/android#1055]
### Actual behaviour
-Tell us what happens
I am using Nextcloud Dev app on a daily basis and I try to report bugs I find.
The last bug I found may have been caused by the introduction of one or more updates, or simply have occurred during normal usage.
It seems performing a clean install, rather than an update has solve that particular issue, maybe something to do with the Thumbnail cache.
I am usually reluctant to perform a clean install for several reasons:

- I need to go through account setup.
- I need to generate a new App password.
- I need to enable Autouploads to point to non-default folder and enable each of the options.

Repeat the above process for my other accounts.

### Expected behaviour
-Tell us what should happen
Is there a way to backup or save the App configuration so it can be reused after the App has been removed and installed again?

**Comment by OlivierS1** [comment]
@tobiasKaminsky , Fair enough.
However, is there no way at all the configuration file if it exist can be accessed with phone file manager/explorer in order to save in another folder then uninstall the app and restore the configuration file after app has been reinstalled?

**Comment by tobiasKaminsky** [comment]
I heard that titanum backup can do something like that.
But the account for instance is saved in the android account manager and this is removed when uninstalling the app.
