### ISSUE TITLE
Can't see files/upload files as User with umlaute (äöü) in the name

### ISSUE THREAD

**Issue by dimitrihof** [nextcloud/android#10561]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Login with a user that has umlaute in the name
Can't see files - only an server error
Can't upload files

### Expected behaviour

Able to see files and upload files as usual

### Actual behaviour

Files are not displayed only an error message. "No files available" (German: Keine Dateien vorhanden) and on the top there is an info bar with "Server not available" (German: Server nicht verfügbar).

### Android version

12

### Device brand and model

Google Pixel 4a

### Stock or custom OS?

Stock

### Nextcloud android app version

3.20.3

### Nextcloud server version

Nextcloud Hub II (23.0.3)

### Using a reverse proxy?

Yes (apache2) 

### Server error logs

Can't find any logs, that relate to that error. Login seems to work properly.

**Comment by joshtrichards** [comment]
This seems to be a server matter: nextcloud/server#34463
