### ISSUE TITLE
Add option to upload only on Wi-Fi

### ISSUE THREAD

**Issue by mozzieongit** [nextcloud/android#10570]
### Is your feature request related to a problem? Please describe.
Some people do not have a big flat rate and when seedvault starts a backup right before leaving home, nextcloud continues to upload via mobile data.

### Describe the solution you'd like
I'd like to have an option to (generally) upload only on Wi-Fi (possibly "unless actively/manually started")

### Additional context
It is kinda related to #5670, but without the "home" part of that issue.

**Comment by AlvaroBrey** [comment]
Is this about autopuload? If so, this is already available

**Comment by mozzieongit** [comment]
No. When Seedvault performs a backup, it writes to a location somewhere in the Nextcloud folders (somewhere in Android/). These temporary files are then uploaded automatically (without being in a listed auto upload folder) and deleted afterwards (after a delay, which could be before uploading when Nextcloud fails to upload). (I already opened an issue with seedvault to allow for manual schedules (seedvault-app/seedvault#429) or backups on wi-fi only (seedvault-app/seedvault#431))

I would like to have the option to disable the automatic uploading of files or even the general upload of files, when I'm not connected to an unmetered Wi-Fi connection.

**Comment by AlvaroBrey** [comment]
I've just had a quick look and it looks like Seedvault "shares" the files to Nextcloud via SAF. This is intended for the use case where users share a file manually from other app with the intent to upload it to Nextcloud; I don't think it would make much sense to add a setting for this.

Hopefully you get your solution in https://github.com/seedvault-app/seedvault/issues/431

**Comment by mozzieongit** [comment]
I understand that. 
Thanks for the insight.
