### ISSUE TITLE
Ransomware protection - Impossible to upload files: infinite notification

### ISSUE THREAD

**Issue by andreapx** [nextcloud/android#10574]
### Is your feature request related to a problem? Please describe.
With the app _Ransomware protection_ when a file is recognized as encrypted, the app alert that with: "Upload failed You are not permitted to upload to this folder", but this alert are fired every minutes or so and it's really annoying and useless.
In my case this happens every time I add a new field into the andOTP app, since the app create a backup that is encrypted (.aes) 

### Describe the solution you'd like
Just alert once per file

**Comment by joshtrichards** [comment]
This sounds more like it should be addressed by configuring the Ransomware Protection app to handle your .aes file correctly:

https://github.com/nextcloud/ransomware_protection#how-the-app-works

You can configure exclusions/etc.

Related: nextcloud/ransomware_protection#107

**Comment by andreapx** [comment]
> This sounds more like it should be addressed by configuring the Ransomware Protection app to handle your .aes file correctly:
> 
> https://github.com/nextcloud/ransomware_protection#how-the-app-works
> 
> You can configure exclusions/etc.

Well, that's a workaround. A notification every minute seems pretty useless to me.
