### ISSUE TITLE
F-Droid version is Outdated

### ISSUE THREAD

**Issue by foosinn** [nextcloud/android#1057]
F-Droid version cant connect to Nextcloud 12. Play Store version can.

https://f-droid.org/repository/browse/?fdfilter=com.nextcloud&fdid=com.nextcloud.client

Please Update. Thanks!

**Comment by mario** [comment]
Hi,

please use this for now:

https://f-droid.org/repository/browse/?fdfilter=com.nextcloud&fdid=com.nextcloud.android.beta

Once 1.5 is out, they'll start building our stable releases once again.

Thanks for using the app!
