### ISSUE TITLE
Unable auto-uploading to "End-to-End encrypted" folder structure with "Use Subfolders" activated

### ISSUE THREAD

**Issue by simonsan** [nextcloud/android#10583]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Setup auto-upload to E2E encrypted folder structure **with "Use Subfolders" activated**
2. Wait for it to start
3. Watch it creating folders in the encrypted root/or not creating the folder structure at all
4. See "Unknown error" in `Uploads` tab

### Expected behaviour

Should create 
- the folder structure based on month and year and
- be able to upload to the right folder correspondingly

### Actual behaviour

Creates the `month` folder in the `encrypted root dir` and isn't able to upload anything. Fails even if the folder structure is created manually, in this case: `root/2022/08/`. **Deactivating "Use Subfolders" fixes the problem.**

For completeness: Encrypted folder is on external storage (via SFTP).

### Android version

11

### Device brand and model

Murena Fairphone 4

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

3.20.3

### Nextcloud server version

24.0.3

### Using a reverse proxy?

Yes

### Android logs

```log
08-03 16:03:29.878  8238  8288 D OwnCloudClient #0: REQUEST POST /ocs/v2.php/apps/end_to_end_encryption/api/v1/lock/null
08-03 16:03:29.879  8238  8288 D AdvancedSslSocketFactory: Creating SSL Socket with remote <host>:443, local null:0, params: org.apache.commons.httpclient.params.HttpConnectionParams@c1f796d
08-03 16:03:29.880  8238  8288 D AdvancedSslSocketFactory:  ... with connection timeout 5000 and socket timeout 60000
08-03 16:03:29.881  8238  8288 I ServerNameIndicator: SSLSocket implementation: org.conscrypt.Java8EngineSocket
08-03 16:03:29.881  8238  8288 I ServerNameIndicator: SNI done, hostname: <host>
08-03 16:03:30.361  8238  8288 E UploadFileOperation: Upload of /storage/emulated/0/DCIM/OpenCamera/IMG_20220803_160325.jpg to /nc-ext/MediaUpload/77f9b8fad5ad4ccd901eedd8b6f665ec/2022/08/IMG_20220803_160325.jpg: Unexpected exception
08-03 16:03:30.361  8238  8288 E UploadFileOperation: com.owncloud.android.operations.UploadException: Forbidden! Please try again later.)
08-03 16:03:30.361  8238  8288 E UploadFileOperation: 	at com.owncloud.android.utils.EncryptionUtils.lockFolder(EncryptionUtils.java:805)
08-03 16:03:30.361  8238  8288 E UploadFileOperation: 	at com.owncloud.android.operations.UploadFileOperation.encryptedUpload(UploadFileOperation.java:483)
08-03 16:03:30.361  8238  8288 E UploadFileOperation: 	at com.owncloud.android.operations.UploadFileOperation.run(UploadFileOperation.java:450)
08-03 16:03:30.361  8238  8288 E UploadFileOperation: 	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:187)
08-03 16:03:30.361  8238  8288 E UploadFileOperation: 	at com.owncloud.android.files.services.FileUploader.uploadFile(FileUploader.java:640)
08-03 16:03:30.361  8238  8288 E UploadFileOperation: 	at com.owncloud.android.files.services.FileUploader$ServiceHandler.handleMessage(FileUploader.java:1396)
08-03 16:03:30.361  8238  8288 E UploadFileOperation: 	at android.os.Handler.dispatchMessage(Handler.java:106)
08-03 16:03:30.361  8238  8288 E UploadFileOperation: 	at android.os.Looper.loop(Looper.java:223)
08-03 16:03:30.361  8238  8288 E UploadFileOperation: 	at android.os.HandlerThread.run(HandlerThread.java:67)
08-03 16:03:30.362  8238  8288 D UploadsStorageManager: updateDatabaseUploadResult uploadResult: RemoteOperationResult(mSuccess=false, mHttpCode=-1, mHttpPhrase=null, mException=com.owncloud.android.operations.UploadException: Forbidden! Please try again later.), mCode=UNKNOWN_ERROR, message=null, getLogMessage=Unexpected exception) upload: com.owncloud.android.operations.UploadFileOperation@312a8b0
08-03 16:03:30.369  8238  8288 V UploadsStorageManager: Updating /storage/emulated/0/DCIM/OpenCamera/IMG_20220803_160325.jpg with status:UPLOAD_FAILED and result:UNKNOWN (old:/storage/emulated/0/DCIM/OpenCamera/IMG_20220803_160325.jpg status:UPLOAD_IN_PROGRESS result:-1)
08-03 16:03:30.369  8238  8288 V UploadsStorageManager: Updating /storage/emulated/0/DCIM/OpenCamera/IMG_20220803_160325.jpg with status=UPLOAD_FAILED
08-03 16:03:30.375  8238  8288 D UploadsStorageManager: updateUpload returns with: 1 for file: /storage/emulated/0/DCIM/OpenCamera/IMG_20220803_160325.jpg
08-03 16:03:30.375  8238  8288 D UploadsStorageManager: notifyObserversNow
08-03 16:03:30.376  8238  8288 D FileUploader: NotifyUploadResult with resultCode: UNKNOWN_ERROR
08-03 16:03:30.386  8238  8288 D FileUploader: Stopping command after id 46
```

### Server error logs

```bash
No errors.
```

### Additional information

/e/-OS version
1.2-r-20220726206059-stable-FP4

Kernel version:
4.19.157-perf-gfdb7ef01a6c7

**Comment by p5n** [comment]
Similar problem but without use-subfolder checkbox, I set up auto upload for folder with subfolders. Subfolders created but no files uploaded
```
POST /ocs/v2.php/apps/end_to_end_encryption/api/v1/lock/530831?format=json HTTP/1.1" 403
```

**Comment by mpsd** [comment]
Same issue here - with android client v3.24..2 - currently E2EE can not be used with autoupload to subfolders :-( 

Any development on this bug (seeing the last label on Aug 3, 2022)?

Thanks for fixing

**Comment by p5n** [comment]
I am not sure, but client was able to sync encrypted subfolder. I guess that I enabled default encryption module app (not using server side encryption), but it may be unrelated.

**Comment by joshtrichards** [comment]
> `Forbidden! Please try again later.`

This indicates the E2EE locking failed on the server (https://github.com/nextcloud/end_to_end_encryption/blob/master/doc/api.md#lock-file).

Please provide the corresponding Nextcloud Server log entries for one of these upload transactions.

Also, please make sure the the standard Encryption app (`encryption`) is not configured alongside the E2EE one (`end_to_end_encryption`). Both cannot be used simultaneously. Obviously make backups of your data before changing anything. :)

It's also entirely possible this issue was addressed since it was reported in a newer release (#11620 among other made changes to E2EE).
