### ISSUE TITLE
Notifications broken

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#1059]
At the moment notifications isn't working anymore. Tested with the credentials you gave me @mario .

On the webUI I see notifications while the Android client (even after refreshes) keeps telling "No Notifications"

**Comment by mario** [comment]
This works for me on both 11 and 12 :-/

**Comment by mario** [comment]
@AndyScherzinger can you please confirm? :p

**Comment by AndyScherzinger** [comment]
retested and it works, so closing (not sure why it didn't at some point when I tested it before ?!)
