### ISSUE TITLE
Sort by recent should mix files and folders

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/android#106]
When sorting by recently modified, folders are shown first. It's quite cumbersome to need to scroll down to reach files.

The elements should be sorted by recently modified, files and folders mixed. This is also how we did it before.

PR: #135

**Comment by tobiasKaminsky** [comment]
I have no idea who/why it was changed. Are you sure that this already was in master and not in beta?
But...here is the PR: #135

**Comment by jancborchardt** [comment]
Maybe it was only in beta, but in any case the folders and files should be mixed. :) Thanks!

**Comment by AndyScherzinger** [comment]
to be release with 1.3.0
