### ISSUE TITLE
Can't upload to Huawei via Fastlane

### ISSUE THREAD

**Issue by AlvaroBrey** [nextcloud/android#10604]
Release [3.21.0](https://github.com/nextcloud/android/releases/tag/stable-3.21.0) is not on Huawei AppGallery due to the following problem:

```ruby
{"ret"=>{"code"=>204144660, "msg"=>"[cds]submit failed, additional msg is [The history of questionnaire feedback content ratings is empty .]"}}
```

**Comment by tobiasKaminsky** [comment]
I filled out questionnaire and update was submitted successfully.
