### ISSUE TITLE
Nextcloud 1.5 vs Nextcloud Dev

### ISSUE THREAD

**Issue by OlivierS1** [nextcloud/android#1060]
### Actual behaviour
-Tell us what happens

This is just a query for information.
It seems Nextcloud 1.5 is in the work and I am wondering about the following:
- Is Nextcloud Dev going to become Nextcloud 1.5? As far as I understand, Nextcloud Dev is a different beast altogether and may not have the same features as 1.5, right?

- Nextcloud Dev is currently being tested but is not a Release Candidate nor a final product.
- Will Nextcloud 1.5 be released under RC or will it go directly to Release? It seems 1.5 is currently being tested.

- Will Nextcloud 1.5 be available to beta tester at some point or will it go as a Release for everybody?

If the former, how to get access to the beta or RC if any?

Thanks

**Comment by mario** [comment]
Nextcloud dev ideally should have everything the next release will have + a few more things that might or might never go into ANY release.

In the real world, unfortunately, we sometimes don't merge everything to dev but this is improving with every passing day...

NC 1.5 will be available as RC (which is basically a beta) under Play Store beta mechanism once ready. Do you need instructions on how to apply for beta?

Cheers!

**Comment by OlivierS1** [comment]
Hi Mario,

I am already setup as Beta on Google play store. I just haven't seen 1.5 yet.
Can't wait to test it out, though.

**Comment by mario** [comment]
It'll come as soon as we feel it's ready :)

Thanks for the patience! :)

**Comment by AndyScherzinger** [comment]
Since imho all questions have been answered I'll close the issue. Feel free to further discuss :)
