### ISSUE TITLE
"enter" (newline) deletes text in txt editor 3.21.0 (3.20.3 is fine) 

### ISSUE THREAD

**Issue by kolAflash** [nextcloud/android#10618]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. open a textfile (*.txt) for editing in the Android app (-> https://github.com/nextcloud/text/)
2. click at the end of a line containing some text
3. press enter

### Expected behaviour

new line appears

### Actual behaviour

rest of the text is being completely deleted

### Android version

Android 12

### Device brand and model

Google Pixel 4a

### Stock or custom OS?

Stock

### Nextcloud android app version

3.21.0

### Nextcloud server version

24.0.3

### Using a reverse proxy?

No

### Additional information

**REGRESSION**

[PIxel 4a](https://en.wikipedia.org/wiki/Pixel_4a), using keyboard: https://f-droid.org/de/packages/org.dslul.openboard.inputmethod.latin/

Maybe related:
https://github.com/nextcloud/files_texteditor/issues/104
https://github.com/nextcloud/android/issues/8945

Bug also happens with: [Fairphone 3 Plus](https://en.wikipedia.org/wiki/Fairphone_3) running [/e/OS 1.0](https://e.foundation/) (Android-10).

**Workaround:**
`adb install -r -d gplay-release-30200390.apk`
https://github.com/nextcloud/android/releases/download/stable-3.20.3/gplay-release-30200390.apk

**Comment by AlvaroBrey** [comment]
cc @tobiasKaminsky, possibly related to #10148

**Comment by tobiasKaminsky** [comment]
@max-nextcloud shall we debug this again, or are you already aware of this?

**Comment by kolAflash** [comment]
**This seems to be a pretty big show stopper for using the txt editor!**

I don't have an running Android build environment. But if someone could build a version stable-3.21.0 with commit 8bd324323841945c883503f5431dbdacfc5748d8 reverted I can test if that fixes the issue.

**If that commit is really the problem, I'd like to suggest reverting it until a better solution is found!**

The purpose of that commit was to resolve the following problem. But the new problem - deleting half a file - seems to be the much worse issue than a cursor going back on bold text.

_Cursor goes back when typing bold text #10032_
https://github.com/nextcloud/android/issues/10032

**Comment by dbolton** [comment]
After upgrading, I've found pressing enter has different results depending on where you are in the file

- Go to begin of the file (line 1, column 1) and press enter -> Deletes full text file. Occasionally it adds two line breaks then deletes both half a second later.
- Go to end of any line of text and press enter -> No line break added.

**Comment by AlvaroBrey** [comment]
> I don't have a running Android build environment. But if someone could build a version stable-3.21.0 with commit [8bd3243](https://github.com/nextcloud/android/commit/8bd324323841945c883503f5431dbdacfc5748d8) reverted I can test if that fixes the issue.

Opened https://github.com/nextcloud/android/pull/10657. A QA build should be automatically posted in a few minutes, which you can test alongside your current install

**Comment by tobiasKaminsky** [comment]
I will have a call with @max-nextcloud on Wednesday about this.
Of course any insight/help until then is highly appreciated :-)

**Comment by snagglewest** [comment]
I can confirm the test build in #10657 works.  
Please please please push this out as soon as possible.  We use shared text files all the time so this is a major inconvenience.  Thanks in advance for all the hard work effort everyone puts into the app!

**Comment by kolAflash** [comment]
Tested #10657 and it does not show th bug 👍

**Comment by tobiasKaminsky** [comment]
I have a call tomorrow with our Text app expert.
Either we can solve it, or we revert the fix.
After that we will directly ship a 3.21.1, as this is a major regression.

**Comment by tobiasKaminsky** [comment]
Max will debug this on Text side.

**Comment by max-nextcloud** [comment]
I have tried to reproduce this behavior with 3.21.0 in Android Studio using both my actual keyboard as well as the on screen keyboard and have not been able to.

So far i tried with a fresh `.md` file and opened it again afterwards. Are you working on plain '.txt' files or markdown? Is there any formatting involved? I am yet to figure out how to trigger this bug.

**Comment by max-nextcloud** [comment]
If you can reproduce this it would also be very helpful to know if the issue also applies when opening the text file in Android WebView from the web interface.

**Comment by snagglewest** [comment]
I'll see what I can provide but keep in mind I'm just a simple user:

web app - enter an existing text doc.  Hit enter results in all text being deleted.  The second attempt to enter a line feed results in nothing.  It is as if the key is never clicked.

Make a new .md file and it is editable as normal but enter results in 2 line feeds as is normal for a lot of mark up editors.

Rename the file to a .txt extension and the enter key no longer works in the .txt file.

Rename the file back to a .md extension and he enter key now only results in a single line.

The android app functions similarly.

Probably not real helpful but I can 100% confirm he test build referenced in 10657 works.

**Comment by dbolton** [comment]
Editing a .txt file via the web, I get different results depending on the browser: Firefox (v. 104.1.0) works without issue. Chrome (v. 103.0.5060.53) doesn't work. When I press enter the cursor jumps to the beginning or somewhere earlier in the file.

**Comment by max-nextcloud** [comment]
Thanks a lot for your help. I was also able to reproduce the enter key not working in `.txt` files. So that is a starting point for debugging.

@snagglewest could you try the demos on https://prosemirror.net/ and https://tiptap.dev/examples/default with your android phone using google chrome browser? Our editor is based on tiptap which in turn is based on prosemirror. So that would help figure out where the problem originates.

**Comment by max-nextcloud** [comment]
@tobiasKaminsky I think we should revert the breaking change for now. The previous issue was way less impactful. That will buy us time to find the root cause and come up with a proper solution.

**Comment by tobiasKaminsky** [comment]
@AlvaroBrey can you revert it and create a 3.21.1 with only this fix?

**Comment by tobiasKaminsky** [comment]
I reopened https://github.com/nextcloud/android/issues/10032

**Comment by snagglewest** [comment]
If it helps, with a Samsung S21 cell phone & Google Chrome browser

https://prosemirror.net/ 
Set text type to:
plain text - enter produces 2 line return
code - enter produces single line return
Heading - enter produces single line return


https://tiptap.dev/examples/default 
Every setting I tried enter produces 2 line return

**Comment by marbx** [comment]
I find this in NextCloud 3.21.0 on Android 12:
- Navigate to plain text file with file ending .txt
- Tap on file to display
- Tap on back to leave file
- From context menu select Edit
- Move cursor to the end of the file
- Press enter
- Observe that text disappears
- Leave editor

NextCloud can no longer display the file
Editor shows empty file
NextCloud does not sync the file

**Comment by marbx** [comment]
I noted NextCloud 3.21.1 contains the fix.
 
The Google Playstore on Android 12 shows NextCloud 3.21.1 as if it was installed:  it shows the Open button.
However, Nextcloud 3.21.0 opens which contains the bug. 
Restart of Android does not change this.
![s](https://user-images.githubusercontent.com/8489107/187021715-84189f02-928e-4986-82e6-38723bbaa37b.png)


F-Droid on LineageOS 18.1 does not show NextCloud App version 3.21.1

Shall I create a new issue to track?

**Comment by AlvaroBrey** [comment]
> I noted NextCloud 3.21.1 contains the fix.
> 
> The Google Playstore on Android 12 shows NextCloud 3.21.1 as if it was installed: it shows the Open button. However, Nextcloud 3.21.0 opens which contains the bug. Restart of Android does not change this.
> 
> F-Droid on LineageOS 18.1 does not show NextCloud App version 3.21.1
> 
> Shall I create a new issue to track?

3.21.1 is correctly published in Google Play. If you don't get the correct version there might be a problem with your Google Play app or something. I suggest uninstalling and reinstalling Nextcloud. Don't create a new issue, this has nothing to do with us.

**Comment by AlvaroBrey** [comment]
> F-Droid on LineageOS 18.1 does not show NextCloud App version 3.21.1

https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11617  new version is merged but not published yet (FDroid build the app themselves, usually takes a few days)

**Comment by marbx** [comment]
I unistalled 3.21.0 on Android, Play Store installed 3.21.1.

Bug fixed on Android
