### ISSUE TITLE
File type other than JPEG and JPG not uploading via Android app

### ISSUE THREAD

**Issue by zulfan91** [nextcloud/android#10616]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Open NC Android app
2. Configure Auto Upload with Manual Folders
3. Save and Enable Auto Upload

### Expected behaviour

I expected all file types in the Folder to be uploaded to the folder configured in the App

### Actual behaviour

Auto Upload feature only uploads JPG and JPEG files and throws Error 406 "Not Acceptable" for all other files types such a PDF or MP4, etc

### Android version

11

### Device brand and model

OnePlus 6T

### Stock or custom OS?

Stock

### Nextcloud android app version

3.21.0

### Nextcloud server version

24.0.3

### Using a reverse proxy?

I don't know

### Additional information

I have tried deleting and reinstalling the app several times with the same error. Uploads work fine with Desktop App as well as over the WEB.

**Comment by AlvaroBrey** [comment]
Did you give the app the "All files access" permission, or the "media read-only" permission?

**Comment by zulfan91** [comment]
> Did you give the app the "All files access" permission, or the "media read-only" permission?

All permissions have been given

**Comment by zulfan91** [comment]
> Did you give the app the "All files access" permission, or the "media read-only" permission?

Yes, all permissions have been given

**Comment by AlvaroBrey** [comment]
Will need to investigate this. As a workaround you can use "Upload content from other apps" and choose the files through there; that should work.

**Comment by OfficialMuffin** [comment]
Uploading from other apps does not work for me either.

**Comment by AlvaroBrey** [comment]
@OfficialMuffin @zulfan91 Can either of you try to upload a PDF or something else, and then get a logcat from the Android device so we can see if there's any errors? Instructions here: https://github.com/nextcloud/android#getting-debug-info-via-logcat-mag

Feel free to search and replace the server URL, username and  file names in the output for privacy, if needed.

**Comment by OfficialMuffin** [comment]
@AlvaroBrey Strangely; I cleared all the permissions for my device and allowed the file permission again and it seems to work now. All PDFs can be uploaded successfully with no error.

**Comment by AlvaroBrey** [comment]
Thanks @OfficialMuffin 

@zulfan91 can you check if the above workaround works for you?
