### ISSUE TITLE
Nextcloud Dev 20170529: "Favorites" and "Shared" menu not working.

### ISSUE THREAD

**Issue by OlivierS1** [nextcloud/android#1061]
### Actual behaviour
-Tell us what happens
I don't know if the following status are still work i progress or simply not working due to bugs:

- "Favorites"
- "Shared"

Right now, when I access the "Favorites" menu, I get a short message that looks like:
"Nothing Favorited yet" (improper English I believe) then follows the spinning "Loading" semi-circle, and ends with "No files here- Upload some content or sync with your devices"

Same drill with the "shared" menu.

PS: As I was breaking down the steps to report this issue, I left my phone in the "Shared" menu. After a while I saw some activity and the display went from "No files fere" to showing a list of the files and folders being shared.
Investigating the issue further, it will take at least a minute before the content gets updated. In the meantime, "No files here" remains. If I swiped the screen down, it refreshes with "Nothing shared yet".
As I am waiting, there seem to be chunks of data being downloaded, at around 10KB/s.
I suspect each burst of data is a portion of the list being downloaded.
As I was performing the test, Nextcloud Dev, crashed a few times.

Pressing the "..." on the right top corner of the display, and switch between "Grid view" and "List view" a few times will populate the list incrementally.
The content doesn't seem to exist in the cache as soon as the screen is being refreshed, the content will instantly disappear.
The feature is not very stable to be useful, I think.
According to the Web interface, I have about 100 folders and 100 files shared for my account.

It seems "Favorites" never gets updated, though, I have 2 folders and 8 files set as favorites.

### Expected behaviour
-Tell us what should happen
Accessing the relevant menu should show some kind of list relevant to the feature.

### Steps to reproduce
1. Accessing "Shared"
2. Waiting until "Loading" stops.
3. 

### Environment data
Android version:
6.0
Device model: 
LG 3
Stock or customized system:
Stock
Nextcloud app version:
Nextcloud Dev 20170529

Nextcloud server version:
11.0.3

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by mario** [comment]
I think I fixed this.

We will see once new dev build is there.

**Comment by mario** [comment]
P.s. actually showing the list is relatively slow, we know - this is a problem, but not sure if it can be solved for 1.5. 

But you should see the loading all the time while it's loading, instead of the "No files here" or whatever.

**Comment by AndyScherzinger** [comment]
#1023 removes "Favorites" from the menu for pre-NC12 since the needed server API isn't available before NC12.

**Comment by mario** [comment]
Ah NC11. You are right :D Shared should work though, but there's the potential that it's slow ...

**Comment by AndyScherzinger** [comment]
@OlivierS1 is the issue still present for you?

**Comment by OlivierS1** [comment]
@AndyScherzinger , As I have upgraded to NC12, I do not have this issue anymore. However, it does take some time to update its content. I think the "Loading" arrow keeps on running until the content id finally loaded.
This behavior makes me think whether the operation is still in progress or the app as actually crashed. It is disconcerting. 
I think the info should be logged so it can be used offline and only when it is updated from server that it should be updated on phone. Just a thought.

**Comment by mario** [comment]
@OlivierS1 this is how it'll work in 1.6, but not for 1.5 - sorry. Just not enough time in a day :(

**Comment by OlivierS1** [comment]
@mario , how so, aren't you working on Centaurian time, standard thirty-seven hour day?

**Comment by mario** [comment]
I am. But still not enough.

**Comment by pzwahlen** [comment]
I'm having this issue for both "Favorites" and "Photos". They both lead to an unlimited "Loading..." page. In my case, this happens with LDAP users on both 12.0.3 and 12.0.4RC1.

When the LDAP app is disabled, things seem to work fine.

Using the Android App v2.0.0 on Samsung Galaxy S8

**Comment by tobiasKaminsky** [comment]
@mario as you implemented the search, do you have in idea why/if this really can be related to ldap? Maybe the "wrong username on ldap" thing?

**Comment by dceee** [comment]
Exact same issue here like with @pzwahlen on Nextcloud 12.0.5 and Android Client 3.0.0RC3. I am also using LDAP authentication which works flawlessly besides this problem.
