### ISSUE TITLE
No auto upload entry in the menu

### ISSUE THREAD

**Issue by rhyst** [nextcloud/android#10623]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Download Nextcloud 3.21.0 
2. Open the app and sign in
3. See that there is no auto upload option in the menu

### Expected behaviour

All the screenshots I've seen suggest that the auto upload option will be in the menu with files, calendar etc.

### Actual behaviour

The menu does not look like any other screenshot and there is no auto upload entry.

![Screenshot_20220813-171116_Nextcloud](https://user-images.githubusercontent.com/5313660/184502841-061f4fe2-769f-4283-91d4-5c55f0955bb3.jpg)

### Android version

11

### Device brand and model

Samsung Galaxy s10e

### Stock or custom OS?

Stock

### Nextcloud android app version

3.21.0

### Nextcloud server version

24.0.4

### Using a reverse proxy?

Yes

**Comment by andyxheli** [comment]
If that your view within the app there's something wrong. 

![Screenshot_20220813-153645_Nextcloud.jpg](https://user-images.githubusercontent.com/59488153/184510074-f37efb3e-13e4-439e-af49-fafab4f551d8.jpg)

**Comment by rhyst** [comment]
Well that is bizarre. I just opened it again, and it prompted me to log in again and now it looks like the app I have seen in screenshots, rather than just the mobile view of the website.

**Comment by andyxheli** [comment]
Iv had a similar issues with the ios App that normally means that the login with that device or the registration did go throw correctly I just remove the all and clear all cache and fixed it for me

**Comment by rhyst** [comment]
Well, thank you for the prompt to check again 😄

**Comment by andyxheli** [comment]
Iv had a similar issues with the ios App that normally means that the login with that device or the registration did go throw correctly I just remove the all and clear all cache and fixed it for me

You're welcome happy to help 😁
