### ISSUE TITLE
"On device" content display behavior should be improved.

### ISSUE THREAD

**Issue by OlivierS1** [nextcloud/android#1062]
### Actual behaviour
-Tell us what happens
Under both version of Nextcloud 1.4.3 and Nextcloud Dev 20170529, I find the "On device" feature to be pretty much useless.
The reason is that the folders are always displayed, even though their content may have not been downloaded yet.
I think it would be more informative to only show folders which have been synchronized and containing files. If the folder is not synchronized, ie. not containing downloaded files, then the folder should not be made visible.
To an extent, it would be nice to have the ability to visualize all the files either broken down per folder or as a single diaporama or catalog where the app would decend into each folder and create a list such as every files present on the storage media are browseable with a swipe. This can be define as an option similar to list view and "Grid view". 

### Expected behaviour
-Tell us what should happen
 
### Steps to reproduce
1. 
2. 
3. 

### Environment data
Android version:
6.0
Device model: 
LG 3
Stock or customized system:
Stock
Nextcloud app version:
Both 1.4.3 and Dev 20170529
Nextcloud server version:
11.0.3

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Showing only those folders that (even in subfolders) contain a downloaded file should be rather easy:
- open up the file path on the device and compare all sever-side folder entries with the local existing ones
 - if a folder exists locally display it as it has a content (even if it only a subfolder with content)
 - otherwise hide the entry
- show all downloaded files

**Comment by mario** [comment]
"On device" menu entry will be completely eliminated in the upcoming version, so closing this.

**Comment by tobiasKaminsky** [comment]
This will be done in a better way with a real offline support, which we track here #1143
