### ISSUE TITLE
Unable to upload files due to sync conflicts & sync conflicts in general

### ISSUE THREAD

**Issue by bannisdale** [nextcloud/android#10628]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Upload any file to any folder

### Expected behaviour

File gets uploaded without error

### Actual behaviour

Sync error appears (which can't even be resolved)

### Android version

12

### Device brand and model

Samsung Galaxy S21

### Stock or custom OS?

Stock

### Nextcloud android app version

3.20.3

### Nextcloud server version

24.0.3

### Using a reverse proxy?

I don't know

### Additional information

This is basically a reopening for #5755, which has been closed without a resolution and has been created more than two years ago. Given that the only response on my comment from a month ago was "I'm having the exact same problem", I'm opening this new issue now.

As written in https://github.com/nextcloud/android/issues/5755#issuecomment-1191177947 a month ago, my exact problem is:

> Most of the comments here seem to concern "auto upload", however the initial posting states the same error for manual uploads. That's what is happening for me.
> 
> I updated both the Nextcloud server (currently 24.0.3) and the Android app (currently 3.20.3). I also uninstalled the app and did a fresh install with a fresh login. Same issue. I tried both versions from F-Droid and Play Store.
> 
> Upload file (that doesn't exist): immediate "resolve conflict" notification. Clicking the notification: Toast message "Error creating conflict dialog". Upload is stopped. Upload tab: "resolve conflict" doesn't do anything, clicking the file starts a new upload that's immediately stopped by the conflict again. [Only "solution" that works is deleting the file from the upload queue.]
> 
> Desktop version works, downloading via Android app works, uploading via web/desktop works. Most error reports I have found concern auto upload, but as far as I can see, even all of them are now "closed" (like this one) without any proper solution? That's quite bothersome, especially since the original report is now more than two years old ...

A more general remark: The problem seems to go a bit deeper.

I tried to search this repository and found a lot of closed and open issues that all seem to handle different parts of sync conflicts problems that might or might not be related. Overall, it seems to be a good idea to consolidate them.

Current issues I found browsing the repository:

1. Problems with sync conflicts showing up for non-existing server files using auto-upload
2. Problems with sync conflicts coming back later even after resolution
3. Problems with sync conflict dialogs not opening when tapping the notification
4. Problems with no sync conflict resolution working

As far as I can see, these problems have lingered around for quite some time now, pretty much regardless of both app- and server-versions. Most issues have been closed without a remark, let alone a solution.

**Comment by AlvaroBrey** [comment]
@bannisdale have you checked if #10423 fits your situation? i.e. the `ErrorDocument` thing

**Comment by bannisdale** [comment]
@AlvaroBrey Apparently, this seems to be the solution for my upload problem. Thanks a bunch for pointing into the right direction!

I tested uploads of different files in two different directories. No errors showed up and the files were synced properly. I also created a conflict on purpose and it seems that the workaround also fixed the "Unable to create conflict dialog" error, as I am now properly seeing the conflict dialog when tapping the notification. To be honest, that's somewhat weird given the change. :D

So, for everyone looking for a manual workaround:

As described in https://github.com/nextcloud/android/issues/10423, I went to the nextcloud home directory on my server, edited the `.htaccess` file there, scrolled down and found the entries (I had never done changes to them before).

```
ErrorDocument 403 //
ErrorDocument 404 //
```

I now commented the 404 part out, so the entries now look as follows:

```
ErrorDocument 403 //
# ErrorDocument 404 //
```

I then saved the `.htaccess` file. For some magical reasons, everything seems to be in order again. I'm closing this issue and will also update #5755 for future reference.

@AlvaroBrey It might be benefitial to check why a (standard?) entry in the .htaccess can prevent the Android app from doing a bunch of stuff without a proper error message. Also, I'm not sure if this might break something else. I'd assume that the entry is there for a reason. :D I'll leave this mistery to #10423.

**Comment by AlvaroBrey** [comment]
> @AlvaroBrey It might be benefitial to check why a (standard?) entry in the .htaccess can prevent the Android app from doing a bunch of stuff without a proper error message. Also, I'm not sure if this might break something else. I'd assume that the entry is there for a reason. :D I'll leave this mistery to #10423.

Yeah, some investigation is needed. I assume that at some point a specific 404 error is expected, but the redirect doesn't match that. Thanks for reporting back!

**Comment by luisfcorreia** [comment]
Commenting that line didn't fix the issue
