### ISSUE TITLE
🎨 Material 3️⃣

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#10638]
Based on the work for talk Android in https://github.com/nextcloud/talk-android/pull/2084

- [x] nextcloud/android#10641
- [x] nextcloud/talk-android#2312
- [x] nextcloud/android#10640

**Comment by AlvaroBrey** [comment]
We have a slight problem with colors in Nextcloud 25, which I noticed this week. It looks like the server color capability now depends on each user's background picture. But this is a problem because:

- The app will look inconsistent (actual server color during and immediately after login, then user color next times)
- The background image is never actually shown in the app
- This will be a problem for branded clients, where we want brand color to be consistent all the time.

For these reasons I believe we should have a way to retrieve the true "server color" independently of user background, and always use that for the mobile apps.

Thoughts @AndyScherzinger @jancborchardt @tobiasKaminsky ?

cc @timkrueger @mahibi

**Comment by jancborchardt** [comment]
> The app will look inconsistent (actual server color during and immediately after login, then user color next times)

How about we do this:
- Use our blue color for during log in process
- As soon as the account is connected we fetch the person’s color, or fall back to server color

That way we don’t have a worst-case 3-step color switch. And we really need to make sure this inconsistency does not exist, which we can by optimizing the loading, no?

> The background image is never actually shown in the app

So the splash screen is the 1 thing which we can unfortunately not edit (only in branded clients). But we might still want to use the background e.g. in the header part of the navigation.

> This will be a problem for branded clients, where we want brand color to be consistent all the time.

This actually depends on the customer I’d say. Admins could disable the functionality for people to set their own background. (Not sure if this is already implemented.)

**Comment by AlvaroBrey** [comment]
> Use our blue color for during log in process

We already do this for the initial screen (the one with the Log In / Host your own server buttons), but we cannot control the login screen, as that is just a webview for the server's login flow. So if a user has a background image different from the server login image, it will always look different. For reference, here's an example of the worst-case scenario:

<details>
<summary> Example </summary>

In this example, the admin has set the server color to red, and the user has configured a yellow background image.

| Initial screen | During login | After login |
| --- | --- | --- |
| ![Screenshot_1666280101](https://user-images.githubusercontent.com/8677743/196994623-aa505513-2232-4e58-a8ec-66795e8ec964.png)  | ![Screenshot_1666280119](https://user-images.githubusercontent.com/8677743/196994732-7b1db8a7-a5cd-40d9-b643-6370a8cf3c81.png)  | ![Screenshot_1666280294](https://user-images.githubusercontent.com/8677743/196994796-2db09cc1-28e4-4ea1-a561-63e4ec503912.png) |

</details>

Putting it simply, there is no way to prevent the three-color switch (except in branded apps, where the server color and the brand color  for login screen could be matched).

> * As soon as the account is connected we fetch the person’s color, or fall back to server color

Just for reference, in the API response we don't have both things. We always get a "server color", but for an unauthenticated request it will be the actual "server color" set in Theming, and for an authenticated request it will be the user color. We would need to keep both stored separately, if we want to have this fallback; I initially will just use the primary color as fallback instead.

> And we really need to make sure this inconsistency does not exist, which we can by optimizing the loading, no?
Yes, this needs to be fixed. It was assumed that `theming.color` would be the server color, but now that it changes after login it's messing with some of our logic in NC25.
