### ISSUE TITLE
Custom storage path (no longer) available?

### ISSUE THREAD

**Issue by neonworker** [nextcloud/android#10654]
### Is your feature request related to a problem? Please describe.
I switched to a new phone (Pixel 3XL -> S21 FE 5G) and while adjusting nextcloud settings I could not set the storage path to something reasonable. On the Pixel it is set to  /storage/emulated/0 and thus in the typical root data directory.

### Describe the solution you'd like
Enable the user to set a custom storage path or give /storage/emulated/0 as an option (again?).

![Screenshot_20220821-182404](https://user-images.githubusercontent.com/15148221/185801198-1fb1b0a5-e918-4d35-84b7-a435af7fd661.png)

**Comment by AlvaroBrey** [comment]
@neonworker what's your Android version?

**Comment by neonworker** [comment]
Both phones are on Android 12

**Comment by joshtrichards** [comment]
> I switched to a new phone (Pixel 3XL -> S21 FE 5G) and while adjusting nextcloud settings I could not set the storage path to something reasonable. 

This is likely the underlying culprit (moving from phone-to-phone). See #10637 for explanation and one-time workarounds needed.

An adjustment was made in #10705 to prevent this from happening in the future.
