### ISSUE TITLE
SSO broken: Your Nextcloud Files app currently does not support the single sign on feature

### ISSUE THREAD

**Issue by KiaraGrouwstra** [nextcloud/android#10658]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Whenever I try to sign on to my nextcloud instance thru a nextcloud app that tries to reuse the existing NextCloud logins, I am met with an error:

> Your Nextcloud Files app currently does not support the single sign on feature.
> Please update it: https://play.google.com/store/apps/details?id=com.nextcloud.client

### Expected behaviour

Android clients of NextCloud apps can successfully use my existing NextCloud login.

### Actual behaviour

error message appears, as mentioned above.

### Android version

GrapheneOS Android 12 (August 1, 2022)

### Device brand and model

Pixel 5

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

20220816

### Nextcloud server version

24.0.4

### Using a reverse proxy?

I don't know

### Android logs

(I don't presently have `adb` set up, and don't see anything resembling the log path in Files)

### Server error logs

```bash
Based on the logs, the NextCloud server does not seem to be hit in this interaction.
```

### Additional information

Affected apps appear to include at least the following, leading me to believe there is more at hand here:

- [Deck](https://f-droid.org/en/packages/it.niedermann.nextcloud.deck/)
- [Maps Geofavorites](https://f-droid.org/en/packages/it.danieleverducci.nextcloudmaps/)
- [NextPush](https://f-droid.org/en/packages/org.unifiedpush.distributor.nextpush/)

**Comment by AlvaroBrey** [comment]
@KiaraGrouwstra can you try with a stable version of the app, rather than the dev version? this may just be a signature incompatibility

**Comment by KiaraGrouwstra** [comment]
that did it. thanks!
