### ISSUE TITLE
Keep media folder set after exit

### ISSUE THREAD

**Issue by Moyounnet37** [nextcloud/android#10685]
### Is your feature request related to a problem? Please describe.
Hello, from the Media tab, it is possible to configure the media folder. It works as long as we don't exit the tab.

Just go to the "All Files" tab and back to the "Media" tab for my setting to be lost. I see all the media again.

### Describe the solution you'd like
I would like my settings to be retained.

**Comment by e0328eric** [comment]
This is still not implemented while ios versions already have.

**Comment by joshtrichards** [comment]
Fixed in #11819
