### ISSUE TITLE
High cellular data usage even when wifi upload only selected

### ISSUE THREAD

**Issue by atd85** [nextcloud/android#1068]
### Actual behaviour
Very high cellular data usage even when upload via wifi only option is selected and no other file transfers are done over cellular data.  I'm 3 weeks into my billing cycle and Nextcloud has used 1.19GB of data. 

### Expected behaviour
Very little or no cellular data should be used if uploads are done over wifi only and no manual transfers are ever done. 
 
### Steps to reproduce
1. Install the app
2. Check data usage after some time.

### Environment data
Android version: 7.1.2

Device model: Nexus 5x

Stock or customized system: Stock

Nextcloud app version: 1.4.3

Nextcloud server version: Owncloud 9.1.4 RC2 (cannot migrate to NextCloud due to outstanding issues with the NC server)

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

Screenshot of issue - http://imgur.com/mJh8aJO

**Comment by AndyScherzinger** [comment]
Oh dear, that shouldn't happen except for two situation I can think of where this might be an issue. Do you:

* upload very large files which might have started uploading while being on a wifi connection and then left the network so the device switched over to cellular?
* have a fresh install on the device and the account on the server has a massive amounts of files and folders?

cc @tobiasKaminsky @mario

**Comment by atd85** [comment]
If I drop wifi connectivity while uploading, the transfer errors and it never resumes, even when reconnected to wifi.  It's one of a few bugs with the auto upload that many have reported (including myself), so I don't think thats an issue.  Even if I uploaded every picture/video I take with my phone over cellular data, I'm not sure if it would be much over a gigabyte in the ~3 week time frame. 

I've had the app installed for a couple months now.  I had the same problem last month (I don't remember the exact amount of data that was used), but I thought maybe it was a fluke, so when I noticed it continuing I finally got around to posting the issue. There hasn't been any change on my server for several months and I'm using the same user account. 

Thanks!

**Comment by AndyScherzinger** [comment]
@atd85 do you see any (strange) behavior in the server log files which would hint to the Android client accessing the server in a massive way?

@mario @tobiasKaminsky do you have an idea about why this might happen or what might be happening?

**Comment by atd85** [comment]
I don't see anything obvious, but maybe I'm missing it.  What specifically should I be looking for?

**Comment by sheyll** [comment]
I have had issues with data usage, too.

**Comment by tobiasKaminsky** [comment]
Can you give us some details of your server? how many ~ files/folders? Any external mounted folders?

**Comment by detly** [comment]
I noticed this too, and in my case it was definitely due to the app not respecting the auto-upload only over wifi setting. I'm running Cyanogenmod 13, which seems to do a reasonable job of smoothly switching over to mobile data when you move out of wifi range. I think this is related to #1105 .

This is pretty dire; if you're charged for excess data (as I am), the app can cost you a *lot* of money unexpectedly.

**Comment by mario** [comment]
Dear users,

thank you for your patience. After lots of work, we’re super excited to be able to give you a test version with new auto upload implementation. Keep in mind we will only accept bugs related to Auto Upload in this APK, as other things might be broken.

https://cloud.nextcloud.com/s/ftZraTruRQjTe0R

This is a dev APK so it will not overwrite your existing play store/f-droid APK unless you’re already running dev version. Also, you might need to remove your existing dev version before installing this one.

Explanation of the current functionality:
- added support for custom folders
- separated image and video folders
- checks for new files happens every 15-20 minutes
- automatic retry every 15-20 minutes or when you force close/open the app
- automatic pause once network is changed (untested!)
- significantly less battery usage

All and any testing is more than appreciated, especially with large and ever-going files like Videos. (like, try to record a 30 min video).

Let me know if you’ve got any questions.

Cheers,
Mario

**Comment by detly** [comment]
> Let me know if you’ve got any questions.

Nice work! I'll try it out soon. One question though — does this *only* affect the auto-upload functionality, or should I also expect to see differences in manual uploads? Specifically, should the manual uploads also have better "resume after network problems" behaviour, better background behaviour, etc?

**Comment by mario** [comment]
I'd have to check to be honest since I never do manual uploads. If they go into the usual upload queue (and afaik they should) then they also have all these improvements.

**Comment by detly** [comment]
I use it to get existing photos and videos uploaded before activating auto upload, since the auto upload only uploads new files since it was activated. I'll try it out and see.

**Comment by detly** [comment]
@mario Do you want me to file bugs against this version here, or in a separate issue?

**Comment by mario** [comment]
New is fine

**Comment by tobiasKaminsky** [comment]
No response within the last month, therefore closing.
Please feel free to reopen with additional infos, if the problem still exists.

**Comment by ma3oun** [comment]
Hi, I'm having the same problem on my Fairphone 4. I have set up a personal Nextcloud server on a RaspberryPi 4 and I use the Android client app on a Fairphone 4, with "Wifi only" option selected for media synchronization. However, the app seems to ignore the "Wifi only" option and always uploads the data to the server.
