### ISSUE TITLE
Open links to Nextcloud files in the app

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/android#1069]
When you get a link to a file it's opened in the browser. When it's a local link or file you have access to on a server you know, it could be opened in the Android app, right?

Much like for example Youtube has a hook to open Youtube links from emails in the Youtube app. The tricky part of course is that the domains are variable since Nextcloud is self-hosted. Is there a way to register the domains from your accounts for this?

**Comment by AndyScherzinger** [comment]
Unfortunately no :(
Link-patterns need to be "hardcoded" into the app's definition at build time (this is what we did for the login-URLs). So if it is a standard http/https URL we can detect its possible relevance for Nextcloud :(

Sorry 😿

**Comment by jancborchardt** [comment]
Damn :( that will then be a major drawback. I gjess it's also not possible with wildcards like saying all cloud.*.* domains could work?

Also not possible on iOS @marinofaggiana?

**Comment by mario** [comment]
This is actually possible but needs to be done on the server side first. If user-agent is ours, just rewrite all links inside NC instance to point to something like nc://serverpath/filepath and we can do it :P

**Comment by AndyScherzinger** [comment]
@mario how can this be achieved? :)

**Comment by AndyScherzinger** [comment]
Ah well, yeah, custom protocol work and are already in place, but that wouldn't be a classic http/https hyperlink...

**Comment by mario** [comment]
@AndyScherzinger sure, but why does it has to be? The general idea is to get this feature. This is how it can be done. Server:

- detect mobile browser
- rewrite links
- done

**Comment by AndyScherzinger** [comment]
@mario that depends on the source, from what I understood:

> links from emails

that would mean it is either a Nc generated mail which would then need to put in a "web-URL" and an "app-URL". Then of course it could work. Furthermore if you would browse the webUI with your mobile device we can't detect if the app is installed so if it is not installed the user would still need to get http/https links to be able to navigate to the file, right?

I am not against having this feature rather it opposite. I think this would be really great and offer a more seamless integration on the device. My point was rather about me not seeing how we can implement this, since youtube works because it is a single domain where a standard, hard-coded http/https+tld-domain filter works.

**Comment by jancborchardt** [comment]
Aaah I think I understand what @mario means. The web app knows if it's an instance you have access to and could offer an »Open in app« link. :)

**Comment by AndyScherzinger** [comment]
@jancborchardt that would work of course :+1:

**Comment by mario** [comment]
Btw. i forgot to comment on this ... we *can* know if an app is installed by checking if we have something that can handle nc:// ;)

**Comment by AndyScherzinger** [comment]
Nextcloud can :) Since we already have this for Login-URLs 😁

**Comment by egeu5** [comment]
#2562 can be referenced.

**Comment by tuxcrafter** [comment]
Is it possible to get deep linking working on Android or iOS?

I need links like https://cloud.example.nl/nextcloud/index.php/f/2872 to be opened on mobile phones with the NextCloud App.

What is the status of this request?

**Comment by Giplat** [comment]
We really need this functionality too. From a business perspective it completely ruins our users' workflow. Because we use 2FA it's incredibly cumbersome to open links from email in the browser. Please please fix this, thank you.

**Comment by AndyScherzinger** [comment]
As stated before and in the referenced issues too: standard *`http/https` links won't work ever* (for technical reasons), it'll *only work for `nc://...` link* which is a **feature @tobiasKaminsky started working on**.

**Comment by tobiasKaminsky** [comment]
> We really need this functionality too. From a business perspective it completely ruins our users' workflow. Because we use 2FA it's incredibly cumbersome to open links from email in the browser. Please please fix this, thank you.

This may be possible with a branded app, which we offer as part/extension to our Enterprise subscription (https://nextcloud.com/enterprise/).

**Comment by szaimen** [comment]
> As stated before and in the referenced issues too: standard http/https links won't work ever (for technical reasons), it'll only work for nc://... link which is a feature @tobiasKaminsky started working on.

Is there an example how this nc:// link will look like? 

I think if the the coherent link to

`https://cloud.example.nl/nextcloud/index.php/f/2872`

Would look like

```
nc://f/2872
Or
nc://index.php/f/2872
```

Then you could easily create links that work with the app.

**Comment by AndyScherzinger** [comment]
This is actually working but broken for Android 12 - see https://github.com/nextcloud/android/issues/9346

**Comment by whitephoenix117** [comment]
Technically I think this is possible, but I dont know how the user experience would be

**Comment by whitephoenix117** [comment]
@szaimen  

The NC:// workaround sounds great, but we still need a way to get a standard TLD URL to get converted. I have a few thoughts.

1. A redirecting browser extension, to take myNCdomain.tld/foo/bar --> NC://foo/bar a quick search found something like this that [already exists](https://addons.mozilla.org/en-US/firefox/addon/redirector/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search). 
2. When a URL is opened based on the device user agent, and probably some server config. The NC server can redirect the client to a NC://*** URL forcing the app to pick it up. To avoid the main issue with login this would need to preceded any type of OAuth/ login redirect.

**Comment by maninthemiddle01** [comment]
[#5915](https://github.com/nextcloud/android/issues/5915) as well as [https://github.com/nextcloud/server/issues/51851](https://github.com/nextcloud/server/issues/51851)](https://github.com/nextcloud/server/issues/51851) could be referenced
