### ISSUE TITLE
Sort favorite files first in the list

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/android#107]
Favoriting is not very integrated at the moment. Only an indicator, we can do better here.

Better integration without needing to switch to a separate view would be to always sort the favorited items of a the current folder up top.

**Comment by AndyScherzinger** [comment]
Dev-hint: This should be done for FileDisplayActivity.java so the sorting then needs to incorporate the chosen way of sorting (alphabetical, date, size) as a second order criteria and favorite (yes/no) as a first order criteria.

**Comment by ryanwr** [comment]
I'll work on this

**Comment by AndyScherzinger** [comment]
implemented, reviewed and tested, part of the next stable release 1.4.0

**Comment by jancborchardt** [comment]
@ryanwr @AndyScherzinger awesome! :) Now we should get this in the web interface as well, cc @nextcloud/designers for https://github.com/nextcloud/server/issues/1802
