### ISSUE TITLE
Selecting "Automatic Uploads" crashes app instantly

### ISSUE THREAD

**Issue by e-alfred** [nextcloud/android#1070]
### Actual behaviour
If I click on "Automatic Uploads" the app crashes instantly.

### Expected behaviour
"Automatic Uploads" pane should show up.
 
### Steps to reproduce
1. Install Nextcloud Android App  stable 1.4.3 or dev 20170602 and set up a Nextcloud server in it.
2. Try opening up "Automatic uploads" where the app crashes immediately

### Environment data
Android version: 6.0.1

Device model: BQ M5

Stock or customized system: Stock ROM

Nextcloud app version: 1.4.3 and 20170602

Nextcloud server version: 12.0.0

**Comment by AndyScherzinger** [comment]
@e-alfred can you provide a logcat of the crash or send a crash report (in case the 1.4.3 is installed via Google Play with a comment hinting at the github issue)? Just asking since this is the very first report/occurrence of this issue and all versions are working fine at least on my device and emulators.

**Comment by e-alfred** [comment]
I sent the logs with the Google Play version and attached this Github issue number.

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger I tried to find this in google dev console, but not succeeded.
Can you give me a hand here?

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky I couldn't find the report either. The only thing I found which fits the symptom is:
```
ava.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media from pid=17978, uid=10167 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
	at android.os.Parcel.readException(Parcel.java:1620)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
	at android.content.ContentResolver.query(ContentResolver.java:502)
	at android.content.ContentResolver.query(ContentResolver.java:445)
	at com.owncloud.android.datamodel.MediaProvider.getMediaFolders(MediaProvider.java:59)
	at com.owncloud.android.ui.activity.FolderSyncActivity$1.run(FolderSyncActivity.java:133)
	at java.lang.Thread.run(Thread.java:818)
```

**Comment by AndyScherzinger** [comment]
This has been reported for Android 6 only and the following devices:

* LG G4 (p1)
* Nexus 5 (hammerhead)
* Moto G(4) Plus (athene_f)
* Galaxy TabS 10.5 (chagallwifi)
* Galaxy Tab S2 8.0 (gts28velte)
* Galaxy S5 mini (kminilte)
* Galaxy On5 (on5ltetmo)
* MI MAX (helium)
* Moto G(4) (athene)

**Comment by tobiasKaminsky** [comment]
> requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()

How can this happen? Someone installs the app, revoke "external storage" permission and then enters auto upload? This indeed crashes and I will fix it.
Nothing should crash our app ;-)

**Comment by AndyScherzinger** [comment]
Merged to master for the next release
