### ISSUE TITLE
auto sync battery optimization bug

### ISSUE THREAD

**Issue by thiat1998** [nextcloud/android#10712]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

I turn off battery optimization
but, It keeps telling me to disable it.
![Screenshot_20220905-081725_Nextcloud](https://user-images.githubusercontent.com/112832077/188337282-a8343e4c-f151-4dc4-8a96-2c06da439c48.jpg)

### Expected behaviour

app update

### Actual behaviour

all battery optimization turn off

### Android version

12

### Device brand and model

Samsung galaxy s21 ultra

### Stock or custom OS?

Stock

### Nextcloud android app version

20220827

### Nextcloud server version

new

### Using a reverse proxy?

I don't know

**Comment by KomelT** [comment]
I am having same problem on Samsung Galaxy S9+, S10 and A52S.

**Comment by joshtrichards** [comment]
If you're still experiencing this can you provide screenshots from your app's battery usage settings? Sometimes we'll also generate this warning if unable to determine battery optimization status.
