### ISSUE TITLE
Crash on low free ROM memory 

### ISSUE THREAD

**Issue by Dsw77** [nextcloud/android#10722]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

After opening the nextcloud app stays unresponsive and crashes after a while. This happens when there is low disk (ROM) memory available. 

### Expected behaviour

Open the app and stay open without issues. 

### Actual behaviour

App crash

### Android version

11

### Device brand and model

Huawei P30 pro 

### Stock or custom OS?

Stock

### Nextcloud android app version

Latest

### Nextcloud server version

24

### Using a reverse proxy?

No

**Comment by AlvaroBrey** [comment]
Do you have a crash log? Additionally, how low is your disk space?
