### ISSUE TITLE
folder view broken when sharing to empty folders >= 3.21.0 (3.20.3 is fine)

### ISSUE THREAD

**Issue by kolAflash** [nextcloud/android#10728]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Open Nextcloud Android app.
2. Create an empty folder `test` in your root folder.
3. Open another app which can share files. E.g. open https://en.wikipedia.org/wiki/Jupiter in Firefox.
4. Long press the photo of Jupiter and choose `Share image`.
5. Choose Nextcloud and walk to the root folder.
6. Click the empty folder `test`.

### Expected behaviour

Show the content of the empty folder `test`.

### Actual behaviour

Now the top of the screen will say `test` but you will still see the contents of your root folder.
You don't have to start from the root folder. Just create an empty folder anywhere and you can reproduce the bug.

<details>
<summary>screenshot</summary>

![Screenshot_20220911-140826_Nextcloud](https://user-images.githubusercontent.com/3355089/189526859-3f9e7f14-2a5b-4278-b7f4-54970cef043d.png)

</details>

### Android version

Android 13

### Device brand and model

Google Pixel 4a

### Stock or custom OS?

Stock

### Nextcloud android app version

3.21.0

### Nextcloud server version

24.0.5

### Using a reverse proxy?

No

### Additional information

**REGRESSION**

Bug happens with [PIxel 4a](https://en.wikipedia.org/wiki/Pixel_4a) (running stock Android-13) and with [Fairphone 3 Plus](https://en.wikipedia.org/wiki/Fairphone_3) (running [/e/OS 1.0](https://e.foundation/) - Android-10).

**Comment by uusijani** [comment]
Still present in Nextcloud 3.21.2. My device is a Samsung A9 running Android 10.

**Comment by svenb1234** [comment]
Confirmed for 3.21.2

**Comment by AlvaroBrey** [comment]
No need to bump the issue: it's approved and still open, we haven't fixed it yet.

**Comment by abdusalamApps** [comment]
I fixed it now. Will create a PR soon.

**Comment by abdusalamApps** [comment]
PR https://github.com/nextcloud/android/pull/10989
