### ISSUE TITLE
Refreshed media page as icons hadn't loaded 

### ISSUE THREAD

**Issue by cakonopka** [nextcloud/android#10733]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Open app
Go to media page
Some 15 or so images had no thumbnails
Refreshed page
App crashed

### Expected behaviour

Page to refresh and display thumbnails

### Actual behaviour

App crashed and no thumbnails 

### Android version

12

### Device brand and model

Oneplus9Pro 

### Stock or custom OS?

Stock

### Nextcloud android app version

3.21.2

### Nextcloud server version

24.0.2

### Using a reverse proxy?

No

**Comment by AlvaroBrey** [comment]
Thanks for your report. However I can't reproduce it. Can you get a logcat from the Android device so we can see if there's any errors? Instructions here: 

https://github.com/nextcloud/android#getting-debug-info-via-logcat-mag

Feel free to search and replace the server URL, username and other file names in the output.
