### ISSUE TITLE
Use root permission (on rooted devices) to access private directories

### ISSUE THREAD

**Issue by andreapx** [nextcloud/android#10731]
I need to backup files of some apps that store them in /android/data/... but this folder is not accessible by thew Nextcloud app.
My phone is rooted, if Nextcloud could t ask for the root permission, it would be great!
Thanks!

**Comment by AlvaroBrey** [comment]
Ref: #9988

**Comment by andreapx** [comment]
I've seen that issue, but there's not track of the use of root.
Will it be possible for Nextcloud app to use root permissions?

**Comment by andreapx** [comment]
@joshtrichards 
Nouuuuuuuu!!!
PLEASE!!!!

**Comment by joshtrichards** [comment]
Duplicate of #8650 
Please subscribe to that issue to track progress and give it a :+1: to express your interest.
