### ISSUE TITLE
Cant upload from android app

### ISSUE THREAD

**Issue by konkrash** [nextcloud/android#10734]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

When either trying to manually upload or set automatic  uploads, nothing happens. 
Tried restart, shutdown phone and reinstalling the app, no luck.

### Expected behaviour

Upload photos/files

### Actual behaviour

Pop up for not enough free space, accept to move files instead, Nothing happens.

### Android version

10

### Device brand and model

Galaxy a7 sm-a750f

### Stock or custom OS?

Stock

### Nextcloud android app version

3.21.2

### Nextcloud server version

24.0.5

### Using a reverse proxy?

No

### Additional information

No android or server log files.
[Screen recording ](https://drive.google.com/file/d/12DTB0aTSO2EmcgBY97A9e9Tj_yGtVkII/view?usp=drivesdk)

**Comment by AlvaroBrey** [comment]
Unfortunately not much can be seen in your video as the screen recording seems to be blocked (for example if you set a PIN lock in the app it will be blocked).

Do you actually have your space almost full?
