### ISSUE TITLE
Crashed opening side menu

### ISSUE THREAD

**Issue by cakonopka** [nextcloud/android#10735]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Opened app
Went to open side menu
App crashed 

### Expected behaviour

Menu to open

### Actual behaviour

Crashed 

### Android version

12

### Device brand and model

Oneplus9Pro 

### Stock or custom OS?

Stock

### Nextcloud android app version

3.21.2

### Nextcloud server version

24.0.2

### Using a reverse proxy?

No

**Comment by AlvaroBrey** [comment]
Not much I can do here, as I can't reproduce it and there's no logs. Can you get a logcat from the Android device so we can see if there's any errors? Instructions here: https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat-mag

Feel free to search and replace the server URL, username and other file names in the output.
