### ISSUE TITLE
Inserting an image in a OnlyOffice document does not work in the Android app of Nextcloud

### ISSUE THREAD

**Issue by Zandt73** [nextcloud/android#10744]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Open a OnlyOffice text document
2. Insert an image from a directory.

### Expected behaviour

Inserting an image in a OnlyOffice document does not work in the Android app of Nextcloud.

### Actual behaviour

If you call the function for inserting an image from a directory, the file selection is not called, unfortunately nothing happens, and you jump back to the document. If I do the whole thing in the mobile browser, inserting an image works without any problems.

### Android version

12, 11

### Device brand and model

Samsung Tab S7 and S6 lite

### Stock or custom OS?

Stock

### Nextcloud android app version

3.21.2

### Nextcloud server version

23.0.4

### Using a reverse proxy?

Yes

### Android logs

[logcatOutput.txt](https://github.com/nextcloud/android/files/9591393/logcatOutput.txt)

**Comment by AndyScherzinger** [comment]
cc @tobiasKaminsky
