### ISSUE TITLE
Search for tags detected by recognize

### ISSUE THREAD

**Issue by ralfi** [nextcloud/android#10742]
nextcloud recognize detected and designed tags like aircraft, landscape and so on very well. It would be helpful if we can searching for tags like these in the Android app if possible.

**Comment by szaimen** [comment]
This should be possible with NC25 IIRC.
See https://github.com/nextcloud/server/pull/26813

**Comment by ralfi** [comment]
Thanks, i'am really looking forward to this...

**Comment by joshtrichards** [comment]
Tags are now searchable.
