### ISSUE TITLE
Daily backup does not work

### ISSUE THREAD

**Issue by vcbranco** [nextcloud/android#10749]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Configure contacts automatic daily backup

### Expected behaviour

Should make and send the backup file to the server

### Actual behaviour

Nothing happens

### Android version

Android 10 and 12

### Device brand and model

Nokia 7.1 (Android 10) and Nokia G60 5G (Android 12)

### Stock or custom OS?

Stock

### Nextcloud android app version

3.21.2

### Nextcloud server version

24.0.5

### Using a reverse proxy?

No

### Android logs

Can not locate the Nextcloud Android log file

### Server error logs

```bash
There is nothing related to the issue
```

### Additional information
The backup works manually without any problem

**Comment by strugee** [comment]
@vcbranco there isn't enough information here to determine what the bug is. You'll need to post, at the very least, `adb logcat` logs (this is what's meant by "Android logs").

**Comment by Fishermanjb** [comment]
doesn't work for me either, Galaxy A53 with the newest app version. Also the Calender Backup has only the birthdays in it, not the rest of my data. 
And another question, is there a good way to backup your tasks?

Greets Jonas

**Comment by Fishermanjb** [comment]
Sorry i wrote it a bit in a hurry.
The daily automated backup doesn't work. And in the manual backup there are only the birthdays. 
I can post the adb logs propably monday.
