### ISSUE TITLE
I can't see any files that another shared with me, pls help me!!

### ISSUE THREAD

**Issue by bangnasia** [nextcloud/android#10750]
### Additional context

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by strugee** [comment]
@bangnasia if you believe you're encountering a bug, please edit your GitHub issue to have all the information that the template requests. If you're just looking for help, the forums are a much better place to ask questions: https://help.nextcloud.com/

Thanks for contributing to Nextcloud!
