### ISSUE TITLE
Sending log issue

### ISSUE THREAD

**Issue by OlivierS1** [nextcloud/android#1076]
### Actual behaviour
-Tell us what happens
Under Nextcloud Dev 20160609, after requesting the log to be sent and pressing the "Upload" button, upon returning to the log page and pressing the "elete history", if the app is still in the process of seting up transfer, then the content of the log will be cleared.

### Expected behaviour
-Tell us what should happen
I think there should be a mechanism that would prevent the log being transmitted to be erased.
 
### Steps to reproduce
1. Access Settings.
2. Press "Logs"
3. Press "SEND HISTORY"
4. Select how to send it (ie. Nextcloud Dev), and select relevant account.
5. Select location and press "UPLOAD"
6. Without waiting, press "DELETE HISTORY"

Check content of logs before and after deletion on server. The file should be empty.

### Environment data
Android version:

Device model: 
LG 3 LG852

Stock or customized system:
Stock

Nextcloud app version:
Nextcloud  Dev 20170609

Nextcloud server version:
NC 12

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
As logs are only enabled in the dev version I think it is a corner case and as we lack a little bit of men power this is something that can be included if someone will help us.

**Comment by joshtrichards** [comment]
https://github.com/nextcloud/android/issues/1076#issuecomment-310998887

**Comment by joshtrichards** [comment]
Hi @OlivierS1 - Thanks for your contribution. This one is unlikely to ever become a priority, but it's still a reasonable idea. :) Closing since it hasn't gotten traction for 6+ years, but anyone interested is still welcome implement a fix/enhancement and send in a PR.
