### ISSUE TITLE
Android integration

### ISSUE THREAD

**Issue by portalninja2** [nextcloud/android#10769]
I'm always frustrated when i would Export an PDF or Docx because the Nextcloud app crashes and doesnt work good, why dont exist an Integration at the File Browser from android, like apple. I know that samsung have an other file browser then Xiaomi but maybe its possible to make an Integration for the popular Tablets, Xiaomi, Samsung etc

The second issue is, that when comes a fix for the Nextcloud app, then its workinhgBUT local files are not in the same App, maybe its an other solution when the app have a local file Browser integrated.

I hope its possible, have a nice day!

**Comment by AlvaroBrey** [comment]
Not entirely sure what you are suggesting here, can you please elaborate a bit what the enhancement would be like?  It sounds like you would like to browse Nextcloud files from the Android Files browser; that is already possible if the Nextcloud app is installed and logged in.  Or is it something else I'm missing?

**Comment by portalninja2** [comment]
Yeah, thats rights, i would have an Integration in the Android File Browser, because that doesnt exist (sorry for German Tablet)

![Screenshot_2022-09-30-09-26-35-378_com.mi.android.globalFileexplorer.jpg](https://user-images.githubusercontent.com/65617101/193215206-9893dda4-0716-48a9-b2e8-40d3cb1b9401.jpg)

**Comment by AlvaroBrey** [comment]
> Yeah, thats rights, i would have an Integration in the Android File Browser, because that doesnt exist (sorry for German Tablet)

It _should_ exist if the app is installed and logged in. See screenshot below for the default AOSP Files app. Can you file this as a bug instead?

<details>
<summary>Screenshot</summary>

![files_nextcloud](https://user-images.githubusercontent.com/8677743/193217305-da86837d-9adc-4497-817b-b285186c8fca.png)

</details>

**Comment by portalninja2** [comment]
This App does Not exist on ja Tablet.... Where i can "become" this App?

**Comment by AlvaroBrey** [comment]
> This App does Not exist on my Tablet.... Where i can "become" this App?

This is the default android Files app. Your tablet may not have it depending on brand customizations. Not sure if the MIUI app you're using even supports third party file storage.

**Comment by portalninja2** [comment]
You get it ._. i have not the Default App, NO Android System use this really anymore, Samsung dont use this app to (Tab A7 and Galaxy a21s) so thats the reason why i opened this 😉I have btw MIUI 13 global on an mi pad 5 and no the MIUI or Samsung File Browser doesnt support third Party file storage, thats the reason why i asked 😉


Von: Álvaro ***@***.***>
Gesendet: Freitag, 30. September 2022 10:13
An: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Betreff: Re: [nextcloud/android] Android integration (Issue #10769)


This App does Not exist on my Tablet.... Where i can "become" this App?

This is the default android Files app. Your tablet may not have it depending on brand customizations. Not sure if the MIUI app you're using even supports third party file storage.

**Comment by portalninja2** [comment]
Oh sorry Outlook, like to make random things... I mean i dont know maybe the App Support it but i dont know, thats why i ask....

**Comment by portalninja2** [comment]
Hey, iam back, i found a solution by myself.

For all Xiaomi User try to install this from Aptoide: [https://files-aosp-studio-llc.de.aptoide.com/app?store_name=catappult&app_id=46713714]()

for me worked fine. I have now an Shortcut to the Android Google File Browser. On the Mi Pad 5 is this explorer installed, but hidden, i cant find it. This make an easy Shortcut to it as an App.

Have a nice Day bye
