### ISSUE TITLE
Double slash in URLs

### ISSUE THREAD

**Issue by bohwaz** [nextcloud/android#10774]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Use Android app. Watch HTTP traffic.

### Expected behaviour

Normal URLs

### Actual behaviour

The app is adding an extra slash after the user part of the URL:

```
 PROPFIND /remote.php/dav/files/bohwaz//Photos/
```

### Android version

any

### Device brand and model

any

### Stock or custom OS?

Stock

### Nextcloud android app version

any

### Nextcloud server version

any

### Using a reverse proxy?

No

**Comment by AlvaroBrey** [comment]
This is known (comes from [here](https://github.com/nextcloud/android-library/blob/8cd3436c291f102a6443818f9aa6e15a9070244b/library/src/main/java/com/nextcloud/common/NextcloudUriDelegate.kt#L64-L64)), but it hardly qualifies as a bug. Though not "correct", most web servers (including apache and nginx) just treat the double slash at a single slash.

**Comment by bohwaz** [comment]
It's not a problem for the user but is still an issue as the client should do well-formed requests :)
