### ISSUE TITLE
Notes app on GrapheneOS not opening (shows SSO error for Files app)

### ISSUE THREAD

**Issue by Mat001** [nextcloud/android#10787]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. on GrapheneOS, Pixel 4 install Nextcloud and Notes apps from f-droid
2. log into Nextcloud synchronization client
3. Check that synchronization app is working
4. open Notes app
5. click Choose Account
6. Select your account and tap OK
7. Notice Error pop up saying:
Your Nextcloud Files app currently does not support the single sign on feature. Please update it: https://google.com/store/apps/details?id=com.nextcloud.client

At the bottom of the phone screen a java exception appears:
"Attempt to invoke virtual method 'java.lang.String android.content.Intent..." (truncated)

### Expected behaviour

Should be able to log into the Notes app and see my notes.

### Actual behaviour

Error pop shows up saying:
Your Nextcloud Files app currently does not support the single sign on feature. Please update it: https://google.com/store/apps/details?id=com.nextcloud.client

At the bottom of the phone screen a java exception appears:
"Attempt to invoke virtual method 'java.lang.String android.content.Intent..." (truncated)

### Android version

13

### Device brand and model

Pixel 4

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

20221001

### Nextcloud server version

23.0.0

### Using a reverse proxy?

I don't know

### Server error logs

```bash
Attempt to invoke virtual method 'java.lang.String android.content.Intent...
```

### Additional information

GrapheneOS, latest stable version.

Notes worked fine on LineageOS few months ago.

Nextcloud synch client app works fine, I am able to access notes inside it.
But Notes app itself not logging me in.
After the error, the spinner icon keeps spinning, until I force stop the app.

Unable to get logs.

**Comment by panomitrius** [comment]
Have the same issue on Linageos 19.

**Comment by joshtrichards** [comment]
See https://github.com/nextcloud/notes-android/issues/1579#issuecomment-1250357489

Details for those curious:

https://github.com/nextcloud/notes-android/issues/1579
https://github.com/nextcloud/notes-android/issues/1547
https://github.com/nextcloud/Android-SingleSignOn/issues/470
