### ISSUE TITLE
Empty content screen icon colors

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/android#1078]
The empty content screen icons are partly a bit off, for example the icon for favorites as well as uploads is blue, which both looks a bit strange.

- Every empty content icon should be 50% grey
- Except favorites which should be the yellow star
- And Folders/files which should be Nextcloud blue

Just like on the server. :)

**Comment by AndyScherzinger** [comment]
That is how it has been implemented actually but the theming PR by @tobiasKaminsky changed the coloring. Since no colors all empty content icons on the fly using the primary color...

**Comment by mario** [comment]
Maybe it shouldn't do that? :)

**Comment by AndyScherzinger** [comment]
It should do it for the light blue icons only.

**Comment by mario** [comment]
Yup

**Comment by jancborchardt** [comment]
Yeah, empty content icons / grey icons should not be touched. :) Except the folder which is blue of course.

**Comment by AndyScherzinger** [comment]
@mario @tobiasKaminsky please see #1083

**Comment by jancborchardt** [comment]
Thanks! :)

**Comment by AndyScherzinger** [comment]
Always a pleasure :D
