### ISSUE TITLE
Quicker and more pleasant picture download/view flow

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/android#1079]
Opening an image, every time it shows the Loading view + bar, then flashes to this:
![screenshot_2017-06-10-16-14-19](https://user-images.githubusercontent.com/925062/27003567-87eb4940-4df9-11e7-8d37-2665ed6e4d40.png)
And only then shows the actual image.

Instead for a much smoother flow:
1. As the downloading view, show the thumbnail (which is already there) in big, and a loading spinner overlayed.
2. Directly change it to the actual image as soon as it’s downloaded.

**Comment by tobiasKaminsky** [comment]
The spinner wheel is only shown while the image is scaled down to fit on the screen, it is independent of downloading.
Try it with a much smaller image or with a faster device and you will notice a shorter/ none loading spinner.

**Comment by jancborchardt** [comment]
Ok, then I'll adjust point 1 ;)

> As the downloading view **and while the image still needs to be scaled to fit the screen**, show the thumbnail (which is already there) in big, and a loading spinner overlayed.

The key is that it needs to be one smooth flow. Tap the image in the list -> get to see it. :)

**Comment by joshtrichards** [comment]
Fixed in #1710
