### ISSUE TITLE
Android 6.0.1 connection error to internal server. 

### ISSUE THREAD

**Issue by johnnygeling** [nextcloud/android#108]
### Actual behaviour

-Tell us what happens
No connection made to owncloud server on internal network via internal wifi. Server is accessible with webdav client FolderSync and via browser. 
Owncloud log and apache access log doesn't show any connection activity. 
Using the connection over LTE, there is normal connection with the owncloud server. 

Doing this on a android version 5.1, the access is normal. 
### Expected behaviour

-Tell us what should happen
Normal connection over to internal server over internal wifi netwerk
### Steps to reproduce
1. 
2. 
3. 
### Environment data

Android version:
6.0.1

Device model: 
Galaxy Tab 2 LTE

Stock or customized system:
Stock

Nextcloud app version:
1.1.0 (beta channel)

Nextcloud server version:
#### Web server error log

```
Insert your webserver log here
```
#### Nextcloud log (data/nextcloud.log)

Nothing logged

Insert your Nextcloud log here

```
```

**Comment by Marcwa19197** [comment]
Maybe something like my issue? https://github.com/nextcloud/android/issues/112

**Comment by johnnygeling** [comment]
Looks similar. I also connect through my want to my own server on the same network. 

The test server on owncloud.org is accessible.

**Comment by tobiasKaminsky** [comment]
Could this be related to ipv6?

**Comment by tobiasKaminsky** [comment]
No response within the last month, therefore closing.
Please feel free to reopen with additional infos, if the problem still exists.
