### ISSUE TITLE
»Nextcloud is running« extra notification

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/android#1080]
Every time I upload files, I get this notification:
![img_20170610_162503](https://user-images.githubusercontent.com/925062/27003590-f06da92c-4df9-11e7-8e79-39c6eee9e6b1.jpg)

Can we remove that notification? It’s an additional one which is not really needed, plus the icon is not properly shown.

**Comment by mario** [comment]
Sorry, but this is not a bug. We have to show that here if we want to have any chance of guarantee that the upload will finish.

There's a way around it of course (using jobs for uploads, instead of a service), but it'll be many moons before this is done.

**Comment by jancborchardt** [comment]
Ah ok. Can we then make the notification nicer? Like use the actual Nextcloud icon in place of the square, maybe even with blue background color?

Also, is it possible to set a more descriptive title like »Nextcloud is transferring data" for example?

_Sent from my Motorola XT1039 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by mario** [comment]
We *might* be able to set the notification icon - it should already be there, dunno why it's not working.

Unfortunately, we cannot change the title.

**Comment by jancborchardt** [comment]
I'm guessing it uses the app icon monochrome version - which in mlst cases is a rounded square. ;) Should be juat the white logo, would be cool if you can check.

**Comment by tobiasKaminsky** [comment]
This is a screenshot of samsung s5 neo and master branch.
![filehkuwjs](https://user-images.githubusercontent.com/5836855/27532019-19d42fae-5a5f-11e7-915a-cb9bf16748c3.png)
