### ISSUE TITLE
empty folder - create folder empty message missing

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#1084]
on master - create an empty folder and open it:

- loading icon keeps being shown instead of showing the empty message + icon

![device-2017-06-12-233146](https://user-images.githubusercontent.com/1315170/27056188-647e8498-4fc7-11e7-8d70-f7e94247378e.png)

**Comment by mario** [comment]
This I know. Assigning it to myself.

**Comment by tobiasKaminsky** [comment]
PR is https://github.com/nextcloud/android/pull/1213

**Comment by AndyScherzinger** [comment]
Merged
