### ISSUE TITLE
share with Nextcloud app - empty folder doesn't show the no empty message for create folder

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#1085]
on master - share a file with Nextcloud and navigate to an empty folder:

- shows empty screen while it should show the empty message "create folder/upload" + create folder icon

![device-2017-06-12-233432](https://user-images.githubusercontent.com/1315170/27056281-c19b0dcc-4fc7-11e7-8cf4-ee6741f9f506.png)

**Comment by mario** [comment]
Create folder icon? Do we have that? o.O can you show me how it usually looks when it works? (Maybe by checking out 1.4.3 and screenshot?)

**Comment by AndyScherzinger** [comment]
Hmmm, doesn't work in 1.4.3 either, while this is the method that seems to not get called anymore

https://github.com/nextcloud/android/blob/master/src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java#L174

Icon is ```ic_list_empty_create_folder```

cc also @tobiasKaminsky

**Comment by AndyScherzinger** [comment]
@mario @tobiasKaminsky see here:
https://github.com/nextcloud/android/pull/449#issuecomment-266788320

**Comment by tobiasKaminsky** [comment]
Creating a new folder is done via the option menu. Do we want to have a FAB for this? Then we should open a new issue as it is not a bug but an enhancement.

Not showing "empty message" is maybe the same as #1084, so assigning to @mario.

**Comment by AndyScherzinger** [comment]
no FAB as this is not the primary action here just displaying right right empty content.

**Comment by tobiasKaminsky** [comment]
> /src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java@master#L174

The activity in question is not FolderPickerActivity but ReceiveExternalFilesActivity.
In https://github.com/nextcloud/android/pull/449#issuecomment-266788320 this is also not shown, although the picture is very similar:
UploadFilesActivity has move/copy dropdown
ReceiveExternalFilesActivity is copy only -> no dropdown

PR for this: #1214

**Comment by AndyScherzinger** [comment]
Merged
