### ISSUE TITLE
[CRASH] Java.Lang.NullPointerException, on ActivityTaskManagerService.reportAssistContextExtras

### ISSUE THREAD

**Issue by Mahdibenamor** [nextcloud/android#10863]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

We are using sentry and apocenter to monitor our app issues. and We found out that we have many crashes
With this name: 
Java.Lang.NullPointerException
Attempt to read from field 'int com.android.server.wm.TaskRecord.taskId' on a null object reference

stack trace: 

android.os.Parcel.createExceptionOrNull Parcel.java:2391
android.os.Parcel.createException Parcel.java:2369
android.os.Parcel.readException Parcel.java:2352
android.os.Parcel.readException Parcel.java:2294
android.app.IActivityTaskManager$Stub$Proxy.reportAssistContextExtras IActivityTaskManager.java:5765
android.app.ActivityThread.handleRequestAssistContextExtras ActivityThread.java:4169
android.app.ActivityThread$H.handleMessage ActivityThread.java:2291
android.os.Handler.dispatchMessage Handler.java:106
android.os.Looper.loop Looper.java:246
android.app.ActivityThread.main ActivityThread.java:8653
java.lang.reflect.Method.invoke Method.java
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run RuntimeInit.java:602
com.android.internal.os.ZygoteInit.main ZygoteInit.java:1130

### Expected behaviour

The app not lunching, and crashing. 

### Actual behaviour

According to the traces that I have the app crashes when it get started: 

Check this link: [https://sentry.io/share/issue/e475c5452920458ba4bffed38f688bc0/](url)

All the users that faces this crash are using **android 10**, **no other version**

### Android version

10

### Device brand and model

SM-A405FN, SM-A202F, SM-A750FN, Redmi Note 8 Pro, Redmi Note 8, Mi Note 10, Core-X4, 5002H_EEA

### Stock or custom OS?

Stock

### Nextcloud android app version

No reponse

### Nextcloud server version

No reponse

### Using a reverse proxy?

No

### Android logs

Stack Trace: 

Java.Lang.NullPointerException

Attempt to read from field 'int com.android.server.wm.TaskRecord.taskId' on a null object reference

Android.Util.AndroidException
Remote stack trace:
	at com.android.server.wm.ActivityTaskManagerService.reportAssistContextExtras(ActivityTaskManagerService.java:3809)
	at android.app.IActivityTaskManager$Stub.onTransact(IActivityTaskManager.java:2620)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)

### Server error logs

```bash
=
```

### Additional information

=

**Comment by AlvaroBrey** [comment]
That stacktrace contains nothing about the Nextcloud app. Why do you think it is related?

**Comment by nolt** [comment]
I have same crash when I want to view any folder with images.
Server: ver. 24.0.6

### App information
* ID: `com.nextcloud.client`
* Version: `30220090`
* Build flavor: `gplay`

### Device information
* Brand: `Xiaomi`
* Device: `umi`
* Model: `Mi 10`
* Product: `umi_eea`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `V13.0.6.0.SJBEUXM`

**Comment by AlvaroBrey** [comment]
> I have same crash when I want to view any folder with images. Server: ver. 24.0.6
> ### App information
> 
>     * ID: `com.nextcloud.client`
> 
>     * Version: `30220090`
> 
>     * Build flavor: `gplay`
> 
> 
> ### Device information
> 
>     * Brand: `Xiaomi`
> 
>     * Device: `umi`
> 
>     * Model: `Mi 10`
> 
>     * Product: `umi_eea`
> 
> 
> ### Firmware
> 
>     * SDK: `31`
> 
>     * Release: `12`
> 
>     * Incremental: `V13.0.6.0.SJBEUXM`

That's likely NOT this crash, but #10825  instead. Update your app and it should be fixed.

**Comment by nolt** [comment]
Well when I post this I had the newest available from Google Play. Today three is new version which resolves crashes.

**Comment by ZarVladimirII** [comment]
I have an Java.Lang.NullPointerException, but on different references on Android 11.
Version: `30220190`
F-Droid Update as today

Upload of pictures does not work too, already before todays update.
