### ISSUE TITLE
3.22.1: Dashboard widget recommend files has no content

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/android#10866]
create a widget
there is no content, on the recommend files widget, in the web app there is
![grafik](https://user-images.githubusercontent.com/24530680/197013564-20910a1c-337f-4ab3-8872-17e2cb5b4628.png)
![grafik](https://user-images.githubusercontent.com/24530680/197013653-11e3a4b2-0b70-4580-8256-b5d9de8fe587.png)

### Expected behaviour

show nice data

### Actual behaviour

no data

### Android version

13

### Device brand and model

Pixel 4a (5G)

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

322.1

### Nextcloud server version

25

**Comment by AlvaroBrey** [comment]
Looks like the server is returning an empty list. May be a server bug, needs more research.

**Comment by jakobroehrl** [comment]
You are probably right, I check on iOS. There the widget is empty, too

**Comment by AlvaroBrey** [comment]
Reported in https://github.com/nextcloud/recommendations/issues/563

**Comment by AlvaroBrey** [comment]
Should be fixed server-side when https://github.com/nextcloud/recommendations/pull/564 is merged

**Comment by joshtrichards** [comment]
Fixed in nextcloud/recommendations#564
