### ISSUE TITLE
"Storage path" setting is too technical

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/android#1088]
Right now the storage path has values like "/data/emulated/0" which is suuper technical.

Instead the choice should be for "Data storage" and the choices could be "Internal storage", "SD card" and if there are multiple cards also "SD card 2" etc, each saying how much free space there is on them.

**Comment by tobiasKaminsky** [comment]
:+1:

**Comment by AndyScherzinger** [comment]
👍

**Comment by tobiasKaminsky** [comment]
What do you think?

Ref: https://github.com/nextcloud/android/issues/802#issuecomment-309372150
> but we should in the end offer both /data and /media because now we are reverting back to pre 1.4 so users that wanted to block media indexing will get mad. So the best would be to offer both with the hint for (SD card - media indexed / SD card - not media indexed).

![fileqqc6ml](https://user-images.githubusercontent.com/5836855/27287508-360f6c98-5504-11e7-917c-edb2d535327d.png)

**Comment by jancborchardt** [comment]
Even as slightly technical user, I don't understand what "media indexed" means. Does it mean "Don't show data in other apps, like Gallery"?

If so, we could put that as a toggle in the bottom of that popup (off by default). But right now this is equally as confusing.

**Comment by AndyScherzinger** [comment]
>  I don't understand what "media indexed" means. Does it mean "Don't show data in other apps, like Gallery"?

Exactly and yes it is not easy to understand, a switch seems to be the nicer way to handle it 👍 
@tobiasKaminsky that might make this a bit more complicated since you need to have a custom dialog then due to the fact that is is not a simple array chooser anymore.

**Comment by jasonbayton** [comment]
Not defending this behaviour but it's a pretty common thing to see. Few apps mask the underlying paths that I've seen.

**Comment by jancborchardt** [comment]
That's where we do things differently to make technology simpler to understand and use. :)

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky do you already have an implementation for the screenshot you posted?

**Comment by tobiasKaminsky** [comment]
It was something local, but I cannot find it, maybe I did not even saved it.. :-/

**Comment by jancborchardt** [comment]
Could we just rename the current display from the technical path to "Internal storage" and "SD card" as mentioned in the original post? ;) The whole »media indexed« thing is a new feature rather than a bugfix and it blocks this small papercut issue.

**Comment by AndyScherzinger** [comment]
> Could we just rename the current display from the technical path to "Internal storage" and "SD card" as mentioned in the original post?

It is imho not that easy :( Afaik you can format an SD card as internal memory so it show up and behaves like internal storage while it is technically/physically still an sd card (!)

**Comment by tobiasKaminsky** [comment]
This is the reason why newer android version are talking about
- internal
- portable 
storage, whereas a hard-wired storage is always internal, but a (removable) sdcard can be both:
- internal: only usable in this exact device, allows to move apps onto it
- portable: mainly for file exchange, useful for audio/video, limitations on what to store onto it

**Comment by Bigdesaster** [comment]
Hi,
i've just a suggestion:
why not leaving the options to 'intenal' and 'sd-card' and set path to android/media.
Then creating a new setting "hide indexing by mediaplayer" which creates or deletes a '.nomedia'-file in the directory?
Greets

**Comment by comradekingu** [comment]
@Bigdesaster 
"Hide contents from indexing mediaplayers" or
"Hide contents from mediaplayer indexation" ?

**Comment by Bigdesaster** [comment]
Yeah that was my opinion. How ist would be named finally doesn't matter. It could also bei an extra option outside the data-storage dialog

**Comment by comradekingu** [comment]
![storageoverhaul](https://user-images.githubusercontent.com/13802408/30487943-3663adf0-9a35-11e7-843f-9e15f67adc66.png)

**Comment by dcbx** [comment]
Hello there! Just wanted to ask if one can expect some progress to this storage path thing? I would see me as a rather tech savvy user and I'm really puzzled which path to choose if I want to interact with my files through other apps.
@AndyScherzinger sent me here.. thanks btw! :)

**Comment by AndyScherzinger** [comment]
No progress atm. If @tobiasKaminsky could recall how to distinguish the different path regarding "indexibility" and internal/portable then I could work on it. Else my time is a bit limited these days so I can't cover this alone :(

**Comment by dcbx** [comment]
Okay, after reading through some similar tickets and Android docs (e.g. https://developer.android.com/training/data-storage ), i think the term "indexation" is misleading as well. Further more i was asking myself "would my parents understand it?" -> No, way!!! ;)
So i'd rather choose something like "sharing (or interact?) with other apps". Maybe as full question: "Do you want to share your files with other apps?"
Yes, that has not very much to do with "choosing my storage path", but _IF_ i understand the Android docs right, the whole concept of storage _path_ is kind of deprecated and this option would need some programmatically changes anyway. Please correct me if I'm wrong!

**Comment by joshtrichards** [comment]
This is now Pocket presents the storage choice. When I saw I thought of this issue. 

Though it only gave me one choice in this case, it was presented clearly with minimal cognitive load.

![Screenshot_20240212-214844](https://github.com/nextcloud/android/assets/1731941/5f805117-e1ab-4bf0-ad48-806be99709d0)

**Comment by digisus** [comment]
Arriving here after just installing NC on a new phone and being unable to just select ANY folder I like as storage location is puzzling to me tbh. Right now, I have to make a choice between four hard to understand options.

I read the entire issue thread and IMHO this discussion is overcomplicating things a lot. I propose to offer a simple file dialog where the user can just choose any folder they like as storage location. The dialog starts in "home", where [Documents] and [Downloads], [DCIM], etc. reside as default because this is familiar to everybody. 

From here the user navigates wherever and makes their own choice:
* If they are non-technical, they may create something like [Documents/Nextcloud] or similar.
* If they want to hide the files, they will first of all already know it is possible and maybe jump into [Android] or elsewhere to bury the NC folder somewhere. For this case, the app can give guidance by offering a link "Advanced options": a new window to explain the different options: SD or not, indexable or not, etc. Here, the current options could be listed and the user could tick their preferred adnvanced option.

Both cases require the user to be able to navigate the full tree of folders. Therefore, I suggest to open a normal file dialog by default with the advanced option on special folders.

**Comment by jancborchardt** [comment]
@tobiasKaminsky we have a full plan and mockup here, this can be gone ahead with right? As per your comment https://github.com/nextcloud/android/issues/1088#issuecomment-309440072 and my clarification afterwards.

![image](https://github.com/user-attachments/assets/f76c8496-7e12-4e20-ade2-2ccaec982e72)

**Comment by tobiasKaminsky** [comment]
Default: toggle off -> visible

**Comment by joshtrichards** [comment]
Related: #2416
