### ISSUE TITLE
Slow Media Tab View 

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/android#10882]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Since this was implemented the media tab got really slow and dose not work. Photos take a long time to load, app freezes. 
https://github.com/nextcloud/android/pull/10008

This seems to happen more on users that have a lot of photos my users has 45GB + of photos and videos

### Expected behaviour

Should load images on the snap like the IOS client dose. 

### Actual behaviour

Slow and laggy 

### Android version

12

### Device brand and model

SM-G996U1 

### Stock or custom OS?

Stock

### Nextcloud android app version

3.22.1

### Nextcloud server version

24.0.6

### Using a reverse proxy?

No

**Comment by omnath0** [comment]
It's super slow specially after the last update and crashed everytime on Samsung S20/22.

**Comment by svenb1234** [comment]
And it flickers because it recalculates the view over and over again.

**Comment by eraser2021999** [comment]
I have a local NextCloud instance accesible from the phone via WiFi. I used NextCloud on iOS and usually I selected to see only the photos from the current year. But on Android this is slow and it puzzles me, since they are already synced and saved offline on the device, so the the issue it doesn't seem related to transfer speed, but with the view rendering.

**Comment by andyxheli** [comment]
Yes I agree there has always been an issue with the Android Media tab view. hopefully, Nextcloud will fix this but yes since the new version has been released it use less I stopped using it can't use it at all

**Comment by andyxheli** [comment]
Im still having alot of issues with this even with https://github.com/nextcloud/android/pull/11082 applied to 3.23.0 

Please see attached recording, For me the Media tab is completely unusable. Hopefully there's a higher property on this as the app comply crashes   

https://user-images.githubusercontent.com/59488153/205330178-16b357e0-b2af-4a44-9404-d120c4462ed8.mp4

**Comment by andyxheli** [comment]
Hi @AlvaroBrey just wanted to give you a quick update on this issue seems like it's a little better on loading the media on Version 3.23.1 but still lags and freezes

**Comment by invario** [comment]
I have lots of photos. And in my years (yes, years) of using the app, it hasn't worked right, ever.

The file browser view doesn't work either. Same issue with slowness to the point of Android saying the all isn't responding.

It's been reported numerous times before and either the developers can't or won't fix it. I've given up and installed the Memories app within NC instead and use the browser interface. It is lightning fast once you index everything:
https://github.com/pulsejet/memories

If you insist on an app, this works quite well too:
https://gitlab.com/nkming2/nc-photos

**Comment by andyxheli** [comment]
I started using the nc-photos for android works like a charm they way the Nextcloud App should.

Thanks I'll also check the memories all as well. 

I really hope there is a resolution on this soon

**Comment by Anvil5465** [comment]
Just wanted to bump this- the media tab is basically unusable on my phone (roughly 90 GB of photos and videos, Pixel 6a with GrapheneOS, Android 13, server version 25, client version 3.23.1). The app crashes constantly. When it doesn't crash, it's extremely slow, and I constantly get the "Nextcloud isn't responding" popup. The error message shows very high CPU usage from Nextcloud, typically 60-80%.

**Comment by mkiah** [comment]
I'm having the same issues. I originally thought it was an issue with preview generation, so I configured that on the server and it's set up to generate previews every 10 minutes. 

If I access the Nextcloud media area from Firefox mobile, everything loads quickly. On the same device, previews in the app don't seem to load at all, and the app will crash regularly. So, it seems like an issue unique to the app.

App version: 3.23.1
Server version: 25.0.2
Android: 13
Phone: Pixel 6
Build: TP1A.221105.002


https://user-images.githubusercontent.com/46502806/213596825-fa00f3e7-4858-49e9-8651-dc1749b366aa.mp4

Happy to do a deeper dive if that'll help, I just need some direction.

**Comment by andyxheli** [comment]
I agree I have preview generator running as well and I don't have any issues via web or via iOS nextcloud. I just wish there was a higher priority on this due to the age of the issue and if you look there's so many other issues regarding the same matter for years now. If the iOS nextcloud can do it, the android should too. It's a shame because it ruins the experience of the app 😕

**Comment by svenb1234** [comment]
> On the same device, previews in the app don't seem to load at all

That's  #10389

**Comment by eraser2021999** [comment]
I have created a pull request (https://github.com/nextcloud/android/pull/11321) with a fix for this issue. The initial tests look promising, maybe some other folks could test it further and provide feedback.

PS: Thank you @starypatyk, @AlvaroBrey  and @szaimen for the assistance.

**Comment by AndyXheli** [comment]
Still an issue. I think the media tab needs redo. Currently I'm using the photos app for nextcloud. Maybe there can me something similar to this build into the app just a suggestion

**Comment by MystikReasons** [comment]
Can confirm the issue, currently have only around 20 photos/videos and as soon as I scroll the entire app starts to lag.
Even opening the hamburger menu while scrolling downwards is lagging.
Tested on latest Android Google Play version (3.29.2)
