### ISSUE TITLE
Sharing with "password rule" enabled is not working

### ISSUE THREAD

**Issue by phatair** [nextcloud/android#1089]
### Actual behaviour
if you enter a password for a link share and this password is too short, you will be redirected to the login windows and a message appears "a error appears during the sharing of a folder or file".

### Expected behaviour
if you enter a password for a link share and this password is too short, e message should notify you about this.
 
### Steps to reproduce
1. enforce password protection is enabled on nextcloud
2. password rule is set (for example 8 characters) on nextcloud
3. in the android app share a file or folder
4. enable "share link"
5. you have to set a password
6. if you set a password with less then 8 characters you will be redirected to the login page

If you did not enforce the password protection and follow this steps, the warning about the password lenght is displayed:
1. disable enforce password protection on nextcloud
2. password rule is set (for example 8 characters) on nextcloud
3. in the android app share a file or folder
4. enable "share link"
5. enable "password protection"
6. if you set a password with less then 8 characters you get a notification that you have to enter 8 characters for the password

### Environment data
Android version: 7.0

Device model: Samsung Galaxy 7 Edge

Stock or customized system: stock

Nextcloud app version: 1.4.3

Nextcloud server version: 12.0

**Comment by AugustinVoiMa** [comment]
Hi
I'm new on this project.

In `om.owncloud.android.ui.activity.FileActivity` on call of `onRemoteOperationFinish(...)`:
If I'm not wrong, it comes from a confusion (we have `result.getCode() == ResultCode.UNAUTHORIZED`) which shall means in this case that the password is wrong.
then calling `requestCredentialsUpdate(...)` forces to ask for new creditentials to the user and the auth view appears. But it doesn't disconnect you (quit the app and launch again you won't have to give creditentials).

I don't know the exact meaning of `ResultCode.UNAUTHORIZED` but I don't know we have to use it to distinguish the case of a bad password.

What I think appropriate to do is to use the `RemoteOperation` option and to add a condition to the class extended (`CreateShareViaLinkOperation` in this case)


@mario Can I fix the issue?

PS: I hope my english is not too bad, sorry for the mistakes I could have done.

**Comment by mario** [comment]
@AugustinVoiMa feel free to try :)

**Comment by mario** [comment]
@AugustinVoiMa, for now, feel free to fork the project, and target master with your branch - later on, I can give you access to our repository to create branches.

**Comment by tobiasKaminsky** [comment]
Cool @AugustinVoiMa that you want to help us.
If you have any questions just ping us.

**Comment by phatair** [comment]
Hi,
so thats a bug in the android app, right? I tested it on two other devices and its the same behavior.
Thanks your your help AugustinVoiMa.

I'm not a coder but it sounds like you find the problem. If i enter the password and it has less characters as set in the password policy, i redirected to the login page. That sounds like "requestCredentialsUpdate(...)"

**Comment by AugustinVoiMa** [comment]
Yes that's it. I made a correction yesterday night but I haven't published it for now. 
I will push this correction when I have the time to verify it doesn't bring new issues, but it seems to be resolved. 
This issue must happen on all devices because there is a source-code confusion, not a compatibility failure.

**Comment by AndyScherzinger** [comment]
Hi @phatair, via this issue it is a known issue now, yes and also @AugustinVoiMa provided a fix already which we need to look at (build fails probably due to repo-issues). So yeah, it will be fixed in the official app.

**Comment by phatair** [comment]
Great - thanks Andy!

**Comment by AndyScherzinger** [comment]
actual PR is #1110

**Comment by tobiasKaminsky** [comment]
I have requested a more meaningful error message from server: https://github.com/nextcloud/server/issues/5545

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky would that block the actual PR? Just asking since a new message on the server means a new sever release which would be a dependency I'd like to avoid here. ;)

**Comment by tobiasKaminsky** [comment]
We can do it in two steps:
- provide now a more generic error message
- after server enhancement, also enhance our password handling system

**Comment by AndyScherzinger** [comment]
sounds good to me 👍

**Comment by tobiasKaminsky** [comment]
Closing as fixed in PR.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky which PR fixed this? 0_o

**Comment by tobiasKaminsky** [comment]
As far as I remember the switch to ocs v2 for sharing in library.
We then get better handling of error and better error messages.
