### ISSUE TITLE
Text field for new folder or renaming very narrow

### ISSUE THREAD

**Issue by TomW80** [nextcloud/android#10895]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

add a new folder or rename a file

### Expected behaviour

The text field should be displayed so large that you can recognize the normal text

### Actual behaviour

The text field is displayed very narrowly, the entered text is no longer visible.
![IMG_20221023_184728](https://user-images.githubusercontent.com/54640793/197404962-79b9e8e9-e4cf-4c46-9366-31c33af74c0a.jpg)
![IMG_20221023_184708](https://user-images.githubusercontent.com/54640793/197404967-8b5aa988-7d5f-4eae-9eaa-ae7edc315b18.jpg)

### Android version

10 (EMUI 12)

### Device brand and model

Huawei Mate 10

### Stock or custom OS?

Stock

### Nextcloud android app version

3.22.1

### Nextcloud server version

24.0.6

### Using a reverse proxy?

I don't know

**Comment by AlvaroBrey** [comment]
This looks like a consequence of the increased dialog margins in Material 3. We may have to revert to non-m3 style for this dialog for now, as I see no way to fix this other than just not using text inputs inside a  non-fullscreen Dialog.

**Comment by AlvaroBrey** [comment]
After further investigation this looks like it's caused by how we force-open the keyboard when opening the dialog. more investigation needed-

**Comment by tobiasKaminsky** [comment]
On Android 10 it works, but not on Android 12.
If this helps.
