### ISSUE TITLE
Use Material You

### ISSUE THREAD

**Issue by CyberTimon** [nextcloud/android#10899]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

If you have a Samsung device running One UI 4 or newer, download Nextcloud and the UI will be pink. 

Tested on a Galaxy A40 and Galaxy S21 Ultra. Both running One UI 4-4.5. 

### Expected behaviour

The UI should match the color of the color palette and should not be pink.

### Actual behaviour

The whole UI in Nextcloud is pink regardless of what color palette is selected in the settings.
For example, Google Calculator is correctly blue/black, while Nextcloud is pink.

### Android version

12

### Device brand and model

Samsung Galaxy S21 Ultra

### Stock or custom OS?

Stock

### Nextcloud android app version

3.22.1

### Nextcloud server version

24.0.6

### Using a reverse proxy?

No

### Android logs

no logs needed

### Server error logs

```bash
no logs needed
```

### Additional information

Pink should not be selected if the palette cannot be found

**Comment by AlvaroBrey** [comment]
Nextcloud does not implement Material You color, only Material 3 styles. The UI color is changed based on the server color instead (or the user background color on NC 25+).

**Comment by ae5960e8-a6fc-491f-b252-898ecf59af95** [comment]
+1

**Comment by CyberTimon** [comment]
Closing as the issue is fixed when changing the nextcloud ui color to something slightly blue rather than black.

**Comment by ThatOneCalculator** [comment]
I think this issue may need to be reopened -- no matter what web theme I use, the actual Android app colors are NOT my material you colors, rather, the stock blue. Pixel 6.

**Comment by BluePixel4k** [comment]
I would also like to see the app with the color based on the Material You monet colors of your phone and not your server.

After adding this, maybe a toggle button could be added for disabling the monet colors for user who don't like it?

**Comment by Armishiuwu** [comment]
They are so right, Android improved a lot with Material You Monet Colors, I don't understand why not to use them, they greatly improve the experience of an app
