### ISSUE TITLE
Confirmation dialog before removing an account

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#109]
Review from the Google Play store. User wished to have a confirmation dialog before an account is removed. 
If I remember correctly we had this discussion at some point and decided not to. But, yes delete is a tricky one. Any input on this @jancborchardt ?

TASK: Show an undo toast after removing an account.

**Comment by jancborchardt** [comment]
As usual, we should offer undo here. :) It’s similar as a confirmation dialog, with the exception that confirmation dialogs are often mindlessly clicked away. Undo, where the action is directly visible (account gone) but actually only carried out in the interface, is much more error-friendly.

**Comment by AndyScherzinger** [comment]
I also though about adding an undo action here. Will have to check how to implement such a thing because this might be a delete & recreate, or a hide from list and delete in case undo hasn't been clicked whatever is technically possible.

Thanks for the feedback! :)

**Comment by jancborchardt** [comment]
> or a hide from list and delete in case undo hasn't been clicked whatever is technically possible.

This is how undo generally works – just lying by removing it from the interface, and then actually deleting it when no undo has been clicked or the next action is performed.

**Comment by tobiasKaminsky** [comment]
In contributing.md is said that we should use label "accepted" for issues and 1...5 only for PRs.
I also suggest to write a summary in the first post if a conclusion is made.
(I will demonstrate it on this issue).

**Comment by przybylski** [comment]
the undo is problematic on a lot of technical levels.
* If we cheat to delete account how long should we postpone until we really delete it? 
* If user closes app immediately after "deleting" account we won't be able to respond to that and account will exists.
* Removing may fail if we quietly ignore it, account will exist after "deletion".

If user won't read warning dialog than it isn't our fault.

**Comment by jancborchardt** [comment]
> * If we cheat to delete account how long should we postpone until we really delete it?

What’s the default for that on Android, like for deleting pictures in Gallery? 5 seconds?

> * If user closes app immediately after "deleting" account we won't be able to respond to that and account will exists.

Isn’t there an exit-app hook?

> * Removing may fail if we quietly ignore it, account will exist after "deletion".

Sure, but that’s exactly the same with a confirmation dialog. Warning needs to be shown either way when the deletion fails. Undo does not mean ignoring an error, but actually the opposite: Only requiring people to take action when there is something wrong.

> * Toaster doesn't provide a way to get feedback when it is dismissed, but even if it did, app might be closed by then making dismiss notification null pointer vulnerable

Isn’t there a way to work around this? Or using snackbar?

> If user won't read warning dialog than it isn't our fault.

Of course it is. It’s a design issue.

**Comment by przybylski** [comment]
> Isn’t there an exit-app hook?

Yes there is but it isn't guaranteed that all procedures will run uniterrupted

> Isn’t there a way to work around this? Or using snackbar?


Yes, snackbar supports onDismiss notification, but I don't know how it will behave when app will be closed.


---
Generally I would rather not insert "undo" button for account deletion, this operation is significant enough that user should be sure that he/she is 100% sure about the consequences.
If we will pretend that account was deleted when in fact it wasn't than the app and system will be in weird state when system sees something else than app.

But even if I get outvoted on that I think for now it is crucial enough to at least put a confirmation dialog there, which I already did in my pull request.

**Comment by tobiasKaminsky** [comment]
I am unsure if this is the correct way to go @przybylski.
As far as I understand @jancborchardt has a different idea and instead of discussing it and coming to a conclusion you opened a PR. Please do not get me wrong, this should in no way be meant as an offence, but I think we should really keep the workflow: idea -> discussion -> conclusion -> PR.

**Comment by AndyScherzinger** [comment]
How about a two step approach. First you the enhancement since it fixed the problem quickly and then work on the final solution. This way we can provide progress faster and evolutionary ;) 

What do you guys think?

**Comment by przybylski** [comment]
I can close that PR and forget about it but I still think that providing undo for account deletion is not the best way to go.
First of all it will significantly increase account handling code complexity, it will also put the app in "undefined" state when it is inconsistent with the rest of the system. And system unaware of such approach can perform operations on those account leading to corrupted data. Beside that would put nextCloud client into inconsistent way of handling delete account. I haven't met any android app (and system version) which would allow undoing account deletion.

I think I already said it but I'll say it once more: deleting account is not consequences free operation, if user performs is, he/she must be absolute sure about it, there is no turning back.

@tobiasKaminsky I understand that opening PR was a bit premature but after just a single try I decided that quick/hot fix is needed.

**Comment by AndyScherzinger** [comment]
@LukasReschke and @jancborchardt any feedback on this one? @przybylski opened a PR for this #116 which is a simple confirmation dialog not the discussed solution here with the undo operation which is still in discussion from my point of view. Feedback would be regarding using the confirmation dialog as a quick solution which we can ship with the next release and than build the evolutionary next version from there. My argument for here is to get stuff out to the users and a confirmation dialog is way better than not having any solution out there at the moment.

**Comment by LukasReschke** [comment]
I'm agreeing with @przybylski. I'd merge that PR.

**Comment by AndyScherzinger** [comment]
Status: 

- Merge: Bartosz, Lukas, Andy
- Don't merge: - 
- Vote open: Jan, Tobias

**Comment by tobiasKaminsky** [comment]
Your approach is very good :+1: @AndyScherzinger 
Short term: dialog
Long term: better UI as @jancborchardt wishes :)

**Comment by AndyScherzinger** [comment]
@jancborchardt are you okay with this approach? Because then we would merge the dialog as a first step.

**Comment by jancborchardt** [comment]
Ok, let’s do it! :)

**Comment by Hanzei** [comment]
#116 already fixed the main point of the issue. Can we close this issue? If we consider an undo option, we can open a new issue.
