### ISSUE TITLE
Hide "notifications" menu entry if no notification is available

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/android#1091]
* just like we do in the web UI
* otherwise users are confused what this is for if there is nothing in that panel

cc @mario @tobiasKaminsky @AndyScherzinger @przybylski @nextcloud/designers @aleister09 @imjarp

**Comment by mario** [comment]
This makes no sense to me.

a) We'd have to check if there are notifications on every activity start, which makes it a pain (BW issues)
b) Notifications entry will completely disappear in 1.6

**Comment by AndyScherzinger** [comment]
I agree with @mario. :+1:

**Comment by jancborchardt** [comment]
Yeah, we should add an indicator though if there are unseen notifications.

**Comment by mario** [comment]
Same issue. We'd have to pool on every screen open, and we don't currently track if you've seen (or haven't seen) the notification. 

That's why we have push :D
