### ISSUE TITLE
Auto upload failed to upload permenently 

### ISSUE THREAD

**Issue by Pravi21** [nextcloud/android#10916]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Log into NC with your local server IP (with self-signed SSL).
2. Go to settings, and configure a custom folder for auto upload. Then save it.
3. Copy some files to the same custom folder.

### Expected behaviour

The NC android app should upload the file to the local server (At least within 15 minutes).

### Actual behaviour

Files are not being uploaded to the server (Waited for 1 hour).

### Android version

Android 10

### Device brand and model

Poco F1

### Stock or custom OS?

Stock

### Nextcloud android app version

3.22.2

### Nextcloud server version

24.0.6

### Using a reverse proxy?

No

### Additional information

Before 3.22.1 the auto upload feature used to work (not always), but on 3.22.2 the feature completely failed to work.

**Comment by luckkmaxx** [comment]
So seems this hasnt fixed finally on 3.22.2?
I will stay on 3.21.2 until the upload feature be fixed.

**Comment by AlvaroBrey** [comment]
@Pravi21  Can you get a logcat from the Android device so we can see if there's any errors? Instructions here: https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat-mag

Feel free to search and replace the server URL, username and other file names in the output.

**Comment by Mars160** [comment]
The same issue and I find that pictures in the auto-upload folder were upload successfully but without delete them on my device. I have set it.
Yeah, only the pictures were uploaded. other types of files failed to, such as zip, docx, sub folder, etc.
My phone is Xiaomi 12S Ultra running MIUI based on Android 12.
I will try to get the log.

**Comment by Mars160** [comment]
https://github.com/nextcloud/android/files/10148053/logcatOutput.txt

log file here
