### ISSUE TITLE
Too bright color for folders & files since Material UI update

### ISSUE THREAD

**Issue by Pilzinsel64** [nextcloud/android#10922]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Update the Nextcloud-App to the latest version avaible in Play Store that uses the new Material UI.
2. Open the Nextcloud-App

### Expected behaviour

The color for folders and files stays as in Nextcloud Webapp and also as before the Material UI update,

### Actual behaviour

The color for folders and files are a lot brighter then in the Nextcloud Webapp and then before the Material UI update.
This also happens to my partner, Samsung Galaxy S20 FE, Stock OS, latest updates everywhere.

Server:
![grafik](https://user-images.githubusercontent.com/23138465/197690792-3802ae55-23f6-459e-b4a3-8207bf69b469.png)

Client:
![Screenshot_20221025-071934_Nextcloud](https://user-images.githubusercontent.com/23138465/197690865-19c96383-8a30-4269-b734-a8276b2237dc.png)

Client (Light, did test it and before you ask xP):
![Screenshot_20221025-071948_Nextcloud](https://user-images.githubusercontent.com/23138465/197690860-d854876a-caf3-4a9b-9586-c9cde31435b4.png)

Client (Light, Menu):
![Screenshot_20221025-071952_Nextcloud](https://user-images.githubusercontent.com/23138465/197690829-55959595-f09a-4e3b-b7ae-7f8685eefdac.png)

### Android version

Android 12

### Device brand and model

Samsung Galaxy S10 (SM-G973F)

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

3.22.2

### Nextcloud server version

Nextcloud 24.0.6

### Using a reverse proxy?

No

### Additional information

- Cusotm ROM: LineageOS 19 (Android 12)
- Device simulation as "Google Pixel 4 XL" is active for getting specific Samsung apps to work. But disabling it (as I need for each update) has no effect!
- The same bug happens to my partner with Samusung Galaxy S20 FE and with **Stock OS**!
- This bug happens also to my other two accounts, one NC24 and one NC25 (coloring is weird on NC25 atm, no deeper tests yet).

**Comment by AlvaroBrey** [comment]
> coloring is weird on NC25 
https://github.com/nextcloud/android/issues/10915, on NC25 color depends on user background color, not server color.

**Comment by AlvaroBrey** [comment]
> also as before the Material UI update
That's not possible, Material 3 uses dynamic colors based off the primary color, while the old implementation used the primary color directly. You'll see similar color changes on the web UI once you update to NC25.

**Comment by Pilzinsel64** [comment]
> on NC25 color depends on user background color, not server color.
> You'll see similar color changes on the web UI once you update to NC25.

That means the bright color for folders and icons in Android app is ideed, as well as on the Server itself?
That should be also the case now for NC24 accounts in the Android App?

Side note:
In NC 25 there is a bug for at the moment that prevents me from testing a custom color or the primary server color. See here https://github.com/nextcloud/server/issues/34578#issuecomment-1286055991.

I made picture from the cloud and the android client from the NC25 account:
![grafik](https://user-images.githubusercontent.com/23138465/197743418-a733b015-def5-4be7-8454-b6258c7eaa8b.png)
![Screenshot_20221025-115705_Nextcloud](https://user-images.githubusercontent.com/23138465/197744102-925c0cdb-5c6f-4c25-a60d-a607ae6d5676.png)
![Screenshot_20221025-115709_Nextcloud](https://user-images.githubusercontent.com/23138465/197744108-f09db9e0-000b-4d28-abef-6dcb579a5df1.png)

I've made a picture of the other NC24 instance I have. Here too, the folder icon is a lot brighter in the Android app as on the Server itself.
![grafik](https://user-images.githubusercontent.com/23138465/197744429-886b5316-e5a7-47ea-ae74-9161d48dcbef.png)
![Screenshot_20221025-120016_Nextcloud](https://user-images.githubusercontent.com/23138465/197744455-b54ea52b-9d6d-482a-9e55-3f96f016249c.png)
![Screenshot_20221025-120017_Nextcloud](https://user-images.githubusercontent.com/23138465/197744459-538b5f07-7e3b-4981-9220-56107ef912a2.png)
