### ISSUE TITLE
Notification when upload finished

### ISSUE THREAD

**Issue by contribguy** [nextcloud/android#1092]
Hi!

This issue is rather a suggestion of extending functionality of the app than it's an issue. The suggestion applies also to the iOS project.

### Actual behaviour
After I have selected say 15 photos for upload via the share-button in the android gallery app and upload finished, it will finish without notification.

### Suggestion
I would like to get a notification telling me something like "Finished uploading 15 files".

**Comment by contribguy** [comment]
Nextcloud/ios#273

**Comment by tobiasKaminsky** [comment]
@jancborchardt what do you think?

**Comment by jancborchardt** [comment]
It's showing a notification while being uploaded. Successful upload doesn't warrant an additional notification, only when there's an error.

**Comment by tobiasKaminsky** [comment]
Same opinion here. If you want to verify if all uploads are correctly done you additionally can go into upload view.
