### ISSUE TITLE
It is impossible to load up a file-

### ISSUE THREAD

**Issue by Lonnie2009** [nextcloud/android#10939]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

The bug comes everytime when I try to load up a file with the Android-Nextcloud App.

### Expected behaviour

It shoud loads the file up.

### Actual behaviour

There comes a notification wich said: "Dateikonflikt beim Hochladen -- Wählen Sie aus welche version (...) behalten werden soll". If I click over it, there comes a Tost wich said: "Fehler beim Erstellen des Konfliktdialogs"

### Android version

11

### Device brand and model

Lenovo Tab P 11 Pro

### Stock or custom OS?

Stock

### Nextcloud android app version

the newst

### Nextcloud server version

the newst

### Using a reverse proxy?

I don't know

**Comment by AlvaroBrey** [comment]
Please add the actual app and server versions to the template, not just "the newest".
