### ISSUE TITLE
android 6.0.1 with 1.4.3 client unreliable sync (unusable)

### ISSUE THREAD

**Issue by DaveBurkhardt** [nextcloud/android#1093]
### Actual behaviour
App missing media 
90% of my media is not sync'd after being created

### Expected behaviour
App should work, this is a cloud sync with this not working it's a fatal flaw.  Show stopper.

### Steps to reproduce
1.  use the app on a Samsung S5 in 6.0.1 android
2.  take pics/movies to SD card (64GB) or local storage
3.  most of them will not attempt sync or show even show in the uploads
4.  then occasionally one will... 

### Environment data
Android version: 6.0.1

Device model:  Samsung S5

### Stock or customized system:
Stock, no mods

### Nextcloud app version:
1.4.3

### Nextcloud server version:
11.0.2

#### Web server error log
not needed, issue is in client app

#### Nextcloud log (data/nextcloud.log)
do not see this path/file on my device

**Comment by DaveBurkhardt** [comment]
My post seems to be a DUP of 

https://github.com/nextcloud/android/issues/804


And that's not good as it's old.

Guys, I can help real-time debug this.  This is a critical error.  Let me know what you need.  All of my phones are S5's in my house.  We have no sync going on....

**Comment by AndyScherzinger** [comment]
I hope @mario's auto upload changes for the upcoming release will fix this.

**Comment by mario** [comment]
Dear users,

thank you for your patience. After lots of work, we’re super excited to be able to give you a test version with new auto upload implementation. Keep in mind we will only accept bugs related to Auto Upload in this APK, as other things might be broken.

https://cloud.nextcloud.com/s/ftZraTruRQjTe0R

This is a dev APK so it will not overwrite your existing play store/f-droid APK unless you’re already running dev version. Also, you might need to remove your existing dev version before installing this one.

Explanation of the current functionality:
- added support for custom folders
- separated image and video folders
- checks for new files happens every 15-20 minutes
- automatic retry every 15-20 minutes or when you force close/open the app
- automatic pause once network is changed (untested!)
- significantly less battery usage

All and any testing is more than appreciated, especially with large and ever-going files like Videos. (like, try to record a 30 min video).

Let me know if you’ve got any questions.

Cheers,
Mario

**Comment by mase76** [comment]
I have updated to 2.0.0rc5 from F-Droid. Today I checked the accounts section, and there was no
Nextclound sync since 4 days. I had to trigger manually. Battery optimization is turned off for
Nextcloud.

**Comment by AndyScherzinger** [comment]
@mase76 the account sync isn't important (or triggered by the app). As for the image/video upload please check the upload menu item in the app and the auto upload settings via the menu. There you should activate the upload for the camera folder (image and/or video) and after taking pictures check if they will/have been uploaded depending on the upload conditions you specified (like wifi only for example).

**Comment by mase76** [comment]
I don't have any automatic upload activated. I only want to have my files synced, that are in my
Nextcloud. These are textfiles or my pw database. Maybe you could add a sync interval like the
Nextcloud newsreader has. Also Davdroid has a sync interval.

**Comment by AndyScherzinger** [comment]
@mase76 did you mark these files as "available offline" within the Nextcloud Android app?

**Comment by mase76** [comment]
Yes, I did.

**Comment by AndyScherzinger** [comment]
@mase76 can you please create a new issue for this matter since this is then not releated to the auto upload feature (topic of this issue), so the dev community can have a look at it. Highly appreciate your efforts!

**Comment by mase76** [comment]
I did so.

**Comment by AndyScherzinger** [comment]
Thanks! :)

**Comment by AndyScherzinger** [comment]
@DaveBurkhardt is this issue still present for you with the latest release 2.0.0?
