### ISSUE TITLE
App is extremely slow - especially navigating to photo-folder 

### ISSUE THREAD

**Issue by rekcodocker** [nextcloud/android#10969]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

The app is very slow to browse to a folder, especially containing photo's. 
It can take minutes and I frequently see the message 'Nextcloud is not responding / wait / kill / send report' .

This also happens when the app is on a device connected directly to the same network as the server.

My backend is a Raspberry Pi 4 with 4GB ram, I use Nextcloud 24.
It also happens when the previews are already rendered - it doesn't seem like thumbnail-generation is causing it. It is also slow when navigating between normal directories. 
I notice the Postgress database is quite busy, it can take 60-100% of one CPU on those requests.

However, the web-interface is stable and usable.

It seems like (I am speculating here) there is a huge latency, a huge number of tiny client/server requests for each and every photo/file, all client/server requests handled sequentially - or a combination of these.

Since the webinterface works fine, I think it's not just a fact of a tiny server.

### Expected behaviour

I think load times when navigating between folders should be fractions of seconds. 
I expect this:
APP: Please send me the directory listing of folder X
Server: Here you are, files, dates, everything
APP: Send me the thumbnails
Server: Here they are

### Actual behaviour

Browsing takes a long time.  Tens of seconds, sometimes running into a minute.  For navigation between folders.
Even when you go back and forth between the same folders, it reloads very time, slowly.

### Android version

12

### Device brand and model

Motorola G30

### Stock or custom OS?

Stock

### Nextcloud android app version

3.22.2

### Nextcloud server version

24.0.5

### Using a reverse proxy?

I don't know

### Additional information

I'm available for debugging sessions (if you tell me what to do) or to provide a test-account on my server if that helps.

**Comment by svenb1234** [comment]
For me, once the notifications start to ask whether to close the app or wait, the never go away, no matter how often one tabs on wait.

**Comment by rekcodocker** [comment]
For me the problem is solved with Nextcloud 25. 
It is _much_ faster and responsive.
