### ISSUE TITLE
Auto upload not working on cellular connection / mobile data

### ISSUE THREAD

**Issue by Quadrubo** [nextcloud/android#10960]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Install Nextcloud app on android
2. Setup Auto Upload for your Camera (Only upload on unmetered WiFi "off")
3. Turn off Wifi, be on Cellular
4. Take a Picture

### Expected behaviour

The Photo should upload.

### Actual behaviour

Photos are stuck on status "Waiting for non-metered Wi-Fi".

### Android version

11

### Device brand and model

OnePlus 8T

### Stock or custom OS?

Stock

### Nextcloud android app version

3.22.2

### Nextcloud server version

25.0.0

### Using a reverse proxy?

Yes

**Comment by joshtrichards** [comment]
Hi @Quadrubo - Thanks for the report. Any chance the auto upload profile just prior had *Only upload on unmetered WiFi* _on_ and had uploads in the queue when you changed the setting to _off_? Already queued uploads I believe follow the policy in place when they are queued.
