### ISSUE TITLE
Stopped uploading audio files from a custom folder 

### ISSUE THREAD

**Issue by xtreye** [nextcloud/android#10995]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

It has stopped uploading audio files. My last dictaphone records on the cloud are dated 3 month ago.
A:
1. Create a new custom folder
2. For local directory, select a folder with audio files (ex, wav)

B:
1. Open synchronised folders setup

### Expected behaviour

A: should display contents of the folder
B: should do the sync and display correct preview

### Actual behaviour

A: The folder is displayed as empty

B:  
1. For existing folder, the newer files are not synced
2. Some randomly picked video is displayed for the preview 

### Android version

13

### Device brand and model

Moto G30

### Stock or custom OS?

Stock

### Nextcloud android app version

3.22.2

### Nextcloud server version

23.0.2

### Using a reverse proxy?

No

### Additional information

Tried both standard file browser and File Commander - the 0 folder is just not visible. Even when hidden files setting is on

**Comment by joshtrichards** [comment]
Hi @xtreye - Thanks for the report and sorry for the troubles.

So this behavior may have started around the time that you upgraded to either v3.21.0 perhaps?

https://github.com/nextcloud/android/releases/tag/stable-3.21.0

Are you still currently experiencing this behavior?
