### ISSUE TITLE
`index.php/204` throttle causes app to believe there's no connection

### ISSUE THREAD

**Issue by PVince81** [nextcloud/android#10993]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Take a picture ( ~ 5 MB)
2. Wait for instant upload
3. Retry upload

### Expected behaviour

Picture uploaded properly

### Actual behaviour

Always shows connection error in the uploads list.
Happens for 2 Samsung mobile phones.

### Android version

12

### Device brand and model

Samsung Galaxy A52s 5G

### Stock or custom OS?

Stock

### Nextcloud android app version

3.22.3

### Nextcloud server version

25.0.1 RC1

### Using a reverse proxy?

No

### Android logs

TODO: if not reproducible on your side I can try and grab logs (logcat is not working I need time to setup/debug)

### Server error logs

```bash
None, the upload connection doesn't even reach the server!
```

### Additional information

Note: I used to have the issue with conflicts on upload on two mobile phones https://github.com/nextcloud/android/issues/7811 and after upgrading to 3.22.3 the above issue is happening

I've checked the access.log and during upload the client does not even reach the server!

However, regular browsing through folders works, I can see a lot of capability requests and PROPFINDs.
It's only uploads that fail to connect.

Is upload using another kind of connection manager ? @tobiasKaminsky @AlvaroBrey

**Comment by PVince81** [comment]
This happens on 2 mobile phones, both Samsung Galaxy A51 and A52s, Android 12.

Let me know if not reproducible on your side.

**Comment by PVince81** [comment]
okay, I got something from logcat:
```
11-06 11:40:53.066 16148 16250 E GetMethod: Error executing method
11-06 11:40:53.066 16148 16250 E GetMethod: java.io.IOException: unexpected end of stream on https://cloud.vincentpetry.net/...
11-06 11:40:53.066 16148 16250 E GetMethod:     at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:203)
11-06 11:40:53.066 16148 16250 E GetMethod:     at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:111)
11-06 11:40:53.066 16148 16250 E GetMethod:     at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:93)
11-06 11:40:53.066 16148 16250 E GetMethod:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
11-06 11:40:53.066 16148 16250 E GetMethod:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
11-06 11:40:53.066 16148 16250 E GetMethod:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
11-06 11:40:53.066 16148 16250 E GetMethod:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
11-06 11:40:53.066 16148 16250 E GetMethod:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
11-06 11:40:53.066 16148 16250 E GetMethod:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
11-06 11:40:53.066 16148 16250 E GetMethod:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
11-06 11:40:53.066 16148 16250 E GetMethod:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:65)
11-06 11:40:53.066 16148 16250 E GetMethod:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
11-06 11:40:53.066 16148 16250 E GetMethod:     at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:205)
11-06 11:40:53.066 16148 16250 E GetMethod:     at okhttp3.internal.connection.RealCall.execute(RealCall.kt:158)
11-06 11:40:53.066 16148 16250 E GetMethod:     at com.nextcloud.common.OkHttpMethodBase.execute(OkHttpMethodBase.kt:175)
11-06 11:40:53.066 16148 16250 E GetMethod:     at com.nextcloud.client.network.ConnectivityServiceImpl.isInternetWalled(ConnectivityServiceImpl.java:81)
11-06 11:40:53.066 16148 16250 E GetMethod:     at com.owncloud.android.operations.UploadFileOperation.checkConditions(UploadFileOperation.java:728)
11-06 11:40:53.066 16148 16250 E GetMethod:     at com.owncloud.android.operations.UploadFileOperation.normalUpload(UploadFileOperation.java:747)
11-06 11:40:53.066 16148 16250 E GetMethod:     at com.owncloud.android.operations.UploadFileOperation.run(UploadFileOperation.java:442)
11-06 11:40:53.066 16148 16250 E GetMethod:     at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:205)
11-06 11:40:53.066 16148 16250 E GetMethod:     at com.nextcloud.client.jobs.FilesUploadWorker.upload(FilesUploadWorker.kt:155)
11-06 11:40:53.066 16148 16250 E GetMethod:     at com.nextcloud.client.jobs.FilesUploadWorker.handlePendingUploads(FilesUploadWorker.kt:103)
11-06 11:40:53.066 16148 16250 E GetMethod:     at com.nextcloud.client.jobs.FilesUploadWorker.doWork(FilesUploadWorker.kt:86)
11-06 11:40:53.066 16148 16250 E GetMethod:     at androidx.work.Worker$1.run(Worker.java:86)
11-06 11:40:53.066 16148 16250 E GetMethod:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
11-06 11:40:53.066 16148 16250 E GetMethod:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
11-06 11:40:53.066 16148 16250 E GetMethod:     at java.lang.Thread.run(Thread.java:920)
11-06 11:40:53.066 16148 16250 E GetMethod: Caused by: java.io.EOFException: \n not found: limit=0 content=…
11-06 11:40:53.066 16148 16250 E GetMethod:     at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:332)
11-06 11:40:53.066 16148 16250 E GetMethod:     at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
11-06 11:40:53.066 16148 16250 E GetMethod:     at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178)
11-06 11:40:53.066 16148 16250 E GetMethod:     ... 26 more
11-06 11:40:53.066 16148 16250 E UploadFileOperation: Upload of /storage/413E-1C03/DCIM/Camera/20221101_122043.jpg to /general/petry/pics/umstiegstation/20221101_122043.jpg: No network connection
11-06 11:40:53.067 16148 16250 D UploadsStorageManager: updateDatabaseUploadResult uploadResult: RemoteOperationResult{mSuccess=false, mHttpCode=-1, mHttpPhrase='null', mException=null, mCode=NO_NETWORK_CONNECTION, message='null', getLogMessage='No network connection'} upload: com.owncloud.android.operations.UploadFileOperation@6afafac
11-06 11:40:53.072 16148 16250 V UploadsStorageManager: Updating /storage/413E-1C03/DCIM/Camera/20221101_122043.jpg with status:UPLOAD_FAILED and result:NETWORK_CONNECTION (old:/storage/413E-1C03/DCIM/Camera/20221101_122043.jpg status:UPLOAD_IN_PROGRESS result:-1)
11-06 11:40:53.072 16148 16250 V UploadsStorageManager: Updating /storage/413E-1C03/DCIM/Camera/20221101_122043.jpg with status=UPLOAD_FAILED
```

**Comment by PVince81** [comment]
just in case I also grepped nextcloud.log for "122043" but there was no entry, so it means it probably doesn't even reach my server

I checked more of logcat and the stack trace repeats itself with the EOFException

**Comment by PVince81** [comment]
https://github.com/nextcloud/android/blob/2c1ff8b84d169b981264250b745ef5a4358b6709/app/src/main/java/com/owncloud/android/operations/UploadFileOperation.java#L728

oh, what is this: https://github.com/nextcloud/android/blob/fbfa7fa746a509be165219d960030cf4a0967eea/app/src/main/java/com/nextcloud/client/network/ConnectivityServiceImpl.java#L78

so the client is requesting "index.php/204" to find out if walled or not

**Comment by PVince81** [comment]
alright, I've compared the response from my server with c.nc.com.
on my server curl says "empty reply from server" but for c.nc.com it returns a proper HTTP response

so either it's a new setup issue on my side (it used to work a week ago), or the expectation regarding the 204 is new and/or need to use a different approach

**Comment by PVince81** [comment]
according to code history those lines haven't been touched in the last 2 years

so it's more likely that something changed on my server, or in 25.0.1 RC1.
I'll check htaccess, etc and figure out where that 204 response is supposed to come from...

still, I think the client should show a better error message that might hint at this

**Comment by PVince81** [comment]
also interesting: it takes around 5 seconds to fail to respond for index.php/204
are we now throttling this endpoint ? @nickvergessen 

status.php returns immediately

**Comment by PVince81** [comment]
I've checked and we're not throttling there

however I found that I had mod_ratelimit enabled in Apache (a former attempt) and apparently it was only throttling these special routes, but not actual downloads (for the background, I switched to [tcconfig](https://github.com/thombashi/tcconfig) for bandwidth limit now)

so feel free to close this ticket

still, I think the exception should be caught in ConnectivityServiceImpl and a proper message should be logged so that admins get a hint that the error is connected to index.php/204 so they can debug further

**Comment by lckarssen** [comment]
I seem to have the same problem. All of a sudden automatic uploads stopped working. I'm not sure if this was due to the recent Android client update to 3.22.3, or to the recent update of my server to NC 24.0.7. :thinking:

**Comment by stoically** [comment]
Not sure if related: Since v3.22.3 the app keeps spamming an HTTP 204 request to the server, as soon as it goes into the foreground. It only stops when the app goes into the background or is fully stopped.

**Comment by nickvergessen** [comment]
I still run 24 and also noticed a lot of requests to index php/204 recently from android and I wonder what that is even about.

**Comment by PVince81** [comment]
please try doing a `curl -D - https://yourdomain/index.php/204`
for the upload to work it needs to return a valid http response with headers, not "nothing at all"

**Comment by PVince81** [comment]
if using mod_ratelimit one would need to exclude that route, otherwise it would likely get throttled
I didn't check how often the clients calls that route, I hope it's not once per file, otherwise it can get throttled quickly

**Comment by AlvaroBrey** [comment]
The calls to the `/204` endpoints are periodically brought up in issues and was last discussed in https://github.com/nextcloud/android/pull/10087. It was implemented [7 years ago](https://github.com/nextcloud/android/pull/1672).

I am still completely unsure whether we need to check this during regular operation at all. For uploads, downloads, etc, detecting a walled garden should be the same result as actually attempting the upload/download and failing. However, removing this check may result in extra work being done for attempting uploads. cc @tobiasKaminsky 

What we can do _right now_ is what was suggested in https://github.com/nextcloud/android/pull/10087#issuecomment-1119193502: cache the 204 result to avoid multiple requests in a short time, e.g. when uploading multiple small files. I'll take a stab at it today.

**Comment by AlvaroBrey** [comment]
>  I hope it's not once per file, otherwise it can get throttled quickly
It's sometimes even more than that I'm afraid. This is 7 year old code :(

**Comment by PVince81** [comment]
@AlvaroBrey while the code for this check itself hasn't been touched recently, is it possible that recent changes around upload have caused it to be called more often than before ? If not then probably many of us just got unlucky at the same time (it sometimes happens in this universe!)

The only recent change I heard of was the fixing of the race condition to prevent reupload/conflicts issues. Not sure if related at all.

Anyway, there are two possible actions I see from here:
1) improve logging/errors so that admins know they need to check their index.php/204 in case it doesn't respond as expected (ex: mod_ratelimit)
2) for later, find ways to make that check happen less often, for example by caching the last result for some time (debounce). But I can't judge if this would cause other side effects

so we keep this ticket for 1) ?

**Comment by AlvaroBrey** [comment]
> @AlvaroBrey while the code for this check itself hasn't been touched recently, is it possible that recent changes around upload have caused it to be called more often than before ? If not then probably many of us just got unlucky at the same time (it sometimes happens in this universe!)
> 
> The only recent change I heard of was the fixing of the race condition to prevent reupload/conflicts issues. Not sure if related at all.

There have been major changes to uploads recently (new upload worker since 3.22 for devices on Android 12+), but I don't think they should mean an increase in calls to /204, especially not on 3.22.3.

> 
> Anyway, there are two possible actions I see from here:
> 
>     1. improve logging/errors so that admins know they need to check their index.php/204 in case it doesn't respond as expected (ex: mod_ratelimit)
> 
>     2. for later, find ways to make that check happen less often, for example by caching the last result for some time (debounce). But I can't judge if this would cause other side effects
> 
> 

Did both in #10996 , let's see how that goes.

**Comment by stoically** [comment]
@AlvaroBrey 

> but I don't think they should mean an increase in calls to /204, especially not on 3.22.3.

Just an observation: This made me check my monitoring, and I can see an unusual increase of 204 requests for some weeks prior to `3.22.3` (Nov 3) already. It did get much worse since Nov 3 though.

**Comment by lckarssen** [comment]
A day or two ago my Samsung S22 updated to Android 13 and since then auto-uploads have been working again... :confused: :thinking:

**Comment by lckarssen** [comment]
And here's the output of the `curl` command:
```bash
 curl -D - https://cloud.<redacted>.com/index.php/204                                         
HTTP/1.1 204 No Content
Date: Wed, 09 Nov 2022 15:42:39 GMT
Server: Apache/2.4.41 (Ubuntu)
Strict-Transport-Security: max-age=63072000; includeSubdomains;
Strict-Transport-Security: max-age=15552000; includeSubDomains
Referrer-Policy: no-referrer
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Robots-Tag: none
X-XSS-Protection: 1; mode=block
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-cache, no-store, must-revalidate
Pragma: no-cache
Content-Security-Policy: default-src 'none';base-uri 'none';manifest-src 'self';frame-ancestors 'none'
X-Request-Id: ht9VMIbBvoIBo0q4DRJ7
Feature-Policy: autoplay 'none';camera 'none';fullscreen 'none';geolocation 'none';microphone 'none';payment 'none'
Set-Cookie: 51328818a9f40=l305n0knklfnk3b1f5pv0kdien; path=/; secure; HttpOnly; SameSite=Lax
Set-Cookie: oc_sessionPassphrase=XXXX<redacted>XXXX; path=/; secure; HttpOnly; SameSite=Lax
Set-Cookie: 51328818a9f40=na4hjlb9ldvtmc3jsbhqf7og5e; path=/; secure; HttpOnly; SameSite=Lax
Set-Cookie: __Host-nc_sameSiteCookielax=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=lax
Set-Cookie: __Host-nc_sameSiteCookiestrict=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=strict
```

**Comment by AlvaroBrey** [comment]
> A day or two ago my Samsung S22 updated to Android 13 and since then auto-uploads have been working again... confused thinking

Well, it could have been some power management thing maybe. Samsung is notoriously bad for killing apps and processes in background.

**Comment by stoically** [comment]
fwiw, https://github.com/nextcloud/android/pull/10996 did not fix the issue for me. Downgrading to 3.22.2 helps. Please let me know if I can provide more information or should open a new issue.
