### ISSUE TITLE
German playstore description

### ISSUE THREAD

**Issue by JSoko** [nextcloud/android#11]
### Actual behaviour
The german description in the playstore at the moment is:
"Die Nextcloud Android App können Sie alle Ihre Dateien auf Ihrem Nextcloud zugreifen."

### Expected behaviour
sholud be:
Die Nextcloud Android App. Mit ihr können Sie auf alle Ihre Dateien in Ihrer Nextcloud zugreifen.
 
### Steps to reproduce
 Search for the nextcloud app in german playstore

### Environment data
Android version: 6.01
Playstore Version: 6.5.08.D-all 2792142

Device model: 
SGS5
Stock or customized system:
customized
Nextcloud app version:
1.0.0
Nextcloud server version:
oc 9.0.2
#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

**Comment by AndyScherzinger** [comment]
@JSoko Thanks for reporting this. @jospoortvliet I guess this one is for you, since the Play Store listing only has English texts configured, I guess Google's Play store is auto-translating at least some stuff. I guess we should also put store texts into the upcoming translation repos.

**Comment by tobiasKaminsky** [comment]
I have translated the description to german.
Please check if this is fine for you?
cc @jancborchardt

**Comment by JSoko** [comment]
Looks good now! :-)

**Comment by LukasReschke** [comment]
Thanks for the feedback! 🚀

**Comment by AndyScherzinger** [comment]
@LukasReschke IMHO this means we should also add the play store listing text to transifex to make sure we don't hit the same auto translated texts in the Play store :)

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger I have changed this directly in the developer console.
