### ISSUE TITLE
Instant Upload broken on Android N

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#110]
With the release of Android N the instant upload feature doesn't work anymore. Most likely due to changes for background processing, doze etc. the instant upload simply doesn't get called anymore, see also the forums: https://help.nextcloud.com/t/direct-upload-photos-doesnt-work/1469

**Comment by tobiasKaminsky** [comment]
There is also an issue in owncloud regarding this.
When will Android N be released? By that date we need to have a solution.

**Comment by tobiasKaminsky** [comment]
https://developer.android.com/preview/features/background-optimization.html

**Comment by AndyScherzinger** [comment]
There is no official date yet, probably sometime around September.

**Comment by LukeOwncloud** [comment]
Does not work for me either. And i am still using 4.2.2

**Comment by Olodin** [comment]
I am having the same problem with the latest Developer Preview on Nexus 5X.
A release date of 22.8. is possible:
http://m.androidcentral.com/android-70-nougat-likely-releasing-august-22

I am happy to test with latest nextcloud beta builds from fdroid.

**Comment by michalmiddleton** [comment]
I can confirm this behavior on Android 7.0 (stock) on Nexus 6P

**Comment by maethor** [comment]
Android 7.0 is out. Any news on this bug?

**Comment by AndyScherzinger** [comment]
Hi @maethor unfortunately no. We have been on vacation for the last weeks but hope to be working on this at the Nextclpud Conference.

**Comment by AndyScherzinger** [comment]
Further info in addition to @tobiasKaminsky's link is https://developer.android.com/about/versions/nougat/android-7.0.html#background_optimizations which also points out that from Lollipop onwards JobSheduler is the prefered way to go. Need to check the google example https://github.com/googlesamples/android-JobScheduler and maybe some tutorials like http://code.tutsplus.com/tutorials/using-the-jobscheduler-api-on-android-lollipop--cms-23562 and http://www.vogella.com/tutorials/AndroidTaskScheduling/article.html

**Comment by AndyScherzinger** [comment]
@michalmiddleton exactly like you mentioned it, but @tobiasKaminsky and I are aiming for a slightly different solution for this issue. Please bare with us since this is now our top priority (except fixing a nasty bug with the latest release, hopefully by tomorrow).

**Comment by stratus-ss** [comment]
I am still suffering from this problem on my Nexus 5X. I actually am running the owncloud app for the instant upload function only with instant upload disabled in the nextcloud app.

I appreciate the work you guys do, but please fix this soon :+1:

**Comment by tobiasKaminsky** [comment]
We do our best, but are doing it in our (very short) free time.
But we have some really impressive improvements for this. It is worth waiting for it, I promise.

**Comment by fossibaer76** [comment]
Are there any news on this topic. Can we somehow assist you? For me this is actually the only annoying problem with nextcloud

**Comment by AndyScherzinger** [comment]
Hi @fossibaer76 

not right now, we are close to be done with a first iteration of the initial, new implementation which will then be available in the beta app first. My estimate would be, just a couple more days, than it will be ready for beta. Sorry for the wait and thank you for your help and patience. So assisting would then be testing the beta app (which can be installed in parallel to the stable release): https://f-droid.org/repository/browse/?fdfilter=com.nextcloud&fdid=com.nextcloud.android.beta

**Comment by AndyScherzinger** [comment]
Main issue to follow for the actual progress is: https://github.com/nextcloud/android/issues/285

**Comment by iGadget** [comment]
After reading #285 I'm a bit confused - does this mean InstantUpload will not work until 1.5.0 is released? I'm currently at 1.3.1 (latest in the Play store) and I really miss this feature...

**Comment by AndyScherzinger** [comment]
@iGadget  you can find the feature in the beta app released on f-droid :)

**Comment by maethor** [comment]
Hi,

Thanks a lot to all the developers! 

It seems to work fine, but is it possible to force the upload of all the old pictures of the file? Currently it seems to upload only the new ones taken after the configuration of Auto upload.

Also, is it possible to auto upload not only pictures but any repository ? It would be great to upload titanium backups, for instance.

Thanks :+1:

**Comment by AndyScherzinger** [comment]
Hi @maethor,

thanks for the feedback. Right now the implementation only supports auto upload of newly taken pictures but this functionaliyt will be extended in the future, see #285 for details. tl;dr at a later stage we will support any kind of folder content and also the upload of older pictures taken before setting up of the sync.

**Comment by seisen** [comment]
Android 7
Nextcloud Android bêta 20170111

when taking a picture,  no instant upload is triggered.

I tried to store the picture on internal or SDcard. 
i made the app to look at the correct directory. 

When a disable/enable InstantUpload on the directory,  the log seems ok:

/01/15 18:19:42
SyncedFolderObserverService : start observer: /storage/emulated/0/DCIM/100ANDRO

2017/01/15 18:19:42
SyncedFolderObserver : Started watching: /storage/emulated/0/DCIM/100ANDRO

2017/01/15 18:19:42
SyncedFolderProvider : notifying folder sync data observers for changed/added: /storage/emulated/0/DCIM/100ANDRO

**Comment by eleith** [comment]
on 1.4.1 RC3 my autoupload rarely triggers. 

it does work from time to time, but mostly, it just doesn't work.

this wasn't the case with 1.4.1 RC1 (however, even then, some files would sometimes be skipped. i believed this to be with HDR photos though and was hoping the 10 second delay in a future release would fix it, but it appears regressions have occurred).

**Comment by AndyScherzinger** [comment]
Hi @eleith, 
afaik we didn't change anything there after RC1 except the 10 seconds delay and a ignore for subfolders an *.tmp files. @tobiasKaminsky any ideas? Else you are right, the HDR processing somehow blocks our detection mechanism (for a yet unknown reason).

**Comment by michalmiddleton** [comment]
@AndyScherzinger I too can confirm that HDR pretty much breaks the upload. My Nexus 6P is set to Auto for both the Flash and HDR. Pretty much every time I take a picture indoors, the phone chooses HDR over Flash and the picture never gets uploaded. I had to switch to upload via Google Photos and mount my GDrive via NC external storage :-(

**Comment by AndyScherzinger** [comment]
@michalmiddleton yeah I also suffer from the HDR issue with my Nexus5X but haven't found the time to further investigate how to properly handle this Google post-processing magic and what happens on the file system...

**Comment by eleith** [comment]
my camera defaults to HDR. I can switch it to non HDR, but the default can't be changed. 

however, I do still find that some non HDR photos also don't back up. I've tried to reproduce, but it seems very inconsistent. perhaps the camera still post process the photos every now and then.

I'll wait till logging is enabled on non beta builds to further debug. but for now, I will resort to manually backing up the photos.

ps: I would pay for the nextcloud app if it could fund full-time development of the app =]

**Comment by eleith** [comment]
as a workaround, I am able to confirm that FolderSync on Android properly auto uploads all photos including HDR photos (at least for my test of three photos)

fyi: their instant sync option is only available on their pro version. 

the nextcloud UI is much more intuitive but FolderSync does seem to work and has a few neat features that are worth exploring.

**Comment by eleith** [comment]
after using FolderSync for a few days now, I can confirm that while it generally works better than 1.4.1RC2 (RC3 and RC4 rarely work for me), it still hasn't completely "solved" the issue.

the filewatching apis must be tricky.

not only does HDR prove to sometimes cause photos to be missed but just taking multiple photos at once.

however, FolderSync provides the option to do a manual one-way and two-way folder sync. i don't use the two-way folder sync, but i did set up a weekly recurring task to trigger a one-way sync from android to nextcloud and this does a great job at uploading any files that were missed by the auto upload feature.

it seems like this is also planned by the android team, so it seems like you are on to the right track. there seems to still be some room for improvement with the auto upload feature, but my guess is there might be a limit to how good it can get if you only use the file watching API.

a cadence of syncing the entire contents of the folder seems to be the sure fire way to provide the consistency users will need.

two-way sync seems like overkill, especially for users like me who want photos on the server to not be moved to the android device but would want all photos on the android device to find their way on the server.

anyhow, just wanted to follow-up on my last comment, to provide more details on what works and not works for me with FolderSync. clearly auto-upload is hard and the community is lucky to have a few folks help push this great app forward =]

**Comment by AndyScherzinger** [comment]
Hi @eleith 

thanks for the update/follow-up 👍 

> it seems like this is also planned by the android team, so it seems like you are on to the right track. there seems to still be some room for improvement with the auto upload feature, but my guess is there might be a limit to how good it can get if you only use the file watching API.

> a cadence of syncing the entire contents of the folder seems to be the sure fire way to provide the consistency users will need.

Yes, as mentioned in #285 we will have to go beyond the file watching API and probably start with a one-way sync to make sure everything finds its way to the server even if it isn't instantaneously.

**Comment by mario** [comment]
This is now being actively worked on. You should be able to test it tomorrow via the following link:

https://github.com/nextcloud/android/raw/beta/apks/latest.apk

**Comment by jmhunter** [comment]
Do these APKs make it to the Google Play store under the 'Beta' tester scheme? I am one of those affected (auto upload not working for me since my phone upgraded to Android 7) and would love to test any new/updated versions.
I have signed up using the link in the app (Good idea, guys, BTW!) but there don't seem to be any beta versions on the Play store to test?

**Comment by mario** [comment]
Hey, Play store only gets Release candidates under 'Beta' tester scheme for now - we'll work on doing it automatically eventually, but maybe under the alpha scheme for daily builds as we sometimes make trouble :)

You can either use the link I provided or Fdroid which has a delay of 24 hours, but still publishes beta daily and allows automatic update - https://f-droid.org/repository/browse/?fdfilter=com.nextcloud&fdid=com.nextcloud.android.beta

**Comment by tobiasKaminsky** [comment]
Beta tester on Play store is for Release Candidates of new major releases.
Alpha testing on Play store is currently not included, and I am uncertain if we should open daily builds to such a big audience or leave it for more tech-affine users on fdroid.

**Comment by jmhunter** [comment]
Have just tested the latest APK (20170215) from github as above. (At first I installed F-Droid and it automatically picked up on my existing 1.4.1 Nextcloud app; I didn't realise there was a separate 'Beta' app I needed to choose.. hopefully this post will help someone else scratching their head looking for beta updates to the regular app!)

I can confirm that auto-upload seems to be working fine now on my Android 7 handset. I have taken some photos and they were all uploaded straight away - this would seem to resolve the situation originally reported for this issue.

I guess whenever the next release is pushed to Google Play store this could hopefully be closed :)

**Comment by chefboyct** [comment]
Hi all, just upgraded my Huawei P9 plus to Nougat and as discussed, I have random issues with Nextcloud Android 1.41 (It closes randomly and upload doesnt work). And now I installed the F-droid nightly version 20170223 and when I log in, I get "unknown error" message. When I typed in https:// .... and it showed secure connection established. And when I enter username and password, it will detect the username and password incorrect. But the moment I enter the correct credential, it shows "unknown error". Please let me know if you need any error log and how to get them on Android. Unfortunately there is nothing showing on my Zorin syncing application as it couldn't even log in. Thanks

**Comment by AndyScherzinger** [comment]
Hi @chefboyct are when talking about 1.4.1 are you using the Google Play store or also the f-droid store? Simply asking since 20170223 is flawed but Google Play already offers the 1.4.2 RC4 version which should solve your issues but in order to get that version you need to register as a tester here: https://play.google.com/apps/testing/com.nextcloud.client

**Comment by chefboyct** [comment]
Thanks @AndyScherzinger . I will give it a try later. I just registered as a tester! Much appreciated!

**Comment by chefboyct** [comment]
@AndyScherzinger . There seems to be some issue with Play Store as I can not connect it via my Huawei P9 plus at the moment. However I can assess the site from my laptop (wired network). Maybe it is busy registering me as a Beta tester? Overall the experience with Nougat has not been great on all levels! :(

**Comment by chefboyct** [comment]
Thanks @AndyScherzinger  It worked like a charm! amazing new interface and also more options for the upload! Excellent work and my hats off to the developers!

**Comment by mario** [comment]
Happy to serve you ;)

**Comment by dan-nkl** [comment]
Auto-Upload in Build 20170301 doing nothing on Android 7.1.1 :(

**Comment by mario** [comment]
Yea so ... which phone?

**Comment by mario** [comment]
cc @dan-nkl :)

**Comment by chefboyct** [comment]
Just in case... please check your battery manager to ensure that Nextcloud
stay up and not closed after screen shut down... it was my 1st mistake. If
not, then I guess we have a problem Houston  !

Kindest regards,

Brad Peng

**Comment by dan-nkl** [comment]
The Phone is an OnePlus One with to be exactly: LineageOS 14.1-20170327-Nightly

I don't think that this is a problem with settings in the battery manager. I tested every option from saving energy to high power with the Nextcloud app on top and screen on for 30 minutes... :/

**Comment by dan-nkl** [comment]
Seems to work now
Running 1.4.2

**Comment by AndyScherzinger** [comment]
I'd say we than close this issue 👍 
Since there are also new issues with deal with bugs and optimizations to the new auto upload implementation. Please re-open if anyone thinks it is still helpful to keep it open.
