### ISSUE TITLE
Disable outdated server warnings by default

### ISSUE THREAD

**Issue by hhirtz** [nextcloud/android#11003]
### Is your feature request related to a problem? Please describe.
Outdated server warnings provide little value to end users. They have no control on the server version and thus can't/won't do anything with the warning except ignore it.

It also hides UI elements such as the plus (+) button and thus degrades the usability of the app.

### Describe the solution you'd like
Disable the warning by default.

### Describe alternatives you've considered
Disable the warning completely. However:

- the logic has already been implemented,
- some users (e.g. instance admins) might want to enable such warnings to keep the version up to date.

Thus I think it's better to just change the default value.

### Additional context
The setting is named `show_outdated_server_warning`.

**Comment by joshtrichards** [comment]
Let's consolidate these efforts into #3855
