### ISSUE TITLE
Huge (40+GB) user data storage usage even without downloading anything

### ISSUE THREAD

**Issue by tobiscode** [nextcloud/android#11005]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

A bit unclear, but here's my guess:
1. Use auto-upload for a folder, don't select "delete file after upload"
2. Delete the file manually (this is what Signal does with its old local backups after there is a newer set of backups)
3. Somehow, the file stays in the user data folder (**not** `media/com.nextcloud.client/nextcloud` folder) and forgets about them.
4. Clearing cache doesn't help.

### Expected behaviour

Even if Nextcloud keeps a copy of a file while it uploads it, it should either be in the cache folder (such that I can clear it manually), or it should keep the user data folder clean.

### Actual behaviour

I am now seeing **40+ GB of user data folder space** for a Nextcloud installation that is used **solely** to upload things - nothing is downloaded, my "on this device" tab is empty, as is the `media/com.nextcloud.client/nextcloud` folder.
I'm hoping this can be fixed soon, because otherwise I'm going to run out of storage and I have to reinstall the entire app and having to re-setup all of my auto-upload folders which is a lot of unnecessary work :/

### Android version

13

### Device brand and model

Pixel 6

### Stock or custom OS?

Stock

### Nextcloud android app version

3.22.2

### Nextcloud server version

23.0.10

### Using a reverse proxy?

I don't know

### Additional information

I've found this related post: https://help.nextcloud.com/t/high-storage-space-usage-by-android-app/53026/6 - sadly, I don't have root rights, so I can't try this fix for myself, which is also why I don't have any access to logs.

If this is a hard issue to track down, I'm happy to install a beta version to see if it becomes clearer from future logs (since the storage is already full).

**Comment by fabian-hk** [comment]
I have the same issue with nearly the same configuration.

**Comment by AlvaroBrey** [comment]
Known issue (#10885), update to 3.22.3.

**Comment by tobiscode** [comment]
I've updated to 3.22.3 RC2 and the user data folder is still huge - do I need to reinstall or should it fix itself?

**Comment by AlvaroBrey** [comment]
> I've updated to 3.22.3 RC2 and the user data folder is still huge - do I need to reinstall or should it fix itself?

Unfortunately you will need to reinstall or clear data - we can't purge the storage as there may be things that are supposed to be there, among the ones that aren't.

Also, 3.22.3 should be available in stable (not RC) version: https://github.com/nextcloud/android/releases (unless you install from FDroid, in which case you'll need to wait for them to build it)

**Comment by tobiscode** [comment]
Thanks for the fix & details! (Indeed, I'm using F-Droid, but that's fine I can wait a couple of days and then reinstall.)
