### ISSUE TITLE
After uploading a large file, I get an error notification

### ISSUE THREAD

**Issue by Kalytis** [nextcloud/android#11017]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Upload a large (5 Go) file to my Nextcloud drive.

### Expected behaviour

File should upload and that's it

### Actual behaviour

I get a random error notification, even though the upload went fine.

### Android version

11

### Device brand and model

Oneplus 7T Pro

### Stock or custom OS?

Stock

### Nextcloud android app version

3.22.3 RC2

### Nextcloud server version

Last

### Using a reverse proxy?

No

**Comment by Kalytis** [comment]
![Screenshot_20221109-192459__01](https://user-images.githubusercontent.com/31107370/200912403-b3d1c477-6ac3-42d8-b587-6f6c77db672c.jpg)

**Comment by AlvaroBrey** [comment]
Looks like a server configuration issue. When uploading a large file, it is first uploaded in chunks, and then a final operation is done server-side where those chunks are put together. This looks like the server is timing out during that last call.

Are you the admin of the server? If so, what is the timeout for requests in your web server?
