### ISSUE TITLE
Replace `set-output` in Github Actions with environment files

### ISSUE THREAD

**Issue by AlvaroBrey** [nextcloud/android#11018]
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by joshtrichards** [comment]
Deferred for now, but looks like still a good idea.

https://github.blog/changelog/2023-07-24-github-actions-update-on-save-state-and-set-output-commands/

I only see it in one spot:

https://github.com/nextcloud/android/blob/a3010629eb746e129c94cf6c6d408994ffe0f25f/.github/workflows/qa.yml#L20
