### ISSUE TITLE
Calender/contact backup gets uploaded to whatever Nextcloud instance you have open at the moment

### ISSUE THREAD

**Issue by joeyboon** [nextcloud/android#11016]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. add at least two Nextcloud accounts to the android app.
2. Enable daily backup for contacts and calendar.
3. Open the other account in app and keep it that way.
4. Wait for the daily backup to complete.

### Expected behaviour

In the ideal situation contacts and calendar backups should either be uploaded to the individual account they belong to or only to the primary account. 

### Actual behaviour

Backups are uploaded to whatever account you have selected at that moment. So if I leave my work account open it uploads my private data (calendar en contacts) to my work account. 

### Android version

13

### Device brand and model

Pixel 6

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

3.22.3

### Nextcloud server version

24.0.7

### Using a reverse proxy?

No

### Additional information

Running GrapheneOS

**Comment by ezaquarii** [comment]
@AlvaroBrey I'll review the code to see if anything stands out.

**Comment by AlvaroBrey** [comment]
@joeyboon I've found and patched the cause of the bug for calendar upload. However, can you confirm that the problem also happens for contacts backup? I couldn't reproduce it, and can't find anything wrong with the contacts code.

**Comment by ezaquarii** [comment]
@AlvaroBrey I reviewed the contacts code, and it looks good to me as well.  I think it was inaccurate issue description.

**Comment by joeyboon** [comment]
I'm sorry for not getting back to you! Thanks for fixing this, my description was indeed inaccurate, it only affected the calendar. Thanks again! :)
