### ISSUE TITLE
Process scanned document in the background

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/android#11021]
### Is your feature request related to a problem? Please describe.
Scanning a document is quite snappy. However after selecting the crop and confirming the scan the final processing and upload takes quite long (~20 seconds on a Pixel 3A)

### Describe the solution you'd like
Any further processing should ideally happen in the background. A notification could show the progress of this but it would be great if one could continue using the app right away.

### Describe alternatives you've considered
None

### Additional context
None

**Comment by AlvaroBrey** [comment]
Working on #11201 I realized that most of this processing time is due to compression. Original settings were PNG with 100% quality; when changing that to JPEG the time to process the image is significantly shorter.

Unfortunately I don't have direct means to make this happen in the background as it's all handled by an external lib; I'd need to fork it.

**Comment by juliushaertl** [comment]
> Working on https://github.com/nextcloud/android/pull/11201 I realized that most of this processing time is due to image compression. Original settings were PNG with 100% quality; when changing that to JPEG the time to process the image is significantly shorter. I may be able to make it faster by reducing the quality but I haven't tested.

Cool, sounds reasonable to just bring down the waiting time.

**Comment by serotonie** [comment]
> Working on #11201 I realized that most of this processing time is due to image compression. Original settings were PNG with 100% quality; when changing that to JPEG the time to process the image is significantly shorter. I may be able to make it faster by reducing the quality but I haven't tested.
> 
> Unfortunately I don't have direct means to make this happen in the background as it's all handled by an external lib; I'd need to fork it.

What lib are you talking about ?
An Issue Report there could perhaps make the things go faster :)

**Comment by AlvaroBrey** [comment]
> > Working on #11201 I realized that most of this processing time is due to image compression. Original settings were PNG with 100% quality; when changing that to JPEG the time to process the image is significantly shorter. I may be able to make it faster by reducing the quality but I haven't tested.
> > Unfortunately I don't have direct means to make this happen in the background as it's all handled by an external lib; I'd need to fork it.
> 
> What lib are you talking about ? An Issue Report there could perhaps make the things go faster :)

It's https://github.com/zynkware/Document-Scanning-Android-SDK and it looks abandoned, unfortunately
