### ISSUE TITLE
Nextcloud app won't upload some file types like zip

### ISSUE THREAD

**Issue by blastrock** [nextcloud/android#11020]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Open nextcloud
2. Click on the `+` icon on the bottom right
3. "Upload files"
4. Go into your phone's folders and try to find your files

### Expected behaviour

I want to be able to see all my files and be able to upload any of them

### Actual behaviour

A lot of files are missing, among them .zip, .xml and .db files.

### Android version

13

### Device brand and model

Google Pixel 4a 5g

### Stock or custom OS?

Stock

### Nextcloud android app version

3.22.3

### Nextcloud server version

25.0.0

### Using a reverse proxy?

Yes

### Additional information

I have the same issue with auto uploads. I want to upload whole folders, but only certain file types are uploaded.

**Comment by AlvaroBrey** [comment]
You likely have granted the app the "Media read only" permission, rather than "All files" permission. You can grant this one through Android Settings > Apps > Special app access > All files access.

**Comment by blastrock** [comment]
Indeed that was it! Why did android move that option out of the "permissions" settings ><

Maybe this should be explained somewhere in the app, it's so hard to find out by oneself.

Anyway thank you, closing this.
