### ISSUE TITLE
Getting "Permission error" suddenly for all auto-uploads

### ISSUE THREAD

**Issue by sseneca** [nextcloud/android#11030]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Have auto-upload enabled
2. All permissions granted to Nextcloud

### Expected behaviour

It should auto-upload the media

### Actual behaviour

I keeps retrying to upload something, failing with "Permission error", retrying, etc.

### Android version

13

### Device brand and model

Pixel 4a

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

3.22.3

### Nextcloud server version

25.0.1-fpm-alpine

### Using a reverse proxy?

Yes

### Additional information

- Running the latest CalyxOS
- When I give it "Photos and videos permission", Android says the "app doesn't support the latest version of Android"

**Comment by AlvaroBrey** [comment]
> @AlvaroBrey any ideas? If I delete/reinstall the app will it lose track of the files it's already uploaded, or will I spammed with sync conflict errors?

You will have sync conflicts if you choose "also upload existing" when configuring an autoupload folder. You can disable that BEFORE configuring it by clicking the three dot menu instead of the cloud icon.
