### ISSUE TITLE
String fr translate

### ISSUE THREAD

**Issue by SvSky** [nextcloud/android#11036]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

In android/app/src/main/res/values-fr/strings.xml

### Expected behaviour

`<string name="create_new_document">Créer un nouveau document</string>`

### Actual behaviour

`<string name="create_new_document">Créer une nouveau document</string>`

### Android version

11

### Device brand and model

Corsscall

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

3.22.3

### Nextcloud server version

0

### Using a reverse proxy?

I don't know

**Comment by AlvaroBrey** [comment]
Translation issues are handled via [Transifex](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#translations). If you want you can report this or fix it yourself there

**Comment by SvSky** [comment]
Hello,
i reported the mistake to transifex and it was refused.
Sorry, i'm french and i know that the translation is wrong......

**Comment by AlvaroBrey** [comment]
@SvSky the translation has been fixed on Transifex and synced to this repo, I just checked: https://github.com/nextcloud/android/blob/master/app/src/main/res/values-fr/strings.xml#L181
