### ISSUE TITLE
AutoUploadJob does not remember restrictions after failure

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#1104]
### Actual behaviour
- Upload starts while not connected to wlan

### Expected behaviour
- Remember "upload only on wlan"
 
### Steps to reproduce
1. set auto upload to "upload only with wlan"
2. let auto upload start
3. disable wlan -> all jobs will fail
4. click on a job

We can debate if this is a desired behaviour as the user "enforces" this by clicking on the upload item and thus wants to have it uploaded now, or if it is a bug as the restriction is not remembered.
I would for the second one.
If an user wants to have an item of the upload queue "forced" uploaded (by omitting the requirements) we can add a long press click with "instant upload".

**Comment by tobiasKaminsky** [comment]
As discussed with @mario it should always obey the restrictions

**Comment by mario** [comment]
Dear users,

thank you for your patience. After lots of work, we’re super excited to be able to give you a test version with new auto upload implementation. Keep in mind we will only accept bugs related to Auto Upload in this APK, as other things might be broken.

https://cloud.nextcloud.com/s/ftZraTruRQjTe0R

This is a dev APK so it will not overwrite your existing play store/f-droid APK unless you’re already running dev version. Also, you might need to remove your existing dev version before installing this one.

Explanation of the current functionality:
- added support for custom folders
- separated image and video folders
- checks for new files happens every 15-20 minutes
- automatic retry every 15-20 minutes or when you force close/open the app
- automatic pause once network is changed (untested!)
- significantly less battery usage

All and any testing is more than appreciated, especially with large and ever-going files like Videos. (like, try to record a 30 min video).

Let me know if you’ve got any questions.

Cheers,
Mario
