### ISSUE TITLE
Autoupload doesn't upload until device is rebooted

### ISSUE THREAD

**Issue by agilob** [nextcloud/android#1106]
### Actual behaviour
- Add some folder to autoupload (nextcloud-dev from fdroid)

### Expected behaviour
-Autoupload on new files
 
### Steps to reproduce
1. take a picture
2. connect device to wifi
3. tada! nothing is being uploaded, there is no way to manually start upload of 'autoupload' folders

### Environment data
Android version: 6.0.1

Device model: 

Stock or customized system: stock

Nextcloud app version: fdroid -dev 20170615

Nextcloud server version: 11

**Comment by tobiasKaminsky** [comment]
What kind of device do you use and is the nextcloud or camera storage set to an external sdcard?

**Comment by agilob** [comment]
>What kind of device do you use

Motorola G4

>the nextcloud or camera storage set to an external sdcard?

both on device. Don't have sd card there.

**Comment by tobiasKaminsky** [comment]
But it is important to know that the taken pictures are detected and queued to the upload.
Now we need to find out why they are not processed...

What kind of settings do you use? only during charging? only on wifi?

**Comment by agilob** [comment]
Only on wifi.

Just checked and if I take picture while device is connected to wifi, it's uploaded immediately. In scenario from top comment, it's uploaded only after reboot.

**Comment by nordic-style** [comment]
I am not sure if its related, but i my app does not upload all images, but just some. They are all in the same directory on my mobile and there are no failed uploads. It seems that the app does not track all uploads. A reboot did not help.

Using Galaxy S8 with Android 7 on nextcloud 12 and 1.4.3 app version from play store.

**Comment by mario** [comment]
Well, that's not entirely correct but I understand why you think so :D

It'll fixed in 1.5.

**Comment by mario** [comment]
Dear users,

thank you for your patience. After lots of work, we’re super excited to be able to give you a test version with new auto upload implementation. Keep in mind we will only accept bugs related to Auto Upload in this APK, as other things might be broken.

https://cloud.nextcloud.com/s/ftZraTruRQjTe0R

This is a dev APK so it will not overwrite your existing play store/f-droid APK unless you’re already running dev version. Also, you might need to remove your existing dev version before installing this one.

Explanation of the current functionality:
- added support for custom folders
- separated image and video folders
- checks for new files happens every 15-20 minutes
- automatic retry every 15-20 minutes or when you force close/open the app
- automatic pause once network is changed (untested!)
- significantly less battery usage

All and any testing is more than appreciated, especially with large and ever-going files like Videos. (like, try to record a 30 min video).

Let me know if you’ve got any questions.

Cheers,
Mario

**Comment by agilob** [comment]
Thanks, I assume this will be available in fdroid in a few days?

**Comment by mario** [comment]
Few days depends largely on Google now. So we'll see when :)

**Comment by agilob** [comment]
I have the latest -dev version from fdroid. Made 6 pictures yesterday, came back home, turned on wifi, 6 pictures were added to uploads list, 4 were uploaded, 2 are "waiting to upload", wifi was on over night, still waiting. turning on and off wifi doesnt start upload.

This function doesnt work for me:

>automatic retry every 15-20 minutes or when you force close/open the app

**Comment by mario** [comment]
Well I said this is not available on f-droid?
