### ISSUE TITLE
Show Albums & Shared Albums under the app

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/android#11070]
Now that we can create albums and share them with users in NC 25 it would be nice to have a tab under this app to show shared with me, shared with others

Please see below on how Synology is doing it on their Photos app.

![Screenshot_20221122_132907_Photos](https://user-images.githubusercontent.com/59488153/203404785-c91442dc-91be-48e8-868d-4c9caf4fc50d.jpg)

**Comment by tobiasKaminsky** [comment]
@artonge is there any api for clients?

**Comment by artonge** [comment]
The API uses DAV on `dav/photos/albums` and `dav/photos/sharedalbums`.

For inspiration, part of the implementation in JS is here: https://github.com/nextcloud/photos/blob/master/src/services/Albums.js
