### ISSUE TITLE
Bump targetSDK to 33

### ISSUE THREAD

**Issue by AlvaroBrey** [nextcloud/android#11086]
Mandatory for new apps by August 2023, updates by November 2023.

Changes: https://developer.android.com/about/versions/13/behavior-changes-13

Changes most likely to impact us:

- [Granular media permissions](https://developer.android.com/about/versions/13/behavior-changes-13#granular-media-permissions) for people that don't use the All Files permission
- [Bootup broadcast not received](https://developer.android.com/about/versions/13/behavior-changes-13#battery-resource-utilization) if app is in restricted performance bucket

**Comment by debojyoti452** [comment]
@AlvaroBrey 
Is this task still available?

**Comment by AlvaroBrey** [comment]
> @AlvaroBrey Is this task still available?

No. This is something we'll do ourselves at some point.

**Comment by AlvaroBrey** [comment]
Done in #11794
