### ISSUE TITLE
New autoupload feature uploads taken pictures to different location than old feature, breaks user experience

### ISSUE THREAD

**Issue by agilob** [nextcloud/android#1108]
When I'm unable to login on nextcloud using 'old' app, and I used '-dev' from fdroid I added and setup autoupload for picture from `DCIM/`, previously I could set 'autoupload taken images'. New system instead uploading images, it watches for new files in a folder and uploads them [folders] to `InstantUpload/.` When I use subfolders, the new system uploads pictures to:

* /InstantUpload/DCIM/2017/06 or:
* /InstantUpload/Pictures/2017/06 when the old system was uploading everything to:
* /InstantUpload/2017/06

the behaviour is inconsistent and breaks user experience. Personally I much preferred upload taken pictures feature, as it was camera-app agnostic. I was able to upload pictures from OpenCamera and LG Camera (great burst-photo functionality) independently. Pictures and videos from both app were uploaded to the same directory. With the new system I had to configure two different folders to observe and I still ended up with two different directories with **new** pictures, which I have to manually merge with my old folders.

Previous system was much better organised and required less user actions to successfully organise images.

**Comment by tobiasKaminsky** [comment]
You can click on the "remote folder" and set it to any folder you like, so you can have all images in the same directory.

**Comment by agilob** [comment]
Thanks I managed to setup it up as it was before.
