### ISSUE TITLE
Support for "files drop" feature

### ISSUE THREAD

**Issue by schiessle** [nextcloud/android#111]
Nextcloud allows you to create public link shares where the users don't see the file listing but can only upload files. This is how it looks like in the web interface:

![filedrop](https://cloud.githubusercontent.com/assets/1589737/16657742/d103b50e-4463-11e6-8721-294b79818db0.png)

If a public link is created and the "Allow editing" permission was set a additional check box shows up, "Hide file listing". If activated it removes the "read" permissions, so it is a simple permissions change which can already be done by the OCS API. Of course this option only exists for folders.

**Comment by tobiasKaminsky** [comment]
How is this "remove read permission" done:
https://doc.owncloud.org/server/8.2/developer_manual/core/ocs-share-api.html#create-a-new-share
1 = read; 2 = update; 4 = create; 8 = delete; 16 = share; 31 = all

are those values summed up like chmod (1, 2, 4)?
Or can I explicitly remove read?

**Comment by AndyScherzinger** [comment]
Besides the necessary app change we might then also need a library change to support this.

**Comment by tobiasKaminsky** [comment]
I do not think as we can currently edit the permission value mentioned above.
So it is only a question to which value I have to change it and not how I can do it ;)

**Comment by tobiasKaminsky** [comment]
So this is working :)
I have just to do some minor UI things.

**Comment by AndyScherzinger** [comment]
Happy to help with any kind of UI implementation necessary :)

**Comment by AndyScherzinger** [comment]
@schiessle can you clearify https://github.com/nextcloud/android/issues/188 with @jancborchardt 
and/or @LukasReschke this matter blocks this issue since the implementation is done and tested but this open question remains.

**Comment by schiessle** [comment]
@AndyScherzinger As others say at #188 I think it is OK to show such a warning
