### ISSUE TITLE
nextcloud android does not detect e2e activation

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/android#11130]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

i activated the e2e pkugin beta on nextcloud 25.0.2 rc2 it works but when i run nextcloud android it tells me that e2e is deactivated by the server.  which is not true because it is active

### Expected behaviour

Active e2e folder

### Actual behaviour

i activated the e2e pkugin beta on nextcloud 25.0.2 rc2 it works but when i run nextcloud android it tells me that e2e is deactivated by the server.  which is not true because it is active

### Android version

12

### Device brand and model

S8 plus

### Stock or custom OS?

Stock

### Nextcloud android app version

3.22.3

### Nextcloud server version

25.0.2 rc2

### Using a reverse proxy?

No

**Comment by joshtrichards** [comment]
> i activated the e2e pkugin beta on nextcloud 25.0.2 rc2 it works but when i run nextcloud android it tells me that e2e is deactivated 

How do you know it works?

Also, can you provide the output of:

`occ app:list`

And the `<end-to-end-encryption> [...] </end-to-end-encryption>` portion of the output of:

`curl -u ncadmin:ncadminpass https://yourHOSTname/ocs/v1.php/cloud/capabilities -H "OCS-APIRequest: true"`

**Comment by joshtrichards** [comment]
Let's consolidate this into your other report #11155. This appears to be a duplicate.
