### ISSUE TITLE
Auto uploads subfolders based on year only

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/android#11144]
Currently there's an option to use subfolder and it stores data in subfolder based on yea and month. It should also be nice to have an option to store Auto upload files just based on year.  Not sure how complex this is

**Comment by AndyXheli** [comment]
Hello! Just wanted to see if there any feedback on this from the Android Team looks like this feature was implemented under ios app. Thanks

**Comment by leandrokemp** [comment]
Yes, please

**Comment by joshtrichards** [comment]
Added in #11852
