### ISSUE TITLE
Naming of Nextcloud Android App in F-Droid

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/android#11166]
### Is your feature request related to a problem? Please describe.

The Nextcloud Android App is currently published on F-Droid in two variations:
- [Nextcloud Dev](https://f-droid.org/de/packages/com.nextcloud.android.beta/)
- [Nextcloud](https://f-droid.org/de/packages/com.nextcloud.client/)

Users are not able to distinguish the apps by the title, but only by the `DEV` hint in the logo.
Given F-Droid sorts apps by `last modified`, the Dev version is usually listed at the very top due to the CI/CD nature, while the released version is at the bottom of the list.

This leads to very users which have installed the Dev version accidentally and do not even notice it.

### Describe the solution you'd like
The title should be changed on F-Droid to `Nextcloud (Dev)`, `Nextcloud (Beta)` or anything else. Ideally also the description should be different and explain what this app actually *is*, but I am not sure whether `fastlane` can be flavored in this way.

### Describe alternatives you've considered
Alternatively or additionally change the title of the main app to `Nextcloud (Stable)` or so, but this doesn't look that good.

### Additional context
I noticed this issue during https://github.com/nextcloud/Android-SingleSignOn/issues/470 where the Dev build was broken. After explaining users that they should switch to the stable version as workaround, many wondered why they even had installed the Dev version.

**Comment by AlvaroBrey** [comment]
cc @tobiasKaminsky

**Comment by tobiasKaminsky** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12210#note_1200824479

Problem is that Fdroid now just build generic flavor, instead of dev flavor.

**Comment by tobiasKaminsky** [comment]
I will fix it and then it should be again "Nextcloud Dev".

**Comment by tobiasKaminsky** [comment]
Auto update is now disabled on Fdroid.
Tomorrow with 20221216 I can add manually a new correct build receipt and re-enable auto update.

**Comment by tobiasKaminsky** [comment]
Update to manually merge 20221216 and re-enabled auto update.

**Comment by tobiasKaminsky** [comment]
Merged. So tomorrow it should work again.
Then we shall monitor if upcoming versions also work.

**Comment by tobiasKaminsky** [comment]
Seems to work again.
If not, please reply or create a new issue.
