### ISSUE TITLE
Crash Report: crash on start following reinstall

### ISSUE THREAD

**Issue by MikeDacre** [nextcloud/android#11168]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Not sure if it will reproduce every time.

1. Phone was factory reset by accident a week ago
2. Reinstalled, no remote files shown (they are there, just not shown in the app)
3. Tried reinstalling from other app stores
4. Force stopped, cleared cache, cleared data, unistalled, reinstalled from play store

### Expected behaviour

Not to crash

### Actual behaviour

Crashed

### Android version

13

### Device brand and model

pixel 7

### Stock or custom OS?

Stock

### Nextcloud android app version

can't get to about screen, latest play store version as of 12/14/22

### Nextcloud server version

24.0.8

### Using a reverse proxy?

No

### Android logs

This folder does not exist, no mextcloud.log on my phone.

Unfortunately, the stack trace that directed me to post here has disappeared and was not automatically copied, so I don't think this issue will be that useful.

### Server error logs

```bash
NA
```

### Additional information

Seems to be related to other issues people have posted about files not showing. 

Sans any logs, not sure how useful it will be. Fine to just close, but wanted to report.

**Comment by AlvaroBrey** [comment]
Thanks for your report, but as you said, nothing we can do without logs. You can try to get a logcat from the Android device if you want, instructions here: https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat-mag

If you don't want to, we'll close this issue

**Comment by MikeDacre** [comment]
Hey, I'm going to close this now. I ran into a bunch of other issues with my instance. Once I have everything going I will just submit a new issue if it happens again. Thanks for the pointer to getting logs with `adb`, I should have found that myself.
