### ISSUE TITLE
Auto upload: CPU load/ infinite loop

### ISSUE THREAD

**Issue by p1gp1g** [nextcloud/android#11179]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

I am not always able to reproduce with these steps, but it worked twice. I had to kill nextcloud client once. I hope it will help to reproduce:

* Reboot the phone
* Enable Wifi
* Create folder Test on the phone
* Add personalized auto upload folder on nextcloud client:
  * Local: Test
  * Distant: Test
  * Wifi Only: check
  * Charging Only: check
  * If exists: ignore
* Disable Wifi
* Copy an image into Test/ (phone)

### Expected behaviour

* Nextcloud client should check the wifi is turned on then suspend the upload if not.

### Actual behaviour

* Nextcloud client checks the wifi and start a loop of failed attempts to upload the image.

### Android version

13

### Device brand and model

Google Pixel 6A

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

v3.23.0

### Nextcloud server version

v25.0.2

### Using a reverse proxy?

Yes

### Android logs

[loop_to_upload.log](https://github.com/nextcloud/android/files/10253952/loop_to_upload.log)

### Server error logs

```bash
-
```

### Additional information

OS: GrapheneOS

It may be related to: #11066 and/or #7378 

---

I started debugging this issue because it drained my battery several times (see screenshot) and made my phone heat up. For now, I have disabled the automatic upload on the folders I want with wifi only, which defeats the purpose of the automatic upload.

<img src="https://user-images.githubusercontent.com/31284753/208302369-438a77b5-4111-43bc-8615-8c11085fb6a8.png" height=600>

**Comment by Sir-Photch** [comment]
This also happens on my device.

**Comment by AlvaroBrey** [comment]
This should be fixed by #11124 , will release soon

**Comment by Sir-Photch** [comment]
It does not happen on the latest dev build, so yeah, seems not to be a problem anymore.

**Comment by AlvaroBrey** [comment]
Fixed by #11124
