### ISSUE TITLE
Wrong title and back icon when navigating up from a folder

### ISSUE THREAD

**Issue by 4444cccc** [nextcloud/android#11186]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

I am in a subfolder of NextCloud app
I want to go to the parent folder
It shows me on the left title all files

### Expected behaviour

To see on the left the parent folder

### Actual behaviour

It shows me all files

### Android version

11

### Device brand and model

p70pad

### Stock or custom OS?

Stock

### Nextcloud android app version

3.23.0

### Nextcloud server version

25.0.2

### Using a reverse proxy?

No

**Comment by AlvaroBrey** [comment]
Not sure I'm understanding your problem. What do you expect to see, and what do you mean by "on the left"? Take screenshots if needed

**Comment by 4444cccc** [comment]
Hi,The label "Mon nuage" isn't correct since there is one more sub  folder. The is no back button, just menu bar, which is not as expected.Поздрави,д-р инж. Гинчо Костов ---- On mer., 21 déc. 2022 13:16:34 +0200  ***@***.***  wrote ----
Not sure I'm understanding your problem. What do you expect to see, and what do you mean by "on the left"? Take screenshots if needed

**Comment by AlvaroBrey** [comment]
Please post a screenshot

**Comment by 4444cccc** [comment]
But I already attached two scdeenshots. Here are they againПоздрави,д-р инж. Гинчо Костов ---- On mer., 21 déc. 2022 13:48:36 +0200  ***@***.***  wrote ----
Please post a screenshot

**Comment by AlvaroBrey** [comment]
Ah, it looks like you're trying to attach them via email, but they don't show up in GitHub. Can you attach them through the GitHub web interface?

**Comment by 4444cccc** [comment]
![Screenshot_20221221-133416](https://user-images.githubusercontent.com/121164933/208904690-95ae5f77-8acd-4469-9316-eb6bff2bc88d.png)
![Screenshot_20221221-133451](https://user-images.githubusercontent.com/121164933/208904698-e340825d-5228-4b78-bbd8-d1b3e6a06249.png)

**Comment by AlvaroBrey** [comment]
Reproduced. Steps:

1. Create folders A > B 
2. Navigate into B
3. Go back up to A
4. Title bar will show "Nextcloud" and menu icon instead of "A" and back button

**Comment by 4444cccc** [comment]
Any idea shall we have corrected mobile version?

**Comment by AlvaroBrey** [comment]
> Any idea shall we have corrected mobile version?

I will fix it at some point, but there's no ETA.

**Comment by 4444cccc** [comment]
Thanks for reproducing the error. It's on all my devices.
