### ISSUE TITLE
unable to launch saved apk installation files

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/android#11197]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

with the latest version the apk files saved on my Nextcloud are downloaded but clicking on them no longer starts the installation as was the case with the previous version

### Expected behaviour

with the latest version the apk files saved on my Nextcloud are downloaded but clicking on them no longer starts the installation as was the case with the previous version

### Actual behaviour

with the latest version the apk files saved on my Nextcloud are downloaded but clicking on them no longer starts the installation as was the case with the previous version

### Android version

12

### Device brand and model

Pixel 6 pro

### Stock or custom OS?

Stock

### Nextcloud android app version

3.23.1

### Nextcloud server version

25.0.2

### Using a reverse proxy?

I don't know

**Comment by AndyScherzinger** [comment]
Hi @tigernero79 ,
this feature had to be removed, Google forced us to do so, else the app would have gotten removed from the store and also no updates could have been published anymore. Nothing we can do here I am afraid.

**Comment by tigernero79** [comment]
Has this problem been verified instead? e2e folder created but android app says encryption is disabled server side which is not true

https://github.com/nextcloud/android/issues/11155

**Comment by AlvaroBrey** [comment]
For this issue, see #11187
