### ISSUE TITLE
FDroid Upstream Repository

### ISSUE THREAD

**Issue by OfficialMuffin** [nextcloud/android#11196]
Today, I noticed the latest android client version here on github is 3.23.1. Where as the FDroid latest version is 3.23.0. If there was a critical fix pushed to the github repo, I'd like for my client to be on that version.

Not related to Nextcloud, but for example, NewPipe has a Fdroid Upstream that allows users to download their latest version quicker than using Fdroids default upstream. As mentioned [here](https://newpipe.net/FAQ/tutorials/install-add-fdroid-repo/ )

**Comment by AlvaroBrey** [comment]
We don't control how often F-Droid builds, and we don't have the capacity to host and maintain a custom upstream right now. 3.23.1 [has been merged in F-Droid already](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12297) but you'll have to wait until their next build.

If you for some reason need the app quickly, you can always download it from our [GitHub releases](https://github.com/nextcloud/android/releases).
