### ISSUE TITLE
drive.shadow.tech acc created, nextcloud on andro7 crashs and drain battery

### ISSUE THREAD

**Issue by haroldsoixante** [nextcloud/android#11208]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

hi

was a bit surprised, since last month shadow tech website offers 20GB on drive.shadow.tech, for free
I added an account
here it is : 
my huawei p8 Lite 2015 ale L21 with lineageos14, even with an update of the nextcloud app, crash every minute and appears suddenly in foreground, on android.
here it is : 
I added the account to nextcloud
it's impossible to use the app with internet, then it crash
I updated nextcloud app to latest version : the same 
in addition, each time there is a bug report screen, where it let me use a browser, lets go on firefox, to report on a bug tracker : I connect with my gitsomething account, then error 400 (or 500)
I cant do anything on the nextcloud app, everything is blocked when internet works
nextcloud is 16% battery consumption, where the 2nd one is only 8% of an entire day. It makes the phone warm a lot, I dont know why.
it happens only since the shadow account has been validated

please notice that the backup of pictures works anyway in background

I cant upload any file, my "voldown" and "power" buttons are dead since the overheat made a false/short circuit on the buttons (power is very very hard, couldnt get sound down when testing for hours.. only volup works)
i will try to record this later, with another phone (poor video quality, 2012 device)

thank you

### Expected behaviour

  f

### Actual behaviour

  g

### Android version

7

### Device brand and model

hauwei p8 LITE ALE L21 alice 2015 version, running LOS14

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

latest one

### Nextcloud server version

ask shadow.tech

### Using a reverse proxy?

No

**Comment by AlvaroBrey** [comment]
This isn't actionable unless we have some logs, unfortunately.
