### ISSUE TITLE
Attempting to drag scroll handle ends up refreshing the folder sometimes

### ISSUE THREAD

**Issue by nanaya** [nextcloud/android#11220]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. open folder with lots of files
2. drag down the scroll handle on the right side

### Expected behaviour

folder scrolls

### Actual behaviour

half the time the folder doesn't scroll but instead refresh icon is shown

### Android version

12

### Device brand and model

asus Zenfone 9

### Stock or custom OS?

Stock

### Nextcloud android app version

3.23.1

### Nextcloud server version

25.0.1

### Using a reverse proxy?

Yes

**Comment by AlvaroBrey** [comment]
Reproduced, will investigage. Thanks for the report @nanaya

**Comment by joshtrichards** [comment]
Let's consolidate this into #11576 

While your report is the earlier one,  others have already upvoted on the newer one so I'll keep that one for prioritization.
