### ISSUE TITLE
Nextcloud Dev 20170623 crashes on start.

### ISSUE THREAD

**Issue by OlivierS1** [nextcloud/android#1123]
### Actual behaviour
-Tell us what happens
After updating from Nextcloud Dev 20170622 to 20170623, the app crashes with the following message:
"Unfortunately, Nextcloud dev has stopped."

### Expected behaviour
-Tell us what should happen
 
### Steps to reproduce
1. Update to Nextcloud Dev 20170623
2. Start the app.
3. app crashes.

### Environment data
Android version:
6.0
Device model: 
LG-G3 852
Stock or customized system:
Stock
Nextcloud app version:
Nextcloud Dev 20170623

Nextcloud server version:
NC 12.0

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by OlivierS1** [comment]
I couldn't access my files as the app would crash.
However, Autoupload was monitoring camera pictures.
I took some pictures today and saw the failed upload notification. Clicking on the notification would open up the app and give me access to upload folder. I couldn't retransmit the pictures due to connection errors.
I was able to access the settings and tried to send the log but upon selecting a folder it would crash.
I tried to modify my account details by changing the password but I could still not be able to check the files.
I decided to uninstall the app and start fresh with the same version.
Now it works.
Any idea what could be the issue?

**Comment by tobiasKaminsky** [comment]
Strange, the upgrade work without any problems. Especially as we did not changed that much between the latest versions.
But glad that it is working.

**Comment by OlivierS1** [comment]
@tobiasKaminsky I am getting the same issue with NC Dev 20170723.
Same behavior. 
With this install, I had also two more accounts set up.
Doing the camera failed upload trick, I was able to access NC Dev and switch account. After closing NC Dev, I was able to start again with the other account. Switching back to my normal account would cause the issue to occur again.
The issue was caused right after I created a folder on my PC and moved some files within the new foler which were placed on the top folder.
On the phone, I started a search when NC Dev crashed.
I had to reinstall and setup account numerous times before getting NC Dev back in order.
I tried to set "Autouploads" back, but after many tries, it seems I have isolated the root cause.
The last step, I reinstalled NC Dev and setup my normal account, but I only enabled "Back up contacts".
Upon exiting NC Dev would crash.

I did one more reinstall and have not setup "Back up contacts" and NC Dev seems to be working.

I was curious about the date as the issue occurred on version 20170623, and now it is happening on 20170723.
I think there is something to do with the date "Back up contacts" doesn't handle properly.

**Comment by tobiasKaminsky** [comment]
Can you give us a logcat while it is crashing?
https://wiki.lineageos.org/logcat.html or 

Settings > About
Tap Build number 7 times
Tap back into Settings
Tap Developer options
Tap Take bug report
Select Interactive to take a screenshot, or full to get more detail. When ready, it’ll appear in the notification area and you can share it
@jasonbayton thanks for this hint!

**Comment by tobiasKaminsky** [comment]
The bugreport option seems not to include the logcat, so you would have to use the option from the link :-/

The error message is a little bit too few, maybe you can give us ~10 complete lines?

**Comment by OlivierS1** [comment]
@tobiasKaminsky Are you saying I need to run logcat over adb then concurently run NC Dev, then cause the crash. After that run bugreport?

**Comment by OlivierS1** [comment]
@tobiasKaminsky I have emailed you new logcat and bugreport files.

**Comment by OlivierS1** [comment]
@tobiasKaminsky Any feedback on this issue?
I did uninstall NC 1.4.x a few deays ago, then installed it again without entering credentials. I didn't use the Google Beta version, since my demise with NC Dev from Mario.
I was using NC Dev 20170810 the latest, but today, after updating NC 1.4.x to 2.0.0RC2, I wanted to give it a try, so I entered my credentials. I played around for a short while, then earlier today, I tried to get back to my NC Dev 20170810 and now find myself with the crash issue.
The first thing I did when setting up the NC 2.0.0RC2 account was to set the "Passcode lock" and then change the "Storage path" to the external SD card which currently holds the same account as the one used with NC Dev 20170810.
I suspect the following could be the reason for the crash:
- Some of the code used in NC Dev and NC Google Beta point to the same location on the memory causing conflicts, corruption or deletion of config files or others.
- Transfer to external SD card doesn't move all the data in unique folders and cause files to be corrupted.
- SSL credential gets corrupted or messed-up during account creation within the app.

**Comment by OlivierS1** [comment]
Running through a new install of NC 2.0.0RC2, I tried to replicate the issue and I was successful at narrowing it down.
- "App password" don't seem to be the issue.
- I left the default for NC 2.0.0RC2 after creating account on internal storage, NC Dev 20170810 was still crashing.
- What is clear is that uninstalling NC 2.0.0RC2 allow recovering from NC Dev 20170810.

What is strange is that NC 2.0.0RC2 seems to work fine and cause NC Dev 20170810 to crash.
Once NC 2.0.0RC2 is uninstalled, NC Dev 20170810 works out of the box. No tweaking required.

Can you check and see if you can reproduce it?

**Comment by tobiasKaminsky** [comment]
Is this still happening? I am using both versions in parallel and do not experience such a crash.

**Comment by tobiasKaminsky** [comment]
No response within the last month, therefore closing.
Please feel free to reopen with additional infos, if the problem still exists.
