### ISSUE TITLE
Option to disable photo media folder notification 

### ISSUE THREAD

**Issue by xeruf** [nextcloud/android#11234]
### Is your feature request related to a problem? Please describe.
My goodness, this notification is annoying.
I get it all the time as my data is kept in sync via syncthing.

### Describe the solution you'd like
An option to disable the notification, or maybe even better, put it into a separate notification channel (for newer Android versions) so it can be disabled or priority reduced in the system settings.

### Describe alternatives you've considered
Muting all nextcloud notifications.

**Comment by AlvaroBrey** [comment]
Duplicate of #9684

**Comment by xeruf** [comment]
which disables all "General Notifications", if you are referring to the system setting

**Comment by xeruf** [comment]
ah, I don't know why I did not discover that button before, thanks...

**Comment by nanaya** [comment]
I was looking for the option too and I thought the one on notification is for the specific folder and not globally... 😅
