### ISSUE TITLE
S22 Ultra keeps creating subfolder "samsung_sm-s908b" inside autoupload folder

### ISSUE THREAD

**Issue by janaxhell** [nextcloud/android#11254]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. on S22 Ultra set autoupload folders /DCIM/Camera and /DCIM/Expert RAW to folders with same name in Nextcloud mount
2. Wait for pictures to be uploaded
3. Check Nextcloud and see all pictures inside /DCIM/Camera and /DCIM/Expert RAW
4. Take a new picture with S22 Ultra

### Expected behaviour

5. Newly taken pictures are uploaded to /DCIM/Camera or /DCIM/Expert RAW, depending on camera settings

### Actual behaviour

Newly taken pictures are inside /DCIM/samsung_sm-s908b/Camera or "/Expert RAW

Try to
6. Delete /samsung_sm-s908b from Nextcloud server
7. Take pictures again
8. /samsung_sm-s908b is created again with new pictures

### Android version

13

### Device brand and model

Samsung S22 Ultra

### Stock or custom OS?

Stock

### Nextcloud android app version

Nextcloud dev 20230111

### Nextcloud server version

Nextcloud Hub 3 (25.0.2)

### Using a reverse proxy?

Yes

### Additional information

adb doesn't give any processID and I'm not a dev, so I don't know how to fix this either

`c:\Program Files (x86)\Minimal ADB and Fastboot>adb shell pidof -s 'com.nextcloud.client'
* daemon not running; starting now at tcp:5037
* daemon started successfully

c:\Program Files (x86)\Minimal ADB and Fastboot>adb shell pidof -s 'com.nextcloud.client'
error: more than one device/emulator`

**Comment by AlvaroBrey** [comment]
> c:\Program Files (x86)\Minimal ADB and Fastboot>adb shell pidof -s 'com.nextcloud.client'
> error: more than one device/emulator`

This means you have more than phone (or tablet, or emulator, or smartwatch) connected to the computer

**Comment by janaxhell** [comment]
I don't. Unless you consider wireless as connected. As you can see the first command starts tcp port, but no deviceID is output, the second command says there are more devices while there is only the one that I have just connected. I have no reason to connect any other Android device, other than trying to extract log for this issue report from my S22.  One cable, one device.

**Comment by joshtrichards** [comment]
Hi @janaxhell 

> Nextcloud dev 20230111

You're running a Dev version. You can just go to *Logs->Settings* in the app for the logs.

Can you provide a screenshot of your active auto-upload folder config entries so we can see their settings?

**Comment by janaxhell** [comment]
I posted about this issue almost a year ago. I've changed both hardware and software since.
At the time I was using NC on an Orange Pi Zero 2, now I'm using NC AIO on a x86 server. 
I still use Nextcloud Dev on S22Ultra and this problem is no more.
