### ISSUE TITLE
Connextion timeout after entering nextcloud address in Graphene OS: The webpage at https://nextcloud.example.com/index.php/login/flow could not be loaded because:  net::ERR_CONNECTION_TIMED_OUT

### ISSUE THREAD

**Issue by Danrancan** [nextcloud/android#11276]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Open the nextcloud app (downloaded from F-droid) on Grapheme OS.
2. Enter the web address (nextcloud.example.com) of your nextcloud server in the nexrcloud app.
3. Wait a long time and a white page will appear with the following text:

```
Webpage not available
The webpage at https://nextcloud.example.com/index.php/login/flow could not be loaded because:

net::ERR_CONNECTION_TIMED_OUT
```

### Expected behaviour

The app should load the password login screen.

### Actual behaviour

The app loads a white page with an error message.

### Android version

Graphene OS Build Number: TQ1A.230105.002.2023011000

### Device brand and model

Google Pixel 6

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

2.0

### Nextcloud server version

TBA - I'm not on my instance right now, I will add this shortly

### Using a reverse proxy?

I don't know

### Android logs

I will have to post app logs after I get home when I can enable logging with the adb command. Please stand by.

### Server error logs

```bash
I am on my phone away from my server. I will post logs shortly after getting home.
```

### Additional information

Other Info:
1. Nextcloud server loads in web browser on pixel 6 just fine, but it doesn't load when using the app.
2. My nextcloud server is running on a Raspberry Pi 4 (Ubuntu Server 20.04).
3. The nextcloud app for this server works fine on iOS using the iOS app.
4. I downloaded nextcloud from F-droid on a google Pixel 6 running Grapheme OS, and this is the phone where the issue lies.

**Comment by joshtrichards** [comment]
Hi @Danrancan - Is this still occurring?

How are you entering the address in the server address window? Are you letting it assume https or are you entering it explicitly? 

E.g. `https://nextcloud.example.com` or `nextcloud.example.com`? (I assume you're using https). 

Are you using a proxy or anything like that?

**Comment by joshtrichards** [comment]
> Nextcloud android app version
> 2.0

I assume this was a typo? Since that version would be 6 years old: https://github.com/nextcloud/android/releases/tag/stable-2.0.0

**Comment by VGA71** [comment]
I'm having the same issue, were you able to resolve it?

**Comment by joshtrichards** [comment]
@VGA71 I posted some questions to the original reporter. Maybe they are relevant to getting to the bottom of the situation for you.

In general though the error means what it says and usually a configuration matter rather than a bug.

**Comment by Danrancan** [comment]
> Hi @Danrancan - Is this still occurring?
> 
> 
> 
> How are you entering the address in the server address window? Are you letting it assume https or are you entering it explicitly? 
> 
> 
> 
> E.g. `https://nextcloud.example.com` or `nextcloud.example.com`? (I assume you're using https). 
> 
> 
> 
> Are you using a proxy or anything like that?

Unfortunately i cannot tell you if it is still occurring or not because i ditched my nextcloud server. However, if someone wants to test again on graphene os i probably would put the server back up if it is working. 

From memory, i believe I was entering https explicitly in the app when trying to connect to the server. 

Sorry I cant be of more help. I will let you know if i put the server back up and do some more testing.
