### ISSUE TITLE
Android 4.x: crash on settings

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#1130]
This is introduced by https://github.com/nextcloud/android/commit/b530d38b07586c60d5a257087c934e83e37fbd63

```Caused by: java.lang.ClassCastException: com.owncloud.android.ui.CheckBoxPreferenceWithLongTitle cannot be cast to android.preference.SwitchPreference```

**Comment by mario** [comment]
Pretty sure this is fixed actually? Can you reproduce it?

**Comment by tobiasKaminsky** [comment]
Yes, it is on master, but I'll fit it :-)

**Comment by lanzi69** [comment]
Hi!

Don't know if it's the same issue but nextcloud dev v20170624 crashes when I try to open settings page.

As far as I tested yet all other functions work.

Crashing is reproducable any time I try to open the settings dialogue.

My device:
Samsung Galaxy S5 mini (kminilte)
Android v5.1.1
Baseband Version G800FXXU1BPC3
Kernel-Version 3.4.39-5886751
Build-Number LMY47X.G800FXXU1BPC4

Thx in avance for fixing! :-)

cu
Lanzi

**Comment by tobiasKaminsky** [comment]
@lanzi69 can you try it with the latest one: 
https://download.nextcloud.com/android/nightly/
or the last fdroid version 20170627

**Comment by AndyScherzinger** [comment]
Merged to master for the next release
