### ISSUE TITLE
Replace "Download" by "Make available offline" AND "Export" by "Download

### ISSUE THREAD

**Issue by Jerome-Herbinet** [nextcloud/android#11343]
All is in the title.

Here are some explanations about two wording changes I would like to make in the file contextual menu.

**1. "Download" :**
I think that "Download" is not true, not relevant, because these files are only off-line files and are not supposed to be found among the phone's folders in order to be manipulated (moved, copied, renamed or whatever). If we really analyze the action and mainly the goal of this action in the menu, the user wants the file to we available off-line ... so let's replace "Download" by "Make available offline".

**2. "Export"**
"Export" in not very understandable. The wording which may be the easiest to understand is ... download, because the user wants (and technically will) get the file in his "Download" folder ... so let's replace "Export" by "Download".

Thanks for reading me.

Jérôme

**Comment by AlvaroBrey** [comment]
I vaguely remember that "download" _used to_ be called "Available offline" but was changed. @tobiasKaminsky do you remember if this is true and why?

**Comment by Miniman45** [comment]
Is this issue open?

**Comment by Jerome-Herbinet** [comment]
Still open ; see my PR ; I didn't hate time try to understand to what's failing. Any help is welcome.
