### ISSUE TITLE
Unable to share photo with Element Android

### ISSUE THREAD

**Issue by rajil** [nextcloud/android#11351]
Sharing a photo doesn't work with Element. When you share a photo it simply opens up Element instead asking for recipient.

Steps:
1.  Open a photo in Nextcloud
2. Use menu to Send/Share
3. Select Element in the choices

Expected behaviour:
The app should give a choice to pick the element contact

Actual behaviour:
Element opens up and there is nothing to share 

Android Version: 10
Phone: Samsung Note 9
Nextcloud App version: 3.23.1
Element Android version: 1.5.22

**Comment by AlvaroBrey** [comment]
Does sharing to Element work from other apps, like from the system filebrowser or camera?

**Comment by rajil** [comment]
@AlvaroBrey yes, it does. Element offers the recipients if i share from the photo gallery.

**Comment by joshtrichards** [comment]
Not sure what's going on.

There have been bugs in element-android in their sharing logic in the past - e.g.
https://github.com/vector-im/element-android/issues/7400 + https://github.com/vector-im/element-android/pull/7473

Looks like there is a little bit of logging in their [`handleShareData` function call](https://github.com/vector-im/element-android/blob/8bfd5f7c543c9d4ffbdb1e5117b1e6014b474f85/vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerFragment.kt#L773C24-L773C24) if you can get logcat on their app...

**Comment by joshtrichards** [comment]
Can you get log output? https://github.com/nextcloud/android/?tab=readme-ov-file#logs
