### ISSUE TITLE
Nextcloud as source for Instagram does not work

### ISSUE THREAD

**Issue by OdinsAuge** [nextcloud/android#1136]
### Actual behaviour
-When I upload pictures on Instagram, I choose Gallery --> Misc and then I can choose different sources on this screen:
![screenshot_20170612-182942](https://user-images.githubusercontent.com/1121917/27531705-ee12b364-5a5d-11e7-9d62-18709ad8aff7.png)
Nextcloud is selectable but no images/folder tree get loaded.

### Expected behaviour
-In earlier versions, selecting Nextcloud opened the local storage path showing the folder tree and files that got already downloaded.
I have a tablet with an older Android version (but latest NC app) where still the old storage path is used (sdcard/nextcloud/ insteaf of /storage/emulated/.../data/com.nextcloud.client/files) there I can still select Nextcloud and get the local files shown.
 
### Steps to reproduce
1. Download file via NC app
2. Open Instagram and add an image (+ button)
3. Select Gallery -->Misc
4. Select Nextcloud from the list

### Environment data
Android version: 7.1.2 (not working), 6.?.? (working) 

Device model: Nexus 6P (not working), Galaxy Tab S2 (working)

Stock or customized system: stock

Nextcloud app version: 1.4.3 (both)

Nextcloud server version: 11.0.3

**Comment by tobiasKaminsky** [comment]
The external storage path will be in next version set again to "sdcard/media..'/" so other apps can access the files again.
