### ISSUE TITLE
 Autoupload doesn't upload

### ISSUE THREAD

**Issue by Tioborto** [nextcloud/android#1137]
### Actual behaviour
Currently, for example all images are not being downloaded in a precisely folder.
For example : 
    I take a picture in the current folder of camera (/storage/emulated/0/Download)
    The autoupload enable to remote folder (/Picture/Asus Download/) 
    But there is noothing in the remote folder.. 

### Expected behaviour
My phone pictures are synchronized
 
### Steps to reproduce
1. Take a picture
2. Enable synchronization/autoupload (by 4G) 

### Environment data
Android version: 6.0.1

Device model: Asus Zenfone 2

Stock or customized system: stock

Nextcloud app version: 1.4.3

Nextcloud server version: 12.0.0

#### Web server error log
No errors in log

#### Nextcloud log (data/nextcloud.log)
No errors in log

**Comment by ahendre2010** [comment]
Even when on wifi it isn't working. Uploading fails to start

**Comment by tobiasKaminsky** [comment]
Could this be the problem: https://github.com/nextcloud/android/issues/759#issuecomment-311283553 ?

**Comment by ahendre2010** [comment]
I have added my camera folder in auto upload two days ago and it still doesn't showing up on NC. I also have unchecked upload only via wifi. I think it should have manual trigger to start auto uploading process so if I know I am on high speed wifi for a limited time then I can use one click to auto upload my photos.

**Comment by Tioborto** [comment]
Like @ahendre2010, i think a button to manually update pictures could be a workaround

**Comment by ahendre2010** [comment]
But that workaround comes with limitation as I have to take a look which
files are uploaded already and then select folder to upload then files
remaining and then it will start.
So button to trigger auto upload can be a good enhancement.

**Comment by Tioborto** [comment]
But what is the solution on my problem ? 
The update doesn't work at this moment & it's problematic ..

**Comment by ahendre2010** [comment]
@tobiasKaminsky I think process Mario said #759(comment) could be a problem
here but manual trigger with all established functionalities makes sense to
me.

**Comment by agilob** [comment]
@Tioborto Try enabling wifi and restarting the device, this helps me with #1106

**Comment by ahendre2010** [comment]
Yes it worked for me @Tioborto in this try. Finally workaround. :)

**Comment by byteturtle** [comment]
Affecting me on 6.0.1 / MIUI 8.2 (Stock) too. My Device is the Xiaomi Redmi 4 Prime.

**Comment by mario** [comment]
Dear users,

thank you for your patience. After lots of work, we’re super excited to be able to give you a test version with new auto upload implementation. Keep in mind we will only accept bugs related to Auto Upload in this APK, as other things might be broken.

https://cloud.nextcloud.com/s/ftZraTruRQjTe0R

This is a dev APK so it will not overwrite your existing play store/f-droid APK unless you’re already running dev version. Also, you might need to remove your existing dev version before installing this one.

Explanation of the current functionality:
- added support for custom folders
- separated image and video folders
- checks for new files happens every 15-20 minutes
- automatic retry every 15-20 minutes or when you force close/open the app
- automatic pause once network is changed (untested!)
- significantly less battery usage

All and any testing is more than appreciated, especially with large and ever-going files like Videos. (like, try to record a 30 min video).

Let me know if you’ve got any questions.

Cheers,
Mario

**Comment by bnbaz** [comment]
I'm having auto-upload issues as well ('connection issue'), on MIUI 8 regardless of battery saver settings (nextcloud excluded or not). Manual uploads do work.

I just installed the dev version posted by @mario, unfortunately this version does not initiate auto-upload at all. Auto-upload is enabled for the camera folder, nextcloud removed, nextcloud dev added to battery exceptions, but it seems the new pictures are not recognized at all. This is regardless of the wifi only setting.

**Comment by mario** [comment]
@bnbaz new version does not need the battery saver disabled. What phone/os? Did you confirm that auto upload folders are configured?

**Comment by bnbaz** [comment]
@mario MIUI Global 8.2.10.0 Stable on Xiaomi Redmi 4X. Auto upload was
enabled for the camera folder and pointed to an existing cloud
InstantUpload folder.

**Comment by mario** [comment]
What android version is that?

If lower than 7, it might take up to 20 minutes for new photos to be
detected

**Comment by bnbaz** [comment]
6.0.1, I will try it again later today and let you know.

**Comment by bnbaz** [comment]
Unfortunately still no upload after an hour.

**Comment by Tioborto** [comment]
I've tested two times the auto upload & nothing is uploaded.. 

_Sent from my Asus ASUS_Z00AD using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by mario** [comment]
Do you see the photos in your camera roll/gallery app? What does the log says if you enable Expert mode in settings?

**Comment by Tioborto** [comment]
Magical.. Two pictures has been uploaded.. I don't how
I check the logs

_Sent from my Asus ASUS_Z00AD using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by mario** [comment]
See? It all works...you just need to wait :p

**Comment by Tioborto** [comment]
Wait two days to upload ? It's a normal things ?

**Comment by mario** [comment]
Well when did it appear in the upload queue? Also possibly it is ... depending on what you were doing with your phone in those two days/if anything? :)

**Comment by bnbaz** [comment]
`UploadsStorageManager  : Updating / 
storage/emulated/...jpg with status:UPLOAD_IN_PROGRESS and result:UNKNOWN (old://storage/emulated/...jpg status:UPLOAD_IN_PROGRESS result:-1)`

UploadsStorageManager  : Updating / 
storage/emulated/...jpg with status=UPLOAD_IN_PROGRESS

UploadsStorageManager  : updateUpload returns with: 1 for file : / 
storage/emulated/...jpg

UploadsStorageManager   : 
notifyObserversNow`

I can't export the logs so I typed the above part. Please let me know if you require more info. These log entries are all about the same file, and made in the same second.

**Comment by AndyScherzinger** [comment]
@bnbaz we are working on releasing the first RC of the next release to Google Play. Please test if it solves your issue. So closing it for now. Please re-open if it occurs again
