### ISSUE TITLE
Autoupload of video in wrong folder (v1.4.3 on Lollipop v5.0.1)

### ISSUE THREAD

**Issue by reglisse69** [nextcloud/android#1139]
### Actual behaviour
-Autoupload of PICTURES is configured in /some/folder with use of subfolder based on date, so a picture taken today is uploaded on /some/folder/2017/06
-Autoupload of VIDEOS is configured exactly the same way, **BUT** a video taken today is uploaded on /some/folder/201706 <= The "/" between year and month is missing

### Expected behaviour
-In this case video and files must be uploaded on the **same folder** /some/folder/2017/06
 
### Steps to reproduce
1. Configure autoupload of pictures in  /some/folder with use of subfolder based on date
2. Configure autoupload of vidos in  /some/folder with use of subfolder based on date 
3. Take a picture and a video
4. Picture is in /some/folder/2017/06 and video in /some/folder/201706 but must be in /some/folder/2017/06

### Environment data
Android version:Lollipop v5.01
Storage of camera in external SD (if necessary)

Device model: Samsung Galaxy S4 (jfltexx)

Stock or customized system: Customized ROM Imperium LL v17.0 (same conclusion with stock, but seems to be different on LineageOS cannot test for the moment).

Nextcloud app version: v1.4.3

Nextcloud server version: Nextcloud version 12.0.0 (stable)

#### Android autoupload history : 
folder without last "/" for video is missing in the history (so really not an error but a small bug)
#### Web server error log
No error in logs

#### Nextcloud log (data/nextcloud.log)
No error in logs

**Comment by tobiasKaminsky** [comment]
This is already fixed on master ind will be in next version.
(Sidenote: Android 5.x will also get the new auto upload system, so the old instant upload will only remain for the very very old devices)

**Comment by mario** [comment]
@tobiasKaminsky actually we get auto upload for 4.x too ;)

**Comment by reglisse69** [comment]
@tobiasKaminsky Thank you very much for the answer.

Will be waiting for the next release (the last dev one on FDroid is crashing).
