### ISSUE TITLE
Per Directory Sort Instead of Globally

### ISSUE THREAD

**Issue by cwmke** [nextcloud/android#114]
### Approved idea

Store sort order folder based, with descending the order to subfolder.
(like list vs. grid view is doing it)
### Expected behaviour

If I change the sort option in one directory, it is remebered for that directory.  When I leave, the sort goes back to the default A-Z sort method.
### Environment data

Android version: 6.01

Device model: Nexus 6p

Stock or customized system: Custom

Nextcloud app version: [F-Droid] Nextcloud beta 20160621

Nextcloud server version: Nextcloud 9.0.52 (stable)

Owncloud's sync app has the opposite behavior as nextCloud's.   With owncloud, when you set _Folder A_ to **Newest - Oldest** sorting, upon leaving said folder the sorting reverts to **A-Z** sorting.  When I reenter _Folder A_, it remembers my previous sorting method and displays accordingly.

This is probably an individual preference for each user but I am interested to see if other people feel similarily.  Maybe it should be an option in settings? Thanks for all of your work!

**Comment by tobiasKaminsky** [comment]
@jancborchardt your comment please.
Then the sort order would be folder based.
Should it auto descend to sub folders like the grid/list view is doing it currently?

**Comment by jancborchardt** [comment]
It should definitely work as before – remember the sort order for a folder, and apply that for all subfolders too.

**Comment by tobiasKaminsky** [comment]
There is no "as before". 
Currently we are storing the sort order globally and the view state folder based with descending to sub-folders.
Then we will do it the same way.

**Comment by tobiasKaminsky** [comment]
Implemented via https://github.com/nextcloud/android/pull/1571
