### ISSUE TITLE
Available storage missing from sidebar

### ISSUE THREAD

**Issue by danielxhaikalx** [nextcloud/android#11400]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

I cant see storage capasity on android

### Expected behaviour

I cant see storage capasity on android

### Actual behaviour

I cant see storage capasity on android

### Android version

11

### Device brand and model

Redmi Note 8 Pro

### Stock or custom OS?

Stock

### Nextcloud android app version

3.24.0

### Nextcloud server version

25.0.3

### Using a reverse proxy?

I don't know

**Comment by AlvaroBrey** [comment]
Can you elaborate on what you expect to see and where? In general just give a more detailed description

**Comment by danielxhaikalx** [comment]
At bottom on how much i use the nextcloud storage on android doesnt have limit like 400gbs left

**Comment by joshtrichards** [comment]
@danielxhaikalx This is the default behavior when there is no quota set on your account. It displays the same thing as what's in the web interface. Set a quota for your user account and it will also add an indicator of the available storage left. 

To set a quota, go into the web UI while logged into an account with NC admin privileges then go to Users -> (username) -> Quota and specify a number like "300 GB" or one of the pre-generated options.

Just tested it for sure to make sure and looks like what I think you're asking for (below).

Does this address your request?

![Screenshot_20230316-175128_Nextcloud](https://user-images.githubusercontent.com/1731941/225761476-12bb2239-1fa2-4409-af8c-153ecde3b686.jpg)
