### ISSUE TITLE
Auto upload uploads existing files causing duplicates

### ISSUE THREAD

**Issue by rugk** [nextcloud/android#1141]
### Actual behaviour
On every phone restart the auto uploader uploads **all** files in the directory (just the camera dir chosen).
I can see how the file name in the notification changes from "IMG123456.jpg" to "IMG123456 (2).jpg" in the "upload finished" notification. So I can clearly see it duplicates these photos.

### Expected behaviour
First check if the file exists on the server (& has already be uploaded) and only then upload it.
 
### Steps to reproduce
1. Upload some files already (e.g. with a previous app version).
2. Upgrade NextCloud app (and/or) enable the upload-feature
3. See how uploads all your photos and you have to cancel each single item to stop the process.

### Environment data
Android version: 7.1

Device model: LineageOS (14.1)

Stock or customized system: see above

Nextcloud app version: 1.4.2

Nextcloud server version: 12

**Comment by marvinwankersteen** [comment]
I have the same problem with the activated beta in Google Play Store.

After the most restarts, the app starts to re-upload all Images. Sometimes not.

Android version: 6.0.0 and 6.0.1
Stock or customized system: Both
Nextcloud app version: 1.4.3
Nextcloud server version: 12.0.0

**Comment by ShapeShifter499** [comment]
I have this issue too, every reboot Nextcloud tries to upload some photos but it also ends up uploading duplicates.

My system
Moto X Pure
LineageOS 14.1 06-26-2017 Nightly
Nextcloud server version 12.0.0
Nextcloud android client version 1.4.2

**Comment by Eloo** [comment]
yep, facing this issue too. Should be nice if this could be fixed in time

**Comment by rcmcronny** [comment]
yes, i am facing this issue to

**Comment by ingmarcosp** [comment]
Me too..
Huawei p8 Android 6.0
Lasted Android app un Google playStore 
Nextcloud 12.0. 0

**Comment by kst87** [comment]
Me too.
LG G4 original (Vodafone) Android 6.0
App Nextcloud 1.4.3
Nextcloud 12.0.0

**Comment by mario** [comment]
Thanks for all your reports, but this will be fixed in 1.5 - we're aware of the issues.

**Comment by mario** [comment]
Dear users,

thank you for your patience. After lots of work, we’re super excited to be able to give you a test version with new auto upload implementation. Keep in mind we will only accept bugs related to Auto Upload in this APK, as other things might be broken.

https://cloud.nextcloud.com/s/ftZraTruRQjTe0R

This is a dev APK so it will not overwrite your existing play store/f-droid APK unless you’re already running dev version. Also, you might need to remove your existing dev version before installing this one.

Explanation of the current functionality:
- added support for custom folders
- separated image and video folders
- checks for new files happens every 15-20 minutes
- automatic retry every 15-20 minutes or when you force close/open the app
- automatic pause once network is changed (untested!)
- significantly less battery usage

All and any testing is more than appreciated, especially with large and ever-going files like Videos. (like, try to record a 30 min video).

Let me know if you’ve got any questions.

Cheers,
Mario

**Comment by Eloo** [comment]
@mario 
Thanks for your work.
Sounds really promising! I will give it a try in time.

**Comment by Eloo** [comment]
are these changes in the dev-20170727 version?

**Comment by mario** [comment]
No, they are only in my APK. (There's already a new version, same URL) because we can't build this automatically yet until Google fixes their toolchain.

**Comment by Eloo** [comment]
So i've installed your apk and so far it looks promising!
Does seem to try reuploading already uploaded pictures and battery drain seems to be reduced, too.
Will try it for some more days.
But so far thanks!!!

**Comment by mario** [comment]
Thanks for the feedback! :)

**Comment by Eloo** [comment]
@mario 
So far i didn't notice any issue with your version. 
No duplicates were created and all pictures are uploaded.
Battery consumption is very low
Nice work!

**Comment by mario** [comment]
@Eloo thanks. Closing this issue then since this will be in 1.5 - yes! :)
