### ISSUE TITLE
Second Modification to File Via Storage Access Framework Fails

### ISSUE THREAD

**Issue by TechD123** [nextcloud/android#11457]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Import a databse to KeePassDX on Android that is stored on Nextcloud
2. Make a modification to the database using KeePassDX (successful)
3. Attempt a second modification (fails)

### Expected behaviour

The second modification should be synced to the Nextcloud instance as well.

### Actual behaviour

KeePassDX displays an error, which, according to the developers of KeePassDX is a problem with Nextcloud, as it "breaks the write permissions on the second opening of the file with the same URI". See [this issue](https://github.com/Kunzisoft/KeePassDX/issues/1444).

### Android version

13

### Device brand and model

 ‎‏‏‎

### Stock or custom OS?

Stock

### Nextcloud android app version

3.24.1

### Nextcloud server version

25.0.3

### Using a reverse proxy?

I don't know

**Comment by afflux** [comment]
pretty sure this is another instance of https://github.com/nextcloud/android/issues/11283. Fix is waiting for review here: https://github.com/nextcloud/android/pull/11286

**Comment by TechD123** [comment]
Ah, so this is also why Seedvault backups don't work.. Thank you for working on this, hoping it gets merged soon :)

**Comment by fuzunspm** [comment]
same issue

**Comment by joshtrichards** [comment]
@TechD123 & @fuzunspm - Can you confirm that this issue no longer occurs in >=v3.26 per #11286?

**Comment by AryehGielchinsky** [comment]
This issue has been fixed for me when I'm connected to my server and I make multiple edits. (If I do some combination of connecting and disconnecting, and editing, I get an error, but I think that was a different issue).

KeePassDX Android: 3.5.1
Nextcloud client android: 3.26.0
Nextcloud Server: 27.0.1

Thank you

**Comment by fuzunspm** [comment]
> @TechD123 & @fuzunspm - Can you confirm that this issue no longer occurs in >=v3.26 per #11286?

sorry I missed the notification but I no longer use KeepassDX but I re-installed it to test and it worked
