### ISSUE TITLE
Delay each picture upload

### ISSUE THREAD

**Issue by andreapx** [nextcloud/android#11451]
### Is your feature request related to a problem? Please describe.
Lots of time I take some pictures and after I've taken about 3/4 I want to delete the ones that are not good, but it happens that some have already been uploaded to Nextcloud, so I have to go there and delete them there too.

### Describe the solution you'd like
In the auto upload section it should be possible to select, for each folder, how much time the app should wait before upload a file. If the file isn't there anymore, it shouldn't throw any error.

### Describe alternatives you've considered
I can't see any alternative way.

**Comment by aaronsegura** [comment]
See: https://github.com/nextcloud/android/issues/7815

**Comment by andreapx** [comment]
> See: #7815

Thanks, I've missed it.
