### ISSUE TITLE
GridView with staggered grid layout

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#1147]
Currently we are cropping the images and showing them as squares in grid view.

WebUI is showing them in a much better way:
![screenshot_20170628-074513](https://user-images.githubusercontent.com/5836855/27622255-3a1fc9ee-5bd6-11e7-8913-b642fffa3c0b.png)

On android we can do this with StaggeredGridLayoutManager and RecyclerView:
![androidrecyclerviewstaggeredgridlayoutmanager2](https://user-images.githubusercontent.com/5836855/27622330-b1d9b756-5bd6-11e7-8b42-50a59a4d7a2b.png)

https://android--code.blogspot.de/2015/12/android-recyclerview.html

Of course we first need to do RecyclerView, but as a mid-term goal I think this would be much nicer than the current grid.

**Comment by AndyScherzinger** [comment]
Yes and no. ;) 

For media data as in image/video thumbnails yes because that would be a gallery view while for a file listing you would still like to get a "normal" grid view :P

**Comment by OlivierS1** [comment]
I do like the normal grid as opposed to RecyclerView as it makes scrolling through images more consistent. Especially during picture selection.
With RecylerView, it makes selecting pictures a bit more challenging.

**Comment by mario** [comment]
That makes no sense :) "Normal" grid can be implemented in recyclerview too, and will be. Everything will be recyclerview instead of list view that we use now.

**Comment by tobiasKaminsky** [comment]
@OlivierS1 RecyclerView is only a way to implement list/grid. We currently use the old system with a ListView and a GridView.
When we change to RecyclerView on the first glance nothing visual will have changed, so there still will be a list view and a grid view.

**Comment by OlivierS1** [comment]
Make sense now, 
Will the grid and list view selectable by user?
Thanks.

**Comment by mario** [comment]
Yes.

**Comment by AndyScherzinger** [comment]
Closed in favor of #2368
