### ISSUE TITLE
Nextcloud Android "auto upload" doesn't place media in specified folder

### ISSUE THREAD

**Issue by branpurn** [nextcloud/android#11486]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Enable auto upload in the Android app 
2. Point auto upload to a specific directory
3. Auto upload does not respect the chosen directory

### Expected behaviour

1a. Point auto upload a directory (remote path) to upload a local media directory (ex., camera roll)
1b. The directory path may include an "External Storage" mount as configured via the official Nextcloud web app settings
2. Auto upload should upload the media to the specified remote path

### Actual behaviour

Nextcloud for Android is not placing media in the specified remote folder.

I navigate in the GUI on Android to a specific directory. The auto upload instead navigates one directory higher, and places the remainder of the directory tree there. 

I actually already have an idea: the path contains external mounted storage through the official settings to configure that. The Android app doesn't know how to handle this.

### Android version

13

### Device brand and model

Samsung Galaxy S22

### Stock or custom OS?

Stock

### Nextcloud android app version

3.24.1

### Nextcloud server version

25.0.4

### Using a reverse proxy?

No

**Comment by joshtrichards** [comment]
Gotcha. That's helpful, but I'm sill unable to reproduce this using even external storage (S3 in this case).

Can you confirm you can upload an individual file to this same folder via the same account in:

- the NC Web UI
- the NC Android client, but outside of an auto upload workflow

?

Also, while we're covering our bases:

- What type of external storage? 
- Anything interesting showing up in the server-side logs (with debug on) around the same time you try to configure the folder as a destination in the Android client for auto upload?
