### ISSUE TITLE
Backstack navigation from "Uploads" to "On Device" continues to show "Uploads" Fragment

### ISSUE THREAD

**Issue by jsoberg** [nextcloud/android#11499]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Open Nextcloud.
2. Using the nav drawer, navigate to "Uploads".
3. Open nav drawer again and navigate to "On Device".

### Expected behaviour

See the "On Device" Fragment.

### Actual behaviour

The "Uploads" Fragment continued to be shown:

https://user-images.githubusercontent.com/1057406/229377846-761f9f71-dd66-4212-a192-4dd70826cf1f.mp4

### Android version

13

### Device brand and model

Google Pixel 6

### Stock or custom OS?

Stock

### Nextcloud android app version

3.24.1 (Google Play)

### Nextcloud server version

26.0.0

### Using a reverse proxy?

No

### Android logs

Looked through logcat and didn't see any relevant logs re: navigation.

### Server error logs

```bash
N/A
```

### Additional information

Going to take a look at the nav code for this to see if it's just a bad transition in the nav graph

**Comment by tobiasKaminsky** [comment]
We plan to overhaul navigation and replace it.
