### ISSUE TITLE
nextcloud android client can't login but android webdev clients do

### ISSUE THREAD

**Issue by pcause** [nextcloud/android#115]
I try to login using the nextcloud android client and it says wrong username/password.  i know the user name and password are correct.  an android webdave client has not issues logging in.  Using current nextcloud on server.  my server uses ssl self signed cert, port other than 443 and basic auth.

I am on Android 6 on a Samsung Note 5.

**Comment by tobiasKaminsky** [comment]
@pcause is this still a problem? If so, can you give us a test account and sent the details to android at nextcloud dot com?

**Comment by tobiasKaminsky** [comment]
No response within the last month, therefore closing.
Please feel free to reopen with additional infos, if the problem still exists.
