### ISSUE TITLE
Activity stream: clicking on image opens wrong one

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#1151]
### Steps to reproduce
1. open activity stream
2. click on one image 
3. see a different one

Same for other links (file link)

**Comment by OlivierS1** [comment]
I have noticed this behavior on Nextcloud Dev when clicking on a thumbnail when the actual picture has not been downloaded. The file name of the picture opened would be located on the Nextcloud app user folder.

**Comment by tobiasKaminsky** [comment]
PR merged -> closing

**Comment by mario** [comment]
Sorry, not on my Mac - what is the Pr?:)

**Comment by tobiasKaminsky** [comment]
#1153 
(if you are not on your mac, you could also answer later when you have proper access. No need for such a hurry.)
