### ISSUE TITLE
Remove "refresh account" from 3 dot menu cause it duplicates pull-to-refresh

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/android#1152]
Pull to refresh is pretty normal these days. It should be doing what the "Refresh account" entry does.

If it's too resource intensive, we could to a two-step pull-to-refresh:

- A normal pull refreshes as now
- A longer pull refreshes the complete account, of course with apt text feedback

**Comment by mario** [comment]
Pull to refresh is an abomination and should never exist on Android. It is a copy-paste from the iOS world, and is useless and absolutely not user-friendly. Also two step? That complicates stuff even further...

**Comment by tobiasKaminsky** [comment]
Isn't this a bit harsh? ;-) It is (at least now) a well know behaviour and officially recommend by https://developer.android.com/training/swipe/add-swipe-interface.html

Two steps are also too much I think.
"Refresh account" is mainly used to update "synced files" and we should enhance the periodic scan. Then we can move this into settings, if we really need to have this option manually.

Swipe to refresh will remain the same then.

**Comment by jancborchardt** [comment]
@tobiasKaminsky ok, that sounds good! :)

@mario systems and designs evolve. Pull to refresh originally comes from the Twitter app Tweetie (which happened to be on iOS). It wasn't a development by iOS, but tirned out a good design pattern which was then adopted across iOS. And then, since considerable time already, on Android. It's know by now.
And besides, pull-to-refresh is mostly for people who want to force-refresh. We already do automatic refresh when changing folders, and periodically, so oftentimes you don't need to do the pull anyway. :)

**Comment by joshtrichards** [comment]
Fixed in #6059 & #6173
