### ISSUE TITLE
Please release version 3.24.2 on GitHub/F-Droid

### ISSUE THREAD

**Issue by zickgraf** [nextcloud/android#11525]
Version 3.24.2 of Nextcloud for Android is available on [Google Play](https://play.google.com/store/apps/details?id=com.nextcloud.client) but this version currently does not exist on [GitHub ](https://github.com/nextcloud/android/releases) and hence, I assume, not on [F-Droid](https://f-droid.org/en/packages/com.nextcloud.client/). Version 3.24.1 crashes when using end-to-end encryption with Nextcloud 26. This seems to be fixed in version 3.24.2. Thus, releasing 3.24.2 on GitHub and F-Droid would be welcome.

**Comment by EVOTk** [comment]
Still not on F-Droid, I'm waiting for this version too

**Comment by zickgraf** [comment]
Version 3.25.0 is now available on F-Droid.
