### ISSUE TITLE
Deleting File on Cloud since no local file detected

### ISSUE THREAD

**Issue by timhorn1** [nextcloud/android#11574]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Add a lot of files (ca. 100) to an auto uploaded folder, so that Nextcloud syncs in the background
2. I opened a Keepass DB over the android storage access framework (Samsung file picker --> Tab Nextcloud on the Drawer)
4. I changed the Keepass DB and it gets saved automatically
5. I closed the Keepass App and saw that Nextcloud doesn't sync the Keepass DB because it syncs my other hundreds files already
6. After some hours of syncing Nextcloud doesn't find my modified Keepass DB anymore but still syncs a version of the DB with no file content which results in a **zero bytes Keepass DB** on the cloud

### Expected behaviour

1. Either files modified over the storage access framework should snync before others (or in between when syncing)
2. Or Files should be kept local available with the storage access framework and be accessible to the nextcloud client after some hours (regardless of standby, locked screen of the device if that matters)

### Actual behaviour

- Nextcloud App can't find a local version of my Keepass DB as shown in Uploads Tab in the App
- Nevertheless, the App uploads a version of my DB obviously with no file content
- I see a zero bytes file on the cloud which I can't open because the file format was not being recognised of any App

### Android version

13

### Device brand and model

Galaxy Tab S7

### Stock or custom OS?

Stock

### Nextcloud android app version

3.24.1

### Nextcloud server version

19.0.4.2

### Using a reverse proxy?

Yes

### Android logs

The log file does not exist at the mentioned directory or is not accessible without root

### Additional information

This might be a critical issue for newcomers trying out Keepass with Nextcloud.

**Comment by joshtrichards** [comment]
Hi @timhorn1 - There's a chance this is fixed in >=v3.26 via #11286. Can you re-test in your environment and confirm? Thanks
