### ISSUE TITLE
WebView for "Sync calendar & contacts" not sandboxed - Logged in as Wrong User

### ISSUE THREAD

**Issue by stellarpower** [nextcloud/android#11597]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

I am signed into multiple accounts on the same instance in my Android app. I am trying to set up tasks syncing using Davx5.

I switch account to the one I want to set up next, and go to settings -> Sync calendar & contacts.

The OAuth-style flow comes up in an in-app browser window on my device, prompting me to grant access to this account (presume it is generating app password in the backend).

### Expected behaviour

Login-type flows available in the app should be sandboxed for the account currently being shown in the main window when they are performed. Or alternatively, cookies etc. should not persist in these browser views once the flow is complete. The behaviour would suggest that if I had logged in as a user not known to the android app in my web browser, the flow would then be granting access for that user, instead of the one in the app when I clicked the button to start the process.

### Actual behaviour

The problem I believe I am seeing is that Android now persists these temporary in-app webpage popups (`WebView`s?) using the web browser in the backend - so that sessions persist for user convenience insigning in. So it seems that any session cookies are stored when I complete this process - if I grant access to Davx5 as one user, when I come to complete the process as a different user, I am still logged in as the previous one, and it proceeds to try to create a second Davx5 account for the same user. If I open Chrome and go to my instance's homepage, I am logged in as the user I last set up sync for. So to set up sync for my accounts, I now need to open my browser and log out of this account in order to clear the session, before then going through the flow for syncing calendars again.

### Android version

EMUI 12.0.0 (not sure where to find underlying Android version)

### Device brand and model

Huawei Mate 20 Pro

### Stock or custom OS?

Stock

### Nextcloud android app version

3.24.2

### Nextcloud server version

22.1.1

### Using a reverse proxy?

Yes

**Comment by joshtrichards** [comment]
That browser session is from DAVx⁵:

https://github.com/bitfireAT/davx5-ose/blob/166b2ac220f1b63c0e5b492eec6e14c762a56e27/app/src/main/kotlin/at/bitfire/davdroid/ui/setup/NextcloudLogin.kt#L87-L112

Though this is someone related to nextcloud/server#34436
