### ISSUE TITLE
InstantUpload for Videos is wrong

### ISSUE THREAD

**Issue by athendrix** [nextcloud/android#1159]
### Actual behaviour
-Tell us what happens
Video gets uploaded into parent folder with name of folder prepended onto file.
e.g. /Videos/InstantUploadVIDEO1234.mp4
### Expected behaviour
-Tell us what should happen
 Should instead go in the folder.
e.g. /Videos/InstantUpload/VIDEO1234.mp4
### Steps to reproduce
1. Setup Instant Upload for pictures and Videos to separate folders
2. Take a video.

### Environment data
Android version:
5.0.2
Device model: 
HTC One
Stock or customized system:
Stock
Nextcloud app version:
1.4.3
Nextcloud server version:
12.0.0

No error logs. It works, it just has the wrong path.

**Comment by mario** [comment]
Instant upload won't be there in 1.5, and this is fixed in Auto Upload.
