### ISSUE TITLE
Texteditor copys file content from previous file to current file

### ISSUE THREAD

**Issue by JohannesGGE** [nextcloud/android#11600]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Open textfile (.md) with content (A)
2. Leave the editor with back navigation of Android
3. Open another textfile (.md) (B)

### Expected behaviour

Editor shows the content of (B)

### Actual behaviour

Editor shows the content of B + the content of A at the end or start of the file. (If there is screenfilling content you don't even notice there is the content from A at the start)

On save/exit with X the file is saved with the added content from A. Sometimes A is written as well with A+B.

### Android version

13

### Device brand and model

Pixel 2

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

3.24.2

### Nextcloud server version

master, 26.0.0

### Using a reverse proxy?

I don't know

### Additional information

Custom OS: Lineage 20 microG

Testet on another android as well.

**Comment by siccovansas** [comment]
I have noticed this as well. This bug leads to very confusing situations and might require people to restore backups of files.
