### ISSUE TITLE
Files auto uploaded to two nextcloud instances, even though autoupload disabled on one.

### ISSUE THREAD

**Issue by bbceg** [nextcloud/android#11610]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Set up two nextcloud instances.
2. In android, configure auto-upload (with use subfolders checked) for one or more folders in one instance.
3. Ensure no folders are configured for auto-upload for the other instance
4. Wait for a sync to occur according to the auto-upload settings
5. Verify that files are created in both clouds

### Expected behaviour

Files (photos in my case) should only be uploaded to the instance configured in the app.

### Actual behaviour

Files are created in both instances though the behaviour is not entirely consistent (the number of files vary between instances). Perhaps even more concerning is that in some cases files end up in the incorrect instance and not the intended instance.

### Android version

13

### Device brand and model

Pixel 5

### Stock or custom OS?

Stock

### Nextcloud android app version

3.24.2

### Nextcloud server version

25.0.6 and 25.0.4

### Using a reverse proxy?

No

**Comment by joshtrichards** [comment]
Let's consolidate this into #11088.
Feel free to subscribe there to track progress.

**Comment by bbceg** [comment]
Makes sense @joshtrichards , sorry I didn't spot the other issue when I posted mine.
