### ISSUE TITLE
Backup contacts screen keeps crashing the app

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#1161]
Reported by @AndyScherzinger on https://github.com/nextcloud/android/pull/1031#issuecomment-312295253
can you give us here some more details?

**Comment by AndyScherzinger** [comment]
I'll check when I get the chance, might be a db issue with the different branches, need to check it with the emulator... Might be a false alarm.

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger if you experience this again, please reopen
