### ISSUE TITLE
Can't login - unspected error

### ISSUE THREAD

**Issue by ArchGalileu** [nextcloud/android#1162]
### Actual behaviour
-Tell us what happens
I can't login on the app with my own server.
It recognizes the security address from the server, it reacts to bad login information, but with correct info says "unexpected error unknown"

### Expected behaviour
-Tell us what should happen
Login as usual
 
### Steps to reproduce
1. Nextcloud 12.0
2. Android App 1.4.3 or DEV
3. 

### Environment data
Android version: 7.1.2

Device model: OnePlus 3T

Stock or customized system: Rom Ressurection

Nextcloud app version: 1.4.3

Nextcloud server version: 12.0

#### Nextcloud log (data/nextcloud.log)
xxxxxx - - [04/Jul/2017:12:30:27 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 357
xxxxxx - - [04/Jul/2017:12:30:36 +0100] "GET /status.php HTTP/1.1" 200 151
xxxxxx - - [04/Jul/2017:12:30:37 +0100] "HEAD /remote.php/webdav/ HTTP/1.1" 401 -
xxxxxx - - [04/Jul/2017:12:30:39 +0100] "HEAD /remote.php/webdav/ HTTP/1.1" 200 -
xxxxxx - - [04/Jul/2017:12:30:40 +0100] "GET /ocs/v1.php/cloud/user?format=json HTTP/1.1" 200 242

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Can you create us a test account and send it to nextcloud at android dot com with a reference to this issue?

**Comment by tobiasKaminsky** [comment]
@ArchGalileu friendly reminder :-)

**Comment by ArchGalileu** [comment]
Sorry for delay @tobiasKaminsky

I had bad config on server, apache, changed for nginx, as i prefer, checked all config and perfect.

Ps. i sended email, as you asked, but it retorned as unknown email...

Best regards
ArchGalileu

**Comment by tobiasKaminsky** [comment]
Glad to hear.
