### ISSUE TITLE
Plain WebDAV protocol support

### ISSUE THREAD

**Issue by stokito** [nextcloud/android#11639]
I used NextCloud for some time but since I using it on a router I decided to switch to a plain WebDAV server (Lighttpd mod_webdav).

Now I wish to sync my files from my Android phone but the only working open source app that I found is https://github.com/newhinton/extRact/ 
It's not published yet to Google Play or FDroid internally it contains compiled rclone in Golang but also it's a sync only app. And I don't need many clouds support but need for something more lightweight.

And here I got the idea: maybe it will be possible to use NextCloud app to synchronize files?
It should be just a little change for the app but will make a big impact for users freedom.
From what I saw in API docs the NC uses own OAuth like authorization, some additional props like thumbnails and some custom chunked uploads.
Maybe it's even possible to use the NC isself with a plain backend WebDAV? E.g. instead of the remote.php use the mod_webdav. This will make file operations faster while keeping the UI of NC which is great.

Many other services are also WebDAV based e.g. Kofr, Onedrive, Yandex etc. So having the option will help users to migrate to NC and from it.

**Comment by joshtrichards** [comment]
Hi @stokito - I'm afraid this is outside the scope of the Android app. You're of course welcome to give it a shot, but it's unlikely to work as-is.
