### ISSUE TITLE
Group Folder is not displayed

### ISSUE THREAD

**Issue by omnath0** [nextcloud/android#11664]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Open the Nextcloud Android App
2. Tap on the Groupfolders tab
3. No Group folders are displayed
4. Swipe the screen to update
5. It goes into an infinite unlock loop

### Expected behaviour

We should see the group folders.

### Actual behaviour

Group folders are not displayed.

### Android version

13

### Device brand and model

S22

### Stock or custom OS?

Stock

### Nextcloud android app version

3.25..0.1 RC1

### Nextcloud server version

 26.0.2.1

### Using a reverse proxy?

I don't know

**Comment by tobiasKaminsky** [comment]
On NC26 there should not be any groupfolder entry shown.
This is a feature which is only available on NC27.
