### ISSUE TITLE
Auto upload is running while in wifi hospot (AP) mode

### ISSUE THREAD

**Issue by jsb1** [nextcloud/android#1166]
### Actual behaviour
The client was configured to upload only over wifi.
I was running my phone in hotspot mode, using it's 4g internet connection on my laptop. After  some minutes I noticed, that Nextcloud was uploading all my photos and videos.

### Expected behaviour
In hotspot mode the phones internet connection is 4g! Nextcloud should not assume that  wifi is connected.

 
### Steps to reproduce
1. Put some images into upload folder. I'm syncing my camera.
2. Restart phone. Not shure if this is neccesary, but I must do that sometimes to activate syncing (another bug?).
3. Activate wifi hotspot mode. Maybe connect a wifi client.

### Environment data
Android version:
6.0.1
Device model: 
Motorola X-Force
Stock or customized system:
stock
Nextcloud app version:
not sure- the one which was on play store at 2017-06-15
Nextcloud server version:
12.0.0
### Logs
No logs for now. If You cannot reproduce I'll try to catch some.

**Comment by mario** [comment]
Dear users,

thank you for your patience. After lots of work, we’re super excited to be able to give you a test version with new auto upload implementation. Keep in mind we will only accept bugs related to Auto Upload in this APK, as other things might be broken.

https://cloud.nextcloud.com/s/ftZraTruRQjTe0R

This is a dev APK so it will not overwrite your existing play store/f-droid APK unless you’re already running dev version. Also, you might need to remove your existing dev version before installing this one.

Explanation of the current functionality:
- added support for custom folders
- separated image and video folders
- checks for new files happens every 15-20 minutes
- automatic retry every 15-20 minutes or when you force close/open the app
- automatic pause once network is changed (untested!)
- significantly less battery usage

All and any testing is more than appreciated, especially with large and ever-going files like Videos. (like, try to record a 30 min video).

Let me know if you’ve got any questions.

Cheers,
Mario

**Comment by jsb1** [comment]
Oh I'm really sorry, I totally forgot that issue. Did anyone test?
