### ISSUE TITLE
Auto-upload settings deleted after app update

### ISSUE THREAD

**Issue by Niemand112233** [nextcloud/android#11670]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Try to Autoupload something.

Autoupload config was automatically deleted.

### Expected behaviour

Autoupload working

### Actual behaviour

Autoupload doesn't work.

### Android version

10

### Device brand and model

Sony Xperia XZ2C

### Stock or custom OS?

Stock

### Nextcloud android app version

3.25.0 RC1

### Nextcloud server version

26.0.1

### Using a reverse proxy?

Yes

**Comment by pieter-groeneweg** [comment]
Same here but Samsung S10
app version 3.25.0 RC1
server 26.0.1

Auto Upload settings where disabled when I checked. Re-enabling does not resolve anything.

noticed also that on starting Nextcloud App is all defaulted to the standard blue background color while usually it reflects the green of my NextCloud Template preference. It returned the green only after I switched to another account in the app and back.

**Comment by ikwtif** [comment]
Just wanted to add that I had the same issue, just noticed it today. I thought it was an issue with my server at first. 
So is there really no other way to add the missing pictures to completely remove the app and set up the uploads again and make it upload every single file again? I did this a while back because there was also an issue with the upload. There has to be a better way of doing this right?

**Comment by joshtrichards** [comment]
@Niemand112233 Any idea which version of the app you updated from? And what method did you use to install the RC edition?

**Comment by joshtrichards** [comment]
Closing since no response received after nearly a year.
Also since this was `3.25.0 RC1` it was probably fixed. (Most likely candidate: #11659)
