### ISSUE TITLE
delayed removal of auto-uploaded files after certain time #enhancement

### ISSUE THREAD

**Issue by Tormen** [nextcloud/android#1167]
### Actual behaviour
- Images should get automatically uploaded (they are not im my case, but that's a different story ;))
- There is only an option to remove the images right after successful upload

### Expected behaviour
- Allow specifying a duration for wich successfully auto-uploaded files (images/videos) are kept, before they will get automatically removed. The idea is to provide a "delayed removal" option instead of the existing "instantly remove after successful upload" option.
- The delay should be customizable (probably best in days (and/or maybe hours for some folks)).
- If set to 0, this means instant removal (like the current setting allows)
- So you once setup this delay, which will then applied to all newly auto-uploaded files. With this option set, this will allow to automatically remove and cleanup all successfully auto-uploaded files after a certain time-span
(eg like count-down for each uploaded file (or batch of files) and once the count-down expires (counted down to 0), the file(s) get automatically (and silently) removed from the smartphones storage space.

### Why?
* Cleanup, regain disk-space.
* At the same time allow to still /use/ recent photos eg. by sharing them without having to re-download them from the nextcloud server :/
* Also privacy to some extend: Because like this I can assure that someone grabbing my phone only gets direct access to x days of personal photos.

### Environment data
Nextcloud app version: v.1.4.3

### Related issues
See also #1146 which also has the goal of cleanup of storage-space, but with a not time-based approach and rather on-demand and/or storage space related triggers.

**Comment by tobiasKaminsky** [comment]
> At the same time allow to still /use/ recent photos eg. by sharing them without having to re-download them from the nextcloud server :/

This will be possible with #69

**Comment by Tormen** [comment]
Hi :) ... but there it was written "Clicking on an image loads a reduced version to the cache.".

I guess I was not clear. Because I have in min something automatic: "Set up once and then forget."
So you once tell Nextcloud: Please keep any new, succesfully auto-uploaded photo for 1 week before automatically removing it.

To make this more clear I renamed the issue and rephrased my description.

**Comment by mario** [comment]
Very very unlikely to happen so closing. Sorry :(
