### ISSUE TITLE
Autoupload first worked when activating the option, but not since

### ISSUE THREAD

**Issue by Tormen** [nextcloud/android#1168]
### Actual behaviour
- When I freshly installed app, I activated Auto-upload. And took a few photos, and they got auto-uploaded. But no photo I took ever since. Hard to say why not. There is no error message of any kind.
Can I maybe grab logs with adb ? or do you have a debug-logging-enabled app version somewhere?

### Expected behaviour
- New photos taken should get auto-uploaded.
 
### Steps to reproduce
1. Install app
2. Turn on auto-uploaded
3. Wait and take new photos

### Environment data
Android version: 7.0

Device model: Huawei Mate 8

Stock or customized system: Stock system.
But this is not Android vanilla, as Huawei always ships with some slight modifications packaged as EMUI (v5.0), but they are far less intrusive than Samsung for instance.

Nextcloud app version: Android v1.4.3

Nextcloud server version: v12.0.0 stable in a CentOS Linux release 7.3.1611 (Core) 

#### Web server error log
--
#### Nextcloud log (data/nextcloud.log)
--

**Comment by Tormen** [comment]
This is most likely a Huawei specific problem. There EMUI has a quite agressive auto-cleanup, close, policy to limit background tasks.
On the upside, if you'll manage to get auto-upload work here, it should probably be working on /all/ other android 7 ;)

They have a mechanism to avoid cloising backround apps after your screen is locked. There I did whitelist Nextcloud! But it is still not working :/

That's why I asked for some sort of logging to know if the background service of NextCloud is running or gets killed...

**Comment by siwyroot** [comment]
Hello,

Problem is auto-upload also observed on Xaiomi MI5 with Android 7.0 (MIUI 8.2). Netxcould android app 1.4.2, server 10.0.4

**Comment by nebulade** [comment]
I can second this on the Mi-4c with MIUI 8. Same behavior, uploaded once after setup and then stopped working, however this is only the case for pictures, videos are still uploaded.

**Comment by JGjorgji** [comment]
I can confirm this happens to me as well, Huawei P9 Lite with Android 7/EMUI 5.
App version: 1.4.3

Power saving is disabled for the nextcloud app but it still happens, other apps that require turning off power saving seem to be running fine.

**Comment by mario** [comment]
Dear users,

thank you for your patience. After lots of work, we’re super excited to be able to give you a test version with new auto upload implementation. Keep in mind we will only accept bugs related to Auto Upload in this APK, as other things might be broken.

https://cloud.nextcloud.com/s/ftZraTruRQjTe0R

This is a dev APK so it will not overwrite your existing play store/f-droid APK unless you’re already running dev version. Also, you might need to remove your existing dev version before installing this one.

Explanation of the current functionality:
- added support for custom folders
- separated image and video folders
- checks for new files happens every 15-20 minutes
- automatic retry every 15-20 minutes or when you force close/open the app
- automatic pause once network is changed (untested!)
- significantly less battery usage

All and any testing is more than appreciated, especially with large and ever-going files like Videos. (like, try to record a 30 min video).

Let me know if you’ve got any questions.

Cheers,
Mario

**Comment by siwyroot** [comment]
Hello, initial testing confirm that auto-upload is working, but I do not see any notification when it's uploading, re-uploading same file creates duplicate (do not know if this is expected, I would rather see info that file already exists) and miniatures are not showing (probably tickets exists or it's not relevant for dev app). I will test large video files this week with network change.

Thanks and keep up the good work :)

**Comment by mario** [comment]
"re-uploading same file creates duplicate" - can you clarify this? Current implementation cannot create duplicates at all, so this sounds strange.

Also notifications should be there...

**Comment by siwyroot** [comment]
Hello,

I'm probably not patient enough for notifications. When I select file by
hand that is already uploaded, it's created again with (2) in name.

**Comment by mario** [comment]
OK, that is a whole different issue not related to auto upload.

**Comment by siwyroot** [comment]
Hello,

After quite a lot of testing I have observed following problems:

1. Upload is working randomly, sometimes it takes up to few hours to finally upload. No contains on battery usage for application in background and it can upload via mobile data and wifi.
2. Almost every time I open app it hangs on refreshing unless I switch to somewhere else via menu on the left (like all files or upload history)
3. Miniatures of photos do not work at all.

Thanks ! Keep up good work :)
