### ISSUE TITLE
Alert dialog box title not changing

### ISSUE THREAD

**Issue by gangulwar** [nextcloud/android#11691]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Open settings
2. Click on Data storage folder

### Expected behaviour

The title should be "Choose storage location" as per

https://github.com/nextcloud/android/blob/c3e4f394ab70779e7e80a0b3137f09abea6d3303/app/src/main/java/com/owncloud/android/ui/dialog/LocalStoragePathPickerDialogFragment.java#L115

### Actual behaviour

![image](https://github.com/nextcloud/android/assets/123754972/6cbf3986-81ce-4ae2-9775-ff0f5ebce5d9)

### Android version

13

### Device brand and model

Pixel 6 Pro 

### Stock or custom OS?

Stock

### Nextcloud android app version

3.26.0

### Nextcloud server version

-

### Using a reverse proxy?

No

**Comment by parneet-guraya** [comment]
Hi, I'm thinking to look into it. I have already set up android studio. I just want to setup the android app, is there any demo link of server which i can use to reproduce the issue? Unfortunately, i'm not able to find any. Can anyone help me with this?

**Comment by gangulwar** [comment]
just clone the repository and open it in android studio

**Comment by parneet-guraya** [comment]
Yes I have done that and the debug version is installed. I want to login into the app so that I can reproduce the error.
Someone suggested that I set up a dev server locally.I wonder how I'm gonna have the app running.

Thanks!

**Comment by Chandan510** [comment]
> Yes I have done that and the debug version is installed. I want to login into the app so that I can reproduce the error. Someone suggested that I set up a dev server locally.I wonder how I'm gonna have the app running.
> 
> Thanks!

I'm also looking for login credentials to do a contribution to this issue. But not get it.

**Comment by AndyScherzinger** [comment]
You would need to setup your own server _or_ you create a free account at a provider offering this, see https://nextcloud.com/sign-up/

**Comment by joshtrichards** [comment]
The referenced code is for the dialog box that pops up when using *Add* (the `+` icon in the lower right) then selecting *Upload Files* and attempting to browse to a different storage volume. The one if your screenshot matches the code and strings the link to here:

https://github.com/nextcloud/android/blob/d88e3748d8e99b8afe680a8406854aec65b908d3/app/src/main/res/xml/preferences.xml#L27
