### ISSUE TITLE
Feature request: Logs in stable

### ISSUE THREAD

**Issue by jasonbayton** [nextcloud/android#1170]
Currently the stable version (1.4.3) of the NC app omits the logs menu item, making self-troubleshooting unnecessarily more difficult than it needs to be. 

Indeed, a large user-base consists of the _user_ stereotype, and those may never need or use it, however a significant portion of us are technical and benefit from seeing under the hood when things go wrong, or requesting it from users in remote support situations.

Therefore, please make logs a permanent menu entry in settings 👍

**Comment by tobiasKaminsky** [comment]
Fine by me, @mario, @AndyScherzinger, @jancborchardt?
(I remember somehow that we already discussed this and said that log should only be available on dev and public beta, but I do not mind having it also enabled on stable)

**Comment by jasonbayton** [comment]
If I was part of that earlier conversation then I have since changed my mind through real-world use 👍 :)

**Comment by mario** [comment]
I will implement this differently. There will be an "expert" mode that is entered by tapping version number three times.

**Comment by AndyScherzinger** [comment]
fine by me, also agreeing with @mario on the "expert mode" while even then it should be a SwitchPreference so the expert can also deactivate the logging.

**Comment by mario** [comment]
@AndyScherzinger they can via the same method. Three times tap the version number.

**Comment by jasonbayton** [comment]
Ooooh I like easter-eggs. 👍 From me!

**Comment by jancborchardt** [comment]
Sounds good! :) What other things will change in expert mode? (It shouldn't be a lot.)

**Comment by mario** [comment]
@jancborchardt for now not much. Added manual upload controls to expert mode. This is now implemented via auto upload branch.
