### ISSUE TITLE
Crash wenn opening a folder 

### ISSUE THREAD

**Issue by RolfHessling** [nextcloud/android#11705]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Open a folder

### Expected behaviour

directory should be listed

### Actual behaviour

Crash dump

### Android version

13

### Device brand and model

Pixel 6 Pro

### Stock or custom OS?

Stock

### Nextcloud android app version

3.24.2

### Nextcloud server version

26.02

### Using a reverse proxy?

I don't know

**Comment by joshtrichards** [comment]
Hi @RolfHessling - Thanks for the report, but you didn't provide much to go on. Can you provide the crash output next time this happens? Also, we don't have a v3.24.2 version that I see... in any case there's a newer version available now as well. :)
