### ISSUE TITLE
SecurityException when searching for sharee

### ISSUE THREAD

**Issue by ZetaTom** [nextcloud/android#11712]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. set up nextcloud app with account
2. tap on share icon of any file
3. select *Share*
4. in *Sharing* fragment open search bar (*Name, Federated Cloud ID or email address*)
5. enter first character of any available username

### Expected behaviour

Available users whose username matches the given prompt are displayed.

### Actual behaviour

`java.lang.SecurityException:...` sometimes appears instead of username or in addition to.

matches *a*dmin and *a*lice | matches only *b*ob
--- | ---
![a](https://github.com/nextcloud/android/assets/70907959/8c7476aa-d27b-496f-8da1-3db164bff01f) | ![b](https://github.com/nextcloud/android/assets/70907959/9dae0100-78ba-44ee-8061-2daa46b6c425)

*admin* is the currently active user.

### Android version

9.0

### Device brand and model

Google Pixel 2 API 28 Emulator

### Stock or custom OS?

Stock

### Nextcloud android app version

7273c29

### Nextcloud server version

26.0.1

### Using a reverse proxy?

No

**Comment by joshtrichards** [comment]
Seeing same behavior in recent Dev builds. Hopefully not in v3.27.0 (haven't checked yet)
