### ISSUE TITLE
[Share] enter password: toggle visibility of password

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#1171]
- share a file as link
- enter password
- allow changing visibility of password 

Ref: https://medium.com/@moyinoluwa/password-visibility-toggle-android-support-library-revision-24-2-0-98b422087e5a

**Comment by AndyScherzinger** [comment]
For any hints, please see the password edit text of the login activity :)

**Comment by OlivierS1** [comment]
@tobiasKaminsky @AndyScherzinger I find entering the password for sharing a link a bit cumbersome and relatively unsecure. I have tried this feature in NC Dev 20170721 and when password doesn't meet requirement it has to be entered again.
Under NC 12, the server is able to generate a password automatically and the password is sent via email while the link to the share is sent on another email.
Can't we have this feature implemented based on server password requirements, best if password had same level of resiliency as app password.

**Comment by tobiasKaminsky** [comment]
Please open a new issue for this. Mixing different things into one issue/discussion is quite confusing.

**Comment by AndyScherzinger** [comment]
password visibility toggle has been merged for 1.5.0
