### ISSUE TITLE
Download of pdf fails when parent folder contains ':'

### ISSUE THREAD

**Issue by chris9734** [nextcloud/android#11720]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Create a folder with a ':' included in the name, like "Method Course: Ma"
2. Upload/Move a pdf in this folder
3.  Try to open/download that pdf in the Nextcloud app

### Expected behaviour

The pdf should be downloaded or opened by an external app

### Actual behaviour

Nothing happens and Nextcloud creates an Error Notification
"Download failed"

### Android version

13

### Device brand and model

Samsung S10 5G

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

3.24.1

### Nextcloud server version

27.0.0 RC3

### Using a reverse proxy?

No

### Android logs

06-10 14:02:07.312  8243 13122 E MediaProvider: File name contains invalid characters
06-10 14:02:07.313 22606 22773 E DownloadFileRemoteOperation: Error creating file /storage/emulated/0/Android/media/com.nextcloud.android.beta/nextcloud/tmp/chris9734@cloud.myDomain.com/Method Course: Ma/Antrag.pdf
06-10 14:02:07.313 22606 22773 E DownloadFileRemoteOperation: java.io.IOException: Operation not permitted
06-10 14:02:07.313 22606 22773 E DownloadFileRemoteOperation: 	at java.io.UnixFileSystem.createFileExclusively0(Native Method)
06-10 14:02:07.313 22606 22773 E DownloadFileRemoteOperation: 	at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:317)
06-10 14:02:07.313 22606 22773 E DownloadFileRemoteOperation: 	at java.io.File.createNewFile(File.java:1006)
06-10 14:02:07.313 22606 22773 E DownloadFileRemoteOperation: 	at com.owncloud.android.lib.resources.files.DownloadFileRemoteOperation.downloadFile(DownloadFileRemoteOperation.java:114)
06-10 14:02:07.313 22606 22773 E DownloadFileRemoteOperation: 	at com.owncloud.android.lib.resources.files.DownloadFileRemoteOperation.run(DownloadFileRemoteOperation.java:88)
06-10 14:02:07.313 22606 22773 E DownloadFileRemoteOperation: 	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:205)
06-10 14:02:07.313 22606 22773 E DownloadFileRemoteOperation: 	at com.owncloud.android.operations.DownloadFileOperation.run(DownloadFileOperation.java:180)
06-10 14:02:07.313 22606 22773 E DownloadFileRemoteOperation: 	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:205)
06-10 14:02:07.313 22606 22773 E DownloadFileRemoteOperation: 	at com.owncloud.android.files.services.FileDownloader.downloadFile(FileDownloader.java:474)
06-10 14:02:07.313 22606 22773 E DownloadFileRemoteOperation: 	at com.owncloud.android.files.services.FileDownloader.access$400(FileDownloader.java:88)
06-10 14:02:07.313 22606 22773 E DownloadFileRemoteOperation: 	at com.owncloud.android.files.services.FileDownloader$ServiceHandler.handleMessage(FileDownloader.java:424)
06-10 14:02:07.313 22606 22773 E DownloadFileRemoteOperation: 	at android.os.Handler.dispatchMessage(Handler.java:106)
06-10 14:02:07.313 22606 22773 E DownloadFileRemoteOperation: 	at android.os.Looper.loopOnce(Looper.java:201)
06-10 14:02:07.313 22606 22773 E DownloadFileRemoteOperation: 	at android.os.Looper.loop(Looper.java:288)
06-10 14:02:07.313 22606 22773 E DownloadFileRemoteOperation: 	at android.os.HandlerThread.run(HandlerThread.java:67)
06-10 14:02:07.317 22606 22773 E DownloadFileRemoteOperation: Download of /Method Course: Ma/Antrag.pdf to /storage/emulated/0/Android/media/com.nextcloud.android.beta/nextcloud/tmp/chris9734@cloud.myDomain.com/Method Course: Ma/Antrag.pdf: Unexpected exception
06-10 14:02:07.317 22606 22773 E DownloadFileRemoteOperation: com.owncloud.android.lib.resources.files.CreateLocalFileException: File could not be created
06-10 14:02:07.317 22606 22773 E DownloadFileRemoteOperation: 	at com.owncloud.android.lib.resources.files.DownloadFileRemoteOperation.downloadFile(DownloadFileRemoteOperation.java:117)
06-10 14:02:07.317 22606 22773 E DownloadFileRemoteOperation: 	at com.owncloud.android.lib.resources.files.DownloadFileRemoteOperation.run(DownloadFileRemoteOperation.java:88)
06-10 14:02:07.317 22606 22773 E DownloadFileRemoteOperation: 	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:205)
06-10 14:02:07.317 22606 22773 E DownloadFileRemoteOperation: 	at com.owncloud.android.operations.DownloadFileOperation.run(DownloadFileOperation.java:180)
06-10 14:02:07.317 22606 22773 E DownloadFileRemoteOperation: 	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:205)
06-10 14:02:07.317 22606 22773 E DownloadFileRemoteOperation: 	at com.owncloud.android.files.services.FileDownloader.downloadFile(FileDownloader.java:474)
06-10 14:02:07.317 22606 22773 E DownloadFileRemoteOperation: 	at com.owncloud.android.files.services.FileDownloader.access$400(FileDownloader.java:88)
06-10 14:02:07.317 22606 22773 E DownloadFileRemoteOperation: 	at com.owncloud.android.files.services.FileDownloader$ServiceHandler.handleMessage(FileDownloader.java:424)
06-10 14:02:07.317 22606 22773 E DownloadFileRemoteOperation: 	at android.os.Handler.dispatchMessage(Handler.java:106)
06-10 14:02:07.317 22606 22773 E DownloadFileRemoteOperation: 	at android.os.Looper.loopOnce(Looper.java:201)
06-10 14:02:07.317 22606 22773 E DownloadFileRemoteOperation: 	at android.os.Looper.loop(Looper.java:288)
06-10 14:02:07.317 22606 22773 E DownloadFileRemoteOperation: 	at android.os.HandlerThread.run(HandlerThread.java:67)
06-10 14:02:07.317 22606 22773 E DownloadFileRemoteOperation: Caused by: java.io.IOException: Operation not permitted
06-10 14:02:07.317 22606 22773 E DownloadFileRemoteOperation: 	at java.io.UnixFileSystem.createFileExclusively0(Native Method)
06-10 14:02:07.317 22606 22773 E DownloadFileRemoteOperation: 	at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:317)
06-10 14:02:07.317 22606 22773 E DownloadFileRemoteOperation: 	at java.io.File.createNewFile(File.java:1006)
06-10 14:02:07.317 22606 22773 E DownloadFileRemoteOperation: 	at com.owncloud.android.lib.resources.files.DownloadFileRemoteOperation.downloadFile(DownloadFileRemoteOperation.java:114)
06-10 14:02:07.317 22606 22773 E DownloadFileRemoteOperation: 	... 11 more
06-10 14:02:07.318 22606 22773 I DownloadFileOperation: Download of /Method Course: Ma/Antrag.pdf to /storage/emulated/0/Android/media/com.nextcloud.android.beta/nextcloud/chris9734@cloud.myDomain.com/Method Course: Ma/Antrag.pdf: Unexpected exception

### Additional information

Using the official LineageOS 20 build

**Comment by joshtrichards** [comment]
See #11241
