### ISSUE TITLE
Support right-to-left

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#1172]
Currently it seems that we do not support right-to-left at all:
![2017-07-11-114353](https://user-images.githubusercontent.com/5836855/28062460-4d05d514-662e-11e7-918f-9e02655b91d5.png) ![2017-07-11-114336](https://user-images.githubusercontent.com/5836855/28062461-4d07b9f6-662e-11e7-8908-b7a08ee6c5d1.png)

https://android-developers.googleblog.com/2013/03/native-rtl-support-in-android-42.html

**Comment by AndyScherzinger** [comment]
Nope we don't, I also have this on my list to implement but always postponed it until we go for min version 4.2 so we don't need to duplicate layout infos.

**Comment by tobiasKaminsky** [comment]
I think this is done by the latest PRs by me. I am not sure how well translated our app is in these RTL languages and how many users we have there.
If bugs are reported, we can fix them anyway.
