### ISSUE TITLE
Support Android 13 / API 33

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#11739]
To be ahead of time, let us aim to support Android 14 as early as possible.

ETA: August

**Comment by tobiasKaminsky** [comment]
First go to Android 13, as this is more urgent.

**Comment by tobiasKaminsky** [comment]
- bump targetSDK
- check migration steps 
- smoke test to see if everything still works
- test upgrade, test new installation

**Comment by ZetaTom** [comment]
## Overview
- [x] raise `targetSdkVersion`
- [ ] test *Battery Resource Utilization*
    - [ ] check if auto-upload still works
- [ ] request `POST_NOTIFICATION` permission
- [x] check intent-filters for exported activities
- [x] check whether deprecated `android:sharedUserId` is used
- [x] review and test for uses of restricted non-SDK interfaces
- [ ] adopt *Granular Media Permissions*

## Media Permissions
- `READ_MEDIA_IMAGES`, `READ_MEDIA_VIDEO`, `READ_MEDIA_AUDIO` replace `READ_EXTERNAL_STORAGE`
- use of new permissions is mandatory
- recommended to utilise [Photo Picker](https://developer.android.com/training/data-storage/shared/photopicker#java) when selecting general media (images/videos)
