### ISSUE TITLE
The server version is no longer supported, please update it.

### ISSUE THREAD

**Issue by IngoBelka** [nextcloud/android#11748]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. start nextcloud app
2. see notification:"The server version is no longer supported, please update it." - translated from German language

### Expected behaviour

No notification because the server is 24.0.11.

### Actual behaviour

False notification.

### Android version

9.1.0.360 / 11 RKQ1.200826.002

### Device brand and model

Huawei MeyiaPad M5 / Xiaomi Mi 9T

### Stock or custom OS?

Stock

### Nextcloud android app version

3.25

### Nextcloud server version

24.0.11

### Using a reverse proxy?

No

**Comment by AndyScherzinger** [comment]
See https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule

V24 is end of life for community, so the behavior is expected and correct.

**Comment by tobiasdroessler** [comment]
I have the same issue.. 
So what this messages means?

It's just a notification to tell users the server is _old_ 
**OR** 
Are there main features which will not work with that server.
