### ISSUE TITLE
Auto Upload does not start automatically on 3.25.0

### ISSUE THREAD

**Issue by BLu85** [nextcloud/android#11741]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Upload only when phone is charging
Upload only with WI-Fi

The autoupload does not automatically start. This is the main feature of this app and it has been broken since January.
Please, can we have this feature fixed? There are other reports related to this same issue but all seem to be ignored.

Many thanks,
Luca

### Expected behaviour

Autoupload should start automatically, as this is the main purpose of this App!

### Actual behaviour

Autoupload does not start automatically.

### Android version

7.0.0

### Device brand and model

Huawey Nova

### Stock or custom OS?

Stock

### Nextcloud android app version

3.25.0

### Nextcloud server version

26.0.0

### Using a reverse proxy?

No

**Comment by BLu85** [comment]
Probably related to #11485

**Comment by rarealphacat** [comment]
probably not related cause mine working fine before 3.25.0. 
@BLu85 , yours not working at all since Janurary?

**Comment by BLu85** [comment]
Yes, exactly, since January.
I have different phones. App dpesn't work on 2 of them. It has always worked on the third one.
On my phone, I reinstalled the new version, set the autoupload and put the phone on a charger for the entire night (9h) but nothing has been uploaded.
Any ideas or suggestions?

**Comment by BLu85** [comment]
Update:

The AutoUpload works if I create a new folder and synchronise some pictures.
It does not work on a pre-existing folder with 6k+ pictures on the server and the same and some more on the phone.
The same happens with the Video folder.

On top of this, the battery was drained by the App Nextcloud.

**Comment by gthau** [comment]
I'm also affected by this issue. Auto-upload stopped working for me after May 18th (the last photos were uploaded on this date). Nothing in June nor July. I found out that the Auto-Upload configuration was "magically" lost (no auto-upload configured), so I enabled it again for my Camera and Screenshots folders, but alas it's not uploading anything, neither previous non-uploaded photos, nor new photos taken since re-enabling auto-upload.

**Comment by Lantyda** [comment]
> I'm also affected by this issue. Auto-upload stopped working for me after May 18th (the last photos were uploaded on this date). Nothing in June nor July. I found out that the Auto-Upload configuration was "magically" lost (no auto-upload configured), so I enabled it again for my Camera and Screenshots folders, but alas it's not uploading anything, neither previous non-uploaded photos, nor new photos taken since re-enabling auto-upload.

I made a github account just to say that I'm experiencing the same issue. Tried uninstalling / reinstalling, made sure to have the app excluded from energy saving, deselected/reselected auto-upload folders, chose different targets on the server.... Made sure that the server has all the updates... And still nothing. A key functionality for this app is lost.

**Comment by BLu85** [comment]
This issue seems the same as #9320 that has been opened for years. Also, I wonder if this #11847 is also true?
No reason to add new features when key functionalities do not work properly.

**Comment by mnalis** [comment]
For me, the issue was that after nextcloud app reinstall, under android `Settings` / `User & accounts` / `Next cloud` option `Sync files` was `off`. Turning it `on` and letting it finish syncing (which took some time due to several thousands of pictures) it seems to have started syncing again.

**Comment by joshtrichards** [comment]
@BLu85 

- What type of auto-upload folders are these? (Custom, auto detected)
- And what are your auto-upload settings for the problematic ones?
- What are the similarities between the two devices that do not function versus the one that does? (I.e. make/make, Android OS version)
- What appears under the Uploads tab queue? 
- Also, any chance you can get a debug log? https://github.com/nextcloud/android?tab=readme-ov-file#getting-debug-info-via-logcat-mag

**Comment by BLu85** [comment]
@joshtrichards requested info are below here.
Thanks

> 
>     * What type of auto-upload folders are these? (Custom, auto detected)
- Auto detected Pictures and Videos. I have roughly 7k pictures on the phone. The majority of them are on the server as well. There are 500+ pictures on the phone that are not on the server and should be auto-uploaded. This does not happen.
> 
>     * And what are your auto-upload settings for the problematic ones?
All the 4 phones have all the same Auto-Upload settings. Remote folder is a custom folder (i.e. **not** _/InstantUpload/Camera/_)
- **Only upload on unmetered WiFi**: ticked
- **Only upload when charging**: ticked
- **Also upload existing files**: ticked
- **Original files will be**...kept in original folder, as it is readonly
- **What to do if the file already exists?**: skip uploading

>     * What are the similarities between the two devices that do not function versus the one that does? (I.e. make/make, Android OS version)


- p1) Xiaomi A1, Android One: Auto-Upload **works fine**
- p2) Xiaomi 12, Android 12: Auto-Upload **works** but also experiences #11974 problem
- p3) Xiaomi Note 8T, Android 11: Nothing uploaded. Auto-upload never triggered. Upload tab has no queue, it's empty
- p4) Huawei Nova, Android 7.0: Nothing uploaded. Auto-upload never triggered. Upload tab has no queue, it's empty
> 
>     * What appears under the Uploads tab queue?
- The 2 phones (p3 and p4) that have the Auto-Upload not working have the **Uploads** tab empty. My phone experiences a huge battery drain (Nextcloud app drains up to 57%). Phone was let connected to the charger the entire night. Up to version [3.23.0](https://github.com/nextcloud/android/releases/tag/stable-3.23.0) my phone was working perfectly, no battery drain and pictures detected and auto-uploaded as soon as WiFi and charger were connected.
> 
>     * Also, any chance you can get a debug log? https://github.com/nextcloud/android?tab=readme-ov-file#getting-debug-info-via-logcat-mag
- Will see what I can do.

Thanks for considering this issue. Really appreciated.

**Comment by JonasMayerDev** [comment]
I think I experience the same issue on my private device. I'm going to take a look at it. First idea: creating a file list takes too long for a background process (without foreground notification) and gets terminated before finishing.

**Comment by JonasMayerDev** [comment]
Jupp just debug a bit and it seems like FilesSyncHelper.insertAllDBEntries takes a long time when the auto upload contains too many images. I'll try to fix the issue.

**Comment by jtrees** [comment]
> For me, the issue was that after nextcloud app reinstall, under android `Settings` / `User & accounts` / `Next cloud` option `Sync files` was `off`. Turning it `on` and letting it finish syncing (which took some time due to several thousands of pictures) it seems to have started syncing again.

Thanks you. I was able to fix the issue on my end with these instructions.
