### ISSUE TITLE
Tighter integration on apps within Nextcloud ecosystem

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#11744]
See https://github.com/nextcloud/files-clients/issues/10

**Comment by ZetaTom** [comment]
## Update
Here is a preview of the current state.

Light Mode | Dark Mode
--- | ---
![blue-light-show](https://github.com/nextcloud/android/assets/70907959/73b68e64-fe2e-4e70-8de3-d7034eb85013) | ![blue-dark-show](https://github.com/nextcloud/android/assets/70907959/a857aa80-4757-4d3f-8df5-5090b4fef60c)
![yellow-light-show](https://github.com/nextcloud/android/assets/70907959/71fa3e39-0421-42ff-b5ea-620658ee0cb3) | ![yellow-dark-show](https://github.com/nextcloud/android/assets/70907959/5b3fe7c2-0e1f-4cb9-8f9c-d8f423de0900)
![blue-light-hide](https://github.com/nextcloud/android/assets/70907959/61abf5b1-a742-4ad7-baee-354751396450) | ![yellow-dark-hide](https://github.com/nextcloud/android/assets/70907959/b3e9c816-916f-4a53-b9a6-c2e4192dfb17)

The ecosystem app icons are displayed in the header of the navigation bar and are coloured according to the server/user defined primary colour. Clicking on an icon will attempt to open the corresponding application and, if applicable, carry over the logged in user. If the application is not yet installed, the user will be prompted to open an app store to download it. The *More* button redirects to an installed app store with the search query *Nextcloud*. If no app stores are found, the Google Play Store web page is opened as a fallback.
There is also a new settings option, to disable/hide the app switcher, which is enabled by default.
