### ISSUE TITLE
Autoupload does not create directories

### ISSUE THREAD

**Issue by mgoppold** [nextcloud/android#1175]
### Actual behaviour
- Autoupload with Subfolder based on year and month does not work because the directory is not created. 

### Expected behaviour
- create the destination directory and auto upload the picture
 
### Steps to reproduce
1. set up  Autoupload with Subfolder based on year and month 
2. take some pictures

### Workaround
- create the monthly directories by hand

### Environment data
Android version: 7.0

Device model: Sony Xperia Z5 Compact (E5823)

Stock or customized system: Sony

Nextcloud app version: 1.4.3 and nextcloud-dev-20170711

Nextcloud server version: nc 12

**Comment by mario** [comment]
Dear users,

thank you for your patience. After lots of work, we’re super excited to be able to give you a test version with new auto upload implementation. Keep in mind we will only accept bugs related to Auto Upload in this APK, as other things might be broken.

https://cloud.nextcloud.com/s/ftZraTruRQjTe0R

This is a dev APK so it will not overwrite your existing play store/f-droid APK unless you’re already running dev version. Also, you might need to remove your existing dev version before installing this one.

Explanation of the current functionality:
- added support for custom folders
- separated image and video folders
- checks for new files happens every 15-20 minutes
- automatic retry every 15-20 minutes or when you force close/open the app
- automatic pause once network is changed (untested!)
- significantly less battery usage

All and any testing is more than appreciated, especially with large and ever-going files like Videos. (like, try to record a 30 min video).

Let me know if you’ve got any questions.

Cheers,
Mario

**Comment by tobiasKaminsky** [comment]
@mgoppold 
Meanwhile we enhanced the app. Can you please try and report back if the bug still exists on latest official version or even try our [dev version](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#dev-release)?

**Comment by mgoppold** [comment]
Sorry for the late response. With nextcloud 13 on my server and app version 3.0.1 the directories were created as expected.

**Comment by DavidVentura** [comment]
This is happening for me in 3.0.2 from FDroid. If I force a rescan with 'create subdirectories' checked I get an instant error "Server unavailable". Works OK if I disable the aubdirectories.

**Comment by AndyScherzinger** [comment]
@DavidVentura can you please update to 3.0.3 :)

**Comment by DavidVentura** [comment]
Can you release that on f-droid?

**Comment by AndyScherzinger** [comment]
It is available on f-droid: https://f-droid.org/packages/com.nextcloud.client/
