### ISSUE TITLE
UX: Enhance sharing when resharing is forbidden

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#1176]
### Actual behaviour
- error after sharing

### Expected behaviour
- show a text "not allowed to reshare files/folders" instead of whole stuff beneath the horizontal border
![2017-07-12-120537](https://user-images.githubusercontent.com/5836855/28112723-6db14ce0-66fa-11e7-9cea-b16bfb9e5dde.png)
 
### Steps to reproduce
1. disable "allow resharing" in server setting
2. try to share a shared file

PR: #1792

**Comment by vnidens** [comment]
@tobiasKaminsky What kind of notification that the resharing is forbidden you see here?

I've been thinking about Snackbar or a Dialog but personally I think that Snackbar is better choice since it should be just a notification without any additional actions required.

It would look like on the screenshot below.
![screenshot_20170728-122801](https://user-images.githubusercontent.com/134937/28711552-a08beede-7390-11e7-95ac-57167509b397.png)]

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky @vnidens Snackbar sounds good to me, also looking at the fact that #1198 whenever merged to master will also move many Toasts to Snackbars :)

**Comment by vnidens** [comment]
@AndyScherzinger Great! In this case I'm continue to work on this issue and #1177

**Comment by vnidens** [comment]
@AndyScherzinger Code wise for sure :) 

Can you tell me how I should manage the new string resource (the `Resharing is not allowed` message) in terms of localization? Should I add translations or I can only add it into the main `strings.xml` file and then it would be handled by Transifex?

**Comment by AndyScherzinger** [comment]
@vnidens nice! As for the translations, you only need to commit the main ```strings.xml``` and everything else will be handled automatically via our bot+transifex as soon as the PR has been merged to master.

**Comment by tobiasKaminsky** [comment]
:+1: looking forward to your contribution.
Happy to have you on board :-)

**Comment by vnidens** [comment]
@AndyScherzinger @tobiasKaminsky While working on this issue I've noticed that the resharing is also possible from several file previews fragments (not only from the files list case you've mentioned).

I think it would be better to hide the "Share" menu completely in these fragments if the resharing isn't enabled. From my point of view it's much better to not have the menu than have one which can do nothing but show you the message "you can't do that" :)

**Comment by tobiasKaminsky** [comment]
My idea was to explain it to the user as it can happen that another account (on a different server) is allowed to share the file/folder and thus confuse the user. 
But let us ask @nextcloud/designers how to proceed

(I am also fine with removing the share entry if resharing is disabled)

**Comment by AndyScherzinger** [comment]
I'd also say remove it if resharing is forbidden but let hear what the designers say :)

**Comment by MorrisJobke** [comment]
> I'd also say remove it if resharing is forbidden but let hear what the designers say :)

Yep - I would just not show it.

**Comment by jancborchardt** [comment]
Even better (if possible) might be to show it greyed out and change the text from »Share« to »Not allowed to share«? Or just have it greyed out and show a snackbar with further info on click.

Just not showing it is missing feedback, and will also be confusing since people don’t know why.

**Comment by tobiasKaminsky** [comment]
> Just not showing it is missing feedback, and will also be confusing since people don’t know why.

This was exactly what I said in https://github.com/nextcloud/android/issues/1176#issuecomment-319009614, but @AndyScherzinger and @MorrisJobke voted for not showing.

**Comment by AndyScherzinger** [comment]
Well, I am also fine with showing the info that it can't be shared (for the bugfix release after the next stable) while I don't know if (being a user) I would want to click share just to realize that I can't / am not allowed to.

**Comment by jancborchardt** [comment]
@tobiasKaminsky yes, with the important distinction that the »Share« text needs to be greyed out, otherwise it seems active/clickable.

@AndyScherzinger Yep – the greying out is an indicator that it’s not really available / clickable. If it’s clicked anyway, you get feedback why. :)

**Comment by tobiasKaminsky** [comment]
Where should be the greyed out shared text? 

In the overflow menu when selecting a file/folder?
In the "share" popup?
![2017-07-12-120537](https://user-images.githubusercontent.com/5836855/28112723-6db14ce0-66fa-11e7-9cea-b16bfb9e5dde.png)

**Comment by jancborchardt** [comment]
In the overflow menu.

The share menu should not show, cause you can't use it, right? (Or can you share the link?) cc @schiessle

Instead of the sharing dialog, tapping the greyed out "Share" text should show a toast/snackbar saying smth like "You don't have permissions to share this file".

**Comment by vnidens** [comment]
I see everyone agreed to still keep the menu but grey it out and show a message that the action isn't allowed.

I would update the behavior in the near future.

**Comment by jancborchardt** [comment]
@vnidens yes, that contribution would be very welcome! :)

**Comment by AndyScherzinger** [comment]
@vnidens that would be really grat 🚀

**Comment by vnidens** [comment]
@jancborchardt @AndyScherzinger @tobiasKaminsky After some digging it seems that it's impossible to change view/background of an individual ActionBar/Toolbar menu - you can only apply theme to all menu items at once.

So the final solution would look like an ordinary "Share" menu item which shows Snackbar with warning.

PS. If you do know the way to update the view of the individual menu item just give me a tip

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger can you help here as you are our ui master? ;-)

**Comment by tobiasKaminsky** [comment]
> So the final solution would look like an ordinary "Share" menu item which shows Snackbar with warning.

@jancborchardt are you fine with this?

**Comment by jancborchardt** [comment]
Sounds ok, yes.
