### ISSUE TITLE
"browser is not supported" error

### ISSUE THREAD

**Issue by AlexeyMarkarov** [nextcloud/android#11768]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Install NC 3.25.0 and login -> it looks like a browser.
2. Uninstall 3.25.0 and install 3.24.1 -> it looks like a proper native app.

Alternatively,
1. Install NC 3.24.1 and login to your account.
2. Update to 3.25.0.
3. Clear cache and app data.
4. Login again.

### Expected behaviour

Expected native app look and feel.

### Actual behaviour

App thinks it's a browser, and shows an error that it's outdated.
Additionally, login credentials are not saved, closing and reopening the app prompts for login again.

### Android version

11

### Device brand and model

Motorola moto g9 play

### Stock or custom OS?

Stock

### Nextcloud android app version

3.25.0

### Nextcloud server version

26.0.2

### Using a reverse proxy?

Yes

### Android logs

--------- beginning of main
06-22 12:48:48.442 29146 29146 D AuthenticatorActivity: onPause() ending
06-22 12:48:48.772 29146 29146 D AuthenticatorActivity: onStop() ending
06-22 12:48:48.773 29146 29146 D AuthenticatorActivity: onSaveInstanceState(Bundle) starting
06-22 12:48:49.405 29146 29146 D AuthenticatorActivity: onStart() starting
06-22 12:48:49.413 29146 29146 D AuthenticatorActivity: onResume() starting
06-22 12:48:52.102 29146 29146 D AuthenticatorActivity: onPause() ending
06-22 12:48:52.364 29146 29146 D AuthenticatorActivity: onStop() ending
06-22 12:48:52.364 29146 29146 D AuthenticatorActivity: onSaveInstanceState(Bundle) starting
06-22 12:48:57.212 29146 29146 D AuthenticatorActivity: onStart() starting
06-22 12:48:57.238 29146 29146 D AuthenticatorActivity: onResume() starting
06-22 12:49:02.790 29146 29146 D AuthenticatorActivity: onPause() ending
06-22 12:49:03.190 29146 29146 D AuthenticatorActivity: onStop() ending
06-22 12:49:03.191 29146 29146 D AuthenticatorActivity: onSaveInstanceState(Bundle) starting
06-22 12:49:27.805 29146 29146 D AuthenticatorActivity: onStart() starting
06-22 12:49:27.818 29146 29146 D AuthenticatorActivity: onResume() starting
06-22 12:49:29.215 29146 29146 W cr_AwAutofillManager: Autofill is disabled: AutofillManager isn't available in given Context.
06-22 12:49:29.230 29146 29146 W cr_AwAutofillManager: Autofill is disabled: AutofillManager isn't available in given Context.
06-22 12:49:39.099 29146 29146 D AuthenticatorActivity: onPause() ending
06-22 12:49:39.385 29146 29146 D AuthenticatorActivity: onStop() ending
06-22 12:49:39.390 29146 29146 D AuthenticatorActivity: onSaveInstanceState(Bundle) starting
06-22 12:49:46.206 29146 29146 D AuthenticatorActivity: onStart() starting
06-22 12:49:46.209 29146 29146 D AuthenticatorActivity: onResume() starting
06-22 12:49:47.325 29146 29146 W cr_AwAutofillManager: Autofill is disabled: AutofillManager isn't available in given Context.
06-22 12:49:55.632 29146 29146 D AuthenticatorActivity: onPause() ending
06-22 12:49:55.844 29146 29146 D AuthenticatorActivity: onStop() ending
06-22 12:49:55.845 29146 29146 D AuthenticatorActivity: onSaveInstanceState(Bundle) starting
06-22 12:50:01.134 29146 29171 D MaterialSchemesProviderImpl: User is anonymous, using default schemes
06-22 12:50:01.223 29146 29178 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=f7d0fefb-0c71-4c55-b7a2-068129477a69, tags={ com.nextcloud.client.jobs.MediaFoldersDetectionWork, *, name:immediate_media_folder_detection, timestamp:1687427401022 } ]
06-22 12:50:04.609 29146 29146 D AuthenticatorActivity: onStart() starting
06-22 12:50:04.613 29146 29146 D AuthenticatorActivity: onResume() starting
06-22 12:50:16.589 29146 29146 D AuthenticatorActivity: onPause() ending
06-22 12:50:16.849 29146 29146 D AuthenticatorActivity: onStop() ending
06-22 12:50:16.851 29146 29146 D AuthenticatorActivity: onSaveInstanceState(Bundle) starting
06-22 12:50:17.363 29146 29146 D AuthenticatorActivity: onDestroy() ending
06-22 12:50:17.457 29146 29146 D FileDisplayActivity: onDestroy() ending
06-22 12:50:17.496 29146 29146 V OperationsService: Destroying service
06-22 12:50:17.497 29146 29146 V FileDownloader: Destroying service
06-22 12:50:17.498 29146 29146 V FileUploader: Destroying service
06-22 12:50:20.354 29146 29146 V FileDisplayActivity: onCreate() start
06-22 12:50:20.363 29146 29146 D MaterialSchemesProviderImpl: User is anonymous, using default schemes
06-22 12:50:20.367 29146 29146 D MaterialSchemesProviderImpl: User is anonymous, using default schemes
06-22 12:50:20.369 29146 29146 D FileDisplayActivity: onCreate(Bundle) starting
06-22 12:50:20.517 29146 29146 D FileDisplayActivity: onStart() starting
06-22 12:50:20.535 29146 29146 E FileDisplayActivity: Access to unexisting list of files fragment!!
06-22 12:50:20.535 29146 29146 V FileDisplayActivity: onResume() start
06-22 12:50:20.536 29146 29146 D FileDisplayActivity: onResume() starting
06-22 12:50:20.538 29146 29146 D MaterialSchemesProviderImpl: User is anonymous, using default schemes
06-22 12:50:20.543 29146  4749 D ExternalLinks: links disabled
06-22 12:50:20.592 29146 29146 D MaterialSchemesProviderImpl: User is anonymous, using default schemes
06-22 12:50:20.594 29146 29146 I chatty  : uid=10407(com.nextcloud.client) identical 1 line
06-22 12:50:20.597 29146 29146 D MaterialSchemesProviderImpl: User is anonymous, using default schemes
06-22 12:50:20.600 29146 29146 I OCFileListFragment: onAttach
06-22 12:50:20.602 29146 29146 I OCFileListFragment: onCreateView() start
06-22 12:50:20.602 29146 29146 D ExtendedListFragment: onCreateView
06-22 12:50:20.615 29146 29146 E DrawerActivity: Drawer layout not ready to add drawer listener
06-22 12:50:20.615 29146 29146 I OCFileListFragment: onCreateView() end
06-22 12:50:20.615 29146 29146 I OCFileListFragment: onActivityCreated() start
06-22 12:50:20.655 29146 29146 W DrawerActivity: setDrawerMenuItemChecked has been called with invalid menu-item-ID
06-22 12:50:20.655 29146 29146 W DrawerActivity: setDrawerMenuItemChecked has been called with invalid menu-item-ID
06-22 12:50:20.669 29146 29146 V FileDisplayActivity: onResume() end
06-22 12:50:20.680 29146 29146 V FileDisplayActivity: onPause() start
06-22 12:50:20.681 29146 29146 D FileDisplayActivity: onPause() ending
06-22 12:50:20.681 29146 29146 V FileDisplayActivity: onPause() end
06-22 12:50:20.702 29146 29146 D OperationsService: Creating service
06-22 12:50:20.708 29146 29146 D MaterialSchemesProviderImpl: User is anonymous, using default schemes
06-22 12:50:20.709 29146 29146 D FileDownloader: Creating service
06-22 12:50:20.715 29146 29146 D skia    : --- Failed to create image decoder with message 'unimplemented'
06-22 12:50:20.719 29146 29146 D MaterialSchemesProviderImpl: User is anonymous, using default schemes
06-22 12:50:20.720 29146 29146 D FileUploader: Creating service
06-22 12:50:20.720 29146 29146 D skia    : --- Failed to create image decoder with message 'unimplemented'
06-22 12:50:20.721 29146 29146 V UploadsStorageManager: Updating state of any killed upload
06-22 12:50:20.723 29146 29146 V UploadsStorageManager: No upload was killed
06-22 12:50:20.886 29146 29146 D AuthenticatorActivity: onCreate(Bundle) starting
06-22 12:50:20.960 29146 29146 W ResourcesCompat: Failed to inflate ColorStateList, leaving it to the framework
06-22 12:50:20.960 29146 29146 W ResourcesCompat: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 0: TypedValue{t=0x2/d=0x7f0400fc a=-1}
06-22 12:50:20.960 29146 29146 W ResourcesCompat: 	at android.content.res.TypedArray.getColor(TypedArray.java:528)
06-22 12:50:20.960 29146 29146 W ResourcesCompat: 	at androidx.core.content.res.ColorStateListInflaterCompat.inflate(ColorStateListInflaterCompat.java:160)
06-22 12:50:20.960 29146 29146 W ResourcesCompat: 	at androidx.core.content.res.ColorStateListInflaterCompat.createFromXmlInner(ColorStateListInflaterCompat.java:125)
06-22 12:50:20.960 29146 29146 W ResourcesCompat: 	at androidx.core.content.res.ColorStateListInflaterCompat.createFromXml(ColorStateListInflaterCompat.java:104)
06-22 12:50:20.960 29146 29146 W ResourcesCompat: 	at androidx.core.content.res.ResourcesCompat.inflateColorStateList(ResourcesCompat.java:262)
06-22 12:50:20.960 29146 29146 W ResourcesCompat: 	at androidx.core.content.res.ResourcesCompat.getColorStateList(ResourcesCompat.java:236)
06-22 12:50:20.960 29146 29146 W ResourcesCompat: 	at androidx.core.content.ContextCompat.getColorStateList(ContextCompat.java:558)
06-22 12:50:20.960 29146 29146 W ResourcesCompat: 	at androidx.appcompat.content.res.AppCompatResources.getColorStateList(AppCompatResources.java:48)
06-22 12:50:20.960 29146 29146 W ResourcesCompat: 	at androidx.appcompat.widget.TintTypedArray.getColorStateList(TintTypedArray.java:179)
06-22 12:50:20.960 29146 29146 W ResourcesCompat: 	at androidx.appcompat.widget.AppCompatBackgroundHelper.loadFromAttributes(AppCompatBackgroundHelper.java:66)
06-22 12:50:20.960 29146 29146 W ResourcesCompat: 	at androidx.appcompat.widget.AppCompatImageButton.<init>(AppCompatImageButton.java:83)
06-22 12:50:20.960 29146 29146 W ResourcesCompat: 	at androidx.appcompat.widget.AppCompatImageButton.<init>(AppCompatImageButton.java:73)
06-22 12:50:20.960 29146 29146 W ResourcesCompat: 	at androidx.appcompat.app.AppCompatViewInflater.createImageButton(AppCompatViewInflater.java:253)
06-22 12:50:20.960 29146 29146 W ResourcesCompat: 	at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:168)
06-22 12:50:20.960 29146 29146 W ResourcesCompat: 	at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1678)
06-22 12:50:20.960 29146 29146 W ResourcesCompat: 	at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1729)
06-22 12:50:20.960 29146 29146 W ResourcesCompat: 	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1059)
06-22 12:50:20.960 29146 29146 W ResourcesCompat: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:995)
06-22 12:50:20.960 29146 29146 W ResourcesCompat: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
06-22 12:50:20.960 29146 29146 W ResourcesCompat: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
06-22 12:50:20.960 29146 29146 W ResourcesCompat: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
06-22 12:50:20.960 29146 29146 W ResourcesCompat: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
06-22 12:50:20.960 29146 29146 W ResourcesCompat: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
06-22 12:50:20.960 29146 29146 W ResourcesCompat: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
06-22 12:50:20.960 29146 29146 W ResourcesCompat: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
06-22 12:50:20.960 29146 29146 W ResourcesCompat: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
06-22 12:50:20.960 29146 29146 W ResourcesCompat: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
06-22 12:50:20.960 29146 29146 W ResourcesCompat: 	at com.owncloud.android.databinding.AccountSetupBinding.inflate(AccountSetupBinding.java:84)
06-22 12:50:20.960 29146 29146 W ResourcesCompat: 	at com.owncloud.android.databinding.AccountSetupBinding.inflate(AccountSetupBinding.java:78)
06-22 12:50:20.960 29146 29146 W ResourcesCompat: 	at com.owncloud.android.authentication.AuthenticatorActivity.onCreate(AuthenticatorActivity.java:326)
06-22 12:50:20.960 29146 29146 W ResourcesCompat: 	at android.app.Activity.performCreate(Activity.java:8108)
06-22 12:50:20.960 29146 29146 W ResourcesCompat: 	at android.app.Activity.performCreate(Activity.java:8092)
06-22 12:50:20.960 29146 29146 W ResourcesCompat: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
06-22 12:50:20.960 29146 29146 W ResourcesCompat: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3481)
06-22 12:50:20.960 29146 29146 W ResourcesCompat: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3683)
06-22 12:50:20.960 29146 29146 W ResourcesCompat: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
06-22 12:50:20.960 29146 29146 W ResourcesCompat: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
06-22 12:50:20.960 29146 29146 W ResourcesCompat: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
06-22 12:50:20.960 29146 29146 W ResourcesCompat: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2132)
06-22 12:50:20.960 29146 29146 W ResourcesCompat: 	at android.os.Handler.dispatchMessage(Handler.java:106)
06-22 12:50:20.960 29146 29146 W ResourcesCompat: 	at android.os.Looper.loop(Looper.java:250)
06-22 12:50:20.960 29146 29146 W ResourcesCompat: 	at android.app.ActivityThread.main(ActivityThread.java:7851)
06-22 12:50:20.960 29146 29146 W ResourcesCompat: 	at java.lang.reflect.Method.invoke(Native Method)
06-22 12:50:20.960 29146 29146 W ResourcesCompat: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
06-22 12:50:20.960 29146 29146 W ResourcesCompat: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
06-22 12:50:20.964 29146 29146 D AuthenticatorActivity: onStart() starting
06-22 12:50:20.965 29146 29146 D AuthenticatorActivity: onNewIntent()
06-22 12:50:20.967 29146 29146 D AuthenticatorActivity: onResume() starting
06-22 12:50:20.978 29146 29146 D FileActivity: Operations service connected
06-22 12:50:20.978 29146 29146 D FileDisplayActivity: Download service connected
06-22 12:50:20.978 29146 29146 D FileDisplayActivity: Upload service connected
06-22 12:50:21.036 29146 29146 D AuthenticatorActivity: onPause() ending
06-22 12:50:21.105 29146 29146 D FirstRunActivity: onCreate(Bundle) starting
06-22 12:50:21.131 29146 29146 D FirstRunActivity: onStart() starting
06-22 12:50:21.133 29146 29146 D FirstRunActivity: onResume() starting
06-22 12:50:21.140 29146 29146 D FileDisplayActivity: onStop() ending
06-22 12:50:21.141 29146 29146 V FileDisplayActivity: onSaveInstanceState() start
06-22 12:50:21.143 29146 29146 D FileDisplayActivity: onSaveInstanceState(Bundle) starting
06-22 12:50:21.143 29146 29146 D ExtendedListFragment: onSaveInstanceState()
06-22 12:50:21.144 29146 29146 V FileDisplayActivity: onSaveInstanceState() end
06-22 12:50:21.471 29146 29146 D AuthenticatorActivity: onStop() ending
06-22 12:50:21.472 29146 29146 D AuthenticatorActivity: onSaveInstanceState(Bundle) starting
06-22 12:50:21.858 29146 29146 D FirstRunActivity: onPause() ending
06-22 12:50:22.192 29146 29146 D FirstRunActivity: onStop() ending
06-22 12:50:22.196 29146 29146 D FirstRunActivity: onSaveInstanceState(Bundle) starting
06-22 12:50:25.060 29146 29146 D UploadsStorageManager: QUERY: (status== ? OR last_result==9 OR last_result==13 OR last_result==11 OR last_result==14 ) AND last_result!= 16 ROWID: -1
06-22 12:50:25.096 29146 29146 V UploadsStorageManager: getUploads() got 0 rows from page 0, 0 rows total so far, last ID -1
06-22 12:50:25.096 29146 29146 V UploadsStorageManager: getUploads() returning 0 (0) rows after reading 1 pages
06-22 12:50:25.096 29146 29146 D UploadsStorageManager: QUERY: (status== ? OR last_result==9 OR last_result==13 OR last_result==11 OR last_result==14 ) AND last_result!= 16 ROWID: -1
06-22 12:50:25.102 29146 29146 V UploadsStorageManager: getUploads() got 0 rows from page 0, 0 rows total so far, last ID -1
06-22 12:50:25.102 29146 29146 V UploadsStorageManager: getUploads() returning 0 (0) rows after reading 1 pages
06-22 12:50:25.146 29146 29146 D UploadsStorageManager: QUERY: (status== ? OR last_result==9 OR last_result==13 OR last_result==11 OR last_result==14 ) AND last_result!= 16 ROWID: -1
06-22 12:50:25.157 29146 29146 V UploadsStorageManager: getUploads() got 0 rows from page 0, 0 rows total so far, last ID -1
06-22 12:50:25.157 29146 29146 V UploadsStorageManager: getUploads() returning 0 (0) rows after reading 1 pages
06-22 12:50:25.158 29146 29146 D UploadsStorageManager: QUERY: (status== ? OR last_result==9 OR last_result==13 OR last_result==11 OR last_result==14 ) AND last_result!= 16 ROWID: -1
06-22 12:50:25.164 29146 29146 V UploadsStorageManager: getUploads() got 0 rows from page 0, 0 rows total so far, last ID -1
06-22 12:50:25.165 29146 29146 V UploadsStorageManager: getUploads() returning 0 (0) rows after reading 1 pages
06-22 12:51:51.459 29146 29146 D FirstRunActivity: onDestroy() ending
06-22 12:51:51.516 29146 29146 D FirstRunActivity: onCreate(Bundle) starting
06-22 12:51:51.562 29146 29146 D FirstRunActivity: onStart() starting
06-22 12:51:51.574 29146 29146 D FirstRunActivity: onResume() starting

### Server error logs

```bash
{"reqId":"em7zFdjhW4PYZqg8UFuM","level":3,"time":"2023-06-21T14:50:31+00:00","remoteAddr":"172.25.0.1","user":"alex","app":"index","method":"POST","url":"/apps/text/session/sync","message":"OCA\\Text\\Service\\DocumentService::getFileForSession(): Argument #1 ($session) must be of type OCA\\Text\\Db\\Session, bool given, called in /var/www/html/apps/text/lib/Service/ApiService.php on line 232 in file '/var/www/html/apps/text/lib/Service/DocumentService.php' line 433","userAgent":"Motorola moto g(9) play (Android)","version":"26.0.2.1","exception":{"Exception":"Exception","Message":"OCA\\Text\\Service\\DocumentService::getFileForSession(): Argument #1 ($session) must be of type OCA\\Text\\Db\\Session, bool given, called in /var/www/html/apps/text/lib/Service/ApiService.php on line 232 in file '/var/www/html/apps/text/lib/Service/DocumentService.php' line 433","Code":0,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/App.php","line":183,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\Text\\Controller\\SessionController"],"sync"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Text\\Controller\\SessionController","sync",["OC\\AppFramework\\DependencyInjection\\DIContainer"],["text.Session.sync"]]},{"file":"/var/www/html/lib/base.php","line":1058,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/text/session/sync"]},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","Line":169,"Previous":{"Exception":"TypeError","Message":"OCA\\Text\\Service\\DocumentService::getFileForSession(): Argument #1 ($session) must be of type OCA\\Text\\Db\\Session, bool given, called in /var/www/html/apps/text/lib/Service/ApiService.php on line 232","Code":0,"Trace":[{"file":"/var/www/html/apps/text/lib/Service/ApiService.php","line":232,"function":"getFileForSession","class":"OCA\\Text\\Service\\DocumentService","type":"->","args":["*** sensitive parameters replaced ***",null]},{"file":"/var/www/html/apps/text/lib/Controller/SessionController.php","line":92,"function":"sync","class":"OCA\\Text\\Service\\ApiService","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":230,"function":"sync","class":"OCA\\Text\\Controller\\SessionController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":137,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\Text\\Controller\\SessionController"],"sync"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":183,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\Text\\Controller\\SessionController"],"sync"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Text\\Controller\\SessionController","sync",["OC\\AppFramework\\DependencyInjection\\DIContainer"],["text.Session.sync"]]},{"file":"/var/www/html/lib/base.php","line":1058,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/text/session/sync"]},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/apps/text/lib/Service/DocumentService.php","Line":433},"CustomMessage":"--"}}
```

### Additional information

Version 3.24.1 does not have this problem. NC in actual browser (either desktop or mobile) also works fine.

https://help.nextcloud.com/t/client-looks-weird/93563 - same problem but no real solution.
If there is indeed some server misconfiguration and android app encounters a problem then it should clearly communicate that problem instead of (or at least in addition to) falling back to being a broken webview.

![Screenshot_20230621-192920](https://github.com/nextcloud/android/assets/3584082/036dea3f-f0b2-4b14-a683-5c34cfacefac)

![Screenshot_20230622-124959](https://github.com/nextcloud/android/assets/3584082/69430943-ef81-4c25-8182-5bf8f9f0024c)

![Screenshot_20230621-192949](https://github.com/nextcloud/android/assets/3584082/f8107eb7-c449-45d0-a9f4-978dcb090ae1)

**Comment by AlexeyMarkarov** [comment]
I updated Android System WebView to v114.0.5735.196 and both NC apps (Files and Talk) seem to be fixed. Still curious why it happened though.

**Comment by fakendry** [comment]
Good morning, I have the exact same problem on iPhone (iOS 17.4.1 and Nextcloud version 28). However I tried to connect the app to the nextcloud demo server “https://nextcloud27.our-servers.de/” (Username: user Password: demo123) and the app works perfectly. So it seems like a server problem.

The problem arose after reinstallation nextcloud.

Excuse me, do I have to open a new post?
