### ISSUE TITLE
UX: Enhance edit share when resharing is forbidden

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#1177]
### Actual behaviour
- misleading "can share" is shown

### Expected behaviour
- do not show option for sharing
 
### Steps to reproduce
1. disable "allow resharing" in server
2. share a new file to an user
3. edit option for user

![2017-07-12-121021](https://user-images.githubusercontent.com/5836855/28112992-39cc6170-66fb-11e7-8ec5-a8c6681e4674.png)

**Comment by AndyScherzinger** [comment]
#1247 has been merged for 1.5.0
