### ISSUE TITLE
Add to favorites option missing when photo or video is opened. 

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/android#11782]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

https://github.com/nextcloud/android/assets/59488153/8ac9d96b-a79c-4aa2-a7de-725997d7d702

### Expected behaviour

Should have have the option to add to favorites under the menue

### Actual behaviour

Not an option

### Android version

13

### Device brand and model

Samsung S22 Ultra

### Stock or custom OS?

Stock

### Nextcloud android app version

3.25.0

### Nextcloud server version

27.0.0

### Using a reverse proxy?

No

**Comment by diegantobass** [comment]
Anyone knows if the menu item was present in prior versions of the app?

**Comment by joshtrichards** [comment]
Seems a reasonable idea, but it's enhancement unless you're saying it was there before. 😉

**Comment by joshtrichards** [comment]
Related: #5845
