### ISSUE TITLE
Support Android 14 / API 34

### ISSUE THREAD

**Issue by ZetaTom** [nextcloud/android#11791]
Final release [expected](https://developer.android.com/about/versions/14/overview) in August(?)

See #11739

**Comment by alperozturk96** [comment]
Here are briefly the parts that interest us regarding Android 14 update

1) Schedule exact alarms are denied by default with Android 14 in our codebase I can't able to find that type of alarm. Please correct me if I am wrong.

2) With Android 14 there is [new permission](https://developer.android.com/about/versions/14/behavior-changes-all#partial-photo-video-access) that recommended for picking photos from gallery if we don't use it automatically [compatible mode](https://developer.android.com/about/versions/14/changes/partial-photo-video-access#compatibility-mode) activated. Compatibility mode may break our UX. Compatibility Mode Briefly: Upon initial selection, the app is granted temporary media permissions, which are revoked when it goes to the background or is closed. Subsequent access to media requires a manual permission request, and using the READ_MEDIA_VISUAL_USER_SELECTED permission is advised for improved user experience.

3) We should reconsider the need for non-dismissible notifications within our app and align with the established [guidelines](https://developer.android.com/about/versions/14/behavior-changes-all#non-dismissable-notifications). The following components currently have non-dismissible notifications: _**AppNotificationManagerImpl, FilesUploadWorker, PlayerService, FileDownloader, and FileUploader.**_

@ZetaTom @AndyScherzinger @tobiasKaminsky

**Comment by tobiasKaminsky** [comment]
Play console complains about usage of foreground service.
We either need to remove them or declare why they are used.

**Comment by tobiasKaminsky** [comment]
https://proandroiddev.com/foreground-services-in-android-14-whats-changing-dcd56ad72788

**Comment by tobiasKaminsky** [comment]
https://support.google.com/googleplay/android-developer/answer/13392821

**Comment by tobiasKaminsky** [comment]
Declared foreground usage via console, :crossed_fingers:
