### ISSUE TITLE
Enhancement: add check if enough ressources available before upload

### ISSUE THREAD

**Issue by victorbw** [nextcloud/android#1179]
I've experienced that some users tend to copy local files within the synced nextcloud-folder, which 'overflows' the servers capacity and force the mysql-server to shut down.

So in a few steps this might be a problem from the past:
- crosscheck what is new on local system and what is already on server
- calculate total size of new local files
- comparison with available space on server
- upload/don't upload (with message why)

does this sound like something worth to implement in a future release?

best regards

**Comment by tobiasKaminsky** [comment]
We are planning to enhance auto upload to a real 2 way sync.
But you seem to have server related problem if the mysql server is shutting down.

Also we do not have a synced folder on android. Maybe you are talking about desktop sync client?

**Comment by victorbw** [comment]
yes of course, should be in the other client section.

**Comment by tobiasKaminsky** [comment]
You can report it here: https://github.com/nextcloud/client_theming
