### ISSUE TITLE
Instant Upload broken for CyanogenMod 13

### ISSUE THREAD

**Issue by GregSutcliffe** [nextcloud/android#118]
### Actual behaviour

Taking a photo with the stock Camera app results in "local file not found" in the Uploads section of the Nextcloud Android App
### Expected behaviour

Photo should be uploaded
### Steps to reproduce
- Install app, configure Instant Upload (if it matters - WiFi only, year/month subdirs, default location)
- Take a photo with Camera
- Nextcloud sees the photo, but upload fails with:

```
IMG_20160711_012340.jpg
3.2Mb, Local file not found
user@my-nextcloud-server/nextcloud
Nextcloud/InstantUpload/2016/07
```
### Environment data

Android version: 6.0.1
Device model: Samsung Galaxy S 2 (i9100)
Stock or customized system: CyanogenMod 13
Nextcloud app version: 1.1.0
Nextcloud server version: 9.0.52 (Debian 8)
#### Web server error log

```
172.20.10.116 - gwmngilfen [11/Jul/2016:01:33:32 +0100] "HEAD /nextcloud/remote.php/webdav/InstantUpload/2016/07/ HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Android) nextcloud-android/1.1.0"
172.20.10.116 - gwmngilfen [11/Jul/2016:01:33:33 +0100] "HEAD /nextcloud/remote.php/webdav/InstantUpload/2016/07/IMG_20160711_012340.jpg HTTP/1.1" 404 1307 "-" "Mozilla/5.0 (Android) nextcloud-android/1.1.0"
```
#### Nextcloud log (data/nextcloud.log)

```
Nothing logged (N.B. file appears to be owncloud.log...)
```
### Additional Notes

Manual upload from Gallery also fails, although with nothing logged to the webserver. Can raise a separate issue if required, but it feels related... :)

**Comment by GregSutcliffe** [comment]
For the record - this issue was present with the default Debian 8 self-signed cert, using an https URL in the Android app. Once I switch to a LetsEncrypt cert, the issue went away, and both manual and instant uploads are now fine.

If it's the cert at fault, might be worth notifying the user that this is the issue in some form (perhaps as OCReader does at login?)

**Comment by AndyScherzinger** [comment]
@LukasReschke can we have a server setup with the cert error somewhere to reproduce this behavior and notify the user? :)

**Comment by LukasReschke** [comment]
> @LukasReschke can we have a server setup with the cert error somewhere to reproduce this behavior and notify the user? :)

So you need a system like "broken-ssl.cloud.wtf" that would have a self-signed SSL certificate? If yes  please write "YES" and I shall get you something 😉

**Comment by AndyScherzinger** [comment]
YES

But it probably needs to be investigated by @przybylski or @tobiasKaminsky since the instant upload is broken in Android N Preview 4 and I haven't found the time to further look into this matter :(

**Comment by przybylski** [comment]
I would love to fix that, but I have no android device :D maybe i'll borrow one from a friend and fix this ugly bug.

**Comment by GregSutcliffe** [comment]
So this happened again, against my proper-SSL system. The scenario was that I re-installed my phone with latest Cyanogen (i9100 CM13 2016-07-17 nightly), which of course wiped out my user configs. Re-installed NextCloud, added my account, fine. Then:

* Took photo - instant-upload failed
* Tried manually uploading photo to InstantUpload/07 - failed
* Gave it a stern glare (this step optional :p)
* Tried manually uploading a non-photo file to the root of the file share - worked (wtf?)
* Retried step 2 - worked
* Took another photo - instant-upload worked.

I had a look through the logs on the server, but there's not much - just the 404 entries I showed in the first post. If there's logs on the Android side, I'd be happy to take a look, assuming they'll still be there after a day or two. I could potentially try to replicate with another wipe, but not this week - got travelling to do :P

**Comment by tobiasKaminsky** [comment]
There is logcat, which can be read with rooted apps.
This would be very helpful, if there is something related to it in the logs.

**Comment by GregSutcliffe** [comment]
I'm going to wipe my phone again for various reasons sometime next week - if I can reproduce it I'll grab the logcat output.

**Comment by GregSutcliffe** [comment]
Ok, so I actually did this tonight, and I think I've got to the bottom of it....

The app correctly requests permission to access the filesystem when you first open it, but not all permissions get correctly set up. If I watch logcat when doing a manual upload, I get:

```
07-24 00:44:07.045  7072  7072 D ReceiveExternalFilesActivity: Uploading file to dir /InstantUpload/2016/
07-24 00:44:07.194  7072  7318 E CopyAndUploadContentUrisTask: Exception while copying content://media/external/images/media/7589 to temporary file
07-24 00:44:07.194  7072  7318 E CopyAndUploadContentUrisTask: java.io.IOException: open failed: EACCES (Permission denied)
07-24 00:44:07.194  7072  7318 E CopyAndUploadContentUrisTask:  at java.io.File.createNewFile(File.java:939)
07-24 00:44:07.194  7072  7318 E CopyAndUploadContentUrisTask:  at com.owncloud.android.ui.asynctasks.CopyAndUploadContentUrisTask.doInBackground(CopyAndUploadContentUrisTask.java:154)
07-24 00:44:07.194  7072  7318 E CopyAndUploadContentUrisTask:  at com.owncloud.android.ui.asynctasks.CopyAndUploadContentUrisTask.doInBackground(CopyAndUploadContentUrisTask.java:47)
07-24 00:44:07.194  7072  7318 E CopyAndUploadContentUrisTask:  at android.os.AsyncTask$2.call(AsyncTask.java:295)
07-24 00:44:07.194  7072  7318 E CopyAndUploadContentUrisTask:  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-24 00:44:07.194  7072  7318 E CopyAndUploadContentUrisTask:  at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
07-24 00:44:07.194  7072  7318 E CopyAndUploadContentUrisTask:  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)07-24 00:44:07.194  7072  7318 E CopyAndUploadContentUrisTask:  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
07-24 00:44:07.194  7072  7318 E CopyAndUploadContentUrisTask:  at java.lang.Thread.run(Thread.java:818)
07-24 00:44:07.194  7072  7318 E CopyAndUploadContentUrisTask: Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
07-24 00:44:07.194  7072  7318 E CopyAndUploadContentUrisTask:  at libcore.io.Posix.open(Native Method)
07-24 00:44:07.194  7072  7318 E CopyAndUploadContentUrisTask:  at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
07-24 00:44:07.194  7072  7318 E CopyAndUploadContentUrisTask:  at java.io.File.createNewFile(File.java:932)
```

Which seems to imply it can't create a temporary file or something, from my limited understanding. However, I then went to App Info and force-stopped the app, reloaded it, and tried again - hey presto, manual upload works (as does Instant Upload).

I've noticed other apps exit themselves after a permissions change (TitaniumBackup leaps to mind) so perhaps thats a valid strategy?

**Comment by mario** [comment]
Please try newest beta:

https://github.com/nextcloud/android/raw/beta/apks/latest.apk

Thanks!

**Comment by tobiasKaminsky** [comment]
I think pointing to Fdroid is also important as (hopefully) some user already use it or do not want to install apk files directly.

**Comment by tobiasKaminsky** [comment]
Does it work now for you @GregSutcliffe

**Comment by GregSutcliffe** [comment]
I think this issue can be closed, yes. I've been testing auto-upload with stable & dev clients due to #833 and I've not seen this File Not Found error in quite a while. Thanks!

**Comment by tobiasKaminsky** [comment]
Glad to hear.
