### ISSUE TITLE
Enhance image preview view / detail

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#11820]
- show maps (geo location from server)
- show metadata if available (exif data)

Later: swipe up in image browser (currently out of scope)

---
<img width="540" alt="Screenshot_20230803_112724" src="https://github.com/nextcloud/android/assets/1315170/0f8c57f3-b97b-42c3-b9ff-c5e3eace1b37">

* feel free to ignore the rounded corners for the map (or implement them if easily possible)
* use open street maps (for examples see talk client), also pin can just be a simple one, no "photo-pin" needed

**Comment by jancborchardt** [comment]
Design-wise I recommend to stay close to what Google Photos is doing so people migrating feel familiar and because it is a de-facto standard. (Similar to how on iOS it should be like in Photos.)
