### ISSUE TITLE
Nextcloud Notifications don't show content of Notification

### ISSUE THREAD

**Issue by carlchen2007** [nextcloud/android#11824]
### ⚠️ Before posting ⚠️

- [x] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

I use my Nextcloud on a VM behind an NGINX reverse proxy and the two-factor authentication used to work well, but now a push notification with acceptance or rejection is no longer displayed when you try to log in, but only NEXTCLOUD NOTIFICATION. If I then go to the Nextcloud app and look under notifications, I also select the fields to choose from, but that gets annoying over time. Am I too stupid do I have to load any configurations in NGINX or is the error in my app?

### Expected behaviour

![Screenshot_20230720-215732](https://github.com/nextcloud/android/assets/119757558/e684e9e4-b888-47f4-a0ce-bbaa6ce1e435)

### Actual behaviour

![Screenshot_20230720-215820](https://github.com/nextcloud/android/assets/119757558/cb5693bc-c0a0-4add-a8e2-064043e8a2fa)

### Android version

11

### Device brand and model

Nokia 7.2

### Stock or custom OS?

Stock

### Nextcloud android app version

3.25.0

### Nextcloud server version

26.0.23

### Using a reverse proxy?

Yes

**Comment by joshtrichards** [comment]
Duplicate  of #1964 

@carlchen2007 - Thanks for your report. Please give #1964 a :+1: and add any additional relevant details or look for clues as to possible triggers/workarounds over in there #1964. If you agree your situation seems covered by #1964 please close this Issue out to avoid confusion. Thanks!

**Comment by joshtrichards** [comment]
Closing in favor of #1964
