### ISSUE TITLE
Auto upload: delete successful uploaded files after a given time

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#1182]
Received via mail:
Please add the setting, delete the uploaded photos over the specified period (for example, week, month, etc.)

This is useful when I took pictures, they need the first couple of days, and then they can be deleted, provided that they are uploaded to the server.

What is your opinion?

**Comment by sosed213** [comment]
Automatically delete photos from your smartphone. Some time still photos are needed on the smartphone, for transmission or demonstration. But after some time, not so much in demand, and it would be nice to have the ability to automatically delete photos from your smartphone, but provided that the photos are uploaded to the server.

**Comment by tobiasKaminsky** [comment]
Maybe we can enhance this into a whole "cleanup" action, where an user can select the folders he wants to clear and the time span.

**Comment by DaveBurkhardt** [comment]
I'm being pessimistic here; but I have yet to see the sync work with latest code (worked great prior).  At this point in time I'd not let the app delete the files.  The sync is broken for a lot of us.  very unreliable (doesn't work).  sometimes it randomly does.  (rare occasion now)

Hopefully you are one of the lucky ones where the sync's coding hooks work.

I have literally 100's (maybe 1000's) of photo's videos for months now which are only on my families local SD cards because I upgraded to latest version of this app.

Considering going to ownclouds app as this apps sync code is not very robust at this point in time.

...

That said I like the idea behind this feature request once they can make the sync solid.  IMO should be more like rsync with a local DB and hashes to track files.  You know what you have and haven't sent by a local DB on device.  Send differences on some keyed hook.

**Comment by sosed213** [comment]
I also have problems with uploading photos, and I hope that in the next version the developers will make the downloading more reliable.
A cleaning / deleting obsolete photos from the smartphone, you can only make sure that the photos are accurately downloaded to the server.
Nobody wants to lose the sealed moments, in a single copy.

**Comment by DaveBurkhardt** [comment]
I switched back to ownclouds client.  Works OK for now;  all photos/movies are uploaded for me now in my testing today.  Just an FYI.  I'll switch back once code looks to be good.

No sync is a critical flaw.  Also appears to not be at the forefront of the current push in the code which is somewhat perplexing.  If I find time I'll contribute to the code; I'm just crazy busy.

**Comment by mario** [comment]
Dear users,

thank you for your patience. After lots of work, we’re super excited to be able to give you a test version with new auto upload implementation. Keep in mind we will only accept bugs related to Auto Upload in this APK, as other things might be broken.

https://cloud.nextcloud.com/s/ftZraTruRQjTe0R

This is a dev APK so it will not overwrite your existing play store/f-droid APK unless you’re already running dev version. Also, you might need to remove your existing dev version before installing this one.

Explanation of the current functionality:
- added support for custom folders
- separated image and video folders
- checks for new files happens every 15-20 minutes
- automatic retry every 15-20 minutes or when you force close/open the app
- automatic pause once network is changed (untested!)
- significantly less battery usage

All and any testing is more than appreciated, especially with large and ever-going files like Videos. (like, try to record a 30 min video).

Let me know if you’ve got any questions.

Cheers,
Mario

**Comment by sosed213** [comment]
Loading is more confident.
Recorded the video for 30 minutes, and during the download to the server switched from wifa to mobile Internet and the file still loaded successfully, the size of 4.4 gigabytes.
It is good to split the loading of photos and videos into folders.

But I have been waiting for the new item in the automatic download settings:
The original file will be ... Removed, after a week (month).

**Comment by mario** [comment]
That is unlikely to happen for now. It's also a super-super strange thing to do, so definitely something that has to be discussed.

**Comment by sosed213** [comment]
The trouble. The application stopped working. Cyclically redirects to the authorization page. those. Enter the server address, login and password, and then the authorization page appears again.

**Comment by sosed213** [comment]
Reinstalling the program did not help. And deleting com.nextcloud.client just did not help.

**Comment by mario** [comment]
Closing since I don't think this will ever happen. cc @AndyScherzinger @tobiasKaminsky
