### ISSUE TITLE
dying project?

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/android#11847]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

@tobiasKaminsky @Andy

but the nextcloud android project is dying? does not receive updates since June 13 compared to the ios version.

moreover, it is not possible to delete files located in the e2e folders, no voice comes out, on pixel 6 pro android 13 version, also opened an issue but no response

there is no one who constantly follows the x android project anymore?

version 3.25.1 which was supposed to come out on the 13th we don't have a date, various problems that are chasing each other in the android version including the big one in my opinion impossibility to delete files in e2e folders, which works with the ios version.

Android 13 with pixel 6 pro.

Haven't received any updates in a month and 1/2

I ask is the project dying?

https://github.com/nextcloud/android/issues/11387

### Expected behaviour

update https://github.com/nextcloud/android/issues/11387

### Actual behaviour

https://github.com/nextcloud/android/issues/11387

### Android version

13

### Device brand and model

google

### Stock or custom OS?

Stock

### Nextcloud android app version

3.25.0

### Nextcloud server version

27.0.1

### Using a reverse proxy?

No

**Comment by joshtrichards** [comment]
Seems your query was answered here: https://github.com/nextcloud/android/issues/11734#issuecomment-1663411664

Please close this Issue out to avoid confusion. Thanks!
