### ISSUE TITLE
Instantupload setup templates

### ISSUE THREAD

**Issue by stratege1401** [nextcloud/android#11895]
For an unknow reason, i have a lot of folders on my smartphone.

I decided to re-use the android app so i am now the the process of choosing the folder to upload, and to choose the options
parameter/configure/
- Start the autoupload option
-  untick the WiFi only
- tick the use underfolder based on date
- tick delete the file 
- tick save

and i have A LOT OF FOLDER, and it is taking centuries to do it. How to change the option template so it is done for all - once

??

**Comment by joshtrichards** [comment]
Duplicate of #9163
