### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by c0fe** [nextcloud/android#119]
I would like make some suggestions to change the uploading UI to be more similar as to how it is in Outlook and Dropbox Android apps.

For example, whenever you upload something you get a better display choice:

https://www.dropbox.com/s/t08de241e6b4435/Screenshot_20160711-095124.png?dl=0

Additionally when you select photos (for example) you get to see the various albums or areas where the photos or screenshots might be stored:

https://www.dropbox.com/s/6vcghpgpe68cyve/Screenshot_20160711-095212.png?dl=0

Also what is helpful is to have thumbnail preview (or at least an option for this) when selecting images rather than the list view:

https://www.dropbox.com/s/01hfa0way69tem8/Screenshot_20160711-095314.png?dl=0

**Comment by przybylski** [comment]
Looks like most of those things is now handled by DocumentProvider, as long as client app is supporting such

**Comment by c0fe** [comment]
I am not particular certain if that's the case but that being said it would be a good idea IMO to implement it.

**Comment by tobiasKaminsky** [comment]
@c0fe this is already in the app. 
Please have a look and if it not fits your needs please explain them a little bit more.

**Comment by AndyScherzinger** [comment]
Any further input @c0fe ? :smiley:

**Comment by c0fe** [comment]
Working on adding those in. But there are apparently some issues with uploading things which I am in the process of working on.

**Comment by AndyScherzinger** [comment]
@c0fe are these points still valid/relevant? If so, can you re-add the screenshots and also add them right in this issue (drag&drop)?
