### ISSUE TITLE
Remember path when sharing to nextcloud

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#1191]
### Actual behaviour
- Path is set to an (unknown) other state

### Expected behaviour
- Path should remember the latest location
 
### Steps to reproduce
1. open an app e.g. gallery
2. share a file to nc
3. select any folder
4. repeat step 1-3

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by joshtrichards** [comment]
This seems to be the behavior today. At least it is for me in recent `master`.
