### ISSUE TITLE
Decks Android App Notifications

### ISSUE THREAD

**Issue by kagstrom2100** [nextcloud/android#11923]
How to use GitHub
Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
Subscribe to receive notifications on status change and new comments.

Is your feature request related to a problem? Please describe.
Some users in my Nextcloud instance don't use the WEB-GUI very often, but mostly the Android app and therefore won't see updates, etc on deck cards.

Describe the solution you'd like
Notifications like new comments on cards, or new card assignments to users via the Nextcloud Android app.

Describe alternatives you've considered
E-mail could work for some people, but in my instance we're not using email.

Additional context
Original post here: https://github.com/nextcloud/deck/issues/5071

**Comment by joshtrichards** [comment]
Hi @kagstrom2100 - As noted in the referenced issue, this is already supported for Android. And I just re-tested to confirm (e.g. comments. assignment) and it works for me.
