### ISSUE TITLE
Auto Upload for every file type ... why not?

### ISSUE THREAD

**Issue by devnull4242** [nextcloud/android#11945]
I currently wonder why Auto Upload can only upload media content and not arbitrary files. Are there honest reasons for this?

If not it would be nice if auto upload could transfer any files to Nextcloud. Why not? What's different about images than PDFs, for example? It also would be nice to auto upload my gpx tracks from [GPS Logger](https://play.google.com/store/apps/details?id=eu.basicairdata.graziano.gpslogger) Android directory to Nextcloud. They are small and i think there would be less problems than with pictures.

There could be an option that would allow auto upload of arbitrary files (gladly also limited to file sizes).

See also:
https://github.com/nextcloud/android/issues/2036
https://help.nextcloud.com/t/nextcloud-client-auf-android-system/169569

**Comment by AndyScherzinger** [comment]
Go to the top right menu in the Auto Upload screen and create a "custom folder" (menu item), configuring any kind of folder pair which then uploads any files from that folder. The presented folders are just easy options offered for the default use case of uploading images/videos.

**Comment by scr4bble** [comment]
Hi @AndyScherzinger, it does not seem to work for me (I will give it a bit more time but for now it doesn't seem to upload pdf files from the custom sync folder.

Now ignoring now whether it works or not, I think you should consider making this explicit in the settings interface. I would say the "custom folder sync settings" should allow to choose "upload all files" or "upload only photos/videos" ... and maybe additional option "upload folders inside recursively". Or if such functionality is chosen by default and cannot be changed, the settings should state that so it is clear for the user. I wouldn't know about how is it supposed to work if I haven't read these issues in github.
