### ISSUE TITLE
OSSEC: Multiple web server 400 error codes

### ISSUE THREAD

**Issue by nobody1407** [nextcloud/android#1194]
### Actual behaviour
I've installed OSSEC to protect the public server. If a user would like to rename a file, he get an error message and I get an email from OSSEC with "multiple web server 400 error codes from same source ip". Rename a file in the browser is working fine without error codes.

### Expected behaviour
without any error codes
 
### Steps to reproduce
1. install NC Server
2. install and start OSSEC
3. rename files with the app

### Environment data
Android version:
7.0 (SW-Nr: 2.41.401.4)

Device model: 
HTC 10

Stock or customized system:
stock

Nextcloud app version:
1.4.3

Nextcloud server version:
12.0.0

#### Web server error log
```
2017/07/15 07:28:51 [error] 652#652: *9967 open() "/usr/share/nginx/html/robots.txt" failed (2: No such file or directory), client: xxx.xxx.xxx.xxx, server: localhost, request: "GET /robots.txt HTTP/1.1", host: "www.mydomain.com"
```

#### Nextcloud log (data/nextcloud.log)
```
today no entries
```
#### OSSEC error message
```
Received From: debian->/var/log/nginx/access.log
Rule: 31151 fired (level 10) -> "Multiple web server 400 error codes from same source ip."
Src IP: xxx.xxx.xxx.xxx
Portion of the log(s):

xxx.xxx.xxx.xxx - USERNAME [15/Jul/2017:12:34:54 +0200] "GET /index.php/apps/files/api/v1/thumbnail/512/512/USER/FOLDER/FILE HTTP/1.1" 404 4387 "-" "Mozilla/5.0 (Android) ownCloud-android/1.4.3"
```

**Comment by tobiasKaminsky** [comment]
Do we support ossec @LukasReschke ?

**Comment by LukasReschke** [comment]
OSSEC is not supported. 400 is a status code which Nextcloud itself also returns on legit responses.
