### ISSUE TITLE
Account deletion mandatory from within Android apps

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#11950]
https://support.google.com/googleplay/android-developer/answer/13316080

Starting from December 2023 we need to have a way that user can trigger/ask for account deletion from within Android app.
A link would also be enough.

On Server side we do not yet have this, but I found https://apps.nextcloud.com/apps/drop_account
As this (or similar) must be working by December, we should put something at latest in NC28 in place, and probably "backport" it.

@tobiasKaminsky  @mahibi @ZetaTom 

---

> Account Deletion Requirement
>
>If your app allows users to create an account from within your app, then it must also allow users to request for their account to be deleted. Users must have a readily discoverable option to initiate app account deletion from within your app and outside of your app (e.g., by visiting your website). A link to this web resource must be entered in the designated URL form field within Play Console.
>
>When you delete an app account based on a user’s request, you must also delete the user data associated with that app account. Temporary account deactivation, disabling, or “freezing” the app account does not qualify as account deletion. If you need to retain certain data for legitimate reasons such as security, fraud prevention, or regulatory compliance, you must clearly inform users about your data retention practices (for example, within your privacy policy).
To learn more about account deletion policy requirements, please review this [Help Center](https://support.google.com/googleplay/android-developer/answer/13327111) [article](https://support.google.com/googleplay/android-developer/answer/10787469?hl=en). For additional information on updating your Data safety form, visit this article.

---
From @jancborchardt 

@tobiasKaminsky as you suggested we modify our existing "Remove account" dialog. I would go with 2 radio options:

Title: **Account removal**

[Here we should show avatar and name as feedback that you are looking at the correct account.]

> **Remove local account**
> Remove account from device and delete all local files

> **Request account deletion**
> Opens a website to start the process and deletes all local files

With "Cancel" and "Remove account" or "Request deletion" button (not just "Ok").

---

On drop_account app:

    expose capability that account can be deleted (e.g. no LDAP)

**Comment by tobiasKaminsky** [comment]
Capability of app: https://framagit.org/framasoft/nextcloud/drop_account/-/issues/25

**Comment by AndyScherzinger** [comment]
@ZetaTom @marcelklehr please see https://framagit.org/framasoft/nextcloud/drop_account/-/issues/25#note_2005909 for the solution and details. Publishing of the updated up to be in around 2 weeks time.

**Comment by tcitworld** [comment]
Version 2.3.0 has been published https://apps.nextcloud.com/apps/drop_account

**Comment by tcitworld** [comment]
> expose capability that account can be deleted (e.g. no LDAP)

Note : There's currently no way to know whether an account should be deleted on Nextcloud or if it should be done with an external source.

I excluded users from LDAP and SAML to keep only `'Database'` and `'Guests'` backends, but here's two remarks:
* there might be valid use cases to delete your Nextcloud account even though you're using a 3rd-party user directory. I could add some admin configuration to allow to override this.
* there's no real way to distinguish a regular Database user from one created through the `nextcloud-oidc-login` or `nextcloud-social-login` apps, so those users are allowed to be deleted even though they are kinda 3rd-party

**Comment by tcitworld** [comment]
Also the API to trigger direct deletion is documented if possible in the future : https://framagit.org/framasoft/nextcloud/drop_account/-/blob/main/openapi.json

**Comment by AndyScherzinger** [comment]
^ @ZetaTom

**Comment by AndyScherzinger** [comment]
Thanks a lot @tcitworld work the ongoing work on this! Highly appreciated! 💙

**Comment by appsfeature** [comment]
Solution: You need to develope a website to provide a control to the user for deleting there account from your server, Appsfeature is provide a solution on this.

https://appsfeature.github.io/account-deletion-policy-compliance
