### ISSUE TITLE
Wenn man Dateien über den Client synchronisiert und man z.B. viele Fotos auf dem Tablet hat (Android), aber auch welche auf dem Handy (Android) hat, die sich überschneiden, dann fragt die App bei jedem einzelnen Foto nach, ob die Version des Servers oder die eigene behalten werden soll. Es wäre himmlisch einen Button zu haben "für alle anwenden", also dass man eine Aktion für alle anwenden kann: z.B. man setzt für alle Fotos - behalte die Server Version.

### ISSUE THREAD

**Issue by Rolexander** [nextcloud/android#11964]
### Additional context

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by lckarssen** [comment]
This looks like a duplicate of #6459.

**Comment by AndyScherzinger** [comment]
You are all aware that this setting exists in the auto upload settings dialog for each folder add the bottom, right?
