### ISSUE TITLE
Large file uploads get to 100% then repeat upload again

### ISSUE THREAD

**Issue by grorico1** [nextcloud/android#11970]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Create a large file (sup 2Go) in a directory on the mobile device.
Configure nextcloud apps to automatically upload every file of the directory.

### Expected behaviour

When I use the manual upload I encounter no difficulty but when I use the automatic upload function then the file uploads at 100% then starts again and again endlessly.

 

### Actual behaviour

Idem

### Android version

13

### Device brand and model

Google 4s

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

3.25

### Nextcloud server version

23.0.12

### Using a reverse proxy?

Yes

**Comment by grorico1** [comment]
Hello,

Some additions:

Repeated sendings are due to the fact that the file transfer begins before the file has been completely generated. If I put myself in airplane mode while generating the file, there are no more repeated sending attempts. The file remains in error but only once.

Furthermore, if I try to upload the file manually everything works correctly.


Hope this helps.

Grorico.

**Comment by joshtrichards** [comment]
> Repeated sendings are due to the fact that the file transfer begins before the file has been completely generated. 

What is generating the file on your device?

**Comment by grorico1** [comment]
Signal messaging app.
