### ISSUE TITLE
In "Deleted files", simply replace "Delete" action wording with "Delete permanently" (to be consistent with web UI)

### ISSUE THREAD

**Issue by Jerome-Herbinet** [nextcloud/android#11984]
Hello,
Everything is a title. Simple wording change. 
I'm familiar with wording change on the web UI and the iOS app, but in this project, I don't know how (where) to do it.
Thanks !

**Comment by ezhil56x** [comment]
Hello @Jerome-Herbinet 👋🏻
I have changed **Delete** to **Delete permanently** in the Deleted Files
More about the implementation on the Pull Request Description

You can refer to the change I made here [https://github.com/nextcloud/android/commit/a14bd3ee3eb80051cea4f128d573701829226495](url)

I have created a new pull request for this change here #11986

**Comment by Jerome-Herbinet** [comment]
@ezhil56x 
LGTM and approved your PR if that's what you were waiting for me to do.
Thanks a lot !
