### ISSUE TITLE
Android app v 3.26.0 drains much more battery than before

### ISSUE THREAD

**Issue by lckarssen** [nextcloud/android#11983]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Upgrade Nextcloud Android app to v3.26.0. 
2. Use phone in the same way as before
3. Observe battery emptying more than before. The Nextcloud app is listed at the top of the list of battery consumers. 

### Expected behaviour

The Nextcloud app should be found somewhere at the bottom of the list of top power consumers.

### Actual behaviour

The app is found at the top of the list of battery power consumption. In my case it is now using roughly between 8% and 12% of battery, easily beating Firefox at ~7% and Always on Display at ~ 5%. 

### Android version

13

### Device brand and model

Samsung S22

### Stock or custom OS?

Stock

### Nextcloud android app version

3.26.0

### Nextcloud server version

27.1.0

### Using a reverse proxy?

Yes

**Comment by joshtrichards** [comment]
This seems related to https://github.com/nextcloud/android/issues/11974#issuecomment-1729361029 so let's focus on addressing that. If this matter remains afterward, we can re-open it.

**Comment by lckarssen** [comment]
> This seems related to [#11974 (comment)](https://github.com/nextcloud/android/issues/11974#issuecomment-1729361029) so let's focus on addressing that. If this matter remains afterward, we can re-open it.

The issue has remained, unfortunately. Instead of reopening this issue, I think follow-up in #7663 makes more sense.
