### ISSUE TITLE
Widget reporting "Nextcloud 25 needed" with Nextcloud 26 (but disabled Dashboard module)

### ISSUE THREAD

**Issue by brezelman** [nextcloud/android#11994]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Disable Dashboard module in your Nextcloud instance.
2. Use Nextcloud Android app to add a widget of that instance.

### Expected behaviour

App tells me to enable Dashboard module in my instance to be able to use widgets in the app.

### Actual behaviour

App tells me, that the instance requires to be of version 25 or above.

### Android version

12

### Device brand and model

Fairphone 4

### Stock or custom OS?

Stock

### Nextcloud android app version

3.25.0

### Nextcloud server version

26.0.5

### Using a reverse proxy?

I don't know

### Additional information

Exact error message in german:

> Nicht verfügbar
> Widgets sind nur auf Nextcloud 25 oder neuer verfügbar

**Comment by shashankiitbhu** [comment]
Hey, I would like to work on this issue, can you assign this to me?

**Comment by joshtrichards** [comment]
@shashankiitbhu Assignment isn't necessary. Just mentioning you're working on it is sufficient.

**Comment by wertzuz** [comment]
Updates?
