### ISSUE TITLE
Choose storage location: ui bug

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#11996]
![image](https://github.com/nextcloud/android/assets/5836855/c1e05768-989e-439f-8972-3802f3ed83a2)

**Comment by shreyanshR7** [comment]
what is the bug , can you please describe a bit?@tobiasKaminsky

**Comment by tobiasKaminsky** [comment]
The icons have white background, but should have transparent one.

**Comment by alperozturk96** [comment]
[PR](bugfix/choose-storage-location-ui-bug-11996) opened @tobiasKaminsky
