### ISSUE TITLE
create custom auto upload not working or not clear

### ISSUE THREAD

**Issue by dejoebad** [nextcloud/android#11997]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. create a custom folder auto upload.
2. save it.
3. boom blocked with close and disable button.
4. not working, cannot be sync.

### Expected behaviour

it should be save and sync

### Actual behaviour

nothing happened

### Android version

12

### Device brand and model

xiaomi poco f1

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

3.26.0

### Nextcloud server version

26.0.1

### Using a reverse proxy?

I don't know

**Comment by joshtrichards** [comment]
Can you provide a screenshot?
