### ISSUE TITLE
Update folder icons

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#11999]
Ref: https://github.com/nextcloud/files-clients/issues/46

**Comment by Abdullahkhanspn** [comment]
hey please assign to me i will do this work in 2 hours only please assign me @tobiasKaminsky

**Comment by tobiasKaminsky** [comment]
@Abdullahkhanspn I am sorry, it is already taken by @alperozturk96 , maybe you find another enhancement in our (long) issue list?
