### ISSUE TITLE
Move magic numbers in layout files to @dims

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#12]
### Actual behaviour
-many magic numbers in layout like 4dp, see review comments in #5 

### Expected behaviour
-move magic numbers like 4dp (widely used) to the dims.xml file as a constant

**Comment by sangeethakp** [comment]
Hi, I am a newbie FOSS Contributor. Can I start by contributing to this project-this bug first? Thanks!

**Comment by AndyScherzinger** [comment]
Hi @sangeethakp,  absolutely yes! We would be happy about that contribution :) 
Any questions, please let me and @tobiasKaminsky know.

**Comment by divayprakash** [comment]
Please ignore 	4ce8c61, a772bee and c01978d as they have been rebased in the next 3 commits due to issues with the commit msgs.

**Comment by divayprakash** [comment]
@AndyScherzinger @tobiasKaminsky #12 is done!

**Comment by AndyScherzinger** [comment]
Merged! :rocket: 
Again, Thanks for your contribution @divayprakash ! :+1:
