### ISSUE TITLE
User agent has changed

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/android#120]
I see that with https://github.com/nextcloud/android/commit/567375e860b456254a42d81f02b9ae8ee12fab01 the user-agent has changed to "nextcloud-android".

Can we change this back to "ownCloud-android"? There are regular expressions in the server that match for that :-)

**Comment by LukasReschke** [comment]
cc @AndyScherzinger

**Comment by AndyScherzinger** [comment]
PR created

**Comment by tobiasKaminsky** [comment]
@LukasReschke is this something very urgent so that we have to create a new release quickly or can it wait until our next regular release?

**Comment by LukasReschke** [comment]
> @LukasReschke is this something very urgent so that we have to create a new release quickly or can it wait until our next regular release?

Can wait. Mainly was used by the File Firewall (Enterprise feature in ownCloud) which we're also writing new (and of course open-sourcing!). But there is no code yet, so all fine :-)

**Comment by tobiasKaminsky** [comment]
So, then closing :+1:

**Comment by nickvergessen** [comment]
well we can also adjust the regex with the next major?

**Comment by AndyScherzinger** [comment]
to late ;) Plus this way the app stays compatible with ownCloud.
