### ISSUE TITLE
Android app to support GIFS and video thumbnail support (without downloadind to phone)

### ISSUE THREAD

**Issue by Blakestandal** [nextcloud/android#12001]
This is in regards to a closed post... https://github.com/nextcloud/android/issues/3125  a post that was never resolved and seems like others desired this feature (which is common among most other cloud drive platforms). 

### Actual behaviour

- Animated GIFs are broken- static images only. 

### Expected behaviour

- Should be playing _without_ downloading to the phone directly. to work exactly like onedrive or google drive...

### Steps to reproduce

- Install latest version and upload images. I personally use truenas scale and in my case the truecharts version of nextcloud. 

Browse files thru the Android app.

Android version: 13

Device model: samsung s22

Stock or customized system: Stock

Nextcloud app version: 3.26

Nextcloud server version:  (truecharts) 27.1.1_22.0.30

**Comment by satvik2131** [comment]
Hi I understood the issue and started working on it 👍😁

**Comment by Blakestandal** [comment]
> Hi I understood the issue and started working on it 👍😁

Bless you 🙏

**Comment by joshtrichards** [comment]
Unfortunately, this is not a client matter. The preview generation takes place at the server. The client can't display what it's not offered. The client receives static images from the server preview generator (that are also no longer gifs). 

Feel free to check for / open an issue in the server repository: https://github.com/nextcloud/server

Also see: https://github.com/nextcloud/android/issues/3125#issuecomment-428518145

If the server offered up animations in theory the client could be enhanced to show them.

Aside: My sense is that there is technical debt associated with the preview handling at the server level; it's probable that  a broader reengineering effort would be preferred before making bolt-on refinements for things like animated GIFs. Many of the things that would address are probably a higher priority first. For example, changing the default preview image format, boosting performance, abandoning some of the not well supported (or buggy) third party image generator libraries. Many of these would be helpful to ultimately bringing animation to previews (if someone wished to implement it), in theory. Disclaimer: I'm not terribly familiar with that area of code server-side so I'm only offering this last bit as my general impression.

**Comment by Blakestandal** [comment]
> Unfortunately, this is not a client matter. The preview generation takes place at the server. The client can't display what it's not offered. The client receives static images from the server preview generator (that are also no longer gifs).
> 
> Feel free to check for / open an issue in the server repository: https://github.com/nextcloud/server
> 
> Also see: [#3125 (comment)](https://github.com/nextcloud/android/issues/3125#issuecomment-428518145)
> 
> If the server offered up animations in theory the client could be enhanced to show them.
> 
> Aside: My sense is that there is technical debt associated with the preview handling at the server level; it's probable that a broader reengineering effort would be preferred before making bolt-on refinements for things like animated GIFs. Many of the things that would address are probably a higher priority first. For example, changing the default preview image format, boosting performance, abandoning some of the not well supported (or buggy) third party image generator libraries. Many of these would be helpful to ultimately bringing animation to previews (if someone wished to implement it), in theory. Disclaimer: I'm not terribly familiar with that area of code server-side so I'm only offering this last bit as my general impression.




Yeah I mean that all makes sense. It's just odd to me that there's no default to have a thumbnail generated for gifs and videos. I feel like this should be a very normal feature (all other cloud services do this).

I appreciate your time though!

**Comment by joshtrichards** [comment]
All the pieces of Nextcloud are free and open source - feel free to jump into some of the development discussions server-side and provide  input or assistance. Or help out somewhere else in some other way (i.e. if coding isn't your thing). It frees up dev resources so your favorite pet feature/functionality is more likely to get resources. :)
