### ISSUE TITLE
Support file versioning

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#1200]
Like in web UI: allow user to restore a previous version of a specific file.
If approved we need to create an issue for the public server API.

**Comment by AndyScherzinger** [comment]
Sounds good to me! 👍

**Comment by tobiasKaminsky** [comment]
Server issue: https://github.com/nextcloud/server/issues/4724

**Comment by jospoortvliet** [comment]
Merged in the server, coming in 14 btw :tada:

**Comment by AndyScherzinger** [comment]
Some housekeeping... implemented via #2685, so it'll be part of 3.3 :rocket: the upcoming feature release :tada:
