### ISSUE TITLE
Wrong icon overlay colors on OS theme

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#12023]
Dark mode:
<img width="540" alt="Screenshot_20231012_102804" src="https://github.com/nextcloud/android/assets/1315170/51e10c2f-0b34-47d2-a350-feb57d4d8503">

System setting:
<img width="540" alt="Screenshot_20231012_102818" src="https://github.com/nextcloud/android/assets/1315170/65b8cabf-7e77-435e-bc50-81a7c2e265bb">

Also not sure about the semi-transparency, should I think just be the background color for a punch out effect. In the current state I am not sure it would meed A11Y contrast requirements. cc @nimishavijay @jancborchardt

**Comment by alperozturk96** [comment]
@AndyScherzinger Did you select dark mode from app or phone's setting? Also could you share device model and Android version?

**Comment by joshtrichards** [comment]
Fixed in #12028
