### ISSUE TITLE
Behaves like a PWA instead of the actual NC App

### ISSUE THREAD

**Issue by Cybercube21** [nextcloud/android#12031]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Install the NC App on a Pixel 8 Pro
2. Be greeted by the NC app looking like a browser window of Nextcloud

### Expected behaviour

Actual NC App UI opens and i can use the App functionalities like auto upload, etc. like this:
https://imgur.com/a/s7GCfnc

### Actual behaviour

NC app looks like embedded browser window and you have 0 app functionalities:
https://imgur.com/a/HNz7Fq2

### Android version

14

### Device brand and model

Pixel 8 Pro

### Stock or custom OS?

Stock

### Nextcloud android app version

3.26.0

### Nextcloud server version

25.0.4

### Using a reverse proxy?

Yes

### Additional information

No Root access

**Comment by joshtrichards** [comment]
Hi @Cybercube21 - How, specifically, did you install the app?

**Comment by Cybercube21** [comment]
@joshtrichards I used the Google Play Store to install it. Later i joined the Beta program to see if the Beta will fix it on the new Phone, it sadly didnt aswell.

**Comment by joshtrichards** [comment]
Can you provide a screen shot that includes the bottom section of *App info* (i.e. everything under the heading "Store") for the Nextcloud app icon you're clicking on?

Right after you installed, were you prompted with the launcher screen that looks basically like these?
Stage 1: https://github.com/nextcloud/android/blob/eeb3dee028e835fd5d7f2e937b104b593ee7546c/app/screenshots/gplay/debug/com.nextcloud.client.FirstRunActivityIT_open_dark_blue.png
Stage 2: https://github.com/nextcloud/android/blob/eeb3dee028e835fd5d7f2e937b104b593ee7546c/app/screenshots/gplay/debug/com.nextcloud.client.AuthenticatorActivityIT_login.png

**Comment by Cybercube21** [comment]
Sure, heres the Version screenshot: https://imgur.com/a/mafJ89q
![Screenshot_20231016-171851](https://github.com/nextcloud/android/assets/45008576/09cefc96-695b-441c-97a6-c81c450e2f43)

And yes, i got the usual NC App Start screen, but i also had a weird interaction there as, instead of waiting for me to click on "Log in", "Sign up with provider" etc., it automatically goes to the login page where i have to type in my servers address + everytime i close the App again it logs me out instantly and i'd have to type in my servers address again and login again. (+ It didnt save my 2fa aswell)

**Comment by joshtrichards** [comment]
- Any chance you're using an untrusted/self signed HTTPS certificate?
- Do you have any other Nextcloud Android apps such as Notes or Deck? If so, can you see if they work correctly? (They depend on the main app).

**Comment by Cybercube21** [comment]
- Im using a Lets Encrypt Certificate
- I tried it with Notes but encountered the same problem since it wants me to log in the main app anyways. I sadly dont have the Deck App
Also like i said, it still works perfectly fine on my Pixel 6 Pro, even after reinstalling it on there i had no issues whatsoever. It really just seems to be on my Pixel 8 Pro

**Comment by joshtrichards** [comment]
That's... weird. Especially since both devices are Android 14.

What version of Android System WebView is installed on them? (It installs/update via the Play store; it's not coupled to the OS image).

**Comment by dsc-cryptostruct** [comment]
I have the Same issue

**Comment by joshtrichards** [comment]
@dsc-cryptostruct Android 14 as well?

**Comment by joshtrichards** [comment]
I just noticed you're using NC Server v25.0.4:

- That's *really* old (and unpatched). There were some web login flow related bugs fixed since then server-side. Any chance you can update your server? 
- Alternatively, can you reproduce this behavior with your client(s) against https://try.nextcloud.com ?

**Comment by Cybercube21** [comment]
Sorry for the late answer, i did try it on a nextcloud from a friend of mine and it did work normal as intended
