### ISSUE TITLE
GPS info in metadata getting lost when using nextcloud android app

### ISSUE THREAD

**Issue by mrcg** [nextcloud/android#12040]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Images transferred with nextcloud android app are loosing GPS info in metadata.
The exact same image (or movie) on smartphone transferred with any other app (e.g. Solid Explorer) show the GPS information in metadata.
For some reason the GPS info is removed when synching the data with nextcloud android app.

I am quite confident that it's caused by bug in the nextcloud android app.
Because when i am using the Solid Explorer app on the smartphone (which supports also nextcloud) and transfer the image to nextcloud server then the GPS data remains in the image.

I realized this issue because i am importing the images from nextcloud into Adobe Lightroom which is showing small icon when GPS info is included.

![nextcloud_Forum](https://github.com/nextcloud/android/assets/4404991/73b61334-27fc-41c4-b0b6-16c7e00611dc)

### Expected behaviour

GPS info from image (or movie) should remain in metadata when using nextcloud android app.

### Actual behaviour

GPS info is getting lost from image (or movie) after transfer with nextcloud android app.
Using any other android app to transfer the data shows that GPS info remain in the image (or movie).

### Android version

v13

### Device brand and model

Samsung Galaxy S23

### Stock or custom OS?

Stock

### Nextcloud android app version

3.26.0

### Nextcloud server version

27.1.2

### Using a reverse proxy?

No

**Comment by joshtrichards** [comment]
Hi @mrcg - Thanks for your report and contribution. Take a look at #6248 which is your situation I believe. There's extensive discussion there.
