### ISSUE TITLE
Missing strings: Settings

### ISSUE THREAD

**Issue by comradekingu** [nextcloud/android#1207]
version 20170713

![missingstrings](https://user-images.githubusercontent.com/13802408/28328328-87856494-6be6-11e7-9447-74194b8ca0d5.png)

------

1. "Daily backup of your contacts"
https://github.com/nextcloud/android/blob/master/src/main/res/xml/preferences.xml#L114
2. "Download latest dev version"
3. "Changelog dev version"

Edit: @tobiasKaminsky: … the first both strings are from dev and so are not included into values/strings, thus not ready for transifex. but the latest one should be there...

**Comment by AndyScherzinger** [comment]
PR is #1208

**Comment by AndyScherzinger** [comment]
@comradekingu merged to master, so it will be translate-able by tomorrow when it got pushed to transifex.
