### ISSUE TITLE
Nextcloud Dev 20170718: Cannot add second account.

### ISSUE THREAD

**Issue by OlivierS1** [nextcloud/android#1209]
### Actual behaviour
-Tell us what happens
Trying to add a second account on Nexctloud Dev, fails.
The Add account page now only included the "server address https://" line. The Account and password filed are no longer present.
When entering the server address and clicking on the right pointing arrow, the "Testing connection" shows up briefly and  Nexctloud is updating the display with a blank page. Normaly, the page would show the certificate details and would provide the user with a choice.
From this point on, nothing can be done and adding account is not possible.

As this was an update, I am not sure if the issue would be reproducible with no account yet.

### Expected behaviour
-Tell us what should happen
 
### Steps to reproduce
1. Select "Add account"
2. Enter server address and press "->"
3. 

### Environment data
Android version:
6.0

Device model: 
LG G3

Stock or customized system:
Stock

Nextcloud app version:
NC Dev 20170718

Nextcloud server version:
NC 12.0

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by jgrete** [comment]
Hi, 
I can this behaviour! In fact I cannot add a single account if I've installed with f-droid.

**Comment by tobiasKaminsky** [comment]
I suppose both of you use "untrusted" certificates, e.g. something that has to be manually approved via the dialog?
I fixed it the day before yesterday in dev branch, but it will take quite some time until fdroid builds it :-/
It will also be tomorrow in the downloadable link (see below).

So either wait some days for fdroid or give https://download.nextcloud.com/android/nightly/latest.apk a try (note that you have to uninstall the fdroid version before)

**Comment by jgrete** [comment]
Yes, you're right! I'll try the latest.apk
Thanks

**Comment by jgrete** [comment]
No luck. After the URL I'm asked to trust the selfsigned cert and than the screen goes white...

**Comment by tobiasKaminsky** [comment]
> It will also be tomorrow in the downloadable link (see below).

The dev version is built midnight, german time, so you can try it tomorrow. I hope this is early enough ;-)

**Comment by jgrete** [comment]
Yes, it is :-)

**Comment by OlivierS1** [comment]
@tobiasKaminsky It does work now, but there is a small question/concern about the login process.
I normally create an app-password for all my applications and accounts, and this approach requires me to login with my normal password then go through OTP then create the app password which I then use for Nextcloud app on the phone.
As I was going through the process, I noticed the app-password was created when I setup the account on Nextcloud Dev app version 20170721.
Can you confirm the app password has really been created?
Is there a post showing the process in details?

**Comment by mario** [comment]
This is indeed true.

**Comment by OlivierS1** [comment]
@mario Trying once more, I noticed I have a choice between what seem to be the normal login and the Alternative login using app token.
What are the differences?

**Comment by OlivierS1** [comment]
@mario I think I can answer that for myself as I tried both options:

1) Normal login:
I use my normal password and go through OTP.
NC Dev request from server a new app-password and give it my phone designation.
NC Dev store the newly 16+ character password from server and use that to login the app from now on.

2) Login with app token:
I log into server via web interface.
I create the app-password.
I go back to NC Dev and paste the app-password newly created.
The end.

Am I missing something?
It seems trying to setup the account with token login and entering my normal password is unsuccessful. This is what I would have expected. Is this really what is happening?

**Comment by tobiasKaminsky** [comment]
If you use TOTP (https://github.com/nextcloud/twofactor_totp) you have to use the app passwords:

https://github.com/nextcloud/twofactor_totp#login-with-external-apps:
> Once you enable OTP with Two Factor Totp, your aplications (for example your Android app or your GNOME app) will need to login using device passwords. To manage it, know more here

So, it works as expected, or?

**Comment by mario** [comment]
Actually normal login now provisions app passwords if you are on NC12 so
you can use TOTP without an issue.

**Comment by jgrete** [comment]
I was not successful, partly... I was able to create a login on one of my two servers. On the other I could enter my credentials (after accepting selfsigned cert) and touch the login button but nothing happens. The button stays responsive (it changes its colour on touch) but nothing more. I tried this a couple of times, no success. The log on the server does not show any related entries.
BTW should I open a separate issue?

**Comment by tobiasKaminsky** [comment]
@jgrete strange, can you create a test account and mail the credentials to android at nextcloud dot com with a reference to this issue? Then I can have a look.

**Comment by jgrete** [comment]
Hi, 
I just was about to do that but to be shure I tried it with the today latest.apk (24.07.) - and it works ...
Sorry for the "false positive" . I did some updates (apps and a new LineageOS flash at the weekend). May be this had some effects.
Thanks a lot
Jürgen

**Comment by tobiasKaminsky** [comment]
Glad to hear, please re-open if it occurs again.
