### ISSUE TITLE
Overlapping text elements in UI when Android Display size (zoom) is set high

### ISSUE THREAD

**Issue by notsouren** [nextcloud/android#12107]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Just open the app and look at the sidebar and you will see the remaining spac text covers the menus
Or sometimes open the Documents folder.
Text appear over another without any layer to separate them 

### Expected behaviour

Text to not appear over another!

### Actual behaviour

Texts appearing over another 
![Screenshot_2023-10-30-18-17-25-55_06ea656a9ba653ff96746f477f32d0f9](https://github.com/nextcloud/android/assets/66199690/3662ce43-f3e4-4df1-bf91-810c0bd192df)

![Screenshot_2023-10-30-17-35-33-11_06ea656a9ba653ff96746f477f32d0f9](https://github.com/nextcloud/android/assets/66199690/8d5c9b34-c96e-44a4-94ee-1ca3b1398921)

### Android version

13

### Device brand and model

Oppo A96

### Stock or custom OS?

Stock

### Nextcloud android app version

latest

### Nextcloud server version

latest

### Using a reverse proxy?

No

**Comment by joshtrichards** [comment]
Hi @notsouren - I was able to reproduce this on a Pixel 7, but only after modifying the default Android settings. This happens if one customizes their Android system *Display size* (zoom) parameter to the second from the last (highest) setting.From the looks of it the Oppo A96 has fairly similar screen size/resolution as the Pixel 7, so I suspect this is the trigger for this behavior in your situation.

**Comment by notsouren** [comment]
I am using all the default settings for fone and screen size.

**Comment by joshtrichards** [comment]
Can you please provide a screenshot from your Android *Settings*->*Display*->*Display size and text* section?

**Comment by notsouren** [comment]
Sure

**Comment by notsouren** [comment]
Haha! Yeah I was replying to the email! Sorry my bad. So these are the defaults, anything smaller is literally the size of ants!

![Screenshot_2023-10-30-23-34-39-62_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/nextcloud/android/assets/66199690/98bb176c-b5a1-46fd-9552-9e045089ba7d)

![Screenshot_2023-10-30-23-34-32-14_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/nextcloud/android/assets/66199690/f3413580-293f-4128-b57f-3ff05efe83c1)

**Comment by notsouren** [comment]
Hold on! I reinstalled my container and also disabled a whole bunch of apps
in NC and it's not doing that anymore!
