### ISSUE TITLE
Nextcloud Dev 20170718: Thumbnails are not persistent.

### ISSUE THREAD

**Issue by OlivierS1** [nextcloud/android#1211]
### Actual behaviour
-Tell us what happens
In grid view, visualizing a folder with pictures, the thumbnails start getting updated, but the update process may cause the same image to toggle from icon to image thumbnail a few times before stabilizing.
Upon scrolling up or down, the pictures will not retain their thumbnail and revert back to icons. Waiting a little bit and the thumbnail will refresh.
This is very similar to
https://github.com/nextcloud/android/issues/596

### Expected behaviour
-Tell us what should happen
 Thumbnail should be persistent.

### Steps to reproduce
1. Open any folder contianing images.
2. Select grid view
3. scroll up and dwon within the folder.

### Environment data
Android version:
6.0
Device model: 
LG G3
Stock or customized system:
Stock
Nextcloud app version:
NC Dev 20170718
Nextcloud server version:
NC 12.0
#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Thank you for your feedback!
I fixed it and it should be available in next dev version, and sometimes later in fdroid.

**Comment by OlivierS1** [comment]
@tobiasKaminsky It is working nicely now.
One thing I would like to add, and maybe this is best to set for a new ticket, but I noticed (not specific to this version) that only document place holders (thumbnail not yet updated) do not get processed unless they appear on the screen.
What I mean by that is if I have let say 100 pictures and only the first 5 are showing, their corresponding thumbnails are going to be updated because they are within the view area. The following pictures will not be updated unless the content is being scrolled down and enough time has past for NC Dev to fetch the data from the server.
If I scroll very quickly down to the last set of pictures, they will be updated. A few pictures between the first and the last can be updated as well, but most of the folder will still remain unpopulated bu updated thumbnail images.
I have a network activity overlay on my phone and I see when and if transfer occur, but for a folder containing a large number of pictures or documents, once the thumbnails have been populated for the documents that appear on the main screen, the network usage goes down. 

Are there any plans of prefetching the rest of the folder so that scrolling down the folder the pictures are already populated?
Are there any plans on prefetching the entire account while phone is not in use?

**Comment by tobiasKaminsky** [comment]
Please open up a new issue for this, so we can discuss this and maybe, find an improvement and then the issue can remain open until it is implemented.
