### ISSUE TITLE
Synced Files Deleted From Phone After Short While

### ISSUE THREAD

**Issue by gohrner** [nextcloud/android#12122]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Syncronize a bigger folder from Nextcloud to the phone

### Expected behaviour

The synced files stay available offline indefinitely.

### Actual behaviour

The files disappear from the phone again after a while and are no longer shown as "synced" (and also are not available any more e.g. in the photo gallery, in my case Google Fotos, not logged in and without any syncing)

### Android version

13

### Device brand and model

Samsung A52

### Stock or custom OS?

Stock

### Nextcloud android app version

observed with 3.24.2

### Nextcloud server version

unsure which it was at the time

### Using a reverse proxy?

Yes

### Additional information

We experienced this problem for quite a while until we asked about it in the Nextcloud forum:
https://help.nextcloud.com/t/android-app-3-24-2-synced-files-deleted-from-phone-after-short-while/161571/1

Meanwhile there was at least one confirmation from a different user who also experienced it.

Meanwhile, we seem to have found a workaround - there were several settings in Android (or maybe Samsung extensions?) regarding “saving storage space for incative apps”. Not sure how they were called in detail, but it was two or three different settings, some related to the app cache, some to application data.

We disabled all of these for the Nextcloud client and now the synced files stay. We’re not sure which one of these settings actually did the trick, but didn’t invest any further time either - we wasted enough of it on the issue already. :frowning:

So it seems to be some Android cleanup feature, but it would be really good if the Nextcloud app could warn prominently about it and provide instructions on how and where to disable this stuff…

Most regular users would simply come to the conclusion "this stupid app just doesn't work" and quickly turn to some other syncing / cloud storage solution, which is unfortunate.

**Comment by joshtrichards** [comment]
What do you have your Data Storage Folder set to?

And can you browse to that folder in your phone's Files app directly?

In Google Photos:

- How precisely are you accessing the NC synced photos? I guess *Library* --> *Photos on device* --> *View all* --> selecting a folder? 
- When you do that and look at one of the photos that disappears repeatedly, check the *Details* and where does Google Photos see the file stored?

P.S. I assume you Google Photos built-in Backup option disabled, correct?

**Comment by gohrner** [comment]
@joshtrichards: Thanks for your quick reaction.

The fotos appear in the Google Photo app "main page", i.e. directly after opening it.

So if I just open the app (and in this case scroll down a bit because the photos are not too recent), I'll see:

![image](https://github.com/nextcloud/android/assets/26199042/b596a8ab-131a-4a54-840a-c6943ecaa9a1)

These photos were synced from Nextcloud.

The details for e.g. the image in the top left corner of the previous screenshot look as follows:

![image](https://github.com/nextcloud/android/assets/26199042/ce91d42d-452b-415e-af00-a0227d1af3ff)

Regarding Google Photos "Backup", you're right, its disabled, and no account is logged in / connected.

The "automagic removal" of the synced images is either a feature of later Android's or something Samsung specific - the other user in the forum also uses a Samsung, and I've never experienced deleted images / files on a Nokia 8 Sirocco with Android One, Android version 10.

The Samsung A52 described above isn't my device - as my Nokia had hardware issues, I recently switched to a Fairphone 5 with Android 13, but was not brave enough to leave the Nextcloud "storage saving" settings on default settings, but disabled them all. With this setting I also didn't encounter any deleted data on my Fairphone.

**Comment by joshtrichards** [comment]
> The "automagic removal" of the synced images is either a feature of later Android's or something Samsung specific - the other user in the forum also uses a Samsung, and I've never experienced deleted images / files on a Nokia 8 Sirocco with Android One, Android version 10.

Possibly this? https://r2.community.samsung.com/t5/Tech-Expert/How-to-easily-manage-your-storage-with-storage-booster/td-p/13439516
