### ISSUE TITLE
Revamped detail screen, part 2

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#1212]
PR #1156 is a real great UI enhancement.
During review I found new ideas, which we should discuss
- make shared link clickable -> open up same "sharing link" dialog as in shared dialog
- click on user opens up detailed sharing option for this user
- show a "x" to remove an user very fast from the sharees

@AndyScherzinger @jancborchardt

**Comment by AndyScherzinger** [comment]
Sounds good to me and would further improve the screen 👍

**Comment by jancborchardt** [comment]
> show a "x" to remove an user very fast from the sharees

We should do it exactly like the share view on the server, with a dropdown including the available permission options and ability to remove them.

**Comment by jancborchardt** [comment]
Right, I have to add: We should merge the Details screen and the Share view, to be exactly like the right sidebar in files. Details on top (smaller filetype icon, move technical info to one row) and things like »Sharing« and »Activity« (with comments, versions and changes) in a tabbed view.

Otherwise we duplicate stuff, like where you can unshare and view who it’s shared with. For example in this view it’s confusing that you can not add new people.

**Comment by AndyScherzinger** [comment]
Sounds good to me. Questions for clarification:

* what do you mean by technical info and shouldn't that then be another tab with file info?
* how do we handle getting to the action(s): right now we have 2 actions "details" and "share", with this change both would navigate to the details screen with the tabs for sharing, activity etc.  Is this fine by everyone. Id say if possible we should then keep the menu entries and display the fitting tab (e.g. if share has been chosen the share tab is the active one, not activity or any other). 
* where should we then put the "set available offline" elements

**Comment by jancborchardt** [comment]
Technical info: file type (should be removed completely as we have the extension), size, and date.

The top part should basically exactly be like the list view, with favicon/preview, filename right next to it and size and date in one line under the filename

"Details" would go to a to-establish activity/comment/versions tab called "Activity" like in the web interface.
"Sharing would go to the Sharing tab.
Those are the only two tabs (we need to merge activity/comments/versions in the server still …)

Set available offline we could keep where it is, under the header part and above the tabs. Let's discuss at the conf if we want to move it.

**Comment by AndyScherzinger** [comment]
PR for mime type removal on file details screen: #1632

**Comment by AndyScherzinger** [comment]
closed. successor is: #2485
