### ISSUE TITLE
"No files here" on fresh install

### ISSUE THREAD

**Issue by mj8w** [nextcloud/android#12136]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

 Installed freshly on my Android phone.
nextcloud web view shows a number of files already synced, I can browse them.
Android app shows "No Files Here".
The + button is gray and does not work.

### Expected behaviour

Expected to see a few folders, especially the ones that nextcloud puts in by default.
Expected I should be able to add a folder to sync.

### Actual behaviour

"No Files Here" is showing on the android app. + button is grayed out.

### Android version

12

### Device brand and model

Pixel 3a XL

### Stock or custom OS?

Stock

### Nextcloud android app version

3.26.0

### Nextcloud server version

27.1.3

### Using a reverse proxy?

No

### Additional information

I do not have a dev version

**Comment by joshtrichards** [comment]
What does your server-side `nextcloud.log` (or equivalent) indicate about these transactions with the client app?

Also, are you using SSL and/or a reverse proxy?

**Comment by mj8w** [comment]
nothing at all in /var/www/nextcloud/data/nextcloud.log
No to SSL, no reverse proxy but I am using wireguard
I was able to add calendar and contacts on the android app, and so those
files show up in the files view on the android app now, but they don't show
up on Files on the web view.

**Comment by joshtrichards** [comment]
In that case, can monitor your web server logs and see what transactions come in when you open the Android client? Please provide a sample of them.

Any chance you moved from another phone?

After you installed the Android client, were you taken through the normal setup wizard to add an account?

**Comment by mj8w** [comment]
access.log when starting the android app:

192.168.1.10 - mike [06/Nov/2023:23:47:55 +0000] "GET
/nextcloud/ocs/v2.php/apps/user_status/api/v1/user_status?format=json
HTTP/1.1" 200 5257 "-" "Mozilla/5.0 (Windows) mirall/3.10.1stable-Win64
(build 20231025) (Nextcloud, windows-10.0.22621 ClientArchitecture: x86_64
OsArchitecture: x86_64)"
192.168.1.10 - mike [06/Nov/2023:23:47:55 +0000] "GET
/nextcloud/ocs/v2.php/apps/notifications/api/v2/notifications?format=json
HTTP/1.1" 304 5100 "-" "Mozilla/5.0 (Windows) mirall/3.10.1stable-Win64
(build 20231025) (Nextcloud, windows-10.0.22621 ClientArchitecture: x86_64
OsArchitecture: x86_64)"
192.168.1.10 - mike [06/Nov/2023:23:47:56 +0000] "PROPFIND
/nextcloud/remote.php/dav/files/mike/Documents HTTP/1.1" 207 5402 "-"
"Mozilla/5.0 (Windows) mirall/3.10.1stable-Win64 (build 20231025)
(Nextcloud, windows-10.0.22621 ClientArchitecture: x86_64 OsArchitecture:
x86_64)"
192.168.1.10 - mike [06/Nov/2023:23:47:58 +0000] "GET
/nextcloud/ocs/v1.php/cloud/user?format=json HTTP/1.1" 200 1334 "-"
"Mozilla/5.0 (Windows) mirall/3.10.1stable-Win64 (build 20231025)
(Nextcloud, windows-10.0.22621 ClientArchitecture: x86_64 OsArchitecture:
x86_64)"
10.202.222.2 - mike [06/Nov/2023:23:47:58 +0000] "GET
/nextcloud/ocs/v2.php/cloud/user?format=json HTTP/1.1" 200 6689 "-"
"Mozilla/5.0 (Android) Nextcloud-android/3.26.0"
192.168.1.10 - mike [06/Nov/2023:23:47:58 +0000] "GET
/nextcloud/remote.php/dav/avatars/mike/128.png HTTP/1.1" 200 2480 "-"
"Mozilla/5.0 (Windows) mirall/3.10.1stable-Win64 (build 20231025)
(Nextcloud, windows-10.0.22621 ClientArchitecture: x86_64 OsArchitecture:
x86_64)"
10.202.222.2 - mike [06/Nov/2023:23:47:58 +0000] "GET /nextcloud/status.php
HTTP/1.1" 200 5293 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.26.0"
10.202.222.2 - mike [06/Nov/2023:23:47:58 +0000] "GET /nextcloud/status.php
HTTP/1.1" 200 1329 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.26.0"
10.202.222.2 - mike [06/Nov/2023:23:47:58 +0000] "GET
/nextcloud/ocs/v2.php/cloud/capabilities?format=json HTTP/1.1" 304 728 "-"
"Mozilla/5.0 (Android) Nextcloud-android/3.26.0"
10.202.222.2 - mike [06/Nov/2023:23:47:58 +0000] "GET
/nextcloud/ocs/v2.php/cloud/capabilities?format=json HTTP/1.1" 304 728 "-"
"Mozilla/5.0 (Android) Nextcloud-android/3.26.0"
10.202.222.2 - mike [06/Nov/2023:23:47:59 +0000] "GET
/nextcloud/ocs/v2.php/apps/user_status/api/v1/predefined_statuses?format=json
HTTP/1.1" 200 6452 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.26.0"
10.202.222.2 - mike [06/Nov/2023:23:47:59 +0000] "GET
/nextcloud/ocs/v2.php/apps/user_status/api/v1/predefined_statuses?format=json
HTTP/1.1" 200 6447 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.26.0"
10.202.222.2 - mike [06/Nov/2023:23:47:59 +0000] "GET
/nextcloud/ocs/v2.php/cloud/user?format=json HTTP/1.1" 200 6688 "-"
"Mozilla/5.0 (Android) Nextcloud-android/3.26.0"
10.202.222.2 - mike [06/Nov/2023:23:47:59 +0000] "GET
/nextcloud/ocs/v2.php/cloud/user?format=json HTTP/1.1" 200 6693 "-"
"Mozilla/5.0 (Android) Nextcloud-android/3.26.0"
10.202.222.2 - mike [06/Nov/2023:23:47:59 +0000] "PROPFIND
/nextcloud/remote.php/dav/files/mike/ HTTP/1.1" 207 2019 "-" "Mozilla/5.0
(Android) Nextcloud-android/3.26.0"
10.202.222.2 - mike [06/Nov/2023:23:47:59 +0000] "PROPFIND
/nextcloud/remote.php/dav/files/mike/ HTTP/1.1" 207 2019 "-" "Mozilla/5.0
(Android) Nextcloud-android/3.26.0"
10.202.222.2 - mike [06/Nov/2023:23:48:00 +0000] "PROPFIND
/nextcloud/remote.php/dav/files/mike/ HTTP/1.1" 500 934 "-" "Mozilla/5.0
(Android) Nextcloud-android/3.26.0"
10.202.222.2 - mike [06/Nov/2023:23:48:00 +0000] "PROPFIND
/nextcloud/remote.php/dav/files/mike/ HTTP/1.1" 500 934 "-" "Mozilla/5.0
(Android) Nextcloud-android/3.26.0"
::1 - - [06/Nov/2023:23:48:06 +0000] "OPTIONS * HTTP/1.0" 200 126 "-"
"Apache/2.4.57 (Debian) OpenSSL/3.0.11 mod_wsgi/4.9.4 Python/3.11 (internal
dummy connection)"
192.168.1.10 - - [06/Nov/2023:23:48:07 +0000] "GET
/nextcloud/ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 304
5100 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
(KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"
192.168.1.10 - - [06/Nov/2023:23:48:07 +0000] "GET
/nextcloud/ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 304
5098 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
(KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"
192.168.1.10 - - [06/Nov/2023:23:48:07 +0000] "GET
/nextcloud/ocs/v2.php/apps/dashboard/api/v2/widget-items?widgets%5B%5D=activity
HTTP/1.1" 200 5379 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64)
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"
192.168.1.10 - - [06/Nov/2023:23:48:07 +0000] "GET
/nextcloud/index.php/apps/files/api/v1/stats HTTP/1.1" 200 5269 "-"
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
Gecko) Chrome/119.0.0.0 Safari/537.36"

So the whole history is that I built nextcloud on a raspberry pi, and
connected to it using my phone (and I had it working). I ran into some
problems with the server and decided to remove the app from my phone, then
later decided to start over and try to install the system afresh. After
nextcloud was installed and working well (took me a couple of attempts),
then I re-installed on my phone, which is when I ran into this issue. I
tried uninstalling and then re-installing the android app, but came up with
the same condition, which is when I filed the bug report.

The install wizard ran fine both times I installed the android app.

Thanks so much for looking at this for me.

Mike

**Comment by joshtrichards** [comment]
> 10.202.222.2 - mike [06/Nov/2023:23:48:00 +0000] "PROPFIND /nextcloud/remote.php/dav/files/mike/ HTTP/1.1" 500 934 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.26.0"
10.202.222.2 - mike [06/Nov/2023:23:48:00 +0000] "PROPFIND /nextcloud/remote.php/dav/files/mike/ HTTP/1.1" 500 934 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.26.0"

These 500 errors indicate a problem server-side. The issue here isn't the "No files here" but whatever is configured/broken in your environment. You're going to need to dig a bit to figure out what's going on. If they're coming from Nextcloud you'll definitely see the cause in the Nextcloud log. If they're not getting that far, your web server error log should have some hints. I suggest posting your server configuration details - and finding those logs - at the Nextcloud Help Forum - https://help.nextcloud.com.
