### ISSUE TITLE
A New Design Proposal For Grid Mode View

### ISSUE THREAD

**Issue by alperozturk96** [nextcloud/android#12143]
### Issue

When the grid mode is active, the icons in the corners of the files are not easy to access. In addition, the design of the web interface does not match the mobile app.

### Proposal

We need to have the same design language between iOS, Android and Web versions.

Showing multiple icons is not suitable for mobile devices, instead we can just put the ellipsis icon at the bottom right. When the user presses it, we can open the bottom-sheet and show the necessary information (favorite or not?, previously downloaded, comments etc.) on that bottom-sheet.

@nextcloud/designers @AndyScherzinger @tobiasKaminsky  

Android

<img width="347" alt="android" src="https://github.com/nextcloud/android/assets/67455295/d5c983d3-7314-4d52-abf1-d61ab72b9a89">

Web

<img width="336" alt="web" src="https://github.com/nextcloud/android/assets/67455295/79273b61-0fbb-4ab4-8f9c-b971b0661b1a">

**Comment by AndyScherzinger** [comment]
GDrive
<img width="540" alt="Screenshot_20231108_144531" src="https://github.com/nextcloud/android/assets/1315170/7e680cd0-6c9a-4827-bd90-0c61671db40e">

Just displays them in a container as an info, so that would be an option, anything "actionable" is in the 3-dot menu opening a bottom sheet. So I think this would be a nice way to handle it

**Comment by jancborchardt** [comment]
Agree with @AndyScherzinger, the icons can be smaller as they are not actionable, and that way they don't overshadow the content so much. And we then only have one place of displaying them.

(Btw slightly related: video previews could get border-radius like images.)

**Comment by alperozturk96** [comment]
@AndyScherzinger @jancborchardt 

It looks nice and we can do something like this instead of the clickable icons in our app. We need to remove the actions from the icons and make them accessible with 3 dots. Live Photo feature should be independent of the new design and we should add this design suggestion as a new feature.

**Comment by AndyScherzinger** [comment]
Sounds good to me @alperozturk96 👍
