### ISSUE TITLE
Browse, load, save images and files from/to File browser like in iOS Files app.

### ISSUE THREAD

**Issue by kintaro1981** [nextcloud/android#12140]
### Is your feature request related to a problem? Please describe.
I can't load nextcloud files and images from other apps.
I used for months ios nexcloud app and I loved how seamless it integrate with iOS.
From the file browser and other app I was able to access nextcloud "file system" to load files and images directly from it, in Android I cant. 

### Describe the solution you'd like
On iOS was super simple and straightforward. Nextcloud was available in Files app and in other apps from which choose images and files. I would like to have the same feature on Android too.

### Describe alternatives you've considered
can't find alternatives

**Comment by joshtrichards** [comment]
I mean... It's there. We support it. 

On my Pixel 7, for example, I can open Gmail and 
browse Nextcloud for the file. And any apps that support the standard Android Storage Access Framework will let me pick Nextcloud (or any cloud provider installed for that matter).

What apps are you testing with?

**Comment by kintaro1981** [comment]
Yes, you are right.

I was trying with instagram and facebook but it seams I have to blame them and not Nextcloud.
Probably they are not (don't want) supporting Android Storage Access Framework.

I tried with an email client app and I attached a file browsing nextcloud files from within the email app.

Thank you for your patience.
