### ISSUE TITLE
Calendar not available from eco-system apps integration

### ISSUE THREAD

**Issue by aliceell** [nextcloud/android#12156]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

When I open the sidebar in the Android app, the calendar is not available. I cannot find it anywhere in the app.

Clicking on "More" opens the Google Play store for the Nextcloud app, rather than showing me other availble Nextcloud features.

### Expected behaviour

The calendar works fine and is accessible in the browser version of NextCloud but seems to be unavailable in the app.

### Actual behaviour

See above. This has happened to other users in our server, not just me. Some are able to access the calendar and others aren't.

### Android version

12

### Device brand and model

Samsung Galaxy S10e

### Stock or custom OS?

Stock

### Nextcloud android app version

3.26.0

### Nextcloud server version

There is no "About" setting in the top right corner.

### Using a reverse proxy?

No

### Additional information

I cannot root my device as it is not mine, and I cannot access logs without root.

However I have attached pictures of what my sidebar looks like. When I tap "more" (circled), it takes me to the Google Play Store for Nextcloud.

![Screenshot_20231112-131713_Nextcloud](https://github.com/nextcloud/android/assets/19187967/273804d0-a336-4d16-b15f-defd2a14d46a)

**Comment by joshtrichards** [comment]
Hi @aliceell - What you're describing is expected behavior based on the implementation (See #11811 / #11744) , but this part makes me think I'm misunderstanding your report:

> See above. This has happened to other users in our server, not just me. Some are able to access the calendar and others aren't.

Can you provide some details on how others are able do this from the Android app? AFAIK there's now direct way to do that currently.
