### ISSUE TITLE
Feature request: calendar subscriptions sync

### ISSUE THREAD

**Issue by quentinus95** [nextcloud/android#1215]
It would be great to have ICS subscriptions automatically kept in sync with the Android device. I was using NextCloud with an iOS device and synchronisation was seamless (new subscriptions were added automatically and deleted one were removed).

It would be great to have the same behavior on Android, as we would not have to double subscribe on both NextCloud and Android.

**Comment by mario** [comment]
Should already be possible with our DavDroid integration? :)

**Comment by tobiasKaminsky** [comment]
You mean that if you add a new calendar in nextcloud web ui that this also get added to your android device?
As we only provide an easier setup for davDroid this is a question for davDroid.

**Comment by quentinus95** [comment]
This has already being discussed on DAVdroid forum: https://forums.bitfire.at/topic/1210/nextcloud-calendar-subscription-not-shown/4

`it would not be possible to synchronize those subscriptions with DAVdroid, because DAVdroid is a CalDAV client and not a Webcal client`

I guess the Android app may need an integration with another service?

**Comment by tobiasKaminsky** [comment]
After reading quite a lot, for me it seems that https://github.com/nextcloud/server/issues/1497 it the way to go as this is a server side and then a dav droid issue.
@quentinus95 are you fine with closing it here?

**Comment by quentinus95** [comment]
Oh, I did not saw this issue! Hope it will be implemented soon. Thanks!
