### ISSUE TITLE
autouploud uploads also uploads to a nextcloud for which autoupload is not configured, when 2 nextcloud added the app

### ISSUE THREAD

**Issue by BuZZ-dEE** [nextcloud/android#12157]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

I don't know.

I have configured 2 nextclouds in the app. I set up autoupload for 1 nextcloud. Now I realized the app upload all my camera image also to the other cloud which was not configured for autoupload.

### Expected behaviour

Autoupload should only upload to the nextcloud where it is configured for.

### Actual behaviour

The app uploaded all my camera images to the second nextcloud which was not configured for upload. It uploaded all images also to the nextcloud for which it was configured, which was correct.

### Android version

13

### Device brand and model

Fairphone 5

### Stock or custom OS?

Stock

### Nextcloud android app version

3.26.0

### Nextcloud server version

27.1.1 & 26.0.8

### Using a reverse proxy?

I don't know

**Comment by joshtrichards** [comment]
This sounds like #11088. Let's track there.
