### ISSUE TITLE
Remove "\u0020" from a text string `file_downloader_notification_title_prefix` for Transifex

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/android#12180]
You need to remove "\u0020" from the text string:

![obraz](https://github.com/nextcloud/android/assets/47037905/e7a199a9-98b8-49b4-9270-c5cf420334a9)

We don not want this at Transifex.

**Comment by joshtrichards** [comment]
Was added in #12052:

https://github.com/nextcloud/android/blob/23d120e5ccdc13ca23eb04c7d32cbd16dde0b5f0/app/src/main/res/values/strings.xml#L165

It's just a unicode space. I'm not up to speed on the translation stuff. It can't just get ignored like the variable substitutions already are (presumably) like here?

https://github.com/nextcloud/android/blob/23d120e5ccdc13ca23eb04c7d32cbd16dde0b5f0/app/src/main/res/values/strings.xml#L167

**Comment by Valdnet** [comment]
Translators are accustomed to values such as `%1$s`. They know that this is a variable value that needs to be included in the translation.

However, not all translators see that it is a Unicode code and should also be left in the translation.

@rakekniven What do you think?

**Comment by AndyScherzinger** [comment]
Cc @alperozturk96
