### ISSUE TITLE
Multiple picture transfer doesn't work

### ISSUE THREAD

**Issue by pjlg** [nextcloud/android#1218]
### Actual behaviour
multiple picture transfer with Googles "Fotos" (pictures) App, V.3.1.0.162400126 to nextcloud interrupt or forget some files during transfer. No error messages will be shown. 
You can check it in the sum of the files in a folder only. So you have to find out the missing picture by yourself.

### Expected behaviour
Transfer all selected files to nextcloud.
 
### Steps to reproduce
1. Open picture gallery
2. Mark some files to transfer
3. Share (transfer) via nextcloud 

### Environment data
Android version: 6.0.1

Device model: Nexus 5

Stock or customized system: Stock

Nextcloud app version: 1.4.3

**Comment by tobiasKaminsky** [comment]
Please have a look if #1066 is the same and then close.
