### ISSUE TITLE
Cannot login when XMPP client enabled

### ISSUE THREAD

**Issue by muppeth** [nextcloud/android#1219]
### Actual behaviour
-When JavaScript XMPP Chat  is enabled, pressing "login button" does nothing. 
### Expected behaviour
-Login button should trigger loging in.
 
### Steps to reproduce
1. Enable XMPP client on the server
2. Try to login
3. Disable XMPP client
4. Try to login

### Environment data
Android version: 7.0

PS. I noticed the same issue when using obscure browsers on desktop same thing happens (checked midori)

**Comment by tobiasKaminsky** [comment]
Strange, can you create a test account and send the credentials to android at nextcloud dot com with a reference to this issue, so we can debug it?

**Comment by jgrete** [comment]
Hi,
issue #1209 describes a similar effect and I remember I also disabled the xmpp-client. So both issues seeming to be related to the xmpp-client.
Sorry for jumpin' in - but I think this is importand
Regards
Jürgen

**Comment by tobiasKaminsky** [comment]
**server.log**
> {"reqId":"Uuyh3agQNYUisr3WScNL","level":3,"time":"2017-07-25T06:41:26+00:00","remoteAddr":"0.0.0.0","user":"--","app":"PHP","method":"GET","url":"\/index.php\/login\/flow","message":"Undefined index: oauthState at \/var\/www\/nextcloud\/core\/templates\/loginflow\/authpicker.php#38","userAgent":"Google Android SDK built for x86","version":"12.0.1.0"}

**Comment by tobiasKaminsky** [comment]
I updated the issue https://github.com/jsxc/jsxc/issues/584

**Comment by tobiasKaminsky** [comment]
Was fixed upstream, nothing to do here.
