### ISSUE TITLE
Can not log-in, stuck at the "connect to your account" page

### ISSUE THREAD

**Issue by Krelyshy** [nextcloud/android#12203]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

When I open the android app (v. 3.26.0), I can enter the cloud server address, however, when I get to the log-in page (with warning about making sure that I am logging in from a new device etc.) pressing either of the two buttons, Log-in or Use an application token do not work - or to be exact, they don't do anything.

I couldn't find any related error messages in the app log, nor can I find anything in the server's logs, everything seems fine.

### Expected behaviour

I expected to be able to log-in.

### Actual behaviour

I can't login. The [Nextcloud server scanner](https://scan.nextcloud.com/results/013118f9-e833-44bc-bebd-0bc7334c366d) also says that everything is fine, below is the debug output from the android app.

### Android version

10

### Device brand and model

Xiaomi Redmi 5

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

3.26.0

### Nextcloud server version

27.1.4

### Using a reverse proxy?

No

### Android logs

[logcatOutput.txt](https://github.com/nextcloud/android/files/13472875/logcatOutput.txt)

Note: logs from beta or dev versions are not stored in said directory `storage/emulated/0/data/nextcloud.log`. On Android 10, the data directory exists under the android directory. The logfiles aren't there either.

### Additional information

I use Android AOSP Extended v7.2 since MIUI became too bloated. It is effectively a clean android system with a few enhancements.

**Comment by joshtrichards** [comment]
> `11-27 11:05:56.636 17819 17819 I WebViewFactory: Loading com.android.webview version 74.0.3729.186 (code 373018655)`

Update your WebView app and you should be good at that point.

We'll check and notify about outdated versions (via #12108) in the next release.

**Comment by Krelyshy** [comment]
Thank you, indeed, fixed.
