### ISSUE TITLE
Sharing to NC Dev doesn't work anymore if subfolder is created

### ISSUE THREAD

**Issue by OlivierS1** [nextcloud/android#1222]
### Actual behaviour
-Tell us what happens
Trying to share files from one appliaction with NC Dev doesn't work anymore.

### Expected behaviour
-Tell us what should happen
If I use Whatsapp, Gallery (my phone media browser) or several other apps, and from within the app I request to share files, NC Dev will open once selected but I will not be able to complete the action as the "Cancel" and "Upload" buttons seem unresponsive (They react on the press action by updating their appearance but the upload doesn't start)
NC Dev as to be switch to another app or closed, and transfer never took place.

 
### Steps to reproduce
1. Open an app such as Gallery
2. Select files to be share within the app.
3. Selected NC Dev from the available apps.
4. In NC Dev, select a folder, create a new folder if needed and try to press the  "Upload" button. Nothing happens.
5. Try to press the "Cancel" button, nothing happens.

### Environment data
Android version:
6.0
Device model: 
LG G3 D852
Stock or customized system:
Stock
Nextcloud app version:
NC Dev 20170723
Nextcloud server version:
NC 12

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
This is strange. We, at least what I can recall, did not changed anything within the last few days.
Do you changed something on your device? Like installing an overlay app (redshift, ...)?

**Comment by OlivierS1** [comment]
@tobiasKaminsky I am still having this issue with NC Dev 20170810.
I have noticed the following once the app to share from open NC:
1) When you use the folder that is presented, the buttons take effect.
2) If a new folder is created, NC will enter the folder, then buttons have no effect.
3) If you create a new folder NC enters it. If you exit the folder, buttons have an effect.
4) f you create a folder, concequtively create several folders (getting down deeper in the folder structure), the folder NC enters never have any effects on the buttons. However, if you go up once, then the buttons will behave as expected.

**Comment by tobiasKaminsky** [comment]
Thank you! I can confirm this also on master:
- share a file with NC app
- create a subfolder (nc enters it automatically)
- try to click upload /cancel 
(side effect: the upload button is not colored correctly)

**Comment by tobiasKaminsky** [comment]
Will be in next dev version for testing.
Thank you very much for finding this :tada:
