### ISSUE TITLE
Access to logs in Stable releases (not just Dev builds)

### ISSUE THREAD

**Issue by joshtrichards** [nextcloud/android#12220]
### Is your feature request related to a problem? Please describe.
I'm always frustrated when a bug reporter has a seemingly legitimate bug report but we make them jump through extra hoops to provide logs. It creates extra work for them and for those triaging their bug reports. In short, it wastes time.

### Describe the solution you'd like
The *Settings->Logs* feature available in Dev builds activated in Stable builds too.

### Describe alternatives you've considered
The approach [here](https://github.com/nextcloud/android/#getting-debug-info-via-logcat-mag) that we historically suggest, but: 
- takes extra time and energy
- frustrates non-developers
- requires a computer to merely gather the logs
- may be too late (i.e. the relevant logs are gone if it's not yet clear how to readily reproduce the situation or the reporter isn't at their computer at the time)

### Additional context
This has been requested in numerous comments and it's not clear why there is an aversion to it.
- It can still be an in-app toggle if desired as long as it's available in stable builds.

We (users, devs, members, all stakeholders) have enough things to deal with: let's not make our collective lives more difficult.

If there's a good reason *not* to do this, that's fine too - but let's at least get the reason out in the open.

**Comment by satvik2131** [comment]
Hi , sorry maybe it must be a stupid question , but if I am not wrong we want to integrate the log feature we have in dev to stable builds , right ? and like is it done , or can I work on it ?

**Comment by joshtrichards** [comment]
> if I am not wrong we want to integrate the log feature we have in dev to stable builds , right ?

That's correct.

**Comment by joshtrichards** [comment]
Duplicate of #9844
