### ISSUE TITLE
Contacts and Calender Backup: Choose upload folder

### ISSUE THREAD

**Issue by ZenKyma** [nextcloud/android#12235]
### Is your feature request related to a problem? Please describe.
Nextcloud is all about maintaining your files organised. I like the option to backup calender and contacts regularly, but unfortunately experience a cluttering of my root nextcloud folder. I have a designated `Backups` folder where I would like to store the aforementioned backups.

### Describe the solution you'd like
Providing an option to choose the upload folders for contacts and calender backups respectively would empower the user to maintain the personally preferred file organisation.

### Describe alternatives you've considered
The is no reasonable alternative, but I personally would find it more appropriate to upload calender and contacts backups to `/Backups/.contacts` and `/Backups/.calenders` or alternatively `/Documents/.contacts` and `/Documents/.calenders` instead of cluttering root with more folders.

### Additional context
Possible layout:

![Screenshot_20231205-124140_Nextcloud_possible-implementation](https://github.com/nextcloud/android/assets/116916092/ca691b80-76d6-49e7-8486-da1e6336bba5)

**Comment by joshtrichards** [comment]
Hi @ZenKyma - Thanks for the suggestion. Also, I admire your write-up. :+1:  I think this is covered in #4132 so I'll close this as a duplicate. Please subscribe yourself to that issue and also give it an upvote to help with prioritization. :)

**Comment by ZenKyma** [comment]
Thanks for the heads-up @joshtrichards ! 🙏
