### ISSUE TITLE
Feature "Select all" improvement

### ISSUE THREAD

**Issue by OlivierS1** [nextcloud/android#1223]
### Actual behaviour
-Tell us what happens
Tried the new feature:
#https://github.com/nextcloud/android/issues/637#issuecomment-317256958

 on the top level of my account. It selected 220 objects in about 5 seconds.
Tried to unselect them all, and it took an excess of 30 seconds.
Unselecting then with the back arrow is almost instantaneous.

Feature is nice, but when folders are present along with the files, everything gets selected (this is expected) but would it be possible to list how many folders and how many files are part of the selection.
The number of items selected is already available.
I think it should be something to explore as it would be too easy to just say, I have only files in the selection and decide to delete them, along with the folders and whatever it contains.

### Expected behaviour
-Tell us what should happen
 It would be nice if the "Select all" feature has extra options to select files onlly, folders only and possibly by extension or wildcards.

### Steps to reproduce
1. 
2. 
3. 

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Removed the dev version in topic as it is an enhancement discussion for the whole app.
In general I think we should avoid to clutter up the UI and thus do not add to many sub-options.

**Comment by OlivierS1** [comment]
@tobiasKaminsky I agree, however do you have anything in mind?

**Comment by tobiasKaminsky** [comment]
Not really :-/

@nextcloud/designers maybe you have an idea?

**Comment by jancborchardt** [comment]
As far as I’m aware this is the first time we have this feature request on any of our platforms – Android, iOS or web interface. Seeing as there’s a narrow use-case, no other popular platform provides this, and it would need to be maintained, I’d rather say this is not something we’ll implement.
