### ISSUE TITLE
Broken links in the results of the search using fulltextsearch

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/android#12245]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Set up fulltextsearch apps on the server
2. Start searching in the NC desktop client using universal search
3. Click over the results in the section FullText Search
4. Observe that the opened page says that there's no such a file
5. Check the URL and find that the link is broken: 
`/apps/files/%3Fdir=/` instead of `/apps/files/?dir=/`
6. Check in webUI and find that it is working there fine.

### Expected behaviour

The links of searched items should be opened in the NC Desktop Client as in the webUI.

### Actual behaviour

The links are opened with the mistake (see above).

### Android version

14

### Device brand and model

Pixel 5A

### Stock or custom OS?

Stock

### Nextcloud android app version

3.26.0

### Nextcloud server version

27.1.4

### Using a reverse proxy?

I don't know

**Comment by ostasevych** [comment]
Moreover, it will be fine, if the results may open not the location of the file, but the file itself, so there should be
`/apps/files/?dir=/Doc/subdir&openfile=<fileID>&scrollto=fileName.docx` 
but not 
`/apps/files/?dir=/Doc/subdir&scrollto=fileName.docx`

**Comment by joshtrichards** [comment]
> The links of searched items should be opened in the NC Desktop Client as in the webUI.

This is the repository for the Android mobile client. Did you mean to post this here?
