### ISSUE TITLE
Unified Notifications

### ISSUE THREAD

**Issue by alperozturk96** [nextcloud/android#12256]
### Problem

1. For each upload, download or any other file related operation app throwing notification
2. Same notification may appear again time to time
3. Code complexity increased in-time and causes problem for maintenance
4. Too many notification annoys user

**As mentioned in these issues:**

- [Too many ever-changing notifications while uploading many files #1532](https://github.com/nextcloud/android/issues/1532)
- [Uploading multiple files - notifications #6008](https://github.com/nextcloud/android/issues/6008)
- [Excessive file upload conflicts after update to 3.26.0 (not before) #11974](https://github.com/nextcloud/android/issues/11974)
- [Allow to dismiss all (grouped) "Upload failed" notifications #10571](https://github.com/nextcloud/android/issues/10571)
- [Download/Upload notification: show only one and update this #261](https://github.com/nextcloud/android/issues/261)

### Solution

1. If multiple file operation running at the same time or back to back no need to throw multiple notification. Single notification can show progress for all operations one by one.
2. Managing notifications directly inside service or inside some other class causes problem regarding code readability and maintenance. One single class that will handle notifications and it will be reusable for different needs. And with proper tests (unit, integration) we can be sure about robustness of our solution.

**Comment by satvik2131** [comment]
Ok , if i am not wrong , it's like if we upload 5 files , it shows 5 upload bars one by one in notification , that be could be one , am I correct ?

**Comment by alperozturk96** [comment]
> Ok , if i am not wrong , it's like if we upload 5 files , it shows 5 upload bars one by one in notification , that be could be one , am I correct ?

No need to show 5 different notification for 5 different files, we can use one notification for multiple files.

**Comment by joshtrichards** [comment]
FYI: I've created a temporary label for tracking transfer related notifications which might be a further resource to study the problem(s): https://github.com/nextcloud/android/labels/hotspot%3A%20uploads%20tab%20and%20transfer%20notifications

**Comment by MrRinkana** [comment]
To illustrate the scope of this problem I made a recording during an upload of my pictures folder:

https://github.com/nextcloud/android/assets/39345772/eca61360-2ac4-42f5-8bf7-54431f611231
This was when it was a bit slower as well, slightly smaller files or if I would have recorded while my phone was closer to the wifi router it would look almost epileptic. Clicking/interacting with the notification below is impossible (or with the nc notification for that matter).


It does make sense to do the upload silently, but **it should be an user choice**: there's value in seeing how the upload is progressing. An example of that is if one uploads a folder manually, and such is not an automatic upload.

The optimal solution is to have a notification that:
- shows overall progress with a bar that simply is x uploaded out of y items (nbr %)
- Another progress bar visible only when the notification is expanded, showing the currently uploading items progress % out of total size (GiB/MiB or w/e)
- That notification can be disabled for automatic uploads in app, or disabled altogether trough android notification settings, the latter already possible as is.

**Comment by BluePixel4k** [comment]
@alperozturk96 thank you for this improvement!

Would it be possible, that the progress bar shows the progress over the whole batch of files that get uploaded (and not for each file)?
Then it would be easier to implement the parallel upload/download for Android: https://github.com/nextcloud/android/issues/10124

**Comment by BluePixel4k** [comment]
Hello @alperozturk96,

thanks for your response!

I already tested the latest APK from this PR, and yes it's a good improvement, thx 👍

Could you also discuss the parallel upload/download feature (#10124)? This would speed up the upload/download process a lot :)

Thank you!
