### ISSUE TITLE
AutoUpload uploads all photos that already in Nextcloud again

### ISSUE THREAD

**Issue by guoyunhe** [nextcloud/android#1226]
### Actual behaviour

Today I found Nextcloud Android is uploading photos to server but I haven't taken any new photos. I found it actually uploading all photos i took in the last three months to server again. So here a lot of duplicate photos on my server.

### Expected behaviour

Nextcloud Android should detect if the same file has been uploaded to server in the same position, instead of uploading the same file to the same place and name it as `XXX_(2).jpg`
 
### Steps to reproduce

I do not know how to reproduce it. It happened without any interaction. 

### Environment data
Android version: 7.0

Device model: Moto G (2017)

Stock or customized system: Nearly original Android

Nextcloud app version: 1.4.3

Nextcloud server version: 12

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by mario** [comment]
The issue will be fixed in 1.5.0.

**Comment by mario** [comment]
Dear users,

thank you for your patience. After lots of work, we’re super excited to be able to give you a test version with new auto upload implementation. Keep in mind we will only accept bugs related to Auto Upload in this APK, as other things might be broken.

https://cloud.nextcloud.com/s/ftZraTruRQjTe0R

This is a dev APK so it will not overwrite your existing play store/f-droid APK unless you’re already running dev version. Also, you might need to remove your existing dev version before installing this one.

Explanation of the current functionality:
- added support for custom folders
- separated image and video folders
- checks for new files happens every 15-20 minutes
- automatic retry every 15-20 minutes or when you force close/open the app
- automatic pause once network is changed (untested!)
- significantly less battery usage

All and any testing is more than appreciated, especially with large and ever-going files like Videos. (like, try to record a 30 min video).

Let me know if you’ve got any questions.

Cheers,
Mario

**Comment by guoyunhe** [comment]
Thanks! I will try this.

**Comment by mario** [comment]
@guoyunhe any feedback?

**Comment by guoyunhe** [comment]
@mario I have been using dev client for a week and didn't notice any problem related to AutoUpload.

**Comment by mario** [comment]
Awesome! Thanks!
