### ISSUE TITLE
NC Dev 20170723: "Download" folder no longer available under "Auto uploads" category.

### ISSUE THREAD

**Issue by OlivierS1** [nextcloud/android#1227]
### Actual behaviour
-Tell us what happens
In an earlier version of NC Dev, ( version 20170706 or within the few days preceding that particular release), I found for the first time my "Download" folder included under my "Auto uploads" category.
Last night, after an issue, I had to uninstall NC Dev. Upon reinstalling it, I couldn't find the "Download" folder from the category anymore.

I am thinking, maybe NC Dev is looking for folders with specific file extensions and maybe I had some pictures in the download folder at some points.

Was the "Download" folder intended to be in the "Auto uploads" category to begin with?
What is the mecanism by which NC Dev assign them into "Auto uploads"?
 

### Expected behaviour
-Tell us what should happen
At some point in time, maybe an update, the "Download" folder was present in the "Auto upload" category.
After reinstalling NC Dev, the "Download" folder was no longer available.
 
### Steps to reproduce
1. 
2. 
3. 

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by OlivierS1** [comment]
Update:
By copying a JPG file directly into the "Download" folder, the next time I access the NC "Auto uploads" folder will I see the "Download" folder.

**Comment by AndyScherzinger** [comment]
Pre 1.5.0 stable we show folder with images, starting with 1.5.0 we will show image and video folders and support the definition of custom, user defined folders. This is still under construction and not yet available in the dev releases.
