### ISSUE TITLE
NC Dev 20170723: App password improvement during account setup.

### ISSUE THREAD

**Issue by OlivierS1** [nextcloud/android#1228]
### Actual behaviour
-Tell us what happens
Upon adding an account multiple time on the same phone (following reinstall).
When using the normal login process, NC Dev will generate an App password based on the phone model or name.
If an App password was previously generated from the same devices (or less likely having more than one of the same device using the same account), NC Dev seems to always create the app password with the same description. 
It would be good to have extra info added to the description so as to manage the correct app password for the corresponding device.

### Expected behaviour
-Tell us what should happen
If an app password is created by NC12 server without a name or description, the server will take care of that by entering some date and time info.
NC Dev creates the app password based only on the phone name and/or model number even with an app password already exist with that name.
NC Dev should be able to create a different App password with a name or description which doesn't already exist.

### Steps to reproduce
1. Reinstall NC Dev 20170723 or remove account on devices
2. Add account using normal login.
3. Upon account creation, app password would have been created on server.
4. Go to App password section of the server. Multiple instance of the same app password name exist.

### Environment data
Android version:
6.0
Device model: 
LG3
Stock or customized system:
Stock
Nextcloud app version:
NC Dev 20170723
Nextcloud server version:
NC 12

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
With the new login we completely rely on server parts for login: we simply show a login provided by the server and then get back the user/password.
So this needs to be discussed in https://github.com/nextcloud/server/issues 
If something is needed in android, please reopen and link to the discussion in /server
