### ISSUE TITLE
New android sharing view

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#1229]
I came across this cool sharing view in ocReader

![2017-07-25-081312](https://user-images.githubusercontent.com/5836855/28558232-5556c820-7111-11e7-9d67-863aca63883e.png)

The first 4 pixelated items are whats app contacts.
I think this is way better than our current sharing (within android) view.

Please approve, if you like it :+1:

**Comment by OlivierS1** [comment]
@tobiasKaminsky Can you elaborate, I am not sure how to interpret the idea.

**Comment by tobiasKaminsky** [comment]
Currently we have this dialog, but I think the new one gives more options as it shows, eg. directly the most recent contacts of whatsapp

![2017-07-25-085715](https://user-images.githubusercontent.com/5836855/28559560-449952b8-7117-11e7-9e91-a0b289590f06.png)

**Comment by AndyScherzinger** [comment]
I like the idea since it is a more modern way to display the available sharing option on the device.

**Comment by OlivierS1** [comment]
@tobiasKaminsky Do you mean that sharing a file or folder from NC will go though this page first then, If I want to share with a NC member, then I would have to select "Nextcloud dev" icon then select the user?
Or is this going to be an option to chose between a NC user or using the external sharing apps?
One thing I don't like about the dialog icon is that they tend to shuffle around.

**Comment by tobiasKaminsky** [comment]
This is about sending a file to an app on the device.
I know the working is difficult here, "share/send to another app" vs "share with a NC user".

**Comment by jsrck** [comment]
Hi! I created pull request #1244 for this issue.
