### ISSUE TITLE
MDM

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#12313]
- initial version for MDM

This needs more info, what MDM we should use.
Stay tuned

Requested by: https://github.com/nextcloud-gmbh/customer-feature-requests/issues/699

**Comment by joshtrichards** [comment]
Not sure exactly what you have in mind, but may be an opportunity to incorporate some of the discussions from some existing relevant open issues:

- #408 
- #664
- #3904
- #4243

**Comment by jasonbayton** [comment]
The codebase suggests not, which is the worst possible outcome after so many years of waiting for it.
