### ISSUE TITLE
Folder error when uploading photos via app

### ISSUE THREAD

**Issue by MarcS1975** [nextcloud/android#12325]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Setup android app for auto upload
2. Take photo
3. NC upload starts
4. Upload fails with 'folder error
What I tired
6. I have changed permissions to 777 on the folder. Still same error persists.
7. I  have added my NC user to the group ,users, which owns the folder.

### Expected behaviour

Photos appear on server

### Actual behaviour

Folder error always

### Android version

Latest

### Device brand and model

Samsung s22plus

### Stock or custom OS?

Stock

### Nextcloud android app version

3.26.0

### Nextcloud server version

NC26

### Using a reverse proxy?

Yes

**Comment by joshtrichards** [comment]
Hi @MarcS1975 - 

Are there any errors appearing in your Nextcloud Server logs?
* Can you upload manually from the client successfully? e.g. `+` *Upload files* and/or by sharing from another app on the same device _to_ Nextcloud?
* Are you otherwise able to access all of your files from the client even though this is occurring?
* What is your *Data Storage Folder* under *Settings* (in the client)?

Also you stated:

> Setup android app for auto upload

Can you provide the exact auto upload settings used (charging, wifi, deletion, etc.)?

It would also be informative to see:

- the Nextcloud Server logs (from only during one of the time windows you're attempting an upload in)
- the Web (or proxy) server logs (also only during the time window)

**Comment by MarcS1975** [comment]
Hello Josh - thanks for your reply.
There were no adverse log entries in NC. The folders were also not
accessible via the NC browser (or manual uploads). It turned out that for
some strange reason NC could not access the mapped volume that I had
defined in my compose file as per below:

My container has a volume defined that maps to a folder of my shared media
drive.
# extract form NC compose file
  volumes:
    - /srv/mergerfs/JPool/MEDIA:/var/www/html/media

This volume is then defined in NC as "local" and shows up as a folder
"MEDIA" under NC - files.
I had also defined a subfolder as the Auto-Upload folder on my Android
device.

This setup worked fine up until lately when I had to replace a harddisk on
the MEDIA server. Consequently, NC did not detect the content of that
folder MEDIA anymore. Although the hard disk as storage medium is at least
2 layers of abstraction removed from NC storage, the NC container failed to
access the respective folder.

The only way to fix this was to  *remove and re-add *the "External Storage"
within NC Admin Settings.

Any ideas what I could improve in my setup to avoid those issues in future?
thanks
Marc

**Comment by joshtrichards** [comment]
Not offhand, but the only way to troubleshoot that would be when it's still messed up and maybe by poking around from a shell *within* the container. As long as the folder/path/mount/ownership/permissions remained the same, NC doesn't care. If it comes up again, post over at the Nextcloud Help Forum - https://help.nextcloud.com - and maybe somebody will turn something up.

Glad you got it working and it wasn't an Android client issue at least. :)
