### ISSUE TITLE
Crash on SHIFT Android

### ISSUE THREAD

**Issue by gryphis** [nextcloud/android#12329]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Nextcloud app crashes repeatedly. Habe added an additional folder to sync Minuten before.

### Expected behaviour

Sync without crash

### Actual behaviour

Crashes every time after restart

### Android version

10

### Device brand and model

ShiftOS 6mq

### Stock or custom OS?

Stock

### Nextcloud android app version

20231220

### Nextcloud server version

Nimmerland Cloud

### Using a reverse proxy?

I don't know

### Android logs

.

### Server error logs

```bash
.
```

### Additional information

SHIFT6MQ.SOS.3.10.L.20231025
Sry, don't know to put Android Liga here.

**Comment by joshtrichards** [comment]
> 20231220

You're running a Dev release not a stable release. Is that intentional?

Can you provide the crash output / stack trace?
