### ISSUE TITLE
Auto upload pictures dosn't work

### ISSUE THREAD

**Issue by datasmurfen** [nextcloud/android#1232]
### Actual behaviour
None picture/videos will be auto uploaded both existing, and new once. 

Have to manually add one picture to start upload 

### Expected behaviour
 Picture/videos will be auto uploaded both existing, and new once. 
 
### Steps to reproduce
1. Download app
2. Set up autoupload 
3. Take some pictures. 
4. Nothing happends. 

### Environment data
Android version:
7.0 

Device model: 
Samsung Galaxy S7 Edge

Stock or customized system:
Stock

Nextcloud app version:
1.4.3

Nextcloud server version:
11.0.1 (git)

**Comment by mario** [comment]
Dear users,

thank you for your patience. After lots of work, we’re super excited to be able to give you a test version with new auto upload implementation. Keep in mind we will only accept bugs related to Auto Upload in this APK, as other things might be broken.

https://cloud.nextcloud.com/s/ftZraTruRQjTe0R

This is a dev APK so it will not overwrite your existing play store/f-droid APK unless you’re already running dev version. Also, you might need to remove your existing dev version before installing this one.

Explanation of the current functionality:
- added support for custom folders
- separated image and video folders
- checks for new files happens every 15-20 minutes
- automatic retry every 15-20 minutes or when you force close/open the app
- automatic pause once network is changed (untested!)
- significantly less battery usage

All and any testing is more than appreciated, especially with large and ever-going files like Videos. (like, try to record a 30 min video).

Let me know if you’ve got any questions.

Cheers,
Mario

**Comment by datasmurfen** [comment]
For me it seems like Snapchat pictures from that folder is uploaded correctly (Saved pictures). But the picture/videos taken by camera just keeps failing.  Just keeps telling me that local file isn't found even I can see it in the menu "Auto upload". So there is still some issue. 
[currentLog.txt](https://github.com/nextcloud/android/files/1176140/currentLog.txt)

**Comment by mario** [comment]
Is the file available at the following location?

**Comment by datasmurfen** [comment]
Yes.

**Comment by mario** [comment]
@datasmurfen what happens if you manually try to upload the file?

**Comment by datasmurfen** [comment]
That works. 

Also maybe a seperate bug but my screenshot folder are picture uploaded inside /instantupload/screenshot/, and also instantupload/

**Comment by mario** [comment]
So it uploads them to two separate folders? o.O

**Comment by datasmurfen** [comment]
Yes.

**Comment by mario** [comment]
Found the first issue. (locking issue on SD card, have to see how to resolve).

Second is strange... can't reproduce.

**Comment by datasmurfen** [comment]
Ok, please let me(us) know when you got a new test-apk, or published a update to Play :)

**Comment by mario** [comment]
@datasmurfen new APK at the same url.

**Comment by datasmurfen** [comment]
No duplicates so far, and now it seems to work perfect. Will keep testing some more, and let you know if I find some more errors. 

![image](https://user-images.githubusercontent.com/3126959/28620517-8a8191a4-720d-11e7-8a48-0bae202203c7.png)

**Comment by datasmurfen** [comment]
Things seems to work without any more big problems. It's only uploading the new file, and not the existing one - but as I read from your feature list abouve I would expect this to be implemented on a later stage.  When will these changes reach Play Store?

**Comment by AndyScherzinger** [comment]
The rewritten Auto upload is more or less the last big remaining issue on our list (the rest are minor changes) so a Beta in August seems realistic.
