### ISSUE TITLE
Collabora not loading in app v3.27.0

### ISSUE THREAD

**Issue by expert-geeks** [nextcloud/android#12338]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Upgrade Nextcloud android app to version 3.27.0
2. Open document in app

### Expected behaviour

Collabora should start and open the document as usual

### Actual behaviour

App seems to try to open the document, but does not complete and hangs at the opening document screen. App hangs permanently and does not time-out. No error returned. CODE Admin console doesn't show the user attempting to log in.

Downgrade from v3.27.0 to v3.25.0 and the documents open as usual.

### Android version

10

### Device brand and model

OnePlus 5

### Stock or custom OS?

Stock

### Nextcloud android app version

3.27.0

### Nextcloud server version

25.0.13

### Using a reverse proxy?

Yes

### Server error logs
There's nothing in the nginx error log, here are the access logs;

```bash
xx.xx.xx.xx - user [03/Jan/2024:17:14:34 +0000] "PROPFIND /remote.php/dav/files/user/path/ HTTP/1.1" 207 1331 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.27.0"
xx.xx.xx.xx - user [03/Jan/2024:17:14:34 +0000] "GET /ocs/v2.php/apps/files_sharing/api/v1/shares?path=%2FDocuments%2F&reshares=true&subfiles=true HTTP/1.1" 200 2480 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.27.0"
xx.xx.xx.xx - user [03/Jan/2024:17:14:36 +0000] "GET /ocs/v2.php/cloud/user?format=json HTTP/2.0" 200 566 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.27.0"

then nothing...
```

### Additional information

logcat file doesn't seem to contain any information about app usage, there's plenty in there about signal strength etc but nothing that seems related to nextcloud. Is there a recommended 'filter' to use with logcat to generate useful logs ?

There doesn't appear to be an apk in releases for 3.26.0 (https://github.com/nextcloud/android/releases/tag/stable-3.26.0) or I would have tested that also.

**Comment by jakobroehrl** [comment]
Same problem.
After the update to 3.27.0 all office docs does not open. They are loading endless.
No problem with the 3.26.0

**Comment by joshtrichards** [comment]
Reproduced in both v3.27 and master/latest Dev. Thank you for reporting!

**Comment by r4tt4** [comment]
+1 same problem here. Downgrade to 3.2.25 re-enables mobile editing again. Hope that will be fixed soon.

**Comment by joshtrichards** [comment]
New document creation appears to work fine; just opening existing documents is broken.

@alperozturk96 The main change #12158, but that in theory shouldn't have changed any behavior.

**Comment by joshtrichards** [comment]
@sentsev No I was clarifying which use cases were failing. In any case, the bug has now been fixed. It'll be in the next minor release.

**Comment by sentsev** [comment]
@joshtrichards Thanks for explaining.
