### ISSUE TITLE
After updating to 3.27.0, I can't see comments on photos and videos shared by multiple people

### ISSUE THREAD

**Issue by HayabusaWorks** [nextcloud/android#12340]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

NextcloudAndroidアプリ3.27.0で操作

1.コメント付き動画を一覧画面から選択する
2.右上メニューから『詳細』を選択する
3-a.自身がコメントしたデータの場合
ロード中のまま何も表示されない
3-b.他人がコメントしたデータの場合
アプリケーションがクラッシュする

Operated with Nextcloud Android app 3.27.0

1. Select a video with comments from the list screen
2. Select "Details" from the top right menu
3-a. For data commented by yourself
Nothing is displayed while loading
3-b.In the case of data commented by others
application crashes

### Expected behaviour

詳細タブでコメントが表示される

Comments are displayed on the details tab

### Actual behaviour

a.自身がコメントしたデータの場合
ロード中のまま何も表示されない
b.他人がコメントしたデータの場合
アプリケーションがクラッシュする

a. For data commented by yourself
Nothing is displayed while loading
b.In the case of data commented by others
application crashes

### Android version

Android9

### Device brand and model

ASUS_X00QD

### Stock or custom OS?

Stock

### Nextcloud android app version

3.27.0

### Nextcloud server version

Nextcloud Hub 6 (27.1.5)

### Using a reverse proxy?

No

### Cause of error
```java
Exception in thread "Thread-26" java.lang.IllegalArgumentException: Trying to execute a remote operation with a NULL OwnCloudClient
    at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:201)
    at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment.lambda$markCommentsAsRead$7(FileDetailActivitiesFragment.java:371)
    at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment.$r8$lambda$YWBrXKUAdoytvoaiG4-M3S75PWU(Unknown Source:0)
    at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment$$ExternalSyntheticLambda8.run(Unknown Source:2)
    at java.lang.Thread.run(Thread.java:764)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30270090`
* Build flavor: `gplay`

### Device information
* Brand: `asus`
* Device: `ASUS_X00QD`
* Model: `ASUS_X00QD`
* Id: `PPR1.180610.009`
* Product: `WW_X00QD`

### Firmware
* SDK: `28`
* Release: `9`
* Incremental: `16.0615.2006.131-0`

**Comment by joshtrichards** [comment]
Fixed in #12583
