### ISSUE TITLE
DEV release with new sync; local file not found

### ISSUE THREAD

**Issue by DaveBurkhardt** [nextcloud/android#1234]
### Actual behaviour
App attempts to upload photo; errors and says local file not found but  shows a preview of the file

### Expected behaviour
App should upload
 
### Steps to reproduce
1.  Take picture
2.  Wait for upload
3. 

### Environment data
Android version: 6.0.1

Device model:  Samsung S5

Stock or customized system: Stock

Nextcloud app version:  DEV version with latest 

Nextcloud server version:   11.0.2

**Comment by mario** [comment]
Please download APK from the same URL again. This error has been fixed.

**Comment by DaveBurkhardt** [comment]
Will do; confused as to why the hooks for immediate sync are not implemented in addition.  It appears it's only on a cronjob like 15m window now.

I switched back to ownclouds android app in past week and it has no issues with the triggers from camera. 

IMO should be both

1) use hooks for instant sync for camera/whatnot
2) follow-up with cron job sync for other apps which may silently put files in the sync folders

I don't believe users are going to wait to wait some random period of time to share something with someone else.

e.g.   Took a cool photo/video want to send someone the link; I now have to wait some undetermined amount of time and keep checking to see if it uploads.

Thanks for the work on this :)

**Comment by mario** [comment]
You are on Android 6 - the approach oC took works on Android versions below 7, but only on certain phones. Our implementation works for everyone starting Android 4.0.

**Comment by DaveBurkhardt** [comment]
I see; so no instant uploads on this code base?  It'll be soley a cron based system?

**Comment by mario** [comment]
Indeed. The important thing is not INSTANT upload but RELIABLE upload ;)

**Comment by DaveBurkhardt** [comment]
yes, baby steps.  Just sync working would be good; the rsync style approach is good.

So in the (newer) android API there are no hooks that work on all models?  And or logic that can check what appears to be multiple hooks?  (I assume some new and some deprecated ones)

So far it appears to be working.  I'll report back in a few days.

**Comment by mario** [comment]
Indeed. Even the old PHOTO/VIDEO hooks didn't really work on all models.

For Android 7, Google has completely dropped the hooks and decided that it gets to decide when to upload files :)

**Comment by DaveBurkhardt** [comment]
Oh geeze.  Thanks for the info.  What a mess; that decision should be the users not googles.  Can't say I like the thought process or direction they are taking that in.  I assume its to "schedule" data xmits so they can be done in groups to save battery. 

Is there any way to force a "full" sync?  i.e. any files that are on my local device which are not on the cloud would be pushed up.

Thanks for your time on this!

**Comment by AndyScherzinger** [comment]
> Is there any way to force a "full" sync? i.e. any files that are on my local device which are not on the cloud would be pushed up. (I ask because I now have months of files which are not sync'd on my families devices). Or will the app see the differences and do it automatically?

Not in the current stage of the feature but better sync capabilities are on the list of feature iterations, see #285

**Comment by jasonbayton** [comment]
> For Android 7, Google has completely dropped the hooks and decided that it gets to decide when to upload files :)

For Android 8 let's hope they reverse that decision...

The cron is something to get used to, but as @mario put it, I'll take reliability over speed when it comes to my personal photos 👍

**Comment by DaveBurkhardt** [comment]
Cool; I like the road map.  

What increment would you say it's at now?

**Comment by AndyScherzinger** [comment]
> For Android 8 let's hope they reverse that decision...

Unfortunately it seems Android O will be even more restrictive when it comes to that :/ Probably not as bad as Android 6/7

**Comment by AndyScherzinger** [comment]
@DaveBurkhardt Increment 2 is what will ship with the next stable release

**Comment by DaveBurkhardt** [comment]
Ok, great.  If no one cares I'm going to close this.  As the issue is resolved.  Or please go ahead and do so.

**Comment by mario** [comment]
Hint for you :)

If you use custom folders and change a file, the change will get uploaded as well :)

**Comment by DaveBurkhardt** [comment]
oh, so "touch" is my friend.  Assuming that's enough of a change.

**Comment by mario** [comment]
It is :P But this is completely experimental and not something I'll support yet :D

**Comment by DaveBurkhardt** [comment]
NP; I understand.

**Comment by mario** [comment]
Sure, but if you have exif tags properly on all the photos, it'll use date from there instead of file modified from the filesystem.

**Comment by DaveBurkhardt** [comment]
Oh, wait.  So year/month structure is not based on the files date/time but the EXIF tags?  oh, cool!  I'll give touch a whirl on a one folder and see how it goes.

**Comment by mario** [comment]
For images that have them, indeed. Magic :D Let me know how it goes!

**Comment by DaveBurkhardt** [comment]
I touched all JPG in a folder; but it never uploaded the files.  (touched both access and modified time)

**Comment by mario** [comment]
Which folder? Do  you have it configured for auto upload and did 20 mins
pass?

**Comment by DaveBurkhardt** [comment]
Oh, wait.  No it worked.  yes, it took closer to 20m.

Both folders I touched files in worked.  As well it did used EXIF data :)  files are stored in proper destination year/month.

**Comment by jasonbayton** [comment]
Dave I've got a bunch of nonstandard folders I want to upload. Tell me more about touch :)

**Comment by DaveBurkhardt** [comment]
It's a unix shell command.  

1) Ensured the folder I wanted to sync was setup in the app 1st.
2) connect phone to PC via USB  (make sure phone is in developer mode or this won't work.  No you don't need root)
3) launched "adb shell" from cmd prompt  (Android dev kit tools, it's the command "adb" with parameter "shell")
![howto](https://user-images.githubusercontent.com/23338339/28634006-5a894cf6-71fb-11e7-877e-bd1996a35274.png)


4) cd /path/to/files  (this path will match exactly what you see in the app on the top under "Preferences for auto uploading" after "for")

![path](https://user-images.githubusercontent.com/23338339/28634015-678b9d0a-71fb-11e7-89ac-e439fc2a6d12.PNG)

5) touch -a -m *
6) wait for the sync.

**Comment by DaveBurkhardt** [comment]
Not difficult at all; but could be a bit daunting if you're not familiar with unix and or using adb.

If you follow the steps for all of your paths you have setup to sync it should work, try one to start.  As well you don't need to keep launching "adb shell".  Once you are in it; just change directories to the next path and run the touch command again.

**Comment by DaveBurkhardt** [comment]
Mario; thanks I read that too. 

 Just FYI seems to work well.  I touched 30+GB of videos/pictures all were uploaded.  (took a long time) but it worked well.

What I haven't tested; is files being written during while the sync process is running.  I.E long video recordings; how it handles open files being actively written while sync is going.

Good work! :)

**Comment by mario** [comment]
@DaveBurkhardt thanks! Think you could try the long video recording? Would be much appreciated. Should be handled via lock mechanism, but you never know :D

Especially if you're recording it on an SD card and/or if you're saving it to a custom folder (generic camera can't do that, but I imagine some can)

**Comment by DaveBurkhardt** [comment]
NP

Yes, everything I have tested is 100% on SD card; no local storage.  I'll try a very long video recording this weekend and ensure it also does a sync during.  i.e. take some pics then start the video.

**Comment by mario** [comment]
A real question is if it will upload an incomplete video :)

**Comment by DaveBurkhardt** [comment]
yes, I'm interested to see if it pushes up the file as it's being recorded when it syncs.

If it does... will it then later detect the last modified time and upload it again (re-upload; as I assume it doesn't send diffs)

**Comment by DaveBurkhardt** [comment]
Looks like it skips the files being written too; it uploaded one small video/picture while another one was recording.

**Comment by mario** [comment]
Excellent ;) I assume later on it uploaded it? :)

**Comment by DaveBurkhardt** [comment]
Waiting to see, I had no time to run test this weekend.  So I just started it when I got to work.  It hasn't yet.  I'll check again in 15m.

**Comment by DaveBurkhardt** [comment]
It uploaded; which is good.  It failed 1st time but then succeeded.  So it took a long time to get there but it did eventually arrive :)

**Comment by mario** [comment]
Well yay! :D
