### ISSUE TITLE
File activity does not show up

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/android#12364]
click on details of a file
no file activity is shown:

![image](https://github.com/nextcloud/android/assets/24530680/8eeebd0a-569d-4353-b926-3351df3934b4)

### Android version

14

### Device brand and model

Pixel 4a calyxos

**Comment by joshtrichards** [comment]
Confirmed and reproduced in latest master as well.

**Comment by Phils80** [comment]
@joshtrichards, seems I was faster :), added comment about duplicate issue.
