### ISSUE TITLE
Add configurable delay for upload & delete (delete after N days after successful upload)

### ISSUE THREAD

**Issue by tilllt** [nextcloud/android#12362]
In the past Android Client Sync was so slow to sync and delete data (pictures) from the phone, that this was not really an issue. I think the client has gotten much better and faster and this is great! Thanks everyone for the hard work.

BUT: I have my phone configured to upload photos to the cloud once it is in WIFI - and delete them afterwards. That's a great workflow for me. But now that the sync has gotten so fast, sometimes, if I want to take a picture, send it to Grandma and delete it, before I manage to press "send" in messenger, it's already uploaded and deleted.

I would like to ask for a feature which adds a "delay" option to the upload config. Optimally, the client would sync new files immediately, but have an option to delete them after N days. Alternatively (if that's easier to implement) the option could be to upload and delete Photos after N days.

The obvious "alternative" is to disable the "Delete after Upload" Functionality, but that would be not the same because it's a really nice automatic workflow to keep your device tidy end retain free space.

Also I am using this app com.nkming.nc_photos.paid which let's me send photos directly from Nextcloud storage. That also works, but especially is problematic if you have bad Internet and want to send big files, as it first needs to download the file and then send it on your phone.

**Comment by joshtrichards** [comment]
Hi @tilllt - I like your write-up and examples. I think #2323 and #3696 cover your use case. If so, I encourage you to upvote/comment/subscribe there and close this out as a duplicate.

**Comment by tilllt** [comment]
You are right, they asked for the same. I can only close it as "not planned" or "done" which both is not correct.
