### ISSUE TITLE
Internal and external connections

### ISSUE THREAD

**Issue by ktatar156** [nextcloud/android#12371]
Hello,

I would love to see feature that will automatically use internal (over private network) connection, and, while external connect, switch to it.

In example, I have setup my private Nextcloud server with IP 192.168.0.100
When I'm in my private WiFi range, I would like to auto-connect to this (due to bandwidth speed reasons). But, when I left my place, I would like to switch connection to external IP (ex. 31.31.31.31) - is it possible?

**Comment by joshtrichards** [comment]
This is outside the scope of the Android client, and more a general networking/DNS question. Please post over at the Nextcloud Help Forum - https://help.nextcloud.com
