### ISSUE TITLE
Calendar daily backup isn't running (Contacts daily backup okay)

### ISSUE THREAD

**Issue by Bitsauger** [nextcloud/android#12370]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [x] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Activate Backup Calendar in Nextcloud Android App, switch to automatic daily Backup.

### Expected behaviour

Daily Backups of my Calendars on my Android Device. There should be Files in the .contacts or .calendar folder, that are not older than 1 day.

### Actual behaviour

The backups are older than 3 days. For Contacts it works, but the calendars it doesnt.

### Android version

13

### Device brand and model

Samsung A72 and A50

### Stock or custom OS?

Stock

### Nextcloud android app version

3.27.0

### Nextcloud server version

Hub 7 (28.0.1)

### Using a reverse proxy?

Yes

### Android logs

Not found

### Server error logs

```bash
No errors
```

### Additional information

Unable to find Nextcloud Logs in Android Device. There aer 2 Devices with the exact same behavior: Contacts backup is working, Calendar backup does not.

**Comment by joshtrichards** [comment]
What happens when you click on "Back up now"?

> The backups are older than 3 days. 

Are they from a prior version of the client or a manual run? 

Trying to determine *when* this behavior started would be helpful in isolating the cause.

**Comment by Bitsauger** [comment]
Thanks for your reply!
> What happens when you click on "Back up now"?

It starts to backup and as expected all calendar and contacs will be saved.

> Are they from a prior version of the client or a manual run?

I set up a fresh nextcloud install, added this new nextcloud in the app. Started Backup for the first time manually and switched the calendar and contacts backup to auto.

> Trying to determine _when_ this behavior started would be helpful in isolating the cause.

I never used this feature before and I am glad to found this feature. I do backups of my Nextcloud data so calendar an contacts will also be saved.

![IMG-20240115-WA0007](https://github.com/nextcloud/android/assets/42753280/deee389a-eb8e-4f16-a82a-61b198aa0f12)
![IMG-20240115-WA0006](https://github.com/nextcloud/android/assets/42753280/5d8bd9f4-6e50-473b-9ee6-c0e4df2e9879)
![IMG-20240115-WA0008](https://github.com/nextcloud/android/assets/42753280/de438352-a900-4641-82e9-97ef11170ebc)
![IMG-20240115-WA0005](https://github.com/nextcloud/android/assets/42753280/38406051-6e89-4ab9-958b-9a430c1cd53c)
![IMG-20240115-WA0010](https://github.com/nextcloud/android/assets/42753280/1acc1877-772b-4c01-bc83-5f257930cc6c)
![IMG-20240115-WA0009](https://github.com/nextcloud/android/assets/42753280/dfc53bc4-c219-4572-9e1d-7162edcbd647)

**Comment by Tom4tot** [comment]
If it helps, I can confirm I have the same issue. Galaxy S24, Android 14.

The app is running regularly both in background and foreground, so it doesn't seem to be the issue. Manual backup seems to work perfectly fine.

**Comment by Bitsauger** [comment]
Just for additional information:

I also use BlissOS 15.9 (Android 12L on x86). On this device the daily calender and contacts backup is working without any problems.

**Comment by Bitsauger** [comment]
I switched to a S23+ Android 14 and OneUI6.1 with Nextcloud App Version 3.28.2.

It seems to be fixed, all Contacts and Calendars are Backup reliably now.

Thanks and best regards.
