### ISSUE TITLE
Not possible to display Activities while looking into file details.

### ISSUE THREAD

**Issue by Phils80** [nextcloud/android#12373]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Install Nextcloud QA test version from #12337 (https://www.kaminsky.me/nc-dev/android-artifacts/12337.apk)

### Expected behaviour

I shoud see activity details.

### Actual behaviour

Seems like app is trying to display activity, but freezes in this stage. 

### Android version

Android 12

### Device brand and model

Asus Zenfone 7

### Stock or custom OS?

Stock

### Nextcloud android app version

QA version 12337

### Nextcloud server version

27.1.4

### Using a reverse proxy?

No

### Android logs

[logs.txt](https://github.com/nextcloud/android/files/13940671/logs.txt)

### Additional information

Bug notification on request of @joshtrichards - bug noticed during testing potential solutions of #12337, #12345 and #11974.

**Comment by joshtrichards** [comment]
Duplicate #12364
