### ISSUE TITLE
Use different chunk sizes depending on network

### ISSUE THREAD

**Issue by mario** [nextcloud/android#1238]
Use bigger chunks for wifi, and smaller for 4g

**Comment by AndyScherzinger** [comment]
👍

**Comment by tobiasKaminsky** [comment]
AFAIK there is an issue (and maybe even a PR) which suggests 10Mb on wifi and 1Mb on 4g.
The problem found was that changing the chunk size during upload could result in a corrupted file.

**Comment by mario** [comment]
2.1.0?

**Comment by AndyScherzinger** [comment]
sure thing 👍

**Comment by JustasStankunas** [comment]
Is there any progress on this? Maybe it would be an option first to implement option somewhere in app settings to allow manually change chunk size?

**Comment by tobiasKaminsky** [comment]
No progress yet, sorry. 
On our next hackweek/contributor week I'll have a discussion with the server guys how we can handle this.

**Comment by tobiasKaminsky** [comment]
- open /remote.php/dav/uploads/$userId
- create folder / fileId, with hashsum -> fileId-hashsum (unique, but random)
- upload chunks with different chunk size, client is responsible to have no gaps 
	- name via byte range, startByte-endByte 0000000000-0000001000
- list existing chunks via PROPFIND
- move ".file" to target e.g. remote.php/files/$userId/$folder/$file.txt
