### ISSUE TITLE
Code not compiled

### ISSUE THREAD

**Issue by T4-RajnishR** [nextcloud/android#12380]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

<img width="1371" alt="Screenshot 2024-01-17 at 11 35 11 AM" src="https://github.com/nextcloud/android/assets/144092493/d65f5f02-20d6-4060-af97-b8da8c8f129a">

### Expected behaviour

Code should compiled @

### Actual behaviour

Code not
<img width="1371" alt="Screenshot 2024-01-17 at 11 35 11 AM" src="https://github.com/nextcloud/android/assets/144092493/ed344461-b1e0-4948-96cf-800e71643efd">
 compiled

### Android version

13

### Device brand and model

One plus

### Stock or custom OS?

Stock

### Nextcloud android app version

20220322

### Nextcloud server version

stable27

### Using a reverse proxy?

I don't know

**Comment by joshtrichards** [comment]
> 20220322

Are you really trying to build an almost 2 year old nightly dev version?

Anyhow, you might have better luck with a newer Gradle version. I think 8.2 is what's used currently.

**Comment by T4-RajnishR** [comment]
Hi can your share me branch name that have latest code.

**Comment by AndyScherzinger** [comment]
`master` branch

**Comment by joshtrichards** [comment]
Closing due to no further actionable items to track.
