### ISSUE TITLE
Monitor/bugfix auto upload

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#12392]
After https://github.com/nextcloud/android/issues/11974 there might still be some more work to do.
Let us track here what is wrong and continue to work on it.

**Comment by joshtrichards** [comment]
#12596 might be worth a look unless the intention here was to limit the of monitoring to #11974 itself.

**Comment by JonasMayerDev** [comment]
@joshtrichards i talked with tobias and i think this issue is only for monitoring the things left from the file conflict issue.
