### ISSUE TITLE
No progress bar for uploading files from the smartphone

### ISSUE THREAD

**Issue by stefan-franz** [nextcloud/android#12395]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

If i upload over the app files i have since yesterday no progress bar for uploading files from the smartphone

### Expected behaviour

A few days ago i had progress bars - had to install my smartphone new - after that, not action is seen - so i don't know if the upload works

### Actual behaviour

No progress bar

### Android version

11

### Device brand and model

Moto G 5G

### Stock or custom OS?

Stock

### Nextcloud android app version

3.27.0

### Nextcloud server version

27.1.5

### Using a reverse proxy?

No

**Comment by joshtrichards** [comment]
> A few days ago i had progress bars - had to install my smartphone new - after that, not action is seen - so i don't know if the upload works

I can't reproduce any problems with upload status notifications. Can you check your notification settings on your phone for the app?

**Comment by stefan-franz** [comment]
Now it works again - don't know the reason. 
All is fine
