### ISSUE TITLE
Automatically resolve conflicts

### ISSUE THREAD

**Issue by sonwayy** [nextcloud/android#12407]
It would be nice if we can have an option in settings, in order to choose if we want server side or local side file when there is a conflit. Because we need to do it manually for all conflits and it is a little bit annoying

**Comment by joshtrichards** [comment]
When using auto-upload?

**Comment by sonwayy** [comment]
> When using auto-upload?

Yes, so we could have a setting to choose whenever we have a conflict if we want local file or cloud file. So we don't need to resolve every conflict one by one.

**Comment by joshtrichards** [comment]
- *Settings -> Auto upload*
- Choose the folder profile you'd like to do this for and click the three dots menu
- Choose *Configure*
- Set the last option on the screen that pops up that is labeled "What to do if the file already exists" to your preferred approach

**Comment by sonwayy** [comment]
Oh nice, that was exactly what i was looking for !
I didn't looked up here, thanks !
