### ISSUE TITLE
Support for Android 8.0

### ISSUE THREAD

**Issue by jasonbayton** [nextcloud/android#1242]
### Actual behaviour
On opening 1.4.3 the app force-closes after the first initial logon (when setting up) and subsequently immediately on every following app launch.

### Expected behaviour
It works as normal
 
### Steps to reproduce
1. Grab a phone that supports the Android O beta and upgrade
2. Download and login to the NC app
3. Watch it crash

### Environment data
Android version: O (8.0)

Device model: nexus 5x

Stock or customized system: stock beta

Nextcloud app version: 1.4.3

Nextcloud server version: 11.0.3

**Comment by tobiasKaminsky** [comment]
As I do not have an android 8 capable device I tried it with an emulator and it works without problems.
Can you give us a locgat output https://github.com/nextcloud/android/blob/master/README.md#get-debug-infos-via-logcat?

**Comment by sosed213** [comment]
I have the same problem on Android 7.1.2.
When you try to log in to your account (administrator), there is an endless redirection to the authorization page. If you go under any other account, then everything happens successfully. What can I check?

**Comment by jasonbayton** [comment]
ADB logs as soon as I can reliably recreate the issue. It's sporadic

**Comment by sosed213** [comment]
How can I safely send a log file?

**Comment by mario** [comment]
Mario@nextcloud.com

**Comment by tobiasKaminsky** [comment]
@jasonbayton today we pushed oreo support into dev version.
Maybe you want to try it tomorrow (via direct download) and report back?

**Comment by infernocs** [comment]
This sucks, since the last update my oneplus5 keeps asking for the password all the time.
