### ISSUE TITLE
only new made photos synced with server

### ISSUE THREAD

**Issue by cyaneo** [nextcloud/android#1245]
### Actual behaviour
- old photo already taken does not sync with server, only new made photos are synced

### Expected behaviour
-after new install, all allready made photos should be synced with server

### Environment data
Android version: 7.0

Device model: Galaxy S7

Stock or customized system:
Stock

Nextcloud app version:
1.4.3
Nextcloud server version:
12.0.0

**Comment by mario** [comment]
This is expected for now.

**Comment by batje** [comment]
There is still quite a few people who expect this behaviour. It is quite unintuitive to only have new files synced. You expect when you select a folder for auto-upload, that it will start with the existing files. 
The forum issue is here: https://help.nextcloud.com/t/autoupload-how-to-sync-existing-files/10149/8

**Comment by AndyScherzinger** [comment]
to be released with 3.11. via #4788
