### ISSUE TITLE
Autoupload does not respect wifi settings. (app dev ver. 20170727)

### ISSUE THREAD

**Issue by ruvashev** [nextcloud/android#1246]
### Actual behaviour
Autoupload does not respect wifi settings. (app dev ver. 20170727). It uses data when wifi is turned off. 

### Expected behaviour
App should upload photos only when wifi is available.
 
### Steps to reproduce
1.  take photo
2. have wifi turned off and setting in autoupload : upload on wifi only.
3. observe that app uploads photos and videos via cellular data.

### Environment data
Android version: 4.4.4
Device model: xperia z2
Stock or customized system: rooted
Nextcloud app version: dev 20170727
Nextcloud server version: 11

**Comment by mario** [comment]
Can you try this please?

https://cloud.nextcloud.com/s/pAbCOxR71TEhGgR

Thanks!

**Comment by ruvashev** [comment]
hi Mario, with DEV 30/07 same happens. Just had recently taken photos and videos uploaded via cellular data.

**Comment by mario** [comment]
@ruvashev is this f-droid or the APK I provided? Sounds strange...

**Comment by ruvashev** [comment]
your apk, i just clicked link you provided. My android pretty old 4.4.4 - keeping for convenience reasons if it makes a difference.

**Comment by mario** [comment]
Should work still. Um can you follow something like this?

http://www.dummies.com/consumer-electronics/tablets/android-tablets/set-metered-wi-fi-connection-android-tablet/

I'm assuming Android thinks you're on unmetered network...

**Comment by ruvashev** [comment]
I have wifi turned off entirely. So app uses cellular data network which it should not I assume.
Is it a bug or something wrong with configuration?
![screenshot_2017-07-31-10-52-08](https://user-images.githubusercontent.com/952468/28783583-cf00cde8-75de-11e7-8f38-030902500433.png)

**Comment by mario** [comment]
Same url, new APK for you. Can you try please? :)

**Comment by ruvashev** [comment]
It took some time for me. Seems like it is working as expected now. Thanks for the fix.

**Comment by mario** [comment]
Thanks.
