### ISSUE TITLE
Upload works - Auto-Upload does not

### ISSUE THREAD

**Issue by kbabioch** [nextcloud/android#1249]
### Actual behaviour
I can manually upload pictures to my Nextcloud instance. However, Auto-Upload does not work. Pictures get queued and the app tries to upload them, but in the Queue view it is shown as "failed".

It does work for other phones, so this seems to be a problem with this specific device.

### Expected behaviour
Auto Upload should work.
 
### Environment data
Android version: 7.0

Device model: Moto G4

Stock or customized system: Stock

Nextcloud app version: 1.4.3

Nextcloud server version: 12.0.0

### Logs

Looking at the logcat output of the device, this seems wrong:

    07-31 16:41:00.239 19013 19013 V UploadsStorageManager: Inserting /storage/170A-0829/DCIM/Camera/IMG_20170731_164022093.jpg with status=UPLOAD_IN_PROGRESS
    07-31 16:41:00.249 19013 19013 D UploadsStorageManager: storeUpload returns with: content://org.nextcloud/uploads/2 for file: /storage/170A-0829/DCIM/Camera/IMG_20170731_164022093.jpg
    07-31 16:41:00.249 19013 19013 D UploadsStorageManager: notifyObserversNow
    07-31 16:41:00.254 19013 19013 D ExpandableUploadListAdapter: refreshView
    07-31 16:41:00.254 19013 19013 D ExpandableUploadListAdapter: loadUploadItemsFromDb
    07-31 16:41:00.261 19013 26546 V UploadsStorageManager: Updating /storage/170A-0829/DCIM/Camera/IMG_20170731_164022093.jpg with status:UPLOAD_IN_PROGRESS and result:UNKNOWN (old:/storage/170A-0829/DCIM/Camera/IMG_20170731_164022093.jpg status:UPLOAD_IN_PROGRESS result:-1)
    07-31 16:41:00.261 19013 26546 V UploadsStorageManager: Updating /storage/170A-0829/DCIM/Camera/IMG_20170731_164022093.jpg with status=UPLOAD_IN_PROGRESS
    07-31 16:41:00.269  5025  5613 W UdcContextManagerHelper: Empty context buffer. Thus might mean that the context is not synced down.
    07-31 16:41:00.269  5025  5613 W GetDeviceDataUploadOptInStatusOp: Empty context model while retrieving upload opt-in status!
    07-31 16:41:00.323 19013 26546 D UploadsStorageManager: updateUpload returns with: 1 for file: /storage/170A-0829/DCIM/Camera/IMG_20170731_164022093.jpg
    07-31 16:41:00.323 19013 26546 D UploadsStorageManager: notifyObserversNow
    07-31 16:41:00.330 19013 26546 D SimpleFactoryManager: getClientFor(OwnCloudAccount ... : 
    07-31 16:41:00.331 19013 26546 D OwnCloudClient #290: Creating OwnCloudClient
    07-31 16:41:00.331 19013 26546 V SimpleFactoryManager:     new client {xxx@xxx.de/nextcloud, XXXXXXXX}
    07-31 16:41:00.331 19013 19013 D ExpandableUploadListAdapter: refreshView
    07-31 16:41:00.331 19013 19013 D ExpandableUploadListAdapter: loadUploadItemsFromDb
    07-31 16:41:00.340 19013 26546 D OwnCloudClient #290: REQUEST HEAD /nextcloud/remote.php/webdav/Camera/
    07-31 16:41:00.342 19013 26546 D AdvancedSslSocketFactory: Creating SSL Socket with remote xxx.de:443, local null:0, params: org.apache.commons.httpclient.params.HttpConnectionParams@ffe406
    07-31 16:41:00.342 19013 26546 D AdvancedSslSocketFactory:  ... with connection timeout 10000 and socket timeout 10000
    07-31 16:41:00.346 19013 26546 I ServerNameIndicator: SSLSocket implementation: com.android.org.conscrypt.OpenSSLSocketImpl
    07-31 16:41:00.346 19013 26546 I ServerNameIndicator: SNI done, hostname: xxx.de
    07-31 16:41:02.720 19013 26546 D ExistenceCheckRemoteOperation: Existence check for https://xxx.de/nextcloud/remote.php/webdav/Camera/ targeting for  existence finished with HTTP status 200
    07-31 16:41:02.731 19013 26546 D UploadFileOperation: Checking name collision in server
    07-31 16:41:02.731 19013 26546 D OwnCloudClient #290: REQUEST HEAD /nextcloud/remote.php/webdav/Camera//IMG_20170731_164022093.jpg
    07-31 16:41:03.046 19013 26546 D ExistenceCheckRemoteOperation: Existence check for https://xxx.de/nextcloud/remote.php/webdav/Camera//IMG_20170731_164022093.jpg targeting for  existence finished with HTTP status 404(FAIL)
    07-31 16:41:03.050 19013 26546 V UploadsStorageManager: Updating /storage/170A-0829/DCIM/Camera/IMG_20170731_164022093.jpg with status:UPLOAD_IN_PROGRESS and result:UNKNOWN (old:/storage/170A-0829/DCIM/Camera/IMG_20170731_164022093.jpg status:UPLOAD_IN_PROGRESS result:-1)
    07-31 16:41:03.050 19013 26546 V UploadsStorageManager: Updating /storage/170A-0829/DCIM/Camera/IMG_20170731_164022093.jpg with status=UPLOAD_IN_PROGRESS
    07-31 16:41:03.061 19013 26546 D UploadsStorageManager: updateUpload returns with: 1 for file: /storage/170A-0829/DCIM/Camera/IMG_20170731_164022093.jpg
    07-31 16:41:03.061 19013 26546 D UploadsStorageManager: notifyObserversNow
    07-31 16:41:03.064 19013 19013 D ExpandableUploadListAdapter: refreshView
    07-31 16:41:03.064 19013 19013 D ExpandableUploadListAdapter: loadUploadItemsFromDb
    07-31 16:41:03.067 19013 26546 D UploadFileOperation: Copying local file
    07-31 16:41:03.068 19013 26546 E UploadFileOperation: Upload of /storage/170A-0829/DCIM/Camera/IMG_20170731_164022093.jpg to /Camera//IMG_20170731_164022093.jpg: Local storage full
    07-31 16:41:03.068 19013 26546 D UploadsStorageManager: updateDataseUploadResult uploadResult: com.owncloud.android.lib.common.operations.RemoteOperationResult@fa8c359 upload: com.owncloud.android.operations.UploadFileOperation@6367b1e
    07-31 16:41:03.074 19013 26546 V UploadsStorageManager: Updating /storage/170A-0829/DCIM/Camera/IMG_20170731_164022093.jpg with status:UPLOAD_FAILED and result:UNKNOWN (old:/storage/170A-0829/DCIM/Camera/IMG_20170731_164022093.jpg status:UPLOAD_IN_PROGRESS result:-1)
    07-31 16:41:03.074 19013 26546 V UploadsStorageManager: Updating /storage/170A-0829/DCIM/Camera/IMG_20170731_164022093.jpg with status=UPLOAD_FAILED
    07-31 16:41:03.081 19013 26546 D UploadsStorageManager: updateUpload returns with: 1 for file: /storage/170A-0829/DCIM/Camera/IMG_20170731_164022093.jpg
    07-31 16:41:03.081 19013 26546 D UploadsStorageManager: notifyObserversNow
    07-31 16:41:03.082 19013 26546 D FileUploader: NotifyUploadResult with resultCode: LOCAL_STORAGE_FULL

The local storage is definitely not full (neither the SD card, nor the internal storage), so there seems to be a problem with the storage. Not sure what information I need to provide for you to be able to debug this, so just let me know.

**Comment by mario** [comment]
Sorry for the trouble, could you try the following APK?


https://cloud.nextcloud.com/s/pAbCOxR71TEhGgR

**Comment by mario** [comment]
Fixed in 2.0.0.
