### ISSUE TITLE
Show/Hide hidden files option not updated till restart

### ISSUE THREAD

**Issue by memen45** [nextcloud/android#1250]
### Actual behaviour
-No change in file browser after changing the option 'Show hidden files' in Settings. Only after restarting the app the settings get updated and the files and folders are correctly hidden or shown, depending on the setting.

### Expected behaviour
-Settings should have immediate effect on the view in file browser

### Steps to reproduce
1. Go to Settings
2. turn on or off option "Show hidden files"
3. Navigate to a folder containing hidden files or folders

### Environment data
Android version: 6.0

Device model: H60-L04

Stock or customized system: EMUI 4.0

Nextcloud app version: 1.4.3

Nextcloud server version: 12.0.0

### Logs 
Not Applicable

**Comment by tobiasKaminsky** [comment]
I have tested in our current master version and there it is working, so it will work also in next release (1.5.0).
Thank you for your bugreport.
If it will not work in 1.5.0, please reopen.
