### ISSUE TITLE
Folder bidirectional sync

### ISSUE THREAD

**Issue by AR2000AR** [nextcloud/android#12524]
I recently switch from a other self hosted cloud that had a feature to sync a folder anywhere on the phone with one on the drive.

The feature I'm looking for is like the current automatic upload feature but it would also download files from nextcloud to the phone or tablet.

For now I use the sync feature, but I cannot choose where exactly the folder is synced to and it doesn't look like the sync is bidirectional and/or automatic.

**Comment by GTP95** [comment]
If you're using the Android client, you just stumbled upon one of the oldest unresolved Nextcloud issues, see issue #19 for this problem's discussion and possible workarounds.
