### ISSUE TITLE
File Details - Activity not loading

### ISSUE THREAD

**Issue by OdinsAuge** [nextcloud/android#12564]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Browse and file in the Android app.
2. Open Details View
3. Details view opens and Activity tab is stuck on loading 

### Expected behaviour

The activities should load and it should be possible to read/write comments.

### Actual behaviour

The activities don't load, 3 fake entries shown as a grey criclke and grey bars are flashing. The comment field is there, sending a comment results in a crash/error (see logs).

![IMG_20240215_080953](https://github.com/nextcloud/android/assets/1121917/32df186b-6438-4d85-b81b-22f78de3eff3)

### Android version

14

### Device brand and model

Google Pixel 8

### Stock or custom OS?

Stock

### Nextcloud android app version

3.27.0

### Nextcloud server version

28.0.2

### Using a reverse proxy?

Yes

### Android logs

![IMG_20240215_081004](https://github.com/nextcloud/android/assets/1121917/a9270105-dcc8-409a-9306-594cd6463fc4)

### Server error logs

```bash
no errors on server side
```

**Comment by AndyScherzinger** [comment]
Fix will ship with 3.28.1 - see https://github.com/nextcloud/android/pull/12541
