### ISSUE TITLE
Can't setup account: Nextcloud angehalten

### ISSUE THREAD

**Issue by schulmar** [nextcloud/android#1259]
### Actual behaviour
Opening the app after installation I shortly see the input form and then get a blank white screen behind a popup that says "Nextcloud angehalten" with only an ok-button that pushes the app into background.
When I open it again I can briefly see the form again and then its back to the blank screen with popup again.

### Expected behaviour
The app opens and I can enter the credentials. (The dev version 20170727 from F-Droid works as expected.)
 
### Steps to reproduce
1. Install the Nextcloud app (from F-Droid?)
2. Open Nextcloud app
3. Try to enter credentials

### Environment data
Android version: 5.0.1 (another phone: Android 5.x.x)

Device model: Samsung Galaxy S4 (the other phone: Fairphone 2)

Stock or customized system: stock (stock)

Nextcloud app version: 1.4.2

Nextcloud server version: 12.0.0

### Logs
There is nohting in the serverside logs as I cannot even enter the server information.

**Comment by tobiasKaminsky** [comment]
I guess it is the same as in #946, it is already fixed as you can see in dev version and will be in next official release.

**Comment by schulmar** [comment]
@tobiasKaminsky Sorry, did not find that one while searching for the problem. Is there already an ETA for that release?

**Comment by tobiasKaminsky** [comment]
It depends on google releasing a stable toolchain, but we hope this month.
