### ISSUE TITLE
Grey-out auto upload options until enabled

### ISSUE THREAD

**Issue by mario** [nextcloud/android#1260]
As suggested by @gahujipo here: https://github.com/nextcloud/android/pull/797#issuecomment-319973580

> The preferences window for auto upload shows a switch next to "Preferences for auto uploading". At the first sight it was not clear to me that that switch is uses to enable the auto upload feature for that folder pair. My idea was to grey out the options in the window unless the switch is set to true.

**Comment by tobiasKaminsky** [comment]
Nice idea :+1:

**Comment by mario** [comment]
Yup, like the idea. That's called good UX :P
