### ISSUE TITLE
Add a retry button in the notification drawer when uploads fail

### ISSUE THREAD

**Issue by gahujipo** [nextcloud/android#1261]
### Actual behaviour
When auto upload fails e.g. when Nextcloud server is only available on the LAN there is a sync error message in the notification drawer. 

### Expected behaviour
As mentioned by @mario here https://github.com/nextcloud/android/pull/797#issuecomment-319997004 it could be an idea for future releases to offer the user (maybe in expert mode only) a retry button in the notification drawer. In that case a resync can be started immediately without waiting for next sync interval and without opening the app and trigger resync in expert mode. 
 
### Steps to reproduce
1. Use a Nextcloud sever that is available only on the LAN.  
2. Enable Auto upload for camera folder
3. Leave WiFi
4. Take a picture with the phones camera.
5. Sync will fail. 
6. Imagine you are in a hurry and need to leave home/office immediately to catch the bus. You have to open the app, enable expert mode in settings, then got to Uploads Menu, click the three dots and trigger a forced sync. 

### Environment data
Nextcloud app version: tested with dev 20170730

**Comment by tobiasKaminsky** [comment]
While I can imagine the need of a manual retry I think putting it in the navigation drawer is too prominent, even in expert mode.

>  then got to Auto Upload, click the three dots on the camera folder and trigger a forced sync.

I thought "retry" is in option menu of upload view?

Also, if an upload fails it has nothing to do with auto upload any more. You can simply go to upload view and click "retry failed".
"Retry" of Auto Upload is rescanning the folders for missing uploads and then will upload them.

**Comment by gahujipo** [comment]
> I thought "retry" is in option menu of upload view?
Also, if an upload fails it has nothing to do with auto upload any more. You can simply go to upload view and click "retry failed".

You're right. I changed that part in the comment. 

> I think putting it in the navigation drawer is too prominent, even in expert mode.

On that I'm holding a contrary opinion. ;-) Maybe give the user the option to opt in for that button?

**Comment by mario** [comment]
Must say I agree with @tobiasKaminsky. In fact, everybody knows my goal is to completely eliminate manual control and leave it all to machines - they're quite smart these days :)

**Comment by joshtrichards** [comment]
Related: #1256
