### ISSUE TITLE
AutoUpload: upload also subfolder

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#1263]
Via email:
Currently a list of directories with pictures is presented. My camera app creates subdirectories, I'd like to add the parent directory and all its subdirectories.

I think this should be the default to watch the folders also recursively.
Maybe for 1.5.1 @mario?

**Comment by mario** [comment]
This is how it works already

**Comment by tobiasKaminsky** [comment]
Cool :-)
Then I guess that the email reporter used the regular dev version and not the special auto upload one.
So closing :-)

**Comment by kaefert** [comment]
I'm using the Nextcloud App 2.0.1 installed via FDroid.

It includes an automatic upload feature, which allows to upload in year/month subfolders, or when not checking this it completely flattens the folder structure and uploads any new files of any of the contained subfolders to the specified remote folder without the subfolder structure.

@tobiasKaminsky you mentioned a "special auto upload version" - where can I get this?

**Comment by tobiasKaminsky** [comment]
There was for a short time an independent testing app which customization for auto upload, but this was, as long way back last year.
So now there are:
- nextcloud dev, available via direct download or fdroid (independent bleeding edge app)
- nextcloud, available on fdroid/gplay, currently 2.0.1, soon next version will be released
- nextcloud RC, available on fdroid -> versions, or google play as beta subscriber, for testing the upcoming stable release

**Comment by kaefert** [comment]
Okey. And does the 1st or the 3rd of your list have a different behavior than the 2nd concerning the auto upload feature?

Was the code for this customized auto upload feature not merged back into the main branch of the app? Why not? Was it bad quality or had serious unfix-able bugs?

**Comment by tobiasKaminsky** [comment]
Custom auto upload folders are available after enabling "expert mode" on settings.

**Comment by kaefert** [comment]
Yes I have enabled that and I can add custom auto upload folders. But what I'd like would be custom auto upload folders that honor the existing sub-folder structure.

For example I would like to backup Whatsapp Images and keep the sent pictures in their separate "sent" sub-folder, but the auto upload feature flattens every folder structure.

**Comment by mario** [comment]
Ah I guess we currently create only 1 level folders. I'll improve this for 3.1.

**Comment by tobiasKaminsky** [comment]
As far as I remember folder creation must be adapted, as currently it only supports creating 1 subfolder hierarchy, eg: /A/ exists, you can create /A/B/C, but not directly /A/B/C/D, which may be necessary.

**Comment by mario** [comment]
Implemented ;)
