### ISSUE TITLE
No buttons during camera upload in Lineage

### ISSUE THREAD

**Issue by UteHaus** [nextcloud/android#12645]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. open the Nextcloud app
2. choose at the add menu (plus button on the bottom right corner )  the camera upload 
3. take picture 

### Expected behaviour

A button bar to confirm the picture upload or cancel the camera upload or take the photo again.

### Actual behaviour

Non button/icon to confirm or cancel the picture upload.

**But** if you know where the buttons are you can press them and the picture will be uploaded.

### Android version

13, 14 LinageOS

### Device brand and model

google pixel 4

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

3.28.0

### Nextcloud server version

28.0.2

### Using a reverse proxy?

Yes

### Android logs

No Logs found

### Server error logs

```bash
Not important.
```

### Additional information

But if you know where the buttons are you can press them and the picture will be uploaded. It looks like the buttons exist but the icons are not displayed correctly or the color of the icons is transparent. :question: :question: 

Here is a screenshot of the camera upload, without buttons.
![Screenshot_20240304-140935_Trebuchet](https://github.com/nextcloud/android/assets/31124997/7b0afc12-9cb5-4662-82eb-a58ff922828f)

**Comment by joshtrichards** [comment]
Interesting. This provides more information for at least one of the scenarios that was reported in #12393.

However I'm not sure what we can really do about this. When we trigger the camera intent in Android we're just telling the OS to open the Camera app. We don't get to define any of these bits. And, so far, this seems limited to Lineage so something weird is going on there. This odd behavior doesn't happen on my Pixel running the stock OS for example.

**Comment by UteHaus** [comment]
Thanks for the fast feedback.
This seems to be a problem with the camera app from  lineage os.  I open a issue on lineageos ([link](https://gitlab.com/LineageOS/issues/android/-/issues/6839)). 
Here is a video in which you can see the buttons when you swipe your finger from bottom to top .

https://github.com/nextcloud/android/assets/31124997/9a5acd8d-ead2-4ccb-a2c4-ba33d8429e50

**Comment by UteHaus** [comment]
With the last LineageOS (21.0-20240502) update the bug was fixed.
