### ISSUE TITLE
Remove unintuitive "clear finished uploads"

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#1264]
@jospoortvliet pointed out that the last entry is misleading as it can be understood as
- finished = successfully finished
- finished = successful & failed

It someone assumes the first all non-pending uploads will be removed and one has to find the failed uploads manually.
So the idea is to remove this entry. 
:+1:  it is more clear what the entries do
:-1: one click more needed if successful & failed shall be removed

![2017-08-04-074540](https://user-images.githubusercontent.com/5836855/28955871-bce58bfe-78e9-11e7-9c68-a77547422ca8.png)

**Comment by mario** [comment]
👍 

1.5.1? :)
