### ISSUE TITLE
account login screen opens again on back press

### ISSUE THREAD

**Issue by mahibi** [nextcloud/android#12652]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1) login with new account in files app
2) after successful login, press back button

### Expected behaviour

app is closed

### Actual behaviour

login screen appears again.

Could be fixed by either set intent flags or by custom handling of onBackPressed

### Nextcloud android app version

3.28.0

**Comment by aloksingh20** [comment]
I want to work on this issue, please assign it to me

**Comment by yadnyeshdande** [comment]
Can I work on this issue?

**Comment by alperozturk96** [comment]
Hello. Thanks for the messages, it's really great to see support @aloksingh20 @yadnyeshdande 🙂

**Comment by raviSaharan07** [comment]
Is this issue still open?

**Comment by neeldoshii** [comment]
Hello @alperozturk96 @mahibi, is this issue progress on stale? If yes can I work on this?

**Comment by joshtrichards** [comment]
Related: #11392

**Comment by Shr3yash** [comment]
Hi team, is this issue still open?
