### ISSUE TITLE
Timeouts while assembling chunks on external storage

### ISSUE THREAD

**Issue by TGion** [nextcloud/android#12665]
### Is your feature request related to a problem? Please describe.
My Nextcloud instance is backed by a (slow) external storage.
When I upload files bigger than `ChunkedFileUploadRemoteOperation.CHUNK_SIZE_MOBILE`, they will be chunked. The chunks will be saved to a temporary folder on the web server (not external storage).
After the upload reaches 100%, the chunks are assembled on my external storage with `MOVE`
After roughly 30 seconds the NC App throws an error: `An error occured while waiting on the server...`
In the background the file is still assembled on the external storage. The App correctly realizes after a while the file is actually there and marks the upload as completed (Same file found on remote. Skipping upload.)

I dont run into any timeout / file size issues when I use:
- Web Client on an external storage folder
- NC App on a folder directly on the web server (no external storage)

Also my nginx logs show that the client (App) closes the connection when the error is shown on the App. Iam convinced this has nothing to do with the usual time out issues of big files.

I assume:
1. NC app has a fixed timeout for responses of operations on the server, e.g. `MOVE`. Since the server is still busy assembling the chunks, no response is send to the App and the timeout is triggered.
2. There is no way to disable server-side chunking for files uploaded by the app.

### Describe the solution you'd like
I am open to suggestions. The following might work:
1. Possibility to disable / change chunking of uploads from the NC app. Preferably on the server-side. 
Similiar to `config:app:set files max_chunk_size --value 0` which doesn't affect chunking by the app.
2. Increase timeout for operations by the App on the server. Alltough I am not aware of any side effects. 

### Describe alternatives you've considered
Get a faster external storage.

**Comment by joshtrichards** [comment]
Related: 

nextcloud/android-library#696
nextcloud/android-library#709

**Comment by TGion** [comment]
Thanks @joshtrichards for the insight.
That leaves the minimum required bandwith for external storages at roughly 5,5 MB/s. Anything slower will result in timeouts i guess.
Anyhow, thanks again for the links. I somehow missed them.
