### ISSUE TITLE
CIFS Shares from NC12 are not working with App

### ISSUE THREAD

**Issue by mitch-geht-ab** [nextcloud/android#1267]
### Actual behaviour
Since my upgrade to NC12, the app (Android nor iOS) isn't showing the external CIFS Shares.
In the NC12 Web interface they are shown.

### Expected behaviour
External CIFS shares should be listet with other directories or files.

### Steps to reproduce
1. Fresh install NC12
2. Add external Share App
3. Add an extrnal CIFS share

### Environment data
Android version:
7.0

Device model: 
Samsung S8

Stock or customized system:
Stock

Nextcloud app version:
Android Stable 1.4.3
Android Dev 20170804

Nextcloud server version:
12

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"wJMhFtSccW8xxMCGvdhX","level":0,"time":"2017-08-04T19:21:04+00:00","remoteAddr":"192.168.2.33","user":"069e27e2-aebd-1030-94bc-fb0f24389eba","app":"core","method":"PROPFIND","url":"\/nextcloud\/remote.php\/webdav\/","message":"could not get login credentials because the token is invalid","userAgent":"Mozilla\/5.0 (Android) ownCloud-android\/20170804","version":"12.0.0.29"}
{"reqId":"zXqbuXYuweqcDEdI6Aro","level":0,"time":"2017-08-04T19:21:04+00:00","remoteAddr":"192.168.2.33","user":"069e27e2-aebd-1030-94bc-fb0f24389eba","app":"core","method":"PROPFIND","url":"\/nextcloud\/remote.php\/webdav\/","message":"could not get login credentials because the token is invalid","userAgent":"Mozilla\/5.0 (Android) ownCloud-android\/20170804","version":"12.0.0.29"}
{"reqId":"zXqbuXYuweqcDEdI6Aro","level":0,"time":"2017-08-04T19:21:04+00:00","remoteAddr":"192.168.2.33","user":"069e27e2-aebd-1030-94bc-fb0f24389eba","app":"OC\\Files\\Cache\\Scanner","method":"PROPFIND","url":"\/nextcloud\/remote.php\/webdav\/","message":"!!! Path '' is not accessible or present !!!","userAgent":"Mozilla\/5.0 (Android) ownCloud-android\/20170804","version":"12.0.0.29"}
{"reqId":"IAY19blfw6Cu4FKZA1XU","level":0,"time":"2017-08-04T19:21:28+00:00","remoteAddr":"192.168.2.33","user":"069e27e2-aebd-1030-94bc-fb0f24389eba","app":"core","method":"PROPFIND","url":"\/nextcloud\/remote.php\/webdav\/","message":"could not get login credentials because the token is invalid","userAgent":"Mozilla\/5.0 (Android) ownCloud-android\/20170804","version":"12.0.0.29"}
```

**Comment by tobiasKaminsky** [comment]
@MorrisJobke (@ nextcloud/server does not seem to exists?) 
I always thought that this is intransparent for the clients? -> for them it does not matter how storage is connected, they always get a list of files/folders via webdav?

**Comment by mitch-geht-ab** [comment]
I thought the same. But in the release notes of NC12 is something written that auth. has been changed.

I've enable debuging and here are some logs:
{"reqId":"wJMhFtSccW8xxMCGvdhX","level":0,"time":"2017-08-04T19:21:04+00:00","remoteAddr":"192.168.2.33","user":"069e27e2-aebd-1030-94bc-fb0f24389eba","app":"core","method":"PROPFIND","url":"\/nextcloud\/remote.php\/webdav\/","message":"could not get login credentials because the token is invalid","userAgent":"Mozilla\/5.0 (Android) ownCloud-android\/20170804","version":"12.0.0.29"}
{"reqId":"zXqbuXYuweqcDEdI6Aro","level":0,"time":"2017-08-04T19:21:04+00:00","remoteAddr":"192.168.2.33","user":"069e27e2-aebd-1030-94bc-fb0f24389eba","app":"core","method":"PROPFIND","url":"\/nextcloud\/remote.php\/webdav\/","message":"could not get login credentials because the token is invalid","userAgent":"Mozilla\/5.0 (Android) ownCloud-android\/20170804","version":"12.0.0.29"}
{"reqId":"zXqbuXYuweqcDEdI6Aro","level":0,"time":"2017-08-04T19:21:04+00:00","remoteAddr":"192.168.2.33","user":"069e27e2-aebd-1030-94bc-fb0f24389eba","app":"OC\\Files\\Cache\\Scanner","method":"PROPFIND","url":"\/nextcloud\/remote.php\/webdav\/","message":"!!! Path '' is not accessible or present !!!","userAgent":"Mozilla\/5.0 (Android) ownCloud-android\/20170804","version":"12.0.0.29"}
{"reqId":"IAY19blfw6Cu4FKZA1XU","level":0,"time":"2017-08-04T19:21:28+00:00","remoteAddr":"192.168.2.33","user":"069e27e2-aebd-1030-94bc-fb0f24389eba","app":"core","method":"PROPFIND","url":"\/nextcloud\/remote.php\/webdav\/","message":"could not get login credentials because the token is invalid","userAgent":"Mozilla\/5.0 (Android) ownCloud-android\/20170804","version":"12.0.0.29"}

**Comment by MorrisJobke** [comment]
@mitch-geht-ab How do you login? What credential type is used for the external storages? cc @LukasReschke for the login stuff, @ChristophWurst for the token error log and @icewind1991 for the external storages.

**Comment by mitch-geht-ab** [comment]
@MorrisJobke What dou you mean with "how"? Via Nextcloud App. I guess it's using the WebDav interface.
User Backend is LDAP ("LDAP user and group backend" app, version 1.2.1).
For the external Storage (CIFS) authentication "Log-in credentials, save in session" is selected.

**Comment by MorrisJobke** [comment]
> @MorrisJobke What dou you mean with "how"? Via Nextcloud App. I guess it's using the WebDav interface.

Is it already the new 1.5.0 beta Android app or still the 1.4.x series?

**Comment by tobiasKaminsky** [comment]
>Android Stable 1.4.3
> Android Dev 20170804

So both of it

**Comment by MorrisJobke** [comment]
> For the external Storage (CIFS) authentication "Log-in credentials, save in session" is selected.

Could you use "Log-in credentials, save in database", log out in web UI, login in web UI and then try to re-login in the android app. Does it then work?

**Comment by MorrisJobke** [comment]
> Could you use "Log-in credentials, save in database", log out in web UI, login in web UI and then try to re-login in the android app. Does it then work?

See https://docs.nextcloud.com/server/12/admin_manual/configuration_files/external_storage/auth_mechanisms.html for an overview of possible options.

**Comment by mitch-geht-ab** [comment]
Hmmm "Log-in credentials, save in database" seems to work with the Dev-App Version 20170804.

Written on the documentation behind your link:
> The Log-in credentials, save in database mechanism uses the Nextcloud login credentials of the user to
> connect to the storage. These are stored in the database encrypted with the shared secret. This allows
> to share files from within this mount point.

Does this still work when user password is changed in the LDAP backend? 
And what is the "shared secret"? The user password from the LDAP backend? 

I wouldn't prefer it when my user password is additionally stored in a second place, aside from the LDAP backend, which is my leading user backend.

**Comment by MorrisJobke** [comment]
> Does this still work when user password is changed in the LDAP backend?

On the next login it will update the password in the DB.



> And what is the "shared secret"?

A config key that is stored in the config.php and automatically generated on install.



> I wouldn't prefer it when my user password is additionally stored in a second place, aside from the LDAP backend, which is my leading user backend.


This looks like a limitation, because the android app will also use in the future an app password, that is a token only associated to the user account and this specific device (which allows revocation of the device). But maybe @ChristophWurst knows it better.

**Comment by ChristophWurst** [comment]
> This looks like a limitation, because the android app will also use in the future an app password, that is a token only associated to the user account and this specific device (which allows revocation of the device). But maybe @ChristophWurst knows it better.

Both app passwords and browser logins create an entry in the database which stores the login password encrypted by the app password or session id. Since nc12 we make use of this encrypted password for external storage as described in https://github.com/nextcloud/server/pull/2044.

**Comment by mitch-geht-ab** [comment]
> On the next login it will update the password in the DB.
> ...
> A config key that is stored in the config.php and automatically generated on install.
Hmmm, okay. Seems that I have to accept all of this :)

Maybe it would not so confusing when you remove the option "Log-in credentials, save in session" from the drop-down?
