### ISSUE TITLE
The error keeps popping up

### ISSUE THREAD

**Issue by MacClancys** [nextcloud/android#12678]
### Additional context

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by strugee** [comment]
@MacClancys can you fill out the issue template? Nobody can tell what error you're talking about, much less solve it, because you haven't provided any information.

**Comment by joshtrichards** [comment]
Agreed. Also, use the Bug template when you do so. It appears you used the Enhancement one. I'll close this since it's empty but don't hesitate to create a new issue. :-)
