### ISSUE TITLE
Hide trash button in upload view (when not in expert mode)

### ISSUE THREAD

**Issue by mario** [nextcloud/android#1268]

**Comment by tobiasKaminsky** [comment]
Not sure about this...
If I manually upload lots of files and select a wrong one by mistake I want to be able to remove it.
Same if auto uploads queues my last images taken by camera and there are some blurry.
Canceling/pausing uploads should stay as easy as possible

Have the user to enable expert mode first is to complicated, I think.

**Comment by mario** [comment]
You're not completely wrong on this, but there's a reason why it needs to stay in the list hm... will think about it.

**Comment by xXSTrikeXx** [comment]
You can implement another Overlay in the upper corner thats allows the user to "undone" his action. In the settings you can take the setting to take it on or off the Overlay. In this way there is no expert mode needed 👍 
You can see many suggestions in an e-mail app for example.

**Comment by tobiasKaminsky** [comment]
Undone is a nice idea, but should be a new issue: https://github.com/nextcloud/android/issues/1305

**Comment by mario** [comment]
Closing since we never really came into agreement on this.
