### ISSUE TITLE
Allow Long Press Copy Options in Text Viewer

### ISSUE THREAD

**Issue by cwmke** [nextcloud/android#127]
### Actual behaviour
Open any text based document in nextCloud's Android app.  Long press on some text and nothing happens.

### Expected behaviour
When long pressing on text in most apps in Android, you are presented with the ability to select a certain amount of text.  Afterwards, you are then presented with options to select all, copy, or share.  Search could be another good option to have as a default.

### Environment data
Android version: 6.0.1
Device model: Nexus 6p
Stock or customized system: Customized
Nextcloud app version: F-droid 20160621

PR: #134

**Comment by AndyScherzinger** [comment]
Calling @nextcloud/android for discussion and voting. I vote to approve this issue since it helps usability and should be a rather simple change complexity wise thus I also flagged it a starter issue. 

Awaiting your comments 😃

**Comment by jancborchardt** [comment]
For sure selecting text should be possible when viewing a text file! :)

(In the long term even editing should be possible, but that’s a separate issue. ;D

**Comment by tobiasKaminsky** [comment]
PR #134 
For editing text file there is already an issue.

**Comment by tobiasKaminsky** [comment]
Merged, will be in next release.

**Comment by jancborchardt** [comment]
@tobiasKaminsky aaawesome, that was quick! :) Great work

**Comment by AndyScherzinger** [comment]
RC1 is out and contains this change for testing :)
