### ISSUE TITLE
Stuck at downloading 100%, again

### ISSUE THREAD

**Issue by Grocel** [nextcloud/android#12711]
For details, please look at: https://github.com/nextcloud/android/issues/8308#issuecomment-1985715237

It happens for me on a Fairphone 4 5G with Android 13 (Stock).
App version: 3.28.0
Server version: 27.1.5

For me it is reproducible when I change a .kdbx file (Keepass Password Safe file)

Screenshot:
![Screenshot_20240320-183148](https://github.com/nextcloud/android/assets/2457653/ae3a0dc6-20df-4117-a031-64e954394bd0)

**Comment by af7567** [comment]
I ran into this problem today too for the first time, also with a kdbx file.
Using app version 3.28.0 installed from the Play Store. Server version 28.0.3
I did see an issue open about it a few weeks ago, but hadn't had the problem then.

**Comment by githubber4ever** [comment]
Got the same issue on my Google Pixel 4a (Android 13) since some weeks. iPad Mini connecting to the same server works without any issues.

**Comment by ostasevych** [comment]
Try 3.28.2 version from github.

**Comment by ryester19** [comment]
> Try 3.28.2 version from github.

Still happening

**Comment by konstin** [comment]
I have this error happening whenever a file changes quickly. In my case the download sometimes gets stuck at 100%, sometimes at nonsensical (like below). The main problem here is that notification can't be dismissed, the only way to remove it is to force-terminate the app.

![Screenshot](https://github.com/nextcloud/android/assets/6826232/4393c0cb-4d0d-476b-9245-08a9464edda6)

**Comment by githubber4ever** [comment]
still not fixed with app version 3.29.0 even there was some adjustment to download/upload handling #12794

**Comment by hellpe** [comment]
I'm having the exact same behavior as @konstin, complete with the "2147483647%" values, using version 3.29 from F-Droid

**Comment by Grocel** [comment]
@AndyScherzinger: I guess my issue of some files being stuck at 100% is a side effect of the internal value being `2147483647%` then?
