### ISSUE TITLE
Difficulty accessing Nextcloud via IPv6

### ISSUE THREAD

**Issue by Alex15622** [nextcloud/android#12722]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

When I restart my server and running the Nextcloud, I usually cannot access the cloud via a mobile device if this is connected to the Internet with mobile data. I think it's because my phone is only assigned an IPv6 address if it is connected to the internet with mobile data. If my cell phone is connected to the WIFI and has an IPv4 address, there are no problems. The problem occurs via access via the web interface as well as access with the Nextcloud Android app. Strangely enough, I found out that if I first log into the nextcloud via WiFi in the web browser on my phone. Then turn off the WiFi and reload the page with mobile data (IPv6 only) and then access the Nextcloud homepage again in a new private tab. Sometimes several attempts are necessary. However, access via mobile data (IPv6) after this process is possible without any problems even after a longer period of time. I think this is a very strange workaround, but so far it has worked without any problems for me.

### Expected behaviour

Actually, the nextcloud should be accessible via IPv4 and IPv6.

### Actual behaviour

As described under steps to reproduce, I only get access via mobile data (IPv6) by using this strange workaround.

### Android version

14

### Device brand and model

Google Pixel 6

### Stock or custom OS?

Stock

### Nextcloud android app version

Android 3.28.0

### Nextcloud server version

Nextcloud AIO 27.1.7 running in Docker Engine on Ubuntu 22.04

### Using a reverse proxy?

No

**Comment by joshtrichards** [comment]
> The problem occurs via access via the web interface as well as access with the Nextcloud Android app

This doesn't sound like an issue with the Android client if it impacts your web browser as well. I suggest posting your Server topology and configuration on the Nextcloud Help Forum (https://help.nextcloud.com) seeking some guidance or suggestions.
