### ISSUE TITLE
Backup of Calendar and Contacts not working

### ISSUE THREAD

**Issue by Markoise** [nextcloud/android#12741]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Start Backup of Calender and Contacts

### Expected behaviour

A Backup of all Calendars will be created

### Actual behaviour

Only the calendar of my contacts' birthdays is backed up. Unfortunately, my calendar with all my appointments is not.

### Android version

14

### Device brand and model

Pixel 7

### Stock or custom OS?

Stock

### Nextcloud android app version

3.28.0

### Nextcloud server version

28.0.3

### Using a reverse proxy?

No

**Comment by Markoise** [comment]
In addition to the birthday calendar, whose backup is not really important, a subscribed calendar is now also saved. 
Unfortunately, my own calendar, which I use and update daily, is not included in this backup.

**Comment by Markoise** [comment]
Apparently the backup works with all calendars since version 3.29.0. 
Even those subscribed to from other sources. In my opinion, this is not necessary, but does not interfere.

**Comment by beedaddy** [comment]
I'm running Nextcloud App version 3.30.0 from F-Droid store and I have noticed that for months (years?) only one calendar (and not my default one) has been backed up. So, for me, the problem still persists.

**Comment by Markoise** [comment]
> I'm running Nextcloud App version 3.30.0 from F-Droid store and I have noticed that for months (years?) only one calendar (and not my default one) has been backed up. So, for me, the problem still persists.

Strange. There is no problem with version 3.29.2 from the Google Play Store. However, a backup is made of every calendar (including subscribed calendars).
