### ISSUE TITLE
Calendar and contacts backup should also be created weekly/monthly

### ISSUE THREAD

**Issue by Markoise** [nextcloud/android#12742]
I would very much like to use the "Calendar and contacts backup" function. 

Daily backup creates a backup file for each day, it would also be useful if you could set how many backups you want to keep, e.g. the last 10 backups.

A weekly or monthly backup would perhaps also be quite good.

**Comment by vince-from-nice** [comment]
I fully agree, keeping only the last few backups would be a very nice feature (as well to choose the backup folders).

**Comment by joshtrichards** [comment]
Duplicate of #2296
