### ISSUE TITLE
Assistant tasks not showing in web UI

### ISSUE THREAD

**Issue by viktorix** [nextcloud/android#12750]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Open Assistant in the app.
2. Create a new Assistant task and submit.
3. Check web UI. The task will not be visible there.

### Expected behaviour

Mobile app Assistant shows tasks submitted by web UI, so web UI should show mobile tasks.

### Actual behaviour

Tasks submitted in the mobile app do not show in web UI.

### Android version

14

### Device brand and model

Pixel 6 Pro

### Stock or custom OS?

Stock

### Nextcloud android app version

20240327

### Nextcloud server version

29 beta

### Using a reverse proxy?

I don't know

**Comment by alperozturk96** [comment]
I logged in same account in web and mobile app. In web, I can see only these four type of task.

<img width="942" alt="Screenshot 2024-03-27 at 16 36 27" src="https://github.com/nextcloud/android/assets/67455295/527d54df-0882-459c-ba37-7fe4cb704831">


In mobile, I can only see the Free Prompt

<img width="463" alt="Screenshot 2024-03-27 at 16 37 21" src="https://github.com/nextcloud/android/assets/67455295/0728e614-5036-4a8b-94a2-4bba472e17e8">


How come web not showing free prompt?

**Comment by alperozturk96** [comment]
Update: After successful POST from mobile server returns 500

**Comment by alperozturk96** [comment]
Fixed via this [PR](https://github.com/nextcloud/android/pull/12791)
