### ISSUE TITLE
Add support for notification actions

### ISSUE THREAD

**Issue by mario** [nextcloud/android#1276]
Both in notifications view and notifications bar.

1.5.1? @AndyScherzinger @tobiasKaminsky

**Comment by tobiasKaminsky** [comment]
What for actions? Mockup for both?

**Comment by mario** [comment]
Notifications can carry actions. Sure, I can do mockups/wireframes but it's really simple (also you can't change the design of how actions are shown in notification bar really)

**Comment by AndyScherzinger** [comment]
Sounds good to me, yes. Question is if this is a "feature" because then I'd vote to put it in 1.6.0 but if it is not too much work 1.5.1 would also be fine by me since imho users also like to (always) see something new when the update an app :)

**Comment by mario** [comment]
Its a small improvement to an existing feature.

**Comment by tobiasKaminsky** [comment]
Still nothing said about which actions these should be...
(as also in some other started issues, please provide a real and well explained description of the idea, otherwise it will result in lots of back and forth to understand the idea)

**Comment by mario** [comment]
@tobiasKaminsky https://github.com/nextcloud/notifications/blob/master/docs/ocs-endpoint-v2.md

Because I don't know? :P The API response will tell us WHAT actions... :)

**Comment by mario** [comment]
(If you need more details on this particular issue, I will gladly provide them - for all others scheduled for 1.5.1 (or to be scheduled), I'm happy to explain it further in the issue itself once we actually release 1.5.0 :P)

**Comment by AndyScherzinger** [comment]
Like @mario stated the actions will be part of the server response while we need to decide which actions to show and how to implement this in the UI.

**Comment by tobiasKaminsky** [comment]
Already done.
