### ISSUE TITLE
Regression: Downloaded files stay in tmp, not in intended location

### ISSUE THREAD

**Issue by kescherCode** [nextcloud/android#12775]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Install 3.28.1. Fresh install or upgrade from 3.28.0, does not matter.
2. Download a file using the context menu on a file. Clicking "Sync" on a folder with server-side changes compared to the client has the same behaviour.

### Expected behaviour

The file should be downloaded at the intended storage location, such as `Android/media/com.nextcloud.client/[user@server]/[path]`. The chosen storage location does not matter, it always happens.

### Actual behaviour

Only the folder structure is recreated up until `Android/media/com.nextcloud.client/[user@server]/[containing directory]`. The rest remains in `Android/media/com.nextcloud.client/tmp/[user@server]/[path]`.

### Android version

14

### Device brand and model

Fairphone 4

### Stock or custom OS?

Custom (CalyxOS)

### Nextcloud android app version

3.28.1

### Nextcloud server version

27.1.8

### Using a reverse proxy?

Yes

### Server error logs

```bash
Not applicable
```

### Additional information

I cannot provide logs as I don't want to upgrade to the broken 2.38.1 again. It should be fairly easy to reproduce. 2.38.0 works fine.

**Comment by kescherCode** [comment]
Also still occurs in Nextcloud Dev 20240331.

**Comment by githubtefo** [comment]
Advice: do not try to downgrade by removing the App and installing from F-Droid! All your sync data in the Android device will gone locally and you will need to re-sync everything.

**Comment by kescherCode** [comment]
@githubtefo That is true, however, for me it was the only viable option to continue using the app. So I did bite the bullet and deleted that sync data.

**Comment by soundconjurer** [comment]
I am also still having this issue. It will download the file to a tmp folder and then not transfer it when it is done, thus failing to open something like a PDF.

**Comment by githubtefo** [comment]
Not sure if related, but the Nextcloud Notes App is showing issues since the same update. I had to revert to the previous version too.

**Comment by githubtefo** [comment]
oh, no! I forgot that F-Droid recently started to auto-update packages in the background :face_exhaling: I'm stuck with the non-working versions again, I won't repeat the whole re-sync process again.

> @githubtefo That is true, however, for me it was the only viable option to continue using the app. So I did bite the bullet and deleted that sync data.
oh, no! I forgot that F-Droid recently started to auto-update packages in the background :face_exhaling: I'm stuck with the non-working versions again, I won't repeat the whole re-sync process again.

**Comment by githubtefo** [comment]
> > Not sure if related, but the Nextcloud Notes App is showing issues since the same update. I had to revert to the previous version too.
> 
> So the nextcloud notes app has an issue as well or is it just having sync issues due to this nextcloud sync app issue?
> 
> I use nextcloud notes heavily. This whole issue is a major major issue. I've been running nextcloud for 7 years and this may be the straw that makes me jump. This is basically making my whole instance unusable.

Agreed - Nextcloud user for 6 years in a row for my professional daily activities and this is hard to swallow.
Notes is working fine now using the stable latest version of both Apps - so I cannot tell at this point whether was a problem between different versions or a configuration issue after removing the Nextcloud App an re-setting everything again.

**Comment by danepowell** [comment]
I hate to demand anything from a free product, but I'd like to hear from the maintainers how such a show-stopping bug slipped through. It suggests that not even basic QA was performed on the release, which shakes my confidence in an otherwise lovable project.

**Comment by githubtefo** [comment]
When viewed in context, this pales in comparison to the recent stumble we've experienced in the open source community :laughing: https://www.wired.com/story/jia-tan-xz-backdoor/
> I hate to demand anything from a free product, but I'd like to hear from the maintainers how such a show-stopping bug slipped through. It suggests that not even basic QA was performed on the release, which shakes my confidence in an otherwise lovable project.

**Comment by brianjmurrell** [comment]
> When viewed in context, this pales in comparison to the recent stumble we've experienced in the open source community 😆 https://www.wired.com/story/jia-tan-xz-backdoor/

Apples and oranges.  Why are you even trying to compare a malicious code injection activity with what seems to be an apparent lack of even basic QA?  They are not related on any level whatsoever.

**Comment by githubtefo** [comment]
> > When viewed in context, this pales in comparison to the recent stumble we've experienced in the open source community 😆 https://www.wired.com/story/jia-tan-xz-backdoor/
> 
> Apples and oranges. Why are you even trying to compare a malicious code injection activity with what seems to be an apparent lack of even basic QA? They are not related on any level whatsoever.

Fair enough.I was trying to make a bad joke to distend the frustration, my apologizes.

**Comment by danepowell** [comment]
> Fair enough.I was trying to make a bad joke to distend the frustration, my apologizes.

No worries, I took it in the intended spirit 😄

**Comment by tobiasKaminsky** [comment]
We have a fix and will release a new 3.28.2 today.

**Comment by kescherCode** [comment]
Just linking the backport PR here: https://github.com/nextcloud/android/pull/12816

**Comment by Maxmystere** [comment]
Thank a lot for the quick response to this issue

**Comment by zerwes** [comment]
the dev version 20240404 from fdroid still suffers from the bug ...

**Comment by brianjmurrell** [comment]
> We have a fix and will release a new 3.28.2 today.

This was 5 days ago.  Was the 3.28.2 release made 5 days ago?  If so, does it really take so long from release to being installable in the Play Store?

**Comment by markusdd** [comment]
No idea, that is why I'm asking. Explicitly checked again now and I do not see this version yet.

**Comment by GillesMocellin** [comment]
Hi !
Yes ! Available on play store, and works fine again for me.
