### ISSUE TITLE
AutoUpload: not below certain battery percentage

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#1277]
Idea via email:
Do not use automatic loading at battery level of 30% (10%, 20%, 30% ...)

**Comment by tobiasKaminsky** [comment]
My opinion is that auto upload should obey the power saving settings, e.g. 15% or 5% if the user set this in the android settings, otherwise auto upload should always work.

-> no new setting in our app needed, stay consistent with regular system

**Comment by mario** [comment]
We can simply disable detection jobs & don't do any uploads when in power saver mode.

**Comment by mario** [comment]
(This is possible for 5+ at least)

**Comment by mario** [comment]
This is quite easy, so 1.5.1.

**Comment by sosed213** [comment]
I recently returned from a trip and photographed a lot on a smartphone. Such a setup would very much help me out.

**Comment by tobiasKaminsky** [comment]
My idea was not to disable detection, because then we will miss uploads and this should never happen.
The intention is only to disable upload as this might be very battery consumpting if e.g. ~2gb are uploaded.

**Comment by mario** [comment]
No we would not miss uploads? They would appear once you are not in power
save mode.

**Comment by tobiasKaminsky** [comment]
Ah, right yes. I confused something :-/
Then: if "battery saver" is enabled (done via android preferences)
- disable upload (show some message per each job in uplad view, maybe "upload disabled due to battery saver")
- disable detection job

**Comment by mario** [comment]
Two jobs actually. But yes.

**Comment by mario** [comment]
@sosed213 not yet. We're still working on 1.5.0 :)

**Comment by sosed213** [comment]
I currently have version 1.4.3

**Comment by mario** [comment]
Feature rather than bugfix, so 2.1.0?

**Comment by stalker314314** [comment]
I'll have a stab a this

**Comment by AndyScherzinger** [comment]
Sounds great, looking forward to it :)
If you have any questions don't hesitate!

@mario is the job scheduling expert around but @tobiasKaminsky and I will also support you in any way possible :+1:

**Comment by AndyScherzinger** [comment]
PR for Android 5+ using the power save mode detection #1527

**Comment by AndyScherzinger** [comment]
implemented via #1527 (battery saver mode)
