### ISSUE TITLE
Code formatting

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#1278]
IIRC we want to use "reformat code" of android studio as default code formatting.
We discussed to do this on one certain point when pending PRs are low.
I would rather now vote for enabling this and have a smooth transition.

This is my current setting:
![screenshot_20170807_092601](https://user-images.githubusercontent.com/5836855/29016721-f0c52daa-7b53-11e7-8953-52488ffe2c2b.png)

rearrange code is disabled as this will move all functions / parameters, ...

If you are fine with this I would add this to contributing.md @mario @AndyScherzinger

**Comment by mario** [comment]
I like the rearrange code too :)

But yea, whatever you and @AndyScherzinger want here...

**Comment by tobiasKaminsky** [comment]
The last time I tried rearrange it moved the private fields and missed the comments on them which results in a lot of confusing lines...
We can also enable rearrange code, but then we will to make sure that nothing gets mixed up.

**Comment by tobiasKaminsky** [comment]
Tested it on some files, all went fine but not FileDisplayActivity:

![screenshot_20170807_094957](https://user-images.githubusercontent.com/5836855/29017127-ccdd80de-7b55-11e7-9a18-07415cd1c03e.png)

I have no idea why all new lines get removed, but not the lines on the lower part of the right side.

**Comment by mario** [comment]
Strange...

**Comment by AndyScherzinger** [comment]
I'd say let's activate it *_after_* we merged #797 because that one contains a lot of changed files and should make it to master first :)

**Comment by tobiasKaminsky** [comment]
We have code formatting now synced.
