### ISSUE TITLE
Autoupload retry not working.

### ISSUE THREAD

**Issue by mlopezcoria** [nextcloud/android#1279]
### Actual behaviour
-When there's some connection problem and anautomatic upload is unable to complete, the retry text on the top of the file list doesn't work.

### Expected behaviour
- It should retry the upload when tapping the notice text in the top part of the file list. 
 
### Steps to reproduce
1. Disconnect internet.
2. Take a picture (when Nextcloud app is configured to upload automatically).
3. Tap on the upload error notification.
4. Tap on the retry notice in the top of the upload file list.

### Environment data
Android version: 4.4.2

Device model: 
Samsung Galaxy S4

Nextcloud app version:
1.4.3
Nextcloud server version:
12

**Comment by mario** [comment]
All retries now (in 1.5, soon to be released) work differently - either automatic or top left overflow menu when in expert mode.

**Comment by mario** [comment]
Should be fixed in 2.0.
