### ISSUE TITLE
Nextcloud V3.28.1 not visible in Google Play Store

### ISSUE THREAD

**Issue by MatthiasJSchmidt** [nextcloud/android#12799]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. open google play store
2. available version shown: 3.28.0 (Feb 13th)

### Expected behaviour

3.28.1 should be shown

### Actual behaviour

only 3.28.0 is available

### Android version

14

### Device brand and model

Samsung S23

### Stock or custom OS?

Stock

### Nextcloud android app version

3.28.0

### Nextcloud server version

28.0.4

### Using a reverse proxy?

Yes

**Comment by AndyScherzinger** [comment]
hi @MatthiasJSchmidt can you check again?
I just check the Google Play Developer Console and status is

<img width="615" alt="2024-04-02 19_29_21-Releases overview _ Nextcloud – Mozilla Firefox" src="https://github.com/nextcloud/android/assets/1315170/e09f7a08-0a33-424a-aa3d-04a40ef37616">

So it should pop up any minute for you.

**Comment by MatthiasJSchmidt** [comment]
Magically it appears now.
Thanks.

**Comment by AndyScherzinger** [comment]
You are most welcome! 
Happy to hear it became available for you 👍
