### ISSUE TITLE
Choosing a file using the system file picker from an app results in ENOENT error

### ISSUE THREAD

**Issue by Ericchi** [nextcloud/android#12801]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Open the app you want to load a Nextcloud file into
2. Use the system file picker to choose a file from Nextcloud
3. The result is a ENOENT error and the file briefly displays as 0 bytes on the Nextcloud app

### Expected behaviour

Load the file correctly into the app

### Actual behaviour

ENOENT error

### Android version

14

### Device brand and model

Google Pixel 8 Pro

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

3.28.1

### Nextcloud server version

28.0.4

### Using a reverse proxy?

No

### Additional information

The ROM I'm using is GrapheneOS Stable 2024032100

**Comment by 0815max** [comment]
Same for me. 
Rom is CalyxOS 5.5.3 (Android 14)
Revert to app version 3.28.0 solves the issue for me (for now).
I have checked the file system on my phone and there is a tmp folder next to the folder named by the NC Account and it seems for me that with version 3.28.1 the file is downloaded to the tmp folder but the external app will grab it from the folder named like the account. Maybe this helps.

**Comment by github-k8n** [comment]
Same here, was very afraid when seeing that it shows "new version created" in the details with 0 B filesize. Reverted back to 3.28.0 (F-Droid).
Hope this is fixed soon in a new version in case some less technically inclined users might experience this and maybe lose files due to this...

**Comment by ps-gill** [comment]
I use Nextcloud to synchronize my KeePassXC database across various devices. However, after upgrading to version 3.28.1, I can no longer access any kdbx files. Additionally, I observed that when I access these files through the Nextcloud Android app, their size initially appears as 0 bytes. The correct file size is displayed only after I refresh the view by pulling down on the screen.

![keepassdx-failure](https://github.com/nextcloud/android/assets/1555152/4f6da699-dd07-4969-bd06-203467d3189b)

**Comment by Oclair** [comment]
I have the same issue

**Comment by sedrubal** [comment]
> I have checked the file system on my phone and there is a tmp folder next to the folder named by the NC Account and it seems for me that with version 3.28.1 the file is downloaded to the tmp folder but the external app will grab it from the folder named like the account. Maybe this helps.

I can confirm this behavior. If you copy the successfully downloaded file from the `tmp` folder to the corresponding directory in the folder named like your account, opening the file works again.

**Comment by 1023660** [comment]
> I use Nextcloud to synchronize my KeePassXC database across various devices. However, after upgrading to version 3.28.1, I can no longer open any kdbx files. Additionally, I observed that when I access these files through the Nextcloud Android app, their size initially appears as 0 bytes. The correct file size is displayed only after I refresh the view by pulling down on the screen.
> 
> ![keepassdx-failure](https://private-user-images.githubusercontent.com/1555152/318993119-4f6da699-dd07-4969-bd06-203467d3189b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMzc4NTMsIm5iZiI6MTcxMjEzNzU1MywicGF0aCI6Ii8xNTU1MTUyLzMxODk5MzExOS00ZjZkYTY5OS1kZDA3LTQ5NjktYmQwNi0yMDM0NjdkMzE4OWIuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDNUMDk0NTUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzA1YTQ5YTg5MjFmNzlhMTExMTdjMWYyYTE0YmNmNGQwMTNmNjMwNTNlYzk1Zjc1OTY5NzAyMGQ3YjIxNTdkMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.v2pwBd2W6Emnn5ab6tYeB5JGtp03ONWTeQN9Ip-92L0)

The same for me.

**Comment by a73s** [comment]
Reverting to 3.28.0 on fdroid fixes the issue.

**Comment by brianjmurrell** [comment]
> Reverting to 3.28.0 on fdroid fixes the issue.

Which only works if you installed with f-droid.  But as much as I love f-droid and the entire concept of a FOSS marketplace the one thing that prevents me from installing more things from it (i.e. when I have a choice between f-droid and the Google Play store) is that it has no concept of remembering and restoring all of the apps I previously had installed when I have to factory reset my phone, or I get a new one.

Whereas Google Play store apps that I had installed all get re-installed on the new/reset device.

So alas, given that I had a choice to install the NC app from f-droid or Google Play, I chose the latter, as much as I would have preferred the former.   So now don't get any option to revert.  Well, other than removing it, re-installing it from f-droid, rolling it back and then forgetting to re-install it manually the next time I have to restore my phone.

**Comment by josenj** [comment]
> I use Nextcloud to synchronize my KeePassXC database across various devices. However, after upgrading to version 3.28.1, I can no longer open any kdbx files. Additionally, I observed that when I access these files through the Nextcloud Android app, their size initially appears as 0 bytes. The correct file size is displayed only after I refresh the view by pulling down on the screen.
> 
> ![keepassdx-failure](https://private-user-images.githubusercontent.com/1555152/318993119-4f6da699-dd07-4969-bd06-203467d3189b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxODk0ODYsIm5iZiI6MTcxMjE4OTE4NiwicGF0aCI6Ii8xNTU1MTUyLzMxODk5MzExOS00ZjZkYTY5OS1kZDA3LTQ5NjktYmQwNi0yMDM0NjdkMzE4OWIuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDRUMDAwNjI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YThiYzQ3MTcxNDcxMDBkMTYxY2VlNWIzMmYyNWRjZTRmMDc4MTg5YjNiZjU3MzkyODM3MWMxOTUxYzhjOGMxYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.DmcYLrda7256W1rluVZVM8yxZO3vVHLt7bQSG6DGLO4)

I too use `KeePassDX` on Android and got the same error.  I downgraded to NextCloud version 3.28.0 and the issue is not there.

**Comment by josenj** [comment]
Same here.  Downgraded to Nextcloud 3.28.0 and the issue is not there.

**Comment by wdlkfjgnb** [comment]
Same issue on a google pixel 6 with android 14

**Comment by tobiasKaminsky** [comment]
We have a fix and will release a new 3.28.2 today.

**Comment by Markus872** [comment]
ok then i wait with fdroid. I have the same issue with KeePassXC

**Comment by sedrubal** [comment]
Guys, this is an issue tracker, not a community forum. Please keep it clean and don't share your stories about your family pictures, your future plans about which apps you want to use, or when you want to update or not, on GitHub.
Only post new information that might help the developer and use reactions if you want to say "I'm affected, too".

**Comment by krichter722** [comment]
Can this be released as a hotfix, please? Waiting for https://github.com/nextcloud/android/pull/12823 which blocks the milestone 3.28.2 and is still in draft mode seems unnecessary. This is a high-impact bug and since choosing versions in Google Play Store isn't possible, Nextcloud users are denied access to their password databases (without workarounds).

**Comment by brianjmurrell** [comment]
I have to agree.  There is NOTHING that should prevent this fix from causing a new hotfix release to made to the Google Play store.  This is an ABSOLUTE showstopper bug for everyone using this client on Android.  Getting it fixed should not have to wait for forty-eleven other bug fixes to be landed.

**Comment by AndyScherzinger** [comment]
Hi all,

let me give some answers until @tobiasKaminsky can comment on it.

* I check Google and hit Publish (again). There is currently a review issue with Google requesting an updated video due to the permissions needed/used by the app where Google states that the video doesn't reflect the need for the permissions adequately. I don't know it the video has been updated, but just hit the publish button in an "I feel lucky way". Let's see if it goes through. So yes, the delay is "just" on the Google Play side but is there nevertheless.
* Yes 3.28.2 is already "finished", so the change mentioned in https://github.com/nextcloud/android/issues/12801#issuecomment-2044572921 hasn't been merged yet and would than be a 3.28.3
* I'll check the milestone and close it then and open a new one. I usually don't but I have the permissions on Github to do so. So this might also help with preventing confusions on versions / development of versions.

**Comment by vimpostor** [comment]
3.28.2 seems to be published now for me on the Google Playstore, and everything is working again.
