### ISSUE TITLE
Android app thumbnails generation

### ISSUE THREAD

**Issue by loic12305** [nextcloud/android#1281]
### Actual behaviour
- On Android app, thumbnail display is very long.

### Expected behaviour
- I think app doesn't use thumbnails create by preview generator (NC12), so NC must generate 256x256 thumbnail. It's too bad, because Preview Generator already create 256 thumb.

### Environment data
Android version: 7.0

Device model: Redmi Note 4

Stock or customized system: Stock

Nextcloud app version: 1.4.3

Nextcloud server version: 12.0.1

#### Web server log when app call thumb
```
"GET /index.php/apps/files/api/v1/thumbnail/256/256/Camera%C2%A0Uploads/2017/2017-06-01_20-44-38.jpg HTTP/1.1" 200 14748 "-" "Mozilla/5.0 (Android) ownCloud-android/1.4.3"
```

**Comment by tobiasKaminsky** [comment]
cc @rullzer would be great if you can have look here, as discussed on irc

**Comment by tobiasKaminsky** [comment]
ping @rullzer :-)

**Comment by rullzer** [comment]
Yes yes I know. Still on the todo :wink:

**Comment by tobiasKaminsky** [comment]
@rullzer I think we recently changed this to use /index.php/apps/files/api/v1/thumbnail/width/heigth/path 
Is this then still valid?

**Comment by rullzer** [comment]
This is fixed then :)

**Comment by loic12305** [comment]
Thank youuuu
