### ISSUE TITLE
The PDF file does not open in Android app(3.28.1)

### ISSUE THREAD

**Issue by Pal-FC** [nextcloud/android#12825]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Open a PDF file in android app

### Expected behaviour

Open PDF with an External PDF app viewer

### Actual behaviour

The PDF file does not open

### Android version

14

### Device brand and model

Samsung Galaxy s21 

### Stock or custom OS?

Stock

### Nextcloud android app version

3.28.1

### Nextcloud server version

28.0.4

### Using a reverse proxy?

I don't know

### Server error logs

```bash
Exception
HMAC does not match.
/var/www/html/lib/private/Security/Crypto.php
riga 119
OC\Security\Crypto->decryptWithoutSecret(
  "*** sensitive parameters replaced ***"
)
/var/www/html/lib/private/Session/CryptoSessionData.php
riga 90
OC\Security\Crypto->decrypt(
  "*** sensitive parameters replaced ***"
)
/var/www/html/lib/private/Session/CryptoSessionData.php
riga 67
OC\Session\CryptoSessionData->initializeSession()
/var/www/html/lib/private/Session/CryptoWrapper.php
riga 112
OC\Session\CryptoSessionData->__construct()
/var/www/html/lib/base.php
riga 449
OC\Session\CryptoWrapper->wrapSession()
/var/www/html/lib/base.php
riga 705
OC::initSession()
/var/www/html/lib/base.php
riga 1200
OC::init()
/var/www/html/index.php
riga 37
undefinedundefinedrequire_once(
  "/var/www/html/lib/base.php"
```

**Comment by Pal-FC** [comment]
I installed the previous version of the nextcloud app (3.28.0) and it solved the problem.
It's definitely a bug in version (3.28.1).

**Comment by dajusc** [comment]
If it also affects other file formats e.g. pictures it may be the same problem as described in #12822.

**Comment by Pal-FC** [comment]
#12823

**Comment by mhdion** [comment]
while waiting for 3.28.2 I'm using CX File Explorer with DAV.

**Comment by Pal-FC** [comment]
> while waiting for 3.28.2 I'm using CX File Explorer with DAV.

È disponibile su https://github.com/nextcloud/android/releases/tag/stable-3.28.2

**Comment by Pal-FC** [comment]
> while waiting for 3.28.2 I'm using CX File Explorer with DAV.

È disponibile su https://github.com/nextcloud/android/releases/tag/stable-3.28.2
