### ISSUE TITLE
Crach after search

### ISSUE THREAD

**Issue by eric-lemesre** [nextcloud/android#12842]
- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. White à Word in search entre (livret)
2. Validate 
3. Crash

### Expected behaviour

Find or not content with the word

### Actual behaviour

Application crash

### Android version

14

### Device brand and model

Samsung ultra 22

### Stock or custom OS?

Stock

### Nextcloud android app version

3.28.1

### Nextcloud server version

28.0.1

### Using a reverse proxy?

No

**Comment by alperozturk96** [comment]
@eric-lemesre Could you share logs?

**Comment by joshtrichards** [comment]
Closing due to insufficient information.
