### ISSUE TITLE
Client stuck at pass code with no keyboard

### ISSUE THREAD

**Issue by chorcheus** [nextcloud/android#12865]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Enable App pass code in the Settings (4 digits pass code) and close the client
2. Open the client a put in the wrong pass code several times, so that your client is blocked
3. After a few hours, open the app again, you'll get a message "Delayed due too many wrong attempts" for a second, then it dissapears and you are free to enter the pass code, except no keyboard will pop up, so you can't.

### Expected behaviour

At point 3, the keyboard should pop up for you to enter the pass code.

### Actual behaviour

At point 3, the keyboard does not pop up and there is no way to put in the passcode.
  * This issue persists for days.
  * The app does not say it is blocked.
  * Switching to different keyboard app does not work.
  * Clearing the cache in Android settings also does not work.
  * Could not try deleting user data, since it requires the pass code as well.
  * Have not tried the uninstall (Actually I would like to avoid it)
  * Logging in with browser works fine. I downloaded the Nextcloud-dev app separately and the login works fine there as well.
  * The app does not upload files automatically in the background anymore.

### Android version

11

### Device brand and model

OnePlus 6T

### Stock or custom OS?

Stock

### Nextcloud android app version

3.28.2

### Nextcloud server version

27.1.8snap1

### Using a reverse proxy?

No

### Additional information

I did not put in any server logs since the app does not even try to connect to the server.
I did not put in Android logs since the problem is not on beta nor dev version of the app and using USB debugging for logcat could mess up with my other settings in the system (since it breaks a system security for some of them).

**Comment by chorcheus** [comment]
Additional info: I tried to put in the pass code with remote keyboard (Kdeconnect on desktop) but it does not make any effect. Seems like the Nextcloud app does not send a signal for a keyboard to pop up at all.

**Comment by Nietzscheanman** [comment]
Same issue

**Comment by AlexOnFOSS** [comment]
Same problem here. Cannot use the nextcloud app anymore.

**Comment by Juliowilly** [comment]
Same issue here. You guys still haven't fixed this?

**Comment by Spreadcat** [comment]
I can confirm this issue is still present. Very annoying and required a re-installation of the app and complete re-configuration.

**Comment by parneet-guraya** [comment]
picking this up

**Comment by parneet-guraya** [comment]
This might solve the issue: #13414

**Comment by KHerschbach** [comment]
I "solved" this by connecting a USB keyboard to my phone and entering the PIN that way.

So it seems to me that the app still registers input at that point, it just doesn't call up the on-screen keyboard.

**Comment by alperozturk96** [comment]
Fixed via https://github.com/nextcloud/android/pull/13414
