### ISSUE TITLE
Allow to use device credentials instead of PIN to unlock app

### ISSUE THREAD

**Issue by shtrom** [nextcloud/android#1286]
### Actual behaviour
- Settings/Passcode lock requests a 4-digit PIN to be entered

### Expected behaviour
- It would be good to have the option to select to use the device's security credentials instead of a PIN; see, for example, flocke/andOTP

**Comment by tobiasKaminsky** [comment]
In the upcoming version you can choose to use fingerprint for unlocking.
Would this be enough?

**Comment by shtrom** [comment]
No (I don't have a fingeprint reader of my device), but it's a start, as it would need the introduction of a way to support multiple unlock methods.

This request, then, is for another option to unlock the app, by using whatever method the phone has been configured to unlock the lock screen (PIN, pattern, ...)

**Comment by tobiasKaminsky** [comment]
If it is possible to use the credentials by android itself I am fine with the idea.
Let's wait on the feedback of the other devs and then someone needs time to implement it, help is always more than welcome :+1:

**Comment by shtrom** [comment]
Judging by http://github.com/flocke/andOTP it seems possible; this is what made me think that it would be a good addition to the Nextcloud client, too

**Comment by shtrom** [comment]
Just got this today from F-Droid. Thanks a lot guys!
