### ISSUE TITLE
Code not working

### ISSUE THREAD

**Issue by T4-RajnishR** [nextcloud/android#12878]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Code not compiling
<img width="1349" alt="Screenshot 2024-04-15 at 11 49 04 AM" src="https://github.com/nextcloud/android/assets/144092493/f749ee69-bf9b-4b72-b9cf-76112de56a78">

### Expected behaviour

code should be compiled

### Actual behaviour

Code not compiling

<img width="1349" alt="Screenshot 2024-04-15 at 11 49 04 AM" src="https://github.com/nextcloud/android/assets/144092493/6ac34e41-7898-48dd-98fa-ea5abf532e6a">

### Android version

13

### Device brand and model

One plus

### Stock or custom OS?

Stock

### Nextcloud android app version

20220322

### Nextcloud server version

stable27

### Using a reverse proxy?

I don't know

### Android logs

<img width="1349" alt="Screenshot 2024-04-15 at 11 49 04 AM" src="https://github.com/nextcloud/android/assets/144092493/ef819f9d-25bd-46a5-bce2-5efdc2346c9c">

**Comment by AndyScherzinger** [comment]
Hi @T4-RajnishR,

can't tell what revision of the code you are trying to run, definitely an older one.

What you would need to do is to change https://github.com/nextcloud/android/blob/master/gradle/verification-metadata.xml#L7 according to the version you are seeing as an error. Again, current main branch is at `8.3.2` already. So best case you just update to latest main branch and the issue should be gone for you.
