### ISSUE TITLE
Provider authorities should be an absolute package name

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#129]
As already filed in the owncloud issue tracker https://github.com/owncloud/android/issues/1735 forks will have collisions with authorities, e.g. ```UsersAndGroupsSearchProvider``` as well as the ```ManageSpaceActivity```.

The later has been fixed (for us) by using the full qualified name of the class but I think it would be best, if we move these two (and any other that may need to be moved) to a ```com.nextcloud.android``` package so both apps behave well and let a user run them in parallel - being good citizens.

cc for approval: @nextcloud/android

**Comment by jancborchardt** [comment]
Sounds good, yeah.

**Comment by przybylski** [comment]
ok to me

**Comment by AndyScherzinger** [comment]
Sweet let's when we find the time to do this. We either can get it into 1.2.0 or should maybe do a 1.2.1 depending on how long it'll take us to implement 1.3.0

**Comment by tobiasKaminsky** [comment]
Merged
