### ISSUE TITLE
Autouploaded Videos Showing Up in Photos Directory

### ISSUE THREAD

**Issue by Torqu3Wr3nch** [nextcloud/android#12910]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Set up autoupload with separate profiles for photos vs videos using the same monitored camera directory but autouploading to two separate photo vs video remote directories.
2. Take a video.
3. Notice that the video file appears in both the photo and video remote directories as a duplicate file.

### Expected behaviour

Android client should respect the photo vs video profiles and only upload to their respective remote directories.

### Actual behaviour

Video file is duplicated on the Nextcloud remote in both the photo and video directories.

### Android version

13

### Device brand and model

OnePlus

### Stock or custom OS?

Stock

### Nextcloud android app version

3.28.2

### Nextcloud server version

28.0.4

### Using a reverse proxy?

Yes

### Additional information

Looking back through my directories, this appears to have started within the past month (April). I don't take that many videos so it's conceivable that this began in the middle of March (the last timepoint I have where I took a video and it wasn't duplicated), but this does seem like a net new change.

Interestingly, it seems like others have complained of the opposite finding the separate profiles unintuitive (see Issue #12585 and Issue #12347). Perhaps changes found their way into the main release? If so, that would be particularly unfortunate since this reflects a change in longstanding autoupload behavior and since we currently lack the ability to suppress (or select) upload based on filetype, there is no available workaround to keep videos and photos in separate directories.

**Comment by Torqu3Wr3nch** [comment]
Updated to 3.29.0 and this issue is no longer occurring. Marking as resolved.

**Comment by seppiola** [comment]
Still happening to me on 3.29.0

**Comment by microbearlogist** [comment]
The bug still exists in 3.29.1.

All my .mp4 files are uploaded in the same folder as the photos (despite having specified a different folder).

**Comment by awptechnologies** [comment]
Same here problem still happening in 3.29.2

**Comment by Torqu3Wr3nch** [comment]
Reopening this issue since it is happening again intermittently and others are reporting the same.

**Comment by awptechnologies** [comment]
any updates on the fix? why all of a sudden? nexcloud has been a wonderful application was able to basically set and forget but this has made it hard to do that. Also can someone verify that it is actually saving two copies. I have been going into my picture library and deleting the .mp4 files but i want to make sure there is actually 2 files and not a link of some sort. Basically asking if i delete the video from the pic library does it mess with the same video in my video library?

**Comment by joshtrichards** [comment]
Fixed in #13255 (>=3.30.0)
