### ISSUE TITLE
NC Dev 20170808 update APK doens't exist.

### ISSUE THREAD

**Issue by OlivierS1** [nextcloud/android#1294]
### Actual behaviour
-Tell us what happens
When trying to download the latest update, upon opening web browser, the messge "File not found" appears.
The files "latest" on https://download.nextcloud.com/android/dev/ contains the value 20170808 which I believe is the name suffix for the APK file.
The APK file doesn't exist for that date.

### Expected behaviour
-Tell us what should happen
 The relevant APK file should exist.

**Comment by tobiasKaminsky** [comment]
There was an internal build problem, but I solved it already and the new version will appear shortly.

**Comment by tobiasKaminsky** [comment]
Now 20170810 is available
