### ISSUE TITLE
Auto Upload: uploads 0b files

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#1295]
- latest LineageOS, OnePlus 3
- take a picture with camera app OR take a screenshot, both with provided apps by LineageOS
- see that 0b are uploaded
- in Amaze (file browser) the file size is also 0b, but it is shown correctly in gallery, however in nextcloud app it is not shown (error image)

Using another camera app (open camera) it is working fine.

**Comment by tobiasKaminsky** [comment]
Strange, seems more a bug in the camera (snap) app:
- right after taking an image it is ~2-3Mb, showing in gallery is also fine
- seconds later, it is 0b and the image is a little bit corrupted on the bottom

**Comment by mario** [comment]
Does the same happens if you don't have NC on your phone? Also internal or external storage?

**Comment by tobiasKaminsky** [comment]
Internal storage and it also happens if no NC is installed.
So definitiv a bug of LineageOS/camera app.

**Comment by tobiasKaminsky** [comment]
After further testing:
those images that are 0b are in fact real images
- ls -l on adb shell/terminal shows correct size
- gallery in camera app shows correct size
- amaze, our app and a few others show the wrong size
- while debugging I see that new File(pathOfStrangeFile).length also shows 0, which then leads to wrong upload

As some apps get the correct file length we should try to use also this approach to get a proper upload of those files.

**Comment by mario** [comment]
2.0.1 then.

**Comment by vnidens** [comment]
@tobiasKaminsky I don't have any device with LineageOS at this moment but have you checked what file size you get when you fetch it through `ContentResolver` using file's `Uri`? See [this link](https://developer.android.com/training/secure-file-sharing/retrieve-info.html#RetrieveFileInfo).

**Comment by mario** [comment]
@AndyScherzinger ? :D Why close this? xD

**Comment by AndyScherzinger** [comment]
reopened... well, it auto closes since your PR said resolves 1295 and thus GH auto closes the issue when the PR is merged 😉

**Comment by tobiasKaminsky** [comment]
Postponing as it is an edge case ;-)

**Comment by mario** [comment]
@tobiasKaminsky I have to postpone this. This happens on some phones to which I don't have access, but I'll steal your phone at hackweek and we can test.

**Comment by tobiasKaminsky** [comment]
PR is #2185, but as noted there, it is unfortunately not 100% working all the time.
