### ISSUE TITLE
Using discouraged APIs

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#12962]
With the update to AGP 8.4.0 via  #12960, newly popping up:

<img width="679" alt="2024-05-01 15_59_32-Lint Report — Mozilla Firefox" src="https://github.com/nextcloud/android/assets/1315170/d3ec99cc-664e-4ca6-b22c-04c609fe1bcc">

**Comment by alperozturk96** [comment]
Solved with https://github.com/nextcloud/android/pull/13025
