### ISSUE TITLE
Support downgrading of database

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#1296]
While developing it happens quite often to me that I switch branches which have different database version.
As currently no downgrade is possible, I always have to uninstall the app, install it again & enter credentials.

Do we want to add downgrading? The latest version upgrades were mainly adding new columns or new tables, so this should be easy to revert?

**Comment by mario** [comment]
👍

**Comment by tobiasKaminsky** [comment]
As this is really annoying when switching between different features/branches: #1559

**Comment by AndyScherzinger** [comment]
PR has been merged, so closing

**Comment by tobiasKaminsky** [comment]
Either I was confused back then or I am now, but:
- we are currently on e.g. database level 25 (master)
- featureBranchA introduces database level 26 
- I install featureBranchA -> DB gets updated
- I switch back to master, master branch has no idea how to downgrade from 26 to 25
    - it could simply downgrade the version, but the next upgrade would then lead to a crash
        - for this we then would need to harden the upgrade again and check if the db changes were already applied

--> I think this does not work as I planned :/

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky correct ;) DB updates need to be aligned within the team and from my point of view you simply can't switch between branches without complete de-installations on the devices... Writing code to do this dynamically raises complexity to infinite and would only be to make devs lives easier when switching branches...
