### ISSUE TITLE
DEV release not syncing :( 

### ISSUE THREAD

**Issue by DaveBurkhardt** [nextcloud/android#1297]
### Actual behaviour
-Take photos and it's not syncing; doesn't even attempt.  My phone did an upgrade during the week and now it's back to not working.  Took 6 photos 45 minutes ago and nothing.

### Expected behaviour
-it syncs
 
### Steps to reproduce
1. take photos
2. 
3. 

### Environment data
Android version: 6.0.1

Device model:  s5

Stock or customized system: stock

Nextcloud app version: DEV

Nextcloud server version:

My phone did an upgrade and now it's back to being broken with the DEV release.

**Comment by DaveBurkhardt** [comment]
Works fine when I manually push them; it's like the service which checks for changes didn't get registered or isn't running.

**Comment by tobiasKaminsky** [comment]
I will generate a new dev version tomorrow, as after the latest merge of auto upload a conflict arises.
I will ping you once it is ready.

**Comment by DaveBurkhardt** [comment]
Thanks; sucks I'm back posting again.  but hopefully this helps the community.  Not sure what happened with the Android release change.  But it messed this up :(

**Comment by OlivierS1** [comment]
Seems to be working fine on 20170810. 
I did notice the new changes to the "Auto upload" menu items.

**Comment by tobiasKaminsky** [comment]
Closing as we now have a new dev version based on latest master.
