### ISSUE TITLE
Closes when loading photos

### ISSUE THREAD

**Issue by OptimoxOaqt** [nextcloud/android#12972]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Se selecciona las imágenes se cargan se cierra la aplicación

### Expected behaviour

Cierra app

### Actual behaviour

Cierra app

### Android version

13

### Device brand and model

Samsung s20fe

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

54.0

### Nextcloud server version

27

### Using a reverse proxy?

No

**Comment by joshtrichards** [comment]
Do you have the crash output?

Do you step-by-step reproduction steps?
