### ISSUE TITLE
Can't see any of my files and folders on Nextcloud App, nor can I upload from Android

### ISSUE THREAD

**Issue by ccamara** [nextcloud/android#13004]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Install Nexcloud app v3.29.0 for Android from F-Droid
2. On my Nexcloud server (v.27.1.7) I create a password for the app, and I generate a QR
3. On Nextcloud app for Android, I read the QR code generated at 2.
4. The account gets linked, and I can see my avatar, the colors match those from my custom theme and the stats showing my disk quota match those on the server

I've tried with installing the app via PlayStore with identical results, and also with 3.28.2

### Expected behaviour

Files and folders should appear, matching those on my NC server.
I should be able to upload files from Android

### Actual behaviour

1. Files' section is empty: no files and folders are shown, despite they are in my NC server.
![Screenshot](https://github.com/nextcloud/android/assets/706549/0714ed35-0efb-41c0-ac78-c40f558dce49)

6. Upload icon is greyed out, and cannot be pressed to upload files.
7. When I search for a file that I know is on my NC server, it does show up.
8. When I search for an existing folder, it is shown, but not their content

### Android version

12

### Device brand and model

Xiaomi Redmi9

### Stock or custom OS?

Stock

### Nextcloud android app version

3.28.2

### Nextcloud server version

27.1.7

### Using a reverse proxy?

I don't know

**Comment by mr-bolle** [comment]
I have three same behavior. After reinstall the App, the files still don't exist.

**Comment by joshtrichards** [comment]
> On my Nexcloud server (v.27.1.7) I create a password for the app, and I generate a QR

To clarify: Are you saying this only occurs when using the QR code, but if you use a more traditional login flow it works fine?

Also, can you provide the web server logs from the period when you open the client?

I noticed you mentioned you're not sure if you're using a reverse proxy. Does that mean you aren't the admin and can't provide the Nextcloud config?

**Comment by strayedelectron** [comment]
I have a similiar problem:
I updated to App version 3.29.0 and since then the App could not connect to my Server version 27.1.6 any more.
The App version before just worked fine. Could see and open my files, auto upload worked too. Now I open the App and it tries to connect forever.
Shame that Fdroid did not allow me to downgrade the version. 
I will try to update my server and hope that it will fix the problem.

**Comment by mr-bolle** [comment]
> > On my Nexcloud server (v.27.1.7) I create a password for the app, and I generate a QR
> 
> To clarify: Are you saying this only occurs when using the QR code, but if you use a more traditional login flow it works fine?

I have reinstall the App and use the Google version. With the App token login. If I search any file from the server, I can get the file.

**Comment by mr-bolle** [comment]
Hi, 

I did some further testing with F-Droid DEV version 20240510.
If I log in with another Nextcloud user (who has fewer files available) then these are also displayed in the app.

I have attached the logs from the main user and second user.

[logs_main-user.txt](https://github.com/nextcloud/android/files/15360891/logs_main-user.txt)

[logs_second-user.txt](https://github.com/nextcloud/android/files/15360892/logs_second-user.txt)

**Comment by ccamara** [comment]
Hello,

I'm not an admin of my instance, so I'm afraid I cannot provide logs.

I can add some info, though:

> To clarify: Are you saying this only occurs when using the QR code, but if you use a more traditional login flow it works fine?

The issue happens if I use the QR as well as traditional login (my regular credentials). This happens with both Nexctloud app from F-Droid as well as Google's Play store.

**Comment by ccamara** [comment]
I can see that @strayedelectron , @mr-bolle and myself are using nextcloud 27.1.x and the same app version (3.29.0). I wonder if this could be the issue.

I will ask my admin if they can upgrade Nextcloud server. @strayedelectron , did the upgrade fix your issue?

**Comment by ccamara** [comment]
I can confirm that after upgrading NC Server to 28.0.3, the issue was addressed and I can use the same android app normally.

**Comment by mr-bolle** [comment]
I have now also done the update from the Nextcloud to v28.0.5, and after several hours troubleshooting. After the update I had no access to the data (also in the desktop browser) I can now access all data again.
