### ISSUE TITLE
AutoUpload uploads .thumbnails as well

### ISSUE THREAD

**Issue by enoch85** [nextcloud/android#1300]
I recently bought a new phone (Huawei P10) and since then I start to get .thumbnails in my uploads folder. What could be the cause of this?

![screenshot from 2017-08-10 19 39 48](https://user-images.githubusercontent.com/4511254/29183816-4d0790d2-7e04-11e7-94fb-46846f3df0b2.png)

### Environment data
Android version:
7.0
Device model: 
Huawei P10

Stock or customized system:
Stock
Nextcloud app version:
1.4.3
Nextcloud server version:
12.0.1
#### Web server error log
```
No logs
```

#### Nextcloud log (data/nextcloud.log)
```
No Logs
```

**Comment by tobiasKaminsky** [comment]
Maybe your camera app is creating them to get faster thumbnails?

**Comment by mario** [comment]
@tobiasKaminsky this shouldn't happen with the new auto upload since I don't think media provider registers thumbnails.

**Comment by tobiasKaminsky** [comment]
@enoch85 you can try the beta version for 2.0.0 from google play store.
Just register here: https://play.google.com/apps/testing/com.nextcloud.client

(the toolchain on fdroid cannot build the beta, so currently no fdroid possible...)

**Comment by enoch85** [comment]
@mario OK, sounds good. I'll try the latest DEV app today and see if the issue presists. Otherwise we need to blacklist it.

@tobiasKaminsky Yeah, could be it. The P10 just flies, it's really quick.

**Comment by enoch85** [comment]
It's solved in the latest dev version.

**Comment by mario** [comment]
Thanks
