### ISSUE TITLE
Sound play button not working

### ISSUE THREAD

**Issue by fairking** [nextcloud/android#13077]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Go to Nextcloud app,
2. Find any .m4a audio file,
3. Try to press play button,
4. The button is not responsive and the playback is not started.

### Expected behaviour

Should start to play the sound track.

### Actual behaviour

The play button is not doing anything.

![Screenshot_20240606-125855](https://github.com/nextcloud/android/assets/13495631/d0bbebc2-3e84-435a-959a-deb149a64879)

### Android version

10

### Device brand and model

Moto macro

### Stock or custom OS?

Stock

### Nextcloud android app version

3.29.0

### Nextcloud server version

28.0.5.1

### Using a reverse proxy?

Yes

**Comment by satvik2131** [comment]
It actually plays , it's just take some time to download , if you select a file and wait for some seconds , then it will be played automatically . What we can do is add a loading popup while the music loads , what say @joshtrichards
