### ISSUE TITLE
Only show thumbnails on activities that have previews

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/android#1307]
![screenshot_2017-08-11-10-08-32](https://user-images.githubusercontent.com/213943/29205487-9209d676-7e7d-11e7-9aa2-e3bf63809e2e.png)

This looks very odd atm:
1. Persons don't have a thumbnail (maybe an avatar but that should then be inline)
2. Events/tasks don't have a thumbnail
3. Calendars/Task lists don't have a thumbnail

So don't show the grey box please ;)

PR: #1317

**Comment by AndyScherzinger** [comment]
merged for release 2.0.0 🎉
