### ISSUE TITLE
Auto Upload is Not keeping videos and pics Separate like before.

### ISSUE THREAD

**Issue by awptechnologies** [nextcloud/android#13087]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Auto Upload

### Expected behaviour

I have 2 folders for camera roll one for pics and one for videos. Auto upload should only put videos in video folder and pics in pic folder.

### Actual behaviour

The video folder is only videos so i would say it is working fine. The picture folder is getting my pics but also putting duplicates of videos in it.

### Android version

14

### Device brand and model

Galaxy S22 Ultra

### Stock or custom OS?

Stock

### Nextcloud android app version

3.29.0

### Nextcloud server version

Nextcloud Hub 8 (29.0.1)

### Using a reverse proxy?

Yes

### Additional information

The folders used to stay separate. When i go to auto upload setting in android it shows 2 camera rolls one for pics and one for videos. So i made separate folders to keep videos separate from pics. i deleted all the videos in my pics folder and now videos in video folders wont open. :(

**Comment by seppiola** [comment]
This is the same as #12910 which hasn't been resolved and it's still present on 3.29.0

**Comment by awptechnologies** [comment]
i tried to look through the issues sorry for duplicate
