### ISSUE TITLE
Requesting delta-sync in longterm

### ISSUE THREAD

**Issue by exokkk** [nextcloud/android#131]
Delta Sync would be great for my truecrypt/veracrypt huge files (~30-100gb). Without delta sync I must stay absent from this product.

Delta Sync would also provide you a feature to distinguish from owncloud

**Comment by AndyScherzinger** [comment]
Hi @exokkk I get the idea but I am not sure if this is a use case for Android devices but rather desktop sync. 

If so the best thing would be to open this issue in the desktop client's issues tracker.

**Comment by exokkk** [comment]
Hi, woooops I didnt realize the "android" at all. Sorry.
Thanks for the reply, I'll move on ;-)

**Comment by AndyScherzinger** [comment]
No worries, glad I could help clearing things up :+1:
