### ISSUE TITLE
Allow to delete notifications

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/android#1311]
In the browser you can delete notifications on hover:
> ![bildschirmfoto vom 2017-08-11 10-36-10](https://user-images.githubusercontent.com/213943/29206166-fc90369a-7e80-11e7-8b5e-3ec3692f2bed.png)

In the android app that option should also be available (maybe by swiping the entry to a side)

To create a notification:
1. Install https://apps.nextcloud.com/apps/admin_notifications
2. `occ notification:generate <username> <message>`

**Comment by mario** [comment]
That's for 2.1. Currently notifications are not even stored anywhere.

**Comment by mario** [comment]
Can potentially be part of https://github.com/nextcloud/android/issues/1271.

**Comment by nickvergessen** [comment]
No need to store anything, just allow to send a simple DELETE request ;)

**Comment by tobiasKaminsky** [comment]
Please let us do it independent from any other PR/work.
As far as I understand we simply need a "x" (delete) button or a "swipe to right" gesture. On that action we send a delete request to the server.

**Comment by xXSTrikeXx** [comment]
I have tested the notification in the bus. The request delivery of the notification works in 2.0 RC2. Havent tested it all, but I think it doesn't notificate the Android system about notification, is it?

Just want to say, great work ;)

_Sent from my HUAWEI MYA-L41 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by AndyScherzinger** [comment]
Implementation is #3607
