### ISSUE TITLE
Can not change password because screen is reloading

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/android#1313]
### Steps to reproduce
1. Set up an account using an app password
2. Delete the app password in the nextcloud web ui
3. Try to change the password via the "account management" of the app
4. Select the "broken" account
5. Not sure what the screen is trying to display
6. If you are quick you can tab the "Change password" in the "…" menu
7. Screen reloads and brings you back to "Account management"

### Environment data
Android version: 6.0 EMUI

Device model: Huawei P8 lite

Stock or customized system:

Nextcloud app version: 2.0.0 RC2

Nextcloud server version: 12.0.1

cc @mario

**Comment by tobiasKaminsky** [comment]
works for me :/
Can you try it with another new user who gets a new app password via the new weblogin flow?

**Comment by tobiasKaminsky** [comment]
"change password" is not there anylonger.
If NC app detects that a password is wrong, it shows weblogin flow and there you can enter your new password.
