### ISSUE TITLE
Sometimes Download or Upload Progress Value Is Not Correct

### ISSUE THREAD

**Issue by alperozturk96** [nextcloud/android#13144]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Try to download or upload some file

### Expected behaviour

Progress value must be between 0 and 100

### Actual behaviour

Sometimes progress value is like **"2147483647%"** it must show correct value.

### Android version

3.29.1

### Device brand and model

Fairphone 5

### Stock or custom OS?

Stock

### Nextcloud android app version

3.29.1

### Nextcloud server version

NA

### Using a reverse proxy?

I don't know

**Comment by joshtrichards** [comment]
Previous reports:

- #12883
- #12711 

If these are likely covered by the PR, please link them for proper closure upon merger.
