### ISSUE TITLE
Match Android app sharing options to Server

### ISSUE THREAD

**Issue by jasonbayton** [nextcloud/android#1321]
As of server 12 the options are as follows: 

![image](https://user-images.githubusercontent.com/3178412/29227224-f91c9e62-7ecc-11e7-99e6-3f1d7262f55c.png)

These changes were made to better explain the functions, however the NC app still uses the older terminology

![image](https://user-images.githubusercontent.com/3178412/29227426-af862560-7ecd-11e7-9d77-113efbd715ab.png)

Can we bring this a little closer inline please?

**Comment by tobiasKaminsky** [comment]
Good idea :+1:

**Comment by AndyScherzinger** [comment]
sounds good :+1:

**Comment by AndyScherzinger** [comment]
Afaik this has been implemented with the revamped sharing screen, please re-open if something is missing.
