### ISSUE TITLE
Error deselecting hide file listing on share

### ISSUE THREAD

**Issue by jasonbayton** [nextcloud/android#1322]
### Actual behaviour
When enabling "hide file listing" then trying to disable it, the following error:

![image](https://user-images.githubusercontent.com/3178412/29227491-f01fd986-7ecd-11e7-98a5-0de9588034c8.png)

### Expected behaviour
Hide file listing should just disable
 
### Steps to reproduce
1. Share folder
2. Enable hide file listing
3. Try to disable it.

### Environment data
Android version: 7.1.1

Device model: Moto Z

Stock or customized system: Stock

Nextcloud app version: 2.0RC 

Nextcloud server version: 12.0.1

#### Web server error log
```
No server log generated from this
```

#### Nextcloud log (data/nextcloud.log)
```
No server log generated from this
```

**Comment by tobiasKaminsky** [comment]
> Hide file listing should just disable

Why do you expect this? I rather except that one can use this function, so we need to find out why this error is thrown.

**Comment by jasonbayton** [comment]
>Why do you expect this?

Because it's a switch - on/off. If I can switch it on, I should be able to turn it off.
Also, I can disable it on the server when choosing between file drop and another option

When the client stops crashing I'll recreate the issue.

**Comment by tobiasKaminsky** [comment]
Sorry, I misunderstood it and thought that you wanted to have the option disabled and not that disabling should work ;-)
I'll have look into it.

**Comment by jasonbayton** [comment]
:) fine, recreation just pending a working app.

**Comment by tobiasKaminsky** [comment]
This is done in #1345 
Thank you very much for reporting this :+1:
