### ISSUE TITLE
Connection Problems with uploads

### ISSUE THREAD

**Issue by xXSTrikeXx** [nextcloud/android#1323]
### Actual behaviour
I got a Huawei Y6 2017 (MYA-L41, Android 6.0) and it gets errors while uploading .mp4 files or image files.
I took a little trick to get uploaded all old pictures with my new smartphone. I set up the sync for Camera, unmounted my SD-Card and remounted it, so that my device needs to upload all old pictures from my old smartphone.  I know there will be duplicated uploads, but i decided  to upload all files, to delete later the duplications to be sure that all files are in the cloud. Now after hundreds of fileuploads, some files won´t be uploaded and I haven´t yet restartet the raspberry pi. But i got some hints in the logs. My old device has got the same hints, but he hasn´t got many problems like my new Huawei smartphone.
### Expected behaviour
-Should just upload my shit!
 
### Steps to reproduce
1. Anyway if I renew my upload task list with a umount/mount command from the synced folder or if I manually add old pictures to the upload task list, there should be no different.
2. Using Pi with Pihole, idk if the actual destination is within his own subnets and doesn’t route the requests into the Internet.
3. A friend flooded the table oc_bruteforce_attempts, becaus he has got revoked his old App of his old Smartphone. The old Smartphone was also in the Wlan like mine. So it blocked my uploads, too. I empty the table with phpmyadmin, but I get these error sometimes. Sometime I think it´s overheating of the Pi, but when I connect with mobile connection the upload works great.

### Environment data
Android version:
6.0
Device model: 
MYA-L41 (Huawei Y6 2017) EMUI: 4.1
Stock or customized system:
just opened the bootloader. Haven´t yet got it rooted, but i want it and i have no idea how to.
Nextcloud app version:
1.4.3
Nextcloud server version:
12.0.1

### General server configuration

**Operating system:** Linux raspberrypi 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l

**Web server:** Apache/2.4.25 (Raspbian) (apache2handler)

**Database:** mysql 10.0.30

**PHP version:** 7.0.19-1
<details>
        <summary>PHP-modules loaded</summary>

```
 - Core
 - date
 - libxml
 - openssl
 - pcre
 - zlib
 - filter
 - hash
 - Reflection
 - SPL
 - session
 - standard
 - apache2handler
 - mysqlnd
 - PDO
 - xml
 - apcu
 - apc
 - calendar
 - ctype
 - curl
 - dom
 - mbstring
 - fileinfo
 - ftp
 - gd
 - geoip
 - gettext
 - iconv
 - igbinary
 - json
 - exif
 - msgpack
 - mysqli
 - pdo_mysql
 - Phar
 - posix
 - readline
 - redis
 - shmop
 - SimpleXML
 - sockets
 - sysvmsg
 - sysvsem
 - sysvshm
 - tokenizer
 - wddx
 - xmlreader
 - xmlwriter
 - xsl
 - zip
 - memcached
 - Zend OPcache
```
</details>

### Nextcloud configuration

**Nextcloud version:** 12.0.1 - 12.0.1.5

**Updated from an older Nextcloud/ownCloud or fresh install:fresh ins 111all of NC11
**Are you using external storage, if yes which one:** Array
(

   [6] => \OCA\Files_External\Lib\Storage\Dropbox
)

**Are you using encryption:** no

<details>
        <summary>Enabled apps</summary>

```
 - activity: 2.5.2
 - admin_audit: 1.2.0
 - admin_notifications: 1.0.0
 - apporder: 0.4.0
 - audioplayer: 2.0.2
 - bookmarks: 0.10.1
 - bruteforcesettings: 1.0.2
 - calendar: 1.5.3
 - comments: 1.2.0
 - contacts: 1.5.3
 - dashboard: 4.0.5
 - dav: 1.3.0
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_accesscontrol: 1.2.4
 - files_automatedtagging: 1.2.2
 - files_downloadactivity: 1.1.1
 - files_external: 1.3.0
 - files_pdfviewer: 1.1.1
 - files_retention: 1.1.2
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - gpxedit: 0.0.7
 - gpxmotion: 0.0.4
 - gpxpod: 2.1.4
 - issuetemplate: 0.2.2
 - keeweb: 0.4.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - nextant: 1.0.8
 - nextcloud_announcements: 1.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - password_policy: 1.2.2
 - piwik: 0.3.1
 - provisioning_api: 1.2.0
 - quota_warning: 1.0.1
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - socialsharing_email: 1.0.1
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - tasks: 0.9.5
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - updatenotification: 1.2.0
 - weather: 1.5.0
 - workflowengine: 1.2.0
```
</details>

<details>
        <summary>Disabled apps</summary>

```
 - encryption
 - ocr
 - registration
 - spreed
 - twofactor_totp
 - user_external
 - user_ldap
```
</details>

<details>
        <summary>Content of config/config.php</summary>

```
{
    "instanceid": "oc6wqgwqj867",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "sytes.net"
    ],
    "datadirectory": "\/var\/www\/nextcloud\/data", #rly its on /media/, but i have symlinked it with ln -s
    "overwrite.cli.url": "https:\/\/sytes.net\/nextcloud",
    "default_language": "de",
    "dbtype": "mysql",
    "version": "12.0.1.5",
    "dbname": "nextcloud",
    "dbhost": "localhost",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "Europe\/Berlin",
    "installed": true,
    "mail_from_address": "was",
    "mail_smtpmode": "smtp",
    "mail_domain": "online.de",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "localhost",
        "port": 6379
    },
    "loglevel": 0,
    "token_auth_enforced": false,
    "mail_smtpsecure": "tls",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtphost": "smtp.1und1.de",
    "mail_smtpport": "587",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "quota_include_external_storage": false,
    "theme": "",
    "updater.release.channel": "stable"
}
```
</details>

### Logs
text clipping: https://help.nextcloud.com/t/bruteforce-ip-range-for-lan-uploads/19332/5
Full Logs of 10.08.
[logs.zip](https://github.com/nextcloud/android/files/1219000/logs.zip)

Well, I found out a memory problem in htop:

pi@raspberrypi:~ $ free -h
             total       used       free     shared    buffers     cached
Mem:          923M       845M        78M        43M        77M       531M
-/+ buffers/cache:       236M       687M
Swap:          99M        90M         9M

I found out, that a lot of memory is free, but the swap is very often out of storage.
Edit: My friends uploads were as fine as with Galaxy S3 Neo (NC. V. 1.4.3, Android 4.4.2 )

**Comment by xXSTrikeXx** [comment]
Updated to 2.0RC 2.
Imageupload works fine. But I have videos that wont be uploaded.
The Upload is very slow (can be referable to provider network problems) and I've seen that the Uploads stops, because my device stopped the Wlan Connection. I hope provider problem will be solved, than can I better test.

_Sent from my HUAWEI MYA-L41 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by xXSTrikeXx** [comment]
Updated to 2.0RC 2.
Imageupload works fine. But I have videos that wont be uploaded.
The Upload is very slow (can be referable to provider network problems) and I've seen that the Uploads stops, because my device stopped the Wlan Connection. I hope provider problem will be solved, than can I better test.

_Sent from my HUAWEI MYA-L41 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by xXSTrikeXx** [comment]
Got no problems with 2.0 version. Seems to be fixed with the new android version. Could be atleast the provider problem which I had. I'm using dyndns with no-ip.com and I see in the logfiles that only my external ip of the router is showing in the logs. Even if my device is connected locally via WLAN. I don't know how to configure it out to use LAN-IP instead of WAN-IP. And my provider problem can be referable for the first issue, because I think it's only connecting threw www.

_Sent from my HUAWEI MYA-L41 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by AndyScherzinger** [comment]
Version 1.4.2 is irrelevant in a way that it will be replaces by 1.4.2 so for Android you basically only have one supported version - the latest :)

**Comment by xXSTrikeXx** [comment]
@AndyScherzinger 
You mean Version 2.0 or 1.5? You're confusing me right now that I see milestones for 1.5 and 2.1 :D 

so we can close this issue now, because it works for the latest version 2.0? 

Can you give me a bit of information how the App connects to the WebUI threw WLAN? I know my app is connecting threw WAN to the WebUI and my question is, if it is already developed to check the connection going threw Lan or Wan? 

_Sent from my HUAWEI MYA-L41 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by AndyScherzinger** [comment]
2.0 is the new 1.5, we decided to go straight to 2.0 so anything which was mentioned for 1.5 is now 2.0.
The WebUI is rather a question for @tobiasKaminsky since he did the work on that :)

**Comment by xXSTrikeXx** [comment]
@tobiaskaminsky

Could you give me some information about my last question? It's just a personal question, if I missconfigured my server settings or I just need to wait until the android app supports checking the connection going threw WAN or LAN?

_Sent from my HUAWEI MYA-L41 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by tobiasKaminsky** [comment]
@xXSTrikeXx we are relying on the generic network part of android, so everything will go via WAN I assume.
There is indeed a feature request to have a "local" connection to the same server via LAN, but it is not implemented yet.
