### ISSUE TITLE
Separate calendar notification category

### ISSUE THREAD

**Issue by yajo** [nextcloud/android#13239]
### Is your feature request related to a problem? Please describe.
I have my calendar synced with DAVx5 in my android phone and tablet. I get notifications from there.

Recently, nextcloud android app also started displaying those notifications.

Now, when I have one event, I get 2 notification. That's unnecessary noise for me.

### Describe the solution you'd like
Be able to block the calendar category of nextcloud app notifications, while still letting other notifications like up/download progress.

### Describe alternatives you've considered
Disable all nextcloud notifications, or have double notifications.

**Comment by joshtrichards** [comment]
On your server, you might find *Administration settings->Groupware* helpful. You can disable push notifications for calendar events there.
