### ISSUE TITLE
(Bug) Clean Install, Server address prompt -> Wrong username or password

### ISSUE THREAD

**Issue by ollioddi** [nextcloud/android#13253]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

I've had my Nextcloud instance for quite some months, without this issue before. Recently got a new phone, and wanted to login to Nextcloud.

I downloaded the app again on the brand new device, and it prompts for a server address. When entering, the app just responds "Wrong username or password" with no option, to enter either. This is unexpected while selecting a server.

### Expected behaviour

After providing a server address, i'd expect a redirect to a designated login page.

### Actual behaviour

The app never prompts for any user details, and fails to setup. No matter the server address entered, it just complains about the login details. Address is redacted for privacy.

![image](https://github.com/nextcloud/android/assets/7466744/7d2bc22f-813d-4038-98df-138ae84ee313)

### Android version

14

### Device brand and model

Samsung Galaxy S24 Ultra

### Stock or custom OS?

Stock

### Nextcloud android app version

3.29.1

### Nextcloud server version

29.0.2

### Using a reverse proxy?

Yes

### Server error logs

```bash
ERROR jsresourceloader:
Could not find resource firstrunwizard/js/personalsettings.js to load
```

### Additional information

I use Authentik as SSO, but it is optional currently, and default login still works. I can login to other Nextcloud apps, such as Talk with no issues on the new device. Only the main application fails.

I couldnt find and access the client logs. Let me know if it would help, and i'd find a way to extract it.

**Comment by joshtrichards** [comment]
> I use Authentik as SSO, but it is optional currently, and default login still works.

What happens when you visit https://domain.com/status.php in a private browser window (i.e. when not logged in)?

**Comment by ollioddi** [comment]
> > I use Authentik as SSO, but it is optional currently, and default login still works.
> 
> What happens when you visit https://domain.com/status.php in a private browser window (i.e. when not logged in)?

I can get access and this is the returned object:

```
{"installed":true,"maintenance":false,"needsDbUpgrade":false,"version":"29.0.2.2","versionstring":"29.0.2","edition":"","productname":"Nextcloud","extendedSupport":false}
```

**Comment by joshtrichards** [comment]
Any chance you have a custom error handling in place?

example: https://help.nextcloud.com/t/app-login-not-working-w-oidc-backend-everything-else-are-fine/197891/6

**Comment by ollioddi** [comment]
That was exactly the issue!

Removed the middleware, as per the post, and now it's working again. Even with SSO, and openid being the primary source.

Thank you! If you create a PR, I'd appreciate if you could reference this so i can hopefully enable error pages again someday :-)

For now, i am closing, since the issue was resolved.
