### ISSUE TITLE
Account first login endless forward - server error oauthState undefined index

### ISSUE THREAD

**Issue by AlexVienna** [nextcloud/android#1325]
### Actual behaviour
when I set up the device and account after entering the login credentials the system hangs saying forwarding ...
On the server an error is logged 

### Expected behaviour
Login working
 
### Steps to reproduce
1. Install RC2.0 from play store beta
2. Enter server,then confirm device and grant access
3. Enter login the press login button

### Environment data
Android version: 7.0

Device model: huawei p9lite

Stock or customized system:stock

Nextcloud app version: Rc2.0.0

Nextcloud server version:12.0.0

#### Web server error log
Undefined index: oauthState at /var/www/nextcloud/core/templates/loginflow/authpicker.php#38
Then 2 times 
Missing expected parameters in change user hook
Then 
Login failed

#### Nextcloud log (data/nextcloud.log)
No  log yet created

**Comment by tobiasKaminsky** [comment]
As this is working an many devices/servers, I think this is a problem on your server.
Can you create us an test account on your server and mail the credentials to android at nextcloud dot com and link to this issue?

**Comment by timmersr** [comment]
Something seems to have changed to kill this bug? 

I had the same issue and tried the new authentication and also reinstalling the client about 10 times. 

It only worked on one of my two 12.0.2 Nextcloud servers, and had an endless loop on the other trying to Grand Access. "Redirecting ...", then "No files present", then looped back to the Grand Access screen. Also, using the legacy app token method didn't work either.  

This morning I reinstalled 2.0.0RC2 and now I was correctly prompted to allow Nextcloud access rights to my media. Hope this helps and thanks for the great work.

Btw: some typo's in the Dutch translation: "Gedeel" should be "Gedeeld" and "Proberen om in the loggen" should be "Proberen om in te loggen"

**Comment by AndyScherzinger** [comment]
@timmersr thanks for the update, we are running short on Dutch translator, so if you have some time you can spend on translations, our translations are maintained here: https://www.transifex.com/nextcloud/nextcloud/android/ if you request access to this you can change any of the Dutch string and also add missing ones. :) No pressure though!

**Comment by timmersr** [comment]
Hi Andy,

 

Thanks, I’ve signed up and will do my best.

 

Best regards,

Rick Timmers

 

Van: Andy Scherzinger [mailto:notifications@github.com] 
Verzonden: donderdag 17 augustus 2017 14:55
Aan: nextcloud/android <android@noreply.github.com>
CC: timmersr <info-from-github@leesme.nu>; Mention <mention@noreply.github.com>
Onderwerp: Re: [nextcloud/android] Account first login endless forward - server error oauthState undefined index (#1325)

 

 <https://github.com/timmersr> @timmersr thanks for the update, we are running short on Dutch translator, so if you have some time you can spend on translations, our translations are maintained here:  <https://www.transifex.com/nextcloud/nextcloud/android/> https://www.transifex.com/nextcloud/nextcloud/android/ if you request access to this you can change any of the Dutch string and also add missing ones. :) No pressure though!

**Comment by AndyScherzinger** [comment]
Thanks @timmersr - beware that after todays merges there will be some more new/changed Strings to be translated in transifex since we will merge bugfixes and what's new infos.

**Comment by AlexVienna** [comment]
Hello Tobias, 
sorry for the delay - was travelling ..
I just emailed the test account as requested
best regards
Alexander

**Comment by timmersr** [comment]
I can confirm that I have saber/dav related server-issues. I'll make a backup, note all my settings and try to create a fresh Ubuntu/Nextcloud install while still keeping all my data. So for now, this topic no longer applies to me.

**Comment by Slevin7** [comment]
Is there any progress?
I get the same error as OP

**Comment by tobiasKaminsky** [comment]
@AlexVienna I tested it with the emailed credentials and it is working for me.
Please try it with upcoming RC6 (tomorrow or monday)

**Comment by timmersr** [comment]
I'm unaware of what caused it, but it is solved now. As the new test-account had no issues at all, this was account-related. Something I could not influence, 

So I created another user, rsync-ed all my files to the new account, reindexed my files, tried the 'account first login' and on success removed the old account.

**Comment by Heidistein** [comment]
Could you dive into what solver your issue? I am facing the same troubles...
Will look into Dutch translations when time permits. :)

**Comment by timmersr** [comment]
You can try my work-around to solve it. 
If you execute it twice, you may even return to the current account name.

**Comment by Heidistein** [comment]
That is not really an option. First, it is an ldap user, so removing it mean lots of logins must change.
And migrating contacts and calendars (also using shares) is a pita too. Passman is doable.

**Comment by timmersr** [comment]
I just feel lucky that everything seems to work without having to reinstall and 'All checks passed' shows when I log on. Sorry that I can't help you; Nextcloud and Linux experience both do no run very deep with me.

**Comment by AlexVienna** [comment]
Just could check with 2.0.0RC6 and working on 2 devices now without change on the server -- seems to be fixed at least for me - thank you!
