### ISSUE TITLE
Force new scan of not permitted files

### ISSUE THREAD

**Issue by xXSTrikeXx** [nextcloud/android#1328]
### Actual behaviour
Checks recently changes on the folders which be autouploaded.

### Expected behaviour
It works fine, I think it´s there to save some battery life, and if you want to instantly upload you can force there a new scan. I´m right? That the reason, why it isn´t added intanlty to the upload tasker, is it?
With the new version I deleted accidentally some upload task. Now I don´t know the deleted filename and it would be nice, that you can press a button in the section of the Autouploadssettings that not only forces the recently data to be synced, rather the whole autoupload folder. So old files can be detected, that wasn´t be uploaded.
So you have a battery life save button in the upload tasks (to upoad recent files) and a sync checker in the autouploadssettings, that takes not permitted files to the upload tasker.

EDIT: Another Idea, you can suggest this only at the start for new user with the whats new screen ;)

**Comment by mario** [comment]
Initial sync of existing files (and missing files) will be added later.

**Comment by tobiasKaminsky** [comment]
Longer goal to get a real 2way sync for folders as described in #285.

**Comment by RufioHugo** [comment]
So at all "force new scan" right now has absolutely no function?
Because - uploads; force new scan ... looks like there is absolutely no effect on nothing!

**Comment by RufioHugo** [comment]
Sorry for late answer - was out of town a real while ...

Android version:
7.1.2 & 7.1.1
Device model:
BQ M5 / U
Stock or customized system:
7.1.2 = lineageOS 14.1 from August
7.1.1 = stock
Nextcloud app version:
3.2.1
Nextcloud server version:
13 (unable to update hangs on step 4)

And "new scan" simply does nothing (had to take some pictures with autoupload off). ;-(

**Comment by joshtrichards** [comment]
Addressed by #4787 (and to some extent #4788)
