### ISSUE TITLE
No thumbnails in the activitys [RC2]

### ISSUE THREAD

**Issue by xXSTrikeXx** [nextcloud/android#1329]
### Actual behaviour
-No thumbnails for .jpg or .mp4, 
-Thumbnails avaible for directories, .vcf, 

### Expected behaviour
-Should see thumbnails

### Environment data
Android version:
6.0
Device model: 
Huawei Y6 2017 (MYA-L41)
Stock or customized system:
just opened the bootloader. Haven´t yet got it rooted, but i want it and i have no idea how to.
Nextcloud app version:
2.0.0RC2
Nextcloud server version:
12.0.1

Image tells more than 1000 words:

![screenshot_2017-08-13-11-43-09](https://user-images.githubusercontent.com/1523741/29248729-a32c5c32-801f-11e7-8852-1df01f2f0c0e.png)

**Comment by gorankav** [comment]
Same here

**Comment by tobiasKaminsky** [comment]
Do you use self-signed certs? Or even a non https connection?

**Comment by AndyScherzinger** [comment]
I can confirm this with my setup on a http connection. No thumbnails at all just the file type icons for all none-thumbnail files.

**Comment by AndyScherzinger** [comment]
I can confirm this with my setup on a http connection. No thumbnails at all just the file type icons for all none-thumbnail files.

**Comment by tobiasKaminsky** [comment]
With a test instance that only allows http I also do not get any thumbnail for an image, to get any images I have 
- explicit enter http://server on account setup
- remove index.php in call
Otherwise I get a 303 response, but maybe this is only my local setup :/

**Comment by xXSTrikeXx** [comment]
Self signed certs? No I dont like the hint in browsers. That looks wired for my older family members. I use certbot with let's encrypt. 

_Sent from my HUAWEI MYA-L41 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky this could also be a server issue since I can recall since when the thumbnails are broken because they also don't work in the file listings, so it could also be related to 12.0.x since I am only running a 12.0.2 instance, no https.

**Comment by tobiasKaminsky** [comment]
@xXSTrikeXx I do not wanted to suggest self signed certs, but my guess was that you are using this as then sometimes the image downloading can fail.
But now I provided a fix, which we need to test.

**Comment by AndyScherzinger** [comment]
Will that then work for activities _AND_ for the file listsings?

**Comment by tobiasKaminsky** [comment]
This approach is for both, but @nickvergessen is only for activity as we do not have a similar property for files retrieved via webdav.

**Comment by xXSTrikeXx** [comment]
@tobiasKaminsky 
Sry, it shouldn't sounds aggressive like that. 
I have got a question of personal interest: How does the parser work? Can't imagine it for myself, only that it doesn't need to fetch anymore.

_Sent from my HUAWEI MYA-L41 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by tobiasKaminsky** [comment]
With the new approach we get a thumbnail url which we can simply download.
The current approach is to generate the thumbnail url by our own like this

> String uri = mClient.getBaseUri() + "/index.php/apps/files/api/v1/thumbnail/" + px + "/" + px + Uri.encode(file.getRemotePath(), "/");
