### ISSUE TITLE
Error en sincronización automática app

### ISSUE THREAD

**Issue by redsolution-mx** [nextcloud/android#1331]
### Actual behaviour
En iphone no se activa la sincronización automática directamente una vez aplicada, la app no sube las fotos al momento y no permite subir masivamente. 

### Expected behaviour
La app debe de mantenerse activa todo el tiempo y subir contenido al servidor , así como también poder eliminarlo desde u. iPhone como lo hace Android. 

 
### Steps to reproduce
1. 
2. 
3. 

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by xXSTrikeXx** [comment]
Youre writing about iPhone. Are you sure that you are in the right section of device, Android? Sry but google translate sucks :D
