### ISSUE TITLE
Unexpected error occured while downloading files

### ISSUE THREAD

**Issue by dodancs** [nextcloud/android#13316]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Have Nextcloud
2. Have Android app
3. Try to Sync a folder via the Android app and get the following error:
![Screenshot_20240725_100450_Nextcloud](https://github.com/user-attachments/assets/c0fa55dc-f4d6-4a8b-862f-da6c4773ed08)

### Expected behaviour

Folders get synced and files appear on my Android device.

### Actual behaviour

Sometimes it syncs part of a folder, like one file in the base directory, when I go inside of the folder in the Nextcloud app and attempt to sync a nested folder it also partly syncs and results in the error. The I can compare the "On device" vs in cloud sizes and definitely see that the folder definitely was not fully synced:

In cloud:
![Screenshot_20240725_101652_Nextcloud](https://github.com/user-attachments/assets/861259e3-2324-4792-beac-8a4cf4540170)
vs On device:
![Screenshot_20240725_101708_Nextcloud](https://github.com/user-attachments/assets/8dd03c03-c736-4c2b-98af-1605d3548173)

### Android version

14

### Device brand and model

Samsung Galaxy S23 Ultra

### Stock or custom OS?

Stock

### Nextcloud android app version

3.29.2

### Nextcloud server version

29.0.4

### Using a reverse proxy?

Yes

### Android logs

[nextcloud-download-issue.txt](https://github.com/user-attachments/files/16373160/nextcloud-download-issue.txt)

### Server error logs

```bash
No error logs, just a happy server:


172.32.0.11 - dodancs [25/Jul/2024:08:09:13 +0000] "PROPFIND /remote.php/dav/files/dodancs/Obsidian%20Notes/ HTTP/1.1" 207 1368 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.29.2"
172.32.0.11 - dodancs [25/Jul/2024:08:09:13 +0000] "PROPFIND /remote.php/dav/files/dodancs/Obsidian%20Notes/notes.sqlite HTTP/1.1" 207 1392 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.29.2"
172.32.0.11 - dodancs [25/Jul/2024:08:29:19 +0000] "GET /remote.php/dav/files/dodancs/Obsidian%20Notes/_files/PastedGraphic-1.pdf HTTP/1.1" 200 711075 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.29.2"
172.32.0.11 - dodancs [25/Jul/2024:08:29:20 +0000] "GET /remote.php/dav/files/dodancs/Obsidian%20Notes/_files/qownnotes-media-aiNuAF.png HTTP/1.1" 200 278366 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.29.2"
172.32.0.11 - dodancs [25/Jul/2024:08:29:20 +0000] "GET /remote.php/dav/files/dodancs/Obsidian%20Notes/_files/qownnotes-media-ALBbxJ.png HTTP/1.1" 200 53901 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.29.2"
127.0.0.1 - - [25/Jul/2024:08:29:20 +0000] "GET /status.php HTTP/1.1" 200 1687 "-" "curl/7.88.1"
172.32.0.11 - dodancs [25/Jul/2024:08:29:20 +0000] "GET /remote.php/dav/files/dodancs/Obsidian%20Notes/_files/qownnotes-media-ArsyxP.png HTTP/1.1" 200 180929 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.29.2"
172.32.0.11 - dodancs [25/Jul/2024:08:29:20 +0000] "GET /remote.php/dav/files/dodancs/Obsidian%20Notes/_files/qownnotes-media-AuySyk.png HTTP/1.1" 200 6167 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.29.2"
172.32.0.11 - dodancs [25/Jul/2024:08:29:20 +0000] "GET /remote.php/dav/files/dodancs/Obsidian%20Notes/_files/qownnotes-media-BfgeXp.png HTTP/1.1" 200 106655 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.29.2"
172.32.0.11 - dodancs [25/Jul/2024:08:29:21 +0000] "GET /remote.php/dav/files/dodancs/Obsidian%20Notes/_files/qownnotes-media-BFhUUE.png HTTP/1.1" 200 287310 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.29.2"
172.32.0.11 - dodancs [25/Jul/2024:08:29:21 +0000] "GET /remote.php/dav/files/dodancs/Obsidian%20Notes/_files/qownnotes-media-bflJiL.png HTTP/1.1" 200 87088 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.29.2"
172.32.0.11 - dodancs [25/Jul/2024:08:29:21 +0000] "GET /remote.php/dav/files/dodancs/Obsidian%20Notes/_files/qownnotes-media-BHKHFo.png HTTP/1.1" 200 63578 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.29.2"
172.32.0.11 - dodancs [25/Jul/2024:08:29:21 +0000] "GET /remote.php/dav/files/dodancs/Obsidian%20Notes/_files/qownnotes-media-bLVykA.png HTTP/1.1" 200 181187 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.29.2"
...
```

### Additional information

This has been happening for a long time now. Around 6 months or maybe even longer. My previous phone on Android 13.1 has the same issue.

In the meantime I have applied many Android updates, Nextcloud app updates and Nextcloud server updates and the issue still persists.

I am just unable to sync any folder on my Nextcloud, just singular files.

The same issue may have plagued the Nextcloud Notes app, which I cannot use anymore because it does not sync my notes. (But I guess they are completely separate issues)

**Comment by jgrocha** [comment]
I'm using Nextcloud Android app version 3.30.6

Everything works. I can download and upload files without problem.

I'm still getting lots of warning with the message: **Unexpected error occured while downloading files**

![Image](https://github.com/user-attachments/assets/b841bd15-2b0c-4fe6-8e59-fa0191652de9)

How do I debug this?

**Comment by kiplingw** [comment]
I'm having the same problem. I also looked in the server logs and didn't see anything unusual, leading me to believe this is a client-side bug.
