### ISSUE TITLE
Kein Speicherplatz mehr

### ISSUE THREAD

**Issue by Hans-06Rostock** [nextcloud/android#13403]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Ich versuche Bilder zu posten und es steht immer wieder da: Hochladen fehlgeschlagen.
Grund dafür ist der Speucherplatz der voll ist.

### Expected behaviour

Ich brauche mehr Speicherplatz als: 1024,0 Mb

### Actual behaviour

Es ist so, dass die Bikder nicht in der Nextcloud App geladen werden, da der Speicher voll ist.

### Android version

Ja

### Device brand and model

Samsung Galaxy A12

### Stock or custom OS?

Stock

### Nextcloud android app version

Habe ich

### Nextcloud server version

Habe uch

### Using a reverse proxy?

I don't know

**Comment by joshtrichards** [comment]
[help.nextcloud.com](https://help.nextcloud.com/c/international/deutsch/19)
