### ISSUE TITLE
Notifications: integrate with android notification system

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#1344]
Followup of https://github.com/nextcloud/android/issues/1311#issuecomment-322104730

> I think it doesn't notificate the Android system about notification, is it?

As it is better to have a separate issue for this, @xXSTrikeXx can you explain a bit more what you mean?

**Comment by xXSTrikeXx** [comment]
I just generated a message:
sudo -su www-data php  /var/www/nextcloud/occ notification:generate admin "message"

The desktop client needed 2 minutes to receive a notification. Yesterday I was on the move. So I didn't tested it at all and my question was, if it is already implemented that the app sends notification to the Android system, like the notifications of permitted or failed uploads.
I just generated now another generated notification and only the desktop client shows me the notification.

_Sent from my HUAWEI MYA-L41 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by mario** [comment]
Push should work, even if it only shows "New notification received". If it does not, it's a bug.

**Comment by xXSTrikeXx** [comment]
I will test it today and update to latest nc version.

_Sent from my HUAWEI MYA-L41 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by xXSTrikeXx** [comment]
@mario I haven't yet tested it on latest nc version, but on 12.0.1 only the win client works as well. I havent got time today to update and tomorrow I will help an a move. So please give me 2 days for testing it and to create a Test Account.😉

_Sent from my HUAWEI MYA-L41 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by xXSTrikeXx** [comment]
Hey folks, I have tested it now with both latest versions and it dont work. There's no notification for android. But if I open notification tab in the app it shows me the notification, but it has never inform me in the android way.

_Sent from my HUAWEI MYA-L41 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by xXSTrikeXx** [comment]
I already generetad such many notifications. And the Server generated update notifications. But nothing of them reached the android stock.

**Comment by tobiasKaminsky** [comment]
@mario I guess this is related to/dup of #1707 and the PR #1836, or?

**Comment by tobiasKaminsky** [comment]
No response within the last month, therefore closing.
Please feel free to reopen with additional infos, if the problem still exists.
