### ISSUE TITLE
Maintenance mode crashes android app

### ISSUE THREAD

**Issue by geez0x1** [nextcloud/android#1347]
### Actual behaviour
- Android app crashes upon Manage Accounts -> select account name

### Expected behaviour
- Open the account settings
 
### Steps to reproduce
1. Put nextCloud server in maintenance mode
2. Open Android app and try to select the account to delete it (I moved to my new server)
3. Crash (tried twice)
4. Disable server maintenance mode
5. Try again and be successful

### Environment data
Android version:
7.1.1
Device model: 
HTC One M7
Stock or customized system:
Custom ROM: LineageOS 14.1-20170302-NIGHTLY-m7
Nextcloud app version:
1.4.2
Nextcloud server version:
11.0.4
#### Web server error log
```
nothing
```

#### Nextcloud log (data/nextcloud.log)
```
Unsure how to find this on android
```

**Comment by AndyScherzinger** [comment]
@geez0x1 does this also happen with 2.0.0 rc2 (unfortunately only available via Google Play store at the moment)?

**Comment by geez0x1** [comment]
@AndyScherzinger I'm not sure, I have it installed through F-Droid and I don't really have the time to re-setup nextCloud from the play store right now, sorry! If it becomes available on F-Droid I'll give it a test.

**Comment by AndyScherzinger** [comment]
@geez0x1 no problem :) Thanks for the update. So we will have to wait for f-droid.

**Comment by AndyScherzinger** [comment]
@geez0x1 2.0.0RCs are available on f-droid now 🎉 If you find the time would you mind giving it a try? 😃

**Comment by tobiasKaminsky** [comment]
Tried the steps and I get 503 connection error when showing account info of account on server with maintenance mode, so this works without a crash now.

**Comment by geez0x1** [comment]
I can confirm this works for me too (App version 3.1.0 through F-Droid). Sorry for the delay :)

**Comment by AndyScherzinger** [comment]
Thanks for the feedback @geez0x1 and happy to hear it has been resolved :)
