### ISSUE TITLE
What happened to NC app 1.5?

### ISSUE THREAD

**Issue by OlivierS1** [nextcloud/android#1349]
### Actual behaviour
-Tell us what happens
There has been talks about NC app 1.5 but recently there has been a new roadmap/milestone to rev 2.0.
Today, I got NC App 2.0.0.RC2 updated on my phone.

Has 1.5 been dropped or simply upgraded to 2.0?

**Comment by mario** [comment]
We changed 1.5 to 2.0 due to number of changes it ships with.
