### ISSUE TITLE
Use primary font color via capabilities

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#1351]
https://github.com/nextcloud/server/pull/6128

Then "our" font color computation can be removed

**Comment by tobiasKaminsky** [comment]
ServerTextColor is supported on NC12+, so we have to keep this until EOL of NC11.

https://github.com/nextcloud/android/blob/614d78ba58c34b75f4b796b9f9595d6e7f90267b/src/main/java/com/owncloud/android/utils/ThemeUtils.java#L140-L154

**Comment by AndyScherzinger** [comment]
> ServerTextColor is supported on NC12+, so we have to keep this until EOL of NC11.

Fine by me while I'd still vote to support the fallback until 12 is EOL.
