### ISSUE TITLE
Back Button Behaviour and Navigation Problems

### ISSUE THREAD

**Issue by alperozturk96** [nextcloud/android#13574]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Have some personal or shared files
2. From drawer menu, pick personal or shared files
3. Personal or shared files will be listed
4. Navigate any folder inside personal or shared files
5. Press back button
6. All files will be listed instead of previous directory

### Expected behaviour

When a user pressing the back button, the user should return to the previous directory.

### Actual behaviour

Pressing the back button does not return the user to the expected root directory

### Android version

14

### Device brand and model

Android Emulator

### Stock or custom OS?

Stock

### Nextcloud android app version

3.30.0

### Nextcloud server version

29.0.4

### Using a reverse proxy?

I don't know

### Additional information

The issue arises due to the lack of a proper navigation flow and the inability to provide a single source of truth because many classes are inherits from one another. 

By gradually eliminating the dependencies between the classes and establishing a proper navigation flow, this issue will be resolved.

**Comment by joshtrichards** [comment]
Presumably fixed by #13599?

**Comment by alperozturk96** [comment]
fixed by https://github.com/nextcloud/android/pull/13599
