### ISSUE TITLE
Blank Screen When Accessing 'Internal 2-Way Sync'

### ISSUE THREAD

**Issue by tobias0409** [nextcloud/android#13579]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Installed the latest version of the Nextcloud Android APK (v3.30.0)
2. Navigated to Settings -> Sync and selected the new "Internal 2-way sync" option
3. The screen goes blank, and nothing happens

https://github.com/user-attachments/assets/3b1e2a0d-6c9f-450e-ba93-9c789509a4c0

### Expected behaviour

The 2-way sync options screen should be displayed after selecting the "Internal 2-way sync" option.

### Actual behaviour

After selecting the "Internal 2-way sync" option, the screen goes blank with no content or options displayed, and no further actions occur.

### Android version

14

### Device brand and model

Samsung Tab S7 FE

### Stock or custom OS?

Stock

### Nextcloud android app version

3.30.0

### Nextcloud server version

29.0.6

### Using a reverse proxy?

Yes

**Comment by d4rkw1n9** [comment]
What was the solution? Got exactly the same issue.

**Comment by tobias0409** [comment]
> What was the solution? Got exactly the same issue.

There so no solution because there is no problem - only the UI is not very user friendly.

You need to open the details of a folder and then you can find a checkbox called *Sync*. Select it. After that you can see the folder in the options -> 2-way sync.

**Comment by Welved** [comment]
> > What was the solution? Got exactly the same issue.
> 
> There so no solution because there is no problem - only the UI is not very user friendly.
> 
> You need to open the details of a folder and then you can find a checkbox called _Sync_. Select it. After that you can see the folder in the options -> 2-way sync.

Yea, that works; but it doesn't actually sync changes. It just creates a directory, it's a one-way sync.

**Comment by tobias0409** [comment]
> > > What was the solution? Got exactly the same issue.
> > 
> > 
> > There so no solution because there is no problem - only the UI is not very user friendly.
> > You need to open the details of a folder and then you can find a checkbox called _Sync_. Select it. After that you can see the folder in the options -> 2-way sync.
> 
> Yea, that works; but it doesn't actually sync changes. It just creates a directory, it's a one-way sync. Meaning, any change not made by the app itself is not at all synced.

Yes, I noticed that too. Since it's another problem, I've created a new issue here: #13752
