### ISSUE TITLE
Blank screen when access to Internal 2-Way Sync

### ISSUE THREAD

**Issue by ivanhercaz** [nextcloud/android#13586]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Upgrade to Nextcloud Dev 20240913.
2. Open "Configuration" in the side menu.
3. Press "Internal two way sync".

### Expected behaviour

The expected behavior is to see the new internal two way options to test and use them.

### Actual behaviour

The actual behavior is it isn't possible to test it because it seems to be some issue with the rendering of the screen or maybe with some widget.

I test with both themes, dark and light, and in both appears a white screen.

![Screenshot_2024-09-19-07-02-58-13_1a9f256f1813f5f4c01c5b3da1928c25](https://github.com/user-attachments/assets/b33e57c0-6618-4cc8-9402-4a6aed12948e)
![Screenshot_2024-09-19-07-03-21-27_1a9f256f1813f5f4c01c5b3da1928c25](https://github.com/user-attachments/assets/2ed61919-d6fd-4756-8845-ccad9cdf48aa)

### Android version

14

### Device brand and model

Realme C55

### Stock or custom OS?

Stock

### Nextcloud android app version

20240913

### Nextcloud server version

29.0.5

### Using a reverse proxy?

I don't know

### Additional information

I will attach the log of the application as soon as possible, because with the mobile it is being impossible to copy today's lines.

Anything I can help you to debug this issue, just ask me!

Thanks for all your efforts and great work with this application!

**Comment by 000yesnt** [comment]
https://github.com/nextcloud/android/issues/13579#issuecomment-2357504487

**Comment by ivanhercaz** [comment]
> https://github.com/nextcloud/android/issues/13579#issuecomment-2357504487

Thank you for referencing the comment, @000yesnt! I admit that I didn't search to check if this was already reported. So soon in the morning 😅.

Closes per https://github.com/nextcloud/android/issues/13579#issuecomment-2357504487
