### ISSUE TITLE
Transifex Updates seem to not work

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#136]
@MorrisJobke @LukasReschke can you have a look at this? We only had 1 push into the repo a couple of days ago and whenever I open transifex the last update on _all_ languages is current day 12:32a.m. so it seems something is not functioning correctly :(

**Comment by MorrisJobke** [comment]
I will check that later. Thanks for the pointer.

**Comment by MorrisJobke** [comment]
5ef50c6658a9a8767c65bda4f56306c4cec47c57

I adjusted the script to force pull translations (to always overwrite the local one, because a fresh clone always has a newer timestamp on the files 😵 )

**Comment by AndyScherzinger** [comment]
That's true :smile: 
So will the script also auto push the master (values/strings.xml) _TO_ transifex?

**Comment by MorrisJobke** [comment]
> So will the script also auto push the master (values/strings.xml) TO transifex?

Yes :)

See https://github.com/nextcloud/docker-ci/commit/eb8a06647c413dc1ebf8aad137a3a621e6a43e0d for the force pull and https://github.com/nextcloud/docker-ci/blob/master/translations/handleTranslations.sh is the script for the server - this is used with a different git URL for the android repo (and without the perl magic).

**Comment by AndyScherzinger** [comment]
Sweet! :)
Thanks for all the infos and explanation :)

**Comment by AndyScherzinger** [comment]
@MorrisJobke can I get full access to the translations on transifex to fix user translation mistakes?
see: https://github.com/nextcloud/android/commit/7f9cf817a734c73b815351fadb1de25b8f665b38
The translators double escaped the Strings :disappointed:     ```\n``` --> ```\\n```

**Comment by MorrisJobke** [comment]
> The translators double escaped the Strings 😞 \n --> \\n, or the export is just wrong

Let me check that.

**Comment by MorrisJobke** [comment]
Looks like a transifex bug:

<img width="575" alt="bildschirmfoto 2016-07-19 um 11 08 42" src="https://cloud.githubusercontent.com/assets/245432/16944496/348d43f6-4da1-11e6-88e4-a4f8a6dcf631.png">

**Comment by MorrisJobke** [comment]
I reported it to transifex. Let's see what they answer.

**Comment by AndyScherzinger** [comment]
Thanks! :smiley: :+1:

**Comment by MorrisJobke** [comment]
To fix this the rich editor needs to be disabled (gear icon -> "Enable Rich/Raw editor" and then you have a switch visible that allows to turn of the Rich editor).

The weird thing is, that if you fix the \n, save it and switch back to the rich editor it looks exactly the same. I just wrote them this back and will post the answer then here:)

**Comment by AndyScherzinger** [comment]
Thank you for your effort @MorrisJobke !

**Comment by MorrisJobke** [comment]
It seems that this is the only way to address the issue :( Every translator needs to be aware of this. @AndyScherzinger I will give you the rights to adjust the translations
