### ISSUE TITLE
DEV-20170817: app crashes when trying to edit the account settings.

### ISSUE THREAD

**Issue by j-ed** [nextcloud/android#1364]
### Actual behaviour
If I open an existing account to edit its setting, the Nextcloud app instantly crashes.

### Expected behaviour
It should be possible to edit the settings of an existing account.
 
### Steps to reproduce
1. Open the Nextcloud app.
2. Select "Manage Account"
3. Select and existing account.
4. The message "Nextcloud dev wurde beendet" is shown.

### Environment data
Android version: 7.1.1

Device model: Jiayu S3 Adv.

Stock or customized system: MadOS ROM

Nextcloud app version: dev-20170817

Nextcloud server version: 12.0.2 

#### Web server error log

Nothing special has been logged related to this problem.

**Comment by tobiasKaminsky** [comment]
Can you provide us a logcat of the crash?
 https://github.com/nextcloud/android/blob/master/README.md#get-debug-infos-via-logcat

I tried it with on my own phone and it works without a problem :confused:

**Comment by j-ed** [comment]
@tobiasKaminsky Can you please tell me your email address to send you the file?

**Comment by tobiasKaminsky** [comment]
android at nextcloud dot com

**Comment by j-ed** [comment]
[**x**] locat file provided.

**Comment by j-ed** [comment]
I can confirm that the problem has been fixed with the latest app version `app-20170901`.

**Comment by AndyScherzinger** [comment]
likely fixed via https://github.com/nextcloud/android/pull/1467

**Comment by AndyScherzinger** [comment]
Thanks for the instant feedback @j-ed
