### ISSUE TITLE
Cannot upload files due to invalid characters/reserved names (that are not present)

### ISSUE THREAD

**Issue by xsolinsx** [nextcloud/android#13658]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. use a gallery/FM app to select a picture/video
2. select the item and tap on share
3. select nextcloud and pick the folder to upload to
4. click on "upload"

### Expected behaviour

the file does get uploaded correctly

### Actual behaviour

nextcloud app says
"this file cannot be uploaded"
"some contents cannot able to uploaded due to contains reserved names or invalid characters"

### Android version

14

### Device brand and model

Nothing Phone 2a

### Stock or custom OS?

Stock

### Nextcloud android app version

3.30.0

### Nextcloud server version

30

### Using a reverse proxy?

Yes

### Additional information

no server log available, it seems to be a client-side check
no client logs available but I tested the DEV version of 20240927 and the upload did work fine without raising the issue

I'm uploading a file named `xcdB.mp4` under a folder named `temp` on nextcloud's root

this started happening with the new update (don't know if server or android app but I believe it's the app's fault since it does not happen with the DEV version), it was working fine previously

**Comment by rainij** [comment]
The update of the android version from 3.30.0 to 3.30.1 fixed the bug for me.

**Comment by joshtrichards** [comment]
Fixed in #13669 / #13606
