### ISSUE TITLE
DEV-20170817: add an indicator to the app menu if not all menu entries are displayed

### ISSUE THREAD

**Issue by j-ed** [nextcloud/android#1366]
### Actual behavior
If not all menu entries of the app can be displayed, this is not visible to the user. Additionally the distance between the last displayed menu entry and the usage bar might be leading to the assumption that there are no additional entries.

![20170817_netxcloud_dev_app](https://user-images.githubusercontent.com/2572764/29413992-9e31029a-835e-11e7-855c-47ef2b954707.jpg)

### Expected behavior
And indicate should be shown at the bottom of the displayed menu if not all menu entries are displayed.
 
### Steps to reproduce
1. Open the Nextcloud app.
2. Open the menu.
3. Check how the entries are displayed.

### Environment data
Android version: 7.1.1

Device model: Jiayu S3 Adv.

Stock or customized system: MadOS ROM

Nextcloud app version: v1.4.3 20170817-dev

Nextcloud server version: 12.0.2 

#### Web server error log

Nothing special has been logged related to this problem.

**Comment by tobiasKaminsky** [comment]
Thank you for this suggestion. Indeed there is something needed, but do you have an idea how? Maybe a screenshot of another app?

A scrollbar could be possible, but this is kind of ugly, or?
<img src="https://i.stack.imgur.com/l9R7x.png"/>

cc @nextcloud/designers

**Comment by j-ed** [comment]
@tobiasKaminsky You're right, that's the way how Google apps etc. are handling such kind of menus.

**Comment by jancborchardt** [comment]
First off, that big amount of vertical whitespace above the quota bar should be reduced. Then it probably is already better. :) A permanent scrollbar is not that nice.

**Comment by AndyScherzinger** [comment]
We do show a scrollbar while opening the menu and it disappears after ~2 seconds (same behavior as the Google apps) which indicates more content on scroll.

**Comment by j-ed** [comment]
You're right. I've never realized that scroll-bar, maybe because it is so slim and vanishes after that time.

**Comment by jancborchardt** [comment]
@AndyScherzinger ah yes. Can we additionally cut a bit off of the vertical whitespace on top of the quota bar? Or what is that for?

**Comment by tobiasKaminsky** [comment]
@jancborchardt how much do you want to cut? I think the space is fine as otherwise the items are two narrow.

![2017-10-30-090657](https://user-images.githubusercontent.com/5836855/32160362-ba89713e-bd51-11e7-80a4-da0348ad8c19.png)

On the initial screen is a larger gap 
![2017-10-30-090846](https://user-images.githubusercontent.com/5836855/32160409-f29e1282-bd51-11e7-93e0-0e3dc86cc2d1.png)

But this is because of the "separation" of regular items and external links/items/apps:
![2017-10-30-090840](https://user-images.githubusercontent.com/5836855/32160438-13209e8a-bd52-11e7-9a4d-637a4d94c5ff.png)

**Comment by jancborchardt** [comment]
@tobiasKaminsky there it seems fine. However in the normal app there is no "do you want more space" text above the quota bar. Could we reduce the height accordingly when that text is not present?

**Comment by tobiasKaminsky** [comment]
Now I got it.
