### ISSUE TITLE
Autoupload uploads on 4G as well, instead of Wifi only

### ISSUE THREAD

**Issue by WebSpider** [nextcloud/android#1370]
### Actual behaviour
After testing a few days with the NC beta app from the Play store, there is one annoying bug:

I have my auto-upload set to function on wifi only, with no charger limitations.
Whenever you connect to a wifi network that is captive-portaled, the app doesn't wait until internet connectivity is made via wifi, but just starts uploading via 4G, pending the [OK] on the captive portal.

### Expected behaviour
Autoupload should only send data over Wifi, like configured
 
### Steps to reproduce
1. Download beta app from Play Store and configure basic settings
2. Enable auto-upload, Enable 'Only upload on Wi-Fi' in preferences for auto uploading
3, Add new content tot the selected folder (in my case: Take a picture)
4. Connect phone to a captive-portal enabled network (in my case: Railway transport public network in NL)
5. Upload seems to start upon association to Wi-Fi, but Wi-Fi is then still a limited network (little exclamation mark next to the Wi-Fi symbol)

### Environment data
Android version: 7.1.1

Device model: OnePlus 3

Stock or customized system: Stock

Nextcloud app version: 2.0.0RC2

Nextcloud server version: 
www-data@cumulus:~/nextcloud$ ./occ status
  - installed: true
  - version: 11.0.4.1
  - versionstring: 11.0.4
  - edition:

**Comment by WebSpider** [comment]
Remaining issue from #761

**Comment by WebSpider** [comment]
Suggestion: Maybe only start auto-upload if Wi-Fi is connected, the NC server can be reached, and Wi-Fi is not limited in Internet connectivity according to the Android OS?

**Comment by WebSpider** [comment]
Also present in 2.0.0rc3

**Comment by mario** [comment]
Unlikely to get fixed for 2.0.0, so setting it to 2.0.1

**Comment by mario** [comment]
Should be fixed via https://github.com/nextcloud/android/pull/1672

**Comment by WebSpider** [comment]
Can't wait for the new beta app :)

**Comment by mario** [comment]
This will be in 2.1, not 2.0.0, sorry :(

**Comment by tobiasKaminsky** [comment]
Fixed by #1672, closing.
Please response if it does not work.

Maybe you want to try out our dev version (you can install it in parallel): 
https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#dev-release
