### ISSUE TITLE
Add more MDM cabilities

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#13725]
- disable welcome screen
- disable multiaccount (haben wir sonst nur global über Branding)
- enable/disable crash_service (Error reporting tool)
- disable log
- disable external sites
- disable open in / sharing / copy & paste (clipboard) -> security

**Comment by alperozturk96** [comment]
We already have some of these capabilities in current codebase, fyi. @tobiasKaminsky 

"show_external_links" --> disable external sites
"logger_enabled" --> disable log
