### ISSUE TITLE
Can't login with email username

### ISSUE THREAD

**Issue by f1lint** [nextcloud/android#1373]
### Actual behaviour
Can't login with email user name. After enter login/password a redirect page appears, but nothing happens more. In server log appears:

{"reqId":"j44SliGSMFW8XhGmIkWM","level":2,"time":"2017-08-18T09:50:54+00:00","remoteAddr":"X.X.X.X","user":"--","app":"core","method":"HEAD","url":"\/remote.php\/webdav\/","message":"Login failed: 'user%40domain.com' (Remote IP: 'X.X.X.X')","userAgent":"Mozilla\/5.0 (Android) ownCloud-android\/2.0.0RC2","version":"12.0.2.0"}
 
### Environment data
Android version: 7.0NRD90M
Device model: Xiaomi Mi5, Elephone p8000
Stock or customized system: Stock system
Nextcloud app version: Nextcloud 2.0RC2
Nextcloud server version: Nextcloud 12.0.2

**Comment by tobiasKaminsky** [comment]
This is working fine on a local test server with RC2.
Can you provide us a test login and send it to andoid at nextcloud dot com?

**Comment by f1lint** [comment]
Hi Tobias
I send test credential to e-mail

**Comment by tobiasKaminsky** [comment]
This is fixed via #1410 and will be in next RC5.
