### ISSUE TITLE
File Details Not Opening From Media Tab

### ISSUE THREAD

**Issue by alperozturk96** [nextcloud/android#13748]
### ⚠️ Before posting ⚠️

- [x] This is a **bug**, not a question or an enhancement.
- [x] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [x] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Open Media Tab
2. Preview an image
3. Try to open file details

### Expected behaviour

It should show file details

### Actual behaviour

It's not showing file details, returning to media tab

### Android version

14

### Device brand and model

Android Emulator

### Stock or custom OS?

Stock

### Nextcloud android app version

3.30.1 RC1

### Nextcloud server version

29.0.4

**Comment by joshtrichards** [comment]
Related: #12163
