### ISSUE TITLE
Two-way internal synchronization does not work and displays a blank page

### ISSUE THREAD

**Issue by miltuss** [nextcloud/android#13753]
Two-way internal synchronization does not work and displays a blank page as soon as the button is clicked in the settings. This is a major bug that completely blocks this functionality, and I'm surprised to see that this bug is present in the stable version of the Nextcloud application.

I have already talked about this bug on matrix and everyone is faced with this blank page which completely blocks the `2-way-sync` function

![Image](https://github.com/user-attachments/assets/732b2b27-fd73-48ab-9261-0a0510a4eb34)

How to solve this problem?

**Comment by joshtrichards** [comment]
Duplicate of #13693 

Note this is a UI/UX matter. See https://github.com/nextcloud/android/issues/13579#issuecomment-2357504487 for setup instructions.
