### ISSUE TITLE
DEV-20170818: no image previews are shown

### ISSUE THREAD

**Issue by j-ed** [nextcloud/android#1378]
### Actual behavior
No image previews are shown in the app.

![20170819_pic_list](https://user-images.githubusercontent.com/2572764/29486664-e85f1e18-84eb-11e7-8704-2dfa3aca0aa9.png)

### Expected behavior
Image previous should be shown in the app.

### Steps to reproduce
1. Open the Nextcloud app.
2. Open a folder which contains picture files..
3. Check how the files are displayed.

### Environment data
Android version: 7.1.1

Device model: Jiayu S3 Adv.

Stock or customized system: MadOS ROM

Nextcloud app version: v1.4.3 20170818-dev

Nextcloud server version: 12.0.2 

#### Web server error log

Nothing special has been logged related to this problem.

**Comment by j-ed** [comment]
After installing DEV-20170901 I found out that the described behavior seems to be cause by an extremely slow thumbnail generation and transfer to the mobile device. In detail the process look like this:
1. You open a directory.
2. The directory content is loaded and an animation at the top of the window is showing the progress.
3. After the animation has stopped all files are shown without any thumbnails.
4. If you keep the view open without doing anything, the thumbnails are loaded and displayed one-by-one. This activity isn't accompanied by any progress animation at the top of the window.

**Comment by AndyScherzinger** [comment]
This will be covered in the other issues that describe the use of recycler view, glide and different server side thumbnail parts. So closing it as duplicate.
