### ISSUE TITLE
Sharing multiple files towards Nextcloud Files app uploads only one file

### ISSUE THREAD

**Issue by thgoebel** [nextcloud/android#13795]
### ⚠️ Before posting ⚠️

- [x] This is a **bug**, not a question or an enhancement.
- [x] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [x] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Open a file manager app, e.g. https://f-droid.org/en/packages/me.zhanghai.android.files/
2. Select multiple files
3. Click "Share"
4. Select Nextcloud
5. Select a folder within Nextcloud
6. Click "Upload"

### Expected behaviour

All files are uploaded.

### Actual behaviour

Only the one file is uploaded.

Note that when you go via Nextcloud -> Upload files -> select multiple files, then all selected files are uploaded correctly.
The issue is only with files shared via Intents towards Nextcloud.

### Android version

14

### Device brand and model

OnePlus 5

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

3.30.0 (F-Droid)

### Nextcloud server version

29.0.7

### Using a reverse proxy?

Yes

**Comment by joshtrichards** [comment]
See #10937 :)
