### ISSUE TITLE
DEV-20170818: click on image downloads not translated and strange character

### ISSUE THREAD

**Issue by j-ed** [nextcloud/android#1379]
The configuration parameter `"Click on image downloads"` hasn't yet been translated and a strange character is displayed behind the entry:

![20170819_settings](https://user-images.githubusercontent.com/2572764/29486676-102e274a-84ec-11e7-9308-ec261a35e693.png)

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky can you have a look at this one?
@j-ed the feature hasn't been integrated into our master so the String won't show up to translators. This will change as soon as the feature is scheduled for the next stable release.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky I commited a fix to your feature branch https://github.com/nextcloud/android/commit/dcdd708e62fa2a7cdefe66c17a87a89dddca41bf
