### ISSUE TITLE
Ständiger Up-/Download

### ISSUE THREAD

**Issue by TimoQu** [nextcloud/android#13827]
### ⚠️ Before posting ⚠️

- [x] This is a **bug**, not a question or an enhancement.
- [x] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [x] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Hallo,

ich habe festgestellt, dass Nextcloud seit gestern ca. 15 GB Datenvolumen verbraucht hat. Die Menge an Daten in meiner Cloud beträgt aber nur 2,9 GB. Also was genau wird da die ganze Zeit übertragen?

Sobald ich die App öffne, werde irgendwelche Daten übertragen. Einstellungen habe ich nicht geändert und die App seit längerem nicht genutzt.

Freundliche Grüße
Timo

### Expected behaviour

Es wäre super, wenn ich herausfinden kann, warum und vor allem was für Daten übertragen werden.

### Actual behaviour

Derzeit muss ich die Nextcloud App explizit schließen, damit mein Datenvolumen nicht kontinuierlich verbraucht wird.

### Android version

13

### Device brand and model

Xiaomi Redmi Note 10 Pro

### Stock or custom OS?

Stock

### Nextcloud android app version

3.30.1

### Nextcloud server version

30.0.1

### Using a reverse proxy?

I don't know

**Comment by TimoQu** [comment]
Ok

**Comment by joshtrichards** [comment]
Duplicate of #13738 (probably)
