### ISSUE TITLE
Nextcloud a craqué, il se met à vouloir tout me synchroniser

### ISSUE THREAD

**Issue by al733** [nextcloud/android#13844]
### ⚠️ Before posting ⚠️

- [x] This is a **bug**, not a question or an enhancement.
- [x] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [x] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Aucune. Sans rien demander à l'application Nextcloud et alors que j'étais en train d'uploader une photo sur le Nextcloud de mon université, je vois plein de notifications de fichiers qui se téléchargent. Je suis obligé de couper internet sur mon téléphone car je dois désactiver un par un la synchronisation des dossiers. Rien de récursif, pas de paramètre global, je vais y passer des heures...

### Expected behaviour

Rien du tout

### Actual behaviour

Sans rien demander à l'application Nextcloud et alors que j'étais en train d'uploader une photo sur le Nextcloud de mon université, je vois plein de notifications de fichiers qui se téléchargent. Je suis obligé de couper internet sur mon téléphone car je dois désactiver un par un la synchronisation des dossiers. Rien de récursif, pas de paramètre global, je vais y passer des heures...

### Android version

14

### Device brand and model

Galaxy S23

### Stock or custom OS?

Stock

### Nextcloud android app version

3.30.1

### Nextcloud server version

???

### Using a reverse proxy?

I don't know

**Comment by Ghoelian** [comment]
So if google translate did its job, you're saying nextcloud started downloading every file, right?

If so, it just started doing exactly the same for me. I tried revoking the filesystem permissions, but I think that just caused it to never flush the files out of ram, so my entire phone crashed and rebooted.

Nextcloud never had permission to write anywhere to my phone except pictures and videos, and I can't find the files anywhere, so I think they got deleted when I uninstalled the app.

**Comment by Ghoelian** [comment]
Might wanna rewrite this issue in English btw, since everything else in this repo is also in English.

**Comment by marjatech** [comment]
Same issue here, this eats up a lot of data Volume. Im disabling the APP now until there will be a fix.

**Comment by joshtrichards** [comment]
Duplicate of #13738
