### ISSUE TITLE
Beta app: Upload on charger-only not honored

### ISSUE THREAD

**Issue by WebSpider** [nextcloud/android#1385]
When using the latest beta app (2.0.0rc3) the setting of auto upload only when charger connected is not honored, when also connecting to wifi

Steps to reproduce:

Environment: same as #1370

1. Install app
2. Add your cloud
3. Add auto upload for Camera folder. Set it to wifi only
4. Connect to wifi, take a picture, see it upload
5. Disconnect wifi
6. Set folder to charger upload and wifi upload only
7. Take picture
8. Connect to wifi
9. See upload happening

I would have expected it to start uploading only when wifi and charger are connected

(submitted via github app for android, so template was missing)

**Comment by mario** [comment]
@AndyScherzinger maybe you can check if charger requirement is properly set in the db?

**Comment by AndyScherzinger** [comment]
see #1394 should be fixed with 2.0.0 RC4
