### ISSUE TITLE
Files are auto-synced despite not setting it on

### ISSUE THREAD

**Issue by dlmw** [nextcloud/android#13868]
### ⚠️ Before posting ⚠️

- [x] This is a **bug**, not a question or an enhancement.
- [x] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [x] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Have photos on phone
2. Launch application
3. ???

### Expected behaviour

It shouldn't auto sync without my permission

### Actual behaviour

It auto-synced without my permission. Now I have albums that are duplicates in my gallery, and it's now uploading albums that contains hundreds of pictures (oh, and multiple notifications for each of them).

### Android version

13

### Device brand and model

Samsung Galaxy S20 5G

### Stock or custom OS?

Stock

### Nextcloud android app version

3.30.1

### Nextcloud server version

30

### Using a reverse proxy?

Yes

**Comment by skotti-de** [comment]
Apparently syncing goes completely wild - in my case the entire content of Nextcloud is synced to the device which is running out of storage.

**Comment by joshtrichards** [comment]
Duplicate of #13738
