### ISSUE TITLE
Motivate more users for RC testing

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#139]
Show somewhere in the setting a direkt link to register for beta channel (RC) testing on play store.
@jancborchardt @AndyScherzinger 

PR: #239

**Comment by AndyScherzinger** [comment]
atm we have 197 registered testers in the Play store beta program

**Comment by tobiasKaminsky** [comment]
This is really great, but how many are reporting back to us?

**Comment by AndyScherzinger** [comment]
I guess around 2-3? At least that is round about the number of people who have reported issues. Else I just check the d3ev console for any crashes and ANRs.

**Comment by tobiasKaminsky** [comment]
Yeah, and this is the reason why I think that having more RC tester gets us more feedback ;-)
But maybe I am wrong and people are lazy ;)

**Comment by AndyScherzinger** [comment]
we are now at 248 enrolled testers

**Comment by jancborchardt** [comment]
Starting with the stupid questions: Where is it possible for a user to enrol in the testers program when you use the normal app from the play store?

I would likely stay away from popovers, but for the beta we could add something like a more present sidebar entry next to »Settings« to »Send feedback«.

**Comment by AndyScherzinger** [comment]
Just go here :) --> https://play.google.com/apps/testing/com.nextcloud.client and enroll :)

**Comment by tobiasKaminsky** [comment]
@jancborchardt can you make a suggestion?

**Comment by jancborchardt** [comment]
@tobiasKaminsky yeah, what do you think about what I said above?

> I would likely stay away from popovers, but for the beta we could add something like a more present sidebar entry next to »Settings« to »Send feedback«.

**Comment by tobiasKaminsky** [comment]
I guess my brain is overloaded...I do not get it...
In the drawer a new entry with...what? "Try our RC"?
And which beta? Beta in fdroid  is bleeding edge, whereas play store beta are our RCs...

**Comment by tobiasKaminsky** [comment]
@jancborchardt 
How about a new entry "Participate" in sidebar below "Settings".
This should be visible in regular app.
In it:

Help us testing. 
We offer two different previews of the upcoming version:
**Beta version** 
This includes all upcoming features and is very bleeding edge. Bugs/errors can occur and if so please report them back to us.
- Fdroid Beta Link

**RC candidate**
A release candidate is a snapshot of the upcoming release. It is expected to be stable and have no bugs. To ensure this we need your help testing it in a vary of server version/settings.
Available on play store: https://play.google.com/apps/testing/com.nextcloud.client
Available on fdroid: https://f-droid.org/repository/browse/?fdfilter=nextcloud&fdid=com.nextcloud.client -> manually look in versions.

**Reporting/contributing**
- per email: android@nextcloud.com
- per github: https://github.com/nextcloud/android/issues
- per IRC: #nextcloud-dev
- per forum: https://help.nextcloud.com/

Feel free to edit it just as you like it.

**Comment by Bugsbane** [comment]
Hi @tobiasKaminsky 

I hope you don't mind, but I went through and just fixed a few English grammar issues above. Feel free to correct mein kaput Deutsche any time!

**Comment by tobiasKaminsky** [comment]
@Bugsbane great, thank you!

@jancborchardt are you fine with this?

**Comment by jancborchardt** [comment]
@tobiasKaminsky yes, that sounds very good! :) Just edited a bit in the »Participate« section to make it more participatory and less about reporting issues via 4 different channels ;)

**Comment by tobiasKaminsky** [comment]
PR was merged
