### ISSUE TITLE
Proper handle result when uploading a virus file

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#1391]
Ref: https://github.com/nextcloud/server/pull/6079

Current response:
><?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>OCA\DAV\Connector\Sabre\Exception\UnsupportedMediaType</s:exception>
  <s:message>Virus Eicar-Test-Signature is detected in the file. Upload cannot be completed.</s:message>
</d:error>

--> parse message and show it in upload pane.

**Comment by AndyScherzinger** [comment]
see also oC / 1984

**Comment by tobiasKaminsky** [comment]
Server side: https://github.com/nextcloud/server/pull/6079

There should be nothing needed on our side as we just show the message from the server.
