### ISSUE TITLE
File auto upload stuck in "waiting for wifi connectivity"

### ISSUE THREAD

**Issue by simonemerlin** [nextcloud/android#1396]
### Actual behaviour
- set a folder for auto upload on Wi-Fi only.
- take a new picture 
- the picture appears in the upload list but stays in "waiting for Wi-Fi connection" even though Wi-Fi is active. I tried to disable/enable Wi-Fi but behavior does not change.

### Expected behaviour
-pictures taken and saved on a folder with auto upload set to Wi-Fi only should upload automatically when Wi-Fi is avaialble
 
### Steps to reproduce
1.set a folder for auto upload on Wi-Fi only.
2. Take a new picture 
3 the picture appears in the upload list but stays in "waiting for Wi-Fi connection" even though Wi-Fi is active

### Environment data
Android version: 6.0

Device model: htc

Stock or customized system:

Nextcloud app version: 2.0.0RC3

Nextcloud server version: 12.0.2

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by mario** [comment]
Try RC4 pls.

**Comment by simonemerlin** [comment]
I tried RC4. same behavior

2017-08-21 23:25 GMT-07:00 Mario Đanić <notifications@github.com>:

**Comment by mario** [comment]
Sounds strange. What happens when you retry manually? (You will need to enable expert mode in order to be able to do that)

**Comment by simonemerlin** [comment]
I enabled expert mode. retry does not help.

just to be clear, the problem is only for pictures taken while the 'only
upload on wifi' is selected. pictures taken with the 'only upload on wifi'
not selected, are uploaded correctly while on wifi (but of course those get
uploaded also when not in wifi...).
FYI, I tried with/without charger,  restart the phone, pictures in
SD/internal memory. the behavior is always the same.   the log is empty,
not sure how I can help.

2017-08-22 2:02 GMT-07:00 Mario Đanić <notifications@github.com>:

**Comment by mario** [comment]
Then it might think you're not on wifi. Are you on unmetered wifi?

**Comment by simonemerlin** [comment]
i'm with my home wifi, no data cap, connection is working fine; dd-wrt
access point.
indeed it seems nextcloud app does not realize wifi is on.

2017-08-22 23:12 GMT-07:00 Mario Đanić <notifications@github.com>:

**Comment by mario** [comment]
Should be fixed with RC9.
