### ISSUE TITLE
cumbersome to view images with question for every file

### ISSUE THREAD

**Issue by kollix** [nextcloud/android#13989]
Using version 3.30.4 on a Samsung Galaxy S8, Android 9

I'm only using NC for pictures (almost all taken via the camera of this phone), stored in different folders. I'm at home in my wlan where both (server and client) reside.

Note that I use the german version so I translate backwards to english:

Using the "all files" view, whenever I want to view a picture and tap on the thumbnail,
I get the question "no small picture available. Download full image?"

YES, of course I want to see the picure in its entirety, why else would I tap on it ?

This is annoying. Please get rid of that question and simply show it.
Or at least provide a global switch to never ask me again.

Bit the worst thing - which I think is a bug - is that even after I tap on "Yes" to that question,
the shown picure is STILL the same small thumbnail (just without a border)!
I then need to tap the top-left back arrow, select the picture again and only then I see
the full image.
I think this was not always a problem. Maybe a regression with some newer version ?

**Comment by joshtrichards** [comment]
I think this is #13515.
