### ISSUE TITLE
Same code style for AndroidStudio

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#14]
As proposed in ownCloud we should identify how to use (and enforce) the same style guide.
And then, after merging most of the old PR, we should refactor every class :)

**Comment by AndyScherzinger** [comment]
Oh yes! :tada:

**Comment by przybylski** [comment]
Coding convention I put together:
[nextCloud coding style.zip](https://github.com/nextcloud/android/files/333029/nextCloud.coding.style.zip)

**Comment by tobiasKaminsky** [comment]
Great, how can I apply this?
Best would be if this is automatically used by android studio

**Comment by przybylski** [comment]
I'll have a look how to automatically apply this.
You can import it manually by copying the xml file to AndroidStudio preferences directory and codestyles subdir.
Eg on my mac i have it at: ~/Library/Preferences/AndroidStudio2.1/codestyles
restart android studio, go to Preferences > Editor > Code Style > Java .
And select nextCloud coding style from Scheme menu.

**Comment by tobiasKaminsky** [comment]
https://stackoverflow.com/questions/22207920/what-is-githubs-character-limit-or-line-length-for-viewing-files-on-github

Line length 120 seems to work :)

**Comment by AndyScherzinger** [comment]
So I would say we go for an 120 since it fits GH and also every modern display easily

**Comment by tobiasKaminsky** [comment]
Then the remaining open question is how to force this for all of us automatically.

**Comment by AndyScherzinger** [comment]
Since it requires manual configuration in Android Studio there probably isn't a way to enforce this except documenting it in out guidelines and check it in the code reviews. :(

**Comment by tobiasKaminsky** [comment]
https://www.jetbrains.com/help/idea/2016.1/configuring-code-style.html
with .editorconfig it seems to be possible

**Comment by tobiasKaminsky** [comment]
https://androidbycode.wordpress.com/2015/02/14/applying-the-aosp-coding-style-in-android-studio/
Maybe we should not define our own code style but rather use the one from AOSP?

**Comment by AndyScherzinger** [comment]
AOSP sounds good to me, square also has its own definition so there are probably enough good definitions out there. 
Standard Android Studio + 120 character limit would imho be enough :)

**Comment by tobiasKaminsky** [comment]
So this are two new options?
- square
- standard android studio + 120 line limit

**Comment by AndyScherzinger** [comment]
Well that is up for discussion. I don't care to much about the details. The benefit is having a common configuration whichever that is. I'd probably go for >>standard android studio + 120 line limit<< since it is the simplest one to have.

**Comment by tobiasKaminsky** [comment]
I did a reformat with default android studio and compared it to master for one class.
Looks good to me.
We should also use "optimize imports", but do not use "rearrange code" as this does too much, or?

**Comment by AndyScherzinger** [comment]
Full Ack, sound good to me +1 for the organize imports

**Comment by tobiasKaminsky** [comment]
Can you add this do contributing.md?
If @przybylski is fine with it

**Comment by AndyScherzinger** [comment]
Do you know how to do it?

**Comment by AndyScherzinger** [comment]
added: https://github.com/nextcloud/android/pull/80/commits/89bf3e20733b60e7b2a753420b2d23ebf787fe58

>### Android Studio formatter setup

>Our formatter setup is rather simple:
* Standard Android Studio
* Line length 120 characters (Settings->Editor->Code Style->Right margin(columns): 120)
* Auto optimize imports (Settings->Editor->Auto Import->Optimize imports on the fly)

**Comment by tobiasKaminsky** [comment]
:+1:
