### ISSUE TITLE
instant upload bug - no account

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#140]
related to #25 

It seems one issue has been found with this one: If the user enables the instant upload and doesn't change the default folder, no account is saved as target account and the upload is not done. The broadcast receiver logs:

```
07-13 11:07:55.544 14302-14302/
com.owncloud.android W/com.owncloud.android.files.InstantUploadBroadcastReceiver: 
No account found for instant upload, aborting
```

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger 
We should try to fix bugs in the next release.
Do you think you can create a PR for 1.3.0?

**Comment by AndyScherzinger** [comment]
We should, unfortunately I am on Android N where instant upload is (completely broken), so I am not able to test/debug this matter :cry: Apart from this, yes fixing it right away would be the way to go.

**Comment by tobiasKaminsky** [comment]
ok, also fine for me.
You can use an emulator with android 5.x to test instant upload. This is the way I am always developing as I do not want to mess up my real device ;)

**Comment by tobiasKaminsky** [comment]
Closing as InstantUpload will be replaced by AutoUpload on all devices.
