### ISSUE TITLE
Only old version 3.29.2 is shown in Google Playstore

### ISSUE THREAD

**Issue by MatthiasJSchmidt** [nextcloud/android#14056]
### ⚠️ Before posting ⚠️

- [x] This is a **bug**, not a question or an enhancement.
- [x] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [x] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Open google playstore on Samsung S23. 
Search nextcloud
Version 3.29.2 shown.

### Expected behaviour

Should be latest released version

### Actual behaviour

Only old version is shown

### Android version

14

### Device brand and model

Samsung S23

### Stock or custom OS?

Stock

### Nextcloud android app version

3.29.2

### Nextcloud server version

30.0.2

### Using a reverse proxy?

Yes

### Server error logs

```bash

```

**Comment by MystikReasons** [comment]
Hi @MatthiasJSchmidt 
There's already an open issue regarding this topic: https://github.com/nextcloud/android/issues/13871
