### ISSUE TITLE
l10n: Need context

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/android#14073]
Please add context as comment to file

https://github.com/nextcloud/android/blob/0a1336a10f3f72573ae3e284980efe0ebbd33f92/app/src/main/res/values/strings.xml#L519

Reported at Transifex.

**Comment by ZetaTom** [comment]
This string is used in the new storage location dialogue (#14005). At runtime `%$1s` is replaced with with either `storage_internal_storage` (Internal Storage) or `storage_external_storage` (External Storage). The two values in brackets represent the amount of used storage space (`%$2s`) and the total amount of available storage space for that location (`%$3s`).

![data_storage_location_new](https://github.com/user-attachments/assets/85f36ad3-8b38-4e2f-a8ec-0d647b42cff0)

**Comment by CafeTango** [comment]
> This string is used in the new storage location dialogue ([#14005](https://github.com/nextcloud/android/pull/14005)). At runtime `%1$s` is replaced with with either `storage_internal_storage` (Internal Storage) or `storage_external_storage` (External Storage). The two values in brackets represent the amount of used storage space (`%2$s`) and the total amount of available storage space for that location (`%3$s`).
> 
> ![data_storage_location_new](https://github.com/user-attachments/assets/85f36ad3-8b38-4e2f-a8ec-0d647b42cff0)

Thank you for the clarification. However, from a translator point of view, we are unable to translate variables (in this case %1$s, %2$s and %3$s, please see screen shot) and the only items available for translation are the punctuation marks. And punctuation marks, I believe, are universal across languages.

 ![Image](https://github.com/user-attachments/assets/e0bf1209-162d-4f56-b04e-eca49d599954)

**Comment by ZetaTom** [comment]
@CafeTango I'm aware that translators can't change variables. To be honest, I'm not sure how this kind of expression is represented in different languages, especially in right-to-left languages, which is why I added this template to the strings.

Please let me know if I've missed anything!
