### ISSUE TITLE
Missing slash in Auto Upload for videos leads to wrong folder

### ISSUE THREAD

**Issue by HanZ92** [nextcloud/android#1413]
### Actual behaviour
-When Auto Uploading a Video, the Video won't be uploaded to PATH/2017/08 but instead to PATH2017/08 (note the missing "/" between PATH and 2017

### Expected behaviour
-The file should be uploaded to PATH/2017/08
 
### Steps to reproduce
0. Activate "Use Subfolder"
1. Take video
2. Wait for it to upload
3. Watch in Nextcloud

### Environment data
Android version: 5.0.2

Device model: HTC One M7

Stock or customized system: Rooted

Nextcloud app version: 1.4.3

Nextcloud server version: 12.0.2

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
Hi @HanZ92 - this has already been fixed for the upcoming release which is currently available as a release candidate. If you like to check it out you can opt in as a tester and then the Google Play store will show you the release candidate too: https://play.google.com/apps/testing/com.nextcloud.client

Or you can of course just wait for the final release.
