### ISSUE TITLE
Landscape mode

### ISSUE THREAD

**Issue by supercyanhero** [nextcloud/android#1417]
### Actual behaviour
When I go to landscape mode, app looks... You can see on the screenshot how an app looks:
 hackarchive.zzz.com.ua/screen.png

### Expected behaviour
I think you understand me :)
 
### Steps to reproduce
1. rewrite xml or add new for it (I don't really understand how it works)

### Environment data
Android version: 4.4.4

Device model: Nexus 7

Stock or customized system: stock

Nextcloud app version: 1.4.3

Nextcloud server version: ???

**Comment by AndyScherzinger** [comment]
@supercyanhero I can't open hackarchive.zzz.com.ua/screen.png 😿

**Comment by srkunze** [comment]
![image](https://user-images.githubusercontent.com/1389648/30178063-0203ddd8-9408-11e7-93ab-b8989edcea5b.png)

[Copy-pasted here directly]

**Comment by AndyScherzinger** [comment]
Ah 😃
I opened an issue for discussion here #1509

**Comment by AndyScherzinger** [comment]
So I'd close this one in favor of the new one.
