### ISSUE TITLE
mDNS - i.e. `https://name.local`

### ISSUE THREAD

**Issue by moonwolf-github** [nextcloud/android#1418]
Is there any plan to implement mDNS (bonjour, avahi or whatever it name is)? Sure it's system responsibility, but Android doesn't support it. For now i'm unable to use `https://name.local` address and it's very inconvenient.

**Comment by tobiasKaminsky** [comment]
As far as I know there is no plan yet.
I am not sure if it is worth the effort as the server is most of the time a static ip with a decent dns (big companies, providers, even private clouds with dynDNS, private clouds on local networks with router, ...)

Technically it seems to be possible to add it: https://developer.android.com/training/connect-devices-wirelessly/nsd.html

**Comment by rogatty** [comment]
I'm not sure if my case is worth the effort 😉 but it would be awesome to have it implemented. I have a local instance of Nextcloud on RaspberryPi and used IP in the Android app. Unfortunately, I don't have access to the router (ISPs policy) and after some time the IP has changed. The app doesn't allow me to change the account hostname, so the only thing I can do is to remove the account, set it up again and wait until it happens again. NSD would be great to have!

**Comment by 9at8** [comment]
I don't think mine is either now haha. I setup https://pi-hole.net on a different device, and set it up as the DNS server on my router. In addition to that, I added a dnsmasq entry from a custom uri to the static local IP address of the nextcloud device.

**Comment by robertbob987** [comment]
I deploy nextcloud on Raspberry Pi 4 and use it in the home network, I expect to access nextcloud via domain name on APP and I expect to do this with mDNS , now Raspberry Pi 4 is mDNS enabled and I expect nextcloud APP to support mDNS as well

**Comment by joshtrichards** [comment]
Android >= 10 natively supports mDNS `.local` resolution now. It's no longer necessary for each app to implement service discovery on their own.
