### ISSUE TITLE
Updated icons are not ok

### ISSUE THREAD

**Issue by mihaiile** [nextcloud/android#1420]
### Actual behaviour
I applaud the time spent in developing this application and I know is easy to just complain, but the new icons to me are still not ok.
1. just a check mark does not identify which application is that
2. the icon is HUGE! in fact is so big that the top and bottom has 0px in Ubuntu top bar, is just huge, something you would expect to see in a UI that is optimised for your grandparents.
While I do understand in the past was too small, I would say too big is also not that good... A compromise has to be taken to have a good design and a pleasing application to use.

This is how it is showing up, to me it is completely non professional and not appealing:
![image](https://user-images.githubusercontent.com/3273985/29659215-cfbe05ce-88bd-11e7-986c-40a754bea1fa.png)

### Expected behaviour
To address the 2 points above I would suggest to have a compromise where first the icons have to be scaled down a bit.
Second, why don't take the idea of what the green icon I have in above screen shot does and use a variation of that with what we had before, the original logo image where we could use a cropped version of before and after circles but in a horizontal line instead of 45 degrees the green icon has them. Yes it will make the icon smaller but I guess it will still be acceptable?
 
### Environment data
Ubuntu 17.04

Nextcloud app version:
Version 2.3.2

**Comment by xXSTrikeXx** [comment]
I think you posted in the wrong section. You are here in the android section, not linux.

_Sent from my HUAWEI MYA-L41 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by mihaiile** [comment]
oh yes, it's true, did not notice, can it be moved or it can be closed and I create another one in linux?

**Comment by xXSTrikeXx** [comment]
I'm not a member of, just a user, but I think it's this section:

https://github.com/nextcloud/client_theming

_Sent from my HUAWEI MYA-L41 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
