### ISSUE TITLE
Master build - Arabic Translation does not show up

### ISSUE THREAD

**Issue by HAlsunaydi** [nextcloud/android#14205]
### ⚠️ Before posting ⚠️

- [x] This is a **bug**, not a question or an enhancement.
- [x] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [x] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Hello ,

I cloned the repository and compiled the app on my device , on the master branch it doesn't show any translation ( While the UI is RTL )

When i changed the to the 3.30.6 tag it works as expected 

The device is on Arabic language 

Master branch : 

![Image](https://github.com/user-attachments/assets/1a0040d8-ad38-4ed1-96ee-ff7efc395cd7)
![Image](https://github.com/user-attachments/assets/5b372c5a-7819-47d6-b87b-6314b4eba2a3)

on stable 3.30.6 tag works fine  : 
![Image](https://github.com/user-attachments/assets/43324490-70c2-4d69-8373-6fe65b86e044)
![Image](https://github.com/user-attachments/assets/35ee19c2-bb01-41d7-900b-a662bee14ab7)

### Expected behaviour

Master branch should load the Arabic translation

### Actual behaviour

All the Strings are in English 

### Android version

14

### Device brand and model

Galaxy S23

### Stock or custom OS?

Stock

### Nextcloud android app version

Master

### Nextcloud server version

29

### Using a reverse proxy?

No

### Server error logs

```bash

```

**Comment by tobiasKaminsky** [comment]
Thank you for your report.
This is indeed strange.

I tested it with this language:
![Image](https://github.com/user-attachments/assets/e103fc00-9ea6-4a08-a828-9ebbd6a7737c)

And it shows mixed translations:
![Image](https://github.com/user-attachments/assets/5818bc5f-17fb-457c-a6d5-27db247d04b1) ![Image](https://github.com/user-attachments/assets/e5570e58-ac4e-4ae3-be90-9a3004430b45)


Is this the same region as you have selected?

**Comment by tobiasKaminsky** [comment]
Update: also German does not work.
So seems to be a general translation problem 😖

**Comment by tobiasKaminsky** [comment]
Found it: https://github.com/nextcloud/android/blob/3eef65d882686e317ed45f9767e5cfdc06babb6f/app/build.gradle#L150

This was added to speed up building process during development.
Will revert it.
