### ISSUE TITLE
Font problem on bright primary color

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/android#1422]
Use theming color: `#DFFFF4`

❌ Font is white instead of black
❌ Some activity items are blue instead of the color
🔧 When the theming color is too bright, we should use black as a font in activities

> ![bildschirmfoto vom 2017-08-24 15-01-55](https://user-images.githubusercontent.com/213943/29667715-bdcbddda-88dd-11e7-8f51-202be92d7889.png)

cc @tobiasKaminsky @AndyScherzinger

**Comment by tobiasKaminsky** [comment]
I adjusted the color generation a bit. What do you think?
(the left one is with code fff)

![2017-08-26-182153](https://user-images.githubusercontent.com/5836855/29743140-f86dde5c-8a8b-11e7-9aa1-abd5b84f02c1.png) ![2017-08-26-182231](https://user-images.githubusercontent.com/5836855/29743141-f89695ea-8a8b-11e7-9985-b568898d3e32.png)
![2017-08-26-182440](https://user-images.githubusercontent.com/5836855/29743142-f89aaa5e-8a8b-11e7-9995-bac99f9abe2c.png) ![2017-08-26-182402](https://user-images.githubusercontent.com/5836855/29743143-f89dc630-8a8b-11e7-95be-c1b82a4f162d.png)

**Comment by AndyScherzinger** [comment]
👍 fine by me since choosing a overly bright color will look bad at some point anyways
