### ISSUE TITLE
Activities has two times listed for each activity and they don't match. 

### ISSUE THREAD

**Issue by Boballen55** [nextcloud/android#1426]
### Actual behaviour
States "yesterday" above and to left of activity and "seconds ago to the bottom right of the activity. That second statement is always" seconds ago" 

### Expected behaviour
Just one statement of time and if there is more than one then why are they different? 
 
### Steps to reproduce
1. Check activities log after uploading something. 
2. 
3. 

### Environment data
Android version:7.1.2

Device model: nexus 6p

Stock or customized system: stock

Nextcloud app version: f-droid.org dev:20170823

```

**Comment by AndyScherzinger** [comment]
@Boballen55 can you provide a screenshot? I just tried it myself and (at least for me) it works fine
![screenshot_20170825-131822](https://user-images.githubusercontent.com/1315170/29715261-de1221ca-89a6-11e7-98a3-56a41ca0823b.png)

**Comment by Boballen55** [comment]
![screenshot_20170825-175958](https://user-images.githubusercontent.com/25942853/29735624-ee84b9aa-89bf-11e7-9e35-97230adc6ab0.png)

**Comment by Boballen55** [comment]
Found server version: 11.0.4snap1 Rev 2707

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky do you have a v11 instance where we could reproduce this behavior?

**Comment by xXSTrikeXx** [comment]
@Boballen55 Even with the lastest version? Or does it work now?

**Comment by AndyScherzinger** [comment]
@Boballen55 @xXSTrikeXx this should be resolved with the next feature release via #1659
