### ISSUE TITLE
Back button not working to the contacts recovery page

### ISSUE THREAD

**Issue by DarkVeter** [nextcloud/android#1427]
### Actual behaviour
Back button updates the current page
### Expected behaviour
Button back to the list of events
 
### Steps to reproduce
1. Enable contacts loading (* .vcf)
2. Go to events
3. Click on the downloaded * .vcf file to restore contacts
4. Click the back button
5. Back button not working
6. The next launch of the application will lead to the contact recovery page. This will continue until the device is rebooted.
### Environment data
Android version: 5.1 (Flyme 6.1.0.0G)

Device model: Meizu MX4

Stock or customized system: customized

Nextcloud app version: 2.0.0RC4

Nextcloud server version: 12.0.0

**Comment by tobiasKaminsky** [comment]
Is this still valid? I tried it and it is working.
Please re-open if you still encounter the problem.
