### ISSUE TITLE
timestamps aren't preserved when uploading

### ISSUE THREAD

**Issue by srkunze** [nextcloud/android#1433]
### Actual behaviour
sorting new to old does sort by uploaded-timestamp not by mtime of original picture

### Expected behaviour
same order as in folder from which the items where uploads, e.g. DCIM/Camera
 
### Steps to reproduce
1. sort by timestamp: new to old
2. upload all pictures from the DCIM/Camera to SofortUpload/Camera
3. order of pictures is inverse to order in DCIM/Camera

### Environment data
Android version: Android 7.1.1

Device model: OnePlus 5

Stock or customized system: Stock

Nextcloud app version: 2.0.0RC4

Nextcloud server version: 11.0.4

**Comment by AndyScherzinger** [comment]
:+1: what do you think @tobiasKaminsky @mario?

**Comment by srkunze** [comment]
@AndyScherzinger Do you have a place for me to look at for this particular problem? :)

**Comment by mario** [comment]
This should be fixed in master maybe, since now timestamps are proper? :P Can you try?

**Comment by srkunze** [comment]
@mario Oh, okay. Didn't see the pull request.
Already in RC in PlayStore? Or do I need to build it and somehow transfer it to my phone?

**Comment by mario** [comment]
https://github.com/nextcloud/android-library/pull/82 :)

It's part of Master of this repo. So either you build it via Android Studio or wait for next RC (hopefully tomorrow).

**Comment by srkunze** [comment]
Ah, a different repo. :) Cool, I wait until tomorrow and will then re-sync all my camera pictures.

Big thanks, @mario :+1: :+1: :+1:

**Comment by srkunze** [comment]
Check!

**Comment by mario** [comment]
Awesome ;)
