### ISSUE TITLE
system back button does not work in auto-upload settings

### ISSUE THREAD

**Issue by srkunze** [nextcloud/android#1434]
### Actual behaviour
pressing system's back button while having the auto-upload settings of a specific folder open, does nothing

### Expected behaviour
pressing system's back button closes the auto-upload settings of a specific folder
 
### Steps to reproduce
1. open settings for auto-upload
2. open settings modal for a specific application/folder such as WhatsApp Videos
3. press Android's back button

### Environment data
Android version: Android 7.1.1

Device model: OnePlus 5

Stock or customized system: Stock

Nextcloud app version: 2.0.0RC4

Nextcloud server version: 11.0.4

**Comment by AndyScherzinger** [comment]
Hi @srkunze, thanks for the report. Helps to improve the UX, fix is provided via #1438

**Comment by srkunze** [comment]
That was fast. :)

**Comment by AndyScherzinger** [comment]
@srkunze well, thanks! :) While it may still be a little bit more time until we will release 2.0.0 RC5 - still hunting down and fixing bugs

**Comment by srkunze** [comment]
@AndyScherzinger You're welcome. Got 3 more. :-)

**Comment by AndyScherzinger** [comment]
@srkunze I saw em. Not sure though if and when they would be done. ;)

**Comment by srkunze** [comment]
@AndyScherzinger Would pull requests be accepted?

**Comment by AndyScherzinger** [comment]
@srkunze in general yes while I'd recommend to wait until an issue has been flagged with "approved" which makes then sure that a PR for that issue would be merged. I am afk today/tomorrow most of the time, so I hope that @mario and @tobiasKaminsky can have a look at your proposals :)

**Comment by mario** [comment]
PR welcome @srkunze

**Comment by AndyScherzinger** [comment]
This issue is already fixed in a PR

**Comment by mario** [comment]
Yup was too late ;)
