### ISSUE TITLE
app lags under higher workload

### ISSUE THREAD

**Issue by srkunze** [nextcloud/android#1435]
### Actual behaviour
- when updating large folders (uploading 1000 pictures, deleted pictures on PC, so needs update on app), controls lag
- cannot go back in folder hierarchy, settings, etc.
- app sometimes shows black screen for a while

### Expected behaviour
- interaction with controls always possible
- changing folders, previews etc always possible
- no waiting when changing between views

### Steps to reproduce
1. open SofortUpload/Camera
2. choose to upload all pictures (1500) from the DCIM/Camera to SofortUpload/Camera
3. no interaction possible for a while

or

1. delete 1000 pictures from a nexcloud folder via PC
2. open app, let it sync this folder
3. no interaction possible for a while

### Environment data
Android version: Android 7.1.1

Device model: OnePlus 5

Stock or customized system: Stock

Nextcloud app version: 2.0.0RC4

Nextcloud server version: 11.0.4

**Comment by jasonbayton** [comment]
Can replicate this. It lags really badly on massive numbers of uploads. We could do with some form of rate-limitation in place to stop it from dragging the app to a crawl.

**Comment by srkunze** [comment]
@jasonbayton Don't know if this is something for Android background services or thread pooling.

**Comment by mario** [comment]
I'm not sure this is ONLY related to uploads.... There's no real ordering/prioritisation of network operations and that is indeed the problem....
