### ISSUE TITLE
Autoupload configuration: allow to upload all files in selected folder now

### ISSUE THREAD

**Issue by shtrom** [nextcloud/android#1444]
### Actual behaviour
- When configuring an auto-upload directory which already contains files, all those files need to be uploaded to the specified location manually

### Expected behaviour
- Adding some way (e.g., a button) in the auto-upload configuration page to process all existing files as if they had just appeared (i.e., auto-upload, or queue if network requirements are not satisfied, then copy/delete if appropriate)

**Comment by jasonbayton** [comment]
This is already on the roadmap, kind-of. So when we get full two-way sync capabilities we should be able to do this; I'd imagine the ability to do it one-way won't go away either. 

In the existing RC4 2.0 the app appears to scan the directory, which is half the work, forcing an upload of all shouldn't be too much additional work @tobiasKaminsky @AndyScherzinger @mario

**Comment by lucasmr** [comment]
Thought the app was not working because of this. Selected an existing folder with files and the auto-upload didn't send them.

**Comment by AndyScherzinger** [comment]
At this very moment the implementation only supports upload of files created after auto upload has been setup while as mentioned here we plan to extend this feature to also support the upload of already existing files.

**Comment by sduensin** [comment]
Would love to see this sooner than later.

**Comment by StopTrain** [comment]
Yep... would be nice to get this sooner than later as @sduensin states :)  Keep up the great work!

**Comment by joshtrichards** [comment]
Implemented in #4788
