### ISSUE TITLE
Autoupload moves/deletes files too early

### ISSUE THREAD

**Issue by shtrom** [nextcloud/android#1445]
### Actual behaviour
- Auto-upload, configured to move files to the app folder, sometimes deletes files taken by the camera app before the application that has triggered the intent got a chance to do something with them (e.g., share with contact).

### Expected behaviour
- Auto-upload is triggered after the intent-calling app is finished with the file. 
 
### Steps to reproduce
1. Use, e.g., https://github.com/siacs/conversations, choose `Attach file`/`Take picture`
2. Take a picture and accept; Conversations offers the file to the recipient
3. Meanwhile, Nextcloud starts auto-uploading the file
4. If the file has finished uploading before the contact has accepted the file, the file will get moved by Nextcloud, and the transfer in Conversations will fail, saying that the file is missing.

### Environment data
Android version: 7.1.2

Device model: Hammerhead

Stock or customized system: LineageOS

Nextcloud app version: 1.4.2

Nextcloud server version: 12.0.0 (but it's a client-side issue)

**Comment by jasonbayton** [comment]
@shtrom are you able to replicate this with the RC4 for 2.0?

**Comment by shtrom** [comment]
Hum, where can I get that from? Is there a binary APK I can grab?

**Comment by jasonbayton** [comment]
It's just been uploaded to fdroid, but otherwise it's in Google Play:

https://play.google.com/apps/testing/com.nextcloud.client

**Comment by shtrom** [comment]
On Fri 01 Sep 2017 at 06:47:34 +0000, Jason Bayton wrote:
> It's just been uploaded to fdroid, but otherwise it's in Google Play:

F-Droid will do just fine. Installing now.

-- 
Olivier Mehani <shtrom@ssji.net>
PGP fingerprint: 4435 CF6A 7C8D DD9B E2DE  F5F9 F012 A6E2 98C6 6655
Confidentiality cannot be guaranteed on emails sent or received unencrypted.

**Comment by OlivierS1** [comment]
I had a case on Dev when uploading to Wifi only was enabled and "Upload on charge only".
As soon as the phone was disconnected and wifi connection lost, then the file would have been deleted from the phone without having a chance to being uploaded.
I haven't checked on RC as it conflict with my Dev version.

**Comment by shtrom** [comment]
Yup, still happens on RC5.

**Comment by jasonbayton** [comment]
@mario @AndyScherzinger @tobiasKaminsky 

Pretty bad bug..

**Comment by khartahk** [comment]
I don't know if this is the same issue but for me this happens:
1. Set move to program folder
2. take a picture
3. I need to enable advanced options and do a refresh to find new images
4. go into all files and find the folder where the image is uploaded
5. see the green checkmark for a second and the it disappears
6. need to re-download the file

**Comment by tobiasKaminsky** [comment]
Meanwhile we enhanced the app. Can you please try and report back if the bug still exists on latest official version in conjuction with latest server or even try our [dev version](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#dev-release)?

**Comment by shtrom** [comment]
It doesn't seem to happen anymore with 3.3.0 from F-Droid :+1:
