### ISSUE TITLE
Upload -> no possibility to go back

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#145]
When I select "Uploads" in main menu, tapping on "All files" or "Uploads" doesn't do anything.
Other than that, switching between the two works ok.

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger this is yours ;)

**Comment by AndyScherzinger** [comment]
I'll have a look. 

Big Thank you for reporting this!!! Sorry for any inconvenience caused!

**Comment by AndyScherzinger** [comment]
Any info on device and Android version?

**Comment by tobiasKaminsky** [comment]
I have reproduced it with an emulator and android 6.

**Comment by michalmiddleton** [comment]
There issue was on Android 6.0.1 on Nexus 6p. Sorry for not being specific..

**Comment by AndyScherzinger** [comment]
No worries @michalmiddleton, This is going to be fixed in the next release candidate :+1:

**Comment by tobiasKaminsky** [comment]
This is now in RC2, available soon.
