### ISSUE TITLE
android app 2.0.0.RC4 shows incorrect word for Shared for Dutch language

### ISSUE THREAD

**Issue by JK74** [nextcloud/android#1451]
Android APP 2.0.0RC4 it shows at the 3 horizontal bars for 'shared' icon  for dutch language 'Gedeel' where it should be 'Gedeeld'

I did lookup on transifex shared for android but it was showing already as ' Gedeeld' so it was or was not known already ? please clarify.

**Comment by mario** [comment]
o.O Screenshot?

**Comment by JK74** [comment]
![image](https://user-images.githubusercontent.com/17946255/29770848-33623222-8bf1-11e7-98d3-2811d2abc3c0.png)

**Comment by tobiasKaminsky** [comment]
The strings is transifex were updated, but not merged into master.
This is now fixed and so the updated dutch strings should be available in next RC.
