### ISSUE TITLE
Resume uploading: what if file is modified inbetween

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#1454]
This came up during conf and should be investigated:
- upload a file with chunking
- interrupt upload
- modify file
- "resume" upload

-> will it be a resume (appending only the newest chunks) or will it begin new (as the filesum changed)

**Comment by AndyScherzinger** [comment]
I'd say it would need to completely restart the upload of the file since it's very likely that the file is corrupt if it is just resumed.

**Comment by mario** [comment]
Need to look into it as the resume mechanism hasn't really changed...

**Comment by jasonbayton** [comment]
Not sure there's too much to discuss, it's safest if it just restarts should it detect a discrepancy between the file when starting and the file when restarting. Make that happen 👍
