### ISSUE TITLE
More developers

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#147]
Do you have any idea how to get more (community) developer to support us in enhancing the app?
Posting on help.nextcloud.org is maybe not the ideal way as there are many end users...?

**Comment by AndyScherzinger** [comment]
I don't unfortunately...but yeas, having more Android developers would help quite a lot since most changes are done by 3 people which only gives us a certain speed where I think we could be _even_ faster than we are today with more people.

cc @jospoortvliet Any idea or channels at hand to attract more Android developers. Looking at the app store people seem to love what we do here but it is still kind of the 3 of us pushing things for the app. :(

**Comment by Icantcodeatall** [comment]
You should tell people you are looking for developers, for example on the playstore or on twitter.
I'm sure people are willing to help but are not aware of what you need and what they can do, I may not be the smartest person on earth but I just figured out today that I could help with testing RCs...

**Comment by tobiasKaminsky** [comment]
This is a draft which may be included in the navigation drawer as "Participate":
https://github.com/nextcloud/android/issues/139#issuecomment-236367059

But yes, writing on play store and twitter is the more direct way.
@jospoortvliet @jancborchardt

**Comment by Bugsbane** [comment]
Well, where do android developers hang out? XDA-Dev foums? First rule of marketing is to go to where your potential audience is... I'm in marketing, not Android dev, so I'm not in a good place to answer this, but someone here (or on the forums) should be....

**Comment by mario** [comment]
Issue solved xD

**Comment by Bugsbane** [comment]
> Issue solved xD

So... We have all the contributors we could ever want to the Android app then?

**Comment by mario** [comment]
Of course not, we always welcome and invite new contributors :)

**Comment by tobiasKaminsky** [comment]
We also plan to participate on Google Summer of Code, but yes there are still some ideas in this issue that are not done. 
But as this is a long-torm "issue" / plan I think we can keep it in mind, but leave this one closed.
Of cource @Bugsbane if you have a great idea, please tell us 👍

**Comment by strugee** [comment]
@tobiasKaminsky congrats on GSoC! That should be a great help; I'm glad this app is in such good hands 🎉

**Comment by Bugsbane** [comment]
> Of cource @Bugsbane if you have a great idea, please tell us 👍

No disrespect meant. Just poking a little fun. My background is in marketing though, so I'd be happy to chat about some ideas, if you like. In general though, the pattern is to figure out who you're after (presumably Android devs interested in open source?), where they're hanging out  (XDA devs? Linux action show? Hacker News? You guys are more the experts here), what they care about and how they would most benefit from hacking on this (feeling like they're contributing to something worthwhile? Resume development? Improving skills?) and present them an engaging message in those places showing how they'll experience those benefits by contributing (giving examples like personal experience++). Figuring out *what* your message is and to whom is really important, and goes well beyond what many devs usually seem to want to do (ie just link to the issue tracker)

**Comment by jancborchardt** [comment]
@Bugsbane good points! Do you have ideas how to improve the "Participate" screen in the app? :)
