### ISSUE TITLE
Themeing NOT apllied

### ISSUE THREAD

**Issue by hitam4450** [nextcloud/android#1471]
Hi to all,

currently I do run 2 NC instances: one on a local server one on the web. (both version12.0.29). As client I use version 1.4.3 on ANDROID 6.0.1.

I do run two different themes in the server instances: one blue and one red and changed the names from Standard "Nexctcloud" to "Blue " and "Red".

The client does **NOT** show the different themes and also **NOT** the different titles on each server 
 It only shows the standard blue color with the standard title NextCloud!

regards, hitam4450

reference: https://github.com/nextcloud/android/pull/1031

**Comment by AndyScherzinger** [comment]
@hitam4450 you need to run the 2.0.0 release candidates 😺 or wait for the stable/final release of it. 1.4.3 does *NOT* support theming.

**Comment by hitam4450** [comment]
@AndyScherzinger  Thanks for your feedback ! I'll wait until the final Version 2.0 is available!
