### ISSUE TITLE
 No files visible on Tablet and Smartphone APP 

### ISSUE THREAD

**Issue by rkoehler2017** [nextcloud/android#1479]
Installed latest stable 10.2 and the APP 1.4.3 on my Samsung p600 Tablet, my Honor 9 and my Huawai Mate 9 Smartphone. Android V 7.x.x
If starting Nextcloud APP - loading - appears and then - no files available- Keine Dateien vorhanden in german.
Also not possible to upload or create folder
No Problem if trying with webdav.

**Comment by AndyScherzinger** [comment]
Hi @rkoehler2017,

thnaks for moving your issue from the forum over here. @mario @tobiasKaminsky any ideas? :)

**Comment by mario** [comment]
Ssl cipher?

**Comment by rkoehler2017** [comment]
If installed now a SSL Certificate on my Server
Configured the APP for the new connection
![grafik](https://user-images.githubusercontent.com/31540737/29993554-b44406be-8fba-11e7-9d7d-5fd2daf516dd.png)
Same Prob, no files

Something to configure on the Server?

**Comment by xXSTrikeXx** [comment]
Hi @rkoehler2017,

do the latest version solves your problem?

**Comment by AndyScherzinger** [comment]
@rkoehler2017 Looking at the server screenshot you posted something seems really wrong there, looking at the fact that it mentiones //sedoparking.com/frmpark ?! Also tested the URL you mentioned in the screenshot above and that instance is now in maintenance mode, so the app can't connect for as long as the server is in that mode.

**Comment by rkoehler2017** [comment]
yes, i saw it, no idea where the sedo came from, but it's my homepage at 1und1 https://ralfkoehler.net/cloud, and yes after the crash it is in maintanance mode, forever IMO.
I think i'll delete all the the nextcloud stuff and start over

**Comment by xXSTrikeXx** [comment]
go to /nextcloud/config/config.php and set there the maintenance mode off. It might help you to login and maybe do an update.

**Comment by AndyScherzinger** [comment]
@rkoehler2017 sounds good, one thing I understood from @mario is that there might be an issue with subfolder installations and client logins while this needs to be fixed on the server side. I also run mine at 1und1 using a subdomain which works great.

**Comment by tobiasKaminsky** [comment]
I am using (on my test instances) lots of server with subfolder installation and did not have any problems.

@rkoehler2017 is this still valid?

**Comment by rkoehler2017** [comment]
I have problem to shutdown nextcloud on my 1and1 webspace.

If I’ve solved this I’ll reinstall everything.

 

So you can close this

 

Regards

ralf

 

Von: Tobias Kaminsky [mailto:notifications@github.com] 
Gesendet: Mittwoch, 3. Januar 2018 14:22
An: nextcloud/android <android@noreply.github.com>
Cc: rkoehler2017 <2017@ralfkoehler.net>; Mention <mention@noreply.github.com>
Betreff: Re: [nextcloud/android] No files visible on Tablet and Smartphone APP (#1479)

 

I am using (on my test instances) lots of server with subfolder installation and did not have any problems.

@rkoehler2017 <https://github.com/rkoehler2017>  is this still valid?

**Comment by tobiasKaminsky** [comment]
Thank you for your reply.
If you need additional help, I am sure you can find them at http://help.nextcloud.com/
And of course you can re-open this issue if the same problem occurs again.
