### ISSUE TITLE
Integration with office apps

### ISSUE THREAD

**Issue by memen45** [nextcloud/android#1481]
### Actual behaviour
Office files are opened in read-only mode by the official Microsoft Office Android apps (Excel etc.)

### Expected behaviour
Office files are opened in read/write mode with the possibility to save changes directly to the server again
 
### Steps to reproduce
1. In any of the MS Office android apps choose 'Open' and then 'Other Cloud Storage'. 
2. From there select Nextcloud and then browse to any office file in your nextcloud account.
3. Now the file is being downloaded and opens in the Office app - in Read-Only mode.

### Environment data
Android version: 6.0

Device model: H60-L04

Stock or customized system: EMUI 4.0

Nextcloud app version: 1.4.3

Nextcloud server version:12.02

I am not sure whether this is a server issue or an issue in the nextcloud app. The latter could be because the app is first downloading the file instead of providing the office app with a 'cloud version' of the file (i.e. webdav link or something).

**Comment by memen45** [comment]
After searching a little more for a possible cause I suspect it has to do with the webdav server. Since the webdav server used by nextcloud does not support locking of files, it will open in read-only mode. Can someone endorse this? Because in that case I should probably post this to the nextcloud/server git instead of this one. Thanks in advance

**Comment by jasonbayton** [comment]
Can't state with authority, but I'd propose opening it on nc/server too just in case.

**Comment by AndyScherzinger** [comment]
The issue with the Android client is that the app ships with a document provider which only implements ```read``` at the moment which is why it is opened as "read-only".
So the document provider would need to be extended to also support the write operation and then this should be possible.

**Comment by jasonbayton** [comment]
@AndyScherzinger 2.1? 👍 😆

**Comment by AndyScherzinger** [comment]
@jasonbayton rather not 😆 while this needs to handle some more infos... because we wouldn't get a signal when the file has been written, so no auto-magic uploads...

**Comment by memen45** [comment]
You mean that modifications to the files would be directly uploaded to the server instead of through the nextcloud app?

**Comment by AndyScherzinger** [comment]
no, I mean they wouldn't be uploaded since the app might not "know" of the changed file. It would simply be saved on the device by the other app but the Nextcloud app might not be aware of the file been written and thus wouldn't do anything.
This is jsut a "maybe" since we have no experience with writing files via the so called document provider.

**Comment by memen45** [comment]
Ah okay, a little more complicated than it seems. If the document provider would use a uri instead of the local file (that was downloaded just after picking it) then saving back would save it directly to the uri - i.e. the server.
Another less smooth solution: if the folder syncing feature will be implemented in the app, you could sync the folder with the document and then just -open the local file, -save to local file -nextcloud detects change in the folder and uploads change, right?

First would be nicer of course, since local storage is often limited.

**Comment by AndyScherzinger** [comment]
> If the document provider would use a uri instead of the local file (that was downloaded just after picking it) then saving back would save it directly to the uri - i.e. the server(?).

No since it retrieval always goes through the Nextcloud Android app's document provider.

> Another less smooth solution: if the folder syncing feature will be implemented in the app, you could sync the folder containing the document and then just -open the local file, -save to local file -nextcloud detects change in the folder and uploads change, right?

correct,yes

**Comment by mario** [comment]
Should be fixed via https://github.com/nextcloud/android/pull/1651, however no direct saving to server.

**Comment by tobiasKaminsky** [comment]
#1651 is merged, closing.
