### ISSUE TITLE
DJVU files are not handled correctly

### ISSUE THREAD

**Issue by exit91** [nextcloud/android#149]
### Actual behaviour
- NextCloud considers djvu files to be images, that is, if I click on one, NextCloud tries to show a preview (and fails to display it -- but that is another matter).

### Expected behaviour
- When clicking on a djvu file, nextcloud should provide me with a list of apps which can open this file.

### Environment data
Android version: 5.0

Device model: Samsung Galaxy Note 3

Stock or customized system: afaik stock

Nextcloud app version: 1.1.0

PR: #153 
Nextcloud server version: 8.2

**Comment by AndyScherzinger** [comment]
Hi @exit91 thanks for reporting this issue.
Can you provide us a sample djvu file and name an app that would be able to open such a file? That would help us to fix this quicker :)

**Comment by tobiasKaminsky** [comment]
PR: #153

**Comment by exit91** [comment]
I am using "Document Viewer" (fork of EBookDroid) as DjVu viewer
(see [Google Play](https://play.google.com/store/apps/details?id=org.sufficientlysecure.viewer)
or [F-Droid](https://f-droid.org/repository/browse/?fdfilter=document+viewer&fdid=org.sufficientlysecure.viewer))

As for an example file, take the [DjVu3 reference](http://djvu.org/docs/DjVu3Spec.djvu).

**Comment by AndyScherzinger** [comment]
> I am using "Document Viewer" (fork of EBookDroid) as DjVu viewer
(see https://play.google.com/store/apps/details?id=org.sufficientlysecure.viewer
or https://f-droid.org/repository/browse/?fdfilter=document+viewer&fdid=org.sufficientlysecure.viewer)

> As for an example file, take the DjVu3 reference http://djvu.org/docs/DjVu3Spec.djvu

**Comment by tobiasKaminsky** [comment]
I have tested it. 
The djvu file is now downloaded instead of treated as image and the ebook reader is part of the suggested apps (along with image apps)

**Comment by AndyScherzinger** [comment]
Awesome :+1:

**Comment by AndyScherzinger** [comment]
will be released with 1.3.0
