### ISSUE TITLE
Cannot connect via app over LAN

### ISSUE THREAD

**Issue by NathanRVance** [nextcloud/android#1494]
### Actual behaviour
The android app cannot connect to a Nextcloud server over LAN, but it can connect to the same server from outside the local network. There is no issue in connecting via a web browser, local or not, even on android.

### Expected behaviour
The app shouldn't have a problem connecting if a web browser has no problem connecting.
 
### Steps to reproduce
1. Install Nextcloud on a server and connect to a router.
2. Install the Nextcloud app on an android phone and connect to the same router. The app can't reach the server.
3. Navigate to the same url that the app uses, but in a web browser on android (Chrome). Connecting works smoothly, and files are accessible.

### Environment data
Android version: 7.1.1

Device model: Oneplus 3

Stock or customized system: Stock

Nextcloud app version: Bug exists both in 1.4.3 and Beta 2.0.0RC5

Nextcloud server version: 12.0.2

#### Web server error log
Nothing on topic. The client here, 192.168.1.69, is my laptop. The access.log is full of my laptop polling the server every 30 seconds.
```
2017/09/05 07:42:49 [error] 24939#24939: *3832 access forbidden by rule, client: 192.168.1.69, server: www.vance.homelinuxserver.org, request: "GET /nextcloud/data/.ocdata?t=1504611769602 HTTP/1.1", host: "vance.homelinuxserver.org"
```

#### Nextcloud log (data/nextcloud.log)
The latest server log was from 2 days ago and involved connecting via the app from outside LAN. Or it might have been Chrome on android... I really can't remember.
```
{"reqId":"GYkOVQy20JakiTi8ogYG","level":3,"time":"2017-09-02T15:03:10+00:00","remoteAddr":"107.4.53.178","user":"--","app":"PHP","method":"GET","url":"\/nextcloud\/index.php\/login\/flow","message":"Undefined index: oauthState at \/var\/www\/nextcloud\/core\/templates\/loginflow\/authpicker.php#38","userAgent":"Oneplus ONEPLUS A3000","version":"12.0.2.0"}
```

**Comment by NathanRVance** [comment]
Turns out, it was an issue with IPv6. As soon as I disabled IPv6 on my router, I could connect.
That being said, is there any reason why the app can't try connecting over both IPv6 and IPv4, and use whichever one connects successfully?

**Comment by mario** [comment]
The app does not support IPv6 yet.

**Comment by AndyScherzinger** [comment]
The reason is that the library we use for the webdav communication supports ipv4 only and that there is no Android compatible implementation yet that supports ipv6 :(

**Comment by NathanRVance** [comment]
Ah, so this is a known issue. I'll close it then. Thanks!

**Comment by olehj** [comment]
Ah f! Is this still valid? I had so much trouble with this the last year and scratched off my head trying to fix this issue.

Wish this would be displayed somewhere. Anyway fixed it by overriding local DNS to use only IPv4 locally.
