### ISSUE TITLE
No account sync

### ISSUE THREAD

**Issue by mase76** [nextcloud/android#1495]
Hi!
I have installed version 2.0.0rc5 of the client. As before, there is no automatic account sync of my
files. I did not set up an automatic upload in the app, I only want to have my files synced. I marked
them to be available offline. I have to trigger the sync manually.
Maybe you could add a sync interval like Nextcloud newsreader or Davdroid has.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky @mario any idea? Imho the client does have a sync intervall and should sync the files back and forth, no?

**Comment by mase76** [comment]
I think, a direct sync when local and marked as offline files change, and a custom sync interval would be fine. The same behaviour than davdroid. At least a sync interval.

**Comment by mario** [comment]
@AndyScherzinger didn't look into this part of code, but uses service to sync files which I assume isn't always alive. Like I said, all this needs to be moved into a sync adapter and then it'll work.

**Comment by mase76** [comment]
I disabled the battery optimation for the nc client. But there is still no account sync.
I think, the behaviour should be equal to the news reader android app.

**Comment by mario** [comment]
There's no sync setup in the client I'm afraid (if I understand the code correctly). Luckily, this is easy to fix and will be done.

**Comment by mase76** [comment]
Yes, there is no sync setup. I can only activate filesync in the android account settings. But it seems,
that it has no effect at all.

**Comment by tobiasKaminsky** [comment]
There is a sync system, https://github.com/nextcloud/android/blob/28a19bb004a5000572a0f58805b74985a28a5db7/src/main/java/com/owncloud/android/syncadapter/FileSyncAdapter.java#L141-L141

It is set to only once an hour (L156).
But like Mario said, we need to test if this works with android 6+

**Comment by mase76** [comment]
I am on 7.1.2. Let me know, if there is something to test. But I am without gapps. I use the
f-droid build.

**Comment by mase76** [comment]
Any news? Without  an account sync, there is only an automatic one-way-sync. We don't get file changes from the server until triggered manually.

**Comment by AndyScherzinger** [comment]
@mase76 does this still happen for 3.0.0? Just asking since @mario added some fixes/magic for available offline files to be kept in sync and also checking for a new version of a file before opening it on the client.

**Comment by mase76** [comment]
I am on 3.0.0 (from F-droid) since today. I had the RC before. I thought, the file monitor would do the trick. But except of the notification about the running monitor, there is no difference visible. Checking Android's account menu, there was no Nextcloud sync for several days, so I always trigger it from there. I am opening the Nextcloud app itself only when adding new files. That isn't that often.
Why not syncing like Davdroid? It is doing it's sync reliable as expected. Never had problems
with it.

**Comment by tobiasKaminsky** [comment]
I tried the following:
- enable account sync
- set date.txt as "keep offline"
- on desktop: change content of date.txt hourly
- directly open date.txt without opening nc app (file browser -> open file)
- as of now (10:23) I had the content "9am" in it. So it synced. (as we only sync once per hour, this still okay, as e.g. the next sync start at 10:39)

I can also see this as preferences -> accounts -> nextcloud -> last sync: 09:39

**Comment by mase76** [comment]
I don't see a sync in the account settings for several days. I sync manually from time to time. There is only an automatic sync, when a file changed locally.
I am on Omnirom 8.1.0 and the stable client from F-droid. No Gapps.
