### ISSUE TITLE
Login issue - 2.0.0 -  web login check issue

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#1496]
URL for reproducing the behavior: https://nextcloud.innovazionedigitale.it

Screenshot:
![ac047b9a172175059fbca652c038d7c306e9f501](https://user-images.githubusercontent.com/1315170/30064855-4d4764e2-9253-11e7-8413-45718a6a408d.JPG)

App's log:
```
09-05 15:57:03.780 5788-5788/com.nextcloud.client D/OperationsService: Starting command with id 1
09-05 15:57:03.781 5788-6072/com.nextcloud.client D/SimpleFactoryManager: getClientFor(OwnCloudAccount ... : 
09-05 15:57:03.781 5788-6072/com.nextcloud.client D/OwnCloudClient #2: Creating OwnCloudClient
09-05 15:57:03.782 5788-6072/com.nextcloud.client V/SimpleFactoryManager:     new client {@nextcloud.innovazionedigitale.it, 249092806}
09-05 15:57:03.788 5788-6072/com.nextcloud.client D/OwnCloudClient #2: REQUEST GET /status.php
09-05 15:57:03.789 5788-6072/com.nextcloud.client D/AdvancedSslSocketFactory: Creating SSL Socket with remote nextcloud.innovazionedigitale.it:443, local null:0, params: org.apache.commons.httpclient.params.HttpConnectionParams@bb4edb4
09-05 15:57:03.789 5788-6072/com.nextcloud.client D/AdvancedSslSocketFactory:  ... with connection timeout 50000 and socket timeout 50000
09-05 15:57:03.876 5788-6072/com.nextcloud.client I/ServerNameIndicator: SSLSocket implementation: com.android.org.conscrypt.OpenSSLSocketImpl
09-05 15:57:03.876 5788-6072/com.nextcloud.client I/ServerNameIndicator: SNI done, hostname: nextcloud.innovazionedigitale.it
09-05 15:57:04.173 5788-6072/com.nextcloud.client I/GetRemoteStatusOperation: Connection check at https://nextcloud.innovazionedigitale.it: Operation finished with HTTP status code -1 (success)
09-05 15:57:04.173 5788-6072/com.nextcloud.client D/GetServerInfoOperation: Trying empty authorization to detect authentication method
09-05 15:57:04.179 5788-6072/com.nextcloud.client D/OwnCloudClient #2: REQUEST HEAD /remote.php/webdav/
09-05 15:57:04.279 5788-6072/com.nextcloud.client D/ExistenceCheckRemoteOperation: Existence check for https://nextcloud.innovazionedigitale.it/remote.php/webdav/ targeting for  existence finished with HTTP status 401(FAIL)
09-05 15:57:04.282 5788-6072/com.nextcloud.client D/DetectAuthenticationMethodOperation: Authentication method found: UNKNOWN
```

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky would you mind having a look at this. Somehow the result is ```Authentication method found: UNKNOWN``` and the fallback simply doesn't show the username/password. 

I could reproduce this (app log from my phone reproducing this issue) with the latest master, so this issue is present on the latest code base.

**Comment by tobiasKaminsky** [comment]
Accessing https://nextcloud.innovazionedigitale.it/remote.php/webdav/ should give
"This is the WebDAV interface. It can only be accessed by WebDAV clients such as the Nextcloud desktop sync client.", but we get "401 Unauthorized".

--> at least in this current state I assume a server misconfiguration.

**Comment by AndyScherzinger** [comment]
Can you reply here: https://help.nextcloud.com/t/nextcloud-androi-app-login-failed/19005
According to the report iOS and web do work :/

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky still, looking at the screenshot, at least the error message is quite misleading since it says username/password wrong while you never entered any of these...

**Comment by tobiasKaminsky** [comment]
On 1.4.3 the error message is "could not find host".
I'll postpone this to 2.0.1 as it is in first instance a problem with the server (at least for android and its workflow).

**Comment by Innovazionedigitale** [comment]
Hi @tobiasKaminsky ,
Thank you for your answer, can i ask if you have an idea of the approximate period when the 2.0.1 version will be released?
Thank you so much.

**Comment by tobiasKaminsky** [comment]
@Innovazionedigitale could you fixed your server meanwhile?

**Comment by tobiasKaminsky** [comment]
No response within the last month, therefore closing.
Please feel free to reopen with additional infos, if the problem still exists.
