### ISSUE TITLE
Two character password in Google Play screenshot

### ISSUE THREAD

**Issue by mabkenar** [nextcloud/android#15]
### Actual behaviour
- In Google Play, the first screenshot of Nextcloud client shows a user 'hans' with a password of only two characters, as represented by '••'.

### Expected behaviour
- Nextcloud should never encourage users to set short passwords for their accounts, even implicitly. I suggest the example password in the screenshot to be at least 10 characters, like '••••••••••' or longer.  
 
### Steps to reproduce
1. Go to Google Play page for Nextcloud client, here: https://play.google.com/store/apps/details?id=com.nextcloud.client
2. Click on the first screenshot of the app, this one: https://goo.gl/LW70E4
3. Look at the password field in the screenshot, it is '••'.

### Environment data
Nextcloud app version:
1.0.0

**Comment by AndyScherzinger** [comment]
Thanks for reporting this and yes we do not want to encourage user to use such short passwords. New screenshots has been uploaded, waiting for the caches to refresh. See also https://github.com/nextcloud/screenshots/pull/7
