### ISSUE TITLE
Using Arbitrary Data Provider for Layout and Sort Order

### ISSUE THREAD

**Issue by srkunze** [nextcloud/android#1508]
Based on #1484

########

> How do you clean up preference entries once say a folder dissappears?:)

Well, first of all, I would evaluate if that's really an issue.
If it's really an issue, I then would ask the person who wrote isGridViewPreferred, what his evaluation was, and how he intended to solve it if at all. :)

If I had to solve it, I tend to use a database having foreign keys and constraints available. So, in case a folder gets removed, we only need to remove all sort-entries for all users of that particular folder.
Folder ids also have the benefit of being path-unrelated. So, less hassle for a user, if he moves some dirs.

My preliminary evaluation tends to "it's not an issue". I cannot imagine that those few bytes are a problem at all. Take this with a grain of salt, as I am new to the project, I might mis-estimate here.

########

Talking practically, it might not be an issue. Talking good design, it is an issue.

As for Arbitrary Data ... yes, it was one of the ideas behind it. You'd basically have "sort_13245" (as an example, where 13245 is folder ID) as a key, and value as the actual sort preference.

I would not mind moving layout preferences to Arbitrary Data as well ... "layout_12345" and then "grid"/"list" as value. Wishful thinking? :)

@mario  @tobiasKaminsky

**Comment by srkunze** [comment]
I have some head ache when we define our own mini-serialization-language with "sort_12345" or "layout_12345".

If you insist on it, I will implement it this way, but it doesn't strike me as overall good design from my perspective.

I am no expert in Android background jobs. How would the Nextcloud/Android-way of cleaning up deleted folders look like? Is there some kind of cron? :)

The algorithm, I would have chosen, would iterate over all keys in the two preference files (one for sort and one for isGrid) and check if the folder still exists. If not, delete it from the file.

**Comment by srkunze** [comment]
@mario Regarding a new "layout" preference, I even had it implemented for a short period of time but removed it as the existing changes were big enough already. Though, I am also for changing that part to an more extensible one (so people can easily add more layouts besides "list" and "grid", e.g. "book-like" or something).

**Comment by srkunze** [comment]
One thought about the mini-serialization: how is the data stored internally? If it's stored in a database, couldn't we simply add a folder-based setting table having the same columns as arbitrary data provider but with an additional folder column?

This way, removing a folder would require removing all foreign keys such as the one from the above-mentioned settings table. So, no background job needed.

How's that sound?

**Comment by mario** [comment]
It's indeed stored in the database. We could, but do you think it has a SIGNIFICANT benefit over storing it in the arbitrary data table? It was created exactly for this kind of random things.
(We always remove things in a background job btw, see: 

https://github.com/nextcloud/android/pull/1547 and AccountRemovalJob.java ;)

**Comment by srkunze** [comment]
Coming from a relational database background, I usually tend towards the eager cleanup solution (if the database itself cleans up eagerly or lazily, I mostly don't know/care). Foreign keys + ondelete-cascade is the established solution for this; also performance-wise.

Anyway, if you say this is the way to go, let's do it although I don't see a SIGNIFICANT benefit over using the regular Android shared preference which btw. the nextcloud client uses a lot already. Will do tomorrow. :)

**Comment by srkunze** [comment]
@mario I think I need some help with this.

1) Where should the code live? PreferenceManager?
2) ArbitraryDataProvider doesn't support Booleans.
3) Where do I get the account? I only have the context.

![image](https://user-images.githubusercontent.com/1389648/30606240-4f917304-9d71-11e7-9b21-91bbbc9a1e0a.png)

**Comment by mario** [comment]
1) Or new UserPreferencesHelper? Pick what you like best :)
2) Sure it does? Just store "true" or "false" as values? You can later parse that as "Boolean.parseBoolean(string);" if you need to.
3) AccountUtils has the following helper method:
getCurrentOwnCloudAccount(Context context)

Hope I've helped? :)

**Comment by srkunze** [comment]
@mario Alright. Sounds good. :) That'll do it.

Last time, I waited for some sort of approval. Would be great to have it here as well. :)

**Comment by mario** [comment]
You're all approved :P

**Comment by srkunze** [comment]
I see. :)

**Comment by AndyScherzinger** [comment]
Labeled and assigned to you,so other don't pick it up by mistake :)

Happy to have you working on this @srkunze 🚀

**Comment by srkunze** [comment]
@AndyScherzinger Thanks.

Done.
