### ISSUE TITLE
Move FAB button to extended toolbar for tablet layouts

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#1509]
### Actual behaviour
-For tablet layouts the fab is bound to the left pane which is the files listing
![fileizxw8d](https://cloud.githubusercontent.com/assets/5836855/25553543/60dd71fc-2cb6-11e7-825b-e7f58a43022e.png)

### Expected behaviour
-Fab should be bound to an extended toolbar as described in material design guidelines https://material.io/guidelines/components/buttons-floating-action-button.html#buttons-floating-action-button-transitions and https://material.io/guidelines/layout/responsive-ui.html#responsive-ui-patterns and discussed with @jancborchardt https://github.com/nextcloud/android/issues/1501#issuecomment-327804769
This also solves the issue reported in #1501 and some parts of #912 :
![patterns_actions_fab_placement7](https://user-images.githubusercontent.com/1315170/30166796-b4a59d10-93e4-11e7-8b93-cb2c0efc5c00.png)
The image from the guideline is just to give you an idea about the FAB position, please ignore anything else since that layout also uses some other UI elements we don't!

**Comment by artem-p** [comment]
Seems that some refactoring needed to achieve this fab position. Usually, it is easy to bind fab to a toolbar, with `app:layout_anchor` property, but fab and toolbar should be under the hood of a single CoordinatorLayout. For now FAB is in CoordinatorLayout in the fragment, but toolbar is on the upper level in the activity and not in CoordinatorLayout. Also, FAB is heavily used in the fragment code, so it cannot be just moved to another xml layout.

**Comment by artem-p** [comment]
Also, FAB position changes programmatically when bottom navigation is enabled that also seems a bad practice.

**Comment by ANUKULJHA1506** [comment]
can u assign me this issue

**Comment by Tiam-Abderezai** [comment]
@AndyScherzinger tested on **Pixel C API 30** emulator:

![image](https://user-images.githubusercontent.com/6480849/174213244-c43fc279-88ce-4cf2-9514-0ad657591f58.png)

Looks like it's showing the FAB in the correct position. Is the issue resolved? Would love to contribute. Please let me know your thoughts.

**Comment by AlvaroBrey** [comment]
Yeah, this is solved as we've removed the split-pane layout for tablets.
