### ISSUE TITLE
no autoupload on 2.0.0RC5?

### ISSUE THREAD

**Issue by baustromverteiler** [nextcloud/android#1510]
### Actual behaviour
Installed the beta from google play because I was having issues with the gallery / picture preview feature from the release (wasn't working), autoupload was working. manual upload via 'share' feature of gallery app works without problems

### Expected behaviour
Newly taken pictures should be automatically uploaded to my nextcloud
 
### Steps to reproduce
1. Configure Autoupload
2. Take picture
3. nothing gets uploaded

### Environment data
Android version: 6.0.1 

Device model: Xiaomi MI4c

Stock or customized system: custom MOKEE Rom, based on cyanogen mod

Nextcloud app version: 2.0.0RC5

Nextcloud server version: 12.0.2

#### Web server error log
```
no erros show up when nothing gets uploaded
```

#### Nextcloud log (data/nextcloud.log)
```
No log gets created from the app
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by mario** [comment]
Strange. Logs?

**Comment by pztrn** [comment]
Same here. Absolutely nothing in logcat output.

But I can launch autoupload manually and it will work only once, I have to launch this process manually.

I'm on 2.0.0RC6 from fdroid with nextcloud 11.0.5.

**Comment by mario** [comment]
@pztrn xiaomi too?

**Comment by pztrn** [comment]
No, Meizu m3 note with latest flyme 6 global (android 5.1).

**Comment by mario** [comment]
Have no way to test on these devices I'm afraid :(

**Comment by mario** [comment]
RC9 folks? :)

**Comment by AndyScherzinger** [comment]
2.0.1? ;)

**Comment by mario** [comment]
There won't be 2.0.1 :P

**Comment by mario** [comment]
I now this is a device-specific issue. You need to ignore battery optimizations on certain phones in order for this to work. So closing.
