### ISSUE TITLE
Footer text wrong in languages with multiple plurals

### ISSUE THREAD

**Issue by stalker314314** [nextcloud/android#1513]
### Actual behaviour
OCFileListFragment.generateFooterText doesn't honor languages with multiple plurals. In those languages, translations are limited (and wrong). For example, "file_list__footer__files" is not plural resource and as such, will not make sense in those languages

### Expected behaviour
Use plural resource to show files and folders in footer. Ideally, logic of this method could be simplified greatly.
 
### Steps to reproduce
1. Change language of phone to language with multiple plurals (Serbian is example I know)
2. Notice that generated translations are nonsensical and weird

### Environment data
Android version:
Dev

**Comment by AndyScherzinger** [comment]
Thanks for your report. 

This issue is due to the fact that we reimplemented the footer texts but don't yet have it merged to master, so this will be auto fixed as soon as it gets merged to master and people translate it on Transifex respecting the multiple plurals.

**Comment by stalker314314** [comment]
Interestingly enough, only reason I created task is to create PR. At least now I know now that:

- [my solution](https://github.com/stalker314314/android/commit/a29fa8a6362f3dc26f3a78b40a77d587b37e885c) is almost the same as [existing solution](https://github.com/nextcloud/android/commit/25c4ce2e57523d75aa91835845349d3677f2f770)
- There _is_ solution already:) Better luck next time for me, lesson learned to research a bit before doing anything:)

Maybe issue can be closed, I will leave this to you

**Comment by AndyScherzinger** [comment]
I'd leave it open until the PR will be merged to master.

Sorry for the trouble :/ Did the change just yesterday...
We'd be happy to have you on board and can help with any task you would like to pick up :+1:
Best approach from my experience is to either create an issue for discussion first or pick an issue which is labeled "approved" but not yet assigned to anyone or labeled "prior exists". We also have starter issues,not that many at the moment but @tobiasKaminsky, @mario and I are here to help in any way we can!

**Comment by AndyScherzinger** [comment]
fixed via #1503
