### ISSUE TITLE
Battery drain

### ISSUE THREAD

**Issue by jsargent7089** [nextcloud/android#1514]
### Actual behaviour
-Tell us what happens
It never stop uploading the same photo
### Expected behaviour
-Tell us what should happen
upload the  the photo once
### Steps to reproduce
1. Use autophoto upload
2. Never stops upload the same photo

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:12.02

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by mario** [comment]
What app version?

**Comment by tobiasKaminsky** [comment]
@jsargent7089 which app version do you use?

**Comment by jsargent7089** [comment]
2.0.0RC9

**Comment by jsargent7089** [comment]
There no error log in the nextcloud server log when it happens.

**Comment by tobiasKaminsky** [comment]
Meanwhile we enhanced the app. Can you please try and report back if the bug still exists on latest official version or even try our [dev version](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#dev-release)?

**Comment by jsargent7089** [comment]
it has been fixed
