### ISSUE TITLE
Change password: hide "get new provider"

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#1518]
If user wants to change a password, one gets following screen:
![2017-09-09-101318](https://user-images.githubusercontent.com/5836855/30238416-8c95ba94-9547-11e7-8717-56be6d13f3b1.png)

Only password is editable.
--> If server url is fixed, do not show "do you net have a server yet..." 

This is only valid for Server <12 as >=12 will use weblogin flow.

**Comment by AndyScherzinger** [comment]
:+1:

**Comment by mario** [comment]
@AndyScherzinger where's the PR for this? :P You seem to do this everywhere :D

**Comment by AndyScherzinger** [comment]
Ups...
