### ISSUE TITLE
Push notification with old login

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#1519]
Push notifications require to have an app password used instead of the "old" login with username/password.
If an user still uses the old login and access the push notification view a fixed snackbar should be shown with "For push notifications please use an app password" (or similar).

(as discussed at conf)

**Comment by AndyScherzinger** [comment]
:+1:

**Comment by mario** [comment]
@AndyScherzinger where's this PR you talk about? :P

**Comment by AndyScherzinger** [comment]
my mistake, meant "approved"
