### ISSUE TITLE
Google Backups: exclude database

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#1521]
In backup.config.xml we currently exclude evernote_jobs.* and we should also exclude our database.
Otherwise it can happen that the database is restored from a (google) backup and leads to inconsistent.

**Comment by AndyScherzinger** [comment]
👍

**Comment by joshtrichards** [comment]
As a result of #10705 / #10637 we no longer backup (via Google) at all, but it might be worth keeping this issue around in case we ever re-consider I guess...

**Comment by joshtrichards** [comment]
On second thought, nothing actionable remains here. Closing.
