### ISSUE TITLE
User manual

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#1522]
Frankly, I never updated anything of the user manual and we have hardcoded checkout of a rather old version:
Submodule path 'user_manual/ocdoc': checked out '343496c792616459e8204b6614fd42a1b16a6d68' from 26 Jan 2015.

I suggest to drop this reference from our repo, so this will not get checked out anymore (will also speed up drone).

If we have (ever) time, we can do a rewrite of docs.

**Comment by AndyScherzinger** [comment]
👍
