### ISSUE TITLE
App stuck on opening vcf vCard in Android app

### ISSUE THREAD

**Issue by HomeServ** [nextcloud/android#1526]
### Actual behaviour
- When opening vcf vCard file, app stuck in the contact restore window. Forced closing the app doesn't help. 

### Expected behaviour
- When push back button/key go back to previous window. 
 
### Steps to reproduce
1. Open vcf file in app
2. Push back button/key

### Environment data
Android version: 7.0

Device model: Samsung Galaxy S8

Stock or customized system: Stock Samsung Firmware

Nextcloud app version: 2.0.0 RC5

Nextcloud server version: 12.0.1

**Comment by mario** [comment]
Guess we need to fix this for next RC...

**Comment by tobiasKaminsky** [comment]
I tried this file 

```
BEGIN:VCARD
VERSION:2.1
N:Mustermann;Erika;;Dr.;
FN:Dr. Erika Mustermann
ORG:Wikimedia
ROLE:Kommunikation
TITLE:Redaktion & Gestaltung
TEL;WORK;VOICE:(0221) 9999123
TEL;HOME;VOICE:(0221) 1234567
ADR;HOME:;;Heidestrasse 17;Koeln;;51147;Deutschland
EMAIL;PREF;INTERNET:erika@mustermann.de
REV:20140301T221110Z
END:VCARD
```

and it is working as expected: first it downloads the file, then I can see the vcard entry, select it and restore it.

Can you give me the problematic file, of course edited to prevent exposing personal infos ;-)

**Comment by tobiasKaminsky** [comment]
No response within the last month, therefore closing.
Please feel free to reopen with additional infos, if the problem still exists.
