### ISSUE TITLE
Doesn´t download album cover on .m4a files

### ISSUE THREAD

**Issue by xXSTrikeXx** [nextcloud/android#1528]
### Actual behaviour
Shows Album Cover´s in the Nextcloud Player, but it doesn´t show the covers in the android player.

### Expected behaviour
Should show the cover in the nextcloud player and also in the android music player.
 
### Steps to reproduce
1. Uploaded files (.m4a) from Itunes via Web (no App) into the cloud.
2. Downloaded via "Sync" order of the music folder.
3. When i open the music file in the nc app it shows the covers, but when I open offline the file via music player no album cover is shown.

### Environment data
Android version: 4 and 6

Device model: Galaxy S3 and Huawei Y6

Stock or customized system: Stock

Nextcloud app version: 1.4.x and 2.0.0 RC5

Nextcloud server version: 12.0.2

**Comment by AndyScherzinger** [comment]
Nothing we can do here... The Nextcloud Player basically reads the cover art from within the audio file and displays it. So 7f other players don't do that there is nothing we can do about that :/

**Comment by xXSTrikeXx** [comment]
Sorry, but I think there is. Yesterday I thought it gets lost by downloading the files via the android app. Now I found out that the player isn´t even recognizing the files, because it´s in the android order ( i save my files to /storage/emulated/0/Android/data/com.nextcloud.client/files). I think thats the reason why the android music player isn´t analyzing the files and they aren´t shown up in the libary. Thats the reason (no analyzing) that the cover´s aren´t shown on the devices. So I think we need to start a discussion of how we integrate music files to the android system, because my system didn´t even recognized that I had downloaded music files from nextcloud.

**Comment by xXSTrikeXx** [comment]
@AndyScherzinger I looked up now on the second device (Galaxy S3 Neo, Android 4.4.2) and I see that the files are shown in the library, but also without album covers. The save directory of nc is there 'standard'.
There it´s not in the standard App folder (e.g. Android/data/com.nextcloud.client/files/Nick@Cloud...; like my Huawei device, look above). 
There it´s in /storage/emulated/0/nextcloud/Nick@Cloud.... I think thats the reason why on this android version the music files are shown in the library.  Well thats doesn´t explain why the covers has left the device, but I think there could be some improvement for a better handling with music files ;)

Cheers

**Comment by AndyScherzinger** [comment]
Oh, sorry. Then there are two issues to talk about actually :)
Files showing up in media libraries and cover art being displayed...

Files showing up should be covered by @tobiasKaminsky change since files showing up in media libraries depends on the storage location while cover art imho depends on the apps themselves.
