### ISSUE TITLE
Feature Request: 2FA via Mobile App

### ISSUE THREAD

**Issue by fti7** [nextcloud/android#1530]
It would be really nice to be able to use the Mobile App to accept 2FA Logins via the Webbrowser.
Several Online Banking Apps use this Kind of 2FA for Transactions.

Workflow example - Login via Webbrowser:
1. Login with usual Username/Password
2. User chooses "Mobile App" as 2FA Mechanism
3. Mobile App: Message Popup with Browser/IP Address of the Browser Login
4. User can Accept/Decline it (There should be some Kind of Timeout. e.g. 60sec which should also be visible in the Browser)
If Fingerprint is activated in the App - An additional Fingerprint Request is made
5. If the User clicks "Accept" in the User will be logged in

There should be some kind of blacklisted 2FA Mechanisms, depending on the Access/Login.
e.g. On Login with the Mobile App, the Mobile App 2FA should be blacklisted and alternative Mechanism like TOTP enforced.

**Comment by nursoda** [comment]
This is implemented long ago, should be closed (I can't).
