### ISSUE TITLE
Auto upload does not work in RC6

### ISSUE THREAD

**Issue by Ricardosgeral** [nextcloud/android#1534]
### Actual behaviour
-set auto upload (I've tested with wifi on and off) to send pictures taken from camera. But nothing started after taking pictures 

### Expected behaviour
-should upload to server the photos taken with phone
 
### Steps to reproduce
1. 
2. 
3. 

### Environment data
Android version: 6.0.1

Device model: xiaomi redmi NOTE 4X 

Stock or customized system:

Nextcloud app version: 2.0 RC6

Nextcloud server version:12.0.2

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by mario** [comment]
Do they appear in the the upload queue at all?

**Comment by Ricardosgeral** [comment]
No,  nothing

**Comment by tobiasKaminsky** [comment]
Meanwhile we enhanced the app. Can you please try and report back if the bug still exists on latest official version in conjuction with latest server or even try our [dev version](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#dev-release)?

**Comment by peteman52** [comment]
I can confirm, that autoupload doesn't work for Nexus 5 with Android 6.0.1 and Nextcloud client 3.4.1  and Nextcloud 14 .
However, just to tease you, autoupload works fine with said configuration and  Owncloud client 2.7.0 .
