### ISSUE TITLE
Photos & Favs Won't Load

### ISSUE THREAD

**Issue by deljones** [nextcloud/android#1535]
Replaced RC5 with the new RC6. Followed instructions removing account and setting back up again.

Photos wont load from server
Favourites wont load from server

Using a Sony XperiaZ5 
Android 7.1.1

Log is empty. Tried uninstall and restart

Dj

**Comment by mario** [comment]
Ldap powered setup?

**Comment by mario** [comment]
Also what nc version?

**Comment by deljones** [comment]
Hi Mario...

No LDAP in use, NC v12.0.2
Everything worked fine with RC5

D

**Comment by mario** [comment]
Can you send a test account to mario@nextcloud.com? I tested with NC 12.0.2
(and a few other people) and it all worked...

**Comment by mario** [comment]
Should be fixed via https://github.com/nextcloud/android/pull/1539.
