### ISSUE TITLE
Remove/insert same SD card causes duplicate auto-upload of all images/videos

### ISSUE THREAD

**Issue by paulmedynski** [nextcloud/android#1538]
### Actual behaviour
- Remove SD card with images/videos that have already been auto-uploaded
- Re-insert same SD card
- Observe that Nextcloud re-uploads duplicates of all images/videos

### Expected behaviour
-Nextcloud doesn't upload duplicates
 
### Steps to reproduce
1. Setup Nextcould to auto-upload new images/videos.
2. Take some pictures/videos and save them to the SD card.
3. Observe that Nextcloud correctly auto-uploads them.
4. Remove the SD card.
5. Re-insert the SD card (note that some devices combine the SD and SIM slots, so it isn't possible to swap SIMs without removing the SD card as well).
6. Observe the Nextcloud re-uploads duplicates of all images/videos that it previously auto-uploaded from the SD card.

### Environment data
Android version:
Android 7.1.2

Device model: 
BlackBerry BBD100-2

Stock or customized system:
Stock

Nextcloud app version:
1.4.3

Nextcloud server version:
Owncloud v8.x

**Comment by mario** [comment]
Fixed in 2.0.0 beta.

**Comment by paulmedynski** [comment]
Excellent!  I signed up for the Play Store beta, so I'll update and check it out.  I have a similar problem with PowerAmp and it seems to stem from Android 7's desire to give the SD card a different mount point every time you insert it - annoying!
