### ISSUE TITLE
Client should respect metered WiFi networks 

### ISSUE THREAD

**Issue by Xparx** [nextcloud/android#154]
### Actual behaviour
Photos and videos are uploaded on Metered WiFi networks even when the option "upload only on WiFi" is selected. 

### Expected behaviour
The app should treat metered network as mobile networks. 
 When options not to upload is selected no photos should be automatically uploaded. 

### Steps to reproduce
1. Turn on upload photos. 
2. Turn on metered networks in WiFi settings on Android. 
3. Turn on only upload on WiFi. 
4. Take pictures. 

### Environment data
Android version:
Latest I think. 
Device model: 
Nexus 6p 

Stock or customized system:
Custom, purenexus ROM. 
Nextcloud app version:
1.1.0
Nextcloud server version:
9.0.52 (i think) 

PR: #161

**Comment by tobiasKaminsky** [comment]
Is there a way to see if a wifi is metered or not from within android?

**Comment by AndyScherzinger** [comment]
AFAIK this should help 

http://developer.android.com/reference/android/support/v4/net/ConnectivityManagerCompat.html#isActiveNetworkMetered(android.net.ConnectivityManager)

**Comment by tobiasKaminsky** [comment]
So there would be an additional option: "upload on metered wifi", which is off by default.
It will affect both instant upload: video and image.

cc: @jancborchardt @przybylski

**Comment by Xparx** [comment]
Thanks for taking the time to look at this. 
The only other app I know that this has an effect on in relation to photo upload is Google photos. It will not upload when the WiFi is metered. 
Alternativ solution would be to either only upload on specific WiFi or pause syncing for an extended period.

**Comment by jancborchardt** [comment]
@tobiasKaminsky I’d definitely avoid a separate setting for that as it’s sooo specific. Most people will not even know what a »metered wifi« is (I sure didn’t). We should simply treat metered wifi networks as mobile networks as @Xparx said Google Photos does as well. Keep it simple.

**Comment by AndyScherzinger** [comment]
I second treating metered wifi networks like cellular networks.

**Comment by tobiasKaminsky** [comment]
Then we have a solution :+1:

**Comment by tobiasKaminsky** [comment]
I cannot test it, but the normal upload on wifi is working.
ref: #161

@Xparx when we have a 1.3.0 RC1 please help us testing this feature

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky you should be able to for example by tagging your own private wifi as metered. 
I can test that too as soon as I am feeling better.

**Comment by AndyScherzinger** [comment]
Just got to settings, data usage, at the bottom you will find network restrictions :)

**Comment by tobiasKaminsky** [comment]
Thanks, then the feature is working :)

**Comment by AndyScherzinger** [comment]
Sweet, so to also tested with metered wifi now? :)

**Comment by tobiasKaminsky** [comment]
Yes :+1:

**Comment by AndyScherzinger** [comment]
Awesome!!!

**Comment by Xparx** [comment]
Wow, that was fast :)! Currently my server is down but I will test as soon as as I'm back home @tobiasKaminsky. It seems like you got it though. Really awesome!

**Comment by AndyScherzinger** [comment]
@Xparx it will be scheduled for 1.3.0 though!

**Comment by Xparx** [comment]
Ah, perfect! @AndyScherzinger this is a big one for me. Really appreciate it.

**Comment by AndyScherzinger** [comment]
Sure thing. I just wanted to provide some information on the release schedule to manage expectations here.  A final 1.3.0 might still be a month away,  a release candidate probably around 2-3 weeks.

**Comment by Xparx** [comment]
I figured something like that, as it was two version ticks off my version. No worries.

**Comment by jancborchardt** [comment]
@Xparx cool! :) Any input and especially help in reviewing pull requests is always appreciated.

**Comment by AndyScherzinger** [comment]
Merged and will thus be part of the next feature release :rocket:

**Comment by AndyScherzinger** [comment]
@Xparx we are just finishing up thing and are in preparation of 1.3.0 RC1 so the final/stable version will probably be published in ~2 weeks

**Comment by Xparx** [comment]
Great news!
Looking forward to it. Many thanks!

**Comment by AndyScherzinger** [comment]
You can register as a tester on Google play and get it right away :) RC1

**Comment by Xparx** [comment]
I will definitely do that. Just found the beta channel now. =)
