### ISSUE TITLE
User information screen issues

### ISSUE THREAD

**Issue by mario** [nextcloud/android#1540]
![screen shot 2017-09-05 at 10 04 15](https://user-images.githubusercontent.com/5810/30371307-7d8ebbb4-987a-11e7-9c40-8664c213f288.png)

Why would I ever have this shown is beyond me o.o So please make it look nicer :P

**Comment by AndyScherzinger** [comment]
@mario what would you consider nicer?

--> changed message to "Failed to retrieve user information"?

**Comment by mario** [comment]
That would be a good start :)

**Comment by AndyScherzinger** [comment]
Cool... Any hints on how to reproduce the error?

**Comment by mario** [comment]
Sure. Login on NC12. Go to web interface, and delete the app password. Magic.

**Comment by AndyScherzinger** [comment]
PR is #1542
