### ISSUE TITLE
Crash during account deletion

### ISSUE THREAD

**Issue by stalker314314** [nextcloud/android#1544]
### Actual behaviour
Deleting account results in crash of app

### Expected behaviour
No crash
 
### Steps to reproduce
1. Create account
2. Auto upload some files (not sure about this part though)
3. Delete account

### Environment data
Android version:

Device model: 

Stock or customized system:
LineageOS

Nextcloud app version:
master

Nextcloud server version:
12.0.2RC

### Logs

`09-13 21:14:58.895 4562-4686/com.nextcloud.android.beta D/FileContentProvider: Removing FILE 00048297ocgghykd5h22

09-13 21:14:58.898 4562-4686/com.nextcloud.android.beta D/FileContentProvider: DB-Error removing file!  java.lang.IndexOutOfBoundsException
                                                                                   at android.net.Uri$PathSegments.get(Uri.java:989)
                                                                                   at android.net.Uri$PathSegments.get(Uri.java:987)
                                                                                   at 

com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:122)
                                                                                   at 

com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:97)
                                                                                   at 

android.content.ContentProvider$Transport.delete(ContentProvider.java:339)
                                                                                   at 

android.content.ContentResolver.delete(ContentResolver.java:1332)
                                                                                   at 

com.owncloud.android.datamodel.FileDataStorageManager.deleteAllFiles(FileDataStorageManager.java:2185)
                                                                                   at 

com.owncloud.android.jobs.AccountRemovalJob.onRunJob(AccountRemovalJob.java:75)
                                                                                   at 

com.evernote.android.job.Job.runJob(Job.java:123)
                                                                                   at 

com.evernote.android.job.JobExecutor$JobCallable.runJob(JobExecutor.java:165)
                                                                                   at 

com.evernote.android.job.JobExecutor$JobCallable.call(JobExecutor.java:150)
                                                                                   at 

com.evernote.android.job.JobExecutor$JobCallable.call(JobExecutor.java:133)
                                                                                   at 

java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                   at 

java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                   at 

java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                   at java.lang.Thread.run(Thread.java:818)
09-13 21:14:58.909 4562-4686/com.nextcloud.android.beta I/JobExecutor: Finished job{id=39, finished=true, result=SUCCESS, canceled=false, periodic=false, class=AccountRemovalJob, tag=AccountRemovalJob}`

**Comment by AndyScherzinger** [comment]
@mario any chance you can have a look at this? While looking at the logs ```/com.nextcloud.android.beta D/FileContentProvider``` tells me it must be the ```dev``` branch not the ```master``` 😕

**Comment by mario** [comment]
@AndyScherzinger I'd assume the same, but @tobiasKaminsky will have to as this is his work + absolutely busy on other things :(

**Comment by stalker314314** [comment]
@AndyScherzinger Ops, you are right, I am switching between multiple versions and got them confused. Sorry!

**Comment by AndyScherzinger** [comment]
No worries @stalker314314 :) Does this also happen on the master branch?

**Comment by tobiasKaminsky** [comment]
Is this still happening for you?

**Comment by stalker314314** [comment]
TBH, I didn't recently tried to delete account while there was upload in progress:) As far as I am concerned, you can tentatively close issue, but I still think there is some concurrency issue lurking underneath uploading logic (based by stack trace)

**Comment by tobiasKaminsky** [comment]
Thank you, I overread the part that you were removing the account during an upload.

Steps to reproduce:
- upload a big file
- meanwhile delete the same account
- crash

**Comment by tobiasKaminsky** [comment]
Retested it now, this seems to be fixed.
If not, please re-open.
