### ISSUE TITLE
[feature request] Sync with check

### ISSUE THREAD

**Issue by ouafnico** [nextcloud/android#1546]
Hi,

The actual feature to auto upload files on folders is very good, but I think it can miss a little option or function.

Is there any way to add an option to tell nextcloud app to check if there are missing files on the server, to upload missing files ?

For example, I create the sync for my camera folder, but only new files will be uploaded, not old ones already present on my phone.

If we can had a sort of real replication can be very very usefull (and not only for pictures), maybe like a simple "one shot" button to tell "upload missing files".

By the way I'm talking only for a one way replication (android to server).

Thanks ;)

**Comment by AndyScherzinger** [comment]
@mario is this functionality covered by the force rescan button?

**Comment by mario** [comment]
Of course not. Force rescan just initiates check faster to see if there are any new files locally since we last checked.

**Comment by AndyScherzinger** [comment]
ah, okay :)

**Comment by ouafnico** [comment]
is it a possible feature?

**Comment by mario** [comment]
Everything is possible :) It will happen one day.

**Comment by xXSTrikeXx** [comment]
discussion is now in the irc ;)

**Comment by AndyScherzinger** [comment]
"Roadmap" for auto upload can be found here #285 where this feature is already documented to be implemented in a future release (so I'd close the issue for now, please re-open if you think it should stay open). Can't say when this might come since it depends on people picking it up and creating an implementation for it.
