### ISSUE TITLE
About dialog

### ISSUE THREAD

**Issue by schiessle** [nextcloud/android#1548]
It might be a good idea to integrate a small about dialog. To give some credits to the (main) developers and to inform the user about the license and where to get the source code.

cc @AndyScherzinger @tobiasKaminsky what do you think?

**Comment by mario** [comment]
Well I guess we could introduce a "Credits / Licences" as part of settings and mention all the tools/libs/etc we use and their licencens.

**Comment by AndyScherzinger** [comment]
All in all I'd say a good idea, also mentioning the libs/licenses, flagging it a starter issue then :)

**Comment by KrishAmal** [comment]
Hey , I would like to work on this .

**Comment by comradekingu** [comment]
@KrishAmal A link to the translation platform, and a field for contacting the translators of the currently selected locale.

**Comment by tobiasKaminsky** [comment]
@comradekingu this is a good idea, but I think that this is not necessary to have in the app. This is already in https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md, which is already included in "participate" view.

This is the current state:
![2017-09-21-113114](https://user-images.githubusercontent.com/5836855/30689474-5c08e454-9ec1-11e7-8176-3467d5f3ffb4.png)

"Credits/Licences" as proposed by Mario are a good idea, but I rather would like to have them here on github as it is easier to manage. So a similar entry/link is maybe enough?
@mario @AndyScherzinger @schiessle 

@KrishAmal please wait with starting developing until we have discussed this, so work is not done twice ;-)

**Comment by AndyScherzinger** [comment]
I'd say combine all of them into an about activity (no dialog) which then could link to several "websites", so merging

* Some about text about Nextcloud/App/OSS-hint
* License
* source code
* developer/translator credits

This way we could have some text and 3 "links" and would also reduce the amount of items on the settings page again

**Comment by AndyScherzinger** [comment]
Thinking about it a little longer... we already have license and code in the app with the latest release and I'd vote to not put names into the app since that is demotivational in my opinion (how to decide "top developers" etc / how do you feel if you didn't make it on the list)...

I'd say: We leave it as is.

**Comment by tobiasKaminsky** [comment]
👍  Fine for me
