### ISSUE TITLE
Errors when Large Selection Uploading

### ISSUE THREAD

**Issue by c0fe** [nextcloud/android#1549]
I am using a Google Nexus 6P phone with Android 7.1 and Nextcloud app that is running on a local home server. I selected about 176 files which came out to be 1.4GB of files, I selected the photos from "Photos"  app that is installed by default in Android and selected to share the files through uploading the actual image size to Nextcloud. The app then crashed out, I opted to send in the feedback with logs but the app then continued to upload. So I am confused.

**Comment by tobiasKaminsky** [comment]
Uploading too many items at once currently leads to a crash.
There is a PR trying to solve this, but it only "postpone" the crash…

Currently the only workaround is to do it in batches, eg. parts of 50 items.

(closing as a duplicate)
