### ISSUE TITLE
[RC1] Can't switch from "Uploads" to "All Files"

### ISSUE THREAD

**Issue by minils** [nextcloud/android#155]
### Actual behaviour
- Using the left drawer to switch from "All Files" to "Uploads"
- App switches to the "Uploads" view
- After tapping "All Files" in the left drawer the app stays in the "Uploads" view

### Expected behaviour
- Using the left drawer to switch from "All Files" to "Uploads"
- App switches to the "Uploads" view
- After tapping "All Files" in the left drawer the app switches to the "All Files" view
 
### Steps to reproduce
1. Open App
2. Open left drawer
3. Switch to "Uploads"
4. Open left drawer
5. Switch to "All Files"
6. Nothing happens

### Environment data
Android version: 6.0.1

Device model:
One Plus 2

Stock or customized system:
Stock OxygenOS 3.0.2

Nextcloud app version:
1.2.0 RC1

Nextcloud server version:
9.0.52

### Logs
-

**Comment by minils** [comment]
Sorry this is a duplicate of https://github.com/nextcloud/android/issues/145.

**Comment by tobiasKaminsky** [comment]
No problem, thanks for reporting :+1: 
We will release a RC2 soon.

**Comment by AndyScherzinger** [comment]
@minils did you already have a change to test the RC2 and if so can you confirm it is working now? :)

**Comment by minils** [comment]
It's working 👍
