### ISSUE TITLE
User does not stay logged in. 

### ISSUE THREAD

**Issue by KroniK907** [nextcloud/android#1550]
Currently I am using SSO & SAML app for user login so this could be part of the problem, however whenever the app closes, the app does not save the user's login state. 

If I open the app, enter in the URL and login (In my case its a google login using SAML) everything comes up as it should. Then if I close the app and re-open it again, I am given the same screen requesting the server URL again. 

The app does not appear to save the user state or even save the last nextcloud server URL when I close the app. 

I currently cannot test with the SSO & SAML app disabled, so its possible that its the SAML login that is causing this issue. 

==Specs==

Nextcloud Server 12.0.2
Nextcloud Android Version 20170903 (downloaded using fdroid)
Android 6.0.1
Samsung Note 4

**Comment by tobiasKaminsky** [comment]
@LukasReschke any ideas regarding our new weblogin flow and sso/saml?

**Comment by skyfox675** [comment]
I too am seeing the same behavior. I have SSO SAML disabled. App shows "file not found" click here to return to.. "
