### ISSUE TITLE
CentOS automatic updates break external storage (Windows shares)

### ISSUE THREAD

**Issue by barrydegraaff** [nextcloud/android#1556]
Hello All,

My Nextcloud instance runs on CentOS 7 with yum-cron for automatic updates.

Last friday my external storage stopped working, it seems a new samba was rolled out in centos 7 and it requires the use of domain\username and not just username.

Adding the domain for shares with global stored credentials worked, however, it does not work when the option 'log-in credentials save in session' is used. I cannot add a domain there (option missing). And my users log on via webdav and can't add it either.

The error is vague, 
'could not get credentials because session is unavialable'

What can be a possible work-around?

**Comment by barrydegraaff** [comment]
Seems like an upgrade issue, when I play around in the UI, at some point
'SMB CIFS using OC login'
changes to 'SMB/CIFS'

Then a `domain` field magically appears, I do not yet see how to make that change happen when I want to.

**Comment by barrydegraaff** [comment]
Unfortunately nextcloud12 no longer uses mount.json, so changing that has no effect

I removed and re-added all my shares by hand, it seems to solve the problem, but it will nuke the cache, so it will hit our performance and probably populate our database with a huge amount of orphans.

**Comment by AndyScherzinger** [comment]
Thank you for your report @barrydegraaff this sounds like a webUI issue so calling @MorrisJobke and @nickvergessen to the rescue!

**Comment by barrydegraaff** [comment]
Yeah, its a little of everything, but I guess, my old owncloud 9 share definition finally broke :-p

It maybe nice, to drop support for `\OC\Files\Storage\SMB_OC` in a next release so it does not happen unexpectedly like this.

**Comment by tobiasKaminsky** [comment]
@MorrisJobke @nickvergessen do you have any insights on this?

**Comment by barrydegraaff** [comment]
Also, for housekeeping it would be better to remove config files that are no longer used, to avoid confusion. So mount.json should be removed, if the configuration of the external storages moved somewhere else.

**Comment by tobiasKaminsky** [comment]
After reading it again, I think most of this is server related, so @barrydegraaff can you open up your ideas on https://github.com/nextcloud/server
