### ISSUE TITLE
Thumbnails: always load the current visible ones

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#156]
### Actual behaviour
- loading of current thumbnail takes very long
### Expected behaviour
- instant show current visible thumbnails
### Steps to reproduce
1. open folder with > 500 not yet loaded thumbnails
2. jump to several points in this folder
3. thumbnails are loaded in this order, the current thumbnails seem to be added to the end of the queue.

**Comment by AndyScherzinger** [comment]
Which screen are we talking about? The file listings? If so this should be "auto-fixed" whenever we implement the move from listview to recyclerview.

**Comment by tobiasKaminsky** [comment]
Yeah, file listing of remote content.
As the switch to recyclerview may take some time we maybe can provide a quick fix for this in the meantime...?

**Comment by AndyScherzinger** [comment]
Hmmm, maybe. The tricky part would be to "know" which thumbnails should be loaded at the very moment (influence the order of the to be downloaded thumbnails).

**Comment by tobiasKaminsky** [comment]
As far as I know we use a check to cancel thumbnail downloading if the thumbnail is not currently visible.
Tested it in latest master and it seems to work.
(do not know what error I experienced back then)
