### ISSUE TITLE
Notifications: dicuss polling

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#1561]
If push notifications are not working, e.g. on Fdroid or temporary problems of registration, do we want to poll?

@AndyScherzinger https://github.com/nextcloud/android/pull/1560#issuecomment-330770769
> [...] would recommend to have a 10-15 minutes interval to not drain the battery. As a second step we could then of course go for a "smarter" polling looking at the frequency of notifications coming in.

@mario https://github.com/nextcloud/android/pull/1560#issuecomment-330772643
> You have to use AlarmManager for F-droid as that is the only thing that currently guarantees the device will wake up. The interval can be decided I guess, but in order to know which notifications to show we'll have to store notifications in the DB and show only ones we haven't shown etc etc.

**Comment by srkunze** [comment]
I would suggest using an increasing interval in case of silence. Had good experience with either linear or exponential growth.

Just wonder if there isn't a standard solution for this in Android (push fallback or something).

**Comment by mario** [comment]
No. Fallback is manual polling :)

Increasing interval is good, yes.

**Comment by srkunze** [comment]
> No. Fallback is manual polling :)

Manual is meh :D all Android apps have to implement it themselves. What a waste...

**Comment by mario** [comment]
That's only if you don't want to publish on Play Store. All Play Store apps
can have push without an issue.

**Comment by srkunze** [comment]
> That's only if you don't want to publish on Play Store. All Play Store apps can have push without an issue.

Ah, okay. Didn't know. :+1:

**Comment by tobiasKaminsky** [comment]
> Fallback is manual polling :)

This means that an user has to enter the app and opens "Notifications". But with polling, even if it is only once an hour, the user will get a delayed notification without manual interaction...

**Comment by joshtrichards** [comment]
Let's consolidate with the more recently active #7046
