### ISSUE TITLE
double uploads

### ISSUE THREAD

**Issue by michapixel** [nextcloud/android#1563]
### Actual behaviour
i only have my camera folder set-up so it auto-syncs to my nextcloud-server (only wlan) splitted into pics and videos (seperated dirs server) but some images and videos are uploaded/copied to the instant-upload-folder ("SofortUpload/Camera"), and then uploaded / synced too, which is REALLY annoying.
Since we are 6 people/phones and even more desktop-endpoints in my house using this feature (syncing) you can understand, that this gets really critical in terms of wasted space. 

### Expected behaviour
it should catch new files in the camery-folder, seperate pics and videos and transfer them to the server when wlan is on 
 
re-installing didn't help, since from what i read here, the settings et.al never gets deleted, but since i use this app from the very beginning, it might have corrupted some settings while i took updates i was offered (in fact g-play does that automagically for me in the background). 

### Steps to reproduce
1. 

### Environment data
Android version: 
8 (Oreo)

Device model: 
Nexus 5x
Stock or customized system:
Stock
Nextcloud app version:
1.4.3 
Nextcloud server version:
12.3 (just updated)
#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

btw:
i love what you do guys, so bare with me, when i sound a little too critical since this app is free, but i need this to be fixed ;)

**Comment by mario** [comment]
Thanks for the report. Fixed with 2.0.0 beta, so will be in 2.0.0 stable ;)
