### ISSUE TITLE
Refresh user avatar

### ISSUE THREAD

**Issue by matiasdelellis** [nextcloud/android#1566]
### Actual behaviour
-Change user photo (or other info) and nextcloud client not reflect it.

### Expected behaviour
-When change any user info on server must be reflected in the client. This already happens for the background image. So both images should be cached for a certain amount of time, e.g. 24 hours.
 
### Steps to reproduce
1. Login on android client.
2. Change user profile on nectcloud server
3. Launch android client.
4. See sidebar info and see old profile...

### Environment data
Android version: 6.0

Device model: Moto X

Stock or customized system: Stok

Nextcloud app version: 2.0.rc5 or anything else..

Nextcloud server version: 2.0.1

#### Web server error log
```
IMHO Irrelevant
```

#### Nextcloud log (data/nextcloud.log)
```
IMHO. Irrelevant
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
@matiasdelellis thanks for the report. One question: Does the avatar never gets replaced or does it just take a while to pick up the new one?

**Comment by matiasdelellis** [comment]
Hi @AndyScherzinger 

Since the report was not updated. Even more, delete the account and turned to create and was not updated.

Maybe it would be android-library bug, since it is handled there and use a different url ..

Android-library say that use a non oficial path:
 * https://github.com/nextcloud/android-library/blob/33bfb0b098eabf0be0e6f5400beee787f936900d/src/com/owncloud/android/lib/resources/users/GetRemoteUserAvatarOperation.java#L53
 * https://github.com/nextcloud/android-library/blob/33bfb0b098eabf0be0e6f5400beee787f936900d/src/com/owncloud/android/lib/resources/users/GetRemoteUserAvatarOperation.java#L186

Nextlcoud use this path:
 * www.host.com/avatar/matias/32?v=1

Thanks..

**Comment by matiasdelellis** [comment]
Ohh..
Android client not use the implementation of library..
https://github.com/nextcloud/android/blob/6826f9dda3ca5fc65f857fe7530a10977a0526c0/src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java#L552

**Comment by matiasdelellis** [comment]
Seems a problem of cache on this client implementation..

* https://github.com/nextcloud/android/blob/6826f9dda3ca5fc65f857fe7530a10977a0526c0/src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java#L637

Just check if it exists, and try to use that..

**Comment by AndyScherzinger** [comment]
Yeah, like to be cached. So it needs to check every now and then and refresh the avatar.

**Comment by matiasdelellis** [comment]
Of course.. I agree that it should be in cache..  😉 

Something to highlight too is that the background image (The server login backgroud) in the sidebar is automatically updated when the application starts, so it is not in the cache.. In general this image is much bigger than the avatar, therefore it should be in cache too.

Thanks for all,
Regards.

**Comment by AndyScherzinger** [comment]
I added that to your original report and mentioned that caching sould maybe only work for e.g. 24 hours.

**Comment by tobiasKaminsky** [comment]
A better way to handle this is to have a version id for both images. So we can simply check this.
We should ask server for this.

**Comment by AndyScherzinger** [comment]
avatar cache is PR #1621
background image cache has been put into a separate issue #1623

**Comment by AndyScherzinger** [comment]
Update since I misread the issue: background image cache is already in place

**Comment by tobiasKaminsky** [comment]
PR: #1621, #1658
