### ISSUE TITLE
Filetype icons and previews are quite small now

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/android#1573]
Some time ago, the filetype icons and previews seem to have shrunk. Weren’t they a bit bigger in the past? They are pretty small now so it would be good to bring them back to the size they were. Or is there an Android standard to those sizes?

**Comment by mario** [comment]
Screenshot?

**Comment by jancborchardt** [comment]
Ok, seems to have been like that for some time, as in 1.2.0:
![](https://raw.githubusercontent.com/nextcloud/screenshots/master/android/phone/files_list.png)

However, isn’t that a bit small?
Compare to Dropbox, where the preview is larger than the two rows of text next to it (filename & details):
![](https://lh3.googleusercontent.com/Sbw3W8L63SaIkhgHjm7e8PwVPZwon4-iDDu4hX4WXr8rkGn5h1VRJaNuTnZNtf1FRg=h900)

**Comment by AndyScherzinger** [comment]
@jancborchardt make all items larger or just the thumbnails --> also enlarge pdf, doc, etc. file type icons?

**Comment by AndyScherzinger** [comment]
@jancborchardt pushed (all) sizes of the list to the to be used 40dp size which is the max size according to material design guide which leads to (left: 32dp / right: 40dp)

![device-2017-10-02-132428](https://user-images.githubusercontent.com/1315170/31075435-cf32cb72-a775-11e7-812b-a7b6735cb828.png)

![device-2017-10-02-132417](https://user-images.githubusercontent.com/1315170/31075436-d1b76074-a775-11e7-8c33-1a56f3d376bf.png)

**Comment by AndyScherzinger** [comment]
PS is #1617 - let's have any detail change discussions over there :)
