### ISSUE TITLE
In file detail view, »Deselect all« is shown in 3-dot-menu

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/android#1574]
Open a picture and go to the 3-dot-menu in the header. One of the actions it will show is »Deselect all« which makes no sense here. ;)

**Comment by stalker314314** [comment]
As a starter, I'm picking this up:)

**Comment by AndyScherzinger** [comment]
@stalker314314 Nice! Little hint, try to not open the PR before Sunday so it counts for hacktoberfest in case you are participating 😉
