### ISSUE TITLE
Using a custom CA certificate

### ISSUE THREAD

**Issue by DBLouis** [nextcloud/android#1577]
The client prints a warning even if the root certificate is in the user trusted certificate store.

LineageOS 14.1 (Android 7.1.2)
Nextcloud client 1.4.2
Nextcloud server 12

**Comment by tobiasKaminsky** [comment]
We changed the login method with 2.0.
Can you try the 2.0 RC7? You can register for the beta program here: https://play.google.com/apps/testing/com.nextcloud.client

**Comment by DBLouis** [comment]
I tried RC6 (no RC7 on f-droid) but I can't login because the user/pass fields appear to be missing. I enter the URL and I get an error when pressing enter.

**Comment by tobiasKaminsky** [comment]
Can you send us the server url (and maybe test credentials) to android at nextcloud dot com with a reference to this issue?

**Comment by j-ed** [comment]
I confirm the described behavior. After installing RC7 I was asked to confirm, that I want to accept the self signed server certificate although the used CA certificate exists in the Android certificate store. Unfortunately my server is not reachable over the Internet so that I cannot provide credentials to you.

**Comment by tobiasKaminsky** [comment]
I am not sure if self signed certs are checked against the manually added cert store.
But manually accepting the self signed cert should not be that problem ;-)

**Comment by mario** [comment]
Please reopen. I can fix.

**Comment by tobiasKaminsky** [comment]
You can reopen it yourself ;-)

**Comment by mario** [comment]
Sure, but not from my email :P Thanks.

**Comment by tobiasKaminsky** [comment]
Then take your time and do it once you are on your laptop ;-)
There are no bonus points in answering < 10mins ;-)
