### ISSUE TITLE
Can't download files

### ISSUE THREAD

**Issue by n13d4** [nextcloud/android#1579]
Dear Sir or Madam,

I would be glad to have some of your thoughts about my issue.
Thank you for your time.

Sincerely,

N.

### Actual behaviour
-Tell us what happens
The android client doesn't download some types of files (.pdf/.doc/.txt/...). The problem seems to be related to "text files", the videos, pictures and sounds are downloaded correctly.
It also seems to be a problem from my server, I tried to use NextCloud's demo  account on the app and the files got downloaded correctly.

Everything works fine with the Windows client or the webui and the encryption isn't enabled.

I used to have this issue on my ownCloud server before installing NextCloud from scratch hoping to fix it.

This issue seems to be related to this thread [#347](https://github.com/nextcloud/android/issues/347) 

### Expected behaviour
-Tell us what should happen
 The client should open every type of files.
### Steps to reproduce
1. Open android's Nextcloud client
2. Add a new account with the following credential 
>Server address : https://durst-webmaster.fr/cloud
Username : test
Password : **\*\*\*\*\*\*\*\***
3. Try to download Nextcloud Manual

### Environment data
Android version:
7.1.1
Device model: 
ONEPLUS A5000
Stock or customized system:
Stock
Nextcloud app version:
1.4.3
Nextcloud server version:
12.0.3

#### Web server error log
```
***.***.***.** - - [24/Sep/2017:00:02:08 +0200] "GET /cloud/ocs/v1.php/cloud/user?format=json HTTP/1.1" 200 334 "-" "Mozilla/5.0 (Android) ownCloud-android/1.4.3"
***.***.***.** - - [24/Sep/2017:00:02:12 +0200] "GET /cloud/remote.php/webdav/Nextcloud%20Manual.pdf HTTP/1.1" 200 4037874 "-" "Mozilla/5.0 (Android) ownCloud-android/1.4.3"
***.***.***.** - - [24/Sep/2017:00:02:18 +0200] "GET /cloud/ocs/v1.php/cloud/user?format=json HTTP/1.1" 200 334 "-" "Mozilla/5.0 (Android) ownCloud-android/1.4.3"
***.***.***.** - - [24/Sep/2017:00:02:18 +0200] "GET /cloud/ocs/v1.php/cloud/user?format=json HTTP/1.1" 200 334 "-" "Mozilla/5.0 (Android) ownCloud-android/1.4.3"
```

#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"WcVvd1vYa5oAAHcMbmkAAADT","level":3,"time":"2017-09-22T20:15:52+00:00","remoteAddr":"***.***.***.**","user":"*****.****","app":"PHP","method":"MOVE","url":"\/cloud\/remote.php\/dav\/files\/****.****\/**************%20-%20Lettre%20de%20motivation%20en%20Fran%C3%A7ais%20BNP%20Papier.pdf","message":"Undefined offset: 3 at \/htdocs\/cloud\/apps\/activity\/lib\/FilesHooks.php#620","userAgent":"Mozilla\/5.0 (Windows) mirall\/2.3.2 (build 1) (Nextcloud)","version":"12.0.3.3"}
{"reqId":"WcYUhlvYa5oAABXsHlIAAAHR","level":2,"time":"2017-09-23T08:00:08+00:00","remoteAddr":"***.***.**.**","user":"--","app":"core","method":"GET","url":"\/cloud\/cron.php","message":"Trusted domain error. \"***.***.**.**\" tried to access using \"www.durst-webmaster.fr\" as host.","userAgent":"LWS Cron\/20150918","version":"12.0.3.3"}
{"reqId":"WcZuCVvYa5oAAH3qJXAAAABM","level":3,"time":"2017-09-23T14:22:02+00:00","remoteAddr":"***.***.**.***","user":"--","app":"no app in context","method":"GET","url":"\/cloud\/core\/img\/actions\/checkbox-white.svg","message":"Exception: {\"Exception\":\"Symfony\\\\Component\\\\Routing\\\\Exception\\\\RouteNotFoundException\",\"Message\":\"Unable to generate a URL for the named route \\\"theming.Theming.getLogo\\\" as such route does not exist.\",\"Code\":0,\"Trace\":\"#0 \\\/htdocs\\\/cloud\\\/lib\\\/private\\\/Route\\\/Router.php(339): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->generate('theming.Theming...', Array, 1)\\n#1 \\\/htdocs\\\/cloud\\\/lib\\\/private\\\/URLGenerator.php(77): OC\\\\Route\\\\Router->generate('theming.Theming...', Array)\\n#2 \\\/htdocs\\\/cloud\\\/apps\\\/theming\\\/lib\\\/ThemingDefaults.php(165): OC\\\\URLGenerator->linkToRoute('theming.Theming...')\\n#3 \\\/htdocs\\\/cloud\\\/lib\\\/public\\\/Defaults.php(186): OCA\\\\Theming\\\\ThemingDefaults->getLogo(true)\\n#4 \\\/htdocs\\\/cloud\\\/core\\\/templates\\\/layout.guest.php(45): OCP\\\\Defaults->getLogo()\\n#5 \\\/htdocs\\\/cloud\\\/lib\\\/private\\\/Template\\\/Base.php(176): include('\\\/htdocs\\\/cloud\\\/c...')\\n#6 \\\/htdocs\\\/cloud\\\/lib\\\/private\\\/Template\\\/Base.php(151): OC\\\\Template\\\\Base->load('\\\/htdocs\\\/cloud\\\/c...', NULL)\\n#7 \\\/htdocs\\\/cloud\\\/lib\\\/private\\\/legacy\\\/template.php(202): OC\\\\Template\\\\Base->fetchPage(NULL)\\n#8 \\\/htdocs\\\/cloud\\\/lib\\\/private\\\/legacy\\\/template.php(224): OC_Template->fetchPage()\\n#9 \\\/htdocs\\\/cloud\\\/lib\\\/private\\\/Template\\\/Base.php(132): OC_Template->fetchPage()\\n#10 \\\/htdocs\\\/cloud\\\/core\\\/templates\\\/404.php(10): OC\\\\Template\\\\Base->printPage()\\n#11 {main}\",\"File\":\"\\\/htdocs\\\/cloud\\\/3rdparty\\\/symfony\\\/routing\\\/Generator\\\/UrlGenerator.php\",\"Line\":130}","userAgent":"Mozilla\/5.0 (Linux; Android 7.0; SAMSUNG SM-G925F Build\/NRD90M) AppleWebKit\/537.36 (KHTML, like Gecko) SamsungBrowser\/5.4 Chrome\/51.0.2704.106 Mobile Safari\/537.36","version":"12.0.3.3"}
```

**NOTE:** You can see the error notification in the screenshot attached.

![screenshot_20170922-222651](https://user-images.githubusercontent.com/32199759/30767288-b9d682fe-9ffb-11e7-86c1-6e4efa709ae6.png)

**Comment by tobiasKaminsky** [comment]
Can you create a test account and send the credentials to android at nextcloud dot com with a reference to this issue?

**Comment by n13d4** [comment]
Dear Sir @tobiasKaminsky ,
Thank you for your answer. I've just sent the requested e-mail.
Sincerely,
N.

**Comment by tobiasKaminsky** [comment]
Thank you for your mail.
This seems to be a tricky one...
Can you tell us something more about your environment? Web server, special settings?

**Comment by n13d4** [comment]
It’s a shared hosting.
Here’s everything I could think of.
Just let me know if you need anything else.

Thank you again for your help !

**Data base Server**

Server : Localhost via UNIX socket
Type of server : MariaDB
Version of the server : 10.1.25-MariaDB-1~jessie - mariadb.org binary distribution
Version of the protocole : 10

**Web Server**

Apache/2.4.10 (Debian)
Version of the data base client : libmysql - mysqlnd 5.0.11-dev - 20120503 - $Id: 76b08b24596e12d4553bd41fc93cccd5bac2fe7a $
PHP Extension : mysqliDocumentation mbstringDocumentation
PHP Version : 5.6.30-0+deb8u1

**PHP Info**

https://www.durst-webmaster.fr/phpinfolws.php

**Comment by n13d4** [comment]
Dear @tobiasKaminsky,

I solved the problem !
I remembered that the problem occurred around the time I tried to use Cloudflare.
I changed back the DNS parameters and now everything works fine.
I still don't know exactly what the problem was but it's solved.

Sincerely,
N.
