### ISSUE TITLE
Massive battery drainage and mobile data use after first usage

### ISSUE THREAD

**Issue by kintrupf** [nextcloud/android#158]
I freshly installed the nextcloud app, connected it to my owncloud server and uploaded one small file of about 100 kb. Worked without any problems.
However, after a few hours I noticed that my phone has lost a lot more battery power than usual for the time span. According to the battery statistics the nextcloud app has used over 30% of the battery since I installed it a few hours ago. Furthermore, the app has used 64.65 MB of mobile data in that time (59.82 MB background data, 4.83 MB foreground), which was over 10% of my monthly data plan! There was no interaction with the app after the initial upload of the one file.

Android version: 6.0.1 MOB30P
Device model: Nexus 5
Stock or customized system: Stock
Nextcloud app version: 1.1.0
Nextcloud server version: owncloud 9.1

**Comment by AndyScherzinger** [comment]
@kintrupf do you still experience this behavior? My guess is that this is due to the initial installation, where the app then has to fetch the folder/file infos to have all the hierarchies and file listings available (not the files themselves.).

**Comment by kintrupf** [comment]
Truth be told, I did not use the nextcloud app ever again after experiencing this problem.
However, even if it was the very first time the app was connected to its cloud it should have never sucked so much data over a _metered_ connection, don't you think?

**Comment by AndyScherzinger** [comment]
totally agree with you @kintrupf, especially on the _metered_ issue that shouldn't happen.

**Comment by AndyScherzinger** [comment]
Openend a new issue for the _meterd_ issue with server communication -  #296

**Comment by tobiasKaminsky** [comment]
Is this one still valid?

**Comment by tobiasKaminsky** [comment]
No response within the last month, therefore closing.
Please feel free to reopen with additional infos, if the problem still exists.
