### ISSUE TITLE
Camera uploads unusable on Android 

### ISSUE THREAD

**Issue by TinoS1964** [nextcloud/android#1580]
### Actual behaviour
Images from camera are uploaded to nextcloud, , but can't view them in app. 
On PC they are alright and viewable. 

### Expected behaviour
It should be possible to view them everywhere. 
 
### Steps to reproduce
1. 
2. 
3. 

### Environment data
Android version: 8.00

Device model: nexus 6p

Stock or customized system: stock 

Nextcloud app version: 1.4.3

Nextcloud server version:latest

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by mario** [comment]
Please test 2.0.0 RC7.

**Comment by TinoS1964** [comment]
No change, what so ever. Tino SchenkTSA Systeembeheer Op 24 sep. 2017 20:10 schreef Mario Đanić <notifications@github.com>:Please test 2.0.0 RC7.

**Comment by tobiasKaminsky** [comment]
What is shown within the app? 
Does the image in question have a green arrow (means it is downloaded)?
What is the file size of the image?

**Comment by TinoS1964** [comment]
Within the app I see correct thumbnails for all images with a green V’s 
Size varies for different images from 2 to 6 MB
When selecting an image nextcloud app reports :  “Sorry cannot show image”
 
 
 
 
Tino Schenk
 
 
’t Slaa 117
7123 CT Aalten
+31 (543) 470455
 
   
 
Van: Tobias Kaminsky [mailto:notifications@github.com] 
Verzonden: maandag 25 september 2017 12:16
Aan: nextcloud/android <android@noreply.github.com>
CC: TinoS1964 <t.schenk@112computer.com>; Author <author@noreply.github.com>
Onderwerp: Re: [nextcloud/android] Camera uploads unusable on Android (#1580)
 
What is shown within the app?
Does the image in question have a green arrow (means it is downloaded)?
What is the file size of the image?

**Comment by tobiasKaminsky** [comment]
Can you delete the image with "local only" and then re-download it? I assume that this is working.

**Comment by TinoS1964** [comment]
Already done that, no change.
 
 
 
Tino Schenk
 
 
’t Slaa 117
7123 CT Aalten
+31 (543) 470455
 
   
 
Van: Tobias Kaminsky [mailto:notifications@github.com] 
Verzonden: maandag 25 september 2017 13:41
Aan: nextcloud/android <android@noreply.github.com>
CC: TinoS1964 <t.schenk@112computer.com>; Author <author@noreply.github.com>
Onderwerp: Re: [nextcloud/android] Camera uploads unusable on Android (#1580)
 
Can you delete the image with "local only" and then re-download it? I assume that this is working.

**Comment by j-ed** [comment]
Android: 7.1.2
Nextcloud app: 2.0.0 RC7

I've just tested it on my phone but I cannot replicate the problem. If I see the thumbnail of a picture and select it, the download bar is instantly shown and a moment later the picture itself is displayed. The problem might be caused by Android 8 - just a guess.

**Comment by TinoS1964** [comment]
Jeah, that's a possibility. I'm happy the images aren't corrupted, they can be viewed on my desktop. There's a challenge for the nextcloud development to tackle it in the future. Best regards, Tino SchenkTSA Systeembeheer Op 28 sep. 2017 09:53 schreef j-ed <notifications@github.com>:Android: 7.1.2
Nextcloud app: 2.0.0 RC7
I've just tested it on my phone but I cannot replicate the problem. If I see the thumbnail of a picture and select it, the download bar is instantly shown and a moment later the picture itself is displayed. The problem might be caused by Android 8 - just a guess.

**Comment by AndyScherzinger** [comment]
Is any of you using sd-card as storage for Nextcloud?

**Comment by TinoS1964** [comment]
Nope, internal mem
 
 
 
Tino Schenk
 
 
’t Slaa 117
7123 CT Aalten
+31 (543) 470455
 
   
 
Van: Andy Scherzinger [mailto:notifications@github.com] 
Verzonden: donderdag 19 oktober 2017 19:29
Aan: nextcloud/android <android@noreply.github.com>
CC: TinoS1964 <t.schenk@112computer.com>; Author <author@noreply.github.com>
Onderwerp: Re: [nextcloud/android] Camera uploads unusable on Android (#1580)
 
Is any of you using sd-card as storage for Nextcloud?

**Comment by tobiasKaminsky** [comment]
Meanwhile we enhanced the app. Can you please try and report back if the bug still exists on latest official version in conjuction with latest server or even try our [dev version](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#dev-release)?
