### ISSUE TITLE
Add customizable delay on removal of original file

### ISSUE THREAD

**Issue by timmersr** [nextcloud/android#1588]
### Actual behaviour
Received pictures are uploaded and removed directly, and are therefore not viewable by the apps.

### Expected behaviour
Being able to at least see the received pictures for some time, *before* they are being removed by Nextcloud, even if conditions of "only upload via Wi-Fi" and "original file will be removed" are correctly met. A setting to upload immediatly, but only remove the original file after X time should fix this.
 
### Steps to reproduce
1. Set "only upload via Wifi" and "original file will be removed" preferences, and have an active wifi connection.
2. Receive pictures in one of the monitored folders (ie. WhatsApp images)
3. Pictures will be uploaded already -kudos!- and removed, therefore not viewable in WhatsApp. 

### Environment data
Android version: 7.0
Device model: Samsung Galaxy 6 Edge Plus
Stock or customized system: Stock
Nextcloud app version: 2.0.0RC7
Nextcloud server version: 12.0.3

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
I am unsure how to solve/enhance this.
Auto upload is never meant to be "immediately", so it can be that there is already a delay due to android schedules the upload.
Also adding another option is cluttering up the UI.

@jancborchardt maybe?

**Comment by mario** [comment]
FYI, I am strictly against this feature.

**Comment by AndyScherzinger** [comment]
I am also voting against this feature since this is an automation tool task (like tasker, locale etc.) so offering upload-only, upload-n-move, upload-n-delete is already quite the choice with delete being an issue depending on the fodle rlocation / write permissions...

**Comment by jancborchardt** [comment]
Exactly, we’re not adding yet another option here. It’s way too specific.

**Comment by timmersr** [comment]
FYI, my workaround is to disable "original file will be removed" for WhatsApp pictures, and then to delete manually afterwards.
