### ISSUE TITLE
Resume chunked upload

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#159]
When failing to upload a really big file nextcloud app should resume and not start fresh with 0%.

**Comment by tobiasKaminsky** [comment]
Hurray :)
I guess it is not exactly clear from the description above, but this allows us to resume broken uploads on exactly the same position and not to waste time / traffic!
This is now implemented and working :) :)
I will release a PR soon.

**Comment by AndyScherzinger** [comment]
Awesome job @tobiasKaminsky :100:

**Comment by tobiasKaminsky** [comment]
Library: https://github.com/nextcloud/android-library/pull/6
PR: https://github.com/nextcloud/android/pull/168

**Comment by AndyScherzinger** [comment]
Code review done!

**Comment by LukeOwncloud** [comment]
Hurray! Available in beta?

**Comment by AndyScherzinger** [comment]
@LukeOwncloud yes it is :)

**Comment by blackcrack** [comment]
thank you for the hard work Andy :+1: 
best regards
Blacky

**Comment by AndyScherzinger** [comment]
You are welcome @blackcrack - Credit where credit is due, @tobiasKaminsky did the implementation :trophy:

**Comment by AndyScherzinger** [comment]
PR has been merged (for release 1.3.0) thus closing the issue.

**Comment by greinick** [comment]
HI, for curiosity, is that also available for the web or a webdav upload with e.g. Cyberduck?

Regadrs.

**Comment by tobiasKaminsky** [comment]
server: @MorrisJobke ?
As cyberduck is "just" a regular client and resume chunked uploads is not a webdav standard I think this must be implemented manually and therefore I doubt that this is already included.

**Comment by MorrisJobke** [comment]
> As cyberduck is "just" a regular client and resume chunked uploads is not a webdav standard I think this must be implemented manually and therefore I doubt that this is already included.

Correct.

**Comment by tobiasKaminsky** [comment]
@MorrisJobke and what about web ui? Does this handle resuming of chunked uploads?

**Comment by greinick** [comment]
Hi thanks for your feedback! The point of "non nextcloud client" resume upload is, that we would like to have foreign users to upload files up to xx GB by and if a web upload fails it starts from 0 ...

**Comment by MorrisJobke** [comment]
> @MorrisJobke and what about web ui? Does this handle resuming of chunked uploads?

13 will do.

**Comment by tcuong53-cell** [comment]
I apologize, I tried to resolve this issue but was unsuccessful. - Tôi xin lỗi, tôi đã thử giải quyết vấn đề này nhưng không thành công.
