### ISSUE TITLE
2.0.0.RC7 upload only in WIFI disregarded at least for videos

### ISSUE THREAD

**Issue by JimmyKater** [nextcloud/android#1591]
### Actual behaviour
- a video tried to (finish) upload via mobile-connection though upload-option was set to wifi-only

### Expected behaviour
- wifi-only should mean wifi-only
 
### Steps to reproduce
having had no time, yet trying to reproduce. but heys... upload took away more than 1/3 of my dataplan.

### Environment data
Android version:
6.0.1
Device model: 
huawai gx8
Stock or customized system:

Nextcloud app version:
2.0.0RC7
Nextcloud server version:

**Comment by tobiasKaminsky** [comment]
Finish means that you started on wifi and then connection to wifi was lost and after that the upload was still ongoing?

**Comment by JimmyKater** [comment]
> Finish means that you started on wifi and then connection to wifi was lost and after that the upload was still ongoing?

exactly that.

**Comment by tobiasKaminsky** [comment]
@mario this is something we did not had in our old implementation and also not in auto upload, or?
I think this must be checked during chunked upload and cancel itself if the constraints are not met any longer.
Or is there a way that the job scheduler can cancel this?

**Comment by mario** [comment]
@tobiasKaminsky there's code for this in rewritten auto upload, but it's not working - I am hoping to fix this for 2.0.1.

**Comment by jasonbayton** [comment]
Can confirm this happens for me too.

**Comment by tobiasKaminsky** [comment]
For this we need some kind of connection change listener and then stop the current upload if it is wifi only.
Isn't this handled via JobScheduler?
I thought that we had included this since quite a long time.

**Comment by mario** [comment]
Nah, we use service to do uploads, and jobscheduler checks connection only on start anyway.

But this might actually be fixed in 2.1.

**Comment by tobiasKaminsky** [comment]
Fixed via #2025
