### ISSUE TITLE
Retry failed uploads automatically if mobile data connection comes back/gets enabled by user

### ISSUE THREAD

**Issue by e-alfred** [nextcloud/android#1592]
### Actual behaviour
-A retry is not started after a mobile data connection becomes available again/the user reenables it and "Upload using Wifi only" is disabled. See https://github.com/nextcloud/android/issues/1568
### Expected behaviour
-The upload should be retried if a mobile data connection becomes available again/the user reenables it and "Upload using Wifi only" is disabled.
 
### Steps to reproduce
1. Add a file to the instant upload list (for example taking a picture) while without a mobile data connection and having "Upload using Wifi only" is disabled.
2. Reenable the mobile data connection after some time/move to an area covered by a mobile data network again.

**Comment by mario** [comment]
Fixed in rc7

**Comment by AndyScherzinger** [comment]
@e-alfred can you re-test with 2.0.0RC7? :)

**Comment by mario** [comment]
Considering this fixed.
