### ISSUE TITLE
2.0.0.RC8 Not all icons of external sites menu entries are shown

### ISSUE THREAD

**Issue by j-ed** [nextcloud/android#1594]
### Actual behavior
No icons are shown in front of *External sites* menu entries in the app menu.

![20170925_nc_app_menu](https://user-images.githubusercontent.com/2572764/30807298-89691f14-a1f9-11e7-91bc-4cda1dba3e4f.png)

### Expected behavior
The configured icons of external sites should be loaded and displayed in the app menu.

### Steps to reproduce
1. Open the Nextcloud app.
2. Check the displayed menu entries, especially the External Sites ones.

### Environment data
Android version: 7.1.1
Device model: Jiayu S3 Adv.
Stock or customized system: MadOS ROM
Nextcloud app version: v2.0.0 RC7
Nextcloud server version: 12.0.3

#### Web server error log
Nothing special has been logged related to this problem.

**Comment by alexknobbe** [comment]
i can confirm this, same here.

**Comment by e-alfred** [comment]
I have more than one external site configured in Nextcloud. Sometimes, if I click on them, an icon is shown for the first one in the list.

Additionally none of the external sites load in the Nextcloud android app. I only get a white screen.

**Comment by tobiasKaminsky** [comment]
@e-alfred regarding white screen, please open up a new issue

**Comment by j-ed** [comment]
I've just tested it with the Nextcloud app 2.0 RC8 and only the first of three external sites is prefixed by the configured icon. Is this how it should work?

**Comment by tobiasKaminsky** [comment]
@j-ed thanks, I can confirm this and will fix it.
