### ISSUE TITLE
SQL and php error in PDOStatement.php#91

### ISSUE THREAD

**Issue by BamiGorengo** [nextcloud/android#1597]
Hi, i switched from owncloud to nextcloud last month. Now i checked the errorlogs and found 2 errors:

> An exception occurred while executing 'SELECT `uid`, `displayname` FROM `EGUq6_users` WHERE LOWER(`uid`) = LOWER(?)' with params ["Butzback"]: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away

> Error while sending QUERY packet. PID=31955 at /www/htdocs/w01750fc/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php#91

The first message is i think because i use a uppercased B in my username... But why i can enter uppercase letters, when its not supported by nextcloud?

And the second error i dont understand. is this a bug?

Best Regards.

**Comment by mario** [comment]
Seems like a server error? :)

**Comment by BamiGorengo** [comment]
hmm so this is not a problem about configs ore any bugs @nextcloud?

**Comment by mario** [comment]
It might be, but you've filled an issue against Android. You need to file an issue against @nextcloud/server ?

**Comment by BamiGorengo** [comment]
oh damn... sorry for this misstake. can you move this or i need to reopen it there?

**Comment by mario** [comment]
Please re-open there, I'll close it now :) And no harm done! :)
