### ISSUE TITLE
small setup screen improvement

### ISSUE THREAD

**Issue by schiessle** [nextcloud/android#16]
I just installed the Nextcloud app, great work from everybody!

When I start the app for the first time it ask for the usual stuff like URL, username and password. Below the input fields there is a "Do you know Nextcloud?" link (don't know the exact wording because I installed it on a German environment). This points to Nextcloud.com/news. Wouldn't it be better to link to Nextcloud.com/about? Might be more useful to learn more about Nextcloud than the blogs.

**Comment by AndyScherzinger** [comment]
I am fine either way :) We could also just link to nextcloud.com or any other page you would like us to :)

@jospoortvliet what do you think from a communication/marketing/pr/whatever point of view?

**Comment by jospoortvliet** [comment]
Yeah, that does make sense. Or even just to our front page...

**Comment by mar1u5** [comment]
Front page would make sense most I think 😉

**Comment by AndyScherzinger** [comment]
Done, see #55 - need two maintainer :+1: to get merged :)
