### ISSUE TITLE
Rename "Upload path"

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#160]
https://help.nextcloud.com/t/nextcloud-android-phone-app-upload-path-problems/1882/7

rename "upload path" to "Instant upload folder"

cc @jancborchardt @AndyScherzinger 

PR: #162

**Comment by AndyScherzinger** [comment]
Perfect to me :+1:

**Comment by AndyScherzinger** [comment]
Same applies for the video upload path

**Comment by tobiasKaminsky** [comment]
Good catch!

**Comment by AndyScherzinger** [comment]
merged already, so will be part of 1.3.0
