### ISSUE TITLE
REQ: Enable Auto upload NOW instead of 15 minute schedule

### ISSUE THREAD

**Issue by 1-eric** [nextcloud/android#1602]
Currently there is only the possibility to enable or disable auto upload. When I enable auto upload, I have to wait 15 minutes (and keep WiFi connected) before the app starts an auto upload session (checking for new files then upload the new files).

It would be nice if I can set the scheduling interval (for example: manual, 15m, 30m, ...) and have an 'Auto upload now' button somewhere.

**Comment by mario** [comment]
If you enable expert mode there is such a meni item in the Upload screen.

**Comment by 1-eric** [comment]
@mario Yes thanks that 'force rescan' is the button I was looking for, but still the app will look for new files to auto upload every 15 minutes... unless the user sets the phone's powersaving mechanism to kill this app when it is in the background.

**Comment by mario** [comment]
@1-eric this is unlikely to change. If anything, we're completely removing this Expert mode menu from the Uploads screen in the coming versions.
