### ISSUE TITLE
Clicking on icon initiates multi-select

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#1605]
Just used amaze and there the multi-select is initialized when you click on a file icon.
With #579 we could also introduce this.
I think this is faster way than the long-press (which still should work)

@jancborchardt for design?

**Comment by jancborchardt** [comment]
Same for the Android mail app. Is this also used in other common Android apps like Gmail, Inbox, Dropbox, Drive etc? Just want to make sure there's no confusion cause in the web interface we're actually moving from click-icon-selects to opening the file cause it was confusing as people often clicked the file/folder icon to open.

(And really multiselect isn't that often used that I would risk having a confusing regular UX.)

**Comment by AndyScherzinger** [comment]
GMail yes
Dropbox no
Drive no

So it is not consistently used... But getting rid of the long click would be nice imho

**Comment by jancborchardt** [comment]
Long click for multiselect is an absolute Material Design / Android pattern by now so I think that’s ok.

**Comment by AndyScherzinger** [comment]
Keeping the long click is fine with, having the icon click as a second way of selecting would be a nice addition imho.

**Comment by jancborchardt** [comment]
That’s what I’m saying though:

> Just want to make sure there's no confusion cause in the web interface we're actually moving from click-icon-selects to opening the file cause it was confusing as people often clicked the file/folder icon to open.

And because we already have a mechanism for multiselect which is the de-facto standard, we don’t really need another one which has the potential to majorly mess with normal navigation. ;) Hence I’d say no on this.

**Comment by AndyScherzinger** [comment]
Fine by me :)

**Comment by jancborchardt** [comment]
@tobiasKaminsky is that ok with you? ;) Sorry but I really think it unfortunately has more potential for confusion, which would outweigh the value.

**Comment by AndyScherzinger** [comment]
Well Jan you just asked for half of it on the other PR where I opossed to it... ;)

**Comment by jancborchardt** [comment]
@AndyScherzinger aah ok, you mean the 3-dot-menu in the list? With overlaying the checkbox icon on the file icon I meant only as soon as multiselect is already initiated. :)

**Comment by AndyScherzinger** [comment]
@jancborchardt Ah okay, than I missunderstood it 👍

**Comment by tobiasKaminsky** [comment]
Fine for me, was just a nice idea ;-)
