### ISSUE TITLE
Cache images in Photos Screen

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#1607]
As discussed in https://help.nextcloud.com/t/android-app-improvements/21545 the Photos view/search (via the main menu) the images aren't caches according to user report. So if this is not the case I'd say as described in the forum that the app should cache these images too.

**Comment by tobiasKaminsky** [comment]
What is not cached? The thumbnails? Or the search result?

**Comment by AndyScherzinger** [comment]
I'd think the thumbnails, but I am not sure since I just opened the issue upon user feedback.

**Comment by tobiasKaminsky** [comment]
This is outdated, we do cache.
