### ISSUE TITLE
Android client 2.0 RC7 only shows white screen after clicking on external sites configured in Nextcloud

### ISSUE THREAD

**Issue by e-alfred** [nextcloud/android#1608]
### Actual behaviour
-When clicking on external site configured in Nextcloud only a whitescreen is shown in the app. This is probably related to this issue: https://github.com/nextcloud/android/issues/1594 At some point tapping on different external sites makes the icon of the first external site showing in the app reappear.

### Expected behaviour
-External page should load inside the app just like in the web interface.
 
### Steps to reproduce
1. Configure external site in Nextcloud
2. Access it using the Android Client 2.0 RC7

### Environment data
Android version: 7.1.1.

Device model: BQ X5 Plus

Stock or customized system: Stock

Nextcloud app version: 2.0 RC7

Nextcloud server version: 12.0.3

**Comment by e-alfred** [comment]
The same problem happens with the Nextcloud-dev 260917 app on a different device.

**Comment by tobiasKaminsky** [comment]
What kind of site do you have configured? 
I tried it with different, generic available sites, like facebook.com google.com and some sites hosted on my own server and each worked.
Are those sites reachable via https?

**Comment by e-alfred** [comment]
The problem is with custom ports. I have pages like https://my.domain:5655 which do not work. Ports on 80/443 seem to work, I tried it with google.com and it works.

**Comment by tobiasKaminsky** [comment]
@e-alfred can you send a not working url to android at nextcloud dot com with a reference to this issue? Then I can debug it. 
(I can also try it with any other arbitrary site with custom ports, but then chances are high that it still will not work for you)

**Comment by xXSTrikeXx** [comment]
Can confirm it, too. Im running pihole on my LAN and I granted access only for LAN connections. So the app listens to an DynDNS/Domain and connects with external IP. The SSL Certificate listen only on the Domain. The Result is that I get an Certificate Error while connect to the interface of pihole via local ip and https. In the browser all works :D Addresses like fritz.box works great.

**Comment by j-ed** [comment]
@xXSTrikeXx From my point of view this sounds like a DNS resolver or SSL certificate problem and not like the described Nextcloud problem. If you've created a certificate for your DynDNS domain but want to use a different DNS name or IP address locally this must fail because it breaks the general certificate verification process.

During a certificate verification the following points are checked and need all be answered "yes":
1. Does the DNS name, which is used to access the server, match the name in your certificate?
2. Could the certificate chain be verified without any failure?
3. Falls the current date/time in the validity window of your certificate?

Different ways exist to solve the problem:
- Generate a server certificate which also contains the internal DNS name and/or ip address.
- Configure your local DNS resolver so that the DynDNS name resolves to a local ip address.

**Comment by xXSTrikeXx** [comment]
@j-ed I've already added the domain but I think the last pihole update overwrited the settings ^^ reconfigurated it now and its working now with no ssl error over ssl. But the main problem persists. White Page in Android.

**Comment by e-alfred** [comment]
I tried 2.0 final and the problem still exists. Only a white page is displayed.

**Comment by xXSTrikeXx** [comment]
The problem exists only on alternative ports. Even for e.g. "fritz.box/myfritz" (Dashboard of Router) is reachable by the app, but it isn´t reachable in the server (webgui) because of the crossblala (idk). It seems that the server cant listen on http sites / sites which haven´t https. https->http

**Comment by e-alfred** [comment]
@xXSTrikeXx I think that your issue isn't quite the same. Loading websites using HTTP inside a HTTPS protected Nextcloud could probably lead to content security policy errors, hence the page wouldn't load.

I run services on custom ports protected with a certificate from an offical CA, and they load well inside Nextcloud in a browser. If I want to access them in the Android app, I can only see a blank page.

**Comment by e-alfred** [comment]
Here is the logcat output I get by opening up an external page inside the app:

```
10-19 20:56:21.097  1880  1880 D GameManagerService: NotifyRunnable. pkg: com.nextcloud.client, type: 4, isMinimized: false, isTunableApp: false
10-19 20:56:21.697  1880  2064 D StatusBarManagerService: manageDisableList userId=0 what=0x0 pkg=Window{c988389 u0 d0 p32151 com.nextcloud.client/com.owncloud.android.ui.activity.ExternalSiteWebView}
10-19 20:56:21.867  1880  3577 V WindowStateAnimator: Finishing drawing window Window{c988389 u0 d0 p32151 com.nextcloud.client/com.owncloud.android.ui.activity.ExternalSiteWebView}: mDrawState=DRAW_PENDING
10-19 20:56:21.877  1880  2168 I ActivityManager: Displayed com.nextcloud.client/com.owncloud.android.ui.activity.ExternalSiteWebView: +786ms
10-19 20:56:21.907  1880  2776 V WindowStateAnimator: Finishing drawing window Window{c988389 u0 d0 p32151 com.nextcloud.client/com.owncloud.android.ui.activity.ExternalSiteWebView}: mDrawState=HAS_DRAWN
10-19 20:56:22.137  1880  2168 I Timeline: Timeline: Activity_windows_visible id: ActivityRecord{b2fe878 u0 com.nextcloud.client/com.owncloud.android.ui.activity.ExternalSiteWebView t5302} time:1406049840
10-19 20:56:22.157 32151 32151 V ActivityThread: updateVisibility : ActivityRecord{7dc9851 token=android.os.BinderProxy@45b1237 {com.nextcloud.client/com.owncloud.android.ui.activity.ExternalSiteWebView}} show : false

```

**Comment by tobiasKaminsky** [comment]
@e-alfred can you send a not working url to android at nextcloud dot com with a reference to this issue? Then I can debug it.
(I can also try it with any other arbitrary site with custom ports, but then chances are high that it still will not work for you)

**Comment by e-alfred** [comment]
@tobiasKaminsky I already sent you one a few weeks ago. Should I send it again?

**Comment by j-ed** [comment]
@tobiasKaminsky I've run some more tests on it and was able to catch the error message on my smartphone by taking a slow-motion video. The server has been accessed on the standard TLS-port 443/tcp. It seems that the Nextcloud app tries to access the external side directly and not *tunneled* over Nextcloud, because a name resolution error is shown first ...

![20171026_nc-android-client-1](https://user-images.githubusercontent.com/2572764/32047969-0d3181fe-ba48-11e7-8e7c-e98b5b0c99b8.png)

... and then the usual message is displayed:
![20171026_nc-android-client-2](https://user-images.githubusercontent.com/2572764/32047976-12b23d58-ba48-11e7-8cad-eb19a72134b9.png)

**Comment by tobiasKaminsky** [comment]
This is a duplication of #1619 or at least we can combine both issues, right?

**Comment by j-ed** [comment]
@tobiasKaminsky I tend to agree 😄

**Comment by e-alfred** [comment]
Well, this issue is about public addresses on custom ports, not about trying to reach an address on a local network from the public internet. So these issues are by no means the same. I have to add that the issue described here is a regression because it worked in Dev versions from a few months ago.

**Comment by j-ed** [comment]
@e-alfred I've just run a test and if I access Nextcloud on a non-standard port, e.g. 8443/tcp, and an external site link, pointing to a https address on the Internet, has been defined, the page opens on my mobile phone without any problem.

**Comment by e-alfred** [comment]
@j-ed I found the problem. My certificate was from Wosign generally got revoked by Google  as an untustworthy CA some time ago. I replaced it with a new one from another CA. Now Webview shows the pages without a problem. Other browsers still work with certificates from Wosign.

To make such errors easier to followup, please show real error pages (like an insecure certificate warning) instead of a whizescreeen in the future.

**Comment by tobiasKaminsky** [comment]
@e-alfred we enhanced the error handling and it will be available in next release: https://github.com/nextcloud/android/pull/1719

Thank you for debugging it!
