### ISSUE TITLE
Migrating apps & data to a new device - bad config rc7

### ISSUE THREAD

**Issue by jasonbayton** [nextcloud/android#1609]
### Actual behaviour
I've set up a new device opting to migrate accounts and data from the old phone. 

NC requests a login, however in the background already has a config in place leading to ghosts of folders that don't exist on an SD card that isn't present.

.. then it uses battery trying to upload nothing (notification is there, nothing happens).
 
### Steps to reproduce
1. Run android setup wizard (new phone or factory reset)
2. Opt to transfer data 
3. Try to configure auto upload
4. See all folders present from old phone, set to upload but not existing.

### Environment data
Android version: 7.1.1

Device model: Moto Z Play (migrating from Moto Z)

Stock or customized system: Stock

Nextcloud app version: RC7

Nextcloud server version: 12.0.3

Screenshots wanted?

**Comment by tobiasKaminsky** [comment]
Do you have google backup system enabled or something similar? Or do you use titanium backup?
After a "real" factory reset no config can ever be there (I do this quite often with emulator) and therefore auto upload cannot have any folders. (it is just like putting a complete new hard disk into a pc).

So the config must come from something else, which it obviously does. Now we have to figure out from where.

**Comment by jasonbayton** [comment]
It's part of the setup wizard to migrate from the old device with an NFC bump - accounts, apps and data are all pulled over.

While many apps do bring the config over, plenty refuse to allow that and I have to set them up as new. That might be the safer approach for NC if there's a manifest option to define it?

**Comment by tobiasKaminsky** [comment]
Then we should try to refuse copying config file.
To have an idea which needs to be done: which setup wizard/NFC bump do you use?

**Comment by mario** [comment]
Its about disallowing db backup which is trivial. Unsure if we should do
that or actually fix the issues :)

**Comment by jasonbayton** [comment]
It's part of the android first run/setup wizard:

"Setup as new
Copy from existing device”

Tapping copy initiates the process for doing an NFC bump.

**Comment by tobiasKaminsky** [comment]
DB backup might be ok, but we need then to exclude auto upload paths as they are device specific.

**Comment by mario** [comment]
I don't think this is possible :) But let me think about this...

**Comment by tobiasKaminsky** [comment]
Ref: #1521 
Maybe we can do two steps: 
- remove database in 2.0.1
- try to enhance this in 2.1
