### ISSUE TITLE
Adding sdcard prompts immediate backup 

### ISSUE THREAD

**Issue by jasonbayton** [nextcloud/android#1610]
### Actual behaviour
I've migrated to a new device and as normal have moved the SD card over with it.

Nextcloud detects all media files in autoupload folders as brand new and attempts to immediately upload on 1800 media files, overwriting those already there.

I've had to remove and re-add the account to prevent this.

We need some form of check against what's uploaded already on the server.

### Environment data
Android version: 7.1.1

Device model: Moto Z Play

Stock or customized system: stock

Nextcloud app version: RC7

Nextcloud server version: 12.0.3

**Comment by tobiasKaminsky** [comment]
As I understood auto upload should not upload existing files.
@mario technically for auto upload it seems as out of a sudden someone captured these images all at once. Do you have an idea how to distinguish between "really new fotos" and "inserted a new sd card"?

**Comment by mario** [comment]
@tobiasKaminsky auto upload relies on timestamp modified + path to see if file has been changed/added. So it's either a case of file getting timestamp changed or SD card getting its mount point changed. 

The only real solution is, tada, hashing :) So ... future :)

**Comment by mario** [comment]
Given that auto upload would NOT upload a new folder path, this is the case of timestamps changing. Can you confirm @jasonbayton ?

**Comment by tobiasKaminsky** [comment]
I understand it as this
- factory reset
- install NC, configure auto upload
- insert sdcard 
-> all images on sdcard are detected as new

How can hashing help here? After step 2 there is no image yet which can be hashed.

**Comment by mario** [comment]
I am 99,99% sure the exact steps you posted would NOT work. Reason being:
 folders on SD would not show up for configuration BEFORE you inserted the
card.

**Comment by tobiasKaminsky** [comment]
This seems to be related to https://github.com/nextcloud/android/issues/1609 as somehow the "old" config reappears and therefore the upload paths are already configured.

So auto upload is configured for the not yet existing sdcard path and then after inserting the sdcard it correctly detects all new images.
Then this is no auto upload problem, but "only" a problem that the old config somehow reappears.

**Comment by mario** [comment]
True, it's related. But I guess this happens because timestamps change and are different from the one in the database. I'll check, but not for 2.0.0 as this is definitely a larger/long-term thing.

**Comment by jasonbayton** [comment]
I see no changes on any of the files for last modified, they coincide with date taken.

@tobiaskaminsky how you see it is pretty much what happened, except the folders were preconfigured based on migrating from the other device.

**Comment by tobiasKaminsky** [comment]
> are different from the one in the database

Which database? It is a clean installation so there are no entries in the database?

**Comment by mario** [comment]
If he migrated and synced folders are enabled, there are.

**Comment by tobiasKaminsky** [comment]
Right, I only thought that the config file/shared preferences will be transferred, but we store auto upload paths in our database, so if this is on the new device all other values are also there.
