### ISSUE TITLE
2.0.0.RC8 unable to access external side links pointing to LAN ressources

### ISSUE THREAD

**Issue by j-ed** [nextcloud/android#1619]
### Actual behavior
I've enable access to a Nextcloud instance over the internet. Everything seems to work fine except accessing a web page which have been added via an external side entry and which is pointing to a resource on the LAN. As soon as you click on such a link the following error is displayed:

![20171002_external_link](https://user-images.githubusercontent.com/2572764/31090375-bb9e5a36-a7a7-11e7-8cd9-75c16d53d26c.png)
### Expected behavior
If you' access a web pages by using an external side entry, access should be proxied via Nextcloud
and displayed from within the Nextcloud app.
 ### Steps to reproduce
1. setup an external side link pointing to an intranet page on your LAN.
2. Open the Nextcloud app.
3. Select an external side link.
-> Sorry Modified.

### Environment data
Android version: 7.1.2
Device model: Jiayu S3 Adv.
Stock or customized system: MadOS ROM
Nextcloud app version: v2.0.0 RC8
Nextcloud server version: 12.0.3

#### Web server error log
Nothing special has been logged related to this problem.

#### Nextcloud app protocol
Nothing has been logged.

**Comment by j-ed** [comment]
It might be possible that issue https://github.com/nextcloud/android/issues/1608 describes a similar or the same issue?!

**Comment by tobiasKaminsky** [comment]
I know that this is always the worsest answer, but it works for me.
But as we are displaying the websites with web view, there are sligthly more security constraints than on the regular mobile browser. 
So this can maybe the problem.

**Comment by j-ed** [comment]
@tobiasKaminsky I investigated further and found out that I'm able to access an external side link of a LAN ressource if I'm directly connected to my LAN using a wifi connection. As soon as I'm establishing a connection over the mobile LTE network the `Sorry - Modified` message is displayed.

**Comment by j-ed** [comment]
@tobiasKaminsky I've run some more tests on it and was able to catch the error message on my smartphone by taking a slow-motion video. The server has been accessed on the standard TLS-port 443/tcp. It seems that the Nextcloud app tries to access the external side directly and not tunneled over Nextcloud, because a name resolution error is shown first ...

![20171026_nc-android-client-1](https://user-images.githubusercontent.com/2572764/32048139-bae7b228-ba48-11e7-9820-6e4c2f6c96e7.png)

... and then the usual message is displayed:
![20171026_nc-android-client-2](https://user-images.githubusercontent.com/2572764/32048146-c361482e-ba48-11e7-95c1-626064814568.png)

**Comment by tobiasKaminsky** [comment]
@j-ed yes, you are right. Android opens the website directly. 
I am currently not sure how server handles this, but performance-wise I would also say that the external site is directly opened and not tunneled via nextcloud server, @MorrisJobke?

**Comment by MorrisJobke** [comment]
Correct - the browser gets the URL directly and opens it from the client

**Comment by j-ed** [comment]
@MorrisJobke, @tobiasKaminsky My understanding, and I think the understanding from most other users, is that all clients should provide access to all configured resources in the same way. So I would expect that URLs are not directly opened by the Android/iOS client but tunneled through Nextcloud.
I don't know how difficult it will be to change the behavior but I believe it would be worse to enhance the functionality in that way. In the meantime the displayed error message should at least be changed to reflect the root cause of the problem.

**Comment by MorrisJobke** [comment]
> So I would expect that URLs are not directly opened by the Android/iOS client but tunneled through Nextcloud.
> I don't know how difficult it will be to change the behavior but I believe it would be worse to enhance the functionality in that way. In the meantime the displayed error message should at least be changed to reflect the root cause of the problem

It does work the same everywhere. Both in the browser as well as in the apps the page is requested by the client side. There is no difference in this between web and app. So changing this is a new feature and needs to be discussed in https://github.com/nextcloud/external - but as of now this is not on the agenda and also not how the app originally was designed.

**Comment by j-ed** [comment]
@MorrisJobke Ok, I will open an enhancement request in that repository. So I think the only thing which need to be fixed for the moment is the error message.

**Comment by MorrisJobke** [comment]
> So I think the only thing which need to be fixed for the moment is the error message.

Why? There is nothing we can do about. It's the error message of the browser. :/

**Comment by j-ed** [comment]
The app is instantly overwriting the message `Webseite nicht verfügbar` by `Sorry Modified`. I was only able to get hold of the original message by taking a slow-motion video with a different phone as I tried to access the link. I think you agree that `Sorry Modified` says nothing?!

**Comment by MorrisJobke** [comment]
> The app is instantly overwriting the message Webseite nicht verfügbar by Sorry Modified. I was only able to get hold of the original message by taking a slow-motion video with a different phone as I tried to access the link. I think you agree that Sorry Modified says nothing?!

Ah - understood.

**Comment by tobiasKaminsky** [comment]
@MorrisJobke @j-ed please see #1719
