### ISSUE TITLE
Dual upload on multiple IP's (ipv4 & ipv6) - pfSense TunnelBroker

### ISSUE THREAD

**Issue by mzeyrek** [nextcloud/android#1622]
I've setup ipv6 (https://doc.pfsense.org/index.php/Using_IPv6_with_a_Tunnel_Broker) to my LAN network where nextcloud is hosted,

### Actual behaviour
-when a folder set to autosync with wireless only, uploads same new/changed file twice

### Expected behaviour
-Upload to server only once.

### Steps to reproduce
1. establish ipv6 over ipv4 via TunnelBroker (pfSense)
2. Android client gets both ipv4 and ipv6 IP addresses 
3. client uploads same file using both protocols

### Environment data
Android version:6.0.1
Device model: BlackBerry PRIV
Stock or customized system: Stock
Nextcloud app version: 2.0.0RC8
Nextcloud server version: 12.0.3
### Logs Let me know if needed, screenshot can be found here : https://ibb.co/jWHCQb

Also here ![screenshot at 2017-10-03 09 34 19](https://user-images.githubusercontent.com/8410706/31112723-135d630e-a81e-11e7-9d52-4f2e9bae23eb.png)

**Comment by tobiasKaminsky** [comment]
Strange, I thought our http library is not capable of IPv6?

**Comment by AndyScherzinger** [comment]
we aren't capable of ipv6 but I thought @mario already fixed this issue which is not really a double upload but some id sending issue...
