### ISSUE TITLE
Implement background image cache

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#1623]
implement a background image cache like it has been done for avatars, see #1621 and please see also  #1595

**Comment by codedsun** [comment]
can I work on this issue?

**Comment by AndyScherzinger** [comment]
Absolutely @codedsun 👍

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger if #1595 is closed, this should also be closed, or?

**Comment by mario** [comment]
Yup, closed.
