### ISSUE TITLE
Settings background is greyish instead of white

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/android#1624]
The background color of the Settings is a slight grey. All background colors (except when viewing images of course) should be white though.

EDIT: Andy -> changed description to all backgrounds should be white.

**Comment by AndyScherzinger** [comment]
All background colors except for viewing images should be white imho ;)

**Comment by mario** [comment]
Well, the issue subject does say white :D

**Comment by AndyScherzinger** [comment]
I know but the description said black. So just clarifying :)

**Comment by jancborchardt** [comment]
:D Sorry, miswrote. Thanks @AndyScherzinger ;)

**Comment by codedsun** [comment]
Can i work on this issue?

**Comment by AndyScherzinger** [comment]
Absolutely @codedsun 👍

**Comment by codedsun** [comment]
@AndyScherzinger I have an issue regarding the setting up for project , the issue
 Error:This Gradle plugin requires Studio 3.0 minimum
I ran the ./gradlew clean build but still it shows the error.

**Comment by mario** [comment]
You need to install android studio 3

**Comment by rizal-rovins** [comment]
Is it solved or can i work on it ?

**Comment by codedsun** [comment]
@rizal-rovins  I m working on it..

**Comment by KingIdee** [comment]
Uhmm.. Where is the settings page -_-

**Comment by AndyScherzinger** [comment]
@KingIdee drawer menu item at the bottom of the main menu :)

**Comment by KingIdee** [comment]
I meant on the repo. Thanks

**Comment by AndyScherzinger** [comment]
Here: https://github.com/nextcloud/android/blob/master/src/main/java/com/owncloud/android/ui/activity/Preferences.java

**Comment by codedsun** [comment]
@AndyScherzinger  I am still getting error in setting up the project 

Error:Unable to resolve dependency for ':@modifiedDebugAndroidTest/compileClasspath': Could not resolve com.android.support:multidex-instrumentation:1.0.2.
<a href="openFile:/home/suneetsri/Desktop/Fest/android/build.gradle">Open File</a><br><a href="Unable to resolve dependency for &#39;:@modifiedDebugAndroidTest/compileClasspath&#39;: Could not resolve com.android.support:multidex-instrumentation:1.0.2.">Show Details</a>


Error:Unable to resolve dependency for ':@gplayDebugAndroidTest/compileClasspath': Could not resolve com.android.support:multidex-instrumentation:1.0.2.
<a href="openFile:/home/suneetsri/Desktop/Fest/android/build.gradle">Open File</a><br><a href="Unable to resolve dependency for &#39;:@gplayDebugAndroidTest/compileClasspath&#39;: Could not resolve com.android.support:multidex-instrumentation:1.0.2.">Show Details</a>

**Comment by codedsun** [comment]
@mario  need help !

**Comment by mario** [comment]
@codedsun master? Try to run gradle refresh.

**Comment by AndyScherzinger** [comment]
@codedsun are you running Android Studio 3.0 beta7 ?

**Comment by codedsun** [comment]
@AndyScherzinger yes

**Comment by codedsun** [comment]
@mario  I tried same issue

**Comment by tobiasKaminsky** [comment]
Do you have some kind of firewall / internet connection problems? 
On gradle start it tries to download the newest dependencies and for me it seems like fetching this is not working.
Can you have look into gradle console and/or event log, both are on lower right.

**Comment by codedsun** [comment]
I am still not able to setup the project :( facing issues ! could anybody connect with me on irc or some other chat providers?
Kindly drop ur email or username

@mario @AndyScherzinger @tobiasKaminsky

**Comment by codedsun** [comment]
@mario could u please help me on the setup of this app

**Comment by mario** [comment]
@codedsun Android studio 3.0 RC1 + git clone and it should work. Anything else, it's a local problem that I'm afraid we can't debug :-/

**Comment by AndyScherzinger** [comment]
This issue itself is resolved via the merged  #1690  so let's keep the issue itself also closed. Dev env setup is not related to the original issue described here :)
