### ISSUE TITLE
Typo in AuthenticatorActivity Spanish version

### ISSUE THREAD

**Issue by gab07** [nextcloud/android#1628]
### Actual behaviour
The app shows this:
¿No tienes todavía un servidor?ulsa aquí para conseguir uno de un proveedor

### Expected behaviour
¿No tienes todavía un servidor?
Pulsa aquí para conseguir uno de un proveedor
 
### Steps to reproduce
Just run the app for first time in a device in Spanish

Btw there is a test server or I have to get my own?

**Comment by AndyScherzinger** [comment]
Thanks for the report @gab07 👍 - I fixed the translation on Transifex right away: https://www.transifex.com/nextcloud/nextcloud/translate/#es/android/91098307 This will thus be fixed in the next release of the app.

If you need a test server you can checkout https://demo.nextcloud.com/
