### ISSUE TITLE
Changing back to "all files" should go to latest folder

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#163]
### Actual behaviour
- root folder is shown

### Expected behaviour

- folder A/B/C is shown
 
### Steps to reproduce
1. go to folder A/B/C
2. drawer -> on device
3. dawer -> all files

**Comment by AndyScherzinger** [comment]
Can't you only switch between them in the root folder anyways?!

**Comment by tobiasKaminsky** [comment]
A/B/C are subfolders or what do you mean?
I just wanted to point out that I am deep in the hierarchical file system and do not want to navigate back to this just because I have switched between on device / all files.

**Comment by AndyScherzinger** [comment]
I meant that the switching is in the drawer which is only accessible in the root folder.

**Comment by tobiasKaminsky** [comment]
Damnit :/ :/
This is working.
What I meant is that if I am in a sub/sub/subfolder and switch to uploads and back to "all files" I am in the root folder.
But I figured out that I can click back when in uploads and then I am in the previous folder.

So...very confusing from me...and closing ;)
