### ISSUE TITLE
Opening files in dev beta app does not work

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/android#1630]
You only get "Sorry, there is no local fule to preview" as empty content view. Same for multiselect downloading.

Previews and normal navigation works fine.

It works in the normal app of course.

**Comment by Sjaak-d1** [comment]
Hi Tobias,

Sorry to hayjack this topic, but i have the same issue.

I tryed the 5 latest dev versions all have the same error " sorry there is no local file to view"
Downloading works its only when view resized image is cheched.

Also even in expert mode there are no logs made.
I see that "83f870fe7266e2240708bf95167223b16772c259" (fix 1660) had an error in the commits list.
Maby thats the problem with the logs.

For referance:
I have a oneplus3 on beta 7.1.1
Storage path set to "storage/emulated/0/Android/media/com.nextcloud.beta

**Comment by tobiasKaminsky** [comment]
@jancborchardt @Sjaak-d1 is this still happening for you?

**Comment by Sjaak-d1** [comment]
Hi tobias, as of dev version 20171127 it was solved for me. Havent been able to test newer versions
