### ISSUE TITLE
Can't connect over WAN

### ISSUE THREAD

**Issue by behgonn** [nextcloud/android#1636]
### Actual behaviour
Android App from Fdroid version 2.0.0RC7 can't connect to my Server over WAN. LAN is ok,with Browser i can connect over both LAN and WAN. Windows App and iOS App works without problems.  

### Expected behaviour
Android App should connect over WAN. 
 
### Steps to reproduce
1. I have the Account connected in LAN
2. Change to Mobile WAN and start tge App. 
3. Can't connect. 

### Environment data
Android version:
7.1.1
Device model: 
Sony Xperia Z Compact - E5823
Stock or customized system:
Original Sony
Nextcloud app version:
2.0.0RC7 from Fdroid
Nextcloud server version:
12.0.3

**Comment by xXSTrikeXx** [comment]
Did you configured the account on LAN? Try to register your accont over WAN in the App. Just to prevent you´re using a LAN IP.

**Comment by behgonn** [comment]
I use a ssl Domain over wan and lan, i can't get a connection over wan to login.

**Comment by xXSTrikeXx** [comment]
What kind of server use you? Did it worked before over WAN in some of the other app versions? Portforwarding activated?

**Comment by behgonn** [comment]
I have a 2.4 Apache Web Server.  I wrote above that all applications work over LAN and WAN this include Windows Client and the iOS App. Only the Android App can't get a connection over WAN. Over the Webbrowser with Android i get a connection, only the App is not working.

**Comment by xXSTrikeXx** [comment]
Does it work with latest RC8?

**Comment by behgonn** [comment]
I did the update to RC8 some minutes ago, still the same issue.

**Comment by AndyScherzinger** [comment]
@behgonn can you check the Nextcloud brute foce database table and remove all entries within? One issue might be that your device has been blocked.

**Comment by behgonn** [comment]
Hi, i knew that i cleared this table one or two times ago. But it didn't worked because i get blocked again i think.

Because i can't login remote to the Server at the Moment i tryed a free vpn and it worked.

So i think the solution would be to disable the brutforce blacklist, is this possible?

Thanks for the help!

**Comment by AndyScherzinger** [comment]
That I don't know...server know how... pinging @nickvergessen @MorrisJobke

**Comment by behgonn** [comment]
The big question at this point is how is it possible that the bruteforce blacklist block the app but don't block the login via browser/web, it's the same IP, and it's a mobilephone i get every time a new ip when i start the phone or connect it bag to 4G. Questions over Questions.

**Comment by nickvergessen** [comment]
You can whitelist ips with https://github.com/nextcloud/bruteforcesettings so they are not throttled anymore, does this help?

**Comment by tobiasKaminsky** [comment]
in config.php
> 'auth.bruteforce.protection.enabled' => false,

Though this will not help to solve the underlying problem

**Comment by behgonn** [comment]
I will try the whitelist later in the Office, but i can't and nobody should whitelist changeing ip's from mobile provider, than makes the brutforce blacklist no sense.

I will post the results but also change the brutforce in the config to false, thanks for this advice!

**Comment by j-ed** [comment]
If the Nextcloud server is reachable over the Internet using a web browser, the general access should be fine (including the blacklist and firewall settings). Very often DNS resolution differs between LAN and mobile Internet access. It might be worse to try to set-up the Nextcloud account in the app over the Internet to get more detailed messages, like if the server is reachable etc. 
Additionally It might be necessary to install the CA certificate on your android phone to make sure that the server certificate can be verified. I'm not having any problem connection to a Nextcloud instance over the Internet, using the latest 2.0.0 RC9 release. The previous versions also worked as expected.

**Comment by behgonn** [comment]
So thanks for all your help. I found out that the nameserver from my isp had a wrong ipv6 dns entry to my server. Problem solved.

Maybe the app could ignore ipv6 when there is no server answer and switch to ipv4? The iOS App worked well, maybe they didn't work with ipv6?

Thanks and greetings
