### ISSUE TITLE
Activity section design details

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/android#1639]
Currently the Activity section looks like this:
![screenshot_2017-10-03-19-25-35](https://user-images.githubusercontent.com/925062/31353776-228cdbbe-ad34-11e7-8b82-6600a98261d5.png)

To make it look more in line with the Nextcloud style, here’s some detail fixes:
- [x] The big headings should not repeat the small detail timestamp. The first one is »Today« (if any), followed by »Yesterday« (if any), followed by the date like »Saturday, October 7«, then »Friday, October 6« etc and so on (also include the year as soon as the event history goes to last year)
- [x] The links should have no underline, bolding is enough
- [x] The link color can be black instead of the Nextcloud blue / primary color as it looks quite out of place. What do you think @nextcloud/android?
- [x] In the web interface we have 50% opacity on all of the action icons on the left since they are a bit too overpowering otherwise.
- [ ] Of course it would be great to have avatars of the other people in this view left next to their name. :)

**Comment by tobiasKaminsky** [comment]
The relative date string is limited to specific date ranges, so it will be relative for the whole last week:
today, yesterday, 2..6 days ago, Oct 10. Year will be added automatically if it is last year.

![2017-10-12-115326](https://user-images.githubusercontent.com/5836855/31490373-fdffedba-af43-11e7-8c4b-05e59d386fbb.png)

Regarding avatars: I would open up a new issue for this, so we then can close this if you are satisfied with the current state.

**Comment by AndyScherzinger** [comment]
merged for 2.1.0 🎉
