### ISSUE TITLE
Bug with photo export

### ISSUE THREAD

**Issue by kendael** [nextcloud/android#1642]
### Actual behaviour
The export function doesn't work well. I can't download the file on my device. It seems the bug comes from the type MIME misdetected when the extension is in uppercase.
See android/src/main/java/com/owncloud/android/utils/MimeTypeUtil.java, this code is case-sensitive (won't work with uppercase).

### Expected behaviour
When I click the export link, Android should suggest me to copy the file on my device. 
 
### Steps to reproduce
1. Sync a jpg file with the extension in uppercase (.JPG)
2. Try to export it with the app

### Environment data
Android version: 7.0

Device model: Honor 8

Stock or customized system: Stock

Nextcloud app version: 1.4.3

Nextcloud server version: 12.0.3

**Comment by AndyScherzinger** [comment]
@kendael what do you mean by export link? Just tried this with "send" and "share" for *.JPG and this works fine with 2.0.0RC9

**Comment by kendael** [comment]
The Send or Share function allow you to share a link (public or private) to the file in the Nextcloud server. The export function is the one that allow us to download the file on the phone or share it via Whatsapp  (for example) without generating a link.
Here what I do : long click on the file, click "menu" button, click on "Export"
Some applications are not suggested, others don't work (for example Keep or Whatsapp).
I think the problem comes from the MIME type required by some apps to manage files.
By reading the code, I understand that the MimeTypeUtil.determineMimeTypesByFilename function isn't case insensitive returning "application/octet-stream" by default or depending on Android detection.

**Comment by AndyScherzinger** [comment]
👍 now I understand and could replicate it in a test with an .JPG and whatsapp!

**Comment by kendael** [comment]
Nice !

**Comment by AndyScherzinger** [comment]
@kendael I just retested everything and it works like a charm (tried Google Photos, Instagram, etc.). What doesn't work is Whatsapp and I debugged the code the mimetype is set correctly to image/jpeg so it seems it is Whatsapp that can't handle the uppercase (which seems weird...)

**Comment by AndyScherzinger** [comment]
hmmm..... Amaze file explorer is able to share the file.... will need to further investigate...

**Comment by kendael** [comment]
I think some apps use the file extension while other use the MIME type. That's why it works for many of them but not all. Google Keep doesn't work either.

**Comment by mario** [comment]
@AndyScherzinger can you check this with my branch? https://github.com/nextcloud/android/pull/1651

**Comment by AndyScherzinger** [comment]
I am on a workshop. Maybe next week... cc @tobiasKaminsky

**Comment by mario** [comment]
Can you try @tobiasKaminsky please? Thanks! :)

**Comment by tobiasKaminsky** [comment]
Works on latest master/3.5.0.
