### ISSUE TITLE
Many wakeups due to Nextcloud app

### ISSUE THREAD

**Issue by eloo** [nextcloud/android#1647]
### Actual behaviour
- Wakelock Detector is showing over 180 WakeUps from Nextcloud during the last 3 hours. Further some nextcloud notification popup and icon is showing up for some millis.

### Expected behaviour
- Less wakeups and no annoying short notification "popup".
 
### Steps to reproduce
1. Install and configure Nextcloud app
2. Enable instant upload (not sure if this is necessary) 

### Environment data
Android version: 7.1.2

Device model: OnePlus X

Stock or customized system: LineageOS

Nextcloud app version: 2.0.0 RC8

Nextcloud server version: 12.0.3

**Comment by mario** [comment]
How does it affect battery though? We have to wake up if we want to make sure we upload a file...

This is indeed related to auto upload...

**Comment by eloo** [comment]
I didn't see nextcloud in the bat stats so it doesn't influence battery life directly but i think every wake up will cause deepsleep to be interrupted. which may cause battery drain by the system itself.
And what do you mean with "make sure we upload a file"? is this the check if there is a new file to upload?
If this is so maybe it would be great if we could change the interval this check is done. in my case every 15 min would be enough. further it seems that this is done if i'm using mobile data but i've configure my instant upload to use only wifi.
what do you think?

**Comment by mario** [comment]
180 wakeups does sound a lot o.O We do check every 15 mins or when you take a photo/video.

**Comment by eloo** [comment]
Yeah that was i thought too.
but it seems that something is not working properly.. 
as said the flashing notification icon is seen in a way higher rate than once in 15 minutes

in the attachment you can see the stats for today nearly 800 times in 15h
i guess this should not be the case :D
![screenshot_20171011-222833](https://user-images.githubusercontent.com/2631895/31465237-a7629f90-aed3-11e7-92e8-c70557850d84.png)

**Comment by tobiasKaminsky** [comment]
I have slightly higher numbers 😨  ;-) ;-)
But I do not experience any flashing notification icon with my oneplus 3.
![screenshot_20171012-090420](https://user-images.githubusercontent.com/5836855/31483468-d08ce188-af2c-11e7-9cb0-79763642c780.jpg)

**Comment by eloo** [comment]
Oh yeah, but i see you're in the CPU wakelock view. 
The view i'm talking about is the WakeUp-Trigger view.
And the flashing icon is not the whole time present.. it sometimes appear for a period of time and then it stays gone for a while..

**Comment by tobiasKaminsky** [comment]
On WakeUp-Trigger, I have 0 for Nextcloud dev/RC9 and I have 7 auto upload folders configured.

**Comment by eloo** [comment]
okay.. i will give RC9 a try ;)

**Comment by supermamie** [comment]
Attached is a screen capture of this kind of "very fast notification".
They appears often, and always multiple time when the network is switched (wifi on or off for example)

[ScreenRecord.zip](https://github.com/nextcloud/android/files/1379659/ScreenRecord.zip)

I'm using Nextcloud 2.0.0RC9

**Comment by mario** [comment]
I believe this is the Upload service turning itself on to check if there's anything to upload....

**Comment by mario** [comment]
@supermamie thanks for the video!

**Comment by Abyss777** [comment]
I'm using 2.0.0 from Google Play and also see 1500 wakeups during 15 hours.
Auto upload is configured, if I disable it does not help.

**Comment by marvinwankersteen** [comment]
Same here with OnePlus 5 with OxygenOS 4.5.12 and Nextcloud 2.0.0 from Google Play.
I configured the display that it will wake up if a new notification comes in. I can't tell how many times, but the display switches very often on.

**Comment by daemongloom** [comment]
Latest version from Google Play. Samsung A7 2017 (Android 7.0)
16672 wake-ups from Nextcloud during 8 hours. That's definitely not good.
