### ISSUE TITLE
Hide hidden folders & files in uploads view

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/android#165]
See https://github.com/nextcloud/android/pull/152#issuecomment-235889677

We should hide those by default. Maybe we can add a 3-dot menu with a checkbox entry »Show hidden files« to show them as we do in the web interface.

**Comment by AndyScherzinger** [comment]
Some questions do get a better understanding of this... details ;)
* What characterizes a hidden file? 
* Everything starting with a dot? 
* Does this also apply for hidden folders (in case we have something like that) too?
* What is meant by uploads view: view to choose what to upload or view to choose where to upload to? (unfortunately both are called upload views at the moment, plus we have the upload view showing you the files that have been uploaded (in the drawer menu)...)

**Comment by jancborchardt** [comment]
Starting with dots, yes. What’s the logic on the server @Morris @schiessle?
And yes, both folders and files. And any view I would say. Even when browsing your own files. Then the »Show hidden files« could be in the 3-dot-menu in any view.

**Comment by jancborchardt** [comment]
(Off by default, hidden files should be hidden of course.)

**Comment by AndyScherzinger** [comment]
@jancborchardt so to be consistent with the server or rather with the web UI should we than just also put this into the settings instead of the menu on the different views?

**Comment by schiessle** [comment]
@AndyScherzinger just to avoid confusions. It is not in the global setting menu (admin or personal settings) but in the files app setting at the bottom left:

![menu](https://cloud.githubusercontent.com/assets/1589737/17218747/34b29f1c-54e9-11e6-954d-6e062615a4a7.png)

I think it is important that the setting is at a place where people can access it easily to toggle the state without leaving the current folder.

**Comment by AndyScherzinger** [comment]
I'd say in the settings screen. Putting it in the menu seems like a too prominent place for an action you probably only use once, never or every couple of weeks/ months. @jancborchardt ?

**Comment by pybizzle** [comment]
I'm not sure if this is expected behavior or not but the hidden files show up if you preform a search from any location via the web interface. I would expect most people to not want this to happen, is there a way to prevent hidden files/folders from being listed in a search?  I understand that the file will only be visible within your own searches unless it was shared for some reason, however for sensitive files it would be safer for them not to be listed in any search.

**Comment by AndyScherzinger** [comment]
changes have been merged and will be released with 1.4.0
