### ISSUE TITLE
NC 2.0.0RC8: Battery being drained while phone doesn't have internet access

### ISSUE THREAD

**Issue by OlivierS1** [nextcloud/android#1654]
### Actual behaviour
-Tell us what happens
While being away, I had trouble getting reliable internet access, it seems my http connection was working but everything related to https was being blocked.
Browsing with Firefox was not a problem but NC and Gmail were no go.
So in absence of connection, NC, but possibly SMS app linked to my server seemed to being the culprit in taking my phone down in a matter of a few hours. 4 or 5 hours seemed to be the time required to drain my phone from a full charge.
I came to the point where I disabled WiFi altogether but even that didn't stop the battery from being drained.

### Expected behaviour
-Tell us what should happen
 
### Steps to reproduce
1. 
2. 
3. 

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by mario** [comment]
Sounds strange? Does the same happen when you do have internet? :D

**Comment by OlivierS1** [comment]
No it doesn't, at least not at work nor at home.
One thing I should mention and I believe this is closely related to the following post:
[https://github.com/nextcloud/android/issues/1653](url)
One thing was an issue with the certificate.
At some point in time, I couldn't even browse the content of my account within the app, eventhough I had files which were already "synchronized" (downloaded).
The account I was using was recently created for the purpose of this trip and only a handful of files were present, so no issue with memory limitation in any way.
However, all I was getting from this account was absence of every folders and documents (5 folders or so and about 10 files, including default Nextcloud default pictures and documents).
I should also mention I had automatic upload enabled and I did take a picture at some point, but I believe it was already late in the day and battery was already around 15% and dropping.

On my day to day live, my phone will normally drop around 3-7% overnight when phone is left alone.
I constantly use GPSLogger and the lack of GPS coverage shoulnd't really affect the performance, but moving around could have an effect as it accounts for Gyro and acceleration interrupts.

At the end, I still suspect this is something related to certificate request and managing local and remote files.
As mentioned earlier, I am using "Nextcloud SMS" and I did find peculiar the number of failed events related to SMS synchronization but then again I have it set to 15 minutes, so maybe it is just fine. It would just try to update when I start using my phone (accessing the lock screen).

This is a lot of unknown and possible feature interaction that are causing such issues. Tough one to evaluate and debug.

**Comment by tobiasKaminsky** [comment]
Meanwhile we enhanced the app. Can you please try and report back if the bug still exists on latest official version in conjuction with latest server or even try our [dev version](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#dev-release)?
