### ISSUE TITLE
No log in app v2.0.0rc7

### ISSUE THREAD

**Issue by Mickael-Martin** [nextcloud/android#1656]
### Actual behaviour
When I go to logs in settings (Journaux in my french version), nothing appear. I just have Clear logs and send logs buttons. Clear logs go to the precedent view and send logs no attach any attachments.

### Expected behaviour
Select logs in settings should display all logs of the application. Send logs button should attach logs.
 
### Steps to reproduce
1. Open the app
2. Go to the settings view
3. Select logs
4. No log displayed

### Environment data
Android version: 7.1.2

Device model: Nexus 4

Stock or customized system: LineageOS 14.1

Nextcloud app version: V 2.0.0RC7

Nextcloud server version: 12.0.3

#### Web server error log
```
Nothing (no action on web server)
```

#### Nextcloud log (data/nextcloud.log)
```
Nothing (no action on web server)
```
#### logcat log
```
Nothing special (no error)
```
![screenshot_20171011-134657](https://user-images.githubusercontent.com/1871792/31439610-1b37d6fc-ae8d-11e7-9574-a1c623a307a9.png)

**Comment by xXSTrikeXx** [comment]
its already implemented? Nevertheless it's a good Enhancement. I think only for the beta channel.

**Comment by tobiasKaminsky** [comment]
Log entry is shown in these cases
- logger_enabled in setup.xml (disabled for regular releases, including RCs)
- debug build 
- expert mode is turned on
(https://github.com/nextcloud/android/blob/90dc587300112df067962da9f3d7cb84af5d7621/src/main/java/com/owncloud/android/ui/activity/Preferences.java#L475-L475)

But logger is starting only on debug build (nextcloud dev):
https://github.com/nextcloud/android/blob/329bccd51439705520e153cd53aec21ae4aa8e58/src/main/java/com/owncloud/android/MainApp.java#L122-L122

So this should be aligned:
- In line 122 add the other two cases
- enabled/disable logging when enabling/disabling expert mode

**Comment by mario** [comment]
Working on this.

**Comment by Mickael-Martin** [comment]
OK I understand. But :
I have no log in expert mode
I have the same issue with the dev version (20171010) in expert mode or not

**Comment by mario** [comment]
I just fixed this, so please wait until we merge PR
