### ISSUE TITLE
Activity is always empty

### ISSUE THREAD

**Issue by ldmpub** [nextcloud/android#1661]
### Actual behaviour
Activity is always empty even when file downloads are in progress.

### Questions
Is it the designed behaviour? I guess not, for instance see #1639.
What kind of info should be displayed under Activity entry in the Android Sync Client? Why can it be empty?

**Comment by tobiasKaminsky** [comment]
Which app version do you use?
There is a bug, which shows an empty list if you had previously changed your password, as then the content could not properly displayed.
It should show the same as the activity stream on web UI.

**Comment by ldmpub** [comment]
Ok bug confirmed:
- Activity is not empty in the web UI (and I had never changed my cloud password)
- Android app version : 2.0.0RC9.

**Comment by tobiasKaminsky** [comment]
Can you create a test user on your server and see if it also failing there? 
If so, please write then an email with the credentials to android at nextcloud dot com (of course only if you are fine with temporally sharing it to us).

**Comment by ldmpub** [comment]
Answers to your questions and additional info:

- I can not create a new (test) user on the server easily because I'm just an "end-user" (I use a free Nextcloud provider at https://framadrive.org ... maybe you can check the server version there).

-  But I confirm that Activity is always empty in the Android App despite I have done a lot of file operations which are visible in the Web UI Activity.

PS: if needed I can give you my personal credentials by "private" mail, because my cloud account contains only podcasts (public MP3 files) I'm listening to.

**Comment by tobiasKaminsky** [comment]
@ldmpub if you can send me your credentials this would be awesome (android at nextcloud dot com with a reference to this issue.

**Comment by ldmpub** [comment]
Done ;-).

**Comment by tobiasKaminsky** [comment]
Just a quick follow-up:
The circle app is sending a "wrong" activity info and therefore we fail on parsing it.
I will test a new circle app soon. If this is working a new version will be released which solves it, without need of a new android version.

**Comment by ldmpub** [comment]
Thanks for this feedback.
(even if it's not clear for me what the "circle app" is, does it mean the Nextcloud server will have to be updated to fix this issue?).

**Comment by tobiasKaminsky** [comment]
https://apps.nextcloud.com/apps/circles 

In your activity stream there is on 21.10:
> "￼$USERNAME a créé le cercle $CIRCLE_NAME"

And this is causing the trouble right now.
It should then be enough to upgrade to a newer circle app version.

**Comment by tobiasKaminsky** [comment]
Circle app version 0.13.6 is now available which should fix this problem.
Can you please login as admin and do an upgrade of the circles app and then reply if it is working for you?

**Comment by ldmpub** [comment]
Hi, update is planned on the server next week.
I will test after update with my current Android client and let you know the result here.

**Comment by tobiasKaminsky** [comment]
Good to know.
As this works with our internal tests, I'll close the issue.
Please re-open it if you experience the problem again.

**Comment by ldmpub** [comment]
Confirmed => Activity is now working.
Thanks!
