### ISSUE TITLE
Personalized app

### ISSUE THREAD

**Issue by Artapel** [nextcloud/android#1664]
Hi Guys. Is it in anyway possible to brand the app a bit. Id like to change the logos and color of the app?

Regards

**Comment by comradekingu** [comment]
@Artapel I suppose yes in every respect, for whom and in which way do you wish to make changes?

**Comment by Artapel** [comment]
@comradekingu I have been tasked to investigate a dropbox like solution for a small business. Having tested Nextcloud which ticked all my requirements, i only need to get it personalized.

- What i was thinking of changing is the icon being displayed on the mobile phone desktop,
- Changing the word nextcloud being displayed int he app
- Changing the color from blue to dark red
- Changing the logo to a logo that i can provide.

That`s about it. In actual fact im just looking to change the theme

**Comment by mario** [comment]
@Artapel you can either get a Nextcloud (support) subscription that includes branding (which means, we tweak the app for you) and support, or you can do it yourself, but it's definitely possible.

Let me know at mario@nextcloud.com if you'd like to talk about a subscription, and I can point you to the right people! :)
