### ISSUE TITLE
Don't try to autoupload when no connectivity

### ISSUE THREAD

**Issue by shtrom** [nextcloud/android#1666]
### Actual behaviour
-The application tries, and fails, to autoupload images when no connection is available (no Wi-Fi nor mobile; roaming or aeroplane mode).

### Expected behaviour
-The application waits for connectivity to be available.
 
### Steps to reproduce
1. Configure autoupload for photos
2. Set the phone to aeroplane mode
3. Take a picture

### Environment data
Android version: 7.1.2 

Device model: Hammerhead

Stock or customized system: Lineage OS 14.1 2017-08-22

Nextcloud app version: 2.0.0RC5

Nextcloud server version: 12

### Logs
Not relevant: application-side only.

**Comment by brjhaverkamp** [comment]
Same here. I am on 2.0rc9
The nextcloud icon keeps flashing in the taskbar. When I open notifications, I see it is spitting out warnings about attempts or failed uploads. But they fly by too fast to read fully. 
Worst is that it eats through the battery like crazy  in this state

**Comment by mario** [comment]
It doesn't actually try to upload, but it does start a service which then checks if all conditions (like network) are met.

**Comment by brjhaverkamp** [comment]
But it keeps flashing a list of messages while doing that. And battery drain was significant.
I was traveling and a week wo wifi when this happened.

**Comment by brjhaverkamp** [comment]
Added strangeness is thatcit kept trying to upload when I switched off autoupload. Not sure if this is related though. Might also be that only the pictures that were queued were retried.
![screenshot_20171013-234645](https://user-images.githubusercontent.com/3051118/31588771-f5cb5ca0-b1f6-11e7-8041-7ec451c02ee1.png)
![screenshot_20171013-234219](https://user-images.githubusercontent.com/3051118/31588773-fc5f3e06-b1f6-11e7-8798-dc1f1fd5ee2b.png)

**Comment by brjhaverkamp** [comment]
The screenshots are from when I returned back home and had wifi again, btw☺

**Comment by shtrom** [comment]
On Fri 13 Oct 2017 at 14:39:56 +0000, Bert wrote:
> Same here. I am on 2.0rc9

Yup, I upgraded to RC9, and still see the same thing.

-- 
Olivier Mehani <shtrom@ssji.net>
PGP fingerprint: 4435 CF6A 7C8D DD9B E2DE  F5F9 F012 A6E2 98C6 6655
Confidentiality cannot be guaranteed on emails sent or received unencrypted.

**Comment by jasonbayton** [comment]
It would be nice if I didn't see a flashing notification frequently when I've got autoupload limited to WIFI.

**Comment by mario** [comment]
I think this is fixed in master.

**Comment by jasonbayton** [comment]
Confirm and close?

**Comment by mario** [comment]
Well, somebody ought to test for sure :P It's part of the DEV release.

**Comment by mario** [comment]
Implemented.
