### ISSUE TITLE
Android app doesn't show user icon if user name contains whitespace

### ISSUE THREAD

**Issue by nursoda** [nextcloud/android#1667]
Bug opened as requested in https://help.nextcloud.com/t/solved-android-app-doesnt-show-user-icon-if-user-name-contains-whitespace/22217 by Andy:

### Actual behaviour
I have several accounts with profile photos. Only for the account with a space in the username, the profile photo is not shown in the app. It’s shown on the web. The same photo is shown in a test account (without whitespace in its user name) when I upload the identical file.

### Expected behaviour
Profile photo should be shown in app, too.
 
### Steps to reproduce
1. create a user with whitespace, such as "maidenname surname".
2. assign a profile photo to that user.
3. add that account to the app. Profile photo is not shown.

### Environment data
Android version: 7.1.1
Device model: OP 3T
Stock or customized system: stock OOS
Nextcloud app version: 1.4.x and 2.0 betax
Nextcloud server version: 12.0.3

### Logs
Please request which logs you need. But you should be able to reproduce yourself easily ;-)

**Comment by AndyScherzinger** [comment]
pinging @tobiasKaminsky since you probably know the exact code part. My guess is it has something to do with escaping (missing)

**Comment by dougouk** [comment]
On the URL, it says this is [solved].. So should this issue be closed?

**Comment by nursoda** [comment]
I did not mark the forum thread solved, don't know who did. Probabl because it moved to this bug. It's NOT solved yet.

**Comment by mario** [comment]
We have a pull request that fixes it, and it will be in 2.1.
