### ISSUE TITLE
Autoupload only with know WiFi-Networks

### ISSUE THREAD

**Issue by Bigdesaster** [nextcloud/android#1683]
### Actual behaviour
- When connecting to a puplic WiFi (mostely they have low bandwith) nextcloud is trying to upload files.

### Expected behaviour
- Optionally set up a list of known network names and upload files only when connected to a network in list

**Comment by FolkyHobbit** [comment]
This would also be useful to me since my server is only accessible from within my home network.

**Comment by egeu5** [comment]
@FolkyHobbit I think that are different things which should be solved by different solutions: 
If a phone is in a wifi with limited access (like at work, in some countrys or if a server is just accessible by local ip) the client should notice that and wait until the server is accessible.

**Comment by klawdhfzasjhaa** [comment]
In DAVDroid, you can tell it to sync only when connected to a given SSID. Maybe this can be used here, too. https://gitlab.com/search?search=SSID&group_id=&project_id=447145&search_code=true&repository_ref=master-ose

**Comment by joshtrichards** [comment]
Let's consolidate tracking this in #821. I encourage you to subscribe, add to the discussion, and/or upvote 👍 that issue.
