### ISSUE TITLE
Auto uploads replaces files with the same name. 

### ISSUE THREAD

**Issue by TheRealChriAnd** [nextcloud/android#1685]
### Actual behaviour
-If using auto upload and a file already exists with the same name, the file will get replaced. 

### Expected behaviour
-In the earlier version the files with the same name got a changed name marked with a number at the end. Something like this "photo.jpg" and the new file would then get the name "photo (1).jpg" 
 
### Steps to reproduce
1. Upload a picture with auto upload 
2. Delete the local file on your phone 
3. Take a new picture and name it as the last one. 
4. Let auto upload, upload the new picture. 
5. The picture has now replaced the last picture stored in nextcloud. 

### Environment data
Android version: 7.1.1

Device model: Sony xperia xz premium 

Stock or customized system: stock

Nextcloud app version:2.0

Nextcloud server version: 12

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by mario** [comment]
Thanks. Explanation and discussion here: https://github.com/nextcloud/android/issues/1686

**Comment by AndyScherzinger** [comment]
closing this issue in favor of the mentioned #1686
