### ISSUE TITLE
Nextcloud app flashes notifications

### ISSUE THREAD

**Issue by kaymes** [nextcloud/android#1687]
### Actual behaviour
Since the latest update of the Nextcloud app, it seems to repeatedly flash notifications for fractions of a second.

The notification shows up as both, a notification itcon on the top left corner of the screen as well as a "proper" notification bar across the screen that shows up when the phone is locked.

The flash is so short, that it is impossible to see the content. The notification bar doesn't even complete its animation before disappearing. However, the icon is shown just long enough to make out the Nextcloud logo.

When I "force stop" the Nextcloud app, the flashes disappear. When I then launch the app again, the flashes start again.

### Expected behaviour
Notifications should either be long-term if important or not shown at all.
 
### Steps to reproduce
1. Have the Nextcloud app installed
2. Observe notifications flashing up.
3. 

### Environment data
Android version:
7.1.1

Device model: 
Sony Xperia Z5 Compact E5823

Stock or customized system:
Stock as shipped by Sony

Nextcloud app version:
2.0.0

Nextcloud server version:
12.0.3

**Comment by xXSTrikeXx** [comment]
@mario has planned to have atleast no notification. So do you really want to be informed by every upload?

**Comment by kaymes** [comment]
I rather not be informed too much. However, at the moment, the app isn't even informing. The icon briefly shows up and a notification starts to animate in and then disappears before the animation hasn't even stopped. This is happening quite often (every few seconds to 1 minute) while there are no changes to the data on the server or locally. Something seems to be broken.

**Comment by AndyScherzinger** [comment]
@jancborchardt can you add @xXSTrikeXx to the orga please? :)

**Comment by jancborchardt** [comment]
> can you add @xXSTrikeXx to the orga please? :)

@AndyScherzinger done, added to the org and Android team. :)

**Comment by AndyScherzinger** [comment]
Thanks a lot @jancborchardt ❤️

**Comment by eknoes** [comment]
I have the same issue on Android 7.1 with the Xperia X Compact.

**Comment by mario** [comment]
This is a know "issue". It'll be fixed in one of the future versions, but not soon as it requires rewiring/rewriting the transfers mechanism, and that in itself would be worthy of 3.0, ignoring all other features we're working on.

**Comment by juju95** [comment]
Same problem here, i'm using nextcloud for now couple of months, and this bug is new for last days
But labeling it an enhancement instead of bug ... and planning to correct it only in version 3 ? :'(
Le bug of the icon flashing is ... al the time, every second or 2 seconds all day ... not good for battery too ... :(
I will remove the Android app and use the web view for the next months until this BUG is corrected :(

**Comment by tobiasKaminsky** [comment]
@mario where does this come from? Is it because of the jobs? 

> all the time, every second or 2 seconds all day

For me it does not happen, but we should try to fix it faster, maybe even with a workaround, if possible.

**Comment by juju95** [comment]
for my part, i can't tell you why, we just see the icon aparring and instantly disapearing from top toolbar, so no way to know what is the corresponding message / notification, seems empty

**Comment by mario** [comment]
@tobiasKaminsky this is a notification from an upload service because it stays in foreground. The "workaround" is not to rely on a service :)

**Comment by kaymes** [comment]
I don't know much about the code. But maybe the workaround could be something like stopping the service when it is no longer needed (i.e. when the app is not in the foreground and no longer uploading anything).

**Comment by mario** [comment]
The service is stopped when it's not doing anything. But currently, do add a file to upload queue or retry, we have to start the service.

**Comment by andreasmn** [comment]
I'm very annoyed by this behavior, too.
Seems that this happens if files are in the upload cue and are waiting for wifi connection.

**Comment by AndyScherzinger** [comment]
@mario could we use a transparent icon for the "stay in foreground" notification so that is not flashing in the system bar while keeping the app's notification icon for the notification where we display the upload progress?

**Comment by eloo** [comment]
is this maybe related to #1835 and #1647 ?

**Comment by jospoortvliet** [comment]
At least insofar that fixing https://github.com/nextcloud/android/issues/1835 will take care of at least part of this.

**Comment by AndyScherzinger** [comment]
@mario @tobiasKaminsky I think this issue is now fixed with latest 3.0.0RC3 release, isn't it?

**Comment by tobiasKaminsky** [comment]
@mario can this be closed?

**Comment by mario** [comment]
Yes, I think this is fixed.
