### ISSUE TITLE
Server Unavailable, but webserver shows requests with status 200 or 404

### ISSUE THREAD

**Issue by muellert** [nextcloud/android#1697]
### Actual behaviour

I'm trying to upload my photos to my PC on the local network (gmtp doesn't work - don't ask). NC dev fails with "Server unavailable", but when I navigate the app, many requests are shown from my phone - the only client - with benign status codes. Files are not being uploaded after having uploaded ~1100 (out of ~6500). When I am trying to search the file mentioned below, 20160322_154857.jpg, in the web interface, it is not there, so the 404 is expected by me, but I'd rather expect the app to upload the file.

### Expected behaviour

I expect that local folders are being scanned and then all files which are not present on the server, are being uploaded (I configured Auto Upload for these local folders).

### Steps to reproduce
1. I have no idea  how to reproduce this.
2. 
3. 

### Environment data
Android version:

5.0

Device model: 

LG 3

Stock or customized system:

stock

Nextcloud app version:

20170930

Nextcloud server version:

12.0.3

I'm running Debian stretch/amd64 with PHP 7.0 (FPM) under nginx, using the config from the nextcloud website, if it helps. I also have Pg 9.6 and Redis configured.

I enabled "Advanced" options in the Settings menu, and got a 'Logs' entry, but which turned out to be empty.

#### Web server error log
```
192.168.2.125 - username [19/Oct/2017:18:44:23 +0200] "HEAD /nextcloud/remote.php/webdav/LG3/ HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Android) ownCloud-android/20170930"
192.168.2.125 - username [19/Oct/2017:18:44:23 +0200] "HEAD /nextcloud/remote.php/webdav/LG3/20160322_154857.jpg HTTP/1.1" 404 0 "-" "Mozilla/5.0 (Android) ownCloud-android/20170930"
```

#### Nextcloud log (data/nextcloud.log)
```
There is no relevant entry in nextcloud.log.
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by xXSTrikeXx** [comment]
hi muellert.
It´s planned in future to have a stable 2-way-sync. atm it is only checking for recently taken photos.
refs #285 #1328

**Comment by danbulant** [comment]
Same thing happening to me.
Using website works, android app does not. It did in past. I'm still logged in but it can't upload nor download files.
