### ISSUE TITLE
All the favorites are displayed twice - refresh helps [2.0.0 RC9]

### ISSUE THREAD

**Issue by mr-bolle** [nextcloud/android#1698]
### Actual behaviour
- Every time if i open the favorites Page i see all items twice.

### Expected behaviour
- If i open the favorites page, i would only see every item once
 
### Steps to reproduce
1. open Nextcloud Add - select favorites > all items visible twice

### Environment data
Android version: 7.1.1

Device model: Sony Xperia Z5 dual

Stock or customized system: Stock ROM

Nextcloud app version: 2.0.0 RC9 & 2.0.0 (final 18.10.2017)

Nextcloud server version: 12.0.3

![favorites twice](https://user-images.githubusercontent.com/22414212/31784725-07396a54-b503-11e7-91ef-b43874047eff.png)

**Comment by zweiflamme** [comment]
That's exactly what happens to me - the same behavior is also reproducible with the Gallery. After a refresh, all items ore only shown once, as expected. Android 7.1.2 on a BB Motion, Nextcloud server is 0.53.24, Nextcloud App is 3.0.3

**Comment by zweiflamme** [comment]
Sorry, Nextcloud Server is 13.0.0.1 (I believe). Have installed NextCloudPi with the above v053, my apologies for the confusion.

**Comment by AndyScherzinger** [comment]
PR is #2490
