### ISSUE TITLE
Upload view: no thumbnail

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#170]
### Actual behaviour
- No thumbnail is shown
### Expected behaviour
- Show thumbnail
### Steps to reproduce
1.  Take a picture
2.  Go to upload view

Branch: master

**Comment by Hanzei** [comment]
Seems to be fixed on 1.4.2. Do you still encounter this issue @tobiasKaminsky ?

**Comment by AndyScherzinger** [comment]
Yes, I also have this with the master, well the mediaStoreAutoUpload branch.

**Comment by tobiasKaminsky** [comment]
It is working for me, but as @AndyScherzinger still has problems.
Do you do additional steps?

**Comment by AndyScherzinger** [comment]
My mistake, the thumbnails work for auto upload and for manual upload in general. 
Only thing still present is:

* activate auto upload
* take a picture and wait for it to be uploaded
* open app again and go to uploads view: you see the fallback image icon
* open another view like all files
* open uploads view again: thumbnail is shown

**Comment by tobiasKaminsky** [comment]
I cannot reproduce this, but #1004 and #671 will remain open.
