### ISSUE TITLE
AutoUpload Issues

### ISSUE THREAD

**Issue by YouTiao233** [nextcloud/android#1702]
Q:I setup the Autoupload but it doesn't upload?(Solved)
Q:Why it only Autoupload new img?
![image](https://user-images.githubusercontent.com/21272351/31845876-5bca7090-b5cb-11e7-88a2-79f1f0c257be.png)

### Environment data
Android version:7.0.0
Device model: MEIZU Pro 6 Plus

Nextcloud app version:2.0.0
Nextcloud server version:12.0.3

**Comment by AndyScherzinger** [comment]
Hi @YouTiao233 to answer your question

> Q:Why it only Autoupload new img?

This is what has been implemented up to now. Uploading existing images/videos created prior to activating auto upload is on the features roadmap: #285
