### ISSUE TITLE
menu favorites does not exists

### ISSUE THREAD

**Issue by ferdiga** [nextcloud/android#1706]
### Actual behaviour
no favorites menu

### Expected behaviour
favorites menu 
I think it should exists, because I saw some issues regarding favorites in git
 
BTW favorites should be accessible not only from Main Menu, but from the right menu to reduce the necessary steps

### Steps to reproduce
1. 
2. 
3. 

### Environment data
Android version: 6

Device model: 

Stock or customized system:

Nextcloud app version:
android 2.0
Nextcloud server version:
11.0.3

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by mario** [comment]
Favorites menu is only shown if you're running Nextcloud 12.

**Comment by ferdiga** [comment]
thanks
