### ISSUE TITLE
Push doesn't work

### ISSUE THREAD

**Issue by mario** [nextcloud/android#1707]
Unfortunately for majority of users automatic storage location detection doesn't work. As a consequence generating the nc-keypair directory and key pair doesn't work either.

Manually selecting one of the available locations fixes this, but the location should be detected automatically or we'll never have some things working (like push here!).

Only a few of our users receive push notification, and this is bad :(

cc @tobiasKaminsky @AndyScherzinger 

please try to look into it.

**Comment by tobiasKaminsky** [comment]
I have never worked with push. Can you give me a hint where to look at?
What do you mean with "available locations"?
Additional for me it works, so it is even harder to debug ;-)

**Comment by mario** [comment]
@tobiasKaminsky this is related to the Storage location in settings, not the push itself. For me it's set to /emulated/0 which is wrong (when I click to select it and select one of the two options, key can be generated and it all works).

**Comment by nickvergessen** [comment]
For me it is the same:
![screenshot_2017-10-24-11-59-24](https://user-images.githubusercontent.com/213943/31936846-0709f0b8-b8b3-11e7-985b-c378f7ec6a95.png)

Two valid options, but in the background you can see that it selected something invalid

**Comment by xXSTrikeXx** [comment]
![](https://i.imgur.com/xgAlP9M.png)

For me, but doesn't work

**Comment by tobiasKaminsky** [comment]
@mario is it correct that #1836 will fix this?

**Comment by mario** [comment]
Yes

**Comment by AndyScherzinger** [comment]
fixed via #1954
