### ISSUE TITLE
Proxy support in app 

### ISSUE THREAD

**Issue by user858753257** [nextcloud/android#1712]
Is there a solution to configure a proxy in the android app ?

**Comment by AndyScherzinger** [comment]
At this moment, no. There is a discussion here: #606 but "normal" proxies can be configured in NAdroid in the network settings itself...

**Comment by Spindletop** [comment]
Even without in-app support of proxy settings, there are problems using Android/system proxy settings:

- application does not support proxies which require authorization (browsers like Firefox for Android do support this) - **enhancement** as not many apps support this, even _davdroid_ as mentioned in #606 does not support this
- proxy exclusions ("Bypass proxy for") are ignored - clearly a **bug**. _davdroid_ as mentioned in #606 does support it. For reference, the problem still applies in Owncloud app: App uses Android proxy setting but ignores exclusions (https://github.com/owncloud/android/issues/793)

**Comment by joshtrichards** [comment]
Duplicate of #606
