### ISSUE TITLE
Photos upload didn't work

### ISSUE THREAD

**Issue by pbda** [nextcloud/android#1713]
### Actual behaviour
When I take a picture it is not uploaded

### Expected behaviour
With Owncloud apps, photo is uploaded.

 
### Steps to reproduce
1. Define automatic download for camera
2. Take a picture
3. Photo is not uploaded.

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by xXSTrikeXx** [comment]
Is it possible to give us some more information about your enviroment? 
App-version`? Device? ...
Login is still possible?

**Comment by pbda** [comment]
I apologize for incomplete report. More infos:
Android version: 6.0

Device model: Motorola Moto G (XT1079)

Stock or customized system: Customized (rooted)

Nextcloud app version: 2.0.0RC8

Nextcloud server version: 12.0.3

File sync is OK

**Comment by mario** [comment]
There is a stable 2.0 release, so please use that. Also supporting rooted systems is .... hard.

**Comment by xXSTrikeXx** [comment]
Well, please update to stable. If there the problems occur just reopen the issue.
