### ISSUE TITLE
dot menu wrong Translation (since 2.0.1 - German)

### ISSUE THREAD

**Issue by mr-bolle** [nextcloud/android#1715]
### Actual behaviour
- Since i update the App to 2.0.1 i see into the Dot Option Menü a wrong Translation, i use the german Lanuage and the delete funtion is visible into english Language.
I check the [Transiflex Translation](https://www.transifex.com/nextcloud/nextcloud/viewstrings/#de/android?qt=Delete) but can't find any mistake there.
 
### Steps to reproduce
1. Switch Language into German
2. Open the App and use the "dot menu" 
3. instead of 'Löschen', this function is now called 'Delete'

![26-10-_2017_19-06-44_new](https://user-images.githubusercontent.com/22414212/32066710-f76edb6c-ba80-11e7-99f2-c46fd0331e4b.png)

### Environment data
Android version: 7.1.1

Device model: Sony Xperia Z5 dual

Stock or customized system: Stock 

Nextcloud app version: 2.0.1

Nextcloud server version: 12.0.3

**Comment by tobiasKaminsky** [comment]
Thank you for the bug report.
This seems to be fixed on current master, so I will close it.
As this is such a minor bug I do not think it is necessary to release a 2.0.2 for this.

![2017-10-27-121010](https://user-images.githubusercontent.com/5836855/32099246-d8c36784-bb0f-11e7-85f3-69a7c7ede420.png)
![2017-10-27-121100](https://user-images.githubusercontent.com/5836855/32099262-e938e116-bb0f-11e7-9c3d-0ed1dd0bacfd.png)
