### ISSUE TITLE
Cannot set folders (local and remote) in autoupload settings

### ISSUE THREAD

**Issue by Mickael-Martin** [nextcloud/android#1716]
### Actual behaviour
I cannot change or select a folder in upload setting. When I select a local or a remote folder nothing appear in "Preferences for autoupload files" (sorry for translation, it's "Préférences pour le téléversement automatique").

### Expected behaviour
Folder's name are displaying as expected when selection is done.
 
### Steps to reproduce
1. Open app
2. Go to Autoupload settings
3. Select one local folder (or clic on manual selected local folder in the top*)
4. Selecting remote (or local + remote for case*) via opened window
5. Local or remote path aren't displaying on the new window and I have "Select a remote folder" (or "select the local folder" *) again. There are no change

### Environment data
Android version:
7.1.2
Device model: 
Nexus 4
Stock or customized system:
LineageOS 14
Nextcloud app version:
20171026 (but I have this issue since >2)
Nextcloud server version:

#### Web server error log
No error
Insert your webserver log here
No web server log (no remote call needed for local selection)

#### Nextcloud log (data/nextcloud.log)
Nothing special (no remote call)
Insert your Nextcloud log here
10-26 21:37:43.760   414   473 D JobRescheduleService: Reschedule 0 jobs of 1 jobs
10-26 21:37:44.855   414   414 D SyncedFoldersActivity: Show custom folder dialog
10-26 21:37:44.859   414   414 D SyncedFolderPreferencesDialogFragment: onCreateView, savedInstanceState is null
10-26 21:37:46.456 12394 17483 I ActivityManager: START u0 {cmp=com.nextcloud.android.beta/com.owncloud.android.ui.activity.UploadFilesActivity (has extras)} from uid 10231 on display 0
10-26 21:37:46.464   414   414 D SyncedFoldersActivity: onPause() ending
10-26 21:37:46.480   414   414 D UploadFilesActivity: onCreate() start
10-26 21:37:46.482   414   414 D UploadFilesActivity: onCreate(Bundle) starting
10-26 21:37:46.537   414   414 I LocalFileListFragment: onCreateView() start
10-26 21:37:46.537   414   414 D ExtendedListFragment: onCreateView
10-26 21:37:46.734   414   414 I LocalFileListFragment: onCreateView() end
10-26 21:37:46.804   414   414 D UploadFilesActivity: onCreate() end
10-26 21:37:46.805   414   414 D UploadFilesActivity: onStart() starting
10-26 21:37:46.806   414   414 I LocalFileListFragment: onActivityCreated() start
10-26 21:37:46.843   414   414 I LocalFileListFragment: onActivityCreated() stop
10-26 21:37:46.873   414   414 D UploadFilesActivity: onResume() starting
10-26 21:37:46.873   414   414 W DrawerActivity: setDrawerMenuItemChecked has been called with invalid menu-item-ID
10-26 21:37:46.877   414   549 D ExternalLinks: links disabled
10-26 21:37:47.076   414   414 D FileActivity: Operations service connected
10-26 21:37:47.163 12394 12454 I ActivityManager: Displayed com.nextcloud.android.beta/com.owncloud.android.ui.activity.UploadFilesActivity: +699ms
10-26 21:37:47.519   414   414 D SyncedFoldersActivity: onSaveInstanceState(Bundle) starting
10-26 21:37:47.535   414   414 D SyncedFoldersActivity: onStop() ending
10-26 21:37:47.568   414   414 D SyncedFoldersActivity: onDestroy() ending
10-26 21:37:47.568   414   414 D SyncedFolderPreferencesDialogFragment: destroy SyncedFolderPreferencesDialogFragment view
10-26 21:37:49.964   414   414 D UploadFilesActivity: onPause() ending
10-26 21:37:49.981   414   414 D SyncedFoldersActivity: onCreate(Bundle) starting
10-26 21:37:50.038   414   414 I AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.
10-26 21:37:50.147   414   414 D MediaProvider: Reading images for Achat appartement
10-26 21:37:50.153   414   414 D MediaProvider: Reading images for Camera
10-26 21:37:50.167   414   414 D MediaProvider: Reading images for Documents
10-26 21:37:50.182   414   414 D MediaProvider: Reading images for Miss
10-26 21:37:50.188   414   414 D MediaProvider: Reading images for PACS
10-26 21:37:50.198   414   414 D MediaProvider: Reading images for Photos appartement
10-26 21:37:50.212   414   414 D MediaProvider: Reading images for Photos appartement
10-26 21:37:50.220   414   414 D MediaProvider: Reading images for Pictures
10-26 21:37:50.235   414   414 D MediaProvider: Reading images for Pièces justificatives
10-26 21:37:50.244   414   414 D MediaProvider: Reading images for Pl@ntNet
10-26 21:37:50.258   414   414 D MediaProvider: Reading images for Screenshots
10-26 21:37:50.277   414   414 D MediaProvider: Reading images for Telegram
10-26 21:37:50.293   414   414 D MediaProvider: Reading images for Twidere
10-26 21:37:50.307   414   414 D MediaProvider: Reading images for WhatsApp Images
10-26 21:37:50.331   414   414 D MediaProvider: Reading videos for Twidere
10-26 21:37:50.347   414   414 D MediaProvider: Reading videos for WhatsApp Animated Gifs
10-26 21:37:50.361   414   414 D MediaProvider: Reading videos for WhatsApp Video
10-26 21:37:50.407   414   414 D SyncedFoldersActivity: onStart() starting
10-26 21:37:50.409   414   414 D SyncedFolderPreferencesDialogFragment: onCreateView, savedInstanceState is Bundle[{android:theme=2131493176, BEHAVIOUR_DIALOG_STATE=false, android:backStackId=0, android:savedDialogState=Bundle[mParcelledData.dataSize=244], android:view_state={2131820821=android.view.AbsSavedState$1@baf0e9d, 2131820942=android.view.AbsSavedState$1@baf0e9d, 2131820961=HorizontalScrollView.SavedState{a6b3f12 scrollPosition=0}, 2131821015=android.view.AbsSavedState$1@baf0e9d, 2131821016=android.view.AbsSavedState$1@baf0e9d, 2131821017=android.view.AbsSavedState$1@baf0e9d, 2131821018=CompoundButton.SavedState{6cd86e3 checked=true}, 2131821019=android.view.AbsSavedState$1@baf0e9d, 2131821020=android.view.AbsSavedState$1@baf0e9d, 2131821021=android.view.AbsSavedState$1@baf0e9d, 2131821022=android.view.AbsSavedState$1@baf0e9d, 2131821023=android.view.AbsSavedState$1@baf0e9d, 2131821024=android.view.AbsSavedState$1@baf0e9d, 2131821025=android.view.AbsSavedState$1@baf0e9d, 2131821026=android.view.AbsSavedState$1@baf0e9d, 2131821027=android.view.AbsSavedState$1@baf0e9d, 2131821028=android.view.AbsSavedState$1@baf0e9d, 2131821029=android.view.AbsSavedState$1@baf0e9d, 2131821030=android.view.AbsSavedState$1@baf0e9d, 2131821031=android.view.AbsSavedState$1@baf0e9d, 2131821032=CompoundButton.SavedState{b2dc8e0 checked=true}, 2131821033=android.view.AbsSavedState$1@baf0e9d, 2131821034=android.view.AbsSavedState$1@baf0e9d, 2131821035=android.view.AbsSavedState$1@baf0e9d, 2131821036=CompoundButton.SavedState{2f2f799 checked=false}, 2131821037=android.view.AbsSavedState$1@baf0e9d, 2131821038=android.view.AbsSavedState$1@baf0e9d, 2131821039=android.view.AbsSavedState$1@baf0e9d, 2131821040=android.view.AbsSavedState$1@baf0e9d, 2131821041=CompoundButton.SavedState{23a3a5e checked=false}, 2131821042=android.view.AbsSavedState$1@baf0e9d, 2131821043=android.view.AbsSavedState$1@baf0e9d, 2131821044=android.view.AbsSavedState$1@baf0e9d, 2131821045=android.view.AbsSavedState$1@baf0e9d, 2131821046=android.view.AbsSavedState$1@baf0e9d}}]
10-26 21:37:50.501   414   570 D ExternalLinks: links disabled
10-26 21:37:50.543   414   571 D OwnCloudClient #1: REQUEST GET /ocs/v1.php/cloud/users/admin
10-26 21:37:50.557   414   571 D AdvancedSslSocketFactory: Creating SSL Socket with remote ******
[.owncloudsync.log](https://github.com/nextcloud/android/files/1419819/default.owncloudsync.log)
![screenshot_20171026-210930](https://user-images.githubusercontent.com/1871792/32073368-1be1e04c-ba96-11e7-998b-dfecdb7e1df1.png)
![screenshot_20171026-211003](https://user-images.githubusercontent.com/1871792/32073369-1c1f1836-ba96-11e7-83c2-e50105e0e021.png)

.librement-votre.fr:443, local null:0, params: org.apache.commons.httpclient.params.HttpConnectionParams@cf531ff
10-26 21:37:50.557   414   571 D AdvancedSslSocketFactory:  ... with connection timeout 60000 and socket timeout 60000
10-26 21:37:50.565   414   571 I ServerNameIndicator: SSLSocket implementation: com.android.org.conscrypt.OpenSSLSocketImpl
10-26 21:37:50.565   414   571 I ServerNameIndicator: SNI done, hostname: *****.librement-votre.fr
10-26 21:37:50.573   414   414 D SyncedFoldersActivity: onResume() starting
10-26 21:37:50.597   414   414 I Choreographer: Skipped 36 frames!  The application may be doing too much work on its main thread.
10-26 21:37:50.868   414   414 D FileActivity: Operations service connected
10-26 21:37:50.909 12394 12454 I ActivityManager: Displayed com.nextcloud.android.beta/com.owncloud.android.ui.activity.SyncedFoldersActivity: +944ms
10-26 21:37:50.985   414   414 D UploadFilesActivity: onStop() ending
10-26 21:37:50.987   414   414 D UploadFilesActivity: onDestroy() ending

**Comment by Mickael-Martin** [comment]
I can't reproduct this bug in the version 20171213. You can close it !

**Comment by AndyScherzinger** [comment]
Thanks for the update @Mickael-Martin ❤️
