### ISSUE TITLE
File chooser does not retrieve updated file 

### ISSUE THREAD

**Issue by memen45** [nextcloud/android#1718]
### Actual behaviour
Choose file from another app through the nextcloud online fs gives the local version if available

### Expected behaviour
Choose file from another app through the nextcloud online fs gives the online version, or - if the local version is up-to-date - the local version.
 
### Steps to reproduce
1. Open pdf file in Nextcloud app (now it is stored locally)
2. Modify the file on the server (Now local file is the old version)
3. Choose the file from another app 

### Environment data
Android version:
Android 6.0

Device model: 
H60-L04

Stock or customized system:
EMUI 4.0

Nextcloud app version:
2.0.0

Nextcloud server version:
12.0.3
### Logs
Not applicable

**Comment by xXSTrikeXx** [comment]
Have you mark it as available offline?

**Comment by memen45** [comment]
![screenshot_2017-10-27-14-25-40](https://user-images.githubusercontent.com/27782135/32119604-0ce44718-bb56-11e7-9827-4a335e278b86.png)
The file lab7 was opened once, therefore has a green checkmark. I have not marked the file as 'available offline' (in options I can still choose 'make available offline')
![screenshot_2017-10-27-14-26-18](https://user-images.githubusercontent.com/27782135/32119731-78699b3c-bb56-11e7-84fd-cb3a61efa660.png)
This is what I mean with the 'choose file from another app'. So I select the file through this online nextcloud.

**Comment by mario** [comment]
Maybe fixed by https://github.com/nextcloud/android/pull/1655 :)

**Comment by AndyScherzinger** [comment]
@memen45 for the time being try to long press the file in the Nextcloud app and choose available offline in the menu.

**Comment by tobiasKaminsky** [comment]
Works for me.
This got enhanced by whole document storage stuff with next version (e.g. #3438)
