### ISSUE TITLE
Failed Uploaded files can not be cleared

### ISSUE THREAD

**Issue by brjhaverkamp** [nextcloud/android#1722]
On version 2.0. I have about 700 fileds in my uploaded files list that failed because the local file can not be found. But there seems to be no way to clear this, other than 700 times tapping the bin icon behind each warning.

Otherwise no bugs found yet. Thanks for the great update!

**Comment by mario** [comment]
The real question is where are all those files? xD

**Comment by mario** [comment]
(Btw. if you enable expert mode in Settings, you can clear the list)

**Comment by brjhaverkamp** [comment]
Thx. I expect this was an accumulation of pictures taken and directly deleted for over three months. To be clear, it was my wifes phone. She takes a lot of pictures, but selects the best shot and deletes the rest. 

Ill look at exert mode. But wasnt it in normal mode before? Either that, or I was in expert mode on my phone for a long time already.

Regards,

Bert

**Comment by mario** [comment]
Was moved to expert mode with 2.0 - let me know how it goes!
