### ISSUE TITLE
Open OAUTH in default browser

### ISSUE THREAD

**Issue by rugk** [nextcloud/android#1723]
### Actual behaviour

The OAUTH login opens in a webview thing…

### Expected behaviour
Open it in the default browser, because:
* I think that is what the spec recommends
* users can use their addons/password managers/known browsers
* enjoy the security stuff of your browser, instead of a potentially outdated webview (often not updated on old devices)

**Comment by tobiasKaminsky** [comment]
https://docs.nextcloud.com/server/latest/developer_manual/client_apis/LoginFlow/index.html#login-flow-v2

Should be possible also on Android/iOS.
Desktop is already doing it.

**Comment by rugk** [comment]
Thanks yeah, I forgot to mention the _most important reason for that_ however:
* Users may already be logged-in in their browser, so a webview just prevents them from an easier login flow.

**Comment by rokejulianlockhart** [comment]
@rugk, GitHub issues are editable.

**Comment by joshtrichards** [comment]
Fixed in #12922
