### ISSUE TITLE
unable to re-initiate failed uploads

### ISSUE THREAD

**Issue by wireddude** [nextcloud/android#1724]
### Actual behaviour
-Tell us what happens

Attempt to upload photos (manually)
They fail, server restart 
But wait, no overflow menu to re-start failed uploads. 

### Expected behaviour
-should see an option to retry failed uploads. Not there anymore 
 

### Environment data
Android version: 8.0

Device model:  Google Pixel

Stock or customized system: N/A

Nextcloud app version:
2.0.1
Nextcloud server version:
12.0.3

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by mario** [comment]
If you enable expert mode in settings, you'll have it :)
