### ISSUE TITLE
Bulk upload after OS update

### ISSUE THREAD

**Issue by jasonbayton** [nextcloud/android#1726]
### Actual behaviour
Update Moto to September 2017 security patch level
Power on Phone
Nextcloud starts uploading photos again out of nowhere. These are already uploaded and it's overwriting them.

over 200 files uploaded before I killed the app

### Expected behaviour
Stop re-uploading all of my photos!
 
### Steps to reproduce
See actual

### Environment data
Android version: 7.1.1

Device model: Moto Z Play

Stock or customized system: Stock

Nextcloud app version: 2.0

Nextcloud server version: 12.0.3

**Comment by mario** [comment]
Should not happen due to crc32 introduction.

**Comment by mario** [comment]
Should not happen due to crc32 introduction.
