### ISSUE TITLE
constant "uploading files" on android

### ISSUE THREAD

**Issue by Progdrasil** [nextcloud/android#1727]
### Actual behaviour
There is a constant "uploading files" activity notification on my android device since updating to 2.0.0. I cannot get rid of this notification as android most likely is considering this as an activity. An example is shown in the following screenshot:
![screenshot_20171030-232021](https://user-images.githubusercontent.com/11562522/32206159-de5a194c-bdc9-11e7-959f-f25a67879b3f.png)

### Expected behaviour
-There should not be a constant activity running from this app that tries to upload files

### Environment data
Android version: 7.1.1

Device model: moto z play

Stock

Nextcloud app version:2.0.0

Nextcloud server version: 12.0.3

**Comment by kreso75** [comment]
Happens also on mine LG G5, stock Android 7.0 with same combination of client app (2.0.0) and Nextcloud 12.0.3.
