### ISSUE TITLE
Renaming in Preferences

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#173]
mPrefInstantUploadPathWiFi --> mPrefInstantUploadOnlyOnWiFi
Check if InstantUpload -> InstantPicture (will be in most cases, except upload behaviour)

**Comment by AndyScherzinger** [comment]
Makes total sense! :+1:

**Comment by tobiasKaminsky** [comment]
As we remove InstantUpload and replace it with AutoUpload and I have no idea what I meant, I will close this.
