### ISSUE TITLE
Can't upload pictures (manually or automaticly)

### ISSUE THREAD

**Issue by StrangeMonkey** [nextcloud/android#1731]
Good morning,

### Actual behaviour
- Actually, i can't upload picture on my cloud. Manually by sharing picture with the Nextcloud application and automaticly by configuring the automatic upload on the nextcloud application

### Expected behaviour
- I would like to update pictures and video automaticly and sometimes manually.
 
### Steps to reproduce
1. Take a picture
2. Go in your media 
3. Share the picture and select Nextcloud
4. Select the destination directories
5. Now the download is always at "Sending..." I don't have any pourcentage or anything like this.

### Environment data
Android version: Android Marshmallow 6.0

Device model: Wiko U Feel LITE

Stock or customized system:

Nextcloud app version: 2.0.0

Nextcloud server version: 12.0.3

In this case, it's for manually upload (to stop the log, i've to force the stop of the app)

### Logs
- To debug i've added log system in nextcloud config.php at 0 level
- Here this is the lastest log. You can see "IMG_20171101_082125%20(411).jpg" and the 411 is incrementing every second, as if it's a try number.
- Mobile is the destination directory.

#### Nextcloud log (data/nextcloud.log)
{"reqId":"ZOZjLUtTXiON3xefckGO","level":0,"time":"November 01, 2017 07:33:17","remoteAddr":"MYIPADDRESS","user":"MYUSERNAME","app":"webdav","method":"HEAD","url":"\/remote.php\/webdav\/Mobile\/IMG_20171101_082125%20(411).jpg","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotFound\",\"Message\":\"File with name Mobile\\\/IMG_20171101_082125 (411).jpg could not be located\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(81): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('Mobile\\\/IMG_2017...')\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:GET', Array)\\n#4 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(253): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response), false)\\n#5 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpHead(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#7 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:HEAD', Array)\\n#8 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(76): Sabre\\\\DAV\\\\Server->exec()\\n#10 \\\/var\\\/www\\\/nextcloud\\\/remote.php(162): require_once('\\\/var\\\/www\\\/nextcl...')\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/ObjectTree.php\",\"Line\":173}","userAgent":"Mozilla\/5.0 (Android) ownCloud-android\/2.0.0","version":"12.0.3.3"}

Thank you for reading,
Sorry for my english,
Thank you for answering,

Please, ask me for more information

**Comment by StrangeMonkey** [comment]
Hello,

Is there something new ?
I can help you if necessary by giving you more details about logs, about my problem.
Please, inform me on how can i help you.

Thank you for reading,
Thank you for answering,

StrangeMonkey

**Comment by tobiasKaminsky** [comment]
> {"Exception":"Sabre\\DAV\\Exception\\NotFound","Message":"File with name Mobile\/IMG_20171101_082125 (411).jpg could not be located","Code":0,"Trace":"#0 \/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(81): 

@MorrisJobke (or another server guy) this seems to be a server problem, or?

**Comment by StrangeMonkey** [comment]
Hello,

I don't think that can be a server problem. In fact, with an iPhone and the Nextcloud iOS application, i can auto-upload or manually upload file without mistake.

Do not hesitate to ask me for more details.

Thank you for reading,
Thank you for answering,

StrangeMonkey

**Comment by tobiasKaminsky** [comment]
Can you create us a test account and send the credentials to android at nextcloud dot com with a reference to this issue?

**Comment by Mr-Maniac** [comment]
I have a similar, if not even the same issue. Server 12.0.0.4 and now 13.0.0 beta 3 and app version 2.0.0 and dev 20171223
When trying to upload anything, the app seems to check, if the file exists, first (via HEAD request to "/remote.php/webdav/{folder}/{filename}"). This gives a 302 redirect to "/apps/files/" and the app tries the HEAD request again, with a new filename (just adds or increments a number. e.g. "IMAG0123%20(44).jpg"). But the app would not upload anything. It just sends the HEAD request (in an infinite loop with increasing number).
Phone HTC One M9 with Android 7.0. Last time I successfully uploaded something was with app version < 2.0.0. I already re-installed the app and, like written above, already tried the dev version.

**Comment by tobiasKaminsky** [comment]
Can you create us a test account and send the credentials to android at nextcloud dot com with a reference to this issue?

**Comment by Mr-Maniac** [comment]
Okay, now I think I understand what's happening after looking into the output of logcat:
1. App sends HEAD request to check, if file already exists
2. Response is 302 redirect to /apps/files/
3. App follows redirect and gets 200 from /apps/files/
4. App thinks "file exists" and will goto 1 with a new filename

Here are the logs from apache and from nextcloud android app (username and server url replaced by {$USER} and {$SERVERURL}):
[nextcloudApacheAccess.log](https://github.com/nextcloud/android/files/1589682/nextcloudApacheAccess.log)
[nextcloudOnlyLog.txt](https://github.com/nextcloud/android/files/1589683/nextcloudOnlyLog.txt)

**Comment by Mr-Maniac** [comment]
Okay, this really seems to be an server issue (when RewriteBase is set in config.php and always with nextcloud 13). See https://github.com/nextcloud/server/issues/7639

**Comment by tobiasKaminsky** [comment]
Great that you figured it out 👍 
So closing this here, as it it as server side bug.
If something still needs to be changed on client, please reply/re-open here.
