### ISSUE TITLE
Tablet enhancements

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#1742]
During hackweek @jancborchardt and I sat together and had a closer look how we can enhance the tablet experience

- orientation switching
    - landscape: show file/folder column on left, detail view on right
    - portrait: show only file/folder (like on phone)
    - this should change dynamically (currently it is only detected during app start)
-  landscape mode
    - instead of empty detail view, show app logo in grey (20% opacity)
    - click on an image shows image preview in detail view
        - click on image preview toggles between fullscreen and preview
        - swipe left/right shows all images in current folder

**Comment by AndyScherzinger** [comment]
@jancborchardt @tobiasKaminsky should this also be like this for grid views especially for more or less pure image folders? Just asking since this is a user complaint in our tracker by several people that when looking through your photos in grid it should stretch through the whole screen.

**Comment by jancborchardt** [comment]
We were unsure about grid view. It might make sense to indeed stretch whole screen, but then we definitely need to adjust how the grid view sizes, because right now in certain scenarios the filenames are not visible, or images are nice but filetype icons are very small.

**Comment by AndyScherzinger** [comment]
Sounds good, then let’s postpone grid specials

**Comment by tobiasKaminsky** [comment]
Close in favor of https://github.com/nextcloud/android/issues/6769
