### ISSUE TITLE
List item: three dots/share icon not full height

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#1743]
Shared icon / three dots icon in list view do not have full height, so if one is clicking nearly directly on the separation line, it will open the file/folder instead of the icon action.
(found by @jancborchardt at tablet)

**Comment by AndyScherzinger** [comment]
Yeah, that one is easy to fix, so marking is a starter issue 👍

**Comment by AndyScherzinger** [comment]
PR is #1760
