### ISSUE TITLE
External SD Card access on Chromebook

### ISSUE THREAD

**Issue by mobamoba** [nextcloud/android#1745]
### Actual behaviour
-Tell us what happens
External SD doesn't appear as a storage option on Chromebook with Android.
### Expected behaviour
-Tell us what should happen
 External SD access should be available. 

Some Android apps on Chromebook are able to access the external SD card and some aren't - I don't understand the underlying tech but here's the Chrome bug report thread (https://bugs.chromium.org/p/chromium/issues/detail?id=660189) which provides a link to what I think is the solution (https://developer.android.com/training/articles/scoped-directory-access.html#removable) though again I don't know for sure.

Given that Android is now out of beta on Chromebooks, having Nextcloud use the External SD card would be hugely helpful. 

### Steps to reproduce
1. 
2. 
3. 

### Environment data
Android version:
7.1.1
Device model: 
Chromebook
Stock or customized system:
Stock
Nextcloud app version:
2.0.0
Nextcloud server version:
12
#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Thank you for your reply.
I also over read your link to a possible solution.
Due to time and lick of such a device, I fear that a solution might take some time.
Maybe some other dev who has such a device can jump in.

**Comment by tobiasKaminsky** [comment]
https://developer.android.com/topic/arc/index.html
