### ISSUE TITLE
Adaptiv Icon

### ISSUE THREAD

**Issue by Slevin7** [nextcloud/android#1746]
Hello,
is it possible to change the icon in an adaptive icon for new android os?
example: https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html

thanks a lot

**Comment by tobiasKaminsky** [comment]
@jancborchardt as you are the design guru :-)

**Comment by AndyScherzinger** [comment]
I'd like to have that and as stated in another issue I can't find anymore we should support the standard launcher icon (for pre-Android O), the circular launcher icon for Android N and the adaptive launcher icon for Android O and above :)

**Comment by AndyScherzinger** [comment]
@Slevin7 yes :)

PR for the adaptive icon is #1887

**Comment by RokeJulianLockhart** [comment]
It's not adaptive for https://gitlab.com/fdroid/fdroiddata/-/blob/dbd211a0f3258356be626aac7b07994f6b4efff7/metadata/com.nextcloud.android.beta.yml

> ![Screenshot_20240504-142514](https://github.com/nextcloud/android/assets/42837531/178253f8-004f-4f79-b2c1-9647a0d65af6)
