### ISSUE TITLE
Combine move and copy (like on web UI)

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#1748]
As requested by @jancborchardt during hackweek, to have fewer menu items, let us combine move and copy in the same way like (NC13) web UI will do it:

![image](https://user-images.githubusercontent.com/5836855/32429134-8cb8947e-c2c9-11e7-8d5a-70a64164408e.png)

![image](https://user-images.githubusercontent.com/5836855/32429160-aafdcc10-c2c9-11e7-9aaf-b3645d801ed2.png)

Is this fine for you?

**Comment by AndyScherzinger** [comment]
Sounds good! 👍 Less menu items while having the same functionality is always nice! :)

**Comment by jancborchardt** [comment]
Closing in favor of https://github.com/nextcloud/android/issues/2212 which has more info
