### ISSUE TITLE
Single file: overflow menu: same order as web ui

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#1749]
Web UI:
![image](https://user-images.githubusercontent.com/5836855/32429134-8cb8947e-c2c9-11e7-8d5a-70a64164408e.png)

Android:
![image](https://user-images.githubusercontent.com/5836855/32429502-2dacfa7c-c2cb-11e7-8122-10f5f5947063.png)

As far as I remember we said that those entries that are android only should be at bottom, @jancborchardt?

**Comment by AndyScherzinger** [comment]
👍 sounds good!

**Comment by jancborchardt** [comment]
> As far as I remember we said that those entries that are android only should be at bottom, @jancborchardt?

At the bottom, but before Delete. :) Delete, or the destructive action, should always be the last one.
