### ISSUE TITLE
Tablet: detail & list view: show folder options on bottom

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#1750]
- tablet in landscape mode
- detail and list view are shown
- click on a file to open up its detail view
- click on upper right overflow menu
--> folder options (refresh account, sort, list view) should be on bottom

![2017-11-06-082939](https://user-images.githubusercontent.com/5836855/32429822-b1b91ac0-c2cc-11e7-941b-c24cf6cf1e7e.png)

**Comment by AndyScherzinger** [comment]
👍 fine by me

**Comment by tobiasKaminsky** [comment]
Close in favor of https://github.com/nextcloud/android/issues/6769
