### ISSUE TITLE
Photos just uploaded by Auto Upload then appear on device with size zero

### ISSUE THREAD

**Issue by roger-whittaker** [nextcloud/android#1751]
### Actual behaviour
I take a photo. It gets uploaded. Later, I navigate on the same device to the directory under InstantUpload where the photo should be. I see a large warning triangle and text that says that the image can not be shown.

If I check in the local folder where the file should be, I see that a file with the correct filename exists, but it has size zero bytes.

If I delete that file locally, the actual file can be downloaded from the server and viewed normally.

### Expected behaviour
I would expect the photo to get downloaded from the server and displayed normally.
 
### Steps to reproduce
1. Take a photo
2. Wait for long enough for the auto upload to happen
3. 
Check in the expected folder.

### Environment data
Android version: 7.1.1 (OxygenOS 4.5.1)

Device model: OnePlus 3

Stock or customized system:

Nextcloud app version: 2.0.0

Nextcloud server version: 12.0.3

This is the same behaviour that I previously reported on older versions in:
https://github.com/nextcloud/android/issues/801

**Comment by roger-whittaker** [comment]
Storage path:

/storage/emulated/0/Android/data/com.nextcloud.client/files

which is also

/sdcard/Android/data/com.nextcloud.client/files

**Comment by roger-whittaker** [comment]
For the record: I can't comment on this any more because I've switched to lineageos (14.1 latest) and the problem no longer happens.  So this looks as if it might have been OxygenOS specific.

**Comment by inducer** [comment]
Happening to me on a One Plus 5 on latest LineageOS. (Nightly from 20171127)

**Comment by inducer** [comment]
Hmm--not sure what I'm seeing is the same bug though. For me, an actually empty file gets uploaded. In addition, during the upload, the notification shows crazy numbers, e.g. "-1238172% uploaded".

**Comment by inducer** [comment]
In addition, this only seems to happen with the built-in camera. OpenCamera does not seem to suffer from this.

**Comment by ovidiub13** [comment]
Happens to me on a OnePlus One with Cyanogen Mod (factory install).

**Comment by inducer** [comment]
Still happening in version 2.0.1 from FDroid (on LineageOS on an OP5). Only happens intermittently for me. And, just to make the context clear, this can be a major data loss bug. If you have the auto upload set to "Move to app folder" or "Delete", then the net effect is that the picture is irrevocably replaced by a zero-size file.

**Comment by inducer** [comment]
Here's a glimpse of the odd notification that lets you know that you're about to lose a photo:

![screenshot_20180113-151447](https://user-images.githubusercontent.com/352067/34912208-93506e44-f8a0-11e7-8e31-29b62e8ff6ff.png)

**Comment by bezerker** [comment]
Does anyone have any workarounds for this? Getting this on an s7edge and it's really annoying.  Seems to occur with auto upload.

**Comment by tobiasKaminsky** [comment]
I have the same problem on my one plus 3 and can workaround it with using openCamera instead of the built in camera app.

**Comment by ovidiub13** [comment]
I've removed the setting to move the pictures in the Instant upload directory, and just leave them in place. I haven't experienced this issue since.
