### ISSUE TITLE
Computed accent color too bright

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#1769]
Currently this is our algo:
if lightness <= 0.55
 lightness + 0.1
else 
 lightness - 0.1

This seems not the best idea  ;-)
@jancborchardt @juliushaertl 

![2017-11-10-143224](https://user-images.githubusercontent.com/5836855/32660725-3cb04860-c624-11e7-8160-80024ef0931a.png)

**Comment by comradekingu** [comment]
I think the "correct" method would include asymmetric colour matching.

https://pdfs.semanticscholar.org/dfc9/7e419d66eb92c4ea968c9bc8f0667575f8cd.pdf

The colour will otherwise appear different based on what background it is on.

**Comment by jancborchardt** [comment]
What we could do:

- Ensure the lightness of the text is not above a certain value, and if it is:
   - Make it darker to fit the value
   - Simply use a defined black or grey text
- Add a _very_ slight text shadow, if that’s possible or at all Android-like

Other ideas @juliushaertl?

**Comment by tobiasKaminsky** [comment]
I would go for idea 1 with a sane threshold. Text shadow is uncommon for me.

**Comment by jancborchardt** [comment]
Can you do an example of hoe that green (or a similar bright color like yellow) looks with 20%, 30%, 40%, 50% lightness? Then we could decide on a threshold.

**Comment by tobiasKaminsky** [comment]
Current situation:
![baseline](https://user-images.githubusercontent.com/5836855/32723273-300065d2-c86d-11e7-907a-1aa6d2e08b7b.png)

10:
![10](https://user-images.githubusercontent.com/5836855/32723281-39efc920-c86d-11e7-96f2-c2a45364601c.png)
20:
![20](https://user-images.githubusercontent.com/5836855/32723288-40076304-c86d-11e7-9d50-9dbcf29bfde1.png)
30:
![30](https://user-images.githubusercontent.com/5836855/32723289-4036a178-c86d-11e7-8640-ee2525ed7bc8.png)
40:
![40](https://user-images.githubusercontent.com/5836855/32723290-405f33cc-c86d-11e7-91e5-044063360abf.png)
50:
![50](https://user-images.githubusercontent.com/5836855/32723291-4087efc4-c86d-11e7-8c62-d29569fbf214.png)
60:
![60](https://user-images.githubusercontent.com/5836855/32723293-40b27410-c86d-11e7-9283-07ab5112d2f4.png)
70:
![70](https://user-images.githubusercontent.com/5836855/32723294-40f343c8-c86d-11e7-91ce-87ce230f1b41.png)

**Comment by tobiasKaminsky** [comment]
For primaryDarkColor we compute it with -20% lightness, so this might also need an adjustment.

**Comment by jancborchardt** [comment]
Thanks! The one at 40 seems best, what do you think? cc @juliushaertl

**Comment by AndyScherzinger** [comment]
Nice, I'd say 30 since then you still have a slight contrast between the two colors whereas with 40 primary and primary dark are about the same and can't be distinguished.

**Comment by jancborchardt** [comment]
I only now saw that the top status bar is affected too btw, my comment was only about the text color. :)

30 seems a tad dark for the text. Is it possible to do the top bar separately? Or maybe 35? (I'm also fine with the top bar and status bar being the same color, looks simple. ;)

But really, details which only occur on theming, so I'm fine with 30 too I guess. ;)

**Comment by tobiasKaminsky** [comment]
No, the top status bar is always primaryDark. This was a fault due to hacking the values (20%, 30%, ...) hardcoded into it.
So this is only about the text color.
I will add a threshold of max 35% and test it with some random colors.
