### ISSUE TITLE
Trigger sync/download/upload

### ISSUE THREAD

**Issue by gsantner** [nextcloud/android#1772]
### Actual behaviour
There is no such methodology available

### Expected behaviour
Some form of lightweight class/snippet to trigger a sync/download/upload. This way apps could trigger re-sync of existing or custom files from Nextcloud. Because of often not-reacting Auto-Upload of this app, and the coming changes in Android O+ I think it would be a good idea to have some sort of outside trigger available to hint  the official Nextcloud app to do it's work, and especially sync specified file(s).

My example is [Markor](https://github.com/gsantner/markor), which edits local files, in this case a file inside Nextcloud: `NCROOT/todo.txt`, which is tagged `offline available` and `favourite`. Still, somehow it doesn't sync accordingly in background, always have to start NC app to see if it is really latest version. In O+ there may be no way for Nextcloud app to run in background (or at least at the right time when something has changed in between), so sending a resync-Intent with an path extra to trigger a forced sync would be very helpful. NC app could than e.g. send a broadcast/intent back in return.

Tell me if there are open questions, the description sounds quite complicated currently :D.

### Environment data
Android version: nougat

Device model: Nexus 5

Stock or customized system: LOS 14.1

Nextcloud app version:  v2.0.1

Nextcloud server version: 12

**Comment by tobiasKaminsky** [comment]
I am not sure about this.
I think the real solution is to harden the upload / sync as we are doing since some time.
Trying to "solve" this via an external app does not sound like the right way for me...

**Comment by gsantner** [comment]
what is the current state of sync used in official app, the api, and the document provider? I feel like there is everywhere a little working code, but none of them stable. I would rrally like to support nextcloud in my apps, ans support tje project in this way, but for me it currently seems quite impossible to create something useable, without data loss or always sync conflicts

**Comment by Ekleog** [comment]
I am hitting the same issue with Orgzly: Nextcloud appears to not download updates to the files until I manually open the app.

Even a widget to manually trigger sync of a set of files would be OK with me, but having to open the app and look through my Nextcloud drive for the files to check they are actually synced is a bit painful :/

Anyway, thank you for the app! :)

**Comment by gsantner** [comment]
Closing some old stuff nobody seems to care about, and I don't use NextCloud Android anymore.
