### ISSUE TITLE
Client TLS negotiation issue

### ISSUE THREAD

**Issue by janipewter** [nextcloud/android#1774]
### Actual behaviour
Nextcloud fails to upload with "Connection error"

### Expected behaviour
Upload should complete successfully.
 
### Steps to reproduce
1. Configure Apache SSL settings with "SSLOpenSSLConfCmd	Curves secp521r1:secp384r1"
2. Attempt to connect to server with Nextcloud client
3. Profit.

### Environment data
Android version: 7.0

Device model: Samsung Galaxy S7 (SM-G930F)

Stock or customized system: Stock

Nextcloud app version: 2.0.0

Nextcloud server version: ownCloud 9.1.6 stable

#### Web server error log
nothing shows

#### Nextcloud log (data/nextcloud.log)
nothing shows

My ownCloud server is behind an Apache2 reverse proxy which also does the SSL. I hardened my SSL configuration but Nextcloud Android client does not like Curves secp521r1:secp384r1. The ownCloud desktop client works fine. If I comment that line out of my config, the Nextcloud Android client works fine.

**Comment by tobiasKaminsky** [comment]
We need to figure out if our http library supports this cipher or if it is available from device.

**Comment by tobiasKaminsky** [comment]
Then it is probably due to our "old" httpclient version 3.1

**Comment by janipewter** [comment]
https://dev.ssllabs.com/ssltest/analyze.html?d=secure.jani.media&s=209.222.30.20&hideResults=on
