### ISSUE TITLE
Frequent failure to upload/download even though server's fine (beta)

### ISSUE THREAD

**Issue by detly** [nextcloud/android#1780]
### Actual behaviour
There are a variety of symptoms, but essentially I can tell when it's started because automatic uploads just error out. Usually a notification says "Could not complete operation. Server unavailable" Occasionally it says "Server in maintenance mode." (It definitely isn't though.)

Downloads will also fail at this point eg. if I tap on a photo, the progress bar doesn't move past 0 and eventually I get a notification "Could not download IMG_....jpg".

However, the server is fine. I confirm this by visiting it in a browser, and if I forcible kill the Nextcloud app and restart it manually, everything suddenly works. This suggests to me it's the app that's the problem, not the server.

### Expected behaviour
Network operations work if the server and internet are fine.
 
### Steps to reproduce
For me, it happens pretty much once a day. I might have a heap of photos waiting to be uploaded (automatically), and it'll fall over on the last ten or so. Not sure beyond that.

### Environment data
Android version: 7.1.2

Device model:  HTC One M9

Stock or customized system: Customised (LineageOS 14.1 20171107 nightly himaul)

Nextcloud app version: 2.0.0

Nextcloud server version: 12.0.3

### Logs

There are no errors on the webserver and the logs section of the settings is blank!

**Comment by GitHubUser4234** [comment]
I cannot upload any file to an encrypted folder in the current alpha release. It **always** fails. Symptoms:

1) Create a new folder
2) Mark the new folder as encrypted
3) Enter the new folder and choose a file to upload
4) It says "Could not complete operation. Server unavailable"
5) Try it again and then it says "Locked"

More info:

It seems there are no meta-data created. In fact the whole data/appdata_ocfxxxxxx/end_to_end_encryption/meta-data/ folder is empty.

**Comment by paour** [comment]
I had the same thing happen to me. The cause send to be that I had set auto upload to create year/month folders, and the client failed to auto create a folder for the new month.

**Comment by sumnerboy12** [comment]
@paour I was having the same problem, and after your comment realised it only started happening post 1st March. When I manually created the `upload\2018\03` folder the uploads started working again. Thanks for the tip!

**Comment by cowai** [comment]
Same here.
It only started after 1th of march. It got fixed by creating the "03" folder my self. Strange bug.

**Comment by detly** [comment]
Clarification: @GitHubUser4234's issue probably has a different cause (I'm not using encryption). @paour's is also likely different (doesn't matter if upload folder exists or not).

**Comment by tiberiust** [comment]
Same issue here from 1st March. I have auto upload subdirs for photos, videos and separate ones for WhatsApp media also. I had to first create the subdirs '03' in all head dirs and then also manually upload a file into those folders using Files in the Nextcloud client. Then autoupload started working again. 
Server 13.0.0, nginx ; Android 3.0.2 ; MIUI 9.2, Photos etc are stored on External SD Card. 

Took me a while to debug the problem, I had updated to Server 13.0 and updated my Mi Max 2 to MIUI 9 since 1st March. Spent ages going thru MIUI bcos that's usually the culprit, but not this time ;)

**Comment by detly** [comment]
@paour @sumnerboy12 @GitHubUser4234 @cowai @tiberiust You are definitely describing a different bug to the one I opened this issue for. You should open a new issue, otherwise when the original issue gets fixed, yours will be forgotten about.

**Comment by edoardoo** [comment]
I have exactly the same issue.
