### ISSUE TITLE
App re-queued everything

### ISSUE THREAD

**Issue by DaveBurkhardt** [nextcloud/android#1781]
### Actual behaviour
everything was requeued,  i have 1000's of files now waiting to be uploaded.  All of these are already on the server. 

### Expected 
Do not do this
 
### Steps to reproduce
1.  No changes to anything for weeks
2.  Rebooted phone and saw battery draining
3. 

### Environment data
Android version:

Device model:   s5

Stock or customized system:
Stock

Nextcloud app version:
2.0.0

Nextcloud server version:
Latest stable

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by DaveBurkhardt** [comment]
![image](https://user-images.githubusercontent.com/23338339/32756083-edec30e6-c89d-11e7-93f2-a98e01c217eb.png)

Server side...

**Comment by DaveBurkhardt** [comment]
![client-side](https://user-images.githubusercontent.com/23338339/32756241-c681bac0-c89e-11e7-830d-2a95484abc05.png)

Client side...

**Comment by DaveBurkhardt** [comment]
How do I fix the queue?  I have 1000's of things queued now?!

**Comment by AndyScherzinger** [comment]
@DaveBurkhardt easiest would be to go to the apps settings, activate expert mode, go back to the Uploads screen and then remove the entries via the top right menu item.

**Comment by DaveBurkhardt** [comment]
Oh, ok.  Thank you!

**Comment by AndyScherzinger** [comment]
Your very welcome, hope it helped :)
