### ISSUE TITLE
Take photo & upload it directly in folder

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#1782]
As wished by mail:
- go into a folder
- open camera, take a photo
- upload photo directly

This is the same like in whatsapp, dropbox.
We could do this in our FAB, and add it there.

**Comment by AndyScherzinger** [comment]
Isn't this the same discussion as #1158

**Comment by tobiasKaminsky** [comment]
Right, thanks for pointing this out 👍
