### ISSUE TITLE
Auto Upload: clarify "unknown error"

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#1783]
Sometimes "unknown error" occurs in upload pane.
This not useful neither for us to debug nor for the user.

**Comment by AndyScherzinger** [comment]
This is due to https://github.com/nextcloud/android/blob/master/src/main/java/com/owncloud/android/ui/adapter/ExpandableUploadListAdapter.java#L601 while I can't say for sure when this is set to unknown.

**Comment by joshtrichards** [comment]
Duplicate of #260
