### ISSUE TITLE
Reference to Owncloud

### ISSUE THREAD

**Issue by johnjgsmith** [nextcloud/android#1786]
### Actual behaviour
- There's still a reference to Owncloud

### Expected behaviour
- Reference to Owncloud should be changed to Nextcloud
 
### Steps to reproduce
1. I went to the profile page in the Android Nextcloud app. When the app couldn't connect to the server, a message saying Owncloud could not connect: "the Owncloud server is not configured".
2. Screenshot (posted your image directly :) ~kingu)
![bilde](https://user-images.githubusercontent.com/13802408/32809597-a7704a62-c997-11e7-84cd-66ae216291f8.png)

### Environment data
Android version: 7.0

Device model: Galaxy Note 5

Stock or customized system: Stock Samsung

Nextcloud app version: 2.0.0

Nextcloud server version: 12.0.3

**Comment by comradekingu** [comment]
![bilde](https://user-images.githubusercontent.com/13802408/32809545-7f6f32a8-c997-11e7-8554-dfc6b715ba43.png)

**Comment by tobiasKaminsky** [comment]
Thank you for your finding @johnjgsmith and thank you @comradekingu for the PR.
I created an additional fix on android-library: https://github.com/nextcloud/android-library/pull/97

**Comment by tobiasKaminsky** [comment]
Closing as PR is merged
