### ISSUE TITLE
Conference ToDo

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#179]
My personal wishes to getting done on the conference
- #50 / #84 (What's new screen)
- #34 (Search feature with /core Search API)
- Screenshot system: https://github.com/nextcloud/screenshots/pull/14 @stp-ip 
- 2way sync / extend instand uploader
- how to deal with new owncloud content
- Bug hunting season
- start using new code style(?)

More ideas are welcome!

**Comment by jancborchardt** [comment]
Something I’d love to get straight on the topic of server-app parity is the Favorites and that they are still different locally and on the server. We should make them sync. And then also add a sidebar entry to quickly access them.

Another point is better offline functionality, or improvement of behavior when the connection is bad. That is, carrying out upload, delete, favorite actions etc. no matter if there’s connection or not.

**Comment by jancborchardt** [comment]
Also cc @AndyScherzinger 

And then people who hopefully come to the conference too: @stoyicker @LukeOwncloud @Spacefish @DavidWiesner @David-Development @schaal @cemrich @b3nson :) see https://conf.nextcloud.com
