### ISSUE TITLE
Video thumbnails not loading on offline files

### ISSUE THREAD

**Issue by TheNetStriker** [nextcloud/android#1791]
### Actual behaviour
I've enabled video thumbnails on my Nextcloud sever and they are working for non-offline files. But as soon as I mark a folder as offline available the video thumbnails arent't loaded anymore. (But image thumbnails are still showing)

### Expected behaviour
Video thumbnails should be displayed for offline files too.
 
### Steps to reproduce
1. Download complete folder containing videos as offline available 
2. Switch to grid view.
3. Scroll down in the folder =>video thumbnails are not loading.

### Environment data
Android version:
6.0.1
Device model: 
ZTE Axon 7
Stock or customized system:
Stock
Nextcloud app version:
2.0.0
Nextcloud server version:
12.0.3
#### Web server error log
No errors found

#### Nextcloud log (data/nextcloud.log)
No errors found

**Comment by tobiasKaminsky** [comment]
Strange thing...This should not even be related.

**Comment by xXSTrikeXx** [comment]
Is it a .mp4 file? Thens its server side.

**Comment by TheNetStriker** [comment]
Yes the files are MP4 files, but the thumbnail generation is working when the files are not stored locally for offline usage. So thumbnail generation on server side should work.

Maybe the problem is that the application doesn't even try to load the thumbnail from the server because it's locally stored?

**Comment by TheNetStriker** [comment]
I've debugged the problem and I think I found the problem in the [ThumbnailsCacheManager](https://github.com/nextcloud/android/blob/66d31bb6030ee41d771335f6b0d238c24bdbbbbb/src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java) at line 273.

I've also found a workarround for this:

Before:

```
if (file.isDown()) {
    Bitmap bitmap = BitmapUtils.decodeSampledBitmapFromFile(file.getStoragePath(), pxW, pxH);

if (bitmap != null) {
.....
```

After:
```
if (file.isDown()) {
    Bitmap bitmap = null;
    if (MimeTypeUtil.isVideo(file)) {
        bitmap = ThumbnailUtils.createVideoThumbnail(file.getStoragePath(),
            MediaStore.Images.Thumbnails.MINI_KIND);
    } else {
        bitmap = BitmapUtils.decodeSampledBitmapFromFile(
            file.getStoragePath(), pxW, pxH);
}

if (bitmap != null) {
```

Is this an acceptable solution for the problem?

**Comment by tobiasKaminsky** [comment]
Thank you for your debugging @TheNetStriker 👍 
Technically it is the right solution, but the wrong GenerationTask: you refer to ResizedImageTask and not ThumbnailGenerationTask.

I created a PR with your fix and it works now as expected, thank you very much 🎉

**Comment by TheNetStriker** [comment]
Yes, sorry I wrote the wrong line number. Thanks for the quick fix!
