### ISSUE TITLE
Pre-fetching next images ...

### ISSUE THREAD

**Issue by Django3** [nextcloud/android#1797]
A small idea for a new app-feature:
Pre-fetching the images (low-res?). To make seamless swiping through pictures/media possible.

Scenario:
If i click on a image - immediately the previous 2 and following 2 images are loading in the background to avoid loading the next picture/media after a swipe left or right.

**Comment by tobiasKaminsky** [comment]
With the next version we will always fetch the images in a low-res / screen adapted size. This is enough for viewing and sharing via whatsapp. 
Pre-fetching +2 and -2 images sounds like a nice idea 👍
