### ISSUE TITLE
Idea for enhancement: add possibility to insert a comment

### ISSUE THREAD

**Issue by Spartachetto** [nextcloud/android#1798]
Having the possibility to insert comments from the phone app would be really useful.

This and #548 (add native tag manipulation) would mean the possibility to a near complete interaction with your files!

**Comment by tobiasKaminsky** [comment]
Thank you for this idea.
@MorrisJobke is there already an endpoint we can use?

This should then be in details view, same like on webUI.

**Comment by MorrisJobke** [comment]
cc @blizzz

**Comment by blizzz** [comment]
DAV :) you should get an attribute with, uhm, propfind? against a file with an url to the comments resource. And can fire put against those. Can deliver more info later. However via DAV is also how the web ui interacts

**Comment by Spartachetto** [comment]
any proposed milestone? ... ;-)

[thank you all!]

**Comment by AndyScherzinger** [comment]
comments can be added via #2690 which will ship with 3.3.0

**Comment by Quix0r** [comment]
How about editing and deleting?
