### ISSUE TITLE
Search in move/copy dialog crashes

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#1800]
- move / copy file
- search something
- app is crashing

The search result is tried to be shown in FileDisplayActivity as this is the normal way to show server side search results.

**Comment by kservical** [comment]
Hey @tobiasKaminsky 
I can reproduce the same bug on my smartphone.When I search a folder which doesn't exist it crash.
Moreover, when I search an existing folder, the app stay on loading without finding it. Then, When I click on  "validate" button it come back to initial step.

**Comment by nb2998** [comment]
@tobiasKaminsky Hi, I also found that when a search is made and back button is pressed,the search results are still shown rather than all contents. Does it cover here or shall it be addressed with a separate issue?

**Comment by tobiasKaminsky** [comment]
I guess this is a new issue. But it sounds familiar, so maybe there is already an open issue, but I did not found it.

**Comment by capoeira974** [comment]
When I debug with ADB , I view this logs in the  terminal.
The part are selecting is the moment when app crash.

![bug](https://user-images.githubusercontent.com/34417891/33891931-b7c05f76-df57-11e7-8f71-4aa954189583.PNG)
