### ISSUE TITLE
Sort order alpha seems not to be alpha (and is different from the server Web UI)

### ISSUE THREAD

**Issue by ldmpub** [nextcloud/android#1802]
### Actual behaviour
Sort order of files within a folder are different between Nextcloud Android app and Windows explorer
=> see 2 screenshots.

Added on Nov 11th: the server also sorts files in the "Windows's way".

![sort order alpha - under windows](https://user-images.githubusercontent.com/1452146/33021947-cc2722ca-ce03-11e7-8d1c-18bff6849113.png)
![sort order alpha - under nextcloud android](https://user-images.githubusercontent.com/1452146/33022035-09648b46-ce04-11e7-9f27-cdf89bcedc13.png)

### Expected behaviour
To be able to give names to files to order them (here files are podcasts I want to store / listen on my Android device in a certain order).
The "[" caracter is not well "ordered" ... special caracters should be first.
 
### Steps to reproduce
See the names of my files in the 2 screenshots.

### Environment data
Android version: 7.0

Device model: 
Galaxy S7

Nextcloud app version:
2.0.0

**Comment by tobiasKaminsky** [comment]
I tried it also on latest server version and there it is the same as on windows.
So we should try to match them.

**Comment by ldmpub** [comment]
@tobiasKaminsky, I also performed the test on the server side and I confirm what you are saying: Nextcloud server and Windows sort order are the same with special caracters first then digits then alphabetical.

I will change issue title accordingly.

**Comment by tobiasKaminsky** [comment]
Furthermore testing reveals that Umlaute are also handled wrong :/
While I have solved the first issue, umlaute needs a bit more thinking ;-)

**Comment by AndyScherzinger** [comment]
> While I have solved the first issue, umlaute needs a bit more thinking ;-)

Until you start realizing that there are for more character like Chinese letters... ;-)

**Comment by tobiasKaminsky** [comment]
I am trying to adapt  https://github.com/nextcloud/server/blob/9a4253ef7c34f9dc71a6a9f7828a10df769f0c32/tests/lib/NaturalSortTest.php but it is really hard. Currently "only" the ordering within the special chars is different :/
