### ISSUE TITLE
Replace Toast with Snackbar

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#1805]
As Snackbar is the "newer" android way to show small text infos, we should replace all Toast with Snackbar.
Searching for "Toast.makeText" we have 33 occurrences.

**Comment by AndyScherzinger** [comment]
Sounds good :) while we might only be able to do this for occurrences within UI screens, so we should replace all Toasts triggered in the user interface while things like services, etc. that don't have a reference to a screen can/should maybe stay with Toast, not sure.

**Comment by codedsun** [comment]
Can I Work on this issue? @tobiasKaminsky @AndyScherzinger

**Comment by AndyScherzinger** [comment]
Hi @codedsun, yes absolutely! That would be awesome!
Please let us know if you have any questions or need assistance. We are here to help:)

**Comment by harshika-arya** [comment]
@AndyScherzinger @tobiasKaminsky 
Can I work on this since it hasn't been updated for a long time?

**Comment by AndyScherzinger** [comment]
Hi @harshika-arya sure and highly welcomed. To be save you def. need to check which of them can be replaced by a Snackbar since you need to have a view where this is the displayed since not all Toasts wihtin the app's code might have a view (like some services or else).
