### ISSUE TITLE
Nextcloud android app doesn't connect

### ISSUE THREAD

**Issue by ulysse132** [nextcloud/android#1806]
### Actual behaviour
-Tell us what happens
When trying to connect in the app, typing the url of the server, I have an error message saying "Malformed server configuration"

### Expected behaviour
-Tell us what should happen
It should connect to the server
 
### Steps to reproduce
1. Install the nextcloud app, from GPlay or F-Droid
2. insert URL of the server https://subdomain.domain.fr
3. here shows the message

### Environment data
Android version: 7.1.1

Device model: Xperia XZ F8332

Stock or customized system: Stock

Nextcloud app version: 2.0.1

Nextcloud server version: 12.0.3

## Server configuration detail

**Operating system:** Linux 4.9.59-v7+ #1047 SMP Sun Oct 29 12:19:23 GMT 2017 armv7l

**Webserver:** nginx/1.10.3 (fpm-fcgi)

**Database:** mysql 10.0.31

**PHP version:** 7.0.19-1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, apc, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imagick, imap, intl, json, exif, mcrypt, mysqli, pdo_mysql, pdo_pgsql, pgsql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 12.0.3 - 12.0.3.3

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.5.2
 - bruteforcesettings: 1.0.2
 - calendar: 1.5.6
 - comments: 1.2.0
 - contacts: 2.0.1
 - dav: 1.3.0
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_external: 1.3.0
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - nextcloud_announcements: 1.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - password_policy: 1.2.2
 - provisioning_api: 1.2.0
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - updatenotification: 1.2.0
 - workflowengine: 1.2.0
Disabled:
 - admin_audit
 - encryption
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "oc4i3blxuswt",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "contacts.p8a.fr"
    ],
    "datadirectory": "\/var\/www\/html\/nextcloud\/data",
    "overwrite.cli.url": "https:\/\/contacts.p8a.fr",
    "dbtype": "mysql",
    "version": "12.0.3.3",
    "dbname": "nextcloud_db",
    "dbhost": "192.168.0.17:3307",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "maintenance": false,
    "logtimezone": "Europe\/Paris",
    "logfile": "\/var\/www\/html\/nextcloud\/data\/nextcloud.log",
    "loglevel": 2,
    "log_authfailip": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "auth.bruteforce.protection.enabled": true
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

<details><summary>LDAP configuration (delete this part if not used)</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

## Client configuration

**Android version:** 

**Device model:** 

**Stock or customized system::** 

**Nextcloud app version::** 

**Nextcloud server version::** 

## Logs

<details><summary>Browser log</summary>

```
Insert your webserver log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Do you have any special authentication?
It seems that the basic auth, that we use, is failing.

**Comment by ulysse132** [comment]
I don't know how to answer you. I just installed nextcloud as it is. How do you see that ? And how could I change it ?

**Comment by tobiasKaminsky** [comment]
I am rather blindly guessing from your error message...
Can you test "https://cloud.domain.com/remote.php/webdav" with your server?
It should be printed something like "This is the WebDAV interface. It can only be accessed by WebDAV clients such as the Nextcloud desktop sync client."
But I guess that you will see some kind of http error.

**Comment by ulysse132** [comment]
I have "500 Internal Server Error - nginx" when I go to this url with windows opera browser. I have the same message in android app.
I understand this is a nginx misconfiguration, isn't it ?

**Comment by ulysse132** [comment]
But when I go to "https://subdomain.domain.fr/remote.php/dav", I have this message : "This is the WebDAV interface. It can only be accessed by WebDAV clients such as the Nextcloud desktop sync client."

**Comment by tobiasKaminsky** [comment]
@MorrisJobke do you have an idea?
We rely on "remote.php/webdav" for checking if the server is available.

**Comment by ulysse132** [comment]
Do you need me to show you nginx configuration and site_enabled file ? Is this useful ?

**Comment by tobiasKaminsky** [comment]
I do not know it this helps, this is something the server guys need to say.
But to shorten time, maybe you can just post them.

**Comment by MorrisJobke** [comment]
> I understand this is a nginx misconfiguration, isn't it ?

Looks like this. Could you check against the configuration in https://docs.nextcloud.com/server/12/admin_manual/installation/nginx.html

If you still have problems first seek for help in the forums: https://help.nextcloud.com - there people also can help with configuration of the web server. This here is the bug tracker.

**Comment by ulysse132** [comment]
I don't know where was the faulty line but now it works. Thanks for your help !

**Comment by andreas-bulling** [comment]
@tobiasKaminsky is the latest version still checking for "remote.php/webdav" to see if the server is available? Not status.php? Problem is that with HTTP AUTH enabled I'd have to exclude the webdav directory to make the Android client work... rather annoying...
