### ISSUE TITLE
Theming: loading bar blue when not loading

### ISSUE THREAD

**Issue by alexanderdd** [nextcloud/android#1808]
### Actual behaviour
-Tell us what happens
![2017-11-24 07 18 07](https://user-images.githubusercontent.com/28591861/33198059-23115d16-d0e9-11e7-8d78-187426d3d894.png)
But when loading, it looks great, then the bar turns yellow with white dashes flying across.

### Expected behaviour
-Tell us what should happen
Theming color should also be applied to loading bar

### Steps to reproduce
1. Open app
2. 
3. 

### Environment data
Android version:
4.4.2
Device model: 
Samsung Galaxy S4
Stock or customized system:
Stock
Nextcloud app version:
2.0.1
Nextcloud server version:
12
#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
As far as I can see this is not possible on Android < Lollipop due to Android itself.
Therefore we tint only the newer androids:
https://github.com/nextcloud/android/blob/1ccf588478819bc83793028d7da0576a536602a1/src/main/java/com/owncloud/android/utils/ThemeUtils.java#L243-L247

However, this does not look good.
@jancborchardt do you have an idea what we can do in this cases?

**Comment by jancborchardt** [comment]
I would say if it's about support missing for an older version of Android, and since this only happens on themed instances, we just have to wait it out.

**Comment by AndyScherzinger** [comment]
The issue is about the progress bar being blue not the system bar being black ;)

**Comment by tobiasKaminsky** [comment]
Black? Who said anything about black? 🤔

**Comment by jancborchardt** [comment]
@tobiasKaminsky I assume @AndyScherzinger means since you refer to a piece of code about the »StatusBarColor«. :) But this is about the _progress_ bar color below the header.

**Comment by AndyScherzinger** [comment]
@jancborchardt that is exactly what I referred to 👍

**Comment by tobiasKaminsky** [comment]
Ah. ok :-)
I tried it now with the correct function (https://github.com/nextcloud/android/blob/508374ff47ca992410b1c6912ae6ebaaf82a610e/src/main/java/com/owncloud/android/utils/ThemeUtils.java#L299) but did not succeed. :-(
