### ISSUE TITLE
Empty local folder

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#181]
### Actual behaviour
- Folder name is shown as only item
### Expected behaviour
- "No content in here" should be shown.
### Steps to reproduce
1. Upload a file
2. choose an empty folder

Current master with applied #180

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky is this bug still present or fixed?

**Comment by tobiasKaminsky** [comment]
No, it seems to be fixed.
