### ISSUE TITLE
Circumvent Fingerprint Protection

### ISSUE THREAD

**Issue by r-boehm** [nextcloud/android#1811]
### Actual behaviour
You can enter the application without entering your fingerprint, even though the app is locked. This only works if the app is open and a notification (upload) is in your status bar. Clicking on that notification while inside the application will open the 'Upload' view.

### Expected behaviour
The application should not grant access without a valid fingerprint.
 
### Steps to reproduce
1. Start an upload to your Nextcloud server via the application.
2. Exit the application.
3. Reopen the application. You will now be asked to use your fingerprint.
4. Click on the upload notification in the status bar. 
5. You will now be redirected to 'Uploads'. 
6. From the side menu you can now access 'All files'.

### Environment data
Android version: 7.0

Device model: SM-G950F

Stock or customized system: Stock

Nextcloud app version: 2.0.0

Nextcloud server version: 12.0

**Comment by AndyScherzinger** [comment]
Hi @Riwolfes thanks for the hint! 

@tobiasKaminsky this is imho due ti the fact that the fingerprint or pin are only checked/asked for for the main view. So if for example via a notification any other screen is launched no check will be triggered. While this should then only happen if you come from outside not via the drawer menu...

**Comment by tobiasKaminsky** [comment]
I tested it and with newest device credentials system I have to enter pin/fingerprint to get the notification list.
