### ISSUE TITLE
Empty pic created each time a photo is uploaded

### ISSUE THREAD

**Issue by moulip** [nextcloud/android#1812]
Hi,

I have a weird issue occuring each time the auto-upload feature is uploading a picture on my remote server.
step to reproduce : 
Take a picture.
Wait for the auto-upload to kick-in
Open Gallery app and see that there is a grey pic with exclamation mark.

i simply delete the empy pic, but that's kinf of annoying.

Nextcloud client version 2.0.0
Smartphone: Samsung Galaxy S8+ recording pics on external SD-Card.

See screenshot
![screennextcloud](https://user-images.githubusercontent.com/805421/33242247-faede4ea-d2d1-11e7-9ca2-756bec504625.png)

**Comment by moulip** [comment]
It seems that bug #1751 is the same.

**Comment by tobiasKaminsky** [comment]
Tken we close it in favor of #1751
