### ISSUE TITLE
Is it supposed to sync remote files?

### ISSUE THREAD

**Issue by sprnza** [nextcloud/android#1817]
I marked some files to be available offline so once I changed them locally they are being uploaded to my server. But they never be synced if they were changed remotely. I don't have Google Services installed so my question is pretty simple. Is it supposed to work for two directions

**Comment by AndyScherzinger** [comment]
It is supposed to work both ways, yes. There seem to be issues though which is why there is some current work on this matter via https://github.com/nextcloud/android/pull/1655 which should guarantee that you always have the latest file from the server when opening a file on the client.

**Comment by sprnza** [comment]
Cool! Thanks @AndyScherzinger !

**Comment by sprnza** [comment]
Is there an intent I could use to force file sync from Tasker? There is an ability to send intents. I wasn't able to find one in AndroidManifest.xml, but could be because of my knowledge lack.

**Comment by tobiasKaminsky** [comment]
No, there is no possibility to trigger a scan from "outside".
