### ISSUE TITLE
Resized images: wrong snackbar if next image fails

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#1818]
Folder with e.g. 3 images:
1st working
2nd corrupt
3rd corrupt

- click on 1st image -> loads resized image
- but shows "no resized image available" as 2nd image is fetched in background

**Comment by tobiasKaminsky** [comment]
We are preloading the next image in background.
I could not figure out, how to show the error message only if the correct image is shown: .isVisible() is true for the current, the next and the last image "slide", to support a fluent transition, so we cannot rely on this.

@AndyScherzinger maybe you have an idea?

**Comment by AndyScherzinger** [comment]
Hmmm, is this info available then, so could we "just" slide to the corrupt image show the "error screen image" and the error message then?

**Comment by tobiasKaminsky** [comment]
As of my understanding the problem is that you do not have a way to "connect" current viewed image with the snackbar as this is running in an async task.

Having this:
1st working
2nd corrupt
3rd corrupt

And you are viewing 1st, will also load 2nd in background and then already showing the snackbar for this. 
It would be enough to suppress the snackbar until 2nd is really viewed, but I did not found a way to do this.

Sliding away from the current image is a bit weird / unexpected for the user.

**Comment by AndyScherzinger** [comment]
But do we have to show a Snackbar or would it be sufficient to just show the image error page when the users swipe to that particular image? Maybe even have the error message saying that the image is corrupt?

**Comment by tobiasKaminsky** [comment]
Snackbar is showing one of this:
No resized image available.
No resized image available. Download full image?

It is happening, if the image is corrupt or if the preview cannot be generated.
As we agreed to not download full image without any user interaction, we have to show something.
(I am not sure if we can use an embedded textview instead of a snackbar)
