### ISSUE TITLE
Unable to start application under restricted user profile

### ISSUE THREAD

**Issue by openhs** [nextcloud/android#1819]
### Actual behaviour
Message box with content "This change is not allowed by the device administrator." is shown.

### Expected behaviour
Application should start and prompt for initial credentials (server address, user and password).
 
### Steps to reproduce
1. Create a restricted user profile
  1.1 Settings -> Cloud and accounts -> Users -> Add user profile -> User (Restricted profile)
2. Switch to the newly created profile
3. Launch Nextcloud application

### Environment data
Android version: 7.0

Device model: Samsung Galaxy Tab A 10.1

Stock or customized system: Stock

Nextcloud app version: 2.0.1

Nextcloud server version: n.a.

**Comment by tobiasKaminsky** [comment]
As our app needs access to storage and this is not allowed for restricted profiles, I am unsure how to handle this.
If we remove the access to storage the app (within a restricted profile) could only access its own files, so no real upload of new files or receiving files.

**Comment by openhs** [comment]
The Nextcloud application has allowed access to the storage (in Settings -> Apps -> Nextcloud -> Permissions).  Also other apps can access the storage.  For example if I take a photo then I can access it by Ghost Commander.  All under the restricted profile.

My guess is that it has something to do with the account management.  Here (https://help.nextcloud.com/t/android-app-does-not-start-under-restricted-profile/18656/3) is reported that other apps can handle accounts under restricted profiles just fine, others with some restrictions.

**Comment by tobiasKaminsky** [comment]
I tried it again with LineageOS on my OnePlus 3.
On android settings -> accounts all was greyed out. So it seems that this restricted profile is not allowed to set up any account.
ForkHub, which also creates an account, is also crashing with the same error.

**Comment by openhs** [comment]
I can confirm that in the settings no account creation is possible either.  But then I am not sure whether using the Android account management to handle accounts in Nextcloud app is the right choice.  I do not see any reason why users in restricted profiles should not be able to log in via the app while having no problem log in to the web interface.

**Comment by tobiasKaminsky** [comment]
I tested this once again with LineageOS and Android 9.
There I added a new user and installed Nextcloud.
I could successfully login and download files.

Can you retest?

**Comment by openhs** [comment]
Currently the Nextcloud application is not even available for restricted user accounts.  Perhaps Android is filtering it out because it needs some permissions which are not available for restricted users (just a wild guess).  So I cannot retest.

Note that on Galaxy Tab where I've tested it there are two types of accounts "normal" and restricted.  The problem is only on restricted accounts.  LineageOS (on a phone) did not gave me a choice for user account type so I assume it always creates "normal" account therefore it is not reproducible there.

I think that in order to enable log-in Nextcloud app would have to manage credentials on its own as some other apps are doing (K9 Mail, Conversations).  Accounts from those apps does not appear in Android's settings -> Accounts.  However Nextcloud accounts do appear there.

**Comment by tobiasKaminsky** [comment]
Thanks for the info.
Unluckily I do not such a device, so I cannot test it.



> to manage credentials on its own

This is planned in mid-term future, so maybe this issue then got automatically solved then.

**Comment by tobiasKaminsky** [comment]
Can you retest this with latest 3.14 and report if it works?

**Comment by openhs** [comment]
Retested with 3.14.1.  It works now, many thanks for the fix!  (I did not have access to the device so the retest took longer.)

The behaviour is a bit rough though.  I will describe it here, although it is not the reason to keep this bug open.

App starts right to the main screen as if a user was already logged in.  It seems that it is not prepared to work smoothly in this state.

In order to add an account user has to click to an empty space where normally user icon/avatar is shown.

When '+' icon is pressed (to upload files) an exception is thrown.

Menu icon does not open the menu.  However sliding from the screen edge does open it.

In the screen which appears after clicking at "Add account" user needs to click twice at "Log in" button.

That is all what I've found.  If you want to fix some of those issues I can test it.  Mind there will be some delay as I am using F-Droid version.

**Comment by AndyScherzinger** [comment]
@openhs thanks for the heads up and re-testing. Would you mind opening a new issue for your described findings? That would be highly appreciated, other than that on the fresh install does it just lead to the behavior you described or do you see any crash log dialogs popping up?

**Comment by openhs** [comment]
I have created two new Issues for the findings.

> do you see any crash log dialogs popping up?

Yes a pop-up "This change is not allowed by the device administrator." appeared actually.  I have mentioned that in the new Issue report.

**Comment by AndyScherzinger** [comment]
Did any Nextcloud crash dialog pop up or rather a small bar at the bottom with a report button?

**Comment by openhs** [comment]
The pop-up I am talking about in previous comment (https://github.com/nextcloud/android/issues/1819#issuecomment-752893397) was a small window visible after I did exit from Nextcloud.  It is most likely a message from Android system.  It is the same one as described in the first comment.

The exception/crash after pressing '+' button mentioned in the closing comment https://github.com/nextcloud/android/issues/1819#issuecomment-752687333 was a screen with a call stack and possibility to report it.
