### ISSUE TITLE
Thumbnails don't show when NC used as a document provider

### ISSUE THREAD

**Issue by Bugsbane** [nextcloud/android#1827]
### Actual behaviour
When using Android's native file choosing application in a device with the Nextcloud app installed, the option is given to select files from the Nextcloud account, however images show up without any thumbnail, unlike if they are in another source like Google drive.

### Expected behaviour
Thumbnails show up when browsing images on the Nextcloud account via the Android file selector.
 
### Steps to reproduce
1. Install NC app with access to an account with images
2. Navigate to any webpage that let's you select an image to upload and click the button to do so
3. When the file selector comes up, choose Nextcloud as the source and navigate to the Nextcloud folder with your images

### Environment data
Android version:
6.0.1

Device model: 
ZTE Grand Prime

Stock or customized system:
Stock

Nextcloud app version:
2.0.1 from Fdroid

Nextcloud server version:
12.0.3

**Comment by tobiasKaminsky** [comment]
You are partly right :-)
If the file is downloaded a thumbnail is shown. 
So as an enhancement it should also show all the thumbnails of non-downloaded images and additionally try to fetch them if they are not already locally cached.

Code ref:
https://github.com/nextcloud/android/blob/4d49735c7bdd5487a45bc211fafd6d53fc96d983/src/main/java/com/owncloud/android/providers/DocumentsStorageProvider.java#L130-L146

**Comment by Bugsbane** [comment]
Sounds perfect.

**Comment by tobiasKaminsky** [comment]
With upcoming version (and current dev version) this should be fixed/included, please test it and if there is something not working as expected, please re-open.
