### ISSUE TITLE
Android 连不上服务器

### ISSUE THREAD

**Issue by ZeronoFreya** [nextcloud/android#1829]
显示
服务器不太给力

PC端没有问题

环境：
CentOS 7 x64
Google BBR加速
Docker 安装

**Comment by tobiasKaminsky** [comment]
Please write in English, as this is our support language.
From tranlator I guess that you have a problem with your server?

**Comment by tobiasKaminsky** [comment]
No response within the last month, therefore closing.
Please feel free to reopen with additional infos, if the problem still exists.
