### ISSUE TITLE
nc-keypair files on /sdcard

### ISSUE THREAD

**Issue by ardevd** [nextcloud/android#1833]
I notice that the Nextcloud app stores a keypair on the /sdcard partition under Nextcloud/nc-keypair/. The two files listed are push_key.priv and push_key.pub. 

Is there any good reason for a keypair to be stored on the world-readable/writable /sdcard partition? Why isnt these files at least stored in the app's private data folder? I havent looked through the source to find out what the keypair is used for but this doesnt look good. I can see they keyfiles are generated in PushUtils.java and are seemingly used to push some sort of registration token to the OwnCloud server.

I highly recommend storing these somewhere else. I'd be happy to provide a patch for this. Since the keys are seemingly only used for a single operation it would be trivial to simply store them in a more appropriate location and either keep them there or delete them after use since it doesnt seem like they are used more than once.

**Comment by mario** [comment]
The push only works for Nextcloud, not ownCloud. Keep in mind the keys location is determined by the method of getting the storage location that was always there, so maybe that's the real problem ... :-/

You are more than invited to provide a patch, but please do it in a way that:
- fixes the storage location
- moves the keys to proper location if they're in a wrong location
- keeps the keys as they are indeed used afterwards and not only once :)

Thanks,
Mario

**Comment by mario** [comment]
@ardevd related to this I'm afraid...

https://github.com/nextcloud/android/issues/1707

**Comment by ardevd** [comment]
@mario I believe I might have fixed both issues with the associated pull request.

**Comment by mario** [comment]
@ardevd please see my questions in that PR :)

**Comment by AndyScherzinger** [comment]
fixed via #1954
