### ISSUE TITLE
Jumping NC symbol at status bar

### ISSUE THREAD

**Issue by Django3** [nextcloud/android#1835]
Hi there,

from time to time or at almost every unlock i see the nextcloud symbol a view seconds jumping in the status bar. Cause it is trying to sync my phone but i activated only syncing if i am connected with a wifi. So it tried to sync but is not syncing at the end cause i am not in the wifi or the file is missing (cause i deleted it already on my phone) - these steps are correct but would it be possible to hide the attempt and only showing something in the status bar if a file is really in the syncing process?

[Here is a screen clip]

Phone: Huawei G8 - Android 5.1

Btw.: is the next app release planed for this year?

**Comment by tobiasKaminsky** [comment]
I think this is related to auto upload scanning.

**Comment by tobiasKaminsky** [comment]
For a pending upload list we should check all conditions and only try to loop over those uploads where the requirements are met, e.g:
10 pending files:
- 5 with wifi (cause of video)
- 2 with nothing, but server is unavailable 
- 3 have no requirements

Instead of trying all 10 pending uploads, it would only start those 3 ones.

**Comment by jospoortvliet** [comment]
This is also an energy saving issue, see https://twitter.com/Nextclouders/status/939982102216527878

**Comment by mario** [comment]
https://github.com/nextcloud/android/pull/1843

Might fix the flashing issue and hopefully some of the energy stuff.

**Comment by mario** [comment]
@AndyScherzinger @tobiasKaminsky can you confirm this is fixed now?

**Comment by AndyScherzinger** [comment]
@mario I'll have to check and see if it happens on my device (running Android O)

**Comment by jospoortvliet** [comment]
Any updates, @AndyScherzinger ?

**Comment by tobiasKaminsky** [comment]
@jospoortvliet as you experienced this too, you can also try the dev version:
https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#dev-release

**Comment by AndyScherzinger** [comment]
Haven’t experienced the flashing lately but also updated to Android O where auto upload doesn’t get auto restarted.

**Comment by jospoortvliet** [comment]
I haven't seen this anymore but that might also be due to me being home atm, where the phone can simply upload. I will be away for a week, will see if it still shows up. Maybe it's fixed with the changes to 2.0.x...

**Comment by tobiasKaminsky** [comment]
Still happening?

**Comment by Django3** [comment]
No, it's not happening anymore in 3.0 :) Thank you guys!
