### ISSUE TITLE
Show message on refreshing if there is no connection

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#1837]
As we merged https://github.com/nextcloud/android/pull/1655 to soon, this remains:
> If mobile data is disabled and I open up e.g. a text file it shows shortly the dialog, then dismisses it, leading to the impression that we now have the updated file (which might be true).
So if the refresh fails we should show a snackbar(?) that says "we could not update the file. Last version available is shown" (or similar)

**Comment by tobiasKaminsky** [comment]
This must be done prior releasing 2.1.

**Comment by AndyScherzinger** [comment]
👍

**Comment by mario** [comment]
https://github.com/nextcloud/android/pull/1946

**Comment by AndyScherzinger** [comment]
Pr has been merged thus closing
