### ISSUE TITLE
Upload whole folder

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#184]
When uploading make it possible to choose the complete folder with all subfolder.

**Comment by AndyScherzinger** [comment]
Sounds good to me!

I see two scenarios:
* select a folder: upload the folder and all its content including all sub folders (so the selected folder also gets created on the server)
* go into a folder with sub folders and choose "select all": no separate folder gets created, all selected files, folders, the content within the sub folders gets uploaded to the chosen location.

Any thought? @tobiasKaminsky @jancborchardt ?

**Comment by tobiasKaminsky** [comment]
:+1:

**Comment by jancborchardt** [comment]
Yup, sounds good!

**Comment by AndyScherzinger** [comment]
Dev hint - corresponding activity: 
https://github.com/nextcloud/android/blob/master/src/com/owncloud/android/ui/activity/UploadFilesActivity.java

**Comment by kollix** [comment]
I don't see the second scenario as needed:

"go into a folder with sub folders and choose "select all": no separate folder gets created, all selected files, folders, the content within the sub folders gets uploaded to the chosen location."

If I have already managed my files in subfolders on the mobile device, why would I NOT want to create exactly this structure on the server ?

**Comment by tobiasKaminsky** [comment]
Was requested today again via email.

**Comment by seanlynch** [comment]
Just tried to do this myself and was quite surprised to find it isn't supported.

**Comment by xXSTrikeXx** [comment]
refs: #285 #1328

**Comment by AndyScherzinger** [comment]
@xXSTrikeXx nope ;) this is related to manual upload where atm you can only choose files but not a folder for upload.

**Comment by QuelonaSec** [comment]
This feature is really mandatory. Along with a checkbox allowing full (initial) upload of a folder in the auto upload section.

Use case: automatic backup of a app folder (which is almost working thanks to the improvement in 2.0)

**Comment by avanc** [comment]
+1 for this Feature Request.
I have a lot of data in my phone which I want to backup.

**Comment by leonardsaers** [comment]
+1
I'm now trying next cloud and I'm happy with how it works. However uploading an entire directory from the mobile is a feature which I'm really missing.

**Comment by subterfugium** [comment]
I've been using FolderSync to backup my /sdcard/ (JUST because I can) overnight on daily basis. I was planning to switch nextcloud app as it's available in FDroid, but there's no way I'm able to achieve full backups with Nextcloud app without folder upload (including subfolders) options. I thought auto-upload would have done this, but it didn't and that's how I ended up adding this comment.

**Comment by aliarshad9691** [comment]
I tried to upload a folder without selecting any file...
it did not show any error message... infact I saw a notification saying uploading files...
nothing happened for 30 mins then I do a select all and upload...

**Comment by hirvinen** [comment]
Has there been any progress on this?

**Comment by thewizardstudio** [comment]
+1 This feature would be a huge help

**Comment by bushrang3r** [comment]
I really appreciate the work that has been done with auto-upload so far in Nextcloud. 
However, has there been any more progress with this? > Uploading folder also uploads its sub-folders.

**Comment by AndyScherzinger** [comment]
Hi @bushrang3r due to a limited number of people working on the app (code-wise), no. We are always happy about new contribution and contributors. So if you or someone else want to help and give it a try we are happy to help to get to now the code base.

**Comment by bushrang3r** [comment]
Thanks @AndyScherzinger
I'd love to help but unfortunately I'm just a beginner coder. I'll work harder until I get to the point where I can help 😀

**Comment by bushrang3r** [comment]
About selecting sub-folders to auto-upload. Currently it can't be done, but it seems that when I update a file that is in a sub-folder of the folder I selected, the sub-folder and it's file are auto-uploaded. I'm not complaining at all, but is this expected behaviour?

**Comment by mario** [comment]
Yes it is @bushrang3r.

**Comment by oz42** [comment]
Anything new here? This is a must.

**Comment by sanvit** [comment]
Would like and update on this as well

**Comment by tobiasKaminsky** [comment]
No date due to time constraints, but we have it on our roadmap :-)

**Comment by 151henry151** [comment]
> I don't see the second scenario as needed:
> 
> "go into a folder with sub folders and choose "select all": no separate folder gets created, all selected files, folders, the content within the sub folders gets uploaded to the chosen location."
> 
> If I have already managed my files in subfolders on the mobile device, why would I NOT want to create exactly this structure on the server ?

because, for example, on my android device there are tons of random subfolders and weird folder structures created by my various apps. I would like to just upload all photos on the entire device, no matter which subfolder they are in, to one directory on my nextcloud.

**Comment by uvwxy** [comment]
@tobiasKaminsky  you can do it :)

**Comment by eZii-jester-data** [comment]
nextcloud is really funny :D

**Comment by eZii-jester-data** [comment]
300$ (-10% bountysource fee) for an android implementation that is released to the play store.

What are you guys smoking.

**Comment by kilves** [comment]
I'm gonna look into this. Looking at the code this should be easy to implement.

**Comment by AndyScherzinger** [comment]
implemented via #184

**Comment by jospoortvliet** [comment]
https://github.com/nextcloud/android/pull/7877 I guess is what Andy meant 🚀

**Comment by AndyScherzinger** [comment]
Thanks for clarifying Jos ❤️

**Comment by thaingoc2604** [comment]
where can i find the source code for the above function

**Comment by AlvaroBrey** [comment]
> where can i find the source code for the above function

https://github.com/nextcloud/android/pull/7877

**Comment by thaingoc2604** [comment]
I still don't have the shape used by the writing code, can you be more specific
