### ISSUE TITLE
New release schedule

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#1840]
As we see our milestone planning is not working quite well.
With the new dev version based on master we always have users who test our latest master versions, so we can hopefully get errors and bug reports more recent.
So I suggest that we release 
- every 2 months a stable version, currently 2.x
     - branch off from master, publish RC1
     - new PRs can be merged into master while stabilizing 
     - wait 1 week and if not publish it as stable
- if needed a minor version 2.x.y
     - fix bug on master
     - backport it to 2.x branch 

With 2 months as a (short) cycle we can ensure that not too much new is into it, so we hopefully have only 1-2 RC.
If you, @mario aand @AndyScherzinger agree, I would copy this into  wiki page on github, same as in /server and also would keep track of releasing it on time.
(the next release will have to wait a bit longer as we want to have E2E included)

**Comment by tobiasKaminsky** [comment]
If we merge a PR we should set the correct milestone to keep track of it for changelog/statistics.

**Comment by AndyScherzinger** [comment]
👍 absolutely fine with the readjustment 👍

**Comment by rullzer** [comment]
Once you branch off don't forget to mark the branch as protected. So that nobody can force push and the status checks need to pass etc.
