### ISSUE TITLE
Unable to Upload file... 

### ISSUE THREAD

**Issue by Deltafox79** [nextcloud/android#1842]
### Actual behaviour
-Tell us what happens
When try to Upload a file I give connection Error... 
Whit Google Store app version Upload file work correct... 
### Environment data
Android version:
7.1.2
Device model: 
Sm-t805

Nextcloud app version:
2.0.0 build 20000099, latest commit here 2 day ago
Nextcloud server version:
12.0.4

**Comment by tobiasKaminsky** [comment]
There is already a fix https://github.com/nextcloud/android/pull/1834.

**Comment by Deltafox79** [comment]
Fix #1834 not reso e problem because I have Compiled apk yesterday whit this Fix inside and Upload not work...

**Comment by Deltafox79** [comment]
I have this into log 👍 

  | Narrowing  occurred during type inference. Please file a bug report on  bugs.php.net at  ..../nextcloud/lib/composer/composer/ClassLoader.php#444
-- | --

**Comment by tobiasKaminsky** [comment]
Then this is a different bug.
Do you have more context of the error in the logs?

@MorrisJobke do you have an idea as this seems to b server related?

**Comment by MorrisJobke** [comment]
> @MorrisJobke do you have an idea as this seems to b server related?

Yes - looks weird - never have seen this kind of error :/

**Comment by Deltafox79** [comment]
No other log in nextcloud Server.. but android app download from store work fine... only develop github version compiled today also have this byug..

**Comment by Deltafox79** [comment]
Commit Fix #1834 have fixed the problems.. Tk's

**Comment by AndyScherzinger** [comment]
@Deltafox79 now I am confused 😆 Does #1834 fix it or not? Because 

> Fix #1834 not resolve the problem because I have Compiled apk today whit this Fix inside and Upload not work...

and

> Commit Fix #1834 have fixed the problems.. Tk's

**Comment by Deltafox79** [comment]
Sorry, #1834 he had not yet been committed. but it solves the problem..

Regards
