### ISSUE TITLE
App Android crash on click left menu Activity...

### ISSUE THREAD

**Issue by Deltafox79** [nextcloud/android#1848]
### Actual behaviour
-Tell us what happens
App crash when click on left menu Activity

### Expected behaviour
-Tell us what should happen
 
### Steps to reproduce
1.  Open App
2.  Click on Left menu Activity
3. 

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:
2.0.0 dev
Nextcloud server version:
12.0.4
#### Android LogCat
12-11 18:45:15.930 13669 13669 D AndroidRuntime: Shutting down VM
12-11 18:45:15.931 13669 13669 E AndroidRuntime: FATAL EXCEPTION: main
12-11 18:45:15.931 13669 13669 E AndroidRuntime: Process: com.nextcloud.client, PID: 13669
12-11 18:45:15.931 13669 13669 E AndroidRuntime: java.lang.ClassCastException: java.util.ArrayList cannot be cast to com.owncloud.android.lib.resources.activities.models.Activity
12-11 18:45:15.931 13669 13669 E AndroidRuntime:        at com.owncloud.android.ui.adapter.ActivityListAdapter.setActivityItems(ActivityListAdapter.java:105)
12-11 18:45:15.931 13669 13669 E AndroidRuntime:        at com.owncloud.android.ui.activity.ActivitiesListActivity.populateList(ActivitiesListActivity.java:280)
12-11 18:45:15.931 13669 13669 E AndroidRuntime:        at com.owncloud.android.ui.activity.ActivitiesListActivity.access$400(ActivitiesListActivity.java:83)
12-11 18:45:15.931 13669 13669 E AndroidRuntime:        at com.owncloud.android.ui.activity.ActivitiesListActivity$3$1.run(ActivitiesListActivity.java:225)
12-11 18:45:15.931 13669 13669 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:751)
12-11 18:45:15.931 13669 13669 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
12-11 18:45:15.931 13669 13669 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
12-11 18:45:15.931 13669 13669 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6186)
12-11 18:45:15.931 13669 13669 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
12-11 18:45:15.931 13669 13669 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
12-11 18:45:15.931 13669 13669 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
12-11 18:45:15.933   879 25565 W ActivityManager:   Force finishing activity com.nextcloud.client/com.owncloud.android.ui.activity.ActivitiesListActivity
12-11 18:45:15.937   879 25565 W ActivityManager:   Force finishing activity com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity
12-11 18:45:15.999   879 17645 I OpenGLRenderer: Initialized EGL, version 1.4
12-11 18:45:16.000   879 17645 D OpenGLRenderer: Swap behavior 1

**Comment by ardevd** [comment]
What device are you using?

**Comment by Deltafox79** [comment]
Every time,  my device nexus 6 Android 7.1.2 regards

**Comment by ardevd** [comment]
I have the Nexus 6 with Android 7.1.1 and I am not able to reproduce your error.

Your stack trace indicates that the generic objects passed to setActivityItems failed to cast to Activities but are seemingly ArrayList objects instead. I suspect the parsing of activities is the actual problem here. Perhaps someone else have seen this before?

**Comment by AndyScherzinger** [comment]
Looking at the actual code on ```master``` this would still happen and I'd also guess it is related to the server response.

@nickvergessen do you have an idea why or when this could happen?

**Comment by tobiasKaminsky** [comment]
@Deltafox79 do you really use 2.0.0 and not latest dev version?
2.0.0 is working fine for me with a 12.0.4, whereas latest dev version / master indeed leads to a crash.
(I will fix it soon)

**Comment by Deltafox79** [comment]
Hi As write the bug is present on 2.0.0 dev version compiled from this github because on v2.0.0 from playstore work fine no crash--

**Comment by tobiasKaminsky** [comment]
We refer to the dev version as only "dev version". Technically it will be the upcoming 2.1.

**Comment by tobiasKaminsky** [comment]
I can confirm that this is crashing on 20171212, but not on master.
So this should be working tomorrow.
