### ISSUE TITLE
Music player progress slider theming is broken (can't see progress)

### ISSUE THREAD

**Issue by anasem** [nextcloud/android#1849]
### Actual behaviour
- Music player progress slider shows one color with no indicator to see what part of the current  track has passed.

![screenshot_20171211-193303](https://user-images.githubusercontent.com/26265640/33847681-a7323e88-deab-11e7-840e-3d833e3d57db.png)

### Expected behaviour
- The progress bar should show differently. 
 
### Steps to reproduce
1. Play a downloaded track in Nextcloud app.

### Environment data
Android version:
6.0 
Device model: 
Motorola Moto G (2nd Generation)

Stock or customized system:
Stock
Nextcloud app version:
2.0.0
Nextcloud server version:
12.0.3

I apologize if this has been reported before, I've searched the issues and couldn't find anything.

**Comment by AndyScherzinger** [comment]
Hi @anasem, thank you for reporting this issue. This has been reported already via #1761 and has been fixed via #1763 and will ship with the next stable release.

**Comment by AndyScherzinger** [comment]
No apologies necessary 😃
