### ISSUE TITLE
Upload view: switch to Grid view

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#185]
When choosing a file from within the app it should be possible to switch to grid view.

**Comment by AndyScherzinger** [comment]
Good call, especially for the camera folder a quite useful feature! :+1: 
Should put that in the three dot overflow menu imho.

**Comment by tobiasKaminsky** [comment]
And the view should be saved and restored as the next view, just like everywhere else.

**Comment by AndyScherzinger** [comment]
fine with me, yes :+1:

**Comment by AndyScherzinger** [comment]
Dev hint: The grid view implementation/switching can be found here for the general file listing and is already in place (for this view, not active for upload views):

https://github.com/nextcloud/android/blob/master/src/com/owncloud/android/ui/activity/FileDisplayActivity.java#L597
