### ISSUE TITLE
Move from Preference to ArbitraryDataProvider

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#1850]
See code review comments https://github.com/nextcloud/android/pull/1831#pullrequestreview-80933483

--> Move to ArbitraryDataProvider

**Comment by tobiasKaminsky** [comment]
👍 
This is very easy as we do not need to have a transition. On an upgrade it will just once more checked for the external links.

**Comment by mario** [comment]
We do need to remove them from prefs
