### ISSUE TITLE
Change userAgent to Nextcloud-android

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#1852]
For E2E we need a way to prevent all older clients to access an encrypted folder, as otherwise they will sea and can delete the encrypted files, but cannot do something useful with it.
As we currently use the old "onwcloud-android/$versionID" user agent we cannot block the clients depending on versionID as we would have to block <2.1 and so a real owncloud client 2.5 can still access the encrypted folder.
Therefore we need to change this to "Mozilla/5.0 (Android) Nextcloud-android/2.1" instead of "Mozilla/5.0 (Android) ownCloud-android/2.1"
I tested it and it works without a server change.
I am unsure about the sideffects, e.g. can oC users still use our client on their server.

@mario @AndyScherzinger 
@schiessle for server

**Comment by AndyScherzinger** [comment]
Imho you can't do this since it'll break the servers file firewall... At least that has been the reason why we revert this change when we forked oC back in the days, see https://github.com/nextcloud/android/issues/120 cc @LukasReschke

**Comment by schiessle** [comment]
@AndyScherzinger I think we could easily update the regex as we already did for IOS: https://github.com/nextcloud/server/blob/master/lib/public/IRequest.php#L70

**Comment by rullzer** [comment]
Please wait at least a month or so after we released all the server updates. Else people that did not update their server yet might run into issues.

**Comment by tobiasKaminsky** [comment]
@rullzer what issues could that be? I had a look where it is used, but it was only a handful of usages.
And I am currently testing it with NC12 and also do not experience any problems.

Waiting is also a bit problematic as this required for E2E and this we want to release at the same time as NC13 stable.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky I am not sure if you need to configure anything in regards to the file firewall

**Comment by rullzer** [comment]
Let me check in depth later. But I believe there was some auth check we did on the user agent string. But maybe we already fixed that in the android client so it is actually not needed anymore :P

**Comment by tobiasKaminsky** [comment]
@rullzer Just ping me. Björnli is also having a look into the server side code.

**Comment by tobiasKaminsky** [comment]
To not have any nasty side-effects, I will change the user Agent only for those calls to E2E server app.
All other calls use the old/default user agent.

After some releases we can change this and use everywhere our nc user agent.

**Comment by tobiasKaminsky** [comment]
As @schiessle implemented it that only Nextcloud user agents (UA) are allowed, I tried to use our app with my suggested approach: use new user agent only for E2E calls.
The problem is, that even a regular propfind (on any folder) needs to be changed to new UA.
Also for upload/download everything needs to be changed or at least check if we need to set the new UA.

I will try to get it working, but I fear that the easiest solution is to use the new UA and fix the things that break, as these are hopefully way fewer than this currently fiddling around.

**Comment by mario** [comment]
Can't we just use the new user agent if we're on 13?

**Comment by tobiasKaminsky** [comment]
This is a nice idea 👍 
I will try it and see if this works or has any side-effects.

**Comment by mario** [comment]
Let's just make sure 13 supports the new user agent completely :P cc @rullzer

**Comment by tobiasKaminsky** [comment]
Setting the new/old user agent based on server is the same "mess" as with setting it based on encryption status:
Currently we are setting the user agent in https://github.com/nextcloud/android/blob/master/src/main/java/com/owncloud/android/MainApp.java#L119

And while init of OwnCloudClient this is just read:
https://github.com/nextcloud/android-library/blob/master/src/com/owncloud/android/lib/common/OwnCloudClient.java#L88-L89

To change this, I added a boolean to change the user agent. Therefore it is no difference if we base on NC13 or on encryption.
I will leave it based on encryption status for now, as this should have lesser (potential) side effects if E2E is not used on NC13.

Sooner or later we should change to NC user agent anyways.

**Comment by AndyScherzinger** [comment]
I'm closing the issue for now. Please reopen if still valid but I think this can just be cosed @tobiasKaminsky
