### ISSUE TITLE
.mp4 preview missing

### ISSUE THREAD

**Issue by johnjgsmith** [nextcloud/android#1854]
### Actual behaviour
-There's no preview for mp4 videos. My mobile takes .mp4 videos and when uploading with InstantUpload to my self hosted nextcloud, there's no preview pictogram. See this picture: https://photos.app.goo.gl/x6zPFfjZfyk6a3oA3 
I don't know if this is an issue with my installation, or if there's no preview at all.

### Expected behaviour
-Tell us what should happen
I expected to see a preview pic for mp4 files. Either a "still" of a random frame or the first frame of the video. If this is not possible, maybe a default pictogram for all MP4s.

### Steps to reproduce
Check pictures in the InstantUpload folder in your browser (Chrome 63 on Kubuntu 17.04)

### Environment data
Android version: 7.0

Device model: Samsung Galaxy Note5

Stock or customized system: Stock

Nextcloud app version: 2.0.0

Nextcloud server version: 12.03. Installed on FreeBSD 11.1, with Apache 2.4, MariaDB 10.2, Redis and PHP 7.1

**Comment by AndyScherzinger** [comment]
Cc @MorrisJobke since the screenshots shows the server's web ui.

**Comment by MorrisJobke** [comment]
We don’t have this yet - Needs to be developed as a preview provider in the server/as an app

**Comment by AndyScherzinger** [comment]
Thanks for the feedback Morris, so closing this issue for Android since the Android client would display the preview if served by the server-side.

**Comment by johnjgsmith** [comment]
Just want to note that the Android app is fine, but icons are not showing in the browser.

**Comment by tobiasKaminsky** [comment]
@MorrisJobke according to the screenshot in first post, which is a web ui screenshot, it is kind of weird that there is no icon at all. At least a placeholder as fallback should be there, or?

**Comment by MorrisJobke** [comment]
> @MorrisJobke according to the screenshot in first post, which is a web ui screenshot, it is kind of weird that there is no icon at all. At least a placeholder as fallback should be there, or?

Yes. We need: web server log, nextcloud log and the web dev tools requests to analyse what went wrong. And please open this as ticket in the nextcloud server repo.
