### ISSUE TITLE
E2E Show info bevor creating first key pair

### ISSUE THREAD

**Issue by tacruc** [nextcloud/android#1855]
### Actual behaviour
-Tell us what happens
Keys are created and user is ask to store the secret in a safe place.

### Expected behaviour
First make shure that the user is somewhere where he has a pen and paper to write the words down, or let him cancel the process at this point.

I think this is important maby the user is not in a save location someone could be watching him. Thinking of somebody is having a presentation opening by mistake a folder marked as encrypted some time before, or he is like me laying in a hotel room without pen and paper. The user could although just sit in the tram or subway playing with new features.

So i think we can not allways expect the user to have something to write down the words.

**Comment by tobiasKaminsky** [comment]
Thank you for this very good and necessary idea 👍 
What do you think regarding the wording?
(also @jancborchardt)

![2017-12-13-150643](https://user-images.githubusercontent.com/5836855/33942776-44fdb89c-e017-11e7-8a17-d505708cae40.png)

**Comment by tacruc** [comment]
I like the message but I think ordinary people are irritated by the word mnemonic. Maby better a secred or 12 secred words.

**Comment by jancborchardt** [comment]
@tobiasKaminsky instead of adding another step before, can we simply have a cancel option in the first view? That would be much preferred.

If not, some feedback:
- Cancel button should be to the left if possible
- »Next« should be labeled more relevant »Set up encryption«
- Agree with @tacruc on the text, how about this:
> You will have to note down a secret 12 word phrase which allows you to set up encryption on other devices.
> Please only continue if you are in a safe location and able to note down the phrase.

**Comment by tobiasKaminsky** [comment]
I thought if we put it in one screen it is too much text.
Also the next screen already shows the mnemonic.

Position of "cancel" is the android styling, I cannot adjust this.

![2017-12-13-155555](https://user-images.githubusercontent.com/5836855/33945037-29b2848a-e01e-11e7-90a5-d7f07a541cc8.png) ![2017-12-13-155559](https://user-images.githubusercontent.com/5836855/33945038-29de5e2a-e01e-11e7-9e5a-65b5ef719983.png)

**Comment by tacruc** [comment]
I like the right onem too. Maby
"This words are like a very strong password: It provides full access to all your encrypted files. Please write it down and keep it somewhere safe and private."
would be enough and a little shorter.

**Comment by tobiasKaminsky** [comment]
I am fine with the proposed changes.

@jancborchardt  ?

**Comment by jancborchardt** [comment]
What's the problem with only having a "Cancel" action in the modal with the phrases? No need to add the extra step with a bunch of text before, cause when you see the phrase and realize you can't note it down or aren't in private, you can cancel. Next time it will be a different phrase anyway, right?

That's also what @tacruc mentioned above

> or let them cancel the process at this point

**Comment by tobiasKaminsky** [comment]
Well, no real problem, but then I have to revert all of the stuff...
so what is the wording then? Cause I just want to do it only once more.

**Comment by tobiasKaminsky** [comment]
Solved.
This is the one and only screen, but it allows to cancel.

![2017-12-15-113721](https://user-images.githubusercontent.com/5836855/34038335-557f962e-e18c-11e7-96b7-6c50414f656c.png)

**Comment by tobiasKaminsky** [comment]
Thank you @tacruc 🎉

**Comment by tacruc** [comment]
@tobiasKaminsky thank you for fixing and responding so fast.
