### ISSUE TITLE
nextcloud-dev-20171213 does not honor "Only upload on Wi-Fi" setting

### ISSUE THREAD

**Issue by tinyboxvk** [nextcloud/android#1858]
### Actual behaviour
-The client will try to auto upload even if it's on cellular network with "Only upload on Wi-Fi" setting turned on.

### Expected behaviour
-The client should honor this setting.
 
### Steps to reproduce
1. Turn on auto upload on a specific folder, say Camera
2. Take a photo

### Environment data
Android version: 7.1.1

Nextcloud app version: dev 20171213

Nextcloud server version: 12.0.4

**Comment by tinyboxvk** [comment]
Nextcloud dev 20171208 does not have this problem.

**Comment by tobiasKaminsky** [comment]
I tried it with my onePlus 3 and dev 20171213, but could not reproduce it.
Have you recently enabled this option? Maybe it was somehow the "old state"?

**Comment by tinyboxvk** [comment]
I installed the app version 20171208 from f-droid and everything worked fine. Later I uninstalled the app and reinstalled version 20171213 from https://download.nextcloud.com/android/dev/ and this broke "Only upload on Wi-Fi". Then I uninstalled 20171213 and reinstalled 20171208 from f-droid because that one worked. Recently f-droid updated the app to 20171213 and broke this once again.

**Comment by tobiasKaminsky** [comment]
@mario do you have an idea?
