### ISSUE TITLE
E2EE only working for admin user (initial user), not for any other users

### ISSUE THREAD

**Issue by cleary** [nextcloud/android#1859]
### Actual behaviour
- Login as any user other than the initial admin user
- Create a new folder, Set as Encrypted (padlock appears)
- Click on the folder to view it, a series of dialogs appear:
"Generating New Keys..."
"Error: Retrieving keys was unsuccessful, please try it again"

(Trying it again is not helping)

### Expected behaviour
- Login as any user other than the initial admin user
- Create a new folder, Set as Encrypted (padlock appears)
- Click on the folder to view it, a series of dialogs appear:
"Generating New Keys..."
"Note your encryption passphrase ... etc"

### Steps to reproduce
(As above)

### Environment data
Android version:  Android 7.0

Device model:  Samsung S8  

Stock or customized system: Stock

Nextcloud app version: v2.1.0-e2e-01 

Nextcloud server version: v13.0.0beta3

#### Web server error log
```
<no logs>
```

#### Nextcloud log (data/nextcloud.log)
```
<no server logs generated by the error>
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
@schiessle do you have an idea why only admin works?
I tested it locally and with "my" test instance and never had this problem.

**Comment by yb171** [comment]
I see the same problem as described, only I am using the initial and only user setup on the device.

Environment data
Android version: Android 8.1.0
Device model: Google Pixel 2 XL
Stock or customized system: Stock
Nextcloud app version: v2.1.0-e2e-01
Nextcloud server version: v13.0.0beta3

**Comment by mario** [comment]
@tobiasKaminsky fixed?

**Comment by tobiasKaminsky** [comment]
Not from my side, waiting for an idea from @schiessle.
I am using/testing E2E always with users != admin and never had problems, so I assume this is some server problem.

**Comment by tobiasKaminsky** [comment]
@schiessle any idea why this is only working for admin?

**Comment by tobiasKaminsky** [comment]
Again @schiessle

**Comment by ConorIA** [comment]
Also having this issue. Only.one user (admin).

**Comment by tobiasKaminsky** [comment]
@schiessle can it be that somehow the underlying openssl is not working?

**Comment by cleary** [comment]
@tobiasKaminsky @schiessle the error has changed with the android client update to 3.0.0 rc1

Now it's generating the keys (which is a step further than the original post), but the next screen show the following error:
"Error: Storing keys was unsuccessful, please try it again!"

Everything is still working fine as the superuser account -

**Comment by tobiasKaminsky** [comment]
@cleary what is your username: the name the admin sees on "user" view on web ui?
And what do you see in the drawer for this user. The first part, in my case"tobi@" is relevant.

![2018-01-19-121428](https://user-images.githubusercontent.com/5836855/35148402-4a8e257c-fd12-11e7-8fd8-88319f52f222.png)

**Comment by cleary** [comment]
@tobiasKaminsky 
I'm not sure I understand the question, but here are all the possible answers I can think of, modified slightly for privacy ;)

**Admin User details:**
Name I login with: admincloud
Name in the app drawer: admincloud
Email in the app drawer: admincloud@cloud.mydomain.com
Username in the webui: admincloud
Full Name in the webui: admincloud

**Regular User details**
Name I login with: bernie@cloud.mydomain.com
Name in the app drawer: Bernard Gray
Email in the app drawer: bernie@cloud.mydomain.com@cloud.mydomain.com (duplicated, not a typo)
Username in the webui: bernie@cloud.mydomain.com
Full Name in the webui: Bernard Gray

**Comment by cleary** [comment]
@tobiasKaminsky I just deleted the user with the double domain, and created another *regular* user with the following details:
Name I login with: bernie
Name in the app drawer: Bernard Gray
Email in the app drawer: bernie@cloud.mydomain.com
Username in the webui: bernie
Full Name in the webui: Bernard Gray

E2E encryption is now working for this user! 

I think you may be onto something with the username thing ;)

**Comment by tobiasKaminsky** [comment]
You can login (account creation in app) with many different values: username, email-address, ...
And this is then used for E2E. But E2E on server expects to have the real uniqe user-id (this is the name the admin created for you). 
If this differs, it will fail.

@rullzer what was the conclusion here? Shall I fetch the user-id and use it?

**Comment by rullzer** [comment]
@tobiasKaminsky that is the easiest.

Do a get to `<server>/ocs/v2.php/cloud/user` and get the `id` element.

**Comment by cleary** [comment]
@tobiasKaminsky thanks a lot! Your persistence paid off, I really appreciate it :)
