### ISSUE TITLE
Unreliable / disfunctional (auto) sync with PIN code lock

### ISSUE THREAD

**Issue by childnode** [nextcloud/android#186]
### Actual behavior
- File is not automatically updated if PIN/Code Lock is enabled
- File is not updated when opening app when marked for sync until you open the folder it is in
### Expected behavior
- You you setup Nextcloud/ownCloud without a PIN, all favorite files are downloaded when they change on Server
- File should update ... anyway... Enabling PIN / Code may not decline this function. Even if you say "it's about security": it is not, an old once synced file is still in the filesystem unless you have enabled PIN / Code or not
### Steps to reproduce
1. setup app 
2. mark a file as favorite
3. change this file externally
4. see this file is being updated on phone automatically
5. setup PIN/Code Lock in Nextcloud app
6. change the file again (from your computer)
7. see .. nothing happens.. Until 
   a) you open the app manually and
   b) you change into the folder the favorite file is in
### Environment data

Android version:
4.4 (.0)

Device model: 
Sony Xperia SP

Stock or customized system:
Stock

Nextcloud app version:
1.2.0 

Nextcloud server version:
somewhat 10beta .. called owncloud 9.1

**Comment by AndyScherzinger** [comment]
@childnode I read two requirements here, please correct me if I am wrong:

* update all files marked for sync when you're in the app (as in right away) not when you navigate to the various folders these files might be located
* always update all files marked for sync as in don't treat PIN protected files differently

Any thoughts @tobiasKaminsky @jancborchardt ?

**Comment by childnode** [comment]
@AndyScherzinger yes, that's correct

**Comment by jancborchardt** [comment]
Totally agree with @childnode, good points!

**Comment by tobiasKaminsky** [comment]
I have tested this and set one file "as available offline" and changed the text file externally and it worked.
@childnode can you confirm that you still have the problem?

(android 7)

**Comment by childnode** [comment]
No I can't. For me this bug is obsolete and quiently fixed :)

**Comment by AndyScherzinger** [comment]
@ all I'll close the issue then (while not being able to assign it to a former release).

Please re-open if anyone is experiencing this behavior again.

**Comment by AndyScherzinger** [comment]
Thanks for the feedback @childnode :)
