### ISSUE TITLE
Beta end-to-end encryption missing

### ISSUE THREAD

**Issue by stratoss** [nextcloud/android#1863]
### Actual behaviour
Can't set a folder to be end-to-end encrypted. I've tried to de-install and install again the beta app on Android but still can't see the encryption setting available.

### Expected behaviour
End-to-end encryption set-up
 
### Steps to reproduce
1. 
![screenshot_20171216-140108](https://user-images.githubusercontent.com/8927314/34070201-fe15a304-e269-11e7-8a83-db44a0817532.png)

2. 
![screenshot_20171216-140147](https://user-images.githubusercontent.com/8927314/34070202-037ec816-e26a-11e7-833f-15794073d397.png)

### Environment data
Android version: 6.0

Device model: Galaxy S5

Stock or customized system: CyanogenMod 13

Nextcloud app version: beta 2.0

Nextcloud server version: 13 beta 3

**Comment by AndyScherzinger** [comment]
Hi @stratoss,
the e2e feature is only available in the Alpha release channel. In order to see alpha releases you need to join the testing channel (which you did since you see the beta releases) but also need to join the G+ community via https://plus.google.com/communities/109411166459647252995?sqinv=WTJad2N1aHAtRGVYNThTTlRXSFFmT2g1TFMyY3FB

Further infos on the e2e test releases is described here: https://nextcloud.com/blog/nextcloud-introducing-native-integrated-end-to-end-encryption/

**Comment by stratoss** [comment]
I've already joined the G+ community but can't find anywhere the alpha release. Willing to test the new awesome features but really stuck with 1) finding the alpha release and 2) Installing the end-to-end server API - can't find any documentation how to do it.

Will be grateful if you can help me with those 2 pointers.

![nextcloud](https://user-images.githubusercontent.com/8927314/34073367-fdbcb988-e2a0-11e7-9d5c-788e4dace9ed.png)

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky is the expert on e2e and will be available on Monday again. Sorry for the inconvenience and not being of any help.

**Comment by tobiasKaminsky** [comment]
You have to be both in g+ community and a registered beta tester (https://play.google.com/apps/testing/com.nextcloud.client).

On server side it is a regular app (https://apps.nextcloud.com/apps/end_to_end_encryption). Please note that this is NC13 only.

**Comment by stratoss** [comment]
@tobiasKaminsky I'm both in the G+ community and registered as a beta tester, but can't find the alpha release in the store. The 'Encrypt' menu item is just missing.

Will check out the end-to-end app, already on NC13 beta 3 so shouldn't be an issue.

Thanks

**Comment by stratoss** [comment]
@tobiasKaminsky will be great if you can check out #1870 - I think I've discovered a bug with the private keys but need to reproduce it by creating a new set of pairs.
