### ISSUE TITLE
The Android app can't be full-screen mode when play a video

### ISSUE THREAD

**Issue by peakyu0739** [nextcloud/android#1867]
The Android app can't be full-screen mode when play a video.

**Comment by tobiasKaminsky** [comment]
I tested it right now with an OnePlus3 and latest app. After clicking on the video the fullscreen mode was enabled.
Can you give us some more details? Which android version? Which device? Which nextcloud app version?

**Comment by AndyScherzinger** [comment]
OP3T tested with Android O: ActionBar doesn't get hidden in Full screen mode... :/

**Comment by tobiasKaminsky** [comment]
This is a screenshot of my OP3. 
There is indeed a bar, is this what you are referring to @AndyScherzinger?

![screenshot_20171219-093402](https://user-images.githubusercontent.com/5836855/34148288-0596b4ea-e4a1-11e7-92fe-b9e23e0f249c.png)

**Comment by AndyScherzinger** [comment]
Yes, exactly @tobiasKaminsky. In olders versions the bar has been hidden in Full screen mode. Are you also running Android O?

**Comment by tobiasKaminsky** [comment]
No, lineage OS with 7.1.2

**Comment by AndyScherzinger** [comment]
Action bar is fixed via #2360
