### ISSUE TITLE
New background for NC13

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#1869]
Showing the new background image in drawer looks a bit strange as the full hd image is resized to e.g. 1260x643 on my emulator:
The "dots" are too small and get blurry.

![device-2017-12-18-115838](https://user-images.githubusercontent.com/5836855/34102857-ee4892d8-e3ea-11e7-8d8b-320832bd3c00.png)

We currently have the "clouds" as a fallback image and this is 984x656.

@nextcloud/designers

**Comment by MariusBluem** [comment]
Same for IOS @marinofaggiana ...

**Comment by MorrisJobke** [comment]
> Same for IOS @marinofaggiana ...

Marino pointed it out in the first place - but yes, this should also be properly handled on iOS. Having the coloured background to properly support transparent PNGs in the menu.

**Comment by MorrisJobke** [comment]
> The "dots" are too small and get blurry.

Could we just use a smaller version for this? But I don't know how to properly "announce" this based on the server.

**Comment by marinofaggiana** [comment]
in iOS this is done and ready from Friday and available :-)

**Comment by jancborchardt** [comment]
Agree with @MorrisJobke - if there is no theming, can we just crop the background to make the dots bigger?

**Comment by MorrisJobke** [comment]
> Agree with @MorrisJobke - if there is no theming, can we just crop the background to make the dots bigger?

But what happens with the default theming that has the same problem (but the file is loaded from the server). How should the android app know when to crop and to which size?

**Comment by tobiasKaminsky** [comment]
Indeed, this is the problem: when to crop?

Currently we always download the "full" background, accessible via theming api. What if we do a background api where a client can request a background with a given width and height? Then the server can do prober resizing:
- if a custom image: scale
- if default: crop

**Comment by MorrisJobke** [comment]
cc @nextcloud/theming

**Comment by marinofaggiana** [comment]
For me this issue do not exists ... I Use my algorithm for background image 
![17-12-18 20-23-52 3737](https://user-images.githubusercontent.com/8616947/34123975-907cd67c-e431-11e7-9b60-b862605d9ad7.png)

**Comment by tobiasKaminsky** [comment]
So what to do? For android icon we have a version with bigger dots

@nextcloud/theming

**Comment by jancborchardt** [comment]
What's the format you need? I can crop something with bigger dots.

And should that then be on the server, or in the app?

**Comment by MorrisJobke** [comment]
> And should that then be on the server, or in the app?

Currently this is used from the server and I have no good idea how to make this nicely working, because if you change the background there it should also properly reflect in the Android/iOS app and not be randomly cropped.

**Comment by juliushaertl** [comment]
> Currently this is used from the server and I have no good idea how to make this nicely working, because if you change the background there it should also properly reflect in the Android/iOS app and not be randomly cropped.

Yes, it should be done in the app, i think. Otherwise there needs to be too much logic inside the theming app that. Clients can check if the default image or a custom image is used though the capabilities api and then adjust the background depending on that.

**Comment by tobiasKaminsky** [comment]
Capabilities show me:
- on custom image: <background>http://localhost/nc13/index.php/apps/theming/loginbackground?v=27</background>
-  on default image: <background>http://localhost/nc13/core/img/background.png?v=29</background>

So I would have to check for some hardcoded string, e.g "background.png" to distinguish if default image or custom image?

**Comment by juliushaertl** [comment]
Hm, not the ideal situation, yes. I guess we should move to more detailed capabilities values in the future. We also use the background field for color values when no image is set. For now I'd just check the string for "apps/theming/loginbackground".

**Comment by tobiasKaminsky** [comment]
@jancborchardt currently we have a jpg file with 984x656 (width x height).
It is scaled with correct aspect ratio depending on the display size:

Nexus 5 emulator: 431 x 646
Samsung S5 neo: 492 x 738
Tablet emulator (Nexus 7): 328 x 492

I am not sure how we can make sure that the "dots" are always as big as needed.

**Comment by jancborchardt** [comment]
So as a quick fix we can definitely just go with a simple Nextcloud blue there (except if themed / a manual image is set).

**Comment by tobiasKaminsky** [comment]
We have till Friday to fix it properly, otherwise we can do it this way ;-)

**Comment by jancborchardt** [comment]
Does this work well?
![](https://raw.githubusercontent.com/nextcloud/promo/04490f37123f94b0d134c7500fe09ed355bbba77/Specific%20designs/app-header.jpg)
https://github.com/nextcloud/promo/commit/04490f37123f94b0d134c7500fe09ed355bbba77

I can modify the opacity etc of course. But since in this case it’s a background for text, I think the increase of the size is enough, and the opacity should stay the same. And it seems to look nice on smaller resolutions.

**Comment by tobiasKaminsky** [comment]
![2018-01-09-161452](https://user-images.githubusercontent.com/5836855/34727800-40bb0a54-f558-11e7-99c4-63ed95fbf3bd.png) ![2018-01-09-161248](https://user-images.githubusercontent.com/5836855/34727801-40d81072-f558-11e7-9746-d96270b552d0.png)

Left: plain image from server
Right: new version by Jan

**Comment by tobiasKaminsky** [comment]
Maybe you can make it transparent so that a solid color is chosen, I can also use the adapted image?

**Comment by tobiasKaminsky** [comment]
@nextcloud/designers ping.
We want to release a RC1 tomorrow and this issue is open since 24 days!

**Comment by tobiasKaminsky** [comment]
Also ping @jancborchardt

**Comment by MorrisJobke** [comment]
I like the right version.

**Comment by tobiasKaminsky** [comment]
Having the right version with a transparent background has the advantage that we can e.g. use orange as a background color, but with default background.
With https://github.com/nextcloud/server/pull/7776 we can support this.
