### ISSUE TITLE
E2EE private keys issues & slow updates

### ISSUE THREAD

**Issue by stratoss** [nextcloud/android#1870]
### Actual behaviour
- Logging-in after switching from stable to e2e is taking about 2 minutes
- Uploading each file tooks about 2 minutes (sitting at 0%, then uploading in few seconds up to 100 - even to non-encrypted folders)
- Inability to encrypt a new folder because the key password isn't accepted (even after re-install of the app)

### Expected behaviour
- Usual times for log-in/upload
- Ability to encrypt NEW folder, with a NEW key (assuming the key pass has been lost for some reason)
 
### Steps to reproduce
1. https://user-images.githubusercontent.com/8927314/34107375-afca014e-e404-11e7-9fdb-219cebfca35e.png

2. https://user-images.githubusercontent.com/8927314/34107384-b4cbdb36-e404-11e7-918f-ff286018abc4.png

3. https://user-images.githubusercontent.com/8927314/34107395-ba770452-e404-11e7-9b23-5b3d831c2601.png

### Environment data
Android version: 6

Device model:  Galaxy S5

Stock or customized system: CyanogenMod 13

Nextcloud app version: 2.1.0-e2e-01

Nextcloud server version: 13 beta 3

**Comment by stratoss** [comment]
Will be great if somebody can hint me how to erase the existing private from the server, because the password isn't being accepted and I can't proceed with further testing because of this.

**Comment by stratoss** [comment]
Uploading to a non-encrypted folder fails out completely giving "Connection error". Re-trying ends with the same error. The phone is connected to the same WiFi as my notebook, but the Linux client uploads in less than second.

**Comment by tobiasKaminsky** [comment]
Regarding lost private key, this needs to be done on server side, I think:  https://github.com/nextcloud/end_to_end_encryption/issues/32

You can manually delete the keys:
- go to $serverData/appdata_token/end_to_end_encryption
- remove keys in specific user folder
- in database delete everything in table "oc_filecache" where name like "$user"

In next version I will enable logging so we can see a bit more what is happening.

**Comment by stratoss** [comment]
Thanks, set-up a new keypair and continuing with the E2E encryption tests

**Comment by stratoss** [comment]
Closing this as after a key-pair regeneration and re-install of the app login/upload times are normal

**Comment by stratoss** [comment]
Referencing the https://github.com/nextcloud/android/issues/1878 and https://github.com/nextcloud/client/issues/98 as related

**Comment by frogueat** [comment]
Can't get rid of my keys :-o No, I'm not an evil admin. But would like to test end-2-end encryption. but i always get the message "Falscher privater Schlüssel für die Verschlüsselungs-App. Bitte aktualisieren Sie Ihren privaten Schlüssel in Ihren persönlichen Einstellungen um wieder Zugriff auf die verschlüsselten Dateien zu erhalten.". Setting the pwd in settings is not possible (old and new pwd are the same??). In folder under data -> occ encryption:show-key-storage-root aren't any files eccept .oc_key_storage!

How to start from new? Any suggestions? pls :-)

**Comment by tobiasKaminsky** [comment]
I think you mix up server-side encryption with end-to-end-encryption.
At least the error messeage sounds a lot like server-side @schiessle?
