### ISSUE TITLE
Errorr: Invalid resource directory name

### ISSUE THREAD

**Issue by abhi472** [nextcloud/android#1874]
Project is not able to be build,
whenever i try to do so i get the error
the error is pointing towards this particular file
<Path to  android studio project folder>NextCloudApp/src/main/res/values-es_419

What i figured out here is that the issue is with resource resolution folder for latin american - spanish translation.

but according to the stackoverflow answer [here](https://stackoverflow.com/a/42282526/6166726)
we should rename the values folder to values-es-b+es+419.

i would like to create a PR for this issue if it's passed as valid.

**Comment by tobiasKaminsky** [comment]
This was fixed just recently: https://github.com/nextcloud/android/pull/1873
Can you just do a pull and check if it is working?

**Comment by abhi472** [comment]
This seems to be working, but as mentioned in the stackoverflow thread,
```to speed up resolution and improve maintainability, you should store resources in the most common parent dialect. For example, if you were storing Spanish resources in the values-es-rUS directory before, move them into the values-b+es+419 directory, which contains Latin American Spanish.```

I think using value-b+es+419 is a better idea

**Comment by tobiasKaminsky** [comment]
There is android 7 and above explicitly mentioned. As we support back to api 15, I am unsure if this works for older devices.

**Comment by tobiasKaminsky** [comment]
> /drone/src/github.com/nextcloud/android/src/main/res/values-es-b+es+419: Error: Invalid resource directory name
mergeGenericDebugResources FAILED

Android also seems to not like this :/
