### ISSUE TITLE
Files not selectable via the checkbox

### ISSUE THREAD

**Issue by stratoss** [nextcloud/android#1877]
### Actual behaviour
- When manually selecting files to be uploaded from within the app, the checkboxes themself aren't clickable

### Expected behaviour
- Ability to select files by tapping over the checkbox as its natural
 
### Steps to reproduce
1. Enter in any folder
2. Tap the + button on the bottom-right
3. Select the upload button

### Environment data
Android version: 6

Device model: Galaxy S5

Stock or customized system: CyanogenMod 13

Nextcloud app version: 2.1.0-e2e-01

Nextcloud server version: 13 beta 3

**Comment by tobiasKaminsky** [comment]
Same happens on latest master, so removing E2E specific.

**Comment by tobiasKaminsky** [comment]
This also happens for multiselect!

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger maybe you have an idea? Some kind of click listener for checkbox seems to be missing, but I thought this would be handled by CHOICE_MODE_MULTIPLE_MODAL.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky I'll have a look 👍

**Comment by AndyScherzinger** [comment]
PR is #1885
