### ISSUE TITLE
E2E inability to decrypt a folder after app re-install

### ISSUE THREAD

**Issue by stratoss** [nextcloud/android#1878]
### Actual behaviour
- key password not being accepted with "Error while decrypting. Wrong password?"

### Expected behaviour
- Accepted password
 
### Steps to reproduce
1. Set-up a key pair (screenshot'ed the words for reference)
2. Upload 1 file in the encrypted folder
3. Re-install the app
4. Try to enter in the encrypted folder
5. Enter the key password (I've used the screenshot and 3 times verified that the words are 1:1 with only 1 space between them)

### Environment data
Android version: 6

Device model: Galaxy S5

Stock or customized system: CyanogenMod 13

Nextcloud app version: 2.1.0-e2e-01

Nextcloud server version: 13 beta 3

**Comment by tobiasKaminsky** [comment]
Please try it without the whitespaces between them. They are only for better readability.
@jancborchardt the instruction seems not to be that clear. I can also additionally just truncate all whitespaces.

**Comment by jancborchardt** [comment]
I would have also tried with the whitespaces cause that's how they are displayed and how I'm used to it from other apps which do this. :)

So yeah, either let's do it with whitespaces, or truncate them for the check.

**Comment by tobiasKaminsky** [comment]
@rullzer @marinofaggiana What do we want to do? Currently I am showing the whitespaces only for for readability and the "real" passphrase is without whitespaces. 
However the RFC is not specific about that. If we agree on something I will update it.

I vote for showing whitespaces, but storing it without whitespaces. With this we have more flexibility in showing it and it cannot happen that a doubled whitespaces refuses to login again.

**Comment by rullzer** [comment]
Client just removes all whitespace for the password generation. So yes. Lets display with whitespace. And accept whitespace. And just strip it.

**Comment by tobiasKaminsky** [comment]
https://github.com/nextcloud/end_to_end_encryption_rfc/pull/12

**Comment by mario** [comment]
@tobiasKaminsky fixed?

**Comment by tobiasKaminsky** [comment]
Yes, android is removing all whitespaces and lowering all chars.
