### ISSUE TITLE
Cancel during fingerprint scan not working

### ISSUE THREAD

**Issue by joekerna** [nextcloud/android#1879]
### Actual behaviour
With activated fingerprint authentication I'm asked for my fingerprint after starting the app.
If I want to close the app right away (maybe I accidentally started it or somebody who's fingerprint is not saved started it), the app can not be closed using the Android "Back" button (does it have a name?). I can only minimize it using the house button.

### Expected behaviour
Clicking on "Back" button should close Nextcloud app without previous fingerprint authentication
 
### Steps to reproduce
1. Activate fingerprint authentication
2. Start Nextcloud app
3. Click "Back" Button

### Environment data
Android version: 7

Device model: Huawei P9

Stock or customized system: Stock

Nextcloud app version: 2.0.0

Nextcloud server version: 13 Beta 3 / 12.0.4

**Comment by tobiasKaminsky** [comment]
Thank you for reporting this.

We are changing the security behaviour with #1657  and will make sure that this will work in the correct way. The plan is to ship this with 2.1. If not we should at least fix this bug.

**Comment by tobiasKaminsky** [comment]
As #1657 is postponed and this is not a serious bug, but more like an annoying papercut, we have to delay this a bit.

**Comment by AndyScherzinger** [comment]
@joekerna that depends on your devices settings regarding which device credentials to be used for the device itself since the app will will the exact same mechanism via the operating system.

**Comment by joekerna** [comment]
I'm not sure I understand. I unlock my phone using fingerprint. Pin code is the backup solution in case fingerprint fails a couple of times.
Shouldn't I expect the unlock Nextcloud with the same mechanism?

**Comment by AndyScherzinger** [comment]
> Shouldn't I expect the unlock Nextcloud with the same mechanism?

That is exactly what should happen. So within Nextcloud's app settings the lock mechanism chosen is device credentials, right?

**Comment by joekerna** [comment]
Yes (_Geräte-Anmeldedaten_) in German.
Also, it is not even asking for a Pin/Fingerprint every time I start it. Is there a timeout after which it'll ask?

**Comment by AndyScherzinger** [comment]
There is a timeout yes, I think it is 15 or 30 seconds, not sure about the exact timeout value but certain that there is one.

**Comment by joekerna** [comment]
To get back to the actual issue: I can in fact close the app while being asked for the pin code.

**Comment by AndyScherzinger** [comment]
> I can in fact close the app while being asked for the pin code.

Hi @joekerna I am a little confused now, isn't the reported issue that the app can't be closed?

**Comment by joekerna** [comment]
Yes, sorry about the confusion. The app version in the Play Store does have this bug. But it is fixed in the latest dev version.
However that version is not asking for a fingerprint to unlock. It is actually a new bug. Should I open up a new issue?

**Comment by AndyScherzinger** [comment]
> However that version is not asking for a fingerprint to unlock. It is actually a new bug. Should I open up a new issue?

@joekerna yes please, that makes it easier to discover the real issue :+1:

**Comment by joekerna** [comment]
#2879

**Comment by AndyScherzinger** [comment]
This original issue should be solved by the newly introduced device credentials support. other issue has been separated in #2879
