### ISSUE TITLE
Warning about possible incompatibility to ownCloud

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#188]
https://github.com/nextcloud/android/pull/141#issuecomment-236938290 @Spacefish 
> I would display a warning during the initial account adding inside the app, which tells the user, that ownCloud might be incompatible and that he may want to upgrade his server to next cloud.. however we loose all the users which may use the next cloud app but can't control the server installation (cooperate or educational users mainly)

Good idea. 
Should we, for now, mention the one and only thing (file drop) that is not compatible?

@jancborchardt @LukasReschke

**Comment by AndyScherzinger** [comment]
I would go for it since it is a neat way to promote the Nc server in the app right in the context of the feature :)

**Comment by AndyScherzinger** [comment]
pinging @jancborchardt and @LukasReschke again for Feedback

**Comment by LukasReschke** [comment]
Mhm. Thoughts, @jospoortvliet @karlitschek? I do see that this makes sense for example we have the upload only sharing links which with ownCloud would not work (see https://github.com/nextcloud/android/issues/111)

**Comment by karlitschek** [comment]
I think this makes sense. Do we have incompatibilities already?

**Comment by LukasReschke** [comment]
Yes. The files drop upload implemented in https://github.com/nextcloud/android/pull/141

**Comment by schiessle** [comment]
I think such a warning is OK. I would keep it more general, which makes it also shorter and display space is always a issue on mobile devices. If you wish you could be more precise about the incompatibilities as part of the online documentation.

**Comment by tobiasKaminsky** [comment]
For this it would be great if /status.php could provide something like "name" set to "nextcloud". When this is absent we can show the warning as a popup warning:
Please be aware that the app is designed to be used with Nextcloud. Fully compatibility to ownCloud cannot be guaranteed.

cc @jancborchardt for design/wording.

**Comment by AndyScherzinger** [comment]
This is a tricky topic. Should we just show this once when login into an oC instance, or do we need to do this on a feature level? 
My guess would be that not all users are aware of the servers features and might then misinterpred errors or crashed as an app issue which it is not. That might lead to bad votings. Thus I would show say we should show the popup in each context where a function is clicked but not oC supported. 

What do you think?

**Comment by tobiasKaminsky** [comment]
Every time might be too much.
Still we do not have a real way to distinguish between oc and nc, or?

**Comment by AndyScherzinger** [comment]
Don't know. Do you know if there is a way @LukasReschke?

**Comment by jancborchardt** [comment]
I’d say this should be on a context basis as @AndyScherzinger says. Just like when a file type is not possible to be previewed. It’s only important when you actually want to do that.

»This functionality is not available with your ownCloud server. Update to Nextcloud for the full functionality. :)«

Something like that. Then with buttons to »Close« and »Learn more«, leading to the server install page.

**Comment by tobiasKaminsky** [comment]
I will do it the way @jancborchardt described for "files drop".
It will be a snackbar and there is only one button allowed. I will us it for "Learn more" as the snackbar disappears after ~3s so the "Close" button is not needed.

**Comment by AndyScherzinger** [comment]
Sounds great, also using the snackbar, which is less invasive :+1:

**Comment by tobiasKaminsky** [comment]
![screenshot_20160905_101444](https://cloud.githubusercontent.com/assets/5836855/18241467/987b608e-7351-11e6-9cde-d86afb42d013.png)
@jancborchardt the text is too long :/

**Comment by AndyScherzinger** [comment]
How about 
»This is a Nextcloud server functionality. Update to Nextcloud for the full functionality.«
in case this is still to long, let's just go for
»This is a Nextcloud server functionality.«

It gives you all the info you need :)

**Comment by tobiasKaminsky** [comment]
Second idea is still too long. So I am using the very short version.
Still it generates a line break on my emulator, but this is device and language specific..
![screenshot_20160905_102121](https://cloud.githubusercontent.com/assets/5836855/18241628/824e432a-7352-11e6-93e9-b26aa75db387.png)

**Comment by AndyScherzinger** [comment]
True, but I think a line break is fine and like you said this depends on the language. So I'd say go with it :+1:

**Comment by jancborchardt** [comment]
> This is a Nextcloud feature, please update.

How about that?

Also, @tobiasKaminsky in your last screenshot the text is very dark?

**Comment by tobiasKaminsky** [comment]
> Also, @tobiasKaminsky in your last screenshot the text is very dark?

It is plain white text. Maybe it is due to the screenshot

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky did you oush the code to GH already? :smiley:

**Comment by tobiasKaminsky** [comment]
Not yet. 
It needed some code for library. I will push it in 4-5 hours.

**Comment by AndyScherzinger** [comment]
:smiley: :+1:

**Comment by tobiasKaminsky** [comment]
Now online :)

**Comment by AndyScherzinger** [comment]
@jancborchardt this is due to the screenshot, see mine:
![unbenannt](https://cloud.githubusercontent.com/assets/1315170/18270924/d001c2c6-742f-11e6-93d9-80b370d6428a.png)
