### ISSUE TITLE
DEV App: cannot use the Android 'share' function to upload files

### ISSUE THREAD

**Issue by nursoda** [nextcloud/android#1880]
### Actual behaviour
I cannot use the Android 'share' function to upload files with the DEV version (from F-Droid). It starts to upload, reports upload error in status bar. File is in "to be uploaded"-section of the app, Re-upload doesn't change anything - error again. Works with PlayStore Beta App on the same server.

### Expected behaviour
Should upload as the beta/release versions did.
 
### Steps to reproduce
1. Open Gallery on your Android device
2. Select a photo (or screenshot in my case) and "share" it (Android-"Share" not Nextcloud's)
3. Select Nextcloud as "share"-Method
4. Confirm PIN/Fingerprint if configured
5. Switch account if necessary
6. Select target directory and press "Upload" button

### Environment data
Android version: 8.0
Device model: OnePlus 3T
Stock or customized system: Stock (OOS Beta)
Nextcloud app version: 20171212 (F-Droid)
Nextcloud server version: 13b3

#### Nextcloud log: No entry while trying to upload file.

**Comment by tobiasKaminsky** [comment]
Is a regular upload from within the app working?
- go into any folder
- press "+"
- select "upload file"
- select any file and upload it

**Comment by nursoda** [comment]
No, also results in "Connection Error".

Sidenote: I tried to select a local file by tapping on the checkbox. No selection is performed if I tap there. If I tap on the file name, it's selected. Is that on purpose?

**Comment by AndyScherzinger** [comment]
> Sidenote: I tried to select a local file by tapping on the checkbox. No selection is performed if I tap there. If I tap on the file name, it's selected. Is that on purpose?

No that has been a bug, reported via #1877 and fixed (but not yet merged) via #1885

**Comment by tobiasKaminsky** [comment]
Can you create a test account on your server, test if this behaviour also occurs there and if yes, send me the credentials with a link to this issue to android at nextcloud dot com?

**Comment by nursoda** [comment]
Done.

**Comment by tobiasKaminsky** [comment]
Thank you.
I already fixed the problem. Once the PR is merged it will be in dev version the next night and then you can test it.
