### ISSUE TITLE
Oreo: round app icon?

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#1886]
![2017-12-21-080957](https://user-images.githubusercontent.com/5836855/34244620-6b2a4642-e626-11e7-9e6b-a680e15f9ff0.png) ![2017-12-21-081319](https://user-images.githubusercontent.com/5836855/34244694-d7d66b90-e626-11e7-9e37-2d8807e2f81a.png)

As you can see our icon is now very small within the circle.
I would like to make it bigger and fill the circle just like the phone app next to our app.

EDIT: as you can see on the right screenshot it seems to be possible to still have a regular icon, like Fdroid.
What do you prefer?

@nextcloud/designers?

**Comment by enoch85** [comment]
Round icon for sure!

**Comment by AndyScherzinger** [comment]
I can take care of this, will do the round icon as an alternative (is Nougat and up) and the adaptive icon (Oreo and up) which changes the outer form factor depending on the user's device settings due to the fact that in Oreo you can choose the icon form, round, square, etc. :)

**Comment by AndyScherzinger** [comment]
As for Oreo we might have to check since we likely have to bump the target version which might deactivate compatibility switches within Android OS itself for running the app so there could be side effects for auto upload, notifications or else. Will check.

**Comment by jancborchardt** [comment]
I'd say we should definitely use the round icon. Even for earlier versions where it's choosable. It fits way better with the logo. :)
(Same for the Talk app logo.)

**Comment by jancborchardt** [comment]
Also as commented at https://github.com/nextcloud/talk-android/issues/15#issuecomment-346844222, find the files there. :)

**Comment by AndyScherzinger** [comment]
Will use your referenced files @jancborchardt with my change will will basically support anything (literally!). Si we will ship, round square, round, and "whatever" (which is a 2 layer icon where the OS (based on the users design settings decides on the form) 🎉

**Comment by AndyScherzinger** [comment]
@jancborchardt @tobiasKaminsky @enoch85 here are screenshots of the round icon (the dots are there but that's how desktop designs work on high resolution devices....):
![device-2017-12-21-140457](https://user-images.githubusercontent.com/1315170/34257128-cfff5ab2-e658-11e7-9bb6-2775f79656a7.png)
![device-2017-12-21-140421](https://user-images.githubusercontent.com/1315170/34257129-d01c69d6-e658-11e7-9467-a844ecbf6e26.png)

Beware that the icons are "adaptive" on Android Oreo so they _will_ change forms based on OEM implementations, see:
![2017-12-21 14_12_49-asset studio](https://user-images.githubusercontent.com/1315170/34257208-28d42ec4-e659-11e7-81a3-64f8bc92cb1a.png)

**Comment by tobiasKaminsky** [comment]
As discussed in #1869 I think the dots need to be bigger...
Otherwise really great @AndyScherzinger!

**Comment by AndyScherzinger** [comment]
Thanks @tobiasKaminsky 

Well as for the dots in the launcher icon I's say drop them.

**Comment by tobiasKaminsky** [comment]
Having only a solid background is "boring" in my opinion.

**Comment by mario** [comment]
The dots are IHMO useless in general on the mobile.

**Comment by tobiasKaminsky** [comment]
@jancborchardt your feedback please :-)

**Comment by jancborchardt** [comment]
We just need to make the dots bigger. I agree with @tobiasKaminsky that only a solid background is a bit bland.

Here’s two variants:
![](https://raw.githubusercontent.com/nextcloud/promo/master/Specific%20designs/icon-background.png)
Source: https://github.com/nextcloud/promo/blob/master/Specific%20designs/icon-background.svg

![](https://raw.githubusercontent.com/nextcloud/promo/master/Specific%20designs/icon-background-big.png)
Source: https://github.com/nextcloud/promo/blob/master/Specific%20designs/icon-background-big.svg

I guess the second one with the even bigger dots works better? Also increased the opacity to 20%.

**Comment by AndyScherzinger** [comment]
@jancborchardt And again you _desktoping_.... this is and will stay a dpi issue... because even with your latest change it'll look like this:
![device-2017-12-21-140457](https://user-images.githubusercontent.com/1315170/34261395-4f3791fe-e669-11e7-8d17-0037da3571c8.png)

So even when looking at this full-HD display screenshot you need to look at it on a phone!

**Comment by jancborchardt** [comment]
Ok, so is this more proper? Otherwise I don’t get what you mean by it being a dpi issue:
![34257128-cfff5ab2-e658-11e7-9bb6-2775f79656a7](https://user-images.githubusercontent.com/925062/34262779-9d5f7b86-e66d-11e7-9dc0-fd2066cf2068.jpg)

Source: https://github.com/nextcloud/promo/blob/master/Specific%20designs/icon-background.svg

**Comment by AndyScherzinger** [comment]
@jancborchardt that seems better, and I'll try that one. What I mean by dpi is that a phone has very high resolution while (at least most) pc screens do not so the image is way larger on a desktop/laptop (in cm) and way smaller on a phone so the dots even though they might look nice on a large pc screen (with a low dpi number) will vanish on a high dpi, phone display. I hope I could explain what I meant, but let's see

**Comment by mario** [comment]
Still something I very much dislike :/

**Comment by AndyScherzinger** [comment]
I am also not a big fan but won't have much time in the upcoming days/weeks so I do whatever it takes to get it done while I still have time...

**Comment by AndyScherzinger** [comment]
So here is the latest version from the oreo branch: 
![device-2017-12-21-172804](https://user-images.githubusercontent.com/1315170/34264804-546b679e-e674-11e7-8f75-11f66a8fe669.png)

cc @jancborchardt

**Comment by AndyScherzinger** [comment]
Overall-all-icon-format-oem-os-possible screenshot:
![2017-12-21 17_18_17-asset studio](https://user-images.githubusercontent.com/1315170/34264852-76b324d6-e674-11e7-85d0-fb5f6d25e343.png)

**Comment by comradekingu** [comment]
@AndyScherzinger Your icons have the logo at-least one pixel too high, could be two.

**Comment by AndyScherzinger** [comment]
Kudos @comradekingu! You are indeed right and in the svg file it has been several pixels actually... eagle eyes! 💯 

Here is the fixed version screenshot
![2017-12-21 17_50_08-asset studio](https://user-images.githubusercontent.com/1315170/34265874-99392782-e677-11e7-93a0-edb667420eff.png)

and updated home screen:
![device-2017-12-21-175246](https://user-images.githubusercontent.com/1315170/34265924-c811cffa-e677-11e7-8893-2285a10ab597.png)

cc @tobiasKaminsky @jancborchardt @mario

**Comment by comradekingu** [comment]
The middle circle also looks slightly smaller. Only happens if you see them together.

**Comment by AndyScherzinger** [comment]
Anyone interested what the adaptive icons for Android O+ will do: https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html

> The middle circle also looks slightly smaller. Only happens if you see them together.

@comradekingu that is always the case as far as I can see (looks to me like the same on nextcloud.com too). If this needs to be changed than we need a reworked SVG file from @jancborchardt or anyone from the designers.

**Comment by comradekingu** [comment]
How about some opposite direction "dropshadows" in a lighter colour?
It would make it seem as they are light-rays going into the water.

**Comment by AndyScherzinger** [comment]
> How about some opposite direction "dropshadows" in a lighter colour?
It would make it seem as they are light-rays going into the water.

Your call @jancborchardt @nextcloud/designers :)

**Comment by jancborchardt** [comment]
No dropshadow in a lighter color please - that is not a shadow and will look tacky. :)

The slight upward position of the logo was intentional btw because otherwise it visually seems hanging down.

**Comment by tobiasKaminsky** [comment]
I like the logo with the background 👍
