### ISSUE TITLE
Background Syncing for the main account not working

### ISSUE THREAD

**Issue by stonerl** [nextcloud/android#189]
### Actual behaviour

I have two accounts added to the client. The main account (the one I have selected in the app) does not get synchronized. The second "inactive" does. See the pi

![tmp_18117-img_20160803_1800321529362149](https://cloud.githubusercontent.com/assets/2091312/17360362/3104a4ac-59a6-11e6-8758-0897512fca93.jpg)
### Expected behaviour

Both accounts should be synchronized.
### Steps to reproduce
1. Add 2 accounts.
2. Select one as the primary.
3. Enable File-sync in the Android Accounts Setting
### Environment data

Android version: 6.0.1

Device model:  OnePlus One (bacon)

Stock or customized system: Cyanogenmod 13 nightlies

Nextcloud app version: 1.2.0

Nextcloud server version: ownCloud 9.0.4 & 8.2.7

I know I currently run owncloud, but I think there are not many differences ATM between oC and nC. Insyamd picture upload for example works. Syncing also works when I open the app. Only background syncing for the main account does bit work as expected.

**Comment by gehriga** [comment]
I can confirm the behaviour with a Nextcloud server, but I only have one account which does not synchronize automatically in background.

Environment:
Nextcloud server version: 9.0.53
Nextcloud app version: 1.2.0
Device model: Motorola Moto X Force
Android version: 6.0

**Comment by tobiasKaminsky** [comment]
The sync interval will be chosen by the new doze mode of android so we cannot adjust this :-/
