### ISSUE TITLE
One server offline prevents upload to any account

### ISSUE THREAD

**Issue by mrdaftpunk** [nextcloud/android#1895]
### Actual behaviour
I have two accounts added to the android app, from two separate Nextcloud server instances. If I attempt to upload a file (via the 'share to' feature of android) when one of the servers is down, the upload to the working (online) server instance will never happen.

Aside from this, attempts to upload when I have two accounts are never guaranteed, it is extremely unreliable.

### Expected behaviour
-The file should upload successfully and consistently, regardless of whether another, unrelated server instance is down.
 
### Steps to reproduce
1. Have two accounts added to the app from separate server instances
2. Have one server offline
3. Try to upload a file via the 'share to' feature to the server instance which is online
4. Observe the notification area icons never appear, uploads always fail
5. Remove the account of the server which is offline
6. Attempt an upload again, observe the app functioning correctly

Note that even when both servers are up, uploading is very unreliable. I have developed a habit of dwelling in a particular folder prior to tapping "upload" as it seems to give an upload more chance of working.

### Environment data
Android version: 8.1.0

Device model: LG Nexus 5x

Stock or customized system: Stock

Nextcloud app version: 2.0.0

Nextcloud server version: 12.0.4

### Logs
None are included as none contained anything for this issue, the upload simply did not occur. I went as far as adb logcat (log showed nothing after the upload action) and packet sniffing with tcpdump, but due to the use of HTTPS nothing useful could be gleaned.

**Comment by tobiasKaminsky** [comment]
As we are checking in the background for user capabilities and avatar, I guess the app is sometimes running into timeout while fetching those infos from the offline server.

**Comment by mrdaftpunk** [comment]
Having just received the bot reminder, I decided to check on the progress of this bug. I undertook the following test:

- Update two instances to v16
- Check android app version (v3.6.1)
- Shut down one instance and check file uploads to the other, still active instance

Everything worked as expected, so I think this bug can be closed?

Thanks!
