### ISSUE TITLE
Unable to sync file : "Sabre\DAV\Exception\BadRequest: expected filesize 4848862 got 3112960"

### ISSUE THREAD

**Issue by venkat118** [nextcloud/android#1896]
### Actual behaviour
Files are not synced

### Expected behaviour
Files to be synced 

### Steps to reproduce
1. Upload a file

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version: 2.3.3

Nextcloud server version:12.0.4

#### Nextcloud log (data/nextcloud.log)
```
Sabre\DAV\Exception\BadRequest: expected filesize 4848862 got 3112960




Insert your Nextcloud log here
```

**Comment by tobiasKaminsky** [comment]
Can you give us some more infos? 
Our latest app version is 2.0.1 and not 2.3.3, myabe a typo?

**Comment by venkat118** [comment]
HI all,

Sorry i posted it at the wrong place.
It was supposed to be on the client tab

Best regards,

Venakt
________________________________

**Comment by rullzer** [comment]
Then lets close this
