### ISSUE TITLE
syncing problem

### ISSUE THREAD

**Issue by Joe7new** [nextcloud/android#1898]
### Actual behaviour:
**_When I used android nextcloud-app earlier it worked fine. Now I have problems:_**
First -In local lan (only using http) : When I select a menu-item like 'favorites' (and choosing this, the error always happens using http in lan!) in the app-menu then the screen shows 'Loading.....' and don't stop showing this message -but nothing happens until I manually do an update (by wiping down on the screen).
When I do this, it seems that that strange behavior spread over on other menu items: Seems to sync or is updating but nothing happens. And when I choose 'photos' the pictures sometimes are shown twice !
Only when I start the app and choose ' all files' -menu item and do not leave this , the behavior is normal ! 
Second- using https and accessing server from lan as well as from wan (via dynDNS) the behavior is similar (although menu item 'favorites' seems to work here most of time). But in menu item 'photos' pictures are also shown twice. When I manually update (wiping down on handy screen) then each picture is listet only once (normal).  To sum up : The **_problem seems to be the app menu_** in the app ! Browsing the menu and choosing a menu item in the list sometimes causes the strange behavior. When I start app and only choose item 'all files' and do not change  this menu item there are no problems.

Comment: Auto-upload doesn't work too !

### Expected behaviour:
The sync should take only a few seconds and the updated files should be shown correctly  .. even after browsing the menu (like Cirrus-app does!).
 
### Environment data
Android version: 6.0.1

Device model: Samsung Galaxy S5neo

Stock or customized system:..

Nextcloud app version:latest v2.0.0

Nextcloud server version:12.0.4

### Logs

Nextcloud log errors shown below only occurs when running nextcloud in virtual machine - no significant errors on physical machines, but similar strange behavior.
#### Nextcloud log (data/nextcloud.log)
```
Error | notifications | GuzzleHttp\Exception\ClientException: Client error response [url] https://push-notifications.nextcloud.com/notifications [status code] 400 [reason phrase] Bad Request | 2017-12-29T21:06:47+0100
-- | -- | -- | --
Error | PHP | Undefined offset: 3 at /var/www/html/nextcloud/apps/activity/lib/FilesHooks.php#620

**Comment by Joe7new** [comment]
**_New tests on **_different physical machines_** shows similar strange behavior:_**
testing in lan via http: Most of the time now the strange things happen, when I choose menu item 'photos'. Then the pictures are shown twice . Wiping down on screen to update manually again pictures are shown once (normal), but then choosing another menu item (for example 'favorites') sometimes the sync doesn't stop again (although nothing happens).
testing in wan via https (self signed certificate or Let's encrypt certificate): seems to be more stable. But when choosing photos and it seems to be normal (each picture only shown once) and  I do a manual update by wiping down on screen then again the described behavior apperas .
And again: app menu seems to be the problem !

**Comment by tobiasKaminsky** [comment]
Might also be related to #1908

**Comment by Joe7new** [comment]
Thanks. Already found it. regards Joe7
