### ISSUE TITLE
Background image stretched in Android app sidebar

### ISSUE THREAD

**Issue by detly** [nextcloud/android#1903]
### Actual behaviour

I have manually set my background image, it's 1920×1920 (ie. 1:1 aspect). When I open the Android sidebar, it appears stretched horizontally. It appears normally on the web interface login.

### Expected behaviour

The Android sidebar image should have the same aspect as the original image (cropped or scaled I don't care).
 
### Steps to reproduce
1. Set a square image for the background via Admin > Theming. 
2. Open and refresh the Android app.

### Environment data
Android version: 7.1.2

Device model: HTC One M9

Stock or customized system: Custom (LineageOS 14.1)

Nextcloud app version: 2.0.0 (beta version)

Nextcloud server version: 12.0.3

I haven't attached logs because I don't have access to the server logs right this minute, and the Android app doesn't log. However, here's a couple of images, first the original scaled down (just for reference) then a screenshot of the Android app.

![bg1](https://user-images.githubusercontent.com/311239/34481371-e0dc4212-f005-11e7-9405-7786366625df.jpg)

![bg2](https://user-images.githubusercontent.com/311239/34481387-f635271e-f005-11e7-997e-1920040c5ea2.png)

**Comment by tobiasKaminsky** [comment]
Here we set the image returned by glide:
https://github.com/nextcloud/android/blob/acdd470c95ed07d5f42829530049e34476f5c600/src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java#L1055-L1064

However, there is no way to keep the aspect ratio. And manually scaling is not working as the width/height of the LinearLayout is not known yet.

I tried to add an ImageView, but now I have slight borders :/

@AndyScherzinger maybe you can help here?

**Comment by mario** [comment]
Store the image received, and set it once we're ready to do that? (e.g. when width/height are known).
