### ISSUE TITLE
Make Basic Auth work

### ISSUE THREAD

**Issue by skorokithakis** [nextcloud/android#1907]
This is related to #371, which is closed, but I feel that the resolution is inadequate. I want to use basic auth *in addition* to the normal web login flow, and there's no reason why the app can't accept a server URL in the form `https://username:password@myserver.com/", as that's standard HTTP. The app should obey the standard there and use HTTP basic auth if it has been specified in the URL.

**Comment by rullzer** [comment]
While this *might* work on the login flow page. This will fail hard on other parts. As we supply the nextcloud credentials via basic auth.

**Comment by skorokithakis** [comment]
Ah, I see, that's too bad. Feel free to close this, then.

**Comment by ShaunCurrier** [comment]
Is it still the case that Basic Auth isn't supported, such as when implemented by a reverse proxy to keep the big bad internet away from the Nextcloud web app?

**Comment by AndyScherzinger** [comment]
Yes because it would lock out the small, nice mobile clients.
