### ISSUE TITLE
No upload at charging if battery is on 100%

### ISSUE THREAD

**Issue by Django3** [nextcloud/android#1911]
Hi! :)

I set 2 folders to auto upload when phone is charging. Now i recognised, if the phone is plugged in to the charger and the battery is below 100% it is working fine. But if the battery is at 100% (and the phone still on the charger) it is not working and the app/the upload is waiting for charging.

Could it be possible, that the app does not recognise the charger if the phone battery is on 100%?

Best regards,
HANNES 

### Environment data
Android version: 7.0
Device model: Huawei Mate 10 lite
Nextcloud app version: 2.0.0
Nextcloud server version: 12.0.3

**Comment by mario** [comment]
Of course. Its not charging anymore then.

**Comment by mario** [comment]
I can probably fix this though so you dont have to close the issue :p

**Comment by Django3** [comment]
... in my view, it is still charging cause it is still pluged in at the charger and will lose no battery.
So it should still upload cause the sense of this function is not to impare the battery, right? ;)

But maybe I'm thinking wrong ...

**Comment by tobiasKaminsky** [comment]
Mario developed a fix and this is now included in our dev version.

Maybe you want to try out our dev version (you can install it in parallel): 
https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#dev-release
