### ISSUE TITLE
Account information should show that there are no details provided

### ISSUE THREAD

**Issue by przybylski** [nextcloud/android#1916]
### Actual behaviour
No indication that no user details are provided
![zrzut ekranu 2018-01-03 o 10 10 41](https://user-images.githubusercontent.com/1734309/34514647-a636b3fe-f06e-11e7-9361-31e5241a47d1.png)

### Expected behaviour
Indicator that no info is provided. Alternatively allow user to edit those details from the app.
![zrzut ekranu 2018-01-03 o 10 10 41 2](https://user-images.githubusercontent.com/1734309/34514696-eeb272c6-f06e-11e7-9881-9dfe12d28eac.png)

 
### Steps to reproduce
1. Setup account with no details (no www, address, twitter)
2. Go to manage accounts > Open the account
3. Weep

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:
master

**Comment by tobiasKaminsky** [comment]
![2018-01-03-162255](https://user-images.githubusercontent.com/5836855/34526289-5e3f5298-f0a2-11e7-960d-451ee72d85b2.png)

This uses the same way as "error" message are displayed, to stay consistent.
Any feedback regarding the wording is appreciated ;-)
