### ISSUE TITLE
Thumbnails of deleted pictures are still visible in activity list

### ISSUE THREAD

**Issue by Joe7new** [nextcloud/android#1926]
### Actual behaviour
The thumbnails of deleted photos are still visible in the activity list of my android nextcloud -app . It seems that they are saved (cached or whatever) on android system (!?) Accessing server’s activity list with desktop browser there are of course no thumbnails visible .In android they appear as if the photos/pictures are still accessable (of course when I click on the link to the photo in activity list the notification “Not accessable” appears).
**_That’s irritating for me - why are the thumbnails not deleted too ?_**
Moreover since the activity list can’t be deleted (nor a time window can be choosen) the list gets longer and longer. Ok.does’nt matter, but since the thumbnails are apparently saved on mobile device they need memory on my device (though only little). The longer the server is runnung ( and the the activity-list increases) the more memory of mobile device is used.
Is that normal behavior ? 

### Expected behaviour
-When pictures/photos are cleared the thumbnails should be removed too.
 
### Environment data
Android version: 6.0.1

Device model: Samsung Galaxy S5neo

Stock or customized system:

Nextcloud app version:2.0.0

Nextcloud server version:12.0.4

**Comment by rullzer** [comment]
Ah well this is due to the caching. The android client doesn't sync the whole file list. So it doesn't get notifications when files are deleted.

Yes they will take up some space. But they are in a cache. So at some point (when you have been browsing other images) they will get removed.

**Comment by Joe7new** [comment]
Thanks for your answer ! I can't find a way to delete them (although they are only cached )!
https://help.nextcloud.com/t/thumbnails-of-deleted-pictures-are-still-visible-in-activity-list/25420/3
Kind regards, Joe7

**Comment by tobiasKaminsky** [comment]
We currently have a cache size of 200mb.
If this limit is reached the oldest thumbnail will be removed.

With the next version we will "only" fetch 50 activity items and once you scroll to the bottom fetch the next 50 items.

Clearing the cache should be possible via android settings -> apps -> nextcloud app -> manage space.

**Comment by Joe7new** [comment]
ok. Thanks.

    Am Montag, 8. Jänner 2018, 09:30:14 MEZ hat Tobias Kaminsky <notifications@github.com> Folgendes geschrieben:  
 
 
We currently have a cache size of 200mb.
If this limit is reached the oldest thumbnail will be removed.

With the next version we will "only" fetch 50 activity items and once you scroll to the bottom fetch the next 50 items.

Clearing the cache should be possible via android settings -> apps -> nextcloud app -> manage space.

**Comment by Joe7new** [comment]
**_First thank you very much for your hard and great work done so far !!!_**  I have found out to clear cache now. 
And I know there are much more important and a lot of things to do . Although I don't really unterstand why thumbnails on the android client can't be deleted when file is deleted (even when file is deleted remotly the client gets the information , otherwise there would'nt be the remark in activity list that file have been deleted). 
It would feel much more "natural" if both (file and thumbnail) are removed.  
But maybe it's not possible for some technical reasons (speed, memory management,syncing technique ..) that I (as user) don't unterstand . 
Then still I have to say thanks very much for nextcloud !!
 Regards Joe7.
