### ISSUE TITLE
Can't connect to server

### ISSUE THREAD

**Issue by JohnMH** [nextcloud/android#1927]
### Actual behaviour
-Tell us what happens

After inputting a valid server, I get the message "Could not establish connection"

### Expected behaviour
-Tell us what should happen
 

### Steps to reproduce
1. Enter "cloud.splentity.com" into server address field

### Environment data
Android version: 

Device model: 
Moto Z Droid, Nexus 5

Stock or customized system:
Both

Nextcloud app version:
20171230

Nextcloud server version:
https://cloud.splentity.com/status.php

#### Web server error log
Nothing relevant

#### App log
01-05 16:47:13.132  8439  8470 E GetRemoteStatusOperation: Connection check at https://cloud.splentity.com: Socket exception
01-05 16:47:13.132  8439  8470 E GetRemoteStatusOperation: java.net.NoRouteToHostException: No route to host
01-05 16:47:13.132  8439  8470 E GetRemoteStatusOperation:      at java.net.PlainSocketImpl.socketConnect(Native Method)
01-05 16:47:13.132  8439  8470 E GetRemoteStatusOperation:      at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:343)
01-05 16:47:13.132  8439  8470 E GetRemoteStatusOperation:      at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:205)
01-05 16:47:13.132  8439  8470 E GetRemoteStatusOperation:      at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:187)
01-05 16:47:13.132  8439  8470 E GetRemoteStatusOperation:      at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
01-05 16:47:13.132  8439  8470 E GetRemoteStatusOperation:      at java.net.Socket.connect(Socket.java:605)
01-05 16:47:13.132  8439  8470 E GetRemoteStatusOperation:      at com.android.org.conscrypt.OpenSSLSocketImpl.connect(OpenSSLSocketImpl.java:265)
01-05 16:47:13.132  8439  8470 E GetRemoteStatusOperation:      at com.owncloud.android.lib.common.network.AdvancedSslSocketFactory.createSocket(AdvancedSslSocketFactory.java:184)
01-05 16:47:13.132  8439  8470 E GetRemoteStatusOperation:      at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
01-05 16:47:13.132  8439  8470 E GetRemoteStatusOperation:      at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)
01-05 16:47:13.132  8439  8470 E GetRemoteStatusOperation:      at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)
01-05 16:47:13.132  8439  8470 E GetRemoteStatusOperation:      at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
01-05 16:47:13.132  8439  8470 E GetRemoteStatusOperation:      at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
01-05 16:47:13.132  8439  8470 E GetRemoteStatusOperation:      at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
01-05 16:47:13.132  8439  8470 E GetRemoteStatusOperation:      at com.owncloud.android.lib.common.OwnCloudClient.executeMethod(OwnCloudClient.java:221)
01-05 16:47:13.132  8439  8470 E GetRemoteStatusOperation:      at com.owncloud.android.lib.common.OwnCloudClient.executeMethod(OwnCloudClient.java:191)
01-05 16:47:13.132  8439  8470 E GetRemoteStatusOperation:      at com.owncloud.android.lib.resources.status.GetRemoteStatusOperation.tryConnection(GetRemoteStatusOperation.java:87)
01-05 16:47:13.132  8439  8470 E GetRemoteStatusOperation:      at com.owncloud.android.lib.resources.status.GetRemoteStatusOperation.run(GetRemoteStatusOperation.java:188)
01-05 16:47:13.132  8439  8470 E GetRemoteStatusOperation:      at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:136)
01-05 16:47:13.132  8439  8470 E GetRemoteStatusOperation:      at com.owncloud.android.operations.GetServerInfoOperation.run(GetServerInfoOperation.java:82)
01-05 16:47:13.132  8439  8470 E GetRemoteStatusOperation:      at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:136)
01-05 16:47:13.132  8439  8470 E GetRemoteStatusOperation:      at com.owncloud.android.services.OperationsService$ServiceHandler.nextOperation(OperationsService.java:477)
01-05 16:47:13.132  8439  8470 E GetRemoteStatusOperation:      at com.owncloud.android.services.OperationsService$ServiceHandler.handleMessage(OperationsService.java:413)
01-05 16:47:13.132  8439  8470 E GetRemoteStatusOperation:      at android.os.Handler.dispatchMessage(Handler.java:102)
01-05 16:47:13.132  8439  8470 E GetRemoteStatusOperation:      at android.os.Looper.loop(Looper.java:154)
01-05 16:47:13.132  8439  8470 E GetRemoteStatusOperation:      at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by JohnMH** [comment]
Please note that the error is not actually "no route to host", I can connect with netcat from the phones on both port 80 and 443 without issue.

**Comment by JohnMH** [comment]
For now, I've fixed this by using a host entry on the phone directly to the IPv6 address of the server..

**Comment by tobiasKaminsky** [comment]
I tried it with a fresh created emulator with latest master version and I can see the login screen from within the app. So the app can successfully connect to your server.
Please note that IPv6 is not working in our app right now, so you need IPv4.

**Comment by JohnMH** [comment]
That's weird, because it actually does work when I overwrite the DNS record to return only an AAAA record.
