### ISSUE TITLE
Allow cancel of pending upload in notification

### ISSUE THREAD

**Issue by childnode** [nextcloud/android#193]
### Actual behaviour
- it is nearly unpossible to interrupt an upload
### Expected behaviour
- upload notification should be rich to get a cancel upload quick action
  -- canceling by 1. open the app, 2. enter the pin, 3. open hamburger menu, 4. tap uploads, 5. cancel upload by tapping (x) which (hopefully) works only on real fast devices, slow devices are busy by uploading and tapping does nothing ... mostly until 99% or 100% of upload is made ;/
- share / upload should get an option to be throttled if not connected with WiFi (there are only some options to handle this for instant uploads of images and videos)

**Comment by jancborchardt** [comment]
Yeah, is it possible to make the notification interactive? @tobiasKaminsky @AndyScherzinger while uploading, cancel should be possible via x on the right of the notification.

**Comment by AndyScherzinger** [comment]
Technically speaking yes. I'll do a mockup the next days but would suggest text instead of icon, since Android notifications dropped icons and went for text. You'll see when I post the mockup. :+1:

**Comment by childnode** [comment]
just some refs:
* https://material.google.com/patterns/notifications.html
> Each action has an icon and a name
* https://developer.android.com/guide/topics/ui/notifiers/notifications.html

so @AndyScherzinger I can't (quickly) see anything about "since Android notifications dropped icons and went for text"?!

**Comment by AndyScherzinger** [comment]
@childnode it is not in the material guidelines (unfortunately) but I experience it on my Nexus5X running Android N Preview 5, also see screenshots here: https://developer.android.com/preview/features/notification-updates.html. So for some reasons they seem to have decided to drop the display of icons execpt for "inline actions" like a direct reply.

**Comment by childnode** [comment]
thank god they change the design guide with each android release :o .. ok .. but shouldn't we still support the icon on marshmallows to follow the current material design for these devices? 

Perhaps let's see the design guide once N is released, I can't imagine that they break the current interface of [Notification.Action.Builder](https://developer.android.com/reference/android/app/Notification.Action.Builder.html) and no more support that icon (didn't looked into the code yet). I think they just not had them in the examples right now ... nevertheless, you might be (partially) right that it is removed or discouraged to show a icon furthermore

**Comment by AndyScherzinger** [comment]
@childnode yes we should, Android N does the magic to remove the icons from the view... :wink:

**Comment by childnode** [comment]
ok, so `approved` and ` 1. to develop` means? 
you want to do some mockup? if nobody else is activly working on it, I'd be pleased to do that.

**Comment by childnode** [comment]
ok, so `approved` and ` 1. to develop` means? 
you want to do some mockup? if nobody else is activly working on it, I'd be pleased to do that.
I see only an open question (that from @jancborchardt ) regarding "cancel should be possible via x on the right of the notification.". does this follow the guide and is it working on all supported devices? e.g. I can't see an (x) for Android 4.4 but rich notification actions. I think "(x)" is somewhat "don't nag me swipe" but doesn't intend a user action?!

**Comment by AndyScherzinger** [comment]
@childnode ```approved```` yes - ```1. to develop``` no, since that is a PR label :wink: So whenever someone opens a "empty" PR for a topic we set it to "1...." So the issue status is perfectly fine here.
If you could do a mockup that would be awesome! :+1: As for working on this issue @tobiasKaminsky and I won't be available for the next two weeks but having everything set until then, we could then start working on it or push this forward at the Nextcloud conference both of us will be attending :)

**Comment by jancborchardt** [comment]
Yeah @childnode it would be cool if you want to get involved! :) You can let us know if you need input. I personally don’t code on the Android part but oversee the design so can give feedback on any mockups or screenshots of implementations. :)

**Comment by AndyScherzinger** [comment]
@childnode I've been on vacation for the last week, so picking up here where we left of. Did you already have a chance to work on a mockup? :smiley:

**Comment by childnode** [comment]
Hi @AndyScherzinger ,

no, I didn't do a mockup ... yet
But I already digged into the code, setup the env and resurrected some of my felt asleep android dev knowledge ;)
Since I just spend time on it on my shuttle to work, it's not that far I can create a pull request yet.

But if there is noone on it calling "it's emergent" I would be pleased to finalize this during this month?!

I'll come back with an update as soon as possible ;)
~Marcel

**Comment by AndyScherzinger** [comment]
Hi @childnode 

sounds great, if you have any questions or need any help just let me know. If you want to we can also meet up somewhere in Frankfurt after work, since I am Frankfurt based, but my schedule is pretty tight before the Nextcloud conference. :smiley:

**Comment by AndyScherzinger** [comment]
@childnode on the other hand the implementation could also be started right away since the layout will probably be "just standard", so we can then work on details (if necessary) using screenshot of the actual implementation state. :)

**Comment by childnode** [comment]
I'm so sorry ... even for getting up that late with bad news: not yet anything to show because things changed quickly in real-life last month so I have to spent lot of time in another project ... refurbishing new /home

**Comment by jancborchardt** [comment]
@childnode ah no worries! :) Since you’re in Mainz maybe you should join the next Nextcoud Rhein-Main meetup: https://meetup.com/nextcloud-rhein-main – with @AndyScherzinger @eppfel @tobiasKaminsky, so it’s pretty good to get something done on the Android app ;)

**Comment by tobiasKaminsky** [comment]
Similar to this one: #383 (but this one is for pausing upload in the upload pane)

**Comment by remram44** [comment]
A button anywhere to cancel *all pending uploads* would very much be appreciated. I have 2000 uploads pending, and while there is a button to cancel any of them, the option to cancel all is not currently anywhere.

**Comment by tobiasKaminsky** [comment]
Together with https://github.com/nextcloud/android/issues/261 this is then a "cancel all", I think.
Cancel will then move them to "completed" uploads in uploads view with status "cancelled".

**Comment by tobiasKaminsky** [comment]
Idea: check how to pause
