### ISSUE TITLE
Can't connect to Nextcloud 10 from android app

### ISSUE THREAD

**Issue by KBaruet** [nextcloud/android#1937]
### Actual behaviour
-Tell us what happens

I can connect to my nextcloud from any browser but not from the app

### Expected behaviour
-Tell us what should happen
 
I should be able to connect to nextcloud from the app

### Steps to reproduce

1. When I enter the nextcloud URL in the app, it says secured connection established
2. When I want to log in and press the connect button, it says that an "unknown error" happened
3. I get nothing from the httpd logs.
4. If I enter a wrong password is says "wrong password or credential", so the error only happens when the credentials are right and it tries to connect to the server.

### Environment data

Android version:
5.0

Nextcloud app version:
2.0.0

Nextcloud server version:
10.0.4 (stable)

**Comment by tobiasKaminsky** [comment]
This is indeed strange, maybe it is some kind of misconfiguration on server side.

Can you create us a test account and send the credentials to android at nextcloud dot com with a reference to this issue?

**Comment by KBaruet** [comment]
I sent you the credential, hope you can help me with this.

**Comment by tobiasKaminsky** [comment]
As written in my email and now I see that I overlooked NC10 in the title, your server version is outdated and thus unsupported.
We only support the current and previous version, so NC12 and NC11 currently.
