### ISSUE TITLE
E2E Missing buttons in "Note your encryption passphrase" dialogue in German version.

### ISSUE THREAD

**Issue by jaltek** [nextcloud/android#1938]
### Actual behaviour
- The buttons for "Cancel" and "Set up encryption" in the "Note your encryption passphrase" dialogue are missing when using the german version. Maybe just the translation is missing?

![screenshot_20180109-122458](https://user-images.githubusercontent.com/359552/34719053-671c196e-f539-11e7-9ddc-de8ce4ff1c63.png)

### Steps to reproduce
1. Mark folder
2. Choose "set as encrypted"

### Environment data
Android version:
7.1.1
Device model: 
Sony Xperia X
Stock or customized system:
Stock
Nextcloud app version:
2.1.0-e2e-01
Nextcloud server version:
13.0.0 Beta 4

**Comment by tobiasKaminsky** [comment]
This is strange. 
I set up an emulator with 2,7" display, which is very very tiny and as you can see I still see the buttons.

![2018-01-09-143000](https://user-images.githubusercontent.com/5836855/34723090-973e0b42-f549-11e7-953a-7bd8c8cf6f00.png)

What happens if you turn your mobile to landscape?

**Comment by jaltek** [comment]
Could you please give me a hint how to reset the encryption? I dismissed the dialogue using the "back button" so the dialogue does not come up again - even not after reinstalling the app...

**Comment by tobiasKaminsky** [comment]
Currently there is no user friendly way:
- remove entries from oc_filecache where name like "%username%"
- remove your user in /data/appdata_token/end_to_end_encryption

Here is a discussion about revoking keys: https://github.com/nextcloud/end_to_end_encryption/issues/32

**Comment by jaltek** [comment]
Thanks. It worked :)

Well...strange...now (after the reset procedure) I only have one "button". So "Abbrechen" is missing. Even in landscape mode:

![screenshot_20180109-164544](https://user-images.githubusercontent.com/359552/34729450-fe57669e-f55c-11e7-8e79-401c99c801e5.png)

**Comment by jaltek** [comment]
Oh...Follow-Up: Maybe that's the problem:
After switching to another app and switching back to the Nextcloud app (while the dialogue is opened) the button disappeared...

**Comment by tobiasKaminsky** [comment]
Thank you for the last hint. 
I added a fix, it will be available on RC1 (weekend/ start of next week)'
