### ISSUE TITLE
E2E Allow to select/copy the encryption passphrase

### ISSUE THREAD

**Issue by jaltek** [nextcloud/android#1939]
### Actual behaviour
- The passphrase in the "Note your encryption passphrase" dialogue is not "selectable" in order to copy it to the android clipboard.

### Expected behaviour
- Maybe this is by design but IMHO you should be able to select (and copy) the passphrase in the "Note your encryption passphrase" dialogue in order to paste the phrase to a safe location.
 
### Steps to reproduce
1. Mark folder
2. Choose "set as encrypted"

### Environment data
Android version:
7.1.1
Device model:
Sony Xperia X
Stock or customized system:
Stock
Nextcloud app version:
2.1.0-e2e-01
Nextcloud server version:
13.0.0 Beta 4

**Comment by tobiasKaminsky** [comment]
Thank you for this suggestion.
I made the passphare selectable, so you can copy or share it.
