### ISSUE TITLE
same account , different accessing causes different sync status on android

### ISSUE THREAD

**Issue by Joe7new** [nextcloud/android#1945]
Accessing server from loacl network /lan  and accessing from internet /wan via dynDNS with the same account shows different sync status of the same file on android-app. There are 2 folders created (user@ local IP and user @ dynDNS) on android and although the same account the same syncing file has to be downloaded twice (once in folder user@localP and once in folder user@dynDNS) to show status 'synced' erverywhere.  Wouldn't it be usefull or possible to have just one folder for the same user and once to download the file to have a green hook (synced) nearby file for this account no matter how accessing ? 
Kind regards !

**Comment by tobiasKaminsky** [comment]
There are several discussions on this topic.
If your router supports this you can access the server via lan even if you use the public/dyn dns address.
Then you will only need one account.

But different accounts will remain in different storage folders.
