### ISSUE TITLE
Link Talk app in drawer if available on server

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#1949]
If the talk app is available on server (should be announced via capabilities), we can show it on drawer.
If the app is not installed then open up google play store for easily setup?

Position could be beneath "participate" or beneath "uploads"?

![2018-01-11-084450](https://user-images.githubusercontent.com/5836855/34813831-b8b0c6f8-f6ab-11e7-8a0f-93d270fac15e.png)

**Comment by mario** [comment]
The Talk app is detected via a separate call (while I agree capabilities would be good). However, my plan is (let me know if you agree):

- Check if Talk is available on the server
YES:
  - show it in the sidebar per account (so maybe after Uploads?)
  - check if we have Talk app installed
  - YES:
     - the link opens Talk app directly into the account
  - NO:
     - the link opens Play Store allowing you to install the app

**Comment by rullzer** [comment]
If you need a capability just open an issue in https://github.com/nextcloud/spreed that is really easy to add :)

**Comment by mario** [comment]
:)

**Comment by tobiasKaminsky** [comment]
If done via capabilities it is directly linked to the account.
So sounds good to me :-)

**Comment by AndyScherzinger** [comment]
Sounds good to me! I agree with Mario’s approach

**Comment by joshtrichards** [comment]
This was implemented at some point I don't recall and even recently updated (see #11744)

**Comment by joshtrichards** [comment]
Actually, despite nextcloud/spreed#594, I don't think the work in #11811 relies on a capabilities check at all currently. Re-opening for the moment.
