### ISSUE TITLE
Show quota if set on navigation drawer

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#195]
Idea per email, seen on cirrus

![screenshot_2016-08-03-13-32-52](https://cloud.githubusercontent.com/assets/5836855/17406966/deff16fe-5a65-11e6-8fe4-bee8d4e45f14.jpg)

**Comment by AndyScherzinger** [comment]
Nein items thumbs up, but for that we should integrate the existing library pr first :)

**Comment by tobiasKaminsky** [comment]
What library PR?
This will probably be in 1.4.0, so no hurry ;)

**Comment by AndyScherzinger** [comment]
There is a nextcloud android library PR to retrieve quota info :)  so that one should imho be used. 
I would love to do the UI part and would hope you could do the server communication and caching part if that would be fine with you. :) 

1.4.0 sounds fine.

**Comment by tobiasKaminsky** [comment]
As far as I have read the code it is just a quick "/ocs/v1.php/cloud/users/" + user + "?format=json" and parsing the returning values.
But a proper caching, e.g. query only once an hour, is a good idea.
I would keep the UI very close to the screenshot.

**Comment by AndyScherzinger** [comment]
Makes sense. As for the caching, we should also refresh after uploads are finished because a user would want to have the actual value.

**Comment by AndyScherzinger** [comment]
This is the library PR I was referring to: https://github.com/nextcloud/android-library/pull/10

**Comment by AndyScherzinger** [comment]
Cc @skymania :)

**Comment by tobiasKaminsky** [comment]
Then we should do it with the library :+1:

**Comment by AndyScherzinger** [comment]
PR with initial UI work has been opened: #204

**Comment by tobiasKaminsky** [comment]
PR merged
