### ISSUE TITLE
Can't connect with android app

### ISSUE THREAD

**Issue by KBaruet** [nextcloud/android#1950]
### Actual behaviour
-Tell us what happens

Android app won't connect but appears connected in the personnal security pannel of the user

### Expected behaviour
-Tell us what should happen

The app should be connected 

### Steps to reproduce
1. I'm using nextcloud through a reverse proxy.
2. The browser access works fine.
3. The android app access does'nt.
4. when I'm asked to enter my credentials, it's ok, but then I got a screen telling me that it's trying to connect to the server, it show "Redirecting..." and I'm stuck there, nothing more.

![image](https://user-images.githubusercontent.com/23720319/34817540-97bd0468-f6b8-11e7-8027-f49b906d9277.png)

5. But, when I'm connect (via my browser to the server)  to the personnal pannel of the user, I can see that my android phone is connected (I guess).

![image](https://user-images.githubusercontent.com/23720319/34817247-bf1a7992-f6b7-11e7-9d2c-af3f3c6a9e1a.png)

The logs don't really show anything to me, hope you can help me with this.

### Environment data
Android version:

5.0

Nextcloud app version:

2.0.0

Nextcloud server version:

12.0.4

#### Nextcloud log (data/nextcloud.log)
```

**Comment by tobiasKaminsky** [comment]
Maybe the reverse proxy is conflicting...

Can you create us a test account and send the credentials to android at nextcloud dot com with a reference to this issue?

**Comment by KBaruet** [comment]
Maybe..


This is the URL :


https://nextcloud.haute-marne.fr/nextcloud


These are the credentials :


User : test_nextcloud

password : next


Kevin Baruet,

Tél: 06 59 81 69 28

Mail: kevin.baruet@outlook.<mailto:k.baruet@gmail.com>fr

________________________________
De : Tobias Kaminsky <notifications@github.com>
Envoyé : jeudi 11 janvier 2018 11:36:52
À : nextcloud/android
Cc : KBaruet; Author
Objet : Re: [nextcloud/android] Can't connect with android app (#1950)


Maybe the reverse proxy is conflicting...

Can you create us a test account and send the credentials to android at nextcloud dot com with a reference to this issue?
