### ISSUE TITLE
Selection colour is applied to often

### ISSUE THREAD

**Issue by splitt3r** [nextcloud/android#1952]
### Actual behaviour
- If you have a list for example with 30 files and select the third file the selection colour (light grey) will be applied to every third file instead of only the third file.

### Expected behaviour
- Only the selected item should be highlighted.
 
### Steps to reproduce
1. Select a file from the list and scroll threw the list

### Environment data
Android version: 7

Device model: Nexus 6

Stock or customized system: Custom ROM

Nextcloud app version: Beta from the Play Store

Nextcloud server version: 13

![android](https://user-images.githubusercontent.com/1869584/34871477-180733d4-f78e-11e7-9840-a19f6ae04224.png)

**Comment by AndyScherzinger** [comment]
@splitt3r closed on purpose (as-in fixed)? :)

**Comment by splitt3r** [comment]
Exactly :+1:
