### ISSUE TITLE
Share permission dialog

### ISSUE THREAD

**Issue by splitt3r** [nextcloud/android#1955]
### Actual behaviour
- The sharing permission dialog looks strange.

### Expected behaviour
- The iOS app looks better here. I would say that the options should all be a checkbox or a slider and they should be all named like 'kann ...'.
 
### Steps to reproduce
1. Share a file / folder and edit the permissions.

### Environment data
Android version: 7

Device model: Nexus 6

Stock or customized system: Custom ROM

Nextcloud app version: Beta from the Play Store

Nextcloud server version: 13

Android:

![android](https://user-images.githubusercontent.com/1869584/34871027-5140782e-f78c-11e7-871a-f059eaddafdf.png)

iOS:

![ios](https://user-images.githubusercontent.com/1869584/34871276-5da583ba-f78d-11e7-9b9b-fb4c980dd74d.png)

**Comment by tobiasKaminsky** [comment]
@nextcloud/designers 
Indeed this screen should get some love.
A bit of explanation "can edit" is the overall setting, therefore it is a slider. If set to off, the three suboptions vanish.
And as suboption you have "can create, edit, delete".

**Comment by tobiasKaminsky** [comment]
Corresponding on server:
![image](https://user-images.githubusercontent.com/5836855/34886175-85e8264a-f7c2-11e7-8f67-396774ef3bce.png)

**Comment by jancborchardt** [comment]
So to which extent can we do it like in the web app? List of the people, checkbox with "Can edit" right-aliged, and right of it a 3-dot-icon which opens that list menu with checkboxes.

That would be ideal, and have the interface symmetric.

**Comment by AndyScherzinger** [comment]
I'll close this issue in favor of #2485 which is its successor describing the complete revamp of the sharing UI parts.
