### ISSUE TITLE
Release next version as 2.5 or even 3.0

### ISSUE THREAD

**Issue by mario** [nextcloud/android#1959]
cc @tobiasKaminsky @AndyScherzinger @jospoortvliet 

Due to a lot of changes, namely:

1) Storage improvements
2) IPv6 support
3) Encryption

And a thousand papercuts, I'm in favour of release version 2.5 or even 3.0, rather than 2.1.

What do you think?

**Comment by AndyScherzinger** [comment]
I’d also be fine with a larger version bump, looking at the newly decided release process I’d be fine with 2.5 and 3.0 also.

**Comment by rullzer** [comment]
Then go with 3.0.

2.0 => 2.5: This feels weird without the releases in between. Also while it might be clear to engineers that this means a big change (since we are skipping 4 . releases). This is probably not at all clear to our users.

**Comment by mario** [comment]
@tobiasKaminsky don't forget to look at this issue before releasing :P

**Comment by tobiasKaminsky** [comment]
We released 2.0 back in August and now, 6months later already 3.0?

According to semantic versioning it is no reason for a new major.
> Given a version number MAJOR.MINOR.PATCH, increment the:
MAJOR version when you make incompatible API changes,
MINOR version when you add functionality in a backwards-compatible manner, and
PATCH version when you make backwards-compatible bug fixes.

On android nobody really cares/see the version number.
For pr/marketing it is indeed useful to have a "big" version jump.

I am fine with 3.0.

**Comment by mario** [comment]
@tobiasKaminsky this is mostly library reasoning (the incompatible API changes). I guess this is purely from marketing perspective, but I dunno. That's why I asked for an opinion of all involved :)

**Comment by AndyScherzinger** [comment]
With mario's list of major changes:
1) Storage improvements
2) IPv6 support
3) Encryption

And everybody who commented already being fine with a mayor release I'd say let's go for 3.0 and from there on let's go with the newly introduced/defined, shorter release cycles where a new release should be smaller so minor versions (or hot fix releases) should be fine. 🎉

**Comment by tobiasKaminsky** [comment]
Then we all agree 🎉
