### ISSUE TITLE
Shared link cannot be copied again

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#196]
### Actual behaviour
- no text/link to copy

### Expected behaviour
- Link should be copied
 
### Steps to reproduce
1. Create a shared link
2. Access it later via "get link"

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

**Comment by tobiasKaminsky** [comment]
This fixes  oc 1562
It will be soon in beta. 
@dva-re it would be cool, if you can test it?

**Comment by AndyScherzinger** [comment]
any feedback @dva-re

**Comment by tobiasKaminsky** [comment]
Merged.
If any problems occur please reply
