### ISSUE TITLE
Cannot accept federation-shared file

### ISSUE THREAD

**Issue by karottenbaum** [nextcloud/android#1968]
### Actual behaviour
In the Activity pane, clicking on the filename of a file that has been shared to me shows a toast with "File not found!".
This occurs only when opening a file from a federated share.

### Expected behaviour
The app should open the file if already accepted by another interface.
If the file has not yet been accepted or declined, it should open a dialog to choose to accept or decline the file.
 
### Steps to reproduce
1. Be shared a file from a federated instance
2. Open 'Activity' pane
3. Click on shared file's name

### Environment data
Android version: 7.1.1

Device model: motorola XT1562

Stock or customized system: Stock

Nextcloud app version: 2.0.0

Nextcloud server version: 12.0.4

#### Web server error log
(This is the access log, the error log is empty.)
```
1.2.4.8 - christopher [15/Jan/2018:19:16:03 +0100] "PROPFIND /remote.php/webdav/null HTTP/1.1" 404 1022 "-" "Mozilla/5.0 (Android) ownCloud-android/2.0.0"
```
#### Nextcloud log (data/nextcloud.log)
(Just one line, the adjacent lines said the same.)
```
{"reqId":"Q3K70wSdh6EucrRSFvUS","level":0,"time":"2018-01-15T18:15:33+00:00","remoteAddr":"1.2.4.8","user":"christopher","app":"webdav","method":"PROPFIND","url":"\/remote.php\/webdav\/null","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotFound\",\"Message\":\"File with name null could not be located\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(967): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('null')\\n#1 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1666): Sabre\\\\DAV\\\\Server->getPropertiesIteratorForPath('null', Array, 0)\\n#2 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(355): Sabre\\\\DAV\\\\Server->generateMultiStatus(Object(Generator), false)\\n#3 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPropFind(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PROPFIND', Array)\\n#6 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(76): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/html\\\/remote.php(162): require_once('\\\/var\\\/www\\\/html\\\/a...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/ObjectTree.php\",\"Line\":173}","userAgent":"Mozilla\/5.0 (Android) ownCloud-android\/2.0.0","version":"12.0.4.3"}
```

A resulting problem of this is that I cannot accept shared files within the app, anywhere. I have to use the other interfaces.

**Comment by tobiasKaminsky** [comment]
@nickvergessen I suspect that we get the wrong url back?

**Comment by nickvergessen** [comment]
Can you check if it works in the web UI?

**Comment by karottenbaum** [comment]
Accepting files via notification works in the web UI, but the Activity pane doesn't have clickable links for the file.

**Comment by nickvergessen** [comment]
@tobiasKaminsky https://github.com/nextcloud/server/blob/master/lib/public/RichObjectStrings/Definitions.php#L327-L345
do you interpret the name as file path?

**Comment by tobiasKaminsky** [comment]
No, as far as I can see name is name and path is set to path:
https://github.com/nextcloud/android-library/blob/c4af3e9bb03de30f3b5673940555984948c6157b/src/com/owncloud/android/lib/resources/activities/models/RichElementTypeAdapter.java#L100-L122
