### ISSUE TITLE
Android (playstore) app will not log in to server 12.04 backend

### ISSUE THREAD

**Issue by stratus-ss** [nextcloud/android#1970]
### Actual behaviour
- Unable to log in with either the Beta client or the regular android client. This happened on an install of server 12.03 and then an upgraded version of 12.04 as well as a fresh install of 12.04 (except I preserved the data folder). When attempting to log in I click the "grant access" button enter a user name and password and the app "spins" for ever before prompting me to revert to the older style login. Tailing the logs on the server shows that the request is made, I see responses from `remote.php/webdav` and some entries. When I try and invalid password the app still spins for ever but the server logs show the invalid access attempt. 

If I keep trying (I spent 3 hours trying to log in and debug this myself) one in maybe 20 tries the login succeeds but I am greeted with no files or folders and what appears to be constant scanning until either the app crashes or my screen goes to sleep. When either event happens the app is logged out (despite having clicked the "remember" option) and I have to start the whole process again.

Using a mobile browser yields no problems. Additionally, using the *owncloud beta* android app (which is free) allows me to log in and have the instant upload of my photos (which is my main concern). Desktop browsers as well as desktop integration works as expected so I am sure this is a problem with the android app. Previously I had no problems, I have been using the beta app for the last several months without issue

### Expected behaviour
- I expect to be able to log in and see my files as I am able to with the owncloud app
 
### Steps to reproduce
1.  Download the nextcloud-client app (or beta) from the play store
2.  Attempt to log in with username and password
3.  Never actually able to log in

### Environment data
Android version: Android 7.0 with Nov 6, 2017 security patches
Kernel: 4.1.18-g6583b88

Device model:  Honor 6XXX

Stock or customized system: Stock

Nextcloud app version: Latest version from the play store (as well as the latest beta)

Nextcloud server version: 12.04

#### Web server error log
```
To follow shortly when I test 
```

#### Nextcloud log (data/nextcloud.log)
```
Unable to locate nextcloud.log, it does not show up in filesystem searches and `data/com.nextcloud.client` has no logs
```

**Comment by tobiasKaminsky** [comment]
Can you create us a test account and send the credentials to android at nextcloud dot com with a reference to this issue?

**Comment by frelis** [comment]
I have the same behavior, logs in for half second and after requests the password again, my back end is 11.0.5

**Comment by stratus-ss** [comment]
I had sent the email as requested although I don't know if it was received

**Comment by tobiasKaminsky** [comment]
@stratus-ss / Steve
I got your email and can successfully login with your provided credentials.
I experienced a very long waiting to get the login view. 
Maybe your connection is even slower and therefore it times out?

**Comment by stratus-ss** [comment]
So I cannot speak for the app login time (although its only a 10M connection), with a web browser for me its sub 2 seconds from the time I hit enter to the time that I get in to see files.

Here are the logs from when I login (and then immediately get logged out) using the app:

```209.6.33.162 - - [22/Jan/2018:17:39:28 -0500] "GET /index.php/login/flow/redirect?clientIdentifier=&stateToken=<removed> HTTP/1.1" 303 -
209.6.33.162 - - [22/Jan/2018:17:39:28 -0500] "GET /index.php/login?redirect_url=/index.php/login/flow/redirect%3FclientIdentifier%3D%26stateToken%3<removed> HTTP/1.1" 200 7753
209.6.33.162 - - [22/Jan/2018:17:39:29 -0500] "GET /index.php/core/js/oc.js?v=4312c8c4cdfe10ec7e0a9c65160aa6c0 HTTP/1.1" 200 3208
209.6.33.162 - - [22/Jan/2018:17:39:29 -0500] "GET /cron.php HTTP/1.1" 200 20
209.6.33.162 - - [22/Jan/2018:17:39:46 -0500] "POST /index.php/login?redirect_url=/index.php/login/flow/redirect%3FclientIdentifier%3D%26stateToken%3<removed> HTTP/1.1" 303 -
209.6.33.162 - - [22/Jan/2018:17:39:53 -0500] "GET /index.php/login/flow/redirect?clientIdentifier=&stateToken=<removed>  HTTP/1.1" 200 6401
209.6.33.162 - - [22/Jan/2018:17:39:54 -0500] "GET /index.php/core/js/oc.js?v=4312c8c4cdfe10ec7e0a9c65160aa6c0 HTTP/1.1" 200 3261
209.6.33.166 - - [22/Jan/2018:17:39:54 -0500] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 1369
209.6.33.162 - - [22/Jan/2018:17:39:55 -0500] "POST /index.php/login/flow HTTP/1.1" 303 -
209.6.33.162 - - [22/Jan/2018:17:39:55 -0500] "GET /cron.php HTTP/1.1" 200 20
209.6.33.162 - - [22/Jan/2018:17:39:55 -0500] "GET /status.php HTTP/1.1" 200 146
209.6.33.162 - - [22/Jan/2018:17:39:56 -0500] "HEAD /remote.php/webdav/ HTTP/1.1" 401 -
209.6.33.162 - stratus [22/Jan/2018:17:39:56 -0500] "HEAD /remote.php/webdav/ HTTP/1.1" 200 -
209.6.33.162 - stratus [22/Jan/2018:17:40:03 -0500] "GET /ocs/v1.php/cloud/user?format=json HTTP/1.1" 200 376
209.6.33.162 - "" [22/Jan/2018:17:40:10 -0500] "GET /ocs/v1.php/cloud/users/stratus?format=json HTTP/1.1" 401 140
209.6.33.162 - "" [22/Jan/2018:17:40:10 -0500] "GET /ocs/v1.php/cloud/capabilities?format=json HTTP/1.1" 401 140
209.6.33.162 - "" [22/Jan/2018:17:40:10 -0500] "GET /index.php/avatar/stratus/384 HTTP/1.1" 200 34
209.6.33.162 - "" [22/Jan/2018:17:40:10 -0500] "GET /status.php HTTP/1.1" 200 146
209.6.33.162 - "" [22/Jan/2018:17:40:11 -0500] "GET /ocs/v1.php/cloud/capabilities?format=json HTTP/1.1" 401 140
209.6.33.162 - "" [22/Jan/2018:17:40:11 -0500] "GET /ocs/v1.php/cloud/user?format=json HTTP/1.1" 401 140
209.6.33.162 - "" [22/Jan/2018:17:40:11 -0500] "PROPFIND /remote.php/webdav/ HTTP/1.1" 401 343
209.6.33.162 - - [22/Jan/2018:17:40:18 -0500] "GET /status.php HTTP/1.1" 200 146
209.6.33.162 - - [22/Jan/2018:17:40:18 -0500] "HEAD /remote.php/webdav/ HTTP/1.1" 401 -
209.6.33.162 - - [22/Jan/2018:17:40:19 -0500] "GET /index.php/login/flow HTTP/1.1" 200 6937
209.6.33.162 - - [22/Jan/2018:17:40:20 -0500] "GET /index.php/core/js/oc.js?v=4312c8c4cdfe10ec7e0a9c65160aa6c0 HTTP/1.1" 200 3208
209.6.33.162 - - [22/Jan/2018:17:40:20 -0500] "GET /cron.php HTTP/1.1" 200 20
209.6.33.166 - - [22/Jan/2018:17:40:24 -0500] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 1369
```

I spotted the `HEAD /remote.php/webdav/ HTTP/1.1" 401` line and so I reran the permissions script found https://docs.nextcloud.com/server/9.0/admin_manual/installation/installation_wizard.html#setting-strong-directory-permissions but it did nothing. I get the same results

**Comment by stratus-ss** [comment]
@tobiasKaminsky anything else I can do to help investigate this?

**Comment by tobiasKaminsky** [comment]
Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

**Comment by stratus-ss** [comment]
[logcatOutput27Jan2018.txt](https://github.com/nextcloud/android/files/1670426/logcatOutput27Jan2018.txt)

Attached as requested sorry for the delay

**Comment by stratus-ss** [comment]
Installed the nightly from Jan 27, so far no problems... i wonder what the difference is

**Comment by tobiasKaminsky** [comment]
Indeed strange, but good that it is working now.
