### ISSUE TITLE
3.0RC1: Videoplayback in full-screen isn't really full-screen

### ISSUE THREAD

**Issue by steve-s-71** [nextcloud/android#1971]
I was checking 3.0RC1 towards my earlier reported bug #1761 that has been greatly resolved - many thanks to @AndyScherzinger 

Another finding that I recognized after I reported #1761 and still existing in 3.0RC1 is that Videoplayback in full-screen isn't really full-screen. There is always a thick bar labeled "Nextcloud" that appears unnecessary to me:

![skizze](https://user-images.githubusercontent.com/17343515/35001011-220dcfae-fae6-11e7-9c8e-b20746ffc2fe.png)

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger do you have in idea here? :-)

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky would have to look into it, so no idea right away :(

**Comment by AndyScherzinger** [comment]
PR is #2360

**Comment by AndyScherzinger** [comment]
Hi @steve-s-71 Fix will ship with 3.1RC1 :+1:

**Comment by steve-s-71** [comment]
Super! 

If you want me to test, just drop a link to the RC1 binary (I assume RCs dont go through G Play Beta Channel).

**Comment by AndyScherzinger** [comment]
The RCs do exactly that, going through the G Play beta channel :)

So RC1 will be there as soon as we have the remaining issues fixed and merged for the release candidate...

**Comment by AndyScherzinger** [comment]
Hi @steve-s-71 3.1 RC1 should now be available to you via the GPlay Beta channel!

**Comment by steve-s-71** [comment]
Hi @AndyScherzinger. I tried 3.1 RC1 and can confirm the issue is gone. Good job!

**Comment by AndyScherzinger** [comment]
Hi @steve-s-71 glad to hear the fix is working and always happy to help!

**Comment by AndyScherzinger** [comment]
Hi @steve-s-71 just wanted to let you know that we released 3.1.0 stable, so now the fix is also available in the stable release.
Thanks again for taking the time to report this issue and also testing the fix and providing all the feedback!
