### ISSUE TITLE
External sites are not shown.

### ISSUE THREAD

**Issue by xXSTrikeXx** [nextcloud/android#1976]
On 2.0 I could reach each external site. Now on 3.0 RC there are no external sites in the menu.

Well done work on the app! Rly!

**Comment by AndyScherzinger** [comment]
Do you have an idea @tobiasKaminsky ?

**Comment by xXSTrikeXx** [comment]
When I click on my profile informations (mail&phone...) and then back to the main view there are 2 of 3 of the external sites rechable in the menu. Else there are no external links in the menu.

**Comment by tobiasKaminsky** [comment]
Fixed. I cleared the links too early.
