### ISSUE TITLE
3.0RC1 Share Icon disappears

### ISSUE THREAD

**Issue by splitt3r** [nextcloud/android#1979]
### Actual behaviour
- After clicking on the share icon of a shared folder the icon disappers from the files list

### Expected behaviour
- The icon should stay

### Steps to reproduce
1. Share a folder via Server
2. Open the Android app
3. Click on the share icon of the folder

### Environment data
Android version: 7

Device model: Nexus 6

Stock or customized system: Custom ROM

Nextcloud app version: RC1 from the Play Store

Nextcloud server version: 12

![share_icons](https://user-images.githubusercontent.com/1869584/35041914-c32a8594-fb86-11e7-8d58-22bb403780f3.png)

**Comment by AndyScherzinger** [comment]
I could reproduce the issue with the actual master on OPT3T Android 8

**Comment by splitt3r** [comment]
The two button do exactly the same :flushed:?

**Comment by splitt3r** [comment]
Ok, sounds good.

**Comment by tobiasKaminsky** [comment]
The problem is that in the dialog the drawable is colored white and then remains white.
Solution is to make this one mutable.
> Make this drawable mutable. This operation cannot be reversed. A mutable drawable is guaranteed to not share its state with any other drawable.
