### ISSUE TITLE
 Missing Files in Android

### ISSUE THREAD

**Issue by area57** [nextcloud/android#1989]
### Actual behaviour
- in NC 3.0.0 RC1 the given save  path Changes, so the Client does a complete Resync and nie i have duplicates which does Not Show Up in Pictures for exampel
### Expected behaviour
-no Change in save path after Update
 
### Steps to reproduce
1. 
2. 
3. 

### Environment data
Android version: 7

Device model: Samsung Galaxy S7edge

Stock or customized system:stock

Nextcloud app version:3.0.0 RC1

Nextcloud server version:13.0.0 Beta 3

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by mario** [comment]
Well, I've tested it quite a few times after the PR was finished and it didn't change the storage path on its own. You tested it too afaik.

**Comment by tobiasKaminsky** [comment]
I suppose this is the problem as we silently use another storage path:
https://github.com/nextcloud/android/pull/1954/files#diff-b0fb3ea404c4520c55c0a642245615dfR117

This then should be reverted, or? Changing the storage path can still be done in preferences.

This should be fine as it is only a fallback:
https://github.com/nextcloud/android/pull/1954/files#diff-cba2b2d836007aea7c192ab85f22c8b4R1020

**Comment by mario** [comment]
This is the default if there's nothing stored in preferences.

**Comment by tobiasKaminsky** [comment]
Right, I read it wrong.
Then I do not know what is going on.
I'll try to reproduce it now with a real device.

**Comment by tobiasKaminsky** [comment]
I tried it with S5 Neo:
- installed 2.0.0 
- downloaded some file
- move storage to external 
- installed 3.0RC1
- all files are still there

**Comment by xXSTrikeXx** [comment]
Cant reproduce it.

**Comment by tobiasKaminsky** [comment]
I can reproduce it with:
- install 2.0 
- do nothing wrt storage path
- install 3.0rc
- storage path is now changed

2.0:    /storage/emulated/0
3.0:    /data/user/0/com.nextcloud.client/files

This is due to changing the default here:
https://github.com/nextcloud/android/blob/88498e4071c5606b28d84e2bd7d65de95b458cbf/src/main/java/com/owncloud/android/MainApp.java#L117-L118
