### ISSUE TITLE
Store files on SD card

### ISSUE THREAD

**Issue by ThomasSteinbach** [nextcloud/android#20]
Currently all files synchronized by the app become stored on the internaml device memory. However it should be able to store files to the SD card instead.

A typically use case would be synchronizing a music library, which could exceed the internal storage by far and is ideally stored on a modern SD card.

PR: #92

**Comment by AndyScherzinger** [comment]
Joint venture of @przybylski and @tobiasKaminsky 

Work in Progress https://github.com/nextcloud/android/tree/externalSD2

Already available in the beta client (soon to be found on f-droid).

**Comment by tobiasKaminsky** [comment]
@ThomasSteinbach this is something I personally want to have as soon as possible working 100%.
Meanwhile you can test it in the beta version on fdroid and report your experience.

**Comment by ThomasSteinbach** [comment]
@tobiasKaminsky I am sorry to say that but currently I am short in time to experiment with. But I'll be the first using this feature when there's a stable version on the playstore.

**Comment by tfl** [comment]
Would like to see this too - it always eats up my internal memory and I do not sync my mp3 library but only images.

**Comment by tobiasKaminsky** [comment]
@tfl can you try the beta and report if it works?

**Comment by tfl** [comment]
The last version I can get from f-droid is from June, 17. Does this version fit? And do I have to remove version 1.0.0?

**Comment by tfl** [comment]
Sorry, I tried it anyway... But the install process failed with an unknown error. So... I can't test the beta at this point.

**Comment by tfl** [comment]
Now, while trying to get a screenshot of the error the installation worked!

**Comment by tfl** [comment]
Ok. Seems to work. The beta allowed me two different storage paths. I know what path on my G3 Motorola points to the external storage. I selected it and all the images I downloded afterwards went to the external sd card. Good. One suggestion: let the user select from "internal storage"  or "external storage". I know what a storage path is. I suspect others won't.

**Comment by tobiasKaminsky** [comment]
@przybylski FYI

**Comment by przybylski** [comment]
Accessing such information is highly restricted in android, in android 6 and later its even more limited. I need to research on how to do it.

**Comment by tobiasKaminsky** [comment]
@przybylski browsing through the comments on play store this is a highly wanted feature.
Is there something I/we can help you with?

**Comment by AndyScherzinger** [comment]
Like @tobiasKaminsky said, is there something we can help you with. Unfortunately I only have devices without an sd card.

**Comment by przybylski** [comment]
For starters you can get me more time in a day :)
I'll try to put it on my schedule ASAP

**Comment by corax205** [comment]
I moved the data files with the beta from f-droid. It works fine! I moved ~5GB.

I like the Suggestion from tfl. 
A bit more comfortable could it be, if the user can choose the complete storage path.

**Comment by maxaustria** [comment]
Hello guys, I would love to see this feature working but the current way how you implement it is not working for me, so I would like to describe my use case here, maybe you consider it in future releases or have an idea how to work around it. Basically I have confidential information (ids,medical records, etc) and big data (pictures, mp3) stored in my cloud yet. Of course it would be very useful to move the big data to the external sdcard (I am doing this manually right now). The problem is, if I move the whole storrage path also my confidential information gets stored on the sdcard. So my internal memory is encrypted, if my gets stolen again, I don't care, but the SDcard is not. So a solution could be to be able to set the storage path for each riot folder for example. Let me know what you think about it.

**Comment by tobiasKaminsky** [comment]
@maxaustria I think this would be too much settings for an average user and it will be a lot of more work for the devs.
Starting with android 6 you can encrypt your sdcard. I think this is the way to go as with this approach also all other apps/files are secured.

**Comment by maxaustria** [comment]
Ok, fine for me. Another idea: What about putting the setting on account level, then I could make a big data account and a confidential account?

**Comment by Xeniac-at** [comment]
I like the Idea with the storage path on account level. As far as i can remember, it is the way as the deskop client handles this. I like the idea that software offers an equal featureset on different platforms and offers these features in the same spots.

btw: Dont's set your bets on encryptet SD cards. Getting android updates is a matter of wishful thinking and many handset vendors remove some AOSP features.

**Comment by Gerii** [comment]
The desktop client allows you to synchronize each folder on the cloud with a different local folder. It's just the standard setting that the whole account is synchronized into a single local folder. Would be nice if the same system can be implemented into the mobile client.

**Comment by edgeHB** [comment]
Hey there, i just wanted to know if this issue is somehow connected to this one: https://github.com/nextcloud/android/issues/286.

**Comment by AndyScherzinger** [comment]
Imho no, since #286 to me seems about access rights while this one is about the Nextcloud app storing its files on the SD card rather than internal memory.

**Comment by ThomasSteinbach** [comment]
I am very happy to say that the original issue is solved by the implementation in version 1.4.0. More information about the release:

https://nextcloud.com/blog/nextcloud-android-client-1.4.0-has-been-released/

**Great thanks to the lovers and engineers of Nextcloud making Open Source great all day!**

If anybody is not satisfied with the implementation of the external SD Card support, please open a new issue specifying the concrete problems. This issue here would be closed as the implementation works in general.

**Comment by AndyScherzinger** [comment]
Happy to hear you like the solution and the new release :)
