### ISSUE TITLE
Retrying failed uploads stops the app

### ISSUE THREAD

**Issue by detly** [nextcloud/android#2000]
### Actual behaviour
- Retrying failed uploads stops the app

### Expected behaviour
- The failed uploads are retried
 
### Steps to reproduce
- Open Nextcloud
- Go to "Uploads" from sidebar
- Notice some uploads failed
- Select "retry failed uploads" from the `...` menu
- Get an Android system message "Nextcloud has stopped" with options to open again, send feedback,e tc.

### Environment data
Android version: 7.1.2

Device model: HTC One M9

Stock or customized system: Custom (LineageOS 14.1)

Nextcloud app version: 3.0.0 RC1

Nextcloud server version: 12.0.4

### Logs

No app logs.

#### Web server error log/Nextcloud log (data/nextcloud.log)

Omitted because it's probably not relevant, but I'll add it if you want.

Note that the uploads *do* still eventually happen if I re-launch the app and just let it run in the background.

**Comment by mario** [comment]
We know. Already fixed, but wait for RC2 please :)

**Comment by detly** [comment]
No worries! I did search first, I promise 😁

**Comment by mario** [comment]
Heheh

**Comment by tobiasKaminsky** [comment]
https://github.com/nextcloud/android/pull/1980 maybe not the best topic line after all ;-)

**Comment by tobiasKaminsky** [comment]
Please test it with RC2 (coming soon) and re-open if it occurs again.

**Comment by detly** [comment]
Unfortunately now (in RC2) the menu entry does nothing ie. I tap it, the
number of failed uploads stays exactly the same, but the menu entry itself
disappears. For whatever reason, the failed uploads are never retried.

Might be worth mentioning, the failed entries are all from before the RC2
update. Any photos and videos taken since then have been uploaded.


On 19 Jan. 2018 5:51 pm, "Tobias Kaminsky" <notifications@github.com> wrote:

Please test it with RC2 (coming soon) and re-open if it occurs again.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/nextcloud/android/issues/2000#issuecomment-358881884>,
or mute the thread

**Comment by mario** [comment]
@tobiasKaminsky is this related to service not starting maybe?

**Comment by tobiasKaminsky** [comment]
I only found problems with not starting service with >=8.0.

**Comment by mario** [comment]
@tobiasKaminsky retry works for you?

**Comment by tobiasKaminsky** [comment]
I tried it with 8.1 and it is not working.
Retry button is doing nothing at all.

**Comment by detly** [comment]
Confirming RC3 fixes both the crash and the "nothing happens" problem ie. it all works as I'd expect. Thanks! :+1:
