### ISSUE TITLE
Wrong color of "password" on E2E

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#2007]
This must be slipped through.
@AndyScherzinger aka master of UI, can you have a look there? 👍 

![2018-01-19-114702](https://user-images.githubusercontent.com/5836855/35147341-87f4f778-fd0e-11e7-9e90-24d18a9cb4f4.png)

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky this should imho work since there is
```
passwordField.getBackground().setColorFilter(accentColor, PorterDuff.Mode.SRC_ATOP);
```
and also
```
Drawable wrappedDrawable = DrawableCompat.wrap(passwordField.getBackground());
        DrawableCompat.setTint(wrappedDrawable, accentColor);
        passwordField.setBackgroundDrawable(wrappedDrawable);
```
So I don't understand why this isn't tinted?! :(

**Comment by AndyScherzinger** [comment]
The later part should imho not be necessary but I might be mistaken

**Comment by tobiasKaminsky** [comment]
At first it is working, but as soon as I enter text it does not work anymore:
![2018-01-19-121022](https://user-images.githubusercontent.com/5836855/35148241-bce4b72c-fd11-11e7-9c93-83925bc305d2.png) ![2018-01-19-121059](https://user-images.githubusercontent.com/5836855/35148268-cf422df0-fd11-11e7-8bd7-ff10367c5d46.png)

**Comment by AndyScherzinger** [comment]
hmmm, then we maybe need to use a colorStateList :(

**Comment by tobiasKaminsky** [comment]
Then I'll give it a try. Thanks for the tip.

**Comment by tobiasKaminsky** [comment]
With
```
passwordField.setSupportBackgroundTintList(ColorStateList.valueOf(accentColor));
```
![2018-01-19-150207](https://user-images.githubusercontent.com/5836855/35154218-b7a8fdfa-fd29-11e7-88fc-5b155eb75c63.png)

But: AppCompatEditText.setSupportBackgroundTintList can only be called from within the same library group (groupId=com.android.support)

Doing it the "right" way with 
```
ViewCompat.setBackgroundTintList(passwordField, ColorStateList.valueOf(accentColor));
```
is not working.

**Comment by AndyScherzinger** [comment]
Maybe adding a list for passwordField.setHintTextColor(); where it probably then needs a list for inactive(grey) and active (accent)...

**Comment by AndyScherzinger** [comment]
Maybe this one helps (not sure)... https://stackoverflow.com/questions/35683379/programmatically-set-textinputlayout-hint-text-color-and-floating-label-color/39271184

**Comment by AndyScherzinger** [comment]
hmmm tried all the mentioned thing and couldn't get it work 😢

**Comment by tobiasKaminsky** [comment]
Thanks for your effort 👍 
What do e went to do now? Remove this fancy PasswordField by a regular textview? 
Keeping it this way is not that nice UI wise :-/

**Comment by AndyScherzinger** [comment]
True, and yes I'd also say the quick win would be to replace it with a standard EditTextView.
