### ISSUE TITLE
Auto-upload not working since the 2.0 update

### ISSUE THREAD

**Issue by Moarc** [nextcloud/android#2011]
### Actual behaviour
Files don't get auto-uploaded. Specifically, they're not queued as they are created; when I click "Force rescan" under Uploads, the Nextcloud app 'notices' them and uploads them perfectly, respecting the charging/WiFi requirement.

### Expected behaviour
New files in selected folders should be queued as they appear.
 
### Steps to reproduce
1. Set photos to be synced with a server-side folder.
2. Take a photo.
3. Auto-upload does not occur.

### Environment data
Android version: 5.1.1

Device model: Samsung Galaxy J3 (J320-FN)

Stock or customized system: SuperSU root and NextApp SDFix
Nextcloud app version: 2.0.1 (from F-Droid)

Nextcloud server version: 13.0.0 Beta 2

#### Web server error log
n/a

#### Nextcloud log (data/nextcloud.log)
n/a

**Comment by tobiasKaminsky** [comment]
Where is your synced folder located? On internal storage or sdcard?

**Comment by Moarc** [comment]
SD card.
One more thing I've noticed: I went out, took some photos, and when I
connected WiFi and plugged in the charger, they were synced properly - so
the behavior I reported isn't consistent. Other times in an analogous
situation, the new files weren't 'noticed' by Nextcloud, and the sync
worked only that one time.

**Comment by gustavohw** [comment]
```
Android version: 5.1.1

Device model: LG G4

Nextcloud app version: 2.0.1 (from F-Droid)

Nextcloud server version: 12.0.5
```
Exactly same issue. Isn't consistent, sometimes it uploads sometimes only by forcing rescan.

Maybe its the folder size and files? I've a 64GB SDcard and about 2.5k files on the DCIM folder.

**Comment by mario** [comment]
Please use 3.0 and let me know.

**Comment by Moarc** [comment]
For me, everything started working flawlessly after the 3.0 release.

**Comment by mario** [comment]
Thanks! :)
