### ISSUE TITLE
files are not synced - version 2.0.0

### ISSUE THREAD

**Issue by ferdiga** [nextcloud/android#2012]
### Steps to reproduce
1. fresh install 2.0.0 on android 7 (ulefone Armor 2)
2. login into my account
3. 

### Expected behaviour
should show the files (works on  android 6 powered device with same account)

### Actual behaviour
does not show anything "no files here"
I can see my "Activities" - hence I am logged in correctly
I can upload a file and only this one is visible in android app (and on the server)
I can delete the file on the server , but it is not deleted on android

## Server configuration detail

**Operating system:** Linux 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64

**Webserver:** Apache/2.4.25 (Debian) (apache2handler)

**Database:** mysql 10.1.26

**PHP version:** 7.0.27-0+deb9u1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, apcu, mysqlnd, PDO, xml, apc, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, imap, intl, json, exif, mcrypt, mysqli, pdo_mysql, pdo_sqlite, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 12.0.4 - 12.0.4.3

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.5.2
 - admin_audit: 1.2.0
 - comments: 1.2.0
 - dav: 1.3.0
 - external: 2.0.3
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_external: 1.3.0
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - nextcloud_announcements: 1.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - password_policy: 1.2.2
 - provisioning_api: 1.2.0
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - updatenotification: 1.2.0
 - workflowengine: 1.2.0
Disabled:
 - admin_notifications
 - announcementcenter
 - bookmarks
 - bruteforcesettings
 - calendar
 - contacts
 - deck
 - encryption
 - files_videoplayer
 - mail
 - nextant
 - notes
 - ocr
 - ojsxc
 - passman
 - registration
 - spreed
 - spreedme
 - tasks
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "ocde8d3204fb",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "datadirectory": "\/var\/www\/owncloud_data",
    "dbtype": "mysql",
    "version": "12.0.4.3",
    "dbname": "owncloud",
    "dbhost": "localhost",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "enable_previews": true,
    "forcessl": true,
    "theme": "",
    "maintenance": false,
    "mail_smtpmode": "smtp",
    "mail_smtphost": "smtp.world4you.com",
    "mail_smtpport": "587",
    "mail_smtptimeout": 10,
    "loglevel": 3,
    "share_folder": "\/Shared",
    "trusted_domains": [
        "service.chricar.at"
    ],
    "mail_from_address": "xenon",
    "mail_domain": "strakosch.at",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "singleuser": false,
    "forceSSLforSubdomains": true,
    "trashbin_retention_obligation": "auto",
    "filelocking.enabled": "false",
    "filesystem_check_changes": 1,
    "mail_smtpauthtype": "PLAIN",
    "mail_smtpsecure": "tls",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "auth.bruteforce.protection.enabled": true,
    "overwrite.cli.url": "\/owncloud",
    "updater.release.channel": "stable"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

<details><summary>LDAP configuration (delete this part if not used)</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

## Client configuration

**Android version:** 
7.0

**Device model:** 
ulefon Armor 2

**Stock or customized system::** 
stock

**Nextcloud app version::** 
2.0.0
**Nextcloud server version::** 
12.0.4
## Logs

<details><summary>Browser log</summary>

```
Insert your webserver log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

**Comment by tobiasKaminsky** [comment]
Is this happening only on the very first start? What happens if you do swipe to refresh?

**Comment by ferdiga** [comment]
nothing, after a short "spinning" wheel "No files here" message again

**Comment by ferdiga** [comment]
I installed owncloud client 2.5.0 and I can access all files.
could it be a timing issue ?
I am currently in Australia and the server is in Germany?

**Comment by tobiasKaminsky** [comment]
Can you create us a test account and send the credentials to android at nextcloud dot com with a reference to this issue?

**Comment by ferdiga** [comment]
FYI, 
automatic update to nextcloud 3.0.0, same problem
uninstalling and reinstalling solved the problem. files are now visible.

**Comment by tobiasKaminsky** [comment]
Strange that you need to re-install the app, but glad that it is now working for you.
