### ISSUE TITLE
Recurring login screen

### ISSUE THREAD

**Issue by koreywithak** [nextcloud/android#2016]
### Actual behaviour
After my app updated and the Nextcloud icon changed (3.0.0 RC1), every time i typed in my password it took me to my files but immediately back to the login screen. The only way to fix was by uninstalling and reinstalling. Also, it crashed when going to the backup contacts screen.

### Expected behaviour
Normal functionality after an update.
 
### Steps to reproduce
1. Update the app to the mentioned version
2. Log in
3. Continue trying to log in

### Environment data
Android version: 7.0

Device model: Nexus 6

Stock or customized system: stock

Nextcloud app version: 3.0.0 RC1

Nextcloud server version: 11.0.3

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by pacovila** [comment]
Same here on a Samsung with 7.0. App version 20180121 Nextcloud dev from F-droid

**Comment by tobiasKaminsky** [comment]
Can you provide us additional infos via logcat? I currently have no clue what the problem could be https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

**Comment by pacovila** [comment]
I have solved the issue by:
- clearing app data and cache
- forcing stop
- uninstall
- reinstall

now the device asks for permission to access my account. Accept. Then

- login

All looks okay now, the login screen did not appear again.

I think the app should reuse stored credentials after update in the first place.

Thanks

**Comment by sharkovios** [comment]
Hi,

i'm currently have the same issue.

Even after clearing the data and reinstalling, it worked for a day and then the same again.

**Comment by koreywithak** [comment]
I'm very much a beginner with this stuff. I will try to figure out logcat when I get some free time. I want to contribute. Maybe there is someone who can get this more quickly than me though.

**Comment by skyfox675** [comment]
Is the SSO plugin required on the server side for the "grant access" functionality to work?
Thanks in advance, 
-Skyfox

**Comment by sharkovios** [comment]
Desktop clients on windows working just fine.
It's very annoying. I've lost connectivity on all my Android Devices and i cannot fix it.
Have you guys found anything?

**Comment by karloluiten** [comment]
Nextcloud dev from fdroid appstore works for me

**Comment by tobiasKaminsky** [comment]
We hope that 3.0.1, which was released ~2h ago, will solve this.

**Comment by AndyScherzinger** [comment]
Please reopen if the issue still occurs with 3.0.1

**Comment by sharkovios** [comment]
I confirm the issue is resolved
