### ISSUE TITLE
Visibility of synchronized files

### ISSUE THREAD

**Issue by ncyclon** [nextcloud/android#2033]
### Actual behaviour
Synced files not show in another applications

### Expected behaviour
Before I completely reinstalled the application, the files downloaded for offline access were visible in other applications, such as a gallery and music player.
 
### Steps to reproduce
1. Select folder to synchronize
2. Tring to find in music player (for example) new files

### Environment data
Android version: 6.0.0

Device model: Samsung Galaxy S6 Edge

Stock or customized system: Stock

Nextcloud app version: 3.0.0RC1

Nextcloud server version: 12.0.4

**Comment by tobiasKaminsky** [comment]
We changed the storage behaviour for RC1, but reverted it. So with RC2 all files should be visible again.
We released RC2 just minutes ago.
Please uninstall and re-install RC2 as otherwise the storage path will remain the same.

If it does not work, please reply.
