### ISSUE TITLE
Retry failed uploads does nothing good

### ISSUE THREAD

**Issue by Fjodor42** [nextcloud/android#2035]
### Actual behaviour
- Nothing, apparently
- One thing, though "Retry failed..." disappears from context menu

### Expected behaviour
- Previously failed uploads should be retried
 
### Steps to reproduce
1. Open app
2. Under menu, find "Uploads"
3. From context menu, select "Retry failed..."

### Environment data
Android version:
8.0.0

Device model: 
OnePlus 3T

Stock or customized system:
OnePlus-supplied OxygenOS

Nextcloud app version:
20180124

Nextcloud server version:
12.0.5

### Notes
Unless someone convinces me that this isn't an internal problem with the app, I should deem logs irrelevant as of now.

With #1980 effecting the app to not stop outright, we're on the right track, but it would seem that we are not entirely there yet...

**Comment by mario** [comment]
Sounds like one of the requirements for retry hasn't been met? Do you use wifi-only or charging-only?

**Comment by mario** [comment]
Retry failed disappears once you click on it so you couldn't click on it for thousand of times :P

**Comment by Fjodor42** [comment]
I had WiFi-only on screenshots (have removed that, but two recent "uploads" are (still) waiting for WiFi - even if I click on them specifically to upload.

No restrictions (power or WiFi) on photos, but Retry all still doesn't do anything - I *can* successfully retry uploading single failed uploads by clicking on them.

**Comment by Fjodor42** [comment]
As for the option disappearing, I *do* believe that this should be dependent on a check for, if uploads are actually "mass"-retried or not, as is the case right now, at least for me ;-)

**Comment by Fjodor42** [comment]
Also, the two screenshots left waiting for WiFi say, specifically, "Waiting for WiFi" (I assume it would do something similar for Power).

The failed uploads just say failed, as they have been doing all along - nothing, except for disabling the "mass"-retry, happens in the GUI when I press "Retry failed"...
