### ISSUE TITLE
How to enable auto-upload for all file types and not just pictures?

### ISSUE THREAD

**Issue by kriskropd** [nextcloud/android#2036]
On Nextcloud Android App v2.0.0 I am able to successfully auto-upload images to my Nextcloud server from Chromebook Pro. The problem is I don't want to just auto-upload pictures. I need everything to auto-upload that goes into this particular folder, such as tar.gz files and pdf files and 7z files and maybe binary files. I suspect this might be an intended limitation, but considering image-uploads work just fine I don't quite understand why it would be unavailable to other file types. As such, I've made an assumption that perhaps it must be available and I simply cannot find where to enable it. What really surprises me is I cannot find previous tickets, questions or forum posts about this particular subject as I would expect it to be a highly demanded feature.

Any suggestions would be appreciated.

**Comment by mario** [comment]
You can enable expert mode in settings, and then create a custom folder in auto upload settings. :)

Let me know if that helps.

**Comment by kriskropd** [comment]
That does seem to enable auto-upload for all file types now. Thank you :)

**Comment by AndyScherzinger** [comment]
Thanks for the feedback @kriskropd
I am closing the issue then, please reopen if any issue with it occurs.

**Comment by dfiord** [comment]
Good morning. I have read this issue and although it is closed I have a question related to your response. 

I am trying to sync all file type from a folder using app ver. 3.6.1. I have read that in ver 3.6 the Expert Mode was removed.  My question is how can I set up the app to sync all file types from a folder?

Thank you.

**Comment by AndyScherzinger** [comment]
The same way you did before. The functionality is still there,we just removed the feature switch so now the former expert mode features are now constantly products sent.

**Comment by dfiord** [comment]
Good morning.
This is interesting. I am trying to sync an Excel file on several devices, Server, PC, android hone. I have setup a folder Documents on the phone with the file in it. The folder is listed under the Auto Upload selection from the main menu and the 'cloud' icon is blue. (I am assuming that this indicates that it is in the que for syncing.) When I make a change to this file and re-save it to the folder it does not sync automatically.  It will sync if I do an 'Upload files' from the blue plus sign on the main screen.  

Is this normal or is there a problem? Am I misunderstanding what the 'Auto Sync' function is supposed to do? Is something in my setup incorrect?  

Thank you for your help.  /

**Comment by AndyScherzinger** [comment]
It should get uploaded while it might take some time, at least that is my understanding. Right? @tobiasKaminsky @mario ?

**Comment by dfiord** [comment]
Thank you for confirming this. It does not seem to be working correctly, at least on my HTC One device. Please let me know if there is any information that you need to help resolve this issue.  Thanks again for your help. @mario @tobiasKaminsky

**Comment by dfiord** [comment]
Hi Andy, I just want to check in to see if there is any progress with this issue.  I have tried this several times and also on another android device, a Samsung 9 or 10S and the same thing takes place. Can someone let me know if there is anything I can do make this work correctly or perform a work around? If I do a manual upload it adds additional documents to the server.  Thanks for your help. @mario @tobiasKaminsky

**Comment by v4rakh** [comment]
I can confirm, this is not working as intended I guess.

Android app doesn't upload on any folder content changes when using a custom folder.

**Comment by dfiord** [comment]
Thank you for your response. Do you have any idea when this item may be fixed?

 

~

Donald G. Fiordelisi

 <mailto:d.fiordelisi@verizon.net> d.fiordelisi@verizon.net

H - 609.448.0986

C - 609.841.7536

"Everything matters." - Stewart Butterfield, CEO, Slack Technologies

“Always be ready for luck.” – Anonymous 

“Luck is what happens when preparation meets opportunity.”-Roman Philosopher Seneca

**Comment by v4rakh** [comment]
I guess this highly depends on the project owner's preferences and the priority it has. Nothing I can estimate @dfiord

**Comment by Maxopoly** [comment]
This is still broken in nextcloud dev 20211002. Very annoying as it makes it impossible to sync backup data of other apps.

**Comment by paperbenni** [comment]
Still broken, only the auto uploader only uploads images and videos, sadly makes it unusable for things like signal backups or documents :(

**Comment by drgrumpy** [comment]
Still broken app version 3.19.1

**Comment by 0xpr03** [comment]
Same here, doesn't work for anything other than png & co.

Is it possible you're using the old anroid API which got restricted to only known media documents ?

**Comment by kreidetafels** [comment]
I'm having the same issue, JPGs are working fine, but as soon as I add a pdf it is neither uploaded nor shown in the data browser of nextcloud's auto upload

**Comment by pzwahlen** [comment]
+1

**Comment by scr4bble** [comment]
Still an issue in Nextcloud Android app 3.26.0
Custom folder sync used but pdf files are not being uploaded.

I would say the "custom folder sync settings" should allow to choose "upload all files" or "upload only photos/videos" ... and maybe additional option "upload folders inside recursively".

**Comment by Cebrain** [comment]
Still nothing?

I really don't understand the priority some time for features. 
To auto upload (i dont speak about syncing) a local folder with different files to Nextcloud shouldn't be something extremely special.
Isn't this a basic feature for and cloud based sync app?

**Comment by EricDuminil** [comment]
@Cebrain : Excellent, thanks! The special permission setting is well hidden, and not visible from NextCloud settings or permissions.

On my Android 14, it's in Settings > Apps > "..." > Special access > All files access.

Many Samsung Bloatware apps had access to all files, but not NextCloud. After turning it on, AutoUpload started uploading my WhatsApp backups among others.

NextCloud App could try to ask for more permissions, or at least display a warning that only Pictures and Videos are uploaded by default.

**Comment by scr4bble** [comment]
Switching the File-access permission for the app to "All files" solved this issue. The auto-upload feature now upload all files from the folder correctly (including pdf files).

So the bug description should be: nextcloud doesn't ask for permission it needs when it should.

**Comment by CrazyVaclav** [comment]
Device Pixel7Pro with Android 15 GrapheneOS

Hi, I have the same problem only media files are allowed and the nextcloud app does not ask for "All Files" Permission.
With the default "App permissions" I cannot give the nextcloud App "All Files" Permission ( The Option is not there)
![Image](https://github.com/user-attachments/assets/a31fb469-e076-45e2-8a4d-c381aaeb1d92)

So I tried the "Special access > All files access." method. The Problem is that the nextcloud app is there also not listed, so I cannot enable the full file access:
![Image](https://github.com/user-attachments/assets/6b0cff28-269a-440c-b7ae-8641ce93e3a2)

Does anyone know how to do this with GrapheneOS

**Comment by Cebrain** [comment]
The problem is google is not allowing this anymore.
Install the Nextcloud App from FDroid Store and it will work again.

**Comment by logiczny** [comment]
I can confirm, installing from FDroid store solves the issue, the app after launching asks for permissions to all files. And autosend of anything (not just photos/videos) works beautifully.

**Comment by onlynickleft** [comment]
> Device Pixel7Pro with Android 15 GrapheneOS
> 
> Hi, I have the same problem only media files are allowed and the nextcloud app does not ask for "All Files" Permission. With the default "App permissions" I cannot give the nextcloud App "All Files" Permission ( The Option is not there) ![Image](https://github.com/user-attachments/assets/a31fb469-e076-45e2-8a4d-c381aaeb1d92)
> 
> So I tried the "Special access > All files access." method. The Problem is that the nextcloud app is there also not listed, so I cannot enable the full file access: ![Image](https://github.com/user-attachments/assets/6b0cff28-269a-440c-b7ae-8641ce93e3a2)
> 
> Does anyone know how to do this with GrapheneOS

No. This is actually the proper way to do it (v. 3.34.1). All you need to do is press the three dot menu on the top right to reveal "Show System". Select that and Nextcloud will appear as an option. Toggle on "Allow access to manage all files" and you're set. You'll even see the fille icons in the auto-upload folders even if they aren't images or videos.
