### ISSUE TITLE
Rename folder to existing name -> wrong snackbar

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#2040]
### Actual behaviour
-"could not give server new name"

### Expected behaviour
- "renaming not possible, name already taken" or similar
 
### Steps to reproduce
1. rename a file/folder to an already existing name
2. look at snackbar

**Comment by cheikhSall** [comment]
Just discovered your app and UnixCorn and I love it. I'm trying to fix this issue, hoping it starts the beginning of a list of contributions.

**Comment by comradekingu** [comment]
"Could not rename server" is the same as the "Could not rename" convention used twice already in Files. There is one "Could not give server new name" in Android, and also "Local copy could not be renamed" but it is just longer for no obvious benefit.

**Comment by AndyScherzinger** [comment]
Welcome @cheikhSall and awesome to read you want to work on it,highly welcome!

If you have any questions or need any pointers @tobiasKaminsky @mario and me are here to help! Don't hesitate to ask 😃

**Comment by AndyScherzinger** [comment]
@comradekingu so what should be the used text here? I'd don't have a good idea but would expect the text to state the issue an in the name being taken already. Else it would be just an "oops" ;)

**Comment by cheikhSall** [comment]
thank you for your welcoming

**Comment by comradekingu** [comment]
@AndyScherzinger @cheikhSall 
I see nothing wrong with "Could not rename server". I made the needed changes in #2115 to have it be that way throughout.
