### ISSUE TITLE
The app does not show all files

### ISSUE THREAD

**Issue by sysoppl** [nextcloud/android#2044]
### Actual behaviour
Almost all files that was uploaded via app just disappear after upload is finished, but they are visible in browser. This also applies to subdirectories

![desktop](https://user-images.githubusercontent.com/30871217/35399078-bc6a6c1a-01f3-11e8-97de-f6180a854693.png)
7 folders, 11 files is uploaded

![phone](https://user-images.githubusercontent.com/30871217/35399207-09db19a4-01f4-11e8-97dc-e6be9c720679.png)
and only 1 file is visible in app

Update:
Also files that show up, when you try to download it shows "this file is not available on the server"
### Expected behaviour
All files should appear
 
### Steps to reproduce
1. Install nextcloud android app
2. Log in to cloud
3. Refresh

### Environment data
Tested on two devices
Android version: 7.1.2 / 6.0

Device model: LG G3s (d722) / Galaxy Tab 2

Stock or customized system: customized (lineageos)

Nextcloud app version: 2.0.1, 3.0.0 RC1, 3.0.0 RC2 / 3.0.0 RC2

Nextcloud server version: 12.0.4, 12.0.5

## Server configuration detail

**Operating system:** Linux 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64

**Webserver:** Apache/2.4.18 (Ubuntu) (apache2handler)

**Database:** mysql 5.7.21

**PHP version:** 7.0.22-0ubuntu0.16.04.1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, json, exif, mcrypt, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 12.0.5 - 12.0.5.3

Array
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.5.2
 - bruteforcesettings: 1.0.3
 - comments: 1.2.0
 - dav: 1.3.1
 - encryption: 1.6.0
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - metadata: 0.6.0
 - nextcloud_announcements: 1.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - password_policy: 1.2.2
 - provisioning_api: 1.2.0
 - quota_warning: 1.1.1
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - spreed: 2.0.2
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - twofactor_totp: 1.3.1
 - updatenotification: 1.2.0
 - workflowengine: 1.2.0
Disabled:
 - admin_audit
 - files_external
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "htaccess.RewriteBase": "\/",
    "instanceid": "ocar89cc8suv",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "..."
    ],
    "datadirectory": "...",
    "overwrite.cli.url": "...",
    "dbtype": "mysql",
    "version": "12.0.5.3",
    "dbname": "...",
    "dbhost": "...",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** yes

**Comment by rexxmagnus** [comment]
I'm also experiencing this issue (I'll have to add diagnostic info later). I suddenly had a file that I was editing offline disappear with the message that it couldn't be written to. I tried re-uploading a copy and the file then appeared with (2) in the filename of the upload but also didn't appear.
On the web interface, both the original and additional copies appear, but they do not show in the android app, even after resetting the cache.

**Comment by sysoppl** [comment]
Every time when I try to open a file, and get the "this file is not available on the server" error, in logs shows up
![err1u](https://user-images.githubusercontent.com/30871217/35487189-209e6196-0479-11e8-9fab-ba0b0c0fefcf.png)

Also, there show up only one (first) file in each folder

**Comment by tobiasKaminsky** [comment]
@sysoppl @rexxmagnus 
Can you both create us a test account and send the credentials to android at nextcloud dot com with a reference to this issue?

@sysoppl you mention that you have this problem also on 2.0.1
@rexxmagnus is this new for you in 3.0RC? Or have you experienced this also at 2.0.1?

**Comment by rexxmagnus** [comment]
I'm pretty sure this has arisen only in the latest update (3.0RC2). It didn't occur on the 12th of January 2018 with whichever version was current on the google play beta channel at that time, if that's any help.

**Comment by sysoppl** [comment]
Tested again with 2.0.1 and 3 RC2
2.0.1 - sorry, that was my mistake - files show up, but I can't access any of it
Uploaded files:
![screenshot_20180129-172524](https://user-images.githubusercontent.com/30871217/35522639-2cede1c0-051d-11e8-8387-e1e74298bbc4.png)


Open file:
![screenshot_20180129-172530](https://user-images.githubusercontent.com/30871217/35521824-00a8bdf8-051b-11e8-960b-10dae771bfbf.png)
"Download failed"

Server error:
![2 0 1 error](https://user-images.githubusercontent.com/30871217/35521831-085af7fa-051b-11e8-9f7f-d3ee891f884e.png)

Note: this folder is not e2e encrypted, the same error show up when I created new folder on 2.0.1 app, uploaded files and tried to open them. Same problem was few weeks ago - I was not able to download files, and that was before I updated to beta and e2e was enabled.

3.0 RC2 - 1 file in each folder. When I was changing the storage path, for short time all files show up, but I was not able to download them (same error as in my second post)

Uploading files to new folder created in 3.0 RC2:
![screenshot_20180129-175347](https://user-images.githubusercontent.com/30871217/35522867-c870f718-051d-11e8-8d95-930f5a23ec85.png)

Refresh:
![screenshot_20180129-175405](https://user-images.githubusercontent.com/30871217/35522876-cd28d83e-051d-11e8-896a-5b989ec9dee9.png)

Open file:
![screenshot_20180129-175423](https://user-images.githubusercontent.com/30871217/35522884-d321ba9e-051d-11e8-8165-132d5bcf35c5.png)
"Download failed"

Server error: same as in my second post

**Comment by tobiasKaminsky** [comment]
@sysoppl thank you very much for your detailed help!
With test account by @rexxmagnus I could also verify that the missing files are marked as encrypted, which they obviously should not.
I'll talk with @schiessle, he is our e2e server guy.

Please remain both test accounts for now.

**Comment by rexxmagnus** [comment]
I am using the default encryption module, if that has any bearing on it - but obviously doesn't explain why some files are showing and others not, but I'll leave the diagnostics up to you. :)
Thanks.

**Comment by tobiasKaminsky** [comment]
The files that are missing are encrypted via server side encryption and this conflicts with end to end encryption as the share both the same encryption flag on files.
I will create a fix for android and it will also be changed on server side (encryption app).

In the next dev version or the next RC3 it will work.

**Comment by rexxmagnus** [comment]
In the meantime, can I now un-encrypt the files on the server until it's fixed, or do you need my test case to be accessible in its current state?

**Comment by tobiasKaminsky** [comment]
You can unencrypt your files, if you want.
Thanks for your test account, you can both, @rexxmagnus and @sysoppl remove them.
