### ISSUE TITLE
Auto-Upload completely messes up the nextcloud file base

### ISSUE THREAD

**Issue by Snaptags** [nextcloud/android#2045]
### Actual behaviour
You can set up a custom auto upload folder. You can do so by selecting the local nextcloud data folder, hoping to get something resembling the two-way sync the windows client has been able do perform for years.
Actual behavior: the android client does upload the whole folder structure, **ignoring** folder names in the process. You end up with millions of files in the ROOT folder.

After deleting the messed up crap, I can sync as often as I want, the millions of files remain on the android client. I have to delete the account completely and re-setup everything

### Expected behaviour
Any behavior other than what is happening in the 3.0.0 RC2
Best guesses: don't accept the nextcloud data folder, if keeping the folder structure is such a big deal
 
### Steps to reproduce
1. using windows set up some files in subfolders
2.  sync everything to the android client. You have to select EVERY subfolder manually to do so.
3.  set up auto-upload to upload the /sdcard/0/nextcloud/user@server/ folder to /
4. sit back and watch the android client up- and downloading all the files

Nextcloud app version:
3.0.0 RC2
Nextcloud server version:
12

**Comment by mario** [comment]
Glad to have this fixed ;)
