### ISSUE TITLE
Sharing encrypted folder

### ISSUE THREAD

**Issue by GitHubUser4234** [nextcloud/android#2046]
Hi,

**Issue**
An encrypted folder has been shared with a user and he can neither access the files in the folder nor upload to it. Maybe the sharing feature is simply not ready yet? 

**Setup**
Client: Android 6.0.1, Nextcloud Android 3.0.0 RC2
Server: Centos 7, PHP 7.0, Nextcloud 13, end_to_end_encryption app 1.0.3

**How to reproduce**
1) UserA creates an encrypted folder with userB
2) UserA uploads a file to the encrypted folder
3) UserA shares the encrypted folder with userB with all permissions available through webUI
4) UserB accesses the shared folder. The file names he sees are scrambled (a mix of numbers and lower case letters) and when he clicks to download a file, error with title "Download failed" and message "The file is no longer available on the server" appears
5) UserA uploads another file to the encrypted folder
6) UserB accesses the shared folder. Since step 5) it oddly appears empty now
7) UserB tries to upload a file to the shared folder, but upload fails

Thanks 😃

**Comment by tobiasKaminsky** [comment]
Sharing is not implemented yet, it will be in Milestone 2.
How did you managed it to share the folder on web ui?
With latest "encryption app" on server it is not possible to share an encrypted folder.
@schiessle

**Comment by Kha13d** [comment]
Any updates about this feature?

**Comment by mario** [comment]
@Kha13d once there's news, we'll update the issue.
