### ISSUE TITLE
Autoupload only works for image file types

### ISSUE THREAD

**Issue by ncuser70** [nextcloud/android#2049]
### Actual behaviour
Non-image files in a monitored folder are not autouploaded to InstantUpload folders on the server.This has been the case since v2.0.0. Expert mode force rescan doesn't help. Unfortunately logs are not available because the v3 beta client crashes when trying to look at the logs, and the v2 client doesn't generate logs.

The Android client version prior to 2.0.0 would upload all files in a monitored folder, whether image or non-image. It would only allow selecting folders with images in them for autoupload, but at least once selected it would upload all the files in that folder.

### Expected behaviour
All files in an autoupload folder should be uploaded, not just image files.
 
### Steps to reproduce
1. Select folder for autoupload.
2. Add PDF or other non-image file to autoupload folder.
3. File is not uploaded to the server.

### Environment data
Android version: 8.1.0

Device model: Nexus 5X

Stock or customized system: Stock

Nextcloud app version: 3.0.0 RC2

Nextcloud server version: 12.0.3

#### Web server error log

Webserver logs are not useful because the Android client doesn't try to upload non-image files.

**Comment by mario** [comment]
You can enable expert mode in settings, and set up a custom folder in auto upload to achieve this functionality.

**Comment by ncuser70** [comment]
Ouch. This isn't obvious - me and my spouse went months (since Oct. 2017) assuming that everything on the phone in the monitored folders was being backed up. Apologies for not reading through the documentation, assuming that this is mentioned in the docs. Maybe it would be helpful to mention this in the client itself.

**Comment by ncuser70** [comment]
PS - thank you for responding with the solution. I will try it out.
