### ISSUE TITLE
I do not see last uploads

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/android#2050]
the beta 3.0.0 rc2 application does not view the latest files uploaded by PC or in general those that are loaded even by forcing the update with the bottom panel

**Comment by chefboyct** [comment]
I have problem with latest 3.0.0 rc2 as well. It seems like auto upload has also stopped working. (pictures for cloud) ... and it also doesnt view the latest files

**Comment by tigernero79** [comment]
at the time I solved by reinstalling nextcloud 2.0 I exited the Beta program from the Play Store and everything works

**Comment by chefboyct** [comment]
@tigernero79  Something is seriously broken. It somehow also broke my google play as none of my apps are updating now (uninstalled the 3.0.0 RC2) and I had to reinstall from F-Droid. It will no longer automatically upload the pictures (I took some pictures with my Sony G8141 and it wouldn't upload) until I open Nextcloud app then they were uploaded. It is Android app dependent as I just upgraded my server to 12.0.5 from 12.0.3 and this problem happened before hands.. I am now running V2.0.1 from F-Droid

**Comment by tobiasKaminsky** [comment]
The storage path was set to a different location on RC1 and this remains on RC2.
So to test this, you would need to remove the app an install it again.

Regarding auto upload we have included a fix in upcoming RC3.

**Comment by tobiasKaminsky** [comment]
Meanwhile we enhanced the app. Can you please try and report back if the bug still exists on latest official version or even try our [dev version](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#dev-release)?

**Comment by tobiasKaminsky** [comment]
No response within the last month, therefore closing.
Please feel free to reopen with additional infos, if the problem still exists.
