### ISSUE TITLE
folder rename on server not visible in the device

### ISSUE THREAD

**Issue by damdamce** [nextcloud/android#2051]
### Actual behaviour
- the renamed folder is not available on the device. I.e. if I swipe down in the parent folder, there is no update. The view still shows the old folder.
- the rename is visible in the activities view.
- after clearing the cache in settings -> application the rename was visible.

### Expected behaviour
- the rename should be mirrored to the device, either automatically or at least when I reload (swipe down)
 
### Steps to reproduce
1. Go to a folder with several subfolders on the device
2. Rename one of the subfolders on the server (for instance via web browser)
3. Try to reload (swipe down) on the device

### Environment data
Android version: 8.0.0

Device model: Nokia 8

Stock or customized system: stock

Nextcloud app version: 3.0.0 RC 2

Nextcloud server version:
12.0.5
#### Web server error log
```
9023 times (only today, this might be another bug, but i'm unsure where to report? server or app? I couldn't log in until i deleted the account via settings -> accounts):
{"reqId":"XXXXXX@XXXXXX","level":2,"time":"2018-01-26T00:22:06+00:00","remoteAddr":"ipv4address","user":"--","app":"no app in context","method":"GET","url":"\/status.php","message":"Temporary directory \/www\/htdocs\/w888888\/cloud.mydomain.at\/tmp\/ is not present or writable","userAgent":"Mozilla\/5.0 (Android) Nextcloud-android\/3.0.0 RC2","version":"12.0.4.3"}

48 times:
{"reqId":"XXXXXX@XXXXXX","level":3,"time":"2018-01-26T16:07:51+00:00","remoteAddr":"ipv4addre","user":"--","app":"PHP","method":"GET","url":"\/cron.php","message":"opendir(\/tmp): failed to open dir: Permission denied at \/www\/htdocs\/w888888\/cloud.mydomain.at\/lib\/private\/TempManager.php#189","userAgent":"Hmd global TA-1004","version":"12.0.4.3"}

(Hmd global TA-1004 is my phone)

besides that some messages from an update i did today (filtered away via grep -v "\"app\":\"updater\"") and other unrelated stuff

```

#### Nextcloud log (data/nextcloud.log)
```
Couldn't find it, i searched my device for nextcloud.log using total commander.
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Thank you for your bug report, this is fixed via #2048 and will be in next dev/RC3.

**Comment by damdamce** [comment]
Ok, cool.

Do you know something about those 9k log entries? It really doesn't look normal to me and I noticed that there is a tmp directory in the nextcloud folder on the phone..

**Comment by tobiasKaminsky** [comment]
This seems to be a server issue:
> Temporary directory \/www\/htdocs\/w888888\/cloud.mydomain.at\/tmp\/

Maybe some problem of your webspace hoster? Or out of space?

**Comment by damdamce** [comment]
right.
so i think the server wanted to cache something in a tmp directory. The function resolved to "/www/htdocs/w888888/cloud.mydomain.at/tmp/", where "/www/htdocs/w888888/cloud.mydomain.at/" is the installation direcotry of nextcloud.

I added the directory manually and now it works (I'll report a bug to nextcloud, because it should be created automatically).

The question remains why there are 9k log entries.
"GET","url":"\/status.php" "userAgent":"Mozilla\/5.0 (Android) Nextcloud-android\/3.0.0 RC2"

so I suspect that the android client is asking very often for the status.php (like 20 times in 3 seconds often). Should i report that as a bug? I mean, it might produce unnecessary traffic, battery drain and it might be the symptom of a more profound bug.

**Comment by tobiasKaminsky** [comment]
> so I suspect that the android client is asking very often for the status.php (like 20 times in 3 seconds often). Should i report that as a bug?

Yes, please a different issue 👍
