### ISSUE TITLE
Setting up encryption on another device

### ISSUE THREAD

**Issue by Simplimus** [nextcloud/android#2056]
### Actual behaviour
I have a NC 13.0.0 RC2 (now RC3) with the 1.0.2 E2E encryption app. I use it with 2 (already configured) android devices. I signed up for the Beta and both devices got updated to the 3.0.0 RC2 android clients.

On devce A I set a folder as encrypted, it showed me the 12 words passcode. I checked on the server and everything is encoded. Fine.

On device B I checked and the folder is shown as encrypted. I tried to enter that folder and it tells me, it is setting up encryption and creating a new key (obviously false behaviour). It then told me it could not write the key (because there already is one stored on the server?). 
On device B I set a second folder as encrypted. Worked. I tried to enter it, again it tried to set up encryption and write the key.
On device A I entered the encrypted folder and everything looks good.

I tried to manually configure the encryption with my keywords, but I could not find anything.
I uninstalled the nextcloud app on device B and reinstall and configure it. No change.

### Expected behaviour
If the encryption is already set up, I would expect a dialog to enter the keywords (passwords?), or the possibility to deconfigure the encryption and delete all encrypted data (with extra safety, please).
 
### Steps to reproduce
1. Configure encrypted folder on device A
2. Try to access that folder from device B

### Environment data
Android version: 
A/B: 7.0

Device model: 
A: Samsung Galaxy S7 Edge (SM-G935F)
B: Samsung Galaxy Tab S2 (SM-T810)

Stock or customized system:
A: Stock with Root
B: Stock

Nextcloud app version:
A/B: 3.0.0 RC2

Nextcloud server version:
3.0.0 RC2 (now RC3 but no change)

**Comment by rullzer** [comment]
I guess this is the userid vs login name thingy @tobiasKaminsky

**Comment by Simplimus** [comment]
Just a quick followup. It's working in RC3. Thanks.
