### ISSUE TITLE
Upload checkbox with multiple files not clickable

### ISSUE THREAD

**Issue by dugite-code** [nextcloud/android#2061]
### Actual behaviour
Pressing checkbox next to filename, File not selected.

### Expected behaviour
File should be highlighted as selected with checkbox filled. Only works if you click anywhere else on the file name.
 
### Steps to reproduce
1. Press `+` FAB button in folder full of files
2. Press upload icon
3. Empty (and filled) checkboxes are not selectable

### Environment data
Android version: Androis 7.0

Device model: Motorola Force X

Stock or customized system: Stock

Nextcloud app version:  2.0.1

Nextcloud server version: 12.0.5

There is no output from logcat

**Comment by AndyScherzinger** [comment]
Hi @dugite-code thank you for your report. This should be fixed via #1885 and will ship with the next release and is also part of the release candidates and the dev releases.
