### ISSUE TITLE
Auto upload of photos fails

### ISSUE THREAD

**Issue by DagNygren** [nextcloud/android#2065]
### Actual behaviour
-Upload of photos fail. Uploads 1M and then fails with "Unknown error". Tried both the official release and master from today and both have the same problem. Secondly there should be a feature for uploading all the photos in the Camera folder for users just starting using Nextcloud. This obviously after the previous issue is solved :-)

### Expected behaviour
- Photos should upload without issues
 
### Steps to reproduce
1. Install Nextcloud for Android, either from Google Play or from github
2. Take a photo
3. Check the Uploads tab and see it fail. Pressing retry you can see it uploading approx 1M and then
  fal with "Unknown error". BTW. Is there a way to get a REAL informative error message here? "Unknown error" is the most infuriating message you can get...

### Environment data
Android version: 7.1.2

Device model: Nokia 6

Stock or customized system: Stock

Nextcloud app version: 20180127

Nextcloud server version:12.0.5

#### Web server error log
```
Insert your webserver log here
[29/Jan/2018:16:30:26 +0200] "PUT /remote.php/webdav/Nokia_6/Photos//2018/01/IMG_20180129_151701.jpg-chunking-19
63162444-4-0 HTTP/1.1" 400 225 "-" "Mozilla/5.0 (Android) Nextcloud-android/20180127"

#### Nextcloud log (data/nextcloud.log)
{"reqId":"Wm8t0bTOPpGqoW43KZyj5QAAAAI","level":4,"time":"2018-01-29T14:21:05+00:00","remoteAddr":"10.0.0.101","user":"sanna","app":"webdav","method":"PUT","url":"\/remote.php\/webdav\/Nokia_6\/Photos\/\/2018\/01\/IMG_20180129_151701.jpg-chunking-1963162444-4-0","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\BadRequest\",\"Message\":\"expected filesize 1024000 got 0\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/local\\\/owncloud\\\/nextcloud-12.0.4\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(105): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->createFileChunked(Resource id #8)\\n#1 \\\/usr\\\/local\\\/owncloud\\\/nextcloud-12.0.4\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(151): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #8)\\n#2 \\\/usr\\\/local\\\/owncloud\\\/nextcloud-12.0.4\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1096): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('IMG_20180129_15...', Resource id #8)\\n#3 \\\/usr\\\/local\\\/owncloud\\\/nextcloud-12.0.4\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(525): Sabre\\\\DAV\\\\Server->createFile('Nokia_6\\\/Photos\\\/...', Resource id #8, NULL)\\n#4 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/usr\\\/local\\\/owncloud\\\/nextcloud-12.0.4\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#6 \\\/usr\\\/local\\\/owncloud\\\/nextcloud-12.0.4\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#7 \\\/usr\\\/local\\\/owncloud\\\/nextcloud-12.0.4\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/usr\\\/local\\\/owncloud\\\/nextcloud-12.0.4\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(76): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/usr\\\/local\\\/owncloud\\\/nextcloud-12.0.4\\\/remote.php(162): require_once('\\\/usr\\\/local\\\/ownc...')\\n#10 {main}\",\"File\":\"\\\/usr\\\/local\\\/owncloud\\\/nextcloud-12.0.4\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":415}","userAgent":"Mozilla\/5.0 (Android) Nextcloud-android\/20180127","version":"12.0.5.3"}


Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by toniokroeger** [comment]
For me, nothing auto-uploads at all in the Android app 2.0.0. (Contact synchronisation and looking at existing folders does work.)
How can we help you to resolve the problem?

**Comment by mario** [comment]
Try 3.0RC3 :)

**Comment by tobiasKaminsky** [comment]
@DagNygren if it is after 1Mb, it might be related to chunking.

Regarding more infos: you can use logcat.
"unknown error" is the very last thing we show to the user if we really do not know what the problem is...

If you cannot find anything in logcat:
Can you create us a test account and send the credentials to android at nextcloud dot com with a reference to this issue?

**Comment by DagNygren** [comment]
Saw the advice to try 3.0RC3. Is this working better? I was earlier at the "official" Google Play version (2.x I think) and that also had the same issue.... Uploads from my Sailfish phone and from my desktop clients have no issues.
Account created for testing and info emailed to the requested address.

**Comment by DagNygren** [comment]
Ok. Tried 3.0RC3 with the same result. Also noticed that if the phone is simultaneously connected to both 4G and WiFi  and "Upload only on WiFi" is ticked it will not understand that it can upload. Also have a small issue with the otherwise nice Autoupload interface: If you have many folders to upload and for example travel to a country with expensive data roaming you will have a lot of ticking to do to disable or enable 4G upload for all of them. One button that affect them all in one click would be a lot more practical.

**Comment by tobiasKaminsky** [comment]
Regarding the other issues/ideas, please open up new issues here, so we can discuss this better.

**Comment by DagNygren** [comment]
Normal uploads works for me too, that is the strange thing. But thanks for verifying that it is not the server setup at least. Don't understand what could be wrong with the device - It is a very clean unmodified Android...

**Comment by mario** [comment]
@DagNygren we'll add roaming feature to auto upload.

**Comment by DagNygren** [comment]
Thanks Mario. I will appreciate that! If I now only could find the reason why my Nokia 6 Android breaks the uploads at 1 MB...

**Comment by DagNygren** [comment]
Just updated one of the Nokia 6:es to Android v 8.0 Oreo and still seeing the same issue. Any hints on where to start looking. Have even considered downloading the sources+SDK and trying to find the problem myself as I am also programming for living :-)

**Comment by DagNygren** [comment]
Just compared the PUT requests that your test of our server made to the ones of the failing requests of our Nokia:s and found an interesting difference. You PUT looks like this:
`Kaminsky [02/Feb/2018:11:30:41 +0200] "PUT /remote.php/webdav/InstantUpload/Camera/2018/02/20180202_103013.jpg HTTP/1.1" 201 - "-" "Mozilla/5.0 (Android) Nextcloud-android/3.0.0 RC3"`

while the failing ones look like this:
`sanna [11/Feb/2018:12:32:06 +0200] "PUT /remote.php/webdav/Nokia_6/Photos//201/01/IMG_20180129_151701.jpg-chunking-1963162444-4-0 HTTP/1.1" 400 225 "-" "Mozilla/5.0 (Android) Nextcloud-android/20180208"`

Mark the double // right after the save directory! I think this is the reason the server returns status 400.

**Comment by DagNygren** [comment]
Ok. Tested the previous "//" theory by removing it in a RewriteRule on the server and found it to be false.
Made no difference at all... The next difference between the log entries is the use of chunking in my problemcases. Can I disable that chunking?

**Comment by DagNygren** [comment]
Digging deeper into the logs I found that you tested that too :-(

Combination of chunking AND autoupload then??

**Comment by DagNygren** [comment]
Digging deeper into the logs I found that you tested that too :-(

Combination of chunking AND autoupload then??

**Comment by DagNygren** [comment]
Couldn't resist and downloaded the SDK and the latest GIT:s of the project + the nextcloud android library. 

Findings so far:

- Enlarging the CHUNK_SIZE to 10M ( = no chunking) makes everything work...
- Shrinking it to 512 MB still fails as before ( Meaning that we dont have a buffer problem in the phone I guess

I will have a look if I can find the reason why it fails if chunking needed. Any hints?

**Comment by DagNygren** [comment]
**# FOUND IT!**

LIne 54 in android-library/src/com/owncloud/android/lib/resources/files/ChunkedUploadRemoteFileOperation.java sets the HTTP Header 

`private static final String OC_CHUNKED_HEADER = "OC-Chunked";`

While the server looks for a header containing HTTP_OC_CHUNKED to handle the file part as a chunk. The "-" will automatically be translated to "_", but the HTTP at the front will not. Changing the line to:

`private static final String OC_CHUNKED_HEADER = "HTTP-OC-Chunked";`

made everything work as expected :-) Why it worked with some clients is beyond me but can someone please correct this in the source? @tobiasKaminsky

**Comment by mario** [comment]
@DagNygren thanks, you're awesome. https://github.com/nextcloud/android-library/pull/119 :)

**Comment by DagNygren** [comment]
Unfortunately I was too happy with the transfer succeeding here. The "fix" seems to have made the reassembly of the chunks not work at the server side and I ended up with the chunk files instead  of an assembled file.... So: WRONG FIXm don't implement it. I WILL come up with a real one as I am on holiday from Wednesday  evening the rest of the week and don't mind checking this out.Sorry for the fuss!

**Comment by DagNygren** [comment]
Finally found the real reason after tracing the server through the steps. And I am happy to say that it is not the fault of the Nextcloud team - Not the Android guys nor the server guys. The problem was that the chunked upload will use the users <user name>/cache directory for assembling the files and some of the older users had this created with user:group of root:root and were not writable by the Nextcloud server. Don't know why, but they happened to be the Nokia users  which led to all the wrong conclusions - Murphy I guess. This also explains why the test account worked as it was freshly created and had all the right permissions. Hope there is some place where this piece of information can be entered to prevent others from searching as long as I did for the problem. A small note to the server guys: A tiny error message telling about the problem when the file couldn't be created would have saved me a couple of workdays of troubleshooting... Thanks to all for all your help and this ticked can be closed on my behalf!

**Comment by mario** [comment]
👍
