### ISSUE TITLE
getCurrentAccount: use proper Exception instead of @Nullable 

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#2069]
https://github.com/nextcloud/android/blob/6820bf1dba3c65d722e4c0642e10b15f0c8602e5/src/main/java/com/owncloud/android/authentication/AccountUtils.java#L58-L58

Instead we should use a real exception handling. Null checking is not the way it should be, I think.

**Comment by przybylski** [comment]
This is not a null checking, it's informing the caller that the result can be null. Since there can be no account setup on the device this function can return null. This is to help dev and lint to check if someone is doing a explicit check for null value upon retrieving the account.

**Comment by AndyScherzinger** [comment]
I agree with @przybylski 👍
