### ISSUE TITLE
FAB doesn´t use theme color

### ISSUE THREAD

**Issue by splitt3r** [nextcloud/android#2070]
### Actual behaviour
- After switching from files view to shared view and back the FAB doesn´t use the theme colour anymore

### Expected behaviour
- The FAB should be green
 
### Steps to reproduce
1. Switch from files view to shared view
2. Switch back to files view

### Environment data
Android version: 7

Device model: Nexus 6

Stock or customized system: Custom ROM

Nextcloud app version: Dev Version from F-Droid

Nextcloud server version: 13

![theming](https://user-images.githubusercontent.com/1869584/35564276-ec415308-05b9-11e8-91cb-2cd8f8b83953.png)

**Comment by przybylski** [comment]
I just created a pull request which fixes this, but having a deeper look on how files are displayed brought me to some more deeper fundamental issues which I will rise by opening a separate issue.
As for now I can tell that with my changes issue is resolved.
