### ISSUE TITLE
File no longer available on the server

### ISSUE THREAD

**Issue by matty-r** [nextcloud/android#2077]
### Actual behaviour
When opening up the Nextcloud client app, then navigating to a folder which should have 5 files. Out of the five files, only two are shown. One which I had downloaded previously as available offline (Gym Plan 3.0.pdf), and another which I would like to access but can't (Gym Plan 2.0.pdf). When attempting to access or download Gym Plan 2.0.pdf a message is shown "Download Failed. The file is no longer available on the server". This same behaviour is seen through out the app, where only one file is shown, and it's inaccessible. 

### Expected behaviour
All files should be shown in the folder and all should be accessible.

### Steps to reproduce
1. Open client app
2. Navigate to a folder which contains documents
3. Attempt to open a document

### Environment data
Android version: 7.0
Device model: Samsung S6 (SM-G920I)
Stock or customized system: Stock
Nextcloud app version: 3.0.0 RC2
Nextcloud server version: 12.0.3

#### Web server error log
10.0.0.139 - admin [31/Jan/2018:12:03:20 +1000] "PROPFIND /remote.php/webdav/Documents/Gym/ HTTP/1.1" 207 772 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.0.0 RC2"10.0.0.139 - admin [31/Jan/2018:12:03:20 +1000] "PROPFIND /remote.php/webdav/Documents/Gym/ HTTP/1.1" 207 4811 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.0.0 RC2"

10.0.0.139 - admin [31/Jan/2018:12:03:20 +1000] "GET /remote.php/webdav/Documents/Gym/null HTTP/1.1" 404 246 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.0.0 RC2"

10.0.0.139 - admin [31/Jan/2018:12:03:21 +1000] "GET /ocs/v2.php/apps/files_sharing/api/v1/shares?path=%2FDocuments%2FGym%2F&reshares=true&subfiles=true HTTP/1.1" 200 957 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.0.0 RC2"

10.0.0.139 - admin [31/Jan/2018:12:03:21 +1000] "GET /remote.php/webdav/Documents/Gym/null HTTP/1.1" 404 246 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.0.0 RC2"

10.0.0.139 - admin [31/Jan/2018:12:03:28 +1000] "PROPFIND /remote.php/dav/files/admin/ HTTP/1.1" 207 512 "-" "Mozilla/5.0 (Windows) mirall/2.3.3 (build 1) (Nextcloud)"

#### Nextcloud log (data/nextcloud.log)
{"reqId":"redacted","level":0,"time":"2018-01-31T02:03:22+00:00","remoteAddr":"10.0.0.139","user":"admin","app":"webdav","method":"GET","url":"\/remote.php\/webdav\/Documents\/Gym\/null","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotFound\",\"Message\":\"File with name Documents\\\/Gym\\\/null could not be located\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(81): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('Documents\\\/Gym\\\/n...')\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:GET', Array)\\n#4 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(76): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/var\\\/www\\\/html\\\/nextcloud\\\/remote.php(162): require_once('\\\/var\\\/www\\\/html\\\/n...')\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/ObjectTree.php\",\"Line\":173}","userAgent":"Mozilla\/5.0 (Android) Nextcloud-android\/3.0.0 RC2","version":"12.0.3.3"}

### Notes
These files can be downloaded and accessed from the iPhone client app, the desktop client app (Sync), desktop web browser, and the browser on Android.

**Comment by tobiasKaminsky** [comment]
Do you have enabled server side encryption?

**Comment by matty-r** [comment]
Yes. Using the Default encryption module.

**Comment by tobiasKaminsky** [comment]
Then this bug will be fixed with next RC3.

**Comment by tobiasKaminsky** [comment]
Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat
