### ISSUE TITLE
RC3 - auto-upload displayed status and buffering

### ISSUE THREAD

**Issue by timmersr** [nextcloud/android#2082]
### Actual behaviour
-status of the next in line to be uploaded, when temporary disconnected from the charger, indicates “waiting for wifi” when it is actually waiting for charging.
-Also, the app seems to buffer the upload. When taken off the charger, it continues to still upload a couple of photo’s.

### Expected behaviour
-status displayed as “waiting for charging” when it is actually waiting for charging.
-finish current uploading image/video, halt uploading all others until reconnected to charger
 
### Steps to reproduce
1. 
![screenshot](https://user-images.githubusercontent.com/31093459/35635610-0f0cb24c-06af-11e8-9dec-2c1a671557a3.jpg)

![screenshot2](https://user-images.githubusercontent.com/31093459/35636040-3fcf9cd6-06b0-11e8-80f8-a054c7816597.jpg)

2. set to upload only while charging, take multiple pictures and while uploading disconnect charger

### Environment data
Android version: 7.1.1

Device model: Samsung Note8

Stock or customized system: Stock

Nextcloud app version: RC3

Nextcloud server version: 12.0.5

**Comment by mario** [comment]
- Status is correct as in the moment of checking it did have charger connected
- HOWEVER, it would not upload without a charger present

Can you please confirm this?

cc @AndyScherzinger

**Comment by timmersr** [comment]
Don't think so Mario: as wifi is available all the time. 

Then again, difficult for me to say; I'm not reporting on an internal picture status of this function, but on the human-readable status for end-users per picture in the Uploads section.

**Comment by timmersr** [comment]
So to be _clearer_: it would not upload without a charger present, which is correct.
Just the displayed status, the reason the picture is waiting to upload, is incorrect.

**Comment by tobiasKaminsky** [comment]
Strange, according to the code it should not happen that the wrong text is shown.
