### ISSUE TITLE
Persistent Notification needed for the Auto Upload to work

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#2083]
In the forum (German: https://help.nextcloud.com/t/android-app-synchronisiert-nicht-richtig/24218/23) the question has been raised if the persistent notification is necessary for the auto upload to work or if this can:
* be implemented without a persistent notification
* the notification/icon being hidden

@mario do you know if any of these suggestions is possible without destabilizing the auto upload?

**Comment by mario** [comment]
Well, it's not persistent. It just stays there while the upload is happening?

**Comment by tobiasKaminsky** [comment]
On >=8 it is permanent:

![2018-02-02-141203](https://user-images.githubusercontent.com/5836855/35734900-050ca1e2-0823-11e8-9ed5-74a4f990fdc4.png)

**Comment by mario** [comment]
Ah that one. Yup, cannot start service from background in 8+ unless it's persistent/in foreground.

**Comment by allcoolusernamesaregone** [comment]
Then you should go without the service. Any other app can do autoupload without a background service (Dropbox, Google Photos). Having this persistent notification is a show stopper - nogo!
You can't be serious to consider this as a final solution?

**Comment by AndyScherzinger** [comment]
This has already been fixed and is only persistent on Android 8+ when files are marked for "keep available offline" which means they get constantly monitored for server changes.

Other then that this is a open source project so everybody is welcomed to improve a solution plus people are contributing to this project in their spare time so let's be respectful when raising issues, concerns and criticizing a status quo / solution.

**Comment by AndyScherzinger** [comment]
issue has been addressed via #2094 and #2095 thus closing

**Comment by mario** [comment]
Rebuilding the upload system from the ground up to support different type of uploads/downloads is on our agenda. 

We're aware of the solution but are also aware of our time limitations so we have to prioritize. 

Like @AndyScherzinger said, please be respectful of the work of every person that contributes to this project.
