### ISSUE TITLE
RFE Option to also upload old pictures

### ISSUE THREAD

**Issue by DagNygren** [nextcloud/android#2091]
### Actual behaviour
-Pictures taken before you enable auto-upload not uploaded

### Expected behaviour
-Would be nice to have an option to also upload all the pictures in the directory. This for backup purposes when you join Nextcloud already having owned the phone for some time.

**Comment by yassintp** [comment]
I second this, this would be a very useful feature! It would also be useful to "re-scan" a certain directory after you cleared failed uploads from the queue to upload photos that couldn't be uploaded earlier.

**Comment by AndyScherzinger** [comment]
Described in #285 as a future increment to be implemented.

duplicates #285
