### ISSUE TITLE
File transfer with "server unavailable" error when app file directory unavailable

### ISSUE THREAD

**Issue by yassintp** [nextcloud/android#2092]
### Actual behaviour
Any transfer of files - upload (manual or auto upload) or download - fails with a "Server unavailable" error message when the app file directory is unavailable due to the SD card having been changed earlier - which means the SD card directory set in the app was (as an example) "AB12-CD34" while the current SD card was referenced to by the system as "DE56-FG78". 

### Expected behaviour
The app should show an error message like "App directory unavailable, please fix". 
 
### Steps to reproduce
1. Set Nextcloud storage path to the SD card.
2. Remove the SD card and insert another SD card.
3. Try to upload or download any file.

### Environment data
Android version: Android 7.0

Device model: Samsung Galaxy A3 2016 (SM-A310F)

Stock or customized system: Stock ROM

Nextcloud app version: 3.0.0 RC3

Nextcloud server version: 12.0.3

**Comment by tobiasKaminsky** [comment]
@przybylski as you wrote the external storage thing, do you have an idea, how we can detect this easily? And what do we want to do? Notify the user and redirect him to the preferences?
