### ISSUE TITLE
Auto uploads 'Waiting for Wi-Fi' when connected to VPN over Wi-Fi

### ISSUE THREAD

**Issue by dan-v** [nextcloud/android#2093]
### Actual behaviour
For auto upload of photos, I have the setting enabled 'Only upload on Wi-Fi' enabled. This option works fine on Wi-Fi without VPN enabled. With VPN enabled, all my uploads sit in the queue with 'Waiting on Wi-Fi'. 

I did a little debugging and built my own APK with additional logging and the call to Device.getNetworkType() is returning NOT_ROAMING. It looks like this decision is made in the android-job library which is making a call to ConnectivityManagerCompat.isActiveNetworkMetered() (https://github.com/evernote/android-job/blob/master/library/src/main/java/com/evernote/android/job/util/Device.java#L107) which is returning true for some reason when connected over VPN. 

This lead me down a path of finding out that Android adheres to a DHCP option that can set the network as metered, so I thought maybe the Wi-Fi network I was connected to was returning this value (although I would expect it to exhibit same behavior without VPN connected). I followed the instructions here (https://stackoverflow.com/questions/23877476/android-why-connectivitymanager-isactivenetworkmetered-always-returning-true#23879816) to explicitly mark my Wi-Fi as unmetered but I still am seeing the same behavior where network type is returning as NOT_ROAMING.

Some additional debug logging I added to UploadFileOperation.java when connected to VPN:
```
02-02 22:17:56.067 12027 12070 I UploadFileOperation: DEBUG: networkInfo.getType(): 1
02-02 22:17:56.577 12027 12070 I UploadFileOperation: DEBUG: networkInfo.getTypeName(): WIFI
02-02 22:17:56.842 12027 12070 I UploadFileOperation: DEBUG: networkInfo.isAvailable(): true
02-02 22:17:57.192 12027 12070 I UploadFileOperation: DEBUG: networkInfo.isConnected(): true
02-02 22:19:54.116 12027 12070 I UploadFileOperation: DEBUG: Device.getNetworkType(mContext): NOT_ROAMING
```

### Expected behaviour
When I'm connected on Wi-Fi, ignore the fact I'm connected to VPN, and upload my photos.
 
### Steps to reproduce
1. Connect to strongSwan VPN
2. Enable 'Only upload on Wi-Fi' option for camera photos
3. Take a photo
4. Photo sits in queue 'Waiting for Wi-fi'

### Environment data
Android version: 8.1

Device model: Pixel XL

Stock or customized system: customized (CopperheadOS)

Nextcloud app version: latest (built from master)

Nextcloud server version: 12.0.5

### Logs
Nothing useful in the server logs

**Comment by spaetz** [comment]
But a VPN connection could be metered, so I am not sure we should simply ignore the fact that we are connected to one...

**Comment by dan-v** [comment]
@mario - yes, I'd be willing to test out an APK.

@spaetz - I'm not sure what the right behavior is here - just voicing how I would want it to work. But if you did go with the approach of ignoring the fact you're on VPN you'd still have the option of forcing the underlying Wi-Fi connection to be metered within Android settings.

**Comment by mr-bolle** [comment]
@mario you can send me the test version as well. Thanks for your help.

**Comment by mario** [comment]
So not sure if this is a bug after thinking about it.Well, to be honest - the settings in auto upload is "Upload on unmetered wifi". When you're on VPN, you don't have unmetered bandwidth...

So not sure if this is a bug after thinking about it.

**Comment by benwaffle** [comment]
>When you're on VPN, you don't have unmetered bandwidth...

That's not true in many cases
