### ISSUE TITLE
Don't start file observer if no files are marked as "Set as available offline"

### ISSUE THREAD

**Issue by mario** [nextcloud/android#2094]
cc @tobiasKaminsky @AndyScherzinger

**Comment by mario** [comment]
This is maybe needed for 3.0.

**Comment by kugel-** [comment]
Is the notification needed at all? AFAIK it's only necessary for foreground services, and I cant imagine why the file observer needs to be a foreground service all the time.

**Comment by mario** [comment]
@kugel- on Android 8 all services started from background need to be started as foreground service.

**Comment by kugel-** [comment]
I understand that background services can still be started from background. Is that wrong?

> The system allows apps to call Context.startForegroundService() even while the app is in the background. However, the app must call that service's startForeground() method within five seconds after the service is created.

Why Context.startForegroundService() at all needed for a file observer?

Anyway, I don't use offline availability at the moment, so it would help already if #2095 could be merged, as the notification is really annoying.

**Comment by mario** [comment]
Because startService doesn't work in a background from where File Observer service is started on Android 8.

**Comment by mase76** [comment]
Is the file observer needed at all? I think, a configurable frequent check for changes would be enough and more battery friendly. That is how davdroid does.

**Comment by Caesar2011** [comment]
I use a Google Pixel 2 with Android 8 Oreo since December and Auto-Upload and Offline Files always worked with background tasks. In my point of view the observer is not needed. To make sure it really work I would change it to use the official Android sync mecanism like DavDroid and other apps does as @mase76 suggested.

**Comment by mikeymop** [comment]
I would be happy with an option to disable this in the app.
I dont mind the notification if I actually used the feature. However, I do not use auto upload and dont wish to as long as there is a persistent notification present.

**Comment by mario** [comment]
You can disable notification channel for it in the app settings of your phone.

**Comment by mikeymop** [comment]
I know that I can do this, however it does not stop the issue of nextcloud
now wanting to be a foreground service all the time.

I would rather an option to disable the service.

**Comment by mario** [comment]
We'll eventually replace the service with jobs-based infrastructure, but I can't say when. It all depends on when one of us gets the time or a contributor jumps in.

**Comment by mikeymop** [comment]
For brevity, can you point me to the applicable classes? I'll try to take a
shot at it

**Comment by mase76** [comment]
Disabling the notification in Oreo leads to another notification, that the app takes battery.

**Comment by mario** [comment]
Well I can point you to the file observer service @mikeymop :)

https://github.com/nextcloud/android/blob/8a5a6ce9b0f069e5e46d5fdea2cca990dbdb919a/src/main/java/com/owncloud/android/services/observer/FileObserverService.java

**Comment by Caesar2011** [comment]
@mase76 I have the same issue on Oreo. You have to force stop the app, auto-upload still works for me after that. Workaround, but not a solution.
