### ISSUE TITLE
App crashes when opening a folder with images that the server fails to generate a preview for

### ISSUE THREAD

**Issue by alexhorn** [nextcloud/android#2096]
### Actual behaviour
App crashes sometimes when opening a folder with images that the server fails to generate a preview for.

### Expected behaviour
App should open the folder without crashing.
 
### Steps to reproduce
1. Set up NextCloud server with low memory limit
2. Upload big image
3. Open folder with big image in app

### Environment data
Android version: 7.0

Device model: Samsung Galaxy S6 SM-G920F

Stock or customized system: Stock

Nextcloud app version: 2.0.0

Nextcloud server version: 12.0.4snap2

### Stacktrace
![screenshot_20180203-011939](https://user-images.githubusercontent.com/13948008/35766071-f13568bc-08d0-11e8-984e-092a42314681.png)

#### Nextcloud log (data/nextcloud.log)
```
Allowed memory size of 134217728 bytes exhausted (tried to allocate 12288 bytes) at /snap/nextcloud/4958/htdocs/lib/private/legacy/image.php#477
```

**Comment by tobiasKaminsky** [comment]
Can you create us a test account, put such a big image in it and send the credentials to android at nextcloud dot com with a reference to this issue?
