### ISSUE TITLE
Use log in background image for background in top of sidebar

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/android#210]
In apps like Play Store and Pocket Casts you can see a very nice background image in the header of the sidebar (where you have the account switcher or app name). We should use the clouds background for that:
https://github.com/nextcloud/server/blob/master/core/img/background.jpg

PR to be found here: #213

**Comment by AndyScherzinger** [comment]
Sounds good, I also thought about this. Will do :)

**Comment by AndyScherzinger** [comment]
release with 1.3.0
