### ISSUE TITLE
Cannot login anymore due to gson update

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#2101]
https://github.com/nextcloud/android-library/pull/113/files#diff-5a28d71c16cbd9f1b8d98de930b72b17R56
gives me: 
> com.google.gson.internal.LinkedTreeMap cannot be cast to com.owncloud.android.lib.ocs.ServerResponse

when I try to authenticate against a recent nc master

@przybylski

**Comment by przybylski** [comment]
Sorry https://github.com/nextcloud/android/issues/2101

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky @przybylski https://github.com/nextcloud/android-library/pull/115 has been merged, thanks for the quick fix 👍

**Comment by tobiasKaminsky** [comment]
Tested and it is now working as expected :+1:
