### ISSUE TITLE
White share icon instead of black one

### ISSUE THREAD

**Issue by splitt3r** [nextcloud/android#2102]
### Actual behaviour
- The app shows a white share icon instead of a black one (themed nc instance).

### Expected behaviour
- Should be black just like the other icons

### Steps to reproduce
1. Use green as your nc instances theme colour
2. View a files details

### Environment data
Android version: 7

Device model: Nexus 6

Stock or customized system: Custom ROM

Nextcloud app version: Recent dev version from F-Droid

Nextcloud server version: 13

![white_icon](https://user-images.githubusercontent.com/1869584/35824398-0628d482-0ab3-11e8-97d0-718d51017608.png)

**Comment by AndyScherzinger** [comment]
Nice catch @splitt3r 👍 

cc @tobiasKaminsky since you are the theming master :)

**Comment by tobiasKaminsky** [comment]
Thank you @splitt3r, this is fixed now and will be in next dev version.

**Comment by splitt3r** [comment]
Ok, keep up the great work :)
