### ISSUE TITLE
Offline file is reset to cached content during editing.

### ISSUE THREAD

**Issue by rexxmagnus** [nextcloud/android#2122]
### Actual behaviour
While editing a file marked as offline (and saving changes), the file occasionally gets reset to the last synced cached version (or does not update with what was just saved), eradicating any changes made since the last sync.

### Expected behaviour
The file should not get updated until synchronised online, and should be in the state that it was last saved in by the editing program.
 
### Steps to reproduce
1. Open a file that is marked as offline.
2. Make some changes to the file using droidedit and save.
3. Reopen the file from nextcloud (before synchronising). The changes are lost. The file may also  change during editing and force a reload, losing all changes.

### Environment data
Android version:
5.1.1

Device model: 
Google nexus 10, original, also occurs on Blackberry priv with 6.0.1 stock

Stock or customized system:
Stock

Nextcloud app version:
3.0.0

Nextcloud server version:
13

### Logs
Logs and webserver version irrelevant as this is an offline issue.

**Comment by rexxmagnus** [comment]
After further experimentation, it seems that some editors are not actually opening the cached file as referenced and that the _content_ is simply being opened by the editor. When saving, the file then goes into a different location as if saving a new file.

**Comment by rexxmagnus** [comment]
Further testing reveals this does not occur on 2.0.1 and does open the file from the cached location and save changes there.

**Comment by tobiasKaminsky** [comment]
@mario can this be due to the changes to the document provider?

**Comment by rexxmagnus** [comment]
Hi, is there any movement on this bug? I only ask because the last version (v2) of the client with functional offline editing now has been removed from fdroid.

**Comment by rexxmagnus** [comment]
It appears this (critical) bug hasn't yet been fixed and the issue is still present in the new 3.1 release.

Try opening an offline text file (without network access) with DroidEdit and then save the changes. You'll see the file has been saved to some temporary location related to DroidEdit, and not a path associated with the nextcloud client - thus those changes are lost.

Is there a timeline for a fix? I'm having to use the old 2.1 version.

**Comment by mario** [comment]
I don't understand, how is this our problem? If DroidEdit saves the file to another location, wouldn't you call it their problem? xD

**Comment by rexxmagnus** [comment]
It was caused by a change between v2.1 and v3 and the way offline files are stored. I've not been able to open an offline file since, and it strikes me that it ought to work in the most compatible way possible and not down to the editors having to work with the sync service. 
I'm about to check another app to see if that's the case.

**Comment by mario** [comment]
Well the editors decide where they want to save the app, don't they?

**Comment by mario** [comment]
(That being said, you might want to change the storage option to something else in the Settings - might help with your problem).

**Comment by rexxmagnus** [comment]
No, they save to where it was opened from, which was why it used to work. Now, when the file is opened from nextcloud there is no path provided - so it doesn't know where to save it.

**Comment by mario** [comment]
Ah this is probably related to Android version change where we have to use content providers rather than file paths!

We need to support write document/file provider and that's a bit time consuming. If that's indeed it - we'll come to this. We know it's important.

**Comment by mario** [comment]
Thanks for the clarifications.

**Comment by rexxmagnus** [comment]
Thanks, I had a feeling that was the case. I'm not on the latest version of android, so it was a little confusing!

**Comment by rexxmagnus** [comment]
As this issue still isn't resolved with the latest client update (still cannot use a program that doesn't implement content provider in the new way), could someone suggest to me a text editor that _will_ work on Android 6 with this client?

The lack of compatibility with older apps is killing it for me, and I'm still having to stick with the 2.0.1 client, since no apps actually say whether they support the new content provider.

**Comment by rexxmagnus** [comment]
I use KeePassX (and KeePassDroid) for passwords, which mean no exposure of files, but KeePassDroid does suffer from the same caching issues. Unfortunately, I think the only workaround for _that_ particular issue would be for me to use dropbox instead since as far as I know KeePass can't use the content provider.
