### ISSUE TITLE
Automatic Contacts Backup - only first contact reaches desktop?

### ISSUE THREAD

**Issue by kaefert** [nextcloud/android#2124]
### Actual behaviour
I've activated the automatic backup of contacts, and they reach my server fine, but there seems to be something special about the way those backups are uploaded, since when they're downloaded to my linux desktop client (maybe the bug is with that client, not android, but I don't know) only the first contact is contained in the backup file (I checked the sync hidden files option in the desktop client)

On the server though the complete contact backups are there, just the download to the desktop client is wrong
![screenshot from 2018-02-09 09-08-06_anon](https://user-images.githubusercontent.com/1448723/36018147-f4a6b3bc-0d7a-11e8-939c-980ba4ee8df9.png)

### Expected behaviour
The whole backups should reach the desktop client
 
### Steps to reproduce
1.) activate automatic contacts backup on android app
2.) sync to linux desktop client

### Environment data
Android version: 7.0
Device model: LG G6
Stock or customized system: Stock (rooted)
Nextcloud app version: 2.0.1
Nextcloud server version: 12.0.5

### Logs
please tell me if you really need logs (and which ones) because acquiring them is a little bit of work I'd like to skip if it is not required.

**Comment by tobiasKaminsky** [comment]
If the files are correctly shown on web ui, it is not the problem of android.
Can you please then open up an issue on client: https://github.com/nextcloud/client

**Comment by kaefert** [comment]
okey, thanks for the reply and the clear instructions. will do.
