### ISSUE TITLE
Small UI glitch in the share dialog

### ISSUE THREAD

**Issue by splitt3r** [nextcloud/android#2125]
### Actual behaviour
- Very small ui glitch 😀 in the share dialog the list of sharees seems to be not correctly centered above the button.

### Environment data
Android version: 7

Device model: Nexus 6

Stock or customized system: Custom ROM

Nextcloud app version: Dev from F-Droid

Nextcloud server version: 13

![share_alignment](https://user-images.githubusercontent.com/1869584/36018424-fa1a8ec6-0d7b-11e8-9d04-3147e758a317.png)

**Comment by codedsun** [comment]
@tobiasKaminsky I want to work on this issue.

@splitt3r can u explain me more about the issue.

**Comment by splitt3r** [comment]
Hm not much to say ^^. If you have a closer look at the screenshot you will notice that the list of sharees is not 100% correctly aligned above the "Add group or user" button.

**Comment by codedsun** [comment]
![screenshot_20180210-234753-2](https://user-images.githubusercontent.com/20026440/36065183-2f819536-0ebd-11e8-8ec1-f2769b164a03.jpg)
@splitt3r as the language here is unreadable to me . 
I am attaching the ss to it, now tell me where the issue is 

>What I see is that the name test is not aligned as same as Share Documents, is this the issue?

**Comment by splitt3r** [comment]
![alignment](https://user-images.githubusercontent.com/1869584/36065213-031e513e-0e98-11e8-839e-869f63d6d35b.png)

The grey bottom border is wider then the black border 😛

**Comment by codedsun** [comment]
@splitt3r that needed much focus, sorry to ask such question.! Okay I m debugging it, thanks!

**Comment by codedsun** [comment]
@splitt3r debugged! 
![screenshot_20180211-000710](https://user-images.githubusercontent.com/20026440/36065372-b908604e-0ebf-11e8-9417-43e9195ce852.jpg)
