### ISSUE TITLE
[3.0.0][#1651] Office files still opened in read only mode

### ISSUE THREAD

**Issue by Orybon** [nextcloud/android#2126]
### Actual behaviour
- When i open a xlsx file from the application, excel open it in read only mode

### Expected behaviour
- Since #1651 has been merged i tought the issue with read only mode opening was corrected.
 
### Steps to reproduce
1. Open the app
2. Open a xlsx file

### Environment data
Android version: 7.0

Device model: Samsung Galaxy S7

Stock or customized system: Stock

Nextcloud app version: 3.0.0

Nextcloud server version: 12.0.4

#### Web server error log
```
NA?
```

#### Nextcloud log (data/nextcloud.log)
```
NA?
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
pinging @mario and @tobiasKaminsky like mentioned this did work with the merge of #1651 but got reverted back by the storage management PR. And while the discussion in that PR is correct stating that this is actually a Microsoft bug I vote for bringing back #1651 since we can't force MS to fix their apps.

**Comment by mario** [comment]
Can you give me the exact location of the xlsx file? like /storage/0/emulated/whatever or whatever it is?

**Comment by mario** [comment]
also can you please tell me what's your storage location in the settings?

**Comment by Orybon** [comment]
Sure, here are the informations you asked for : 

- storage location : /storage/emulated/0/Android/media/com.nextcloud.client
- file location : /Documents/<here_the_name_of_file>.xlsx

**Comment by mario** [comment]
Hm, this should actually work. @AndyScherzinger  - https://github.com/nextcloud/android/blob/8a5a6ce9b0f069e5e46d5fdea2cca990dbdb919a/src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java#L206

**Comment by Orybon** [comment]
ok, so i tried with a .docx file and it's working fine. I got the problem only with .xlsx files.

**Comment by Orybon** [comment]
ok i found out the source of the issue. The Nextcloud App isn't the problem.

Office Word for android permit to open in write mode any .docx file on my phone without being logged with an Office account.

But in order to open in write mode an excel file (even for saving locally) i must connect to my Office account.

Weird. But it's now working, sorry for the unecessary consumed time on your side.

**Comment by mario** [comment]
👍

**Comment by glen-nicol** [comment]
I'm having this issue. But I'm signed into excel. I can open the file in edit mode if I find it from excel in storage. But its much quicker to go through nextcloud ui. Any tips?

Also, word opens in readonly mode too.
