### ISSUE TITLE
Loading thumbnails from top to bottom // enhancement

### ISSUE THREAD

**Issue by Django3** [nextcloud/android#2127]
It would be nice if the thumbnails would loading always sequential from the top to the bottom. Independent from the sort order. Right now it is sometimes randomly. It is loading a few in the middle, a few at the bottom and so on. This is sometimes annoying if you have a folder with lots of images/files.

Just a improvement proposal! :)

Best regards,
HANNES 

Android version: 7.0
Device model: Huawei Mate 10 Lite
Nextcloud app version: 3.0.0.

**Comment by AndyScherzinger** [comment]
Fixed by #2039 which replaces the list implementation with a recycler view which internally will basically do this right anyways :)
