### ISSUE TITLE
How can I display the 12 word key E2E on android apps?

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/android#2128]
I have two android phones with nextcloud installed on the first access to encrypted folder and not having marked the key on the second mobile with the same account asks me the password to access the same folder?

I do not remember how I can do it? on app ios of a friend of mine there is voice display key would serve a function like that to remember it, or there is a way to get it back or reset it?

**Comment by tobiasKaminsky** [comment]
Currently there is no way, but his will be developed for next version.

**Comment by tobiasKaminsky** [comment]
Android and iOS app are developed differently and therefore it can happen that some features are available at one platform, and not on the other one.
But this will be available in next android version, too.

**Comment by tobiasKaminsky** [comment]
E2E [RFC](https://github.com/nextcloud/end_to_end_encryption_rfc/blob/master/RFC.md) says:
> The mnemonic passphrase can also be shown in the client settings in case the user forgets their mnemonic. Displaying the mnemonic requires the user to enter their PIN/fingerprint again on mobile devices.

PIN/fingerprint is not set up on every device, so I thought to use the nextcloud user password, but with new weblogin flow this is not stored locally anylonger, @rullzer?

@marinofaggiana how do you protect showing the mnemonic?

**Comment by tobiasKaminsky** [comment]
@MorrisJobke @blizzz @rullzer @schiessle 
Do we have a possibility to check with a server call if the entered password is correct? 
With new weblogin flow the "real" password is never stored on android, so we cannot use the stored password to show e2e passphrase...

**Comment by marinofaggiana** [comment]
@tobiasKaminsky sorry for the delay, in iOS I request "obligatory" the figerprint or password code for activate the e2ee and after for read passphrase.

**Comment by MorrisJobke** [comment]
@tobiasKaminsky BTW - I created the @nextcloud/server-triage team ;)

**Comment by MorrisJobke** [comment]
> Do we have a possibility to check with a server call if the entered password is correct?

Reauthenticate against an endpoint without sending the cookies?

**Comment by rullzer** [comment]
Won't work as it most likely does :boom: when you have 2FA enabled.

If I remember correctly you are moving to device credentials anyway right? So maybe just require that?

**Comment by tobiasKaminsky** [comment]
Yeah, maybe using the device credentials is the easiest.
Thanks for your input!

(and thanks @MorrisJobke for the team, it is way easier to user & remember :+1:)

**Comment by tobiasKaminsky** [comment]
This is now in https://github.com/nextcloud/android/pull/2381, but needs #1657, which will not be ready for 3.1 (which we want to do a RC1 tomorrow).
