### ISSUE TITLE
Unable to remove or decrypt e2e encrypted folder under e2e encrypted folder app android

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/android#2129]
I noticed that if I create an e2e encrypted folder from android application and inside it create a folder the application itself makes me exit again crypt folder entry, but it should not be already encrypted by default being a sub folder? and in any case it does not allow me to erase it and I come to say decripta does not decrypt it

**Comment by tobiasKaminsky** [comment]
I guess that I do not fully understand, but I did following:
- create folder "secret"
- "set encryption" on folder "secret"
- uploaded a file into it -> encrypted
- created a folder in it: /secret/subfolder -> does not show lock/encryption symbol, but it is encrypted
- enter subfolder and uploaded a file into it --> encrypted

Deleting an encrypted folder is currently not supported on android.

**Comment by tigernero79** [comment]
with android app, I create folder then the crypto, within this folder and create a new folder, basic the subfolder should already be encrypted right? instead hobancora option crypt folder as a voice. appearance possibility to delete folders encrypted however by app. at the end of the pc, with the nextcloud app
