### ISSUE TITLE
File Observer indicator

### ISSUE THREAD

**Issue by mtompkins** [nextcloud/android#2130]
I think it is a poor choice to have this icon always present on the device, especially without an ability to disable it. This bar should be left for notifications in my view and is arguably the standard for apps.

**Comment by Happyfeet01** [comment]
Under Android 8 I can disable the Notification.

**Comment by tobiasKaminsky** [comment]
We want to change this for the next version.

**Comment by koiulpoi** [comment]
To add to this:

The notification cannot be disabled within the app itself (no option in setting, missing ui).

Within Android, the notification can be disabled. However, on Oreo, this changes to a different persistent message that Nextcloud is "using battery." This notification can also be suppressed, but it is VERY poor ux to have to turn off part of the operating system to make one app work.

For the record, I had no issue with files uploading on previous versions before the constant notification, running on Oreo. I would request the option to turn this off!

I'm frankly ignorant in this regard; why does Google Drive or OneDrive or Dropbox function without a constant notification on Android while Nextcloud needs one?

**Comment by skidelo** [comment]
+1

**Comment by raphaotten** [comment]
+1

**Comment by luiscruz** [comment]
> why does Google Drive or OneDrive or Dropbox function without a constant notification on Android while Nextcloud needs one? 

I'm curious on this one. Any ideas?

**Comment by mario** [comment]
Because they did their implementation differently and we inherited a legacy codebase.

But I've removed this and it will be in the next larger release.

**Comment by tobiasKaminsky** [comment]
PR is #2253
