### ISSUE TITLE
Auto-uploaded files that are moved to app folder are deleted from local storage the next time the folder is viewed in the app

### ISSUE THREAD

**Issue by realaerosol** [nextcloud/android#2131]
exactly the same issue like described in #735 and fixed by @tobiasKaminsky 
### Actual behaviour
After images are taken and auto-uploaded, they are moved to the app folder as expected. However, the next time the folder containing those images are viewed in the Nextcloud app, the images are deleted.

### Expected behaviour
The images should not be deleted and should appear with a green checkmark as with all other locally-available files.

### Steps to reproduce
1. Enable auto upload for e.g. the camera
2. Change "Original file will be..." to "moved to app folder"
3. Take a picture
4. View the upload subfolder of the app folder in a file explorer and notice that the image has been moved there
5. Open the upload folder in the app and notice that the newly-uploaded image has a green checkmark, then see the checkmark is gone and file is deleted in file system
6. View the upload subfolder of the app folder in a file explorer again and notice that the image is gone

## Environment data
Android version:

Device model: 
Redmi 4x

Stock or customized system:
LineageOS

Nextcloud app version: 3.0.0

Nextcloud server version: 13.0.0

**Comment by ironicx** [comment]
I see exactly the same behaviour here.

### Environment data

Android version: 
6.0.1

Device model:
Fairphone 2

Stock or customized system:
Fairphone OS

Nextcloud app version: 
3.0.1 (Fdroid)

Nextcloud server version: 
13.0.0

**Comment by veltsov** [comment]
I see exactly the same behaviour also on my phone. Additional comment: the green mark is visible for a fraction of a second after opening the folder in the application. Then the mark disappears and the file is indeed deleted. I have my photos in the internal phone memory, and tested with the Nextcloud application folder both in the internal memory and on the external SD card. In both cases the behaviour is identical.

Android version: 8.0.0

Device model: Samsung Galaxy S7

Stock or customized system: Stock

Nextcloud app version: 3.2.1 (Fdroid) and 20180811 (Fdroid Nextcloud Dev), both behave identically in this respect

Nextcloud server version: 13.0.5

**Comment by ftoral** [comment]
+2
Same behaviour for me on my phone and another one. 

I've not noticed that the green mark is temporarily visible, could only see the image just moved in the app folder within another Gallery app (Simple Gallery for example) then it seems deleted within seconds/minutes. The Nextcloud app show a thumbnail on my first phone, and the real image on the second one, but none of them have the green mark.

I expected the green mark as soon as i've not deleted the file from the local storage. But in the other hand i wonder the behaviour when my device runs out of storage (my Moto X has no SD extension)... So the current behaviour saddly help me to keep space on my storage ;)

I also noticed when searching for this kind of bug that the issue #2521 describe a similar behaviour

**Environment data** _For phone n°1_
Android version: 6.0
Device model: Motorola Moto X 2nd Gen
Stock or customized system: stock
Nextcloud app version: 3.2.1 (from F-Droid)
Nextcloud server version: 13.0.1

**Environment data** _For phone n°2_
Android version: 7.0
Device model: LG V20
Stock or customized system: stock
Nextcloud app version: 3.2.1 (from F-Droid)
Nextcloud server version: 13.0.1

**Comment by DragonQ** [comment]
I have a similar issue. Files get uploaded (as expected), COPIED to the local app directory (should be moved), but then get deleted when I view them in the Nextcloud app (should not happen).

I'm using Nextcloud 14.3 and app version 3.3.2. I have set "original file will be" to "moved to app folder" for my auto-upload folder.

**Comment by prontog** [comment]
I have the same issues (described by @DragonQ) with 3.4.1 version on Android 7.1.2. Nextcloud server is 15.0.0.

**Comment by tobiasKaminsky** [comment]
I tested this on a vanilla emulator and on a OnePlus3 with LineageOS and on both devices the files remain.
This seems to be some kind of "auto clean up" on your devices.



> If I set "original file will be" to "deleted", the original file does not get deleted either. Basically the setting seems to do nothing.

Are your images on a sdcard? I fear that this storage location is then read-only by our app and thus the original file cannot be mover nor deleted.
This will be "fixed" by showing a warning in next version #3461

**Comment by AndyScherzinger** [comment]
@DragonQ write permission is the user's / operating system choice. So nothing to be done here, while with the next version we actually show this info so the users knows that the SD card is read-only (and needs to change this by themselves)

**Comment by AndyScherzinger** [comment]
> Ah, so SD card being writeable is not a per-application thing? In that case it cannot be the cause of the issues described in this issue thread since I have plenty of apps that can write to the SD card.

the correct answer to your question is actually "both". The app requests the write permission to external storage (e.g. SD cards) but an SD card can also be read-only so the storage permission won't help. So if other apps can write to your SD card and the app has the permission to do so too (you can check that via Android's general/app settings for the Nextcloud app) then this is not the cause of your issue.

**Comment by SebStaeubert** [comment]
Bug confirmed.
Not only videos are affected but photos, too.

Samsung S7, Android 8

Bug: Upload option to move the local file or photo to the application folder does not inform the nexcloud app that the moved file is available local now. As a result the file is moved, but there is no overlay icon (little green checkmark circle) and after accessing the folder in the next nextcloud app, the file is deleted in the local app folder!

**Comment by icasdri** [comment]
I can confirm that this issue still exists :/
Photo is present in app folder when viewing with external file browser after auto-upload, but viewing with Nextcloud app's "On device" file browser causes local deletion (you can see it for a second before it gets removed). Viewing with Nextcloud app's "All files" has similar behavior (you can see it with a green checkmark for second before the checkmark goes away).

Android version: 9
Nextcloud app version: 3.7.0 (F-Droid)
Nextcloud server version: 16.0.3 (Docker)

**Comment by MultiCoreNop** [comment]
newer bug reports of seemingly same Problem: #4220 #4454

**Comment by feutl** [comment]
I tested this, because I had problems with it like mentioned in my [comment](https://github.com/nextcloud/android/issues/4454#issuecomment-537806803) and it worked over the last 7 days without issues.

Even deleting files locally available in the app folder, on another device, removed the files on the device where it was moved to the local app folder correctly.

Device: Samsung S9+
NextcloudClient: 3.9.2
Nextcloud: 16.0.4 and 17.0.1
Android: 9.0

Thanks
