### ISSUE TITLE
E2E: Unsupported class: class javax.crypto.spec.IvParameterSpec when encrypting the private key.

### ISSUE THREAD

**Issue by ardevd** [nextcloud/android#2134]
Using the latest version from Google Play, whenever I try to enable an encrypted folder, the app shows me a new recovery key phrase, and when proceeding I get an error saying "Keys could not be stored, please try again".

This is on a Pixel 2 XL running Android 8.1.0.

**Comment by ardevd** [comment]
02-09 23:12:30.829 28516  3071 D SetupEncryptionDialogFragment: public key successful downloaded for xxx@xxxxx
02-09 23:12:30.831 28516  3071 V ArbitraryDataProvider: Updating arbitrary data with cloud id: xxx@xxxx key: PUBLIC_KEY value: -----BEGIN CERTIFICATE-----
02-09 23:12:30.831 28516  3071 V ArbitraryDataProvider: <REDACTED>
02-09 23:12:30.831 28516  3071 V ArbitraryDataProvider: <REDACTED>
02-09 23:12:30.831 28516  3071 V ArbitraryDataProvider: <REDACTED>
02-09 23:12:30.831 28516  3071 V ArbitraryDataProvider: <REDACTED>
02-09 23:12:30.831 28516  3071 V ArbitraryDataProvider: <REDACTED>
02-09 23:12:30.831 28516  3071 V ArbitraryDataProvider: -----END CERTIFICATE-----
02-09 23:12:30.841 28516  3071 D OwnCloudClient #2: REQUEST GET /ocs/v2.php/apps/end_to_end_encryption/api/v1/private-key

**Comment by ardevd** [comment]
No related log entries on the server side which makes me suspect that the issue resides in the client. I'm assuming it's unable to create/store the keys on the device. Has this been tested with Android 8.1.0?

**Comment by tigernero79** [comment]
Some problem on Samsung s8 Nexus 6 ed Nexus 6p, but ok on smartphone huawei

**Comment by ardevd** [comment]
This is where it fails for me. 

```
RemoteOperationResult result = operation.execute(account, getContext(), true);

                if (result.isSuccess()) {
                    Log_OC.d(TAG, "public key success");

                    publicKey = (String) result.getData().get(0);
                } else {
                    keyResult = KEY_FAILED;
                    return "";
                }
```

operation.execute() is unsuccessful for some reason and hence the AsyncTask returns an empty string. 

Stepping into SendCSROperation shows that the server returns status code 409. I've actually never encountered a 409 error before so I had to look it up. No idea what's causing it though.

**Comment by ardevd** [comment]
Here is the relevant output from the server log.

`{"reqId":"Wn4aTQhHaObiPj@tJX0Q3gAAAAY","level":4,"time":"2018-02-09T22:01:49+00:00","remoteAddr":"10.10.10.20","user":"user","app":"webdav","method":"PROPFIND","url":"\/remote.php\/webdav\/Tmp\/Test","message":"Exception: {\"Exception\":\"OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Exception\\\\Forbidden\",\"Message\":\"client not allowed to access end-to-end encrypted content\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/end_to_end_encryption\\\/lib\\\/Connector\\\/Sabre\\\/LockPlugin.php(124): OCA\\\\EndToEndEncryption\\\\Connector\\\\Sabre\\\\LockPlugin->checkUserAgent('Mozilla\\\/5.0 (X1...', '\\\/Tmp\\\/Test')\\n#1 [internal function]: OCA\\\\EndToEndEncryption\\\\Connector\\\\Sabre\\\\LockPlugin->checkLock(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#4 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(80): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/var\\\/www\\\/html\\\/nextcloud\\\/remote.php(164): require_once('\\\/var\\\/www\\\/html\\\/n...')\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/end_to_end_encryption\\\/lib\\\/Connector\\\/Sabre\\\/LockPlugin.php\",\"Line\":169}","userAgent":"Mozilla\/5.0 (X11; Fedora; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.140 Safari\/537.36","version":"13.0.0.14"}
`

**Comment by ardevd** [comment]
Reading through the E2E app docs the 409 error was caused by the fact that a public key already existed for my user. I deleted it, now the RemoteOperationResult returns 200 OK so now I can finally get to the actual cause of the problem, which is an unsupported KeySpec.

`SetupEncryptionDialogFragment: Unsupported class: class javax.crypto.spec.IvParameterSpec`

This is caused by` EncryptionUtils.encryptPrivateKey(privatePemKeyString, keyPhrase);`

**Comment by tigernero79** [comment]
great, I'm waiting for the solution is new release that fixes the bug. in fact I had another user on s8 and Nexus 6, but on Nexus 6p instead no, but I had an error.

**Comment by ardevd** [comment]
The offending bit of code: `byte[] iv = cipher.getParameters().getParameterSpec(IvParameterSpec.class).getIV();`

I'll see if I can make a PR that fixes this.

**Comment by ardevd** [comment]
PR created. The fix is seemingly pretty simple and works fine on my devices, but they all run Android 8.1.

**Comment by aquaritus** [comment]
Maybe this is only a me too post, but I have the same problem on my Nexus 6P running Android 8.1. Thus I'd like to know if there is a timeline for accepting arddevd PR and releasing a new version of the app fixing this issue?
And of course a big thx for all your research with this problem!

**Comment by tobiasKaminsky** [comment]
As we had a bit of trouble for many users upgrading to 3.0 I somehow missed this.
Thank you @ardevd for the great fix, I have tested it and it is working fine. :tada: 
It will be included in 3.0.1, which will be released today.

**Comment by tigernero79** [comment]
I updated to nextcloud 3.0.1 and yet the problem of archiving Keynn was solved for Nougat? have you solved just for oreo?

**Comment by tigernero79** [comment]
I try to uninstall apps and reinstall, otherwise I try your second method .. I hope anyway in an application in the application as soon as possible. I keep you updated

**Comment by tigernero79** [comment]
I uninstalled and reinstalled but the problem persists. I have my nextcloud hosted on Aruba and I do not have access to the Shell how to fix?

**Comment by ardevd** [comment]
You don't need shell access. You can curl from your local machine. Just pass the hostname for your NextCloud server to it.

```
curl -X DELETE https://<user>:<password>@<nextcloud.myserver.com>/ocs/v2.php/apps/end_to_end_encryption/api/v1/private-key -H "OCS-APIRequest:true"

`curl -X DELETE https://<user>:<password>@<nextcloud.myserver.com>/ocs/v2.php/apps/end_to_end_encryption/api/v1/public-key -H "OCS-APIRequest:true"
```

Replacing <user>, <password> and <nextcloud.myserver.com> with their correct values.

**Comment by tigernero79** [comment]
suppose my user is called "Ti@er"
and suppose my password is "pallino"

and suppose my nextcloud is

https://www.pensierando.it/Nextcloud

which command to curl where to write in a linux terminal because it happens?

I receive error

curl: (3) Illegal port number

**Comment by ardevd** [comment]
Hmm, your username really has an @ in it? Damn, that must be screwing things up for you!

Say your username was "bob" and the password was "SuperSecretPass" the command would be

Your command would be:

`curl -X DELETE https://bob:SuperSecretPass@www.pensierando.it/Nextcloud/ocs/v2.php/apps/end_to_end_encryption/api/v1/private-key -H "OCS-APIRequest:true"`

**Comment by ardevd** [comment]
Try this? 

`curl -X DELETE https://"Ti@er":SuperSecretPass@www.pensierando.it/Nextcloud/ocs/v2.php/apps/end_to_end_encryption/api/v1/private-key -H "OCS-APIRequest:true"`

I'll be honest, I have no idea if that will work ^^

**Comment by tigernero79** [comment]
also tried with the tips "Ti @ er" even my password has the "@@"

but always error curl: (3) Illegal port number

**Comment by tobiasKaminsky** [comment]
curl supports -u to specifcy user/password, so maybe try:
curl -u "Ti@er:SuperSecretPass" -X DELETE https://www.pensierando.it/Nextcloud/ocs/v2.php/apps/end_to_end_encryption/api/v1/private-key -H "OCS-APIRequest:true"

**Comment by tigernero79** [comment]
view?
![immagine](https://user-images.githubusercontent.com/35575744/36211452-8dd8b84e-11a1-11e8-8e56-a381dfa6746a.png)

**Comment by ardevd** [comment]
@tigernero79 use the suggestion from @tobiasKaminsky 

`curl -u "Ti@er:SuperSecretPass" -X DELETE https://www.pensierando.it/Nextcloud/ocs/v2.php/apps/end_to_end_encryption/api/v1/private-key -H "OCS-APIRequest:true"`

**Comment by tigernero79** [comment]
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>failure</status>
  <statuscode>404</statuscode>
  <message>Impossibile trovare la chiave privata che appartiene all'utente Ti@er</message>
 </meta>
 <data/>
</ocs>

**Comment by ardevd** [comment]
Ok, good. No stale private key. Now do:

`curl -u "Ti@er:SuperSecretPass" -X DELETE https://www.pensierando.it/Nextcloud/ocs/v2.php/apps/end_to_end_encryption/api/v1/public-key -H "OCS-APIRequest:true"`

**Comment by tigernero79** [comment]
ok

![immagine](https://user-images.githubusercontent.com/35575744/36211774-7f9291e6-11a2-11e8-8e73-1997e2b218b8.png)

**Comment by ardevd** [comment]
Ok, doesnt seem like there was any stale public keys either. I'm beginning to suspect you're experiencing a different issue here. 

Whats the output of the following command?

`curl -u "Ti@er:SuperSecretPass" -X GET https://www.pensierando.it/Nextcloud/ocs/v2.php/apps/end_to_end_encryption/api/v1/public-key -H "OCS-APIRequest:true"`

**Comment by tigernero79** [comment]
![screenshot_20180214-162821 2](https://user-images.githubusercontent.com/35575744/36212488-5d481bae-11a4-11e8-976e-e8115dfad04b.png)

**Comment by ardevd** [comment]
And if you now run the Android app it still doesnt work?

**Comment by tigernero79** [comment]
exact it does not work for me. I tried both with Samsung s8 and with Nexus 6 both have Nougat. I tried as well with another nextcloud domain I have. same problem

**Comment by tigernero79** [comment]
with my wife Huawei's cell phone on both my nextcloud domains it worked right away. I have also deleted my Tiger user and Created Ti @ er thinking about Key problems but as you also see Tiger from the same problem

**Comment by tigernero79** [comment]
if you want to create test user to you on my nextcloud and try it too? if you have a Nexus 6 or s8? with Huawei it worked

**Comment by tigernero79** [comment]
![screenshot_20180214-165613](https://user-images.githubusercontent.com/35575744/36213928-441cc752-11a8-11e8-8bc0-5ef3b217e52b.png)
![screenshot_20180214-165631](https://user-images.githubusercontent.com/35575744/36213929-4430608c-11a8-11e8-9467-14557b367b99.png)

As you see the key is generated but then it is not saved

**Comment by ardevd** [comment]
So you're saying it works with your wife's Huawei using the same Nextcloud account as you're trying to use on your device?

**Comment by tigernero79** [comment]
no, with my wife's account works, same domain, also tested with nexus 6p my brother's account has oreo and it also works.

**Comment by ardevd** [comment]
Can you try your wife's account with your phone then? We have to figure out if the problem here is with your account (in which case you should start a new issue as your problem is unrelated to the bug described here).

**Comment by tigernero79** [comment]
ok I try to configure it with my wife's account give me a minute

**Comment by tigernero79** [comment]
then on my phone with my wife's account is gone, what does this mean? mystery of faith.
being an administrator I create a new account and I'll try .. but that's strange.

**Comment by tigernero79** [comment]
I'm doing some tests, but I think if one has some special character in the password like the "@" app, it has problems storing it ...

**Comment by tigernero79** [comment]
creating Tiger accounts and not everything went well, I believe that users with special characters are not managed well

**Comment by tobiasKaminsky** [comment]
@tigernero79 which special chars do you use? And where, in user or pass or both?

**Comment by tigernero79** [comment]
Both @ and #

**Comment by ConorIA** [comment]
Just thought I'd chip in here. I'm also experiencing issues trying to create keys for my admin account. 

```
~ >>> curl -u "user(no special chars):password(with special chars)" -X GET https://my_server/ocs/v2.php/apps/end_to_end_encryption/api/v1/public-key -H "OCS-APIRequest:true" 
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>failure</status>
  <statuscode>404</statuscode>
  <message>Could not find the public key belonging to the user user</message>
 </meta>
 <data/>
</ocs>
```
