### ISSUE TITLE
[Feature Request] Add auto upload for folders contaning files also

### ISSUE THREAD

**Issue by HorribleGeek** [nextcloud/android#2136]
### Actual behaviour
- Auto-Upload works only for Photos!

### Expected behaviour
- Auto-Uploads should be for folders with files (txt or any extension) also

Maybe add an option below to select auto upload folder.
 
### Steps to reproduce
1. Go to Auto-Uploads in NextCloud Android

### Environment data
Android version: Any

Device model: Any

Stock or customized system: Any

Nextcloud app version: v3

Nextcloud server version: ;/ Latest

**Comment by mario** [comment]
Already available, enable expert mode in settings

**Comment by HorribleGeek** [comment]
Oh! I didn't see that, Thank You!
