### ISSUE TITLE
Unable to connect after server settings were changed

### ISSUE THREAD

**Issue by savin-msk** [nextcloud/android#2139]
### Actual behaviour
I change port number on my server. After that android app can't connect and stuck. there is no possibility to change connection string.

### Expected behaviour

I would like to have ability to change connection string.

 
### Steps to reproduce
1.  Change server's port
2.  Try to connect with existing account.

### Environment data
Android version:
7.0, 7.1

Device model: 
Xiami Mi Note 3, SGS7

Stock or customized system:

Stock

Nextcloud app version:
3.0

Nextcloud server version:
13.0

**Comment by tobiasKaminsky** [comment]
If you want to change the address you have to setup a new account and delete the old one.
As far as I remember this was introduced as a security enhancements back in the old days, so that no one can simply change the server address.
