### ISSUE TITLE
Waiting for Wi-Fi // bug

### ISSUE THREAD

**Issue by Django3** [nextcloud/android#2140]
Hello,

my phone is connected to the wifi (with working Internet) but the auto upload is not working cause it is always writing "Waiting for Wi-Fi".

![inkedinkedscreenshot_20180210-214615_li](https://user-images.githubusercontent.com/33788078/36066638-a9164c30-0ead-11e8-8773-aee443196ec4.jpg)

Best regards,
HANNES

Android version: 7.0 (Nougat)
Device model: Huawei Mate 10 Lite
Nextcloud app version: 3.0.0.

**Comment by eleith** [comment]
I'm seeing this bug on Android 8 as well

**Comment by eleith** [comment]
actually, this bug seems to be the culprit for me, not sure about the OP.

https://github.com/nextcloud/android/issues/2093

**Comment by mario** [comment]
@Django3 do you use vpn too?

**Comment by user23498723452** [comment]
I've seen this issue on Android 8.1 Google Pixel.  I do not use VPN.  Reconnecting to wifi fixes the issue from what I've seen.  I do toggle wifi on/off during the day.

**Comment by DagNygren** [comment]
Seeing this on 3.0.0RC3 as well. VPN or not doesn't matter. The setting on autoupload was WiFi only when some photos were qued. Now these are stuck in the que seemingly forever. Turnig WiFI on/off doesn't work. Turning phone off/on doesn't work. Turning off 4G doesn't work. It just doesn't seem to pick up the changed status..I see that the bug report is closed. Does this mean that the issue is fixed?

**Comment by AndyScherzinger** [comment]
@DagNygren can you please update to 3.0.1 to check if the issue persists

**Comment by DagNygren** [comment]
Did that now. No difference in behaviour..

**Comment by DagNygren** [comment]
The exact chain of events that triggered the problem was:
Set up to download only on WiFi
Go out and take a photo where there is no WiFi
Go back in and activate the WiFi connection and you still see the uploads queued in "Waiting for WiFi" state

**Comment by DagNygren** [comment]
Ok. Used the source ("Use the source, Luke!" and found that the upload on WiFi setting is not really an "Upload on WiFi" .... What it actually says is "Upload on unmetered networks only" . And as this is something you can turn on and off also on WiFi (in settings for Data Usage) it just happened to be in the On position for our internal network for some reason. Turning that setting off made the autouploads work. So now there is two options: 

- Change the text in the settings for the app as uploading on unmetered only actually makes a lot of sense. But I do hope that a 3G or 4G connection is automatically entered without the unmetered flag in Android.

or:

- Change the test to WiFi to actually test for WiFi

I will leave it up to the dev:s to make the decision on this, but please do some change to avoid confusion in the future!

**Comment by tobiasKaminsky** [comment]
Thanks for your help in debugging this! :tada: 

I also think that we should change the name to "upload on unmetered wifi only".
Allowing the app to upload on any wifi is not a good idea.

@mario?

**Comment by DagNygren** [comment]
No problem.Glad I could help a bit. Thanks to you guys for creating this and  using Open Source - It makes debugging sooo much easier :-)
