### ISSUE TITLE
Wrong time display in activity time

### ISSUE THREAD

**Issue by quentinus95** [nextcloud/android#2141]
In the Activities tab of the app, it looks like there was a confusion between minutes and monthes (e.g. 18:02 is displayed instead of 18:53 because we are in february).

**Comment by xXSTrikeXx** [comment]
Is your servertime correct?

**Comment by quentinus95** [comment]
Yes.

As I stated in my first message, minutes are replaced by the month number. If I scroll down a lot, I will find some 18:01 (for instance) and then 13:12 (for example).

I know that date formatting in PHP uses `m` for monthes and `i` for minutes. Maybe it is the same in Java and there was a confusion here.

**Comment by quentinus95** [comment]
Or maybe the issue comes from the PHP consumed API.

**Comment by AndyScherzinger** [comment]
I reproduced it and will open a PR within the next hour.

**Comment by AndyScherzinger** [comment]
PR is #2146

**Comment by AndyScherzinger** [comment]
Will be released with 3.1
