### ISSUE TITLE
Not uploading many files

### ISSUE THREAD

**Issue by memen45** [nextcloud/android#2142]
### Actual behaviour
Nothing (not even error message in the app, nor errors in the server logs) 

### Expected behaviour
Upload the selected files
 
### Steps to reproduce
1. Choose "upload" in a folder in the app
2. Select the files to upload - using select all (tested on around 2400 jpg files at the same time) 
3. Choose "upload" to start upload

### Environment data
Android version: Android 6.0

Device model: H60-L04

Stock or customized system: EMUI 4

Nextcloud app version: 3.0.0 (release from play store) 

Nextcloud server version: 12.0.5

**Comment by xXSTrikeXx** [comment]
Huawei got a "ignore optimization list", which apps shouldn't be optimized for a good akku experience. So mabye the system had closed the app and caused a break while uploading. Huawei is something special. :D
Could you please check your

**Comment by memen45** [comment]
I am aware of this setting, however I never navigate away from the app, nor close my phone. If I select only one file, it uploads correctly including immediate notifications as 'uploading' and 'uploaded' as normal. However, with this many files, there isn't a single notification or anything. Just seems to be ignored.

**Comment by tobiasKaminsky** [comment]
Here we put the paths in an intent:
https://github.com/nextcloud/android/blob/60fae3c50247c1d3f9fad9b9b27d596c1f31d539/src/main/java/com/owncloud/android/ui/activity/UploadFilesActivity.java#L514-L531

**Comment by tobiasKaminsky** [comment]
This is then a different bug @PakhomGolynga.
The one we are talking about here is, that after selecting many many files and clicking upload, nothing happens.

Please open up a new issue for your bug.

**Comment by PakhomGolynga** [comment]
@tobiasKaminsky , I found a similar problem with my issue #369.
