### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by duesteap** [nextcloud/android#2143]
### Actual behaviour
When I attempt to login on my Samsung Galaxy S7 it says the username and password are incorrect.

### Expected behaviour
I should input my username and password and be granted access to nextcloud.
 
### Steps to reproduce
1. Enter username
2. Enter password
3. Click submit

### Environment data
Android version: 7.0

Device model: Samsung Galaxy S7

Stock or customized system: stock..I do use Nova for the skin

Nextcloud app version: not sure

Nextcloud server version: 13.0.0

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by xXSTrikeXx** [comment]
Already exist at  #2131 &  #2147
