### ISSUE TITLE
Fix push by deleting keys & registrations and regenerating them

### ISSUE THREAD

**Issue by mario** [nextcloud/android#2145]
Unfortunately the user agent change had a significant impact on the push infrastructure, so I'd suggest we do this for 3.0.1 if you all agree?

I ca

**Comment by AndyScherzinger** [comment]
👍 sounds good to me, cc @tobiasKaminsky

**Comment by tobiasKaminsky** [comment]
You mean the version number in the user agent? As the user agent itself should remain the same (unless for E2E calls).
Fixing it in 3.0.1 would be nice.

**Comment by tobiasKaminsky** [comment]
You can just create a fix for master and I'll do the backport stuff for 3.0.1 to save you time ;-)

**Comment by mario** [comment]
No, version number shouldn't impact it. I didn't yet checK HOW, but it looks like push requests were set to Nextcloud-Android.

**Comment by mario** [comment]
I'll gladly fix this part, but would appreciate if you could check HOW it could happen in the first place since E2E is your domain :)
