### ISSUE TITLE
File explorer notification always on

### ISSUE THREAD

**Issue by moulip** [nextcloud/android#2151]
Hi,

Since the upgrade to V3, I have a constant notification from the app. It says File explorer looking for file changes.
I have to kill the app to make the notification disappear.
![screen](https://user-images.githubusercontent.com/805421/36098348-edaf24dc-0ffe-11e8-86c1-c3d838e4363c.jpg)

**Comment by mario** [comment]
I assume you run 8.x. This is expected if you have marked as "Set as available offline". 
So while it's not that nice, it's not really a bug.
