### ISSUE TITLE
Picture auto-upload seems to succeed but in the end it failed

### ISSUE THREAD

**Issue by jhf2442** [nextcloud/android#2152]
### Actual behaviour
- take a new picture on mobile phone
- auto-upload starts
- auto upload ends
- nothing at all on server

### Expected behaviour
-picture uploaded
 
### Steps to reproduce
1. 
2. 
3. 

### Environment data
Android version: 7.0

Device model: Galaxy S6 (SM-G925F)

Stock or customized system: Stock

Nextcloud app version: 3.0.0

Nextcloud server version: 12.0.4

#### Web server error log

%MY_IP% - %MY_USER% [12/Feb/2018:18:50:17 +0100] "HEAD /remote.php/webdav/InstantUpload/Camera/2018/02/ HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.0.0"
%MY_IP% - %MY_USER% [12/Feb/2018:18:50:18 +0100] "GET /status.php HTTP/1.1" 200 157 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.0.0"
%MY_IP% - %MY_USER% [12/Feb/2018:18:50:24 +0100] "PUT /remote.php/webdav/InstantUpload/Camera//2018/02/20180212_172714.jpg-chunking-924028200-4-0 HTTP/1.1" 200 4334 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.0.0"
%MY_IP% - %MY_USER% [12/Feb/2018:18:50:34 +0100] "PUT /remote.php/webdav/InstantUpload/Camera//2018/02/20180212_172714.jpg-chunking-924028200-4-1 HTTP/1.1" 200 4334 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.0.0"
%MY_IP% - %MY_USER% [12/Feb/2018:18:50:43 +0100] "PUT /remote.php/webdav/InstantUpload/Camera//2018/02/20180212_172714.jpg-chunking-924028200-4-2 HTTP/1.1" 200 4328 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.0.0"
%MY_IP% - %MY_USER% [12/Feb/2018:18:50:45 +0100] "PUT /remote.php/webdav/InstantUpload/Camera//2018/02/20180212_172714.jpg-chunking-924028200-4-3 HTTP/1.1" 200 4334 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.0.0"
%MY_IP% - %MY_USER% [12/Feb/2018:18:50:46 +0100] "PROPFIND /remote.php/webdav/InstantUpload/Camera//2018/02/20180212_172714.jpg HTTP/1.1" 200 4328 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.0.0"
%MY_IP% - %MY_USER% [12/Feb/2018:18:50:47 +0100] "HEAD /remote.php/webdav/InstantUpload/Camera/2018/02/ HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.0.0"
%MY_IP% - %MY_USER% [12/Feb/2018:18:50:47 +0100] "GET /index.php/apps/files/api/v1/thumbnail/512/512/InstantUpload/Camera//2018/02/20180212_172714.jpg HTTP/1.1" 200 4328 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.0.0"
%MY_IP% - %MY_USER% [12/Feb/2018:18:50:47 +0100] "GET /status.php HTTP/1.1" 200 157 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.0.0"
%MY_IP% - %MY_USER% [12/Feb/2018:18:51:00 +0100] "PUT /remote.php/webdav/InstantUpload/Camera//2018/02/20180212_172657.jpg-chunking-1694244714-4-0 HTTP/1.1" 200 4328 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.0.0"
%MY_IP% - %MY_USER% [12/Feb/2018:18:51:06 +0100] "PUT /remote.php/webdav/InstantUpload/Camera//2018/02/20180212_172657.jpg-chunking-1694244714-4-1 HTTP/1.1" 200 4334 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.0.0"
%MY_IP% - %MY_USER% [12/Feb/2018:18:51:14 +0100] "PUT /remote.php/webdav/InstantUpload/Camera//2018/02/20180212_172657.jpg-chunking-1694244714-4-2 HTTP/1.1" 200 4334 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.0.0"
%MY_IP% - %MY_USER% [12/Feb/2018:18:51:15 +0100] "PUT /remote.php/webdav/InstantUpload/Camera//2018/02/20180212_172657.jpg-chunking-1694244714-4-3 HTTP/1.1" 200 4328 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.0.0"
%MY_IP% - %MY_USER% [12/Feb/2018:18:51:16 +0100] "PROPFIND /remote.php/webdav/InstantUpload/Camera//2018/02/20180212_172657.jpg HTTP/1.1" 200 4328 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.0.0"
%MY_IP% - %MY_USER% [12/Feb/2018:18:51:18 +0100] "HEAD /remote.php/webdav/InstantUpload/Camera/2018/02/ HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.0.0"
%MY_IP% - %MY_USER% [12/Feb/2018:18:51:18 +0100] "GET /index.php/apps/files/api/v1/thumbnail/512/512/InstantUpload/Camera//2018/02/20180212_172657.jpg HTTP/1.1" 200 4328 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.0.0"
%MY_IP% - %MY_USER% [12/Feb/2018:18:51:18 +0100] "GET /status.php HTTP/1.1" 200 157 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.0.0"
%MY_IP% - %MY_USER% [12/Feb/2018:18:51:25 +0100] "PUT /remote.php/webdav/InstantUpload/Camera//2018/02/20180212_165152.jpg-chunking-899504744-5-0 HTTP/1.1" 200 4334 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.0.0"
%MY_IP% - %MY_USER% [12/Feb/2018:18:51:31 +0100] "PUT /remote.php/webdav/InstantUpload/Camera//2018/02/20180212_165152.jpg-chunking-899504744-5-1 HTTP/1.1" 200 4334 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.0.0"
%MY_IP% - %MY_USER% [12/Feb/2018:18:51:36 +0100] "PUT /remote.php/webdav/InstantUpload/Camera//2018/02/20180212_165152.jpg-chunking-899504744-5-2 HTTP/1.1" 200 4334 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.0.0"
%MY_IP% - %MY_USER% [12/Feb/2018:18:51:45 +0100] "PUT /remote.php/webdav/InstantUpload/Camera//2018/02/20180212_165152.jpg-chunking-899504744-5-3 HTTP/1.1" 200 4328 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.0.0"
%MY_IP% - %MY_USER% [12/Feb/2018:18:51:53 +0100] "PUT /remote.php/webdav/InstantUpload/Camera//2018/02/20180212_165152.jpg-chunking-899504744-5-4 HTTP/1.1" 200 4334 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.0.0"
%MY_IP% - %MY_USER% [12/Feb/2018:18:51:54 +0100] "PROPFIND /remote.php/webdav/InstantUpload/Camera//2018/02/20180212_165152.jpg HTTP/1.1" 200 4328 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.0.0"
%MY_IP% - %MY_USER% [12/Feb/2018:18:51:55 +0100] "GET /index.php/apps/files/api/v1/thumbnail/512/512/InstantUpload/Camera//2018/02/20180212_165152.jpg HTTP/1.1" 200 4328 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.0.0"

#### Nextcloud log (data/nextcloud.log)

I think the relevant part is this, but I can provide a full log from the whole uploading process

2018/02/12 18:51:54
ChunkedUploadRemoteFileOperation : Upload of /storage/emulated/0/DCIM/Camera/20180212_165152.jpg to /InstantUpload/Camera//2018/02/20180212_165152.jpg, chunk index 3, count 5, HTTP result status 200

2018/02/12 18:51:54
OwnCloudClient #59 : REQUEST PUT /remote.php/webdav/InstantUpload/Camera//2018/02/20180212_165152.jpg-chunking-899504744-5-4

2018/02/12 18:51:57
ChunkedUploadRemoteFileOperation : Upload of /storage/emulated/0/DCIM/Camera/20180212_165152.jpg to /InstantUpload/Camera//2018/02/20180212_165152.jpg, chunk index 4, count 5, HTTP result status 200

2018/02/12 18:51:57
UploadFileOperation : Upload of /storage/emulated/0/DCIM/Camera/20180212_165152.jpg to /InstantUpload/Camera//2018/02/20180212_165152.jpg: Operation finished with HTTP status code 200 (success)

2018/02/12 18:51:57
OwnCloudClient #59 : REQUEST PROPFIND /remote.php/webdav/InstantUpload/Camera//2018/02/20180212_165152.jpg

2018/02/12 18:51:58
ReadRemoteFileOperation : Read file /InstantUpload/Camera//2018/02/20180212_165152.jpg failed: Unexpected WebDAV exception Exception : [org.apache.jackrabbit.webdav.client.methods.DavMethodBase.getResponseException(DavMethodBase.java:165), org.apache.jackrabbit.webdav.client.methods.DavMethodBase.getResponseBodyAsMultiStatus(DavMethodBase.java:91), com.owncloud.android.lib.resources.files.ReadRemoteFileOperation.run(ReadRemoteFileOperation.java:91), com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:151), com.owncloud.android.operations.UploadFileOperation.saveUploadedFile(UploadFileOperation.java:1356), com.owncloud.android.operations.UploadFileOperation.handleSuccessfulUpload(UploadFileOperation.java:987), com.owncloud.android.operations.UploadFileOperation.normalUpload(UploadFileOperation.java:928), com.owncloud.android.operations.UploadFileOperation.run(UploadFileOperation.java:407), com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:151), com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:155), com.owncloud.android.operations.common.SyncOperation.execute(SyncOperation.java:93), com.owncloud.android.files.services.FileUploader.uploadFile(FileUploader.java:1090), com.owncloud.android.files.services.FileUploader$ServiceHandler.handleMessage(FileUploader.java:1023), android.os.Handler.dispatchMessage(Handler.java:102), android.os.Looper.loop(Looper.java:154), android.os.HandlerThread.run(HandlerThread.java:61)]

2018/02/12 18:51:58
UploadFileOperation : Error reading properties of file after successful upload; this is gonna hurt...

2018/02/12 18:51:58
FileDataStorageManager : Number of files updated with CONFLICT: 1

2018/02/12 18:51:58
FileDataStorageManager : checking parents to remove conflict; STARTING with /InstantUpload/Camera//2018/02/

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by jhf2442** [comment]
In case it matters, I have the nextcloud-client (arch linux, version aur/2.3.3-1) running at the same time on my laptop (thus same IP than my mobile phone)

**Comment by tobiasKaminsky** [comment]
Can you create us a test account, test if the problem occurs also there and if so send the credentials to android at nextcloud dot com with a reference to this issue?

**Comment by jhf2442** [comment]
Hi Tobias,

account created & email sent

problem still happens - uploads tab reports completion, file manager even shows the InstandUpload/Screenshots/2018/02 folder for some time, but after closing and restarting the app the folder is no longer visible, and it never was on the server (root server, checking using "find" command within shell

Previously, a manual test uploadof a picture was hanging - had to restart my mobile phone
From the webserver log (note the increasing number in the filename) : 
%MY_IP% - %USER% [14/Feb/2018:21:29:32 +0100] "HEAD /remote.php/webdav/20180212_172657%20(21540).jpg HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.1"
%MY_IP% - %USER% [14/Feb/2018:21:29:32 +0100] "HEAD /remote.php/webdav/20180212_172657%20(21541).jpg HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.1"
%MY_IP% - %USER% [14/Feb/2018:21:29:32 +0100] "HEAD /remote.php/webdav/20180212_172657%20(21542).jpg HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.1"
%MY_IP% - %USER% [14/Feb/2018:21:29:32 +0100] "HEAD /remote.php/webdav/20180212_172657%20(21543).jpg HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.1"
%MY_IP% - %USER% [14/Feb/2018:21:29:33 +0100] "HEAD /remote.php/webdav/20180212_172657%20(21544).jpg HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.1"
%MY_IP% - %USER% [14/Feb/2018:21:29:33 +0100] "HEAD /remote.php/webdav/20180212_172657%20(21545).jpg HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.1"
%MY_IP% - %USER% [14/Feb/2018:21:29:33 +0100] "HEAD /remote.php/webdav/20180212_172657%20(21546).jpg HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.1"
%MY_IP% - %USER% [14/Feb/2018:21:29:33 +0100] "HEAD /remote.php/webdav/20180212_172657%20(21547).jpg HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.1"
%MY_IP% - %USER% [14/Feb/2018:21:29:33 +0100] "HEAD /remote.php/webdav/20180212_172657%20(21548).jpg HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.1"
%MY_IP% - %USER% [14/Feb/2018:21:29:33 +0100] "HEAD /remote.php/webdav/20180212_172657%20(21549).jpg HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.1"
%MY_IP% - %USER% [14/Feb/2018:21:29:34 +0100] "HEAD /remote.php/webdav/20180212_172657%20(21550).jpg HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.1"
%MY_IP% - %USER% [14/Feb/2018:21:29:34 +0100] "HEAD /remote.php/webdav/20180212_172657%20(21551).jpg HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.1"

**Comment by tobiasKaminsky** [comment]
It seems that your nginx server is misconfigured.

Doing a HEAD on a non-existing file, should give this:
```
 curl -u "tobi:tobi" http://localhost/nc/remote.php/webdav/12312313123.pdf                                                                                                                       
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
  <s:message>File with name 12312313123.pdf could not be located</s:message>
</d:error>
```

But for you I get a real html page, saying the file cannot be found.

Please check:
https://docs.nextcloud.com/server/13/admin_manual/installation/nginx.html

cc @MorrisJobke

**Comment by MorrisJobke** [comment]
Especially those lines should be removed: https://github.com/nextcloud/documentation/pull/392/files

**Comment by jhf2442** [comment]
Many thanks, that seems to be the issue !
Upload now works fine

**Comment by tobiasKaminsky** [comment]
Glad to hear.

**Comment by tobiasKaminsky** [comment]
@MorrisJobke any chance that this can be checked during setup? Took us quite a time to figure this out and ideally the server should warn about this?

**Comment by MorrisJobke** [comment]
> @MorrisJobke any chance that this can be checked during setup? Took us quite a time to figure this out and ideally the server should warn about this?

Let me test a bit, but should be possible.

**Comment by MorrisJobke** [comment]
@tobiasKaminsky Could you open a ticket in the server repo and assign me?

**Comment by jhf2442** [comment]
As far as I could trace it from my backups this must come from some very old owncloud setup.
Have checked - at least owncloud 8.0 recommends to have the 403 and 404 lines in the nginx config
