### ISSUE TITLE
Wrong themed color

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#2157]
Should be black
![2018-02-13-092229](https://user-images.githubusercontent.com/5836855/36139864-75ece1b8-109f-11e8-8080-eff99f383439.png)

**Comment by przybylski** [comment]
I am working on this as a part of #2084

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky is this still present? (I guess no)

**Comment by tobiasKaminsky** [comment]
Is working on light/dark theme.
