### ISSUE TITLE
App gets stuck in synching state when put into background and then killed by the  system

### ISSUE THREAD

**Issue by Bubu** [nextcloud/android#2161]
### steps to reproduce:

1. Be logged in and have the folder list fully synced
2. Enable the "Don't keep activities" setting in androids developer options to force this bug to happen instantly
3. Put nextcloud in background.
4. Bring it into foreground again

The app now displays only empty folders or the "synching" state this apparently goes on indefinitely.

Explicitly closing nextcloud (swiping it away from recently used apps) and opening it again instantly brings back all folders and sync state.

### notes

This has been happening definitely since v2.0 and now with 3.0 as well.

Cc @tobiasKaminsky as we talked about this yesterday.

**Comment by tobiasKaminsky** [comment]
Great that you found a way to trigger this :+1: 
I will try to solve this for next version as this is a really nasty bug UX wise.

**Comment by Bubu** [comment]
I had to uninstall-reinstall the app to finally fix this on my phone, no idea what was going on.

**Comment by Bubu** [comment]
The bug actually reappeared now after pressing back when being in the loaded folder list. Now I can reproduce it again as in the initial report.

Can someone reopen?

**Comment by tobiasKaminsky** [comment]
This is closed as the bug fixing PR was merged.
It is currently available only in dev version and will be in upcoming 3.1.
Which version do you use?

**Comment by Bubu** [comment]
Well now that explains it all I guess. Currently using 3.0.3 from f-droid I thought this was in 3.0.2 already :see_no_evil:
