### ISSUE TITLE
Backport Fix Push

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#2162]
Backport of #2150 to ship the fix for #2145 with 3.0.1

Cc @mario

**Comment by mario** [comment]
👍

**Comment by AndyScherzinger** [comment]
Cc @tobiasKaminsky

**Comment by tobiasKaminsky** [comment]
My plan/idea was to label all needed PRs with "backport" and as soon as we merge them, create a backported version of it.
We can also add them to our roadmap issue and delete them afterwards.

**Comment by tobiasKaminsky** [comment]
I also remove the "backport" label once we have the PR backported, so we do not loose track.
