### ISSUE TITLE
Push notification is still received if account is removed

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#2167]
- add account
- test push notification -> working
- remove account (no account available now)
- test push notification -> still receiving

On AccountRemovalJob we should test if this is the last account and then remove the push key.
Or do we just want to suppress showing the notification?

**Comment by mario** [comment]
I don't understand, how will this help? You'll receive push notifications until account removal process has been completed and the account has been unregistered for push.

I'd never remove the push key.

Once push is implemented properly, we won't show notifications for accounts pending delete.

I'll leave this to you to close :)

**Comment by tobiasKaminsky** [comment]
> the account has been unregistered for push

This somehow does not happen. As said, I have all accounts removed, but still get a push notification for my account "test": it is shown in notification bar, and if I click on it, Login view is shown.

**Comment by mario** [comment]
Then this has to be debugged. But this is a different issue.

**Comment by mario** [comment]
Will take a look soon.

**Comment by tobiasKaminsky** [comment]
I cannot reproduce this on latest master -> closing.
