### ISSUE TITLE
On upload connection error, German string is wrong (minimal)

### ISSUE THREAD

**Issue by nerdoc** [nextcloud/android#217]
### Actual behaviour
when an upload of a file fails, the Message says "Verbindungs Fehler". This is known as "Deppenleerzeichen", it should be "Verbindungsfehler"
 
### Steps to reproduce
Just upload a file from your android device, cut the connection meanwhile.

![screenshot_20160816-121419](https://cloud.githubusercontent.com/assets/2955584/17695968/9f9b38c2-63ab-11e6-882e-9b614b1f0534.png)

### Environment data
Android version: 6.0.1 
Device model: Samsung i9100
Stock or customized system: Cyanogenmod
Nextcloud app version: 1.1.0
Nextcloud server version: 9.0.52

### Logs
not necessary here. only translation error.

**Comment by nerdoc** [comment]
BTW: I would have changed this in Transifex, but could not find it... - therefore the issue here.

**Comment by AndyScherzinger** [comment]
@nerdoc can you update to version 1.2.0 and try again. I checked the language files and tried it on my phone and the spelling mistake isn't there :)

**Comment by nerdoc** [comment]
OMG. Have overlooked that 1.2 is available...
Yes. it is "Verbindungsfehler" now.
Sorry for the Spam ;-)

**Comment by AndyScherzinger** [comment]
No worries, enjoy 1.2 :smiley:
