### ISSUE TITLE
key storage error continues e2e

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/android#2173]
I have updated to nextcloud 3.0.1 I have read of the resolution of the problem of the key storage on oreo, but for those who have nougat still not good. i have s8 samsung and nexus 6 with android 7.x but error also persists with 3.0.1
![screenshot_20180214-145614](https://user-images.githubusercontent.com/35575744/36208061-1581e6a8-1198-11e8-85bb-1c0a6c424af3.png)

**Comment by tigernero79** [comment]
I uninstalled and reinstalled but the problem persists. I have my nextcloud hosted on Aruba and I do not have access to the Shell how to fix?

**Comment by hebbet** [comment]
Still not working with Pixel 2 and Android 8.1

**Comment by tigernero79** [comment]
have fixed with nextcloud 3.0.1 with oreo and pixel 2, the problem for me was I believe the special character in the username and / or password, I created a new account as administrator and with password without special characters and the key are stored correctly .

**Comment by tobiasKaminsky** [comment]
@tigernero79 which special char is this? "@"?

**Comment by tigernero79** [comment]
Yes

**Comment by tigernero79** [comment]
yes in the name I had the @ and in the password I used @ and # now I do not know if the username or password with special characters which Delle 2 bothered. fact is that I created administrator user without special characters in the name and password everything has worked.

**Comment by tobiasKaminsky** [comment]
@tigernero79 thank you for testing and finding this bug :tada:
