### ISSUE TITLE
Autoupload not respecting battery saver whitelisting of app

### ISSUE THREAD

**Issue by CNeutron** [nextcloud/android#2174]
### Actual behaviour
Autoupload is not auto uploading files, while in battery-saver mode (Stamnia on Sony), even though the Nextcloud app is checked for not-optimised in Battery-Saver_mode ("nicht optimiert" in "Akku-Leistungsoptimierung") 
Sorry, but for some words I do not know their exact english counterparts (mine is german)

### Expected behaviour
Nextcloud used to auto-upload just fine before 3.0.0 (even if in Stamnia Mode)
 
### Steps to reproduce
1. Activate Stamnia Mode
2. check Nextcloud in Stamnia Mode whitelist
3. activate Autoupload
4. take picture --> no Upload

Version 1
5. deactivate Stamnia Mode --> still nothing happens
6. in Nextcloud App go to Uploads --> Force New Scan --> Upload starts

Version 2
5. in Nextcloud App go to Uploads --> Force New Scan --> Upload shows up, but "Warte auf Verslassen des Energiesparmodus"
6. deactivate Stamnia Mode --> Upload starts

### Environment data
Android version:
7.1.1
Device model: 
F5321 (Sony Xperia X Compact)
Stock or customized system:
Stock
Nextcloud app version:
3.0.0 & 3.0.1
Nextcloud server version:
13.0.0
### Logs
Are there useful Logs that I can extract from the App? How?

**Comment by tobiasKaminsky** [comment]
@mario can this be related to this? https://github.com/nextcloud/android/blob/f675c1c972c3aa217c0ec66692fffb97962a9f47/src/main/java/com/owncloud/android/operations/UploadFileOperation.java#L771-L771

**Comment by mario** [comment]
This is not a bug as this is intentional and expected. Uploading during power save can easily kill your phone and damage the battery in the long run since you can run into 0%.

**Comment by CNeutron** [comment]
With a quick search I'm thinking it should respect the adnroid API isIgnoringBatteryOptimizations.
I have my mobile on Powersave all the time, but exclude/whitelist some Apps from it (nextcloud being one of them).
So while it is true that my mobile is on powersave, nextcloud should not be.

Other solution:
Would it be possible to make that user selectable?

**Comment by mario** [comment]
Power saving mode is different from ignoring battery optimizations however. Ignoring battery optimizations means services of the app are more likely to live and notifications more likely to appear if your app is in the background. 

Power saving is turned on automatically once you reach a certain percentage of your battery. You can change that percentage on some phones though.

**Comment by CNeutron** [comment]
Thanks for the clarification, guess my Sony Phone isn't as smart as I was hoping.

A followup though:
After leaving Power saving mode (when I charge it), shouldn't there be a Scan (reScan) of the auto-upload folders?

**Comment by mario** [comment]
It will happen within 15-20 minutes. :)

**Comment by CNeutron** [comment]
thanks

**Comment by DEvil0000** [comment]
I see the info on android 5 which does not have battery optimisation.

**Comment by thekk1** [comment]
> It will happen within 15-20 minutes. :)

This is never happen on Samsung S21 in all time energy saving mode.
