### ISSUE TITLE
When there auto upload conditions (WiFi, charge) app should only queue files when conditions are met

### ISSUE THREAD

**Issue by S74HK9hV** [nextcloud/android#2176]
Not really a bug, just improvement suggestion

### Actual behaviour
- Auto upload starts queuing files for upload as soon as photo is taken. If file is deleted a few minutes later, it remains in the upload queue. Later, once the app is ready to upload (WiFi and charging conditions are met) the app returns an error saying that local file is not found

### Expected behaviour
- App should not try and upload deleted files. Should check for files to be uploaded at the time of upload so that it doesn't try and upload non-existent files
 
### Steps to reproduce
1. take some photos
2. delete one or more photos
3. trigger auto-upload by connecting to charging and wifi (this assumes you have set those conditions, instead of uploading immediately)

### Environment data
Android version: 8.0.0

Device model: Sony F5321 Xperia X Compact

Stock or customized system: Stock

Nextcloud app version: 3.0.1

Nextcloud server version: 13

#### Web server error log
```
no errors on server side
```

#### Nextcloud log (data/nextcloud.log)
```
no errors on server side
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by mario** [comment]
It doesn't try to upload them, aka there's no network connectivity going on if the file doesn't exist.
