### ISSUE TITLE
 if I change user in the android application I can not delete file

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/android#2181]
Practically changing user in the android application with a new one does not allow me to delete folders or files says that I am not allowed, in the nextcloud logs I have:

":"DELETE","url":"\/Nextcloud\/remote.php\/webdav\/Doc_Miei\/contratto%20portabilita.pdf","message":"Exception: {\"Exception\":\"OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Exception\\\\Forbidden\",\"Message\":\"client not allowed to access end-to-end encrypted content\",\"Code\":0,\"Trace\":\"#0 \\\/web\\\/htdocs\\\/www.pensierando.it\\\/home\\\/Nextcloud\\\/apps\\\/end_to_end_encryption\\\/lib\\\/Connector\\\/Sabre\\\/

tells me: 
client not allowed to access end-to-end encrypted content,

but not

 is a folder or file encrypted and even if it was user I enabled with the 12 words ..., I deactivated module e2e I can with new user to delete files and folders

![screenshot_20180215-104705](https://user-images.githubusercontent.com/35575744/36250297-ac7e6bd0-123d-11e8-8d9c-faf7acaeee3f.png)

**Comment by tigernero79** [comment]
there is also a translation error:
the words: "Non Ti è consentito per eliminare questo file" 

you write it

"Non ti è consentito di eliminare questo file"


the word "per" should be changed to its place should be "di"

**Comment by tigernero79** [comment]
It is as if you saw the files and folders not encrypted as encrypted and obviously android application is not yet enabled to delete files and folders encrypted.

But the problem is that by mistake it is unencrypted folders and on unencrypted files.

this after switching user in the application

**Comment by AndyScherzinger** [comment]
> the word "per" should be changed to its place should be "di"

@tigernero79 can you check (and maybe correct) the translation on transifex https://www.transifex.com/nextcloud/nextcloud/android/ where all translations are maintained since I don't know which exact locale you're device is using?

**Comment by tigernero79** [comment]
Italiano

**Comment by tigernero79** [comment]
error 
https://github.com/nextcloud/server/issues/8379

**Comment by schiessle** [comment]
If you run server-side encryption and client-side encryption in parallel this should fix it: https://github.com/nextcloud/end_to_end_encryption/pull/61, maybe you can apply this two line change and report back if it solves the issue for you: https://github.com/nextcloud/end_to_end_encryption/pull/61/commits/cb7e3b1ac51d65beb4a8d6bbdbb551ae02982fa7
