### ISSUE TITLE
Register intent filters with Nextcloud to be available for opening any kind of file

### ISSUE THREAD

**Issue by mathiasconradt** [nextcloud/android#2182]
Would be great if Nextcloud files app would register an intent filter to allow other apps to select documents (esp. pdf, images, .docx) from it.
For example, in the [DocuSign](https://play.google.com/store/apps/details?id=com.docusign.ink) app, Nextcloud does not appear as an option to choose files from.

![image](https://user-images.githubusercontent.com/295122/36258304-719afa70-125a-11e8-885b-744d317e96da.png)

**Comment by AndyScherzinger** [comment]
@mathiasconradt we actually do have that...well had it seems

@mario @tobiasKaminsky the document provider seems to be broken. I checked it on my Android 8.0 OP3T and also can't see Nextcloud anymore.

**Comment by mario** [comment]
It appears "sometimes". I don't know when "sometimes" is though xD

**Comment by mathiasconradt** [comment]
@mario Maybe compare the manifest.xml with the ones of the other apps (in my screenshot) that appear stable?

**Comment by mathiasconradt** [comment]
@AndyScherzinger You mean the DocuSign menu? No, nothing happens after leaving the menu open for few minutes. I think that there are simply intents missing in the intent filters, I don't think that Android needs so long to find providers.

Beside BROWSABLE I would maybe try with OPENABLE or some other. For reference, I attach the AndroidManifest.xml of Dropbox, which definitely appears as provider app a lot and stable. Maybe you can find some hint in there.

[AndroidManifest.xml.txt](https://github.com/nextcloud/android/files/1728476/AndroidManifest.xml.txt)

**Comment by tobiasKaminsky** [comment]
For me it is working with 3.0.1.
As you can see, NC is showing on top, not as an app.
As far as I know, you can currently choose only files that are already downloaded. So maybe you do not have any file within nc folder downloaded?

![image](https://user-images.githubusercontent.com/5836855/36301007-b2540030-1303-11e8-999e-d995402693fe.png)

**Comment by AndyScherzinger** [comment]
> As far as I know, you can currently choose only files that are already downloaded.

didn't test it again, but I thought you browse the remote structure and it'll download if not present on the device

**Comment by mathiasconradt** [comment]
I think so too, that you'd browse the remote structure. Anyway, I do have files in the local Nextcloud folder, and I'm also on 3.0.1.

![image](https://user-images.githubusercontent.com/295122/36301434-1effec66-1305-11e8-893c-98cff2cbff6a.png)

**Comment by tobiasKaminsky** [comment]
Yes it its. But I do not see any remote folder structure in it...Only those files I had downloaded.

**Comment by mathiasconradt** [comment]
Ok, but then I think the wrong activity (inside the Nextcloud app) is chosen here.

**Comment by tobiasKaminsky** [comment]
This is a document provider: any app can request/browse the content of an app, if this app provides a document provider. 
Why do you think that the wrong activity is used? What do you expect instead?

**Comment by mathiasconradt** [comment]
I expect the same behaviour as with Dropbox or Google Drive here: being able to browse the remote documents on the server (and not only local ones that have been stored already) and select one (which then, in this example, gets loaded into DocuSign). Standard document picker functionality.

> Why do you think that the wrong activity is used? 

Just a guess. If you don't get to the document picker for remote documents but only able to pick local documents, then there must be something wrong there, therefore my guess is that the document browser (for remote documents) isn't called but something else. But since I don't have Nextcloud as an option, I cannot validate this, just a guess from your description above regarding its current behaviour.

**Comment by tobiasKaminsky** [comment]
> If you don't get to the document picker for remote documents but only able to pick local documents, then there must be something wrong there

As far as I remember this was implemented by @przybylski and on first iteration it was intended to have only already downloaded files shown.

**Comment by mathiasconradt** [comment]
> However: you see only those files, which folders you have entered once. So if you've never been to /A/B/C, and then navigate to it in document provider you will see no files in C.

I see. Google Drive seems to behave similar (doesn't allow refreshing the file list via remote calls to the server while in the "document picker mode"), while Dropbox does that and also shows folder structures that you haven't entered before. Just tested it. Of course, the latter is a little bit nicer to have, if it's technically possible in NC.

**Comment by mathiasconradt** [comment]
@tobiasKaminsky @AndyScherzinger No idea what has changed, but today when I needed the file picker in some app, all my Nextcloud accounts are showing up properly on my Huawei device where they previously never showed before.

I see that the latest app version 3.0.2 just got released on Feb 27. Maybe the update included a fix for this as well.

**Comment by AndyScherzinger** [comment]
> I see that the latest app version 3.0.2 just got released on Feb 27. Maybe the update included a fix for this as well.

No idea.... 3.0.2 didn't have any changes for the document provider implementation...

**Comment by tobiasKaminsky** [comment]
3.0.2 and 3.0.3 did not touched these code parts.
We should keep this open as it happens also on emulator that the accounts are not showing up.

**Comment by FredericLespez** [comment]
On my two phones (OnePlus 5T with latest LineageOS and Oneplus 6 with latest OxygenOS) and Nextcloud android 3.6.0, I am still seeing this issue.

**Comment by tobiasKaminsky** [comment]
@FredericLespez can you try this
- start nc app
- start files/documents app -> verify if nc is there
- if not: close files/documents app via "recent apps"
- start files/documents app again

Do you have any pass protection enabled within our app?

**Comment by FredericLespez** [comment]
@tobiasKaminsky I tried what you suggested, but it didn't solve the issue.
Server side, I use Nextcloud 15.0.7 with 2FA (TOTP) enabled.
Android Side, I use the Nextcloud PIN access feature.

I tried to disable the Nextcloud PIN access feature and now it works...
That's strange because I am pretty sure it wasn't working "before" (cannot be more precise).
And it keeps working even if I enable it again. But if I keep it enabled, it doesn't work after a reboot.

**Comment by tobiasKaminsky** [comment]
> I tried to disable the Nextcloud PIN access feature and now it works...

This is expected. The idea is, that if the app/content is so restricted that you need /want a pin/protection, then also no other apps should have access to it.



> And it keeps working even if I enable it again. 

This is a bug then. It should directly remove the document provider. Can you verify if only the NC entry is shown, or if you can really access data?

> But if I keep it enabled, it doesn't work after a reboot.

This is then working fine.

**Comment by tobiasKaminsky** [comment]
> > And it keeps working even if I enable it again.
> 
> This is a bug then. It should directly remove the document provider. Can you verify if only the NC entry is shown, or if you can really access data?

- see storage within doc/files app
- enable pin protection
- see storage within doc/files app
- try to refresh/download
--> error as permission is restricted
- disable pin protection
- see error in doc/files app
- refresh 
- works

--> so in my case everything works as expected

**Comment by FredericLespez** [comment]
@tobiasKaminsky 

> > And it keeps working even if I enable it again.
> 
> This is a bug then. It should directly remove the document provider. Can you verify if only the NC entry is shown, or if you can really access data?
After enabling again PIN protection, you can access data until you close (via "recent apps") either the Files or the Nextcloud app. After access is blocked.

I can see exactly the same behavior with the OneDrive app (except that you need to force close the app after enabling PIN protection to bloacl data access).

So we can say everything work as expected, maybe the fact that PIN protection and 'file manager' integration is incompatible should be told to the user. Maybe through a pop-up when you enable PIN protection ?

Thanks a lot for your help.
