### ISSUE TITLE
upload files to an encrypted folder?

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/android#2189]
with Android application still not allowed to upload files to the encrypted folder?

**Comment by tobiasKaminsky** [comment]
Can you create us a test account and send the credentials to android at nextcloud dot com with a reference to this issue?

**Comment by tigernero79** [comment]
tobias send email nero79@msn.com whit credenzial for test account

user= tobias
psw= send to email nero79@msn.com

url= https://www.pensierando.it/nextcloud

**Comment by tigernero79** [comment]
@tobiasKaminsky 

the reference is that once created the folder and encrypted with e2e inside I can not copy anything or create folders I do not have permission to do so says.

**Comment by 80tf3262p8** [comment]
"Fixing" the user agent in 3.0.1 is probably what broke this. It works fine back in 3.0.0.
From the 3.0.1 notes: "New android lib, fixing wrong user agent"
From the server log, after updating Android client to 3.0.1:
"OCA\DAV\Connector\Sabre\Exception\Forbidden: client not allowed to access end-to-end encrypted content
/home/nextcloud/nextcloud/apps/end_to_end_encryption/lib/Connector/Sabre/LockPlugin.php - line 124: OCA\EndToEndEncryption\Connector\Sabre\LockPlugin->checkUserAgent('Mozilla/5.0 (An...', '/e2eetest')"

**Comment by tobiasKaminsky** [comment]
We hope this is fixed in upcoming 3.0.2

**Comment by tobiasKaminsky** [comment]
This is fixed with 3.0.2, tested with a clean installation with an existing user and with a fresh one.
If this happens again, please re-open.
