### ISSUE TITLE
Full size previews do not scale to fullscreen

### ISSUE THREAD

**Issue by godfuture** [nextcloud/android#2190]
### Actual behaviour
When opening a fresh image, the full preview is shown after short time. As intended. But it seems that the temporal preview in full size is not scaled well to full-screen. They appear to be too small. This does not apply to downloaded images.

### Expected behaviour
The image is previewed. After short time the full size image is shown. The temporal full size preview is scaled well to full screen, just as the downloaded one.
 
### Steps to reproduce
1. Upload image to server which has less pixels than the screen of your mobile device.
2. Browse to this image with android client.
3. Open (non downloaded) image with android client. Wait for  full size image being delivered automatically.
4. Check, if image is scaled to full screen.

### Environment data
Android version: 7.1.2

Device model: BQ X5 Plus

Stock or customized system: LOS 14.1

Nextcloud app version: 3.0.1

Nextcloud server version: 13.0

**Comment by AndyScherzinger** [comment]
@godfuture thanks for the report. Could you provide any screenshots please since I wasn't able to reproduce the behavior (yet)?

**Comment by godfuture** [comment]
![screenshot_20180219-022555](https://user-images.githubusercontent.com/4669278/36358339-28d72308-150d-11e8-8fdf-3eb7e07168e3.png)
![screenshot_20180219-022845](https://user-images.githubusercontent.com/4669278/36358340-28fdfa78-150d-11e8-8fd1-01aa7cb846a6.png)
![gt143](https://user-images.githubusercontent.com/4669278/36358341-292714c6-150d-11e8-9687-e6990d83398e.png)

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky any idea on why this might happen?

**Comment by tobiasKaminsky** [comment]
What file type is this?
I saw this from time to time with png or svg...?

**Comment by AndyScherzinger** [comment]
According to the screenshots the file type is png
