### ISSUE TITLE
Host not found

### ISSUE THREAD

**Issue by bloo90** [nextcloud/android#2193]
### Actual behaviour
-After logoff application doesn't login with given server login, pass and hostname. When I'm typing server address application display "security connection", but when I click login it displays "hostname not found". Even when typed demo.owncloud.org with test/test credentials app shows "hostname not found" error.

### Expected behaviour
-Tell us what should happen
 
After logoff when adding server it should add account and run

### Steps to reproduce
1. Logoff/remove account from app
2. Try to login to demo.owncloud.org with test/test credentials
3. See error "hostname not found"

### Environment data
Android version: 6.0

Device model: Huawei P8Lite

Stock or customized system:no

Nextcloud app version: 3.0.1

Nextcloud server version: 10.0.4

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
cc @mario @tobiasKaminsky 

@bloo90 any chance for upgrading the server? Nc10 is End-of-Life since last year and isn't supported anymore.

Closing since it is a Duplicate of #2194
