### ISSUE TITLE
Login won't work with "Couldn't found host" message

### ISSUE THREAD

**Issue by Siggi0904** [nextcloud/android#2194]
### Actual behaviour
With Lineageos 7.1.2 on NC 11.0.1 and 3.0.1 the android app won't work.
In login window "Secured connection established" is shown und the domain. Then I input the password and after pressing the connect button Message "Couldn't found host" is shown. Both messages here in german, that means translation to english could not be exact the same.

Verified by others with same versions on our server https://cloud.sl-its.de

### Expected behaviour
Finalized login process to see data.

### Steps to reproduce
1. Open login window
2. "Secured connection established" is under insert domain shown
3. insert creditals
4. push login button
5. "Couldn't found host" is under domain shown

### Environment data
Android version: 7.1.2 security patches January 2018

Device model: Samsung Galaxy S4 I9506

Stock or customized system: Lineageos 7.1.2

Nextcloud app version: 3.0.1

Nextcloud server version: 11.0.1

**Comment by AndyScherzinger** [comment]
cc @tobiasKaminsky @mario this has also been reported on GPlay several times. @Siggi0904 any chance for upgrading the server? According to https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule Nc will be End-of-life by May 2018 so it is highly recommended to upgrade.

**Comment by Siggi0904** [comment]
Hi Andy, upgrading is not a solution for this, because of firstly the server is not in my hand and second version 12 and 13 not stable enough that my admin will upgrade. In addition the upgrade process doesn't work pretty well, but other topic.

In these fact, it would be nice that newly released apps working with older NC version's.

**Comment by AndyScherzinger** [comment]
> In these fact, it would be nice that newly released apps working with older NC version's.

The app should work with Nc11, yes. Else it is a bug and this is one we need to look into and fix. Beware though that as soon as Nc11 is EOL it is likely that as soon as there is a breaking change the devs (including me) won't put extra effort in supporting a server version that isn't supported anymore itself.

What do you think @mario @tobiasKaminsky ?

**Comment by Siggi0904** [comment]
Ok, I'll talk with my admin to upgrade to 12 or 13 of NC.

But would be nice that till of EOL all released apps are working with.
Ofter EOL, you are right, it could be that it doesn't work with but then the latest working version should be shown and documented at the apps website.

**Comment by AndyScherzinger** [comment]
> But would be nice that till of EOL all released apps are working with.

Fully agree on that, so yes it is a bug!

**Comment by bloo90** [comment]
After upgrade to 12->13 problem solved

**Comment by Siggi0904** [comment]
http://paste.thedevstack.de/view/99ad3076 -> server log file (doubled from cache server)
http://paste.thedevstack.de/view/e5e21c76 -> nextcloud log file

Looks like login successed but the shows nothing.

I deleted the old account in the app after that the loading sign will shown every time.

**Comment by Siggi0904** [comment]
In addition a screen with these loading circle.

![screenshot_20180217-223019](https://user-images.githubusercontent.com/4992106/36345836-e2baa9f6-1432-11e8-9bba-7fc767866d79.png)

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky can you have a look at this one?

**Comment by thebaron06** [comment]
I am pretty sure thats the same issue like mine: https://github.com/nextcloud/android/issues/2192
At least the behavior is exactly the same.

**Comment by Siggi0904** [comment]
If it is these nullpointer, can you please catch them and update it to the beta channel in Google play store? Then we can check that it is fixed before to release it as stable.

In beta with addition loggings for example.

**Comment by janipewter** [comment]
I have this issue too. Nextcloud app on Android 7.0.  When I input the URL it says secure connection established, but when I enter credentials and click connect it says could not find host.

Can't take a screenshot as app DRM seems to prevent it.

Nextcloud app version 3.0.1 from Play store
Android 7.0 on Samsung Galaxy S7
Owncloud server version 10.0.4 stable

**Comment by thebaron06** [comment]
@Siggi0904 i can just provide an untested fix for thatbecause i do not have the possibility to test that here as well as i do not have the build environment set up. I also do not know whats the impact of the change. I am a bit busy the next days but i will try my best to provide a mr.

**Comment by tobiasKaminsky** [comment]
@Siggi0904 
I tested 3.0.1 with latest NC11 and it is working for me.
The fix/bug from @thebaron06 should also not affect you as in NC11 we have a quota.

I suspect that something is wrong with server setup.
@Siggi0904 @janipewter 
Can you create us a test account and send the credentials to android at nextcloud dot com with a reference to this issue?

**Comment by tobiasKaminsky** [comment]
> Can't take a screenshot as app DRM seems to prevent it.

This happens if you have pin protection enabled.

**Comment by mrlongshen** [comment]
Im using nc 12 and nc apps 3.0.2 its not working.

**Comment by mrlongshen** [comment]
Typo nc 3.0.1

**Comment by tobiasKaminsky** [comment]
This is fixed via https://github.com/nextcloud/android-library/pull/127 and will be in 3.0.2

**Comment by mrlongshen** [comment]
Thanks. Its work now ! Yehaaaaaaaaaaaaaaaaa 😁😍

**Comment by tobiasKaminsky** [comment]
How is this? There is no new release? ;-)

**Comment by janipewter** [comment]
What was the problem and when will the updated app be in Play store?

**Comment by Siggi0904** [comment]
Hi, is it now fixed?
When will be the 3.0.2 released at GooglePlay?
I'm at the beta channel but there is no testing stuff.

**Comment by khandom** [comment]
When will the 3.02 Android app be released?

**Comment by xXSTrikeXx** [comment]
Hey folks, please have a look at the milestones:

https://github.com/nextcloud/android/milestones

There are many issues open and some pull request aren't pulled. So please be patient until the pr are merged and a beta can be build. :wink:

**Comment by tobiasKaminsky** [comment]
Plan is to release 3.0.2 today.
Please note that NC10 is end of life and therefore might not work in all cases.

**Comment by AndyScherzinger** [comment]
Last remaining PR has been merged. Thus I close the issue for now. Please re-open in case you still experience this issue after a 3.0.2 updated (which you shouldn't of course).

**Comment by khandom** [comment]
Your patch seems to have fixed our issue. I will continue to test the
functionality with intentions of upgrading from OC to NC. Thank you very
much :) I left a 5 star review on the google play store.

On Tue, Feb 27, 2018 at 10:43 AM, Andy Scherzinger <notifications@github.com

**Comment by AndyScherzinger** [comment]
Hi @khandom, thank you very much for your feedback and of course for the 5 star rating! Happy we could fix the issue :)

**Comment by janipewter** [comment]
The update seems to have fixed the problem for me too. Thanks for your hard work guys...will give you a 5 star review on Google Play.

**Comment by AndyScherzinger** [comment]
Thanks for the feeback and the 5 star rating @janipewter. Both is highly appreciated.

**Comment by Siggi0904** [comment]
Login window popup every time with 3.0.2 too.
See https://github.com/nextcloud/android/issues/2133

**Comment by AndyScherzinger** [comment]
Just dropped you an email. If you can provide us with a test account than we can debug the issue with your server.

**Comment by Siggi0904** [comment]
I answered your mail.

**Comment by Myzel394** [comment]
If anyone is coming across this, make sure to set a A record for your domain. I was using a CNAME record, which didn't work.
