### ISSUE TITLE
storage path

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/android#2195]
I noticed that by default the folder where nextcloud saves the downloaded files is: "storage / emulated / 0" 

if I change storage location in one Of the three options set by you 

I can no longer choose the default "storage / emulated / 0 "

if not uninstalled and reinstalled android app

**Comment by mario** [comment]
This is expected. /storage/emulated/0 is a "broken" configuration that exists only in legacy installs, and we do not encourage it really.
