### ISSUE TITLE
Can not upload file to E2E folder on Android 

### ISSUE THREAD

**Issue by johnwmail** [nextcloud/android#2197]
### Actual behaviour
-Tell us what happens
Upload file to E2E folder, then nextcloud show error message: forbidden

### Expected behaviour
-Tell us what should happen
 Success to upload file to E2E folder

### Steps to reproduce
1. encrypt E2E folder with "E2E encryption"
2. upload file to E2E folder
3. nextcloud show error message: forbidden

### Environment data
Debian, nginx, php7.2, redis

Device model: 

Stock or customized system:

Nextcloud app version:
Android version:3.0.1
Nextcloud server version:
13.0.0.14
#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
#7 {main}\",\"File\":\"\\\/www\\\/apps\\\/end_to_end_encryption\\\/lib\\\/Connector\\\/Sabre\\\/LockPlugin.php\",\"Line\":169}","userAgent":"Mozilla\/5.0 (Android) ownCloud-android\/3.0.1","version":"13.0.0.14"}

```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tigernero79** [comment]
discussion here already open
https://github.com/nextcloud/end_to_end_encryption/issues/60

**Comment by johnwmail** [comment]
@tigernero79 thanks
So, I close this report.
