### ISSUE TITLE
Duplicated images on external storage

### ISSUE THREAD

**Issue by sysoppl** [nextcloud/android#2198]
### Actual behaviour
When images are uploaded to external storage (ostack in my case), they are duplicated in gallery. 

### Expected behaviour
Images should not be duplicated
 
### Steps to reproduce
1. Upload files to external storage:
![screenshot_2018-02-18-17-57-10](https://user-images.githubusercontent.com/30871217/36354642-c8779ef0-14d7-11e8-8e72-71afdf95a65e.png)

2. Open "photos" from menu
3. Images are duplicated:
![screenshot_2018-02-18-17-56-36](https://user-images.githubusercontent.com/30871217/36354643-cb383b9a-14d7-11e8-855e-ad01810006b7.png)

After that, when I go back to the folder with uploaded files, for short amount of time they are showing like this:
![screenshot_2018-02-18-17-56-42](https://user-images.githubusercontent.com/30871217/36354617-6e6ce96a-14d7-11e8-932f-50ac3d1d95b4.png)
and when it refreshes, they're back to normal (3 files)

In browser everything is showing good.

When images are on internal storage, they are showing as they should.
### Environment data
Android version: 6.0

Device model: Lg K350

Stock or customized system: stock

Nextcloud app version: 3.0.1

Nextcloud server version: 13

**Comment by AndyScherzinger** [comment]
Thanks for your report @sysoppl!

Im closing this issue as a duplicate in favor of #1698 since this is the case for images and favorites.

**Comment by AndyScherzinger** [comment]
PR is #2490
