### ISSUE TITLE
Visualise external storages

### ISSUE THREAD

**Issue by xXSTrikeXx** [nextcloud/android#2199]
In the windows client the external storages are easily showed with a network icon. In Android there is only a normal folder icon for external storage.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky I know that we had the external folder icon within our forked source but it hasn't been used by the app. Do you know how we can identify external storage/folders?

**Comment by tobiasKaminsky** [comment]
Done. We need a bit of files_external app change (done by @rullzer :+1: ), so it will take some time until we see the external folder icon.
I think it is bound to major releases, so it will be in NC14.
