### ISSUE TITLE
Slight design optimizations for the login screen

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#22]
As per discussion with @nextcloud/designers / @jancborchardt 

- remove the card view (white hovering thingy)
- color of input fields to be white
- "Do you know Nextcloud?" to white, but semi-transparent at 50% which means #7fc0e3 (since we don't have transparency, or at least I couldn't find it for text, just backgrounds)

Development will be done on: https://github.com/nextcloud/android/tree/loginLayout
The Branch could also be used to do #16 while working on the login screen changes from this issue

**Comment by MorrisJobke** [comment]
Sounds great. Just for reference: this is how it looks nowadays: https://github.com/nextcloud/screenshots/blob/75f2376e9d1a413dde74f324e42c4372b9d81aab/android/phone/login.png

**Comment by AndyScherzinger** [comment]
I know... I did that :P

**Comment by skymania** [comment]
A 16dp left and right padding and we have a winner ;)

**Comment by AndyScherzinger** [comment]
Hmm, strange, will have to check that because I thought I did set a 16dp padding... 0_o 
But yes, if this isn't the case the 16dp are going to be set :)

**Comment by MorrisJobke** [comment]
> I know... I did that :P

I just want to post it for reference for other people that maybe read this ;)

**Comment by mar1u5** [comment]
Solved with #75 :muscle:
