### ISSUE TITLE
Manual photo upload from DCIM folder broken on Android N

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#220]
Android N Preview 5 on a Nexus5X:
You can't upload photos from the camera (DCM folder) anymore manually. For some reason the images are detected as folders (which they are not). Images in other folders are detected as photos though.

![device-2016-08-17-190718](https://cloud.githubusercontent.com/assets/1315170/17745965/3eefd1d2-64ae-11e6-8c3c-7d4eec59210c.png)

**Comment by Olodin** [comment]
Thought I had found the same bug, but for me those were actual folders. One image and one corresponding folder. Maybe the folder is left from HDR processing?

Uploading the image files worked without problems.

I just checked this with 1.2.0 on Nexus 5X with Android N latest preview NPD90G.

**Comment by niceyyy** [comment]
The folders are there, but the pictures are also there. Just scroll down

**Comment by AndyScherzinger** [comment]
This seems to be a Android OS / camera bug we can't do anything about :(
Need to check if this behavior persists in the recently released Android N final version.

**Comment by AndyScherzinger** [comment]
Unfortunately this seems to be a standard behavior in Android N now :(
