### ISSUE TITLE
Auto upload custom remote folder setup problem

### ISSUE THREAD

**Issue by amotl** [nextcloud/android#2202]
### Credits and intro
First things first: Thank you so much for conceiving and maintaining the grand Nextcloud project. You rock!

I am finally moving to mobile and obviously want to use Nextcloud instead of sharing my personal data with Google or others. Using DAVdroid for syncing contact information works perfectly already so i am now trying to tackle the automatic image upload feature by using the Nextcloud Android App. However, i found a minor issue when configuring the custom settings.

### Actual behaviour
I am trying to configure a custom remote folder for the "Auto upload" feature. Unfortunately, i am not able to actually save these settings. The "SAVE" button just doesn't respond. Using "CANCEL" works, though - but obviously doesn't store the desired settings.

### Expected behaviour
The "SAVE" button on the custom folder settings dialog actually works and the desired "Auto upload" custom folder settings get applied properly.
 
### Steps to reproduce
1. Navigate to "Auto upload"
2. Use button "Set up a custom folder" at the top to display settings dialog
3. Try to tap the "SAVE" button...
4. ... it does not respond ;[.

### Environment data
Android version:
7.1.2

Device model: 
SM-G930F

Stock or customized system:
Stock LineageOS 14.1-20180124-NIGHTLY-herolte

Nextcloud app version:
3.0.1

Nextcloud server version:
11.0.4.1

**Comment by AndyScherzinger** [comment]
@amotl did you set the remote and local folder within the dialog?

**Comment by amotl** [comment]
Hey @AndyScherzinger,

thanks for your quick response. When setting both local **and** remote folders, the custom folder got added, thanks! I have to admit that by doing so, i finally recognized that this is about adding **new/different** folders to the synchronization besides the default ones.

While arriving as a new user to the application, i had the impression that these would be global settings applying to all the items below. That's the reason i tried to set the remote folder only.

Now everything is clear to me, thank you very much again!

With kind regards,
Andreas.

P.S.: However, you might open a different ticket or reuse this one for tracking a feature to add an appropriate message to the user interface which will make this more clear, i.e. by displaying a text like "You need to assign **both** local and remote folder settings to add a new synchronized folder to your profile" or similar. Thanks!

**Comment by AndyScherzinger** [comment]
Happy I could help :) There is already an issue for this matter: #2034 I'll close this one in favor of the existing one

**Comment by amotl** [comment]
Thank you so much and keep up the spirit!

**Comment by AndyScherzinger** [comment]
Happy to help ❤️
