### ISSUE TITLE
Nextcloud isn't listed in android "open from" file selection dialog

### ISSUE THREAD

**Issue by asdil12** [nextcloud/android#2203]
![](https://upload.kruton.de/files/1519073937/nc.png)

The left image shows the correct behaviour on my friends phone,
the right image shows the incorrect bahaviour on my phone.
Both use the same android and nextcloud version and the hardware is identical as well.

### Actual behaviour
- On the right image the nextcloud entry is missing.

### Expected behaviour
- There should be a nextcloud entry on for file selection like on the left image.

### Environment data
Android version: 7.1.1

Device model: Motorola Z Play

Stock or customized system: Stock

Nextcloud app version: 3.0.1

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky @mathiasconradt see this issue, there seems indeed to be some issue with the document provider lately :/

**Comment by mathiasconradt** [comment]
Yep, same as https://github.com/nextcloud/android/issues/2182

**Comment by xXSTrikeXx** [comment]
I want to add that Huawei Y6 2017 also wont work 🗡 
EMUI 4.1
Model: MYA-L41
Build: Maya-L41C432B140
Android 6.0

**Comment by mathiasconradt** [comment]
Maybe there is some different behaviour on different Android systems (i.e. Huawei / EMUI), they way providers or intents are handled. Dropbox and Google Drive apps seem to behave pretty stable on all devices though in this regard. For reference I attach the manifests of both here as well, maybe something can be found in there in comparison.

[GoogleDrive_AndroidManifest.xml.txt](https://github.com/nextcloud/android/files/1739043/GoogleDrive_AndroidManifest.xml.txt)
[Dropbox_AndroidManifest.xml.txt](https://github.com/nextcloud/android/files/1739044/Dropbox_AndroidManifest.xml.txt)

**Comment by AndyScherzinger** [comment]
@mathiasconradt @xXSTrikeXx on the devices where Nc is showing up do you have any files downloaded via Nc and do the other installation don't have any files downloaded? Just asking since there are comments which might suggest it is only showing downloaded files. Just wanting to make sure this isn't the reason for the behavior.

**Comment by tobiasKaminsky** [comment]
I did a few tests with a fresh emulator (Android 7.0)
- first no provider was shown
- restarted a few times, still no provider
- download a file 
- restarted again a few times 
- then out of sudden a provider was shown

I still have no clue, why and when a provider is shown...

**Comment by mathiasconradt** [comment]
@AndyScherzinger I have downloaded files within the NC app on my Huawei Mate 8, where NC is not showing up.

**Comment by tobiasKaminsky** [comment]
Once I had an nullpointer during document provider setup at:
getAppContext().getResources().getString(R.string.account_type) in MainApp.java

This then refuses the provider to work. But I am not sure, how to retrigger starting the provider...

**Comment by mathiasconradt** [comment]
What's causing the NPE there then? Missing app context, resource string? I guess an NPE shouldn't be thrown in the first place though, not?

**Comment by tobiasKaminsky** [comment]
I assume that getAppContext() is somehow null. 
Maybe this is due to some race condition, whereas the app is not yet started (no context available), but something tries to start document provider.

But as said, I had this only once. On other tries there was no exception, but still no provider.

**Comment by xXSTrikeXx** [comment]
@AndyScherzinger 
To clarify that I test now the right actual behavior:
1. Add test account to android. 
2. Go to 'all files'
3. Press + Icon and choose the second one 'content of other apps'
4. Filemanager opens and for me now Nextcloud is now showing up with 2 Accounts. So its working for me.
So the expected behavior is working, but I recognize that now no avatar is loading. For a few days I created a test account and the avatar "T" for user test was showing up correctly. Now after back adding the test account then there is no avatar shown. Thats crazy.....

**Comment by mathiasconradt** [comment]
@xXSTrikeXx Just tried the same on my Huawei Mate 8, created a new account. Still, NC doesn't show when the filepicker menu shows.
(Also noted some Avatar issues today. Avatar only shows of 1 of my 3 accounts).

**Comment by auchri** [comment]
Is there any progress on this issue? It's really annoying to share multiple files to e.g. whatsapp, since whatsapp does only recognise the first image if I try to share multiple images...

**Comment by FredericLespez** [comment]
On my two phones (OnePlus 5T with latest LineageOS and Oneplus 6 with latest OxygenOS) and Nextcloud android 3.6.0, I am still seeing this issue.

**Comment by auchri** [comment]
.

**Comment by FredericLespez** [comment]
On my phones, Nextcloud wasn't listed in android "open from" file selection dialog because I enabled the Nextcloud PIN access feature in the Android client. See tobiasKaminsky comment in this issue:
https://github.com/nextcloud/android/issues/2182#issuecomment-491226819

**Comment by sunjam** [comment]
Same issue on Mi 9T.  Please re-open

**Comment by RoL0NL** [comment]
Same on Pixel 6a
