### ISSUE TITLE
Combine Move and Copy in menu

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/android#2212]
Just like in the server, we should have a single entry "Move or copy".

For that the current move/copy view just needs to be minimally adjusted:

- In the root view, header should have an "x" in the top left to cancel operation
- Header text in root view should be "Move <filename>" (not enough space to include "copy" here)
- Primary blue button on right should say "Move here", secondary grey left button " Copy".

cc @nextcloud/android

**Comment by tobiasKaminsky** [comment]
> In the root view, header should have an "x" in the top left to cancel operation

At least for me this is very uncommon in android. Also as this is no dialog it additionally would look/feel strange, I think.

> Header text in root view should be "Move " (not enough space to include "copy" here)

This will depend heavily on screen size and language. On a recent (full hd) phone English might work with "Move/copy", but German "Verschieben/Kopieren" might not. But saying only move might confuse the user. 
Maybe we find something more generic? Android will try to fit text in and if not trim it at the end, so I would then keep it this way.

**Comment by jancborchardt** [comment]
@tobiasKaminsky what do you suggest for canceling then? 3rd button on the bottom seems to not have space.

About the header, we could also use the filename? And even if the header text is »Move or copy« and is ellipsized on smaller screens, that is absolutely ok.

**Comment by tobiasKaminsky** [comment]
I would try to use move/copy, with ellipzsizing, so that at least user see that it not only "move", but, e.g. "move/...".

3rd button or file name is not needed in my opinion.

**Comment by jancborchardt** [comment]
Ok, so cancel via hardware/main back button then? What would be in the top left then though – a filetype icon / preview of the file being moved?

**Comment by tobiasKaminsky** [comment]
This is our current copy screen:

![2018-03-20-164546](https://user-images.githubusercontent.com/5836855/37665716-2d4947f0-2c5e-11e8-8db8-72a94b8009d1.png)

Hardware back button and top left back arrow is used to navigate up, or if in root, to close.
If we replace "close" with copy, then we would not have any possibility to close this dialog, when in any subfolder, as then the use would have to navigate back up to root (via back button/arrow).
Having a closeable dialog with an "x" in top right, as on desktop/web ui is very very uncommon on android.


Amaze is doing it in a different way:
- once you select a file for copy/move you see a paste icon in top bar
- then go to desired folder 
- click paste

![2018-03-20-165225](https://user-images.githubusercontent.com/5836855/37666173-30e309ae-2c5f-11e8-9043-406a544338b2.png)

Another idea would be this:
![2018-03-20-170058](https://user-images.githubusercontent.com/5836855/37666631-4e57e09e-2c60-11e8-902c-d3a8b1c701df.png)
With this the user always has to click on it and then choose copy/move.

**Comment by jancborchardt** [comment]
This is how we do it in server (moved from the other issue):
Menu | Dialog
-|-
![image](https://user-images.githubusercontent.com/5836855/32429134-8cb8947e-c2c9-11e7-8d5a-70a64164408e.png)|![image](https://user-images.githubusercontent.com/5836855/32429160-aafdcc10-c2c9-11e7-9aaf-b3645d801ed2.png)

**Comment by tobiasKaminsky** [comment]
We would add "cancel" on lower left side? As "x" like on web is not common on Android.

**Comment by AlvaroBrey** [comment]
AOSP file browser has separate "copy to" and "move to" options, just as a data point.

**Comment by AlvaroBrey** [comment]
Another option for the UX flow: keep the existing "choose folder" view, but _after_ the folder is chosen ask in a dialog whether to copy or move. This is what KDE does when dragging a file to a folder, for example.

**Comment by comradekingu** [comment]
How about just "Move here" or "Copy here" as options once something is "copied or cut".
Bonus points for showing striked outline versions in the folder the user navigates to.

**Comment by alperozturk96** [comment]
Here is Google Drive behaviour

https://github.com/nextcloud/android/assets/67455295/31e765fb-ce22-4253-829a-717d342d7f2e

I recommend simplifying the user interface by eliminating any icons (such as share or link) positioned alongside the more icon at the end of each file. Instead, we can make these options accessible when a user long-presses any file. During a long press, a top bar will appear displaying the three most common two actions: Copy or Move, and More, represented by icons.

Once the user selects an action, they will be presented with two options at the bottom bar: Cancel and the chosen action. This design aligns with Material Design principles.

For example, when the user selects "Copy or More," from topbar, the bottom bar will show the options "Cancel," "Copy," and "Move."

@tobiasKaminsky

**Comment by tobiasKaminsky** [comment]
Long press is currently used for multi-select and I do not like to "hide" such an important function to a rather unknown gesture.

**Comment by alperozturk96** [comment]
Current Behaviour

https://github.com/nextcloud/android/assets/67455295/b3ab676f-df4f-47cd-b6ca-86493c7f5af7

Actually in current behaviour of app you can't access top bar actions without long press in other way already hidden function. We can add frequently used one more action(copy or move) in top bar and bottom bar will have "Cancel", "Copy", "Move" rather than "Cancel", "Choose" just like our web app so that we can preserve our cross-platform design language.
