### ISSUE TITLE
Remove "Select all" from the 3-dot-menu as that's already in the multiselect menu

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/android#2213]
When there's no file selected, we don't need "Select all" in the 3-dot-menu.

**Comment by tobiasKaminsky** [comment]
It is a short to select all ;-)
It will automatically enable multi-select mode and select all files.

I am unsure if this is important enough to keep it, but technically it is working ;-)

**Comment by tanvidadu** [comment]
I can work on this issue. It would help me get familiarized with the code base a little.

**Comment by tanvidadu** [comment]
I can start working on this issue. it will help me get familiarized with code base.

**Comment by tobiasKaminsky** [comment]
Great that you want to help us :+1: 
If you have any question @tanvidadu, please do not hesitate to ask, either in this issue or on #nextcloud-mobile on irc.
