### ISSUE TITLE
Activity icons are much too large

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/android#2215]
The icons on the left here should not be so big:
![](https://i.imgur.com/NZ7Pwin.png)

Instead, they need to have the same size as the action icons in the header or file list. (The text alignment is good though, left-aligned with the title.)

**Comment by AndyScherzinger** [comment]
PR is #2217

Is this fine by you size-wise @jancborchardt?
![device-2018-02-21-232331](https://user-images.githubusercontent.com/1315170/36509043-a076b77c-175e-11e8-8dae-532fc98c1b59.png)
