### ISSUE TITLE
Activity date dividers design

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/android#2216]
Currently the date dividers are a bit lost in the list:
![](https://i.imgur.com/YuFeay2.png)

2 things to improve:
- Add whitespace above them, around the height of one row of a normal entry.
- Make the header sticky when scrolling (alternatively: show the "5 days ago" instead of the header, or as a subheader)

**Comment by AndyScherzinger** [comment]
Thus not like the web UI?
![2018-02-21 23_32_16-activity - cloudbox](https://user-images.githubusercontent.com/1315170/36509315-90eef188-175f-11e8-9f31-62d980dee2fb.png)

**Comment by tanvidadu** [comment]
Is this issue up for grabs ? I will like to work on it . Thanks :)

**Comment by AndyScherzinger** [comment]
Hi @tanvidadu and welcome!

Yes, this issue is up for grabs. If you need any help, have any questions please feel free to ask. 
@tobiasKaminsky @mario and me are here to help :)

**Comment by jancborchardt** [comment]
@AndyScherzinger:the whitespace is like in the web interface. The stickiness or setting it as subheading helps further. :)

**Comment by AndyScherzinger** [comment]
> the whitespace is like in the web interface. The stickiness or setting it as subheading helps further.

None of what you suggest here or in the original description makes even remotely sense to me.
However is up for the task, feel free

**Comment by jancborchardt** [comment]
I'm talking about the "Tuesday, February 13" date heading in my original screenshot. It has insufficient whitespace above and below the text.

Should be around double the whitespace to the bottom and 4 times the whitespace to the top. As said, compare to the web interface of Activity where the whitespace/margin is proper. :)

**Comment by AndyScherzinger** [comment]
Okay, I do understand the whitespace/stickyness part for the headline which makes absolute sense while I don't understand the changes for the item time-info (if any of your description is related to that, not sure anymore). As for the headlines we do you 3 days ago, 6 days ago etc. while we jump to the "Tuesday, February 13" format if the items is further back in time:
![device-2018-04-09-101137](https://user-images.githubusercontent.com/1315170/38486837-7f082928-3bde-11e8-9983-16ed72c91b02.png)

So just to be save: Does this issue have any impact on the "time/HH:mm Subheading"?

**Comment by jancborchardt** [comment]
@AndyScherzinger I already thought you might think I'm talking about the time info (hh:mm) and no – this issue is only about the day/date heading. Sorry for the confusing wording. :)

**Comment by AlexNi245** [comment]
@AndyScherzinger @tobiasKaminsky   is there still work to do on that issue? If i understood the discussion correctly the day/date heading should stick to the top while the user scrolls down. Also the whitespace arround the date heading should be increased.
I would work at this issue if you are fine with that :)

**Comment by AndyScherzinger** [comment]
@AlexNi245 absolutely yes ❤️ First step would be to make the headers sticky and then work on the whitespace afterwards.

**Comment by jancborchardt** [comment]
As mentioned in https://github.com/nextcloud/android/pull/4294#issuecomment-522491228

> With things like "Recommendations" coming in, and Favorites not being separated visually except for their indicator yet, we could also think about introducing headers like that for those. Not saying we have to, just thinking aloud. :)

**Comment by tobiasKaminsky** [comment]
@jancborchardt this is also not the correct issue, as this will be closed once the PR is merged.
I meant that you should post your idea into the "recommendations" or "Favorites not being separated" issue.
Not sure what they both are about to be honest. 
If there is no such issue right now, please then open up individual ones (as I doubt they are related).
