### ISSUE TITLE
Remove "change password" 

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#2229]
Change password is currently changing only the password with which the app authenticates to the server.
If this password is not valid anylonger, e.g. when the auth token is revoked, the user gets the Authenticator/Login screen presented. So this is all fine.

Currently when clicking on "change password" this just opens up AuthenticatorActivity / Weblogin flow, which can change the internal stored password, but as seen above, this is useless.
A real password changing is only possible via webUI and should only be done there, especially if other user backends are handled there.

Therefore I suggest to remove the "change password" option.

**Comment by AndyScherzinger** [comment]
Nice catch for UX :+1:

**Comment by AndyScherzinger** [comment]
PR is #2433

**Comment by influenist** [comment]
Can anyone explain why this option has been removed? I now am not able to update the login credentials since the android app does not recognise the credentials have been changed server side ...

**Comment by tobiasKaminsky** [comment]
"Change password" was to change the password of the whole account (similar like you do it within web).
As it used a different api, it could create conflicts when using LDAP, therefore it was removed.

For your problem: ideally you use weblogin flow which creates an app token. The app token remains valid even when you change your password.
