### ISSUE TITLE
External Storage Folder not Visible

### ISSUE THREAD

**Issue by chrisueb** [nextcloud/android#2232]
Hello,
In der new Android App, i can't find the SMB External Storages.
In the old Version works the External Storage Folders.
Thx

**Comment by tobiasKaminsky** [comment]
This is strange, as we did not changed that, we rely on the results from server.
Did you also upgraded the server?

Can you create us a test account, test if the problem occurs also there and if so 
send the credentials to android at nextcloud dot com with a reference to this issue?

**Comment by zepolam** [comment]
Hello, i have the same problem.
I can't view the SMB external storage connected (Netapp CIFS share) using the Android APP

With web browser can view without problems.

Nextcloud Server version: 13.0.0
App version: 3.0.3

Thanks.

**Comment by kuhlmannmarkus** [comment]
@barttjer I can confirm your observation!

**Comment by tobiasKaminsky** [comment]
@nextcloud/server-triage is this something known, which can be addressed by better documentation?

**Comment by blizzz** [comment]
Imho, this should not matter for this scenario, as the password should be set anyway in the session. After all, you authenticate via app. @chrisueb  did your master password change recently?
