### ISSUE TITLE
Error message is not shown completely and not fully understandable

### ISSUE THREAD

**Issue by avanc** [nextcloud/android#2236]
### Actual behaviour
- Open Nextcloud App
- Go to "Benachrichtigungen" (Notifications?)
- Note is shown: 

> Keine Push Benachrichtigungen aufgrund veralteter Benutzersitzung. Bitte erwägen Sie das erneute Hinzufügen Ihres Kontos.
https://github.com/nextcloud/android/blob/1e5924d611a69bbe8b17dd54d1b09449c215bf29/src/main/res/values-de-rDE/strings.xml#L658

- However, the text is not fully visible on the screen. Only in Landscape Mode.
- In addition, some further information would be helpful. Do I really have to remove the account on my device? This means, I have to download all the offline content again. Maybe a Link to a webpage would be sufficient.

### Expected behaviour
- Push notifications should work.
 
### Steps to reproduce
1. Open Nextcloud App
2. Go to "Benachrichtigungen" (Notifications?)

### Environment data
Android version:

Device model: 
Nexus 5x

Stock or customized system:
Stock

Nextcloud app version:
3.0.1
Nextcloud server version:
13.0.0

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky I think this needs a fix in transifex translations while I can't exactly say what it should say then. Any ideas?

**Comment by tobiasKaminsky** [comment]
The text is indeed to long, but also have no idea how to get it shorter...

**Comment by avanc** [comment]
But do I really have to delete my account on that device and start from scratch?

**Comment by tobiasKaminsky** [comment]
If you want to have push notifications, then yes.
The reason for this is that you need a new authentication token created by the new weblogin flow. Only with this you have a unique id and can receive notifications.

If you do not need push notifications you can still open up "notifications" on drawer and see the recent ones.

**Comment by avanc** [comment]
I removed the account an started over again. But I get the message again. Do I have to do something special while signing in? Or some configuration on the backend needed ?

**Comment by tobiasKaminsky** [comment]
On login you see the "new login" with "grant access"? Or can you directly type username/password in?

**Comment by avanc** [comment]
Yes, I got the grant access (Zugriff gewähren) dialog.
But I didn't select the Option talking about app token.

**Comment by gueniewie** [comment]
But whath is the way to configure correct, have I do delete my LDAP Users (?) all other I have tested the Error message are still here
