### ISSUE TITLE
Only show empty content message when there really is nothing in there

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/android#224]
Oftentimes when a folder is loading, the »Nothing in here« message already shows. This gives the impression of files being missing, which is not correct and actually a bit frightening.

We should only ever show the »Nothing in here« message if there absolutely is nothing in there. Until that it’s loading state.

Also, with the »Loading …« state there should also be the spinner shown for more feedback. :) Just like on the web interface. Similarly, the empty content notice should get a folder icon above it so it looks nicer. Again, copy it from the web interface. :)

**Comment by AndyScherzinger** [comment]
@jancborchardt makes sense except for the spinner, since that is already shown in the action bar :) so I would now add another "moving thing" :wink:

**Comment by AndyScherzinger** [comment]
Adding to the importance of this UX matter, the comment from @Bugsbane in the forum

> I'm getting a minor issue where often when the app is loading the contents of a large direcory, it will say "loading..." and then "No contents found" only to then show the contents of the folder a few seconds later. Not sure if this is expected behaviour or not...

**Comment by Bugsbane** [comment]
> This gives the impression of files being missing, which is not correct and actually a bit frightening.

I second this. There's a brief moment where you wonder if all of your files have been deleted.... o.O

**Comment by AndyScherzinger** [comment]
cc @tobiasKaminsky without having looked into the code I think the empty-list text should be the easy part, the refresh then showing the list with its items is taking some time for large folders is due to the usage of listview and not yet using the recyclerview imlpementation which will need quite some refactoring. That is something we tried again some time ago as a joint venture qith @skymania but due to the feature pushed we has since June we most likely have do redo it or resolve a lot of conflicts on the branch. Other than that it'll need quite some testing since we change a lot of UI related code...

**Comment by jancborchardt** [comment]
Looks like this issue still persists.

**Comment by AndyScherzinger** [comment]
Correct, we haven't started working on it yet

**Comment by tobiasKaminsky** [comment]
My idea is:
- upon on receiving folder/file list we get also an info about folder size
- if we go into one folder, where we know it is >0, then do not show "empty message", but "loading" or "spinner".
@jancborchardt what do you prefer?

**Comment by jancborchardt** [comment]
Seems good! And yes, just already showing the "Loading …" with spinner is good.

Just let’s make sure there’s no flash of a screen essentially saying "All your files are gone". ;)

**Comment by tobiasKaminsky** [comment]
Please test: https://github.com/nextcloud/android/pull/5754#issuecomment-605057847

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger @jancborchardt can you test this please? ❤️

**Comment by AndyScherzinger** [comment]
Apk link is a 404
