### ISSUE TITLE
[regression v3] Upload: Files that are not found anymore have wrong error "Waiting for WiFi"

### ISSUE THREAD

**Issue by leandro-lucarella-sociomantic** [nextcloud/android#2241]
### Actual behaviour
I have auto-upload for camera pictures and I have the upload only enabled on WiFi.
When I take a picture and I don't like and I remove it before the WiFi was available (so the picture is not uploaded yet), then after the WiFi is available the file is wrongly marked as failed with reason "Waiting for WiFi".

### Expected behaviour
The error shouold be "Local file not found" instead, as it was before v3.
 
### Steps to reproduce
1. Set auto-upload for pictures
2. Set to only upload on WiFi
3. Disable WiFi
4. Take picture
5. Remove picture
6. Connect WiFi

### Environment data
Android version: 7.0

Device model: LG G6 EU (H870)

Stock or customized system: Stock

Nextcloud app version: 3.0.1

Nextcloud server version: 12.0.5

### Logs

I don't think it's relevant, but if you ask for any particular log I can paste some log lines.

**Comment by mario** [comment]
This is because it's never retried so it's not given a chance to update the status.

**Comment by mario** [comment]
I hopefully have a fix here: https://github.com/nextcloud/android/pull/2254
