### ISSUE TITLE
It seems that the search results are incorrect

### ISSUE THREAD

**Issue by dxj728** [nextcloud/android#2244]
### Actual behaviour
When you click on the upload on your phone, there is a search option in the pop-up screen, but when you search for a file or a strange character, it gets the results, but it's not correct.

### Expected behaviour
Get the right results
 
### Steps to reproduce
1. Click on the main interface to upload the file
2. Click search in the open screen and search for a non-existent file
3. But got the wrong result.

This version doesn't matter; the problem persists

### Environment data
Android version:  android 5.1.1

Device model:  Nexus5

Stock or customized system:

Nextcloud app version:  v3.0.1

Nextcloud server version: 12.0.0

**Comment by tobiasKaminsky** [comment]
I tried it and I guess it tries to get the closest possible result, which is still wrong, but maybe explain why and which files are presented...

**Comment by dxj728** [comment]
@tobiasKaminsky Will you fix the problem? After all, it was wrong.

**Comment by tobiasKaminsky** [comment]
Yes, this will be fixed, but I cannot estimate when as it is not a high rated bug.
