### ISSUE TITLE
App 3.0.2 bug on file deletion with e2e and server-side encryption enabled

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/android#2246]
nextcloud application 3.0.2 with server-side encryption and active encryption and 2e does not allow you to delete files in unencrypted folders. we can upload files but do not delete them

![screenshot_20180227-215309](https://user-images.githubusercontent.com/35575744/36754232-ba06072a-1c08-11e8-95ee-006d5f4d7b50.png)

![screenshot_20180227-215319](https://user-images.githubusercontent.com/35575744/36754247-c322a016-1c08-11e8-8099-c8933a7738a4.png)

**Comment by tigernero79** [comment]
I had to disable e2e again because with the server-side encryption enabled and with e2e running via nextcloud 3.0.2 it is not possible to remove files in unencrypted folders. this is serious.

**Comment by AndyScherzinger** [comment]
cc @tobiasKaminsky for e2e implementation :)

**Comment by tigernero79** [comment]
the proletariat is Poe on normal folders not e2e where I can not delete files but only uplodate. while electronic folders e2e can delete files is uplodate. the problem is either in normal folders when both server-side and client-side e2e encryption is enabled

**Comment by tobiasKaminsky** [comment]
I tried it on my NC13 test server with both enabled server side (SSE) and client side encryption (E2E):
- upload a file to a normal folder -> content is encrypted (SSE)
- delete this file worked without a problem
- upload a file to an E2E folder -> complete file is encrypted
- delete this file worked without a problem

I remember you gave us test credentials. Can you test if this problem also occurs there? Then I'll have a look.

**Comment by tigernero79** [comment]
User=tobias
Psw= send to android@nextcloud.com

URL= https://www.pensierando.it/Nextcloud

**Comment by tigernero79** [comment]
@tobiasKaminsky 
OCA\DAV\Connector\Sabre\Exception\Forbidden: client not allowed to access end-to-end encrypted content
/web/htdocs/www.pensierando.it/home/Nextcloud/apps/end_to_end_encryption/lib/Connector/Sabre/LockPlugin.php - line 124: OCA\EndToEndEncryption\Connector\Sabre\LockPlugin->checkUserAgent('Mozilla/5.0 (An...', '/Test/andftp.xm...')
[internal function] OCA\EndToEndEncryption\Connector\Sabre\LockPlugin->checkLock(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
/web/htdocs/www.pensierando.it/home/Nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)

![screenshot_20180228-074057](https://user-images.githubusercontent.com/35575744/36773642-e0fdea30-1c5a-11e8-8995-8092b81cad86.png)

**Comment by tigernero79** [comment]
@tobiasKaminsky 

in your nextcloud to test the server-side encryption voice in addition to enable it you also checked the square that encrypts the main archive? because I have it enabled

**Comment by tigernero79** [comment]
I updated the e2e module to the 1.0.4 release and I solved the problem
