### ISSUE TITLE
Still have write permission to E2E folder problem, after upgrade android client to 3.0.2

### ISSUE THREAD

**Issue by johnwmail** [nextcloud/android#2247]
### Actual behaviour
-Tell us what happens
Upload file to E2E folder, then nextcloud show error message: forbidden
### Expected behaviour
-Tell us what should happen
 Success to upload file to E2E folder
### Steps to reproduce
1. encrypt E2E folder with "E2E encryption"
2. upload file to E2E folder
3. nextcloud show error message: forbidden

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:
Android 3.0.2
Nextcloud server version:
Debian, nginx, php7.2, redis
#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
#7 {main}\",\"File\":\"\\\/var\\\/www\\\/apps\\\/end_to_end_encryption\\\/lib\\\/Connector\\\/Sabre\\\/LockPlugin.php\",\"Line\":169}","userAgent":"Mozilla\/5.0 (Android) ownCloud-android\/3.0.2","version":"13.0.0.14"}

```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by johnwmail** [comment]
My nextcloud End-to-End Encryption apps is show me version 1.0.2,
and https://apps.nextcloud.com/apps/end_to_end_encryption show us,
then last version is 1.0.2, but when I click the link,
I actually downloaing end_to_end_encryption-1.0.3.tar.gz

So, what is the last update to date, end_to_end_encryption release version?
1.0.2 or 1.0.3?   or both is the same?
Thanks

**Comment by AndyScherzinger** [comment]
cc @tobiasKaminsky for e2e

**Comment by tigernero79** [comment]
I updated the e2e module to the 1.0.4 release and I solved the problem

**Comment by johnwmail** [comment]
After upgrade e2e app to 1.0.4, I still have problem, the nextcloud.log show us.

#7 {main}\",\"File\":\"\\\/var\\\/www\\\/apps\\\/end_to_end_encryption\\\/lib\\\/Connector\\\/Sabre\\\/LockPlugin.php\",\"Line\":170}","userAgent":"Mozilla\/5.0 (Android) ownCloud-android\/3.0.2","version":"13.0.0.14"}

**Comment by tigernero79** [comment]
what's your problem now? it seems you simply have locked files. 
to avoid this, insert the entry 
`'filelocking.enabled' => false`
in the config.txt file and delete the files in question. 
if the file is in an e2e folder, 
remove the encryption before deleting the file. 
done this eliminates the entry from the config.txt file

**Comment by johnwmail** [comment]
@tigernero79
What are you talking about?
Where is config.txt?
Why do you think, it is file locking problem?
I don't think so.

**Comment by tigernero79** [comment]
Directory Nextcloud/configurazioni/configurazioni.txt

Edit this file, insert the entry

Test

**Comment by johnwmail** [comment]
No, same error message
No matter 'filelocking.enabled' => false or true.

Again, why do you think this?

**Comment by tigernero79** [comment]
for this error

/ Saber \ /LockPlugin.php

try on terminal digit

`sudo chown -R www-data:www-data /var/www/nextcloud`


where / var / www / Nextcloud you need to set the directory of your nextcloud

**Comment by johnwmail** [comment]
@tigernero79

#7 {main}","File":"\/var\/www\/apps\/end_to_end_encryption\/lib\/Connector\/Sabre\/LockPlugin.php","Line":170}","userAgent":"Mozilla/5.0 (Android) ownCloud-android/3.0.2","version":"13.0.0.14"}

Please read / Saber \ /LockPlugin.php line170

The problem is useragent

**Comment by tobiasKaminsky** [comment]
@tigernero79 you are mixing things up and thus this cannot help:
LockPlugin has nothing to do with filelocking although the name suggests this.
Filelocking is a global server concept, whereas LockPlugin is only for E2E. On upload the target directory gets first locked so that no-other can write into it, until the client uploaded file and metadata and unlocked the folder.

Changing chown should also not be needed.

**Comment by tobiasKaminsky** [comment]
Indeed @johnwmail, the problem is again useragent, while I do not get this...All E2E related calls are with new user agent...

**Comment by johnwmail** [comment]
Any idea, how to fix it?

**Comment by Micha-Btz** [comment]
I have this too with NC 13.0.3 and android app 3.2.0.
