### ISSUE TITLE
Sharing: app icons are not sized equally

### ISSUE THREAD

**Issue by karottenbaum** [nextcloud/android#2248]
### Actual behaviour
The app icons in the sharing menu are not equally sized, instead they are displayed in their original size.
2 screenshots:
![screenshot_20180228-110941](https://user-images.githubusercontent.com/6024426/36782507-75877680-1c79-11e8-84c0-65b8731be35c.png)
![screenshot_20180228-112346](https://user-images.githubusercontent.com/6024426/36782710-0c33b1ac-1c7a-11e8-8046-f19d02339961.png)

### Expected behaviour
The app icons in the sharing menu should be equally sized.
 
### Steps to reproduce
1. Click 'Share' icon on any file

### Environment data
Android version: 8.1.0

Device model: Google Pixel 2

Stock or customized system: stock

Nextcloud app version: 3.0.1

Nextcloud server version: 13.0.0

### Logs
 (n/a)

**Comment by tobiasKaminsky** [comment]
This needs to be fixed for next release.
If anyone wants to pick it up, please feel free.
Otherwise I'll do it close to feature freeze.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky I am not even sure what the correct size is. Looking at Twitter and Tumbler they are the same and both ship the Android 8 defined launcher icon sizes. But yeah should probably be smaller for the moment but we might have to enlarge it again at a later point in time in case more apps support Android 8 icons.

**Comment by tobiasKaminsky** [comment]
Without looking at the code, I assume that a defined size is missing, e.g. 32dp.

**Comment by xXSTrikeXx** [comment]
I will look into it and try my best ;)

**Comment by xXSTrikeXx** [comment]
@tobiasKaminsky
Can you explain me how the images are set there without an "<ImageView/>"
The library for that is still there, but never declared. I waysted a lot of time (confused about the 2nd system share layout [pr exist] and the missing ImageView, but the library is -loading for some reason and its unnecessary in the code) on friday.
Maybe you can give me a hint and I can learn more about android ;)
