### ISSUE TITLE
No instant Upload under android 7

### ISSUE THREAD

**Issue by niceyyy** [nextcloud/android#225]
### Actual behaviour
Instant Upload Feature does not work with Android N (7)
It seems that the app don't recognize new fotos/videos 

### Environment data
Android version: 7.0

Device model: Nexus 5X
Stock or customized system: Stock
Nextcloud app version: 1.2.0
Nextcloud server version: 10.0 beta

### Logs
nothing to see in the logfiles.

**Comment by xraMsamohT** [comment]
Duplicate of #110

**Comment by AndyScherzinger** [comment]
thus closed. Please track any progress in #110.
