### ISSUE TITLE
'Locked' error after uploading files to e2e folder

### ISSUE THREAD

**Issue by sysoppl** [nextcloud/android#2256]
### Actual behaviour
- After uploading some files (about 15) into e2e encrypted folder it shows up 'Locked' error

I cannot:
 - reupload files that failed to upload (locked error)
 - open uploaded files (they're showing as encrypted or something, picture 1)
 - upload new files to the folder (locked error)
 - delete files (server is unavailable error)

When I try to open/delete files I get "this file is no longer available on the server"
Picture 1:
![inkedscreenshot_20180228-172615_li](https://user-images.githubusercontent.com/30871217/36799370-54250e74-1cad-11e8-842c-84dad4f47d38.jpg)

Server error:
![e1](https://user-images.githubusercontent.com/30871217/36799598-d4d85940-1cad-11e8-8bf9-4618347d1dc5.png)

Even changing 'filelocking.enabled' => false, doesnt help in this case.

**Tried on second folder now, new files, same issue**

### Expected behaviour
- Remove error (?), ability to upload, open files
 
### Steps to reproduce
1. Start uploading files to e2e folder
2. Some files failed to upload with 'locked' error in app
3. Cannot do much in this folder anymore

### Environment data
Android version: 7.1 g3s / 6 tab2

Device model: Uploaded on galaxy tab 2, tried to open on tab2 & lg g3s, tried to upload new files on tab2

Stock or customized system: customized,  lineage

Nextcloud app version: 3.0.2

Nextcloud server version: 13
External storage (ostack)
Tried on internal - same error

E2e version: 1.0.4

**Comment by vincentadultman** [comment]
I'm aware the E2E features are currently in technology preview but is there any further information that can be provided by those of us experiencing this problem that would be of use to you? This is also happening to me using the nextcloud snap and a fully updated Nexus 5x

**Comment by tobiasKaminsky** [comment]
Is this always happening when you use a bunch of files?
Does this also happen when you do the file operation one by one?

**Comment by sysoppl** [comment]
Yeah, I just upload one by one ~25 files, everything was ok, no errors (I already thought the problem is fixed), but when I refreshed it shows something like picture 1 in my first post. After that, I cannot upload more files.
