### ISSUE TITLE
Nextcloud App Download Error F-Droid

### ISSUE THREAD

**Issue by sethc432** [nextcloud/android#2259]
### Actual behaviour
Displays message "The requested file was not found. https://f-droid.org/repo/com.nextcloud.client_20000199.apk"

### Expected behaviour
The app should be downloaded and installed.
 
### Steps to reproduce
1. Use Copperhead OS OPM3.171019.014.2018.02.18.00
2. Use F-Droid 1.0.2
3. Install Nextcloud App (non-dev)

### Environment data
Android version:8.1.0

Device model: Huwaei Nexus 6P

Stock or customized system: Custom Copperhead OS

Nextcloud app version:2.0.1

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Fdroid seems to have only the latest 3 versions:
3.0.1
3.0.0
3.0.0RC3

For every other fdroid related question, please open up a ticket on froid.
