### ISSUE TITLE
Integrate Code Quality Checks

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#226]
Integrate certain typical code quality measurement tools, as described here: http://vincentbrison.com/2014/07/19/how-to-improve-quality-and-syntax-of-your-android-code/ and corresponding sample project https://github.com/vincentbrison/vb-android-app-quality

which basically means adding checkstyle, pmd, findbugs, etc. to the build. 

What do you think @nextcloud/android ?

**Comment by Serverfrog** [comment]
I will try to add these things and create a Pull Request. This would be my first time i add something via Github so please bear with with ;)

**Comment by AndyScherzinger** [comment]
No worries @Serverfrog! We are here to help, so if you have any questions or issues don't hesitate to ask :smiley: and also thanks in advance for your contribution!

**Comment by tobiasKaminsky** [comment]
Great, welcome onboard :+1: 
If you need "quicker" help you can also join #nextcloud-mobile on irc.

**Comment by djubreel** [comment]
Hello @AndyScherzinger  is this still open? could I work on it? is it under hacktoberfest?

**Comment by AndyScherzinger** [comment]
Hi @djubreel it is still open and I now flagged it as hacktoberfest - what I don't know though is if the issue or just the PR can't be created before 1st October.

**Comment by djubreel** [comment]
@AndyScherzinger Okay,I'd start work on it

**Comment by AndyScherzinger** [comment]
@djubreel just to be sasve with the starting dates I closed this issue and opened the exact same one again --> #310
