### ISSUE TITLE
Too many queries in the background?

### ISSUE THREAD

**Issue by okaestne** [nextcloud/android#2263]
### Actual behaviour

The app fires so many queries to the status.php and /index.php/204 that my apache's mod_evasive blocks it. This happens in the background, when the app isn't in use, even at nights. ~BUT this only seems to happen when my smartphone is connected via cellular networks, NOT when connected via WLAN.~

### Expected behaviour
- Less queries
 
### Steps to reproduce
1. Connect smartphone ~via cellular network (LTE, HSDPA)~
2. Let app run in background

### Environment data
Android version: 7.1.2

Device model: Oneplus One

Stock or customized system: Custom: Lineage OS (Sultanxda)

Nextcloud app version: 3.0.2

Nextcloud server version: 13.0.0.14

#### Access log:

	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:30:58 +0100] "GET /status.php HTTP/1.1" 200 4616 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:30:58 +0100] "GET /status.php HTTP/1.1" 200 4616 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:30:58 +0100] "GET /status.php HTTP/1.1" 200 1635 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:30:58 +0100] "GET /status.php HTTP/1.1" 200 1637 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:31:00 +0100] "GET /status.php HTTP/1.1" 200 1631 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:31:01 +0100] "GET /status.php HTTP/1.1" 200 1633 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:31:01 +0100] "GET /status.php HTTP/1.1" 200 1627 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:31:01 +0100] "GET /status.php HTTP/1.1" 200 1631 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:31:01 +0100] "GET /status.php HTTP/1.1" 200 1627 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:31:01 +0100] "GET /status.php HTTP/1.1" 200 4610 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:31:01 +0100] "GET /status.php HTTP/1.1" 200 4614 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:31:01 +0100] "GET /status.php HTTP/1.1" 200 4616 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:31:01 +0100] "GET /status.php HTTP/1.1" 302 1578 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:31:01 +0100] "GET /status.php HTTP/1.1" 200 1631 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:31:01 +0100] "GET /status.php HTTP/1.1" 200 1629 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:31:01 +0100] "GET /status.php HTTP/1.1" 302 1572 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:31:01 +0100] "GET /status.php HTTP/1.1" 200 1631 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:31:01 +0100] "GET /status.php HTTP/1.1" 302 1574 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:31:01 +0100] "GET /status.php HTTP/1.1" 302 1574 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:31:01 +0100] "GET /status.php HTTP/1.1" 200 1633 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:31:01 +0100] "GET /index.php/apps/files/ HTTP/1.1" 200 40332 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:31:01 +0100] "GET /index.php/apps/files/ HTTP/1.1" 200 40338 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:31:01 +0100] "GET /status.php HTTP/1.1" 302 1580 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:31:01 +0100] "GET /status.php HTTP/1.1" 302 1568 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:31:02 +0100] "GET /status.php HTTP/1.1" 200 1629 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:31:01 +0100] "GET /index.php/apps/files/ HTTP/1.1" 200 40330 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:31:02 +0100] "GET /status.php HTTP/1.1" 302 1574 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:31:02 +0100] "GET /index.php/apps/files/ HTTP/1.1" 200 40338 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:31:02 +0100] "GET /status.php HTTP/1.1" 200 1631 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:31:02 +0100] "GET /index.php/apps/files/ HTTP/1.1" 200 40340 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:31:02 +0100] "GET /index.php/apps/files/ HTTP/1.1" 200 40330 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:31:02 +0100] "GET /index.php/apps/files/ HTTP/1.1" 200 40334 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"

#### Nextcloud log (data/nextcloud.log)
 ( only some Trusted domain errors in this timeframe)

### EDIT: 
Sometimes it's status.php, some times index.php

### EDIT2: 
nvmd, affects WLAN networks as well, just less often.

### EDIT3: 
screw this issue report, now it's only /index.php/204

**Comment by tobiasKaminsky** [comment]
204 is used on newer server versions.

In general, we should think if we can enhance this.
Checking the connection state is only needed if 
- connection changed
- first start

So maybe it is possible to keep track of the current state globally and access the info prior network usage?

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky @2green2freak so what to do with this report then?

**Comment by 2green2freak** [comment]
I re-checked this now for 48h using a package capturing app and my server logs. 
It seems like it doesn't happen anymore since 3.1.0 RC1/2. There are only some requests every few minutes and also only two requests to /index.php/204 at most.
So from my side this seems to be fixed now. So shall I close this or do you still want to discuss something?

**Comment by 2green2freak** [comment]
Here a sample from today: maybe still quite frequent (~same as desktop sync client), but not as much as when I opened the issue.

	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:00:02:46 +0200] "GET /index.php/204 HTTP/1.1" 204 4342 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:00:02:46 +0200] "GET /index.php/204 HTTP/1.1" 204 1351 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:00:03:53 +0200] "GET /index.php/204 HTTP/1.1" 204 1494 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:00:03:53 +0200] "GET /index.php/204 HTTP/1.1" 204 1504 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:00:03:54 +0200] "GET /index.php/204 HTTP/1.1" 204 1349 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:00:03:54 +0200] "GET /index.php/204 HTTP/1.1" 204 1353 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:00:08:07 +0200] "GET /index.php/204 HTTP/1.1" 204 4342 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:00:08:07 +0200] "GET /index.php/204 HTTP/1.1" 204 4336 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:00:08:07 +0200] "GET /index.php/204 HTTP/1.1" 204 4342 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:00:08:07 +0200] "GET /index.php/204 HTTP/1.1" 204 4340 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:00:08:07 +0200] "GET /index.php/204 HTTP/1.1" 204 1496 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:00:08:07 +0200] "GET /index.php/204 HTTP/1.1" 204 1359 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:00:08:07 +0200] "GET /index.php/204 HTTP/1.1" 204 1355 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:00:17:23 +0200] "GET /index.php/204 HTTP/1.1" 204 4340 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:00:17:23 +0200] "GET /index.php/204 HTTP/1.1" 204 4338 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:00:17:23 +0200] "GET /index.php/204 HTTP/1.1" 204 4348 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:00:17:23 +0200] "GET /index.php/204 HTTP/1.1" 204 1490 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:00:17:23 +0200] "GET /index.php/204 HTTP/1.1" 204 1351 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:00:17:23 +0200] "GET /index.php/204 HTTP/1.1" 204 1488 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:00:22:29 +0200] "GET /index.php/204 HTTP/1.1" 204 4342 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:00:27:23 +0200] "GET /index.php/204 HTTP/1.1" 204 1492 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:00:27:23 +0200] "GET /index.php/204 HTTP/1.1" 204 1349 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:00:35:10 +0200] "GET /index.php/204 HTTP/1.1" 204 4340 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:00:35:11 +0200] "GET /index.php/204 HTTP/1.1" 204 1361 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:00:39:12 +0200] "GET /index.php/204 HTTP/1.1" 204 1498 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:00:42:24 +0200] "GET /index.php/204 HTTP/1.1" 204 4350 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:00:42:24 +0200] "GET /index.php/204 HTTP/1.1" 204 4340 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:00:42:24 +0200] "GET /index.php/204 HTTP/1.1" 204 4342 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:00:42:24 +0200] "GET /index.php/204 HTTP/1.1" 204 1361 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:00:42:24 +0200] "GET /index.php/204 HTTP/1.1" 204 1359 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:00:42:24 +0200] "GET /index.php/204 HTTP/1.1" 204 1359 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:00:52:57 +0200] "GET /index.php/204 HTTP/1.1" 204 4342 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:00:52:57 +0200] "GET /index.php/204 HTTP/1.1" 204 4342 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:00:52:57 +0200] "GET /index.php/204 HTTP/1.1" 204 4338 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:00:52:57 +0200] "GET /index.php/204 HTTP/1.1" 204 4338 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:00:52:58 +0200] "GET /index.php/204 HTTP/1.1" 204 1494 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:00:52:58 +0200] "GET /index.php/204 HTTP/1.1" 204 1355 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:00:52:58 +0200] "GET /index.php/204 HTTP/1.1" 204 1496 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:01:03:02 +0200] "GET /index.php/204 HTTP/1.1" 204 4340 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:01:03:02 +0200] "GET /index.php/204 HTTP/1.1" 204 4340 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:01:03:02 +0200] "GET /index.php/204 HTTP/1.1" 204 4336 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:01:03:02 +0200] "GET /index.php/204 HTTP/1.1" 204 1496 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:01:03:02 +0200] "GET /index.php/204 HTTP/1.1" 204 1367 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:01:03:02 +0200] "GET /index.php/204 HTTP/1.1" 204 1494 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:01:07:51 +0200] "GET /index.php/204 HTTP/1.1" 204 1494 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:01:14:02 +0200] "GET /index.php/204 HTTP/1.1" 204 4340 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:01:14:02 +0200] "GET /index.php/204 HTTP/1.1" 204 1371 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:01:23:17 +0200] "GET /index.php/204 HTTP/1.1" 204 4348 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:01:23:17 +0200] "GET /index.php/204 HTTP/1.1" 204 4348 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:01:23:17 +0200] "GET /index.php/204 HTTP/1.1" 204 4348 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:01:23:17 +0200] "GET /index.php/204 HTTP/1.1" 204 4338 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:01:23:18 +0200] "GET /index.php/204 HTTP/1.1" 204 1355 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:01:23:18 +0200] "GET /index.php/204 HTTP/1.1" 204 1355 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:01:23:18 +0200] "GET /index.php/204 HTTP/1.1" 204 1357 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:01:33:17 +0200] "GET /index.php/204 HTTP/1.1" 204 4342 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:01:33:17 +0200] "GET /index.php/204 HTTP/1.1" 204 4340 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:01:33:17 +0200] "GET /index.php/204 HTTP/1.1" 204 4346 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:01:33:17 +0200] "GET /index.php/204 HTTP/1.1" 204 1363 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:01:33:17 +0200] "GET /index.php/204 HTTP/1.1" 204 1357 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:01:33:17 +0200] "GET /index.php/204 HTTP/1.1" 204 1353 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:01:37:36 +0200] "GET /index.php/204 HTTP/1.1" 204 1496 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:01:43:51 +0200] "GET /index.php/204 HTTP/1.1" 204 4342 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
	<server-ip>:443 <smartphone-ip> - <user> [07/Apr/2018:01:43:51 +0200] "GET /index.php/204 HTTP/1.1" 204 1361 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC2"
