### ISSUE TITLE
nextcloud android does not install apk from unknown sources Oreo Samsung s8

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/android#2266]
With introduction of oreo each application must be specified if it has permission to install apk from unknown sources, this with nougat had to be done by enabling installation from unknown sources, in oreo must be done for each application, but when I try to click on an apk file that is in my nextcloud does not start installing and asks me if I want to authorize installation of apk from unknown sources, with nougat that happened without problems

I also click the voice open with after downloading it but nothing happens

**Comment by tigernero79** [comment]
Practically with oreo Nextcloud is not detected among programs that can install unknown applications

**Comment by ardevd** [comment]
@tigernero79 Why did you open this issue and then #2269?

**Comment by tigernero79** [comment]
to indicate that it is clicking on the file and then going into the open menu with the same error.

surely it is due to the same bug. that you solved in pr

**Comment by AndyScherzinger** [comment]
Fixed via #2311 for 3.1

**Comment by tigernero79** [comment]
@AndyScherzinger
how far is expected to exit nextcloud 3.1 app?

**Comment by AndyScherzinger** [comment]
We plan to release a release candidate 1 to Google Play beta program in ~1+ week with a RC phase of ~2 weeks. So the stable release 3.1.0 should be somewhere around 9th of April.

**Comment by AndyScherzinger** [comment]
Other than that tomorrows nightly dev build will ship this fix
