### ISSUE TITLE
Cannot upload anything from nextcloud app

### ISSUE THREAD

**Issue by tribb333** [nextcloud/android#227]
### Actual behaviour

-Tell us what happens
Cannot upload anything from nextcloud app
### Expected behaviour

-Tell us what should happen
 Files should upload
### Steps to reproduce
1. Download app
2. Connect to server 
3. Attempt to upload file
### Environment data

Android version:
6.0.1
Device model: 
Galaxy Note 5
Stock or customized system:
Stock
Nextcloud app version:
1.2.0
Nextcloud server version:
10
#### Web server error log

```
Insert your webserver log here
```
#### Nextcloud log (data/nextcloud.log)

```
Insert your Nextcloud log here
```

**Comment by AndyScherzinger** [comment]
@tribb333 do you see any related errors in the servers log files and/or in the uploads view of the Android app? Just tested it with my phone running 1.2.0 with my Nc10 server instance and it works, so it is not a general issue.

**Comment by tribb333** [comment]
Going to try to get the logs tonight, doing this in my spare time for fun.  Sorry for the delay.

**Comment by AndyScherzinger** [comment]
No worries @tribb333 - we are also community contributors developing the Android app in our spare time. :+1:

**Comment by tribb333** [comment]
As a side note. I can upload just fine using owncloud app and web browsers

**Comment by tribb333** [comment]
GNU nano 2.2.6                     File: error.log                                                  
[Tue Aug 30 06:25:04.304628 2016] [:error] [pid 8460] python_init: Python version mismatch, expected $[Tue Aug 30 06:25:04.304790 2016] [:error] [pid 8460] python_init: Python executable found '/usr/bin/$[Tue Aug 30 06:25:04.304809 2016] [:error] [pid 8460] python_init: Python path being used '/usr/lib/p$[Tue Aug 30 06:25:04.304829 2016] [:notice] [pid 8460] mod_python: Creating 8 session mutexes based o$[Tue Aug 30 06:25:04.304840 2016] [:notice] [pid 8460] mod_python: using mutex_directory /tmp
[Tue Aug 30 06:25:04.330321 2016] [ssl:warn] [pid 8460] AH01909: localhost:443:0 server certificate d$[Tue Aug 30 06:25:04.332757 2016] [mpm_prefork:notice] [pid 8460] AH00163: Apache/2.4.10 (Debian) mod$  GNU nano 2.2.6                     File: error.log                                                  [Tue Aug 30 06:25:04.304628 2016] [:error] [pid 8460] python_init: Python version mismatch, expected $[Tue Aug 30 06:25:04.304790 2016] [:error] [pid 8460] python_init: Python executable found '/usr/bin/$[Tue Aug 30 06:25:04.304809 2016] [:error] [pid 8460] python_init: Python path being used '/usr/lib/p$[Tue Aug 30 06:25:04.304829 2016] [:notice] [pid 8460] mod_python: Creating 8 session mutexes based o$[Tue Aug 30 06:25:04.304840 2016] [:notice] [pid 8460] mod_python: using mutex_directory /tmp
[Tue Aug 30 06:25:04.330321 2016] [ssl:warn] [pid 8460] AH01909: localhost:443:0 server certificate d$[Tue Aug 30 06:25:04.332757 2016] [mpm_prefork:notice] [pid 8460] AH00163: Apache/2.4.10 (Debian) mod$[Tue Aug 30 06:25:04.332779 2016] [core:notice] [pid 8460] AH00094: Command line: '/usr/sbin/apache2'

**Comment by tribb333** [comment]
Apache2 error.log

**Comment by tribb333** [comment]
I've got a blank nextcloud.log

**Comment by AndyScherzinger** [comment]
Hmm, that is strange, what is the error you see for the tried upload for the file in the Upload list, from the app's upload menu item (left, top main menu)?

**Comment by tobiasKaminsky** [comment]
@tribb333 is the error still valid for the latest version?

**Comment by AndyScherzinger** [comment]
No response since 7 month, so closing for now. Please re-open if problem still occurs.
