### ISSUE TITLE
Desktop view on Android app

### ISSUE THREAD

**Issue by albertlepinski** [nextcloud/android#2270]
### Actual behaviour
-Tell us what happens
When I log in using my Android app it is showing me the view my desktop gets when using a web browser to connect and not the one I expect in the Android App

### Expected behaviour
-Tell us what should happen
 I should see the Android app as it was meant to be.

### Steps to reproduce
1. Just login
2. 
3. 

### Environment data
Android version:
7.1.2

Device model: 
HTC 10

Stock or customized system:
running LineageOS

Nextcloud app version:
latest in Playstore

Nextcloud server version:
12.0.0.12

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by xXSTrikeXx** [comment]
Can you provide us a screenshot of the view?

**Comment by albertlepinski** [comment]
![screenshot_20180302-113151](https://user-images.githubusercontent.com/3074447/36910173-fcb6dbc4-1e0d-11e8-8f5e-a3b7845e39ad.png)
gladly...thanks

**Comment by albertlepinski** [comment]
once in a while i'll get a prompt on the button to log in the old way...when i do i get a glimpse of the App as i expect ( where i can set up my auto upload folders and such ) but then this forces it self over the top in a moment or two.

**Comment by albertlepinski** [comment]
also oddly enough it worked fine on my HTC M8...I just upgrade to an HTC 10 and that is when this issue started.  Both running LineageOS

**Comment by AndyScherzinger** [comment]
Outch, that should not happen (the web-login is correct, seeing the content afterwards isn't...)

Calling @tobiasKaminsky to the rescue! :)

**Comment by albertlepinski** [comment]
If I can provide anything more to help please let me know.

**Comment by tobiasKaminsky** [comment]
@rullzer have you experienced this?
We listen if the returned URL starts with "nc://login/".
Do you have an idea when and how this can fail server side?

**Comment by rullzer** [comment]
I guess stuffcould go wrong but it should trigger an error then i guess.

@albertlepinski is there anything in your nextcloud.log file?

**Comment by albertlepinski** [comment]
![screenshot_20180308-131953](https://user-images.githubusercontent.com/3074447/37169285-834a826e-22d5-11e8-93c4-fa1b168cce62.png)
I do get this on the bottom after a few minutes. "Revert to old login method".  when do that then it's like the two screens are overlapping and I can "back" to the view I expect  but the wrong view pops up over it almost immediately.
For the log file should I paste a number of rows in or attach the file itself?

**Comment by rullzer** [comment]
What would be best I guess:

1. clear the file
2. Try to login with the android app again
3. Post the whole file

**Comment by albertlepinski** [comment]
here it is.  thanks!
[nextcloud.log](https://github.com/nextcloud/android/files/1794726/nextcloud.log)

**Comment by xXSTrikeXx** [comment]
First looking it seems that you had set some permissions wrong. Please check your server file permissions :)

**Comment by albertlepinski** [comment]
What would those be?
We have a stock LG G4 that works fine with this server and my previous HTC m8 did too.  Issue started with the HTC 10.

**Comment by tobiasKaminsky** [comment]
@rullzer any idea? The only login related message is

`
{"reqId":"rg7X\/Vjp4kn2zw7+SGA1","remoteAddr":"192.168.1.126","app":"core","message":"Scss is disabled for \/usr\/local\/www\/nextcloud\/core\/css\/styles.scss, ignoring","level":3,"time":"2018-03-08T20:50:55+00:00","method":"GET","url":"\/index.php\/login","user":"--","version":"12.0.0.12"}
`

As it is working with HTC8, but not with HTC10, I think that somehow the javascript rewrite stuff on weblogin is not working correctly...

**Comment by albertlepinski** [comment]
With the loading of lineage-14.1-20180317-nightly-pme-signed the issue seems to have gone away.  Just wanted to let you guys know so you can close this.

**Comment by tobiasKaminsky** [comment]
Thank you for this info :+1:
