### ISSUE TITLE
Auto-sync doesn't work

### ISSUE THREAD

**Issue by chujionglie** [nextcloud/android#2273]
### Actual behavior
-Tell us what happens: When I upload files in the app or make changes on my computer, it immediately shows the same behavior in the app. But for the folders I've switched to Auto-sync, nothing happened to them. 

### Expected behavior
-Tell us what should happen: Please tell me what should I doto make it work. I just wanna automatically backup pics on my phone to the server. 
 
### Steps to reproduce
1. 
2. 
3. 

### Environment data
Android version: 8.0.0

Device model: MHA-AL00 (HUAWEI MATE9)

Stock or customized system:

Nextcloud app version: 3.0.2

Nextcloud server version: 2.3.2

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by chujionglie** [comment]
Thank you for providing such  a good program, it helps a lot.

**Comment by lindhe** [comment]
I get a notification that the server was not available (even though it aught to be). Do you also get that error? Or just nothing?

Have you tried going to "Uploads" in the main menu, and choosing "Force rescan" in the context menu (three dots in the upper right hand corner)?

**Comment by lindhe** [comment]
There seems to be an issue open already, with more detailed discussions going on. If you think it is the same issue, please close this issue and join that thread instead.

https://github.com/nextcloud/android/issues/2249

**Comment by chujionglie** [comment]
thank you, I've tried the methods mentioned, but they don't work for me neither. And I'll close this issue and watch that one.
best regards.

**Comment by xXSTrikeXx** [comment]
Nextcloud server version: 2.3.2

I suggest to update your server version ;)

**Comment by chujionglie** [comment]
@xXSTrikeXx Thank you. I've mistaken the linux client version for the server version. The correct server version should be 12.0.5snap1 (5132).

**Comment by xXSTrikeXx** [comment]
Then I would suggest to wait until 3.0.3 ships some changes on autouploader ;) For some people it helps to update to 13. But lets wait ;)
