### ISSUE TITLE
PHP errors (libpng)

### ISSUE THREAD

**Issue by janipewter** [nextcloud/android#2274]
### Actual behaviour
Nextcloud logs show loads of these errors:

imagecreatefrompng(): gd-png: fatal libpng error: invalid block type at /var/www/nextcloud/lib/private/legacy/image.php#582

### Expected behaviour
Not this error
 
### Steps to reproduce
1. Upload png files
2. ???
3. Profit

### Environment data
Android version: 7.0

Device model: Samsung Galaxy S7

Stock or customized system: Stock

Nextcloud app version: 3.0.2

Nextcloud server version: 13.0

#### Web server error log
```
Nothing interesting
```

#### Nextcloud log (data/nextcloud.log)
```
See top of post
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
@janipewter this sounds rather like a server issue imho

**Comment by tobiasKaminsky** [comment]
@janipewter it might be that android is triggering this when you upload a png / create a thumbnail on server for a png file.
Afterall this is a server side error, so please open up a new issue at: https://github.com/nextcloud/server/issues/new
