### ISSUE TITLE
Strange autoupload behavior when no autoupload is set

### ISSUE THREAD

**Issue by xXSTrikeXx** [nextcloud/android#2275]
Device: Huawei Y6 2017 Android 6
Core: 13.0.0
App: 3.0.2 (beta in playstore)
 
Steps do reproduce:
- deinstall app
- Reinstall from playstore
- Login and dont do anything:
No upload, no download, dont set anything in autoupload.

Periodicly it opens a notification which says files upload. Im asking myself, why it stands there when nothing has to be done by autouploader.
![img_20180304_042151](https://user-images.githubusercontent.com/1523741/36941786-d3c35efc-1f63-11e8-83ae-6edaaa1600b0.png)

**Comment by xXSTrikeXx** [comment]
I think #2253 will fix it, but as enhancement there should be a check if autoupload or "keep file offline" are set. Just want to give the note in this issue. 
I want also give the hint, after I reinstalled it my avatar is there. But before I reinstalled it there wasn't such a notification. I will test later the behaviour on updating from v2.X. Maybe the update was the fault for my missing avatar.

**Comment by xXSTrikeXx** [comment]
cc @mario Will your PR fix it, so I can close this issue? :P :)

**Comment by mario** [comment]
Yes
