### ISSUE TITLE
Improve Folder Sync Configuration

### ISSUE THREAD

**Issue by cluelessperson** [nextcloud/android#2277]
Remove the auto scan feature and allow users to define folders with basic options.

Folder
 - Local
 - Remote
 - When to Sync
 - TwoWay / Upload Only / Download Only
 - Recursive or Not
 - Include Hidden Files or Not

**Comment by AndyScherzinger** [comment]
@cluelessperson you can create custom folder in that view in case you activated the "expert mode" in the app's settings

**Comment by leafcutterant** [comment]
@AndyScherzinger I have expert mode activated, but I'm not sure which view you refer to.

Right now I want to achieve that a specific server-side folder won't even appear in the folder list (and neither sync), but I can't make it disappear, not even by a local-only delete.

**Comment by AndyScherzinger** [comment]
> Right now I want to make a specific server-side folder not appear in the folder list (and neither sync), but I can't make it disappear, not even by a local-only delete.

That isn't possible at the moment afaik

**Comment by tobiasKaminsky** [comment]
What you describe is roughly our 2 way sync #285, but this is not yet done.
If you think this meets your idea, please close.

**Comment by AndyScherzinger** [comment]
@cluelessperson please reopen if you don*t think #285 will meet your idea...
