### ISSUE TITLE
New login method using incorrect server path

### ISSUE THREAD

**Issue by metafarion** [nextcloud/android#2279]
When logging into my server, the nextcloud app is looking for a nonexistent file path /nextcloud/nextcloud/index.php/login/flow/redirect and getting a Not Found error.  If I select "Revert to old login method", then login succeeds, but the credentials are not saved and I have to repeat the process shortly thereafter.  I also have no issue using the nextcloud web interface, so it definitely has something to do with the new login method.

I am accessing my nextcloud instance through a reverse proxy, and as such I'm using some special path parameters set in my nextcloud config.php including overwrite.cli.url overwritehost and overwritewebroot which it seems as though the new login method might be ignoring, but I have no way to confirm this.

I'm running Nextcloud 12.0.4 and version 3.0.2 of the Android app on an LG G4 with Android 6.0

**Comment by tobiasKaminsky** [comment]
Can you create us a test account and send the credentials to tobias at nextcloud dot com with a reference to this issue?

**Comment by AndyScherzinger** [comment]
Any news on this @metafarion ?

**Comment by metafarion** [comment]
Oh, sorry.  I ended up working around this by adjusting the url paths on the proxy server and the nextcloud server to match each other better.

THEN: nextcloud.mydomain.com redirecting to nextcloud.local.machine/nextcloud
NOW:  nextcloud.mydomain.com redirecting to nextcloud.local.machine

This made the overwritehost and overwritewebroot directives on the server unnecessary, and the android app was much happier.

**Comment by AndyScherzinger** [comment]
Glad to hear you worked it out @metafarion - closing the issue then :smiley:
