### ISSUE TITLE
Login loop

### ISSUE THREAD

**Issue by An3eljo** [nextcloud/android#2284]
### Actual behaviour
Again, since the last update of the nextcloud app, a relogin-page will be shown repeatedly. This bug occured recently too, but it was fixed by an update. Now he's turned up again

### Expected behaviour
- Re-login-page should not appear
 
### Steps to reproduce
1. Open Nextcloud-App

### Environment data
Android version: 7.0

Device model: UMIDIGI Z1 Pro

Stock or customized system: Raw Android customized by UMIDIGI

Nextcloud app version: 3.0.2

Nextcloud server version: 10.0.6

#### Web server error log
No related logs to bug

#### Nextcloud log (data/nextcloud.log)
No related logs to bug

**Comment by dim2on** [comment]
same here

**Comment by RayOfLight1** [comment]
try upgradin nextcloud server version

**Comment by xXSTrikeXx** [comment]
Nextcloud 10.06 is EOL. 
Have a look at release schedules: https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule

**Comment by ali-rahmanian** [comment]
I updated my nextcloud to the latest version and it was working fine. One I log out and wanted to log in again, I faced with log in loop :'( 
Cloud you please help me? I found there would be file premission but I did not solve my issue.
