### ISSUE TITLE
Nextcloud Androi app don't work 

### ISSUE THREAD

**Issue by danut2006** [nextcloud/android#2292]
### Actual behaviour
-The Nextcloud android app don't work after update from android 7 to android 8 (the phone is huawei P10 VTR-L29.
Before upgrade the app work very wheel, the auto-upload work great. Now she don't upload the file (photos,video) even i restart the phone the app don't see the new photos to upload on nextcloud server. 

### Expected behaviour
-Would be awesome if the app it wheel be work like before the upgrade.
 
### Steps to reproduce
1. 
2. 
3. 

### Environment data
Android version:8.0.0

Device model: Huawei P10 VTR-L29

Stock or customized system:Stock system

Nextcloud app version:3.0.3

Nextcloud server version:13.0.0

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by xXSTrikeXx** [comment]
Can you provide more infos?
Not working is, like a car is not working. There it could be a broken exhaust pipe or a broken clutch.
Nothing in Nextcloud Logs or in the web server logs?

**Comment by danut2006** [comment]
in web server logs there are nothing to see, and on the phone (I hope I did not get it wrong) but on the phone i didn't find  data/nextcloud.log
when i say the app is not work i'm talking about the auto-upload don't work like before the upgrade.

pls help me whit details how to get you the right information.

**Comment by xXSTrikeXx** [comment]
@danut2006  what is the error msg, when the autouploader tries to upload files to the server?
For data/nextcloud.log you have to look in you webserver in the directory at /nextcloud/data/nextcloud.log. The log is in the data structure on web server :D 

Another hint can be to look into the android app under settings in the protocol.

**Comment by danut2006** [comment]
@xXSTrikeXx maybe i look like a stupid guy, i check the nextcloud server (/nextcloud/data/nextcloud.log) and there is no file nextcloud.log. (picture atache)
on the phone i try to find in the app setting the protocol section bat there is nothing there(picture atache) 
haw i say in the first post, the app work, bat upload the photos/video only if i open the nextcloud app, she don't auto-upload the media in the background like before the upgrade.
this issue it is annoying because i have to check if the all media was correct upload and don't miss any file.
![capture](https://user-images.githubusercontent.com/36423801/37049481-a5d0498e-2179-11e8-869d-80ad1623231a.PNG)
![whatsapp image 2018-03-06 at 20 00 47](https://user-images.githubusercontent.com/36423801/37049482-a6064200-2179-11e8-834d-7fd251ec107f.jpeg)

**Comment by xXSTrikeXx** [comment]
ll? is that an alias? ls -l should list the directory ;)

And nextcloud android protocoll is not findable in the system settings, rather in the app itself under settings and protocol:

![screenshot_2018-03-06-19-11-56](https://user-images.githubusercontent.com/1523741/37049838-7b21c0a2-2172-11e8-85f3-0b04415d7e22.png)

**Comment by danut2006** [comment]
ok i found.
[currentLog.txt](https://github.com/nextcloud/android/files/1786296/currentLog.txt)

**Comment by xXSTrikeXx** [comment]
@danut2006 Can you explain where your data directory is? There should be all files in with personal data of all users. 
There should be sth like this:

drwxr-xr-x 12 www-data www-data      4096 Feb  8 04:31 appdata_oc6dfsafe3
drwxrwxrwx 10 www-data www-data      4096 Aug  7  2017 appdata_oc6dfsafe3
drwxrwxrwx  2 www-data www-data      4096 Aug  6  2017 dataBackup
drwxr-xr-x  2 www-data www-data      4096 Sep 11 01:50 files
drwxrwxrwx  2 www-data www-data      4096 Feb 14 19:16 files_external
drwxrwxrwx  3 www-data www-data      4096 Aug  7  2017 gpxedit
-rwxrwxrwx  1 www-data www-data         0 Feb 16 03:32 index.html
**_-rw-r-----  1 www-data www-data 331026294 Mar  6 21:01 nextcloud.log_**
drwxr-xr-x  4 www-data www-data      4096 Feb 14 22:15 ownbackup
drwxrwxrwx  8 www-data www-data      4096 Oct 21 11:59 User
drwxr-xr-x  5 www-data www-data      4096 Feb 26 04:36 User
drwxr-xr-x  4 www-data www-data      4096 Feb 24 18:43 User
drwxr-xr-x  4 www-data www-data      4096 Feb 12 22:10 test
drwxr-xr-x  4 www-data www-data      4096 Feb 28 07:25 Test2
drwxrwxrwx  9 www-data www-data      4096 Feb  8 22:52 User
drwxr-xr-x  7 www-data www-data      4096 Jan 31 20:37 User
-rwxrwxrwx  1 www-data www-data   1106627 Feb  8 02:48 updater.log
drwxr-xr-x  4 www-data www-data      4096 Feb  8 03:15 updater-oc6dfsafe3
drwxrwxrwx  4 www-data www-data      4096 Aug 19  2017 updater-oc6dfsafe3

I´ll study your log and will edit this posting ;)

**Comment by xXSTrikeXx** [comment]
@danut2006 It comes to mind:
Have you set nextcloud to allow power consumption? Since Android 6 (or maybe  already 5) the apps needs to be added to a list, which are allowed to be running in background. Otherwise every app will be closed to reduce power consumption ;) Maybe this is your solution ;)

**Comment by danut2006** [comment]
Hello,

i think you may have right, i make changes on the phone to allow power consumption and it look the auto-upload works. i will monitoring the app tomorrow and i came back whit an answer about the app.
tks very much for your help to resolve that issue.

**Comment by xXSTrikeXx** [comment]
Yes, thats Huawei, mario and me loves it 🙄

**Comment by tobiasKaminsky** [comment]
Is there a way to detect these aggressive power mechanism? Then we would show a snackbar when enabling auto-upload...

**Comment by xXSTrikeXx** [comment]
@tobiasKaminsky have a look at the app radio.de There is the snackbar implemented. Maybe you can work with it, even it is not open source. @mario and me last tried it on my device with talk. 😉
