### ISSUE TITLE
InstantUpload no longer works if using sub folders

### ISSUE THREAD

**Issue by aborsu** [nextcloud/android#2294]
### Actual behaviour
-Tell us what happens
I've noticed that my phone stopped uploading  pictures since the end of february. No pictures have been uploaded in march.

I tried re-installing the application, re-creating an account to no avail.
After debugging a little, it appears that when I disable using subfolders, the uploads work again.

### Steps to reproduce
Take a picture, go to the `send history` menu (I'm usin it in french so not sure it's that menu exactly. In french its 'Historique des envois'

### Environment data
Android version: 7.0

Device model: HUAWEI P10-Lite

Stock or customized system: stock

Nextcloud app version:3.0.2

Nextcloud server version: 13.0

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
Last 100 lines of logs
[here](https://cloud.acelpb.com/s/CzAQ9bWLbg2Q5kZ)

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
Did you update to the latest version 3.0.3 released today? That one should fix the subfolder issue we experienced.

**Comment by aborsu** [comment]
Hello,

I saw the update about 5 minutes after I posted this. Worked like a charm thank you
