### ISSUE TITLE
"Could not save keys, please try again later" message after "set up encryption"

### ISSUE THREAD

**Issue by madsiman** [nextcloud/android#2298]
### Actual behaviour
Getting the error message: 
Could not save keys, please try again later
### Expected behaviour
Keys should get stored
I should be able to enter they folder.

### Steps to reproduce
create a folder via the app on my cloud.
Setting it to encrypted in App.
trying to enter it in app - problem
trying to enter folder on Server - not possible.

### Environment data
Android version:
7.+
Device model: 
Samsung s6 root
Stock or customized system:
customized - not having any other issues with any other app. 
not using playstore or google account (yalp store instead)

Nextcloud app version:
05 march
Nextcloud server version:
latest stable

**Comment by xXSTrikeXx** [comment]
cc @tobiasKaminsky for E2E ;)

**Comment by tobiasKaminsky** [comment]
Which e2e server app version do you use? 
Please upgrade to the latest and try again.

**Comment by hoellen** [comment]
Same here. I get an invalid CSR error in log.

Nextcloud log:
```
{"reqId":"STJs3jmq7LjXcIsApY94","level":3,"time":"2018-03-08T15:13:09+01:00","remoteAddr":"77.178.86.112","user":"testuser","app":"PHP","method":"POST","url":"\/ocs\/v2.php\/apps\/end_to_end_encryption\/api\/v1\/public-key?format=json","message":"openssl_csr_sign(): cannot get CSR from parameter 1 at \/apps2\/end_to_end_encryption\/lib\/SignatureHandler.php#60","userAgent":"Mozilla\/5.0 (Android) ownCloud-android\/20180302","version":"13.0.0.14"}
{"reqId":"STJs3jmq7LjXcIsApY94","level":3,"time":"2018-03-08T15:13:09+01:00","remoteAddr":"77.178.86.112","user":"testuser","app":"end_to_end_encryption","method":"POST","url":"\/ocs\/v2.php\/apps\/end_to_end_encryption\/api\/v1\/public-key?format=json","message":"Can't create public key: could not sign the CSR, please make sure to submit a valid CSR","userAgent":"Mozilla\/5.0 (Android) ownCloud-android\/20180302","version":"13.0.0.14"}
```
Android App: Dev 20180302
E2E Server App: 1.0.4
