### ISSUE TITLE
GPLv2 vs Apache2 license

### ISSUE THREAD

**Issue by krt16s** [nextcloud/android#23]
This app is GPLv2 licensed but uses Apache2 style dependencies like Google's Android support libraries.  This might be problematic, e.g. see https://www.apache.org/licenses/GPL-compatibility.html . So iirc switching to GPLv2+ ( adding the "version 2 and later"option) or GPLv3 solves this, but I am not a lawyer...

**Comment by AndyScherzinger** [comment]
I am no lawyer either and not an OSS license specialist, so @fkarlitschek or @jancborchardt or @LukasReschke can you answer this?

**Comment by LukasReschke** [comment]
Summoning @schiessle as well on this. Go GNU/Björn 😉

**Comment by jancborchardt** [comment]
Any info on this @schiessle @karlitschek? If this is a problem, then it’s an issue with the original code too and the relicense to GPLv2 from the previous GPLv2+ might have been not proper.

**Comment by karlitschek** [comment]
I think Apache dependencies are not a problem. But @schiessle is the expert here!

**Comment by schiessle** [comment]
Yes, the Apache license and GPLv2 are not compatible because of the patent grant in the Apache license.

I'm not a Android expert, if the "Google's Android support libraries" are system libraries this shouldn't be a problem, because of the "system library exception" https://www.gnu.org/licenses/gpl-faq.html#SystemLibraryException

**Comment by schiessle** [comment]
We can't change the license from GPLv2 only to GPLv2+ because we don't own the complete source code. But I would suggest to consider switching to GPLv2+ for every new code added to the android app. We do something similiar on the server (ownCloud code is AGPLv3 only but we add new code as AGPLv3+)

**Comment by tobiasKaminsky** [comment]
We are doing it the @schiessle proposed: every new code done by us is GPL3+
