### ISSUE TITLE
Non-empty folder shows as empty in app

### ISSUE THREAD

**Issue by keithzg** [nextcloud/android#230]
### Actual behaviour

Folder that isn't actually empty is shown as empty, and any help understanding or debugging why would be appreciated . . .
### Expected behaviour

Contents of the folder should be shown!
### Steps to reproduce
1. Happen to have a folder that's cursed like one of mine is (I haven't been able to find any special attribute of this folder to verify _why_ this one is different)
2. Go to the folder in the Android app.
3. See "Nothing in here. Upload something!" instead of the folder contents.
### Environment data

Android version: 6.0.1

Device model: Nexus 6P (also tested on a Pixel C running Android 7.0 and an old Moto X 2013 running Android 4.4)

Stock or customized system: Stock.

Nextcloud app version: 1.2.0

Nextcloud server version: 10.0.0

Nextcloud server OS: *buntu 16.04
#### Web server error log

Nothing written to /var/log/apache2/error.log, although when looking at the access.log I see PROPFINDs like a normal folder but never any GET like is caused by browsing to other folders.
#### Nextcloud log (data/nextcloud.log)

Nothing is written to this when I browse to the folder in the Android app, or when I pull down to prompt a refresh (in fact the only thing writing seems to be logs recording the invocation of cron.php by my system cron job for the sake of the News app).

**Comment by AndyScherzinger** [comment]
Hi @keithzg 
if the folder on the server isn't empty and you don't see any errors in the server logs that would link to this error, could you install the Nextcloud Android app beta version from f-droid (https://f-droid.org/repository/browse/?fdfilter=com.nextcloud&fdid=com.nextcloud.android.beta) and check the log (to be found on the settings screen in the app?

That way we might gain some inside what the android client is doing.

**Comment by keithzg** [comment]
Unfortunately, I may have run into a different bug, unless there's something else I have to do to enable logging in the beta app?

![empty log listing](https://lh3.googleusercontent.com/R2tC7rkOp_ED_tF-7H496XZ3FYg9TtMCCfX1XQ5G6LwNxdokzB9ww1mliOC80_y24nrMg4PT-5TskpTlug0rqGw70aqOKKUukLJUwKc4DYI5Fr7l6OQA3Z_uklt76gh7cJ-vJr5ZKP_WwnXIOFFmp6RmYzQ1peZweIgNuXTwBXoDz5FSh1WeySXbW0AnCs1PDu07afYVaGQurZHE75PP5T21Ury3jKsGwmRME675kLZT2yJwK1F11NVKOTNFP3fHgAFVE8gRAY28RbXzOMbhX2bKbYI2ECU9l_dRwKk4LqWD0mgQtI8TipO-imoGbGJr551lHNhToCLsMzdUo5kx3P0mkY8U187unbGyNLfGqjS3DFXn_Y7krpMZIOnRTtCA2RZikziYYIEQiBCyz4zaEBhXOxhYmYxfMO72BgKMnARLo7JlPL6hvu9R_5Ua0BOt4bah3AKLlH0e6AYD7Qke2z7i59ql07pbF68HOv_AwSGHKEyIT1FhGWxvyUpDQYoTOQYwgGLSVYFo7ukFvekdu7sgJ98MBx3BxmdBFHvmZ0W3oD4L6tINPBG5U_c23GvZtU3-gJLMtt2Xxomv4D-69tu8_QLSGP3Iwl0rlty7sQNa0gDTaA=w615-h1093-no)

**Comment by AndyScherzinger** [comment]
0_o now it gets really weird. There should be something in it, basically always since the beta logs a lot of stuff to support finding bugs...

![device-2016-08-31-110029](https://cloud.githubusercontent.com/assets/1315170/18122558/53935f98-6f6a-11e6-873d-5aa10486edf9.png)

Is the log empty on both devices?

**Comment by keithzg** [comment]
The Pixel C running 7.0 has nothing in the Logs section either. Are you sure there's no additional step I would have to take to enable it? (I guess we're getting a bit off track here, heh, but it's certainly hard to debug issues without logs.)

**Comment by AndyScherzinger** [comment]
There is no additional step required, to my knowledge. The log is aleays active for the beta. Maybe @tobiasKaminsky can shed some light in this after he is back - next week.

**Comment by keithzg** [comment]
Any news? This isn't the worst problem in the word---I can always just access the folder via WebDAV, and that works fine from my Android devices---but both the lack of any file and folder listing for this folder, and the lack of any logging, seem bizarre and I'd love to get to the bottom of them.

**Comment by AndyScherzinger** [comment]
@keithzg no progress yet. @tobiasKaminsky is back from vacation and we are preparing for the conference starting end of this week. Is the folder containing any rather private information while of course the files are private per se. So you could create an a separate account shared with us to debug this matter? Seeing no logs at all on both devices seems really weird since at least on the Nexus6P your are most likely not the only user with this device.
Is the folder any kind of special storage like external drive, dropbox integration, etc.?

Other than that @tobiasKaminsky I think we should implement discuss and schedule #247. Even though if the beta app doesn't show any logs it seems rather related to the device (not the device model since there are no other reports of Nexus6P users and it is working on my Nexus5X).

As a general note, we would also like to get to the bottom of this since the lack of files/folders is strange and this should "simply work".

**Comment by milgner** [comment]
I was experiencing this issue myself with my `/Music` folder. Now I notice that it has disappeared, there are two things that I changed: I updated my Nextcloud server to the latest version and changed the rewrite rules for stripping trailing slashes a bit. Of course the Android app may also have been updated in the meantime but I'm not sure about that.

**Comment by AndyScherzinger** [comment]
@milgner you can check the Android App version in the settings screen at the bottom :) 1.3.0 RCx or 1.2.0 propably.

**Comment by tobiasKaminsky** [comment]
I do not have a clue at the moment why the logs are not shown...

**Comment by keithzg** [comment]
I've updated my beta app to version 20160907, and unfortunately there's no change to either the folder being empty, nor to the log screen being empty.

>  Is the folder containing any rather private information

Unfortunately, the folder in question is perhaps the single most private folder I have on my Nextcloud instance---it's my personal notes folder! Not all are terribly private, but many are, alas.

> Is the folder any kind of special storage like external drive, dropbox integration, etc.? 

Nope, it's all on the same single drive that the entire server runs from, and is no different than any of my other folders in that regard.

> Is anything happening when you pull-down-to-refresh?

It briefly goes to "Loading..." but after a second or two the motion dots at the top cease again and the text in the middle changes back to "Nothing in here. Upload something!"

**Comment by AndyScherzinger** [comment]
@keithzg at the moment I do not really have an idea because the log should have plenty of log statements in it and if it is empty than that is rather really strange :(

@tobiasKaminsky any idea what to do? the only thing that comes to my mind is that an error happens during this fetching of the folder/file list which brings you back to "Nothing in here. Upload something!". So for the beta we could add a toast or something which then at least displays an error (if one occurs) and probably do something similar for the log screen. Any other ideas?

**Comment by alnixon** [comment]
@keithzg Just to rule this out ... in the menu, ensure you have "All files" selected and not "On device".

**Comment by keithzg** [comment]
@alnixon Oh indeed, it's "All files" that I'm under. Lots of files and folders I can see that aren't on the device itself, just not the contents of that one particular folder.

**Comment by AndyScherzinger** [comment]
@keithzg is the log in the Android beta app from f-droid empty on all your devices?

**Comment by keithzg** [comment]
@AndyScherzinger This was true as of September, but I finally got around to re-checking this today, and at some point in the intervening days this has changed! I finally have an actual error message to report:

```
2017/01/27 22:11:29
ReadRemoteFolderOperation : Synchronized /clientsync/notes.d/: Unexpected exception: 
java.lang.NullPointerException: 
Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference - 
Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference 
Exception : 
[com.owncloud.android.lib.common.network.WebdavEntry.<init>(WebdavEntry.java:168),
 com.owncloud.android.lib.resources.files.ReadRemoteFolderOperation.readData(ReadRemoteFolderOperation.java:151),
 com.owncloud.android.lib.resources.files.ReadRemoteFolderOperation.run(ReadRemoteFolderOperation.java:89), 
 com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:136),
 com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:313), 
 com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:197), 
 com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:303), 
java.lang.Thread.run(Thread.java:761)]
```

(Some line breaks added for readability.)

**Comment by AndyScherzinger** [comment]
Hi @keithzg 
is still issue still present for your device(s)?

**Comment by keithzg** [comment]
@AndyScherzinger sadly it still is. Currently running version 1.4.2 of the Android app, version 11.0.2 of Nextcloud itself. I also recently got a Samsung Chromebook Plus, and the issue appears there as well.

**Comment by Adi3000** [comment]
Hello, for information I encounter the same issue. My wife seems to make it work perfectly (Sony Xperia Z3  Compact D5803 with Android 6.0.1) but me (with Sony Xperia Z3 "normal" (D6603) on Android 6.0.1) cannot see my owncloud home.

Beside, I can upload thing, and those things can be seen next to my other thing : 
1) My empty view
![screenshot_20170417-122358](https://cloud.githubusercontent.com/assets/1077725/25086661/7a9f0d90-2369-11e7-983b-5ca22167fa31.png)
1b) My web full view 
![image 1](https://cloud.githubusercontent.com/assets/1077725/25086693/b2ede0a4-2369-11e7-9393-f87b93af09f7.png)
2) After upload
![screenshot_20170417-122549](https://cloud.githubusercontent.com/assets/1077725/25086697/bb2f093c-2369-11e7-8d80-7d399a5b8766.png)
2b) My proper after upload view
![image 2](https://cloud.githubusercontent.com/assets/1077725/25086705/d5a6370e-2369-11e7-9cc8-37a1e8472a67.png)

For information, 
* I just upgrading from owncloud 9.x to nextcloud 11.0.2 (but it works on my wife phone) and Android screenshoot come from nightly 20170315. I didn't try what happens on Owncloud 9.x with this app
* My log view is also empty 
* And the problem occured also on Android App owncloud 2.3.0 (I installed it today, so I also didn't try what happens with owncloud 9.x)

**Comment by tobiasKaminsky** [comment]
@Adi3000 is this working with a fresh account?

**Comment by tobiasKaminsky** [comment]
@keithzg @Adi3000 is this still happening with a fresh account?
If so do you want to create a test account and mail it to android at nextcloud dot com with reference to this issue?

**Comment by Adi3000** [comment]
It solved my problem : indeed, my profile was stuffed with some symlinks which may have broken listing over my folder.

A new profile was fully functionnal over my phone.
Also deleting symlinks resolved my problem thank to that note : https://github.com/owncloud/documentation/issues/2493
My Wife Phone didn't use symlinks within her account on her phone so she wasn't impacted.

**Comment by tobiasKaminsky** [comment]
@Adi3000 glad to hear :-)
@keithzg if the problem still occur, just answer and re-open this issue.

**Comment by keithzg** [comment]
Going off of the hint of using a new profile, but considering that in my case it was only the sole folder that was causing grief, I went ahead and copied the entire folder out of my instance, and back in again as a "different" folder. At that point, the folder loaded perfectly fine in the Android app!

Juggling things around so that the "new" folder had the old name yet sync wasn't terribly confused was a bit of a hassle, but I got it done eventually.

Note that in no place in my synchronized folders do I have symlinks, so the exact underlying issue here remains opaque to me! All's well that ends well though, I suppose ;)

**Comment by tobiasKaminsky** [comment]
@keithzg thank you for your feedback.
I will also a little unsatisfied that the real cause of this problem, at least for you, is not found.

**Comment by Adi3000** [comment]
@keithzg your issues may be logged under your owncloud server log. It was the case for me.
@tibiasKaminsky Maybe the listing file over Owncloud server is not impacted by any error encountered during feching all file's folder. When an error is encountered while listing, you may return an empty list of file.
