### ISSUE TITLE
'Backup contacts' is failing to upload contacts

### ISSUE THREAD

**Issue by ShapeShifter499** [nextcloud/android#2300]
### Actual behaviour
Under Settings > More tapping "backup contacts initates a backup with a timestamped vcf file but then fails with "connection error".

### Expected behaviour
Selecting the "backup contacts" should result in successful upload
 
### Steps to reproduce
1. Go to settings in nextcloud
2. tap on backup contacts
3. see a connection error under uploads

### Environment data
Android version: 7.0

Device model: XT1575 Moto X Pure

Stock or customized system: Stock with magisk root

Nextcloud app version: 3.0.2

Nextcloud server version: 13

Here is a log from the android app.
[currentLog.txt](https://github.com/nextcloud/android/files/1785760/currentLog.txt)

I can upload files manually just fine, it's just the "backup contacts" option that is failing.

**Comment by xXSTrikeXx** [comment]
Could you test latest 3.0.3?

**Comment by ShapeShifter499** [comment]
As of writting, Nextcloud Android app 3.0.3 isn't available in F-Droid. I'll gladly test when it's available.

**Comment by tobiasKaminsky** [comment]
There is unfortunately nothing we can do to speed up fdroid as this is done automatically.

**Comment by ShapeShifter499** [comment]
I got a Raspberry Pi 3B+ and setup Nextcloud anew.  This time around coupled with the Android app version 3.1.0, contact uploads appear to work fine again. I will now close this issue.

**Comment by AndyScherzinger** [comment]
Thanks for the feedback @ShapeShifter499 and happy to hear the matter could be resolved.
