### ISSUE TITLE
Push notifications disabled due to depedencies on proprietary Google Play Services

### ISSUE THREAD

**Issue by ardevd** [nextcloud/android#2301]
When I launch the Notifications Activity a persistent SnackBar appears at the bottom saying that Push notifications are disabled due to dependencies on proprietary Google Play Services. 

Looking at the code, the message is triggered here in NotificationsActivity line 154.

```
String pushUrl = context.getResources().getString(R.string.push_server_url);
 
if (pushUrl.isEmpty()) {
 snackbar = Snackbar.make(emptyContentContainer, R.string.push_notifications_not_implemented,
         Snackbar.LENGTH_INDEFINITE);
```

The push_server_url string is hardcoded as `https://push-notifications.nextcloud.com` so I cant quite see the connection between the actual error, the pushUrl string being empty or null, and the snackbar error message. 

Seeing this on a Pixel 2 XL running Android 8.1 with Google Play services installed.

**Comment by mario** [comment]
Hmmm ... how did you login? You need to login using login flow in order to have push.

**Comment by ardevd** [comment]
I logged in the only way I thought was possible. Still doesn't explain the error message though which gives the impression that Google Play services are missing, which is not the case.

**Comment by mario** [comment]
You're right. @tobiasKaminsky is the latest release gplay flavour?

**Comment by ardevd** [comment]
I realize now that the push_server_url string is not in strings.xml. It's found in two places:

gplay/res/values/setup.xml and main/res/values/setup.xml. The latter is an empty string and the primary is https://push-notifications.nextcloud.com. 

A bit confused as to how you've designed this.

**Comment by mario** [comment]
It's designed this way in order to support building both push-enabled Google Play release and push-disabled F-Droid release. Anyway, let's wait to see what @tobiasKaminsky says if he built a gplay release.

**Comment by tobiasKaminsky** [comment]
Yes, latest release is built with gplay release (I am always testing this).
I tested it with a fresh new emulator and it is working, meanwhile I found missing support for 8.x --> #2335

As this @ardevd is also using 8.x I think this is related to #2335.

**Comment by ardevd** [comment]
@tobiasKaminsky You're probably correct then. I think we can mark this as a duplicate of #2335 for sure.

**Comment by tobiasKaminsky** [comment]
Hmm. While thinking about this, it seems to be independent for me.
On my fresh emulator, I never saw the "due to dep" snackbar, but instead I got a warning when a push notification is received.
Sorry that I read it wrong.

Have you installed the app from google play store?

**Comment by Mickael-Martin** [comment]
Hello,
Sorry, I'm not remember if I ask the question : Why Nextcloud not use http/2 push notification if the server support this feature ?
