### ISSUE TITLE
A-Z (alphabetical) sorting doesn't work

### ISSUE THREAD

**Issue by leafcutterant** [nextcloud/android#2303]
For me, A-Z ascending kind of clusters together the files that start with the same letter (not completely consistent), but it scrambles the clusters all over the place.

This is from a folder with ~200 items.

![0](https://user-images.githubusercontent.com/7106231/37062425-b231ed64-2196-11e8-980b-7522351bb81d.png) ![1](https://user-images.githubusercontent.com/7106231/37062426-b43cd9e8-2196-11e8-8800-001bddd6ca7b.png)

### Environment data

Nextcloud app version: 3.0.2

Nextcloud server version: 13.0.0

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky any idea?

@leafcutterant is it possible to provide a list of the file names?

**Comment by leafcutterant** [comment]
I can provide you with a list in email. Can you give me an address of yours?

**Comment by xXSTrikeXx** [comment]
android(at)nextcloud.com ;)

**Comment by tobiasKaminsky** [comment]
Just copy a file list in here please. If there are private informations in the file names, please try to replace the with dummy values.
I want to avoid to have the communication decentralized.

In #2262 I enhanced the sorting with natural sorting and also added a few more test cases.

In general it should be consistent with web ui, so you can create there just a bunch of text files and see if sorting is working there as a expected.

**Comment by tobiasKaminsky** [comment]
No response within the last month, therefore closing.
Please feel free to reopen with additional infos, if the problem still exists.
