### ISSUE TITLE
A-Z sorting preference is not remembered

### ISSUE THREAD

**Issue by leafcutterant** [nextcloud/android#2304]
It reverts back to the same strange sorting I described in #2303. The preference seems to be retained with all the other sorting options.

### Environment data

Nextcloud app version: 3.0.2

Nextcloud server version: 13.0.0

**Comment by AndyScherzinger** [comment]
Hi @leafcutterant,
just to be sure. Do you mean you "loose" the sorting option you chose? The sorting option is on a per folder basis, so when you choose a sorting option it will only be active for the current folder. The default is always A-Z though.

**Comment by leafcutterant** [comment]
Yes, I lose it.

To make it clearer: A-Z sorting is the default, but for me, it realizes in this strange "clustered" ordering I described in #2303. When I explicitly set A-Z ascending sorting, it becomes somewhat better: the folders in the folder become truly alphabetically ordered, and the files take up an order that resembles an alphabetical one more, but there is still a degree of this quirky clustering. If I leave the folder and come back to it, it reverts to the first version of the "clustered" ordering.

**Comment by AndyScherzinger** [comment]
Cc @tobiasKaminsky any ideas?

**Comment by tobiasKaminsky** [comment]
Nope, no idea.
Maybe, only maybe, TimSort is crashing while sorting and this then renders an arbitrary/partial sorting order.
As said in #2303 we would need some test file names where this is not working.
