### ISSUE TITLE
Crash on login

### ISSUE THREAD

**Issue by louwers** [nextcloud/android#2306]
### Actual behaviour
After logging in (pressing the button after putting credentials) the application says "redirecting" then crashes.

### Expected behaviour
It should show me my files.

### Steps to reproduce
This is probably a server bug or incompatibility. Still, the app shouldn't crash. 

### Environment data
Android version: 7.1.2

Device model: ONE E1003

Stock or customized system: Using LineageOS version 14.1-20180303-NIGHTLY-onyx

Nextcloud app version: 3.0.2

Nextcloud server version: v0.26c

#### Web server error log

If needed I can provide these.

#### Nextcloud log (data/nextcloud.log)
https://bpaste.net/show/97483f61d70d

**Comment by xXSTrikeXx** [comment]
@louwers Excuse me, but what server version do you use? Nextcloud server version: v0.26c?
The latest is v13. ;)

**Comment by louwers** [comment]
@xXSTrikeXx It's actually 12.0.5! Sorry, my bad.

I will try the new version once it's in F-Droid.

**Comment by amas01** [comment]
Looks like the same as these other issues: #1531 #2032

See if the solution posted here solves the problem for you: [#2032 comment](https://github.com/nextcloud/android/issues/2032#issuecomment-370811027).

**Comment by louwers** [comment]
@amas01 That worked! Closing this as a duplicate.
