### ISSUE TITLE
User and password in provisioning link not working

### ISSUE THREAD

**Issue by LiamHD** [nextcloud/android#2308]
### Actual behaviour
I start the nextcloud app via a provisioning link like
nc://login/user:test&password:secret&server:docs.myserver.de
The nextcloud app is started. The server's address is correctly taken over. Then a screen comes up where the server ask for Account access: "You are about to grant %s access to your %s account."
When I accept this the login page comes up but username and password fields are not prefilled.

### Expected behaviour
username and password fields should be pre-filled.
 
### Steps to reproduce
See above.

### Environment data
Android version:
7.0

Device model:
Samsung Galaxy Tab S3

Stock or customized system:
stock

Nextcloud app version:
3.0.3

Nextcloud server version:
13.0.0

**Comment by LiamHD** [comment]
Why is this an "enhancement". According to https://nextcloud.com/blog/nextcloud-android-client-1.4.0-has-been-released/ this should work. Even though this blog post says that the url-scheme is "nextclound" and not "nc".

**Comment by LiamHD** [comment]
What is tricky and only working in firefox?

**Comment by xXSTrikeXx** [comment]
In Chrome it opens for me the google search :D So there should be an improvement in the code to be able to do it also in chrom ;) That was the tricky one on my testing purpose :D

**Comment by LiamHD** [comment]
I just put a link to an html link element <a href="...">..</a>

**Comment by LiamHD** [comment]
I just put the link in the href attribute of an html <a> element. Chrome on Android correctly launches the nextcloud app.

**Comment by AndyScherzinger** [comment]
@LiamHD The issue is basically that this worked until pre-3.0.

@tobiasKaminsky any change to get this fixed as in transffering the user/password within the new web login? Since this feature has been build long before the web login via the app has been implemented.

**Comment by tobiasKaminsky** [comment]
The "new" login flow is used/created to have a session password instead of using the regular user password for all connections: user "test" and password "test" becomes to test:aiesaie23423, which will then be used for all further communication between app and server.
This kind of password/login is also needed for push notifications.

So we could just create an account with provided user/pass via provisioning link, but this then has to be a session based login.
Or the server needs to be enhanced so that we can pass user/pass to the new login flow without human interaction and get back the desired password.
@rullzer

**Comment by rullzer** [comment]
Aaah this is less easy that I thought.

We can't create a simple endpoint where you submit your username + password and get back an apptoken. Well we could in theory. But it would not work if users have 2FA enabled.

Sending the username+password when opening the current page is not really an option as it would have t be done via GET and thus probably gets logged in the webserver log.

mmm I'm not fully sure yet how to solve that. I'll think about it some more.

**Comment by mario** [comment]
Why not just store the username & pass we get directly in the account manager? Then people can pass app passwords via provisioning link.

**Comment by rullzer** [comment]
I don't know where these provisioning links are generated. But if they use apppasswords sure. 

But even then I would prefer it to generate a new app password specifically for this device. To avoid multiple devices registered to the same app password because the link is passed from device to device.

**Comment by mario** [comment]
AFAIK manually? That's the point - admin generates them for each of the users devices that he's aware of (say corporate devices?), and they're separate. Sure, they're potential for abuse (you do it on multiple devices) it's probably an edge case.

**Comment by rullzer** [comment]
In the current setup admin users can't create apppasswords for users.

At least not without them manually loggin into the account. Which would mean the admin needs to know the user password.

**Comment by mario** [comment]
Well, that's true, but in a "world of provisioning" you could "manually"/via script provision users with app passwords in the database, couldn't you?

**Comment by rullzer** [comment]
No you can't. The apppassword contains information that is only available when the user is explicitly logged in.

**Comment by mario** [comment]
Well ... damn.

**Comment by LiamHD** [comment]
Maybe we just skip the password part of the story. I also don't think that it's a good idea to pass them around.
But at least the user name could be taken over. So a user clicking on that link does not have the need to enter the server-url and the username. But only needs to enter his password.

In addition it would be cool if nextcloud server could show that provisioning link as QR-Code on that "first start wizard" that comes up a user logs on for the first time. That wizard already provides download links for the native clients. So it would be a perfect place to provide that provisioning link as the first step you do after installing the native app is entering the credentials.

**Comment by AndyScherzinger** [comment]
I like @LiamHD's idea! That would help with the worst part, putting in the URL :+1:

**Comment by LiamHD** [comment]
the url part is working as afar is i know.

**Comment by rullzer** [comment]
Sending the loginname via get is fine. This can then be autofilled in the login page.

The android app can then just open the same 'add new account' stuff we have now. Just it enters the server directly. And then when opening the webflow your pass `?user=<user>`

Would that work?

**Comment by LiamHD** [comment]
@rullzer That would be perfectly fine for me.

**Comment by LiamHD** [comment]
Any progress on this?

**Comment by tobiasKaminsky** [comment]
If I understand @rullzer 
 in https://github.com/nextcloud/android/issues/2308#issuecomment-373140199 correctly, we would have to wait for NC14 to have this enhancement implemented on server side?

**Comment by mario** [comment]
I already implemented automated login using both username&pass (not via link though yet) for Talk, so I can do the same for Nc app.

**Comment by rullzer** [comment]
@tobiasKaminsky yes. Well you could already have the url entered on scanning. I need to look in if/how you can pass on the username.

**Comment by tobiasKaminsky** [comment]
With next NC16 you can generate a QR code on security page and this can be scanned and will directly login you into NC app.
