### ISSUE TITLE
E2E encryption : not able to re-enable a folder as E2E encrypted

### ISSUE THREAD

**Issue by GLLM** [nextcloud/android#2309]
### Actual behaviour
I've set a folder as being E2E encrypted (from Windows client). It worked.
I have some random files (testing the tech now, not using it) in there.

Yesterday, from my Android 8 phone, I set the folder as Not Encrypted :
* files remain encrypted in the folder ... is it expected ?
* I cannot set it back to E2E encrypted folder on Android ... had to do it again from the Windows client
* Once I set it back on Windows client : the decrypted files appeared ... along with the encrypted ones ! These "duplicates" are the encrypted & non-encrypted versions.

### Expected behaviour
* EITHER Not being able to disable E2E encryption if files will not be decrypted, hence (files) will not be available anymore
* OR : decrypt files before setting it back to normal (not E2E) fodler

* AND : be able to re-enable the E2E encryption from the Android client
 
### Steps to reproduce
1. create a folder, put some files in it
2. sync with your winodws & android client
3. go on android, set the folder as NOT encrypted ... you cannot se it back

### Environment data
Android version: 8.0
Device model:  Samsung Galaxy S8+
Stock or customized system: STOCK
Nextcloud app version: E2E 1.0.4
Nextcloud server version: 13.0.0 STABLE
Android app version : 3.0.2

**Comment by tigernero79** [comment]
can you test with android application nextcloud 3.0.3 and let me know if you have the same problem?

**Comment by GLLM** [comment]
Hi @tigernero79 !
I will as soon as it is available on F-Droid  :-)
Thanks

**Comment by xXSTrikeXx** [comment]
@GLLM That I was guessing to, I was close to write it for @tigernero79 XD 
Well surprise me, if 3.0.3 works :) :D

**Comment by tobiasKaminsky** [comment]
3.0.3 will not help.
I am currently unsure why your android client does not recognize the E2E folder.
It should open up a dialog where you have to enter the 12words passphrase.
