### ISSUE TITLE
Updating sync capabilities on mobile

### ISSUE THREAD

**Issue by proninyaroslav** [nextcloud/android#231]
Hello. As you can see, in OwnCloud this function has already been implemented https://github.com/owncloud/android/issues/1677. Do you plan adding this capability in Nextcloud?

**Comment by AndyScherzinger** [comment]
You can also see the discussion here: #93

**Comment by proninyaroslav** [comment]
@AndyScherzinger 
Thank you for responding to my question :)
The most important feature for me - an opportunity to select folder on my device, which would be synchronized with my server. Simply put, I would have used it for some of backup data on my phone.

**Comment by AndyScherzinger** [comment]
@proninyaroslav thanks for the details. By synchronized you mean back and forth to the server as in changes on the server might happen which you want to have pushed to the client, or something like e.g. a whatsapp folder and all its images auto-copied to the server?

**Comment by proninyaroslav** [comment]
Of course, desirable if the changes are synchronized in both directions (`server <-> client`), but if this task is difficult, then for starters you can make synchronization with direction `server <- client`.

**Comment by AndyScherzinger** [comment]
The later is something we have on our roadmap anyways since Android N break the instant upload mechanism, so we will need a change here that will most likely be a folder observer and thus giving you `server <- client`

**Comment by proninyaroslav** [comment]
@AndyScherzinger 
Excellent. Keep us informed :)
