### ISSUE TITLE
Wrong account displayed on notification

### ISSUE THREAD

**Issue by rullzer** [nextcloud/android#2315]
1. Have 2 accounts setup  in the android app, `Account A` and `Account B`
2. Switch to `Account B` in the client
3. Close the app (probably also work when it stays open but I didn't test)
4. Get a notification in `Account A`
5. Click on the notification

Now:
App is opened on `Account B`'s notification screen and you see an empty list

Expected:
App is opened on `Account A`'s notification screen and you see your notification

**Comment by tobiasKaminsky** [comment]
Additionally we should also switch completely to account A. If the user wants to do something with the notification (e.g. download file), it is better to be in the correct account directly.

**Comment by mario** [comment]
This will be fixed once notifications are improved.

**Comment by ferdiga** [comment]
I have a similar problem:
Sometimes I get a notification that another user created a file (pdf?) which was synchronized from my linux desktop some month ago.

**Comment by tobiasKaminsky** [comment]
@ferdiga can you open up a new issue on this? 
Do you get also this notification on webUI? If so, this is more related to server, I assume.

**Comment by mario** [comment]
This is normal @tobiasKaminsky. The TTL for notifications is 24 hours, so in theory you could receive it after say 23 hours and 14 minutes.

**Comment by tobiasKaminsky** [comment]
> The TTL for notifications is 24 hours

> …some month ago…

This seems not be the explanation then…

**Comment by mario** [comment]
Ah sorry. Ttl is 4 weeks actually. But yea, months ago o.o

**Comment by tobiasKaminsky** [comment]
Do we want to adjust this? 
I would expect that a notification > 1 week may already be outdated…
