### ISSUE TITLE
InstantUpload corrupt JPEG pictures

### ISSUE THREAD

**Issue by benpro** [nextcloud/android#2316]
### Actual behaviour

- I synchronize my SnapSeed folder with InstantUpload, and some pictures got corrupted while transferred on my Nextcloud instance. 
- https://pics.benpro.fr/TIADhO5q/X5fhbyfb.jpeg
- My guess is that InstantUpload send the picture before the picture was successfully written by SnapSeed/Android.

### Expected behaviour

- No corruption
 
### Steps to reproduce

1. Install SnapSeed
2. Edit some pictures & configure InstantUpload to upload SnapSeed folder
3. Some pictures got corrupted

### Environment data
Android version:
Nougat

Device model: 
Samsung Galaxy Tab S2

Stock or customized system:
Lineage OS 14.1

Nextcloud app version:
3.0.2-fdroid

Nextcloud server version:
13.0.0

### Logs

TODO

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

**Comment by tobiasKaminsky** [comment]
@mario I understood that file locking should prevent this?
Do you have an idea?
