### ISSUE TITLE
Allow to see / sync hidden folders

### ISSUE THREAD

**Issue by xXSTrikeXx** [nextcloud/android#2319]
In autoupload settings in the 3 dot layer there should be added a new layer  'see hidden folders' to allow also to sync to hidden folders.

In the settings of the app there should be an option to display all files, even hidden, or not 😉 

ref bug: #2318

**Comment by AndyScherzinger** [comment]
> In the settings of the app there should be an option to display all files, even hidden, or not

In the settiings of the app there is an option to display/hide hidden files... ;)

**Comment by xXSTrikeXx** [comment]
I thought now about this a little while. What about my first sentence as suggestion/enhancement? I think not everyone want enable to view hidden files all the time. This layer would improve the UX that they can quick set up hidden folders/files for syncing in autouploader settings. Think about it and lets discuss. 👍  😉 
@AndyScherzinger @nextcloud/designers

**Comment by AndyScherzinger** [comment]
I don't have a strong opinion on this but get the idea to be able to sync to hidden folders, while that would just mean showing them in the remote folder chooser and maybe also show them in the local folder chooser for custom folders. What I don't know is if this should be optional or just the default since adding a setting screen or general auto upload settings adds a layer of complexity where I'd rather like to have smart defaults. So looking forward to feedback from @nextcloud/designers :)

**Comment by tobiasKaminsky** [comment]
I think "hidden folders" should always be optional and default is to not show them.
There is a reason why they are hidden, so they should never treated as regular folders.

**Comment by xXSTrikeXx** [comment]
@tobiasKaminsky Yes, i dont want to see all time hidden folders by default. But as enhancement there could be a layer in the 3 dot menu to allow to show them in the process while adding folders to autouploader settings. Then it´s easier to select hidden files, when the default is **not** to show hidden files. 😉 
awaiting feedback from @nextcloud/designers

**Comment by jancborchardt** [comment]
Showing hidden folders/files is a setting which on mobile is fine to be only in the main settings. Putting it in the 3-dot-menu would make it way too present there, and drown out other more important things.

**Comment by xXSTrikeXx** [comment]
@jancborchardt  There is a lot space for the important things like that. See screenshot. And I think there should be also a option for another sorting type.
The layer “show hidden files“ can also be an enhancement only for the expert mode in the 3dot menu. Atm the 3dot menu includes only a “new directory“ layer. See screenshot:
