### ISSUE TITLE
Some of the functions of the Android side after accessing the ldap service are not available

### ISSUE THREAD

**Issue by dxj728** [nextcloud/android#2320]
### Actual behaviour
When you access the ldap server and log in using ldap users, not only is it slower, but the favorites and pictures in the drawer bar have been sharing these features all the time, but no matter how long they are, they won't show the result.

### Expected behaviour
 display normal results after loading
 
### Steps to reproduce
1. Correctly configure the ldap account on the server side
2. Then log in to the android client using the ldap account
3. Use drawer bar collection, pictures, etc., but no results

### Environment data
Android version: android 5.1.1

Device model: Nexus5

Stock or customized system:

Nextcloud app version: v3.0.1

Nextcloud server version:13.0.0

![screenshot_1520561711](https://user-images.githubusercontent.com/18740322/37186992-272f7dfa-2383-11e8-9cd5-e423b250fe26.png)

**Comment by xXSTrikeXx** [comment]
Can you update to latest v3.0.3 and give it a try? 😃

**Comment by AndyScherzinger** [comment]
Any news @dxj728 ?

**Comment by tobiasKaminsky** [comment]
This is related to username vs. userId problem, which will be fixed globally for the version after the next one.

**Comment by tobiasKaminsky** [comment]
This should be fixed now, @dxj728, please test and re-open if not.
