### ISSUE TITLE
Improper text wrapping in the grid view of All files activity

### ISSUE THREAD

**Issue by arundhatigupta** [nextcloud/android#2321]
### Actual behaviour

Currently, the height of the text contents in the text view is greater than the height of the view itself. Due to this a fraction of the height of the text strings becomes invisible.

### Expected behaviour

The text needs to be wrapped properly within the text view.
 
### Steps to reproduce

1. Open the app and log into your account.
2.  Open the All files activity 
3. Choose Grid view from the Options menu in the Action Bar
4. You'll see the following, as in the attached screenshot.

### Environment data

Android version: 7.0

Device model: Xiaomi Redmi Note 4

### Screenshot

![nextcloud_text_wrap](https://user-images.githubusercontent.com/30979369/37190402-89a42fc0-237f-11e8-9218-8ac6a55c3ac1.jpg)

**Comment by arundhati24** [comment]
@nextcloud/designers Would you please have a look at this issue? :) I think this is not a big issue, but still this should be fixed. :)

**Comment by xXSTrikeXx** [comment]
@arundhati24 It is the same or associated with #2305 ?

**Comment by jancborchardt** [comment]
Yeah, good point.

The filetype icons could be a bit smaller here, they are very big. (Image previews should retain size thought.) Then the text has more space and can move up a bit.

**Comment by AndyScherzinger** [comment]
I agree with Jan and no, has nothing to do with #2305 imho

**Comment by arundhati24** [comment]
@xXSTrikeXx As @AndyScherzinger mentioned, it is not the same as #2305  :)

**Comment by AndyScherzinger** [comment]
@arundhati24 since Jan from designers and me from dev perspective are fine with the issue and Jan proposed a way to do it I think it is good to go 👍

**Comment by joshtrichards** [comment]
Can't find the ultimate merged PR, but this behavior does not exist today.
