### ISSUE TITLE
REQ: clear the history of the "Uploaded" section.

### ISSUE THREAD

**Issue by timmersr** [nextcloud/android#2324]
Actual behaviour

-Tell us what happens

The "Uploaded" section has hunderds of succesful uploads with small previews listed over the last year. (In my case) the originals of these pictures have been automatically deleted via Auto-Upload.

-Tell us what should happen

The possibility to select the whole or individual entries in the "Uploaded" section and delete them.
After seeing that the upload has taken place, the long history serves no purpose in this section for me anymore (other than to show me the preview of a embarrassing picture I have deleted :-)

Steps to reproduce

    Take a photo
    Go to Main menu, Uploads, browse to "Uploaded" section.

Environment data

Android version: 7.1.1

Device model: Samsung Note 8

Stock or customized system: Stock

Nextcloud app version: 3.0.3

Nextcloud server version: 13.0.0

**Comment by xXSTrikeXx** [comment]
You can already clear all recently uploads in the 3 dot menu 😉

**Comment by mario** [comment]
To clarify, you need to enable expert mode in settings to do that.

**Comment by tobiasKaminsky** [comment]
Although this is possible via a (hidden) button, what about following:
show only 50 succesfull uploads and when reaching bottom, dynamically load the next ones?

Failed and currently pending should be shown always in full length.

**Comment by AndyScherzinger** [comment]
That might be a solution while we still polute the database and should have some kind of housekeeping deleting anything older than x.

**Comment by tobiasKaminsky** [comment]
Right, I forgot the database...
What about showing all uploaded items, but delete items older than 7 days when entering the activity?

**Comment by mario** [comment]
I was thinking cleaning it via a job every now and then.

**Comment by AndyScherzinger** [comment]
> delete items older than 7 days

Sounds good to me while I do like @mario's approach do do this via a job since the user then doesn't have to "wait"

**Comment by tobiasKaminsky** [comment]
I just have started an async task, but a job is also fine.
-> https://github.com/nextcloud/android/issues/2339
