### ISSUE TITLE
Auto upload ignores files already in auto-upload folders beforehand

### ISSUE THREAD

**Issue by Bugsbane** [nextcloud/android#2325]
### Steps to reproduce
1. Install the NC 3.0.3 app. Switch on auto upload for one of the folders already detected by auto-upload, or add a new folder maually and switch sync on. Notice that files are shown in that folder in "Auto uploads"
2. Go to "Uploads"
3. Notice that it finds and uploads  nothing uploads until a new file is added, and even then everything but the new files are ignored.

### Expected behaviour
When adding a new auto-upload folder, or switching it on, all files already in the folder should then be uploaded.

### Actual behaviour
No preexisting files get uploaded when adding / switching on an auto-upload folder sync.

### Environment data
Android version:
6.0.1

Device model: 
ZTE Z957
Samsung GalaxyS5

Stock or customized system:
Stock

Nextcloud app version:
3.0.3 (and previous versions from 2.0+ onwards)

Nextcloud server version:
13 (and all previous versions back to owncloud 1.0)

## Server configuration detail

**Operating system:** Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.51-3 (2017-12-13) x86_64

**Webserver:** nginx/1.6.2 (fpm-fcgi)

**Database:** mysql 5.5.59

**PHP version:** 5.6.33-0+deb8u1
Modules loaded: Core, date, ereg, libxml, openssl, pcre, zlib, bcmath, bz2, calendar, ctype, dba, dom, hash, fileinfo, filter, ftp, gettext, SPL, iconv, mbstring, session, posix, Reflection, standard, shmop, SimpleXML, soap, sockets, Phar, exif, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlwriter, zip, cgi-fcgi, PDO, apcu, curl, gd, imagick, intl, json, ldap, mcrypt, mysql, mysqli, pdo_mysql, readline, mhash, apc, Zend OPcache

**Nextcloud version:** 13.0.0 - 13.0.0.14

**Updated from an older Nextcloud/ownCloud or fresh install:** 
Updated from previous Nextcloud versions (and OC before that)

**Where did you install Nextcloud from:** unknown
DOwnloaded source from Nextcloud.com

<details><summary>Signing status</summary>

Array
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.6.1
 - admin_audit: 1.3.0
 - bookmarks: 0.10.1
 - calendar: 1.6.1
 - comments: 1.3.0
 - dav: 1.4.6
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_external: 1.4.1
 - files_pdfviewer: 1.2.0
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - files_videoplayer: 1.2.0
 - firstrunwizard: 2.2.1
 - gallery: 18.0.0
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - mail: 0.7.10
 - news: 12.0.1
 - nextcloud_announcements: 1.2.0
 - notes: 2.3.2
 - notifications: 2.1.2
 - oauth2: 1.1.0
 - password_policy: 1.3.0
 - provisioning_api: 1.3.0
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - spreed: 3.1.0
 - survey_client: 1.1.0
 - systemtags: 1.3.0
 - theming: 1.4.1
 - twofactor_backupcodes: 1.2.3
 - updatenotification: 1.3.0
 - user_ldap: 1.3.1
 - workflowengine: 1.3.0
Disabled:
 - bruteforcesettings
 - circles
 - contacts
 - encryption
 - previewgenerator
 - tasks
 - twofactor_totp
 - user_external

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "localhost",
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "13.0.0.14",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbtableprefix": "***REMOVED SENSITIVE VALUE***",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "UTC",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "ldapIgnoreNamingRules": false,
    "memcache.local": "",
    "memcache.locking": "",
    "theme": "",
    "loglevel": 2,
    "maintenance": false,
    "appstore.experimental.enabled": true,
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "php",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "updatechecker": true,
    "logout_url": "***REMOVED SENSITIVE VALUE***",
    "htaccess.RewriteBase": "\/",
    "updater.server.url": "https:\/\/updates.nextcloud.org\/updater_server\/",
    "updater.release.channel": "stable",
    "preview_libreoffice_path": "\/usr\/lib\/libreoffice\/program\/soffice",
    "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
    "app.mail.imaplog.enabled": true,
    "app.mail.imap.timeout": 60
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

<details><summary>LDAP configuration (delete this part if not used)</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

**Comment by xXSTrikeXx** [comment]
At the moment it´s not implemented. But it´s a longer goal to implement it in the future. Have a loog at #285 This is the roadmap to the final app. Feel also free to contribute 😉
Atm only recently taken files will be uploaded after enabling autouploader for these files 😃

**Comment by tobiasKaminsky** [comment]
@xXSTrikeXx thank you very much for helping us here with answering issues :+1:

**Comment by xXSTrikeXx** [comment]
@tobiasKaminsky  Year, I try my best to support you in supporting issues while you can go on silent and program the best code every user wants 😄 
We both have advantages: You can program calmly, and I can learn about it 🙄 😆 🤣 😉
