### ISSUE TITLE
Feature Request: 2 click authorization for apps to use NC account

### ISSUE THREAD

**Issue by Bugsbane** [nextcloud/android#2326]
Currently I have the following apps all installed accessing my Nextcloud server:

- Nextcloud
- Nextcloud dev
- Tasks (new caldav branch)
- Davdroid
- Simpletask Nextcloud
- Notes for Nextcloud
- Advanced Call Recorder
- Davdroid
- Nextcloud News
- Nextcloud Bookmarks

...and a couple I don't even remember the name of (like the FOSS app I use to track my car expenses, which syncs over Nextcloud).

Each of these I had to go through and painstakingly log in via the web interface, go to the personal settings menu, then security, then set up an app password, then find a way to copy that  password across to my phone, then find and enter the server url (some apps are fine with the base url, some need the full path to remote.php), the user name and the app token...

...and all of that is just if it's all correct and working the first time! Honestly, each time, it's tempting just to use my administrator password as I know it and it's much quicker to enter. This is not good user experience or encouraging security!

I really wish that after installing the nextcloud app, in the other apps, I could just click a "Use Nextcloud account" button, that just asked the Nextcloud Android app for a 1-click permission to access my nextcloud server. If there is more than one account, then it would just be one more click to choose which one.

I imagine that behind the scenes it would work something like this:
1. User has installed and setup the Nextcloud Android app.
2. User installs an app designed to use this new system and clicks on a "Use Nextcloud account" (or similar) button. (The requesting app)
3. The requesting app passes a request to access a nextcloud account, with it's name and whether it needs file access, to the Nextcloud app.
4. The nextcloud app pops up a dialogue asking whether to allow the requesting app access to the nextcloud account (and files if requested). If authorized, it asks which account to use (of the ones set up in the NC apps).
5. After authorization, the NC app passes the requesting app name to the server, and gets back an app token.
6. The Nextcloud app passes the username and token to the requesting app, which then uses that from then on to sync with the nextcloud account.

If permission was granted, then the app would automatically pass the requesting app name to the server, and get back a new app token from the server. This would be passed back to the original requesting app, which would use these from now on.

**Comment by tobiasKaminsky** [comment]
There are already several ideas/approaches, one is https://github.com/nextcloud/ownCloud-Account-Importer/issues/3 which is doing the same you want to have.

However, time is a big problem and thus it is not delevoped any further.

**Comment by AndyScherzinger** [comment]
shppied with 3.3.x while apps need to implemment the login via the Nextcloud app (see nextcloud news for example.
