### ISSUE TITLE
Backup Contacts to selected Nextcloud Instance

### ISSUE THREAD

**Issue by maxmeyer** [nextcloud/android#2327]
### Actual behaviour
- Backup of contacts is enabled
- The app is configured to use to separate accounts - one which is internal (local LAN) and one is external (internet)
- The app is configured to upload a backup of my contacts
- The app uploads the contact backup to the external nextcloud only although the internal account was selected before activating the contact backup
- When I switch to "Settings > Backup contacts" the app switches the theme from internal to external

### Expected behaviour
- The app should upload contact backups only using the currently active nextcloud account 
 
### Steps to reproduce
1. Add at least two different accounts to the app - with two different colored themes at best
2. Activate account A
2. Activate contact backups "Settings > Backup contacts" 
3. Upload contact backup
4. Activate the other account B
5. Try to activate contact backu for that account. "Settings > Backup contacts" 

### Environment data
Android version: 6.0.1

Device model: BlackBerry Priv STV100-4

Stock or customized system: Stock

Nextcloud app version: 3.0.3

Nextcloud server version: 13.0.0.14

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky any ideas on this?

**Comment by tobiasKaminsky** [comment]
We used the saved account, if available, instead of the current one.
So, if an user switches the app and had a saved instance of preference dialog, it could happen that the wrong account was used.
Fix is in: #2488

**Comment by AndyScherzinger** [comment]
Merged for 3.2

**Comment by maxmeyer** [comment]
Thanks.
