### ISSUE TITLE
unable to add cloud account 

### ISSUE THREAD

**Issue by thdrmz** [nextcloud/android#2328]
### Actual behaviour
Upgrade to Server Version 13

### Expected behaviour
unable to login with android app
 
### Steps to reproduce
do have any problems on cloud server version 12

### Environment data
Android version:
7.1
Device model: 
Samsung S5 - SM-G901F

Stock or customized system:
linage os
Nextcloud app version:
current version in app store
Nextcloud server version:
13
#### Web server error log
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here

Mar 11 17:17:29 chicago NextCloud[14874]: {webdav} Exception: {"Exception":"Sabre\\DAV\\Exception\\BadRequest","Message":"expected filesize 10000000 got 5144576","Code":0,"Trace":"#0 \/var\/www\/cloud\/apps\/dav\/lib\/Connector\/Sabre\/Directory.php(151): OCA\\DAV\\Connector\\Sabre\\File->put(Resource id #22)\n#1 \/var\/www\/cloud\/apps\/dav\/lib\/Upload\/UploadFolder.php(39): OCA\\DAV\\Connector\\Sabre\\Directory->createFile('00000263', Resource id #22)\n#2 \/var\/www\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1096): OCA\\DAV\\Upload\\UploadFolder->createFile('00000263', Resource id #22)\n#3 \/var\/www\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(525): Sabre\\DAV\\Server->createFile('uploads\/thomas\/...', Resource id #22, NULL)\n#4 [internal function]: Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#5 \/var\/www\/cloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#6 \/var\/www\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(479): Sabre\\Event\\EventEmitter->emit('method:PUT', Array)\n#7 \/var\/www\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#8 \/var\/www\/cloud\/apps\/dav\/lib\/Server.php(283): Sabre\\DAV\\Server->exec()\n#9 \/var\/www\/cloud\/apps\/dav\/appinfo\/v2\/remote.php(35): OCA\\DAV\\Server->exec()\n#10 \/var\/www\/cloud\/remote.php(164): require_once('\/var\/www\/cloud\/...')\n#11 {main}","File":"\/var\/www\/cloud\/apps\/dav\/lib\/Connector\/Sabre\/File.php","Line":178}
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
@thdrmz do you still have login issues? Afaik Nc13 should work fine and works fine for my devices.

cc @tobiasKaminsky if any further infos are needed.

**Comment by tobiasKaminsky** [comment]
Can you create us a test account, test if the problem occurs also there and if so send the credentials to tobias at nextcloud dot com with a reference to this issue?

**Comment by tobiasKaminsky** [comment]
No response within the last month, therefore closing.
Please feel free to reopen with additional infos, if the problem still exists.
