### ISSUE TITLE
Crash loop when showing upload history

### ISSUE THREAD

**Issue by marmeladema** [nextcloud/android#2329]
### Actual behaviour
When i start the application, unlock it with my fingerprint and try to show the upload history, it crashes. Ii then restarts by itself and if I unlock it again, it crashes directly, i guess because it try to directly show upload history.
For the record, i was abroad without internet for a few days and took photos. There should be around 240 photos waiting in failure state because of missing internet connection in the upload history.

### Expected behaviour
It should not crash and show the upload history.
 
### Steps to reproduce
1. Start the application
2. Unlock it with your fingerprint
3. Show the upload history

### Environment data
Android version: Android 8.1.0 from CopperheadOS

Device model: Nexus 5X

Stock or customized system: CopperheadOS

Nextcloud app version: 3.0.3

Nextcloud server version: 13.0.0

#### Web server error log:
Nothing

#### Nextcloud log (data/nextcloud.log)
Nothing

**Comment by ardevd** [comment]
Could you post a stacktrace of the crash?

**Comment by xXSTrikeXx** [comment]
You can debug it a little bit for us, then we can check whats wrong. Here is an instruction for debugging with adb: https://github.com/nextcloud/android#getting-debug-info-via-logcat

**Comment by AndyScherzinger** [comment]
@marmeladema any update regarding stack trace / logcat? If so, please post and re-open.
