### ISSUE TITLE
CM13 InstantUpload won't start

### ISSUE THREAD

**Issue by okias** [nextcloud/android#233]
After switching from ownCloud Beta to Nextcloud Beta, it stopped uploading (it not even tries and fails) pictures with InstantUpload, but manual upload works.

### Environment data
Android version: 6.0.1

Device model: S4 9505

Stock or customized system: Cyanogenmod 13

Nextcloud app version: latest F-Droid

Nextcloud server version: 10.0

### Logs

**Comment by AndyScherzinger** [comment]
Hi @okias can you post the apps log (in the apps settings screen) and a screenshot of the settings screen? :)

**Comment by okias** [comment]
log is empty
![screenshot_20160901-134003](https://cloud.githubusercontent.com/assets/2457435/18166165/d04c2576-7049-11e6-8649-4d1ac56a19ce.png)

**Comment by AndyScherzinger** [comment]
Hmmm, @tobiasKaminsky can you have a look at this. The settings look fine to me. Unfortunately I can't test the instant upload feature on my phone (Android N) or in the emulator right now (internet connection issues).

**Comment by okias** [comment]
Fixed by Nextcloud or Cyanogenmod update...

Thank you!
