### ISSUE TITLE
Do not show conflict dialog if app is in background

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#2333]
Following up discussion from https://github.com/nextcloud/android/pull/2253#discussion_r173728945:

Currently (with old and new sync implementation) a dialog showing a conflicting file can be shown even if the app is in background, which should be avoided as it distracts the user.

In my opinion there are three possible solutions
- show a notification once the conflict appears 
- show conflicting dialog once the app is resumed 
- do not show anything, but only if user enters the folder show the conflicting file with a red "!". When clicking the file show the conflict dialog.

What do you think? For me it boils down how urgent do we want to treat those conflicts...

**Comment by tobiasKaminsky** [comment]
This is an example of the dialog that is showing up "out of a sudden" if a sync conflict is detected.

![2018-03-12-130803](https://user-images.githubusercontent.com/5836855/37283048-dce2f152-25f6-11e8-930b-c8e9bcc14cc2.png)

What is missing from my side:
- file name (with storage location)
- thumbnail, to distinguish images
- file size? 
- modification date

In general something like this:
![image](https://user-images.githubusercontent.com/5836855/37283133-2cb4e582-25f7-11e8-9504-5b170390d87d.png)

Anything else? @nextcloud/designers

**Comment by joshtrichards** [comment]
Can't find the associated PR, but this is the behavior today.
