### ISSUE TITLE
Can't view External Storage in APP

### ISSUE THREAD

**Issue by zepolam** [nextcloud/android#2336]
Hello,

I can't view the SMB external storage connected (Netapp CIFS share) using the Android APP

With web browser can view without problems. 

Android version: 8.0.0
Device model: Samsung Galaxy S8 - SM-G950F
Nextcloud app version: 3.0.3
Nextcloud server version: 13.0.0

Thanks!

**Comment by tobiasKaminsky** [comment]
Can you create us a test account, test if the problem occurs also there and if so send the credentials to tobias at nextcloud dot com with a reference to this issue?

**Comment by tobiasKaminsky** [comment]
Possible dup of #2232

**Comment by zypro** [comment]
> I have had this problem as well, it was fixed when I use "Log-in credentials, save in database" instead of "Log-in credentials, save in session" under Settings -> External storages.

Is this setting still available in nexcloud 17+ ? Can't find it there...

**Comment by tobiasKaminsky** [comment]
It is, in settings, but you must be an Admin I belive.
Settings -> external storage

![image](https://user-images.githubusercontent.com/5836855/79344440-238fb600-7f30-11ea-81ca-ec2f2ab4d742.png)
