### ISSUE TITLE
Permanent notification running

### ISSUE THREAD

**Issue by Philippe-Arnaud** [nextcloud/android#2337]
The application is showing a permanent notification (that cannot be swiped) in the notification slider of Android.

The problem exists in Android 7 and 8 as well.

Should it be considered as a server side problem?

**Comment by mario** [comment]
This is fixed by https://github.com/nextcloud/android/pull/2253, though it shouldn't exist on Android 7.

**Comment by Philippe-Arnaud** [comment]
What can I do to share details about this issue?

**Comment by mario** [comment]
Show a screenshot from Android 7? :)

**Comment by Philippe-Arnaud** [comment]
Last update resolved the issue on 8.

7 is indeed not concerned.

**Comment by mario** [comment]
:) Cool, thanks for the feedback @Philippe-Arnaud

**Comment by AndyScherzinger** [comment]
So close then?

**Comment by mario** [comment]
@AndyScherzinger done.
