### ISSUE TITLE
Fails to upload bigfile when chunk assembly take more than 60 seconds

### ISSUE THREAD

**Issue by seisen** [nextcloud/android#234]
### Actual behaviour

he Android App upload a bigfile, it fails when upload seem to be complete.
When the last chunk is uploaded, Owncloud Server assemble all chunks and the process can take a long time.
If it takes more than 60 seconds, the Android App abort and notify:
"An error occurred whilst waiting for the server, the operation couldn't be done"

Owncloud Server is served by nginx. A HTTP Code 499 means that the http client closed the socket.
### Expected behaviour

The Android App should wait for the chunk assembly completion.
### Steps to reproduce
1.  With Android App, upload a big file, assembling all chunk must take more than 60 seconds
2.  wait
3.  Android App notify a socket error
### Environment data

Android version: 6.1.0
Device model: Sony Xperia Z5
Stock or customized system: stock
ownCloud app version: 1.2.0
ownCloud server version: 10.0.0
### Logs

```
1.2.3.4 - user [01/Sep/2016:14:08:13 +0200] "PUT
 /remote.php/webdav/Photos/Upload/videos/MOV_001.mp4-chunking-1901-575-573
 HTTP/1.1" 201 1169 "-" "Mozilla/5.0 (Android) ownCloud-android/1.2.0" "-"
 msec="1472731693.423" request_length="1024430"
 request_time="2.795" "connection_requests=77"
1.2.3.4 - user [01/Sep/2016:14:09:13 +0200] "PUT
 /remote.php/webdav/Photos/Upload/videos/MOV_001.mp4-chunking-1901-575-574 
 HTTP/1.1" 499 0 "-" "Mozilla/5.0 (Android) ownCloud-android/1.2.0" "-" 
 msec="1472731753.602" request_length="281163" 
 request_time="60.086" "connection_requests=78"
```

**Comment by seisen** [comment]
also found in Owncloud https://github.com/owncloud/android/issues/1768

**Comment by AndyScherzinger** [comment]
@seisen this will probably be resolved by #168 which has been implemented and is scheduled for the next release. 

@tobiasKaminsky right? Or would this just help on the restart part so that only the last junk(s) would have to be uploaded?

**Comment by seisen** [comment]
Is there a daily build i can test ? 
https://download.nextcloud.com/android/
The latest is from 29 july

**Comment by AndyScherzinger** [comment]
As far as I remember it is already part of our beta release: https://f-droid.org/repository/browse/?fdfilter=com.nextcloud&fdid=com.nextcloud.android.beta

https://download.nextcloud.com/android/ only includes release candidates and stable releases.

**Comment by seisen** [comment]
same tried with Android client 20160809

`1.2.3.4 - user[01/Sep/2016:21:58:39 +0200] "PUT
 /remote.php/webdav/Photos/Upload/videos/MOV_001.mp4-chunking-19645721-575-574
 HTTP/1.1" 400 0 "-" "Mozilla/5.0 (Android) nextcloud-android/20160809"
 "-" msec="1472759919.115" request_length="281178"
  request_time="60.115" "connection_requests=3"
`

Error log:
```
2016/09/01 21:58:39 [info] 18752#0: *37 client prematurely closed connection,
 client: 1.2.3.5, server: xxxx.domain.org, request: 
 "PUT /remote.php/webdav/Photos/Upload/videos/MOV_001.mp4-chunking-19645721-575-574
 HTTP/1.1", host: "xxxx.domain.org"

```

```

**Comment by AndyScherzinger** [comment]
@seisen what happens when you retry the upload from the uploads view in the main menu? Does it then resume and finish the upload? About the 60 seconds is the with regards to the total upload time or after the last chunk the time that need to be taken for assembly?

**Comment by seisen** [comment]
The app checks if the file exists and only do one PUT which timeout after 60 seconds.

```
1.2.3.4 - user[02/Sep/2016:09:41:53 +0200] "GET 
 /index.php/avatar/user/384 HTTP/1.1" 200 1383 "-" 
 "Mozilla/5.0 (Android)  nextcloud-android/20160809" "-" msec="1472802113.752" 
 request_length="255" request_time="0.448" "connection_requests=1"
1.2.3.4 - user [02/Sep/2016:09:41:59 +0200] "HEAD 
 /remote.php/webdav/Photos/Upload/videos/ HTTP/1.1" 200 1147 "-" 
 "Mozilla/5.0 (Android) nextcloud-android/20160809" "-" msec="1472802119.333" 
 request_length="269" request_time="0.447" "connection_requests=2"
1.2.3.4 - user [02/Sep/2016:09:42:00 +0200] "HEAD 
 /remote.php/webdav/Photos/Upload/videos/MOV_001.mp4 HTTP/1.1" 404 1089 "-" 
 "Mozilla/5.0 (Android) nextcloud-android/20160809" "-" msec="1472802120.306" 
 request_length="281" request_time="0.787" "connection_requests=3"
1.2.3.4 - user [02/Sep/2016:09:43:00 +0200] "PUT 
 /remote.php/webdav/Photos/Upload/videos/MOV_001.mp4-chunking-19645721-575-574 HTTP/1.1" 400 0 "-" 
 "Mozilla/5.0 (Android) nextcloud-android/20160809" "-" msec="1472802180.640" 
 request_length="281166" request_time="60.191" "connection_requests=4"
```

**Comment by AndyScherzinger** [comment]
@seisen can you give the latest beta (or later this week the final 1.4.0) another try? We did increase the last chunk timeout for uploads.

**Comment by tobiasKaminsky** [comment]
@selsen can you test it, again?

**Comment by Selsen** [comment]
@seisen

**Comment by tobiasKaminsky** [comment]
No response within the last month, therefore closing.
Please feel free to reopen with additional infos, if the problem still exists.
