### ISSUE TITLE
grant access error

### ISSUE THREAD

**Issue by lasaa2** [nextcloud/android#2341]
### Actual behaviour
I have change url of my nextcloud server. The app loops grant access without asking new url. There isn't cancel or back button or something to fix url. 

Grant access has looping problems without changing server url last days.

### Expected behaviour
The app will asks new url if grant access fails or there are buttons with new login methods.

### Steps to reproduce
1. 
2. 
3. 

### Environment data
Android version: 7.0

Device model: Samsung S7, SM-G930F

Stock or customized system:

Nextcloud app version: 4.0

Nextcloud server version: newest of 12

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by xXSTrikeXx** [comment]
You need to delete your old account and add a new one with the right URL ;)
