### ISSUE TITLE
Highlight items in the file browser on click

### ISSUE THREAD

**Issue by Nutomic** [nextcloud/android#2343]
### Actual behaviour
When you tap on an item in the file browser, there is no indication that the tap was registered. Other apps usually turn the item background gray in this case. This is independent from the background change after a long tap.

This works correctly in the settings screen, if you click on an item there, the item background will turn gray while your finger is on the screen.

### Expected behaviour
Items in the file browser should be highlighted on touch, same as in the settings screen (and most other Android apps).
 
### Steps to reproduce
1. open file browser in nextcloud app
2. click an item
3. there is no onscreen indication that the click was successful
4. repeat the same steps on the settings screen, note the background change

### Environment data
Android version: 7.1

Device model: LG G4

Stock or customized system: LineageOS

Nextcloud app version: 3.0.3

**Comment by AndyScherzinger** [comment]
@Nutomic thanks for the report and you are right, I could reproduce this on my device.

@tobiasKaminsky will this be fixed automatically via the RecyclerView PR?

**Comment by tobiasKaminsky** [comment]
About which screen do we talk? Upload file from within our app?
Then it is already working with latest master:

![2018-04-20-134751](https://user-images.githubusercontent.com/5836855/39049361-7813212e-44a1-11e8-9317-71af93833a42.png) ![2018-04-20-134756](https://user-images.githubusercontent.com/5836855/39049362-782f16d6-44a1-11e8-9319-974cae3f1633.png)

**Comment by Nutomic** [comment]
@tobiasKaminsky No, the main screen where you can browse your files/folders in Nextcloud. Called "All files" in the drawer.

**Comment by tobiasKaminsky** [comment]
Read it again, and now I understand that you do not mean multiple select, but instead if you click on a single item.
So you want to have a visualization that the single item was clicked.

https://guides.codepath.com/android/ripple-animation something like that, I guess?

PR -> #2519

**Comment by Nutomic** [comment]
Yep, thanks!
