### ISSUE TITLE
high battery usage without configuration

### ISSUE THREAD

**Issue by khumboldt** [nextcloud/android#2344]
### Actual behaviour
- When you install the app from Play store, open it and close it without a configuration, Android shows a notification after some time. The app has a high battery usage.

### Expected behaviour
- As no Nc server is configured, the app should do nothing in the background and there should be no warning about high battery usage
 
### Steps to reproduce
1. Download app from Play store
2. Open app but don't configure a Nextcloud server
3. Go to another app via the "Home" button, so the app is in the background.
4. After some time Android will show a message because of high battery usage

### Environment data
Android version: 7.0

Device model: Samsung Galaxy S7 edge

Nextcloud app version: 3.0.3

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky @mario imho then related to auto upload / keep available offline 
or in short "job scheduling"

**Comment by mario** [comment]
Well, either job scheduling or services.

**Comment by mario** [comment]
Let's see what 3.1 says about this :D

**Comment by xXSTrikeXx** [comment]
It´s duplicate of #2275
