### ISSUE TITLE
No option and not uploading videos 

### ISSUE THREAD

**Issue by chefboyct** [nextcloud/android#2346]
### Actual behaviour
-there is no more upload video options in the camera folder from nextcloud side nor videos are uploaded automatically. 

### Expected behaviour
-all files in the camera folder on the phone should be auto uploaded... No matter its video or pictures 
 
### Steps to reproduce
1. Take a video and pictures 
2. Pictures were uploaded but not videos 
3. 

### Environment data
Android version: Oreo 8.00

Device model: G8141 Sony XZ Premium

Stock or customized system: Stock 47.1.a.12.75

Nextcloud app version: 3.03

Nextcloud server version: 12.0.5

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by chefboyct** [comment]
Mobile version 3.03
Nextcloud server 12.0.5 (will update to 13.0.0 now as I see a new version)

**Comment by AndyScherzinger** [comment]
@chefboyct did you update the auto upload for videos? Video and Images are split, so there is one entry for video and one entry for images in the auto upload view and in order to have both uploaded you need to activate both. This is to be able to have different settings for when to upload such files (videos is probably a wifi only thing...).

Please re-open if you still have issues and beware that at this very moment existing files won't be uploaded, just files created _after_ activating auto upload for that folder (see #285)

**Comment by chefboyct** [comment]
@AndyScherzinger  Thanks for the reply. However for Sony phones.. both videos and photos are saved under one android folder /DCIM/100ANDRO. and in my auto upload option for the folder... it doesn't have a video option (used to have one long time ago but I am sure it was removed based on it would auto upload everything in that specific folder whether it is photos or videos) . But now it is no longer there nor working. I have a screenshot but I cannot post it here it seems... so please advise. Thanks,

**Comment by chefboyct** [comment]
Oh wait,,, there are two separated options with /DCIM/100ANDRO  so you are saying the other one is for video? let me try it out and thanks but very confusing.. :(

**Comment by chefboyct** [comment]
Ok, it is now working. As you mentioned, videos are separated from pictures... the reason why I didn't take notice because I took videos and pictures simultaneously on the same objects... Thanks!

**Comment by AndyScherzinger** [comment]
You are very welcome. :)
So you are saying the little icon is not very obvious, right?

@nextcloud/designers any ideas on how we could make this more obvious?
We could add a play icon overlay for the videos but that might lead to the impression that you can actually start the videos (which you can't) or make the icon larger but then it would be imbalanced with the header font size. So any feedback is highly appreciated. The split for image/video is on purpose btw. since this way we can offer separate auto upload configurations for the two types of media data per folder (explicitly request by several users)
![device-2018-03-14-105033](https://user-images.githubusercontent.com/1315170/37395047-8deb1b08-2775-11e8-8051-6b646eaa3663.png)

**Comment by chefboyct** [comment]
Hi @AndyScherzinger  

Thanks for the reply but there is no icon next to the video option. 
![screenshot_20180314-115543](https://user-images.githubusercontent.com/24209549/37395469-f3a10b20-277e-11e8-8578-0101f2c9bc06.png)

**Comment by chefboyct** [comment]
Ah, again... never mind... I see which icon you are talking about now... I guess I totally missed that! My bad! :(

**Comment by AndyScherzinger** [comment]
No worries and well that is why I asked the designers for feedback since it seems to be a UX matter as-in not obvious enough, so let's see if this can be enhanced.

**Comment by chefboyct** [comment]
Hi @AndyScherzinger  . No wI see what you are saying... and this is my suggestion... What about making that little "picture" or "video" icon a bit bigger and make it inline with first picture below? Then move ANDRO (folder name) to inline with the next picture below?

**Comment by AndyScherzinger** [comment]
@chefboyct do you have some kind of a mockup since I am not sure how this would then look like. I'd say it should keep the folder name in the header section since this is basically the divider between different folders/setups.

**Comment by chefboyct** [comment]
Something to this effect but just make the picture / video icon bigger which sitws above the first picture or video previews.. (sorry I am using Linux and not good with editing) 
![screenshot_20180314-115543 new](https://user-images.githubusercontent.com/24209549/37397776-258012e8-2785-11e8-81a5-1f730699ff9f.png)

**Comment by AndyScherzinger** [comment]
Sweet, Here is my take with paint... So the icons sizes and the alignment isn't perfect, but I tried to align the icon with the drawer icon and to align the list headers with the toolbar header:
![unbenannt](https://user-images.githubusercontent.com/1315170/37408982-887c1a78-279d-11e8-8e2e-a37f8876cc71.png)

**Comment by chefboyct** [comment]
Ah I see... well, either way... the icon size needs to be a bit bigger and more visible I think. But I guess once someone highlighted it to the users... it all becomes clear! Thanks for taking your time to answer my questions!

**Comment by AndyScherzinger** [comment]
You are very welcome and thanks for taking the time to report this issue. I'll see that I get this fixed for a future release (maybe not the next one though, to tight schedule...)

**Comment by AndyScherzinger** [comment]
@chefboyct I opened a PR for discussion with the other devs and designers, #2354 feel free to comment :)

**Comment by AndyScherzinger** [comment]
Hi @chefboyct I changed the layout according to our discussion here and it has been merged so it will be part of the 3.1 release.

**Comment by chefboyct** [comment]
@AndyScherzinger  I just saw the post and sorry I missed your e-mail. It looks good and let's see if anyone still miss the icon (video / photo) as I did... XD

**Comment by AndyScherzinger** [comment]
@chefboyct thanks and nothing to be sorry for :) Let's see if this helps with the usability / experience since btw you were at least the second person who had and issue with the different types of folder not being very clearly marked.

**Comment by chefboyct** [comment]
In the past there was a video option which you can tick but then it would all go into one user defined folder. Now with separate video (file type) options, then it will allow you to upload to different ones. I found it can be useful but not really a deal breaker for me... if that makes sense!  :)

**Comment by AndyScherzinger** [comment]
Yeah, I get that. You can of course still define the same folder. The use case for some user is rather another one... Upload images on cellular networks but upload videos only on wifi connections or even when charging only. :)

**Comment by chefboyct** [comment]
Ah, you are right... @AndyScherzinger  .. I totally forgot about the video uploading size and etc. Now that makes 100% sense to me! Thank you for being so thoughtful! 

Enjoy rest of your week and again making Nextcloud a great product!

**Comment by velis74** [comment]
Lucky I found this. Was also wondering why videos weren't being uploaded...

Any reason this copying / moving has to be done at all? Initially I just wanted to add the DCIM folder to NextCloud client, like I do on the PC, but it wouldn't let me...

**Comment by AndyScherzinger** [comment]
You should be able to. Do this via the top right menu adding it as a custom folder.

**Comment by velis74** [comment]
@AndyScherzinger I just went (again) through pretty much every menu entry I could find, even trying some out that sounded like what you suggested: I cannot find a feature like you mention.

**Comment by AndyScherzinger** [comment]
Do you find Auto Upload (in the Settings)? There you should have an option in the top-right 3-dot menu

**Comment by velis74** [comment]
That one I'm using already.

**Comment by AndyScherzinger** [comment]
Now I am confused 🤔 Thought you meant you don't find the custom auto upload folder menu item, no?

**Comment by velis74** [comment]
> Initially I just wanted to add the DCIM folder to NextCloud client, like I do on the PC, but it wouldn't let me...

I thought this was clear: I wanted to be able to specify the folder where Nextcloud client had its local root, e.g. /sdcard/DCIM/Camera. Not do some "auto upload" that has to move and rearrange files as it does its magic. Not that it's bad, I just find it redundant.

**Comment by AndyScherzinger** [comment]
Actual no. To answer your question you can't choose the local root of where the Nextcloud Android app puts its file and we don't plan to do so.

**Comment by velis74** [comment]
Yes, I agree. And I found my answer in this thread. 

I just wanted to share my experience with a different design between the PC client and Android client. I did not expect a reply about how it might be doable, but WAS super pleasantly surprised that you did, even if you misunderstood my comment.

I just verified and you seem to be one of the lead developers, so - as a fellow developer - I can tell you that I appreciate the effort. I also apologise for wasting your time. Except for the different UX that lead me to this issue, I'm supper happy with the app and the entire product, so, please, keep up the good work.

**Comment by AndyScherzinger** [comment]
Hi @velis74 thank you very much. I appreciate you input and feedback and happy to help. The comment popped up so I tried to help :)
