### ISSUE TITLE
Check if internet is walled only on wifi

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#2349]
Am I right that we can assume that any mobile data is not walled?

So then we could change the check of this to only wlan connections:
https://github.com/nextcloud/android/blob/b71c302db83dbce593195f43d7d196b9571ee8b8/src/main/java/com/owncloud/android/utils/ConnectivityUtils.java#L49-L51

**Comment by AndyScherzinger** [comment]
I'd think so but would like to pass on this question to @mario - him being the expert on this.
