### ISSUE TITLE
Display pop-up right from the start in case of incompatible client/server versions

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#2355]
At the moment we don't check the server version with regards to even working at all.
With the change of the user agent we break compatibility with any server version lower than 11.0.8.

Thus when logging in we should show a blocking pop-up that the server is incompatible with the client and needs to be upgraded for the client to work.
This differs from the webUI since the webUI comes with the server and thus always works (except for browser issues) while the native clients depend on the server APIs etc. So they will break at some point like they did now. So it is okay to tell it to the users and not let them any further (since it'll crash or loop, or else anyways).

This way the user knows the real issue and this might then also lower the amount of 1-star ratings in the app store which are simply due to folk operating servers which are end of life.

**Comment by joshtrichards** [comment]
Fixed in #2728
