### ISSUE TITLE
Login with app password not working (2fa TOTP)

### ISSUE THREAD

**Issue by hukoeth** [nextcloud/android#2356]
### Actual behaviour
When trying to login using an app password, the app gets stuck on a blank screen with waiting animation (waited 10 minutes and nothing happens).
This was working before but I don't know why/when it actually stopped working since I haven't used the app for a couple of weeks before I re-installed it last weekend.

### Expected behaviour
App should login
 
### Steps to reproduce
1. Install and activate the Two Factor TOTP Provider app on the server
2. Activate 2fa for your account
3. Generate an app password on the server
4. Open the Talk app and enter your server URL
5. Tap on "Alternate login with app password"
6. Enter your username and the app password created in step 3

### Environment data
Android version: 7.1.1

Device model: BQ Aquaris X Pro

Stock or customized system: Stock

Nextcloud app version: 1.1.0beta4

Nextcloud server version:  Server: 13.0.1, App: 3.1.0

#### Nextcloud log (data/nextcloud.log)
```
No log messages relevant to this (in fact no log messages at all when I try to login using app password)
```

**Comment by mario** [comment]
A server bug really (cc @rullzer), but you shouldn't be logging in with app password. Just log in using your normal username+pass combo, and you'll be asked to use your 2fa token or whatever and it'll work.

**Comment by mario** [comment]
Also the Talk repository is over here: https://github.com/nextcloud/talk-android :)
