### ISSUE TITLE
Use Lombok to remove boilerplate code

### ISSUE THREAD

**Issue by arundhati24** [nextcloud/android#2359]
### Actual behaviour

Currently, there is a lot of boilerplate code present in classes, say FileSystemDataSet.java, under datamodel directory.

### Expected behaviour

Use Lombok to replace the boilerplate code. Use appropriate annotations to generate the getters, setters etc., rather than including all of them in the main class. This would make the code a lot more cleaner and structured.

**Comment by arundhati24** [comment]
What do you suggest @tobiasKaminsky @mario @AndyScherzinger ? :)

**Comment by mario** [comment]
I like Lombok, but please wait for approval from @tobiasKaminsky or @AndyScherzinger too.

There are bunch of places where we could use it.

**Comment by arundhati24** [comment]
sure @mario :)

**Comment by AndyScherzinger** [comment]
Fine with me 👍 

What do you think @tobiasKaminsky?

**Comment by arundhati24** [comment]
:+1: @AndyScherzinger

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky ping ;-)

**Comment by tobiasKaminsky** [comment]
Good idea.
Although this should not affect our app, I think we should only introduce this with sane test cases, especially for equals, compare, ...

So I suggest this roadmap
- write test cases for the desired data models in a separate PR
- in a PR based on this above, add lombok
--> test should still work

I also suggest, to change only one data model at once, e.g. OCFile, OCShare, ...

(in general we should try to have test cases for any new introduced feature/code [which is worth it])
In regard of this I already started with #2312, which are integration tests.
For this Unit tests should be enough.

As always, if you need any help, please do not hesitate to ask here or on irc #nextcloud-mobile

**Comment by AndyScherzinger** [comment]
lombok has been added to the master branch, thus closing
