### ISSUE TITLE
NextCloud 3.0.3 stuck at "Redirecting" login

### ISSUE THREAD

**Issue by josvanroosmalen** [nextcloud/android#2361]
### Actual behaviour
NextCloud 3.03 does not initialize after reinstall. After providing login credentials, you get a "REDIRECTING...."  screen with a looping spinner. This screen never goes away.

it seems like that the developers do not trust this new 'login' method themselves since they show an option to use the 'old login method' in this 'redirecting'  screen, but that also does not work. 

### Expected behaviour
This "Redirecting"  screen should go away.

### Steps to reproduce
1. Uninstall NextCloud Android
2. Install NextCloud Andorid 3.0.3
3. Provide URL/userid/pwd.

### Environment data
Android version: 7.0

Device model:  Galaxy S8

Stock or customized system: Stock

Nextcloud app version: 3.0.3

Nextcloud server version: 12

**Comment by xerographic** [comment]
Same problem. Lots of comments on this issue on the Google app store page.

Server and desktop work just fine. 

I found hundreds of leftover sync clients in the Security settings page for my user (not admin). I laboriously began revoking them all and about halfway through the app connected and synced. 


**Environment data**

Android version: 6.0

Device model: LG G4

Stock or customized system: Stock

Nextcloud app version: 3.0.3

Nextcloud server version: 13.0.1

**Comment by lalalolo49** [comment]
I had this issue, it was about my IP being banned because of force brute. Why ? Don't know.

**Comment by xXSTrikeXx** [comment]
Seems to be like this issue:
https://github.com/nextcloud/android/issues/2032#issuecomment-370811027

**Comment by DriXse** [comment]
Hi,

I have the exact same problem with fresh first time install for server (Nextcloud 13.02) and smartphone.
I've tried lot if things 
- Move to internal  from the apps settings of android 7
    - By default when sd card is install as internal storage, nextcloud app use sdcard for install
- Revok the mobile access from my server + reboot smartphone + clean cache date
- Try with nextcloud from playstore or nextcloud dev from fdroid

I can't use adb things from the sqlite database for delete account things as explain here
https://github.com/nextcloud/android/issues/2032

Thanks a lot for your work.
