### ISSUE TITLE
NextCloud 3.0.3 randomly generated login failures server side

### ISSUE THREAD

**Issue by josvr** [nextcloud/android#2362]
### Actual behaviour
I use NextCloud 3.0.3. Serverside I scan the `nextcloud,log `for login failures and I block access via `fail2ban` after x login failures. The username is okay (in nextcloud) so the password is most likely wrong. 

Now it seems that randomly the Android Application is causing login failures. So if it uploads 5 photo's it suddenly fails on photo 3, so the first 2 go correctly. Also I see in the Android App the message something like "Checking the stored credentials". 

So it seems that if we store the nextcloud credentials ("keep me logged in") is not always retrieving the right password!?

### Environment data
Android version: 7

Device model: OnePlus 5

Stock or customized system: Stock

Nextcloud app version: 3.0.3

Nextcloud server version:12

**Comment by xXSTrikeXx** [comment]
Do you have installed the app bruteforce?

**Comment by Ceaus** [comment]
Same here. App currently is unusable. Client: 3.0.3. The server hasn't changed since ages and is stock.

**Comment by Ceaus** [comment]
Btw, I removed the previous client before installing v3.0.3

**Comment by AndyScherzinger** [comment]
@ceaus are you running at least Nextcloud 11.0.8?

**Comment by Ceaus** [comment]
No. I'm running "Nextcloud 10.0.1 (stable)" on FreeBSD.

FYI: I've stopped the Android client (from the Android Settings/Apps menu) and reopened the client. The result from that action is attached. Particularly interesting (to me) is the brute force report.
[nextcloud.log](https://github.com/nextcloud/android/files/1840515/nextcloud.log)

**Comment by AndyScherzinger** [comment]
@Ceaus the 3.0.x isn't compatible with Nc 10, you need to run at least 11.0.8 in order for the client to work.

**Comment by Ceaus** [comment]
Bummer. I was hoping the login issue was a stand-alone issue. Oh well...

**Comment by AndyScherzinger** [comment]
@Ceaus yeah, sorry for that. You can either upgrade your server on re-install the app downloading the 2.0.1 client from our download server: https://download.nextcloud.com/android/ while I'd advice you to upgrade to server for various reasons like security where downgrading on the client side will also lock you on that version.

**Comment by AndyScherzinger** [comment]
@josvr which exact version of Nc 12 are you running? To be safe that it is not a server issue you should run the latest patch release of 12 which is 12.0.6 or even better upgrade to 13.0.1.

For now I'll be closing the issue until further feedback.

**Comment by josvr** [comment]
Why does the android client not check the server version, and say "You are running version x, this client only works with version y"?  I am not sure there is an API to get the server version number, but if you can obtain that it would be a good idea and this will avoid a lot of reported issues.

**Comment by AndyScherzinger** [comment]
@josvr absolutely true, this is why I created an issue for that some days ago: https://github.com/nextcloud/android/issues/2355
