### ISSUE TITLE
Auto upload does not initiate caused by app power monitor

### ISSUE THREAD

**Issue by levster69** [nextcloud/android#2364]
Nextcloud 3.0.3

Auto upload does not initiate until you perform force rescan

**Comment by mario** [comment]
What version of Android, what phone?

**Comment by xXSTrikeXx** [comment]
@levster69
Please add power consumption for the app, because autoupload is a background service :blush:

**Comment by levster69** [comment]
Galaxy S9+, Android 8.0.0

As far as power consumption goes, I'm not sure how to get that. All I see under the setting for the Nextcloud app is 0 since last fully charged.

**Comment by xXSTrikeXx** [comment]
@levster69 
Look under **_## Put apps to sleep… forever_**
https://www.cnet.com/how-to/tips-and-tricks-to-improve-battery-life-of-the-galaxy-s9-s9-plus/
App power monitor has to be disabled for nextcloud 😉

**Comment by levster69** [comment]
OK. done. I think that it works. Thank you!

**Comment by toger5** [comment]
I have the same issue on an LG G4.

I can't even find the force rescan option.

**Comment by mario** [comment]
@toger5 that option is nearly useless for 99,99% of people. Please disable battery optimizations for the app instead. (To be fair, I'll tell you how to get force rescan - go to settings and enable expert mode. Then go to uploads and open the menu).

**Comment by toger5** [comment]
@mario Thank you! for telling me how to force rescan ;)

Turned of the battery optimization. I will update you if it works.

Would it be possible to detect if the battery optimization is not ignored and give the user the option to ignore it inside the app?

**Comment by mario** [comment]
In part yes. Some phones are tricky I'm afraid :(

**Comment by toger5** [comment]
Okay so it worked now. But only with a picture I have just taken. older pictures I want to back up are still ignored.

**Comment by mario** [comment]
That is normal and expected, we dont support uploading old pics just yet :)

**Comment by toger5** [comment]
okay. 
good to know.

But this is something which will come soon or later?

Checking the source right now and will have some time soon so maybe ill look into it...

**Comment by mario** [comment]
Yes, I'll work on it if nobody implements it since I'm the auto upload guy and responsible for most of the ways it does its magic :D

**Comment by toger5** [comment]
Cool. So you know where to look at immediatly.

Would it be possible, if i find time (after the 20. Im more or less free) to contact you for help?

**Comment by mario** [comment]
Of course. Mario at nextcloud.com :)

**Comment by joshtrichards** [comment]
#4788
