### ISSUE TITLE
No auto upload after update

### ISSUE THREAD

**Issue by levster69** [nextcloud/android#2377]
Just upgraded to 13.0.1 and the auto upload feature does not work for images or video, WiFi or not. Manually pushing image worked. Syncing from a PC works.

Galaxy S9+ running Android 8.0.0

**Comment by tobiasKaminsky** [comment]
Do you also use the latest android version? 
An upgrade to NC13 should not affect auto upload.

**Comment by levster69** [comment]
What's interesting, I noticed that some folders would sync while others did not. Last night I tried the same thing on my wife's phone and all worked as should. I reinstalled the app on my phone with no change. I cleared cache and reinstalled. Same issue. I did that about half a dozen times, rebooting the phone hooping that some small piece of install remained that was preventing the app from uploading photos/videos from the main folder. Changed to a new folder on the server to upload to. Nothing was happening.

Then, not attributing to anything that I did, the files were uploaded on their own. 

Now, again it seems to have stalled. Force rescan does not change anything.

Yes, I am on the latest stable Android APK.

**Comment by levster69** [comment]
I tried to uninstal and reinstall the app, but the original settings remain. I cleaned the cache and memory, yet the settings remain. Is there a way to completely remove the app, including its settings?

**Comment by levster69** [comment]
Only one folder is giving me troubles, the main photo gallery. Is there a way to uninstall the app and clear out the cache. Every time that I have tried to uninstall the app the original settings remain.

**Comment by levster69** [comment]
Well, I somehow got it to work. My mistake was that I was uninstalling and then reinstalling the app. The original settings remained. To make it finally work, I removed the account, cleared out the cache and then re-added the account without reinstalling. Now, everything seems to be working OK. I still would like to know why the original settings for the app do not clear when the app is uninstalled.

**Comment by heximal** [comment]
Autoupload doesn't work for me too. Any photos taken prior to installing the app are ignored. If I take a new photo, it is uploaded.

I suppose it's an issue with rescanning the folder?

Nextcloud 13.0.1, app 3.0.3 on Samsung S7.

**Comment by mario** [comment]
@heximal this is not a bug. It's expected.

**Comment by heximal** [comment]
@mario I wasn't aware this was the intended functionality. So it is not possible to sync anything on my phone with the server, unless it is created after the app was installed?

**Comment by toger5** [comment]
I think by the way the sync featurw is designed users definitly expect the whole folder to be synced.
Maybe when acrivating the instant upload there should be an alert:
"This folder contains x images. Do you want to sync all of them?
-Syync all
-Only sync new files from now on

And than there is a cloud icon or a cloud icon with a small date on the bottom so ppl now which sync method is chosen

**Comment by chris007de** [comment]
Same here on Nexus 5x.
When configuring an "automatic" upload for a folder, I would definitely expect that the whole folder is uploaded, and not only files newer than the app installation date.
Any sync app I used so far just took the whole content of a folder and uploaded it. So at least for me (and I guess I am not alone), this is the expected behaviour.
So please either change this to take all files into account or make it at least configurable to do so.
Until then, I'll switch back to another sync app :)

**Comment by mist0706** [comment]
Not sure if related but all video auto uploads have stopped working for me since the 18th of march (last video uploaded). Uploading videos manually also doesn't work but simply crashes the entire app.

**Comment by tobiasKaminsky** [comment]
@mist0706 if manually video upload also does not work, I assume that this is the reason why auto upload also does not work, but as it is in background it just does no t crash.

Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

**Comment by vwbusguy** [comment]
I'm seeing the same thing on Galaxy S9+.  Auto-uploads have largely stopped working.  If it does work, it only uploads one picture and stops.  Bulk upload works just fine.  I've tried "Force Rescan" as well and it doesn't appear to do anything.  No errors - it's like it's just failing to find anything to upload.  It was working fine until about early April.

**Comment by levster69** [comment]
My auto upload has effectively stopped for all folders. Individual or mass upload still works, if initiated manually. Latest Android app and updated server.

S9+

**Comment by mist0706** [comment]
Looking at my files through the nextcloud manual upload button it lists all
my files as created April 5th. This might have something to do with the
issue.

**Comment by brandonkal** [comment]
### I am also experiencing issues with auto upload. This seems to always be inconsistent but in my case it hasn't uploaded anything for the last 3 months.

**Comment by levster69** [comment]
Has there been any progress on this particular issue? It's been a while since I originally posted this and so far haven't seen any significant feedback or suggestion as to how to remedy it.

**Comment by levster69** [comment]
I've updated to 3.2.0 RC2. Now, the auto upload does not initiate, however, when you do force rescan the files get appropriately uploaded.

**Comment by brandonkal** [comment]
This may be stale, but I believe this bug still exists.
