### ISSUE TITLE
AutoUpload creates unwanted copies of files 

### ISSUE THREAD

**Issue by antumin** [nextcloud/android#2379]
### Actual behaviour
- AutoUpload creates a copy of all files, which are uploaded in the folder /nextcloud/tmp/$account@hostname$/AutoUpload/ when using the default configuration (keep file in folder)
This causes a massive usage of storage over time under some conditions.

### Expected behaviour
- The files should not be copied, but simply kept in its folder.
 
### Steps to reproduce
1. Activate AutoUpload for a folder
2. Invoke upload of file

### Environment data
Android version: 7.1.1

Device model: Moto Z Play

Stock or customized system: Stock

Nextcloud app version: 3.0.3

Nextcloud server version: 12.0.5

**Comment by mario** [comment]
The bug is not in the fact that files are copied (because they have to be), but in the fact that they're not deleted afterwards. Thanks for reporting this!

**Comment by mario** [comment]
I assume you're using SD card?

**Comment by antumin** [comment]
No, I have only internal storage

**Comment by tobiasKaminsky** [comment]
We have only two occurrences where we delete the temp file:
https://github.com/nextcloud/android/blob/3ce42809313cbde72b88ff496132a596fa4ae283/src/main/java/com/owncloud/android/operations/UploadFileOperation.java#L869-L869

https://github.com/nextcloud/android/blob/3ce42809313cbde72b88ff496132a596fa4ae283/src/main/java/com/owncloud/android/operations/UploadFileOperation.java#L952-L952

Now the big question is why and which case is not working...

**Comment by AndyScherzinger** [comment]
Maybe in case of unsuccessful (auto) uploads where we also might have been terminated and then a file stays there? Just an idea, not sure.

**Comment by antumin** [comment]
I deleted the files manually. After I did that, everything works fine, except the files are shown in "On device" but cannot be opened anymore.
Maybe this helps

**Comment by imthefrizzlefry** [comment]
I just had to manually delete 40+ GB of files from my phone due to this issue.  most of the pictures were months or even a year old.  Perhaps it would be good to clear out this folder when the activity loads by running an operation to remove temporary files older than X days?


Android: 8.1.0 (Security Patch March 5th 2018)
Device: Google Pixel 2 XL
App Version: 3.1.0 RC2
Server Version: 13.0.0 RC1

**Comment by GAS85** [comment]
Just for information, have the same issue, but with a different path: `/ExternalSD/Android/media/nextcloud/tmp/user@domain%2Fnextcloud/FOLDER`
Phone is Samsung Galaxy A5 2016 with Android 7.0

Files will never be deleted, even if moved/deleted in server.
