### ISSUE TITLE
Enhance what's new screen

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#2396]
![image](https://user-images.githubusercontent.com/5836855/37818487-94c133f2-2e7a-11e8-822e-c7902bdd758e.png)

[Feedback](https://github.com/nextcloud/android/pull/1657#issuecomment-375121502) by @jancborchardt:
can you also adjust the layout/whitespace according to the screenshot I posted above?
- More spacing above and below the top header
- As mentioned, top header could be better in non-bold to not fight with the feature header
- Less space between feature header and feature detail text

**Comment by josechoy** [comment]
Hi @tobiasKaminsky , can I work on this enhancement?

**Comment by tobiasKaminsky** [comment]
@josechoy yes, sure. Thank you for your help :tada: 

If you have any questions, just ping me.
Once your PR is ready, please ping nextcloud/designers and @jancborchardt to have design feedback.

**Comment by josechoy** [comment]
@tobiasKaminsky Hi, I am sorry. I am currently working on other priority. I will come back later if the issue still available.

**Comment by tobiasKaminsky** [comment]
Ok, thanks for letting us know. I re-added "good first issue" so that others can pick it.

**Comment by artem-p** [comment]
Hello @tobiasKaminsky, can I work on this issue?

**Comment by xXSTrikeXx** [comment]
@artem-p sure :)

**Comment by artem-p** [comment]
![screenshot_1522927270](https://user-images.githubusercontent.com/1714477/38363415-4bdd73ea-38dd-11e8-857b-745836e40fba.png)

This is what I did so far. I didn't find device protection what's new resources in the project, therefore took a screenshot with IPv6. @jancborchardt please, take a look.

**Comment by jancborchardt** [comment]
@artem-p nice, that looks good! :) :+1:

@tobiasKaminsky what do you think?

**Comment by artem-p** [comment]
@jancborchardt @AndyScherzinger thanks!
