### ISSUE TITLE
3.1.0rc1 InvalidArgumentException: Search is only supported on directories

### ISSUE THREAD

**Issue by MeiRos** [nextcloud/android#2400]
### Actual behaviour
There are new errors in the nextcloud.log after update to 3.1.0 rc1

### Expected behaviour
No errors
 
### Steps to reproduce
1. Install rc1
2. Use it
3. look at the log

### Environment data
Android version: 8.0.0

Device model: SM-G950F

Stock or customized system: stock

Nextcloud app version:3.1.0 rc1

Nextcloud server version:Nextcloud 13.0.1

#### Web server error log
```
error.log
nothing
```
```
access.log
12.345.678.90 - Test [23/Mar/2018:20:59:45 +0000] "GET /index.php/204 HTTP/1.1" 204 0 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC1"
12.345.678.90 - Test [23/Mar/2018:21:00:01 +0000] "GET /ocs/v1.php/cloud/user?format=json HTTP/1.1" 200 336 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC1"
12.345.678.90 - Test [23/Mar/2018:21:00:07 +0000] "GET /ocs/v1.php/cloud/user?format=json HTTP/1.1" 200 336 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC1"
12.345.678.90 - Test [23/Mar/2018:21:00:07 +0000] "OPTIONS /remote.php/dav HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC1"
12.345.678.90 - Test [23/Mar/2018:21:00:07 +0000] "SEARCH /remote.php/dav HTTP/1.1" 500 238 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC1"
12.345.678.90 - Test [23/Mar/2018:21:00:07 +0000] "GET /status.php HTTP/1.1" 200 157 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC1"
12.345.678.90 - Test [23/Mar/2018:21:00:07 +0000] "GET /ocs/v1.php/cloud/capabilities?format=json HTTP/1.1" 200 1699 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC1"
12.345.678.90 - Test [23/Mar/2018:21:00:08 +0000] "GET /ocs/v1.php/cloud/user?format=json HTTP/1.1" 200 336 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC1"
12.345.678.90 - Test [23/Mar/2018:21:00:08 +0000] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 774 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.1.0 RC1"
12.345.678.90 - Test [23/Mar/2018:21:00:08 +0000] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 3571 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.1.0 RC1"
12.345.678.90 - Test [23/Mar/2018:21:00:08 +0000] "GET /ocs/v2.php/apps/files_sharing/api/v1/shares?path=%2F&reshares=true&subfiles=true HTTP/1.1" 200 138 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC1"
```

#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"9G1uvxSlDS4gSWpLOIi0","level":4,"time":"2018-03-23T21:00:07+00:00","remoteAddr":"12.345.67.89","user":"test","app":"webdav","method":"SEARCH","url":"\/remote.php\/dav","message":"Exception: {\"Exception\":\"InvalidArgumentException\",\"Message\":\"Search is only supported on directories\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/nginx\\\/domains\\\/domain.com\\\/public\\\/3rdparty\\\/icewind\\\/searchdav\\\/src\\\/DAV\\\/SearchHandler.php(75): OCA\\\\DAV\\\\Files\\\\FileSearchBackend->search(Object(SearchDAV\\\\XML\\\\BasicSearch))\\n#1 \\\/home\\\/nginx\\\/domains\\\/domain.com\\\/public\\\/3rdparty\\\/icewind\\\/searchdav\\\/src\\\/DAV\\\/SearchPlugin.php(123): SearchDAV\\\\DAV\\\\SearchHandler->handleSearchRequest(Array, Object(Sabre\\\\HTTP\\\\Response))\\n#2 [internal function]: SearchDAV\\\\DAV\\\\SearchPlugin->searchHandler(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/home\\\/nginx\\\/domains\\\/domain.com\\\/public\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/home\\\/nginx\\\/domains\\\/domain.com\\\/public\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:SEARCH', Array)\\n#5 \\\/home\\\/nginx\\\/domains\\\/domain.com\\\/public\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/home\\\/nginx\\\/domains\\\/domain.com\\\/public\\\/apps\\\/dav\\\/lib\\\/Server.php(283): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/home\\\/nginx\\\/domains\\\/domain.com\\\/public\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(35): OCA\\\\DAV\\\\Server->exec()\\n#8 \\\/home\\\/nginx\\\/domains\\\/domain.com\\\/public\\\/remote.php(164): require_once('\\\/home\\\/nginx\\\/dom...')\\n#9 {main}\",\"File\":\"\\\/home\\\/nginx\\\/domains\\\/domain.com\\\/public\\\/apps\\\/dav\\\/lib\\\/Files\\\/FileSearchBackend.php\",\"Line\":152}","userAgent":"Mozilla\/5.0 (Android) ownCloud-android\/3.1.0 RC1","version":"13.0.1.1"}
{"reqId":"QP7TtNPmEA4RDwF8VYrX","level":4,"time":"2018-03-23T21:00:07+00:00","remoteAddr":"12.345.67.89","user":"test","app":"webdav","method":"SEARCH","url":"\/remote.php\/dav","message":"Exception: {\"Exception\":\"InvalidArgumentException\",\"Message\":\"Search is only supported on directories\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/nginx\\\/domains\\\/domain.com\\\/public\\\/3rdparty\\\/icewind\\\/searchdav\\\/src\\\/DAV\\\/SearchHandler.php(75): OCA\\\\DAV\\\\Files\\\\FileSearchBackend->search(Object(SearchDAV\\\\XML\\\\BasicSearch))\\n#1 \\\/home\\\/nginx\\\/domains\\\/domain.com\\\/public\\\/3rdparty\\\/icewind\\\/searchdav\\\/src\\\/DAV\\\/SearchPlugin.php(123): SearchDAV\\\\DAV\\\\SearchHandler->handleSearchRequest(Array, Object(Sabre\\\\HTTP\\\\Response))\\n#2 [internal function]: SearchDAV\\\\DAV\\\\SearchPlugin->searchHandler(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/home\\\/nginx\\\/domains\\\/domain.com\\\/public\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/home\\\/nginx\\\/domains\\\/domain.com\\\/public\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:SEARCH', Array)\\n#5 \\\/home\\\/nginx\\\/domains\\\/domain.com\\\/public\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/home\\\/nginx\\\/domains\\\/domain.com\\\/public\\\/apps\\\/dav\\\/lib\\\/Server.php(283): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/home\\\/nginx\\\/domains\\\/domain.com\\\/public\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(35): OCA\\\\DAV\\\\Server->exec()\\n#8 \\\/home\\\/nginx\\\/domains\\\/domain.com\\\/public\\\/remote.php(164): require_once('\\\/home\\\/nginx\\\/dom...')\\n#9 {main}\",\"File\":\"\\\/home\\\/nginx\\\/domains\\\/domain.com\\\/public\\\/apps\\\/dav\\\/lib\\\/Files\\\/FileSearchBackend.php\",\"Line\":152}","userAgent":"Mozilla\/5.0 (Android) ownCloud-android\/3.1.0 RC1","version":"13.0.1.1"}
```

```
```
InvalidArgumentException: Search is only supported on directories

    /home/nginx/domains/domain.com/public/3rdparty/icewind/searchdav/src/DAV/SearchHandler.php - line 75: OCA\DAV\Files\FileSearchBackend->search(Object(SearchDAV\XML\BasicSearch))
    /home/nginx/domains/domain.com/public/3rdparty/icewind/searchdav/src/DAV/SearchPlugin.php - line 123: SearchDAV\DAV\SearchHandler->handleSearchRequest(Array, Object(Sabre\HTTP\Response))
    [internal function] SearchDAV\DAV\SearchPlugin->searchHandler(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /home/nginx/domains/domain.com/public/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
    /home/nginx/domains/domain.com/public/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit('method SEARCH', Array)
    /home/nginx/domains/domain.com/public/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /home/nginx/domains/domain.com/public/apps/dav/lib/Server.php - line 283: Sabre\DAV\Server->exec()
    /home/nginx/domains/domain.com/public/apps/dav/appinfo/v2/remote.php - line 35: OCA\DAV\Server->exec()
    /home/nginx/domains/domain.com/public/remote.php - line 164: require_once('/home/nginx/dom...')
    {main}
```

**Comment by MeiRos** [comment]
Trying to access Favourites makes this happen. Favourites never opens.

**Comment by MeiRos** [comment]
Looks like e2ee have something to do with this. My encrypted folder is asking password (didn't write it) and while one folder is encrypted and not opened with pw, accessing to favourites gives warning, which is above. Setting folder as unencrypted, accessing to favourites works and no warnings.

(And when I set folder as unencrypted, files stayed encrypted. Folder can't be encrypted again so don't know how to open files...)

This problem is part of my whole problem, which I've been trying to solve here. https://help.nextcloud.com/t/nextcloud-app-on-android-keeps-loading

After setting encrypted folder as unencrypted, this problem looks like solved. But I think my case is worth of deeper looking... There's something which may cause troubles. Puzzle pieces aren't in place yet, so I can't report better. This is quite a mess.

Would be nice if developers share their thoughts about this.

**Comment by MeiRos** [comment]
Oh F*CK!
I was wrong. I had it somehow working with admin account. Back in Test account and favourites stays loading and errors are there. Deleted all other app permissions. Only one app allowed.

http://i68.tinypic.com/eqbeki.jpg

**Comment by MeiRos** [comment]
With rc2 errors are there. Favourites and Photos keeps loading.

**Comment by tobiasKaminsky** [comment]
@nextcloud/server-triage, is this server related?

**Comment by MeiRos** [comment]
Hmmm... It’s quiet in there @nextcloud/server-triage

@tobiasKaminsky 
I have tested dev version 20180330. Samsung S8 keeps loading and gives 2 errors almost every time which are described in the first message. But with Huawei Y5 LineageOS 14.1 no errors and everything works. It doesn’t matter which I try first or totally different time. In the other thread, there’s also Samsung phone. Can this be phone related? (Same Nextcloud account in both phones)

**Comment by MeiRos** [comment]
I uninstalled both rc2 and dev app and installed dev again. This time I used alternative login using app token. No errors and no loading... After few tests it looks like working... I’ll be back later after longer tests.

Do rc2 and dev use same folder for cache and other files? Was it total uninstall or app token which make it (atm) working? What do you think Tobias?

**Comment by tobiasKaminsky** [comment]
dev and rc2/stable are completely independent.
If the app token would have been the cause, then all other things, e.g. folder listing, up-/download would also not have worked.

I am also a bit out of clue...

**Comment by MeiRos** [comment]
You are absolutely right @tobiasKaminsky
It's not token it's the user name case sensitive problem! Log in as Admin and it keeps loading and gives fatal errors. Log in as admin and it works! The other keyboard starts user name automatically with big A and because I'm lazy, I didn't change it. That's why the other phone worked.
I tested this theory many times and it always did the same.

So expected behaviour:
Forbid log in if the user name is not absolutely correct
or
Make webdav? work even if the user logs in with "wrong" user name.

BTW
Thanks for your comments! Without them I would have give up. :)

**Comment by MeiRos** [comment]
Tested with dev 20180410.

Login as Admin with big A. Favourites and Photos keeps loading and produces fatal errors. Other options are working. 
Login as admin with small a. Everything is working. 

This is new one. 
Login as admin  with small a and empty space after. Favourites and Photos keeps loading. Other options are working.

**Comment by MeiRos** [comment]
Tested with dev 20180412
Still the same. (sometimes it may need extra refresh, swipe down, when returning back to fully working user name.)
@tobiasKaminsky have you tried these logins?

**Comment by MeiRos** [comment]
@tobiasKaminsky
Do you still need info/discussion about this?

**Comment by tobiasKaminsky** [comment]
@MeiRos thank you for your detailled steps. With these it was much easier to track this bug down.
