### ISSUE TITLE
Android 3.0.3 Auto upload fail

### ISSUE THREAD

**Issue by ghost** [nextcloud/android#2402]
### Actual behaviour
- Auto upload fail after  reinstall

### Expected behaviour
- Auto upload succeeds after first install
 
### Steps to reproduce
-    Install NextCloud Android App 3.0.3 on LineageOS 14.1-20180207 / Android 7.1.2
-    Select Auto Upload from the menu
-    Tap the cloud so it is blue
-    Take a photo
-    See a notification saying: “Upload failed: Cloud not complete operation. Server unavailable”
-    Reboot the phone
-   Run nextcloud
-    See the newest photo is successfully uploaded

### Environment data
Android version: Android 7.1.2

Device model: Samsung SIII

Stock or customized system: LineageOS 14.1-20180207

Nextcloud app version: 3.0.3 

Nextcloud server version: 13

### Comment

First filed [in the forum](https://help.nextcloud.com/t/android-3-0-3-auto-upload-fail-after-first-install/29118)

**Comment by xXSTrikeXx** [comment]
Is it a new device or just a reinstall?

**Comment by dachary** [comment]
It is a re-install, not a device shipped natively with LineageOS 14.1-20180207.

**Comment by xXSTrikeXx** [comment]
Reinstalling will not purge the app data. 
@tobiasKaminsky I and friends phone get always these error message. Any ideas how to debug it? 😉

**Comment by dachary** [comment]
@xXSTrikeXx I see you changed the title of bug report. However the steps described to reproduce the problem will only work to demonstrate **Auto upload** fails to work the first time. After rebooting the device **Auto upload** works fine on the device. If you have different steps or a different device where **Auto upload** never works, would you mind creating a separate issue? The two issues may be related but... maybe not?

**Comment by tobiasKaminsky** [comment]
@xXSTrikeXx  a separate issue is better, so we get not confused. If it is in the end the same, we still can close one as duplicate.

@dachary does this happen after every device restart?

Can you provide us additional infos via logcat when this is happening? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

**Comment by dachary** [comment]
> does this happen after every device restart?

No, it only happens after re-installing nextCloud, as described in the message. When the device is restarted all is well and working.

> additional infos via logcat when this is happening?

I will do that, thanks for the tip!

**Comment by dachary** [comment]
@tobiasKaminsky here is the relevant part of the logcat command while following the instructions in the original message before rebooting the device (fail.txt) and after rebooting the device and taking another picture (success.txt). I can also send you via encrypted email the (larger) entire logcat output in case it is useful.

[debug.zip](https://github.com/nextcloud/android/files/1858963/debug.zip)

**Comment by mhow2** [comment]
I can confirm the save behavior as stated by some users above: it starts to work after a reboot. (on my I9300/S3 , Android 7.1.2 - lineageOS)

**Comment by sergrulez** [comment]
For me the autoupload doesn't work even after a reboot.
Xiaomi Mi5
Android 7.1.2 LineageOS 14.1-20180102-NIGHTLY-gemini
