### ISSUE TITLE
No show password button, for long passwords the last typed char only shows up for ~2 seconds - makes typing long passwords correctly very challenging

### ISSUE THREAD

**Issue by JonasT** [nextcloud/android#2408]
### Actual behaviour
No show password button, for long passwords the last typed char only shows up for ~2 seconds - makes typing long passwords correctly very challenging.

### Expected behaviour
There is a show password button on the login form.
 
### Steps to reproduce
1.  Enter a nextcloud URL
2. Use the login form, check for show password button

### Environment data
Android version: 7.1.2

Device model: GT-I9195 / serrranoltexx / Samsung Galaxy S4 Mini LTE (International version)

Stock or customized system: LineageOS 14.1

Nextcloud app version: 3.0.3 / f-droid

Nextcloud server version: don't know

#### Web server error log
```
don't have access to this server right now
```

#### Nextcloud log (data/nextcloud.log)
```
don't have access to this server right now
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
We use the login form which comes from server, so I ask @nextcloud/server-triage team for further infos/ideas.

**Comment by MorrisJobke** [comment]
> No show password button, for long passwords the last typed char only shows up for ~2 seconds - makes typing long passwords correctly very challenging.

We don't have this for the login fields - we only have this on change password fields. So this is an enhancement and should be filed in the server.
