### ISSUE TITLE
In Android 4.x, I use BluetoothSocket.close(), but the count of fd increase to 1024.

### ISSUE THREAD

**Issue by lzj1991** [nextcloud/android#2409]
### Actual behaviour
-In Android 4.x, I hava used BluetoothSocket.close(), but the count of fd still increase to 1024.
However In Android 5.0 or higher, the count of fd not increase, it is perfectly normal.
### Expected behaviour
-the count of fd should not be increased when we hava used BluetoothSocket.close()
 
### Steps to reproduce
1. in a looper
2. mBluetoothSocket = device.createRfcommSocketToServiceRecord(UUID_ANDROID_DEVICE);
3. mBluetoothSocket.close()

### Environment data
Android version:

Device model: 
Android 4.4  4.2
Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Where do we use this bluetooth code you are referring to?

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky we don't thus I'll close this issue since it is not related to Nextcloud. @lzj1991 please reopen _if_ related to the app and not to Android's API behavior in general.
