### ISSUE TITLE
Files are not downloaded; permanent notification

### ISSUE THREAD

**Issue by ygoe** [nextcloud/android#2411]
### Actual behaviour
I have two issues and I'm not sure if they're related.

1. I have marked my KeePass database file for offline use in the app. When I open it through NextCloud, it can be opened by KeePass DX. But at all other times, that file doesn't exist. It seems to be deleted right after opening it.

2. There's a permanent notification saying "Dateimonitor", "Prüft auf Dateiänderungen". No idea what that is. It only appears on Android 8.0 but not on 7.1. And it can't be discarded, it's always there and shows an icon in the top bar.

### Expected behaviour
1. Files marked for offline use should be downloaded and remain available on the device.

2. No notification when not actively doing anything.
 
### Steps to reproduce
See above

### Environment data
Android version: 8.0, 7.1

Device model: Samsung Galaxy S8, Sony Xperia Z5 Compact

Stock or customized system: Stock (well, from Samsung)

Nextcloud app version: 3.0.3

Nextcloud server version: 3.0.*

**Comment by ygoe** [comment]
Sorry, I have investigated this further and was misled by a bug in KeePass DX. The file is indeed downloaded but that app doesn't show it.

So what about that notification? What is it good for? Can I just disable it through Android system settings? I don't want to see it all day.

**Comment by mario** [comment]
I thought I fixed this for 3.0.3, but if not, it's definitely fixed in 3.1 :)  (just can't remember when we merged the PR, maybe @tobiasKaminsky knows?)

**Comment by tobiasKaminsky** [comment]
This is fixed/merged via #2253 and will be in 3.1.
