### ISSUE TITLE
@ sign in the folder name of the data cause VLC to stop scanning.

### ISSUE THREAD

**Issue by awolff64** [nextcloud/android#2419]
### Actual behaviour
My synced music is not found by VLC.

### Expected behaviour
VLC should find the synced Music.
When I remove the @ for the directory name user@url it works.
Couldn't you make a url/user directory instead?
 
### Steps to reproduce
1. Sync Music to an android.
2. Run VLC and it wont find it.
3. Remove the @ from the user@url directory name.
$. VLC will find it.

### Environment data
Android version:
5 and 6
Device model: 
ACER

Stock or customized system:
Stock

Nextcloud app version:
current.

Nextcloud server version:
11.

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

**Comment by tobiasKaminsky** [comment]
For me this is a bug in VLC as this directory pattern is allowed by android, so all apps should handle it.
Changing our data structure might be possible, but would then need a data migration step, which I would like to avoid.
Additionally, if you download music in a folder called "music@home", then you would also have the problem.

Please cross-link the bug in VLC to this. I am glad to help/debug it, but it should be addressed on VLC side.
