### ISSUE TITLE
Don't show upload failure notification for deleted files

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/android#242]
### Actual behaviour
- setup instant upload of photos and limit it to wifi
- disable wifi
- take a photo
- delete this photo
- enable wifi
- there is a notification about a failed upload (it says: can't find local file)

### Expected behaviour
- there should be no notification about a failed upload
 

@jancborchardt Does that make sense? I'm always annoyed by this behavior because I think that something is broken even if this isn't the case.

Beside that for real failures they should maybe not say: "failed upload due to connection issues" but something like "3 queued upload - they are retried once the network connection is better" because sometimes you have flaky internet connection but you don't care about the upload, but it should actually do it at some time and not not at all after the first failed try.

**Comment by MorrisJobke** [comment]
@AndyScherzinger "There is no issue for that" 😉  (you even +1ed this)

**Comment by AndyScherzinger** [comment]
tested and merged thus to be released with 1.3.1, so closing it.
