### ISSUE TITLE
Image preview -> show details

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#2425]
### Actual behaviour
- file list is shown 

### Expected behaviour
- image detail should be shown
 
### Steps to reproduce
1. preview an image
2. click on overflow menu -> details

tested with latest master.

**Comment by AndyScherzinger** [comment]
Just tested this with latest master and it works fine for me? :confused:

**Comment by tobiasKaminsky** [comment]
Strange, I am doing this
- click on a non-downloaded image
- see resized preview image
- click on detail
- see parent folder listing with image name
![2018-04-06-145218](https://user-images.githubusercontent.com/5836855/38422193-1e29aca2-39aa-11e8-9daf-136963aa2433.png)
- minimize app
- restore app
- see photo detail view

Another strange thing is:
- click on a non-downloaded image
- see resized preview image
- click on detail
- see parent folder listing with image name
- click back arrow
--> opens up preview
