### ISSUE TITLE
Increase of PROPFIND-requests in background mode

### ISSUE THREAD

**Issue by gasttor** [nextcloud/android#2431]
### Actual behaviour
- Since updating to version 3.1.0 RC1 I can see an increase of PROPFIND-requests within my nginx-logfiles. After investigating I found out that the app start doing those requests as soon as the app goes into the background-mode. It also does those requests over mobile data. Is this a desired behaviour or should those requests only be done via WIFI? 

### Expected behaviour
- I would expect that those requests are only done via WIFI
 
### Steps to reproduce
1. Start nextcloud-app (mobile data, no WIFI)
2. Send nextcloud-app into background
3. Inspect logfiles of the nextcloud-webserver

### Environment data
Android version: 7.0

Device model: Huawai P9 light

Stock or customized system: customized

Nextcloud app version: 3.1.0 RC2

Nextcloud server version: 13.0.1

#### Web server error log
no error occured

#### Nextcloud log (data/nextcloud.log)
I think no log is necessary

**Comment by AndyScherzinger** [comment]
@mario could this be related to the Keep available offline feature?

**Comment by mario** [comment]
No, offline syncing feature (automatic one) only works on unmetered wifi.

**Comment by gasttor** [comment]
@tobiasKaminsky I checked my yesterday's webserver-logfiles.

I opened the nextcloud-app at 12:33pm. Eight minutes later, when the app was in the backgroung and my handy was not in use, the app started with the PROPFIND-requests. and it went through all available directories in my account.

If you need more information please contact me again.

**Comment by architek** [comment]
Hello,

After installing the application, I noticed my battery drains faster than usual and network is often active.

Nginx logs confirms that the application cyclically PROPFINDs all my files (several thousands on local external storage)

Adb logcat shows chatty for OwnCloudClient, meaning the application is DOSing the log 
```
09-24 15:03:51.630 23555 27864 I chatty  : uid=10163(com.nextcloud.client) /system/bin/dex2oat expire 449 lines
```

To whitelist the application I had to 
```
adb logcat -P ''
```

Every dozen of minutes, the logcat shows thousands of lines:

```
[...]
09-24 15:43:07.747 29253 30953 I RefreshFolderOperation: Checked user@cloud.example.com/Partage/Movies/Concerts/BLABLA/ : changed
09-24 15:43:07.751 29253 30953 D OwnCloudClient #2: REQUEST PROPFIND /remote.php/webdav/Partage/Movies/Concerts/BLABLA/
09-24 15:43:07.795 29253 30953 I ReadRemoteFolderOperation: Synchronized /Partage/Movies/Concerts/BLABLA/: Operation finished with HTTP status code 207 (success)
09-24 15:43:07.795 29253 30953 D RefreshFolderOperation: Synchronizing user@cloud.example.com/Partage/Movies/Concerts/BLABLA/
09-24 15:43:07.828 29253 30953 D RefreshFolderOperation: Remote folder /Partage/Movies/Concerts/BLABLA/ changed - starting update of local data 
09-24 15:43:07.870 29253 30953 D FileDataStorageManager: Saving folder /Partage/Movies/Concerts/BLABLA/ with 3 children and 0 files to remove
09-24 15:43:07.881 29253 30953 D FileDataStorageManager: Sending 4 operations to FileContentProvider
09-24 15:43:07.881 29253 30953 D FileContentProvider: applying batch in provider com.owncloud.android.providers.FileContentProvider@ff51f86 (temporary: false)
09-24 15:43:07.897 29253 30953 D FileContentProvider: applied batch in provider com.owncloud.android.providers.FileContentProvider@ff51f86
09-24 15:43:07.949 29253 30953 D FileSyncAdapter: Send broadcast com.owncloud.android.syncadapter.FileSyncAdapter.EVENT_FULL_SYNC_FOLDER_CONTENTS_SYNCED
09-24 15:43:07.950 29253 30953 D RefreshFolderOperation: Checking changes in user@cloud.example.com/Partage/Movies/Docu/
09-24 15:43:07.952 29253 30953 D OwnCloudClient #2: REQUEST PROPFIND /remote.php/webdav/Partage/Movies/Docu/
09-24 15:43:07.993 29253 30953 I RefreshFolderOperation: Checked user@cloud.example.com/Partage/Movies/Docu/ : changed
09-24 15:43:07.999 29253 30953 D OwnCloudClient #2: REQUEST PROPFIND /remote.php/webdav/Partage/Movies/Docu/
09-24 15:43:08.059 29253 30953 I ReadRemoteFolderOperation: Synchronized /Partage/Movies/Docu/: Operation finished with HTTP status code 207 (success)
09-24 15:43:08.059 29253 30953 D RefreshFolderOperation: Synchronizing user@cloud.example.com/Partage/Movies/Docu/
09-24 15:43:08.096 29253 30953 D RefreshFolderOperation: Remote folder /Partage/Movies/Docu/ changed - starting update of local data 
09-24 15:43:08.133 29253 30953 D FileDataStorageManager: Saving folder /Partage/Movies/Docu/ with 6 children and 0 files to remove
09-24 15:43:08.157 29253 30953 D FileDataStorageManager: Sending 7 operations to FileContentProvider
09-24 15:43:08.157 29253 30953 D FileContentProvider: applying batch in provider com.owncloud.android.providers.FileContentProvider@ff51f86 (temporary: false)
09-24 15:43:08.179 29253 30953 D FileContentProvider: applied batch in provider com.owncloud.android.providers.FileContentProvider@ff51f86
09-24 15:43:08.246 29253 30953 D FileSyncAdapter: Send broadcast com.owncloud.android.syncadapter.FileSyncAdapter.EVENT_FULL_SYNC_FOLDER_CONTENTS_SYNCED
[...]
```

**Configuration:**
NC server and android apps are the latest.
Phone is OnePlus 5T, Official Beta Android Oreo, not rooted.

The application is currently unusable as it will drain my battery in a few hours :-(

Thank you

**Comment by architek** [comment]
My problem has vanished the day after. 
Not sure what did it though...

**Comment by tobiasKaminsky** [comment]
Thanks for the feedback, so closing for now.
Please re-open once the problem re-occurs.
