### ISSUE TITLE
App login leads to HTML viewer and error

### ISSUE THREAD

**Issue by brgbrg** [nextcloud/android#2437]
### Actual behaviour
- I open the freshly (re-)installed Nextcloud 3.0.3 
- App displays an entry field for the server address (no user / password entry field as in earlier versions)
- I enter the address of my Nextcloud 13 server (https://<server>:<port>/nextcloud/  
- I get a display of the Android HTML viewer (translated from German):
  Website not available:
  The Website under https://<server>:<port>/nextcloud/index.php/login/flow may be temporarily deactivated or permanently moved to a new address

### Expected behaviour
- I had expected to get asked for the user and password for that server 
 
### Steps to reproduce
1. open Nextcloud 3.0.3 on device 
2. Try to enter address

### Environment data
Android version:  Android 4.2.2

Device model: AW-420 RX Smartwatch (Small display 240*240 pixel)

Stock or customized system: Stock

Nextcloud app version: 3.0.3

Nextcloud server version: 13

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
Not found / No access to this directory

**Comment by brgbrg** [comment]
Forgot to mention: At the same time the Smartwatch has access to the same Nextcloud server path via firefox.

**Comment by AndyScherzinger** [comment]
cc @tobiasKaminsky for login issue
@brgbrg this sounds like it might be a server config issue to me but don't know for sure. I'd have to know the server url to give it a try :/

**Comment by brgbrg** [comment]
I now made the test server available under https://breuning.selfhost.eu:4949/mycloudtest/

My server runs OpenSuse Leap 42.3, thus has an apache config by a vhosts-file, not a sites-enabled.
Thus I cant fully follow the config under https://docs.nextcloud.com/server/13/admin_manual/installation/source_installation.html#installation-wizard

**Comment by AndyScherzinger** [comment]
I just tried the url you posted and get the proper web view with the login form. Running 3.1.0RC2 on an Android 8 device.

**Comment by AndyScherzinger** [comment]
@brgbrg by web view I meant the app, where I actually see the web Form where you see the error.
Might be related to Android 4.2.2.
@tobiasKaminsky @mario do you have a 4.2.2 at hand?

**Comment by brgbrg** [comment]
Just an attempt:
If I enter the address
  https://breuning.selfhost.eu:4949/mycloudtest/index.php/login/flow 
as provided by the app above into my browser (chromium), I also get an error:
![image](https://user-images.githubusercontent.com/38156896/38580907-7e09f9d8-3d0b-11e8-9819-86a602d2b2ad.png)

If a add a "/" to the address:
  https://breuning.selfhost.eu:4949/mycloudtest/index.php/login/flow/
I get redirected to the login page.

Hence: Should the app the address with a training "/" ?
(Or does it do so and my 4.2.2 android does something wrong?)

**Comment by AndyScherzinger** [comment]
Not an expert on the login flow so we'll have to wait for feedback. @tobiasKaminsky can you please have a look at this?

**Comment by Marcool04** [comment]
Hi @brgbrg.
Just thought I'd mention: I had the same issue on a similar generation Android phone, and after a second attempt, I noticed that the Nextcloud app shows a grey bar at the bottom of the screen offering to "Revert to old login method" (or something along those lines, I don't have it in front of me now…). When I tapped this and entered URL and credentials, login succeeded.
So if you haven't already, maybe you should try again and see if this shows up on your phone…
Best regards,
Mark.

**Comment by tobiasKaminsky** [comment]
@nextcloud/server-triage do you have any ideas/questions to resolve this?

**Comment by Marcool04** [comment]
Perhaps the app could fall back on the "old login method" as soon as the "new" one fails… that would make it seamless for users of older Android versions… Not sure how easy that would be to implement.

**Comment by tobiasKaminsky** [comment]
The problem should not be android, as our app is just showing a webpage. 
I assume this is some kind of server configuration problem.

**Comment by Marcool04** [comment]
Ah… ok. My Nextcloud server instance is up to date (let me know if you want to go elsewhere to chat about this… IRC?)

**Comment by tobiasKaminsky** [comment]
Can you create us a test account and send the credentials to tobias at nextcloud dot com with a reference to this issue?

**Comment by Marcool04** [comment]
Ok. Server is at nextcloud dot archraspberrypi dot tk
Username as you indicated.
Password is "issue" and the number of this issue. No spaces nor separator.

**Comment by tobiasKaminsky** [comment]
Thank you, @Marcool04

**Comment by brgbrg** [comment]
As I raised the original issue: I volunteer to test with my tiny Android device. (Would need to get the login name)

**Comment by tobiasKaminsky** [comment]
@Marcool04 I can verify this on your sever with Android 4.1, but on the same 4.1 it is working fine with my server (also NC13).

Can you give us some more infos regarding your server?

**Comment by Marcool04** [comment]
@brgbrg : I'll create an account for you if you'd like, can you give me an email address to send credentials to please?
@tobiasKaminsky  : Here is some more info about the server. It is running on Arch linux ARM on a Raspberry Pi 3B1 (armv7 architecture). Nextcloud instances is interfacing with MariaDB database, reverse proxied over an Apache HTTPD webserver.

````
$ uname -a
Linux [HOST] 4.14.44-1-ARCH #1 SMP Fri Jun 1 13:13:07 UTC 2018 armv7l GNU/Linux
---------------
$ cat /etc/share/webapps/nextcloud/config/config.php
<?php
$CONFIG = array (
  'instanceid' => 'oc78yfpyrrcy',
  'passwordsalt' => '[REDACTED]',
  'secret' => '[REDACTED]',
  'trusted_domains' => 
  array (
    0 => 'nextcloud.[HOST]',
  ),
  'datadirectory' => '/home/nextcloud/data',
  'overwrite.cli.url' => 'https://nextcloud.[HOST]',
  'dbtype' => 'mysql',
  'version' => '13.0.2.1',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost:/run/mysqld/mysqld.sock',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'nextcloud',
  'dbpassword' => '[REDACTED]',
  'installed' => true,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'maintenance' => false,
  'mail_smtpmode' => 'php',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_from_address' => 'nextcloud',
  'mail_domain' => 'mail.[HOST]',
  'mail_smtphost' => 'localhost',
  'log_type' => 'syslog',
  'logfile' => '',
  'loglevel' => '3',
  'theme' => '',
  'integrity.check.disabled' => true,
);
---------------
$ cat /etc/httpd/config/extra/http-ssl.conf | grep -v "^\s*#"
SSLRandomSeed startup builtin
SSLRandomSeed startup file:/dev/urandom 512
SSLRandomSeed connect builtin
SSLRandomSeed connect file:/dev/urandom 512

Listen 0.0.0.0:443

AddType application/x-x509-ca-cert .crt
AddType application/x-pkcs7-crl    .crl
SSLSessionCache        shmcb:/var/cache/mod_ssl/scache(512000)
SSLSessionCacheTimeout  300

SSLPassPhraseDialog  builtin

SSLSessionCache        "shmcb:/run/httpd/ssl_scache(512000)"
SSLSessionCacheTimeout  300

Header always set Strict-Transport-Security "max-age=63072000; includeSubDomains"

SSLProtocol             all -SSLv3 -TLSv1 -TLSv1.1
SSLCipherSuite  ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA
SSLHonorCipherOrder     on
SSLCompression          off
SSLSessionTickets       off

SSLUseStapling          on
SSLStaplingResponderTimeout 5
SSLStaplingReturnResponderErrors off
SSLStaplingCache        shmcb:/var/run/ocsp(128000)
-------
$ cat /etc/httpd/conf/extra/vhosts/[HOST].conf | grep -v "^\s*#"
<VirtualHost *:80>
   ServerName nextcloud.[HOST]
   Redirect permanent / https://nextcloud.[HOST]/
</VirtualHost>

<VirtualHost *:443>
    DocumentRoot /usr/share/webapps/nextcloud
    ServerName nextcloud.[HOST]
    
    SSLEngine on
    SSLCertificateFile      "/etc/letsencrypt/live/nextcloud.[HOST]/fullchain.pem"
    SSLCertificateKeyFile   "/etc/letsencrypt/live/nextcloud.[HOST]/privkey.pem"

    Redirect 301 /.well-known/carddav /remote.php/dav
    Redirect 301 /.well-known/caldav /remote.php/dav

    RewriteEngine on
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization},L]

    <Directory /usr/share/webapps/nextcloud/>
        Options FollowSymlinks
        AllowOverride all
        Require all granted
    </Directory>

    SecRuleRemoveById 958291             # Range Header Checks
    SecRuleRemoveById 981203             # Correlated Attack Attempt    
    SecRuleRemoveById 950109             # Check URL encodings
    SecRuleRemoveById 960024             # Repeatative Non-Word Chars (heuristic)
    SecRuleRemoveById 981173              # SQL Injection Character Anomaly Usage
    SecRuleRemoveById 981204             # Correlated Attack Attempt
    SecRuleRemoveById 981243             # PHPIDS - Converted SQLI Filters
    SecRuleRemoveById 981245             # PHPIDS - Converted SQLI Filters
    SecRuleRemoveById 981246             # PHPIDS - Converted SQLI Filters
    SecRuleRemoveById 981318              # String Termination/Statement Ending Injection Testing
    SecRuleRemoveById 973332             # XSS Filters from IE
    SecRuleRemoveById 973338             # XSS Filters - Category 3
    SecRuleRemoveById 981143              # CSRF Protections ( TODO edit LocationMatch filter )
    SecRuleRemoveById 970903             # Microsoft Office document properties leakage
    SecRuleRemoveById 981401             # Content-Type Response Header is Missing and X-Content-Type-Options is either missing or not set to 'nosniff'
    SecRuleRemoveById 200002             # Failed to parse request body
    SecRequestBodyNoFilesLimit 5242880  # UPLOADS ( 5 MB max excluding file size )
    SecRuleRemoveById 960017             # Host header is a numeric IP address
</VirtualHost>
````

Let me know if you need anything else. Nothing in the logs from your interaction with the server yesterday looks out of the ordinary (nor did it when I signed in from my Android phone).

**Comment by tobiasKaminsky** [comment]
@nextcloud/server-triage can you help us here please?
For some reasons we get an html error when accessing new weblogin flow…

**Comment by OverByThere** [comment]
Sorry to potentially revive an old ticket, but I'm seeing the same issue:
<img width="952" alt="screen shot 2018-08-30 at 09 44 24" src="https://user-images.githubusercontent.com/6248551/44840615-51c86100-ac39-11e8-98a7-eed70774a5a6.png">
This is after I've accepted the cert as its not valid

**Comment by AndyScherzinger** [comment]
@OverByThere according to your screenshot you seem to have an issue withe the desktop client (or the server setup in general) https://github.com/nextcloud/desktop/issues then with the Android client, right? Then it would need to be reported to the desktop client tracker.

**Comment by OverByThere** [comment]
@AndyScherzinger Apologies, I realised this after I had posted. I've now posted in the correct place, sorry!

**Comment by AndyScherzinger** [comment]
Thanks @OverByThere and no worries, it's all good! :+1:
