### ISSUE TITLE
Error uploading: NullPointerException: String.isEmpty() on a null object reference

### ISSUE THREAD

**Issue by cweiske** [nextcloud/android#2439]
### Actual behaviour
In "Uploads", I click on one of the failed (automatic) uploads (image or video).

The android notification bar shows a notification "Hochladen fehlgeschlagen: Die Operation kann nicht abgeschlossen werden". English ~ "Upload error: The operation could not be finished".

`adb logcat` shows:

```
E/FileUploader( 4218): Error uploading
E/FileUploader( 4218): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
E/FileUploader( 4218): 	at com.owncloud.android.operations.UploadFileOperation.run(UploadFileOperation.java:399)
E/FileUploader( 4218): 	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:145)
E/FileUploader( 4218): 	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:149)
E/FileUploader( 4218): 	at com.owncloud.android.operations.common.SyncOperation.execute(SyncOperation.java:93)
E/FileUploader( 4218): 	at com.owncloud.android.files.services.FileUploader.uploadFile(FileUploader.java:1090)
E/FileUploader( 4218): 	at com.owncloud.android.files.services.FileUploader$ServiceHandler.handleMessage(FileUploader.java:1023)
E/FileUploader( 4218): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/FileUploader( 4218): 	at android.os.Looper.loop(Looper.java:189)
E/FileUploader( 4218): 	at android.os.HandlerThread.run(HandlerThread.java:61)
```

### Expected behaviour
The file should be uploaded or a sensible error message be shown.
 
### Steps to reproduce
1. In the nextcloud app, click the "uploads" menu entry
2. Click on one of the failed uploads.

### Environment data
Android version: 5.0

Device model: Wiko Rainbow Up

Stock or customized system: -

Nextcloud app version: 3.0.3

Nextcloud server version: 12.0.5

#### Web server error log
No entries in the error log, no entries in the access log.

#### Nextcloud log (data/nextcloud.log)
No entries in the nextcloud log.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky could this already be fixed via 3.1?

**Comment by cweiske** [comment]
I tried it with 3.1.0 RC1 and have the same problem:
```
E/FileUploader(29609): Error uploading
E/FileUploader(29609): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
E/FileUploader(29609): 	at com.owncloud.android.operations.UploadFileOperation.run(UploadFileOperation.java:399)
E/FileUploader(29609): 	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:145)
E/FileUploader(29609): 	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:149)
E/FileUploader(29609): 	at com.owncloud.android.operations.common.SyncOperation.execute(SyncOperation.java:93)
E/FileUploader(29609): 	at com.owncloud.android.files.services.FileUploader.uploadFile(FileUploader.java:1097)
E/FileUploader(29609): 	at com.owncloud.android.files.services.FileUploader$ServiceHandler.handleMessage(FileUploader.java:1030)
E/FileUploader(29609): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/FileUploader(29609): 	at android.os.Looper.loop(Looper.java:189)
E/FileUploader(29609): 	at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by AndyScherzinger** [comment]
@cweiske are the files that failed pointing to an encrypted directory via the e2e feature?

@tobiasKaminsky the failing line of code (which leaves me with the impression of being e2e related) is:
```
// try to unlock folder with stored token, e.g. when upload needs to be resumed or app crashed
// the parent folder should exist as it is a resume of a broken upload
if (!mFolderUnlockToken.isEmpty()) {
```

**Comment by cweiske** [comment]
No, I did not enable any e2e features.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky @mario PR is #2449 and should imho be included in the next release.

**Comment by tobiasKaminsky** [comment]
It is kind of weird that this happens at all, as we get it from OCUpload:
https://github.com/nextcloud/android/blob/86e661bdd443368d5f37d4ee1673b6863251ea7c/src/main/java/com/owncloud/android/operations/UploadFileOperation.java#L221

Maybe it is some old upload from previous version.
In any case, your fix should work. I added another check to it.

**Comment by AndyScherzinger** [comment]
merged
