### ISSUE TITLE
Autoupload fails due to reset of the trusted certificate

### ISSUE THREAD

**Issue by redfave** [nextcloud/android#244]
### Actual behaviour
- Autoupload fails instantly on every photo to upload and every retry 
- No specific error code or error description
- No logs on Nextcloud server
### Expected behaviour
- Working autoupload feature
### Steps to reproduce
1. Take a picture
2. Wait for autoupload
3. See how it fails
### Workaround
1. Enter the Nextcloud app
2. Try to upload a file from within the Nextcloud app
3. Nextcloud app asks you if trust the certificate of your cloud
4. Tap Yes
5. Go to upload queue
6. Select retry all failed uploads
7. It works now flawlessly
8. Profit
### Suggestion

The dialogue if you trust your unsigned certificate should be accessable from within the upload queue
### Environment data

Android version: 6
Device model: LG G3 (D855)
Stock or customized system: Stock
Nextcloud app version: 1.2.0
Nextcloud server version: 10.0 (stable)
**Self signed certificate**
#### Web server error log
- Nothing to insert
#### Nextcloud log (data/nextcloud.log)
- Nothing to insert

**Comment by Huster-at-github** [comment]
> Go to upload queue
> Select retry all failed uploads
> It works now flawlessly

Same here, but without certificate problem. My certificate is official.

## Environment data

Android version: 6
Device model: OnePlus 3
Stock or customized system: Stock
Nextcloud app version: 1.2.0
Nextcloud server version: 10.0 (stable)
**Official signed certificate**

**Comment by tobiasKaminsky** [comment]
As the upload is a background job I do not know how we can get this dialog to work. @mario any idea?

But the certification dialog should open right after entering the app so it seems to me a very rare corner case.

**Comment by mario** [comment]
Dear users,

thank you for your patience. After lots of work, we’re super excited to be able to give you a test version with new auto upload implementation. Keep in mind we will only accept bugs related to Auto Upload in this APK, as other things might be broken.

https://cloud.nextcloud.com/s/ftZraTruRQjTe0R

This is a dev APK so it will not overwrite your existing play store/f-droid APK unless you’re already running dev version. Also, you might need to remove your existing dev version before installing this one.

Explanation of the current functionality:
- added support for custom folders
- separated image and video folders
- checks for new files happens every 15-20 minutes
- automatic retry every 15-20 minutes or when you force close/open the app
- automatic pause once network is changed (untested!)
- significantly less battery usage

All and any testing is more than appreciated, especially with large and ever-going files like Videos. (like, try to record a 30 min video).

Let me know if you’ve got any questions.

Cheers,
Mario

**Comment by evilantishad0w** [comment]
Ran into this problem with the latest release with a cert issue and auto-uploading phone contacts.  Phone was continuously retrying upload and failing, which is poor behavior.  Wasn't able to stop it until I opened files and approved the cert.  Needs to at least detect when it's having problems uploading and stop retrying.

**Comment by tobiasKaminsky** [comment]
Given the fact that only 2 users reported this issue, I consider this as not worth fixing at, as there is a work around: open app and approve the cert. Otherwise one would also not be able to browse files.
