### ISSUE TITLE
Activities section in app stays empty

### ISSUE THREAD

**Issue by SimJoSt** [nextcloud/android#2441]
### Steps to reproduce
1. Go to Activities in Nextcloud app

### Actual behaviour
- no activities shown
- it says "No activities for now."

### Expected behaviour
- the activities, which are available through the web interface, should be shown
- if an error occurs, print a sensible error message

### Environment data
Android version: Android 7.1.2

Device model:  Lenovo ZUK Z1

Stock or customized system: LineageOS 14.1

Nextcloud app version: 3.0.3

Nextcloud server version: 13.0.1

#### App error log
After successfully running `GetRemoteActivitiesOperation` and getting a valid response the following error occurs:

```
2018/04/08 15:40:55
GetRemoteActivitiesOperation : Exception while getting remote activities Exception : [
com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224), 
com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41), 
com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82), 
com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61), 
com.google.gson.Gson.fromJson(Gson.java:888), 
com.google.gson.Gson.fromJson(Gson.java:953), 
com.owncloud.android.lib.resources.activities.GetRemoteActivitiesOperation.parseResult(GetRemoteActivitiesOperation.java:160), 
com.owncloud.android.lib.resources.activities.GetRemoteActivitiesOperation.run(GetRemoteActivitiesOperation.java:119), 
com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:145), 
com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:149), 
com.owncloud.android.ui.activity.ActivitiesListActivity.lambda$fetchAndSetData$5$ActivitiesListActivity(ActivitiesListActivity.java:257), 
com.owncloud.android.ui.activity.ActivitiesListActivity$$Lambda$2.run(Unknown Source), 
java.lang.Thread.run(Thread.java:761)
]

2018/04/08 15:40:55
ActivitiesListActivity : Unexpected exception

2018/04/08 15:40:55
FileDisplayActivity : onSaveInstanceState() start

2018/04/08 15:40:55
FileDisplayActivity : onSaveInstanceState(Bundle) starting

2018/04/08 15:40:55
ExtendedListFragment : onSaveInstanceState()

2018/04/08 15:40:55
FileDisplayActivity : onSaveInstanceState() end

2018/04/08 15:40:55
FileDisplayActivity : onStop() ending
```

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky @mario any ideas?

@SimJoSt just realized that you are running an old version of the Nextcloud server, where you should at least run 11.0.8 since you else will run into login issues as far as I know.

**Comment by AndyScherzinger** [comment]
> That said, I do agree that the app should show an error if one occurs and not just show the default "No activities yet" view.

Yes, totally agree on that since not showing that something went wrong is imho bad UX :+1:

**Comment by SimJoSt** [comment]
Uh, my mistake. Of course I am running **13**.0.1
I corrected the original post.

**Comment by AndyScherzinger** [comment]
@SimJoSt do you have a way to provide the JSON reply from the server, so we can reproduce the error? I can't really tell from the stack trace why it happens just that the JSON parser crashes since it doesn't like the reply/data/format/whatever.

**Comment by AndyScherzinger** [comment]
@SimJoSt Other than that, are you running the app via f-droid or via Google Play?

**Comment by SimJoSt** [comment]
I tried both versions. Same result.
Didn't try today's release on f-droid yet.

I will try to sanitize the JSON, so it doesn't contain any personal data, but it should be fine, as the're not that many files on there yet.

**Comment by AndyScherzinger** [comment]
Having the JSON would be really great since then I'd say we should be able to reproduce + fix this issue :+1: 
Thanks for all your efforts!

**Comment by SimJoSt** [comment]
Huh. Ok, this is weird.
Earlier today I deleted the last log file from the app out of my root cloud folder. Just now I was looking for it in the trash and couldn't find it. After asking other users of the same cloud, if they are having issues as well and they said no, I tried again. Created a simple text file, deleted it, switched to trash and reloaded. Jup, there it was. But no other deleted files... Also no the ones from a few months ago.
I think to myself, one issue at a time, open the app to create a new log and lo and behold, the activity feed loads without any problem.

I will try to figure out a way how to restore the last "broken" log file from our cloud backup site. Even if this issue is resolved for me personally right now, inconsistencies should never be ignored :-)

**Comment by AndyScherzinger** [comment]
True, this issue needs to be fixed. Does the error occur if you scroll down to the end of the activity list? Not sure when we introduced block wise reading for the activities feed, might be 3.1,not sure.

**Comment by SimJoSt** [comment]
I hope it is readable at all and if you need more, just ask: https://gist.github.com/SimJoSt/5b4acbe13c606b406c6e0464a1668456
I could provide you an unsanitized version privately.

**Comment by tobiasKaminsky** [comment]
Thanks @SimJoSt for this snippet.
Can you mail me the unsanitized version to tobias at nextcloud dot com with a reference to this issue?
The problem is that I now get an error due to your replaced "***REMOVED SENSITIVE VALUE***"

**Comment by tobiasKaminsky** [comment]
I found one error, but it still would be cool to have the entire snippet.
https://github.com/nextcloud/activity/issues/277

**Comment by SimJoSt** [comment]
Where can I send it to you privately?

**Comment by tobiasKaminsky** [comment]
@SimJoSt tobias at nextcloud dot com with a reference to this issue.

**Comment by tobiasKaminsky** [comment]
@SimJoSt is this still valid?
As far as I remember, I harded parsing of activities, so that even if one activity is not working, all other should be shown.

**Comment by SimJoSt** [comment]
"Unfortunately" I cannot reproduce the issue anymore.
I believe this issue is resolved, but as it just started working for me again, so I have no idea why.
