### ISSUE TITLE
multiple file selection is not removed after deleting files

### ISSUE THREAD

**Issue by andreasmalta** [nextcloud/android#2463]
### Actual behaviour
i'm selecting multiple files and then I delete them. on the screen it still tells me "2 selected"

### Expected behaviour
I expect automatic deselection after deleting the files
 
### Steps to reproduce
1. upload 2 test files
2. select both files (multiple selection
3. select to delete them all
4. the files are deleted but the selection stays on top of the screen

### Environment data
Android version: 8.0.0

Device model: Samsung SM-G950F

Stock or customized system: Stock

Nextcloud app version: 3.1.0

Nextcloud server version: 13.0.1

**Comment by AndyScherzinger** [comment]
@andreasmalta thanks for reporting this!

@tobiasKaminsky @tobiasKaminsky could reproduce the issue on latest master.

**Comment by jmintb** [comment]
I would like to tackle this.

Just to make sure that I understand correctly, is the desired effect here, that we leave the selection mode or simply reset the selection count to 0?

**Comment by jmintb** [comment]
@AndyScherzinger The selection isn't cleared when selecting "local only", should I make a new PR to adress this? :)

**Comment by AndyScherzinger** [comment]
I'd say so yes, to have a consistent behavior for actions triggered for multi selections

**Comment by jmintb** [comment]
@AndyScherzinger then I will include it in #2861, as it deals with the same issue. :)

**Comment by AndyScherzinger** [comment]
Sounds good to me 👍
