### ISSUE TITLE
Apostrophes

### ISSUE THREAD

**Issue by MeiRos** [nextcloud/android#2464]
### Actual behaviour
- while using finnish translation there are apostrophes around klo (=time) at file listings. 

### Expected behaviour
- Apostrophes can be removed. Those are not needed. Text is clearer without them. Use klo or kello not 'klo'. It's ok even without klo, kello or 'klo' too. 
 
### Steps to reproduce
1. Install android app
2. Use finnish translation
3. 

I did not find that part in transifex. It must be deeper in the code. 

http://i66.tinypic.com/2ll1wdk.jpg

**Comment by tobiasKaminsky** [comment]
We do not add this within our app, but we use 

https://github.com/nextcloud/android/blob/a2fac73af364734e7eb8a877e54f0d8e53518439/src/main/java/com/owncloud/android/utils/DisplayUtils.java#L344-L370

which is using the android built in system. There is on some android version a problem with too many apostrophes. We would have to remove this manually, for specific languages and on specific times, which is hard to maintain.

**Comment by MeiRos** [comment]
With Android 9 there are no unnecessary apostrophes.
