### ISSUE TITLE
modsecurity apache blocks deleting folder and e2e also

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/android#2465]
on an apache 2 system with active modsecurity I can not delete a folder via app, nor to create an e2e folder. if I disable the modsecurity everything returns to work. How can I solve? I am attaching errors in the modsecurity log file

Message: Warning. Match of "within %{tx.allowed_methods}" against "REQUEST_METHOD"$Message: Access denied with code 403 (phase 2). Operator GE matched 5 at TX:anomal$
Message: Warning. Operator GE matched 5 at TX:inbound_anomaly_score. [file "/usr/s$
Apache-Error: [file "apache2_util.c"] [line 273] [level 3] [client %s] ModSecurity$Apache-Error: [file "apache2_util.c"] [line 273] [level 3] [client %s] ModSecurity$Apache-Error: [file "apache2_util.c"] [line 273] [level 3] [client %s] ModSecurity$Action: Intercepted (phase 2)
Apache-Handler: proxy:unix:/run/php/php7.0-fpm.sock|fcgi://localhost
Stopwatch: 1523565520305204 465610 (- - -)                                         Stopwatch2: 1523565520305204 465610; combined=7687, p1=949, p2=6252, p3=0, p4=0, p$Producer: ModSecurity for Apache/2.9.1 (http://www.modsecurity.org/); OWASP_CRS/3.$Server: Apache/2.4.25 (Raspbian)                                                   Engine-Mode: "ENABLED"
--186c2139-Z--

**Comment by tigernero79** [comment]
which rules enable why nextcloud works with apache active modsecurity?

**Comment by tobiasKaminsky** [comment]
@nextcloud/server-triage do we support this?

**Comment by tigernero79** [comment]
tobias, I do not understand if the question was related to me or someone of the staff, however if I have active modsecurity I can not delete folders or to encrypt a folder I'm wrong.
non-empty folder says or you do not have permission to delete this acrtella.
If I disable the mod security everything returns to work.

I think I should activate some rules,
for webdav already I have enabled the permissions for the calls propfind and it works,
not understand instead for deleting the folder and encrypting what to enable.

**Comment by blizzz** [comment]
well, modsecurity is an apache module that can be configured with rules. If it blocks some endpoints in Nextcloud, those need to be adjusted. i don't see anything here to be done for either the client nor the server.

**Comment by MorrisJobke** [comment]
There is no official support for this, so if it works if you disable mod_security then it's up to you to configure it properly to work with Nextcloud.

**Comment by AndyScherzinger** [comment]
Thanks for the Feedback @MorrisJobke - thus closing this issue.
