### ISSUE TITLE
It bounces back to the login screen.

### ISSUE THREAD

**Issue by mogibu** [nextcloud/android#2466]
### Actual behaviour
- Tell us what happens

### Expected behaviour
- Tell us what should happen
 
### Steps to reproduce
1. 
2. 
3. 

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by nerijus** [comment]
Happens here with nextcloud-10.0.4-2.el7.noarch (packages from CentOS 7 epel repo).

**Comment by AndyScherzinger** [comment]
@nerijus If you can upgrade to at least 11.0.8 than that is what I would recommend (10 is end of life and so will 11 be this May). If you can't upgrade the server you need to use the App version 2.0.1 which is available via the download server: https://download.nextcloud.com/android/

**Comment by AndyScherzinger** [comment]
--> nextcloud-20000199.apk

**Comment by nerijus** [comment]
Do you know if packages in CentOS 7 epel repo will be updated?

**Comment by AndyScherzinger** [comment]
No ideas sorry. As for notifications about unsupported server versions I already opened an issue to have such a thing in the future. No. Implementation yet though.
