### ISSUE TITLE
Sorting not working 

### ISSUE THREAD

**Issue by MeiRos** [nextcloud/android#2467]
### Actual behaviour
- I try to upload a picture from my phone. 
Choose +, Choose upload, go to Camera folder and try to sort pictures. I have more than 1000 pictures and videos in the folder. Can't sort at all.  

### Expected behaviour
- Sorting should work

### Environment data
Android version:
8.0.0
Device model: S8

Stock or customized system:Stock

Nextcloud app version:dev 20180412

Nextcloud server version:13.0.1

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky it seems sorting broke with the move to the RecyclerView implementation for the local file listings (remote file list sorting seems fine to me)

**Comment by surajdubey** [comment]
I'd love to submit PR for this @AndyScherzinger

**Comment by AndyScherzinger** [comment]
Hi @surajdubey! You are highly welcome. The sorting implementations should already be there and are in use for the remote file listings but it seems they have been utilized for the local file listings. In any case feel free you takkle this and if any questions come up feel free to just ask. @tobiasKaminsky did the original rewrite from ListView to RecyclerView so he should be able to answer any question, same goes for @mario and me :)

**Comment by kosli** [comment]
is there any news on this issue? @surajdubey @AndyScherzinger

**Comment by AndyScherzinger** [comment]
@MeiRos @kosli fix has been merged to master, thus will ship with the next nightly and with 3.2.0
