### ISSUE TITLE
F-Droid store icons are not consistent

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/android#2469]
### Actual behaviour
- Icons in f-droid store are not consistent 

### Expected behaviour
- All the icons used in Play Store and F-Droid should be consistend across all the apps.
 
### Steps to reproduce

The icons on the devices do not matter because they are adaptive. But the icons on each store should be consistently square, but not mixed.

#### Play Store

![grafik](https://user-images.githubusercontent.com/4741199/38771709-16687e2e-4028-11e8-9af4-be43e394e5ec.png)

#### F-Droid

![grafik](https://user-images.githubusercontent.com/4741199/38771714-3e42826e-4028-11e8-97b9-edff08ca1986.png)

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger since you did the adaptive stuff, do you recall what our decision was? The "intended" shape is a circle, at least for this app, or?

@nextcloud/designers what is your opinion here? As Stefan said, it is only for gplay/fdroid store as the devices shape it dynamically.

**Comment by stefan-niedermann** [comment]
I personally would go for the square icon because more of the nice background is visible and it makes the logo in general more visible compared to other apps since it is simply bigger.

But that's just an personal taste i guess...

**Comment by AndyScherzinger** [comment]
We never had a decision for the store icons while Jan prefers the circle in general. I am fine either way. My guess would be that’s droid is using the launcher icon...

**Comment by AndyScherzinger** [comment]
Do yo know how to change the f-droid store listing icon? Is this possible? cc @Bubu

**Comment by tobiasKaminsky** [comment]
https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots

We can put a icon.png into default locale, this then should overwrite the auto extracted one.

**Comment by jancborchardt** [comment]
We did use the rounded rectangle for long – but the new preferred background is the circle, as it fits much better with our logo and general forms.

Hence the Talk app should be adjusted to use circle by default. cc @mario

**Comment by tobiasKaminsky** [comment]
I updated it also on play store, so that we have also round icon.
https://play.google.com/store/apps/details?id=com.nextcloud.client

![image](https://user-images.githubusercontent.com/5836855/41045454-c1b097ae-69a8-11e8-9cf6-2de5071ef747.png)
