### ISSUE TITLE
Trying to create folder with already existing name shows »Method not allowed«

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/android#2470]
### Actual behaviour
- I try to create a new folder and a toast shows with »method not allowed«. I didn’t know a folder with that name already existed.

### Expected behaviour
- The app should give helpful feedback like a toast saying
> Folder already exists. **Open foldername**

**Comment by AndyScherzinger** [comment]
:+1: yes, that would be way better :+1:

**Comment by ardevd** [comment]
If I'm not mistaken, this is not something that can be fixed through the app itself. The Toast message simply shows the HTTP response message returned by the server. When creating a directory that already exists the remote operation returns [HTTP error 405](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405). See attached screenshot for more info.

In other words, this needs to be fixed server side as there is no way for the app to know why the operation failed other than the error message returned by the server.

![nextcloud_error](https://user-images.githubusercontent.com/366855/38798327-963fba88-4161-11e8-81d8-b341c7f7479a.png)

**Comment by AndyScherzinger** [comment]
@ardevd true, while when getting a 405 and knowing the user tried to create a directory we could check if the directory already exists (or do that even before we try to create it). So Yes, having a nicer server response would be great  :) What do you think @nextcloud/server-triage?

**Comment by ardevd** [comment]
@AndyScherzinger We could definitely come up with some hacky spagetti code that tries to figure out why a 405 error was returned. However, I'm fairly sure the proper fix here is to implement better error responses on the server side.

**Comment by rullzer** [comment]
Well actually 405 is the correct response here. As the url is already mapped. https://tools.ietf.org/html/rfc4918#section-9.3.1

**Comment by tobiasKaminsky** [comment]
On creating/uploading a file we do not have this problem, as we are checking for the existence and if so then append (2), (3).
I think we should handle this in https://github.com/nextcloud/android-library/blob/107c575d44e9b00e880b8a36b45bd09c8949b6ef/src/com/owncloud/android/lib/resources/files/CreateRemoteFolderOperation.java#L44 and return a FOLDER_ALREADY_EXISTS.

If we do this in our library, we have clean way, I think.

**Comment by tobiasKaminsky** [comment]
Is already fixed: https://github.com/nextcloud/android/pull/2807
