### ISSUE TITLE
isInternetWalled returns wrong value for servers behind firewall

### ISSUE THREAD

**Issue by schaarsc** [nextcloud/android#2472]
isInternetWalled "pings" the server only if device is online ***and*** is using WiFi. 
Current implementation is missing the use case in which server is not reachable (e.g. because server is behind firewall or in maintenance mode). 

Assuming server requires VPN to work, isInternetWalled returns wrong value:
If the device is connected without VPN and not using WiFi: isOnlineWithWifi returns false, Device.getNetworkType returns != ANY and as a consequence isInternetWalled returns false, this in turn allows synch jobs to start even if server is not reachable.

Why is the server not contacted if the device is connected, but not using WiFi?  

I suggest to replace
https://github.com/nextcloud/android/blob/1cbee0e903e2cc7ef22cf417ae8cd537dbb97677/src/main/java/com/owncloud/android/utils/ConnectivityUtils.java#L52
with
`if (!Device.getNetworkType(context).equals(JobRequest.NetworkType.ANY)) {`

**Comment by AndyScherzinger** [comment]
Pinging @mario seince he is the wizard when it comes to the auto upload implementation and network detection :)

**Comment by tobiasKaminsky** [comment]
The idea behind isInternetWalled is to detect walled garden / capative portals on wifi. We assumed that you do not have a restriction on mobile data. So to not query the server that often, we check only on WiFi.

Having a server behind a firewall/VPN is an edge case we/ have not thought about.
With the behaviour of 2.x this would then also have failed, so this is just not an enhancement, or is it a regression for you?

**Comment by schaarsc** [comment]
I agree, it is a corner case, so let's label it as enhancement...

To reduce the traffic, would it be possible to use BroadcastReceiver / CONNECTIVITY_ACTION and only check when event is received?

**Comment by mario** [comment]
Not really. You could be behind a walled internet but you're signed in. In 45 minutes you're still connected but the wall signed you out. What then? :D

**Comment by schaarsc** [comment]
what about "caching" last result if not connected to WIFI? run a new check only if result is older than x minutes  (x<=5)?
