### ISSUE TITLE
Upload view: "no uploads" not tinted?

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#2478]
Shall this upload icon be tinted? For me it looks kind of weird as the default blue is never shown everywhere else.

![2018-04-17-131157](https://user-images.githubusercontent.com/5836855/38866358-f2644f10-4240-11e8-83fd-06a2816d9275.png)

**Comment by AndyScherzinger** [comment]
Nope from what I understood in the past from Jan is that it should be grey while I forgot to ever fix this :(
