### ISSUE TITLE
Provisioning Links to launch and prefill app with login data

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#248]
I thought about this feature for a while and saw that @paraqles now also opened a feature request for that on the oC Android client tracker.

My request (which I would implement myself) would be do implement Nextcloud URLs which could do exactly that but would like to do this in a way as it is proposed by Google/Android/Chrome.
https://developer.android.com/guide/components/intents-filters.html#Receiving
https://developer.chrome.com/multidevice/android/intents
https://github.com/zxing/zxing/blob/master/android/AndroidManifest.xml#L99

The exact schema(s) will have to be defined during implementation. The schema should read in a flexible way as in might just contain the server address, might also have the username, might have the password (or not).

Any input @nextcloud/designers @nextcloud/android

**Comment by MorrisJobke** [comment]
> might have the password (or not).

As we have app specific password functionality on the server we could use this to provision them.

**Comment by AndyScherzinger** [comment]
:smiley: that would be an option, yes. I just defined it like that to have a format which supports setting a value or not, so any combination of the 3 (address, username, password) is valid and will pre-fill the login screen accordingly b/c this would support address only for things like "Android users click here and login with your credentials"

**Comment by tobiasKaminsky** [comment]
You mean you click on this link "nc://myuser:mypass@myserver" and nc app is opened and, if necessary, a new account is created?
What would be the use case of it? How and where do you get this link?

**Comment by AndyScherzinger** [comment]
Right now it would have to me manually written by a human person, in the future this could be generated from the server :) -  I am already working on the implementation, will hopefully push a first implementation this week :rocket:

**Comment by tobiasKaminsky** [comment]
Understood. When there will be a server side it is a good idea.
Isn't this somehow related to the idea with qrcodes?

**Comment by AndyScherzinger** [comment]
Kind of. Whever my PR is integrated it would also work for URLs since they could just be QR-codes for URLs and then just use Nextcloud to open them :D

**Comment by AndyScherzinger** [comment]
Implementation has been started: #253
