### ISSUE TITLE
Menu with icons

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#2483]
![menu with icons](https://user-images.githubusercontent.com/5836855/38918981-96671ff8-42ef-11e8-97ed-8d3eb05d5d9f.jpg)

We brainstormed a bit on hackweek and @jancborchardt came up with adding icons to overflow menu as part of new sharing.
As this would blow up sharing PR, this can and should be done independent. 

The idea is to not have an icon on every entry, but only on the most important ones.

**Comment by AndyScherzinger** [comment]
Sounds good to me. Do we then still want to keep the overflow menu or also make use of bottom sheet menus?

**Comment by tobiasKaminsky** [comment]
On overflow per file in file list, we maybe could switch to bottom sheet; though I am unsure how this looks like as we have many many options there.
On global options in file display or in options for preview image, I would keep it the current way.

So I would decide on case by case.

**Comment by AndyScherzinger** [comment]
Fine with me!

**Comment by jancborchardt** [comment]
Let me know if you have any questions btw! :)

The icons are all available in the server repo at https://github.com/nextcloud/server/tree/master/core/img/actions, with a handy visual guide at https://docs.nextcloud.com/server/14/developer_manual/design/icons.html

**Comment by jancborchardt** [comment]
Just one important thing if we use the bottom sheet: As header, we need to use something relevant like the file/foldername (if it’s the actions of a file/folder) or the username (if it’s sharing options for a specific user).

**Comment by joshtrichards** [comment]
Fully implemented in #11008
