### ISSUE TITLE
Make available offline as default

### ISSUE THREAD

**Issue by mase76** [nextcloud/android#249]
Hi!
Please add an option to make new files and folders available offline as default.
Why aren't new files copied to the nextcloud folder synced automatically? That would be the same behaviour than the desktop client has. I mean like a normal webdav folder.
I think, that would make things much easier.

**Comment by tobiasKaminsky** [comment]
This is not enabled because of the limited space of (most) phones.
In the future there will be a real 2 way sync and also an extended 1 way sync, so this should then solve your wishes.
