### ISSUE TITLE
progress bar not working

### ISSUE THREAD

**Issue by fabianfrz** [nextcloud/android#2496]
### Actual behaviour
- graphical progress bar in view stays 0% while the message from the system shows the progress

### Expected behaviour
- progress should match the real progress and always should be equal to the system dropdown menu
 
### Steps to reproduce
1. upload a list of files
2. click on it to open the upload view

### Environment data
Android version: 5

Device model: Nexus 10

Stock or customized system: St0ck

Nextcloud app version: 3.2

Nextcloud server version: 13

**Comment by AndyScherzinger** [comment]
closing as duplocate of #2480 - Fix has been merged to master and will ship with 3.2
