### ISSUE TITLE
Failed to import android-library into my project app

### ISSUE THREAD

**Issue by ainnazrah95** [nextcloud/android#2499]
### Actual behaviour
- When I'm trying to import android-library module by right-click on the project app, New ->New module -> add gradle file ->"ERROR to load the module"

-already add maven { url "https://jitpack.io" } under build.gradle project and already add implementation 'com.github.nextcloud:android-library:-SNAPSHOT' under build.gradle module

### Expected behaviour
- nextcloud androd-library should be available in my project. 
 
### Steps to reproduce
1. 
2. 
3. 

### Environment data
Android version: 3.1.1

Device model: Xiaomi Redmi Note 5A Prime

Stock or customized system:

Nextcloud app version:

Nextcloud server version: 13

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
Hi @ainnazrah95 sometimes jitpack has some hick-ups with providing the latest master snapshot of the lib.
For the time being you could use 1.0.40 instead which has the same code base.
