### ISSUE TITLE
Android app returns unknown error. Android Monitor shows html page being loaded

### ISSUE THREAD

**Issue by supportreq** [nextcloud/android#250]
Dear All,

For my new nextcloud installation, i am trying to login through the android app, it returns unknown error. While verifying the android monitor it shows that the webapp is being loaded instead..

/GetRemoteUserInfoOperation: Successful response: <!DOCTYPE html>
                                                                                     <html class="ng-csp" data-placeholder-focus="false" lang="en" >

please advice is there an error with the server or the mobile app.

thank you

**Comment by supportreq** [comment]
Verified using owncloud android app as well.. returning the same error.. windows clients work fine.. but i m not sure why android is not taking this.. also identified, this seems specific to my setup.. if i did a fresh install on another subdomain it worked fine..

it is 
SNI done, hostname: ********
09-10 13:27:26.652 25489-26576/com.nextcloud.android D/OwnCloudClient #1: Location to redirect: https://*********/index.php/apps/files

Why is it redirecting any clue?

**Comment by tobiasKaminsky** [comment]
Maybe some misconfiguration in your apache?

**Comment by supportreq** [comment]
@tobiasKaminsky what should i check? cause another installation on same server works well..

**Comment by AndyScherzinger** [comment]
@MorrisJobke could this also be related to the legacy login URL topic?

**Comment by MorrisJobke** [comment]
> @MorrisJobke could this also be related to the legacy login URL topic?

Possible.

**Comment by AndyScherzinger** [comment]
Hi @supportreq can you test our latest beta client release (can be installed in parallel to the regular app):
https://f-droid.org/repository/browse/?fdfilter=com.nextcloud&fdid=com.nextcloud.android.beta

It contains a fix for a login issue we found, so this might solve your problem and will then also be integrated into the next regular/stable release 1.4.0

**Comment by supportreq** [comment]
@AndyScherzinger verifying...

**Comment by supportreq** [comment]
@AndyScherzinger it is working on the latest nextcloud 2nov 2016 version...

thanks!!
