### ISSUE TITLE
Folder path in auto upload not ellipsized

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#2506]
![2018-04-24-073018](https://user-images.githubusercontent.com/5836855/39167818-66479c20-4791-11e8-9b91-66237b213387.png)

As seen the folder path in long folder names is not ellipsized, but only truncated at the end.
This should be, like it was back some time, changed to ellipsize in the middle.

The cool feature, that path is expanding after clicking on it, still works :+1:

**Comment by tobiasKaminsky** [comment]
It seems to be correctly set, however it does not work:
https://github.com/nextcloud/android/blob/6da1079ce51258714002f13d8e40ff9b551f866b/src/main/res/layout/synced_folders_settings_layout.xml#L188-L189

**Comment by AndyScherzinger** [comment]
Strange really :/

**Comment by tobiasKaminsky** [comment]
I would close this. It is not perfect, but one can click on it to see the full path (which is not obvious), and one can still click on the "browse" icon to see the full path…
