### ISSUE TITLE
Splash screen shown when returning from preferences

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#2507]
### Actual behaviour
- Splash screen is shown

### Expected behaviour
- Splash screen should only be shown on app start
 
### Steps to reproduce
1. start app (see splash screen)
2. go to settings
3. click "back arrow" -> see splash screen

@ardevd since you implemented the splash screen, can you have look into this?

**Comment by ardevd** [comment]
Yep! I'll look into it.

**Comment by tobiasKaminsky** [comment]
Great :-)
I assigned it to you, so that no one else takes it.
