### ISSUE TITLE
Failed to download files when path is /storage/sdcard1

### ISSUE THREAD

**Issue by susobaco** [nextcloud/android#2513]
### Actual behaviour
- The client won't let me download any files. Failed to download

### Expected behaviour
- Tell us what should happen
 
### Steps to reproduce
1. I configure nextcloudclient with the download path in the configuration in /storage/sdcard1 (microsd storage)
2. I'm trying to download a file.
3. Failure to download the file (When by default settings, download without any problem)

### Environment data
Android version:
4.4.4
Device model: 
Primux Omega 6
Stock or customized system:

Nextcloud app version:
3.1.0
Nextcloud server version:
13.0
#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
I didn't find the log (where or hoz can I fiad it?)
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by ardevd** [comment]
@susobaco Could you use `adb shell` or a terminal emulator to verify that `/storage/sdcard1 `actually exists? 

Could you post a stack trace with `adb logcat `from when you try to download a file?

**Comment by susobaco** [comment]
Yes, the directory exists. Let's see if this log works. Thank you!
https://cloud.disroot.org/s/Rbz2Q8MzYWXnf6B

**Comment by ardevd** [comment]
@susobaco Your stack trace is missing the initial cause of the crash (it seems). Could you try and include the first reference to the crash in your log output?

Also, just out of curiosity, have you tried re-installing the app? If you've had the app installed for a long time your issue might be related to the storage path system migration we did a while back.

**Comment by tobiasKaminsky** [comment]
> If you've had the app installed for a long time your issue might be related to the storage path system migration we did a while back.

Then it would be nice to see the real cause and fix it.
So @susobaco can you first try to get the logcat and after that re-install it (if needed).

Just a quick idea: Does NC has the permission to write to external storage? Please verify this in app details.

**Comment by susobaco** [comment]
Hi, if I use nextcloud dev from f-droid, the application just crashes. Attached register
[currentLog.txt](https://github.com/nextcloud/android/files/2055190/currentLog.txt)

**Comment by susobaco** [comment]
Hi, after much research, I applied this solution to my android 4.4 and the problem was fixed.
https://technofaq.org/posts/2014/04/fixing-external-sd-card-write-issue-on-android-kitkat/
Thanks for the help.
