### ISSUE TITLE
Crash at files loading

### ISSUE THREAD

**Issue by stemy2** [nextcloud/android#2515]
### Actual behaviour
- Tell us what happens
After connecting and an attempt to load the files, the app crashes become unable to launch.
### Expected behaviour
- Tell us what should happen
 I should be able to use the app.
### Steps to reproduce
1. Open the app
2. Connect yourself
3. Wait for some seconds
4. try to relaunche the app.

### Environment data
Android version:
6.0.1
Device model: 
Fairphone 2
Stock or customized system:
Fairphone open
Nextcloud app version:
3.1.0
Nextcloud server version:
12.0.4
#### Web server error log
```
Insert your webserver log here
Can't open the log cause my notepad can't detect the character encoding.

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
Can't open the log cause my notepad can't detect the character encoding.

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by stemy2** [comment]
The strange thing is that all those versions of this app worked fine on my previous phone that was exactly the same brand/model.

**Comment by ardevd** [comment]
@stemy2 Please post a strack trace of the crash using `adb logcat `so that we can investigate the crash further. Without any more details it's pretty hard to debug the issue.

**Comment by stemy2** [comment]
I' like to correct something: i installed the version 3.0.3 via apk and it works fine.
