### ISSUE TITLE
More icon in upload view has wrong color

### ISSUE THREAD

**Issue by splitt3r** [nextcloud/android#2516]
### Actual behaviour
- The more icon is black instead of white

### Expected behaviour
- Should be white
 
### Steps to reproduce
1. Open the file upload dialog on a themed Nc instance

### Environment data
Android version: 8

Device model: Nexus 6

Stock or customized system: Custom ROM

Nextcloud app version: Dev from F-Droid

Nextcloud server version: latest 13 from git

![upload](https://user-images.githubusercontent.com/1869584/39249691-8561f682-489f-11e8-9ce2-ff112213a2bc.png)

**Comment by surajdubey** [comment]
@AndyScherzinger I’d love to take up and fix this issue

**Comment by AndyScherzinger** [comment]
@surajdubey feel free and thanks for taking care of this issue!

@splitt3r can you still reproduce this issue? Just to be sure...

**Comment by splitt3r** [comment]
Nope :grin: with the latest beta version all icons are black in the top bar.

**Comment by AndyScherzinger** [comment]
Thanks for the feedback, I'll close this issue then.
