### ISSUE TITLE
Remove build tools from build.gradle

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#2523]
When outdated build tools are specified, we get this warning: 

> The specified Android SDK Build Tools version (26.0.2) is ignored, as it is below the minimum supported version (27.0.3) for Android Gradle Plugin 3.1.2.
Android SDK Build Tools 27.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '26.0.2'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

I think it is safe to remove it, as we nearly immediately get a notice of a failing build (either on devs machine or drone).

**Comment by ardevd** [comment]
You have two options. You can drop the Build tools version declaration and have the build system use whatever is default. This may or may not be the desired behaviour depending on your various CI tools. Alternatively, you can maintain the newest version manually.

**Comment by AndyScherzinger** [comment]
We should be rather save with ci while manually maintaining this has the advantage if knowing what is actually used in the build.

Sind we have nightly builds etc I'd say let's drop it :)

**Comment by tobiasKaminsky** [comment]
Let's try it :+1:
