### ISSUE TITLE
Re-add large picture preview when uploading

### ISSUE THREAD

**Issue by BlackDex** [nextcloud/android#2526]
### Actual behaviour
- When uploading new files (pictures in this case) there is no option to have big tiles without a filename.

### Expected behaviour
- Have an option to show larger image thumb/preview when uploading. I know this was available before and i really liked that. Now i can only show small previews with the filename and date etc.. besides it.
 
### Steps to reproduce
1. Choose a folder
2. Click the "+" sign at the bottom right
3. Select "Upload Files"
4. Browse to your camera folder (In my case DCIM)
5. Enable grid view using the 3dot menu top-right.

There is no option to view large images two side-by-side for instance. This was available before and very nice to preview the images. Now they are very small and sometimes not good to see when there are small details in the pictures.

### Environment data
Android version: 8.1.0 and 7.0

Device model: Nexus 5X and Galaxy S6 (SM-G920F)

Stock or customized system: Stock

Nextcloud app version: 20180425

Nextcloud server version: Owncloud 9.1.6 (I know i need to switch & upgrade ;) )

#### Web server error log
```
n/a
```

#### Nextcloud log (data/nextcloud.log)
```
n/a
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
Cc @tobiasKaminsky I can reproduce this. While you can pinch to zoom you'll basically end up with a 2 column list style grid for manual upload file picker instead of the typical grid layout used in the main remote files view.

**Comment by AndyScherzinger** [comment]
solved via #3008 to be shipped with 3.4.0
