### ISSUE TITLE
Not all images / videos upload

### ISSUE THREAD

**Issue by levster69** [nextcloud/android#2528]
It seems that recently, maybe for the last several weeks, the autoupload does not initiate on it's own, until I hit Force Rescan, and even then, not all the time. Additionally, when the upload does start, only some of the files get to be uploaded, where as others are not, even though the images may have been taken only several seconds apart. The behavior is very random. I just tried, taking three regular shots, and only one was uploaded on it's own. Force Rescan did not "find" other two images.

Samung S9
Android 8.0.0
stock.
Latest Nextcloud 3.1.0
Nextcloud server 13.0.1

**Comment by grandiego** [comment]
Same here.  Xiaomi mi max2, android 7. Latest client and server

**Comment by levster69** [comment]
I've reinstalled the app after deleting the account and clearing the cache. Still no go. Force rescan does nothing.

**Comment by Schroedingberg** [comment]
Old files not synced here. When I took a photo, that one was automatically uploaded though.

**Comment by AlexanderKgr** [comment]
Same bug here
S9 plus

**Comment by Bubbelb** [comment]
Got a dirty workaround. Flushing cache and Dalvik cache via TWRP starts the upload again. After a reboot, all the missing files are uploaded correctly. 
Newly created files aren't uploading again, until I flush cache & Dalvik cache again.
Flushing application cache doesn't help.

**Comment by feutl** [comment]
I am in the same boat with my S9

So many open tickets with the same issue, does this gets addressed ?
https://github.com/nextcloud/android/issues?page=2&q=is%3Aissue+is%3Aopen+label%3AAutoUpload
