### ISSUE TITLE
Photos get appended to other RecyclerView lists if you navigate away from Photos screen

### ISSUE THREAD

**Issue by ardevd** [nextcloud/android#2530]
### Actual behaviour
When navigating away from the Photos screen before the loading is complete, you'll suddenly see image files being appended to whatever RecyclerView list is currently visible.

### Expected behaviour
Navigating away from the Photos screen should cancel the image loading.
 
### Steps to reproduce
1. Open app
2. Go to Photos screen.
3. Let it load for a few seconds but before it completes, navigate to "All Files".
4. Notice how image files are suddenly appended to the bottom of the list.

### Environment data
Android version: 8.1.0

Device model: Pixel 2 XL

Stock or customized system: Stock

Nextcloud app version: 3.1.0

Nextcloud server version: 13.0.1

**Comment by tobiasKaminsky** [comment]
We need to properly kill the search operation.

**Comment by tobiasKaminsky** [comment]
I cannot reproduce it anymore.
If it still happens, please re-open.
