### ISSUE TITLE
Storage Continuously Increaseing

### ISSUE THREAD

**Issue by msonst** [nextcloud/android#2532]
### Actual behaviour
- Apps used storage increases significantly over time even though no files are kept local (7GB) (edit: setting do not delete locally in nextcloud. Manually deleting pictures once the content on phone once it appears in my backups)
- Only way to  (maybe) get rid of this is delete stored data via Google clean files, but then you'll get warned that you'd also remove settings, db, etc.

### Expected behaviour
- Almost constant storage usage when nothing kept local
- Way to safely clean app data, without being required to setup credentials again
 
### Steps to reproduce
1. Autosync dcim
2. Manual remove of pictures from device
3. Use for approx 7mo

### Environment data
Android version: 7

Device model: SM-G930A
Kernel 3.8.31-12564870

Stock or customized system: Stock

Nextcloud app version: 3.1.0

current unavailable, will add once I get back to the office

Nextcloud server version: 

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Can you use an app to see which folder is that big, e.g. DiskUsage?

**Comment by grospolina** [comment]
I have the same issue on my device. The uploaded images remain in the temporary folder on my sd-card:
`SD-Card/Android/media/com.nextcloud.client/nextcloud/tmp/MyUsername@MyServer/MySyncedFolder`

### Environment data
Android version: 6.0.1
Device model: Sony Xperia Z3 Compact
Stock or customized system: Stock
Nextcloud app version: 3.1.0
Nextcloud server version: 13.0.2

**Comment by msonst** [comment]
Hi,

Fthe folder looks similar in my side.

Sd/media/android/data/com.nextcloud.client/files/nextcloud/tmp/<user@domain>/<server folder structure>

Thanks Michael

**Comment by tobiasKaminsky** [comment]
I created a fix for this, which will be soon in dev version. 
It would be cool if you can test it there :+1:

**Comment by adyanth** [comment]
Is this still not fixed? I'm on 3.15.1 and currently nextcloud app is using 11+GB on my phone!

**Comment by Mister-Muffin** [comment]
Same Problem here!
Version: 3.21.0 RC1

**Comment by leojimenezcr** [comment]
Same problem. Nextcloud 3.22.3, Android 12.

I look into Android/media/com.nextcloud.client//nextcloud but there are no temporary files there

It seems that the cache files are being stored in another location.

**Comment by dmz006** [comment]
> Same problem. Nextcloud 3.22.3, Android 12.
> 
> I look into Android/media/com.nextcloud.client//nextcloud but there are no temporary files there
> 
> It seems that the cache files are being stored in another location.

Same version,  same problem

**Comment by dmz006** [comment]
/storage/emulated/0/Android/media/com.nextcloud.client/nextcloud/dmz@nextcloud.dmzs.com/DMZ-Phone/Camera

1237 files 3.87G

My dcim folder was cleaned,  and the files were uploaded,  I think.  I'll double check a few to be sure.

**Comment by dmz006** [comment]
![Screenshot_20221110-120805_Nextcloud](https://user-images.githubusercontent.com/548875/201075909-b5868eab-f425-4ada-88ba-2c6e11651585.jpg)
![Screenshot_20221110-120726_Nextcloud](https://user-images.githubusercontent.com/548875/201075919-885cf1ed-0b10-4426-b641-88111a297cbf.jpg)
![Screenshot_20221110-120523_Files by Google](https://user-images.githubusercontent.com/548875/201075921-55c2a82a-18f4-4308-b593-9616d9601aeb.jpg)
![Screenshot_20221110-120516_Nextcloud](https://user-images.githubusercontent.com/548875/201075926-c3983ff5-ab0c-4835-b955-17d74bdc7548.jpg)


The screenshots here show the sync folder with a green checkmark next to everything in the internal storage but upload show the images folder uploaded and I just started a sync manually and it is downloading from cloud to local,  into the internal storage and then the checkmark shows.

Is it is really synching why is it downloading into the local storage folder using 2x space for image in scimitar and nextcloud folder

**Comment by dmz006** [comment]
3.23.0 from 2022/12/1 appears to have fixed my problems. My almost 4G of storage is now down to 500M.
