### ISSUE TITLE
search results can not be opened (JPG)

### ISSUE THREAD

**Issue by schnello** [nextcloud/android#2534]
### Actual behaviour
Open App.
Press magnifying glass-
Enter search word.
If the result is an picture (jpg) the app doenst show the content. Only a white page.
![image](https://user-images.githubusercontent.com/6481341/39465448-b6f24778-4d23-11e8-9d3f-5f4a78eb26b5.png)

If i navigate directly to this file... it is shown as expected.
![image](https://user-images.githubusercontent.com/6481341/39465663-caf7f7ee-4d24-11e8-9e51-992900b6707e.png)

### Expected behaviour
The picture should be shown
 
### Steps to reproduce
1.  see Actual behaviour

### Environment data
Android version: 8.0.0

Device model: Samsung S8

Stock or customized system: stock

Nextcloud app version: 3.1.0

Nextcloud server version: 13.0.2

**Comment by ffreakboi** [comment]
,CSC RVfrfcffffffrf fty

**Comment by schnello** [comment]
looks like in the latest version this problem is solved.
