### ISSUE TITLE
"Upload failed" notifications stay even after they complete successfully 

### ISSUE THREAD

**Issue by W-Hamra** [nextcloud/android#2535]
Not an actual bug, just minor annoyance.

### Actual behaviour
- The app doesn't remove the notification that an upload has failed after it succeeds in a retry.

### Expected behaviour
- Once the app retries an upload and it succeeds, it should remove the notification.
 
### Steps to reproduce
- Take some pics
- During autoupload (while app is in background) switch networks, walk into a weak WiFi spot
- Nextcloud would should an upload failed notification.
- Walk back into good WiFi coverage. Wait few minutes.
- Notification still there, but if you tap on it, it shows all uploads successful.

### Environment data
Android version:
8.0.0

Device model: 
Galaxy Note 8

Stock or customized system:
Stock

Nextcloud app version:
3.1.0 (F_Droid)

Nextcloud server version:
13.0.1

**Comment by AndyScherzinger** [comment]
I agree, when all uploads that formerly had an error could be uploaded then the notification should be removed.

**Comment by joshtrichards** [comment]
Consolidating tracking for this enhancement into #3234
