### ISSUE TITLE
Crash when new version download fails

### ISSUE THREAD

**Issue by MyIgel** [nextcloud/android#2538]
### Actual behaviour
- After marking a file to be available offline the app checks every time before openimg it if a newer version is available (which is anoying when the network is bad) and it crashes when the network goes down

### Expected behaviour
- Don't check for newer files or at least stop it when the server doesn't respond after a second or two 
 
### Steps to reproduce
See actual behavior

### Environment data
Android version:
8.0.0

Device model: 
OnePlus 3t

Stock or customized system:
Stock

Nextcloud app version:
3.1.0

Nextcloud server version:
13.0.2

### Logs
Not available

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky thought you fixed this for 3.1 or is this fix scheduled for 3.2?

**Comment by tobiasKaminsky** [comment]
No, not in context of "available offline"…

**Comment by tobiasKaminsky** [comment]
No response within the last month, therefore closing.
Please feel free to reopen with additional infos, if the problem still exists.
