### ISSUE TITLE
Upload button / design issue with white color in theming app

### ISSUE THREAD

**Issue by BornToBeRoot** [nextcloud/android#2539]
You cannot read the text in the button...

![image](https://user-images.githubusercontent.com/16019165/39525959-c124593e-4e1d-11e8-8bbc-498685e351d9.png)

App Version: 3.1.0 (PlayStore)

NC13.0.2 with theming app and color white (`#FFFFFF`) 

![image](https://user-images.githubusercontent.com/16019165/39525989-d3b35208-4e1d-11e8-9801-3ac67487f1bf.png)

**Comment by AndyScherzinger** [comment]
Same goes for the icon in the middle of the screen (folder icon for empty content) which is tinted white while here it should be grey.

**Comment by tobiasKaminsky** [comment]
We just should forbid this ;-)
Similar to #2544, this needs indeed to be improved.
