### ISSUE TITLE
Incorrect filenames sharing files to the Nextcloud app due to different Android versions / file managers

### ISSUE THREAD

**Issue by Wikinaut** [nextcloud/android#2551]
filed here after having discussed with @jospoortvliet 

### Actual behaviour
I use two different HUAWEI phones. On my newer phone I notice - since at least many months - a strange behaviour when I upload a file via the "share" function inside the Huawei filemanager: the original filename e.g. ```test.test``` or ```1.1``` or ```00001.vcf``` is not transported to the Nextcloud server directory, intead a plain number like ```101663``` is shown, the file and filesize appears to be intact.

The filename is preserved when I "upload" a jpeg file via the share function.

### Expected behaviour
I expect that the correct filename is used and transported to the server directory.
 
### Steps to reproduce
1. Start the Filemanager, navigate to an internal or SD card directory
2. Rename a ```file.jpg``` to ```1.1``` (or create a file with that name)  
3. Long-click the file and select "Weitergeben" (~ share) in the "Mehr" ("more") context menu
4. Select to share with the "Nextcloud" app
5. Navigate to a suited Nextcloud directory and start the upload to there.
6. Nextcloud closes and the upload starts
7. Re-open Nextcloud and notice, that the filename is now something like ```101663``` instead of ```1.1``` in the example.

### Environment data
On the newer phone, there is the problem.
Android version: 7.0
Device model:  HUAWEI P8 LITE 2017
Filemanager: "Dateien Version 7.2.3.319_Local"
Stock or customized system: Stock
Nextcloud app version: 3.1.0
Nextcloud server version: 13.0.2

Older phone (no problem):
Android version: 6.0
Device model: HUAWEI P8 LITE
Filemanager: "Dateien Version 7.1.1.301_L"
Stock
Nextcloud app version 3.1.0
Nextcloud server version: 13.0.2

#### Web server error log
```
Insert your webserver log here
(no relevant messages there)
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here (I cannot find it)
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
Hi @wikinaut, did you test it with a different file manager like Amaze?

I tested it on my OP3T Android 8 and it works just fine, file name is preserved.

**Comment by AndyScherzinger** [comment]
Hah! @wikinaut @tobiasKaminsky I can reproduce this using the shipped file manager of the One Plus 3T, then I also just get renamed, simply numbered files without a file extension.

**Comment by Wikinaut** [comment]
@AndyScherzinger No, I always use the standard (built-in) Filemanager.

**Comment by AndyScherzinger** [comment]
Okay, well I can reproduce it and thus @tobiasKaminsky @mario or @ardevd can probably too :)

**Comment by Wikinaut** [comment]
Really? It's in since a while, a regression then.

**Comment by Wikinaut** [comment]
About since 6 months or so.

**Comment by AndyScherzinger** [comment]
Definitely nothing to do with old oC clients I guess it is related to different types of intent/uri handlings.

**Comment by ardevd** [comment]
@AndyScherzinger Can we please clean up the issue title a bit? It's hurting my brain. The details are provided in the actual issue description. :)

**Comment by ardevd** [comment]
Tried to reproduce this on an emulator running Android 8.1. 

- Place a a file named 1.1 on the internal storage.
- Share it to the NextCloud app through the Android downloads app. 
- Verify that it shows up as "1.1" in the NextCloud server UI and app.

So are we saying the issue is related to different Android versions or different file managers?

**Comment by AndyScherzinger** [comment]
Changes the title :) 

> related to different Android versions or different file managers

Yes that is basically the issue :/

**Comment by ardevd** [comment]
@AndyScherzinger So give me a file manager I can reproduce the issue with?

**Comment by AndyScherzinger** [comment]
@ardevd tricky to do: Amaze file manager - works; OnePlus 3T file manager - doesn't work.

**Comment by AndyScherzinger** [comment]
@ardevd yeah, I know. I could only reproduce it with my phone's file manager. @tobiasKaminsky can you reproduce this with your OP3 running LineageOS?

**Comment by Byggvir** [comment]
I tried to upload a MS Word docx document. On the server the filename was only a n4 digit number. After renameing the files on an Linux desktop the file was readable.

**Comment by weleoka** [comment]
This still happens on Android 9 with filenames turning into a 6 digit number. The suffix (file type) remains correct however. I use [com.simplemobiletools.filemanager.pro](https://github.com/SimpleMobileTools/Simple-File-Manager/blob/master/app/build.gradle) (or free version) on Android 9. 

This same file name issue exists with webdav syncing from, for example, Joplin Note Taking App (I think, but have yet to confirm).

**Comment by Wikinaut** [comment]
I still see the annoying problem on my devices (Android 10) now and then. For at least one file this is strictly reproducible.

**Comment by AndyScherzinger** [comment]
cc @tobiasKaminsky 

@Wikinaut what is "special" about the file where this keeps happening for you?

@weleoka in case this also happens for Joplin (completely different/standalone implementation) it rather points to a server side issue.

**Comment by weleoka** [comment]
@AndyScherzinger 

> @weleoka in case this also happens for Joplin (completely different/standalone implementation) it rather points to a server side issue.

I have now [confirmed](https://joplinapp.org/faq/#is-it-possible-to-use-real-file-and-folder-names-in-the-sync-target) (and [confirmed2](https://github.com/laurent22/joplin/issues/1770)) that Joplin does this deliberately. So disregard my paragraph about WebDAV and Joplin.

**Comment by joshtrichards** [comment]
Is anyone on this thread still experiencing this? This is a very old issue that hasn't seen any traffic in awhile. I also haven't seen evidence of other similar reports lately. Perhaps this is solved?

**Comment by Wikinaut** [comment]
Not valid any longer → I close the issue.
