### ISSUE TITLE
Login screen shows every 5 seconds

### ISSUE THREAD

**Issue by jj-uk** [nextcloud/android#2553]
### Actual behaviour
The login screen shows ->  login -> files are shown then 5 secs later login screen shows again.
Pressing the back button shows files again. Then 5 seconds later login screen. This pattern repeats forever even when credentials are correct. 
Note if you can navigate to setting page it doesn't show login screen again until you browse files again.
### Expected behaviour
- Tell us what should happen
 Login only once.
### Steps to reproduce
1. As above. Just open app, enter pin.
2. 
3. 

### Environment data
Android version: 5.1.1

Device model: 
Samsung j3
Stock or customized system:
Stock
Nextcloud app version:
3.1.0
Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by Thorketil** [comment]
I have the same problem. I can't access to my app on Android anymore.

**Comment by jj-uk** [comment]
The current version is 13 and its still broken.

**Comment by AndyScherzinger** [comment]
Thanks in advance for your efforts @jj-uk ❤️

**Comment by derekblankmccoy** [comment]
I'm experiencing this issue as well. Very strange as I have two identical Galaxy Tab A's both running the same version of Android (8.1), both freshly wiped and NC app installed. One logs in fine, the other does the login loop.
For what it's worth, I think the old login method was better.

**Comment by tobiasKaminsky** [comment]
This is indeed very very strange.


> For what it's worth, I think the old login method was better.

The old login method uses the password as typed in, which does not work with new apis like comment/favorite/search.
Also the new login flow supports 2fa out ouf the box (as it is using the same login as on server).

The login page is shown if a http request to the server is failing with "auth denied", so this is after a first successful login, or?

- do you use on both the same user account?
- an you provide us additional infos via logcat on the failing device? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

**Comment by tobiasKaminsky** [comment]
Do you have a SdCard in one or both devices?

**Comment by derekblankmccoy** [comment]
No, both are SD free.

**Comment by Slevin7** [comment]
I have the same problem, with android 9 on my pixel 2
allways asking for my password and on the in the logfiles it sayes 

Login failed: 'slevin7' (Remote IP: 'remote ip')
--

**Comment by tobiasKaminsky** [comment]
@Slevin7 then this seems to be indeed a login problem. Do you have any special setup? LDAP? Totally strange characters in password? 

(we had also login loops which occur due to problems with Account Manager of Android, where the login was successful).

**Comment by Slevin7** [comment]
Hello, I feel a bit ashamed I only looked for problems on github instead of completely reinstalling the app.
At least I can log in again.
Sorry that I did not think so right away.

**Comment by derekblankmccoy** [comment]
I think this happens when the app is upgraded from a version using the old login method over to one using the new one. Is it possible it's looking at the old app token which wasn't 'granted access'? This would explain why changing case on the username works, its generating a new app token. Dunno, just a thought.

**Comment by Slevin7** [comment]
This could be the case.
I have this app installed since nextcloud 10.
To be honest I don't use the Android app that often.
After a time I see this behavior an search if this was known.

Greetings


derekblankmccoy <notifications@github.com> schrieb am Do., 21. Feb. 2019,
19:09:

**Comment by derekblankmccoy** [comment]
This shouldn't have been closed.
