### ISSUE TITLE
Autoupload is failing - UPLOAD_FAILED and result:FOLDER_ERROR 

### ISSUE THREAD

**Issue by miodzicho** [nextcloud/android#2555]
### Actual behaviour
Images are not being uploaded into nwe 2018/05 subfolder (error message server not found, folder error).

### Expected behaviour
Images should be uploaded into corresponding subfolder 
 
### Steps to reproduce
1. take a photo
2.  wait for sync with server
3. check on web if image has been uploaded

### Environment data
Android version: 8.1.0

Device model: 
Oneplus 5T
Stock or customized system:
stock rooted
Nextcloud app version:
3.1.0
Nextcloud server version:
13
#### Nextcloud log (data/nextcloud.log)
2018/05/07 06:41:01
UploadFileOperation : Checking name collision in server

2018/05/07 06:41:01
UploadsStorageManager : Updating /storage/emulated/0/DCIM/Camera/IMG_20180506_115558.jpg with status=UPLOAD_IN_PROGRESS

2018/05/07 06:41:01
UploadsStorageManager : updateUpload returns with: 1 for file: /storage/emulated/0/DCIM/Camera/IMG_20180506_115558.jpg

2018/05/07 06:41:01
UploadsStorageManager : notifyObserversNow

2018/05/07 06:41:01
OwnCloudClient #1 : REQUEST PUT /nextcloud/remote.php/webdav/SofortUpload/DCIM/2018/05/IMG_20180506_115558.jpg-chunking-199888553-3-0

2018/05/07 06:41:01
ChunkedUploadRemoteFileOperation : Upload of /storage/emulated/0/DCIM/Camera/IMG_20180506_115558.jpg to /SofortUpload/DCIM/2018/05/IMG_20180506_115558.jpg, chunk index 0, count 3, HTTP result status 404

2018/05/07 06:41:01
UploadFileOperation : Upload of /storage/emulated/0/DCIM/Camera/IMG_20180506_115558.jpg to /SofortUpload/DCIM/2018/05/IMG_20180506_115558.jpg: Local file does not exist

2018/05/07 06:41:01
UploadsStorageManager : updateDatabaseUploadResult uploadResult: com.owncloud.android.lib.common.operations.RemoteOperationResult@d50598b upload: com.owncloud.android.operations.UploadFileOperation@300aa68

2018/05/07 06:41:01
UploadsStorageManager : Updating /storage/emulated/0/DCIM/Camera/IMG_20180506_115558.jpg with status:UPLOAD_FAILED and result:FOLDER_ERROR (old:/storage/emulated/0/DCIM/Camera/IMG_20180506_115558.jpg status:UPLOAD_IN_PROGRESS result:-1)

2018/05/07 06:41:01
UploadsStorageManager : Updating /storage/emulated/0/DCIM/Camera/IMG_20180506_115558.jpg with status=UPLOAD_FAILED

2018/05/07 06:41:01
UploadsStorageManager : updateUpload returns with: 1 for file: /storage/emulated/0/DCIM/Camera/IMG_20180506_115558.jpg

2018/05/07 06:41:01
UploadsStorageManager : notifyObserversNow

2018/05/07 06:41:01
FileUploader : NotifyUploadResult with resultCode: FILE_NOT_FOUND

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
> FILE_NOT_FOUND

Was the file deleted meanwhile?

**Comment by miodzicho** [comment]
Some of them, yes. But not all. What is maybe important, all new photos, I took today, are uploaded just fine. It seems it stuck on some of them.

**Comment by miodzicho** [comment]
I took over 100 photos today, and they are not being uploaded....will attach log soon.

**Comment by miodzicho** [comment]
log attached....
[nextcloud_android.log](https://github.com/nextcloud/android/files/1994008/nextcloud_android.log)

**Comment by miodzicho** [comment]
I'm not even checking it, I have nearly 200 images not being uploaded now. All stuck in queue. 
And I see no solution.

**Comment by Byggvir** [comment]
Automatic upload works in 3.2.0 RC2.
