### ISSUE TITLE
ActivitiesActivity crash when no network

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#2556]
### Actual behaviour
- App crashes

### Expected behaviour
- Show some meaningful error
 
### Steps to reproduce
1. disable internet
2. open up Activities
3. wait until timeout (30s)

**Comment by ardevd** [comment]
I'll look into it right away!

**Comment by ardevd** [comment]
@tobiasKaminsky I'm not able to reproduce this. 

1. Disable network data connection
2. Open up activities
3. Wait until timeout (30)s
4. A toast is displayed, showing the appropriate Exception message.

Are you seeing something else?

**Comment by tobiasKaminsky** [comment]
Thanks for trying to verify this so quickly :+1: 

I tried it and indeed it is now working, maybe it was another crash, because of some process running in background.

Sorry for the noise :-)
