### ISSUE TITLE
Trashbin view

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#2557]
![2018-05-07-154129](https://user-images.githubusercontent.com/5836855/39704916-2897e5a2-520d-11e8-9e25-9b8fbacd07f8.png)

@nextcloud/designers I am currently implementing trashbin view into android.
Web UI has only "delete" on overflow menu (three dots), which is a bit uncommon for me, if there is only one menu item. Is it okay to have the delete button directly next to restore?

To save some space I want to put the "deletion time" beneath the file name:
.Contacts-Backup
deleted 25 days ago

(file size will be removed).

What do you think?
@AndyScherzinger also for you :-)

**Comment by stefan-niedermann** [comment]
But if delete is displayed directly, then there are a destructivr and a constructive action directly next to each other - users might want to restore a file but accidently hit the delete button...

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky putting the deletion time in there, sure like:

As for the actions: putting the delete in the per item overflow menu seems fine to me since this action is probably not used that often. What should imho be added is a "Empty recycle bin" action item at the top above the list since users probably either 
* need to restore a file or 
* purge the recycle bin

**Comment by rullzer** [comment]
> @AndyScherzinger I am not sure if this exists. @rullzer is there a possibility to purge the entire trash bin?

Yes DELETE `<server>/remote.php/dav/trashbin/<USERID>/trash` and it will empty the trashbin

**Comment by rullzer** [comment]
@tobiasKaminsky what probably would begood to somehow display is the original location of the file.

As if you have two folders 'customers' or whatever it might be godo to know where they came from.

**Comment by jancborchardt** [comment]
> Web UI has only "delete" on overflow menu (three dots), which is a bit uncommon for me, if there is only one menu item. Is it okay to have the delete button directly next to restore?

I'm a bit worried about misclicks here. The restore action and absolutely destructive action are right next to each other, as said by others too. Undo for deletion should be there either way.

The "Remove all deleted files" function should also be in an overflow menu on the top, not directly visible.

And would be nice if there's a search function in this view too in case you want to restore something specific.

Just one more thing: Make sure the text of the main content and the header line up (are aligned left along the same horizontal line).

> To save some space I want to put the "deletion time" beneath the file name

Yep, just wanted to mention. :) Good call.

**Comment by tobiasKaminsky** [comment]
Current status:
![2018-05-09-090653](https://user-images.githubusercontent.com/5836855/39800521-5e298098-5368-11e8-8d22-60be13aac01b.png) ![2018-05-09-090657](https://user-images.githubusercontent.com/5836855/39800522-5e4a1998-5368-11e8-926b-ab0f42ee8210.png)

Todo, but in next PRs:
- undo -> should be discussed separately, also for other actions
- search function (well, will be a filter as it will only shrink the view to desired files)

**Comment by jancborchardt** [comment]
And as mentioned above:

> Just one more thing: Make sure the text of the main content and the header line up (are aligned left along the same horizontal line).


Also, is there a specific reason the 3-dot-menu of the content rows and the header doesn't align? Cause they should have the same tappable area.

**Comment by AndyScherzinger** [comment]
> no, just personal incompetence, which was fixed by @AndyScherzinger ;-)

my pleasure :grin:

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky anything missing to open a PR and start the reviews?

**Comment by tobiasKaminsky** [comment]
Some polishing, will be by end of the week.
