### ISSUE TITLE
Autoupload doesn't recognise WiFi

### ISSUE THREAD

**Issue by RufioHugo** [nextcloud/android#2558]
### Actual behaviour
Changed for a reason from "only WiFi" to mobile data, then used BT for a short period - after switching back to "only WiFi" (same as before) it no longer uploads anything (Statusmessage: Waiting for WiFi - manual retry doesn't work either) if deactivating "only WiFi" again and use mobile data new files are uploaded but no "old" ones.

### Expected behaviour
Upload as selected ...
 
### Steps to reproduce
Can't list, there seems to be no way to get my phones/nextcloud working again with WiFi & reproduce it, sorry. (Cleared cache/userdata, created new account, even reinstalled App)

### Environment data
Android version:
7.1.2 & 7.1.1
Device model: 
BQ M5 / U
Stock or customized system:
7.1.2 = lineageOS 14.1 from 05/05
7.1.1 = stock
Nextcloud app version:
3.1.0
Nextcloud server version:
13 (unable to update hangs on step 4)
#### Web server error log
-none available-
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
-none available-Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by nonplusnl** [comment]
I have this issue as well. See also #2632 (which apparently was solved for original contributor but not for me). Uploads remain stuck "Waiting for wifi". Nokia 7 plus with Android 8.1

**Comment by nonplusnl** [comment]
Isolated the issue on my phone: the VPN. See #2839
