### ISSUE TITLE
Unable to move multiple files

### ISSUE THREAD

**Issue by pludi** [nextcloud/android#256]
### Actual behaviour
When selecting multiple files, the option to move them is removed, and only copy is available

### Expected behaviour
Ability to move multiple files.
 
### Steps to reproduce
1. Select a single file
2. Open the menu
3. Menu contains actions for Rename, Move, Copy, …
4. Select additional file(s)
5. Open menu again
6. Only options left are Copy, Remove, Available offline

### Environment data
Android version: 5.1.1

Device model: Zuk Z1

Stock or customized system: Stock

Nextcloud app version: 1.2.0

Nextcloud server version: 10.0 stable

**Comment by AndyScherzinger** [comment]
Hi @pludi,

it is still there, but when you have selected more then one file it is shown directly in the bar:
![device-2016-09-12-100007](https://cloud.githubusercontent.com/assets/1315170/18428738/f5f4e892-78cf-11e6-99cf-1f5a8646125c.png)

@nextcloud/designers @tobiasKaminsky - imho no bug but a UX issue regarding discoverability as for 1-selected file the menu item is part of the overflow menu and for multiple-selected files is is shown in the bar.

Let's discuss a solution, I label it as a starter issue and we can fix this in the conference workshop. Sounds good?

**Comment by AndyScherzinger** [comment]
New issue created for the UX discussion: #257
