### ISSUE TITLE
[F-Droid Dev version] App crashes on Auto upload option openning

### ISSUE THREAD

**Issue by SkyWheel** [nextcloud/android#2567]
Similar behavior on 2 different devices:
Xiaomi Redmi Note 3 with rooted LineageOS 14.1 latest
Google Pixel XL with non-rooted latest 8.1
Nextcloud Dev F-Droid 20180427 version.

**Comment by tobiasKaminsky** [comment]
Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

**Comment by SkyWheel** [comment]
I cannot reproduce the bug anymore , so I'm closing the issue. Thank yoy
