### ISSUE TITLE
Move action hard to discover - difference between single/multi selection

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#257]
![device-2016-09-12-100007](https://cloud.githubusercontent.com/assets/1315170/18428796/5f9abe16-78d0-11e6-8410-a990e258871d.png)

As shown in the screenshot in move action is part of the action bar when selecting multiple files, for a single file selection it is part of the overflow menu.

cc @tobiasKaminsky @nextcloud/designers

**Comment by tobiasKaminsky** [comment]
Both should then be in overflow menu, I think

**Comment by AndyScherzinger** [comment]
What do you mean by both?

* all actions should be in the overflow menu?
* put move in overflow (which would actually lead to copy being displayed...)

So I would probably say put everything into the overflow menu

**Comment by tobiasKaminsky** [comment]
Yeah, I meant, that in both cases it should be in the overflow menu.
Sorry for the confusion :/

**Comment by AndyScherzinger** [comment]
Okay, so basically moving all menu items to the overflow menu. Agreed?
