### ISSUE TITLE
crash on file delete

### ISSUE THREAD

**Issue by kollix** [nextcloud/android#2574]
[nc-crash.txt](https://github.com/nextcloud/android/files/1997835/nc-crash.txt)
### Actual behaviour
- I rebooted the device and start Nextcloud client
- I select one image via longtap
- I select "Delete" from the menu to delete this image file
- Nextcloud crashes

### Expected behaviour
- no crash, file deleted
 
### Steps to reproduce
see above

### Environment data
Android version:4.4.2

Device model: Samsung Galaxy Note II  (GT-N7100)

Stock or customized system: stock

Nextcloud app version: 3.1.0 (from F-Droid)

Nextcloud server version: owncloud-8.2.11

### Logs
attached

**Comment by ardevd** [comment]
@kollix Is the file actually deleted?

The stack trace you posted indicates a OutOfMemoryError exception which is odd.

**Comment by kollix** [comment]
On Montag, 14. Mai 2018 08:28:21 CEST ardevd wrote:
> @kollix Is the file actually deleted?

no
 
> The stack trace you posted indicates a OutOfMemoryError exception which is odd.

Yes, I've seen that, so my first guess was really an OOM situation.
First try was to close all apps possible - no luck.
Therefore: reboot, only start NC - no luck.

I don't understand this, since it's just trying to allocate 3MB

still: why does it
com.owncloud.android.datamodel.ThumbnailsCacheManager.addThumbnailToCache(ThumbnailsCacheManager.java:174)
when I DELETE the file ???

-- 
Best regards/Schöne Grüße

Martin

()  ascii ribbon campaign - against html e-mail 
/\                        - against proprietary attachments

**Comment by tobiasKaminsky** [comment]
> still: why does it
com.owncloud.android.datamodel.ThumbnailsCacheManager.addThumbnailToCache(ThumbnailsCacheManager.java:174)
when I DELETE the file ???

For non-downloaded images we show a resized preview, which will be fetched from server.
However if you already have an image downloaded, delete it and immediately afterwards want to see the resized image, the device would have to download it.
That is the reason why we create the resized image on deletion.

After all this should not crash and should just create a resized image.

@kollix how big is the image in question?

**Comment by kollix** [comment]
On Mittwoch, 16. Mai 2018 11:41:54 CEST Tobias Kaminsky wrote:
> > still: why does it
> com.owncloud.android.datamodel.ThumbnailsCacheManager.addThumbnailToCache(ThumbnailsCacheManager.java:174)
> when I DELETE the file ???
> 
> For non-downloaded images we show a resized preview, which will be fetched from server.
> However if you already have an image downloaded, delete it and immediately afterwards want to see the resized image, the device would have to download it.
> That is the reason why we create the resized image on deletion.
> 
> After all this should not crash and should just create a resized image.
> 
> @kollix how big is the image in question?

I just tested with a 2MB file and got a crash with the log:

D/dalvikvm(21453): GC_FOR_ALLOC freed 187K, 19% free 18967K/23228K, paused 62ms, total 62ms
I/dalvikvm-heap(21453): Grow heap (frag case) to 49.963MB for 31961104-byte allocation
D/KeyguardUpdateMonitor( 2627): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 2627): handleKeyguardVisibilityChanged(1)
I/SurfaceFlinger( 1954): id=1025 Removed GileDisplay (11/17)
I/SurfaceFlinger( 1954): id=1025 Removed GileDisplay (-2/17)
D/KeyguardUpdateMonitor( 2627): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 2627): handleKeyguardVisibilityChanged(1)
D/dalvikvm(21453): GC_FOR_ALLOC freed 18K, 8% free 50160K/54444K, paused 40ms, total 40ms
D/dalvikvm(21453): GC_CONCURRENT freed 1564K, 11% free 48597K/54444K, paused 8ms+4ms, total 60ms
D/KeyguardUpdateMonitor( 2627): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 2627): handleKeyguardVisibilityChanged(1)
D/dalvikvm(21453): GC_FOR_ALLOC freed 21K, 11% free 48581K/54444K, paused 33ms, total 33ms
I/dalvikvm-heap(21453): Grow heap (frag case) to 56.738MB for 8739856-byte allocation
I/dalvikvm-heap(21453): Clamp target GC heap from 64.737MB to 64.000MB
D/dalvikvm(21453): GC_FOR_ALLOC freed <1K, 10% free 57116K/62980K, paused 35ms, total 35ms
I/dalvikvm-heap(21453): Clamp target GC heap from 64.738MB to 64.000MB
D/dalvikvm(21453): GC_CONCURRENT freed <1K, 10% free 57116K/62980K, paused 3ms+10ms, total 63ms
I/dalvikvm-heap(21453): Clamp target GC heap from 64.738MB to 64.000MB
D/dalvikvm(21453): GC_FOR_ALLOC freed 1K, 10% free 57116K/62980K, paused 35ms, total 36ms
I/dalvikvm-heap(21453): Forcing collection of SoftReferences for 3686416-byte allocation
I/dalvikvm-heap(21453): Clamp target GC heap from 64.728MB to 64.000MB
D/dalvikvm(21453): GC_BEFORE_OOM freed 74K, 10% free 57041K/62980K, paused 43ms, total 43ms
E/dalvikvm-heap(21453): Out of memory on a 3686416-byte allocation.
I/dalvikvm(21453): "Operations thread" prio=5 tid=23 RUNNABLE
I/dalvikvm(21453):   | group="main" sCount=0 dsCount=0 obj=0x42753f48 self=0x5c92a670
I/dalvikvm(21453):   | sysTid=387 nice=10 sched=0/0 cgrp=apps/bg_non_interactive handle=1649462384
I/dalvikvm(21453):   | state=R schedstat=( 1444040562 301242947 1023 ) utm=133 stm=10 core=0
I/dalvikvm(21453):   at android.graphics.Bitmap.nativeCreate(Native Method)
I/dalvikvm(21453):   at android.graphics.Bitmap.createBitmap(Bitmap.java:928)
I/dalvikvm(21453):   at android.graphics.Bitmap.createBitmap(Bitmap.java:901)
I/dalvikvm(21453):   at android.graphics.Bitmap.createBitmap(Bitmap.java:822)
I/dalvikvm(21453):   at android.graphics.Bitmap.createBitmap(Bitmap.java:747)
I/dalvikvm(21453):   at android.media.ThumbnailUtils.transform(ThumbnailUtils.java:449)
I/dalvikvm(21453):   at android.media.ThumbnailUtils.extractThumbnail(ThumbnailUtils.java:234)
I/dalvikvm(21453):   at android.media.ThumbnailUtils.extractThumbnail(ThumbnailUtils.java:209)
I/dalvikvm(21453):   at com.owncloud.android.datamodel.ThumbnailsCacheManager.addThumbnailToCache(ThumbnailsCacheManager.java:174)
I/dalvikvm(21453):   at com.owncloud.android.datamodel.ThumbnailsCacheManager.generateResizedImage(ThumbnailsCacheManager.java:1156)
I/dalvikvm(21453):   at com.owncloud.android.operations.RemoveFileOperation.run(RemoveFileOperation.java:90)
I/dalvikvm(21453):   at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:145)
I/dalvikvm(21453):   at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:149)
I/dalvikvm(21453):   at com.owncloud.android.operations.common.SyncOperation.execute(SyncOperation.java:93)
I/dalvikvm(21453):   at com.owncloud.android.services.OperationsService$ServiceHandler.nextOperation(OperationsService.java:473)
I/dalvikvm(21453):   at com.owncloud.android.services.OperationsService$ServiceHandler.handleMessage(OperationsService.java:413)
I/dalvikvm(21453):   at android.os.Handler.dispatchMessage(Handler.java:102)
I/dalvikvm(21453):   at android.os.Looper.loop(Looper.java:146)
I/dalvikvm(21453):   at android.os.HandlerThread.run(HandlerThread.java:61)
I/dalvikvm(21453): 
W/dalvikvm(21453): threadid=23: thread exiting with uncaught exception (group=0x41bdcc08)
E/AndroidRuntime(21453): FATAL EXCEPTION: Operations thread
E/AndroidRuntime(21453): Process: com.nextcloud.client, PID: 21453
E/AndroidRuntime(21453): java.lang.OutOfMemoryError
E/AndroidRuntime(21453):        at android.graphics.Bitmap.nativeCreate(Native Method)
E/AndroidRuntime(21453):        at android.graphics.Bitmap.createBitmap(Bitmap.java:928)
E/AndroidRuntime(21453):        at android.graphics.Bitmap.createBitmap(Bitmap.java:901)
E/AndroidRuntime(21453):        at android.graphics.Bitmap.createBitmap(Bitmap.java:822)
E/AndroidRuntime(21453):        at android.graphics.Bitmap.createBitmap(Bitmap.java:747)
E/AndroidRuntime(21453):        at android.media.ThumbnailUtils.transform(ThumbnailUtils.java:449)
E/AndroidRuntime(21453):        at android.media.ThumbnailUtils.extractThumbnail(ThumbnailUtils.java:234)
E/AndroidRuntime(21453):        at android.media.ThumbnailUtils.extractThumbnail(ThumbnailUtils.java:209)
E/AndroidRuntime(21453):        at com.owncloud.android.datamodel.ThumbnailsCacheManager.addThumbnailToCache(ThumbnailsCacheManager.java:174)
E/AndroidRuntime(21453):        at com.owncloud.android.datamodel.ThumbnailsCacheManager.generateResizedImage(ThumbnailsCacheManager.java:1156)
E/AndroidRuntime(21453):        at com.owncloud.android.operations.RemoveFileOperation.run(RemoveFileOperation.java:90)
E/AndroidRuntime(21453):        at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:145)
E/AndroidRuntime(21453):        at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:149)
E/AndroidRuntime(21453):        at com.owncloud.android.operations.common.SyncOperation.execute(SyncOperation.java:93)
E/AndroidRuntime(21453):        at com.owncloud.android.services.OperationsService$ServiceHandler.nextOperation(OperationsService.java:473)
E/AndroidRuntime(21453):        at com.owncloud.android.services.OperationsService$ServiceHandler.handleMessage(OperationsService.java:413)
E/AndroidRuntime(21453):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(21453):        at android.os.Looper.loop(Looper.java:146)
E/AndroidRuntime(21453):        at android.os.HandlerThread.run(HandlerThread.java:61)
W/ActivityManager( 2438):   Force finishing activity com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity
V/FileDisplayActivity(21453): onPause() start
D/FileDisplayActivity(21453): onPause() ending
V/FileDisplayActivity(21453): onPause() end

-- 
Best regards/Schöne Grüße

Martin
A: Because it breaks the logical sequence of discussion
Q: Why is top posting bad?

()  ascii ribbon campaign - against html e-mail 
/\                        - against proprietary attachments

Geschenkideen, Accessoires, Seifen, Kulinarisches: www.lillehus.at
