### ISSUE TITLE
Enable "Upload option" when uploading files using share function outside the app

### ISSUE THREAD

**Issue by vitaliis** [nextcloud/android#2575]
### Actual behaviour
- Shows regular dialog to select folder where to upload the file that is being shared. It just assumes the default "Upload option" as "Keep file in source folder".

### Expected behaviour
- "Upload option" is showed, allowing user to select one of the following when uploading using "share" functionality:
** Move file to nextcloud folder
** Keep file in source folder
** Delete file from source folder
 
### Steps to reproduce
1. For example open "Galery" with pictures or file browser.
2. Select file/image and click "share icon".
3. In the opened dialog "Share via" select "Nextcloud".
4. The view opened lets you select the folder where to upload the file, but doesn't allow you to select an appropriate "Upload option" (one of: Move file to nextcloud folder, Keep file in source folder, Delete file from source folder).

### Environment data
Android version: 7.1.2

Device model: ZTE A2017...

Stock or customized system: LineageOS

Nextcloud app version: 3.1.0

**Comment by tobiasKaminsky** [comment]
This is not really possible, as we only get a copy/read only file when sharing the file internally, so this is only possible if you do it the other way around.

**Comment by vitaliis** [comment]
Hello @tobiasKaminsky ,

thank you for the reply. Maybe there is other possibility to do this. Please advise.
It is possible to select a list of files that are shared (uploaded) then.
Depending on the type of the given values we might do some operations on them. Of course if it is a sequence of bytes there is not much info we can derive from it. But if it is of type `File` or similar, then it should be possible.
Maybe it is possible to derive the file path for each file and perform operations on them?

P.S. I am a Scala developer myself, so we can talk in more depth than an average user.

**Comment by tobiasKaminsky** [comment]
There are other issues, were user report that these options sometimes to do not work, when the files are on sdcard.
So I would not try to complicate this, but instead assume that "share within android" is read-only and for the other way around we should prior check if it is possible to move/delete the file and only then show the option.
