### ISSUE TITLE
case-insensitive filename bug?

### ISSUE THREAD

**Issue by cbrace** [nextcloud/android#2576]
I am seeing what appears to be a bug in the Android client related to filenames. Here is how I reproduce it:

1. Create new folder on my Linux desktop running Mint.
2. Add two files: somefile.pdf and SomeFile.pdf.
3. Open this folder in my NextCloud android client.
4. Tap on of one these to open it. The client downloads and opens it a PDF viewer.
5. Tap on the second file. The client reports a version collision. If I select server version I end up with two versions of the first file, even though the filenames are different. This change is propagated back to the server and the the desktop client.

Somewhere in the app there seems to some filename comparison code which is case-insensitive.

Nextcloud android client v3.1.0
Nextcloud desktop client v2.3.3.
Nextcloud server: v13.0.1

**Comment by cbrace** [comment]
This bug has been fixed in v3.3.0. Thanks to whoever took care of it.

**Comment by AndyScherzinger** [comment]
Thanks for the feedback @cbrace. I guess @tobiasKaminsky @mario @ardevd took care of it - sicne I can't remember me doing a fix for it.
Happy to read the matter got resolved!
