### ISSUE TITLE
Show move/copy context in toolbar title

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#258]
![device-2016-09-12-101119](https://cloud.githubusercontent.com/assets/1315170/18429040/a04b3156-78d1-11e6-8c1c-e3fd67e8f1be.png)

See screenshot above, the "folder chooser" for move file and copy file which is launched after single/multi selection of a file from the main file list view always says "Nextcloud" so you don't have a detailed context. So my proposal is to show "Copy to..." and "Move to..." as the title to set the context right. Else the user has to remember the action that has been chosen before.

As for testing we need to make sure that all (other) chooser screens like when sharing with Nextcloud isn't affected by this.

cc @tobiasKaminsky @nextcloud/designers 

PR: https://github.com/nextcloud/android/pull/265

**Comment by tobiasKaminsky** [comment]
:
