### ISSUE TITLE
Replace legacy and stale custom ImageView and ViewPager classes with a better alternatives

### ISSUE THREAD

**Issue by ardevd** [nextcloud/android#2583]
We currently include a `com.ortiz.touch.ExtendedViewPager` class that provides zooming/scrolling functionality for preview images. It's only used in the `PreviewImageActivity`.

The code is seemingly not maintained anymore and the source is pretty clunky. 

As @AndyScherzinger recommended, let's look for a replacement in form of a third party library that will remove the need to maintain old code nobody knows how to work with and perhaps give a better user experience as well.

I'll be happy to look into this. @AndyScherzinger proposed [PhotoView](https://github.com/chrisbanes/PhotoView) which looks good to me. I'll see if I can dig up other alternatives too though and play around with them to see what works.

**Comment by AndyScherzinger** [comment]
@mario @tobiasKaminsky fine with you? (I guess so but still asking for your feedback) :smiley:

**Comment by mario** [comment]
Yes

**Comment by tobiasKaminsky** [comment]
Fine with it and thanks for taking care of it, @ardevd :+1:

**Comment by AndyScherzinger** [comment]
.....aaaaaand merged to master! Again Kudos to @ardevd to doing such a great job pushing the app forward! :heart:
