### ISSUE TITLE
Set automatically the ability to select multiples images by default

### ISSUE THREAD

**Issue by c0fe** [nextcloud/android#2584]
When you are uploading images via the Nextcloud Android app you have to press with your finger on the screen and hold for a few seconds before being able to select multiple files to upload. If you do not do this then you will only upload one file that you initially selected.

My proposal is to set it to allow multiple files to be selected by default with the top option being upload.

**Comment by tobiasKaminsky** [comment]
At least from my experience long press for multiselect items is a common android pattern, so I would not change this.

What about you? @mario @AndyScherzinger @ardevd

**Comment by AndyScherzinger** [comment]
I agree with you @tobiasKaminsky regarding the long press to initiate multi select. Other pattern thought would be that you can directly multi-select by clicking on the item icon on the left (like in gmail, file browsers or Nextcloud Talk), while that would need some coding work

**Comment by c0fe** [comment]
@tobiasKaminsky my experience is primarily with Dropbox, by default they allow for multiple files to be selected.

My argument for this is that long press is not intuitive, there is nothing there to let the user know immediately that they can select multiple files if they press their finger for a few seconds longer than they normally would. Of course they can look this up but this defeats the purpose of intuitiveness.

With automatic default multiple files, a user can select one file and hit the "open" or "upload" button or they can select multiple files and then hit the "open" or "upload" button. This approach is more intuitive at least in my opinion.

**Comment by joshtrichards** [comment]
> With automatic default multiple files, a user can select one file and hit the "open" or "upload" button or they can select multiple files and then hit the "open" or "upload" button. This approach is more intuitive at least in my opinion as the upload option is already there and there does not need to be some known knowledge to activate the a particular feature.

This is basically how the *Upload files* now functions today so I'm going to close this enhancement discussion out.
