### ISSUE TITLE
user login

### ISSUE THREAD

**Issue by bobblkabb** [nextcloud/android#259]
### Actual behaviour

Couldn't login ordinary user; admin user works
### Expected behaviour

Connect android client with nextcloud
### Steps to reproduce
1. add account
2. insert server and user information
3. connect
### Environment data

Android version: 6.0.1

Device model: Wileyfox Swift

Stock or customized system: customized

Nextcloud app version: 1.2

Nextcloud server version: 10.0
#### Web server error log

79.206.97.44 - chucky [13/Sep/2016:11:12:20 +0200] "HEAD /remote.php/webdav/ HTTP/1.1" 200 137 "-" "Mozilla/5.0 (Android) ownCloud-android/1.2.0"
79.206.97.44 - chucky [13/Sep/2016:11:12:21 +0200] "GET /index.php/ocs/cloud/user?format=json HTTP/1.1" 302 2834 "-" "Mozilla/5.0 (Android) ownCloud-android/1.2.0"
79.206.97.44 - chucky [13/Sep/2016:11:12:21 +0200] "GET /index.php/apps/files/ HTTP/1.1" 200 35959 "-" "Mozilla/5.0 (Android) ownCloud-android/1.2.0"
Insert your webserver log here
#### Nextcloud log (data/nextcloud.log)

```
Insert your Nextcloud log here
{"reqId":"V9fC4X8AAQEAAFwzLRsAAAAY","remoteAddr":"79.206.97.44","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(60): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/nextcloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/nextcl...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":188,\"User\":false}","level":0,"time":"2016-09-13T11:12:01+02:00","method":"HEAD","url":"\/remote.php\/webdav\/","user":"--"}
{"reqId":"V9fC9H8AAQEAAFzQ2fcAAAAD","remoteAddr":"79.206.97.44","app":"admin_audit","message":"Login attempt: \"chucky\"","level":1,"time":"2016-09-13T11:12:21+02:00","method":"HEAD","url":"\/remote.php\/webdav\/","user":"--"}
{"reqId":"V9fC9H8AAQEAAFzQ2fcAAAAD","remoteAddr":"79.206.97.44","app":"admin_audit","message":"Login successful: \"chucky\"","level":1,"time":"2016-09-13T11:12:21+02:00","method":"HEAD","url":"\/remote.php\/webdav\/","user":"chucky"}
{"reqId":"V9fC9X8AAQEAAFzQ2fgAAAAD","remoteAddr":"79.206.97.44","app":"admin_audit","message":"Login attempt: \"chucky\"","level":1,"time":"2016-09-13T11:12:21+02:00","method":"GET","url":"\/index.php\/ocs\/cloud\/user?format=json","user":"--"}
{"reqId":"V9fC9X8AAQEAAFzQ2fgAAAAD","remoteAddr":"79.206.97.44","app":"admin_audit","message":"Login successful: \"chucky\"","level":1,"time":"2016-09-13T11:12:21+02:00","method":"GET","url":"\/index.php\/ocs\/cloud\/user?format=json","user":"chucky"}
{"reqId":"V9fC9X8AAQEAAFzQ2fkAAAAD","remoteAddr":"79.206.97.44","app":"admin_audit","message":"Login attempt: \"chucky\"","level":1,"time":"2016-09-13T11:12:21+02:00","method":"GET","url":"\/index.php\/apps\/files\/","user":"--"}
{"reqId":"V9fC9X8AAQEAAFzQ2fkAAAAD","remoteAddr":"79.206.97.44","app":"admin_audit","message":"Login successful: \"chucky\"","level":1,"time":"2016-09-13T11:12:21+02:00","method":"GET","url":"\/index.php\/apps\/files\/","user":"chucky"}


After temporary enhancing the user with admin privileges it worked.
Btw. it didn't work with a Samsung Galaxy S6 either.
```

**Comment by AndyScherzinger** [comment]
@bobblkabb does the user and/or password have any special characters or something like that?

**Comment by bobblkabb** [comment]
@Andy
No, only small and capital letters. Same behaviour with a second user who's password is like 'obot9876'.

**Comment by AndyScherzinger** [comment]
@bobblkabb could you create a dummy user for testing which would also not work on your phone/tabler and send my the server addres + details? e.g. on https://help.nextcloud.com/ ?

**Comment by bobblkabb** [comment]
@AndyScherzinger 
How can I send private messages over here? Don't wanna expose (more or less) sensitive information..

**Comment by bobblkabb** [comment]
So!?..

**Comment by AndyScherzinger** [comment]
@bobblkabb you simply can't, again you would have to use the https://help.nextcloud.com/ and write a private message to @andy or write an email to google@nextcloud.com (mail android@nextcloud.com also works) and ask to have it forwarded to me (Andy).

**Comment by AndyScherzinger** [comment]
@bobblkabb I had a quick look and what actually happens is the following. The client requests the user Info via 
```
.../index.php/ocs/cloud/user?format=json
```
which (tested on Nextcloud 10) would lead to a json reply but for your instance actually serves the html-page

Do you do any redirecting on your webserver?

**Comment by bobblkabb** [comment]
Redirecting on the webserver itself? Like from http -> https?!..

**Comment by AndyScherzinger** [comment]
No it is all https, but the server redirects to the login page which is triggered by the server side, yes.

**Comment by Marlinc** [comment]
I'm currently also running into this issue on my Nextcloud instance. But on any user, admin user won't work either.

**Comment by bobblkabb** [comment]
How to find out?
Any .conf file?..

**Comment by Marlinc** [comment]
In my case its not the webserver that's redirecting but actually Nextcloud itself. I tried to debug some things to see where the redirect come from but I couldn't find it.

**Comment by AndyScherzinger** [comment]
@bobblkabb @Marlinc no idea to be honest since redirects are a server issue and I just "know" the Android client, so this would be best to be asked in the server-repo's tracker https://github.com/nextcloud/server/issues or probably even better, prefered in the forums https://help.nextcloud.com/

**Comment by Marlinc** [comment]
@AndyScherzinger well you're right. Its a server issue not a issue in the app. It might be good to create a issue at the server repo and then mention this issue @bobblkabb

**Comment by xaionaro** [comment]
I faced the same issue.

**Comment by xaionaro** [comment]
If somebody interested in, this workaround helped me:

```
--- a/lib/private/OCS/PrivateData.php
+++ b/lib/private/OCS/PrivateData.php
@@ -110,5 +110,30 @@ class PrivateData {
 
                return new Result(null, 100);
        }
+
+
+       public function getCurrentUser() {
+               $user = \OC_User::getUser();
+
+               $data = array(
+                       'id'    => $user,
+               );
+
+               // Getting email
+               $query = \OCP\DB::prepare('SELECT `configvalue`  FROM `*PREFIX*preferences` WHERE `userid` = ? AND `appid` = "settings" and `configkey` = "email" ');
+               $result = $query->execute(array($user));
+               if ($row = $result->fetchRow()) {
+                       $data['email'] = $row['configvalue'];
+               }
+
+               // Getting displayName
+               $query = \OCP\DB::prepare('SELECT `displayname`  FROM `*PREFIX*users` WHERE `uid` = ?');
+               $result = $query->execute(array($user));
+               if ($row = $result->fetchRow()) {
+                       $data['display-name'] = $row['displayname'];
+               }
+
+               return new Result($data);
+       }
 }
 
diff --git a/ocs/routes.php b/ocs/routes.php
index 3085cd9..f5fa515 100644
--- a/ocs/routes.php
+++ b/ocs/routes.php
@@ -75,3 +75,10 @@ API::register(
        'core',
        API::USER_AUTH
        );
+API::register(
+       'get',
+       '/cloud/user',
+       array('OC_OCS_Privatedata', 'getCurrentUser'),
+       'core',
+       API::USER_AUTH
+);
```

**Comment by AndyScherzinger** [comment]
Hi @bobblkabb can you test our latest beta client release (can be installed in parallel to the regular app):
https://f-droid.org/repository/browse/?fdfilter=com.nextcloud&fdid=com.nextcloud.android.beta

It contains a fix for a login issue we found, so this might solve your problem and will then also be integrated into the next regular/stable release 1.4.0

**Comment by tobiasKaminsky** [comment]
No response, therefore closing.
If you experience the error again, please reopen with additional infos.
