### ISSUE TITLE
Logged out on every phone reboot

### ISSUE THREAD

**Issue by samtygier** [nextcloud/android#2595]
### Actual behaviour
Every time I restart my phone I need to log in to Nextcloud again.

### Expected behaviour
Authentication should be remembered between reboots
 
### Steps to reproduce
1. Start Nextcloud, enter server, username and password
2. Reboot phone
3. Log in is forgotten, and I have to enter server, username and password again

### Environment data
Android version:
4.2.2

Device model: 
Fairphone 1

Stock or customized system:
Stock

Nextcloud app version:
3.1.0 from fdroid

Nextcloud server version:
13.0.2snap1

**Comment by samtygier** [comment]
Moving the app to internal storage seems to help.

Android Settings -> Apps -> Nextcloud -> Move to internal storage

**Comment by tobiasKaminsky** [comment]
We have introduced this in 3.0:
https://github.com/nextcloud/android/blob/391368947cbfc1195b1decfaaf3658d17d557c14/src/main/AndroidManifest.xml#L78

in our AndroidManifest.
According to androids doc this is even not needed (https://developer.android.com/guide/topics/data/install-location):
> If you do not declare this attribute, your application will be installed on the internal storage only and it cannot be moved to the external storage.

However there are some vendors that do not obey this and allow an app to be moved to external storage if this was not forbidden explicitly, but seeing this now is a new problem, but this needs to be solved by the vendor.

Did you upgraded or was 3.1 a fresh installation?

--> tl;dr: our app is not allowed on external storage, if this is however possible, it is a problem of mobile vendor.

**Comment by tobiasKaminsky** [comment]
Yeah, I guess this is the problem, as the "phone storage" is the same like a sdcard, but built-in…
