### ISSUE TITLE
Snackbar messages overlap the navigation bar when viewing images

### ISSUE THREAD

**Issue by ardevd** [nextcloud/android#2596]
### Actual behaviour
- When viewing a image in the app, the view overlaps the translucent navigation bar at the bottom meaning view elements aligned to the bottom overlap with the navigation bar. One example being the snackbar messages that can appear when viewing images. 

### Expected behaviour
- View elements should not overlap with the navigation bar.
 
### Steps to reproduce
1. Preview a .gif or .svg
2. Notice the snackbar message appearing at the bottom behind the navigation bar.

### Environment data
Android version: 8.1

Device model: Emulator

Stock or customized system: Stock

Nextcloud app version: 3.1.0

Nextcloud server version: 13.0.2

![device-2018-05-20-192651](https://user-images.githubusercontent.com/366855/40281565-c833ad7a-5c63-11e8-89a0-34443366becc.png)

**Comment by AndyScherzinger** [comment]
Fixed via #2599
