### ISSUE TITLE
I keep getting asked for the password every 3-5 seconds

### ISSUE THREAD

**Issue by andreicristianpetcu** [nextcloud/android#2597]
### Actual behaviour
- I open the app, log in but I keep getting asked for the password.
https://vimeo.com/270982183
If I just press back, and the log in screen dissapears.

### Expected behaviour
- I expect once I log in, not to be asked for the password anymore.
 
### Steps to reproduce
1. I just open the app where I am logged in.

### Environment data
Android version: LineageOS 14.1-20180324-NIGHTLY-oneplus2 based on Android 7.1.2

Device model: OnePlus2

Stock or customized system: Custom. LineageOS.

Nextcloud app version: 3.1.0 same on the dev build 20180427 Both from F-Droid

Nextcloud server version: 11.0.2

### Logs
I don't have access to the server logs :(

**Comment by xXSTrikeXx** [comment]
I suggest to update at least to version 11.0.8 or better directly to v. 13, because version 11 is already EOL.
