### ISSUE TITLE
downloading a file makes the phone vibrate until the download is finished.

### ISSUE THREAD

**Issue by obama** [nextcloud/android#2601]
### Expected behaviour
it should not vibrate all the time
 
### Steps to reproduce
1. download a file from your nextcloud to the phone

### Environment data
Android version: 8.0

Device model: Xiaomi Mi A1

Stock or customized system: Stock, using trebuchet launcher

Nextcloud app version: 3.1

Nextcloud server version: 13.0.2

**Comment by AndyScherzinger** [comment]
Hi @obama this usually doesn't happen, can you check if this is related to the launcher, since the stock launchers don't seem to do this, at least not the ones we know.

**Comment by tobiasKaminsky** [comment]
On android 8 you can change notification behaviour for each channel of an app.
Please go to app settings -> nextcloud -> app notifications and then have a look what settings are chosen for "download channel". it should be "importance medium: no sound".
