### ISSUE TITLE
Make check box slightly larger

### ISSUE THREAD

**Issue by c0fe** [nextcloud/android#2608]
My suggestion is small and simple, make the check box that appears in the Android application a bit larger. currently I find it more difficult than it should be to select it.

**Comment by AndyScherzinger** [comment]
@c0fe are you referring to any checkbox in particular or check boxes within the app in general?

No matter which one of the two I'd say don't enlarge the check boxes since it is the standard size for check boxes but enlarge the "hit box" thus a larger area "around" the checkbox will also de-/select the check box.

**Comment by tobiasKaminsky** [comment]
Once multi-select is enabled you can click on the whole row area for selecting/deselecting an item, so the "touchable area" of a checkbox is not used at all, or am I missing something?

**Comment by AndyScherzinger** [comment]
Like my initial question: I am not sure which check boxes @c0fe is referring to

**Comment by c0fe** [comment]
@AndyScherzinger checkboxes in the app in general if you want to select multiple files for deletion for example.

**Comment by AndyScherzinger** [comment]
@c0fe erm, at least checkin with 3.1.0 when I then have the multi-select mode active I can click anywhere on the item for selection, I don't have to click on the check box itself.

**Comment by c0fe** [comment]
@AndyScherzinger that's weird, maybe something wrong with my thumbs.

**Comment by AndyScherzinger** [comment]
@c0fe Can you do an animated gif / video of it?

**Comment by c0fe** [comment]
@AndyScherzinger further testing I think I just messed up something or my screen is not working. I will close this issue for now.

**Comment by AndyScherzinger** [comment]
@c0fe thanks for the feedback, please feel free to reopen in case you are experience this issue again since checkboxes should be easy to hit and if not it needs to be fixed.
