### ISSUE TITLE
#2573 breaks account change

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#2610]
the account switch isn't working anymore at all on the PR/branch #2573

Simply try to switch the account (2 accounts on 2 different servers).
If you remove the launch singleTop flag it works again for the user list in the drawer but still doesn't work at all for the avatar clicks in the drawer header. So something is really broken here.

Good thing, this doesn't happen on the master branch, or trashbin branch thus it must have been introduced via #2573

**Comment by tobiasKaminsky** [comment]
I'll give it a try now.

**Comment by AndyScherzinger** [comment]
Awesome! :heart:

**Comment by tobiasKaminsky** [comment]
> If you remove the launch singleTop flag it works again for the user list in the drawer but still doesn't work at all for the avatar clicks in the drawer header. So something is really broken here.

This is fixed with my latest commit.

With "singleTop" it is not working, but I'll debug it further.

**Comment by tobiasKaminsky** [comment]
Now this is also working.
@AndyScherzinger please test and then we can close this :tada:

**Comment by AndyScherzinger** [comment]
Works like a charm :+1:
