### ISSUE TITLE
"Auto upload" works after start app manualy

### ISSUE THREAD

**Issue by ahadobas** [nextcloud/android#2612]
### Actual behaviour
I've set up folders (DCIM, ...) to "auto upload". It works. Restarted my phone. Taken pictures. No auto upload at all.

### Expected behaviour
It should be to do the auto upload after restarting the phone.
 
### Steps to reproduce
As I described above.

### Environment data
Android version: MIUI 8.4.19

Device model: Xiaomi Mi 5s

Stock or customized system: Stock, dev

Nextcloud app version: 3.1.0

Nextcloud server version: 13

**Comment by savin-msk** [comment]
Confirm. I have same behavior on my Mi Note 3. MIUI 9.5.3.0.

**Comment by FredericMa** [comment]
I experience the same.
To initiate the upload I need to start the Nextcloud app and take a new picture.
After that the app starts uploading all remaining pictures.

Phone: Samsung Galaxy S8
Android: Official Samsung Oreo 8.0.0
Nextcloud: 13.0.0

**Comment by stratege1401** [comment]
Absolutely the same, I concur.

**Comment by nordic-style** [comment]
Phone: Galaxy S9
Android: 8.0.0
Nextcloud App: 3.2.0
Nextcloud 13.0.2

Energy Saving is disabled for the app.

Steps:
1) Shot a picture
2) no upload
3) start nc app
4) shot another pictures
5) auto upload
6) send mobile to sleep
7) take another picture
8) no upload
9) start nc app
10) take another picture
11) auto upload

... etc ...

**Comment by linxux** [comment]
So, any update for this issue?

**Comment by tobiasKaminsky** [comment]
I tested it with a S9+ and I had to disable the energy/suspend optimization explicitly for this app.
After this it worked without any problems.
If you need, I can do some screenshots, where I disabled the energy stuff.

**Comment by loelkes** [comment]
@tobiasKaminsky I have a S9+ with stock Android 8.0.0 and NC 3.2.1 and the disabling of the energy / suspend optimization did not solve the problem.

**Comment by ahadobas** [comment]
@tobiasKaminsky I've set it up. Works, BUT drains battery extremely fast :(

**Comment by xeno024** [comment]
It still does not work for me. I just installed everything. He does not want to fill it up automatically. Several folders are set, but you do not want to upload old files. There is no sign of any mistake, there is nothing in the uploads.
(Huawei phone)
Sorry about my English!

**Comment by codecraftsman9** [comment]
Try turning off "battery saver" mode.

**Comment by xeno024** [comment]
It was already there but it did't help.

**Comment by egeu5** [comment]
Any news on that? Nextcloud is set to auto-start and run in background but without success. On my old phone it is working perfectly, same thing on my ipad.

**Comment by egeu5** [comment]
I've no new news on that. Still not working.

**Comment by tobiasKaminsky** [comment]
Unfortunately this is due to some vendors think they are smarter than Android's battery saving mechanism and then implement something "better".

As I do not have a Huawai P10, there is not much I can do here.
We are following Android's way to start Auto Upload as background jobs after reboot.

**Comment by egeu5** [comment]
But i disabled battery-saving for the app. Other "background auto-sync-apps" are working.

**Comment by nicbou** [comment]
I have the same issue on my Galaxy S9.

- The uploads work fine, but stall about a minute after I close the app. The notification shows a 100% upload that can't be dismissed.
- The uploads resume as soon as I reopen the app.

I have explicitly disabled power saving for the app. My phone is fully charged. The issue happens even when my phone is charging.

Would it be possible for the bot to stop closing these issues? They are not stale. There is just nothing else to add.

![Screenshot_20200506-084351_Chrome](https://user-images.githubusercontent.com/88917/81145124-ee4a1700-8f75-11ea-8f45-f838ac7365b2.jpg)
![Screenshot_20200506-083714_Settings](https://user-images.githubusercontent.com/88917/81145125-f013da80-8f75-11ea-80f5-0eeebecc45e2.jpg)

**Comment by nicbou** [comment]
I have also confirmed that data usage is not limited. Other background apps like Spotify and Podcast Addict do not have issues. 

![Screenshot_20200506-084806_Settings](https://user-images.githubusercontent.com/88917/81145362-6f091300-8f76-11ea-97e1-7e5680e4eac6.jpg)

I'll leave this in case it can help others. The issue is still unresolved, but there's no telling whether Samsung or Nextcloud is to blame.
