### ISSUE TITLE
Obsolete Gradle Dependency

### ISSUE THREAD

**Issue by gupta1anubhav** [nextcloud/android#2614]
### Actual behavior
Warnings are shown by Android Lint as some Gradle dependencies are outdated.

### Expected behavior
Gradle dependencies should be updated to the latest version.

### Environment data
Warnings are shown in all build variants.

Stock or customized system: Stock, dev

Nextcloud app version: 3.1.0

![screenshot from 2018-05-24 16-08-47](https://user-images.githubusercontent.com/31107831/40482523-cb54b384-5f72-11e8-834f-fb5b23ca000f.png)

Would you like to work on this issue?
Yes, I want to work on this issue.

**Comment by AndyScherzinger** [comment]
Hi @gupta1anubhav and welcome to Nextcloud! 

Thanks for the report and for the offer to work on this :+1:

**Comment by gupta1anubhav** [comment]
Thanku @AndyScherzinger

**Comment by AndyScherzinger** [comment]
gradle dependencies are now halndled by the dependabot, thus closing
