### ISSUE TITLE
Logo/Icon Proposal

### ISSUE THREAD

**Issue by jbeguna04** [nextcloud/android#2615]
Sorry for not having the template
Hi good day! Im Jibbie Eguna, a graphics designer, I would like to ask for your permission to propose a new designs of logo in your application/project. I would like to help projects in open-source .I would just like to propose new designs if you are needing it. Hoping for your positive response Thank You!

**Comment by AndyScherzinger** [comment]
Hi @jbeguna04 and welcome to Nextcloud.

I'm looping in @jancborchardt and @nextcloud/designers for this questions while I'd guess the answer will be no.

**Comment by jbeguna04** [comment]
thank you for the response, good luck on your application

**Comment by AndyScherzinger** [comment]
Thanks @jbeguna04 :heart: 

Since you create graphical work for OSS Apps, maybe you want to have a chat with @jancborchardt about the opensourcedesign initiative :balloon:

**Comment by jbeguna04** [comment]
That would be great sir, I wish i can communicate with him

**Comment by juliushaertl** [comment]
@jbeguna04 Checkout https://opensourcedesign.net/ for more details on the initiative. Maybe you also want to join the forum at https://discourse.opensourcedesign.net/ or the IRC channel #opensorucedesign at freenode.

**Comment by jbeguna04** [comment]
thank you @juliushaertl

**Comment by juliushaertl** [comment]
And about the original question, I don't think that the proposal of a new design for the logo is needed, but if you encounter issues with the design in Nextcloud, feel free to join and discuss them in issues here on GitHub. For more details on how you can contribute to Nextcloud design, see: https://nextcloud.com/design/

**Comment by jancborchardt** [comment]
Thanks @AndyScherzinger & @juliushaertl! :) Have nothing more to add
