### ISSUE TITLE
Destroyed file due to failed opening of .ipf file

### ISSUE THREAD

**Issue by Pillaknuff** [nextcloud/android#2627]
### Actual behaviour
I tried to oben a igor procedure file on my smartphone. Since the format is not supported by any app i then tried to copy it to another folder, change the ending to .txt and then open it (which did not work). I then deleted the copied version. The next day when syncing with a nextcloud desktop client i saw, that the original file was broken, meaning having 0kb of size and being empty. Restoring a previous version did save the file, but it seems opening unsupported datatypes can destroy files.

### Expected behaviour
I expected to file to be opened as a txt file, since it is simply a plane text file of code with a different file ending.
 
### Steps to reproduce
1. upload an igor procedure file (.ipf)
2.  try to open in adroid app
3. copy
4. rename copy
5. delete copy
6. sync original file to desktop by client

### Environment data
Android version:

Device model: Samsung galaxy s8+

Stock or customized system:

Nextcloud app version: 3.1.0

Nextcloud server version: 13.0.0

### Logs
 from android app:
-file changed (<- probably this is the problematic entry)
-file created
-created file renamed
-renamed file deleted

**Comment by tobiasKaminsky** [comment]
Step 3 is for me not clear: where are you copy the file to?

**Comment by Pillaknuff** [comment]
I mean copy using the nextcloud android app, meaning copy the file to another folder in order to enable opening by then changing the .ipf ending to .txt
