### ISSUE TITLE
In app deep links

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#263]
Clicking on https://nextcloud.com/index.php/f/389122 in browser should open the corresponding file in nextcloud app.

**Comment by tobiasKaminsky** [comment]
Wasn't there a recent discussion where we figured out that this cannot work as the links can change dynamically whereas android requires the app to register with a defined prefix?

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky yes, that would be #1069 where we then would need to have nc:// links

**Comment by tobiasKaminsky** [comment]
Then I'll close this in favor of #1069
