### ISSUE TITLE
Upload not working correctly

### ISSUE THREAD

**Issue by BlueCaos** [nextcloud/android#2630]
### Actual behaviour
The App uploads the file / picture / contact to 100%, but then gets stuck with full progress bar. When I check via webinterface the file is there.
After the upload ran into an timeout, i get the message an error occured. But a few seconds later it tries again and would run in the same issue.

Thats an image of the resulting files on my nextcloud (contact backup):
![image](https://user-images.githubusercontent.com/39102356/40600621-75646324-6252-11e8-8d4e-bc1d2e0e29d2.png)

The behaviour with otherfiles is the same:
![image](https://user-images.githubusercontent.com/39102356/40600955-81973eae-6253-11e8-9d9c-7ca4b61ba560.png)

### Expected behaviour
- The file gets uploaded once.
 
### Steps to reproduce
1. Upload anything with the nextcloud app

### Environment data
Android version:
7.0
Device model: 
LG-H850
Stock or customized system:
Stock
Nextcloud app version:
3.1.0 beta
Nextcloud server version:
13.0.2 stable
#### Web server error log
Noting related realy

#### Nextcloud log (data/nextcloud.log) (that's an error i found a few days ago, not today. Tody there were none in the log file)
{"reqId":"iNknPu7npTDUJZxGbg9l","level":0,"time":"2018-05-20T06:35:17+00:00","remoteAddr":"2.247.254.139","user":"tim","app":"webdav","method":"HEAD","url":"\/remote.php\/webdav\/.Contacts-Backup\/2018-05-20_08-35-14.vcf","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotFound\",\"Message\":\"File with name .Contacts-Backup\\\/2018-05-20_08-35-14.vcf could not be located\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(81): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('.Contacts-Backu...')\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:GET', Array)\\n#4 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(253): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response), false)\\n#5 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpHead(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#7 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:HEAD', Array)\\n#8 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\\/var\\\/www\\\/html\\\/cloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(80): Sabre\\\\DAV\\\\Server->exec()\\n#10 \\\/var\\\/www\\\/html\\\/cloud\\\/remote.php(164): require_once('\\\/var\\\/www\\\/html\\\/c...')\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/cloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/ObjectTree.php\",\"Line\":174}","userAgent":"Mozilla\/5.0 (Android) ownCloud-android\/3.1.0","version":"13.0.2.1"}
{"reqId":"ku6iOjtS3d6G7TRvaiDX","level":0,"time":"2018-05-20T06:44:07+00:00","remoteAddr":"2.247.254.139","user":"tim","app":"webdav","method":"HEAD","url":"\/remote.php\/webdav\/.Contacts-Backup\/2018-05-20_08-35-14%20(2).vcf","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotFound\",\"Message\":\"File with name .Contacts-Backup\\\/2018-05-20_08-35-14 (2).vcf could not be located\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(81): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('.Contacts-Backu...')\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:GET', Array)\\n#4 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(253): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response), false)\\n#5 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpHead(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#7 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:HEAD', Array)\\n#8 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\\/var\\\/www\\\/html\\\/cloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(80): Sabre\\\\DAV\\\\Server->exec()\\n#10 \\\/var\\\/www\\\/html\\\/cloud\\\/remote.php(164): require_once('\\\/var\\\/www\\\/html\\\/c...')\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/cloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/ObjectTree.php\",\"Line\":174}","userAgent":"Mozilla\/5.0 (Android) ownCloud-android\/3.1.0","version":"13.0.2.1"}
{"reqId":"50O5grRNWFLcLnNXVxWp","level":0,"time":"2018-05-20T06:59:17+00:00","remoteAddr":"2.247.254.139","user":"tim","app":"webdav","method":"HEAD","url":"\/remote.php\/webdav\/.Contacts-Backup\/2018-05-20_08-35-14%20(2)%20(2).vcf","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotFound\",\"Message\":\"File with name .Contacts-Backup\\\/2018-05-20_08-35-14 (2) (2).vcf could not be located\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(81): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('.Contacts-Backu...')\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:GET', Array)\\n#4 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(253): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response), false)\\n#5 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpHead(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#7 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:HEAD', Array)\\n#8 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\\/var\\\/www\\\/html\\\/cloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(80): Sabre\\\\DAV\\\\Server->exec()\\n#10 \\\/var\\\/www\\\/html\\\/cloud\\\/remote.php(164): require_once('\\\/var\\\/www\\\/html\\\/c...')\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/cloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/ObjectTree.php\",\"Line\":174}","userAgent":"Mozilla\/5.0 (Android) ownCloud-android\/3.1.0","version":"13.0.2.1"}
{"reqId":"gOxmZlJefK4O4ibxBgsh","level":0,"time":"2018-05-20T07:02:58+00:00","remoteAddr":"92.211.7.71","user":"tim","app":"webdav","method":"HEAD","url":"\/remote.php\/webdav\/.Contacts-Backup\/2018-05-20_08-35-14%20(2)%20(2)%20(2).vcf","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotFound\",\"Message\":\"File with name .Contacts-Backup\\\/2018-05-20_08-35-14 (2) (2) (2).vcf could not be located\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(81): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('.Contacts-Backu...')\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:GET', Array)\\n#4 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(253): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response), false)\\n#5 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpHead(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#7 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:HEAD', Array)\\n#8 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\\/var\\\/www\\\/html\\\/cloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(80): Sabre\\\\DAV\\\\Server->exec()\\n#10 \\\/var\\\/www\\\/html\\\/cloud\\\/remote.php(164): require_once('\\\/var\\\/www\\\/html\\\/c...')\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/cloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/ObjectTree.php\",\"Line\":174}","userAgent":"Mozilla\/5.0 (Android) ownCloud-android\/3.1.0","version":"13.0.2.1"}
{"reqId":"5MJZ0Ysutz8C8FfRc2E6","level":0,"time":"2018-05-20T07:13:07+00:00","remoteAddr":"92.211.7.71","user":"tim","app":"webdav","method":"HEAD","url":"\/remote.php\/webdav\/.Contacts-Backup\/2018-05-20_08-35-14%20(2)%20(2)%20(2)%20(2).vcf","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotFound\",\"Message\":\"File with name .Contacts-Backup\\\/2018-05-20_08-35-14 (2) (2) (2) (2).vcf could not be located\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(81): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('.Contacts-Backu...')\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:GET', Array)\\n#4 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(253): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response), false)\\n#5 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpHead(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#7 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:HEAD', Array)\\n#8 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\\/var\\\/www\\\/html\\\/cloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(80): Sabre\\\\DAV\\\\Server->exec()\\n#10 \\\/var\\\/www\\\/html\\\/cloud\\\/remote.php(164): require_once('\\\/var\\\/www\\\/html\\\/c...')\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/cloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/ObjectTree.php\",\"Line\":174}","userAgent":"Mozilla\/5.0 (Android) ownCloud-android\/3.1.0","version":"13.0.2.1"}
{"reqId":"JDc6KZGbLcZcL6cIKwcP","level":0,"time":"2018-05-20T07:14:17+00:00","remoteAddr":"92.211.7.71","user":"tim","app":"webdav","method":"HEAD","url":"\/remote.php\/webdav\/.Contacts-Backup\/2018-05-20_08-35-14%20(2)%20(2)%20(2)%20(2)%20(2).vcf","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotFound\",\"Message\":\"File with name .Contacts-Backup\\\/2018-05-20_08-35-14 (2) (2) (2) (2) (2).vcf could not be located\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(81): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('.Contacts-Backu...')\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:GET', Array)\\n#4 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(253): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response), false)\\n#5 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpHead(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#7 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:HEAD', Array)\\n#8 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\\/var\\\/www\\\/html\\\/cloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(80): Sabre\\\\DAV\\\\Server->exec()\\n#10 \\\/var\\\/www\\\/html\\\/cloud\\\/remote.php(164): require_once('\\\/var\\\/www\\\/html\\\/c...')\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/cloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/ObjectTree.php\",\"Line\":174}","userAgent":"Mozilla\/5.0 (Android) ownCloud-android\/3.1.0","version":"13.0.2.1"}

**Comment by tobiasKaminsky** [comment]
This is indeed strange:
if a file xyz.jpg already exists, a new file "xyz (2).jpg" and then "xyz (3).jpg" is created. 
But you have "xyz.jpg", "xyz (2).jpg" and xyz (2) (2).jpg".

Can yo give us some details on your server?
- web server? apache or nginx
- external storage?

**Comment by BlueCaos** [comment]
The Webserver is Apache 2.4.25-3 on Raspberry Pi 3+
the storage used is on a cifs mount from my local NAS

**Comment by tobiasKaminsky** [comment]
@nextcloud/server-triage can this be somehow related to cifs? 
We check if a file already exists and if so, increment (2…5).

**Comment by rullzer** [comment]
Does this also happen when you try to upload via the webui?

**Comment by BlueCaos** [comment]
no, the webui works fine. This only occures when I try to Upload it with my phone.
It even detects conflicts, if the file exists.

I Uploaded a testfile:

![image](https://user-images.githubusercontent.com/39102356/40652302-3e949ee0-6338-11e8-9ebb-15c6839360ef.png)
![image](https://user-images.githubusercontent.com/39102356/40652393-6dc14c4a-6338-11e8-987c-dbb93cd1b35a.png)

**Comment by BlueCaos** [comment]
Allright, so since the Update 3.2.0 RC2 the Upload is working mostly

**BUT**
If I use the option "move to app folder" the Upload itself is working just fine, but after it's completion (it stopps at 100%) the move operation wont trigger st once. so the file is just sitting there until it maybe works or the app runs in an timeout, and i get the error.
the contactbackup is still not working (yesterday i got the backup 16 times, all with one additional "(2)" in the filename. You can immagin how it looks like.)
