### ISSUE TITLE
AutoUpload staying on 'waiting for wifi' 

### ISSUE THREAD

**Issue by klauf** [nextcloud/android#2632]
### Actual behaviour
- AutoUpload queues pics to upload but is not uploading them
- standard manual upload of photos or files works pretty well, also from the app

### Expected behaviour
- Photos in the upload queue should be uploaded
 
### Steps to reproduce
1. Go in upload menu
2. Photos are in the list 'waiting for wifi', click on one to try again
3. Progress bar is shown for a few seconds then the error 'waiting for wifi' comes back

### Environment data
Android version: 8.1.0

Device model: Huawei P20 EML-L29

Stock or customized system: stock

Nextcloud app version: 3.1.0

Nextcloud server version: 12.0.4

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
2018/05/28 22:46:10
UploadFileOperation : Upload delayed until WiFi is available: /InstantUpload/Photos Huawei P20//IMG_20180506_173113.jpg

2018/05/28 22:46:10
UploadFileOperation : Upload of /storage/emulated/0/DCIM/Camera/IMG_20180506_173113.jpg to /InstantUpload/Photos Huawei P20//IMG_20180506_173113.jpg: Operation finished with HTTP status code -1 (fail)

2018/05/28 22:46:10
UploadsStorageManager : updateDatabaseUploadResult uploadResult: com.owncloud.android.lib.common.operations.RemoteOperationResult@facec53 upload: com.owncloud.android.operations.UploadFileOperation@7d41990

2018/05/28 22:46:10
UploadsStorageManager : Updating /storage/emulated/0/DCIM/Camera/IMG_20180506_173113.jpg with status:UPLOAD_FAILED and result:DELAYED_FOR_WIFI (old:/storage/emulated/0/DCIM/Camera/IMG_20180506_173113.jpg status:UPLOAD_IN_PROGRESS result:-1)

2018/05/28 22:46:10
UploadsStorageManager : Updating /storage/emulated/0/DCIM/Camera/IMG_20180506_173113.jpg with status=UPLOAD_FAILED

2018/05/28 22:46:10
UploadsStorageManager : updateUpload returns with: 1 for file: /storage/emulated/0/DCIM/Camera/IMG_20180506_173113.jpg

2018/05/28 22:46:10
UploadsStorageManager : notifyObserversNow

2018/05/28 22:46:10
FileUploader : NotifyUploadResult with resultCode: DELAYED_FOR_WIFI

2018/05/28 22:46:10
FileUploader : Stopping command after id 1
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by klauf** [comment]
Forgot to mention I'm on wifi, and also disabled the option 'sync only on wifi' I prior to trying again and save logs.
issue #2035 seems similar but doesn't help.
many thanks in advance

**Comment by nonplusnl** [comment]
Same issue, Android 8.1, Nokia 7 plus.
Wifi is on. "Metered network" is on Automatic; turning to "Unmetered" does not help. Uploads remain stuk "Waiting for wifi", despite unmetered wifi active. 
(Note: when "Upload on unmetered wifi" is unchecked, uploads work fine. But obviously I want to wait for wifi:-)

**Comment by klauf** [comment]
Guess what, just changed the server (from Raspberry pi 2 running osmc to Raspberry pi 3+ running the very same SD card with osmc) and nextcloud app currently uploading :-)
will report if expected behavior returns (upload on wifi)

**Comment by nonplusnl** [comment]
That's weird. I just upgraded from 13.0.2 to 13.0.4 but that did not help. Running on Ubuntu 17.10 x64 with 4GB RAM; should be no problems there.

**Comment by nonplusnl** [comment]
Hi @klauf , I see you have closed this issue. Does that mean it is fixed now? As it stands, my autouploads still all end up "Waiting for wifi"  :-(
Thanks

**Comment by klauf** [comment]
Yep, actually the new pics resumed auto uploading, as for the ones remaining "waiting for wifi" I uploaded them manually and deleted the entry in the auto upload list. Everything fine now. Working as it should. 

On 24 June 2018 17:54:26 CEST, nonplusnl <notifications@github.com> wrote:
>Hi @klauf , I see you have closed this issue. Does that mean it is
>fixed now? As it stands, my autouploads still all end up "Waiting for
>wifi"  :-(
>Thanks
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/nextcloud/android/issues/2632#issuecomment-399766644

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by nonplusnl** [comment]
Finally isolated the bug. In my case, the VPN is causing problems. I opened #2839  for this
