### ISSUE TITLE
Upload failing - Large file (490MB)

### ISSUE THREAD

**Issue by noci2012** [nextcloud/android#2637]
### Actual behaviour
- The upload completes in the sense that ALL 448 segments of 1MB are uploaded
- Then all files get deleted and the upload is declared failed....

### Expected behaviour
- An upload of the file that completes and is stored (like its smaller bretheren).
 
### Steps to reproduce
1. On phone make a backup of some tool (Titanium)
2. Synchronize this to nextcloud
3. ....

### Environment data
Android version:
6.0.1 
Device model: 
Samsung 5s
Stock or customized system:

Nextcloud app version:
Current version
Nextcloud server version:
13.0.2.1
#### Web server error log
```
a.b.c.d - user [29/May/2018:15:11:19 +0200] "PUT /remote.php/webdav/backup/net.osmand.plus-20180529-000727.tar.gz-chunking-1348511718-448-447 HTTP/1.1" 499 0 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.1.0"
```

#### Nextcloud log (data/nextcloud.log)
```
No relevant entries except for some remainders of previously failed transfers due to loss of WiFi 
Messages like:
Fatal | webdav | Sabre\DAV\Exception\BadRequest: expected filesize 1024000 got 532480
-- | -- | --
But those are NOT relevant to the failure. 
```

**Comment by noci2012** [comment]
Addendum: PHP allows for 1GB datauploads, (php.ini, pool settings, .user.ini)
data memory limit for PHP = 1GB
Web server = nginx, php = fpm V7.0,  front = haproxy (tcp mode).

**Comment by tobiasKaminsky** [comment]
@nextcloud/server-triage can this be a prbolem due to timeout on chunk assembling?

**Comment by rullzer** [comment]
Could be it is hard tot ell.

@noci2012 can you upload large files properly via the web ui?

**Comment by noci2012** [comment]
I could do a 120MB  & 700MB upload by dropping a file into the Download folder in Nextcloud.

The difference i see is: 
This upload send data to:
{user}/uploads/web-file-upload-3f010e8c81c9adeafe3fcc89cc2e2087-1527695175439/{random names}
(a 700MB .zip could be uploaded)

The failing upload sends data to:
{user}/cache/{basename}-{partnumber}

**Comment by noci2012** [comment]
a 124MB files does materialize....

The 700MB files also shows up, but it continuously retried...
So it seems get assembled anyway, the clients only doesn't care anymore it seems.

**Comment by noci2012** [comment]
upload of 700MB seemed to succeed when i added 

      fastcgi_read_timeout 300;
      fastcgi_send_timeout 300;

to the fastcgi invocation section for php.

**Comment by tobiasKaminsky** [comment]
@rullzer we are doing currently 1mb chunks, can it be that there are just too many chunks and therefore the server runs in timeout?
How big are the chunks during web upload?

**Comment by rullzer** [comment]
@tobiasKaminsky could be a timeout issue. Webupload they are 10MB if I'm not mistaken. But the overhead should not be that huge if you have 42 chunks or 420 chunks.

@noci2012 what kind of hardware are you running on? Particulary slow storage?

**Comment by noci2012** [comment]
10K Scsi RAID 1 Array (mdraid). 
From SmartCTL:
Vendor:               SEAGATE
Product:              ST3300007LW
~30% of diskcapacity in use..

System is a 4 Core AMD Phenom X4 810 (800Mhz, - 2Ghz on demand) 8GB Mem, ~50% used.
system load 1.5 - 2.5 (latter when a VM there is handling remote backups that are synced to this site, different disks though).
Internet connection 80 Mbps Symmetric (will become 100 in a few days)

Wifi is 5Ghz  on two tested locations.

**Comment by noci2012** [comment]
@rullzer, do you need more info?

**Comment by rullzer** [comment]
Nah those specs look fine.

I'm a bit puzzled as those specs should be able to assemble a 400 mb file pretty easily within 5 minutes...

**Comment by noci2012** [comment]
I think it is solved, the server inadvertenendly updated itself to V14.0.3  when update 13.0.7 became availabel.
Not observed since.... (Server now V15.04, so this became untestable).
