### ISSUE TITLE
[3.2.0 RC1] View filter in main menu (photos, favorites, shared) don't work anymore

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#2638]
### Actual behaviour
- simply click on the filter in the drawer menu, nothing is happening.

**Comment by gradinaruvasile** [comment]
Those never worked for me on the Android app (i tried on 3 phones and 4 Android versions).

**Comment by arnowelzel** [comment]
Favorites and Shared work for me in 3.1.0 (did not check 3.2.0 yet). Photos really long to load, but I think this is more because of the huge number of photos I have on my server.

**Comment by gradinaruvasile** [comment]
I understand the photos issue (i have a large library) but favorites i have 5 or so and it doesnt work either. It never worked for me.

**Comment by AndyScherzinger** [comment]
> It never worked for me.

Well, that is an issue/bug then :(

**Comment by rullzer** [comment]
There are in general upgrades coming in this direction (faster photo load) but they will only be possible with NC14 as server support is needed.

**Comment by rullzer** [comment]
@AndyScherzinger yes seems like the filters don't do anything. Not even loading....

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger is correct, it was due to "sinleTop".
There is now a fix in #2647
