### ISSUE TITLE
[3.2.0.RC1] Crashes on start after app update

### ISSUE THREAD

**Issue by OlivierS1** [nextcloud/android#2639]
### Actual behaviour
- Tell us what happens
Nextcloud no longer works after updating to, I believe, 3.2.0.RC1.
I was using my phone when I received Nextcloud app crash window poping. I noticed it had been updated a few minutes earlier.

### Expected behaviour
- Tell us what should happen
I can no longer run Netcloud app as it crashes on start. I uninstalled the app and installed it a few times without any results. 

### Steps to reproduce
1. Installing 3.2.0.RC1
2. launching the app and crash.
3. 

### Environment data
Android version:
4.x
Device model: 
Samsung Galaxy II
Stock or customized system:
Stock
Nextcloud app version:
3.2.0.RC1
Nextcloud server version:
13.1
#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
@OlivierS1 did you send a crash report?

**Comment by OlivierS1** [comment]
@AndyScherzinger Are you talking about the the report  from the following dialog:
"Unfortunately, Nextclooud has stopped. Report, OK"?
Or the log gathered from withing  the Nextcloud App itself under the "Settings" menu? For the latter, I would need more guidance to extract the log without the app running.

**Comment by AndyScherzinger** [comment]
> "Unfortunately, Nextclooud has stopped. Report, OK"?
This one! :+1:

**Comment by OlivierS1** [comment]
@AndyScherzinger Done.

**Comment by AndyScherzinger** [comment]
Hi @OlivierS1, my guess by your infos and the reports which hint this is the one I guess you hit this one: #2643

Does the app always crash at the start or only the first time? Only after booting the phone?

**Comment by OlivierS1** [comment]
@AndyScherzinger It always crashes. I first noticed the issue as I was ready some emails when out of the blue I got the ""Unfortunately, Nextclooud has stopped. Report, OK". I would press the "OK" button and shortly after the app would crash again.
I tried to restart the phone but it did not help. Upon removing the app, I reinstalled it and while starting it, it would crash. I couldn't reach the point where I could enter the app and setup my account.

As a backup solution, I am now running off F-Droid "Nextcloud Dev: Version 20180526".

**Comment by AndyScherzinger** [comment]
Thanks for the feedback @OlivierS1 

strangely
> "Nextcloud Dev: Version 20180526"
shouldn't then work either since we haven't touched anything related to the file sync 7 auto upload lately.

@tobiasKaminsky @mario any ideas? I guess #2643 is the cause of this

**Comment by OlivierS1** [comment]
3.2.0.RC2 fixed the issue.
Thanks.

**Comment by AndyScherzinger** [comment]
Glad we got it resolved quickly and thanks for the instant report :)
