### ISSUE TITLE
Disable Google Analytics introduced by Firebase

### ISSUE THREAD

**Issue by alexara** [nextcloud/android#2657]
Since you have introduced Firebase, you might need to explicitly disable Google Analytics (https://firebase.google.com/docs/analytics/). :-)

The instruction https://firebase.google.com/docs/analytics/android/start/ actually says:
> Getting started with Analytics is easy. **Just add the Firebase SDK to your new or existing app, and data collection begins automatically**

> Analytics automatically logs some events and user properties; **you don't need to add any code to enable them.** 

**So how can you disable the Analytics?** 

If you have a look at https://firebase.google.com/docs/android/setup#available_libraries it says that the `firebase-core` library corresponds to the Analytics part of FireBase. 
The `firebase-core` is pulled in as a dependency automatically once you add the Firebase SDK to you project.

Hence you would like to remove it:
```configurations.all {
exclude group: 'com.google.firebase', module: 'firebase-core'
}
```

The official guide to disable Analytics does not tell you about this solution (or at least it's pretty good hidden) and suggests another:

> **Permanently deactivate collection**
> 
> If you need to deactivate Analytics collection permanently in a version of your app, set firebase_analytics_collection_deactivated to true in your app's AndroidManifest.xml in the application tag. For example:
> 
> `<meta-data android:name="firebase_analytics_collection_deactivated" android:value="true" />`
> 
> **Disable Advertising ID collection**
> y
> If you wish to disable collection of the Advertising ID in your Android app, you can set the value of google_analytics_adid_collection_enabled to false in your app's AndroidManifest.xml in the application tag. For example:
> 
>` <meta-data android:name="google_analytics_adid_collection_enabled" android:value="false" />`
> 

Source: https://firebase.google.com/support/guides/disable-analytics

See also https://stackoverflow.com/questions/39327141/disable-the-analytics-service-for-firebase-cloud-messaging

PS: Nextcloud Talk for Android already disabled it:

-  https://github.com/nextcloud/talk-android/blob/1f1eb30123faed81c496bbe2ff948a67ac0f829c/app/src/gplay/AndroidManifest.xml#L17
- https://github.com/nextcloud/talk-android/blob/0a55a110c17c524476570a5de8edf52ae6dfab7f/app/build.gradle#L71

**Comment by mario** [comment]
Firebase Analytics was already removed.

**Comment by mario** [comment]
@alexara let me know if you find this not correct, but it really shouldn't be in the APK.

**Comment by alexara** [comment]
Where and how? I searched for "firebase" but it not find anything in this repository that shows that it is disabled. Can you point me to the commit?

**Comment by mario** [comment]
We removed the firebase-core dependency and I don't think firebase-messaging pulls it in.

The other two things you can add in Manifest are not really needed in case you don't have Firebase Core.

**Comment by alexara** [comment]
But why did you add it in the first place? https://github.com/nextcloud/android/commit/c7eed23de90ff3bc4e8f757986a993031b0c85a0

> We removed the firebase-core dependency and I don't think firebase-messaging pulls it in.

I thought it gets pulled in as inputmice stated here  https://github.com/siacs/Conversations/issues/3041

> By looking at the merged manifest excluding it seems to work...
But it was pulled in as a dependency. 

Well, if I find some more time and proof you wrong I will comment on it again ;-)

**Comment by mario** [comment]
Because we had a user that wanted to use Analytics for themselves?

**Comment by alexara** [comment]
> Because we had a user that wanted to use Analytics for themselves?

Never mind, I read the comments on the PR. :-)  Sorry for taking your time!
