### ISSUE TITLE
NextCloud consuming 25% CPU without any visible clue of work being done.

### ISSUE THREAD

**Issue by noci2012** [nextcloud/android#2663]
### Actual behaviour
-According to SystemPanel 2 CPU Stats,  Nextcloud is top CPU user with 21-25 %where total CPU use is around 34-50% .

### Expected behaviour
- Not consuming that much CPU? 
 
### Steps to reproduce
1. start NextCloud?
2. 
3. 

### Environment data
Android version:
6.0.1
Device model: 
Samsung s5 mini
Stock or customized system:
Stock, rooted

Nextcloud app version:
Current

Nextcloud server version:
N/A.  (13.0.2.1)

#### Web server error log
```
N/A
```

#### Nextcloud log (data/nextcloud.log)
```
N/A
```

**Comment by noci2012** [comment]
shortly after it mentions the failure to upload the 700MB file.
I didn't notice any network activity...

**Comment by tobiasKaminsky** [comment]
During upload we copy the file from external sd card to internal, if needed.
How long was the high cpu? 
If it was only in a short time span, this can be due to upload.

**Comment by noci2012** [comment]
The upload was 700MB, so this copy lasted minutes.... (10+?)   as the upload failed later on (other bug: #2637)  it is retried, retried, .... ad nauseam.
