### ISSUE TITLE
Synchronizing tasks with DAVDROID in ANDROID app and NC

### ISSUE THREAD

**Issue by hitam4450** [nextcloud/android#267]
Hi,
besides synchronizing calendars & contacts, how about to complete the synchronizing efforts by including the data of the task app as well ?

regards, hitam4450

**Comment by AndyScherzinger** [comment]
Hi @hitam4450,

at the moment there are no efforts made to add tasks but this might be something to be considered in the future but depending on the demand might be included in the Nextcloud app or provided by a separate third party or community app.

Best regards,
Andy

**Comment by tobiasKaminsky** [comment]
Depending on the task app it is just an ordinary calendar which already works syncing.
So look for a task app that uses caldav and sync it with davdroid.

**Comment by hitam4450** [comment]
Well, I do have Open task on my mobile device and I sync it already with the help of DAVDROID with the tasks app in NC 10! However, i would like to minimize on number of apps, interfaces and so son!

Maybe the ANDROID Client could achieve more then only handling the files app in the future e.g. tasks, gallery, etc.

regards, hitam4450

**Comment by tobiasKaminsky** [comment]
Due to limited dev capacities we cannot include all apps, especially when there are decent apps that will do it better than we can.
So we want to go the way to provide the nextcloud app as a central authenticator for every NC related app so it will be much easier to setup the other apps.
