### ISSUE TITLE
[3.2.0RC2] NPE in OCFile.getLocalId

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#2674]
via GPlay console
```
java.lang.NullPointerException: 
  at com.owncloud.android.datamodel.OCFile.getLocalId (OCFile.java:744)
  at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment.lambda$fetchAndSetData$4$FileDetailActivitiesFragment (FileDetailActivitiesFragment.java:230)
  at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment$$Lambda$2.run (Unknown Source)
  at java.lang.Thread.run (Thread.java:761)
```

**Comment by tobiasKaminsky** [comment]
I had a look at all those three, but could not find a fix :/

**Comment by tobiasKaminsky** [comment]
I do not find a way to pass a null ocFile into it :/

**Comment by AndyScherzinger** [comment]
Like you said, I'd expect getRemoteId() to be null.

**Comment by tobiasKaminsky** [comment]
Still this is very strange as we have always a remoteId as this is the internal file id from the server and without this nothing would work…

**Comment by equinoxefr** [comment]
Hi guys,

I think i have the same issue with 3.1 and 3.2RC2 versions. When i launch android client, after a few seconds the app crash.

`
06-10 09:19:34.898  6789  7637 D OwnCloudClient #7: REQUEST PROPFIND /remote.php/webdav/

06-10 09:19:34.990  6789  7637 I ReadRemoteFolderOperation: Synchronized /: Operation finished with HTTP status code 207 (success)

06-10 09:19:34.990  6789  7637 D RefreshFolderOperation: Synchronizing XXXX/

06-10 09:19:34.995  6789  7637 D OCFile  : OCFile name changing from /

06-10 09:19:34.998  6789  7637 D RefreshFolderOperation: Remote folder / changed - starting update of local data 

06-10 09:19:35.002  6789  7637 E AndroidRuntime: FATAL EXCEPTION: Thread-15

06-10 09:19:35.002  6789  7637 E AndroidRuntime: Process: com.nextcloud.client, PID: 6789

06-10 09:19:35.002  6789  7637 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.substring(int, int)' on a null object reference

06-10 09:19:35.002  6789  7637 E AndroidRuntime: 	at com.owncloud.android.datamodel.OCFile.getLocalId(OCFile.java:744)
`

Ask me if i can help you to get more advanced debugging infos.

Pierre

**Comment by tobiasKaminsky** [comment]
Is this also happening after uninstalling the app?
Maybe for some reason there is a broken DB entry.

**Comment by equinoxefr** [comment]
> Is this also happening after uninstalling the app?

Yes, i tried everything (uninstall, cleaning manually...). I will try on another phone.

On the same phone with another account it's ok.

There's still an issue on 3.2.

**Comment by tobiasKaminsky** [comment]
>  I will try on another phone.

This will be interesting.
If the error persists after cleaning, then it is probably related to the account :-/

**Comment by equinoxefr** [comment]
Hi,

I tried on an other phone with an older android version. Same issue. It seems you are right, it could be an issue related to my account. Do you know if there is something to check in the database ?

I already tried some occ maintenance without any success.

**Comment by tobiasKaminsky** [comment]
Can you create us a test account, test if the problem occurs also there and if so send the credentials to tobias at nextcloud dot com with a reference to this issue?

**Comment by equinoxefr** [comment]
i have no issue with other accounts. I will try to reproduce it with some data from my account.

**Comment by equinoxefr** [comment]
Hi,

I tried something new:

Move all data from my account on the server (mv command on linux)
occ files:scan on the account
Still crash.
Remove the account from Nextcloud
Recreate the account
move the data back to the account
occ files:scan on the account

Now it works like a charm

**Comment by tobiasKaminsky** [comment]
:+1: great to hear, but still strange what happened.
Maybe on server side some files were not correctly indexed and thus lead to crashing the app.
