### ISSUE TITLE
Application password / token should not be hidden

### ISSUE THREAD

**Issue by nicobo** [nextcloud/android#2677]
### Actual behaviour
Authenticating via an app password (or 'token', don't know how it's called in english, french translation is not consistent between the server and the app) is complicated because of the length of the generated app passwords : you have to type it with the smartphone's tiny keyboard and it's hidden.

### Expected behaviour
- The app password is very long and complicated to type on a phone so it should not be hidden or there should be a button to reveal it so I can check that I've not mistyped it.
 
### Steps to reproduce
1. Add a connection through the app
2. Choose 'login with app password' (or whatever label in english)
3. Try to type the password you got from the web interface

### Environment data
Android version:
6.0.1
Device model: 
Fairphone 2

Stock or customized system:
N/A
Nextcloud app version:
3.1.0
Nextcloud server version:
13
#### Web server error log
N/A
Insert your webserver log here
N/A

#### Nextcloud log (data/nextcloud.log)
N/A
Insert your Nextcloud log here
N/A

**Comment by AndyScherzinger** [comment]
like @tobiasKaminsky mentioned we now have a new login flow where the app tokens are genereated during the login
