### ISSUE TITLE
Display application password / token as QR Code

### ISSUE THREAD

**Issue by nicobo** [nextcloud/android#2678]
### Actual behaviour
Authenticating via an app password (or 'token') is complicated because of the length of the generated app passwords : you have to type it with the smartphone's tiny keyboard.

### Expected behaviour
- When connecting with an app password, allow : 
  - from the web interface to display it as a QR code
  - to scan this QR code from the mobile app to fill the field without typing
 
### Steps to reproduce
1. Add a connection through the app
2. Choose 'login with app password' (or whatever label in english)
3. Try to type the password you got from the web interface

### Environment data
Android version:
6.0.1
Device model: 
Fairphone 2

Stock or customized system:
N/A
Nextcloud app version:
3.1.0
Nextcloud server version:
13
#### Web server error log
N/A
Insert your webserver log here
N/A

#### Nextcloud log (data/nextcloud.log)
N/A
Insert your Nextcloud log here
N/A

**Comment by tobiasKaminsky** [comment]
Similar to #2677 this is something that needs to be done in server.
We currently supply nc://login/ urls with server address, user and password as parameters, so if you have a qr code that provides this, it can used with our app.

Please open up an issue on server repo.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky @nicobo Imho this isn't needed at all anymore since we now have the login via the webview, so @nicobo when you login with your password the server will generate a token/app-password and the Android client uses that one. So no need to manually create any app-passwords.

**Comment by AndyScherzinger** [comment]
@apiraino you don't need to find the app token. When you login in the Android app, it'll generate the app token and the Android app then uses it automatically. This is all done completely in the background.

As for the QR code. That feature hasn't been released yet but is still in development by @tobiasKaminsky

**Comment by apiraino** [comment]
> When you login in the Android app, it'll generate the app token and the Android app then uses it automatically

So, if I understand correctly, the workflow is the following:
1. login from the Android App using username/password
2. a token is generated by the server and used to authenticate all subsequent requests, it's an Authorization token?

If yes, then I don't understand how to fill the App-Token field on the login screen of the Android app

**Comment by AndyScherzinger** [comment]
Correct, yes. Can you post a screenshot of.the login page?

**Comment by apiraino** [comment]
On the login page I click "Alternate login via App-Token" and I'm taken to this page

![screenshot_20190113-231203](https://user-images.githubusercontent.com/6098822/51091319-8c1a4100-1789-11e9-8c82-728b7e32cfc1.png)

**Comment by AndyScherzinger** [comment]
> If yes, then I don't understand how to fill the App-Token field on the login screen of the Android app

You chose to type in the app-token yourself which means you need to create the app-token yourself via the web user interface and type it in here. The easier way would jsut be to simply login with the password (like stated before, which auto generates the app-token in the background).
