### ISSUE TITLE
Nextcloud android app sorting files to upload not working

### ISSUE THREAD

**Issue by Matei-Ciobotaru** [nextcloud/android#2692]
### Actual behaviour
When trying to upload files by the Nextcloud Android app, the sort function does not work, as in it does not sort anything...

For clarity, I've shared a screen recording with the issue [here](https://nimbus.go.ro/cloud/index.php/s/KgG9JzmQYaBjEZe)

### Expected behaviour
Seeing how the app has a "sort" menu while browsing the phone filesystem, one would expect it to sort files by provided criteria.
 
### Steps to reproduce
1. From the Nextcloud Android app, hit upload files
2.  Go to a path on your phone where you have multiple files
3. Hit the three vertical dots on the upper right corner and try to sort cet files.

### Environment data
Android version: Android 7.0, kver: 3.18.14-12365438

Device model: Samsung Galaxy S7 G930F

Stock or customized system: Stock

Nextcloud app version: 3.1.0

Nextcloud server version: 13.0.2

#### Web server error log
```
No entries logged in web server log as this is a client side issue.
```

#### Nextcloud log (data/nextcloud.log)
```
No entries logged in Nextcloud log as this is a client side issue.
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
Hi @Matei-Ciobotaru,
this has been fixed for the upcoming release already, see #2566
You can either wait for the release (likely next week) or use the actual release candidate (register as a tester on GPlay, or manually update on f-droid).
