### ISSUE TITLE
Panic button support

### ISSUE THREAD

**Issue by ZJaume** [nextcloud/android#2697]
### Actual behaviour
Nextcloud app does not appear on the list of apps responding to Ripple panic button

### Expected behaviour
Nextcloud app appearing on the list and having the option to configure behaviour. The options could be:

- Hide the app
- Logout from nextcloud
- Erase all offline stored data on the device.

 
### Resources
https://guardianproject.info/2016/01/12/panickit-making-your-whole-phone-respond-to-a-panic-button
https://dev.guardianproject.info/projects/panic/wiki

**Comment by tobiasKaminsky** [comment]
Never head from this before.
Shouldn't a proper device protection be sufficient, instead of adding to each and every app some kind of destructive mode?

**Comment by ZJaume** [comment]
I think this is a second layer of security, in case lock screen security is bypassed. In some cases, the user could be forced to reveal the password. If the user prevents this situation, the user can trigger the panic button before, to hide some apps or make some data unrecoverable.

**Comment by joshtrichards** [comment]
The mentioned project hasn't had any activity since 2018 and it's apps aren't compatible with any modern versions of Android. Closing for now since this hasn't seen any other traction here in 5 years. Can always revisit if things change.
