### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by blackcrack** [nextcloud/android#27]
### Actual behaviour
-Tell us what happens
google apps only
### Expected behaviour
-Tell us what should happen
 should be also in F-Droid Markedplace

### Steps to reproduce
- no steps

### Environment data
Android version:
all ;)
Device model: 
all ;)

(but the "muster/sample "  it's really good on the issue list :+1:  :)

best regards
Blacky

**Comment by AndyScherzinger** [comment]
Hi @blackcrack thanks for reporting, this is already in the making, please see #10 thus closing this issue as duplicate

cheers
Andy

**Comment by blackcrack** [comment]
eh ja, sorry, have this see in f-droit by this minute !
sorry for reporting as issue :\ *bG*
holy crap, do you be fast *bg*

best regards
Blacky

**Comment by AndyScherzinger** [comment]
Joah, kein Stress :grin:

**Comment by blackcrack** [comment]
hihi :) (man könnte ja meinen du bist ne AI \*bg\* wegen der Geschwindigkeit ..)
because f-droid, i have think me also something :)

best regards
Blacky

**Comment by AndyScherzinger** [comment]
hehehe. I am not. Would be awesome since the AI would then also extend the apps functionality :D

**Comment by blackcrack** [comment]
hihihi a buddy programming in "M" (MUMPS) and he have programming a AI in Puppy with M ..
so, it's also possible hehehe.. so.. well... humm.. a ai, self learning and user-supporting thing.. oh well, would be a suggestion .. and maybe in M .. or in # because the Reactos-webconnectivity.. if we thinking this further .. so.. just for fun .. a personally Bot with AI with a Girlvoice who be a "partner/service" in live and web.. and all where be your' handy, inclusive reminding per telephoning call from your  Service AI-Bot with Girlvoice like a wachdog and it is fully running on you saved space at home in the basement server and save you data and all information ... but interacting with you like a hot Girl/hot chick.... uuhhh i become goose skin ! ... \*bg\* A dream from all geeks, like i guess..
bad becomes if she goes jealous, if you become a other Girlfrend *\lol\* uhuh...
best regards
Blacky
