### ISSUE TITLE
Do not use Device class from evernote

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#2701]
According to https://github.com/evernote/android-job/issues/465#issuecomment-396294657, we shall not use Device as this is an internal class.

https://github.com/nextcloud/android/blob/f733f7b0bb7172cdc845ea1cceace9d54f0930ab/src/main/java/com/owncloud/android/utils/ConnectivityUtils.java#L99-L101

can be replaced by

```
ConnectivityManager cm = (ConnectivityManager)context.getSystemService(Context.CONNECTIVITY_SERVICE);

NetworkInfo activeNetwork = cm.getActiveNetworkInfo();
boolean isConnected = activeNetwork != null &&
                      activeNetwork.isConnectedOrConnecting();
```
(https://developer.android.com/training/monitoring-device-state/connectivity-monitoring)

But we also use `Device.getNetworkType(context).equals(JobRequest.NetworkType.UNMETERED)`

What could we use for this, @mario?

And 
https://github.com/nextcloud/android/blob/7fb487f7172ebfd334e52da1d3dcc7429bce34e7/src/main/java/com/owncloud/android/files/services/FileUploader.java#L975

needs also to be replaced with:

```
IntentFilter ifilter = new IntentFilter(Intent.ACTION_BATTERY_CHANGED);
Intent batteryStatus = context.registerReceiver(null, ifilter);

// Are we charging / charged?
int status = batteryStatus.getIntExtra(BatteryManager.EXTRA_STATUS, -1);
boolean isCharging = status == BatteryManager.BATTERY_STATUS_CHARGING ||
                     status == BatteryManager.BATTERY_STATUS_FULL;

// How are we charging?
int chargePlug = batteryStatus.getIntExtra(BatteryManager.EXTRA_PLUGGED, -1);
boolean usbCharge = chargePlug == BatteryManager.BATTERY_PLUGGED_USB;
boolean acCharge = chargePlug == BatteryManager.BATTERY_PLUGGED_AC;
``` 
(https://developer.android.com/training/monitoring-device-state/battery-monitoring)

**Comment by AndyScherzinger** [comment]
:+1: especially since this is recommended by the lib dev himself :+1:

**Comment by joshtrichards** [comment]
All final traces of a dependency on the Evernote job scheduler were removed in #5986 and some prior related work for battery stuff in #4078.
