### ISSUE TITLE
Preferences is crashing

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#2702]
On master, I cannot access preferences anylonger, this is crashing:
https://github.com/nextcloud/android/blob/122e2c47ab80f11bedabe4b669d24424642731e1/src/main/java/com/owncloud/android/ui/activity/Preferences.java#L790-L794

Can someone check, if this also occurs for him?

**Comment by AndyScherzinger** [comment]
Just tested and app is also crashing on my device when opening the settings.
