### ISSUE TITLE
SD Card cannot delete File after upload to Cloud

### ISSUE THREAD

**Issue by Iam2fast4u2catch** [nextcloud/android#2707]
### Actual behaviour
- Tell us what happens
I Choose Upload file to Nextcloud AND delete File after Sucessfully upload.
It cant delete OR Mover files that are on a SD Card after upload to Cloud ,when retry i have Duplicated Movies / Photos on Cloud.

### Expected behaviour
- Tell us what should happen
 Automatic DELETE Movies/Photos/Files from SD Card on Mobile (Galaxy S7 Edge. Android 8.0 and Ported S9+ Rom.
Not possible to let app delete due to Insuccfient Write rights for App on the SD Card.

### Steps to reproduce
1. Select File for upload
2. Choose DELETE after Upload
3. Upload

### Environment data
Android version:
8.0

Device model: Galaxy S7 Edge ,Ported S9+ Rom

Stock or customized system: Customized S9+ Rom

Nextcloud app version: 3.2.0

Nextcloud server version: Actual Version

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by M4xTheMan** [comment]
I've the same issue on Lineage OS 14.1 / Android 7.1.2 / Samsung Galaxy S7.
