### ISSUE TITLE
Nextcloud Android account sync failing

### ISSUE THREAD

**Issue by prilly** [nextcloud/android#271]
### Actual behaviour

Running nextcloud app on a samsung s3. the created sync account is running and running, never completing a sync. this result in huge power drain and data usage.
### Expected behaviour

the sync account should complete the sync
### Steps to reproduce
1. install nextcloud android app
2. activate account sync
3. watch it drain your battery and dataplan for all eternity
### Environment data

Android version:
4.3
Device model: 
samsung s3
Stock or customized system:
stock
Nextcloud app version:
1.3.0
Nextcloud server version:
10.0
#### Web server error log

```
Insert your webserver log here
```
#### Nextcloud log (data/nextcloud.log)

```
Insert your Nextcloud log here
```

**Comment by AndyScherzinger** [comment]
Strange, just tried it with a Nexus5X, Android N, Nextcloud server 10 and it took barely more than ~10 seconds.

**Comment by prilly** [comment]
I have 2 large samba shares attached to the nc server with alot of files, may that be the problem

-------- Opprinnelig melding --------
Fra: Andy Scherzinger <notifications@github.com> 
Dato:19.09.2016  23:42  (GMT+01:00) 
Til: nextcloud/android <android@noreply.github.com> 
Ko: Prilly <prilly@speedbox.me>,Author <author@noreply.github.com> 
Emne: Re: [nextcloud/android] Nextcloud Android account sync failing (#271) 

Strange, just tried it with a Nexus5X, Android N, Nextcloud server 10 and it took barely more than ~10 seconds.

**Comment by prilly** [comment]
Ok i think the problem can be related to the 2 samba shares i have added to NC, it contains around 1TB data and around 500K files, it seems the NC android app completes a sync but it takes around 5 hours.
There has to be something wrong with this implementation. if i remove the samba shares the file count drasticaly reduces and the sync completes within 1 min.

i have attached a screenshot from Android, this shows the battery consumption of this app, its huge.


![screenshot_2016-09-20-09-53-25](https://cloud.githubusercontent.com/assets/1522162/18661976/83344100-7f18-11e6-9233-2d812e4f9824.png)

**Comment by tobiasKaminsky** [comment]
I am unsure if this is really a bug or if it is just time (and battery) consumptive to have all those files scanned.
This is probably related to another issue, where it is discussed if a first complete sync is necessary.

**Comment by tobiasKaminsky** [comment]
While we surely can improve the sync the main reason for the battery drain is the giant sync folder.
