### ISSUE TITLE
3.2.0 automatic synch broken

### ISSUE THREAD

**Issue by stratege1401** [nextcloud/android#2710]
might be related to  #285  #2691 and maybe more
automatic upload once again broken by update.

To fix it, one again, had to cut/past all pics in DCIM to another location.
Stop the app, clear the cache.
cut/past back the files.
Restart the app.

**Comment by FredericMa** [comment]
Maybe #2612 is also related to this issue?

**Comment by tobiasKaminsky** [comment]
What devices / android OS version do you have?

**Comment by FredericMa** [comment]
@tobiasKaminsky I have a Samsung Galaxy S8 running android 8.0.0.
In issue #2612 you find a list of other peoples devices and OS that have the same issue.

**Comment by klm46** [comment]
COme on guys. This is a basic feature of an cloudsolution. it hust never works coreectly foor langer than a few days. it's a shame and it costs so much time. i think i need to change my cloud-solution at home because this is really a big big bug!

**Comment by stratege1401** [comment]
@tobiasKaminsky   

Smartphone 1: Wiko fever android 7.1.1 + NC 3.2.0
Smartphone 2: One+5 android 8.0 + NC 3.2.0
Smartphoen 3: One+6 android 8.1 + NC 3.2.0

**Comment by Raz0rsEdge** [comment]
S9+ Had been working for months but on Friday was taking a lot of pics and auto uploading over 4G and suddenly stopped now can't get it to work at all. Manual upload works and auto contacts backup upload works.

**Comment by Raz0rsEdge** [comment]
App ver 3.2.1 RC1 still auto upload not working.

**Comment by tobiasKaminsky** [comment]
I'll have an extensive debug session tomorrow with a Samsung S9+.

**Comment by Raz0rsEdge** [comment]
Cool let me know if you need anything from me :)

**Comment by Raz0rsEdge** [comment]
Have installed 3.2.1 stable same behaviour no auto uploading.
