### ISSUE TITLE
Back button doesn't work in sharing screen

### ISSUE THREAD

**Issue by karottenbaum** [nextcloud/android#2717]
### Actual behaviour
I can't use the system back button inside the sharing screen. If I press it, the text field stays focused and the app doesn't go back to the file list.

### Expected behaviour
The back button goes back to the file list.
 
### Steps to reproduce
1. Open sharing view on any file
2. Tap text field
3. Press back button

### Environment data
Android version: 8.1.0

Device model: Google Pixel 2

Stock or customized system: stock

Nextcloud app version: 3.2.0

**Comment by tobiasKaminsky** [comment]
For me this was also happening once or twice, but only after I searched for an user.
Then it helped to click on "x" on the right side of the search field.

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger as you implemented this, do you have an idea? :-)

**Comment by AndyScherzinger** [comment]
No idea right away but I can have a look at it

**Comment by schlagi123** [comment]
I have the same problem in the app verison 3.3.2. Everytime the searchfield is focused I can see this behaviour.

**Comment by tobiasKaminsky** [comment]
This seems to be affected only on Android <9.
So it seems that Android changed it behaviour.

**Comment by karottenbaum** [comment]
For me, this still happens on Android 9 (Nextcloud 3.3.2).
