### ISSUE TITLE
Add support for WLAN SSID, only use WLAN

### ISSUE THREAD

**Issue by IceBoosteR** [nextcloud/android#2719]
### Actual behaviour
- Automatic file upload & contacts backup does fail because I am not in my home WLAN, or I am not in WLAN at all.
- Please note that I can only access my Nextcloud instance when I am at home, it is not public available
### Expected behaviour
- Only use the backup and the automatic file upload when I am connected to a WLAN, and please add a function (as you can see in FileSync for example) to limit the upload to one or multiple specific WLAN SSIDs. So I can make sure that there are no tries when I am connected elsewhere.
- Use preferred timeslots to queue the upload/backup to a specific window (like daily at 6pm, or on every Sunday)
 
If anything is unclear or if this should be spillted into two tickets, please lemme know ;)

**Comment by klawdhfzasjhaa** [comment]
Please add this feature to contact's backup, too. Relates to #1626.

**Comment by joshtrichards** [comment]
Let's consolidate tracking this in #821. I encourage you to subscribe, add to the discussion, and/or upvote 👍 that issue
