### ISSUE TITLE
share file with dictadroid to nextcloud

### ISSUE THREAD

**Issue by JSoko** [nextcloud/android#272]
### Actual behaviour
share a dictate (*.wav) file with the share funktion od dictadroid http://www.dictadroid.com/ to a folder in the Nextcloud doesn't work.

### Expected behaviour
It should be possible to choose a folder and the file should be uploaded. This worked as expected until V1.3. With 1.3 where ther should be "choose the folder" there is "create Textfile" and I just have the possibility to create a Textfile and the dictate isn't uploaded.

Trying to share the same file wit other programs, p.e. Es-fileexplorer works as expected
![screenshot_20160919-120925](https://cloud.githubusercontent.com/assets/5583290/18629315/10ac707a-7e65-11e6-96ff-73b66e017c92.png)

 
### Steps to reproduce
1.  Start Dictadroid
2.  Create a dictate
3.  Press share
4. choose nextcloud
5. try to choose a uploadfolder

### Environment data
Android version:
6.01
Device model: 
Samsung Galaxy S7

Stock or customized system:
Stock
Nextcloud app version:
1.3
Nextcloud server version:
10.0.16
#### Web server error log
none
#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

**Comment by AndyScherzinger** [comment]
Hi @JSoko,

we found the issue and wrote a fix, see #274. We will prepare a release a version 1.3.1 as soon as the code review has been done.

Best regards,
Andy

**Comment by JSoko** [comment]
That was fast! Thank You!

**Comment by AndyScherzinger** [comment]
Fixed and to be released with 1.3.1, so closing it.
