### ISSUE TITLE
Loop display and wrong icon Parameters >>> Privacy

### ISSUE THREAD

**Issue by katacore** [nextcloud/android#2721]
When i go to Parameters, I open the Privacy item
- The top left icon is a list (but an arrow is expected) but it do return to Parameters when I tap it
- I get back to Parameters, I tap the top left arrow of Parameters and I return to Privacy, not to the main page.

### Environment data
Android version: 7

Device model: SM-G935F

Stock or customized system: STOCK

Nextcloud app version: 3.2.0

Nextcloud server version: 13

**Comment by AndyScherzinger** [comment]
I could reproduce this with my OP3T running Android 8.1.
So I seems to be a general issue.

**Comment by tobiasKaminsky** [comment]
I doubt that this is a good first issue as I fear this is related to "singleTop" and therefore not that easy so solve…

**Comment by AndyScherzinger** [comment]
I removed the label
