### ISSUE TITLE
Refactor search

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#2723]
This is a brainstorming issue.

Currently we have multiple "search" functionalities:
- name based search on server (in FileDisplayActivity)
- webdav search (e.g. favorites, shared) via DrawerActivity

Both result in a call to OCFileListFragment and this makes this fragment really huge.

So my idea is to separate this:
- NamedSearchResultFragment, which extends OCFileListFragment
	- get & store search result bound to lifecycle of this fragment
	- if you open enter a folder (which is a search result), go back, you will get back to the search result list
	- clicking back on search result list opens up root of server file list
- FixedSearchResultFragment, which extends NamedSearchResultFragment
	- no search view at all

Additionally searchView in FileDisplayActivity should just call the new fragments, if a search was entered, but not be responsible for anything else.

We can then easily swap/exchange the fragments, and all fragments have a (hopefully) more lightweight lifecycle.

What do you think?

**Comment by AndyScherzinger** [comment]
:+1: Sounds good to me, sure!

**Comment by tobiasKaminsky** [comment]
I will also have a look if it is possible, to show the already processed files.
E.g. you have a search result of 1000, then currently you see the result only after all 1000 results are processed.
--> Show them in a bunch of e.g. 20.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky shouldn't have  #2726 closed this issue?

**Comment by tobiasKaminsky** [comment]
No, this one is more broader approach, e.g. splitting up OCFileList is not done yet.

**Comment by jancborchardt** [comment]
The main issue I see with search at the moment is that it is so slow that it doesn’t seem to work. @tobiasKaminsky I think we talked about it at the Contributor Week – what would be great is:
- **Instantly filter the current view as you type** – this solves soo many cases already.
- In the background check anything which the app knows about, like cached/downloaded files etc. in other folders
- In the background also ask the server

**Comment by AlexNi245** [comment]
hello i'd like to pick this issue if its still relevant. As i got it right there are a refactoring part as described by @tobiasKaminsky  and add some  new features as described by @jancborchardt. if you agree i'd open two pull requests and then start working.

**Comment by jancborchardt** [comment]
@AlexNi245 that sounds great! @tobiasKaminsky @AndyScherzinger do you have any input? :)

**Comment by AndyScherzinger** [comment]
Except for what @tobiasKaminsky wrote, not from my side. Maybe Tobias has additional, further input on this one.

**Comment by tobiasKaminsky** [comment]
Still valid.
Thanks for taking this @AlexNi245 
(btw: we have a NC conference at https://nextcloud.com/conf-2019, maybe you want to join?)

**Comment by AndyScherzinger** [comment]
@jancborchardt can you add @AlexNi245 to the Android tem, so he can work with the repo directly? :) ❤️

**Comment by tobiasKaminsky** [comment]
Added

**Comment by joshtrichards** [comment]
Closing per this comment and hoping we're both right (unified search) :-) https://github.com/nextcloud/android/pull/4368#issuecomment-946354050
