### ISSUE TITLE
Selecting Favorites from the Favorites list shows empty folder

### ISSUE THREAD

**Issue by gradinaruvasile** [nextcloud/android#2725]
### Actual behaviour
- I tap on the Favorites link from the side menu on a favorite folder that has files in it
- The folder is shown empty

Although if at this point i press back, i will be take into the parent folder from where i can select the favorite fooder with no issues.

### Expected behaviour
- I tap on the Favorites link from the side menu on a favorite folder that has files in it
- The folder contents are shown
### Steps to reproduce
1. I tap on the Favorites link from the side menu on a favorite folder that has files in it
2. The folder is shown empty
3. 

### Environment data
Android version:
8.1.0
Device model: 
Lenovo K6 Power, Xiaomi Redmi 4A 
Stock or customized system:
Lineage OS (custom) 15.1 (lenovo), Stock MIUI (xiaomi)
Nextcloud app version:
3.2.0
Nextcloud server version:
13.0.4
#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
This is indeed a bug, which will be addressed with #2723.
Currently you can work around and use pull to refresh (swipe down).

**Comment by gradinaruvasile** [comment]
@tobiasKaminsky pull refresh doesn't work either. I have to "go back " which takes me to the parent folder then select the folder from there.

**Comment by tobiasKaminsky** [comment]
Indeed, https://github.com/nextcloud/android-library/pull/152 is also missing.
You can try this with tomorrows dev version, if you want.
