### ISSUE TITLE
After sorting can't choose file to upload

### ISSUE THREAD

**Issue by MeiRos** [nextcloud/android#2729]
### Actual behaviour
I try to manually upload a pic. In the camera folder, I sorted files and tapped a file. No check in the box. 

### Expected behaviour
The box should be checked when the file is chosen. 
 
### Steps to reproduce
1. +, Upload files, DCIM, Camera
2. Sort newest first
3. Try to choose a pic -> No check in the box
If I cancel now, and do the first step again (files are now sorted newest first), I get check in the box when the pic is chosen. 

### Environment data
Android version: 8.0.0 

Device model: Samsung s8 

Stock or customized system: stock

Nextcloud app version: 3.2.0 and dev 20180613 and dev 20180616

Nextcloud server version: newest 13

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

**Comment by AndyScherzinger** [comment]
Reproducible as mentioned by @MeiRos
