### ISSUE TITLE
Activity stream design enhancements on file detail

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#2737]
From https://github.com/nextcloud/android/pull/2690#issuecomment-397328377.

We are re-using the activity stream, which can be accessed via drawer -> activities, so each change will also affect the other stream:

![2018-06-20-135633](https://user-images.githubusercontent.com/5836855/41656896-c8e8bd78-7491-11e8-90e2-3493246be46f.png) ![2018-06-20-135644](https://user-images.githubusercontent.com/5836855/41656897-c9072786-7491-11e8-8fdd-04c307893d59.png)

> - The first line of the comment »Commented by you« is not really useful. It should simply say »You« instead

Needs to be done on activity app

> - Similar for the icon: Instead of the generic comment icon, it should show your avatar

Wouldn't it be better to have the big icon as "action icon" and just before "test" (user) we show the avatar?

> - And the comment text below should have the same text size as the normal text. We shouldn’t have too many different text sizes as that looks strange.

Currently we have 3 font sizes:
- Date (today, yesterday, monday, May 28)
- "action" (new version was created, you changed file, you commented)
- "value" (file size, comment text)

![image](https://user-images.githubusercontent.com/5836855/41657329-559179d0-7493-11e8-9c74-c9a9df17d42a.png)

--> action and value both in size of "action"?

> - We can remove the »Today« header – it’s not necessary to show that one. Should only start with »Yesterday«.

This will then also be in activity stream. Is this ok for you?

What about the bold text? Personally I do not like them at all.
(there is no thumbnail because the files are already deleted)

File details only:
do we want to hide the thumbnails, as the user knows which file he is viewing?
![2018-06-20-140942](https://user-images.githubusercontent.com/5836855/41657439-a5f5ecb2-7493-11e8-9050-2ea5813d5593.png)

@jancborchardt

**Comment by jancborchardt** [comment]
> Wouldn't it be better to have the big icon as "action icon" and just before "test" (user) we show the avatar?

It looks way nicer if the avatar is the big icon. :) Especially for comments, the comment icon itself is not really needed as for chat messages usually always the avatar is shown.


> action and value both in size of "action"?

Yes. :) However, we need to differentiate a bit with opacity, and ideally it would be:
- Full opacity for things like the action text, and for "value" which is actual content, like a comment text.
- Less opacity for main date header, time on right, and for "value" which is metadata, like file size. _And_ that less opacity should be a bit less than the current one. Let me know what the current one is and I’ll tell you what it should be. :) (If it’s more than 50%, make it that for a start)




      

> > We can remove the »Today« header – it’s not necessary to show that one. Should only start with »Yesterday«.
>
> This will then also be in activity stream. Is this ok for you?

Yup! :)


>  What about the bold text? Personally I do not like them at all.

Let’s keep this for now. It’s good to immediately show the focus of the activity. But yes, this is something we could rethink.


> File details only:
> do we want to hide the thumbnails, as the user knows which file they are viewing?

Good point. Yes, let’s hide it but only for when you view a file, and only when it’s a filetype icon. When it’s an actual preview (like for pictures) we should keep it, so you can directly see what changed (even though it’s small, the preview is useful) :)

**Comment by tobiasKaminsky** [comment]
> It looks way nicer if the avatar is the big icon. :) Especially for comments, the comment icon itself is not really needed as for chat messages usually always the avatar is shown.

Have you reported this to activity app as we only take their stream :)

> Full opacity for things like the action text, and for "value" which is actual content, like a comment text.

>Less opacity for main date header, time on right, and for "value" which is metadata, like file size. And that less opacity should be a bit less than the current one. Let me know what the current one is and I’ll tell you what it should be. :) (If it’s more than 50%, make it that for a start)

We have no real way to determinate the "type" of an activity. We would have to hardcode this somehow in it and this is something I do not want to do.
--> all "values" need to have the same opacity 

main date header, time on right: currently there is no opacity, but just a grey text color: #757575

**Comment by tobiasKaminsky** [comment]
> Good point. Yes, let’s hide it but only for when you view a file, and only when it’s a filetype icon. When it’s an actual preview (like for pictures) we should keep it, so you can directly see what changed (even though it’s small, the preview is useful) :)

Folder:
![2018-06-22-100057](https://user-images.githubusercontent.com/5836855/41765937-d9a7c242-7605-11e8-80e9-92eb91679b73.png) -> ![2018-06-22-100026](https://user-images.githubusercontent.com/5836855/41765932-d68c0a3c-7605-11e8-8856-b5f63d47092d.png) 

File without preview:
![2018-06-22-100131](https://user-images.githubusercontent.com/5836855/41765981-0086b76a-7606-11e8-8c2a-dc5b734d4049.png)

File with preview:
![2018-06-22-101919](https://user-images.githubusercontent.com/5836855/41766002-0b71a18a-7606-11e8-9ccf-a61c31dc2a58.png)

**Comment by tobiasKaminsky** [comment]
Same size of text:
![2018-06-22-094317](https://user-images.githubusercontent.com/5836855/41766029-26098ddc-7606-11e8-98b7-cbef08761152.png)

**Comment by jancborchardt** [comment]
Good stuff! Only one thing: Of course when viewing the activities of a single folder (just like single file) we also don’t need the icon. (I meant to say »when viewing a single file« (also including folders), not »only for _files_«. :)

**Comment by tobiasKaminsky** [comment]
Well, it is, or?
(in previous post I showed the old one on the left and the new on the right)

![2018-06-22-100026](https://user-images.githubusercontent.com/5836855/41765932-d68c0a3c-7605-11e8-8856-b5f63d47092d.png)

**Comment by jancborchardt** [comment]
> (in previous post I showed the old one on the left and the new on the right)

Aaah ok – then nevermind. :D All good :+1: :taco:

**Comment by tobiasKaminsky** [comment]
Thanks for your feedback, will be auto-closed with pr #2751
