### ISSUE TITLE
Exit as soon as internet is on

### ISSUE THREAD

**Issue by francois4444** [nextcloud/android#2759]
### Actual behaviour
- Tell us what happens
Version 0616
Both dev and prod show startup screen then exit. However does work if wifi is off
Android 5.0.2 medion lifetab 8' tablet
### Expected behaviour
- Tell us what should happen
 To work ?
### Steps to reproduce
1. 
2. 
3. 

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:
13.4 i think. Latest installed 3 days ago
#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

**Comment by francois4444** [comment]
I'll see what I can do, I don't think I have adb installed 

Le 25/06/2018 08:39, Tobias Kaminsky a écrit :

> Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].

 

Links:
------
[1]
https://github.com/nextcloud/android/issues/2759#issuecomment-399847417
[2]

**Comment by francois4444** [comment]
Hello sorry for the delay 

I have been experiencing some problems with the web access too lately,
so I digged a bit on the server side and I realized the problem is most
likely on the server side: 

[22-Jul-2018 15:46:42 UTC] PHP Fatal error:  Out of memory (allocated
23592960) (tried to allocate 3072 bytes) in
/home4/francois/public_html/cloud/lib/private/Preview/Watcher.php on
line 109
[22-Jul-2018 15:47:59 UTC] PHP Fatal error:  Out of memory (allocated
23330816) (tried to allocate 12288 bytes) in
/home4/francois/public_html/cloud/lib/private/Files/Node/Folder.php on
line 248 

So I guess you can probably close this bug for the time being. 

I will correct the problem on the server and test again. I guess it is
just happenstance (load on server ?) that I went thru with the phone and
didn't with the tablet. 

I'll let you know if I find anything else. 

Thanks for the (very) good job anyway :-) 

best regards, 

Frank 

Le 25/06/2018 08:39, Tobias Kaminsky a écrit :

> Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].

 

Links:
------
[1]
https://github.com/nextcloud/android/issues/2759#issuecomment-399847417
[2]

**Comment by AndyScherzinger** [comment]
Thanks for the update @francois4444, I'll close the issue for now. Please re-open if the issue comes back after the server is running smoothly again :)
