### ISSUE TITLE
No files shown

### ISSUE THREAD

**Issue by takiainen** [nextcloud/android#276]
Migrated from owncloud 8xx to nextcloud 9xx and then 10 beta. I can see all the files correctly via browser and linux desktop integration, but with latest fdroid nexcloud official android app I can't see any files. It shows the actual size of folder content, but inside it claims there's nothing. 

### Expected behaviour
Well nextcloud beta works correctly. It shows the files.
 
### Steps to reproduce
1. Install nextcloud android app
2. check your files
3. nothing

### Environment data
Android version:
6
Device model: 
Oneplus One
Stock or customized system:
Custom rom: Slim6.

Nextcloud app version:1.3.0

Nextcloud server version:10.0.1RC1

**Comment by AndyScherzinger** [comment]
@takiainen what do you mean by nextcloud beta? The Android beta app from f-droid?

**Comment by takiainen** [comment]
Yes, the android app: Nextcloud beta (Synchronization client) - https://f-droid.org/app/com.nextcloud.android.beta

**Comment by takiainen** [comment]
The new version from F-Droid seems to work fine. So issues is fixed.
