### ISSUE TITLE
Device credentials check when lock mechanism is deactivated within the app

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#2763]
Reported via the forum: https://help.nextcloud.com/t/nextcloud-dev-android-app-issue/33376
> I’ve been using the Nextcloud Dev app from FDroid for over a year now, with no real issues until the other day. Every time I go to open the app it asks me to re enter my device password, if I use fingerprint it says incorrect credentials so I have to type in my password before access the app.
> I am running version 20180622 according to the app, and I have no lock configured in the settings of the app.

**Comment by tobiasKaminsky** [comment]
Hm. Quite strange.
Is it helping to enable and disable lock from within the app?

**Comment by gitziom** [comment]
Same problem for me, Galaxy S5, android 6.0.1, cant use app because forcing credentials all the time.

**Comment by tobiasKaminsky** [comment]
@gitziom do you had some locking previously enabled within our app?

> cant use app because forcing credentials all the time.

It should only be requested on first start and then after a timeout.
Does it help to enable and disable lock within our app settings?

**Comment by skjnldsv** [comment]
I can reproduce! :)
I also have desactivated the security lock on the app but still gets requested my pattern.
Also, it keeps requesting the pattern or the fingerprint when enabled and always says  "bad credentials" or something like that

**Comment by freijon** [comment]
same here on Nextcloud Dev

**Comment by tobiasKaminsky** [comment]
We had a bug with fingerprint (un)lock mechansim. It affected only a few devices, e.g. Xiaomi, Motorola, …
As none of our test deices was affected, hunting this bug down took a while.

If any of you could download and install this apk (https://cloud.nextcloud.com/s/pCwRFo7rFF3MMjM) and test if it is now working better, I would appreciate it.
(the APK file is signed with the key for Google Play Store and is 3.3.2 Alpha 1, so this proves that it is an official version and can be easily upgraded. The up-to-come 3.3.2 version then can also just update this version).
