### ISSUE TITLE
Social Login App not allowing to log in

### ISSUE THREAD

**Issue by Dicafr** [nextcloud/android#2765]
### Actual behaviour
Using Google login option only (authorized url https://mydomain.com/apps/sociallogin/oauth/google)

The Nextcloud instance is being accessed through a web browser (computer) and Android app. Everything works great on the web browser (both computer and Android devices). The Google button is pressed and the user is redirected to the Nextcloud instance.

The problems start when trying to log in using the Android app. The button to login using Google is there as expected after providing the instance to acces. When pressed, it shows a login screen (I would have expected it to use the credentials of the account on the Android device). Once the user logs in, the web page version of Nextcloud is displayed and not the Android frontend. It's like the web page that is being displayed for login is never closed and the user is never really logged in. After about 30 seconds, at the bottom of the screen, the "go back to old login method" message shows up. Clicking on it brings the user back to the login page. (An example of this problem #1587 although the cause of the problem is different). If I disable the Google login, the problem disappears.

Is there anybody using the Social Login app on the Android app? I have tested on 4 different devices (HTC 10, Samsun S8, Motorola X Play And Asus ZenPhone 5Q. I haven't tested with the iOS version.

An initial report was posted on the Social App project ([here](https://github.com/zorn-v/nextcloud-social-login/issues/35) and it was suggested to report it here instead.

### Expected behaviour
To be able to use Social Login's login method to log in to my instance of NextCloud.
 
### Steps to reproduce
1. Install Social Login app
2. Create OAuth2 Client IDs on Google API Console
 a. Create a new project
 b. Create a new web app
 c. Set "Authorized redirect URIs" to https://mydomain.com/apps/sociallogin/oauth/google
3. Back in the NextCloud instance, logged in as an Admin, go to Settings -> Social login
4. Under the Google section, provide the App ID and the secret that were created at step 2
5. Set the new user access to a group that doesn't have access to anything
6. From the Android App, provide the instance to connect to on the first screen
7. On the login page, scroll down and select the Google button
8. A Google login will be displayed. Provide Username and Password
9. Redirected to web version of NextCloud (not the Android App) and "go back to old login method" message shows up at the bottom of the page after less then a minute which will bring the user back to the initial screen to provide the instance.

### Environment data
Android version: 8.0.0

Device model: HTC 10

Stock or customized system: Stock

Nextcloud app version: 3.2.0 and beta verison

Nextcloud server version: 13.0.3

Social App version: 1.8.0

#### Web server error log
no errors

#### Nextcloud log (data/nextcloud.log)
Going through the logs unfortunately doesn't show any new logs that are generated on login attempt.

**Comment by tobiasKaminsky** [comment]
@nextcloud/server-triage do you know if this app is fully supported with our weblogin flow? If so, then it should work and not redirect to the wrong page at step 9.

**Comment by MorrisJobke** [comment]
This seems to be an issue with the social login app: https://github.com/zorn-v/nextcloud-social-login

Please report it there and if the maintainer has question they can ping one of the people in @nextcloud/server-triage and we can help out.

**Comment by tobiasKaminsky** [comment]
@MorrisJobke https://github.com/zorn-v/nextcloud-social-login/issues/35 was redirected to this ;-)

**Comment by MorrisJobke** [comment]
> @MorrisJobke zorn-v/nextcloud-social-login#35 was redirected to this ;-)

But then we need to check what the social login does wrong regarding the login flow. Which is completely on the server. Let me comment there.

**Comment by Dicafr** [comment]
zorn-v/nextcloud-social-login#35 fixed Tested and working!

Awesome support, people. Very impressed!
