### ISSUE TITLE
Stuck when upload some files

### ISSUE THREAD

**Issue by Astrubale** [nextcloud/android#2792]
### Actual behaviour
- App stopped working when trying to upload 7000+ images in one shot.

### Expected behaviour
- App doesn't upload anything and freeze for a couple of seconds. 
  After scking for "Send feedback" it starts working again but doesn't upload selected files.
 
### Steps to reproduce
1. Open a folder
2. Select a lot of files to upload in one shot
3. Tap on "upload"

### Environment data
Android version: 8.1.0

Device model: OnePlus 6

Stock or customized system: Stock OxygenOS

Nextcloud app version: 3.2.0

Nextcloud server version: 13.0.4

# Logs
- No logs, sorry

**Comment by tobiasKaminsky** [comment]
Yes, this is a know bug, which is partly solved by #2460, but then it crashes a step later.
So currently there is only the workaround to upload them in batches.
