### ISSUE TITLE
Screen adapted image is loading a very long time

### ISSUE THREAD

**Issue by Django3** [nextcloud/android#2793]
Hi there,

i have the following problem:
The screen adapted images should be about 50-100kb. In my case i had to wait 25 to 40 seconds to see it. 100kb should normaly be loaded in 1 second ;) - i am also using the preview generator so there should be nearly no work for the server.

How can i check/debug where the cause for this issue is?

Btw. a small improvement suggestion: wouldn't it be better to load always at first the thumbnail and then the adapted image? So if the adapted image need more time to load you can already see the thumbnail.

NC app: 3.2.0
NC Server: 13.0.4

Best regards!

**Comment by Django3** [comment]
What i recognized during some tests. If i swipe fullscreen through the thumbnails and then stop at a picture i like, it seems the app is first loading all the other pictures i swiped through and finaly the picture i stopped.

1 -> click on a folder with pictures where the screen adapted image is not downloaded yet
2 -> then swipe a few times to one direction
3 -> then wait until the adapted image is downloaded from the current picture and swipe immediately back
4 -> you can see the other adapted images are downloaded already

If you only wait a few seconds at point 3 and swipe back, you can see that the first adapted images where you started to swipe are already downloaded.

In my opinion the current file should always be preferred in the background download cue to make it more seamless and reduce waiting time.
What do you think about that?

**Comment by tobiasKaminsky** [comment]
If there is a thumbnail available, it is is shown, until resized image is loaded.
Indeed 40-100kb should not take that long.
Are the images in question loading fast on web ui? (this is also using preview generator, so we can rule this out).

Regarding loading order:
Currently there is no such logic, it is simply doing it in order. 
Changing the queue would indeed help.

**Comment by Django3** [comment]
> Changing the queue would indeed help.
If it is not a disadvantage for another function, this would be great to implement ... especially for users which often handle with photos on NC.
Set the current file at the top of the queue and not at the end ... so reversing the queue.

> Are the images in question loading fast on web ui?
They are loading a few seconds faster but also too long. For a (5,7MB original size) picture about 17 sec. in web ui and about 23 sec. in the app. That means there is something wrong with my preview generator right?

**Comment by tobiasKaminsky** [comment]
@rullzer as you are the master of preview generator :-)

**Comment by tobiasKaminsky** [comment]
Is this still happening?
We changed the queue so that it should be faster…
