### ISSUE TITLE
combine lint/findbugs tables into one table each

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#2799]
see examples:

<h1>Lint</h1>
<table width='500' cellpadding='5' cellspacing='2'>
<tr class='tableheader'>
<th align='left'>Type</th>
<th align='right'>Master</th>
<th align='right'>PR</th>
</tr>
<tr class='tablerow0'>
<td>Warnings</td>
<td align='right'>92</td>
<td align='right'>92</td>
</tr
<tr class='tablerow1'>
<td>Errors</td>
<td align='right'>0</td>
<td align='right'>0</td>
</tr>
</table> 

<h1>FindBugs</h1>
<table width='500' cellpadding='5' cellspacing='2'>
<tr class='tableheader'>
<th align='left'>Warning Type</th>
<th align='right'>Master</th>
<th align='right'>PR</th>
</tr>
<tr class='tablerow0'>
<td>Bad practice Warnings</td>
<td align='right'>35</td>
<td align='right'>35</td>
</tr>
<tr class='tablerow1'>
<td>Correctness Warnings</td>
<td align='right'>166</td>
<td align='right'>166</td>
</tr>
<tr class='tablerow0'>
<td>Experimental Warnings</td>
<td align='right'>4</td>
<td align='right'>4</td>
</tr>
<tr class='tablerow1'>
<td>Internationalization Warnings</td>
<td align='right'>12</td>
<td align='right'>12</td>
</tr>
<tr class='tablerow0'>
<td>Malicious code vulnerability Warnings</td>
<td align='right'>9</td>
<td align='right'>9</td>
</tr>
<tr class='tablerow1'>
<td>Multithreaded correctness Warnings</td>
<td align='right'>9</td>
<td align='right'>9</td>
</tr>
<tr class='tablerow0'>
<td>Performance Warnings</td>
<td align='right'>158</td>
<td align='right'>158</td>
</tr>
<tr class='tablerow1'>
<td>Security Warnings</td>
<td align='right'>163</td>
<td align='right'>163</td>
</tr>
<tr class='tablerow0'>
<td>Dodgy code Warnings</td>
<td align='right'>208</td>
<td align='right'>209</td>
</tr>
<tr class='tablerow1'>
<td><b>Total</b></td>
<td align='right'><b>764</b>
<td align='right'><b>765</b></td>
</td>
</tr>
</table>

**Comment by tobiasKaminsky** [comment]
Lint is improved, for FindBugs I need a good idea or some bash inspiration ;-)

**Comment by AndyScherzinger** [comment]
:+1: fine by keeping as-is since it doesn't seem to be worth the time...

**Comment by tobiasKaminsky** [comment]
Well, for rainy sunday evenings… ;-)
