### ISSUE TITLE
Bug: Freezes up on Uploading

### ISSUE THREAD

**Issue by c0fe** [nextcloud/android#28]
Server: OwnCloud 9.0.2
App: NextCloud
Server Host: HostGator

At random the files would not be uploading, or some do upload while the status shows 0% uploading.

This occurs on a Google Nexus 6P with all updates installed.

**Comment by tobiasKaminsky** [comment]
Unfortunately this is too unspecific to fix this problem.
Can you try to find the reason? Similar file type? Slow internet? Wlan? Mobile?

**Comment by c0fe** [comment]
Wireless, as I said Google Nexus phone. No wireless interference. And fast internet with 100mbps down and 12 mbps up. Doesn't matter file type. Can be XML or can be jpg

**Comment by tobiasKaminsky** [comment]
hmm...IPv4 or 6?
Can you try it with "official" demo server of owncloud: demo.owncloud.org?

**Comment by c0fe** [comment]
Both, IPv4 and IPv6 I have used various wireless networks.

Is the login credentials, user: test password: test ?

**Comment by tobiasKaminsky** [comment]
> Is the login credentials, user: test password: test ?

yes

**Comment by c0fe** [comment]
Attempted, frozen up on the 9th photo that was being uploaded.

I tried reuploading the total of 14 photos a second time and it all went through fine.

**Comment by c0fe** [comment]
I believe I have solved the bug. What occurs is this. I didn't notice this because my previous phone was a Samsung Galaxy S3. But anyways, the files will upload apparently with no issue as long as the application is still visible in the recent pages section. On Google Nexus 6P there is a tab where it shows all the recent applications visited which also apparently means they are running in memory and their tasks are tied to that. If you swipe out Nextcloud, the uploading just freezes. 

I am not sure if this is a bug, misunderstanding or if it can be improved where the files selected to upload would continue to upload after the app is swiped off from the recents or if a dialog message warning can pop up.

**Comment by tobiasKaminsky** [comment]
I doubt that we can do something on this.
But I will investigate further.

**Comment by c0fe** [comment]
I am curious if it be setup to operate like automatic backup does, at least I haven't noticed NextCloud app window when auto upload is enabled.

**Comment by tobiasKaminsky** [comment]
What do you mean? Normally this should be a background task that is started by the app.
There is no need to see an window when uploading, though you see an upload notification.

Do you have any task manager/battery optimizer/whatever running? Or maybe your phone has something build in...?

**Comment by thorian93** [comment]
Could it be an issue on how the app handles the upload?
Is it just one mechanism that manages automatic uploads and manual uploads?
Because @c0fe eliminated the server component as the problem because both his and the owncloud demo server won't work properly. Connectivity seems not the problem either because his wireless connections seems fine.

I recall having basically the same issue with an owncloud app about a year ago. But I can't tell what exactly caused the issue. Also I am not sure whether it has been fixed later because I use owncloud and will use nextcloud soon only for calendar and contacts and not for file upload.

Maybe investigating in the owncloud app and her former issues can help here.

**Comment by c0fe** [comment]
@thorian93 @tobiasKaminsky https://www.dropbox.com/s/pu5ncyxmncc9pud/Screenshot_20160623-110622.png?dl=0

This is the screenshot of my phone's recent tab. You can see Chrome and Nextcloud App in it. If I swipe left, the tab would be closed. What this does with the app itself I am not sure, if it shuts it down entirely or just removes the tab. But that being said once i swipe it away the uploading ceases.

**Comment by AndyScherzinger** [comment]
@c0fe that is kind of a works as design at the moment. When you swipe the app away you basically terminate it and with it the uploading. Right now the app doesn't do any auto-resume during the next startup but expects the user to open the upload screen via the top left menu and hitting the resume (top right menu)

**Comment by c0fe** [comment]
@AndyScherzinger yeah i was thinking that might be it but wasn't sure since my other phone didn't do this. I thought that the uploading would be a background process separate from the app itself. So once it was concluded it would just shut down on its own.

**Comment by AndyScherzinger** [comment]
Unfortunately I think it is something in between. @tobiasKaminsky One thing that doesn't fix this but would at least add some more automation would be that when the app starts and uploads weren't successful that the app in case of connectivity simply restarts the uploads. What do you think? cc @przybylski

**Comment by thorian93** [comment]
I just made a few steps into android app development yet, but wouldn't a background service for uploads be best? Because as a user I would assume, that a upload I trigger goes through, no matter what.

**Comment by AndyScherzinger** [comment]
Yes that would be best but we would still have to implement a restart resume mechanism due to the Android N doze function which terminates your app so the app needs to handle doze.

**Comment by AndyScherzinger** [comment]
Closing since this will be covered by #285
