### ISSUE TITLE
Rephrase "Lock" term to make it clearer that it is a app access restriction

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#2806]
see https://help.nextcloud.com/t/android-client-pin-fingerprint-protection-pointless/33590/2 

The thread shows that the access restriction we have is/can be misinterpreted as a file access restriction while it is a app access restriction. So I think we should thus show this fact as in maybe renaming "Lock" to "App access restriction" or something like that. Not a native speaker so maybe @nextcloud/designers or @mario @tobiasKaminsky have a better term to be used here :)

**Comment by tobiasKaminsky** [comment]
To make it a bit clearer what we are talking about (for others):

This protects the app from starting without entering correct pin/device credentials (fingerprint, password, …).
It is not meant to protect downloaded files on internal storage.

![2018-07-05-142954](https://user-images.githubusercontent.com/5836855/42323282-e92e26fc-805f-11e8-9bc9-5dd407d614b2.png) ![2018-07-05-142957](https://user-images.githubusercontent.com/5836855/42323281-e9105794-805f-11e8-87ac-fa4ed4e971f0.png)

Suggestion:
- app protection
- App lock
- Lock, but with a text "prevents unauthorized people from using app"

**Comment by AndyScherzinger** [comment]
Sounds good to me :+1:
