### ISSUE TITLE
Favorites of External Storages not showing

### ISSUE THREAD

**Issue by Refhi** [nextcloud/android#2809]
### Actual behaviour
- Folders/files stored on an external storage it's not shown in the "Favorite" tab.
- Working fine with other files, or when checking on the web interface

### Expected behaviour
- I should be able to see any favorite in the so-called tab.
 

### Environment data
Android version: Android 7.1.2 aosp_hammerhead

Device model: Nexus 5

Nextcloud app version: 3.2.0

Nextcloud server version:13.0.4

**Comment by tobiasKaminsky** [comment]
@nextcloud/server-triage do you have an idea how this can happen? We basically do a webdav search
