### ISSUE TITLE
Allow also upload on mobile data if user wants so

### ISSUE THREAD

**Issue by theel0ja** [nextcloud/android#2810]
### Actual behaviour
- "Waiting for Wi-Fi" and no toggle to turn off that

### Expected behaviour
- I would like to have option to also upload on mobile data.
 
### Steps to reproduce
1. Enable auto picture uploads
2. take a picture
3. go to "Uploads" menu and see "Waiting for Wi-Fi"

### Environment data
Android version: Android 8.0 (Samsung)

Device model: Samsung A3 (2017)

Stock or customized system: stock

Nextcloud app version: 3.2.0

Nextcloud server version: 13.0.4

**Comment by AndyScherzinger** [comment]
Hi @theel0ja , 
can you check your settings for that specific folder within the auto upload screen, in particular if the upload on unmetered wifi only option is active and if so deactivate it?

**Comment by theel0ja** [comment]
Oh! Found it!

On July 9, 2018 10:31:02 AM GMT+03:00, Andy Scherzinger <notifications@github.com> wrote:
>Hi @theel0ja , 
>can you check your settings for that specific folder within the auto
>upload screen, in particular if the upload on unmetered wifi only
>option is active and if so deactivate it?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/nextcloud/android/issues/2810#issuecomment-403386227

-- 
Sent from my Android device with K-9 Mail.

**Comment by AndyScherzinger** [comment]
@theel0ja thanks for the feedback :heart:. So closing the issue for now. Please reopen if you still experience an issue regarding auto upload and the wifi-only preference switch.
