### ISSUE TITLE
Nextcloudpi (https://nextloudpi.local): Could not find host 

### ISSUE THREAD

**Issue by java-py-c-cpp-js** [nextcloud/android#2816]
After installing the recent version of Nextcloudpi and the recent Android App from FDroid (3.2.0), i can't login locally getting the error message "Could not find host" directly after entering the local server address https://nextcloudpi.local.

**Comment by tobiasKaminsky** [comment]
Is the same url working with a browser on mobile?

**Comment by tobiasKaminsky** [comment]
If it does not work within a browser, then there is some other issue. Maybe routing? 
Can you verify with other devices that the nextcloudpi.local address is working?

As I have no experience with nextcloudpi, it is better to ask on their specific forum.

Once it is a real problem with the app, please re-open.
