### ISSUE TITLE
activities: Confusing info icon shown in Activities activity

### ISSUE THREAD

**Issue by ardevd** [nextcloud/android#2822]
When displaying the activities activity I now get a weird gray strip up top with an info icon that doesnt seem to do much. What gives?

![device-2018-07-13-102854](https://user-images.githubusercontent.com/366855/42681307-990e261c-8687-11e8-87f3-1800a2d0ba42.png)

**Comment by ardevd** [comment]
I'm assuming this will be fixed by #2818. Closing for now.

**Comment by AndyScherzinger** [comment]
@ardevd can you confirm that #2818 fixed this issue? :)

**Comment by ardevd** [comment]
@AndyScherzinger Just tested. It seems to have fixed the issue, yes. :)

**Comment by AndyScherzinger** [comment]
Sweet :smiley:
