### ISSUE TITLE
please downgrade googleLibraryVersion to 9.6.* to fix MicroG support

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/android#2824]
https://github.com/nextcloud/android/blob/dd6f7c824e7c41ca78ff14e6b475220f9a9cb04e/build.gradle#L39

See https://github.com/nextcloud/talk-android/commit/e724cd045a09d21893a6fcb74818fb148b32578b

**Comment by tobiasKaminsky** [comment]
With #2825, I wanted to update them to 15.
Is there some background, why 9.6.x is needed? 
Is this for both gcm and firebase?

**Comment by mario** [comment]
@tobiasKaminsky currently yes. This is needed because the client libs of newer versions don't work well with the MicroG service.

**Comment by mario** [comment]
See my comment: https://github.com/nextcloud/android/pull/2825

**Comment by tobiasKaminsky** [comment]
Going back from 12.x (Mar 2018) to 9.6.x (Apr 2017), while having 15.x (May 2018) is something I do not feel comfortable about.
Are there some information from microG side, if and when they will fix this, maybe a bug link?
