### ISSUE TITLE
very slow opening apps when using local copy only

### ISSUE THREAD

**Issue by bahbarnett** [nextcloud/android#2828]
I'm often without internet access.  For those cases, I have files tagged as available offline.

When I do end up offline, I get a message/prompt, stating that the app must make use of its local copy.  I'm sorry I don't have the message right now, but it is along the lines of "can't fetch newest version, using local copy".

Up until this point, all is fine.

However -- it now takes around 30+ seconds, maybe even a minute to open the file.  It's all nextcloud here, since I know immediately when the file is to be opened -- I have no defaults set, and it prompts for what app to use to open (for example) a PDF or JPG.

I don't know why the delay exists, but Nextcloud android app should, once it knows it is opening the local copy only, immediately do so.  Not pause for 30 seconds, 1 minute.
 
I've seen some other reports, with similar issues -- but, none of them refer to the app *knowing* it is offline, saying it will open the local copy, then pausing for a minute to do so....

**Comment by ardevd** [comment]
Thanks for reporting the issue. Could you provide a step-by-step guide on how to reproduce the issue?

**Comment by bahbarnett** [comment]
- test using any file set as "available offline"
- have no internet access (eg, turn on airplane mode)
- click on file to open it

You will now wait ~ 65 seconds, with "Fetching most recent version of the file." on your screen.  There is even a further maddening delay of 5 seconds or so, where a "using old version of file" is shown at the bottom of screen.

After this all passes, you will be able to view the old version of the file.

Understand that, for example, you may often need to look through many documents quickly.  I was at the airport, and had to search through 8 documents to find an obscure number I needed.

Timeout in such a case should be much, much, much less.  Say -- a few seconds at most?  Alternatively, a way to just view a cached file should be available.  EG, long click/hold menu?

Even better for it to realise that you'll never get a file, when the phone has no network connection.

And most maddening of all.. I was (as mentioned) looking for something at the airport.. so, if you close the file and re-open?  Same behaviour.

**Comment by AndyScherzinger** [comment]
@bahbarnett which version of the app are you using?
@tobiasKaminsky I though you fixed this in some of the younger releases, didn't you? Can't find it atm.

**Comment by bahbarnett** [comment]
Version in about->settings says 3.2.1.

Note that I am using a VPN, in case that makes a significant difference in online/offline detection.  Yet even if it does, connectivity issues should not result in this behaviour either.

For example, I'm often online but unable to connect anywhere with 4G / etc.  I hope for no 65 second delay there either...

**Comment by tobiasKaminsky** [comment]
I fear that the normal timeout is set…
There are many different "offline" modes:
- airplane
- really no mobile carrier, e.g. in a cellar
- mobile carrier available, but so poor that it is in fact no connection

For the first, it is really fast.

**Comment by bahbarnett** [comment]
sdgdf
