### ISSUE TITLE
Wording on dialog actions

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/android#2836]
Instead of generic words like "OK", "Yes" and "No" on dialogs, we should use specific action words:
- For deletion, the actions should be: "Delete", "Delete locally" (or something shorter?) and "Keep"
- For folder creation, it should be: "Create" and "Cancel"

![2018-07-19-143143](https://user-images.githubusercontent.com/5836855/42942548-8acb30f8-8b60-11e8-8deb-04af6f556515.png) ![2018-07-19-143153](https://user-images.githubusercontent.com/5836855/42942549-8ae5ed12-8b60-11e8-93d6-ed00446dd14f.png)
(Yes I took these screenshots from [your issue comment](https://github.com/nextcloud/android/issues/2835#issuecomment-406260398) @tobiasKaminsky ;)

**Comment by tobiasKaminsky** [comment]
Good idea, additionally on the left one, shouldn't the buttons be horizontal aligend?

**Comment by tobiasKaminsky** [comment]
@Morvidus thank you for your contribution!
Aligning the buttons horizontally would indeed be nice :+1: 
I am however not sure, if this work on all languages…

**Comment by jancborchardt** [comment]
@tobiasKaminsky is there something like a "Split button" where the action can be selected?

Compare to Bootstrap split buttons at https://getbootstrap.com/docs/4.0/components/dropdowns/#split-button-dropdowns


I made a quick mockup based on that. The goal is basically to make te dialog dead-simple (as it should be) by only showing 2 main actions, but still making the 3rd action "Delete locally" easily accessible and usable:
![screenshot from 2018-08-09 16-27-49](https://user-images.githubusercontent.com/925062/43905378-465631a6-9bf1-11e8-8f64-eddaa4038486.png)

- There’s only two actions visible, "Delete" as primary and "Keep" as secondary
- (This will likely make it work across languages regarding width concerns)
- Tapping on the main part of the button deletes the file
- Tapping on the right selection arrow enables you to change the default action between "Delete" and "Delete locally"
- The default action is remembered until it is changed again, making it very easy to e.g. only delete locally if that’s what you do.

**Comment by Morvidus** [comment]
@jancborchardt I had a quick look and found the 'Adding a List' part, it might be what you're suggesting?

https://developer.android.com/guide/topics/ui/dialogs#AlertDialog

**Comment by AndyScherzinger** [comment]
@jancborchardt @tobiasKaminsky unfortunately there is no standard component within Android or Material design for having a splitt-button. What could be done would be to have the triangle next to the (borderless?) button that shows a pop-up menu (like we do with the 3-dot menus) so a user can choose the action type, saving that in a preference in a background + setting the buttons text. Upon clicking the button we check the preference and trigger the corresponding action.

So looking at @jancborchardt's mockup we might always use borderless buttons, having "Keep" in black and "Delete" in the primary color (Nc blue or whatever the theme tells us) and have the triangle also colored according to the themes primary color.

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger your approach is a bit overkill in my opinion, but I also do not have better idea how to solve this :/

> having "Keep" in black and "Delete" in the primary color (Nc blue or whatever the theme tells us)

This might look strange if the primary color is white, then we switch to gray:
- primary action: gray
- secondary action: black

**Comment by AndyScherzinger** [comment]
From what I just understood from Jan's comment in another issue is that the text-button can all keep the primary color, so so grey/black/whatever mixture :)

**Comment by AndyScherzinger** [comment]
> your approach is a bit overkill in my opinion, but I also do not have better idea how to solve this :/

You mean the triangle thing? I also don't have a nicer idea. _If_ we want to implement a split-button when likely have to do it ourselves at the moment so the simplest way I could think of was a triangle drawable + a pop-up menu and having a preference for it since Jan mentioned that the choice needs to be saved and reused for any future actions when the dialog comes up thus it needs to be stored...

**Comment by AndyScherzinger** [comment]
This has been implemented a while ago, so closing.
