### ISSUE TITLE
Don't erase configuration after booting Android into Safe Mode

### ISSUE THREAD

**Issue by Sanookmakmak** [nextcloud/android#2843]
Android 5.0
Nextcloud App 3.2.0

After booting Android into Safe Mode and reboot again into normal mode all configurations and contacts are vanished.

Netcloud app has to be configured new and data has to be snced again.

More info: https://help.nextcloud.com/t/3-2-0-android-app-is-losing-configuration-after-android-safe-mode/34102

Nextcloud app is not working in Android Safe Mode.

**Comment by AndyScherzinger** [comment]
hmmm, need to look into this while the app itself doesn't touch your device's contacts. So the contacts removal must have happen/been done by another app or the OS itself :/

**Comment by tobiasKaminsky** [comment]
Nextcloud is not touching the contacts, unless you enable contacts backup. 
You can check if the permission flag is even set.

Getting the settings removed is indeed a problem.
