### ISSUE TITLE
Wrong resolution

### ISSUE THREAD

**Issue by ajtak-angelus** [nextcloud/android#2846]
I have problem on Samsung tablet (SAMSUNG Galaxy Tab S3) with Android (8.0). Sometimes it happends that display folders is not correct. They are diminished as if it detected another resolution. Thank You

![01](https://user-images.githubusercontent.com/19210976/43134117-3816a2ea-8f41-11e8-89bd-6e89325bfb23.jpg)
![02](https://user-images.githubusercontent.com/19210976/43134119-383ee502-8f41-11e8-9d33-5be1645b1bee.jpg)
![03](https://user-images.githubusercontent.com/19210976/43134120-3867b8c4-8f41-11e8-96ae-6b28fd4cfca4.jpg)

**Comment by ardevd** [comment]
Hi and thanks for submitting the issue.

I am struggling to understand what you are referring to. Would you be able to post actual screenshots (Press Volume Down + Power button) that illustrate the problem? I see no resolution issues in the images you posted.

**Comment by tobiasKaminsky** [comment]
@ardevd we have two "view modes": tablet and phone, which are decided at startup via screen width:
- tablet: two panes: left folder, right detail / image view
- phone: the regular one, most of us use/know

Now it seems that for $reason the app is switching from tablet view to phone.

**Comment by tobiasKaminsky** [comment]
@ajtak-angelus can you reproduce how and when this is happening? E.g. everytime when you view an image, …?

**Comment by ajtak-angelus** [comment]
Hello, I´m sorry for responding late. But it took me some time to work with that tablet again. I made printscreens (including tablet version and type) see attachement. And this how the display is everytime I open the nextcloud. Thank You

![screen1](https://user-images.githubusercontent.com/19210976/45420314-20fd1880-b68a-11e8-9326-577e5beade1a.jpg)
![screen2](https://user-images.githubusercontent.com/19210976/45420315-20fd1880-b68a-11e8-8c72-e4cbc4f8b9c3.jpg)
![screen3](https://user-images.githubusercontent.com/19210976/45420316-2195af00-b68a-11e8-8e1f-09a7aed6afd4.jpg)
![screen4](https://user-images.githubusercontent.com/19210976/45420317-2195af00-b68a-11e8-9471-53df41603d81.jpg)

**Comment by AndyScherzinger** [comment]
@ajtak-angelus thanks for the screenshots, the latest post of you shows the client layout as expected actually since the client uses a 2 pane layout for tablets so on the right side there woul dbe a display of the details, previews etc. the settings or auto upload and others are a 1 pane layout, so "just the file explorer view of the server side" has this 2-pane layout.
