### ISSUE TITLE
Contextual menu: unable to know that there are additionnal items

### ISSUE THREAD

**Issue by ldmpub** [nextcloud/android#2851]
### Actual behavior
If I choose a file in the "middle" of the screen, there is no enough room to display all the items in the  contextual menu ... the problem is that user is not warned that there are additional items below.

### Expected behavior
Suggestion: add something (like 3 dots) to inform user he can scroll to gain access to additional menu items (I don't suggest to display a vertical scroll bar because it is not material design compliant).
Note: below one of the missing item is "Delete" / Supprimer.
 
![suggestion - unable to know thay there is additionnal item in menu](https://user-images.githubusercontent.com/1452146/43289541-9bea1ef0-912b-11e8-941b-0288ae511094.jpg)

### Environment data
Android version: 8.0
Nextcloud app version: Last Beta

**Comment by ardevd** [comment]
Hmm, not sure there's a way to tell if the entire context menu is shown on screen without the need to scroll but I see your point. Do you have any examples of other apps that solve this problem?

I'd instinctively argue that the real problem here is that the context menu has too many items, but others might disagree.

**Comment by AndyScherzinger** [comment]
Also don't have an idea how to display such an information what I do know is that the menu will show a scrollbar at the beginning which hints for more menu items.

**Comment by tobiasKaminsky** [comment]
Right, it shows a scrollbar after opening the context menu.
This scrollbar then vanishes after a short period.
As this is android specific and there is no such option, I fear that we cannot change this.
