### ISSUE TITLE
Navigation Drawer navigation not working when navigating from other activities -> FileDisplayActivity related items.

### ISSUE THREAD

**Issue by eryogeshsingh** [nextcloud/android#2857]
### Actual behaviour
- Once we click activities and then attempt to navigate to other parts of the app from the navigation drawer nothing happens. One have to navigate back to all files then only its possible to goto links like photos, fav or shared.

### Expected behaviour
- All the links should be accessable from anywhere in the app.
 
### Steps to reproduce
1. Navigate to activity in the mobile app
2. Click photos in the menu
3. Photos tab in the menu does not open.

### Environment data
Android version: v7

Device model: Xiaomi mi5 and redmi note 3

Stock or customized system: MIUI

Nextcloud app version: latest

Nextcloud server version: latest

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by ardevd** [comment]
I can reproduce this as well. Just to confirm:

1. Open Activities activity
2. Attempt to navigate to Photo's activity.
3. The Photo's activity does not start. 

Certain activities start just fine ("All Files", "On Device", etc) while other's do not. I'll investigate this asap.

**Comment by AndyScherzinger** [comment]
Thanks @ardevd :1st_place_medal:

**Comment by ardevd** [comment]
The issue is not specific to the Activities activity either though. It affects most of the others as well. 

1. Open the Uploads activity
2. Attempt to navigate to Photos
3. Nothing happens.

It seems to affect all the navigation drawer menu items associated with an EventBus message instead of an activity start. I'll see if I can find a fix.

**Comment by AndyScherzinger** [comment]
Thanks @ardevd :+1: Maybe @mario has some hints or insights on this matter :)

**Comment by mario** [comment]
Consulted with @ardevd.

**Comment by ardevd** [comment]
I've updated the title to make it slightly more precise but it's hard to nail it down in one sentence. Feel free to improve :)
