### ISSUE TITLE
NextCloud on Android 2.x

### ISSUE THREAD

**Issue by AmineToualbi** [nextcloud/android#2858]
Hello, 

I do not know if this is supposed to go here but I really would like to get involved in this project. 

However, before downloading & setting up the whole thing, I wanted to know if we can work on this app on Android Studio 2.x. I cannot download the 3.x version for some reason & I wanted input before starting to work.

Thanks for your help, guys!

**Comment by ardevd** [comment]
@AmineToualbi Without answering your question, is there any particular reason you could share to explain why you cant use Android Studio 3.x?

Also, have you tried building the project with Android 2.x? I'd assume it would work but I might be wrong.

**Comment by AndyScherzinger** [comment]
Afaik when we moved to AS3 I'd couldn't be build anymore in AS2 due to the changed gradle/build toolchain so I would guess it won't work. Any particular reason known why the As3 download doesn't work @AmineToualbi ?

**Comment by AmineToualbi** [comment]
Thank you for the answers. This is what I thought, most projects can't build once you move onto AS3 on AS2. I had this problem on another open-source project I wanted to contribute to. 

I am having an error when building my project after the download & installation are completed. I get an error blocking my build and I gave up on that but I might have to try to figure it out if it comes to that. I tried when I started using AndroidStudio but I didn't know much about the platform itself so I hope I'll be able to figure out what's wrong now. 

Thanks for the answers, though. I appreciate it. Good luck, guys!

**Comment by ardevd** [comment]
I'd strongly advise you to use Android Studio 3.x instead of trying to shoehorn this to build on Android Studio 2.x. If you require Android Studio 2.x for other projects it's totally possible to run the two of them side by side, just download it and unzip it to a separate directory. You could of course also run it in a VM if you want to isolate it fully for some reason.

**Comment by tobiasKaminsky** [comment]
AS2 will not work.
We also have nextcloud-mobile on irc, if you need help while setting up AS3 with nextcloud.
