### ISSUE TITLE
multiple file selection is not removed after copy/move/download/set-available-offline

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#2859]
follow up to #2463 and #2856

### Actual behaviour
- select multiple files and then copy/move/download/set-available-offline them: On the screen it still tells you "X selected"

### Expected behaviour
- Selection should be cleared after the corresponding action has been triggered/confirmed/etc.
 
### Steps to reproduce
1. upload 2 test files
2. select both files (multiple selection)
3. select them and choose copy/move/download/set-available-offline from the menu
4. the files are copied/moved/downloaded/set-available-offline but the selection is still actie and also shown in the toolbar

### Environment data
Android version: 8.1.0
Device model: OP3T
Stock or customized system: Lineage 15.1
Nextcloud app version: 3.3.0-master
Nextcloud server version: 13.0.5

**Comment by AndyScherzinger** [comment]
@jmintb fancy fixing the remaining multiselect issues in a separate PR ;) :heart: That be awesome.

Btw. I just reviewed your PR, looking good awaiting a second pair of eyes :)

**Comment by jmintb** [comment]
@AndyScher

**Comment by jmintb** [comment]
@AndyScherzinger Should the sync button also exit the selection mode?
If you have selected files that are already downloaded, a sync button is displayed in the menu instead of the download button.

**Comment by AndyScherzinger** [comment]
@jmintb I'd say yes :+1:
