### ISSUE TITLE
Instant camera upload stopped after installing sd card

### ISSUE THREAD

**Issue by SRevels** [nextcloud/android#286]
## What happens

Been using instant upload to sync camera pictures for about a month, no problem. Installed an sd card (which camera uses as default storage location now) and now every picture says ”local file not found” when attempting to upload.
## What should happen

The files should upload as they did before the sd card was installed.
### Steps to reproduce
1. Configure instant upload, take picture, works fine
2. Install sd card & set camera to use it as storage
3. Take picture & app reports local file not found
### Environment data

Android version: 6.0.1

Device model: Samsung Galaxy S7

Stock or customized system: stock

Nextcloud app version:1.3.1

Nextcloud server version: 10.0.0

**Comment by edgeHB** [comment]
Hey, i can confirm this issue.
Device: Galaxy S7 edge
Android 6.0.1
SD-Cars as standard storage for the camera

**Comment by tobiasKaminsky** [comment]
@SRevels @edgeHB can you both try the latest version (or the latest beta found on fdroid or 
https://github.com/nextcloud/android/blob/beta/apks/latest.apk)

**Comment by tobiasKaminsky** [comment]
No response within the last month, therefore closing.
Please feel free to reopen with additional infos, if the problem still exists.
