### ISSUE TITLE
nextcloud crashed when using fingerprint as a validation method while reloading nextcloud

### ISSUE THREAD

**Issue by yanggis** [nextcloud/android#2862]
### Actual behaviour
- Tell us what happens

nextcloud crashed when using fingerprint as a validation method while reloading nextcloud on android 8.0. The issue didn't appear on android 7.00before.

### Expected behaviour
- Tell us what should happen
 
### Steps to reproduce
1. 
2. 
3. 

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
Hi @yanggis which version of the app are you using?

**Comment by yanggis** [comment]
The latest version on Google Play.

**Comment by yanggis** [comment]
@AndyScherzinger No, didnt report it on the device. I'm sure the issue happened only on Android 8.0, everything worked fine on Android 7.0; I just upgraded to Android 8.0 last weekend.
