### ISSUE TITLE
Can't set expiration date on link 

### ISSUE THREAD

**Issue by tommyguitfiddle** [nextcloud/android#2866]
### Actual behaviour
- When touching the checkbox, no options show up for setting an expiration date

### Expected behaviour
- as with the web UI, there should be a calendar or other method of selecting a date
 
### Steps to reproduce
1. Touch the sharing icon next to a folder
2. Touch the share link checkbox
3. Touch the three-dot menu icon
4. Touch the set expiration date menu option
5. Nothing happens

### Environment data
Android version: 8.0.0

Device model: LG V20

Stock or customized system: stock

Nextcloud app version: 3.2.1

Nextcloud server version: 13.0.4

**Comment by AndyScherzinger** [comment]
Hi @tommyguitfiddle thanks for reporting this, could you try the beta releases via f-droid maybe? https://f-droid.org/en/packages/com.nextcloud.android.beta/

@tobiasKaminsky I checked the actual 3.3.0 alpha and it works fine on my OP3T running Android 8.1

**Comment by tommyguitfiddle** [comment]
This does work in the developer version.  Hopefully when the production version of the app is next updated, this bug will disappear

On August 7, 2018 8:40:38 AM MDT, Andy Scherzinger <notifications@github.com> wrote:
>Hi @tommyguitfiddle thanks for reporting this, could you try the beta
>releases via f-droid maybe?
>https://f-droid.org/en/packages/com.nextcloud.android.beta/
>
>@tobiasKaminsky I checked the actual 3.3.0 alpha and it works fine on
>my OP3T running Android 8.1
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/nextcloud/android/issues/2866#issuecomment-411080540

-- 
Sent from my mobiledevice. Please excuse my brevity and any typos.

**Comment by AndyScherzinger** [comment]
Thanks for the feedback @tommyguitfiddle :heart: If I remember correctly there has been a bug with setting the date and I fixed that a while ago but have been to late for 3.2.x thus included it for 3.3.0 which should become a stable release around end of August / beginning of September.

**Comment by tobiasKaminsky** [comment]
I do not find the corresponding PR, but as this is fixed, I'll close it.
If this is not working on 3.3, please re-open.
