### ISSUE TITLE
Open files in new task

### ISSUE THREAD

**Issue by linucksrox** [nextcloud/android#2867]
### Actual behaviour
Resuming Nextcloud opens into the last app used if a file was opened from Nextcloud.

### Expected behaviour
When opening a file, in my opinion the app used to open the file should be opened in its own task so that when resuming Nextcloud later on, you actually launch into the Nextcloud app itself instead of opening the last used app, which can be pretty confusing.
 
### Steps to reproduce
1. Open Nextcloud from the app drawer
2. Open a keepass .kdbx file using Keepass and unlock the database
3. Lock the database and return to the home screen (not using the back button to navigate back into the Nextcloud app)
4. Open Nextcloud from the app drawer to be taken to the Keepass login dialog

### Environment data
Android version: 8.1

Stock or customized system:

Nextcloud app version: 3.2.1

Nextcloud server version: 13.0.5

**Comment by ardevd** [comment]
I totally get your point and I understand you preference. However, that is simply not how Android intents work. As far as I know there is no way to change this behavior.

**Comment by AndyScherzinger** [comment]
@linucksrox not sure which app you are using and it might look like a workaround but I use Keepass2Android which has a WebDAV connector build in so the app connects with the Nextcloud server itself and also sync the keepass database with the server :)

**Comment by linucksrox** [comment]
@ardevd I was thinking about the Intent flag `.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)` which would accomplish this behavior.
@AndyScherzinger I'm also using Keepass2Android and I've tried that method, but I seem to recall having problems with syncing. I landed on using Nextcloud for the syncing which works pretty well in my case, except for the occasional time I go back into Nextcloud to look for a file and have to back out of Keepass2Android first.

**Comment by tobiasKaminsky** [comment]
Yes, this is working with "new_task":
- click on a pdf file
- see two apps on recent apps: nc and pdf (right)
- previously it was only nc with pdf inline (left)

![2018-08-13-154137](https://user-images.githubusercontent.com/5836855/44035264-6472944c-9f0f-11e8-9e0b-897e917eb2d4.png) ![2018-08-13-154102](https://user-images.githubusercontent.com/5836855/44035265-6492f656-9f0f-11e8-8be5-da23c2d53b03.png)


I'll create a PR.
