### ISSUE TITLE
locally avaiable files are no longer useable when there is no 'net' availabe

### ISSUE THREAD

**Issue by josch09** [nextcloud/android#2869]
### Actual behaviour
- files are on phone (available offline, because the intention was to use them in remote areas where there is no internet, or I cannot access my nextcloud server)
- click on such a file (in my case a pdf with some chinese stuff) - a modal window opens which says: "Fetching most recent version of the file"
- and then nothing happens...

### Expected behaviour
- It should be possible to open the such local files again.  

### Steps to reproduce
1.  Disable wifi, and sim card internet should also not avaiable
2.  see actual behaviour

### Environment data
Android version: 6.0

Device model: mediatek china grumpel

Stock or customized system: customized, rooted + afwalled 

Nextcloud app version: from FDROID 20180726

Nextcloud server version: 13.0.5

**Comment by scheinercc** [comment]
This seems to still be the case. Additionally to the modal/spinner saying "Fetching most recent version of the file" files I tried to open got actually deleted from my device and only restored when I was online again.
This bug restricts the usability of the client IMHO quite substantially.

Client version: 3.5.0
Nextcloud Server version: 15.0.2
Android version 6.0.1

_Recommending to adjust the title to: "alleged locally available files are no longer usable while offline"_
