### ISSUE TITLE
Database Usage Status is not same in ios and android version.

### ISSUE THREAD

**Issue by fullstackdeveloper90** [nextcloud/android#2876]
![simulator screen shot - iphone 6 - 2018-08-12 at 01 49 51](https://user-images.githubusercontent.com/16564649/43993516-18bc2542-9dd2-11e8-8639-6f04ecebe4b1.png)
![screenshot_20180812-014811](https://user-images.githubusercontent.com/16564649/43993524-2b6b0208-9dd2-11e8-9aee-08aee0e606b9.jpg)

We can see 2 screenshots about database usage status.
I hope android version is same as ios version.

**Comment by AndyScherzinger** [comment]
@fullstackdeveloper90 what are you refering to? 
* The iOS screenshot shows the menu and the acount's storage usage on the server. 
* The Android client screenshot shows the file listing

**Comment by AndyScherzinger** [comment]
@fullstackdeveloper90 you should see that info in the main menu of the Android app at the very bottom

**Comment by fullstackdeveloper90** [comment]
but it shows only folder and file.

**Comment by AndyScherzinger** [comment]
@fullstackdeveloper90 you are talking about the file listing while I am talking about the main menu accessible via the menu on the top left. there within the menu at the very very bottom you should see the exact same information. Only scenario where you don't get this displayed is if the account's quota is set to "unlimited" on the server.

**Comment by tobiasKaminsky** [comment]
What make me wonder is, that on iOS a total size is shown.
@fullstackdeveloper90 can you open up the drawer and see if there is at the bottom a quota?

![2018-08-14-135139](https://user-images.githubusercontent.com/5836855/44090073-37a11b7c-9fc9-11e8-8c92-7841c09d9646.png)


@AndyScherzinger on "unlimited" we could at least show the current used size with a grey bar.

Web UI:
![image](https://user-images.githubusercontent.com/5836855/44089969-e65f7d6c-9fc8-11e8-8887-cb7d439fe811.png)

**Comment by fullstackdeveloper90** [comment]
Ok. thanks. let me check.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky yeah makes sense to at least show that info in grey tones for unlimited quotas (like the webUI)

**Comment by tobiasKaminsky** [comment]
Then I'll do it noooooooooow

**Comment by fullstackdeveloper90** [comment]
@tobiasKaminsky 
I tried to see the feature like your screenshot.
But I can't see that in latest release version.

**Comment by fullstackdeveloper90** [comment]
![screenshot_1534248624](https://user-images.githubusercontent.com/16564649/44090874-fdcb8fea-a00e-11e8-898b-c2c02ed30f53.png)

**Comment by fullstackdeveloper90** [comment]
It's screenshot I built from latest project.

**Comment by tobiasKaminsky** [comment]
If you have unlimited space / no quota set, you will not see an info.

This is what I developed now, when quota is not set:
![2018-08-14-150211](https://user-images.githubusercontent.com/5836855/44093179-08b5b048-9fd3-11e8-822c-ad386d5cfe05.png)

**Comment by fullstackdeveloper90** [comment]
good. it shows the usage
