### ISSUE TITLE
automatic file upload very often uploads .thumbdata4 file from .thumbnails folder

### ISSUE THREAD

**Issue by okias** [nextcloud/android#2878]
### Actual behaviour
- automatic file upload very often uploads .thumbdata4 file from .thumbnails folder

### Expected behaviour
- do not try upload .thumbnails subfolder
 
### Steps to reproduce
1. set folder with pictures and .thumbnails folder for automatic synchronization

### Environment data
Android version: 8.1.0

Device model: Xiaomi Mi6 sagit

Stock or customized system: stock LOS

Nextcloud app version: F-Droid stable

Nextcloud server version: 13.0.4

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
@okias so I am guessing you configured the folder as a custom folder or did you just pick the folder from the displayed list within the auto upload screen? The custom folder variant simply uploads anything within the folder rand is not limited to media files

**Comment by okias** [comment]
@AndyScherzinger well, yes. I didn't noticed that whole DCIM folder has been marked for upload but had icon of "all-content-sync"..

Is there any other place where I can notice this? Also when creating custom own folder for upload, can this behaviour be altered to "only media" or "everything" ?

Thanks

**Comment by tobiasKaminsky** [comment]
I think we exclude this now.
Is this still happening?

**Comment by AndyScherzinger** [comment]
afaik we don't or at least only for some of these thumb-dot-files (can't check due to JDK issues on my laptop...)

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky see https://github.com/nextcloud/android/blob/master/src/main/java/com/owncloud/android/datamodel/FilesystemDataProvider.java#L99 I guess we only ignore .thumbnail while I can't say if this works for standard auto upload _and_ custom folders (also can't say for sure if this is the right code part, has been added with 3.8.0 I think according to the changelog)

**Comment by tobiasKaminsky** [comment]
> works for standard auto upload _and_ custom folders

Should work for both, as we just fetch the files for any synced folder id.

As original reporter did not replied, we can close this, I guess.
