### ISSUE TITLE
App is not asking for fingerprint (pin only)

### ISSUE THREAD

**Issue by joekerna** [nextcloud/android#2879]
### Actual behaviour
With device credentials set to fingerprint unlocking, the app always asks for the pin code.

### Expected behaviour
It should ask for a fingerprint. Pin could be fallback solution
 
### Steps to reproduce
1. Turn on fingerprint verification
2. Start app
3. Notice pin request

### Environment data
Android version: 8

Device model: Huawei P9

Stock or customized system: stock

Nextcloud app version: latest development version

Nextcloud server version: 13.0.5

**Comment by AndyScherzinger** [comment]
@joekerna can you tell on which screens (or all of them) this isn't working because if I remember correctly not all screens have a check for this, while the main, file listing screen most definitely does.

**Comment by joekerna** [comment]
I can not find one screen that asks for my fingerprint. It's either PIN or nothing (before the timeout)

**Comment by joekerna** [comment]
Yes I have.
The pin is the one I've set up on android. It's the one I use to unlock my phone in case fingerprint fails or after a reboot.
I have not set up any passwort/pin in the nextcloud app.

**Comment by tobiasKaminsky** [comment]
I see this screen and can either enter pin or use my finger.

![screenshot_20180814_122653](https://user-images.githubusercontent.com/5836855/44089438-1028f710-9fc7-11e8-80c9-3032ce9504d0.png)

However this is sometimes not working with an emulated device, but working reliable with my OnePlus3 (on latest dev release).

Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

**Comment by AndyScherzinger** [comment]
Same for me, as mentioned by @tobiasKaminsky while that is obvious since i use a OnePlus3T which is more or less the same device :/

**Comment by joekerna** [comment]
I tried to take a screenshot but it's blocked. But as described in my case it only asks for the pin.
I don't have logcat set up. I will as a friend with a different phone (Samsung) than mine (Huawei) to see if it's working for him.

**Comment by joekerna** [comment]
I've uploaded a protocol file from the app (3.3 RC3)
[currentLog.txt](https://github.com/nextcloud/android/files/2383238/currentLog.txt)

**Comment by JOrion9999** [comment]
This is now happening on the stable version 3.3.0 that was auto updated to my phone. Even with the settings for "lock" in settings is set to "none". I still get the screen and have to login with a fingerprint (which fails every time "incorrect credentials" but it was set up for using fingerprint in the last version and it worked fine) or with the phone's pin which I will usually have to enter several times before it will finally go through and show my files but it also pops up a message that I have to click OK on that simply says "E2E mnemonic" and nothing else but an OK button. 

This happened on a Stock ZTE Axon 7 ROM (rooted using Magisk) and a users ROM (AICP rooted using Magisk)

**Comment by mehturt** [comment]
Same here, after update the app is asking for PIN. There is no indication on the screen that I can use fingerprint (it was there in previous version), though the fingerprint works for me every time.

**Comment by knut-hildebrandt** [comment]
Well, already posted about this issue in #3062. From this thread I deduce that this behavior is intended and not a bug. But why  I'm not always asked for PIN and/or fingerprint when I (re)start the app. This is in my opinion a security breach which did not exist in older versions.

Setup 

> Yes I have.
Well, already posted about this issue in #3062. From this thread I deduce that this behavior is intended and not a bug. But why  I'm not always asked for PIN and/or fingerprint when I (re)start the app. This is in my opinion a security breach which did not exist in older versions.

My setup is like the one @joekerna describes:
  > The pin is the one I've set up on android. It's the one I use to unlock my phone in case fingerprint fails or after a reboot.
> I have not set up any passwort/pin in the nextcloud app.

**Comment by igor-cali** [comment]
Same here, With Honor P8.

**Comment by oyelekci** [comment]
Same here with Honor 9

**Comment by tobiasKaminsky** [comment]
We had a bug with fingerprint (un)lock mechansim. It affected only a few devices, e.g. Xiaomi, Motorola, …
As none of our test deices was affected, hunting this bug down took a while.

If any of you could download and install this apk (https://cloud.nextcloud.com/s/pCwRFo7rFF3MMjM) and test if it is now working better, I would appreciate it.
(the APK file is signed with the key for Google Play Store and is 3.3.2 Alpha 1, so this proves that it is an official version and can be easily upgraded. The up-to-come 3.3.2 version then can also just update this version).

**Comment by mehturt** [comment]
I'm testing on Honor 8.
Setting Lock to None and turning screen off, then on, it still asks for PIN (or fingerprint).
Not sure if it's a different issue.

**Comment by joekerna** [comment]
Huawei P9:
The app is asking for a PIN even though fingerprint is activated in device settings. However if I place the finger on the scanner, the app unlocks successfully.
So this is in fact an inprovement but I guess it should ask for a fingerprint.

**Comment by tobiasKaminsky** [comment]
Thanks for testing.

@mehturt are you sure this is from NC? Turning on/off screen should not affect our app as we just go for a timeout (10s).

@joekerna we are using the built-in device credentials screen, which varies from device to device. On some there is only a very little fingerprint icon on the bottom.
Can you maybe post a screenshot? (Unfortunately you will have to take a picture with a different phone as screenshots are prohibited when device lock is enabled)

But all in all it seems to be better :+1:

**Comment by mehturt** [comment]
@joekerna same here, but as @tobiasKaminsky said it's probably a device thing that app can't do much about

@tobiasKaminsky  not sure what you mean by "this is from NC"?  The scenario I'm describing is when starting up NC app, yes.

**Comment by JOrion9999** [comment]
On the Axon 7 the downloaded version finally fixed my issue .. the pin always seemed to work as long as I didn't use the fingerprint... if I tried the FP it would cause the Pin to fail as many times as I used the FP sensor but then would get me in .. if I didn't use the FP and only used the pin it seemed to work .. but now with the new version, I can use both the fingerprint or the pin and they are now both successful. Thank you for solving this issue :)

**Comment by joekerna** [comment]
> 
> 
> Thanks for testing.
> 
> @mehturt are you sure this is from NC? Turning on/off screen should not affect our app as we just go for a timeout (10s).
> 
> @joekerna we are using the built-in device credentials screen, which varies from device to device. On some there is only a very little fingerprint icon on the bottom.
> Can you maybe post a screenshot? (Unfortunately you will have to take a picture with a different phone as screenshots are prohibited when device lock is enabled)
> 
> But all in all it seems to be better 👍

I will take a "screenshot" this evening and post it. Though the device credentials screen still looks different than the screen from other apps. Those only cover a small part of the screen.

**Comment by tobiasKaminsky** [comment]
After timeout (10s) I started NC app:
(this screen can be a bit different, depending on vendor/device)
![screenshot_20181031_131256](https://user-images.githubusercontent.com/5836855/47787298-c9387080-dd0e-11e8-83ea-a7f91a54e076.png)

@joekerna as you can see in this screenshot from stock android 9, there is only at bottom a litte icon. On older android version it can happen that the keyboard hides this icon.
