### ISSUE TITLE
Regression: Displaying of SVG files fails

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#2893]
### Actual behaviour
- SVG files can't be displayed anymore

### Expected behaviour
- SVG files get displayed again
 
### Steps to reproduce
1. download a SVG file
2. click to open
3. Preview/Image view opens, loading for a while and ending with the error screen

### Environment data
Android version: 8.1.0

Device model: OP3T

Stock or customized system: Lineage latest build

Nextcloud app version: master/glide-branch

Nextcloud server version: 13.0.5

**Comment by debuc** [comment]
I want to fix this issue. Could anyone give me some context please?

**Comment by AndyScherzinger** [comment]
@debuc see https://github.com/nextcloud/android/commit/da060314fa63a5e2d05a5dd5f7ad621b75308f25 which provides the fix (sorry for fixing it myself), issue was that the if-block never turned true for svg files since svg is stores in the drawable variable
