### ISSUE TITLE
Entering user name for sharing a file gives error

### ISSUE THREAD

**Issue by spaceChRiS** [nextcloud/android#2895]
### Actual behaviour
- Setup: Nextcloud android app 3.2.1 from f-droid interacting with OwnCloud 10.0.8 server (have to use OwnCloud in this case since it is not my server/installation)
- The German translation of “unknown error” is shown when a character is entered in the user name field. User name completions are not shown.
- Maybe the error is related to incompatibilities between OwnCloud and NextCloud?

### Expected behaviour
- User name suggestions should be shown and it should be possible to share files
 
### Steps to reproduce
1. Klick on share symbol on file/folder
2. Enter single or several characters into user/group name search box
3. Error message is shown as overlay, no results found

### Environment data
Android version: tested on 5.x and 7.x

Device model: Samsung Galaxy S5/7

Stock or customized system: Stock

Nextcloud app version: 3.2.1

Nextcloud server version: Owncloud 10.0.8

#### Web server error log
```
no access to log
```

#### Nextcloud log (data/nextcloud.log)
```
App log ends half a year ago
```

**Comment by ardevd** [comment]
@AndyScherzinger Is running the NextCloud app with (an old version of) OwnCloud even expected to work?

@spaceChRiS Sounds like you should be using the OwnCloud app instead, or am I missing something here?

**Comment by AndyScherzinger** [comment]
@ardevd the short answer would be no. The Nextcloud client might work with ownCloud (latest version is 10) while we don't test or actively support it, so it is rather luck if it works. For the sharing that is likely an incompatibility since both projects are changing their sharing features. Best solution in this special case would actually be to stay with the corresponding client app or run both :/

So I'd close the issue for now.

**Comment by spaceChRiS** [comment]
Thanks for the clarification.

@ardevd I have accounts on several Next/OwnClouds (private local nextcloud for testing things, private hosted owncloud (no possibility to switch), and nextcloud at work), but I don't want to use several clients on my phone. It would cost energy and memory, and the different features of the clients would make it even more cumbersome, plus caring about updates, handling app passwords on both clients with some of the updates, … Nextcloud is definitely the better solution, but unfortunately no option for the hosted private cloud. Hope that will change some day.
Too sad that the sharing features differ so much that interoperability is not possible. I remember that it did work before.
