### ISSUE TITLE
Create new file option

### ISSUE THREAD

**Issue by mjd80** [nextcloud/android#2896]
### Actual behaviour
- There is "create new folder" but lack of analogous option for file. 
We have unconfortable use case for simple text files. One needs to create empty file on PC or in text editor then write into phone storage and then run  NextCloud client and copy to repository - it's longer process and even leaves garbage on storage. 

### Expected behaviour
- Mainly for simple txt: it would be very handy the option that enables to create just empty file of given extension directly in NextCloud repository. 
 
### Steps to reproduce
- Click on Plus icon
- Choose "Create new file" 

### Environment data
Android version: 7.1.1

Device model: Asus zc553kl

Stock or customized system: Stock

Nextcloud app version: 3.2.1

Nextcloud server version: 13.0.5

**Comment by mjd80** [comment]
I'm sorry, I duplicated at least:

#877 (Create new text file from within NC), #785 (Proposal: Add create file button)

Also sending selected text into NextCloud makes possible to create new file. Sadly, it's not fully obvious resolution.

**Comment by tobiasKaminsky** [comment]
Closing this in favor of #877.
Sending text to NC app indeed lets you create a new text file. And you are right that this is not that obvious.
If you have an idea, how this can be improved, please open up a new issue, where we can discuss this :+1:
