### ISSUE TITLE
Enable pull-to-refresh in upload/document share intent

### ISSUE THREAD

**Issue by shtrom** [nextcloud/android#2897]
### Actual behaviour
- Pull-to-refresh when browsing in the upload/share intent does nothing

### Expected behaviour
- Pull-to-refresh when browsing in the upload/share intent should refresh the view and show new folders
 
### Steps to reproduce
1. Share a document from another app to Nextcloud
2. Go to any folder
3. From another device, create a new sub-folder to that folder
4. On the first device, pull-to-refresh

### Environment data
Android version: 7.1.2

Device model: Nexus 5 (Hammerhead)

Stock or customized system: LineageOS 14.1

Nextcloud app version: 3.2.1

Nextcloud server version: 13.0.1

**Comment by shtrom** [comment]
Doesn't seem like any of those issues are related. Thanks @nextcloud-android-bot

**Comment by tobiasKaminsky** [comment]
We refresh when entering a folder, this should be good enough.
