### ISSUE TITLE
Renaming of folder makes whole folder to download again

### ISSUE THREAD

**Issue by mako2580** [nextcloud/android#2898]
### Actual behaviour
- Content of renamed folder is deleted on phone and redownloaded.

### Expected behaviour
- It should only rename folder on phone.
 
### Steps to reproduce
1. Rename folder over web interface
2. Sync folder in android app

### Environment data
Android version: 7.1.2

Device model: Blackview A5

Stock or customized system: Lineage OS 14.1

Nextcloud app version: 3.2.1

Nextcloud server version: 13.0.5

**Comment by tobiasKaminsky** [comment]
@rullzer how do you do this on desktop?

Scenario: 

1) Folder /a/b gets renamed to /a/c
As it is in the same folder before removing, we could see if the same fileId is somewhere used

2) Folder /a/b gets moved to /e/b
How about this? We do not keep track of / get noticed of file/folder moves. So how can we prevent deleting this in one folder?
