### ISSUE TITLE
add "sort by name descending" (Z-A) option

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#29]
https://github.com/owncloud/android/issues/1656

@jancborchardt I know we have discussed this back in the days I have implemented it, but it seems as it is demanded by some...

**Comment by jancborchardt** [comment]
Isn’t the real fix here to use the real EXIF date taken of the picture? Because if we just add that view, the files still have the wrong date. Photos should, when not edited, retain the »modified date« of when they were taken, not when they were uploaded.

**Comment by tobiasKaminsky** [comment]
Hmm, not really as this is an example, I guess. 
What if you want to open the oldest file. You still have to scroll down the entire list.

**Comment by jancborchardt** [comment]
But that’s exactly what you do when you want to open an old file – scroll down the list. You don’t switch the sorting just for that.

Instead, that’s what the scrollbar dragger in the Contacts app is made for – do you know what I mean? Can we have that in our Android app as well?

**Comment by tobiasKaminsky** [comment]
You do not see me working with dolphin ;)
But the second part is the clue to this issue I guess: we need a fast scroll handler for the list.

**Comment by AndyScherzinger** [comment]
Yay for the fast scroll :)

**Comment by tobiasKaminsky** [comment]
Then I have created a new issue: #47 and therefore close this one.
