### ISSUE TITLE
Nextcloud App - Cannot change custom folder paths. 

### ISSUE THREAD

**Issue by zslukacsik** [nextcloud/android#2906]
### Actual behaviour
- Cannot apply the folders path at Local and Remote folder.

### Expected behaviour
- Auto upload. Set up a custom folder
 
### Steps to reproduce
1. Menu - Auto upload - Set up a custom folder
2.  Local folder (choose local folder)
3.  /storage/emulated/0/CallRecordings
4. Tap choose button

Nothing happen (choose local folder again)
At Remote folder same issue.

### Environment data
Android version:
4.4.2

Device model: 
Samsung S5 Duos

Nextcloud app version:
3.2.3

Nextcloud server version:
13.0

### Logs
No errors.

#### Web server error log
No errors.

**Comment by AndyScherzinger** [comment]
@nextcloud/android I can reproduce this and checked the layout code. The click listener sits on the linear layout so it should work and sometimes it does while sometimes the click isn't detected, don't know why or if it is related to any background threads (while it shouldn't). So this seem to happen while I don't know why :(

**Comment by AndyScherzinger** [comment]
@zslukacsik that is another issue since the first screenshot shows an Nextcloud internal path which should be auto-hidden from the list of available folders. Can you please create a new issue for that one? :)

**Comment by zslukacsik** [comment]
@AndyScherzinger Of course. Thanks!

https://github.com/nextcloud/android/issues/2910

**Comment by AndyScherzinger** [comment]
Thanks a lot @zslukacsik - This is highly appreciated :+1:

**Comment by ndehav01** [comment]
I experienced the same problem described in the original post when trying to add custom paths to Auto Upload folders on my Android phone. It worked once after first installation, but on subsequent attempts at a later time, both versions of the dialogue ("Preferences for auto uploading" and "Create new custom folder setup") failed to show the local or remote folder paths after confirming with the "Choose" button.

Uninstalling and reinstalling the app did not solve the problem. Upon further investigation, I realised I had switched on Android's Developer Options at some point after installing the app for the first time, when trying to solve a USB to PC connection problem.

I turned off the Developer Options in Android's settings and tried to setup the Auto Upload feature again, and this time _both dialogues worked as expected_, allowing me to select the custom folder paths.

**Environment data**

Android version:
6.0

Device model:
LG G3 (LG-D855)

Nextcloud app version:
3.3.0

Nextcloud server version:
14.0.1 (running on Ubuntu Server 18.04 LTS)

**Comment by zslukacsik** [comment]
@ndehav01 
Heureka! 💡 
There is no error with developer option. But when in the "developer option" - "Do not keep activities" - is active -> the app forget the path, because we set to do clear every "activities" (like forget the paths) when we leave a "window".  😄
So, maybe it's not a bug, it's an user error! 
Tested, worked for me! THX!

**Comment by tobiasKaminsky** [comment]
In my opinion we do not have to fix if someone has "don't keep activities" enabled, as this is only a dev option to test long suspended apps.
