### ISSUE TITLE
Show if a file comments

### ISSUE THREAD

**Issue by Spartachetto** [nextcloud/android#2908]
Nextcloud app is constantly improving and the new versions will allow to insert comments and tags (#1798 and #548).

I Think it could be useful to display which files have comments and/or tags.

**Comment by AndyScherzinger** [comment]
> it could be useful to display which files have comments and/or tags.

looping in @nextcloud/designers and @nextcloud/android if and how this could be achieved

**Comment by xXSTrikeXx** [comment]
I like the tagging. But now it is useless, until you can use it also on the desktop client and mobil client.

**Comment by tobiasKaminsky** [comment]
The web UI also does not show if a file/folder has a tag/comment.
As they (normally) have lots of more space than we have on mobile devices, I am not that sure, how we can solve this.

**Comment by tobiasKaminsky** [comment]
Cool, didn't know that. 
How is this done? Do we have to check on each and every file/folder for unread comments?

**Comment by juliushaertl** [comment]
You can get it from the PROPFIND of the folder, if you request the `oc:comments-unread` property.

**Comment by Spartachetto** [comment]
I was thinking to https://github.com/nextcloud/server/issues/6424 when writing this issue. But juliushaertl was faster than me at linking to it!

**Comment by DerTomm** [comment]
Today I wanted to create a first implementation attempt for this feature request as I really like to use this feature in the app too. But then I realized that in last December the necessary code changes were already commited by @tobiasKaminsky into master branch.

The way the feature is implemented looks really good and exactly meets my expectations. So I'd like to ask if there is already a plan when the changes will be merged into stable branch.

**Comment by AndyScherzinger** [comment]
@DerTomm next release 3.5.0 might well get a first release candidate next week. So it should become a stable release within the next 2-3 weeks we hope.

**Comment by tobiasKaminsky** [comment]
We have https://github.com/nextcloud/android/issues/2485 for discussing tag support.
So we can close this, I guess.
