### ISSUE TITLE
Android client cannot open images

### ISSUE THREAD

**Issue by someonestolemyusername** [nextcloud/android#2909]
### Actual behaviour
- If I open an image (in all files, gallery, etc) it opens a view with a light grey title bar with the file name, and a white content area. There is no way to open/view an image.

### Expected behaviour
- Image should open.
 
### Steps to reproduce
1. Open an image. Does not matter if the green tick is present or not.
2. 
3. 

### Environment data
Android version: 8.1.0

Device model: Huawei P20 Pro

Stock or customized system: Stock EMUI 8.1.0

Nextcloud app version: Latest from Google Play (3.2.1)

Nextcloud server version: Latest 13.0.5

#### Web server error log
No data in error.log

#### Nextcloud log (data/nextcloud.log)
No data generated when attempting to view any image.

**Comment by thechonta** [comment]
This Bug is still active on P20 Pro with Android 9 and nextcloud App 3.6.1
Upload of files smaler than 1MB is possible, everything larger failes (autoupload or manuelupload)
Same Server from an LG G6 and it works so it is not the server.
