### ISSUE TITLE
Implement two factor authentication (2FA)

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#291]

**Comment by mario** [comment]
This needs oAuth2 server (or similar), so can't be done currently.

**Comment by AndyScherzinger** [comment]
@mario you can talk to @ChristophWurst he is the 2FA expert on the server side and we already talked about this on the last conference and according to him we should be able to implement it and that the server side capabilities are already there :)

**Comment by mario** [comment]
@ChristophWurst chime on this, please.

**Comment by ChristophWurst** [comment]
Basically, we need a mechanism to obtain a new app password from the server which then is used to authenticated. I worked on a browser-based approach months ago in https://github.com/owncloud/core/pull/24835. It would let the user log into their Nextcloud account and confirm the connection, while the client application (in this case the Android app) will get the new password in the background. This way we're totally independent of the many 2FA providers admins could have activated on the server.
@LukasReschke is this still the preferred way to implement this?

**Comment by ChristophWurst** [comment]
In the meantime, we should also detect when logins in the app fail due to activated 2FA and inform users that they have to generate the app password manually in their personal settings.

**Comment by mario** [comment]
Well, if there's an error message for that... :)

**Comment by ChristophWurst** [comment]
We could do it [like GitHub](https://developer.github.com/v3/auth/#working-with-two-factor-authentication) and reply with a special header, like `X-Nextcloud-2FA: required`

**Comment by mario** [comment]
We could, yes. Just need to backport it to at least 11. Maybe in time for 11.0.2? :)

**Comment by ChristophWurst** [comment]
Sure, I can work on this next week!

**Comment by mario** [comment]
You are awesome!

**Comment by ChristophWurst** [comment]
Fun fact: I already implemented it months ago, but seem to have forgotten it 🙈 https://github.com/owncloud/core/pull/25162

That does only work for DAV, however. Do we need it for other endpoints too, like OCS?

**Comment by mario** [comment]
This will be done in 1.5 via web login support.
