### ISSUE TITLE
No reload after new account add

### ISSUE THREAD

**Issue by tomastd** [nextcloud/android#2913]
### Actual behaviour
- when you add an additional account you need to restart the app for it to be listed

### Expected behaviour
- the new account should be listed and maybe selected just after configuring it
 
### Steps to reproduce
1. add a second or third NC account
2. confirm that ot is not listed
3. 

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
@tomastd can you provide more information as to app version, Android version, running the app on internal memory, device,  etc. 
Just tested your scenario and it works just fine / as expected (like you described how it should work).

**Comment by tobiasKaminsky** [comment]
As you are directly switched to the new account, you do not see it listed in the drawer list, but on top where the current account is shown.

**Comment by tomastd** [comment]
Android 8.0 on Samsung A8 (2018) device.
Everithing running on internal memory.
Android Nextcloud 3.2.3 (just updated)

After finishing the process for adding the new account it is not listed and the active account is the old one. Then, if I quit the app and I restart it, the new account is listed and everything works fine.

**Comment by tomastd** [comment]
Restarting the cell phone, doesn't solve the issue.

After setting up the account, it is listed on the accoun managing screen, so it is well configured. You can select it on that screen, which allows you to delete it. But it doesn't appear on the side menu.

It's necesary to restart the app for the new account to be listed and selected. After that application restart, there's no problem at all.

That's why I think that it is mising a refresh process to list again the accounts after configuring (maybe a service reload).
