### ISSUE TITLE
How to configure Proguard for Android Client library

### ISSUE THREAD

**Issue by gerritbeuze** [nextcloud/android#2914]
I’m using the Nextcloud Android library to add Nextcloud support to an android app using Android Studio. I’m having trouble configuring Proguard. When I run with minifyEnabled false all is fine, but with minifyEnabled true I get lots of Proguard related warnings and error. For example:

com.owncloud.android.lib.common.ExternalLink$$Parcelable: can’t find superclass or interface org.parceler.ParcelWrapper

library class org.apache.commons.codec.binary.BinaryCodec extends or implements program class org.apache.commons.codec.BinaryDecoder

org.apache.jackrabbit.webdav.server.AbstractWebdavServlet: can’t find referenced method ‘int getContentLength()’ in program class org.apache.jackrabbit.webdav.WebdavRequest

I can run with disabling the warings , for example
-dontwarn com.owncloud.android.lib.**
etc.
But then the app crashes as soon as a client completes.

I have tried copying the Proguard.cfg settings from the Nextcloud client app on Github, but that does not make a difference.

Any idea how to configure Proguard to make this work?

Android version:
Android 8.0

Device model: 
Huawei SHT-W09, but happens on any model, it's compiling problem.

**Comment by tobiasKaminsky** [comment]
This is already answered in https://github.com/nextcloud/android-library/issues/160
