### ISSUE TITLE
[FR] Screenshot auto uploading

### ISSUE THREAD

**Issue by gsantner** [nextcloud/android#292]
### Actual behaviour
- Not implemented

### Expected behaviour
- Allow auto uploading of screenshots (power menu/keycombo) made on the device to NextCloud
- Implementation/Options like Camera/DCIM pictures
- Very useful for developers

### Environment data
Android version: 6.0.1

Device model: Nexus 6

Stock or customized system: CM13

Nextcloud app version: 1.3.1

Nextcloud server version: 10.0

**Comment by AndyScherzinger** [comment]
Hi @gsantner this should be covered by #285 which is currently in development.
