### ISSUE TITLE
Android app crashes when opening the menu

### ISSUE THREAD

**Issue by WiLars** [nextcloud/android#2920]
### Actual behaviour
The android app crashes, when attempting to open the menu (both swipe to the right and pushing the hamburger button). Happens on two different devices, since circa two or three months.

### Expected behaviour
I can use the settings...
 
### Steps to reproduce
1. try to open the menu

### Environment data
Android version:
7.1.2
Device model: 
sony e5823
Stock or customized system:
linage os
Nextcloud app version:
3.2.2 but happened before
Nextcloud server version:
13.0.5

**Comment by ardevd** [comment]
Hi and thank you for reporting the issue. 

Please attach logcat output of the crash in order for us to investigate the issue.

**Comment by WiLars** [comment]
ok, I don't really have experience with android logs, but i guess this should be the complete crash event:
thanks for the fast response!

``08-24 15:32:02.668 D/AndroidRuntime(31356): Shutting down VM
08-24 15:32:02.669 E/AndroidRuntime(31356): FATAL EXCEPTION: main
08-24 15:32:02.669 E/AndroidRuntime(31356): Process: com.nextcloud.client, PID: 31356
08-24 15:32:02.669 E/AndroidRuntime(31356): java.lang.RuntimeException: Canvas: trying to draw too large(145299648bytes) bitmap.
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:260)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.graphics.Canvas.drawBitmap(Canvas.java:1415)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at com.bumptech.glide.load.resource.bitmap.GlideBitmapDrawable.draw(GlideBitmapDrawable.java:101)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.graphics.drawable.LayerDrawable.draw(LayerDrawable.java:1012)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.widget.ImageView.onDraw(ImageView.java:1316)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.view.View.draw(View.java:17189)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.view.View.updateDisplayListIfDirty(View.java:16171)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.view.View.draw(View.java:16955)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.view.View.updateDisplayListIfDirty(View.java:16166)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.view.View.draw(View.java:16955)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.view.View.updateDisplayListIfDirty(View.java:16166)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.view.View.draw(View.java:16955)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:4703)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.view.View.draw(View.java:17192)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:4107)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.view.View.updateDisplayListIfDirty(View.java:16171)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.view.View.draw(View.java:16955)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.view.View.draw(View.java:17192)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.support.design.internal.ScrimInsetsFrameLayout.draw(ScrimInsetsFrameLayout.java:87)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.view.View.updateDisplayListIfDirty(View.java:16171)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.view.View.draw(View.java:16955)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1366)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.view.View.draw(View.java:17192)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.view.View.updateDisplayListIfDirty(View.java:16171)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.view.View.draw(View.java:16955)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.view.View.updateDisplayListIfDirty(View.java:16166)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.view.View.draw(View.java:16955)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.view.View.updateDisplayListIfDirty(View.java:16166)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.view.View.draw(View.java:16955)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.view.View.updateDisplayListIfDirty(View.java:16166)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.view.View.draw(View.java:16955)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.view.View.updateDisplayListIfDirty(View.java:16166)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.view.View.draw(View.java:16955)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.view.View.draw(View.java:17192)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at com.android.internal.policy.DecorView.draw(DecorView.java:756)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.view.View.updateDisplayListIfDirty(View.java:16171)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:648)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:654)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:762)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2800)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2608)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2215)
08-24 15:32:02.669 E/AndroidRuntime(31356): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
08-24 15:32:02.670 E/AndroidRuntime(31356): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6344)
08-24 15:32:02.670 E/AndroidRuntime(31356): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
08-24 15:32:02.670 E/AndroidRuntime(31356): 	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
08-24 15:32:02.670 E/AndroidRuntime(31356): 	at android.view.Choreographer.doFrame(Choreographer.java:621)
08-24 15:32:02.670 E/AndroidRuntime(31356): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
08-24 15:32:02.670 E/AndroidRuntime(31356): 	at android.os.Handler.handleCallback(Handler.java:751)
08-24 15:32:02.670 E/AndroidRuntime(31356): 	at android.os.Handler.dispatchMessage(Handler.java:95)
08-24 15:32:02.670 E/AndroidRuntime(31356): 	at android.os.Looper.loop(Looper.java:154)
08-24 15:32:02.670 E/AndroidRuntime(31356): 	at android.app.ActivityThread.main(ActivityThread.java:6236)
08-24 15:32:02.670 E/AndroidRuntime(31356): 	at java.lang.reflect.Method.invoke(Native Method)
08-24 15:32:02.670 E/AndroidRuntime(31356): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
08-24 15:32:02.670 E/AndroidRuntime(31356): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
08-24 15:32:02.679 W/ActivityManager( 1019):   Force finishing activity com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity
08-24 15:32:02.696 W/ContextImpl( 1019): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:877 com.android.server.am.AppErrors.crashApplicationInner:375 com.android.server.am.AppErrors.crashApplication:309 com.android.server.am.ActivityManagerService.handleApplicationCrashInner:13738 com.android.server.am.ActivityManagerService.handleApplicationCrash:13720 
08-24 15:32:02.771 I/OpenGLRenderer( 1019): Initialized EGL, version 1.4
08-24 15:32:02.771 D/OpenGLRenderer( 1019): Swap behavior 1
08-24 15:32:03.194 W/ActivityManager( 1019): Activity pause timeout for ActivityRecord{556e62e u0 com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity t3544 f}
08-24 15:32:03.945 W/GAv4-SVC( 2985): Network compressed POST connection error: java.net.SocketTimeoutException: connect timed out
08-24 15:32:05.485 I/MSM-irqbalance(  497): Decided to move IRQ159 from CPU5 [P:0] to CPU0 [P:1] (banned)
08-24 15:32:05.980 I/ActivityManager( 1019): Killing 31356:com.nextcloud.client/u0a138 (adj 900): crash
``

**Comment by WiLars** [comment]
Hi again,
after having a look at the log, I solved the problem: It seems like the app tries to display something that doesn't fit onto the screen. So the only non-stock image is the log in picture of the nextcloud server, which i had modified previously. So i reseted it to the standard, and now the menu works for me again.

However, to prevent this issue in the future it might be useful to only allow the admin to upload a log-in picture of a certain resolution or rescale it in the app or serverside.

Thank you for giving me a hint in the right direction!

Lars

**Comment by AndyScherzinger** [comment]
@WiLars thanks for the update!

Afaik the client should already take care of this, so pinging @tobiasKaminsky about this matter. It seems the client tries to download the background image for the drawer menu header and that image seems to be a bit to large for the device to handle thus it crashes. I though we do some resizing/shrinking etc. but it seems not to be the case or maybe too late down the road.

**Comment by tobiasKaminsky** [comment]
Can you give us the width and height and your device resolution?

**Comment by WiLars** [comment]
I had the problem on two devices. One with 1280 x 720 and the other with 1080p.

**Comment by tobiasKaminsky** [comment]
And what was the size of the login image?
