### ISSUE TITLE
Pin code bypassed

### ISSUE THREAD

**Issue by jj-uk** [nextcloud/android#2921]
### Actual behaviour
Nextcloud opens and is fully accessible without entering the required pin code

### Expected behaviour
Pin code should be required for access to the app 

### Steps to reproduce
1. Enable pin code and auto upload.
2. Take some photos. 
3. Open Nextcloud. Pin code screen is shown.
4. Wait for images to start uploading. The android notification "uploading..." is shown.
5. Click on the notification during upload. Pin code screen is shown.
6. Open android notification bar again and click the uploading image notification.  
7. Nextcloud fully opens. No pin entry required!

### Environment data
Android version:
5.1.1
Device model: 
Samsung  j3
Stock or customized system:
Stock 
Nextcloud app version:
3.2.1
Nextcloud server version:
13
#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by ardevd** [comment]
Are you sure you're letting the lock timeout expire before opening the app? Try waiting a bit before opening the app from the notification.

**Comment by jj-uk** [comment]
How long is the timeout?

I opened the app probably 10 mins before opening the notification twice to get access.

**Comment by jj-uk** [comment]
How long is the timeout?

I opened the app probably 10 mins before opening the notification twice to get access.

**Comment by ardevd** [comment]
But how long was it between the first time you clicked the notification (where you say the pin code prompt was shown) and the second time? (where the pin code prompt was not shown)

**Comment by jj-uk** [comment]
I've just restarted my phone. Uploading starts automatically after 20 secs. 

Pulling down the notification 1st time shows pin screen.
Pulling it down immediately again shows the uploads screen -full access to the app without entering the pin.

**Comment by ardevd** [comment]
But how long do you wait between the first and second time you click the notification?

**Comment by jj-uk** [comment]
About 5 seconds

**Comment by ardevd** [comment]
@jj-uk Try waiting 30 seconds and see it the issue persists.

**Comment by jj-uk** [comment]
Ok. I clicked the 1st notification to get to the pin screen.
Waited there for 30 secs.
Clicked the notification again and was given access to the app without entering the pin.

**Comment by jj-uk** [comment]
I've not entered a pin since Restarting the phone. No need to.

**Comment by AndyScherzinger** [comment]
@ardevd afaik not all activities have this check implemented so we should probably add it here too.

What do you think @tobiasKaminsky?

**Comment by ardevd** [comment]
@AndyScherzinger Sorry to hijack this, but can we please do something about the nextcloud-android-bot? Does it add anything positive apart from mis-labeling issues and suggesting irrelevant issues? :)

**Comment by AndyScherzinger** [comment]
@ardevd I can't do anything about that I guess, since that can probably only be changed by @tobiasKaminsky or @MorrisJobke

**Comment by moritzschramm** [comment]
Fingerprint/Pin code can also be bypassed like this:

1. Open app -> shows fingerprint required
2. Go to recent apps list (if its called like that? The square button..))
3. Remove app from recent apps list
4. Open app again, if fingerprint still required, go back to step 2
5. Profit

At least this works for me with version 3.5.0 on Android 8.0. I restarted the system, so there shouldn't be any lock timeout or anything, still works.

**Comment by tobiasKaminsky** [comment]
Can you retest this with newest 3.6.1 RC2 (via beta program) or final tomorrow?
