### ISSUE TITLE
[Discussion] Create an calendar synchronization app 

### ISSUE THREAD

**Issue by giupardeb** [nextcloud/android#2925]
Hi everybody, I think that it's better to create an official nextcloud calendar application to synchronize calendar events. In the past I tried to use the DAVDroid synchronization, but in my personal opinion it is difficult to configure.
What do you think?

**Comment by xXSTrikeXx** [comment]
I think its already very easy. You go in the nextcloud app to settings and you click there on “calendar & contacts synchronisation“. Enter password or copy app password from personal settings and voila! ;)

**Comment by AndyScherzinger** [comment]
I agree qith @xXSTrikeXx. Also knowing the amount of work that went into the development of DAVDroid and still goes into it also being aware of the complexity of such a sync/card/calDAV handling within Android. Other than that like @xXSTrikeXx said, it should not be that hard to setup going through the Nextcloud clients settings screen and also looking at the SSO solution for Android announced at this year's conference this might get even simpler than it is today.

**Comment by tobiasKaminsky** [comment]
@giupardeb what is your experienced difficulties in setting up davdroid? Maybe we can then somehow improve the setup flow, but we certainly have not enough men power to maintain such a big app, especially if there is such a great app like davdDroid.

**Comment by visionok** [comment]
I followed this guide here:
https://ownyourbits.com/2017/12/30/sync-nextcloud-tasks-calendars-and-contacts-on-your-android-device/

**Comment by giupardeb** [comment]
I was wrong.. It's very easy synchronize calendar with DAVDroid, thank you @visionok . Maybe I executed the bad configuration. However, to create a separate application to synchronize calendar was Just an idea, I believed it was useful. Thank you all

**Comment by tobiasKaminsky** [comment]
Glad that you solved it, Giuseppe :+1:
