### ISSUE TITLE
[Feature from NC iOS app]: Change filename mask

### ISSUE THREAD

**Issue by rwat1** [nextcloud/android#2926]
### Actual behaviour
- The default filename mask is YYYYMMDD_HHmmss

### Expected behaviour
- The iOS app for NC has the ability to make custom filename mask, such as:

YYYY-MM-DD_HH.mm.ss
or
YY-MM-DD_HH.mm.ss
or
YY.MM.DD-HH-mm-ss

Any any other specified combination.

Example from iOS NC App:
 ![photo2018-08-26__21 42 04_6961](https://user-images.githubusercontent.com/13740715/44636420-a8077c80-a979-11e8-9b81-8aea910eaed7.png)

### Steps to reproduce
1. 
2. 
3. 

### Environment data
Android version:  8.0.0

Device model:  Samsung S9 Plus

Stock or customized system: Stock

Nextcloud app version: version 3.2.3

Nextcloud server version:    NCP v0.58.1

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by rwat1** [comment]
the bot is wrong.

**Comment by tobiasKaminsky** [comment]
We discussed this already in some other issues.
Our idea/intend is to not change any file/folder, but just copy/upload/download them.
So we are simply relying on what the camera app is generating.

Therefore I vote to not add this within our app as it creates another layer of complexity…

**Comment by armartar** [comment]
Hi, 

is there anyway to remove the leading "Photo" before the custom filename mask?
