### ISSUE TITLE
Minor UI issues with "Deleted Files" view

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#2927]
### Actual behaviour
![device-2018-08-27-091933](https://user-images.githubusercontent.com/1315170/44646254-afab3d80-a9da-11e8-9656-42c5a539cd31.png)

### Expected behaviour
1. icon should maybe changed to grey600? cc @jancborchardt 
2. files should display the respective mime type icon not the folder icon
3. text is cut of needs some more padding at the bottom

### Environment data
Android version: 8.1

Device model: OP3T

Stock or customized system: Linage latest nightly

Nextcloud app version: actual master

Nextcloud server version: 14.0.0R1

cc @tobiasKaminsky since he implemented the view :)

**Comment by tobiasKaminsky** [comment]
1. correct, should be the same color like overflow menu, or?
2. works for me, I also get the correct preview. 
3. this then needs to be changed in overall xml, as this is just like the regular oc file list

Thanks for testing and reporting this findings :+1:

**Comment by AndyScherzinger** [comment]
> 1. correct, should be the same color like overflow menu, or?

yes

> 2. works for me, I also get the correct preview. 

okay, will have to try and re-install then

> 3. this then needs to be changed in overall xml, as this is just like the regular oc file list

okay

**Comment by AndyScherzinger** [comment]
> 1. correct, should be the same color like overflow menu, or?

yes, grey600

2. works for me, I also get the correct preview.

> hmm, doesn't work for me with latest master, might need a fresh install

> 3. this then needs to be changed in overall xml, as this is just like the regular oc file list

nope, trashbin uses it's own item layout `trashbin_item.xml` since it has 3 lines, while the file item has 2 (thus 72dp are not enough here, will fix)

**Comment by tobiasKaminsky** [comment]
Have you already changed the third problem? Or is this vanished because we do not longer have a divider?

![2018-09-11-140429](https://user-images.githubusercontent.com/5836855/45359041-9c4bc500-b5cb-11e8-9f03-06072f82ddcb.png)

**Comment by tobiasKaminsky** [comment]
I cannot reproduce second problem.
Is this still happening to you?

**Comment by AndyScherzinger** [comment]
Haven't checked this issue and it also works for me, due to all the changes and layout fixed I did when removing the dividers via #2944, so we can close this as it'll ship with 3.3.0 :+1:
