### ISSUE TITLE
Automatic upload does't work

### ISSUE THREAD

**Issue by optimistic5** [nextcloud/android#2929]
### Actual behaviour
Automatic upload does't work

### Expected behaviour
Automatic upload should work
 
### Steps to reproduce
Nextcloud app-Automatic upload-Add some folder from device or sdcard

### Environment data
Android version: 6.0.1

Device model: One E1001

Stock or customized system: stock

Nextcloud app version: 3.2.3

Nextcloud server version: 13.0.4

**What kink of logs should I add? What the path of this logs?**

**Comment by nanawel** [comment]
Same issue here after upgrade to version 2.8.0, on a Galaxy J5, Android 5.1.1.
Was working correctly with a previous version of the app (but I don't remember which one it was).

Whatever the directory I set in the configuration, it does not detect the new pictures once taken.

**Comment by rwat1** [comment]
SAME HERE!!! I had to create a "Custom Folder" because the automatic upload data configuration settings is messed up.  Ultimately, I had to completely reinstall the NC App, and the default automatic folders started to work again.

This only happened after I upgraded to new version 2.8.0

**Comment by InfamousUser** [comment]
Doesn't work for me either, not to mention there are a bunch of issues for Nextcloud about auto upload not working!

**Comment by InfamousUser** [comment]
Why would this become closed if it hasn't been resolved?

**Comment by nanawel** [comment]
> Why would this become closed if it hasn't been resolved?

As mentioned by the bot, because nobody replied and added information to this issue. But that's a bit unfair since we don't know what information we might add to help fix it since no developer ever seemed to show interest in this bug.

**Comment by InfamousUser** [comment]
What kind of smartass makes a bot that removes bug reports that that aren't actively talked about after they're reported and then doesn't do anything about the bug for months?

**Comment by rwat1** [comment]
Why was this CLOSED when the issue wasn't resolved?
