### ISSUE TITLE
Push Notifications not working on 3.2.3

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#2931]
from the forums, cc @tobiasKaminsky 
_________
When i enter notificacions screen in android app i can see the follow message “Push notifications currenly no available”. I can see current notifications list, but push don’t work.

In browser, notificacions are working correctly. I don’t see any error in nextcloud log, nor apache logs.

I’m using the follow configuration:

* Nextcloud 14 RC1 running on custom docker image based on Ubuntu 18.04 with php 7.2.7 and apache 2.4.29.
* Nextcloud android app 3.2.3 installed from Play store, running on stock Oneplus 6 (Oxygen OS Android 8.1 with play services)

I register user and authorize in the app without any error, and I can see the device authorizacion in the security section of my user in nextcloud.

I see the issue https://github.com/nextcloud/android/issues/2301 5, push notifications are currently working on android ?

**Comment by AndyScherzinger** [comment]
@fracarvic I think you won't see anything, afaik this happens in cases where the APK hasn't been signed, which is something I don't know but @tobiasKaminsky might.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky it seems the 3.2.3 release for the play store hasn't been signed correctly which seems odd since I guess you wouldn't be able to publish, so then it must be signed the same way with the same signature so push should work ?!

**Comment by tobiasKaminsky** [comment]
The code did not changed regarding push notification, but I automated the release process and maybe did something wrong.
I will have a look today as this is a show stopper for upcoming versions…

**Comment by tobiasKaminsky** [comment]
@fracarvic @AndyScherzinger can you both test this release?
It is 3.2.4 Alpha 1 and properly signed, so it can be installed on top of 3.2.3 and will then replaced by upcoming 3.3 without problems.

https://cloud.nextcloud.com/s/zj2dQtjA6bF9wgS

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky work fine for me too :+1:
