### ISSUE TITLE
 Menu browsing not working reliably on nextcloud android app

### ISSUE THREAD

**Issue by Joe7new** [nextcloud/android#2947]
### Actual behaviour
- **While browsing in menu** of android app (clickling on menu items 'Alle Dateien' , 'Aktivitäten', etc..)  **the app stopps /freezes after a while !** Then clicking on another menu item (except 'Alle Dateien') has no effect and content will not be updated. In most cases clicking on the menu item 'Alle Dateien' seems to remove this problem for a while and browsing the menu items is possible again with updated content.
But this doesn't last very long !
### Expected behaviour
- clicking on a menu item should always show the right content and switching between menu items should work reliably !

### Environment data
Android version:6.0.1

Device model: Samsung Galaxy S5 neo

Stock or customized system:

Nextcloud app version: 3.2.3

Nextcloud server version: last 13.0.6 (running on virtual machine-/Ubuntu Server 16.04)

### Logs
**some log content of android app**:
2018/09/01 19:48:16
RefreshFolderOperation : Send broadcast com.owncloud.android.operations.RefreshFolderOperation.EVENT_SINGLE_FOLDER_SHARES_SYNCED
2018/09/01 19:48:17
DrawerActivity : **Unknown drawer menu item clicked**: Alle Dateien
2018/09/01 19:48:20
DrawerActivity : **Unknown drawer menu item clicked**: Favoriten
2018/09/01 19:48:20
OwnCloudClient #1 : REQUEST OPTIONS /remote.php/dav
2018/09/01 19:48:20
OwnCloudClient #1 : REQUEST SEARCH /remote.php/dav
2018/09/01 19:48:20
AdvancedSslSocketFactory : Creating SSL Socket with remote xxxxxxxxx:443, local null:0, params: org.apache.commons.httpclient.params.HttpConnectionParams@yyyyyyy
2018/09/01 19:48:20
AdvancedSslSocketFactory : ... with connection timeout 60000 and socket timeout 60000
2018/09/01 19:48:20
ServerNameIndicator : SNI done, hostname: xxxxxxxxxxxxxx
2018/09/01 19:48:22
DrawerActivity : **Unknown drawer menu item clicked**: Aktivitäten
2018/09/01 19:48:22

.....

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by Ukurra** [comment]
### Environment data

Android version:5.1.1

Device model: Samsung Galaxy J3 (2016)

Stock or customized system:

Nextcloud app version: 3.3.0

Nextcloud server version: last 12.0.11

**Logs**
- - - - - - - - - - - - - - - - - -
2018/09/20 09:30:55
Model : SM-J320F

2018/09/20 09:30:55
Brand : samsung

2018/09/20 09:30:55
Product : j3xltejt

2018/09/20 09:30:55
Device : j3xlte

2018/09/20 09:30:55
Version-Codename : REL

2018/09/20 09:30:55
Version-Release : 5.1.1

2018/09/20 09:30:58
Preferences : onPause() ending

2018/09/20 09:30:58
BaseActivity : onRestart() start

2018/09/20 09:30:58
BaseActivity : onRestart() end

2018/09/20 09:30:58
UploadListActivity : onStart() starting

2018/09/20 09:30:58
UploadListActivity : onResume() start

2018/09/20 09:30:58
UploadListActivity : onResume() starting

2018/09/20 09:30:58
OwnCloudClient #6 : REQUEST GET /ocs/v1.php/cloud/user

2018/09/20 09:30:58
AdvancedSslSocketFactory : Creating SSL Socket with remote example.com:443, local null:0, params: org.apache.commons.httpclient.params.HttpConnectionParams@1e8eef9d

2018/09/20 09:30:58
AdvancedSslSocketFactory :  ... with connection timeout 60000 and socket timeout 60000

2018/09/20 09:30:58
ServerNameIndicator : SNI done, hostname: example.com

2018/09/20 09:30:58
ExternalLinks : links disabled

2018/09/20 09:30:58
UploadListActivity : onResume() end

2018/09/20 09:30:59
Preferences : onStop() ending

2018/09/20 09:30:59
Preferences : onDestroy() ending

2018/09/20 09:31:01
DrawerActivity : Unknown drawer menu item clicked: Настройки

2018/09/20 09:31:01
UploadListActivity : onPause() start

2018/09/20 09:31:01
UploadListActivity : onPause() ending

2018/09/20 09:31:01
UploadListActivity : onPause() end

2018/09/20 09:31:01
Preferences : onCreate(Bundle) starting

2018/09/20 09:31:01
Preferences : Error retrieving user's base URI Exception : [com.owncloud.android.lib.common.OwnCloudAccount.<init>(OwnCloudAccount.java:65), com.owncloud.android.ui.activity.Preferences$18.run(Preferences.java:874), java.lang.Thread.run(Thread.java:818)]

2018/09/20 09:31:01
Preferences : onStart() starting

2018/09/20 09:31:01
Preferences : onResume() starting
- - - - - - - - - - - - - - - - - -

**Comment by Joe7new** [comment]
Same problem found in your log-file: 
DrawerActivity : **Unknown** drawer **menu item clicked**: ..
should be fixed ...
regards, Joe

**Comment by sehucke** [comment]
This is not fixed in 3.3.2. The client still logs "Unknown drawer" messages.

**Comment by Joe7new** [comment]
Can't reproduce it now, because of new server setup. But problem even was there when updating to last version of android client. Nevertheless thanks for trying to fix this. 
Sorry, that I can't give you more info for the moment... regards joe

**Comment by sehucke** [comment]
No crashes/freezes so far. But there are still those error messages stating "unknown drawer menu item clicked". Checked that in the logs for activities and settings. But it seems to happen for all menu items.
