### ISSUE TITLE
Set/remove avatar in android client

### ISSUE THREAD

**Issue by sm2017** [nextcloud/android#2949]
There is no option to set/remove avatar in android client

**Comment by AndyScherzinger** [comment]
@rullzer @nickvergessen do you know if there is a service/api for the clients for this?

**Comment by nickvergessen** [comment]
This is not possible yet, but there is an issue already:
https://github.com/nextcloud/server/issues/10549

**Comment by tobiasKaminsky** [comment]
Frankly I am not sure if it worth the effort.
To have it done right, we then also would need some kind of image resizing like on web UI…
(@AndyScherzinger we agreed some time ago, that "approved" label is only set if two people agree on it)

**Comment by mario** [comment]
We need this here and we will probably need it in order to change group
avatars.

**Comment by tobiasKaminsky** [comment]
Why do we "need" this?

**Comment by joshtrichards** [comment]
Seems silly to have this Issue sit around here since it is not actionable. It's not implemented in Server (nextcloud/server#10549) and also doesn't seem to be a high demand feature. We can revisit when/if Server exposes support for it.
