### ISSUE TITLE
Update account list to recyclerview

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#2953]
> The account list is still a list view so we'd need to rewrite it to be a recyclerview to get rid of the dividers (can be done and should be done of course).

- update account list to recyclerview
- remove dividers

**Comment by nantoniou** [comment]
Hello, if this issue can be handled by a new developer, I would like to help with it.

**Comment by AndyScherzinger** [comment]
Hi @nantoniou and welcome to Nextcloud! 🎉 

If you want to take care of this issue, you are more than welcome to do so and we appriciate any help and if you have any questions please feel free to ping @tobiasKaminsky and me ❤️ 

The Activity you are likely looking for is `ManageAccountsActivity`
