### ISSUE TITLE
download of any file not working, crashes dev version.

### ISSUE THREAD

**Issue by sanderboer** [nextcloud/android#2957]
### Actual behaviour
Trying to sync files, app tries to download files, stable version fails. Dev version crashes immediately.
I see in the webserver log an attempt to access a webdav file, if I copy/paste the webdav url in a browser, the file gets downloaded without a problem..

### Expected behaviour
App downloads files onto phone's fs.

### Nota Bene
Download/sync used to work a couple of months ago. Changes since then include ubuntu upgrade to 18.04, nc server upgrade to 13.05 and 13.06, app update to 3.2.3.
I cannot pinpoint exactly when this behavior started. But my gut says it is a change in the android file permissions scheme, as ghost commander too is unable to touch any file besides the ones in the download folder.

Now, the app seems to not be able to touch files on the fs. Once sync used to work, I had a bunch of files on my phone's fs. Now, when I delete some of these files in the app, they're still on the fs. Double checked app permissions, has storage read/write permissions.
 
### Steps to reproduce
Install a fresh nc app,
Connect to server,
In app, select a directory you want to sync, tell it to sync,
app 3.2.3 shows notification "downloading file ...", but stays at 0%
Dev version 20180829 crashes immediately when I want so sync a dir.

### Environment data
Android version:
8.1.0
Device model: 
wileyfox swift 2
Stock or customized system:
stock
Nextcloud app version:
3.2.3 and dev version 20180829
Nextcloud server version:
13.0.6

### Logs
Will post logs if necessary.

**Comment by sanderboer** [comment]
FIXED !
(tested stable app)

It works again after I sanitized all pre-existing data from my phone.
in android 8.1.0:

hold nextcloud app icon-> app-info ->storage-> manage space-> clear data
hold nextcloud app icon-> app-info ->storage-> clear cache

Nice that it is fixed, kind of a bummer that it appears to be a gremlin in android and I need to re-sync 10gb.

**Comment by tobiasKaminsky** [comment]
Indeed, this is already solved and will be available in next dev version.
On gplay/fdroid we will publish a RC2 this afternoon.

**Comment by Wikinaut** [comment]
I confirm, that the issue has been fixed! (thanks)
