### ISSUE TITLE
Feature request: connection status

### ISSUE THREAD

**Issue by artur3** [nextcloud/android#2959]
Please add some kind of notification (colour, icon) to be visible when app is connected to the server or not.

Also maybe autostart of VPN client for 
cellular connections and unknown WiFi.

**Comment by tobiasKaminsky** [comment]
![2018-09-04-112536](https://user-images.githubusercontent.com/5836855/45022746-44deaf80-b035-11e8-8d5d-717cc09e819f.png)

On upcoming 3.3.0 we will have an indicator if there is no internet connection.
I hope that this will also fit your needs, as being offline is (hopefully) a less often state.

**Comment by artur3** [comment]
My phone is almost always connected to internet but Nextcloud server is only available by home WiFi or VPN.  

This is also good to indicate some problems with a server. Specially for new users.

**Comment by AndyScherzinger** [comment]
I'd say the only thing we don't show at the moment is "server unreachable" the reason will always be unknown to the client since the client can't know why the server can't be reached.

I strongly vote against showing that the client is connected to the server since that is the standard case so there is no need to show that. While I understand this scenario here I consider it an edge case. Just my personal opinion though.

**Comment by artur3** [comment]
Showing that there is "no connection" instead "connection" is absolutely fine.

"No internet connection" is usually somehow displayed by OS.

**Comment by AndyScherzinger** [comment]
> Showing that there is "no connection" instead "connection" is absolutely fine.

:+1:

**Comment by tobiasKaminsky** [comment]
Then we can close this.
If you experience any problem with 3.3.0, please re-oen.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky does 3.3.0 also show "no connection"?

**Comment by artur3** [comment]
1. You can have no internet connection but still can connect to the Nextcloud server 

2. Have internet connection but can't establish connection to Nextcloud server.

**Comment by tobiasKaminsky** [comment]
We are checking if there is no network connection or if the host/nexctloud is not available. 
It will only be shown if a connection is unsuccessful. 

We can change the working to "No connection to Nextcloud"?

**Comment by AndyScherzinger** [comment]
I'd say we should have two distinct messages for the two scenarios since they mean different things.
