### ISSUE TITLE
Block server communication on metred networks

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#296]
issue raised in #158 

The client with 1.3.0 made a first step in honoring metered connections by not triggering instant uploads on metred wifi connections. This should be extended to any kind of server communication while to not render the app useless on metered networks by asking the user if the communication should be blocked or not (and then saving this to the apps preferences to revert the decision).

What do you think @tobiasKaminsky @nextcloud/designers ?

**Comment by tobiasKaminsky** [comment]
All automatic sync/connections should respect the metered network (mainly the automatic account sync atm)
But if an user opens the app I guess he knows what he/she is doing and really wants it.

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger what do you say to my answer?
Updating the file list is a rather small data transfer so it seems fine to me.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky I agree in general. I guess the problem is when you setup the app on a metered network and the file-tree sync kicks in and uses a lot of the (paid) data/transfer. So yeah, when navigation through the app it's fine to communicate with the server but any auto stuff happening in the background should be blocked.

**Comment by tobiasKaminsky** [comment]
That's what I wrote here https://github.com/nextcloud/android/issues/296#issuecomment-250530814 ;-)
