### ISSUE TITLE
Asks for Password every few seconds

### ISSUE THREAD

**Issue by oschult** [nextcloud/android#2961]
### Actual behaviour
The App asks every few seconds for the password.

### Expected behaviour
Stay logedin until the session will be closed
 
### Steps to reproduce
1. Install App
2. Login
3. Open some Dokuments and wait for a while

### Environment data
Android version: 8.0.0 (Sec. 01.08.2018)

Device model: Samsung S8

Stock or customized system: Stock

Nextcloud app version: 3.2.4 (04.09.2018)

Nextcloud server version: 11.0.2.7 (www.stadtwerke-cloud.de)
It is a service provider. I can't change it.

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
@oschult I know you can't change the server and this isn't meant in an offensive way but there is only one way for you to fix this which is install the Android client 2.0 from the download server: https://download.nextcloud.com/android/nextcloud-20000199.apk 

To be able to use 3.x of the Android client, the server needs to be at least 11.0.8 and even then Nextcloud 11 is end-of-life and so will 12.x be in a couple of days. So even with 11.0.8 future versions of the client are likely to fail.

**Comment by AndyScherzinger** [comment]
other than that, there is https://play.google.com/store/apps/details?id=de.cloud.stadtwerke so it seems the provider is also shipping it's own client, so they need to make sure it still works.

**Comment by oschult** [comment]
Yes, I know that client. It crashes when I try to open PDF-Dokuments from the cloud.
Thanks for the hint to the older version of the app. I will try it!

**Comment by oschult** [comment]
The older app version seems to work for me! :-)
I already made a comment to the app and I wrote to the helpdesk of the provider, but no response!
Thanks a lot for your help!

**Comment by AndyScherzinger** [comment]
You are very welcome, sorry you are missing out on the newer app releases of Nextcloud due to the server restriction. Maybe your provider will upgrade the server at some point which they should anyways due to security vulnerabilities...
