### ISSUE TITLE
Enhancement: Download to...

### ISSUE THREAD

**Issue by Gatak** [nextcloud/android#2963]
### Actual behaviour
- Selecting a file to Download only downloads the file to NCs app .

### Expected behaviour
Give the user a choice where to download the files to.

**Comment by tobiasKaminsky** [comment]
What would the benefit of this? After downloading you can open the file with any app (open with).
Downloading the file to any arbitrary destination will prevent the app from keeping it in sync.

**Comment by AndyScherzinger** [comment]
I'd also vote to keep it as-is for the argument mentioned + this is a mobile app behaving like mobile apps in the ecosystem of Android meaning browsers and others also don't let the user choose the download location since this will cause quite some other problems with the OS in the long run (file system permissions)

**Comment by Gatak** [comment]
I use Opera browser and get to choose where to download too.

The purpose of sometimes downloading to another folder is for example adding some music files to my music folder for playback in another app. Same goes for videos and movies. It isn't necessary to keep these in sync.

Other options are if I want to make other compilations of files in specific folders. 

This is quite easily possible with most webdav clients, but I do prefer the pen source native nc app :)

**Comment by tobiasKaminsky** [comment]
Then you can still use a native file browser to move the downloaded files to any other folder.
VLC also allows to browse the media collection, despite of the real "location" on phone.

As there are some alternatives to do this and explained for the reasons why we do not want to include this, I hope you are fine that we close this issue.

**Comment by Gatak** [comment]
@tobiasKaminsky i don't agree with your statement:
> After downloading you can open the file with any app (open with)

I have use case from today. I wanted to export settings from an app on one phone and import it on another phone. The settings file is a regular xml file.
Steps taken. 

1. On first phone. It was easy to upload the file in the NC app as it allows the user to upload from any arbitrary folder.
2. Second phone. Click Download in NC app. 
3. Select Open With. I get the usual selection of text editors etc. But not my app I wanted. There is no show all apps.
4. Now I have to use the app itself to look for the file. After some searching I realise it was in sdcard/Android/media/com.nextcloud.client/files/...

I think that most users would not know how to look for files there. Yes, I know the path is in settings, but it's not always the same in all apps. Some say /sdcard, /storage/sdcard, /storage/4E4B-B8FE/ or simply "6" on my phone, a pretty recent Samsung A5 with Android 8. 

So, in my humble opinion this could have been simpler.

**Comment by tobiasKaminsky** [comment]
It should be possible to use the other app to open the desired file, which then opens up 
![2018-09-10-110313](https://user-images.githubusercontent.com/5836855/45287671-1fe0b580-b4e9-11e8-8476-c1e6c58ac173.png)

There you can browse the downloaded files from NC, without knowing the path.
(This is the desired/common android way)

**Comment by Gatak** [comment]
You're right. The  specific app I used used only its built in file browser / picker.

I've learnt something from  your comments and using the file picker like that lets me open  any file from my NC :)

So, I'm sorry for the long and overly pushy comments from my side.

**Comment by tobiasKaminsky** [comment]
No problem, glad that you found a way that is working for you.

Do you have an idea how we can make this more visible / understandable to the user?
Not every one is asking here…
