### ISSUE TITLE
Fix logging in beta app

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#297]
All recent issue reports when asking for the beta app's log reply with the fact that the log is empty which seems to be an issue and need to be solved in order to gain the necessary information to solve the actual issues that got reported.

At least installed via Android Studio (thus with debug flag) my logged are filled, same if I install it from f-droid.

Any idea @tobiasKaminsky ?

---

TODO:
improve logging on standard beta client installations to find
- [ ]  "UNKNOWN_ERROR" https://github.com/nextcloud/android/issues/288#issuecomment-251504857
- [ ] Unexpected exception https://github.com/nextcloud/android/issues/287#issuecomment-250549099

**Comment by tobiasKaminsky** [comment]
We need to collect the device and android version and see if there is something in common.

**Comment by radegand** [comment]
Hi,
I've reported issue #288 and I have Nexus 5X on Android 7.0, build number NRD90R. I can provide more logs if someone points me to what's the best way to get them.
Thanks.

**Comment by AndyScherzinger** [comment]
added https://github.com/nextcloud/android/pull/169/commits/59355d38d5de3babcff3369ebe7d15be7dfef719 to gain the result code for issue #288

**Comment by AndyScherzinger** [comment]
added https://github.com/nextcloud/android-library/commit/c1ebf063043b076caba0cd51f31e3f3fa2fc2151 to log the exception type and message for issue #287 (ven though log suggest this is related to chunking)

**Comment by iskradelta** [comment]
Hello friends,

in MainApp the check is if (BuildConfig.DEBUG) but DEBUG is not set to true when checking the built with baksmali - but we have BUILD_TYPE set to DEBUG - which seems reasonable - so the fix is a simple "DEBUG".equalsIgnoreCase(BuildConfig.BUILD_TYPE) which seems simpler than to figure out why gradle doesnt set the variable DEBUG or somehow force it to do it when build type is debug... Im new to this.

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger 
@iskradelta found the error and we added it to beta.
Please test and close it.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky this might still be an issue in some way, see #979 :/

**Comment by hechi** [comment]
Hey still no logs for me :(
Nextcloud Android App: 20170509
![screenshot_20170512-164745](https://cloud.githubusercontent.com/assets/3808354/26003481/12aedc50-3733-11e7-9385-5eeacfe3c99f.png)

**Comment by tobiasKaminsky** [comment]
Then I was too fast...
@hechi can you give me some more details? Do you use an external sdcard? which device?

**Comment by hechi** [comment]
Hey @tobiasKaminsky 
Android version: 6.0.1
Device model: Moto 4G
Stock or customized system: Stock + Root
Nextcloud app version: 20170509
Nextcloud server version: 11.0.3
Storage ist now **/storage/emulated/0** before updating to 20170509 it was unknown

**Comment by tobiasKaminsky** [comment]
@hechi this will be in the next dev version.
Please give it a try and report back :+1:

**Comment by hechi** [comment]
Hey @tobiasKaminsky logs are now working :+1: if the problem appears again i will report it back with more logs :)
