### ISSUE TITLE
android 7 never starts instant upload

### ISSUE THREAD

**Issue by lachlan-00** [nextcloud/android#299]
### Actual behaviour
-no matter what settings I choose for instant upload nothing is ever uploaded automatically.
-wifi/charging/subfolders/etc and the app has all permissions available but will never start after photo.
-there is no information in the server log about uploads
-manual upload and move works
 
### Steps to reproduce
1. Use a nexus 5x with stock 7
2. Use any nextcloud app
3. Take a photo

### Environment data
Android version: stock Android 7

Device model: nexus 5x

Stock or customized system: stock with root

Nextcloud app version: 1.3.1

Nextcloud server version: 10.0.1

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

**Comment by lachlan-00** [comment]
Camera hdr!

The default setting for the camera in nougat is auto hdr processing so the upload hook never gets started.

When I take a photo I get a notification that hdr is processing then no upload. Turn hdr off and the upload works. That means that the camera app in stock is only doing one action when taking a photo and the upload is ignored

**Comment by AndyScherzinger** [comment]
@lachlan-00 what device are you using since HDR on/off doesn't trigger the upload on my Nexus 5X which is due to the fact that according to documentation Androi 7 doesn't trigger the "new photo" event anymore so the app doesn't get informed about the fact that a picture has been taken.

**Comment by lachlan-00** [comment]
5x, using stock 7.0 with the September security updates. (Nrd90s)

Disabling hdr is the only way uploads will work

**Comment by AndyScherzinger** [comment]
Hmmm, strange. Just gave it another try, with hdr disabled and it doesn't trigger any uploads... :(

**Comment by lachlan-00** [comment]
It might have been a coincidence. It doesn't work at all for me now. Hdr or not

**Comment by zoff99** [comment]
no coincidence. on android 7 its never triggered anymore.

**Comment by zoff99** [comment]
thats why this is also giving up:
https://github.com/M66B/FineGeotag

**Comment by AndyScherzinger** [comment]
@zoff99 that's why we are already working on a new/different solution/approach on how to handle instant upload (using the JobScheduler): https://github.com/nextcloud/android/tree/syncedFolders - still quite some more work to do to get this complete, please bear with us :pray: THis is quite the challange to do it right.

**Comment by zoff99** [comment]
will this work as a replacement for the "hook"?
i like to fix https://github.com/M66B/FineGeotag for nougat if possible

**Comment by lachlan-00** [comment]
Good to know! No point keeping this open if it's work in progress

**Comment by AndyScherzinger** [comment]
reference issue for implementation infos: #285
