### ISSUE TITLE
Nextcloud Sync

### ISSUE THREAD

**Issue by b1ggjoe** [nextcloud/android#30]
Team,

Following up on my post here:

https://help.nextcloud.com/t/learning-from-other-open-source-projects-like-syncthing/600?u=joe

Would it be a good idea to consider forking off this project, in order to create the ultimate 'Nextcloud Sync' app for Windoze, Apple OS, Linux as well as iOS and Android mobile?

Here's the project: https://syncthing.net/

Think of it, there's a whole community following all working on just this aspect of 'Syncing' alone.

J.

**Comment by tobiasKaminsky** [comment]
After a quick look the sync process seems to be completely independent from "our" system.
So this will not work...
Maybe we can get inspired by some ideas. Maybe you can help us here if you have insight on their app and can tell us what works better?

**Comment by b1ggjoe** [comment]
Hello Tobias,

Sure, I would love to help in any way that I can. I'm not a coder nor do I
know the first thing about development...but I'd like to learn some day.
Yes, in the mean time...it's very interesting with 'Syncthing'.

At first, the concept of 'Syncthing' seems like competition to services
like Nextcloud, ownCloud, DropBox and etc. It did start out this way
actually, sort of.

When the likes of 'BTSync' (renamed to just 'Sync) and then 'Syncthing'
came out, the goal was to make it easy for people to accomplish the File
Sync/Backup operations WITHOUT having to subscribe to the likes of DropBox,
SugarSync and so forth.

They weren't targeting Open Source projects like ownCloud or Nextcloud.

However, once I fully understood the 'vision' it's actually almost
identical to our vision with Nexcloud. It's about 'liberating' your data
and putting you in full control of it. Albeit, two completely different
paths...with the same goal in mind. Some of the concepts that the team at
Syncthing subscribe to, such as 'Open Development, Open Discourse' are at
it's core, some of the very core philosophies that caused the shift away
from ownCloud and gave birth to Nexcloud...the two visions are almost the
same.

The reason I even brought up Syncthing to begin with is because their sole
focus is a singular one: 'Syncing' capabilities.

With a following of more than 12,000 followers, that's more than
owncloud/core.

My thoughts were that perhaps somehow 'partnering' between the two
communities would help further spread the vision of both Nextcloud and
Syncthing.

Anyway, as you can see...just my thoughts.

I tend to over think everything...as my wife says LOL

BJ

**Comment by b1ggjoe** [comment]
OBTW,

Although this is *slightly* dated, this is one of the best videos that I have ever seen on Syncthing. It's an excellent overview on Syncthing and the overall user experience:

[https://www.youtube.com/watch?v=ycVM5pdH3xg](url)

BJ.

**Comment by Spacefish** [comment]
Syncthing is some sort of p2p folder synchronisation script written in Go with a Web Frontend. They have some sort of "central" server which handles meta information and allows client discovery. The concept is different from Nextcloud.
P2P synchronisation would make sense imho, if you have your mobile connected to the same LAN on which a Nextcloud PC client resides. If someone in the network already has the file you are trying to pull from an Nextcloud server behind a WAN link, you would circumvent the possibily slow WAN link by locally transfering the file. Much like Dropbox Lan-Sync

B.t.w. Nextcloud isn´t a hosted cloud provider like G Drive or Dropbox, you can run the script on your own server / infrastructure, thereby already putting you into control of your data.

**Comment by tobiasKaminsky** [comment]
@Spacefish the idea with lan sync is something that is a great idea and should be opened as a new issue on /core.

Regarding the syncthing, as I said before I do not think that we can implement this.
