### ISSUE TITLE
Uploads wait for device charging, even when not selected

### ISSUE THREAD

**Issue by pludi** [nextcloud/android#300]
### Actual behaviour
Video uploads are kept in the state "waiting for device charging", even though that option isn't active. Images upload as intended.

### Expected behaviour
Videos should start uploading on WiFi connection.
 
### Steps to reproduce
1. Activate instant video upload, select uploading only when connected to WiFi 
![Screenshot](https://cloud.githubusercontent.com/assets/2112148/19016273/9acf8864-8815-11e6-91a8-199522a281a6.png)

2. Take a video
3. Watch the Upload tab of the app 
![Screenshot](https://cloud.githubusercontent.com/assets/2112148/19016268/744b70b8-8815-11e6-8ef4-b9579b555822.png)

### Environment data
Android version: 5.1.1

Device model: Zuk Z1

Stock or customized system: Stock

Nextcloud app version: 1.3.1

Nextcloud server version: 10.0

#### Web server error log
Not applicable, no upload happening

#### Nextcloud log (data/nextcloud.log)
Not applicable, no upload happening

**Comment by tobiasKaminsky** [comment]
Solved by #312
