### ISSUE TITLE
Use native Android file browser when uploading files within NC

### ISSUE THREAD

**Issue by erikw** [nextcloud/android#3001]
When uploading files from within the NC app, it uses a custom file browser (screenshot 1). It would be much nicer if could use the standard file browser in Android (screenshot 2), because then the use can upload from different apps like Google Drive Dropbox, Google Photos etc. This dialog is most other apps use and it is something Android users are used too. 

This gives the user a much wider choice of files to upload, and much easier to find. I think this is way more important than the custom feature of whether to keep the original file or not after upload with the current file browser in NC.

![screenshot_20180908-095630](https://user-images.githubusercontent.com/175286/45251891-3ef71000-b34e-11e8-9c68-2d110884b228.png)

![screenshot_20180908-100025](https://user-images.githubusercontent.com/175286/45251888-39012f00-b34e-11e8-9903-63666f772b95.png)

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
I agree. Why 'reinvent the wheel'?

**Comment by AlvaroBrey** [comment]
Not sure why I got notified of this issue now. But either way, it's implemented, choose "Upload content from other apps" in the upload menu.
