### ISSUE TITLE
[3.3.0 RC2] Crash of the Nextcloud application

### ISSUE THREAD

**Issue by ghost** [nextcloud/android#3011]
Hello,

I contact you to report a bug in the beta version of nextcloud android.

When somebody posts an announcement, i receive a push notification. I clicked above that opened Nextcloud application then the application crash. She closed and I had an error message "L'application Nextcloud a cessée de fonctionner". 

I have retry several times unsuccessfully.

Regard,
Sim59121

**Technical information**

Android version : 7.1.1

Device model : SM-J52016

Nextcloud app version : 3.3.0 RC2

**Comment by AndyScherzinger** [comment]
Hi @Sim59121,

Thanks for the report! Could you please attach a logcat? If possible, of course.

**Comment by Sim59121** [comment]
Hi ! 

I'm not the administrator of the instance.
I'm just a user of this instance...

How i can get the log ? 

I also whrite to the administrator of the instance.

**Comment by AndyScherzinger** [comment]
@Sim59121 logcat refers to the log of the device, not the server, see Section about logs here: https://github.com/nextcloud/android/blob/master/README.md

Does the app in general still work and the crash only happens when you click on a notification?

**Comment by AndyScherzinger** [comment]
Thanks for the feedback!

@tobiasKaminsky are you able / have the time to reproduce this?

**Comment by Sim59121** [comment]
Hello,

Thank you for your help and your answer.

You can close the topic and work on this bug (if you work at nextcloud) ?

If you need informations, you can contact me.

Regard,

**Comment by Sim59121** [comment]
Hello,

Thank you for your help and your answers.

Can i close the topic ? Do you need more informations to work on this bug ? 

Regard,

**Comment by AndyScherzinger** [comment]
@Sim59121 the topic stay open until it got fix by a developer, when a fix has been done the issue gets auto-closed :)

**Comment by Sim59121** [comment]
Ok ! 

So, i wait.

**Comment by tobiasKaminsky** [comment]
Too few infos to debug :-(
