### ISSUE TITLE
[3.2.4/3.3.0RC] Sharing broken

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#3014]
When I share a file with an Nc user of the same instance (probably the same for any other kind of sharing) it fails with the corresponding snackbar while the share is actually created when checking the webUI.

The reason for this: The server for me Nc14 / for a user in the forum Nc 13 (https://help.nextcloud.com/t/sharing-not-possible-teilen-nicht-moglich/36636/6) is replying with the result code 35 with translates to the ordinal value `35`-> `SHARE_FORBIDDEN` and the mData value `Connection could not be established with host 127.0.0.1 [Connection refused #111]`. This might be a server (configuration issue) or a client side change to the interpretation of the server response, that I don't know :/

Android 7/8
Client 3.2.4 and latest master

![share](https://user-images.githubusercontent.com/1315170/45362339-d9688500-b5d4-11e8-92e3-cfa57456f330.png)

**Comment by AndyScherzinger** [comment]
Also cc @nextcloud/server-triage to check if this might be server related

**Comment by tobiasKaminsky** [comment]
- emulator -> local dev server --> NOT working
- 3.3.0 RC2 on real phone -> NC14 productive server -> working

**Comment by AndyScherzinger** [comment]
The connection could not be established error message is sent by the server. I also saw this error for sharing in the web UI of 14.0.0 RC1 but it vanished with the stable (didn't check RC2 of Nc14).

@tobiasKaminsky Is your local server http and your productive server https? Just asking since my productive server is http!

**Comment by tobiasKaminsky** [comment]
Yes:
https on productive
http on local machine

--> Testet with latest master on emulator and productive server -> working

**Comment by AndyScherzinger** [comment]
> --> Testet with latest master on emulator and productive server -> working

Well, I guess it might be related to https while that would be quite a bug and "lease use https" shouldn't be the workaround/solution ;)

**Comment by tobiasKaminsky** [comment]
Let us wait on server input for this…

**Comment by AndyScherzinger** [comment]
I did a share by user (from user A to user B within the same server)

**Comment by burner-** [comment]
I install new vm with ubuntu 18.04. Then I installed nextcloud with this procedure https://github.com/nextcloud/vm
I access that server with windows machine with google chrome and I can confirm that I hit to this same problem. Share will do false positive error message each time.

**Comment by tensberg** [comment]
> Connection could not be established with host is from our 3rd party lib which we use to send emails.
> I guess this shouldn't break sharing though (only if you do a share by mail)

At least for me the problem really was that I had no mailserver configured in my Nextcloud test installation. Configuring one fixed the sharing error.

Apparently Nextcloud 14 always sends a mail to the persons you're sharing with, see https://github.com/nextcloud/server/issues/11216
