### ISSUE TITLE
Download der Foto Vorschaubilder dauert sehr lange

### ISSUE THREAD

**Issue by StefanTux19** [nextcloud/android#3016]
### Actual behaviour
- Tell us what happens
Download der Foto Vorschaubilder dauert sehr lange. Viele Bilder werden überhaupt nicht angezeigt.

### Expected behaviour
- Tell us what should happen
Download der Vorschaubilder muss schneller werden. Sonst ist das Fotoerlebnis schlecht.
 
### Steps to reproduce
1. 
2. 
3. 

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
This is mostly a problem of the server as the server has to generate preview images in the correct sizes.
To test if this is really the cause, you can wait until one folder is completely loaded and then clear the app's cache and re-enter the folder.
Then it should be much quicker.

You can also use https://github.com/rullzer/previewgenerator to generate the previews in advance and not on demand.

**Comment by AndyScherzinger** [comment]
> You can also use https://github.com/rullzer/previewgenerator to generate the previews in advance and not on demand.

while again the preview generator would have to generate the previews in the requested resolution, right?

**Comment by tobiasKaminsky** [comment]
@Zeromax ok, you are talking about the photo section. This is unfortunaly known and currently a search limitation of the server. We hope to have a better way on next server release (NC15).
I assumed that @StefanTux19 is talking about the regular file list.

**Comment by Zeromax** [comment]
Ah OK. I thought it is related. Thanks for the clarification.
