### ISSUE TITLE
Animated GIFs broken

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#3020]
with latest master (maybe earlier version too) the animated gifs (downloaded images) aren't animated anymore :(

Android 8.1
App: `master branch`
Server: 14.0.0

**Comment by tobiasKaminsky** [comment]
On stable 3.3.x branch it is working for me.
So we need to fix this for 3.4.

**Comment by AndyScherzinger** [comment]
actual guess (untested) is that this is related to the photoview lib update

**Comment by tobiasKaminsky** [comment]
What is happening when you click on a gif? Do you see an image, but no animation?

I see a white background with blue spinning circle, and after quite a while it is showing the gif (OP3 with dev).
On master with emulator, it is working right away :/

**Comment by AndyScherzinger** [comment]
Erm, this is embarrassing... just tried the latest master (again) and now it also works for me, GIF has the animation... strange... So I guess we can close it then
