### ISSUE TITLE
App (All versions)  crashes frequently if there are files/folders in the user folder root that are shared in chat

### ISSUE THREAD

**Issue by gradinaruvasile** [nextcloud/android#3021]
### Actual behaviour
- The app crashes randomly in most screens where there are files/folders. Started happening after server was upgraded to 14

The error seems to be 
```
android java.lang.IllegalArgumentException: Empty values
at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1619)
```

### Expected behaviour
- It should not crash
 
### Steps to reproduce
1. Install app (Server NC 14)
2. log in
3. Watch it crash

### Environment data
Android version:
8.1.0
Device model: 
Lenovo K6
Stock or customized system:
Runs Lineage OS
Nextcloud app version:
All versions (Play Store 3.2.4, 3.3.0 RC2, FDroid 3.2.3, FDroid Dev)
Nextcloud server version:
14
### Logs
```
09-12 01:30:17.461 21931 22134 E AndroidRuntime: FATAL EXCEPTION: Thread-14
09-12 01:30:17.461 21931 22134 E AndroidRuntime: Process: com.nextcloud.client, PID: 21931
09-12 01:30:17.461 21931 22134 E AndroidRuntime: java.lang.IllegalArgumentException: Empty values
09-12 01:30:17.461 21931 22134 E AndroidRuntime: 	at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1619)
09-12 01:30:17.461 21931 22134 E AndroidRuntime: 	at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1599)
09-12 01:30:17.461 21931 22134 E AndroidRuntime: 	at com.owncloud.android.providers.FileContentProvider.updateFilesTableAccordingToShareInsertion(FileContentProvider.java:424)
09-12 01:30:17.461 21931 22134 E AndroidRuntime: 	at com.owncloud.android.providers.FileContentProvider.insert(FileContentProvider.java:314)
09-12 01:30:17.461 21931 22134 E AndroidRuntime: 	at com.owncloud.android.providers.FileContentProvider.insert(FileContentProvider.java:258)
09-12 01:30:17.461 21931 22134 E AndroidRuntime: 	at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:302)
09-12 01:30:17.461 21931 22134 E AndroidRuntime: 	at com.owncloud.android.providers.FileContentProvider.applyBatch(FileContentProvider.java:698)
09-12 01:30:17.461 21931 22134 E AndroidRuntime: 	at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:317)
09-12 01:30:17.461 21931 22134 E AndroidRuntime: 	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:465)
09-12 01:30:17.461 21931 22134 E AndroidRuntime: 	at android.content.ContentResolver.applyBatch(ContentResolver.java:1578)
09-12 01:30:17.461 21931 22134 E AndroidRuntime: 	at com.owncloud.android.datamodel.FileDataStorageManager.saveSharesInFolder(FileDataStorageManager.java:1562)
09-12 01:30:17.461 21931 22134 E AndroidRuntime: 	at com.owncloud.android.operations.RefreshFolderOperation.refreshSharesForFolder(RefreshFolderOperation.java:545)
09-12 01:30:17.461 21931 22134 E AndroidRuntime: 	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:222)
09-12 01:30:17.461 21931 22134 E AndroidRuntime: 	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:316)
09-12 01:30:17.461 21931 22134 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
09-12 01:30:17.465  2185  9201 W ActivityManager:   Force finishing activity com.nextcloud.client/com.owncloud.android.ui.activity.FolderPickerActivity
```

#### Web server error log
```

```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by gradinaruvasile** [comment]
I just built the app from git and it still crashes.

**Comment by gradinaruvasile** [comment]
That was my thinking too.
The issue started when i upgraded to the Play Store 3.3.0 RC2. Afterwards i uninstalled it, reinstalled and the issue persisted even with the stable, RC, dev versions, both from Play Store and FDroid. I uninstalled a few times, same problem.
What should i clean? I removed the directory created under the local storage a few times. Maybe there are leftover files in the user/0/ directory?

PS I too verified another client and that had no issues. Granted, that was a stable 3.2.4 from Play Store that was never "disturbed".

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky can you help out here with storage paths that need to be checked, data that might need to be purged?

**Comment by AndyScherzinger** [comment]
Hmmm, can you go through Android's 
settings -> apps -> Nextcloud -> storage -> manage space -> clear data

**Comment by gradinaruvasile** [comment]
> Hmmm, can you go through Android's
> settings -> apps -> Nextcloud -> storage -> manage space -> clear data

Did that, i even uninstalled the app repeatedly, installed different flavors, all from Play Store , from FDroid and even i compiled the latest git myself. All exhibited the exact same issue.
Now i connected through adb root and checked the user folder as i uninstalled the client. The data folder was removed from the user 0's home folder. I manually removed the folder from the internal storage. 
Now it might be some peculiarity with my user profile but until NC 14 this was not an issue.

**Comment by AndyScherzinger** [comment]
any idea @tobiasKaminsky ?

**Comment by tobiasKaminsky** [comment]
Uninstalling the app removes also the database, so this should be enough.

From stacktrace it seems to be related to sharing.
Can you try to use a new user?
Are there any shares in the folder when it is crashing?

**Comment by gradinaruvasile** [comment]
Yes there are a few shares. Not important i can remove them.

**Comment by tobiasKaminsky** [comment]
Are those shares any special? Are they correctly shown in webUI?

**Comment by gradinaruvasile** [comment]
Hmm. I removed the shares and left only one (which i need), cleared the app cache and since then no crashes.

**Comment by gradinaruvasile** [comment]
> Are those shares any special? Are they correctly shown in webUI?

No, just were shared with a group i think. One of them was i think shared also in a chat session.

**Comment by tobiasKaminsky** [comment]
> One of them was i think shared also in a chat session.

Maybe this is the problem.

According to the stacktrace something is empty. Maybe the group was deleted only partially.
May I ask you if you can play a bit and see if you can trigger it again?

Thank you for your help!

**Comment by gradinaruvasile** [comment]
So i was able to reproduce it.
I shared the "About.txt" file in a chat with another account. The file is still in the root folder of my account.
Now if i open the NC app, it crashes. 
I removed the sharing and it works.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky not sure, so re-opening since it still gets reported for 3.3.0 stable, see dev console:
```
Today, 12:46 PM on app version 30030099
Xiaomi MI MAX (hydrogen), Android 7.0
Report 1 of 3
java.lang.IllegalArgumentException: 
  at android.database.sqlite.SQLiteDatabase.updateWithOnConflict (SQLiteDatabase.java:1543)
  at android.database.sqlite.SQLiteDatabase.update (SQLiteDatabase.java:1523)
  at com.owncloud.android.providers.FileContentProvider.updateFilesTableAccordingToShareInsertion (FileContentProvider.java:424)
  at com.owncloud.android.providers.FileContentProvider.insert (FileContentProvider.java:314)
  at com.owncloud.android.providers.FileContentProvider.insert (FileContentProvider.java:258)
  at android.content.ContentProviderOperation.apply (ContentProviderOperation.java:302)
  at com.owncloud.android.providers.FileContentProvider.applyBatch (FileContentProvider.java:698)
  at android.content.ContentProvider$Transport.applyBatch (ContentProvider.java:316)
  at android.content.ContentProviderClient.applyBatch (ContentProviderClient.java:438)
  at android.content.ContentResolver.applyBatch (ContentResolver.java:1329)
  at com.owncloud.android.datamodel.FileDataStorageManager.saveSharesInFolder (FileDataStorageManager.java:1562)
  at com.owncloud.android.operations.RefreshFolderOperation.refreshSharesForFolder (RefreshFolderOperation.java:556)
  at com.owncloud.android.operations.RefreshFolderOperation.run (RefreshFolderOperation.java:217)
  at com.owncloud.android.lib.common.operations.RemoteOperation.run (RemoteOperation.java:316)
  at java.lang.Thread.run (Thread.java:760)
```

**Comment by AndyScherzinger** [comment]
Argh, okay, reviewed and merged now
