### ISSUE TITLE
Handling of conversation shares

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/android#3029]
In Nextcloud 14 there was a new share type introduced: `10`
https://github.com/nextcloud/server/blob/857bb4536628814cdae3591c795bb1e21e9704b7/lib/private/Share/Constants.php#L42

It would be nice if the shares are flagged as `displayname (conversation)` when listing all the shares, and when you also would allow to create such shares in the client. You can test this easily, by going to an instance with talk installed, create a conversation "Test room", go to the files app, open the share sidebar and try to share with "Test room". There should be a suggestion `Test room (conversation)`

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky is already working on this, labeled it enhancement, prio:high and release 3.3.0 since this scenario will render a client unusable at the moment (crashes) in case a user has a share via talk.

**Comment by nickvergessen** [comment]
(I know, he asked me to create the issue for public tracking)

**Comment by AndyScherzinger** [comment]
I just added the comment to anybody reading this issue is aware of the fact that somebody is already working on it and isn't picking it up ending with a PR that won't get merged :)

**Comment by tobiasKaminsky** [comment]
We have #3033, which prevents the app from crashing when an unknown share type occurs.
I am working on a real usage of ROOM share type, but this will not happen in 3.3.0 as this requires lots of changes.

As there is a fix, I remove "high" and milestone.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky afaik this has been solved, right?

**Comment by tobiasKaminsky** [comment]
Yes, we can now share files to a conversation :+1:
