### ISSUE TITLE
When Downloading Files the `modify date` is not set right

### ISSUE THREAD

**Issue by mist** [nextcloud/android#3040]
### Actual behaviour
- The Filesystem modify date is set to the current date

### Expected behaviour
- The Filesystem modify date is set to the modify date in nextcloud (=original modify date = desktop client downloaded file modify date)
 
### Steps to reproduce
1. "Alle Dateien" (all files)
2. Open any folder
3. Open any file
Alternatively
2. Synchronize any folder

### Environment data
Android version: 7.0 Secpatch 2018-06-01

Device model: SM-T719

Stock or customized system: stock

Nextcloud app version: 3.2.3 (fdroid)

Nextcloud server version: 13.0.4.0

### Comment
I guess this is a feature request. If not I can provide client logs.

**Comment by AndyScherzinger** [comment]
> I guess this is a feature request. If not I can provide client logs.

Can't day if it is a bug or a feature request but I agree downloads should respect the files meta data and preserve it. What do you think @tobiasKaminsky ?

**Comment by mist** [comment]
Ok, I digged a little deeper and found out that on my other Android the modify-date is set correctly after downloading.
Maybe it has something to do with the files being on an SD-Card?

**Comment by mist** [comment]
New phone, new installation, now it works on the SD card aswell...
So if you didn't change anything this is a worksforme now.

**Comment by tobiasKaminsky** [comment]
Thanks for feedback, then I'll close.
