### ISSUE TITLE
App crashes everytime after opening

### ISSUE THREAD

**Issue by Gerrixx** [nextcloud/android#3046]
### Actual behaviour
- Tell us what happens
directly after opening of the app, it crashes. 

### Expected behaviour
- Tell us what should happen
 
### Steps to reproduce
1. open
2. wait one or three seconds 
3. crash
4. afterwards a banner with a request of a report appears 

### Environment data
Android version: 6.0.1

Device model: one plus one

Stock or customized system: cyanogen 13.1.2

Nextcloud app version: 3.2.4

Nextcloud server version: 13.0.6

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by Gerrixx** [comment]
hi, after the app update to 3.3.0 it works again.

**Comment by AndyScherzinger** [comment]
Thanks for the feedback @Gerrixx :heart:
