### ISSUE TITLE
Feature request -- Port knocking before sync attempt

### ISSUE THREAD

**Issue by skewty** [nextcloud/android#3047]
For security reasons I don't like to leave my NextCloud server always exposed on the internet.  Something as simple as a port knocking feature would allow security conscious people to expose their server for a brief period (for new connections) of time after a port knock.

In this scenario, firewall rules allow established connections to pass through just fine.  But new ones would only be permitted for say 10 seconds or 5 minutes on that port number.  [Wikipedia link](https://en.wikipedia.org/wiki/Port_knocking)

If I could specify a port knock port number and timeout (in case several shorter lived connections are made by the android app) this would likely be sufficient UI elements.

IMO, this would go a long way towards helping home users more securely host their own nextCloud and reduce the amount of stories we hear on the Internet about non updated versions of nextCloud being hacked.

**Comment by Gatak** [comment]
Port knocking is mostly a security by obscuring. It gives the perception of being more secure than it may be. That said it would probably stop many of the automated random scans against your system.

You can implement it with iptables. 

On the other hand, if may simpler to use a different listening port for your NC instance.

**Comment by skewty** [comment]
How does Joe User use iptables on his non rooted Android phone exactly?

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by Gatak** [comment]
You misunderstand. Iptables is the firewall on linux, where you run the Nextcloud server. You can't implement portnocking in nextcloud itself as that would defeat the point of it.

**Comment by tobiasKaminsky** [comment]
In my opinion this feature is out of scope of this app.
Even if it would have been built in and enabled on NC server, you then would not be able to sync your address book / calender on e.g. Thunderbird or Andrdoid with davDroid.

In general, keeping the server up to date, both on NC and on all other software, should be good enough. You can also enable 2FA, if you want to have another security layer.
