### ISSUE TITLE
[3.3.0RC3] crashing when viewing a picture

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/android#3049]
### Actual behaviour
Crash when I try to view the image (I wanted to share it but never get a chance)

### Expected behaviour
Please don't crash ;-)
 
### Steps to reproduce
1. took picture
2. go to the folder view and try to view it
3. booooom

### Environment data
Android version: 8.0.0
plus 'Samsung Experience 9.0'

Device model: Samsung Galaxy S7
Stock, unrooted.

Nextcloud app version: 3.3.0RC3

Nextcloud server version: 14.0.0

#### Web server error log

-> note: also crashes when network is OFF. Thumbnail preview shows in grid and list view, just opening the image - BOOM.

Image in question:

https://cloud.nextcloud.com/s/4B7JJTP8ciwFC5T

**Comment by tobiasKaminsky** [comment]
You should enjoy your vacation and don't work and report bug reports :-P

Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat
