### ISSUE TITLE
Internal Media player gets stuck while streaming mp4

### ISSUE THREAD

**Issue by godfuture** [nextcloud/android#3063]
### Actual behaviour
Nextcloud APP freezes suddenly between first and second minute. Navigating the time bar does not work. Issue is reproducible.

### Expected behaviour
Media is played till the end without getting stuck. Navigating the time bar should allow the user to jump into the video without having to watch from the beginning.
 
### Steps to reproduce
1. Upload mp4 file which was produced by mobile phone camera
2. Try watching this video from Android app
3. Check if the video runs till end without freezes.
4. Check if the time bar allows you to skip certain seconds

### Environment data
Android version: 7.1.2

Device model: BQ x5Plus

Stock or customized system: lineage is 14.1

Nextcloud app version: 3.3.0

Nextcloud server version: 14.0

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
I recorded a 2 min video with "open camera" on my OnePlus3 with LineageOS, uploaded it to NC server and watched it.
It was working without a problem.

Is this about streaming or is also the downloaded file not working?

Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat
