### ISSUE TITLE
Video Media streaming with the built in video player doesn't always works (mostly)

### ISSUE THREAD

**Issue by gradinaruvasile** [nextcloud/android#3064]
### Actual behaviour
- Tap a video, the video player launches but most times fails to show the video, the screen stays black. Sometimes the length of the video is shown, but mostly shows 0:00. Sometimes it shows an error that the built in player is unable to play the video.

Note that 
- if i use the "Stream with..." option and have VLC installed, the streaming works via VLC.
- smaller video files seem to have bigger chances to be played.
- even if a video starts succesfully, most times it just freezes after a few seconds (after initial caching?)
- this happens even if the device is on wifi on the same LAN as the NC server

### Expected behaviour
- The video should be played every time. Or, if there are issues, an appropriate message to be shown.
 
### Steps to reproduce
1. Tap a video
2. 
3. 

### Environment data
Android version:
8.1.0
Device model: 
Lenovo K6 Power
Stock or customized system:
Lineage OS
Nextcloud app version:
3.3.0
Nextcloud server version:
14.0.0

**Comment by gradinaruvasile** [comment]
This issue is still present on Android 8.1, 9 with server versions 16.0 (latest ATM).

**Comment by exussum12** [comment]
This still happens

**Comment by tobiasKaminsky** [comment]
I'll have a look.
@exussum12 do you see any difference if you use different video formats?

**Comment by exussum12** [comment]
Ive only tried mp4. I can try another format if you like ? It does seem to try and download the entire video before trying to play, smaller videos (1-2 seconds) work but anything over 1 min has big issues

**Comment by exussum12** [comment]
I imagine this is more to do with #3061 actually looking more in to it

**Comment by tobiasKaminsky** [comment]
I found some problem, which is independent from Android: https://github.com/nextcloud/server/issues/16511

**Comment by AaronADev** [comment]
It appears that this issue still persists. Has there been any updates on this or any newer issues that are actually tracking this?

**Comment by ezaquarii** [comment]
@tobiasKaminsky Is it fixed server side?

**Comment by DragonQ** [comment]
My wife and I both have this issue. Viewing images works fine but we cannot play videos. Tapping a video just leads to a "loading" page forever, and if I choose "Stream with..." then MX Player, MX Player just sits there loading forever too. Most of the videos were recorded on our phones and are 1080p, AVC L4.1 in an MP4 container with AAC audio.

The only workarounds I've found are to download the video first within Nextcloud app (which defeats the purpose IMO), or to use the web interface instead. There is nothing related in the Nextcloud server-side logs either.

**Comment by dennorske** [comment]
I confirm this issue persists in the nextcloud dev 20191017 android app, and also on version 3.8.1. I am running android 10, on a oneplus 6T

Streaming with VLC works, but built in app has never worked for me.

**Comment by tobiasKaminsky** [comment]
@DragonQ do you have server side encryption with user keys enabled?

@dennorske what kind of videos are those? The built in media player relies on the codecs that are installed on Android, so there might a few missing.

**Comment by dennorske** [comment]
These are mainly phone-recorded videos, such as MP4's from my OnePlus 6T. I don't see why the files can play on the phone but not through nextcloud's app. Let me know if i can provide more details.

**Comment by DragonQ** [comment]
> @DragonQ do you have server side encryption with user keys enabled?
No, "Default encryption module" is not enabled.

**Comment by AaronADev** [comment]
Has anyone had any updates on this? It would be nice if the videos played better natively through the app especially for content creators etc. Thanks in advance.

**Comment by gradinaruvasile** [comment]
Unfortunately it is still not working properly. It seems that shorter
videos work because they are cached fully locally in very short time. But
longer ones, unless you pre-download them, are hit and miss.

**Comment by mathieu2em** [comment]
for me, on android, mp4 video files works well on the native nextcloud app but not on the stream with vlc.
for .mpk , it just gives sound on native and media player and load indefinitely on vlc

**Comment by njfox** [comment]
Is anyone still looking into this? I'm running into this issue on the latest stable NC server and android client.

**Comment by dennorske** [comment]
Can confirm the above

**Comment by DragonQ** [comment]
Not sure if this'll help others but I set the Apache log level to debug and saw some non-error clues that led me to figuring out a solution in my case. There were basically some "errors" relating to the domain name.

I set up a Let's Encrypt cerrificate (to avoid issues with self signed certificates) and tried accessing my server via its public facing URL. Voila, videos load and play successfully. However, if I access my server via its internal IP address while connected to my home network, they do not play. So the solution for me is to use the public facing URL and set up a redirect on my internal network DNS server so it forwards to my local server address, so I'm still accessing the server internally where possible even when using the public URL.

Hopefully this helps someone else with this problem!

**Comment by maidstein** [comment]
Still have the same problem! This problem only exists in case of playing larger files. Let me know if you need more details.

Please help!

**Comment by dopyrory3** [comment]
I'm having this problem too, makes switching from iPhone to Android a hot mess when none of your existing videos work

**Comment by fredbcode** [comment]
Same here, and I found no way to totally disable the nextcloud player (video plugin is disabled but the player still running)

A simple alternative should be to open automatically the file with vlc or some local players

**Comment by MrJaypot** [comment]
I also have this issue. SAD!

**Comment by Peter-JanGootzen** [comment]
I can't play any of videos past 5 seconds, it freezes every single time.
It seems this issue was only closed because of it's age, but this bug has never been fixed. Videos are just unplayable on Android which is a real pity.

**Comment by tobiasKaminsky** [comment]
> A simple alternative should be to open automatically the file with vlc or some local players

This is possible:
![image](https://user-images.githubusercontent.com/5836855/108176087-d9ec9a80-7101-11eb-89b5-188443e4241b.png)

**Comment by tobiasKaminsky** [comment]
> I can't play any of videos past 5 seconds, it freezes every single time.
> It seems this issue was only closed because of it's age, but this bug has never been fixed. Videos are just unplayable on Android which is a real pity.

I had this also with one video, but after 2s it just resumed.
The same video worked without a problem on another device.
If it hangs, I pressed pause/play and then it worked again. Can you check this?

Maybe it runs out of buffer as the internet connection is not fast enough?

If video in general is working, I'll try to look into how to increase buffer.

**Comment by feutl** [comment]
I do have problems with some "videos" and especially formats hosted on my NC instance. I have videos and formats which can be played directly within the NC app on my Android. Some of them just don't work because of its codecs anyhow this are my challenges.

Supported video formats
1. I do have a video which plays nicely within the NC app, but if it is not yet downloaded (which I need to do manually using the menu) it never starts.
2. Using the same video without downloading it and stream it to VLC also won't start, but using the Samsung Video Player works.
3. Opening the downloaded file works for all media player I use.

Non Supported video formats
I do have some videos which seem not to be supported by the NC android app, mainly old MOV files. This is ok. VLC would fix this, but streaming it does not work, and downloading would be the only option.

Now, even though I know all of this, I use NC within my family and explaining this my younger family members, even older ones ;) is challenging. They want to click on the video and watch it. Even though the the format is not supported by the NC app. So I would like to see an option which let me allow to forward all my videos to an app installed so I can set it up and all is fine.
And I also would like to understand why streaming without downloading the file using the menu to VLC does not work for me, perhaps for others as well.

**Comment by DragonQ** [comment]
It seems like people are describing various different issues in this thread. Personally, streaming video has NEVER worked for me, either with the internal player or when using "stream with...". I can only play videos when they are downloaded first.

**Comment by Peter-JanGootzen** [comment]
> > I can't play any of videos past 5 seconds, it freezes every single time.
> > It seems this issue was only closed because of it's age, but this bug has never been fixed. Videos are just unplayable on Android which is a real pity.
> 
> I had this also with one video, but after 2s it just resumed.
> The same video worked without a problem on another device.
> If it hangs, I pressed pause/play and then it worked again. Can you check this?
> 
> Maybe it runs out of buffer as the internet connection is not fast enough?
> 
> If video in general is working, I'll try to look into how to increase buffer or how to increase debug output

Pressing play/pause when it starts hanging doesn't do anything, it just changes the play/pause icon.
The internet connection is for sure not a problem. When i open the video in the browser on my phone it plays back without any issues.

**Comment by ezaquarii** [comment]
I think we should allow users to open the stream in the external video player by default and "fix" it that way.

Video player - in its current form - is not fixable as we just use the built-in `VideoView`, with all the platform, version and vendor specific bugs you can imagine.

**Comment by jakobroehrl** [comment]
@ezaquarii 
You mean this solution? https://github.com/nextcloud/android/issues/378
I think it's a good idea, with VLC all videos are played well

**Comment by tobiasKaminsky** [comment]
There is an experimental switch to another video player in https://github.com/nextcloud/android/pull/8132#issuecomment-792722526

This apk can be installed in parallel. 
It would be great if you can give this a test, if it helps in your scenario.

**Comment by DragonQ** [comment]
> 
> 
> There is an experimental switch to another video player in [#8132 (comment)](https://github.com/nextcloud/android/pull/8132#issuecomment-792722526)
> 
> This apk can be installed in parallel.
> It would be great if you can give this a test, if it helps in your scenario.

Well that's the first version of the app I've ever used that actually allows me to stream videos, so that's a great plus. It's definitely buggy though, it's crashed mid-playback twice and also if I start a video then press the back button, I can still hear the video playing.

**Comment by tobiasKaminsky** [comment]
It is a quick&dirty replacement, so misbehaving UI is ok.

Crash while playing not.
Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat
