### ISSUE TITLE
Impossible to change the auto-upload parameters

### ISSUE THREAD

**Issue by amcbedli** [nextcloud/android#3068]
I have tried to see if someone else already talked about this, but couldn't find it. If there was already a thread on this topic, I apologize in advance

### Actual behaviour
I have been trying to change the parameter of the auto-upload function, but when I hit on the "save" button, nothing happens. The "cancel" button works fine though. I'm sorry if I can't provide all the info requested below, but I'm still a newbie in the world of open-source and there are certain things I still don't understand or don't know. Thank you in advance for your patience! 

### Expected behaviour
- after I make a change in the parameters, I should be able to save them, by hitting the "save" button. 
 
### Steps to reproduce
1. Go to auto-upload
2. Click on customize a personal folder
3. Change one or more parameters in the menu and hit the "save" button. 

### Environment data
Android version: 8.0

Device model: SM-G930F - Samsung Galaxy 7

Stock or customized system:

Nextcloud app version: 3.3. 0

Nextcloud server version: not sure where to find this 

#### Web server error log
```
Not sure either where to get that. 
```

#### Nextcloud log (data/nextcloud.log)
```
Same as above 
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
Hi @amcbedli , could you post a screenshot please? My guess is that not all mandatory fields have been set and thus you can't save it. Not sure though.

**Comment by amcbedli** [comment]
Actually, I figured out a way around the problem. I have to individually set the settings for each folder, while I was trying to set up the same parameters for all folders at the same time. But I find it weird that there is a menu to do so, if it doesn't work. I'll post printscreen a bit later, just to show what I mean.
