### ISSUE TITLE
3.3.0RC3 Settings: setup DAVdroid Intent doesn't pass URL

### ISSUE THREAD

**Issue by rfc2822** [nextcloud/android#3076]
Hello,

I have tried 3.3.0RC3 :) and have found this:

### Actual behaviour
Nextcloud Android app: 3.3.0RC3

- Set up Nextcloud account in app
- Settings / More: Sync calendars and contacts
- DAVdroid is started, but with no URL. Only the user name is passed, and it's in the email address field because there's no URL

![screenshot_1537631732](https://user-images.githubusercontent.com/156167/45919105-08161380-be91-11e8-8336-22580317eb3a.png)

### Expected behaviour
- URL should be passed

With 3.2.3, this works as expected:

![screenshot_1537631691](https://user-images.githubusercontent.com/156167/45919102-fb91bb00-be90-11e8-9b59-7401ace0d8be.png)

Thanks for your work!
Ricki

**Comment by AndyScherzinger** [comment]
Hi Ricki, thanks for the report! :heart: 

@tobiasKaminsky do you have the time to look into this?

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky I can reproduce the behavior based on the latest `master`

**Comment by AndyScherzinger** [comment]
Fix merged for 3.3.1 and for 3.4.0
