### ISSUE TITLE
No FAB button if a favorite folder is opened from the Favorites menu option

### ISSUE THREAD

**Issue by gradinaruvasile** [nextcloud/android#3077]
### Actual behaviour
- If i open a favorite folder from the favorite folder list, there is no FAB button present. I can see the FAB button if i open the side menu and select "All files". This will preserve the current directory but it will show the FAB button. Not really logical.

### Expected behaviour
- If a favorite folder is opened from the favorite folder list, the FAB button should be visible.
 
### Steps to reproduce
1. Set a favorite folder
2. Navigate back to the root
3. Open the Favorites list on the side menu and select the favorite folder.

### Environment data
Android version:
8.1.0
Device model: 
Lenovo K6 Power, Xiaomi Redmi 4A
Stock or customized system:
Lineage OS
Nextcloud app version:
3.3.0
Nextcloud server version:
14.0.0

**Comment by gradinaruvasile** [comment]
This isssue is stil present in 3.6.1 RC2

**Comment by tobiasKaminsky** [comment]
Thanks for confirming; I can also reproduce it.
