### ISSUE TITLE
Adapt build status in README.md to new CI server address

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#308]
small change, PR #309

**Comment by tobiasKaminsky** [comment]
@saksham15082 this was just adjusting an URL, nothing to code.
If you want to help us, have a look at some issues labeled starter_issue. If you mention me I am glad to help you getting your hands on nextcloud.

**Comment by AndyScherzinger** [comment]
@saksham15082 like @tobiasKaminsky said any issue that is either labelled as starter_issue or hacktoberfest _and_ is approved https://github.com/nextcloud/android/labels/hacktoberfest. "1. to develop" might be possible to, there you can just comment and ask since "1, to develop" might mean someone is already starting also any issue with label "pr exists" is already done but not yet merged and thus not closed yet.

**Comment by saksham15082** [comment]
Thanks
