### ISSUE TITLE
Auto-uploaded files on external SD-Card should be deleted after upload, but they don't

### ISSUE THREAD

**Issue by MarkusH1975** [nextcloud/android#3083]
### Actual behaviour
- Tell us what happens
I uses the autoupload feature and configured it to delete the original file, after upload.
The upload folder is located on a external SD-card. 
The nextcloud storage is located as well on the same SD-card, so access rights should be already granted.
(Didn't try is with internal memory. )

### Expected behaviour
- Tell us what should happen
After upload, the original file should be deleted, it isn't.
 
### Steps to reproduce
1.  Configure auto upload folder on (external) sd-card, with setting "delete" original after upload.
2. Move some file in upload folder
3. Wait until the file is uploaded in the cloud.
4. Original file is not deleted. 

### Environment data
Android version: Android 6.0.1

Device model: Sony Xperia Z3 compact

Stock or customized system:

Nextcloud app version: 3.3.0

Nextcloud server version: 13.0.5

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
Hi @MarkusH1975 is the auto upload folder a "standard" auto upload folder as in image, video or audio or did you configure a custom folder?

**Comment by MarkusH1975** [comment]
@AndyScherzinger it is a custom folder on the SD-card
