### ISSUE TITLE
Auto-Upload issue: Photos taken are not uploaded when no network traffic possible at create time of photos

### ISSUE THREAD

**Issue by michaelof** [nextcloud/android#3091]
### Actual behaviour
Camera app's folder are set to auto-upload. Works mostly stable (have seen a couple of similar issues already open here), but, new for for me, NOT in the following  scenario:

- was off-site, no wifi, and with no mobile data, as no "credit" for (prepaid) mobile data. Means that technically devices shows mobile data (4G) connection as established, but no traffic comes through, blocked from telco company.
- I have taken some photos when "no network", as described above.
- Nextcloud app "sees" network connection established, tries to auto-upload. Forever, no time-out.
-  Even when later again a network connection had been established, NC app shows still no progress on auto-upload notification. Had to kill NC app, finally, to get rid of the "uploading files ...." notification.
- NO chance to get these never-uploaded photos auto-uploaded after NC app restart.
-  Even a manually "forced" re-scan doesn't detects them, they're not shown as failed, just nothing
- Later taken photos, with "normal" network connection, again are auto-uploaded fine, as desired.

### Expected behaviour
- NC app should run in a timeout, or at least be able to detect "skipped" files later on, latest with a manual forced re-scan
 
### Steps to reproduce
(already described above)

### Environment data
Android version: 6.0
Device model: Lenovo C2 / K10a40
Stock or customized system: Stock
Nextcloud app version: 3.2.3, F-Droid
Nextcloud server version: 14.0.0, OpenSuse Leap 15.0 repo version
### Logs
nothing in log for these photos, unfortunately

**Comment by artur3** [comment]
I have similar problem. After taking photos I got notification that sending is not possible, server is not accessible.
But:
server can't be accessed because it's only available in my local network trough WiFi,
in sync setting I checked option to upload only when charging.

**Comment by greku** [comment]
Of all the auto-upload issues open, this one seems to correspond the most to the problem I have too. Sometimes, some pictures not yet uploaded, do not upload when being connected to the server. Although newer set of pictures get uploaded. This results in some pictures not being uploaded.

For some reason, I suspect the app is trying to upload the "new" pictures at some point. The upload doesn't succeed, but for some reason, the app considers these pictures don't need to be uploaded anymore. This results in this set of "new" pictures to be never uploaded, although next pictures may upload without problem.

Using a private cloud server, only available on one local wifi network.
