### ISSUE TITLE
auto-upload ignores "subfolders" settings

### ISSUE THREAD

**Issue by azrdev** [nextcloud/android#3095]
### Actual behaviour
- configure the (default) photo & video folders for auto-upload
- enable *use subfolders by year/month*
- take photo
- photo appears in configured "autoupload-root"

### Expected behaviour
- photo should appear in subfolder of configured "autoupload-root"
 

### Environment data
- Android version: 7.1
- Device model: golden / Samsung S3 Mini
- Stock or customized system: inofficial ROM
- Nextcloud app version: 3.2.3 from F-Droid
- Nextcloud server version: 13

**Comment by edonnachie** [comment]
I request this issue be reopened. Sometimes the subfolder setting is honoured, sometimes not. I can't see any pattern to this behaviour.

**Comment by AndyScherzinger** [comment]
@edonnachie could you please provide some more details, like app version, android version and possible differences between the folders where it works and where it doesn't.

**Comment by edonnachie** [comment]
@AndyScherzinger:
Android app Version 3.9.2
Android 7.0 on Honor 6X

Subfolders seem always to work with Video, but not with photos (both /storage/emulated/0/DCIM/Camera).

On taking a photo, I sometimes get a notification from Nextcloud that a new media folder has been found, but photos are always uploaded to the specified folder on the server (just not always to the subfolder).

**Comment by tobiasKaminsky** [comment]
Hm. This is strange.
Do you have a custom upload folder? Or maybe an additional app that also uploads it and thus is sometimes faster?

**Comment by edonnachie** [comment]
I upload to /phone/photos on the server, but I don't have any other sync apps. Honor/Huawei seems to be strange with regard to background apps, so I'm not sure if it's connected in some way

**Comment by AndyScherzinger** [comment]
still open

**Comment by tobiasKaminsky** [comment]
Is this still valid?

**Comment by edonnachie** [comment]
After updating client and server to the latest versions, I haven't observed this problem over the last week or so.

**Comment by AndyScherzinger** [comment]
@edonnachie let's close the issue then and reopen in case the issue comes back.
