### ISSUE TITLE
no search in text-file viewer

### ISSUE THREAD

**Issue by azrdev** [nextcloud/android#3096]
### Actual behaviour
- open a text file in the nextcloud app
- press the search-icon in the top bar
  - enter a search term which appears in the file (and press enter/search)
  - note that nothing happens
- press *back* (either the system button or "←" in the top bar) to quit searching
- press *back* to quit viewing the file and go back to its containing folder
  - note that you don't view the folder, but search results for files/folders with your search from above
  - press *back* to get to view any folder
    - note that the view is now empty, but to regularly view any folder you have to use the swipe-menu on the left or reopen the app (this might be a separate bug, actually)

### Expected behaviour
- searching while a file is viewed should search that view
- when in search results, going back should go to the previous regular folder view
 

### Environment data
- Android version: 7.1
- Device model: golden / Samsung S3 Mini
- Stock or customized system: inofficial ROM
- Nextcloud app version: 3.2.3 from F-Droid
- Nextcloud server version: 13

**Comment by AndyScherzinger** [comment]
Search in viewed text file is a work in progress implementation not yet finished nor releases, PR is #565

**Comment by tobiasKaminsky** [comment]
I revived the PR, rebased it and fixed search/highlight after resuming.

**Comment by AndyScherzinger** [comment]
I'll retest the PR next week if time permits, not having access to a dev environment before it seems.

**Comment by AndyScherzinger** [comment]
PR has been merged and will ship with 3.4.0
