### ISSUE TITLE
files shared via Talk conversations causes app to crash

### ISSUE THREAD

**Issue by reppard** [nextcloud/android#3098]
### Actual behaviour
- App crashes when navigating to a folder containing a file that has been shared in a conversation.

### Expected behaviour
- App should load content of directory without crashing
 
### Steps to reproduce
1. Share a file from a folder in a Talk conversation (https://apps.nextcloud.com/apps/spreed)
2. Open Nextcloud mobile app and navigate to folder containing the file shared in the previous step
3. Watch app crash

### Environment data
Android version: 8.1.0
Device model: Nexus 5X
Stock or customized system: custom(Lineage 0S)
Nextcloud app version: 3.3.0
Nextcloud server version: 14

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky already created a fix which will be released with the next bugfix version
