### ISSUE TITLE
While uploading file "Move file and Delete from source option" are one and the same

### ISSUE THREAD

**Issue by Blackhat96** [nextcloud/android#3099]
### Actual behaviour
- While uploading a file to cloud, user will be given three options.
   a. Move file to NextCloud server.
   b. Keep file in source folder.
   c. Delete file from source folder.

### Expected behaviour
- Move file to NextCloud server and Delete file from source folder are one and the same so I feel that it is redundant.
 
### Steps to reproduce
1. Click the **+** in homescreen of the app.
2. Users will be given 3 options

![screenshot_1538022387](https://user-images.githubusercontent.com/29779749/46123613-238c7000-c23d-11e8-9c04-8e6d86de96d5.png)

### Environment data
Android version: 8.1.0
Device model: Pixel 2 XL
Stock or customized system: Stock ROM
Nextcloud app version: 3.4.0 Alpha 1

**Comment by AndyScherzinger** [comment]
Are you sure it is one and the same? While both options will remove the file from the original location the move option will actually move it into the app's folder structure _on_ your device!

**Comment by Blackhat96** [comment]
@AndyScherzinger You are right. The file will be moved to apps folder, which is at
**Android/media/nextcloud/account/<file>** 

- Is there a use case for that? As the file will occupy the same space whether its moved from the source folder or not.
- Also I personally feel that instead of storing the file inside **Android/media/nextcloud/**  it will be good thing if there is a dedicated folder in root of SDCARD, also it will be easier for end users to locate/modify it later.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky can you provide some feedback here since you originally implemented this feature? :)

> SD card
Is tricky since many devices just have internal memory and SD cards usually come with write permission issues depending on the OEM :/

**Comment by mr-bolle** [comment]
Hi, i have the same issue. Currently i use v3.5.0 and try with Nextcloud 14.0. 6 and 15.0.4

I can't remember since when this issue appears

**Comment by Spacandy** [comment]
While uploading a file to cloud, user will be given three options.
a. Move file to NextCloud server.
b. Keep file in source folder.
c. Delete file from source folder.

I have a question
for a and c, what is different?
