### ISSUE TITLE
Integrate Code Quality Checks

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#310]
Integrate certain typical code quality measurement tools, as described here: http://vincentbrison.com/2014/07/19/how-to-improve-quality-and-syntax-of-your-android-code/ and corresponding sample project https://github.com/vincentbrison/vb-android-app-quality

which basically means adding checkstyle, pmd, findbugs, etc. to the build. 

**Follow up for #226 - claimed by @djubreel**

**PR is #321**

**Comment by djubreel** [comment]
@AndyScherzinger Okay,I'd work on it

**Comment by AndyScherzinger** [comment]
@djubreel thanks! Any help and contribution is highly appreciated! :rocket:

**Comment by wmora** [comment]
be warned that it might require a lot of changes to the current code when integrating these tools depending on how strict you configure them

**Comment by AndyScherzinger** [comment]
It'll definitely require that. The idea would be to get it integrated in general and then step by step making the checks stricter.

**Comment by djubreel** [comment]
Hello @AndyScherzinger  I have created a PR already

**Comment by AndyScherzinger** [comment]
Hi @djubreel I saw it and already tested it, just waiting for @tobiasKaminsky's feedback before merging it. Great work and a big thank you for this contribution! :tada:

**Comment by djubreel** [comment]
@AndyScherzinger thanks, I'd appreciate if you could point me to any starter issue

**Comment by AndyScherzinger** [comment]
Hi @djubreel I just opened an issue for pmd/findbugs #322 which should be enough for a first fix to be able to activate the introduced checks in the CI builds. If you have any question or feel something is missing or unclear, just let me know! :)
