### ISSUE TITLE
Play music from App directly

### ISSUE THREAD

**Issue by MegaV0lt** [nextcloud/android#3102]
### Actual behaviour
- not possible to play music, folders of music with nextcloud app without downloding first

### Expected behaviour
- should be possible to play/stream musi fom nextcloud app directly with possibility to play folders content

### Environment data
Android version: 6

Device model: HomTom HT16 Pro

Stock or customized system: ? with root

Nextcloud app version: Actual stable 3.x

Nextcloud server version: 13.x

**Comment by gradinaruvasile** [comment]
This is already implemented in the 3.3.0 version actually but you need the server version 14 at least.

**Comment by MegaV0lt** [comment]
Great! I will upgrade server on Monday and test it. Client 3.3.0 is the stable one?

**Comment by AndyScherzinger** [comment]
Yes, 3.3.0 is the latest stable version of the Android app, 14.0.1.1 the latest stable of the server.

**Comment by MegaV0lt** [comment]
Have tried, but sadly is only possible to play one file at a time. Playlist (m3u) is not recognized ;-(

**Comment by yasuoiwakura** [comment]
Hi there,
"folder playback" is not yet possible, right?

**Comment by joshtrichards** [comment]
Duplicate of #1038

Also related to #5555
