### ISSUE TITLE
permanent message "Uploading files" whereas all files are uploaded

### ISSUE THREAD

**Issue by ferdiga** [nextcloud/android#3104]
### Actual behaviour
permanent message "Uploading files"

### Expected behaviour
the message should be cleared after all files are uploaded
 
### Steps to reproduce
1. install android client
2. take a photo
3. wait until it is uploaded
4. message "Uploading files ...." does not disappear 
5. apparently the Autoload path is not allowed

### Environment data
Android version: 3.3.0

Device model: 
nokia 8

Stock or customized system:
stock

Nextcloud app version:

Nextcloud server version:
13.0.6

#### Nextcloud log (data/nextcloud.log)
```

...
apparently the Autoload path is not allowed
...
{"reqId":"hK7Bb69wnVfTgnvA3AX2","level":3,"time":"2018-09-30T01:15:03+00:00","remoteAddr":"","user":"--","app":"core","method":"--","url":"--",

"message":"Error while running background job (class: OC\\Settings\\RemoveOrphaned, arguments: ): 
{\"Exception\":\"OCP\\\\AutoloadNotAllowedException\",
\"Message\":\"Autoload path not allowed: \\\/var\\\/www\\\/owncloud\\\/apps\\\/ojsxc\\\/settings\\\/personal.php\"

,\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/autoloader.php(158): OC\\\\Autoloader->isValidPath('\\\/var\\\/www\\\/ownclo...')\\n#1 [internal function]: OC\\\\Autoloader->load('OCA\\\\\\\\OJSXC\\\\\\\\Setti...')\\n#2 [internal function]: spl_autoload_call('OCA\\\\\\\\OJSXC\\\\\\\\Setti...')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(95): ReflectionClass->__construct('OCA\\\\\\\\OJSXC\\\\\\\\Setti...')\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(118): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->resolve('OCA\\\\\\\\OJSXC\\\\\\\\Setti...')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/ServerContainer.php(132): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('OCA\\\\\\\\OJSXC\\\\\\\\Setti...')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Settings\\\/Manager.php(201): OC\\\\ServerContainer->query('OCA\\\\\\\\OJSXC\\\\\\\\Setti...')\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Settings\\\/RemoveOrphaned.php(86): OC\\\\Settings\\\\Manager->checkForOrphanedClassNames()\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/BackgroundJob\\\/Job.php(61): OC\\\\Settings\\\\RemoveOrphaned->run(NULL)\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/BackgroundJob\\\/TimedJob.php(55): OC\\\\BackgroundJob\\\\Job->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Settings\\\/RemoveOrphaned.php(70): OC\\\\BackgroundJob\\\\TimedJob->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#11 \\\/var\\\/www\\\/owncloud\\\/cron.php(123): OC\\\\Settings\\\\RemoveOrphaned->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#12 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/autoloader.php\",\"Line\":134}","userAgent":"--","version":"13.0.6.1"}

```

```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by FelixBuehler** [comment]
I have the same problem but can't reproduce it in all occasions. I would guess it happens 10-30% of the uploads.
Nextcloud Server shows no errors in the log.

I can't remove the notification by swiping it away, so this kinda annoys. I either have to upload a new file or have to restart my phone.

I'm using Nextcloud Android 3.6.2 on a HTC 10 with Android 8.0.0 with Nextcloud Server 16.0.1

Any hints to try to locate the problem?

**Comment by maurerle** [comment]
I am experiencing this issue too.
NC Android 3.9.2 (F-Droid), Xiami Redmi Note 7 (MIUI 11, Android 9)
Server: 17.0.2

I think this has something to do with Autoupload as I can only reproduce it when I am not looking (not using the app and relying on the autoupload makes this notification appear after a day or two when opening the app). Hard to debug, I'm sorry.

I am currently force closing the app to remove the notification.

In the Server logs I saw some PUT Requests resulting with a 201 (route remote.php) and some with a 200 (route index.php).
I think both are coming from uploading pictures. Maybe this has something to do with it.

**Comment by newhinton** [comment]
I have this issue aswell, sometimes a notification gets stuck at 100%, but i also had it beeing stuck at a lower percentage. I dont know what triggers it, but i know why it happens. It seems in those cases the background service finishes or crashes, and then the message does not get cleaned. It seems there is a racecondition somewhere

@ezaquarii Will your new notification code take care of this? My "solution" would be to call .setOngoing(false) as soon as 100% was hit, so it gets swipeable. Also, maybe we should make this dismissable when it was clicked, which would actually solve this better.

**Comment by ezaquarii** [comment]
@newhinton if you can get an improvement with just a few lines of code, I'd say it's a no-brainer. I'm not sure when I'll have a chance to push my code forward as the Nextcloud team is currently slow with reviews and merges due to other work in Talk.

I'd say that if you can get something simple working quickly - go for it.

**Comment by ezaquarii** [comment]
not stale

**Comment by tobiasKaminsky** [comment]
> apparently the Autoload path is not allowed

Please ask on forum, as this is not related to Android, but should also be fixed.

**Comment by joshtrichards** [comment]
There have been a variety of relevant PRs merged since the original (and subsequent) reports. Are any of you still experiencing this?
