### ISSUE TITLE
Notification 'Upload failed'

### ISSUE THREAD

**Issue by MeiRos** [nextcloud/android#3105]
### Actual behaviour
- When I take few pictures in a short time,(Let's say 6 pics in ten minutes) my autoupload gives error notification. "Upload failed. Can't finish action. Server not in use." (or something like that. my translation) Anyway, pics will be uploaded soon after ~15 minutes automatically. 

### Expected behaviour
- Notification should disappear when it starts trying upload again or at least when everything is uploaded succesfully. 
 
### Steps to reproduce
1. Have a slow mobile connection
2. Take few pics
3. Wait autoupload to handle the rest

### Environment data
Android version: 8.0

Device model: galaxy S8

Stock or customized system: stock

Nextcloud app version: 3.3.0

Nextcloud server version: 13.0.6

#### Web server error log
```

```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by MeiRos** [comment]
I already think that bot is useless... 
Well, this is duplicate to #2535.
Cannot remember that issue even I follow these issues quite much.

**Comment by joshtrichards** [comment]
Consolidating tracking for this enhancement into #3234
