### ISSUE TITLE
Ability to mount the files as external storage

### ISSUE THREAD

**Issue by ghost** [nextcloud/android#3109]
... or something.

So that the files on Nextcloud can be read by other apps (e.g. a music player, #914, #3102).

Is it possible with the android API?

PS: I don't have enough space on my phone to sync all the files I need...

### Environment data
Android version: 8.1.0

Device model: ASUS_Z017D

Stock or customized system: Custom system, Lineage OS

Nextcloud app version: 3.3.0

Nextcloud server version: 14.0.0

**Comment by joshtrichards** [comment]
Any application that supports Android's Storage Access Framework can do this today (e.g. VLC's *Pick a File* option).
