### ISSUE TITLE
Tapping successful upload notification should open the details view directly

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/android#3111]
Currently when you upload a file and then tap the notification to edit details, you are sent to the Uploads view.

That's not very useful – better would be to show the detail view of the file so you can add comments, share, rename etc.

**Comment by adikul30** [comment]
Can I pick up this issue ?

**Comment by AndyScherzinger** [comment]
Hi @adikul30, welcome to the Nextcloud! Yes, thanks for taking an interest and picking this one up :+1:

**Comment by tobiasKaminsky** [comment]
This is only possible due to a short time span, when "succesfull upload" is shown.
Most of the time user will only see "upload in progress" and this cannot be redirected to file details view as it then does not yet exist on server.

**Comment by tobiasKaminsky** [comment]
It is shown for ~2s, I am fine with either way…

**Comment by adikul30** [comment]
I tried to emulate the situation here and Yes the notification disappears as soon as you notice it. So, should I try to persist the notification and implement the detail view opening or do you plan to remove the notification and just show a toast or sound instead ?

**Comment by AndyScherzinger** [comment]
Depends on the feedback of @jancborchardt
My vote is on removing the notification for 'uploaded successfully'

**Comment by tobiasKaminsky** [comment]
(@jancborchardt said, that we should not only ping him, but always @nextcloud/designers, so also pinging them)

**Comment by juliushaertl** [comment]
From a UX experience it might make sense to keep the notification for a little longer. Imagine a user uploads a file, continues with something else during the upload happens and once finished, they can pick up with the finished upload to for example share the file then.

**Comment by AndyScherzinger** [comment]
It's a bit more complicated than that I'm afraid :/
You'll see this notification per uploaded file, so when I upload several files at once via the multi select this success notification will get triggered per file, at least at the moment. 
So. From my pov this notification in its current state isn't useful and keeping it a little longer won't help since it would then either get overwritten by the next successful file been uploaded or the notifications would simply pile up, which is then imho just noise to the user. :/

I'd rather argue that the uploads view should also get a three dot menu to offer similar actions than the file list view, while the menu should then only be present for successfully uploaded files. Would that work as an alternative way to handle this?

**Comment by juliushaertl** [comment]
> So. From my pov this notification in its current state isn't useful and keeping it a little longer won't help since it would then either get overwritten by the next successful file been uploaded or the notifications would simply pile up, which is then imho just noise to the user. :/

OK, in that case it makes no sense to keep the notification.

> I'd rather argue that the uploads view should also get a three dot menu to offer similar actions than the file list view, while the menu should then only be present for successfully uploaded files. Would that work as an alternative way to handle this?

Yes, that sounds like a good improvement then. :+1:

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky are you also fine with the latest approach discussed here? :)

**Comment by jancborchardt** [comment]
Am also fine with removing the notification! :)

**Comment by joelselvaraj** [comment]
Hello Guys, can I work on this issue?

**Comment by AndyScherzinger** [comment]
Sure thing @joelselvaraj 👍

**Comment by joelselvaraj** [comment]
As per the decision here, I have created a pull request #3637 to remove the notification on successful uploads. Kindly review and let me know if any changes are required.

**Comment by tobiasKaminsky** [comment]
> > I'd rather argue that the uploads view should also get a three dot menu to offer similar actions than the file list view, while the menu should then only be present for successfully uploaded files. Would that work as an alternative way to handle this?
> 
> Yes, that sounds like a good improvement then.

As this is separate from this issue, we should split this up and discuss it: https://github.com/nextcloud/android/issues/3646
