### ISSUE TITLE
Tapping files in upload view should open the file view in the Nextcloud app

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/android#3112]
Currently when I tap a file in the uploads view, either it opens it in the local image viewer, or I get this:
![](https://cloud.jancborchardt.net/s/eRXRK2n7Aq5zqXg/preview)

Apart from this being very technical wording no one should ever see, tapping a file in this view should open the file view (like viewing the image) inside Nextcloud, no?

Alternatively also the detail view works. But when you upload pictures to share, currently you upload - tap upload notification - get to uploads view - tap file - file opens in local viewer - you can use the share function there …?

**Comment by asaikarthikeya** [comment]
Is this Still open issue? i would like to work on this .

**Comment by tobiasKaminsky** [comment]
> I get this:

Something is missing here…?

**Comment by ANUKULJHA1506** [comment]
can u assign me this issue

**Comment by jancborchardt** [comment]
Closing in favor of https://github.com/nextcloud/android/issues/847 which already existed
