### ISSUE TITLE
Button to copy link available only at landscape orientation

### ISSUE THREAD

**Issue by Phistan** [nextcloud/android#3119]
### Actual behaviour
Button to copy link on shared items available only at landscape orientation 

### Expected behaviour
Available button at both landscape and portrait orientation 
 
Screenshots 
Button available - https://nc.phistan.lv426.tech/s/sGZtARCZsz8bDe3
No button - https://nc.phistan.lv426.tech/s/AJATBayq6ZYG2Qn

### Environment data
Android version: 7.1.2

Device model: Xiaomi Redmi Note 4

Stock or customized system: customized

Nextcloud app version: 3.3.0

Nextcloud server version: 14.0.1

**Comment by johnnybigoode** [comment]
Heya, may I take this?

**Comment by AndyScherzinger** [comment]
Hi @johnnybigoode, thanks for taking an interest in picking up this issue. Pinging @tobiasKaminsky since he should be around in case you have any questions or need a hint or else.
