### ISSUE TITLE
Nextcloud app stops/crashes when opening .ics file

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/android#3127]
If you have an .ics file (like from a Bahn booking) and tap on it, the app crashes saying

> Unfortunately, Nextcloud dev has stopped

This does not happen when you open the 3-dot-menu and choose "Open with", where you can open it with a calendar and there are no problems.

It seems there is no default action set for .ics files? When you tap them, it should be as if "Open with" was chosen.

Latest Nextcloud dev (from F-Droid) on Fairphone Android 6.0.1

**Comment by agilob** [comment]
I can successfully open .isc file generated by meetup.com, file is opened as a normal text file, burger-menu and "open with" works fine too. Do you have logs for this crash?

**Comment by tobiasKaminsky** [comment]
Same for me, I used a sample.ics I fonud on the internet.
@jancborchardt can you mail me the file in question?

**Comment by jancborchardt** [comment]
I forgot which file this was. Will reopen if it happens again. :)
