### ISSUE TITLE
Enlarge app icon

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#313]
Enlarge app icon, although it does not obey material design guidelines.
Currently it is just too small.
@jancborchardt

**Comment by wincinderith** [comment]
Do we want to remove padding from the icon entirely? I'm down for that, it'd look pretty good IMO.

**Comment by AndyScherzinger** [comment]
Hi @wincinderith not sure if it should/will be removed completely or just be reduced drastically (kind of the same I know), but that is the basic idea here. Awaiting @jancborchardt's reply / svg source file for @tobiasKaminsky to do this :smiley:

**Comment by wincinderith** [comment]
Sure, look forward to it. :smiley:

**Comment by tobiasKaminsky** [comment]
@jancborchardt pinging, again :)

**Comment by jancborchardt** [comment]
@tobiasKaminsky @AndyScherzinger soooorry for the late reply, finally managed! :)

Here’s the source: https://github.com/nextcloud/promo/blob/master/icon-android.svg
I would just use the square area as icon, without the whitespace around it. No need to resize anything, just use the selection as export area in Inkscape. Let me know if you need any help :)

**Comment by wincinderith** [comment]
I can do this, use Inkscape all the time. Expect a PR soon!

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky already did it, but doesn't have an internet connection at the moment being on the train!

**Comment by tobiasKaminsky** [comment]
PR #352

**Comment by AndyScherzinger** [comment]
Merged
