### ISSUE TITLE
Auto upload -> select folder for remote folder -> see FAB

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#3137]
### Actual behaviour
- see fab

### Expected behaviour
- do not see FAB
 
### Steps to reproduce
1. auto upload
2. choose folder for remote folder
3. see FAB

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by fayad** [comment]
Thanks for working on this issue. 

As per #2462 feature is soon to merge on to fdroid version. But the option to select custom folder is not available on v3.3.2 yet.
