### ISSUE TITLE
incomplete file auto-upload

### ISSUE THREAD

**Issue by Aviortheking** [nextcloud/android#3138]
### Actual behaviour
- Tell us what happens

some files arent completly uploaded to the cloud

example : 
Source
![screenshot_minecraft_20180913-044605](https://user-images.githubusercontent.com/15822031/46904157-327f4d80-cee0-11e8-9522-1b95b76d5aaf.png)

Cloud (got from ftp because i could not download it from clients or server
![screenshot_minecraft_20180913-044605](https://user-images.githubusercontent.com/15822031/46904182-8be77c80-cee0-11e8-8ae3-501713d67770.png)

### Expected behaviour
- android client should see if the file is fully uploaded and re-upload missing parts
 
### Steps to reproduce
1. start an upload
2. I don't really know
3. 

### Environment data
Android version: 8.1.0

Device model: ONEPLUS A3003

Stock or customized system: LineageOS 15.1

Nextcloud app version: 3.3.0

Nextcloud server version: 14.0.0

#### Web server error log
```
no error from server side
```

#### Nextcloud log (data/nextcloud.log)
[nextcloud.log](https://github.com/nextcloud/android/files/2475343/nextcloud.log)

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by Aviorleking** [comment]
Nop noneof these are the same

**Comment by Aviortheking** [comment]
please stale bot this haven't been resolved

**Comment by AndyScherzinger** [comment]
So this still happens with version 3.6?

**Comment by rcsilva83** [comment]
Hi,

I had the same problem: a video file with 2.9GB was auto uploaded but the server file is just 73MB. Should I open a new issue as I'm using a much newer Nextcloud server and Android app versions?

I know this must be a tough issue to reproduce but it has a high impact on my trust on Nextcloud as a Google Photos alternative... I'm available to help with anything.

**Comment by scr4bble** [comment]
Same for me, video file that has 150 MB locally got uploaded only partly (seems like it failed because of some network issue)... resulted into 40 MB file in the cloud.
When trying to play the video in nextcloud client it says "Could not read the media file".

This makes the nextcloud very unreliable as an alternative to other cloud media backup solutions.

**Comment by scr4bble** [comment]
New issue created in here: https://github.com/nextcloud/android/issues/12339
Feel free to add more information if you are experiencing this bug.
