### ISSUE TITLE
Charging only makes problem

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#314]
### Actual behaviour
- reported by a colleague
- enable charging only on pictures
- take a photo
- charge device
### Expected behaviour
- image should be uploaded

Please provide more infos
@MorrisJobke

**Comment by MorrisJobke** [comment]
For now I don't have more information. What else is useful to know?

**Comment by tobiasKaminsky** [comment]
@MorrisJobke phone model and android version would be great

**Comment by MorrisJobke** [comment]
> @MorrisJobke phone model and android version would be great

Ummm ... I just sold it ... but I can ask about this info :D

**Comment by MorrisJobke** [comment]
Model: `A00001`
Android: 6.0.1

**Comment by tobiasKaminsky** [comment]
The only possibility, as far as I see, is that the device does not report the charging status correctly.
I can make a special debug app for testing this, if you are willing to help?

**Comment by Querschlag** [comment]
Problem also occurs on Nexus 6P with Android 7.0

**Comment by tobiasKaminsky** [comment]
Can you help us and install a debug app, which I will provide you?
It will print a lot more infos while using it.

**Comment by Querschlag** [comment]
Sure no problem.

**Comment by Querschlag** [comment]
I just created a small test app with the BroadcastReceiver example from the [offical Documentation](https://developer.android.com/training/monitoring-device-state/battery-monitoring.html).
Unplugging the device is correctly detected, but connecting the device does not update the status, but polling the status manually (IntentFilter) a short peroid after replugging shows correct charging state...
Looks like a timing issue.
Also ```BatteryManager.BATTERY_PLUGGED_USB``` and ```BatteryManager.BATTERY_PLUGGED_AC``` states do change before ```BatteryManager.BATTERY_STATUS_CHARGING```

**Comment by tobiasKaminsky** [comment]
In the nearer future there will be a new "auto upload" mechanism that relies on JobServer.
I hope that this issue is then solved by design ;-)

**Comment by Querschlag** [comment]
Just tested with version 1.4.0 on Android 7.1.1 - works without issues now.

**Comment by AndyScherzinger** [comment]
@Querschlag does your test suite also still work? (Maybe for you it works because Google might have fixed something with 7.1.1)

**Comment by tobiasKaminsky** [comment]
This is nothing we can fix on our own as we have to rely on the broadcast.
For newer android versions there is auto upload.
So I will close.
