### ISSUE TITLE
auto sync

### ISSUE THREAD

**Issue by ghost** [nextcloud/android#3142]
I've scanned the open and closed issues for auto sync info. some of the features sound like they *may* result in what I think of as auto sync... do any of them (auto pull new files to phone)? the description of 'favorites' sounds like it may. And many issues make 'auto upload' sound like it was just poorly named. ? Is there a way to auto sync(pull new files to phone automatically)? also is it possible to make the documentation describe the features / name the features less ambiguously? great

**Comment by joshtrichards** [comment]
Many things have changed since this was created. *3-dot menu->Sync* is the short answer. But there are other issues tracking various refinements: https://github.com/nextcloud/android/labels/feature%3A%20sync
