### ISSUE TITLE
Switch to WorkManager

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#3147]
https://developer.android.com/topic/libraries/architecture/workmanager

> The WorkManager API makes it easy to specify deferrable, asynchronous tasks and when they should run. These APIs let you create a task and hand it off to WorkManager to run immediately or at an appropriate time.

> WorkManager chooses the appropriate way to run your task based on such factors as the device API level and the app state. If WorkManager executes one of your tasks while the app is running, WorkManager can run your task in a new thread in your app's process. If your app is not running, WorkManager chooses an appropriate way to schedule a background task…

Currently we use android-job from Evernote and they suggest to [switch over](https://github.com/evernote/android-job#workmanager).

**Comment by tobiasKaminsky** [comment]
What to do
- slowly switching from evernote to WorkManager
- centralize all constrain checks with ConnectivtyService/DeviceModule (e.g. battery, wifi)
- all Jobs need to handle start/stop/restart gracefully, we must make sure that jobs really end
- write test cases

**Comment by ezaquarii** [comment]
@tobiasKaminsky @AlvaroBrey I think the migration has been completed some time ago. Shall we close it?
