### ISSUE TITLE
Enhance "recommend to a friend"

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#315]
- add fdroid as alternative app store
- allow sharing to whatsapp/sms as plain text

**Comment by tobiasKaminsky** [comment]
Whatsapp should include an app link that opens a market store (fdroid/play store)

**Comment by jsrck** [comment]
I created a pull request for this:
https://github.com/nextcloud/android/pull/1216

**Comment by AndyScherzinger** [comment]
merged to master
