### ISSUE TITLE
Hard seperation of client / library

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#3150]
Currently most of the server manipulation tasks are in serve, but e.g. RestoreTrashbinFileOperation is in client.

This is wrong for multiple reasons
- no other app can use it
- testing library cannot test this operation
- testing on client side is also harder

(I guess that I did this out of lazyness /hide)

So the idea is to have
- in library: all server related tasks, actually manipulation is done here
- in client: call library tasks and parse results

With this, we could (at some point) mock the complete library and test the complete app without any real server/library usage.

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger @ezaquarii can you recheck if everything is splitted / moved accordingly? 
Then we could close this…

**Comment by tobiasKaminsky** [comment]
All things in library should be end with "RemoteOperation", e.g. 
CreateFolderOperation (in files app)
CreateFolderRemoteOperation (in library)

**Comment by ezaquarii** [comment]
Get list of all operations implemented in library:
```
$ for i in `find ./ -name '*Operation.java'`; do
echo ${${i##*/}%RemoteOperation.java} >> ~/lib-operations.txt
done
```

Same for ops still in app:
```
$ cd ./nextcloud-android/src/main/java/com/owncloud/android/operations
for i in *.java; do
echo ${i%Operation.java} >> ~/app-operations.txt
done
```

Ops still not moved to library:
```
grep -Fxv -f lib-list.txt app-list.txt
CheckCurrentCredentials
CreateShareViaLink
CreateShareWithSharee
DetectAuthenticationMethod
GetCapabilities
GetServerInfo
GetSharesForFile
GetUserProfile
RefreshFolder
RemoveRemoteEncryptedFile
RichDocumentsCreateAsset
RichDocumentsUrl
SynchronizeFile
SynchronizeFolder
Unshare
UpdateNoteForShare
UpdateOCVersion
UpdateSharePermissions
UpdateShareViaLink
```

Ops already moved to library:
```
$ grep -Fx -f app-list.txt lib-list.txt                            
CommentFile
CopyFile
RenameFile
DownloadFile
RemoveFile
UploadFile
MoveFile
CreateFolder
```

Looks like a lot of work to do...

**Comment by tobiasKaminsky** [comment]
I fear it is not that easy, as most in the first list are a client wrapper to the remote call, e.g. https://github.com/nextcloud/android/blob/eaccdc83a57177eee05de87eebda270622f893ab/src/main/java/com/owncloud/android/operations/GetCapabilitiesOperation.java#L31-L38

But I went through the list and found this:

to move:
/

to rename in library:
GetRemoteSharesForFileOperation -> GetSharesForFileRemoteOperation
CreateRemoteShareOperation -> CreateShareRemoteOperation
GetRemoteStatusOperation -> GetStatusRemoteOperation
GetRemoteUserInfoOperation -> GetUserInfoRemoteOperation
RemoveRemoteShareOperation -> RemoveShareRemoteOperation
UpdateRemoteShareOperation -> UpdateShareRemoteOperation

**Comment by tobiasKaminsky** [comment]
This is done.
