### ISSUE TITLE
After clearing of cache & dalvik cache Next cloud lost all accounts.

### ISSUE THREAD

**Issue by noci2012** [nextcloud/android#3155]
### Actual behaviour
- I cleared the cache & Dalvik Cache. (due to wifi issues).
When nextcloud was started the next time, it appearantly lost al info on it's account.
Also the DavDroid config went missing.

### Expected behaviour
- Account info should not be in the cache, but in account data.
 
### Steps to reproduce
1. Clear cache & Dalvik cache (from recovery)
2. restart phone (it takes time to "prepare all applications"
3. start nextcloud, it was missing it's account info.

### Environment data
Android version: 6.0.1

Device model: SM-G800F

Stock or customized system: Stock, rooted,

Nextcloud app version: 3.3.0

Nextcloud server version: 14.0.3

#### Web server error log 
```
N/A
```

#### Nextcloud log (data/nextcloud.log) 
```
N/A
```

**Comment by noci2012** [comment]
None of GitMate.io's issues are applicable...
There were no login problems or account problems other than it being in the cache data in stead of more persistent data.

**Comment by tobiasKaminsky** [comment]
Account data is stored in AccountManager of Android.
I tried this on my OnePlus3 and formatted dalvik/cache but on Android 8 and no data was lost. But this is maybe due to the fact that Android 6 is using the old app system…

I fear that we cannot do anything here…
