### ISSUE TITLE
Objects without sharing features showing sharing options 

### ISSUE THREAD

**Issue by emersonkfuri** [nextcloud/android#3160]
Description: Even if the objects (external storage and group folders) on web files app are explicit marked as non shareable, mobile app still shows share options

Steps to reproduce: Go on web app files, create group folders or external storages, disable sharing features for it, and view it on mobile

Version: 3.3.1 RC1

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky can you reproduce this? I don't have an IDE at hand at the moment but afaik we do not have a check for this in place but I might be wrong.

**Comment by emersonkfuri** [comment]
I was cheking #3162 and it references about  reshare options only in files. So maybe it is a regression because folders are showing too.

**Comment by tobiasKaminsky** [comment]
@emersonkfuri in #3162 in the first screenshot, you can see that the sharing button is invisible for folders.
Isn't this what you expect?

**Comment by emersonkfuri** [comment]
Yes, it is! Just saying on #3162 the button is only hide for folders which is not happening right now.

**Comment by tobiasKaminsky** [comment]
> And it should be hide for any object

No, if you have a e.g.text file, you might want to send it to your email app. Then you want to click on the "share" button as this is a combined send/share.
(in this case sharing is then hidden):

![2018-10-18-100026](https://user-images.githubusercontent.com/5836855/47139696-ba889d00-d2bc-11e8-9b7d-e9ff9662ccc6.png)

**Comment by emersonkfuri** [comment]
But if parent object is not shareable, why its children's should be?

At least in my case, when I mark a external storage and/or a group folder to not be shareable, I expect that any objects inside it cannot be shared too.

**Comment by tobiasKaminsky** [comment]
The share option is only meant for NC -> sharing with other user
Files can still be sent to other apps locally, even without NC: download a file, browse with any file manager to it and do whatever you want.

--> "share" is disabled, while "send" is still allowed
