### ISSUE TITLE
Auto Upload Notification recreation

### ISSUE THREAD

**Issue by SchoolGuy** [nextcloud/android#3163]
### Actual behaviour
- Picture is taken
- Nextcloud detects the new picture
- Uploads it
- Deletes the local picture (like it should)
- DCMI folder is empty
- Nextcloud sends a notification that a new upload folder has been found (actual bug)

### Expected behaviour
- There should be no notification about the new folder becuase it is not a new folder.
 
### Steps to reproduce
- Like above in "Actual behaviour".

### Comments from me
It is like a nag screen. The good thing is though that in the app no settings are altered. It seems from the outside just like a bug with the notifications.

### Environment data
Android version: 

Device model: Huawei P9 Plus (VIE-L09) & Samsung Galaxy S8 (SM-G950)

Stock or customized system: Huawei with Smart Launcher (5.1 build 048K), Samsung 100% Stock

Nextcloud app version: 3.3.0 on both

Nextcloud server version: 14.0.1 & 14.0.3

#### Web server error log
```
Should not be relevant and the timespan is too huge to include everything.
```

#### Nextcloud log (data/nextcloud.log)
```
The log is too long that I can assure that there is no sensetive data in it. From my point of view there are even no current log entrys. I will now empty the log and trigger the bug and look into the new one.

UPDATE: There is no log of any events. Not the successful upload of the picture nor the re-detection notification of the Camera folder. On both phones. The log is blank, not a single entry.
```

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky afaik this is a duplicate and there are two things that need to be implemented to get this type of notification right:
* Don't show the notification for a folder twice
* don't show the notification for a folder that is activated for auto upload

The later point is debatable since with the first approach it would then after being released only happen exactly once again so we could ignore the second part as a trade of to keep the check simpler.

**Comment by tobiasKaminsky** [comment]
This is the relevant part:
- it iterates over account and found media folders, in this case image
- notification is only sent if folder is not already setup for sync
--> this seems to fail in this case.

https://github.com/nextcloud/android/blob/13f00bfa4043d3fcd0209b730fad2b3faf80b134/src/main/java/com/owncloud/android/jobs/MediaFoldersDetectionJob.java#L108-L117
