### ISSUE TITLE
Grid view: file type icons smaller

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#3174]
From: https://github.com/nextcloud/server/issues/11902

![2018-10-19-083302](https://user-images.githubusercontent.com/5836855/47201292-a060c480-d379-11e8-9270-561ff50feff8.png) ![2018-10-19-083440](https://user-images.githubusercontent.com/5836855/47201363-d7cf7100-d379-11e8-9cf0-22a2497932d7.png)

Answer by @jancborchardt:
> @tobiasKaminsky nice, already looks much better! It's really visible how the folder icon size looks nicer in comparison to the rest.
> 
> * The other filetype icons also need to be smaller
> * The text below can be moved up a bit (towards the filetype icon)
> * Text size is also a bit large maybe? Is it the same as the file name in list view?

**Comment by AndyScherzinger** [comment]
@jancborchardt yeah, I know what you mean. From my pov people using the grid view for image folders don't really want to interact with the items (except for maybe opening the larger previews with the pager or maybe sharing the file with others). So having a very quick access for file actions not really needed nor helpful. No idea how to properly solve this atm :(

**Comment by joshtrichards** [comment]
This looks fixed to me. Can't find the relevant PR (and I suspect there are a couple different ones), but this is what it looks like so I'll close it out.
![image](https://github.com/nextcloud/android/assets/1731941/6877ca5e-599a-4ea3-b41d-f058df7c2438)
![image](https://github.com/nextcloud/android/assets/1731941/a20fb15d-b970-4e1a-a465-e0f135fb9165)
