### ISSUE TITLE
.thumbdata files uploaded

### ISSUE THREAD

**Issue by marco44** [nextcloud/android#3177]
Hi,

The app sends .thumbdata files to the server while synchronizing. I cannot find a way to not send them.

I only asked to send the "Camera" foldes automatically in "automatic upload" (don't know if these will be the exact term, as my phone is set up for french).

Phone is oneplus 5, stock rom (android 8.1.0)

The only thing I see in logcat is:
```
10-23 15:03:00.956 10031 10031 V UploadsStorageManager: Updating /storage/emulated/0/DCIM/.thumbnails/.thumbdata4--1967290299 with status=UPLOAD_IN_PROGRESS
```

Tell me if I can provide more.

Regards

**Comment by marco44** [comment]
Well, what can I do, dear bot ? :)

**Comment by tobiasKaminsky** [comment]
Hm. Auto Upload is built to be "dumb". It uploads everything, to not complicate it or  have too many options on UI.
We could add a custom check for ".thumbnail"…
Do you know which and why these .thumbnail folder is created? No one else reported this right now…

@AndyScherzinger you also have a oneplus 5?

**Comment by marco44** [comment]
I don't know, but I guess it's the thumbnails from the gallery app. But I'm wondering if this is still the case, cannot find it right now on my phone. It may have changed in a recent update

**Comment by tobiasKaminsky** [comment]
That would be good, as this should just not be in this directory…
If it happens again, please re-open.

**Comment by jamm73** [comment]
Hi,

I get the exact same issue.

The file is uploaded from my Android phone (Samsung S9), to my newcloud, everytime this file is changed (i.e. every time there is a change in the syncronized pictures folder).

In my case the file:

- name: **.thumbdata4--1967290299** -> NOTE: it starts with a dot '.', hiding the files while listing the folder.
- size: **687.8 MB** (today)

It is data, time and space in server.

It would be nice if we could avoid uploading that file.

Anycase, congratulation for his briliant product.


Regards,
José

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky as discussed in another issue and agreed on with Jan, we should detect (at least) this kind of file and prevent its upload. I can probably work on it in August (won't have the time before that).

**Comment by jamm73** [comment]
Many thanks.

Please contact me in case you think I can help you testing.

Regards.

**Comment by AndyScherzinger** [comment]
@jamm73 one question did you just activate auto upload for that folder or did you explpicitely define a custom folder in the auto upload screen?

**Comment by jamm73** [comment]
Hi, thanks for your reply.

My settings are:

- Server : I am using a folder I created called "/FotosMovil/" (no quotes).
- Phone : I selected the folder "/storage/3E94-12EE/DCIM/Camera" (no quotes).

I wish I am replyaing your question.

Regards,
José

**Comment by AndyScherzinger** [comment]
Hi @jamm73 thanks for the reply, 

my question was rather, did you:

a) open the auto upload view and hit the cloud icon on an entry within the list (which means the app auto detected the media folder) or

b) created a so called custom folder by explicitely choosing a folder on the device (which then uploads any files, not just media files)

Best regards,
Andy

**Comment by StarFscker** [comment]
Hello, I think this could best be solved with a simple option to avoid uploading dot files. It is very rare for any hidden files to require a sync.
