### ISSUE TITLE
Downloading image downloads wrong one

### ISSUE THREAD

**Issue by dlosku** [nextcloud/android#3196]
Hi,

I'm using Nextcloud in our Company and noticed that when I open a picture(photo, image etc.) it gives me the notice (No resized image available. Download full image? Yes). That's fine, I poke yes and nothing happens. The picture stays blurry. When I go back to view the file-list I see that the picture below has the green dot with white V on it..so it actually downloaded the picture BELOW. Yet I tested that if I open a picture, poke the 3 dots in the top-right corner and download from there it actually downloads the correct one. Could you please fix this small issue :) Thank you very many :)

Regards,
Oskari

**Comment by tobiasKaminsky** [comment]
Hm, if you open up an image, it tries to get the current one, the one before and the next one.
If any of these three is not available as resized image, it is shown as snackbar.
And if you then click "yes" it downloads it.

Can you verify this?

**Comment by dlosku** [comment]
When I click "yes" it only downloads the next picture, just tested that again. We are using our Nextcloud server only as a gateway to our own S3, we only use external storage folder, nothing is on actual nextcloud server. Can that kind of setup cause issue?

**Comment by tobiasKaminsky** [comment]
Can you try it with only one image in one folder? 
Then the "yes" should be for the current image.

But I guess the main question is, why there are no resized images possible.
Do you see anything in nextcloud.log?

@rullzer thumbnails/resized images on S3 external storage should be possible, or?

**Comment by dlosku** [comment]
If folder has only 1 image, then the resized picture is downloaded correctly. But if any more than that, then it's always the next one below.

I can see a list of the images with thumbnails in the folder. Only the snackbar "yes" doesn't do what it supposed to do.

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger can you reproduce this?

**Comment by AndyScherzinger** [comment]
> @AndyScherzinger can you reproduce this?

I can't. I created a folder with 3 images while one of them is corrupt (just renamed a pdf to .jpg). It prompet for full size download, did that and had the checkmark at the right "image". At least on latest master.

**Comment by dlosku** [comment]
If folder has only 1 image, then the resized picture is downloaded correctly. But if any more than that, then it's always the next one below.

I can see a list of the images with thumbnails in the folder. Only the snackbar "yes" doesn't do what it supposed to do.

**Comment by tobiasKaminsky** [comment]
Some time back I tried that the snackbar is only shown for the current image fragment, but I did not succeeded as fetching resized Image is async and therefore also the next one is tried, but there is no direct reference / no way to detect which fragment is currently visible.
