### ISSUE TITLE
Upload Nextcloud app to F-Droid not just the beta version

### ISSUE THREAD

**Issue by testman86** [nextcloud/android#32]
Even if it's written in the description that the official Nextcloud Android app is on F-Droid, at the moment just the beta is available there. Would be nice to have it also on F-Droid and not just google play store.

**Comment by LukasReschke** [comment]
That is in the process already :)

**Comment by testman86** [comment]
good to hear :-)

**Comment by tobiasKaminsky** [comment]
And we are in!
