### ISSUE TITLE
ability to change server adress

### ISSUE THREAD

**Issue by koksnuss** [nextcloud/android#320]
It would be nice if it would be possible to change the server adress of an existing account. just as if you change the password. it would be very useful for me as my server adress is changing regularly...

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky what do you think. I get the problem @koksnuss is trying to solve here. The risk is users putting in a different server, so when the server address is changed we would have to basically throw away the account and reinitialize to make sure we don't corrupt any data... (imho)

**Comment by tobiasKaminsky** [comment]
Changing the server address should only be possible by removing and re-adding the account as this is a very basic change of the whole app.
The question is why is your server address changing this often @koksnuss and how to solve this?
Your idea is just trying to bypass the real problem.

**Comment by js-d-coder** [comment]
There is a workaround this issue. You can set the url something `http://raspberry` instead of any IP. Then point the `raspberry` to the IP, which can be set/edit anything using DNS Changer on Android or editing `/etc/hosts` on Linux... Enjoy. Now I don't have problem accessing my raspberry from android or desktop even if I move onto different network.

**Comment by koksnuss** [comment]
@tobiasKaminsky my server address is changing from time to time as i am trying to rely on free subdomains from https://freedns.afraid.org. Due to quantity-limitations for free letsencrypt certificates for some of these (quite popular) subdomains i faced multiple issues across the last years which effectively forced me to change the server address. I do not understand what you mean by 'Your idea is just trying to bypass the real problem.' What is the real problem her? The fact that I change my server address from time to time? I cannot see the 'problem' here as i think it is legitimate to change my server address from time to time but still like the ability to not resync all files, reconfigure all clients.

@js-d-coder this is a very nice workaround, thank you very much!
