### ISSUE TITLE
Contacts restore - no way out

### ISSUE THREAD

**Issue by jmue** [nextcloud/android#3213]
### Actual behaviour
- The contact restore activity can not be closed in any way

### Expected behaviour
- The contact restore activity can be closed
 
### Steps to reproduce
1. Enable daily contact backup
2. Go to activity view and click on the created backup file
3. Try to close the contact restore activity be eigther the navigation-up or back-button 

The also no way to get out of this by closing the nextcloud app from task manager. Clearing cache data has also no effect. Even if I restore a contact I get back to the restore activity again.

### Environment data
Android version: 3.0.1

Device model: Moto G5

Stock or customized system: Stock

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
I can reproduce this issue with the latest master, it is basically a navigation loop from contacts-backup<->settings screen and no way out. Had to re-install.

**Comment by tobiasKaminsky** [comment]
Force close should be enough, or?

**Comment by jmue** [comment]
You're right. Force close do the job.👌

**Comment by jmue** [comment]
THis seems to be fixed on master branch.
