### ISSUE TITLE
App crashes when synchronizing big folders

### ISSUE THREAD

**Issue by Any0ne22** [nextcloud/android#3220]
When I try to synchronize folders with a great number of files (around 700 in my case) the app shows a popup saying "close the app or wait" and if I don't click on wait the application stops. But if I stay 15 or 20 minutes clicking on "wait" each time the popup appears the download will start normally.
Sorry for my bad English I hope my explanations are clear

**Comment by tobiasKaminsky** [comment]
Thanks for reporting this issue. It is a duplicate of #2679, which we will address hopefully soon.

**Comment by kiwijunglist** [comment]
Hi i have this problem currently, latest version of nextcloud on android phone. 3440 photo/video in folder.
