### ISSUE TITLE
Share dialog: set expiration date option disappeared in version 3.3.x

### ISSUE THREAD

**Issue by mel26** [nextcloud/android#3224]
### Actual behaviour
- Share file dialog does not contain option to set share expiration date
- It's impossible to set "share by link" expiration date like in desktop app and web interface
- This option was present in previous version of app (I think below 3.3), but in version 3.3.2 there is no this option

### Expected behaviour
- Share file dialog contain option to set expiration date
 
### Steps to reproduce
1. Open share dialog for file or folder
2. Share file "by link" or "by user name"
3. There is no option to set share expiration date

### Environment data
Android version: 8.1, 9.0

Device model: Google Nexus 5X, Google Pixel 2XL

Stock or customized system: Stock

Nextcloud app version: 3.3.2

Nextcloud server version: 14.0.3

![screenshot_20181105-004741](https://user-images.githubusercontent.com/8760037/47970300-9ab2f080-e094-11e8-8b50-cef4b750a80c.png)
![screenshot_20181105-004715](https://user-images.githubusercontent.com/8760037/47970301-9ab2f080-e094-11e8-809e-ab980dc0f911.png)

**Comment by tobiasKaminsky** [comment]
![2018-11-05-122837](https://user-images.githubusercontent.com/5836855/47995669-58ba9680-e0f6-11e8-9112-2164998ee190.png)


For me, latest version and NC15 "expiration date" is shown for "share via link", but not for users.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky my guess is that this is a layouting problem since the whole 3-dor menu isn't shown. @mel26 what happens if you flip the device for landscape?
My guess is that this is due to the too long transtaion strings, maybe...

**Comment by tobiasKaminsky** [comment]
In all above screenshots I can see the "3-dot" menu?

**Comment by AndyScherzinger** [comment]
see firsst screenshot pposted by @mel26 -> no 3 dow menu

**Comment by tobiasKaminsky** [comment]
ahaha. Stupid me. 
I only saw the first three dot menu, but not the menu for the link…

As you are the UI pro, maybe you can have a look?

I will then have a look if and how shares to user should have an expiration date.

**Comment by AndyScherzinger** [comment]
> As you are the UI pro, maybe you can have a look?

I'll have a look. Might be though that we need to have ellipsizing in place (pretty sure we need to)

**Comment by tobiasKaminsky** [comment]
We have enough vertical place…But I am unsure how this could look like in a good way…

**Comment by AndyScherzinger** [comment]
> We have enough vertical place…But I am unsure how this could look like in a good way…

No idea really. We can of course try to implement this with multi-line fields which would also solve th issue and would be an alternative to ellipsizing, true.

**Comment by mel26** [comment]
You right.
In horizontal orientation I can see 3-dot menu.
In vertical - no.

--
С уважением,
  Павел А. Мельниченко

пн, 5 нояб. 2018 г., 14:38 Andy Scherzinger notifications@github.com:

**Comment by AndyScherzinger** [comment]
looking for @nextcloud/designers' input. For the sharing dialog on Android we have the situation that (for sharing links we might have translations (like this one) where the text consumes to much space leading to the menu being hidden. We do have 2 (technical) solutions for this:
* ellipsize the text (ellipsizing middle?) so the single line item layout will be preserved while that means the texts might be shortened
* make the texts 2-line text which will lead to list items of different size or slightly different layouting (1-line Text for user shares vs. 2-line Text for link shares)

Actual situation for a non-Englisch screen:
<img width="720" alt="47970300-9ab2f080-e094-11e8-8b50-cef4b750a80c" src="https://user-images.githubusercontent.com/1315170/48058963-2b362180-e1b8-11e8-8d41-f34cff33f937.png">

**Comment by jancborchardt** [comment]
Yeah, we also had these space issues on the server. We decided that for links we only show:

> Share link    [ 📋 Copy ]  •••

And the "Allow editing" checkbox needs to go into the 3-dot menu.
