### ISSUE TITLE
Fix or remove failing tests

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#3232]
atm 2 tests for uploading are failing in drone CI. This breaks every build and thus makes QA for PRs rather complicated since you always have to check the build logs to see if you hit the test issue or if something else broke.

So to get CI back we should either remove or fix the tests.

@tobiasKaminsky

**Comment by tobiasKaminsky** [comment]
I took a look on Friday, but I'll have deeper look now.

**Comment by tobiasKaminsky** [comment]
So…This seems to be a server bug.
Uploading a 0b file leads to a complaining dav…

**Comment by AndyScherzinger** [comment]
So we need to create a non-zero-bytes file within the tests, right? Do you have the time to implement this? (Just asking)

**Comment by tobiasKaminsky** [comment]
Yes, and no…
No, as we/client/user can upload 0b files, it should be fixed on server.

And yes, we should also test upload with non-zero files to make sure that this works.
And also with bigger files, so we test chunked upload.

**Comment by tobiasKaminsky** [comment]
PR with new test cases is #3233 
For server, @rullzer knows, so we can close this.
