### ISSUE TITLE
Thumbnails cache disappear/cleaned after a awhile?

### ISSUE THREAD

**Issue by eirmd** [nextcloud/android#3240]
### Actual behaviour
- Cache image not display after a few days / a week and need to regenerate again.

### Expected behaviour
- When I open my folder with photo and the thumbnail cache image generated, I hope it'll stay there because its slow to generate the whole pictures in every folder.
 
### Steps to reproduce
1. Open nextcloud client, go to my pictures folder and scroll all the pictures so the thumbnails cache displayed/generated.
2. Close/exit nextcloud client and open it again, go to the picture folder, the thumbnails image is there.
3. But after a long time, maybe a week not opening the nextcloud client and open it again, the thumbnails/cache is not there and need to regenerate again.

### Environment data
Android version:
7.1.2
Device model: 
Xiaomi Mi Max
Stock or customized system:
LineageOS 14.1
Nextcloud app version:
3.3.2
Nextcloud server version:
14.0.3

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by eirmd** [comment]
Oh, it means cache will be removed if no cache space left (200MB) and if there's a new image, cache must be generated but not for all folder? Correct me if I am wrong.

Currently my cache size is 33.29 MB.. and I am still have a lots of picture to see/regenerate cache. I'll let you know later..maybe the cache will reach 200MB

I dont think Xiaomi doing auto-cleanup because I am using custom rom, LineageOS 14.1 but I'll see all the possibilities..

**Comment by eirmd** [comment]
The max size for cache I got is about 80MB, but today the size of the cache is 60KB. I don't know what happen. Free internal space about 600MB. I dont know how to reproduce the problem. I'll try again to cache only 1 or 2 folder with less images and see what happen next.

**Comment by tobiasKaminsky** [comment]
Seems to me that any app is cleaning the cache.
We do not have something like that in our app…

**Comment by eirmd** [comment]
I think this problem related to rom and available space (storage).
Auto clear all cache when then storage almost full (maybe).
Now my free space is 1GB, since then, no problem with my nextcloud thumbnails cache. I'll see what happen after a few days and I will make more free space of my storage.

**Comment by tobiasKaminsky** [comment]
Glad to hear that it is not a bug in NC ;-r
If you experience it again, please re-open.
