### ISSUE TITLE
Nextcloud App crashed on Samsung Galaxy Note Edge

### ISSUE THREAD

**Issue by Dom-Gabriel** [nextcloud/android#3242]
When I try to start the Nextcloud App on my Samsung Galaxy Note Edge, the app crashes. I am not able to use it. It worked with previous versions.

Details:
Device: Samsung Galaxy Note Edge (SM-N915FY)
Device Android: 6.0.1, Kernel 3.10.40
Nextcloud-Version: 3.3.2 (02-Nov-2018)

The issue happens both on WiFi as well on 4G networks.

I sent an error report via my GMail address (grueeck@gmail.com).

**Comment by tobiasKaminsky** [comment]
To which address did you send this? I cannot find it.
Can you send this again to tobias at nextcloud dot com?

**Comment by Dom-Gabriel** [comment]
Hello Tobias,

 

It seems that my phone does send such error reports to Google directly (see attached screen shot). I have no option to change this nor do I see this message in any „Sent“ folder or so.

 

As the crash message was popping up several times when I work with the phone, I uninstalled the app from my phone. I’ll give it another try in some weeks or so and use M$ OneDrive meanwhile.

 

On my tablet (Android 8.1), things work fine, though.

 

Best Regards,

Gabriel.

 

Von: Tobias Kaminsky <notifications@github.com> 
Gesendet: Donnerstag, 8. November 2018 07:52
An: nextcloud/android <android@noreply.github.com>
Cc: Dom-Gabriel <gabriel@caipirinha.spdns.org>; Author <author@noreply.github.com>
Betreff: Re: [nextcloud/android] Nextcloud App crashed on Samsung Galaxy Note Edge (#3242)

 

To which address did you send this? I cannot find it.
Can you send this again to tobias at nextcloud dot com?

**Comment by tobiasKaminsky** [comment]
Sad to hear.
I'll have a look int gplay crash reports, maybe I find something suspicious on your model.
