### ISSUE TITLE
App does not show notifications due to 'outdated user session'

### ISSUE THREAD

**Issue by RiSK1979** [nextcloud/android#3244]
The next cloud app doesn't show server notifications and insists that I am using an 'outdated user session'. It recommends removing the account and adding it once again, but even after setting it up again, it keeps showing me this message.

[Screenshot here](https://cloud.keuchen.net/s/9FCxHiPrPBoiXFJ)

App version: 3.3.2
Device: Samsung Galaxy S8 (Android 8.0.0)
Logged in via App token

**Comment by tobiasKaminsky** [comment]
Which server do you use?

**Comment by RiSK1979** [comment]
Thanks for your feedback. Im' running Nextcloud 14.0.3 on an Odroid HC-2 with up-to-date NextcloudPi.

Ah, and btw. with the German translation of the android app, the message is too small to read the text on a vertical screen. I needed to switch to horizontal view to read the message in total and get its meaning.

**Comment by tobiasKaminsky** [comment]
Can you create us a test account, test if the problem occurs also there and if so send the credentials to tobias at nextcloud dot com with a reference to this issue?

**Comment by RiSK1979** [comment]
Sorry for net getting back here earlier. I have been on a business trip. I have set up an account for you and sent the login credentials by mail

**Comment by viggy96** [comment]
I have this same issue on Nextcloud server 15.0.8, Android app version 3.6.1. I use two factor authentication on my account.

**Comment by tobiasKaminsky** [comment]
@viggy96 
Can you create us a test account, test if the problem occurs also there and if so send the credentials to tobias at nextcloud dot com with a reference to this issue?

**Comment by viggy96** [comment]
@tobiasKaminsky The error does not occur on a test account. The test account does not use 2FA however. What does this mean? How can I fix this on my primary account?

**Comment by viggy96** [comment]
@tobiasKaminsky Is there any other guidance that can be provided? As stated earlier, the issue did not occur on a test account. But it still occurs on my primary account.

**Comment by schniepp** [comment]
I also have the problem that I get the "old login" message — although I have logged in via QR code. Server is 18.0.4, and android app was installed via Google Play Store. I also have 2FA enabled. Is there a chance that 2FA and the notification in the Android app don't play together well?

**Comment by schniepp** [comment]
OK, now I turned off 2FA, and the problem still happens. Then, I also created a test account and added it as a second account on the android app. On this app, I don't get the "old login" snackbar when I click the notifications menu. Removing and re-adding my main account on the android app did not solve the problem: I still get the snackbar.
