### ISSUE TITLE
Version 3.3.0 is consuming network data

### ISSUE THREAD

**Issue by gfordinal** [nextcloud/android#3246]
Thanks for your answer on Playstore: "Do you use VPN, or something similiar? Do you see this info "only" in settings, or do you actually see upload in progress when not using wifi?"

- VPN: nope.
- The data consumption is only visible when I looked up my data summary in the system settings. No active uploads visible, I didn't open the app to browse files.
- I deactivated background data for this app in system settings as a consequence.
- Luckily files are still auto-uploaded in WiFi, showing the progress notification (seems not to count as background data).
- I initially added a second account (two months ago), deleting the old one one the way. But this setup should cause the "mobile network upload issue".
- Not sure if still the case, since I didn't re-activate background data again - to save my plan.

LG G6 (LG-H870), Android 8.0.0, Software version V20c-EUR-XX

**Comment by tobiasKaminsky** [comment]
If you create a new account you would have to re-setup the upload settings also for this account.

**Comment by gfordinal** [comment]
Sorry, this is obvious, not sure what made you mentioning that...
I am not complaining about any lack of auto-uploading my images; on that
end, everything's fine.
It's about data consumed by the app in the background on the mobile
connection (without me taking new images) in the magnitude of several
hundreds of megabytes.


Am Do., 8. Nov. 2018, 07:58 hat Tobias Kaminsky <notifications@github.com>
geschrieben:

**Comment by tobiasKaminsky** [comment]
Is this really upload via mobile data? 
Can you try to figure out what there is transferred?

Several hundred mb still sounds like auto upload…

**Comment by gfordinal** [comment]
Hey, I'm gonna check back after a clean new install and re-affirm
afterwards.
Blocking background data via system settings did it for me.

Am Fr., 9. Nov. 2018 um 13:03 Uhr schrieb Tobias Kaminsky <
notifications@github.com>:

**Comment by sehucke** [comment]
Hi,

I am having the same problem: NC 3.3.2 consumes much background traffic. (i.e. ~415 MiB since 01.11.2018) I had only one auto upload folder active - just for testing purposes, no files got uploaded in November. Only other files that got uploaded were the daily contacts backups (~225 KiB * 19 days).

**Comment by sehucke** [comment]
I completely disabled the Auto-Upload 7 hours ago. Despite that, NC consumed 6 MiB of background traffic during that time.

I will check the server access logs later on...

**Comment by sehucke** [comment]
I was able to do a quick check only this evening... Only things that were logged under my username: some dozen calls to index.php/204 and to status.php.

I will try to take a deeper dive into the logs tomorrow.

Any ideas what could be the cause so far?

**Comment by sehucke** [comment]
There are only a few files listed in "on this device" - but they were not updated. And to produce that "much" traffic (7-8 MiB last night) they all must have been downloaded several times when I was asleep. ^^ Should see that in the nginx access logs this evening.

**Comment by sehucke** [comment]
Ok... I got some information out of the NC client log.

Just took a quick view inside when the next 4-5 MiB were used: Seems like NC is updating _all_ folders of my account in the background.

Unfortunately, I cannot open the exported logs on my phone. I will paste some entries later @ home.

Stumbled upon some other weired entries, too. I will check them and open separate issues when needed.

**Comment by AndyScherzinger** [comment]
Thanks for the feedback @sehucke - On initial installations the client indeed does load the whole folder/file structure as-in it's meta information not the files themselves of course. So this should then happen exactly once and it also shouldn't consume gigabytes of data.

**Comment by sehucke** [comment]
I just realized that I activated the sync under "Android settings" -> "Accounts" -> "Nextcloud" some time ago... When I was troubleshooting the failing auto upload.

I was wandering what this setting is for and thought it would have no effect at all. Could this trigger a frequent reload of folder metadata?

**Comment by AndyScherzinger** [comment]
> I was wandering what this setting is for and thought it would have no effect at all. Could this trigger a frequent reload of folder metadata?

According to https://help.nextcloud.com/t/what-is-settings-accounts-nextcloud-sync-for/36548/7 and @tobiasKaminsky it syncs the files that have been marked "keep-available-offline"

**Comment by sehucke** [comment]
Ah, I see. :-) Another piece in the weird and confusing sync/offline/favourite/download puzzle. ;-)

Ok, back to topic: The log entries suggested NC detected some changes in those folders. And it seems to constantly detected a new server version, thus loading the server capabilities over and over again.

**Comment by sehucke** [comment]
> 204/status.php would be checks if the server can still be reached which afaik is done every 15 minutes, but again @tobiasKaminsky and @mario might know more about this.

According to my logs, this is done more often. But this should not produce that much traffic.

**Comment by sehucke** [comment]
OK, I nailed it down: I disabled the sync option in "Android Settings" -> "Accounts" -> "Nextcloud" a few days ago. No more background traffic occured (at least only < 1 MiB).

There might be a bug in the "sync" feature that generates too much traffic. Especially when you consider the logs above.

**Comment by matsest** [comment]
Same issue here. Not enabled auto upload and minimal (kB range) of new files added. Only two very small files markes as offline. Still uses tens of MB every day in sync BG data. It also uses a significant amount of battery.

Disabled sync in android settings now, but it would be nice if this was solved without such "fixes" from users.

**Comment by tobiasKaminsky** [comment]
With #2886 we do not have available offline anymore.
Once this is in dev version (available via Fdroid) it would be really cool if you both @sehucke and @matsest could test this.

**Comment by matsest** [comment]
Thanks, will try out. Btw, is there any difference between regular Nextcloud app as downloaded from GPlay or Fdroid @tobiasKaminsky?

**Comment by AndyScherzinger** [comment]
> Thanks, will try out. Btw, is there any difference between regular Nextcloud app as downloaded from GPlay or Fdroid @tobiasKaminsky?

Yes, f-droid doesn't ship with push notification support. Other than that is is the exact same app / code base.

**Comment by sehucke** [comment]
I do not use Fdroid by now. Will the new dev version be available on GPlay as well?

**Comment by AndyScherzinger** [comment]
Dev versions are published via f-droid only

**Comment by tobiasKaminsky** [comment]
There is also the way to download & install it manually: https://download.nextcloud.com/android/dev/

I suggest that you subscribe to #2886 and if this is merged, you can try it in dev version.

**Comment by matsest** [comment]
Dev version is working fine - look forward to seeing #2886 merged. I added a [question](https://github.com/nextcloud/android/pull/2886#issuecomment-446634708) regarding the new Sync option in that PR.

**Comment by Neugebam** [comment]
Hi,
same Problem here. I had to disable "background data" in the System Options.
Before disabling tons of "propfinds" in the Server log:

x.x.x.x - USERNAME [13/Jan/2019:05:24:56 +0100] "PROPFIND /owncloud/remote.php/webdav/ / HTTP/1.1" 207 858 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.4.1"

It crashed my amount if mobile data (1.6 GB since 3.1.2019 for the NC-app).
I remember that I put a large external folder (pictures) via SMB into my nextcloud Server settings before.

I never used auto-upload and so my solution at the moment is to disable "background data" for the NC-app.

Android version:
8.0.0

Device model:
Sony H3213 (xperia XA 2 ultra)

Stock or customized system:
Stock

Nextcloud app version:
3.4.1

Nextcloud server version:
15.0.2.0
