### ISSUE TITLE
Instant picture upload fails on permission error

### ISSUE THREAD

**Issue by brjhaverkamp** [nextcloud/android#325]
### Actual behaviour

i enabled instant upload for photos. Initially the external storage directory I choose was not writable and the app gave a correct error. After the issue was fixed, the error remains. I verified the upload location and can upload files from the nextcloud client. But Instant picture upload keeps giving an error. 
### Expected behaviour
- After fixing the permission issue the photos should upload without errror
### Steps to reproduce
1. Upload photo to external storage without write permission
2. Wait for error
3. Fix write permission
4. Try to upload photo again, or upload new photo
### Environment data

Android version:
6.0.1
Device model: 
Samsung Galaxy S5
Stock or customized system:
Stock
Nextcloud app version:
1.3.1
Nextcloud server version:
10.0.1
#### Web server error log

```
Insert your webserver log here
```
#### Nextcloud log (data/nextcloud.log)

```
Insert your Nextcloud log here
```

**Comment by brjhaverkamp** [comment]
I am not sure if the initial permission error is related to the bug, I included it for completeness.
But even with new pictures and after setting the the destination directory to something different the problem remains.

**Comment by AndyScherzinger** [comment]
Hi @brjhaverkamp do you see anything regarding the retried upload in the server's log file?

**Comment by mario** [comment]
Please try newest beta if you're running Android 5+:

https://github.com/nextcloud/android/raw/beta/apks/latest.apk

Thanks!

**Comment by tobiasKaminsky** [comment]
@brjhaverkamp any new infos regarding your issue?

**Comment by brjhaverkamp** [comment]
Not really. I can confirm that upload is still not always smooth. On my wife's phone I could not get the upload of older failed uploads to restart, while newer photos uploaded automatically fine. In the end I used,USB to get the photos uploaded manually.
Some better error messages might help getting more and better info.

Kind regards, 

Bert

On 23 June 2017 09:41:07 GMT+02:00, Tobias Kaminsky <notifications@github.com> wrote:
>@brjhaverkamp any new infos regarding your issue?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/nextcloud/android/issues/325#issuecomment-310595580

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mario** [comment]
Dear users,

thank you for your patience. After lots of work, we’re super excited to be able to give you a test version with new auto upload implementation. Keep in mind we will only accept bugs related to Auto Upload in this APK, as other things might be broken.

https://cloud.nextcloud.com/s/ftZraTruRQjTe0R

This is a dev APK so it will not overwrite your existing play store/f-droid APK unless you’re already running dev version. Also, you might need to remove your existing dev version before installing this one.

Explanation of the current functionality:
- added support for custom folders
- separated image and video folders
- checks for new files happens every 15-20 minutes
- automatic retry every 15-20 minutes or when you force close/open the app
- automatic pause once network is changed (untested!)
- significantly less battery usage

All and any testing is more than appreciated, especially with large and ever-going files like Videos. (like, try to record a 30 min video).

Let me know if you’ve got any questions.

Cheers,
Mario

**Comment by tobiasKaminsky** [comment]
No response within the last month, therefore closing.
Please feel free to reopen with additional infos, if the problem still exists.
