### ISSUE TITLE
Switching from "Activities" to other view does not work

### ISSUE THREAD

**Issue by pasdVn** [nextcloud/android#3253]
### Actual behaviour
Switching from "Activities" to "Favourites", "Photos" or "Shared"  in the side menu does not work. The "Activities" view is kept (i.e. nothing happens). But in the side menu the view you tried to switch to is highlighted.

### Expected behaviour
Switching to one of the mentioned views should also work, if your starting point is the "Activities" view.
 
### Steps to reproduce
1. go to "Activities" view
2. go to "Favourites", "Photos" or "Shared" via the side menu
-> nothing happens

### Environment data
Android version: Android 7.1.2

Device model: jfvelte

Stock or customized system: lineage os 14.1

Nextcloud app version: 3.3.0 (f-droid)

Nextcloud server version: 14.0.3 (running on nginx)

**Comment by tobiasKaminsky** [comment]
This is fixed via https://github.com/nextcloud/android/pull/3065 and will be in froid with RC1 ~end of November.

Maybe you want to try out our dev version (you can install it in parallel): 
https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#dev-release
