### ISSUE TITLE
bad displayed file list on android tv box (landscape): only in first 1/3 of screen 

### ISSUE THREAD

**Issue by fuuzi** [nextcloud/android#3254]
![screenshot_20181109-014014](https://user-images.githubusercontent.com/2010692/48287144-25fefe00-e468-11e8-9647-df8377d11ccd.png)
### Actual behaviour
bad displayed file list on android tv box (landscape): only in first 1/3 of screen - as on attached screenshot

### Expected behaviour
used whole width of screen or setupped part of screen (i dont want to see only first few chars of file names, when there is much more free unused space around)

### Steps to reproduce
1. go to directory listing

### Environment data
Android version: 8.0
Device model: ROCKCHIP h96 MAX 

Stock or customized system: STOCK

Nextcloud app version: 3.3.2

Nextcloud server version: 14

**Comment by tobiasKaminsky** [comment]
This is our current way for showing files in landscape format.
You are right, there is clearly way to improve, as you can see in these issues:

https://github.com/nextcloud/android/issues/1742
https://github.com/nextcloud/android/issues/912
https://github.com/nextcloud/android/issues/1750

So I close this as a duplicate.
