### ISSUE TITLE
"Server unavailable" / SSL Error on missing auto upload directory (i.e. after manually deleting it)

### ISSUE THREAD

**Issue by fabian727** [nextcloud/android#3256]
### Actual behaviour
- I enabled auto upload of pictures (with WiFi) of selected directories. Those pictures will be uploaded to my cloud into the directory www.***.com/.../pictures/yyyy/mm/
- If I take a picture it won't upload, but I get the error "server unavailable", SSL Error

### Expected behaviour
- the picture should upload
 

### Steps to reproduce
1. enable auto upload into year and month named directories
2. the directories will be created and new pictures will upload
3. now delete the directory and take a new picture
4. you get the error. I would expect the directory to reproduce "itself"

### Environment data
Android version: 8.0.0

Device model:

Stock or customized system: stock

Nextcloud app version: 3.3.2

Nextcloud server version: 14.0.3

**Comment by fabian727** [comment]
@nextcloud-android-bot : similiar questions, but not the same, so not related. I have the issue with deleting and creating the upload directory, but not uploading the file itself

**Comment by joshtrichards** [comment]
Hi @fabian727 - Are you still able to reproduce this behavior today?

**Comment by fabian727** [comment]
sry for the delay.
Thanks for the response and your time making my life easier.

I couldn't reproduce today.
