### ISSUE TITLE
Top-right menu on Uploads missing

### ISSUE THREAD

**Issue by 491810** [nextcloud/android#3258]
I am using nextcloud on Android 9 (Pie) on the new Huawei Mate 20 Pro. And I am missing the top-right menu in the "Uploads" section to clear/reload/delete the upload list. Not able to clear the list. Just able to force reloads by pulling down the list. Bug or feature?

**Comment by 491810** [comment]
I'm not missing any of those. I miss the top-right menu in "Uploads" which gives me the option to delete uploaded, force recheck and delete uploaded files.

**Comment by AndyScherzinger** [comment]
Hi @491810, please go to the app's settings and activate the expert mode, then the menu should be visible.

**Comment by 491810** [comment]
Thanks Andy. Worked. Totally forgot that this „expert option“ was there when setting up the new Huawei Mate 20 Pro. 
Sorry for reporting this. Due to the fact that I’m new on Github … is there a way to delete my report? Or can you close it?

 

Von: Andy Scherzinger [mailto:notifications@github.com] 
Gesendet: Sonntag, 11. November 2018 22:51
An: nextcloud/android <android@noreply.github.com>
Cc: 491810 <491810@gmail.com>; Mention <mention@noreply.github.com>
Betreff: Re: [nextcloud/android] Top-right menu on Uploads missing (#3258)

 

Hi @491810 <https://github.com/491810> , please go to the app's settings and activate the expert mode, then the menu should be visible.

**Comment by AndyScherzinger** [comment]
@491810 no worries glad I could help, issues can't be deleted but I closed it :)
