### ISSUE TITLE
The ability for users to more manually edit/delete/hide their auto-upload media folder connections. 

### ISSUE THREAD

**Issue by jcklpe** [nextcloud/android#3263]
### Is your feature request related to a problem? Please describe.
I find it very annoying that every time any app I use downloads an image nextcloud will then create an auto upload folder connection. Here are some scenerios where the current behavior is a problem:

1. Sometimes I download an app just to try it out, or use it temporarily and then I uninstall it. But even once I uninstall, that doesn't get rid of the left over auto-upload folder connection. Over time this creates lots and lots of auto-upload folders that are useless and may not even be referencing an existing folder on either local or remote. 
2. Sometimes apps will create folders that have recognizable media that triggers the creation of an auto upload folder but I don't want these folders auto uploaded nor should they be junking up the auto upload folder connection UI. The nextcloud devs can't really predict where some apps devs might choose to stick folders, and it would be bad design if the installation of one unscruplous app could throw the NC UX into disarray. 
For instance, I have a folder where I store Gameboy ROMs for emulation on my phone. Sometimes the ROM distributors will include a small screenshot picture so that the folders will be easier for a human to visually scan in a desktop file manger program. I don't want 65 individual 125kb images each getting their own  auto upload connection and cluttering up the UI. 
Another example, I am subscribed to 137 podcasts, and while I don't listen to them all, all the time, I do have most of them set to auto download the latest episodes when on wifi. If a podcast app chose to cache the album art images to the user's folder then it would be chaos!
3. Sometimes I change my mind about where I want the app to be remotely. In my case, I originally had my camera upload to InstantUploads/Camera on my server. Then I changed my mind and I created a folder called Phone/Camera on my server. I could change the existing auto upload folder, but if I uninstalled and then reinstalled NextCloud it would create 2 auto upload folder connections! One for InstantUpload/Camera and one for Phone/Camera. Very annoying!
4. Sometimes I have a folder that contains many subfolders with media, but I really only need the top layer folder to be identified by the autoupload folder connections. In my case, I have a folder called "Library" in which I put audio books on my server that I want to be then synced over to my phone. But the NextCloud client doesn't set up a folder for "Library", it sets up an auto upload folder connection for every single book in the library, because every book is in it's own sub folders. The auto upload folder connection is triggered by the presence of album art in the folder. This is also a huge problem for people who might want to sync over their Music Library, which I imagine is a really common use case for the NextCloud android client. 

### Describe the solution you'd like
Currently it is possible to edit folder connections. This is good (though it does not appear to be very persistent as shown by my uninstalling and reinstalling issues mentioned in example 3 above). 

It is also possible to set an auto upload folder connection to inactive. This is also a good feature

 But it should also be possible to delete/hide inactive connections. Doesn't really matter which, it just needs the ability to reduce the amount of extra chaos added to the UI by all the extra crud. 

### Describe alternatives you've considered
I have uninstalled the NextCloud android client and set up a bunch of syncing folders with FolderSync [[link]](https://play.google.com/store/apps/details?id=dk.tacit.android.foldersync.full&hl=en_US)

I would prefer to support/use/test the NextCloud client though. The foldersync is not specifically made for NextCloud so it has a more cluttered interface, setting up syncs is less straightforward, and because it relies on a webdav connection the instant sync feature only works when adding or deleting files on the android side of things, and can not work the other way around.

### Additional context
A lot of my issues can be tracked by this previous bug report when I originally thought that this was possible and the difficulty in doing this thing was not by design: https://github.com/nextcloud/android/issues/3161

Also see related feature request issue here https://github.com/nextcloud/android/issues/3239

**Comment by jancborchardt** [comment]
And in case someone does want to sync these after all, we could show at the bottom of the list:

> Show 37 excluded folders (albums, podcasts, …)

Which then would toggle showing them below.

**Comment by AndyScherzinger** [comment]
> Could there be a set of simple exclude rules? Like:
>
> If the folder only contains one image called "cover.jpg/png" (and only music files otherwise), we can assume it's an album and exclude it from auto upload.

Yes we could probably do such a thing. @jcklpe could you provide some input on your folder structures for podcats, roms, etc?

> And in case someone does want to sync these after all, we could show at the bottom of the list:
>
> Show 37 excluded folders (albums, podcasts, …)
>
> Which then would toggle showing them below.

yes that would be possible to, while you then might rather want to configure a custom folder since you want to sync all files within that folder no matter the mime type :)

**Comment by AndyScherzinger** [comment]
while we can still have both hide/show as described by Jan and custom folders (already in place)

**Comment by jcklpe** [comment]
I would contend against an automatic solution, or at least for this particular ticket. It is very closely related though. When I first filed a ticket I actually included both this function and the ability to edit the automatic upload rules in the same ticket. I think @jancborchardt makes excellent points and that the issue of the editing of automatic upload rules would be a better fit for the original  ticket: https://github.com/nextcloud/android/issues/3239#issuecomment-438097413 

To me the focus of this ticket should be just the ability to manually hide/delete already created folders because no matter what automatic rules the user or the NC devs put in place, there is no real predicting what crazy thing any particular app dev might do, and I think it's good to give the user some level of manual control. 

Additionally this manual control is very simple, easy for the user to understand, and wouldn't need to add a whole bunch of extra fiddly bits to the UI. And I'm just a designer learning to develop, so I'm not a very good developer yet but I assume it would also be easier to implement. 

@AndyScherzinger : Sure thing. 

root
- sdcard
  - podcasts
     - backup
        - appbackup.file
        - feedbackup.opml
     - podcast
        - episode.mp4
        - episode.mp4
        - episode.mp4
     - anotherpodcast 
        - episode.mp4
        - episode.mp4
        - episode.mp4
  - Arcade
    - SNES
       - Gamefolder
         - game.rom
         - screenshot.png
         - readme.txt
       - Gamefolder
         - game.rom
         - screenshot.png
         - readme.txt
    - Gameboy
       - Gamefolder
         - game.rom
         - screenshot.png
         - readme.txt
       - Gamefolder
         - game.rom
         - screenshot.png
         - readme.txt
  - Ringtones
    - contact ringtones
      - friend.mp4
      - friend2.mp4
    - retroRingtones
       - mario.mp4
       - pacman.mp4
    - randomringtone.mp4
    - ringtone-placed-by-phone-vendor.mp4

**Comment by AndyScherzinger** [comment]
Thanks for the input @jcklpe - so all the folders you mentioned would be something that you want to be hidden?

auto-hidding for certain scenarios vs. manual hidding option are hard to compare effort-wise since a simple rule for auto-hidding certain folders would be simple to implement,complex rules might be tricky and hard to implement, manual hiding (+ the necessary UI part) is somewhere in between.

So without having an angreed rule definition (which o/c can't be changed by the user) it is hard to tell would needs more effort to be implemented. So that is something we need to agree on first, while I'd also like to have @tobiasKaminsky's feedback on this matter before any implementation work begins.
Unfortunately he won't be able to comment on this matter at the moment. So in order to take his feedback into consideration we need to wait for 2 weeks (sorry for that!).

**Comment by jcklpe** [comment]
@AndyScherzinger  To answer your question, I would want to not sync /podcasts but I would want to sync the contents of /podcasts/backup. 

I would want to sync the Arcade folder, but not individually sync the individual game sub folders (which is currently what is happening depending on if they have a screenshot in them). 

I would want to sync the Ringtones folder, but not have individual folder connections set up for the sub folders, which is what sometimes happens when I add stuff.

**Comment by AndyScherzinger** [comment]
we still need your help @nextcloud/designers with this matter to come to a solution that can work. This issue gets raised repeatedly, see latest issue #3384. So we should find a solution and spend the time on implementing it instead of having to deal with reported issues pointing out this matter ;)

**Comment by newhinton** [comment]
We could use two levels of control:

1. Level:
Toggle detection to either fully enabled or fully disabled. that would also disable the popups of a new detection.

This has the advantage that this app behaves more like the desktop client, but the disadvantage of increasing the "maintenance" by the user to configure folders.

2. Level: (Only nessessary with enabled detection)

2a) Button to toggle active/inactive folders
2b) Button to toggle between custom and detected folder
2c) Button to show/hide detected (inactive?) folders (and always show custom ones)
2d) @jancborchardt 's idea with show 37 more hidden elements

**Comment by jancborchardt** [comment]
> I would contend against an automatic solution, or at least for this particular ticket. It is very closely related though.

Remember we have a large userbase. We don't want every individual person to need to manage their stuff manually.

We should go with the automatic solution first (see what I suggested above) and based on that we can still enhance.

The vast majority of people don't ever change settings, and for them it needs to work by default. That's our main target audience. Special cases come afterwards.

**Comment by newhinton** [comment]
Yes sure, those were only the options :) So the default would still be detection-enabled, but you could turn it of if you don't need it or want to manage it manually. And Level 2 is not really influenced by this, depending on what will be implemented.

**Comment by AndyScherzinger** [comment]
So to sum things up we have different things that need to be talked about I guess:

* hidding (detected) folders
  * if they only contain a single image (easy to implement)
  * auto upload inital detection notification would still be shown (can't be prevented since we only detect the folder once when the first media file has been created on the file system within this folder)

* sub-folder
  * can be hidden as stated above
  * won't get uploaded to the server since the auto uploada doesn't care about sub-folders (at least with today's implementation!)
  * folders shown within the auto upload list by the detecetion mechanism are media-folders-only and also due to that the auto upload will only respect and upload media files of the given type (image or video!)

**Comment by AndyScherzinger** [comment]
> but you could turn it of if you don't need it or want to manage it manually

@newhinton beware that "managing manually" means you need to create custom folders (exper mode enabled) and that these kind on configurations are mime type independent so any file created in this folder will be uploaded to the server.

**Comment by newhinton** [comment]
Yes, but to be honest, that was what i was expecting from custom folders ;) 

But what about fully disabling the detection feature? This could be an option which is only shown when expert mode is enabled, and if you disable expert mode it is automatically turned on again. 
That would solve most problems @jcklpe is experiencing

**Comment by AndyScherzinger** [comment]
True, but in my personal experience it'll destroy the simplicity for most users. Since in my believe they just want their photos to be synced super easy. So simply clicking the cloud in the auto upload screen works for most people just fine, thus we just need to find a way to make this easy for power users without sacrificing the one for probably 90% of the users like my parents :)

**Comment by newhinton** [comment]
I may have choosen my words badly. I did not want to change the default behaviour, im completely fine with enabling autoupload! :) I meant that somebody who has expert mode enabled, could/should have the ability to fully turn autoupload off (for non-custom folders)

**Comment by jcklpe** [comment]
> > I would contend against an automatic solution, or at least for this particular ticket. It is very closely related though.
> 
> Remember we have a large userbase. We don't want every individual person to need to manage their stuff manually.
> 
> We should go with the automatic solution first (see what I suggested above) and based on that we can still enhance.
> 
> The vast majority of people don't ever change settings, and for them it needs to work by default. That's our main target audience. Special cases come afterwards.

This is true, I agree. I'm just saying I think the automatic solution conversation better fits the other feature request issue here: https://github.com/nextcloud/android/issues/3239

Setting up exclusion rules to determine whether or not something is going to be auto detected by the auto detection isn't really in the purview of this ticket. This ticket is purely about how to visually declutter the interface from an excess of folder connections that have been created automatically and then disabled by the user. 

These are distinct issues. 


> So to sum things up we have different things that need to be talked about I guess:
> 
> * hidding (detected) folders
>   
>   * if they only contain a single image (easy to implement)
>   * auto upload inital detection notification would still be shown (can't be prevented since we only detect the folder once when the first media file has been created on the file system within this folder)
> * sub-folder
>   
>   * can be hidden as stated above
>   * won't get uploaded to the server since the auto uploada doesn't care about sub-folders (at least with today's implementation!)
>   * folders shown within the auto upload list by the detecetion mechanism are media-folders-only and also due to that the auto upload will only respect and upload media files of the given type (image or video!)

I think this approach is conflating issues. Or maybe I'm not understanding your summation correctly. I think we've really got two separate features needed here and they have independent though overlapping usecases. 

I think @newhinton summed it up best here: 



> We could use two levels of control:
> 
> 1. Level:
>    Toggle detection to either fully enabled or fully disabled. that would also disable the popups of a new detection.
> 
> This has the advantage that this app behaves more like the desktop client, but the disadvantage of increasing the "maintenance" by the user to configure folders.
> 
> 1. Level: (Only nessessary with enabled detection)
> 
> 2a. ) Button to toggle active/inactive folders
> 2b. ) Button to toggle between custom and detected folder
> 2c. ) Button to show/hide detected (inactive?) folders (and always show custom ones)
> 2d. ) @jancborchardt 's idea with show 37 more hidden elements




**Level 1** is addressed by this ticket: https://github.com/nextcloud/android/issues/3239

And **level 2** is addressed by the ticket we are currently in: https://github.com/nextcloud/android/issues/3263


My vote on these issues are as follows. 

### Level 1:
Default to auto connection detection and creation, with the ability for users to go into the settings and turn off this default behavior (which then leaves only manually created folder connections being used)

This level 1 behavior could deal with the more complex exclusion rules that Jan mentions in his post, but I don't think the discussion of that issue is really needed in this ticket, it should really be in the other more relevant ticket. 

### Level 2:
Default behavior to automatically hiding all disabled folders, and putting a button at the bottom of the scroll that says something like `[click to view 37 hidden disabled connections]`.  

This is different than my original suggestion of making the hiding of these folders manual, since I realized... well pretty much the only folders you'd want to hide are the ones that are disabled and since there's already a toggle to disable the folders, there's no reason why it shouldn't also hide it either. That creates a baseline smart default auto behavior which covers 99% of usecases and doesn't add any additional UI toggles to the folder connections. (the only additional UI it adds is a "see more button" at the bottom which I don't think is going to make things difficult for users to grok)

**Comment by newhinton** [comment]
I would also suggest to add an exclude list of files to the expert mode, similar to the desktop client. (as an example, dcim often contains a .thumbdata* file, wich is often useless to sync)
that would allow us to even further refine the control over custom uploads

**Comment by jancborchardt** [comment]
Let’s not use "expert mode" as a pile we can add more stuff to. Every setting we add needs to be tested, and sometimes we also just need to say "hey, this might not make sense, let’s not add it". See new design discussion on expert mode at https://github.com/nextcloud/android/issues/3398

**Comment by bertwesarg** [comment]
sorry, I'm getting lost in all these 'auto-upload' related issues, but has someone already raised the issue, that I get constanty notifications about new media folder, only because I made a burstshot with my Camera (Noka stock)? The camera app creates for each burstshot a new folder, getting notifications about it while still taking photos is not welcomed. Sorry for taking over this issue here.

**Comment by AndyScherzinger** [comment]
@bertwesarg please see https://github.com/nextcloud/android/pull/3448 (and yes this has been raised :)

**Comment by newhinton** [comment]
@nextcloud-designers
@AndyScherzinger
@tobiasKaminsky

I want to implement that not enabled autouploads (custom and auto ones) are "hidden" in a list entry called [Click here for X inactive uploads] , is there any reason i should not do that?

**Comment by AndyScherzinger** [comment]
That needs some input from @nextcloud/designers and especially @jancborchardt in my opinion. I'd like to have the list shortened. Think you're proposed pattern would work nicely while hidding all inactive entries seems wrong to me. The reason why I implemented it the way has is right now and has been since the initial release is to make it very easy for non-tech-savvy users like my parents to have a simple way to backup their photos. So with that use case in mind hidding inactive one seems wrong since by default any newly detected folder is inactive. So I rather think that having some logic like "at least 2 images, else hidden" seems to be a smarter way while I can't say which other aspects a filter should have.

Again, even if this has been discarded I think it would help to have:
* a set of rules for which folders should be initially hidden
* a possibility that manually hide a folder via the 3dot menu
* a way to show these folders again, like proposed by @newhinton

So looking for more feedback since this is just my opinion :) Also @tobiasKaminsky

**Comment by newhinton** [comment]
@AndyScherzinger You are right regarding the problems

But:

If you agree with shortening it somehow, i can already start working on that, enabling shortening based on some condition we decide on could be made in the end :D

And regarding the default hidden stuff: let's say we show all if we only have 5 overall, if it gets more, we start hiding it then.

Are you fine with continuing this design-discussion in a pr where i start implementing this?

**Comment by AndyScherzinger** [comment]
Well, @jancborchardt and the others designers do have a veto right so there is a risk but since Jan already mentioned that we should come up with rules which folders should be auto hidden I think it is rather save to start while this is just my guess.

You could sent him an email while it is Friday evening so I wouldn't expect any answer before Monday or Tuesday.

**Comment by newhinton** [comment]
I will start with the base functionality only, so i guess there wont be a huge problem there :D And i don't want to ruin jan's weekend, so ill just start and see where it gets ^^

**Comment by jcklpe** [comment]
Just to chip in on the usability front, you could have it default to asking the user what their preferences was, which is similar to what Google Photos currently does.

**Comment by jancborchardt** [comment]
Sorry, was on vacation and I’m unfortunately busy with other stuff at the moment. :\ Is it possible to have a _simple_ specification for this that could be reviewed?

Ideally it could be just what @AndyScherzinger and I mentioned above in https://github.com/nextcloud/android/issues/3263#issuecomment-438158904 as a start?

**Comment by jcklpe** [comment]
Again, the problem with the "simple" exclude rules functionality is that is a separate feature from the one this ticket is about and fits better under https://github.com/nextcloud/android/issues/3239

This ticket is meant to be for the Level 2 issue which is the visual presentation of disabled connections, NOT the rules by which those automatic connections are made. 

Sorry, I don't know if I'm doing a really bad job communicating this, or if it's a language thing, or perhaps I'm just not really understanding but I feel like I'm talking in a circle. 

There are two problems, and two tickets and the spec you suggest is good but it's not what this ticket is about, it's a better fit under the other ticket which deals with the automatic adding behavior. 

# Auto connection folder filtering

This fits under https://github.com/nextcloud/android/issues/3239
Default to auto connection detection and creation, with the ability for users to go into the settings and turn off this default behavior (which then leaves only manually created folder connections being used)

This level 1 behavior could deal with the more complex exclusion rules that Jan mentions in his post, but I don't think the discussion of that issue is really needed in this ticket, it should really be in the other more relevant ticket.


# Visibility controls for ignored folders

This ticket here that we are in: https://github.com/nextcloud/android/issues/3263 is the one that about the visibility controls for ignored folders

Default behavior to automatically hiding all disabled folders, and putting a button at the bottom of the scroll that says something like [click to view 37 hidden disabled connections].

This is different than my original suggestion of making the hiding of these folders manual, since I realized... well pretty much the only folders you'd want to hide are the ones that are disabled and since there's already a toggle to disable the folders, there's no reason why it shouldn't also hide it either. That creates a baseline smart default auto behavior which covers 99% of usecases and doesn't add any additional UI toggles to the folder connections. (the only additional UI it adds is a "see more button" at the bottom which I don't think is going to make things difficult for users to grok)

If it's helpful I can make a mockup to explain in Sketch

**Comment by AndyScherzinger** [comment]
**Visibility controls for ignored folders** 
Way forward for this issue #3263 as described in https://github.com/nextcloud/android/issues/4331#issuecomment-522028215 and https://github.com/nextcloud/android/issues/4331#issuecomment-522098564, thus closing the other issues in favor of this one

> A hide feature would not delete the folders which we wouldn't do anyways (as in deleting them from storage) but like other tools with long auto dicovered list (items) I think it be good to have such a possibility (and then via the 3-dot menu do toggle the visibiliyt of hidden items, kind of like SeriesGuide is doing is and I am making heavy use of it as a SeriesGuide user).

> Then at the end of the list there could be an entry called "Show hidden folders" which toggle shows/hides them all.

* Auto connection folder filtering**
As nicely summerized by @jcklpe, to be done/discussed via #3239

**Comment by AndyScherzinger** [comment]
PR (work in progress) for show/hide of auto upload list entries can be found in #4784

**Comment by jcklpe** [comment]
Woo! Glad to hear :)

**Comment by AndyScherzinger** [comment]
> Woo! Glad to hear :)

So for expectation management, it is still "in progress". I am currently working on it but is is not yet ready to use/merge/dev-build or anything, but you can of course keep taps on this issue or the PR :) I plan to get this stable for the 3.10 (which is due end of year or beginning of next year), it will of course be in a dev build way earlier.
