### ISSUE TITLE
LDAP, AD authentification - locking users AD acounts after PW change

### ISSUE THREAD

**Issue by kokotko1337** [nextcloud/android#3265]
### Enviroment
Nextcloud using LDAP authentification
Win Domain - with policies:
- change PW every X months
- Password can not be the same
- after 6x wrong password, Active Directory account is locked - User can not login into domain - can not using PC, VPNS and other services because account is locked and must be manually unlocked in AD

### Actual behaviour
App is trying to log in with saved password, which leads to blocking users AD account.

### Expected behaviour
After not successful login with saved password, ask for password for this nextcloud account
 
### Steps to reproduce
1. login in APP to nextcloud with LDAP account 
2. Change PW - forced domain policy - change PW every X months
3. app using old PW til AD account is locked

### Environment data
Android version: every version

Device model: 
standard android phones like samsung etc

Stock or customized system:
all roms
Nextcloud app version:
latest
Nextcloud server version:
13.0.6

**Comment by MorrisJobke** [comment]
The plan was to make app tokens to persist. Thus the change of the LDAP password should not cause trouble. But there were some pending issues - cc @ChristophWurst. Beside that: I already talked with @tobiasKaminsky about this to minimize the initial parallel requests on a wake up to avoid that 5 parallel requests are fired and then cause the lockup without a chance of the android app to pause and ask for the new credentials. Unfortunately I don't know if this went into any code or not.

**Comment by kokotko1337** [comment]
@AndyScherzinger my users are using domain username and password - same as in AD, sorry i can not answer your question, I dont know backround of NC and authentification process

in NC I have only Ldap cfg with Ldap server, ldap read only account and some user groups.

**Comment by blizzz** [comment]
> The plan was to make app tokens to persist. Thus the change of the LDAP password should not cause trouble. But there were some pending issues - cc @ChristophWurst.

That's implemented in 15

> parallel requests on a wake up to avoid that 5 parallel requests are fired and then cause the lockup 

But that's not limited to this only. The more clients you have, the more different applications auth at LDAP (i.e. not just Nextcloud), the sooner you will run into a lockout. That's a disadvantage of the lock-out-by-so-and-so-many-attempts approach.

**Comment by tobiasKaminsky** [comment]
So is this solved? I am not that familiar with LDAP…

**Comment by kokotko1337** [comment]
@tobiasKaminsky it is not solved ... it is big issue in Organisations with AD Accounts

**Comment by rullzer** [comment]
There is nothing that android can do here. Android has no clue about eh backend of the app.

In NC15 it will be tried one and if the password is invalid it will be marked as such.

**Comment by rullzer** [comment]
@kokotko1337 it isn't authenticating against ldap. it is authenticating against nextcloud. Nextcloud then auhtenticates against ldap.

Sure the client might do some exponential backoff but that won't solve the problem. As I said. This is improved in NC15. So please update.

**Comment by patit72** [comment]
It doesn't seem to have improved in NC15. Same problem on every password change

**Comment by kokotko1337** [comment]
> It doesn't seem to have improved in NC15. Same problem on every password change

It it bad for Bussiness ... My solution is, that users are using Tokens for mobile devices ... it is annoying but it is not locking accounts out

**Comment by johnripper1** [comment]
Does these tokens expire? Tried tue same and it wasnt useful at all

**Comment by tobiasKaminsky** [comment]
@rullzer can we do something here?
