### ISSUE TITLE
Add SMS Backup & Phone call history record Backup

### ISSUE THREAD

**Issue by sulliwane** [nextcloud/android#3267]
### Is your feature request related to a problem? Please describe.
I love the contacts backup option. Could it be possible to allow "SMS backup" and "phone call history" backup ?

### Describe the solution you'd like
Same as this but for SMS & phone call history:
![screenshot_20181115-095426_nextcloud](https://user-images.githubusercontent.com/1733686/48541320-a6848b00-e8bc-11e8-8197-812166a3a284.png)

Thank you for your input on this !

**Comment by AndyScherzinger** [comment]
Hi @sulliwane,

this might require a lot more app permission that might look suspicious and also don't fit the "files focus". You can check out https://github.com/nerzhul/ownCloud-SMS-App (available via f-droid and Gplay) which does backups for SMS (while it'll need the corresponding Nextcloud server app installed).

@tobiasKaminsky what do you think?

@sulliwane looking at https://github.com/nerzhul/ownCloud-SMS-App it might be worth a try to request such a feauture for the phone-focused app.

**Comment by sulliwane** [comment]
To give a little more insight, it's part of my attempt to make phone restore/change smoother, ie: when I flash or change a phone, there are a few things that I'd love to resync just by installing owncloud, for example:

- wifi passwords
- contacts
- sms
- phone call history

But that's probably out of the scope of Nextcloud for Android (and probably more tricky than it seems, especially for sms). I'll have a look at owncloud-SMS-App then.

thank you for your answer !

**Comment by AndyScherzinger** [comment]
I'll close the issue for now then. Thanks for the feedback.
