### ISSUE TITLE
How do I change the "mipmap-anydpi-v26" icon?

### ISSUE THREAD

**Issue by dotrozn** [nextcloud/android#3268]
Hi!
So I was able to change every app-icon besides "mipmap-anydpi-v26" because it's in lc_launcher.xml.
How do I get it to my custom icon in there? every other PNG is already changed.

**Comment by AndyScherzinger** [comment]
Hi @dotrozn see either https://developer.android.com/studio/write/image-asset-studio#create-adaptive or remove the folder while you'll then loose the adaptive launcher icon part ;)
