### ISSUE TITLE
Android Talk after DNS change

### ISSUE THREAD

**Issue by tkintenn** [nextcloud/android#3269]
Opened Per Mario feedback via google play
### Actual behaviour
I copied my NC files and DB to a new VM (moved it from 1and1 hosting). Then upgraded from 13 to 14. Talk app would not login, just said "Redirecting" and logs shows an invalid login for my user. Web interface worked fine. The Nextcloud app worked just fine. 
The background was intentionally made different so i could tell when DNS switch had started working. Both Android NextCloud Talk and the Next Cloud app showed the new background image. 

### Expected behaviour
It would login. 
 
### Steps to reproduce
1. Move to a new IP for your NC instance
2. Try to login with Talk
3. Fail

### How I fixed it
Cleared the data and cache on the Talk App. It appeared (after watching network attempts via packet capture) that it had cached the IP of the URL. Once I cleared it's data, it correctly used the new IP.

Seems it should resolve the url to IP on each open.

### Environment data
Android version: 8

Device model: LG V20

Stock or customized system: Stock

Nextcloud app version: Talk 3.1.0beta4

Nextcloud server version: 14.0.3

**Comment by AndyScherzinger** [comment]
The right repo for this issue would be https://github.com/nextcloud/talk-android
Cc @mario
