### ISSUE TITLE
Domains and dynamic IP's

### ISSUE THREAD

**Issue by derbenx** [nextcloud/android#3274]
I just wanted to suggest a slight change to the PC client app or to make it an option. 

I use a website url to forward all calls to a dynamic IP, Example:
https://mydomain.com/NC/params?*
this server returns a 307 temporary redirect to the current dynamic IP like so:
https://123.123.123.123/NC/params?*

This works fine, except that the Next Cloud pc client remembers the dynamic IP url and not the domain that I entered on setup, so whenever the IP changes I have to delete and setup my user info again.
Can we have it remember the domain entered and not the resolved redirect? (or an option to do so would be awesome for the next app release!)

Thanks, love the program!

### Actual behaviour
- PC app remembers http://123.123.123.123/NC

### Expected behaviour
- it should remember http://myDomain.com/NC
 
### Steps to reproduce
1.  Setup a webserver that forwards all traffic via a 307 redirect to another url/ip. (or ask me to set one up)
2.  Setup a PC client to point to the URL
3. Client saves the redirect, not what was entered.

### Environment data

Nextcloud app version:  Version 2.3.3 (build 1)

Nextcloud server version:   Nextcloud 13.0.5 (updating now)

Server logs shouldn't be needed... you can see the client adding the url.

**Comment by AndyScherzinger** [comment]
Hi @derbenx, this is the Android client issue tracker, please open your issue in the desktop project: https://github.com/nextcloud/desktop/issues

Thanks :) ❤️
