### ISSUE TITLE
How to use davdroid for calender and task syncing

### ISSUE THREAD

**Issue by tanvir1414** [nextcloud/android#3275]
I log in via nextcloud and i want to see the davdroid contact and calender but no vain. In the settings, I get synchronized but i did not get the file in nextcloud server. I tried this link https://nextcloud.webo.hosting/remote.php/dav/ 
and get message that
"This is the WebDAV interface. It can only be accessed by WebDAV clients such as the Nextcloud desktop sync client."

Could you tell how to access the calender syncing or suggest a news software freely available.

**Comment by AndyScherzinger** [comment]
Hi @tanvir1414 as for DAVDroid please visit their forums: https://forums.bitfire.at/category/4/davdroid and for the Nextcloud News app, the freely available version is available via f-droid: https://f-droid.org/de/packages/de.luhmer.owncloudnewsreader/
