### ISSUE TITLE
Sync to server not working

### ISSUE THREAD

**Issue by jclgs** [nextcloud/android#3282]
Android NextCloud Version: 3.3.2
Server 14.0.2

Open Nextcloud Androit Client app.
Open an excel file
Select Microsoft Excel.
Modify the file.
Exit Excel.

The file is saved locally on the phone, but the Androit Nextcloud app is never syncing the file back to the NextCloud server.

The only way to get the file sync trigger, is to open the file again from the Android phone. When doing that, it looks that it trigger the syncing to the cloud server. After that, when I'm going on my file server, the file is up to date.

I know that I can select the option in the menu "Sync", but working on the cloud means that if I open a file and save it, I want it to be automatically save on the cloud server and not stay on my phone and need a manual sync to get uploaded to the server. If someone else has access to that file, it means that the file will stay on my phone and the other user accessing that file will never get the updated file until I open it again or do a manual sync.

On the Android Account, Nextcloud Syncing file is enabled, but is not doing anything.

**Comment by jclgs** [comment]
I saw most of them. I saw they were most related with the AutoUpload of picture. I don't know if it's the same sync in background, this is why I opened a new issue.

**Comment by AndyScherzinger** [comment]
@jclgs it is how it is supposed to work at the moment while we are working on changing this behavior so that any file downloaded will be kept in sync, see #2886 - this feature isn't ready yet so I guess this will then be something coming to the app in 2019.

**Comment by AndyScherzinger** [comment]
I'd close the issue (for now) since the matter is resolvedd (available offline) and a new behavior is in the making.
