### ISSUE TITLE
Can i disable old login method, including snackbar notification? :)

### ISSUE THREAD

**Issue by gstamosbg** [nextcloud/android#3284]
### Actual behaviour
- I cant disable old login method. I tried everything, but everytime when i tried to compile -> compiler is crashing without any error.

### Expected behaviour
- Just tell me, how to stop that. 💃 

### Environment data
Android version: 8.0.0

**Comment by AndyScherzinger** [comment]
hi @gstamosbg try to run a `clean`command via gradle before you compile.
