### ISSUE TITLE
Email changes doesn't reflect on app

### ISSUE THREAD

**Issue by nauxnim** [nextcloud/android#3285]
The left drawer menu only reflects the old email. Changed email should be reflected everywhere. Refreshing account doesn't help. Logging in and out will fix it, but it will need to resync everything and that will take up a really long time, which is troublesome and not worth doing just to see a change in email shown in the app.

**Comment by AndyScherzinger** [comment]
@nauxnim the left drawer mennu doesn't show an email. It shows `username`@`server-address` which might coincidently be the same thing like your email address, but that has nothing to do with what we show here, so nothing we can do here.

@tobiasKaminsky do you agree?

**Comment by tobiasKaminsky** [comment]
I agree with @AndyScherzinger, this is username @ server.

If you think this is somehow wrong, please give us a detailled way, with username, server, etc. (might be dummy values), so that we can understand the problem better.
