### ISSUE TITLE
Data Loss: Remotely deleting a Folder silently deletes unsynced local files

### ISSUE THREAD

**Issue by gohrner** [nextcloud/android#3288]
1) On the Android phone, I added a new subfolder in the NextCloud folder
2) I copied images there which were synced
3) Later, I added some additional images, which, for reasons unknown to me, were not synced. :-/ (The phone was connected to WiFi all the time and it only was a handful of pictures.)
4) Even later, on my Desktop computer which uses the NextCloud Linux Client, I moved the folder with the images somewhere else, out of NextCloud's reach.

Unfortunately, only then I noticed that after moving the folder, it did not contain the images I added in step 3.

As soon as I tried to open the folder on my Android device, it disappeared, and with it apparently the unsynced local images. Ouch!

Curiously, Google Fotos (which I only use because it came preinstalled as the only Gallery app, but I do *not* use its sync/online features) still shows the missing files, but in "information" it shows the now non-existent Nextcloud folder as the file location, and I cannot copy or share them in any way any more in the Fotos app. Apparently, Google Fotos uses a local cache which still contains the image file... Does anyone know any way to get them out there quickly before the are really deleted?

**Comment by tobiasKaminsky** [comment]
Hm, if you upload files and the upload did not worked, they are still in the original folder, e.g. your DCIM…
Removing a remote folder only removes downloaded files within the NC app folder.

Can you explain the problem with a demo file, e.g. 
- take picture A
- picture A is in /sdcard/DCIM/A.jpg
- try to upload picture to folder /F while offline -> thus failing
- remove folder /F

This is what I understand, but then in folder /F the picture A is not yet there, but still remains in /sdcard/DCIM/A.jpg, so removing /F should be no problem

**Comment by gohrner** [comment]
> Hm, if you upload files and the upload did not worked, they are still in the original folder, e.g. your DCIM…

I'm always using the "Move to Nextcloud folder" option as I do not want to have duplicate files on my phone.

This lead to the images which were not synced at the time I moved the folder away to be lost / deleted.

So the steps you describe are correct but the exception that the image is not in the DCIM folder any more.

**Comment by tobiasKaminsky** [comment]
> So the steps you describe are correct but the exception that the image is not in the DCIM folder any more.

This is really strange as the original file will only moved once the upload succeeded:
- manually upload a file with "move to Nextcloud folder"
- during upload cancel upload
- file is still in original folder
