### ISSUE TITLE
Backing up photos and contacts Malformed server configuration

### ISSUE THREAD

**Issue by H3is3nb3rgbr** [nextcloud/android#3289]
### Actual behaviour
- Tell us what happens
Get error when trying to backup contacts or photos to server

### Expected behaviour
- Tell us what should happen
Should upload from phone to NAS system at home
 
### Steps to reproduce
1. 
2. 
3. 

### Environment data
Android version:
9

Device model: 
Google Pixel 3XL

Stock or customized system:
Stock

Nextcloud app version:
3.3.2

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Thank you for your bug report, but we need a little more infos:
Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat
