### ISSUE TITLE
Sync: Mirror the latest version of files

### ISSUE THREAD

**Issue by skygate2012** [nextcloud/android#3290]
I'm trying to make NextCloud work with [Anki](https://apps.ankiweb.net/), which needs to exactly mirror the latest version of files between PC and Android. For example, when I made changes on the PC, the latest file changes locally will replace the server version, and on Android the latest file changes on the server will replace the older local file version. Is it possible to do this?

**Comment by AndyScherzinger** [comment]
@skygate2012 you can mark all the files as "keep available offline" within the Android app. This way thhe files should be kept in sync. Beware though that you can only mark files (not folders yet) so when you create new files they won't be kept in sync with the server.

**Comment by skygate2012** [comment]
> 
> 
> @skygate2012 you can mark all the files as "keep available offline" within the Android app. This way thhe files should be kept in sync. Beware though that you can only mark files (not folders yet) so when you create new files they won't be kept in sync with the server.

Thank you for answering. I guess I can only sync without media files. When will folders be able to be marked as sync by the way?

**Comment by tobiasKaminsky** [comment]
Closing as it is part of https://github.com/nextcloud/android/issues/285
