### ISSUE TITLE
In-app notification for shared content 

### ISSUE THREAD

**Issue by dusscloud** [nextcloud/android#3294]
Today, when sharing content, the receiver gets a dedicated email.
What about receiving an in-app notification if this user has the nexcloud app?
Then a setting on the user setting would ask what would be the notification : mail, app, both, or none.

**Comment by nickvergessen** [comment]
Its on the todo for @schiessle to do this for 16

We will make the local shares feel like the federated ones. So you get a (push) notification for them and can accept/decline from there

**Comment by AndyScherzinger** [comment]
@nickvergessen @schiessle would the server then trigger 2 notifications? (mail _and_ push notification)

**Comment by nickvergessen** [comment]
We are unsure yet if the mail option is being kept.

**Comment by AndyScherzinger** [comment]
Thanks for the input @nickvergessen 

@dusscloud we then need to postpone this issue until Nc16 is available and it might then well be, that the issue is obsolete completely.

**Comment by jancborchardt** [comment]
Yup, what @nickvergessen said. The important part is that especially not the person who shares should select how the _receivers_ get their notifications.

**Comment by developerfromjokela** [comment]
@nickvergessen  Best solution is to make some algorithm to detect have you received it on your device, or have you any devices with Nextcloud app. Maybe do request back to the server, and it will cancel sending email, and if there is no response in 10-15 minutes, it will send Email.

**Comment by jakobroehrl** [comment]
Hi @nickvergessen and @AndyScherzinger  
Are there any news on this topic since NC16 is out?
