### ISSUE TITLE
Nextcloud 14, davdroid 2.0.5-ose - appointment deletes not synced to mobile

### ISSUE THREAD

**Issue by kolcon** [nextcloud/android#3295]
### Actual behaviour
- When I sync my Nextcloud account to android, it syncs OK.
- When I delete an appointment on the server, it remains undeleted in mobile (all calendar apps)

### Expected behaviour
- Appointment should be deleted on mobile
 
### Steps to reproduce
1. Sync new Nextcloud account
2. Delete appointment
3. Appointment not deleted on mobile

### Environment data
Android version:
8.0.0

Device model: 
Samsung Galaxy S7

Stock or customized system:
Stock

Nextcloud app version:
davdroid 2.0.5-ose

Nextcloud server version:
14
#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
DAVDroid is a separate project: https://gitlab.com/bitfireAT/davdroid without an issue tracker but has a forum https://forums.bitfire.at/category/4/davdroid

Unfortunately not much the Nextcloud Andorid App can do about this :(

**Comment by kolcon** [comment]
Thanks, I report it there...

**Comment by kolcon** [comment]
Unless you want to include CalDav and CardDav into the Nextcloud android app ;)

**Comment by AndyScherzinger** [comment]
> Unless you want to include CalDav and CardDav into the Nextcloud android app ;)

No plans to do this :) DAVDroid is quite advanced when it comes to Cal/CardDAV 👍
