### ISSUE TITLE
Autoupload doesnt work at all...

### ISSUE THREAD

**Issue by RedondoBoony** [nextcloud/android#3296]
Android App 3.3.2, autoupload doesnt work at all (Galaxy S9+).
I can add it, but nothing happens. 
Turned off (only during charging/only Wlan) but no luck...
4.0.4 on server (Synology DS918+)

**Comment by voidzero** [comment]
Whatever the case maybe and whatever old ticket this is related to, the truth is that it is still not working.

You know, it would be ideal if there is a manual auto-upload button too, to make sure that whatever hasn't been uploaded, will still be uploaded, to the right subfolder (e.g. based on year and month). The other thing this would do is to move local images that have been uploaded to the specified fold.r (app folder for instance.)

Having to do this by hand gets a bit tedious, I think. And it really sucks that I only noticed it stopped working right now, with a ton of not properly uploaded images that I do need to take care of by hand now I guess.

**Comment by tobiasKaminsky** [comment]
On Samsung you have to exclude our app from battery optimization.
There are two settings as far as I remember.

**Comment by Hundsbuah** [comment]
Ich hab ein Note 9 und hab die App aus allen Battery Optimization Einstellungen raus genommen. Auto Upload funktioniert nur wenn ein neues Bild gemacht wird. Das wird sofort hochgeladen. Alle anderen, alten Bilder/Dateien werden nicht hochgeladen....

**Comment by AndyScherzinger** [comment]
@Hundsbuah this is expected, see #285 and is on the roadmap to be implemented.

**Comment by voidzero** [comment]
@tobiasKaminsky D'Oh! Why did I not think of this. Thank you, I think that this might have done the trick for me.

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger we should really include this somehow as a warning/dialog.
Do you have an idea when and how?

Show an dialog after enabling an auto upload folder? 
"Your device may have battery optimization. AutoUpload works only properly if you exclude this app from it." 

Do we want to limit this to Samsung right now?

**Comment by tobiasKaminsky** [comment]
I do not recall, but it could be.

**Comment by tobiasKaminsky** [comment]
PR in #3350

**Comment by metafarion** [comment]
Not sure about newer models, but the LG G4 running Android 6.0 has the battery optimization exception thing too.  Setting an exception for the Nextcloud app didn't appear to make Auto Upload functional, but I couldn't say whether or not it is necessary for Auto Upload to work.

**Comment by voidzero** [comment]
Ok, so as it seems, even with the batt optimization disabled, this stuff just does not work properly and I have to upload these ignored files by hand.

**Comment by peteman52** [comment]
can confirm, that autoupload doesn't work for Nexus 5 with Android 6.0.1 and Nextcloud client 3.4.1 and Nextcloud 14 .
However, just to tease you, autoupload works fine with said configuration and Owncloud client 2.7.0 .

**Comment by dmnk** [comment]
Galaxy Tab A (SM-T585) on Android 8.1.0, Security Patch: 01.11.2018
nextcloud (3.4.1) and nextcloud dev (20190117) manually excluded from battery saving.

If the productive one is running in split-screen, while the monitored files are changed; it detects the change and uploads the files. 
the dev doesn't even do that.

However, scanning for changes uploads all edited files. no matter which of the two versions or if they've been running during the manipulation / creation.

**Comment by tobiasKaminsky** [comment]
> Sync happened about 10 minutes after change.
> At least without external trigger, but giving users a hint what to expect and where to disable what, might help.

Glad that it works.
With next version you will see a battery optimization warning when enabling AutoUpload for the first time.
If supported by the Android version, you can then also directly disable it.

**Comment by dmnk** [comment]
already saw that one when starting the dev release the first time.

however, on samsung (and other "not so nice" manufacturer's android derivates) there might be more than one setting to change. And from UI/UX perspective, i'd somehow expect to be informed about a delay, if the sync isn't meant to start right after touching a file.

congrats on still not using the firebase job, even if it might seem that this would solve problems. it got it's own downsides ;)

**Comment by tobiasKaminsky** [comment]
Do you have an idea where this info about "not immediately upload" can be shown? Maybe in setting when configuring the individual folder?

**Comment by dmnk** [comment]
I guess that's where i'd put it, as i guess that most people checking their settings are there because it's not working or they'd like to change something. 

maybe allow different intervals for different folders?
then it wouldn't be a "notice text"-flying around, but a setting where i see that it's ~quarter-hourly / hourly. ... 

But the next one will demand high/low-duty schedules, ... so i guess a text is perfect for now 
;D

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky sure thing, hoping it won't be to much text since the dialog should still have the focus on the settings not on potential warnings/issues. :)

**Comment by InfamousUser** [comment]
I cannot get the auto upload to work. After days of being set up and not working and changing settings, somehow today it appeared in uploads menu, but it is apparently blocked by power saver mode. I have power saver mode active 24/7. App does not warn anywhere that it will not auto upload in power saver mode.

1. Please add notification about power saver mode.
2. Please add a setting to ignore power saver mode for auto uploads.
3. Please fix whatever is preventing the auto upload from working otherwise.
4. Please add a button to manually trigger the auto upload as a workaround for emergency situations.

**Comment by InfamousUser** [comment]
Still not working properly with 3.5.1, it seems to only autoupload the pictures I took since enabling autoupload or something like that.

**Comment by lemmy04** [comment]
same here: autoupload refuses to autoupload for unknown reasons

**Comment by voidzero** [comment]
It's working fine for me now

**Comment by bernd-wechner** [comment]
>     1. Please add notification about power saver mode.
>     2. Please add a setting to ignore power saver mode for auto uploads.
>     3. Please fix whatever is preventing the auto upload from working otherwise.
>     4. Please add a button to manually trigger the auto upload as a workaround for emergency situations.
>     5. Please add date and time of last successful auto upload.

A good list. As suggested elsewhere I would ad, that it's invaluable to see somewhere int he app:

1. An indicator of the status of the server connection (live or not)
2. On the AutoUpload page some indicator on the photo previews as to their status (uploaded, not uploaded) and a way to see a summary of status (tap the thumbnail and get a summary of status, uploaded, yes, or no, when was it uploaded, into which server folder ... last connection to server, reason it's not uploaded yet). A button to request upload now etc.

This kind of transparence would make diagnosing and working around these issues so much simpler.

**Comment by lemmy04** [comment]
Galaxy S8+, camera folder is on SD card, auto upload does NOT work.

I can easily reproduce:

1. turn off wifi
2. take picture
3. turn on wifi
4. picture from 2. does not get uploaded, and in the list of pending uploads the file is sitting "Waiting for WIFI" even though wifi is connected

5. turn the phone into FLIGHT MODE
6. turn off flight mde
7. file gets uploaded

**Comment by lemmy04** [comment]
still the same - see previous comment

**Comment by InfamousUser** [comment]
> > ```
> > 1. Please add notification about power saver mode.
> > 2. Please add a setting to ignore power saver mode for auto uploads.
> > 3. Please fix whatever is preventing the auto upload from working otherwise.
> > 4. Please add a button to manually trigger the auto upload as a workaround for emergency situations.
> > 5. Please add date and time of last successful auto upload.
> > ```
> 
> A good list. As suggested elsewhere I would ad, that it's invaluable to see somewhere int he app:
> 
> 1. An indicator of the status of the server connection (live or not)
> 2. On the AutoUpload page some indicator on the photo previews as to their status (uploaded, not uploaded) and a way to see a summary of status (tap the thumbnail and get a summary of status, uploaded, yes, or no, when was it uploaded, into which server folder ... last connection to server, reason it's not uploaded yet). A button to request upload now etc.
> 
> This kind of transparence would make diagnosing and working around these issues so much simpler.

Great additions!
Number 4 already says about the button - it would help immensely! Even if auto upload doesn't work, people could still make backups until they fix it, should be trivial to add!
So if they added status about all the items that are supposed to be auto uploaded, as you've said, that would be wonderful.

**Comment by lemmy04** [comment]
...anyone actually working on fixing this?

**Comment by adnoh** [comment]
This issue ist one of the biggest blocker for a Lot of people to Not use NC. Without a Client which can keep your Files in sync, it is Not really usefull. Has anyone the right amount of Java vodoo to fix this? I mean there ist plenty of Open source sync Software Out There working...maybe one who understands the Code can have a Look how to do it the proper way?

**Comment by tobiasKaminsky** [comment]
Is anyone still having this problem? And is willing to install an APK and can give me the logcat?
Then  we can try together to hunt this down…

**Comment by InfamousUser** [comment]
Personally I've had the issue because of power saving mode, it didn't want to upload in power saver mode and I didn't know about it because it didn't mention it anywhere in the app.

Nothing to do with the issue itself but adding a "force sync" button to trigger autoupload, and a date of last successful sync somewhere would be very helpful for troubleshooting these issues.
