### ISSUE TITLE
Feature Request: Add Wifi Only Options

### ISSUE THREAD

**Issue by c0fe** [nextcloud/android#33]
I like the ability to set a particular folder in which I would like Nextcloud to upload photos to, rather than trying to upload to all new folders it detects. But I would also like an option where it will only automatically upload the photos when the phone is in wireless network and doesn't use the data phone network.

Additionally to this I would like to request a feature in which you can have the photos automatically uploaded but not delete them from the server if I delete the photos from my phone.

**Comment by Spacefish** [comment]
Actually this is how it behaves currently. Just go to Preference and enable "Instant photo upload" aswell as "only upload via wifi".

**Comment by skewty** [comment]
Where is the "only upload via wifi" option?  I can't see it in settings.

**Comment by tobiasKaminsky** [comment]
Exactly, if you need some help please respond, meanwhile closing
