### ISSUE TITLE
Theming App Settings not applied to client

### ISSUE THREAD

**Issue by Torbe** [nextcloud/android#3300]
### Actual behaviour
- The Settings in the Server/ Theming App are not applied to the Android Client. 

### Expected behaviour
- Colors, Login Image etc. should be applied to the Client (with programmatically calculated adaptions) 
 
### Steps to reproduce
1. Have the exact same enviroment as I do
2. Do a clean Installation of Nextcloud Android Client
3. Colors are probably the default Blue on White

### Environment data
Android version: 9

Device model: OnePlus 6

Stock or customized system: Stock Oxygen OS (although Beta 7)

Nextcloud app version: 3.3.2

Nextcloud server version: 14 (tried on 15rc)

**Comment by tobiasKaminsky** [comment]
Please try to do a swipe to refresh on root folder, this will update capabilities of server. After a restart of the app, it should also be available for drawer.

If not, please can you create us a test account and send the credentials to tobias at nextcloud dot com with a reference to this issue?

**Comment by Torbe** [comment]
That worked! Thanks!
