### ISSUE TITLE
Update contribution.md

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#331]
- leftover of draft
- clarify wording

**Comment by djubreel** [comment]
@tobiasKaminsky  can you please shed more light on this?

**Comment by tobiasKaminsky** [comment]
It was https://github.com/nextcloud/android/pull/333 and already merged ;-)

**Comment by tobiasKaminsky** [comment]
If you want to help us, please have a look at other hacktoberfest labels.
If you need  some help, please do not hesitate and ping me.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky - @djubreel contributed the gradle checks for pmd, findbug etc. :wink:

**Comment by tobiasKaminsky** [comment]
Ah, great stuff. I was not aware that you are the same dev :+1:
