### ISSUE TITLE
direct editing files with Collabora (Collabora Server >=4.0) ?

### ISSUE THREAD

**Issue by gradinaruvasile** [nextcloud/android#3329]
Here:
https://github.com/nextcloud/android/releases/tag/rc-3.4.0-01
We have an item named:

`direct editing files with Collabora (Collabora Server >=4.0)`

So if we have a Collabora on-premise server integrated with Nextcloud we should be able to edit files directly in the Android app?
I have the stable branch Collabora server installed and configured (i think it is version 5.3?) but i don't see it working in the Android app.
Is this feature refer to something else (?) or it maybe requires NC 15?

**Comment by tobiasKaminsky** [comment]
The current stable collabora server is 3.5.3 and version 4.0 is expected to be available within the next week(s).

**Comment by gradinaruvasile** [comment]
Ah ok. Thanks. Will it work with NC 14.04?

**Comment by tobiasKaminsky** [comment]
It only depends the latest richDocuments app, but I am unsure if this is available on NC14, @rullzer?

**Comment by mr-bolle** [comment]
I try NC14 with richDocuments 3.0.6 with follow Collabora Server. 
I suppose that this works only since NC15 --> [Nextcloud Blog-Post](https://nextcloud.com/blog/nextcloud-15-goes-social-enforces-2fa-and-gives-you-a-new-generation-real-time-document-editing/) 

Collabora Online Development Edition (CODE)
LOOLWSD
4.0.0 (git hash: [3c3bc88](https://gerrit.libreoffice.org/plugins/gitiles/online/+log/3c3bc88))
LOKit
Collabora Office 6.0-18 (git hash: [e74e598](https://gerrit.libreoffice.org/plugins/gitiles/core/+log/e74e598))

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky can answer this but I also think it'll only work with Nc15+

**Comment by gradinaruvasile** [comment]
I upgraded to CODE 4.0 and nothing new happens on mobile. So is it a NC15 only thing?
BTW what is supposed to happen if i upgrade to NC15? It would suddenly change the way the mobile client opens office documents?

**Comment by AndyScherzinger** [comment]
> BTW what is supposed to happen if i upgrade to NC15? It would suddenly change the way the mobile client opens office documents?

Nope, it just adds another item to the menu of the file "Open with Collabora".

>  So is it a NC15 only thing?

Again, this is something @tobiasKaminsky should be able to answer

**Comment by Dynag** [comment]
Hi,
I updated nc to 15.0 and collabora to 4.0 but I cant edit document on my phone. Is that normal or I missed a new parameter ?

**Comment by tobiasKaminsky** [comment]
A new version of richdocuments app is needed, which will be released within the next days.

**Comment by gradinaruvasile** [comment]
I managed to get it work on NC 14.04. So it seems the requirements are:

NC 14.04 at least (i suppose?)
CODE (version 4.0) (i have it installed from the Debian repo)
Richdocuments 3.1.0
Android Client 3.4.1 RC2

Addirtional config in the web server:

nginx:
```
#Enable mobile editing feature
location ^~ /hosting/capabilities {
proxy_pass https://localhost:9980;
proxy_set_header Host $http_host;
}
```

apache:
```
ProxyPass           /hosting/capabilities https://127.0.0.1:9980/hosting/capabilities retry=0
ProxyPassReverse    /hosting/capabilities https://127.0.0.1:9980/hosting/capabilities
```

**Comment by tobiasKaminsky** [comment]
@rullzer do we have those additional config parts in our howto?

**Comment by Dynag** [comment]
I got the same problem, I updated all the instances and changes the apache config but it doesnt work anyway...

**Comment by KopfKrieg** [comment]
I just wanted to say the latest update of the Andorid App to version 3.4.1 solved the problem for me, I'm now able to edit files on my phone.
