### ISSUE TITLE
Path of search results

### ISSUE THREAD

**Issue by LukeOwlclaw** [nextcloud/android#3331]
### Is your feature request related to a problem? Please describe.
When using the search I see a list of found files. But I do not see in which folder these files are located. 

### Describe the solution you'd like
I'd like to see the (full) path of the file somewhere. Maybe in the details view.

### Describe alternatives you've considered
Next time I could search again. Or I could browse manually through the folders to find the file. No good options.

**Comment by tobiasKaminsky** [comment]
Thank you for your idea.
We discuss this NC wide in https://github.com/nextcloud/server/issues/12964

**Comment by e-magon** [comment]
There aren't any updates?

**Comment by joshtrichards** [comment]
Fixed long ago in #7568 and elsewhere.
