### ISSUE TITLE
Disable media player

### ISSUE THREAD

**Issue by LukeOwlclaw** [nextcloud/android#3332]
### Is your feature request related to a problem? Please describe.
I just tried the media player (after a long time) and was still sadly disappointed. It did not download the file (nor stream it), it just said Could not play the file using the builtin media player" --> https://github.com/nextcloud/android/issues/3061

So I download the file manually, then the media player played the file. I clicked "back" to browse through other nextcloud files. Then I wanted to stop the played (MP3) file: I click on the notifcation "Nextcloud Player" which brings me to the folder containing the file - not the player. So I cannot stop the played file directly.

So I click the file and stop it. Good. Then my screen switches off. When I switch it back on again the file starts playing again! Arghh!

### Describe the solution you'd like
Considering my experience together with the list of issues reported by other users and how long these troubles with the media player exist, I strongly vote for disabling for the integrated media player.

### Describe alternatives you've considered
Making the integrated media player nice to use. But that is a lot of work and is not necessary because there are good players.

### Additional context
I already suggested to get rid of the player 4 years ago --> https://github.com/owncloud/android/issues/776)
and the same reasoning still applies: This is a sync client, no a multi-purpose tool.

**Comment by tobiasKaminsky** [comment]
We are planning to enhance the media player. Some nice dev approached to us on CCC and wants to help us.
So the plan is to enhance this instead of removing it.

Maybe you can find some time to report issues individually, so that we can tackle them?
(Meanwhile I'll close this)
