### ISSUE TITLE
Add support for htpassword

### ISSUE THREAD

**Issue by Popolon** [nextcloud/android#3335]
### Is your feature request related to a problem? Please describe.
My NexxtCloud instance use htpassword for protection, the Android application has no function to add/enter those parameters and fail.

### Describe the solution you'd like
The ability detect a htpassword protection to enter login and password, and memorize it  (if user agree to keep it ?)

### Describe alternatives you've considered
Memorization of login only, not the password, as the htpassword  could be used to protect a full host, and not only NextCloud instance.

**Comment by tobiasKaminsky** [comment]
@nextcloud/server-triage do you have an idea how to handle this? Is this even supported by server?

**Comment by blizzz** [comment]
The Nextcloud server itself is not affected by this mechanism, it just sits on front, sort of as a doorkeeper. The clients would need to deal with it. I do not recall that this setup was ever brought up somewhere before.

**Comment by rullzer** [comment]
We actually recommend against it. Nextcloud itself uses basic auth as well and this conflicts.
Long story short this is not supported. You should just login to your Nextcloud.

**Comment by tobiasKaminsky** [comment]
Ok, if this is not supported nor recommended by server, it will not be included in clients.

**Comment by Popolon** [comment]
htpassword allow to limit security holes to mainly kernel/HTTPd/SSL library. Reduce attacks that could be linked to php interpreter/application/plugins potential issues.
