### ISSUE TITLE
Differenciate between "Downloading" and "Make available offline"

### ISSUE THREAD

**Issue by timmersr** [nextcloud/android#3341]
If I am correct, "Downloading" and "Make available offline" is exactly the same, just a different menu option;

I expect "Download" to put the document under **/sdcard/Download** by default ór to ask me where I want to store it.

And I expect "Make available offline" to keep a copy of the downloaded file to be kept in a not so very obvious location (like **/sdcard/Android/data/com.nextcloud.client/files/nextcloud/...**) to be kept in sync with the document on the server.

**Comment by tobiasKaminsky** [comment]
The old behaviour:
- download: only download once, do nothing morge
- keep available offline: periodic scan if file is out of date and update it

new behaviour will be:
all downloaded files will be updated, if
- on wifi
- no conflict occurs

> I expect "Download" to put the document under **/sdcard/Download** by default ór to ask me where I want to store it.

This is something that is not supported (yet) and should not be needed, as you can share any file to any app you want?

**Comment by timmersr** [comment]
> > I expect "Download" to put the document under **/sdcard/Download** by default ór to ask me where I want to store it.
> 
> This is something that is not supported (yet) and should not be needed, as you can share any file to any app you want?

That is true, but it is also (very) cumbersome to direct to another app to do a standard file download:

- You first need to select the file (as it is not an option in the three-dot menu of the file itself).
- Then go to the three-dot menu in the upperhand right corner to select Sharing.
- Then make a selection of an another app or behaviour option.

**Comment by AndyScherzinger** [comment]
> That is true, but it is also (very) cumbersome

Actually it is not:
* option 1: just click on the share icon in the file listing and choose your action
* option 2: if the app in use supports opening files via the Android document provider than you simply choose your Nextcloud storage, browse to your file and simply open it.

**Comment by timmersr** [comment]
Well, those were just my 2 cents. ;-) 
Hopefully you agree that having two menu options (Downloading and Make available offline) that are the same is not logical, and that Sharing as part of the _file_ three-dot menu would be more practical.

**Comment by AndyScherzinger** [comment]
> Well, those were just my 2 cents. ;-)

Yes, thanks for that. :)

> Hopefully you agree that having two menu options (Downloading and Make available offline) that are the same is not logical, 

Which will be changed since "make available offline" will vanish soon

> and that Sharing as part of the file three-dot menu would be more practical.

The sharing icon right next to the three-dot menu does that already so no reason to duplicate it into the menu (!)

**Comment by jedwabny** [comment]
Hi,

So, "make available offline" has gone in 3.5.0. Sure, the name was very unfortunate, but it worked like a dream! 

Now, again, it's needed all the time to synchronise manually before and after edit a file. It's again unhandy if persons works on the same simple txt file on android phones. Even on wifi the same. 

Just my humble question. Are there any plans to make auto upload (after edit in external app like quickedit) and auto download (of outdated file) , working reliably again or is it unwanted feature? 

Regarding and good day,
Mariusz.

**Comment by clawoflight** [comment]
Yes please, this should really be a core feature of the app!

**Comment by joshtrichards** [comment]
Closing since this is done as of #2886.

The rest of the bits here are covered in other Issues covering sync improvements and refinements.
