### ISSUE TITLE
Log in: "Unknown HTTP error occurred!"

### ISSUE THREAD

**Issue by haffs** [nextcloud/android#3345]
Connection to Nextcloud server (version 14.0.4.2), listening at the non-standard port 444 for https connections, fails. The app (version 3.32, Android 7) speaks plain http instead of https (Full request URI: http://xx.xxx.de:444/status.php). The server sends back a "400 Bad Request".

**Comment by tobiasKaminsky** [comment]
Normally it should also check for https, but maybe this is not done if it as non-standard port.
Can you try and enter manually https://xx.xxx.de:444 ?

**Comment by haffs** [comment]
For some reason, I can connect now with a different IP address/different route to the server. I've no idea what caused the error, in both cases I used IPv6 (a double-hop VPN connection). The problem persists with the first IPv6/route. It's inscrutable to me. May be there was a IPv6/IPv4 routing issue with the one route, but that's only an airy guess. - Because I can connect now, the issue can be closed, I think. Sorry for the buzz. Thank your for looking into the issue.
