### ISSUE TITLE
android app crashes when trying to sort a directory of photos to upload

### ISSUE THREAD

**Issue by koreywithak** [nextcloud/android#336]
### Actual behaviour

When trying to sort a folder of photos on my android device while in the upload screen of the nextcloud app, the app crashes.
### Expected behaviour

It should sort the folder without crashing
### Steps to reproduce
1. Click upload in app
2. Find the DCIM folder on phone to get to camera photos
3. Click sort in the app
### Environment data

Android version: 6.0.1

Device model: Nexus 6

Stock or customized system: stock

Nextcloud app version: 1.3.1

Nextcloud server version: 10.0.1

Don't have time to upload logs right now. Hopefully I can add later.
#### Web server error log

```
Insert your webserver log here
```
#### Nextcloud log (data/nextcloud.log)

```
Insert your Nextcloud log here
```

**Comment by AndyScherzinger** [comment]
Hi @koreywithak thank you for the report. No logs needed since I can reproduce this crash.

**Comment by koreywithak** [comment]
Okay great. Glad to help.

**Comment by AndyScherzinger** [comment]
corresponding PR #346

**Comment by AndyScherzinger** [comment]
Hi @koreywithak, the fix has been merged and will be shipped with the next release! :rocket:

**Comment by koreywithak** [comment]
Awesome. Pretty fast and organized resolution. Thanks!

**Comment by AndyScherzinger** [comment]
Thanks! I consider 27 days until merge quite long but that is due to the upcoming feature release and Hacktoberfest.
