### ISSUE TITLE
Automatic synchronization of modified file

### ISSUE THREAD

**Issue by jp-bennett** [nextcloud/android#337]
### Actual behaviour

After opening a text file in an external editor and making changes, the text file shows the changes only on the Android device.  The changes are not pushed to the nextcloud server until the file is manually synchronized.
### Expected behaviour

When a file is changed, it should automatically synchronize
### Steps to reproduce
1. create a text file in nextcloud from the browser
2. open the text file in the nextcloud app, open in editor, and make changes
3. Changes appear in the nextcloud app but not on the server
### Environment data

Android version:
6.0.1
Device model: 
NVidia Shield Tablet
Stock or customized system:
Cyanogenmod
Nextcloud app version:
1.3.1
Nextcloud server version:
10.0.1

**Comment by xHasKx** [comment]
@jp-bennett, behavior what you described is working when you set "offline access" for file.

**Comment by tobiasKaminsky** [comment]
Indeed this this already working when the file is set to "offline available".

**Comment by wangjiyang** [comment]
This issue still exists in Android 3.0 version.

**Comment by jfml** [comment]
Yeah, it doesn't seem to be working for me either. File opened in an external editor seems to be saved in /sdcard/attechment1 (attachment2, 3, 4 etc) and not in the original directory/textfile (and therefore the changes are not synct back to the server)
