### ISSUE TITLE
When uploading to external mount without write permissions, file can be deleted from local device under upload.

### ISSUE THREAD

**Issue by dali99** [nextcloud/android#3375]
### Actual behaviour
If you try to upload to a sftp external storage that you can't write to, the file shows up for a split second and is then removed.

If delete from device after upload is on, the file will also be removed from the phone.
### Expected behaviour
Upload should fail and not delete the file from the phone.
 
### Steps to reproduce
1. Add unwritable sftp external storage
2. Upload from phone app with "delete file from local device" turned on
3. Cry

This might be a nextcloud server thing rather than mobile, since the server probably should fail the upload. But never the less I was surprised that the phone doesn't verify the upload was correct before deleting data.

**Comment by MorrisJobke** [comment]
@dali99 Looks weird. Is it the same behavior like with read-only shared folders? This would then allow us to know if this is a permission or external storage issue.

**Comment by dali99** [comment]
I'm not sure how I would test read-only shared folders, since the app disallows me to upload to them / fails with "you are not permitted to upload to this folder"

Changing the permissions on the external storage did allow me to upload successfully for the record

**Comment by MorrisJobke** [comment]
Okay - then it seems to be a permission propagation issue. cc @rullzer @icewind1991

**Comment by tobiasKaminsky** [comment]
Like on other folder dav should give the client a proper info if a folder is writable. Then we can simply hide the upload button on it.

**Comment by rullzer** [comment]
Of course we do not always know. If the user doesn't have write permission on the external storage there is no reliable way for us to check that.

Of course the upload should also just fail then.

I'll see if I can reproduce this.
