### ISSUE TITLE
Galaxy S8 still not auto-uploading in power save 

### ISSUE THREAD

**Issue by fpernice518** [nextcloud/android#3376]
My galaxy S8 still does not auto-upload unless I completely disable power save mode. Mid-power save will not allow me to upload.

**Comment by peteman52** [comment]
I can confirm, that autoupload doesn't work for Nexus 5 with Android 6.0.1 and Nextcloud client 3.4.1 and Nextcloud 14 .
However, just to tease you, autoupload works fine with said configuration and Owncloud client 2.7.0 .

**Comment by peteman52** [comment]
Yes you can use the owncloud app with a nextcloud setup. At least till Owncloud client 2.7.0. Owncloud client 2.9.xxx doesn't work any more.
