### ISSUE TITLE
Add sort by size to upload 

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#338]
- Click upload in the app
- click sort: only name, date

There should be sortable by size as an user maybe wants to upload the biggest files first.

**Comment by Spacefish** [comment]
I would argue that users might want to upload the smallest files first, so the pictures get uploaded before there raw representation and the videos

**Comment by tobiasKaminsky** [comment]
Yeah, maybe ;-)
But the sorting options in the "normal" file view is also biggest -> smallest. Therefore I proposed it this way.

I know that we discussed if one can reverse the sorting order, back in the old days...
So for consistence I would leave this issue the way it is and open a new one regarding the sorting order.

**Comment by AndyScherzinger** [comment]
for PR see #346
