### ISSUE TITLE
Add the ability to force upload of autoupload-folder

### ISSUE THREAD

**Issue by newhinton** [nextcloud/android#3382]
Currently, if you add an existing folder to autosync, only new files are beeing uploaded. There should be an option to "force" an upload of the folder and all of its content.

Also this could be used to regularly backup your folder if this "forced" sync could be triggered via intent

**Comment by newhinton** [comment]
Seems to be related to #2812 and #285

**Comment by AndyScherzinger** [comment]
Yes, #285 is the roadmap issue and #2812 is the same as this issue.

**Comment by AndyScherzinger** [comment]
to be released with 3.11. via #4788
