### ISSUE TITLE
Button to toggle visibility of not synced autoupload-folders

### ISSUE THREAD

**Issue by newhinton** [nextcloud/android#3384]
Currently the app shows all found folders with images and videos. This can get quiet messy because some apps create many folders with single images in them. 

There could be a 3-Dot menu which has the option to toggle the visibility of non synced folders.

this could be expanded to toggle the visibility of only custom folders, and hide all auto-found folders

**Comment by AndyScherzinger** [comment]
thanks for the report @newhinton. This is a duplicate/extension to #3263, please follow up on this matter in that issue. There is an ongoing discussion on how to solve this matter which still hasn't come to a final conclusion on how this could be "fixed".

**Comment by newhinton** [comment]
ah thanks, will do that

**Comment by AndyScherzinger** [comment]
Thanks @newhinton :)
