### ISSUE TITLE
Show system protocols

### ISSUE THREAD

**Issue by bes1002t** [nextcloud/android#3385]
I had a crash few moments ago and I wanted to send feedback to the team. So the app asked whether I wanna append system protocols. Maybe yes, maybe not. I don't know, because I don't know the content of these protocols. I guess it's a stack trace.

So my feature request would be: please show the whole information which is sent to the team if an error occurrs.

**Comment by tobiasKaminsky** [comment]
Yes, this is something from OS / vendor specific. We do not have anything like that included. We only have in settings -> logs a way to display our application log.

@bes1002t Sometimes there is a button to send it to a specific email address, then you could mail it first to you.
