### ISSUE TITLE
File detail: show exact modification timestamp

### ISSUE THREAD

**Issue by memen45** [nextcloud/android#3389]
In the tab 'All Files' the full time stamps (of the form hh:mm(:ss) dd-mm-yyyy) are shortened to 'x days ago' or the date 'Nov 18' for example. This is all fine and makes the overview much more readable, however, this same shortened version is also shown in the file details activity. That makes it impossible to check the full date and time of a file or folder, which is very inconvenient. 
![screenshot_20181218-133132__01](https://user-images.githubusercontent.com/27782135/50154568-ff837c80-02c9-11e9-8400-fe2a16a80567.jpg)

**Comment by AndyScherzinger** [comment]
pinging @nextcloud/designers @jancborchardt @tobiasKaminsky for input on this

**Comment by AndyScherzinger** [comment]
@jancborchardt @nextcloud/designers the webUI has a hover pop-over which shows the exact timestamp (Nc15 at least does so) while this is a concept we don't have on mobile. So we could either make it clickable to toggle between relative and absolute date of show the date on click via a pop-up or whatever even better idea you folks might come up :)

**Comment by tobiasKaminsky** [comment]
Short click with a little pop up? But I am unsure which android component we can use.
Toggle on click would be the easiest way, I guess, but do we have enough space (in every language / date combination?)

**Comment by jancborchardt** [comment]
Long-press could show a toast with the full time? This seems like a sort-of Android standard, which is also used to show the tooltips of icons in the top bar.

**Comment by tobiasKaminsky** [comment]
> which is also used to show the tooltips of icons in the top bar.

This is a built-in feature, but this is not available for TextViews as far as I found.
So we can show a toast on long click, but this then would be on standard position (bottom centered)…

**Comment by AndyScherzinger** [comment]
> So we can show a toast on long click, but this then would be on standard position (bottom centered)…

would be fine with me

**Comment by tobiasKaminsky** [comment]
Like this…? I am unsure if
- people will ever click on the date
- people will recognize the toast down there

![2018-12-20-105944](https://user-images.githubusercontent.com/5836855/50278085-6168f100-0446-11e9-8a2d-5a1edcdeefdb.png)

**Comment by AndyScherzinger** [comment]
That would match the proposal of @jancborchardt 
Like I meantioned somewhere before we could also just toggle the date on click while that would be hard to discover from a user perspective too...

**Comment by jancborchardt** [comment]
Yeah, the toast is indeed very strange … the long-press is difficult to discover, and then it’s shown somewhere completely different.

The proposal with toggling the date display on tap seems much better! Sounds much more discoverable, and we could save the state globally (_not_ per file :D), so that people who prefer the absolute dates are covered. But the default should stay relative date.

**Comment by tobiasKaminsky** [comment]
> The proposal with toggling the date display on tap seems much better! Sounds much more discoverable,

How is this more discoverable? 
I also think it is better, but still no user will know that clicking on the date is changing anything…

**Comment by jancborchardt** [comment]
> So globally also means for the file listings, not just the detail views, right?

No, only for the detail view. Only the place which changes it.

> How is this more discoverable?
> I also think it is better, but still no user will know that clicking on the date is changing anything…

Yes, it is _more_ discoverable than long-press. Sure it’s still not obvious, but for the few people who require this, either they might try tapping or word will eventually get out. It’s not a crucial feature that _needs_ to be discovered.

**Comment by memen45** [comment]
Tapping would indeed be a workable solution. Some other suggestions:
1. Would it be possible to show both at the same time? Example: 
`3 days ago, Thursday 20 December 2018, 17:32:23`
2. Would it be possible to show information more detailed? Example:
`File size: 168 KB`
`Last Modified: Day dd Month yyyy, hh:mm:ss`
There should be more than enough space for this, as the rest of the activity is filled with the 'File Activities' tab.

Maybe the last suggestion addresses the File Detail view as a whole, not specifically the last modified date. In the 'All Files' tab, every item in the list already shows the size in short (e.g. `2.1 GB`) and the date in short (e.g. `3 days ago` or `Nov 18`):

![aantekening 2018-12-23 183957](https://user-images.githubusercontent.com/27782135/50386182-40243100-06e2-11e9-8e25-b699ecd91df6.jpg)

The File Detail view shows exactly this same short information, while I expect it to show more information than I already knew, e.g. `2.05 GB (2.210.334.237 bytes)` and long date/time:

![aantekening 2018-12-23 184202](https://user-images.githubusercontent.com/27782135/50386191-84afcc80-06e2-11e9-8fe4-93d9270f9779.jpg)

Maybe this should be in a new issue though?

**Comment by jancborchardt** [comment]
> There should be more than enough space for this, as the rest of the activity is filled with the 'File Activities' tab.

It’s not about how many space there is, but how much information density we want. As this detail screen is something that is often accessed for sharing and activities, we shouldn’t put too much in there.

Let’s go with tapping as a first simple way.

**Comment by AndyScherzinger** [comment]
#3399 resolves the date issue as discribed by @jancborchardt
