### ISSUE TITLE
Overview of all files currently set as offline

### ISSUE THREAD

**Issue by Whisprin** [nextcloud/android#3395]
### Is your feature request related to a problem? Please describe.
See bug #3394 
Users can't learn which files are currently set as offline and being synced in the background, when the last or next sync occurs

### Describe the solution you'd like
An overview of sync jobs and synced files set as offline, comparable to "uploads" in the navigation drawer
Last sync: synchronized files
Next sync: time stamp
Issues: E.g. the file has been removed from the server

### Describe alternatives you've considered
Look at the adb logs of the app during sync to figure out which files are set as offline

**Comment by AndyScherzinger** [comment]
cc @tobiasKaminsky for feedback

**Comment by joshtrichards** [comment]
Seems done to me. Closing.
