### ISSUE TITLE
Remove the overlay icon immediately after unset available as offline

### ISSUE THREAD

**Issue by Whisprin** [nextcloud/android#3396]
### Is your feature request related to a problem? Please describe.
When a file which is currently available offline gets "unset as available offline" the yellow overlay icon is still displayed.

### Describe the solution you'd like
Remove the yellow "set offline" overlay icon immediately after the users selects "unset as available offline" from the files context menu

### Describe alternatives you've considered
Leave the folder and reenter it in order to update the UI

![screenshot_20181219-122430_1](https://user-images.githubusercontent.com/3153136/50217973-a7607f00-038a-11e9-9e07-5c7015dbae69.png)
![screenshot_20181219-122421_1](https://user-images.githubusercontent.com/3153136/50217979-aaf40600-038a-11e9-9ac3-ee24e2ec9a2b.png)
![screenshot_20181219-122500_1](https://user-images.githubusercontent.com/3153136/50217982-af202380-038a-11e9-9a76-e2ad012e7083.png)

**Comment by AndyScherzinger** [comment]
Thanks for the detailed report @Whisprin ❤️ 

@tobiasKaminsky is this still an issue looking at the latest change for sync donwloaded for v3.5.0?

**Comment by AndyScherzinger** [comment]
@Whisprin you might want to give https://f-droid.org/de/packages/com.nextcloud.android.beta/ a try (is installed in parallel to the stable app) which introduces a completely new way of handling this (all files downloaded will be synced with the server when on a wifi connection).

**Comment by Whisprin** [comment]
Thanks. I just tried the current beta app

There the "set available as offline" command adds a yellow star icon (favourite) as an overlay.

Afterwards a "remove from favourite" command is available which does remove the overlay icon.

However, the file is not downloaded when set available offline is selected.

Is there a high level documentation available on how the new favourite/sync system works? Is it intended to merge offline and favorite files/folders?

**Comment by tobiasKaminsky** [comment]
@Whisprin 



> There the "set available as offline" command adds a yellow star icon (favourite) as an overlay.
> 
> Afterwards a "remove from favourite" command is available which does remove the overlay icon.

Can you retest this? For me both is named "favourites".



> However, the file is not downloaded when set available offline is selected.

In beta / upcoming release there is no "available offline".



> Is there a high level documentation available on how the new favourite/sync system works? 

Favorite files/folders are just sorted on top.
Sync: we now sync/update all downloaded files every 15min (or later due to doze) if your device is using wifi.

> Is it intended to merge offline and favorite files/folders?

No, they are two different concepts.

**Comment by Whisprin** [comment]
> > There the "set available as offline" command adds a yellow star icon (favourite) as an overlay.
> > Afterwards a "remove from favourite" command is available which does remove the overlay icon.
> 
> Can you retest this? For me both is named "favourites".

After updating to the latest dev release it's "add to/remove from favourites" 

> > Is there a high level documentation available on how the new favourite/sync system works?
> 
> Favorite files/folders are just sorted on top.
> Sync: we now sync/update all downloaded files every 15min (or later due to doze) if your device is using wifi.

That's interesting. Will have to test how this performs with many files / slow WiFi. 
Is there a way to manually select important files to keep synced without WiF on mobile network only? Is there a better place to talk about the new behaviour? 
 
> > Is it intended to merge offline and favorite files/folders?
> 
> No, they are two different concepts.

Thanks. It was my misunderstanding

**Comment by tobiasKaminsky** [comment]
> Is there a way to manually select important files to keep synced without WiF on mobile network only?

No, though I am unsure if this is really needed/wanted as it is another option, and it can highly consume data.

If a file needs to be updated, you can do it manually, but then it is user choice.

**Comment by joshtrichards** [comment]
No longer existing behavior / no longer a problem. Closing for that reason.
