### ISSUE TITLE
Use Account Language

### ISSUE THREAD

**Issue by reiner-text** [nextcloud/android#3397]
### Is your feature request related to a problem? Please describe.
I don't want to use the device language (German) with this app because of the translation.

### Describe the solution you'd like
Use the language of the connected Nextcloud (server) account with fallback to English if the translation isn't available in the app.

### Describe alternatives you've considered
Use a manual language selection.

**Comment by tobiasKaminsky** [comment]
On server we use the language which is set by the browser, so this is nearly the same as using system setting on android.
Having an option to manually set the language is cluttering up preferences. Honestly I do not know much apps where you can set a different language, e.g. on chrome you can only set the website language, but not the language for the app itself.

Using the server account language may also get confusing as I do not know which is the default language for new accounts?

@nextcloud/designers

**Comment by David-Development** [comment]
> I don't want to use the device language (German) with this app because of the translation.

Maybe it makes sense to investigate the cause of this issue rather than finding a workaround. @reiner-text You said "because of the translation". My phone language is english therefore I never tested the german translation on the files app. So my question is: What is wrong with the german translation? Maybe you can elaborate a little more on this? 
 
I guess it makes more sense to improve the german translation rather than adding a language switch option. @tobiasKaminsky Not sure if that is even possible?

**Comment by tobiasKaminsky** [comment]
Good point @David-Development!



> I guess it makes more sense to improve the german translation rather than adding a language switch option. @tobiasKaminsky Not sure if that is even possible?

Yes it is possible, but I doubt that it is that recommended to have it…

**Comment by reiner-text** [comment]
@David-Development The German translation could be better and/or shorter in some places. Unfortunately, I am currently unable to work on their improvement.

**Comment by jancborchardt** [comment]
@reiner-text if you find the time (or know people who could help) feel free to contribute to the translations at Transifex: https://www.transifex.com/nextcloud/nextcloud/android/ :slightly_smiling_face:

**Comment by tobiasKaminsky** [comment]
There is also https://help.nextcloud.com/t/die-deutsche-ubersetzung-von-nextcloud-hier-diskutieren-und-fehler-melden/32139

Maybe you do not have time to actively help, which is ok, but maybe you find a bit of time to post a screenshot and point out the problems…?
