### ISSUE TITLE
About "Expert mode"

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/android#3398]
Currently we have a switch in the settings called "Expert mode". Enabling it has no instant effect and there’s no description.

Do we have a list somewhere which lists what it does, and why we have it?

I was browsing the Signal repository the other day and came across their great [development ideology](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md#development-ideology) which is pretty similar to ours. A relevant excerpt:

> **3. There are no power users.** The idea that some users "understand" concepts better than others has proven to be, for the most part, false. If anything, "power users" are more dangerous than the rest, and we should avoid exposing dangerous functionality to them.

At Nextcloud we always aim to make everything properly usable, and ideally automatic. Most people do not switch settings. Anything we add to "expert mode" we would need to test and ensure it works, which is a not really justified amount of work for the small percentage of people who use these settings.

So let’s analyze what we have in expert mode, what we need it for, and how we could solve these things better. Ideally getting rid of "expert mode".

cc @nextcloud/android. Also recommended reading: [Choosing our preferences](https://ometer.com/preferences.html)

**Comment by newhinton** [comment]
On which premise do we want to have this discussion? Since this issue is quiet closely tied to #3263 and somewhat "depends" on a solution of this problem, do we want to discuss it as a whole? Or more like a general discussion which only covers the existing functionality behind "expert mode"?

**Comment by jancborchardt** [comment]
It’s a more general discussion, and we should see https://github.com/nextcloud/android/issues/3263 as separate.

**Comment by newhinton** [comment]
So the first step could be to replace the "expert toggle" with a "enable custom upload folder" toggle. It could be moved to the upload activity, which would further clean up the settings

But simply renaming the button would at least solve the problem in the regard that the user now knows what is meant when he enables the toggle

**Comment by AndyScherzinger** [comment]
@newhinton not quite ;) At the moment the toggle would also activate/deactive the menu in the Uploads list screen (not just the custom folder feature in the Auto upload screen). So in my opinion I think @tobiasKaminsky's and @jancborchardt's suggestion would work: simply remove the preference, put the custom folder feature into the 3-dot menue on the auto upload screen and just activate the menu on the upload screen (since we never implemented an auto-cleanup) or add 3 dot menues to the respective header within the uploads screen like suggested by Tobias.

**Comment by newhinton** [comment]
Ah yes you are right. But couldn't we just show them always?

**Comment by jancborchardt** [comment]
> simply remove the preference, put the custom folder feature into the 3-dot menue on the auto upload screen and just activate the menu on the upload screen (since we never implemented an auto-cleanup) or add 3 dot menues to the respective header within the uploads screen like suggested by Tobias.

Yes yes and yes! :sparkles: 

And then we can still decide which of these features make sense separately. But then at least they are in the place where they are relevant, and not only for people who dare pull a switch basically labeled "this probably breaks stuff". :wink:

**Comment by tobiasKaminsky** [comment]
Things to do / discuss:

swipe to refresh for force re-scan
trash bin icon on uploaded / failed row
retry button failed (or should this be done via swipe to refresh? )
