### ISSUE TITLE
Search feature for the Android App

### ISSUE THREAD

**Issue by supportreq** [nextcloud/android#34]
Adding a search option at the top of the file list..

Ref : https://github.com/owncloud/android/issues/695

**Comment by mar1u5** [comment]
cc @tobiasKaminsky @jancborchardt (because you participated in https://github.com/owncloud/android/issues/695)

**Comment by tobiasKaminsky** [comment]
Can someone summarize what the conclusion is?

**Comment by AndyScherzinger** [comment]
Especially with regards to filtering Vs. search and also if this is supposed to work within a folder (filtering) or throughout the complete file tree (rather a search)

**Comment by supportreq** [comment]
@AndyScherzinger but for the time being we can atleast have the filter part..

**Comment by AndyScherzinger** [comment]
@supportreq yes absolutely, not sure but I think @tobiasKaminsky might have started such an implementation a while ago. :)

**Comment by tobiasKaminsky** [comment]
Filter should be doable in a short time.
@jancborchardt is this ok for you?
Searching would then be after the search api is in /core?

**Comment by jancborchardt** [comment]
Yeah, just like in the web interface, it should be filtering the current view first. Search results from subfolders and other places can be shown later once we have it in core.

cc @LukasReschke regarding search API.

**Comment by tobiasKaminsky** [comment]
So, keeping this open and opened a new issue for filter: #60

**Comment by supportreq** [comment]
@tobiasKaminsky any update for this?? do we have an api.. it is very important feature..

**Comment by AndyScherzinger** [comment]
As far as I know we do not have an API yet.

cc @LukasReschke regarding search API.

**Comment by tobiasKaminsky** [comment]
For server tracking: https://github.com/nextcloud/server/issues/676

**Comment by tobiasKaminsky** [comment]
Closing in favour of #588
