### ISSUE TITLE
Choose sorting order

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#340]
Currently files can be sorted by 
- A -> Z
- Biggest -> Smallest
- Newest -> Oldest

This issue is about discussing if (and how) we can allow to change the sorting order.

Ideas:
- Add 3 options with reversed order: Z -> A 
  - ugly as hell -> NO
- Second click on same order reverts sorting order
  - not understandable/visible for user
- use fast scroll instead of reversing order
  - user can easily and fast scroll down 

Option 3 is maybe independent and should be implemented anyway (#47) 

@Spacefish

**Comment by AndyScherzinger** [comment]
This is how Amaze file manager is doing it:
![device-2016-10-17-115631](https://cloud.githubusercontent.com/assets/1315170/19433416/df5a6ad8-9460-11e6-9cf6-c4a4aba9c931.png)

**Comment by mario** [comment]
If it's not too much to ask, can you please leave the sort & filter functionality for April? I have a few issues I want to go through first, but I have a quite clear picture of how both sort and filtering should work. Thanks!

**Comment by AndyScherzinger** [comment]
Hi @mario, sure thing! :) Any reason for April (as in this exact month)?

**Comment by mario** [comment]
@AndyScherzinger there are quite a few NC Android tasks I have to do before I can revert to sort&filter that are of higher importance at this particular moment, and I don't know how long it'll take me to do all of them - if I do them earlier, sort & filter will come sooner as well, but in that case I'll let you know!

**Comment by AndyScherzinger** [comment]
Sounds good @mario! :) Beware though that any changes should be discussed first via a GH issue before implementation is started, just to make sure it will get improved and thus getting merged in the end and not declined ;)

**Comment by mario** [comment]
@AndyScherzinger certainly. You'll get wireframes and all that stuff.

**Comment by AndyScherzinger** [comment]
That sounds awesome! Happy to have you on board! 🎉

**Comment by ldmpub** [comment]
Hi,

In Nextcloud Android app, Alphabetical sort order (A - Z) does not work:
http://dl.free.fr/mSJbHjaLG

**Comment by AndyScherzinger** [comment]
@ldmpub which Version are you running, I just checked the latest master and it is working like a charm

@mario any objection for implementing the order ascending/descending issue before April?

**Comment by mario** [comment]
@AndyScherzinger absolutely none - let me know how you want it to look UI-wise and I can make it happen if you want.

**Comment by AndyScherzinger** [comment]
@mario I would have gone for the solution Amaze chose: https://github.com/nextcloud/android/issues/340#issuecomment-254164569

any comments/input @eppfel ?

**Comment by eppfel** [comment]
If it not hurts too much, that it might be redone with filter in aprils, go for it! Like it.

@ldmpub Looks very weird. Best would be to open a new issue with more specifics.

**Comment by AndyScherzinger** [comment]
Great, then let's go for it! This will add to the usability part :)

**Comment by AndyScherzinger** [comment]
@mario preference wise it might already be available but the UI part to set Ascending / descending is missing

**Comment by ldmpub** [comment]
> @ldmpub Looks very weird. Best would be to open a new issue with more specifics.

New issue opened, see #572.

**Comment by jancborchardt** [comment]
@Andyscherzinger in the original post up top and the discussions we decided to not do the ascend/descend since it's quite confusing and Z->A or Oldest->Newest doesn't really make sense, does it?

**Comment by tobiasKaminsky** [comment]
@jancborchardt what if you have 1000 files and want to see the oldest file? 
As we do not have a "fast scroll", with which you then could just scroll to bottom nearly immediately, we should support this.
It is only one more button in the sorting options ;-)

**Comment by eppfel** [comment]
The longer the list, the more relevant this use case gets. 
But now that I think about it, this adds a tap to the process. Is it possible to introduce ascending /descending as tabs, which changes the options. Therefore we add a tap only to switch and it would be easier to discover what does what.

**Comment by AndyScherzinger** [comment]
@eppfel what do you mean by a ascending, descending tab? And where? Wireframe?

**Comment by eppfel** [comment]
Very rough, but that should be understandable. Other options beside name should have small indications (Oldest -> Newest / Newest ->), too.

It was just an idea. I have no idea, if this is easy to implement...

![slice2](https://cloud.githubusercontent.com/assets/1899308/22182201/abd10466-e09f-11e6-89c6-95af2ae01c3b.png)

**Tap on descending:**

![slice1](https://cloud.githubusercontent.com/assets/1899308/22182200/abd0d4aa-e09f-11e6-993c-640a23c2305b.png)

**Comment by ldmpub** [comment]
Hi, 

I personally find tabs and terms Ascending / Descending very hard to use (double tap) and to understand (is date x ascending compared to date y?).

From my / end-user point of view a simple list is more effective:
- Last Modified - Older first
- Last Modified - Newer first
- Name - A -> Z
- Name - Z ->A
 - and so on...

**Comment by ldmpub** [comment]
An other solution is to create this kind of UI (extract from ES File Exporer), same as above but more rich because each 'list' entry has its own icon:
![sort suggestion for nexcloud android app](https://cloud.githubusercontent.com/assets/1452146/22182561/5ff57a46-e0a8-11e6-8be8-5511b9371863.png)

**Comment by eppfel** [comment]
Yeah, I would prefer icons as well. I think the idea was to introduce the capability with a small change. I could come up with a more detailed mock-up, but I don't if it is worth it at this point...

**Comment by AndyScherzinger** [comment]
Uuuuuh, I like @ldmpub's solution with icons :)
This would mean a custom pop up but isn't to hard to implement and the currently active could just be tinted NC blue when opened and a simply click on the icon would close the pop up and set the new order. I think that would still be doable in an okay amount of time and with the tinting would support theming out of the box whenever we start with that feature :)

**Comment by AndyScherzinger** [comment]
I can start to put up a prototype some time later today based on the icon idea :)

**Comment by eppfel** [comment]
I would still change the axis of @ldmpub's screenshot...

**Comment by eppfel** [comment]
Description left, two icons on the right. Doable?

**Comment by AndyScherzinger** [comment]
@eppfel absolutely :+1:

**Comment by AndyScherzinger** [comment]
For any further discussion, please see/go-to the corresponding PR #575

**Comment by AndyScherzinger** [comment]
#575 has been merged to master

**Comment by jancborchardt** [comment]
![](https://s-media-cache-ak0.pinimg.com/736x/d0/92/66/d092661e20d0ac2bce268941fdd2a28a.jpg)
