### ISSUE TITLE
Share file problem

### ISSUE THREAD

**Issue by bazio101** [nextcloud/android#3402]
Android 5.0.2
Nextcloud 3.4.0

After last update, when I try to share a file with another user, I get an "unknown error" message. This happens at the moment I type the name of the user at the search field on sharing tab. (one message for every letter I type). App seems not to be able to find users at server. Things are ok on 3.3.2 version. This is the log entry, hope it helps: 

12-22 15:46:56.385 V/ActivityThread(26327): Performing resume of ActivityRecord{25f1c2eb token=android.os.BinderProxy@3e15c848 {com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}}
12-22 15:46:56.398 I/ActivityManager(658): START u0 {act=ACTION_CHECK flg=0x20000 cmp=com.nextcloud.client/com.owncloud.android.ui.activity.PassCodeActivity} from uid 10096 on display 0
12-22 15:46:56.420 D/OwnCloudClient #2(26327): REQUEST GET /nextcloud/index.php/apps/files/api/v1/thumbnail/64/64/IMG_20181222_130516.jpg
12-22 15:46:56.468 D/OwnCloudClient #2(26327): REQUEST GET /nextcloud/ocs/v1.php/cloud/user
12-22 15:46:56.548 D/Avatar  (26327): URI: http://myserver/nextcloud/index.php/avatar/dimitris/192
12-22 15:46:56.556 D/OwnCloudClient #2(26327): REQUEST GET /nextcloud/index.php/avatar/dimitris/192
12-22 15:46:56.633 D/Posix   (26327): [Posix_connect Debug]Process com.nextcloud.client :80 
12-22 15:46:56.642 D/Posix   (26327): [Posix_connect Debug]Process com.nextcloud.client :80 
12-22 15:46:56.660 D/Posix   (26327): [Posix_connect Debug]Process com.nextcloud.client :80 
12-22 15:46:56.754 D/OwnCloudClient #2(26327): Location to redirect: https://myserver/nextcloud/ocs/v1.php/cloud/user?format=json
12-22 15:46:56.759 D/Posix   (26327): [Posix_connect Debug]Process com.nextcloud.client :443 
12-22 15:46:56.762 D/OwnCloudClient #2(26327): Location to redirect: https://myserver/nextcloud/index.php/apps/files/api/v1/thumbnail/64/64/IMG_20181222_130516.jpg
12-22 15:46:56.767 D/Posix   (26327): [Posix_connect Debug]Process com.nextcloud.client :443 
12-22 15:46:56.781 D/OwnCloudClient #2(26327): Location to redirect: https://myserver/nextcloud/index.php/avatar/dimitris/192
12-22 15:46:56.785 D/Posix   (26327): [Posix_connect Debug]Process com.nextcloud.client :443 
12-22 15:46:56.904 W/ActivityManager(658): Activity pause timeout for ActivityRecord{39803fe u0 com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity t1840}
12-22 15:46:57.111 D/ActivityThread(26327): ACT-AM_ON_RESUME_CALLED ActivityRecord{25f1c2eb token=android.os.BinderProxy@3e15c848 {com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}}
12-22 15:46:57.111 V/ActivityThread(26327): Resume ActivityRecord{25f1c2eb token=android.os.BinderProxy@3e15c848 {com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}} started activity: true, hideForNow: false, finished: false
12-22 15:46:57.112 V/ActivityThread(26327): Launch ActivityRecord{25f1c2eb token=android.os.BinderProxy@3e15c848 {com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}} mStartedActivity set
12-22 15:46:57.112 V/ActivityThread(26327): Scheduling idle handler for ActivityRecord{25f1c2eb token=android.os.BinderProxy@3e15c848 {com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}}
12-22 15:46:57.194 D/ActivityThread(26327): ACT-AM_ON_PAUSE_CALLED ActivityRecord{25f1c2eb token=android.os.BinderProxy@3e15c848 {com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}}
12-22 15:46:57.214 V/ActivityThread(26327): Handling launch of ActivityRecord{20cec233 token=android.os.BinderProxy@1da669f0 {com.nextcloud.client/com.owncloud.android.ui.activity.PassCodeActivity}}
12-22 15:46:57.215 V/ActivityThread(26327): ActivityRecord{20cec233 token=android.os.BinderProxy@1da669f0 {com.nextcloud.client/com.owncloud.android.ui.activity.PassCodeActivity}}: app=com.owncloud.android.MainApp@3168c330, appName=com.nextcloud.client, pkg=com.nextcloud.client, comp={com.nextcloud.client/com.owncloud.android.ui.activity.PassCodeActivity}, dir=/data/app/com.nextcloud.client-2/base.apk
12-22 15:46:57.266 V/ActivityThread(26327): Performing resume of ActivityRecord{20cec233 token=android.os.BinderProxy@1da669f0 {com.nextcloud.client/com.owncloud.android.ui.activity.PassCodeActivity}}
12-22 15:46:57.267 D/ActivityThread(26327): ACT-AM_ON_RESUME_CALLED ActivityRecord{20cec233 token=android.os.BinderProxy@1da669f0 {com.nextcloud.client/com.owncloud.android.ui.activity.PassCodeActivity}}
12-22 15:46:57.267 V/ActivityThread(26327): Resume ActivityRecord{20cec233 token=android.os.BinderProxy@1da669f0 {com.nextcloud.client/com.owncloud.android.ui.activity.PassCodeActivity}} started activity: false, hideForNow: false, finished: false
12-22 15:46:57.271 V/ActivityThread(26327): Resuming ActivityRecord{20cec233 token=android.os.BinderProxy@1da669f0 {com.nextcloud.client/com.owncloud.android.ui.activity.PassCodeActivity}} with isForward=true
12-22 15:46:57.271 V/PhoneWindow(26327): DecorView setVisiblity: visibility = 0 ,Parent =ViewRoot{ccadfb9 com.nextcloud.client/com.owncloud.android.ui.activity.PassCodeActivity,ident = 19}, this =com.android.internal.policy.impl.PhoneWindow$DecorView{da94e8f V.E..... R.....ID 0,0-0,0}
12-22 15:46:57.271 V/ActivityThread(26327): Scheduling idle handler for ActivityRecord{20cec233 token=android.os.BinderProxy@1da669f0 {com.nextcloud.client/com.owncloud.android.ui.activity.PassCodeActivity}}
12-22 15:46:57.272 D/ActivityThread(26327): ACT-LAUNCH_ACTIVITY handled : 0 / ActivityRecord{20cec233 token=android.os.BinderProxy@1da669f0 {com.nextcloud.client/com.owncloud.android.ui.activity.PassCodeActivity}}
12-22 15:46:57.323 D/BufferQueueDump(136): [com.nextcloud.client/com.owncloud.android.ui.activity.PassCodeActivity] parse str:[none]
12-22 15:46:57.323 D/BufferQueueDump(136): [com.nextcloud.client/com.owncloud.android.ui.activity.PassCodeActivity] parse substr:[none]
12-22 15:46:57.323 D/BufferQueueDump(136): [com.nextcloud.client/com.owncloud.android.ui.activity.PassCodeActivity] checkBackupCnt: str:[none]
12-22 15:46:57.323 D/BufferQueueDump(136): [com.nextcloud.client/com.owncloud.android.ui.activity.PassCodeActivity] matchName: str:[none] mName:com.nextcloud.client/com.owncloud.android.ui.activity.PassCodeActivity 
12-22 15:46:57.323 D/BufferQueueDump(136): [com.nextcloud.client/com.owncloud.android.ui.activity.PassCodeActivity] matchCName: 0
12-22 15:46:57.323 D/BufferQueueDump(136): [com.nextcloud.client/com.owncloud.android.ui.activity.PassCodeActivity] match result:0
12-22 15:46:57.323 D/BufferQueueDump(136): [com.nextcloud.client/com.owncloud.android.ui.activity.PassCodeActivity] parse substr:[none]
12-22 15:46:57.323 D/BufferQueueDump(136): [com.nextcloud.client/com.owncloud.android.ui.activity.PassCodeActivity] checkBackupCnt: str:[none]
12-22 15:46:57.326 V/WindowManager(658): Changing focus from null to Window{283aa5cb u0 com.nextcloud.client/com.owncloud.android.ui.activity.PassCodeActivity} Callers=com.android.server.wm.WindowManagerService.relayoutWindow:3571 com.android.server.wm.Session.relayout:197 android.view.IWindowSession$Stub.onTransact:237 com.android.server.wm.Session.onTransact:131 
12-22 15:46:57.323 D/BufferQueueDump(136): [com.nextcloud.client/com.owncloud.android.ui.activity.PassCodeActivity] matchName: str:[none] mName:com.nextcloud.client/com.owncloud.android.ui.activity.PassCodeActivity 
12-22 15:46:57.323 D/BufferQueueDump(136): [com.nextcloud.client/com.owncloud.android.ui.activity.PassCodeActivity] matchCName: 0
12-22 15:46:57.323 D/BufferQueueDump(136): [com.nextcloud.client/com.owncloud.android.ui.activity.PassCodeActivity] match result:0
12-22 15:46:57.323 D/BufferQueueDump(136): [com.nextcloud.client/com.owncloud.android.ui.activity.PassCodeActivity] parse * isMatched:0 backupCnt:0
12-22 15:46:57.323 I/BufferQueueConsumer(136): [com.nextcloud.client/com.owncloud.android.ui.activity.PassCodeActivity](this:0xb8a918a0,id:4709,api:0,p:-1,c:136) setConsumerName: com.nextcloud.client/com.owncloud.android.ui.activity.PassCodeActivity
12-22 15:46:57.323 I/BufferQueueConsumer(136): [com.nextcloud.client/com.owncloud.android.ui.activity.PassCodeActivity](this:0xb8a918a0,id:4709,api:0,p:-1,c:136) setDefaultBufferSize: width=540 height=960
12-22 15:46:57.335 I/BufferQueueProducer(136): [com.nextcloud.client/com.owncloud.android.ui.activity.PassCodeActivity](this:0xb8a918a0,id:4709,api:1,p:26327,c:136) connect(P): api=1 producer=(26327:com.nextcloud.client) producerControlledByApp=true
12-22 15:46:57.336 I/WindowManager(658): Gaining focus: Window{283aa5cb u0 com.nextcloud.client/com.owncloud.android.ui.activity.PassCodeActivity}
12-22 15:46:57.336 I/BufferQueueProducer(136): [com.nextcloud.client/com.owncloud.android.ui.activity.PassCodeActivity](this:0xb8a918a0,id:4709,api:1,p:26327,c:136) new GraphicBuffer needed
12-22 15:46:57.338 D/BufferQueueProducer(136): [com.nextcloud.client/com.owncloud.android.ui.activity.PassCodeActivity](this:0xb8a918a0,id:4709,api:1,p:26327,c:136) cancelBuffer: slot 0
12-22 15:46:57.338 I/BufferQueueProducer(136): [com.nextcloud.client/com.owncloud.android.ui.activity.PassCodeActivity](this:0xb8a918a0,id:4709,api:1,p:26327,c:136) setBufferCount: count = 4
12-22 15:46:57.339 I/BufferQueueConsumer(136): [com.nextcloud.client/com.owncloud.android.ui.activity.PassCodeActivity](this:0xb8a918a0,id:4709,api:1,p:26327,c:136) getReleasedBuffers: returning mask 0xffffffffffffffff
12-22 15:46:57.340 I/BufferQueueProducer(136): [com.nextcloud.client/com.owncloud.android.ui.activity.PassCodeActivity](this:0xb8a918a0,id:4709,api:1,p:26327,c:136) new GraphicBuffer needed
12-22 15:46:57.386 I/ActivityManager(658): [AppLaunch] Displayed Displayed com.nextcloud.client/com.owncloud.android.ui.activity.PassCodeActivity: +481ms
12-22 15:46:57.386 D/ActivityManager(658): AP_PROF:AppLaunch_LaunchTime:com.nextcloud.client/com.owncloud.android.ui.activity.PassCodeActivity:481:105610296
12-22 15:46:58.133 D/ActivityManager(658): ACT-IDLE_NOW_MSG from windowsVisible() for idle: ActivityRecord{344531b6 u0 com.nextcloud.client/com.owncloud.android.ui.activity.PassCodeActivity t1840}
12-22 15:46:58.195 V/ActivityThread(26327): Finishing stop of ActivityRecord{25f1c2eb token=android.os.BinderProxy@3e15c848 {com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}}: show=false win=com.android.internal.policy.impl.PhoneWindow@1ef78938
12-22 15:46:58.382 I/BufferQueueProducer(136): [com.nextcloud.client/com.owncloud.android.ui.activity.PassCodeActivity](this:0xb8a918a0,id:4709,api:1,p:26327,c:136) queueBuffer: fps=2.94 dur=1019.83 max=726.02 min=72.68
12-22 15:46:59.726 D/ActivityThread(26327): ACT-AM_ON_PAUSE_CALLED ActivityRecord{20cec233 token=android.os.BinderProxy@1da669f0 {com.nextcloud.client/com.owncloud.android.ui.activity.PassCodeActivity}}
12-22 15:46:59.730 I/BufferQueueProducer(136): [com.nextcloud.client/com.owncloud.android.ui.activity.PassCodeActivity](this:0xb8a918a0,id:4709,api:1,p:26327,c:136) queueBuffer: fps=2.97 dur=1347.51 max=458.94 min=165.23
12-22 15:46:59.738 V/ActivityThread(26327): Performing resume of ActivityRecord{25f1c2eb token=android.os.BinderProxy@3e15c848 {com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}}
12-22 15:46:59.801 D/OwnCloudClient #2(26327): REQUEST GET /nextcloud/index.php/apps/files/api/v1/thumbnail/64/64/IMG_20181222_130516.jpg
12-22 15:46:59.802 V/WindowManager(658): Changing focus from Window{283aa5cb u0 com.nextcloud.client/com.owncloud.android.ui.activity.PassCodeActivity} to null Callers=com.android.server.wm.WindowManagerService.relayoutWindow:3571 com.android.server.wm.Session.relayout:197 android.view.IWindowSession$Stub.onTransact:237 com.android.server.wm.Session.onTransact:131 
12-22 15:46:59.812 D/OwnCloudClient #2(26327): REQUEST GET /nextcloud/ocs/v1.php/cloud/user
12-22 15:46:59.814 I/WindowManager(658): Losing focus: Window{283aa5cb u0 com.nextcloud.client/com.owncloud.android.ui.activity.PassCodeActivity}
12-22 15:46:59.890 D/OwnCloudClient #2(26327): Location to redirect: https://myserver/nextcloud/ocs/v1.php/cloud/user?format=json
12-22 15:46:59.898 D/OwnCloudClient #2(26327): Location to redirect: https://myserver/nextcloud/index.php/apps/files/api/v1/thumbnail/64/64/IMG_20181222_130516.jpg
12-22 15:47:00.419 D/ActivityThread(26327): ACT-AM_ON_RESUME_CALLED ActivityRecord{25f1c2eb token=android.os.BinderProxy@3e15c848 {com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}}
12-22 15:47:00.419 V/ActivityThread(26327): Resume ActivityRecord{25f1c2eb token=android.os.BinderProxy@3e15c848 {com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}} started activity: false, hideForNow: false, finished: false
12-22 15:47:00.419 V/ActivityThread(26327): Resuming ActivityRecord{25f1c2eb token=android.os.BinderProxy@3e15c848 {com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}} with isForward=false
12-22 15:47:00.420 V/PhoneWindow(26327): DecorView setVisiblity: visibility = 0 ,Parent =ViewRoot{291c8dac com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity,ident = 1}, this =com.android.internal.policy.impl.PhoneWindow$DecorView{13ed3cdb V.E..... R.....ID 0,0-540,960}
12-22 15:47:00.420 V/ActivityThread(26327): Scheduling idle handler for ActivityRecord{25f1c2eb token=android.os.BinderProxy@3e15c848 {com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}}
12-22 15:47:00.465 D/BufferQueueDump(136): [com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity] parse str:[none]
12-22 15:47:00.465 D/BufferQueueDump(136): [com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity] parse substr:[none]
12-22 15:47:00.465 D/BufferQueueDump(136): [com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity] checkBackupCnt: str:[none]
12-22 15:47:00.465 D/BufferQueueDump(136): [com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity] matchName: str:[none] mName:com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity 
12-22 15:47:00.466 V/WindowManager(658): Changing focus from null to Window{1893d42a u0 com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity} Callers=com.android.server.wm.WindowManagerService.relayoutWindow:3571 com.android.server.wm.Session.relayout:197 android.view.IWindowSession$Stub.onTransact:237 com.android.server.wm.Session.onTransact:131 
12-22 15:47:00.465 D/BufferQueueDump(136): [com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity] matchCName: 0
12-22 15:47:00.465 D/BufferQueueDump(136): [com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity] match result:0
12-22 15:47:00.465 D/BufferQueueDump(136): [com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity] parse substr:[none]
12-22 15:47:00.465 D/BufferQueueDump(136): [com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity] checkBackupCnt: str:[none]
12-22 15:47:00.465 D/BufferQueueDump(136): [com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity] matchName: str:[none] mName:com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity 
12-22 15:47:00.465 D/BufferQueueDump(136): [com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity] matchCName: 0
12-22 15:47:00.465 D/BufferQueueDump(136): [com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity] match result:0
12-22 15:47:00.465 D/BufferQueueDump(136): [com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity] parse * isMatched:0 backupCnt:0
12-22 15:47:00.465 I/BufferQueueConsumer(136): [com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity](this:0xb8a98c48,id:4711,api:0,p:-1,c:136) setConsumerName: com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity
12-22 15:47:00.465 I/BufferQueueConsumer(136): [com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity](this:0xb8a98c48,id:4711,api:0,p:-1,c:136) setDefaultBufferSize: width=540 height=960
12-22 15:47:00.471 I/WindowManager(658): Gaining focus: Window{1893d42a u0 com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}
12-22 15:47:00.472 I/BufferQueueProducer(136): [com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity](this:0xb8a98c48,id:4711,api:1,p:26327,c:136) connect(P): api=1 producer=(26327:com.nextcloud.client) producerControlledByApp=true
12-22 15:47:00.473 I/BufferQueueProducer(136): [com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity](this:0xb8a98c48,id:4711,api:1,p:26327,c:136) new GraphicBuffer needed
12-22 15:47:00.474 D/BufferQueueProducer(136): [com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity](this:0xb8a98c48,id:4711,api:1,p:26327,c:136) cancelBuffer: slot 0
12-22 15:47:00.475 I/BufferQueueProducer(136): [com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity](this:0xb8a98c48,id:4711,api:1,p:26327,c:136) setBufferCount: count = 4
12-22 15:47:00.475 I/BufferQueueConsumer(136): [com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity](this:0xb8a98c48,id:4711,api:1,p:26327,c:136) getReleasedBuffers: returning mask 0xffffffffffffffff
12-22 15:47:00.477 I/BufferQueueProducer(136): [com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity](this:0xb8a98c48,id:4711,api:1,p:26327,c:136) new GraphicBuffer needed
12-22 15:47:00.648 I/BufferQueueProducer(136): [com.nextcloud.client/com.owncloud.android.ui.activity.PassCodeActivity](this:0xb8a918a0,id:4709,api:1,p:-1,c:136) disconnect(P): api 1
12-22 15:47:00.648 I/BufferQueueConsumer(136): [com.nextcloud.client/com.owncloud.android.ui.activity.PassCodeActivity](this:0xb8a918a0,id:4709,api:1,p:-1,c:136) getReleasedBuffers: returning mask 0xffffffffffffffff
12-22 15:47:00.924 D/ActivityManager(658): ACT-IDLE_NOW_MSG from windowsVisible() for idle: ActivityRecord{39803fe u0 com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity t1840}
12-22 15:47:00.936 I/BufferQueueConsumer(136): [com.nextcloud.client/com.owncloud.android.ui.activity.PassCodeActivity](this:0xb8a918a0,id:4709,api:1,p:-1,c:-1) disconnect(C)
12-22 15:47:00.936 I/BufferQueue(136): [com.nextcloud.client/com.owncloud.android.ui.activity.PassCodeActivity](this:0xb8a918a0,id:4709,api:1,p:-1,c:-1) ~BufferQueueCore
12-22 15:47:01.683 I/BufferQueueProducer(136): [com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity](this:0xb8a98c48,id:4711,api:1,p:26327,c:136) queueBuffer: fps=3.79 dur=1056.32 max=511.17 min=42.00
12-22 15:47:02.539 D/OwnCloudClient #2(26327): REQUEST GET /nextcloud/ocs/v2.php/apps/files_sharing/api/v1/sharees
12-22 15:47:02.621 D/OwnCloudClient #2(26327): Location to redirect: https://myserver/nextcloud/ocs/v2.php/apps/files_sharing/api/v1/sharees?format=json&itemType=file&search=%20vass&page=1&perPage=50
12-22 15:47:02.869 I/BufferQueueProducer(136): [com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity](this:0xb8a98c48,id:4711,api:1,p:26327,c:136) queueBuffer: fps=16.01 dur=1186.56 max=498.85 min=14.66
12-22 15:47:03.827 D/OwnCloudClient #2(26327): REQUEST GET /nextcloud/ocs/v2.php/apps/files_sharing/api/v1/sharees
12-22 15:47:03.828 I/NotificationService(658): enqueueToast pkg=com.nextcloud.client callback=android.app.ITransientNotification$Stub$Proxy@2b7b66e4 duration=0
12-22 15:47:03.829 D/NotificationService(658): Show pkg=com.nextcloud.client callback=android.app.ITransientNotification$Stub$Proxy@2b7b66e4
12-22 15:47:03.872 I/BufferQueueProducer(136): [Toast](this:0xb8a918a0,id:4718,api:1,p:26327,c:136) connect(P): api=1 producer=(26327:com.nextcloud.client) producerControlledByApp=true
12-22 15:47:03.903 D/OwnCloudClient #2(26327): Location to redirect: https://myserver/nextcloud/ocs/v2.php/apps/files_sharing/api/v1/sharees?format=json&itemType=file&search=%20&page=1&perPage=50
12-22 15:47:04.113 I/BufferQueueProducer(136): [com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity](this:0xb8a98c48,id:4711,api:1,p:26327,c:136) queueBuffer: fps=3.22 dur=1243.86 max=511.71 min=213.63
12-22 15:47:05.437 I/BufferQueueProducer(136): [com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity](this:0xb8a98c48,id:4711,api:1,p:26327,c:136) queueBuffer: fps=3.02 dur=1323.41 max=496.35 min=89.38
12-22 15:47:05.830 D/NotificationService(658): Timeout pkg=com.nextcloud.client callback=android.app.ITransientNotification$Stub$Proxy@2b7b66e4
12-22 15:47:06.865 I/BufferQueueProducer(136): [com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity](this:0xb8a98c48,id:4711,api:1,p:26327,c:136) queueBuffer: fps=3.50 dur=1428.84 max=499.02 min=115.08
12-22 15:47:07.055 I/NotificationService(658): enqueueToast pkg=com.nextcloud.client callback=android.app.ITransientNotification$Stub$Proxy@1fe6cdbd duration=0
12-22 15:47:07.057 D/NotificationService(658): Show pkg=com.nextcloud.client callback=android.app.ITransientNotification$Stub$Proxy@1fe6cdbd
12-22 15:47:07.064 D/OwnCloudClient #2(26327): REQUEST GET /nextcloud/ocs/v2.php/apps/files_sharing/api/v1/sharees
12-22 15:47:07.119 I/BufferQueueProducer(136): [Toast](this:0xb8a918a0,id:4724,api:1,p:26327,c:136) connect(P): api=1 producer=(26327:com.nextcloud.client) producerControlledByApp=true
12-22 15:47:07.166 D/OwnCloudClient #2(26327): Location to redirect: https://myserver/nextcloud/ocs/v2.php/apps/files_sharing/api/v1/sharees?format=json&itemType=file&search=%20vasso&page=1&perPage=50
12-22 15:47:07.722 D/SystemServicesProxy(787): getRecentTasks:TASK = Task.Key: 1840, u: 0, lat: 1545486419727, com.nextcloud.client/isExcluded = false/isTopTaskHome = false/isFirstValidTask = true
12-22 15:47:07.727 D/SystemServicesProxy(787): getRecentTasks:TASK = Task.Key: 1840, u: 0, lat: 1545486419727, com.nextcloud.client/isExcluded = false/isTopTaskHome = false/isFirstValidTask = true
12-22 15:47:07.730 D/RecentsTaskLoader(787): getTaskStack:Task = Task.Key: 1840, u: 0, lat: 1545486419727, com.nextcloud.client
12-22 15:47:07.736 W/PackageManager(787): Failure retrieving resources for com.nextcloud.client: Resource ID #0x0
12-22 15:47:07.768 V/WindowManager(658): Changing focus from Window{1893d42a u0 com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity} to null Callers=com.android.server.wm.WindowManagerService.setFocusedApp:4424 com.android.server.am.ActivityManagerService.setFocusedActivityLocked:2741 com.android.server.am.ActivityStack.completeResumeLocked:1158 com.android.server.am.ActivityStack.resumeTopActivityInnerLocked:2100 
12-22 15:47:07.768 I/WindowManager(658): Losing focus: Window{1893d42a u0 com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}
12-22 15:47:07.787 D/ActivityThread(26327): ACT-AM_ON_PAUSE_CALLED ActivityRecord{25f1c2eb token=android.os.BinderProxy@3e15c848 {com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}}
12-22 15:47:07.794 D/SystemServicesProxy(787): getRecentTasks:TASK = Task.Key: 1840, u: 0, lat: 1545486427745, com.nextcloud.client/isExcluded = false/isTopTaskHome = false/isFirstValidTask = true
12-22 15:47:07.794 D/RecentsTaskLoader(787): getTaskStack:Task = Task.Key: 1840, u: 0, lat: 1545486427745, com.nextcloud.client
12-22 15:47:07.802 W/PackageManager(787): Failure retrieving resources for com.nextcloud.client: Resource ID #0x0
12-22 15:47:08.092 V/ActivityThread(26327): Finishing stop of ActivityRecord{25f1c2eb token=android.os.BinderProxy@3e15c848 {com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}}: show=false win=com.android.internal.policy.impl.PhoneWindow@1ef78938
12-22 15:47:08.093 V/PhoneWindow(26327): DecorView setVisiblity: visibility = 4 ,Parent =ViewRoot{291c8dac com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity,ident = 1}, this =com.android.internal.policy.impl.PhoneWindow$DecorView{13ed3cdb I.E..... R.....ID 0,0-540,960}
12-22 15:47:08.177 I/BufferQueueProducer(136): [com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity](this:0xb8a98c48,id:4711,api:1,p:-1,c:136) disconnect(P): api 1
12-22 15:47:08.177 I/BufferQueueConsumer(136): [com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity](this:0xb8a98c48,id:4711,api:1,p:-1,c:136) getReleasedBuffers: returning mask 0xffffffffffffffff
12-22 15:47:08.287 I/BufferQueueConsumer(136): [com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity](this:0xb8a98c48,id:4711,api:1,p:-1,c:-1) disconnect(C)
12-22 15:47:08.289 I/BufferQueue(136): [com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity](this:0xb8a98c48,id:4711,api:1,p:-1,c:-1) ~BufferQueueCore
12-22 15:47:08.546 I/NotificationService(658): enqueueToast pkg=com.nextcloud.client callback=android.app.ITransientNotification$Stub$Proxy@3a5c2744 duration=0
12-22 15:47:09.059 D/NotificationService(658): Timeout pkg=com.nextcloud.client callback=android.app.ITransientNotification$Stub$Proxy@1fe6cdbd
12-22 15:47:09.061 D/NotificationService(658): Show pkg=com.nextcloud.client callback=android.app.ITransientNotification$Stub$Proxy@3a5c2744
12-22 15:47:09.119 I/BufferQueueProducer(136): [Toast](this:0xb8a98c48,id:4727,api:1,p:26327,c:136) connect(P): api=1 producer=(26327:com.nextcloud.client) producerControlledByApp=true
12-22 15:47:11.063 D/NotificationService(658): Timeout pkg=com.nextcloud.client callback=android.app.ITransientNotification$Stub$Proxy@3a5c2744

**Comment by alvVDC1846** [comment]
I get the same error with Android APP 3.4.1, NextCloud Server 13.0.6 and Android 7.0.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky did we change anything in the library with 3.4.0 release? I tried latest master with my Nc15 server which just works fine. So it might be the combination of client/server versions.

**Comment by nferrari** [comment]
Happens to me while sharing with a group. Autocompletion successfully finds the group while I'm typing it but validating the sharing ends with an error.

Nextcloud version is 3.4.1.

**Comment by MeiRos** [comment]
Same error here. Unknown error when searching for user to share. -> Can't share.
App 3.4.1
NC 13.0.8
Android 8.0.0

**Comment by tobiasKaminsky** [comment]
I verified it on my latest server:
- I can search for users
- I can select a user/group to share with


Can you create us a test account, test if the problem occurs also there and if so send the credentials to tobias at nextcloud dot com with a reference to this issue?

**Comment by jbchurn** [comment]
Getting unknown error when trying to search name for file sharing.
App 3.4.1
NC 13.0.4
Android 8.1.0

Likely when will be new release to solve this? Facing critical unable to sharing issue now by users currently.
TQ

**Comment by AndyScherzinger** [comment]
Hard to tell, it will definitely ship with 3.5.0 which will be released mid of February. @tobiasKaminsky also flagged it for a Hotfix release while I thus can't say when he will find the time to do the release for version 3.4.2.

**Comment by jbchurn** [comment]
Hi,
TQ for the priority. May I know how can we follow the progress of mentioned beta that include this fix?

Between, the fix will support for NC13.0.4 as well, correct?

TQ.

**Comment by MeiRos** [comment]
3.4.2 RC1 and still the same. After every letter 'unknown error'.

**Comment by AndyScherzinger** [comment]
@MeiRos could you sent @tobiasKaminsky a test account to debug this? android @ nextcloud dot com

**Comment by tobiasKaminsky** [comment]
> when I try to share a file with another user, I get an "unknown error" message. This happens at the moment I type the name of the user at the search field on sharing tab. (one message for every letter I type).

Hm. This seems to be a bit different from what I've fixed.
For this I really need a test account…

**Comment by bazio101** [comment]
> Hm. This seems to be a bit different from what I've fixed.
> For this I really need a test account…
You need to create you a test account on my server, is that right? If so, how to send it to you? How to use android@nextcloud.com?

**Comment by tobiasKaminsky** [comment]
@bazio101 
Can you create us a test account, test if the problem occurs also there and if so send the credentials to tobias at nextcloud dot com with a reference to this issue?

**Comment by tobiasKaminsky** [comment]
Thank you, I could verify it and I already created a fix, which will be in todays new RC2.
Please test it once it is out.

**Comment by tobiasKaminsky** [comment]
3.4.2 RC2 is now on Gplay, please try it :-)

**Comment by MeiRos** [comment]
Works here too, but I can't change rights from the shared pic. I can't deny edit or share. Quit sharing works.
@tobiasKaminsky test account is still there if you need it.

**Comment by tobiasKaminsky** [comment]
Can you open up for both new issues, with a detailed info according to the template, and maybe screenshots?
@bazio101 at least for your issue a screenshot would be good
@MeiRos and for your issue we would need a detailed info

**Comment by tobiasKaminsky** [comment]
Closing this as the original problem (cannot share) is solved
