### ISSUE TITLE
choose folder of account

### ISSUE THREAD

**Issue by Thatoo** [nextcloud/android#3404]
### Is your feature request related to a problem? Please describe.
My nextcloud server address is not at the root of my domain but on something like https://domain.tld/nextcloud/
So the android app stores everything on android/media/com.nextcloud.client/nextcloud/user@domain.tld%2Fnextcloud .The problem is that %2F isn't always liked by other app. Some confuse it with / .It is the case at least for KeePass DX so it makes the usage of keepass and sync unfriendly.

### Describe the solution you'd like
I would like to choose my account's folder's name. Instead of "user@domain.tld%2Fnextcloud" I'd prefer to choose. I would just put "user" in my case...

### Describe alternatives you've considered
If it's really not possible to choose our account's folder's name maybe it could be a good idea to change %2F by something like a "_" or a "-" .

**Comment by AndyScherzinger** [comment]
Does keepassx support webDAV? I am using keepass2android where I configured the keepass file within the NExtcloud server via webDAV within the app itself and so keepass2android syncs the file itself. No need for the Nextcloud files app to be involved :) (just an alternative of course / friendly suggestion)

**Comment by Thatoo** [comment]
On the computer, we access, read and write files that are in the synced folder so I don't see any reason not to do that in android.

No, keepassx doesn't support webdav... Thank you for your suggestion.

**Comment by joshtrichards** [comment]
> No, keepassx doesn't support webdav... Thank you for your suggestion.

Closing, as KeePassX no longer exists these days.

KeePassDX, another option, supports the approach we suggested back in 2019 (using Android's Documents Provider/ SAF): https://github.com/Kunzisoft/KeePassDX/wiki/File-Manager-and-Sync
