### ISSUE TITLE
Could you please delete email when file sharing

### ISSUE THREAD

**Issue by tanvir1414** [nextcloud/android#3408]
I don't like sharing my email when i share my file with public.

**Comment by AndyScherzinger** [comment]
Hi @tanvir1414, if how and when do you share your email with a public share? If you generate share link you can share that one with anybody any way you like. So you can share it via whatever your phone provides to share information with others like messengers, etc.

**Comment by tanvir1414** [comment]
I say mail should not be shown. In google drive we dont know the mail when we share public  but download the file. Here mail is shown. Example:
https://nextcloud.webo.hosting/s/zAF9JBPED6DjwrZ

**Comment by AndyScherzinger** [comment]
Thanks :)

Server issue is https://github.com/nextcloud/server/issues/13272
