### ISSUE TITLE
Shared folders rename themselves

### ISSUE THREAD

**Issue by Fabiosilvero** [nextcloud/android#341]
### Actual behaviour
- Folders shared with me rename themselves by adding (2) at each synchronization. 
### Expected behaviour

This should not happen.
### Steps to reproduce
1. Share folders From A to B
2. Log in with B in the app
3. Launch a synchro. Shared folder will be renamed with (2) at the end. (2) will be added at each synchro.
### Environment data

Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:
#### Web server error log

```
Insert your webserver log here
```
#### Nextcloud log (data/nextcloud.log)

```
Insert your Nextcloud log here
```

**Comment by tobiasKaminsky** [comment]
This is solved in server: https://github.com/nextcloud/server/issues/1588
It is in stable10 and should be released with the next update.

**Comment by Fabiosilvero** [comment]
Thank you ! That was quick :)

**Comment by tobiasKaminsky** [comment]
Once 10.0.2 is released, please test it and (I hope) close it :+1:
