### ISSUE TITLE
Push notifications disabled for the wrong reason

### ISSUE THREAD

**Issue by Zepmann** [nextcloud/android#3410]
### Actual behaviour
On an Android device without proprietary Google code and with all [microG](https://microg.org/) components installed, the Nextcloud Android application (installed through F-Droid) does not receive push notifications. In addition, the Notifications screen has the following message:

"Push notifications disabled due to dependencies on proprietary Google Play services."

The Nextcloud Android application from the Play Store (installed using a sideloaded APK) does not show this behavior. Push notifications work through microG.

### Expected behaviour
Push notifications should work in the F-Droid release of the Nextcloud Android application, the same way as they do in the Play Store release. A check could be made for the availability of either Google's proprietary code **or** microG.

An example of an application that works correctly with Google's proprietary code and with microG is [Signal](https://signal.org/).
 
### Steps to reproduce
1. Have an Android device without proprietary Google code ('GApps'), with microG installed. Make sure all checkmarks under 'Signature spoofing support' and 'Installed packages' are enabled in microG Settings.
2. Install F-Droid. Install 'Nextcloud' through F-Droid.
3. Open the Nextcloud application and login in your Nextcloud instance.
4. Open the Notifications screen to see the mentioned message. Alternatively, try to authenticate another device with Nextcloud Notification two-factor authentication enabled. There will be no notification on the Android device.

Steps 3 and 4 can be repeated using the Play Store's APK when it is sideloaded. The result is that notifications work.

### Environment data
Android version: 7.1.2

Device model: Xiaomi Mi 4c

Stock or customized system: LineageOS (without GApps)

Nextcloud app version: 3.4.1

Nextcloud server version: 5.0.0

**Comment by mario** [comment]
This is unfortunately  not possible yet as F-Droid cannot build with the required client side libraries. It will however change soon since Google is open sourcing the Firebase client push libs :) So stay tuned ;)

**Comment by Zepmann** [comment]
The current situation promotes APK downloading through shady websites to receive a fully working application, on devices that miss access to the Play Store. This seems undesirable from a security perspective.

I would suggest to at least provide an unrestricted APK on the Nextcloud site itself, for those of us (un)fortunate enough to miss Google applications on their devices. [Signal does this](https://signal.org/android/apk/).

**Comment by mario** [comment]
@Zepmann https://download.nextcloud.com/android/ is not very shady :)

**Comment by Zepmann** [comment]
Neither is it publicly known. A link to there from the [client download page](https://nextcloud.com/install/#install-clients) would be appreciated. 

An additional suggestion: provide a copy/link to the latest version. Do not let the user select it if it is not needed/desired.

**Comment by mario** [comment]
Always happy to help! :)
