### ISSUE TITLE
Not getting Two factor login prompt from app

### ISSUE THREAD

**Issue by ryan77627** [nextcloud/android#3413]
### Actual behaviour
- I try to login to Nextcloud and choose notification for my TFA method. I dont get any notification on phone so I have to open up the app, go to notifications, then approve
### Expected behaviour
- It should present a push notification.
### Steps to reproduce
1. Enable TFA by notification
2. Log out of your account on the computer and add the app on a phone
3. Try to log back in

### Environment data
Android version: 7.0.1

Device model: LG Stylo 3

Stock or customized system: Stock

Nextcloud app version: 3.4.1

Nextcloud server version: 15.0.0

**Comment by AndyScherzinger** [comment]
cc @tobiasKaminsky afaik a push notification should be send (is 3.4.1 signed properly?)

**Comment by mario** [comment]
What he is saying is there are no buttons in the notification itself :)

**Comment by AndyScherzinger** [comment]
@mario from what I understood there is no incoming push notification at all!

**Comment by ryan77627** [comment]
No, I'm saying I'm not getting a push notification in my top bar. If I go into the app and then to notifications I can see it and the buttons are there ;)

**Comment by ryan77627** [comment]
Just noticed, I'm getting the notification fine on my tablet just fine. Same app version and same android version. Notifs are not blocked on my phone and I have nextcloud set to ignore battery optimizations so it shouldn't be closing. Anyone have any ideas? I'm stumped.

**Comment by ryan77627** [comment]
Nope, nothing. Interestingly, when i put a usb stick in my phone, the
app sends a push stating a new media folder was detected just fine. The
2FA dont get pushed though.

**Comment by tobiasKaminsky** [comment]
> push stating a new media folder was detected just fine

This is not a push notification, but a regular notification.

A push notification is something that is triggered by server and send to the device via googles cloud messaging service.

**Comment by ryan77627** [comment]
Is it? It gets pushed to my tablet just fine, just not my phone. When I get
home I'll make a video to show the issue, since I think the distinction
between "push" and "regular" notifications needs to be made.

On Jan 8, 2019 10:58 AM, "Tobias Kaminsky" <notifications@github.com> wrote:

push stating a new media folder was detected just fine

This is not a push notification, but a regular notification.

A push notification is something that is triggered by server and send to
the device via googles cloud messaging service.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/nextcloud/android/issues/3413#issuecomment-452350617>,
or mute the thread

**Comment by AndyScherzinger** [comment]
@nextcloud/server-triage does the push notification get send to just one device or several for a 2FA request? 

Side note:
Notifications are just that, notifications. There is not distinction between them within Android, same for any other app on the Android platform.

**Comment by ryan77627** [comment]
I only have my tablet and my phone, so the 2FA notification goes to the tablet, not the phone. I'm gonna look for some other devices in my house when I get home to get a better sample size.

@tobiasKaminsky Thanks for the distinction between the two. I guess the regular notifications work fine on the phone, just not the push notifications. Both types work fine on my tablet.

@AndyScherzinger I understand that there are just notifications, however I'm going to keep referring to them as "push" and "regular" referring to notifications either generated in the app or generated from the nextcloud server pushed to the app. Since technically they are two different "types" of notifications

**Comment by chriswells0** [comment]
I have (had?) the same issue.  When I looked at the devices registered for notifications, some were missing:

`select uid, token, deviceidentifier, apptype from oc_notifications_pushtokens;`

I went to Android's Settings -> Apps & notifications -> Nextcloud, clicked Force stop, selected Storage, and then cleared cache and storage.  After restarting Nextcloud, it registered for push notifications again.

What's interesting is that the wifey's phone (Nextcloud and Talk apps) disappeared from the table shortly after I got all 4 of our devices working.  It could be a coincidence, but her battery had died just before I noticed it was no longer registered.  Is there any scenario such as multiple failed push notifications that causes the server to unregister a device?

**Comment by chriswells0** [comment]
@ryan77627 Did you get your notifications working?  If not, does the fix I described above (clearing the app cache and storage) resolve it for you?

@tobiasKaminsky / @AndyScherzinger Do either of you know whether the server will unregister a device under any scenario?  I suppose the client could be unregistering itself, but that seems less likely.

**Comment by ryan77627** [comment]
Sorry, I'll try later today, I ended up turning it off. I think it worked
every since I bought a new phone, but I'll verify and try your fix if it
doesn't work.
