### ISSUE TITLE
upload change Settings has no effect

### ISSUE THREAD

**Issue by abc2006** [nextcloud/android#3414]
### Actual behaviour
When setting Auto-Upload, it stops working after a time and produces many errors.
I want to use auto upload with deleting the files after uploading in nextcloudfolder "Sofortuploads/Honor110"
I get the error (sorry, just reinstalled) that the file is locally not found and thus not uploaded.
I changed the setting to "leave images on the source folder" but get the same error as above.
I changed the target folder on my nextcloud-server to "test", and get two! error messages that the file couldn't be uploaded: /sofortuploads/test and /sofortuploads/camera.
Why Camera? i didn't want this folder... 

### Expected behaviour
Upload to the given folder and then delete the local file.
 
### Steps to reproduce
1. automatic upload
2. change Remote-directory to something new
3. original file is being deleted

### Environment data
Android version:
8.1
Device model: 
Honor 10
Stock or customized system:
stock
Nextcloud app version:
341
Nextcloud server version:
14.0.3 -> just doing the update

**Comment by abc2006** [comment]
#409 is not related - server is reachable
#1056 is not related - filesize is shown correctly
#757 does not look related as i am not modifiying files
#2020 may be related , as its concerning the settings of auto-upload
#2531 may be related, as i moved through different time zones (USA) in September

**Comment by tobiasKaminsky** [comment]
File deletion is only possible if the source folder is write-able.
In case of sdcard it sometimes can be that it is only read-only.

All in all the new settings will only apply for new uploads, but not for existing ones.
