### ISSUE TITLE
Editing with Collabora disables Android clipboard

### ISSUE THREAD

**Issue by pleasantarmour** [nextcloud/android#3415]
### Actual behaviour
- When selecting text, the only options for cutting, copying, or pasting text exist within Collabora on the Nextcloud app. Text cannot be pasted from another app using the default Android clipboard.

### Expected behaviour
- The native Android clipboard should be available, so that text can be copied and pasted from other apps.
 
### Steps to reproduce
1. Open an odt document.
2. Hold down on text to select text to cut/copy or paste text from clipboard.
3. (alternatively) Begin editing and try using Gboard to paste text by navigating to the text editing layout.

### Environment data
Android version:
8.1.0
Device model: 
OnePlus 5T and Honor 7X
Stock or customized system:
AICP and stock (respectively)
Nextcloud app version:
3.4.1
Nextcloud server version:
15.0.0

**Comment by tobiasKaminsky** [comment]
@rullzer this is something for Collabora, right? Or is this done by our RichDocuments app?

**Comment by rullzer** [comment]
Collabora handles this. Richdocuments just relays you to the collabora server.

However, I assume that this is something with android and the webview.

**Comment by pleasantarmour** [comment]
Would there be any use in reporting this on the Collabora side or is this something they wouldn't be able to fix?

**Comment by tobiasKaminsky** [comment]
I'll ask Collabora.

**Comment by tobiasKaminsky** [comment]
It also does not work when using Chrome and Nextcloud/RichDocuments.

**Comment by tobiasKaminsky** [comment]
CC for our Collabora partners: @thebearon @timar

**Comment by tobiasKaminsky** [comment]
@pleasantarmour can you test latest 3.8.0RC1? It is available via Play Beta Program.

**Comment by tobiasKaminsky** [comment]
Ref: #4189

**Comment by pleasantarmour** [comment]
@tobiasKaminsky I do not have the Play Store on my phone, but I will try it once the F-Droid version is live. Thanks for the update.

**Comment by pleasantarmour** [comment]
Still doesn't seem to be working on my end with 3.8.0.

**Comment by tobiasKaminsky** [comment]
Can you maybe post a screenshot what happens when you long press it?

**Comment by pleasantarmour** [comment]
Apologies for the late reply on this. Attached is a screenshot of what appears when I long press to try to paste some text from my clipboard. For some more info, I'm running the 4.0.6.1 collabora/code Docker image with Collabora Online 3.4.2 on my Nextcloud server.

![photo4938261686960367663](https://user-images.githubusercontent.com/3100993/65837110-57b7c800-e2b9-11e9-8759-4fc0724925d9.jpg)

**Comment by tobiasKaminsky** [comment]
For me it shows now the copied text directly in keyboard.
