### ISSUE TITLE
After uploading a file from external memory, can't upload from internal memory anymore.

### ISSUE THREAD

**Issue by igor-cali** [nextcloud/android#3419]
### Actual behaviour
Cannot access to internal card content from the navigation/path bar in the dialog to add files to NC.
This happens after I uploaded content from external SD card.
The only workaround now for me is to move files to external memory (using a file manager app) and then uploading from NC client.

### Expected behaviour
NC to be able to access/select internal SD content from the navigation bar (e.g. `/storage/emulated/...`).
- Tell us what should happen
 
### Steps to reproduce
1. Select NC File view;
2. add new content by pressing the `+` floating button;
3. browse the external SD card (`/storage/3799-3C6C/...` in my case);
4. select and upload a file.
5. close NC client / reboot device.
6. try to add new content by pressing the `+` floating button;
3. try to browse the internal SD card: at this step, from path /storage/ 3 folders are listed: `3799-3C6C` (the external card), `emulated` (no content if selected) and `self` (no content if selected).

### Environment data
Android version: 8.0.0

Device model: 
FRD-L09 - Honor 8

Stock or customized system:
stock

Nextcloud app version:
3.4.1

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by DecaTec** [comment]
Same problem here.
All files on internal storage have to be copied to external storage manually in order to be available for auto upload.

**Comment by Bertel3** [comment]
I have the same problem since the app remembers the last upload path. 
But it was never possible to use the file browser in the Nextcloud app to browse back to the internal strorage once you have browsed to the external storage. But before the app remembered the last upload path it was not a problem because it always started browsing from the internal storage.
I would suggest adding a shortcut to browse to the internal /external storage.
