### ISSUE TITLE
Cannot turn off app locking

### ISSUE THREAD

**Issue by tomasz-grobelny** [nextcloud/android#3421]
### Actual behaviour
- Cannot turn off application locking in settings. Every time I finish editing a file I am asked to unlock the application. Every time I start the application I am asked to unlock it.

### Expected behaviour
- Application should not ask for unlocking.
 
### Steps to reproduce
1. Run the application.
2. Unlock (I use swipe pattern)
3. Go to nextcloud app settings and set locking to none.
4. Exit app.
5. Run app - unlock screen appears again.

### Environment data
Android version: 8.0.0.162(C432)
Device model: FIG-LX1
Stock or customized system: Stock
Nextcloud app version: 3.4.1

**Comment by tobiasKaminsky** [comment]
Strange, do you see at step 3 a confirmation?

**Comment by tomasz-grobelny** [comment]
Do you mean if I need to enter my unlocking code to confirm resigning from unlocking code? Yes. The setting seems to be saved, but not respected in subsequent application runs.

One more observation: I recently installed dev version and it seems to work there just fine.

**Comment by tobiasKaminsky** [comment]
> The setting seems to be saved, but not respected in subsequent application runs.

Strange…



> One more observation: I recently installed dev version and it seems to work there just fine.

So for some reason the saved setting is not respected in the stable version.

Unfortunately I have no idea what to do, as I do not have access to the device…

**Comment by tomasz-grobelny** [comment]
Any idea what I could check or the only option that comes to mind is to set up development environment and attach debugger (which might not be worth it as it seems to work in dev version)? Maybe I could analyse the configuration? Where is this setting stored?

**Comment by tobiasKaminsky** [comment]
Setting is stored in shared_preferences.xml, called "lock", with one of:
"none"
"passcode"
"device_credentials"

**Comment by christianlupus** [comment]
I think I am affected by the same bug. I cannot disable the protection mode as well. As far as I remember, I had to use my fingerprint/swipe for the very first time I used the app. 

Where is this file `shared_preferences.xml` to be found?

**Environment data**
Android version: 9
Device model: Xiaomi Redmi A2 Lite
Stock or customized system: Stock
Nextcloud app version: 3.6.0 (stable from Google play store)

**Comment by christianlupus** [comment]
@tobiasKaminsky Can you tell me, where to find this XML file? Do I need to use ADB to open it or can I use a normal file explorer to get it?

**Comment by christianlupus** [comment]
@tobiasKaminsky I would like to share my settings but __please__ tell me where the file is located.

For me this causes problems as in #1924 discussed: I cannot make any screenshots even if I wanted to. I cannot disable the locking of the app thus all I can do is make a (physical) photo of the device in order to write the documentation I am up to...

**Comment by ezaquarii** [comment]
@christianlupus the file can be found in application data directory, `/data/data/com.nextcloud.client/`. The problem is that if you have stock device, you don't have access to this file from `adb shell`. You'd need to "root" the phone first, as the security model does not allow apps to access data of other apps.

If you can reliably reproduce this problem, we could provide you a special build with options to extract this data.

**Comment by christianlupus** [comment]
@ezaquarii Rooting of the device is not the best idea, I think. I can try if I can get in but I doubt it.

What I can confirm is that I have a NC app installed, while having the setting `App-PIN` (localized in German, in English it is I think `App passcode`) set to `Nichts` (meaning none). With these settings I have to enter the swipe code of the system each time I open the app and in the list of open apps the NC app's preview is white-only.
If I do not miss anything, this is the described bug here. I am willing to install a dev version if you provide it to me and report back.

**Comment by ezaquarii** [comment]
@christianlupus You can check out our new development version that has option to show/export preferences:

https://github.com/nextcloud/android/pull/4133
#4133

1. Just scan the QR code or download apk from the link.
2. Install the app
3. Reproduce the problem
4. Go to `Settings`, scroll to bottom and select `Engineering & Test Module` -> `Preferences`
5. Use "share" icon to share the contents of your preferences with tobias@nextcloud.com

_Plase do NOT publish your preferences here!_

**Comment by christianlupus** [comment]
@stale: Please wait a bit, we are sorting this out ;-)

**Comment by christianlupus** [comment]
@ezaquarii As the PR is now merged, could you please provide me with information about further steps? Thank you

**Comment by ezaquarii** [comment]
@christianlupus You can install the daily dev (or ETM build using QR code) and share your preferences.

Please be advised that prefs can contain URLs to your server and your login (but no passoword). You can safely remove them - those are not needed to investigate the issue.

Drawer -> Settings -> scroll to bottom -> Engineering Test Mode -> Preferences -> Share icon in upper right corner

**Comment by ezaquarii** [comment]
@christianlupus You can install the daily dev (or ETM build using QR code) and share your preferences with us.

Please be advised that prefs can contain URLs to your server and your login (but no passoword). You can safely remove them - those are not needed to investigate the issue.

Drawer -> Settings -> scroll to bottom -> Engineering Test Mode -> Preferences -> Share icon in upper right corner

**Comment by ezaquarii** [comment]
@christianlupus I think this feature is intended only for dev version and won't be available on Google Play anytime soon. The best we can do now is to re-create this issue on daily dev build.

Are you able to do it? If you don't want to uninstall your daily driver, you can use QR code from ETM link above to install a dev version side by side and then you can experiment with various settings.

**Comment by christianlupus** [comment]
> Are you able to do it? If you don't want to uninstall your daily driver, you can use QR code from ETM link above to install a dev version side by side and then you can experiment with various settings.

You mean I should install the dev version mentioned in the README.md in the main repo (like direct APK of fdroid)? This should be doable.

What do you mean by daily driver? The normal (google playstore based) version?
I would prefer if I did not need to resetup my configuration but I would be ok with a dev version at the moment (also to get bug quickly sorted out). Can I simply install the fdroid version over the currently installed one or will this break things?

**Comment by ezaquarii** [comment]
@christianlupus Please use direct apk link. I confirmed that it contains ETM screen in settings.

**Comment by christianlupus** [comment]
@ezaquarii I just tested the dev version from the APK file. It does definitively not behave as the "official" stable version from google play store. The following happens depending on the setting of the app lock mechanism selected in the settings:

*None*
No app locking is enabled at all. The ETM shows a line `lock: none`.

*Device credentials*
No app locking can be seen. I swiped the app out of the memory to force reloading of the activity and restarted it. In ETM there is a line `lock: device_credentials`. (Fun fact: When changing to no locking in the settings I am asked for my fingerprint/unlocking pattern.)

*Application PIN*
Merely the same as with the device credentials. No request for the app pin is made when reopening or whatever is done. However the pin asked as well when changing the locking method. There is a line `lock: passcode` in the ETM debug settings.

This looks like the app protection is disabled in the dev version somehow. Should I file a separate bug request to tackle this separate problem/bug?

**Comment by christianlupus** [comment]
tock tock, I am still on this issue.

**Comment by tobiasKaminsky** [comment]
The only idea I have is to delete the app and re-install it as then the settings are also removed.
Then you could test again if lock removal is working.

As it is working on so many other devices, I fear that this is some kind of hiccup with your device, which is hardly to help over the internet :/

**Comment by christianlupus** [comment]
OK, I will remove the dev apk version soon and reinstall it thereafter. Then I can see, if this helps. I just came home from hildays these days and I need to get things going first...

**Comment by christianlupus** [comment]
OK, sorry for my late answer. I was a bit busy these days...

First, I removed the dev version of the app and reinstalled it afterwards once more. I seem to get the desired effect: I can select which way the app protects itself. Good so far.

The main app was updated in the mean time from the play store. I do not know if these changes were somehow related to this bug report.

The funny part is that the app locking seems no longer affect the possibility to make screeen shots (the reason for me trying to disable locking). I do not know if this is related to me having enabled the development mode in my phone at the moment or if here was a change in the code base of the nextcloud app that allows now screenshots. Anyway I am ok with the current behavior although I cannot effect some settings of the version in the play store. So there is still a bug but that does not affect me negatively.

It is up to you if you want to continue trying to hunt down the bug at the moment. Please tell me if I need to do something.
