### ISSUE TITLE
Auto Upload not working

### ISSUE THREAD

**Issue by Speed7811** [nextcloud/android#3425]
Dear all,

I have NC in Version 14.0.4 running with two Accounts. One Moto G5 with Android 8.1. This works without any Issues. The other Samsung J5 with Android 7.1.1. On thus Smartphone the Auto Upload doesn't work always. I reinstalled the NC App abd renew the Auto-Upload settings bit it doesn't work the most time. Sometimes when I search in the NC App the upload starts...but rhe most time auto-upload doesnt work. What can I do? 

Rainer

**Comment by jacquesschenk** [comment]
Same problem here with a samsung s8 android 8.0. Some uploads fail some are ok, if it fails error is "Verbindingsfout" which translates to connection error. Not very usefull in troubleshooting. Where can i find the logfiles to show what is actualy going on? Manual retry fails also. Aa full manual uploads succeeds without Issues.

**Comment by tobiasKaminsky** [comment]
Samsung has special battery handling, please try to remove NC app from this batterystuff.

@jacquesschenk go to settings -> logs
