### ISSUE TITLE
Files appear as conflicting with the server even though they were not modified on server

### ISSUE THREAD

**Issue by djibux** [nextcloud/android#343]
Hello,

I have posted this as an ownclient client issue but migrated to nextcloud since, and I also have the issue.  I am not sure whether cross-posting it a good idea, and I am sorry if it is not.
### Actual behaviour

When a file is modified twice on the client within a few seconds and the first upload to the server didn't finish, I get a popup telling me the local version is in conflict with the distant version.
Expected behaviour

A file should not be in conflict with the server version if the file hasn't been modified on the server…
### Steps to reproduce
1. Make a file available offline
2. Make a few quick changes and saves to that file, making sure that your saves happen before the previous version was uploaded to the server (I personally always trigger the error with a todo.txt file modified via an app called Simpletask)
3. The "conflict resolution" popup opens within nextcloud client.
### Environment data

Android version: 6.0.1

Device model: Zuk Z1

Stock or customized system: CyanogenMod, official nightly build

nextCloud app version: Nextcloud 1.3.1 (f-droid)

nextCloud server version: 10.0.1 (current stable)

**Comment by tobiasKaminsky** [comment]
Meanwhile we enhanced the app. Can you please try and report back if the bug still exists on latest official version in conjuction with latest server or even try our [dev version](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#dev-release)?

**Comment by djibux** [comment]
Sorry for the delay.  I confirm I no longer encounter the issue.  There now seems to be a delay between the time a file is modified and the time it is uploaded on the server which certainly helps.
