### ISSUE TITLE
Uploader: don’t make the account choice a blocking popup 

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/android#344]
I have 2 accounts configured in my Nextcloud mobile app. There is a blocking account chooser popup every time I want to upload something.

This isn’t great beacuse most of the time I use my personal instead of my company account anyway. So:
- we should directly show the file list, defaulting to the account last used
- put a switcher dropdown in the top bar

Ok @tobiasKaminsky @AndyScherzinger? (As already discussed in the old repo ;)

**Comment by AndyScherzinger** [comment]
Sounds good to me, yes.

**Comment by tobiasKaminsky** [comment]
Fine for me. 
Just to clarify: is it "enough" to have a "switch account" in the overflow menu, which then shows the blocking account chooser?

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky fine for me for a first solution. At some point we might want to have it in the toolbar as a general chooser on the headline itself" but that could be done in a later iteration.

**Comment by jancborchardt** [comment]
Any update here? This is one of the most annoying things when wanting to upload.

**Comment by AndyScherzinger** [comment]
No update yet but since it is a small change maybe something that can be done pre-2018. And it is imho also a starter issue, so labeling as such 👍

**Comment by esafirm** [comment]
Hi, this seems interesting. Could i take this one?

**Comment by mario** [comment]
@esafirm just one second please :)

@AndyScherzinger hm, what is this issue about? Shouldn't it upload to a current account?

**Comment by AndyScherzinger** [comment]
It is for share with nextcloud where the folder chooser of our app comes up. At the moment this has a blocking pop up with an account chooser but instead should just default to the current account while having a action bar chooser for the accounts. Just like defined by Jan in the issue description.

So imho @esafirm can go ahead :)

**Comment by mario** [comment]
Ah! Ok, @esafirm - you have a go!

**Comment by esafirm** [comment]
I'm on it 👍

**Comment by esafirm** [comment]
Moving it to overflow menu. Is the order alright? 
I think the menu title should be `switch account` but creating new string resource kinda overwhelming (translation stuff) so i chose the already defined string "choose account" 

<img width="342" alt="screen shot 2017-10-04 at 11 20 37 pm" src="https://user-images.githubusercontent.com/1691440/31187019-a936beba-a95a-11e7-9f39-e2597b0d2f56.png">

**Comment by AndyScherzinger** [comment]
@esafirm you can just create a new string, no worries. You just need to have the standard value, all translations will come in via Transifex. After this has been merged to master the Nextcloud bot will push it to Transifex for translations.

@jancborchardt what do you think? Since it is now kind of hidden and implicit (since you are not forced to choose) I'd like to have the current account as a subtitle in the action bar so the users see/know to which account they will be uploading files + it gives first time users a hint that there is the possibility to switch accounts.

Other than that if the approach is fine with Jan/designers I'd also say: 
* Don't display the menu item if there is only one account in total
* Don't display the account in the action bar's subtitle if there is only one account in total

**Comment by comradekingu** [comment]
The underlying text could start scrolling if blocked by an overlying text, not that it made sense this time.

**Comment by AndyScherzinger** [comment]
@comradekingu not sure I understand, the subtitle is shown below like for example shown here: http://www.viralandroid.com/2015/12/setting-android-actionbar-subtitle-and-color.html

Do you think the account string might be too long to fit in some edge cases?

**Comment by jancborchardt** [comment]
@AndyScherzinger having the account name as a subtitle sounds good! I also thought about directly showing the avatar in the top right (where the share icon would normally be, next to the menu icon), what do you think? Of course only show it when you have two different accounts in the first place – same for the subtitle, it’s not needed with only one account.

The only issue with the avatar of course is if you use the same avatar on both instances …

**Comment by AndyScherzinger** [comment]
Hmm,not sure about the avatar. Never saw any app doing this or a guideline promoting it. Anything besides unicolored menu icon on the right seems unusual,no material. Besides that you have the same issue if you have to accounts without avatars which gives you the letter circle and if the accounts end up with similar color codes than you can't distinguish them either.

**Comment by esafirm** [comment]
@AndyScherzinger @jancborchardt so ... should i go for the subtitle?

**Comment by AndyScherzinger** [comment]
Subtitle would be great, yes please :)

**Comment by jancborchardt** [comment]
@esafirm yep, subtitle is good. :) Just make sure that when there’s only one account that there’s no subtitle because then it’s not needed. ;)

**Comment by esafirm** [comment]
Made a pull request! https://github.com/nextcloud/android/pull/1684 😁
