### ISSUE TITLE
Document provider enhancement

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#3441]
This is somekind of a meta issue:

Issues regarding document provider:
- #2952 
- #303
- #2258
- #3422
- #1827

Google sample project: https://github.com/googlesamples/android-StorageProvider
Info: https://developer.android.com/guide/topics/providers/create-document-provider

PR fixing it:
- [x] #3432 
- [x] #3433 
- [x] #3434 
- [x] #3435 
- [x] #3436 
- [x] #3454 (was #3437)
- [x] #3455 (was #3438)
- [x] #3439 
- [x] #3453 (was #3442)

So once all PRs are tested, we should ping the issues and get a verification that they are solved.

**Comment by AndyScherzinger** [comment]
🎉 awesome work @tobiasKaminsky - also sub-tasks have been merged and are done. Do you ping the issues related to this one (as mentione ddin the issues description?).

Should we close this issue (since DONE) or do you want to keep it open depending on the issues feedbacks?

**Comment by tobiasKaminsky** [comment]
I'll close this and ping the others.
