### ISSUE TITLE
App allows to go out of ../emulated , but not to come back

### ISSUE THREAD

**Issue by telmich** [nextcloud/android#3449]
When selecting files, it is possible to go to /. However once being there, it shows no files found and you cannot go back in the tree anymore

**Comment by AndyScherzinger** [comment]
Well, We probably should have a chooser for the storage paths like sd-card, internal, etc. (e.g. like Amaze File Manager), no?

**Comment by AndyScherzinger** [comment]
Good catch @DecaTec - they probably share the exact same root cause, yes.

**Comment by AndyScherzinger** [comment]
Good question, we can't use the drawer menu like Amaze but we could use the chooser in the toolbar for that and drop its current functionality?

**Comment by AndyScherzinger** [comment]
Where would you put this button, also calling @nextcloud/designers for feedback :)

**Comment by tobiasKaminsky** [comment]
No real idea…on header next to overflow menu?

**Comment by AndyScherzinger** [comment]
> No real idea…on header next to overflow menu?

Thant would work and likely be the easiest way to implement it (technically speaking)

**Comment by jancborchardt** [comment]
> Well, We probably should have a chooser for the storage paths like sd-card, internal, etc. (e.g. like Amaze File Manager), no?

Yeees please. :D All this /0/emulated is soo confusing. ;)

Couldn’t this be the very top, with a listing of "Storage" and "SD card"? If there is only one storage, the view is not needed and the last readable root is "Storage".

**Comment by tobiasKaminsky** [comment]
Hm, I currently have no clue where and how this listing should look like.
Can you explain this a bit more?
