### ISSUE TITLE
Newly added custom auto-upload folder is at the bottom

### ISSUE THREAD

**Issue by bertwesarg** [nextcloud/android#3456]
### Actual behaviour
- Newly added custom auto-upload folder is at the bottom, after all existing auto-upload folders, be they custom or suggested, active or inactive.

### Expected behaviour
- Newly added custom auto-upload folder should be at the top, at least in the block of all custom auto-upload folders
 
### Steps to reproduce
1. Open Nextcloud App
1. Ensure expert mode
1. Go to Auto upload pane
1. Select 'Set up a custom folder' and fill in than 'SAVE'

### Environment data
Android version: 8.0

Device model: Nokia TA-1032 (aka. "Nokia 3")

Stock or customized system: Stock

Nextcloud app version: 3.4.1

Nextcloud server version: 15

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky this is true right after addition but correct when re-opening the screen (newly added cusotm folder doesn't trigger a new sorting of the list...)
