### ISSUE TITLE
Sharing a non-downloaded image shares a very blurry and cropped preview

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/android#3458]
### Steps to reproduce
1. Go to an image in your Nextcloud app which is not downloaded locally
2. Share it, and pick e.g. Signal

### Actual behaviour
The recipient only gets the very blurry and cropped-to-square preview of the file.

![signal result after sharing through nextcloud mobile app without downloaded](https://user-images.githubusercontent.com/925062/51116537-b44a8400-180b-11e9-8cd6-719cc951fd40.png)

### Expected behaviour
They get the full-resolution file.

![signal share original](https://user-images.githubusercontent.com/925062/51116509-a4cb3b00-180b-11e9-983b-8a9fb749d423.png)

### Environment data
Android version: 8.1.0

Device model: Fairphone 2

Stock or customized system: LineageOS

Nextcloud app version: Latest Nextcloud dev from F-Droid (20190112)

Nextcloud server version: 13.0.8

**Comment by tobiasKaminsky** [comment]
They get what image "version" you have:
- only thumbnail -> only thumbnail
- you have opened up the image -> sent resized version
- you have downnloaded the image -> sent full image (it can be that recipient still receive a smaller version as e.g. WhatsApp is resizing it)

I would change it, so that you at least get the resized version?

**Comment by AndyScherzinger** [comment]
> I would change it, so that you at least get the resized version?

I second that approach. Sending the resized should be fine most of the time. What do you think @jancborchardt ? :)

**Comment by jancborchardt** [comment]
@tobiasKaminsky @AndyScherzinger yes, that seems to be like a good approach, and we can still adjust if it doesn’t work. Because the thumbnail is definitely too small. :)

**Comment by Senneseph** [comment]
I think it should give you the full, real file, downloading it first if it has to.

Imagine Nextcloud users sharing `.jpg`s and every time they did so it got they more and more pixelated.

**Comment by jancborchardt** [comment]
@Senneseph as was mentioned above:

> Sending the resized should be fine most of the time.

And

> that seems to be like a good approach, and we can still adjust if it doesn’t work.

If we force a download before you can share, then people are going to hate using Nextcloud because it will always take some time to download, especially on mobile connections. That’s why we should do the "good enough" path first, and then we can look at the next step.

**Comment by Gatak** [comment]
When choosing "Share with" there could be an option to share original file or the resized file (at max rez). I actually often would chose between them.

**Comment by tobiasKaminsky** [comment]
Tried it, but we cannot download it in background, as sharing process is not allowed to take that long.

**Comment by chainria** [comment]
> Tried it, but we cannot download it in background, as sharing process is not allowed to take that long.

Okay so what does this mean? No full image? No rescaled image? And what about the "Share" Buttons in the app? Maybe they could download the image files first or something? This bug really hit me hard and I was wondering why I always sent out pixelated images to different sources
