### ISSUE TITLE
Improvement of former Expert Mode features

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#3463]
* swipe to refresh for force re-scan
* trash bin icon on uploaded / failed row
* retry button failed (or should this be done via swipe to refresh? )

cc @tobiasKaminsky

**Comment by tobiasKaminsky** [comment]
Now doing this

**Comment by AndyScherzinger** [comment]
As for your coffee comment I think rescan and retry should be pull to trigger and delete should be the icon.

**Comment by tobiasKaminsky** [comment]
coffee comment?

Thanks for the confirmation, this also what I wanted to do :-)

**Comment by AndyScherzinger** [comment]
> coffee comment?

coffee -> icon (auto correct on the phone...)
