### ISSUE TITLE
Unable to download files

### ISSUE THREAD

**Issue by leveled** [nextcloud/android#347]
### Actual behaviour

I recently migrated my owncloud installation to nextcloud (via [the instructions here](https://help.nextcloud.com/t/migrating-from-owncloud-to-nextcloud/551)) and although behavior on the desktop client and web client is functional, I am unable to download files from the android client. 
### Steps to reproduce

I'm not sure how to reproduce this issue. 
### Environment data

Stock or customized system: Customized (migrated from Owncloud) 
Nextcloud app version: 1.3.1 
Nextcloud server version: 10.0.1 
#### Nextcloud log (data/nextcloud.log)

```
{"reqId":"tVmyl+e7RmNqunzmd1SX","remoteAddr":"10.0.8.4","app":"webdav","message":"Exception: {\"Message\":\"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.\",\"Exception\":\"OC\\\\Encryption\\\\Exceptions\\\\DecryptionFailedException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Stream\\\/Encryption.php(460): OCA\\\\Encryption\\\\Crypto\\\\Encryption->decrypt('PK\\\\x03\\\\x04\\\\n\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\xF7iRI\\\\x1E...', 0)\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Stream\\\/Encryption.php(291): OC\\\\Files\\\\Stream\\\\Encryption->readCache()\\n#2 [internal function]: OC\\\\Files\\\\Stream\\\\Encryption->stream_read(8192)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/Wrapper.php(83): fread(Resource id #143, 8192)\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/CallbackWrapper.php(91): Icewind\\\\Streams\\\\Wrapper->stream_read(8192)\\n#5 [internal function]: Icewind\\\\Streams\\\\CallbackWrapper->stream_read(8192)\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/http\\\/lib\\\/Sapi.php(78): stream_copy_to_stream(Resource id #146, Resource id #148, '392210')\\n#7 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(470): Sabre\\\\HTTP\\\\Sapi::sendResponse(Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(60): Sabre\\\\DAV\\\\Server->exec()\\n#10 \\\/var\\\/www\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/ownclo...')\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/Crypto\\\/Encryption.php\",\"Line\":361,\"User\":\"adi\"}","level":4,"time":"2016-10-18T18:44:31+00:00","method":"GET","url":"\/remote.php\/webdav\/laverna-backup.zip","user":"adi"}
```

The file is not a shared file and like I mentioned before, there seems to be no problem using the webui. After looking through the thread [here](https://github.com/owncloud/ios/issues/701), where users faced a similar issue there seemed to be an issue with email fields in LDAP. However, I have not enabled LDAP on my installation.

**Comment by AndyScherzinger** [comment]
Hi @leveled Sorry to here that. Calling the server know how @MorrisJobke @nickvergessen @LukasReschke and @rullzer any idea what the issue is?

**Comment by MorrisJobke** [comment]
> The file is not a shared file and like I mentioned before, there seems to be no problem using the webui.

Have you encryption enabled?

**Comment by leveled** [comment]
> Have you encryption enabled?

I had encryption enabled in Owncloud, when I migrated to Nextcloud I reenabled it and added the correct encryption module from the app list (it seems to be working in the web/desktop client). When I ran into the error with the Android client I tried disabling encryption and decrypting all the files, but am still running into the same error, even after reinstalling the app itself.



Files for following users couldn't be decrypted,
maybe the user is not set up in a way that supports this operation:
    adi

**Comment by MorrisJobke** [comment]
cc @schiessle

**Comment by leveled** [comment]
I tried reinstalling nextcloud from scratch and am still running into the same problem. Furthermore even when I access my nextcloud instance from a browser on the phone I still am unable to download. 

The logging produced some interesting output, I am not sure what exactly is going on 

`{"reqId":"jZa5ibaJJZZFo4EYbCT+","remoteAddr":"10.0.8.3","app":"PHP","message":"Uncaught Error: Access to undeclared static property: OC\\Files\\Filesystem::$normalizedPathCache in \/var\/www\/nextcloud\/lib\/private\/Files\/Filesystem.php:773\nStack trace:\n#0 \/var\/www\/nextcloud\/lib\/private\/Files\/View.php(2034): OC\\Files\\Filesystem::normalizePath('\/adi\/files\/lave...')\n#1 \/var\/www\/nextcloud\/lib\/private\/Files\/View.php(1152): OC\\Files\\View->unlockFile('\/laverna-backup...', 1)\n#2 [internal function]: OC\\Files\\View->OC\\Files\\{closure}()\n#3 \/var\/www\/nextcloud\/3rdparty\/icewind\/streams\/src\/CallbackWrapper.php(109): call_user_func(Object(Closure))\n#4 [internal function]: Icewind\\Streams\\CallbackWrapper->stream_close()\n#5 {main}\n  thrown at \/var\/www\/nextcloud\/lib\/private\/Files\/Filesystem.php#773","level":3,"time":"2016-10-26T19:05:17+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"adi"}`

**Comment by AndyScherzinger** [comment]
seems to be a server-side issue, so (sorry for the repeated mentions) @MorrisJobke @LukasReschke @rullzer @schiessle @nickvergessen

**Comment by MorrisJobke** [comment]
This is known but we haven't reproduced this properly https://github.com/nextcloud/server/issues/1166

**Comment by leveled** [comment]
Just for clarification it DOES work when I try to access it from my desktop browser/client which is very bizarre.

**Comment by mr-bolle** [comment]
Hi, 

i upgrade the Nextcloud App to 20161108 and after that, i can't download any files from the Storage. With the previouse App i don't have any issues.

Phone: Sony Xperia Z3 dual Android 6.0.1.
Server: Nextcloud 10.0.1
MySQL: MariaDB

[currentLog.txt](https://github.com/nextcloud/android/files/581854/currentLog.txt)

**Comment by tobiasKaminsky** [comment]
Is this still happening with the latest official release or with the latest beta?

**Comment by mr-bolle** [comment]
Hi Tobias, 

With the current beta version i don't have this issue. 

Thanks and best regards

**Comment by tobiasKaminsky** [comment]
Thank you for your quick reply.
Then chances are very good that it will also work in upcoming version 1.4.2.
If not, please re-open.
