### ISSUE TITLE
Share screen behaviour with photos

### ISSUE THREAD

**Issue by bazio101** [nextcloud/android#3473]
Nextcloud dev android 20190118 version
Android 5.0.2
Server running Nextcloud 13.0.8

When I select a file (any except photo) -> details -> sharing and click on field to write, everything works fine.
If I do the same with a photo, when click on field and keyboard appears, the loading icon comes up. Can type letters and take results of users but is not possible to see what I write, unless I disappear the keyboard. 

Sharing problem of issue #3402 with nextcloud dev 20190117 no more exists.

@tobiasKaminsky I uploaded some screenshots on my server on test account. Hope they help.

**Comment by tobiasKaminsky** [comment]
![2019-01-18-103143](https://user-images.githubusercontent.com/5836855/51377894-44d6dc00-1b0c-11e9-8f0a-b581cdfcca38.png)

Totally strange.

@AndyScherzinger do you have in idea?

**Comment by tobiasKaminsky** [comment]
Indeed this is only happening for images.

**Comment by tobiasKaminsky** [comment]
Also it happens if you click in "new comment" text input (in details of an image)

**Comment by AndyScherzinger** [comment]
no an idea about the issue, while the difference is obviously the toolbar's content (image view is hidden in the toolbar for non-images), so this is the only thing that comes to my mind atm.

**Comment by tobiasKaminsky** [comment]
I suspect that for some reason the activity/share fragment (or parts of it) are set to hidden (as of the keyboard) and then the "empty_list" part remains visible.

If this is true, the question is, why does parts of the layout get hidden when opening the keyboard…and who is responsible of this…)

**Comment by AndyScherzinger** [comment]
Afaik while not having looked at the code we do not explicitely hide UI elements when the keyboard becomes visible

**Comment by AndyScherzinger** [comment]
yes, that might well be the cause of it 👍

**Comment by tobiasKaminsky** [comment]
> Setting the LinearLayout to visibility:gone in empty_list.xml helps.

This is indeed working, but now I have no clue how to do this programmatically:
It should only show the loader on refresh activities/on loading on for first time.

But it now shows only a white area…

I guess on long run, we should set LinearLayout to "gone" by default and only enable it when needed in an occurrences…
