### ISSUE TITLE
Lets Encypt Cert with DNS Suffix --> The identity of the server could not be verified

### ISSUE THREAD

**Issue by m0rph2k** [nextcloud/android#3474]
Hi

I have a Lets Encypt Cert with many DNS-Suffix entrys for different private webs.

Sample: 
Cert CN= wildcard.dyndns.org with DNS-Suffix nextcloud.dyndns.org
The Nextcloud Web works fine with this cert but the App say "The identity of the server could not be verified"

Is it possible to check the DNS-Suffix and accept the certificate as trusted in the app ?

**Comment by tobiasKaminsky** [comment]
I tested it and there is a dialog to manually accept the cert.
During debug, I found out that we check the cert with X509TrustManager.checkServerTrusted which is an Android API call.
This results in 
```
java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
```

So I am afraid that we cannot do anything as this seems to be an Android problem.

My proposal is to use a specific cert for this domain.
