### ISSUE TITLE
Syncing Pre-Existing Files Causes Re-upload and Download

### ISSUE THREAD

**Issue by aknobloch** [nextcloud/android#3477]
### Actual behaviour
Given a folder of files on a Nextcloud server, when you manually add those files to the Android file system and start a sync on Android, the given files are uploaded/downloaded again.

### Expected behaviour
The Android app should recognize files that have been manually added to the managed folder, and not trigger an upload/download. Repeating the below reproduction steps, but replacing the Android client with a PC client will show the expected behavior. 
 
### Steps to reproduce
1. Create a folder ("Example_Folder") on the server, containing a file ("test_file").
2. Navigate to the "Example_Folder" directory within the Android app, and manually add the "test_file".
3. Go to the Nextcloud Android app, find the "Example_Folder" and select the "Sync" option.
4. Observe as the "test_file" is both uploaded from the Android server to the client, and then also downloaded from the server to the client. 

### Environment data
Android version: 9

Device model: OnePlus 6T (A6013)

Stock or customized system: Stock

Nextcloud app version: 3.4.1

Nextcloud server version: 13.0.5

### Logs
No relevant logs.

**Comment by tobiasKaminsky** [comment]
Well, this is simply not the way it works.
You should not adjust anything within Nextcloud folder on your own. This will confuse the app.
What you can do is:
- share a file to NC app
- create a file within NC app
- download a file within NC app

then edit it, with any app you want to use via Documents Provider.

**Comment by aknobloch** [comment]
Shouldn't the experience be consistent across platforms? It doesn't make sense that the client application functions fundamentally different on the Android than it does on other devices.
