### ISSUE TITLE
Auto upload fails to upload from mutilpe folders

### ISSUE THREAD

**Issue by sbadger** [nextcloud/android#3482]
### Actual behaviour
I have several folders set to auto upload and only the top folder in my list seems to be uploaded. New files in the other folders are ignored. These are all separate folders in different patch on the local file system. Some folders are synced to the same path as the folder that does sync, others go to sub folders in that same path on the server.

### Expected behaviour
All the folders should automatically upload the new content whenever it is created in a monitored folder.
 
### Steps to reproduce
1. setup multiple folders to sync to InstantUploads and some to Instantuploads/others
2.  generate new content in those folders
3. 

### Environment data
Android version: 9

Device model:  Pixel

Stock or customized system: Stock

Nextcloud app version: 3.4.1

Nextcloud server version: 14.0.6

#### Web server error log
```
```

#### Nextcloud log (data/nextcloud.log)
```
I did not find any info in the log associated with this error
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by sbadger** [comment]
An update on this issue. I found that some of the folders were not even scanned because they had a .nomedia file in them. I believe the app should have the ability to ignore this and scan a folder. The .nomedia file is there to prevent photo apps and such from displaying images form unwanted content not for an app the synchronizes files.

**Comment by tobiasKaminsky** [comment]
We rely on Androids media scanner functionality, as we do not scan for ourselves.

**Comment by AndyScherzinger** [comment]
...which is why we don't "see" these folders (jsut to explicitely mentioned this fact for others not familiar with Android's media scanner)

**Comment by sbadger** [comment]
So there is no way to sync a folder that would have .nomedia in it then. I would think you should be able to add such a folder outside of what the media scanner would find on a device esp since not every folder a user wants to sync contains photos or other media.

**Comment by AndyScherzinger** [comment]
You can create a custom folder in the auto upload screen for such a folder (expert mode activated for pre version 3.5.0), while that would also not work for the subfolders.
