### ISSUE TITLE
Autoupload does not create new subfolders

### ISSUE THREAD

**Issue by ruslan-murzin** [nextcloud/android#3484]
### Actual behaviour
- When new subfolder creates in the folder used for Auto-upload (or in it's subfolder) with any content (file) - files from that new subfolder can not be uploaded because app can not create new subfolder on the server side. If create that subfolder on the server - Auto-upload works fine.

### Expected behaviour
- New subfolder should be created on the server.
 
### Steps to reproduce
1. Create new Auto-upload for a folder
2. Within that folder create subfolder and add to the subfolder any file.
3. New subfolder doesn't created, upload fails with a reason "Connection error".

### Environment data
Android version: 6.0

Device model: Meizu M3 Max

Stock or customized system: Stock

Nextcloud app version: 3.4.2 RC2

Nextcloud server version: 15.0.2

#### Web server error log
```
37.99.39.222 - ruslan [21/Jan/2019:21:23:12 +0600] "GET /ocs/v1.php/cloud/user?format=json HTTP/1.1" 200 583 "-" "Mozilla/5.0 (Android) ownCloud-android/3.4.2 RC2"
37.99.39.222 - ruslan [21/Jan/2019:21:23:12 +0600] "GET /index.php/avatar/ruslan/384 HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Android) ownCloud-android/3.4.2 RC2"
37.99.39.222 - ruslan [21/Jan/2019:21:23:13 +0600] "GET /index.php/204 HTTP/1.1" 204 0 "-" "Mozilla/5.0 (Android) ownCloud-android/3.4.2 RC2"
37.99.39.222 - ruslan [21/Jan/2019:21:24:15 +0600] "PUT /remote.php/webdav/Temp/NextCloud%20sync%20test//NewFolder/1547290024131.jpg-chunking-2025223250-2-0 HTTP/1.1" 499 0 "-" "Mozilla/5.0 (Android) ownCloud-android/3.4.2 RC2"
```

#### Nextcloud log (data/nextcloud.log)
File does not exist. I found 2 log files in a different location but last records were made few days ago.

### Additional info
It's very much like this bug report: https://github.com/nextcloud/android/issues/2272

**Comment by AndyScherzinger** [comment]
@mario @tobiasKaminsky can you have a look at this. Afaik this is by design while it should be discussed if this shouldn't be working arbitrary.

**Comment by tobiasKaminsky** [comment]
I tried it with my emulator and latest 3.4.2 and it worked:
- set auto upload to a new folder
- enabled "use subfolder
- took one image
- 2019/01 in new folder was created 
- file was uploaded

Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky it's the other way around, mark a folder for auto upload and create a subfolder in there with files. That subfolder won't be detected, created and uploaded. Imho this is the issue described here: no auto upload for arbitrary folder hierarchies.

**Comment by tobiasKaminsky** [comment]
Ahh, right.
We have a similar issue somewhere.
I do not know if this is possible, but to solve this we can simply recursively watch that folder and upload everything?
At least I think that user will expect this?

**Comment by AndyScherzinger** [comment]
Yes I think that would be the best option (at least for custom folders). We could do the same for non-custom folders while that needs further discussions since that might be more complex to do to make it fail save and easy to use for the users.

And yes, for a custom folder I would expect this (also for any kind of media folder while that needs further investigation on how to implement that, see other issues where this has been discussed for burst mode pixel phone behavior etc.)

**Comment by AndyScherzinger** [comment]
I know but if working in an arbitrary way this one should then upload any file and folder created within DCIM and that needs further specification on how to handle this and its scenarios.

**Comment by ruslan-murzin** [comment]
At the moment Android app already tries to upload all new folders (as I understand, or at least all files in selected folder and it's subfolders) but can not do it if subfolder (where new file located) does not exist on the server folders structure.

**Comment by tobiasKaminsky** [comment]
How deep are those folders that need to be created?
Can you post the (maybe anonymized) folder path here, e. /Images/InstantUpload/Camera/2019/01?

**Comment by OlivierS1** [comment]
@tobiasKaminsky, 
/Images/InstantUpload_Xxxxxxx/Camera/2019/01

Nothing different than what was already there. I have used this since 2016 in the same exact setup.
It just broken with this release or the release before, but last month seems to have been fine.

**Comment by tobiasKaminsky** [comment]
So, I created
"Images/InstantUpload_xxx/Camera"

Then I changed my autoupload to this and enabled "use subfolders"
On next image, 2019/01 was created and the image was uploaded fine.

Which server do you use?
We did not changed anything in regard of AutoUpload for quite some time…

**Comment by ruslan-murzin** [comment]
> So, I created
> "Images/InstantUpload_xxx/Camera"
> 
> Then I changed my autoupload to this and enabled "use subfolders"
> On next image, 2019/01 was created and the image was uploaded fine.
> 
> Which server do you use?
> We did not changed anything in regard of AutoUpload for quite some time…

I have never talked about "Use subfolders" option. As I wrote in the header, this issue seems to me very similar to the issue with "Use subfolders" option, which you fixed 10 months ago (see https://github.com/nextcloud/android/issues/2272). It's similar to that issue because app can't upload files if destination folder does not exist. So I'm talking about situation when withing source folder some app/user creates new subfolder. And new files withing this new subfolder (which does not exist in the destination folder) can not be uploaded.

**Comment by tobiasKaminsky** [comment]
> So I'm talking about situation when withing source folder some app/user creates new subfolder. And new files withing this new subfolder (which does not exist in the destination folder) can not be uploaded.

Do I understand you correct that the subfolders do not exist on server?
This is exactly what I tried and described above:
- created Images/InstantUpload_xxx/Camera
- no subfolders in it
- auto upload a file
- app created Images/InstantUpload_xxx/Camera/2019/01 and uploaded file into it

**Comment by tobiasKaminsky** [comment]
No I get it, :+1:

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger I remember another issue where this was discussed.
Do we want this to be the default behaviour?

**Comment by OlivierS1** [comment]
> 
> 
> > So I'm talking about situation when withing source folder some app/user creates new subfolder. And new files withing this new subfolder (which does not exist in the destination folder) can not be uploaded.
> 
> Do I understand you correct that the subfolders do not exist on server?
> This is exactly what I tried and described above:
> 
>     * created Images/InstantUpload_xxx/Camera
> 
>     * no subfolders in it
> 
>     * auto upload a file
> 
>     * app created Images/InstantUpload_xxx/Camera/2019/01 and uploaded file into it

For my case, I haven't changed how "Autoupload" is setup, but its setting is to create the subfolder broken down with the year and the month.
The phone was actually trying to upload the same image over and over, but didn't noticed the error reported was related to "Folder error".
I went to the server NC 14.0.4 or 14.0.6 at the time and created the "01" folder there. As soon as it was created, the file was able to upload without issues.

**Comment by tobiasKaminsky** [comment]
is this still happening? As I remember that we enhanced this over the last versions…?

**Comment by siccovansas** [comment]
@tobiasKaminsky I replicated this issue (added a new folder in an auto upload folder and added an image in the new folder) and the folder and image are successfully detected and uploaded. So this issue seems to be fixed to me :)!

**Comment by MetalNeo** [comment]
I am still running into this issue. Creating a new folder within a folder that is already marked as Auto Upload and adding a file to it prompts for the user to configure the new folder individually, instead of automatically uploading it as a subfolder of the original folder.

Android version: 11

Device model: Oneplus 5

Stock or customized system: MicroG for LineageOS 18.1

Nextcloud app version: 3.15.1

Nextcloud server version: 21.0.1
