### ISSUE TITLE
switching to a different app while checking activities causes a spinning wheel displayed on return

### ISSUE THREAD

**Issue by j-ed** [nextcloud/android#3488]
### Actual behaviour
If you've checked the latest activities in your Nextcloud app, switch to a different app and return to the Nextcloud app afterwards, the activities tab is still selected but an infinite spinning wheel is shown instead of the available activities.

### Expected behaviour
The available activities should directly be shown under the activities tab, independently if you've switched to a different app in-between.
 
### Steps to reproduce
1. Open the Nextcloud app on your mobile device and check the displayed activity.
2. Switch to a different app.
3. Return to the Nextcloud app on your mobile device, in which the activities tab is still selected.
-> You should see an infinite spinning wheel instead of the available activities.

### Environment data
Android version: 8.0
Device model: Samsung Galaxy S7
Stock or customized system: Stock ROM
Nextcloud app version: 3.4.2
Nextcloud server version: 15.0.2

#### Web server error log
```
No error messages were logged.
```

#### Nextcloud log (data/nextcloud.log)
```
No error messages were logged.
```

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky I think I meantioned this before, it seems stuff is done in onResume() or some message bus magic since rotating the screen has the exact same effect.
