### ISSUE TITLE
Technical cleanup: Parceler: Reflection is required to access private field: String extension, consider using non-private.	

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#3491]
The classes `Template` and `SearchEvent` throw this compiler warning several time, so for housekeeping reasons we should simply change this accordingly + then set this to ignore for codacy's checks.

cc @tobiasKaminsky for approval

**Comment by tobiasKaminsky** [comment]
Yeah, let us do this :+1: 
Though I do not really like it, but it seems that this is the way parceler is handling it.
