### ISSUE TITLE
NC 15.0.2 / Android client 3.4.1 / Collabora 4 - backspace key not working

### ISSUE THREAD

**Issue by himpierre** [nextcloud/android#3492]
Hello Devs.

Currently it seems the backspace key is not working when editing a collabora document with the android app. Everything else i tested works. Even tried the dev version to no avail.

thanks and cheers
t.

**Comment by tobiasKaminsky** [comment]
I tried it with a test version (4.0.0 (git hash: f4e0e748)), and there it is working fine with my emulator and a OnePlus3.
Here it works. 
I'll try to ask the Collabora guys to see if they know that kind of issue.

Are you using some kind of a custom keyboard or hardware keyboard? Which device do you tested with?

**Comment by himpierre** [comment]
Good to know it works in generell. I'm using LineageOS 14.1 (Nougat) with the integrated keyboard. No fancy stuff. Collabora 4.0.0 (git hash: 173510f).

**Comment by thebearon** [comment]
Works here as well on a Samsung tablet as well. Which browser are you using? What's the keyboard installed in device settings? Is there some kind of IME enabled for it?

**Comment by himpierre** [comment]
In generell the backspace key works. Email, Browser, Notes, you name it. Even the nextcloud app itself works. Creating a folder and use backspace to correct the name works. Only when editing with collabora the backspace key does not work within the android app. I'm not talking about the browser.

**Comment by thebearon** [comment]
Do you have further details about the keyboard settings?

**Comment by himpierre** [comment]
Nothing special. Plain Android AOSP Keyboard.

**Comment by himpierre** [comment]
@tobiasKaminsky Did you have the chance to talk to the collabora people? having the very same problem on different android phone with different android releases. Now running NC 15.0.4 / Richdocuments 3.2.1 (git version because of the spinning circle bug introduced with 3.2.0) and Android 3.5.0 RC4.

**Comment by tobiasKaminsky** [comment]
I forgot to keep you updated, sorry.

According to the cool guys, this should have been fixed with https://cgit.freedesktop.org/libreoffice/online/commit/?id=42823fcafb89bb854036fe09bbc6281ac50189c9, but it seems not be fixed in all cases.

Such a bug should be created it https://bugs.documentfoundation.org with "LibreOffice Online" as component, according to them.
Please do this and post a reference to this issue, so if we need to do something on our side, we get informed.

**Comment by himpierre** [comment]
Thanks @tobiasKaminsky 

For reference: https://bugs.documentfoundation.org/show_bug.cgi?id=123437
