### ISSUE TITLE
Exception on trying to manage account on deleted server

### ISSUE THREAD

**Issue by rwhector** [nextcloud/android#3493]
I've deleted my old server, including deleting the hostname from DNS.
When I tried to manage the account in order to delete it, I got an exception - something about an unknown host, I think, but I can't recheck it.
I was given the suggestion to delete the account via Android's account management, which worked.
I'm using the Nextcloud app version 3.4.1, from Fdroid.

**Comment by tobiasKaminsky** [comment]
I tried it, and I can remove the account.
But if you got to account details, the app tries to fetch user infos, like name, address, … and this fails due to "unknown host".
Nevertheless you can remove the account from within the app, therefore closing.
