### ISSUE TITLE
Video streaming stops after minutes of playback

### ISSUE THREAD

**Issue by fernandocollova** [nextcloud/android#3494]
### Actual behavior

Videos stop playing after around 4 minutes of streming with the internal player.

### Expected behavior

Videos should play until they end.
 
### Steps to reproduce

- Browse to a video file to play
- Tap on it to start playing
- See it play for around 4 minutes
- Get an error message along the lines of "The media file can't be read" (Or, in Spanish, "No fue posible leer el archivo de medios"

### Environment data

Android version: 8.1.0

Device model: Axon 7

Stock or customized system: Lineage for microG

Nextcloud app version: 4.3.1

Nextcloud server version: 15.0.2, from the Docker image tag `15.0-apache`

### Some extra info

I'm experiencing this bug on 2 devices with the same Lineage version: a ZTE Axon 7 and a Xperia Tablet Z WiFi. The logs I attached are from playing an 840MB MP4 file on the Axon 7, but the original problem was playing a 1.2GB MKV file on the Xperia Tablet, which lead me to try with different files, all encoded in (according to VLC) `H264 - MPEG-4 AVC (part 10) (avc1)` with `MPEG AAC Audio (mp4a)` at 48Khz and 32bits, but varying the resolution and size, in both the internal player and the one bundled with android, with no success.

However, VLC seems to work just fine, and also, I successfully streamed many other smaller videos, which, besides being around 70MB only, they were only different in audio sampling: They were at 44.1Khz instead of 48Khz, and the rest was the same. Don't know if it's relevant however.

Regarding the logcat, I just removed what seemed like sensitive info in line 256, but besides that, I wasn't really sure what part of the logcat could be important, so I dumped every log line during the whole 3 minutes of playback to the attached file... Sorry for that :/ but it seemed like the best option.

[nextcloud_server_logs.txt](https://github.com/nextcloud/android/files/2794357/nextcloud_server_logs.txt)

[nextcloud_app_logs.txt](https://github.com/nextcloud/android/files/2794359/nextcloud_app_logs.txt)

**Comment by tobiasKaminsky** [comment]
@rullzer do you have an idea, if this is related to server? 
In log it says that "EOS" was detected, which is "end of stream" I assume.

**Comment by rullzer** [comment]
No idea. Does this happen for all files? I just streamed a 10 minute video without issues....

**Comment by fernandocollova** [comment]
It happens on most files. Maybe I wasn't specific enough with the extra info, but the data in the bug report is for one file, that crashed in around four minutes. However, the one I called the "Original problem" the MKV file playing on the Xperia tablet, played for a little less than 30 minutes one time, and more ore less 10 minutes on a second try.

There is also the case I mentioned about the 70MB files, that are 20 minutes long give or take, and they play without issues consistently.

Thanks, Fernando

**Comment by fernandocollova** [comment]
Hi, me again with a more concrete example of this.

This is a 11 second video the Nexctcloud app auto uploaded after it was taken. Here, when I open the video, you can see it loading up until 80% more or less, and, do nothing after.

![screenshot_20190204-122127_nextcloud](https://user-images.githubusercontent.com/4233438/52300268-33902b00-2966-11e9-9a20-393b08340590.png)

I'm attaching the [lserver logs](https://github.com/nextcloud/android/files/2833609/logcat.txt), and the [phone's logcat](https://github.com/nextcloud/android/files/2833610/server_logs.txt), and here is a [link to the video](https://fernandocollova.com/nextcloud/s/6PZ77nkqq9sM6L7) in case it helps debugging.

Thanks, Fernando

**Comment by tobiasKaminsky** [comment]
Is it working in an external app, e.g. vlc? To exclude server as a cause?

**Comment by fernandocollova** [comment]
VLC can play the video, but I don't think is streaming it.

You can't see the difference that much with this video, but with any longer video, when I tap in the three dots menu, and I select the option to play with an external player, it's "loading" for a long time, and then it plays with instant seek and rewind. And I never had such a speedy response with Samba or anything I've used in the past over wired or wireless networks, so I'd bet it's downloading it and playing it.

What is playing and actually steaming (for the formats it supports at least, which is not this video) is the web video player. That one works perfect every time.

**Comment by fernandocollova** [comment]
VLC can play the video, but I don't think is streaming it.

You can't see the difference that much with this video, but with any longer video, when I tap in the three dots menu, and I select the option to play with an external player, it's "loading" for a long time, and then it plays with instant seek and rewind. And I never had such a speedy response with Samba or anything I've used in the past over wired or wireless networks, so I'd bet it's downloading it and playing it.

What is playing and actually steaming (for the formats it supports at least, which is not this video) is the web video player. That one works perfect every time.

**Comment by fernandocollova** [comment]
Hi again

Just passing by to say that I rechecked this bug on the ZTE phone after upgrading the server to `15.0.5` and the app to `3.5` and the bug still happens.

Thanks, Fernando

**Comment by luntik2012** [comment]
the same on desktop firefox and android firefox (stops after first second)
