### ISSUE TITLE
Warn if app was not installed in 'internal storage'

### ISSUE THREAD

**Issue by bertwesarg** [nextcloud/android#3495]
### Is your feature request related to a problem? Please describe.
See #63 and #2595: If app was not installed into the 'internal storage' than the login credentials are lost every reboot of the phone. The consent is, that the OS should not be allowed to install the app into the external storage, but vendors may ignore this request. In my case its Nokia 3 with Android 8.1.

### Describe the solution you'd like
Maybe it is at least possible that the app itself can issue a warning to the user, that it was not installed in the internal storage.

### Describe alternatives you've considered
None known to me.

**Comment by phu9Suop** [comment]
Correct procedure is to assure installation in internal storage. 
Without exception and instantly and immediately at the time of installation and upgrade. 
Is straight thinking so difficult?

**Comment by ezaquarii** [comment]
You can set a special flag in manifest, disallowing moving the app to external storage.

The loss of functionality should be minimal, considering that it doesn't work anyway.

**Comment by AndyScherzinger** [comment]
That has already been set see: https://github.com/nextcloud/android/blob/master/src/main/AndroidManifest.xml#L86 so the app's installation (via manifest) is theoretically enforced to be installed on internal memory only while @tobiasKaminsky's comment remains true, (some) OEMs trick Android and we can't do anything about that... 

So comment on the offensive yet wrong comment... yes thinking straight is easy while OEMs manipulating how Android works which is the platform the app rans on top...not so much.

**Comment by ezaquarii** [comment]
@AndyScherzinger Hm... in that case I'm out of ideas and I guess it's not our bug then. :-)

**Comment by joshtrichards** [comment]
As noted we already do this. Can't do much if the underlying OEM opts to both ignore what is *already* Android's default behavior *and* our declaration making it explicit. 

Given paths faked/etc we can't reliably detect this. I also hope this has become less come four years later.
