### ISSUE TITLE
Feature request: Default to keeping local copy on android

### ISSUE THREAD

**Issue by stratus-ss** [nextcloud/android#350]
### Actual behaviour
-by default the upload function removes the local copy

### Desired behaviour
-Have an option or set the default to preserve the local file
 
### Steps to reproduce
1. Open the app
2. Click the upload button
3. select file
4. Observe the file has been removed

### Environment data
Android version:
7

Device model: 
Nexus 5X

Stock or customized system:
Stock

Nextcloud app version:

1.3.1

Nextcloud server version:

10.0.1

I have been using Owncloud since version 4 and nextcloud since V 9. The expected behaviour because of previous apps (Owncloud) is that the local version gets preserved. When I am in a hurry and I am pushing an edited photo to NextCloud server, I don't always remember that the default is to remove the picture from the phone. This results in extra bandwidth usage on the phone as I have to pull the picture back down after I am done uploading it.

Please allow an option to select the default behaviour when uploading a file

**Comment by tobiasKaminsky** [comment]
In 1.3.1 you have a dropdown menu to switch between the three options.
The last option will be remembered. (the option will not be remembered if you choose an option and then press cancel).
I have checked it, the default should be "keep file in source folder".

**Comment by stratus-ss** [comment]
@tobiasKaminsky at least for me it does has not remembered this in the past. What version was this implemented on? 

Perhaps I will try uninstalling and reinstalling the application. I have noted that this is not the case when I have powered off the phone and back on.

**Comment by tobiasKaminsky** [comment]
1.3.0 I guess. 
It should be remembered in any case, strange...

**Comment by stratus-ss** [comment]
While the drop down is definitely handy, why is the default choice to delete the local copy? I would think that this is not the best default choice

I purged the application and can confirm that 1.3.1 does seem to remember the setting now.

If you believe that you have the correct defaults you can close this

**Comment by AndyScherzinger** [comment]
AFAIK the initial default has been implemented as "just upload"
