### ISSUE TITLE
android client cannot login on self hosted server installed on subdirectory

### ISSUE THREAD

**Issue by kcris** [nextcloud/android#3501]
### Actual behaviour
- I am hosting my own server on a subdirectory (not a subdomain)
https://docs.nextcloud.com/server/13/admin_manual/configuration_server/reverse_proxy_configuration.html#overwrite-parameters
- I can connect to my server from a pc, no issues whatsoever
- from android client, when I enter the server url  myserver/nextcloud, I get the error: "Wrong username or password"

### Expected behaviour
- I should be able to access my own server from android via the official client (same way I access it from a pc, via the browser)
 
### Steps to reproduce
1. open android client
2. enter server url:  https://myserver/nextcloud or myserver/nextcloud

### Environment data
Android version:
8

Nextcloud app version:
3.4.2

Nextcloud server version:
15.0.2

**Comment by tobiasKaminsky** [comment]
Can you create us a test account, test if the problem occurs also there and if so send the credentials to tobias at nextcloud dot com with a reference to this issue?

**Comment by kcris** [comment]
Hi,

sure, I will. Where to send them in private?

thanks
Chris

**Comment by kcris** [comment]
sorry, i see the email adress now, I'll get send them today

**Comment by kcris** [comment]
Tobias, thanks a lot for taking the time to help me.

I just checked (on my Android 8.0) using the latest beta client - version 3.5.0. RC1... and problem is solved.
Everything works in the latest beta. So I can't wait the next release of the android client :)
Thank you!
