### ISSUE TITLE
Rename DAVdroid to DAVx⁵ (DAVdroid) in settings screen

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#3502]
DAVdroid got renamed due to naming issue with Android and is now called DAVx⁵.
So at some point we should also do this change. Question is:
* do it know right before the 3.5.0 release (will remove all existing translations we have for it today). 
* do it right after the 3.5.0 stable release while that means it'll take another 2+ month until this changes is publishes
* do it after we created the table branch and manually do this change to the stable branch?

What do you think @tobiasKaminsky ?

**Comment by nickvergessen** [comment]
I vote for asap, because people get confused.

**Comment by AndyScherzinger** [comment]
I also vote for asap while I'd go for "DAVx⁵ (DAVdroid)" for now to not confused anybody.

**Comment by AndyScherzinger** [comment]
DONE: #3504

**Comment by pjrobertson** [comment]
Just thought I'd head over here and say I think you guys made the right decision doing this ASAP. I was already confused with the precious wording, but after the 3.5.0 upgrade it's much clearer.

Thanks for all the hard word, from a happy user!
