### ISSUE TITLE
Icon in push notifications is in the wrong color

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/android#3503]
### Actual behaviour
Icon is red

### Expected behaviour
Icon should be blue
 
### Steps to reproduce
1. Set up one account with blue theming
2. Set up another account with red theming
3. Browse the red files
4. Receive a push notification for blue
5. Check the color of the icon in the notification.

### Environment data
Android version: 9 - January update

Device model: Xiaomi Mi A1

Stock or customized system: Stock (Android One)

Nextcloud app version: 3.4.2

Nextcloud server version: 15.0.2

**Comment by tobiasKaminsky** [comment]
Thank you for the detailed step to reproduce
