### ISSUE TITLE
Upload problem (but problem solved after having renamed the specific file)

### ISSUE THREAD

**Issue by Wikinaut** [nextcloud/android#353]
I noticed again an upload problem. ("upload failed" (Hochladen fehlgeschlagen) for file xxxx.jpg).

Server:
- owncloud 9.0.x and Nextcloud 10.0.1
- PHP 7.0.12 
- debian 8

Client:
- Android Nextcloud client 1.3.1

Also, deleting a previously uploaded version of the file on the server does not help.

However, when I rename the file on the Android, I **can** upload it.

What can be the reason for this behaviour ?

**Comment by Wikinaut** [comment]
Logifle shows 

```
Exception: {"Message":"HTTP\/1.1 404 File with name SofortUpload\/xxxx.jpg could not be located","....
```

**Comment by iskradelta** [comment]
Hi,

Can you try the "Nextcloud beta" app? The problem should be fixed there, at least upload retries should succeed.

The 404 error message, is not per se an error, it means the android client asked "Is this file already there", and 404 means "Nope, doesnt exist", which is fine.

**Comment by Wikinaut** [comment]
@iskradelta There is no such "Nextcloud beta" (in Google Play Appstore).

**Comment by AndyScherzinger** [comment]
Hi @Wikinaut the beta is only available via f-droid: https://f-droid.org/repository/browse/?fdfilter=com.nextcloud&fdid=com.nextcloud.android.beta

**Comment by Wikinaut** [comment]
@AndyScherzinger alternatively, I can build it. General question: is the master branch recommend as the "bleeding" (and working) edge, or is master not recommended and I better shall build "beta" ?

**Comment by Wikinaut** [comment]
@AndyScherzinger Building has the charme, that I can help the project (like I did for ownCloud).

**Comment by AndyScherzinger** [comment]
Hi @Wikinaut both are fine ;) The master is basically the stable branch, so it contains the latest release + any changes that will be shipped with the next stable release (and release candidates) so the master is very stable. Leading edge is the beta branch, that one is also working and always contains the latest beta release. The beta release is basically any PR that has reached the stage "3. to review" and is considered feature complete. The advantage of the beta is "new features" so if youo want to test drive stuff that one is the way to go. If you want to hunt down a bug happening on the stable release, then the master is the way to go.

Remark: Both can be installed in parallel! :rocket:

**Comment by jancborchardt** [comment]
@AndyScherzinger done :)

**Comment by Wikinaut** [comment]
(my last action with ownCloud Android was the addition of code for showing certificate's fingerprints in several formats, when a new account is added.... a view for already added accounts should be added, but this if off-topic here...(pls don't answer. I just wanted to let you know.)

**Comment by AndyScherzinger** [comment]
@Wikinaut I know, that is why asked for you to be added to the Nextcloud organization :)

**Comment by AndyScherzinger** [comment]
@jancborchardt without wanting to spam this thread, can you please add @iskradelta also? :smiley: :+1:

**Comment by Wikinaut** [comment]
I am closing this, but perhaps reopening with a more specific title, because the upload problem looks to be a "Re-upload a SofortUpload-ed image fails" issue.
