### ISSUE TITLE
[3.5.0 RC1] Actions in notifications look weird

### ISSUE THREAD

**Issue by rullzer** [nextcloud/android#3533]
![screenshot_nextcloud_20190130-202930](https://user-images.githubusercontent.com/45821/52007122-1e328100-24ce-11e9-98d8-4edd7a4960ef.png)

Those action buttons are styled in similar way to the other buttons. Only I feel there is some significant spacing missing here ;)

@tobiasKaminsky @AndyScherzinger

**Comment by tobiasKaminsky** [comment]
This looks even more strange on custom theming:
![2019-01-31-082126](https://user-images.githubusercontent.com/5836855/52038934-7ea7d980-2533-11e9-9fae-e265847d9e6a.png)

**Comment by AndyScherzinger** [comment]
like @rullzer said we seem to neither have any padding nor margin set...
Since the buttons are created programatically so we might also need to set the theme value (if possible) :/

**Comment by tobiasKaminsky** [comment]
![2019-01-31-125525](https://user-images.githubusercontent.com/5836855/52052701-7e213a00-2557-11e9-9188-9ed2fcc12191.png)

Thanks to @mario.

I guess this is okay now?

**Comment by AndyScherzinger** [comment]
Whitespace between the button and the notification text seems to be too large, padding inside the button needs to be way larger.

**Comment by tobiasKaminsky** [comment]
![2019-01-31-125525](https://user-images.githubusercontent.com/5836855/52052701-7e213a00-2557-11e9-9188-9ed2fcc12191.png) ![2019-01-31-135459](https://user-images.githubusercontent.com/5836855/52055483-d4927680-255f-11e9-9d5c-e5aab5850ff7.png)

**Comment by AndyScherzinger** [comment]
Looks better, might still need some more padding, grey is likely EEEEEE or E0E0E0, button text should be bold, secondary button's text color should be the primary color. 
Just compare it to the file picker screens :)

**Comment by tobiasKaminsky** [comment]
Thanks for the design input!
Let us continue over here: #3537, I'll add it soon.
