### ISSUE TITLE
Opening PDF document on the phone delete the file if no internet connection present.

### ISSUE THREAD

**Issue by OlivierS1** [nextcloud/android#3535]
### Actual behaviour
- Tell us what happens:
When I am trying to read a PDF document from within Nextcloud which has been already downloaded on the phone, trying to open the file when the phone doesn't have internet connection will cause the PDF document to be deleted from the folder it resides.

### Expected behaviour
- Tell us what should happen:
Nextcloud would normally ask the server if the file on the phone is the latest one. In absence of internet connection, the operation would proceed to having the document opened from the phone and not being deleted.
 
### Steps to reproduce
1. With internet (wifi) connection enabled, download a PDF document.
2. Disable internet (wifi) connection on the phone.
3. Open file from Nextcloud with Adobe reader or possibly default viewer.
4. Two messages are going to pop-up:
- Checking latest version of the file present on server...
- File doesn't exist....
Adobe will close and the PDF document will be removed from the phone.

### Environment data
Android version: 4.4

Device model: Samsung Galaxy S III

Stock or customized system: Stock

Nextcloud app version:
3.5.0.RC1

Nextcloud server version:
14.6 and 15.2

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
No longer showing the "LOG" option within Nextcloud app.

Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Thank you for your detailed steps, I found the issue and it will be fixed in RC2.
