### ISSUE TITLE
Android app tries to connect to wrong OCS endpoint

### ISSUE THREAD

**Issue by rullzer** [nextcloud/android#354]
See: https://github.com/nextcloud/server/pull/1861

Basically when setting up a new account in the app it connects to `/index.php/ocs/cloud/user?format=json`

This might have worked for dark hackery reasons in the past. But this is not the valid OCS endpoint.

It should be ``/ocs/v2.php/cloud/user?format=json` (note that you need to send the `OCS-APIREQUEST: true` header.

Basically this does no longer work in NC11 because we moved OCS to the appframework.

**Comment by Spacefish** [comment]
thanks for fixing this.. gave me headaches, i couldn´t use the app for aprox.. a month due to this..

**Comment by AndyScherzinger** [comment]
https://github.com/nextcloud/android-library/pull/21

This has been fixed and will be part of the next stable. We moved to v1 though, not v2 due to the discussions there.

**Comment by AndyScherzinger** [comment]
It is already available in the beta app :)

**Comment by rullzer** [comment]
OK lets me close then!
@AndyScherzinger which discussion?

**Comment by rullzer** [comment]
Ah found it.
Yeah using v1 is fine as well. V2 is available already in NC9 so the nextcloud client could jump. But that is for another time.

Awesome it is already fixed!

**Comment by AndyScherzinger** [comment]
Sweet! Yeah, had the route discussion at the NC conference Hackweek with @MorrisJobke :+1:
