### ISSUE TITLE
Unknown mime-Type for .msg Files

### ISSUE THREAD

**Issue by katuss** [nextcloud/android#3543]
### Actual behaviour
- When I open a .msg file with any MSG viewer it works fine. But as soon as I open the Nextcloud Android App with the "open with" function I use the Viewer App was not listed. 

### Expected behaviour
- in the nextcloud android app I open a .msg file. I use Open with > Viewer App > Done

### Steps to reproduce
1. Download Android NC App & and any .msg file compatible viewer app. as example: https://play.google.com/store/apps/details?id=com.sharpened.androidfileviewer
2. try to open a .msg file from the nextcloud app. 

3. try to open a .msg file from the viewer app.

### Environment data
Android version: 8.0 / 8.1 / 9

Device model: SM-A530x / SM-G39F / BKL-L09

Stock or customized system: Manufacturer unchanged (Samsung / Huawei)

Nextcloud app version: 3.4.2

Nextcloud server version: 14.0.6

### Answer from a Fileviewer Dev Support: 
The reason for this issue is technical and has to do with the source app you’re trying to open the .msg files from.  A short explanation is below.  We are working on a solution for this for a future version of File Viewer for Android.

If the app you’re trying to open the file from asks to open an “application/vnd.ms-outlook” file, then File Viewer will be shown as an open option because this is the correct MIME type for the file.  However, it’s more likely that your app is requesting that a generic “application/octet-stream” byte stream be opened because it does not correctly identify the MIME type.  In this case, File Viewer does not display as an open option because “application/octet-stream” is not specific.

**Comment by tobiasKaminsky** [comment]
We are relying on Android to detect the correct mimetype:
https://github.com/nextcloud/android/blob/5d641b4e32448f747dac655fc8d6be913292c858/src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java#L354

But this fails for "msg" and thus it is opened by any app that can handle octet-stream.
While we could try to mantain our own mimetype map, the main fix would be that Android can detect msg properly…

**Comment by katuss** [comment]
I also reported the problem to Google issuetracker. 
https://issuetracker.google.com/issues/123737754


I hope this gets fixed fast. 
In the meantime I am grateful for suggestions and workarounds.

**Comment by 15characterlimi** [comment]
I've commented on your bug on the Google issue tracker too, but basically I don't think it's clear why you need any change of Android's behavior at all. If you want to recognize files with a particular extension then why are you trying to recognize them by MIME type rather than by that extension?

Also, you haven't specified *which* MIME type you consider to be correct for .msg files and why you consider that to be correct. An RFC would be great, but I couldn't find an RFC that specified a correct MIME type for .msg files. Upstream mime-support also doesn't have a mapping for .msg files:
https://salsa.debian.org/debian/mime-support/blob/master/mime.types

**Comment by tobiasKaminsky** [comment]
> My understanding is that it should be sufficient to use the file extension to recognize those files.

We are doing this, but as said Android does not handle .msg. So we (and maybe hundreds of other apps) need to handle this on their own.

**Comment by tobiasKaminsky** [comment]
Can you give this a try? 
This is working for me with latest NC app and Android 10.

**Comment by AndyScherzinger** [comment]
Also tested it with Android 9 and working jsut fine offering the mentioned app for .msg files. So closing the issue. Please feel free to comment and re-open in case the issue persists.
