### ISSUE TITLE
Photo upload runs only when charging

### ISSUE THREAD

**Issue by kotecky** [nextcloud/android#3553]
Auto upload of photos works only when charging despite the settings (not checked) and the granted exception from battery-saving (phone). When charging starts, the auto upload starts immediately.

Related to old #300 and #355. 
3.5.0 RC1, I do not have access to server logs. 
Sony Xperia X Compact, Android 8. 0

**Comment by tobiasKaminsky** [comment]
Can this maybe related to some sort of battery saving optimization on your phone?

**Comment by kotecky** [comment]
Tobias, 
it does. But the application has an exception. So I am wondering whether the application correctly interprets the state that the phone is in. I will test things if needed, just need a hint on what should be tested. 

(The #3569 seems to share the same symptoms.)

**Comment by tobiasKaminsky** [comment]
> I will test things if needed, just need a hint on what should be tested.

Thanks for the offer, unfortunately I also do not have a clue, where to start…

Do you see the uploads in the upload queue?

**Comment by kotecky** [comment]
Indeed, they are in the queue and saying that they wait for the battery saving regime to end. Sony calls that regime Stamina. When disabling the regime, the photos get uploaded immediately. So it seems that the app does not know that it has an exception from the regime.

**Comment by tobiasKaminsky** [comment]
We rely hier on Android's PowerManager.isPowerSaveMode(context) method.
But I found a way to detect if the app is whitelisted.

@kotecky I can create you a test apk file, which you can simply install (and it will be upgraded to next stable release automatically).
Would you try it?

**Comment by kotecky** [comment]
@tobiasKaminsky yes, I will. Let me know.

**Comment by AndyScherzinger** [comment]
As per discussion with @tobiasKaminsky on irc:

> power save mode and battery optimization setting are 2 very different things that should not be mixed, nevertheless we need to detect such scenarios as mentionede above since the app itself can't do much about it, it is rather an OEM bug where there is no real work around.

So the solution discusse dis to dected such a situation and inform the user about it within the app.
On the file list screen check:
1. Any Folder configured _and_ active for Auto Upload
2. Any file queued for upload with status "waiting for battery"
3. Battery optimization active
4. App not excluded from battery optimization

If all these rules apply then show a popup, mentioning the situation (blocked auto uploads) and offering a possible solution (refer to batetry optimization / whitelist). 

Another possibility would also be some kind of a "force upload now" where we then update the queued entries to "createdByUser" which is basically a "ignore energy related OS settings" (This needs to be discussed...)
