### ISSUE TITLE
Option to disable chunked uploads

### ISSUE THREAD

**Issue by Hansa064** [nextcloud/android#3554]
### Is your feature request related to a problem? Please describe.
I create daily backups of my signal account. They are ~500MB each and I've setup the backup folder to be automatically synced with my own nextcloud server. Everything works this far, but I notice really slow (~500kb/s) upload speeds for this large files. For small files, like images, everything works fine.
When I upload the same file from my PC I get full upload speed (~10MB/s).
Now I've seen, that in 3.5 RC1 something has changed in the cod for chunked uploads (e.g. https://github.com/nextcloud/android/pull/3464) which should fix this kind of problems as mentioned e.g. in https://github.com/nextcloud/android/issues/1238.

But after testing nothing changed. I still only get around 500kb/s upload speed.

### Describe the solution you'd like
I downloaded the code, commented out the part about chunked uploads in the `UploadFileOperation.java` file and tested it for myself. And now I also get full upload speed as well!

Thus, I vote for removing the chunked upload logic at all. I don't get it anyway, at least for me, they arn't resumed anyway, thus, there is no need to chunk the upload, isn't it?

If not removing this option, at least, there should be an option to disable it IMHO.

**Comment by tobiasKaminsky** [comment]
Chunked uploads are resumed, if the previous fails and you click on it in upload queue.
Reason for chunked uploads is to prevent client (maybe even via mobile data) to have re-upload the whole file, when only a small part on the end is missing.

The new chunked upload you mentioned detects if device is using wifi and then uses 10mb chunks, where the upload should be much faster, as there is fewer overhead.
On mobile connection it uses 1mb chunks.

Can you test/verify that 10mb chunks are used? onWifiConnection in ChunkedFileUploadRemoteOperation

**Comment by Hansa064** [comment]
I've tested again using the Nextcloud Dev version (20190201) from the F-Droid store. And I donno what I did wrong yesterday, but now, chunked upload is working and it's using 10MB chunks. Upload speed looks (mostly ok to me) falls down to 500kb/s for some chunks during upload, but that's okay. Might be connection related (bad WiFi at work). 

I'll close this issue and sorry for the inconvenience!
