### ISSUE TITLE
Make use of "new" material icons/style

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#3562]
To trigger a discussion...

With the latest material design changes there are also new icon styles like oulined and two-tone, see https://material.io/tools/icons/?style=outline for example.

Trend seems to be (when looking at most Google apps that have already been refreshed design-wise) to use the outlined ones.

So what do you think @nextcloud/designers @jancborchardt @tobiasKaminsky ?
Looking at the fact that on the webUI the icons are filled-style icons I can't say what would be the better choice and why.

**Comment by tobiasKaminsky** [comment]
I have no real opinion on that, only that given on available time, this might be not that important.
Icons that are related to Android can be changed.
Icons that are related to NC should(?) maybe remain

**Comment by AndyScherzinger** [comment]
> only that given on available time, this might be not that important.

I know while it is something I like to work on (UI stuff 😄) so it is kind of important to me :) As for the Nc icons non-existant in Android, I probably would re-create them in the styling that we choose _if_ we choose to go for a new icon style for Android.

**Comment by tobiasKaminsky** [comment]
Hehe, I know you do :-D
Of course it is fine for me, but please discuss this with @nextcloud/designers

**Comment by AndyScherzinger** [comment]
> Of course it is fine for me, but please discuss this with @nextcloud/designers

Of course! Which is why I mentioned them in the issue ❤️

**Comment by jancborchardt** [comment]
We should always use the filled icon version. :slightly_smiling_face: 
- All the Nextcloud icons are filled
- Filled icons are simpler shapes and easier to perceive
- Remember how iOS experimented with outlined icons and went back to filled? :wink:
