### ISSUE TITLE
Crash on start android 9

### ISSUE THREAD

**Issue by ictabc** [nextcloud/android#3565]
### Actual behaviour
- App starts and crashes

### Expected behaviour
- nextcloud screen??
 
### Steps to reproduce
1. Start app
2. crash
3. 

### Environment data
Android version: Latest android 9 jan 5

Device model: Pixel 3 XL

Stock or customized system: Stock

Nextcloud app version: Latest from app store

Nextcloud server version: 15.0.2

Tried removing app en reinstalling, clear cache/data etc. Still same problem.

### Logs

adb logcat:

02-04 06:05:48.738 6072 6072 E AndroidRuntime: FATAL EXCEPTION: main
02-04 06:05:48.738 6072 6072 E AndroidRuntime: Process: com.nextcloud.client, PID: 6072
02-04 06:05:48.738 6072 6072 E AndroidRuntime: java.lang.RuntimeException: Unable to create application com.owncloud.android.MainApp: android.database.sqlite.SQLiteException: duplicate column name: redirect (code 1 SQLITE_ERROR): , whil
e compiling: ALTER TABLE external_links ADD COLUMN redirect INTEGER
02-04 06:05:48.738 6072 6072 E AndroidRuntime: at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5925)
02-04 06:05:48.738 6072 6072 E AndroidRuntime: at android.app.ActivityThread.access$1100(ActivityThread.java:200)
02-04 06:05:48.738 6072 6072 E AndroidRuntime: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
02-04 06:05:48.738 6072 6072 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:106)
02-04 06:05:48.738 6072 6072 E AndroidRuntime: at android.os.Looper.loop(Looper.java:193)
02-04 06:05:48.738 6072 6072 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:6718)
02-04 06:05:48.738 6072 6072 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
02-04 06:05:48.738 6072 6072 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
02-04 06:05:48.738 6072 6072 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
02-04 06:05:48.738 6072 6072 E AndroidRuntime: Caused by: android.database.sqlite.SQLiteException: duplicate column name: redirect (code 1 SQLITE_ERROR): , while compiling: ALTER TABLE external_links ADD COLUMN redirect INTEGER
02-04 06:05:48.738 6072 6072 E AndroidRuntime: at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
02-04 06:05:48.738 6072 6072 E AndroidRuntime: at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:903)
02-04 06:05:48.738 6072 6072 E AndroidRuntime: at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:514)
02-04 06:05:48.738 6072 6072 E AndroidRuntime: at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
02-04 06:05:48.738 6072 6072 E AndroidRuntime: at android.database.sqlite.SQLiteProgram.(SQLiteProgram.java:58)
02-04 06:05:48.738 6072 6072 E AndroidRuntime: at android.database.sqlite.SQLiteStatement.(SQLiteStatement.java:31)
02-04 06:05:48.738 6072 6072 E AndroidRuntime: at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1770)
02-04 06:05:48.738 6072 6072 E AndroidRuntime: at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1698)
02-04 06:05:48.738 6072 6072 E AndroidRuntime: at com.owncloud.android.providers.FileContentProvider$DataBaseHelper.onUpgrade(FileContentProvider.java:1741)
02-04 06:05:48.738 6072 6072 E AndroidRuntime: at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:398)
02-04 06:05:48.738 6072 6072 E AndroidRuntime: at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:322)
02-04 06:05:48.738 6072 6072 E AndroidRuntime: at com.owncloud.android.providers.FileContentProvider.query(FileContentProvider.java:485)
02-04 06:05:48.738 6072 6072 E AndroidRuntime: at android.content.ContentProvider.query(ContentProvider.java:1057)
02-04 06:05:48.738 6072 6072 E AndroidRuntime: at android.content.ContentProvider.query(ContentProvider.java:1149)
02-04 06:05:48.738 6072 6072 E AndroidRuntime: at android.content.ContentProvider$Transport.query(ContentProvider.java:241)
02-04 06:05:48.738 6072 6072 E AndroidRuntime: at android.content.ContentResolver.query(ContentResolver.java:802)
02-04 06:05:48.738 6072 6072 E AndroidRuntime: at android.content.ContentResolver.query(ContentResolver.java:752)
02-04 06:05:48.738 6072 6072 E AndroidRuntime: at android.content.ContentResolver.query(ContentResolver.java:710)
02-04 06:05:48.738 6072 6072 E AndroidRuntime: at com.owncloud.android.datamodel.SyncedFolderProvider.getSyncedFolders(SyncedFolderProvider.java:105)
02-04 06:05:48.738 6072 6072 E AndroidRuntime: at com.owncloud.android.datamodel.SyncedFolderProvider.updateAutoUploadPaths(SyncedFolderProvider.java:246)
02-04 06:05:48.738 6072 6072 E AndroidRuntime: at com.owncloud.android.MainApp.updateAutoUploadEntries(MainApp.java:556)
02-04 06:05:48.738 6072 6072 E AndroidRuntime: at com.owncloud.android.MainApp.initSyncOperations(MainApp.java:299)
02-04 06:05:48.738 6072 6072 E AndroidRuntime: at com.owncloud.android.MainApp.onCreate(MainApp.java:167)
02-04 06:05:48.738 6072 6072 E AndroidRuntime: at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
02-04 06:05:48.738 6072 6072 E AndroidRuntime: at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5920)
02-04 06:05:48.738 6072 6072 E AndroidRuntime: ... 8 more
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by ictabc** [comment]
Unable to reopen #3257

**Comment by AndyScherzinger** [comment]
cc @tobiasKaminsky

**Comment by ictabc** [comment]
Update, clear storage option doesn't work because the app is started and crashes with same error.

**Comment by tobiasKaminsky** [comment]
Closing this one in favor of #3507
