### ISSUE TITLE
Push notifications disabled

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/android#3576]
The notifications are as follows: `Push notifications disabled due to dependencies on proprietary Google Play services.`

The problem has been discussed many times, but I have not found a solution for me.

Nexcloud on android v3.5.0 RC2 with F-Droid
Nexcloud server v15.0.2
Notifications v2.3.0
Android v7.0

**Comment by tobiasKaminsky** [comment]
Well…the snackbar is exactly for this reason there: to inform fdroid user that they do not have push notification as they rely on google libs and this is not allowed/wanted on fdroid/by the users.

@Valdnet what do you expect? Better named message?

**Comment by Valdnet** [comment]
> @Valdnet there is no solution at the meoment. Push notifications require Google services and are thus only available via the app distribution on the Google Play store.

@tobiasKaminsky The application installed from Google Play and the situation is the same. Some solution?

Maybe the problem lies in Google Play?

**Comment by Valdnet** [comment]
> @Valdnet Push notifications require Google services and are thus only available via the app distribution on the Google Play store.

And there is no other solution?

**Comment by AndyScherzinger** [comment]
> And there is no other solution?

As of this very moment, no. There are some people working on an OSS alternative but that isn't ready to be utilized by projects.

**Comment by Valdnet** [comment]
Thanks for a quick explanation of the problem.
