### ISSUE TITLE
Instant Upload: more options for automatic subfolders

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#359]
Currently "only" year/month, e.g. 2016/10 is supported.
If one opens this in gallery app one sees only "10".
So I propose some more options:
- 2016 / "2016 - 10"
- 2016 / "2016 - October"
- 2016 - October

Maybe it is better to offer option for year and month:
year
- as folder
- include in month folder

month:
- digit
- written

**Comment by AndyScherzinger** [comment]
@Spacefish I thought the folders names are "flat" as is "yearmonth" at the moment?

**Comment by kaefert** [comment]
A nice additional option would be to mirror the same folder structure as exists in the local folder in the chosen nextcloud folder.

The current behavior I experience with the nextcloud android app  version 2.0.1 installed via FDroid is:
-) checkbox "use subfolders" checked: creates YYYY/MM/ folders and places any new files inside and below the chosen local folder in that MM folder ignoring the original folder structure.
-) unchecked: any new files inside and below the chosen local folder are uploaded flattened without structure to the chosen nextcloud folder

**Comment by seuf** [comment]
+1 !
I'd love to see a pattern configuration for subfolders. Like `YYYY/YYYY-MM`

**Comment by joshtrichards** [comment]
Let's consolidate this with #1330
