### ISSUE TITLE
Fingerprint Lock Not working on Xiaomi Mi 8 devices

### ISSUE THREAD

**Issue by EneOli** [nextcloud/android#3595]
Actual behaviour

With device credentials set to fingerprint unlocking, the app always asks for the pin code.
Expected behaviour

It should ask for a fingerprint. Pin could be fallback solution
Steps to reproduce

    Turn on fingerprint verification
    Start app
    Notice pin request

Environment data

Android version: 9

Device model: Xiaomi Mi 8

Stock or customized system: stock

Nextcloud app version: latest PlayStore release

Nextcloud server version: 14.0.3.

**Comment by EneOli** [comment]
Checked, gut issue still Not reseolved.

**Comment by tobiasKaminsky** [comment]
There are some vendors / android version where you only see pin input field, but still can use fingerprint. 
Have you tried to use the fingerprint sensor even if pin is shown?

**Comment by EneOli** [comment]
Yes, I did, but it does not work.

**Comment by EneOli** [comment]
![img_20190213_160932234](https://user-images.githubusercontent.com/23139864/52721533-23053380-2faa-11e9-90cf-bb84e23b5d80.jpg)

Taking screenshots is not possible, so I took a photo.

**Comment by tobiasKaminsky** [comment]
Thanks, this is indeed the lock screen by your vendor. 
So I fear that this is a problem by Xiaomi.
Does this work for other apps, e.g. banking apps?

**Comment by EneOli** [comment]
Yes, I have a file manager, where I can encrypt files. To decrypt them I can use fingerprint.

But the file manager ist from Xiaomi too.

**Comment by EneOli** [comment]
I now have a Synology Diskstation and it has an Android app called "DS File". There I can use fingerprint to unlock the app.

**Comment by titeishon** [comment]
I have the exact same issue with my Xiaomi Mi 8 Lite.  It also affects other apps that use device credentials like andOTP so it seems to be a MIUI problem.  I previously installed an AOSP ROM and the fingerprint unlock did show up.
