### ISSUE TITLE
Hidden files not included in file counts

### ISSUE THREAD

**Issue by danielb42** [nextcloud/android#3597]
### Actual behaviour
- When "Show hidden files" is enabled, those are not included in the counter at the bottom of folder views. It's a minor UX issue but it still makes the counter itself seem buggy/broken.

### Expected behaviour
- When "Show hidden files" is enabled, those should be included in the counter at the bottom of folder views.
 
### Steps to reproduce
1. Enable "Show hidden files".
2. Place a hidden file somewhere.
3. Navigate there and wonder if the counter line is actually buggy.

### Environment data
Nextcloud app version: **3.4.2**

**Comment by tobiasKaminsky** [comment]
Thanks for reporting, this is fixed and will be in 3.6 release.
