### ISSUE TITLE
PreferenceManager does not manage anything

### ISSUE THREAD

**Issue by ezaquarii** [nextcloud/android#3599]
### Is your feature request related to a problem? Please describe.
PreferenceManager is just a namespace to access some global state, making unit testing impossible.

### Describe the solution you'd like
Turn `PreferenceManager` into a normal object, wrap SharedPreferences and inject it whenever needed, instead of relying on static getters/setters. Cleanup direct calls to `SharedPreferences` too.

**Comment by tobiasKaminsky** [comment]
Nice idea!
With inject do you mean some sort of dependency injection, or simple create an instance of PreferenceManager?

**Comment by AndyScherzinger** [comment]
Hi @ezaquarii how would you handle the possible context leaking in such a scenario? Or would you still always have the context object as a ethod paramter (like today's methods)? I am just asking since for anything except Activities like the services having a class holding a context object might lead to context leaks so one would have to use weak references to handle that which complicated the code I think. Or did a miss something regarding your solution approach. The "PreferenceManager" has been created to have a layer between classes needing access to shared preferences and the handling of them (like commit() vs. apply() and "knowing" the preference's id) and things like that.

I am not arguing against such a change I just try to understand the solution approach and 👍 for increasing testability 👍

**Comment by ezaquarii** [comment]
> Hi @ezaquarii how would you handle the possible context leaking in such a scenario?

In short term, we can always use `Application` context and inject it into app `PreferencesManager` (or any other component that requires it). `Application` context is guaranteed to be bound to process lifetime, so there is no leak.

> I am just asking since for anything except Activities like the services having a class holding a context object might lead to context leaks

I understand and share your concern here. In the grand scheme of things however preferences user should not care what `Context` god object is nor how to work around it's design flaws.

> The "PreferenceManager" has been created to have a layer between classes needing access to shared preferences

I understand the motivations and it was definitely a step in right direction. However, the current implementation is just a very thin syntactical wrapper that still leaks all internal implementation details (including Android design flaws) to the client code.

This has several far reaching implications:

1. unit-testing any code depending on preferences requires non-trivial mocking effort of static methods and/or global preferences state - practically making unit tests unfeasible;
2. the client code needs to care about creation procedure (let's not focus on this for now - discussion about DI is for another time);
3. the client code needs to depend on potentially useless `Context` - if you don't use it for anything except preferences - tying at least some unit tests to `android.jar` for no profit (running tests on emulator is not fun);
4. mocking `Context` is a rabbit hole - in practice it will discourage contributors from writing automated tests, as it is a type of code that is not "fun" to write.

All the above-mentioned issues are at least eased by a dependency injection of course, but getting there requires some intermediate steps.

For the time being, please consider the following pseudo-code proposal:

```java
interface IPreferencesManager {
    // let's not talk about naming conventions yet
}

class PreferencesManager implements IPreferencesManager {
    /**
     * Preferences manager should not care where the system prefs object is
     * coming from nor how to create it, so we inject it via constructor
     */
    PreferencesManager(SharedPreferences preferences) {
        ...
    }

    /**
     * Temporarily we can make-do with a factory method until DI
     * solution becomes available. Let's skip the discussion about context leakage
     * here, as I suspect that shared prefs is not using it internally, but grepcode 
     * server is 503 for now. Let's spend few clock cycles to make it defensive.
     */
    public static IPreferencesManager fromContext(Context context) {
        Context appContext = context.getApplicationContext(); // defensive context retrieval
        SharedPreferences prefs = appContext.getSharedPreferences(...); // does it keep context? not sure yet
        return new PreferencesManager(prefs);
    }
```

Let's skip a discussion about `I` prefix for interfaces and `Impl` suffix for implementations for now - it's like tabs vs spaces and not relevant for the design. Luckily, Java comes with a free, unlimited renames perk, so you can defer such discussions indefinitely. :)

Once the client code depends only on `IPreferencesManager` interface, we can start thinking about migrating away from `PreferencesManager.fromContext(...)` factory method to a more advanced DI solution. Please note that I'm not talking about DI *library* here - the specific dependency injection mechanism, being it a hipster library of the month, old-fashioned constructor injection or a self-rolled "framework", is irrelevant at this stage.

Please bear in mind that replacing static preference manager with an injectable one will not automagically guarantee you a universal testability - there might be more dependencies that require untangling before it starts paying a dividend.

I hope my intentions are a bit clearer now.

Cheers.

**Comment by AndyScherzinger** [comment]
Hi @ezaquarii,

Thanks a lot for the detailed explanation and solution approach. I really like your way forward 👍
All perfectly fine with me, also about having the naming discussion as well as the IoC framework discussed latter on 😊

Any feedback @tobiasKaminsky?

**Comment by tobiasKaminsky** [comment]
Really really great stuff! 
Good explanation, good ideas, "small" improvements one by one, I really look forward to get more input from you :-)

Do you wanna give it a try, or shall I do it?

**Comment by ezaquarii** [comment]
This one has been fixed some time ago so I'm closing it.
