### ISSUE TITLE
external sdcard storage parameter is ignored

### ISSUE THREAD

**Issue by GCastor** [nextcloud/android#360]
### Actual behaviour
- Store file to sdcard doesn't work since beta 20161019 or 20161012, android client ignore configuration and store in internal storage. Since update old files stays on correct place but new files go to internal storage.
### Expected behaviour
- Storing file in /storage/sdcard1/deepFilePathVeryF**ingLong  like selected in configuration before update.
### Steps to reproduce
1.  initial config to /sdcard1 with September beta version
2. update to 20161019 (20161012 seems have same comportment )
3. download new files, they going to strong place

II have tried to reinstall and wipe config, but i can't resolve this. 
### Environment data

Device model: 
Kindle Fire 7 HD (ford) - FireOS stock = Android 5.1
sm-t800 - Cyanogenmod 12 = Android 5.1

Nextcloud app version:
beta 20161019-beta 20161012

Nextcloud server version:
10

**Comment by AndyScherzinger** [comment]
pinging @tobiasKaminsky

**Comment by Linutux** [comment]
I am having the same problem.

I have the following two options in my config to choose from
(A) "/storage/emulated/0/Android/data/com.nextcloud.android.beta/files"
(B) "/storage/3463-3134/Android/data/com.nextcloud.android.beta/files"

I selected (B), my external SD card. The required directories are created, but files are saved to "/storage/emulated/0/nextcloud/files". 

Device model: 
Samsung S5 Neo (SM-G903F)

Android version:
Android 6.0.1

Nextcloud app version:
beta 20161027

Nextcloud server version:
10.0.1

**Comment by it25fg** [comment]
I guess I'm having the same problem.

System is Android 4.4.2 on a LG L40 D-160, Client version 20161108, Server 10.0.1 on Debian Jessie.

I'm selecting "/storage/external_SD" (really the external SDcard) as storage location.

Trying to download a file, then the download starts, fetches the whole file somewhere, and after 99% it turns into 'download failed', so none of the symbols (checkmark/arrow) appear at the file.

Looking into /storage/external_SD, there are two related subdirectories (I had cleaned up before, everything I see must be freshly created)

"nextcloudbeta" with the subdir "log" and the "currentLog.txt" inside, and
"nextcloud" with the full path of the file to be downloaded, but no file.

Searching for the file in question reveals that it remained in the temp location in the internal storage
/storage/emulated/0/nextcloud/tmp/[accont]/thepath (and nowhere else)

Can I increase log level to see where it wanted to move the file?

**Comment by AndyScherzinger** [comment]
Hi @it25fg unfortunately there is no way to increase the log level in the app. Just assigned the ticket to @tobiasKaminsky since he has more knowledge about to this area of the app and also to give this some more attention :)

**Comment by tobiasKaminsky** [comment]
All I can currently imagine is a permission problem...
But I do not know how to solve it, or how it to debug it other with getting a full logcat.

**Comment by tobiasKaminsky** [comment]
Just another thought. If the migration is failing, it can happen that the storage location shows the new path, but still uses the old one.
Can you removing the app, all nextcloud folders and right after the re-install switch to external sd card?

**Comment by it25fg** [comment]
Before reporting here, I already did a full cleanup: deinstall app, remove all stale folders, and reinstall.

I would doubt a permission issue. The creation of the destination folder has succeeded, and the log file is also written to SD after migration, so some permission must have been granted.

One additional suspicious detail is that the old log file was not **moved** to the new place. The logfile before migration remained in /storage/emulated/0/nextcloud/log while new log was written to the SD.

I'll equip myself with ADB, do a cleanroom attempt again, and see what logcat says.

**Comment by it25fg** [comment]
[log.txt](https://github.com/nextcloud/android/files/583919/log.txt)

Again wiped all traces, reinstalled and then tried all three methods of downloading: tapping on a file, selecting a file -> download, and selecting a file -> set as available offline. Always the same result.

Attached the logcat output, filtered by 'nextcloud'.

By the way, manually moving the files from the temp location to the intended place cured the status in nextcloud: the green check mark appeared, and I could open the cached copy in nextcloud. I did that with the stock "file manager" app without any root privileges, so I think it's unlikely to be a permission problem.

**Comment by Flos** [comment]
I have the same issue with the Nextcloud Beta from 20161111.
Samsung Galaxy Note 3.
Android 5.0.1

The log says: 
`DownloadFileOperation: Download of /path/and/filename to /storage/extSdCard/Android/data/com.nextcloud.adroid.beta/files/nextcloud/username@server/path/filename: Error while moving file to final directory

FileObserverService: No observer for path /storage/extSdCard/Android/data/com.nextcloud.adroid.beta/files/nextcloud/username@server/path/filename`

**Comment by AndyScherzinger** [comment]
Hmm.... @tobiasKaminsky strange thing that I see is com.nextcloud.**adroid**.beta

**Comment by Linutux** [comment]
I can't second the thing with "adroid. I it not working for me also, but this is what I get. 
/storage/3463-3134/ is my external SD card
/storage/emulated/0/ is my internal phone storage

> 2016/11/13 12:35:13
> OwnCloudClient #20 : Creating OwnCloudClient
> 
> 2016/11/13 12:35:13
> SimpleFactoryManager :     new client {simon@cloud.asdyx.de, 258276657}
> 
> 2016/11/13 12:35:13
> OwnCloudClient #20 : REQUEST GET /remote.php/webdav/2016_10_hochfrequenzhandel.pdf
> 
> 2016/11/13 12:35:13
> FileObserverService : Received broadcast intent Intent { act=com.owncloud.android.files.services.FileDownloaderDOWNLOAD_ADDED flg=0x10 bqHint=4 (has extras) }
> 
> 2016/11/13 12:35:13
> FileObserverService : No observer for path /storage/3463-3134/Android/data/com.nextcloud.android.beta/files/nextcloud/simon@cloud.asdyx.de/2016_10_hochfrequenzhandel.pdf
> 
> 2016/11/13 12:35:15
> DownloadRemoteFileOperation : Download of /2016_10_hochfrequenzhandel.pdf to /storage/emulated/0/nextcloud/tmp/simon@cloud.asdyx.de/2016_10_hochfrequenzhandel.pdf: Operation finished with HTTP status code 200 (success)
> 
> 2016/11/13 12:35:15
> DownloadFileOperation : Download of /2016_10_hochfrequenzhandel.pdf to /storage/3463-3134/Android/data/com.nextcloud.android.beta/files/nextcloud/simon@cloud.asdyx.de/2016_10_hochfrequenzhandel.pdf: Error while moving file to final directory
> 
> 2016/11/13 12:35:15
> FileObserverService : Received broadcast intent Intent { act=com.owncloud.android.files.services.FileDownloaderDOWNLOAD_FINISH flg=0x10 bqHint=4 (has extras) }
> 
> 2016/11/13 12:35:15
> FileDownloader : Stopping after command with id 1
> 
> 2016/11/13 12:35:15
> FileObserverService : No observer for path /storage/3463-3134/Android/data/com.nextcloud.android.beta/files/nextcloud/simon@cloud.asdyx.de/2016_10_hochfrequenzhandel.pdf

**Comment by AndyScherzinger** [comment]
Does any of this also happen to any of you in the stable release 1.4.0? And also, do  you have both versions installed beta and stable?

**Comment by bekl101** [comment]
similar problem with beta 20170206
download is started , but file isn´t stored on sd-card. Error looks like permission denied.
when i select internal storage as target, everything works as expected.
With stable version both target are exepted (internal and sd-card)

**Comment by przybylski** [comment]
@bekl101 what is your android version ? is the phone rooted?

**Comment by bekl101** [comment]
Its a Galaxy S7 Android 7 no root

**Comment by tobiasKaminsky** [comment]
Is this bug still valid?

**Comment by tobiasKaminsky** [comment]
I created an enhancement which will be in next dev version, if you want to test.

**Comment by tobiasKaminsky** [comment]
@bekl101 can you give the latest dev version a try?

**Comment by tobiasKaminsky** [comment]
If this problem occurs again, please re-open.
