### ISSUE TITLE
Unit test coverage is insufficient

### ISSUE THREAD

**Issue by ezaquarii** [nextcloud/android#3600]
### Is your feature request related to a problem? Please describe.
Application is written without testability in mind. A lot of global states, minimal dependency injection. Coverage ~6% is rather disappointing and lack of test coverage discourages larger changes.

### Describe the solution you'd like
Improve testing coverage. That would require significant refactorings applied in many components.

### Describe alternatives you've considered
none

### Additional context
I'm keen to understand the Nextcloud appetite for test coverage improvement. This is not a one-off ticket - it's a process requiring significant amount of incremental refactorings.

**Comment by AndyScherzinger** [comment]
Thanks for bringing this matter up for discussion :+1: Pinging @tobiasKaminsky for feedback.
In general we definitely want to improve the test coverage same as we want to improve the static code analysis scores.

**Comment by tobiasKaminsky** [comment]
You are totally right @ezaquarii, we are indeed lacking on tests, both unit and integration tests.
From time to time I write some tests, but as you said, this is way to few.

At some point we should "force" ourselves to only submit new PRs with proper tests.

@ezaquarii do you have experience in testing?

**Comment by ezaquarii** [comment]
I have experience in both testing and refactoring enterprise-grade projects that suffer from similar problems. That is why I immediately spotted some patterns in the code and I believe that some of this tech debt is recoverable.

But making a dent in such large scale codebase is not a 1 or 2 commits, which would require more coop from core devs and some systematic surgery. See #3599 as a first item I proposed few days ago.

**Comment by tobiasKaminsky** [comment]
Indeed this is a long term goal.
If you want to contribute, we are happy to have you on board :tada:

**Comment by ezaquarii** [comment]
I believe we are on the same page here. Shall we close it or you want to have more discussion here?

**Comment by AndyScherzinger** [comment]
I'd vote for closing this one as we are on the same page and opening up more specific issues for discussions an aspect / certain change.
