### ISSUE TITLE
The built-in media player is unable to play the media file

### ISSUE THREAD

**Issue by pibyny** [nextcloud/android#3601]
I guess I found some useful information about this behavior because many people are suffering from this issue I posted at the end of this message where I think the solution is.

### Actual behaviour
- When clicking on a media file in app (mp3, mp4, mov, etc.) the message 'The built-in media player is unable to play the media file' is displayed.

### Expected behaviour
- You'd expect clicking a media file would play the file. Now you have to click on the three dots and select 'stream with' such that it will play with VLC. But you have to do this for all songs in the containing folder which is a bore. You can't listen to an album since you'd have to repeat these steps when a song finishes..
 
### Steps to reproduce
1. Open the app
2. Browse to a media file
3. Click on it to try to play the file.

### Environment data
Android version:
Android 7.1.2
Stock or customized system:
Customized system
Nextcloud app version:
3.4.2
Nextcloud server version:
15.0.2
#### Nextcloud log (data/nextcloud.log)
```
2019/02/05 05:27:00
PreviewMediaFragment: onCreateView

2019/02/05 05:27:01
PreviewMediaFragment: onActivityCreated

2019/02/05 05:27:01
PreviewMediaFragment: onStart

2019/02/05 05:27:01
PreviewMediaFragment: Binding to MediaService...

2019/02/05 05:27:01
PreviewMediaFragment: onResume

2019/02/05 05:27:01
PreviewMediaFragment: Media service connected

2019/02/05 05:27:01
PreviewMediaFragment: starting playback of null

2019/02/05 05:27:01
MediaServiceBinder: Loading and starting through binder...

2019/02/05 05:27:01
PreviewMediaFragment: Successfully bound to MediaService, MediaController ready

2019/02/05 05:27:01
FileDisplayActivity: Media service connected

2019/02/05 05:27:01
OwnCloudClient #3: REQUEST POST /ocs/v2.php/apps/dav/api/v1/direct

2019/02/05 05:27:02
MediaService: Error in audio playback, what = -38, extra = 0

2019/02/05 05:27:03
PreviewMediaFragment: onPause

2019/02/05 05:27:03
PreviewMediaFragment: onStop

2019/02/05 05:27:03
PreviewMediaFragment: Unbinding from MediaService ...

2019/02/05 05:27:03
PreviewMediaFragment: onDestroy

2019/02/05 05:27:04
ExtendedListFragment: Setting selection to position: 0; top: 0; index: 2

```

I believe the main problem is the error
```
2019/02/05 05:27:02
MediaService: Error in audio playback, what = -38, extra = 0
```
I think below is some useful information to resolve this issue.
http://bighow.org/questions/21660098/android-mediaplayer-error-38-0-
https://stackoverflow.com/questions/9008770/media-player-called-in-state-0-error-38-0

**Comment by tiredthinker** [comment]
I noticed I can stream media using the app until I enable https in the configuration of nginx or apache2.

**Comment by jwilczek** [comment]
I'm also unable to stream to Android. Any updates on this?

**Comment by HFranz** [comment]
I have the same issue ("The built-in media player is unable to play the media file is displayed."). After trying to play the mp3 file again (and again) it works sometimes. Sometimes it is not possible to start playing the file. Later (after app restart) it works again. Broadly speaking: error is not deterministic.

**Comment by susobaco** [comment]
#3351

**Comment by erm156** [comment]
I am experiencing this issue, too. I have enabled https in my configuration of apache2. Never tried playing any media files prior to enabling https via letsencrypt.

**Comment by redtux** [comment]
Hi everybody! Thank you for this cool client. 🤩 I have just installed the most recent version 3.7.0 hoping that this annoying bug has been fixed, but unfortunately it is still there. Any hints? I have also been trying dev from f-droid, but no luck. Playback from within the browser or streaming with other clients over webdav works fine. 👍

**Comment by ezaquarii** [comment]
It's being worked on here:
https://github.com/nextcloud/android/pull/4208

What I can say? Join in, test the dev build, raise bugs.

**Comment by MishelMF** [comment]
my log
07-18 13:21:46.169 22712 22712 E MediaPlayer: error (-38, 0)
07-18 13:21:46.169 22712 22712 E MediaPlayer: Attempt to call getDuration without a valid mediaplayer
07-18 13:21:46.170 22712 22712 E MediaPlayer: Error (-38,0)
07-18 13:21:46.170 22712 22712 E MediaService: Error in audio playback, what = -38, extra = 0
07-18 13:21:46.179 22712 22712 I MediaPlayer: [HSM] stayAwake false uid: 10113, pid: 22712
07-18 13:21:46.180  3139  4297 I MediaProcessHandler: processOp opType: 1, uid: 10113, pid: 22712
07-18 13:21:46.180  3139  4297 W MediaProcessHandler: remove target not exist, maybe the UI process: uid: 10113, pid: 22712
07-18 13:21:46.180 22712 22712 I MediaPlayer: [HSM] stayAwake false uid: 10113, pid: 22712
07-18 13:21:46.180  3139  3149 I MediaProcessHandler: processOp opType: 1, uid: 10113, pid: 22712
07-18 13:21:46.180  3139  3149 W MediaProcessHandler: remove target not exist, maybe the UI process: uid: 10113, pid: 22712
07-18 13:21:46.181 22712 22712 I AudioManager: abandonAudioFocus
07-18 13:21:46.183 22712 22712 I MediaPlayer: [HSM] stayAwake false uid: 10113, pid: 22712
07-18 13:21:46.183  3139  3958 I MediaProcessHandler: processOp opType: 1, uid: 10113, pid: 22712
07-18 13:21:46.183  3139  3958 W MediaProcessHandler: remove target not exist, maybe the UI process: uid: 10113, pid: 22712
07-18 13:21:46.232 22712 22712 I AudioManager: requestAudioFocus() status : 1
07-18 13:21:46.233 22712 22712 I AudioManager: requestAudioFocus() apk    : com.nextcloud.client
07-18 13:21:46.239 22712 22712 I AudioManager: abandonAudioFocus

**Comment by ezaquarii** [comment]
*cough*

**Comment by ZandroidX** [comment]
Are you trying to play the file using the "Recent" option in the file explorer?

**Comment by edgaras-civinskas** [comment]
Having same issue still

**Comment by ZandroidX** [comment]
@MishelMF
Did it play a song before you received the mediaplayer or is it just not playing from the start?

**Comment by edgaras-civinskas** [comment]
It did. It's a bit random to be honest. I can get the song playing after multiple refresh. Same in reverse. If the song was playing before, next time I play the song again, I can get Unable to play media file.  Same applies if I am on the local network or external.

**Comment by atagunov** [comment]
Clients (two of them):

Netxtcloud Android app version 3.9.2 on both of
1) LineageOS 14.1-20171107-NIGHTLY-hlte (this is a 7.1.2)
2) LineageOS 14.1-20181204-NIGHTLY-v1awifi

Server:
nextcloud-php72-16.0.4
apache24-2.4.41

FreeNAS-11.2-U7 running 11.3-RELEASE-p5 jail (works somehow) with Nextcloud setup roughly as explained [here](https://www.samueldowling.com/2018/12/08/install-nextcloud-on-freenas-iocage-jail-with-hardened-security/); running on HTTPS - hostname resolved from symbolic to IP, certificate signed by FreeNAS own CA, certificate imported as User CA into Android

I can use Nextcloud app as expected, except when I press on an .mp4 file to play

- before "importing from SD card" my own root CA certificate: no playback at all; after a long time I got "The built-in media player is unable to play the media file" message
- after I "imported from SD card" my own root CA certificate: playback starts but gets stuck after a short while; playback may continue or not continue

Seems like this is the relevant part of `adb logcat` stream:

```
12-31 02:56:16.348   347  5206 D NuPlayerDriver: notifyListener_l(0xb5d2af00), (3, 38, 0), loop setting(0, 0)
12-31 02:56:17.310   347  5208 I NuCachedSource2: restarting prefetcher, totalSize = 2949120
12-31 02:56:17.348   347  5215 D GenericSource: startBufferingIfNecessary_l
12-31 02:56:17.348   347  5206 D NuPlayerDriver: notifyListener_l(0xb5d2af00), (3, 38, 0), loop setting(0, 0)
12-31 02:56:17.348   347  5206 D NuPlayerDriver: notifyListener_l(0xb5d2af00), (200, 703, 40986), loop setting(0, 0)
12-31 02:56:17.351   347  5206 I NuPlayer: buffer low, pausing...
12-31 02:56:17.351   347  5206 D NuPlayerDriver: notifyListener_l(0xb5d2af00), (200, 701, 0), loop setting(0, 0)
```

Interestingly the progress bar kept moving on my screen so I tried touching it with my finger at a later pointer where video seemed to have been loaded and got a few more seconds of playback; think the relevant fragment of `adb logcat` may be this:

```
12-31 02:56:33.380   347  5206 D NuPlayerDriver: notifyListener_l(0xb5d2af00), (3, 53, 0), loop setting(0, 0)
12-31 02:56:34.382   347  5206 D NuPlayerDriver: notifyListener_l(0xb5d2af00), (3, 53, 0), loop setting(0, 0)
12-31 02:56:35.386   347  5206 D NuPlayerDriver: notifyListener_l(0xb5d2af00), (3, 53, 0), loop setting(0, 0)
12-31 02:56:35.971   347  5208 I NuCachedSource2: Keep alive
12-31 02:56:36.389   347  5206 D NuPlayerDriver: notifyListener_l(0xb5d2af00), (3, 54, 0), loop setting(0, 0)
12-31 02:56:36.503   777   843 E QCOM PowerHAL: Failed to acquire lock.
12-31 02:56:36.670   347  1001 D NuPlayerDriver: seekTo(0xb5d2af00) 22496 ms at state 5
12-31 02:56:36.670   347  1001 D NuPlayerDriver: notifyListener_l(0xb5d2af00), (7, 0, 0), loop setting(0, 0)
12-31 02:56:36.725   347  5207 D GenericSource: stopBufferingIfNecessary_l
12-31 02:56:36.726   347  5206 D NuPlayerDriver: notifyListener_l(0xb5d2af00), (200, 703, 36264), loop setting(0, 0)
12-31 02:56:36.726   347  5206 I NuPlayer: buffer ready, resuming...
12-31 02:56:36.726   347  5206 D NuPlayerDriver: notifyListener_l(0xb5d2af00), (200, 702, 0), loop setting(0, 0)
12-31 02:56:36.726   347  5206 D NuPlayerDriver: notifyListener_l(0xb5d2af00), (3, 53, 0), loop setting(0, 0)
12-31 02:56:36.726  4922  5210 W MediaPlayer: info/warning (703, 36264)
12-31 02:56:36.726  4922  5210 W MediaPlayer: info/warning (702, 0)
```

**Comment by tobiasKaminsky** [comment]
There is an experimental switch to another video player in https://github.com/nextcloud/android/pull/8132#issuecomment-792722526

This apk can be installed in parallel. 
It would be great if you can give this a test, if it helps in your scenario.
