### ISSUE TITLE
Photo folder spinning 

### ISSUE THREAD

**Issue by Mikam74** [nextcloud/android#3602]
Hi, so far I live the improvement, just one thing when I select any folder on my Nextcloud, they open fast even though they are bigger in size compare to the photo folder which spins indefinitely and never open.

**Comment by tobiasKaminsky** [comment]
This is indeed an area where the app needs to be improved.
In fact there are already attempts like https://github.com/nextcloud/android/pull/2250

Duplicate of #1682
