### ISSUE TITLE
automatic upload does not automatically upload

### ISSUE THREAD

**Issue by lemmy04** [nextcloud/android#3603]
I've set my nextcloud app to automatically upload photos to my cloud, but it does not work. It only detects new pictures when I manually scan for them.

running on a rooted S8+ running Samsung's 8.0 android image. Nextcloud is the latest 15.04 running on openSUSE Leap 15 on my own server, running under php7

**Comment by tobiasKaminsky** [comment]
Have you excluded the app from battery optimization?

**Comment by lemmy04** [comment]
see https://github.com/nextcloud/android/issues/3604 ;)
