### ISSUE TITLE
nextcloud app keeps detecting the same folder over and over

### ISSUE THREAD

**Issue by lemmy04** [nextcloud/android#3604]
### Actual behaviour
- I upload pictures to my  nectcloud
- i delete the pictures from my phone
- after the desktop client has synced the pictures to my computer I import them into my digikam image library, and then delete them from my nextcloud folder on my desktop, which deletes them from the cloud as well

next time I take a picture I will get a notification from the nextcloud app telling me that it detected a new folder

### Expected behaviour
it should  not re-detect the same folder over and over

### Steps to reproduce
see above

### Environment data
Android version:
8.0
Device model: 
samsung S8+
Stock or customized system:
stock
Nextcloud app version:
current
Nextcloud server version:
current 15.0.4

**Comment by AndyScherzinger** [comment]
Hi @lemmy04 which version of the Android app are you using? (to be found in the app's settings at the bottom)

**Comment by lemmy04** [comment]
version 3.4.2.

One detail, my phone stores the camera pictures on SD card. None of the devices where auto upload works has additional storage.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky shouldn't this be fixes with 3.4.2?

Other than that there will also be an option with 3.5.0 to disable this kind of notification. While that disables any new media folder notification.

**Comment by lemmy04** [comment]
update: i just cleared all app data on my phone, and now auto upload seems to work as intended.

**Comment by AndyScherzinger** [comment]
Glad to hear that. Beware that Samsung has a very aggressive way of battery optimization so you'll definitely will need to exclude Nextcloud from that. @tobiasKaminsky probably has more details since I don't own a Samsung device.

**Comment by lemmy04** [comment]
I just ran the last tests and it seems to work as intended now, and I disabled battery optimization for the nextckoud client now (i was sure i had already done that...)

**Comment by AndyScherzinger** [comment]
Nice! While I read some articles about battery optimization it seems that at least for some OEM that they are reseting these whitelists from time to time :/
So in case it breaks again you might need to check if Nextcloud is still excluded from these optimizations...

**Comment by tobiasKaminsky** [comment]
Good to hear that everything works now, then I'll close this.
