### ISSUE TITLE
[3.5.0RC3] Files can no longer be open via Collabora 3.5.0 RC3

### ISSUE THREAD

**Issue by elpraga** [nextcloud/android#3605]
The spinning wheel is shown, bit the document is not. Files can still be opened abd edited on chrome on the same device.

**Comment by elpraga** [comment]
One note. If the file has been already opened  via the web interface, it does register another user joining in, even though nothing is shown in the android client.

**Comment by tobiasKaminsky** [comment]
This is fixed in RichDocuments as this was a server side problem.
https://github.com/nextcloud/richdocuments/pull/392

**Comment by juliushaertl** [comment]
New version of richdocuments has been released, please upgrade to get the fix. 

@tobiasKaminsky Maybe it would be nice to have some sort of timeout with a proper error message, that loading the document on the server failed here?

**Comment by tobiasKaminsky** [comment]
> @tobiasKaminsky Maybe it would be nice to have some sort of timeout with a proper error message, that loading the document on the server failed here?

Nice idea.

![2019-02-14-151309](https://user-images.githubusercontent.com/5836855/52792200-11d02b80-306b-11e9-81e2-a0dd665b253e.png)

Wording can be adjusted a bit ;-)

**Comment by tobiasKaminsky** [comment]
Let us discuss it in https://github.com/nextcloud/android/pull/3625
