### ISSUE TITLE
Newest F-Droid beta crashes app when opening instant upload

### ISSUE THREAD

**Issue by cwmke** [nextcloud/android#361]
### Actual behaviour

After upgrading to the latest beta, a message pops up stating instant uploads has been revamped. After clicking the open button, the app crashes. Selecting instant uploads from the slide-out menu continues to crash the app.
### Expected behaviour

After selecting open button, the user should be taken to the new instant uploads menu.
### Steps to reproduce
1. Open the latest F-droid beta.
2. Select instant uploads from the slide out menu.
3. App crashes
### Environment data

Android version: 7.0

Device model: Nexus 6p angler

Stock or customized system: customized, Copperhead OS

Nextcloud app version: F-droid Nextcloud beta 20161026

Nextcloud server version: 10.0.1 (stable)
#### Web server error log

```
** CAUSE OF ERROR **

android.database.sqlite.SQLiteException: near "s": syntax error (code 1): , while compiling: SELECT _data FROM images WHERE (_data LIKE '/storage/emulated/0/<PATH TO FILE>/%') ORDER BY datetaken DESC LIMIT 8
    at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:179)
    at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
    at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
    at android.content.ContentResolver.query(ContentResolver.java:530)
    at android.content.ContentResolver.query(ContentResolver.java:472)
    at com.owncloud.android.datamodel.MediaProvider.getMediaFolders(MediaProvider.java:79)
    at com.owncloud.android.ui.activity.FolderSyncActivity$1.run(FolderSyncActivity.java:130)
    at java.lang.Thread.run(Thread.java:761)

** DEVICE INFORMATION *
Brand: Android
Device: angler
Model: Nexus 6P
Id: NBD90Z
Product: aosp_angler

** FIRMWARE **
SDK: 24
Release: 7.0
Incremental: 2016.10.21.23.10.25
```

**Comment by AndyScherzinger** [comment]
Hi @cwmke tricky one, since the query seems okay, does the ```<PATH TO FILE>``` part contain something like **'s** ?

**Comment by cwmke** [comment]
It does. It has a 's.

**Comment by AndyScherzinger** [comment]
Ah, then that is the issue....
This crashes the query since the ' isn't escaped and corrupts the database query.

... I am on it! :+1:

**Comment by AndyScherzinger** [comment]
Hi @cwmke I implemented a fix for this issue but was to late for the next beta build :cry: So it will *not* be in the next release *20161027* but the one after that one! :smiley:

**Comment by cwmke** [comment]
I think a same day fix is awful great. Thanks for the work! 😀

**Comment by AndyScherzinger** [comment]
@cwmke please be aware that the fix is same day but the delivery via a beta release will need some more time as in whenever @tobiasKaminsky finds the time to do another release :smiley:

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky assigned this one to you. Fix is already on the branches ```syncedFolder``` and ```beta``` so whenever you publish the next beta release this item can be closed :smiley:

**Comment by AndyScherzinger** [comment]
@cwmke we build the next beta release with the fix. should be available via f-droid in the next 24-48h :smiley:

**Comment by cwmke** [comment]
All set! Thanks everyone.
