### ISSUE TITLE
Disable auto upload discovery of new folder

### ISSUE THREAD

**Issue by Mte90** [nextcloud/android#3611]
### Is your feature request related to a problem? Please describe.
RIght now I usually remove folders instead of the content like for screenshots or download. I get everytime the folder is generated an alert about add it for the auto upload but I don't want the notifications and the autoupload.

### Describe the solution you'd like
Settings to change this behaviour like an exclude list or disable the auto upload feature

**Comment by AndyScherzinger** [comment]
The notifications can be turned off with the upcoming release 3.5.0
