### ISSUE TITLE
Nextcloud Sofortupload funktioniert nicht mehr

### ISSUE THREAD

**Issue by Ivonnestirni** [nextcloud/android#3612]
Seit einiger Zeit (Okt 18) funktioniert der Sofortupload nicht mehr. Es kommt bei jeder neuen Datei die Fehlermeldung "Hochladen fehlgeschlagen". Ich finde keine Lösung. Akku-Optimierung ausgeschaltet. Moto G5 plus.

**Comment by tobiasKaminsky** [comment]
Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

**Comment by Mebus** [comment]
Same problem here. Auto-Upload does not work very often. Really annoying.

**Comment by jasondaigo** [comment]
for me autoupload only works if i dont specify custom folder destination; so for example if  want all my camera photos to folder/photos/camera it wont work; no error message,no upload activity.
   
it only works if i leave it untouched to "SofortUpload"
