### ISSUE TITLE
nextcloud app doesn't upload photos

### ISSUE THREAD

**Issue by Blisk** [nextcloud/android#3614]
### Actual behaviour
I expect when I make a photo or video, nextcloud upload it, but it doesn't
it takes for fev days until it decide to upload photos
 
### Steps to reproduce
1. taking photo
2. no photos at nextcloud server after fev hours
3. after fev days than photos appear

### Environment data
Android version: 8.0.0

Device model: samsung S7

Stock or customized system: stock

Nextcloud app version:3.4.2

Nextcloud server version: 15

#### Web server error log
```
Insert your webserver log here
```
no errors in webserver log
#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Have you disabled battery optimization for this app?

**Comment by Blisk** [comment]
Yes I did and it is the same. Before I did that it worked when I open app, but now that not work anymore.

**Comment by tobiasKaminsky** [comment]
Hm. This is really strange as we did not changed AutoUpload within the last versions…

**Comment by Blisk** [comment]
yes but there was some update in phone, new android version

**Comment by pjl4567** [comment]
Android version: 7.1.1

Device model: nubia z17

Nextcloud app version:20190219

Nextcloud server version: 15.04

have the same question unresolved
