### ISSUE TITLE
If a file is modyfied locally on the Android device, later sync fails with an error [3.5.0 RC3]

### ISSUE THREAD

**Issue by elpraga** [nextcloud/android#3615]
### Actual behaviour
- File is modified on the android device-
- manual sync is called
- sync (very often) fails

### Expected behaviour
- Files changed locally get uploaded correctly and automatically (as it used to work with the now deprecated __Available offline__ option)

**Comment by tobiasKaminsky** [comment]
Is this something new on 3.5?
I tested it 5x and it worked every time.
I edited a text file with amaze text editor and quickedi.

**Comment by tobiasKaminsky** [comment]
Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

**Comment by elpraga** [comment]
Greetings @tobiasKaminsky !
Have you tried bigger files? I run into this issue when editing  PDFs. (40-100 MB).

I'm sure it's new to 3.5, because I used to do the same with the same files (I used to use the deprecated __available offline__ feature)

I use XODO to add annotations to PDFs. They get saved, and they used to get uploaded automatically without a glitch.

Now, after upgrading to the 3.5 version, I edit  the files, I sync them by hand, the uploading starts, it gets __to full 100%__, and __then__ it spits out a message "Upload failed".

I have to use  __share__ button from the XODO reader, upload it to Nextcloud (works flawlessly  every time, but it gets uploaded under a modified name),  delete the old file,  and  rename the new file to the old filename. 

Did those details help?

I'm  right now  in the middle of exam madness, and I don't have neither logcat nor adb set up. It won't be until the beginning of March when I might be able have a look at it.

I've also tried uploading small text files, and they work well, but the larger PDF do not.

Could you try those? (I can send you one of the files, if you want). 

If it helps, server logs might be more accessible for me..

**Comment by rnalrd** [comment]
I can confirm the same behaviour of @elpraga. I'm handling PDF from small (1MB) to larger ones (40MB) and I can't upload the new versions with new annotations. Rolling back the client 3.5.0->3.4.2 the issue disappears.

**Comment by elpraga** [comment]
Seems to be fixed in 3.5.1.

**Comment by elpraga** [comment]
Thank you for looking into it!
