### ISSUE TITLE
Internal picture Viewer: delays and malefunktion

### ISSUE THREAD

**Issue by DudeDudeDudeDudeDude** [nextcloud/android#3621]
### Actual behaviour
- Pictures within the internal picture viewer are loading very slowly or not at all. If loaded, one can't swipe them. 

### Expected behaviour
- pictures should load and should be swipeable
 
### Steps to reproduce
I reproduced this on differnet devices:
1. Moto G5, Android 8.1.0
2. Sony Xperia Z, Android 6.01
3. Moto X Play, Android 7.1.1

### Environment data
Android version: 
see above
Device model: 
see above
Stock or customized system:

Nextcloud app version:
3.4.2
Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Are those pictures somehow special?
We rely on server capability to generate screen adapted previews to save bandwith.
You can also download the full sized image manually. Are they then shown?

**Comment by DudeDudeDudeDudeDude** [comment]
Sorry again for the late answer. The pictures a regular jpgs, taken by mobil phones. They are shown after the download.

**Comment by tobiasKaminsky** [comment]
Do you see those images in web?

**Comment by DudeDudeDudeDudeDude** [comment]
Yes, I do. No problems there.
