### ISSUE TITLE
Missing translation in instant upload

### ISSUE THREAD

**Issue by Siggi0904** [nextcloud/android#3626]
Hello,

since 3.5.0 RC2 there are missing translations in the context menu of the instant upload feature.

Screen:
![screenshot_20190214-192150](https://user-images.githubusercontent.com/4992106/52808919-58d01800-308f-11e9-9872-b7d5e56c9749.jpg)

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky easiest fix would be to backport #3472

**Comment by tobiasKaminsky** [comment]
Damn transifex ;-)
#3472 is not that finished yet, in my opinion. 

Is there a way to find out which strings are not translated? We would have to compare it against 3.4.2…

As this can happen more often, if we backport transifex, we need to find a better approach…

**Comment by AndyScherzinger** [comment]
> As this can happen more often, if we backport transifex, we need to find a better approach…

I means we can't merge PRs after initial RC which removes existing translations, Than this can't happen while that means we need to check that manually :/

**Comment by tobiasKaminsky** [comment]
> I means we can't merge PRs after initial RC which removes existing translations, Than this can't happen while that means we need to check that manually :/

So while backport transifex, we just add/change stuff, but do not delete it.
Sounds feasible, although it needs to be done manually.
Another downside is, that then extra/unneeded translation might be in RC, but this should be shown via lint.

**Comment by AndyScherzinger** [comment]
> EDIT: I am sure, I can script something that does this…

That would be awesome 👍

**Comment by tobiasKaminsky** [comment]
Approach on server:
1) go to master and extract strings (you don't need this, because you have them extracted already in a source code file), then repeat this for all supported branches
2) combine all those files into one
3) submit this combined file to transifex so it will contain all strings of still supported versions
4) fetch translations
5) ship this combined file to all branches (in our approach the l10n layer just ignores additional l10n strings)

**Comment by AndyScherzinger** [comment]
Hmm, that would also work for us I think. It is basically master and the latest stable branch(es).

**Comment by tobiasKaminsky** [comment]
https://github.com/nextcloud/android/issues/3626FYI: this is currently failing due to corrupted xml files on Transifex side.
I already reported this via mail to them.

**Comment by Siggi0904** [comment]
with 3.5.1 RC1 from today translation aren't fixed actually.

**Comment by AndyScherzinger** [comment]
Hi @Siggi0904 we didn't add them with 3.5.1, they should however be available with 3.5.1RC2 released today.

**Comment by tobiasKaminsky** [comment]
Screenshot of 3.5.1 RC2:
![2019-03-12-133218](https://user-images.githubusercontent.com/5836855/54200272-4f3da280-44cb-11e9-9504-889837f3bacf.png)
