### ISSUE TITLE
upload fails

### ISSUE THREAD

**Issue by audiofrequenz** [nextcloud/android#3631]
### Actual behaviour
After Update to version 3.5 of the app, the upload fails with the german error message 'Verbindungsfehler'. This translates to english like 'Connection Error'.
I restartet the device a couple of times, including the server which it is trying to connect to.
Download works like a charm. Only the upload of fotos and files fails.

### Expected behaviour
Shoud upload pictures automaticly to the cloud
 

### Environment data
Android version: 8.0.0

Device model: Samsung S7

Stock or customized system: Stock

Nextcloud app version: 3.5

Nextcloud server version: 14.0.4

**Comment by audiofrequenz** [comment]
Images are still there, connection is also there, upload was not succesful, server is available => testet with other device where the upload works (galaxy s5 with custom rom lineageOS). As i mentioned, it started after updating to version 3.5. Nothing else has changed. Problem with your App and Galaxy S7? Energy Saving Options also disabled for the app

**Comment by audiofrequenz** [comment]
Works after reinstall the app on the device.

**Comment by albgus** [comment]
Not working for me either, manual uploads results in an upload error with the error text "Sync conflict, please resolve manually". As far as I can tell there is actually no way to resolve the sync conflict. A 0B file is created on Nextcloud. Reinstalling the app did not work for me. Automatic upload of images seems to work though (except it isn't very automatic)

Huawei CLT-L90 (P20 Pro) @ Android 9.0

**Comment by tobiasKaminsky** [comment]
Can you create us a test account, test if the problem occurs also there and if so send the credentials to tobias at nextcloud dot com with a reference to this issue?

**Comment by eisenherzz** [comment]
Had the same issue. What worked for me was changing for auth with app token.

**Comment by thechonta** [comment]
P20 Pro, no file Larger 1 MB can be uploaded automatic or manual
https://github.com/nextcloud/android/releases/tag/stable-3.4.2
Tried from 3.6.1 back to 3.4.2 and this is the last that works with Files larger than 1MB
