### ISSUE TITLE
App funktioniert nicht mit Two Factor TOTP Provider

### ISSUE THREAD

**Issue by awiesi81** [nextcloud/android#3633]
Seit dem letzen Update funktioniert die Android App nicht mehr mit meinem Server. 

Auf meinem Server läuft Nextcloud 15.0.4 mit Two Factor TOTP Provider 2.1.1.
Die Android App Version ist 3.5.0. 

Problemgerät: Sony Xperia ZX 2 Android 9

App lässt sich nicht einloggen, weder mit passwort login noch mit App-Passwort

**Comment by derritter88** [comment]
Same for me!
Ich habe TOTP und U2F aktiv.

Sobald ich die Android Applikation öffne, versucht Nextcloud zu synchronisieren und zeigt mir nach drei, vier Sekunden die Login-Seite an, obwohl ich mich nicht ausgeloggt habe.

Anmelden geht nicht mehr.

**Comment by schlagi123** [comment]
Das verhalten kann ich bestätigen. 
Nachdem ich die App jedoch neu installiert habe und das Konto neu in die App eingebunden habe, trat der fehler nicht mehr auf.

**Comment by awiesi81** [comment]
Ich habe es gerade probiert - die komplette Deinstallation und ein neues Installieren lösen das Problem.
Hatte gestern nur das Konto gelöscht und mich neu angemeldet.

**Comment by tessus** [comment]
Must be the server version. I'm using TOTP and U2F, Android client 3.5.0, and server 14.0.6.
I haven't experienced the OP's problem.

**Comment by awiesi81** [comment]
Habe gerade gemerkt das es nach dem App Update auf meinem Sony Xperia Z3 Compact Tablet mit Android 5.1.1 auch zu keinen Problemen gekommen ist. Dürfte wohl auch mit der Android Version zu tun haben.

**Comment by ThomasCr** [comment]
I also have Nextcloud 15.0.4 with TOTP, U2F and Notifaction Apps enabled - I also cant logon again to my Cloud on Android App

**Comment by tobiasKaminsky** [comment]
I tested it with 3.5.0 and NC 15 and it works.
As TOTP is used via weblogin, so Android opens up login flow from server, please ask on server why the TOTP is not working.
(have you tested if the TTOP is working whith web ui?)

**Comment by alerque** [comment]
I'm taking a guess here, but given the disparity in duplicating this I'm going to hazard a guess that it actually has nothing to do with TTOP / 2FA and is just another iteration of the login issue in #3623.

**Comment by eldiep** [comment]
I can confirm @alerque s statement. I used the app without TOTP/2FA and the login wasn't possible after a while. Now I'm using TOTP for a few weeks and the bug appears again. So I think it doesn't depend on the 2FA-Authentication.
