### ISSUE TITLE
3.5.0 still downloads documents intead of opening with Collabora

### ISSUE THREAD

**Issue by fafische** [nextcloud/android#3634]
### Actual behaviour
- Android App 3.5.0 downloads OpenDocument-files instead of opening when tapping on them 
- in Chrome on same android phone documents are edited directly
- on iPhone direct editing works

### Expected behaviour
- document is opened for direct editing

### Environment data
Android version: 7.1.1
Device model: Sony Xperia Z5Compact (E5823)
Stock or customized system: Stock
Nextcloud app version: 3.5.0
Nextcloud server version: 15.0.4
Collabora Online (NextcloudApp): 3.2.1
CODE: 4.0.0

**Comment by AndyScherzinger** [comment]
@fafische did you try the 3-dot menu of the list entry where it should say edit with Collabora?

@jancborchardt @tobiasKaminsky it seems we have a client inconsistency here. For Android a file click always leads to a file download except for images, they get a preview.

**Comment by fafische** [comment]
Yesterday 3-dot menu does not show anything about collabora. Today without changing anything direct editing works fine (with tapping on file as well as with 3-dot menu).
Is there a caching problem on server side? Caching problem in app is implausible for me, because after upgrading to CODE 4.0 ... I reinstalled app for downgrading from beta to stable.

**Comment by AndyScherzinger** [comment]
I can't say anything about the server. I only know that the client does some caching I am aware of while like you said doesn't matter since you reinstalled the app.

So. Should be close this issue then?
