### ISSUE TITLE
Conflict with auto-upload

### ISSUE THREAD

**Issue by PTamis** [nextcloud/android#3635]
### Actual behaviour
After I updated my NextCloud app to latest version 3.5.0 (Feb, 13, 2019) the auto upload fails to upload an excel file from my phone to the cloud.
It reports the following error:
1.0MB, Sync conflict, please resolve manually.

I delete the file locally I download the version from the server, I edit the file and I try to upload again.
And again I have the same error!!!
Sync conflict, please resolve manually!!!

Also option to have this file offline seems to be missing with new update.

### Expected behaviour
I expect when I edit a file an is saved to be able to be uploaded automatically and don't have sync conflicts!
This was not happening with previous version.
Something broke the functionality with this new version.
 
### Steps to reproduce
1.  Have a excel file at server
2.  Download and edit file. Save and try to sync.
3. Application reports sync problem and it never uploads the edited version.

### Environment data
Android version: 7.0 NRD90M

Device model: Xiaomi Redmi Note 4

Stock or customized system: Stock system (not rooted)

Nextcloud app version: 3.5 latest version!

Nextcloud server version: 15.02

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tiggerfan** [comment]
same issue with autoupload for photos instanceupload.  downgrading back to prior version.

**Comment by Ablu** [comment]
I also get the issue, however, only for files which get updated (for eg. WhatsApp backups).

The files with unique timestamps work fine, only the one without suffix fails.

**Comment by Fortyseven** [comment]
> _I also get the issue, however, only for files which get updated (for eg. WhatsApp backups)._
> 

That's what I'm seeing. In my case, if I crop or adjust the color of a photo, it kicks in.

![image](https://user-images.githubusercontent.com/156409/53466684-0d1f5600-3a21-11e9-8b32-02981ac29f62.png)

**Comment by GiganteX** [comment]
I take a picture, it tries to upload it, I get "Conflict". Makes no sense.

**Comment by tiggerfan** [comment]
same for me, new pictures get "conflict" when they attempt to auto-upload.  I downgraded to 3.4.2 and it is working fine now.

**Comment by tobiasKaminsky** [comment]
Can you create us a test account, test if the problem occurs also there and if so send the credentials to tobias at nextcloud dot com with a reference to this issue?

**Comment by PTamis** [comment]
@tobiasKaminsky what do you mean by a test account?
Make an account at nextcloud.com and try to repro the issue there?

I just downloaded the version 3.5.1 RC1 and tried also there.
The actual problem has been fixed.
Now I can upload my file and no conflict happens.
BUT there is another problem now. 
The upload does not work automatically. 
I have to sync the manually with the sync button. 
The option to have the file offline is missing which this I think making the file to sync automatically.

Could you please see this and add the functionality again to next release?

**Comment by PTamis** [comment]
Further updates over this issue with 3.5.1 RC1
If you update the excel file on the server, then when you open the nextcloud app on your phone the excel file is being synced and downloaded to your phone automatically.
This is working fine and it is what's expected!

But the other way is not happening automatically as was happening with 3.4.2.
Meaning, when you update the file on your phone then you have to press the button sync on the nextcloud application in order for the excel file to be uploaded to the server.

Ok its much much better than 3.5.0 which broke everything but still it is not working as before.
Could you please check this and fix the automatic auto upload?

**Comment by PreTamp** [comment]
I had nearly the same issue like @Fortyseven : I got a message like "conflict, please resolve manually" for my msgstore.db.crypt12 from whatsapp (auto sync for the whatsapp folder on my android).

But now, after the update of the app (now 3.5.1) this issues seems to be resolved. :)

**Comment by Ablu** [comment]
> But now, after the update of the app (now 3.5.1) this issues seems to be resolved. :)

I can confirm this! Thanks for the update!

**Comment by tobiasKaminsky** [comment]
Thanks for your update and glad that it works!

**Comment by Murgeye** [comment]
This bug seems to be present in 3.11.0 RC1 for me. Should it be fixed already or is the Beta Version "behind" on that?

**Comment by AndyScherzinger** [comment]
@Murgeye could you please open an issue about this (since you say it is (still) present in 3.11.0 RC1) and ping @tobiasKaminsky and @ArisuOngaku about it? Thanks ❤️
