### ISSUE TITLE
One screen, 2 improvments: 1 missing translation + Date in reverse order

### ISSUE THREAD

**Issue by ldmpub** [nextcloud/android#3636]
Hi,

I'm a huge fan of nextCloud and an active french translator. On the same screen (Activity) I have noticed 2 little "bugs":
* date: in french order should be reversed, please display "Mercredi 30 Janvier" in this example (without comma)
* one string can not be translated (I didn't find it to translate in transifex where I have access).

see screen shot with annotations
![new_popup not translated-and wrong date format order - nextcloud - with annoatons](https://user-images.githubusercontent.com/1452146/52889696-6bc31500-3181-11e9-8d83-79f236ad8e5d.jpg)

Thanks,

**Comment by ldmpub** [comment]
I had a look and none of the above "automated related issues" seems to have any link with my 2 remarks (GitMate is far far away from IA!):
1. Wrong french format for top date
1. No translation for "File not found" popup.

Note: Android NextCloud is 3.5.0 in beta program.

**Comment by tobiasKaminsky** [comment]
There is an android function that shows the datetime in correct localized form.
However it is written in French with lower case, while your idea is to have it with capital starting chars.

![2019-02-26-135838](https://user-images.githubusercontent.com/5836855/53414319-c143c100-39ce-11e9-9e33-062b3221f6af.png) ![2019-02-26-135910](https://user-images.githubusercontent.com/5836855/53414320-c143c100-39ce-11e9-87a9-3fcc155950e8.png) ![2019-02-26-135923](https://user-images.githubusercontent.com/5836855/53414321-c1dc5780-39ce-11e9-9087-4158c4455158.png)

Would this be fine for you?

**Comment by ldmpub** [comment]
@tobiasKaminsky your proposal is perfect for me (first capital letter is a detail).

Thanks
