### ISSUE TITLE
Authentifizierung schlägt fehl

### ISSUE THREAD

**Issue by dkthenker** [nextcloud/android#3639]
Client kann sich nicht am Server anmelden. Passwort aber korrekt und per Browser okay.
Samsung Galaxy S9 +
Android 9

**Comment by alerque** [comment]
It's hard to tell for sure since my German isn't good for much _and_ this issue has very few details to go on, but this is probably a duplicate of issue #3623.

**Comment by tobiasKaminsky** [comment]
Can you create us a test account, test if the problem occurs also there and if so send the credentials to tobias at nextcloud dot com with a reference to this issue?
