### ISSUE TITLE
Beta 20161026: Storage path "Unknown" in settings

### ISSUE THREAD

**Issue by Olodin** [nextcloud/android#364]
### Actual behaviour

I installed nextcloud Beta 20161026 parallel to release 1.3.1 and see Unkown in storage path.

![screenshot_20161028-204217](https://cloud.githubusercontent.com/assets/15112195/19818759/7f1b6f24-9d51-11e6-9b74-5c6b096cd32c.png)

I have set up the same account as on the release version. It seems as if both versions now use the same data folder: /storage/emulated/0/Android/data/com.nextcloud.android.beta/files is empty.
But the beta app shows all files and also syncs.
### Expected behaviour
- Default storage path should be choosen, different one than installed release app.
### Environment data

Android version: 7.1.1, Build NPF10C

Device model: Nexus 5x

Stock or customized system: Google beta system

**Comment by mr-bolle** [comment]
After I had selected the path, it has lasted very long to the choice was taken over. I have closed the Application, and once more have chosen the path - then it has functioned immediately.

Perhaps, it helps the reinstall of the Application.

Device model: Sony Xperia Z3 binary (D6633) 
Android version: Android 6.0.1

**Comment by AndyScherzinger** [comment]
@Olodin the path is different, since the Stable release doesn't have the word "beta" in the folder-path, so no worries there! :smiley: 
@mr-bolle yes after choosing a path it takes a while since all the data gets migrated (moving files around) which takes time :(
