### ISSUE TITLE
Add offline option for folders 

### ISSUE THREAD

**Issue by Tonus1** [nextcloud/android#3640]
Hi, 
Could it be feasible to add the offline sync capability to folders in the Android app ? 

Actually files are kept in sync (last update) but I would like to automatically sync files I add in the target folder (one of my nextcloud provider do not offer proper webdav credentials). 

Regards

**Comment by AndyScherzinger** [comment]
Absolutely :) Closing it though in favor of #269 please follow up in the original issue.
