### ISSUE TITLE
Delete the notification content

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/android#3661]
I will restart this #1311 topic about deleting notifications.

Is it possible to delete notifications in the application? Without deleting from the server, after many notifications is made a little mess.

Removal may involve slaid them to the side or via a cross.
Additionally in the menu:  `: `-> `delete all`.

**Comment by AndyScherzinger** [comment]
@Valdnet thanks for the offer :)
I do think that @tobiasKaminsky already did an implementation these days which should already be present in the dev build and thus will ship with 3.6.0. Unfortunately @tobiasKaminsky won't be back before next week to confirm this.

See #3607

**Comment by Valdnet** [comment]
Ok. So let's wait for the new version :wink:

**Comment by tobiasKaminsky** [comment]
@Valdnet you can also try our dev version and give us feedback, how you like the enhancement.

**Comment by Valdnet** [comment]
@tobiasKaminsky i am sorry I did not express my opinion on this subject. Somehow it escaped me.
In my opinion, it looks very nice. This was missing in this application 👍 

I have a question, is it possible to bend the content line of the notification displayed in the top system bar?

**Comment by tobiasKaminsky** [comment]
> I have a question, is it possible to bend the content line of the notification displayed in the top system bar?

Can you open up a new issue for this? And maybe with a little screenshot as I currently do not know what you expect :-)

**Comment by Valdnet** [comment]
As I thought. New issue #3753.
