### ISSUE TITLE
Active "Save" button in set up a custom folder

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/android#3664]
### Actual behaviour
- `Save` button is active at all times in `Set up a custom folder`.
![obraz](https://user-images.githubusercontent.com/47037905/53154895-155c3900-35bc-11e9-982c-cb1576315723.png)

### Expected behaviour
- `Save` button **only** active after selecting the folder `Set up a custom folder` and `Remote folder` in the `Set up a custom folder`.
![obraz](https://user-images.githubusercontent.com/47037905/53155397-3f622b00-35bd-11e9-875b-2cc72969e9fc.png)
![obraz](https://user-images.githubusercontent.com/47037905/53155484-73d5e700-35bd-11e9-9f69-4442e7fd5ebe.png)
![obraz](https://user-images.githubusercontent.com/47037905/53155097-a29f8d80-35bc-11e9-9cfe-91e9b18bc3e3.png)
 
### Steps to reproduce
1. Select from the menu `Auto upload`.
2. Select: `:` -> `Set up a custom folder`.
3. Select only: `Set up a custom folder`.
4. Enter: `Save`.

**No reaction by the application. This is confusing for the user.**

### Environment data
Android version: 6

Nextcloud app version: 3.5.0 and bf99c2d

**Comment by ezaquarii** [comment]
The button is not active - it is disabled, but the theme does not have a special drawable for this state. The whole dialog uses alpha to dim other disabled controls.

**Comment by Valdnet** [comment]
> The button is not active - it is disabled

That's right. But another user may not know about it and click endlessly.

> The whole dialog uses alpha to dim other disabled controls.

It should also darken the "Save" button.

In my opinion, the correct behavior of the application should be as I wrote above.

**Comment by ezaquarii** [comment]
```
    private void setupDialogElements(View view) {
        int accentColor = ThemeUtils.primaryAccentColor(getContext());
        ...
        mCancel = view.findViewById(R.id.cancel);
        mCancel.setTextColor(accentColor);

        mSave = view.findViewById(R.id.save);
        mSave.setTextColor(accentColor);
```

Those `setTextColor` lines override color selector that handles enabled/disabled state. We can simply remove them, but I'd like to understand the purpose of `ThemeUtils.primaryAccentColor(getContext());`.

It looks like we're trying to handle dynamic themes this way.

**Comment by AndyScherzinger** [comment]
Exactly, we fetch the theme colors from the server so we would need to keep this while it should be implemented with a proper color state list then :)

**Comment by Valdnet** [comment]
@AndyScherzinger may add a message with information about the need to enter the folder paths.

**I - Steps:**
1. Click "save" without specifying the local folder path.
2. Message: Enter the path of the local folder.
3. Confirmation of the message by clicking on the "Close" button.

**II - Steps:**
1. Click "save" without specifying the remote folder path.
2. Message: Enter the path of the remote folder.
3. Confirmation of the message by clicking on the "Close" button.

I think that this behavior of the application would also be correct and understandable for the user.
This solution does not require the interference of color themes.

**Comment by AndyScherzinger** [comment]
Imho the colors should be there anyways to support the behavior and the hint. The message might also help while it would then either be a snackbar or a toast.

**Comment by Valdnet** [comment]
@AndyScherzinger I tested today a new version of dev 2d28640.
Works sensational. This was missing in the Nextcloud application.
You should get a 🥇 for it.

**Comment by AndyScherzinger** [comment]
Actually @ezaquarii did the fix so he should get all the praise 💯

**Comment by Valdnet** [comment]
@ezaquarii and also a 🥇 for you.
