### ISSUE TITLE
Not able to choose remote (federated id) share option.

### ISSUE THREAD

**Issue by cappuMUC** [nextcloud/android#3666]
### Actual behaviour
When I try to share a folder with for example user@domain.example the app gives me two options. I can either choose between a remote account or an email address. Regardless what I'm selecting, remote or email, the app always creates a share by email and not by the federated id.
In the web UI I'm able to create the remote share without any issues.

### Expected behaviour
If I select `remote` a remote share should be created instead of an email share.
 

### Environment data
Android version: 6.0.1 

Device model: Motorola Moto X (xt1052)

Stock or customized system: Lineage OS 13.0

Nextcloud app version: 3.5.0

Nextcloud server version: 14.0.6 and 15.0.4

**Comment by tobiasKaminsky** [comment]
Thanks for this bug report, this will be fixed in upcoming minor 3.5.1 release.
