### ISSUE TITLE
3.5.0 auto uploads broken (3.5.1 as well)

### ISSUE THREAD

**Issue by lachlan-00** [nextcloud/android#3669]
Any file I upload larger than a megabyte fails.

Could not complete operation. Server unavailable.

My primary phone is google play only and can no longer upload from the camera unless the picture is small.

I tested on my rooted phone with 3.4 f-droid and auto upload works. 3.5 had an update with chunking uploads?

**Comment by InfamousUser** [comment]
Yep, auto uploads are not working, I just added a comment on this yesterday on a previously opened issue: https://github.com/nextcloud/android/issues/3296

**Comment by WebSpider** [comment]
Issue #3641 is also open for this.

**Comment by lachlan-00** [comment]
I read these bugs before posting but you're having trouble with all uploads?

I have no issue with anything below 1mb in other media folders but my phone camera can't take a picture below 1mb even on lowest settings.

I've tested with putting files into my DCIM folder and they go up fine as well.

**Comment by WebSpider** [comment]
That must be it, indeed. I just noticed that screenshots (which are < 1MB usually) are uploaded. I will amend my issue.

**Comment by franck-eyraud** [comment]
Good morning, I can confirm that the problem is for uploading files above 1Mb (not only auto upload, amslo manual uploads), and seems to be linked to new chunk upload #1026 in version 3.5.0. Upgrading the server seems to not solve the issue, and [downgrading the android app](https://github.com/nextcloud/android/issues/3641#issuecomment-465063962) does restore the feature.

**Comment by peteman52** [comment]
I'm perplexed. I updated from 3.4.2 to 3.5, after confirming that autoupdating doesn't work I installed 3.4.2 again. Now autoupdating doesn't work with 3.4.2. Did you merge some features of 3.5 in 3.4.2 ?

**Comment by lachlan-00** [comment]
No issues with fdroid 3.4.2 for me.

**Comment by carlosfvp** [comment]
> 
> 
> I'm perplexed. I updated from 3.4.2 to 3.5, after confirming that autouploading doesn't work I installed 3.4.2 again. Now autouploading doesn't work with 3.4.2. Did you merge some features of 3.5 in 3.4.2 ?
> 
> Update: I installed 3.4.2 from F_DROID and autouploading didn't work. I then deinstalled it and installed nextcloud-30040290.apk (which seems to be 3.4.2) from https://github.com/nextcloud/android/releases/tag/stable-3.4.2 . Now autouploading is working again. ???

The version from nextcloud-30040290.apk is not working for me either.
I just keep uploading videos of less than 15M and photos of less than 1M.

**Comment by lachlan-00** [comment]
Looks to be still broken in 3.5.1

**Comment by AndyScherzinger** [comment]
pinging @tobiasKaminsky

**Comment by WebSpider** [comment]
Just to let you know, it works for me in 3.5.1!

**Comment by lachlan-00** [comment]
I've got some router troubles I need to sort. But that's good to know. Maybe it was an internet problem.
I'll report back tonight

**Comment by lachlan-00** [comment]
My server is still only uploading files that are under 1mb.

This chunking feature is just simply not working.

**Comment by AndyScherzinger** [comment]
pinging @tobiasKaminsky for further input

**Comment by tobiasKaminsky** [comment]
@lachlan-00 
Can you create us a test account, test if the problem occurs also there and if so send the credentials to tobias at nextcloud dot com with a reference to this issue?

**Comment by lachlan-00** [comment]
sure can. i'll send that through in a few minutes

**Comment by tobiasKaminsky** [comment]
@lachlan-00 I tried it with 3.5.1 and with latest master version, both are working really fine.
Have you tried it with "my" user on your phone?

**Comment by lachlan-00** [comment]
i had to uninstall completely and reinstall again. then my user can upload photos. not ideal after a month of no uploads but better than nothing

**Comment by tobiasKaminsky** [comment]
Sorry to hear, it is hard to say from the distance what caused the problem.
But luckily it works now.
