### ISSUE TITLE
Disable annoying "New photo media folder detected.." notifications.

### ISSUE THREAD

**Issue by mark-orion** [nextcloud/android#3672]
### Is your feature request related to a problem? Please describe.
I am really annoyed by the "New photo media folder detected..." notifications. I am not using the auto upload feature and even worse: Whenever I add a folder containing media I am getting these notifications hours later in the middle of the night.

### Describe the solution you'd like
An option to disable either these notifications or the complete auto upload feature. Issue [3611](https://github.com/nextcloud/android/issues/3611) promises that these can be disabled in 3.5.0, but I have not found any way to do this.

### Describe alternatives you've considered
Switch all Nextcloud notifications off (A bad option because there might be useful ones).

### Additional context
Nextcloud App vs. 3.5.0
Android Version 9
Hardware: Sony XPeria XZ2

**Comment by mark-orion** [comment]
Looking at #3080 I found a solution in disabling the "File Observer" notification for the Nextcloud App via the Android Settings. This solves the problem, but an option to do this from within the app would be preferrable.

**Comment by AndyScherzinger** [comment]
Can be done from within the app. In 3.5.0 you can disable it via an action offered within the notification for new media folders.

**Comment by Mte90** [comment]
I was looking for a setting inside the app, so @AndyScherzinger you mean that now the notification about the new folder has a button? because I didn't noticed that.

**Comment by AndyScherzinger** [comment]
@Mte90 exactly. It might be that depending on the phone/oem/resolution/whatever that the notification is displayed in a collapsed way by the Operating System and you might need to expand the notification. For screenshots see https://github.com/nextcloud/android/pull/3448
The app's setting sscreen will display an option to reactivate after you chose to hide the notifications via the notification itself.

**Comment by Mte90** [comment]
I will check beter at the next notification :-)

**Comment by AndyScherzinger** [comment]
If you run the app version 3.5.0 or above and don't see such buttons in your notifications, please let us know. It should show up, fingers crossed :)

**Comment by stuart12** [comment]
I have Nextcloud 3.5.1 from F-Droid running on Lineagos 15.1-20190323 (Android 8.1.0, API Illama 9) and have just inserted a SD card with hundreds of folders containing photos.  I have thus hundreds of notifications that are arriving one after another. Beep, Beep, Beep. As you can imagine this is very annoying and have thus looked hard for any setting to stop this happening. I have looked under Settings -> Notifications and I have looked at the notification itself. Nothing looks like it will stop this stream of notifications.  I never want Nextcloud to synchronize my photos and I certainly don't want it to ask me for every new folder.

**Comment by AndyScherzinger** [comment]
@stuart12 I might be mistaken with the version the fix is in it should be 3.5 I think, else it will definitely ship with 3.6. I ddn't find the time to search for the exact change and time when it has bene made. Can you remember this @tobiasKaminsky ?

**Comment by a1b0hph0b1a** [comment]
I can confirm there is still no option for disabling the notifications. Or the search which triggered the notifications in NextCloud Android app version 3.6.0.

It is neither in the settings page or the notifications page drop down menu.

TBH though, this morning my Nextcloud server attempted an update to the certificate and has completely bricked itself, congratulations on an excellent product!!!

Context...
Lineage OS version: 14.1
Android version: 7.1.2
Device Samsung: Galaxy S3 GT-i9300

**Comment by AndyScherzinger** [comment]
@a1b0hph0b1a can you please post a screenshot of the Android notification you are seeing?

**Comment by a1b0hph0b1a** [comment]
I can't, I've disabled the notifications in the LineageOS Privacy Guard. I can send an image of the settings menu though!
It only seems to happen when you turn the phone on or when first installed.

TBH, I may stop using NextCloud. I've used it for a week and it's already completely useless as the cert is broken and I can't fix it!

![settings_menu](https://user-images.githubusercontent.com/13733356/56868395-e1512a00-69e9-11e9-806d-e2e902aa97ee.png)

**Comment by AndyScherzinger** [comment]
@a1b0hph0b1a see screenshots in https://github.com/nextcloud/android/pull/3448 the disable-button is within the notification itself (expanded notification view!). In the settings screen it'll only show up _after_being disabled.

As for the cert part, that sounds like a server side problem (with the current infos at hand of course), so my recommedation if you want to work on that part would be to ask for help on the forums at https://help.nextcloud.com/

**Comment by a1b0hph0b1a** [comment]
Honestly, seems exceptionally dumb to not have a button in settings. I've tried to recreate error by resetting phone and nothing has come up (yes, I turned back on notifications in Privacy Guard first). One does wonder if it's now because it can't connect to server!

Yes, I guessed that much. Overnight it tried to update cert and this error...
**THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE**
There doesn't appear to be help anywhere for it. Neither on NextCloud or LetsEncrypt pages. Or even just as support on pip.

**Comment by bannisdale** [comment]
@AndyScherzinger I'm back here with the same problem. I get the notification, but my Galaxy S10e groups it within "General Notifications". I can turn them off, sure, but I'd rather just turn this one specific notification off. Which doesn't work, as there is no app setting. :)

**Comment by AndyScherzinger** [comment]
@bannisdale do you have a screenshot of the (expanded) notification on your device? The notificastion itself should have a action button for disabling such notifications. Which version of the app yre you using 3.6.x?

**Comment by bannisdale** [comment]
@AndyScherzinger Thanks for the quick response. Now I got it, thanks! I somehow thought "disabling via the notification" meant the standard Android way, but after expanding it, there is - indeed - your custom button. I would still prefer the now appeared re-enabling option to also be present to disable it in the first place, but given that everything works now, I won't bother you further. :D

Have a rest of the week!

**Comment by beddari** [comment]
This option really need to be in the settings without having to 'deactivate' from the notification first. As it is now it was very confusing for me. 

Thanks.

**Comment by AndyScherzinger** [comment]
> This option really need to be in the settings without having to 'deactivate' from the notification first. As it is now it was very confusing for me.

that is something you need to take up with the @nextcloud/designers
