### ISSUE TITLE
Combine multiple sharees

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#3679]
#3320 is implemented nearly everything from https://github.com/nextcloud/server/issues/12874#issuecomment-445140760, but it is missing the stacked sharees.
This is due to the fact that this info is not yet available via dav.

To finish and merge #3320 I'll create this issue to not forget about it.

**Comment by AndyScherzinger** [comment]
#3320 has been merged, shipping with 3.6.0

**Comment by tobiasKaminsky** [comment]
We have this since a while.
