### ISSUE TITLE
Auto upload not respecting upload behavior setting

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#368]
### Actual behaviour
- during upload files are also copied to the nextcloud app's folder (thus is creates a copy) 
- thanks to the media scan this will then result in another Camera folder that contains all uploaded files

### Expected behaviour
- No copy of the photos to the nextcloud apps own storage
 
### Steps to reproduce
1. Configure Instant upload behavior for Camera and set "Original file will be" to "kept in original folder"
2. take a picture(s)
3. picture(s) get uploaded correctly
4. during upload files are also copied to the nextcloud app's folder (thus is creates a copy) 
5. thanks to the media scan this will then result in another Camera folder that contains all uploaded files

### Environment data
Android version: 7.1.1

Device model: Nexus5X

Stock or customized system: stock

Nextcloud app version: beta / syyncedFolder branch

Nextcloud server version: 10.0.1

this issue is related to #358

**Comment by tobiasKaminsky** [comment]
I pushed a fix, please test @AndyScherzinger

**Comment by AndyScherzinger** [comment]
Yay! Just tested it and it now respects the setting :+1:
