### ISSUE TITLE
Auto upload starts also on mobile network

### ISSUE THREAD

**Issue by luckyhandler** [nextcloud/android#3681]
### Actual behaviour
- Nextcloud starts auto upload also when not connected to any WiFi. The constant notifications and triggers to auto upload data which is not possible drain the battery and are simply annoying.

### Expected behaviour
- When no WiFi is connected the upload should not start or in any case stop as soon as the WiFi is disconnected. 
 
### Steps to reproduce
1. Activate auto upload
2. Check "Only upload on unmetered Wi-Fi
3. Change connection to mobile

### Environment data
Android version: 9.0 / 8.0

Device model: Sony Xperia XZ3 / OnePlus 5

Stock or customized system: Stock and customized

Nextcloud app version: 3.5.0

Nextcloud server version: 14.0.4

 ![](https://i.imgur.com/MIefM9r.jpg)

**Comment by itsmortoncornelius** [comment]
@tobiasKaminsky any ideas?

**Comment by lachlan-00** [comment]
I've noticed this too. Since the chunking update in 3.5.0 auto upload has been completely useless.

**Comment by itsmortoncornelius** [comment]
did anyone look into this yet?

**Comment by benedetto** [comment]
Same over here. Samsung Galaxy S7, Nextcloud App Version 3.6.2 Android.
