### ISSUE TITLE
No push notifications

### ISSUE THREAD

**Issue by OOmatrixOO** [nextcloud/android#3685]
### Actual behaviour
I installed the app from google play store. For example, if someone uploads a new file to a shared folder, I will not receive any notification.

### Environment data
Android version: 7.0 / MIUI 10.2

Device model: Redmi Note 4

Stock or customized system: stock

Nextcloud app version: 3.5.0

Nextcloud server version: 15.0.4

**Comment by tobiasKaminsky** [comment]
Can you open up our app and go into "Notifications" do you see a snackbar on the bottom showing an error?

**Comment by OOmatrixOO** [comment]
Thanks for your reply.
No there is no snackbar.

**Comment by tobiasKaminsky** [comment]
Then it means that the registration to the push notification server was successful.
Can you try to mention your user with another user in a file's comment, so that you get a new push notification?
Maybe it was just temporary hiccup.

**Comment by OOmatrixOO** [comment]
Ok that works. But without mention not. Should that be so? Do notifications only go with a mention?

**Comment by tobiasKaminsky** [comment]
@nickvergessen is there somewhere a list what triggers a push notification?

**Comment by nickvergessen** [comment]
All notifications are pushed

**Comment by OOmatrixOO** [comment]
What is all? If someone load a new file in a shared folder i should receive a push notification?
I have no notification.

**Comment by nickvergessen** [comment]
That does not show a notification, so of course it's not pushed.

**Comment by OOmatrixOO** [comment]
And what are pushed? Only mentions?

**Comment by nickvergessen** [comment]
I can't tell you, but at least those apps are known to me:
> ![bildschirmfoto von 2019-02-28 20-30-41](https://user-images.githubusercontent.com/213943/53593001-d0299f80-3b97-11e9-9599-e9f356b41604.png)

In which events they push, I can't tell you either.

**Comment by OOmatrixOO** [comment]
Ok that's a pity, of course, that such simple things as sharing a new file have no notification. 

Unfortunately, only the email notification remains. Is this something planned for the future?

Thank you for your help and education.

**Comment by tobiasKaminsky** [comment]
Please ask and discuss this in server repo, as there are the server devs (they do not read this repo, but only if they are mentioned).

As the original problem was that no push notification was received and this is "fixed", I'll close it.
