### ISSUE TITLE
Developer request

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/android#3686]
**Developer request:**
to download new translations from Transifex when publishing a development version.
This will be helpful for translators who want to see the translation changes made to make any corrections.

We also want to see our work.
Thanks.

**Comment by AndyScherzinger** [comment]
@Valdnet This is happening already! We auto integrate all translations every night. A new dev release is auto created whenever a non-translation change has been made on that day, see e.g. https://github.com/nextcloud/android/releases/tag/dev-20190228
You can also run the app via f-droid and check for updates within the app's settings: https://f-droid.org/de/packages/com.nextcloud.android.beta/

Nice thing: dev version can be run side-by-side with the stable release :)

**Comment by Valdnet** [comment]
> This is happening already!

But it is made only after the release of the Dev version.

[tx-robot] updated from transifex
nextcloud-bot committed **8 hours ago**

daily dev 20190228
tobiasKaminsky committed **11 hours ago**

> Nice thing: dev version can be run side-by-side with the stable release :)

I know and use the Dev version 😉

**Comment by AndyScherzinger** [comment]
Ah, okay, my mistake

@tobiasKaminsky can we flip transifex & dev build?

**Comment by tobiasKaminsky** [comment]
> @tobiasKaminsky can we flip transifex & dev build?

I can do this, but please note that we build & release only a new dev version if there are actual code changes. 
Changing transifex does not trigger a new dev version, as we then would have every day a new version, which is especially on F-Droid too often.

**Comment by Valdnet** [comment]
@tobiasKaminsky Can you manually download translation from transifex before the release of the Dev version?

**Comment by tobiasKaminsky** [comment]
I can do this, but then it is somehow out of sync with latest master.
So I currently changed the order:
(berlin time:)
- ~2:50 Transifex
- 3:30 dev build (only publish if also code changes)

I am not sure when F-Droid is checking, but hopefully it is not that early…

**Comment by AndyScherzinger** [comment]
> I can do this, but then it is somehow out of sync with latest master.

Why is it out of sync then?

**Comment by Valdnet** [comment]
@tobiasKaminsky I am happy to. As will be good, we will close the issue.

**Comment by tobiasKaminsky** [comment]
> > I can do this, but then it is somehow out of sync with latest master.
> 
> Why is it out of sync then?

When I manually pull translated files from Transifex even if they are not yet merged to master.

**Comment by Valdnet** [comment]
Now it is great. Translators can check their translation changes with each new version of dev 😉 

> I am not sure when F-Droid is checking, but hopefully it is not that early…

@tobiasKaminsky according to you, is everything well too?

Thanks again.

**Comment by tobiasKaminsky** [comment]
> Now it is great. Translators can check their translation changes with each new version of dev

Glad you like it.

> > I am not sure when F-Droid is checking, but hopefully it is not that early…
> 
> @tobiasKaminsky according to you, is everything well too?

Should be fine, it seems it is build later than 4 am, so closing.

**Comment by Valdnet** [comment]
@tobiasKaminsky new translations from Transifex have not been downloaded for two days. Has something changed?

> 
> Commits on Mar 6, 2019
>     daily dev 20190306 
> Commits on Mar 5, 2019 
>     daily dev 20190305

**Comment by tobiasKaminsky** [comment]
Strange.
On 2019-03-05 transifex bot ran, but nothing new 
On 2019-03-06 the bot did not even run
I started it manually now and it found new translations.

Thanks for the warning.

**Comment by Valdnet** [comment]
> On 2019-03-05 transifex bot ran, but nothing new
> On 2019-03-06 the bot did not even run

Maybe, if he does not find anything new, next time (the next day) he does not resume anymore so as not to generate traffic. And the settings are good?

**Comment by tobiasKaminsky** [comment]
Bot is always running once a day, independent from the previous result.
Maybe it was just a temporary hiccup…
