### ISSUE TITLE
Implement "Always ask for a password" on Android for public links

### ISSUE THREAD

**Issue by schiessle** [nextcloud/android#3687]
Nextcloud knows two settings for passwords and public links: "enforce password" and "always ask for a password". Always ask is basically a suggestion, we ask the user to set a password but they are free to continue without a password.

"Enforce password" works nicely on Android, but not "Always ask for password".

**Comment by tobiasKaminsky** [comment]
So it should just open up a dialog asking for a password, but user is free to also close this dialog?
How is this UX wise handled in webUI?

**Comment by joshtrichards** [comment]
Fixed in #3989
