### ISSUE TITLE
Sabre DAV Exception

### ISSUE THREAD

**Issue by ClepToManix** [nextcloud/android#3691]
Hallo,

we had an bug in our nextcloud installation. Since we have updated nc those errors are still appearing. In nextcloud app running on android the "new account page" always pop up on this devices. The only solution is, to deaktivate network, delete the account and add them again.

thanks for your help

### Server configuration

**Operating system**:
Ubuntu Server 18.04
**Web server:**
Apache Webserver
**Database:**
mysql 10.0.38
**PHP version:**
7.3.2
**Nextcloud version:** (see Nextcloud admin page)
15.0.4.0
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 15.0.2.0
**Where did you install Nextcloud from:**
implemented installer
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>


```Group Folders


### Logs
Fatal - Webdav:
Sabre\DAV\Exception\ServiceUnavailable: OC\User\LoginException: Nutzer deaktiviert
/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Auth/Plugin.php - line 200:

OCA\DAV\Connector\Sabre\Auth->check(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Auth/Plugin.php - line 150:

Sabre\DAV\Auth\Plugin->check(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})

<<closure>>

Sabre\DAV\Auth\Plugin->beforeMethod(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})

/var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105:

call_user_func_array([ Sabre\DAV\ ... "], [ Sabre\HTTP ... }])

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 466:

Sabre\Event\EventEmitter->emit("beforeMethod", [ Sabre\HTTP ... }])

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254:

Sabre\DAV\Server->invokeMethod(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})

/var/www/nextcloud/apps/dav/appinfo/v1/webdav.php - line 80:

Sabre\DAV\Server->exec()

/var/www/nextcloud/remote.php - line 163:

require_once("/var/www/kw ... p")




Error - no app in context:
OC\User\LoginException: Nutzer deaktiviert
/var/www/nextcloud/lib/private/User/Session.php - line 576:

OC\User\Session->completeLogin("*** sensiti ... *")

/var/www/nextcloud/lib/private/User/Session.php - line 338:

OC\User\Session->loginWithPassword("*** sensiti ... *")

/var/www/nextcloud/lib/private/User/Session.php - line 420:

OC\User\Session->login("*** sensiti ... *")

/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Auth.php - line 130:

OC\User\Session->logClientIn("*** sensiti ... *")

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Auth/Backend/AbstractBasic.php - line 105:

OCA\DAV\Connector\Sabre\Auth->validateUserPass("*** sensiti ... *")

/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Auth.php - line 253:

Sabre\DAV\Auth\Backend\AbstractBasic->check(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})

/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Auth.php - line 155:

OCA\DAV\Connector\Sabre\Auth->auth(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Auth/Plugin.php - line 200:

OCA\DAV\Connector\Sabre\Auth->check(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Auth/Plugin.php - line 150:

Sabre\DAV\Auth\Plugin->check(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})

<<closure>>

Sabre\DAV\Auth\Plugin->beforeMethod(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})

/var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105:

call_user_func_array([ Sabre\DAV\ ... "], [ Sabre\HTTP ... }])

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 466:

Sabre\Event\EventEmitter->emit("beforeMethod", [ Sabre\HTTP ... }])

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254:

Sabre\DAV\Server->invokeMethod(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})

/var/www/nextcloud/apps/dav/appinfo/v1/webdav.php - line 80:

Sabre\DAV\Server->exec()

/var/www/nextcloud/remote.php - line 163:

require_once("/var/www/kw ... p")

**Comment by skjnldsv** [comment]
Moving then :racing_car:

**Comment by tobiasKaminsky** [comment]
Hm. First I thought it would be the same like #3623, but if it is working after deleting the account, it cannot be the same.

@ClepToManix do you use any special things? 2FA? LDAP?

**Comment by ClepToManix** [comment]
No, nothing. After deleting it works for a few days. Actually the only solution to remove the accounts which are affected from this bug.

**Comment by tobiasKaminsky** [comment]
> After deleting it works for a few days.

Do I understand you correctly that a working account fails after some days, and after removing the account locally on the device, it works again for only a few days?

**Comment by ClepToManix** [comment]
> > After deleting it works for a few days.
> 
> Do I understand you correctly that a working account fails after some days, and after removing the account locally on the device, it works again for only a few days?

Yeah, right.

**Comment by tobiasKaminsky** [comment]
> > Do I understand you correctly that a working account fails after some days, and after removing the account locally on the device, it works again for only a few days?
> 
> Yeah, right.

@nextcloud/server-triage this sounds to me as if somehow the app tokens get removed/invalidated?

**Comment by ClepToManix** [comment]
I dont know. 
In Error log i found this one:
`Object of class OCA\GroupFolders\Versions\GroupVersion could not be converted to string at /var/www/kwolkemk/apps/groupfolders/lib/Versions/ExpireManager.php#126`


Maybe this error connected with the main error

**Comment by ClepToManix** [comment]
Updated to Nextcloud version 15.0.5. Still the same error

**Comment by blizzz** [comment]
@icewind1991 perhaps groupfolders related?
