### ISSUE TITLE
Uploading picture fails

### ISSUE THREAD

**Issue by themagicm** [nextcloud/android#3692]
### Actual behaviour
When selecting a picture to upload from the photo gallery on my android phone, selecting Nextcloud (sign in of course) then selecting Upload in the client, it fails.   If I view the failed picture in nextcloud and retry, it will work.

### Expected behaviour
- Tell us what should happen
 
### Steps to reproduce
1. Go to photo gallery on your Android device
2. Select photo
3. Select share
4. Select Nextcloud client in the applications list
5. Sign into nextcloud with the app
6. Select upload
7.  Hit home and go to main screen
8.  Wait for it to fail
9.  Select failed upload notification and you get sent back to nextcloud client.   Retry.  Works.

to make it work all the time:
1.  Open Nextcloud client app
2.  Click + to upload
3.  Find picture
4.  Upload.   
5.  No issues this way.  

### Environment data
Android version:
8.0.0

Device model: 
SM-N950U (note 8)

Stock or customized system:
stock

Nextcloud app version:
3.5.0

Nextcloud server version:
15.0.2

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by soofstad** [comment]
Also started to see this issue with AutoUploads just after I upgraded the server to 15.0.5 from 15.0.3

**Comment by tobiasKaminsky** [comment]
> 5\. Sign into nextcloud with the app

What do you mean with this? After sharing a file to NC app there is no need to sign in? You should directly see the file list?

All it all, I tested it with google photos app and it worked fine. 
What error message do you see in upload queue?

@soofstad this seems to be a different problem, can you open up a new issue for this?

**Comment by themagicm** [comment]
Meaning...

When I go to my "Gallery" in Android, select a photo, select share.  My apps list pops up which allows me to choose how to share.  I select nextcloud client.  Next Cloud client asks to "Verify Identity" which is what I mean by log in.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by tobiasKaminsky** [comment]
> Next Cloud client asks to "Verify Identity" which is what I mean by log in.

can you show a screenshot of this?
