### ISSUE TITLE
Files in wrong folder

### ISSUE THREAD

**Issue by ero-sennin95** [nextcloud/android#3694]
Hello, the file manager show me files than are normally in another folder...

**Comment by tobiasKaminsky** [comment]
Can you give us more details, e.g. also with file name/paths (filenames can be replaced by arbitrary values).

**Comment by ero-sennin95** [comment]
Hello, i find the pb. This happened when. Nomedia file is present. I removed it.then it's ok...

**Comment by AndyScherzinger** [comment]
Thanks for the feedback @ero-sennin95. I'll close the issue then. Feel free to reopen in case the issue comes back.
