### ISSUE TITLE
Files can only be synced to internal phone memory

### ISSUE THREAD

**Issue by orsotron** [nextcloud/android#370]
### Actual behaviour
All synchronized files are stored in internal phone/device memory with the risk of running out of memory.

### Expected behaviour
There should be a parameter to enable storage of synced files to sd cards/external memories
 
### Steps to reproduce
1. select a file or folder and click on synchronize
2. All synchronized files are stored on internal device memory

### Environment data
Android version: Any

Device model: tried on samsung galaxy tab 2, galaxy S mini 5, galaxy S4, galaxy S4 mini 

Stock or customized system:

Nextcloud app version: 1.3

Nextcloud server version: 10.01

**Comment by AndyScherzinger** [comment]
Hi @orsotron 

SD card support will be part of the next stable release 1.4.0 --> #92 (already implemented)
