### ISSUE TITLE
problems with umlauts or spaces in directory name

### ISSUE THREAD

**Issue by krebsi83** [nextcloud/android#3701]
[Nextcloud Android App v. 3.5.0 - Playstore-Version]
The app currently has problems with umlauts or spaces in directory names.

Example:
Directory name "Gespräch" >> No files are displayed!
Renamed to "Gespraech" >> files are displayed.

Example:
Directory name "PDF 2019" >> >> No files are displayed!
Renamed to "PDF2019" >> files are displayed.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky Just tested this (server 15.0.5) and this works like a charm for me.

**Comment by krebsi83** [comment]
Oops! We are still working with version 14.08 ... 🤔 I will make an update to version 15 this evening and test it again.

**Comment by AndyScherzinger** [comment]
@krebsi83 thanks for the feedback. Nevertheless that shouldn't make a difference in my opinion since I am not aware of any Umlaut or space issue with the Android client and any server version. Maybe @tobiasKaminsky has an idea.

**Comment by tobiasKaminsky** [comment]
Hm. We did not changed anything in this regard.
Also there are lots of other languages with "special" characters and they work fine.

So I assume it is something with the server.
Are the files on an external storage? Is there something else special with the setup?

**Comment by krebsi83** [comment]
System: Ubuntu Server 16.04 on Windows Hyper-V Server
Files are stored on an ext4 disk image which is mounted under /datastore

**Comment by tobiasKaminsky** [comment]
If this persists after NC15 upgrade, can you create us a test account, test if the problem occurs also there and if so send the credentials to tobias at nextcloud dot com with a reference to this issue?

**Comment by krebsi83** [comment]
after update to NC15 the problem ist still there...
but with new user and new folder there is no problem...

**Comment by tobiasKaminsky** [comment]
@krebsi83 is this only on android? 
Can you also try it with a webdav browser: https://docs.nextcloud.com/server/15/user_manual/files/access_webdav.html

If this works, is there an old user that you can share with me, so I can debug it on android side?

**Comment by krebsi83** [comment]
I have tried it with WebDavNavLite on Android. No problems ... File in folder with umlauts is displayed. (see the screenshot) 
![image](https://user-images.githubusercontent.com/48238011/53875706-6c72fc80-4005-11e9-88e5-a9dde837fca0.png)
![image](https://user-images.githubusercontent.com/48238011/53875737-84e31700-4005-11e9-9e8f-2457cf3fe443.png)

**Comment by krebsi83** [comment]
I have uninstalled the Nextcloud Android app and reinstalled it. 
**Now files are also displayed in the umlaut folder.**
😃👍🍻

**Comment by tobiasKaminsky** [comment]
Glad that it works now, but still it is strange that re-installation was required…
