### ISSUE TITLE
CODE4: New office document always odt/ods

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/android#3703]
### Actual behaviour
I use Collabora Code 4.0 and edit office document within the app. It works awesome! :)
In the Collabora Online settings on the server I use "Office Open XML"
Wen I create new office files in the Browser the filename is xxx.docx/xlsx
Wen I create new office files in the App the filename is xxx.odt/ods

### Expected behaviour
The same behavour as in the Browser. Create new files with the name xxx.docx/xlsx when "Office Open XML" is used.

**Comment by tobiasKaminsky** [comment]
@juliushaertl @rullzer this is not available via capabilities.
Or…should it be at all? 
Shouldn't the /ocs/v2.php/apps/richdocuments/api/v1/templates/new endpoint obey this setting?

**Comment by juliushaertl** [comment]
@tobiasKaminsky The OCS endpoint just takes the filename with extension, at least on the files app, I assume it is the same on android. But you are right, we either should expose this to capabilities or just allow calling the template/new endpoint without a file extension and let the backend pick the proper extension.

**Comment by tobiasKaminsky** [comment]
Hm. On Android we pass a template to /ocs/v2.php/apps/richdocuments/api/v1/templates/new.

I am unsure what should be done, but as an user I would expect that all files are "open xml", even if the template itself is e.g. odt.
So this would require an internal conversion?

**Comment by juliushaertl** [comment]
@tobiasKaminsky This will be handled by collabora, since they open the template and use save us to actually store the file then. 

/ocs/v2.php/apps/richdocuments/api/v1/templates/new also takes the path as an argument. Do you manually append the file ending there on android?

**Comment by tobiasKaminsky** [comment]
ping @juliushaertl :-D

**Comment by tobiasKaminsky** [comment]
ping @juliushaertl what is the current status on your side?
