### ISSUE TITLE
HTTP Basic Authentication

### ISSUE THREAD

**Issue by atsp** [nextcloud/android#371]
### Actual behaviour
It's not possible to connect Nextcloud instance from mobile client (incl. Beta) which is using HTTP Basic Authentication (logins-passwords are the same for web-server http-auth. and Nextcloud). Nextcloud itself works fine with it (authenticate directly with it, no need to enter login/password to web form), DAVDroid works fine too. Neither of them have any problem-related settings.

### Expected behaviour
I would like you to consider a possibility to use a basic-http-auth in app.
 
### Steps to reproduce
1. Enter URL and credentials
2. Testing connection -> Wrong username and password

### Environment data
Android version: 6.0.1 Cyanogenmod 13.0-ZNH2K stable
Device model: OnePlus One A0001 (bacon)

Stock or customized system: stock

Nextcloud app version: stable 1.3.1 & beta 20161102

Nextcloud server version: 10.0.1 (stable)

#### Web server error log
192.168.1.1 - - [06/Nov/2016:10:11:18 +0200] "GET /cloud/status.php HTTP/1.1" 401 188 "-" "Mozilla/5.0 (Android) nextcloud-android/20161102"

#### Nextcloud log (data/nextcloud.log)
no logs

**Comment by rfc2822** [comment]
Do you have a password with special characters?

**Comment by atsp** [comment]
Only one underline

**Comment by eugenio** [comment]
I think i have the same problem my password contains and at mark

**Comment by AndyScherzinger** [comment]
Hi @atsp and @eugenio can you send me test credentials to your server instances where the test account's passwords would also have the same characteristics? I just tested the login against my personal server with two users where one's password contains a _ and the other one's an @. So there is no general special characters issue with the login, but rather something which seems to be related to client/server setup.
The easiest way to send my such (private) information would be via PM in our forum, my username there is just "Andy" https://help.nextcloud.com/

**Comment by eugenio** [comment]
You are right @AndyScherzinger the issue persist changing to a simpler password without special characters. I seem to be unable to find how to send pm on the help forum

**Comment by AndyScherzinger** [comment]
![2016-11-30 15_40_26-nextcloud community](https://cloud.githubusercontent.com/assets/1315170/20756553/6595341e-b713-11e6-9110-e34a8b5cce56.png)top right, avatar, "Mail icon" on the next screen on the left choose "new message" and as a recipient type my forum nick Andy :)
If that doesn't work just post your Forum nick here and I'll send you a message to which you then be able to reply :)

**Comment by eugenio** [comment]
my nickname is : eugenio

**Comment by AndyScherzinger** [comment]
PM sent :)

**Comment by atsp** [comment]
It doesn't work for me either. My nick is on the screenshot.
![screen shot 2016-11-30 at 17 12 50](https://cloud.githubusercontent.com/assets/9769008/20757907/baefca52-b720-11e6-9367-911f25e24225.png)

**Comment by AndyScherzinger** [comment]
@atsp just sent you a PM
@eugenio just analyzed your login error. Yours is due to the fact that your server doesn't send a reply within 10 seconds (actually takes > 30 seconds).

**Comment by eugenio** [comment]
@AndyScherzinger thanks for your kind help!

**Comment by AndyScherzinger** [comment]
Always a please to help! :)

**Comment by atsp** [comment]
So I created a new user with password without any special characters and it didn't solved the problem.
Also I sent you my server's address and credentials.
Thank you!

**Comment by eugenio** [comment]
the issue was cause in my case by the bruteforce attack protection. in order to make the server and all the connected apps (android and owncloud linux client for example) work properly i had to disable that feature and drop the table of the failed login attempts. In my case the offender ip was the router internal ip.

**Comment by AndyScherzinger** [comment]
@eugenio so the matter is resolved in your setup? :)

**Comment by eugenio** [comment]
Seems so.  But the brute force attack protection is disabled and this is a
security issue.

Il 01 dic 2016 4:45 AM, "Andy Scherzinger" <notifications@github.com> ha
scritto:

**Comment by atsp** [comment]
So I created a new user with password without any special characters and it didn't solved the problem.
Also I sent you my server's address and credentials.
Thank you!

**Comment by AndyScherzinger** [comment]
Hi @atsp just tried out the credentials you sent me and I get an HTTP error for your server :(
```
Connection check at https://****masked****: Operation finished with HTTP status code 401 (fail)
```

When I call this URL in the browser I directly get a htaccess-style login popup. Not sure if this is the reason for the 401 (at a later point on the HTTP app request) or if it is related to any missing configuration in your nginx.

**Comment by atsp** [comment]
Hi, Andy! Did you tried username & password in web browser?
Please, see first message of the topic - yes, my server is protected by HTTP Basic Authentication

**Comment by AndyScherzinger** [comment]
Hi, yes I did tried it in the browser and that does work and I can log in there (while it is impossible for me to then logout again). Nevertheless for whatever reason the Android client gets a HTTP401 reply

**Comment by AndyScherzinger** [comment]
@MorrisJobke @rullzer @LukasReschke any idea what needs to or could be done here?

**Comment by LukasReschke** [comment]
The famous base64 encoding problem strikes again I assume. @AndyScherzinger can you forward me the credentials?

**Comment by AndyScherzinger** [comment]
Invited you to the message in the forum :)

**Comment by atsp** [comment]
@LukasReschke please keep the server address private, thank you!

**Comment by zaroth** [comment]
any news on this? Encountered the exact same issue as @atsp with app version 1.4.0, server version 10.0.1. Nginx is used as the proxy with http basic auth, https enabled with forced redirect from http, nextcloud is running on uwsgi+php plugin.

DavDroid and Firefox don't have any issues with the http_basic auth, only the Nextcloud Android app complains. Happy to provide any other details.

**Comment by AndyScherzinger** [comment]
Hi @zaroth only thing that would help us tracking it down, looking to implement a solution and testing that one would be a test account for your server (since I personally do not run such a setup or have the ability to set it up somewhere). So that would help. Easiest would be a PM on the forum to me (user: andy) and to @tobiasKaminsky (user tobiasKaminsky): https://help.nextcloud.com/
No further details needed at the moment, are you running any "special" ciphers? Android version?

**Comment by zaroth** [comment]
I just created an account ( https://help.nextcloud.com/users/zaroth ), but it seems that I don't have the ability to send private messages there - the "Message" button is missing in user's profiles. Could you suggest something here?

**Comment by zaroth** [comment]
So I fiddled around with the config of my server and changed the cipher to one that is possible to be decrypted in Wireshark without much fiddling when the private key is known (for the record, it was `AES128-SHA` in nginx and openssl, TLS1/1.1/1.2 used). Then I compiled the latest master of this repo in Android studio and tried to run the whole interaction in AVD and capture the packets. Then ran and captured it again with Firefox to compare.

Discovered the following behaviors:

*Firefox*
- I enter in the address bar http://nextcloud.example.com
- FF sends GET / on port 80 to server nextcloud.example.com, receives response "301 moved permanently to https://nextcloud.example.com/"
- FF makes a successful TLS handshake on port 443 with server nextcloud.example.com
- FF sends GET / on port 443 to server nextcloud.example.com, receives response "401 unauthorized"
- at this point FF displays the user prompt for http_basic_auth style username and password, I enter the test credentials there and hit enter
- FF sends GET / on port 443 to server nextcloud.example.com with line `Authorization: Basic dGVzdDp0ZXN0MTIz` in header, this time I successfully get straight to nextcloud, bypassing the login screen (and unable to logout, as @AndyScherzinger noticed, but it's to be expected in this setup)
- all the future requests from FF include the `Authorization` line in the header, resulting in successful responses

*Android NextCloud app*
- I enter login credentials on the screen and then fill the server address field with `nextcloud.example.com` (as https:// is already assumed)
- app makes a successful TLS handshake on port 443 with the server
- app sends `GET /status.php` on `nextcloud.example.com` port 443, receives 401 Unauthorized
- app makes a successful TCP handshake on `nextcloud.example.com` port 80
- app sends `GET /status.php` on `nextcloud.example.com` port 80, receives `301 moved permanently to https://nextcloud.example.com/status.php`
- app again sends `GET /status.php` on `nextcloud.example.com` port 443, receives 401 Unauthorized
- app gives up and displays "wrong username or password" message on the screen

**Comment by zaroth** [comment]
After a bit more tinkering, it became apparent that the issue lies in the [linked function, lines 77-102. Note that it operates in three steps:

1. Get status info from `/status.php`
2. If step 1 was successful, get authorization method info
3. Merge results

With this flow, `/status.php` being behind basic auth (and probably also any other) barrier causes the whole thing to crash. What should be done to fix this is either:
 - swap order of steps 1 and 2
 - or if step 1 fails, do step 2 and try step 1 again using auth method info gained from step 2.

To confirm my suspicions, I added an exception in nginx (so server-side) for just `/status.php` to not require any auth. Sure enough, the (current) client worked with that workaround.

**Comment by zaroth** [comment]
After trying to fix it, there's unfortunately no way to fix it in a simple way - changes in https://github.com/nextcloud/android-library/blob/master/src/com/owncloud/android/lib/resources/status/GetRemoteStatusOperation.java and maybe even https://github.com/nextcloud/android-library/blob/master/src/com/owncloud/android/lib/common/OwnCloudClient.java may be required. The cause is fact that the remote status info is pulled via these external owncloud library functions, which don't currently offer a way to use any kind of authentication for the `/status.php` GET from what I've found.

So either the calling code should take into account that it may not get the status result it expects and still proceed, or the called library should take more parameters and learn how to get the status from behind auth. Leaving this decision up to project maintainers here, I'm done investigating. :-)

**Comment by atsp** [comment]
Great investigation, zaroth! Thank you

**Comment by ibexmonj** [comment]
please let me know if i can help with any logs or any debugging attempts.

**Comment by zaroth** [comment]
I think at this point I've triaged the problem enough (`/status.php` is requested without using provided http basic credentials). All that's left is for a dev to decide upon a solution and implement it.

In the meantime, as mentioned above:

## A workaround (server-side)
Make only `/status.php` accessible without authentication. Example in nginx:

```
location = /status.php {
  auth_basic off;
}
```

**Comment by tobiasKaminsky** [comment]
As talked with @LukasReschke the basic authentication will not work with our new weblogin flow (#1148)...

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky close then?

**Comment by mario** [comment]
Yes

**Comment by andreas-bulling** [comment]
Would be quite nice if this worked. Just ran into the same issue - HTTP auth and although I've disabled it for status.php the Android client can't connect

**Comment by andreas-bulling** [comment]
Same problem here. What's strange - it works totally fine with the MacOS client. Only the linux clients have this problem (or maybe it's because I installed the linux clients from scratch and had used the MacOS one for a while already?)

**Comment by ShaunCurrier** [comment]
I'm also finding that HTTP Basic Auth doesn't work on the Android client.  When entering our server URL of the form user:pass@mysite.com, the app errors with "Wrong username or password."

**Comment by l-Legacy-l** [comment]
Is there any workaround to make it work ?

**Comment by tobiasKaminsky** [comment]
You can try to create an app token, and then create a link in format:
https://docs.nextcloud.com/server/latest/developer_manual/client_apis/LoginFlow/index.html#obtaining-the-login-credentials

And add user:pass to server url.

**Comment by chris-free** [comment]
> You can try to create an app token, and then create a link in format: https://docs.nextcloud.com/server/latest/developer_manual/client_apis/LoginFlow/index.html#obtaining-the-login-credentials
> 
> And add user:pass to server url.

This didn't work for me
