### ISSUE TITLE
Incorrect message and delete your favorite folder (file) from the folder "On device"

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/android#3714]
### 1. For a folder - "On device".
![obraz](https://user-images.githubusercontent.com/47037905/53879225-39813680-400e-11e9-9545-3045b12d8be4.png)
![obraz](https://user-images.githubusercontent.com/47037905/53882088-a1874b00-4015-11e9-898b-f991d14a748c.png)
### Actual behaviour
- Erroneous question when deleting a folder.

![obraz](https://user-images.githubusercontent.com/47037905/53879158-0c348880-400e-11e9-9a83-72fef2f03dde.png)
![obraz](https://user-images.githubusercontent.com/47037905/53882391-823ced80-4016-11e9-9bc6-d9325d2299e6.png)

### Expected behaviour
- The correct question when removing the folder.

![obraz](https://user-images.githubusercontent.com/47037905/53879050-c4adfc80-400d-11e9-9bc0-87745a78bc4c.png)
![obraz](https://user-images.githubusercontent.com/47037905/53882626-22931200-4017-11e9-9f4b-29461b3c4234.png)

### Steps to reproduce
1. Create a folder.
2. Mark the folder as a favorite.
3. Save to device.
4. Open from the menu "On device".
5. Delete your favorite folder.

### 2. For a file - "On device".
![obraz](https://user-images.githubusercontent.com/47037905/53879225-39813680-400e-11e9-9545-3045b12d8be4.png)
![obraz](https://user-images.githubusercontent.com/47037905/53882110-b5cb4800-4015-11e9-96da-4cf4274730a5.png)
### Actual behaviour
- Erroneous question when deleting a file.

![obraz](https://user-images.githubusercontent.com/47037905/53879777-97fae480-400f-11e9-9cec-d5f880c2ac6b.png)
![obraz](https://user-images.githubusercontent.com/47037905/53882851-b7960b00-4017-11e9-9f88-642c4d8b49d7.png)

### Expected behaviour
- The correct question when removing the file.

![obraz](https://user-images.githubusercontent.com/47037905/53879861-cbd60a00-400f-11e9-9c1c-ec592026954a.png)
![obraz](https://user-images.githubusercontent.com/47037905/53882922-eca25d80-4017-11e9-8851-9af4ac5999da.png)

### Steps to reproduce
1. Create a file.
2. Mark the file as a favorite.
3. Save to device.
4. Open from the menu "On device".
5. Delete your favorite file.

### Environment data
Android version: 6
Nextcloud app version: daily dev 20190306 commit: 7e1424a
Nextcloud server version: 15.0.4

**Comment by tobiasKaminsky** [comment]
Can you translate the dialogs so that we can understand what the problem is?

**Comment by Valdnet** [comment]
@tobiasKaminsky i translated the dialogues.

**Comment by tobiasKaminsky** [comment]
This was done on purpose:
- if you are "on device" you only shall delete files/folders "on device"
- if you are on "all files" you can decide whether to delete files/folders only on device or both.

**Comment by Valdnet** [comment]
The error applies only to the **favorite** folder or file that is on "On device".

![obraz](https://user-images.githubusercontent.com/47037905/54028555-af6bd600-41a5-11e9-9834-f9270f884050.png)

The following question arises:

![obraz](https://user-images.githubusercontent.com/47037905/54028661-12f60380-41a6-11e9-878e-24a9e385bbd5.png)
![obraz](https://user-images.githubusercontent.com/47037905/54028790-83048980-41a6-11e9-96ab-c148dcb78c14.png)

When confirming the deletion, the file is removed from the device and from the main folder.

The question should be a choice from which location to delete.

![obraz](https://user-images.githubusercontent.com/47037905/53882626-22931200-4017-11e9-9f4b-29461b3c4234.png)

Please, analyze again "Steps to reproduce" 😉

**Comment by Valdnet** [comment]
@tobiasKaminsky if you confirm the error, please re-open issues 😉

**Comment by tobiasKaminsky** [comment]
Now I understand.
Thank you for finding & reporting this bug!

**Comment by tobiasKaminsky** [comment]
Reference: https://github.com/nextcloud/android/issues/2718

@AndyScherzinger I am not quite sure about this long issue (#2718), but somwhere it is stated that remove should work the same on "on device" and "all files".

For some reason this was included:
https://github.com/nextcloud/android/blob/8971dc1442d0a53f9266d72fef4cf0ef37a1cc91/src/main/java/com/owncloud/android/ui/dialog/RemoveFilesDialogFragment.java#L100-L102

--> I would simply kill this: so you can delete everything if you want and always get the choice "yes, no, only local".

**Comment by tobiasKaminsky** [comment]
To check: 
- create a f1/f2/2.txt
- download this file
- go to on device
- delete f1
- should offer "only local", which then removes f1 locally recursive

**Comment by AndyScherzinger** [comment]
> --> I would simply kill this: so you can delete everything if you want and always get the choice "yes, no, only local".

@tobiasKaminsky agreed, I'd also vote for always having all options when it comes to "delete"

**Comment by AndyScherzinger** [comment]
ships with v3.6.0 🎉
