### ISSUE TITLE
Autoupload - Android 9.0 does not work

### ISSUE THREAD

**Issue by Excel1** [nextcloud/android#3721]
### Actual behaviour
install nextcloud
set battery optimization off
log in
set autoupload (pictures)
choose remote folder
click save

nothing happens. 
wait several days...
nothing uploaded.
(only new created Pictures after set "autoupload" will be uploaded)

### Expected behaviour
install nextcloud
set battery optimization off
log in
set autoupload (pictures)
choose remote folder
click save

uploading started.
wait several days...
uploaded.
(New and old Pictures. / Like a sync)
 
### Steps to reproduce
1. install nextcloud
2. set battery optimization off
3. log in
4. set autoupload
5. choose remot folder
6. click save

### Environment data
Android version: 9.0

Device model: SM-N950F

Stock or customized system: Stock

Nextcloud app version: 3.5.0 / 3.6.0 / 3.6.2 / 3.7.1 / 3.8.0

Nextcloud dev app version: 20190815

Nextcloud server version: 15.0.5 / 16.0.0 / 16.0.1 / 16.0.3

### Interesting
with latest iOS on iPhone 5S works
new Pictures (recently shot or downloaded) will be uploaded. Only old pictures wont be uploaded.

### ChangeLog
+ Added Details
+ Added Nextcloud dev app version
~ Updated Server/App Version
--
~ Updated Server/App Version

**Comment by Baron164** [comment]
I'm having the same issue with my Pixel XL running Android 9.

**Comment by xopez** [comment]
Same here. Honor 10 Android 9
Model: COL-L29

**Comment by thechonta** [comment]
Probably Files smaler than 1 MB will be uploaded.
Try the APK of 3.4.2 this is the last working App on my Huawei P20 Pro.
The 3.6.1 did not work also for me. It is not the Server it is something in the App itself.
Same App aon an LG G6 works, but on my P20 Pro only the 3.4.2 will work.

**Comment by SimonMellerin** [comment]
I've the same issue on my device (Xiaomi Mi A2 Lite with Android 9)
I'm currently with Nextcloud App v3.7.0 RC3 from Fdroid

Each time I try to set up autoupload a pop up says me :

**Battery Optimization:**
Battery optimiziation may be active on your device. Autoupload can work properly only if you exlude this app from optimization
(I'm translating from french so it may not be this exact message)

In this popup I click on the 'Desactivate' button, then nothing happened :/

**Comment by Excel1** [comment]
@tobiasKaminsky is this expected that only new pictures will be uploaded? 

Maybe that is more an approvement than a bug (to autoupload old pictures too with the same folder structure).

**Comment by memen45** [comment]
It is intended behavior as confirmed [here](https://github.com/nextcloud/android/issues/4004#issuecomment-497436425).

Therefore this issue seems to be more a feature request and as such exactly equivalent to #2812. The good news is that it seems like this feature is currently in development: #2873!
