### ISSUE TITLE
beta: new instant upload only uploads one picture (when wifi trigger is hit)

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#373]
### Actual behaviour
-app uploads only one picture during instant upload

### Expected behaviour
-app should upload all pictures
 
### Steps to reproduce
1. Set upload to wifi only
2. Take some pictures without wifi
3. Enable wifi

Result: 
* It only uploads the one picture, most of the time the last one taken.

### Environment data
Android version: 7.1.1

Device model: Nexus5X

Stock or customized system: stock

Nextcloud app version: beta-20161105

Nextcloud server version: 10.0.1

**Comment by ncyclon** [comment]
I have similar problem, in log I see "Instant picture upload disabled, ignoring new picture" but it's enabled.

**Comment by tobiasKaminsky** [comment]
> "Instant picture upload disabled, ignoring new picture" 

this is from the "old" instant upload and can be safely ignored.
I fixed it and it will be available in the next beta.
