### ISSUE TITLE
Cant't upload pictures/files after folder creation

### ISSUE THREAD

**Issue by blu-IT** [nextcloud/android#3738]
### Actual behaviour
- When I select pictures on my phone for upload and create a new folder via app on nextcloud, then an upload is not possible. The upload button is not available any more.
I have to switch back to my gallery on the phone and select all the pictures again for upload - then it works.

### Expected behaviour
- Upload button should be available and upload of already selected pictures should be possible.
 
### Steps to reproduce
1. Select pictures
2. Create new folder with nextcloud app
3. Try upload.

### Environment data
Android version: 8.1.0

Device model: 
Samsung Galaxy J5 (2017)
SM-J530F

Nextcloud app version: 3.5.1 RC1

Nextcloud server version: 14.0.7

**Comment by nickvergessen** [comment]
My workaround is:
Navigate out of the folder and in again, upload is possible now
