### ISSUE TITLE
Menu "Deleted files"

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/android#3747]
### Actual behaviour
- The "Deleted files" item is missing from the application menu.

![obraz](https://user-images.githubusercontent.com/47037905/54280526-03a4fa80-4598-11e9-8132-adf4801d849c.png)

### Expected behaviour
- Display in the "Deleted files" application menu.

![obraz](https://user-images.githubusercontent.com/47037905/54280508-fd168300-4597-11e9-9530-5856e3595046.png)

### Steps to reproduce
1. Open the application menu.

"Deleted files" only appear after opening "Uploads" or "Notifications".

![obraz](https://user-images.githubusercontent.com/47037905/54281246-985c2800-4599-11e9-9d5d-9f4e72f0db9a.png)

### Environment data
Android version: 6

Nextcloud app version: 3.5.1 RC2 97ee2e3

**Comment by AndyScherzinger** [comment]
@Valdnet which server are you using? Does this issue persist over time?
The menu item is only display in case the trashbin is activated in the servers configuration I think.

But @tobiasKaminsky knows best.

**Comment by Valdnet** [comment]
>  which server are you using? Does this issue persist over time?

Nextcloud 15.0.5

The user account has place for unlimited files.

**Comment by Valdnet** [comment]
The dev-20190313 b5931a3 version also has the same problem on one Nextcloud.

This is probably due to the fact that this account is set in the file "config":
` 'defaultapp' => 'phonetrack',`

**Comment by AndyScherzinger** [comment]
Then I'd close this issue since the menu item is hidden in case the server doesn't tell that it supports the trash bin (this info is cached!) so _if_ the server had a hiccup of some kind it'll take things like either time, account swicthes or else for the client to check this again.

**Comment by tobiasKaminsky** [comment]
We refresh the server capabilities on account switch or after 10th time of opening the app.
So it might be that the capabilities were fetched a bit too late on initial setup and thus the trashbin did not show up.
