### ISSUE TITLE
Enable users to activate logging, provide access to log file

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#375]
### Actual behaviour
-stable releases have logging disabled

### Expected behaviour
-user can choose to activate logging
 
### Steps to reproduce
At the moment logging is deactivated in stable releases via a programmatic switch. 
Suggestion: Add a on/off switch in the settings at the bottom where the "Log" entry resides so that users of the stable version have the chance to activate the logging to provide logs to development. 
Con: Logging is a rather technical thing and should be hidden from the user
Pro: We get bug reports from stable users but have nearly no chance to gather any information if it is a non-trivial bug that can be reproduced but is rather related to the context (server setup, connection, navigation flow, etc.). So by giving the user the chance to activate logging, send us the log, deactivate logging again we would have better chance to help users and tackle issues

pinging @tobiasKaminsky and @nextcloud/designers for feedback if this is something worth discussing/implementing.

**Comment by tobiasKaminsky** [comment]
Yeah, let us do this. :+1: 
I know it is an additional  preference entry, but it also important to get the app better.

Maybe (@nextcloud/designers) it is possible to "hide" this somehow.

**Comment by Bugsbane** [comment]
I guess you could hide it behind some non obvious interaction such as how android had (has?) you open developer options by tapping repeatedly on the about entry, or behind a long press. That way the UI remains clear but people can always be told in the tracker or on forums how to access logging.

Not sure if it's really a good thing to hide the option so much that a person actively looking for it in the settings can't find it though...

**Comment by eppfel** [comment]
IMO hiding is not really needed here. It is nothing where people can break things and numerous settings is not the worst ux.

**Comment by mario** [comment]
Implemented for 1.5 via expert mode.
