### ISSUE TITLE
Autoupload Galaxy Note 9 (Android 9)

### ISSUE THREAD

**Issue by Stowen** [nextcloud/android#3755]
Auto upload isn't working on my Galaxy Note 9.

Device: SM-N960U
Android: 9

Issue:
Auto upload isn't uploading anything at all. Power save mode or whatever was requested was disabled, waited a few days, and still nothing was uploaded.

**Comment by Sanookmakmak** [comment]
It does not work on ANY Galaxy devices. See Nextcloud forum - it's filled up with that issue.

Explanation of an app developer why it does not work:
https://help.nextcloud.com/t/nextcloud-client-app-3-2-1-fur-android/35045/4?u=sanook

**Comment by ezaquarii** [comment]
I'm wondering if we could make our custom folder-watcher solution. Even an alarm-triggered folder scan every couple of hours will make an infinitely better than not working at all.

Using job scheduler should make it more battery friendly too.

**Comment by ezaquarii** [comment]
I'm wondering if we could make our custom folder-watcher solution. Even an alarm-triggered folder scan every couple of hours will make an infinitely better than not working at all.

Using job scheduler should make it more battery friendly too.

@tobiasKaminsky @AndyScherzinger What do you think?
