### ISSUE TITLE
App lock easily bypassed

### ISSUE THREAD

**Issue by nxtiak** [nextcloud/android#3757]
### Actual behaviour
In Nextcloud app setting under Lock, if Passcode is enabled, all you have to do is open the recent apps screen on the phone, close Nextcloud, relaunch Nextcloud and you're in. Video: https://youtu.be/WLRt3qUGThs

In Nextcloud app setting under Lock, if using Device Credentials (I'm using Fingerprint lock on my phone), all you have to do is press Back button quickly as the Nextcloud app is launching, do it a couple times and Nextcloud app will launch without asking for it. Video: https://youtu.be/x9rJH7XLof8

### Expected behaviour
App should stay locked unless pin or fingerprint is entered.
 
### Steps to reproduce
1. Listed above with video.

### Environment data
Android version: 9

Device model: Pixel 3 XL

Stock or customized system: Stock

Nextcloud app version: 3.5.0

Nextcloud server version: 15.0.5

**Comment by stucamp** [comment]
Same issue as above however can reproduce much more simply and consistently.  

**Steps to reproduce**

1. Enable pin/fingerprint

**Environment data**
Android version: 9
Device model: Pixel
Stock or customized system: Stock
Nextcloud app version: 3.5.0
Nextcloud server version: 14.0.8

**Comment by ardevd** [comment]
Correct me if I'm wrong, but this only happens if you quickly re-open the Nextcloud app, correct? If you wait 20 seconds before reopening the app, the lock should show up. There is a grace period there of a few seconds so that the app doesnt prompt you for a pin if you're just quickly switching back and forth. I believe that's whats tricking you here but if not then please let us know.

**Comment by stucamp** [comment]
Negative.  This works for me without ever actually authenticating.  I can close all open apps.  Restart my phone.  Open the app where it'll prompt me for authentication, quickly close the app and reopen it and I'll bypass any authentication.  All without ever authenticating.

**Comment by nxtiak** [comment]
ardevd, I'm aware of the 20 second timeout, but that's not what is happening. The Nextcloud app is in locked status. And without unlocking the app (by entering my fingerprint/phone lock/pin/etc), do the bypass as shown in video, then it will be unlocked on its own.

**Comment by stucamp** [comment]
I have noticed that you have to exit the app and restart it fairly quickly for the bypass to work... maybe all within a second or so.  But without fail, even after restart, if you exit the app and restart it quick enough the authentication screen is bypassed.

**Comment by ardevd** [comment]
Thanks for the feedback. I can also reproduce it now albeit not reliably. It usually prompts for credentials but not always. I'll look into this asap.

**Comment by ardevd** [comment]
Can you confirm that this issue only happens when you kill the app first?

**Comment by stucamp** [comment]
Yea, won't work if you simply minimize it.  Have to swipe the app closed and re-open it in like half a second.

**Comment by ardevd** [comment]
I think I've found the bug. I'll update you on my findings. Thanks again for reporting the issue.

**Comment by nxtiak** [comment]
Don't need to kill the app. Just tried it right now, pressed back/launch/back/launch, it's unlocked. I showed killing the app in the video just in case, to show it fully running from scratch.

**Comment by ardevd** [comment]
@nxtiak thats because when you're hitting the back button when the activity stack only contains one entry you kill the app :)

At any rate, I've found the bug and now I just need to figure out how to fix it.

**Comment by ardevd** [comment]
@stucamp @nxtiak Ive created a pull request with a proposed fix. Can you guys give it a try and see if you can bypass the lock screen?

**Comment by stucamp** [comment]
Can't on my actual pixel, but have emulated the phone and could replicate with Google Play version... Cloned the repo, made your proposed changes, and ran in emulated Google Pixel with Android 9 and was no longer able to replicate the bypass.

**Comment by ardevd** [comment]
@stucamp thanks for testing.

**Comment by stucamp** [comment]
Just to be sure... then uninstalled the modified version... reinstalled the Google Play version and was again able to bypass... looks like it's working as intended to me!

**Comment by tobiasKaminsky** [comment]
> The app lock is pretty basic to be honest. Ideally your locally synced files and the remote API token would be encrypted and only decrypted when authenticating with PIN and the PIN being part of the encryption key.

The scope of app protection is not to protect the downloaded files as they can accessed directly via file system, but to prevent other people to mess with data on server (delete, move, add comments, share files, …)

But of course you are right, it should be not get bypassed.
I have a look at your fix @ardevd now.

**Comment by ardevd** [comment]
My PR has not been accepted yet so no. Still pending

**Comment by nxtiak** [comment]
bump.

**Comment by tobiasKaminsky** [comment]
You can test the new pass procetion on beta program or tomorrow with final 3.6.1.

**Comment by nxtiak** [comment]
Just downloaded 3.6.1 looks like it's fixed, thank you. Closing this now.
