### ISSUE TITLE
Replace (dead) FindBugs with (alive) SpotBugs

### ISSUE THREAD

**Issue by ezaquarii** [nextcloud/android#3759]
### Describe the solution you'd like
Replace FindBugs with SpotBugs.

https://spotbugs.github.io/

Quote from the project's site:
> SpotBugs is the spiritual successor of FindBugs, carrying on from
> the point where it left off with support of its community.

SpotBugs is actively maintained and proven in industrial environment.

### Additional context
For all practical purposes, FindBugs is abandoned. It haven't got any update in last 3 years.
https://github.com/findbugsproject/findbugs/commits/master

**Comment by tobiasKaminsky** [comment]
I indeed tried to change it some times back, but it turned out to be not a one to one replacement, but this is definitely what we should do.
Import is that also the plugins (security, android, …) are supported and enabled.

**Comment by ezaquarii** [comment]
I added basic support for SpotBugs. We can leave it to run alongside findbugs and start building on top of it.

Also, Findbugs plugin for gradle is deprecated: https://github.com/gradle/gradle/pull/6664

**Comment by tobiasKaminsky** [comment]
Cool, I already changed our test CI to use spotBugs.
