### ISSUE TITLE
automatic upload, no remote folder selectable 

### ISSUE THREAD

**Issue by SprickW** [nextcloud/android#3763]
fresh install of 3.5.0 as I changed server.

After selecting a remote folder the selection can not be stored. Back does work.

**Comment by AndyScherzinger** [comment]
@SprickW did you configure remote _and_ local folder?

**Comment by SprickW** [comment]
No, I didn't.

Am 18. März 2019 8:58:53 vorm. schrieb Andy Scherzinger 
<notifications@github.com>:

**Comment by tobiasKaminsky** [comment]
You have to specify local and remote folder, otherwise you cannot save it.
Please provide more info what you do and what and when it is not working.
