### ISSUE TITLE
Upload the same file twice doesn't warn

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/android#3767]
### Actual behaviour
- File (2).txt is created

### Expected behaviour
- Option to overwrite/rename/abort should be offered
 
### Steps to reproduce
1. Share File.txt to Nextcloud and upload it
2. Share File.txt to Nextcloud and upload it
3. You now have File.txt and File (2).txt

My wife uploads her photos manually most of the time, so she can sort them into the correct folders already. However sometimes she uploads the same file multiple times without knowing it, she then asked my why there isnt a warning like on windows or the web interface where we ask whether the file should be renamed, overwritten or the upload even aborted.

**Comment by joekerna** [comment]
#431

**Comment by nickvergessen** [comment]
Duplicate of #431
