### ISSUE TITLE
Uploading files from SD card simply does not work

### ISSUE THREAD

**Issue by fwsGonzo** [nextcloud/android#3782]
### Actual behaviour
I expect not to get an error message saying I dont have room to upload the files from my almost empty SD via my almost empty internal storage (which is where nextcloud is). I get an error message saying "Insufficient space to copy files ...". If I select "move the files" it works, but that's not what I want. I also can't for the life of me get auto-uploads to work from my SD card either. It seems there is a big problem with that on Android.

### Expected behaviour
I expect it to work. Move works, copy doesn't.
 
### Steps to reproduce
1. Go into folder
2. Press Upload
3. Select a 4mb image.
4. Get error message about insufficient space.

### Environment data
Android version: 9
Device model:  Stock Samsung S8
Nextcloud app version: 3.5.1
Nextcloud server version: 15, latest

I also tried going to the gallery and pressing Share on an image, then uploading it to a Nextcloud folder. Nothing happens. Image probably on SD card.

**Comment by fwsGonzo** [comment]
It's now a day later, and it has started working. I'll leave the issue open as I expect the same problem reappearing if I want to add new folders. Something to look into.

**Comment by nyex** [comment]
I'm using a rooted Moto G4 Play, LineageOS 14 with the Nextcloud app 3.6 and I'm having this issue of the auto-upload to work -- my photos are in the SD card. I also tried uploading something from the SD card and I got the same kind of warning: it says the local storage is full, so it cannot make the copy. It worked before (with the same phone, same config), so I guess for some reason the app lost the ability to properly read the SD card?

**Comment by NESC1US** [comment]
I was also able to replicate this behaviour with 15GiB of free space on the 'storage card'

**Comment by leonnnn** [comment]
This is affecting me as well with version 3.6.2 of the nextcloud app.

**Comment by wiibaker** [comment]
Affects me as well. Using also Android Nextcloud app version 3.6.2

I had the situation that the SD card had less space available than the size of the video file (960mb) it was trying to Auto-Upoad. Once I freed space from the SD card it was able to Auto-Upload the file succesfully.

**Comment by leonnnn** [comment]
To be specific, this is the exact message I get when trying to upload my whole Camera folder (by selecting "Upload files" and then doing "Select all" in that folder, which lives on the SD card and contains 4299 images, 29.12 GB in total size):

"Insufficient space prevents copying the selected files into the Nextcloud folder. Would you like to move them there instead?"

I want to keep them on the SD card, though, so I’m unable to sync this folder.

30.81 GB of my 32 GB of my internal storage are used.
66.55 GB of my 183 GB of SD card storage are used.

Please let me know if there is any way to sync such large folders to Nextcloud or if there’s any way for me to assist with debugging this.

**Comment by TeNNoX** [comment]
I would like to clarify / add to this issue as I think I'm having the same, but I would describe the issue like this:
### Prompt to move to app folder on upload even though 'Keep in source folder' is selected

I want to upload files from an app (in my case TitaniumBackup), and I select **"keep files in source folder"**.

#### Expected behaviour
Nextcloud would upload the files and keep them in the source folder.

#### Actual behaviour
Nextcloud asks me:
> **Attention**
> Insufficient space prevents copying the selected files into the Nextcloud folder. Would you like to move them there instead?

Pressing 'No' cancels the operation, and pressing 'Yes' moves the files from the source folder to the nextcloud app folder - which is not what I want.

Is it so that Nextcloud can't upload without having them in the app folder?!
If that is so (which would be weird), at least give a hint about that in the modal.

**Comment by meika** [comment]
I have my Samsung S5 to put the camera taken photos on the SD card. Autoupload set up, but get error message "Local storage full" in Uploads>Failed/pending restart screen in the Android Nextcoud client (this is a recent install after a factory reset of the Samsung S5). Now it actually has worked in the past, but I think not from the SD card. The "Local storage full" message is bizarre as the 16GB SD card has about 2GB on it.

**Comment by lejallec** [comment]
Hi,
I found out that storing android app data on the sdcard itself solved the issue for me.
See on the screenshot below for the settings. I replaced the defaut local storage to sdcard itself and upload of 11Gb of files is now ongoing :-)
Hope it can help.

![IMG_20191120_215541](https://user-images.githubusercontent.com/286354/69277542-bd04a700-0be0-11ea-9fe2-78ed855c20f0.jpg)

**Comment by maxirus** [comment]
Can confirm, using @lejallec's suggestion works. Changed the storage path to `/data/users/0/..`

**Comment by dietrichmd** [comment]
I can also confirm @lejallec's suggestion works on LG V60.  Changed storage to use the SD Card and everything is nice now.

**Comment by piranha79** [comment]
Can confirm as @lejallec suggestion works as a charm. :+1:

**Comment by ianp5a** [comment]
This exact problem still persists today with me. No fix has arrived. Just a workaround that most users will never discover.
I have lots of space on my Nextcloud, my phone and my SD card, so the error message is wrong.
This is one of the _main_ purposes of the app. So when that fails for no good reason, the app is useless.
