### ISSUE TITLE
Icon inconsistency

### ISSUE THREAD

**Issue by Derkades** [nextcloud/android#3783]
The app uses both outline and filled icons:
![image](https://i.ibb.co/cChhKXR/Screenshot-20190323-101529.png)

**Comment by AndyScherzinger** [comment]
Hi @Derkades,

thanks for the report. Which icons should be changed from your point of view? I fixed the folder icon via  #2796.

**Comment by Derkades** [comment]
I had a quick look around the app and it seems that is the only one

**Comment by AndyScherzinger** [comment]
> I had a quick look around the app and it seems that is the only one

Alright, then it'll be fixed via #2796

**Comment by tobiasKaminsky** [comment]
![image](https://user-images.githubusercontent.com/5836855/55065648-8344c600-507c-11e9-9d4f-38c2f7ff1272.png)

Comparing our app to web ui, it seems that "all files" is also not correct.
But we are using the correct icon for "no files available":

![2019-03-27-103929](https://user-images.githubusercontent.com/5836855/55065734-a7a0a280-507c-11e9-847d-ec6434a1402a.png)

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky it should be fine via the icons PR where I fixed it for the menu.
