### ISSUE TITLE
Background sync job not syncing

### ISSUE THREAD

**Issue by asdrubal77** [nextcloud/android#3784]
### Actual behaviour
- File is synced/downloaded.
- File is changed on android device
- Background sync job (running every 15min, according to description on issue #3673) does not update file on server when connected through wifi.

### Expected behaviour
- File changed on the android device should be updated to server
 
### Steps to reproduce
1. Sync/Download file through Nextcloud android app
2. Change synced file on Android device.

### Environment data
Android version: 8.1

Device model: Samsung Galaxy Tab A 10.1 2016 with S-Pen (P585)

Stock or customized system: NA

Nextcloud app version: 3.5.1

Nextcloud server version: 15.0.5

**Comment by stefanodecillis** [comment]
I'm facing the same problem with my oneplus 6t and android pie. I removed the app from optimized app by doze and nothing is changed.

**Comment by tsarevpp** [comment]
I am still getting the same issue. Two notifications are shown:
- One saying "Uploading files..."
- Another one showing the status of the last upload that usually hangs on 0% until the app is on foreground

Also sometimes the uploading hangs at 100% even if the app is open and you have to pull the list down for the reload feature to fix it.

**Comment by ruffson** [comment]
Please reopen.
I have the same problem with the latest app: I add a file to my Nextcloud server and it will not be synced to my Android device. Even after hours. When I open the app and navigate to the folder it even shows the file but is just not syncing until I explicitly press `sync`.
Same goes for "Auto" Upload. Pretty much nothing is happening until I explicitly try to sync or even reset the local folder.
