### ISSUE TITLE
Specify number of contact backups

### ISSUE THREAD

**Issue by Berni-MD** [nextcloud/android#3785]
With the help of the Android App for Nextcloud the address book can be secured very well. But there are no settings for the number of backups or for a rhythm for deleting backups.

This causes the backup directory to overflow or become confusing at some point.

The most ingenious would be a file rollup where for example the last 5 backups are preserved + one per month.

**Comment by tobiasKaminsky** [comment]
Indeed we already have the support of keeping # of backups already internally.
It is set to unlimited by default.
We could add a config/input value for this.

**Comment by Berni-MD** [comment]
Great - that would do it.

by the way:
In the German surface it is not really to be recognized that one can restore the backup also. 
The name "Datum auswählen" is a bit unfortunate and not self-explanatory.

**Comment by Berni-MD** [comment]
> We could add a config/input value for this.
In the last 2 updates I couldn't find anything yet. Will this option still come?

**Comment by Berni-MD** [comment]
Demand on the status of implementation.

With version 3.6.2 no settings are possible yet.
Is this feature still on the to do list?

**Comment by joshtrichards** [comment]
Duplicate of #2296
