### ISSUE TITLE
[Feature request] Enable video streaming

### ISSUE THREAD

**Issue by xylo** [nextcloud/android#379]
### Actual behaviour
When I click on a video that has not been downloaded so far the app starts downloading the video file instead of playing it directly.

### Expected behaviour
When I click on a video that has not been downloaded so far the video should played as video stream, i.e. playing should start immediately and the video should not be downloaded to the internal memory.

There is already a pull request for this feature: https://github.com/nextcloud/android/pull/183

Moreover the feature is already included in the Beta app and works for me (at least when playing the video in an external player).  For some reason the internal player has some issues with several or all video formats.

### Steps to reproduce
1. Navigate to a folder with videos that have not been downloaded.
2. Click on a video.

**Comment by tobiasKaminsky** [comment]
Thanks for creating the issue and remaining me of the stale PR.
I schedule it for the release after the next.

**Comment by tobiasKaminsky** [comment]
Regarding your second issue: as this seems to be independent of streaming please open a new issue and maybe you can provide some sample videos and specify on which device the problem occurs.

**Comment by xylo** [comment]
Thanks a lot, Tobias!  Regarding the second issue, I will file another ticket next week.

**Comment by lftsy** [comment]
Good evening, I am testing the app 3.0.0RC2 from PlayStore and streaming feature seems not present yet so I keep my old owncloud Android app to be able to stream movies
If you need some testers for the Android video streaming, I can test and report problem If any
=> I think you can update roadmap to next version since 3.0.0 seems not having it
Thanks and Best Regards

**Comment by supportreq** [comment]
@tobiasKaminsky is this feature available??
