### ISSUE TITLE
3.6.0 android crashes, does not start

### ISSUE THREAD

**Issue by ikke-t** [nextcloud/android#3799]
App does not start at all after update. It immediately crashes. How do I send logs? My device is not rooted, so I don't get system logs.

RC1, device is oneplus5 with latest sw. Oxygen 9.0.4, Android 9

**Comment by tobiasKaminsky** [comment]
This is already fixed by RC2, which was released 2min ago.
Can you please test it and report back if it fixes your problem?

**Comment by ikke-t** [comment]
I will update as soon as it hits google play. I can't see it yet there. Or can I download it somewhere directly to test now?

**Comment by ikke-t** [comment]
That was fast, thank you. It does not crash any longer.
