### ISSUE TITLE
Fixed layout on Chromebook

### ISSUE THREAD

**Issue by jasonbayton** [nextcloud/android#38]
### Actual behaviour
- The app utilises a "portrait" view on the app installed on an Asus Chromebook Flip, leaving the rest of the window blank.
### Expected behaviour
- The app should make use of all available space 
### Environment data

Android version:
6.0
Device model: 
Asus Chromebook flip (Android framework runs within a container)
Stock or customized system:
... both?
Nextcloud app version: 1.0

Nextcloud server version: 9.0

![screenshot 2016-06-19 at 21 55 07](https://cloud.githubusercontent.com/assets/3178412/16179800/08390cd0-3669-11e6-8d2d-1d9769b8ecbb.png)

**Comment by AndyScherzinger** [comment]
@jasonbayton that is done on purpose since the landscape mode uses a split view, e.g. for mp3, video, etc. so will have the file lsit on the left and the files content on the right.

**Comment by jasonbayton** [comment]
@AndyScherzinger it feels super cramped when exploring the folder contents, particularly when the grid layout is selected. It just seems like a lot of space dedicated to less 
important information.

![screenshot 2016-06-19 at 22 17 27](https://cloud.githubusercontent.com/assets/3178412/16179883/bc9a1352-366b-11e6-89ff-9ca01b58c1b3.png)

![screenshot 2016-06-19 at 22 18 59](https://cloud.githubusercontent.com/assets/3178412/16179892/da341836-366b-11e6-9c41-0953986b92bf.png)

**Comment by AndyScherzinger** [comment]
Any comment @jancborchardt? UX is rather your area of expertise :)
This would somewhat get better to some extend when we are done / ready to bring filtering/search to the app.

**Comment by Hanzei** [comment]
A tablet and chromebook friendly UI is being discussed at #912
