### ISSUE TITLE
Wrong username or password screen blocks everything

### ISSUE THREAD

**Issue by axmo12** [nextcloud/android#3806]
Hi,

I'm operating the 3.6.0 RC2 (March, 28, 2018) Android Beta App on 8.1.0 on a Motorola G5 Plus. There are two accounts in my app.

Whenever there's an authentication error, a pop up appears where I couldn't enter any data into it.
![NC](https://user-images.githubusercontent.com/10323208/55221797-a4d3b800-520a-11e9-9f13-e8b64fff04a1.png)

I have only the possibility to go back (and get out of the app) and can't change anything.

I would expect to see a window where I could enter username or password or where I could remove this account.

**Comment by tobiasKaminsky** [comment]
It should be possible to press enter to get to the username/password input screen

**Comment by axmo12** [comment]
I don't get an onscreen keyboard. - If I'm pressing back, nextcloud closes.
I tried tapping on the server URL to get an input field, but nothing happened.

**Comment by AllerTeaM** [comment]
Hello! Have the same issue, when I changed my password, through web-version. It "testing" connection, and then immediately show me this, with no chance to give me enter my new passw.

**Comment by tobiasKaminsky** [comment]
@AllerTeaM changing your password should not lead to any problems, as Android uses a password token, which is independent from password change.
What server version do you run?
