### ISSUE TITLE
Client with 2 accounts: One is blocked, other doesn't upload.

### ISSUE THREAD

**Issue by axmo12** [nextcloud/android#3807]
Hi,

I'm operating the 3.6.0 RC2 (March, 28, 2018) Android Beta App on 8.1.0 on a Motorola G5 Plus. There are two accounts in my app.

One account (no sync is setup for this one) is blocked  due to bad username / password and the other account is setup to auto upload pictures.

While the first account is blocked, the second account doesn't do any uploads in between. - I would expect that whenever one of the two accounts is blocked, the other is still working.

**Comment by tobiasKaminsky** [comment]
Yes, this should work.
Do see any error message why the auto upload of the second account?
