### ISSUE TITLE
Auto Upload: add pending jobs to "uploads"

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#381]
Back in the old instant upload the user can see the pending uploads.
This should also be possible in the new "auto upload" way...and it is, I am implementing it currently ;-)

My question is regarding the UI/UX:
As these uploads are triggered by android the user cannot start them manually.
But it is possible to stop/kill one -> is this necessary?
What else should be displayed:
- Name
- thumbnail
- status: (waiting for wifi connection/waiting for device charging)

@jancborchardt @eppfel 
@AndyScherzinger

**Comment by eppfel** [comment]
Think killing gives nice control, BUT what happens after that. If I have auto upload activated for a certain folder this particular file is never uploaded? I mean it is not a sync, right? Just for better understanding for UX implications.

**Comment by tobiasKaminsky** [comment]
Yeah, it just will remain in the original folder.
Use case would be: User takes 10 pictures and only want to have synced the latest one.
Maybe it is no the best use case ;-)

**Comment by eppfel** [comment]
If this is a relevant use-case, we have to think for options like activating auto upload, but only for new files not the old ones, right?

If a user would be able to kill an upload, it should be possible for him to revert this (restart uploading those files), without tweaks. This all points towards sync functionality... 😁

**Comment by tobiasKaminsky** [comment]
We will enhance it step by step.
This is maybe what you are describing: https://github.com/nextcloud/android/issues/382

**Comment by mario** [comment]
Tobias, this should already work, right? Can it be closed?

**Comment by tobiasKaminsky** [comment]
if it is also working with the/your new upload system? But your code should not affect this as in this issue only existing jobs are queried, where your code improves the way to create new jobs.
So...if you have tested it with your latest autoUpload branch and it is working you can close it.

**Comment by mario** [comment]
OK. I slightly improved how jobs are shown, but that's about it - thanks!
