### ISSUE TITLE
SDcard Write Access

### ISSUE THREAD

**Issue by Auguss82** [nextcloud/android#3819]
Please have nextcloud android client to request write access to sd card. This way for people whom have copious amounts of photos videos on auto upload on charge at night and on wifi will have an empty phone to start a new in the morning. Good for travelers and vacationers.

**Comment by ardevd** [comment]
@Auguss82 not quite sure I follow your reasoning, but at any rate, the Nextcloud app already requests read/write access to external storage.

https://github.com/nextcloud/android/blob/2dfbe3dfe11e16f129d2a21cf42758526d317558/src/main/AndroidManifest.xml#L54

**Comment by Auguss82** [comment]
When I upload files it says it does not have write access to sd card, so it cannot delete old file on upload. How do I change the setting or get it to reprompt? I already viewed Settings > Apps > Nextcloud > permissions. All selections enabled.

**Comment by unix0r** [comment]
I can confirm this.
My Camera app was writing all photos to the sd card and the auto upload function should move uploaded photos to the app folder.
But for now, the setting for the original file is set to keep in original folder and cant be changed.

Changed the storage of the camera app to the inside memory and the auto upload can be set to move file to app folder.
Something was wrong with the sd card permissions.

**Comment by tobiasKaminsky** [comment]
> When I upload files it says it does not have write access to base directory sd card, so it cannot delete old file on upload.

This is verified by "canWrite" permission on the specific folder. 
I am unsure why the app cannot write onto sdcard for you, but as @ardevd pointed out, we do query for this permission.

**Comment by Auguss82** [comment]
https://vincentbird. linkpc.net/index.php/s/cHRbKEAX5idQMrZ. 

It has write access to the emulated sdcard but not the mounted sdcard.

**Comment by Auguss82** [comment]
You will need to fix the link

**Comment by Auguss82** [comment]
Any more information that is needed?

**Comment by Auguss82** [comment]
.

**Comment by tobiasKaminsky** [comment]
@Auguss82 it seems that you are the only one left with this problem.
Which device do you have? 
which Android version?

**Comment by gjanssens** [comment]
Might this be the same issue as #2554 ?
Are the files being uploaded successfully and only the originals not removed ?

**Comment by Auguss82** [comment]
Samsung LG G6
Android 8.0.0 Build OPR1.170623.032

The problem I am experiencing that the nextcloud app does not request access to external SD that is inserted into the device but read the logical or internal SD card as the external SD card. 

So if there is a /media/sdcard, which is the logical or internal SD card, next cloud assumes this is the external. 

If there is a /media/0000-0000, the numbers vary on speed of read and write of external SD card and manufacturer of external SD card. it does not detect this inserted external SD card as writable media.

**Comment by Per0x** [comment]
Same problem on Samsung Galaxy Edge 7 with Android 8

**Comment by wis775** [comment]
Same problem on Samsung Galaxy A6 with Android 10

**Comment by llucax** [comment]
Please reopen. I'm experiencing this on Android 11. I also have some folders in the SD card I want to auto-upload and want the uploads to be moved to next loud folder, and the option is grayed out. I have the feeling the first time I installed the app it worked just fine, but I needed to re-format the SD card. I backed-up all files and inserted it again, but now the exfat filesystem has a different serial number. I think android considers this a different SD and because of that it needs to ask for permission again and next loud is not doing this automatically nor providing any option to do it manually.

**Comment by llucax** [comment]
I can confirm the above. I just uninstalled Nextcloud and installed it again and now it can write again to the SD card (i.e. move auto-upload files to the Nextcloud folder). Nextcloud app version 3.16.1 (from f-droid).

**Comment by Ihi** [comment]
Same problem - I am unable to set write access for Nextcloud app to "Camera" directory (exactly in my case '/storage/43A4-0AF9/DCIM/Camera'). Uninstalling and reinstalling doesn't help. App doesn't ask for permission (but on the other hand it can use folder on SD card for 'Data storage folder'). Google account is managed via Family link (user under 13, if this somehow matters, but i think it don't).

Phone: Xiaomi Redmi 5A
Android: 8.1.0
Nextcloud app: 3.18.1

**Comment by plwww** [comment]
I have the same problem. Moto G7, Android 10, NextCloud version 3.19.0 Alpha1(also tried current Play store version and F-Droid version, whatever those were as of around Dec-27th). 

My on-phone storage is presented as /storage/emulated/0/
SD-Card is presented as /storage/A945-0A01/

NextCloud properly detects that /storage/A945-0A01/DCIM/Camera is a media directory, but it is read-only so I cannot select the option to delete after upload. I can select this option for folders stored on-device. 

I have verified through the debugger: 
  it asks for the correct permission WRITE_EXTERNAL_STORAGE when first displaying the FileDisplayActivity, and receives that permission(it is my understanding that without this permission NextCloud also wouldn't be able to delete from on-device shared storage). 
  In the SyncedFolderPreferencesDialogFragment.checkWritableFolder() method, the call to .canWrite() returns false. 
  Environment.getExternalStorageDirectory() -> "/storage/emulated/0"
  Environment.getStorageDirectory() -> "/storage"

NextCloud can read from "/storage/A945-0A01", so it must be treated as External Storage for read permissions, just not getting write permissions. If there's anything else I can look at, please let me know.

**Comment by appiekap653** [comment]
Same problem is still present, Please reopen.
Nextcloud version 3.25.0, Android 10.

Sdcard directory: /storage/34D2-F864/DCIM/Camera
