### ISSUE TITLE
Login no working to nc instance behind a reverse proxy

### ISSUE THREAD

**Issue by linex83** [nextcloud/android#3825]
I cannot login to my Nextcloud instance and I have reasons to believe that this is due to the fact that my Nextcloud instance is running behind a reverse proxy.

Here is what happens if I try to login in the Android app:
1. Start Android app, press "Log in". Screen with server address input opens.
2. Type in server address "https://example.com/nextcloud". Screen with log in button is opened.
3. Press "Log in". At first no response. After a few seconds the option "Revert to old login method" is shown.
4. Press "Back". Screen with server address input opens. The server address shown is "http://example.com/nextcloud/index.php/login/flow". Error message "Malformed server configuration" is shown.
5. Type in server address "https://example.com/nextcloud". Input fields for Username and Password are shown.
6. Now login works, but after several issues before that.

I am running a fresh Nextcloud instance behind a reverse proxy. The reverse proxy is reachable via my domain name, say https://example.com. Requests to https://example.com/nextcloud are forwarded to the server with the Nextcloud instance. The Nextcloud server is not accessible from the outside world, it is only accessible through the reverse proxy.

The reason why this seems to be a reverse proxy issue is that once I allow access to my Nextcloud server from any client and use the IP address of the server rather than the domain name, then the login using the app works fine without any of the issues described above. All in all, I believe that the issues point to a bigger problem that Nextcloud has with the reverse proxy. I cannot be sure, of course, but I suspect that the app connects with the domain name at first, but then tries to use the IP address of the Nextcloud server, thus trying to access the server directly, which fails because the server is only accessible via the reverse proxy.

Nextcloud version 15.0.5:
Operating system and version: Ubuntu 18.04
Apache version: 2.4.29
PHP version: 7.2.15

**Comment by ardevd** [comment]
Can you successfully log in to your Nextcloud instance using a browser? If not, then this is not an issue specific to the Android client and your issue is probably posted in the wrong project.

However, there should be no issue running Nextcloud behind a reverse proxy so I suspect the issue here is how you've configured said proxy.

In order for us to help you it would be very helpful if you could share your apache config so that we might identify the issue. How are you handling SSL? Is SSL terminated at the reverse proxy or at the Nextcloud server?

**Comment by tobiasKaminsky** [comment]
Can you create us a test account, test if the problem occurs also there and if so send the credentials to tobias at nextcloud dot com with a reference to this issue?

**Comment by linex83** [comment]
This turns out to be a bug with the server, it's not a client issue: https://github.com/nextcloud/server/issues/13713

The workaround there solved the problem.

**Comment by tobiasKaminsky** [comment]
> I do find the behaviour of the client weird - see step 4 in particular.

Thanks for reporting this, which should be fixed via #3847
