### ISSUE TITLE
Share resized image via whatsapp

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#384]
This is currently not working.
I doubt it is "our" problem as sharing to k9, sms is working.

(as this is currently only in beta it is not that big problem, but needs to be investigated further...)

**Comment by AndyScherzinger** [comment]
Do you know the feature branch on which this has been implemented? :)

**Comment by tobiasKaminsky** [comment]
It should be "resizedImages"

**Comment by tobiasKaminsky** [comment]
Integrated in #69
