### ISSUE TITLE
File is not deleted after upload

### ISSUE THREAD

**Issue by cmassaviol** [nextcloud/android#3840]
### Actual behaviour
- when i upload a file i choose the option "delete file from original folder". It worked a while ago but now it doesn t anymore.

### Expected behaviour
- the file should be deleted from my local folder after being uploaded 
 
### Steps to reproduce
1. 
2. 
3. 

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Where is the file in question located?

**Comment by cmassaviol** [comment]
In my folders of my mobile phoneEnvoyé depuis mon smartphone Samsung Galaxy.
-------- Message d'origine --------De : Tobias Kaminsky <notifications@github.com> Date : 12/04/2019  08:46  (GMT+01:00) À : nextcloud/android <android@noreply.github.com> Cc : cmassaviol <celine.nguyen.dang2@gmail.com>, Author <author@noreply.github.com> Objet : Re: [nextcloud/android] File is not deleted after upload (#3840) Where is the file in question located?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/nextcloud/android","title":"nextcloud/android","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/nextcloud/android"}},"updates":{"snippets":[{"icon":"PERSON","message":"@tobiasKaminsky in #3840: Where is the file in question located?"}],"action":{"name":"View Issue","url":"https://github.com/nextcloud/android/issues/3840#issuecomment-482458129"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/nextcloud/android/issues/3840#issuecomment-482458129",
"url": "https://github.com/nextcloud/android/issues/3840#issuecomment-482458129",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by topas-rec** [comment]
Can confirm this behavior on my LG G4 using cypherOS 6.0.0 which is bases on android 8.

Example file location is:
/storage/emulated/0/Android/data/net.osmand.plus/files/tracks/rec

**Comment by AndyScherzinger** [comment]
@topas-rec that seems right though since no other app should have destructive write access to an app's data folder except the owning app (OSMAnd) itself. So that is likely by design of Android as on OS / sandbox.

**Comment by topas-rec** [comment]
I see.
I directly tested it with a file from /storage/emulated/0/Documents.
That file also is not deleted when I upload it (which works) and select to delete the source file.

Should it work in this directory?

**Comment by AndyScherzinger** [comment]
That should work I think. The delete option should also only be shown if we have write access.
Calling @tobiasKaminsky to the rescue since he implemented that feature ❤️

**Comment by topas-rec** [comment]
> The delete option should also only be shown if we have write access.

I also thought about that. I think that is a good idea. To avoid issues an advice with the reason for the missing option should be there, too.

**Comment by topas-rec** [comment]
But there seems to be an issue with directories where nextcloud has write access. To come back to this issue again.

**Comment by AndyScherzinger** [comment]
AFAIk that is what @tobiasKaminsky implemented. So it should not be displayed in such cases. So there is either a bug and we have write access or there is a bug in detecting the permission, or elsee (hard to tell from the distance).

**Comment by avanc** [comment]
I can confirm that files are not deleted after upload. But it worked in the past with a previous version of the app (don't know when the behaviour changed). Here are the details:
* Motorola G5
* Android 8.1.0
* Folder: /storage/emulated/0/DCIM/Camera

Shouldn't be a problem with access rights, pictures are automatically uploaded and removed from the folder. Unfortunately, videos are not uploaded automatically. Thus, I uploaded them manually but they are not removed although I selected "delete file from original folder".

**Comment by cmassaviol** [comment]
Yes I confirmed.  It worked in the past.

**Comment by wilyarti** [comment]
Same issue as avanc on a OnePlus 5T. Auto upload will detect and upload then delete newly created files successfully but the upload function fails to delete uploaded files.

**Comment by cmassaviol** [comment]
Still not solved.  Check last commente from mother people

**Comment by AaronADev** [comment]
Facing the exact same issue
- Samsung Galaxy S9+
- Andoid 9.0
- Files do not delete from ANY folder on the device. 
- I can confirm it did work several app updates ago. 

Has there been any updates to this that anyone is aware. Would absolutely love to have this feature back and working.

**Comment by AaronADev** [comment]
> Facing the exact same issue
> 
> * Samsung Galaxy S9+
> * Andoid 9.0
> * Files do not delete from ANY folder on the device.
> * I can confirm it did work several app updates ago.
> 
> Has there been any updates to this that anyone is aware. Would absolutely love to have this feature back and working.

Just confirming that this issue still persists. Are there any updates whatsoever on this?

**Comment by topas-rec** [comment]
Can also confirm that issue. Happened to me today.
