### ISSUE TITLE
Favorite files and folders

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/android#3844]
### Actual behaviour
- No "star" icon for your favorite files and folders.
- There are no default icons with empty text files.

Files on the Nextcloud app:

![obraz](https://user-images.githubusercontent.com/47037905/55483051-17d39900-5626-11e9-9b77-e9da3c61307c.png)

![obraz](https://user-images.githubusercontent.com/47037905/55483062-202bd400-5626-11e9-9262-90be0e49effa.png)

Files on the Nextcloud Android app
![obraz](https://user-images.githubusercontent.com/47037905/55483078-28840f00-5626-11e9-91aa-197197e1c939.png)

![obraz](https://user-images.githubusercontent.com/47037905/55483085-2cb02c80-5626-11e9-9bae-43e2faac7eaf.png)

### Expected behaviour
- Displays the "stars" icon for your favorite files and folders.
- With empty text files display the default icon.

### Environment data
Android version: 6

Nextcloud app version: dev 20190403 06e710d

Nextcloud server version: 15.0.5

**Comment by tobiasKaminsky** [comment]
> * No "star" icon for your favorite files and folders.

For me it is working and we did not changed anything in this regard.
Can you create us a test account, test if the problem occurs also there and if so send the credentials to tobias at nextcloud dot com with a reference to this issue?

> * There are no default icons with empty text files.

We have default icons, but server is generating previews out of text. If the text file is empty, it shows an "empty" preview instead of a default text mimetype icon.

**Comment by tobiasKaminsky** [comment]
The second one is fixed via #3845

**Comment by Valdnet** [comment]
@tobiasKaminsky I sent email.

>  If the text file is empty, it shows an "empty" preview instead of a default text mimetype icon.

In my opinion, if the file is empty, the default icon should be displayed. The empty file icon is a bit misleading.

**Comment by tobiasKaminsky** [comment]
> In my opinion, if the file is empty, the default icon should be displayed. The empty file icon is a bit misleading.

Yes, this is already fixed.

**Comment by tobiasKaminsky** [comment]
Thanks for the credentials via mail.
For me the favorite icon is working quite fine:
![2019-04-08-131515](https://user-images.githubusercontent.com/5836855/55720141-6b682d00-5a00-11e9-98ac-35e089822e63.png)

**Comment by Valdnet** [comment]
After upgrade to db42fde the problem is also the with the display of file icons.

![obraz](https://user-images.githubusercontent.com/47037905/55783682-3ff04b80-5aaf-11e9-988c-7a13645c6740.png)
@tobiasKaminsky I do not know where the problem is. Maybe with the Android version. Have you checked on version 6?

**Comment by tobiasKaminsky** [comment]
Just to make sure: this happens while you are browsing the files? And not when opening "favorites" on the drawer?

**Comment by Valdnet** [comment]
> this happens while you are browsing the files?

Yes. This happens when you browse files in the menu: All files and Favorites.

**Comment by Valdnet** [comment]
The situation is similar in version 3.7.0 RC3. The star icons on your favorite files are no longer displayed.

App:
Nextcloud Android 3.7.0 RC3
Android 6
