### ISSUE TITLE
Screen overlay

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/android#3848]
### Actual behaviour
- You can not allow access to photos, media and files on your device.

### Expected behaviour
- The ability to allow access to photos, media and files on your device.
 
### Steps to reproduce
1. Uninstall the old version of Nextcloud Android.
2. Install the new version of Nextcloud Android.
3. Start the application.
4. Set access to photos, media and files on the device.
5. The application detects and asks you to disable the screen overlay.
6. Disable the screen overlay for all applications.
7. There is still no way to give access to photos, media and files on the device.

### Environment data
Android version: 6

Nextcloud app version: dev 20190404 2b95ff3

Nextcloud server version: 15.0.5

**Comment by tobiasKaminsky** [comment]
Do you have some app like twilight or other redlight switching apps installed?
Which device do you run?
I am pretty sure that this is independent from our app…

**Comment by Valdnet** [comment]
> Do you have some app like twilight or other redlight switching apps installed?

No.

> Which device do you run?

LGK10

**Comment by tobiasKaminsky** [comment]
Can you post a screenshot of this message in step 5?

**Comment by Valdnet** [comment]
Step 5 screenshot:
![obraz](https://user-images.githubusercontent.com/47037905/55591594-332dc980-5736-11e9-8c8f-006cb6a52802.png)

**Comment by Valdnet** [comment]
After rebooting Android, the message does not appear. What could have been the cause?

**Comment by tobiasKaminsky** [comment]
This must have been something special on your device as this is nothing we have included in our app.
