### ISSUE TITLE
Nextcloud app locks user by using wrong password after password change

### ISSUE THREAD

**Issue by fellwell5** [nextcloud/android#3851]
### **Actual behaviour**
- **Tell us what happens**
Our nextcloud system is linked with our active directory for password verification.
After forced password changes for our users, in the nextcloud app is the old password stored.
The nextcloud app tries to logon several times and therefore the active directory account will be locked.
- **Tell us what should happen**
The app should stop trying to logon after the logon failed due to an wrong username / password combination and should show an notification that informs the user about the wrong password and ask the user to type in the new credentials.

### Steps to reproduce

1. Link your nextcloud instance with your active directory (LDAP)
2. Logon to your nextcloud instance via the app
3. Change the password on windows
4. The nextcloud apps tries to logon with the wrong credentials and therefore the user account will be locked.

### Environment data
This bug is present in the iOS & Android app from nextcloud.

**Comment by tobiasKaminsky** [comment]
@nextcloud/server-triage shouldn't app token be used? 
And thus changing a password should not matter?

**Comment by blizzz** [comment]
Yes, if app tokens are used and login fails, they are sort of disabled iirc. since 15.
