### ISSUE TITLE
Keep file in sync

### ISSUE THREAD

**Issue by TobiasDev** [nextcloud/android#3854]
I have a vauge memory of the ability to keep single files in sync through the NextCloud android client. 

Eg. I have my Todo.txt saved on NextCloud so I can reach it from my PC and through the Android client that automatically downloads and uploads when it has changes.

However, I cant find this option anymore. Has it been removed? Or was this never possible?

If it isn't I would love to see that optionen added.

**Comment by tobiasKaminsky** [comment]
This is done automatically now: every downloaded file is synced when on wifi every 15 min.
If you are not on wifi the file status will be checked upon entering directory.

**Comment by TobiasDev** [comment]
Can we get an option to keep it in sync even on mobile data? I have a shared buy.txt, and if I need to remember to jump into Nextcloud each time I change that file, it removes the point of it being shared. Maybe if the file is under x size, or we can somehow set it to be forced on a file, so it still checks every 15 minutes, but it does it even on mobile data.
