### ISSUE TITLE
allow using nextcloud app for chared links

### ISSUE THREAD

**Issue by syntron** [nextcloud/android#3856]
### Is your feature request related to a problem? Please describe.
It is possible to share data using links to the NC server. However, if it is data which can be used on the mobiles / tables / (desktop apps) it would be helpfull to allow adding such a shared link as a reduced nextcloud login. I.e. a login within the app which only has access to the shared data and nothing more.

My usecase is that I'm hosting a nextcloud instance and on it I have a share which contains files for a group of people. These do not have an account but access the data (read only). Up to now, they have to check manually each time if something has changed.

### Describe the solution you'd like
After I send the link to the NC share, they could open it in the NC mobile app and enter the password. After that, the data is useable for them like with an account on the server. This would mean, that the app checks for changes, changes are highlighted, etc.

### Describe alternatives you've considered
As it is handled now: manual download after I announce changes

### Additional context
This would also be something like a reduce 'guest' account if only a part of data has to be chnaged for a time. Options like password, stop time etc. would also apply to it.

**Comment by tobiasKaminsky** [comment]
This is a nice idea, though I fear that this will not be implemented soon, due to lack of man power. Also we try to judge enhancement on impact of users and therefore the focus is mainly on daily usage of users with proper login.

Of course any contribution is appreciated, but before starting we should discuss this a bit more.

**Comment by syntron** [comment]
I just got NC16 - the new guest app seems to solve this issue. I can simply use such a guest account ... Thanks for the good work!

**Comment by tobiasKaminsky** [comment]
Nice idea to use guest app :tada:
