### ISSUE TITLE
Auto upload missing on Android < 7

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/android#386]
### Actual behaviour

- No new auto upload
- No legacy auto upload

### Expected behaviour

There should be at least one of the auto upload options available.
 
### Steps to reproduce
 - Install 1.4.0 RC1
- Auto upload info popup shows up
- Configure autoupload
- Go back to files
- No autoupload in drawer 
- No autoupload in settings

### Environment data
Android version: 6.0.1

Device model: Nexus 5

Stock or customized system: Cyanogenmod 13

Nextcloud app version: 1.4.0 RC1

Nextcloud server version: 10.0.1

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky since I am ultra busy with my day job (GoLive), can you fix this? 
Needs to be done like for the menu:

here: https://github.com/nextcloud/android/blob/master/src/com/owncloud/android/ui/activity/Preferences.java#L371
and here: https://github.com/nextcloud/android/blob/master/src/com/owncloud/android/ui/activity/FileDisplayActivity.java#L251

Thanks a lot! :100:

**Comment by AndyScherzinger** [comment]
And should then be released ASAP, right away

**Comment by AndyScherzinger** [comment]
@juliushaertl just to manage expectations ;) ... 1.4.0 will only activate Auto Upload for Android 7+ devices (since this is a relatively huge change which should be intensively tested and hardened). So after this fix Android 6 will have the legacy instant upload again.

**Comment by juliushaertl** [comment]
@AndyScherzinger Makes sense. :wink: 

Works quite nice for me btw. I'm also running the beta on my phone. Awesome work :rocket:

**Comment by AndyScherzinger** [comment]
https://github.com/nextcloud/android/releases/tag/rc-1.4.0-02  :)

**Comment by juliushaertl** [comment]
Works for me. Not sure why, but i needed to reenable the instant upload.

Am 17. November 2016 23:44:31 MEZ, schrieb Andy Scherzinger <notifications@github.com>:
>https://github.com/nextcloud/android/releases/tag/rc-1.4.0-02  :) 
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/nextcloud/android/issues/386#issuecomment-261393872

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by juliushaertl** [comment]
Hmm, the app crashes after I made a photo. Do you receive the crash reports that can be sent after a crash?
-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by AndyScherzinger** [comment]
Hi @juliushaertl - we get the crash reports, yes. Just opened a new issue fot the crash: #388
