### ISSUE TITLE
Unable to upload using multiple threads

### ISSUE THREAD

**Issue by blue-orchid** [nextcloud/android#3865]
You can upload only one file at a time.This does not play to the large bandwidth of modern devices.Equivalent to multithreading, which is a waste of time

**Comment by blue-orchid** [comment]
It is distressing that the synchronization process cannot be paused.

**Comment by tobiasKaminsky** [comment]
This is due to our network library, which will be changed hopefully this ear.

**Comment by fuzsin** [comment]
> 
> 
> This is due to our network library, which will be changed hopefully this year.

Hi Tobies, is this the same problem we have here? If I upload files from within the app, everything works. If (for example) from the gallery-app, only one file is uploaded, the others have to be loaded manually.

**Comment by joshtrichards** [comment]
This work is covered elsewhere (namely: nextcloud/android-library#17, nextcloud/android-library#1466, nextcloud/android-library#371, nextcloud/android-library#815, nextcloud/android-library#881) as well as some [overlapping open issues](https://github.com/nextcloud/android/labels/performance%20%F0%9F%9A%80). Closing this here.
