### ISSUE TITLE
Push notifications still not working

### ISSUE THREAD

**Issue by biware-repo** [nextcloud/android#3872]
### Actual behaviour
- any notifications is comming just email no push on android

### Expected behaviour
- if i create share with concrete user the push notification should appears but nothing happens, but email notifications arrive
 
### Steps to reproduce
1. User A has a file and share it via web UI with user B
2. User B has mobile app and expect push notification that somebody (in this case user A shared a file with him) and after sharing the push notify should appears, but nothing shown. 

All notifications are allowed for mobile app. 
App is not closed or slept. Synchronization is ON on system account level. 

### Environment data
Android version:
8.0.0
Device model: 
Huawei p10 lite
Stock or customized system:
STOCK
Nextcloud app version:
3.6.0
Nextcloud server version:
15.0.4
#### Web server error log

file error.log is empty

#### Nextcloud log (data/nextcloud.log)
file not exist

**Comment by tobiasKaminsky** [comment]
@nickvergessen is sharing on the same server is meant to get a push notification?
I also never got one and assumed that this is expected.

**Comment by biware-repo** [comment]
It is on the same server. I thing it should be expected. It is important to inform user about any change with push notification and not to flood email. It is not about activities. It is just info you have new shared file by.... and others. Maybe there is any misunderstanding by me.

**Comment by nickvergessen** [comment]
Scheduled for 17:
https://github.com/nextcloud/server/issues/2192

**Comment by tobiasKaminsky** [comment]
As I understand that this then will be implemented on server side, I'll close this.
(If we figure out in linked issue that some client parts are needed, we can create a new issue).
