### ISSUE TITLE
automatic upload: sync only on a specific wlan ssid

### ISSUE THREAD

**Issue by Gifford47** [nextcloud/android#3876]
An option in the automatic upload menu to start the synchronization of the images only on a specified WLAN ssid.

This setting is important for me because I can't/ do not want to reach my nextcloud server from outside. The automatic sync should then take place at home.

**Comment by Gifford47** [comment]
any suggestions here?

**Comment by joshtrichards** [comment]
Let's consolidate tracking this in #821. I encourage you to subscribe, add to the discussion, and/or upvote 👍 that issue
