### ISSUE TITLE
Include Calender Sync

### ISSUE THREAD

**Issue by Mululu** [nextcloud/android#3883]
### Is your feature request related to a problem? Please describe.

It is not a direct problem but it would make the app better. Please integrate the Calendar Syncronization into the app. So, not another app like Davdroi is needed. Many people do not want to additionally install an app to sync a calendar. In this day and age, it should not be a problem to get this into the app.

**Comment by tobiasKaminsky** [comment]
Unfortunately it is not that easy.
Maintaining calendar & contact sync is something davX5 is doing 100% on their day job, we cannot "easily" integrate this, as we only have limited men/women power…

As there is a nice integration from our app to davX5, I fear this is the most we can do here within quite a while…
