### ISSUE TITLE
Convert AccountUtils into injectable component

### ISSUE THREAD

**Issue by ezaquarii** [nextcloud/android#3884]
### Is your feature request related to a problem? Please describe.
`AccountUtils` namespace contains bag of global accessors for global shared state. It's used in 180 places.

### Describe the solution you'd like
Turn it into an injectable components, the same way we did with `AppPreferences`

### Additional context
Continuation of story sketched in #3600

**Comment by tobiasKaminsky** [comment]
Just a side note: "design" label is for UI design and not for architectual design.
For code we mainly use enhancement/bug to split issues in those big buckets.

**Comment by ezaquarii** [comment]
This is closed with #4043.
