### ISSUE TITLE
App-Pin only works at App full start

### ISSUE THREAD

**Issue by Siggi0904** [nextcloud/android#3887]
Android: Oneplus 6 - Android 9
Nextcloud App: 3.6.0

After setting a App pin the App won't ask for the pin at opening the app.
Only if the App will be completely closed (removed from memory) or screen switched on/off and newly started the App asked for the pin. Same with selected device login data.

In addition: Please support fingerprint. as separate option not under device login data.

**Comment by tobiasKaminsky** [comment]
Can you give this a try with 3.6.1 (either via beta program) or on Friday?

> In addition: Please support fingerprint. as separate option not under device login data.

Can you explain this why this is needed? Do you want to have only an app protection, but not a device protection? In my opinion it should rather be the other way around…
