### ISSUE TITLE
Auto upload does nothing, manual upload works

### ISSUE THREAD

**Issue by tkedwards** [nextcloud/android#3896]
### Actual behaviour
- Auto upload does nothing, it never appears to sync, no errors are shown

### Expected behaviour
- Auto upload should sync new files as they're created, in my test case as new photos are made on the phone which creates files in the DCIM/OpenCamera folder
 
### Steps to reproduce
1. Open Nextcloud app->Auto Upload
2. Setup auto upload of /storage/emulated/0/DCIM/OpenCamera (the path where the OpenCamera camera app stores photos) to a folder on the server called 'Photo Upload'
3. Open the OpenCamera app, take a few photos. Wait several hours. Reboot the phone, take some more photos. Still no sign of auto upload doing anything

### Environment data
Android version: 9

Device model: Samsung S8

Stock or customized system: stock

Nextcloud app version:3.6.0

Nextcloud server version: 15.0.7snap1

Are there any logs on the Android side I can use to try and see why auto upload isn't working, or fails silently?

**Comment by tkedwards** [comment]
Seems to have started working now, seemed like it needed another phone reboot and then to wait a while. Now photos upload fairly soon after being taken

**Comment by InfamousUser** [comment]
Still doesn't work me; seldomly it does upload new pictures but it never auto uploaded all pictures from a folder.

**Comment by tkedwards** [comment]
I'm using it to upload photos so it makes sense for that to only have it upload new photos (I've already copied older photos into folders on the computer). Would be nice to have the option to do a full sync though

**Comment by InfamousUser** [comment]
Well if it never uploads the pictures that are *previewed* under and take up like 20 times the space of the auto upload button itself, I consider that a bug.
