### ISSUE TITLE
1.4RC2 NC tries to upload HDR dir after taking a picture

### ISSUE THREAD

**Issue by michalmiddleton** [nextcloud/android#390]
### Actual behaviour
NC tries to upload temporary HDR folder after taking a picture, and fails.

### Expected behaviour
Upload pictures only.
 
### Steps to reproduce
1. Open google camera app and make sure HDR is on
2. Take a picture
3. Review uploads in NC, notice there are two attempts to upload each picture. One IMG_date_time.jpg and one IMG_date_time (which corresponds to HDR temp folder)

### Environment data
Android version: 7.0

Device model: Nexus 6P

Stock or customized system: stock,latest ota, Google Camera app

Nextcloud app version:1.4RC4

**Comment by tobiasKaminsky** [comment]
@michalmiddleton can you install latest beta and try it as @mario has rewritten parts of auto upload.

**Comment by michalmiddleton** [comment]
Actually I'm not going to be able to test it. After many years on Android, I switched back to Apple. Thanks for all your work!

**Comment by tobiasKaminsky** [comment]
How sad to hear this ;-)
If you ever come back, you can always use our app (and report bugs).
For now closing it as you were the only one reporting this issue.
