### ISSUE TITLE
master does not compile - nextcloud library master-SNAPSHOT is not working anymore 

### ISSUE THREAD

**Issue by ezaquarii** [nextcloud/android#3906]
### Actual behaviour
Can't compile master

### Expected behaviour
Well...
 
### Steps to reproduce
1. `gradle assembleGeneric` 
2. fails compiling `MainApp` complaining about missing `com.owncloud.android.lib.common.OwnCloudClientManagerFactory.Policy;`

`gradle.properties` temporary fix:
```
    genericImplementation 'com.github.nextcloud:android-library:1.4.0' 
    gplayImplementation 'com.github.nextcloud:android-library:1.4.0' 
    versionDevImplementation 'com.github.nextcloud:android-library:1.4.0' 
```
Then it compiles.

**Comment by AndyScherzinger** [comment]
Fixed via #3886

**Comment by ezaquarii** [comment]
> #3886

I'm not sure if this is a good ref #. "*Rename PreferenceManager to AppPreferencesImpl*" doesn't touch it, unless it breaks it somehow. :)

**Comment by AndyScherzinger** [comment]
My mistake, it is #3889

**Comment by tobiasKaminsky** [comment]
That was my fault. There are sometimes changes that require a parallel merge of app and library merge, as we rely on master-SNAPSHOT.

As #3889 is now merged, it works fine again.
