### ISSUE TITLE
Issue with Calender reminder on Mobile Apps

### ISSUE THREAD

**Issue by Mululu** [nextcloud/android#3910]
### Actual behaviour
- The following scenario:

User 1 creates a calendar and shares it with user 2. There are several appointments in this calendar. Each appointment has a reminder 1 day before.

User 1 has an Android phone and uses the Davx5 app and it will display 1 day's reminder

User 2 also uses an Android phone with the Davx5 app. It will not show any reminders.

In the web browser, are the same problem

Either the calendar is not fully shared with reminders, or the Davx5 app can not read anything or is not assigned by nextcloud.

If I give the user 2 a write permission to test and only open the appointment and update without changing anything, the 1-day reminder will also be displayed on the Android user 2.

Enclosed screenshots from Google Calendar once from user 1 and user 2. Both have the same calendar from nextcloud.

With Apple the same problem could be determined

[User1](https://feuerwehr-gebirge.de/wp-content/uploads/2019/04/User-1.png)
[User2](https://feuerwehr-gebirge.de/wp-content/uploads/2019/04/User-2.png)

**Comment by tobiasKaminsky** [comment]
This is either a bug report for davX5 or for server repo with dav label.
For web ui, it is calendar repo.
