### ISSUE TITLE
SpotBugs picks up Dagger autogenerated code

### ISSUE THREAD

**Issue by ezaquarii** [nextcloud/android#3911]
### Actual behaviour
SpotBugs is picking up auto-generated code and complains about usage of private APIs.

### Expected behaviour
SpotBugs should not analyse auto-generated code.
 
### Steps to reproduce
1. add Dagger module
2. run build on CI
3. spotbugs issues are increased

**Comment by ezaquarii** [comment]
I'm going to fiddle with `findbugs-filter.xml` to see if we can exclude it.

**Comment by tobiasKaminsky** [comment]
@ezaquarii have you resolved this via 

https://github.com/nextcloud/android/blob/bbaf3553289d7ae7b4532973b86ae43caf947919/findbugs-filter.xml#L15-L22

**Comment by ezaquarii** [comment]
> @ezaquarii have you resolved this via

@tobiasKaminsky Nope, as dagger also generates code in other packages, for example where you hold your modules.

A simplified mental model for this is that you have dagger generated code in every package of the app
which is not actually true, but shows the issue.

Unfortunately this generated code can trigger spotbugs, so I'll need to find away to exclude it. I tried to fiddle with path filter, but it didn't work for me and then I lost the immediate motivation to debug it when my refactorings lowered spotbugs count in other parts, compensating for this issue.

**Comment by tobiasKaminsky** [comment]
Damn… ;-)
I would have expected that this is something widely know to Android community and thus there are some smarter people than us who already solved this ;-)
