### ISSUE TITLE
Issue with thumbnails remaining on device. 

### ISSUE THREAD

**Issue by xavierxxx** [nextcloud/android#3917]
On a non rooted device (samsung S8) I had both nextcloud and mega installed. I viewed files within both applications. I then deleted both. I ran Diskdigger and it found thumbnails of all photos that was within the nextcloud app and none of the photos within mega. I didn't download the files for offline use and privacy settings set.

**Comment by tobiasKaminsky** [comment]
Can you give us the storage path where those thumbnails are?
We only store thumbnails within our cache, so the images should not be directly visible?

**Comment by xavierxxx** [comment]
I can try to recreate this. Unfortunately it happened on that device with Samsung's Android rom before I flashed Lineage OS on it for testing. Over weekend I'll try it on a few others and if not then next week try to reinstall samsung and run it again.

**Comment by tobiasKaminsky** [comment]
Maybe those are thumbnails of downloaded files? And not Nexcloud app, but maybe a gallery app generated them?

**Comment by xavierxxx** [comment]
Negative. The files were never on this device. The server I set this up on had photos from family members devices on that nextcloud account. So I had gotten multiple devices from family and uploaded on the server thru usb and then just opened the folder in nextcloud app on my device. My mega account was only work photos. They were never saved offline or opened with gallery. Initially when issue arose I contacted nextcloud via Twitter and where Diskdigger dev saw the post. Then I was ignored and went ahead and wiped device and installed Lineage as planned. Yesterday I brought issue up on another thread and was asked by dev to post issue here.

**Comment by AndyScherzinger** [comment]
The dev was me @tobiasKaminsky since it caught my attention and I think this should be fixed in case Nc app leaves files behind after uninstall...

**Comment by tobiasKaminsky** [comment]
> I think this should be fixed in case Nc app leaves files behind after uninstall...

Totally agree, but:
> The files were never on this device.

As said, all thumbnails we have are stored in our LRUcache, so they are nor stored as file on phone.

**Comment by AndyScherzinger** [comment]
AFAIK still valid

**Comment by AndyScherzinger** [comment]
AFAIK still valid

**Comment by tobiasKaminsky** [comment]
Here is what I tried to reproduce:
- generated a new emulator
- as root: find 2>/dev/null | grep jpg$                                                                                                                                                                                                                                 
```
./config/sdcardfs/extensions/1057/jpg
./data/system_ce/0/snapshots/1706_reduced.jpg
./data/system_ce/0/snapshots/1706.jpg
./data/system_ce/0/snapshots/1765_reduced.jpg
./data/system_ce/0/snapshots/1765.jpg
./data/system_ce/0/snapshots/1762_reduced.jpg
./data/system_ce/0/snapshots/1762.jpg
``` 
- opened an image as preview
- shared this file to K9
- shared this file to SMS
- re-run above command
--> still no newer jpg

Sorry to say, but I need steps to reproduce, otherwise I cannot do anything.
I'll close this one as latest answer was in April by @xavierxxx 
Of course feel free to re-open.
