### ISSUE TITLE
Install APK from nextcloud 3.6.0 is not possible on Android 5 and lower

### ISSUE THREAD

**Issue by pschonmann** [nextcloud/android#3919]
### Actual behaviour
- Hi, im trying install some apk apps from install folder. Using android tablet with 4.4 and 5.0.1. There is problem, on 6.0+ is everything ok.
When i tap on APK file, its downloaded ok. but not installed. 4.4 nothing happens, 5.0.1 info about app has no program associated to launch ( dropbox have no problem with that )

 
### Environment data
Android version: 4.4

Device model: Lenovo TAB2 A7-20

Stock or customized system: Stock

Nextcloud app version: 3.6.0

Nextcloud server version: Nextcloud 15

**Comment by tobiasKaminsky** [comment]
Which apk do you use, so I can test exactly the same on a 4.4 device.

**Comment by pschonmann** [comment]
[Nextcloud  3.6.0.apk.zip](https://github.com/nextcloud/android/files/3100285/Nextcloud.3.6.0.apk.zip)

**Comment by ezaquarii** [comment]
@pschonmann
> ( dropbox have no problem with that )

Could you please elaborate on this? Does it mean that you can install the app by opening the apk from dropbox?

**Comment by pschonmann** [comment]
@ezaquarii .
Same scenario on dropbox. Dropbox wins :)

Open Dropbox / Nexcloud
Open folder called INSTALL
Tap on MY_APP.apk

Dropbox install MY_APP.apk, Nextcloud dont.

**Comment by tobiasKaminsky** [comment]
So I downloaded your zip file, extracted it, put it on scard and clicked on it with amaze, and it installed.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky upload it to the Nc server, open it in the Nextcloud files Android client and see if it installs (I think that is the scenario here which seems to not be working)

**Comment by tobiasKaminsky** [comment]
![2019-05-02-093517](https://user-images.githubusercontent.com/5836855/57061563-9ff89d00-6cbd-11e9-9bc7-1fbe94b87838.png)

this does not work for both…

**Comment by AndyScherzinger** [comment]
> this does not work for both…

which is the bug reported here. I know this worked before and I think we already had to fix this sometime before, don't knwo when. I recall this had something to do with permissions changing between Android versions. So maybe we hit such a scenario again.

**Comment by tobiasKaminsky** [comment]
Hm. We are just asking Android to give us an app that handles apks. 

We have this permission REQUEST_INSTALL_PACKAGES:
> Added in API level 23
String REQUEST_INSTALL_PACKAGES
Allows an application to request installing packages. Apps targeting APIs greater than 22 must hold this permission in order to use ACTION_INSTALL_PACKAGE

Are you sure that this worked before with <API 23?

**Comment by tobiasKaminsky** [comment]
This is working for > 5.0, which is good enough I think, given the fact that even 6.x is EOL by Google/Android.
