### ISSUE TITLE
"Instant Picture Upload Disabled, Ignoring New Picture"

### ISSUE THREAD

**Issue by kreene1987** [nextcloud/android#392]
### Actual behaviour
-New photos/videos are not being uploaded from DCIM folder

### Expected behaviour
-Photos should trigger upload as soon as they are taken
 
### Steps to reproduce
1. Set Auto-Upload from Camera folder to Photos/Phone Directory on server. Using subfolders checked, originals kept in original folder.
a. Doesn't matter if wifi or charging boxes are checked or unchecked per my testing, both result in the same log entry.
2. Take a picture or video
3. Nothing happens, logs show new picture found, but then "Instant Picture Upload Disabled, Ignoring New Picture"

### Environment data
Android version: 6.0.1

Device model: LG G5

Stock or customized system: Stock

Nextcloud app version: beta 20161111

Nextcloud server version: 10.0.1 stable

#### Web server error log
N/A

#### Nextcloud log (data/nextcloud.log)
2016/11/21 08:25:09
com.owncloud.android.files.InstantUploadBroadcastReceiver : Received: android.hardware.action.NEW_PICTURE

2016/11/21 08:25:09
com.owncloud.android.files.InstantUploadBroadcastReceiver : New photo received

2016/11/21 08:25:09
com.owncloud.android.files.InstantUploadBroadcastReceiver : Instant picture upload disabled, ignoring new picture

2016/11/21 08:25:09
com.owncloud.android.files.InstantUploadBroadcastReceiver : OFFICIAL processed: android.hardware.action.NEW_PICTURE

2016/11/21 08:25:09
com.owncloud.android.files.InstantUploadBroadcastReceiver : Received: com.android.camera.NEW_PICTURE

2016/11/21 08:25:09
com.owncloud.android.files.InstantUploadBroadcastReceiver : New photo received

2016/11/21 08:25:09
com.owncloud.android.files.InstantUploadBroadcastReceiver : Instant picture upload disabled, ignoring new picture

2016/11/21 08:25:09
com.owncloud.android.files.InstantUploadBroadcastReceiver : UNOFFICIAL processed: com.android.camera.NEW_PICTURE

**Comment by AndyScherzinger** [comment]
@kreene1987 thanks for the report
@tobiasKaminsky can you take a look at this issue?

**Comment by Sjaak-d1** [comment]
Exact same issue for me,

Environment data

Android version: 6.0.1

Device model: oneplus 3

Stock or customized system: Stock

Nextcloud app version: beta 20161111

Nextcloud server version: 10.0.1 stable

**Comment by tobiasKaminsky** [comment]
The log is regarding the "old" instant upload system, so is is correct that the broadcast NEW_PICTURE is being ignored.
The question is why this the new "auto upload" is not being triggered.
Do you have something like "syncedfolder" in the logcat?

**Comment by Sjaak-d1** [comment]
Hi Tobias,

Installed latest beta 29-11, still Same issue.

The only log containing syncedfolders is this :



2016/11/29 07:51:52
FileDisplayActivity : Received broadcast com.owncloud.android.operations.RefreshFolderOperation.EVENT_SINGLE_FOLDER_CONTENTS_SYNCED

2016/11/29 07:51:52
FileDisplayActivity : Setting progress visibility to true

2016/11/29 07:51:52
FileDisplayActivity : Received broadcast com.owncloud.android.operations.RefreshFolderOperation.EVENT_SINGLE_FOLDER_SHARES_SYNCED

**Comment by AndyScherzinger** [comment]
Hi @Sjaak-d1,
the new version 11-29 re-activated the new auto upload for Android 5+, what did you configure for the Camera folder in the auto upload screen?

**Comment by Sjaak-d1** [comment]
![screenshot_20161129-092310](https://cloud.githubusercontent.com/assets/16209976/20701884/91a9aa16-b615-11e6-879c-b00ec6f7728d.png)

**Comment by AndyScherzinger** [comment]
Hmmm, that look completely right. So is there any item in the upload list regarding photos and is the wifi you are connected to a non-metered one (for a metered one you would have had to manually mark it a metered within Android OS wifi settings).

**Comment by Sjaak-d1** [comment]
Hi Andy, 
No upload list completely empty.. not even failed upload.
My wifi is non-metered. Is my Home connection with Unlimited data and 100mb Fiber connection to internet.

In the beta 23-11 in witch you disabled the New upload System everything is working perfectly.

**Comment by AndyScherzinger** [comment]
I do hope that @tobiasKaminsky will be able to shed some light on this since he is now also owning a oneplus 3 😃

**Comment by Sjaak-d1** [comment]
Ahh cool. Thanks Andy!

**Comment by AndyScherzinger** [comment]
Just to be sure, will it upload a picture via cellular if you remove the wifi-only restriction?

**Comment by Sjaak-d1** [comment]
No it wont trigger upload.. que is still empty


![screenshot_20161129-101636](https://cloud.githubusercontent.com/assets/16209976/20703693/f3b487b0-b61c-11e6-9565-23f0314f200a.png)

**Comment by octo777** [comment]
Hey guys,  I have a Moto G gen3  wth Android 5.1.1 and the newest beta Nextcloud client and i have the same issue.  the log says "Instant Picture Upload Disabled, Ignoring New Picture"  even though it is enabled.   Some times it works, sometimes it doesnt.   The last two days I had them all disabled for real, and rebooted my phone and all of a sudden Nextcloud client had a who bunch it tried to sync up even though upload  was supposed to be turned off for both camera and whatsapp.

**Comment by octo777** [comment]
I had to go back to an older version of the nextcloud beta because not only does it not work when the Instant upload is enabled, it actually tries to upload things sometimes when it is Disabled.  I have to use the Beta version because the one in the regular repos wants to download every picture you view on your phone which is not something im going to do lol.   Is it something simple like a issue with the instant upload enabled/disabled   toggle somewhere in the code?  Logs showing skipping because its not enabled when it actually is, and trying to upload when its not enabled, thinking that it is apparently?

**Comment by ncyclon** [comment]
20161215 have this problem

**Comment by AndyScherzinger** [comment]
fixed via #488 and to be shipped with 1.4.1 and also beta version 20161231

**Comment by octo777** [comment]
It is working great now,  thank you. I finally do not need to use any other syncing app.  Nexcloud app is great.

**Comment by octo777** [comment]
Any way to add the Whatsapp video directory to the upload choices? Or perhaps a way to select a custom directory to monitor?  :) :)

**Comment by AndyScherzinger** [comment]
Both things you mentioned are planned for future releases while we haven't found a neat way how to add this to the app in a comfortable manner. 

Glad to hear it is working for you in the beta :)
