### ISSUE TITLE
No edit on shared links on files

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#3922]
![2019-04-18-080018](https://user-images.githubusercontent.com/5836855/56339819-0a82e680-61b0-11e9-9bfe-1d15e52c5307.png) ![2019-04-18-080003](https://user-images.githubusercontent.com/5836855/56339820-0a82e680-61b0-11e9-9ea3-df311723db08.png)

On left (file) edit icon is missing.
This is due to: 
https://github.com/nextcloud/android/blob/dc7a2c0e7e01a22b10407368e46a8eda43750148/src/main/java/com/owncloud/android/ui/fragment/FileDetailSharingFragment.java#L247-L259

@AndyScherzinger as you changed it (no blame :-)), do you remember why you did this?

**Comment by tobiasKaminsky** [comment]
Now I know why.
When enabling via android, I do get "public upload is only possible for public shared folders".

**Comment by AndyScherzinger** [comment]
Erm, I think I did this because I thought that there is no edit option on files shared by link.

**Comment by tobiasKaminsky** [comment]
At least on NC16 in web ui there is.
I'll figure this out and fix it :-)

**Comment by AndyScherzinger** [comment]
Thanks a lot 😊👍

**Comment by tobiasKaminsky** [comment]
Sooner or later we have to do this

- reflect all settings / layout like web ui
- allow multiple share links
- clean up
- add test cases
