### ISSUE TITLE
Open file/folder from Talk

### ISSUE THREAD

**Issue by mario** [nextcloud/android#3933]
I want to click on a file preview in Talk and open a file or folder inside Nextcloud Files. Current approach is as follows:

- [x] Check if we have the app 
- [x]  Check if Nc app has the correct account
- [ ]  Check if Nc app is the right version

The way I do this is as follows and is brandable + it supports various (similar) apps installed since it doesn't hook into the "nc://" mechanism.

```
                    Intent filesAppIntent = new Intent(Intent.ACTION_VIEW, null);
                    final ComponentName cn = new ComponentName(context.getString(R.string.nc_import_accounts_from), "com.owncloud.android.ui.activity.FileDisplayActivity");
                    filesAppIntent.setComponent(cn);
                    filesAppIntent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
                    filesAppIntent.setPackage(context.getString(R.string.nc_import_accounts_from));
                    Bundle options = new Bundle();
                    options.putString(BundleKeys.KEY_ACCOUNT, accountString);
                    options.putString(BundleKeys.KEY_FILE_PATH, "/" + message.getSelectedIndividualHashMap().get("path");
                    context.startActivity(filesAppIntent, options);

```
nc_import_accounts_from - the package name of the files app
BundleKeys.KEY_ACCOUNT - KEY_ACCOUNT
BundleKeys.KEY_FILE_PATH - KEY_FILE_PATH

Let me know if you have any questions @nickvergessen, @tobiasKaminsky and @AndyScherzinger 

If this is sound, please implement handling of the intent inside the Files app and release a version so I can include a version check inside the Talk app.

**Comment by nickvergessen** [comment]
Should use the file id instead of path, in case the file/folder is renamed between loading of the message and the user interacting with the message.

**Comment by mario** [comment]
Yup, the path thing is now invalid, and was moved to KEY_FILE_ID which will have a file ID.

**Comment by tobiasKaminsky** [comment]
Do we have an endpoint where I can get all needed file infos for a given file id?
Currently we only file path all the time, as far as I remember.

**Comment by mario** [comment]
Search should do exactly this?

**Comment by tobiasKaminsky** [comment]
When you click on a file, what should happen? The same like clicking on this file within the app, so e.g. stream/open in collabora/show preview?
Or open the parent folder and scroll to the specific file, like we are doing in web ui?

**Comment by mario** [comment]
Well, since it could be a folder as well, and (I, personally) would prefer to have the same behaviour, I'd scroll to the file (or folder, since it could be a folder) in question.

I hate to say it, but this would make it consistent with the web and also would allow you to do whatever you want with the file/folder, not just open it.

**Comment by mario** [comment]
Keep in mind that we should somehow highlight the file/folder as just scrolling might not be enough.

**Comment by tobiasKaminsky** [comment]
Okay, this is also my desired behaviour, but why do you hate it? ;-)

**Comment by mario** [comment]
Because I'm usually against just mimicking the web ui, but here it makes sense. 

(I didn't say I hate the behaviour, just the fact that I have to say this xD)

**Comment by mario** [comment]
Maybe the highlight I mentioned above could be a ripple effect once the scrolling stops? That's Android-compliant and won't interfere the flow.

**Comment by tobiasKaminsky** [comment]
Nice idea, but I do only see this ripple effects in conjunction with onClick, but not used for highlighting an item programmatically.
Do you have any reference for this?

**Comment by mario** [comment]
I'd do a workaround there. Just set a variable "automatedRipple" to true and when the click listener is fired, ignore everything that should happen if automatedRipple is true (and clearly, set it to false).
