### ISSUE TITLE
Uploading folders is super complicated / does not work

### ISSUE THREAD

**Issue by oz42** [nextcloud/android#3934]
### Is your feature request related to a problem? Please describe.
I am trying to rescue photos from a damaged phone to my own Nextcloud server (FreeBSD)
My own phone: no problem
Buggy phone: I say "upload this folder, no matter what" and it does - nothing. Very frustrating.

### Describe the solution you'd like
When I say "upload this folder", it should upload this folder. That is what Joe Average expects.
Actually, I have selected seven (vidos and photos). After saying "upload this", app switches to "on my device" view with no files or folders (which is bug #2, it should display Whatsapp/Facebook/camera pictures and much more.

### Describe alternatives you've considered
Google Drive :-/

**Comment by maxlinux2000** [comment]
+1
in the app you can not upload entire folders, and it is very important, when you want to do for example, a backup of my documents/songs/photos/other stuff in my server

**Comment by joshtrichards** [comment]
This is a very old issue. A lot has changed since. 

> I say "upload this folder, no matter what" and it does - nothing. Very frustrating.

If you still have a similar experience or feedback today, please provide a step by step of what you did so that we can better understand the challenge.
