### ISSUE TITLE
Android client is not available in Georgia

### ISSUE THREAD

**Issue by zgrge** [nextcloud/android#3935]
Nextcloud client for android can't be installed from Play store for Georgian account
Can you please make it available?

![play_store_georgia](https://user-images.githubusercontent.com/1510690/56677635-fd935500-66d1-11e9-9bbb-cd8c52736b81.jpeg)

**Comment by tobiasKaminsky** [comment]
There were 9 countries where this app was not available, however we did not disabled them and we will not exclude any country from using this app.
I enabled all of them and it is stated that this should be available within a day.

Can you check it again and report back?

**Comment by zgrge** [comment]
It works now, thank you Tobias!
I wonder these 9 countries are disabled by default in Play Store?

**Comment by tobiasKaminsky** [comment]
> I wonder these 9 countries are disabled by default in Play Store?

I have no idea, maybe they were added later and default is to prevent access?
But somehow I doubt this, as those countries are rather old ;-)

Anyway, thanks for your feedback.

**Comment by mario** [comment]
This actually indeed happens when Play Store adds new countries to the store, and for various reasons, it decided to keep them disabled before you enable them manually (which again, makes sense). But it's important it's solved now :)

**Comment by tobiasKaminsky** [comment]
Hm. I do not recall all of those countries, but at least Georgia is not that new in world…strange that Google added it only recently…

**Comment by ezaquarii** [comment]
I has quite a lot to do with financial legal system supporting what they payment model needs.
