### ISSUE TITLE
Preview not working when masterkey encryption is enabled on the server

### ISSUE THREAD

**Issue by MassiveStorage** [nextcloud/android#3936]
I have a nextcloud-server running on which i enabled masterkey encryption.
The installation is working just fine, as long as i use the web-interface.
When I use the app, i get connected to the server and i see the content just fine, however as soon, as i want to open media-data like pictures or videos it get weird problems.

I open a video and it starts loading infinitly without ever showing a single image of the video.
When i preview an image, it tries to load the image and then showing an error in which the app tells me that it cannot handle the data retrieved by the server.
Opening any images or videos on the web-interface works.

Before i encrypted the data on the Nextcloud-Server everything just worked.

**Android client version:**
3.6.0

### Server configuration

**Operating system**:
Ubuntu 18.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.2

**Nextcloud version:**
15.0.7

**Comment by tobiasKaminsky** [comment]
@nextcloud/server-triage 
video is /directDownload
and preview/image is the thumbnail api.

Both should work just fine with encryption, or?

**Comment by MorrisJobke** [comment]
> Both should work just fine with encryption, or?

Yes they should work just fine.

**Comment by tobiasKaminsky** [comment]
"Great". Do you have an idea what the problem could be?

Can you create us a test account, test if the problem occurs also there and if so send the credentials to tobias at nextcloud dot com with a reference to this issue?

**Comment by MassiveStorage** [comment]
> "Great". Do you have an idea what the problem could be?
> 
> Can you create us a test account, test if the problem occurs also there and if so send the credentials to tobias at nextcloud dot com with a reference to this issue?

@tobiasKaminsky I've sent you a mail

**Comment by tobiasKaminsky** [comment]
Thank for the credentials.
So I logged in, entered "photos" and directly saw thumbnails of the 4 images.
Clicking on them allowed me to see a higher-res preview.

**Comment by tobiasKaminsky** [comment]
Can you test the exact same user with your device?
And if this fails also with another device? Maybe the problem is somehow the device.

**Comment by MassiveStorage** [comment]
@tobiasKaminsky: I tested on my smartphone and i found that image previewes worked with the testuser, however videos still load infinite.

**Comment by tobiasKaminsky** [comment]
@MassiveStorage do video preview work on web ui?

**Comment by MassiveStorage** [comment]
On the web interface everything works
