### ISSUE TITLE
Application hang Systematically in Android For Work Container

### ISSUE THREAD

**Issue by GPLExpert** [nextcloud/android#3939]
### Actual behaviour
- The application hang at start (When we launch the application on the mobile, it stop immediately with a popup "nextcloud stop systematically" and propose (Application Information, Close Application, Send comments) 
### Expected behaviour
- It should launch the application correctly

I don't know how to give you an application crash report
 
### Steps to reproduce
1. Configure Android for Work
2. Install Nextcloud android app and configure it
3. Launch it one time. The next time it will hang.

### Environment data
Android One version: 9 (2019/March/05)

Device model: MI A2 LITE (M1805D1SG)

Stock or customized system: Stock

Nextcloud app version: 3.6.0

Nextcloud server version: 15.0.7

#### Web server error log
Nothing
Insert your webserver log here
Nothing

#### Nextcloud log (data/nextcloud.log)
Nothing

**Comment by GPLExpert** [comment]
Have you got any news ?

**Comment by tobiasKaminsky** [comment]
Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

Please note that this seems to be a feature, used by companies, if so, please think about a https://nextcloud.com/enterprise subscription in order to get best support.

**Comment by pharmacare** [comment]
Same issue for us:

- App is deployed as Android for Work app (always the newest one)
- the app resides in a container that Android for Work creates on the phone
- app crashes on start

Android Version 9, Oneplus 7 Pro, App Version 3.6.2

**Comment by tobiasKaminsky** [comment]
This sounds like an Enterprise feature and we can help you with that.
Please contact nextcloud.com/enterprise.
As part of a subscription things like that can be developed via a project.
