### ISSUE TITLE
Problems with autoupload

### ISSUE THREAD

**Issue by aeszter** [nextcloud/android#3946]
### Actual behaviour
Autoupload starts for new pictures, then an error message appears: "Hochladen fehlgeschlagen. Die Operation kann nicht abgeschlossen werden, d..." (upload failed. The operation couldn't complete b[ecause])
Unfortunately,  the reason isnt shown.

On the server, the instant upload hierarchy down to the camera/year/month level is created but empty. There's a (populated) folder inside the uploads folder with the name (hash) mentioned in the logs.

Since this is a recently set up server, misconfiguration is quite possible, but I'm at a loss as to what to look for.

Possibly related to #3816 

### Expected behaviour
Autoupload proceeds without error message, and the files are available from the web interface.
 
### Steps to reproduce
1. Configure autoupload
2. Create a picture

### Environment data
Android version: 9

Device model: Wileyfox Swift 2

Stock or customized system: LineageOS

Nextcloud app version: 3.6.0

Nextcloud server version: 13.0.8

#### Web server error log empty, access log:
```
77.22.49.7 - - [03/May/2019:07:23:38 +0200
] "MKCOL /nextcloud/remote.php/dav/uploads
/ansgar/XXXX H
TTP/1.1" 301 395 "-" "Mozilla/5.0 (Android
) ownCloud-android/3.6.0"
77.22.49.7 - ansgar [03/May/2019:07:23:38
+0200] "MKCOL /nextcloud/remote.php/dav/uploads/ansgar/XXXXXXX HTTP/1.1" 405 247```

#### Nextcloud log (data/nextcloud.log)
```
time":"2019-05-03T05:08:03+00:00","remote
Addr":"77.22.49.7","user":"ansgar","app":"
webdav","method":"MKCOL","url":"\/nextclou
d\/remote.php\/dav\/uploads\/ansgar\/XXXXX","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\
Exception\\\\MethodNotAllowed\",\"Message\
":\"The resource you tried to create alrea
dy exists\",\"Code\":0,\"Trace\":\"#0 \\\/
srv\\\/www\\\/htdocs\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CoreP
```

**Comment by thechonta** [comment]
Same here on P20 Pro.
It is only a Problem for all Files that created by the Camera.
Pictures Downloaded (Twitter, Facebook, Instagram, Messanger) are Uploaded.
Further The Folderstructure for the Files will be created, only the file will not be created.

**Comment by developerfromjokela** [comment]
@aezter Have you tried to upgrade your Nextcloud Server?

**Comment by aeszter** [comment]
@developerfromjokela Not yet -- I'm using the stock version from openSUSE 15.0. I'll pull in a more recent version, though, and see how it goes.

**Comment by aeszter** [comment]
After upgrading the server to version 14, the problem seems to have resolved itself.
