### ISSUE TITLE
Crash navigating to Favorites or Photos

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/android#3949]
### Actual behaviour
- Disabling the Nextcloud Android application.

### Expected behaviour
- Display Favorites and Photos.
 
### Steps to reproduce
1. Choose "Favorites" or "Photos" from the menu.
2. Disabling the application.
Message: Unfortunately, Nextcloud dev has been stopped.

### Environment data
Android version: 6

Device model: LG-K430

Nextcloud app version: dev-20190504 and dev-20190502

Nextcloud server version: 15.0.7

**Comment by tobiasKaminsky** [comment]
Thank you for reporting it :-)

**Comment by tobiasKaminsky** [comment]
Fixed by https://github.com/nextcloud/android-library/pull/286 and will be in library 1.4.2 #3954
