### ISSUE TITLE
Autoupload

### ISSUE THREAD

**Issue by mcclaneonfire** [nextcloud/android#3950]
### Actual behaviour
I open and edit a Microsoft Excel sheet by clikcing it in my Nextcloud,
It opens directly in the MS Excel android app,
Then I close it,
No upload happens,
Then open it again,
Now it is uploaded to the Nextcloud.

-> alternatively: 
I can also click syncronize in the NC App directly for this Excel file. That works. 
**But an auto-sync after editing does not happen.** 

### Expected behaviour
It should be uploaded immediately upon closing the sheet in Excel. 

### Environment data
Android version: 8.0.0

Device model: Samsung A3

Stock or customized system:
Stock Android

Nextcloud app version:
3.6.0
Nextcloud server version:
15.0.7
#### Web server error log
I don't see an error shown in the NC log section.

**Comment by strugee** [comment]
This seems like a duplicate of #3215?

**Comment by mcclaneonfire** [comment]
> 
> 
> This seems like a duplicate of #3215?

Yes you're right, thank you :) 
I'll close it...
