### ISSUE TITLE
Search crash the app

### ISSUE THREAD

**Issue by ralfi** [nextcloud/android#3951]
Hi nextcloudies,

App crashes if i try to search for something. If i use browser access everything works. Nothing in protocol section, using latest dev 20190504 with  nc16 stable.

**Comment by ralfi** [comment]
Crashes only with dev, 3.6 from GPlay works well

**Comment by tobiasKaminsky** [comment]
This is the same root cause like #3949 and fixed with new library, starting tomorrow in dev and also in 3.6.1.

**Comment by ralfi** [comment]
Thank you, Tobias
