### ISSUE TITLE
Auto Upload fails citing 'File Error' before succeeding with actual .jpg

### ISSUE THREAD

**Issue by lauhayden** [nextcloud/android#397]
### Actual behaviour
I have auto upload turned on for my camera folder. When taking a picture, Auto upload will try to upload two files: 'IMG_YYYYMMDD_HHMMSS' and 'IMG_YYYYMMDD_HHMMSS.jpg' - the first will fail via 'File Error' while the second will succeed.

I suspect the camera app writes a temp file to storage before writing the whole file, and Nextcloud finds both files but the first one is removed before being uploaded.

### Steps to reproduce
1.  Take a picture
2. See result

### Environment data
Android version: 7.0, Build NRD91N

Device model: Nexus 5X

Stock or customized system: Stock

Nextcloud app version: 1.4.0RC2

Nextcloud server version: 10.0.1 (current stable)

Screenshot: https://cloud.deltaepsilon.ca/s/aH2XdQuuNcWRF8R

**Comment by lauhayden** [comment]
By the way, I very much appreciate how responsive you devs are, and the revamp of Instant upload in 1.4. Go Nextcloud!

**Comment by AndyScherzinger** [comment]
Thanks for reporting this @lauhayden and very happy to hear you are enjoying the app 🎉 

@tobiasKaminsky can you take care of this? Issue here is imho 

1. Problem with Android 7 which should be fixed in Android 7.1 (at least on my Nexus5X) where the system camera app writes an empty file with the same name but without a file extension (see https://code.google.com/p/android/issues/detail?id=220928)
2. Other issue which might be a problem for other versions and is not related to this ticket is that the camera also writes a temp file in case it does HDR auto processing, so we should wait for a couple of seconds before we detect/decide on a file upload.

**Comment by tobiasKaminsky** [comment]
Is this bug still valid?

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky according to the responses on the Android tracker https://issuetracker.google.com/issues/37117304 users are still experiencing this on Android 7.1.1 so I'd say, still valid :(

**Comment by tobiasKaminsky** [comment]
We made a few enhancements
- wait at least 10s
- verify if file exists otherwise fail silently

@AndyScherzinger the issue you linked is something we cannot fix, but I hope we can bypass it with the enhancements above.
--> @lauhayden can you test this with the latest dev version?

**Comment by mario** [comment]
Dear users,

thank you for your patience. After lots of work, we’re super excited to be able to give you a test version with new auto upload implementation. Keep in mind we will only accept bugs related to Auto Upload in this APK, as other things might be broken.

https://cloud.nextcloud.com/s/ftZraTruRQjTe0R

This is a dev APK so it will not overwrite your existing play store/f-droid APK unless you’re already running dev version. Also, you might need to remove your existing dev version before installing this one.

Explanation of the current functionality:
- added support for custom folders
- separated image and video folders
- checks for new files happens every 15-20 minutes
- automatic retry every 15-20 minutes or when you force close/open the app
- automatic pause once network is changed (untested!)
- significantly less battery usage

All and any testing is more than appreciated, especially with large and ever-going files like Videos. (like, try to record a 30 min video).

Let me know if you’ve got any questions.

Cheers,
Mario

**Comment by tobiasKaminsky** [comment]
No response within the last month, therefore closing.
Please feel free to reopen with additional infos, if the problem still exists.
