### ISSUE TITLE
Same server with different URLs to handle different connections (WIFI/4G)

### ISSUE THREAD

**Issue by NicolaP8** [nextcloud/android#3970]
My nextcloud server is at home so I can contact it with my two(*) WIFI when at home or through the cellular when out.

This is 1 account with 2 different URLs leading to same server/account but the app doesn't support it.

The new functions suggested are:
- more than 1 URL for server;
- at least 1 WIFI name associated to the URL (or none if is for remote use);
- limits and/or warnings in case of download/upload of big files.

*) I have a 2.4 GHz and a 5GHz WIFI with different names.

**Comment by tobiasKaminsky** [comment]
While this is a valid request, I doubt that this will be done anytime soon, as we focus on the majority of users/customers and there the most common use case is to have one (or more) central server 24/7 available via a public ip.

To circumvent this you can also point your server-url to your local ip within wifi.

**Comment by joshtrichards** [comment]
Hi @NicolaP8 - What you're looking for is split-horizon DNS:

https://en.wikipedia.org/wiki/Split-horizon_DNS

Many home routers have some form of built-in support, but Pi-hole (https://pi-hole.net/) and dnsmasq are common options.

https://help.nextcloud.com/t/accessing-nextcloud-on-my-home-network/147657/13
https://github.com/nextcloud/all-in-one#how-can-i-access-nextcloud-locally
