### ISSUE TITLE
QR code viewfinder is rotated by 180°

### ISSUE THREAD

**Issue by Bubu** [nextcloud/android#3979]
### Actual behaviour
- Viewfinder is rotated by 180 °
- It's quite confusing to navigate this way

### Expected behaviour
- Viewfinder is working the correct way around
 
### Steps to reproduce
1. tap the scan qr code button

### Environment data
Android version: LOS 15.1/ Android 8.1

Device model: Nexus 5X

Stock or customized system: LineageOS for microg: https://lineage.microg.org/

Nextcloud app version: 3.6.1 RC1

Video link, because github doesn't support video attachements apparently :thinking:  https://cloud.bubu1.eu/s/dwfAfF6a6NozgdR

**Comment by tobiasKaminsky** [comment]
I can confirm it only with my Nexus 7 tablet.
I'll have a look into the library we are using.

**Comment by tobiasKaminsky** [comment]
https://github.com/blikoon/QRCodeScanner/issues/8

**Comment by tobiasKaminsky** [comment]
I'll close this, as it is a upstream bug.
But I do get a notification once there is a change, then I can do a test and version bump.
