### ISSUE TITLE
Auto Upload view shows files in Nextcloud temporary storage

### ISSUE THREAD

**Issue by strugee** [nextcloud/android#398]
STR:

1. Upload a bunch of photos so that (I think?) they're copied into Nextcloud temporary storage (e.g. `/storage/emulated/0/nextcloud/tmp/$ACCOUNT_NAME/$UPLOAD_PATH` on my phone) and there's enough that the upload will take a while
2. While they're still uploading, look at the Auto Upload view in the sidebar. Note that there are a bunch of folders for the photos you're uploading.

I'm on a Nexus 6P running CyanogenMod 13.0-20160819-SNAPHSHOT based on Android 6.0.1. I have Nextcloud beta 20161111 installed from F-Droid.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky I thought we took care of this, but it seems that we missed the temp folder :(

**Comment by tobiasKaminsky** [comment]
Are you sure it is /storage/emulated/0/nextcloud/tmp/$ACCOUNT_NAME/$UPLOAD_PATH ?
As we are filtering every directory that starts with " /storage/emulated/0/nextcloud/", so this should include the tmp dir.
I cannot reproduce it :/
Which is your storage path?

**Comment by strugee** [comment]
@tobiasKaminsky the Auto Upload view seems to be gone in beta 20161123 from F-Droid... so I can't reproduce either :/

**Comment by tobiasKaminsky** [comment]
@strugee Auto Upload should be re-enabled in beta.
Can you give it a try again?
Thank you!

**Comment by strugee** [comment]
I can no longer reproduce. Closing.

Happy new year :)
