### ISSUE TITLE
editing with Collabora on Android problems

### ISSUE THREAD

**Issue by Bubu** [nextcloud/android#3980]
### Actual behaviour
- Can't delete any text, neither the backspace key (from AOSP keyboard) nor marking of any text works

### Expected behaviour
- I can delete and mark text
 
### Steps to reproduce
1. open a odt document with the nextcloud app
2. write some text
3. try to delete that text again

### Environment data
Android version: 8.1

Device model: Nexus 5X

Stock or customized system: LOS 15.1

Webview version: Android System WebView 72.0.3626.121

Nextcloud app version: 3.6.1 RC1

Nextcloud server version: 16

**Comment by Bubu** [comment]
I tried it in Firefox on Android (actually the fennec f-droid build) by opening a shared document link:
* backspace isn't working either
* marking text and overwriting it this way works.

**Comment by tobiasKaminsky** [comment]
CC for our Collabora partners: @thebearon @timar

**Comment by thebearon** [comment]
I don't have a device with AOSP keyboard, do you have predictive input enabled? If so, can you try disabling it?

**Comment by Bubu** [comment]
> do you have predictive input enabled

There's no such option in aosp keyboard. Is that gesture typing? That's disabled as the gesture decoder is part of the google proprietary libraries and doesn't come with aosp/Lineage.

Then there are various autocorrect options, these are all at default settings:

![image](https://user-images.githubusercontent.com/105185/59025508-9f22d000-8854-11e9-960c-08da5ee273ed.png)

Disabling them all doesn't make a difference. Backspace is still not working

**Comment by tobiasKaminsky** [comment]
I guess he is referring to "next-word suggestions".

**Comment by Bubu** [comment]
* stares at the bot somewhat irriatated

**Comment by tobiasKaminsky** [comment]
CC for our Collabora partners: @thebearon @timar

**Comment by thebearon** [comment]
This isn't related to the Nextcloud app, feel free to close the issue here.
The bug can be tracked at [tdf#123437](https://bugs.documentfoundation.org/show_bug.cgi?id=123437).

**Comment by tobiasKaminsky** [comment]
Thanks for the update @thebearon
