### ISSUE TITLE
No load "Shared"

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/android#3986]
### Actual behaviour
- Can not load "Shared"

### Expected behaviour
- View files "Shared"
 
### Steps to reproduce
1. Choose "Shared" from the menu.

There is still a problem with the menu navigation described in this issues: #3729  :expressionless:

### Environment data
Android version: 6

Nextcloud app version: 3.6.1 RC2

Nextcloud server version: 15.0.7 and 16.0.0

**Comment by AndyScherzinger** [comment]
Still an open issue

**Comment by tobiasKaminsky** [comment]
PR is in #4373
