### ISSUE TITLE
Show Server Notifications in Android Notication Panel

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/android#3988]
There are some notifications I only see in the browser (bell icon).
These notifications are shown in the Notification area in the App, too. 
But I don't always look if there is an new notification. 
Is it possible the add an option for showing the notifications in Android Notication Panel so I will get an mobil info?

Thanks for thinking about

**Comment by Valdnet** [comment]
In the Nextcloud Android version of Google Play, notifications are received and displayed on the fly in the Android system tray.

**Comment by tobiasKaminsky** [comment]
As far as I know all notifications that are shown in web ui should also be visible in our app in the Notification area.
*Additionally* if the app is installed via gplay, they are also shown as push notification (in status bar).

@jakobroehrl which one are missing?
@nickvergessen are you aware of any missing notifications?

**Comment by jakobroehrl** [comment]
Hi @tobiasKaminsky 
after reinstalling the app I can see the push notifications! :)
All of them are there. 

Is it possible to navigate to the file in the App when clicking on a notification? 
The current state is that the mobile browser starts. 
And if I don't know my login data it's dumb...

**Comment by tobiasKaminsky** [comment]
> Hi @tobiasKaminsky
> after reinstalling the app I can see the push notifications! :)
> All of them are there.

Gread to hear.



> Is it possible to navigate to the file in the App when clicking on a notification?
> The current state is that the mobile browser starts.
> And if I don't know my login data it's dumb...


Which notification is this, for example?
Then I can have a look.

**Comment by jakobroehrl** [comment]
@tobiasKaminsky 
on my other test mobile phones I had to reinstall the app as well before getting the push notifications.
That's not so good for existing users.

> Which notification is this, for example?
> Then I can have a look.
It's the notification you well get if someone mentions you in a file/folder comment. 

Btw: Is it possible to mention other people from within the app? 
In the current version no names come up if I tipp '@' in a comment. 

Thanks again! :)

**Comment by tobiasKaminsky** [comment]
> Btw: Is it possible to mention other people from within the app?
> In the current version no names come up if I tipp '@' in a comment.

Not yet, but https://github.com/nextcloud/android/issues/3999 is there to track it

**Comment by tobiasKaminsky** [comment]
> on my other test mobile phones I had to reinstall the app as well before getting the push notifications.
> That's not so good for existing users.

I'll have a look, can you meanwhile go to Notifications in drawer and see if there is a warning on those devices that are not working?

**Comment by tobiasKaminsky** [comment]
> It's the notification you well get if someone mentions you in a file/folder comment.

https://github.com/nextcloud/android/issues/4000

**Comment by tobiasKaminsky** [comment]
> on my other test mobile phones I had to reinstall the app as well before getting the push notifications.
> That's not so good for existing users.

I verified it. If there is no push registration yet, it tries it at least on every app start.
I am not sure why this is not working for your user. Maybe the device is registered, but somehow the token is not accepted by push server :/

**Comment by jakobroehrl** [comment]
@tobiasKaminsky 
There is no warning. I had to reinstall than the push notifations came. 
On some devices I get after the reinstall the warning: no push notications because of old session. 
I deleted the account and created it, but I always get this message. 
What can I do?

Btw: Cloud you give a info, if the push notications does not work and how to fix it? I think it's a great feature and user does not recognize it's there. 

I think push talk notifcations (private message send, want to speak to you) are not push notifcations. They only come up in Notifications drawer. I think the should also trigger a push, maybe with the info: "consider to install the talk app"

**Comment by tobiasKaminsky** [comment]
> There is no warning. I had to reinstall than the push notifations came.

This is strange. I would have expected something like "push currently not available".



> On some devices I get after the reinstall the warning: no push notications because of old session.

This is due to the way how to setup android app: you have to use the weblogin flow, instead of the old legacy login.


> Btw: Cloud you give a info, if the push notications does not work and how to fix it? I think it's a great feature and user does not recognize it's there.

If, for some reason, the initial push registration fails, the app tries it again and again, at least on every app start. If this fails, it shows a warning in "notification area".
I do not know what we can further do.



> I think push talk notifcations (private message send, want to speak to you) are not push notifcations.

With upcoming android version, the app will show these talk notification if talk is not installed on the same device.

**Comment by jakobroehrl** [comment]
> This is due to the way how to setup android app: you have to use the weblogin flow, instead of the old legacy login.

All devices are set up in the same way, I don't switch the methode.

**Comment by jakobroehrl** [comment]
Found the problem: It was the energy saving mode on a oneplus device. 
Disabled it, notifacations work great! :)

**Comment by tobiasKaminsky** [comment]
Just to get this right: oneplus' energy saving mode is blocking push notifications?

**Comment by jakobroehrl** [comment]
It seams so. There are 3 possibilities to save battery. 
After disabling these, the notifications are working. 
Before I had to reinstall the app to get the notifications working.

**Comment by jakobroehrl** [comment]
@tobiasKaminsky: In the latest beta I realized, that talk notifications (no talk app installed on the phone) are shown in the Panel but don't create a Push Notification:

For the first an last I got the Push, for the middle one not.

![Tyl99Vk4XIhHvn3r8jf6W6z0oX3hH-F9CN2HugvezO2MvC9ooI595qA7EO9eNmPRb5tgFK7Nsy_ZuxtGbZjdA9JPxueBKd2DlBuM-zq-2BcWg68HyqPI7il9k-Vafm4PEtXLo8P66Fa-5dImr1bGZWgISx1WLDjEWEeJDbgF2vpZNLS1HrpmFH8jM1wbGc7Nce4znezVHAKX3-2vCVg](https://user-images.githubusercontent.com/24530680/60177741-f85d9e00-9819-11e9-9571-0480110ca749.jpg)

**Comment by jakobroehrl** [comment]
reopen

**Comment by UserXH726** [comment]
Whats the reason why notification are only shown when I have installed the GPlay version?

**Comment by tobiasKaminsky** [comment]
Notifications require push and this is a google only service. 
As Fdroid does not allow proprietary software, this cannot work right now.

**Comment by schniepp** [comment]
I also have the problem in Android that the notifications don't show up, and I am getting the message that it is because of old login. However, I have reinstalled the app TWICE (from google play store), and deleted and added my NC account twice! I am using 2FA on my server, and as a login method I used the QR code (it looks like this is using an app password).

**Comment by jakobroehrl** [comment]
For me this issues is solved. Notifications are working when using the app from the playstore.
Notifications need google libs to work

**Comment by mortee** [comment]
As for my setup, my users and I receive proper android push notifications about announcements and talks - but flow notifications only appear on the web interface and the app's notifications area. Even after reinstalling the app, and reviewing the notifications settings. What might cause this?
