### ISSUE TITLE
show results of fulltextsearch

### ISSUE THREAD

**Issue by ralfi** [nextcloud/android#3992]
Hi nextcloudies,

i dont know if this a feature request or a bug ...
Results of fulltextsearch inside office docs or pdf shows in the web-if but not at android client.

Thanks in advance

**Comment by tobiasKaminsky** [comment]
It is a feature :-)
In fact I started at some point in the past, but as regular search needs some love first, I got stucked…

**Comment by ralfi** [comment]
Thanks Tobias.

**Comment by tobiasKaminsky** [comment]
Note to myself: FTS endpoint supports pagination, so load next 20 when reaching bottom.

**Comment by ralfi** [comment]
Hi Tobi, any news about this?

**Comment by joshtrichards** [comment]
Part of Unified Search handled in #7568.
