### ISSUE TITLE
App should give a notification when server is not reachable (Still)

### ISSUE THREAD

**Issue by jonathanmmm** [nextcloud/android#3995]
Reference to issue https://github.com/nextcloud/android/issues/894

### Actual behaviour
- Android App does not show new "server unavailable" warning

### Expected behaviour
- Android App should show
 
My Nextcloud Server runs behind nginx proxy on another nginx server.
My front nginx server is almost all the time online. But the second server is shutting down automatically when not needed. It needs to be woken up manually.

Proxy pass response normally with error code 502. I changed it to 503 with custom error_page.

Mynextcloud.com gets a error page which redirects to another website (startnextcloud.org, to start the server remotely).
Mynextcloud.com/status.php just gets the standard nginx 503 error page.

The App does not show server offline.
I thought the clients check for the status.php file and if this is error 503 or similar they will say server is unavailable.

No that my nginx before replies with 503 still the notification is not shown. Can browse folders and says by folders that they are empty.

Is it because I redirect to another URL?
(through Meta refresh in html header)

I don't redirect status.php.

I have Android 3.6.0
Nextcloud 15.0.7 (should not matter, the server is in this case down).

Do I have to give another error code then 503 or which path are the clients checking (Android, iOS, Windows) to see if the server is available? Is it something different then status.php?

**Comment by tobiasKaminsky** [comment]
We are either checking status.php (on older NC) or /index.php/204 if this returns 204.

**Comment by jonathanmmm** [comment]
Ok and what has mynextcloud.com/index.php/204 has to reply if the client should show: Server unavailable? HTTP Code 503 does not seem to work.

**Comment by jonathanmmm** [comment]
> We are either checking status.php (on older NC) or /index.php/204 if this returns 204.

Thanks for the fast reply :)

**Comment by jonathanmmm** [comment]
@tobiasKaminsky /index.php/204 returns right now a 503 error code. I also changed the forwarding that the clients reach the server directly without nginx proxy. 

I get status Code "Error" connect EHOSTUNREACH XX.XX.XX:443 (used httpstatus.io)
{Anomyzed Ip adress with XX}

Do I have to return some other error Code?

If I put my phone in Flightmode i shows server not available but else it just shows the flowing points from left to right and when I tried to unshare a folder (with public link) the app crashed.

**Comment by tobiasKaminsky** [comment]
> Ok and what has mynextcloud.com/index.php/204 has to reply if the client should show: Server unavailable? HTTP Code 503 does not seem to work.

on success it should give only 204 back, without any content.
on failure: anything other than 204 is handled as an error and is showing the "not rechable" message

**Comment by jonathanmmm** [comment]
@tobiasKaminsky 

This is sadly not true (or for some reason not working on my phone).
Both /index.php/204 and status.php return error 503 Service temporarly mot avaivalable (in browser, Nginx default error page). Should I use another error maybe 502?

The App just shows the floating points at the top. Using Android 8 App Version 3.6.2.
Nextcloud is now 16.0.1 but should not matter because it is not available.

In Flightmode or no Internet at all it shows the grey notification at the top.
