### ISSUE TITLE
Beta 20160617: nextcloud beta app changelog points to Owncloud beta changelog

### ISSUE THREAD

**Issue by elpraga** [nextcloud/android#40]
And thus is not updated.

**Comment by AndyScherzinger** [comment]
Thanks for reporting this @elpraga 

@tobiasKaminsky any idea where to look for the in our code base?

**Comment by tobiasKaminsky** [comment]
Will be in next beta!
Please verify and close then.

**Comment by tobiasKaminsky** [comment]
@elpraga @AndyScherzinger please verify if this is fixed and then close.
