### ISSUE TITLE
When moving/copying, show the folder the user started in

### ISSUE THREAD

**Issue by strugee** [nextcloud/android#400]
Often when I move or copy files in the app I'm organizing them within a particular hierarchy in my Nextcloud. Currently the folder picker starts at the root, but it'd be nice if it started in the same folder the user was already looking at. (This is particularly nice because even if it's more convenient for the user to start at the root, it's much easier for them to press back a couple times than it is for a user in the current situation to navigate through a bunch of folders.)

Alternately, we could start in the last used folder.

**Comment by AndyScherzinger** [comment]
As for copy/move I think start at the folder where you currently are shouldn't be an issue.

**Comment by strugee** [comment]
:thumbsup:

**Comment by tobiasKaminsky** [comment]
I vote for the last used folder as start. This is then the same bahaviour as on many programs (firefox) on the desktop.

**Comment by tobiasKaminsky** [comment]
@mario @jancborchardt please confirm if "last used folder" should be shown as first and then approve

**Comment by jancborchardt** [comment]
If "last used folder" means "folder where you currently are" as @strugee and @andyscherzinger said I agree. :) Because that gives the best context.

**Comment by mario** [comment]
Sure, but 1.6 please - this is far too complicated (because we have other things to do) for 1.5.

**Comment by AndyScherzinger** [comment]
@mario no worries, except for the fixes and the auto upload rewrite/fix 1.5 is basically feature frozen

**Comment by xXSTrikeXx** [comment]
@AndyScherzinger
Is the roadmap for milestones only important for pr? Because the issue is for milestone 2.2.0 and not the actual 3.x :yum:

**Comment by tobiasKaminsky** [comment]
With our new release cycle we want to set the milestone only afterwards, to keep track what is already included in the new release.
The aim is to have any open PR as soon as possible merged, there is no need to artificially delay it.
For enhancement issues the best idea, in my opinion, is to use high,med,low.
For bugs, the aim should also be to resolve them as soon as possible. Unfortunately there are many bugs, which occur only for specific persons/situations.
