### ISSUE TITLE
(Push) Notification about mentioned in file/folder should open it

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#4000]
Currents situation:
- receive a (push) notification about mentioning in a file / folder
- click on it
- web opens with redirect to file /folder

Expected:
--> click on it should open file / folder in app

**Comment by AndyScherzinger** [comment]
Why web and redirect?

**Comment by tobiasKaminsky** [comment]
Well…this is the current behaviour, if there is a link, it will be displayed and you can click on it.

**Comment by AndyScherzinger** [comment]
Well, what I meant is: it should not open a link but rather directly navigate in-app to the details page with the comment for the given file. This way you leave the "native" world and open a web browser while the notification belongs to the app.

What do you think @nextcloud/designers

**Comment by jancborchardt** [comment]
Agree that if you click on a push notification from the app, it should of course open in the app. Or what's the confusion?

**Comment by AndyScherzinger** [comment]
The confusion is that since the notification ships the we link it'll open the browser showing the file details where the user was mentioned and like you and me said it should open the app with the right view, not the browser.
What I can't say from the issues description is if that is possible given the available meta data within the notification.

**Comment by tobiasKaminsky** [comment]
> What I can't say from the issues description is if that is possible given the available meta data within the notification.

It is an enhancement request, so no idea, but the idea was always to let it open in app.

**Comment by AndyScherzinger** [comment]
> It is an enhancement request, so no idea, but the idea was always to let it open in app.

Well, that would then be what all participants within this issue's discussion would expect it to be :) 👍

**Comment by tobiasKaminsky** [comment]
As we now have this cool "open from Talk feature" this should also not be too hard.
I'll have a look.
