### ISSUE TITLE
do not try to download if phone has too little space left

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#4001]
- have a device with only e.g. 300Mb left
- download 500Mb file
- currently downloads and then fails with "no storage left"

-> do something better

@jancborchardt 
@zukunft
@AndyScherzinger

**Comment by tobiasKaminsky** [comment]
From https://github.com/nextcloud/android/issues/2175#issuecomment-449510786

- First, the 10 GB of the server wouldn’t go to the phone directly.
- Then, if you want to open a file which would fill up your phone storage space, we could do 2 things:
    - Try to intelligently clean the least recently cached files
    - Show a warning about it
    - Do both, maybe showing a warning like: "File can not be downloaded because phone storage is full. [ Clear downloaded files ]" ref #3342 (file removal dialog / cached files)

**Comment by jancborchardt** [comment]
Still agree with my suggestion. ;) :+1:

**Comment by joshtrichards** [comment]
Fixed in #5328
