### ISSUE TITLE
Sync, autoupload and upload files not wokr in mobile app.

### ISSUE THREAD

**Issue by Xardas123** [nextcloud/android#4004]
### Actual behaviour
 I configure autoupload on any folder, but nothing will happen. I try setup sync, but 
trouble is same. 
I click on sync any folder in phone. nextcloud icon appears on the status bar, but nothing happens again. 
if I sync a folder on the server, all working good. Files was download from server to my phone.
I think, sync and auto upload not work, because apk can't upload files on the server. Download is work, but upload not.

### Expected behaviour
My phone files are synchronized.
 
### Steps to reproduce
1. Install app
2. Allow all necessary permissions and create an exception in battery saver
3. setup sync nextcloud in android
4. configure autoupload on any folder, or manualy click on sync.
5. I restart my phone
6. I try uninstall app and repeat all steps again

### Environment data
Android version: 9

Device model: Samsung Galaxy S9 SM-G960F

Stock or customized system: stock

Nextcloud app version: 3.6.1 RC2 (May, 08, 2019)

Nextcloud server version: 16.0.0

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by memen45** [comment]
As far as I know, only NEW files will be uploaded, NOT existing files. So after setting up auto upload for a local folder, add some file(s) to this folder and see if they get uploaded automatically.

**Comment by AndyScherzinger** [comment]
> As far as I know, only NEW files will be uploaded, NOT existing files

That is correct, yes.

Other than that since this report mentions a Samsung device, be sure to disable any kind of "Battery Optimization" for the NNextcloud app, else auto uploads and syncs won't work due to Samsung's aggressive battery saving algorithm...

**Comment by uvwxy** [comment]
Is this related to #1920 ?
