### ISSUE TITLE
Allow Kotlin to be used in app code

### ISSUE THREAD

**Issue by ezaquarii** [nextcloud/android#4007]
### Is your feature request related to a problem? Please describe.

According to google, Kotlin is now considered primary Android app development language, not Java.

### Describe the solution you'd like

Just start using it. Project leaders should start familiarizing themselves with Kotlin from now on.

### Describe alternatives you've considered

Start adopting Kotlin in tests, but it seems that testability is not achievable in immediate future.

### Additional context

Google I/O 2019

**Comment by AndyScherzinger** [comment]
Fine with me 👍

**Comment by tobiasKaminsky** [comment]
Fine by me.
Luckily it is compatible, so we can just switch slowly :+1:

**Comment by ezaquarii** [comment]
I guess we're all set here then. :)
