### ISSUE TITLE
License, GPLv3+, GPLv2+, GPL2, GPL3, or a mixture of all?

### ISSUE THREAD

**Issue by comradekingu** [nextcloud/android#4014]
Attemptedly, the license has been [changed to GPLv2 only](https://github.com/nextcloud/android/commit/bdc0332c23b326d21193f71ff7db2cf587de0c43),
where it went from v3+ to v2 only, and from v3+ to v3 only, after being adopted from ownCloud and respective copyright holders.

Some of it is (still) GPLv3+ now…
Unless all copyright holders agree, to my knowledge changing it backwards when it already is "or later", is not legal. Also don't think GPLv3+ is compatible with v2 in one program, though that is a lesser issue I am not so sure about.
I propose making it all GPLv3+, since the "GPLv2 only" parts seems conflicting with the prior license, and as such could be considered void.

The Transifex license info says GPLv2+, but the version of it Nextcloud uses is closed source now, with a rather alarming EULA.

tobias says:
> owncloud code is gpl2, but newer Nextcloud code is v3+.

**Comment by tobiasKaminsky** [comment]
> Also don't think GPLv3+ is compatible with v2 in one program, though that is a lesser issue I am not so sure about.

@schiessle what do you think?



> I propose making it all GPLv3+, since the "GPLv2 only" parts seems conflicting with the prior license, and as such could be considered void.

I doubt that we can do this. As said for newer contributions (Nextcloud) we ask the contributor for gplv3+, but I am pretty sure that the old code will remain gplV2.

**Comment by comradekingu** [comment]
@tobiasKaminsky 
From the FSF website https://www.gnu.org/licenses/gpl-faq.html#v2v3Compatibility

It seems making GPLv2+ code GPLv2 only by Nextcloud before asking all prior rights-holders is legal. https://www.gnu.org/licenses/gpl-faq.html#AllCompatibility
However going from GPLv3+ to GPLv2 only, ([from the same PR](https://github.com/nextcloud/android/commit/bdc0332c23b326d21193f71ff7db2cf587de0c43#diff-934a08193d1654d25d12197eb44d569a)) is not.

It was however GPLv2+, so making it GPLv3+ is allowed, so that part is fine, see links above.

The problem is with being in a place where the only way out of GPLv2 only, which then makes it a requirement for the whole program, requires every prior rights-holder to agree. I hope this is not the case.

Now since a project can't be both GPLv2 only, and GPLv3+ at the same time, and the change making it GPLv2 only tried to put it in such a state against the terms of the GPLv3+ license, I would say that the whole change is void. However, IANAL, but if I were to guess, either everything happening since then is "unlicensed", or just follows in the lines of the prior workable state/license, as that is the program people contribute to.

From the GPLv3+  

> If the Program does not specify a version number of the GNU General Public License, you may choose any version ever published by the Free Software Foundation.

In my head not presenting contributors with a legal option falls under this logic, and GPLv3+ can be selected. However, someone needs to do something about the GPLv2 only change.

As for newer contributions being GPLv3+, where does it say that?
It seems the license file for the Android client was part of the aforementioned attempted license change https://github.com/nextcloud/android/commit/bdc0332c23b326d21193f71ff7db2cf587de0c43#diff-61e0bdf7e1b43c5c93d9488b22e04170
I say attempted, because of the legality, and also it seems to have been done in a replace-all fashion.

**Comment by tobiasKaminsky** [comment]
> It seems making GPLv2+ code GPLv2 only by Nextcloud before asking all prior rights-holders is legal. [gnu.org/licenses/gpl-faq.html#AllCompatibility](https://www.gnu.org/licenses/gpl-faq.html#AllCompatibility)
> However going from GPLv3+ to GPLv2 only, ([from the same PR](https://github.com/nextcloud/android/commit/bdc0332c23b326d21193f71ff7db2cf587de0c43#diff-934a08193d1654d25d12197eb44d569a)) is not.

This is a change that was done long before Nextcloud (change was done at 17.04.2013, NC started at 2.06.16).



> It was however all GPLv2+ (?) before the attempted GPLv2-only change, so making it GPLv3+ from all GPLv2+ previously is allowed, so that part is fine, see links above.

We do not change any "old" licences.
But we encourage contributor to contribute their new files under GPLv3+:
https://github.com/nextcloud/android#contribution-guidelines--license

> GPLv2. All contributions to this repository from June, 16 2016 on are considered to be licensed under the AGPLv3 or any later version.

We should reflect this also in License.txt

**Comment by jancborchardt** [comment]
The info is stated in the Readme at https://github.com/nextcloud/android#contribution-guidelines--license

Closing hence.

**Comment by comradekingu** [comment]
@jancborchardt That isn't the problem. Effectively that dual-licenses the code.

The problem is using code that attemptedly has been changed in hap-hazardous ways seemingly putting the codebase in an illegal state, and nontheless would require copyright-holder consent to do so.

Possibly what the distributed binaries say could also be problematic.
