### ISSUE TITLE
Accessing CI build artifacts

### ISSUE THREAD

**Issue by ezaquarii** [nextcloud/android#4017]
### Is your feature request related to a problem? Please describe.

I want to run CI-built package when reviewing a PR. I need to fetch the source code and compile it myself.

### Describe the solution you'd like

Since CI has already build apks at this point, why just not fetch them from there?
1. A QR code with URL to the APK could be posted in PR discussion automatically when CI build is complete.
2. Build artifacts can be cleared automatically after some delta T

### Additional context

Current setup discourages smoke testing while reviewing PRs as there is no convenient way to fetch build artifacts.

**Comment by tobiasKaminsky** [comment]
This is a really cool idea.
I'll take a look soon.

**Comment by AndyScherzinger** [comment]
Sound very nice indeed. I'd be even fine with just a link since I usually access GH via my phone during the day. But yeah, if you use a big screen you might want to have that QR code of course.

**Comment by tobiasKaminsky** [comment]
As this is a dev version, I'll sign it with no key.
This might then lead to a conflict if official app is installed, but I do not want that people install it and assume that it is an official release.

**Comment by AndyScherzinger** [comment]
👍 Perfectly fine

**Comment by Valdnet** [comment]
> This might then lead to a conflict if official app is installed, 

What conflict do you speak about?

Will the installation of the new dev version be without problems?

**Comment by tobiasKaminsky** [comment]
Android checks for same package name.
Dev version has a different package name, so this is not a problem.

But if you have installed offical gplay/fdroid version and want to manually install an APK from one of the upcoming PRs, this will lead to a conflict, as the package name are the same, but gplay/fdroid is offically signed, whereas the APK from PR is not.

**Comment by tobiasKaminsky** [comment]
Please have a look at #4018 @AndyScherzinger @ezaquarii
