### ISSUE TITLE
Virus PUA.Andr.Trojan.Mobidash-6840972-0 in nextcloud-30060190.apk?

### ISSUE THREAD

**Issue by zxtwonder** [nextcloud/android#4021]
Downloaded nextcloud-30060190.apk from https://github.com/nextcloud/android/releases/download/stable-3.6.1/nextcloud-30060190.apk and uploaded to our Nextcloud 16.0.0 deployment.

However, clamav complains that it contains PUA.Andr.Trojan.Mobidash-6840972-0.

`OCP\Files\InvalidContentException: Virus PUA.Andr.Trojan.Mobidash-6840972-0 is detected in the file. Upload cannot be completed.`

Is it a false positive hit?

**Comment by tobiasKaminsky** [comment]
```
root@tobi-laptop:/tmp # freshclam
ClamAV update process started at Tue May 14 14:15:05 2019
main.cvd is up to date (version: 58, sigs: 4566249, f-level: 60, builder: sigmgr)
daily.cvd is up to date (version: 25449, sigs: 1569506, f-level: 63, builder: raynman)
bytecode.cld is up to date (version: 328, sigs: 94, f-level: 63, builder: neo)
root@tobi-laptop:/tmp # 
tobi@tobi-laptop:/tmp » clamscan nextcloud-30060190.apk
nextcloud-30060190.apk: OK

----------- SCAN SUMMARY -----------
Known viruses: 6126872
Engine version: 0.101.2
Scanned directories: 0
Scanned files: 1
Infected files: 0
Data scanned: 41.05 MB
Data read: 9.39 MB (ratio 4.37:1)
Time: 34.949 sec (0 m 34 s)
```

I cannot reproduce this.
As this is always built directly from github, I am pretty sure that this is virus free.

**Comment by tobiasKaminsky** [comment]
Can you update your clamAV and test it again?

**Comment by zxtwonder** [comment]
Yes, I will try to run again directly in the clamav container and see the result.

I just tried in our test deployment and got the same report. Our clamav container is built from 
`FROM mk0x/docker-clamav:alpine` and with freshclam:

```conf
###############
# General
###############

DatabaseDirectory /store
LogSyslog yes
LogTime yes
PidFile /run/clamav/freshclam.pid
DatabaseOwner root

###############
# Updates
###############

DatabaseMirror db.cn.clamav.net
DatabaseMirror db.hk.clamav.net
DatabaseMirror db.us.clamav.net
DatabaseMirror database.clamav.net
ScriptedUpdates yes
NotifyClamd /etc/clamav/clamd.conf
SafeBrowsing yes
Bytecode yes
```

**Comment by zxtwonder** [comment]
Need to do it a little later, but just tried to upload the apk decompressed and got clamav points to classes.dex file:

```
[files_antivirus] Warning: Infected file deleted. PUA.Andr.Trojan.Mobidash-6840972-0 Account: *** Path: files/nextcloud-30060190/classes.dex.ocTransferId688959901.part

PUT /remote.php/webdav/nextcloud-30060190/classes.dex
```

**Comment by tobiasKaminsky** [comment]
https://www.virustotal.com/gui/home/upload is a scanner for 60 engines and it also did not found anything…

**Comment by zxtwonder** [comment]
Ok, probably is a false-positive here then. Will close to avoid false alerts. Will do some analysis later to see what caused the clamav to panic.

**Comment by tobiasKaminsky** [comment]
Ok, if you encounter anything, please reply back :-)
