### ISSUE TITLE
Switching between Profiles does not work

### ISSUE THREAD

**Issue by sten-schmidt** [nextcloud/android#4022]
### Actual behaviour
Switching between Profiles does not work in App-Version 3.6.1.
The last added Account (B) is used, even when selecting Account A.

### Expected behaviour
Selected Account should be used.
 
### Steps to reproduce
1. Install App-Version 3.6.1 via PlayStore or APK.
2. Configure Account A with Nextcloud-Instance A. 
3. Add another Account B for Nextcloud-Instance B. 
4. Try to select Account A
 
### Current Workaround
1. Uninstall App-Version 3.6.1.
2. Install old App-Version 3.6.0 via APK (https://github.com/nextcloud/android/releases/tag/stable-3.6.0).

### Environment data
Android version: 9 
Device model: OnePlus 6 (A6003)
Stock or customized system: Stock (OxygenOS 9.0.5)
Nextcloud app version: 3.6.1
Nextcloud server version: 14.x + 13.x

**Comment by tobiasKaminsky** [comment]
This is solved via #4031

**Comment by sten-schmidt** [comment]
Issue solved with 3.6.2 RC1

**Comment by AndyScherzinger** [comment]
Thanks for the feedback @sten-schmidt 👍
