### ISSUE TITLE
Sync on save doesn't work properly

### ISSUE THREAD

**Issue by volhovm** [nextcloud/android#4024]
Expected behaviour: I would like to open pdfs from the pdf reader directly (from the place nextcloud stores my synced files), annotate them in-place, save them from the reader, and see how nextcloud sees the content change and syncs the item automatically.

What happens in reality is that autosave is not triggered. It syncs only if I do it manually (from nextcloud app), or if I re-open the file from the nextcloud. I can open my file from the reader many times, and it seemingly doesn't lead to the file being synced.

I am not sure whether it is a bug or intended behaviour/absence of feature.

**Comment by AndyScherzinger** [comment]
This would be a question for @tobiasKaminsky. What happens after you save the PDF within 15 minutes while being connected to wifi?
Also are you using a Samsung device with a battery saver?

**Comment by volhovm** [comment]
I have just checked it -- modified file doesn't sync automatically after an hour, though the tablet is connected to the wifi. I am using Xiaomi Mi Pad 4 Plus, I guess it doesn't have any explicit "battery saving" feature. 

It does work though on my Xiaomi Mi A2 lite smartphone with the battery saving feature turned off explicitly, after 5-10 minutes the file auto-syncs.

**Comment by volhovm** [comment]
The issue disappeared after I tuned the power saving settings properly. I'm closing the issue.
