### ISSUE TITLE
IllegalStateException on Toolbar

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#4026]
```
Caused by: java.lang.IllegalStateException: 
  at androidx.appcompat.app.AppCompatDelegateImpl.setSupportActionBar (AppCompatDelegateImpl.java:345)
  at androidx.appcompat.app.AppCompatActivity.setSupportActionBar (AppCompatActivity.java:130)
  at com.owncloud.android.ui.activity.ToolbarActivity.setupToolbar (ToolbarActivity.java:69)
  at com.owncloud.android.ui.activity.ToolbarActivity.setupToolbar (ToolbarActivity.java:99)
  at com.owncloud.android.ui.activity.FileDisplayActivity.onCreate (FileDisplayActivity.java:244)
  at android.app.Activity.performCreate (Activity.java:7326)
  at android.app.Activity.performCreate (Activity.java:7317)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1271)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3066)
```

This is the IllegalStateException:
`"This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead."`

Seems to happen quite often, starting with 3.6.1 RC2.
Unfortunately I do not have any infos how to reproduce it.

**Comment by tobiasKaminsky** [comment]
Hm. So it seems to be a problem when creating FileDisplayActivity
https://github.com/nextcloud/android/blob/afc11086e2b86905ec55a8d55181941b6c080ba5/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java#L243-L244

A few lines above we do set a theme:
https://github.com/nextcloud/android/blob/afc11086e2b86905ec55a8d55181941b6c080ba5/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java#L222-L223

This theme is implemented two times:
https://github.com/nextcloud/android/blob/ba24f648a0b5a38e973cab056b450827633b8b60/src/main/res/values/styles.xml#L73-L75
https://github.com/nextcloud/android/blob/a038c2c83732a668c07d6f642789af0df5d6b103/src/main/res/values-v21/styles.xml#L33-L35

Judging from the crashes it is only a 21+ thing.

In v21/styles.xml there is no "windowActionBar" -> false.
I wonder why this crash happens now, as we have this included a long time…last change was 06/2016…

So I would add "windowActionBar" false to v21/styles?
But I would really like to have a way to reproduce it …

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger since it seems that you implemented it back then…
Do you have any idea why it now result in crashes?

**Comment by AndyScherzinger** [comment]
I have no idea why this crashes now. This scenario happened back then in 2016 in case the theme declared having an action bar and you added a toolbar which is what we prevented afaik.

So yes, setting it to false is the correct way I think. Can you give it a try?

**Comment by Unpublished** [comment]
If you want to reproduce:
1. Enable "Don't keep activities" in Developer options.
2. Open Nextcloud
3. Leave app (by pressing home)
4. Open Nextcloud again->crash

**Comment by tobiasKaminsky** [comment]
@Unpublished thanks for finding steps how to reproduce it.
You added "pr exists". Is this fixed within #3459?

As this is a rather annoying bug, I would like to release a 3.6.2 soon, containing this fix.
Can you point me to the fix?

**Comment by AndyScherzinger** [comment]
The added test in the PR seems to fail actually (even though there is a fixing change? 0_o)

**Comment by Unpublished** [comment]
I added the test first so you can see that the issue is actually triggered in my test. Afterwards I pushed the fix but gplay stage failed due to connectivity issues of drone, I guess.
