### ISSUE TITLE
Re-add Exception handler

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#4030]
Like in Deck app: if we encounter an Exception, we can show a nice dialog.
Pre-requisites are already at https://github.com/nextcloud/android/blob/9130635fa1b9ba7b18a08cb54177c2924c2a8d8c/src/main/java/com/owncloud/android/ui/errorhandling/ExceptionHandler.java#L30

**Comment by ezaquarii** [comment]
Pls check out #4039

**Comment by tobiasKaminsky** [comment]
PR: 
#4056 ExceptionHandler
#4039 ACRA
