### ISSUE TITLE
Add resizing and WebP support to instantupload

### ISSUE THREAD

**Issue by jmaris** [nextcloud/android#4045]
### Is your feature request related to a problem? Please describe.
InstantUpload of photo's is one of my favourite features in the Nextcloud app, however on nextcloud installs with limited space, and for users who take lots of photos, it can quickly fill up.

### Describe the solution you'd like
I propose the InstantUpload feature integrates conversion to webp, which would allow significant size reductions in images.  resizing could also be made availiable, as with _google photos_

**Comment by joshtrichards** [comment]
This could be done server-side utilizing this already:

https://github.com/nextcloud/workflow_script

People do similar with video format conversion..
