### ISSUE TITLE
Change default InstantUpload location

### ISSUE THREAD

**Issue by okulev** [nextcloud/android#405]
### Actual behaviour
-Tell us what happens
When instant upload is activated, the default Nextcloud location is /InstantUpload

### Expected behaviour
-Tell us what should happen
Please change default location to its natural place - in Photos folder, so that default location is /Photos/InstantUpload

### Environment data
Nextcloud app version:
1.3.1

Nextcloud server version:
10.0.1

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky what is your opinion on this? I'd vote to keep it like it is (/InstantUpload) since 1.4.0 will introduce Auto-upload which will allow any image-media to be uploaded, e.g. screenshots and post 1.4.0 version will allow generic sync here so /Photos/InstantUpload would be wrong then. Other than that I see the issue of simply breaking existign client installations which are using today's default since we would then simply be updating their default...

**Comment by okulev** [comment]
If you have such plans, I recommend to have separate option for instant upload of photos to /Photos/InstantUpload (or custom location) while the rest to go to current location.

**Comment by AndyScherzinger** [comment]
@okulev can you elaborate a bit more on this idea? Looking at my phone will show my more then 10 folders to upload just for images like: Camera, WhatsApp Images, Instagram, Screenshots, etc. so I want all of these to go into /Photos/<The original name> while at the same time (post 1.4.0) I will also have "video", "audio" and "whatever" (the later being any kind of local/remote folder pair). So when Auto upload get's activatedd for Android 5+ and all evolutionary versions of this implementation are done it'll be a complete folder sync. So even now for the initial release (looking at the screenshot scenario) setting the default to /Photos/... wouldn't be correct.

**Comment by okulev** [comment]
I use FolderSync Lite to backup various folders to my Nextcloud and it's great that such feature is planned. It is perfectly fine for me to have default folder for all synced folders (/InstantUpload) that can be changed, and also ability to customize individual folders to be uploaded to some different location (e.g. /DCIM to be uploaded to /Photos/MyPhone instead of /InstantUpload).

**Comment by jrullo** [comment]
After installing the Andoid NextCloud app, I only see Auto Upload. I don't see any label "Instant Upload". However, on the server, the app tries to upload to a folder called Instant Upload. I want what I see on the app which is to upload to the directory I set in the app.

The Auto Upload section has as the first option the ability to set a directory where to upload files.
This does not work at all. After selecting a destination directory, I can see that the directory is set. As a test, I manually uploaded a file on my phone from the camera directory to the same directory set in the Auto Upload. NextCloud seems to try to upload to a folder Camera, which doesn't exist, and never uploads to the directory I set in the settings on the phone app. 

I started with app version 1.40. Now have 1.41. Neither works as expected. Instead, I get hundreds of "successul" uploads of less than 20k files all named the same as my photos, however, the extension is .0, not .jpg as they should be. I also get similar filenames listed as failed uploads on the app "Uploads" tab. 

I'm struggling to understand why you would have an option to set the remote destination directory and not actually try to upload there. I see zero information on the NextCloud Admin area log. There are no errors in the apache2 error logs. If it were a permissions problem, then I shouldn't be able to manually upload a file using the app.

**Comment by AndyScherzinger** [comment]
@jrullo what is your Android version and device model?

@tobiasKaminsky we should then also exclude .0 as a file extension. As for the folder issue, what do you think @tobiasKaminsky regarding the folder issue? We always add the local folder so activating several local media folders get their own folder automatically.

**Comment by AndyScherzinger** [comment]
@jancborchardt @eppfel any comment here UX wise? For the auto upload we always add the local folder to the chosen path, so each activated image folder will result in exactly the same folder on the server side within the folder a user has chosen. The discussion here is the user's whish to not do this. 

Both solutions, automagically adding a folder and never adding a folder, seem not optimal in my opinion. Maybe there is a even better solution I am not aware of :)

**Comment by eppfel** [comment]
Can't we let the user decide in the dialog where he selects the folder?

It's hard to wrap my head around the flow. Do not use the feature myself.

**Comment by jancborchardt** [comment]
I think naming the folders automatically makes sense. And with the new Autoupload this issue is a bit outdated, no?

**Comment by AndyScherzinger** [comment]
exactly, 1.5 or 1.5+ rather will render this issue more or less obsolete. While we will still have auto naming in place, which is what we decided on after several discussions. ...and yes that is a trade off for comfort/90%-usecase over flexibility ;)

**Comment by gloschtla** [comment]
I wish to be able to modify the _default_ instant upload directory.
The preferred storage in my nextcloud account is mounted as an external storage, because the native nextcloud storage is insufficient. So my media files can only be uploaded to **/MyLinkToExternalStorage/InstantUploads** 
Therefore, with its fixed default directory **/InstantUploads**, this Nextcloud Client makes no sense to me.

**Comment by tobiasKaminsky** [comment]
You can configure this in each folder, just click on remote folder:
![2019-02-04-095144](https://user-images.githubusercontent.com/5836855/52198258-7e287f00-2862-11e9-8928-ba5737bbaa19.png)


Regarding the original request: I do not think we should change the current naming. However every user can set up their own paths.
I think this is good enough.

**Comment by gloschtla** [comment]
This does not help, if you have a camera app which creates a new subfolder every day. The result is that nextcloud notifys me every new day: "Oh, I discovered a new photo folder. Shall I sync it to the (default) remove directory?" So for every day (for each recognized new picture's subfolder) I would have to change the remove directory manually. This effort makes the Instant Uploads Feature useless, because it takes the same time to manually upload the new pictures daily. 
The only workaround now is, to stop the Camera App from creating new subfolders.

**Comment by tobiasKaminsky** [comment]
This seems to be independent from my last answers and also not match the original request.
Please open up a new issue for this, if there is no matching issue.

**Comment by oddstr13** [comment]
I was unable to find an app-wide default setting, was this not implemented?

I'd like to replace the default `/InstantUpload/` prefix with something else, as to avoid having to manually create and choose the path for every directory.

**Comment by jaded0** [comment]
I'd also like the above feature. This 'good enough' reasoning isn't good enough

**Comment by pafcioooo** [comment]
In case someone is interested in this feature, there seems to be a new approach to this issue #1310.
