### ISSUE TITLE
hello nextcloud crashes when i upload something , my phone is ASUS znefone max pro m1, android 8.1, thanks

### ISSUE THREAD

**Issue by zourit77** [nextcloud/android#4054]
### Actual behaviour
- Tell us what happens

### Expected behaviour
- Tell us what should happen
 
### Steps to reproduce
1. 
2. 
3. 

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by ezaquarii** [comment]
Hi @zourit77, thank you for reporting the issue. Unfortunately we cannot proceed with it without any details. Could you please fill the form that you can find in bug description?
