### ISSUE TITLE
Upload not working with nextcloud in subdir

### ISSUE THREAD

**Issue by SR4ven** [nextcloud/android#4059]
### Actual behaviour
Uploading files from the android app get stuck at 0% and never complete.
My guess is that this happens because of an invalid request, that doesn't match the subdir Nextcloud is running in.
Browsing and downloading files in the app works fine. Uploading works fine from the website and Windows sync client.

### Expected behaviour
File upload should work
 
### Steps to reproduce
1. Setup a Nextcloud server in another location than the webroot and configure an alias (apache2) + ` 'htaccess.RewriteBase' => '/cloud'` in the nextcloud config.php
2. Try to upload a file from the mobile app

### Environment data
Android version: 9

Device model: Galaxy S9

Stock or customized system: Stock

Nextcloud app version: 3.6.1

Nextcloud server version: 16.0.1

#### vHost config
```
</VirtualHost>
<IfModule mod_ssl.c>
<VirtualHost *:443>
        ServerName *******
        <IfModule mod_headers.c>
                Header always set Strict-Transport-Security "max-age=15552000; includeSubDomains"
        </IfModule>

        Alias /cloud "/media/DATA/cloud/Nextcloud"
        <Directory /media/DATA/cloud/Nextcloud>
                Options +FollowSymLinks
                AllowOverride All
                Satisfy Any

                <IfModule mod_dav.c>
                        Dav off
                </IfModule>

                SetEnv HOME /media/DATA/cloud/Nextcloud
                SetEnv HTTP_HOME /media/DATA/cloud/Nextcloud

        </Directory>

        Protocols h2 http/1.1
        <IfModule mod_rewrite.c>
                RewriteEngine on
                RewriteRule ^/\.well-known/host-meta            /cloud/public.php?service=host-meta             [QSA,L]
                RewriteRule ^/\.well-known/host-meta\.json      /cloud/public.php?service=host-meta-json        [QSA,L]
                RewriteRule ^/\.well-known/webfinger            /cloud/public.php?service=webfinger             [QSA,L]
                RewriteRule ^/\.well-known/carddav              /cloud/remote.php/dav/                          [R=301,L]
                RewriteRule ^/\.well-known/caldav               /cloud/remote.php/dav/                          [R=301,L]
                RewriteRule ^/ocm-provider                      /cloud/ocm-provider/                            [R=301,L]
                RewriteRule ^/ocs-provider                      /cloud/ocs-provider/                            [R=301,L]
                RewriteRule ^/apps                              /cloud/apps/                                    [R=301,L]
                RewriteRule ^/core                              /cloud/core/                                    [R=301,L]
                RewriteRule ^/dav                               /cloud/dav/                                     [R=301,L]
                RewriteRule ^/webdav                            /cloud/webdav/                                  [R=301,L]
        </IfModule>

        CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
</IfModule>
```

#### Web server error log
```
[Wed May 22 18:34:50.632619 2019] [authz_core:error] [pid 634:tid 547658650016] [client 192.168.1.188:51483] AH01630: client denied by server configuration: /var/www/html/webdav
[Wed May 22 18:34:53.131863 2019] [authz_core:error] [pid 634:tid 547138564512] [client 192.168.1.188:51483] AH01630: client denied by server configuration: /var/www/html/webdav
[Wed May 22 18:34:54.629504 2019] [authz_core:error] [pid 634:tid 548020937120] [client 192.168.1.188:51483] AH01630: client denied by server configuration: /var/www/html/webdav
(repeated many times)
```

#### Web server access log
```
192.168.1.188 - - [22/May/2019:18:18:51 +0200] "HEAD /cloud/remote.php/webdav/Test/2019/IMG-20190517-WA0000%20(86).jpg HTTP/1.1" 302 1039 "-" "Mozilla/5.0 (Android) ownCloud-android/3.6.1"
192.168.1.188 - - [22/May/2019:18:18:52 +0200] "HEAD /cloud/apps/files/ HTTP/1.1" 200 831 "-" "Mozilla/5.0 (Android) ownCloud-android/3.6.1"
192.168.1.188 - - [22/May/2019:18:18:52 +0200] "HEAD /cloud/remote.php/webdav/Test/2019/IMG-20190517-WA0000%20(87).jpg HTTP/1.1" 302 1039 "-" "Mozilla/5.0 (Android) ownCloud-android/3.6.1"
192.168.1.188 - - [22/May/2019:18:18:53 +0200] "HEAD /cloud/apps/files/ HTTP/1.1" 200 831 "-" "Mozilla/5.0 (Android) ownCloud-android/3.6.1"
192.168.1.188 - - [22/May/2019:18:18:53 +0200] "HEAD /cloud/remote.php/webdav/Test/2019/IMG-20190517-WA0000%20(88).jpg HTTP/1.1" 302 1039 "-" "Mozilla/5.0 (Android) ownCloud-android/3.6.1"
(repeated many times)
```

#### Nextcloud log (data/nextcloud.log)
```
Just login info/no errors
```

**Comment by piknew** [comment]
I can confirm that the same behavior happens with config that do not include alias. Seems that it is neverending loop (original file name was "IMG_20190630_191053.jpg" but some kind of suffix appers in log).

`<IfModule mod_ssl.c>
        <VirtualHost *:443>

                Define servername my.hidden.host.name

                ServerName ${servername}:443
                ServerAlias ${servername}
                ServerAdmin admin@my.hidden.domain

                Include conf-custom/ssl-options.conf

                Include conf-custom/strict-transport-security.conf
                Include conf-custom/referrer-policy.conf

                ProxyRequests off

                ProxyErrorOverride on

                Define documentroot /share/data/www/nextcloud

                DocumentRoot ${documentroot}

                <Directory ${documentroot}>
                        Options Indexes FollowSymLinks
                        AllowOverride All
                        Require all granted
                </Directory>

                <FilesMatch ".+\.ph(ar|p|tml)$">
                        SetHandler "proxy:fcgi://localhost:9007"
                </FilesMatch>
                <FilesMatch ".+\.phps$">
                        Require all denied
                </FilesMatch>
                <FilesMatch "^\.ph(ar|p|ps|tml)$">
                        Require all denied
                </FilesMatch>

        </VirtualHost>
</IfModule>
`

`Jul  2 10:11:01 my.host.name apache[24142]: my.hidden.host.name:443 37.47.58.8 - "HEAD /remote.php/webdav/IMG_20190630_191053.jpg HTTP/1.1" 302 RX:1215 TX:4949 "-" "Mozilla/5.0 (Android) ownCloud-android/3.6.2"
Jul  2 10:11:02 my.host.name apache[24152]: my.hidden.host.name:443 37.47.58.8 - "HEAD /index.php/apps/files/ HTTP/1.1" 200 RX:599 TX:857 "-" "Mozilla/5.0 (Android) ownCloud-android/3.6.2"
Jul  2 10:11:03 my.host.name apache[24170]: my.hidden.host.name:443 37.47.58.8 - "HEAD /remote.php/webdav/IMG_20190630_191053%20(2).jpg HTTP/1.1" 302 RX:625 TX:1071 "-" "Mozilla/5.0 (Android) ownCloud-android/3.6.2"
Jul  2 10:11:03 my.host.name apache[24180]: my.hidden.host.name:443 37.47.58.8 - "HEAD /index.php/apps/files/ HTTP/1.1" 200 RX:599 TX:857 "-" "Mozilla/5.0 (Android) ownCloud-android/3.6.2"
Jul  2 10:11:04 my.host.name apache[24198]: my.hidden.host.name:443 37.47.58.8 - "HEAD /remote.php/webdav/IMG_20190630_191053%20(3).jpg HTTP/1.1" 302 RX:625 TX:1071 "-" "Mozilla/5.0 (Android) ownCloud-android/3.6.2"
Jul  2 10:11:05 my.host.name apache[24208]: my.hidden.host.name:443 37.47.58.8 - "HEAD /index.php/apps/files/ HTTP/1.1" 200 RX:599 TX:857 "-" "Mozilla/5.0 (Android) ownCloud-android/3.6.2"
Jul  2 10:11:06 my.host.name apache[24226]: my.hidden.host.name:443 37.47.58.8 - "HEAD /remote.php/webdav/IMG_20190630_191053%20(4).jpg HTTP/1.1" 302 RX:625 TX:1071 "-" "Mozilla/5.0 (Android) ownCloud-android/3.6.2"
Jul  2 10:11:06 my.host.name apache[24236]: my.hidden.host.name:443 37.47.58.8 - "HEAD /index.php/apps/files/ HTTP/1.1" 200 RX:599 TX:857 "-" "Mozilla/5.0 (Android) ownCloud-android/3.6.2"
Jul  2 10:11:07 my.host.name apache[24254]: my.hidden.host.name:443 37.47.58.8 - "HEAD /remote.php/webdav/IMG_20190630_191053%20(5).jpg HTTP/1.1" 302 RX:625 TX:1071 "-" "Mozilla/5.0 (Android) ownCloud-android/3.6.2"
Jul  2 10:11:08 my.host.name apache[24264]: my.hidden.host.name:443 37.47.58.8 - "HEAD /index.php/apps/files/ HTTP/1.1" 200 RX:599 TX:857 "-" "Mozilla/5.0 (Android) ownCloud-android/3.6.2"
Jul  2 10:11:09 my.host.name apache[24282]: my.hidden.host.name:443 37.47.58.8 - "HEAD /remote.php/webdav/IMG_20190630_191053%20(6).jpg HTTP/1.1" 302 RX:625 TX:1071 "-" "Mozilla/5.0 (Android) ownCloud-android/3.6.2"
Jul  2 10:11:10 my.host.name apache[24293]: my.hidden.host.name:443 37.47.58.8 - "HEAD /index.php/apps/files/ HTTP/1.1" 200 RX:599 TX:857 "-" "Mozilla/5.0 (Android) ownCloud-android/3.6.2"
Jul  2 10:11:10 my.host.name apache[24312]: my.hidden.host.name:443 37.47.58.8 - "HEAD /remote.php/webdav/IMG_20190630_191053%20(7).jpg HTTP/1.1" 302 RX:625 TX:1071 "-" "Mozilla/5.0 (Android) ownCloud-android/3.6.2"
Jul  2 10:11:11 my.host.name apache[24348]: my.hidden.host.name:443 37.47.58.8 - "HEAD /index.php/apps/files/ HTTP/1.1" 200 RX:599 TX:857 "-" "Mozilla/5.0 (Android) ownCloud-android/3.6.2"
Jul  2 10:11:12 my.host.name apache[24367]: my.hidden.host.name:443 37.47.58.8 - "HEAD /remote.php/webdav/IMG_20190630_191053%20(8).jpg HTTP/1.1" 302 RX:625 TX:1071 "-" "Mozilla/5.0 (Android) ownCloud-android/3.6.2"
Jul  2 10:11:12 my.host.name apache[24377]: my.hidden.host.name:443 37.47.58.8 - "HEAD /index.php/apps/files/ HTTP/1.1" 200 RX:599 TX:857 "-" "Mozilla/5.0 (Android) ownCloud-android/3.6.2"
Jul  2 10:11:13 my.host.name apache[24395]: my.hidden.host.name:443 37.47.58.8 - "HEAD /remote.php/webdav/IMG_20190630_191053%20(9).jpg HTTP/1.1" 302 RX:625 TX:1071 "-" "Mozilla/5.0 (Android) ownCloud-android/3.6.2"
Jul  2 10:11:14 my.host.name apache[24405]: my.hidden.host.name:443 37.47.58.8 - "HEAD /index.php/apps/files/ HTTP/1.1" 200 RX:599 TX:857 "-" "Mozilla/5.0 (Android) ownCloud-android/3.6.2"
Jul  2 10:11:15 my.host.name apache[24423]: my.hidden.host.name:443 37.47.58.8 - "HEAD /remote.php/webdav/IMG_20190630_191053%20(10).jpg HTTP/1.1" 302 RX:626 TX:1071 "-" "Mozilla/5.0 (Android) ownCloud-android/3.6.2"
Jul  2 10:11:15 my.host.name apache[24433]: my.hidden.host.name:443 37.47.58.8 - "HEAD /index.php/apps/files/ HTTP/1.1" 200 RX:599 TX:857 "-" "Mozilla/5.0 (Android) ownCloud-android/3.6.2"
Jul  2 10:11:16 my.host.name apache[24451]: my.hidden.host.name:443 37.47.58.8 - "HEAD /remote.php/webdav/IMG_20190630_191053%20(11).jpg HTTP/1.1" 302 RX:626 TX:1071 "-" "Mozilla/5.0 (Android) ownCloud-android/3.6.2"
Jul  2 10:11:17 my.host.name apache[24461]: my.hidden.host.name:443 37.47.58.8 - "HEAD /index.php/apps/files/ HTTP/1.1" 200 RX:599 TX:857 "-" "Mozilla/5.0 (Android) ownCloud-android/3.6.2"
Jul  2 10:11:17 my.host.name apache[24479]: my.hidden.host.name:443 37.47.58.8 - "HEAD /remote.php/webdav/IMG_20190630_191053%20(12).jpg HTTP/1.1" 302 RX:626 TX:1071 "-" "Mozilla/5.0 (Android) ownCloud-android/3.6.2"
Jul  2 10:11:18 my.host.name apache[24489]: my.hidden.host.name:443 37.47.58.8 - "HEAD /index.php/apps/files/ HTTP/1.1" 200 RX:599 TX:857 "-" "Mozilla/5.0 (Android) ownCloud-android/3.6.2"
Jul  2 10:11:19 my.host.name apache[24507]: my.hidden.host.name:443 37.47.58.8 - "HEAD /remote.php/webdav/IMG_20190630_191053%20(13).jpg HTTP/1.1" 302 RX:626 TX:1071 "-" "Mozilla/5.0 (Android) ownCloud-android/3.6.2"
Jul  2 10:11:19 my.host.name apache[24517]: my.hidden.host.name:443 37.47.58.8 - "HEAD /index.php/apps/files/ HTTP/1.1" 200 RX:599 TX:857 "-" "Mozilla/5.0 (Android) ownCloud-android/3.6.2"
Jul  2 10:11:20 my.host.name apache[24535]: my.hidden.host.name:443 37.47.58.8 - "HEAD /remote.php/webdav/IMG_20190630_191053%20(14).jpg HTTP/1.1" 302 RX:626 TX:1071 "-" "Mozilla/5.0 (Android) ownCloud-android/3.6.2"
Jul  2 10:11:21 my.host.name apache[24545]: my.hidden.host.name:443 37.47.58.8 - "HEAD /index.php/apps/files/ HTTP/1.1" 200 RX:599 TX:857 "-" "Mozilla/5.0 (Android) ownCloud-android/3.6.2"
Jul  2 10:11:22 my.host.name apache[24563]: my.hidden.host.name:443 37.47.58.8 - "HEAD /remote.php/webdav/IMG_20190630_191053%20(15).jpg HTTP/1.1" 302 RX:626 TX:1071 "-" "Mozilla/5.0 (Android) ownCloud-android/3.6.2"
Jul  2 10:11:22 my.host.name apache[24573]: my.hidden.host.name:443 37.47.58.8 - "HEAD /index.php/apps/files/ HTTP/1.1" 200 RX:599 TX:857 "-" "Mozilla/5.0 (Android) ownCloud-android/3.6.2"
Jul  2 10:11:23 my.host.name apache[24591]: my.hidden.host.name:443 37.47.58.8 - "HEAD /remote.php/webdav/IMG_20190630_191053%20(16).jpg HTTP/1.1" 302 RX:626 TX:1071 "-" "Mozilla/5.0 (Android) ownCloud-android/3.6.2"
Jul  2 10:11:24 my.host.name apache[24601]: my.hidden.host.name:443 37.47.58.8 - "HEAD /index.php/apps/files/ HTTP/1.1" 200 RX:599 TX:857 "-" "Mozilla/5.0 (Android) ownCloud-android/3.6.2"
Jul  2 10:11:25 my.host.name apache[24619]: my.hidden.host.name:443 37.47.58.8 - "HEAD /remote.php/webdav/IMG_20190630_191053%20(17).jpg HTTP/1.1" 302 RX:626 TX:1071 "-" "Mozilla/5.0 (Android) ownCloud-android/3.6.2"
Jul  2 10:11:25 my.host.name apache[24629]: my.hidden.host.name:443 37.47.58.8 - "HEAD /index.php/apps/files/ HTTP/1.1" 200 RX:599 TX:857 "-" "Mozilla/5.0 (Android) ownCloud-android/3.6.2"
Jul  2 10:11:26 my.host.name apache[24647]: my.hidden.host.name:443 37.47.58.8 - "HEAD /remote.php/webdav/IMG_20190630_191053%20(18).jpg HTTP/1.1" 302 RX:626 TX:1071 "-" "Mozilla/5.0 (Android) ownCloud-android/3.6.2"
Jul  2 10:11:27 my.host.name apache[24657]: my.hidden.host.name:443 37.47.58.8 - "HEAD /index.php/apps/files/ HTTP/1.1" 200 RX:599 TX:857 "-" "Mozilla/5.0 (Android) ownCloud-android/3.6.2"
Jul  2 10:11:28 my.host.name apache[24675]: my.hidden.host.name:443 37.47.58.8 - "HEAD /remote.php/webdav/IMG_20190630_191053%20(19).jpg HTTP/1.1" 302 RX:626 TX:1071 "-" "Mozilla/5.0 (Android) ownCloud-android/3.6.2"
Jul  2 10:11:28 my.host.name apache[24685]: my.hidden.host.name:443 37.47.58.8 - "HEAD /index.php/apps/files/ HTTP/1.1" 200 RX:599 TX:857 "-" "Mozilla/5.0 (Android) ownCloud-android/3.6.2"
Jul  2 10:11:29 my.host.name apache[24703]: my.hidden.host.name:443 37.47.58.8 - "HEAD /remote.php/webdav/IMG_20190630_191053%20(20).jpg HTTP/1.1" 302 RX:626 TX:1071 "-" "Mozilla/5.0 (Android) ownCloud-android/3.6.2"
Jul  2 10:11:30 my.host.name apache[24713]: my.hidden.host.name:443 37.47.58.8 - "HEAD /index.php/apps/files/ HTTP/1.1" 200 RX:599 TX:857 "-" "Mozilla/5.0 (Android) ownCloud-android/3.6.2"
Jul  2 10:11:31 my.host.name apache[24731]: my.hidden.host.name:443 37.47.58.8 - "HEAD /remote.php/webdav/IMG_20190630_191053%20(21).jpg HTTP/1.1" 302 RX:626 TX:1071 "-" "Mozilla/5.0 (Android) ownCloud-android/3.6.2"

`

**Comment by tobiasKaminsky** [comment]
@nextcloud/server-triage do you see any special/wrong in the configs?

We are checking with head on webdav if a file exists.
if yes, we append (2) and check it again, then with (3), etc.

**Comment by piknew** [comment]
I see only HEADs in my log. There is really no upload here. And... file does not exist, so return should be false.

It happens for me in two situations:

1. Auto upload - when I am using option "create subfolders" but subfolders do not exists. Eg. auto upload was working for 2019/06, but since July - not. I needed to create folder "07" manually and it started working again. I am not sure if it is the same problem or not (probably not). **I will register it separately if needed.** Could you please suggest if it is valid issue or duplicated already (I was searching issues but haven't found anything similar).

2. Manual upload. I select a file. Does not matter if by "share" from other application or by "+" in client. Nextcloud is starting upload in never-ending loop. In such a case file does not exists but it seems that "checking" is retuning logical true "it exists". I do not have knowledge which service is "checking":

This?: **HEAD /remote.php/webdav/IMG_20190630_191053%20(18).jpg HTTP/1.1** (ends with 302)
or
This?: **HEAD /index.php/apps/files/ HTTP/1.1**  (ends with 200)

**Comment by SR4ven** [comment]
Not fixed in 3.7.0
Still cannot upload anything and the notification of the stuck upload can only be removed by force stopping the app.

**Comment by SR4ven** [comment]
Issue is still present and sadly renders the app totally useless.
I haven't been able to upload a single file through the app for half a year now.

If additional information is needed, let us know.

**Comment by nursoda** [comment]
I also run my server in subdir config ("domain/cloud") and see no issues uploading. I use   `'overwrite.cli.url' => 'https://seyfarth.de/cloud',`
not redirect, though.

**Comment by tobiasKaminsky** [comment]
@SR4ven 
Can you create us a test account, test if the problem occurs also there and if so send the credentials to tobias at nextcloud dot com with a reference to this issue?

**Comment by SR4ven** [comment]
> 
> 
> @SR4ven
> Can you create us a test account, test if the problem occurs also there and if so send the credentials to tobias at nextcloud dot com with a reference to this issue?

Done.
Please notify me when the account can be deleted.

**Comment by tobiasKaminsky** [comment]
@SR4ven the problem seems that you have "location" as header which redirects to /cloud/apps/files/.

I think this is a problem in server conf, but I am not a expert.

curl --request HEAD \
  --url https://sr.asuscomm.com/cloud/remote.php/webdav/121233.jpg \
  -u  user:pass
 should return 404, but for you it returns 302, as it redirects as said above.

**Comment by SR4ven** [comment]
Thanks for the hint @tobiasKaminsky!
Now I need to find out where the location header comes from. I didn't set anything like that in the apache config, so I guess it has its origin somewhere in the Nextcloud config.
For the configuration, I followed the documentation [here](https://docs.nextcloud.com/server/16/admin_manual/installation/source_installation.html#pretty-urls).

I'll test some other options and report back later.

**Comment by SR4ven** [comment]
@tobiasKaminsky I've done some testing and traced the issue down to the "ErrorDocument", which does the redirecting for some reason.
https://github.com/nextcloud/server/blob/master/core/templates/404.php
Commenting out the ErrorDocument lines in `.htacces` results in https://sr.asuscomm.com/cloud/remote.php/webdav/121233.jpg returning 404, but with the standard Apache error page. However, in this state the login into the android app is no longer possible as it somehow seems to depend on this file redirecting to /apps/files/.

Does anyone know an explanation for this strange behaviour of 404.php, or even better, has a fix?

I have tested with and without any `redirect` or `overwrite` setting in the `config.php` without any change.

**Comment by SR4ven** [comment]
I finally managed to fix this problem.
It turns out that I had a global ProxyErrorOverride set in my Apache config, which was messing with the Nextcloud error handling.
After moving this option into the correct context everything works as expected.

Thanks for your help!
