### ISSUE TITLE
Error by uploading photos taken via WhatsApp (local file not found)

### ISSUE THREAD

**Issue by Wuppie007** [nextcloud/android#406]
First sorry for my terrible english

### Actual behaviour
- Take picture with Whatsapp
- Nextcloud app tries to upload (Direct Upload enabled)
- Cannot upload photo (local file not found)

### Expected behaviour
- Or upload photos taken via whatsapp or ignore them

Maybe other issue but if you are at the failed/succeeded upload list and press options (3 stripes). it tries again to upload.
 
### Steps to reproduce
1. 
2. 
3. 

### Environment data
Android version: 6.0.1

Device model: Nexus 5

Stock or customized system: Stock

Nextcloud app version: 1.4.0 RC2

Nextcloud server version: 10.0.1

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

**Comment by AndyScherzinger** [comment]
Hi @Wuppie007 thanks for reporting this issue. We will have to look into it, but this shouldn't happen. To be honest I never used the instant upload feature for anything else than the camera pictures (Android stock camera).

**Comment by Wuppie007** [comment]
Correct me if 'm wrong, but with 1.3 version of the app 'ignores' photos taken with WhatsApp (fine for me). But now with 1.4.0 RC2, the app tries to upload these pictures too.

**Comment by AndyScherzinger** [comment]
Hi @Wuppie007,

as far as I know 1.4.0 shouldn't be trying to upload photos which have been taken with WhatsApp's camera functionality. What do you think @tobiasKaminsky. On Android N you can now also specifiy the WhatsApp folder but in 1.4.0 that is a Android N only feature.

**Comment by tobiasKaminsky** [comment]
I have no Idea it. It seems as whatsapp would trigger a new picture broadcast.

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger the "skip deleted" is not for InstantUpload but for our new AutoUpload.

**Comment by AndyScherzinger** [comment]
ah, I see

But shouldn't we then have somethin in the Uploads view for this scenario? As is "restart failed" which should skip deleted files and simply remove them from the view (or am I confused/mistaken?!)

**Comment by mario** [comment]
This is fixed in master for sure.
