### ISSUE TITLE
error when entering full screen while streaming video

### ISSUE THREAD

**Issue by crustulumtheoneandonly** [nextcloud/android#4066]
Actual behaviour
When I start to stream a video everything works fine so far. But when I enter the fullscreeen there is a blackscreen and the playback stops. 

Expected behaviour
-the Video playbak should go on and the pause button should disappear to not block parts of the video
 
Steps to reproduce
1. uploading a streamable video file in your cloud
2. navigate to the file in the android app
3. click on it without downloading it (stream) 
4. rotate your phone (video should play back as normal)
5. tap on the screen to make the pause button disappear
6. notice the playback has stopped and there is a black screen

Environment data:

App Version: 3.6.2 RC1
Android version: 8.0.0
Oneplus 3
Oxygen-OS: 5.0.8

Nextcloud server version:
16

**Comment by ezaquarii** [comment]
I noticed that the play/pause button stops working during screen rotation. Togging play/pause has no effect on video playback, but the video plays as normal.

@crustulumtheoneandonly do you have a PIN lock enabled by any chance?
