### ISSUE TITLE
Sync downloads but doesnt keep in sync

### ISSUE THREAD

**Issue by derekblankmccoy** [nextcloud/android#4067]
### Actual behaviour
- changes in a "synced" folder dont happen

### Expected behaviour
- new, or changed files should download automatically
 
### Steps to reproduce
1. Sync a folder
2. Wait
3. Wait longer

### Environment data
Android version: 9.0

Device model: Galaxy S8

Nextcloud app version: 3.6

Nextcloud server version: 15.03

I thought changes were meant to "sync" every 15 minutes but this simply doesnt happen. "Sync" just acts like a manual download of that folder.

It would be great if Sync meant "keep in sync" and its behaviour could be modified in settings the same way an email client is. You could select every xx minutes. Another option for "only on Wi-Fi" and maybe another for "only while charging".

**Comment by szaimen** [comment]
I think that is related to #285 
For now you can probably press "synchronize" folder again to manually trigger the synchronization.

**Comment by mase76** [comment]
I can confirm this issue.
