### ISSUE TITLE
Version beta-20161125 is not available in F-Droid

### ISSUE THREAD

**Issue by Ventusfahrer** [nextcloud/android#407]
Is this by accident or  intended?

**Comment by tobiasKaminsky** [comment]
Nope, I think they have an hiccup.
F-Droid automatically searches for a new beta tag like beta-20161125 and builds the apk on their own.
So all we can do is to provide a correct tag.

I guess it will be working in the next days again.

**Comment by mr-bolle** [comment]
@Ventusfahrer please try again, now i get this Update

**Comment by AndyScherzinger** [comment]
Now it is available while I would still say wait for the next release to be published 29112016 (which again depends on the f-droid people to be published after tonight's build)
