### ISSUE TITLE
Cannot open third account

### ISSUE THREAD

**Issue by djermann** [nextcloud/android#4075]
### Actual behaviour
When adding 3 accounts from 3 different installations, it becomes impossible to open the third account. It always jumps back to the last opened account. With 3 accounts from the same Nextcloud installation it works.

### Expected behaviour
One should be able to open all 3 accounts.
 
### Steps to reproduce
1. Add 3 accounts from 3 different Nextcloud installations
2. Open one after another.

### Environment data
Android version:
9
Device model: 
Huawei mate 10 Pro
Stock or customized system:
Stock
Nextcloud app version:
3.6.1
Nextcloud server version:
16.0.1

**Comment by AndyScherzinger** [comment]
Hi @djermann can you please upgrade to 3.6.2 which should have a fix for changing between accounts.

Also please get back to us if the issue is still present for you.
