### ISSUE TITLE
ktlint does not offer any style configuration

### ISSUE THREAD

**Issue by ezaquarii** [nextcloud/android#4082]
### Actual behaviour
`ktlint` style checker is "opinionanted". Sad that it is opinionated against JetBrains defaults...

Just run ktlint over default JetBrains-formatted code and it will fail over empty newline at the end of file. IDE will automatically insert this line for you, making default kotlin development experience broken.

### Expected behaviour
I thought they should know better, TBH.

### Solution
Replace it with checkstyle?

**Comment by tobiasKaminsky** [comment]
https://github.com/pinterest/ktlint/issues/103

I'll add a PR later.


> Replace it with checkstyle?

Is this also valid for kotlin? And having all checks as ktlint?
I always understood (at least in java) that lint != checkstyle.j

**Comment by tobiasKaminsky** [comment]
Hm. 
Here we have a new line https://github.com/nextcloud/android/blob/3d7b14386a87b297af7e25a3891ed971781c6e62/src/main/java/com/nextcloud/client/device/DeviceModule.kt#L40
(tricky to see on Github, but if there would have been no new line you would see a red carriage return)

And ./gradlew ktlint is not failing for me.

**Comment by ezaquarii** [comment]
According to ktlint docs it should enforce standard Kotlin style, as vanilla as it comes form JetBrains. Let's see how it goes with #4078.
