### ISSUE TITLE
Crash when enterring server details

### ISSUE THREAD

**Issue by Pacersparko** [nextcloud/android#4083]
### Actual behaviour
App crashes

### Expected behaviour
App moves on to login screen
 
### Steps to reproduce
1. Enter address (it uses a non-standard port and a Nextcloud-generated unsigned certificate) 
2. Click Yes
3. Crash

### Environment data
Android version: 9

Device model: Oneplus 6

Stock or customized system: OmniROM, nano gapps

Nextcloud app version: 3.6.2 RC1 on beta channel or 20190524 on F-Droid

Nextcloud server version: 15.0.8.1

#### Web server error log

Nothing logged

#### Nextcloud log (data/nextcloud.log)

Couldn't find this file - I am using snap, let me know where to find it! 

![image](https://user-images.githubusercontent.com/50557782/58534035-7fc0ed00-822d-11e9-99d4-05226d0b252f.png)

**Comment by Pacersparko** [comment]
Resolved by installing gapps micro (where nano failed). There must be a Google dependency in the Nextcloud app. 
https://github.com/opengapps/opengapps/wiki/Package-Comparison

**Comment by AndyScherzinger** [comment]
cc @tobiasKaminsky for more information on this one (I don't know if there are Google dependencies in these builds).

**Comment by Pacersparko** [comment]
I was unable to retest it but I believe it was related to the OS-default browser being disabled/unavailable (Chromium in this instance, Chrome usually). At the time it crashes it is trying to open a webpage. Another app I use had a similar issue.
