### ISSUE TITLE
Upload error

### ISSUE THREAD

**Issue by Mati24** [nextcloud/android#409]
Hello
The app doesn't want to upload pictures : the server is unavailable. 
I can browse my files normally. 
Thanks 

### Environment data
Android version: 6

Device model: z3 compact 

Stock or customized system: custom

Nextcloud app version:last

Nextcloud server version:last

**Comment by AndyScherzinger** [comment]
Hi @Mati24 does this error still persist with the latest stable 1.4.0?

**Comment by Mati24** [comment]
Hello, yes I have Erreur inconnue (unknown error). Is there a way to see logs ? Thanks

**Comment by AndyScherzinger** [comment]
Unfortunately not (yet), the log of the client is only available in the beta release at the moment (https://f-droid.org/repository/browse/?fdfilter=Nextcloud&fdid=com.nextcloud.android.beta)

**Comment by Mati24** [comment]
It's ok now, but not always at the first try. Sometimes I find error on deleted pictures. 
Thanks
