### ISSUE TITLE
Delete file from source folder not working anymore

### ISSUE THREAD

**Issue by memen45** [nextcloud/android#4097]
### Actual behaviour
- just upload, source file remains

### Expected behaviour
- upload, followed by a delete of the source file
 
### Steps to reproduce
1. go to a folder, choose '+' and 'Upload files'
2. choose 'Upload option: Delete file from source folder'
3. tap 'Upload'

### Environment data
Android version: 9.0.13

Device model: OnePlus 6T

Stock or customized system: OxygenOS (Stock)

Nextcloud app version: 3.6.2

Nextcloud server version: 15.0.8

**Comment by memen45** [comment]
Can anyone reproduce/confirm this problem?

**Comment by memen45** [comment]
Nextcloud app version: 3.7.0
Nextcloud server version: 15.0.10

Bug still present.

**Comment by 0xbb** [comment]
Same for server version: 16.0.3

**Comment by gjanssens** [comment]
Is the source folder on an external SD card ?
Does it work for a source folder in internal storage ?

**Comment by memen45** [comment]
In my case it does not work on internal storage. Can't test with external storage, since I do not have an external sd card slot.

**Comment by tomasy** [comment]
Same for me. Not working in internal storage and no external storage

**Comment by AndyScherzinger** [comment]
@memen45 @tomasy #4287 might be the fix for your issue (can't really tell for sure) so maybre 3.8.0 (upcoming release) might fix this for you. You can also test this via the Dev releases (if you want to)

**Comment by tomasy** [comment]
I tested against developer version 20190803 and it works for me.
Thanks

**Comment by PhantomEight** [comment]
The fix in #4287 worked for me as well.   Couldn't upload files and have them get automatically deleted from my phone.  Not sure how others feel about it, but it's a pretty critical feature to me.  

Consider  case where you take lots of photos and what not, it's nice to be able to dump them manually or automatically to Nextcloud and have your phone clear out.

**Comment by gjanssens** [comment]
Ok, so this is a different issue from #2554 , will continue my issue there.

**Comment by memen45** [comment]
This is indeed working again in app version 3.8.0.

**Comment by Andy-EOS** [comment]
Not working in app version 3.22.1
