### ISSUE TITLE
how to change the package name of app

### ISSUE THREAD

**Issue by tofik313** [nextcloud/android#4109]

**Comment by ezaquarii** [comment]
Package name is set in `AndroidManifest.xml`. You'd need to change it and compile your own apk.

What are you trying to achieve? Custom braning for an organization comes to mind...

**Comment by tofik313** [comment]
> Package name is set in `AndroidManifest.xml`. You'd need to change it and compile your own apk.
> 
> What are you trying to achieve? Custom braning for an organization comes to mind...

yes you are right.
i already tried this but it gives error to all imports files

**Comment by tobiasKaminsky** [comment]
If you only want to install the app next to an existing one, it is sufficient to change applicationId in build.gradle.

Changing package name would require to also change all class files.

Please note that we also support branding for you (if you are a company)
https://nextcloud.com/pricing/ (scroll down to branding)
