### ISSUE TITLE
Removal failed

### ISSUE THREAD

**Issue by ncyclon** [nextcloud/android#411]
### Actual behaviour
- When I try to delete file in folder I've got message that "Removal failed" but file actually removed (I can't see it after refresh).
- In the same time **everything works normal** in last stable release in Google play and with ownCloud client.

### Expected behaviour
- Normal removal
 
### Steps to reproduce
Reproduce in any directory on my server.

### Environment data
Android version:
6.0.1

Device model: 
Samsung galaxy S6 edge

Stock or customized system:
stock

Nextcloud app version:
20161125

Nextcloud server version:
ownCloud 9.1.2 (stable)

#### Web server error log
nothing

#### Nextcloud log (data/nextcloud.log)
2016/11/29 09:57:56
FileActivity : show loading dialog

2016/11/29 09:57:56
OperationsService : Starting command with id 1

2016/11/29 09:57:56
SimpleFactoryManager : getClientFor(OwnCloudAccount ... : 

2016/11/29 09:57:56
OwnCloudClient #100 : Creating OwnCloudClient

2016/11/29 09:57:56
SimpleFactoryManager :     new client {user@my.domain.ru, 95001049}

2016/11/29 09:57:56
OwnCloudClient #100 : REQUEST DELETE /remote.php/webdav/Photos/Old/IMAG0037.jpg

2016/11/29 09:57:56
AdvancedSslSocketFactory : Creating SSL Socket with remote my.domain.ru:443, local null:0, params: org.apache.commons.httpclient.params.HttpConnectionParams@e8c9125

2016/11/29 09:57:56
AdvancedSslSocketFactory :  ... with connection timeout 5000 and socket timeout 30000

2016/11/29 09:57:56
ServerNameIndicator : SSLSocket implementation: com.android.org.conscrypt.OpenSSLSocketImpl

2016/11/29 09:57:56
ServerNameIndicator : SNI done, hostname: my.domain.ru

2016/11/29 09:57:57
RemoveRemoteFileOperation : Remove /Photos/Old/IMAG0037.jpg: Operation finished with HTTP status code 204 (success)

2016/11/29 09:57:57
FileContentProvider : Removing FILE 00016080oca4k8mvt8yx

2016/11/29 09:57:57
OperationsService : Called 1 listeners

2016/11/29 09:57:57
OperationsService : Stopping after command with id 1

2016/11/29 09:57:57
FileActivity : Received result of operation in FileActivity - common behaviour for all the FileActivities 

2016/11/29 09:57:57
FileActivity : dismiss loading dialog

**Comment by AndyScherzinger** [comment]
Hi @ncyclon,
thanks for the report and happy to hear the client works for your oC installation too. We are still trying to keep the Android app compatible with oC for features supported by both servers while still adding support for Nc only features.
The deletion issue is a bug though and we will look into it. Since we are working on finishing up 1.4.0 final it might still take some time until we can take a closer look though.

**Comment by cwmke** [comment]
I also have this bug using nextCloud 10.0.1 server with the F-Droid Beta 20161129 app.

**Comment by SlavikCA** [comment]
I have this issue, too.
Using NC app version 1.4.0 installed from Google Play
Android 7.1.1 on Nexus 6P
NextCloud 10.0.1 on Ubuntu 16.04 x64

**Comment by benbrummer** [comment]
+1
Nextcloud 10.0.1
Android 5.1
App 1.4.0

**Comment by haisma** [comment]
I have also this issue!
NextCloud 10.0.0.1
NextCloud Android Beta 20161123
Android 6.0 on OnePlus3

**Comment by ncyclon** [comment]
20161215 all the same

`2016/12/16 13:31:48
com.owncloud.android.files.InstantUploadBroadcastReceiver : Received: android.hardware.action.NEW_PICTURE

2016/12/16 13:31:48
com.owncloud.android.files.InstantUploadBroadcastReceiver : New photo received

2016/12/16 13:31:48
com.owncloud.android.files.InstantUploadBroadcastReceiver : Instant picture upload disabled, ignoring new picture

2016/12/16 13:31:48
com.owncloud.android.files.InstantUploadBroadcastReceiver : OFFICIAL processed: android.hardware.action.NEW_PICTURE`

**Comment by ncyclon** [comment]
20161215 same problem

**Comment by MCeddy** [comment]
same problem also if I remove files only locally in the android app

android app 1.4.0
nexcloud server 11.0.0 (stable)

**Comment by koarlmichael** [comment]
android app 1.4.0
nexcloud server 11.0.0

remove files locally not work, also "removal failed"

no messages in the server logfile

**Comment by Dulanic** [comment]
Same issue here.

**Comment by koreywithak** [comment]
I have the same issue. I should state that mine seems to be accompanied by the following (debug-level) error in my Nextcloud web-based admin log:
"CSRF check failed"

**Comment by AndyScherzinger** [comment]
A fix for this has been provided in the latest beta and us also part of 1.4.1 RC2

**Comment by koreywithak** [comment]
Any idea if the root of this issue was also the cause of the "CSRF check failed" logs I was getting?

**Comment by AndyScherzinger** [comment]
Hi @koreywithak as far as I can tell they shouldn't be related to the deletions. :(

**Comment by koreywithak** [comment]
I just tested the beta and everything looks good. For anyone out there with this issue who wants to test the beta version, I'd like to mention that a simple installation of the beta (even when clearing app cache/data) did not fix the issue. I had to uninstall the app completely before installing the beta from the Play Store to have it work. It was not obvious to me that this would be necessary.

**Comment by Dulanic** [comment]
I was able to just update and it worked.

**Comment by tobiasKaminsky** [comment]
@Dulanic great to hear -> solved

**Comment by MorrisJobke** [comment]
I also run into this and I can verify that 1.4.0 is broken and the 1.4.1 RC3 fixes this. 👍
