### ISSUE TITLE
Remove feedback link from app

### ISSUE THREAD

**Issue by albgus** [nextcloud/android#4112]
### Actual behaviour
When attempting to send feedback through the app, you'll get an immediate response

`Due to the high amount of mails we receive, please visit our forum (https://help.nextcloud.com/c/clients/android) for help or GitHub (https://github.com/nextcloud/android) if you encounter a bug or want to propose a feature.`

This makes is sound that all feedback sent through this channel is ignored, thus the button in the app is useless?

### Expected behaviour
- Feedback should be removed, or linked to a forum where feedback is actually accepted.
 
### Steps to reproduce
1. Open Nextcloud app
2.  Go to Settings, then press feedback
3.  Type out an email
4. Get told that feedback emails are not read and issues should be posted on Github

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky @ezaquarii @nextcloud/designers I agree with @albgus' assessment and would also vote to have it removed or replaced with a forum item.

**Comment by ezaquarii** [comment]
What would be the proper UX for this? Forum and GitHub are both for different target groups.

Forum has rather high friction, as you need to sign up, but would probably work for all.

GitHub has lower friction for people who... actually have GitHub account, which are developers, but it won't work for anybody else.

Maybe a pop-up with 2 buttons allowing user to choose?

**Comment by jancborchardt** [comment]
I would simply drop the "Feedback" entry in settings as we have the full "Participate" entry right in the sidebar which has a link to Github.

**Comment by tobiasKaminsky** [comment]
What about changing Participate to "Participate/Feedback" and duplicate forum on top of it:
![2019-06-05-104138](https://user-images.githubusercontent.com/5836855/58942684-8516be00-877e-11e9-841e-4347a39effc3.png)

"Get help on forum" ?

**Comment by ezaquarii** [comment]
For dev, it's github, as we can anticipate that the audience is mostly technical.
For prod - I guess that forum would be better choice.

**Comment by jancborchardt** [comment]
Let's maybe call it "Community"? This evokes both getting help and contributing.

And yeah, we can add the forum info at the top. That way the thing probably most people need is at the top. :)

**Comment by AndyScherzinger** [comment]
Still valid

**Comment by rajput2122** [comment]
Can i work on this?

**Comment by AndyScherzinger** [comment]
sure thing @rajput2122 and thanks for picking it up ❤️ 

There are actually 2 tasks within this issue that should be resolved:
1. remove the Feedback item from the settings screen
2. rename "Participate" to "Community" (toolbar title _and_ drawer menu item) and put the community info on to of the screen (`ParticipateActivity`)

**Comment by rajput2122** [comment]
Thanks sir

**Comment by AndyScherzinger** [comment]
My pleasure 👍 

If you need any help, have any question feel free to ask, @tobiasKaminsky @ezaquarii and I are here to help :)

**Comment by rajput2122** [comment]
Sir, I have done the removal of the feedback item. Can you please elaborate more about putting community info on to of the screen?

**Comment by AndyScherzinger** [comment]
@rajput2122 The `Participate` activity see https://github.com/nextcloud/android/issues/4112#issuecomment-498993851 offers the community information. The idea is to put the more community-centered information (forum, translations, etc.) at the top while it is now at the bottom of the screen (not visible in the screenshot!)

**Comment by rajput2122** [comment]
Ok sir ,So sorry for late

**Comment by rajput2122** [comment]
Actually sir i have little less knowledge about git commands when i had actually done all the work related to this issue and before pushing it to local repo i have done reset head due to which all the changes removed from my local disk.

**Comment by rajput2122** [comment]
i have done it again little work is yet to be done in community activity . I'll try to make PR today

**Comment by jancborchardt** [comment]
@rajput2122 no worries, mistakes happen. :) Thanks a lot for your contribution!

**Comment by AndyScherzinger** [comment]
Like @jancborchardt said no worries and also no pressure! Thanks again for tackling this issue ❤️

**Comment by rajput2122** [comment]
Sir i opened a pull request kindly review it
