### ISSUE TITLE
folders are only offered for Autoupload, if they are not empty

### ISSUE THREAD

**Issue by Ventusfahrer** [nextcloud/android#412]
### Actual behaviour
Camera folder was not offered for AutoUpload. Reason: Camera folder was empty. 

### Expected behaviour
It would be better if you could offer all 
 
### Steps to reproduce
1. Empty the Camera folder
2. try to configure AutoUpload for the Camera

### Environment data
Android version:
7.0

Device model: 
Nexus 9

Stock or customized system:
Stock

Nextcloud app version:
20161129-beta

Nextcloud server version:
10.0.1

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

**Comment by AndyScherzinger** [comment]
Hi @Ventusfahrer,

unfortunately we can't do that. The implementation is based on Android Media (scanner) capabilities. So when we query Android's media database there needs to be an indexed photo, else the query will return 0 results.
