### ISSUE TITLE
The notification can not be removed - 3.7.0 RC2

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/android#4126]
The push notification can not be removed from the bar.

![obraz](https://user-images.githubusercontent.com/47037905/59045734-ecb53200-8880-11e9-9df8-bb668ac0e801.png)

### Environment data
Android version: 6

Nextcloud app version: 3.7.0 RC2

Nextcloud server version: 16.0.1

**Comment by jookk** [comment]
Android 9 too

**Comment by tobiasKaminsky** [comment]
Thanks for testing RC2 and filing up this bug.
I also experienced this right now and will have a look.
