### ISSUE TITLE
Dagger tries to load NContentObserverJob on <5.0

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#4147]
```
java.lang.NoClassDefFoundError: com.owncloud.android.jobs.NContentObserverJob
        at com.nextcloud.client.di.DaggerAppComponent.getMapOfClassOfAndProviderOfAndroidInjectorFactoryOf(DaggerAppComponent.java:320)
        at com.nextcloud.client.di.DaggerAppComponent.getDispatchingAndroidInjectorOfActivity(DaggerAppComponent.java:323)
        at com.nextcloud.client.di.DaggerAppComponent.injectMainApp(DaggerAppComponent.java:714)
        at com.nextcloud.client.di.DaggerAppComponent.inject(DaggerAppComponent.java:710)
        at com.owncloud.android.MainApp.attachBaseContext(MainApp.java:185)
```

NContentObserverJob is >=Lollipop and such it is not compiled/accessible on <5.0.

@ezaquarii do you have an idea how to fix this?
Maybe we need two different ComponentsModule, depending on API?

This needs to be fixed before 3.7.0 can be released.

**Comment by tobiasKaminsky** [comment]
Maybe something like this?
https://stackoverflow.com/questions/34274795/dagger2-is-it-possible-to-inject-based-on-android-version

**Comment by ezaquarii** [comment]
As an immediate fix you can pull it out of DI and create it the old fashioned way. 

It is not a totally trivial as Dagger it compile-time generator and you don't want to generate a code that depends on unavailable classes, so any runtime differentiation needs a bit of thinking.

I think the safest bet would be to pull our of DI on this area for 3.7 - this should be trivial.

I'll take a look at it this evening.

Cheers,
Chris

**Comment by ezaquarii** [comment]
Yes, this boils down to having an interface that hides a platform specific implementation.

This is a way to go with our own code, but it could be a bit tricky for any existing platform-related that does not give much flexibility with subclassing/implementing interface. 

Android APIs are really badly designed, sadly.

I'll check it out this evening and get back to you.

Reverting di around this particular class could be a simplest solution for the time being until we roll out a correct fix for this issue.

Cheers,
Chris

**Comment by tobiasKaminsky** [comment]
Thanks for this great idea how to solve it.
I was somehow totally blocked and only tried to find a way how to solve it with DI.
I will release a RC4 with this fix at ~24.06., as I am on vacation next week.

**Comment by ezaquarii** [comment]
> I will release a RC4 with this fix at ~24.06., as I am on vacation next week.

Ok, in such case I can possibly supply a proper fix for this mergable when you get back.

**Comment by ezaquarii** [comment]
I think that optimal solution would be to migrate it to https://developer.android.com/reference/androidx/work/WorkManager

This official library abstracts away platform differences betwen API levels. We could probably also migrate evernote tasks too.

**Comment by ezaquarii** [comment]
Quick fix: https://github.com/nextcloud/android/pull/4171 - I removed dagger DI.

**Comment by AndyScherzinger** [comment]
PR exists

**Comment by ezaquarii** [comment]
This PR was meant to help push 3.7.0 out of the door only. I'm ok with merging it however, as it has minimal impact anyway.

In longer term I'd rather kill this `NContentObserverJob` and replace it with latest API that works on all levels.

**Comment by tobiasKaminsky** [comment]
> In longer term I'd rather kill this `NContentObserverJob` and replace it with latest `WorkManager` that works on all android api levels.

That is a good way to go.
So we close this and https://github.com/nextcloud/android/issues/3147 is about to switch to WorkManager, so we do not forget it.
