### ISSUE TITLE
Android client would not download files due to installing with wrong download path setting from Google

### ISSUE THREAD

**Issue by BorisRabit** [nextcloud/android#4151]
When changing to a new Android phone, the system installs app data backed up from a previous phone without being clear what it is doing. After installing Nextcloud app on new phone, when trying to select a file to download, the download would fail without explanation. Uninstalling and reinstalling do not fix the problem.

Checking the storage path in settings shows a path identical to the one used on the previous phone (Galaxy s7), a path that does not exist on the new phone (a basic Nokia). Manually selecting one of the storage path options fixes this.

### Actual behavior

When downloaded from Google Play Store, app can include defaults from a previous phone that set a non-existent download location

### Expected behavior

A new installation should default to a working default storage directory regardless of a user accidentally having Play Store try to restore backed up app data

### Steps to reproduce

- Use Nextcloud app on a Samsung phone
- On the same Google account, install Nextcloud on a new non-Samsung phone

### Environment data

- Samsung Galaxy s7 with Android 8.0.0
- Nokia 6.1 with Android 9
- Nextcloud Android App version 3.6.2 on both phones

**Comment by tobiasKaminsky** [comment]
Hard to reproduce without Google ;-)
A fix would be that our app should check if storage path is available on startup, and if not 
- notify user
- change it silently to a default path
- …?
