### ISSUE TITLE
Zip unzip of files and folders

### ISSUE THREAD

**Issue by maxlinux2000** [nextcloud/android#4152]
### Is your feature request related to a problem? Please describe.

It would be very useful to be able to compress folders and decompress .zip files directly from the browser.

### Describe the solution you'd like
I'm sorry, but gdrive has this function and it would be nice if nextcloud has it too

**Comment by AndyScherzinger** [comment]
@nextcloud/server-triage this seems to be a rather server/webUI related request, right? :)

**Comment by maxlinux2000** [comment]
well ... it's good that you could compress / decompress and upload entire folders, from the web with firefox/chromium, and also from the android app

**Comment by blizzz** [comment]
There's https://apps.nextcloud.com/apps/extract

**Comment by nickvergessen** [comment]
Yes, there is this extract app which just had a security issue.

I don't think we want to put that into the default product and therefor also into the mobile clients, so I'm closing this.

**Comment by goldengel** [comment]
In case of timeouts (to many files in folder) and backup issue, I would ask if I can vote somewhere for a "Nextcloud zip folder" function.
