### ISSUE TITLE
Android back button accessed via Photos in left slide menu exits app

### ISSUE THREAD

**Issue by ben423423n32j14e** [nextcloud/android#4159]
### Actual behaviour
- Pressing Android back button while in Photos accessed from the left slide menu exits the app

### Expected behaviour
- Should return to the previous screen in NextCloud
 
### Steps to reproduce
1. Open App
2. Select Photos from the left slide menu
3. Press Android back button down the bottom of the screen

### Environment data
Android version: 9

Device model: Galaxy S9

Nextcloud app version: 3.6.2

Nextcloud server version: 16.0.1

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky any idea how to fix this? I am not an expert on the event bus stuff :/

**Comment by tobiasKaminsky** [comment]
Is this really something we want to fix?
In my opinion it is same like "on device" or "shared". 
This are just other views of "files" and thus if you click on "back" the app is closed.

**Comment by AndyScherzinger** [comment]
Don't know, maybe @jancborchardt has some feedback. While it is a filter (technically speaking) it is an explicit navigation via the main navigation mechanism so from a user perspective I'd expect the app to behave the same way in all the situations no matter the technical background of the implementation.

**Comment by tobiasKaminsky** [comment]
>  I'd expect the app to behave the same way in all the situations no matter the technical background of the implementation.

So what is your expected behaviour upon back button pressed? :thinking:

**Comment by AndyScherzinger** [comment]
> So what is your expected behaviour upon back button pressed? 🤔

Easy, like described in th eoriginal issue description:

> Should return to the previous screen in NextCloud

basically "respect" the back stack

**Comment by tobiasKaminsky** [comment]
As this is just another view of files on server, there is no previous screen.
Or, in other terms: it could be anything, e.g.
- settings -> photos -> back
- files -> on device -> photos -> back

So unless we store the entire history, I would go either with
- photos -> back -> files (as it is default)
- photos -> back -> closes app (as it is now)

**Comment by AndyScherzinger** [comment]
> As this is just another view of files on server, there is no previous screen.

Of course there is, just try the following:

open app -> auto upload -> photos -> back -> closes the app 

And this behavior is just wrong since respecting the back stack it would nee to show auto upload again.
This works fine for other screens, see

open app -> auto upload -> uploads -> back -> back

**Comment by tobiasKaminsky** [comment]
Ah, yes.
But this is because these are different activities. And activities are stored in Androids' stack.

For
> open app -> auto upload -> photos -> back -> closes the app

Photos is FDA/OCFileList and thus if you close it you close the app.
(We have a check like "if you are in FDA and click back, first close drawer if open, else close app").

**Comment by AndyScherzinger** [comment]
> Photos is FDA/OCFileList and thus if you close it you close the app.

Erm, nope. Photos _always_ closes the app. Sp if I opened Auto upload before opening Photos why shoudln't I get back to Auto Upload (which is an activity and should be on the stack?). This isn't the "all files"->"photos" scenario (which is the same, single Activity).
