### ISSUE TITLE
missing setting on Xiaomi Redmi 4 Prime

### ISSUE THREAD

**Issue by PerthTotty** [nextcloud/android#4160]
### Actual behaviour
On my device "Xiaomi Redmi 4 Prime" there is no setting "disable notifications for new image folders" (I'm not sure what's the exact translation in english).
On my device "Samsung S9plus" there is a slider to decide if I want to be notified ...

### Expected behaviour
Having this setting on my Xiaomi Smartphone would be nice. (It always notifies by default)
 
### Steps to reproduce
1. Open settings

### Environment data
Android version:
Pie (9.0)

Device model: 
Xiaomi Redmi 4 Prime (markw)

Stock or customized system:
DotOS 3.0

Nextcloud app version:
3.6.2

Nextcloud server version:
don't know exactly (but quite actual)

Many thanks in advance!

**Comment by PerthTotty** [comment]
Really no one else, who has this problem ... ?

**Comment by AndyScherzinger** [comment]
So the notifications on xiaomi don't have any possibilities to be expanded?

**Comment by tobiasKaminsky** [comment]
Can you show us a screenshot of it?
It should be sufficient to slide a bit down on notification to open up action?

**Comment by PerthTotty** [comment]
![Screenshot_20190717-152501_Nextcloud](https://user-images.githubusercontent.com/40835272/61379562-11e98700-a8a8-11e9-9b3e-2412ac1c6f7c.png)

No, the problem is that there is no setting "disable notifications for new image folders". (see screenshot)
My Samsung shows this between "Show hidden files" and "Sync calendar & contacts)

**Comment by AndyScherzinger** [comment]
The item you mention in the settings iys only shown _after_ you disabled such notifications via the notification itself, which is why we asked for a screenshot of the notification itself, _not_ the settings screen.

Could you post the notification itself, unfortunately none of us has access to a xiaomi device which is why we can't reproduce this ourselfs.

**Comment by PerthTotty** [comment]
Ah, sorry - I didn't get that ...

After disabling the Notifications for Nextcloud I still haven't got the setting option.

Here's the screenshot of the notifications (before I disabled notifications)
![Screenshot_20190717-183350_Nextcloud](https://user-images.githubusercontent.com/40835272/61393976-6c8fdc80-a8c2-11e9-832b-defd9c9ac5b1.png)

**Comment by AndyScherzinger** [comment]
So if you swipe down on one of these notifications it should show the ignore button, you might have better luck when swiping away all but one of these notifications first.
