### ISSUE TITLE
Unwanted notification "Sending files"

### ISSUE THREAD

**Issue by ldmpub** [nextcloud/android#4170]
### Actual behaviour
- Unwanted notification

### Steps to reproduce
1. Start smartphone with Nextcloud installed
2. After some time, Nextcloud displays a notification "Sending files"

Note: this behaviour occurs since 2 or 3 weeks even if I have not change any preferences on my side.

![Send files](https://user-images.githubusercontent.com/1452146/59982243-6a15cc00-960f-11e9-8910-bb60fbf4da51.jpg)

### Environment data
Android version: 8.0.0

Device model: Samsung Galaxy S7

Stock or customized system:
Stock ROM

Nextcloud app version:
3.7.0 RC3

Bonus question: what means at then end of 1st line 9:21, it looks like a time but what time?
[EDIT] Answer: it's just the time of the notification raised

**Comment by DaleBCooper** [comment]
Can confirm this.
Going back to 3.6.2 temporarily fixes it.

**Comment by ldmpub** [comment]
@DaleBCooper thanks for your confirmation ;-).

In addition: clicking on this notification does not open any part of the app for more details (for instance what files are currently trying to being sent).

**Comment by ldmpub** [comment]
Hi,

Any news about this annoying notification bug?
Shoud I downgrade my Android apps like suggested above?

**Comment by ldmpub** [comment]
Hi,

This bug is still there and annoying. Is there any plan to fix this ?

**Comment by FelixBuehler** [comment]
Bug is still present. I assume it might be the daily backup of the contacts, since it appears every day again, no matter if I open the app on that day or not. Can anyone confirm?

**Comment by ldmpub** [comment]
I confirm this unwanted notif still occurs and is not linked to automatic contacts backups because they are disabled in my app...

**Comment by ldmpub** [comment]
Hi, it looks like this pb is gone after update to 3.8.0 RC (currently I have no more ennoying notifications with 3.8.0 RC2).

Is it ok for other users?

**Comment by FelixBuehler** [comment]
Can confirm for the newest version, that the bug is gone.

**Comment by ldmpub** [comment]
Thanks for your confirmation feedback => issue closed.
