### ISSUE TITLE
Nextcloud 3.7 beta (f-droid) does not show files from old server

### ISSUE THREAD

**Issue by beerse** [nextcloud/android#4176]
### Actual behaviour
- Tell us what happens
Just installed nextcloud from f-droid (3.7, beta 4) and connected it to my stackstorage.com folder.
The app reported it is an old server (it is: TransIP has their own spin-of from owncloud)
After a longer wait, no files show up in the all files section (dutch: "Alle Bestanden").
Mean while it crashed a couple of times.

### Expected behaviour
- Tell us what should happen
Removed 3.7beta4 from f-droid. Installed the current (3.6.x) from play-store an dconnected it to my stackstorage.com folder.
The app reported it is an old server (it is).
The "Alle Bestanden" (all files?) show up direct, without any issue.
 
### Steps to reproduce
1. install 3.7 beta from f-droid
2. connect to a stackstorage.com webdav share
3. accept it is an old server.

### Environment data
Android version:
Lineage-OS

Device model: 
Samsung Tab 2

Stock or customized system:
Lineage-os with google play-store and f-droid.

Nextcloud app version:
bug: 3.7 beta (today's f-droid)
working: 3.6.2 (today's play-store)

Nextcloud server version:
unknown, out of control: stackstorage.com from trans-ip (https://www.transip.nl/)

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
Without knowing the exact version of the server, I can only say that the app is only supporting the last 4 mayor releases of Nextcloud server.
So the app is expected to fail for any older or other version. So you would need to use an older version of the client app. 

Cc @tobiasKaminsky

**Comment by beerse** [comment]
It sounds reasonably to match client and server and keep that as the base.

But what is left from the statement that standard-protocols are used in the communication?
If there is some issue between 2 parties that both state to follow the same standaard (here: webdav for file transfer) and it has worked in the past then it is worth to look at the reason (details in the protocol) where it fails.

Hence, please reconsidder the issue or clearly state you donnot follow the standard anymore.

**Comment by AndyScherzinger** [comment]
cc @tobiasKaminsky for feedback/opinion

@beerse we use webDAV _and_ Nextclouds ReST API. The app is a Nextcloud client _not_ a generic webDAV-client

**Comment by tobiasKaminsky** [comment]
We do follow the standard as closely as needed/possible.
For file listing problems I suspect that we query for a custom property which the other server does not understand.

**Comment by beerse** [comment]
Then I've been mis-informed. I had the impression the nextcloud on both server and client where using webdav. I expect if they find each-other and matching version numbers they can switch over to their own api-s. However, both could do pure webdav (with its limitations) if needed.

**Comment by tobiasKaminsky** [comment]
For file listing we do use webdav.
For sharing info we do use our own nextcloud specific ocs query.

listing pure files like with a dav browser is not enough for our app (as you want to share, have preview, etc.).
