### ISSUE TITLE
Auto Upload item is missing in sidebar

### ISSUE THREAD

**Issue by strugee** [nextcloud/android#418]
As mentioned in https://github.com/nextcloud/android/issues/398#issuecomment-263036902: the "Auto Upload" item in the sidebar seems to be missing. I can reproduce this in beta 20161123 and beta 20161125.

App is installed from F-Droid. I'm on CyanogenMod 13, Android 6.0.1, Nexus 6P. Happy to provide more debugging upon request, but I'm assuming this is just a problem with the beta branch or something :)

**Comment by tobiasKaminsky** [comment]
Please try it again with the latest beta 20161129.
I tried it and "auto upload" is back again, for me.

**Comment by AndyScherzinger** [comment]
correct, this has been fixed with ...29

**Comment by strugee** [comment]
Whoops, sorry! Apparently my repositories were out of date when I upgraded to the "latest" last night.

Can confirm that this is fixed :thumbsup:
