### ISSUE TITLE
Cannot create new office od* file with template

### ISSUE THREAD

**Issue by ralfi** [nextcloud/android#4183]
### Actual behaviour
Creating *new* LOOL file with empty template do not work
Open existing files works.

### Expected behaviour
New empty LOOL file should be created
 
### Steps to reproduce
1. tap +, use create new dokument
2. entry new filename
3. tap on "empty" template symbol
4. nothing happens, only rotate circle symbol
5. tap back, file seems to be created with zero bytes
6. tap on the file to try it open
7. lool tells the read the doc failed from storage, please contact administrator

### Environment data
Android version: 9.0

Device model: Samsung GS9
Stock or customized system: Samsung Android

Nextcloud app version: 3.6.2, latest DEV from 27062019
Nextcloud server version: docker nextcloud:latest image download from 20190626

**Comment by ralfi** [comment]
JAVA related Logfile Entries (via adb)

06-27 11:31:36.539  4868  5043 I InputReader: Touch event's action is 0x1 (deviceType=0) [pCnt=1, s=] when=10313.204840
06-27 11:31:36.539  4868  5042 I clp-JNI : CLP add process info start. (channel) c495c75 com.nextcloud.android.beta/com.owncloud.android.ui.activity.FileDisplayActivity (server) (pkg) AppWindowToken{44653d2 token=Token{9ea7e5d ActivityRecord{f2fe034 u0 com.nextcloud.android.beta/com.owncloud.android.ui.activity.FileDisplayActivity t13454}}} (action) 1
06-27 11:31:36.539  4868  5042 I clp-JNI : CLP add process info end.
06-27 11:31:36.539  4868  5042 I InputDispatcher: Delivering touch to (19749): action: 0x1, displayId: 0, 'c495c75', toolType: 1
06-27 11:31:36.540 19749 19749 D ViewRootImpl@fe546e7[FileDisplayActivity]: ViewPostIme pointer 1
06-27 11:31:36.562  4868  6213 E Parcel  : Class not found when unmarshalling: com.owncloud.android.datamodel.OCFile
06-27 11:31:36.562  4868  6213 E Parcel  : java.lang.ClassNotFoundException: com.owncloud.android.datamodel.OCFile
06-27 11:31:36.562  4868  6213 E Parcel  : 	at java.lang.Class.classForName(Native Method)
06-27 11:31:36.562  4868  6213 E Parcel  : 	at java.lang.Class.forName(Class.java:453)
06-27 11:31:36.562  4868  6213 E Parcel  : 	at android.os.Parcel.readParcelableCreator(Parcel.java:2827)
06-27 11:31:36.562  4868  6213 E Parcel  : 	at android.os.Parcel.readParcelable(Parcel.java:2781)
06-27 11:31:36.562  4868  6213 E Parcel  : 	at android.os.Parcel.readValue(Parcel.java:2684)
06-27 11:31:36.562  4868  6213 E Parcel  : 	at android.os.Parcel.readArrayMapInternal(Parcel.java:3053)
06-27 11:31:36.562  4868  6213 E Parcel  : 	at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:288)
06-27 11:31:36.562  4868  6213 E Parcel  : 	at android.os.BaseBundle.unparcel(BaseBundle.java:232)
06-27 11:31:36.562  4868  6213 E Parcel  : 	at android.os.BaseBundle.getString(BaseBundle.java:1155)
06-27 11:31:36.562  4868  6213 E Parcel  : 	at android.content.Intent.getStringExtra(Intent.java:8111)
06-27 11:31:36.562  4868  6213 E Parcel  : 	at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:721)
06-27 11:31:36.562  4868  6213 E Parcel  : 	at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:659)
06-27 11:31:36.562  4868  6213 E Parcel  : 	at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:1503)
06-27 11:31:36.562  4868  6213 E Parcel  : 	at com.android.server.am.ActivityStarter.execute(ActivityStarter.java:601)
06-27 11:31:36.562  4868  6213 E Parcel  : 	at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:6565)
06-27 11:31:36.562  4868  6213 E Parcel  : 	at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:6439)
06-27 11:31:36.562  4868  6213 E Parcel  : 	at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:6430)
06-27 11:31:36.562  4868  6213 E Parcel  : 	at android.app.IActivityManager$Stub.onTransact$startActivity$(IActivityManager.java:10814)
06-27 11:31:36.562  4868  6213 E Parcel  : 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:111)
06-27 11:31:36.562  4868  6213 E Parcel  : 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:4126)
06-27 11:31:36.562  4868  6213 E Parcel  : 	at android.os.Binder.execTransact(Binder.java:739)
06-27 11:31:36.562  4868  6213 E Parcel  : Caused by: java.lang.ClassNotFoundException: com.owncloud.android.datamodel.OCFile
06-27 11:31:36.562  4868  6213 E Parcel  : 	at java.lang.Class.classForName(Native Method)
06-27 11:31:36.562  4868  6213 E Parcel  : 	at java.lang.BootClassLoader.findClass(ClassLoader.java:1346)
06-27 11:31:36.562  4868  6213 E Parcel  : 	at java.lang.BootClassLoader.loadClass(ClassLoader.java:1406)
06-27 11:31:36.562  4868  6213 E Parcel  : 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
06-27 11:31:36.562  4868  6213 E Parcel  : 	... 21 more
06-27 11:31:36.562  4868  6213 E Parcel  : Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
06-27 11:31:36.563  4868  6213 W Bundle  : Failed to parse Bundle, but defusing quietly
06-27 11:31:36.563  4868  6213 W Bundle  : android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.owncloud.android.datamodel.OCFile
06-27 11:31:36.563  4868  6213 W Bundle  : 	at android.os.Parcel.readParcelableCreator(Parcel.java:2855)
06-27 11:31:36.563  4868  6213 W Bundle  : 	at android.os.Parcel.readParcelable(Parcel.java:2781)
06-27 11:31:36.563  4868  6213 W Bundle  : 	at android.os.Parcel.readValue(Parcel.java:2684)
06-27 11:31:36.563  4868  6213 W Bundle  : 	at android.os.Parcel.readArrayMapInternal(Parcel.java:3053)
06-27 11:31:36.563  4868  6213 W Bundle  : 	at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:288)
06-27 11:31:36.563  4868  6213 W Bundle  : 	at android.os.BaseBundle.unparcel(BaseBundle.java:232)
06-27 11:31:36.563  4868  6213 W Bundle  : 	at android.os.BaseBundle.getString(BaseBundle.java:1155)
06-27 11:31:36.563  4868  6213 W Bundle  : 	at android.content.Intent.getStringExtra(Intent.java:8111)
06-27 11:31:36.563  4868  6213 W Bundle  : 	at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:721)
06-27 11:31:36.563  4868  6213 W Bundle  : 	at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:659)
06-27 11:31:36.563  4868  6213 W Bundle  : 	at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:1503)
06-27 11:31:36.563  4868  6213 W Bundle  : 	at com.android.server.am.ActivityStarter.execute(ActivityStarter.java:601)
06-27 11:31:36.563  4868  6213 W Bundle  : 	at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:6565)
06-27 11:31:36.563  4868  6213 W Bundle  : 	at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:6439)
06-27 11:31:36.563  4868  6213 W Bundle  : 	at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:6430)
06-27 11:31:36.563  4868  6213 W Bundle  : 	at android.app.IActivityManager$Stub.onTransact$startActivity$(IActivityManager.java:10814)
06-27 11:31:36.563  4868  6213 W Bundle  : 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:111)
06-27 11:31:36.563  4868  6213 W Bundle  : 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:4126)
06-27 11:31:36.563  4868  6213 W Bundle  : 	at android.os.Binder.execTransact(Binder.java:739)
06-27 11:31:36.565  4868  6213 I ActivityManager: START u0 {act=null typ=null flg=0x0 cmp=ComponentInfo{com.nextcloud.android.beta/com.owncloud.android.ui.activity.RichDocumentsWebView}} from uid 10091
06-27 11:31:36.566  4868  6213 D CustomFrequencyManagerService: acquireDVFSLockLocked : type : DVFS_MIN_LIMIT  frequency : 1794000  uid : 1000  pid : 4868  pkgName : AMS_ACT_START@CPU_MIN@55
06-27 11:31:36.569  4868  6213 D ActivityManagerPerformance: AMP_acquire() ACT_START
06-27 11:31:36.571  4317  4317 I SurfaceFlinger: id=2401 createSurf (5920x5920),2 flag=4, AppWindowToken{1d84d37 token=Token{46e9a36 ActivityRecord{8b00fd1 u0 com.nextcloud.android.beta/com.owncloud.android.ui.activity.RichDocumentsWebView t13454}}}#0
06-27 11:31:36.575 19749 19749 V FileDisplayActivity: onPause() start
06-27 11:31:36.576 19749 19749 D FileDisplayActivity: onPause() ending
06-27 11:31:36.576 19749 19749 D OCFileListAdapter: cancel: abort get method directly
06-27 11:31:36.576 19749 19749 V FileDisplayActivity: onPause() end

06-27 11:31:41.271 19749 19749 D InputMethodManager: prepareNavigationBarInfo() DecorView@bae2e5d[RichDocumentsWebView]
06-27 11:31:41.271 19749 19749 D InputMethodManager: getNavigationBarColor() -855310
06-27 11:31:41.287 19749 19749 E ThemeUtils: setTextViewCursorColor
06-27 11:31:41.287 19749 19749 E ThemeUtils: java.lang.NoSuchFieldException: No field mCursorDrawable in class Landroid/widget/Editor; (declaration of 'android.widget.Editor' appears in /system/framework/framework.jar!classes3.dex)
06-27 11:31:41.287 19749 19749 E ThemeUtils: 	at java.lang.Class.getDeclaredField(Native Method)
06-27 11:31:41.287 19749 19749 E ThemeUtils: 	at com.owncloud.android.utils.ThemeUtils.setTextViewCursorColor(ThemeUtils.java:585)
06-27 11:31:41.287 19749 19749 E ThemeUtils: 	at com.owncloud.android.utils.ThemeUtils.themeEditText(ThemeUtils.java:462)
06-27 11:31:41.287 19749 19749 E ThemeUtils: 	at com.owncloud.android.utils.ThemeUtils.themeSearchView(ThemeUtils.java:470)
06-27 11:31:41.287 19749 19749 E ThemeUtils: 	at com.owncloud.android.ui.fragment.ExtendedListFragment.onCreateOptionsMenu(ExtendedListFragment.java:196)
06-27 11:31:41.287 19749 19749 E ThemeUtils: 	at androidx.fragment.app.Fragment.performCreateOptionsMenu(Fragment.java:2561)
06-27 11:31:41.287 19749 19749 E ThemeUtils: 	at androidx.fragment.app.FragmentManagerImpl.dispatchCreateOptionsMenu(FragmentManager.java:3321)
06-27 11:31:41.287 19749 19749 E ThemeUtils: 	at androidx.fragment.app.FragmentController.dispatchCreateOptionsMenu(FragmentController.java:331)
06-27 11:31:41.287 19749 19749 E ThemeUtils: 	at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:379)
06-27 11:31:41.287 19749 19749 E ThemeUtils: 	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
06-27 11:31:41.287 19749 19749 E ThemeUtils: 	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:2549)
06-27 11:31:41.287 19749 19749 E ThemeUtils: 	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
06-27 11:31:41.287 19749 19749 E ThemeUtils: 	at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:455)
06-27 11:31:41.287 19749 19749 E ThemeUtils: 	at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:56)
06-27 11:31:41.287 19749 19749 E ThemeUtils: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
06-27 11:31:41.287 19749 19749 E ThemeUtils: 	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
06-27 11:31:41.287 19749 19749 E ThemeUtils: 	at android.view.Choreographer.doFrame(Choreographer.java:693)
06-27 11:31:41.287 19749 19749 E ThemeUtils: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
06-27 11:31:41.287 19749 19749 E ThemeUtils: 	at android.os.Handler.handleCallback(Handler.java:873)
06-27 11:31:41.287 19749 19749 E ThemeUtils: 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-27 11:31:41.287 19749 19749 E ThemeUtils: 	at android.os.Looper.loop(Looper.java:214)
06-27 11:31:41.287 19749 19749 E ThemeUtils: 	at android.app.ActivityThread.main(ActivityThread.java:6986)
06-27 11:31:41.287 19749 19749 E ThemeUtils: 	at java.lang.reflect.Method.invoke(Native Method)
06-27 11:31:41.287 19749 19749 E ThemeUtils: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
06-27 11:31:41.287 19749 19749 E ThemeUtils: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
06-27 11:31:41.304  4868  6213 V WindowManager: Relayout Window{c495c75 u0 com.nextcloud.android.beta/com.owncloud.android.ui.activity.FileDisplayActivity}: viewVisibility=0 req=1080x2220 {(0,0)(fillxfill) sim={adjust=resize} ty=BASE_APPLICATION wanim=0x10302fe
06-27 11:31:41.304  4868  6213 V WindowManager:   fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
06-27 11:31:41.304  4868  6213 V WindowManager:   pfl=FORCE_DRAW_STATUS_BAR_BACKGROUND  remains{ 0x1000000 }
06-27 11:31:41.304  4868  6213 V WindowManager:   vsysui=LAYOUT_STABLE LAYOUT_FULLSCREEN LIGHT_NAVIGATION_BAR naviIconColor=0}
06-27 11:31:41.306  4317  4317 I SurfaceFlinger: id=2408 createSurf (1080x2220),1 flag=404, com.nextcloud.android.beta/com.owncloud.android.ui.activity.FileDisplayActivity[19749]#0
06-27 11:31:41.307  4868  6213 D StatusBarManagerService: notifyRequestedSystemKey recent=false home=false
06-27 11:31:41.307  5175  5175 D Navbar.SecNavigationBarView: notifyRequestedSystemKey requested = 0
06-27 11:31:41.307  5175  5175 D Navbar.ImmersiveController: handleEvent - VISIBLE, REQUESTED_SYSTEM_KEY_CHANGED
06-27 11:31:41.307  4868  4913 D WindowManager: setSystemUiVisibility: vis= 0x8518, fullscreenVis= 0x0, dockedVis= 0x0, win=Window{c495c75 u0 com.nextcloud.android.beta/com.owncloud.android.ui.activity.FileDisplayActivity}

**Comment by ralfi** [comment]
can confirm anyone?

**Comment by ralfi** [comment]
and ... create file with browser the same way works

**Comment by ralfi** [comment]
Same with 3.7.0 RC4, mmmmh

**Comment by tobiasKaminsky** [comment]
I tested it with latest Dev and oneplus3 on my system and it works.

I guess that somehow on dour system/collabora the new file could not be created and thus the file is 0k.

Is there something relevant on nextcloud.log?

**Comment by ralfi** [comment]
Hi Tobias, i will setup the log level to debug and reply asap. 

Today i play a little bit with the template directory setting (i use some templates from my libreoffice desktop install and upload them with the web interface) and now creating a file from one of these named template works, but i am not able to save the new created document; whether with the save nor with the save as menu.

But you could be right because i am using a configuration with two apache reverse proxies, nextcloud and lool as docker images and custom volumes... I will come back with more information asap.

Thanks!

**Comment by ralfi** [comment]
[loolwsd.log](https://github.com/nextcloud/android/files/3362686/loolwsd.log)

Hi Tobias, Log as attachment.

There are only two entries with ERR and the first section as you can see is from the crashed try, the last entries are from the normal web access. IMHO i think that is a lool problem, also there are no relevant entires in the nextcloud.log with loglevel 3. Do you have a hint where i can leave this issue at the most helpfull point here?

**Comment by ralfi** [comment]
same device works with Browser, not with NC/Android 3.7 rc4. It could be relevant thgat recognising the empty template or the entries in the template path tooks a while vor works with the second try.

**Comment by ralfi** [comment]
Also the same behavior with different screen Keyboards

**Comment by tobiasKaminsky** [comment]
@juliushaertl (for RichDocuments)
@thebearon @timar for Collabora

Do you have an idea what is wrong here?

**Comment by juliushaertl** [comment]
ERR messages extracted from the log:
```
wsd-00029-01276 2019-07-05 11:42:59.277315 [ docbroker_047 ] INF  ToClient-0079: Command: unocommandresult: {
    "commandName": ".uno:Save",
    "success": "false",
    "result": {
        "type": "void"
    }
}
| wsd/ClientSession.cpp:705
wsd-00029-01276 2019-07-05 11:42:59.277398 [ docbroker_047 ] ERR  Cannot save docKey [/index.php/apps/richdocuments/wopi/files/507120_oceqwn99mkb6], the .uno:Save has failed in LOK.| wsd/DocumentBroker.cpp:850
wsd-00029-01276 2019-07-05 11:42:59.277482 [ docbroker_047 ] INF  ~ClientSession dtor [ToClient-0079], current number of connections: 0| wsd/ClientSession.cpp:64
wsd-00029-01276 2019-07-05 11:42:59.277524 [ docbroker_047 ] INF  Terminating dead DocumentBroker for docKey [/index.php/apps/richdocuments/wopi/files/507120_oceqwn99mkb6].| wsd/DocumentBroker.cpp:361
wsd-00029-01276 2019-07-05 11:42:59.277554 [ docbroker_047 ] INF  Finished polling doc [/index.php/apps/richdocuments/wopi/files/507120_oceqwn99mkb6]. stop: true, continuePolling: true, ShutdownRequestFlag: false, TerminationFlag: false, closeReason: dead. Flushing socket.| wsd/DocumentBroker.cpp:368
wsd-00029-01276 2019-07-05 11:42:59.277770 [ docbroker_047 ] ERR  DocumentBroker stopping although modified  Broker: Modern.ott pid: 1261 *** Marked to destroy ***
  loaded in: 1384ms
  sent: 0
  recv: 0
  modified?: 1
  jail id: CqOuVRMsCB80H0TT
  filename: Modern.ott
  public uri: https://REPLACED-FQDN/index.php/apps/richdocuments/wopi/files/507120_oceqwn99mkb6?access_token=0Nw6yRaUB5em7C6t01QZszrM6AWS4Bp6&access_token_ttl=0
  jailed uri: file:///user/docs/CqOuVRMsCB80H0TT/Modern.ott
  doc key: /index.php/apps/richdocuments/wopi/files/507120_oceqwn99mkb6
  doc id: 047
  num sessions: 0
  last saved: Fri Jul  5 11:42:02 2019
```

Are you using the latest richdocuments version?

**Comment by ralfi** [comment]
Hi Julius,
I am using richdocuments 3.3.12; nc 16.0.1.1 docker Image. But app:check-code richdocuments shows me some errors, details followed asap. But updating tells me there is no newer version available.

**Comment by ralfi** [comment]
Same with nc 16.0.2 docker image

**Comment by ralfi** [comment]
Same with nc 16.0.3 docker image. Mmmh. 

Conclusion: Creating lool oft file from Android mobile device works with different mobile browsers (Chrome, FF) and also from pc (amd64) browsers. Do not work from different mobile devices with different Android's and nc android app 3.7.0.

Should be stay opened.

**Comment by ralfi** [comment]
supplementing: app:check-code richdocuments tells me some errors but i really dont know if this relevant....

**Comment by ralfi** [comment]
For all who read this post ;-) ... 

I am build a Android_x86 VM to check a local NC / LOOL (latest docker hub images) setup without DNS, apache and reverse proxy. This config also DO work to create a LOOL odt file with the empty template with Chrome browser but NOT with the NC Android App latest DEV. So it seems to me this not depends on apache and reverse proxy but could be depend my docker configuration.

**Comment by ralfi** [comment]
[vokoscreen-2019-07-12_14-09-43.mkv.zip](https://github.com/nextcloud/android/files/3386377/vokoscreen-2019-07-12_14-09-43.mkv.zip)

(only remove zip extension before playing ...) screencast to see what i meean ...

**Comment by tobiasKaminsky** [comment]
Hm. I am unsure if this is related to Android or to the way we create the file from template, @juliushaertl 

Opening a 0kb will always fail, so this is somehow expected.

**Comment by ralfi** [comment]
This diff to the way create this with a browser is that with the app no "OK" button appears. Could that be relevant?

**Comment by ralfi** [comment]
[nextcloud_dev_log.txt](https://github.com/nextcloud/android/files/3391523/nextcloud_dev_log.txt)
a little log snip from Android DEV client ...

**Comment by tobiasKaminsky** [comment]
> This diff to the way create this with a browser is that with the app no "OK" button appears.

This is only UX: on browser you select the template and click on ok, wheres on Android selecting a template means to start creating it.
I assume that the error is later, as otherwise you would be stucked in this dialog.

**Comment by tobiasKaminsky** [comment]
> [nextcloud_dev_log.txt](https://github.com/nextcloud/android/files/3391523/nextcloud_dev_log.txt)
> a little log snip from Android DEV client ...

Have you done creating a template within this timespan which is in log?
Seems that it does not logged anything related

**Comment by tobiasKaminsky** [comment]
> But app:check-code richdocuments shows me some errors

Is this still valid?

**Comment by juliushaertl** [comment]
>> But app:check-code richdocuments shows me some errors

> Is this still valid?

That is known and not an issue here. Those are basically warnings for using static methods which don't have a proper API in the server yet.

**Comment by ralfi** [comment]
Sorry about NC dev log, wrong log level. I will upload a new one asap.

**Comment by ralfi** [comment]
But for me its reinforced that could only a problem between the two docker images and there configuration

**Comment by ralfi** [comment]
[nextcloud.log](https://github.com/nextcloud/android/files/3406595/nextcloud.log)
[loolwsd.log](https://github.com/nextcloud/android/files/3406596/loolwsd.log)

NEW insights ...

Okay, everything i open a existing od* file everything is fine. Error appears only with Android App on different devices and independent of existing docker config. Both new logs are from today without DNS, apache and / or proxy access, native on one machine with a Android QEMU VM and docker images for nc and lool.

Please have a look at loolwsd.log with the time stamp 12:25:29.153961. Is the template file "documentott" ? In my app window this appears as "leer" and i also missed the "." between document and the ott  file extension. Could this be the problem?

**Comment by ralfi** [comment]
And why could it work on the Tobias' Oneplus 3? Language settings ...?

**Comment by ralfi** [comment]
![Bildschirmfoto vom 2019-07-18 15-19-43](https://user-images.githubusercontent.com/294423/61460699-90f5c280-a96f-11e9-9802-c8002fe09fa6.png)

Setting the webdeveloper console in my browser tells me this about the "template-picker" codebase ...

**Comment by ralfi** [comment]
,wsd-00029-00122 2019-07-23 13:24:56.638378 [ docbroker_004 ] **ERR  Cannot save docKey [/index.php/apps/richdocuments/wopi/files/507120_oceqwn99mkb6], the .uno:Save has failed in LOK.| wsd/DocumentBroker.cpp:850**
,wsd-00029-00122 2019-07-23 13:25:51.566757 [ docbroker_004 ] INF  Dropping empty tilecombine response: tilecombine: part=0 width=512 height=512 tileposx tileposy imgsize tilewidth=3840 tileheight=3840 ver oldwid wid=| wsd/DocumentBroker.cpp:1677
,wsd-00029-00122 2019-07-23 13:25:51.840448 [ docbroker_004 ] WRN  Dropping empty tile response: tile: part=0 width=512 height=512 tileposx=3840 tileposy=0 tilewidth=3840 tileheight=3840 oldwid=3 wid=0 ver=106| wsd/DocumentBroker.cpp:1643
,wsd-00029-00122 2019-07-23 13:25:52.903410 [ docbroker_004 ] WRN  Dropping empty tile response: tile: part=0 width=512 height=512 tileposx=3840 tileposy=0 tilewidth=3840 tileheight=3840 oldwid=3 wid=0 ver=111| wsd/DocumentBroker.cpp:1643
,wsd-00029-00122 2019-07-23 13:25:54.280195 [ docbroker_004 ] INF  Saving doc [/index.php/apps/richdocuments/wopi/files/507120_oceqwn99mkb6].| wsd/DocumentBroker.cpp:1077
,wsd-00029-00122 2019-07-23 13:25:54.285429 [ docbroker_004 ] INF  ToClient-0058: Command: unocommandresult: {
,    "commandName": ".uno:Save",
,    "success": "false",
,    "result": {
,        "type": "void"
,    }
,}
,| wsd/ClientSession.cpp:745


Hope this helps further ...

**Comment by ralfi** [comment]
Heu -!- Re -!- Ka !

It seems to me i found a solution. On friday i change the way to set the background activities from ajax to cron.php for my docker image / data volume with nextcloudcron.service and nextcloudcron.timer how it describe in the admin doc section. Since this open the a LOOL doc with empty template works like a charm. Open with pre-defined user template do not work furthermore but this could be caused by the template definition.

Thanks Tobias and Julius
and all the people who works for this wonderful piece of software ... ;-)

**Comment by tobiasKaminsky** [comment]
@juliushaertl is this a known problem?

**Comment by juliushaertl** [comment]
This might have impact on editing in general, as we fetch details from the collabora server in a background job. However I still have no idea why this would only cause issues when editing on mobile.
