### ISSUE TITLE
[bug?] no sso with nextcloud dev

### ISSUE THREAD

**Issue by nr458h** [nextcloud/android#4190]
Hi guys,

I am using the android dev app from f-droid.

And I would expect, that similar to the stable release I can use the sso feature.

but when I try to use sso with another app(nextcloud deck) I got this error:

The nextcloud file app is not installed please install..
 (link to google play).

Do I need to use the stable version?

**Comment by tobiasKaminsky** [comment]
No, we added this recently.
But it must be included in the other apps, .e.g. deck: https://github.com/stefan-niedermann/nextcloud-deck/issues/78#issuecomment-506979208

As this is either for the other apps, or https://github.com/nextcloud/Android-SingleSignOn I'll close this here.

**Comment by nr458h** [comment]
thanks for the hint
