### ISSUE TITLE
Downloading a folder (for offline use) spams a large number of notifications

### ISSUE THREAD

**Issue by skumblex** [nextcloud/android#4197]
### Actual behaviour
When syncing a whole folder for offline use, the app spawns download notifications for each and every file in this folder. Thus performing an initial sync of a folder with approximately 50 files, already crashes the app unless you disable this particular type of notification.

### Expected behaviour
I would expect to see one notification showing the overall progress of the download.
 
### Steps to reproduce
1. Open the app
2. Click on the three dots next to the folder you want to sync
3. Click sync and see multiple notifications appear and disappear until the sync is completed

### Environment data
Android version: 9.0

Device model: OnePlus 6T

Stock or customized system: Stock; OxygenOS 9.0.14

Nextcloud app version: 3.6.2

Nextcloud server version: unknown

**Comment by tobiasKaminsky** [comment]
> already crashes the app unless you disable this particular type of notification.

I never experienced that multiple notifications crash the app.

Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

**Comment by skumblex** [comment]
Sure, I appended the logcat and I also made a video of the app 'crashing'. Hope this helps.

https://www.dropbox.com/s/vqiizsi7hwda00j/19-07-03-21-54-54.mp4?dl=0
[nextcloud_logcat.txt](https://github.com/nextcloud/android/files/3356680/nextcloud_logcat.txt)

**Comment by unix0r** [comment]
I'm getting the same "Crash", but somehow the app is not crashing. The App is downloading all files in the background process. As you can see in the video of @skumblex, the app shows the error, that its not responding, but the downloads are going on.

Small side question: Is there any multithreading model implemented for up- and downloads? As we can see, all files are downloaded file by file. Especially with a lot of files this is a huge performance weakness.

Back 2 Topic: maybe the exception has something to do with the loads of notifications. What about showing only one notification, regarding the status of all files down-/ uploaded? And not an extra notification for all files?

Something like Downloaded files: 43/354.

**Comment by redtux** [comment]
I can confirm that you get an error that the app is not responding - even when syncing very small folders. Beside that, the respective folder shows 0 bytes while syncing, which makes me think that everything inside the folder got accidentally deleted. After a second or so the shock is over and all my files still are where they belong.  Anyway, I also have the feeling that this is a strange and misleading behaviour.

**Comment by redtux** [comment]
Not sure if this really has been fixed…

**Comment by skumblex** [comment]
I am running th lastest version of the app that is available on the Play Store (3.8.0) and I can confirm that this issue has not yet been fixed.
When downlading a 1.6MB folder for offline use, there are not longer any notifications; however, most of the time I still get the message that "Nextcloud is not responding" and if I do not get this message, the app simply crashes.

**Comment by redtux** [comment]
I can also confirm it has not been fixed yet. Just tried and got the same
error again…
