### ISSUE TITLE
Cannot install Nextcloud client in Samsung Chromebook Pro 

### ISSUE THREAD

**Issue by rogeliodh** [nextcloud/android#4199]
### Actual behaviour

Cannot install Nextcloud client in Samsung Chromebook Pro.

Going to https://play.google.com/store/apps/details?id=com.nextcloud.client&hl=en&rdid=com.nextcloud.client

and clicking on install, it says that the app is not compabtible with my "google Samsung Chromebook Pro"

![image](https://user-images.githubusercontent.com/110125/60627498-d9c84b80-9db3-11e9-95f3-7841e6c116e0.png)

Searching for the nextcloud client in the Play Store app does not show the app.

To workaround the issue, I downloaded the source code, built the app, uploaded it with my Google Developer account, publish it as closed beta and it installs perfectly fine. So, I think this must be some setting in the play store listing.

### Expected behaviour

Nextcloud client should be compatible with Samsung Chromebook Pro.
 
### Steps to reproduce
1. Browse to https://play.google.com/store/apps/details?id=com.nextcloud.client&hl=en&rdid=com.nextcloud.client

2. click on install, 
2. select your "google Samsung Chromebook Pro"

### Environment data

ChromeOS version: Version 74.0.3729.159 (Official Build) (64-bit)

Android version: 7.1.1

Device model: "google Samsung Chromebook Pro"

Stock or customized system: Stock

Nextcloud app version:3.6.2

Nextcloud server version: 16.0.1

**Comment by tobiasKaminsky** [comment]
We fixed this for our upcoming 3.7.0.
If you want, you can join beta program and already install it.
Please re-open if it still does not work.
