### ISSUE TITLE
Feature request: watched folders

### ISSUE THREAD

**Issue by jasonbayton** [nextcloud/android#42]
I have several folders on my device that hold images; screenshots, whatsapp, DCIM, downloads, etc

With Google Photos I can select local directories outside of DCIM to watch and backup, can this functionality be added to the NC client also? We currently have autobackup for DCIM, but adding others to that list (and their respective locations on NC server) would be great.

**Comment by blackcrack** [comment]
+1 and would be well, if can select folders and connect with folders on the Cloud,
like the DCIM folder, connect with Photos or Photos-Work/ Photos-Private on the NextCloud
and hold this every sync if the Android connect via [X] WLan  [x]GX or other

the same with Documents (Documents-work/Documents-Private), 
Music and so on, if i move some songs up into Nextcloud to be it then later synced on my Android System's on my phones and my Tablet ..
as suggestion ..
(long press on the Folder in the NextOwn App opens a Sync-Configuration with a connect to local Folder and the NextCloud folder. And Connection configuration like via Wlan or other possibility's  with checkbox for have a control possibility with local folders and Nextcloud folders. )

best regards
Blacky

**Comment by tobiasKaminsky** [comment]
There is already a branch where I have started developing this.
It basically extends instant upload to any folder on the device and "links" this to a folder on the server.
So, stay tuned, this will come sooner or later

**Comment by jasonbayton** [comment]
Amazing, I'll jump on it as soon as it lands on beta!

**Comment by strugee** [comment]
Dupe of #285?

**Comment by jasonbayton** [comment]
Mine was first :p

**Comment by AndyScherzinger** [comment]
We can close this one if we want to #285 is basically outlining the road map for the the new sync feature which also contains a) any photo folder and b) any folder pair in general so we could just track it there. What do you thinl @jasonbayton ?

**Comment by jasonbayton** [comment]
I'm happy with that. Progress is progress :)
