### ISSUE TITLE
Unusual high battery consumption (for my taste)

### ISSUE THREAD

**Issue by r2p2** [nextcloud/android#4201]
### Actual behaviour
High battery consumption

### Expected behaviour
Nearly no battery consumption unless the app is used often.
 
### Steps to reproduce
Hard to say.
1. Install the application
2. Connect to own Nextcloud instance
3. Setup Synchronization of contacts, calendars and image upload (only if wlan and power are connected)

### Environment data
Android version: 9

Device model: Google Pixel

Stock or customized system: Stock

Nextcloud app version: 3.6.2

Nextcloud server version: 16.0.1

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

I will add a screenshot of the battery consumption later this day.

**Comment by r2p2** [comment]
Here are the promised screenshots. Sorry for the german language, I hope it makes sense nevertheless.
https://ibb.co/pXzVT9y
https://ibb.co/ynnmLXF

What's noteworthy is that the background activity seemed to increase constantly since around 9 o'clock but somewhere in the day it did stop. I will keep an eye on it today too. But first I have to update Nextcloud to 16.0.2 on the server.

**Comment by r2p2** [comment]
On Friday I thought it was over as it only consumed 3% over the whole day but on Saturday it did start again for no apparent reason, consuming 23% at the end while being active for 2h and 45 minutes in background tasks.

**Comment by S74HK9hV** [comment]
i recently started having the same issue. And not just battery consumption, the app used up 750MB of mobile data in the background. not sure what it was doing in the background that uses up so much battery and data. 

i see a LOT of requests to apache on the server "PROPFIND". please let me know what logs i can post to help diagnose. 

thanks

**Comment by r2p2** [comment]
30% today. I saw the background data too. That was easy to fix by preventing it to use mobile data via android. But since my phone is on wlan all day long...

**Comment by r2p2** [comment]
Okay, one thing is strange. I've installed PhoneTrack which drains the battery like crazy, at least when active.  Most of the time it is inactive but since the installation, both Nextcloud and Samsung Health drain massively more power than before.

Is it possible that some apps issue something in the Android OS which causes other apps (Nextcloud, ..) to wake-up more often?

**Comment by ezaquarii** [comment]
Sync is done every 15 mins.

**Comment by r2p2** [comment]
I managed to call `adb shell` and see com.nextcloud.client using 30% cpu while printing REQUEST PROPFIND in the log. If this is an actual thing which happens every 15 minutes and takes for my number of files so long that my phone is actually active all the time, than my question would be: How can I disable that without losing contact, calendar and notes synchronization?

**Comment by AndyScherzinger** [comment]
cc @tobiasKaminsky for the latest questions / infos being raised/provided
