### ISSUE TITLE
Leakage of deleted files

### ISSUE THREAD

**Issue by pilsnerbeer** [nextcloud/android#4203]
### Actual behaviour
Deleted files loaded in cache will for a brief time appear in folders as if they were still present before finally disappearing. Some files (like pictures) can still be partially retrieved and viewed in a short time window (from cache).

**Picture 1: Folder showing deleted content**

![Screenshot_20190705-172554](https://user-images.githubusercontent.com/36133540/60733016-33a74d80-9f3b-11e9-86f9-5ffe577faa94.jpg)

**Picture 2: Files finally disappear after a short time**

![Screenshot_20190705-172559](https://user-images.githubusercontent.com/36133540/60733046-4e79c200-9f3b-11e9-9e8f-5958b567ee46.jpg)

**Picture 3: Deleted files can be opened from cache**

![Screenshot_20190705-172640](https://user-images.githubusercontent.com/36133540/60733054-5afe1a80-9f3b-11e9-995f-da44197b26d6.jpg)

### Expected behaviour
Deleted files should not appear anymore in the folders. Maybe retrieve deleted content from the server & remove deleted files from cache on app start?
 
### Steps to reproduce
1. open a folder with some files on your phone
2. delete the files from somewhere else, like your PC
3. access the folder on your phone, files will be visible for a brief time

### Environment data
Android version: 9

Nextcloud app version: 3.6.2

Nextcloud server version: 16

**Comment by tobiasKaminsky** [comment]
As we sync currently only upon entering a folder, we cannot do it in another way right now.
I am also unsure if we ever will/can do it the same like on desktop and always sync the complete file tree with all subfolders, as mobile devices are still limited in terms of battery and storage (even if it is the metadata).
Especially if you think of companies with more than 100k files/folder into it, I am not sure if this all needs to be up to date on mobile clients.

Back to topic: if you enter a folder it takes a bit of time (depending on folder size, connection speed, etc.) to get a new folder list. 

We could first show a loading info and only after having the new list, we could show it.
What do you think?

cc @AndyScherzinger @ezaquarii

**Comment by pilsnerbeer** [comment]
I personally like that idea - show a loading screen whenever user opens a folder which has been changed in any way and/or shows incomplete data. There are a few issues with this approach though, mainly that the current approach (small loading bar at the tom) lets you interact with files while others are loading, making interaction with the app much faster. If user has to wait for each screen to load updated content, it will damage the user experience. 

I really like how MEGA app reacts to data changes. ([GitHub](https://github.com/meganz/android/) - It doesnt seem to be running in the background and the updates are immediately synced. I would enjoy this very much on Nextcloud.
