### ISSUE TITLE
Video playback stops once buffer underflows

### ISSUE THREAD

**Issue by nakal** [nextcloud/android#4204]
### Actual behaviour
Tapping on a video, it starts to buffer and starts to play a moment later. After a few seconds the playback buffer seems to be underflowing and the video stops for ever. It's not possible to make it play anymore.

### Expected behaviour
The video player should wait for buffer to fill and continue automatically, when there is enough data to play again. It should also be possible to navigate back and play the video within the available data range.
 
### Steps to reproduce
1. Tap on a video.

### Environment data
Android version: 9

Device model: OnePlus A6003

Stock or customized system: stock

Nextcloud app version: 3.7.0 RC4

Nextcloud server version: 16.0.1 (FreeBSD)

### Logs

Please tell me if you look for something particular in logs, I'll provide it. It looks like the relevant URI in the remote.php HTTP request (used for streaming?) contains sensitive information.

**Comment by AaronADev** [comment]
It appears that I am facing the same issue as well.

Android 9
Samsung Galaxy S9+
Nextcloud 16.02

**Comment by Simounet** [comment]
Hi there,
I'm also encountering this issue making this app unusable to play Nextcloud videos. I have to download before playing them.
- I don't have any error in the Nextcloud log file,
- Everything is fine from the web view,
- I tried to use VLC for Android to play the video but it didn't even start.
Can I send some logs from my Android app to help you?
Have a nice day and stay safe.

**Comment by tobiasKaminsky** [comment]
Do you use a reverse proxy?
What is your setup?

**Comment by Simounet** [comment]
No reverse proxy, Apache2, PHP-FPM7.3 and as I said, it's working fine through a browser.

**Comment by nakal** [comment]
The bug still exists. It happens when the buffer underflows at some time during playback. It seems it improved for me slightly, because when I wrote the first report the underflow happened right at the beginning quite often.

**Comment by tobiasKaminsky** [comment]
@ezaquarii as you had a deep look into media player: do you know a way to improve buffer underruns?

**Comment by ezaquarii** [comment]
@tobiasKaminsky For the video player - no. Audio player has different architecture, with playback in background. We control everything there.

Video player does not use a dedicated player service - it's just loads URL into a `VideoView` - very  basic component encapsulating `MediaPlayer`. We'd need to deliver something more sophisticated than that.

First line of defense would be to increase buffer size, but tbh I'd assume that the player can recover for an underrun itsef.

We could also take a loot at `ExoPlayer`.

**Comment by Simounet** [comment]
Can we give a debug log to help you? Don't you encounter this issue too?

**Comment by ezaquarii** [comment]
The best idea would be to provide an account and content where this can be reproduced. How easily reproducible this problem is? Does it happen on different devices in different networks?

**Comment by tobiasKaminsky** [comment]
Strange is that VLC also does not work.
I would have assumed that VLC is better in terms of stability…

**Comment by ezaquarii** [comment]
On Wed, Apr 22, 2020 at 04:49:41AM -0700, Tobias Kaminsky wrote:
> Strange is that VLC also does not work.
> I would have assumed that VLC is better in terms of stability…

Could be a web server config issue?

**Comment by tobiasKaminsky** [comment]
> Can we give a debug log to help you? Don't you encounter this issue too?

Can you create us a test account, test if the problem occurs also there and if so send the credentials to tobias at nextcloud dot com with a reference to this issue?

**Comment by Simounet** [comment]
Sorry for the late reply. Mail sent.

**Comment by Simounet** [comment]
This time, this is not my fault and I still encountering this issue. Help needed. :)

**Comment by Simounet** [comment]
It's still a very annoying issue.

**Comment by tobiasKaminsky** [comment]
There is an experimental switch to another video player in https://github.com/nextcloud/android/pull/8132#issuecomment-792722526

This apk can be installed in parallel. 
It would be great if you can give this a test, if it helps in your scenario.

**Comment by Simounet** [comment]
- on the main app, I can't play any video anymore, I just can see the icon but no video playing
- on your QA app, I can play the whole video (which is a great progress) BUT the video doesn't seems to be stopped and run in the background even if I try to play another one. I had the video playing after I closed the app and locked my phone. Maybe it's normal at the moment but I wanted to let you know @tobiasKaminsky .

**Comment by tobiasKaminsky** [comment]
Thanks for testing.
Indeed this is "just" to prove if streaming / playback is better.
I did not fully tested stop/resume, etc.

**Comment by Simounet** [comment]
Good to know. So it worked. Don't know if it's normal that the current official build is not working at all then.
