### ISSUE TITLE
Automatic Upload doesn't work

### ISSUE THREAD

**Issue by bastel-123** [nextcloud/android#4207]
Environment:
Huawei P20 Pro mit latest updates (Android 9). Netcloud app ist not added to the battery saving options.

Netzcloud on server is the latest version too.

Related list is added at the automatic upload menu. But nothing happens. Locale WIFI is connected.

**Comment by thechonta** [comment]
You hvae to disable autoupdate for aps and install 3.4.2 APK (before download it)
It is the last ap that work for P20 Pro.
Funfact everything less then 1MB will be uploaded, and no it has nothing to do with the serversetings

Sadly that it still not work. but now i do not need to test on my own :-)

**Comment by bastel-123** [comment]
Thank you for your response. Is it planed to fix this bug?

**Comment by thechonta** [comment]
I hope so, i am only an customer with an P20 Pro ^^
This Bug reportet also for some Samsung devices and mentioned mote than once on github.

**Comment by memen45** [comment]
Take a look at [this comment](https://github.com/nextcloud/android/issues/4004#issuecomment-497306727) and [this fix](https://github.com/nextcloud/android/issues/2834#issuecomment-413856687).

Not sure if it is a real bug, since new installs seem to work fine.

**Comment by thechonta** [comment]
i deletet cache and all the stuff nothing helped

**Comment by Excel1** [comment]
@memen45 @bastel-123  Same problem like here? 
https://github.com/nextcloud/android/issues/3721
