### ISSUE TITLE
Integrate found issues from codacy in github pr review

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#421]
https://www.codacy.com/landing-page-assets/images/main/png/landing-screen-2.png

> Codacy pushes results as comments in your pull requests or as notifications in Slack or Hipchat channels.

It would also be great to have a threshold of codacy issue severity which must be solved, e.g. all NPE or critical issues must be solved before codacy shows a valid pr. (I do not know if this is possible)

**Comment by AndyScherzinger** [comment]
I will check that. With today's integration Codacy already blocks a merge if the code quality would get worse with the merge :)

**Comment by tobiasKaminsky** [comment]
https://support.codacy.com/hc/en-us/articles/207280219-GitHub

But I can only integrate this on my forked repo, as far as I understand this.

**Comment by AndyScherzinger** [comment]
Since the bot started commenting it seems you got it working :)
