### ISSUE TITLE
Share/Send to snapseed of photo doesn't work unless downloaded

### ISSUE THREAD

**Issue by rexbron** [nextcloud/android#4212]
### Actual behaviour
- Sharing a photo to a local app like Snapseed for further editing will hang in Snapseed on a loading screen. 

Downloading the photo to the local device results in the correct behavior.

### Expected behaviour
- Photo will be downloaded automatically if required.
 
### Steps to reproduce
1. Load photo 
2. Share photo
3. Wait forever

### Environment data
Android version: 9

Device model: pixel 3A

Stock or customized system: Stock

Nextcloud app version: 3.6.2

Nextcloud server version: 16

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by rexbron** [comment]
Bump.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky I can reproduce this with snapseed while it works just fine with Instagram for example. Important is that we talk about the preview image if you download it, it'll also work with snapseed. I am afk so I don't know if there is a difference in handling images preview vs full resolution...

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger as there is quite some time passed, can you test it again with snapseed?
Maybe they fixed it on their side.

**Comment by rexbron** [comment]
Just tested it again. The cached thumbnail of the image gets sent to
Snapseed rather than the actual image.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky AFAIK that is the expected behavior while I understand that this is not the desired behavior depending on the app you have chosen (which is one step to late).

What do you think @tobiasKaminsky @jancborchardt? We can destinguish this situation since the choice of the app to share the image to happen after we pick the image (thumbnail). So either it is always the smaller image or we change the logic and sharing an image to another android app always leads to a download.

**Comment by rexbron** [comment]
Imo, sharing of the picture should lead to a cached download.

Expected behavior that doesn't meet the desired behavior is still a bug :)

**Comment by tobiasKaminsky** [comment]
> @tobiasKaminsky AFAIK that is the expected behavior while I understand that this is not the desired behavior depending on the app you have chosen (which is one step to late).

The image that is currently available will be shared.
If the file is downloaded, the full sized image will be used, else the preview image (screen size adapted).

If any, we could add something like "share full size / resized image" for images only.
But there should be no direct auto-download a 12Mb file when an user wants to share it via e.g. WhatsApp where it gets resized anyways…
