### ISSUE TITLE
Insta Upload stopped working properly

### ISSUE THREAD

**Issue by farao** [nextcloud/android#422]
### Actual behaviour
- When connecting wifi, Insta-Upload starts uploading taken photos
- Usually the first 2-3 work fine and then most of the file uploads show some progress (usually until ~70%, but sometimes also less) and then fail
- Retrying of the failed uploads leads to failed uploads again
- also: when entering the InstaUpload directory (in "All Data"), the nextcloud app failed a lot of times until I was able to enter it (now not happening anymore) -> might have something to do with my insta upload directory containing 4,6gb of files - it's now still slow when I open the directory

### Expected behaviour
-Photos should be uploaded
-If an upload fails, the retry should work
-If a use "remove failed uploads", there should be a way how I can synchronize the instant upload directory later. How am I supposed to do this now? I have some pictures that failed to upload and I can't event retry anymore because I accidentally used the remove functionality (now they are still in my phone gallery but not in the instant upload folder in the nextcloud app)
=> It would be nice to have a "upload all not synchronized/previously failed photos from the gallery" option or so

### Environment data
Android version: Cyanogenmod 13.0

Device model: Moto G3

Nextcloud app version: 1.3.1

Nextcloud server version: 10.0

#### Web server error log
No entries in lighttpd error log. In access.log, only the successful uploads appear as "PUT" with result 201

#### Nextcloud log (data/nextcloud.log)
No errors

**Comment by AndyScherzinger** [comment]
Sounds to me like the chucking bug we which will be fixed in 1.4.0 to be released really really soon, and in most likely some time next week. :)

**Comment by farao** [comment]
Wonderful, I'll wait for that :-) Will 1.4 also provide me with a way to synchronize my not uploaded photos with the InstantUpload folder on my nextcloud or is there another way to do this?

**Comment by farao** [comment]
So I tried the new client version (1.4 RC2 from F-Droid) but it didn't solve the problem. When I retry all the failed uploads, it shows me message pairs like this in the lighttpd access.log:

<myip> <mydomain> - [10/Dec/2016:19:27:20 +0100] "HEAD /remote.php/webdav/<uploaddir> HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Android) ownCloud-android/1.4.0 RC2"
<myip> <mydomain> - [10/Dec/2016:19:27:21 +0100] "HEAD /remote.php/webdav/<uploaddir>/IMG_20161130_115439.jpg HTTP/1.1" 404 0 "-" "Mozilla/5.0 (Android) ownCloud-android/1.4.0 RC2"

So the lookup of the upload directory works (200) but of the picture doesn't (404). Actually this is not unexpected, right? But it isn't followed by a PUT and on the client it only shows the message that the picture is uploading for a brief moment before apparently failing and continuing to the next picture (which then fails again because most of the uploads fails currently).

Do you have any idea what's the source of the problem here? Is it rather the server or the app? When uploading from my linux client I usually don't have any problems

**Comment by farao** [comment]
Also: Can I somehow get a log of the Android app? It would be nice to know the reason for all the failing uploads

**Comment by AndyScherzinger** [comment]
1.4.0 has now also been released on f-droid with some more networking related fixes. 

A client side log is only available in the beta app available via f-droid (to be found in the settings). 

A future version of the stable app will add the ability to activate client side logging.

**Comment by farao** [comment]
Works perfectly with 1.4.0. Thanks for the great work :-)

A "synchronize all non-uploaded" button would still be nice in the future!

**Comment by AndyScherzinger** [comment]
A "synchronize all non-uploaded" is planed for future version which will still need some time since we need to iron out bug of the new auto upload and also add further other features to it first before we get to the point to implement a sync / upload existing files.

**Comment by tobiasKaminsky** [comment]
> A "synchronize all non-uploaded" is planed for future version

Do we have an open issue for this?

**Comment by AndyScherzinger** [comment]
added it to #285 v1.1
