### ISSUE TITLE
Restricting mobile data usage

### ISSUE THREAD

**Issue by torantal** [nextcloud/android#4221]
I activated auto upload for photos but need to restrict it to wifi usage.

I have not found a system setting on my Samsung note 9 with Android Pie to restrict the app.

Therefore I would like to see an option to delay uploads until an unmetered wifi is connected.

**Comment by ezaquarii** [comment]
`Drawer` -> `Autoupload` -> `...`
![settings](https://user-images.githubusercontent.com/1426823/61078376-63ad8f80-a418-11e9-8dd8-5573c6734191.jpg)

**Comment by torantal** [comment]
Thanks, I checked and I actually had this set (and didn't find this setting again later). 

Still, with this active I've had 1.2 GB of mobile uploads this month. I guess I have to refile this request under bugs.

**Comment by g6094199** [comment]
So,

**can we have this setting for Downloads, too?!**

In fact sometimes it happens that i start sync (download) music from the cloud while i`m in WIFI, but on the run. So i leave while syncing is not finished and will continue on the mobile connection and exceeds my free volume very fast.

Sash
