### ISSUE TITLE
Upload trying to kill memory and hang device

### ISSUE THREAD

**Issue by mittorn** [nextcloud/android#4222]
### Actual behaviour
When i uploading file, application try to copy file to different folder (like /data/data/.../files). If file very big, it fails or hang device for few minutes due to high io activity. It even may crash android with ANR
### Expected behaviour
Upload is going directly to server
### Steps to reproduce
1. Open upload target
2. Select upload in menu
3. Start uploading big file

### Environment data
Android version:
5.1
Device model: 
Stark Impress Strong
Stock or customized system:
Stock
Nextcloud app version:
3.6.2 f-droid

**Comment by mittorn** [comment]
NAND/eMMC has limited write cycles, so this behaviour is inacceptable

**Comment by tobiasKaminsky** [comment]
@mario 

https://github.com/nextcloud/android/blob/49d858ea9fcbf1a5ca2907a31e7c8b926f60e233/src/main/java/com/owncloud/android/operations/UploadFileOperation.java#L793-L822

I think this was added by you.
Can you give me a hint why you copy the file?

**Comment by mittorn** [comment]
Copy is needed only if file given from other app. But i think, there are some streaming solutions for all  sources. Browsers does not copy files got from document api. I was able to upload 900mb file using aosp browser, but nextcloud client failed because no much free space.

**Comment by mittorn** [comment]
Tried https://download.nextcloud.com/android/nextcloud-10010001.apk
It has same behaviour.
