### ISSUE TITLE
Server not found problem

### ISSUE THREAD

**Issue by sanchobear** [nextcloud/android#4224]
Situation: Nextcloud is installed on a local machine and this machine can be accessed from the internet. For in-house WIFI use the public domain name is routed by a DNS split to the local machine.

Problem: The nextcloud app connects from outside - no problem. When inside the local wifi area the app shows "server not available", even after stopping and restart app with new connection and will never connect.

Expected behavior: The app should connect by any available technology and switch upon availability.

Hint: Nextcloud-Tak app and Dav-x5 equally work in-house wifi or out of house.

**Comment by tobiasKaminsky** [comment]
This should be something that you can configure on your local wifi AP/dns routing.
