### ISSUE TITLE
Log_OC doesn't collect logs in file

### ISSUE THREAD

**Issue by ezaquarii** [nextcloud/android#4228]
### Actual behaviour
Logs don't show up in `Settings`->`Logs`

### Expected behaviour
Logs should be visible there

### Steps to reproduce
1. Launch Nextcloud app
2. Go to `Settings`->`Logs`
3. Logs are outdated

### Environment data
Android version: 9.0
Device model: One Plus 6T
Stock or customized system: Stock
Nextcloud app version: master
Nextcloud server version: 16.0.2

#### Nextcloud log (data/nextcloud.log)
```
This is exactly the stuff that is missing!
```

**Comment by ezaquarii** [comment]
Logging must be enabled:
```
synchronized private static void appendLog(String text) {
    if (isEnabled) {
        ...
```

However, the logger is enabled in a somewhat peculiar way:

```
synchronized public static void startLogging(Context context) {
    ...
    try {
        // Create the current log file if does not exist
        isEnabled = mLogFile.createNewFile();
```

`File.createNewFile` returns `false` if the file already exists, which means that logging works only for the very first ime. On all subsequent app runs logging is disabled.

**Comment by ezaquarii** [comment]
To solve this problem, there are few things that are piling up:

1. ETM PR for injectable view models: https://github.com/nextcloud/android/pull/4133
2. Pluggable logger implementation in Library: https://github.com/nextcloud/android-library/pull/324
3. New logger - https://github.com/nextcloud/android/pull/4275

**Comment by tobiasKaminsky** [comment]
Thanks for the nice summary and bug finding/fixing!
I'll have a look at the PRs now.
