### ISSUE TITLE
Make local owncloud folder visible to other applications

### ISSUE THREAD

**Issue by Ventusfahrer** [nextcloud/android#423]
### Actual behaviour
I am using AndrOpen Office.
When saving a new document I got offered (see first screenshot) to store to the Local Drive (which is a subdirectory to /storage/emulated/0/myapplication...).
Additionaly I got the possibility to save my file in the dropbox or the "Other Cloud Storage" 
![savedocumentto](https://cloud.githubusercontent.com/assets/5901190/20868535/1fca0754-ba5e-11e6-8312-2211c46ebea5.png)

- which is the directory of the Cirrus App (also an owncloud client).
![lastused-afterothercloudstorage](https://cloud.githubusercontent.com/assets/5901190/20868536/2861714a-ba5e-11e6-8241-be03ebc12b35.png)

The NextCloud folder is missing here...)

### Expected behaviour
I would like to see the nextCloud folder too here.
 
### Steps to reproduce
1. Create a new document with AndrOpen Office
2. Save the document

### Environment data

Android version:
7.0

Device model: 
Nexus 9

Stock or customized system:
stock

Nextcloud app version:
20161129-beta

Nextcloud server version:
10.0.1

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

**Comment by tobiasKaminsky** [comment]
We need to figure out why other cloud clients are shown there.

**Comment by AndyScherzinger** [comment]
Imo because our document provider is read only thus not shown for write...

**Comment by joshtrichards** [comment]
This was implemented long ago through a number of PRs, but probably most relevant in this case is #3433.
