### ISSUE TITLE
Adding an account results the first account disappearing

### ISSUE THREAD

**Issue by Mikaela** [nextcloud/android#4234]
### Actual behaviour

I logged in, and from the left sidebar added an account by clicking the id and selecting "Lisää tili" ("Add account" in Finnish). After logging in, I only see the recently added account and the first one seems to have gotten forgotten entirely. I don't see it in "Tilien hallinta" ("Credential/account" manager?).

### Expected behaviour

- I expected I could switch between my two accounts (and when I logged into a third one) from the sidebar on the left.
 
### Steps to reproduce

1. Install Nextcloud and login to get to the main screen 
2. Select "Lisää tunnus" (Add account) from the sidebar on the left
3. Login
4. The first account disappears from the left sidebar.

### Environment data

Android version: Android 9 Go Edition (2019-06-05 security patches)

Device model: Nokia 1 TA-1047

Stock or customized system: stock

Nextcloud app version: 3.7.0 from Play Store

Nextcloud server version: I don't know either

### Logs

I don't think I have access to them on either instance.

**Comment by mvidelgauz** [comment]
@Mikaela I _thought_ I have the same problem and even was filling my environment details here until I realized that this is just a bit misleading UI in the android app. After I set up easily distinguishable profile pictures for both accounts I mentioned them both as seen in the attached screenshot. I agree that arrow down is a bit misleading and makes a user think that it will expand to a list of accounts and let you switch between them. But now I can switch to another account by tapping its avatar on the right side:


![Screenshot_20190719-212556_Nextcloud](https://user-images.githubusercontent.com/547740/61557358-b4526780-aa6c-11e9-9341-62c35635915d.jpg)

**Comment by heikojansen** [comment]
I have the same problem as Mikaela on a freshly installed Android Phone (Resurrection Remix OS 7.0.2, so Android 9). App is 3.7.0 from Google Play Store.
This used to work fine on a whole number of other devices and in fact I have another phone in the family with the same OS where I have two different Nextcloud accounts working just fine.

**Comment by heikojansen** [comment]
Oh my. Gave it one last try after adding my comment and of course this time it worked. I'm pretty sure that I did follow the exact same steps that did not work for at least five times before and I have no idea what made the difference...

**Comment by mvidelgauz** [comment]
looks like just writing a post in this thread solves the problem ))))

**Comment by Mikaela** [comment]
> looks like just writing a post in this thread solves the problem ))))

I cannot reproduce this and neither has any other suggestion helped. I have tried touching the empty areas, but I am not magically transferred to the first account :(

**Comment by Berni-MD** [comment]
I also have this mistake!
A second account cannot be created. 
Android 9.0, Huawei, security patch 05.06.2019

**Comment by diesl** [comment]
I have the same issue. After adding the second account, the first one has disappeared.

Android version: Android 9

Device model: Google Pixel 2 XL

Stock or customized system: stock

Nextcloud app version: 3.7.1 from F-Droid

Nextcloud server version: 16.0.3 (Docker)

**Comment by netmackan** [comment]
Same problem. Will post here and see if it helps :-)

Nextcloud app version: 3.7.1. from F-Droid
Android 9 (LineageOS)

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky do you have a clue when this might happen?

**Comment by KayKursawe** [comment]
Same here.

- Nextcloud app 3.7.2 from Play Store
- Android 6.0
- 2 Nextcloud instances, Hetzner Storage Share 16.0.4

I had the app connected to both instances in parallel and it worked like a charm for several months. Needed to re-setup the accounts now, since the domains have changed. Now it's not working anymore.
Not only does the the first account disappear when setting up the second one, but both of them.

**Comment by maledo** [comment]
Any news on this? Has someone found a workaround?
I have the same problem with version 3.8.0 from F-Droid on Android 9.

Issue #4529 is probably the same.

**Comment by ezaquarii** [comment]
Reproducible on master!

**Comment by ezaquarii** [comment]
Adding new account launches `FirstRunActivity`. Due to some logic flaw, `isFirstRun` flag is still true, even after the user logged in.

This causes a cleanup routine to remove all app accounts from the phone.

**Comment by ezaquarii** [comment]
> Any news on this? Has someone found a workaround?
> I have the same problem with version 3.8.0 from F-Droid on Android 9.
> 
> Issue #4529 is probably the same.

@maledo @KayKursawe  @netmackan  @diesl  @Berni-MD Yes, there is a work around.

1. Add your first account
2. Kill the app (terminate the process, either by swiping it out from recent apps or using Force Close via Settings->Apps)
3. Start the app and add more accounts (no need to kill the app)

This bug happens only if you try to add multiple accounts immediately after installations. It won't affect you if you have restarted the app since first login.

**Comment by maledo** [comment]
Thank you @ezaquarii , that worked for me!
