### ISSUE TITLE
Configurable delay/auto-delete for auto-upload 

### ISSUE THREAD

**Issue by bruennlein** [nextcloud/android#4240]
Hi all,

it would be nice, if the auto-upload could get a configureable delay. Because when you take some pictures and then delete all but the best one, every picture gets uploaded instantly.
Having a delay could prevent from uploading unecessary pictures to the server (which have to be cleaned up later).
Maybe this request is for the same reason as in #3696. They already mentioned a delayed upload. But I would prefer a configurable delay.
Anyway, there should be an option to automatically delete pictures from the server, which got deleted on the mobile devices auto-upload folder(s).

Cheers...

**Comment by tobiasKaminsky** [comment]
This is indeed the same as in #3696, whereas the other idea is to not have a configurable delay as this will complicate UI, but is rather needed.
