### ISSUE TITLE
Can't open Keepass file from app

### ISSUE THREAD

**Issue by gloomytrousers** [nextcloud/android#4246]
### Actual behaviour
I have a KeePass password repo (.kdbx file) in Nextcloud, the Nextcloud app and KeePassDroid (v2.4.1) on my phone. Until recently (I don't know when it changed), I was able to tap on the password file in the Android app and it would open in KeePassDroid. However, now when I do so I get the message "No app set up to handle this file type."

In case it's relevant: on the server, /etc/nextcloud/mimetypemapping.json contains
```
{
  "kdbx": ["application/x-kdbx"]
}
```

I have the Keeweb app installed on the server at that opens the file fine.

### Expected behaviour
The KeePassDroid app should open and load the file.
 
### Steps to reproduce
1. Tap on the .kbdx file in Nextcloud app

### Environment data
Android version: LineageOS 16.0 (same behaviour in 15.0)

Device model: Samsung S5

Stock or customized system: Custom OS (LineageOS)

Nextcloud app version: 3.7.0

Nextcloud server version: 16.0.3

**Comment by gloomytrousers** [comment]
Still happening. App version 3.7.1.

**Comment by genesispower411** [comment]
How change password?

**Comment by MathiasRenner** [comment]
Still happening, for me, too.

**Comment by mr-bolle** [comment]
Could you try the app [keepass2android](https://play.google.com/store/apps/details?id=keepass2android.keepass2android) with this application you can download .kdbx files from Nextcloud. I use the webdav path to the password container.

**Comment by AndyScherzinger** [comment]
> Could you try the app keepass2android with this application you can download .kdbx files from Nextcloud. I use the webdav path to the password container.

I am also using keepass2android in the exact same way and it works just fine. I'd also say it is better/easier to leave this to the keepass mobile app itself

**Comment by MathiasRenner** [comment]
I had success using the app recommended by @mr-bolle . Thank you very much!
@AndyScherzinger Thanks to you, too, I agree that the usability is nicer. I used "Keepass DX" before.

**Comment by mr-bolle** [comment]
@MathiasRenner great that it works for you too. This application is from original developer of keepass.

**Comment by tobiasKaminsky** [comment]
So this not a bug in our app but rather a missing extensions registration on the other app?

**Comment by gloomytrousers** [comment]
Looks like you're right. There's a fix but it's not merged (after 6 months): https://github.com/bpellin/keepassdroid/pull/352

**Comment by genesispower411** [comment]
How change cloud password?


This e-mail message may contain legally privileged and/or confidential
information. If you are not the intended recipient(s), or the employee or
agent responsible for delivery of this message to the intended
recipient(s), you are hereby notified that any dissemination, distribution
or copying of this e-mail message is strictly prohibited. Should you
have received this message in error, please immediately notify the sender
and delete this e-mail message from your computer.

PLEASE CONSIDER THE ENVIRONMENT BEFORE PRINTING THIS E-MAIL


PLEASE CONSIDER THE ENVIRONMENT BEFORE PRINTING THIS E-MAIL

**Comment by mr-bolle** [comment]
This sounds like a Phishing Mail. You don't get such mail from Nextcloud.

If you have to restore your nextcloud password, you can reset if you want to login (if you set a email account)

Otherwise you are posting on the wrong repository.

**Comment by gloomytrousers** [comment]
@genesispower411 your question is unclear and, as far as I can tell, this does not seem the most appropriate place to ask it.
