### ISSUE TITLE
Synching Files in Android-Client doesn’t work with [] in path

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#4247]
copied from https://help.nextcloud.com/t/synching-files-in-android-client-doesnt-work-with-in-path/56272

> Took me a couple of days to figure out, since it’s an external storage having [] in its name. Maybe one could add a warning, since so far it only says couldn’t download.

**Comment by AndyScherzinger** [comment]
ping

**Comment by tobiasKaminsky** [comment]
External storage: is this meant on server or on Android?

**Comment by totti4ever** [comment]
ah, sorry - here as well :-)

it is meant on the NC server

**Comment by tobiasKaminsky** [comment]
@nextcloud/server-triage have you ever heard about this problem?

**Comment by rullzer** [comment]
I believe those are indeed not allowed chars

**Comment by tobiasKaminsky** [comment]
Hm. How can we prevent this? 
I remember there was a time where Android client checked for those chars.
This seems to be only for external storage, or?

**Comment by rullzer** [comment]
Nope you also can't create it in the webui right now I believe

**Comment by totti4ever** [comment]
Well, I could set it up using the web UI?!

That is what my problem is based upon

**Comment by AndyScherzinger** [comment]
Still needs to be checked

**Comment by AndyScherzinger** [comment]
Still needs to be checked

**Comment by AndyScherzinger** [comment]
Still needs to be checked

**Comment by tobiasKaminsky** [comment]
Which type of external storage is causing the problem?

**Comment by totti4ever** [comment]
> Which type of external storage is causing the problem?

pretty sure it was Samba

**Comment by AndyScherzinger** [comment]
Still needs to be checked

**Comment by tobiasKaminsky** [comment]
> Nope you also can't create it in the webui right now I believe

I can create "[ iae ]" on web ui…

**Comment by tobiasKaminsky** [comment]
Or is web checking explicitly for external storage?
