### ISSUE TITLE
auto-upload and WhatsApp backups

### ISSUE THREAD

**Issue by micheelengronne** [nextcloud/android#4260]
### Actual behaviour

When auto-upload uploads WhatsApp backups files it perfectly uploads the file from the last day (which has a date indication like `msgstore-2019-07-25.dB.crypt12 `) but it creates a conflict with the backup of the day (which has no date indication like `msgstore.dB.crypt12 `) as a file with the same name already exists on the server.

The error message is (in french) `Conflit de synchronisation, Veuillez le résoudre manuellement`

### Expected behaviour
All WhatsApp backups should be successfully uploaded. The backup of the day should replace the previous one on the server (and with version enabled, should create a new version).
 
### Steps to reproduce
1. Configure WhatsApp backups for local storage
2. Add auto-upload on the local folder containing WhatsApp backups files
3. Wait for an auto-upload and another. The first auto-upload will create the backup of the day file on the server, the second auto-upload will show the error message

**Comment by tobiasKaminsky** [comment]
I cannot reproduce it:
- manual auto upload folder for /sdcard/downloads
- copied an image to downloads
- wait for upload
- adb shell: echo >> file.jpg to get a change on filesystem
- wait for upload
- see new upload, but file was overwritten

![2019-07-30-141034](https://user-images.githubusercontent.com/5836855/62128048-da310500-b2d3-11e9-8fa7-fa021f57b541.png)

**Comment by micheelengronne** [comment]
Apparently it was fixed in the last release as I can not reproduce anymore either :)

Cool !

**Comment by ArnaudD-FR** [comment]
I have the same issue. I have set up the WhatsApp backup folder to Auto Upload, this is working fine. But each night WhatsApp is overriding some files in this folder and creating new ones. 

For each overridden file, each morning, I have to solve the conflict issue manually. It would be good to have an option to remember the conflict resolution choice.

Android App version: 3.11.0
Nextcloud server: 18.0.3

**Comment by micheelengronne** [comment]
It is also back for me.

**Comment by tobiasKaminsky** [comment]
This will be solved by #5810
