### ISSUE TITLE
No connection with WiFi

### ISSUE THREAD

**Issue by Hoerli1337** [nextcloud/android#427]
### Actual behaviour
- If i use WiFi, i cant login or download anything.
- If i use mobile data, all works fine

### Expected behaviour
- Login and Download / upload files with WiFi
 
### Steps to reproduce
1. Activate WLan
2. Try to Login
3. Try to download a file

### Environment data
Android version: 6.0.1 + 6.0

Device model: Samsung Galaxy Note 3 + Samsung Galaxy Alpha

Stock or customized system: Phronesis ROM + Stock ROM without root

Nextcloud app version: 1.4.0 RC4

Nextcloud server version: 10.0.1 (stable)

#### Web server error log
```
No logs for that. Sorry
```

#### Nextcloud log (data/nextcloud.log)
```
No logs for that. Sorry.
```

**Comment by AndyScherzinger** [comment]
Hi @Hoerli1337,

is your server with a IPv6 or IPv4 address? Just asking since at this moment the client doesn't yet support IPv6 which would explain why you can't connect via the wifi or is it any wifi network you are connected to?

**Comment by Hoerli1337** [comment]
I use both. IPv4 and IPv6.
Its any Wifi-Network i use.
But 1/20 it works with wifi.
It may be an IPv6 problem. I'm trying to figure it out.

**Comment by Krands** [comment]
I +1 this issue.

I have this same behaviour, except that my NC server is in the same WLAN than my phone (Android Marshmallow). 

There is also a IPv6 address along the IPv4. However, when I connect at my girlfriend's house, there is no problem, thought. 🤔

---

## Actual behaviour

    If i use WiFi, i cant login or download anything.
    If i use mobile data, all works fine

## Expected behaviour

    Login and Download / upload files with WiFi

## Steps to reproduce

    Activate WLan
    Try to Login
    Try to download a file

## Environment data

Android version: 6.0.1 + 6.0

Device model: BQ Aquaris X5 Plus (not linked)

Stock or customized system: Stock

Nextcloud app version: 1.4.0 RC4

Nextcloud server version: 10.0.1 (stable)

**Comment by ralftar** [comment]
@Hoerli1337 Any success on figuring it out? I am experiencing the same behavior.

**Comment by JSoko** [comment]
2 posible reasons:
Ipv6 => switch to ipv4
Bruteforce => have a look into the bruteforcetable of your database...

**Comment by ralftar** [comment]
@JSoko Thanks! It was related to the anti brute-force mechanism. It was triggered after changing credentials. I suppose a fix would be to drop the app's intensive connect attempts upon wrong credentials.

**Comment by MRZA-MRZA** [comment]
I can't connect to nextcloud server in ipv6 networks. This makes android app pretty useless :(

**Comment by AndyScherzinger** [comment]
@MRZA-MRZA sorry to hear that, can you run an IPv4 address besides the IPv6?

**Comment by MRZA-MRZA** [comment]
@AndyScherzinger I have ipv4 and ipv6 addresses. Domain also have ipv4 and ipv6 addresses. By default it resolves with ipv6 address therefore nextCloud app can't connect :(

**Comment by elforesto** [comment]
This issue also exists in the OwnCloud Android client (fails to connect when IPv6 is enabled). I'm guessing it has carried over from there.

**Comment by AndyScherzinger** [comment]
@elforesto correct, the webdav library in use can't yet handle IPv6 :/

**Comment by orf** [comment]
I am still experiencing this, even on the beta release. My domain uses ipv4 and there are no entries in the bruteforce table.

I'm running it on a non-standard port (1339), and I'm using let's encrypt. Works fine over 4g, no connection via my WiFi. No logs.

**Comment by xXSTrikeXx** [comment]
Do you use Dns or DynDns?

**Comment by orf** [comment]
Nope, It works when I connect to a free WiFi service. The only thing I can
think of is that I have the desktop client running on my laptop.

I'm willing to help debug this if you have any more questions.

**Comment by MRZA-MRZA** [comment]
I fixed this problem by enabling ipv6 on my web server. Looks like nextCloud client tries to connect to server's ipv6 address on ipv6 network but not to ipv4 address if ipv6 connection fails.

**Comment by orf** [comment]
Oh, so my router is giving my phone an ipv6 address so the client attempts
to connect via ipv6?

But my DNS records don't have an ipv6 address associated with them at all.
I'll give it a try though.

**Comment by orf** [comment]
Yeah, so simply exiting the NextCloud app on my Desktop allows my Phone to sync correctly. I'm guessing its something to do with the server....

Please fix this.

**Comment by xXSTrikeXx** [comment]
@orf It´s android section here, not the server section. In the past it helped me to add the domain and LAN-Ip to the file /etc/hosts. If you have a DNS Server in your Lan add the ip there. E.g. 
domain.com 192.168.178.13
So the router´s DNS (my fritzbox includes a local DNS) needs to know the internal Ip of the nextcloud instance to be able to connect the nextcloud instance. Only using DNS causes, that the client connects over WAN-Ip and not LAN.

**Comment by jajaX** [comment]
Hi (sorry for my bad english !)

I have got this issue since a few months too !!

I solved it now :D

under configuration on my freebox, I activate "forcer la réponse en broadcast" (force answer in broadcast). now my nextcloud android can connect with my nextcloud server on wifi to my home !!!!

regards
jajaX

**Comment by jajaX** [comment]
after new problem
I test other thing.
I enable dhcp ipv6 on my freebox
nextcloud android works back again :)
