### ISSUE TITLE
Automatic upload does not work

### ISSUE THREAD

**Issue by itsmeJ4Y** [nextcloud/android#4271]
### Actual behaviour
- Tell us what happens
**The automatic upload does not work.** 

### Expected behaviour
- Tell us what should happen
**Since I'm not familiar with app development, I can't answer the question. I hope that the bug will be fixed as soon as possible. The app is not usable.** 

### Environment data
Android version:
**9**

Device model: 
**Samsung Galaxy S9+**

Stock or customized system:
**The phone/cloud and app is in its original state.**

Nextcloud app version:
**3.7.0**

Nextcloud server version:
**16.0.3**

**Comment by MichaelHeimann** [comment]
Same thing here. Version 3.7.1
Added a folder to sync and it doesn't sync the pictures. 
New pictures are synced btw, but the existing picture library is left on the device. No refresh or scan folder option.
Device is one plus 5
OS is android 9

**Comment by AndyScherzinger** [comment]
@MichaelHeimann existing pictures aren't synced since that hasn't been implemented yet so that isn't a bug!

**Comment by AndyScherzinger** [comment]
@itsmeJ4Y did you deactivate any Samsung battery optimizations for the Nextcloud app? Else it won't work since Samsung has an extremely aggressive 'optimization' killing the app and its background processing...

**Comment by MichaelHeimann** [comment]
Ah, I see. I do remember in old versions that you could do it and also there was a rescan option.
So 'hasn't been implemented' is a little strange to me.

But ok, maybe during redo of autoupload in 2 this was changed.

Technically speaking a feature request then.

But to be clear: the whole autoupload feature is completely useless if it doesn't sync existing files.
So whoever decided to implement it that way should go to the corner of shame stay there until it's fixed.

**Comment by itsmeJ4Y** [comment]
@MichaelHeimann I agree 100%

**Comment by AndyScherzinger** [comment]
What you have been looking for is described within #285

@tobiasKaminsky feel free to take over. I don't spend any more time on people that disrespectful regarding their language.

**Comment by itsmeJ4Y** [comment]
I have already set the app to "Not optimized" in the Samsung settings. The app "NextCloud" is therefore NOT considered and is not closed in the background! 

I created a folder "Backup" in my cloud and linked it to the folder "Instagram". I've made all the settings so that you can upload without WLAN. I manually put an image in there AND additionally posted an image to Instagram (2 new images in the folder). Nothing is uploaded and that's a fact! I tried it again, it just doesn't work!

**Comment by itsmeJ4Y** [comment]
......... so this app doesn't work at least on the S9+ (Samsung). Apart from the fact that it is not logical that existing images/documents are not taken into account.

**Comment by itsmeJ4Y** [comment]
... which I also noticed (but I don't know if it's the NextCloud icon): Every now and then a small "n" appears in the bar at the top (on my mobile phone). That disappears immediately again. If it has nothing to do with NextCloud, this can be ignored. I haven't found out what this has to do with yet. I can imagine that NextCloud tries to synchronize documents. Apparently it doesn't work.

**Comment by kw5sk8d** [comment]
Same issue

Samsung S8 active 
Android 9
NC 3.7.2
NCS 16.0.3

**Comment by tobiasKaminsky** [comment]
> Logs seem to have this similarity; unclear if it's related
> "Exception":"Sabre\DAV\Exception\BadRequest","Message":"expected filesize 22284265 got 4472832"

This seems like #4005
