### ISSUE TITLE
Odd Activities Behavior

### ISSUE THREAD

**Issue by Boballen55** [nextcloud/android#4272]
### Actual behaviour
If I click on the Activities menu options it loads a recent list of activities and all looks well. If I scroll down it attempts to pull more history from the server but instead adds the same bit of entries to the bottom over and over.

### Expected behaviour
Ideally new data would be pulled from server. Alternatively just the limited set of initial data would be logical if limited. 
 
### Steps to reproduce
1. Install Android 3.7.0
2. Connect to server 
3. Open activities and keep scrolling down, the entries should repeat 

### Environment data
Android version: 8.1.0

Device model: Nexus 6P

Stock or customized system: Lineagos

Nextcloud app version: 3.7.0

Nextcloud server version: 15.0.10snap2

### Logs
Where do I find my Nexcloud log in the snap version?

**Comment by tobiasKaminsky** [comment]
@Boballen55 thanks for reporting.
This have been slipped through, but now I fixed it.

In https://github.com/nextcloud/android/pull/4419 you will soon find a APK you can test, if you want.
