### ISSUE TITLE
Cannot download aac files

### ISSUE THREAD

**Issue by mjlabe** [nextcloud/android#4273]
### Actual behaviour
- (aac file) Download failed. Does not exist on server. File is accessible via web though. 

### Expected behaviour
- download 
 
### Steps to reproduce
1. Upload aac
2. Attempt download 

### Environment data
Android version: 8.0

Device model: Motorola Z2 play

Stock or customized system:stock

Nextcloud app version:3.7.0

Nextcloud server version: latest

#### Web server error log
```
Unavailable 
```

#### Nextcloud log (data/nextcloud.log)
```
Unavailable 
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
I do not have a aac file, but as it some audio file, it tries to stream it and this seems to fail.
You can click on three dots next to the file and either choose "stream with external app" or download.
