### ISSUE TITLE
"Shares" is broken

### ISSUE THREAD

**Issue by pilsnerbeer** [nextcloud/android#4274]
### Actual behaviour
The Web version of NC shows me I am currently sharing 2 files - Android app disagrees and shows nothing instead. Even if I try share something from the app, it will not appear in there (web synces immediately and shows the item in "Shares").

This section is also prone to another bug - go to Shares, pull-to-update and you will see all of your files in your NC (instead of only shared ones).

### Expected behaviour
All shared items must appear in the "Shares" section of the Android app. For pull-to-update: download the newest share data and update list.
 
### Steps to reproduce
1. Have some files shared (with somebody, or just link)
2. Make sure those shared files are visible under Shared in the web app
3. Go to Android app, notice there are "No Files" under the "Shared" section.

### Environment data
Android version: 9
Nextcloud app version: 3.7.0
Nextcloud server version: 15

**Comment by tobiasKaminsky** [comment]
The "shared" view got an update for 3.8.0. 
You can test RC1 already via Google Play Store Beta.

**Comment by tobiasKaminsky** [comment]
PR is: #4249

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky like I wrote in another issue, shared is empty for me too. Running master (3.8.0RC2) and 16.0.4 so this issue is still present!

**Comment by tobiasKaminsky** [comment]
Can you have a look in logcat if there is an error?
Or if it just takes waaay too long?

**Comment by pilsnerbeer** [comment]
Myself I found no errors in the log and there seem to be no loading going on.
