### ISSUE TITLE
Auto Upload one OnePlus 6T doesn't work

### ISSUE THREAD

**Issue by JulianSchneider** [nextcloud/android#4277]
### Actual behaviour
Enabled Auto Upload, added to list of exceptions. Nothing happens.

### Expected behaviour
Files are uploaded 
### Steps to reproduce
Enable Auto Upload on a onePlus 6T

### Environment data
Android version:
9
Device model: 
OnePlus 6T
Stock or customized system:
Stock
Nextcloud app version:
3.7.0
Nextcloud server version:
Newest

**Comment by AndyScherzinger** [comment]
Hi @JulianSchneider,

did you take pictures _after_ you enabled the auto upload?

**Comment by JulianSchneider** [comment]
Hi @AndyScherzinger 

Yes, tried that as well. Didn't work at fist. Retried just now and that worked. Not sure if detection is spotty or it just took some pictures to register. 
Are there plans to enable upload for existing images? I assume I can just upload them manually.

**Comment by AndyScherzinger** [comment]
> Are there plans to enable upload for existing images? I assume I can just upload them manually.

For now you'll need to upload thhem manually. #285 describes the feature of also adding the bits and pieces to upload existing images which hasnn't been implemented yet. It is on our agenda but nobody found the timie to work on this just yet.

Auto uploads, depending on the deivce/Android-version/OEM might take up to 15 minutes before being triggered after a picture has been taken.
