### ISSUE TITLE
Reconfigure stale-bot

### ISSUE THREAD

**Issue by 1989gironimo** [nextcloud/android#4279]
### Is your feature request related to a problem? Please describe.
I'm always frustrated when a issue gets closed, even if it's confirmed by a dev or supportteam member and the issue is obviously not addressed by one or more patches.

### Describe the solution you'd like
Reconfigure stale-bot in such a way, that it doesn't automatically close issues. It should just flag them as stale and a supportteam member should have an oversight, which ticket should really be closed (for instance, bad description, probably fixed issue, etc.)

**Comment by tobiasKaminsky** [comment]
The idea is that each bug gets tested/reproduced and if it is indeed a bug, it gets label "approved", which then will prevent stale bot from closing it.

The reason for stale bot is that many many issues are only one time issues and can not be reproduced as of different reasons (specific device, personal cloud misconfiguration, …) and if the reporter does not reply, the stale bot can close it (after a warning).

If you have any issue that you want to have re-open, just ping in the corresponding issue and it will of course get re-opened / trying to get fixed.

**Comment by lemmy04** [comment]
> [...] if the reporter does not reply, the stale bot can close it (after a warning).

and what about all those issues where the **developers** never reply?
