### ISSUE TITLE
[InstantUpload] Re-upload an InstantUpload-ed image fails

### ISSUE THREAD

**Issue by Wikinaut** [nextcloud/android#428]
* Nextcloud server 10.0.1
* Debian 8
* Nextcloud client Android 1.3.1 on Android 6.0

After an InstantUpload (SofortUpload) of an image I cannot upload the image again to my cloud account, not even to another directory like "transfer".

**Comment by tobiasKaminsky** [comment]
This will be fixed in 1.4.2. 
If you then still experience this issue, please reopen.
