### ISSUE TITLE
Says falsely «no internet connection»

### ISSUE THREAD

**Issue by stemy2** [nextcloud/android#4280]
Hello,

I can't download anything because according the app, there's no internet connection. But actually, the connection works well, and i can access to my nextcloud server with a web browser and download any file.

**Comment by tobiasKaminsky** [comment]
Hm. This sounds strange.
Can you create us a test account, test if the problem occurs also there and if so send the credentials to tobias at nextcloud dot com with a reference to this issue?

**Comment by stemy2** [comment]
There is no such error anymore.

**Comment by stemy2** [comment]
The error is back again.

**Comment by kyds3k** [comment]
I am getting this error now. Version 3.3.4.1, constant failure to upload, but it's reachable via browser.
