### ISSUE TITLE
"Details" on a photo does nothing

### ISSUE THREAD

**Issue by pilsnerbeer** [nextcloud/android#4285]
### Actual behaviour
Trying to view "details" from thee-dot menu with a picture opened in "photos" section of the app does nothing - it closes the currently viewed picture and that's about it.

![Screenshot_2](https://user-images.githubusercontent.com/36133540/62213440-32830800-b3a3-11e9-9eeb-2e75ffed9ee0.png)

### Expected behaviour
View details/exif data about a picture
 
### Steps to reproduce
1. Go to gallery
2. open a pic
3. menu -> details

### Environment data
Android version: 9

Nextcloud app version: 3.7.0

Nextcloud server version: 15

**Comment by AndyScherzinger** [comment]
@ezaquarii @tobiasKaminsky I can reproduce this with latest master (well, with the dark theme branch...) also running Android 9 (Lineage) and a v16 server.

**Comment by tobiasKaminsky** [comment]
Tested and seems to be fixed.
