### ISSUE TITLE
Viewing images is very slow

### ISSUE THREAD

**Issue by arnowelzel** [nextcloud/android#4289]
### Actual behaviour
When opening an larger image (5248x3936 pixels) in a folder with 5 or more other images like this the app often becomes very slow and unresponsive. Zooming the image or swiping from one image to the next takes several seconds.

Using the local gallery app of the device with the same images downloaded before works without any delays. It also does not change when all the images are downloaded in the Nextcloud app first.

### Expected behaviour
When opening an larger image (5248x3936 pixels) in a folder with 5 ore more images like this, the image is displayed and one can zoom or swipe to the next image without noticable delays (except the time needed to download an image).
 
### Steps to reproduce
1. Open a folder with at least 5 images where each image is about 5248x3936 pixels
2. Open one of the images, so it will be downloaded and opened in the gallery view
3. Try to zoom the image or swipe to the next one

### Environment data
Android version: 8.1

Device model: Sony Xperia Z3 Compact

Stock or customized system: Customized (CarbonROM 6.1)

Nextcloud app version: 3.7.1

Nextcloud server version: 16.0.3

**Comment by tobiasKaminsky** [comment]
Hm.
Maybe this is due to your phone? I have no idea how good this is.
I tested it with a rather old Samsung S5 Neo:
- 3008x2000px, 4Mb
- 8000x5210, 14Mb
- 10109x4542, 15Mb
- 7819x8897, 20Mb
- 17446x500, 17Mb

The last two took ~2s too load, but then zooming and scrolling is without lag.

As I found the images on wikipedia/google I could give them to you to test them or vice vera.

**Comment by arnowelzel** [comment]
As I said: the gallery app on the phone works fine with the same images. It's just the Nextcloud app which behaves like this. Even in a mobile browser the gallery view of my Nextcloud server works better than the app.

However - when I download the images first (so they get a green check mark in the list) then opening, zooming etc. works fine. But as soon as only one image has to be loaded from the server (using a 100 MBit/s DSL connection and 5 GHz Wifi), the whole app get's really sluggish - not only swiping images is slow, but even opening the main menu is slowed down. On the server itself within a browser the gallery works fine without any delays.

And another finding: even after viewing one or more images it seems the images don't get downloaded either - at least the files don't get a green checkmark in the list. Where do the image files go then?

**Comment by tobiasKaminsky** [comment]
> But as soon as only one image has to be loaded from the server (using a 100 MBit/s DSL connection and 5 GHz Wifi), the whole app get's really sluggish - not only swiping images is slow, but even opening the main menu is slowed down. On the server itself within a browser the gallery works fine without any delays.

Hm. Never experienced such a thing. The download is done in background and should not delay UI, but this is up to Android handling it correctly.



> And another finding: even after viewing one or more images it seems the images don't get downloaded either - at least the files don't get a green checkmark in the list. Where do the image files go then?

If you click on an image a screen adapted resized images is downloaded to cache. So if the original image 14mb you download ~80kb of preview in cache.
Therefore you do not see a "green checkmark" as this indicates the downloaded file.

What happens if you have all 5 images as preview available and then swipe through them. Is it then still sluggy?

**Comment by arnowelzel** [comment]
Yes, it stays sluggy. It only gets usable when I download the images first. But then the app works perfectly fine.

**Comment by tobiasKaminsky** [comment]
> Yes, it stays sluggy. It only gets usable when I download the images first. But then the app works perfectly fine.

Hm. Then I am totally out of clue :/
I would have expected that with preview viewing the image is better as less memory is needed.



> Edit: well - as one can always zoom the images, even when they are not downloaded first, the original size image has to be somewhere as well.

This is a wrong assumption, we allow to zoom into 2x even on a resized image.
With original image you should be able to zoom into more.

**Comment by arnowelzel** [comment]
Another test: downloaded the images first and then deleted the local copies again. After this, the gallery works fine, even if the pictures are not locally available any longer. So it looks like there is a problem with the caching of the preview images. If I have more time for investigation I'll have a look into the code as well.

**Comment by tobiasKaminsky** [comment]
When you delete a downloaded image, a screen adapted image will previously be generated, so that you still can see a "fullscreen" version.

You are refering to gallery: this is the preview image within our app, where you can swipe left/right to see the images, just to be sure?

**Comment by arnowelzel** [comment]
Yes, with "gallery" I refer to the preview image in the app which I can swipe left/right to change between the images. This works fine when images got downloaded once - even after deleting the local copy. But as long as the images never got downloaded, opening the preview causes the whole app to become sluggish, also when closing the preview and opening it again with the very same images.

**Comment by tobiasKaminsky** [comment]
But the screen adapted previews are shown?
On a first start you see square thumbnails, which then get replaced by the previews. It should always be fullscreen (or at least one side should fit the full width/height)

**Comment by arnowelzel** [comment]
yes, the previews are always adapted to the screen. it's only sluggish, if the images have never been downloaded before.

**Comment by tobiasKaminsky** [comment]
Can you maybe do a video of this?
Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

**Comment by arnowelzel** [comment]
You will find everything here: https://nextcloud.0x0c.de/s/pS7QbJySdBmbAYE

image-preview-sluggish.mp4 - this is the sluggish preview of images which never have been downloaded before. The first time you can see how the preview images are loaded. But even when opening the preview the second time it doesn't get better.

image-preview-normal.mp4 - this is a preview of the images after downloading and then after deleting the local copies. The preview behaves as expected - no delays, even after the local copies got deleted.

logcat.txt contains the logcat output of during the sluggish operation. This is a notable message:

```08-05 14:18:39.379 27832 27832 D FileActivity: Operations service connected
08-05 14:18:39.380 27832 27832 D PreviewImageActivity: Simulating reselection of current page after connection of download binder
08-05 14:18:39.380 27832 27832 D PreviewImageActivity: Upload service connected
08-05 14:18:40.027 27832 27832 I Choreographer: Skipped 36 frames!  The application may be doing too much work on its main thread.
08-05 14:18:40.457 27832 27832 V FileDisplayActivity: onSaveInstanceState() start
08-05 14:18:40.457 27832 27832 D FileDisplayActivity: onSaveInstanceState(Bundle) starting
08-05 14:18:40.458 27832 27832 D ExtendedListFragment: onSaveInstanceState()
08-05 14:18:40.458 27832 27832 V FileDisplayActivity: onSaveInstanceState() end
08-05 14:18:40.822 27832 27832 D FileDisplayActivity: onStop() ending
08-05 14:18:44.100 27832 27832 I Choreographer: Skipped 49 frames!  The application may be doing too much work on its main thread.
08-05 14:18:45.174 27832 27832 I Choreographer: Skipped 64 frames!  The application may be doing too much work on its main thread.
08-05 14:18:45.906 27832 27832 I Choreographer: Skipped 43 frames!  The application may be doing too much work on its main thread.
08-05 14:18:49.222 27832 27832 I Choreographer: Skipped 41 frames!  The application may be doing too much work on its main thread.
08-05 14:18:50.036 27832 27832 I Choreographer: Skipped 47 frames!  The application may be doing too much work on its main thread.
08-05 14:18:50.752 27832 27832 I Choreographer: Skipped 42 frames!  The application may be doing too much work on its main thread.
08-05 14:18:51.155 27832 27832 D PreviewImageFragment: onStop starts```

Whatever the app does in this moment - something is going on in the background which does not happen, if the images have been downloaded once. Even if the local copies get deleted, it still behaves normal.

**Comment by tobiasKaminsky** [comment]
Thanks for your videos, this helps a lot to understand the problem.

It might be that your cache is so slow that it slows down the app.
Then I still wonder why it does not happen after deleting the file.

Can you try this:
- open up resized images
- swipe through some images, see it is sluggy
- go back to file list
- open up the same images again, in the same order

Please do this with complete new images, so that there is no cached entry.

**Comment by arnowelzel** [comment]
Sorry, I was busy with other things - but I tried the suggested procedure with the same results: as long as the images did not get downloaded the whole app is very sluggish in the image preview.

**Comment by sosed213** [comment]
The problem with slow loading of image previews in the Android application persists to this day.
Nextcloud Server 21.0.3 and Nextcloud 22.0.0.
Nextcloud App for Android 3.16.1

Google Pixel 3 smartphone, Android 11.

Slowly works over wifi in the local network with the Nextcloud server, and over the LTE network.

**Comment by rightsaidfred99** [comment]
4 years later and it is still and issue. The app never preloads so every swipe we have to wait for the app to download
