### ISSUE TITLE
New NextCloud App, data inaccessible

### ISSUE THREAD

**Issue by SaittamW** [nextcloud/android#429]
### Actual behaviour
Today i installed the new version of NextCloud App. After starting the app and migrating to the new version i can't acces my music and photo's/pictures anymore which i have downloaded with the Nextcloud App on my phone (Nexus 5x - Android 7.1.1).

### Expected behaviour
Normally i upload pictures and music with my PC to my NextCloud server and download them on my phone. The files come automatically visible in Google Photo's and Play Music app. 

For now: i've installed the OwnCloud-app also. That fixed the problem temporary... :(
 
### Steps to reproduce
1. Install new version of the app & migrate (Settings -> path (unknown) -> select path: (only one option shows up) /storage/emulated/0/Android/data/com.nextcloud.client/files)
2. Open Photo-app or Play Music-app
3. No data (photo's/pictures/music) visible

### Environment data
Android version: 7.1.1
Device model: Nexus 5x

Stock or customized system: Stock

Nextcloud app version: 1.4.0

Nextcloud server version: 10.0.0.1

**Comment by benbrummer** [comment]
# Environment data
Android: 5.1
Device model: Moto G
Upgraded from 1.3.1 to 1.4
Device has no sdcard

# After Upgrade:
Files are visible as before in different Gallerie Apps
Settings:
Storage Path: Unknown

Wanted to correct "unknown"
Only Option for Storage Path "/storage/emulated/0/Android/data/com.nextcloud.client/files"
=> Files disappeared from all other Apps

Except of that everything is working, files are visible at least in the nextcloud app

**Comment by greenmanspirit** [comment]
##Environment Data
Android: 6.0
Phone: LG G4
App: 1.4
Server: 10.0.0.1
Using SD Storage

##After Upgrade
I changed storage to my SD card and I can see the pictures and music in my file manager however, Music and Gallery cannot see the files.

**Comment by xraMsamohT** [comment]
> Files disappeared from all other Apps

> Music and Gallery cannot see the files.

It's because of the `.nomedia`file in `/Android/data` folder. 

Solution: Either a complete choosable path or `/Nextcloud` on internal or external storage, as before.

**Comment by nwl** [comment]
I am not given a choice about choosing the Storage Path. 

Is there a way to remove the .nomedia file from /Android/data ?

**Comment by SaittamW** [comment]
Will this problem be solved? And when? For me the app is unusable anymore.

**Comment by xraMsamohT** [comment]
@nwl The removal of the `.nomedia` file is not a proper solution. Afterwards all images in the cache folders of other apps are visible in the Gallery.

**Comment by RogerSik** [comment]
Will this behavior changed in future? Photos I don't need (doubled) in my photo app. But my Music I want to have access.

**Comment by puchrojo** [comment]
@nwl I try with remote of .nomedia file on /storage/emulated/1/Android/data/ and nothing change. The pictures and mp3 are not sow on gallery or music program.

**Comment by JSoko** [comment]
@puchrojo thats by android design...
But Fastimageviewer can handle the files in the nextcloud folder...
https://play.google.com/store/apps/details?id=com.tdfsoftware.fiv

**Comment by JSoko** [comment]
@RogerSik have a look at #285 and you can see, what is planed...

**Comment by AndyScherzinger** [comment]
This will likely be made possible again in the future but I don't have any specific dates yet. As for images the upload duplication will be gone with the next release and you can keep the files in the original folder and not move it to Nextcloud's storage on the phone.

**Comment by tobiasKaminsky** [comment]
The external storage path will be /SD/Android/media and not "/SD/Android/data" to allow other apps to access the download files.
This will be part of the next version.

**Comment by corppneq** [comment]
@tobiasKaminsky What is the release data?

**Comment by AndyScherzinger** [comment]
today/tomorrow will be the release of RC1 on Google Play. For f-droid we need to wait for them to update their build pipelines regarding the build tools. Not sure when that will be done but they already started working on it.
