### ISSUE TITLE
AutoUpload not working with multiple photo's

### ISSUE THREAD

**Issue by SaittamW** [nextcloud/android#430]
### Actual behaviour
Finally: InstantUpload is back :D But... after taking multiple photo's (example: 3 photo's in 2-3 seconds) only the first photo will be uploaded when i'm connected to wifi (only upload with wifi-connection turned on). When i'm not connected, all photo's will be uploaded when i connect to wifi. The photo's won't also not appear in Uploads in the app.

### Expected behaviour
Upload all the photo's i shoot, when i'm connected to wifi or not.
 
### Steps to reproduce
1. Install new version of the app
2. Take photo's (fast after each other)

### Environment data
Android version: 7.1.1
Device model: Nexus 5x

Stock or customized system: Stock

Nextcloud app version: 1.4.0

Nextcloud server version: 10.0.0.1

**Comment by mario** [comment]
Please try newest beta.

https://github.com/nextcloud/android/raw/beta/apks/latest.apk

Thanks!

**Comment by tobiasKaminsky** [comment]
@SaittamW does it work for you now?

**Comment by mario** [comment]
Dear users,

thank you for your patience. After lots of work, we’re super excited to be able to give you a test version with new auto upload implementation. Keep in mind we will only accept bugs related to Auto Upload in this APK, as other things might be broken.

https://cloud.nextcloud.com/s/ftZraTruRQjTe0R

This is a dev APK so it will not overwrite your existing play store/f-droid APK unless you’re already running dev version. Also, you might need to remove your existing dev version before installing this one.

Explanation of the current functionality:
- added support for custom folders
- separated image and video folders
- checks for new files happens every 15-20 minutes
- automatic retry every 15-20 minutes or when you force close/open the app
- automatic pause once network is changed (untested!)
- significantly less battery usage

All and any testing is more than appreciated, especially with large and ever-going files like Videos. (like, try to record a 30 min video).

Let me know if you’ve got any questions.

Cheers,
Mario

**Comment by tobiasKaminsky** [comment]
No response within the last month, therefore closing.
Please feel free to reopen with additional infos, if the problem still exists.
