### ISSUE TITLE
PIN can't be reset if forgotten

### ISSUE THREAD

**Issue by patlecat** [nextcloud/android#4306]
### Actual behaviour
- When a PIN was used in the Android app but later forgotten then there's no way at all to reset it. Re-installing it also won't work, the PIN seems still stored somewhere. Or maybe only that there was a PIN set but now it's lost after the reinstallation and even entering the correct PIN won't work anymore?

### Expected behaviour
- I expect a reset function that either sends an eMail for a reset or that interacts with the server admin so that he can unlock the PIN and allow a reset thereof (fingerprint isn't available). This way the app remains unusable forever.

### Environment data
Android version: 9.0

Device model: Huawei Y6

Stock or customized system: stock

Nextcloud app version: 3.7.1

Nextcloud server version: 16.0.1

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky wouldn't the pin be removed (including any data) when you wipe the app's data (probably twice) using Android settings - apps - clear data (2x)

**Comment by tobiasKaminsky** [comment]
No, we have a special remove data which prevents pin from being deleted.
Only way is (currently) do re-install the app.

PIN is only a local protection system, like in an online banking app, it is independent from the server.
As there is no data within our app that is not on server, you can safely re-install the app. Only downside is that you will loose all downloaded files, but they are on server.

**Comment by patlecat** [comment]
Maybe you need to think what the order of security is here. The 4 digit PIN isn't the highest oder protection step! It's just a **convenience feature** for users - and btw you should make it 4-8 digits long at least.
The highest order protection is the password to the vault. If I use something like a 25 alphanumeric pwd it is my strongest line of defense. If the PIN gets lost/forgotten, then offering to erase it won't, of course, also override my very secure password! It should however ask the user to re-enter that password before being able to set a new PIN. That at least would keep the data clear of access. So by resetting the PIN you have to clear the password at the same time too of course!

And if I may add, if you wanted to offer a really good security, then you would let the admin of the server reset the PIN as well as the password for a user. Or at least make this an optional feature.

And sadly the re-installation of the app doesn't work on that phone, it has been tried several times but the PIN was still asked afterwards and could not be reset. Apparently you do not clean all the data on the phone properly. Please check that.

**Comment by ezaquarii** [comment]
The only purpose of the PIN is too stop some 3rd party to accidentally skim over your files if they get accidental, **temporary** access to unlocked phone. It's good of typical office environment, with poorly motivated, unskilled, random passerbys.

PIN does not offer strong security for few reasons:

1. files on the phone are not encrypted and can be retrieved, usually by just plugging the phone as USB drive
2. In case phone being stolen, the only real line of defense is your full disk encryption
3. even if the pin was used as a real security measure, it provides pathetic 30-ish bits of entropy; whch is crackable on your typical laptop in few seconds

Generally making PIN feature any more complicated is counter-productive.

App reinstallation should remove all application data. Are you sure you uninstalled the application completely? Installing another version over previously installed one does not remove settings.

**Comment by patlecat** [comment]
@ezaquarii 
As I described the security level of the PIN is certainly way below the password so a reset should be offered.
Yes it was uninstalled and then reinstalled.
