### ISSUE TITLE
Deleting files from the app is incredible slow when marking multiple files

### ISSUE THREAD

**Issue by FelixBuehler** [nextcloud/android#4307]
### Actual behaviour
- When deleting files from the app, it takes around 2 seconds per file to delete it when you use the option to mark multiple files and then press "delete" once for all the marked files.
It's deleting every file per se. Feels like it sends a new request for each file to delete it and not just send like a reguest "Delete files [1, 2, 3, 4]"

### Expected behaviour
- I check multiple files, click delete and after an appropriate amount of time (like 10 seconds or so), all files should be deleted at once.
 
### Steps to reproduce
1. Have a folder with multiple files (5+ is good for testing. Just use some empty .txt-files)
2. Mark all or some of the files.
3. Click "delete" to delete the marked files

### Environment data
Android version: 8.0.0

Device model: HTC 10

Stock or customized system: Stock

Nextcloud app version: 3.7.1

Nextcloud server version: 16.0.3

#### Web server error log
```
No error log
```

#### Nextcloud log (data/nextcloud.log)
```
Nothing to see in the log.
```

**Comment by FelixBuehler** [comment]
Can no one reproduce the problem?

**Comment by dan0xii** [comment]
Yes, this happens to me also. It seems the app waits for confirmation from the server that the file was deleted before moving on to the next which can be slow if your server or connection isn't particularly fast -- both true in my case.

**Comment by tobiasKaminsky** [comment]
You are right, this is exactly what is done here.
The reason is that webdav only allows to do a per file operation, that means that we indeed have to do it one by one.

@nextcloud/server-triage do you have a different approach on server?

**Comment by blizzz** [comment]
No, the web UI also deletes one per request.

**Comment by tobiasKaminsky** [comment]
Then there is nothing much we can do…
