### ISSUE TITLE
Ask if existing file should be replaced

### ISSUE THREAD

**Issue by joekerna** [nextcloud/android#431]
### Actual behaviour
If I upload a file that already exists in my nextcloud it automatically creates another copy with the name and a (2) appended.

### Expected behaviour
I should be asked if I want to replace the existing file or create another copy
 
### Steps to reproduce
1. Upload file (for example: photo.jpg)
2. Upload the same file again to the same directory

### Environment data
Android version: 6.0

Device model: Huawei P9

Stock or customized system: Stock

Nextcloud app version: 1.4.2

Nextcloud server version: Nextcloud 11.0.2 RC
#

**Comment by tobiasKaminsky** [comment]
This is a good idea, but only for manual upload as the autoupload is done in the background and can annoy users if the get such a dialog.
For images both thumbnails, local and remote, should be shown.
@jancborchardt @mario @AndyScherzinger

**Comment by AndyScherzinger** [comment]
agreeing with @tobiasKaminsky onyl thing we could think about is if some kind of conflict resolving strategy could be chosen by the user per folder-pair as is "always override", "discard and keep server version", etc.

**Comment by mario** [comment]
We can do this for auto upload as well - just show it in the Activity screen (which will be done for 1.5)

**Comment by tobiasKaminsky** [comment]
So for autoupload the conflicting file would be paused until the user resolves the conflict? Then this should be shown as a notification, which then leads to the activity screen. Good idea 👍

**Comment by joekerna** [comment]
Can there be some kind of diff? In that case the decision is clear and there is no user-interaction necessary, right?

**Comment by nickvergessen** [comment]
Bump, see the 2 linked issues above for more details and usecases

**Comment by caco3** [comment]
Please also consider the usecase as documented in https://github.com/nextcloud/android/issues/1239

**Comment by Belphemur** [comment]
Any news on this issue ?

**Comment by Feederhigh5** [comment]
I think the conflict message has been implemented by now, because I have the problem that my whatsapp back-up files are not automatically uploaded and replaced anymore.
Instead, the nextcloud android app asks me every time, whether I want to replace it or add it with a modified name.
As proposed in 2017 by AndyScherzinger, I would love to configure the auto-upload settings for this specific folder to "always override".
(I thought if you upload something with the same name, nextcloud automatically has a version history, in case you need to restore a specifc version of a file?)

**Comment by AndyScherzinger** [comment]
> As proposed in 2017 by AndyScherzinger, I would love to configure the auto-upload settings for this specific folder to "always override".

There is a PR already: #5810

**Comment by joshtrichards** [comment]
This was implemented awhile ago and is the current behavior.
