### ISSUE TITLE
Log: do not quit view after reset

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#4311]
### Actual behaviour
- Log view quits after clearing

### Expected behaviour
- only clear log, but do not exist
 
### Steps to reproduce
1. go into log view
2. click on clear logs

**Comment by AndyScherzinger** [comment]
could this be fixed within @ezaquarii's PR maybe?

**Comment by tobiasKaminsky** [comment]
The PR in question (https://github.com/nextcloud/android/pull/4275) is already merged.

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger I think you misunderstand me.
If you right now (with #4275) click on "clear logs" the activity will exit and you see settings again.
Previously behaviour was that the empty log is shown (the activity is not closed).

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky yes, I was refering to #4309 :)
