### ISSUE TITLE
Misuse of AsyncTask

### ISSUE THREAD

**Issue by pangeneral** [nextcloud/android#4318]
According to our research, there are misuses about the following AsyncTask class:
1. `com.owncloud.android.ui.activity.ManageSpaceActivity.ClearDataAsynTask`
2. `com.owncloud.android.ui.activity.ErrorsWhileCopyingHandlerActivity.MoveFilesTask`

The problems are:
1. These classes are inner classes of Activity, which means it holds strong reference to Activity. It will cause memory leak when the Activity is destroyed and the AsyncTask did not finish;
2. The instance of these classes are not cancelled before the Activity is destroyed, which can lead to the wrong invocation of `onPostExecute()` if the Activity is destroyed 

I think we can make following changes to fix the misuse problems:
1. `ClearDataAsynTask` and `MoveFilesTask` should be static inner classes
2. Add AsyncTask field in `ManageSpaceActivity` and `ErrorsWhileCopyingHandlerActivity` which refer to AsyncTask object and invoke cancel() in the onDestroy() method if the AsyncTask field is not null.

These are my suggestions above, thank you.

**Comment by ezaquarii** [comment]
@pangeneral Are you interested in working on this? Recently we meged our own async task mechanism and we'd be happy to clean up this area.
