### ISSUE TITLE
Translation of the description of developer functions

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/android#4323]
I suggest adding a translation for the description of developer functions:

- Download latest dev version

- Changelog dev version

![obraz](https://user-images.githubusercontent.com/47037905/63025535-afd17100-bea9-11e9-90ed-e0a72c9b1d23.png)

**Comment by tobiasKaminsky** [comment]
Thank you, I created a PR for it.
It will then be soon on Transifex for translation.
