### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by Aybee2k** [nextcloud/android#433]
### Actual behaviour
When logging in via the Android app, the error always appears: The server takes too long for a response

### Steps to reproduce
We can not say half a day we could use the app and then Suddenly the error.

### Environment data
Android version: 6.0.1

Device model: Moto G4+

Stock or customized system: Stock
Nextcloud app version: 1.4.0
Nextcloud server version:  10.0.1 (stable)

**Comment by tulamidan** [comment]
Same here. Android 7.1 Nextcloud 10.0.1
After trying to change the password I am stuck here.

**Comment by Aybee2k** [comment]
After we have cleared the cache of the APP and the mobile phone has re-started it worked with us.

**Comment by tulamidan** [comment]
I wish it was so easy. Als my desktops can't connect any more. Only the webUI works fine

**Comment by tobiasKaminsky** [comment]
@tulamidan if it also does not work with a desktop client, then it seems more related to the server.

**Comment by madmas** [comment]
Hi, I have the same issue after changing the password on the server. 
It seems like the app has difficulties to invalidate the session and just re-request the password. (Same thing seems to be the case for the desktop sync app : -( ). 
Will try to remove the account and restart the phone.

**Comment by JSoko** [comment]
@madmas Please first have a look in your bruteforce table and delete relateing entries:
You can handle the bruteforcetable with phpmyadmin or in the terminal:

#DON'T FORGET TO MAKE A DATABASE BACKUP!
mysql
USE nextcloud;
SHOW tables;
SELECT * FROM oc_bruteforce_attempts;
# Lists the bruteforce entries
Um einen Eintrag zu entfernen
DELETE FROM oc_bruteforce_attempts WHERE IP="nnn.nnn.nnn.nnn.";
SELECT * FROM oc_bruteforce_attempts;
exit

**Comment by madmas** [comment]
@JSoko Thanks a lot for the hint, wasn't aware of that mechanism! #893  would definitely be an improvement!

**Comment by tobiasKaminsky** [comment]
In the latest dev version there is already https://github.com/nextcloud/android/pull/1099 which will make the login work again.
Please test it and if it is not working, re-open issue.
