### ISSUE TITLE
Delete Auto Upload folders

### ISSUE THREAD

**Issue by trymeouteh** [nextcloud/android#4331]
Please add an option to delete an auto upload folder in the app. I have so many auto uploads for all of my pictures that I would like to remove. I do not want to disable them, I want to delete it.

**Comment by tobiasKaminsky** [comment]
We show all folders with images in it, so that user can enable them.
If you would remove one of those, you would never be able to enable auto upload for this folder again.

@AndyScherzinger

**Comment by AndyScherzinger** [comment]
I'd still like to add a "hide" feature while this would need to be discussed with @nextcloud/designers especially @jancborchardt. A hide feature would not delete the folders which we wouldn't do anyways (as in deleting them from storage) but like other tools with long auto dicovered list (items) I think it be good to have such a possibility (and then via the 3-dot menu do toggle the visibiliyt of hidden items, kind of like SeriesGuide is doing is and I am making heavy use of it as a SeriesGuide user).

**Comment by jancborchardt** [comment]
Sounds good as @AndyScherzinger described.

Then at the end of the list there could be an entry called "Show hidden folders" which toggle shows/hides them all.

**Comment by AndyScherzinger** [comment]
feature description has been done via the last 2 comments, so closing this issue in favor of #3263
