### ISSUE TITLE
Navigation drawer shows full name instead of username

### ISSUE THREAD

**Issue by lbrocke** [nextcloud/android#4337]
### Actual behaviour
When opening the navigation drawer, the displayed Cloud ID doesn't consist of `<username>@<host>` but instead `<full name>@<host>` (see screenshot). In the "Manage accounts" section, the Cloud ID is displayed correctly.

### Expected behaviour
The Cloud ID should contain the username, not the full name. I remember it showing correctly, not sure what update update caused this. Maybe this is somehow related to #157 ?

### Environment data
Android version: 7.1.2 (LineageOS)
Nextcloud app version: 3.7.1
Nextcloud server version: 16.0.4

### Screenshots
![1](https://user-images.githubusercontent.com/14028471/63208767-7f234e80-c0d8-11e9-871a-5d5e1dd5559c.png)
![2](https://user-images.githubusercontent.com/14028471/63208768-7f234e80-c0d8-11e9-83a6-efeda640ff7e.png)

**Comment by ezaquarii** [comment]
@AndyScherzinger 

So this is the guilty party:
```
    public static String getAccountNameDisplayText(Context context, Account savedAccount, String accountName, String
            fallbackString) {
        try {
            return new OwnCloudAccount(savedAccount, context).getDisplayName()
                    + "@"
                    + convertIdn(accountName.substring(accountName.lastIndexOf('@') + 1), false);
        } catch (Exception e) {
            Log_OC.w(TAG, "Couldn't get display name for account, using old style");
            return fallbackString;
        }
    }
```

Get `getName()` returns string in format `login@server.url`. I guess this is what we want here?

**Comment by AndyScherzinger** [comment]
I don't recall anybody changing this

Since we also display the full name, it should then obviously be the username 👍

**Comment by tobiasKaminsky** [comment]
This was changed by me as there was some reports, that this looks weird 
- on ldap, e.g. 2342348972479292@server.com (as it can be any value)
- with email address as username: tobias@kaminsky.com@cloud.server.com (which is done by SimpleSignUp)

Do we need to show this information at all? Isn't this a technical detail, which is fine to shown only in user account info?
Then we could simply show the server.

**Comment by AndyScherzinger** [comment]
I think the issue is that there could be more than one account with the exact same name (first name / last name) while these accoount only differ in their username. It might be an edge case but afaik that is why we actually showed the username.

**Comment by tobiasKaminsky** [comment]
Same Display Name (can happen) on same server? 
Could be…yes.
But then any ldap value / email address will look weird…

**Comment by AndyScherzinger** [comment]
Maybe the @nextcloud/designers have a nice idea how to solve this? :)

**Comment by jancborchardt** [comment]
In the desktop app we do it like this:
- Avatar on top of course
- First row shows the full name if set, user name if not
- Second row only shows the server address

![desktop app accounts](https://user-images.githubusercontent.com/925062/63334752-57ccbb80-c33c-11e9-9c87-738c85d95908.png)

How about that? Will look shorter and less technical. Yes if you have 2 exact same profiles on the same server _if_ the same full name is set _and_ the avatar is the same too then you can not distinguish.
It does show the "user@server" full thing on hover though, but I would say we can leave it out on mobile?
