### ISSUE TITLE
[1.4.0] Uploading pictures to Subfolders are broken

### ISSUE THREAD

**Issue by enoch85** [nextcloud/android#434]
### Actual behaviour
Uploading to subfolders based on year and month doesn't work. It creates the folder, but no picture is uploaded.

The uploads view says that the local file couldn't be found.

"Normal" uploads work (not uploading to subfolders)

### Expected behaviour
Pictures taken with the phone should be uploaded to subfolders if that setting is checked
 
### Steps to reproduce
1. Activate Auto-upload on the Camera folder
2. Tick the box, "Upload to subfolder"
3. Take a photo

### Environment data
Android version:
7.0

Device model: 
Nexus 5x

Stock or customized system:
Stock

Nextcloud app version:
1.4.0

Nextcloud server version:
10.0.1

### Logs
No relevant logs

**Comment by enoch85** [comment]
Sorry for the noise. It works, just had to choose the Upload folder again due to that it's translated. This only concerns the Swedish translations and I will fix it right away.

May be a good thing to have in the release notes.

**Comment by tobiasKaminsky** [comment]
Can you explain what should be shown in the release notes?
And why do you have to re-select the upload folder? This should not be necessary...

But glad that it is working ;-)

**Comment by enoch85** [comment]
FYI this was the translation I did: 
![screenshot from 2016-12-08 21-45-00](https://cloud.githubusercontent.com/assets/4511254/21027090/9b964d50-bd8f-11e6-8b41-ff62e728e1cf.png)


What I had to do was to manually select the uploads folder so that it got a ending / and then it worked.

![screenshot_20161208-214636](https://cloud.githubusercontent.com/assets/4511254/21027156/e6fad9fa-bd8f-11e6-9099-c1f095735264.png)

**Comment by enoch85** [comment]
For the release notes.

- On Swedish devices you have to manually select the "Folder on Nextcloud" so that it gets a ending slash (/) for the uploads to work with subfolders.

But hmm, maybe this isn't a bug after all? As regular uploads work just fine. Maybe it needs the ending slash to understand that it should upload to a subfolder? In that case it isn't a translation error, it's a bug.

The original text should say /Instantuploads/ I think...

**Comment by AndyScherzinger** [comment]
@enoch85 did you check 1.4.0 final again? Just asking since (I am running english) the pathes are correct on my phone and the uploads also work just fine. So the original text with /InstantUpload works .(for me)

**Comment by enoch85** [comment]
I will do one more try on another phone, will open this again if it presits. 

It should work as the translation are exactly the same with the /Instantupload (without a ending slash)
