### ISSUE TITLE
Auto Upload does not Upload existing files

### ISSUE THREAD

**Issue by lu4p** [nextcloud/android#4340]
## Current Behavior
Auto Upload does not Upload existing files in the directories I select. Only newly added files get uploaded.

Is this intentional? 

## Expected Behavior
I expected that the auto upload function behaves like the sync function on Desktop so all existing files get uploaded.

Please add the option to upload all existing files in the auto upload dialog or at least inform the user that existing files don't get uploaded.

## Environment
OS: Lineage 16 (Android 9) without Gapps
Nextcloud Android 3.7.1
Nextcloud Server 16

**Comment by mr700** [comment]
Same problem with my phones:
 - stock huawei mate 10, android 8
 - xiaomi note 4s  android 9 crdroid 5.6 no gapps.

On my wife's iPhone it uploads everything at once (slow but works).

Nextcloud server 16.4 (latest as of today).
Latest Nextcloud client 3.7.1 from F-Droid, Latest Nextcloud dev 20190810 from F-Droid.

**Comment by AndyScherzinger** [comment]
Upload of existing files and other features of the auto upload have been described within #285 already, so closing this (since it is a duplicate)
