### ISSUE TITLE
Auto upload: ignore .thumbdata*

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#4350]
Follow up for #3177 - @tobiasKaminsky 
See https://github.com/nextcloud/android/issues/3177#issuecomment-511137877

Hi,
I get the exact same issue.
The file is uploaded from my Android phone (Samsung S9), to my newcloud, everytime this file is changed (i.e. every time there is a change in the syncronized pictures folder).

In my case 
* the file:name: `.thumbdata4--1967290299` -> NOTE: it starts with a dot '.', 
* hiding the files while listing the folder.size: `687.8 MB` (today)

It is data, time and space in server.
It would be nice if we could avoid uploading that file.Anycase, congratulation for his briliant product.

Regards,José

**Comment by AndyScherzinger** [comment]
Related to custom folders I think

**Comment by ajostergaard** [comment]
Possibly useful to know I have the exact same issue (even with the same filename - though see note below) on both Android 9 and 10.

Number after '--' changes even inside the same folder:

![image](https://user-images.githubusercontent.com/791747/64491503-19eaf500-d261-11e9-812f-1677f72244f4.png)

PS: Don't think DCIM is a custom folder, is it?
