### ISSUE TITLE
Storage folder

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#4352]
Hi, i found a other issue with the nextcloud qa app (version 10456) [apk nextcloud qa](https://github.com/nextcloud/android/pull/4349#issuecomment-522684043)

If i download a file from the nextcloud app i have follow folder structure

*/storage/emulated/0/Android/media/com.nextcloud.client/nextcloud/tmp* temp upload folder
*/storage/emulated/0/Android/media/com.nextcloud.client/nextcloud/USER@NEXTCLOUD.DOMAIN* Path for downloadet content 

with the nextcloud qa app (version 10456) and if i download files from the nextcloud, any files are stored into the tmp folder
*/storage/emulated/0/Android/media/com.nextcloud.android.qa/nextcloud/tmp* if i use multi accounts, any files should be stored in one folder.

_Originally posted by @mr-bolle in https://github.com/nextcloud/android/issues/4341#issuecomment-522709208_

**Comment by tobiasKaminsky** [comment]
Due to the line wrapping, I do not get the problem.

What is stored in one folder? All files of all accounts are stored in the same temp folder?
This should not do any harm as we only process up-/download one after one and clean up afterwards. So it cannot happen to have conflicts there.

Or do I misunderstood you?

**Comment by mr-bolle** [comment]
![](https://i.imgur.com/yVXroJ5.jpg)

I made a new test with 2 different nextcloud accounts. If I have only one account, the downloaded file is stored into the folder **nextcloud/tmp** and if i add the second account all new downloads are separate to the folder **nextcloud/USER@NEXTCLOUD.DOMAIN**

There is really no issue with multiple accounts.

**Comment by tobiasKaminsky** [comment]
> There is really no issue with multiple accounts.

As we fixed it for one account in #4349, I can close this?

**Comment by mr-bolle** [comment]
Yes, thanks a lot.
