### ISSUE TITLE
Enhancement request: allow to select the name of dedicated WIFI networks for picture/video uploads

### ISSUE THREAD

**Issue by j-ed** [nextcloud/android#436]
### Actual behaviour
If the options "Instant picture/video upload" and "Upload pictures/video on Wifi only" are selected, the app tries to upload the pictures independently if a connection to the `right` Wifi network has been established. Not every Nextcloud server is reachable via the Internet but over the local Wifi network at home.

### Expected behaviour
If the options "Instant picture/video upload" and "Upload pictures/video on Wifi only" are selected it should be possible to additionally select a specific Wifi network which should be used for the upload of the pictures and videos. If a different Wifi network is active any upload attempt should be stopped.
 
### Environment data
Android version: 5.1.1
Stock or customized system: stock

Nextcloud app version: 1.4.0

**Comment by mario** [comment]
I am unsure I want to add this kind of complexity. cc @AndyScherzinger @tobiasKaminsky

**Comment by AndyScherzinger** [comment]
I also think we shouldn't add this since: 

* this would basically introduce white listing while we are already are respecting "metered wifi" so we already have blacklisting...

**Comment by j-ed** [comment]
I think you should differentiate this two access attempts, because blocking of "metered wifi" only guaranties that no mobile data connection is used to start syncing files.
Many users are nowadays connecting to each open wifi network which is in their reach, and the app would automatically try to connect to a Nextcloud instance although it might not be reachable. Beside the fact that each connection attempt will use system resources and  drain the battery, it is also propagating sync requests to the outside world by sending at least dns lookup requests.
In a personal environment that might be justified but due to the fact that Nextcloud is also being offered as a corporate solution, security will most likely of high relevance. Just my two cents why I believe it would be worse to implement a white list.

**Comment by AndyScherzinger** [comment]
@j-ed that is only correct as of now ;) 

* metered wifi - only protects you from uploads on wifi networks where you pay for data
* #1672 will check on connected wifi for an internet access/connection first before trying to upload

I do understand the security issue while it is on the other hand a security vs. comfort discussion in my eyes.

**Comment by xXSTrikeXx** [comment]
How is the connection being checked? I would prefer to check  a normal site e.g. nextcloud.com if a connection is etablished. So the “walled Garden“ wouldn't be able to know the clouds dns.

**Comment by pixelipo** [comment]
I hope this issue is still at least being considered. Let me explain my particular use-case:

One of my NC instances is running on a RPi in a local network. Network itself is metered, which means I want to upload from outside as little as possible. Hence, I've setup the Android app to the local IP, so autoupload is always running through a local network.

Problems start every time I connect to another WiFi network. I could set NC server to allow such data transfers, but it would increase network usage considerably.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky any opinion on this?

**Comment by j-ed** [comment]
To give you an idea how it could look like I attached two screenshots from the ContactSync and CalenderSync app which, from my point if view, has solved this request in a perfect manner:

![nc-sync-dialog](https://user-images.githubusercontent.com/2572764/35520417-44168bfa-0517-11e8-8a5b-d8d7284b0849.jpg)

![nc-wifi-select](https://user-images.githubusercontent.com/2572764/35520426-4a6c8004-0517-11e8-94a0-08fc1f36beec.jpg)

**Comment by mario** [comment]
I think this brings complexity beyond how useful it is. I understand @pixelipo case for example which will be solved differently eventually, but anyway ... you will have this for 3.x if @tobiasKaminsky and @AndyScherzinger want it.

**Comment by AndyScherzinger** [comment]
I agree with @mario due to the complexity, UX issues and the complexity driver which this feature will bring like

* bound to the account? 
* different per folder pair? 
* bound to mime types? 
Etc.

**Comment by tobiasKaminsky** [comment]
I remember that there is somewhere an option to mark wifi networks as limited/metered? Maybe this is enough.
In general, the purpose of this app is to upload/download/sync. If some users have a special setup which limits this to certain wifis, this is out of scope of this app, I think.

**Comment by pixelipo** [comment]
What about public wifi networks? Say you don't want NC to sync over public (non-secure) networks...

**Comment by pixelipo** [comment]
@tobiasKaminsky , your suggestion resolves my issue, though in a really weird way. Basically, I set all the known WiFi networks  except my home-network as "metered".

Just have to remember to add each new WiFi network to this list 🤦‍♂️

**Comment by tobiasKaminsky** [comment]
Hopefully the connection to your cloud is via https, so it should no matter if the public network is not secure...

**Comment by tobiasKaminsky** [comment]
As this is really an edge case, I will close this and am glad that you found a workaround.
