### ISSUE TITLE
Downloading to NExtcloud Chromebook

### ISSUE THREAD

**Issue by francofunghi** [nextcloud/android#4364]
### Is your feature request related to a problem? Please describe.

This is a feature request or maybe only a search for a solution i didn find yet:
https://help.nextcloud.com/t/new-android-client-on-chromeos/58152

it would enhance the workflow on a chromebook great if i could not only upload from nc (the nc files in the files app must be a webdav connection as no files are synced) to a website, but also download from there to nc (on downloading the nc filesystem is not visible)

On a chromebook the behavior would the be like on a windows machine with the new virtual drive funktionality.

i think that chromebooks even in europe are a growing market, and to have a smooth integration to nextcloud (not only with www will) increase the benefits for endusers and businesses.

### Describe the solution you'd like
i would like to download directly to nc on a chromebook

### Describe alternatives you've considered

tried webdav with linux apps on a chromebook, but very slow and no possibility to link to chromebook filesystem

### Additional context
searched on chromebook google forums but they bounced me back to nc app delevopers

https://support.google.com/chromebook/thread/12320095?hl=en

Look how nice this works on a chromebook (but only on uploads):

![Screenshot 2019-08-19 at 09 42 59](https://user-images.githubusercontent.com/54352275/63417776-39c98e80-c402-11e9-8e4f-9e796ee7c6ba.png)

Regards Franz

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by wiswedel** [comment]
CC @tobiasKaminsky 
CC @nextcloud/android

**Comment by joshtrichards** [comment]
Either things are different today or I'm misunderstanding this Issue. On my Chromebook I can access all my Nextcloud files and share with them on device apps and services without any problem. 

Closing this out because seems good. Don't hesitate to ping us back if something is being overlooked here.
