### ISSUE TITLE
Pause Synchronisation on network change (especially WiFi to mobile)

### ISSUE THREAD

**Issue by ThomasSteinbach** [nextcloud/android#437]
### Actual behaviour
If you synchronize a folder (or upload files), the fulfillment of the upload/download/synchronization continues even after the internet interface changes.

Practical example: You start synchronizing a 10GB folder while being connected to you WiFi at home. After a while you have to go to work. After leaving the WiFi zone Nextcloud continues synchronizing over LTE (or whatever). After a while you monthly mobile high speed volume is exhausted.

### Expected behaviour
When changing the network connection, Nextcloud should automatically stop the upload/download/synchronization. The user should be asked, when to continue the process.

Additionally there should be an option (opt-in?) to "do not pause synchronization on WiFi connection" - or vice verca (opt-out!) to "pause synchronization on mobile connection".
 
### Steps to reproduce
1. select a folder
2. choose 'synchronize' in the burger menu

### Environment data

Nextcloud app version:

1.4.0

### Additional Information

This issue would probably solve #193 but going further (beeing more smart).

**Comment by tobiasKaminsky** [comment]
Can you retry this? I did a test with the new auto upload system and after leaving wifi it stopped all other upload jobs.

**Comment by mario** [comment]
Dear users,

thank you for your patience. After lots of work, we’re super excited to be able to give you a test version with new auto upload implementation. Keep in mind we will only accept bugs related to Auto Upload in this APK, as other things might be broken.

https://cloud.nextcloud.com/s/ftZraTruRQjTe0R

This is a dev APK so it will not overwrite your existing play store/f-droid APK unless you’re already running dev version. Also, you might need to remove your existing dev version before installing this one.

Explanation of the current functionality:
- added support for custom folders
- separated image and video folders
- checks for new files happens every 15-20 minutes
- automatic retry every 15-20 minutes or when you force close/open the app
- automatic pause once network is changed (untested!)
- significantly less battery usage

All and any testing is more than appreciated, especially with large and ever-going files like Videos. (like, try to record a 30 min video).

Let me know if you’ve got any questions.

Cheers,
Mario

**Comment by tobiasKaminsky** [comment]
No response within the last month, therefore closing.
Please feel free to reopen with additional infos, if the problem still exists.
