### ISSUE TITLE
Non-destined users receive update notifications

### ISSUE THREAD

**Issue by sciurius** [nextcloud/android#4371]
### Setup
- NC is configured to send update notices to members of the admin group
- Android client has multiple user accounts, including one user that is member of the admin group
- A non-admin user is currently active. When the NC icon is clicked, it shows the data for this user

### Actual behaviour
- Notifications appear when updates are available for NC or any apps.

### Expected behaviour
- Notifications should only be send if the current user is member of the admin group, or the app update applies to an app that the current user has installed
 
### Environment data
Android version: 9.0
Device model: Samsung Galaxy Note Tab S4
Stock or customized system: no
Nextcloud app version: latest stable
Nextcloud server version: 16.0.4 and earlier

**Comment by tobiasKaminsky** [comment]
Android client just shows all notifications it gets via push, for all accounts.
Otherwise you would miss a lot of notifications, if they only pop up once you switch to the account.

Or am I missing something?

**Comment by sciurius** [comment]
The scenario that triggered my question is as follows.

My wife is a computer illiterate and she has a tablet that a.o. runs a NC client.
My NC account (which is admin group) is also on her tablet, but it is generally not used.
Now my wife gets notifications about a new NC being available. She does not understand, there is nothing she can do with this (yes, she can tell me but I already get my own notifications on my own clients). So I would appreciate if it were possible to prevent these notifications. 

IMO only the active account should get notifications. Notifications for other accounts could contain privacy sensitive information.

**Comment by mario** [comment]
I'm pretty sure that's unexpected behaviour @sciurius. If the account is not being used on a device, remove it.

For one, there are 2FA notifications which you don't want to miss, among others. And exceptions are a big no-no, so I don't think we want to go there.

**Comment by sciurius** [comment]
@mario: I assume you mean "expected behaviour"?
I don't think the mere _presence_ of an account is a reason to show everyone messages for that account.
Following that logic, all users of a Linux (or Android) system would receive system messages just because there is a root account on the system.

**Comment by tobiasKaminsky** [comment]
Your scenario is the same like having multiple accounts on desktop sync within the same linux user.


> Following that logic, all users of a Linux (or Android) system would receive system messages just because there is a root account on the system.


To have the same like you describe here, is that you have two different users on android (which is possible via profiles) and then you configure each NC app with its own account. Then you of course will not get a notification.
So I suggest this way, instead of mixing up two different users in one android user profile.

**Comment by sciurius** [comment]
"you have two different users on android (which is possible via profiles)..."

None of the devices here (Samsung A3, Samsung Tab S4, Zenpad 300) seem to support this :( .

**Comment by tobiasKaminsky** [comment]
Yeah, Samsung patched this out :/ 
But "normally" (what is normal in Android) world, it is supported…

**Comment by sciurius** [comment]
Anyway... Thanks for the understanding and support.
