### ISSUE TITLE
Auto upload with Motion Photos

### ISSUE THREAD

**Issue by javl** [nextcloud/android#4375]
### Actual behaviour
Nextcloud app sees 'Motion photos' as folders instead of photos.

### Expected behaviour
Motion photos should be seen as single photo within a folder.
This issue (which seems unrelated to this specific problem but also is about motion photos) seems to suggest uploading the photos used to work: #3262
 
### Steps to reproduce
1. Take a photo with Motion enabled
2. Nextcloud detects the new photo, thinks its a folder and suggests to sync the 'folder'.

### Environment data
Android version: 9
Device model: Pixel 3a
Stock or customized system: Stock
Nextcloud app version: 3.7.1
Nextcloud server version: NextCloudPi 16.0.3

### Desciption
Android offers the option to take `Motion Photos`, which are basically short videos which you can select the best frame from to use as your photo. Not sure what kind of format they use, but it seems Nextcloud thinks they're folders instead of images.

I took four photos of my cat with Motion enabled. They get stored in the default camera folder (which I am syncing) at `/storage/emulated/0/DCIM/Camera/`, but Nextcloud thinks the Nextcloud photos are actually folders within the `Camera` folder.

![Screenshot_20190822-112820](https://user-images.githubusercontent.com/734644/63503822-867b9b00-c4d0-11e9-83fb-9c5ca7043df1.png)
![Screenshot_20190822-112825](https://user-images.githubusercontent.com/734644/63503823-867b9b00-c4d0-11e9-8830-b8fc5e80aa01.png)

**Comment by tobiasKaminsky** [comment]
Nice cat :-)

It seems that the motion pictures are stored within sub-folders.
Can you show us the content of 
/storage/emulated/0/DCIM/Camera/IMG_20190818_184522

As a general bugfix AutoUpload should upload all files within a configured folder and also create corresponding folders.

**Comment by javl** [comment]
The amount of files in the folders seems to differ (had some with 1, some with 3), but they always have a ```*_COVER.jpg``` file:

Examples:

```
./IMG_20190818_184522:
drwxrwx--x  2 root sdcard_rw    3488 2019-08-18 18:45 .
drwxrwx--x 18 root sdcard_rw    8192 2019-08-26 10:03 ..
-rw-rw----  1 root sdcard_rw 3462635 2019-08-18 18:45 00000PORTRAIT_00000_BURST20190818184522697.jpg
-rw-rw----  1 root sdcard_rw 5161858 2019-08-18 18:45 00100lPORTRAIT_00100_BURST20190818184522697_COVER.jpg

./IMG_20190816_221120:
drwxrwx--x  2 root sdcard_rw    3488 2019-08-16 22:51 .
drwxrwx--x 18 root sdcard_rw    8192 2019-08-26 10:03 ..
-rw-rw----  1 root sdcard_rw 3000062 2019-08-16 22:11 00000PORTRAIT_00000_BURST20190816221120580.jpg
-rw-rw----  1 root sdcard_rw 4275999 2019-08-16 22:11 00100lPORTRAIT_00100_BURST20190816221120580_COVER.jpg
-rw-rw----  1 root sdcard_rw 4091533 2019-08-16 22:51 00100lPORTRAIT_00100_BURST20190816221120580_COVER~2.jpg
```

**Comment by tobiasKaminsky** [comment]
Can you give this a try?
It has a APK in it which you can install in parallel:
https://github.com/nextcloud/android/pull/4425

**Comment by javl** [comment]
_Turns out it wasn't the Motion photos but photos I took in the Portrait mode of the camera, which allow you to set a custom background blur (it saves the blurred version but also an original). But this doesn't change the problem with the folders._

Looking more closely, I noticed there are a couple of things going on here:

**Original app**
With the original NC app (with sync on for the `camera` folder):
1. I take a portrait photo
2. the app tells me there is a new media folder. This is the type mentioned above, named after the photo (so `camera/photoname/photoname.jpg`)
3. I ignore the notification and don't enable autoupload for this new folder
4. As the subfolder is part of a folder with autoupload on (the `camera folder) the NC app uploads the new photos anyway but puts them straight into the `camera` folder. 

**QA app**
Then I disabled auto upload in the NC app, installed the QA version of the NC app, and enabled the auto upload function of the `camera` folder in there:

1. I take a portrait photo
2. The app silently creates a new folder inside the remote `camera` folder and uploads the images to this new folder.

In both cases the thumbnails on the `auto upload` overview in the NC app are NOT updated to show the new images (doesn't show anything in subfolders). 


The result of the QA app makes sense: you get a folder with the new files, which is also the structure used on your mobile device. One (potentially huge) drawback of this new folder on the server is that it is... a folder. This means you can't easily browse your `camera` directory anymore, as you'll have to enter multiple subfolders to see their contents (which sometimes is just a single photo).

The gallery app on your phone gets around this problem by not treating them as folders; it presents you with a single image on the gallery overview, and when tapped it will use the other images in the folder in specific ways (original/edited versions, etc.) Of course the NC app could do something similar, but that would be way too specific behaviour for a project like NC.

**Final thoughts**
I'm not sure what the best option would be. Any thoughts on this?

1. keep the old behaviour where the content of subfolders ends up in the parent folder. 
    Pro: easy to browse gallery pages on the server
    Con: different structure from what is on the phone, images are not linked/related anymore (though you can use the name for custom scripts).
2. use the new method where subfolders are uploaded as subfolders
    Pro: mirrors folder structure of phone
3. something else?
    Con: makes it harder to browse images on server

**Comment by javl** [comment]
Was traveling and didn't see this on time. I do think this problem hasn't really been fixed/confirmed yet, but I don't know if anyone else has problems with this and if it is worth spending a lot of time on. Nevertheless, thanks for the help.

**Comment by joshtrichards** [comment]
@javl Since #4425 got merged it seems we went with approach two for now. :) (assuming it didn't change later on... this was awhile ago and I haven't glanced through later potentially relevant PRs).
