### ISSUE TITLE
Crash when selecting from the app menu

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/android#4399]
When choosing from the menu "Shared", "On device", "Photos" etc. At one point a crash app occurred.

> ************ CAUSE OF ERROR ************
> 
> java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference
> 	at java.io.File.fixSlashes(File.java:183)
> 	at java.io.File.<init>(File.java:130)
> 	at com.owncloud.android.ui.adapter.OCFileListAdapter.onBindViewHolder(OCFileListAdapter.java:433)
> 	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6781)
> 	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6823)
> 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5752)
> 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6019)
> 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
> 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
> 	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
> 	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
> 	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
> 	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
> 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
> 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
> 	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4194)
> 	at android.view.View.layout(View.java:16694)
> 	at android.view.ViewGroup.layout(ViewGroup.java:5481)
> 	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:625)
> 	at android.view.View.layout(View.java:16694)
> 	at android.view.ViewGroup.layout(ViewGroup.java:5481)
> 	at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1183)
> 	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:870)
> 	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:889)
> 	at android.view.View.layout(View.java:16694)
> 	at android.view.ViewGroup.layout(ViewGroup.java:5481)
> 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
> 	at android.view.View.layout(View.java:16694)
> 	at android.view.ViewGroup.layout(ViewGroup.java:5481)
> 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
> 	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
> 	at android.view.View.layout(View.java:16694)
> 	at android.view.ViewGroup.layout(ViewGroup.java:5481)
> 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
> 	at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1732)
> 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1497)
> 	at android.view.View.layout(View.java:16694)
> 	at android.view.ViewGroup.layout(ViewGroup.java:5481)
> 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
> 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
> 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
> 	at android.view.View.layout(View.java:16694)
> 	at android.view.ViewGroup.layout(ViewGroup.java:5481)
> 	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1231)
> 	at android.view.View.layout(View.java:16694)
> 	at android.view.ViewGroup.layout(ViewGroup.java:5481)
> 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
> 	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
> 	at android.view.View.layout(View.java:16694)
> 	at android.view.ViewGroup.layout(ViewGroup.java:5481)
> 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
> 	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
> 	at android.view.View.layout(View.java:16694)
> 	at android.view.ViewGroup.layout(ViewGroup.java:5481)
> 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
> 	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
> 	at android.view.View.layout(View.java:16694)
> 	at android.view.ViewGroup.layout(ViewGroup.java:5481)
> 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
> 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
> 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
> 	at android.view.View.layout(View.java:16694)
> 	at android.view.ViewGroup.layout(ViewGroup.java:5481)
> 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
> 	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
> 	at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2697)
> 	at android.view.View.layout(View.java:16694)
> 	at android.view.ViewGroup.layout(ViewGroup.java:5481)
> 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2229)
> 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1982)
> 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1140)
> 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6233)
> 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
> 	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
> 	at android.view.Choreographer.doFrame(Choreographer.java:606)
> 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
> 	at android.os.Handler.handleCallback(Handler.java:739)
> 	at android.os.Handler.dispatchMessage(Handler.java:95)
> 	at android.os.Looper.loop(Looper.java:148)
> 	at android.app.ActivityThread.main(ActivityThread.java:5530)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:734)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:624)

### Environment data
Android version: 6

Nextcloud app version: dev-20190823

Nextcloud server version: 16.0.4

**Comment by Valdnet** [comment]
Next:

> 
> ************ CAUSE OF ERROR ************
> 
> java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextcloud.android.beta/com.owncloud.android.ui.activity.FileDisplayActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.owncloud.android.datamodel.FileDataStorageManager.getVirtualFolderContent(com.owncloud.android.datamodel.VirtualFolderType, boolean)' on a null object reference
> 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2434)
> 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494)
> 	at android.app.ActivityThread.access$900(ActivityThread.java:157)
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356)
> 	at android.os.Handler.dispatchMessage(Handler.java:102)
> 	at android.os.Looper.loop(Looper.java:148)
> 	at android.app.ActivityThread.main(ActivityThread.java:5530)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:734)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:624)
> Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.owncloud.android.datamodel.FileDataStorageManager.getVirtualFolderContent(com.owncloud.android.datamodel.VirtualFolderType, boolean)' on a null object reference
> 	at com.owncloud.android.ui.adapter.OCFileListAdapter.showVirtuals(OCFileListAdapter.java:909)
> 	at com.owncloud.android.ui.fragment.PhotoFragment.handleSearchEvent(PhotoFragment.java:117)
> 	at com.owncloud.android.ui.fragment.PhotoFragment.onActivityCreated(PhotoFragment.java:88)
> 	at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2460)
> 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1483)
> 	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
> 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
> 	at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3269)
> 	at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229)
> 	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
> 	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:620)
> 	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
> 	at com.owncloud.android.ui.activity.BaseActivity.onStart(BaseActivity.java:194)
> 	at com.owncloud.android.ui.activity.DrawerActivity.onStart(DrawerActivity.java:1414)
> 	at com.owncloud.android.ui.activity.FileActivity.onStart(FileActivity.java:204)
> 	at com.owncloud.android.ui.activity.FileDisplayActivity.onStart(FileDisplayActivity.java:2618)
> 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1238)
> 	at android.app.Activity.performStart(Activity.java:6288)
> 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2397)
> 	... 9 more

**Comment by tobiasKaminsky** [comment]
This seem to happen if a file is assumed to be locally downloaded, but it is not.
Maybe this happens when you switch too fast…

**Comment by Valdnet** [comment]
> ************ CAUSE OF ERROR ************
> 
> java.lang.RuntimeException: An error occurred while executing doInBackground()
> 	at android.os.AsyncTask$3.done(AsyncTask.java:309)
> 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
> 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
> 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
> 	at java.lang.Thread.run(Thread.java:818)
I got this error today.
> Caused by: java.lang.IllegalStateException: Fragment PhotoFragment{25794a9} not attached to a context.
> 	at androidx.fragment.app.Fragment.requireContext(Fragment.java:696)
> 	at com.owncloud.android.ui.asynctasks.PhotoSearchTask.doInBackground(PhotoSearchTask.java:90)
> 	at com.owncloud.android.ui.asynctasks.PhotoSearchTask.doInBackground(PhotoSearchTask.java:38)
> 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
> 	... 4 more

### Environment data

Android version: 6
Nextcloud app version: dev-20190905
Nextcloud server version: 16.0.4
