### ISSUE TITLE
Favorites display error

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/android#4400]
### Steps to reproduce
1. Select "Favorites" from the menu.

- Screen with your favorite files:

![obraz](https://user-images.githubusercontent.com/47037905/63587787-1b4fc880-c5a5-11e9-9f94-e0ecf6c713d7.png)

- Screen with no favorite files:

![obraz](https://user-images.githubusercontent.com/47037905/63594591-1f84e180-c5b7-11e9-8821-aa2f2a6d2f51.png)

### Environment data
Android version: 6

Nextcloud app version: dev-20190823 and 3.8.0 RC2

Nextcloud server version: 16.0.4

**Comment by AndyScherzinger** [comment]
can be reproduced on latest master (OP3T, Lineage 16)

**Comment by tobiasKaminsky** [comment]
Fixed via https://github.com/nextcloud/android/pull/4485 and will be in RC5.
