### ISSUE TITLE
Battery drain with AutoUpload

### ISSUE THREAD

**Issue by oksjd** [nextcloud/android#4406]
### Actual behaviour
- On all 3 Xiaomi phones the app drained a significant amount of battery with auto upload enabled. Auto upload itself works as expected.

### Expected behaviour
- Should not drain battery that much
 
### Steps to reproduce
1. Install the stable version from F-Droid
2. Go through the initial configuration and disable every battery restriction for this app in Settings
3. Enable AutoUpload for a few folders

### Environment data
Android version:
MIUI 10 Android 9.0 on Mi 8SE and Redmi Note7 Pro, MIUI10 Android 8.1.1 on Mi 6X
Device model: 
Mi 8SE and Redmi Note7 Pro, Mi 6X
Stock or customized system:
Latest stock firmware
Nextcloud app version:
3.7.1
Nextcloud server version:
16.0.4
#### Web server error log
Unrelated
#### Nextcloud log (data/nextcloud.log)
Unrelated
### Battery management screenshots from Mi 8SE
![Screenshot_2019-08-24-11-42-45-520_com miui securitycenter](https://user-images.githubusercontent.com/54463160/63632333-c4aac300-c666-11e9-8bc0-6437408ed11d.png)
![Screenshot_2019-08-24-11-42-36-992_com miui securitycenter](https://user-images.githubusercontent.com/54463160/63632334-c5435980-c666-11e9-9c31-3e3dd111a142.png)
![Screenshot_2019-08-24-11-40-58-956_com miui securitycenter](https://user-images.githubusercontent.com/54463160/63632335-c5435980-c666-11e9-862e-b421b24a5317.png)

**Comment by richard-dg** [comment]
I have the same issue.

**Comment by fedotv** [comment]
I have having the same issue.
Anyone found any solution?

**Comment by richard-dg** [comment]
Actually I don't see, why there are any updates needed. The description is accurate, all needed information is there. The issue simply hasn't been assigned yet. 
So from my part: I'm using an BQ Aquarius X Pro, Android 8.1.0, App-Version 7.0.7

**Comment by samedamci** [comment]
I have the same issue on Xiaomi Mi A2 Lite with stable and also dev NextCloud app.
