### ISSUE TITLE
[Feature Request] InstantUpload - Set Path for Picture and Video 

### ISSUE THREAD

**Issue by Crasha** [nextcloud/android#441]
I noticed this was removed for some reason and it was very handy to have when trying to keep organised. There is already an option in the Nextcloud App called "Use Subfolders" which stores files inside a directory structure based on the Year and Month.  I have another two folders however called Pictures and Videos, thus the directory would be something like...

2016/December/Photos
2016/December/Videos

**Comment by AndyScherzinger** [comment]
Hi Crasha,

which version of the app and which android version are you running? Just asking since the feature should still be in place for any version below Android 7 runing the stable release but was replaced by the auto pload for anthing Android 5 or higher in case you are running the beta app.

**Comment by Crasha** [comment]
Hi @AndyScherzinger,

I'm running Android 7.1.1 (Just upgraded the other night) however the new revamped Auto Upload removes this incredibly neat feature with just a standard "Remote upload path" in which everything uploaded just gets dumped into one folder. It was nice to select what went where in terms of Photos and Videos.

Also, the previous app didn't detect my Photos/Videos as I took a photo/recording so it would Upload automatically, however the ownCloud app worked fine.

**Comment by AndyScherzinger** [comment]
Hi @Crasha,

that is true, Android 7 has been broken for the Nextcloud app before the release of 1.4.0 while 1.4.0 doesn't distinguish between photos and videos which is something we are thinking about how to bring this back in a nice/simple/comfortable way. 

So cc @nextcloud/designers and @tobiasKaminsky for the discussion how to best solve the video/photo matter also mentioning that we (as in I from the UI perspective) will probably extend this soon to also offer audio folders and at some point the any folder pair thing.

@Crasha if I understood you correctly the version 1.4.0 uploads videos and photos into different folders?

**Comment by Crasha** [comment]
@AndyScherzinger,

Version 1.4.0 has the AutoUpload feature in which you select a Remote folder on the server to upload photos/videos to. Previous versions, like the ownCloud app, you could select Instant Photo upload and Instant Video Upload paths on the server so you can separate the two.

**Comment by AndyScherzinger** [comment]
@Crasha so you _want_ videos and photos to go into different folders (or at least the chance to specifiy it for each one), right? (Then I missunderstood your previous comment)

**Comment by Crasha** [comment]
@AndyScherzinger That's correct.

**Comment by AndyScherzinger** [comment]
Hi @Crasha this has been re-introduced for the next release 2.0.0 which you can already test via our release candidate.

**Comment by Crasha** [comment]
@AndyScherzinger Awesome, thank you!
