### ISSUE TITLE
Keyboard suggestions sync

### ISSUE THREAD

**Issue by smnthermes** [nextcloud/android#4411]
### Is your feature request related to a problem? Please describe.
Not able to use, seamlessly, keyboards suggestions across multiple Android devices, using a trustworthy provider, rather than Google (Gboard) or Microsoft (SwiftKey).

### Describe the solution you'd like
An API of keyboard suggestions sync which could be implemented by apps such as AnySoftKeyboard and Hacker's Keyboard.

### Describe alternatives you've considered
Currently, there isn't even one alternative for manual importing/exporting

**Comment by tobiasKaminsky** [comment]
I would do this as a server side NC app, and then it must "only" be implemented in these keyboards.
This is independent from Files app, thus closing as out of scope.

P.S: I do like the idea!
