### ISSUE TITLE
Instant upload crashes client

### ISSUE THREAD

**Issue by ac3r** [nextcloud/android#442]
### Actual behaviour
- Android 6 Sony Xperia XA, 1.4.0 RC2 from f-droid.org.
- Take a photo using factory camera app with instant upload enabled, client crashes (message "Unfortunately, Nextcloud has stopped.") 
- Upload doesn't happen even when restart client.
- External SD card selected for storage path in settings. 

### Expected behaviour
- Photos uploaded automatically after being taken using factory camera app. 
 
### Steps to reproduce
1. 
2. 
3. 

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

**Comment by AndyScherzinger** [comment]
Hi @ac3r,

Sorry for the inconvinience. This has been fixed with RC3 and since today the stable version of 1.4.0 is finally available via f-droid and will solve the crash issue.
