### ISSUE TITLE
App leaking deleted files in "failed" section of "Uploads"

### ISSUE THREAD

**Issue by pilsnerbeer** [nextcloud/android#4426]
### Actual behaviour
This lands somewhere between bug report & request because I don't think this feature was created accidentally. However, the app will leak/show you thumbs of files you deleted a long time ago, which I imagine is not preferred.

The concerned part is the "uploads" section -  if you set a certain album to upload automatically, the error list may get populated with long-deleted photos.

![Screenshot_1](https://user-images.githubusercontent.com/36133540/63787856-d30e0e80-c8f4-11e9-9c75-0a30f10cbbbe.png)

Please read the steps to grasp the issue in full

### Expected behaviour
I guess do not show deleted images - they were deleted for a reason and may display sensitive data.
 
### Steps to reproduce
1.  Make sure to enable autoupload for a folder - let's say /screenshots.
2.  Disconnect from the internet
3.  Take a screenshot, new file will be created under /screenshots/ and Nextcloud will queue it for upload as soon as connection is established.
4.  Delete the screenshot from the device (wait some time before doing so it can cache the thumbnail)
5.  Enable internet connection
6. Under "Uploads", your screenshot will be shown in "failed to upload" section.

### Environment data
Android version: 9
Nextcloud app version: 3.7.2

Nextcloud server version: 15

**Comment by tobiasKaminsky** [comment]
To be honest I do not see any problem, as you are the owner of the device.

What does the other devs think? @AndyScherzinger @ezaquarii

**Comment by pilsnerbeer** [comment]
I respect the decision to keep it - but it is simply the principle of deleting a file: when delete, delete forever, from everywhere. Perhaps I could fabricate a few extreme examples in which this small "feature" could expose secrets but I'm sure you know what I mean.

**Comment by AndyScherzinger** [comment]
I'd keep it as is since file not found doesn't necessarily mean deleted. It could also mean file has been moved. So the Nc app doesn't know why the file isn't there anymore so besides the file name the preview image might give the user an additional hint.

So format both scenarios there can't be extreme cases where for pro/con while I still think for most users the preview images are rather beneficial.
