### ISSUE TITLE
Master does not compile

### ISSUE THREAD

**Issue by ezaquarii** [nextcloud/android#4428]
### Actual behaviour

Master does not compile

### Expected behaviour

I'm out of ideas...
 
### Steps to reproduce
```
$ ./gradlew assembleQa
> Task :compileQaDebugJavaWithJavac
/home/tn/Devel/nextcloud-android/src/main/java/com/owncloud/android/ui/fragment/FileDetailActivitiesFragment.java:315: error: cannot find symbol
                    getRemoteNotificationOperation.setNextUrl(pageUrl);
                                                  ^
  symbol:   method setNextUrl(String)
  location: variable getRemoteNotificationOperation of type GetActivitiesRemoteOperation
/home/tn/Devel/nextcloud-android/src/main/java/com/owncloud/android/ui/activities/data/activities/ActivitiesServiceApiImpl.java:99: error: cannot find symbol
                    getRemoteNotificationOperation.setNextUrl(pageUrl);
                                                  ^
  symbol:   method setNextUrl(String)
  location: variable getRemoteNotificationOperation of type GetActivitiesRemoteOperation
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors

> Task :compileQaDebugJavaWithJavac FAILED
```

**Comment by ezaquarii** [comment]
Oupsie, my refs are messed up.

**Comment by tobiasKaminsky** [comment]
We have our new workflow with "client change requires".
This indeed works somehow good.
The current problem is that after merging of lib PR the corresponding files PR was stalled too long by CI.
This timegap is something where I do not have any idea how to minimize…

**Comment by tobiasKaminsky** [comment]
https://github.com/nextcloud/android/pull/4419 is now merged, so everything should work again (maybe after a rebase)

**Comment by ezaquarii** [comment]
> This timegap is something where I do not have any idea how to minimize…

How about

1. tag library with version
2. use tagged version on master

Is there a reason why we use snapshot?

**Comment by AndyScherzinger** [comment]
> Is there a reason why we use snapshot?

Any code breaking change on the lib would enforce a release tag so master build.gradle would change all the time and branches would need to be rebased constantly.
