### ISSUE TITLE
Option to auto upload/sync existing files

### ISSUE THREAD

**Issue by denis-pujdak-adm-it** [nextcloud/android#4430]
### Is your feature request related to a problem? Please describe.
I'm always frustrated when AutoUpload works only for new files but not for existing ones.

### Describe the solution you'd like
Have an extra option to upload/syncronize all existing files as well.

### Describe alternatives you've considered
-nope-

### Additional context
![Screenshot_20190827-221357_Nextcloud](https://user-images.githubusercontent.com/13495631/63808674-686eca00-c918-11e9-89ef-ce8afe269c33.png)

**Comment by AndyScherzinger** [comment]
This feature is already defined and request in #285

**Comment by denis-pujdak-adm-it** [comment]
Thanks @AndyScherzinger .
