### ISSUE TITLE
Display location of searched files

### ISSUE THREAD

**Issue by pilsnerbeer** [nextcloud/android#4432]
### Is your feature request related to a problem? Please describe.
The mobile app doesn't show the location of searched files. For instance, here's a search result from the mobile app:

![Screenshot_2](https://user-images.githubusercontent.com/36133540/63858572-648d8700-c9ae-11e9-8f86-c39891140987.png)

(Note: the "Details" option doesn't reveal the file location either).

Compare it with results from the web:

![Screenshot_1](https://user-images.githubusercontent.com/36133540/63858653-8f77db00-c9ae-11e9-847b-72840c996c9a.png)

Notice the web app displays the location of the searched file.

### Describe the solution you'd like
Show the location of each searched file, right below the file name , next to size/date.

**Comment by t-m-w** [comment]
A messy and incomplete workaround is to add a comment on the file in the Details such as, "Where is this?" Then, go to your Activities page, tap the file in the comment, and you'll be taken to the folder in which the file resides. Unfortunately, the folder name at the top will be incorrect (it shows the name of the file instead), but as you press the Back button, you will navigate through the parent folders and may be able to deduce where it is.

**Comment by AndyScherzinger** [comment]
Additional extension of this request by @lwbr 

> when I search for a document (mobile app) and the search results are displayed, it is not possible to see in which path the file is located. so it would be good if you can see the path under document details. maybe an additional option to switch to the appropriate folder.

via https://github.com/nextcloud/android/issues/7641#issuecomment-742509188

**Comment by tobiasKaminsky** [comment]
This will be better with #7480

**Comment by joshtrichards** [comment]
The current implementation now looks like the web UI screenshot. #7480 and follow-on merges addressed this.
