### ISSUE TITLE
Site URL is not displayed all

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/android#4437]
I noticed that in the application 
the URL of the site is cut in half horizontally, 
the characters are not completely visible.  
I am attaching a screenshot.

![20190830_093838](https://user-images.githubusercontent.com/35575744/64002305-04135c80-cb0a-11e9-81a9-c09a773810e4.jpg)

**Comment by AndyScherzinger** [comment]
@tigernero79 thanks for the report. What device are you using (specifically: does is have a display noth?)? And which version of the app are you using (can be found at the bottom of the settings screen)?

**Comment by tigernero79** [comment]
I'm using samsung galaxy s10 plus, beta version 3.8.0 rc3 application, on google pixel 2xl instead everything ok

**Comment by tigernero79** [comment]
up

**Comment by tigernero79** [comment]
@AndyScherzinger up

**Comment by AndyScherzinger** [comment]
@tigernero79 up?

**Comment by tigernero79** [comment]
@AndyScherzinger I meant to read above, my answer.  sorry if i wasn't clear.

**Comment by tigernero79** [comment]
@AndyScherzinger Announcements? do you need any other information?

**Comment by AndyScherzinger** [comment]
@tigernero79 None yet. Looping in @tobiasKaminsky @ezaquarii since I don't have a device or the time to tackle this issue.

**Comment by tobiasKaminsky** [comment]
I can have a look later when my wife is back.

**Comment by tigernero79** [comment]
@tobiasKaminsky thank's

**Comment by tobiasKaminsky** [comment]
"Sadly" my wife only has a 9+ without notch.
With emulator one can simulate a notch and then the outcome is similar.
I'll give it a try.

**Comment by tigernero79** [comment]
news for risolution?

**Comment by tigernero79** [comment]
can it depend on the display resolution of the s10 plus?

**Comment by tigernero79** [comment]
@tobiasKaminsky 
output version 3.9.0, which still carries this bug on samsung s10 plus series

**Comment by tigernero79** [comment]
@tobiasKaminsky news for the bug?

**Comment by tobiasKaminsky** [comment]
I have now a OP6T with a notch, but I do not have the overlapping text.
Sorry, I am out of clue :/

**Comment by tobiasKaminsky** [comment]
This is changed with latest master.

**Comment by tigernero79** [comment]
@tobiasKaminsky  I have version 3.12.0 RC3 but the defect remained on s10 plus samsung. 
Also noticed the next release of a version 19. not so because you have closed tobias

**Comment by AndyScherzinger** [comment]
the change Tobias refers to will ship with 3.13.0

**Comment by tigernero79** [comment]
ok thanks for all
