### ISSUE TITLE
Auto upload uploads zero bytes .tmp files

### ISSUE THREAD

**Issue by ISibboI** [nextcloud/android#444]
### Actual behaviour
Auto upload uploads zero byte tmp files
Their file names look like this: `Screenshot_20161122-224131.png9788e926-5e84-4b21-bdd8-dc5a4d9ed24c.tmp`

### Expected behaviour
Zero byte files should be ignored by auto upload, and maybe the ending tmp as well.
Or make the user choose, which endings he she wants to upload.
 
### Steps to reproduce
Don't know

### Environment data
Android version: 7.1.1

Device model: Nexus 5X

Stock or customized system: Stock

Nextcloud app version: 1.4.0

Nextcloud server version: 9.0.53

**Comment by Crasha** [comment]
I've experienced this as well. I was quite surprised .tmp files were being uploaded.

**Comment by tobiasKaminsky** [comment]
PR: #485

**Comment by AndyScherzinger** [comment]
PR has been merged for next release 1.4.1
