### ISSUE TITLE
Backup Contacts: 'Last Backup' value totally wrong

### ISSUE THREAD

**Issue by DavHau** [nextcloud/android#4440]
My nextcloud Server has been down for weeks, still under Settings/Backup Contacts the field 'Last Backup' shows 12 hours ago which is not true. The time displayed is probably the time of the last backup attempt, but it should display the time of the last successful backup. Because of this bug users are mislead into thinking their contacts have been backed up even if they never have.

**Comment by AndyScherzinger** [comment]
pinging @tobiasKaminsky since he is the expert on contacts backup
