### ISSUE TITLE
Minor Usability improvements

### ISSUE THREAD

**Issue by eppfel** [nextcloud/android#445]
I looked closely to the current app and spotted some things we could improve for usability:

# Missing space between avatar and filename :white_check_mark: 
`papercut` - see #449

![screenshot_20161124-194840](https://cloud.githubusercontent.com/assets/1899308/21112965/13410e06-c0a8-11e6-8d94-2d72c02acb93.png)

# Add icon to make state more recognize :white_check_mark: 
Reading the text takes time, an icon is easily remembered and then you would spot on first glimpse, that this is an empty folder. see #449

![screenshot_20161124-195142](https://cloud.githubusercontent.com/assets/1899308/21112456/216f2744-c0a6-11e6-8e88-eb580a74e939.png)

## Some folders have opaque white background in multiselect
![screenshot_20161124-195506](https://cloud.githubusercontent.com/assets/1899308/21112623/c214f89a-c0a6-11e6-9bd4-5fb6108b72d5.png)

## Wrong top-left icon after menu swipe :white_check_mark: 
When you are in an folder and swipe from the left edge of the screen the menu opens. After closing the menu again, the icon has changed from `back` to `menu`, but the action is still `back`. see #449

![screenshot_20161212-195635](https://cloud.githubusercontent.com/assets/1899308/21112835/93afcbf0-c0a7-11e6-81cd-86d3c1c6541b.png)

#  Trim filenames in respect to each other
In this view you can not distinguish the files, because they follow the same pattern `P3_[Date]_[Content]_[Owner].[extesnion]`. Not so easy to fix, I guess and not a use-case that happens often: Therefore Low priority

![screenshot_20161124-195114](https://cloud.githubusercontent.com/assets/1899308/21112234/4ebc597a-c0a5-11e6-89ae-8d76418a1df8.png)

### Environment data
Android version: 6.0.1

Device model: Sony E5823

Nextcloud app version: Latest Beta (30.11.16)

**Comment by AndyScherzinger** [comment]
Great eye for details @eppfel!!! :+1:

**Comment by AndyScherzinger** [comment]
3 out of 5 have been fixed by see #449

**Comment by eppfel** [comment]
- [x] Missing space between avatar and filename https://github.com/nextcloud/android/pull/449/commits/7012be9baa2396b6064479a0ee8fd72433225be3
- [x] Add icon to make state more recognize https://github.com/nextcloud/android/pull/449/commits/246acd94bbd11f5e78988103934302ca14e1307f
- [x] Wrong top-left icon after menu swipe https://github.com/nextcloud/android/pull/449/commits/1d420261fcbca95d0ab44ea534c02c5569714313
- [ ] Some folders have opaque white background in multiselect (not sure if/how this can be fixed) 
- [ ] Trim filenames in respect to each other (not sure if/how this can be fixed)

**Comment by tobiasKaminsky** [comment]
I never experienced the opaque background during multi select.
Dynamically trim file names is nearly impossible ...
So closing
