### ISSUE TITLE
Auto upload deletes despite setting "move to app folder"

### ISSUE THREAD

**Issue by voidzero** [nextcloud/android#4454]
### Actual behaviour
Enabled auto-upload for a directory: 
Setting: "Original file will be... moved to app folder."

But files get deleted from local device after upload. Sometimes they don't get deleted but still they are not visible via "On Device". Maybe "On Device" actually deletes them???

### Expected behaviour
The files should remain on the device, and visible via "On Device" navigation on the android app
 
### Steps to reproduce
1. Enable auto-upload for a directory
2. Set Original File wil be... "moved to app folder"
3. Wait for upload
4. Go to On Device
5. Navigate to the right directory
6. It says "No files here"

### Environment data
Android version: Pie

Device model: HTC U11+

Stock or customized system: Stock

Nextcloud app version: 3.7.2

**Comment by MultiCoreNop** [comment]
Same for me. This has always been this way. No matter whether setting is "delete" or "move to app folder" - files will be deleted.
Side note: Opening the Nextcloud App after such an automated upload and switching to "On Device" shows all directories with their corresponding sizes. As soon as you open one, all files within will be deleted.

**Comment by MultiCoreNop** [comment]
clarification: "has always been this way == since I started to use the Nextcloud App several years ago"
This problem remained over several devices and Android versions (I am currently on LineageOS 16.x / Android 9 from 2019-08-01). Nextcloud Dev from F-droid.

**Comment by MultiCoreNop** [comment]
duplicate: see #4220 #2131

**Comment by feutl** [comment]
I want to add that forum entry to that issue, because this is not what I expected when using that feature
https://help.nextcloud.com/t/move-file-to-app-folder-after-automatic-upload-works-but-files-get-deleted-locally-after-opening-the-nc-app/61080

**Comment by voidzero** [comment]
Meh

**Comment by voidzero** [comment]
Meh

**Comment by MultiCoreNop** [comment]
Since somewhere in October 2019 this problem seems to be fixed for me. All photos since then remain on my device, even of I browse through them using the Nextcloud app/on device.
(+ there was a fix submitted somewhere I thought, so this problem should not exist any longer)

**Comment by MultiCoreNop** [comment]
So I guess the question is:
Can anyone still reproduce the bug using Nextcloud-dev 20191116 or newer?

**Comment by MultiCoreNop** [comment]
still: duplicate of #2131

**Comment by feutl** [comment]
I tested this, because I had problems with it like mentioned in my [comment](https://github.com/nextcloud/android/issues/4454#issuecomment-537806803) and it worked over the last 7 days without issues.

Even deleting files locally available in the app folder, on another device, removed the files on the device where it was moved to the local app folder correctly.

Device: Samsung S9+
NextcloudClient: 3.9.2
Nextcloud: 16.0.4 and 17.0.1
Android: 9.0

Thanks

**Comment by voidzero** [comment]
Thank you kindly for letting us know it works... I wasn't able to test this myself, so, i'm happy you're letting us know. Closing.
