### ISSUE TITLE
Autoupload doesn't detect google camera photos

### ISSUE THREAD

**Issue by adrigrillo** [nextcloud/android#446]
### Actual behaviour
When I take a photograph with the google camera application autoupload doesn't detect that it was taken, doesn't matter if the HDR+ is on or off. This problem does not happen when I take the photo with my other camera app (Camera FV-5).

### Expected behaviour
The picture has to appear in the queue of autoupload.
 
### Steps to reproduce
1. Take a photograph with Google Camera with HDR+ on or off.

### Environment data
Android version: 7.0 
Device model:  Nexus 5x
Stock or customized system: PureNexus Rom
Nextcloud app version: 1.4.0
Nextcloud server version: 10.0.1

**Comment by AndyScherzinger** [comment]
Hi @adrigrillo,

what other settings did you choose? wifi-only? charging-only?

**Comment by adrigrillo** [comment]
Hi @AndyScherzinger 
The only change I made was the route of the saving folder. Been trying with and without wifi-only but didn't change the behavior. Also exclude the app from greenify but nothing.

**Comment by mario** [comment]
Try the newest beta. 

https://github.com/nextcloud/android/raw/beta/apks/latest.apk

Thanks!
