### ISSUE TITLE
Login does not work on Android 4.2

### ISSUE THREAD

**Issue by kugelblitz** [nextcloud/android#4464]
### Actual behaviour
- "Webpage not available" message during login
- No visible workaround (QR code auth is a hope, but it seems that the used version of the server does not support it)

### Expected behaviour
- Normal login
 
### Steps to reproduce
1. Install a fresh Nextcloud client on android 4.2
2. Run the client, enter a server address to login, for instance https://nextcloud.iaaras.ru

### Environment data
Android version: 4.2.2

Nextcloud app version: 3.7.2

Nextcloud server version: not exactly known

### Causes

The web page does exist. If one opens it in Android 4.2 stock browser, it will say "couldn't establish a secure connection".

The problem, I think, is that Nextcloud login does its thing via WebView. On Android Jelly Bean, WebView was infamously left without updates. In particular, it does not support TLS 1.2, only TLS 1.0 (Android 4.2 stock browser has the same problem). The server requires TLS 1.2.

The good news is that there seems to be a way to enable TLS 1.2 in even in Jelly Bean's WebView programmatically in the app, see e. g. https://www.reddit.com/r/androiddev/comments/8uqt0c/how_can_i_support_tls_12_pre_kitkat_on_android/

I ask you to follow this path and to enable TLS 1.2 to make users of Android 4.2, and Jelly Bean in general (reportedly there are still tens of millions of them) happy with Nextcloud.

**Comment by AndyScherzinger** [comment]
Please give the beta version a try 3.8.0RC since it ships with TLS support for 1.3 and for legacy Android OS versions.

Any feedback would be highly appreciated.

**Comment by AndyScherzinger** [comment]
As a side note beware that we actively drop legacy server version support so at some point the client will stop working at all no matter the Android OS version.

**Comment by kugelblitz** [comment]
Upgrading to 3.8.0 RC (apk from f-droid) did not resolve the issue.

However, I noticed that I have to wait a minute on the failed WebView screen to see the "revert to the old login method" button, and the old login method works. This applies not only to 3.8.0 C, but also to 3.7.2 as well. So I have a workaround. It is kind of hidden, though, as the user has to sit and wait relatively long to see the old login option.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky any way we can detect this and revert back to the old style login? Other than that I thought 3.8.0 should have solved this?
