### ISSUE TITLE
 Prompt to move to app folder on upload even though 'Keep in source folder' is selected

### ISSUE THREAD

**Issue by TeNNoX** [nextcloud/android#4465]
Similar issue to #3782 - but that is Closed and a bit different.

### Actual behaviour
I want to upload files from an app (in my case TitaniumBackup), and I select **"keep files in source folder"**.

Nextcloud asks me:
> **Attention**
> Insufficient space prevents copying the selected files into the Nextcloud folder. Would you like to move them there instead?

Pressing 'No' cancels the operation, and pressing 'Yes' moves the files from the source folder to the nextcloud app folder - which is not what I want.

Is it so that Nextcloud can't upload without having them in the app folder?!
If that is so (which would be weird), at least give a hint about that in the modal.

### Expected behaviour
Nextcloud would upload the files and keep them in the source folder.
 
### Steps to reproduce
1. Have a disk with less space than the folder you want to upload (I guess)
2. Go to Upload > Upload files > select files
3. Select to 'Keep files in source folder'
4. Press upload

(When selecting **Upload from other apps** it seems to work: the files stay in source folder - but I'm not sure because my phone's disk space got full - and maybe that was because Nextcloud was copying the files somewhere)

### Environment data
Android version: 9
Device model: Oneplus 6T
Stock or customized system: Oneplus Oxygen (rooted)
Nextcloud app version: 3.7.2

**Comment by TeNNoX** [comment]
An addition:
The warning prompt event shows up when I select "Delete from source folder" - there is not enough space to delete them?! :yum:

**Comment by TeNNoX** [comment]
Well, it's stale because no team member replied. That's not a reason to close this issue :yum:

**Comment by tobiasKaminsky** [comment]
Hm.
Can you create a screenshot? I do not fully understand how you can upload from a file and also have a decision "keep in source folder"?

**Comment by AaronADev** [comment]
I can confirm this is an issue also occurring on my Android devices, and all of them. If examples are needed I can try to post it when I get home tonight.

**Comment by AaronADev** [comment]
![Screenshot_20191007-191129_Nextcloud](https://user-images.githubusercontent.com/12901914/66358116-1ff2f500-e937-11e9-84b3-d44164b4fc77.jpg)
![Screenshot_20191007-191101_Nextcloud](https://user-images.githubusercontent.com/12901914/66358117-24b7a900-e937-11e9-8896-3106e81604b4.jpg)

So interesting thing is, there is tons of space on both the phone and the server. About 40GB free on the phone and 11 Terabytes free on the server. There is no insufficient space anywhere. Also, the path is for the internal phone memory and not an external SD card. So, I am assuming something went wrong with a recent update. Anyone have feedback on this?

**Comment by AaronADev** [comment]
So.. I changed the storage path from

`/storage/emulated/0/Android/media/com.nextcloud.client`

To

`/storage/emulated/0/Android/data/com.nextcloud.client/files`

And the issue has gone away. Is there a reason for this? Is there a difference between the media and data paths that prevents the app from determining the availability of disk space on the device?

**Comment by tobiasKaminsky** [comment]
>  Is there a difference between the media and data paths that prevents the app from determining the availability of disk space on the device?

Both paths seem to be in the same location (internal vs. external storage).
The only difference is that media is also accessible by other apps, whereas data is not.

I am out of clue, why this is happening :-(

**Comment by Berulacks** [comment]
Can confirm that I have the same issue, as well. I'm trying to use Nextcloud to backup/clear my phone (whose storage is now full) of images. Selecting "Keep in source folder" has no effect on the upload - I'm still prompted to move the files in question into the data directory in order to upload.

**Comment by typorian** [comment]
this is still happening. can't upload images without being forced to move them, which removes them from the regular spot where they are saved.
