### ISSUE TITLE
Displaying "On device"

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/android#4467]
Incorrect display of the "On device" window
 
### Steps to reproduce
1. Download the file to your device.
2. Select "Shared" from the menu.
3. Select "On device" from the menu.
4. Display error.

![obraz](https://user-images.githubusercontent.com/47037905/64345769-33860580-cff1-11e9-8819-5af3c9925a5c.png)

Environment data

Android version: 6

Nextcloud app version: 3.8.0 RC4 and dev-20190905

Nextcloud server version: 16.0.4

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky I can reproduce this with latest master, haven't tested it with 3.7.x

**Comment by tobiasKaminsky** [comment]
I cannot reproduce right now, but I'll keep this up for navigation update after 3.8.

**Comment by tobiasKaminsky** [comment]
Does not happen anymore.
