### ISSUE TITLE
The Favorits load but I cannot click on them: 3.8.0 RC4

### ISSUE THREAD

**Issue by szaimen** [nextcloud/android#4469]
The Favorits load but I cannot click on them: 3.8.0 RC4
See the screenshot:
![Inkedphoto5442855309845572487_LI](https://user-images.githubusercontent.com/42591237/64368528-cf783700-d01a-11e9-9a7d-603bf1bd1380.jpg)
I think it is hidden behind the Error-Message and cannot be clicked because of that.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky this is also happening to @Valdnet and me so this is somewhat of a blocking issue for a release imho!

**Comment by tobiasKaminsky** [comment]
Fixed via https://github.com/nextcloud/android/pull/4485 and will be in RC5.
