### ISSUE TITLE
Auto upload is not triggered on Android 7.1

### ISSUE THREAD

**Issue by enoch85** [nextcloud/android#447]
### Environment data
Android version:
7.1
Device model: 
Nexus5x
Stock or customized system:
Stock
Nextcloud app version:
1.4.0
Nextcloud server version:
10.0.2
### Logs
-

**Comment by AndyScherzinger** [comment]
Hi @enoch85 ,

which settings are you using? Just asking since I also run 7.1.1 on my Nexus5X and the auto upload works on my device. I only use the camera folder with standard settings though (wifi only, /InstantUpload/Camera)

**Comment by enoch85** [comment]
Sorry (again) it works, must have been a temporary error.

**Comment by AndyScherzinger** [comment]
❤️
