### ISSUE TITLE
Some uploaded files don't appear when shared from other apps

### ISSUE THREAD

**Issue by nunofmds** [nextcloud/android#4477]
### Actual behaviour
- When multiple pictures selected to upload some of them don't appear on the nextcloud server but there is no error during the operations. I have always to manual check if they are there.

### Expected behaviour
- All selected files should be uploaded to the target folder, if some fails it should prompt the user back to repeat or to cancel the operation.
 
### Steps to reproduce
1. Select +10 pictures from gallery
2. Click on share
3. Select nextcloud
4. Select folder
5. Click Upload 

### Environment data
Android version: 9

Device model: Xiaomi Mi A2 Lite

Stock or customized system: No. Android One

Nextcloud app version: Latest

Nextcloud server version: Latest

**Comment by gohrner** [comment]
I can confirm this with a Nokia 8 Sirocco (Android One, Android 9 "Pie"). I was just about to report the same issue. This is about uploading content using the Android "Share ..." feature. (As described in the "Steps to reproduce" of the original report above, but not stated in the subject line.)

It appears to be more or less random which images are actually uploaded, i.e. if I delete the files at the target location and repeat the "Share with Nextcloud" process, a different (incomplete) set of images will be uploaded, compared to the first try.

The upload is never complete, there's always many images missing, and if I do not check the upload before deleting the originals, trusting in the upload process as there are no error messages, I'll lose data... :-(

That's not only extremely annoying, but also dangerous. :-(

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky this is probably due to some data limitation / Android OS version thing where we might need to read the incoming data differently to be able to process the files (or it might not be possible at all, don't know).

**Comment by gohrner** [comment]
In any case, it definitely should not appear as if it worked successfully if it didn't...

**Comment by xNuno** [comment]
Maybe but it's bad that we always have to resend the images again and they got renamed to (x) if they exist already. Besides that we can't fully trust on this feature...at least an error, retry or something should output for the user awareness.

**Comment by tobiasKaminsky** [comment]
I created these images and shared them on Android 9 emulator with Photos:
`
IMG_20190910_134145.jpg
IMG_20190910_134146.jpg
IMG_20190910_134149.jpg
IMG_20190910_134151.jpg
IMG_20190910_134152.jpg
IMG_20190910_134154.jpg
IMG_20190910_134155.jpg
IMG_20190910_134157.jpg
IMG_20190910_134159.jpg
IMG_20190910_134200.jpg
IMG_20190910_134202.jpg
IMG_20190910_134203.jpg
IMG_20190910_134205.jpg
IMG_20190910_134206.jpg
IMG_20190910_134208.jpg
`

All but IMG_20190910_134205.jpg were uploaded fine.
IMG_20190910_134205.jpg was not found in any nextcloud log (via logcat / debug). 
So it seems that this file never got to NC and therefore we cannot warn about a missing/failing upload.

I'll try to further investigate.

**Comment by xNuno** [comment]
Is there any update about this? Can I help somehow?

**Comment by thomas64600** [comment]
Hello, the last update seems to correct the problem, all the Photo came back on the application. thank you very much

**Comment by ne20002** [comment]
I can confirm. All photos missed are now visible in Android app.

**Comment by arkascha** [comment]
This issue is still not resolved. Every time I want to "share" more than just a handful of files with my nextcloud only a subset is uploaded, the rest silently ignored. 
This is very annoying.

**Comment by joshtrichards** [comment]
Let's centralize tracking for this in #10937.
I encourage those following here to subscribe and/or upvote :+1: that issue.
