### ISSUE TITLE
Uploading an image

### ISSUE THREAD

**Issue by markbryanduncan** [nextcloud/android#4478]
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'long com.owncloud.android.datamodel.OCFile.getLastSyncDateForData()' on a null object reference
	at com.owncloud.android.ui.helpers.FileOperationsHelper.lambda$startSyncForFileAndIntent$0$FileOperationsHelper(FileOperationsHelper.java:209)
	at com.owncloud.android.ui.helpers.-$$Lambda$FileOperationsHelper$Q56PsCgyFZxef_IG4gCdZEuyyO8.run(lambda)
	at java.lang.Thread.run(Thread.java:761)

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20190906
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: samsung
Device: m0
Model: GT-I9300
Id: NJH47F
Product: m0xx

************ FIRMWARE ************
SDK: 25
Release: 7.1.2
Incremental: 5b9aa512ea

**Comment by prateekd11** [comment]
I would like to investigate this issue further

**Comment by prateekd11** [comment]
Will you please elaborate this issue? I had no trouble uploading an image.

**Comment by markbryanduncan** [comment]
Hi @prateekd11 

All seems to be working ok now. I did an os update (Running on /e/ OS)

Many Thanks @markbryanduncan
