### ISSUE TITLE
Upload Folder

### ISSUE THREAD

**Issue by ShlomiRex** [nextcloud/android#4481]
### Is your feature request related to a problem? Please describe.
I don't see 'Upload Folder' option to allow uploading a single folder to nextcloud.

### Describe the solution you'd like
Add 'Upload Folder' option.

### Describe alternatives you've considered
This is my first issue. I saw in 'UploadFilesActivity' the function: isFolderPickerMode. I set it true but of course it's not that easy, I need to dig down more. This is also my first attempt at contributing something to anythnig.

### Additional context
I attached an image showing I don't have that option. (Galaxy S5)

![Screenshot_2019-09-09-11-37-09](https://user-images.githubusercontent.com/17744127/64516432-346fad80-d2f7-11e9-8990-a23f33509558.png)

**Comment by joshtrichards** [comment]
The *Upload Files* option opens the file picker and a folder can be selected in the same way as an individual file.
