### ISSUE TITLE
Sono loggato con & senza flag ricordami, faccio scadere la sessione, torno nell'app, l'app si blocca

### ISSUE THREAD

**Issue by amicomed-support** [nextcloud/android#4487]
Sono loggato senza flag ricordami, faccio scadere la sessione, esco dall'app lasciandola aperta per circa 30 secondi, torno nell'app, ed esce fuori l'avviso riportato qua sotto in foto.
Questo avviso rimane all'infinito bloccando di fatto l'utilizzo dell'app, abbiamo testato in due persone.

![image](https://user-images.githubusercontent.com/26152288/64607311-93e9be00-d3c8-11e9-97a8-24d15d0ad9f9.png)

Lo stesso identico problema si verifica quando sono loggato con il flag ricordami.

**Comment by tobiasKaminsky** [comment]
Please fill out the template https://github.com/nextcloud/android/issues/new?labels=bug&template=bug_report.md in english, so that everyone can understand the problem and help you
