### ISSUE TITLE
Registro e arrivo in fondo ma non premo OK, esco e rientro, premo ok e vado avanti.

### ISSUE THREAD

**Issue by amicomed-support** [nextcloud/android#4488]
Registro l'account, compilo il questionario, mi esce la schermata con due opzioni da scegliere: "invia di nuovo l'email" oppure "ok".
Non premo nessun bottone ed esco dall'app lasciandola aperta, poi rientro, premo ok e nel primo tentativo effettuato mi compare questa schermata.

![image](https://user-images.githubusercontent.com/26152288/64607963-e1b2f600-d3c9-11e9-900e-209ecb4cea43.png)

Nel secondo tentativo invece, dopo avere eseguito i medesimi passaggi sopraelencati vengo indirizzato alla schermata principale.

![image](https://user-images.githubusercontent.com/26152288/64608044-1921a280-d3ca-11e9-985c-c4f2d082ea29.png)

**Comment by tobiasKaminsky** [comment]
Please fill out the template https://github.com/nextcloud/android/issues/new?labels=bug&template=bug_report.md in english, so that everyone can understand the problem and help you
