### ISSUE TITLE
Inconsistent action menus in grid vs list view

### ISSUE THREAD

**Issue by ghost** [nextcloud/android#4499]
### Actual behaviour
There are different action menus depending on if I have grid view or list view. 

### Expected behaviour
The menus should have the same basic features; send, open with. share, etc. 
 
At least I would like to be able to share (send) a file with an external app, like a chat program or email, from both grid view and from list view. Grid view is important because the thumbs are too small in list view. 

I think it should be a common use case to want to share a good picture from the grid view or the opened/full screen picture view. 

### Steps to reproduce
1. Open a folder with pictures
2. View in grid and list view
3. Check the different action menus. 

![Screenshot_20190913-151907_Nextcloud](https://user-images.githubusercontent.com/1469150/64866688-352c7a80-d63c-11e9-87bb-8a698ce25213.jpg)

![Screenshot_20190913-151924_Nextcloud](https://user-images.githubusercontent.com/1469150/64866712-407fa600-d63c-11e9-9d1e-fd9670e79aa0.jpg)

![Screenshot_20190913-151939_Nextcloud](https://user-images.githubusercontent.com/1469150/64866736-4a090e00-d63c-11e9-9645-16f3c90d7ad8.jpg)

![Screenshot_20190913-152118_Nextcloud](https://user-images.githubusercontent.com/1469150/64866744-53927600-d63c-11e9-9c5d-c7c2494c4899.jpg)

![Screenshot_20190913-153550_Nextcloud](https://user-images.githubusercontent.com/1469150/64866752-5a20ed80-d63c-11e9-832f-202fd3e1a1c1.jpg)

### Environment data
Android version: 8

Device model: Samsung A5 

Stock or customized system: stock 

Nextcloud app version: 3.8.0 rc3

Nextcloud server version: 16.0.4

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
@nextcloud/designers any feedback/help is highly appreciated. I can't say for sure if the menus should be the same while there are some list-operations (de/select all for example) that can't be used for single files (in the preview)

**Comment by jancborchardt** [comment]
Largely they should probably be the same. Is there a matrix of the different places a menu can show up, crossed with the actions? Then we can check off where an action makes sense and where not, and maybe even what to cut or simplify.

(E.g. on the server we combined "Move or copy", similarly we could combine the "Select all / Deselect all" to be a toggle first selecting all and then deselecting all.)

**Comment by joshtrichards** [comment]
The grid and list menus are consistent now.
