### ISSUE TITLE
App version 1.0.1 incompatible with 9.0.50

### ISSUE THREAD

**Issue by sjurtf** [nextcloud/android#45]
### Actual behaviour
Android app v. 1.0.1
Server v 9.0.50
After the Android app got autoupdated on my phone the server view just tries to refresh but won't update.
Server works fine with OC desktop app on Mac OS X Maverics and NC web-app works fine.
Tried removing the profile in the app and add it back. When NC app tries to conenct to the server the app responds with "Unknown error occurred!" Tested both on WiFi on the same LAN as the server, and via 4G.

### Expected behaviour
Android app 1.0.1 should manage to reload content from server version 9.0.50.
 
### Steps to reproduce
1. Remove server profile in app
2. Add it back
3. "Unknown error occurred!" should appear

### Environment data
Android version:
6.0.1 Marshmallow
Device model: 
Nexus 5X
Stock or customized system:
Stock
Nextcloud app version:
1.0.1
Nextcloud server version:
9.0.50
#### Web server error log
```
Nothing in the access logs or error logs in nginx - nothing in the nextcloud.log
```

#### Nextcloud log (data/nextcloud.log)
```
Could not find the logs under /data or /sdcard/nextcloud or /sdcard/Android/com.nextcloud.client
```

**Comment by tobiasKaminsky** [comment]
I know this is not a good answer, but I have tested it with an emulator and my own device and it works fine.
Soon we will have an official demo-server that can be used to test.

**Comment by sjurtf** [comment]
Ok. I've been getting a new error now as well: "The server took to long to respond". Some of the times the unknown error appears, and others I get the message above.

This new error message adds an entry in the nginx error logfile. I'll look more into that.
2016/06/21 22:57:52 [alert] 27920#0: worker process 11663 exited on signal 11

**Comment by AndyScherzinger** [comment]
Hmmm, not sure about nginx, the only change which might but should not have an impact is the new soft cookie handling introduced in Nextcloud, so pinging @LukasReschke

**Comment by sjurtf** [comment]
Seems like there is a problem that causes nginx to segfault.
It might be related to this: https://trac.nginx.org/nginx/ticket/235.

I added: ssl_session_cache shared:SSL:50m; to http.conf and it I can now successfully connect with the server again. Don't know what in the new version of the app that are causing it though.

**Comment by AndyScherzinger** [comment]
My guess would be: https://github.com/nextcloud/android/commit/0e4243c9961821724581f2622c310fd2078773cd
