### ISSUE TITLE
Mistakes in russian localization

### ISSUE THREAD

**Issue by lukinpv** [nextcloud/android#450]
### Actual behaviour
File res\values-ru\strings.xml contains strings #535-536:
\<string name="welcome_feature_1_title">Безопасный хранилище для всех ваших данных\</string>
\<string name="welcome_feature_1_text">Доступ,  общий доступ &amp; защитита ваших файлов для дома и предприятия\</string>

### Expected behaviour
Strings #535-536 in file res\values-ru\strings.xml should be:
\<string name="welcome_feature_1_title">Безопасное хранилище для всех ваших данных\</string>
\<string name="welcome_feature_1_text">Доступ, общий доступ и защита ваших файлов для дома и предприятия\</string>

### Steps to reproduce
1.  First launch of android app
2.  1st feature on welcome screen in russian environment

### Environment data
Android version:
5.1
Device model: 
Blackview A8
Stock or customized system:
stock
Nextcloud app version:
1.4.0

**Comment by AndyScherzinger** [comment]
Hi @lukinpv,

thanks for the report, I fixed the translation on transifex https://www.transifex.com/nextcloud/nextcloud/translate/#ru/android/101583035 and it will be fixed in the next release of the app.
