### ISSUE TITLE
Pressing details throws you to list view

### ISSUE THREAD

**Issue by Gatak** [nextcloud/android#4500]
### Actual behaviour
Pressing details from an open picture throws you back to list view instead of file details. 

### Expected behaviour
File details screen should open

### Steps to reproduce
1. Open an image
2. Press details 
![Screenshot_20190913-155025_Nextcloud](https://user-images.githubusercontent.com/1469150/64867990-c4d32880-d63e-11e9-8bb8-574edfa4cc55.jpg)
3. You end back in list view. You can open details from there. 
![Screenshot_20190913-155058_Nextcloud](https://user-images.githubusercontent.com/1469150/64868091-f64bf400-d63e-11e9-88e7-743656aca517.jpg)

### Environment data
Android version: 8

Device model: Samsung A5 

Stock or customized system: stock 

Nextcloud app version: 3.8.0 rc3

Nextcloud server version: 16.0.4

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by ezaquarii** [comment]
To be specific, it does not go back. It launches another file list actvity with a wrong view.
Going back actually returns to the picture view.

**Comment by bazio101** [comment]
Pressing details from an open picture works fine after upgrade to 3.10.1 (f-droid version).

**Comment by tobiasKaminsky** [comment]
Works again.
