### ISSUE TITLE
Enhancement: Exif data in file details

### ISSUE THREAD

**Issue by Gatak** [nextcloud/android#4501]
-deleted-

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky I sescond @Gatak's suggestion while that would mean that we get this info from the server (a thumbnail doesn't ship this info)

**Comment by Gatak** [comment]
I suppose two options are possible. Either download full image  or ask the server. First case might be unwanted on mobile data or otherwise slow connections.

Is exif data stored in any particular place in files? Could the app in that case request only relevant parts to avoid downloading it all.

**Comment by AndyScherzinger** [comment]
If the app should do it on their own then it would need to download the whle file which I vote to not implement since my DSLM's jpg images are rather large (like yours I guess). SO this would be overpowered and costly (band-width), so if the server can display it then it should be made available to the clients via an API in case that isn't already available.

@tobiasKaminsky do you know if this info is accessible for the clients?

**Comment by Gatak** [comment]
Fully agree with you there. An API to read this data would of course be really nice.

**Comment by AndyScherzinger** [comment]
> Fully agree with you there. An API to read this data would of course be really nice.

If the server displays it within the details page then I guess the data is avalaible, I just don't know if this info is available via API.

**Comment by tobiasKaminsky** [comment]
There is no public api available right now: https://github.com/gino0631/nextcloud-metadata
As this is also no official app, I see the problem that it might be not compatible / non working at some time in future and thus we either have to support this app on our own (increasing work load) or we then have to remove it again (which is bad UX).
So while I do agree that this is nice for certain file types and scenarios I do not want to rely on the app for above reasons.

**Comment by Spartachetto** [comment]
As far as I understood, there was some discussion to include capability of reading EXIF metadata in the server.

Have a look at nextcloud/server#5106

**Comment by tobiasKaminsky** [comment]
Ah, good to know.
Once this is in server we can also include it also in our app.

**Comment by Gatak** [comment]
Closing. Don't want to be affiliated with Nextcloud

**Comment by szaimen** [comment]
@ghost this was a great feature request. Why did you close it?
