### ISSUE TITLE
Crashes after splash screen

### ISSUE THREAD

**Issue by nbuechner** [nextcloud/android#4503]
### Actual behaviour
- Tell us what happens
The app crashes after splash screen.

### Expected behaviour
- Tell us what should happen
The app should start.
 
### Steps to reproduce
1. Install app
2. Login
3. Restart app

### Environment data
Android version:
9
Device model: 
Xiaomi MiPad 4

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
Not found

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by nbuechner** [comment]
Version 3.8.0

**Comment by ezaquarii** [comment]
Not enough information to proceed.
