### ISSUE TITLE
Upload failing due to connection error on version 3.8.0

### ISSUE THREAD

**Issue by nunesgh** [nextcloud/android#4510]
### Actual behaviour
- Uploads are failing on the latest version of the app (3.8.0);
- The app is reporting a "Connection error".

### Expected behaviour
- Uploads should complete without errors, as was the case on prior versions.
 
### Steps to reproduce
1. Just try to upload a file.

### Environment data
Android version: 9;

Device model: Motorola G6 Play;

Stock or customized system: stock;

Nextcloud app version: 3.8.0;

Nextcloud server version: 16 (with Cloudflare SSL certificate and using a custom port).

**Comment by ChrisB85** [comment]
Same problem here with auto-sync feature. Some files are sent without problems and others fails with "Connection error". Manual uploads works as expected.

Nextcloud android app 3.8.0 on Android 9; Pocophone F1.
Nextcloud server app 16.04 with Cloudflare SSL.

**Comment by bbbf0621** [comment]
Its not only the auto-sync function. If you upload file manually with WiFi, it doesn't work. It works only if I turn off the WiFi and use Cellar network.

Nextcloud android app 3.8.0. Oneplus 6
Nextcloud server app 15.0.11

**Comment by bubonic** [comment]
I've having the same issue as of today. I even tried  to upgrade the Nextcloud server to 16.0.4 today. I can't upload any files from my Google Pixel C Tablet or my Google Pixel Phone. 

Nextcloud android app version 3.8.0 Google Pixel & Google Pixel C Tablet
Nextcloud server app 16.0.4

Please fix. 

Ty

**Comment by AndyScherzinger** [comment]
Pinging @tobiasKaminsky while my guess is (due to wifi versus cellular) that this is rather a server config issue (not handling http chunking correctly).

**Comment by nunesgh** [comment]
I don't think it is a server side issue. It has started after updating the Android app and devices on the previous version were still able to upload correctly.

**Comment by AndyScherzinger** [comment]
My comment was rather about @bubonic and @bbbf0621. Afaik there haven't been any changes to auto upload (except for general TLS 1.3 support), which is why I pinged @tobiasKaminsky for further commenting.

**Comment by patlecat** [comment]
Same problem here, not one upload worked with v3.8.

**Comment by DataNinjaOfAppliedAlchemy** [comment]
I see the same issue. Uploads work after first installing the app. After closing and reopening the app, uploads fail unless using cellular service. Reverting to 3.7.2 fixes the problem, so seems to be introduced in 3.8.0.
I've seen this on both a Samsung S10 and kindle fire (fire does not have cell service so no uploads are possible until downgrading to 3.7.2). 
Other oddities are that I can still change folder names, add or remove folders and even delete files, but I can not upload new files.

**Comment by nunesgh** [comment]
> Other oddities are that I can still change folder names, add or remove folders and even delete files, but I can not upload new files.

Same issue here.

How is it possible to revert the app to version 3.7.2?

**Comment by DataNinjaOfAppliedAlchemy** [comment]
I downloaded the 3.7.2 apk from f-droid. Previous versions are listed at the bottom of the app description page.
Fair warning, I had to uninstall next cloud and reinstall it using  the apk, which lost all of my synched files and settings.

James Gwaltney

Software Analyst



Eurofins TestAmerica

6712 Benjamin Rd.

Tampa, FL 33634

USA



Phone: 813-205-3405



E-mail: james.gwaltney@testamericainc.com

www.EurofinsUS.com<http://www.EurofinsUS.com> | www.TestAmericainc.com<http://www.TestAmericainc.com>



￼  ￼

________________________________

**Comment by damianpeterson** [comment]
Confirming that uploads are no longer working with v3.8 on naked android 9 and 10.

**Comment by rarealphacat** [comment]
Switched back to 3.7.2 and worked flawlessly.
 Upload only works after fresh install thorough WiFi. Shows connection error after reopen the nectcloud app to both auto upload and manual upload. Mobile data uploads without problems.

**Comment by MikaelMollberg** [comment]
I have the same issue. I had no issues prior to updating the app to 3.8

Uploading files on the same device using the website instead of the app works. Auto upload and regular upload fails in the app with "Connection error"

**Comment by fmartinou** [comment]
Same problem for me.  
_Connection error_ if I switch the WIFI on (it only works with cellular data).

My configuration:
- Xiaomi MI8
- MIUI 10.3
- Android 9
- Nexcloud Server version: 17.0.0
- Nexcloud App version: 3.8.0

When do you think it'll be fixed?

**Comment by patlecat** [comment]
Any idea how long a fix might take? The app is not usable for many ppl as it now.

**Comment by tobiasKaminsky** [comment]
Can you create us a test account, test if the problem occurs also there and if so send the credentials to tobias at nextcloud dot com with a reference to this issue?

**Comment by DataNinjaOfAppliedAlchemy** [comment]
That fixed it for me too. Not sure why the newer app fails, but the older one passes...

**Comment by disaderp** [comment]
I believe that this PR already fixes this issue: #4528

**Comment by patlecat** [comment]
What was fixed and where? Using Cloudflare isn't a bug of the users. And I can't see where I would use Cloudflare at all. So nothing is fixed for me. The server still isn't available when I try to log into the app.

**Comment by disaderp** [comment]
This issue was about failing uploads. It turned out, all of the reporters were using Cloudflare in front of their installation of Nextcloud, which blocked uploads due to unrecognized user agent. 
If your server is unavailable when you log into the app, it seems like it's unrelated to this issue.

**Comment by nunesgh** [comment]
Any updates on this issue?

**Comment by TobiasWenzel** [comment]
Yesterday evening I upgraded to version 3.8.1 and since then Nextcloud is uploading gigabytes of photos which it missed during the last weeks. So it seems this issue is finally fixed. :-)
Just don't know why it's not yet marked as fixed.

**Comment by nunesgh** [comment]
The issue was not even assigned to the version 3.8.1 milestone. I think this is the reason why it was not marked as fixed with that release - in the case it is really fixed.

So, does it mean it is now possible to reactivate Cloudflare's Browser Integrity Check?

**Comment by TobiasWenzel** [comment]
Although I never checked that my Nextcloud provider has Cloudflare, I would assume so - according to [disaderp's reply above](#issuecomment-537137676).

**Comment by DataNinjaOfAppliedAlchemy** [comment]
It does appear to be fixed. I turned the browser integrity check back on, and it uploads fine now using 3.8.1.

**Comment by nunesgh** [comment]
I have also reactivated Cloudflare's Browser Integrity Check and the issue no longer exists on version 3.8.1!

**Comment by AndyScherzinger** [comment]
Thanks for the feedback folks 👍
I'll close the issue for now even though I am not aware of a dedicated fix for this issue. 

Maybe @tobiasKaminsky has some more information on this. 

Please reopen and report back in case the issue comes back.

**Comment by le5emeaxe** [comment]
Same issue with 3.8.1 with lineageos 16 on PocoF1. Work with 3.7.2
I use my own nextcloud instance with nginx reverse proxy.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky any idea what might have changed between 3.7 and 3.8 with respect to uploads?
