### ISSUE TITLE
 Android mobile app high background data usage

### ISSUE THREAD

**Issue by sm8ps** [nextcloud/android#4511]
### Steps to reproduce
1. Install NC app on Android 9 and connect to personal NC instance without any automatic uploads configured. Calendar and contacts are synched through DAVx5.
2. Wait some for undetermined amount of time. Use the NC instance by synching data from other devices (laptops).
3. Check data usage of NC app. Here: 630 MB in approximately 12 hours.
4. Check file space usage unter 'Android/media/com.nextcloud.client/' and 'Android/data/com.nextcloud.client/' which is almost nil.
5. Turn of background data to stop the wasting of bandwidth.
6. Verify that the NC app functions just the same.
NB: I remember having the _exact_ same issue on my old phone with Android 5.0.
It seems to be very much the same as described in the now closed #3123.

### Expected behaviour
The app should not use any noticeable amount of data when not manually down- or uploading files.

### Actual behaviour
The NC app on Android 9 uses hundreds of MB background data for nothing, i.e. without up- or downloading any traceable user data. This happens  without any image upload or any other synching. The app is solely used for remote data access, i.e. browsing the NC data cloud.
What is more, the exact same behaviour was observed some years ago on Android 5! The work-around consists in denying the app access to background data.

## Server configuration detail

**Operating system:** Linux 4.15.0-62-generic #69~16.04.1-Ubuntu SMP Fri Sep 6 02:43:35 UTC 2019 x86_64

**Webserver:** nginx/1.17.3 (fpm-fcgi)

**Database:** mysql 10.3.17

**PHP version:** 

7.2.19-0ubuntu0.18.04.2
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, apc, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, inotify, intl, json, exif, mysqli, OAuth, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 15.0.5 - 15.0.5.3

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from v13

**Where did you install Nextcloud from:** nextcloud.com

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.1.0
 - activity: 2.8.2
 - apporder: 0.6.0
 - audioplayer: 2.7.2
 - bruteforcesettings: 1.4.0
 - calendar: 1.6.5
 - cloud_federation_api: 0.1.0
 - comments: 1.5.0
 - contacts: 3.1.3
 - dav: 1.8.1
 - deck: 0.6.6
 - federatedfilesharing: 1.5.0
 - federation: 1.5.0
 - files: 1.10.0
 - files_external: 1.6.0
 - files_inotify: 0.1.4
 - files_pdfviewer: 1.4.0
 - files_sharing: 1.7.0
 - files_texteditor: 2.7.0
 - files_trashbin: 1.5.0
 - files_versions: 1.8.0
 - files_videoplayer: 1.4.0
 - firstrunwizard: 2.4.0
 - gallery: 18.2.0
 - grauphel: 0.7.2
 - groupfolders: 3.0.2
 - impersonate: 1.2.0
 - issuetemplate: 0.5.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.3.0
 - nextcloud_announcements: 1.4.0
 - notes: 3.0.1
 - notifications: 2.3.0
 - oauth2: 1.3.0
 - password_policy: 1.5.0
 - provisioning_api: 1.5.0
 - qownnotesapi: 19.4.0
 - quota_warning: 1.4.0
 - serverinfo: 1.5.0
 - sharebymail: 1.5.0
 - support: 1.0.0
 - survey_client: 1.3.0
 - systemtags: 1.5.0
 - tasks: 0.11.1
 - theming: 1.6.0
 - twofactor_backupcodes: 1.4.1
 - twofactor_totp: 2.1.2
 - unsplash: 1.1.3
 - updatenotification: 1.5.0
 - workflowengine: 1.5.0
Disabled:
 - admin_audit
 - encryption
 - files_markdown
 - lsd
 - ownpad
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "lxcnextcloud.okunterhof5.ch",
        "lxcNextCloud",
        "nextcloud.wildi.name",
        "lxcnextcloud"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "http:\/\/lxcnextcloud.okunterhof5.ch",
    "dbtype": "mysql",
    "version": "15.0.5.3",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "logtimezone": "Europe\/Zurich",
    "loglevel": "2",
    "log_rotate_size": 10485760,
    "skeletondirectory": "",
    "share_folder": "\/Mit mir geteilt",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "tls",
    "mail_smtpauth": 1,
    "mail_smtpport": "587",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "force_language": "de",
    "trashbin_retention_obligation": "disabled",
    "versions_retention_obligation": "disabled",
    "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
    "forwarded_for_headers": [
        "HTTP_X_FORWARDED",
        "HTTP_FORWARDED_FOR"
    ],
    "auth.bruteforce.protection.enabled": false,
    "maintenance": false,
    "filelocking.enabled": "true",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "timeout": 0
    },
    "theme": ""
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** 

## Client configuration

**Browser:** 

**Operating system:** 

## Logs

<details><summary>Web server error log</summary>

```
There is nothing in /var/log/nginx/error.log pertaining to the IP address of the Android device which is 192.168.1.151. There regularly are some entries  like the following in /var/log/nginx/access.log, roughly in the intervals set in DAVx5.

192.168.1.102 - USER [15/Sep/2019:04:08:43 +0200] "PROPFIND /remote.php/dav/addressbooks/users/NAME/CALENDAR1/ HTTP/1.0" 207 1593 "-" "DAVx5/2.5.4.1-ose (2019/08/27; dav4jvm; okhttp/3.12.3) Android/9" "192.168.1.151"
192.168.1.102 - USER [15/Sep/2019:04:08:44 +0200] "PROPFIND /remote.php/dav/calendars/NAME/CALENDAR2/ HTTP/1.0"
 207 1185 "-" "DAVx5/2.5.4.1-ose (2019/08/27; dav4jvm; okhttp/3.12.3) Android/9" "192.168.1.151"
192.168.1.102 - USER [15/Sep/2019:04:08:45 +0200] "PROPFIND /remote.php/dav/calendars/NAME/CALENDAR3/ HTTP/1.0" 207 1442 "-" "DAVx5/2.5.4.1-ose (2019/08/27; dav4jvm; ok
http/3.12.3) Android/9" "192.168.1.151"
192.168.1.102 - USER [15/Sep/2019:04:08:45 +0200] "PROPFIND /remote.php/dav/calendars/NAME/CALENDAR4/ HTTP/1.0" 207 1451 "-" "DAVx5/2.5.4.1-ose (2019/08/27; 
dav4jvm; okhttp/3.12.3) Android/9" "192.168.1.151"
192.168.1.102 - - [15/Sep/2019:04:08:48 +0200] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.0" 200 3717 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:69.0) Gecko/20100101
 Firefox/69.0" "192.168.1.169"
192.168.1.102 - USER [15/Sep/2019:04:08:53 +0200] "PROPFIND /remote.php/dav/addressbooks/users/NAME/ADRBOOK1/ HTTP/1.0" 207 1608 "-" "DAVx5/2.5.4.1-ose (2019/08/27; dav4jvm; okht
tp/3.12.3) Android/9" "192.168.1.151"
192.168.1.102 - USER [15/Sep/2019:04:09:05 +0200] "PROPFIND /remote.php/dav/addressbooks/users/NAME/ADRBOOK2/ HTTP/1.0" 207 1597 "-" "DAVx5/2.5.4.1-ose (2019/08/27; dav4jvm; okhttp/3.12.3) Android/9" "192.168.1.151"
192.168.1.102 - - [15/Sep/2019:04:09:05 +0200] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.0" 200 3717 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:69.0) Gecko/20100101
 Firefox/69.0" "192.168.1.169"
192.168.1.102 - USER [15/Sep/2019:04:09:05 +0200] "PROPFIND /remote.php/dav/addressbooks/users/NAME/ADRBOOK3/ HTTP/1.0" 207 1614 "-" "DAVx5/2.5.4.1-ose (2019/08/27; dav4jvm
; okhttp/3.12.3) Android/9" "192.168.1.151"
192.168.1.102 - USER [15/Sep/2019:04:09:15 +0200] "PROPFIND /remote.php/dav/addressbooks/users/NAME/ADRBOOK4/ HTTP/1.0" 207 1593 "-" "DAVx5/2.5.4.1-ose (2019/08/27; dav4jvm; okhttp/3.12.3) Android/9" "192.168.1.151"



```
</details>

<details><summary>Nextcloud log</summary>

```
There is not a single entry pertaining to the IP address of the Android device in question.
```
</details>

<details><summary>Browser log</summary>

n.a.
</details>

**Comment by vKnmnn** [comment]
I was going to open a new issue, but i see this one's already here.
I have the same thing going on in Nextcloud app v3.10.1

**Comment by ezaquarii** [comment]
I noticed that the app pings the server regularly. This could be the problem.

**Comment by tobiasKaminsky** [comment]
> I noticed that the app pings the server regularly. This could be the problem.

**Comment by sm8ps** [comment]
I just read through #3123 in full detail and would like to add that I had neither any auto-upload like picture folders nor anything related to contacts done via the Nextcloud app as I use DAVx5 for that. As mentioned in my original report the work-around was to disable access to background data for the Nextcloud app so I do not see the problem anymore. However, I might miss out on some features -- like what?

**Comment by alajovic** [comment]
Reporting this on account of a friend that seems to have been bitten by this problem, too. NextCloud Android app recently started using huge amounts of data in the background (more than 1 GB in the last few days), for no apparent reason. I have access to server logs (full history) and Android app logs (for the past few hours). What follows is my basic dissection of the logs. Feel free to ask me for more information.

The server logs for the days preceding the problem only show rather normal traffic: there's an occasional PROPFIND, but only for certain files/directories (likely for those that have been downloaded to the device). Example:
```
[24/Apr/2020:10:21:15 +0200] "PROPFIND /remote.php/webdav/documents/ HTTP/1.1" 207 367 0
```
But then, suddenly, the app started PROPFINDing *everything*. It is recursing through the entire directory structure, and doing it repeatedly. An example for just a single path:
```
[01/May/2020:20:18:31 +0200] "PROPFIND /remote.php/webdav/some/path/ HTTP/1.1" 207 841 0
[01/May/2020:20:18:32 +0200] "PROPFIND /remote.php/webdav/some/path/ HTTP/1.1" 207 7856 0
[01/May/2020:20:33:24 +0200] "PROPFIND /remote.php/webdav/some/path/ HTTP/1.1" 207 841 0
[01/May/2020:20:33:24 +0200] "PROPFIND /remote.php/webdav/some/path/ HTTP/1.1" 207 7856 0
[01/May/2020:20:38:53 +0200] "PROPFIND /remote.php/webdav/some/path/ HTTP/1.1" 207 841 0
[01/May/2020:20:38:53 +0200] "PROPFIND /remote.php/webdav/some/path/ HTTP/1.1" 207 7856 0
[01/May/2020:20:56:09 +0200] "PROPFIND /remote.php/webdav/some/path/ HTTP/1.1" 207 841 0
[01/May/2020:20:56:09 +0200] "PROPFIND /remote.php/webdav/some/path/ HTTP/1.1" 207 7856 0
[01/May/2020:20:58:40 +0200] "PROPFIND /remote.php/webdav/some/path/ HTTP/1.1" 207 841 0
[01/May/2020:20:58:40 +0200] "PROPFIND /remote.php/webdav/some/path/ HTTP/1.1" 207 7856 0
```
Neither the directory nor the files under this path have been updated in over a year, and yet the NC app is querying it again and again. I counted 340 PROPFINDs on this particular path in the last 6 days. In total, there were almost 75k PROPFINDs in the same period.

If I search the app log for this same path, I find the following repeating pattern:
```
2020-05-06T19:14:40.170+0200;D;RefreshFolderOperation;Checking changes in user@host/some/path/
2020-05-06T19:14:40.173+0200;D;OwnCloudClient #0;REQUEST PROPFIND /remote.php/webdav/some/path/
2020-05-06T19:14:40.501+0200;I;RefreshFolderOperation;Checked user@host/some/path/ : changed
2020-05-06T19:14:40.516+0200;D;OwnCloudClient #0;REQUEST PROPFIND /remote.php/webdav/some/path/
2020-05-06T19:14:41.085+0200;I;ReadFolderRemoteOperation;Synchronized /some/path/: Operation finished with HTTP status code 207 (success)
2020-05-06T19:14:41.085+0200;D;RefreshFolderOperation;Synchronizing user@host/some/path/
2020-05-06T19:14:41.113+0200;D;RefreshFolderOperation;Remote folder /some/path/ changed - starting update of local data 
2020-05-06T19:14:41.157+0200;D;FileDataStorageManager;Saving folder /some/path/ with 7 children and 0 files to remove
2020-05-06T19:14:41.201+0200;D;FileDataStorageManager;Sending 8 operations to FileContentProvider
2020-05-06T19:14:41.202+0200;D;FileContentProvider;applying batch in provider com.owncloud.android.providers.FileContentProvider@b420dba (temporary: false)
2020-05-06T19:14:41.223+0200;D;FileContentProvider;applied batch in provider com.owncloud.android.providers.FileContentProvider@b420dba
2020-05-06T19:14:41.254+0200;D;FileSyncAdapter;Send broadcast com.owncloud.android.syncadapter.FileSyncAdapter.EVENT_FULL_SYNC_FOLDER_CONTENTS_SYNCED
```
The same sequence of events repeats over and over again with a time interval of somewhere between 5 and 20 minutes (it seems quite random).

One final note, in the app log, there are two recurring errors:
```
2020-05-06T20:46:54.074+0200;E;FileDisplayActivity;Access to unexisting list of files fragment!!
```
and
```
2020-05-06T20:46:54.074+0200;E;FileDisplayActivity;Still have a chance to lose the initialization of list fragment >(
```
This might have something to do with the problem (or not).
I hope this helps. If you need additional data, let me know.

**Comment by tobiasKaminsky** [comment]
Hm. We are doing in background, when on wifi, a check for all downloaded files to rescan if they need to be updated.
Are those files/folders downloaded to app?

**Comment by alajovic** [comment]
@tobiasKaminsky, this massive synchronization was obviously not performed over wifi, which is why my friend even noticed it in the first place. The last of the regular traffic before the onset of the problem was such (wifi/mobile data status in first column):
```
wifi [01/May/2020:13:29:50 +0200] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 376 0
wifi [01/May/2020:13:44:43 +0200] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 376 0
wifi [01/May/2020:13:44:44 +0200] <about 30 PROPFINDs for downloaded files>
wifi [01/May/2020:13:59:56 +0200] <PROPFINDs for /, about 3-4 per hour>
wifi [01/May/2020:16:21:29 +0200] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 376 0
data [01/May/2020:20:17:26 +0200] "GET /index.php/avatar/username/384 HTTP/1.1" 304 - 0
```
The last request (for avatar) was the first in the series that started with the massive recursive synchronization.

To answer your question, only a few dozen files are downloaded to the phone (this was checked with the file browser). The path for which I reported the repeated PROPFINDs in my previous post is not among those. That is, neither the folder nor its contents have been downloaded to the phone.

**Comment by alajovic** [comment]
I don't know if it's of any use for you, but here is the sequence of server log entries from the start of the massive synchronization (I have redacted a few path names):
```
[01/May/2020:20:17:26 +0200] "GET /index.php/avatar/username/384 HTTP/1.1" 304 - 0
[01/May/2020:20:17:26 +0200] "GET /ocs/v1.php/cloud/user?format=json HTTP/1.1" 200 577 0
[01/May/2020:20:17:26 +0200] "GET /ocs/v1.php/cloud/user?format=json HTTP/1.1" 200 577 0
[01/May/2020:20:17:27 +0200] "PROPFIND /remote.php/webdav/abc/def/ HTTP/1.1" 207 951 0
[01/May/2020:20:17:27 +0200] "PROPFIND /remote.php/webdav/abc/def/ HTTP/1.1" 207 951 0
[01/May/2020:20:17:28 +0200] "PROPFIND /remote.php/webdav/abc/def/ HTTP/1.1" 207 4877 0
[01/May/2020:20:17:28 +0200] "PROPFIND /remote.php/webdav/abc/def/ HTTP/1.1" 207 4877 0
[01/May/2020:20:17:28 +0200] "GET /ocs/v2.php/apps/files_sharing/api/v1/shares?path=%2Fabc%2Fdef%2F&reshares=true&subfiles=true HTTP/1.1" 200 138 0
[01/May/2020:20:17:29 +0200] "GET /ocs/v2.php/apps/files_sharing/api/v1/shares?path=%2Fabc%2Fdef%2F&reshares=true&subfiles=true HTTP/1.1" 200 138 0
[01/May/2020:20:18:00 +0200] "GET /ocs/v1.php/cloud/user?format=json HTTP/1.1" 200 577 0
[01/May/2020:20:18:01 +0200] "PROPFIND /remote.php/webdav/abc/def/ HTTP/1.1" 207 951 0
[01/May/2020:20:18:01 +0200] "GET /ocs/v2.php/apps/files_sharing/api/v1/shares?path=%2Fabc%2Fdef%2F&reshares=true&subfiles=true HTTP/1.1" 200 138 0
[01/May/2020:20:18:05 +0200] "GET /status.php HTTP/1.1" 200 170 0
[01/May/2020:20:18:06 +0200] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 835 0
[01/May/2020:20:18:06 +0200] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 55536 2
[01/May/2020:20:18:09 +0200] "PROPFIND /remote.php/webdav/abc/ HTTP/1.1" 207 840 0

```
After this, it continued PROPFINDing the contents of the `abc` directory recursively, later proceeding on to the next top-level folder, recursing through that one, and so on.

**Comment by alajovic** [comment]
Anyone have any updates? Please let me know if additional info is needed to diagnose this.

**Comment by vKnmnn** [comment]
The app had 2.54GB of background data usage last month.

**Comment by motey** [comment]
Here same on one of the devices connected to our Nextcloud running version 3.15.0 connected to Nextcloud 20.0.7

**Comment by mandavister** [comment]
Data usage reported 1,67 GB for last month while auto upload is active with a handful of images and using daily contact data upload of ~ 180kB each / synchronisation of contacts&calender using DAVx5. Nextcloud 20.0.6 / App 3.14.1. Data usage looks pretty evenly distributed over the month. It's by far my app with the highest data usage while rarely used.

**Comment by HansAschauer** [comment]
I was bitten by this bug a few days ago, while on vacation, i.e. without regular access to wifi.
Android App version: 3.22.2
I am not sure about the version of the server, since the app connects to different servers.
One additional data point: before going on vacation, I tested access to my home-based server through Wireguard. As far as I remember, Wireguard was disabled while on vacation, but maybe this confused the "on-wifi" detection?
See the screenshots on how dramatic the data usage was, and that the app recognized the data usage as in foreground...

![Screenshot_20221107-071800](https://user-images.githubusercontent.com/19638185/200240458-d692694d-50bb-4c55-bd13-f0affc79a0fd.png)
![Screenshot_20221107-072022](https://user-images.githubusercontent.com/19638185/200240740-a5a15ba7-a16e-472d-adc2-7070d00dc321.png)

**Comment by AlvaroBrey** [comment]
This should be greatly alleviated by #10996 if merged
