### ISSUE TITLE
Random sound and vibration events

### ISSUE THREAD

**Issue by danielb42** [nextcloud/android#4514]
### Actual behaviour
- Since upgrading to 3.8.0, on some actions within the NC app a notification beep is played (resp. vibration if phone set silent). Unfortunately I don't see any pattern yet as to when this happens, and cannot reproduce the behaviour consistently, but I noticed it several times by now at least on...

* opening the NC app
* entering Settings view
* un-selecting images in folder view

### Expected behaviour
- no beeps/vibrations

### Steps to reproduce
0. upgrade to nc 3.8.0
1. ??? (maybe force-close app, open, enter settings, un/select some images, wish I could tell you...)

### Environment data
Android version: 9.0

Device model: Samsung Galaxy S9

Stock or customized system: stock

Nextcloud app version: 3.8.0

Nextcloud server version: 16.0.4

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky any ideas as to what might have caused a change in behavior?

@danielb42 besides the update to 3.8.0 did anything else change regardinig the device? for examplpe a OS update?

**Comment by danielb42** [comment]
@AndyScherzinger on Sept14 (the day when I also updated NC) there was an Android security patch to level Sept1. Besides that no change to device or OS. However, the mysterious beep events did never occur anywhere outside NC app yet - and inside NC they were just perfectly aligned with touching for the mentioned actions, so I don't think they come from something else in the background or the like. Thanks!

**Comment by tobiasKaminsky** [comment]
No idea, we do did not changed anything in this matter.



>     * un-selecting images in folder view

I am not even sure if we could trigger a sound here, but we definitively do not.

**Comment by danielb42** [comment]
This is so strange. Anyway it hasn't happened again. \*shrug* 
I think we should close and forget..

**Comment by tobiasKaminsky** [comment]
If it happens again, just re-open :-)

**Comment by bjoernhohe** [comment]
Sounds strange but the solution is easy - I had my credit card inside the case and it seems to trigger the NFC...but only in the nextcloud app

**Comment by AlvaroBrey** [comment]
> Sounds strange but the solution is easy - I had my credit card inside the case and it seems to trigger the NFC...but only in the nextcloud app

Reference: https://github.com/nextcloud/android/issues/8606. Vibration should only happen in the login screen.
