### ISSUE TITLE
Music Player gets unaccessible although playback is on

### ISSUE THREAD

**Issue by archont00** [nextcloud/android#4515]
### Actual behaviour
* Tap on a music file to start Music Player.
* Press "back" arrow on top left to browse other files within Nexctloud Files.
* **There is no way to to get back to the Music Player although the playback continues.**
* **Tapping on "Music Player" notification in Android opens Nextcloud Files App, but not the Music Player.**

### Expected behaviour
* When Music Player is on, an item in Nextcloud menu should appear to be able to switch to it.
* Tapping on Music Player notification should open Music Player directly.
 
### Steps to reproduce
See above.

### Environment data
Android version: 8.0.0

Device model: Samsung Galaxy S7

Stock or customized system: Stock

Nextcloud app version: 3.8.0

**Comment by ezaquarii** [comment]
@tobiasKaminsky Background playback fiasco strikes back.

I'd reconsider support for it in #4208.

**Comment by ezaquarii** [comment]
@archont00 Now you can close the player with STOP button in the notification.
