### ISSUE TITLE
Move uploaded file to program folder not working

### ISSUE THREAD

**Issue by khartahk** [nextcloud/android#452]
### Actual behaviour
When I take the picture, it is uploaded to the server but the file remains in the DCIM subfolder

### Expected behaviour
After the picture is uploaded it should be moved to the Android/data/com.nextcloud... folder
 
### Steps to reproduce
1. Take a picture
2. Wait for it to upload
3. Check the DCIM subfolder and the file is still there but it's not in the Android/data..nextcoud folder

### Environment data
Android version:
6.0
Device model: 
HTC One m8
Stock or customized system:
Stock but rooted
Nextcloud app version:
1.4.x - currently latest release
Nextcloud server version:
10.0.2 (stable)

Right now I've downgraded to 1.3.1 where this was working and the pictures were moved to sdcard/nextcloud folder. Which I also prefer as the pictures in Android/data are not displayed in the gallery app. But I'll file another bug as this is a separate issue.

**Comment by AndyScherzinger** [comment]
Hi @khartahk,

what did you set as upload behavior in the setting s screen?

**Comment by khartahk** [comment]
I've set it to move to program folder.

**Comment by Bart873** [comment]
I can reproduce this bug 100%. See also the more overall issue #474 I just filed.

### Environment data
Android version: 6.0.1
Device model: Samsung Galaxy S4 Mini (GT-I9195)
Stock or customized system: Cyanogenmod 13.0 (Android 6.0.1)
Nextcloud app version: 1.4.0 
Nextcloud server version: 11.0.0

**Comment by OlivierS1** [comment]
Same behavior with Nextcloud app 1.4.1 RC1

Android version:
6.0
Device model: 
LG-G3 LG-D852
Stock or customized system: 
Stock
Nextcloud app version: 
1.4.1 RC1
Nextcloud server version: 
OC 9.1

**Comment by ncyclon** [comment]
1.4.1 rc2, Samsung Galaxy s6, Android 6.0.1, OC 9.1.2, same problem here.

**Comment by tobiasKaminsky** [comment]
@OlivierS1 @ncyclon can you try the latest dev version? This bug should be solved, but just to verify it.

**Comment by ncyclon** [comment]
@tobiasKaminsky 
Can't check, the version by this link https://download.nextcloud.com/android/dev/latest.apk crashing on my Samsung Galaxy S6 Edge (Android 7.0)

**Comment by tobiasKaminsky** [comment]
@ncyclon now there is a new version.
Sorry for the trouble, but can you test it again? :-)

**Comment by ncyclon** [comment]
Everything works fine, thx)

**Comment by tobiasKaminsky** [comment]
Glad to hear.
