### ISSUE TITLE
Not all requests use the proper user-agent

### ISSUE THREAD

**Issue by darix** [nextcloud/android#4522]
### Actual behaviour
- Some requests come in with "Jakarta Commons-HttpClient/3.1" as User-Agent
  I think mostly requests for /index.php/204 during uploads are affected.

### Expected behaviour
- All requests should use "Mozilla/5.0 (Android) Nextcloud-android/3.8.0"

### Steps to reproduce
1. Install and use app 

### Environment data
Android version: 9.0

Device model: nokia 8

Stock or customized system: stock

Nextcloud app version: latest

Nextcloud server version: latest

**Comment by AndyScherzinger** [comment]
Nice catch @darix 

cc @tobiasKaminsky since you handled agent-string related stuff in the past ❤️

**Comment by tobiasKaminsky** [comment]
Indeed there was a change.
Is this an urgent problem for you? Do you anything related with the user agent?
Of course we will change it.

**Comment by darix** [comment]
I was just confused who would regularly poll my nextcloud with some 
basic java app. when I blocked access to it because it annoyed me, I 
noticed uploads are failing. So now I removed the block for jakarta and 
everything is working again.
