### ISSUE TITLE
Better error message if sync failes because FS can't handle long file names

### ISSUE THREAD

**Issue by guettli** [nextcloud/android#4526]
### Is your feature request related to a problem? Please describe.

I have files with long file names:

    kinder/Michael_Ende_gelesen_von_Thomas_Schendel-Jim_Knopf_und_die_Wilde_13_1._Das_Meeresleuchten/4.Viertes_Kapitel,_in_dem_die_Reisenden_eine_seltsame_Bekanntschaft_machen,_die_sie_zu_einem_Abstecher_ins_Barbarische_Meer_veranlasst.ogg

If I try to sync these files via the android app. It fails.

It fails because my external sd card uses a fat filesystem.

It is 100% ok that it fails. 

But a better error message would help very much.

I guess it would even help you, since a lot of vague complaints would
get much more precise.

### Describe the solution you'd like

For example a message like this:

> Sync failed. The file name is long. It is likely that your storage does not support long file names. The file system type of your storage is NAME_OF_FILESYSTEMTYPE

**Comment by joshtrichards** [comment]
Related: #3197

Might be addressed by #11384.

**Comment by joshtrichards** [comment]
Fixed in #11384
