### ISSUE TITLE
Accounts added by token does not work

### ISSUE THREAD

**Issue by BuZZ-dEE** [nextcloud/android#4529]
### Actual behaviour
I tried to add my 3 Nextcloud accounts using an app token to the client.
1. Added first account by token. App reloaded, I had to enter it again. Then it worked.
2. Added first account by token. App reloaded, I had to enter it again. Then it worked., but first account is gone.
3. Added third account by token. App reloaded, I had to enter it again. Then it worked., but also second account is gone.
-> only the last added account is now in the app

### Expected behaviour
Three accounts added by token.
 
### Steps to reproduce
Don't know. Try to add 3 accounts by token to a fresh installed Nextcloud client.

### Environment data
Android version: 9

Device model: OnePlus 7 Pro

Stock or customized system: Oxygen OS

Nextcloud app version: 3.8.0

Nextcloud server version: 3 different Nextcloud server. Don't know the version.

#### Web server error log
Don't have any logs.

#### Nextcloud log (data/nextcloud.log)
Can not find a `nextcloud.log` file on my device.

**Comment by ezaquarii** [comment]
Reproducible on master!

**Comment by ezaquarii** [comment]
@BuZZ-dEE 
1. add new account
2. kill the app
3. add 2nd account

This should work around the problem.
