### ISSUE TITLE
Allow selecting specific folder to use as the local cache

### ISSUE THREAD

**Issue by khartahk** [nextcloud/android#453]
### Actual behaviour
If the picture is set to move to program folder it is now supposed to be moved to the Android/data... folder where the gallery app is not scanning for pictures as there are multiple thumbnails and other images of the apps ui there that should not be in the gallery. Now there are 2 problems. 
1st: the pictures from the Android/data... folder are not shown in the gallery app
2nd: related to the first one is that I now need to leave the picture where the nextcloud app found it so that it is shown in the gallery app and I now have two same pictures on the phone

### Expected behaviour
Before this update the pictures were stored in the nextcloud folder directly on the internal sdcard which worked nicely. The pictures would be moved from DCIM subfolder to the nextcloud folder so that there would be only one copy of it on the phone and they were also visible in teh gallery app.
 
### Steps to reproduce
1. Set the pictures to be moved to the program folder after autoupload
2. Take a picture and let it be uploaded
3. check the gallery app if you still see the picture
4. also related to my previous bug #452 the picture is not actualy moved to the Android/data... folder and is left in the DCIM subfolder

### Environment data
Android version:
6.0
Device model: 
HTC One m8
Stock or customized system:
Stock but rooted
Nextcloud app version:
1.4x currently latest release
Nextcloud server version:
10.0.2

**Comment by inducer** [comment]
This update breaks:

* Sharing my password database with keypassx
* Sharing my todo list with Simpletask Cloudless
* Sharing pictures with gallery apps
* Sharing my notes with Writeily

for me.

**Comment by Bart873** [comment]
I agree with khartahk, the expected function of the stock gallery app is to display media content from various sources that are available on the device. When the nextcloud data is saved in the Android/data folder, all pictures synced with nextcloud disappear from the gallery and the gallery is broken at this point.

It is worth to say that even if it is stored inside Android/data, all synced nextcloud data is still accessible by any other app that has the permission to read the external storage (READ_EXTERNAL_STORAGE). It is only ignored by the media scanner and therefore no content gets displayed in the gallery. So it is definitely *not* a security improvement to move the nextcloud data to Android/data.

**Comment by khartahk** [comment]
Does anybody know if this will be added? Is it that hard to add an option to allow manual selection of where the storage folder should be? This would help quite a bit. As right now the only way this works as expected is if I install the old version where the data folder was nextcloud and then upgrade to the new version and don't select the folder in the settings. I'm not an android developer but if somebody can point me to where this selection is happening I'll check if I can add this myself.

**Comment by kosli** [comment]
+1

**Comment by tobiasKaminsky** [comment]
We have changed the storage location on sdcard to /sdcard/media/... to allow gallery to scan the downloaded images again.
This will be in next version.
