### ISSUE TITLE
Cannot open files in encrypted folders using the android file open dialog

### ISSUE THREAD

**Issue by TimMagee** [nextcloud/android#4536]
### Actual behavior
When attempting to open a file in an E2E folder, the file open dialog gives me a "Can't load content at the moment" screen.

### Expected behavior
E2E folders behave just like all other folders and I can open files from the file open dialog.
 
### Steps to reproduce
1. Set up E2E on one or more folders.
2. Attempt to open a file from an E2E folder in another app
3. Notice the "Can't load content at the moment" screen whenever attempting to open an E2E folder.

### Environment data
Android version: 9

Device model: Samsung Galaxy s5 G900T

Stock or customized system: MicroG Lineage OS 16

Nextcloud app version: 3.8.0

Nextcloud server version: 16.4

**Comment by AndyScherzinger** [comment]
Pinging @tobiasKaminsky
