### ISSUE TITLE
Data loss when using auto upload with "move to app folder"

### ISSUE THREAD

**Issue by PhilLab** [nextcloud/android#4546]
### Actual behaviour
When using auto upload for your camera app folder with  "Original file will be... moved to app folder", you will **loose** your photos and only the newest ones are retained.

### Expected behaviour
No photo should be deleted. Or the user should explicitly warned that using this feature has its caveats.
 
### Steps to reproduce
1. In the NC app, open the Auto upload page
1. Select your camera's picture folder for auto upload
1. Use "Original file will be... moved to app folder"
1. Take some photos in your camera app
2. Make sure that NC can sync. Wait a little bit
2. Take some more photos in your camera app
2. Make sure that NC can sync.

Result: Your pictures are gone, only the latest ones are available.

Why? Because most camera app (e.g. my stock Xperia camera app) number their photos based on the existing files. If the files are directly removed from the folder after upload, the next picture will get the same filename (`DSC_0001.JPG`) and thus Nextcloud uploads the next picture at the same filename, effectively deleting the older photo

### Environment data
Android version: 9

Device model: Sony Xperia XZ2 Compact H8314

Stock or customized system: stock

Nextcloud app version: 3.8.0

Nextcloud server version: 16.0.4.1

**Comment by feutl** [comment]
I want to add that forum entry to that issue, because this is not what I expected when using that feature
https://help.nextcloud.com/t/move-file-to-app-folder-after-automatic-upload-works-but-files-get-deleted-locally-after-opening-the-nc-app/61080

**Comment by tobiasKaminsky** [comment]
> Because most camera app (e.g. my stock Xperia camera app) number their photos based on the existing files.

If I am not wrong it is rather a corner case on Android (while it is true on DSLR cameras), but most of the Android devices use IMG_YYYYMMDD_HHMMSS.jpg pattern.

To prevent this problem, you could use "copy" instead of "move" as then the image remains in source folder.

**Comment by PhilLab** [comment]
@tobiasKaminsky Thanks for taking a look at this issue. My current Sony Xperia - and if I remember correctly, both its predecessors - uses this pattern so I am not sure if one could call it a corner case.

Yes, there is a workaround available, but nevertheless, a "loose all your pictures" setting in the sync app is a very inconvenient one. I was just lucky that I quickly recognized the damage.

**Comment by PhilLab** [comment]
Still relevant for all Sony smartphones and probably others as well

**Comment by PhilLab** [comment]
Still relevant

**Comment by PhilLab** [comment]
Still relevant

**Comment by PhilLab** [comment]
Still relevant

**Comment by PhilLab** [comment]
Hm, an anti stale bot would be nice

**Comment by AndyScherzinger** [comment]
cc also @tobiasKaminsky. I support the corner case scenario, especially looking at the fact that afaik Sony terminated development of new xperia phones.

**Comment by bjuraga** [comment]
The corner case would be valid if the files are the same. By same i mean "same byte for byte". A different payload with the same name should not be considered "the same file" by NC and i agree with the OP that this is not a corner case but a bug / over optimization on the file change detection mechanism. 

I can easily come up with many more scenarios, like my printer generates auto numbered scan files, and its produced in the last year or two. 

The use case on phones is to "auto upload and delete" so we have more room for next pictures, but the use case is valid for many more devices. 

I consider this a core bug and a critical one because it causes data loss. I hope you can see this from a user perspective.

**Comment by tobiasKaminsky** [comment]
With upcoming new 3.11 version there should be then shown a conflict error.
Can you test this?

**Comment by bjuraga** [comment]
I tested the scanner scenario with a document.
Steps:
- create a folder on Nextcloud / Android 
- create a folder on Nextcloud / Server
- on Android in the Nextcloud setup a custom folder auto upload fro the above folders
  - set auto upload existing files and move file to app folder
- on Android create a file called Doc001.docx in the folder created for this test
- observe the file is uploaded to the Server
- make a change to the file and save it
- observe the upload failing and requiring manual conflict resolution.

Test successful

Thanks! This experience works now just as expected, plus the UI/UX is flawless.
