### ISSUE TITLE
Android Mobile app crash in photos section

### ISSUE THREAD

**Issue by woprusn** [nextcloud/android#4549]
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'long com.owncloud.android.datamodel.OCFile.getLastSyncDateForData()' on a null object reference
	at com.owncloud.android.ui.helpers.FileOperationsHelper.lambda$startSyncForFileAndIntent$0$FileOperationsHelper(FileOperationsHelper.java:209)
	at com.owncloud.android.ui.helpers.-$$Lambda$FileOperationsHelper$Q56PsCgyFZxef_IG4gCdZEuyyO8.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:764)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: beyondxq
Model: SM-G977U
Id: PPR1.180610.011
Product: beyondxqvzw

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: G977UVRU2ASH7

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky any idea when this might be happening? Could such a NPE just be caught and skipped?

**Comment by ezaquarii** [comment]
@tobiasKaminsky @AndyScherzinger 

It looks like we're trying to get sync timestamp for parent. What if the file genuinely does not have a parent?
```
            // check if latest sync is >30s ago
            OCFile parent = storageManager.getFileById(file.getParentId());
            if (parent.getLastSyncDateForData() + 30 * 1000 > System.currentTimeMillis()) {
                EventBus.getDefault().post(new SyncEventFinished(intent));
                return;
            }
```
I'm not familiar with `OCFile` model design - is it possible that files in root have null parent?

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky probably knows best. I have no idea why and when it could be happening.

**Comment by tobiasKaminsky** [comment]
`
Attempt to invoke virtual method 'long com.owncloud.android.datamodel.OCFile.getLastSyncDateForData()' on a null object reference
`
The problem is not that we do not have a sync timestamp, but that we try to access a OCFile that is null.

**Comment by tobiasKaminsky** [comment]
Ah, damn.
The problem is that when fetching photos, we maybe do not have a parent, as it not yet synced.
