### ISSUE TITLE
Better emptycontent view for file types which can not be shown

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/android#455]
Currently we still have the dark background and the strange alarm icon.

Would be better to have the nice light emptycontent view like in https://github.com/nextcloud/android/pull/449, with an icon-file icon (the grey page, maybe with lines. Or something similar.

**Comment by AndyScherzinger** [comment]
Hi @jancborchardt do you have an example for me? I tried with a file I can't open and I just see a blank, black screen, no alarm icon? 0_o

**Comment by mario** [comment]
@jancborchardt if you have a screenshot of this and a way to reproduce I'd appreciate it! :)

**Comment by tobiasKaminsky** [comment]
Steps to reproduce:
- create a 0byte text file and name it "corrupt.jpg"
- download the file and view it

![screenshot_20170119-174254](https://cloud.githubusercontent.com/assets/5836855/22115844/d752f4e2-de6e-11e6-993a-ea3db935e7d0.png)
