### ISSUE TITLE
Better integration of DAVx⁵

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/android#4551]
Is there a possibility to use SSO or another easy possibility?
I think it should be delivered with the nextcloud App installation.
Are there any plans for the future?

**Comment by AndyScherzinger** [comment]
This question is better asked in the Davx5 tracker.
There is an SSO library which can be used by apps and works with the installed Nextcloud app but this integration then needs to be done by the using clients. 

The Nextcloud Deck app uses this for example as well as the news app.

**Comment by rfc2822** [comment]
See also: https://github.com/nextcloud/android/issues/4708
