### ISSUE TITLE
PNG files have full-screen checkerboard background

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/android#456]
That makes them look very very strange. Instead, the background should be dark as with JPG. The checkerboard background should only be as large as the size of the image, directly behind it, as fallback if there’s transparency in the image.

**Comment by przybylski** [comment]
But isn't this widely accepted way of presenting png with transparency ? What if I have image with only black shapes on transparent background ?

**Comment by tobiasKaminsky** [comment]
@jancborchardt means the background if the image is not full sized like here: https://github.com/nextcloud/android/pull/560#issuecomment-273851857
