### ISSUE TITLE
Auto upload stopped working - uploads queue has stopped being populated

### ISSUE THREAD

**Issue by Rychu-Pawel** [nextcloud/android#4560]
### Actual behaviour
For 10 days I have been having an issue that when taking a new photo it doesn't appear in the `Uploads` queue and is never uploaded to the server. 

Hints:
- Affected is only my phone. Nextcloud client app on my wife's phone works correctly.
- I'm able to upload anything I want manually (it appears in the `Uploads` as successfull)
- Newly taken photos **do** appear in the `Auto upload` folders preview
- App correctly sends contacts copy to the server every day (it appears in the `Uploads` as successfull)

### Expected behaviour
After taking a picture it is shown correctly in the `Uploads` queue and is sent to the server.
 
### Steps to reproduce
I don't know what exactly I did to get into this issue but here are some steps in chronological order that I guess are connected with the issue:
1. Switch all folders to `Only upload on unmetered Wi-Fi` (this is where everything had been still working for few days)
2. Download a lot of big movies (few GB each) from GoPro to one of the folders that are synced with the server (my server's php upload limit was set to 600MB)
3. Run out of free space on your phone
4. I think this is where it broke

Please note that auto upload is broken not only for GoPro-Exports folder but for all folders.

### What I have tried so far
- Freeing a lot of space on my mobile by removing the GoPro movies from synced folder (sent and not yet sent ones)
- Changing max upload size on the server in php config to 10GB
- Changing the folders back to also mobile data sync
- Right now I'm connected to WiFi in the same network the server is which is set as unmetered in my phone
- Cleared app cache

### Environment data
Android version: **9**
Device model: **OnePlus 6T**
Stock or customized system: **Stock**
Nextcloud app version: **3.8.0**
Nextcloud server version: **16.0.4.1**

App has permissions to access Camera, Contacts, Storage and show notifications. 
It is allowed to use mobile data in the background. 
Battery optimization is off for this app.

#### Web server error log
There are no related web server logs

#### Nextcloud log (data/nextcloud.log)
For 14 days (since last nexcloud server update and after which everything was working fine) there hasn't been in the logs anything else than just 
```
Sabre\DAV\Exception\BadRequest: expected filesize XYZ got ZYX
```

**Comment by Rychu-Pawel** [comment]
As always I fixed the issue after writing the post... But the reason is unknown. What fixed the auto-upload for me was going to the GoPro app and removing all movies and pictures from there. Then suddenly all other folders started being sync with the server. This is strange as I'm pretty sure the GoPro app keeps all the movies and pictures somewhere else then the GoPro-Exports folder. It copies files to this folder after selecting them and tapping on "Save to phone".

Still, in my opinion, there should be an error message informing a user what stops the app from syncing all the folders.

**Comment by Serphentas** [comment]
I can confirm I have the same issue, where any auto-upload folder will neither upload nor fail in the Uploads view. I have tried to remove and replace folders, as suggested above, but it doesn't work for me.

This is a really inconvenient issue...

**Comment by tobiasKaminsky** [comment]
This is indeed a strange behavior and a strange "solution".
I currently have no clue what could trigger this.

**Comment by ezaquarii** [comment]
> This is indeed a strange behavior and a strange "solution".

This potentially could be caused by a silent crash suppressed by a `try {} catch() {}` somewhere deep in sync logic.

We recently added support for logs - maybe we could find somewhere there? Are logs enabled in prod build?

**Comment by Serphentas** [comment]
I have noticed that the file's last modified time (or accessed, not really sure) has to be after the time the sync is initially set up, meaning existing files don't move unless they are `touch`'d.

**Comment by Rychu-Pawel** [comment]
Yes, I know about that but this wasn't the issue in my case. Sync folder was created long before and even new files had not been syncing. It behaved like it was stuck on a file that is bigger than my php upload limit without any error message. Once I removed it sync continued for all folders.

**Comment by HugzFluentMiny** [comment]
I'm also having this issue.
When browsing the bugs it looks like this has happened in the past.

Existing files don't upload.
When i take a picture, the new picture is uploaded. The others don't even get added to the upload queue.

On my end there is nothing to remove. The queue is simply not populated.

**Comment by Rychu-Pawel** [comment]
@HugzFluentMiny note that after setting up the client for the first time only new photos get updated and I assume this is intended behavior. Maybe devs can correct me if I'm wrong.

What this bug report is about that the auto upload had been working, then it stopped. I think this is a different case that you are describing.

**Comment by Serphentas** [comment]
@Rychu-Pawel Have you tried removing and then readding your account ? Maybe even the whole app, too.

I've since done that and files (old & new alike) are synced on time.

**Comment by Rychu-Pawel** [comment]
@Serphentas 
No chance to check if this solves the issue because, as I mentioned above, I fixed it by removing all big files "invisibly blocking" the queue.

**Comment by beeender** [comment]
I have the similar issue. The auto-uploading stopped work after a server issue (the max upload size was changed to a wrong value). Since that, auto-uploading didn't happen.

But **rebooting the phone** solves the issue.

**Comment by Rychu-Pawel** [comment]
So here I am again with a very similar issue :) But this time I wasn't fixing anything so we can play with this issue. 

### Steps to reproduce

I did *almost* the same thing as a year ago but this time I'm not sure that GoPro movies are the issue here (see point 4). Also, new files are synced correctly.

1. Switched all my directories to `Only upload on unmetered Wi-Fi`. I have 4 directories. Two camera ones (photos and movies) and two GoPro ones (photos and movies)
2. Made some photos with my smartphone (auto-upload worked correctly on wifi at this moment)
3. Recorded two movies with GoPro, synced them with the phone but didn't click `save to phone` button in GoPro app (this is a bit confusing behavior btw and maybe that's the issue? these movies were sent somewhere to the phone but are not available in the GoPro folder yet)
4. Made a few more photos with my smartphone's camera (photos auto-upload still worked correctly on wifi at this moment)
5. Got into the plane. Turned airplane mode on and took few pictures on board. Turned `Only upload on unmetered Wi-Fi` off.
6. Got home. The photos taken in the plane have never made it to the cloud.
7. New photos sync successfully.

I can see the airplane photos in the `Auto upload` tab but I do not see them in the folder in `All files` tab. My `Uploads` queue is empty.

### What I can do

Right now I can:

1. Click `save to phone` button for the movies in the GoPro app to see if that will fix the issue
2. Remove the movies from the phone

But I don't want to do it as I don't really need that airplane photos and maybe we can try to figure out what happened?

**Comment by vazir** [comment]
Still does not upload ANYTHING
