### ISSUE TITLE
Add home screen widgets: Recommend files, activities by others

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/android#4571]
### Describe the solution you'd like
It would be nice to have a widget on the home screen, that listes the same objects as in Files App with the Recommend App enabled

### Additional context
![grafik](https://user-images.githubusercontent.com/24530680/65752441-1aaed280-e10d-11e9-9413-310e945eb01b.png)

In this Issue is a widget described also, but it's taking about quick access to specific folders or files
https://github.com/nextcloud/android/issues/3175

### Describe alternatives you've considered
Open the mobile browser and navigate to the files app there

**Comment by jakobroehrl** [comment]
Another helpful widget could be a Activity feed (all activities by others)

**Comment by joshtrichards** [comment]
Fixed in #10719
