### ISSUE TITLE
Can't open list of shared items

### ISSUE THREAD

**Issue by alexbijma** [nextcloud/android#4572]
### Actual behaviour
The menu item for "shared" items ("gedeeld" in Dutch) doesn't seem to work.
When you click it, it keeps loading or you get the attached screen. https://secure.familiebijma.nl/s/fQgcKySZxft95J7

### Expected behaviour
View a list of shared items, so you have complete overview of items shared

### Steps to reproduce
1. Open android app
2. Goto main menu
3. Click "Shared"(gedeeld)

### Environment data
Android version: 8.0

Device model: Samsung s7

Stock or customized system:

Nextcloud app version: 3.8.0

Nextcloud server version: 16

**Comment by szaimen** [comment]
Unfortunately not stale!

**Comment by alexbijma** [comment]
i can still reproduce this issue on several devices and several servers. Seems that the "Shared" item in the menu is not working at all on Android app.

**Comment by AndyScherzinger** [comment]
@szaimen @alexbijma how many files do you have that are shared?

**Comment by szaimen** [comment]
>  how many files do you have that are shared?

@AndyScherzinger 
In the moment, I have shared 1 folder and 1 file via link and 2 pdf files are shared with me from other local users.

**Comment by alexbijma** [comment]
i have around 15 folders and 5 files shared with other people. On web this same overview of shared items is working, only in the app it isn't working.

**Comment by alexbijma** [comment]
hi @AndyScherzinger can you put this issue in some next state? it still does happen and tested it on multiple devices and with different servers.

Also tested on iOs and there it does work.

In english it's called the "Shares" menu item

**Comment by szaimen** [comment]
BTW: @AndyScherzinger does it work for you?

**Comment by AndyScherzinger** [comment]
Just tested it (again) and I am experiencing the same behavior.

Cc @tobiasKaminsky shared view stays empty.

**Comment by bazio101** [comment]
Just upgraded to 3.11.0 (f-droid).
Seems to work fine. Now I can see the files I have shared with other people.

**Comment by alexbijma** [comment]
android 10, nextcloud 3.11, server version 17.0.2 still the same problem.
ah... server with version 18 doesn't have the problem anymore. so seems to be fixed with server version 18.

Anyone else who can confirm that?

**Comment by szaimen** [comment]
It works for me, too. So I close this issue.
