### ISSUE TITLE
[Feature Request] Support remote search if Nextant is available

### ISSUE THREAD

**Issue by affanse** [nextcloud/android#458]
Hi devs, it is absolutely awesome if the search function can transparently utilize available indexing service proxy like nextant (using solr) so user can do a full text search for documents.

**Comment by mario** [comment]
We already support remote search. Not sure if Nextant has a separate API? @daita

**Comment by daita** [comment]
This needs to be done and there is already an API, however, I would advice waiting for [nextant v2: fullnextsearch](https://github.com/nextcloud/nextant/tree/fullnextsearch) 

In the meanwhile we could start to discuss how to detect that the app is installed, if you need anything from my side

**Comment by mario** [comment]
@daita well, that part is simple I guess? Just expose it via capabilities?

**Comment by tobiasKaminsky** [comment]
I am already working on it, together with @daita  :-)

**Comment by tobiasKaminsky** [comment]
Replaced by unified search.
