### ISSUE TITLE
Cannot Upload via WiFi (LTE/3G work)

### ISSUE THREAD

**Issue by mcrosson** [nextcloud/android#4580]
### Actual behaviour
The NextCloud app throws sync errors when connected to WiFi. I cannot get a single file to upload when on WiFi. However, when I disconnect WiFi and switch to LTE/3G the uploads work as expected.

### Expected behaviour
Files should be able to be sync'd over WiFi or LTE or 3G. Not just the cell connections.
 
### Steps to reproduce
1. Connect to WiFi
2. Edit a file locally
3. Look for a sync failure
4. Turn off wifi
5. Connect to cell nework
6. Retry sync

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by cervorange** [comment]
Hello, i have exactly the same problem:
Android oneplus 5 Rom Stock
OxygenOS 9.0.8
NextcloudPi v1.17
Nextcloud app 3.8.0

It s arrived last days, some time it works. The problem is that nextcloud try all the time to resend photos and that cost lost of battery

**Comment by ism-hub** [comment]
I've have something similar - I can't connect with my public address to the server when I'm inside the server's LAN. (Not nextcloud bug.. My router refuses to port forward in that situation [see here](https://stackoverflow.com/questions/58122484/port-forwarding-for-port-80-doesnt-work-for-requests-from-inside-the-lan-works) ). I "solved" (there are some problems with it) it by connecting with my server's LAN address.

**Comment by mcrosson** [comment]
> 
> 
> I've have something similar - I can't connect with my public address to the server when I'm inside the server's LAN. (Not nextcloud bug.. My router refuses to port forward in that situation [see here](https://stackoverflow.com/questions/58122484/port-forwarding-for-port-80-doesnt-work-for-requests-from-inside-the-lan-works) ). I "solved" (there are some problems with it) it by connecting with my server's LAN address.

In my case I'm not connecting to a local server. The one I'm working with is 100% offsite at all times.

**Comment by cervorange** [comment]
> 
> 
> > I've have something similar - I can't connect with my public address to the server when I'm inside the server's LAN. (Not nextcloud bug.. My router refuses to port forward in that situation [see here](https://stackoverflow.com/questions/58122484/port-forwarding-for-port-80-doesnt-work-for-requests-from-inside-the-lan-works) ). I "solved" (there are some problems with it) it by connecting with my server's LAN address.
> 
> In my case I'm not connecting to a local server. The one I'm working with is 100% offsite at all times.
Like me

**Comment by disaderp** [comment]
If you are using Cloudflare, this is related to #4510

**Comment by AndyScherzinger** [comment]
What kind of errors do you see I. The uploads view for the failing photos?

**Comment by mcrosson** [comment]
I am using CloudFlare. Will close and track #4510  . Will open fresh with crash info/logs if 4510 doesn't address my problem

**Comment by cervorange** [comment]
Hello, it's work good now...

Probably with the update to 1.17.1... 
I don't see another change

Thanks for your time
