### ISSUE TITLE
Crash on conflict

### ISSUE THREAD

**Issue by mcrosson** [nextcloud/android#4581]
### Actual behaviour
When a file is found to be conflicted there is a null pointer exception once the dialog stating the file is conflicted opens.

### Expected behaviour
It shouldn't crash
 
### Steps to reproduce
1. Edit a file locally that fails sync
2. Edit the same file on a different computer/device that does successfully sync
3. Re-try opening the file on the device that failed sync
4. Crashes

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
Can you please attach the stack trace for the null pointer? Highly appreciate your help in digging into this matter ❤️

**Comment by AndyScherzinger** [comment]
> Would it be more appropriate to close this as "not enough info" and I can re-open if it happens again with the full stack trace?

Not necessary, if no new comment is added within 4 weeks than the stale bot will label it stale, if for another 2 weeks there's no update then the bot will auto close it 🤖
