### ISSUE TITLE
Separate Theme Colors

### ISSUE THREAD

**Issue by raddacle** [nextcloud/android#4583]
Having the theme color be used for the action bar and folders is rather overwhelming. I've explored through android studio, though I can't find what string to change to override the folder color. What string would override the color for just folders/files?

**Comment by tobiasKaminsky** [comment]
Folder icon is determinated by https://github.com/nextcloud/android/blob/fba301b248eb844f463aec535258e092f170e67f/src/main/java/com/owncloud/android/utils/MimeTypeUtil.java#L160

and the color is set here:
https://github.com/nextcloud/android/blob/fba301b248eb844f463aec535258e092f170e67f/src/main/java/com/owncloud/android/utils/MimeTypeUtil.java#L179

**Comment by raddacle** [comment]
> Folder icon is determinated by
> 
> https://github.com/nextcloud/android/blob/fba301b248eb844f463aec535258e092f170e67f/src/main/java/com/owncloud/android/utils/MimeTypeUtil.java#L160
> 
> and the color is set here:
> https://github.com/nextcloud/android/blob/fba301b248eb844f463aec535258e092f170e67f/src/main/java/com/owncloud/android/utils/MimeTypeUtil.java#L179

I really appreciate the direction. How would line 179 need to be changed to insert a hex code as a the value?

**Comment by tobiasKaminsky** [comment]
Line 179 expects an int, so you need a function to translate hex to int.

**Comment by raddacle** [comment]
Great, thank you! Figured it out.

For reference for anyone else:

1. Add `<color name="mycolor">#ffdd55</color>` to the colors.xml, with whatever hex color you want.
2. Change line 179 to `return ThemeUtils.tintDrawable(drawableId, context.getResources().getColor(R.color.mycolor));`

**Comment by raddacle** [comment]
Only issue I'm noticing is that zip ("package") files are not affected. Is that set somewhere else?

**Comment by raddacle** [comment]
And... Found it! 

Changed line 112 to `ThemeUtils.tintDrawable(icon, context.getResources().getColor(R.color.mycolor));`
