### ISSUE TITLE
Unusable files after upload retry

### ISSUE THREAD

**Issue by oparoz** [nextcloud/android#459]
### Actual behaviour

Files are named with ids of some sort

### Expected behaviour

Files should keep their original names
 
### Steps to reproduce

1. Upload files
2. Disable data connection on mobile
3. Got to the list of failed Nextcloud transfers
1. Tap on retry
1. Wait until transfers are completed

### Environment data
Android version: 6

Device model: S7 edge

Stock or customized system: stock

Nextcloud app version: 1.4

Nextcloud server version: 11

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

**Comment by tobiasKaminsky** [comment]
@oparoz do you still experience this bug?

**Comment by tobiasKaminsky** [comment]
@oparoz I tried this again and had no problems.

**Comment by oparoz** [comment]
OK, let's close this then :) Thanks.
