### ISSUE TITLE
File Upload fail - Not acceptable

### ISSUE THREAD

**Issue by CSchaefer70** [nextcloud/android#4590]
### Actual behaviour
When requesting a file upload (from Android Device) to an existing functional NextCloud the transfer stops with "Not Acceptable"; regardless of WiFi or Cellular connection.  Smaller files (less then 8mb) work flawlessly.

### Expected behaviour
I would expect the upload to complete the same as the NextCloud Windows Client or drop and drop (copy) within a Browser like Chrome of Firefox.  File limits are set to 500mb and any larger files completes flawlessly when using Windows Client or Browser.  I suspect the "Chunk Size" is too small but do not know how to change in the Android Client. 
 
### Steps to reproduce
1. Select file larger the 10mb on Android phone (I tried a video or photo)
2. Select "Share" to NextCloud
3. Select "Upload" to folder

### Environment data
Android version: 9

Device model: Samsung Note 8 SM-N950U

Stock or customized system: Kernel 4.4.153; UI 1.0; knox 3.2.1 API 27 TIMA 3.3.0

Nextcloud app version: 3.8.0

Nextcloud server version: 16.0.4

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
@rullzer do you  have an idea what "not acceptable" could cause?
A quick search does not show any occurrence in Android code.

**Comment by CSchaefer70** [comment]
So the best I understand is that "Not Acceptable" is the general error routine for not meeting the criterion of successfuly transfer.  I had the same problem with the Windows NC App Client. After a little investigation I discovered the "...roaming/nextcloud/nextcloud.cfg" file and found by changing the "ChunkSize" parameter transfers completed correctly.  The WindowsApp github stable version download was too small for larger files (perhaps because of a shared server environment??? Not really sure about that).  Anyway, I changed the ChuckSize and the problem is  resolved:

 _**[General]
confirmExternalStorage=false
newBigFolderSizeLimit=250
optionalDesktopNotifications=true
useNewBigFolderSizeLimit=false
crashReporter=false
monoIcons=false
chunkSize=167772160
optionalServerNotifications=true**_

I wonder if that is the same issue with the Android App??

**Comment by ezaquarii** [comment]
> @rullzer do you have an idea what "not acceptable" could cause?
> A quick search does not show any occurrence in Android code.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/406

> The HyperText Transfer Protocol (HTTP) 406 Not Acceptable client
> error response code indicates that the server cannot produce a response
> matching the list of acceptable values defined in the request's proactive
> content negotiation headers, and that the server is unwilling to supply a
> default representation.

**Comment by CSchaefer70** [comment]
Yes.  I agree. Where do we compare the list of acceptable parameters? I know mine from the server end... **what** and more importantly **where** does the NextCloud Android App keep it's protocol parameters??  

Please understand I'm loving NextCloud in so many ways... just I do not have the knowledge of how to fix this little yet critical feature to upload a file bigger then 8mb.  A task I consider essential, intrinsic to any cloud/VPN.

As mentioned, the Android App "FolderSync" executes flawlessly to and from my NextCloud Server (on shared host) with files beyond 200mb.  So the best I can tell is that the problem must be with the NextCloud Android App: https://play.google.com/store/apps/details?id=com.nextcloud.client&hl=en_US

**Comment by alexandrejsgomes** [comment]
I have the same problem. What we can do?

I love the nextclound, but i have this little problem.

**Comment by CSchaefer70** [comment]
Alexandrejsgomes... foldersync app for older versions of NextCloud or OwnCloud.  Otherwise, upgrade to the lastest NextCloudHub 21.0.1  AND get off shared server environment.  Everything works better on VPS.  You'll need to learn Ubuntu or CentOS.  However, command line gets the current version of everything.  Just Google each command with the verion of Linux and there are lots of "Step x Step" [copy paste].  I found that with MySQL8+ and proper php version everything flows!
