### ISSUE TITLE
Missing pictures

### ISSUE THREAD

**Issue by tom64100** [nextcloud/android#4601]
Excellent application, However I notice a concern, some photos do not appear in the mobile application while they are present via the Web browser. These are photos that are sent automatically via the mobile application.

**Comment by ne20002** [comment]
#4477

**Comment by ne20002** [comment]
I can confirm this for 3.8.0. For me it's only photos uploaded with iOS-App affected.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky @nextcloud/server-triage any idea why this could happen and how?

**Comment by tobiasKaminsky** [comment]
> Those are the same issue:
> #4502

This indeed seems to be the same.


> #4477

This is about uploading files, so it is something different.

**Comment by tobiasKaminsky** [comment]
Can you create us a test account, test if the problem occurs also there and if so send the credentials to tobias at nextcloud dot com with a reference to this issue?

**Comment by AndyScherzinger** [comment]
@tom64100 @ne20002 is this issue still present for you with v3.8.1 of the app?

**Comment by thomas64600** [comment]
@andyscherzinger 
Hello, update 3.8.1 corrected the problem, the photos appear well. thank you very much.

**Comment by AndyScherzinger** [comment]
Thanks for the feedback @thomas64600, highly appreciated and happy to hear the matter has been resolved in your case 🎉
