### ISSUE TITLE
Error with addition subfolders in 3.8.1 RC1

### ISSUE THREAD

**Issue by Siggi0904** [nextcloud/android#4608]
Hi together, I have a problem with the newly subfolder feature for pictures in the RC1 android app. In my case I'll backup the whole whatsapp folder with a defined folder structure. 
These newly feature creates sub sub folder with same names and store all files in these wrongly folders. In addition not only images are uploaded in sub sub folder, all files are here included.

Please remove tthese feature or fix it if there is no sub folder in remote.

**Comment by tobiasKaminsky** [comment]
Can you post an example directory structure where it does make problem?
I do not fully get the problem and what you expect.

**Comment by Siggi0904** [comment]
For shure, see attachment.
![nc_folders_fault](https://user-images.githubusercontent.com/4992106/66325523-b0c1d480-e927-11e9-8f89-68f38b2da760.jpg)

**Comment by tobiasKaminsky** [comment]
Do you have multiple whats app auto upload folder defined?

**Comment by Siggi0904** [comment]
No, root of whatsapp folder is selected, no subfolder too.
With version before 3.8.1 rc1, all works fine.

**Comment by tobiasKaminsky** [comment]
@Siggi0904 

https://github.com/nextcloud/android/pull/4648#issuecomment-540497808
Can you test this apk, which you can install in parallel to your existing Nextcloud app.

**Comment by Siggi0904** [comment]
When will be the next RC released?
I'd like to wait to it and test it then.
Ticket is cloased, means anyone has tested it before.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky has implemented and tested it
Next RC is likely published today

**Comment by Siggi0904** [comment]
Is this then RC3?
I got RC2 two day ago. Then I can test it too.
Great thanks.

**Comment by AndyScherzinger** [comment]
It'll be RC3, while @tobiasKaminsky is already offline so publishing might rather happen tomorrow.
