### ISSUE TITLE
Upload from Camera doesn't work for more than one picture

### ISSUE THREAD

**Issue by yennor** [nextcloud/android#4609]
### Actual behaviour
When uploading several files directly from the camera to a folder without waiting for the previous pictures to finish uploading. It won't upload any pictures besides the first ones. The other ones will fail with "Local File not foud"

### Expected behaviour
- You should be able to take as many pictures as you want without waiting after each pictures until it finished uploading it
 
### Steps to reproduce
- Open the nextcloud app
- Choose a folder on the server
- Press the plus button and choose "upload from camera"
- Take a picture and accept it.
- Now nextcloud starts uploading that picture.
- Don't wait before it finished uploading, choose "upload from camera" again and upload an other picture.
- It will fail uploading the second file. In the upload log it shows "local file not found"

### Environment data
Android version: 9

Device model: Xiaomi Mi A2 Lite

Stock or customized system: Stock

Nextcloud app version: 3.8.0

Nextcloud server version: 16.0.5

**Comment by yennor** [comment]
well I don't know with what to update it.. .still the same problem

**Comment by FiC5020** [comment]
Thanks for the immediate answer. Now I unterstand the problem and can it explain to projectmanagers.
Is there a plan to apply this change to the client like AndyScherzinger mentioned it in Issue #7380 ?

thanks very much.

**Comment by AndyScherzinger** [comment]
@FiC5020 I wrote a fix, please see  and if possible test that one (can be installed in parallel) and report back if the matter is resolved for you (testing showed it works for me) so we can push this for the next release(s).
https://github.com/nextcloud/android/pull/7411#issuecomment-731435608
