### ISSUE TITLE
Changing the account/domain does not work

### ISSUE THREAD

**Issue by seltsamt** [nextcloud/android#4610]
### Actual behaviour
- I changed the domain of my nc install. As In wanted to change the same in the apps account settings. After the basic input I wanted to see the details for the second account but at first the app did not load for a long time and than it crashed.

### Expected behaviour
- App accepts the new domain and lets me proceed.
 
### Steps to reproduce
1. Open account setting.
2. Add new account.
3. App freezes or quits.

### Environment data
Android version: 8.1

Device model: Moto G5

Stock or customized system: Stock

Nextcloud app version: 3.8.9

Nextcloud server version: 16.0.5

#### Web server error log
Could not find that one :-)

#### Nextcloud log (data/nextcloud.log)
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
	at com.owncloud.android.ui.activity.UserInfoActivity.populateUserInfoUi(UserInfoActivity.java:259)
	at com.owncloud.android.ui.activity.UserInfoActivity.lambda$null$0$UserInfoActivity(UserInfoActivity.java:377)
	at com.owncloud.android.ui.activity.-$$Lambda$UserInfoActivity$gWBfB6Gsuel8SADkZiTj2AR_AJs.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6626)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080090
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: motorola
Device: sanders_n
Model: Moto G (5S) Plus
Id: OPSS28.65-36-11-4
Product: sanders_n

************ FIRMWARE ************
SDK: 27
Release: 8.1.0
Incremental: b6557

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by ezaquarii** [comment]
AFAIK changing account domain is not supported due to security concerns and there are no plans to support it in the future.

If you changed the domain, pls remove the old account and log in again.

@AndyScherzinger @tobiasKaminsky close?

**Comment by ezaquarii** [comment]
This crash should not happen, tho.

**Comment by seltsamt** [comment]
That's what I actually did. I made a new account and wanted to delete the
old one. On checking whether it worked, I experienced the crash.

It worked for me after I restarted my phone.

Best,
Thomas



Chris Narkiewicz <notifications@github.com> schrieb am So., 6. Okt. 2019,
11:39:

**Comment by tobiasKaminsky** [comment]
> java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
> at com.owncloud.android.ui.activity.UserInfoActivity.populateUserInfoUi(UserInfoActivity.java:259)
> at

This means that the account object we need is null, but I fail to find a reason why this is so.
Even if the account is not accessible anylonger, it still should be possible to see the accounts info.

**Comment by nursoda** [comment]
Maybe related here: I noticed that the app doesn't react (and offers to be killed) when I delete an account. This only happens if I have MANY accounts (like ~10) set up. The more account, the longer it takes (partly more than a minute on a OnePlus 6T). It finally works fine if one waits long enough, but it should not take that long. Should I open a bug for that? If so: What info to include there?

**Comment by tobiasKaminsky** [comment]
@nursoda yes please as it is a separate issue, I guess.
