### ISSUE TITLE
Folder name in grid view (as it was before)

### ISSUE THREAD

**Issue by kjlhgfds** [nextcloud/android#4611]
### Is your feature request related to a problem? Please describe.
When browsing in grid veiw, folders have no name, wich is a bit difficult to know what is what.

### Describe the solution you'd like
Just to have the name of folders under them, like it was before.

### Additional context
<a href='https://postimg.cc/4KqjsjRb' target='_blank'><img src='https://i.postimg.cc/4KqjsjRb/Screenshot-20191006-122059-Nextcloud.jpg' border='0' alt='Screenshot-20191006-122059-Nextcloud'/></a>

**Comment by tobiasKaminsky** [comment]
This is quite the same behaviour since June 2017: if you have more than 4 columns in grid view the file names are not shown.
We did this as if you have e.g. 5 or 6 columns then each column is so small that you do not see any meaningful names anylonger.

**Comment by kjlhgfds** [comment]
I understand, but then how can I change how many columns I see ? Because even if I have only 1 folder, I have 5 column (4 empty), so I don't see his name.

**Comment by AndyScherzinger** [comment]
You can pinch to zoom on grid view :)
