### ISSUE TITLE
Upload complains on missing storage space

### ISSUE THREAD

**Issue by avanc** [nextcloud/android#4612]
### Actual behaviour
- Storage is almost full
- Use Nextcloud App to upload large video (Upload and delete in source folder)
- Nextcloud App complains that not enough space is available to _copy_ file and proposes to move file instead
- File is uploaded and moved internally to Nextcloud folder

### Expected behaviour
- Storage is almost full
- Use Nextcloud App to upload large video (Upload and delete in source folder)
- File is uploaded ad space is freed on device
 
### Steps to reproduce
See above

### Environment data
Android version: 
8.1.0

Device model: 
Motorola Moto G5

Stock or customized system:
Stock Android

Nextcloud app version:
3.8.0

Nextcloud server version:
17.0.0

#### Web server error log
No logs

#### Nextcloud log (data/nextcloud.log)
No logs

**Comment by tobiasKaminsky** [comment]
Sorry, I fail to find the problem?
If the file in question is on an external sdcard the app first copies it and then uploads it, so that a card removal does not make a problem.

**Comment by avanc** [comment]
The scenario regarding external storage sounds valid. But why not moving instead of copying it to avoid the problem of duplicate storage?
'Move to app folder' works as expected as no additional storage is needed intermediately.

My problem is, that for a short time double amount of storage is needed.

**Comment by tobiasKaminsky** [comment]
For "move to app folder" this would be partly valid to directly move the file, but imagine this
- file on scard
- move file to internal storage
- upload fails
- move file back
- maybe not possible due to sdcard removed
--> data loss

So it is better to be safe and move the file only after a sucessful upload.

**Comment by avanc** [comment]
I didn't thought about this case.

Thanks for the detailed clarification.
