### ISSUE TITLE
App seems only to be a webwapper with 17.0.0

### ISSUE THREAD

**Issue by Narandum** [nextcloud/android#4613]
### Actual behaviour
I run my nextcloud version 17.0.0 in a docker-compose setup behind a apache reverse proxy and everything is working. 
When I try to connect to the server with my Android Phone and the app client v. 3.8.0 the app shows me just the webgui and not the app gui.
 
### Steps to reproduce
1. install docker version of 17.0.0 nextcloud
2. apache reverse proxy to the ports of the nextcloud
3. install TOTP Authentication App in nextcloud
4. Log in to nextcloud with 3.8.0 android app

### Environment data
Android version:
9.1.0
Device model: 
Huawei Mate 20 Pro
Stock or customized system:
Stock
Nextcloud app version:
3.8.0
Nextcloud server version:
17.0.0

**Comment by Narandum** [comment]
When I log into my Nextcloud with an generated App-Token it worked fine.
So do I have to generate tokens for everyone I want to use the nextcloud with?

**Comment by AndyScherzinger** [comment]
Your users can simply login with their user credentials via the web login flow. The server generates a token in the background which is then used by the client. So no need to generate any tokens manually upfront.

**Comment by Narandum** [comment]
This didn't work for me.
I had to generate the code manually in a browser and login to the app via the qr code.

**Comment by tobiasKaminsky** [comment]
Then there is a problem with your setup. 
You can even use TOTP during login, as Andy said.

**Comment by Narandum** [comment]
Okay, than i will look into it and close this issue.
