### ISSUE TITLE
AutoUpload don't work

### ISSUE THREAD

**Issue by derjohannes19** [nextcloud/android#462]
### Actual behaviour
In the app -> Auto Upload I can see all my folders (Camera, Screenshots, WhatsApp Images) and I turned on sync for all this folders. But nothing happens, no new pictures (or old pictures) get uploaded to the nextcloud server.
It is just working with WhatsApp Images. 
But: I can see the new taken pictures in the app -> Auto Upload - there are the new pictures, but they dont get uploaded into the cloud! 

### Expected behaviour
Auto Upload new taken pictures
 
### Steps to reproduce
1. Open App
2. Go to Auto Upload
3. Turn on sync
4. take a picture

### Environment data
Android version: 7.0

Device model: Huawei Mate 9

Stock or customized system: Stock

Nextcloud app version: 1.4.0 and also with the newest beta version

Nextcloud server version: 11.0.0

EDIT:
I tested the app now on my S7 Edge with the latest android 7 beta - its also not working.

**Comment by henningvs** [comment]
I can confirm the problem. Neither old or new pictures are synced to the cloud after selecting the folder for sync.

# Environment data

Android version: 7.1.1
Device model: Google Nexus 5X
Stock or customized system: Stock
Nextcloud app version: 1.4.0 (from Play Store)
Nextcloud server version: 10.0.2

**Comment by SnipeLike** [comment]
Same on my Samsung Note4 with Android 6.0.1 with Nextcloud App Version 20161129.

**Comment by bene33** [comment]
Same on my LG G5 with Android 7.0 with Nextcloud Version 1.4.0 and Nextcloud server 11.0.0

**Comment by su-ex** [comment]
Same on my Samsung Galaxy S5 with Android 7.1.1 and Nextcloud beta Version 20161215.

**Comment by nwcatalyst** [comment]
Confirmed same issue with Xperia Z3c rooted. Android 6.0.1. 

Have tried the latest beta and 1.4 version in Google Play store. Server version 10 on Linux Mint 18.

**Comment by equinoxefr** [comment]
Hi,

Same problem for me. No autoupload in android 7.1 (Nexus 5X stock)

Regards

**Comment by reinvented** [comment]
The issue for me (Nextbit Robin, Android 7.0) isn't so clear cut: _sometimes_ images and screen shots sync, sometimes they don't.

**Comment by witteschnitte** [comment]
Same issue for me! Android 6.0.1. since the beta 29112016  auto upload is not working anymore. I like the New Feature to select folders, but it is not working. no pictures get to the upload queue.
I write tons of mails to the nextcloud Team but no one answers. 
Home you fix this before you rolling out this app!

**Comment by marmeladema** [comment]
Same on nexus 5X with CopperheadOS and nextcloud beta from f-droid.

**Comment by 062bel313** [comment]
It was working fine till yesterday (10.0.1), and I updated nextcloud server (to 10.0.2) and auto upload does not work, I can see all new files in the autoload folders, but do not get uploaded.

**Comment by gibbon-joel** [comment]
Can confirm with app 1.4.0

Huawei mate 9, Android 7.0. 

Most Screenshots get uploaded, but photos are not uploaded even though they will show up in the Auto Upload Folder Gallery.

**Comment by gibbon-joel** [comment]
nextCloud  is also version 10.0.2. I can not say if the new style upload worked before with 10.0.1 because I changed my phone since the upgrade and can not remember if I had old or new style auto upload.  Sorry for the double comment.

**Comment by fredfs456** [comment]
Similar issue
Nextcloud Android app 1.4.0
Nextcloud 11
Android 7.1.1 Build NMF26F, Nexus 5X (stock)

**Comment by tobiasKaminsky** [comment]
@witteschnitte 
can you give us some more details on your device? android version and device type?
Of course we do not want to break any working features.

**Comment by witteschnitte** [comment]
Hey. I used android 6.0.1 on my galaxy s6. But it also tested it under android 4 and 5 with galaxy tab 3 and galaxy tab s2. Same here as i already posted.

**Comment by utahbmxer** [comment]
I have not had much luck with the new auto upload feature since moving to Nougat and then the new auto upload feature in Android App 1.4.  I hope this gets fixed soon as this is the most important feature to me.  Would love to help if I could.

NC Server 10.0.2 and now 11.0.0
Stock Nexus 6p running 7.1.1 (Dec 5 patch release)

**Comment by aronovgj** [comment]
I think this is connected:

Reproduce: 
- Have Auto-Upload enabled
- Go to App-Info
- Force close Nextcloud
- Open Nextcloud
- Change to photo app and take a photo
-> Nothing is uploaded

- Disable Auto-Upload
- Enable Auto-Upload
- Take a picture
-> Works

I think that issue could be caused by LMK/doze/standby,... Whatever kicks the app out of memory or stops it from functioning temporarily to save battery.

OOS4 (Andorid 7.0)
NC 11
App 1.4.0

**Comment by gibbon-joel** [comment]
I guess we have several problems then. It behaves differently for me. For me, the nextCloud App has 2 services running: SyncedFolderObserverService and FileObserverService. When I take a picture with the default camera app, it is immediately visible in the Auto-Upload Gallery, but not uploaded.

If I take a picture with the Lightroom Camera App or take a screenshot, it is immediately uploaded. 

The Configuration of the folders is identical. Force-Killing/Restarting makes no difference.

**Comment by SnipeLike** [comment]
I posted this in Issue 498 and might help. So here again:

> Im using Android 6, Beta20170101 and Nextcloud 11. No Pictures are uploaded to my Nextcloud.
> The Serverlog shows the following lines:
> 
> ```
> {"reqId":"olZk+WqwwC1yrKUb6Fqz","remoteAddr":"xy.xy.228.118","app":"admin_audit","message":"Login successful: \"user\"","level":1,"time":"2017-01-04T08:36:10+00:00","method":"GET","url":"\/nextcloud\/ocs\/v1.php\/cloud\/users\/user?format=json","user":"user","version":"11.0.0.10"}
> 
> {"reqId":"olZk+WqwwC1yrKUb6Fqz","remoteAddr":"xy.xy.228.118","app":"no app in context","message":"CSRF check failed","level":0,"time":"2017-01-04T08:36:10+00:00","method":"GET","url":"\/nextcloud\/ocs\/v1.php\/cloud\/users\/user?format=json","user":"user","version":"11.0.0.10"}
> ```

**Comment by gibbon-joel** [comment]
Reinstalling the app and deleting all data does not help either. The camera DCIM folder is watched correctly but not uploaded. ALL other selected folders are.

**Comment by boden** [comment]
Can confirm the issue on Android 7.1.1, Nexcloud App 1.4.0, and Nextcloud Server 11.0.0.

**Comment by AndyScherzinger** [comment]
There is an issue and it seems to depend on the camera app. :(
On my Nexus 5X I see the same issues but haven't found the source as in what the camera app does on a file system level that prevents the implementation to work proper. Two issues I see are taking pictures very fast or activating HDR processing. Both lead to photos not being detected.

**Comment by jaj08** [comment]
I have never had luck no matter the version of Nextcloud with auto upload working. Previous posts suggested upgrading to the beta app would fix my problems, but I am running the 20170122 and continue to have issues


LG V20, Android 7.0, using the default camera app nothing auto uploads.  Just tested with a 3rd party camera app, and the photo immediately auto uploaded.   Server version 11.0.1.

**Comment by tobiasKaminsky** [comment]
@jaj08 so for you it is the same as with @AndyScherzinger:
the stock camera app causes trouble, but a 3rd party camera app works?
So the "basic" auto upload is working. Now we have to figure out why the stock cameras cause trouble..

**Comment by jaj08** [comment]
I continue to test this out, my built in camera will not upload, but when I go under auto upload settings I see all the most recent thumbnail images.

But when I use a 3rd party app, that stores the photo in a different location, it continues to auto upload them no problem.

**Comment by razzildinho** [comment]
I'm encountering the same issue. Can confirm that a third party camera saved somewhere other than DCIM/Camera/ uploads successfully. However, when I set the save directory to DCIM/Camera/ on the third party camera it didn't work. From the logs it looks like the `SyncedFolderObserver` event is not being fired when DCIM/Camera contents changes but is being fired for other directories.

**Comment by witteschnitte** [comment]
for me it is also not working with Screenshots. I also tried other folders but nothing happens. 

My systeminfo you will find in previous posts.

**Comment by mario** [comment]
Hi,

please try newest beta.

https://github.com/nextcloud/android/raw/beta/apks/latest.apk

Thanks!

**Comment by gibbon-joel** [comment]
Hey and thanks Mario. I tried your newest beta.

It takes about 10-30s or so but the app does pick up new photos in the camera folder now (where the original app does not help)

Testing procedure:

- Install BETA app
- Add nextCloud account
- Go to auto-upload settings
- mark cloud icon at "Camera" folder
- change to camera app
- take picture
- change to home screen
- wait a short while

You seem to have improved this for me a lot :) - Thank you very much.

**Comment by mario** [comment]
New beta (out tomorrow) might even a take bit more to start uploading, but the important thing is that it works - thank you for testing! :)

**Comment by mario** [comment]
(Btw. folks if it's not working for you, feel free to re-open the issue, and if it does - cool!)

**Comment by razzildinho** [comment]
Can confirm that the issue is fixed on the beta.

**Comment by witteschnitte** [comment]
I also confirm.  it works with the latest beta on my galaxy s6.  I can sync all folders including camera! 
very nice work nextcloud Team!!!

**Comment by mario** [comment]
Thanks for testing folks and for being this awesome! :)

**Comment by jaj08** [comment]
So while it is now triggering an upload, I seem to be having some new issues. So far in troubleshooting I have cleared out app data, uninstalled, rebooted phone.

Problem is I have configured a custom upload location several sub folders deep. Yet when I now take a photo, it is trying to upload to both my custom location, and the default Instantupload/camera folder.  It has gone back and forth on which one works, as typically the photo or video will only upload to either my instant folder or the custom folder location and the other gets marked as failed.  I assume this is a new issue, but I thought I would start by posting here as it may be related to the fixes put in place for this issue.

**Comment by mario** [comment]
Will try to reproduce.

**Comment by witteschnitte** [comment]
Hi,

I think i was to fast with my working comment.
The new Autoupload now puts all my Pictures in the Queue but don´t upload.
In the new autoupload Settings i set only to upload if the Smartphone is at the power suply.
If i connect it with my power suply, nowthing happens.

Also i missed the Video upload function. my Videos will not recognized anymore.
Dear nextcloud Team. what have you done to a well working app Feature.

Regards.
Felix

**Comment by mc-comanescu** [comment]
Check your Accounts->Next Cloud->Sync->File sync set to be on. The app creates an account with sync permissions. When I activated file sync it started to upload. Android 7

**Comment by aronovgj** [comment]
I have file sync off and autoupload still works.
