### ISSUE TITLE
Deleting multiple files at once files but doesn't

### ISSUE THREAD

**Issue by martinoj2009** [nextcloud/android#463]
### Actual behaviour
When selecting multiple files at once I get a Remove Failed message. The list of items are still displayed. I then back out of the folder and go back in to see that the files were removed. 

### Expected behaviour
Delete the requested files, then refresh the list view. Then determine if the files were deleted, or determine if they did then refresh the list view. 
 
### Steps to reproduce
1. Select multiple files
2. Select remove

### Environment data
Android version:
7.0
Device model: 
HTC 10
Stock or customized system:
Custom
Nextcloud app version:
1.4.0
Nextcloud server version:
11
#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

**Comment by tobiasKaminsky** [comment]
Will be fixed in next minor release (and next beta)

**Comment by tobiasKaminsky** [comment]
#479
