### ISSUE TITLE
Hangs on uploading multiple files

### ISSUE THREAD

**Issue by kotek14** [nextcloud/android#4633]
### Actual behaviour
Adds files to the Uploads queue
Uploads 2 or 3
Stops either at 0% or 100%
I have to swipe down to reload the Uploads queue, after that it may or may not upload 2 or 3 more.

### Expected behaviour
Upload files, one after another.
 
### Steps to reproduce
1. Hit a plus sign, choose "Upload files"
2. Select multiple files (better choose 20-30). Works better with "chewy" files, several megabytes in size.
3. Hit Upload

### Environment data
Android version: 9

Device model: SM-N950U

Stock or customized system: Stock Samsung system

Nextcloud app version: 3.8.0

Nextcloud server version: 17.0.0

#### Web server error log
```
No NGINX errors
```

#### Nextcloud log (data/nextcloud.log)
```
This one is empty
Also, everything works fine with Linux desktop 2.6.0git
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by marckt** [comment]
Same bag

**Comment by xkeysorg** [comment]
Same problem. I think it's the same issue as #3715 .
Android 10
Version 3.9.0
