### ISSUE TITLE
Accountslist disappears when switching to another app and back

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/android#4636]
### Actual behaviour
Accountslist disappears when switching app and go back

### Expected behaviour
- Accountslist should stay visible
 
### Steps to reproduce
1. Open files app
2. Click in the drawer on your username to switch to the Accountslist
3. Open another app
4. Open files app again
5. You literally can watch the Accoubtslist to disappear

### Environment data
Android version:any

Device model: any

Stock or customized system:any

Nextcloud app version: 3.8.0

![ezgif-4-a55283d7f367](https://user-images.githubusercontent.com/4741199/66468424-660a9e80-ea86-11e9-8e3f-08de328cc3cc.gif)

**Comment by tobiasKaminsky** [comment]
:+1:  thanks for the very detailed and good bug report!

I created a fix in https://github.com/nextcloud/android/pull/4640
There is an APK file in this PR, which you can install in parallel to your existing Nextcloud app.
Can you test it?

**Comment by stefan-niedermann** [comment]
Can't find the `apk` ...?

**Comment by tobiasKaminsky** [comment]
It will be there once CI ran, sorry.

**Comment by stefan-niedermann** [comment]
Issue successfully resolved :rocket:
