### ISSUE TITLE
Two Factor Authentication Problem With Android Mobile Client

### ISSUE THREAD

**Issue by Wayne-Fagan** [nextcloud/android#464]
Steps to reproduce

**1. Install Nextcloud client on Android version 6.0.1, kernal 3.4.0-9493471. And sign in to account
2. Enable TOTP on user account - web interface
3. Go back to Android client, and try to sign in**

Expected behaviour

Tell us what should happen

**Should be able to sign in back, or be prompted for a Google Authenticator code to sign**

Actual behaviour

Tell us what happens instead

**Password for user account is rejected, and therefore refuses access to mobile client**

Server configuration

Operating system:

**Ubuntu server 16.04**

Web server:

**Apache 2.0**

Database:

**mysql Ver 15.1 Distrib 10.0.28-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2**

PHP version:

**PHP Version 7.0.8-0ubuntu0.16.04.3**

Nextcloud version: (see Nextcloud admin page)

**11.0**

Updated from an older Nextcloud/ownCloud or fresh install:

Where did you install Nextcloud from:

**Main Nextcloud site**

Signing status:

Signing status
List of activated apps:

App list
The content of config/config.php:

Config report
Are you using external storage, if yes which one: local/smb/sftp/...

Are you using encryption: yes/no

Are you using an external user-backend, if yes which one: LDAP/ActiveDirectory/Webdav/...

LDAP configuration (delete this part if not used)

LDAP config
Client configuration

Browser:

Operating system:

Logs

Web server error log

Web server error log
Nextcloud log (data/nextcloud.log)

Nextcloud log
Browser log

Browser log

**Comment by schrieveslaach** [comment]
I do have the same behaviour. I can not use two factor authentication.

**Comment by sjash** [comment]
@schrieveslaach  @Wayne-Fagan  First log-in using web-client and enable T-OTP and then go to personal-->App Passwords.
Create an Application Password say Mobile client it will show your username and an app password.
Copy that password and when you login through android app give that password instead of your original Password/LDAP password.
It will solve your issue.

**Comment by mario** [comment]
Closed since @sjash gave you a solution :)
