### ISSUE TITLE
Playing long mp3 files is not possible

### ISSUE THREAD

**Issue by pilsnerbeer** [nextcloud/android#4652]
### Actual behaviour
I can play standard length music files just fine. But NC will not play long (1hr+ mp3 files from the cloud). This is the error: (tested on multiple devices)

![Screenshot_20191010-155742](https://user-images.githubusercontent.com/36133540/66576758-c7ef0500-eb67-11e9-81a4-ef36f567f085.jpg)
 
### Steps to reproduce
1.  Play a long mp3 file inside the app

### Environment data
Android version: 9, 7
Nextcloud app version: latest
Nextcloud server version: 16

**Comment by AndyScherzinger** [comment]
@pilsnerbeer does this also happen with the latest dev builds? Just asking sisnce @ezaquarii rewrote the music player, so this might have changed.

**Comment by pilsnerbeer** [comment]
Just as I was about to reply "its not working", the music started running on my phone. It took about 40 seconds to load a 48min tune. (This is not the case for the public version, which does not load the song).

I figured out the dev build will load an mp3 instantly (for a 30min mp3) or with a slight delay (1hr mp3) for the first time its run but the second time user wants to play a mp3 it takes much much longer. This will need more testing.

 ~1 hour mp3s files for testing can be found [here](http://two66.com/mirrors/?dir=GTA-Radio-Stations/GTA-San-Andreas)
