### ISSUE TITLE
Error when connecting to server

### ISSUE THREAD

**Issue by smichel17** [nextcloud/android#466]
### Actual behaviour
- `Malformed server configuration`
### Expected behaviour
- Successful login
 
### Steps to reproduce
1. Open Nextcloud app
2. Enter login details
3. Click Connect

### Additional Info/steps

I've been successfully running Owncloud (v8, I think) for a while. I finally have some spare time, so I decided to upgrade to nextcloud. These were the steps I took:

- wiped owncloud server side
- installed nextcloud with the php installer
- created admin user
- created standard user
- Installed apps: mail, contacts, calendar, notes
- Successfully set up nextcloud desktop client
- Removed android dav-droid account
- Attempted to re-add dav-droid account.
  - Discovery failed. I expected this since I remember having to set up .well-known urls for owncloud to work. Looked up that process, found that the nextcloud app can automatically configure dav-droid.
- Uninstalled android owncloud app
- Installed nextcloud on android
- See `steps to reproduce` above.

I'm happy to do another clean reinstall and attempt with a completely clean server config if that would be helpful.

### Environment data
Android version: 5.0.1

Device model: Verizon Samsung Galaxy s4 (SCH-I545)

Stock or customized system: rooted & xposed, otherwise stock

Nextcloud app version: Latest stable & beta on f-droid
Stable: 1.4.0
Beta: 20161215

Nextcloud server version: 11.0.0 (stable)

#### Web server error log

This error appears a lot. Timestamps do not line up with login requests.
```
Error	PHP	Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. at Unknown#0
```
This error happened once:
```
Error	no app in context	InvalidArgumentException: The given object name is invalid

    /afs/hcoop.net/user/s/sm/smichel17/vhosts/loungecrew.com/htdocs/apps/activity/lib/FilesHooks.php - line 892: OC\Activity\Event->setObject('files', 53, false)
    /afs/hcoop.net/user/s/sm/smichel17/vhosts/loungecrew.com/htdocs/apps/activity/lib/FilesHooks.php - line 184: OCA\Activity\FilesHooks->addNotificationsForUser('smichel', 'created_self', Array, 53, false, true, true, 0, 'file_created')
    /afs/hcoop.net/user/s/sm/smichel17/vhosts/loungecrew.com/htdocs/apps/activity/lib/FilesHooks.php - line 111: OCA\Activity\FilesHooks->addNotificationsForFileAction('/', 'file_created', 'created_self', 'created_by')
    /afs/hcoop.net/user/s/sm/smichel17/vhosts/loungecrew.com/htdocs/apps/activity/lib/FilesHooksStatic.php - line 45: OCA\Activity\FilesHooks->fileCreate('/')
    [internal function] OCA\Activity\FilesHooksStatic fileCreate(Array)
    /afs/hcoop.net/user/s/sm/smichel17/vhosts/loungecrew.com/htdocs/lib/private/legacy/hook.php - line 106: call_user_func(Array, Array)
    /afs/hcoop.net/user/s/sm/smichel17/vhosts/loungecrew.com/htdocs/lib/private/Files/View.php - line 1237: OC_Hook emit('OC_Filesystem', 'post_create', Array)
    /afs/hcoop.net/user/s/sm/smichel17/vhosts/loungecrew.com/htdocs/lib/private/Files/View.php - line 1163: OC\Files\View->runHooks(Array, '/smichel/files', true)
    /afs/hcoop.net/user/s/sm/smichel17/vhosts/loungecrew.com/htdocs/lib/private/Files/View.php - line 266: OC\Files\View->basicOperation('mkdir', '/smichel/files', Array)
    /afs/hcoop.net/user/s/sm/smichel17/vhosts/loungecrew.com/htdocs/lib/private/Files/Node/Folder.php - line 149: OC\Files\View->mkdir('/smichel/files')
    /afs/hcoop.net/user/s/sm/smichel17/vhosts/loungecrew.com/htdocs/lib/private/Files/Node/Root.php - line 380: OC\Files\Node\Folder->newFolder('/smichel/files')
    [internal function] OC\Files\Node\Root->getUserFolder('smichel')
    /afs/hcoop.net/user/s/sm/smichel17/vhosts/loungecrew.com/htdocs/lib/private/Files/Node/LazyRoot.php - line 65: call_user_func_array(Array, Array)
    /afs/hcoop.net/user/s/sm/smichel17/vhosts/loungecrew.com/htdocs/lib/private/Files/Node/LazyRoot.php - line 282: OC\Files\Node\LazyRoot->__call('getUserFolder', Array)
    /afs/hcoop.net/user/s/sm/smichel17/vhosts/loungecrew.com/htdocs/lib/private/Server.php - line 948: OC\Files\Node\LazyRoot->getUserFolder('smichel')
    /afs/hcoop.net/user/s/sm/smichel17/vhosts/loungecrew.com/htdocs/lib/private/User/Session.php - line 411: OC\Server->getUserFolder('smichel')
    /afs/hcoop.net/user/s/sm/smichel17/vhosts/loungecrew.com/htdocs/lib/private/User/Session.php - line 479: OC\User\Session->prepareUserLogin(true)
    /afs/hcoop.net/user/s/sm/smichel17/vhosts/loungecrew.com/htdocs/lib/private/User/Session.php - line 299: OC\User\Session->loginWithPassword(*** sensitive parameters replaced ***)
    /afs/hcoop.net/user/s/sm/smichel17/vhosts/loungecrew.com/htdocs/lib/private/User/Session.php - line 329: OC\User\Session->login(*** sensitive parameters replaced ***)
    /afs/hcoop.net/user/s/sm/smichel17/vhosts/loungecrew.com/htdocs/apps/dav/lib/Connector/Sabre/Auth.php - line 130: OC\User\Session->logClientIn(*** sensitive parameters replaced ***)
    /afs/hcoop.net/user/s/sm/smichel17/vhosts/loungecrew.com/htdocs/3rdparty/sabre/dav/lib/DAV/Auth/Backend/AbstractBasic.php - line 105: OCA\DAV\Connector\Sabre\Auth->validateUserPass(*** sensitive parameters replaced ***)
    /afs/hcoop.net/user/s/sm/smichel17/vhosts/loungecrew.com/htdocs/apps/dav/lib/Connector/Sabre/Auth.php - line 252: Sabre\DAV\Auth\Backend\AbstractBasic->check(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /afs/hcoop.net/user/s/sm/smichel17/vhosts/loungecrew.com/htdocs/apps/dav/lib/Connector/Sabre/Auth.php - line 155: OCA\DAV\Connector\Sabre\Auth->auth(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /afs/hcoop.net/user/s/sm/smichel17/vhosts/loungecrew.com/htdocs/3rdparty/sabre/dav/lib/DAV/Auth/Plugin.php - line 202: OCA\DAV\Connector\Sabre\Auth->check(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /afs/hcoop.net/user/s/sm/smichel17/vhosts/loungecrew.com/htdocs/3rdparty/sabre/dav/lib/DAV/Auth/Plugin.php - line 150: Sabre\DAV\Auth\Plugin->check(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    [internal function] Sabre\DAV\Auth\Plugin->beforeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /afs/hcoop.net/user/s/sm/smichel17/vhosts/loungecrew.com/htdocs/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
    /afs/hcoop.net/user/s/sm/smichel17/vhosts/loungecrew.com/htdocs/3rdparty/sabre/dav/lib/DAV/Server.php - line 466: Sabre\Event\EventEmitter->emit('beforeMethod', Array)
    /afs/hcoop.net/user/s/sm/smichel17/vhosts/loungecrew.com/htdocs/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /afs/hcoop.net/user/s/sm/smichel17/vhosts/loungecrew.com/htdocs/apps/dav/appinfo/v1/webdav.php - line 60: Sabre\DAV\Server->exec()
    /afs/hcoop.net/user/s/sm/smichel17/vhosts/loungecrew.com/htdocs/remote.php - line 165: require_once('/afs/hcoop.net/...')
    {main}
```

#### Nextcloud log (data/nextcloud.log)
I can't find this file. Would it be useful to grab a logcat?

**Comment by AndyScherzinger** [comment]
Hi @smichel17 thanks for the report, yes the logcat would be super helpful to get to the root cause of the error.

**Comment by smichel17** [comment]
A couple things I forgot to include in the original report:

- I have tried using the admin account as well as the standard account; no change.
- The site has an expired cert (I'm lazy)
- My status.php includes `"installed":true` (I saw other threads around the internet in which people received the `Malformed..` error message but had `"installed":false`)

My logcat is really congested; it's ~3000 lines in the ~10 seconds it took me to reproduce. Could you share the tags that you'd look for so I can share that subset with you? (Both to save you the trouble of combing through 3k lines and to save me from worrying about if there's any sensitive info in there.)

I'm going to see if  I can get a clean log from an emulated device in the morning. Failing that, I can post the dirty log if you really want it and/or make an account on my server so you can test yourself. If you'd like that, what's the best way to contact you privately with the credentials?

**Comment by smichel17** [comment]
Okay, got a log from an emulated Nexus 5, API 24 x64.

https://gist.github.com/smichel17/f72448e7bf053c3025ead302ae185be1

This seems to be the most relevant part, at line 116:
```
12-22 11:21:32.434  2538  2572 D ExistenceCheckRemoteOperation: Existence check for https://DOMAIN.com/remote.php/webdav/ targeting for  existence finished with HTTP status 200
12-22 11:21:32.435  2538  2572 D OwnCloudClient #2: REQUEST GET /ocs/v1.php/cloud/user
12-22 11:21:32.541  2538  2572 E GetRemoteUserInfoOperation: Failed response while getting user information 
12-22 11:21:32.541  2538  2572 E GetRemoteUserInfoOperation: *** status code: 500 ; response message: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
```

So, it's possible this is a bug with the server.. although then I'm confused why the desktop client  and web interface both work.

Are there any additional logs that it would be helpful for me to get, server-side? I have ssh access; if there are any logs not shown through the web interface, I can get those too.

**Comment by smichel17** [comment]
@AndyScherzinger Anything I can do to help move this along? Should I create a matching issue on nextcloud server?

**Comment by smichel17** [comment]
I found one thing that was wrong: with my hosting provider, I had added a redirect from `.well-known/carddav/` to `remote.php/carddav/`, the way it was done on oc 8, when now I need to redirect to `remote.php/dav`.

That fixed the error that was preventing davdroid from connecting. However, the nextcloud app is still unable to connect.

**Comment by smichel17** [comment]
I upgraded to 11.0.1 via the manual upgrade process, so this was either an issue with 11.0.0 or with the php installer. Seeing as I don't want to reinstall to recreate this bug, I'm going to close this issue.

**Comment by AndyScherzinger** [comment]
Hi @smichel17 
happy to hear it is working for with the latest server update :)
