### ISSUE TITLE
Refreshing "Favorites"

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/android#4664]
### Actual behaviour
- When refreshing "Favorites" (drag your finger down the screen), it returns to "All files".

### Expected behaviour
- When refreshing "Favorites" (drag your finger down the screen), it refreshes your favorite files.
 
### Steps to reproduce

1. Choose "Favorites" from the menu.
2. Refresh your favorite files by finger down the screen.
3. The app **automatically goes to "All files"**, although the "Favorites" description is active in the menu.

### Environment data
Android version: 6

Nextcloud app version: 3.8.1 and dev-20191011

Nextcloud server version: 17.0.0

**Comment by paskalito** [comment]
Confirmed

Android 7.1.2. LOS 14.1

Nextkoud app 3.8

**Comment by mr-manuel** [comment]
Confirmed, in addition no favorites are shown. The list is empty. I did a fresh install and configuration.

Android 10
Nextcloud Android 3.11.0 RC4
Nextcloud Server 18.0.3
