### ISSUE TITLE
nextcloud crashes when opening a photo from photo view with a green check mark

### ISSUE THREAD

**Issue by stylefish** [nextcloud/android#4666]
### Actual behaviour
- app crashes

### Expected behaviour
- photo should be shown
 
### Steps to reproduce
1. Auto upload is activated with "move to app folder"
2. Tap on a photo that has a green check mark
3. Crash

### Environment data
Android version:9

Device model: pixel 2 xl

Stock or customized system: customized, carbonrom, nextcloud installed via fdroid

Nextcloud app version:
See below
Nextcloud server version:

#### Web server error log
```
```

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'long com.owncloud.android.datamodel.OCFile.getLastSyncDateForData()' on a null object reference
	at com.owncloud.android.ui.helpers.FileOperationsHelper.lambda$startSyncForFileAndIntent$0$FileOperationsHelper(FileOperationsHelper.java:209)
	at com.owncloud.android.ui.helpers.-$$Lambda$FileOperationsHelper$Q56PsCgyFZxef_IG4gCdZEuyyO8.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:764)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080090
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: google
Device: taimen
Model: Pixel 2 XL
Id: PQ3A.190801.002
Product: taimen

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: d4d12b460c

```

**Comment by AndyScherzinger** [comment]
@stylefish can you please upgrade to the latest version and retest? @tobiasKaminsky might have already fixed this recently. :)

**Comment by stylefish** [comment]
This is the latest version published on fdroid. Do you want me to try the "dev" version? But for all day use I would like to stay on "stable" :)

**Comment by AndyScherzinger** [comment]
No worries, you can of course wait for f-droid to publish it and then retest :)

**Comment by stylefish** [comment]
Thanks, seems to be fixed (at least i've not Bern able to reproduce it again).
The photos section of the app is very slow with 20gb of photos in the folder. The web frontend is much faster. Is it planned to speed this up, or to create a gallery app only for viewing photos and videos? :) 
Greetings

**Comment by AndyScherzinger** [comment]
> But the photos section of the app is very slow with 20gb of photos in the folder.

The app loads this via chunks of data (I think 95 at a time) so if this is slow with 20gb of photos on the server than it is actually a server side issue, so cc @nextcloud/server-triage (in case this is a known/unknown issues) for feedback and cc @tobiasKaminsky

**Comment by stylefish** [comment]
@AndyScherzinger thanks for your reply, it seems that it's not the size of the data itself (e.g. big pictures) but the count of the photos in a single folder. when i open the folder in web it takes a little bit longer than for a small folder (e.g. ~5secs) but then its fast. maybe the paging is implemented for data fetching but not for some kind of metadata that gets fetched for all items in a folder upfront? 
my "wild guess" without looking at any code would be that this fetch of a large amount of data works in the browser but the app struggles with it.
only loading some thumbnails in smaller folders works like a charm.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky correct me if I am wrong but I guess @stylefish is right. In case you navigate into a big folder where the content changed we fetch the meta data of the folder and as such all. The files upfront which might take a while for folders with a huge amount of files.
