### ISSUE TITLE
Crash while loading SVG graphics 

### ISSUE THREAD

**Issue by Byggvir** [nextcloud/android#4673]
### Actual behaviour
- Tell us what happens
I browsed SVG pictures. Nexcloud ask if full picture it should download the full picture. - Not a necessary question when the file has only a few kByte.

### Expected behaviour
- Tell us what should happen
Picture should be downloaded and displayed and in case the SVG has only a few kByte Nextcloud should not ask for permission to download the full picture when an smaller version is not available.
### Steps to reproduce
1. Upload some SVG files
2. Browse the files
3. May be the reason is somewhere else.

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by Byggvir** [comment]
The SVG-File was corrupted. Can't reproduce today. The log was unfortunately not uploaded.
Can be closed.

**Comment by Byggvir** [comment]
Seems it is a problem in another app to display grafics and not an Nextcloud issue.

**Comment by AndyScherzinger** [comment]
Thanks for reporting back and closing the issue 🙏
