### ISSUE TITLE
Citing this repository in academic journal

### ISSUE THREAD

**Issue by al-sadi** [nextcloud/android#4698]
### Is your feature request related to a problem? Please describe.

We are working on academic paper that leverages Nextcloud as platform. Now it is the time to cite the GitHub repository but it seems that the repository owner should create a citable DOI link for the repository. 

### Describe the solution you'd like
Using Zenodo as suggested by Github
https://guides.github.com/activities/citable-code/

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky can you take care of this? ❤️

**Comment by tobiasKaminsky** [comment]
@nextcloud/infrastructure can you take care of this, as I am not an admin of the org.

**Comment by al-sadi** [comment]
> @nextcloud/infrastructure can you take care of this, as I am not an admin of the org.

The link you mentioned seems to be broken; can you kindly forward it to the right person?

**Comment by AndyScherzinger** [comment]
Pinging @rullzer for support

**Comment by rullzer** [comment]
Added. should be all triggered on the next release
