### ISSUE TITLE
Auto Upload: auto retry

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#470]
https://developer.android.com/reference/android/app/job/JobInfo.Builder.html#setBackoffCriteria(long,%20int)

Discuss if and how a failed job should be automatically retried.

**Comment by joekerna** [comment]
I would really like this feature. Maybe retry once or twice a day automatically? Or at least notice the user that the upload has failed through a notification.

**Comment by mario** [comment]
Dear users,

thank you for your patience. After lots of work, we’re super excited to be able to give you a test version with new auto upload implementation. Keep in mind we will only accept bugs related to Auto Upload in this APK, as other things might be broken.

https://cloud.nextcloud.com/s/ftZraTruRQjTe0R

This is a dev APK so it will not overwrite your existing play store/f-droid APK unless you’re already running dev version. Also, you might need to remove your existing dev version before installing this one.

Explanation of the current functionality:
- added support for custom folders
- separated image and video folders
- checks for new files happens every 15-20 minutes
- automatic retry every 15-20 minutes or when you force close/open the app
- automatic pause once network is changed (untested!)
- significantly less battery usage

All and any testing is more than appreciated, especially with large and ever-going files like Videos. (like, try to record a 30 min video).

Let me know if you’ve got any questions.

Cheers,
Mario

**Comment by mario** [comment]
Done in a branch that will be merged to master, so closing. :) (If you think it's too early, please re-open)

- Jobs are retried every 15-20 Mins
- Jobs are retried on network change or charging change (Android 4.2.2 and up!)
- Jobs are retried every time a new "instant" photo or video is detected and processed
- Jobs can be manually retried in Uploads view if you enable an expert mode in settings
