### ISSUE TITLE
Nextcloud App account name doesn't update in system file picker.

### ISSUE THREAD

**Issue by triptronics** [nextcloud/android#4706]
### Actual behaviour
- Tell us what happens
I open an app that invokes the default Samsung/
Android file manager and the account name listed under Nextcloud is that of an old account I removed.
### Expected behaviour
- Tell us what should happen
 I removed all nextcloud accounts and created a new account under a new name. I expect this name to be listed in the system file picker, nothing else.
### Steps to reproduce
1. Have a predefined nextcloud account.
2. Delete that account and create a new account with a different URL/port.
3. Open a separate app and notice the new URL and port does not appear. The initial nextcloud account information is listed...

### Environment data
Android version: 9

Device model: Samsung S8

Stock or customized system:
Stock
Nextcloud app version: 3.8.1

Nextcloud server version: 

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
Is this happening over a longer period of time? It takes some time for Android itself to refresh these infos.
