### ISSUE TITLE
PDFs > 1MB too large

### ISSUE THREAD

**Issue by AvoMMH** [nextcloud/android#4707]
### Actual behaviour
When uploading a pdf larger than 1MB the app tells me "Request Entity to large".
The connection is opened, but never completed (HTTP 110).

All other files work without problems. It seems to be a specific problem with pdf files.
Via the web ui it works properly.

### Expected behaviour
- It should upload the file.
 
### Steps to reproduce
1. Upload a pdf larger than 1MB

### Environment data
Android version:
6.0, 9.x

Device model: 
Huawei p8 lite, Samsung S9, Samsung S4

Stock or customized system:
Stock

Nextcloud app version:
3.8.1

Nextcloud server version:
16.0.4

#### Web server error log
```
2019/09/10 11:37:02 [error] 30444#30444: *2890906 upstream timed out (110: Connection timed out) while reading response header from upstream, client: x.x.x.x, server: cloud.xxx.de, request: "POST /updater/index.php HTTP/1.1", upstream: "http://x.x.x.x:80/updater/index.php", host: "cloud.xxx.de", referrer: "https://cloud.xxx.de/updater/"
```

#### Nextcloud log (data/nextcloud.log)
```
It never reaches the Nextcloud API
```

**Comment by AvoMMH** [comment]
The issue is not solved.
Only diff is the Nextcloud Version: 17.0.1 and App Version 3.9.0

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky any ideas whiy this might be happening ans also is limited to pdfs? 😕
