### ISSUE TITLE
Use Login Flow with DAVx⁵

### ISSUE THREAD

**Issue by rfc2822** [nextcloud/android#4708]
DAVx⁵ supports the Nextcloud Login Flow since 2.6-beta1. The intent is documented here: https://www.davx5.com/manual/technical_information.html#api-integration (updated recently so you may have to refresh the browser cache)

I suggest to call the new Intent from the Nextcloud app so that Login Flow is used.

Compatibility:

* old Nextcloud app / new DAVx⁵ versions: no problems, because the URL/username/password extras are still actively supported
* old DAVx⁵ / new Nextcloud app versions: You could set both the url, username, password extras and the data URI + loginFlow/davPath extras. In this case, new DAVx⁵ versions will see the loginFlow extra and switch to Login Flow, while old DAVx⁵ versions will still use the URL/username extras.

If you need any assistance or anything else, please just write here or there: https://forums.bitfire.at/topic/2121/please-support-nextclouds-singlesignon-sso

**Comment by AndyScherzinger** [comment]
Pinging @tobiasKaminsky 😊

**Comment by tobiasKaminsky** [comment]
@rfc2822 thanks for your great work!
I found a little bug and fixed it: https://gitlab.com/bitfireAT/davx5-ose/merge_requests/22

**Comment by AndyScherzinger** [comment]
@rfc2822 will ship this with the upcomming 3.9.0 🎉

**Comment by rfc2822** [comment]
Thanks, I have merged the two MRs to DAVx⁵. Would it be possible that you send a current Nextcloud APK so that I can have a try too? :)

**Comment by tobiasKaminsky** [comment]
In every PR is always a QA build which can be installed in parallel.

https://github.com/nextcloud/android/pull/4716#issuecomment-545807542

**Comment by rfc2822** [comment]
Thanks. Seems fine for me :) We'll release DAVx⁵ 2.6 soon.

**Comment by jakobroehrl** [comment]
Hi, sorry about the question, but where is the difference between the solution before?
I installed the 2.6 but I have to fill in the credentials again if I start dav5x out of the nextcloud App (3.9.0).
There is no single sign on. Or do I made a mistake? Or is the flow login not with sso?
Thanks for clearification

**Comment by szaimen** [comment]
@jakobroehrl 
You can look here for details:
https://forums.bitfire.at/topic/2121/please-support-nextclouds-singlesignon-sso/8

**Comment by tobiasKaminsky** [comment]
@jakobroehrl it is not about single sign on, but about easily generate an app token.
