### ISSUE TITLE
Fingerprint unlock

### ISSUE THREAD

**Issue by DjSni** [nextcloud/android#4709]
### Actual behaviour
- the fingerprint unlock appears with the code login -> 3. screen
- using the fingerprint unlock and the fingerprint disappears
- now the pin must be entered otherwise no unlock -> 4. screen

### Expected behaviour
- Able to unlock with fingerprint.
 
### Screenshots

![Screenshot_2019-10-19-12-29-21-542_com nextcloud client](https://user-images.githubusercontent.com/31524614/67158553-afd26f00-f339-11e9-9680-da1650cff4ea.png)

![Screenshot_2019-10-19-12-29-09-710_com nextcloud client](https://user-images.githubusercontent.com/31524614/67158560-bd87f480-f339-11e9-9721-4d84d50addc4.png)

![InkedIMG_20191020_130415_LI](https://user-images.githubusercontent.com/31524614/67158733-06d94380-f33c-11e9-9266-f67f1b3cc0ad.jpg)
- Before fingerprint unlock

![InkedIMG_20191020_130430_LI](https://user-images.githubusercontent.com/31524614/67158737-0e005180-f33c-11e9-8847-ec5a575eae1f.jpg)
- After fingerprint unlock

### Environment data
Android version: 9.0 PKQ1.181121.001

Device model: Xiaomi Mi 9 SE

Fingerprint sensor: Under-Screen Fingerprint Sensor

Stock or customized system: Stock -> Miui Global 10.3.9 Stable

Nextcloud app version: 3.8.1 (Play Store Beta Channel)

Nextcloud server version: 16.0.4

**Comment by DjSni** [comment]
the bug seems to be fixed with the last update 3.9.0

**Comment by AndyScherzinger** [comment]
Thanks for the update @DjSni - we haven't changed anything in this area so this has rather been fixed on the operating system level (I guess)
