### ISSUE TITLE
Add a home button

### ISSUE THREAD

**Issue by paskalito** [nextcloud/android#4714]
I often find myself several foldera deep in the nav. Especially when i "return" to the app.

Then i want to go to / fast. This however seems not to be possible. And i end up clicking the back button several times. (On the very awkward tip left corner of my phone) with too long waiting times in between.

So a nice home button next to the back button that would take me back to /  would do it :)

Also see

https://github.com/nextcloud/android/issues/3219

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger 
This seems to be a bug for me:
- go into /sub/folder/2/
- suspend app
- go back to app
- be in folder 2 :+1: 
- click on "all files"
- nothing happens
--> should return to root folder, or?

At least this is what I recall…

**Comment by AndyScherzinger** [comment]
It should return to root folder yes.
Other than that one needs to know that the menu can be called via a swipe from the left... So some kind of better up navigation would be nice. But that would be a larger task that needs to be discussed and designed...

**Comment by tobiasKaminsky** [comment]
At least the first part is fixed.
Having a better navigation is some other enhancement task.
