### ISSUE TITLE
Remove local file doesn't delete file from device

### ISSUE THREAD

**Issue by OlivierS1** [nextcloud/android#473]
### Actual behaviour
When trying to delete / remove local files from device, the device returns the following error message:
"Removal Failed"
The file remains in the device.

To an extent, trying to move the file to another location, the file gets copied to the new location succesfully, but the file in the old location is still present.

### Expected behaviour
 - Removal of the file should happen.

### Steps to reproduce
1. Select a file in the device with Nextcloud app.
2. When prompted with "Do you really want to remove ...?": Select "LOCAL ONLY.
3. Upon removal, the error message will popup.

### Environment data
Android version:
6.0

Device model: 
LG-D852

Stock or customized system:
Stock

Nextcloud app version:
1.4.0

Nextcloud server version:
Owncloud 9.1.1
Nextcloud 11.0.0

**Comment by hannemann** [comment]
I can confirm this behaviour on Nexus5 with cm14.1, nextcloud 10, App 1.4.0

**Comment by hannemann** [comment]
I downgraded to Version 1.3.1 of the client which is not affected by this bug

**Comment by tobiasKaminsky** [comment]
Will be in next minor release

**Comment by hannemann** [comment]
Great to hear.
Thank you
