### ISSUE TITLE
Storage path "unkown" by default, cannot be changed to a custom value. Selecting the only available option "/storage/emulated/0/Android/data/com.nextcloud.client/files" breaks gallery functionality. Pictures made are not moved to the storage location.

### ISSUE THREAD

**Issue by ghost** [nextcloud/android#474]
Probably related to:
#452 
#453 

### Actual behaviour
In settings, storage path says "unkown" by default. It can only be set to "/storage/emulated/0/Android/data/com.nextcloud.client/files". No further options are available. This is unexpected behaviour.

Pictures synced with the nextcloud server are stored in the "nextcloud" folder, as long as this option is **not** changed from "unknown". The *are* visible in the stock Gallery App. This is the expected 
behaviour.

When "Instant picture uploads" is selected and "Original file will be...moved to the app folder", the picture is uploaded but **not** moved to the nextcloud folder on the device. This is unexpected behaviour.

Once the storage path is changed to the only available option "/storage/emulated/0/Android/data/com.nextcloud.client/files", synced/downloaded pictures are **not displayed in the stock Gallery App** any more. This is unexpected behaviour.

Pictures made are still uploaded to the server but not moved to the storage path on the device.

### Expected behaviour
Default storage path should be displayed instead of "unknown". Be able to select a custom storage path. After selecting the storage path, picture files synced with nextcloud should still be visible via the stock Gallery App. Picture made should be moved to the app folder after successful upload.
 
### Steps to reproduce
1. Take picture
2. Wait for successful upload
3. Check picture location with any file manager on device - it still is in DCIM/Camera
4. Select "/storage/emulated/0/Android/data/com.nextcloud.client/files" as storage path
5. Display of media content (e.g. pictures) synced with nextcloud is broken, pictures are not displayed any more in the stock Gallery app.
6. Redo step 1-3, pictures made are still not moved to the storage location.

### Environment data
Android version: 6.0.1
Device model: Samsung Galaxy S4 Mini (GT-I9195)
Stock or customized system: Cyanogenmod 13.0 (Android 6.0.1)
Nextcloud app version: 1.4.0 
Nextcloud server version: 11.0.0

**Comment by SaittamW** [comment]
Same issue: [#429](https://github.com/nextcloud/android/issues/429)

**Comment by tobiasKaminsky** [comment]
We have changed the storage location on sdcard to /sdcard/media/... to allow gallery to scan the downloaded images again.
This will be in next version.
