### ISSUE TITLE
Update to material 1.1.0

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#4749]
Update to material 1.1.0 ([when released](https://mvnrepository.com/artifact/com.google.android.material/material?repo=google))

**Comment by tobiasKaminsky** [comment]
As this is now in master, and we have dependabot, we do not need this issue anylonger.

**Comment by AndyScherzinger** [comment]
Dependabot only notifies about 1.2.0 since alpha is already out, so we don't get this info!

**Comment by tobiasKaminsky** [comment]
Ah, right. As we are on unstable (alpha) it assumes that we also want to have updates for other alphas (including 1.2.0) and thus we do not get stable info.

Damn…

**Comment by AndyScherzinger** [comment]
DONE
