### ISSUE TITLE
Wrong setting header color after enabling dark

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#4754]
![2019-10-29-114643](https://user-images.githubusercontent.com/5836855/67760551-cebfb800-fa41-11e9-9ed3-f4966d1c5d80.png)

- install for first time
- go to setting
- enable dark theme

**Comment by tobiasKaminsky** [comment]
Did not happened to me with #4757 
If happens again, we can re-open.

**Comment by tobiasKaminsky** [comment]
This happens for me, when I set server theming to white and enable dark  mode.

**Comment by AndyScherzinger** [comment]
Hmmm, but isn't the header the same for dark/light? At least I don't knwo how to handle this or when to decide for which color (black/white hheader text/icons)

**Comment by tobiasKaminsky** [comment]
I think it is just missing that black text should be used instead of white.
I'll have a look.
