### ISSUE TITLE
Obey dark/light setting by OS

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#4757]
In Android 10 one can enable dark mode in quick settings, this should be reflected by our app.
Something like:
Theme
- dark
- light
- determinated by system

**Comment by tobiasKaminsky** [comment]
Nearly done. PR will be coming this week.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky pllease be aware of https://github.com/nextcloud/android/pull/4797#discussion_r342792918
