### ISSUE TITLE
Create a brand feature to disable completely notifications

### ISSUE THREAD

**Issue by Shagequi** [nextcloud/android#4759]
Hello,

When forking this project, some developers may not have set up a push server, and therefore the "Notifications" activity becomes unnecessary as there have never been any notifications.

I propose to allow the developer to decide whether or not to activate the entire notification system. 

By adding a setting in `setup.xml`, disable NotificationActivity, Drawer Item and add a filter to block any other notification to come from app.

**Comment by Shagequi** [comment]
This idea is based on PR 4753 : https://github.com/nextcloud/android/pull/4753

**Comment by AndyScherzinger** [comment]
Hi @Shagequi,

two things that are slightly different as to my knowledge (please correct me if I am wrong @tobiasKaminsky):

> When forking this project, some developers may not have set up a push server

The push server is run by Nextcloud (as in the company) themselves for any Nextcloud installation

> and therefore the "Notifications" activity becomes unnecessary as there have never been any notifications.

The notifications of Nextcloud have nothing to do with push notifications. They are notifications which are being created within the Nextclud server and it's installed 3rd party apps. They do in fact get delivered to the client(s) as push notifications (also) but they are notifications (within Nextcloud) so they are always loaded via Nextcloud's server API. So they are always there no matter the presence of a push notification server (!)
Hiding notification (as a feature) is conterproductive, an example is when a file gets shared with you, so as a user you want to know this and the notifications list in the app is the only way to discover this fact.

**Comment by Shagequi** [comment]
Hi @AndyScherzinger ,

after several tests to create internal notifications (without push server) like creating a new media folder, or uploading a file, etc. 
I notice that these notifications do not appear in the `Notifications` tab....

So, this Activity doesn't show internal notifications, nor push notifications.
Is it a bug ? If not, what is the purpose of this activity/tab?

**Comment by Shagequi** [comment]
So it must pass through server to be defined as a "server-side notification" ? But it doesn't depend on push-server ?

Which notifications are internal, which ones are serverside and which one are used by "push-server" ? I don't really understand ^^'

**Comment by AndyScherzinger** [comment]
😁 Hard to tell since I don't contribute to the server's development. I think @nickvergessen is probably the one who can answer this best.

> So it must pass through server to be defined as a "server-side notification" ? But it doesn't depend on push-server ?

Exactly, afaik notifications are also sent as push messages but for the feature to work this isn't needed. The push server is just to get nextcloud's notification delivered as push notifications. That's it.

Of course the Android client also shows other notifications (as in Android Notifications (via the system bar) for new media folders detected (as an example) this is pure client-side logic and has nothing to do with the Notifications menu item in the app. (not sure I explained this clearly...)

**Comment by tobiasKaminsky** [comment]
Just in short
- if a notification is created on server, it is also pushed via push proxy
- push proxy only works with our official builds, for other builds/certificates, one need its own push server
- in this repo we will only include options / code for official clients
- if you want to enhance/modify the client in any way, please fork it, modify it.
- if you think an ehancement (e.g. new feature xy) would fit, please open first up a new issue, discuss it, if it as approved, then create a PR, not vice vera

**Comment by nickvergessen** [comment]
In addition to what Tobias said, everything will work apart from push notifications. So it makes sense to keep the notification/activity section of the app because they still allow you to access the information.
