### ISSUE TITLE
Note field has wrong cursor color

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#4760]
![device-2019-10-07-171909](https://user-images.githubusercontent.com/1315170/66325280-427d1200-e927-11e9-8876-c506acd7cedd.png)

**Comment by tobiasKaminsky** [comment]
Hm. I found no way other than using reflection, but this will not work with Android 10…As they lock down those reflection tricks…

**Comment by AndyScherzinger** [comment]
😣 Does 10 allow for other ways to do this?

**Comment by tobiasKaminsky** [comment]
No. Not that i found…
Which is weird :-/

**Comment by tobiasKaminsky** [comment]
@dan0xii do you have maybe an idea?
This does only happen on dark theme.

**Comment by dan0xii** [comment]
I think you are correct re: reflection not working anymore. I did some testing and couldn't find a reliable way of changing the cursor colour in 10. It is strange they don't have a supported method.

Leave this issue open and I'll take a look as it was some time ago that I last did.

**Comment by tobiasKaminsky** [comment]
Maybe we can just hardcode it to black/white, without trying to dynamically tint it?
It is not the best solution, but better than this strange color.

**Comment by joshtrichards** [comment]
No longer the behavior in recent builds. Closing out!
