### ISSUE TITLE
In properties of a file, "Set picture as" item doesn't work

### ISSUE THREAD

**Issue by Shagequi** [nextcloud/android#4764]
Hello,

![screen_shot](https://user-images.githubusercontent.com/7050479/67847389-122e2b00-fb03-11e9-8141-88bd4e22a6fe.jpg)

This button (in english "Set picture as" or "Use image as") doesn't work, but only in the properties of a file.

Release 3.8.1 - branch stable

**Comment by AndyScherzinger** [comment]
@Shagequi Maledives? 😁 I can reproduce the issue, do you fancy providing a fix for this? ❤️

**Comment by Shagequi** [comment]
@AndyScherzinger Yes :)
Currently working on it (and other things) I'll notify you when it'll be ready

**Comment by AndyScherzinger** [comment]
Best to have a PR per "issue" that helps with the review and keeps PRs small and tidy 😊
