### ISSUE TITLE
dynamic PNG background

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#4766]
Currently we have always a white PNG background with chess board pattern.
We should discuss if we want to change this dynamically on dark mode to a black background with chess board pattern?
Or if we say that is ok to have it always white.

@dan0xii @AndyScherzinger

**Comment by jancborchardt** [comment]
Yep, white checkered background is the way to go even in dark mode as the typical empty "canvas" of any graphics app is also white. In practice the issue is mainly when there’s white-only icons (like we have in Nextcloud) and then the checkerboard pattern comes in.

**Comment by AndyScherzinger** [comment]
Then it is already working as expected 👍
