### ISSUE TITLE
Nextcloud android app

### ISSUE THREAD

**Issue by Joedrummer720** [nextcloud/android#4770]
### Actual behaviour
- Tell us what happens
Tried to manage users on android app
### Expected behaviour
Should be able to add a user
 
### Steps to reproduce
1. 
2. 
3. 

### Environment data
Android version:
10
Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky adding users is imho a admin task and is not within the scope of a end user app.

**Comment by tobiasKaminsky** [comment]
Correct, this is something that we should not put into our app.

**Comment by Joedrummer720** [comment]
Thanks, makes sense now that I understand how the app is designed.

 

Joe

jgarbus@kensicoconsulting.com
