### ISSUE TITLE
Improve menu file name pattern

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#4774]
Adapt naming pattern based on https://github.com/ribot/android-guidelines/blob/master/project_and_code_guidelines.md

#### 1.2.2.3 Menu files

Similar to layout files, menu files should match the name of the component. For example, if we are defining a menu file that is going to be used in the `UserActivity`, then the name of the file should be `activity_user.xml`

A good practice is to not include the word `menu` as part of the name because these files are already located in the `menu` directory.

**Comment by tobiasKaminsky** [comment]
:+1:
