### ISSUE TITLE
Drop Android 4.1 support

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#4778]
Follow-up of #2923 for the release after. So looking at the 0.5% rule (and not dropping more than one Android version at a time) we can shedule dropping Android 4.1 making 4.2 (sdk version 17) the min version for 3.11.

* [ ] Right after this issue has been resolved #4480 should be reactivated to get that depedency updated (which requires Android minSDK 17)

cc @tobiasKaminsky

**Comment by tobiasKaminsky** [comment]
We do not need an issue for that, it is in our overview issue:
https://github.com/nextcloud/android/issues/150

Other than that I am fin with it.
If you want to get it tracked, then create an overview issue for 3.11 and add it there.

**Comment by AndyScherzinger** [comment]
added infos to overview release issue 👍
