### ISSUE TITLE
No buttons on date picker

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#4783]
- set theming to white
- create a share
- set an expiration date
- see no button
![2019-11-01-152419](https://user-images.githubusercontent.com/5836855/68031313-b2c74b00-fcbb-11e9-80bf-5a9f3f277e6e.png)

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky @dan0xii The text is likely white so we need to do yet another color analysis (like we do in other places when contrast is "too low").
