### ISSUE TITLE
Black background in the application settings

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/android#4785]
After choosing "Settings" from the application menu only a black background appears.

App:
Nextcloud Android: dev-20191102
Android 6

**Comment by ralfi** [comment]
Also here, everything else works

**Comment by AndyScherzinger** [comment]
@ralfi which app version and Android version are you running?

**Comment by ralfi** [comment]
Hi Andy, it crashed only with the latest Dev - since a few days. Could be related to pin setting seems me.

**Comment by ralfi** [comment]
And only if you go to settings

**Comment by AndyScherzinger** [comment]
Hmm "only a black background appears" and "crashed only with the latest Dev" are two rather differend things. Do you see any error infos showing up? What @Valdnet described might rather have something to do with the new dark/light theming option

**Comment by ralfi** [comment]
Hi, the symptom is user independent. The Dev App (from today) crashes when running the Settings function. It is strange that despite complete app cleaning deposited somewhere that the app is protected with pin. I do not think it's related to the Black Theme.

**Comment by ralfi** [comment]
[logs.txt](https://github.com/nextcloud/android/files/3803466/logs.txt)

Log File Part from Crash Time ...

**Comment by ralfi** [comment]
Mmmh, complete both apps and install 3.9 RC1 -fine. Then i am install the latest dev again and switch to settings works and also dark theme works but the App-PIN setting is enabled with Pin?? Is there a default pin or is this the problem? If i try to disable the dev app crashed.

**Comment by ralfi** [comment]
![Screenshot_20191104-112635_Nextcloud dev](https://user-images.githubusercontent.com/294423/68114407-38ced600-fef6-11e9-9d19-9ea399a23613.jpg)

**Comment by Valdnet** [comment]
In version dev-20191107 the app works correctly.
