### ISSUE TITLE
Bypassing AppPreferences in BaseActivity

### ISSUE THREAD

**Issue by ezaquarii** [nextcloud/android#4791]
### Actual behaviour
`BaseActivity` uses `SharedPreferences` directly and cherry-picks private implementation details from `AppPreferencesImpl`.

### Expected behaviour
Application should use application abstraction `AppPreferences`.
`AppPreferencesImpl` is private implementation and shall not be touched.
 
### Steps to reproduce
This regression has been introduced in 1615130093d382211c3c84d33ff2b6206d5f5728 and c1aa005db929d08af4453489de603938e9d0c9c2

**Comment by ezaquarii** [comment]
@AndyScherzinger @tobiasKaminsky @dan0xii 

I think this should be addressed. This change is against design principles we try to intr

The only reason we still have `AppPreferencesImpl` accessible is that we can't close it due to some tech debt in other places, but this **will** change. 

1. Private implemenation shall not be accessed - all calls should be via relevant interfaces
2. `SharedPreferences` shall not be accessed directly as it is unmanageable from data migration perspective

**Comment by AndyScherzinger** [comment]
You are absolutely right 👍
I haven't had much sleep lately... 

This should be addressed and be fixed before 3.10. While I don't know how to remove the change listener (I guess you have an idea 😊)

**Comment by ezaquarii** [comment]
We shall just extend the `AppPreferences` interface and delegate to the shared preferences inside the `*Impl` insntance. Pretty trivial refactoring.
