### ISSUE TITLE
Make the search case insensitive

### ISSUE THREAD

**Issue by Shagequi** [nextcloud/android#4793]
Hello,

The search input is case sensitive.
For example, I have a file named "Sac.jpg", and if use search bar and type "sac" (with the `s` in lowercase), the activity will not display the file.

![Capture d’écran 2019-11-04 à 10 23 19](https://user-images.githubusercontent.com/7050479/68110578-901c7880-feed-11e9-8455-0ebc4ebb2461.png)

I therefore propose to make the search case insensitive, in order to simplify the search process.

![Capture d’écran 2019-11-04 à 10 23 25](https://user-images.githubusercontent.com/7050479/68110567-8a269780-feed-11e9-9d11-90a02b9bb9f9.png)

@AndyScherzinger this is something I'm going to apply on my own project, do you approve this idea for yours ?

**Comment by Shagequi** [comment]
My bad, this is already managed 😓
I close, sorry.

**Comment by AndyScherzinger** [comment]
No worries. I am slightly confused, so it is working already or not? I am a bit confused by the messages 😅

Also feel free to usually also ping @tobiasKaminsky (also a maintainer)
