### ISSUE TITLE
Android - Auto Upload STILL not working after 1.5 Years!!!

### ISSUE THREAD

**Issue by backamblock** [nextcloud/android#4800]
### Actual behaviour
- i connect nextcloud android app with fresh nextcloud install
- i select folders in "Auto upload" to sync to specific folders in nextcloud
- nextcloud android does not upload anything

### Expected behaviour
- i connect nextcloud android app with fresh nextcloud install
- i select folders in "Auto upload" to sync to specific folders in nextcloud
- nextcloud android should upload ALL data in the selected folders (pictures/videos/...) to nextcloud server

### Steps to reproduce
1.  install nextcloud android
2.  select folder to sync via auto upload
3.  wait for upload (which won't start.. ;)

### Environment data
Android version: 9 (Pixel Experience Rom)

Device model: Poco F1

Stock or customized system: Custom (but stock does not work either, Not even lineage works with the app)

Nextcloud app version: 3.8.1 (Playstore Version)

Nextcloud server version: 17.0.0

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by szaimen** [comment]
The auto upload feature just uploads newly created files inside this for auto-upload marked folder. What you want to do is partially covered here: https://github.com/nextcloud/android/pull/4788

**Comment by AndyScherzinger** [comment]
And sync is described in #285
