### ISSUE TITLE
Enhancement: Constant and Unique HTTP User Agent for Nextcloud Clients.

### ISSUE THREAD

**Issue by nextra06** [nextcloud/android#4807]
Hello All,

Kind request to the devs to make the user agents of all the clients (Android, PC Desktop, Linux Desktop) constant and unique which does not change with any updates.

Regards.

**Comment by tobiasKaminsky** [comment]
Can you explain us a bit more why you need this?

**Comment by nextra06** [comment]
Needed to add an extra layer of security so that if someone wants they can only allow there predefined headers to pass and rest be redirected elsewhere. Say like a pre login check.

**Comment by tobiasKaminsky** [comment]
As UA can be faked anyway, this is not a reliable way for  any security concern.
Also UA changes only by version number, so you can use a regex.
