### ISSUE TITLE
no comments on android app

### ISSUE THREAD

**Issue by danielweigandt** [nextcloud/android#4809]
The comments of files are not displayed. Nothing below "New comment..." field

**Comment by kesselb** [comment]
[Issue Template](https://github.com/nextcloud/android/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) makes it much easier to triage issues.

**Comment by 1234michi** [comment]
I also see no comments F-droid(3.13.0), but I can write comments...
Anyone else this problem? Then I can create an issue - otherwise it seems it my fault...
