### ISSUE TITLE
Duplicate auto upload folders

### ISSUE THREAD

**Issue by eitch** [nextcloud/android#4810]
### Actual behaviour
- Install App
- Go to Auto Upload
- See duplicates of photos in images and video folder (e.g. for camera)

### Expected behaviour
- Should only see a file in one category for a single folder (video or image)
 
### Steps to reproduce
- Install App
- Go to Auto Upload
- See duplicates

### Environment data
Android version: 10.x

Device model: Pixel 3a

Stock or customized system: stock

Nextcloud app version: 3.8.1

Nextcloud server version: 17.0.0

**Comment by AndyScherzinger** [comment]
@eitch please check the icons, there you be separate folders for video and images. So this is by design. 

Please reopen in case you really see duplicated folders with then same content.

**Comment by eitch** [comment]
Ahh yes, true. One icon is for the photos and one for the videos. But sadly the auto upload folder for videos also contains photos...

**Comment by AndyScherzinger** [comment]
@eitch I am not sure I understand, the folder (on your device) liely has mixed media content. So for videos and images to be uploaded both entries need to be activated. Beware though that only files created _after_ activating the option will be uploaded

**Comment by eitch** [comment]
@AndyScherzinger 

On my device i have two entries in the auto upload view. One for the photos, and one for videos. Yet strangely in the video entry i see photo thumbnails. So i guess the entry is not just handling videos, as suggested by the icon, but also photos.

Futher some photos are in both entries.

**Comment by AndyScherzinger** [comment]
>One for the photos, and one for videos. Yet strangely in the video entry i see photo thumbnails.

That would then actually be a bug because that should not happen!

**Comment by AndyScherzinger** [comment]
@eitch are you sure it i like that? as for live images (since you run Androuid 10) the google app created videos and images at the same time... Can you check this maybe with a file explorer?

**Comment by eitch** [comment]
I just checked again, and those files are truly photos, which are shown as videos. I just made a few new photos and they show up properly. 

Perhaps it is because it was a new installation and those files were already on the phone, when NextCloud saw them.
