### ISSUE TITLE
syncronising subfolders leads to conflicts

### ISSUE THREAD

**Issue by hex-m** [nextcloud/android#4817]
### Actual behaviour
- I take a photo and nextcloud uploads it automatically. But it also leads to a sync conflict.

### Expected behaviour
- It should not lead to a conflict. The misconfiguration I have should not be possible.
 
### Steps to reproduce
1. Configure DCIM for auto-upload
2. Configure DCIM/Camera for auto-upload
3. take a picture
4. you get a conflict

### Environment data
Android version: 7.1.2

Device model: Galaxy S3 (GT-I9300)

Stock or customized system: customized

Nextcloud app version: 3.8.1 (f-droid)

The App should throw an error in step 2 and not allow autoupload of folders when subfolders or superfolders are already configured for sync. Many users don't understand the folder structure in Android (it's hidden most of the time) so we should help them avoid mistakes.

**Comment by uusijani** [comment]
This is still an issue.
