### ISSUE TITLE
Connection error (Verbindungsfehler), during upload. Upload not possible LG G6+ 

### ISSUE THREAD

**Issue by Y-Gry** [nextcloud/android#4826]
### Actual behaviour
- If I want to upload data from my LG G6+ to my nexloud, a connection error occurs.
Uploading with a Samsung S10 is possible.
Downloading is possible on both devices.

### Expected behaviour
- uploading of any kind of data
 
### Steps to reproduce
1. Try to upload for example a picture

### Environment data
Android version: 8.0.0

Device model: LG G6+ (LGUS997U)

Stock or customized system:

Nextcloud app version: 3.9.0 RC1

Nextcloud server version: 16.0.5.1

**Comment by Y-Gry** [comment]
Update: It is possible to upload files now. But only if the file size is quite small. For example less than 1 MB.

**Comment by AndyScherzinger** [comment]
@Y-Gry than your server is misconfigured (educated guess). The client does chunked uploads, si the server-side gets 1MB (or 10MB on wifi) chunks of the file. If the server has config issues than this fails (for different reason, I am not an expert on this).

**Comment by Y-Gry** [comment]
I don't think that this could be the reason. Because from my laptop I can upload everything, it doesn't matter how large the file is. The same behavior

**Comment by AndyScherzinger** [comment]
> I don't think that this could be the reason. Because from my laptop or another phone I can upload everything, it doesn't matter how large the file is.

@Y-Gry So reopen the issue? Is the other phone also Android-based? Laptop doesn't matter since that is a completely differnet client(implementation)

**Comment by Y-Gry** [comment]
Sorry my mistake I closed it accidently. 
Yes it is also a android based phone, as I described further a Samsung Galaxy S10.

**Comment by Y-Gry** [comment]
Issue isn't solved until now.

**Comment by tobiasKaminsky** [comment]
What kind of error do you get?

**Comment by jokester** [comment]
I'm experiencing a similar issue: Android client fails to upload larger files (roughly >=4MB) with "Connection error", while smaller files and PC clients works normally.

My server configurations (from inside out):

1. Nextcloud server: `nextcloud:16-fpm-alpine`  from dockerhub
2. nginx v1.16: similar to [manual](https://docs.nextcloud.com/server/16/admin_manual/installation/nginx.html) but http only
3. outmost nginx v1.16: listening on `public-ip:443`, configured like [this gist](https://gist.github.com/jokester/e5ba10aa1e76052f888140ee4886619c)

**Comment by tobiasKaminsky** [comment]
Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

**Comment by Y-Gry** [comment]
Fixed since version 3.11.0

Only the upload of many files at the same time can cause problems, as described in Issue #5911 and #5891
