### ISSUE TITLE
Disable 'Shared' until Php-fpm bug is resolved

### ISSUE THREAD

**Issue by pilsnerbeer** [nextcloud/android#4830]
I suggest that until the bug in the app which immediately spikes CPU usage to 100% indefinitely is temporarily mitigated by disabling "shared" in the navigation drawer. 

I have to be careful not to touch it and explain anyone who's using it on my server not to use it either. This may be problematic in larger teams. AFAIK the only way out is to kill the php-fpm process manually.

**Comment by ezaquarii** [comment]
IMO this hotfix belongs to the server where or should be possible to disable the offending API.

Maybe there is a way to do it by applying a simple patch on already deployed server?

What about iOS client? Is it also causing the trouble?

**Comment by pilsnerbeer** [comment]
Sorry, I don't have info on the iOS client. And while it is possible that the fault must be fixed on the server, the trigger mechanism lays in the client itself..

**Comment by AndyScherzinger** [comment]
I might be wrong here but isn't fpm an optional thing so for people not running fpm it would just kill the feature for no reason?

**Comment by pilsnerbeer** [comment]
Oh I think you are right. I was using the snap package so I didn't realize that. In that case I agree with you here.
