### ISSUE TITLE
App v3.9.0 crashes when trying to view "Details" of *.md files

### ISSUE THREAD

**Issue by roechr** [nextcloud/android#4836]
### Actual behaviour
- App crashes when trying to view "Details" of *.md files.

### Expected behaviour
- A new view with the well-known details should be shown.
 
### Steps to reproduce
1. Open Android App version 3.9.0
2. Go into the "Notes" folder
3. Tap on a *.md file so that it gets displayed
4. Tap on the 3-dot-kontext-menu in the upper right corner and choose "Details"
5. ==> CRASH!

### Environment data
Android version: 6.0.1

Device model: Motorola G3

Stock or customized system: stock

Nextcloud app version: 3.9.0

Nextcloud server version: 16.0.4.1 (owncube.com)

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 
'android.content.res.Resources android.content.Context.getResources()' 
on a null object reference at 
com.owncloud.android.utils.ThemeUtils.primaryColor(ThemeUtils.java:139) at 
com.owncloud.android.utils.ThemeUtils.primaryColor(ThemeUtils.java:125) at 
com.owncloud.android.ui.preview.PreviewTextFragment.getRenderedMarkdownText(PreviewTextFragment.java:284) at 
com.owncloud.android.ui.preview.PreviewTextFragment.setText(PreviewTextFragment.java:562) at 
com.owncloud.android.ui.preview.PreviewTextFragment.lambda$performSearch$0$PreviewTextFragment(PreviewTextFragment.java:270) at com.owncloud.android.ui.preview.-$$Lambda$PreviewTextFragment$8cnNMZfHrJC_BSC1jdHMw1eFOds.run(lambda) at android.os.Handler.handleCallback(Handler.java:746) at 
android.os.Handler.dispatchMessage(Handler.java:95) at android.os.Looper.loop(Looper.java:148) at 
android.app.ActivityThread.main(ActivityThread.java:5443) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) at 
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

************ APP INFORMATION ************
ID: com.nextcloud.client 
Version: 30090090 
Build flavor: generic

************ DEVICE INFORMATION ************ 
Brand: motorola 
Device: osprey_u2 
Model: MotoG3 
Id: MPIS24.107-55-2-17 
Product: osprey_reteu_2gb

************ FIRMWARE ************ 
SDK: 23 
Release: 6.0.1 
Incremental: 19
```

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky can you take a look into this (I don't have the time atm). 🙏

**Comment by roechr** [comment]
The problem can be reproduced with "Nextcloud Dev" App Version 20191121, too.

**Comment by roechr** [comment]
@AndyScherzinger @tobiasKaminsky The Problem is still present even in App Version 3.9.2 :-(

**Comment by AndyScherzinger** [comment]
@roechr does this happen for any other previewable file (like .txt)?

**Comment by roechr** [comment]
Well, it seems to depend on whether there is actual markup syntax in the file. With a file including format sequences, it does not matter if the extension is .md or .txt.
On the other hand side, a pretty normal textfile without format sequences behalves correct, independent of the file extension.

**Comment by AndyScherzinger** [comment]
looping in @tobiasKaminsky as discussed

**Comment by tobiasKaminsky** [comment]
Can you try this on 3.10 RC2? 
I could reproduce this on 3.9, but not with any later version.

**Comment by roechr** [comment]
Hi @tobiasKaminsky , 
in 3.10 RC2 and RC3 the Problem seems to be fixed ;-)

**Comment by AndyScherzinger** [comment]
Thanks for the feedback @roechr ❤️ then I'll close it with target 3.10
