### ISSUE TITLE
Automatic upload dont work

### ISSUE THREAD

**Issue by chichin79** [nextcloud/android#484]
### Actual behaviour
When taking a photo the phone starts to upload the picture but fails between 20-60%
Manual upload works

### Expected behaviour
The picture should uploud to my nextcloud automaticly 

### Steps to reproduce
1. Take picture with phone
2. Wait for the upload to begin
3. It fails

### Environment data
Android version:

6.0.1

Device model: 

Sony Z3 compact

Stock or customized system:

Stock

Nextcloud app version:

1.4.0

Nextcloud server version:

11.0

#### Web server error log
[Thu Dec 29 06:57:01.785821 2016] [mpm_prefork:notice] [pid 24989] AH00163: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g configured -- resuming normal operations
[Thu Dec 29 06:57:01.785846 2016] [core:notice] [pid 24989] AH00094: Command line: '/usr/sbin/apache2'
Insert your webserver log here

Access.log empty

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here

cat /var/log/nextcloud.log (empty)

**Comment by mario** [comment]
Please try the newest beta and revert to us with results.

https://github.com/nextcloud/android/raw/beta/apks/latest.apk

**Comment by chichin79** [comment]
Hello Mario, thanks, the beta version works with autoupload om Huawei mate
9 pro😀

Regards

Stefan

Den 8 feb. 2017 4:33 em skrev "Mario Đanić" <notifications@github.com>:

**Comment by mario** [comment]
Thanks for testing ;)
