### ISSUE TITLE
Screenshots' text too long

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#4840]
![image](https://user-images.githubusercontent.com/5836855/69030415-d8e92c80-09d7-11ea-9bba-eff0370ac63c.png)

@jancborchardt as you can see, also the 3rd one is too long.
For last one you suggested:
Titel: "Calendar & Contacts"
Subtitle: "Sync with DAVx5"

**Comment by jancborchardt** [comment]
Suggestion for 1st subline:
> Self-hosted productivity

Suggestion for 3rd heading
> Activity, shares, …
