### ISSUE TITLE
Is it needed to load the Drawer for each Activity ?

### ISSUE THREAD

**Issue by Shagequi** [nextcloud/android#4844]
Hi,

All is in the title.
The Drawer takes a certain time to load in each Activity (it musts load the layouts, invalidate current instance,  re-filter each item in the menu, etc.) and it takes a certain time to do this. 

My suggestion : Remove the Drawer from "one level" activites, (like in settings : where we just need to add an arrow to return to previous activity). 

So, replace the Drawer by an arrow for **at least**  :
- Activities ("logs")
- Pictures 
- Notifications
- Auto upload
- Uploads
- Community

(The list above is, where I think we could remove the drawer withouth forcing the user to click many times on top-left arrow to go back more than 2 times).

What do you think about it ?

**Comment by AndyScherzinger** [comment]
Cc @jancborchardt @tobiasKaminsky from a navigation point of view the drawer needs to stay since 8n the mentioned cases you aren't navigating down/deeper so the up navigation (back arrow) wouldn't be right and we should rather check if there are things that can be speed up.

**Comment by tobiasKaminsky** [comment]
I also think we should keep the drawer in the above activities.
However, I recall that many many apps now have only one activity, and use instead fragments.

If we would use fragments, then we would not have to recreate drawer.
I am sure this brings other downsides, which we should discuss / think of carefully.

**Comment by jancborchardt** [comment]
I actually would go the other way and say that it should be consistent in there _always_ being the drawer and the hamburger menu icon (instead of sometimes the back button to open the drawer).

Would this be bad performance-wise or for other reasons?

**Comment by Shagequi** [comment]
@jancborchardt Normally this would not be a problem, but in the case of this app, for each "Activity", we need to re-instantiate the Drawer (which takes a certain time to load).

If we used fragments (kinda interface parts) within the same Activity (with always the same Drawer), it should be better for performances (but this app is not fragment-oriented). 

And I don't really agree with a hamburger "everywhere", here is a discussion about this idea: https://ux.stackexchange.com/questions/82795/android-navigation-drawer-everywhere-drawbacks, I think we have to keep it on important and "multi level" elements (where you may go deeper to navigate) but we could remove it on "one level" activities (settings are a good example).

**Comment by AndyScherzinger** [comment]
Looking @ https://material.io/design/navigation/understanding-navigation.html most of today's activities reachable via the drawer menu are to be consideren top-level screens (so should rather have the hamburger/drawer) while navigating into deeper levels of one activity would have the up-navigation and no drawer.

I strongly disagreee with the refered page since this would mean when going from one "one level" activity to another the user will always have to navigate "up" as-in to the file list (or rather the last opened activity that triggered the navigation to the actual screen). So I find this rather unconvinient and inconsistent from a user perspective. And also like @Shagequi mentioned the up-navihation "hack" would be to solve a performance issue, which shouldn't be a reason for changing the general navigational behavior of the whole app.

**Comment by jancborchardt** [comment]
So here’s the issue going navigationless/drawerless in many views, which at the moment can only be seen using the "Settings" entry:
**It would always take 2 steps to reach the navigation, and it’s inconsistent.**

Meaning that e.g. uploads or activities look like the same top level entries as "All files" and "On device" but they are different in that you have to go back with the back arrow, which will get you to the last "main view" you were at (whatever these "main views" are, which will be confusing in itself already) and only _then_ you can reach the menu icon.

Am I missing something here?

**Comment by Shagequi** [comment]
You're not missing anything 😄 
My proposal was mainly performance-oriented. To load the Drawer each time create some "bugs" (sometimes the hovered/selected item is wrong or not display, the drawer is sometimes laggy).
I think UX is not only composed of the ease and intuitiveness of the interfaces, but also of a certain fluidity. 

So, the idea would be to replace voluntary duplicated Activities by Fragments, and use "Main Activities" (one for file exploration with different fragments for each case, one for settings, etc.) in order to "uniquify" some processes (like drawer loading)

But the change process could be long...

**Comment by Shagequi** [comment]
I close this issue, we could plan to use the fragments in a major version.
