### ISSUE TITLE
The "Shared" item in Drawer (Shared Search Event) doesn't work ?

### ISSUE THREAD

**Issue by Shagequi** [nextcloud/android#4845]
Hi,

The Shared Search Event (accessible from Drawer) doesn't seem to work on a complete NextCloud package

**App : NextCloud 3.9.0**
**Server : NextCloud 17.0.1 - 17.0.1.1**

The error returned on server is : 
```
Error | PHP | Undefined offset: 0 at [...]/drive/3rdparty/icewind/searchdav/src/XML/Operator.php#71 |  
```
(I didn't change server configuration, and used default files provided with NextCloud)

Could you try to reproduce ?

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky can you have a look at this? :)

**Comment by szaimen** [comment]
It isn't stale!

**Comment by Shagequi** [comment]
up

**Comment by tobiasKaminsky** [comment]
@icewind1991 do you have an idea what the problem might be?

**Comment by icewind1991** [comment]
what is the search request being sent?

**Comment by Shagequi** [comment]
@icewind1991 It's visibly not due to the server, the app doesn't seem to send data back to the server (because the search type is no longer handled/routed), we're investigating with @tobiasKaminsky

**Comment by Shagequi** [comment]
Due to unlink of SHARED_SEARCH in android-library

**Comment by tobiasKaminsky** [comment]
Plan is to have all types shown in "shared" view:
- incoming shares (other users shared with me)
- outgoing shares (I shared files/folders with other users)
- shared via link
- remote shares


http://localhost/nc/ocs/v1.php/apps/files_sharing/api/v1/shares?format=json&shared_with_me=false&include_tags=true
http://localhost/nc/ocs/v1.php/apps/files_sharing/api/v1/remote_shares?format=json&include_tags=true
http://localhost/nc/ocs/v1.php/apps/files_sharing/api/v1/shares?format=json&shared_with_me=true&include_tags=true

I will combine this in library so that the result is a big list of shares, which then can be shown in Files app.

**Comment by Shagequi** [comment]
@tobiasKaminsky Will the Activity contains removed shares like in web app (with a specific symbol/styling) ?

**Comment by tobiasKaminsky** [comment]
@Shagequi this is still to be discussed.
As of NC18, a quick win was to show it in side bar.
But goal is to have it on top of file list, so that user can immediately react on this.
There will be a general issue on how to do this, which also targets mobile integration.
I will then link it here.

**Comment by Shagequi** [comment]
@tobiasKaminsky Which point has to be discussed ? 
The presence of "removed shares" ? Or all the shares and the way to display them to the user in Android app ?

**Comment by tobiasKaminsky** [comment]
Ah, I was talking about "pending shares".

Removed shares should be shown in the regular "share" list, but with a restore button.

**Comment by Shagequi** [comment]
Okay perfect :D 
And do you have some news about the library issue ?

**Comment by tobiasKaminsky** [comment]
Planned for this week, hopefully.

**Comment by tobiasKaminsky** [comment]
Regarding "pending shares": https://github.com/nextcloud/server/issues/2192

**Comment by tobiasKaminsky** [comment]
So, plan is, according to @jancborchardt and me ;-) :
In "shared" pane:
- "Pending": sort by incoming date, most recent first
- "Shares": (all share, "my" shares, shares to me, shares via link, via mail, etc) sort by last modified, most recent first
- "Deleted": sorted by deletion date, most recent first

--> I will create for each three of them an RemoteOperation in lib.

**Comment by tobiasKaminsky** [comment]
As a quick win #5300, this will re-enable the old/current state, and shows only "shares".
