### ISSUE TITLE
Perpetual loader in pictures/on device/etc.

### ISSUE THREAD

**Issue by Shagequi** [nextcloud/android#4846]
Hi,

![Screenshot_20191118-120531_Nextcloud](https://user-images.githubusercontent.com/7050479/69047653-fc25d300-09fb-11ea-9941-c63cadccafb2.jpg)

The loader on the bottom of the Activity doesn't stop (although all the files have loaded). 
Is this Loader needed ? given that there is a "synchronous" Loader during the creation of this activity ? 

Could you try to reproduce ?

Thanks :)

**Android app version : 3.9.0 stable (Nextcloud)**
**Server version : 17.0.1 - 17.0.1.1 (Nextcloud)**

**Comment by AndyScherzinger** [comment]
Cc @tobiasKaminsky this shouldn't happen, haven't had this issue but I have 2ay more than 95 images (guessing this is the photos view)

**Comment by Shagequi** [comment]
This bug seems to be present in pictures, favorites, "on device" and every specific file list.
The presence of this loader is variable (not always here)

**Comment by Shagequi** [comment]
up

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky can you check this one?

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky can you check this one?

**Comment by tobiasKaminsky** [comment]
When is this happening?
Are these 8 images the only images on the account?
