### ISSUE TITLE
Properties of a file not functional in preview mode

### ISSUE THREAD

**Issue by Shagequi** [nextcloud/android#4847]
Hi,

The properties of a file are clickable but not functional during the preview.
It concerns essentially pictures (videos are functional, txt/docs too): 

![Screenshot_20191118-121132_Nextcloud](https://user-images.githubusercontent.com/7050479/69049185-950a1d80-09ff-11ea-8153-6d40d80329ea.jpg)
![Screenshot_20191118-121139_Nextcloud](https://user-images.githubusercontent.com/7050479/69049186-950a1d80-09ff-11ea-880a-70922e5fe5ea.jpg)

Version : 3.9.0

**Comment by AndyScherzinger** [comment]
Fancy providing a fix @Shagequi?

cc @tobiasKaminsky

**Comment by Shagequi** [comment]
Yep, working on it :)

**Comment by AndyScherzinger** [comment]
> Ps: @Shagequi is my colleagues :)

Ah, good to know, thanks for the heads up 🙏

**Comment by AndyScherzinger** [comment]
Code change related to #843 is ##881
