### ISSUE TITLE
Folder size not refreshed after file moving

### ISSUE THREAD

**Issue by Shagequi** [nextcloud/android#4851]
Hi,

When I create a folder, move a file in it and go back to the main activity (where the folder has been initialy created), the folder size is not refreshed (although the file is well inside).

So, I think we could refresh the "folder" (file) onResume by refreshing only the folder during the `onResume`.

Steps : 
1) Create a folder where you want, name it like you want
2) Move a file in the created folder
3) Return where you were during the folder creation (so, go back through one level)
4) You can see the folder size at 0.0MB (despite the file in it)

**Version : 3.9.0 for Android app (NextCloud)**

**Comment by AndyScherzinger** [comment]
Sounds right to me, cc @tobiasKaminsky for feedback

**Comment by AndyScherzinger** [comment]
fixed via #4898
