### ISSUE TITLE
Files list doesn't refresh after file restore

### ISSUE THREAD

**Issue by Shagequi** [nextcloud/android#4852]
Hi,

When you restore a file from "deleted files" (the trashbin), and return in "all files" Activity, the restored folder/file is not directly displayed, because the list is not refreshed after restore operation.

So, we need to manually reload the list. Is it a wanted behaviour or is it really a bug ?

Thanks :)

App Version : 3.9.0 , all devices, Nextcloud
Server Version : 17.0.1 - 17.0.1.1 (Nextcloud)

**Comment by AndyScherzinger** [comment]
Cc @tobiasKaminsky AFAIK a bug since the list should get a different etag for the folder from the server and refresh the list.

**Comment by Shagequi** [comment]
So, it could be relative to this issue too : https://github.com/nextcloud/android/issues/4851 ?

**Comment by AndyScherzinger** [comment]
Maybe... it might also be related to `onResume` or something like that

**Comment by AndyScherzinger** [comment]
fixed via #4898
