### ISSUE TITLE
Auto upload: enabled icon not visible on white theming

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#4855]
- have white theming enabled
- enable one auto upload folder
- do not see icon any longer

![2019-11-19-081049](https://user-images.githubusercontent.com/5836855/69124438-2d59de00-0aa4-11ea-99a1-de862530f075.png)

**Comment by AndyScherzinger** [comment]
Probably the same for dark color and dark theme activated... 😞
