### ISSUE TITLE
Login to Android App using TFA

### ISSUE THREAD

**Issue by ptman** [nextcloud/android#4856]
### Actual behaviour
With old login form login doesn't complete and with new I get an embedded browser view of nextcloud instead of the actual app. If I remove TFA I can login normally in the android app.

### Expected behaviour
Logged in to the app so that I can e.g. setup automatic upload that isn't available on the web
 
### Steps to reproduce
1. Enable Two-Factor Auth
2. Try to login

### Environment data
Android version: 9 (security path 2019-11-01)

Device model: Nokia 6.1

Stock or customized system: Stock

Nextcloud app version: 3.9.0

Nextcloud server version: 17.0.1

**Comment by ptman** [comment]
The QR code can be used, but it would be nice not to need that

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky I thought you can simply use 2FA with the weblogin
