### ISSUE TITLE
Cannot set default app to open file with

### ISSUE THREAD

**Issue by derekblankmccoy** [nextcloud/android#4857]
### Actual behaviour
When I try to open a file (pdf in this instance), I get asked what app to open it with.

### Expected behaviour
- The "Just Once" and "Always" option should be available.
 
### Steps to reproduce
1. Make sure you have at least 2 pdf viewer apps available
2. Upload a pdf to Nextcloud
3. Nextcloud will ask which pdf viewer to use with no option to set one as default

![image](https://user-images.githubusercontent.com/11743619/69151067-d79c2a80-0ad1-11ea-894a-6249969bb2ab.png)

### Environment data
Android version: 8, 9

Device model: Galaxy S10e, Galaxy A5 and Huawei P10

Stock or customized system: Stock

Nextcloud app version: 3.8 and 3.9

Nextcloud server version: 15.0.7

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky didn't you fix this for 3.9 (I think)?

**Comment by AndyScherzinger** [comment]
My mistake @tobiasKaminsky - fix is #4746 to be shipped with 3.10
