### ISSUE TITLE
Drawer is swipeable from the left on image/picture preview

### ISSUE THREAD

**Issue by Shagequi** [nextcloud/android#4864]
Hi,

The Drawer is swipeable from the left when we consult a picture. Given the full screen mode, the Drawer is cropped and not really useful. 

![Screenshot_20191120-153900_Nextcloud](https://user-images.githubusercontent.com/7050479/69248611-d8ee5580-0bac-11ea-8481-1ae9f0d5a28e.jpg)

Is it needed ?

App version : 3.9.0

**Comment by AndyScherzinger** [comment]
Nope, not needed. The issue here (just a guess, haven't looked at the code) is that the activity inherits the `DrawerActivity` which might well be because of the Tablet behavior (where this would just be on the left (file list, etc.) Not sure though.

cc @tobiasKaminsky

**Comment by Shagequi** [comment]
Normally, this block : 
```
        mFullScreenAnchorView.setOnSystemUiVisibilityChangeListener
                (flags -> {
                    boolean visible = (flags & View.SYSTEM_UI_FLAG_HIDE_NAVIGATION) == 0;
                    if (visible) {
                        actionBar.show();
                        setDrawerLockMode(DrawerLayout.LOCK_MODE_UNLOCKED);
                    } else {
                        actionBar.hide();
                        setDrawerLockMode(DrawerLayout.LOCK_MODE_LOCKED_CLOSED);
                    }
                });
``` 
`com/owncloud/android/ui/preview/PreviewImageActivity.java:121`

shouldn't allow the Drawer in "visible mode". So we may remove this block and replace by only `setDrawerLockMode(DrawerLayout.LOCK_MODE_LOCKED_CLOSED);` to disallow Drawer swiping.

**Comment by AndyScherzinger** [comment]
Worth a try I guess 👍

**Comment by Shagequi** [comment]
Hi @AndyScherzinger  :)

My fix works for pictures, but videos are concerned too (the Drawer is swipeable).
Do I need to fix for just pictures or videos too ?

**Comment by tobiasKaminsky** [comment]
Video is in PreviewVideoActivity.

**Comment by AndyScherzinger** [comment]
plus there is also the text preview activity

**Comment by Shagequi** [comment]
up

**Comment by Shagequi** [comment]
Can't understand why... the videos preview activity can't lock the Drawer.

**Comment by mario** [comment]
@Shagequi are you sure you are actually loading the Videos Preview activity? I really don't think that's used anymore, what you see when you click on a video is PreviewMediaFragment. See line 2343 in FileDisplayActivity in your branch. :) So you might want to handle the drawer locking/unlocking in the fragment lifecycle methods.

**Comment by Shagequi** [comment]
I'll work today on a fix for video preview activity/fragment (in order to hide the Drawer) @AndyScherzinger

**Comment by Shagequi** [comment]
Issue created
