### ISSUE TITLE
Pasteboard Site 

### ISSUE THREAD

**Issue by ralfi** [nextcloud/android#4868]
### Actual behaviour
- Pasteboard App in Menu

### Expected behaviour
- really ?
 
### Environment data
Android version: 9
Device model:  SG9
Stock or customized system: Orginal Samsung
Nextcloud app version: Dev 20191120
Nextcloud server version: 17.0.1

![Screenshot_20191121-134858_Nextcloud dev](https://user-images.githubusercontent.com/294423/69339943-ba4c9500-0c66-11ea-8b2b-7049ffe5bc6f.jpg)

I have enabled this in nc settings - externla sites for all devices. It appears how expected in the android app but do not work. Its only a question: could these work in this way?

**Comment by tobiasKaminsky** [comment]
It should show the configured external site in a webview.
Can you give us a screenshot how you configured it on server side?

**Comment by ralfi** [comment]
![grafik](https://user-images.githubusercontent.com/294423/69341220-6ee7b600-0c69-11ea-8cb2-a5d8def50efb.png)

Hi Tobias,
as you can see... But it do not work. Could this work?

**Comment by ralfi** [comment]
If i do embedding sites from my Server like pihole stats with apache reverse proxy this works well.

**Comment by tobiasKaminsky** [comment]
Looks good so far, same as I have it.
What is happening when you click on the entry?
Is it closing drawer? Or is drawer remaining opened?

**Comment by tobiasKaminsky** [comment]
> If i do embedding sites from my Server like pihole stats with apache reverse proxy this works well.

Hm. it should also work with external sites…

**Comment by ralfi** [comment]
Let me have a deeper look with enabling again and posting logfiles. At this moment nothing happens if i tap on the screen on my SG9.

**Comment by ralfi** [comment]
Browser ...

![Bildschirmfoto vom 2019-11-21 15-40-05](https://user-images.githubusercontent.com/294423/69347932-a0ff1500-0c75-11ea-959c-c9ea9e00dc72.png)

and Phone
![grafik](https://user-images.githubusercontent.com/294423/69348007-be33e380-0c75-11ea-9023-84c9990c6103.png)

Logs do not have useful entries. Seems to me related with other settings.

**Comment by ralfi** [comment]
Browser works, Phone not.

**Comment by tobiasKaminsky** [comment]
For my emulator it is working with the same settings as you posted above:
![2019-11-22-074346](https://user-images.githubusercontent.com/5836855/69403822-dea68100-0cfb-11ea-9264-390762829f8a.png) ![2019-11-22-074339](https://user-images.githubusercontent.com/5836855/69403823-dea68100-0cfb-11ea-80b8-d21ed135cf96.png)

I am not sure why your device is blocking it…

**Comment by ralfi** [comment]
Yeah on my emulator this works also. Seems to me related to device security settings or something else. Does it work on your device? I will try this on my SGTab T810 with LineageOS...

**Comment by ralfi** [comment]
Do not work on both Android Devices, only in emulator. Seems to be security related like CORS or related

**Comment by tobiasKaminsky** [comment]
On my OnePlus6 with LineageOS I can also add an external site, which is not at the some domain and it works.

**Comment by ralfi** [comment]
Yes, but pasteboard.co not at me
