### ISSUE TITLE
Add Chris to review list

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#4899]
Just in case @ezaquarii is fine with it of course: @tobiasKaminsky could you add @ezaquarii to the review list as in: https://www.kaminsky.me/nc-dev/reviews.php?id=ezaquarii

@ezaquarii Tobias is running a cron/bot/dunno which lists all PRs that haven't been reviewed by a person, see https://www.kaminsky.me/nc-dev/reviews.php?id=AndyScherzinger for example and it also shows which PRs have conflicts with the base branch. In case this is helpful to you I'd say @tobiasKaminsky could add you to the list :)

**Comment by tobiasKaminsky** [comment]
Done

**Comment by AndyScherzinger** [comment]
@ezaquarii hope it helps: https://www.kaminsky.me/nc-dev/reviews.php?id=ezaquarii 😃

**Comment by ezaquarii** [comment]
This looks good, I'll be visiting this list regularly. Thank you.

**Comment by AndyScherzinger** [comment]
You're very welcome and as always, no pressure! This is just to have a better overview which PR somebody hasn't had a look at (doesn't mean you always need to review all PRs), just declutters GHs notification page a bit to only see the top things that need reviewer attention :)
