### ISSUE TITLE
Android app: Failed to download a file from server

### ISSUE THREAD

**Issue by lambis7** [nextcloud/android#4917]
### Actual behaviour
- Whe i try to download a file from server from the android app (v.3.9.0) i get an error saying that the download of the file could not be completed.

### Expected behaviour
- The file should be downloaded
 
### Steps to reproduce
1. 
2. 
3. 

### Environment data
Android version: 9.1

Device model: Huawei P20

Stock or customized system: Stock

Nextcloud app version:3.9.0

Nextcloud server version:17.0.1

**Comment by Shagequi** [comment]
Hey, 

There is not really any information that could help to understand the problem, the best way is to transmit the file type, the file size, logs, screenshots of the error, etc.

Maybe your server is misconfigured, maybe you had connectivity issues, impossible to determinate until you give more informations.

Thank you in advance for your answer :)

**Comment by lambis7** [comment]
The file is an .xlsx file of 17KB, there is no log about that on the server (Settings-> Administartion-> Logging), and the screenshot of the error on the is that (It's on Greek but it says that the file failed to download):
![20191204_185727](https://user-images.githubusercontent.com/24440946/70163644-7f1b7e80-16c8-11ea-9969-b8a92453cf25.jpg)

**Comment by pholthau** [comment]
I do have the same thing (I guess this was ongoing since a while already but I never bothered too much). I cannot find anything related in the server's log. Same device, versions as follows:

Nextcloud app version:3.9.1
Nextcloud server version:17.0.1.1

How do I debug the Android app?

**Comment by lambis7** [comment]
Now i see an error at Server Logging (Settings-> Administartion-> Logging):
[PHP] Error: Undefined offset: 0 at /var/www/nextcloud/3rdparty/icewind/searchdav/src/XML/Operator.php#71

**Comment by pholthau** [comment]
My issue has been resolved by selecting a new storage path in the app settings.
I don't know how that got messed up, though. I am assuming it never worked correctly on that phone (Huawei P20) until I manually configured the path.
