### ISSUE TITLE
Welcome screen: no dark mode

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#4921]
![2019-12-03-074418](https://user-images.githubusercontent.com/5836855/70026759-c1e23700-15a0-11ea-92bd-e112c6cbecb5.png) ![2019-12-03-074406](https://user-images.githubusercontent.com/5836855/70026762-c4dd2780-15a0-11ea-9e1c-b6e587dcbd6a.png)

Do we want to have a dark mode here?

@AndyScherzinger 
@dan0xii

**Comment by AndyScherzinger** [comment]
I'd say no. This is a very specific and special themed screen (in contrast to the regular applicaiton screens), SO I wouldn't touch this.

**Comment by tobiasKaminsky** [comment]
Okay, totally fine with this.
