### ISSUE TITLE
Implement document (docx, odt) preview in app directly

### ISSUE THREAD

**Issue by Shagequi** [nextcloud/android#4927]
Hi,

I would like to know if you've already tried to implement a document preview directly in app. 
Today, when you open a document, it opens Word or OnlyOffice or any other doc editor/viewer. 

Is it a normal behaviour ? Have you ever thought about implementing in-app preview instead of out-app ?

Thank you for your answer

**Comment by JorisBodin** [comment]
On the iOS app this feature exists. But it's very easy, just open file with native webview. In Android it's not possible :(
Maybe use docx4j lib?

**Comment by AndyScherzinger** [comment]
May Tobias knows, for collabora it should work just fine for Libre Office files (at least)

**Comment by tobiasKaminsky** [comment]
We have integration with Collabora Online, which then also supports preview in file list.
It is also time/benefit tradeoff, as we do not have to do the work twice…

Some time ago I had a deep search to find a FOSS library that supports read/edit support for all office files, but I failed to find one.

**Comment by tobiasKaminsky** [comment]
> May Tobias knows, for collabora it should work just fine for Libre Office files (at least)

Collabora can also handle ms office files.

**Comment by JorisBodin** [comment]
I do not think editing is important.
Just a quick reading of the file, same ios app.

Same you, I don't find a open source lib. 
Just find docx4j, for convert office file to PDF and show it :)

**Comment by tobiasKaminsky** [comment]
> Just find docx4j, for convert office file to PDF and show it :)

:-D but then we are better with using Collabora, as we then do not have to download the entire file…

**Comment by jakobroehrl** [comment]
This is working in Android, I think we can close this issue.
