### ISSUE TITLE
Allow to select & send multiple files

### ISSUE THREAD

**Issue by kollix** [nextcloud/android#493]
### Actual behaviour
When I view a single image or play some other media file, I have a "send" action in the menu, which e.g. allows me to send the file via bluetooth, etc.
This send action however is not available when I select one or more files directly in the file view

### Expected behaviour
Have the "send" action available in file view with multi-selection
 
### Environment data
Android version: 4.4.2

Device model:  Samsung Galaxy S4 mini

Stock or customized system: stock

Nextcloud app version: 1.4.0

**Comment by joshtrichards** [comment]
Duplicate #677
