### ISSUE TITLE
Create new text document

### ISSUE THREAD

**Issue by mjanssens** [nextcloud/android#4930]
### Is your feature request related to a problem? Please describe.
Now that the Text app is official and supported, in terms of design consistency it would be justified to have an extra menu item "create new textdocument".

### Describe the solution you'd like
Similar as the web app, it would create a md file. I know that at this moment the nextcloud android app only allows viewing. But editing or creating a file and transferring to an md editor android app would be nice.

**Comment by tobiasKaminsky** [comment]
:-D
This is already in development: #4890 and #4915

**Comment by mjanssens** [comment]
Very nice!
