### ISSUE TITLE
Infinite loop with fingerprint

### ISSUE THREAD

**Issue by cochran008** [nextcloud/android#4944]
Hello I use a fingerprint to unlock. 

By the unlock code query, I end up in an endless loop. 

The fingerprint or the password is queried again and again.

What can I do? 

### Environment data
Android version: 8

Device model: Samsung s7

Stock or customized system: stock

Nextcloud app version: 3.9.1

Nextcloud server version: 16.0.5

**Comment by gk26** [comment]
Same here

**Comment by biserov** [comment]
Same problem after app update...
Again...

**Comment by anindyamaiti** [comment]
Changelog of the 3.9.1 update:
1. Bumped up all the version numbers.
2. Brought back the dreaded fingerprint looping bug, which will render your app completely useless!

I guess [beta testing](https://en.wikipedia.org/wiki/Software_testing#Beta_testing) is not a thing anymore.

LineageOS 14.1 on LG G6. Server 17.0.1

**Comment by tuedelue** [comment]
Same here - Oneplus 6, Android 9.

**Comment by tobiasKaminsky** [comment]
I recheck and will provide a fix soon.

**Comment by tobiasKaminsky** [comment]
I did this:
- installed 3.9.0 on an emulator
- enabled pin, then fingerprint
- unlocked app
- installed 3.9.1
- unlocked app

Even after rebooting it is working.

The fix we included should not lead to a loop, but I fear that it leads to ask for verification on every app start, and not (as it was previous) with a slight grace period of 5s.

**Comment by joekerna** [comment]
I can also confirm the issue on 3.9.1 on a Huawei P20, Android 9.

It was not there in the RC

**Comment by tobiasKaminsky** [comment]
@all can you test: https://cloud.nextcloud.com/s/NsPiMyQQFekzmDJ

This is signed with the same key as google play release, so it is safe to update.

**Comment by tuedelue** [comment]
The provided version works for me!

**Comment by joekerna** [comment]
Yes, that version is working

**Comment by tobiasKaminsky** [comment]
Strange, as I still fail to understand the reason.
Let us wait for another approval and then I release a hotfix 3.9.2 as soon as possible.

**Comment by tobiasKaminsky** [comment]
And … there it is… :-D
Thanks for testing.

**Comment by tobiasKaminsky** [comment]
3.9.2 released to gplay. It should be available within the next 30min.

**Comment by tobiasKaminsky** [comment]
A short update: it seems that Google takes a bit longer with releasing.
There is nothing I can do, but wait… :/

**Comment by darix** [comment]
btw: would it be possible to provide the releasenotes also in google play and not just here? or link to the release tag on github?

**Comment by tobiasKaminsky** [comment]
@darix I use fastlane and there I add changelogs. They should be uploaded.
I will have a look as fastlane recently changed something.

**Comment by darix** [comment]
the least few releases all say "the developer did not provide the information"

**Comment by tobiasKaminsky** [comment]
I do see this https://play.google.com/store/apps/details?id=com.nextcloud.client&hl=de

![image](https://user-images.githubusercontent.com/5836855/70249415-a895e200-177c-11ea-9a64-77dfb1e94fea.png)

(we only provide changelog in english)

**Comment by tobiasKaminsky** [comment]
3.9.2 is now available!

**Comment by cochran008** [comment]
Release 9.3.2 works for me.

Thanks for the fast fix!

**Comment by Animeshz** [comment]
@tobiasKaminsky issue still persist on OnePlus5 android 7.1.1 i can turn on the unlock option inside setting->google->account services-> search, assistant & voice->voice->voice match. But even if it is turned on there that doesn't show to be on inside google assistant settings->assistant devices->phone and it doesn't unlock . And if i turn that on i get infinite loop asking for lock pattern.
