### ISSUE TITLE
wish: preview instead of download for photos

### ISSUE THREAD

**Issue by joephein** [nextcloud/android#495]
It would be great if the android app can preview photo's instead of downloading them first. I do not want to download the full size 10 MP photo but just view and/or store a resized preview based on my device resolution. These previews ideally need to be available already to avoid creating them again and again. I guess this app could do that job: https://apps.nextcloud.com/apps/previewgenerator

**Comment by AndyScherzinger** [comment]
Hi @joephein,
Previews have already been implemented in the beta version available via f-droid :)

**Comment by joephein** [comment]
Perfect I confirm this is working well. The initial preview is of a lower quality but it seems a new preview is generated based on the device resolution in the background and is automatically available if you wait a while. There is an issue with photo's that are already downloaded. They do not display at all. Manually removing the files from the device solves this.

**Comment by AndyScherzinger** [comment]
cc @tobiasKaminsky since you implemented the preview functionality :)

**Comment by tobiasKaminsky** [comment]
#503
