### ISSUE TITLE
Not auto-uploading photos, endless spinner

### ISSUE THREAD

**Issue by MarcStoecker** [nextcloud/android#4957]
### Actual behaviour
- New photos taken don't get auto uploaded, no status/feedback
- "Photos" has an endless spinner at the bottom
- manual uploads work

![image](https://user-images.githubusercontent.com/1537988/70312410-e2fe8e00-1813-11ea-86ae-4c6635a18e68.png)

### Expected behaviour
- Auto-upload of photos
- Feedback to user on status, expecially on error/problem

### Steps to reproduce
1. Create a new Nextcloud instance
2. Install Nextcloud Android app (first ever on device)
3. Activate photo roll upload (w/ accept permissions)
4. Take a picture

### Environment data
- Android 9, November 2019 Patch
- Samsung Galaxy S10e
- Nextcloud app 3.9.2
- Permissions: camera, contacts, storage and notifications
- background data allowed, but connected to Wifi
- battery optimization deactivated for app

**Comment by MarcStoecker** [comment]
Could it be that the picture roll is getting scanned or such desprite old pictures not getting uploaded? I have quite a substancial amount of images on my phone ...

**Comment by AndyScherzinger** [comment]
Existing pictures prior to activating auto upload don't get uploaded. This is a feature the project is currently working on m

**Comment by MarcStoecker** [comment]
Ok, sorry for not mentioning. I did indeed take new photos to test.

**Comment by MarcStoecker** [comment]
I force closed (completely unloaded) the app (closing with the app switcher didn't actually unload it truly)  and reopened it, now the photos do get synced.

However, I still do have the "endless spinner" at the bottom, below the photos. Hope it doesn't mean too much.

**Comment by AndyScherzinger** [comment]
Old pictures don't get uploaded just yet, see #285 

the photos tab is a view of the images available on the server

**Comment by MarcStoecker** [comment]
What do you mean by "old pictures"? I installed the app, activated Auto-Upload and took a picture (several actually). None of them got synced until the app got restarted (force closed).

To me this looks like a bug that occured right when I activate the feature and expeced pictures taken *afterwards* to be synced (which is what the feature suggests).

Sorry if I am missing something here.

**Comment by AndyScherzinger** [comment]
> Sorry if I am missing something here.

Nope, your absolutely right. The pictures should get uploaded starting after 15 minutes (latest) while the auto upload also depends on the devices battery saving/optimization. So the app should be excluded from such "optimizations".

Else it isn't working for your device (right now). As for the spinner, that is related to the photos view which should show all images present on the server, this has already been reported via #4846

**Comment by MarcStoecker** [comment]
Great, thanks. So the spinner is something different. This means that after a restart of the app everything's working. Just a minor glitch, essentially. 🙃
