### ISSUE TITLE
Autoupload of images does not work when SD card is selected as the download destination of photos by camera app

### ISSUE THREAD

**Issue by elpraga** [nextcloud/android#496]
### Actual behaviour
Select SD card as your storage in your camera app. 
Photos don't get auto uploaded.

### Expected behaviour
Photos should get auto uploaded.
 
### Steps to reproduce
1. Select SD card as your storage in your camera app.
2. Select automatic upload in the NC android app
3. Take a photo with your camera app.

### Environment data
Android version:
6.0
Device model: 
Huawei Y6II
Stock or customized system:

Nextcloud app version:
1.4.0
Nextcloud server version:
NC 11.0.0
#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

**Comment by elpraga** [comment]
__Side note I forgot to mention:__ Autoupload works as expected on my device with a different camera app which has internal storage selected to save photos.

**Comment by AndyScherzinger** [comment]
Hi @elpraga
Can you get a log cat from the phone / Nextcloud client since the question is if choosing SD card leads to the camera app not sending a new picture broadcast (which our app is listening to).

**Comment by tobiasKaminsky** [comment]
@elpraga you mean "InstantUpload" as you are using Android 6?
"AutoUpload" is our new feature for Android 7.

**Comment by elpraga** [comment]
@tobiasKaminsky yes, I do indeed. Sorry for the mismatch. @AndyScherzinger how can I get what you ask me for from the 1.4.0? I apologize for my ignorance...

Happy new year to both of you!

**Comment by AndyScherzinger** [comment]
Hi @elpraga, 

you probably can't since the stable doesn't have logging enabled, just the beta has :( Else you would have to connect your device via USB + adb to Android Studio (dev environment) and there check the devices logging in the log cat console within Android studio. My guess is that the stock camera, when writing to an external-sd-card storage won't send a broadcast, but I am not sure.

**Comment by OlivierS1** [comment]
Same behavior with Nextcloud app 1.4.1 RC1.
Nextcloud data can be stored eiher on internal memory or external SD card, Autoupload will not take effect if Camera app is using external SD card as the primary storage media.
Restarting the phone and selectign Internal memory as storage media for the camera app will allow Autoupload to take place.

**Comment by tobiasKaminsky** [comment]
@OlivierS1 which device model do you have?

**Comment by OlivierS1** [comment]
@tobiasKaminsky:

Android version:
6.0
Device model:
LG-G3 LG-D852

Stock or customized system:
Stock

**Comment by elpraga** [comment]
It seems to be working now on my phone. I'm not sure what the issue was exactly, but my phone might have been killing NextCloud app in the background. 

In any case, I'm not able to reproduce the error. It's working now. 

I'll post updates if I have new info. 

I'll leave this issue open for @OlivierS1

**Comment by mario** [comment]
@OlivierS1 @elpraga is this working with the newest beta?

https://github.com/nextcloud/android/raw/beta/apks/latest.apk

**Comment by elpraga** [comment]
@mario Although I did not use the link you provided, I believe that I am using the same version, because I updated to the latest version using the app. Beta20170213 still creates the tmp file in the main storage and downloads fail. It is not working yet.

**Comment by mario** [comment]
@elpraga thanks. Gonna investigate right away mate :)

**Comment by elpraga** [comment]
Thanks for the swift answer and your help pal! :wink:

**Comment by mario** [comment]
I just tried this and it works :-/ Will be hard to debug...

**Comment by mario** [comment]
Can you please clarify "downloads fail"? What downloads? Do you mean uploads?

**Comment by elpraga** [comment]
Wow. 
Stupid question, do you have SDcard selected as the storage?

And where is the tmp file created? On the SD card or in the main storage?

How can I help to debug?

**Comment by mario** [comment]
Hehe, yes I do have SD card selected as the storage. Can you screenshot your storage settings? I'd have to check where the tmp file is created.

**Comment by elpraga** [comment]
No. I mean downloads. Uploads work fine for me, even automatic photo uploads.

The problem is when I try to download a file. The app creates a tmp file in the main storage (the official app doesn't, it creates the tmp file on the SD card). The file gets downloaded to the tmp folder correctly, but the app fails to copy it to its final destination, and an error stating download failed appears.

Did this help @mario ?

**Comment by mario** [comment]
Ok, so this is a wholeeee separate issue :D Can you open a new issue, and copy/paste the error logs if you have them? :)

**Comment by elpraga** [comment]
I'm so sorry! My bad! 

I have already opened an issue for it a month ago: [Beta20161224: files don't get downloaded properly when SD card storage is selected](https://github.com/nextcloud/android/issues/476), and you said you'd have a look at it.

As you mentioned my name, I thought were referring to that issue. 

I'm really sorry :angel:

**Comment by mario** [comment]
No worries, it's just complicated to track everything :D

**Comment by tobiasKaminsky** [comment]
@elpraga is it wroking now for you?

**Comment by elpraga** [comment]
Yes. It's working now. I have totally forgotten about this issue.

Closing.
