### ISSUE TITLE
Photos are not uploaded or synced

### ISSUE THREAD

**Issue by nicrame** [nextcloud/android#4964]
#4956 # Actual behaviour
App do not upload photos after installing and logging in. What is the point of having Nextcloud app, when it do not do it's main function? 

### Expected behaviour
Work as it should - upload photos from the folders i choosed. 
 
### Steps to reproduce
1. Install app and login. 
2. Select folders to upload. 
3. Nothing is happening. 

### Environment data
Android version: 10 on MIUI 11.
![IMG_20191207_100448](https://user-images.githubusercontent.com/5872054/70372394-9b910400-18de-11ea-9413-3a2650c13464.jpg)
Device model: Xiaomi Mi9

Stock or customized system: Official stable MIUI for EU. 

Nextcloud app version: 3.9.2

Nextcloud server version: 17 newest

#### Web server error log
```
No action from client is no logs. 
```

#### Nextcloud log (data/nextcloud.log)
```
Same
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
Please see #285 and #4788 respectively.

The app as of now doesn't upload existing images just photos/videos taken _after_ the setting has been activated.
