### ISSUE TITLE
Nextcloud removing files when connected to new Server with the same login.

### ISSUE THREAD

**Issue by floriplum** [nextcloud/android#4965]
### Actual behaviour
After reinstalling my Nextcloud Server with the same credentials and DNS name the nextcloud app deletet everything currently under the android/media/com.nextcloud.client/nextcloud/$USERNAME@$NEXTCLOUDHOSTNAME.

### Expected behaviour
Maybe ask or warn that everything will be deleted that was currently downloaded.
 
### Steps to reproduce
1. Connect to a Nextcloud Server with the android app
2. Download pictures from the server or upload them and tell the app to move the file to the Nextcloud folder.
3. Install a new Nextcloud Server with the same DNS name and create a User with the same credentials.

### Environment data
Android version: 9

Stock or customized system: LineageOS

Nextcloud app version: 3.9.0

Nextcloud server version: 11 on the old one and 17 on the new one

I think that i have a super rare case here and ofc i have backups of the missing data.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky while I agree with @floriplum 

> a super rare case

I still think that we should put out a warning like mentioned

> Maybe ask or warn that everything will be deleted that was currently downloaded.
