### ISSUE TITLE
More information about "thumbnail" in Activities

### ISSUE THREAD

**Issue by JorisBodin** [nextcloud/android#4970]
Hi :)

I noticed that the thumbnail were recovered with the "thumbnail" route EXCEPT in the view "Activities". In this view the "preview" route is called.
Is this intentional or a migration omission?

Thanks you :D

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky can you answer this?

**Comment by JorisBodin** [comment]
@AndyScherzinger My apologies, it's the back that turns this road around.

**Comment by tobiasKaminsky** [comment]
@JorisBodin if comes from server, then yes please.
