### ISSUE TITLE
White text in options menu for image preview

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#4976]
### Actual behaviour
- white text

### Expected behaviour
- text should be black (or white text on dark background in dark mode)
 
### Steps to reproduce
1.  open an image
2.  open option menu

Happens on latest master, dev version

@dan0xii do you have an idea where I have to look at?

**Comment by tobiasKaminsky** [comment]
(again setting a milestone as this is somehow a showstopper…)

**Comment by dan0xii** [comment]
Not off the top of my head but will have a look..

**Comment by tobiasKaminsky** [comment]
This happens only if android dark mode is set to light.
On dark mode it is as intended: grey text on dark grey background
