### ISSUE TITLE
Directories incorrectly shown as empty if they contain many elements

### ISSUE THREAD

**Issue by m1cm1c** [nextcloud/android#4978]
### Actual behaviour
When opening a directory with many elements, after some time of "Loading ...", the message "No files here" is displayed.

For example, this happens with my WhatsApp Images directory:

![](https://i.imgur.com/VkmWgUX.jpg)

As you can see, there should be plenty of files in there:

![](https://i.imgur.com/r9lRuwx.jpg)

### Expected behaviour
Either continue loading or display an error message stating that the contents cannot be displayed. Don't lead the user to think their data is gone!
 
### Steps to reproduce
1. Fill a directory with many files. In my case the described behavior started recently and I now have about 3500 files in that directory.
2. Open it in the app.

### Environment data
Android version: 9

Device model: OnePlus 6

Stock or customized system: Original OxygenOS 9.0.9

Nextcloud app version: 3.9.2

Nextcloud server version: 17

**Comment by m1cm1c** [comment]
The problem didn't magically go away.

**Comment by AndyScherzinger** [comment]
@m1cm1c what happens if you pull-down-to-refresh within that folder?

Also cc @tobiasKaminsky @ezaquarii

**Comment by m1cm1c** [comment]
I refreshed before, restarted my phone, and restarted the server without seeing a change. But now I wanted to confirm this again before stating so and the problem is actually magically gone. It even is gone on my second account on the phone (where I installed the Nextcloud app too) and in all of the directories where it happened.

**Comment by AndyScherzinger** [comment]
hmm, strange; might be related to initial fetching of the meta data from the server (can't say for sure). Thanks for the feedback. ❤️ 

Please feel free to re-open/report back in case the issue comes back.
