### ISSUE TITLE
OnlyOffice support in the app

### ISSUE THREAD

**Issue by UserXH726** [nextcloud/android#4980]
Hello,
Just a simple question (or feature request)
Is it planned to integrate onlyoffice in the app like collabora is?

**Comment by tobiasKaminsky** [comment]
Yes :-)
Though I cannot say when… :-)

**Comment by szaimen** [comment]
Now that Nextcloud Hub is released with built in Onlyoffice, I think, that the Onlyoffice integration is quite missing.

**Comment by e-alfred** [comment]
Onlyoffice editing is integrated into the Nextcloud Android app, but Onlyoffice removed the ability to edit files on mobile devices in their Open Source version, so only viewing files is possible.

@tobiasKaminsky Maybe you could implement an option to select either Onlyoffice or Collabora to edit supported documents from the three dots menu if both are installed on the server? Currently I can open up ODT in Collabora and DOCX in Onlyoffice having both set up in the server. In the web interface I can select either of them in supported documents.

**Comment by tobiasKaminsky** [comment]
Please see discussion here: 
https://help.nextcloud.com/t/onlyoffice-removed-web-mobile-editing-from-version-5-5-0-of-community-document-server/74360

**Comment by tobiasKaminsky** [comment]
> @tobiasKaminsky Maybe you could implement an option to select either Onlyoffice or Collabora to edit supported documents from the three dots menu if both are installed on the server? Currently I can open up ODT in Collabora and DOCX in Onlyoffice having both set up in the server. In the web interface I can select either of them in supported documents.

Let us track this in https://github.com/nextcloud/android/issues/5729

As this is about adding OO, I will close it (technically it is working… ;-) Rest is out of my control, and will hopefully be fixed)
