### ISSUE TITLE
OOM crash when browsing pictures.

### ISSUE THREAD

**Issue by StyXman** [nextcloud/android#4981]
My picture collection must be around 40k photos. I was swiping the images; I was just a few pictures in when it crashed.

**Comment by StyXman** [comment]
Sorry, I can't update further, my instance is down and can't bring it up until the end of next week.

**Comment by tobiasKaminsky** [comment]
What kind of device do you have?
Swiping through images should at max take 3 images into ram, and those cannot be that big that there is a OOM.
Can you provide us with a logcat?

**Comment by StyXman** [comment]
> What kind of device do you have?

FairPhone 2, 3GiB of RAM.

> Swiping through images should at max take 3 images into ram, and those cannot be that big that there is a OOM.

I agree

> Can you provide us with a logcat?

Not now, no; my home server crashed, and it will be another 10 days before I can get my hands on it. Should I close this while I try to reproduce?

**Comment by tobiasKaminsky** [comment]
How big are the images?

**Comment by tobiasKaminsky** [comment]
Let us track it in #5479
