### ISSUE TITLE
Symbol error

### ISSUE THREAD

**Issue by hao41815w** [nextcloud/android#4987]
error: cannot find symbol class RequestEntity
private NameValuePair[] convertMapToNVP(Map<String, String> map) {
^
....
I can't build Gradle this project now.
I have been built this project before.
But now it isn't working.
Can you explain this or can you update this project?
Thanks

**Comment by ezaquarii** [comment]
@hao41815w It looks like apache http client is not linkable. Since it is deprecated, I suspect you were caught in a middle of a breaking migration.

@tobiasKaminsky Another library upgrade?

**Comment by AndyScherzinger** [comment]
be fixed via #4900

**Comment by hao41815w** [comment]
So how can I build this app on my PC?
Please help me...

**Comment by AndyScherzinger** [comment]
@hao41815w please wait for #4900 to be merged (within today, the issue will auto close then)

**Comment by hao41815w** [comment]
So can I build this app within 24 hours?

**Comment by AndyScherzinger** [comment]
As soon as this issue closes you can pull the master again and it will build and yes that is likely within less than 24 hours

**Comment by hao41815w** [comment]
Ok, thanks 
I will wait for your good news.
And I will rebuild this app again.(within 24 hours)

**Comment by AndyScherzinger** [comment]
@hao41815w master should work again now

**Comment by hao41815w** [comment]
"A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptExecution"

This is my building issue.
I can't build this app yet.

**Comment by AndyScherzinger** [comment]
see https://drone.nextcloud.com/nextcloud/android/11949/1/2
master builds just fine, so you rather seem to have a local issue on your maschine (now)
