### ISSUE TITLE
Weird state management in FirstRunActivity

### ISSUE THREAD

**Issue by Kilian-Perisset** [nextcloud/android#4993]
Hi,

On the first start (without being connected), The FirstRunActivity is launched after a few Intents. 
And, when you access this Activity, and lock your phone, and reopen it, you should go back to this "FirstRunActivity", but instead you're redirected directly to login and a thread crashes.

So why don't we redirect immediatly to FirstRunActivity through MainApp instead of passing from FileDisplayActivity, and why we don't relaunch this activity onRestart ? And why is it a MediaFolder detection before ANY connection (which fails and kill the thread)? : 

``` 
2019-12-12 16:47:53.267 16477-25164/XXXXXXXXX E/JobExecutor: Crashed job{id=27, finished=true, result=FAILURE, canceled=false, periodic=true, class=MediaFoldersDetectionJob, tag=MediaFoldersDetectionJob}
    java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media from pid=16477, uid=10468 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
        at android.os.Parcel.createException(Parcel [...]
``` 

So, what is the "wanted" behaviour for the first launch ? And why do we pass through FileDisplayActivity without being connected ?

V. 3.9.2

**Comment by AndyScherzinger** [comment]
Maybe you can shed some light on this @tobiasKaminsky?

**Comment by tobiasKaminsky** [comment]
>  The FirstRunActivity is launched after a few Intents.
> And, when you access this Activity, and lock your phone, and reopen it, you should go back to this "FirstRunActivity", but instead you're redirected directly to login and a thread crashes.

Indeed. I guess I never tried this…Thanks for this findind!



> So why don't we redirect immediatly to FirstRunActivity through MainApp instead of passing from FileDisplayActivity,

Good question, I do not remember why I(?) did this. But your idea sounds better.

>  and why we don't relaunch this activity onRestart ?

I guess I just forgot about this case…




> And why is it a MediaFolder detection before ANY connection (which fails and kill the thread)? :

This is failing because of missing permission. And it is run as we simply start this as a periodic background check.
I would go make this in MediaFoldersDetectionJob more robust and exit early if permission is missing.

Do you want to to tackle these? :heart: 
(if so, please in separate (as possible) PRs)

**Comment by Shagequi** [comment]
I'll see what I can do :)

**Comment by tobiasKaminsky** [comment]
just to be sure: FirstRunActivity is also shown when you create a second account.

**Comment by Shagequi** [comment]
Yup, thank you for clarifying this.
To be honest, I'm interested in solving this issue, but I also have to spend time on other things. So I don't promise an immediate resolution :)

**Comment by tobiasKaminsky** [comment]
No problem, any help at any time is more than appreciated.
As it is working right now, it is nothing urgent :-)

**Comment by Shagequi** [comment]
up (I have to work on it)

**Comment by tobiasKaminsky** [comment]
To simplify this whole mess, I think it is best to have each Activity in its own separate life cycle:
- start app
- FDA checks if account is available
  - no account: start FirstRunWizard (without any dependencies), that's it
  - account exists: continue to FDA
- FirstRunWizard: starts login or choose provider, ends itselfs
- Login / choose provider: go through login or start FirstRunWizard again
- if login is successful go to FDA

This way we only have one Activity at the same time running.

Additional we have to consider:
- click on nc://login/ link which currently targets FDA
- scan QR code which is basically the same link, also targets FDA

**Comment by JorisBodin** [comment]
@tobiasKaminsky Why would the FDA be checks if account is available?
We could have an activity dedicated to that.
For exemple:

- start app
- LaunchActivity checks if account is available
- no account: start FirstRunActivity
- account exists: start FDA

**Comment by ezaquarii** [comment]
Yes, it is a mess. Generally this area is scheduled for serious redecoration effort once we deprecate legacy account registration logic. There is probably little sense to invest time in it at this moment.
