### ISSUE TITLE
Suppress Up/Download Notifications when accessed through DocumentsProvider

### ISSUE THREAD

**Issue by grote** [nextcloud/android#4998]
### Is your feature request related to a problem? Please describe.

When Nextcloud's storage is accessed through Android's storage access framework programmatically, lots of files might be uploaded. This causes a flood of upload and download notifications popping up all the time.

Insofar this is related to #261 which would already help

### Describe the solution you'd like

If notifications could be suppressed for access that happens via the DocumentsProvider this would be perfect as apps accessing it usually provide their own progress reporting.

### Describe alternatives you've considered

Maybe there could also be other mechanisms to suppress the notifications such as the presence of a special file in a parent folder like `.nomedia`.

An alternative could be to only show a single notification for the up/downloads like described in #261.

**Comment by grote** [comment]
After https://github.com/nextcloud/android/pull/6806 was merged, there are only upload notifications left: one persistent one saying "Uploading files..." and one per uploaded file which gets recreated for each new file in the queue.

**Comment by jmue** [comment]
Thank you for your work on this :thumbsup:. Please note my issue https://github.com/nextcloud/android/issues/6883 which coveres a case where a notification is show while **opening** a document.

**Comment by grote** [comment]
The persistent notification saying "Uploading files..." is created by `FileUploader`, because it is needed for the foreground service it starts.

Then, it creates additional notifications for progress reporting. @tobiasKaminsky I wonder, if we could not simply make the progress notification update the foreground notification instead of creating a dedicated one. What do you think? I can also contribute a PR, if it helps and there are no other plans.

Alternatively, we could investigate if the notification grouping feature helps. When you support simultaneous uploads, this might become useful.

**Comment by tobiasKaminsky** [comment]
> What do you think?

This should be possible. 

It would be great if you can do this :+1:

**Comment by grote** [comment]
I marked the above PR as closing this ticket as only one single upload notification is left which is probably fine or do you think we should get rid of this one as well?

**Comment by tobiasKaminsky** [comment]
Thanks!
No, we decided to keep uploading notification so that user know that something is happening.
