### ISSUE TITLE
What's new screen

### ISSUE THREAD

**Issue by przybylski** [nextcloud/android#50]
@AndyScherzinger @tobiasKaminsky @jancborchardt 
Do we want it? Should introduce that PR here ?

**Comment by AndyScherzinger** [comment]
:smiley: I would appreciate a screen like that, the question is do we want an "Introduction screen" or a "What's new"?

I would vote for a intro screen which only gets shown the very first time and never again, not even for updates. What's new would be nice too but would lead to extra work for every feature release since the core team developing new this right now is just the three of us I would argue that we should rather spend our time on features than maintaining the what's new screen for every release plus the feature images we would need for every release. So what'#s new will most likely slow down our dev speed :rocket:

**Comment by przybylski** [comment]
Well, the code is ready and should work just fine it. Last time I tested it, it was working on first run and on update.
https://github.com/owncloud/android/pull/1375
Now with other beta version scheme it will be easier to add this to beta release as well.

**Comment by AndyScherzinger** [comment]
Version theme?
We still have 2 themes one for the play store with proper versioning scheme and the f-droid beta which uses the release date. So it would work for the Play Store beta programm

**Comment by przybylski** [comment]
version number scheme: https://github.com/nextcloud/android/wiki/Development-Guide#version-name-and-number

**Comment by AndyScherzinger** [comment]
...for stabe and release candidate (as in play sore beta), else for the Tobias' beta: https://github.com/nextcloud/android/wiki/Development-Guide#development-beta-release

**Comment by przybylski** [comment]
damn, sorry for confusion.

**Comment by AndyScherzinger** [comment]
No worries :)
Our Goal is to not need the hardcore beta anymore but to merge fast, test, feature freeze, release to Play beta programm for 2 week, release it as stable

**Comment by tobiasKaminsky** [comment]
I think it is a good idea to show the biggest changes (if any) on every new release.
Mostly it is just a short text and an image, so it is not that much time and hopefully the PR author supports us.

**Comment by tobiasKaminsky** [comment]
Otherwise e.g. multiselect is not immediately known to users

**Comment by jancborchardt** [comment]
»What’s new« is only necessary on really big changes as you already said. A generic »changelog« screen is annoying and people generally don’t care as long as everything works. ;)

Didn’t we have a nice intro slideshow at some point, or was that only iOS?

**Comment by AndyScherzinger** [comment]
@jancborchardt The what's new screen is actually implemented as a Intro slideshow :dancer:

**Comment by przybylski** [comment]
In that case on the weekend I will import that PR here

**Comment by Bugsbane** [comment]
Personally, as a user, I love seeing a "What's New" screen, but only, as @jancborchardt noted, for major improvements, not for every bugfix in every minor point release. That way it's always exciting when it comes up as you know you now have access to some Cool New Thing™.

**Comment by tobiasKaminsky** [comment]
That is the plan :+1: only on major upgrades and then also only the new major features :tada:

**Comment by AndyScherzinger** [comment]
Okay, that then mean that we would use it for "What's new" only and not for "Introduction to the app", which is fine with me. Only issue I can thing of is that nice graphics for new features could block releases if they don't get done on time, same issue if we add text for the features that is only translated by 50% for a language. :(

**Comment by tobiasKaminsky** [comment]
I thought it is both for introduction and for new features (and we were just talking about the scope for the features).
Regarding the graphics/languages this is indeed a problem.
How is this currently solved? Do we wait until the major languages are fully translated before releasing?

**Comment by AndyScherzinger** [comment]
At the moment we just release after the RCs have proven to be stable. This will probably always be the case. Most widely used languages are fully translated at the final release date.

We should then still have a differentiating between whats new and introduction. So at first start we should only show the intro, at update we should only show the what's new.

**Comment by Bugsbane** [comment]
> nice graphics for new features could block releases

I can't promise to always be available depending on my workload, but let me know if I can help out here.

> So at first start we should only show the intro, at update we should only show the what's new.

Agreed, although I'm sure the same classes could be used, just feeding in two different content streams.

**Comment by AndyScherzinger** [comment]
> I can't promise to always be available depending on my workload, but let me know if I can help out here.

That would be great! At least the "Intro graphics" are stable so if you have time you could already help us out with these :smiley: 

> Agreed, although I'm sure the same classes could be used, just feeding in two different content streams.

Exactly, yes that is the case. :+1:
