### ISSUE TITLE
File ownerId is null after file upload

### ISSUE THREAD

**Issue by ezaquarii** [nextcloud/android#5005]
### Actual behaviour
Freshly uploaded file is presented as being shared by `null` in file details page

### Expected behaviour
Share information should be hidden for self-owned files
 
### Steps to reproduce
1. upload a file
2. go to file details
3. show shared tab
4. observe that file is shared by `null`

### Environment data

Device model: OnePlus 6T
Stock or customized system: stock
Nextcloud app version: master
Nextcloud server version: 17

### Additional info:
- ownerId is refreshed after pull-to-refresh

**Comment by ezaquarii** [comment]
Share information is shown if `accountOwnsFile` evaluates to false.

```
    @Override
    public  boolean accountOwnsFile(OCFile file, Account account) {
        return !TextUtils.isEmpty(file.getOwnerId()) && account.name.split("@")[0].equals(file.getOwnerId());
    }
```

Immediately afetr uploading a file `TextUtils.isEmpty(file.getOwnerId())` is `true`.

@tobiasKaminsky Would that work?
```
    @Override
    public  boolean userOwnsFile(OCFile file, User user) {
        return TextUtils.isEmpty(file.getOwnerId()) || user.getId().getUsername().equals(file.getOwnerId());
    }
```

**Comment by tobiasKaminsky** [comment]
Looks good to me, as when a new file is created, the current user is the owner :+1:
