### ISSUE TITLE
No app set up to handle this file type

### ISSUE THREAD

**Issue by cieska** [nextcloud/android#5009]
### Actual behaviour
Android NX app has a lack of option when opening an unknown file type. After error message user left without the option to choose from the list of apps. 

### Error message
> No app set up to handle this file type.

### Expected behaviour
Would be nice to have to choose what app to use when NX app doesn't know how to deal with it. 
 
### Steps to reproduce
1.  Try to open YAML file (which is a simple text file) in NX app.
2. 
3. 

### Environment data
Android version: 9

Device model: OnePlus A5010

Stock or customized system: no major changes applied 

Nextcloud app version: 3.9.2 (usually latest - auto-updates ON)

Nextcloud server version: 16.0.6 (production stream)

### Screenshot
![Screenshot_20191206-133027](https://user-images.githubusercontent.com/41318524/70870739-e66de400-1f8e-11ea-9e20-380b05616ec6.jpg)

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky how do we want to handle this? When we can't detected the mime type we can just launch for "file" which won't give you a useful set of applications...

While for .yaml and others I'd be just fine to add them (doesn't solve the issue with unknown/undetctable types)

**Comment by AndyScherzinger** [comment]
pinging @tobiasKaminsky for feedback

**Comment by monperrus** [comment]
I just hit this bug and error message.

It happens for kbdx files (KeePass). It worked perfectly before and KeePassDroid is still installed.

Is there a known workaround on the client-side (phone) or on the server-side?

**Comment by AndyScherzinger** [comment]
@monperrus we didn't change anything on the Nextcloud side. For a workaround I usually suggest using KeePass2Android which is an android app having a dav client, so keepass2android itself is keeping your KeePass database in sync with the Nextcloud.

**Comment by AndyScherzinger** [comment]
You could test the QA build in #5326 to be sure

**Comment by monperrus** [comment]
> we didn't change anything on the Nextcloud side.

do you mean on the client side?

FYI, the regression seems to coincide with a server upgrade from 16.x to 18.x

**Comment by monperrus** [comment]
> I usually suggest using KeePass2Android which is an android app having a dav client, so
keepass2android itself is keeping your KeePass database in sync with the Nextcloud.

Thanks for the suggestion, I'll try this.

**Comment by AndyScherzinger** [comment]
> do you mean on the client side?

Yes, no changes on the client side

> FYI, the regression seems to coincide with a server upgrade from 16.x to 18.x

Interesting, while I am not aware of any change that might cause this though upgrading 2 mayor versions might have some changes relevant to this case.

**Comment by monperrus** [comment]
Who is responsible for setting the mime-type of the file based on the extension, the client or the
server?

**Comment by tobiasKaminsky** [comment]
This depends:
- open file online in text/OnlyOffice: we get matching mimetypes from server
- open files within our app, .eg. download markdown: we match in client
- open files with another app, e.g. keepass: Android is responsible of it: other apps register themselves centrally and Android shows a matching list.

**Comment by cieska** [comment]
Hopefully there will be some changes in future and I will leave this to be closed in two weeks. Thanks guys for you work..

**Comment by AndyScherzinger** [comment]
@cieska I'll tested the latest master build and it works fine for me as in:
* yml files get opened by the markor app directly (so that might work for you too
* kdbx files get opened by keepass2android 

so both file types mentioned in this issue are actually resolved.

**Comment by jgoerzen** [comment]
Hi all,

I've been experiencing this same issue after upgrading to server v18, with KeePassDroid.  This is a pretty severe issue for me.  Do I understand correctly that a patch is checked in on this?  If so, is there an ETA for the build appearing on the play store?

FWIW, it would also be nice to have a "download" option so a file could just be saved in the Downloads folder, as with a web browser, and then opened from there.

**Comment by AndyScherzinger** [comment]
@jgoerzen this is rather related to KeePassDroid I am afraid. It works just fine for keepass2android so no patch or anything since there is no issue on the Nextcloud side.

**Comment by jgoerzen** [comment]
I submitted a KeePassDroid bug and can confirm it works with keepass2android.

I'm confused though.  I upgraded Nextcloud Server from 16 to 18, made no change on Android, and now my .kdbx files are useless on Android; I can't open them in KeePassDroid, can't save them, can only "send" them with some apps (Gmail, etc...  don't want to send something security-sensitive like that).

Shouldn't there be a "save to Downloads" or some such option here?

**Comment by AndyScherzinger** [comment]
We don't have a download option, while the client downloads the file and stores it in its own data path.

Other than that without using KeePassDroid, so I can't say much about it, I am using KeePass2Android since it offers WebDav, so keepass2android is actually managing my kdbx file on the Nextcloud server it self and syncs changes back and forth (which is likely what you would also like to have).

**Comment by AndyScherzinger** [comment]
See also https://github.com/bpellin/keepassdroid/pull/352

**Comment by monreal** [comment]
> I'm confused though. I upgraded Nextcloud Server from 16 to 18

Same here, only difference is that my server was upgraded from 17 to 18

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky did we change anything (an in reading a server side detected mime type I am not aware of?)

**Comment by stephensimon758** [comment]
Actually, the file extension that the original poster was looking for was .yaml which still doesn't work, at least for me. Does anyone have any further info that might help? Should this be reopened?

**Comment by gbakeman** [comment]
I think I've been running into this issue too, both for KeePass files and now PDFs. It doesn't seem like Nextcloud is really referring to Android to handle files the user wants to open. For example, I downloaded a PDF in Nextcloud. When I try to open it, Nextcloud claims that the file type is unsupported. When I open my Nextcloud directory with the Material Files app, and select the PDF, I get the Android app selector as I would've expected in Nextcloud.

Why is there this disconnect between how any other file manager opens a file, and how Nextcloud handles the file? Is there any way this can be addressed?

![Screenshot_20211012-112532](https://user-images.githubusercontent.com/842942/137009971-216e2cce-600b-4ee2-a2f1-fd1dba4af00a.jpg)

**Comment by FreeMinded** [comment]
I just got bit by this as well. No known updates my side. 2-3 days ago Nextcloud Client suddenly stopped open kdbx, pdf and other files (all?) in external application. Is there any workaround to this?

**Comment by AndyScherzinger** [comment]
I just tried to reproduce this and it works just fine, I click on a pdf, and it shows me the choice of apps capable of opening the PDF. Which version of the app are you using as well as which server version, do you have an internet connection at that moment etc.

**Comment by AndyScherzinger** [comment]
Can reproduce it now on the latest release candidates, but not on 3.17, please track #9227 for further discussions/fixes
