### ISSUE TITLE
Auto-upload not working after upgrade to Android 10

### ISSUE THREAD

**Issue by schtibal** [nextcloud/android#5011]
### Actual behaviour
- After taking a photo with camera, or saving an edited photo to a folder monitored by auto-upload, nothing happens.

### Expected behaviour
- Newly saved image file should be uploaded to Nextcloud server.
 
### Steps to reproduce
Auto-upload has been working without a problem for me for months, through a number of server and client upgrades. Photos taken the day before my phone was upgraded were uploaded successfully. Photos taken the day after my phone upgraded do not upload.

Auto-upload still works fine on my other (older) Android devices.

I've tried to disable/enabled and remove/add auto-upload folders, to no avail.

I realise there are already a handful of other issues raised around auto-upload not working, but none seem to be specific to Android 10.

### Environment data
Android version: 
10
Build #00WW_5_13D

Device model: Nokia 9 Pure View

Stock or customized system:
Stock (Android One)

Nextcloud app version:
3.9.2

Nextcloud server version:
17.0.1

#### Web server error log
```
(No web logs generated)
```

**Comment by ArisuOngaku** [comment]
@schtibal does this issue persist in latest 3.10.1 version?

**Comment by schtibal** [comment]
All seems to working fine for me now

**Comment by ArisuOngaku** [comment]
Nice! If anybody is still having a similar issue please open a new one (unless another opened one already exists).
