### ISSUE TITLE
libEGL: EGLNativeWindowType 0x7e35e57010 disconnect failed android

### ISSUE THREAD

**Issue by Benjy45** [nextcloud/android#5021]
I Resolve the problem with OPEN GL in FisrtRunRctivity.java

`
GLSurfaceView glView = new GLSurfaceView(getApplicationContext());

glView.setEGLContextClientVersion(2);

glView.setPreserveEGLContextOnPause(true);

`

[https://www.codota.com/code/java/methods/android.opengl.GLSurfaceView/setPreserveEGLContextOnPause?fbclid=IwAR319niKBMYhvgW8OJPrU55F4FQuWmBe2IeYeIt0m6vp07KWC7msFfDAZ7M](url)

**Comment by skshaon** [comment]
by using those line of code .. 
i steel face same problem ?

**Comment by igovind** [comment]
i am facing this issue in flutter

**Comment by albertochigua** [comment]
> i am facing this issue in flutter

@igovind me too, any solution to the problem? I only get it on a motorola g20 device, in all other tests on emulator and real devices it works fine.
