### ISSUE TITLE
Markdown Preview: Make hyperlinks clickable

### ISSUE THREAD

**Issue by thomas-mc-work** [nextcloud/android#5030]
At the moment the hyperlinks are just formatted as links (underlined and blue font colour) but not clickable. Would be nice to have them functionally.

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger do you have an idea?

**Comment by AndyScherzinger** [comment]
I'll have a look, while it might come out of the box when the client supports Nextcloud Text.

**Comment by AndyScherzinger** [comment]
https://noties.io/Markwon/docs/v4/core/configuration.html#linkresolver / https://github.com/noties/Markwon/issues/118 should do the trick while this doesn't seem to get triggered, so maybe somebody has an idea why, maybe @BaptisteRFoxIntel can shed some light onto this? 🙏 

https://github.com/nextcloud/android/blob/dbe12e6d20cd86a007001709a77dd938bf35c9d4/src/main/java/com/owncloud/android/ui/preview/PreviewTextFragment.java#L286-L300

**Comment by noties** [comment]
Hey! It is always `MovementMethod` when links are not clickable. But `Markwon` will set one automatically if it's missing after text is rendered. And it works just fine in most of the cases until `textIsSelectable` is added. So, try to set `LinkMovementMethod` to your TextView before applying markdown content, like this:

```java
// in onCreateView for example, or right before applying markdown
textView.setMovementMethod(LinkMovementMethod.getInstance());

/* ... */

markwon.setMarkdown(textView, markdown);
```

At least this worked for me

**Comment by AndyScherzinger** [comment]
@noties Thanks a lot for the hint! 🥇 Works for me too just fine.

@thomas-mc-work @tobiasKaminsky will open a PR is just a minute.
