### ISSUE TITLE
Crash at leaving the app

### ISSUE THREAD

**Issue by nagi121** [nextcloud/android#5036]
### Actual behaviour
- The App crashed

### Expected behaviour
- It should not crash at leaving the app
 
### Steps to reproduce
1. 
2. 
3. 

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
@nagi121 can you please post the corresponding logcat?

**Comment by nagi121** [comment]
Oh, sorry. I expected that the logcat will be attached to this issue automatically.
i am able to start the adb shell, can you tell me the right command to retrieve the logcat corresponding to the issue?

Some more information to the circumstances that leads to the crash:

Directly after installing the app, I connected to NextCloudPi and synchronized some folders. The crash occured after pressing the back button to leave the app.

**Comment by nagi121** [comment]
I found something. Hope this helps.

`12-19 16:01:18.571 15282 15282 E AndroidRuntime: FATAL EXCEPTION: main
12-19 16:01:18.571 15282 15282 E AndroidRuntime: Process: com.nextcloud.client, PID: 15282
12-19 16:01:18.571 15282 15282 E AndroidRuntime: android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{4a80abe u0 com.nextcloud.client/com.owncloud.android.services.OperationsService}
12-19 16:01:18.571 15282 15282 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1743)
12-19 16:01:18.571 15282 15282 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
12-19 16:01:18.571 15282 15282 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:280)
12-19 16:01:18.571 15282 15282 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6706)
12-19 16:01:18.571 15282 15282 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
12-19 16:01:18.571 15282 15282 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
12-19 16:01:18.571 15282 15282 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`

**Comment by AndyScherzinger** [comment]
Thanks for the logcat @nagi121, so you've been hit by a known issue #2010 so I am closing this one in favor of #2010.
