### ISSUE TITLE
Switching account on share option doesnt update files

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/android#5046]
### Actual behaviour
- File list still shows the items from the previous account, but the theming color changes

### Expected behaviour
- List of files/folder should update
 
### Steps to reproduce
1. Go to your files/gallery app
2. Select a file and share it to Nextcloud
3. Realise you are in the wrong account, so you switch account

### Environment data
Android version: 9

Device model: Xiaomi Mi A1

Stock or customized system: Android One

Nextcloud app version: 3.9.2/3.9.1

Nextcloud server version: 17.0.1 on both accounts

**Comment by AndyScherzinger** [comment]
Still unchecked

**Comment by jedwabny** [comment]
I observe the same. I can say that the account is finally switched, but after a few minutes of patient waiting. 
Anyway, it should switch in seconds.

**Comment by jedwabny** [comment]
I've just verified app version 3.10.1 and server 18.0 - it's working good. Thanks a lot!

**Comment by tobiasKaminsky** [comment]
Thanks for checking, @jedwabny.
Closing, please re-open if it happens again.
