### ISSUE TITLE
uploading too many files will get stuck

### ISSUE THREAD

**Issue by xuxingcan** [nextcloud/android#5048]
### Actual behaviour
- Tell us what happens
Uploading too many files will get stuck. But it will be uploaded again, if you switch to other pages.
 
### Expected behaviour
- Tell us what should happen
 upload normally

### Steps to reproduce
1. open the android app
2. upload more than 100 photos
3. switch the page to upload
4. the uploading list will be stuck after 3 or 4 photos uploaded
5. it will be uploaded again, if you switch to other pages.

### Environment data
Android version:9.0   and   7.1.1 

Device model: Huawei nova 4   and   smartisan OD103(坚果pro in Chinese)

Stock or customized system:

Nextcloud app version:3.9.2 from F-Dorid

Nextcloud server version:Nextcloud 17.0.1 with docker

### Something I knew
I had cloned the source code of the Android app and found out that the stuck happens at the line "result = mUploadOperation.execute(client);" in "UploadFileOperation.normalUpload". 

When a photo uploaded, the ThumbnailGenerationTask will be executed immediately in the other child thread(AsyncTask). so there will be more than one HttpClient to execute, once 2 HttpClient executed at the same time, then it gets stuck!!

Then I googled it, it seems to be a bug to HttpClient, see these links:

https://stackoverflow.com/questions/9925113/httpclient-stuck-without-any-exception
https://stackoverflow.com/questions/33351157/httpclient-hangs-when-doing-a-second-request

Hope to fix it soon, I will be there if you need any other information.

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by ezaquarii** [comment]
I can confirm that this is happening.

**Comment by anthraxn8b** [comment]
Still an issue.

**Comment by ezaquarii** [comment]
@anthraxn8b can you confirm that switching app pages resumes the upload process?

In the past, the upload was depending on garbage collector callbacks and that's why random actions were causing uploads to restart, but since we fixed this, this should no longer be depending on it. Perhaps you have found another issue?

**Comment by demaniak** [comment]
This still seems to be an issue as of 3 April 2023.
Fresh install of nextcloud server, android client sitting with 63 photos in the upload queue that refuse to go anywhere.

So the odd parts:
- where I spot checked, the images in question actually ARE uploaded, I can download(sync) with desktop client.  Seems fine.
- I can't remove the images from the upload queue (maybe my finger is just to fat to hit the close/cancel button?)

Some additional  info:
- relevant folders on android side is set to not upload existing files (seems relevant?)
- android folders set to upload only on unmetered wifi (I am on unmetered wifi)
- android folders set to upload only while charging  (phone is charging)
- android folders also set to use subfolders
