### ISSUE TITLE
Can't login Error, and QR Code do not work

### ISSUE THREAD

**Issue by nicrame** [nextcloud/android#5075]
Android 10, Xiaomi Mi9, server v 17.02 is working on CentOS 7 box i built last day.
Connecting with web browser is working good and as expected. I can login from computers or same Android device (using Firefox).
I was trying using Nextcloud Android app (newest from playstore) and had similar problem trying to use Nextcloud QA (v 11963 with upload existing files by default, what should be done in every stable release).
Problem: when i try to login, i get net::ERR_SSL_PROTOCOL_ERROR. But my Nextcloud DO NOT USE SSL, and at login address i use HTTP **not** HTTPS.
I also use non standard port (85) because locally my router use it for it's admin console (it also make less connection try from Internet by bots).
In attachment there are screenshots of this problem.
![Screenshot_2019-12-29-12-29-20-353_com nextcloud client](https://user-images.githubusercontent.com/5872054/71556668-9df90080-2a3b-11ea-86c1-dcbe7eb41926.jpg)
![Screenshot_2019-12-29-12-28-44-863_com nextcloud client](https://user-images.githubusercontent.com/5872054/71556667-9df90080-2a3b-11ea-9c55-9662dcaefc4c.jpg)

Also, the QR Code reading do not work at all, i just generated QR with my server address and Nextcloud apps say that it can't read it (tried laaarge boxes and small, and from many websites).

**Comment by tobiasKaminsky** [comment]
Can you create us a test account, test if the problem occurs also there and if so send the credentials to tobias at nextcloud dot com with a reference to this issue?
