### ISSUE TITLE
Deactive stale bot

### ISSUE THREAD

**Issue by krichter722** [nextcloud/android#5076]
The project seems to use stale bot which closes important issues which hasn't been dealt with after a certain time (e.g. #3151). Issues don't disappear after a time. They have to be resolved or a decision has to be made to close it. Closing them automatically is of no help for no imaginable project and causes the overhead that one day you have to figure out which issues are still present and need to be reopened.

The solution to keep a good overview of the backlog with labels and closing issues if they can't be reproduced without using the bot is always at least as good as using the stale bot, but doesn't cause the unnecessary communication overhead it produces.

Addition to this manifesto which I've been posting in some projects: I've seen the reply in #4279 which is why I added the second paragraph.

**Comment by lemmy04** [comment]
+1.

**Comment by lemmy04** [comment]
...at least rename the bot to "Angela".

**Comment by joshtrichards** [comment]
The old stale bot config is gone. Today we only expire out things that have been specifically tagged as needing further information from the reporter(s) in order to be actionable.
