### ISSUE TITLE
Auto-upload works on mobile wireless but not on LAN

### ISSUE THREAD

**Issue by admered1** [nextcloud/android#5084]
### Steps to reproduce
1. Log into home LAN
2. Take a picture
3. Watch it fail to upload

### Expected behaviour
- It should upload like it does on mobile data

### Actual behaviour
- Fails with "Connection Error"

### Environment data
Android version: 9

Device model: HTC U11+

Stock or customized system: Stock

Nextcloud app version: 3.9.2

Nextcloud server version: 17.0.2

#### Web server error log
No error logs .. no reports of anything in fact. Not sure the app even tried to connect.

#### Nextcloud log (data/nextcloud.log)
Nothing from the apps address at all

**Comment by velletti** [comment]
can confirm, that an AutoUpload problem exists with pictures.  but for me it happens independing from Connectiontype (WLAN / Mobile Data) 

The subfolder year/month is created, File Upload progressbar runs to 100 % and then Connection error. 
Also for me : No entry in the servers Logs. 

BUT : on the same phone (Huawei P20 Pro) the autoupload works for Screenshots. 
I Tried to restart the Phone, disable Backup And sync to google photos, but the error exists . 
Nextcloud app version: 3.9.2

Nextcloud server version: 16  Updateing to Server Version 17.0.2 helped for me .

**Comment by admered1** [comment]
It turned out to be a an odd routing issue .. closing

**Comment by velletti** [comment]
Thanks fr the answer, but how did you solve it ? what kind of odd Routing ? 
as i again have this problem ..

**Comment by admered1** [comment]
It was a unique self inflicted issue that had nothing in fact to do with Nextcloud
