### ISSUE TITLE
Very slow processing when first download lot of file in folder

### ISSUE THREAD

**Issue by JorisBodin** [nextcloud/android#5086]
Hello,

I've noticed that for processing more than 1000 files in a folder. The application processes the folder for about **a minute**. And only the first time. Afterwards it's not so long, but it's long anyway.

I'm making the optimization. **I'm getting to about a second now**. But I'd rather improve my code before proposing the pull request.

https://github.com/Infomaniak/android-infomaniak-drive/tree/optimization

**Comment by JorisBodin** [comment]
![image](https://user-images.githubusercontent.com/2796439/71663869-2555b500-2d57-11ea-94e4-eb37dc00449f.png)
@tobiasKaminsky 
I do not understand the addition of this line. It adds a lot of processing time. What is its purpose?

**Comment by JorisBodin** [comment]
@tobiasKaminsky 
I found it useful
https://github.com/nextcloud/android/issues/4502#issuecomment-540430544

I was trying to optimize this, but I can't reproduce the bug to understand exactly what's going on.
Because it adds 10 seconds of processing for the first sync of a folder of + 1000 files.

I realized that on the emulator it was very fast. But I was on an s8 galaxy

**Comment by tobiasKaminsky** [comment]
> I was trying to optimize this, but I can't reproduce the bug to understand exactly what's going on.

This is not a bug, but you can reproduce it like this:
- have a fresh installation (with no database content of files)
- open up "photo" section 
- click on an image
- this needs then parentId and thus it needs to be fetched

As this is exists on second refresh, it is a lot faster.

For photos this might be possible to change, but the concept is also true for search, where you can get a file, where no ancestor is known, and thus it (currently) needs to be fetched.
