### ISSUE TITLE
Push notification not working.

### ISSUE THREAD

**Issue by nextra06** [nextcloud/android#5092]
### Steps to reproduce
1. Enable 2FA in Nextcloud Server (Nextcloud notification and TOTP)
2. Install Nextcloud app (Google Play)
3. Login to your account with your credentials (in App) 
4. Login to Nextcloud via web browser on a PC or elsewhere outside the app
5. Enter your login details
6. Select Nextcloud notification option (2FA)

### Expected behaviour
Notification should be pushed to device.

### Actual behaviour
Notification is only visible in the app and not on device screen outside the app.

### Environment data
Android version: 10 / 9 / 8 / 7

Device model: OnePlus 6 (Stock) & Sony Z5 (Stock rooted)

Stock or customized system: Stock

Nextcloud app version: 3.9.2

Nextcloud server version: 16.0.5 (Apache - HTTPS / HSTS / HTTP/2 / PHP-FPM / Redis / APCu)

### Logs
No errors
```
None
```

#### Nextcloud log (data/nextcloud.log)
```
Nothing about push notifications. Just some warnings about ClamAV not found as it has been removed.
```

Notification app is enabled on server. Nothing works to make the notifications visible outside the app.

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by nextra06** [comment]
Sorted out the problem. Had modified the login.js file to incorporate some specific security requirements. Turns out it disturbs the login flow to register push devices.
All well now (So far).

**Comment by AndyScherzinger** [comment]
thaanks for the update @nextra06 👍
