### ISSUE TITLE
Whitespace of rich workspaces section is off

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/android#5096]
In the root folder there is a big white space on top, no placeholder for the rich workspaces which lets me know I can add text or so, like on the web:
![workspace whitespace root](https://user-images.githubusercontent.com/925062/71782351-99b87e80-300b-11ea-8d1d-9b50ca3a292b.png)

Also in folders with rich workspace content there's only one heading line shown and then whitespace, bit more preview text would be good, like on web:
![workspace whitespace](https://user-images.githubusercontent.com/925062/71782354-9ae9ab80-300b-11ea-85c4-1f0cec10c7e3.png)

Especially when there’s only a bit more text in there it would be good to simply show that:
![workspace open](https://user-images.githubusercontent.com/925062/71782353-9a511500-300b-11ea-977a-d7779dd1d48f.png)

cc @tobiasKaminsky @juliushaertl 

(Also btw, what is that line below the heading?)

**Comment by tobiasKaminsky** [comment]
> In the root folder there is a big white space on top, no placeholder for the rich workspaces which lets me know I can add text or so, like on the web:

Do you have a readme.md in your root folder? which is empty?

**Comment by tobiasKaminsky** [comment]
> Also in folders with rich workspace content there's only one heading line shown and then whitespace, bit more preview text would be good, like on web:

This is how your file is…if headline is too big, or too much whitespace you do not see much.

**Comment by tobiasKaminsky** [comment]
> Especially when there’s only a bit more text in there it would be good to simply show that:

we use 30%, this is hardcoded, we will/can not analyze the text to distinguish how much we want to show.

**Comment by tobiasKaminsky** [comment]
> (Also btw, what is that line below the heading?)

This is how a headline is separated by markdown. 
Isn't this the normal view for it? 
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#h1

**Comment by juliushaertl** [comment]
> we use 30%, this is hardcoded, we will/can not analyze the text to distinguish how much we want to show.

Since you are loading the file anyway, we could at least make sure that if the size is 0 or if no readme is found, we show a nice placeholder like on the web.


> This is how a headline is separated by markdown.
> Isn't this the normal view for it?
> adam-p/markdown-here/wiki/Markdown-Cheatsheet#h1

We should make sure the markdown preview is at least similar to what it looks like in text: 
![image](https://user-images.githubusercontent.com/3404133/71902555-9c79b780-3162-11ea-8850-2636b9c64d3c.png)

**Comment by tobiasKaminsky** [comment]
> Since you are loading the file anyway, we could at least make sure that if the size is 0 or if no readme is found, we show a nice placeholder like on the web.

We do not load the file, but it get via dav from server. And I show it only if size is not empty.
Having a placeholder in every folder is a bit too much, or?

**Comment by tobiasKaminsky** [comment]
> We should make sure the markdown preview is at least similar to what it looks like in text:

Not sure how and if this is possible, as we only use the library.

**Comment by jancborchardt** [comment]
What @juliushartl said. :)

> Having a placeholder in every folder is a bit too much, or?

We should do it the same as on web, where we do show a placeholder in every folder.
On the web we also need a setting "Show rich workspaces" and the same should be available on mobile.

**Comment by tobiasKaminsky** [comment]
> What @juliushaertl said. :)

What does this mean?

> On the web we also need a setting "Show rich workspaces" and the same should be available on mobile.

we had this issue open for so long, and now 1,5 before NC18 you come up with such an idea?
(remember that we discussed this together with Julius at last hackweek)

**Comment by tobiasKaminsky** [comment]
Due to space constraints I propose this:
- show rich workspace only if text is set
- if not, have an option in three dots menu "add folder info"
  - this then opens up text editor

**Comment by jancborchardt** [comment]
@tobiasKaminsky sounds great! :)

Should be the same on iOS @marinofaggiana

**Comment by marinofaggiana** [comment]
for me is not clear the: 

> show rich workspace only if text is set 

you open in top a web view that  load the readme.dm ?

**Comment by marinofaggiana** [comment]
>if not, have an option in three dots menu "add folder info"
this then opens up text editor

it would be better a button (text) in top "as Server side" with in gray: Add notes ?

**Comment by tobiasKaminsky** [comment]
Yes, I think this takes too much spaces, and I am not sure how many users really do use this feature.
So I think it is a good trade off to have it in an option menu.

**Comment by marinofaggiana** [comment]
For now I don't insert this section, I want to understand if used and how to make it graphically pleasant.

**Comment by jancborchardt** [comment]
If there is content in the Readme.md, a preview should absolutely be shown though – also on mobile. Otherwise this is not visible and findable at all.

**Comment by AndyScherzinger** [comment]
Still open

**Comment by tobiasKaminsky** [comment]
So, we show content of Readme if there is one.
Content is shown as is, we cannot do any logic here.
Otherwise we show "add folder info" in overflow menu.

If something is missing, please re-open.
