### ISSUE TITLE
Give the possibility to group folders/files by [date, type, etc]

### ISSUE THREAD

**Issue by kjlhgfds** [nextcloud/android#5101]
### Is your feature request related to a problem? Please describe.
In a folder with folders and files, when you "sort by" something ex. date), the files and folders mix together, wich isn't really easy to navigate.

### Describe the solution you'd like
I would be great to be able to "group by" (ex. type), so all the folder would stick together, etc.

### Describe alternatives you've considered
When you "sort by", it doesn't mix folders and files.

### Additional context
[
![sort by](https://user-images.githubusercontent.com/43605270/71823731-46404200-3098-11ea-8322-3064a247e00a.jpg)
](url)

**Comment by AndyScherzinger** [comment]
cc @nextcloud/designers @jancborchardt for feedback

**Comment by jancborchardt** [comment]
Yes, in iOS we have an option called "Sort folders on top" and this is one thing that I’d say is good to also bring to Android and web.

cc @nextcloud/designers @tobiasKaminsky what do you think? (I remember there’s also existing issues about this)

**Comment by AndyScherzinger** [comment]
Sounds good to my. I checked and couldn't find an existing issue for this, so I'd say this one is fine while the feature request would be

* add option to sorting dialog to "Sort folders on top", question is, is this a general or a per folder setting since the sorting is a per folder setting (!)

**Comment by jancborchardt** [comment]
Hmm, I’d say that it should be a general setting for now. In the web interface for example it would go into the bottom left settings area.

**Comment by tobiasKaminsky** [comment]
As this is a feature parity thing, I created it in server: https://github.com/nextcloud/server/issues/18905
Thus closing it here.
