### ISSUE TITLE
Fab + is white for dark theme with primary color #FFFFFF

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#5110]
Testing #5107 I realized that the fan's + is white for dark theme and primary color white.

**Comment by tobiasKaminsky** [comment]
![2020-01-08-064458](https://user-images.githubusercontent.com/5836855/71953409-6714ae80-31e2-11ea-9d62-8c9eb3eed133.png)

Hm. Not for me? I tested on latest master (after merging all outstasting PRs)

**Comment by AndyScherzinger** [comment]
Will check later, so let's keep our fingers crossed 🤞

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky tested the RC1 QA build, same issue.

**Comment by tobiasKaminsky** [comment]
Hm. I am testing this on my emulator.
Maybe a real device behaves different…? :thinking:

**Comment by AndyScherzinger** [comment]
Don't know, but might be able to test this later today in the afternoon via the branch.
Which Android version are you testing on?
