### ISSUE TITLE
FirstRun is not shown

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#5112]
### Steps to reproduce
1. fresh installation

### Expected behaviour
- see first run wizard

### Actual behaviour
- directly see authenticator activity

Tested on latest master / 3.10

**Comment by AndyScherzinger** [comment]
I can reproduce this behaviors, thus `approved`

**Comment by tobiasKaminsky** [comment]
@ezaquarii do you have an idea?
Something seems to call "finish" on FirstRun, as it is definitively started, but immediately ended.
