### ISSUE TITLE
[3.10 RC1] When upload/editing is restricted: make the plus-button grey again

### ISSUE THREAD

**Issue by szaimen** [nextcloud/android#5124]
[3.10 RC1] When upload/editing is restricted: make the plus-button grey again
### Steps to reproduce
1. Install 3.10 RC1
2. open a folder with restricted upload/editing
3. Plus button should be grey here (since upload and editing is forbidden here) but has the primary color:
![20200108_133815](https://user-images.githubusercontent.com/42591237/71978664-305b8a00-321c-11ea-9d17-6af8b64cc26d.png)

**Comment by AndyScherzinger** [comment]
@szaimen is the button still "green" after the folder has been loaded?

@tobiasKaminsky @nextcloud/designers @jancborchardt I'd even say hide the FAB in case it's actions are disabled.

**Comment by szaimen** [comment]
@AndyScherzinger yes, it is still green even after the folder has loaded.

**Comment by szaimen** [comment]
> I'd even say hide the FAB in case it's actions are disabled.

This makes sense imho 👍

**Comment by jancborchardt** [comment]
Let’s make it muted, so it’s clear it’s disabled, and additionally when you tap it, there should be a toast (or something comparable) stating why it is disabled. In the server we say:

> You don’t have permission to upload or create files here

**Comment by AndyScherzinger** [comment]
> Because if we just not show the FAB it looks like an error and people don’t know why it is hidden. :)

Sounds good! @tobiasKaminsky any idea how to implement this? :)

**Comment by tobiasKaminsky** [comment]
I have a quick fix for restoring grey color again: #5187 

The other part, where there should be a snackbar, will be in a new PR, in a later version.
As this requires a bit more testing, so that in every case the snackbar is shown correctly.
