### ISSUE TITLE
Auto upload not working on Samsung Galaxy S10 with Android 10

### ISSUE THREAD

**Issue by msundin** [nextcloud/android#5127]
### Steps to reproduce
1. Update your Galaxy S10 from Android 9 to Android 10
2. Auto upload stops working in Nextcloud

### Expected behaviour
- Auto upload should work

### Actual behaviour
- Nothing is uploaded

### Environment data
Android version: 10

Device model: Samsung Galaxy S10

Stock or customized system: Stock

Nextcloud app version: 3.9.2

Nextcloud server version: 16.0.4

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by szaimen** [comment]
I have a S10e and for me its working.
Have you looked here? 
https://dontkillmyapp.com/

**Comment by msundin** [comment]
Thanks @szaimen but it was not that.

However I updated the server from 16.0.4 to 16.0.7 and updated the S10 with the latest January Android 10 patch and all of a sudden it started working again. Not sure if that fixed the problem or something else but at least it works now.
