### ISSUE TITLE
Error at starting the app

### ISSUE THREAD

**Issue by julio666** [nextcloud/android#5137]
### Steps to reproduce
1. I've just started my app (using it for some months now)

### Expected behaviour
I expect my app to start but it crashes while trying to update content from the server.

### Actual behaviour
The app crashes while trying to update the content from server.

### Server version
17.0.1

### Mobile info and logs
```
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Message android.os.MessageQueue.next()' on a null object reference
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5525)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090290
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: lge
Device: p1
Model: LG-H812
Id: MRA58K
Product: p1_vtr_ca

************ FIRMWARE ************
SDK: 23
Release: 6.0
Incremental: 162351557bde6
```

**Comment by AndyScherzinger** [comment]
@julio666 does this happen constantly or just once, since the error log only shows code from Android itself not from the app's code?

**Comment by julio666** [comment]
@AndyScherzinger it was happening constantly since the first time it appeared. I have uninstalled my app and downloaded it again. Everything is right since then.

My nextcloud server is seflhosted. Maybe I can find clues on it if you tell how to.

**Comment by tobiasKaminsky** [comment]
Hm. This is very hard to debug, as Andy said, there is no real code from our side involved.
So closing it, as it works…
