### ISSUE TITLE
Creating files from templates is missing an action button

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/android#5144]
When creating files from templates e.g. with Collabora the view seems to be confusing to quite some people as there is no primary action button present.

![image](https://user-images.githubusercontent.com/3404133/72142352-c4506180-3394-11ea-91f1-6e50226fa3c8.png)

I would propose the following enhancements to that:
- Add a "Create file" primary action in the bottom
- If only one template is present (empty) hide the template selector

cc @nextcloud/designers

**Comment by jancborchardt** [comment]
> * Add a "Create file" primary action in the bottom
> * If only one template is present (empty) hide the template selector

Yep, exactly. Additionally:
- Put a heading "Document name" above the doc name input field. :)

**Comment by rcs10** [comment]
@AndyScherzinger @jancborchardt @juliushaertl can I work on this issue?

**Comment by tobiasKaminsky** [comment]
Sure :+1: 
If you have any question, feel free to ask :-)

**Comment by rcs10** [comment]
@tobiasKaminsky can you review my PR and i have used screenshot of the working model ,that should suffice right?
