### ISSUE TITLE
Crash when changing sorting order

### ISSUE THREAD

**Issue by vasyugan** [nextcloud/android#5149]
************ CAUSE OF ERROR ************

java.lang.ClassCastException: com.owncloud.android.ui.activity.FolderPickerActivity cannot be cast to com.owncloud.android.ui.dialog.SortingOrderDialogFragment$OnSortingOrderListener
	at com.owncloud.android.ui.dialog.SortingOrderDialogFragment$OnSortOrderClickListener.onClick(SortingOrderDialogFragment.java:180)
	at android.view.View.performClick(View.java:6597)
	at android.view.View.performClickInternal(View.java:6574)
	at android.view.View.access$3100(View.java:778)
	at android.view.View$PerformClick.run(View.java:25906)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090290
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus3T
Model: ONEPLUS A3003
Id: PQ3A.190801.002
Product: lineage_oneplus3

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 14326229a3

**Comment by tobiasKaminsky** [comment]
How can this be triggered?

**Comment by vasyugan** [comment]
Am Freitag, den 10.01.2020, 11:24 -0800 schrieb Tobias Kaminsky:
> How can this be triggered?

What I did was switch the sorting mode in a directory. That's all I can
tell. I assume this is not easily reproduced.

**Comment by ezaquarii** [comment]
@tobiasKaminsky I haven't reproduced it as I don't know how, but I did some code analysis and it looks pretty straightforward.

`FolderPickerActivity` has sort action that launches this dialog:

https://github.com/nextcloud/android/blob/dbe12e6d20cd86a007001709a77dd938bf35c9d4/src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java#L316-L326

`SortingOrderDialogFragment` gets host `Activity` and blindly casts it to a listener:

https://github.com/nextcloud/android/blob/e92daa2fc4f8342249a31507846dea595ff4a194/src/main/java/com/owncloud/android/ui/dialog/SortingOrderDialogFragment.java#L176-L183

Please note that in this very case the host activity does not implement the listenre interface, hence it crashes. However, this interface is implemented in a derived `FilePickerActivity`:

https://github.com/nextcloud/android/blob/bf517356335e71d40853cb15a13f384248abdd70/src/main/java/com/owncloud/android/ui/activity/FilePickerActivity.java#L37-L38

Sort option has been added in commit 3a7ef8263297fae9b9a673f52b11c0262033a448.

So, how I see it:

1. sorting is meant to be implemented in `FilePickerActivity`
2. feature logic has been split between 2 classes: some logic that supports this action has been placed in base class `FolderPickerActivity`, on assumption that it won't be triggered from there, listener has been placed in `FilePickerActivity`
3. Somehow user is capable of displaying `FolderPickerActivity` and triggering this action from there, which does not implement part of the required logic and crashes

Solution:
1. Move menu action to `FilePickerActivity`, so it is not accessible from base class
2. Implement listener in `FolderPickerActivity` as well, if it makes sense to have sorting action there

**Comment by ezaquarii** [comment]
> How can this be triggered?

If you can display `FolderPickerActivity` somehow (**not** `FilePickerActivity`), it should be reliabily reproducible.

**Comment by AndyScherzinger** [comment]
Thanks for the detailed analysis @ezaquarii, due to which I can tell you folks how to reproduce:

* click the 3-dot menue of a file in the file list
* pick "Move"
* click 3-dot menu in folder picker toolbar
* dialog launches, pick different sorting
* **crash**

cc @tobiasKaminsky
