### ISSUE TITLE
Allow servers applications update from the android app

### ISSUE THREAD

**Issue by leolivier** [nextcloud/android#5151]
I'm frustrated when the Android app notifies me that there is an update of a server application that's available and I cannot install this update directly from Android although I have admin rights on the server
 
Would be great if we could update the applications installed on the server directly from the Android app when we receive a notification.

**Comment by tobiasKaminsky** [comment]
Sorry, this is out of scope for the app.
Also this should be done via ssh/screen (at least on big installations)…

**Comment by jospoortvliet** [comment]
Brave people do it from their mobile browser 🙈🙉🙊

**Comment by leolivier** [comment]
I can be brave from time to time but not too often :smile:

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky @jospoortvliet it think @leolivier is talking about nextcloud apps, not about the (core) server itself. So if the app notifications would over an update action (cc @nickvergessen) than this might be something that could then work out of the box?

@jospoortvliet I usually upgrade nextcloud via my phone's browser 😂

**Comment by nickvergessen** [comment]
We have apps that are way too big either. I stand with my point, adminstration is too critical to be done via phone. If you trust like that, you can also add occ app:update --all as a cron job and be done

**Comment by leolivier** [comment]
@nickvergessen, I don't understand what the size of applications has to do with this. I don't want them to be downloaded on my phone.
And I don't understand why you would trust any PC or even your phone browser more than your phone application...

**Comment by nickvergessen** [comment]
If your server has to download a lot of MB (20+ for maps, mail and 200+ for the document server) and your request is aborted due to network issues, it's quite risky to try this. I also wouldn't try to trigger an update via the browser on my phone. But maybe I'm just being paranoid. But the next request is then to allow installing apps from the phone, etc. and the effort for such a tiny section explodes.

**Comment by leolivier** [comment]
Fort the 1rst point, I don't get the difference you make between a phone application and any browser on any PC: for me, the risk is exactly the same. Anyway, at the end, if the installation has to fail, it'll fail exactly the same way, won't it?
For the 2nd point, I swear I'll never ask for installation of new application :grin: but updating is not the same, you might for instance face urgent security issues that should be fixed quickly...
