### ISSUE TITLE
null pointer exception on remove account of one account

### ISSUE THREAD

**Issue by stites** [nextcloud/android#5155]
### Steps to reproduce
1. Login (with only one account)
2. Navigate to Manage accounts
3. Remove account

### Expected behaviour
- Tell us what should happen
I log out and am sent to landing page

### Actual behaviour
- Tell us what happens
I get a null pointer exception 

### Environment data
Android version: 10

Device model: pixel 2xl

Stock or customized system: no

Nextcloud app version: fdroid nextcloud dev

Nextcloud server version: unknown, i think i was connected to Minnesota.

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by ezaquarii** [comment]
@stites Do you have a stack trace? How do you know it's NPE?

We can't do much without a stacktrace.

**Comment by stites** [comment]
![Screenshot_20200111-142044](https://user-images.githubusercontent.com/1694705/72209554-aca0d800-347d-11ea-9475-12db24cd891e.png)

I've already listed the steps to reproduce. It should be quite straightforward.

**Comment by ezaquarii** [comment]
@stites You can check the fix by installing apk using this QR code:

https://github.com/nextcloud/android/pull/5157#issuecomment-573356503
