### ISSUE TITLE
Allow managing multiple share links per folder

### ISSUE THREAD

**Issue by krombel** [nextcloud/android#5158]
### Is your feature request related to a problem? Please describe.
I wanted to share a folder with two sets of people:
- some people who should be able to have write access (so they dont need to have an account)
- some people who have read only access to the folder

Therefore I wanted to create two dedicated links (as I did on another folder in the past via web ui) and realized that it is not possible here. When creating a second link on web I additionally only see one link in Nextcloud Android. 

### Describe the solution you'd like
Manage multiple links per folder as Nextcloud Web provides.

### Additional context
It might be related to #3679 as it deals with multiple "share targets". But as it only relates to other accounts (!= "anonymous links") I think this is something different.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky sound right to me 👍

**Comment by joshtrichards** [comment]
Fixed in #6358
