### ISSUE TITLE
App dev crashes on startup

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/android#5162]
When starting the app, it crashes from versions dev-20200110 e0b77f9102f20980cabd2dbdd7b0ccc68f1bd51b and dev-20200112 09d98e16c5a252961867cbd7f6da0ca6b0caf021.

### Environment data
Android version: 6

Nextcloud app version:
dev-20200110 
dev-20200112

**Comment by ezaquarii** [comment]
Can you provide us with a stacktrace, please?

**Comment by Valdnet** [comment]
@ezaquarii Below the stack trace from the system:

`01-12 10:52:01.956  8853  8853 E AndroidRuntime: FATAL EXCEPTION: main
01-12 10:52:01.956  8853  8853 E AndroidRuntime: Process: com.nextcloud.android.beta, PID: 8853
01-12 10:52:01.956  8853  8853 E AndroidRuntime: java.lang.RuntimeException: Unable to create application com.owncloud.android.MainApp: android.database.sqlite.SQLiteException: duplicate column name: rich_workspace (code 1): , while compiling: ALTER TABLE filelist ADD COLUMN rich_workspace TEXT
01-12 10:52:01.956  8853  8853 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4803)
01-12 10:52:01.956  8853  8853 E AndroidRuntime: 	at android.app.ActivityThread.access$1600(ActivityThread.java:157)
01-12 10:52:01.956  8853  8853 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1417)
01-12 10:52:01.956  8853  8853 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-12 10:52:01.956  8853  8853 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
01-12 10:52:01.956  8853  8853 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5530)
01-12 10:52:01.956  8853  8853 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-12 10:52:01.956  8853  8853 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:734)
01-12 10:52:01.956  8853  8853 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:624)
01-12 10:52:01.956  8853  8853 E AndroidRuntime: Caused by: android.database.sqlite.SQLiteException: duplicate column name: rich_workspace (code 1): , while compiling: ALTER TABLE filelist ADD COLUMN rich_workspace TEXT
01-12 10:52:01.956  8853  8853 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
01-12 10:52:01.956  8853  8853 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:893)
01-12 10:52:01.956  8853  8853 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:504)
01-12 10:52:01.956  8853  8853 E AndroidRuntime: 	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:726)
01-12 10:52:01.956  8853  8853 E AndroidRuntime: 	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
01-12 10:52:01.956  8853  8853 E AndroidRuntime: 	at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
01-12 10:52:01.956  8853  8853 E AndroidRuntime: 	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1784)
01-12 10:52:01.956  8853  8853 E AndroidRuntime: 	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1715)
01-12 10:52:01.956  8853  8853 E AndroidRuntime: 	at com.owncloud.android.providers.FileContentProvider$DataBaseHelper.onUpgrade(FileContentProvider.java:2092)
01-12 10:52:01.956  8853  8853 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:256)
01-12 10:52:01.956  8853  8853 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)
01-12 10:52:01.956  8853  8853 E AndroidRuntime: 	at com.owncloud.android.providers.FileContentProvider.query(FileContentProvider.java:471)
01-12 10:52:01.956  8853  8853 E AndroidRuntime: 	at android.content.ContentProvider.query(ContentProvider.java:1017)
01-12 10:52:01.956  8853  8853 E AndroidRuntime: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:238)
01-12 10:52:01.956  8853  8853 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:500)
01-12 10:52:01.956  8853  8853 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:442)
01-12 10:52:01.956  8853  8853 E AndroidRuntime: 	at com.owncloud.android.datamodel.UploadsStorageManager.getUploads(UploadsStorageManager.java:289)
01-12 10:52:01.956  8853  8853 E AndroidRuntime: 	at com.owncloud.android.datamodel.UploadsStorageManager.getFailedUploads(UploadsStorageManager.java:368)
01-12 10:52:01.956  8853  8853 E AndroidRuntime: 	at com.owncloud.android.utils.FilesSyncHelper.restartJobsIfNeeded(FilesSyncHelper.java:194)
01-12 10:52:01.956  8853  8853 E AndroidRuntime: 	at com.owncloud.android.MainApp.initSyncOperations(MainApp.java:492)
01-12 10:52:01.956  8853  8853 E AndroidRuntime: 	at com.owncloud.android.MainApp.onCreate(MainApp.java:309)
01-12 10:52:01.956  8853  8853 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
01-12 10:52:01.956  8853  8853 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4800)
01-12 10:52:01.956  8853  8853 E AndroidRuntime: 	... 8 more
01-12 10:52:03.164  8900  8900 E AndroidRuntime: FATAL EXCEPTION: main
01-12 10:52:03.164  8900  8900 E AndroidRuntime: Process: com.nextcloud.android.beta:crash, PID: 8900
01-12 10:52:03.164  8900  8900 E AndroidRuntime: java.lang.RuntimeException: Unable to create application com.owncloud.android.MainApp: android.database.sqlite.SQLiteException: duplicate column name: rich_workspace (code 1): , while compiling: ALTER TABLE filelist ADD COLUMN rich_workspace TEXT
01-12 10:52:03.164  8900  8900 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4803)
01-12 10:52:03.164  8900  8900 E AndroidRuntime: 	at android.app.ActivityThread.access$1600(ActivityThread.java:157)
01-12 10:52:03.164  8900  8900 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1417)
01-12 10:52:03.164  8900  8900 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-12 10:52:03.164  8900  8900 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
01-12 10:52:03.164  8900  8900 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5530)
01-12 10:52:03.164  8900  8900 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-12 10:52:03.164  8900  8900 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:734)
01-12 10:52:03.164  8900  8900 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:624)
01-12 10:52:03.164  8900  8900 E AndroidRuntime: Caused by: android.database.sqlite.SQLiteException: duplicate column name: rich_workspace (code 1): , while compiling: ALTER TABLE filelist ADD COLUMN rich_workspace TEXT
01-12 10:52:03.164  8900  8900 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:179)
01-12 10:52:03.164  8900  8900 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
01-12 10:52:03.164  8900  8900 E AndroidRuntime: 	at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
01-12 10:52:03.164  8900  8900 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:500)
01-12 10:52:03.164  8900  8900 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:442)
01-12 10:52:03.164  8900  8900 E AndroidRuntime: 	at com.owncloud.android.datamodel.UploadsStorageManager.getUploads(UploadsStorageManager.java:289)
01-12 10:52:03.164  8900  8900 E AndroidRuntime: 	at com.owncloud.android.datamodel.UploadsStorageManager.getFailedUploads(UploadsStorageManager.java:368)
01-12 10:52:03.164  8900  8900 E AndroidRuntime: 	at com.owncloud.android.utils.FilesSyncHelper.restartJobsIfNeeded(FilesSyncHelper.java:194)
01-12 10:52:03.164  8900  8900 E AndroidRuntime: 	at com.owncloud.android.MainApp.initSyncOperations(MainApp.java:492)
01-12 10:52:03.164  8900  8900 E AndroidRuntime: 	at com.owncloud.android.MainApp.onCreate(MainApp.java:309)
01-12 10:52:03.164  8900  8900 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
01-12 10:52:03.164  8900  8900 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4800)
01-12 10:52:03.164  8900  8900 E AndroidRuntime: 	... 8 more
01-12 10:52:10.765  8974  8974 E AndroidRuntime: FATAL EXCEPTION: main
01-12 10:52:10.765  8974  8974 E AndroidRuntime: Process: com.nextcloud.android.beta, PID: 8974
01-12 10:52:10.765  8974  8974 E AndroidRuntime: java.lang.RuntimeException: Unable to create application com.owncloud.android.MainApp: android.database.sqlite.SQLiteException: duplicate column name: rich_workspace (code 1): , while compiling: ALTER TABLE filelist ADD COLUMN rich_workspace TEXT
01-12 10:52:10.765  8974  8974 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4803)
01-12 10:52:10.765  8974  8974 E AndroidRuntime: 	at android.app.ActivityThread.access$1600(ActivityThread.java:157)
01-12 10:52:10.765  8974  8974 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1417)
01-12 10:52:10.765  8974  8974 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-12 10:52:10.765  8974  8974 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
01-12 10:52:10.765  8974  8974 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5530)
01-12 10:52:10.765  8974  8974 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-12 10:52:10.765  8974  8974 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:734)
01-12 10:52:10.765  8974  8974 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:624)
01-12 10:52:10.765  8974  8974 E AndroidRuntime: Caused by: android.database.sqlite.SQLiteException: duplicate column name: rich_workspace (code 1): , while compiling: ALTER TABLE filelist ADD COLUMN rich_workspace TEXT
01-12 10:52:10.765  8974  8974 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
01-12 10:52:10.765  8974  8974 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:893)
01-12 10:52:10.765  8974  8974 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:504)
01-12 10:52:10.765  8974  8974 E AndroidRuntime: 	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:726)
01-12 10:52:10.765  8974  8974 E AndroidRuntime: 	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
01-12 10:52:10.765  8974  8974 E AndroidRuntime: 	at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
01-12 10:52:10.765  8974  8974 E AndroidRuntime: 	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1784)
01-12 10:52:10.765  8974  8974 E AndroidRuntime: 	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1715)
01-12 10:52:10.765  8974  8974 E AndroidRuntime: 	at com.owncloud.android.providers.FileContentProvider$DataBaseHelper.onUpgrade(FileContentProvider.java:2092)
01-12 10:52:10.765  8974  8974 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:256)
01-12 10:52:10.765  8974  8974 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)
01-12 10:52:10.765  8974  8974 E AndroidRuntime: 	at com.owncloud.android.providers.FileContentProvider.query(FileContentProvider.java:471)
01-12 10:52:10.765  8974  8974 E AndroidRuntime: 	at android.content.ContentProvider.query(ContentProvider.java:1017)
01-12 10:52:10.765  8974  8974 E AndroidRuntime: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:238)
01-12 10:52:10.765  8974  8974 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:500)
01-12 10:52:10.765  8974  8974 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:442)
01-12 10:52:10.765  8974  8974 E AndroidRuntime: 	at com.owncloud.android.datamodel.UploadsStorageManager.getUploads(UploadsStorageManager.java:289)
01-12 10:52:10.765  8974  8974 E AndroidRuntime: 	at com.owncloud.android.datamodel.UploadsStorageManager.getFailedUploads(UploadsStorageManager.java:368)
01-12 10:52:10.765  8974  8974 E AndroidRuntime: 	at com.owncloud.android.utils.FilesSyncHelper.restartJobsIfNeeded(FilesSyncHelper.java:194)
01-12 10:52:10.765  8974  8974 E AndroidRuntime: 	at com.owncloud.android.MainApp.initSyncOperations(MainApp.java:492)
01-12 10:52:10.765  8974  8974 E AndroidRuntime: 	at com.owncloud.android.MainApp.onCreate(MainApp.java:309)
01-12 10:52:10.765  8974  8974 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
01-12 10:52:10.765  8974  8974 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4800)
01-12 10:52:10.765  8974  8974 E AndroidRuntime: 	... 8 more
01-12 10:52:11.892  9001  9001 E AndroidRuntime: FATAL EXCEPTION: main
01-12 10:52:11.892  9001  9001 E AndroidRuntime: Process: com.nextcloud.android.beta:crash, PID: 9001
01-12 10:52:11.892  9001  9001 E AndroidRuntime: java.lang.RuntimeException: Unable to create application com.owncloud.android.MainApp: android.database.sqlite.SQLiteException: duplicate column name: rich_workspace (code 1): , while compiling: ALTER TABLE filelist ADD COLUMN rich_workspace TEXT
01-12 10:52:11.892  9001  9001 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4803)
01-12 10:52:11.892  9001  9001 E AndroidRuntime: 	at android.app.ActivityThread.access$1600(ActivityThread.java:157)
01-12 10:52:11.892  9001  9001 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1417)
01-12 10:52:11.892  9001  9001 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-12 10:52:11.892  9001  9001 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
01-12 10:52:11.892  9001  9001 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5530)
01-12 10:52:11.892  9001  9001 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-12 10:52:11.892  9001  9001 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:734)
01-12 10:52:11.892  9001  9001 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:624)
01-12 10:52:11.892  9001  9001 E AndroidRuntime: Caused by: android.database.sqlite.SQLiteException: duplicate column name: rich_workspace (code 1): , while compiling: ALTER TABLE filelist ADD COLUMN rich_workspace TEXT
01-12 10:52:11.892  9001  9001 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:179)
01-12 10:52:11.892  9001  9001 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
01-12 10:52:11.892  9001  9001 E AndroidRuntime: 	at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
01-12 10:52:11.892  9001  9001 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:500)
01-12 10:52:11.892  9001  9001 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:442)
01-12 10:52:11.892  9001  9001 E AndroidRuntime: 	at com.owncloud.android.datamodel.UploadsStorageManager.getUploads(UploadsStorageManager.java:289)
01-12 10:52:11.892  9001  9001 E AndroidRuntime: 	at com.owncloud.android.datamodel.UploadsStorageManager.getFailedUploads(UploadsStorageManager.java:368)
01-12 10:52:11.892  9001  9001 E AndroidRuntime: 	at com.owncloud.android.utils.FilesSyncHelper.restartJobsIfNeeded(FilesSyncHelper.java:194)
01-12 10:52:11.892  9001  9001 E AndroidRuntime: 	at com.owncloud.android.MainApp.initSyncOperations(MainApp.java:492)
01-12 10:52:11.892  9001  9001 E AndroidRuntime: 	at com.owncloud.android.MainApp.onCreate(MainApp.java:309)

01-12 10:52:11.892  9001  9001 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
01-12 10:52:11.892  9001  9001 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4800)
01-12 10:52:11.892  9001  9001 E AndroidRuntime: 	... 8 more`

**Comment by AndyScherzinger** [comment]
cc @tobiasKaminsky for db upgrade issue on dev build

**Comment by Valdnet** [comment]
@ezaquarii @AndyScherzinger @tobiasKaminsky Version dev-20200115 5849ba2 now works correctly. Thanks 😉.
