### ISSUE TITLE
Password transmitted in cleartext on every request

### ISSUE THREAD

**Issue by neonknight** [nextcloud/android#5163]
### Steps to reproduce
1. add account with server (that only supports https) using connection method http://
2. sniff traffic
3. see your password...

### Expected behaviour
- instead of transferring the password on any request, use http sessions. This way an attacker can still take over the current session, but does not necessarily get to read the password.
- if user tries to connect to unencrypted server (http://) print a warning, at least while user is setting up the account.
- if server always redirects to https (re)configure automatically reconfigure as secure connection, at least while user is setting up the account.
- honour Content-Security-Policy headers.

### Actual behaviour
- if configured by user, app connects to server using unencrypted http connection and sends auth data on any request.
- app receives 301/302 redirect to https
- actual data is being transferred securely

### Environment data
Nextcloud app version: 3.9.0
Nextcloud server version: 16.0.5
- Server redirects any request to http to https (RewriteRule ^(.*)$ https://%{SERVER_NAME}$1 [L,R])
- Server sends Content-Security-Policy header

**Comment by AndyScherzinger** [comment]
cc @tobiasKaminsky @rullzer for feedback

**Comment by tobiasKaminsky** [comment]
http is known to be unsecure by design. Using sessions would only delay the exposure of the password.
So this can only be "fixed" by using https.
