### ISSUE TITLE
Synchronize a big folder causes some bugs

### ISSUE THREAD

**Issue by Shagequi** [nextcloud/android#5176]
Hi,

When you want to synchronize a folder (of 150GB+) manually (by click on contextual menu of the folder, then "Synchronize"), after ≃ 30s there is a "Nextcloud isn't responding" message asking for killing/keeping the process.

1) Why does the app show a message asking to kill or continue the process, if this one is able to finish/crash without any "damage" (because it's an async task) ?
2) Why does the app allow to synchronize 150GB+ if the device doesn't have 150GB of memory ?
3) Why cannot we abort the operation ?

Thank you for your answers :)

**Comment by AndyScherzinger** [comment]
My 2 cents

1. it shouldn't, like you said it should: just do this in the background
2. it shouldn't, like you said it should: check the available space first and inform the user if unable to do so
3. we should be able to abort (while this is a quite large effort to implement; not there/planned yet)

cc @tobiasKaminsky

**Comment by Shagequi** [comment]
Thank you @AndyScherzinger for your answers :D
I think I should create 3 different issues, but I wanted to clarify this point with you before creating these issues.

Another question @AndyScherzinger do you go to the contributor week ?

**Comment by AndyScherzinger** [comment]
> do you go to the contributor week ?

Unfortunately, no 😭  but @tobiasKaminsky will be there. I'll have to work (day job) 😢

**Comment by Shagequi** [comment]
Three issues have been created : 
https://github.com/nextcloud/android/issues/5177
https://github.com/nextcloud/android/issues/5178
https://github.com/nextcloud/android/issues/5179

I close this one
