### ISSUE TITLE
[3.10 RC2] Dark Mode upload picker doesn't look right

### ISSUE THREAD

**Issue by szaimen** [nextcloud/android#5188]
### Steps to reproduce
1. enable dark mode on 3.10 RC2
2. share a file from another app to nextcloud
3. see the upload picker

### Expected behaviour
there shouldn't be white dividing lines:

### Actual behaviour
there are white dividing lines.

### Environment data
Android version:
Android 10
Device model: 
SGS10e
Stock or customized system:
Stock
Nextcloud app version:
3.10 RC2
Nextcloud server version:
17.0.2

### Look at this screenshot
<img width="540" alt="Screenshot_20200114-094253_Nextcloud" src="https://user-images.githubusercontent.com/42591237/72341237-0990ce00-36ca-11ea-9215-5df20c4b2960.png">

**Comment by szaimen** [comment]
Actually, I cannot upload files here, but the UI doesn't show that!
a comparable issue to: https://github.com/nextcloud/android/issues/5124

**Comment by AndyScherzinger** [comment]
Nice catch, the divider is actually light gray and also present in the light theme, so the divider needs to be removed in general.

**Comment by szaimen** [comment]
@AndyScherzinger have you seen my comment below?
https://github.com/nextcloud/android/issues/5188#issuecomment-574133506

**Comment by AndyScherzinger** [comment]
> I could open a new issue for that...

Yes please, since it is a different part of the app/implementation than #5124 - Thanks for your reports 🙏

**Comment by szaimen** [comment]
> > I could open a new issue for that...
> 
> Yes please, since it is a different part of the app/implementation than #5124 - Thanks for your reports 🙏

I opened https://github.com/nextcloud/android/issues/5190 for that 👍
