### ISSUE TITLE
[Upload Picker] Visualize if upload is forbidden (disable/gray-out button)

### ISSUE THREAD

**Issue by szaimen** [nextcloud/android#5190]
### Steps to reproduce
1. share a file from another app with the nextcloud app
2. open a folder where the upload is forbidden

### Expected behaviour
I should see visually, that the upload is forbidden.

### Actual behaviour
nothing is visually different to a normal folder where the upload is allowed. (only the upload button doesn't work here)

### Environment data
Android version:

Android 10
Device model: 
SGS10e
Stock or customized system:
Stock
Nextcloud app version:
3.10 RC2
Nextcloud server version:
17.0.2
### Screenshot
Here is a Screenshot from a location where the upload is forbidden:
![image](https://user-images.githubusercontent.com/42591237/72352482-9fd0ee00-36e2-11ea-91c3-8f23a2f13142.png)

### Possible solution
Maybe it could also get solved by what @jancborchardt has suggested in https://github.com/nextcloud/android/issues/5124#issuecomment-573873566:
> Let’s make it muted, so it’s clear it’s disabled, and additionally when you tap it, there should be a toast (or something comparable) stating why it is disabled. In the server we say:
> 
> > You don’t have permission to upload or create files here

**Comment by AndyScherzinger** [comment]
cc @tobiasKaminsky as a follow-up to the fab-gray-out PR/issue 😃
