### ISSUE TITLE
Crash When trying to add whatsapp folder to sync

### ISSUE THREAD

**Issue by dab911** [nextcloud/android#5191]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
@dab911 can you please post the error log / log cat? Else we'll need to close this issue.

**Comment by dab911** [comment]
Hello Andy, 

Where is located the log on Android ? 

cdt 

Le 2020-01-14 16:06, Andy Scherzinger a écrit : 

> @dab911 [1] can you please post the error log / log cat? Else we'll need to close this issue. 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or unsubscribe [3].

 

Links:
------
[1] https://github.com/dab911
[2]
https://github.com/nextcloud/android/issues/5191?email_source=notifications&amp;email_token=ABZXR4ZESTQU3FV4TFHGBL3Q5XIF3A5CNFSM4KGUKBX2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEI45Z5Q#issuecomment-574217462
[3]

**Comment by AndyScherzinger** [comment]
Hi @dab911,

when the app crashes it should actually show a pop-up with this information. Else the app should show you a log settings entry within the apps settings screen (via the main menu of the app)
