### ISSUE TITLE
Some design refresh

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/android#5207]
These are some possible design polishing items we could do – some more easy and some more difficult. :) What we assume to be quick wins are marked with ⚡

(No mockups yet as it’s just a quick list, and as it can mostly be seen by just checking out Gmail and Google Drive.)

- [x]  **⚡ Splash screen polishing:** During the splash screen, the status bar on top and the controls bar on the bottom is black. Can we make it blue as well? Will make it look much less boxed in. :) https://github.com/nextcloud/android/pull/5229
- [x] **⚡ Colorless header bar:** The new material design doesn’t have colored header bars or status bars. The branding would only be via FAB and folder icons, which is fine. :)
- [x] **⚡ Slight rounding of the file previews:** Some very slight rounded corners on the image file previews just like we do on server, makes it appear much friendlier. https://github.com/nextcloud/android/pull/5231
- [x] **Get rid of 3-dot menu in top right:** The "Refresh account" option can go away (right?) :D. The Sort as well as Grid view can go below the search field in a specific row, just like Google Drive does.
  - [x] Add sort / switch list view to ReceiveExternalFiles and Trashbin
- [x] **Account switcher in top right:** Again, same as Gmail and other Google Apps, we show the avatar in the top right instead of the drawer.

- [x] **Search bar open by default:** Just like Gmail as well, the bar could be there by default and say **Search in Nextcloud**. When you are in a subfolder, it would change "Nextcloud" to the subfolder name
  - [x] use new header in subfolders
- [x] **⚡ Use bottom sheet for actions menu:** Instead of the small popover we can use the proper bottom sheet which is nicely reachable with the thumb. It should of course show the file in question on top so you know what the action will be carried out on.
- [x] **⚡ Transparent bottom bar:** The Home/Back/Switcher bar on the bottom currently has a black background. If we make it transparent like in Gmail, it will look much lighter and like "more space for your own stuff"
- [x] **⚡ Hide header bar on scrolling:** In Gmail and Material Files (from F-Droid) for example, when you scroll down, the whole header bar hides, and shows again when you scroll up a bit. This gives you a lot of space for your files and is really nice.
- [x] centralize fonts, e.g. difference between switch account popup and drawer
- [x] FirstRunActivity (and follow up while login): white navigation bar, should be blue
- [x] header in e.g. Activities/Notifications looks old, what can we do about it?
- [x] add new header to trash bin, sort is then a filter as sever does not support searching in trash bin
- [x] preview image: white navigation bar

Discussed with @tobiasKaminsky @Shagequi, cc @AndyScherzinger :) What do you think? Other quick things?

**Comment by AndyScherzinger** [comment]
Sounds good (all of it). Only thing a found:
 > **Transparent bottom bar:** The Home/Back/Switcher bar on the bottom currently has a black background. If we make it transparent like in Gmail, it will look much lighter and like "more space for your own stuff"

the bottom bar is actually white in GMail, not transparent.

**Comment by mario** [comment]
@AndyScherzinger where do you see it's white? Looks at best like it's white with translucency set on pre-Android 10. On Android 10 it looks transparent with some automatic adaptation.

**Comment by AndyScherzinger** [comment]
On OP3T, Lineage 16. / Android 9:
![Screenshot_20200115-133726_Gmail](https://user-images.githubusercontent.com/1315170/72434697-8db38600-379c-11ea-82cf-72dcd669430f.png)

**Comment by mario** [comment]
Fun stuff.

**Comment by AndyScherzinger** [comment]
Semi-transparentcy is fine with me (the Google News app has that for the bottom bar). So I am fine with the statement/decision, just wanted to clearify that it might not look as described got GMail on all devices.

**Comment by jancborchardt** [comment]
Hmm, guess it’s device- or version-dependent then. :) The point is: Let’s make the bottom bar semi-transparent. :crystal_ball:

**Comment by AndyScherzinger** [comment]
Yes let's do it, btw, the bar is semi transparent now in Gmail (so a bug within their app...)

**Comment by Shagequi** [comment]
I would suggest : 
- Add an unique "in-notification" file transfer status with action buttons

**Comment by JorisBodin** [comment]
Hello,

After discussion with @tobiasKaminsky and @jancborchardt, here are our mokups to refresh the current design.
The iOS and Android apps will be aligned designwise.
https://infomaniak.invisionapp.com/share/3VWA11OK9E8#/410365622_App_Nextcloud_-_Drive_2

In the first step, we will not implement the bottom bar.
In the new design only the header bar is going away, the rest should still be themed.

**Comment by AndyScherzinger** [comment]
@JorisBodin Mockup looks great, beware that @tobiasKaminsky started working on this (a while ago), see #5290 so best would be to collaborate on that branch and looping in @tobiasKaminsky ❤️

**Comment by szaimen** [comment]
Hi,

I really like the new design but I would argue that the following proposal is a better arrangement of the bottom buttons, because especially the most important files button is now by far better reachable for right-handed people (apparently I have switched the order from "left to right" to "from right to left"):

## My Proposal:
![image](https://user-images.githubusercontent.com/42591237/80803610-1bcc4480-8bb3-11ea-914b-2bf1e3baf833.png)

## Current Prototype:
![image](https://user-images.githubusercontent.com/42591237/80803643-3c949a00-8bb3-11ea-9a62-e62eb812d50e.png)

**Comment by jancborchardt** [comment]
@szaimen it is a default that the main entry is always on the left. If we go with a bottom bar, then the order as in the mockup is fine (possibly having "Notifications" instead of "Photos" though).

**Comment by szaimen** [comment]
@jancborchardt I am all in for defaults that follow the function but that is clearly a standard that doesn't make sense for 90% of the people who want to use the app on a daily basis.

But +1 for this idea:
> If we go with a bottom bar, then (possibly having "Notifications" instead of "Photos" though).

**Comment by jancborchardt** [comment]
> a standard that doesn't make sense for 90% of the people

Basically all apps using this means doing it any different would _not_ make sense for 90% of the people.

Let’s not discuss this to death, we are first going without a bottom bar for Android anyway.

**Comment by Shagequi** [comment]
@szaimen @jancborchardt Of course, we can look with the person who designed the mock-ups and integrate it into a debate in another (new) issue ^_^

**Comment by Shagequi** [comment]
Comment from @jancborchardt here about mockups : https://github.com/nextcloud/android/pull/6029#issuecomment-626173398

> sorry for the miscommunication. The folder icon size is great in the grid view as in the mockup – but for the list view, the current folder icon size is better, so we should keep that.

> I checked the current mockup again to make sure there’s no inconsistencies, and 3 more things came up (which I gave as feedback before as well):

>  The search requires 2 characters minimum – that is unnecessarily restrictive, instead the current view should be filtered first for quick results.
    The "Menu" navigation sliding in from the right but then sticking to the left is strange. Would look nicer if it is a full view list.
    The text in the app header is not left-aligned with the file names down below. (Compared to how it is in the current app.)

> The mockup also doesn’t have other details like left/right animation for going into folders, so I didn’t assume it was so set in stone but a basis for what we’ll work on. Sorry if that was the wrong assumption, and hope the comment clears it up? :)

**Comment by JorisBodin** [comment]
Hello @jancborchardt 
The "Menu" navigation, doesn't change, until we have the bottom navigation bar. And it's fullscreen view. It's a mock-up problem.

> The text in the app header is not left-aligned with the file names down below. (Compared to how it is in the current app.)

This is the native android display. We can hack it if you want.

**Comment by jancborchardt** [comment]
> The "Menu" navigation, doesn't change, until we have the bottom navigation bar. And it's fullscreen view. It's a mock-up problem.

Cool, no worries from my side. Just wanted to make sure as the mockup is sometimes cited as the gold standard, which it often can not be for these reasons, and others such as some parts not being covered by it. (Which again, is fine by me.)



> > The text in the app header is not left-aligned with the file names down below. (Compared to how it is in the current app.)
> 
> This is the native android display. We can hack it if you want.

Not very important, but it’s a nice detail. Some apps seem to align it, and it does look better.

**Comment by JorisBodin** [comment]
> Not very important, but it’s a nice detail. Some apps seem to align it, and it does look better.

Maybe it's the content is align at the bar and not the opposite?

**Comment by jancborchardt** [comment]
> > Not very important, but it’s a nice detail. Some apps seem to align it, and it does look better.
> 
> Maybe it's the content is align at the bar and not the opposite?

Not sure, but if we ignore the content we can also say that the search text should be aligned with the header text. That means either moving the search text to the left (which would look nice) or moving the header text further to the right (which takes away more space for letters and looks off).

**Comment by szaimen** [comment]
@Shagequi what about the buttom appbar which is visible in the mockups? I haven't seen that on the list https://github.com/nextcloud/android/issues/5207#issuecomment-617270183

**Comment by Shagequi** [comment]
@szaimen it''ll be implemented later, if I remember @jancborchardt wanted to do this redesign in two phases : 
1- Consists to apply all the above check list
2- Consists to implement the bottom app-bar 

@JorisBodin may confirm this.

**Comment by jancborchardt** [comment]
Yep, as we are not sure about the bottom app-bar yet, we wanted to first start out with all the other great improvements to not have that one thing block the rest. :)

**Comment by Shagequi** [comment]
The translucid appbar/navigationbar is ... not too simple, 

We need to apply a theme parameter : 
```
<item name="android:windowTranslucentNavigation">true</item>
``` 
Which needs to isolate the "Photos" in a specific view, with a particular theme.
But this is already deep-rooted in FileDisplayActivity (with many buses and other technical complications)... and the the to invest is too long for a "small result" 

@jancborchardt Do you absolutely want a translucid appbar/appnavigation for medias/photos activity ?

**Comment by tobiasKaminsky** [comment]
As the first major round of updates is done (awesome work @Infomaniak), I will go now through the app and collect missing todos and add them in first post.

**Comment by tobiasKaminsky** [comment]
Feel free to add something if you find it.
After this "second" round, we then should close this issue and create individual issues, if something is still "wrong".

**Comment by tobiasKaminsky** [comment]
As nothing more popped up so far, I will transfer the remaning ones as new issues and close this one.
Please open any issues, related to new design, as "bug" so that we make sure to fix them for next stable.

**Comment by jancborchardt** [comment]
Really great work everyone! :)
