### ISSUE TITLE
AutoUpload Photo name pattern

### ISSUE THREAD

**Issue by FlamingFlowair** [nextcloud/android#521]
### Actual behaviour
-Tell us what happens
Every picture is renamed when uploaded to nextcloud like 20160107-202521.jpg

### Expected behaviour
-Tell us what should happen
 Every picture is renamed when uploaded to nextcloud.
The name pattern should be customizable like Y-m-d_H.M.S or Y or d_s

I'm from dropbox and my pictures names are inconsistent which is annoying.
No big deal though, you probably have more important things to do ;)

**Comment by tobiasKaminsky** [comment]
There was a discussion many months ago regarding this topic.
The conclusion then was that this should handle the camera app.
But I am open for discussion.
With our new "auto upload" we could add this as an extra option which can be enabled on each folder separately.

**Comment by FlamingFlowair** [comment]
No more discussion needed, the point is clear and it's your choice to implement it or not with the new auto upload version.
I apologise, I think i only searched this in the open issues that's why i created a new issue for something that has already been discussed before.
Thanks for your answer.
:)

**Comment by CNeutron** [comment]
I'd really appreciate a rename feature.
Sonys Xperia Cameras use a counter which starts at 0001 and counts +1 of the file.

My Problem is that if I use the delete (or move) option after the auto upload the next picture will have the exact same name as the one just uploaded.

**Comment by joshtrichards** [comment]
Let's consolidate this into #10103 since that's where the activity is.
