### ISSUE TITLE
Since 3.10.0, app is excluded from recent/current apps

### ISSUE THREAD

**Issue by Shagequi** [nextcloud/android#5213]
Hi,
Since the 3.10.0 version, during the first launch/connection process only,  the app is excluded from the "recent apps".
Here is an example of "recent apps" view : 
![HFCji](https://user-images.githubusercontent.com/7050479/72515331-00316e00-3850-11ea-9aa2-d7ef6c6d7399.png)

Here is the steps to reproduce :
1. Disconnect your account(s) in order to retreive the "connection status" process OR uninstall and reinstall the app
2. During the process, try to go on another app, like an Authenticator or similar app
3. Try to return in Nextcloud app through the "recent apps" view (by clicking on bottom-bar button) 
**You'll see that you're unable to return to the app through this view.**

**Comment by Shagequi** [comment]
@JorisBodin

**Comment by JorisBodin** [comment]
I find, this merge create this bug : https://github.com/nextcloud/android/commit/d7d1c475aebb7b7e92b98c3d36dbf66c7a244d86

The _finish();_ at line 184

I make MR

**Comment by Shagequi** [comment]
Fixed by : https://github.com/nextcloud/android/pull/5218
