### ISSUE TITLE
Dev version: use commit hash instead of master

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#5215]
For having reliable builds, that can also be build weeks after the coresponding daily, we have to use commit hash of library instead of master-snapshot.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky so how to you update master? By merging the commit-hash version as a separate PR whenever you merge something in the lib project? Especially for lib changes that don't impact its API

**Comment by tobiasKaminsky** [comment]
My idea was to use this only for dev version, so that eg tag dev-20200120 points not to master-SNAPSHOT, but e.g. 2423424232 (commit hash).

Problematic is that we cannot add this to master.
What about:
- creating a new branch "dev"
- on every new dev version
  - rebase master into dev
  - bump versionName/Code
  - change library to latest commit hash
  - commit

This way we would have no real diff between master and dev, except for versionName/Code and library, which is what we want

**Comment by AndyScherzinger** [comment]
Sounds like a plan 👍
