### ISSUE TITLE
"Upload failed" message should be removed when uploads are succesful

### ISSUE THREAD

**Issue by OlivierS1** [nextcloud/android#522]
### Actual behaviour
-Tell us what happens
This is more of an improvement, but can also be considered a bug.
Let's say Auto Upload or manual uploads are in progress. Then something wrong happens and the file being uploaded is stopped in it's track. Nextcloud app then output a "Failed updload" message, and it is the way it is supposed to happen. However, with the new retry mechanism, upload will eventually resume and all standing by uploads should complete. 
Upon completion, if all the files have been uploaded, then the "Failed upload" should be removed from the list, when the user log back on the phone.
I think the result should be transparent.

### Expected behaviour
-Tell us what should happen
When an upload fails and user is not logged-in the phone, then the message "Failed upload" is added to the status messages for the user to review during login.
However, if the transfer finally complete and everything is is order, then this "Failed upload" message should be removed from the status task. Maybe the message should update the status message saying maybe "There were some failed uploads, but everything has been uploaded" This is a mouthful, but something more concise should work too. If we go this route, then I could possibly think about when the uploads last took place, but I think this is too much information.

 
### Steps to reproduce
1. 
2. 
3. 

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

**Comment by ferdiga** [comment]
1.4 version
the failed uploads are marked with "Unknown Error"
obviously not very helpful to take actions.
I think you get it if the upload already succeeded.

**Comment by mario** [comment]
Is this still the case with the newest beta app?

https://github.com/nextcloud/android/raw/beta/apks/latest.apk

@ferdiga we're working on improving error messages.

**Comment by ferdiga** [comment]
currently I do not have issues with android 1.4.1 and nextcloud 10.0.2

**Comment by joshtrichards** [comment]
Great write-up, @OlivierS1! Let's consolidate this with #3234.

@ferdiga Tracking that in #260.
