### ISSUE TITLE
the 'Stream with" option on video files doesn't work with the popular VLC for Android app

### ISSUE THREAD

**Issue by ghost** [nextcloud/android#5221]
### Steps to reproduce
1. Connect to a NextCloud server with the NextCloud Android app
2. Navigate to a video file
3. Select the 'stream with...' option on that file and choose VLC player since the internal player doesn't support that many video formats

### Expected behaviour
- VLC should stream the selected file.

### Actual behaviour
- VLC doesn't stream the file, instead of the file's name it displays a long illegible string. The spinning icon indicates that the app tries to load something, but it doesn't change.

Meanwhile, VLC works just fine in streaming files selected via a different WebDAV app (example: Fx file explorer). That tells me that the WebDAV connection works fine and that VLC player does so, too.

### Environment data
Android version:
Android Version: 9

Device model: 
Phone: Xiaomi POCO F1 (POCO F1)

Stock or customized system:
Rom: lineage_beryllium-userdebug 9 

Nextcloud app version:
3.9.2

Nextcloud server version:
NextCloud17.0.2.1
(on a raspberry pi 4b with NextCloudPi 1.20.1)

**Comment by szaimen** [comment]
Ping

**Comment by tobiasKaminsky** [comment]
Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

**Comment by szaimen** [comment]
Ping

**Comment by tobiasKaminsky** [comment]
@rullzer there are now quite a lot streaming issues…
Do you have an idea how we can tackle down the root cause of them?

**Comment by ezaquarii** [comment]
On Tue, Apr 28, 2020 at 02:51:24AM -0700, Tobias Kaminsky wrote:
> @rullzer there are now quite a lot streaming issues…
> Do you have an idea how we can tackle down the root cause of them?

@rullzer
@tobiasKaminsky

Test account could help, perhaps?

**Comment by tobiasKaminsky** [comment]
Can you create us a test account, test if the problem occurs also there and if so send the credentials to tobias at nextcloud dot com with a reference to this issue?

**Comment by szaimen** [comment]
> Can you create us a test account, test if the problem occurs also there and if so send the credentials to tobias at nextcloud dot com with a reference to this issue?

The bug occurs with the testaccount, as well.
The e-mail was sent to you 👍

**Comment by tobiasKaminsky** [comment]
@szaimen I uploaded two files. Avi is not working for me, but mp4 is working.
However it takes ~30s to get a video…

**Comment by szaimen** [comment]
> @szaimen I uploaded two files. Avi is not working for me, but mp4 is working.
> However it takes ~30s to get a video…

Yes, it is really slow and not a problem of my server since it plays fine in the browser.

Why doesn't the avi file stream with vlc? it shouldn't be a codec problem since vlc support nearly all codecs. So I would guess this is a problem of the nextcloud app?

Where you able to run logcat to get some protocolls while trying the stream with option?

BTW: The same problem occus if the file is already downloaded to the android app and if I click on stream with vlc afterwards, which should really work since it is already locally available. So definitely a nextcloud app bug... The open with vlc option works fine after downloading.

**Comment by szaimen** [comment]
Ping

**Comment by szaimen** [comment]
Ping

**Comment by szaimen** [comment]
Ping

**Comment by MrJaypot** [comment]
Piiiiing

**Comment by citizenserious** [comment]
Ping

**Comment by tobiasKaminsky** [comment]
Do you have any external storages?

**Comment by citizenserious** [comment]
> 
> 
> Do you have any external storages?

Yes, my storage path is set to internal though.

**Comment by tobiasKaminsky** [comment]
There is an experimental switch to another video player in https://github.com/nextcloud/android/pull/8132#issuecomment-792722526

This apk can be installed in parallel. 
It would be great if you can give this a test, if it helps in your scenario.

**Comment by tobiasKaminsky** [comment]
> There is an experimental switch to another video player in [#8132 (comment)](https://github.com/nextcloud/android/pull/8132#issuecomment-792722526)
> 
> This apk can be installed in parallel.
> It would be great if you can give this a test, if it helps in your scenario.

**Comment by szaimen** [comment]
@tobiasKaminsky this issue is about the problem that streaming with VLC player doesn't work. The internal video player from your linked PR does work for me.

**Comment by tobiasKaminsky** [comment]
Can you test this with another server?

**Comment by szaimen** [comment]
I think it is due to the usage of the external storage app (with local storage). So switching the server won't change anything because it is no limitation here on the network or configuration side.
But when #8132 gets merged, I no longer need the stream with option and it will be fine for me.

**Comment by tobiasKaminsky** [comment]
> I think it is due to the usage of the external storage app (with local storage)

This is server side?
Then also switching via #8132 will not help, as the server implementation right now does not work with external storage.
If it is really due to server, please then report an issue on server.

(please do not remove the label all the time)

**Comment by szaimen** [comment]
> This is server side?

Yes

> Then also switching via #8132 will not help, as the server implementation right now does not work with external storage.

Thats incorrect as I've tested the apk with this configuration and video streaming worked perfectly!
