### ISSUE TITLE
text from Readme.md not shown properly when dark theme selected

### ISSUE THREAD

**Issue by elpraga** [nextcloud/android#5232]
### Steps to reproduce
1. Select dark theme
2. try to read the preview from Readme.md
3. first few lines will not be visible

### Expected behaviour
- I expect the lines to be visible

### Actual behaviour
- they are dark and not visible

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by elpraga** [comment]
![Screenshot_2020-01-18-15-54-47-084_com nextcloud client](https://user-images.githubusercontent.com/13814570/72667366-6dddc580-3a1b-11ea-835d-44da69ed6fce.jpg)
![Screenshot_2020-01-18-15-56-52-857_com nextcloud client](https://user-images.githubusercontent.com/13814570/72667370-7930f100-3a1b-11ea-9934-ace10cf3c126.jpg)

**Comment by AndyScherzinger** [comment]
Cc @tobiasKaminsky, since this is related to rich work spaces I guess.

**Comment by AndyScherzinger** [comment]
Hmm, @elpraga are by any chance the first few lines explicetely coloered black? (Just asking because for me they are just colored fine and also rendered fine.

**Comment by elpraga** [comment]
No Andy. The while text us the same.

Will provide more info later

**Comment by AndyScherzinger** [comment]
Nevermind, I can reproduce it with latest master :(

**Comment by AndyScherzinger** [comment]
PR is #5496
