### ISSUE TITLE
Text unreadable In some elements (black on black) when using dark or follow system themes in 3.10.0

### ISSUE THREAD

**Issue by elpraga** [nextcloud/android#5242]
### Steps to reproduce
1. Use a dark theme
2. try to rename a file or a folder
3. you cannot see the text once unselected (black font on a black background)

### Expected behaviour
- I can see the text

### Actual behaviour
-=

### Environment data
Android version:9.0

Device model: 

Stock or customized system:

Nextcloud app version:
3.10.0
Nextcloud server version:
18.0
#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by elpraga** [comment]
![Screenshot_2020-01-19-16-16-03-483_com nextcloud client~01](https://user-images.githubusercontent.com/13814570/72683412-64199800-3ad7-11ea-90d2-c319c5bc22e1.jpg)

**Comment by AndyScherzinger** [comment]
cc @tobiasKaminsky since it should be easy to fix :)

**Comment by elpraga** [comment]
![Screenshot_20200123-120557](https://user-images.githubusercontent.com/13814570/73136484-6ab38c80-404e-11ea-99a3-b6beb4012192.png)

**Comment by elpraga** [comment]
Some other elements use incorrect colours

**Comment by elpraga** [comment]
I have just noticed that: follow system and dark themes are not the same.

Dark theme: (text hard to read)
![Screenshot_2020-01-29-13-03-12-998_com nextcloud client~2](https://user-images.githubusercontent.com/13814570/73355321-38956b00-4298-11ea-9daf-82fdfdbec11a.jpg)

Follow system: (OK)
![Screenshot_2020-01-29-13-03-39-784_com nextcloud client~2](https://user-images.githubusercontent.com/13814570/73355388-5793fd00-4298-11ea-9b0b-3f745b42cb79.jpg)
