### ISSUE TITLE
Data not visible in Apps

### ISSUE THREAD

**Issue by corincorvus** [nextcloud/android#525]
### Actual behaviour
- Path not normally visible for Apps like Quickpic, Gallery, Wallpaper Changer, Poweramp and more
- Pictures and Music not visible. Only manual add is working
- Actual data path: /sdcard/Android/data/com.nextcloud.client/files/nextcloud/Account/Data

### Expected behaviour
Need to change the Path for the Data directory outside of "Android" folder
 
### Steps to reproduce
1. Sync Media Data
2. Open Quickpic or Gallery
3. You only see the Pictures, if u make visible "invisible Data"

### Environment data
Android version: 6.0

Device model: ASUS Zenpad 3S 10, Samsung Galaxy Note 3, Samsung Galaxy S7 (Girlfriend)

Stock or customized system: Asus Stock, Note 3 Custom (Cyanogenmod), S7 Stock

Nextcloud app version: 1.4.0

Nextcloud server version: 11.0.0 stable

### Logs
No Error Logs from Server and Client

**Comment by tobiasKaminsky** [comment]
This is done already in dev and master and will be in text version.
