### ISSUE TITLE
Drawer shouldn't be swipeable in Video Preview

### ISSUE THREAD

**Issue by Shagequi** [nextcloud/android#5251]
Hi,
All is in the title, I just create this issue for a better "issues management".
It's relative to this : https://github.com/nextcloud/android/issues/4864 but with videos :)

I'll work on it today

**Comment by Shagequi** [comment]
Fixed in : https://github.com/nextcloud/android/pull/5252

@AndyScherzinger if you want to review it :D

**Comment by AndyScherzinger** [comment]
Review done and merged! 👍 

Nice work @Shagequi 🎉
