### ISSUE TITLE
Do not recursively AutoUpload the same photo multiple times

### ISSUE THREAD

**Issue by marmeladema** [nextcloud/android#526]
### Actual behaviour
- Save a picture from silence (for example) to Pictures/smssecure-2017-01-07-010203.jpg
- AutoUpload synchronize the picture in InstantUpload/Pictures/2017/02/smssecure-2017-01-07-010203.jpg
- Browse the picture, it gets downloaded to InstantUpload/Pictures/smssecure-2017-01-07-010203.jpg/2017/01/smssecure-2017-01-07-010203.jpg (weird right?)
- AutoUpload synchronize the picture in InstantUpload/Pictures/smssecure-2017-01-07-010203.jpg/2017/01/smssecure-2017-01-07-010203.jpg
- Browse the picture, it gets downloaded to InstantUpload/Pictures/smssecure-2017-01-07-010203.jpg/2017/01/smssecure-2017-01-07-010203 (2).jpg
- ...

### Expected behaviour
- Save a picture from silence (for example) to Pictures/smssecure-2017-01-07-010203.jpg
- AutoUpload synchronize the picture in InstantUpload/Pictures/2017/02/smssecure-2017-01-07-010203.jpg
- Browse the picture, it gets downloaded to InstantUpload/Pictures/2017/01/smssecure-2017-01-07-010203.jpg

### Environment data
Android version: 7.1

Device model: Nexus 5X

Stock or customized system: CopperheadOS

Nextcloud app version: 1.4.1RC1

Nextcloud server version: 11

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

**Comment by AndyScherzinger** [comment]
Hi @marmeladema 

> Browse the picture, it gets downloaded to InstantUpload/Pictures/smssecure-2017-01-07-010203.jpg/2017/01/smssecure-2017-01-07-010203.jpg (weird right?)

That has been fixed with RC2 (which unfortunately isn't available on f-droid yet)

the "(2)" issue though is something we need to investigate.

**Comment by tobiasKaminsky** [comment]
@marmeladema you can try our latest beta app on fdroid or https://github.com/nextcloud/android/blob/beta/apks/latest.apk

Both bugs should be fixed in it.

**Comment by tobiasKaminsky** [comment]
Please re-open if it happens again.
