### ISSUE TITLE
Auto Upload function missing some photos to be uploaded

### ISSUE THREAD

**Issue by cieska** [nextcloud/android#5261]
### Steps to reproduce
Unknown.
My best guess would be that poor mobile network or maybe switching between mobile and wifi networks interrupting auto upload and it never checks what's uploaded already what's missing? 

### Expected behaviour
All photos must be synced in any circumstances. Some kind of checking mechanism should confirm whats uploaded whats not. In the worst-case scenario option to upload all the photos in the given folder manually.

### Actual behaviour
I haven't noticed it before or maybe didn't pay enough attention if this did happen before, but very clearly I have missed two days worth of photos. I haven't really done anything to my phone configuration or anything I think that could make auto-upload not happening. 
I have a screenshot of a list of files that I have to copy manually. Also in NC web where photos modified 2 days ago and the next up 6 days ago.

![Screenshot_20200120_225340](https://user-images.githubusercontent.com/41318524/72764111-8a762b00-3bde-11ea-975e-9d1534cbe5d8.jpg)

![Screenshot_20200120_225526](https://user-images.githubusercontent.com/41318524/72764112-8cd88500-3bde-11ea-97fc-702c9c363acb.jpg)

### Environment data
Preferences for auto uploading:
Only upload on unmetered Wi-Fi [ ]
Only upload when charging [ ]
Use subfolders [x]

Android version:
Latest 3.10.0

Device model: 
OnrPlus A5010 

Stock or customized system: 
stock Oxygen 9.0.10

Nextcloud server version:
16.0.6

**Comment by paradoxon82** [comment]
I had the same issue. For me, the reason was that my phone was in "energy saver" mode.
When the phone is in this mode, the camere upload is not active.
When you later deactivate the mode, pictures taken in this mode are not uploaded retroactively.
So you are automatically missing all pictures that you take in "energy saver" mode.
And as far as I can see there is no solution which is not manual.

**Comment by tobiasKaminsky** [comment]
@cieska have you tried @paradoxon82 suggestion?

**Comment by paradoxon82** [comment]
I actually have no suggestion for his specific problem. I just wanted to
add other circumstances when the auto upload does not work. It seems that
nextcloud has no actual memory of what it did and did not upload.
It only creates an upland task when you take a picture.
And even that can fail as I described.
It should have an option to check if all pictures on the phone are also on
the server

Tobias Kaminsky <notifications@github.com> schrieb am Fr., 27. März 2020,
06:38:
