### ISSUE TITLE
Optio to force all photos upload with in Auto Upload function.

### ISSUE THREAD

**Issue by cieska** [nextcloud/android#5262]
Probably this feature was requested before.

### Is your feature request related to a problem? Please describe.
Only the new photos taken are auto-uploaded when starting using NC app and auto-upload function for media folders.

### Describe the solution you'd like
To have an option to choose if to auto-upload to NC server all contents of this folder or just the new files that will be appearing in this folder since now.  

### Describe alternatives you've considered
My view is that by default all contents of the exact folder should be uploaded since you configuring for auto-upload. Also/or force check existing files on the server and upload missing ones. Even it's manual function but it would help force missing files on the server to upload, as the app itself [sometimes](https://github.com/nextcloud/android/issues/5261) mistaking and not auto-uploading random files. 

### Additional context
I was thinking for about a year or more since I started using it, I can't come up with any good reason why auto-upload happens only for new files.

**Comment by AndyScherzinger** [comment]
> Probably this feature was requested before.

Yes and the work can be tracked here: #4788
