### ISSUE TITLE
Onlyoffice not opening files with special characters in name

### ISSUE THREAD

**Issue by zuim** [nextcloud/android#5277]
### Steps to reproduce
1. Create a document with a name containing € or ä
2. Tap on it in the app

### Expected behaviour
- The file should be opened in onlyoffice, like files with other names. This works in the web interface.

### Actual behaviour
- The fullscreen loading message of onlyoffice instantly closes and the toast message "Laden des Dokuments fehlgeschlagen" (Loading of document failed) is shown.

### Environment data
Android version: 9
Device model: Zuk Z2 Pro
Stock or customized system: AEX
Nextcloud app version: 3.10.0
Nextcloud server version: 18.0 with community documentserver

#### Web server error log
Only access log, no error occured in the webserver:
[webserver_log.txt](https://github.com/nextcloud/android/files/4095018/webserver_log.txt)

#### Nextcloud log (data/nextcloud.log)
("Druck\u00fcbersicht" is supposed to be "Druckübersicht")
[nextcloud_log.txt](https://github.com/nextcloud/android/files/4095014/nextcloud_log.txt)

**Comment by tobiasKaminsky** [comment]
@juliushaertl as I query the directEditing endpoint…? Do you have an idea?

**Comment by juliushaertl** [comment]
@tobiasKaminsky Do you url encode the file path that is sent over as a parameter?

**Comment by tobiasKaminsky** [comment]
No, but I assumed that it is sent in body via post, so that there is no need of url encoding the path?

**Comment by juliushaertl** [comment]
Could you check if the path is a proper utf8 string when you add it to the form data? I can reproduce the issue with the android app and a file called "ä.docx" but not when issuing the requests with curl.


```
curl --request POST \
  --url 'https://admin:admin@localhost/ocs/v2.php/apps/files/api/v1/directEditing/open?editorId=onlyoffice&creatorId=onlyoffice_docx&format=json' \
  --header 'content-type: application/x-www-form-urlencoded' \
  --header 'ocs-apirequest: true' \
  --data 'path=/ä.docx'
```
