### ISSUE TITLE
Nextcloud 20170109 Beta: "Changelog beta version" is not current

### ISSUE THREAD

**Issue by OlivierS1** [nextcloud/android#528]
### Actual behaviour
-Tell us what happens
When updating to consecutive beta versions, content of changelog is not being kept up to date.

### Expected behaviour
-Tell us what should happen
"CHANGELOG.mg" is not being updated.
### Steps to reproduce
1. Go in "settings"
2. Click on "Changelog beta version"
3. Web brwoser opens with the link.
4. Last update shows as "## 2016-12-31"

### Environment data
Android version:
6.0

Device model: 
LG G3

Stock or customized system:
Stock

Nextcloud app version:
Nextcloud 20170109 Beta

Nextcloud server version:
OC 9.1.1

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

**Comment by AndyScherzinger** [comment]
@OlivierS1 I'll close this issue since @tobiasKaminsky has automated this now
