### ISSUE TITLE
Enhance file conflict dialog

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#5280]
![2020-01-22-123113](https://user-images.githubusercontent.com/5836855/72890829-17220580-3d13-11ea-83bd-5a0bcd991b36.png)

For #4788 we should enhance this dialog a bit, and as a quick win:
- title "click on file you want to keep"
- show files side by side
   - show file size
   - show modification date
   - show image
- click on file keeps it
- two secondary actions on bottom:
  - cancel
  - keep both

@AndyScherzinger @jancborchardt

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky details for have been described by @jancborchardt here: https://github.com/nextcloud/android/pull/4788#issuecomment-563875618

so c&p:
Something like:
**Conflict during auto upload**
Pick which version to keep of `filename`

### Conflict resolution dialog
![Auto upload file conflict resolution](https://camo.githubusercontent.com/e7d270a9fd12a6eba282cab1e22ed0da3bb781b5/68747470733a2f2f707573682e61726973752e66722f7065726d616e656e742f53637265656e73686f745f313537353838323639392e706e673f31)

We need more info on both the files here to be able to decide which one to keep. See the conflict resolution dialog on the server, it gives you:
- thumbnails of both files so you can quickly see
- timestamp and file size of the files (ideally both, not sure why it currently doesn’t do the file you are uploading …)

Not saying that dialog is perfect, but thumbnails and the basic metadata go a long way already to decide whether it’s the same file, or a newer one, or a downscaled/cropped one, etc. to help inform your decision.
![file conflict server](https://user-images.githubusercontent.com/925062/70499256-5c1b1f80-1b4b-11ea-919c-67efb5b38266.png)

**Comment by tobiasKaminsky** [comment]
Having a checkbox is overhead and it is not that easy to use on touch.
Let us go with clicking on it, which highlights it instead.
