### ISSUE TITLE
Color text 

### ISSUE THREAD

**Issue by darkhil** [nextcloud/android#5313]
![Screenshot_20200126-032550_Nextcloud](https://user-images.githubusercontent.com/6114740/73128666-360ee900-3fec-11ea-9417-6b24caf4f8a0.jpg)
White text pls

### Environment data
Android version: 9

Device model: Samsung galaxy a20

Stock or customized system: one ui

Nextcloud app version:  3.10

**Comment by AndyScherzinger** [comment]
@darkhil where? Everything seems fine, the text preview image on the right comes directly form the server and is an image!
