### ISSUE TITLE
Root directory

### ISSUE THREAD

**Issue by Michele64** [nextcloud/android#5314]
### Steps to reproduce
1. Navigate to some subdirectory 
2. Open menu and choose "all files" (Alle Dateien in german) 
3. 

### Expected behaviour
- it should show the root directory, as shown in the app title

### Actual behaviour
-it stays in the previous selected subdirectory 

### Environment data
Android version:
8.1.1
Device model: 
OnePlus 5T
Stock or customized system:
Stock, rooted
Nextcloud app version:
3.9.2
Nextcloud server version:
17.0.2
#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
cc @tobiasKaminsky and @nextcloud/designers for feedback

**Comment by juliushaertl** [comment]
Makes sense, as this is also how the web UI behaves.

**Comment by jancborchardt** [comment]
Yep, agree with @juliushaertl. :)

**Comment by tobiasKaminsky** [comment]
I am pretty sure that his was at some point the behaviour…
I will adjust it.
