### ISSUE TITLE
Feature: unlock with fingerprint

### ISSUE THREAD

**Issue by laurentdinclaux** [nextcloud/android#532]
### Actual behaviour
I can unlock the app with a pin

### Expected behaviour
I would like to unlock it using my fingerprints

PR: #624

**Comment by joseandroidengineer** [comment]
I've worked with adding fingerprint features so I'll give it a whirl!

**Comment by AndyScherzinger** [comment]
Sounds awesome @joseandroidengineer!

**Comment by DanielYWoo** [comment]
Today I setup my own nextcloud and give it a try, it looks cool, but this feature is missing ;-)
It will be very convenient on iPhone.

**Comment by jshatch** [comment]
The owncloud app has had this request in for a year and nothing was done.  I'm excited to see how this progresses here.

**Comment by DanielYWoo** [comment]
@jshatch That's exactly why I dumped ownCloud!

**Comment by tobiasKaminsky** [comment]
@joseandroidengineer if I can assist you while building this feature, please just ping me here or on irc.

**Comment by Flole998** [comment]
That pull request should add that feature.

**Comment by JSoko** [comment]
Fingerprint lock works an SGS7 nougat with beta 20170211 👍

**Comment by AndyScherzinger** [comment]
will be shipped with the upcoming version 1.5.0
