### ISSUE TITLE
nextcloud error

### ISSUE THREAD

**Issue by mmikelic** [nextcloud/android#5325]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
Hi @mmikelic, can you please post the ogcat/stacktrace/error log?

**Comment by backinabit** [comment]
@AndyScherzinger : He's probably referring to an upgrade error on the latest version. Its trying to run "ALTER TABLE filelist ADD COLUMN rich_workspace TEXT", but the column already exists, so obviously it crashes. That query really should read as "ALTER TABLE filelist ADD COLUMN IF NOT EXISTS rich_workspace TEXT".

**Comment by AndyScherzinger** [comment]
That has already been fixed!
