### ISSUE TITLE
The Edit button does not open a Markdown file for editing from the preview

### ISSUE THREAD

**Issue by elpraga** [nextcloud/android#5335]
### Steps to reproduce
1. preview an .md file
2. try to hit the Edit button (__from the preview__)
3. nothing happens

### Expected behaviour
- file is opened for editing

Note: files can be edited just fine from the file list view

### Environment data
Android version:
9.0
Device model: 
redmi note 7

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky can you check this, don't have a OO setup

**Comment by AndyScherzinger** [comment]
@elpraga is this still happening?
@tobiasKaminsky can you check this, don't have a OO setup

**Comment by elpraga** [comment]
Yes, @AndyScherzinger it is still happening in NextCloud Android app 3.10.1 
BTW, why are you mentioning OO setup? Are you taking about OpenOffice?

**Comment by AndyScherzinger** [comment]
I referred to Only Office which is available with fresh installs.

I hope @tobiasKaminsky has an idea

**Comment by elpraga** [comment]
The issue I am reporting concerns Markdown files edited by the Text app via webview.

I'm slightly confused. Why did you mention OnlyOffice @AndyScherzinger ?

**Comment by AndyScherzinger** [comment]
Because I wasn't sure which app is used in the background for editing (server side wise).
Sorry for the confusion!

**Comment by tobiasKaminsky** [comment]
How do you preview md file?
For me it always opens directly in online text editor?

**Comment by elpraga** [comment]
It does that when it's not downloaded locally.

When it **is** downloaded locally, a preview is opened when you click on the file. When viewing the preview, there's an **edit** button as well. This is the one that does nothing.

**Comment by elpraga** [comment]
Is that what you needed @tobiasKaminsky ?

**Comment by tobiasKaminsky** [comment]
Totally :-) Thank you for reporting!
Fix will come.
