### ISSUE TITLE
Log file: Need for content screening.

### ISSUE THREAD

**Issue by OlivierS1** [nextcloud/android#534]
### Actual behaviour
-Tell us what happens
The Log file becomes too large very quickly which makes it difficult to locate specific actions or events.
After clearing the log file, as soon as Nextcloud access my accounts, the log file will exceed 4000 line count.

### Expected behaviour
-Tell us what should happen
The file as is, cannot be used efficiently from my phone, so I must access it from my PC.
I don't know if it is adding more programming headaches and extra debuging, but I would like to have the ability to limit how much data or the type of data should be stored in the log file.
 
### Steps to reproduce
1. Request Log from "Settings"
2. Exit settings and go to "All files"
3. Return in "Settings" and request Logs.
4. Log file produced can span well over a few thousand lines. smallest file is about 250KB.

### Environment data
Android version:
6.0

Device model: 
LG -G3
Stock or customized system:
Stock
Nextcloud app version:
20170111
Nextcloud server version:
OC 9.1.1
#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

**Comment by mario** [comment]
What about adding search? Would that solve your problem? :)

**Comment by OlivierS1** [comment]
I am not sure a search would be realistic in this instance.
The purpose of the log, as far I understand, at least on the phone side, it so be able to extract meaningful information related to Nextcloud behavior.
It should be possible to extract such information while on a PC, but on the phone it is not realistic.

Let's take the following scenario:
- I want to take a photo and I have Autoupload enabled.
- I look at the Nextcloud log and decide to clear it.
- I switch to photo app and take one or more photos.
- I switch to Nextcloud app which takes me to the main Folder directory content.
- I check the "Upload" folder within the Nextcloud app. I do not see the pictures in it.
- I go to Nextcloud settings and scroll down to "Logs"
- Logs is being displayed, but the log will contain everything from the time I clear it, which includes every single transaction. All the steps that occured up to that point have been recorded.

Nextloud folder listing is adding so many logs it's impossible to know what happened between the time the photo where taken and Autoupload failed.

I do not see any easy way of approaching this problem without having to write a log manager.
Ideally, I would like to be able to suppress some actions, possibly before the log is created or make an app that would screen the logs and show it's content based on filters.

**Comment by tobiasKaminsky** [comment]
The log indeed can grow very rapidly, but the log is also intended to be used by devs and they can browse the file on the pc with a good text editor and filter for tags.
So this is, at least for me, no real issue as it works as intended.
