### ISSUE TITLE
Synchronized files can not be edited in Onlyoffice

### ISSUE THREAD

**Issue by joekerna** [nextcloud/android#5340]
### Steps to reproduce
1. Synchronize a folder containing a document/spreadsheet/...
2. Try to edit it in Onlyoffice
3. 

### Expected behaviour
Onlyoffice should open the file

### Actual behaviour
![Screenshot_20200128_125452](https://user-images.githubusercontent.com/23077594/73267859-1b9a6280-41da-11ea-8c75-512b1c7e24d4.jpg)

### Environment data
Android version: 9

Device model: Huawei P20

Stock or customized system: Stock

Nextcloud app version: 3.10.0

Nextcloud server version: 18.0.0

Onlyoffice app: 4.1.4

see #5329 

If a file is synchronized locally it won't open in Onlyoffice. (see screenshot).

**Comment by AndyScherzinger** [comment]
looping in @tobiasKaminsky since you are the expert on the OO integration

**Comment by AndyScherzinger** [comment]
looping in @tobiasKaminsky since you are the expert on the OO integration

**Comment by tobiasKaminsky** [comment]
What kind of file is this?
You have to specify OO to open odt, ods, …

**Comment by joekerna** [comment]
It was an XLSX File (Excel 16)

**Comment by tobiasKaminsky** [comment]
Fix will come
