### ISSUE TITLE
Dark mode: some polishing to the topbar

### ISSUE THREAD

**Issue by szaimen** [nextcloud/android#5346]
### Steps to reproduce
1. Set the app to dark mode (not system default)
2. open a folder
3. some elements in the topbar are black but all should be white

### Expected behaviour
all elements in the topbar should be white

### Actual behaviour
some elements in the topbar are black

### Environment data
Android version: 10

Device model: SGS10e

Stock or customized system: Stock

Nextcloud app version: 3.10.0

Nextcloud server version: 17.0.2

Screenshots:
Dark mode (manual, not system default)
![image](https://user-images.githubusercontent.com/42591237/73287269-4cd65b00-41f9-11ea-8d37-a21083acadce.png)

This is how I would expect it (dark mode, system default)
![Screenshot_20200128-173530_Nextcloud](https://user-images.githubusercontent.com/42591237/73286803-7d69c500-41f8-11ea-8775-091424b9cfea.png)

**Comment by szaimen** [comment]
BTW: when closing the app after setting to dark mode in the app manually, and reopening, all text in the topbar is black. just after opening the first folder, the back button gets white.

**Comment by szaimen** [comment]
Ping

**Comment by szaimen** [comment]
Could this be something for 3.11? Now that "follow systemdesign" is standard more users will notice it...

**Comment by AndyScherzinger** [comment]
Hard to tell for which version since we don't assign issues to versions up-front. So it'll be fixed whenever somebody picks up the issue (or I find the time to fix it myself 😞)

also cc @tobiasKaminsky @dan0xii maybe you folks find the time 🤞

**Comment by tobiasKaminsky** [comment]
>  just after opening the first folder, the back button gets white.

This is the real problem.
It seems to be some sort of race condition…

For tests I changed every occurence of it to red/green, but still the very first show is white…

**Comment by szaimen** [comment]
But why does it work on system default then? What is the difference?

**Comment by tobiasKaminsky** [comment]
On light mode, it is also white, but it should be black:
![2020-03-10-150020](https://user-images.githubusercontent.com/5836855/76319700-df314a80-62df-11ea-830d-1b538004c033.png)

Color depends on primary color: 
bright background -> black
dark background -> white

**Comment by tobiasKaminsky** [comment]
So, after a lot of testing:
If I set this to false, then it directly shows the correct color.
https://github.com/nextcloud/android/blob/01b1e719ffdf0546acf54d2e450aca81edee59be/src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java#L782

But this is needed to show the animated hamburger menu.
It seems that 
- in root: shows hamburger menu
- go to subfolder: 
  - changes hamburger to arrow
  - tints it
  - not correctly shown
- go to root
- go to subfolder -> correct

**Comment by szaimen** [comment]
@tobiasKaminsky I've tested the apk from the PR and it seems to be a problem still with the them manually set to dark mode:
![photo5422477996423490855](https://user-images.githubusercontent.com/42591237/76406500-1b20ea00-638a-11ea-93e8-3b3d52481a66.jpg)
Also shouldn't those character be white when activating the dark mode.

Also with the latest apk "use system defaults" seems to be the only working mode...
BTW: the characters are white when using the bright mode setting, although they should be dark?
