### ISSUE TITLE
Dark mode: some polishing to the plus-button

### ISSUE THREAD

**Issue by szaimen** [nextcloud/android#5347]
### Steps to reproduce
1. set to dark mode
2. open a folder with restricted upload

### Expected behaviour
the plus-button should be completely grey

### Actual behaviour
the plus-button has a border in the primary color (if you look closely

### Environment data
Android version: 10

Device model: SGS10e

Stock or customized system: Stock

Nextcloud app version: 3.10.0

Nextcloud server version: 17.0.2

Screenshots:
![image](https://user-images.githubusercontent.com/42591237/73287205-2a444200-41f9-11ea-8c9c-d3a74f43f754.png)

**Comment by szaimen** [comment]
Ping

**Comment by szaimen** [comment]
Could this be something for 3.11? Now that "follow systemdesign" is standard more users will notice it...

**Comment by AndyScherzinger** [comment]
> Could this be something for 3.11? Now that "follow systemdesign" is standard more users will notice it...

Hard to tell for which version since we don't assign issues to versions up-front. So it'll be fixed whenever somebody picks up the issue (or I find the time to fix it myself 😞)

also cc @tobiasKaminsky @dan0xii maybe you folks find the time 🤞
