### ISSUE TITLE
Dark mode: Hamburger menu has weak focus colors

### ISSUE THREAD

**Issue by moviuro** [nextcloud/android#5350]
### Steps to reproduce
1. Set up android to use a dark theme
2. Set up Nextcloud app to follow system
3. Open the app and the hamburger menu (top left button): it brings the left panel into focus, with one item selected.

### Expected behaviour
- The focused item in the left-side menu has vibrant colors

### Actual behaviour
- The focused item in the left-side menu has weak colors: see [screenshot](https://sco.popho.be/s/kB3eRW49NJNo29S) where "_Activities_" is almost unreadable.

### Environment data
Android version: 10

Device model: Nokia 7 Plus

Stock or customized system: Stock

Nextcloud app version: 3.10.0

Nextcloud server version: 18.0.0

#### Web server error log
```
Irrelevant
```

#### Nextcloud log (data/nextcloud.log)
```
Irrelevant
```

**Comment by AndyScherzinger** [comment]
cc @tobiasKaminsky @dan0xii maybe you folks find the time 🤞

**Comment by tobiasKaminsky** [comment]
![2020-03-10-104648](https://user-images.githubusercontent.com/5836855/76300098-75537980-62bc-11ea-942d-2f91bb6dca74.png)

**Comment by moviuro** [comment]
@tobiasKaminsky this would look nice with light accent colors, but in your screenshot, the colors are [not easy to distinguish](https://webaim.org/resources/contrastchecker/?fcolor=8000FF&bcolor=333333).

FWIW, I'm far from being a designer, and I've been tearing my own hair to get a decent CSS for my blog; but I'd go for:

* Use accent color for the icon (in your case, purple)
* Slightly darker or lighter gray for the selected item (instead of blue -- though this might be due to branding? Blue Nextcloud icon?); or gray + some slight accent touch
* White text

**Comment by AndyScherzinger** [comment]
@moviuro please see the linked pull request which shows the change, the Screenshot within this issue shows the current state before the fix :)
