### ISSUE TITLE
Wakelock on beta

### ISSUE THREAD

**Issue by aronovgj** [nextcloud/android#536]
### Actual behaviour
Wakelock seen in BetterBatteryStats, caused by:

- `*sync*/org.nextcloud.beta.provider/nextcloud.beta`
- `*job*/org.nextcloud.beta.provider/nextcloud.beta`

Nothing should be uploaded or synced however, as I didn't do anything.
Auto upload is activated. Might be the cause.

### Expected behaviour
No wakelock
 
### Steps to reproduce
1. Just let it sit for a few hours 

### Environment data
Android version:
OOS 4.0 (Nougat)

Device model:
Oneplus 3

Stock or customized system:
Stock/Rooted

Nextcloud app version:
beta 20170111

Nextcloud server version:
11

### Logs
Would want to post the protocol but the problem is https://github.com/nextcloud/android/issues/535

**Comment by tobiasKaminsky** [comment]
@aronovgj do you still experience this problem?

**Comment by aronovgj** [comment]
No, seems to be fixed. Will reopen if I encounter the issue again.
