### ISSUE TITLE
Cannot open .eml with email app

### ISSUE THREAD

**Issue by mauricebauer** [nextcloud/android#5368]
### Steps to reproduce
1. Save an email to nextcloud (in my case from thunderbird) with file-extension .eml
2. Open the current nextcloud Android App (V3.10.0)
3. Open the .eml file

### Expected behaviour
- The popup with apps to open the file with contains email programs (such as GMail)

### Actual behaviour
- Only text viewers and other apps are shown, but no email app
- When opening a .eml file in the Google Drive app there is the option to open it with Gmail (so the file-type acceptance from the Gmail app is there)

### Environment data
Android version: Android 9 (MIUI Global 11.0.3) and tested on Android 7.0

Device model: Xiaomi Redmi Note 8 Pro

Stock or customized system: Stock from Xiaomi Global

Nextcloud app version: 3.10.0

Nextcloud server version: 18.0.0

![Screenshot_2020-02-01-11-06-37-418_android](https://user-images.githubusercontent.com/34477772/73590684-89e66a00-44e5-11ea-99e6-59a9d9ce6567.jpg)

**Comment by AndyScherzinger** [comment]
mime type detection needs to be extended to map `.eml` to `message/rfc822` (while I can't say if this helps siince I don't know for which mime types the described apps would listen).

**Comment by AndyScherzinger** [comment]
basically see https://github.com/nextcloud/android/pull/4434/commits/bff6395e420db0ee60386e1a0595a81786aca0be for a hint on how such a code change would have to look like and where it would be located

**Comment by waleedsarwar86** [comment]
@AndyScherzinger I would like to work on this issue.

**Comment by AndyScherzinger** [comment]
@waleedsarwar86  That be great 👍 and is highly appreciated!

**Comment by daniboomberger** [comment]
@AndyScherzinger Is this Issue still available? I would like contribute to my first big Open Source Project and would love to help here. Have a nice day!!

**Comment by AndyScherzinger** [comment]
Hi @daniboomberger yes, this issue is still available so feel free to pick it up 👍
