### ISSUE TITLE
Cannot change storage path from default to external.

### ISSUE THREAD

**Issue by ruvashev** [nextcloud/android#537]
Hi i have a problem with storage path.
Could you look if you have the same issue? Or what might be the reason?

Thanks!

### Actual behaviour
open nextcloud app on android. Go to settings. In general section, tap storage path. Nothing is selected btw there. select /storage/sdcard1.
Error window pops up:
Updating storage path
ERROR: While migrating

### Expected behaviour
storage path changed to sdcard.
 
### Steps to reproduce
1. open nextcloud app on android
2. Go to settings. In general section, tap storage path.
3. select /storage/sdcard1.

### Environment data
Android version: 4.4.4

Device model: Sony Xperia Z2. D6503

Stock or customized system: rooted stock.

Nextcloud app version: 1.4.0

Nextcloud server version: 11
![screenshot_2017-01-12-16-49-39](https://cloud.githubusercontent.com/assets/952468/21909920/ea768f0c-d8e7-11e6-885a-06d93c12562c.png)

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

**Comment by przybylski** [comment]
There might be a couple of reasons for this. Most probable is that there isn't enough space on the sd card.
Can you provide device logs for this issue ?

**Comment by ruvashev** [comment]
hi Bartosz,

thanks for looking into that!

please find logs attached.
I have enough space (128GB sd card).
![_20170119_174246 jpg](https://cloud.githubusercontent.com/assets/952468/22128490/d938b26a-de6e-11e6-9943-f1a85fc1e298.jpeg)
[currentLog.txt](https://github.com/nextcloud/android/files/717969/currentLog.txt)

Is there anything i can enable/do to trace the application (debug traces?)?

Great application btw, thanks for that!

Thanks.

/Ruslan.

**Comment by przybylski** [comment]
Hi Ruslan,

Those are logs from server. In order to understands whats going on I would need device logs. Are you able to provide those?

**Comment by przybylski** [comment]
You can get logs by using logcat tool
https://developer.android.com/studio/command-line/logcat.html

**Comment by ruvashev** [comment]
Hi Bartosz,

thanks a lot! it took me sometime to collect logs - i have not used that tool before.
please find logs attached.
action done:
lunch app
tap ///
tap settings
tap storage path
tap /storage/sdcard1
<get error>
tap storage path
tap default
<nothing happens>
tap storage path
tap /storage/sdcard1
<get error>

what else can i do?
[logcat_traces_before_app_lunch.txt](https://github.com/nextcloud/android/files/722250/logcat_traces_before_app_lunch.txt)

can i run debug app with more traces added?

/Ruslan

**Comment by przybylski** [comment]
Hi,
sorry for such late response.
Is this log taken after the migration process? I can't see anything related with it in this log.

One more thing to check. Is the SD card in RW mode ? could you try to make `/storage/sdcard1/nextcloud` directory with rwxrwxrwx premissions?
you can create the directory using:

    mkdir -p /storage/sdcard1/nextcloud

set permissions using this command

    chmod 777 /storage/sdcard1/nextcloud

**Comment by ruvashev** [comment]
hi,

thanks for reply.

Yes those logs include migration.

But actually about changing permission... Once i created the folder i can see that app can migrate but since folder has 770 permission app cannot write in there. I tried to change permission but that does not work...

```
drwxrwx--- root     sdcard_r          2016-05-10 03:43 DCIM
drwxrwx--- root     sdcard_r          2016-03-09 18:33 Download
drwxrwx--- root     sdcard_r          2016-04-15 14:18 Music
drwxrwx--- root     sdcard_r          2016-03-09 19:13 Photos
drwxrwx--- root     sdcard_r          2016-03-09 19:20 Pictures
drwxrwx--- root     sdcard_r          2016-06-09 10:10 SuperBeam
drwxrwx--- root     sdcard_r          1979-12-31 19:00 XZDualRecovery
-rwxrwx--- root     sdcard_r      146 2017-01-29 21:47 customized-capability.xml
-rwxrwx--- root     sdcard_r    14792 2017-01-29 21:47 default-capability.xml
drwxrwx--- root     sdcard_r          2017-01-29 21:59 nextcloud
```

so regardless what i do i cannot change it to anything than 770...

Do you know what could be the reason?

Thanks.

/Ruslan.

**Comment by przybylski** [comment]
I am not sure how rooting changes the access to the external directory but my guess is that the app process is not a part of sdcard_r group which diallows it from writing to that directory.

**Comment by prilly** [comment]
I have the same problem:

https://github.com/nextcloud/android/issues/968

Is there a fix for this?
