### ISSUE TITLE
Enable copy of file to remain on mobile device for X number of days after syncing

### ISSUE THREAD

**Issue by Dho100** [nextcloud/android#5379]
Request feature to retain a copy of files on local device for a specified number of days after syncing to Nextcloud. 

Presently all of my synched photos/files delete on my mobile device after syncing, but I would prefer to have a local copy retained for 30/90 days after syncing.

**Comment by joshtrichards** [comment]
Duplicate of #2323 

I suggest subscribing to that issue to track progress and/or giving it an upvote :+1:
