### ISSUE TITLE
F-Droid app stuck on v3.9.2

### ISSUE THREAD

**Issue by metaMMA** [nextcloud/android#5385]
It seems that the application hosted on F-Droid is outdated. Is there a way to automate the releases to the F-Droid repo?

**Comment by tobiasKaminsky** [comment]
We have this automated, and 3.10 is in Fdroid available for building:
https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/com.nextcloud.client.yml#L1031

But it seems to fail: https://f-droid.org/wiki/page/com.nextcloud.client/lastbuild_30100090

Please open up an issue on Fdroid, as this is not something we can fix here.

**Comment by tobiasKaminsky** [comment]
Here is already an issue: https://gitlab.com/fdroid/fdroiddata/issues/1930
