### ISSUE TITLE
Feature request: Adding server monitoring as part of Nextcloud app.

### ISSUE THREAD

**Issue by OlivierS1** [nextcloud/android#539]
### Actual behaviour
-Tell us what happens
With NC11, there is an app that can be added to Nextcloud server which allow Nextcloud performance and usage monitoring by collecting some statistics.
While there are tools to do just that (I am personally not aware of which tool to use) I would like to know if there is a plan to integrate this functionality within Nextcloud app to monitor the server.

### Expected behaviour
-Tell us what should happen
 If possible, I would like to be able to see Nextcloud Server statistics, such as CPU statistics, user activity, quota, from withing Nextloud app itself.
Only specific users should be able to see entire server statistics, but each user could have the ability to monitor their own account statistics.

**Comment by xraMsamohT** [comment]
This is only interesting for admins. No user needs this. This should be developed in a separate app.

**Comment by Spartachetto** [comment]
It is true that server statistics are only interesting for admins.
Yet I think that a synthesis of user's data could be really a useful addition. In this server issue I proposed one of the possibilities: [visualize useful synthetic information when user clicks 'Tags'](https://github.com/nextcloud/server/issues/2143).
Having something like that also on mobile would be really cool!!!

**Comment by mario** [comment]
Unfortunately, I don't think we'll put this in the NC app, but we'd be more than happy to support you in creating a separate app doing this! :)
