### ISSUE TITLE
Internal network server not found

### ISSUE THREAD

**Issue by Fahaba** [nextcloud/android#5392]
**Steps to reproduce**

1. Setup internal web server with Nextcloud
2. Setup web Server only resolvable to local network
3. Download Nextcloud Android App
4. Open -> Connect with server -> enter ip or host definition

**Expected behaviour**

Nextcloud should be able to connect. **Google Chrome can resolve the address** without issues.

**Actual behaviour**

Message "server not found" occurs

**Environment data**

Nextcloud Android : 3.10
Nextcloud Server: 17.0.2

The web server uses a http connection (not https).
The android app does work on old devices, which were configured ~10/2019 (also Nextcloud 3.10).

**Comment by tobiasKaminsky** [comment]
Do you see login screen? Or does it fails upon entering server address?

**Comment by Fahaba** [comment]
Yes I can see a login screen. After entering the user credentials in the Android app I get a message "Server not found".
It is working via Chrome Browser Login with the same credentials

**Comment by tobiasKaminsky** [comment]
Do you have a specific network setup, e.g. reverse proxy, etc?

**Comment by Fahaba** [comment]
Hi,
I mapped a network host to a IP and added reverse DNS for the internal network.
I recently found out, when I enter hostdef + "/." in the input field, the app will find the server, but after entering user credentials and clicking the button Allow access, it just hangs and will never do anything.

**Comment by Fahaba** [comment]
Any idea when this will be fixed? I actually can't use the app at all right now.
Do you need some additional log information?

**Comment by AndyScherzinger** [comment]
I guess @rullzer can answer this while I guess the server isn't configured correctly.

**Comment by Fahaba** [comment]
Sorry to bother you guys with this. You're totally right.
My boss diddn't want some people to download stuff from the cloud.
I know this is not the best solution but I switched over some session names and returned in the remote.php webdav section. I diddn't know that the android app uses the webdav, too.
Tank you for looking into it and shame on me
