### ISSUE TITLE
Enhancement: View images thumbnail instead of full download

### ISSUE THREAD

**Issue by FalcoSK** [nextcloud/android#540]
### Actual behaviour
-When opening image, full size image is being downloaded. 

### Expected behaviour
-For saving data and enhance performance, we request to be delivered smaller thumbnail of image for temporary view. Option to download full size image should be available then.
 
### Environment data
Android version: 6

If this is already available, please, provide us a guideline. Thank you.

**Comment by elpraga** [comment]
@FalcoSK the beta app (downloadable [here](https://github.com/nextcloud/android/tree/beta/apks) ) already has this functionality and it works great. You can even pinch zoom to change the thumbnail sizes..

**Comment by AndyScherzinger** [comment]
Like @elpraga mentioned it is available in the beta version, implementation is covered by #69 which still has some issue regarding thumbnail proportions coming from the server side.
