### ISSUE TITLE
File Menu is suddenly jumping after a second after opened

### ISSUE THREAD

**Issue by jedwabny** [nextcloud/android#5409]
# Steps to reproduce
1. Like on the attached screenshots:
While having number of files, click on the file menu (click the dots at the right side of file).
Hint: It's rather better reproducible if using one of the in middle files. 
Wait a few seconds and observe whether menu jumps a few positions down.
2. If not reproduced, close the menu and try again - also try another's file menu.
3. If still not reproduced, quit the directory then come back and repeat again.

Opening the menu:
![Screenshot_20190928-085200](https://user-images.githubusercontent.com/22258500/73848992-701c8e00-4829-11ea-9a65-48e5f3b6f010.jpg)
And a second after the menu has changed his position (itself):
![Screenshot_20190928-085259](https://user-images.githubusercontent.com/22258500/73849011-7579d880-4829-11ea-98cd-7ee673fe2d60.jpg)

### Expected behaviour
- Opened menu should stay in position it appeared for the first time after has been opened

### Actual behaviour
- From time to time menu suddenly jumps from top to a few rows down after second or two after opening it.
So, if you have bad luck, you run not the expected feature.
- The second behaviour is about the menu content that is not complete. A few options are hidden even if there is still enough free space on the screen to display entire menu. Anyway, the missing positions are properly accessible on scrolling so it's just minor customer experience issue.

### Environment data
Android version: 8.1.0

Device model: Asus ZC553KL

Stock or customized system: Stock

Nextcloud app version: 3.10.0 but issue is observed at least for a few versions back. Sometimes very rarely but then very frequently.

Nextcloud server version: 17 and 18 as well

**Comment by jedwabny** [comment]
Not stale

**Comment by tobiasKaminsky** [comment]
Not sure if this is what you mean, but the menu is opening always on the location of the file you want to use…
So it is expected to be opened on different positions.

**Comment by jedwabny** [comment]
Hi, the matter is not the position the menu appears but the menu sometimes suddenly changes position a second after appearing. 

So when I open the menu (screen1) and find out for example "synchronize" option which I want to use, menu jumps/skips to different position(screen2) and, if I have bad luck, it causes me to click on "move file" or "rename".

**Comment by tobiasKaminsky** [comment]
Now I got it :+1: 
Hm, I fear that we cannot do that much, as layout/positioning of the overflow menu is done by Android.
Is this also happening for you on other devices?

**Comment by jedwabny** [comment]
I reproduce it as well on xiaomi Mi A2 with android 10.

Were you able to reproduce it too?

**Comment by tobiasKaminsky** [comment]
No, I never saw this, and I have a bunch of devices, also with Android 10… :/

**Comment by jedwabny** [comment]
If I could help with reproduction as it is quite tricky.

It's needed to have a number of files in directory in order to have screen full of files (I have directories and txt files) .
Starting from the top one file, you see that the menu is opening to the down part of screen. It's ok of course. 
So continue: please open the menu of the second file, then third file, and so on, as long as you find out the first one (the highest placed one) for which the menu opens to the top. This is the file (on Your list) for which the issue occurs most frequently.
Now it's needed to quit the directory and go back and try opening the menu of axectly this file.
If issue doesn't happen then again: quit the  directory, go back, and try opening the menu.
For me the issue happens after 5-10 attepts.

Hope I described it enough clear.

**Comment by tobiasKaminsky** [comment]
Can you maybe make a video of it?
There are some screen recording apps.

**Comment by jedwabny** [comment]
Of course, I recorded the video. 
How could I send it to you?

**Comment by tobiasKaminsky** [comment]
Send it to tobias at nextcloud dot com with a reference to this issue?

**Comment by jedwabny** [comment]
not stale - video has been sent on email.

**Comment by tobiasKaminsky** [comment]
Thanks for the video.
I never saw this before and I have no idea what this is causing.
We just open up the menu and positioning is done by Android.

I really fear that we cannot do anything here…

**Comment by jedwabny** [comment]
Don't worry, it's understood.

Anyway, thank you for interesting in my problem.

Regards,
Mariusz
