### ISSUE TITLE
Add me to the repository

### ISSUE THREAD

**Issue by mario** [nextcloud/android#542]
### Actual behavior
I am not a member of the repository, can't commit, push or review.

### Expected behavior
I should be a member of the repository, should be able to commit, push and review.
 
### Steps to reproduce
1. Buy a cookie
2. Check the list of repository users
3. See that I'm missing

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

**Comment by AndyScherzinger** [comment]
@jancborchardt @LukasReschke can you please add @mario to the Nc Orga?

@mario please see https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md for our lean dev approach/process - as to "final review": this is limited to the project maintainers (via LGTM check - which has some hickups now and then), while you can do reviews nonetheless but shouldn't merge PRs.

**Comment by mario** [comment]
@AndyScherzinger thanks, I've read the file but I'll do it once again in more detail. Please forgive me if I do a mistake or two in the process :)

**Comment by AndyScherzinger** [comment]
No worries @mario, happy to answer any questions and help out with whatever I can 👍

**Comment by jancborchardt** [comment]
You’re added, welcome @mario! :) After accepting the invite, also make sure to set your visibility from Private to Public at https://github.com/orgs/nextcloud/people

**Comment by mario** [comment]
So kind of you @jancborchardt! :)

**Comment by jancborchardt** [comment]
@mario well, awesome to have you on board! :rocket:

**Comment by mario** [comment]
@jancborchardt @LukasReschke doesn't look like I can push still.

**Comment by AndyScherzinger** [comment]
You should be able, since you are am member. 0_o
Do you push to a branch? (because master is protected and pushes are prohibited to master)

**Comment by mario** [comment]
@AndyScherzinger 

git push --set-upstream origin bugfix-454
remote: Permission to nextcloud/android.git denied to mario.
fatal: unable to access 'https://github.com/nextcloud/android.git/': The requested URL returned error: 403

As far as I'm aware, this should push the branch.

**Comment by AndyScherzinger** [comment]
Hmmm, I just checked the settings:
> The Nextcloud organization has their default repository permission set to write. This means that every member of this organization has write access to this repository, regardless of the team and collaborator access specified...

So since you are a member of the organization, you should be able to?!

**Comment by mario** [comment]
@AndyScherzinger I'll double check, maybe I've just done something silly.

**Comment by mario** [comment]
Nevermind, for some reason HTTPS pushes don't work so I've switched to to SSH ones.

**Comment by AndyScherzinger** [comment]
Glad to hear it is working not, weird though since I always do HTTPS.
