### ISSUE TITLE
Autoupload / only in specific wlans

### ISSUE THREAD

**Issue by criwe** [nextcloud/android#5424]
### Describe the solution you'd like
At the moment it is possible to restrict auto upload to free wlans (on/off).

It would be great to select one or more specific wlans where auto upload sould happen or as an alternative select some wlans where auto upload should not happen.

For example: allow auto upload at my home-wlan, but not via the wlan at work.

Thanks!
Best

**Comment by CardSnap** [comment]
I think this would be a good idea.

**Comment by joshtrichards** [comment]
Duplicate of #3671
