### ISSUE TITLE
Clarify search behaviour

### ISSUE THREAD

**Issue by mario** [nextcloud/android#543]
Can you please clarify the search behaviour for me?

So I have: NC11, few changes done to default files, uploaded a few new files.

Searching for "t" (or whatever) results in a bunch of copies of the same result in the view. Before I dig into the code too much, what's the intended behaviour of this?

**Comment by mario** [comment]
For the sake of transparency, I'm now looking into this as well.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky: this one is for you ;)

@mario at the moment the "search" is basically a filter in the listView, so "t" leads to all files where the filename contains a "t" get's displayed.

**Comment by mario** [comment]
@AndyScherzinger that's the expected behavior, but not how it works :P Anyway, I'm working on search this week to make it usable at least :)

**Comment by AndyScherzinger** [comment]
Sounds great! :)
As I mentioned Tobias is probably he best to talk to since he implemented the first iteration.

**Comment by tobiasKaminsky** [comment]
@mario thank you for your help and finding this bug.
With "working on search this meek" you mean filtering the file list? Search, at least in our term, is searching across all folders for a specific query.

**Comment by mario** [comment]
@tobiasKaminsky search doesn't seem to work that way at the moment (aka it only filters current directory, and it doesn't even do a good job at that (several instances of the same file are shown). I am working on making it:

a) perform better, as it's really slow right now since on every char it re-queries
b) actually perform the search across all directories
c) various other search improvements

Hope that clarifies things, but if not I'm here! :)

**Comment by tobiasKaminsky** [comment]
This can be closed as we have #558 and your pull request #550 and we can discuss over there.
