### ISSUE TITLE
Exception on activating auto file upload

### ISSUE THREAD

**Issue by tauchmi** [nextcloud/android#5431]
### Steps to reproduce
1. Open NextCloud App on android
2. Create new Folder on server
3. Exception

### Expected behaviour
- Tell us what should happen
No error

### Actual behaviour
- Tell us what happens
Nullpointerexception

### Environment data
Android version:

Device model: 
Huawei P30 Pro
Stock or customized system:
Emui
Nextcloud app version:

Nextcloud server version:
18.0
#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
```

**Comment by ezaquarii** [comment]
@tauchmi Could you provide us the stacktrace? We can't do anything without it.

**Comment by tauchmi** [comment]
Where do I get the stacktrace?

**Comment by ezaquarii** [comment]
Normally it should be shown to you when the app crashes, in form of a
pop-up.

I assume you must have seen it as you reported it as
NullPointerException and this information comes from the stacktrace.

**Comment by tauchmi** [comment]
Yes, but it disappeared afterwards as the app crashed.

Is there a log file written?

Chris Narkiewicz <notifications@github.com> schrieb am So., 9. Feb. 2020,
12:23:

**Comment by ezaquarii** [comment]
Crash report should not self-close.
Did it disappear or did you close it?

There is no log written anywhere, AFAIK.
Maybe we should update our logger to do this.

**Comment by tauchmi** [comment]
I was alle to reproduce it:

Activating Sync
Creating Folder in App via Create Button
Crash

************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method
'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on
a null object reference
at
com.owncloud.android.ui.dialog.CreateFolderDialogFragment.onClick(CreateFolderDialogFragment.java:140)
at
androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:213)
at android.app.ActivityThread.main(ActivityThread.java:8147)
at java.lang.reflect.Method.invoke(Native Method)
at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWVOG
Model: VOG-L29
Id: HUAWEIVOG-L29
Product: VOG-L29EEA

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 10.0.0.178C431


Chris Narkiewicz <notifications@github.com> schrieb am So., 9. Feb. 2020,
23:55:

**Comment by ezaquarii** [comment]
@tauchmi Thank you, this is very useful.

**Comment by AndyScherzinger** [comment]
@ezaquarii also related to #4792 (same error different navigational path)

**Comment by AndyScherzinger** [comment]
@Shagequi does your fix also happen to imrove/fix this scenario?

**Comment by Shagequi** [comment]
@AndyScherzinger 
Hi,

I think it could help.
Apparently, the fix was merged on master 1 month ago, but still not "active" on `stable-3.10`.  
That explains why it keeps happening. 

@tobiasKaminsky Hey ! do you have any idea when the fix is gonna be merged?
 https://github.com/nextcloud/android/pull/5465
Thanks

**Comment by AndyScherzinger** [comment]
@Shagequi `stable-3.10` likely won't see anymore releases 3.11RC2 is out, RC3 to follow any minute. So let's hope this week 3.11 to be released 🤞

**Comment by tobiasKaminsky** [comment]
Please test 3.11 (available today) and re-open if it is not fixed.
