### ISSUE TITLE
Cannot run androidTest due to INSTALL_FAILED_SHARED_USER_INCOMPATIBLE error

### ISSUE THREAD

**Issue by ezaquarii** [nextcloud/android#5440]
### Steps to reproduce
0. Connect phone with usb cable
1. Open Android Studio
2. Select androidTest
3. Right-click and run

### Expected behaviour
- Android test should run

### Actual behaviour
```
Testing started at 23:37 ...

02/09 23:37:51: Launching 'RegisteredUserTest' on OnePlus ONEPLUS A6013.
Installation did not succeed.
The application could not be installed: INSTALL_FAILED_SHARED_USER_INCOMPATIBLE

List of apks:
[0] '/home/tn/Devel/nextcloud-android/build/outputs/apk/androidTest/qa/debug/nextcloud-android-qa-debug-androidTest.apk'
Installation failed due to: 'null'
Retry
```

### Environment data
Android version: 10
Device model: OnePlus 6T
Stock or customized system: stock
Nextcloud app version: master

I suspect it has something to do with this commit 76bbc110a942116dc7a9d4ba72a970afd93cf7a5. Removing this line 
https://github.com/nextcloud/android/blob/76bbc110a942116dc7a9d4ba72a970afd93cf7a5/src/androidTest/AndroidManifest.xml#L31
fixes the test runner.

@tobiasKaminsky did you experience this issue?

**Comment by tobiasKaminsky** [comment]
This is due to screenshot tests.
In order to grab screenshots, test apk and regular app must have the same shared user.
From output it seems that you use qa as build flavor…

It should also be "enough" to omit screenshot Tests.

**Comment by ezaquarii** [comment]
@tobiasKaminsky Does it mean the tests should not even run in QA? Is this a bug?

**Comment by tobiasKaminsky** [comment]
So I tested it with a real device, where NC was installed via play store.
Tested with
- selected "qaDebug" as build variants.
- run RegisteredUserTest, by pressing play button next to class name (line 37)
- worked

**Comment by ezaquarii** [comment]
On Thu, Apr 23, 2020 at 12:39:50AM -0700, Tobias Kaminsky wrote:
> So I tested it with a real device, where NC was installed via play store.
> Tested with
> - selected "qaDebug" as build variants.
> - run RegisteredUserTest, by pressing play button next to class name (line 37)
> - worked

Which orchestration? AndroidX?
Which Android Studio version?

Maybe it has something with my setup.

**Comment by tobiasKaminsky** [comment]
I am using current master, so AndroidX.
Android Studio is latest stable 3.6.3
