### ISSUE TITLE
concerning #5331

### ISSUE THREAD

**Issue by wfue-20** [nextcloud/android#5452]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
- Tell us what should happen
stable version
### Actual behaviour
- Tell us what happens
app crashed
### Environment data
Android version:
7.1
Device model: 
SM-J510FN, successor of Medion Tablet of case #5331
Stock or customized system:

Nextcloud app version:
dev version installed with reference to bug #5331, parallel installation with version 3.9, as Tobias suggested in his response mail of 11.2.2020
Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky fancy taking a look? :)

**Comment by ezaquarii** [comment]
What am I looking at here? Confirmation of smtg?

**Comment by AndyScherzinger** [comment]
Don't know, only Tobias has been involved in the mailings, so we need to wait for his reply.

**Comment by tobiasKaminsky** [comment]
That was not a mail in first place, but a github reply:
https://github.com/nextcloud/android/issues/5331#issuecomment-584487298

@wfue-20 should install dev version to see if this fixes our library problem.

**Comment by tobiasKaminsky** [comment]
…so? It is working?
