### ISSUE TITLE
Error trying to answer NC Talk call from NC app notifications

### ISSUE THREAD

**Issue by Mohammed-Al-Haidary** [nextcloud/android#5457]
### Steps to reproduce
1. Login from a PC, and start a call in Nextcloud Talk to a second user.
2. From an Android phone that has the second user logged into the NC app and the NC Talk app, click on the notification that says "X wants to talk with you".
3.  Press "Answer Call".

### Expected behaviour
- I would expect it to redirect me to the NC Talk app and join the call.

### Actual behaviour
- I get a message saying "Failed to execute action".

### Environment data
Android version: 9

Device model:  SM-A705FN/DS

Stock or customized system: Stock.

Nextcloud app version: 3.10.1

Nextcloud server version: 18.0.0

**Comment by Soygen** [comment]
Having this same issue. Did you ever resolve it?

**Comment by Mohammed-Al-Haidary** [comment]
No, I'm still waiting for the developers to help :(

**Comment by AndyScherzinger** [comment]
Cc @tobiasKaminsky for feedback

**Comment by tobiasKaminsky** [comment]
@nickvergessen can we prevent showing the "call" action on push notifications for mobile?
It is indeed not useful, as it does not work on files app and talk app is handling this separately.

**Comment by nickvergessen** [comment]
It's a WEB action, so just redirect to the browser?
