### ISSUE TITLE
nextcloud-text, no option to view/insert images on android

### ISSUE THREAD

**Issue by axel-rank** [nextcloud/android#5462]
### Steps to reproduce
- Create a text document with nextcloud-text on nextcloud-server. Insert an image.
- Open the document on nextcloud-android.
- The image isn't visible. Only a placeholder "view image". If you tab on it you get locked out.
- Create a text document on nextcloud-android.
- No option to insert image.

Nextcloud android: 3.10.1
Nextcloud text: 2.0.0
Nextcloud server. 18.0.0

**Comment by tobiasKaminsky** [comment]
@juliushaertl do you have an idea why the image is not shown?



>     * No option to insert image.

This is a missing feature, but needs server work first

**Comment by tobiasKaminsky** [comment]
@juliushaertl ping :-)

**Comment by juliushaertl** [comment]
Yes, let me put that on my list to check if we can figure out an easy implementation for the way inserting images currently works with the preview. For the android side we would then emit something like `insertGraphic` that we use on Collabora already.

**Comment by tobiasKaminsky** [comment]
@juliushaertl ^ :-)

**Comment by tobiasKaminsky** [comment]
This should be tracked here https://github.com/nextcloud/server/issues/16132 as it is for all clients.
