### ISSUE TITLE
Failed to start editor

### ISSUE THREAD

**Issue by bazio101** [nextcloud/android#5467]
I just upgraded to version 3.10.1 from f-droid.
There's a new option in the up-right menu "Add folder info", but every time I select it, I just get a "Failed to start editor" message.
Am I missing something on android device (version 5.1) or it's a server side problem (missing app on 16.0.7 version)?

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky isn't this a Nextcloud 18+ feature so this should be hidden for any older server version?

**Comment by tobiasKaminsky** [comment]
Well…yes :see_no_evil:
