### ISSUE TITLE
Again: Auto upload does not work correctly

### ISSUE THREAD

**Issue by michaelof** [nextcloud/android#5472]
### Steps to reproduce
1. Auto upload set to "WLAN only"
2. Stay on Mobile Data for a while, whatever reason, no WLAN
3. make some photos and videos during "WLAN-offline" time
4. install available upgrade for Nextcloud App
5. Enable WLAN
6. Many photos and videos are NOT detected as candidates for auto upload, although in designated/defined folders

### Expected behaviour
- Nextcloud app should detect auto upload candidates correctly, even after an upgrade/update ** OR **
- a "sync" / "resync" / "scan again" feature should be available. 

I've seen that this feature is already an enhancement request, any news for this?

### Actual behaviour
Step 6. above:
--> Many photos and videos are NOT detected as candidates for auto upload, although in designated/defined folders
- no resync / rescan functionality avaiable (anymore, afai remember)

### Environment data
Android version: 6.0 

Device model: Lenovo K10a40

Stock or customized system: Stock

Nextcloud app version: 3.10.1, F-Droid version

Nextcloud server version: 18.0.1, self-hosted

### Logs etc.: 
-> Please advise which logs would be helpful. As no error msg, no idea if normal webserver (apache) logs would be of any use?

**Comment by tobiasKaminsky** [comment]
>     * a "sync" / "resync" / "scan again" feature should be available.

You can go to upload view and pull to refresh.
Does this help?

**Comment by michaelof** [comment]
Forgot to mention before that I've tried this already. But unfortunately no, it does not have any effect.  New "upload candidates" are not detected by nextcloud app.
