### ISSUE TITLE
Crash triggered by the tablet orientation change

### ISSUE THREAD

**Issue by 1div0** [nextcloud/android#5478]
### Steps to reproduce
1. Open the gallery
2. Change orientation
3. Boom

### Expected behaviour
- That should not happen.?!

### Actual behaviour
- Tell us what happens

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by ezaquarii** [comment]
@1div0 stacktrace?

**Comment by 1div0** [comment]
Not sure I can obtain it. Will try to repeat the condition with ADB.

**Comment by ezaquarii** [comment]
On crash, you should see an error pop-up with stacktrace and "send" button.

**Comment by 1div0** [comment]
G2G now. Will do so ASAP.

**Comment by 1div0** [comment]
[Editor.txt](https://github.com/nextcloud/android/files/4213493/Editor.txt)
OOM

**Comment by tobiasKaminsky** [comment]
From stacktrace it is a duplicate of #4981
