### ISSUE TITLE
Crash by the download of the document

### ISSUE THREAD

**Issue by 1div0** [nextcloud/android#5484]
### Steps to reproduce
1. Download
2. Wait
3. Boom

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by 1div0** [comment]
It was observed during download via unreliable Wi-Fi in the bus. Sadly, the stack trace appeared shortly, but I forgot to copy the content to the clipboard.

**Comment by AndyScherzinger** [comment]
@1div0 thanks for the update, can you reproduce the crash and post the stack trace? ❤️

**Comment by 1div0** [comment]
So far so good. Maybe some noise from the network layer caused crash. Or maybe lack of the memory. So closing.
