### ISSUE TITLE
Onlyoffice isn't loading .doc Documents (docx is working)

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/android#5489]
### Steps to reproduce
1. Create a .doc Word document (docx is working)
2. It is loading in the Browser
3. It isn't loading in the Android App, a download starts

### Expected behaviour
- doc should be open the onlyoffice build-in editor

### Actual behaviour
- Tell us what happens

### Environment data
Android version: 9
Device model: oneplus
Nextcloud app version: latest
Nextcloud server version: latest

**Comment by AndyScherzinger** [comment]
@juliushaertl @tobiasKaminsky I guess this is a server side issue, right?

**Comment by juliushaertl** [comment]
Could you check your ONLYOFFICE settings if doc is enabled for default opening?

![image](https://user-images.githubusercontent.com/3404133/74767997-19cb3880-5288-11ea-89ea-37a49d80609f.png)

**Comment by juliushaertl** [comment]
@tobiasKaminsky If i remember correctly, mimetypes that are in the optional can still be opened with the 3-dots menu on android, right?

**Comment by jakobroehrl** [comment]
@juliushaertl 
yes, doc is enabled (otherwise it wouldn't load in the Browser)

**Comment by juliushaertl** [comment]
Ah indeed it seems that onlyoffice is not exposing the mimetype for doc files:

![image](https://user-images.githubusercontent.com/3404133/74827158-32c9fd00-530d-11ea-8a83-bbc07c9dc1bd.png)

@jakobroehrl Could you open an issue for that in https://github.com/ONLYOFFICE/onlyoffice-nextcloud ?
