### ISSUE TITLE
[request] Custom path for AutoUpload local folder

### ISSUE THREAD

**Issue by varhub** [nextcloud/android#5502]
> Could you though about allow manual handwritten local path at AutoUpload feature?

## Motivation
I have Magisk's "ExSdCard Access Enabler" that will allow write access to external sdcard  and bring back "move to app folder" option. But it is useless for Nextcloud due it does not appear at selectable storages.

## Rationale
New enforced API for SdcardAccess is a pain  making external sdcard unwritable.

This problem will be present on **all** Android 10 and several Android 9. And even worse, API is not stable so every single efort made now could be a waste of time for Android 11+ (this already happent between 9 and 10).

So instead of beg you for a full rewrite of sdcard management, I ask for a shortcut for all people with rooted phones and/or magisk.

## Final questions

1. Any chance to implement something that covers it?
2. Anyone know if I can edit some DB or file to replace stock unwritable path of an already configured folder by its magisk replacement?

**Comment by tobiasKaminsky** [comment]
We are relying on Android API:
https://github.com/nextcloud/android/blob/39e113f25165dd0c8460dfde3b3394700eb37771/src/main/java/com/owncloud/android/datastorage/DataStorageProvider.java#L71

I fear that Magisk is conflicting with this…
Maybe the best is to ask Magisk to get this reliable in?

Regarding your questions:
1. I do not have time for this feature, as I have to prioritize and this will only affect a small subset of users. Also I think it is not the correct approach, as it might lead unexperienced users into trouble.
2. Yes, this is possible. It is stored in shared preferences. Force stop the app, change the xml (as you are root this should be possible) and then restart the app.

**Comment by varhub** [comment]
Thanks tobias for your support.

About .xml file, Im unable to find it.
I spent several time exploring /data/data/com.nextcloud.client and other locations but no single text file has mentioned paths.

The only match was:
```
<string name="upload_from_local_last_path">/storage/0000-0001/DCIM/Camera</string>
```

What Im missing out?
Is this config placed at some database file?

Many thanks in advance.

**Comment by joshtrichards** [comment]
The string you're likely looking for is `storage_path`. The default value for it isn't populated from the xml normally from the looks of it, but in theory it can be defined there. You're on your own though. :-)

Going to close this out as there's nothing actionable in terms of enhancements/etc.
