### ISSUE TITLE
W/libEGL: EGLNativeWindowType 0x6ff572f010 disconnect failed

### ISSUE THREAD

**Issue by samsonayalew** [nextcloud/android#5519]
### Steps to reproduce
I am using nanohttpd to access files locally with webView on android studio 3.6.

### Expected behaviour
- I expected the webview to display my mini website like it use to do 
on 3.4 android studio

### Actual behaviour
- This error on the title i think is the culprit.

### Environment data
Android version: 3.6

Device model: Samsung s8

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
D/InputTransport: Input channel constructed: fd=78
D/InputTransport: Input channel destroyed: fd=79
D/ViewRootImpl@74f4093[MainActivity]: stopped(true) old=false
D/ViewRootImpl@74f4093[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager: prepareNavigationBarInfo() DecorView@552ebed[MainActivity]
    getNavigationBarColor() -855310
W/libEGL: EGLNativeWindowType 0x6fdac2a010 disconnect failed
D/OpenGLRenderer: eglDestroySurface = 0x6fefa91a00, 0x6fdac2a000
D/ViewRootImpl@74f4093[MainActivity]: Relayout returned: old=[0,0][1080,2220] new=[0,0][1080,2220] result=0x5 surface={false 0} changed=false
D/ViewRootImpl@74f4093[MainActivity]: Relayout returned: old=[0,0][1080,2220] new=[0,0][1080,2220] result=0x1 surface={false 0} changed=false

```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
@samsonayalew this has nothing to do with Nextcloud I am afraid, so closing the issue.
