### ISSUE TITLE
In the welcome screen "multi account" is overkill for a new user

### ISSUE THREAD

**Issue by mabkenar** [nextcloud/android#552]
### Actual behaviour
-In the welcome screen (the screen that shows up the first time user runs Nextcloud client) there is a slide for "Multi account: Connect all your clouds", here:
![934e1d90-b1cc-11e6-8d56-df271352b9c3](https://cloud.githubusercontent.com/assets/3006332/22083118/f2b48fe2-ddca-11e6-82a7-78808da0ee0f.png)

### Expected behaviour
- This is supposed to be an introduction for someone who is new to Nextcloud. I think setting up a *second* account when the user still hasn't set up the first one is overkill. The multi account feature, while being really nice, is an advanced feature. The average Nextcloud user needs only one account, and should not be presented in the welcome screen.
  
### Steps to reproduce
1. Run a fresh copy of Nextcloud Android client (or delete the app storage from Application manager to reset the app)
2. Look at the second slide in the welcome screen.

**Comment by przybylski** [comment]
Welcome screen is suppose to introduce to the app, not the nextcloud as a whole.

**Comment by mabkenar** [comment]
Oh I see. That's a good point, since you also plan to use the welcome screen to notify the user when a new important feature is added to the client.
Still, multi user is not one of the first things a new user should learn, in my opinion. This silde could be simply removed, or be replaces with something else, like a hint for the user to find (or set up) a server (see [here](https://github.com/nextcloud/android/issues/53#issuecomment-273600471)).

**Comment by jancborchardt** [comment]
This is actually a really good point. While for us multi-account is pretty useful, the majority of people will mainly have one account.

@tobiasKaminsky @AndyScherzinger @eppfel what do you think? 3 slides:
1. A safe home for all your data
2. Instant upload
3. Log in

Quick and no frills

**Comment by przybylski** [comment]
How about:
1. A safe home for all your data
2. Auto upload
3. Deep system integration
?

**Comment by eppfel** [comment]
I am not too attached to this one...

But I feel 3 intro slides is just about right and the login is not an intro slide, it's mandatory. ..and the "skip" button exists for a reason.

> Deep system integration

If there are new features we want to promote in the next version, I am happy to make new slides and then we can replace multi account first.

Another thing @nextcloud/android : Can we trigger these slides after an update and not first install? Because then they would be real "Whats new" slides. Best would be to distinguish both use cases. And offer different slides on each.

**Comment by mario** [comment]
In my opinion, the best way would be if NC could expose a simple endpoint which would return few lines of changelog (including the images), and we could pull those automatically once the NC on the server is updated. 

As for the welcome screen itself on the first run - it has its benefits, but maybe in a form different than what it is now.

@eppfel as for your last question - if I remember correctly, we can detect when package is replaced and trigger the slides then but If we go that route I'd suggest we go with NC exposing changelog endpoint.

**Comment by eppfel** [comment]
Changelog was discussed before and we decided against it (and I would argue against it again) Anyone has the issue number?

The Whats new/intro screen, is really for the arbitrary non-technical user, so he does not have to dive deep into the app to discover new functionality or we want to inform changes in the workflow of the app to ease the transition, e.g. moving the "on your device" to a filter as discussed lately.

Please explain what you mean with a different form...

**Comment by mario** [comment]
@eppfel changelog endpoint would allow us to create the what's new/intro slides dynamically rather than changing the code every time we have to update them - but if you've already talked about it and decided against it, then I apologize.

Maybe an intro screen would show a way how to achieve most common operations rather than show features themselves? Can still be a image/text combo, but with some hand showing "Click here to find your most common files" or something.

**Comment by przybylski** [comment]
> Another thing @nextcloud/android : Can we trigger these slides after an update and not first install? Because then they would be real "Whats new" slides. Best would be to distinguish both use cases. And offer different slides on each.

That's the way I wrote it :)

**Comment by przybylski** [comment]
> Maybe an intro screen would show a way how to achieve most common operations rather than show features themselves? Can still be a image/text combo, but with some hand showing "Click here to find your most common files" or something.

I feel this discussion is beyond the scope of this issue

**Comment by eppfel** [comment]
> but if you've already talked about it and decided against it, then I apologize.

No need to apologize. This should not sound harsh :sweat_smile: Just wanted to mention it. Maybe you have something new to add. Just did not want to repeat it.

> Maybe an intro screen would show a way how to achieve most common operations rather than show features themselves? Can still be a image/text combo, but with some hand showing "Click here to find your most common files" or something.

I am absolutely with you on this one. 👍 That's what I aimed at (but not completely succeeded) with the redesign: to mimic the actual UI.

**Comment by mabkenar** [comment]
I would say the most non-trivial aspect of Nextcloud for a non-technical user is that the Android client is server-agnostic; That they need to find a server before they can use the app.

@eppfel
> But I feel 3 intro slides is just about right

I think so too.

My suggestion is:
1. A safe home for all your data
2. **Your data, your rule: Choose from many Nextcloud providers, or use your own server**
3. Instant upload

**Comment by eppfel** [comment]
> Your data, your rule: Choose from many Nextcloud providers, or use your own server

Could be a bit long. If someone makes the changes and screenshots, I can give feedback. Still low priority to me...

**Comment by mabkenar** [comment]
> Could be a bit long. 

The suggested text is slightly *shorter* than what we already have for the first slide. Compare this:
**A safe home for all your data**
**Access, share & protect your files at home and in your enterprise**
With this:
**Your data, your rule**
**Choose from many Nextcloud providers, or use your own server**

> If someone makes the changes and screenshots, I can give feedback.

I can happily make a pull request right away, but I don't have resources to build the app and make screenshots myself.

**Comment by mabkenar** [comment]
Another thing is graphics. Can you think of a graphics that best represents the idea behind such a slide? I just made a very crude sketch right away [here](https://iffcloud.fz-juelich.de/index.php/s/GbACyTsSYOECxTq) but please don't look at it before you think of your own!

**Comment by jancborchardt** [comment]
> changelog endpoint would allow us to create the what's new/intro slides dynamically rather than changing the code every time we have to update them - but if you've already talked about it and decided against it, then I apologize.

@mario we decided against a changelog since the small changes are less important. This is a basic one-time intro. No need to implement a big server API part for it just to have it fancy and dynamic if we don’t really need to do it.

@eppfel many apps have the »log in« as part of the intro, basically being the third slide. That’s like 1-2-3, otherwise it’s a fourth step.

**Comment by eppfel** [comment]
So:
first install: 2 + login 
Update: max. 3 depending on changes 
?

**Comment by mabkenar** [comment]
I would say

* First install: 3 ("A safe home for all your data", "Your data, your rule", "Instant upload") + login
* Update: max. 3 depending on changes

Also, there is an [Oxford comma](https://en.wikipedia.org/wiki/Serial_comma) missing in the first slide:
**Access, share & protect** ---> **Access, share, & protect**

**Comment by mabkenar** [comment]
@tobiasKaminsky @AndyScherzinger Could you please build and make a screenshot for the above pull request? Of course it won't be final before a proper slide image is made, just to get an idea how it looks.

**Comment by tobiasKaminsky** [comment]
We can close this issue here and move the discussion to #586 or?
