### ISSUE TITLE
Improve dev edition changelog

### ISSUE THREAD

**Issue by strugee** [nextcloud/android#5525]
I find that the changelog for the F-Droid dev edition isn't really helpful; it's dense and hard to read. I haven't looked into it closely but I'm guessing we automatically generate it - here are some suggestions for how to clean it up:

* Omit commit IDs. These don't actually mean anything to end users
* Rewrite Transifex commits to "update translations" or something
* Omit version bump commits like 1dd355d
* Don't show the library commit, instead just say "updated library" if the commit changed since last time
* Filter out commits that touch only tests
* Filter out merges probably?

I'll look into this myself when I have time but anyone should feel free to pick it up themselves if you get to it before me 👍

**Comment by AndyScherzinger** [comment]
Hi @strugee, yes, it is auto generated and @tobiasKaminsky is likely able to provide some code pointers 😊

**Comment by strugee** [comment]
Filed #5530. I _think_ I got the labels right, but someone should double-check :P

**Comment by AndyScherzinger** [comment]
>  I got the labels right, but someone should double-check

double-checked and all is well, just added `pr exists` to the issue 🚀

**Comment by tobiasKaminsky** [comment]
@strugee It seems that some info are missing:

![image](https://user-images.githubusercontent.com/5836855/76057383-ac9eef00-5f79-11ea-9eae-7cf9098942a4.png)

But only 
``
Fix test
Update Nextcloud Android library
Update 3rd-party dependencies`
```

is shown.

It should show also some info about conflict dialog, or?

**Comment by strugee** [comment]
Hm, interesting. Without having looked at it in depth (at all, really) I think what happened here was:

1. Commits about the conflict dialog got committed to a feature branch.
2. A daily dev version was released.
3. The feature branch got merged.

The merge commit is being excluded because all merge commits are excluded. The original commits are being excluded because they're older than the last dev version tag. What we really want to exclude is not things that are _older_ than the latest dev version tag/commit, but rather things that are _not referenceable_ from the latest dev version tag/commit.

I don't know offhand if this is easy to do with `git log`. I will look into it.
