### ISSUE TITLE
Onlyoffice navigation is very slow and laggy

### ISSUE THREAD

**Issue by drikqlis** [nextcloud/android#5533]
### Steps to reproduce
1. Open a Word or Excel document from Nextcloud Android app, preferably long with for example 50 pages of text.
2. Try to scroll, zoom and move inside the document.
3. The movement is very laggy, choppy and unresponsive.

### Expected behaviour
- When navigating the document it should be smooth like when using Google Docs or Word.

### Actual behaviour
- The movement while navigating is very laggy, choppy and unresponsive - not usable.

### Environment data
Android version: 10

Device model: Samsung Note 9

Stock or customized system: Stock

Nextcloud app version: 3.10.1

Nextcloud server version: 18.0.1

**Comment by tobiasKaminsky** [comment]
As we "only" show the OnlyOffice view, this app cannot do anything about this.
Can you please report this to OO?
