### ISSUE TITLE
Onlyoffice zoom bug

### ISSUE THREAD

**Issue by drikqlis** [nextcloud/android#5534]
### Steps to reproduce
1. Open a Word or Excel document from Nextcloud Android app.
2. Try to zoom in different ways.
3. The navigation bar is moving and zooming too.

### Expected behaviour
- When navigating the document and zooming navigation bar should stay unchanged.

### Actual behaviour
- When zooming, sometimes the navigation bar is zooming to and hiding.

### Environment data
Android version: 10

Device model: Samsung Note 9

Stock or customized system: Stock

Nextcloud app version: 3.10.1

Nextcloud server version: 18.0.1

**Comment by tobiasKaminsky** [comment]
@juliushaertl this seems to happen more often with a freshly started app, or if one zooms while loading.
After loading, or after clicking in the text area, zoom is working fine.

**Comment by juliushaertl** [comment]
Hm, not sure but the OnlyOffice app probably needs to disable zooming in a viewport meta tag as done in text https://github.com/nextcloud/text/blob/252296e15e583d0ec8dca957d5532bbb87d61579/src/views/DirectEditing.vue#L108

**Comment by tobiasKaminsky** [comment]
@juliushaertl can you point me out where to change this for testing? ❤️

**Comment by juliushaertl** [comment]
Adding that line to https://github.com/ONLYOFFICE/onlyoffice-nextcloud/blob/master/js/directeditor.js#L28 could work :wink:

**Comment by tobiasKaminsky** [comment]
The link refers only to an empty line? 🙈

**Comment by juliushaertl** [comment]
Yes, just add it to the beginning of the file ;)

**Comment by tobiasKaminsky** [comment]
So a very quick some test seems to work…

**Comment by tobiasKaminsky** [comment]
I created an PR in their repo.

**Comment by tobiasKaminsky** [comment]
Please open up an issue there, if it still happens after a release.
