### ISSUE TITLE
onlyoffice  .txt Dateien öffnen nicht

### ISSUE THREAD

**Issue by weinic** [nextcloud/android#5545]
Mit der nutzung von onlyoffice in der Android app funktioniert das öffnen von Text Dateien nicht.
Es wird zwar angezeigt dass mit onlyoffice geöffnet wird, aber passiert nichts. die Text Datei wird nicht geöffnet.

So this is actually two things:
- [x] txt should be opened first with text app, only after that with OO (@tobiasKaminsky 
- [ ] txt should still be working with OO (@juliushaertl)

**Comment by AndyScherzinger** [comment]
cc @tobiasKaminsky @juliushaertl 

@weinic what setup are you running? Versions: App, Android, Nextcloud Server, Document Server?

**Comment by juliushaertl** [comment]
Does opening the file work in the browser? Are there any entries in the Nextcloud log? Could you also share a screenshot of your onlyoffice settings from the server, especially how the mimetype checkboxes are set there?

**Comment by weinic** [comment]
@AndyScherzinger 

My versions are:
App Version 3.10.1
Android (lineage OS): 7.1.2
Nextcloud Server: 18.0.1 on Debian system
Community Dcument Server: is the New integatet v. 0.1.5

@juliushaertl 
In the Browser works fine to open and edit the txt file.
I just tried it.
The mimetype checkbox are aktivated in the onlyoffice settings

**Comment by tobiasKaminsky** [comment]
Indeed…
When clicking on a non-downloaded txt-file it tries to open it with OO and this fails.
It keeps hanging on "loading document" @juliushaertl 

So this is actually two things:
- txt should be opened first with text app, only after that with OO (@tobiasKaminsky 
- txt should still be working with OO (@juliushaertl)

**Comment by tobiasKaminsky** [comment]
![image](https://user-images.githubusercontent.com/5836855/77906503-5a0ad700-7288-11ea-8290-32b09f97ca37.png)

@juliushaertl text does not offer to open txt as main mimetype. Is there a reason for it?

**Comment by juliushaertl** [comment]
No, actually not. Let's fix that in https://github.com/nextcloud/text/pull/743

**Comment by tobiasKaminsky** [comment]
Now the only question is why does txt not open with OO…

**Comment by tobiasKaminsky** [comment]
So this is not related to Android, but also happens when opening it directly in web.

**Comment by tobiasKaminsky** [comment]
Closing, as Android side is fixed and there is an issue in text now.
