### ISSUE TITLE
Dynamic menu items

### ISSUE THREAD

**Issue by mario** [nextcloud/android#555]
Capabilities API would expose menu items to be added to the sidebar. The menu items would simply open a web page, and the API would expose title and the URL - but @MorrisJobke probably knows a bit more about this than I do.

While I will have an issue regarding sidebar menu redesign, in the current design the links would probably go between uploads and settings.

Involving @nextcloud/designers team just in case they have any issue with the suggested approach.

@AndyScherzinger @tobiasKaminsky 

PR: #806

**Comment by tobiasKaminsky** [comment]
What menu entries would be added? 
We need to make sure that only important and not too many entries are shown.

**Comment by mario** [comment]
The user would be able to add the entries on the server side. Including @karlitschek so he can tell us more about this.

**Comment by MorrisJobke** [comment]
> The user would be able to add the entries on the server side. Including @karlitschek so he can tell us more about this.

It's not the user, but the admin. Stuff like "more information about our service" (can be found on the web page and therefore an URL is used here and open the browser from within the app).

The entries can be fully defined by the admin of the instance and should be placed on a fixed position (as in hardcode the position within the Android code) but not at the very end. Maybe after "Uploads" and before "Settings".

**Comment by tobiasKaminsky** [comment]
Oh, great stuff. 
Is every "self defined" entry just a link, which should be opened as a webview in the app?
Where can I (as an admin) adjust this? (for testing purpose)

**Comment by MorrisJobke** [comment]
> Is every "self defined" entry just a link, which should be opened as a webview in the app?
> Where can I (as an admin) adjust this? (for testing purpose)

Yes. It's defined as "name and URL". This needs to be developed ;)

**Comment by AndyScherzinger** [comment]
Sounds rather easy :)

We already do this for the account menu list, so basically define a menu item group which you populate dynamically based on the server response. While for bandwidth savings there should be some caching though.

**Comment by mario** [comment]
@MorrisJobke  do you know if this is going to be available for 12, as I need it in the app?

Poking @karlitschek so he doesn't forget about the need for this :P

**Comment by MorrisJobke** [comment]
> @MorrisJobke do you know if this is going to be available for 12, as I need it in the app?

Sure :) I guess we also will bring this to an older version. We are currently settling on an API. I will keep you posted.

**Comment by AndyScherzinger** [comment]
I created a branch for development here: https://github.com/nextcloud/android/tree/dynamicMenuItems

**Comment by mario** [comment]
Sure but there is no API for this yet

**Comment by AndyScherzinger** [comment]
I know. Just thought I can do some UI preparation work to support you with this change, so we "just" have to integrate the server's API at some point while the UI part is already there :)

**Comment by mario** [comment]
K. You know the three types of links?

**Comment by AndyScherzinger** [comment]
Erm, no. :) Which are they?

**Comment by mario** [comment]
Regular sidebar links, quota link (will go below quota bar), and settings links (will replace our settings links like help etc etc).

**Comment by tobiasKaminsky** [comment]
Just a quick screenshot of how the webview looks like
![device-2017-04-04-155724](https://cloud.githubusercontent.com/assets/5836855/24660314/7f6fc112-194f-11e7-93a9-b933cc396ae7.png)

- Javascript is enabled, even though "Using setJavaScriptEnabled can introduce XSS vulnerabilities into your application, review carefully." But I guess websites without JS are pretty hard to display.
-  The webpage is not reloaded when rotating, but rotation is done be webview, so it is a really smooth UI feeling

Tomorrow I will start with fetching the items via ocs

@MorrisJobke

**Comment by mario** [comment]
Hi @tobiasKaminsky - some comments:

- maybe show back icon so you can go back to settings instead of drawer icon (which is disabled)
- please make sure to disable local file access for webview
- please open a PR with WIP so we can track progress :)
