### ISSUE TITLE
Nextcloud crashed

### ISSUE THREAD

**Issue by TaZi-loh** [nextcloud/android#5551]
### Steps to reproduce
0. Create a new group and a user in that group
0. This user logs in on his mobile device
1. He Uses a subfolder of "Photos" (a folder that existed when I finished my Nextcloud setup) to upload all photos from his mobile device with the app
2. Login in as admin on your pc and download the "group folder" app. 
3. Create a group folder "Photos" and give the new group writing permission. The admin also gets all permissions in the new group. 
4. The earlier created user looks into his app again and sees his folder replaced by the group folder
5. He decides to upload his stuff to another folder which he newly creates. He clciks on "ok" and the app crashes. 

### Expected behaviour
- I would have expected to either have normal folders and group folders distinguished or to be warned when I create a folder with the same name
- app not crashing

### Actual behaviour
- i wasn't warned 
- the other folder disappeared
- the app crashed

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
	at com.owncloud.android.ui.dialog.CreateFolderDialogFragment.onClick(CreateFolderDialogFragment.java:140)
	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7682)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus6
Model: ONEPLUS A6003
Id: QKQ1.190716.003
Product: OnePlus6

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 2001151848

```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
> * Login in as admin on your pc and download the "group folder" app.

What is this app?
