### ISSUE TITLE
Lost shared folder while moving to new location

### ISSUE THREAD

**Issue by schaarsc** [nextcloud/android#5552]
### Steps to reproduce
1. UserA shares folder F1 with group G
2. UserB (member of group G) sees /shared/F1
3. UserB moves /shared/F1 to /sharesFromA/F1
4. at this point in time I saw a Toast message "lost connection to server"
5. then I saw /shared/F1 removed from /shared

### Expected behaviour
- move should be an atomic transaction, even if connection to server is lost

### Actual behaviour
- UserB has lost access to F1 
- UserB activity shows "you have moved folder F1 to /sharesFromA/F1"
- UserA still sees F1 being shared with group G

### Environment data
Android version: 9

Stock or customized system: stock

Nextcloud app version: 3.10.1

Nextcloud server version: 18

**Comment by tobiasKaminsky** [comment]
This is an atomic operation we do via dav on server.
@nextcloud/server-triage do you have an idea?
