### ISSUE TITLE
Android app won't connect to self-hosted public server

### ISSUE THREAD

**Issue by VirusAlex** [nextcloud/android#5562]
### Steps to reproduce
1. Install app from https://play.google.com/store/apps/details?id=com.nextcloud.client
2. Type server address (eg https://subdomain.domain.com)
3. Tap on "Предоставить доступ" ("Grant access" ??) button after login

### Expected behaviour
Successful login to an account (from web-browser works perfectly)

### Actual behaviour
Infinite loading screen:
<details>
    <summary>Screenshot</summary>

![nextcloud_bug](https://user-images.githubusercontent.com/28566658/75703759-26f51800-5cc9-11ea-9395-f00ddfcf2b40.jpg)
</details>

### Environment data
Android version: 10 QKQ 1.1190825.002

Device model: Mi 9T Pro

System: MIUI Global 11.0.2 Stable (QFKMIXM)

Nextcloud app version: 3.10.1

Nextcloud server version: 17.0.0 (docker pull nextcloud:17.0.0)

#### Nextcloud log (data/nextcloud.log)

[nextcloud.log](https://github.com/nextcloud/android/files/4277225/nextcloud.log)

**Comment by tobiasKaminsky** [comment]
Can you create us a test account and send the credentials to tobias at nextcloud dot com with a reference to this issue?

**Comment by VirusAlex** [comment]
> Can you create us a test account and send the credentials to tobias at nextcloud dot com with a reference to this issue?

Done. Have you received my email?

**Comment by Unclezz** [comment]
Same issue for me, forced to use the "old login version" in order t ohave mobile devices to login.

Happening on Oneplus5t, Oneplus 3T, Samsung S10E as well as all other phones I tried to use.

**Comment by tobiasKaminsky** [comment]
Alex gave me some test credentials and problem lies somewhere in config of server as in the the login phase the app is only showing a webview with login flow.

I suspect that the same happens for you @Unclezz.

**Comment by tobiasKaminsky** [comment]
Please check/verify all server side php/webserver settings.

**Comment by Unclezz** [comment]
@tobiasKaminsky thanks a lot for checking this one!
I confirm, problem is in the configuration. 
Specifically, it is required to add following in config.php:

 'overwriteprotocol' => 'https',

**Comment by tobiasKaminsky** [comment]
Thanks for replying and glad that it now it is working.

**Comment by abrodkin** [comment]
@tobiasKaminsky even though proposed change in `config.php` fixed the same problem for me (and that's good) I still have a couple of questions:
1. Web-client (i.e. desktop & mobile Firefox for Android) used to work perfectly fine even w/o discussed configuration change
2. Is there a chance to document it somewhere? In my case there's a Traefik reverse proxy which I may guess affects all that but in the documentation here (https://docs.nextcloud.com/server/16/admin_manual/configuration_server/reverse_proxy_configuration.html) there's no mention of a need to set `overwriteprotocol => https` in case of Traefik usage.

**Comment by tobiasKaminsky** [comment]
For such infos you can open a PR on https://github.com/nextcloud/documentation/
