### ISSUE TITLE
Dark Theme no readable Text

### ISSUE THREAD

**Issue by corincorvus** [nextcloud/android#5565]
Hi,
in the newest Version of Nextcloud Android the Text of Readme and the Top Text is black on Dark Theme. Have a look on my Screenshot. 

May you fix it?
![Screenshot_20200303-075430](https://user-images.githubusercontent.com/21257329/75750541-b4b22100-5d24-11ea-9c25-8c267136cc45.jpg)

**Comment by AndyScherzinger** [comment]
fixed via #5496
