### ISSUE TITLE
Deleting an account freezes temporarily the UI

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/android#5576]
### Steps to reproduce
1. Add an Account
2. Delete it
3. 

### Expected behaviour
- Show a spinner and keep the UI responsive

### Actual behaviour
- UI completely freezes until deletion is done

### Environment data
Android version: Lineage OS 16

Device model:  Pocophone F1

Stock or customized system:

Nextcloud app version: 3.10.x

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Hm, for me it instantly went back to login…?
Maybe it depends how much needs to do while removing account.
Did you have many downloaded files?

**Comment by stefan-niedermann** [comment]
No, happens also with any downloaded files to me.

**Comment by tobiasKaminsky** [comment]
Is the account you delete the last one? 
Or is this happening only if you delete 2nd account and it should immediately switch to 1st one?

**Comment by stefan-niedermann** [comment]
It happens when i have more than one accounts and delete one of them.

**Comment by tobiasKaminsky** [comment]
Thanks for sharing the video.
However, I still cannot reproduce it :/
