### ISSUE TITLE
Non-empty folder shown as empty after opening through search function

### ISSUE THREAD

**Issue by Th0maz** [nextcloud/android#5578]
### Steps to reproduce
1. Open Android app
2. Search for a folder, that contains some files
3. Click on that folder in the search results

### Expected behaviour
- Folder is shown with its content

### Actual behaviour
- Folder is shown as empty
When I open the folder directly (without search) afterwards, it is still shown as empty.
When I open the same folder on another device, I can see the content.
Reprocucable with every folder.
Tested it with two devices (in both directions), it's not device-related.

### Environment data
Android version: 10

Device model: Samsung Galaxy S10

Stock or customized system: stock

Nextcloud app version: latest

Nextcloud server version: 17.0.3

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
@Th0maz can you please do a pull-down-to-refresh in that folder and see if that helps?

**Comment by Th0maz** [comment]
I'm pretty sure I already tried that without any luck, but when I refresh now, I can see the content.
Not sure if this was a temporary issue only.
However I still see empty folders at first when using the search function.

**Comment by tobiasKaminsky** [comment]
I tried it right now, and all the folder content is available.
Sorry, I am a bit out of clue…
