### ISSUE TITLE
3.11.0 RC1: Upload existing files makes app hang

### ISSUE THREAD

**Issue by doits** [nextcloud/android#5590]
### Steps to reproduce

1. Go to automatic uploads
2. Choose a folder with a lot of existing files and enable "Upload existing files"
3. Close the dialog

### Expected behaviour

Existing files should be uploaded if they are not uploaded already.

### Actual behaviour

App hangs and crashes.

### Environment data

The folder has a lot of files (10.000+ images). A folder with not so many files seems to work, at least the app does not hang.

Android version: 10

Device model: Pixel 4XL

Stock or customized system: Stock

Nextcloud app version: 3.11.0 RC1

Nextcloud server version: 18.0.1

**Comment by kuba-orlik** [comment]
I'm also experiencing this issue on 3.11.0 RC1

**Comment by tobiasKaminsky** [comment]
Let us track it in #5613
