### ISSUE TITLE
photos are not synced

### ISSUE THREAD

**Issue by axxName** [nextcloud/android#5591]
### Steps to reproduce
1. Android is disconnected from the Internet (home WiFi)
2. Take a photo with your camera
3. After some minutes set Internet (WiFi) on.

### Expected behaviour
- I expect the photo to appear on the server

### Actual behaviour
- The photo is not synced
But works fine if Internet connection active when taking photo

### Environment data
Android version:
7.1.2 N2G47H
MIUI 10.2.3

Device model: 
XiaoMi Redmi 4A

Stock or customized system:

Nextcloud app version:
3.10.1

Nextcloud server version:
18.0.1

**Comment by AndyScherzinger** [comment]
Maybe @ArisuOngaku has an idea? I fear it is oem related since many XiaoMi devices reported issues with auto upload.

**Comment by bpcurse** [comment]
I have the same issue using a Blackberry DTEK50 (Android 6.0.1)

**Comment by ArisuOngaku** [comment]
I cannot reproduce this issue; could you please @bpcurse @axxName reproduce this bug on the **dev** version of the app, then send the logs (settings > more > logs)? Don't forget to strip out sensitive data.

**Comment by bpcurse** [comment]
@ArisuOngaku Thanks for looking into this.

The dev version 20200313 does upload the photo, but it takes quite long after switching wifi back on (approx. 10 Minutes) and can lead to the impression that it's not working at all.

Do you still need logs in this case?

**Comment by ArisuOngaku** [comment]
Np; well in this case this is more of a UX issue; @axxName could you please:
- confirm that your photos are not sinced even after more or less 10+ minutes?
- if so, try the **dev** version of the app? If the same is happening to you this would avoid having to open a separate issue.

Thanks in advance for your time.

**Comment by axxName** [comment]
I don't know where to get apk for dev version.
But for nextcloud-30110054.apk (3.11.0 RC4)
it does start uploading the photo
But when I started syncing my account manually

It takes time to transfer all my photos.
I'll add a comment later.

**Comment by uniartisan** [comment]
> 也许@ArisuOngaku有个主意？我担心这是oem相关，因为许多小米设备报告与自动上传的问题。

I have a similar problem.
My phone is HONOR 20 Pro, EMUI10, and ny nextcloud server is 18.0.3 ，app 3.11.0
Not all new photos are bring auto uploaded. Besides, nextcloud app is not always running at background.
And I can't find a good way to upload all my old photos to my server and put them in different folders due to different time from app.
