### ISSUE TITLE
Automated testing

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#56]
To improve the quality of our app we should introduce automated testing.
@przybylski you said on IRC that you have experience with this?
What can you recommend? 
ownCloud started with appium

**Comment by tobiasKaminsky** [comment]
Also we should have some kind of test plan for every new feature we are developing.
Does anyone has a best practice for this?

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger @jancborchardt @LukasReschke @przybylski

**Comment by przybylski** [comment]
what sort of tests we want to have?
UT?
Monkey tests?
Other?

**Comment by jancborchardt** [comment]
@przybylski if you have experience with it, what do you recommend? :)

@AndyScherzinger @stoyicker @David-Development @zmatsuo @strugee do you have any experience with it?

**Comment by stoyicker** [comment]
I have worked on writing tests for an SDK, and I would definitely recommend to thoroughly test android-library if it's not being done already, can't really remember.

As for the app itself however, that's going to be daunting - I don't think I recall this app using DI, and without that, injecting test data in non-trivial cases will be very hard or even impossible at times. https://github.com/JakeWharton/u2020/ is a great example of coding an Android app for testability.

For UI-tests, in my experience, the biggest issue are animations. To overcome this you can disable them on your devices or use IdlingResources, but I haven't found a way to do the first one reliably for all devices and the second way requires code added in the main source set, so I'm not sure it's an approach I want to call 'good'.

**Comment by AndyScherzinger** [comment]
Unfortunately I don't but would agree with @stoyicker that the library needs to be thoroughly tested since it is/might-be used by others which gives it some importance.

Since the implementation hasn't had the focus on testability up to now the automation (without using a real back end) will be tricky, complex or impossible in some situations.

But even just with a real backend which isn't perfect we could implement test for the larger, standard use cases to make sure they haven't been broken.

**Comment by strugee** [comment]
@jancborchardt unfortunately I don't. Don't have enough experience with Android :)

Good thing other people here do.

**Comment by jancborchardt** [comment]
@stoyicker thanks! @strugee no worries. :)
Btw you were both added to the Nextcloud Android team, you just need to accept it at https://github.com/nextcloud to join. :rocket:

**Comment by strugee** [comment]
@jancborchardt cool! But I'm not sure why? I've never done that much more than file issues/suggest UX improvements from time to time.

**Comment by jancborchardt** [comment]
@strugee which is very important :) not only devs are team members.

**Comment by strugee** [comment]
Very true! :)

Thanks!

**Comment by tobiasKaminsky** [comment]
We have now all kinds of tests in place…
