### ISSUE TITLE
No longer able to open KeePass files from within Nextcloud client

### ISSUE THREAD

**Issue by monreal** [nextcloud/android#5600]
### Steps to reproduce
1. Until a few weeks ago, so before 3.10 I think, I was able to open .kdbx files using KeePassDroid by selecting the file from the Nextcloud client
2. With recent versions like 3.10.1 the message "no app set up to handle this file type" is shown
3. Even "open with" does not let me select any app
4. However opening .kdbx files stil works from other apps like Solid file manager, so I guess it sis not a problem with KeePassDroid

### Expected behaviour
- File should open in KeePassDroid

### Actual behaviour
- see above

### Environment data
Android version: Lineage OS 16 (Android 9)
Device model: Pocophone F1
Stock or customized system: Official Lineage build
Nextcloud app version: 3.10.1
Nextcloud server version: 18.0.1

**Comment by monreal** [comment]
![Screenshot_20200307-092057_Nextcloud](https://user-images.githubusercontent.com/54005/76150016-30ee9080-60a6-11ea-8bbd-a840fe3205f1.png)

**Comment by AndyScherzinger** [comment]
@monreal see https://github.com/nextcloud/android/issues/5009#issuecomment-594720511 this isn't an issue of Nextcloud but KeePassDroid (since it works perfectly fine with keepass2android)

KeePassDroid issue: https://github.com/bpellin/keepassdroid/issues/391

**Comment by AndyScherzinger** [comment]
see also https://github.com/bpellin/keepassdroid/pull/352
