### ISSUE TITLE
Problems switching between accounts

### ISSUE THREAD

**Issue by ogneir** [nextcloud/android#5602]
### Actual behaviour 
- after the update 3.11.0 RC1, switching between account accounts stopped working in menu, but if click on icon  work correctly.

### Environment data
Android version:
Android 9 
Device model: 
Huawei p20 rpo and huawei mediapad m5 10.8 pro
Stock or customized system:
EMUI 9.1
Nextcloud app version:
3.11.0 RC1
Nextcloud server version:
18.0.0

**Comment by AndyScherzinger** [comment]
cc @tobiasKaminsky since I am currently not running a 3.11 build on my phone

**Comment by tobiasKaminsky** [comment]
Fixed via https://github.com/nextcloud/android/pull/5608

**Comment by redtux** [comment]
Where has this been fixed? I just wanted to report the same bug for the same version. 🙂

**Comment by AndyScherzinger** [comment]
@redtux it has been fixed via #5608 and will be released with 3.11.0 RC2

**Comment by redtux** [comment]
My fault, fixed doesn't mean released. I saw the fix, but was waiting for a new release. Should be more patient, I guess. 😃 Thanks for the fix! 🎉

**Comment by redtux** [comment]
Great, it works again! 👌🤩 I have so many accounts, that using the icons did not work for me. 🤭 Now I can use NC on my phone again. Thanks a lot! 🧡
