### ISSUE TITLE
Existing files auto upload freezes app

### ISSUE THREAD

**Issue by MarekPikula** [nextcloud/android#5613]
### Steps to reproduce
1. Select folder with a lot of files to auto upload existing files (in my case over 2500 photos).
2. Save
3. Wait until application not responding dialog is shown.

### Expected behaviour
Some sort of indicator that the app is scanning the folder (I presume that's what it's doing) without freezing the app.

### Actual behaviour
Application freezes and "Application not responding" dialog is constantly appearing.

### Environment data
Android version: 9

Device model: HTC U11

Stock or customized system: Stock

Nextcloud app version: 3.11.0 RC1

Nextcloud server version: 18.0.1

#### Web server error log
Not relevant.

#### Nextcloud log (data/nextcloud.log)
Not relevant.

**Comment by AndyScherzinger** [comment]
cc @tobiasKaminsky @ArisuOngaku

**Comment by doits** [comment]
reported in #5590, too

**Comment by InfamousUser** [comment]
It is freezing in the background while uploading on 3.10.1 as well.

**Comment by ArisuOngaku** [comment]
I can confirm enabling this setting on a folder with a large amount of files will freeze the app.

```
D/SyncedFolderPreferencesDialogFragment: onCreateView, savedInstanceState is null
W/extcloud.clien: Accessing hidden method Landroid/graphics/drawable/DrawableContainer;->getOpticalInsets()Landroid/graphics/Insets; (light greylist, reflection)
D/EGL_emulation: eglMakeCurrent: 0xcc8cd040: ver 2 0 (tinfo 0xc9c22d00)
I/chatty: uid=10088(com.nextcloud.client) RenderThread identical 2 lines
D/EGL_emulation: eglMakeCurrent: 0xcc8cd040: ver 2 0 (tinfo 0xc9c22d00)
D/EGL_emulation: eglMakeCurrent: 0xcc8cd040: ver 2 0 (tinfo 0xc9c22d00)
D/EGL_emulation: eglMakeCurrent: 0xcc8cd040: ver 2 0 (tinfo 0xc9c22d00)
D/EGL_emulation: eglMakeCurrent: 0xcc8cd040: ver 2 0 (tinfo 0xc9c22d00)
D/EGL_emulation: eglMakeCurrent: 0xcc8cd040: ver 2 0 (tinfo 0xc9c22d00)
D/EGL_emulation: eglMakeCurrent: 0xcc8cd040: ver 2 0 (tinfo 0xc9c22d00)
D/OpenGLRenderer: endAllActiveAnimators on 0xc798c980 (RippleDrawable) with handle 0xc60fe410
[FREEZES AFTER THIS LINE] V/SyncedFolderProvider: Updating /storage/emulated/0/DCIM/test_images with enabled=true
I/extcloud.clien: Waiting for a blocking GC ProfileSaver
I/extcloud.clien: WaitForGcToComplete blocked ProfileSaver on HeapTrim for 29.298ms
D/JobProxy14: Scheduled alarm, request{id=15, tag=FilesSyncJob, transient=false}, delay 00:00:01 (from now), exact true, reschedule count 0
I/Choreographer: Skipped 1804 frames!  The application may be doing too much work on its main thread.
D/cache_test_DISK_: image read from disk 1066657249
D/cache_test_DISK_: image read from disk 297349192
D/cache_test_DISK_: image read from disk 1990549361
D/cache_test_DISK_: image read from disk -1422336219
D/cache_test_DISK_: image read from disk 271940146
D/cache_test_DISK_: image read from disk 1131770002
D/EGL_emulation: eglMakeCurrent: 0xcc8cd040: ver 2 0 (tinfo 0xc9c22d00)
```

**Comment by kuba-orlik** [comment]
Happening to me as well

**Comment by tobiasKaminsky** [comment]
We then need to extract this somehow into background…

**Comment by gustavohw** [comment]
Happening here as well.

Android version: 9
Device model: Samsung S10e
Stock or customized system: Stock
Nextcloud app version: 3.11.0
Nextcloud server version: 18.0.3

Freezes when clicking the cloud icon on the folder to configure auto upload.
DCIM Photo has over 4k files, video around 500, even the screenshot folder which has around 400 images freezes.

**Comment by JonnyHaystack** [comment]
I'm a bit confused as to what "upload existing files" means. Does this mean "upload files that exist on the server already" or does it mean "upload files that exist locally but haven't been synced, rather than only syncing new files that are created after enabling sync"?

It doesn't seem very clear to me. I had assumed it meant the latter, but now this new setting has been added that only gives you the option to overwrite or rename. So it seems like it's actually the first meaning? Otherwise you would have options like "use remote" or "use local" for a conflict, which is what I would've expected.

**Comment by tobiasKaminsky** [comment]
it means "upload any file in this folder on device".
This can then of course create many conflicts, if the files already exists on server.
(most would use it with "move file", so that this cannot happen)

**Comment by tobiasKaminsky** [comment]
Is this freezing still happening on 3.12 RC2? 
(available via googe play store beta program)

**Comment by trancilo** [comment]
> Is this freezing still happening on 3.12 RC2?
> (available via googe play store beta program)

I am experiencing this bug on 3.12.0 on android 8.1.0

**Comment by tobiasKaminsky** [comment]
> Which fixes this bug.

So it should be meanwhile in stable version.

If this still happens, please re-open.

**Comment by arthurtaborda** [comment]
I have the same issue, android 10, nextcloud 3.14.3
