### ISSUE TITLE
Nextcloudapp Absturzproblem

### ISSUE THREAD

**Issue by JoOeli** [nextcloud/android#5619]
Hallo,
nutze sehr gerne die Nextcloud und hatte mir dazu  die App Nextcloud Notes gekauft.
Sie funktionierte anfänglich auch sehr gut nur kann ich sie jetzt seit einiger Zeit nicht mehr öffnen.
Die App läuft auf einem **Shift6m** unter **Android 8.0.0**.
Vorgehensweise:
1. App Start über das Symbol
2. Fehlermeldung: Notizen wurde beendet
3. App wieder öffnen angetippt
4. Notizen wird wiederholt beendet App schließen...
wenn ich lange auf das Symbol drücke sehe ich die zuletzt bearbeiteten Kategorien und die Option "neue Notiz" darüber komme ich in die App hinein und kann bearbeiten/ erstellen. Beim drücken auf den Zurück_Pfeil schließt sich die App dann  wieder.
Habe schon deinstalliert und wieder neu installiert hat aber nichts geholfen.
**Nach Löschen des Speichers stürzte beim ersten Neustart auch die Nextcloudapp ab.**

*Additional infos by @stefan-niedermann:*

- Nextcloud Android Version: 3.10.1
- Exception: `ArrayIndexOutOfBoundsException`
- Unfortunately no stacktrace

![Screenshot_Google_Play-Dienste_20200310-185904](https://user-images.githubusercontent.com/62028875/76344530-06990f00-6302-11ea-90db-ce29ae6ff1bc.png)
![Screenshot_Google_Play-Dienste_20200310-185918](https://user-images.githubusercontent.com/62028875/76344531-0731a580-6302-11ea-8e65-b8b101da0fed.png)
![Screenshot_Google_Play-Dienste_20200310-185932](https://user-images.githubusercontent.com/62028875/76344533-0731a580-6302-11ea-8d3f-93003189356d.png)
![Screenshot_Google_Play-Dienste_20200310-185940](https://user-images.githubusercontent.com/62028875/76344534-07ca3c00-6302-11ea-8926-c7e241f3f1da.png)
![Screenshot_SHIFT_Home_20200310-185822](https://user-images.githubusercontent.com/62028875/76344535-07ca3c00-6302-11ea-862f-d935e60e6e8b.png)
![Screenshot_Google_Play-Dienste_20200310-185843](https://user-images.githubusercontent.com/62028875/76344537-07ca3c00-6302-11ea-9ae9-98e36ba661c7.png)
![Screenshot_Google_Play-Dienste_20200310-185851](https://user-images.githubusercontent.com/62028875/76344538-0862d280-6302-11ea-80ac-7ccb56162af7.png)

**Comment by tobiasKaminsky** [comment]
It crashes in TextLine.
Do you use this somewhere @stefan-niedermann?

**Comment by stefan-niedermann** [comment]
No, i don't use `TextLine` anywhere in the Notes app. Just did a fulltext search to confirm this.

**Comment by tobiasKaminsky** [comment]
https://stackoverflow.com/questions/55135222/android-textview-gives-indexoutofboundsexception-textline-handlerun

Maybe something like this?
Have you a race condition in Notes? Or it tries to show non-printable chars?

**Comment by stefan-niedermann** [comment]
After all i am pretty sure this is a issue in the Files app. The user deleted the storage of *both* apps and then started the *Files* app where it crashed.

> Nach Löschen des Speichers stürzte beim ersten Neustart auch die Nextcloudapp ab.

@JoOeli könntest du bitte noch einmal einen Blick darauf werfen: Kannst du bitte Notes komplett deinstallieren und nur versuchen, die Nexcloudapp zu starten? Stürzt diese immer ab bei dir oder funktioniert diese alleinstehend?

**Comment by JoOeli** [comment]
Notizen komplett deinstalliert. Nextcloud läuft danach ohne Absturz. Wenn ich aber den Speicher bei Nextcloud lösche und die App starte werden die Ordner angezeigt, dann öffne ich einen Ordner- es kommt die Abfrage, ob meinem eigenen Zertifikat vertraut werden soll- dies bestätigte ich mit ja und danach stürzt Nextcloud ab. Nach einem Neustart der App läuft sie wieder ohne Probleme. Notizen nochmals danach neu installiert stürzt sofort ab.

**Comment by stefan-niedermann** [comment]
Scheint mir ein Zertifikats-Problem zu sein @tobiasKaminsky - Dass Notes danach sofort abstürzt erscheint mir als Folgefehler korrekt, wenn der eigentliche Fehler in der Files-App liegt.

Für mich wäre ein Test-Account zum Nachvollziehen interessant. Kannst du mir einen Test-Account einrichten @JoOeli ? Die Zugsangsdaten dann an info@niedermann.it, ich leite sie vertraulich an @tobiasKaminsky weiter.

Was ich nach wie vor nicht verstehe ist, wie es überhaupt zu einem derartigen Total-Absturz kommen kann - Ich dachte ihr verwendet inzwischen auch überalls einen `UncaughtExceptionHandler`, @tobiasKaminsky ?

**Comment by tobiasKaminsky** [comment]
> Ich dachte ihr verwendet inzwischen auch überalls einen `UncaughtExceptionHandler`, @tobiasKaminsky ?

Machen wir eigentlich auch…Aber evtl. wird das irgendwie vom System unterdrückt? Oder das ist der System Abstuhzrhändler.

**Comment by stefan-niedermann** [comment]
Kurzes update für dich @tobiasKaminsky ich habe von @JoOeli Test-Zugangs-Daten erhalten und konnte mich mit diesen auf diversen Geräten erfolgreich einloggen (beide Apps).

@JoOeli ist ebenfalls in der Lage, sich testweise von einem geliehenem Geräte einzuloggen.

Ich vermute daher ein lokales Problem mit seinem Smartphone. Wir sind so verblieben, dass er nun vorübergehend Carnet nutzt und hin und wieder die Konstellation mit Notes noch einmal versucht.

Ich denke, hier ist erstmal nicht viel, was wir noch tun können, da der Fehler sich von anderen Geräten aus nicht nachstellen lässt. :-/
