### ISSUE TITLE
Auto-Upload doesn't work - 3.10.1 (Android 10)

### ISSUE THREAD

**Issue by 120e314** [nextcloud/android#5649]
### Actual behaviour
Our Folders in the Nextcloud are set up for automatically Upload. If we take a picture with the Android-App "Open Camera", the pictures will be locally saved and then uploaded in the Nextcloud. These pictures aren't uploaded until we have a WLAN-Connection to our Network, to these steps everything is right. So but if we have the WLAN-Connection to our Network the Nextcloud trying to upload the pictures, without success. When i go in the Nextcloud-App --> Menu --> Uploads i see that the Nextcloud waiting for a WLAN-Connection, even though our Connection is stable.
We tried that with some other Devices like the "Samsung Galaxy X Cover 4" (Android 9), here its working alright.

Another interesting Point..
If we choose some pictures and upload them manually in the Nextcloud it works but only with an amount of max 6 pictures...

What can we do to solve our problem with the automatically Upload?

### Environment data
Android version:
10

Device model: 
Samsung Galaxy S10e

Stock or customized system:
customized

Nextcloud app version:
3.10.1

Nextcloud server version:
16.0.4

#### Web server error log
```
Insert your webserver log here
No log

#### Nextcloud log (data/nextcloud.log)
```
No log
```

**Comment by tobiasKaminsky** [comment]
Have you disabled/excluded the app from battery saving mechanism?

**Comment by 120e314** [comment]
Yes, the battery saving mechanism is disabled for the nextcloud-app.
