### ISSUE TITLE
Dark mode results in dark-on-dark elements only visible at high screen brightness

### ISSUE THREAD

**Issue by o8k57** [nextcloud/android#5657]
Submitting this as requested by the developer in response to Play review.

### Steps to reproduce
1. Set dark mode
2. Set brightness lower than half way
3. Look at the app

### Expected behaviour
- Setting dark mode should apply a dark theme, but any control elements (menus buttons, action buttons, button labels) should have lighter elements so the user can see where they are and what they do.

### Actual behaviour
- Menu controls and button labels are dark, so cannot be seen. Some not at all, others only when the screen is set to very high or maximum brightness which is not desirable in low light conditions. 

### Environment data
Android version: 8.1.0

Device model: Samsung S9

Stock or customized system: LineageOS 15.1

Nextcloud app version: 3.10.1

Nextcloud server version: 18.02 (affects previous versions too)

top right and top left menus invisible
![1 - top right and top left menus invisible](https://user-images.githubusercontent.com/19149667/76633922-68918880-653d-11ea-99a3-81efb924d458.png)

keep and delete button text only visible at very high brightness
![2 - keep and delete button text](https://user-images.githubusercontent.com/19149667/76633970-7b0bc200-653d-11ea-8927-43bb188fe6d5.png)

dark icons on dark background only visible with very high brightness
![3 - dark on dark only visible with high brightness](https://user-images.githubusercontent.com/19149667/76633995-8a8b0b00-653d-11ea-8f55-3fc4a027bf59.png)

"cancel" action button text only visible with very high brightness.
![4 - cancel text only visible with high brightness](https://user-images.githubusercontent.com/19149667/76634032-9bd41780-653d-11ea-96f1-3999dcdd51b6.png)

**Comment by AndyScherzinger** [comment]
cc @tobiasKaminsky @dan0xii @nextcloud/designers @jancborchardt the reason for this (in this scenario) is that the primary color set via server-side theming it "black" and then the dark them has been chosen on the client. So to some extend we need to implement the same logic @tobiasKaminsky implemented for setting "white" as primary color on the server-side and choosing the light theme on the client-side.

**Comment by o8k57** [comment]
> cc @tobiasKaminsky @dan0xii @nextcloud/designers @jancborchardt the reason for this (in this scenario) is that the primary color set via server-side theming it "black" and then the dark them has been chosen on the client. So to some extend we need to implement the same logic @tobiasKaminsky implemented for setting "white" as primary color on the server-side and choosing the light theme on the client-side.

I just updated the server side theme to the default black on white - not a problem as I rarely use the web interface. However that only appears to fix the issue in the first image (top left and top right menus). Icons and button text are still dark-on-dark.

**Comment by AndyScherzinger** [comment]
@o8k57 I am hoping that @dan0xii's fixes will largely improve the situation 🙏

**Comment by dan0xii** [comment]
> @o8k57 I am hoping that @dan0xii's fixes will largely improve the situation pray

Pretty sure this was all covered off by #5658.

**Comment by tobiasKaminsky** [comment]
Closing, as fixed by #5658.
If not, please re-open.
