### ISSUE TITLE
Cannot remove automatically created "AutoUpload" folder even after changing default

### ISSUE THREAD

**Issue by petemagnusson** [nextcloud/android#5659]
### Is your feature request related to a problem? Please describe.
In the versions of nextCloud from 14 to 18 i have a "Auto Upload" folder.
I cant select what is being uploaded there, but it dose take my camera roll from my Android device.
I have setup other places i want to auto upload to, but i cant disable the "Autoupload" folder in the root of my user account folder.

### Describe the solution you'd like
It is great to be able to auto upload all photos to a folder but i would like to have the option to not do this but rather do this by choise.

### Describe alternatives you've considered
I have removed all the auto upload sync folders and started new, it dont help however, this AutoUpload folder even after deleten is auto created.

![nextcloud_autoupload](https://user-images.githubusercontent.com/8865134/76703323-4cbeeb80-66d1-11ea-8c0d-b1ca3193030f.png)

**Comment by AndyScherzinger** [comment]
@petemagnusson thanks for the report. Within the auto upload section (via the main menu) you can actually choose a distinct folder for each of your auto upload (list) entries vie the configure menu item.

So I rather consider this a bug.

You mentioned you removed/deactivated all auto upload entries in the auto upload section?
* Are there any uploads still in the upload queue triggered by the auto upload (see Uploads section)?
* Your folder shows >250MB so are the images within this folder being uploaded very recently from a single device? (just to check you don't have several devices uploading to the same server folder).
* did you configure distinct/different folders for your auto upload items?

**Comment by petemagnusson** [comment]
Hi @AndyScherzinger ,
Sorry for my late reply.

I was hoping i had missed something :)

Yes everything under "Autoupload" was removed, and content was still being uploaded tot he "AutomastiskUppladdning" folder. To me it looks like a background service of sorts.

Answers to your question:
1, No, i cleared those out completely. 
2, Yes, it is just one active device in this account. 
3, Yes for most of them. There as i am on Android and use different camera apps these will have different folders on the device, but i want them all to go in to the same folder. 
There are other folders where i upload just one folder content from the device to NextCloud.

Thanks and have a great day!

**Comment by nicbou** [comment]
I have the same issue. When I change the folder, the uploads continue to the old location until I cancel them in the Uploads panel. However that cancels those uploads forever. They're never uploaded to the new location.

Newly taken pictures are uploaded just fine.

**Comment by joshtrichards** [comment]
Hi @petemagnusson - Are you still experiencing this?

If so:

> Your folder shows >250MB so are the images within this folder being uploaded very recently from a single device? (just to check you don't have several devices uploading to the same server folder).

What are the files in there?
