### ISSUE TITLE
Get last modified time from SAF files?

### ISSUE THREAD

**Issue by ChristianTacke** [nextcloud/android#5660]
### Is your feature request related to a problem? Please describe.
I would like the last modified time on the server to also be set correctly when uploading files from other apps.

### Describe the solution you'd like
According to [this stackoverflow posting](https://stackoverflow.com/questions/35744654/storage-access-framework-set-last-modified-date-of-local-documentfile) (reading part), it might be possible to use `leakedContentResolver.query(currentUi, null, null, null, null)` and `cursor.getLong(cursor.getColumnIndexOrThrow(DocumentsContract.Document.COLUMN_LAST_MODIFIED))` to get the last modified time of a "Document" in SAF.

One could possibly use this in `src/main/java/com/owncloud/android/ui/asynctasks/CopyAndUploadContentUrisTask.java`, method `doInBackground()` and then either set the mtime of the temporary file or give that time to the final upload function.

Could this work? I am not an Android Developer, I have just researched a bit. And maybe this is all complete nonsense?

### Describe alternatives you've considered
* If it is possible to get the last modified time from a "file from an app", please try to set it on the server during upload.
* If that's not possible, then possibly document this in a place that search engines can

**Comment by AndyScherzinger** [comment]
Thanks for the report and research @ChristianTacke 

pinging @tobiasKaminsky since he knows most about SAF regarding the Nextcloud Android client ❤️

**Comment by ChristianTacke** [comment]
Hi @tobiasKaminsky and @AndyScherzinger

it's been two months since the last post on this issue.
Any updates?

**Comment by AndyScherzinger** [comment]
Hi @ChristianTacke, no update from my side (not much time to contribute at the moment), so pinigng @tobiasKaminsky about this again.

**Comment by tobiasKaminsky** [comment]
Unfortunately no time right now to inspect this :/
As it is no bug, I fear that it will take some time until I have a chance to look into this…

**Comment by ChristianTacke** [comment]
Hi @tobiasKaminsky and @AndyScherzinger

Thanks for the update and letting me know, what the current status is.

**Comment by ChristianTacke** [comment]
Thanks everybody!
