### ISSUE TITLE
Accents block the display of files

### ISSUE THREAD

**Issue by Kaor** [nextcloud/android#5668]
### Steps to reproduce
1. Have a directory with an accent, eg : "Élisa"
2. Try to display files inside
3. Refresh do nothing : no files

### Expected behaviour
- show files

### Actual behaviour
- no files

### Environment data
Android version : 9

Device model : on many phones 

Stock or customized system :  android or lineage

Nextcloud app version: 3.10.1

Nextcloud server version: 16.0.9

**Comment by tobiasKaminsky** [comment]
I cannot reproduce this.
What kind of file system do you use?
Is this on an external storage?
Is this also happening on web?
How was the folder created?

**Comment by Kaor** [comment]
i reproduce it here, with another account and folder
What kind of file system do you use? android 9 and lineageos 16 on 3 differents phones : sony, xiaomi, asus
Is this on an external storage? no
Is this also happening on web? no
How was the folder created? on web

**Comment by tobiasKaminsky** [comment]
what file system on server do you use? 
Which distribution?

Can you create us a test account, test if the problem occurs also there and if so send the credentials to tobias at nextcloud dot com with a reference to this issue?

**Comment by Kaor** [comment]
Debian 10
since Nextcloud 16.0.9 upgrade
problem is solved !
i close
