### ISSUE TITLE
Upload files only when connected to home WiFi

### ISSUE THREAD

**Issue by TheLastGimbus** [nextcloud/android#5670]
### Problem

Many people (including me) use Nextcloud only inside their home WiFi network. Even NextCloudPi installer asks you if you want to connect to server outside of your home or not. Therefore, there is no sense for app to even try to connect to server (which is 192.168.x.x) if phone is outside of home wifi. Those "Upload failed" notifications annoy me so much.

### Solution

We could use something as dumb as reading network name/mac (would require location permission) and comparing it to home name, but we could just try to ping server and see if it's available.
This can be done together with #1683

##### Post Scriptum

I'm not sure how Nextcloud authenticates server, so I'm not sure if this isn't even a security threat. If someone could make fake NC server on other network, and trick our app to sending all files to itself. Is this possible?

**Comment by asuh** [comment]
This is an understated issue that many more of us are experiencing. I'm using [Seedvault](https://github.com/seedvault-app/seedvault) for backup with similar results as OP.

It's more of an annoyance than anything but the endless number of new notifications saying the upload failed doesn't make sense.

One other solution that's a bit harder but could be valuable is allowing some type of switching from the local non-routable IP (like 192.168.x.x) to either an authenticaed virtual hostname (many dyndns type services can provide this) or through a VPN tunnel to the same LAN IP address for Nextcloud. With either method, backup can still be continuous but Nextcloud can have an offsite address or direct tunnel to use for the same purpose.

Despite this potential solution, it would be good if Nextcloud Android app found a way to prevent unnecessary traffic to an IP address that is available on in a specific network.

**Comment by TheLastGimbus** [comment]
Finally I managed to open DMZ on my router and I use DuckDNS + Caddy. Tho many people simple don't have that ability because f.e. their ISP prevents it :confused:

**Comment by joshtrichards** [comment]
Let's consolidate tracking this in #821. I encourage you to subscribe, add to the discussion, and/or upvote 👍 that issue.
