### ISSUE TITLE
unable to connect to the server

### ISSUE THREAD

**Issue by Amanuense-del-diavolo** [nextcloud/android#5671]
Every time It tries to check the connection to the server it fails giving this error

### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by Amanuense-del-diavolo** [comment]
there was a configuration erro by mi side, sorry fot the useless issue

**Comment by AndyScherzinger** [comment]
No worries, while you got matters resolved, still thanks for taking the time to write a report and also to provide the feedback that it has been resolved. :)
