### ISSUE TITLE
Broken conflict dialogue

### ISSUE THREAD

**Issue by juanjosegarciaripoll** [nextcloud/android#5672]
### Steps to reproduce
1. Create a file elsewhere
2. Upload a file with same name
3. Conflict dialogue pops up
4. Select to keep the newer version
5. Local version is replaced with remote one and not uploaded

### Expected behaviour
- The newer file that has been uploaded should replace the remotely created (and older) file

### Actual behaviour
- The remote file does not change
- The local file is erased and replaced with the remote one

### Environment data
Android version: 8.1.0

Device model: BQ Aquaris

Stock or customized system: Stock

Nextcloud app version: 3.11.0 RC2

Nextcloud server version: unknown (Corporate install)

**Comment by tobiasKaminsky** [comment]
This is fixed via #5675 
There will be a RC3 soon.
Please report back if this then still happens.
