### ISSUE TITLE
Exiting full-screen video player

### ISSUE THREAD

**Issue by pilsnerbeer** [nextcloud/android#5678]
### Steps to reproduce
1. open a video, let it play
2.  tap the screen to make it full-screen
3. tap BACK to exit back to directory

### Expected behaviour
one BACK press is required to exit the video
### Actual behaviour
two presses are actually required. One tap exits back to the same video, only this time non-fullscreen mode.

Additionally, (in STEP 2) it takes a long time to load the video in full-screen mode (especially for longer videos). If this load time cannot be eliminated, I would suggest to show a progress circle to notify the user of loading process. On top of this, entering the full-screen mode could be handled with a dedicated icon placed somewhere in the edge of the screen to prevent accidental entering of full-screen mode by user (because of the long load time).
### Environment data
Android version: 9
App version: 3.10.1

**Comment by tobiasKaminsky** [comment]
For me this is the intended behaviour:
- play a video
- click on it to enter fullscreen
- click back to exit fullscreen, but video keeps running
- click back to exit video

For example VLC also only exits fullscreen mode, when pressing esc, but not ending it.

@nextcloud/designers your input please

**Comment by buddebej** [comment]
I would like to confirm the problem that you mention in STEP 2:

When switching to full screen, I'm getting nothing but a black screen. @pilsnerbeer is right: Smaller vidoes will start playing after some seconds. Larger files are never showing any full screen playback in my setup. Eventually, I need to restart the app to get back to normal operation.

Expected: No loading time when switching between fullscreen / small screen. If not possible: Show a loading animation.

This behavior has already described in #4066 and #3745 but both issues were closed without comment.

**Comment by tobiasKaminsky** [comment]
Please do not mix issues, but create a new one for this.

**Comment by jancborchardt** [comment]
> For me this is the intended behaviour:
> 
>     * play a video
> 
>     * click on it to enter fullscreen
> 
>     * click back to exit fullscreen, but video keeps running
> 
>     * click back to exit video
> 
> 
> For example VLC also only exits fullscreen mode, when pressing esc, but not ending it.
> 
> @nextcloud/designers your input please

Yep, this is indeed intended, and that’s how it works. :) Closing this issue hence.
