### ISSUE TITLE
Auto upload of non media folders?

### ISSUE THREAD

**Issue by Olangu** [nextcloud/android#568]
### Actual behaviour
-When choosing auto upload tab a list of media (picture) directories are listed and selectable for auto upload.

### Expected behaviour
-Some option to select non media or hidden media (.nomedia) foldes shall exist.
 
### Steps to reproduce
1. Open auto upload
2. No way to select non media folders
3. 

### Environment data
Android version:
CM-13

Device model: 
SM-G850F

Stock or customized system:
custom

Nextcloud app version:
Nextcloud beta 20170117

Nextcloud server version:
Nextcloud 

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

**Comment by AndyScherzinger** [comment]
Hi @Olangu this is on out auto upload agend, see #285
