### ISSUE TITLE
net::ERR_SSL_VERSION_OR_CIPHER_MISMATCH

### ISSUE THREAD

**Issue by vitorinux** [nextcloud/android#5680]
### Steps to reproduce
1. Google Play BETA TESTER
2. Download app
3. Open and enter domain 

### Expected behaviour
- Redirect to login page (https://MYDOMAIN-OR-IP/index.php/login/flow)

### Actual behaviour
- Stuck on info page with the error
 
### Environment data
Android version:
5.1.1
Device model: 
GT-I9300
Stock or customized system:
ArchDroid-STABLE-3.1.5 (CM 12.1-20151112-i9300)
Nextcloud app version:
3.11.0 RC2
Nextcloud server version:
I've tried on
- 16
- 17
- 18.0.2 (actual)

#### Web server error log
 NO ERROR DETECTED 

Insert your webserver log here
ACCESS.LOG
`192.168.10.35 - - [17/Mar/2020:22:32:42 +0100] "GET /status.php HTTP/1.1" 200 179 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.11.0 RC2"
192.168.10.35 - - [17/Mar/2020:22:32:43 +0100] "HEAD /remote.php/webdav/ HTTP/1.1" 401 0 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.11.0 RC2"`

#### Nextcloud log (data/nextcloud.log)
NO LOG DETECTED (while accessing)
Insert your Nextcloud log here
NO LOG DETECTED (while accessing)
 
#### ADITIONAL INFO (about cipher web server)
`ssl_session_timeout 1d; ssl_session_cache shared:SSL:50m;
ssl_session_tickets off; ssl_protocols TLSv1.3 TLSv1.2;
ssl_ciphers 'TLS-CHACHA20-POLY1305-SHA256:TLS-AES-256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384';
ssl_ecdh_curve X448:secp521r1:secp384r1:prime256v1;`

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Hm. 
Android is rather old and it is a custom rom.
Which kind of cipher do you allow on your server? Maybe the one your device is capable is not enabled?

**Comment by vitorinux** [comment]
Im trying disabling some ciphers and do less secure my nextcoud deploy but... is not the key.

When comment "ssl_ciphers" line of my nginx config works properly. Just trying...

Thanks for your quick reply, the issue is relate to my device, and adjusting parameters I can to get login app page.
