### ISSUE TITLE
Forward of files from shared folder not possible (only!) in app

### ISSUE THREAD

**Issue by DTMW2** [nextcloud/android#5681]
### Steps to reproduce
1. User A: create folder F and share with internal user B with all rights granted
2. User B: login into web interface with browser -> forward of arbitrary file from folder F is possible (clicking on icon (A) indicating that the file is owned by user A)
3. User B: open android app (newest/current version) using stored credentials of user B -> forward of thats same file is NOT possible (clicking on icon (A)) only opens detail menu allowing to copy via link

### Expected behaviour
- The app should be able to forward not only files from folders created by oneself but from other users, too (if settings allow to do that) - like shown in "Steps to reproduce" the web interface is able to do that

### Actual behaviour
- As expected forwarding is possible via the web interface but not via the app.
- Workaround in the app for user B: copy one file owned by user A in an arbitrary own folder (owned by user A). Magic: suddenly it is possible to forward that exact file and at the same time another icon is used by the app (not circle with first char of username but sharing-icon)

### Environment data
Android version: 10

Device model: Sony ZX2 Compact

Stock or customized system: stock

Nextcloud app version: 3.10.1

Nextcloud server version: 17.0.3

**Comment by tobiasKaminsky** [comment]
What do you mean with "forward"? Share it again?

**Comment by DTMW2** [comment]
Yes share it again ("Teilen" in geman) -> the function to hand over a file e.g. to my instant messenger, or my mail client.

**Comment by tobiasKaminsky** [comment]
Hm. Have you enabled "reshare" option for the file as user A?
("kann teilen")?

**Comment by DTMW2** [comment]
Hi, Tobias,

yes. reshare is enabled (just rechecked it now + checked it before filing this bug report).

**Comment by tobiasKaminsky** [comment]
> * As expected forwarding is possible via the web interface but not via the app.
> 



>  the function to hand over a file e.g. to my instant messenger, or my mail client.

This somehow is not the same, or? As in web you cannot share a file to another app.
