### ISSUE TITLE
German / Deutsch Android App Synchronisations Fehler

### ISSUE THREAD

**Issue by ElectroJo-73** [nextcloud/android#5683]
### Steps to reproduce
1. Login in the Nextcloud App
2. Create or click on a file

### Expected behaviour
- Tell us what should happen
I should See my Files in the App
### Actual behaviour
- Tell us what happens
I cannot See my Files in the app
### Environment data
Android version:
9.0
Device model: 
Motorola Moto G7 Power
Stock or customized system:
/
Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Can you create us a test account, test if the problem occurs also there and if so send the credentials to tobias at nextcloud dot com with a reference to this issue?
