### ISSUE TITLE
crash when creating new folders on cloud 

### ISSUE THREAD

**Issue by madox85** [nextcloud/android#5686]
app crashes when creating new folder on cloud within instant upload dialog 

************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
	at com.owncloud.android.ui.dialog.CreateFolderDialogFragment.onClick(CreateFolderDialogFragment.java:140)
	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7811)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: starlte
Model: SM-G960F
Id: QP1A.190711.020
Product: starltexx

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: G960FXXS7DTB5

**Comment by tobiasKaminsky** [comment]
It seems that the parent folder is not correctly set-up.
Where do you want to create a folder?

**Comment by madox85** [comment]
Hi,

I tried to create the folder in the root directory of my Nextcloud
Server. The Name of the folder, I tried to create was "Hörbücher" (There
are also other folders with special caracters on that cloud server)

Thanks again.

**Comment by tobiasKaminsky** [comment]
Is this happening reliable? 
Can you test it without any special chars?

**Comment by madox85** [comment]
Hi Tobias,

Thank you.

I'd just created 3 new folders, the same way, as before. One without,
two, with special characters. (One similar to the one, I doubt to be the
root of that error. (Hörbücher2)) Every of that folders has been created
without any crash. I dont know, why. :-/

Am 30.03.20 um 13:33 schrieb Tobias Kaminsky:

**Comment by tobiasKaminsky** [comment]
Hm, strange.
Can you re-open it, if it occurs again?
