### ISSUE TITLE
Push Notifications -TCP

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/android#5700]
Push notifications on Android 10 are delayed. They are received only when the Nextcloud Android app is running.

Settings on Android:
Battery saving for the app - disabled
Sustained Wi-Fi connections - enabled.

When you set the Android app to run to manual, the background process appears. It changes so much that push notifications are received as soon as the smartphone wakes up.

Other Push notifications, e.g. from Android Talk work properly, i.e. they come immediately.

It looks like a TCP connection on port 5228. (heartbeats) is turned off.

@tobiasKaminsky  Is this a reason?

App:
Android 10
Nentcloud Android: 3.11.0 RC3
Nextcloud: 18.0.2

**Comment by tobiasKaminsky** [comment]
> Other Push notifications, e.g. from Android Talk work properly, i.e. they come immediately.

@mario do you have any special power saving settings?

**Comment by mario** [comment]
This is expected. Currently only Talk notifications are marked as high priority thus have the ability to wake up the device. (note that even this isn't guaranteed)

In the future, this should/needs to be extended to support 2fa via Nextcloud and I've already opened an issue for that. 

Most (all?) other things do not warrant an immediate response, so I'm therefore closing this issue.

**Comment by tobiasKaminsky** [comment]
Ok, valid for me, so no bug per se, but intended.

**Comment by Valdnet** [comment]
@tobiasKaminsky In my case, immediate push notifications in Nextcloud are important because I use the Phonetrack app in which I have set zones for devices. And these notifications should come immediately after crossing the zone.

**Comment by tobiasKaminsky** [comment]
This is always a trade off between battery consumption and up to date notifications.
As Mario said, we do not expect that any notification is important enough to force increase battery consumption.

**Comment by szaimen** [comment]
> In the future, this should/needs to be extended to support 2fa via Nextcloud and I've already opened an issue for that.

Do you have the issue number? I cannot find it and would like to subscribe...

**Comment by mario** [comment]
@szaimen https://github.com/nextcloud/notifications/issues/594

@Valdnet in these cases, it's the phonetrack that should probably show a high priority notification eventually. But anyway.

**Comment by Valdnet** [comment]
@mario I don't have information on the priority with which PhoneTrack notifications are sent, but I know for sure that for Android 4, 6 and 8 work properly for Nextcloud Android. They come immediately, so you can conclude that they work properly.

@tobiasKaminsky I think this problem is not about saving battery and should be solved for Android 9 and 10. Maybe the proposal @mario in issue: https://github.com/nextcloud/notifications/issues/594 will solve the problem.
I will add that Push notifications in other versions of Android (4, 6 and 8) for Nextcloud Android work correctly and do not consume a lot of battery. Push notifications come immediately, which fulfill their task, i.e. immediate notification of the user. In addition, I noticed that the Android Nextcloud process is sometimes active in the background and sometimes turns off for some reason.

**Comment by mario** [comment]
I do, they're sent as "normal". 

But anyway, each Android version introduces further restrictions on background processing - Android 10 is the worst. It can be partly mitigated by showing a foreground notification but you don't want to do that for everything, especially since the number of high priority notifications that will wake up the device are limited PER hour. The issue I posted will not solve the issue you're having, but only partly for 2FA notifications. Also, sometimes active / sometimes not is something the Android as a system decides, not us.
