### ISSUE TITLE
Clicking "On this device" and the "All Files" does not go back to all files screen

### ISSUE THREAD

**Issue by suokunlong** [nextcloud/android#5704]
### Steps to reproduce
1. Click "On this Device".
2. Click "All Files".

### Expected behaviour
- Nexcloud should go back to the all files screen.

### Actual behaviour
- Nextcloud remains at "On this Device" screen. To go back, a workaroud is to click "Activities" and then click "All Files".

It works ok in previous version.

### Environment data
Android version: 8.00

Device model: KNT-AL10, Huawei Honor V8.

Stock or customized system: Stock system provided by phone maker.

Nextcloud app version: 3.11.0 RC2

Nextcloud server version: 18.0.1

#### Nextcloud log (data/nextcloud.log)
I can't find the log file. Where is it? There is no such file in data/.

**Comment by xirikm** [comment]
I have the same problem.
It seems the issue has not been resolved in the version 3.11.0 (March, 26, 2020) on Google Play?

**Comment by tobiasKaminsky** [comment]
No, otherwise there would be a PR and this bug would be closed :)

**Comment by Shagequi** [comment]
Hi,

The issue has been "created" in one of the 147 commits since the beginning of March.

I'll find it out :)

**Comment by Shagequi** [comment]
It's due to this commit : bab00c6125545eacb8f489fe18a0070cf47ecdc2

**Comment by tobiasKaminsky** [comment]
Thanks for finding the commit, but this was only the backport.
This is the original commit/pr to master: https://github.com/nextcloud/android/pull/5617

So it seems, I fixed something and broke something else :see_no_evil: 
I will create a fix.
