### ISSUE TITLE
Where's the automatic synchronization? 

### ISSUE THREAD

**Issue by Bati4eli** [nextcloud/android#5706]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

Automatic synchronization doesn't work! 

### Environment data
Android version:
10
Device model: 
Xiaomi mi 9t
Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Can you explain what exactly does not work?
If a file is downloaded and a change (either locally or on server) is detected, it tries to sync the file, but only on wifi.
Otherwise you have to do this manually.
