### ISSUE TITLE
Sort order is not effective

### ISSUE THREAD

**Issue by ldmpub** [nextcloud/android#572]
Switching from one sort order to an other has no effect.

See video where I wanted to sort Alphabetical (order A - Z):
http://dl.free.fr/mSJbHjaLG

Android version: 6.0.1
Nextcloud app version: 1.4.1 RC4

**Comment by AndyScherzinger** [comment]
#575 might solve this even though I couldn't reproduce this issue on an Emulator running Android 6 :(

**Comment by AndyScherzinger** [comment]
@ldmpub is the actual beta working for you? -> https://f-droid.org/repository/browse/?fdfilter=Nextcloud&fdid=com.nextcloud.android.beta

**Comment by ldmpub** [comment]
@AndyScherzinger: yes sort order is ok with the new sort design "I proposed :-) ;-)".

Just one more question: why the new screen is in english and I see no strings in Transifex to translate?

**Comment by AndyScherzinger** [comment]
They will become available in transifex the day after this gets merged to master :)

**Comment by tobiasKaminsky** [comment]
@ldmpub glad you like the/your new feature 👍

**Comment by AndyScherzinger** [comment]
It is not merged yet since it is scheduled for 1.5.0
