### ISSUE TITLE
3.11 RC4 : On first run, the slider is bypass

### ISSUE THREAD

**Issue by JorisBodin** [nextcloud/android#5736]
Hello,

The first time you open the application, you expect to get this:
![Screenshot_20200324-185617_Nextcloud](https://user-images.githubusercontent.com/2796439/77460637-a75af480-6e01-11ea-9f0b-7de141fbdd9b.jpg)

But it comes down to this:
![Screenshot_20200324-185624_Nextcloud](https://user-images.githubusercontent.com/2796439/77460684-b9d52e00-6e01-11ea-9fe2-250466b0ad40.jpg)

It used to happen only if the application was paused.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky @ezaquarii did you do any changes in this area for 3.11?

**Comment by JorisBodin** [comment]
@AndyScherzinger I searched the commit, it's from him: https://github.com/nextcloud/android/commit/4be18adc2d305f70b575b2deb469b01745d1c60f
I'm looking for the problem
