### ISSUE TITLE
Weird forum link in Participate page

### ISSUE THREAD

**Issue by ldmpub** [nextcloud/android#574]
Hi,

The english value for translation key 'participate_contribute_forum_text' is incorrect and does not display anything is the app: Menu > Participate.

It's true for all languages because english source is wrong and has been declined in other languages.

The value is currently set to:
Help others on the &lt;a href="%1$s>forum&lt;/a>

=> at least is misses a " and maybe more ;-(.

**Comment by AndyScherzinger** [comment]
Thanks for pointing this out @ldmpub 

@ all --> https://github.com/nextcloud/android/blob/master/res/values/strings.xml#L523

**Comment by tobiasKaminsky** [comment]
It is working for me in the latest master version on english?

**Comment by AndyScherzinger** [comment]
it might work depending on the Android version I guess. We should fix it nevertheless :)

**Comment by AndyScherzinger** [comment]
@mario do you have the time to fix the strings? :)

**Comment by mario** [comment]
@AndyScherzinger PR ready.
