### ISSUE TITLE
Not deleting account in Android app

### ISSUE THREAD

**Issue by FlyingEagle** [nextcloud/android#5745]
Hi,

I changed the URL of my Server and I can not found a option to change the url for an acoount in the android app.
So I decieded to delete that account and add a new one.
The adding worked well but I can not delete the old account.

No error messages nothing happened.

How can I delete it?

Regards

**Comment by tobiasKaminsky** [comment]
I tried:
- add an account
- disable my web server
- start app, see "no connection"
- open drawer, select account
- delete account
--> works

Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

**Comment by FlyingEagle** [comment]
i removed the app and installed new with new user(s).
but for the other issue, i remmoved it again.

**Comment by tobiasKaminsky** [comment]
So is it solved?
Sorry, I do not fully understand your answer :)
