### ISSUE TITLE
IPv6 AAAA record misunderstood

### ISSUE THREAD

**Issue by roncamma** [nextcloud/android#5746]
### Steps to reproduce
1. domain name (exemple.com) with only AAAA record
2. try to connect with the app using https://exemple.com

### Expected behaviour
The app should be connect to the server ising ipv6 address provided by the DNS

### Actual behaviour
The app can't find the server
error : Unable to fiind server

### Environment data
Android version: 10

Device model: OnePlus 6

Stock or customized system: Stock OxygenOS 10.3.1

Nextcloud app version: 3.10.1

Nextcloud server version: 17.0.3

### Test realized :
- No issues with a web browser.
- When I use directly the IPv6 addresse with the right format : https://[xxx.xx.x...] it works 👍
- If I put the address in incorrect format : https://xxx.xxxx... same error !
I believe that the app doesn't use the right format to connect to the host.
My android device resolve well the AAAA record. It works using Firefox on the same device.

Thanks.

**Comment by tobiasKaminsky** [comment]
Can you create us a test account and send the credentials to tobias at nextcloud dot com with a reference to this issue?

**Comment by roncamma** [comment]
Hello @tobiasKaminsky 
Email sent. Thank you !:)

**Comment by tobiasKaminsky** [comment]
Hm. No mail received?

**Comment by roncamma** [comment]
Is it okay now ?
Thanks.

**Comment by svennissel** [comment]
Same Problem with Samsung Galaxy S10e (Android 10). My nextcloud has an a and AAAA Record but in my Network the clients use IPv6 primary. My Nextcloud Version is 18.0.3. I run nextcloud in a docker container and behind a nginx https proxy.

**Comment by tobiasKaminsky** [comment]
> Is it okay now ?

Thanks, I received the mail and will have a look soon.

**Comment by svennissel** [comment]
In a tcpdump on the server i see no incomming traffic from the smartphone with the nextcloud app (connected over LTE).
My domain is subdomain.domain.de and my dns record is ipv6 ip in a short notation: 
*.domain.de. 86400 IN AAAA xxxx:xxx:xxx:xxxx::1

**Comment by tobiasKaminsky** [comment]
sorry for coming back so late.
I tested with @roncamma credentials via mail:
- on my laptop with ipv4 only: no connection at all
- with my Android 10 lineageos, with ipv4/ipv6: connection, browsing and image upload worked fine

I used the address to connect, even without https prefix, not the ip: next.xxx.tld

**Comment by roncamma** [comment]
Thanks Tobias for your message.
It works also for me now. Any app update ?
Or maybe the app use its own dns server ? Maybe the DNS record was not yet propagated to the dns server that app use when I post this issue.

**Comment by tobiasKaminsky** [comment]
Last update was ~2 weeks ago and we did not changed anthing in this regard.

**Comment by tobiasKaminsky** [comment]
@svennissel in your case I unfortunately do not have an idea :/

**Comment by svennissel** [comment]
In between a had turned on the firewall. So i have seen no packeges in TCP Dump. Know I see TCP errors "Port unreachable". But this will be a error with my nginx Proxy. Sorry for my wrong comments. Thank you for your help.
