### ISSUE TITLE
uploading stops every 4 files till any operation 

### ISSUE THREAD

**Issue by Whishay** [nextcloud/android#5758]
Hi,
I am trying to upload some files(2000+ pictures) to my server but it seems that the process stops every 4 file unless I check anything on the app(tap, checking setting..., any operations).

I found this on the 'uploads' status and I am not sure if it is a client or server issue. 
Anyone got the same issue?

App version:
3.11.0

Server:
Docker latest(Apache image)

**Comment by nimrodolev** [comment]
Experiencing the same issue - I didn't understand the pattern until I found this issue and figured out it's exactly what I'm seeing.

Enabled auto-upload for a couple of folders on my Android device with 200-300 total photos and with this strange behavior the sync is basically unusable.

Using the March 26th Android app release with a freshly installed docker container running the Apach image.

**Comment by tobiasKaminsky** [comment]
Is this happening only on Auto Upload?
What do you see in upload queue?
What devices do you have?

**Comment by nimrodolev** [comment]
1. This seems to only happen on Auto Upload. I tried just manually uploading 20+ files and they were all uploaded without this strange pause every 4 files.
2. When the upload pause the upload queue just lists the files to be uploaded (seems to be all of them), and are all listed as "Waiting to upload".
3. I'm the app installed on a Galaxy S7 (SM-G930F) running Android 8.
4. Interestingly, this might be affected by the number of items in the synced folder. I just turned on  "Auto upload" for a folder with only 9 items and they were all uploaded without a hitch.

**Comment by stefanpetter** [comment]
My girlfriend and I are experiencing the same problem on our Android phones, app version 3.11.0. It occurs only when selecting a folder to upload. InstantUpload works fine. Every 3/4 files we have to refresh the screen

**Comment by Whishay** [comment]
Hi Nimrod,
Thanks for your reply, this is the info.

Q: Is this happening only on Auto Upload?
A: Not exactly, it replicates on a manual uploading and I tried both 2k+ or  20+ files. 
It seems it is not related to the file numbers.

Q: What do you see in upload queue?
A: The queue lists the files and the progress bar advances for the first 4 files and stops after that until refreshing the screen or the app.

Q: What devices do you have?
A: It is a vivo running android 9.

**Comment by Whishay** [comment]
I took a day to set up android studio and gave it a debug. It turns out that the uploading hangs in ChunkedFileUploadRemoteOperation.java, specifically in function run().

The 'createFold' always successes, I set two breakpoints afterwards, one before and the other after 'client.executeMethod(listChunks)' and the second never hits after resuming the first one.

I am not familiar with android app/sdk, so I am going to stop here, anyone can help on this?

protected RemoteOperationResult run(OwnCloudClient client) {
            ........................................
            ........................................
            client.executeMethod(createFolder, 30000, 5000);
            
            // list chunks
            PropFindMethod listChunks = new PropFindMethod(uploadFolderUri,
                    WebdavUtils.getChunksPropSet(),
                                                           DavConstants.DEPTH_1);

            client.executeMethod(listChunks);
            
            if (!listChunks.succeeded()) {
                return new RemoteOperationResult(listChunks.succeeded(), listChunks);
            }
}

**Comment by tobiasKaminsky** [comment]
Then it might be that you hit a bug I fixed via https://github.com/nextcloud/android-library/pull/418

can you try out our dev version (you can install it in parallel): 
https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#developement-release

**Comment by Whishay** [comment]
Give a quick shot and it didn't work still on dev version 20200405.

BTW, the first few files includes files bigger than 1M and it works well with them.

**Comment by tobiasKaminsky** [comment]
So only files <1Mb are failing?

**Comment by stefanpetter** [comment]
> So only files <1Mb are failing?

No, also files > 1Mb are failing. I tried to upload 900+ photo's. Each photo around 2,5MB.

**Comment by Whishay** [comment]
> > So only files <1Mb are failing?
> 
> No, also files > 1Mb are failing. I tried to upload 900+ photo's. Each photo around 2,5MB.

Exactly, it seems that the size of files doesn't make sense.

**Comment by Whishay** [comment]
Is anyone working on this? It seems this is a basic and common issue suffered by many users. 
This blocks the entire experience of using this cool tool/app.

**Comment by ezaquarii** [comment]
> Is anyone working on this?

A fix is pending: https://github.com/nextcloud/android-library/pull/424

**Comment by Whishay** [comment]
Chris,
Awesome and thank you very much. I will give it a try later on.

**Comment by joshtrichards** [comment]
Fixed in nextcloud/android-library#424 (and several spin-off PRs)
