### ISSUE TITLE
Share icon in the file list should be grey and have some information

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/android#577]
My wife and me always get confused by the black share icon. I always try to click it to get information from whom the file was shared or expect it to allow me to share it.
But it just opens the file/folder.

If you only want to indicate that the file is shared, the icon should be gray scaled and not black

**Comment by AndyScherzinger** [comment]
I am on it :)

**Comment by AndyScherzinger** [comment]
PR has been opened for design discussion: #578
