### ISSUE TITLE
Manage Accounts & User Info are missing back button

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#5774]
![2020-03-30-153456](https://user-images.githubusercontent.com/5836855/77918336-0609ed80-729c-11ea-979f-9f20c7bcf1eb.png) ![2020-03-30-153452](https://user-images.githubusercontent.com/5836855/77918338-06a28400-729c-11ea-963d-addfbbc8da0c.png)

Thanks for finding @AndyScherzinger

**Comment by chawki505** [comment]
Hello,
I'm going to do this if nobody started doing it.
