### ISSUE TITLE
Unsync a file

### ISSUE THREAD

**Issue by gucu** [nextcloud/android#5783]
### Is your feature request related to a problem? Please describe.
I have downloaded a photo to my phone but my phone is running out of space. There does not seem anyway of unsyncing that file.

### Describe the solution you'd like
On the app menu a way of saving stop saving file.

Thanks

Rich

**Comment by AndyScherzinger** [comment]
@gucu you can click delete an then choose "local only"

**Comment by gucu** [comment]
Thanks for sorting it out. This is the very day God acted—let’s celebrate and be festive!Rich07546 804439https://gucu.org.ukhttps://cregy.uk/https://cregy.org/On 31 Mar 2020 1:11 pm, Andy Scherzinger <notifications@github.com> wrote:
@gucu you can click delete an then choose "local only"
