### ISSUE TITLE
Add settings option to disable all autoupload features

### ISSUE THREAD

**Issue by ApolloLV** [nextcloud/android#5784]
### Is your feature request related to a problem? Please describe.
When I use the Nextcloud app on my android phone, I repeatedly get notifications about automatic upload of new "detected" media folders. I tend to swipe those away instinctively and that tends to not happen all too often, but its still annoying. Today I got across that notification again, and finally decided that it was so unnecessary and distracting I wanted to disable autoupload entirely. I don't plan to use it ever, so I don't want to be bugged about it. Lo and behold, there is no option in the entire app to turn it off. I'd expect there to be a knob somewhere in settings, for example under notifications, or in the hamburger menu in the autoupload section. I expected something like "turn off autoupload". 
#3611 and #3672 (and other issues here) indicate that I am not the only one confused by this missing option.

### Describe the solution you'd like
I'd expect there to be a knob somewhere in settings, for example under notifications, or in the hamburger menu in the autoupload section. I expected something like "autoupload of media folders enabled" that I could toggle.

### Describe alternatives you've considered
An alternative solution is to disable notifications for the Nextcloud app. However, this is a OS-dependent feature only available in newer android versions and it requires additional steps. Additionally, it is error-prone in that a user might disable desirable notifications as well.
In the newest app versions, the notification itself has a disable button. This is easily missed, since at least on my phone I have to swipe down on the notification to be able to see that action button.
Some users also might want to disable autoupload proactively or after having swiped away the notification already.

### Additional context
I am using the Android Nextcloud App version 3.11.0 on lineageOS Android 9

**Comment by AndyScherzinger** [comment]
@ApolloLV your referenced issues are closed for a reason. The notification offers 2 actions one to configure the folder for auto upload one to disable such detections.

**Comment by ApolloLV** [comment]
Yes. I am fully aware of the notification action, which I do not consider an adequate solution to this usability issue. 
Other users in the aforementioned issues did also express the wish to have an in-app-setting, e.g. @beddari, @shscs911, and @rumwerfer. I consequently think it makes sense to have an explicit feature request for this.

**Comment by AndyScherzinger** [comment]
Which already has been decided against during the design phase of this feature, so looping in @nextcloud/designers and @jancborchardt to recheck if the decision needs to be revised and if a explicit option to disable folder detection for auto uploads should be added in the settings screen. (asking just to be sure/save since the design rule is "as little config options as possible/generally-useful)

**Comment by ApolloLV** [comment]
Sorry, I was unaware of this design rule.

**Comment by AndyScherzinger** [comment]
> Sorry, I was unaware of this design rule.

No worries, that's why I looped in @jancborchardt and @nextcloud/designers to comment and mayber decide otherwise (either way is fine with me personally, I just need to know if we want to change this).

**Comment by jancborchardt** [comment]
> The notification offers 2 actions one to configure the folder for auto upload one to disable such detections.

This seems to still be the proper solution. You deal with it when it comes up, in a "Don’t remind me again" fashion. This makes the settings manageable, new features discoverable as they come along, and possible to disable when it actually comes up.

**Comment by smihael** [comment]
I would still like to have that in Settings. When the notification comes up, usual behavior is to just swipe it away, _before_ checking the options within the notification. After that I opened the app to see if there is an option to disable the notification before it appears again. It is definitely not user friendly to manually create a new folder to reproduce what appears to me a bug, just to be presented with an option to disable this notifications. With such a design it is also unclear, how to enable auto upload notifications again once they are disabled.

**Comment by asavah** [comment]
Not having a global option for this annoying shit is bad design and bad UX.
Specially when you (re)install the app and it throws 20 notifications up your throat and it wouldn't come to my mind that one needs to expand the notifications so one can see the "disable" button.
Had to google which itself proves my pint about bad UX.
https://github.com/orgs/nextcloud/teams/designers

**Comment by robsdedude** [comment]
It's an old issue but I second this. This is bad UX. I couldn't figure out how to get rid of the scanning without reading one of the many issues. The fact that there are several issues from people not finding how to disable this is yet another indicator that the provided solution (deactivation button on the notification) while technically sound is not a user-friendly one. I'm asking you to reconsider this design decision.

**Comment by beddari** [comment]
Its still annoying in 2022, and not in line with how people expect to handle notifications. I have to manually train people.
