### ISSUE TITLE
App Crashes on start and bringes app to foreground

### ISSUE THREAD

**Issue by Hilzerak** [nextcloud/android#5785]
### Steps to reproduce
1. Open the App
2. 
3. 

Similar Problems here:
https://github.com/nextcloud/android/issues/4702
https://github.com/nextcloud/android/issues/4919

### Expected behaviour
- Open the App without crash

### Actual behaviour
- App Crashes directly after start

Nextcloud server version: 18.0.3

**** CAUSE OF ERROR ****

 android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
	at android.database.CursorWrapper.getString(CursorWrapper.java:137)
	at com.owncloud.android.datamodel.UploadsStorageManager.createOCUploadFromCursor(UploadsStorageManager.java:321)
	at com.owncloud.android.datamodel.UploadsStorageManager.getUploads(UploadsStorageManager.java:302)
	at com.owncloud.android.datamodel.UploadsStorageManager.getFailedUploads(UploadsStorageManager.java:368)
	at com.owncloud.android.files.services.FileUploader.retryFailedUploads(FileUploader.java:1005)
	at com.owncloud.android.utils.FilesSyncHelper.lambda$restartJobsIfNeeded$0(FilesSyncHelper.java:222)
	at com.owncloud.android.utils.-$$Lambda$FilesSyncHelper$fa2LBpPOxRVQOm4F_Glue5u4hdM.run(Unknown Source:10)
	at java.lang.Thread.run(Thread.java:764)

**** APP INFORMATION ****
ID: com.nextcloud.client
Version: 30110090
Build flavor: gplay

**** DEVICE INFORMATION ****
Brand: OnePlus
Device: OnePlus5
Model: ONEPLUS A5000
Id: PKQ1.180716.001
Product: OnePlus5

**** FIRMWARE ****
SDK: 28
Release: 9
Incremental: 2002242003

**Comment by InfamousUser** [comment]
I have a lot of crashes here as well, even more since the 3.11.0 update.

**Comment by tobiasKaminsky** [comment]
Do you have many pending uploads?

**Comment by Hilzerak** [comment]
Happend while syncing, yes. But now i cant do anything. App crashes directly after launch

**Comment by InfamousUser** [comment]
Yes, exactly, same here. I managed to get it to open by force stopping and turning off the radios.

**Comment by tobiasKaminsky** [comment]
> I just added the main storage directory to autoupload

You added the *entire* storage directory to auto upload? :fearful:

**Comment by InfamousUser** [comment]
Well yes, that is one of the reasons for installing Nextcloud, I want a phone backup. Google offers it including all the root-only data but it goes to their servers...

**Comment by Hilzerak** [comment]
> 
> 
> > I just added the main storage directory to autoupload
> 
> You added the _entire_ storage directory to auto upload? 😨

Why not? Are there any known limitations?

With the "radio off workaround" i got access to the app and disable all snycs exept 1.
The app now hangs farther(no response). Every 5-10min the app closes randomly. Then i can restart the app and it beginns to upload again,....

I think the mobile synching mode is completly unusable for large file count.
The sync speed is a joke too. I sync ~350 pictures within one hour. The filesize is 300MB. My device or network arent the problem. I can copy files within other apps with about 500-600mbit/s.
If i sync videos with the nextcloud app i get peaks to 3-5MB/s. Thats complete fine for me.
So the overhead / routine for small files must be realy realy bad.

I want to sync my pictures and videos from mobile device to nextcloud. filecount overall ~20.000.

**Comment by tobiasKaminsky** [comment]
> Why not? Are there any known limitations?

Not known limitations, but having the entire storage, which might change very often, is a bit untested ;-)

Regarding upload speed: we do chunked uploads with 10mb chunk size for bigger files.
This then takes a bit to assemble on server.

300Mb / h sounds a bit too slow…
Can you try to put your device on charger while uploading? Maybe your Android is throttling it…

**Comment by InfamousUser** [comment]
Please put entire storage to autoupload to test what's crashing it. There's lots of crashes and I don't have a slow phone. :)
Whole-phone backup to Nextcloud would be awesome in the future if possible.

**Comment by Hilzerak** [comment]
After about 2 weeks ive given up.
This feature is definitely not near close to stable.
App closes randomly. App not respond. App sync partially but don't go on with remaining files after that.
On other folder it sync only new files although the option "sync existing files" are enabled. Disabling, Enabling multiple times. Nothing happens.
The speed of small files (<2mb) is ridiculous low.

My devices isnt slow. My connection is for a mobile device pretty awesome. The server sitting on ssd and 16 core processor. The load from the system is going throug zero.
In the webserver access log-files for me nothing really happen if i add a new folder to sync and enable sync. would have expected many posts there....

If i can help with anything to identify this problem. Pls just ask. I've full access on the server and can try anything you want.

**Comment by InfamousUser** [comment]
Autoupload feature has never fully worked for me. There has always been some issue. And recently more issues than usual.

**Comment by tobiasKaminsky** [comment]
This might be better with #5679

**Comment by InfamousUser** [comment]
Great, will test when the update arrives!

**Comment by InfamousUser** [comment]
Retest guys, fixed for me with 3.11.1 beta. It crashes on uploads page now.

**Comment by tobiasKaminsky** [comment]
> Retest guys, fixed for me with 3.11.1 beta

Nice, then we can close it.



>  It crashes on uploads page now.

This is a different bug, which is already tracked.
