### ISSUE TITLE
Crash on conflict resolution

### ISSUE THREAD

**Issue by qguv** [nextcloud/android#5789]
### Steps to reproduce
1. Create file X on server
2. Create different file X locally
3. Trigger a sync
4. Wait until the conflict is detected
5. Tap the dots menu next to the conflicting file
6. "Downloading server version" message appears
7. Crash

### Expected behaviour

- I imagine there's some activity that shows the files and allows you to pick between them

### Actual behaviour

- App crash

### Can you reproduce this problem on https://try.nextcloud.com?

I'm sorry but I don't have time right now.

### App log

```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Can't toast on a thread that has not called Looper.prepare()
	at android.widget.Toast$TN.<init>(Toast.java:432)
	at android.widget.Toast.<init>(Toast.java:126)
	at android.widget.Toast.makeText(Toast.java:297)
	at android.widget.Toast.makeText(Toast.java:287)
	at android.widget.Toast.makeText(Toast.java:324)
	at com.owncloud.android.ui.activity.ConflictsResolveActivity.showErrorAndFinish(ConflictsResolveActivity.java:229)
	at com.owncloud.android.ui.activity.ConflictsResolveActivity.lambda$onStart$0$ConflictsResolveActivity(ConflictsResolveActivity.java:192)
	at com.owncloud.android.ui.activity.-$$Lambda$ConflictsResolveActivity$EM0Z1Vrhvmim7X4XXFnNqL4vK1A.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:919)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30110090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: motorola
Device: troika_sprout
Model: motorola one action
Id: QSBS30.62-17-4
Product: troika_reteu

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 6d5df
```

Nextcloud server version is 18.0.3

**Comment by AndyScherzinger** [comment]
Comment @droberg https://github.com/nextcloud/android/issues/5764#issuecomment-607160453

> Sorry for the late answer. I don't use GitHub since a while back.
>
> I'm not sure exactly what I did. I remember having a real messy situation with several files in conflict. (After several crashed uploads it seems.. ). This was my first attempt at using the app, and I was trying to upload all my pictures/movies. The app got stuck in a unresponsive state a few times directly after enabling the directory sync and was killed of by Android OS. Then it turned out that it was actually doing something in the background, but extremely slowly (like some kB per second) so I let it run for a long-long-long time without touching it (and thus not triggering the unresponsive kill thingy.) After that it claimed to have synced everything except for a few large movies and some images (10Mb and about 250Mb). During the attempts to solve this I tried several times but the same files kept coming back as in conflict, then it crashed.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky see
http://www.programmersought.com/article/27331310030/
https://fincoapps.com/java-lang-runtimeexception-cant-create-handler-inside-thread-that-has-not-called-looper-prepare/

Unfortunately we use the toast calling method within the UI thread _and_ within a child thread, the later causing the error, so we might have to add a flag to tell the toasting method to use a looper or (maybe?) use the looper within the child thread while I have never worked with loopers, so not an expert on this topic.
