### ISSUE TITLE
File actions in the list

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/android#579]
Currently it’s very cumbersome to do any action on a file. You have to go through long-press, then the multiselect menu, and then choose the action.

Instead we should do it obviously, like in the mobile web interface:
![capture du 2017-01-24 12-06-42](https://cloud.githubusercontent.com/assets/925062/22244940/d4a10924-e22d-11e6-958d-4be6e8d91043.png)
- A 3-dot-menu for every folder/file. Very obviously clickable
- The share icon should also be clickable, because people expect that. Playing around with making it appear un-clickable is just beating around the problem. ;) If there’s too little space then we could even only show the share icon when a file _has_ been shared (like we do now) but when tapped it should be interactive and open the share options.
- If there’s enough space, even have a column or some more space for the favorite icon on the left.

Already talked about this with @mario, what do you think @tobiasKaminsky @eppfel @AndyScherzinger?

**Comment by AndyScherzinger** [comment]
Sounds good to me and is doable.
Only thing I am not sure if it is better to 
1. always show a share icon (in grey) and paint it black if the file is actually shared
2. only add the share icon if the file is actually shared, else don't

**Comment by jancborchardt** [comment]
@AndyScherzinger cool! :) As said I’m also not entirely sure, but then maybe let’s go with 

> always show a share icon (in grey) and paint it black if the file is actually shared

This is consistent with the web interface, makes it easy to share, and doesn’t require us to change the menu.

> if we put the "share action" in there then I guess it should always be shown with the share action wired to it :)

Yep, that’s the idea! :)

**Comment by mario** [comment]
Glad we all agree :P

**Comment by tobiasKaminsky** [comment]
Just a "little" concern about space: have you checked it on low end devices, which have a low-res display? Your idea might lead to a nearly unreadable filename...
This is something we should check with a "mockup" prior developing it.

**Comment by jancborchardt** [comment]
Yes, I mean you can quite easily check with the web interface and checking it in responsive design view of the browser or making it very narrow. The mobile web interface is the living mockup :)

If there are space constraints then I’d say we can do without the dedicated favorite and share action, but we definitely need the 3-dot-menu. In there we can then have the fav/share also. But it’s not ideal.

And I guess somehow we can check how big the screen is, and show the actions accordingly even?

**Comment by AndyScherzinger** [comment]
As for the three-dot menu, should we then have the (non-Android-like) schaschlik 3-dot menu icon or the typical Dönerspieß 3-dot icon?
Other than that one thing that is different for the Android UI: We do have the multi selection functionality, which gives you the toolbar menu (which also dynamically changes its content for single/multi file selection) which we should keep imho, since that is how selections are done standard Android way even though it means a single selection and just hitting the list item's menu entry will give you the same functions. Other than that the actual selection functionality is needed for the grid view.

**Comment by eppfel** [comment]
> If there are space constraints then I’d say we can do without the dedicated favorite and share action, but we definitely need the 3-dot-menu.

Came here to say this. I would actually use fav on landscape width only. Long Filenames are the most important. Just look at example you posted 😉 

@AndyScherzinger Ein Android Dönerspieß Bitte! 😂 
I feel, people won't even notice and it works better when there is less space IMO

**Comment by tobiasKaminsky** [comment]
schaschlick 3-dot, dönerspieß? What are you talking about? Oo

**Comment by AndyScherzinger** [comment]
schaschlick = 3 dot horizontal (see web interface)
dönerspieß = 3 dot vertical (see Android toolbar overflow menu icon)

**Comment by AndyScherzinger** [comment]
While initially my mistake was to call is doener since that one is actually a different icon symbolizing filtering ;D

**Comment by jancborchardt** [comment]
Yup, let's go for the strawberries on a stick covered in chocolate … I mean Dönerspieß!

And sure, the multiselect menu should stay, even also for single files (in case you deselect everything else).

We simply also need the probably most used way of just doing something with a single file. ;)

**Comment by mario** [comment]
@jancborchardt @AndyScherzinger @tobiasKaminsky do we have the three dot icon in the correct sizes?

Also, since this menu could grow and real estate is limited, I'd still vote for opening a bottom sheet style menu for this - but @jancborchardt is the boss, so please think about it once again :P

**Comment by AndyScherzinger** [comment]
@mario I can add the three dot icon in the right sizes and coloring, just need to know the branch :)

**Comment by mario** [comment]
@AndyScherzinger mario AT nextcloud DOT com is the branch :P

**Comment by AndyScherzinger** [comment]
@mario you got 📬

**Comment by jancborchardt** [comment]
> Also, since this menu could grow and real estate is limited

It should have pretty much exactly the items we have in the web interface. Which are 5, not that much. :) We need to consolidate.

**Comment by mario** [comment]
@jancborchardt on a small phone, sure - that's too much. Also, if you open menu at one of the items near the end of the list - issue :D

**Comment by AndyScherzinger** [comment]
As long as we use Android's standard menu mechanisms like the pop up menu, there isn't an issue I think :)

**Comment by tobiasKaminsky** [comment]
Is there somehow a screenshot which shows this kind of popup?

**Comment by AndyScherzinger** [comment]
I can post one tomorrow or next week, or if you have seriesguide installed, he implemented it. The look and feel is basically the one from the toolbar overflow menu.

**Comment by tobiasKaminsky** [comment]
Thanks for the tip, @AndyScherzinger 

Here is a screenshot for "Lucifer" pressed
![screenshot_20170131-215950](https://cloud.githubusercontent.com/assets/5836855/22484235/b6da01ce-e800-11e6-9fd0-8e267a80b68b.png)

And here for "Sherlock"
![screenshot_20170131-215956](https://cloud.githubusercontent.com/assets/5836855/22484249/d3353636-e800-11e6-8676-a987228cc54d.png)

Both looks really nice and, I guess, it will also work fine on low-res displays.

**Comment by jancborchardt** [comment]
Any update or any help needed here? :) From a user perspective this is _the_ biggest issue when using the app day-to-day right now.

**Comment by mario** [comment]
None, but due to other constraints, this is not in the 2.1 plan (aka, next two and a half months). So maybe 2.2? cc @AndyScherzinger @tobiasKaminsky

**Comment by mario** [comment]
(Ergh I can see milestone is set to 2.1.0, but I think our 3 months plan doesn't include it - @AndyScherzinger and @tobiasKaminsky will confirm - I think we wanted to put this in once RecyclerView is here?)

**Comment by AndyScherzinger** [comment]
Exactly, so not planned for 2.1 since like Mario said we want to have RecyclerView first. But let's see, maybe someone else wants to pick it up. Imho a starter issue since everything is in place except the menu...

**Comment by tobiasKaminsky** [comment]
If someone else wants to do it, we can include it before Recycler View. Otherwise it will be done after implementation of Recycler View, so I removed the milestone for now.

**Comment by AndyScherzinger** [comment]
👍 since it shouldn't be to much of a hassle to implement either way I tagged it a starter issue.

**Comment by jancborchardt** [comment]
Could this issue be part of the milestone-after-next then though? Would be cool if this doesn’t fall under the rug, especially since it’s starter-issue-material and should hence be easy to implement. ;)

**Comment by AndyScherzinger** [comment]
I'll see if I can find the time plus hoping any other contributor jumps in :)

**Comment by AndyScherzinger** [comment]
merged! :)
