### ISSUE TITLE
Performance issues on playing videos in app

### ISSUE THREAD

**Issue by pilsnerbeer** [nextcloud/android#5800]
### Steps to reproduce
1. Play video from the app

### Expected & actual behaviour
Loading time is expected to be comparable or faster than if user played the same video using their browser app. In reality, the loading time (for a particular mp4 video that I had in my cloud) was 7-11 seconds (a very long time until the video even started playing) but if I played the same video using my web browser, it started playing instantly.

Picture- loading the video. Usually at least 5 seconds, sometimes the file never even loads. The videos I used for testing are low to mid bitrate and 1080p.
![Screenshot_20200403-114502](https://user-images.githubusercontent.com/36133540/78347443-cba49700-75a0-11ea-947d-3aec90f2c658.jpg)

### Environment data
Android version: 9

Device model:  Oneplus 5T

Nextcloud app version: 3.11.0

Nextcloud server version: 17

**Comment by tobiasKaminsky** [comment]
@rullzer do you have any idea what direct editing could to take so long?

**Comment by jakobroehrl** [comment]
Same problem here, tested with 3 different smartphones and NC19
 - It takes 8-12 secs to preload the video no matter how long the video is
 - Video stops while playing to preload again

In the browser it's working fine.
Can post a video of the problem it that helps

**Comment by tobiasKaminsky** [comment]
@rullzer can you imagine how/why the direct endpoint is so slow?

**Comment by szaimen** [comment]
Ping

**Comment by edwinhuish** [comment]
same issue here.

**Comment by jakobroehrl** [comment]
Ping

**Comment by jakobroehrl** [comment]
Tested this weekend with other smartphones. On P30 it works well, for example. There is only a 2-4 sec delay. 
As a nice workaround I use "stream with -> VLC", with that the video starts almost immediately.

**Comment by szaimen** [comment]
ping

**Comment by qosmio** [comment]
Same exact issue, NC 19.0.1. Videos just keep trying to buffer over and over. Both the browser (safari for native mov playback) and iOS app. I've been on the latest betas of the app too.

**Comment by military1** [comment]
NC 19.0.2, Nextcloud app version: 3.11.0, Android 10. Same issue.

**Comment by Wytoo** [comment]
Hi there, I'm having the same issue. 83mb video is taking about a minute, even if it's loading.
I'm using a DS918+. Processor isn't even at 30% with lots of other stuff running.

EndDevice: Android 10. Galaxy S10 3.13.0, or iPhone X newest iOS and Nextcloud version (familywide problem)
Server: NC18.0.1 

I'd love to attach some logs, but don't know how or which.

**Comment by tobiasKaminsky** [comment]
It seems that the buffer size of MediaPlayer is fixed.
There is a way to show it, but the percent is a bit strange, so I am unsure if we should show it:
MediaPlayer:OnBufferingUpdateListener:
> /**
         * Called to update status in buffering a media stream received through
         * progressive HTTP download. The received buffering percentage
         * indicates how much of the content has been buffered or played.
         * For example a buffering update of 80 percent when half the content
         * has already been played indicates that the next 30 percent of the
         * content to play has been buffered.
         *
         * @param mp      the MediaPlayer the update pertains to
         * @param percent the percentage (0-100) of the content
         *                that has been buffered or played thus far
         */

After all we already show a loading spinner…

**Comment by AlekseiMarinichenko** [comment]
Video is loading forever on Android inside the app.

"stream with -> VLC" does not work too. 

Is there any workaround?

**Comment by pilsnerbeer** [comment]
> Is there any workaround?

I switched to web version after I noticed pretty much everything is way faster compared to the app (incl. loading times for folders etc). Plus - you can actually seek video/audio files there unlike the app player which has been broken for a couple of months now;)

btw - streaming via VLC doesn't work for me either but google photos works ok (web player still much faster though.)

**Comment by TechnicallyComputers** [comment]
This is a issue for me too.  It seems to not be codec related, but purely performance based from what I can tell.

I have a large collection of family pictures and videos to share with family, and I've found that, despite being all MP4 H264, most don't load and buffer almost indefinitely, from the android app or the web browser.

If the framerate is 60fps instead of 30fps, the video will *not* buffer properly.
If I set the video/camera it to 1920x1080 resolution, 30fps, it will load, but buffering takes a noticeable amount of time at the start.
If I set it to 1280x720 and 30fps, it buffers and loads effectively.

**Comment by JonathanBrose** [comment]
Same issue for me... 
System: 32gb ram, ryzen 9 3900x, gbit lan, no bottleneck here.
I am running NC19, and trying to stream videos from the web-ui and android app. 
All Tests are in LAN. 
On Chrome i can watch FULLHD 30fps, Firefox even that buffers forever. Android app buffers for ages.
i have a lot of 4k30 and 4k60 vids with 100mbits bitrate or even more. 60fps doesnt work at all, just shows black and plays the sound. 4k30 works, but buffers lik 30secs for 1-2secs of playback. Downloading the file is nearly instantly... 
If i click stream with vlc on android i can play any of these videos no problem without delay

**Comment by Fuzl** [comment]
Same issue here, for large videos : one of 600Mo and the other of 2.5Go
Tested on web Firefox.

**Comment by cieska** [comment]
ping

**Comment by caalca** [comment]
Same issue

**Comment by hardeek** [comment]
Stream with "Photos" (Google Photos) is working fine for me!

**Comment by cieska** [comment]
ping

**Comment by Wytoo** [comment]
yep, still the same issue

**Comment by laguerreche** [comment]
I made a video with my phone of "Big Buck Bunny" being played on my PC to get a video file that isn't played smoothly (the original file was played correctly!). I uploaded my video at https://demo1.nextcloud.com, user "cH2awx9JwD6z9cnj", file name "VID_20201221_202750.mp4". I can re-upload it somewhere else...

In firefox on a PC with Linux, seeking seems to be broken so the video may become stuck after a few frames have been played and it may continue once the file has been downloaded.

If someone wants to reproduce the video:
- I downloaded Big Buck Bunny from there: https://cloud.blender.org/films/big-buck-bunny/gallery?asset=263 (BTW it's played correctly by Nextcloud),
- I used my Android 9 phone in 1080p@60Hz (but other settings lead to the same result) to capture a video (if too short the file will be small and no problem may appear).

**Comment by jakobroehrl** [comment]
>     * I downloaded Big Buck Bunny from there: https://cloud.blender.org/films/big-buck-bunny/gallery?asset=263 (BTW it's played correctly by Nextcloud),


I can stream this video without any problems on my nextcloud and on my android phone.

**Comment by laguerreche** [comment]
> > ```
> > * I downloaded Big Buck Bunny from there: https://cloud.blender.org/films/big-buck-bunny/gallery?asset=263 (BTW it's played correctly by Nextcloud),
> > ```
> 
> I can stream this video without any problems on my nextcloud and on my android phone.

And I can also... But I then filmed my PC screen playing Big Buck Bunny to get a new video file and that file cannot be played correctly.

**Comment by TechnicallyComputers** [comment]
The video posted is 720p, of course it works, the issues are with 1080p or higher content.

**Comment by disgustipated** [comment]
I'm seeing this on latest snap image in ubuntu, local works ok but someone trying to stream a share of mine takes a while. I have a 300mb upload speed and the video seems to stop after a couple of frames. im technically inclined and i can gather details, just let me know whats needed.

**Comment by tobiasKaminsky** [comment]
There is an experimental switch to another video player in https://github.com/nextcloud/android/pull/8132#issuecomment-792722526

This apk can be installed in parallel. 
It would be great if you can give this a test, if it helps in your scenario.

**Comment by cieska** [comment]
> There is an experimental switch to another video player in [#8132 (comment)](https://github.com/nextcloud/android/pull/8132#issuecomment-792722526)
> 
> This apk can be installed in parallel.
> It would be great if you can give this a test, if it helps in your scenario.

Not counting hundred of other bugs with this player/app it plays very well. Instantaneous play, quick play after sliding to any play on time bar. Looks good regarding playback. 
But playback doesn't stop if you exit app without the stoping video, app must be uninstalled to stop the play in background. Same with starting other video if other one not stoped then two plays inbacgroud. No full screen button. And probably something else.

**Comment by disgustipated** [comment]
As cieska says, seems a little buggy but im guessing its just to get it in to test. I didnt have to reboot, just force killed the qa app to get video to stop playing in background.
Seems to work a lot better, testing on a 1gb video and was able to jump around with relatively low delay when playing back after jumping around to different locations and rewinding and ffwd.  I assume this would go into place for the web portion as well?

**Comment by tobiasKaminsky** [comment]
I should have been more clear, this is just about streaming/playback issues.
All other is not expected to work better/ at all.

But it seems as it is the way to go 💪

Thanks for testing.

**Comment by military1** [comment]
@tobiasKaminsky , In which version app will there be a solution to this problem with streaming playback? I have to use two applications, Nextcloud and Owncloud (free, which has not been updated for a long time, but there video streaming works fine).

**Comment by nikbpetrov** [comment]
Apologies for reviving an old issue but I am still getting the exact same symptoms as described above. Video playback is fine in Chrom on Web on both Windows and Android but does NOT work on:
- Firefox on Windows/Android
- NC web app
- Android VLC player/Android Video player when opened with "Stream with..." option

Nextcloud Android app v3.29.2, Nextcloud 25.0.5
Samsung Galaxy S22+

**Comment by kbftech** [comment]
Hi,

Same issue here. Nextcloud is installed on a Debian VM (Proxmox - 4 cores [AMD Ryzen 9 5900X], 16gb RAM, 10gbps virtio).
Iperf reports: 
`[ ID] Interval       Transfer     Bandwidth
[  1] 0.0000-10.0229 sec  1.08 GBytes   927 Mbits/sec`
Meanwhile loading a video takes ages but loading photos is pretty much instant.
Tested on:
Chrome (Brave): Terrible (loads about 1 second, then gets stuck, then starts again, and so on - Pauses of seconds in between stops)
Firefox: Worst (Plays for a second and then just buffers for minutes before doing anything else)

**Comment by Zusel** [comment]
Same error here. I searched for a solution but this is everything i found...

**Comment by Oriann** [comment]
Still same issue till now. Not fixed

**Comment by TechnicallyComputers** [comment]
Filebrowser is a super lightweight file management application with way less fluff than Nextcloud or Owncloud, and it has no issues with 1080p high quality video playback compared to nextcloud, none of the extra unneeded features of owncloud.  Good alternative.
