### ISSUE TITLE
Changing local file through SAF in quick succession leads to filecorruption

### ISSUE THREAD

**Issue by newhinton** [nextcloud/android#5806]
### Steps to reproduce
1. Create&upload onelist file
2. Import via app, so that it accesses the file through the storage access framework
3. Check multiple items in quick succession

OR:

Create an app that changes a raw file a few times a second

See https://github.com/lolo-io/OneList/issues/11

### Expected behaviour
- The file should upload the newer file, and not corrupting it while beeing uploaded

### Actual behaviour
- The ascii content corrupts. 

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: Android 10

Device model: S9

Stock or customized system: Selfbuild LineageOS

Nextcloud app version: 3.11.0

Nextcloud server version: 18.0.3

**Comment by newhinton** [comment]
I forgot to mention: 

The affected file is a plaintext json file, and the app writes it with a "text/x-json" mimetype. 

It is corrupted only with a single closing bracket '}' duplicated at the end.

Original:
> {"deletedItems":[],"items":[{"comment":"","commentDisplayed":false,"deleted":-1,"done":false,"stableId":1586115167129,"title":"test"}],"stableId":1586115160177,"title":"test"}

Uploaded:
> {"deletedItems":[],"items":[{"comment":"","commentDisplayed":false,"deleted":-1,"done":true,"stableId":1586115167129,"title":"test"}],"stableId":1586115160177,"title":"test"}}

**Comment by tobiasKaminsky** [comment]
Can you test this with another app, e.g. a simple text app?
I currently cannot imagine that only "}" in the end is missing…

**Comment by newhinton** [comment]
I have tried it with QuickEdit from gplay (i found out most simple editor apps on fdroid do not support saf yet) and it messes with the content too. However, it is quiet hard to test it properly since you need to be quick to make the changes.

**Comment by tobiasKaminsky** [comment]
So, with QuickEdit, you did something like
- open quickedit
- open a text file via SAF on Nextcloud
- change text
- save
- change text
- save
- and sometimes it is corrupt?

**Comment by newhinton** [comment]
Yes. It is easier with the onelist-app since it edits a textfile on a click, but that is generally how it happens

**Comment by tobiasKaminsky** [comment]
@nextcloud/server-triage if android uploads very frequently the same file, this is exclusivley, or?
So it cannot be servers problem if a file is corrupted?

**Comment by MorrisJobke** [comment]
> @nextcloud/server-triage if android uploads very frequently the same file, this is exclusivley, or?
> So it cannot be servers problem if a file is corrupted?

What do you mean with "exclusively"? A file upload itself is atomic, but not multiple uploads.

**Comment by tobiasKaminsky** [comment]
exclusively == atomic.
So, if I upload 10x the same file, there should be no race problem / corruption, right?

**Comment by MorrisJobke** [comment]
> So, if I upload 10x the same file, there should be no race problem / corruption, right?

correct

**Comment by tobiasKaminsky** [comment]
@newhinton can you verify if the local file is valid, e.g. there is no corruption?

**Comment by newhinton** [comment]
Do you mean the file stored in Android/media/com.nextcloud.client/nextcloud/user/... ?

**Comment by tobiasKaminsky** [comment]
I tried it with 1list, but I cannot access any text file stored on NC.
Even when I first create a local list, share it to NC and then try to open this list via SAF, I cannot see it.
Can you describe me how I can do this?

**Comment by newhinton** [comment]
Sure! 
I opened the app, and then started creating a new list via the plus. There i expanded the more options dropdown, and there i selected 'App private storage' (this may actually be mislabeled)

then a new popup opens where you can select a folder, which should open the folderpicker, and there you can select a target like nextcloud

**Comment by tobiasKaminsky** [comment]
I tried this and after that added some infos to the list.
Do I then have to save this somehow? 
Nothing is transferred to NC and in settings I still see "app private storage".

**Comment by newhinton** [comment]
@tobiasKaminsky Ah yes, i have to apologise, i forgot that this was a little bit buggy. 

See this comment:
https://github.com/lolo-io/OneList/issues/11#issuecomment-609035349

Basically you need to export the file to local, then upload that file to nextcloud, remove it from iolist, and then create a new list but instead of creating one, you import the one from nextcloud.
(Interesting sidenote, the files are called *.1list on the local system, but after sharing it with nextcloud they get an additional extension, uploaded they are called *.1list.bin (the stock-filemanager recognizes the file as binary data, too, but shows no .bin extension))


I have to admit, there may be something else going on, but i could not figure out what may be wrong with the SAF-Implementation in onelist. If you have advice on some good resources to the SAF, i will investigate it further.

**Comment by newhinton** [comment]
since this is a rather strange bug, would it help you if i write a simple app that basically tests this?

**Comment by tobiasKaminsky** [comment]
> since this is a rather strange bug, would it help you if i write a simple app that basically tests this?

Yes, this would be ideal!
