### ISSUE TITLE
Conf of auto upload leads to crash

### ISSUE THREAD

**Issue by pm974** [nextcloud/android#5809]
One plus 6 T, android 10 (oxygen os 10.3.2
Nextcloud app crash when configuring automatic upload. 
Settings get registered but app needs force shutdown. 
Lots of other problems : long delais when changing other settings in the app.

**Comment by tobiasKaminsky** [comment]
Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat
