### ISSUE TITLE
... 

### ISSUE THREAD

**Issue by ghost** [nextcloud/android#5814]

**Comment by szaimen** [comment]
Actually I would disagree that it isn't obvious that Nextcloud downloads/chaches those files to play it with another apps. I guess to hand them over via the storage api to other apps it is necessary to download the file first. 

But having an option to automatically delete the files locally afterwards if accessed over this api would definitely be useful.

**Comment by DevinDuricka** [comment]
What if you could select a folder and mark it as exempt from caching?
