### ISSUE TITLE
Can’t upload files bigger than 1MB with android app

### ISSUE THREAD

**Issue by m0rph2k** [nextcloud/android#5818]
Hello

Is it normal that i can't Upload any file bigger than 1MB ?

`[webdav] Fatal: OCP\Files\NotFoundException: /XYZ/files/072774e2872b80f6de18c073d1c5ddf6/0000000000000000-0000000003175364 at <<closure>>

 0. /var/www/html/nextcloud/lib/private/Files/Node/Folder.php line 137
    OC\Files\Node\Root->get("/XYZ/files/07 ... 4")
 1. /var/www/html/nextcloud/apps/dav/lib/Connector/Sabre/SharesPlugin.php line 157
    OC\Files\Node\Folder->get("/072774e2872b80 ... 4")
 2. /var/www/html/nextcloud/apps/dav/lib/Connector/Sabre/SharesPlugin.php line 210
    OCA\DAV\Connector\Sabre\SharesPlugin->getShares(OCA\DAV\Connector\Sabre\File {})
 3. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/PropFind.php line 98
    OCA\DAV\Connector\Sabre\SharesPlugin->OCA\DAV\Connector\Sabre\{closure}("*** sensitive parameters replaced ***")
 4. /var/www/html/nextcloud/apps/dav/lib/Connector/Sabre/SharesPlugin.php line 213
    Sabre\DAV\PropFind->handle("{http://nextcloud.org/ns}sharees", Closure {})
 5. <<closure>>
    OCA\DAV\Connector\Sabre\SharesPlugin->handleGetProperties(Sabre\DAV\PropFind {}, OCA\DAV\Connector\Sabre\File {})
 6. /var/www/html/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
    call_user_func_array([OCA\DAV\Connect ... "], [Sabre\DAV\PropF ... }])
 7. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1059
    Sabre\Event\EventEmitter->emit("propFind", [Sabre\DAV\PropF ... }])
 8. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 981
    Sabre\DAV\Server->getPropertiesByNode(Sabre\DAV\PropFind {}, OCA\DAV\Connector\Sabre\File {})
 9. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1666
    Sabre\DAV\Server->getPropertiesIteratorForPath("uploads/XYZ/0 ... 6", ["{DAV:}resource ... "], 1)
10. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 355
    Sabre\DAV\Server->generateMultiStatus(Generator {}, false)
11. <<closure>>
    Sabre\DAV\CorePlugin->httpPropFind(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
12. /var/www/html/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
    call_user_func_array([Sabre\DAV\CorePlugin {},"httpPropFind"], [Sabre\HTTP\Requ ... }])
13. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 479
    Sabre\Event\EventEmitter->emit("method:PROPFIND", [Sabre\HTTP\Requ ... }])
14. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 254
    Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
15. /var/www/html/nextcloud/apps/dav/lib/Server.php line 319
    Sabre\DAV\Server->exec()
16. /var/www/html/nextcloud/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
17. /var/www/html/nextcloud/remote.php line 165
    require_once("/var/www/html/n ... p")

PROPFIND //remote.php/dav/uploads/XYZ/072774e2872b80f6de18c073d1c5ddf6`

**Comment by tobiasKaminsky** [comment]
This should be fixed with next version.
Can you try out our dev version (you can install it in parallel): 
https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#developement-release

**Comment by tobiasKaminsky** [comment]
Ref: https://github.com/nextcloud/android-library/pull/418

**Comment by m0rph2k** [comment]
mhh, i try to install the nextcloud-dev-20200405.apk from https://download.nextcloud.com/android/dev/

but endless installation loop

Android 6.0.1

**Comment by m0rph2k** [comment]
Hi, thx works with nextcloud-dev-20200405.apk
