### ISSUE TITLE
Manual Auto upload button (e.g. for forcing on mobile even when set to wifi only)

### ISSUE THREAD

**Issue by pahy** [nextcloud/android#582]
Featurerequest:

Menuentry or button to force autoupload manually. So everything starts even when wifi only is selected.

By the way: Good work!

**Comment by AndyScherzinger** [comment]
@jancborchardt @eppfel any comments on this UX wise? I get the motivation behind it, but it also seems unintuitive to me and adding complexity to the app/code-base.

cc @mario @tobiasKaminsky for dev-side-of-life

**Comment by eppfel** [comment]
I totally understand the idea, had it with other apps before. But you UX is problem and I would give this minimal priority. It is possible to deactivate wifi-only temporarily anyway, right?

**Comment by mario** [comment]
@eppfel yes, but I don't think existing jobs queued would change, at least not automatically. Dunno.

**Comment by eppfel** [comment]
But we could implement this. And I would rather go for that, than an extra button/option/etc.

**Comment by mario** [comment]
So what you're asking for is:

Be on a mobile network. Have wifi-only set. Take some pictures. Queue jobs. Disable wifi-only (manually). Run all jobs. Turn on wifi-only (manually).

Right?

**Comment by eppfel** [comment]
I think that is what user would might do, but maybe I'm wrong here. Maybe a force upload per item could also be an option, but I can't imagine it, yet.

**Comment by tobiasKaminsky** [comment]
As this will be data consumptive I suggest to put this only on a per item base, via long click?
But I do not know how to show/present this to the user.

**Comment by joshtrichards** [comment]
Let's consolidate this into #7019, which is where most of the upvotes are already and there's no need to have duplicates.
