### ISSUE TITLE
Problem with nextcloud client

### ISSUE THREAD

**Issue by Phiphi-P** [nextcloud/android#5820]
Hi, the nextcloud doesn't want to connect to my personal cloud. they say "cannot find the host"
I can connect to with a web page.
the certifact is all right with let's encrypt.
The nextcloud app is install on yuhonost on raspberry pi

thanks for your return
Philippe (FR)

**Comment by tobiasKaminsky** [comment]
Can you create us a test account, test if the problem occurs also there and if so send the credentials to tobias at nextcloud dot com with a reference to this issue?

**Comment by Phiphi-P** [comment]
Ok i try it in few hours.
The first time i install nextcloud alone not under yunohost and it works. But the problem appear with yunohost...
thanks

**Comment by Phiphi-P** [comment]
Hi Tobias,
I did not understand when you want me to create a test account, can you tell me?
The translation from English to French is sometimes tricky ;-).
One clarification is that when I put the ip address ( https://91.46.**.***/nextcloud/ )of my server it does not work either.
It gets stuck on "host search" and that's it.
thanks for your help

**Comment by tobiasKaminsky** [comment]
Yes, please create a test account, and send username/password and server address to tobias at nextcloud dot com with a reference to this issue

**Comment by Phiphi-P** [comment]
Hi Tobias, i send you a email.
Thanks

**Comment by Phiphi-P** [comment]
Hi Tobias, i stop my server with yunohost for the moment. i try to install with Docker.
Thanks

**Comment by tobiasKaminsky** [comment]
Ok,
please re-open once it happens again.
