### ISSUE TITLE
Upload of WhatsApp Backup failed

### ISSUE THREAD

**Issue by alex9434** [nextcloud/android#5827]
### Steps to reproduce
1. Create WhatsApp Chat Backup locally 
2. Activate local directory /storage/emulated/0/WhatsApp for auto-upload in Nextcloud App

### Expected behaviour
- Backup files automatically uploaded to Nextcloud server overwriting old (and outdated) backups

### Actual behaviour
- Upload fails with sync conflict that needs to be resolved manually for each individual file.

### Can you reproduce this problem on https://try.nextcloud.com?
- Yes

### Environment data
Android version:
10
Device model: 
Samsung s9 Plus
Stock or customized system:
Stock
Nextcloud app version:
3.11.0
Nextcloud server version:
18.0.0.3
#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
#5810 should fix this introducing behaviors for such a scenario (overwrite, rename, etc)

**Comment by alex9434** [comment]
Yes, you are right. Good point. Thank you.
