### ISSUE TITLE
No push notifications : GmsHttpFormClient Error=FIS_AUTH_ERROR 

### ISSUE THREAD

**Issue by flyinva** [nextcloud/android#5837]
### Steps to reproduce
1. Install Nextcloud app from Google Play
2. Launch app

### Expected behaviour

Push notifications should be enabled. The app should be listed in in microg Google Cloud Messagging registered app. 

### Actual behaviour

Other apps are registered in Google Cloud Messagging from microg (riot.im, jitsi meet) but not Nextcloud or Talk. Push notifications are disabled.

### Environment data
Android version: 9 

Device model: Wileyfox Swift

Stock or customized system: microg lineageOS

Nextcloud app version: 3.11.0

Nextcloud server version: 18.0.3

#### android logs (logcat)
```
      GmsHttpFormClient  D  -- Request --
                         D  X-GOOG.USER_AID=xxxxxxxxx&device=xxxxxxx&app=com.nextcloud.client&appid=fskKRFuaRF2AGvIWqQoD6b&cert=74aa1702e714941be481e1f7ce4a8f779c19dce>
                            app_ver=30110090&app_ver_name=3.11.0&gmp_app_id=1%xxxxx%3Aandroid%xxxxxx&gmsv=xxxx&scope=*&osv=xx&sender=xxxx&subtype=xxx>
    FileDisplayActivity  V  onPause() start
                         D  onPause() ending
                         V  onPause() end
             Adreno-EGL  I  <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build: Nondeterministic_AU_msm8916_64_LA.BR.1.2.9_RB1__release_AU (I38fdb1353f)
                         I  OpenGL ES Shader Compiler Version: XE031.09.00.03
                         I  Build Date: 10/24/16 Mon
                         I  Local Branch: mybranch22985090
                         I  Remote Branch: quic/LA.BR.1.2.9_rb1.8
                         I  Local Patches: NONE
                         I  Reconstruct Branch: NOTHING
            ConfigStore  I  android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
                         I  android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
         OpenGLRenderer  I  Initialized EGL, version 1.4
                         D  Swap behavior 1
             Adreno-EGL  W  <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
                         W  <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
            vndksupport  D  Loading /vendor/lib64/hw/gralloc.msm8916.so from current namespace instead of sphal namespace.
      GmsHttpFormClient  D  -- Response --
                         D  Error=FIS_AUTH_ERROR

```

**Comment by tobiasKaminsky** [comment]
This is very strange, I use microG with Android 10 on OP6T and it working really great here.
As we are following the official push specs and it is working on official gplay devices, I fear I cannot do anything here.
Maybe you can ask the microG devs?

**Comment by nels83** [comment]
I think it's the same problem as https://github.com/nextcloud/talk-android/issues/769
Fix is in this commit https://github.com/nextcloud/talk-android/commit/6b1642931164531d1b2a645ac7f7310853d2cd79

As a workaround, you can try to install 3.10.1 gplay release from https://github.com/nextcloud/android/releases/tag/stable-3.10.1
Configure the application, it should register with GCM.
You can then upgrade to the latest version.

**Comment by flyinva** [comment]
@nels83 : OK for nextcloud. Can I do the same for Talk ? I didn't find any gplay release for Talk.

**Comment by nels83** [comment]
You can do the same for Talk (in fact I only did this for Talk and assumed it was the same for Nextcloud ;-)). All releases seem to include gplay code.
Just install 8.0.3 release from https://github.com/nextcloud/talk-android/releases/tag/v8.0.3
