### ISSUE TITLE
NextCloud

### ISSUE THREAD

**Issue by sbtabor** [nextcloud/android#5846]
### Steps to reproduce
1. open app on Galaxy Note 10
2. auto sync photos
3. app does not respond and freezes

### Expected behaviour
- Tell us what should happen
The photos should sync to my server
### Actual behaviour
- Tell us what happens
Error Is not responding
### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: Galaxy Note 10 Android

Stock or customized system: Stock

Nextcloud app version: 3.11.0

Nextcloud server version: 15.0.14

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
This will be fixed via https://github.com/nextcloud/android/pull/5810
