### ISSUE TITLE
Text-Shadow in sidebar looks blurry with a light Theme-color

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/android#5847]
I am currently implementing theming in the Deck app and stumbled over the issue that if you have selected a light Nextcloud Theme-Color like yellow, the name and url will look very blurry. I wanted to know how this has been solved in this app and it looks like it's the same at all:

![IMG_20200411_091302](https://user-images.githubusercontent.com/4741199/79037820-b1883b80-7bd4-11ea-814b-e8717ff1b7e3.jpg)

Not sure if this a bug or by intention. Potential fixes:

- Remove shadow completely
- Use `#fff` or `#000` based on whether the `text-color` property is further away from white or black

**Comment by stefan-niedermann** [comment]
FYI: I solved it in the Deck app with using `#ffffff` / `#000000` shadow color depending on the `textColor`:

```java
final boolean isDarkTextColor = ColorUtil.isColorDark(textColor);
if (isDarkTextColor) {
    headerBinding.drawerAppTitle.setShadowLayer(2, 0.5f, 0, Color.WHITE);
} else {
    headerBinding.drawerAppTitle.setShadowLayer(2, 0.5f, 0, Color.BLACK);
}
```

where `ColorUtil.isColorDark()` is

```java
public static boolean isColorDark(@ColorInt int color) {
    final int[] rgb = {Color.red(color), Color.green(color), Color.blue(color)};

    final int brightness = (int) Math.sqrt(rgb[0] * rgb[0] * .241 + rgb[1]
            * rgb[1] * .691 + rgb[2] * rgb[2] * .068);

    return brightness < 200;
}
```

Feel free to adapt if you want or to close if this is nothing you want to address :)

**Comment by tobiasKaminsky** [comment]
@stefan-niedermann thanks for pointing this out and giving us a solution :-)

Can you post two screenshots with your new backgronud?

@jancborchardt what do you think?

**Comment by stefan-niedermann** [comment]
Light main color → dark text color → white *shadow*

![grafik](https://user-images.githubusercontent.com/4741199/79194035-1be6e900-7e2c-11ea-8c04-f44f3714fb7f.png)

Dark main color → light text color → black *shadow*

![grafik](https://user-images.githubusercontent.com/4741199/79194043-20130680-7e2c-11ea-8e77-449cdebc5a23.png)

Important is, that the shadow color does *not* directly depend on the *main color* but on the *text color* (which itself depends on the mail color of course).

**Comment by stefan-niedermann** [comment]
PS.: instead of the `isColorDark(...)` magic one could *assume* that the Nextcloud capabilities endpoint always returns `#ffffff` or `#000000` as `textColor`-property (at least i didn't ever see another value for the `textColor`). But i didn't want to rely on this assumption, therefore checking whether the font-size is dark or light manually.

**Comment by tobiasKaminsky** [comment]
We do not have this any longer.

**Comment by stefan-niedermann** [comment]
Me neither :laughing:
