### ISSUE TITLE
showing incorrect file

### ISSUE THREAD

**Issue by acloudadmin** [nextcloud/android#5850]
Hi there,

App working overall great for me. Still waiting for a version inwhich I can either self-set the size of the cache or allow thumbnails to persist indefinitely, but otherwise very satisfied. Thank you!

But noticed this morning that the app has become confused about a particular file.

App shows:

![via android app](https://user-images.githubusercontent.com/55052096/79042559-ca89f000-7bc6-11ea-9e2d-a410104ae660.jpg)

But it should be showing:

![via browser](https://user-images.githubusercontent.com/55052096/79042565-d5448500-7bc6-11ea-991e-344a1af0f02c.jpg)
![source](https://user-images.githubusercontent.com/55052096/79042567-d83f7580-7bc6-11ea-9885-a884554bdd0f.jpg)

_(on that last screenshot, realized I highlighted the wrong file. The correct file is directly above it)_ 

Any thoughts about how I can fix this, and any other files about which it may have become confused?

Thanks! - Andy

**Comment by tobiasKaminsky** [comment]
It seems that only the thumbnail is wrong, or?
If you click on it, to get a full screen image of it, dos it then shows the image correct?
What is shown if you download the file?

**Comment by acloudadmin** [comment]
It wasn't just the thumbnail. Showed the wrong file in Nextcloud and downloaded a pic of my dog under the "C19-1 ..." filename.

But good news: the app seems to have figured it out and now displays the correct thumbnail and downloads the correct file. No server or phone reboot ... it just now displays correctly. 

Thanks!
