### ISSUE TITLE
Crash when trying to upload many files

### ISSUE THREAD

**Issue by rufftruffles** [nextcloud/android#5861]
### Expected behaviour
The application should upload all the selected files.

### Actual behaviour
I navigate to the target folder on the server, then press the upload buttons. Then,
I select a folder to upload (my camera's images, actually). I choose "Select all" then I press "Upload". Then, the application crashes.

### Steps to reproduce
1. Have a folder with many files (in my case, ~8000?)
2. Select them for upload
3. Press "Upload"

### Environment data
Android version: 10

Device model: Samsung Galaxy S10+

Stock or customized system: Stock

Nextcloud app version: 3.11.0

Nextcloud server version: 18.0.3

#### Web server error log
```
no errors
```

#### Nextcloud log (data/nextcloud.log)
```
No errors received when the crash happened
```

**Comment by ezaquarii** [comment]
@abunasar There should be a popup with a stacktrace. Can you provide it?

**Comment by abunasar** [comment]
> @abunasar There should be a popup with a stacktrace. Can you provide it?

There isn't any popup, it just exits!

**Comment by tobiasKaminsky** [comment]
I once digged into this and as we use Intents for transferring the info which files to upload, this is limited and thus crashes.
Currently the only suggestion/workaround is to do this in chunks of eg 500.

**Comment by ezaquarii** [comment]
@abunasar If our crash handler cannot catch it, we can still extract some information from `adb logcat`. Are you able to provide us with logs from that source?

**Comment by abunasar** [comment]
@ezaquarii I uninstalled nexcloud altogether and went with seafile. Nextcloud is way too buggy to use.

**Comment by joshtrichards** [comment]
Closing in favor of #1695 (which this reports to have been partially copied from; and the other report also contains a stack trace).
