### ISSUE TITLE
For more security spongycastle -> bouncycastle

### ISSUE THREAD

**Issue by Neustradamus** [nextcloud/android#5862]
For more security, can you change old spongycastle (based on old bouncycastle) to bouncycastle?
- https://www.bouncycastle.org/
- https://www.bouncycastle.org/releasenotes.html
- http://www.bouncycastle.org/latest_releases.html
- https://www.cvedetails.com/vulnerability-list/vendor_id-7637/Bouncycastle.html

**Comment by tobiasKaminsky** [comment]
We are using spongycastle only for pkix.
I cannot find this package on bouncycastle.
Do you have an idea?

**Comment by Neustradamus** [comment]
@tobiasKaminsky: Thanks for your comment!
Currently Bouncy Castle last version is 1.65 and Spongy Castle last version is 1.58.
Spongy Castle is a fork of Bouncy Castle.
Please look previous links :)

Since several years, a lot of projects have already moved from Spongy Castle to Bouncy Castle because the project is dead.

You can see discussion "34" in https://github.com/rtyley/spongycastle/issues.

**Comment by Neustradamus** [comment]
@tobiasKaminsky: Thanks a lot!

**Comment by Neustradamus** [comment]
@tobiasKaminsky: Can you update to 1.69?

**Comment by AndyScherzinger** [comment]
Thanks for the ping @Neustradamus -->  #8738
