### ISSUE TITLE
[Feature Request / Support] Distinction between video and photo in photo upload?

### ISSUE THREAD

**Issue by kvoit** [nextcloud/android#587]
I recently hit the auto-upload overhaul in the F-Droid Nextcloud app beta. While it looks pretty nice and more general than the old camera upload feature, I seem to miss an important feature, the distinction between video and photo upload on mobile and wifi connection.
While I can afford uploading photos immediately, even my pretty generous 6GB LTE volume does not allow to push 4k videos without wifi.
If this is really not possible right now - e.g. because the upload feature is supposed to be general and not limited to photos and videos - I suggest a file size threshold for immediate mobile-connection upload vs. wifi-only upload.

This is not just a backup issue. I would really like to get my photos to my server immediately, for emergency cases where my phone may be taken away or destroyed afterwards, be it a criminal attacker or e.g. documentation of police violence.

**Comment by tobiasKaminsky** [comment]
This is similar to the issue created by me #486 
If you think this is the same, we can close this one and discuss in #486

**Comment by kvoit** [comment]
Yes, I agree that we can proceed there.
