### ISSUE TITLE
Nextcloud RC app: thumbnails disappear 

### ISSUE THREAD

**Issue by elpraga** [nextcloud/android#588]
### Actual behaviour
Enter a folder with many photos. Wait until all thumbnails are loaded. Leave the folder and enter again. The oldest thumbnails will be missing. (Tried on a folder with 1500 photos)

### Expected behaviour
Once thumnails are loaded, they do not disappear. 
 
@AndyScherzinger do you think this might be just an issue of low cache set in the app? I don't have this problem in the Beta App, and I remember that the default cache size was rather small. 

Would it be possible to raise the default value? (If this is the case of the behavior...)

**Comment by AndyScherzinger** [comment]
@elpraga I sounds like it is related to the cache size, yes. Caching/Thumbnailing has been done by @tobiasKaminsky - what do you think?

**Comment by tobiasKaminsky** [comment]
@elpraga you can see it for yourself: go to app settings -> nextcloud -> storage -> cache size
The cache size is currently set to 10Mb.

**Comment by elpraga** [comment]
But this is possible only in the beta app, and I know about it and I did set it higher there. 

I have this problem in the RC from Google play, where this setting is not present @tobiasKaminsky

**Comment by tobiasKaminsky** [comment]
I meant that you can see if the cache limit (in RC hardcoded to 10mb) is exceeded.
The cache size can, for every app, being seen in android -> preferences -> apps -> nextcloud -> cache.

It is only to verify if the small cache limit is the problem or if you experience another issue.

**Comment by elpraga** [comment]
Thank you for clarifying! I just checked it, and indeed it is the case.  BTW my beta app is using 28 MB of cache.

Is there a reason for the cache to be so small? Could it be raised in the official app as well? (Or maybe could the option from the beta app be added to set the cache size freely?)

**Comment by elpraga** [comment]
Thank you for clarifying! I just checked it, and indeed it is the case.  BTW my beta app is using 28 MB of cache.

Is there a reason for the cache to be so small? Could it be raised in the official app as well? (Or maybe could the option from the beta app be added to set the cache size freely?)

**Comment by tobiasKaminsky** [comment]
Then this is no issue, but just an unwanted behaviour.
I will open a new issue regarding cache size.

**Comment by tobiasKaminsky** [comment]
Then this is no issue, but just an unwanted behaviour.
I will open a new issue regarding cache size: #596

**Comment by elpraga** [comment]
Ok. Thank you for the help.
