### ISSUE TITLE
Content observer work is not re-scheduled after triggered by media update

### ISSUE THREAD

**Issue by ezaquarii** [nextcloud/android#5881]
### Steps to reproduce
1. Configure instant upload of camera images
2. take a photo few times

### Expected behaviour
- Instant upload should be triggered shortly after taking a photo

### Actual behaviour
- Nothing happens - media does not trigger content observer task

**Comment by ezaquarii** [comment]
@tobiasKaminsky this should be fixed before the release

**Comment by tobiasKaminsky** [comment]
Is this on current master? Or on your new PR?

I think we changed behaviour from instant sync to ~15min sync, so it would be an expected behaviour for me?

**Comment by ezaquarii** [comment]
It's on current master. This is a regression introduced by migration to `ContentObserverWork` in 808c9098ea7476fd7e6311aa838e81d90c9e0e99.

The work is re-scheduled using `KEEP` flag. Since the work is running when hile re-scheduling occurs, it cannot replace itself.

The fix is included https://github.com/nextcloud/android/pull/5879

**Comment by tobiasKaminsky** [comment]
> The work is re-scheduled iteself using `KEEP` flag. Since the work is unique and running when re-scheduling occurs, it cannot replace itself.
> 
> The fix is included in #5879
> 
> If you'd like to port it to other branch, just replace `KEEP` -> `REPLACE`.

I am a bit lost: is this included in stable-3.11 branch?
If so, we need to fix it, as I want to release 3.11.1 on Thursday.

**Comment by ezaquarii** [comment]
> > The work is re-scheduled iteself using `KEEP` flag. Since the work is unique and running when re-scheduling occurs, it cannot replace itself.
> > The fix is included in #5879
> > If you'd like to port it to other branch, just replace `KEEP` -> `REPLACE`.
> 
> I am a bit lost: is this included in stable-3.11 branch?
> If so, we need to fix it, as I want to release 3.11.1 on Thursday.

@tobiasKaminsky 

Stable uses different version of this task, with a different bug:

https://github.com/nextcloud/android/blob/stable-3.11.0/src/main/java/com/nextcloud/client/jobs/BackgroundJobManagerImpl.kt

Here, we are scheduling unconditionally. Whenever the app starts, it schedules a new job. As a side effect, the app will be accumulating new `ContentObserverWork` jobs scheduled to run after restart restart.

#5879 uses `sheduleUniqueWork` to have no more than 1. We could do something similar here as well.

**Comment by ezaquarii** [comment]
> Stable uses different version of this task, with a different bug:

@tobiasKaminsky Quick fix for stable issue: https://github.com/nextcloud/android/pull/5912

After applying it, old tasks will die down on completion, leaving only 1 scheduled job left.

**Comment by tobiasKaminsky** [comment]
Nice :+1:
