### ISSUE TITLE
Enabling auto-upload on Camera folder crashes app with ANR

### ISSUE THREAD

**Issue by ezaquarii** [nextcloud/android#5882]
### Steps to reproduce
1. have a decently sized camera folder
2. go to Auto upload
3. toggle camera folder (cloud icon)

### Expected behaviour
- setting toggles, folder is enabled for auto upload

### Actual behaviour
- Application freezes, ANR follows shortly after

### Environment data
Android version: 10
Device model: OnePlus 6T
Stock or customized system: stock
Nextcloud app version: master
Nextcloud server version: not relevant

https://github.com/nextcloud/android/blob/5d428fe9a2f7870505d462672956a83266e0b241/src/main/java/com/owncloud/android/ui/activity/SyncedFoldersActivity.java#L624-L628

Inside this `if` a massinve database I/O on main thread occurs:
https://github.com/nextcloud/android/blob/5d428fe9a2f7870505d462672956a83266e0b241/src/main/java/com/owncloud/android/utils/FilesSyncHelper.java#L88

This won't work. We need to move this massive I/O to a background thread. For the time being, I propose we don't enable upload of existing files by default.

**Comment by tobiasKaminsky** [comment]
I am on it
