### ISSUE TITLE
Stuck in on device 

### ISSUE THREAD

**Issue by krakra9** [nextcloud/android#5896]
### Steps to reproduce 
1. Start app
2. Go to on device 
3. Go to all files

### Expected behaviour
- I expect to be moved to all files on the server. 

### Actual behaviour
- it says on device despite me trying to go on all files again and again. It only gets fixed if I go out of the app and back in

### Environment data
Android version:
9
Device model: 
OnePlus 3
Stock or customized system:
Stock
Nextcloud app version:
3.11

**Comment by dusscloud** [comment]
I noticed the same bug
On way to get back to the server side files is to click "activities" then to click back to "all files"

**Comment by tobiasKaminsky** [comment]
This is fixed via #5617 and will be available in next 3.11.1 (expected to be this week).
Please re-open if it is still valid after update.
