### ISSUE TITLE
Avatars refresh issue

### ISSUE THREAD

**Issue by mario** [nextcloud/android#592]
When you have multiple accounts, sometimes all the avatars have the same picture. Rotating the phone (or closing/reopening the app) fixes that as the activity is killed and recreated. Race condition somewhere?

**Comment by tobiasKaminsky** [comment]
I cannot reproduce it and have never seen it, neither on emulator nor on real device.
@AndyScherzinger what about you?

**Comment by AndyScherzinger** [comment]
@mario can you still reproduce this issue since I also never experienced this behavior nor was I able to enforce it somehow :/

**Comment by tobiasKaminsky** [comment]
Closing, but please re-open if the problem occurs again.
