### ISSUE TITLE
Theme change

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/android#5929]
### Steps to reproduce

1. Select app settings.
2. Change the theme to "Dark".
3. Change the theme to "Follow system" again.
4. Exit settings.
5. **The theme is still dark "Dark"**.

The theme changes only after restarting the app.

### Expected behaviour
- Correct display of the theme after changing it.

### Actual behaviour
- Incorrect theme change.

### Environment data
Android version: 10

Nextcloud app version:  3.11.1

Nextcloud server version: 18.0.3

**Comment by tobiasKaminsky** [comment]
@dan0xii @AndyScherzinger can you both maybe look into it, and try to reproduce and then fix it? :heart:

**Comment by AndyScherzinger** [comment]
Maybe @dan0xii has an idea

**Comment by dan0xii** [comment]
Thinks so. Will have a PR later on today.

**Comment by AndyScherzinger** [comment]
Fixed via  #5952

**Comment by AndyScherzinger** [comment]
Thanks @dan0xii ❤️

**Comment by tobiasKaminsky** [comment]
I think the first approach to fix this did not worked out, so I re-open it.

**Comment by tobiasKaminsky** [comment]
let me give it a try

**Comment by tobiasKaminsky** [comment]
> * Select app settings.
> 
> * Change the theme to "Dark".
> 
> * Change the theme to "Follow system" again.
> 
> * Exit settings.
> 
> * **The theme is still dark "Dark"**.

I tried this with latest master and it works as expected for me…
Can you try latest dev version?

**Comment by tobiasKaminsky** [comment]
@dan0xii 

According to my my understanding setLocalNight(…) and applyDayNight() is only needed if we want to override the default folllow system.

**Comment by Valdnet** [comment]
> Can you try latest dev version?

@tobiasKaminsky It's the same with the dev 20200429 version.

**Comment by Shagequi** [comment]
UP ! @dan0xii
