### ISSUE TITLE
Changing information in the "Community"

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/android#5930]
### Describe the solution you'd like
Information found in "Community":
- Interested in helping out by testing what will be the next version?

In my opinion, information should not be as a question.

![obraz](https://user-images.githubusercontent.com/47037905/80185891-6b3bcf00-860d-11ea-988e-10336618cdab.png)

### Describe alternatives you've considered
Change to e.g.

- Help us test the next version.

**Comment by AlvaroBrey** [comment]
Honestly I think this text should just be removed. It doesn't add any information and is out of place (it's before the forums, instead of the testing versions)

Also, "Oddments" is not an applicable word there in the first paragraph; "odd behaviours" is what we want.

**Comment by AlvaroBrey** [comment]
cc @tobiasKaminsky , prompted by #11172

**Comment by tobiasKaminsky** [comment]
Fine by removing it.
But then also link to irc.
