### ISSUE TITLE
App freezes when changing automatic upload settings

### ISSUE THREAD

**Issue by jnsmn** [nextcloud/android#5932]
### Steps to reproduce
1. Open settings of any automatic uploading folder
2. change any setting (hitting "save" afterwards is not even required sometimesfor reproducing this bug)

or

1. Tab on blue cloud symbol of automatic upload folder to toggle automatic uploads on/off

### Expected behaviour
- User should be able to continue working in app by i.e. hitting back button of phone

### Actual behaviour
- App freezes and needs to be closed entirely by user though android app overview or by waiting for android notification "app doesn't react anymore"

### Can you reproduce this problem on https://try.nextcloud.com?
No. It is an app related issue from my understandig

### Environment data
Android version: 9

Device model: Xiaomi Mi5

Stock or customized system: LineageOS 16.0-20200412-NIGHTLY-gemini

Nextcloud app version: 3.11.0

Nextcloud server version: 18.0.4

Reverse proxy: none

**Comment by tobiasKaminsky** [comment]
This should be fixed with latest 3.11.1 version.
If not please re-open.
