### ISSUE TITLE
stuck on device

### ISSUE THREAD

**Issue by hboetes** [nextcloud/android#5934]
After downloading some files I selected the "on device" item. And after that I wanted to download something else, so I tried to select "All files", the app starts thinking for a long time but after a while it stops  and I still was on the "on device" section.

To get out of "on device" I have to select "activities" and then "All files"

Is this repeatable?

**Comment by tobiasKaminsky** [comment]
Please update as this is fixed with latest version.
If not, please re-open.

**Comment by hboetes** [comment]
Yup, works again as expected. Thanks!
