### ISSUE TITLE
"All files" section fails to open after opening "On Devive" section

### ISSUE THREAD

**Issue by navilg** [nextcloud/android#5935]
### Steps to reproduce
1. Open the nextcloud android app.
2. Click on "On device" from left panel. (In my case On device is empty)
3. Again, click on "All files" option from left panel.

### Expected behaviour
- Once we click on "All files", it should have opened the files on nextcloud. 

- To return to "All files", I need to take an intermediate path, like clicking on some other option first, then clicking on "All files".

### Actual behaviour

- It stays in "On device " page and doesn't return to "All files".

### Can you reproduce this problem on https://try.nextcloud.com? It opens mobile web version. Web version doesn't have on device option. Issue is in android version.

- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 8.0.0

Device model: Samsung SM-C701F/DS

Stock or customized system: Stock

Nextcloud app version: 3.11.0

Nextcloud server version: 17.0.5

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
> Nextcloud app version: 3.11.0

Please update as this is fixed with latest version.
If not, please re-open.
