### ISSUE TITLE
It's possible to create a account with wrong username capitalisation

### ISSUE THREAD

**Issue by JSoko** [nextcloud/android#594]
see https://github.com/nextcloud/server/issues/3305

### Actual behaviour
If you have a user testuser you con connect with NextcloudAndroid entering the username Testuser
While uploading files you get a warning 
### Expected behaviour
No problems or don't connect because of the wrong capitalisation (T instead of t)
 
### Steps to reproduce
see https://github.com/nextcloud/server/issues/3305

**Comment by tobiasKaminsky** [comment]
cc @LukasReschke what is the desired behaviour?

**Comment by mario** [comment]
Seems to be a server issue - so closing it here.

**Comment by nickvergessen** [comment]
No the server can not handle this. You can get the correct user id casing from:
The `cloud/user` endpoint gives you the correct spelling in the `<id>` element:
```
curl -H "OCS-APIREQUEST: true" https://Admin:admin@localhost/ocs/v2.php/cloud/user
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>200</statuscode>
  <message>OK</message>
 </meta>
 <data>
  <id>admin</id>
  <display-name>Administrator</display-name>
 </data>
</ocs>
```

however not sure if that works with ldap, so I'd just use that if `lower(id) === lower(provided id)`

**Comment by tobiasKaminsky** [comment]
I tried it with my current NC and current android app and used "Tobi" instead of "tobi" and it is working without any issue. I tried both auto upload and manually upload.
