### ISSUE TITLE
Android app doesn't login if Nextcloud behind reverse proxy with SSL

### ISSUE THREAD

**Issue by rafaelrs** [nextcloud/android#5945]
I am newly installed nextcloud server, it works ok, thru web everything fine. It work as nextcloud+apache server <- ngninx revers proxy + let's encrypt cert's <- router. I checked, nextcloud works on web as locally, and externally (outside of local networks thru internet). Android also works ok locally (http://nexcloud.home), but if i use external url and https (https://nextcloud.mydomain.com) it stuck on login. There no any errors neither in Apache or nginx or nextcloud logs. Also i tried trick, i made reverse proxy on 80 port without SSL (i just copied location / {} block there and turned off server on 443 port) - logins ok. Now after that i turned my config back so it redirect 80(http) to 443(https) and found that already logged in app still works: a can browse files at least, but events give me error, i didn't checked other functionality

### Steps to reproduce
1. Install Android app
2. Enter server
3. Enter login, pass work, press login
4. App stucks on in infitely
5. If you now press back, there button, says to start login again
6. If you press it, it doesn't asks login/pass again, but says to "Allow access to android device"
7. I press allow and stucks again and no any chance to make it move forward any way
8. Entering wrong password works as expected

### Expected behaviour
Normal login

### Actual behaviour
Stuck

### Environment data
Android version:
Tried 8.1.0 and 5.1.1

Device model: 
ASUS ZC554KL, Highscreen PowerFive

Stock or customized system:
Tried both - stock and customized

Nextcloud app version:
3.11.1
Nextcloud server version:
18.0.4.2
Reverse proxy:
nginx 1.16.1

Nginx config:
I tried many different options and configs, for example i copied lines 9-82 from here: https://github.com/BobyMCbobs/nextcloud-docker-nginx-reverse-proxy/blob/master/nginx.cfg
Apache config for virtual host (everything rest is untouched and standart for Centos 7):
```
<VirtualHost *:80>
        ServerName nextcloud.mydomain.com
        ServerAdmin admin@nextcloud.mydomain.com
        DocumentRoot /var/www/html/nextcloud
        <directory /var/www/html/nextcloud>
                Require all granted
                AllowOverride All
                Options FollowSymLinks MultiViews
                SetEnv HOME /var/www/html/nextcloud
                SetEnv HTTP_HOME /var/www/html/nextcloud
         </directory>
</VirtualHost>
```

#### Nginx proxy server logs during process
```
91.193.178.6 - - [27/Apr/2020:03:26:29 +0000] "GET /status.php HTTP/1.1" 200 170 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.11.1" "-"
91.193.178.6 - - [27/Apr/2020:03:26:29 +0000] "HEAD /remote.php/webdav/ HTTP/1.1" 401 0 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.11.1" "-"
91.193.178.6 - - [27/Apr/2020:03:26:29 +0000] "GET /index.php/login/flow HTTP/2.0" 200 6874 "-" "Asus ASUS_X00ID (Android)" "-"
91.193.178.6 - - [27/Apr/2020:03:26:29 +0000] "GET /index.php/core/js/oc.js?v=e8e710c4 HTTP/2.0" 200 8053 "-" "Asus ASUS_X00ID (Android)" "-"
91.193.178.6 - - [27/Apr/2020:03:26:30 +0000] "GET /cron.php HTTP/2.0" 200 20 "-" "Asus ASUS_X00ID (Android)" "-"
91.193.178.6 - - [27/Apr/2020:03:26:34 +0000] "GET /index.php/login/flow/grant?stateToken=CMu9M9ONiVmdH7lENmdz923oz2r2oXipnx59BtA6Sxx9DAATfzsakbz25E6HB9Tq&clientIdentifier= HTTP/2.0" 303 0 "-" "Asus ASUS_X00ID (Android)" "-"
91.193.178.6 - - [27/Apr/2020:03:26:34 +0000] "GET /index.php/login?redirect_url=/index.php/login/flow/grantstateToken%3DCMu9M9ONiVmdH7lENmdz923oz2r2oXipnx59BtA6Sxx9DAATfzsakbz25E6HB9Tq%26clientIdentifier%3D HTTP/2.0" 200 6282 "-" "Asus ASUS_X00ID (Android)" "-"
91.193.178.6 - - [27/Apr/2020:03:26:34 +0000] "GET /index.php/core/js/oc.js?v=e8e710c4 HTTP/2.0" 200 8053 "-" "Asus ASUS_X00ID (Android)" "-"
91.193.178.6 - - [27/Apr/2020:03:26:35 +0000] "GET /cron.php HTTP/2.0" 200 20 "-" "Asus ASUS_X00ID (Android)" "-"
91.193.178.6 - - [27/Apr/2020:03:26:57 +0000] "POST /index.php/login HTTP/2.0" 303 0 "-" "Asus ASUS_X00ID (Android)" "-"
```
In Apache logs i see similar 10 entries that finishes with "POST /index.php/login HTTP/1.1" 303"

#### Nextcloud log (data/nextcloud.log)
there nothing in nextcloud logs

#### Logcat filtered by nextcloud (data/nextcloud.log) during that process
```
2020-04-27 06:51:41.394 18120-18168/? I/GetStatusRemoteOperation: Connection check at https://nextcloud.myhost.com: Operation finished with HTTP status code -1 (success)
2020-04-27 06:51:41.497 18120-18168/? I/HttpMethodDirector: No credentials available for BASIC 'Nextcloud'@nextcloud.myhost.com:443
2020-04-27 06:51:41.498 18120-18168/? D/ExistenceCheckRemoteOperation: Existence check for https://nextcloud.myhost.com/remote.php/webdav/ targeting for  existence finished with HTTP status 401(FAIL)
```

**Comment by rafaelrs** [comment]
I've found also that other peoples was facing that problem, and didn't found any solution:
https://help.nextcloud.com/t/reverse-proxy-with-android-client-does-not-work/3346/3

**Comment by AndyScherzinger** [comment]
@rafaelrs just checking since this is the number one configuration issue on the server side, did you
set this in your config fin´le?

'overwriteprotocol' => 'https',

see https://docs.nextcloud.com/server/18/admin_manual/configuration_server/reverse_proxy_configuration.html#overwrite-parameters

**Comment by rafaelrs** [comment]
@AndyScherzinger , no! I added it and now it work! 

Thank you

**Comment by AndyScherzinger** [comment]
Happy I could help 😃

**Comment by gr01d** [comment]
Hi, I am having the same issue with reverse proxy nginx without SSL.
I have updated my Nextcloud Android to the latest version **(3.11.1)** in F-Droid.
Added `'overwriteprotocol' => 'http',` to config file and restarted nginx, whenever I login (grant access to device name). It just loops again. I see the 401 error from my nginx log about `HEAD /nextcloud/remote.php/webdav`.
