### ISSUE TITLE
Backspace not working

### ISSUE THREAD

**Issue by dolamroth69** [nextcloud/android#5950]
### Steps to reproduce
1. When editing any odt file in the app, the backspace key is not working
2. 
3. 

### Expected behaviour
Backspace should delete previous characters

### Actual behaviour
Nothing happens at all – no backwards deletion, not even a cursor movement

### Can you reproduce this problem on https://try.nextcloud.com?
No, issue only in the Android app

### Environment data
Android version:
9
Device model: 
moto g 7 play
Stock or customized system:

Nextcloud app version:
3.11.0
Nextcloud server version:
n.a.
Reverse proxy:
n.a.
#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Which kind of office integration do you use?
Only Office, Collabora, Document server (coming with NC Hub)

**Comment by dolamroth69** [comment]
I am using Collabora office integration
--
T. +49 171 4115114
LinkedIn <https://www.linkedin.com/in/michaelmiener> | Xing <https://www.xing.com/profile/Michael_Miener>

**Comment by Chillstice** [comment]
This same behavior can be seen in the Android App 3.12.0 with Nextcloud 18.0.6 and the built-in version of Only Office 5.4.2

Makes correcting typos really annoying because there's a chance that the backspace will work a couple times right after reopening the document.

**Comment by thebearon** [comment]
> I am using Collabora office integration -- T. +49 171 4115114 LinkedIn <https://www.linkedin.com/in/michaelmiener> | Xing <https://www.xing.com/profile/Michael_Miener>

Give it a try with the Gboard virtual keyboard app.

**Comment by tobiasKaminsky** [comment]
As NC just opens up a webview showing Collabora/OnlyOffice, please open it up in their repositories.
