### ISSUE TITLE
Do not show three dots while search

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#5958]
Follow up discussion of #5933 

![image](https://user-images.githubusercontent.com/5836855/80501009-357d4a00-896f-11ea-848e-f7c4c76801e1.png)

I did a check and gmail and other material designed apps to not show the three dots button while searching.

Gmail:
![image](https://user-images.githubusercontent.com/5836855/80501123-5ba2ea00-896f-11ea-8c25-f7e433f77877.png)

@JorisBodin

**Comment by tobiasKaminsky** [comment]
Ah. Totally true.
I just saw that we also have the three dot button on latest stable/dev.

Shall I keep this open?

**Comment by JorisBodin** [comment]
@tobiasKaminsky We can close :)
