### ISSUE TITLE
Intermediate bar which when shown/hidden makes the content jump, this didn't happen before.

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#5963]
One minor issue that should be fixed (maybe in another PR?) is the intermediate bar which when shown/hidden makes the content jump, this didn't happen before.

Is this appbar shown anywhere where the loading needs to be displayed? Asking sind the search bar would rather use the circular spinner and maybe we should just switch to that one only, since we use it on other screens like activities or notifications.

_Originally posted by @AndyScherzinger in https://github.com/nextcloud/android/pull/5933#issuecomment-620809382_

**Comment by tobiasKaminsky** [comment]
@JorisBodin :-)

**Comment by JorisBodin** [comment]
@AndyScherzinger You mean the ProgressBar?

See with @jancborchardt, we remove this and keep only the Swipe-to-Refresh (like google drive)

But we can easily correct this by not using a GONE but an INVISIBLE visibility.

**Comment by tobiasKaminsky** [comment]
Removing it is fine, I think :-)

**Comment by AndyScherzinger** [comment]
@JorisBodin perfect 👍
