### ISSUE TITLE
Weird checkboxes bug in Documents/Photos

### ISSUE THREAD

**Issue by Shagequi** [nextcloud/android#5970]
Hi, 
There is a bug relative to file multi-selection mode in "Document" and "Photos" File list for Nextcloud 18. Due to the "folder description" on the top, there is a bug during this, I let you see the gif.

![qjNlgIOcVH](https://user-images.githubusercontent.com/7050479/80615035-7b094800-8a3f-11ea-93f7-82deebee53d5.gif)

I thought the UI revamp (https://github.com/nextcloud/android/issues/5207) was responsible of this, but no, it's a more "distant" bug.

**Comment by AndyScherzinger** [comment]
Reproducable on master, yes 😐

**Comment by tobiasKaminsky** [comment]
I am on it
