### ISSUE TITLE
White back button in ManageAccountsActivity due to UI revamp

### ISSUE THREAD

**Issue by Shagequi** [nextcloud/android#5972]
Hey,
The title is very explicit :)
The button to go back is white on a "white" background, so we don't see it.

**Comment by Shagequi** [comment]
Relative to this : https://github.com/nextcloud/android/issues/5207 and because of this : https://github.com/nextcloud/android/pull/5933.

**Comment by AndyScherzinger** [comment]
@Shagequi follow up might be the user info activity (if you click on an item in the user list in this activity) since back button is white (likely fine due to the background image) while the three dot menu icon gets tinted.
