### ISSUE TITLE
Rich workspace should be disabled for the search

### ISSUE THREAD

**Issue by svenb1234** [nextcloud/android#5988]
### Is your feature request related to a problem? Please describe.
When searching from the root files/folders list, the rich workspace is shown above the search result.

This hides the spinner https://github.com/nextcloud/android/issues/5989 and e.g. the "no matches found" message https://github.com/nextcloud/android/issues/5990.

### Describe the solution you'd like
In my opinion the richt workspace should be disabled for the search. What use does it have in the context of displaying swarch results?

**Comment by joshtrichards** [comment]
I can't find the PR offhand (may have been general unified search stuff), but this appears to not be an issue today. If you can reproduce it let me know here and I'll reopen this.
