### ISSUE TITLE
Show a spinner or some signal of "search in progress" (rich workspace)

### ISSUE THREAD

**Issue by svenb1234** [nextcloud/android#5989]
### Is your feature request related to a problem? Please describe.
Currently, when one starts a search with the rich workspace enabled, there is no indication of the search actually running. _No spinner, no text displayed "searching..." or similar hints to the user that something is happening.

Or disable the rich workspace for the search, see https://github.com/nextcloud/android/issues/5988.

### Describe the solution you'd like
Show the user some hint that the search is in progress.

App 3.11.1

**Comment by joshtrichards** [comment]
There's a spinner today. Also #5988 addressed. So I believe this is addressed. Free to reply/re-open if I overlooked something.
