### ISSUE TITLE
fullscreen video shows only a black screen

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/android#5994]
### Steps to reproduce
1. Start any video 
2. Tip on the sceen while it is playing
3. Display gets black, nothing will happen

### Expected behaviour
- Watch the video in fullscreen

I can reproduce it on https://try.nextcloud.com
Tried with three different smartphones

**Comment by tobiasKaminsky** [comment]
how did you started the video? Is it a downloaded video or streaming?

**Comment by jakobroehrl** [comment]
Streaming, tested it again with 2 new videos. In the app it tooks 14-15 secs to start, in the mobile browser 1-2 secs. 
Downloaded videos are playing instandly.

**Comment by tobiasKaminsky** [comment]
@ezaquarii as you enhanced media player recently.
Do you have an idea what could the player take so long to start?
Given that it starts in browser ~ 10x faster, it cannot be that the bandwith is too low.

Maybe we are buffering too much?

**Comment by ezaquarii** [comment]
@tobiasKaminsky I did the audio player. Video player uses `VideoView` that uses internal player. We didn't touch video playback at all.

**Comment by svenb1234** [comment]
I see the same frequently when switching to full screen.

**Comment by jakobroehrl** [comment]
Problem is still there

**Comment by tobiasKaminsky** [comment]
I tried it with a OnePlus 6T, with LineageOS.
I download a file, started to watch the video and clicked on it to get fullscreen, and it worked.

**Comment by jakobroehrl** [comment]
Tested this weekend with other smartphones. On P30 it works well, for example. 
But at least some OnePlus smartphones still have problems with that. 
As a workaround I use "stream with -> VLC"

**Comment by tobiasKaminsky** [comment]
Hm. So if it is a problem of OnePlus/Oxygen I fear that I cannot really help…We are using VideoView, which is plain Android.
So maybe you can open up an issue on Oxygen OS?
