### ISSUE TITLE
Filter

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#60]
- Filter current files and folders (no subfolders) by typing. 
- Search also in the middle of the name
- "search" icon next to three-dot menu as it is a very important task so it should be always visible

PR: #152

**Comment by tobiasKaminsky** [comment]
https://github.com/owncloud/android/issues/695
https://github.com/owncloud/android/issues/696

**Comment by AndyScherzinger** [comment]
I need to investigate this but if I am not mistaken there is a nice way to do it directly in the toolbar

**Comment by jancborchardt** [comment]
Yeah, many other apps like Signal, Contacts, VLC etc put the search action directly in the toolbar cause it’s quite an important help to quickly find what you need. I’d do the same, and next to it put the 3-dot icon for the other actions.

**Comment by tobiasKaminsky** [comment]
So we have a conclusion?
![4hoqo](https://cloud.githubusercontent.com/assets/5836855/16339399/bfc3cab8-3a22-11e6-9bfd-964e66b1ca66.png)

**Comment by AndyScherzinger** [comment]
Yes! :smiley: That would also be my choice on how to do this :+1:

**Comment by tobiasKaminsky** [comment]
Uh, yeah "approved" is a cool label :+1:

**Comment by AndyScherzinger** [comment]
Yeah,  I just need to check if we already documented this in our lean dev process

**Comment by supportreq** [comment]
@AndyScherzinger when will this be live?

**Comment by AndyScherzinger** [comment]
Hi @supportreq none of us has started with this yet. So I can't give you any date yet. Cc @tobiasKaminsky @przybylski

**Comment by tobiasKaminsky** [comment]
PR: #60

**Comment by AndyScherzinger** [comment]
Hi @supportreq the feature has been implemented and is now in code review, so 1.3.0 is a quite save assumption. Thus around end of August, beginning of September :rocket:

**Comment by jancborchardt** [comment]
Which is damn awesome work by you folks by the way. We’re getting some really great useful & anticipated features in! :)

**Comment by AndyScherzinger** [comment]
Thanks! :) Except for the "eierlegende Wollmilchsau", we are still missing that one :wink:

**Comment by AndyScherzinger** [comment]
PR is already on master and is thus part of the next release thus closing this issue.
