### ISSUE TITLE
Displaying SORT option on the action bar

### ISSUE THREAD

**Issue by pilsnerbeer** [nextcloud/android#6009]
### Is your feature request related to a problem? Please describe.
I use SORT very often and changing sort mode currently requires 3 taps. Given the importance of the function, I suggest to put it on the action bar next to search.

### Describe the solution you'd like
Solution pictured: (no other changes to the function or design)

![sort](https://user-images.githubusercontent.com/36133540/81085671-ccaa4a80-8ef7-11ea-9e84-4f99d84e3bae.png)

**Comment by AndyScherzinger** [comment]
Hi @pilsnerbeer,

this will be fixed with 3.13, see design changes in  #5992
