### ISSUE TITLE
Account removal

### ISSUE THREAD

**Issue by aca95** [nextcloud/android#6012]
### Steps to reproduce
1. Add new account
2. Delete old account

### Expected behaviour
- It should delete the old account

### Actual behaviour
- Shows the error

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 9

Device model: Huawei P Smart Z

Stock or customized system:

Nextcloud app version: 20200501

Nextcloud server version: 16.0.10

Reverse proxy:

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke interface method 'void com.nextcloud.client.jobs.BackgroundJobManager.startAccountRemovalJob(java.lang.String, boolean)' on a null object reference
	at com.owncloud.android.ui.activity.UserInfoActivity$AccountRemovalConfirmationDialog.lambda$onCreateDialog$0$UserInfoActivity$AccountRemovalConfirmationDialog(UserInfoActivity.java:375)
	at com.owncloud.android.ui.activity.-$$Lambda$UserInfoActivity$AccountRemovalConfirmationDialog$osA3sIya6dPwTaPaGxHf1imuA9A.onClick(Unknown Source:2)
	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
	at android.os.Handler.dispatchMessage(Handler.java:112)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20200501
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWSTK-HF
Model: STK-LX1
Id: HUAWEISTK-LX1
Product: STK-L21EEA

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 9.1.0.280C431

```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
@ezaquarii can you have a look?

https://github.com/nextcloud/android/blob/1a2d85a9cb8c22bbb8c2d020e5266ed061635fba/src/main/java/com/owncloud/android/ui/activity/UserInfoActivity.java#L332-L335

Seems that injecting is somehow not working.

**Comment by aca95** [comment]
Im sorry, i dont know where and what should i do, im not a dev

**Comment by aca95** [comment]
Also, unrelated to this: when im in the app it always shows at the bottom that there is an update but in the store there is none, its on the latest version.

**Comment by tobiasKaminsky** [comment]
> Also, unrelated to this: when im in the app it always shows at the bottom that there is an update but in the store there is none, its on the latest version.

If it is unrelated, then open up next time a new issue (as it is indeed a valid bug).
(it will be fixed with https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6728)
