### ISSUE TITLE
SSL certificate not trusted only with Android App

### ISSUE THREAD

**Issue by flogoe** [nextcloud/android#6018]
### Steps to reproduce
1. Install the Nextcloud App for Android
2. Press "Log in"
3. Type in "https://mydomain.de"

### Expected behaviour
- Should trust the SSL server certificate, because its working in Firefox, Chrome and the IOS app.

### Actual behaviour
A dialog shows up and says:
```
The identity of the server could not be verified
- The server certificate is not trusted

Do you want to trust this certificate anyway?
```

### Can you reproduce this problem on https://try.nextcloud.com?
- Created a test demo and tried to connect to it via the Android App.
- Everything is working fine here.

### Environment data
Android version: 8.0.0

Device model: Samsung A5

Stock or customized system: Stock

Nextcloud app version: 3.11.1

Nextcloud server version: 18.0.4

Reverse proxy: yes, nginx

#### Nextcloud log (data/nextcloud.log)
```
...
[ip-addr] - - [06/May/2020:20:09:12 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.0" 200 3859 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0"
[ip-addr] - - [06/May/2020:20:09:42 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.0" 200 3859 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0"
[ip-addr] - - [06/May/2020:20:10:12 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.0" 200 3859 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0"
[ip-addr] - - [06/May/2020:20:10:42 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.0" 200 3859 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0"
```
### Certificate
Organisation: DigiCert Inc
Common Name: RapidSSL RSA CA 2018

**Comment by tobiasKaminsky** [comment]
Can you send the server url to tobias at nextcloud dot com with a reference to this issue?

**Comment by flogoe** [comment]
Sure, I sent you the email.

**Comment by flogoe** [comment]
Thank you @tobiasKaminsky for your help. 

There was a problem within my cert chain that led to this problem. I fixed the cert chain and the error message was gone.
