### ISSUE TITLE
Json Null with android 6

### ISSUE THREAD

**Issue by amsaravi** [nextcloud/android#6021]
### Steps to reproduce
after fresh install and selecting present next-cloud account the program does not enter and says that JSON null. i tried with my wife's phone (android 8) an every thing is fine

### Expected behavior
- should enter the program and see the app working

### Can you reproduce this problem on https://try.nextcloud.com?
after several times of trial and error i couldn't make my phone enter the next-cloud demo up and running so i couldn't test on that

### Environment data
Android version: 6

Device model: GLX Pars

Stock or customized system:

Nextcloud app version: 3.7.2

Nextcloud server version: 18 docker image

Reverse proxy:

#### Web server error log
```
no error log:
Nginx revers proxy:
92.168.1.122 - amsaravi [07/May/2020:06:24:31 -0400] "GET /ocs/v2.php/cloud/capabilities?format=json HTTP/1.1" 200 3443 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.7.2" "-"                                  
192.168.1.122 - amsaravi [07/May/2020:06:24:31 -0400] "GET /ocs/v2.php/cloud/capabilities?format=json HTTP/1.1" 200 3443 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.7.2" "-"                                  
192.168.1.122 - amsaravi [07/May/2020:06:24:31 -0400] "GET /index.php/apps/deck/api/v1.0/boards?details=true HTTP/1.1" 200 9704 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.7.2" "-"                           
192.168.1.124 - amsaravi [07/May/2020:06:24:33 -0400] "PROPFIND /remote.php/dav/files/amsaravi/ HTTP/1.1" 207 388 "-" "Mozilla/5.0 (Linux) mirall/2.6.4git (Nextcloud)" "-"                                       
192.168.1.124 - amsaravi [07/May/2020:06:24:40 -0400] "PROPFIND /remote.php/dav/files/amsaravi/ HTTP/1.1" 207 389 "-" "Mozilla/5.0 (Linux) mirall/2.6.4git (Nextcloud)" "-" 
```
cnt see any new log in apache2 access and error logs
No difference if i connect directly to apache by ip (bypassing nginx revers proxy). maybe it is a problem with my old android device

#### Nextcloud log (data/nextcloud.log)
```
when i use `tail -f ` no new log is generated. maybe the request was not sent to the server. i tried that with my wife's phone(android 8) and every thing is fine

**Comment by tobiasKaminsky** [comment]
> GET /index.php/apps/deck/api/v1.0/boards

@stefan-niedermann I guess this is about your app, or?

**Comment by stefan-niedermann** [comment]
@amsaravi if your issue is about thr Nextcloud Deck Android app please open the issue here: https://github.com/stefan-niedermann/nextcloud-deck/issues/new?assignees=&labels=bug&template=bug_report.md&title=

And also mention the versions of your Nextcloud instance and of your server side deck app besides all the other asked information in the template.

**Comment by stefan-niedermann** [comment]
Your Nextcloud app version seems to be very outdated (3.7.2). Please update and try again whatever you did first.
