### ISSUE TITLE
NC-app crashes when opening foto folder

### ISSUE THREAD

**Issue by lorchix** [nextcloud/android#6024]
### Steps to reproduce
1. Login into NC app
2. click into foto folder and 
3. wait till all fotos in are loaded
4. after a while app crashes

### Expected behaviour
- show list of all fotos contained in foto folder

### Actual behaviour
- OutofBoundException

### CoreDump:
************ CAUSE OF ERROR ************

java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionOCFileListGridImageViewHolder{6412d27 position=32 id=-1, oldPos=-1, pLpos:-1 no parent} com.owncloud.android.ui.EmptyRecyclerView{b664f5e VFED..... .F...... 0,0-1440,2224 #7f0901b5 app:id/list_root}, adapter:com.owncloud.android.ui.adapter.OCFileListAdapter@7729f3f, layout:androidx.recyclerview.widget.GridLayoutManager@20d300c, context:com.owncloud.android.ui.activity.FileDisplayActivity@39930d4
	at androidx.recyclerview.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5974)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6158)
	at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:288)
	at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:345)
	at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:361)
	at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:368)
	at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:399)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30110190
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: samsung
Device: herolte
Model: SM-G930F
Id: R16NW
Product: heroltexx

************ FIRMWARE ************
SDK: 26
Release: 8.0.0
Incremental: G930FXXS7ETA7

### Environment data
Android version: see coredump

Device model: SGS7 (see coredump)

Stock or customized system: stock

Nextcloud app version: 3.11.1

Nextcloud server version: 18.04

#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"RTDOP8xnGbK7Kd1K6ikg","level":3,"time":"2020-05-08T08:07:33+00:00","remoteAddr":"91.18.7.50","user":"nc1-Lorch","app":"PHP","method":"POST","url":"/index.php/apps/support/generateSystemReport","message":"Undefined index: readonly at /var/www/nextcloud/apps/support/lib/Sections/ServerSection.php#268","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0","version":"18.0.4.2","id":"5eb51835e6b68"}
{"reqId":"RTDOP8xnGbK7Kd1K6ikg","level":3,"time":"2020-05-08T08:07:33+00:00","remoteAddr":"91.18.7.50","user":"nc1-Lorch","app":"PHP","method":"POST","url":"/index.php/apps/support/generateSystemReport","message":"Undefined index: readonly at /var/www/nextcloud/apps/support/lib/Sections/ServerSection.php#268","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0","version":"18.0.4.2","id":"5eb51835e6b78"}
{"reqId":"n8NvyfW4pCkSaRELDPYJ","level":3,"time":"2020-05-07T22:22:10+00:00","remoteAddr":"91.18.7.50","user":"anja","app":"PHP","method":"GET","url":"/index.php/apps/deck/","message":"Undefined index: debug at /var/www/nextcloud/apps/deck/templates/main.php#31","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0","version":"18.0.4.2","id":"5eb51835e6b82"}
....

**Comment by tobiasKaminsky** [comment]
Do you scroll? Or really just keep it loading?

**Comment by lorchix** [comment]
Hi,
no scrolling, just keep it loading. Tried it twice.

Tnx fr assistants.
Lorchix

Am 12. Mai 2020 08:22:59 MESZ schrieb Tobias Kaminsky <notifications@github.com>:
>Do you scroll? Or really just keep it loading?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nextcloud/android/issues/6024#issuecomment-627135879

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.
