### ISSUE TITLE
🔑 Support for client certificates

### ISSUE THREAD

**Issue by mlsxlist** [nextcloud/android#603]
### Actual behaviour
In order to secure Nextcloud on TLS level, it would be good if the app could support client certificates. If the client certificate is not sent on handshake, the server prevents access to Nextcloud logon page. This would provide a second line of defense.

### Expected behaviour
Nextcloud app should support client certificates as other apps like caldav sync and carddav sync already do.

**Comment by riesnerd** [comment]
Hello mlsxlist,

if this is of any use to the case, there is an open issue about this over at the owncloud github site:

https://github.com/owncloud/android/issues/163

Best wishes
riesnerd

**Comment by tobiasKaminsky** [comment]
I would vote this "medium" to get this done when we (@mario or me) have time.
Everything that enhances the security of the app/nextcloud should have priority.
cc @mario ?

**Comment by riesnerd** [comment]
Okay thanks! In some way this also enhances security. ;)

**Comment by mario** [comment]
@tobiasKaminsky let me think about it, and I'll come back to you - we need to focus on fixing current issues first to make the app (more) usable than it is now - thought definitely this is something we want to do in the future.

**Comment by riesnerd** [comment]
Okay thanks in advance!

**Comment by seanlynch** [comment]
I would also very much like to see this, because it protects from potential issues with the login page as well as weak passwords and password guessing attacks.

**Comment by lucacarangelo** [comment]
Any news on this ? This is a very important enhancement !

**Comment by AndreasMettlen** [comment]
@mario let me know if you still need a test setup with client certificates enabled. In the meantime I will try to look into this (I haven't worked on android apps yet, but I can find my way around in php/java/python so I will give it a try)

**Comment by mario** [comment]
@AndreasMettlen yes I do. Send me the required cert + url, server and pass to mario@nextcloud.com :)

**Comment by AndreasMettlen** [comment]
@mario Did you have a chance yet to look into this ?

**Comment by mbrescia** [comment]
Hi,
I really look forward for this enhancement.
In the meantime I've tried to patch the code on Android and it kinda works... even if it's ugly as hell 😈 
I've used the Android KeyChain features to allow the user to select a PKCS12 certificate and then stored the cert alias into the app preferences:

AuthenticatorActivity
```
private void checkOcServer() {
        if (mHostUrlInput != null) {
            uri = mHostUrlInput.getText().toString().trim();
            mOkButton.setEnabled(false);
            showRefreshButton(false);
        } else {
            uri = mServerInfo.mBaseUrl;
        }

        mServerIsValid = false;
        mServerIsChecked = false;
        mServerInfo = new GetServerInfoOperation.ServerInfo();

        if (uri.length() != 0) {
            if (mHostUrlInput != null) {
                uri = AuthenticatorUrlUtils.stripIndexPhpOrAppsFiles(uri);
                mHostUrlInput.setText(uri);
            }

            // Handle internationalized domain names
            try {
                uri = DisplayUtils.convertIdn(uri, true);
            } catch (IllegalArgumentException ex) {
                // Let Owncloud library check the error of the malformed URI
                Log_OC.e(TAG, "Error converting internationalized domain name " + uri, ex);
            }

            if (mHostUrlInput != null) {
                mServerStatusText = getResources().getString(R.string.auth_testing_connection);
                mServerStatusIcon = R.drawable.progress_small;
                showServerStatus();
            }

            if (NetworkUtils.alias == null) {
                KeyChain.choosePrivateKeyAlias(this, (KeyChainAliasCallback) this, null, null, uri, -1, null);
            } else {
                startServerInfoIntent();
            }

        } else {
            mServerStatusText = "";
            mServerStatusIcon = 0;
            if (!webViewLoginMethod) {
                showServerStatus();
            }
        }
    }
```

```
public void alias(final String alias) {
        System.out.println("THREAD: " + Thread.currentThread().getName());
        System.out.println("Selected alias: " + alias);
        try {
            SharedPreferences sp = PreferenceManager.getDefaultSharedPreferences(this.getApplicationContext());
            SharedPreferences.Editor editor = sp.edit();
            editor.putString("TLS_ALIAS", alias);
            editor.commit();

            startServerInfoIntent();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
```

Then it uses the cert to initialize the SslSocketFactory:

NetworkUtils (nextcloud-android-library)
```
public static AdvancedSslSocketFactory getAdvancedSslSocketFactory(Context context) 
    		throws GeneralSecurityException, IOException {

        if (mAdvancedSslSocketFactory  == null) {

            if(chain == null || pk == null || alias == null) {
                // try to recover from preferences
                SharedPreferences sp = PreferenceManager.getDefaultSharedPreferences(context);
                alias = sp.getString("TLS_ALIAS", "");
                try {
                    chain = KeyChain.getCertificateChain(context, alias);
                    pk = KeyChain.getPrivateKey(context, alias);
                } catch (KeyChainException e) {
                    e.printStackTrace();
                } catch (InterruptedException e) {
                    e.printStackTrace();
                } catch (NullPointerException e) {
                    e.printStackTrace();
                }
            }

            if(chain != null) {
                KeyStore trustStore = KeyStore.getInstance(KeyStore.getDefaultType());

                X509ExtendedKeyManager keyManager = new X509ExtendedKeyManager() {

                    @Override
                    public String chooseClientAlias(String[] strings, Principal[] principals, Socket socket) {
                        return alias;
                    }

                    @Override
                    public String chooseServerAlias(String s, Principal[] principals, Socket socket) {
                        return alias;
                    }

                    @Override
                    public X509Certificate[] getCertificateChain(String s) {
                        return chain;
                    }

                    @Override
                    public String[] getClientAliases(String s, Principal[] principals) {
                        return new String[]{alias};
                    }

                    @Override
                    public String[] getServerAliases(String s, Principal[] principals) {
                        return new String[]{alias};
                    }

                    @Override
                    public PrivateKey getPrivateKey(String s) {
                        return pk;
                    }
                };

                TrustManagerFactory trustFactory = TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());
                trustFactory.init(trustStore);
                TrustManager[] trustManagers = trustFactory.getTrustManagers();

                X509TrustManager[] tm = new X509TrustManager[] { new AdvancedX509TrustManager(trustStore) {

                    public void checkClientTrusted(X509Certificate[] chain, String authType) throws CertificateException {
                    }

                    public void checkServerTrusted(X509Certificate[] chain, String authType) throws CertificateException {
                    }

                    public X509Certificate[] getAcceptedIssuers() {
                        return chain;
                    }

                    public boolean isClientTrusted(X509Certificate[] arg0) {
                        return true;
                    }

                    public boolean isServerTrusted(X509Certificate[] arg0) {
                        return true;
                    }

                } };

                SSLContext sslContext = SSLContext.getInstance("TLS");
                sslContext.init(new KeyManager[] {keyManager}, tm, null);
                SSLContext.setDefault(sslContext);

                mHostnameVerifier = new BrowserCompatHostnameVerifier();
                mAdvancedSslSocketFactory = new AdvancedSslSocketFactory(sslContext, new AdvancedX509TrustManager(trustStore), mHostnameVerifier);

            } else {
                // can't recover the chain
                ...
            }
        }
        return mAdvancedSslSocketFactory;
    }
```

That's a big paste-up of various articles and posts that I've read to try to solve the problem... unfortunately I can't remember all of them:
[issue #163](https://github.com/owncloud/android/issues/163)
[kbremner](https://medium.com/@_kbremner/android-and-client-authentication-fd416af19a04)

Hope it helps.
Best wishes

**Comment by mario** [comment]
@mbrescia feel free to start a patch, and I can help? In the mean time, maybe you can try Nextcloud Talk v1.2.0beta? Same for you @AndreasMettlen ^_^

**Comment by mario** [comment]
@ClCfe can you file a bug here, preferably with stacktrace?

https://github.com/nextcloud/talk-android

**Comment by proton2b** [comment]
@mbrescia 
is there any chance that you upload your whole example, because i tried your workaround but without success.
best regards

**Comment by mbrescia** [comment]
@proton2b
Sure, I'll start a branch as soon as I can

**Comment by proton2b** [comment]
@mbrescia 
ok great, thanks in advance!

**Comment by carlos-sarmiento** [comment]
Has there been any update on this? It would be an excellent addition to security

**Comment by proton2b** [comment]
> Has there been any update on this? It would be an excellent addition to security

Unfortunately not.

**Comment by mirko** [comment]
I'm really interested as well. Actually I already setup the server and my desktop client that way and was kind of puzzled the Android app refused to work with client certificates.

**Comment by steffenfritz** [comment]
+1

**Comment by ben423423n32j14e** [comment]
I would also like to see client certificates supported in the nextcloud app.

**Comment by TJB-99** [comment]
+1

**Comment by mlsxlist** [comment]
Instead of adding +1 comments to this ticket please use the thumb up emoji at the top. Thanks.

**Comment by ben423423n32j14e** [comment]
I know its not directly related but can someone share an Apache config for Collabora to communicate with Nextcloud when SSLVerifyClient require is set in Apache?

I've got it set on both the NextCloud and Collabora sub domains, I can authenticate fine via the certificate to both subdomains but Collabora won't work.

**Comment by hostingnuggets** [comment]
@ben423423n32j14e please don't hijack issues like that, this is not a support forum. I recommend you first have a look at https://github.com/nextcloud/richdocuments if you can find any info.

**Comment by ben423423n32j14e** [comment]
I've found an alternative to certificate authentication for the Android app (but still keeping certificate authentication for the website and Collabora).

Basically I compiled my own version of the NextCloud Android app and replaced the http user agent with a really long random string.

If certificate authentication is not successful, an Apache re-write rule activates and if it can see the custom user agent from the app (being transmitted over https), it will allow bypassing the certificate authentication.

**Comment by razaborg** [comment]
@stephanritscher seems to have made a working patch. 
Why hasn't it been integrated yet ?

**Comment by rob2g2** [comment]
+1 vote for client cert auth from me! please!

**Comment by plai2010** [comment]
An alternative approach is to make NextCloud an OAuth2 client, then implement an OAuth2 authz/token endpoint that uses client cert for authentication. I am not sure if NextCloud can function as an OAuth2 client out-of-the-box, but there is already Google login, e.g. in [Social Login](https://apps.nextcloud.com/apps/sociallogin), so that is certainly possible.

Perhaps I should take a crack at this.

**Comment by razaborg** [comment]
> An alternative approach is to make NextCloud an OAuth2 client, then implement an OAuth2 authz/token endpoint that uses client cert for authentication. I am not sure if NextCloud can function as an OAuth2 client out-of-the-box, but there is already Google login, e.g. in [Social Login](https://apps.nextcloud.com/apps/sociallogin), so that is certainly possible.
> 
> Perhaps I should take a crack at this.

I am not sure to understand of the advantages of this method over just using the device certificate truststore through the Android API, just like web browser would do.

In my case (but I'm sure this would perfectly fit compagnies security needs too), the setup is the following : a web fronting reverse-proxy which authorize access to the nextcloud server only if the device present a valid client certificate. The goal behind all that is to avoid having an useless and huge attack surface fronting on the internet.

Thus, I am not sure to understand correctly the architecture of "NextCloud as an OAuth2 client", but if nextcloud has to be fronting on the internet, we probably miss the point.

**Comment by plai2010** [comment]
Configuring web server to require client certificate as an additional layer of security is fine. I thought however some installations wanted to use client cert only, without the regular username/password. Perhaps there is some well defined mechanism to bypass that; I am new to NextCloud so just unaware of such.

As for "NextCloud as an OAuth2 client", it can be confusing. I'm not talking about NextCloud as an OAuth2 client to access say Google Drive. Rather, NextCloud can leverage the OAuth2 authorization flow as a unified way to support arbitrary authentication mechanisms. Consider what happens when a NextCloud user logs in via Google:

1. NextCloud user clicks the "Google Login" button on the NextCloud login page.
2. Some Google controlled webflow is kicked off that authenticates the user with Google.
3. The webflow ends with a callback from Google to NextCloud with an authorization result. NextCloud verifies the authorization and lets the user in.

We can replace 'Google' above with 'My Special'. The 'My Special' webflow can be arbitrarily complicated -- it can do client cert, captcha, SMS code, etc., even combination of them. Core NextCloud is out of the loop and would not need additional development just to support new auth mechanisms.

**Comment by plai2010** [comment]
> ... without the regular username/password. Perhaps there is some well defined mechanism to bypass that; I am new to NextCloud so just unaware of such.

There is [SSO & SAML authentication](https://apps.nextcloud.com/apps/user_saml) that is relevant too. In particular it looks like any server environment variable based mechanism would work.

**Comment by strzinek** [comment]
This issue is a stopper for me. I need just a simple client cert validation on https level, independent of user authentication. Any plans to implement it?

**Comment by cp289** [comment]
If I understand correctly, implementing this feature in the [android-library repo](https://github.com/nextcloud/android-library) would be a more effective solution since it would add client certificate support to all Nextcloud apps using the library. There is an issue for this [here](https://github.com/nextcloud/android-library/issues/276).

**Comment by tdotu** [comment]
Is there any update on this issue? I would love to have client certificates on Android.
Due to the following issue thread, I assume the desktop client supports it: https://github.com/nextcloud/desktop/issues/1190
But I haven't tested it yet.

**Comment by morkol-dot** [comment]
Not sure if it helps anybody but client certificates work for me in 3.2.1.
However, what I found out is that as soon as I let my nginx Reverse Proxy send the HSTS headers (Strict-Transport-Security), I do get an error and Nextcloud is not connecting anymore. Not sure if this is intended (because HSTS is somehow redundant there) or a bug.

**Comment by mlsxlist** [comment]
> Not sure if it helps anybody but client certificates work for me in 3.2.1.

You probably talk about the desktop client. This ticket is about the Android client.

**Comment by tasmin** [comment]
Using cloudflare DNS with client cert required for protection, I really need to have the client cert requirement handled by the android app

**Comment by asphalter** [comment]
Just to recall the request for the client certificates support.

It's a request that was open since the Jan 29, 2017 but it hasn't been really considered yet, although it would be a considerable bump up in security for the Nextcloud services that can't be simply exposed to the Internet for internal policies.

**Comment by balaustrada** [comment]
Why is this feature not getting into nextcloud or even other apps like home assistant. It is because is hard to implement? or because people does not need it in general? I found mTLS a really simple and secure option for non-expert users...

**Comment by avocadio** [comment]
@stephanritscher - Thanks it worked - well worth the APK compilation time!!! 
There is one issue which may be due to my setup (mTLS internet facing/TLS internal) I just had to register internally, it was not working externally.  

The selection UI should really not been seen as a blocker if we consider the security value brought by this feature. 
Thanks again you made my day! 

@mario  Is there anyway to bring this to at least the 'dev' version?

**Comment by tobiasKaminsky** [comment]
> Is there anyway to bring this to at least the 'dev' version?

If you want to help us integrating this feature, then please create a PR both on this app and on library, so we can review and discuss it.

**Comment by peshovec** [comment]
> @stephanritscher - Thanks it worked - well worth the APK compilation time!!! There is one issue which may be due to my setup (mTLS internet facing/TLS internal) I just had to register internally, it was not working externally.
> 
> The selection UI should really not been seen as a blocker if we consider the security value brought by this feature. Thanks again you made my day!
> 
> @mario Is there anyway to bring this to at least the 'dev' version?

Initial registration fails to me too (after workaround and registering, connects fine). was able to investigate a little bit:
it is faulting here:
log from the nginx:
ocs/v2.php/cloud/user?format=json HTTP/2.0" 444 0 "-" "Mozilla/5.0 (Android) Nextcloud-android/20220921"

tried to dig further (logcat) and this seems as possible code place:

android-library/library/src/main/java/com/owncloud/android/lib/resources/user/GetUserInfoRemoteOperation.java

   public RemoteOperationResult<UserInfo> run(NextcloudClient client) {
        RemoteOperationResult<UserInfo> result;
        int status;
        GetMethod get = null;

        String url = client.getBaseUri() + OCS_ROUTE_SELF;

        // get the user
        try {

            get = new GetMethod(url, true);
            HashMap<String, String> map = new HashMap<>();
            map.put("format", "json");

            get.setQueryString(map);
            status = client.execute(get);

**Comment by Torqu3Wr3nch** [comment]
Looks like we have multiple commits from Stephan (thank you, by the way).

@stephanritscher can you please issue a PR so we can get this implemented in the official Nextcloud Android client? It sounds like @tobiasKaminsky is onboard. I can't think of a more vitally significant piece of development for the Nextcloud community. Security of a file storage/synchronization platform is always highest priority.

Thank you again for your work.

**Comment by stephanritscher** [comment]
> @stephanritscher can you please issue a PR so we can get this implemented in the official Nextcloud Android client?

I rebased my repos and created PRs https://github.com/nextcloud/android-library/pull/1005 and https://github.com/nextcloud/android/pull/11099 to start the discussion. I guess it might need some changes, but let's see.

Sorry, but I might not be able to respond/incorporate changes quickly due too lack of time.

**Comment by avocadio** [comment]
@AlvaroBrey in https://github.com/nextcloud/android/pull/11099 it was mentioned that there was an internal consensus, 
would you mind describing a bit more? I have a bit of spare time over the coming break and would like to understand what would be accepted?

Just for reference major open source application in the IoT world has used similar method:
https://github.com/home-assistant/android/pull/2023
Mattermost support this due to the use of react. 
Not to forget Talk (and that is working great!)

**Comment by bestrocker221** [comment]
Any news on the topic? Still not implemented but would be awesome to have!

**Comment by bestrocker221** [comment]
Any plan on adding it to release?

**Comment by AndyScherzinger** [comment]
It's planned to ship it with the next feature release 3.29 - scheduled for 24th April

**Comment by kaikli** [comment]
Maybe I'm just blind, but how can I specify a client certificate when signing in with the android app? Is this a hidden feature that is only enabled when a client certificate is required or how does it work?

I'm using 3.30.0 and when I add a new account, I only see two options to enter the url of the server. Enter it manually or scan the configuration with a qr code. After that a browser is opened to sign into nextcloud.

**Comment by Elv1zz** [comment]
> Maybe I'm just blind, but how can I specify a client certificate when signing in with the android app? Is this a hidden feature that is only enabled when a client certificate is required or how does it work?
> 
> When I add a new account, I only see two options to enter the url of the server, manually or scan the configuration with a qr code. After that a browser is opened to sign into nextcloud.

Yes, exactly. There is no direct way to configure the nextcloud connection, so especially no explicit selection of the certificate before trying to establish the connection. That's the way nexctloud connections are configured (so far). I personally prefer an explicit configuration, like e.g. DAVx uses it.
The (proxy) server has to request the client certificate for the HTTPS connection -- it can either be required or optional on the server side. However, at the moment a mixed operation of clients with and without client certificates does not seem to work.

**Comment by superamnesia** [comment]
The android app works as expected but iOS one doesn’t work. Have you already plan a release?
And for the desktop apps?

**Comment by tobiasKaminsky** [comment]
Please ask in the corresponding repositories for status.
