### ISSUE TITLE
color problem with darkmode

### ISSUE THREAD

**Issue by fm-sys** [nextcloud/android#6034]
When the App is in Darkmode, text styled as Codeblocks in the readmefile is white colored so you can't see it...

![2020-05-09 13_46_38-Dateien - Nextcloud](https://user-images.githubusercontent.com/64581222/81473163-02537a00-91fd-11ea-9465-97884c5530d5.png)

![Screenshot_20200509_133546](https://user-images.githubusercontent.com/64581222/81472737-5577fd80-91fa-11ea-9b03-e236aaed0b39.jpg)

### Environment data
Android version:
Android 10

Device model: 
Huawei SNE-LX1

Stock or customized system:
EMUI 10.0.0

Nextcloud app version:
3.11.1

Nextcloud server version:
18.0

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger maybe? ❤️

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky no idea, does this come from the server or is it styled on the client-side?

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger this is our local markdown viewer.
There seems to be a different between preview and full view:

![2020-05-12-170958](https://user-images.githubusercontent.com/5836855/81710918-6f704500-9473-11ea-9c52-fc621d8618bb.png) ![2020-05-12-171001](https://user-images.githubusercontent.com/5836855/81710905-6da68180-9473-11ea-8150-f9c9584751de.png)

**Comment by tobiasKaminsky** [comment]
OCFileList: https://github.com/nextcloud/android/blob/60d7f2c41791b3f81016379a01670303a7e12f7c/src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java#L340-L355

PreviewTextStringFragment:
https://github.com/nextcloud/android/blob/4eec8905ae144285babbfaf86424374b421e8565/src/main/java/com/owncloud/android/ui/preview/PreviewTextStringFragment.java#L152-L156

**Comment by tobiasKaminsky** [comment]
So issue seem to be the shader.
Commenting L355 shows the text:

![2020-05-12-171420](https://user-images.githubusercontent.com/5836855/81711496-076e2e80-9474-11ea-9a4d-8e022b2031e8.png)

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky maybe we can try something like this:

```
Shader shader = new LinearGradient(0,
                                               headerViewHolder.headerText.getHeight()-20,
                                               0,
                                               headerViewHolder.headerText.getHeight() - 100,
                                               0,
                                               0xFF000000,
                                               Shader.TileMode.CLAMP
            );

            headerViewHolder.headerText.getPaint().setXfermode(new PorterDuffXfermode(PorterDuff.Mode.DST_OUT));
            headerViewHolder.headerText.getPaint().setShader(shader);
```

**Comment by tobiasKaminsky** [comment]
Not working for me.
It seems also to be a problem on light color.
Text is:
```
\```
implementation "io.noties.markwon:core:${markwonVersion}"
\```
```

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger do you have time to take another look?
If not, we need to remove the shader… :/

**Comment by AndyScherzinger** [comment]
Will open a PR any minute

**Comment by AndyScherzinger** [comment]
PR is #6222
