### ISSUE TITLE
Daily contacts backup didn't work at 3.12.0 rc1

### ISSUE THREAD

**Issue by Siggi0904** [nextcloud/android#6041]
Hi,

looks like that daily contacts backup didn't work at 3.12.0 rc1.
Manually backup works fine, daily backup not.

Thanks for checking, confirmation and fixing.

**Comment by AndyScherzinger** [comment]
Pinging @tobiasKaminsky and @ezaquarii

**Comment by tobiasKaminsky** [comment]
As you on RC1, you should be able to see settings -> Engineering Test Mode?
Can you then go to background jobs and see if "periodic_contacts_backup" is scheduled?

**Comment by Siggi0904** [comment]
Hi, I got rC1 from google play but there is no Engineering testing mode.
I only have the logs there. And there I cannot find any string like "periodic".

Is this a hidden menu like dev mode in google apps?
Like tap 5 times at version number or so?

**Comment by ezaquarii** [comment]
On Tue, May 12, 2020 at 09:06:12AM -0700, Mario Siegmann wrote:
> I only have the logs there. And there I cannot find any string like "periodic".
> Is this a hidden menu like dev mode in google apps?

@tobiasKaminsky - if this version is published in Google Play, entire dev category
is disabled in Settings activity and ETM won't be availabe.

> Like tap 5 times at version number or so?

Unfortuantely it's compile-time option, but maybe we should
implement some sort of secret cheat code?

**Comment by ezaquarii** [comment]
@tobiasKaminsky Running ETM from adb shell could be an option. This is not possible atm.

**Comment by Siggi0904** [comment]
I can confirm that since 3.12 rc1 these contact backup didn't work.
If there is any option that I con do to fix that problem, let me know.

**Comment by Siggi0904** [comment]
Hi, still not working with RC2.
Thanks for helping or fixing the app.

**Comment by ezaquarii** [comment]
@tobiasKaminsky is 1c7430367d530630d587e2b5c6000e0716ec399d in RC2?

**Comment by AndyScherzinger** [comment]
@ezaquarii according to https://github.com/nextcloud/android/compare/rc-3.12.0-02...stable-3.12 it should be in RC2, yes (backport PR is #6079

**Comment by Siggi0904** [comment]
Reinstalled the app comletely, same issue.

Second point that nc deletes sync folder at deinstalling android app.
Quite not nice.

**Comment by ezaquarii** [comment]
I can confirm the issue. I checked the code and it looks like the period is set to `86400000` (24h in milliseconds).

The problem is that the input expects time in minutes, so the backup period is 1440000 hours, or ~164 years.

[Even NASA makes such mistakes](https://en.wikipedia.org/wiki/Mars_Climate_Orbiter), so no heated blames please.
