### ISSUE TITLE
Auto-upload view not seeing new files in *one* directory

### ISSUE THREAD

**Issue by adrien-n** [nextcloud/android#6045]
I use auto-upload for two kind of files: photos and videos. Photos get uploaded fine but not videos. I don't upload the videos I take from my phone but instead I transcode them on the phone before uploading them and the new files end up in a different directory named Movies. As far as I can tell, auto-upload is configured the same for every directory.

Some files from Movies have been uploaded but now the files there are not uploaded anymore and, more interestingly, nor the filecount in the auto-upload view nor the thumbnails change anymore. I've tried Clear Cache in Android; the app had to refresh the configuration view and thumbnails but still no update.

Is something like this already known? Anything to do to help with debugging?

### Environment data
Android version: 9

Device model: Oneplus 3T

Stock or customized system: stock

Nextcloud app version: 3.11.1

Nextcloud server version: latest

**Comment by tobiasKaminsky** [comment]
The app relies on the media scanner, so when creating an image/movie the other app has to register the file in the media scanner. Then you can also see it in default gallery.
I suspect that the other transcode app is not doing this/not all the time.

As a workaround you could set up a custom folder for "Movies", then every file in it is uploaded.

**Comment by tobiasKaminsky** [comment]
> Is it technically doable that nextcloud force refreshes the media database upon user request?

Could be, but same with every other option we try to have as little manual interactions/options as possible.
So if the problem is battery saver on Oxygen OS, then please exclude the app from it.
