### ISSUE TITLE
Can't access nexcloud on domain name in local with ipv6

### ISSUE THREAD

**Issue by HugoPourrierNunez** [nextcloud/android#6049]
### Steps to reproduce
1. Be on your local network wifi where you host your private server
2. Have a ddns with only ipv6 redirection configure (mine is duck dns)
3. Try to log in the app -> didn't work (failed to respond)
4. Try to log from a browser on the phone -> success

### Expected behaviour
- The app login should have the same behavior as the browser

### Actual behaviour
- The nextcloud app doesn't work in local but other app using nextcloud, like "FolderSync" works well in local.

Android version: 9

Device model: Huawei P20 Pro and Samsung S10e

Stock or customized system: Stock

Nextcloud app version: 3.12.0 RC1 (or 3.11.1, same result)

Nextcloud server version: 18.0.4.2

#### Nextcloud log (data/nextcloud.log)
There is no specific log to this issue in nexcloud.log

**Comment by HugoPourrierNunez** [comment]
I have these logs in with logcat when I tried to connect : 

05-12 12:00:31.533: D/hw_netstat(1148): total/3196/837,com.nextcloud.client/3112/785,unknown:1051/84/0,android.uid.system:1000/0/52

05-12 12:00:35.432: D/HwWifiConnectivityMonitor(1148): ENTER: notifyTopUidTcpInfo, rtt = 632, rttPkts = 6, aveRtt = 105.333336, app = com.nextcloud.client

05-12 12:00:35.433: D/HwUidTcpMonitor(1148): parseWlanUidTcpStatistics newUidTcpStatInfo = [ mUid = 10145 mPacketName = com.nextcloud.client mSendSegs = 11 mResendSegs = 0 mRcvSegs = 11 ]

05-12 12:00:41.567: D/hw_netstat(1148): total/2424/4672,com.nextcloud.client/2182/4428,com.google.uid.shared:10112/0/244,unknown:1020/122/0,unknown:0/120/0

05-12 12:00:43.437: D/HwWifiConnectivityMonitor(1148): ENTER: notifyTopUidTcpInfo, rtt = 232, rttPkts = 10, aveRtt = 23.2, app = com.nextcloud.client

05-12 12:00:43.438: D/HwUidTcpMonitor(1148): parseWlanUidTcpStatistics lastUidTcpStatInfo = [ mUid = 10145 mPacketName = com.nextcloud.client mSendSegs = 26 mResendSegs = 0 mRcvSegs = 27 ]

**Comment by tobiasKaminsky** [comment]
What do yo umean with local?
Your local ip? Within your local IP?

**Comment by HugoPourrierNunez** [comment]
I'm just on the same local network as the server, I want to access to my server with his domain name , the domain name resolver only return ipv6 in my configuration and the android app doesn't support it (I can't even log in) while it perfectly works on chrome on my phone.

**Comment by Guigui37** [comment]
Same thing here, working in ipv6 using browser, but not with android app.
Note that an other android app NC Talk works in IPv6, but not others like Notes, Deck, News.
Tried rebooting phone, still not working.

**Comment by ThomasVialars** [comment]
Same error here.

I have my server on an ipv6 address.
I can access it with my computer with my domain name, with my phone with the browser app with my domain but not with the nextcloud app with the domain name.
