### ISSUE TITLE
FAB is missing when entering folder

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#6053]
### Steps to reproduce
1. see FAB
2. scroll until FAB vanishes
3. click on folder to enter subfolder
4. do not see FAB

### Expected behaviour
FAB should be shown when entering a new suboflder

### Actual behaviour
No FAB

@JorisBodin can you have a look into this? 💙

**Comment by JorisBodin** [comment]
@tobiasKaminsky same problem https://stackoverflow.com/questions/61735814/android-fab-hidebottomviewonscrollbehavior-statys-hidden-after-changing-fragment
Maybe a bug of google lib? 🤷‍♀️

I check this...

**Comment by JorisBodin** [comment]
@tobiasKaminsky I found :D
https://stackoverflow.com/a/61753254/2389197

I fix it
