### ISSUE TITLE
Remove sort and grid view in top right menu

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#6059]
Btw @JorisBodin, now the "Sort" and "Grid view" entries in the 3-dot menu on the top right can be removed, right?

_Originally posted by @jancborchardt in https://github.com/nextcloud/android/pull/5992#issuecomment-627347765_

**Comment by tobiasKaminsky** [comment]
This would leave "refresh account" as only remaining item.
I am unsure if we need this?

This is triggered:
https://github.com/nextcloud/android/blob/207846ebeab22648728326041b0170ad900e9ada/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java#L899

**Comment by jancborchardt** [comment]
> This would leave "refresh account" as only remaining item.
> I am unsure if we need this?

This should be triggered anyway by a pull to refresh in the root folder, so yes please we can remove it. :)

**Comment by JorisBodin** [comment]
And for "refresh account", the "swipe down" use for that :)

**Comment by Shagequi** [comment]
Watching for this now :)

**Comment by AndyScherzinger** [comment]
Well, this is broken for the local file list.
Just try to upload files via the fab button and check sorting as well as list/grid (also broken for the menu)

**Comment by JorisBodin** [comment]
> (also broken for the menu)

Normal it uses the same method :P
It must be the case in stable.

**Comment by tobiasKaminsky** [comment]
Should be fixed already.
