### ISSUE TITLE
The left side menu in dark mode has the wrong grey tone

### ISSUE THREAD

**Issue by szaimen** [nextcloud/android#6066]
### Steps to reproduce
1. Activate the dark mode
2. Open side menu
3. See wrong grey tone. (It is brighter than all other used grey tones.)

### Expected behaviour
- should use the same grey tone like on other places

### Actual behaviour
- the grey tone is wrong

### Environment data
Android version:
10
Device model: 
Samsung Galaxy S10e
Stock or customized system:
Stock
Nextcloud app version:
3.12 RC1
Nextcloud server version:
18.0.4
Reverse proxy:
No

### Here a screenshot:
![20200513_162803](https://user-images.githubusercontent.com/42591237/81825291-c25f0080-9536-11ea-90f0-03e8fa692ddb.png)

**Comment by AndyScherzinger** [comment]
Cc @JorisBodin @dan0xii @Shagequi @sirambd

**Comment by JorisBodin** [comment]
@jancborchardt what color would you like?
I find this color here

**Comment by szaimen** [comment]
I mean it had the same background color like this before and it looked nicer, imo.
![20200514_112252](https://user-images.githubusercontent.com/42591237/81917312-54b5e180-95d5-11ea-8140-2c8e07c6c52e.png)

**Comment by JorisBodin** [comment]
> I mean it had the same background color like this before and it looked nicer, imo.
> ![20200514_112252](https://user-images.githubusercontent.com/42591237/81917312-54b5e180-95d5-11ea-8140-2c8e07c6c52e.png)

I think it's too dark.
The color must be the same as the appbar. Which is lighter than the background.

**Comment by szaimen** [comment]
> I think it's too dark.
> The color must be the same as the appbar. Which is lighter than the background.

The thing is, that it was darker before version 3.12 RC1 if I remember correctly.
Otherwise I would probably not have seen it.

Imo it looks better with a darker grey. Especially becaue the quota bar on the bottom has a darker background.

Also why are the appbar and the side menu not allowed to have a different grey tones to it? I see no problem with that... (the mockup isn't showing the dark mode, afaik)

**Comment by AndyScherzinger** [comment]
> I think it's too dark.

I checked Google GMail/Play/Drive and in Darkmode they all use the background coor of the "main view" for the drawer menu also, so it would need to be dark(er).Other than that they also don't use White for font/icon in the drawer menu but grey-ish

**Comment by AndyScherzinger** [comment]
![device-2020-05-14-113931](https://user-images.githubusercontent.com/1315170/81919059-9d6e9a00-95d7-11ea-85bc-bfd6ae05c3bf.png)

**Comment by JorisBodin** [comment]
@AndyScherzinger Yes but the background is not black. If we have black background, the appbar and drawermenu is grey.

**Comment by szaimen** [comment]
> @AndyScherzinger Yes but the background is not black. If we have black background, the appbar and drawermenu is grey.

But the background is not black but a dark grey...

**Comment by Shagequi** [comment]
Hey,

I like the issue number, that's almost the number of the beast 😂 

About this problem, I'll watch what I can do... but  to be very honest, this grey doesn't shock me, and allows to see the difference with the background (in dark mode) where the files are present... so I'd say it's rather a good thing. 

But I'm going to present you with samples so we can see which one is more interesting

**Comment by tobiasKaminsky** [comment]
If you ever change this, please make sure to test it with edge cases…
light yellow
dark purple
black
white

all in normal and dark mode :-)

**Comment by szaimen** [comment]
@Shagequi I've tested the latest PR #6156
It seems like the text in the drawer on dark mode is a bit darker now and I still think that making the background color of the drawer the same like the background color of the main view looks better:
Currently | Proposed
------------ | -------------
![image](https://user-images.githubusercontent.com/42591237/83037138-bb0e1b80-a03b-11ea-9f27-4acaafdf3172.png) | ![image](https://user-images.githubusercontent.com/42591237/83036991-87cb8c80-a03b-11ea-9423-c8daa4cdef3f.png)

**Comment by Shagequi** [comment]
@szaimen 

I'm more of an enforcer than a decision-maker, awaiting @jancborchardt for approval.
It would take ... two lines, to apply the change :)

**Comment by JorisBodin** [comment]
@szaimen The menu must be in a lighter color than the background. Like account dialog.
![Screenshot_1590596172](https://user-images.githubusercontent.com/2796439/83045896-86ec2800-a046-11ea-964d-24845aeb4e7f.png)

**Comment by szaimen** [comment]
> @szaimen The menu must be in a lighter color than the background.

@JorisBodin Yes, you already said that. But why?

**Comment by JorisBodin** [comment]
Do you prefer 1 or 2?
|1|2|
|---|---|
|![Screenshot_1590596937](https://user-images.githubusercontent.com/2796439/83046988-0c240c80-a048-11ea-9114-affb88fefa98.png)|![dark](https://user-images.githubusercontent.com/2796439/82461139-5e01eb00-9aba-11ea-986a-c61abe015719.gif)|

For me, the background is to dark for use it in drawer and dialog

**Comment by szaimen** [comment]
@JorisBodin Thanks for showing an example.
If possible, I would just change the background color of the drawer but leave the background color of the dialog as it currently is.

**Comment by szaimen** [comment]
It would also be comparable to e.g. the play store, since google uses different colors for the drawer and the dialog as well:
Drawer (same background color as main background) | Dialog (a brighter grey tone background color)
------------ | -------------
![image](https://user-images.githubusercontent.com/42591237/83049120-f5cb8000-a04a-11ea-8b49-cad568efe6cc.png) | ![image](https://user-images.githubusercontent.com/42591237/83049132-fbc16100-a04a-11ea-87d2-5b39128ac920.png)

**Comment by JorisBodin** [comment]
> Drawer (same background color as main background)

Yes but the background color is lighter than nextcloud

**Comment by szaimen** [comment]
@JorisBodin it seems that we don't come to an agreement here.
What is @jancborchardt's opinion on that? (making only the drawer the same grey tone like the background color)

**Comment by AndyScherzinger** [comment]
afaik the decision has been reached to use the toolbar color which reflects the correct elevation.

**Comment by AndyScherzinger** [comment]
fixed as discussed with designers shipping with 3.13
