### ISSUE TITLE
Can't use Custom DNS

### ISSUE THREAD

**Issue by superzanti** [nextcloud/android#6069]
### Steps to reproduce
1. Register a domain name that points to the WAN IP address of your network (ex: myhomepage.com)
2. Setup nextcloud so that it works using this domain name
3. Setup a DNS such as PiHole
4. Add a Custom DN in PiHole for the homepage so that local devices use the local IP instead of the WAN IP (ex: myhomepage.com -> 192.168.1.50)
5. Add account for myhomepage.com in the nextcloud android app (this fails, it works in the desktop app)
6. Add account for 192.168.1.50 (this succeeds)

### Expected behaviour
- If myhomepage.com is a registered domain, that points to my WAN IP address, then the app works as expected. However, I was hoping to have anything on the internal network use the internal IP to speed up transfers.

- I would expect myhomepage.com to work even if the IP points to a local IP. This tells me that the android app must be going off network when I use a domain name. This makes me uncomfortable.

### Actual behaviour
- The Nextcloud app fails to connect to myhomepage.com when myhomepage.com is paointing on a local IP

### Environment data
Android version: 10

Device model: Google Pixel 2 XL

Stock or customized system: Stock

Nextcloud app version: 3.11.1

Nextcloud server version: 18.04

**Comment by tobiasKaminsky** [comment]
What is the error?

**Comment by superzanti** [comment]
![error](https://user-images.githubusercontent.com/4262089/81980537-07913a00-95ec-11ea-86b8-d611741ab319.png)

The weird thing is, it works perfectly fine in the desktop app.
