### ISSUE TITLE
Auto-upload pauses when app is not in focus

### ISSUE THREAD

**Issue by JinHadah** [nextcloud/android#6071]
### Steps to reproduce
1. Open nextcloud and designate folders for auto-upload
2. Switch to upload pane and watch the progress
3. Switch to a different app or return to your home screen.

### Expected behaviour
- Tell us what should happen
Uploads should continue until done
### Actual behaviour
- Tell us what happens
Uploads stop until you return to the app
### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

Behavior persists on demo server

### Environment data
Android version:
10
Device model: 
SM-G965U1
Stock or customized system:
Stock
Nextcloud app version:
3.11.1
Nextcloud server version:
18.0.4.2
Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Do you have any battery optimization enabled?
I suspect that Samsung is force closing the app when in background.

**Comment by JinHadah** [comment]
When turning on auto-update, one is prompted to disable power optimization for the app. I chose the disable option. However, when I checked the app whitelist just to be sure, nextcloud wasn't listed. In fact, when I tried to add it to the whitelist, it wasn't even smoke the options. Instead, I disabled app sleeping all together, but the problem still persists.

On May 14, 2020 3:58:48 AM AKDT, Tobias Kaminsky <notifications@github.com> wrote:
>Do you have any battery optimization enabled?
>I suspect that Samsung is force closing the app when in background.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nextcloud/android/issues/6071#issuecomment-628586269

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Gr3ytooth** [comment]
I have exactly the same issue on a Sony XZ1 Compact and a Sony XZ2 Compact. On both the battery optimization has been disabled.
It's extremely annoying as for me the auto upload is one of the mayor reasons I set up Nextcloud on my server and mobiles. 
If you want any logs or assistance let me know and I will what I can do.

**Comment by ezaquarii** [comment]
@tobiasKaminsky This user uses 3.11. I believe the fix for stalled uploads is going into 3.12, no?

**Comment by ezaquarii** [comment]
Fixed here https://github.com/nextcloud/android-library/pull/424

**Comment by ezaquarii** [comment]
@JinHadah @Gr3ytooth You can try our dev build to see if this problem goes away. New 3.12 with lots of fixes is coming soon.

**Comment by JinHadah** [comment]
I've downloaded the 3.12 RC and it seems to have resolved the issue. Thanks for the advice
