### ISSUE TITLE
HTTP error / code 401

### ISSUE THREAD

**Issue by 007fred50** [nextcloud/android#6084]
I got the error below

Then i try to setup a nextcloud server.

![Screenshot_20200515-151017](https://user-images.githubusercontent.com/25218874/82054050-a25a4900-96be-11ea-8379-2b041a828a37.png)

Thanks for your time !

**Comment by 007fred50** [comment]
http://people8people.com:8080/nextcloud
Demo user !

User: demo
Pass: MacBookProUbuntu

Error in Android and IOS
But i can get it work inside web browser !

Thanks for your time !

**Comment by 007fred50** [comment]
error in ubuntu software / nextcloud

![nextcloud_error](https://user-images.githubusercontent.com/25218874/82057407-94f38d80-96c3-11ea-8cc1-c2fcd6d09462.png)

**Comment by 007fred50** [comment]
I works in browser on my phone. but not in both app with IOS and Android

**Comment by 007fred50** [comment]
It works inside VirtualBox with nextcloud inside. Maybe i think it's my apache2 server.

**Comment by AndyScherzinger** [comment]
@007fred50 just checking since this is the number one configuration issue on the server side, did you set this in your config fin´le?

'overwriteprotocol' => 'https',

see https://docs.nextcloud.com/server/18/admin_manual/configuration_server/reverse_proxy_configuration.html#overwrite-parameters

**Comment by 007fred50** [comment]
Here is my config.php:

```
<?php
$CONFIG = array (
  'instanceid' => 'ocnpw36p83gr',
  'passwordsalt' => 'shWmQA/ndzKTmwrhA4wCNilnLazSod',
  'secret' => 'Wqy9C/NainlV/O9G+U5Sju2l3bh6KxM59Enliy0Apdrb+aSU',
  'trusted_domains' => 
  array (
    0 => 'people8people.com:8080',
  ),
  'datadirectory' => '/media/disk8tb1/www/nextcloud/data',
  'dbtype' => 'mysql',
  'version' => '18.0.4.2',
  'overwrite.cli.url' => 'http://people8people.com:8080/nextcloud',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'oc_nextcloud1',
  'dbpassword' => '+i9bSrPCc0pGXu94wRAwUKAa+W6KCb',
  'installed' => true,
);
```

i just add ('overwriteprotocol' => 'https',)

**Comment by 007fred50** [comment]
Here is my apache2 config.

```
<VirtualHost *:80>
    ServerName people8people.com
    DocumentRoot /media/disk8tb1/www
    <Directory /media/disk8tb1/www>
        Options -Indexes +FollowSymLinks +MultiViews
        AllowOverride All
        Require all granted
    </Directory>
    <FilesMatch \.php$>
        SetHandler "proxy:unix:/var/run/php/php7.4-fpm.sock|fcgi://localhost"
    </FilesMatch>
</VirtualHost>
```

i just add (RewriteEngine On) ?

**Comment by 007fred50** [comment]
I added (RewriteEngine on) inside my apache2 (sites-available/***.conf)
And run this command (sudo a2enmod rewrite)

After restart (sudo service apache2 restart)


it works for me thanks

**Comment by 007fred50** [comment]
i remove the demo user.

**Comment by AndyScherzinger** [comment]
So it is working for you now?

**Comment by 007fred50** [comment]
yes Thanks.
