### ISSUE TITLE
Version 3.11.1 on Android 10: Foto refresh is raising php-fpm: pool www to 1,8 GB, 

### ISSUE THREAD

**Issue by apg1980** [nextcloud/android#6085]
Hello together,

i am using latest Nextcloud 18.04 on Ubuntu 18.04 with postgresql and apache2 with php 7.3.
On my androind device "Huawei Mate 20 Pro - Android 10" i am using Nextcloud Android APP 3.11.1.

While refreshing the Foto section, the circle is running for a minute and the left with no found content.

Exactly ant the time i am executing the Foto refresh, seversidely the php-fpm: pool www process is imediately growing up to 1,8 gb and a lot of cpu time for postgresql and the fpm process is consuming.

### Steps to reproduce
1. Open Android app with a user that has a lot of images (my own with 400gb) 
2.  Goto Fotos
3.  Refresh

### Expected behaviour
Image Previews are displayed

### Actual behaviour
No Images are displayed, high ram usage of php-fom: pool www process (1,8GB).

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 10

Device model: Huawei Mate 20 Pro

Stock or customized system: Stock

Nextcloud app version: 3.11.1

Nextcloud server version: 18.04

Reverse proxy: Sophos UTM 9.7

#### Web server error log
No Error Logs

#### Nextcloud log (data/nextcloud.log)
No Error Logs

**Comment by tobiasKaminsky** [comment]
This is related to https://github.com/nextcloud/server/issues/20839
But this is a server problem…
Android is just querying, and this should not drive the server crazy.
(therefore closing it)
