### ISSUE TITLE
Abdroit App Crashes

### ISSUE THREAD

**Issue by n35k3nd1r** [nextcloud/android#6095]
### Steps to reproduce
1. Start App 
2. Wait
3. Error

### Expected behaviour
- App starts GUI

### Actual behaviour
- App don't Open GUI, but Upload in background runs.

Problem is only in this devive. 

Stock or customized system: 
Hetzner Storage Share

************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.db.OCUpload.getAccountName()' on a null object reference
	at com.owncloud.android.files.services.FileUploader.retryFailedUploads(FileUploader.java:1020)
	at com.owncloud.android.utils.FilesSyncHelper.lambda$restartJobsIfNeeded$0(FilesSyncHelper.java:232)
	at com.owncloud.android.utils.-$$Lambda$FilesSyncHelper$fa2LBpPOxRVQOm4F_Glue5u4hdM.run(Unknown Source:10)
	at java.lang.Thread.run(Thread.java:764)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30110190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: a5y17lte
Model: SM-A520F
Id: R16NW
Product: a5y17ltexx

************ FIRMWARE ************
SDK: 26
Release: 8.0.0
Incremental: A520FXXUDCTB1

**Comment by ezaquarii** [comment]
@tobiasKaminsky There is potentially null value in the array caused by array index mishandling. This is only the case in 3.11, as later `array[index] = ...` has been replaced by `List.add`.

@n35k3nd1r  you can try 3.12 release candidate. This issue should be solved in the upcoming version.
