### ISSUE TITLE
Autoupload includes incomplete downloads

### ISSUE THREAD

**Issue by Keepco** [nextcloud/android#611]
### Actual behaviour
The autoupload  function includes temporary download files generated by chrome with the file extension `.crdownload`

### Expected behaviour
Nextcloud should ignore files with the `.crdownload` file extension
 
### Steps to reproduce
1. Enable autoupload for a directory to which chrome downloads files
3. Download a picture via chrome

### Environment data
Android version:
7.0

Device model: 
Moto Z (XT1650)

Stock or customized system:
Stock

Nextcloud app version:
1.4.1

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky @mario can you take over this issue? My 2 cents would be to just exclude any "hidden" files as in ignore any .* files.

**Comment by mario** [comment]
@AndyScherzinger but what if I want my dot configuration files included? :) Let me think about this!

**Comment by mario** [comment]
We are currently going to exclude all DOT files just like @AndyScherzinger suggested. Thank you for this bug report.

**Comment by tobiasKaminsky** [comment]
Fine for me.
If too many users want to sync their hidden files, we will have to think about it again.

**Comment by AndyScherzinger** [comment]
@mario why is this issue closed? At this moment we do not exclude all DOT files, so we need an issue and a code change for that, also since it got reported here: https://help.nextcloud.com/t/android-client-instant-uploading-exo-etc-files-when-i-told-it-not-to/8394

**Comment by mario** [comment]
@AndyScherzinger @tobiasKaminsky closed it I guess? :) But there's a code change in my PR for that :)

**Comment by AndyScherzinger** [comment]
And that one excludes all "hidden files" ?

**Comment by mario** [comment]
It excludes DOT files, yes.
