### ISSUE TITLE
Auto-upload (and likely more) Dark mode color issues

### ISSUE THREAD

**Issue by NukeManDan** [nextcloud/android#6115]
### Steps to reproduce
1.  Turn on Dark mode in settings for the android app
2.  Navigate to auto upload
3.  Look for cloud (indicating it is syncing) for each subfolder (top right) - it's black, like the background - I can only distinguish with way way high contrast.

![Screenshot_20200519-190509](https://user-images.githubusercontent.com/35669742/82393830-ba0a3800-9a04-11ea-8a5c-715e53dfca2e.png)

---

Also the configuration window, when selecting a file, the bottom two buttons (cancel, save?) are illegible. 

![Screenshot_20200519-190551](https://user-images.githubusercontent.com/35669742/82393841-bd9dbf00-9a04-11ea-8a10-1923713bf97c.png)

### Expected behaviour
I should be able to read all text and icons

### Actual behaviour
- Tell us what happens
Can't see a thing

### Environment data
Android version:
8.1.0

Device model: 
CUBOT King Kong 3

Stock or customized system:
Server: Stock with OPENOFFICE using scripts from the VM here: https://github.com/nextcloud/vm
Android: stock

Nextcloud app version:

Nextcloud server version:

Reverse proxy:
none

**Comment by AndyScherzinger** [comment]
Thanks for the report, this happens on latest master too. The issue is dark theme + black being the primary color. This needs to be handled by the app 👍
