### ISSUE TITLE
First Run not fullscreen / fully blue

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#6118]
- Start app
- see
![2020-05-20-172454](https://user-images.githubusercontent.com/5836855/82464927-f13d1f80-9abe-11ea-9012-d5567fa6959b.png)

--> the lower navigation bar should not be shown
@JorisBodin maybe? 💙

**Comment by tobiasKaminsky** [comment]
![2020-05-20-172833](https://user-images.githubusercontent.com/5836855/82465229-5729a700-9abf-11ea-8ba8-ca57eb5e8b5a.png)

same here

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky looknig at the screenshots, why is the systembar dark again? We changed that a while ago so the system uses the primary color not the secondary.

**Comment by JorisBodin** [comment]
Currently the version on googleplay is like this:
![Screenshot_20200525-190704_Nextcloud](https://user-images.githubusercontent.com/2796439/82832403-40b68d80-9ebb-11ea-9a4b-b55d9039ff94.jpg)

Because before the color wasn't customized.
@jancborchardt What do we do now?

**Comment by jancborchardt** [comment]
The status bar should be Nextcloud blue background with white icons. And if possible, the navigation bar on the bottom should be the same. Just like the splash screen, much nicer:
![Screenshot_20200525-211412_Nextcloud_dev](https://user-images.githubusercontent.com/925062/82838533-cf7fd600-9ecc-11ea-87c8-38e950f408a7.png)
