### ISSUE TITLE
Loading complete resets layout / cancels search

### ISSUE THREAD

**Issue by pilsnerbeer** [nextcloud/android#6126]
situation: you're trying to search for a file in your cloud instance.
### Steps to reproduce
1. Open up the app, click Search (top right) while contents are  still loading (there will be a loading bar visible on top indicating the app is loading)
2. Start typing file name ..
3. The search layout will close on you as soon as the background loading process is complete.

### notes
Let me search for the file and don't close the search bar / keyboard. This becomes more annoying as time progresses, leaving no option then to let the app load the list and then proceed with searching.

### Environment data
Android version: 9

Device model: 

Stock or customized system:

Nextcloud app version: 3,11,1

**Comment by joshtrichards** [comment]
This appears to be fixed. As the original reporter can you confirm?
