### ISSUE TITLE
Can not add folders to auto upload (like my app data backup folder)

### ISSUE THREAD

**Issue by fredddii** [nextcloud/android#613]
Not much to explain really. I backup certain application data with oandbackup and it ends up in a directory called oandbackup.

I would like to add this as an auto upload folder to keep my backups backed up on Nextcloud.

Using Nextcloud 1.4.1 on Android 7.1.1.

![r0wr8vk](https://cloud.githubusercontent.com/assets/15217150/22527689/61cee6b0-e8d0-11e6-81d7-2ae827a5c4e1.png)

**Comment by mario** [comment]
After looking into everything, this feature is not there on purpose - we first have to make sure auto upload works for regular images/videos taken, and after that we'll implement this request of yours!

Thanks for taking the time to write a bug report!

**Comment by tobiasKaminsky** [comment]
There is a (long-term) roadmap for AutoUpload/sync: #285 
And there we already included this idea.
