### ISSUE TITLE
Instant Upload not uploading files in Downloads folder

### ISSUE THREAD

**Issue by jdaviescoates** [nextcloud/android#6130]
### Steps to reproduce
1. Get promoted my android to clear up space.
2. Notice video and other files in Downloads folder have not auto uploaded to Instant Upload folders
3. Wonder why not

### Expected behaviour
- Everything in my Downloads folder should be auto uploaded

### Actual behaviour
- I don't think anything in that folder is getting uploaded

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

I don't see how I can test this there given the issue is with the Android app

### Environment data
Android version:
8.1.0
Device model: 
Wileyfox Swift 2 Plus
Stock or customized system:

Nextcloud app version:
3.11.1
Nextcloud server version:
18.0.4

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
@jdaviescoates did you add the download folder in the auto upload screen of the app?

**Comment by AndyScherzinger** [comment]
> Everything in my Downloads folder should be auto uploaded

That is not an expected behavior btw (at least not if you haven't explicitly configured the app to do so)

**Comment by jdaviescoates** [comment]
Yes the Download folder is configured to auto upload in the Auto upload settings

![Screenshot_20200522-151210](https://user-images.githubusercontent.com/2113743/82676828-e9a48480-9c3e-11ea-9f26-e25ce4dededc.png)

The video which that first visible thumbnail represents has not been uploaded

Here is how it's configured:

![Screenshot_20200522-151222](https://user-images.githubusercontent.com/2113743/82676925-15276f00-9c3f-11ea-9379-071005b960f1.png)

I've tried turning the folder on/ off and on again, but that doesn't seem to do anything.

**Comment by jdaviescoates** [comment]
Just to add, I just tried downloading an image and that did Auto upload.  So perhaps this issue is just related to video?

(off topic: I'd actually like all files in that folder to Auto upload, including PDF files etc - but I think I'm correct in that at present it's only images and video that auto upload, right?)

**Comment by jdaviescoates** [comment]
Hmz, and I just downloaded another video too, but [a short one](https://files.uniteddiversity.coop/Can%20Flatpack%20Democracy%20save%20post%20pandemic%20Britain%20Radio4%20interview%20with%20Peter%20Macfadyen%20coming%20soon.mp4), and that uploaded fine too...

So really just trying to work out why that longer video in that folder (as seen in the thumbnail above) has not/ is not uploading...

**Comment by jdaviescoates** [comment]
OK, so I think it is because I downloaded it using https://download.uniteddiversity.coop/ (my install of https://github.com/Rudloff/alltube ) which initially saves the file as Download.htm (which of course is neither recognised as a video nor image). However, I don't understand when I rename the file to be a .mp4 the video is not then spotted and uploaded?

**Comment by jdaviescoates** [comment]
Yeah, just tested by downloading the exact same video a different way (I downloaded it to my laptop then uploaded it to https://files.uniteddiversity.coop/ then downloaded it directly from there using my phone, and then the auto upload worked fine).

Still, anyway I can get Nextcloud to recognise when download.htm files are renamed to .mp4 and then auto upload those too?

**Comment by AndyScherzinger** [comment]
> (off topic: I'd actually like all files in that folder to Auto upload, including PDF files etc - but I think I'm correct in that at present it's only images and video that auto upload, right?)

You can create a so called "custom folder" via the menu at the top right. Such folders will upload any file no matter the file type. So this should do the trick for you. While in this case you should then deactivate it for images/video since you might end up with duplicate (there is no check if more than one configuration has been made for a single folder).

> However, I don't understand when I rename the file to be a .mp4 the video is not then spotted and uploaded?

I am not exactly sure if/when files are being detected, since images/video rely on Android's media index while custom folders don't.

**Comment by jdaviescoates** [comment]
> You can create a so called "custom folder" via the menu at the top right. Such folders will upload any file no matter the file type. So this should do the trick for you. 

Excellent, thanks! I've now turned off video/ images for that folder and then added the same folder as a custom folder and now everything work exactly as I'd like, thanks!

**Comment by AndyScherzinger** [comment]
You're very welcome, happy I could help 😃

**Comment by jdaviescoates** [comment]
Although rather bizarrely, there is still one video file that is still not uploading in that folder (which is not one of the ones I've had to rename. It was recorded on my phone, either using WhatsApp or Camera, can't remember.  Not really sure how it ended up in the Download folder though!)

**Comment by AndyScherzinger** [comment]
huh, for that case, no idea to be honest. Only thing to have it back-upped would then be to upload that single file manually.
