### ISSUE TITLE
Deck api tests

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#6131]
After I finally got CI up and running again, it still failed on some tests: 
`Tests on android-27(AVD) - 8.1.0 failed: Test run failed to complete. Expected 149 tests, received 143`

I tracked this down to DeckApiTest:
```
05/22 16:44:56: Launching 'DeckApiTest' on emulator.
Running tests

$ adb shell CLASSPATH=$(pm path androidx.test.services) app_process / androidx.test.services.shellexecutor.ShellMain am instrument -r -w -e targetInstrumentation com.nextcloud.client.test/com.nextcloud.client.ScreenshotTestRunner -e disableAnalytics true -e TEST_SERVER_URL http://10.0.2.2/nc -e TEST_SERVER_USERNAME test -e TEST_SERVER_PASSWORD test --no-window-animation  -e debug false -e class 'com.nextcloud.client.integration.deck.DeckApiTest' androidx.test.orchestrator/androidx.test.orchestrator.AndroidTestOrchestrator
Connected to process 17382 on device 'emulator-5554'.

Started running tests

Test running failed: Test run failed to complete. Expected 8 tests, received 2
 ```
@ezaquarii do you have an idea why this is expecting 8, but only received 2?

**Comment by tobiasKaminsky** [comment]
Hm.
Disabling https://github.com/nextcloud/android/blob/43cf2909c4a8fd0c1489470663828b8c9f927fdb/build.gradle#L196 helped

**Comment by ezaquarii** [comment]
@tobiasKaminsky Sadly, `ANDROIDX_TEST_ORCHESTRATOR` seems to be broken. I doesn't work for me at all when trying to run tests in IDE, so I'm not surprised.

**Comment by tobiasKaminsky** [comment]
In #6132 I try to get all tests up and running again.
I hope that our RetryRule is working better than ANDROIDX_TEST_ORCHESTRATOR and thus we can remove the later one.
