### ISSUE TITLE
Copy/move to root folder fails

### ISSUE THREAD

**Issue by asparc** [nextcloud/android#6137]
### Steps to reproduce
1. Select a file from anywhere but the root folder `/`
2. Choose _Move_ or _Copy_
3. Select the root folder `/` as the destination in the menu _Move to..._ or _Copy to..._
4. Click _Choose_
5. Nothing happens...

### Expected behaviour
- The selected file should have been moved or copied, like it does for all other destinations.

### Actual behaviour
- Nothing happens...

### Can you reproduce this problem on https://try.nextcloud.com?
- No, it's an Android problem. This does work via the web interface.

### Environment data
Android version: 8.0.0

Device model: SM-A520F

Stock or customized system: Stock

Nextcloud app version: 3.11.1

**Comment by tobiasKaminsky** [comment]
moving file/folder from subfolder to root just silently fails
