### ISSUE TITLE
Automatic Upload does not work

### ISSUE THREAD

**Issue by iblue** [nextcloud/android#6141]
### Steps to reproduce
1. Install a Nextcloud server
2. Install the Android App
3. Set up Autoupload for my Camera folder

### Expected behaviour
It should upload my Camera folder

### Actual behaviour
It does not upload my Camera folder. When I open the app, it does requests to the server, getting my files, however I do not see it uploading any files to the server. It does neither sync existing nor new files. When I take a picture, nothng happens.

### Can you reproduce this problem on https://try.nextcloud.com?
I don't want to upload my personal files to a public server. However, my server works fine and everything else works, so I determined it's a problem in the app.

### Environment data
Android version: 9

Device model: Mi A2 Lite (M1805D1SG)

Stock or customized system: Stock

Nextcloud app version: 3.11.1

Nextcloud server version: 18.0.4

Reverse proxy: No

#### Web server error log
No entries from installation of the app to error.

#### Nextcloud log (data/nextcloud.log)
No entries when setting up autosync.

**Comment by iblue** [comment]
I don't know why, I changed nothing, I didn't even open the app. It just started syncing the files.

**Comment by AndyScherzinger** [comment]
Thanks for the update @iblue, it might take up to 15 minutes for the auto upload to kick in
