### ISSUE TITLE
Black screen on picture display instead of thumbnail

### ISSUE THREAD

**Issue by Shagequi** [nextcloud/android#6143]
Hi,

@tobiasKaminsky Sorry for the delay, I thought for sure I did create this issue... but I didn't :( 

Before (in January i.e.), when you would like to consult a picture, the thumbnail (used in files list) was used as a "holder" during the picture loading and we got a blurry preview of the picture.
On recent versions of Nextcloud, there is a "black screen" before the image appears (instead of the thumbnail).

![photos_thumb_bug](https://user-images.githubusercontent.com/7050479/82795173-e940ff00-9e73-11ea-9214-970ab8b19675.gif)

Any idea ?

**Comment by tobiasKaminsky** [comment]
In your screencast it seems like you click on an image where no thumbnail exists.
So it is like this when you click on an image
- if there is a thumbnail -> show it
- if there is a resizedImage (in cache) -> show it
- if file is downloaded -> show it
- if nothing, then it shows black

**Comment by tobiasKaminsky** [comment]
Can you verify this?

**Comment by tobiasKaminsky** [comment]
>     * if nothing, then it shows black

When thinking about this, maybe we should show the default image placeholder, with the shimmer effect?
@jancborchardt

**Comment by jancborchardt** [comment]
> When thinking about this, maybe we should show the default image placeholder, with the shimmer effect?

Sounds good, yes! :) Better than only black.

And for things where we have the thumbnail, even if it’s just very blurry, we should show the thumbnail as loading indicator. Then in the background load the higher resolution and just replace it seamlessly.

**Comment by AndyScherzinger** [comment]
designer feedback provided
