### ISSUE TITLE
When in multiselect mode, deselecting all should go out of multiselect mode

### ISSUE THREAD

**Issue by JorisBodin** [nextcloud/android#6147]
Hello,

In actionmode, if 0 selected we have no menu. We should have "selected all"?
![image](https://user-images.githubusercontent.com/2796439/82830524-3e9e0000-9eb6-11ea-9831-0296586faa73.png)

And isn't it weird to have "selected all" in photo view?

**Comment by jancborchardt** [comment]
I’d say when none are selected, it should go out of multiselect mode, no? Cause that way you can very easily invoke multiselect mode by long-press, but then also get out of it quickly by tapping the selected file again. :)

**Comment by JorisBodin** [comment]
@jancborchardt Yes it's better like that :)
