### ISSUE TITLE
auto-upload takes way too long to start

### ISSUE THREAD

**Issue by cholzer79** [nextcloud/android#6153]
### Steps to reproduce
1. have auto upload enabled
2. shoot some pictures
3. auto-upload will *not* start to upload the new pictures right away , not even when you open the nextcloud app, where you do see the new images in the camera folder already. I had to wait ~5 minutes until it started the upload.

Note: I was connected to WiFi

### Expected behaviour
- newly shot images get uploaded right away (at the very least as soon as I open the nextcloud app).
OneDrive works exactly like that, newly shot pictures get synced with very little delay.

### Actual behaviour
- there is a long (unpredictable) delay before the app will start to upload images. to the user it appears as if the auto upload is broken since the app clearly sees the new images in the camera folder but still won't start to sync right away, nor when you open the app and try to force it.

### Environment data
Android version: 10

Device model: One Plus 6T

Stock or customized system: Stock 10.3.3

Nextcloud app version: 3.11.1

**Comment by tobiasKaminsky** [comment]
This is due to saving background work and thus saving battery.
We trigger at least every 15min.
If you want to have it faster, then please open app, go to uploads and swipe to refresh.

**Comment by cholzer79** [comment]
I should have mentioned that this does not work either to force the upload.

Here is what I tried:
- go to "uploads" and "swipe down" / nothing happens
- go to "auto upload" and disable -> reenable sync for the camera folder / nothing happens

**Comment by cholzer79** [comment]
> 
> 
> This is due to saving background work and thus saving battery.
> We trigger at least every 15min.
> If you want to have it faster, then please open app, go to uploads and swipe to refresh.

I should have mentioned that I tried that too to force the sync - which does not work.

Here is what I tried:
-     go to "uploads" and "swipe down" / refresh icon appears breifly, sync does not start
-     go to "auto upload" and disable -> reenable sync for the camera folder / sync does not start
