### ISSUE TITLE
auto-upload cannot be forced

### ISSUE THREAD

**Issue by cholzer79** [nextcloud/android#6159]
the nextcloud app only auto-uploads newly shot pictures at a fixed interval of "at least every 15min", which is too long for me.

As @tobiasKaminsky suggested [here ](https://github.com/nextcloud/android/issues/6153), it should be possible to force auto-sync by going to "uploads" and swiping. However this does not work.

### Steps to reproduce
1. shoot some pictures
2. open netxloud app
3. go to uploads
4. swipe down
5. **refresh icon appears briefly** but: sync does not start, images do not get added to upload queue - queue stays empty. _(When you go to the auto-upload section netcloud does see the newly shot images.)_

### Expected behaviour
- newly shot pictures get added to the upload queue by swiping down on the uploads screen
- **improvement suggestion** (GUI) add "swipe down to force upload" on the upload screen to inform the user that this feature exists.

### Actual behaviour
- nothing happens

### Environment data
Android version: 10

Device model: One Plus 6T

Stock or customized system: Stock 10.3.3

Nextcloud app version: 3.11.1

**Comment by tobiasKaminsky** [comment]
With swipe to refresh (step 4) we schedule a new worker thread, which should run immediately, but it can be delayed by Android.

This is the unfortunately the best we can do, as those processes can be long running and thus they have to run via Android's work manager.

For me, on vanilla Android it starts immediately. I fear that this might be some obscure optimization by OxygenOS.

**Comment by cholzer79** [comment]
> 
> 
> For me, on vanilla Android it starts immediately. I fear that this might be some obscure optimization by OxygenOS.

I also see the exact same issue with:
Sony Xperia XZ2
Samsung Galaxy S6
Xiaomi Mi A2

I also disabled all energy optimizations for the nextcloud app, still the upload **won't start** when I swipe down on the "uploads" screen.

So I'm not sure what is going on but I cannot force auto-sync on 4 different smartphones.

@tobiasKaminsky it's great that it works on your smartphone but I would really apprechiate if you would not be so quick closing my reports. 😅
