### ISSUE TITLE
(new setting) auto-update interval

### ISSUE THREAD

**Issue by cholzer79** [nextcloud/android#6160]
### Is your feature request related to a problem? Please describe.
As @tobiasKaminsky said [here](https://github.com/nextcloud/android/issues/6153) auto-upload only gets active at a fixed interval of _"at least every 15 minutes"_ - which is way too long for me coming from onedrive which starts the upload almost immediatly after I shot a new picture.

### Describe the solution you'd like
Expose the auto-upload interval in the settings and allow the user to change that value.

**Comment by AndyScherzinger** [comment]
Sorry for hard-closing this issue (without a discussion), but the 15 minutes are a technical limitatoin of modern Android versions (except when you are a big company paying the OS folks to give you a fast path...) So we can't speed this up (in a guaranteed way).  Auto-upload might get triggered right away or not (highly depends on the device/OEM). So the 15 minutes a the max time frame in which Android guarantees to call our upload function. Sorry for the bad news :(

cc @tobiasKaminsky

**Comment by cholzer79** [comment]
So Microsoft is paying to get a fast path for OneDrive? :(

**Comment by AndyScherzinger** [comment]
Well, I guess it depends. There are usually win-win situations so one might not always having to pay.

So it takes 15 minutes on your device? Which device, Android version is it? (just curious)

**Comment by cholzer79** [comment]
> 
> So it takes 15 minutes on your device? Which device, Android version is it? (just curious)

It's not just that the auto-upload takes very long to start, I cannot even force the update manually as suggested by @tobiasKaminsky https://github.com/nextcloud/android/issues/6159

I see that behaviour on all our devices (Mine, wife, kids).
One+ 6T
Sony Xperia XZ2
Samsung Galaxy S6
Xiaomi Mi A2

All run stock android (latest update) - also disabled all power saving options for the nextcloud app but that had no effect either.

At work I frequently take a picture with my phone which I then pretty much immediatly need on my PC to process/archive it.
You can surly imagine how annoying it is when the auto sync does not kick in quickly, as well as that I cannot force the upload either which would be an acceptable workaround.
I still have to use onedrive in addition to nextcloud because of this. :-/

**Comment by AndyScherzinger** [comment]
As for the force-trigger maybe @tobiasKaminsky can comment on this again? 🙏

**Comment by ezaquarii** [comment]
On Thu, May 28, 2020 at 10:34:10PM -0700, Andy Scherzinger wrote:
> Well, I guess it depends. There are usually win-win situations so one might not always having to pay.
> 
> So it takes 15 minutes on your device? Which device, Android version is it? (just curious) 

15 minutes is a periodic job scheduler limitation. If we could use
different triggering mechanism, we can potentially acquire immediate
sync capability.

**Comment by cholzer79** [comment]
> 
> On Thu, May 28, 2020 at 10:34:10PM -0700, Andy Scherzinger wrote: Well, I guess it depends. There are usually win-win situations so one might not always having to pay. So it takes 15 minutes on your device? Which device, Android version is it? (just curious)
> 15 minutes is a periodic job scheduler limitation. If we could use different triggering mechanism, we can potentially acquire immediate sync capability.

It would be great if I could force the upload to start immediatly. :)

**Comment by danielb42** [comment]
Sorry for commenting on a closed issue, but related to this I'm _really_ confused atm. Since today (13Jun2020) my auto uploads behave weird, not starting immediately as they have _always_ done in the past. Came here to check for issues maybe introduced by v3.12 and found even older discussions like this one.

- Why were my auto uploads always immediately when that "sometime in 15 minutes" behaviour is (was???) obviously the default?
- Why am I experiencing this since today, not having updated anything (consciously) since v3.12?
- Why is auto upload suddenly using the directory "(InternalMemory)/Pictures", where images are obviously stored temporarily so the Gallery app picks up only broken remains of auto uploaded files?

Even if all this *was* introduced by v3.12 and I'm just too dense to find it in the changelog, it definitely wasn't around for me in v3.11.

Any enlightenment from @tobiasKaminsky or @AndyScherzinger maybe, just to ease my major WTF at least a little bit?

**Comment by cholzer79** [comment]
@danielb42 welcome to the club of users who have issues with auto-sync.

I shot 4 pictures today at 7:59, now it's 12:53 and they still did not get sync'ed (phone is connected to WiFi).

Sadly all issues I created on auto sync problems got closed by the devs with little to no discussion as they don't seem to have that problem (while I see that behaviour on all our families Android phones). So we seem to have to wait until one of them is plagued by it to get this investigated.......

**Comment by danielb42** [comment]
@cholzer79 I just enabled "Vorhandene Dateien ebenfalls hochladen" (eng. "Also upload existing files" I guess) on each auto upload folder and I until now any photo and video was uploaded within 15 minutes. Why this option should have relevance (as the files are definitely not "existing") is beyond me, but maybe you should give it a try.

Again, whatever it is must have come with v3.12. \*shrug*

**Comment by cholzer79** [comment]
> 
> 
> @cholzer79 I just enabled "Vorhandene Dateien ebenfalls hochladen" (eng. "Also upload existing files" I guess) on each auto upload folder and I until now any photo and video was uploaded within 15 minutes. Why this option should have relevance (as the files are definitely not "existing") is beyond me, but maybe you should give it a try.

I have that one enabled too, yet auto upload of new images takes ages.

The pictures I shot at 7:59, finally got uploaded at 14:03 :-/
