### ISSUE TITLE
Can't upload photos; server EOL message when it's up to date

### ISSUE THREAD

**Issue by Petrosophia** [nextcloud/android#6162]
### Steps to reproduce
1. Login via Android app
2. Attempt to upload one or more photos manually
3. Hangs

### Expected behaviour
It should upload the photos.

### Actual behaviour
Photos don't get uploaded (manually or automatically); the screen on which I can tap "Cancel" or "Upload" seems to time out (greys out with spinning "loading" wheel), notifications say the upload is at 0% for a long time, and eventually (after a long time) will indicate that the upload failed.
Additionally, upon opening the app, it says that my server is end-of-life, but it's the most recent stable release, as is the Android app. I don't know if this is related.

### Can you reproduce this problem on https://try.nextcloud.com?
Yes, I was able to connect via the app but was unable to upload anything.

### Environment data
Android version:
9

Device model: 
Motorola Moto X4

Stock or customized system:
Stock

Nextcloud app version:
3.11.1

Nextcloud server version:
18.0.4snap2

Reverse proxy:

#### Web server error log
I'm not exactly sure what's relevant here, but I couldn't find anything that seemed like it 
```
{"reqId":"x","level":2,"time":"2020-05-26T18:14:45+00:00","remoteAddr":"","user":"--","app":"appstoreFetcher","method":"","url":"--","message":"Could not connect to appstore: cURL error 28: Operation timed out after 9731 milliseconds with 2410880 out of 4954543 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)","userAgent":"--","version":"18.0.4.2","id":"x"}
```

#### Nextcloud log (data/nextcloud.log)
```
same as above
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
How many files do you try to upload?
Can you make a screenshot of it?

**Comment by Petrosophia** [comment]
![1](https://user-images.githubusercontent.com/15187307/83038716-46bb8400-a00b-11ea-8456-f8ca3c089606.png)
![2](https://user-images.githubusercontent.com/15187307/83038721-47541a80-a00b-11ea-8119-dd83e7d60a63.png)
![3](https://user-images.githubusercontent.com/15187307/83038720-47541a80-a00b-11ea-998c-d518bc5e3ee3.png)

I've tried everything from uploading one at a time to uploading ~30 at a time with no difference.
