### ISSUE TITLE
Dark/light theme refresh bug

### ISSUE THREAD

**Issue by Shagequi** [nextcloud/android#6164]
Hi,

A quick bug about UI (dark/light).

When you select "Follow system" for theme, sometimes the main activity stay white or dark, even if your system is the total inverse. 

To reproduce : 

1) Go in settings, and chose the theme as "Dark" 
2) On your android system, set the theme as "Light"
3) Return in your app, and set the theme as "Follow System" 
4) Return in the main activity, now the theme is dark on FileDisplayActivity but not in other activities. 

The only way to fix, is to restart completely the app.

Based on master.

**Comment by AndyScherzinger** [comment]
looping in @dan0xii since he originally added the dark/light feature and might be able to add some input.

**Comment by dan0xii** [comment]
Think this is a duplicate of #5929.

**Comment by Shagequi** [comment]
So, if it's a duplicate, let's close this one.
