### ISSUE TITLE
Ошибка установки приложения под Android

### ISSUE THREAD

**Issue by vszadera** [nextcloud/android#6169]
### Steps to reproduce
Предыстория: Приложение Nextcloud уже было установлено на данном устройстве. По ряду причин пришлось сделать сброс настроек до заводских на данном устройстве. После данной манипуляции, приложение отказалось устанавливаться.
1. Пытаюсь установить приложение через Google Play. Приложение не устанавливается, выдает ошибку "Не удалось установить приложение Nextcloud. Повторите попытку. Если это не поможет, воспользуйтесь советами по устранению неполадок"
2. Скачал с GitHub latest.apk, попробовал установить - не устанавливается. Пишет, что не возможно установить, без указания кода ошибки.
3. Установил F-Droid. Попытался установить через f-droid, результат тот же - ошибка установки

### Environment data
Android version:
5.0.2
Device model: 
PSP3532DUO

**Comment by tobiasKaminsky** [comment]
Please only submit in english and then re-open.
