### ISSUE TITLE
Error installing the Next cloud app on Android

### ISSUE THREAD

**Issue by vszadera** [nextcloud/android#6170]
Steps to reproduce
Background: the Next cloud App was already installed on this device. For a number of reasons, I had to reset the settings to the factory settings on this device. After this manipulation, the app refused to install.

Trying to install the app via Google Play. The app does not install and returns the error " Nextcloud app could not be installed. Try again. If this doesn't help, follow the Troubleshooting tips"
Downloaded from GitHub latest. apk, tried to install - does not install. Writes that it is impossible to install without specifying the error code.
Installed F-Droid. Tried to install via f-droid, the result is the same-installation error
Environment data
Android version:
5.0.2
Device model:
PSP3532DUO

**Comment by tobiasKaminsky** [comment]
> Background: the Next cloud App was already installed on this device.

How can this be?
Maybe the app is somehow installed as a system app and thus cannot be re-installed again?

Or do you have multiple users/accounts? Then it is only uninstalled for you, but not for the others.

**Comment by vszadera** [comment]
It could be.
If the application was installed as a system application, then when you reset the settings to factory settings, the application is deleted. What proof can I give you?

**Comment by vszadera** [comment]
Background: the Next cloud App was already installed on this device.

This is a disadvantage of the translator. What I really wanted to say is that the Nextcloud client was already installed on The same device earlier

**Comment by vszadera** [comment]
I downloaded the apk version 3.0.2 - everything was installed without problems

**Comment by vszadera** [comment]
The problem is still present. As I mentioned earlier, I installed version 3.0.2 from the apk.
If you try to update to a newer version in Google Play, the error remains the same.

**Comment by tobiasKaminsky** [comment]
> If the application was installed as a system application

How did you installed it as a system app?

**Comment by swishi** [comment]
I have exactly the same problem... is there any soution to that...? Im trying to insztall the nc app to my samsung s10 throgh the playstore but the installation stopps after a few instants... i tryed cleaning the cache of the playstore and did the restart of the phone... nothing to do...! I newer had nc installed before...
