### ISSUE TITLE
Crash on Samsung chromebook plus v2

### ISSUE THREAD

**Issue by johnwmail** [nextcloud/android#6182]
### Steps to reproduce
1.  install NC from google play store on chromebook
2.  start the NC app
3. 

### Expected behaviour
normally start the app

### Actual behaviour
crash and cannot start

-----------------------------------------
Hi all, it work before, but recently I found it cannot access NC files via CB files app.
so I try to reinstall NC app, after reinstall NC, it even cannot run, NC show the crash/error on every boot.
any idea why will that? any workaround, thanks.

Samsung ChromeBook Plus v2 (83.0.4103.77) 64bit

**Comment by tobiasKaminsky** [comment]
I tested it with an Acer Chromebook and i can use it without any problems.
Do you see any further infos?

**Comment by johnwmail** [comment]
Hi, I understand it is hard to help without useful information.
Is there easy/simple way to make debug log to devs, if it crash again?

I removed it, reboot, install NC (without any config/setup), reboot, setup NC connect to NC server, then it do not crash again.

**Comment by johnwmail** [comment]
I cannot reproduce the problem now
