### ISSUE TITLE
Sharing files: request for improvement

### ISSUE THREAD

**Issue by OlivierS1** [nextcloud/android#619]
### Actual behaviour
-Tell us what happens
When selecting a file for sharing, the application will present a popup window where user can be entered.
Once the user has been selected, there is an option to clear the keyword used in the search bar, so that another user can be added. This is fine.
However, the only way around to exiting this popup window is to press the back key on my phone. 
This requires like 4 or 5 key press before getting back to the file list.
It would be great to have an extra button available that will allow the window to be cleared once pressed.

### Expected behaviour
-Tell us what should happen
Once the user has been selected, the popup window should present another button giving the option to terminate the sharing process and return to the list of files.
 
### Steps to reproduce
1. Select one files only.
2. Select to share the one file.
3. Enter the user name to share with.
4. Accept the selection of the user.
5. "Exit" or "Return to list" button should be presented. It could also be presented at step 4 to save one keypad press.
6. The popup window should close and present the list of files as it was before.
7. Since only one file can be selected for sharing, and because the list of share is not relevant anymore as it was already presented, it would make sense to unselect the file automatically. This way the next file can be selected and shared if needed.

### Environment data
Android version:
6.0

Device model: 
LG G3

Stock or customized system:
Stock

Nextcloud app version:
1.4.1 and Beta 20170202

Nextcloud server version:
NC 11.0.1

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

**Comment by tobiasKaminsky** [comment]
Thank you for taking the time to report this enhancement.
cc @jancborchardt @eppfel (our designers/UX experts)

Searching for an user
![screenshot_1486135507](https://cloud.githubusercontent.com/assets/5836855/22596832/6cc3a444-ea2d-11e6-84cd-b5f888c02ec3.png)

Selected an user
![screenshot_1486135522](https://cloud.githubusercontent.com/assets/5836855/22596830/6c1cff0e-ea2d-11e6-8207-78942f7cc7fc.png)

One have to click back multiple times
![screenshot_1486135531](https://cloud.githubusercontent.com/assets/5836855/22596831/6cb200f4-ea2d-11e6-9ca0-1b5a8f0289a6.png)

**Comment by eppfel** [comment]
Good suggestions, here my Usability Review:

1. the search for users should be intragrate into the share dialog. The button add user could add an search input into the list of users 
2. everytime you select a user it gets added to the list and the searchbar is cleared and the cursor sits there.
3. Add simple done button to the end, so you don't require the the back button.
4. Deselect the file as @OlivierS1 suggested


If integrating is to complex, I'll propose 2.-4. anyway.

**Comment by jancborchardt** [comment]
Agree with everything @eppfel said. Additionally of course sharing and all the actions should - as said many times before ;) be reachable through a 3-dot menu on the right of each entry, just like in the mobile view of the web interface.

Long-press select is for multiselect and only that. :) If we abolish that for this single-file workflow, this problem is also solved.

**Comment by joshtrichards** [comment]
UI is completely different now. Closing. :)
