### ISSUE TITLE
Bug in Drawer header on first connection

### ISSUE THREAD

**Issue by Shagequi** [nextcloud/android#6194]
Hi, 

Due to : https://github.com/nextcloud/android/issues/5207 

When you connect on your Nextcloud  server (at least, for the first time), the Drawer header color is "wrong" and still blue : 

![Capture d’écran 2020-06-02 à 14 44 19](https://user-images.githubusercontent.com/7050479/83521635-cb147800-a4df-11ea-8c12-2b2e3c0c28f8.png)

I reproduced this bug by : 
1) Reinstalling completely nextcloud
2) Adding my Nextcloud account
3) Watching the Drawer header

It's due to a color-resolution bug or latency, I don't know why 

Based on master.

**Comment by AndyScherzinger** [comment]
This has also been true for the old theming implementation, @tobiasKaminsky might be able to provide some details. AFAIK the header fetching is done asynchronously.

**Comment by tobiasKaminsky** [comment]
We get the theming info via capability, which is done at some point after starting the app.
After we have this info, we do not directly update it (legacy code), but wait for next app refresh.

Dup of #2075
