### ISSUE TITLE
Perpetual thumbnail loading on scroll

### ISSUE THREAD

**Issue by Shagequi** [nextcloud/android#6196]
Hi, 

Due to : https://github.com/nextcloud/android/issues/5207 

When you load a folder full of pictures, the thumbnail is no longer cached 

![no-cache](https://user-images.githubusercontent.com/7050479/83522763-69eda400-a4e1-11ea-88ee-a7f89f55d7c1.gif)

So,

1) Go in a large folder of pictures (> 300MB, 20+ pictures)
2) The top is being loaded (you may see the "shimmer" effect)
3) Once the top loaded, if you go down, the "bottom pictures" will be loading, but if you go back to the top, the top pictures will be loading on more time (when they've already been loaded)

Maybe a cache-issue or an UI invalidate issue ? 

Based on master.

**Comment by tobiasKaminsky** [comment]
Are the thumbnails really fetched again from server?
Or is it only a UI problem?

**Comment by tobiasKaminsky** [comment]
I cannot reproduce this.
For me the images on "top" are shown directly, without any shimmer nor delay…

**Comment by Shagequi** [comment]
@tobiasKaminsky 

It's only on the first load. 
You need to clear cache/restart the app and consult a "big folder" with many pictures in it. 

If you scroll down, then scroll up, the pictures will be loaded one more time. 

According to @sirambd , the problem is that when you scroll (bind the views), you create jobs (async tasks) to get the thumbnail, and if you don't stop to scroll, you'll always create new jobs.

**Comment by tobiasKaminsky** [comment]
> According to @sirambd , the problem is that when you scroll (bind the views), you create jobs (async tasks) to get the thumbnail, and if you don't stop to scroll, you'll always create new jobs

Hm. I guess this is true.
But when we would kill all the task once the view is out of screen scope, then we might never finish any task…
Do you have an idea?

**Comment by szaimen** [comment]
Ping

**Comment by Derkades** [comment]
I cannot reproduce in app version 3.13.3 with these steps:
* Open a folder I had never opened before
* Wait for thumbnails to load
* Scroll down
* Wait for more thumbnails to load
* Scroll back up
* Observe thumbnails are still visible, unlike your video

**Comment by szaimen** [comment]
In my case it is still reproducible on 3.13.1:
[Screen_Recording_20200912-140816_Nextcloud_1.zip](https://github.com/nextcloud/android/files/5212641/Screen_Recording_20200912-140816_Nextcloud_1.zip)

**Comment by Derkades** [comment]
I can reproduce it on SMB external storage. Previously I tried it on local external storage

**Comment by Derkades** [comment]
Still had the issue yesterday

**Comment by tobiasKaminsky** [comment]
There is an APK file in this PR, which you can install in parallel to your existing Nextcloud app.

**Comment by Derkades** [comment]
> There is an APK file in this PR, which you can install in parallel to your existing Nextcloud app.

Can you point me to where I can find the download link?

**Comment by szaimen** [comment]
> > There is an APK file in this PR, which you can install in parallel to your existing Nextcloud app.
> 
> Can you point me to where I can find the download link? I have clicked through a couple of the CI entries but I can't find a build anywhere

https://github.com/nextcloud/android/pull/7111#issuecomment-712104242

**Comment by szaimen** [comment]
> There is an APK file in this PR, which you can install in parallel to your existing Nextcloud app.

@tobiasKaminsky I have tested the PR and it seems to solve the issue. Thanks!
