### ISSUE TITLE
Sort-by and grid/listview not effective in Local synchronization

### ISSUE THREAD

**Issue by Shagequi** [nextcloud/android#6202]
Hi,

In this view (Setup a custom folder) :
 
![Capture d’écran 2020-06-02 à 17 20 46](https://user-images.githubusercontent.com/7050479/83539868-df646f00-a4f7-11ea-99b3-dbed20e1a96e.png)

When you choose a local folder, there are buttons to sort-by/change display but they don't work : 

![bug](https://user-images.githubusercontent.com/7050479/83540300-64e81f00-a4f8-11ea-8c6d-3494a7e258a0.gif)

Based on master.
Due to : #5207

**Comment by AndyScherzinger** [comment]
Also used for manual file uploads via the fab button

**Comment by tobiasKaminsky** [comment]
Fixed by https://github.com/nextcloud/android/pull/6203
