### ISSUE TITLE
Cannot share to Instagram in Android 8

### ISSUE THREAD

**Issue by DesktopMasters** [nextcloud/android#6208]
### Steps to reproduce
1. Click share icon on photo in NextCloud app.  (does not matter if it is downloaded or not)
2. Click the "Feed" Icon for Instagram

### Expected behaviour
Instagram should show the image with a posting wizard.

### Actual behaviour
Get a Toast message from instagram "Unable to load image" and then it disappears.

### Environment data
Android version: 8.0.0

Device model: LG-LS993

Stock or customized system: Stock

Nextcloud app version: 3.11.1

Nextcloud server version: 18.0.4

Reverse proxy:
Nginx

**Comment by tobiasKaminsky** [comment]
Is this working with other apps, e.g. WhatsApp?

**Comment by DesktopMasters** [comment]
I am sorry, I should have included that.  We did some testing in IRC and yes, it does work with WhatsApp

**Comment by AndyScherzinger** [comment]
I just tested the latest master on an Android 10 device and sharing to Instagram Feed works for me :/

**Comment by DesktopMasters** [comment]
Bump
