### ISSUE TITLE
Enhance FolderPickerActivity: start in folder

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#6217]
- go into subfolder
- copy/move file
- see that you are root folder
--> should start in selected folder
--> needs to update UI
  - on top: show folder
  - on bottom: move/copy
--> replace getCurrentFolder() / mFile with getListOfFiles().getCurrentFile()

- test afterwards with FilePickerActivity

**Comment by Michele64** [comment]
That was the behaviour in some previous versions, but disappeared

**Comment by joshtrichards** [comment]
Missed this earlier when I started consolidating issues for this into #11831. Oh well. 

Duplicate of #11831 :P

**Comment by Michele64** [comment]
hmm, care to explain why? I still think it's the expected behaviour

**Comment by joshtrichards** [comment]
Explain why what? Their is an issue tracking this - I'm just eliminating duplicate issues. See #11831 as I stated. :-)
