### ISSUE TITLE
Android app cannot auth on Owncloud 10.4.1 server

### ISSUE THREAD

**Issue by bombaata** [nextcloud/android#6223]
### Steps to reproduce
1. login to existing owncloud server using Nexcloud app
2. server found, login/password ok, OTP ok
3. server account show

### Expected behaviour
- Nextcloud app should auth

### Actual behaviour
- my Owncloud user account opens

### Can you reproduce this problem on https://try.nextcloud.com?
Server setup is ok. No errors in logs.
Owncloud app is working.

### Environment data
Android version: 8.0.0

Device model: Samsung SM-G930F

Nextcloud app version: latest from F-Droid of Google Play store

Owncloud server version: 10.4.1

**Comment by tobiasKaminsky** [comment]
We do not support ownCloud.
Is there a reason why you do not want to user their official client?

**Comment by bombaata** [comment]
I'm looking for a way to sync my data to the SD card of my phone. This feature doesn't exist on Owncloud's app. I was told that Nextcloud's app would work with Owncloud server, obviously it doesn't.
