### ISSUE TITLE
Currently active account is represented on multiple ways

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/android#6228]
After pressing the account switcher button in the toolbar and go to "Manage accounts" activity i saw that the currently active user is represented in multiple ways.

Differences:

1. The "active" icon is on the completely other side of the display
2. The "active" icon switches between `check` and `person`
3. The "active" icon switches between `overlapping avatar` and `free standing`

This makes it harder to remember and recognize the currently active account.

Therefore I propose to decide for one of the ways to display the currently active account.

Personal opinion: I like the overlapping of the avatar (we also use it in Deck), but i would go for a `check` instead of the `person`, the latter seems repeated unnecessarily.

![grafik](https://user-images.githubusercontent.com/4741199/83940464-868d2300-a7e4-11ea-8b9c-a13a04d9225d.png)

![grafik](https://user-images.githubusercontent.com/4741199/83940467-8b51d700-a7e4-11ea-9133-6bf71dd2af63.png)

cc @nextcloud/designers @jancborchardt @tobiasKaminsky

**Comment by jancborchardt** [comment]
I'd agree the overlapping of the avatar is good since it works in more setups. The check on the right doesn't work so well if there is a 3-dot menu on the right already as it looks like an action.

Regarding icon, a checkmark is better though. Otherwise we have an avatar overlaid with the icon of an avatar, which is strange. ;)

And lastly, to make it very visually clear that an entry is selected, we should also give it a background color, exactly like for navigation entries in the left side menu as well. What do you think?

**Comment by stefan-niedermann** [comment]
So something like this would be the goal for both menus? (Mockup)

![image](https://user-images.githubusercontent.com/4741199/83944823-c5cc6b80-a806-11ea-9d1e-ddf03ba0e773.png)

> And lastly, to make it very visually clear that an entry is selected, we should also give it a background color, exactly like for navigation entries in the left side menu as well. What do you think?

:-1: Hmm, i don't think this looks *that* good. It is **not** a navigation menu.
I would only highlight a navigation menu if it's something like... hmm like a URL or a website where you can go.

But the account menu here is more like selection menu. I would compare it with something like this:

![image](https://user-images.githubusercontent.com/4741199/83944765-50f93180-a806-11ea-836f-1f8758b9397a.png)

And while there is an indicator for the current selection, never the whole selection has another background.

**Comment by jancborchardt** [comment]
Ok, sure – then your proposal works from my view. :+1:  :)
