### ISSUE TITLE
Nextcloud Android client crash grid view

### ISSUE THREAD

**Issue by JohannesStroebel** [nextcloud/android#6232]
### Steps to reproduce
1. Select "Upload Media"
2. Choose "Grid view"

### Expected behaviour
- grid view

### Actual behaviour
- App crashes

Android version: Android 11

Device model:  Xiaomi Mi 9t

Stock or customized system: Stock

Nextcloud app version: 3.11.1

Nextcloud server version: 18.0.4

Reverse proxy: Nginx

nPN64vuLYxU7SJHRpkU4

**Comment by strugee** [comment]
Duplicate of #6133, I believe. If that doesn't sound right, feel free to comment and I can reopen!

**Comment by JohannesStroebel** [comment]
Yep, I also think so. It is fixed in the latest Dev version 20200530
