### ISSUE TITLE
Hide header bar on scrolling

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#6238]
n Gmail and Material Files (from F-Droid) for example, when you scroll down, the whole header bar hides, and shows again when you scroll up a bit. This gives you a lot of space for your files and is really nice.

**Comment by tobiasKaminsky** [comment]
What do you like more when scrolling up?
Only search bar is gone vs everything vanishes (right) 

![2020-06-09-102312](https://user-images.githubusercontent.com/5836855/84124239-3fe53600-aa3b-11ea-90f7-eb7d813a5fb5.png) ![2020-06-09-102316](https://user-images.githubusercontent.com/5836855/84124241-407dcc80-aa3b-11ea-8bbd-59034395a27c.png)

A video: https://nextcloud.kaminsky.me/s/DHGpNgMcZooF4Dy

@jancborchardt @AndyScherzinger @JorisBodin @Shagequi

**Comment by AndyScherzinger** [comment]
I'd vote for everything vanished (like GDrive also)

**Comment by JorisBodin** [comment]
What ever you like :)

BTW @tobiasKaminsky you can use native software for screenrecord :D
Directly in gif for github
https://reactnativeforyou.com/how-to-screen-record-and-take-screenshots-from-android-emulator-without-using-android-studio/
or
https://developer.android.com/studio/debug/am-video

**Comment by szaimen** [comment]
> I'd vote for everything vanished (like GDrive also)

+1

**Comment by jancborchardt** [comment]
> I'd vote for everything vanished (like GDrive also)

Yep – the reasoning here being that the sorting and grid toggle is definitely not more important than menu / search / account switcher. So the whole top block can vanish. :)
