### ISSUE TITLE
Update actions menu style to Material 3

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#6239]
Instead of the small popover we can use the proper bottom sheet which is nicely reachable with the thumb. It should of course show the file in question on top so you know what the action will be carried out on.

**Comment by jancborchardt** [comment]
Just a note: Bottom sheets seem to be not so much used in Material You anymore, but in-place menus with the rounded corners and ideally icons like so: https://m3.material.io/components/menus/overview

**Comment by AlvaroBrey** [comment]
@jancborchardt I still think we should go with bottom sheets, we have a lot of actions for a menu already

**Comment by tobiasKaminsky** [comment]
I am also all for bottom sheets, as Alvaro said, it is way cleaner than those popup menu…

**Comment by AndyScherzinger** [comment]
See https://m3.material.io/components/menus/guidelines m3 suggests bottom sheets for mobile/small screens and pop over menues for large screens, so since we don't have a proper tablet layouting I would also suggest to go with bottoms sheets.
