### ISSUE TITLE
Feature request: try app passwords in uppercase

### ISSUE THREAD

**Issue by rigrig** [nextcloud/android#625]
### Actual behaviour
- user creates app password: ABCDE-FGHIJ-KLMNO-PQRST (which is good, because uppercase is easier to read)
- user attempts to log in with abcde-fghij-klmop-pqrst
- login attempt fails

### Expected behaviour
- The client should detect the provided password matches /[a-z]{5}-[a-z]{5}-[a-z]{5}-[a-z]{5}/ , retry to login with strtoupper($password), and (on success) remember the uppercase password.

 
### Steps to reproduce
1. create app password, which is in UPPERCASE
2. enter the app password into the app, but without turning CAPSLOCK on
3. fail to log in

**Comment by tobiasKaminsky** [comment]
I think the password is case-sensitive because it adds more complexity to possible password combinations. So I think it should sty the way.

**Comment by rigrig** [comment]
I didn't mean to make passwords case-insensitive.
I meant the specific case of app passwords:
These are already generated in all caps, in the pattern ABCDE-FGHIJ-KLMNO-PQRST.
If you then type this into your phone but forget about using uppercase, it would be nice if the app detects that the entered password looks like a lowercase app password and also tries it in uppercase.

This wouldn't affect the security of your account at all, as the server-side authentication stays the same, only the app now tries two passwords.

**Comment by mario** [comment]
@rigrig that goes against all logic. I'm sorry, but this is not something we will do.
