### ISSUE TITLE
Decide on font

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#6252]
> The font family (font style?) still seems to be different compared to the dialog

@stefan-niedermann yeah, this is anothe rissue which according to @JorisBodin is due to the use of material UI classes which default to another (newer) font but yes this should be fixed (via another PR)

_Originally posted by @AndyScherzinger in https://github.com/nextcloud/android/pull/6245#issuecomment-640496621_

**Comment by tobiasKaminsky** [comment]
@jancborchardt I remember that we switched font at some point and reverted then back again.
So I prefer to keep the font we have in drawer/everywhere else and only switch the font in the new dialog?

**Comment by AndyScherzinger** [comment]
reading https://www.xda-developers.com/roboto-android-fall-rise-default-font/ I'd also vote for staying with Roboto since Google Sans is proprietary so that might lead to issues throughout the different Android versions :/

**Comment by tobiasKaminsky** [comment]
Can someone help me a bit here?
Our create folder dialog seems to use:
https://github.com/nextcloud/android/blob/768b067fb2d802244ee10ebf57d8ff950fcd63f6/src/main/res/values/styles.xml#L107

![image](https://user-images.githubusercontent.com/5836855/84126003-a3706300-aa3d-11ea-87c2-2e1e0a63906b.png) ![image](https://user-images.githubusercontent.com/5836855/84126041-af5c2500-aa3d-11ea-9437-468c64cc3d24.png) ![image](https://user-images.githubusercontent.com/5836855/84126135-d155a780-aa3d-11ea-8ed9-69dcaa395499.png) ![image](https://user-images.githubusercontent.com/5836855/84126250-f518ed80-aa3d-11ea-8f72-510b80cd636e.png) 


(account choose dialog - create folder dialog - list view - drawer)
left to right

**Comment by JorisBodin** [comment]
> reading https://www.xda-developers.com/roboto-android-fall-rise-default-font/ I'd also vote for staying with Roboto since Google Sans is proprietary so that might lead to issues throughout the different Android versions :/

We should no longer use google lib. 🤷‍♀️
Remove `com.google.android.material:material` in the build gradle

**Comment by tobiasKaminsky** [comment]
This is from "create folder" dialog, so our long term used UI:
![image](https://user-images.githubusercontent.com/5836855/99492822-89cd3300-296e-11eb-976c-ae8e2b04bb5f.png)

The top one is MaterialButton with typeface sans:
The bottom one is unchange MaterialButton:
![image](https://user-images.githubusercontent.com/5836855/99493074-e3356200-296e-11eb-8fad-b47460550aaf.png)
(both are from "choose account" dialog.

It seems that "create folder" and top one are the same, or?

**Comment by AndyScherzinger** [comment]
Looks like it, yes. So that means what?

**Comment by tobiasKaminsky** [comment]
That means we can add "typeface:sans" to every usage of MaterialButton and then we have a consistent font again.

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger do you know if we can do this via a style?

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky yeas that should be possible, while I can't say if we need to set that style on all buttons manually.
