### ISSUE TITLE
Doc files wont open via collaborate

### ISSUE THREAD

**Issue by axheli** [nextcloud/android#6268]
### Steps to reproduce
1. Open Nextcloud app
2. open a doc and ever open with collaborate
3. 

### Expected behaviour
- The file shoould open up

### Actual behaviour
- File never openes up

### Environment data
Android version: 10

Device model: Oneplus 7 Pro

Stock or customized system: Stock

Nextcloud app version: 3.12.0

Nextcloud server version: 19
![Screenshot_20200610-203644](https://user-images.githubusercontent.com/59488153/84335568-bfb5f200-ab5a-11ea-9be9-41dd2a1ead8e.jpg)

**Comment by elpraga** [comment]
I'm experiencing the same issue I'm version 3.12. using Google chrome works flawlessly on the and device.

Do you need more information?

**Comment by rubinho76** [comment]
I have the same problem since the update to NC19.
Everything works fine with a web browser.
With the Android version (stable or dev) nothing works.
I have tested both versions of Colabora, Docker  and Built-In .

**Comment by elpraga** [comment]
Were the developers able to reproduce this bug?

Do you need more information?

**Comment by tobiasKaminsky** [comment]
Can you create us a test account, test if the problem occurs also there and if so send the credentials to tobias at nextcloud dot com with a reference to this issue?

**Comment by martin-77** [comment]
Same here on android 10
Working without any problems on my ipad, via browser on android (and windows - browser independent)
Setup: nextcloud 19
Collabora on external server in a docker container- latest version, I think it is 4.2.4.4

Greetings

**Comment by elpraga** [comment]
I've sent you the email you and for @tobiasKaminsky

**Comment by elpraga** [comment]
@tobiasKaminsky have you reviewed the log in details from me?

**Comment by MattSpec** [comment]
Also experiencing this error. I seem to get a log entries:

session_start(): A session had already been started - ignoring at /var/www/nextcloud/lib/private/Session/Internal.php#209

**Comment by obrb** [comment]
same here:

Pixel3a, Android 10, Stock. Nextcloud Android App 3.12.0
Nextcloud 19.0.0 on Ubuntu 18.04 with Apache 2.4.43, PHP 7.3.19 and MariaDB 15.1
Latest Collabora Docker Container and Collabora Online App

Collabora is working fine via browser on desktop and mobile. (latest Firefox and Chrome). iPad is also working fine in both Safari and the official Nextcloud iOS App.

**Comment by ti-guru** [comment]
Same issue in Android app with loading spinner stuck after tapping on document. I'm running separate LXD containers with Nextcloud 19.0.0 on domain cloud.mydomain.tld and Collabora Office 6.2-17 native packages on office.mydomain.tld behind a Nginx reverse proxy. Collabora opens as expected in browser on desktop and mobile. No obvious warnings or errors in logs.

**Comment by rubinho76** [comment]
Hi
Is the problem reproducible on the part of the developers, or does it require further information?

**Comment by elpraga** [comment]
We've tried to provide what they asked for, it seems that they still haven't used that information. 

Strange, because this bug evidently affects multiple users (those who reported it here and those who don't bother reporting anything and just think it's bad software that doesn't work)

**Comment by martin-77** [comment]
Bug is fixed my latest collabora-plugin update (I think it is 3.7.1).
Thanks!

**Comment by axheli** [comment]
Yes, fixed in 3.7.1 app.

**Comment by elpraga** [comment]
I'm sorry @axheli , I'm somewhat confused. The latest version of the Nextcloud app I'm the Play Store is 3.12.

What is version 3.7.1?

**Comment by rubinho76** [comment]
Great, it's working again. Thanks
