### ISSUE TITLE
Delete ALL relevant local files once account is removed

### ISSUE THREAD

**Issue by mario** [nextcloud/android#627]
Currently when you remove an account all files stay on your phone.

This is, IMHO, a very big security problem and should be remedied for 1.5.0.

Todo:
Show a warning with the options OK and Cancel, but don't provide the option "Remove account but keep data locally".

**Comment by tobiasKaminsky** [comment]
I think there was a discussion about it, either here or back then on ownCloud repo...
But I do not remember the conclusion of it...

When removing the account the user should get a warning "all files will be deleted from your phone and stay on server" to make sure the user knows what it is doing.
I think it should be a question and the user can choose to keep the files (as it is his/her phone and his/her data and he is responsible for it).

@AndyScherzinger @jancborchardt

**Comment by mario** [comment]
Less options, more defaults - since the files stay on the server no harm done. 

But @jancborchardt is our UX guy, so let's just wait for him...

**Comment by tobiasKaminsky** [comment]
(label 1.-4. are only for PRs, Issue should only have these labels "none", "approved", "pr exists").

**Comment by AndyScherzinger** [comment]
I'd also say there should then be a warning that the files will be removed from the device but like Mario argues for the default also say that if the user chooses to remove the account the files will be deleted but never kept on the device. 

Else just don't remove the account. ;)

**Comment by mario** [comment]
@AndyScherzinger some bugs in your answer maybe? :D

**Comment by AndyScherzinger** [comment]
I edited the comment, tl;dr:

Show a warning with the options OK and Cancel, but don't provide the option "Remove account but keep data locally).

**Comment by mario** [comment]
I can live with that, even though I'm always a fan of less warnings, especially with things that are easily revertable (like removing an account from an app is). :)

**Comment by AndyScherzinger** [comment]
It is not about the part of re-adding the account but of possibly re-downloading all the files ;)

**Comment by OlivierS1** [comment]
Should this apply to server password revocation as well. If security is a concern it would make sense content is made unavailable. Not sure how much can really be done unless device gets proper intrrnet access. Or maybe should this be left to antitheft apps instead.

**Comment by jancborchardt** [comment]
Yep, just delete but with a warning is nice cause it's a very destructive action (hassle to add the account again) and very seldomly done. As @AndyScherzinger proposed.

**Comment by AndyScherzinger** [comment]
merged to master for 1.5.0
