### ISSUE TITLE
2 loader in same time

### ISSUE THREAD

**Issue by JorisBodin** [nextcloud/android#6271]
Hello @jancborchardt

Do you have any idea what that should be like?
|On device|On first folder download|
|---|---|
|![image](https://user-images.githubusercontent.com/2796439/84398139-dc583580-abff-11ea-8900-266a4b0b8911.png)|![image](https://user-images.githubusercontent.com/2796439/84398154-e417da00-abff-11ea-8349-7c4a33e73e8e.png)|

**Comment by jancborchardt** [comment]
Would it be possible to replace any of the "full-screen" spinners with the skeleton loading feedback? Then the "pull to refresh" spinner can still be there, but the content will be skeleton screens.

**Comment by JorisBodin** [comment]
I like skeleton loading idea :)

**Comment by AndyScherzinger** [comment]
Uuuh, skeleton loading sounds very nice 👍

**Comment by jancborchardt** [comment]
The good part is that we could totally extend on the work done by @sirambd on the thumbnail loading feedback :) https://github.com/nextcloud/android/pull/5991

**Comment by AndyScherzinger** [comment]
Yes absolutely 👍

**Comment by tobiasKaminsky** [comment]
Maybe @sirambd can help here out? :+1:

**Comment by tobiasKaminsky** [comment]
PR is #6757
