### ISSUE TITLE
Deleted files is show before end downloading

### ISSUE THREAD

**Issue by JorisBodin** [nextcloud/android#6272]
![image](https://user-images.githubusercontent.com/2796439/84400684-9fda0900-ac02-11ea-9ad9-c673f8e1a15d.png)

**Comment by tobiasKaminsky** [comment]
Can you give me some more details?
I do net fully understand the problem/screenshot?

**Comment by JorisBodin** [comment]
@tobiasKaminsky "Aucun fichier supprimé" = "No file deleted"
While the request is still being loaded. And there are a lot of deleted files

**Comment by AndyScherzinger** [comment]
still valid

**Comment by tobiasKaminsky** [comment]
Ah, so it is the same like on files…
There I did the trick that if we know that a subfolder is not empty (as we know the size), we show only the spinner.

But on trashbin, we do not know it.
So best would be to remove this empty content view until loading has finished.

--> let me have a look right now.
