### ISSUE TITLE
New header jumps around

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/android#6274]
### Steps to reproduce
1. Click the new header to open the searchbar
2. close the searchbar to return to the "card"-layout header
3. watch content juming around (e.g. look at "A - Z ⇩")

![ezgif-6-afd12a187ad1](https://user-images.githubusercontent.com/4741199/84469619-cbe89f00-ac81-11ea-9574-31aca9c4e66b.gif)

**Comment by tobiasKaminsky** [comment]
Hm. This is the same Gmail is doing:
![2020-06-15-125630](https://user-images.githubusercontent.com/5836855/84649938-a5d43080-af07-11ea-8332-819933796572.png) ![2020-06-15-125626](https://user-images.githubusercontent.com/5836855/84649939-a66cc700-af07-11ea-9688-8cc6d1e0ce4b.png)

Do you have a suggestion?

**Comment by stefan-niedermann** [comment]
I think it's caused by the way how we construct the two different toolbars.

1. The "card"-thingy (right side) has the shadow on all sides, which requires the shadow to be applied directly on the card view.
2. The default toolbar (left side) has no shadow, but uses the shadow of the `AppBarLayout`.


![grafik](https://user-images.githubusercontent.com/4741199/84651653-99050c00-af0a-11ea-8f49-21c6d083aeae.png)

One solution would be to not use `AppBarLayout` at all but apply the other shadow to the toolbar from 2. There might be other disadvantages though, e. g. we cannot use `android:layout_height="?attr/actionBarSize"`, because this does not include the spacing for the shadow which will overflow and be hidden behind the main content then

![grafik](https://user-images.githubusercontent.com/4741199/84652086-52fc7800-af0b-11ea-85e2-57e249e677d1.png)

**Comment by AndyScherzinger** [comment]
still open

**Comment by tobiasKaminsky** [comment]
Is this related to the shadow? Or not "only" a problem of different heights?

**Comment by stefan-niedermann** [comment]
The current issue is different from the original issue i think.

Originally the height did not match exactly, make the header look like jumping a bit when activating the search.

Currently this doesn't matter anymore because the activate search card *contains* now the grid-view and sort buttons.
Remaining issues though are:

- **The grid-view and sort buttons are not at the same vertical offset**

| - | - |
| --- | --- |
|  ![](https://user-images.githubusercontent.com/4741199/88300673-0d01b380-cd04-11ea-82ae-7a4384fd7c99.jpg) | ![](https://user-images.githubusercontent.com/4741199/88300695-11c66780-cd04-11ea-80b6-b3e64a49571e.jpg) |

- **In the moment while activating the search, the shadow crazily shakes up and down for a second.** This looks like a defect animation.

**Comment by tobiasKaminsky** [comment]
>     * The grid-view and sort buttons are not at the same vertical offset

I do not understand this :/



>     * **In the moment while activating the search, the shadow crazily shakes up and down for a second.** This looks like a defect animation.

True, but I have no clue what the root cause of this might be…

**Comment by stefan-niedermann** [comment]
> I do not understand this :/

I took a screenshot of the images in GitHub. The buttons on the left screenshot are higher than the buttons on the right screenshot. You see?

![Screenshot_20200723-172120_Firefox_Preview](https://user-images.githubusercontent.com/4741199/88304801-01fd5200-cd09-11ea-903f-6933aed8b198.png)
