### ISSUE TITLE
Autoupload account not pin'able

### ISSUE THREAD

**Issue by mrvanes** [nextcloud/android#628]
### Actual behaviour
-Tell us what happens
I have two NextCloud servers and configured two NextCloud accounts.
I have AutoUpload enabled and have it pointed to photos/upload.
I want the pictures to be uploaded to server 1.
When I take a picture, the auto-upload process uploads the picture to the server that was last accessed in the NextCloud app.
Then, trying to manually upload the same picture to upload path on server 1 fails with unknown error.

### Expected behaviour
-Tell us what should happen
I want the picture allways to be uploaded to server 1, independent of last server accessed in app.
I want to be able to manually correct the wrong upload afterwards.
 
### Steps to reproduce
1. Have two NextCloud servers
2. Setup two NextCloud accounts
3. Enable auto-upload, select destination folder on server 1
4. Access server 2 in app.
5. Take picture
6. Picture is uploaded to upload path on server 2, if it didn't exist, it is created.
7. Manually upload picture to upload path on server 1 fails (unknown error).

### Environment data
Android version: 6
Device model: Alcatel 6036Y
Stock or customized system: Stock.
Nextcloud app version:1.4.1

**Comment by mario** [comment]
Hello, thank you for the report. 

Manual upload fail is a known issue and we're working on it. cc @tobiasKaminsky 

As for uploads to the wrong server - I've heard of this issue, but unfortunately never had the time to properly test it out - I attempt to look into it for 1.4.2, but if not will be fixed in 1.5.0 for sure.

**Comment by mario** [comment]
Should be fixed in a build that will land tomorrow.

**Comment by mario** [comment]
This should be fixed in the beta build.

Please try:

https://github.com/nextcloud/android/raw/beta/apks/latest.apk

Thanks!

**Comment by mario** [comment]
There's a new beta on the same URL - please try.

**Comment by mrvanes** [comment]
I think it works as I expected now, but it took me a while to understand the new interface ;)
It's cool we can now differntiate not only per account, but also per local folder. Great job!!

**Comment by AndyScherzinger** [comment]
@mrvanes be aware though that the new auto upload has only been activated for Android 7 in the stable releases and will be activated for Android 5 & 6 in an upcoming feature release, most likely 1.5.0

**Comment by mrvanes** [comment]
One small remark: From a UXP point of view, there is little to no difference (other than a bit of whitespace) between the "Auto upload" widget and Setting but there's a world of difference since "Auto upload" is account specific and Settings is Global. Maybe a more visible divider or other visual clue may help out here...

**Comment by AndyScherzinger** [comment]
@jancborchardt  @eppfel what do you think about the divider remark?

**Comment by tobiasKaminsky** [comment]
please open a separate issue for this.
Closing this one as @mrvanes confirmed that it is working as expected.
Great job @mario
