### ISSUE TITLE
Improve web dav URL calculation

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#629]
### Actual behaviour
-  #401 fixed the web dav URL to be calculated as: ```/remote.php/dav``` but in a hard coded way

### Expected behaviour
- we should  use ```AccountUtils.getWebdavPath(AccountUtils.getServerVersion(account)``` while this one should then return ```/remote.php/dav``` instead of ```/remote.php/webdav``` for server versions >= 9
- This way the path works of Nc but still supports older versions of oC for app users that are running oC < 9 as their backend.

**Comment by mario** [comment]
I don't think it's that simple. Not all things work via /dav from what I've found :( even though I guess it should.

**Comment by joshtrichards** [comment]
The passage of time has nullified the need for backwards compatibility this deep AFAIK and the rest is covered in #8705.
