### ISSUE TITLE
MD/Text skips editor for synchronized files

### ISSUE THREAD

**Issue by Fmstrat** [nextcloud/android#6293]
### Steps to reproduce
1. Open Nextcloud app
2. Open an MD file
3. The editor comes up as expected
4. Close the file
5. Synchronize the file to the device
6. Open the file again
7. A viewer is displayed instead of the editor

### Expected behaviour
The editor should be accessible and the first view when tapping on a synced file when offline or online.

### Actual behaviour
See above

### Environment data
Android version: 10

Device model: S9+

Stock or customized system: stock

Nextcloud app version: 3.12.0

Nextcloud server version: Latest/na

Reverse proxy: nginx

**Comment by tobiasKaminsky** [comment]
You can click on options menu of this file and click "edit".

@jancborchardt I do get the UX problem…
What about having an "edit" FAB in lower right side like when displaying rich documents info?

Left: current view on downloaded md file 
Right: preview of rich document, with edit button
![2020-06-15-090458](https://user-images.githubusercontent.com/5836855/84627505-55e57180-aee7-11ea-89a3-d0998e439c1e.png) ![2020-06-15-090503](https://user-images.githubusercontent.com/5836855/84627503-554cdb00-aee7-11ea-9526-eea908b3932f.png)

**Comment by Fmstrat** [comment]
@tobiasKaminsky Thanks! And yes, I was aware of the menu/edit feature, I just didn't understand the differential between a downloaded or online file. It's a partial UX issue, but also a system issue as you can't bring up the editor in Airplane mode. It seems as if the app is trying to fetch the latest version on edit, but if it can't it won't let the editor load.

My personal belief is since it's a WYSIWYG editor, just like "Text" on the web UI the user should be brought directly to the editor screen, skipping the "display" since they look identical (other than dark mode) regardless of online status. Then, when the device goes back online it should sync the file as it would any other offline file. (Granted, I'm an N of 1)

**Comment by jancborchardt** [comment]
@tobiasKaminsky your proposal makes sense for when you are offline since then we have no access to the editor, and could show the "Open with" dialog when you click the edit icon (or load the editor when the connection resumed meanwhile).

Although when online, I would indeed also directly open in edit mode – that way no matter whether the file is downloaded or not, you get the editor immediately.

**Comment by Fmstrat** [comment]
@jancborchardt Is there a reason the editor can only be available online? (If it's due to sharing/etc, what about a partial editor for content?)

**Comment by AndyScherzinger** [comment]
> Is there a reason the editor can only be available online?

@Fmstrat because the editor _is_ online as in the client opens a webview with Nextclouds webUI itself, so the client has no editing capabilities today
