### ISSUE TITLE
Seperate SSO and file sync

### ISSUE THREAD

**Issue by varac** [nextcloud/android#6294]
### Is your feature request related to a problem? Please describe.

I'd like to *only* use the nextcloud deck app, without file sync.
Installing the file apps only to authenticate deck is too much of a burden because it will grant access of my smartphone to all my files stored in nextcloud, which I don't want to because of security concerns (I use the desktop files app but don't want my smartphone access the files).

### Describe the solution you'd like

Central SSO and file sync should get seperated. Make file sync in the current nextcloud android app optional (which would mean that it will only act as SSO provider for other nextcloud apps).

### Describe alternatives you've considered

SSO and file sync could be shipped by 2 different apps.

**Comment by varac** [comment]
From https://github.com/nextcloud/android/issues/2606#issuecomment-394351153:

> If you only want to have one app installed, then you do not need such "single account" system.
> If this then gets popular and there is need for a separate app, we still can do this.
> (or put it also in talk; as both are official apps and only official apps should serve as an account provider)

**Comment by stefan-niedermann** [comment]
I think this has been resolved by https://github.com/stefan-niedermann/nextcloud-deck/issues/527#issuecomment-646578344
