### ISSUE TITLE
App doesn't remember cloud connection

### ISSUE THREAD

**Issue by thalman** [nextcloud/android#63]
### Actual behaviour

-If mobile is restarted (I use planned switch-off/on during night) app asks for url, username and password
### Expected behaviour

-App should at least pre-fill last cloud URL and username or if it is not security issue save credentials and login automatically.
### Steps to reproduce
1. login into app
2. restart phone
3. start app
### Environment data

Android version: 4.2.1

Device model: evolveo strongphone

Nextcloud app version: 1.0.1

**Comment by tobiasKaminsky** [comment]
This is/was a problem also of ownCloud and was fixed by an additional app https://play.google.com/store/apps/details?id=com.owncloud.android.workaround.accounts
But as far as we understood this is only needed for paid apps.
You can try to use this app, but I am unsure wether this helps...

**Comment by thalman** [comment]
Thanks for hint, but unfortunately it doesn't work with nextcloud app. At least in my case.

**Comment by AndyScherzinger** [comment]
@thalman do you still experience this issue?

**Comment by thalman** [comment]
Yes I do. I see the nextcloud account created in the list of accounts (skype, google, nextcloud), but after restart it is gone.

**Comment by tobiasKaminsky** [comment]
@thalman  Is this still happening?

**Comment by thalman** [comment]
Yes, It is still there. Tested yesterday.

**Comment by tobiasKaminsky** [comment]
Strange behaviour...
You say the account disappears on "list of accounts", but can you still login within the app?

**Comment by thalman** [comment]
Good news, I find out that if I move app to "internal storage" it works well. If I have it in "internal device memory" it does not. I'm not sure about translation, my phone speaks different language.

**Comment by thalman** [comment]
@tobiasKaminsky, nono, I mean I have to "recreate" account and login. But the issue is somewhere else, see my previous comment.

**Comment by tobiasKaminsky** [comment]
So you have an internal storage and an external sdcard? Moving the app to the external storage leads to disappearing accounts?
How do you move the app? Is this a system option?

**Comment by thalman** [comment]
Yes, like this: Move app out of internal device memory, reboot phone => account settings is lost.

Moving apps is standard feature (Settings->Applications->Nextcloud, there is button "move ....")
This might help: https://developer.android.com/guide/topics/data/install-location.html

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky looking at chapter

> Applications That Should NOT Install on External Storage

It is obvious that the app should not be on external storage (while our data still can be...) simply because we basically this "check" for all the listed reasons described in that chapter...

**Comment by tobiasKaminsky** [comment]
Right, now I remember. In another issue I also discovered this as the cause...
But the question is how and why is our app itself allowed to be transferred to the external storage?
We do not have android:installLocation in it, so this should not be allowed.

It seems that some vendor just do not obey this setting and allow any app to be moved to external storage.
So I doubt we can do anything here? (at least a quick search did not reveal anything)
If someone comes up with a good idea how to prevent this, please reopen and reply.
