### ISSUE TITLE
Navigation drawer: align touch state with selected state

### ISSUE THREAD

**Issue by thgoebel** [nextcloud/android#6304]
### Steps to reproduce
1. Open navigation drawer
2. Press on any item

### Expected behaviour
- The touch state should cover the same area as the area highlighted by the selected item

### Actual behaviour
- The touch state is slightly bigger (has no margins) and no rounded corners

<img src=https://user-images.githubusercontent.com/33295590/84802222-908efd00-b000-11ea-8f60-dd6b10e2d9dd.jpg width=200>

### Can you reproduce this problem on https://try.nextcloud.com?

not a logic bug

### Environment data

Android version: 10

Device model: OnePlus 7

Stock or customized system: stock

Nextcloud app version: 2d6c25a

Nextcloud server version: 19.0.0

Reverse proxy: nginx 1.19

**Comment by thgoebel** [comment]
I looked around the code, and my first guess is that this could be achieved through the `NavigationView_itemBackground` attribute.

To get the margins and corner radius absolutely the same, it would be good to see how they are defined in the highlighting of the selected state. I failed to find the definitions thereof though - does this highlighting come straight from Material Components? Do the current touch states come from there as well? If yes, why does Google not make it nicer?!?

**Comment by AndyScherzinger** [comment]
@thgoebel like you guessed: this comes straight from the material components / theming and isn't changed by the app itself in any way. No idea why they did this, I guess it is unfinished / a bug in their implementation.

Cc @JorisBodin @Shagequi

**Comment by tobiasKaminsky** [comment]
I see three option
- change highlighted area to match selected state
- try to get it working (not sure if it is worth the effort / possible at all)
- keep it this way (as it is only temporary and even animated)

@jancborchardt

**Comment by thgoebel** [comment]
I guess keep it this way and wait/hope for the library to update it is the go-for option - I'm being really picky here anyway :)
