### ISSUE TITLE
Autoupload implementation doesn't sort older images into correct directories.

### ISSUE THREAD

**Issue by jasonbayton** [nextcloud/android#631]
From #630  

What I have noticed is it's not respecting the date of the whatsapp media. There are images from 03/2016 being uploaded to 02/2017 for example. Is it not set to interrogate image data on non-camera images?

![96305f8c-ec69-11e6-9de5-fa248bbf6503](https://cloud.githubusercontent.com/assets/3178412/22692491/44625dbc-ed37-11e6-8a5d-db90a2f7e300.png)

Is this simply a case of it finding the images today (yesterday) for the first time and uploading them to the corresponding directory for today's date? Is it supposed to be able to pick up the correct year/month based on file name or meta?

**Comment by tobiasKaminsky** [comment]
Yes. Currently the upload date is the date which is used for subfolders.
But there is #451 which should solve this and use the creation date instead of the upload date.

**Comment by mario** [comment]
You mean last_modified, not creation date, right @tobiasKaminsky ? :)

**Comment by tobiasKaminsky** [comment]
I am uncertain what the user would expect, if he takes an image on 31.1.2017, modifies it on 3.2.2017 (like cropping) and uploads it on 05.02.2017 via autoupload.
I personally would expect that is in january 2017 as it is the date where the image was taken.

**Comment by mario** [comment]
I don't think you can get creation date on Android, except from metadata, and again only JPGs will have that. So usually, last_modified date is used. (also, if auto upload is enabled on 5.2., images created/modified before that won't be uploaded).

**Comment by tobiasKaminsky** [comment]
Then, yes. This is also the way it is done in the PR on library https://github.com/nextcloud/android-library/pull/36

(in my scenario autoupload was enabled all the time, but only at 5.2. the file was uploaded via wlan; I know it is a strange scenario, but just wanted to create an artificial delay)

**Comment by mario** [comment]
@jasonbayton try the newest beta please.

**Comment by jasonbayton** [comment]
Oh do we have a possible implementation? 🥇 
Downloading now.

**Comment by tobiasKaminsky** [comment]
> @jasonbayton try the newest beta please

There is no new beta from 10.02 as the build was not working due to a wrong library merge, do not know who merged). So the latest ist 20170209, thus @jasonbayton you should not be able to see any difference ;-)

@mario do you have an idea why the settings are not stored / reset for @jasonbayton ?

**Comment by jasonbayton** [comment]
Indeed I didn't see anything different.

**Comment by mario** [comment]
What settings tobias?

**Comment by mario** [comment]
Yes, I think I fixed that bug :)

**Comment by jasonbayton** [comment]
Sorry @mario @tobiasKaminsky I have a habit of editing and naturally these aren't resent to inboxes :)

**Comment by mario** [comment]
Ah, so custom locations indeed reset? :-/

**Comment by mario** [comment]
Also, do images upload for deselected folders?

**Comment by jasonbayton** [comment]
> Ah, so custom locations indeed reset? :-/

On every update recently, yup.

> Also, do images upload for deselected folders?

No, I haven't seen that as yet.

**Comment by mario** [comment]
Did you, by any chance, remove the previous beta before installing the new one?
Or do you just install the new one over the old one?

**Comment by jasonbayton** [comment]
I generally only ever update directly over the previous version. That shouldn't cause issues though.

**Comment by mario** [comment]
The implementation uses preferences entry in order to check if it should clean "old" auto upload entries. If you remove the app, that preferences entry disappears too, so it would clean again.

But this doesn't look like to be the case with you :)

**Comment by mario** [comment]
OK, I just saw that my changes regarding this (and duplicate uploads) didn't go in the build. Should be there tomorrow.

**Comment by jasonbayton** [comment]
I'll pick it up in the morning, thank you :)

**Comment by tobiasKaminsky** [comment]
Beta is now up to date: https://github.com/nextcloud/android/blob/beta/apks/latest.apk

**Comment by jasonbayton** [comment]
I've had it installed most of today.

- Backup folders remained selected 
- App path has remained
- No wild uploads so far

Is there anything else I need to look out for?

**Comment by mario** [comment]
upload based on date?

**Comment by jasonbayton** [comment]
How does it work, scan and upload a folder and all its contents or just new files?

**Comment by tobiasKaminsky** [comment]
Upload based on date means that not the current upload date is used but the date when the file was last modified, e.g. you take an image on 31.01. and it gets uploaded on 01.02. Prior to the latest change it would be uploaded to 2017/02 as this was the upload date, but now it will get uploaded to 2017/01 as this is the creation date of the image (assuming you have enabled "use subfolder").

**Comment by tobiasKaminsky** [comment]
Rescanning an upload folder and upload the files that are missing is another feature which is wished, but not yet implemented.

**Comment by jasonbayton** [comment]
Perfect, just so I know what to expect. This sounds perfect :)

**Comment by mario** [comment]
I can do this easily, but that is one way sync - do we want that right niw?

**Comment by tobiasKaminsky** [comment]
I vote to keep the autoUpload as simple as possible and implement a real 2way sync soon, which then can also be limited by the user to a 1way sync (at least how I imagine it ;-) )

**Comment by jasonbayton** [comment]
I'm ok with that also.

**Comment by jasonbayton** [comment]
OK small update - it just tried to upload my entire watched folder, again, to the 2017/02 directory on the server. Luckily another recurring issue "App was terminated" stopped it.

So 
- it's still trying to push everything to this month's folder [1]
- it's still trying to upload duplicates of files that exist [1]
- whenever a new single file drops into the watched folder, it attempts to upload it multiple times [2]

[1]
![screenshot_20170212-103049](https://cloud.githubusercontent.com/assets/3178412/22861351/168eec8a-f10f-11e6-984f-03befcadd8b7.png)

[2]
![image](https://cloud.githubusercontent.com/assets/3178412/22861347/f90faf0a-f10e-11e6-88a0-b82c15137345.png)

Here, have a log (set to expire in a couple of days as it's got identifiable info in it):
https://cloud.bayton.org/s/dIHrmFtdKSMK3nV

It's from a few days ago, as that's the current, up-to-date output when I click on logs in settings.

Edit, it's going mad again: 
![screenshot_20170212-103049 1](https://cloud.githubusercontent.com/assets/3178412/22861410/02a7c56a-f110-11e6-826b-844bf9ba3176.png)

**Comment by mario** [comment]
You're free to delete the logs now - I have them. Gotta see what's happening, as I can't reproduce this with my branch atm :((

**Comment by mario** [comment]
Also, @tobiasKaminsky this sounds strange - didn't the timestamp fix fix the uploading to proper folders issue? Seems like not...

**Comment by jasonbayton** [comment]
If I can force it to generate logs I'll happily supply more.

**Comment by tobiasKaminsky** [comment]
> @jasonbayton it just tried to upload my entire watched folder

How do you do this? 
The timestamp fix is not for auto upload :/ I had it wrongly remembered. This fix "just" sets the upload date on the server to the last modification date and not to the current one.
Respecting and using the last modification date for "use subfolder" is something new :/
Sorry, my fault, I had a knot in my brain.
@mario I can develop this tomorrow if you like.

**Comment by mario** [comment]
Sure @tobiasKaminsky, but please do it in this branch.

**Comment by jasonbayton** [comment]
All I've done is set a directory to be uploaded via auto upload and chosen a custom directory. Everything else happening it's doing by itself.

**Comment by tobiasKaminsky** [comment]
> All I've done is set a directory to be uploaded via auto upload and chosen a custom directory. Everything else happening it's doing by itself.

But this does not led to uploading already uploaded files, or? (maybe I am just a little bit confused)

**Comment by tobiasKaminsky** [comment]
> Sure @tobiasKaminsky, but please do it in this branch.

@mario ok, I'll do it :)

**Comment by mario** [comment]
No it does not

**Comment by tobiasKaminsky** [comment]
But on https://github.com/nextcloud/android/issues/631#issuecomment-279209877 it seems as if there lots of lots of old images trying to be uploaded? (that is my confusion)

**Comment by mario** [comment]
That issue is unrelated. Please ignore and make sure uploads happen to the directory based on date modified. :)

**Comment by jasonbayton** [comment]
Oops, I've crossed issues.
The other one should probably be reopened.

**Comment by jasonbayton** [comment]
I'd say this _basically_ works now. Perhaps with the build today it'll stop confusing some images with the months they should be organised into, but for the most part it's working. I'll test the new build when it drops

**Comment by mario** [comment]
@jasonbayton if I understood our auto-build system properly, this should already be there so please try it :)
