### ISSUE TITLE
Folder that is shared with another user wolnt open

### ISSUE THREAD

**Issue by logan71f100** [nextcloud/android#6312]
### Steps to reproduce
1. Have a folder that is already shared with another user 
2. Try to open in app
3. Just sits and spins for over 20 mins and never loads 

### Expected behaviour
- should load the folder 

### Actual behaviour
- never loads 

### Environment data
Android version: 9

Device model: lg thin q 

Stock or customized system:root on factory software 

Nextcloud app version:20200617

Nextcloud server version:18.0.6

Reverse proxy:no

**Comment by tobiasKaminsky** [comment]
What kind of folder is this?
Can you open this folder via web?

**Comment by logan71f100** [comment]
Yes everything is fine on web version, but when I try to open on Android dev app it just spins. it has 3 sub folders not like it should be loading that much can the app dump a log?
________________________________

**Comment by logan71f100** [comment]
Never mind I guess, I added a file from the web interface to that folder and now it opened right up sorry to waist your time
________________________________
