### ISSUE TITLE
Select root folders for Autoupload

### ISSUE THREAD

**Issue by fdawans** [nextcloud/android#6315]
Would it be possible to add root folders to the autoupload system? 
It can be used to backup folders in the root directory (/) such as whatsapp databases for instance. 
![Screenshot_20200617-183844](https://user-images.githubusercontent.com/53601011/84925233-e67ba780-b0c9-11ea-987f-412d6028a705.jpg)

**Comment by AndyScherzinger** [comment]
@fdawans you can do that already buy navigation up the folder tree in the view of your screenshot (see the back arrow or the folder name drop down in the toolbar)

**Comment by fdawans** [comment]
I tried but it brings up the pop-up, it does not matter where I click, menu or arrow. 
Maybe I should give root permissions to Nextcloud. 
Thank you,

**Comment by AndyScherzinger** [comment]
@fdawans did you actually click on one of the marked elements?:
<img width="451" alt="1" src="https://user-images.githubusercontent.com/1315170/85015181-d4e8dd00-b167-11ea-9e80-68bd31ef29e8.png">

**Comment by AndyScherzinger** [comment]
Ah, wait, you are already on the "top level", because you can find WhatsApp right where you already are. ;) We don't go further up since we don't have read permissions there and it is unnecessary you seem to be rather looking for /0/WhatsApp/...

**Comment by fdawans** [comment]
Yes, you are right but those are the encrypted databases, I am looking for /data/data/com.whatsapp.
It also applies to other apps with data stored on the root partition. It would allow upload directly app data to Nextcloud for further analysis/backup.
So there is no 'root explorer' functionality built-in.

**Comment by AndyScherzinger** [comment]
> So there is no 'root explorer' functionality built-in.

No, rather the other way around if we don't have sufficient privileges regarding the target folder you try to navigate to then we show the location chooser while I am unsure if in your scenario a grant of right to the root folder would get to to navigate there within the app. Maybe @tobiasKaminsky has some more insights.
