### ISSUE TITLE
Continuous errors uploading files from unselected folders

### ISSUE THREAD

**Issue by ctodobom** [nextcloud/android#632]
### Actual behaviour
-After recent update from f-droid, many files was placed on upload queue, even files from folders that aren't activated on autoupload settings.

### Expected behaviour
-Correct upload of selected folders
 
### Steps to reproduce
1. Have a lot of files on Downloads and other folders that are disabled on autoupload
2. wait for the errors

### Environment data
Android version: 7.0

Device model: Motorola Moto Z Play (Moto Z Droid on US)

Stock or customized system: Stock

Nextcloud app version: 20170206 from f-droid

Nextcloud server version: 10.0

#### Error that constantly shows on the app

```
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Apps may not schedule more than 100 distinct jobs
 at android.os.Parcel.readException(Parcel.java:1691)
 at android.os.Parcel.readException(Parcel.java:1636)
 at android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:158)
 at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:42)
 at com.owncloud.android.services.FileAlterationMagicListener.onFileCreate(FileAlterationMagicListener.java:103)
 at org.apache.commons.io.monitor.FileAlterationObserver.doCreate(FileAlterationObserver.java:379)
 at org.apache.commons.io.monitor.FileAlterationObserver.checkAndNotify(FileAlterationObserver.java:345)
 at org.apache.commons.io.monitor.FileAlterationObserver.checkAndNotify(FileAlterationObserver.java:304)
 at org.apache.commons.io.monitor.FileAlterationMonitor.run(FileAlterationMonitor.java:182)
 at java.lang.Thread.run(Thread.java:761)

************ DEVICE INFORMATION ***********
Brand: motorola
Device: addison
Model: XT1635-02
Id: NPN25.137-15-2
Product: addison

************ FIRMWARE ************
SDK: 24
Release: 7.0
Incremental: 2```

**Comment by mario** [comment]
Hello,

thanks for the report, we're aware of the issue - this should be fixed in a (our) beta APK tomorrow, or the day after that in F-Droid.

Cheers!

**Comment by mario** [comment]
Try this apk please:

https://github.com/nextcloud/android/raw/beta/apks/latest.apk

**Comment by ctodobom** [comment]
I'm using f-droid version. I managed to stop the error removing and reinstalling. Version 20170211 looks that it is working well for me, but I can't tell if the original problem was solved. Hope anyone else with same issue that hasn't removed the app and reinstalled can check this.

**Comment by gyoda** [comment]
Can you link to the fix for this issue? Seeing this as well. Interested in how it is resolved.

**Comment by mario** [comment]
@gyoda https://github.com/nextcloud/android/raw/beta/apks/latest.apk - if you want to try it out. Just to be sure, remove the app and install this then.

**Comment by gyoda** [comment]
@mario Thanks for the link, and sorry for the confusion. I was interested in the code fix for this issue. Wondering how you got around a framework error like that one. Could you link to the checkin where this was fixed?

**Comment by mario** [comment]
We actually don't - this issue happened because of a bug in the code that created 100+ jobs in the first place.
