### ISSUE TITLE
Black primary color on Android dark theme

### ISSUE THREAD

**Issue by powerbitnet** [nextcloud/android#6323]
### Steps to reproduce
1. Choose black color on nextcloud website
2. Open Android nextcloud app
3.  Icons are black and very hardly to see 
3.1 Many buttons are hardly to see e.g. in auto upload config's remote folder 

### Expected behaviour
- on dark theme icons and buttons needs to be white 

### Actual behaviour
- icons and buttons are black and hard to see

**Comment by AndyScherzinger** [comment]
Thanks for the report @powerbitnet 

@tobiasKaminsky @JorisBodin @Shagequi @dan0xii 
this has mostly been fixed except for 
* active drawer menu item
* buttons of the contact backup screen
* FAB
* (maybe buttons for actions on activities, don't have any atm, so can't check)

**Comment by Shagequi** [comment]
I let you fix, because it's a very specific issue about one color. 
@AndyScherzinger for the next issues, I'd be happy to help you, but only if the issue globally impacts the app (not because of a specific color for a specific server) 

Thank you :D

**Comment by AndyScherzinger** [comment]
Thanks for the heads up @Shagequi, will do 👍

**Comment by dan0xii** [comment]
Will have a look today or tomorrow.

**Comment by tobiasKaminsky** [comment]
![2020-06-22-080445](https://user-images.githubusercontent.com/5836855/85253704-0ced6a00-b45f-11ea-907f-7b5e2d35914a.png) ![2020-06-22-080424](https://user-images.githubusercontent.com/5836855/85253706-0ced6a00-b45f-11ea-973f-a9b3652aeba5.png) ![2020-06-22-080419](https://user-images.githubusercontent.com/5836855/85253708-0d860080-b45f-11ea-8adb-2edf852ebc97.png)

For me this looks quite good on latest master, @AndyScherzinger ?
If so, then we just wait until 3.13, there is no need for backporting something to 3.12.1.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky you are using the light theme, just switch to the dark theme... 😅

**Comment by AndyScherzinger** [comment]
@dan0xii will open a PR with some issues fixed any time soon (some time today), so we can collaborate there or do fixes in several PRs. I'll add another edge case handling primaryColor method to theme utils btw.

**Comment by AndyScherzinger** [comment]
@dan0xii I opened #6332 for collaboration (and comments)

**Comment by AndyScherzinger** [comment]
fixes have been made via #6332, now ready for review (design approval has been done already). 🎉
