### ISSUE TITLE
When using "upload from camera", uploads failed due to exceeded quota can't be resumed, the image is lost

### ISSUE THREAD

**Issue by kartoffelkage** [nextcloud/android#6330]
### Steps to reproduce
1. Use a Nextcloud account that is using its full quota
2. Select "Upload from camera" in the Android app (I'm unsure about the exact name of the function in English, there's no obvious way to change localization in the app that I could find)
3. When the upload fails due to full quota, increase the quota or clear space on the account
4. Retry the upload

### Expected behaviour
The image should be uploaded when the account has sufficient space available

### Actual behaviour
The upload fails with "Local file not found". Presumably the temporary file was deleted before upload was verified.

### Can you reproduce this problem on https://try.nextcloud.com?
I'm trying to max out my quota, so far still uploading...

### Environment data
Android version:
9

Device model: 
Samsung Galaxy Note8 (SM-N950F)

Stock or customized system:
Stock

Nextcloud app version:
3.12.0

Nextcloud server version:
18.0.6

Reverse proxy:

#### Nextcloud log (data/nextcloud.log)
```
[webdav] Fatal: Sabre\DAV\Exception\InsufficientStorage: Insufficient space in /XXX/XXX, 7289498 required, 5103943 available at <<closure>>

 0. /var/www/nextcloud/apps/dav/lib/Connector/Sabre/QuotaPlugin.php line 137
    OCA\DAV\Connector\Sabre\QuotaPlugin->checkQuota("/XXX/XXX", 7289498)
 1. <<closure>>
    OCA\DAV\Connector\Sabre\QuotaPlugin->beforeMove("uploads/XXX/0 ... e", "files/XXX/XXX ... g")
 2. /var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
    call_user_func_array([OCA\DAV\Connect ... "], ["uploads/XXX/ ... "])
 3. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 633
    Sabre\Event\EventEmitter->emit("beforeMove", ["uploads/XXX/ ... "])
 4. <<closure>>
    Sabre\DAV\CorePlugin->httpMove(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
 5. /var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
    call_user_func_array([Sabre\DAV\CorePlugin {},"httpMove"], [Sabre\HTTP\Requ ... }])
 6. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 479
    Sabre\Event\EventEmitter->emit("method:MOVE", [Sabre\HTTP\Requ ... }])
 7. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 254
    Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
 8. /var/www/nextcloud/apps/dav/lib/Server.php line 319
    Sabre\DAV\Server->exec()
 9. /var/www/nextcloud/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
10. /var/www/nextcloud/remote.php line 165
    require_once("/var/www/nextcl ... p")

MOVE /remote.php/dav/uploads/XXX/02fd7b5569d7effb174671e7d8a3c22b/.file
from XXX.XXX.XXX.XXX by XXX at 2020-XX-XXTXX:XX:XX+XX:XX
```

**Comment by tobiasKaminsky** [comment]
>     2\. there's no obvious way to change localization in the app that I could find)

You have to change it within Android itself, but I understood it :)

The upload indeed should be resumeable.

**Comment by tobiasKaminsky** [comment]
I think this is now done via https://github.com/nextcloud/android/issues/4609
If not, please re-open.
