### ISSUE TITLE
Nextcloud locally deletes synced folder without reason

### ISSUE THREAD

**Issue by stephanritscher** [nextcloud/android#6334]
- ### Steps to reproduce
1. Sync a sub folder "/folder/sub" to your mobile.
2. Make changes to the folder remotely.
3. Use nextcloud app including visiting the synced folder and using Android file provider to open/edit files in this folder.
4. Repeat similar actions with bad/no connectivity.
(I didn't figure out what exactly triggered the issue, but encountered it repeatedly.)

### Expected behaviour
- All synced files remain on mobile device (in the original or an updated variant)

### Actual behaviour
- From time to time, all the synced files from the subfolder get deleted locally without apparent reason.
- From adb logcat and webserver log, I was able to see, that OfflineSyncJob was sending a PROPFIND for the path "/sub" instead of "/folder/sub".

### Environment data
Nextcloud app version:
3.13.0 Alpha 1
Nextcloud server version:
18.0.4

**Comment by Thovi98** [comment]
I've got this same issue a few times. The last one was this week.
I could'nt take logs unforrunatly...

Android 12L PixelExperience custom rom and the files were on sdcard

**Comment by joshtrichards** [comment]
Fixed in #6335
