### ISSUE TITLE
Icons of Account not loaded - Only Letter shown

### ISSUE THREAD

**Issue by jamfx** [nextcloud/android#635]
### Actual behaviour
If you log in in your App with the account you have online, the Icon is not showing up. Only the first Letter.

### Expected behaviour
-The letter should be replaced by the Icon from Account.
 
### Steps to reproduce
1. Create an account in your nextcloud and attach a personal photo or Icon attached to it.
2. If you log in on your server, your icon / logo is shown in nextcloud server
3. Log in on your device and check the icon. Only Letter visible

### Environment data
Android version:
Android 7.0 Patchlevel, 1. December 2016

Device model: 
Honor 8, no root
Nextcloud app version:
Latest Beta 20170208

Nextcloud server version:
11.0.0

**Comment by mario** [comment]
If you rotate your phone, does it appear? :)

**Comment by jamfx** [comment]
Sorry, close this. It just loaded. No rotation needed. Ah, sorry for disturbing... :(

**Comment by mario** [comment]
:)

**Comment by AndyScherzinger** [comment]
😀 Yeah they are loaded asynchronously 🚀

**Comment by jamfx** [comment]
Sorry, i just made a mistake. After renewing my NC I forgot to check if the icon is there. It was gone. So I just uploaded the Pic and it appeared immediately.  Stupid me. Sorry for bothering :)
