### ISSUE TITLE
TOTP Integration for Android APP

### ISSUE THREAD

**Issue by zmbcgn** [nextcloud/android#636]
### Actual behaviour
- I just installed the TOTP App from (https://apps.nextcloud.com/apps/twofactor_totp). Unfortunately I noticed that this feature is not supported by the Android App. Apps says "wrong login credentials"

### Expected behaviour
- Login with password and another popup with the required OTP submit prompt.
 
### Steps to reproduce
<opsolete>

### Environment data
Android version: 5.1.0

Device model:  Samsung Galaxy S4

Stock or customized system: Stock

Nextcloud app version:  1.4.1 

Nextcloud server version: 11.0.1

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

**Comment by mario** [comment]
Thank you for your bug report. Due to technical limitations, this cannot be implemented now - maybe later :)

For now you have to generate app codes inside settings to be able to login via mobile apps.

**Comment by zmbcgn** [comment]
Thats what I did. I generated 10 codes within my personal settings. when i'm inside the mobile app i use my username and one of the codes as password. That is not working..

**Comment by zmbcgn** [comment]
Oh. Sorry. I confused TOTP backup codes with app codes.

**Comment by mario** [comment]
:)

**Comment by zmbcgn** [comment]
Works like a charm.
