### ISSUE TITLE
Follow up on "hide on scrolling"

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#6360]
I have tested the PR and have found two issues:
* [x] #6569 The part below the header bar looks strange in dark mode: different grey tone?
* [ ] The FAB button seems to need a long touch time to get hidden/shown. If I scroll fast (and thus touch short to trigger the scrolling), I can trigger a state where the FAB button doesn't get hidden/shown while scrolling.
* [x] The FAB button and the sorting/grid/list action bar are visible in the Text preview screen (and possible others as well)
* [ ] The empty list elements aren't vertically centered anymore (might be to to the parent element PR, can't say for sure).
* [x] header is scrolled down:
 - open app
 - scroll down, and up so header is gone
 - go into subfolder / detail view
 - header is gone (as this state is remembered)

_Originally posted by @szaimen in https://github.com/nextcloud/android/pull/6262#issuecomment-648956174_

**Screenshots**
![com nextcloud client FileDisplayActivityIT_open](https://user-images.githubusercontent.com/1315170/85758720-ddfe1f00-b710-11ea-95bd-9f6a3deae43d.png)
![com owncloud android ui preview PreviewTextFileFragmentTest_displayJavaSnippetFile](https://user-images.githubusercontent.com/1315170/85758724-de96b580-b710-11ea-9c2d-64f5e2ab49f2.png)

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky I added further issues I found to the list

**Comment by tobiasKaminsky** [comment]
>  The FAB button seems to need a long touch time to get hidden/shown. If I scroll fast (and thus touch short to trigger the scrolling), I can trigger a state where the FAB button doesn't get hidden/shown while scrolling.

Is this still valid?

**Comment by szaimen** [comment]
> > The FAB button seems to need a long touch time to get hidden/shown. If I scroll fast (and thus touch short to trigger the scrolling), I can trigger a state where the FAB button doesn't get hidden/shown while scrolling.
> 
> Is this still valid?

On 3.13.0 it is, yes 👍

**Comment by tobiasKaminsky** [comment]
I cannot reproduce it.
If it is still valid, please re-open with a video.

**Comment by szaimen** [comment]
Here is a screenrecording:
[Screen_Recording_20200924-101039.zip](https://github.com/nextcloud/android/files/5274470/Screen_Recording_20200924-101039.zip)
(You have to touch really short during scrolling to trigger this but it definitely still happens)

**Comment by tobiasKaminsky** [comment]
For me it is shown once the search bar is open fully.

This was introduced by @JorisBodin https://github.com/nextcloud/android/commit/adecd7b5ae95972a0259eebf665a035a10e48073

Maybe you can help us here? 💙

**Comment by JorisBodin** [comment]
This is a feature of the google lib. So actually make the effect fail. You can remove the option if it's really problematic :)

**Comment by tobiasKaminsky** [comment]
>  can remove the option

You mean removing entire "hide FAB on scrolling"? 
I am not keen on doing this…

**Comment by tobiasKaminsky** [comment]
> (You have to touch really short during scrolling to trigger this but it definitely still happens)

Hm. I tried many different devices, but I cannot reproduce it :S
Does this also happen if you have more entries to scroll upwards to?

**Comment by szaimen** [comment]
I think I've located the problem:
It seems like while scrolling down the FAB only hides after the top-bar is completely hidden.
The other way around: if I scroll up, the FAB gets only visible after the top-bar is fully visible again.
I think synchronizing the animation; for scrolling down: hiding the FAB while the top-bar gets hidden and not after it is hidden and for scrolling up: making the FAB visible while the top-bar gets visible and not after it is visible would solve all problems.
Do you get what I mean?

**Comment by tobiasKaminsky** [comment]
@szaimen thanks for the detailed info.

@JorisBodin do you see any chance that we can change this behavior as described?

**Comment by tobiasKaminsky** [comment]
>     * The empty list elements aren't vertically centered anymore (might be to to the parent element PR, can't say for sure).


This is fixed.

**Comment by tobiasKaminsky** [comment]
The other thing:
I played around a bit, but all other solutions er even more strange, e.g.: if you swipe up/down a tiny bit it directly shows/hides header, which makes it feel like an overlay.

I fear that we have to live with this situation.
