### ISSUE TITLE
Icon of the text file in the dev version

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/android#6369]
The text file icon has a black background, which looks strange in a light theme.

![obraz](https://user-images.githubusercontent.com/47037905/85843183-22d19680-b7a1-11ea-8fd6-050eda38b4b0.png)

However, in a dark theme it is hardly visible.

![obraz](https://user-images.githubusercontent.com/47037905/85843314-47c60980-b7a1-11ea-9bf6-fc22a5df5d1f.png)

### Environment data
Android version: 10

Nextcloud app version: dev 20200626

**Comment by AndyScherzinger** [comment]
pinging @nextcloud/server-triage since afaik the client "just displays" the thumbail for the text file retrieved from the server. So this would then be rather a server-side issue.

@Valdnet what is your server version?

**Comment by Valdnet** [comment]
@AndyScherzinger My server version is 19.0.0.

**Comment by AndyScherzinger** [comment]
> I think this is not on the server side, because in version 3.12.0 everything is fine, and the connection is also from 19.0.0.

Hard to tell, I run Nc19, Android 10, app-master and don't have this issue :/

**Comment by Valdnet** [comment]
@AndyScherzinger In the dev 20200625 version the txt file is displayed correctly. This has been happening since the last dev 20200626 version.

**Comment by Valdnet** [comment]
@AndyScherzinger I have reinstalled the application well and now the txt file is displayed correctly. I think the issue can be closed. Thanks for your input.
