### ISSUE TITLE
Feature request: Select all (particularly in search)

### ISSUE THREAD

**Issue by jasonbayton** [nextcloud/android#637]
It would be useful to, on searching for a selection of files by a certain criteria, select the 3 dots menu and tap "Select all". Currently the requirement to long tap + tap each file to be selected is not a quick and simple process, particularly when dealing with a large number of files.

PR: #1196

**Comment by mario** [comment]
Like the idea. I'll do that once I start working on search. (1.5.0). 

@AndyScherzinger @tobiasKaminsky confirm please.

**Comment by tobiasKaminsky** [comment]
Good idea.
Select all (and deselect all) is already implemented in the upload view (where you can upload local files stored on the device), so this should be really simple 👍

**Comment by AndyScherzinger** [comment]
Yes, ggod idea 👍

**Comment by jsrck** [comment]
Hi! As I'm new here I tried to implement this starter issue and created a pull request.
https://github.com/nextcloud/android/pull/1196
I'm not sure if I did the merge / pull request correctly. Please let me know, if not. This is my first time working on GitHub (So far I used SVN).
As far as I know, the next step would be a code review, correct?

**Comment by AndyScherzinger** [comment]
@jsrck that's correct :) Thanks for your contribution! I labelled the PR to review 👍

**Comment by OlivierS1** [comment]
Tried the new feature on the top level of my account. It selected 220 objects in about 5 seconds.
Tried to unselect them all, and it took an excess of 30 seconds.

Feature is nice, but when folders are present along with the files, everything gets selected (this is expected) but would it be possible to list how many folders and how many files are part of the selection.
The number of items selected is already available.
I think it should be something to explore as it would be too easy to just say, I have only files in the selection and decide to delete them, along with the folders and whatever it contains.

**Comment by AndyScherzinger** [comment]
merged for 1.5.0

@OlivierS1 would you mind opening a new issue for you proposal since it extends beyond the original description of the issue? :)
