### ISSUE TITLE
Extremely slow upload speed when using Android app (1.4.1), with latest Nextcloud (11.0.1) release

### ISSUE THREAD

**Issue by Drag0nFly** [nextcloud/android#640]
### Actual behaviour
All uploads performed from within the Android app are insanely slow when compared to doing the exact same operation from within a browser (also on Android, from the same network and using the same file)

Typically it takes around 10 minutes to upload a 5Gb file from our company network into the recently-established Nextcloud instance. From the Android app, however, this was left running for approx. 30 minutes, resulting in numerous chunks of files, consisting of 1Mb each, being left in the ../cache directory for the user and only made it to around 340Mb during this time before the upload was terminated. The files had to be manually removed on the server-side after cancelling the upload in the App. It appears that the connection is re-initiated for every 1Mb chunk, causing the slowdown.

This flaw makes the Android app completely unusable for this purpose; and the users are forced to use the regular web frontend instead.

### Expected behaviour
Uploads from within the app should perform the same as when done from within a browser (on the same device, and on the same WiFi network)

I would really like to see an option to remove this chunk-upload behaviour, as this does not occur when uploading from a browser, which places the uploaded file(s) into temporary files suffixed with ocTransferId<$transferid>.part on the correct location and bypasses the ../cache dir altogether.

From looking at previous tickets (last activity on Oct 2016) it appears that a temporary workaround was done to increase the chunk-size from 1 to 8-10Mb, but this does not seem to have made it into the release/stable branch yet. Nevertheless it should not need to chunk the files unless under very special circumstances, as we've not experienced issues when testing various hot-spots and uploading large(ish) files without issues.

### Steps to reproduce
1. Open Nextcloud Android app 
2. Select a file of 2Gb or larger size
3. Perform an upload and watch the uploading user's cache directory being flooded with "-chunking-nnnnnnnnn-nn" files of 1000Kb each while enjoying the upload speed of a 28.8kbps modem. ;)

### Environment data
Android version: 6.0.1 Multiple Android versions also tested.

Device model:  Sony Z3C (D5803). Multiple devices also tested.

Stock or customized system: n/a

Nextcloud app version: 1.4.1

Nextcloud server version: 11.0.1

### Logs

Apache error log is empty. 

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
No logfile is produced in data/nextcloud.log

**Comment by mario** [comment]
WIll be fixed in 1.5, sorry about that :(

**Comment by Drag0nFly** [comment]
@mario: ok - thanks for the acknowledgement. Hopefully 1.5 is not far away!

**Comment by mario** [comment]
@Drag0nFly first comes 1.4.2, and then 1.5.0. If it becomes too much wait, we'll release 1.4.3 :)

**Comment by AndyScherzinger** [comment]
@mario see also https://github.com/nextcloud/android/issues/348 and https://github.com/nextcloud/android/issues/329

**Comment by tobiasKaminsky** [comment]
@mario do you have a good idea how to improve this?
(also we decided not to assign milestones)

**Comment by mario** [comment]
Removing milestone. I need our policy in writing :P But first you need to comment on the process issue :)

Yup, I have a pretty good idea - we'll see if it works :D

**Comment by tobiasKaminsky** [comment]
> Yup, I have a pretty good idea - we'll see if it works :D

I guess it is better for time/coding trade-off to first discuss the idea.

**Comment by tobiasKaminsky** [comment]
@mario are you still up on this?

**Comment by mario** [comment]
@tobiasKaminsky yes, but it depends on my time if it'll be in 1.5 or not.

**Comment by tobiasKaminsky** [comment]
Just asked as you have unassigned you.
