### ISSUE TITLE
Sync remote folder to custom local folder

### ISSUE THREAD

**Issue by AlexVerrico** [nextcloud/android#6407]
### Is your feature request related to a problem? Please describe.
It's not ideal how the app only lets you sync a remote folder to its corresponding location in the chosen data folder, rather than being able to choose a particular folder on the device. For example, I store my music in a folder on my nextcloud server, but when I sync that folder, I have to use a third party music app so that I can manually add the nextcloud data directory as a media source.

### Describe the solution you'd like
I think that an ideal solution would be allowing the user to choose where to sync each folder, rather than just offering three choices of locations to mirror the remote directory structure to.

**Comment by tobiasKaminsky** [comment]
Downloaded audio files should be directly visible via Androids media library.
Syncing to any local folder is not possible and will be even more restricted with Android 11, please see "scoped storage" for further infos.

**Comment by AlexVerrico** [comment]
Hi @tobiasKaminsky 
Thanks for replying with a reason, rather than just telling me that it can't be done, like many developers on other projects would.
I can see why the app behaves how it does now, and understand that what I suggested is impractical to implement, therefore, I will close this issue.
Cheers,
Alex.

**Comment by AlexVerrico** [comment]
For anyone who stumbles across this issue in # the future, here is a good article explaining scoped storage: https://www.androidcentral.com/what-scoped-storage
