### ISSUE TITLE
All files shows "No files here" until manual refresh

### ISSUE THREAD

**Issue by mohasi** [nextcloud/android#6409]
### Steps to reproduce
1. Have some photos in cloud
2. Select "photos" from hamburger menu
3. Then click "all files"
4. It spins around a bit and says "No files here"
5. Pull down gesture to reload, and your files are now visible.

### Expected behaviour
When navigating to "All Files", the files should show first time.

### Actual behaviour
When navigating to "All Files", it says "No files here" until you refresh manually.

### Environment data
Android version: 10
Device model: lavender
Stock or customized system: Lineage OS 17.1
Nextcloud app version: 3.12.0
Nextcloud server version: 18.0.6

**Comment by tobiasKaminsky** [comment]
Have you waited after step 2 to see the photos?

**Comment by mohasi** [comment]
@tobiasKaminsky as mentioned in the other possibly related bugs, the thumbnails load after step 2, the spinner carries on, then I do step 3 (click all files).

**Comment by tobiasKaminsky** [comment]
Can you also post here please some screenshots to better understand the problem?

**Comment by mohasi** [comment]
Not sure how this screenshot will help more than the steps I already mentioned, but here you go:

![Screenshot_20200723-225916_Nextcloud](https://user-images.githubusercontent.com/47725053/88343104-887d5800-cd38-11ea-82c1-7bbd7575c486.png)

So, I have 11 images in "Photos", after displaying the thumbnails of them almost immediately the spinner keeps going forever.

**Comment by tobiasKaminsky** [comment]
Ok, and there are no more than these 11 images on your server?
So the result is correct, but only the misleading spinner is the problem?

**Comment by AndyScherzinger** [comment]
> So the result is correct, but only the misleading spinner is the problem?

Yes, so is my understanding too and I remember other users reporting this exact scenario.
