### ISSUE TITLE
beta20170209 can't connect

### ISSUE THREAD

**Issue by JSoko** [nextcloud/android#641]
### Actual behaviour
-deinstall beta 20170208
- install beta 20170209
- enter NC-URl
- enter credentials
Can't connect to server
The server needs to long for an answer (Der Server braucht zu lange für eine Antwort)

revert to 20170208 and it works as expected...

### Expected behaviour
-should connect to nextcloud
 
### Steps to reproduce
see above

### Environment data
Android version: 7.0

Device model: 
sgs7
Stock or customized system:
stock
Nextcloud app version:
20170209
Nextcloud server version:
11.01.
#### Nextcloud log (data/nextcloud.log)
nothing related

**Comment by mario** [comment]
The problem is nobody touched this part of code :(

@AndyScherzinger @tobiasKaminsky ?

**Comment by JSoko** [comment]
I was astonished about that and so I tried twice before reporting...
deinstalling 0209 and reinstalling 0208 fixes...

**Comment by AndyScherzinger** [comment]
@mario no clue to be honest and no, we did not change anything there... ?!

**Comment by JSoko** [comment]
Tried again and can reproduce it, **BUT** it seems to have something to do with my local Network. If I try it over umts, it works...
...will test a little bit more and come back here.

**Comment by JSoko** [comment]
mirical:
In local W-Lan i could connect to my nextcloud with 20170208, browser, caldav-sync, card-dav-sync and OwncloudNewsreader, but not with the 20170209...

Switched off ipv6 and restarted routers, now it works...

**Comment by AndyScherzinger** [comment]
Ah, yes. The client is not IPv6 ready :(

**Comment by mario** [comment]
@AndyScherzinger what needs going?

**Comment by AndyScherzinger** [comment]
To be honest, I don't know because I never investigated what we would need to do to implement IPv6 and I also don't know if this might also be related to the used http client...
So the first thing would be researching the root cause / steps that need to be taken...
