### ISSUE TITLE
Quickly changing between Photos to All files causes UI mismatch

### ISSUE THREAD

**Issue by mohasi** [nextcloud/android#6411]
### Steps to reproduce
1. Have some photos in cloud
2. Select "photos" from hamburger menu
3. Quickly select "All Files"

### Expected behaviour
The selected item should change to "All Files" as well as the page.

### Actual behaviour
The selected item stays as "Photos" but page changes to "All Files"

### Environment data
Android version: 10
Device model: lavender
Stock or customized system: Lineage OS 17.1
Nextcloud app version: 3.12.0
Nextcloud server version: 18.0.6

**Comment by tobiasKaminsky** [comment]
Related to your other issues.
I assume that photo query is not finished as the server is responding too slow.
Can you wait until photo is loaded and try again?

**Comment by mohasi** [comment]
@tobiasKaminsky Unfortunately the photo spinner never finishes, even though all the thumbnails are displayed fine.

**Comment by tobiasKaminsky** [comment]
Can you post a screenshot please?

**Comment by mohasi** [comment]
@tobiasKaminsky You cannot really capture this in a screenshot, if I take a screenshot of the burger menu then you still have no idea its incorrect until you also collapse it and see that the main view is not the same.

**Comment by tobiasKaminsky** [comment]
Isn't this the same as #6409?
