### ISSUE TITLE
show share accept notification in app

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/android#6418]
This notifications are not show in android:
![grafik](https://user-images.githubusercontent.com/24530680/86592148-30ea9880-bf93-11ea-93ec-173b561b6f2d.png)

**Comment by tobiasKaminsky** [comment]
It should be shown in Notifications. 
Also it should be shown as push notification, so that you get an info in notification bar of Android.
Can you check if you see some error message in "Notifications"?

**Comment by jakobroehrl** [comment]
OK, that's right. If I tip on notifications I see:
![Screenshot_20200708-073221_1](https://user-images.githubusercontent.com/24530680/86880715-60151d00-c0ed-11ea-9aed-20a318d5c0fa.jpg)

But there is no push notification. All other push notifications I get

**Comment by tobiasKaminsky** [comment]
Ah. This is in internal share, right?
Then there is no push notification for this.
Push notifications are only for federated share.

@nextcloud/server-triage this is indeed a bit strangex

**Comment by nickvergessen** [comment]
When you see it online there was a push for it. Everything in the notifications block was pushed

**Comment by tobiasKaminsky** [comment]
> But there is no push notification. All other push notifications I get

Strange, then this must be a temporary fault on clients app side…?

**Comment by nickvergessen** [comment]
yeah could be many things:
temporary connection issue between cloud and push proxy, push proxy and google/apple, google/apple and your phone, ...

**Comment by jakobroehrl** [comment]
Tested on other phones: It's working properly. 
I think we could close this issue.

**Comment by jakobroehrl** [comment]
Sorry, I have to reopen this issue.
I have exact the same problem with 2 phones. 
All other notifications are shown.

**Comment by jakobroehrl** [comment]
@tobiasKaminsky 
Tested again. 
I could solve it, with reinstalling the app.
