### ISSUE TITLE
Make User info editable

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#642]
Just had a nice chat with @AndyScherzinger and we came up with the idea that the user info should be editable in the app, so that the new values are stored on the server.

**Comment by mario** [comment]
That's all good, but maybe for one of the future versions. :)

**Comment by tobiasKaminsky** [comment]
Of course. Just as a reminder that we do not forget it :)

**Comment by AndyScherzinger** [comment]
👍

**Comment by szaimen** [comment]
Duplicate of #1925
