### ISSUE TITLE
Placement of "Copy link" in share view

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/android#6427]
Currently it looks like this:
![](https://user-images.githubusercontent.com/5836855/86581920-17d8ec00-bf81-11ea-99ca-dc9bcc4e2731.png)

It would be nicer if the copy icon would just be left next to the 3-dot icon, no? @tobiasKaminsky @AndyScherzinger 

Additionally we could see to add the text "Copy" to the icon to make it more obvious. Maybe only though if there’s no custom link text set via https://github.com/nextcloud/server/pull/21357 as otherwise there might be lack of space for the text.

**Comment by AndyScherzinger** [comment]
> It would be nicer if the copy icon would just be left next to the 3-dot icon, no?

sure thing

> Additionally we could see to add the text "Copy" to the icon to make it more obvious. Maybe only though if there’s no custom link text set via nextcloud/server#21357 as otherwise there might be lack of space for the text.

not sure about this one. You mean adding "copy" to the right of the copy-icon?
So this would be: ```"link icon" Share link "copy icon" Copy "3-dot icon"```
This might be a bit crowded, no?

Also the mix between links with custom text and links without it might look "unaligned"
<img width="177" alt="Copy_link" src="https://user-images.githubusercontent.com/1315170/86786021-bc335f00-c063-11ea-89af-564485c2ac02.png">

What do you think @jancborchardt ?

**Comment by jancborchardt** [comment]
@AndyScherzinger yeah, I was thinking either it shows a label for all or for none. It could show a label for all links unless there is at least 1 link with a custom label? It’s kind of a "learnable UI" as when you already know how to set a custom label, you also probably know that the button there is for copying?

**Comment by tobiasKaminsky** [comment]
> It would be nicer if the copy icon would just be left next to the 3-dot icon, no? @tobiasKaminsky @AndyScherzinger

I already changed this and it will be in my next PR for share enhancement.

**Comment by tobiasKaminsky** [comment]
> @AndyScherzinger yeah, I was thinking either it shows a label for all or for none, no mixing. It could show a label for all links unless there is at least 1 link with a custom label? It’s kind of a "learnable UI" as when you already know how to set a custom label, you also probably know that the button there is for copying?

Let us do not over-complicate and over-engineer things here please…
- self learning UI needs to be created…this is totally easy said in 1-2 sentences, but not feasible in the same time.
- we do not show text representation on other "self explaining" icons, e.g. grid vs list view
- server UI also does not have it (goal of my PR is to have it as close as possible to server…)
- this icon is so well known…and if one does not know it, click on it and a message "link copied to your clipboard" appears"

**Comment by jancborchardt** [comment]
@tobiasKaminsky sure, good call – the placement fix will already make it look much nicer. :)

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky labeled it "PR exists" since you covered the alignment issue already 👍
