### ISSUE TITLE
Changes to file does not update list

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#6428]
### Steps to reproduce
1. open app
2. add/remove file from favorites
3. list is not updating

same for
- rename

### Expected behaviour
- list should update

### Actual behaviour
- list is not updating

**Comment by willpyshan13** [comment]
hello, i want to know when does this bug be resloved?

**Comment by tobiasKaminsky** [comment]
Seems to be already fixed, at least I tried it on latest version.
