### ISSUE TITLE
Remove title theming of modal dialog

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#6429]
Looping in @nextcloud/designers @jancborchardt @tobiasKaminsky @JorisBodin @Shagequi 

Looking at https://material.io/components/dialogs - dialogs don't do any special theming for modal dialog titles in contrast to our Android client which tints the title using the primary color. This is also don for the (border-less) buttons (the later being fine and in alignment with material design guidelines).

So I propose that we drop the dialog title tinting (which today's makes them look like the dialog buttons except for the font size...)

What do you think? I think it'll help with the new look to be introduced with the next release and support its visual cornerstones.

**Comment by jancborchardt** [comment]
Sure thing, let’s just remove the tinting. :)

**Comment by tobiasKaminsky** [comment]
Sure :-)
