### ISSUE TITLE
Autoupload does not work

### ISSUE THREAD

**Issue by gsantner** [nextcloud/android#643]
### Actual behaviour
- Autoupload doesn't work at all

### Expected behaviour
- Autoupload should work
 
### Steps to reproduce
1. Enable autoupload for any picture folder
2. Create / add photos to folder
3. See that app didn't upload anything

I enabled the settings below for pretty much every picture directory, e.g. Screenshots, Camera/DCIM, 9GAG. But neither of them are working. Doesn't matter if I take photo with camera, or make an screenshot. Nothing gets uploaded. I also don't get any notification for an upload try, and don't get an message in the upload view. The nextcloud app also definitely has (M-)Permissions granted to access those files.
Note that manual upload of files, and sharing files into the app works. At least for camera directory OwnCloud Instant Upload worked, with this one not even camera.
I tried it on 3 devices now and instant upload doesn't work on any of those devices.

I tried to get an logcat (`adb logcat -s com.nextcloud.client`) but there seems to be no logcat output, and no option to share error logs from the app (maybe another suggestion/feature).

![screenshot_20170210-171631](https://cloud.githubusercontent.com/assets/6735650/22834466/80d466de-efb5-11e6-8c66-237f725fb6c7.png)
![screenshot_20170210-171655](https://cloud.githubusercontent.com/assets/6735650/22834479/8d6640f2-efb5-11e6-8b9e-e18a3ede2611.png)

### Environment data
Android version: Nougat 7.1.1, Marshmallow

Device model: Nexus 5, Moto G2

Stock or customized system: LOS 14.1, CM13

Nextcloud app version: 1.4.1 - F-Droid

Nextcloud server version: 11.0.1

#### Web server error log
No server error, because app didn't even try to upload.

#### Nextcloud log (data/nextcloud.log)
No server error, because app didn't even try to upload.

**Comment by mario** [comment]
Can you try the f-droid beta please? :)

**Comment by gsantner** [comment]
@mario 
Tried Nextcloud beta some weeks ago, but there were the same issue.
Trying now new beta.

**Comment by mario** [comment]
Thanks:)

**Comment by gsantner** [comment]
Thank you! ;)

**Comment by mario** [comment]
So it works? :)
