### ISSUE TITLE
Use themed color during login

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#6432]
- login to a themed server
- see this (extreme example):
![2020-07-08-092852](https://user-images.githubusercontent.com/5836855/86890364-7d51e780-c0fd-11ea-81dd-6aefbf4f3732.png)

Color is exposed via capabilities, so we should use this.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky you mean for system and navigation bar?

**Comment by tobiasKaminsky** [comment]
Yes. This should be temporary used, as otherwise this looks really ugly.

**Comment by tobiasKaminsky** [comment]
So far so good…
Is there some code for changing navigation bar already?

![2020-07-08-152229](https://user-images.githubusercontent.com/5836855/86923827-d8e89900-c12e-11ea-9a47-44ed788da344.png)

**Comment by tobiasKaminsky** [comment]
![output](https://user-images.githubusercontent.com/5836855/86925503-4269a700-c131-11ea-815c-e0468f3f65dd.gif)
