### ISSUE TITLE
Preview View shows Sorting/grid/list element and FAB while it shouldn't

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#6437]
See screenshot, beware that the same applies for the details view
![1](https://user-images.githubusercontent.com/1315170/86945217-1823e380-c149-11ea-9c47-71cfe0e7eee3.png)

cc @tobiasKaminsky @JorisBodin @Shagequi 

💡 I guess it is due to #6262 ... but that is just a guess

**->** IMHO we should not release 3.13.0 without having this matter fixed

**Comment by tobiasKaminsky** [comment]
I had to change toolbar and FAB to get this scrolling to work.
FAB is now again bound to FDA.
Toolbar has now the sort/list group, but it is set to visibility=gone, but enabled for FDA.
As PreviewTextFragment is in FDA it still shows it.
