### ISSUE TITLE
Auto upload doesn't work on Android for already uploaded photos.

### ISSUE THREAD

**Issue by BGrard** [nextcloud/android#6443]
### Prerequisites: 
I use Nextcloud on my Android phone to backup the photo I take. After some change in the settings, the old files are not upoaded again.
Android app is in the latest version : 3.12.1
And the server version is 18.0.4

### Steps to reproduce
1. In Android app, activate the auto upload of a folder. Then wait for the folder content upload to finish. 
2. Then change the settings of the auto upload to chose a new destination folder.

### Expected behaviour
I expected to see the whole folder uploaded in the new folder.

### Actual behaviour
Only the files that are created afterwards are uploaded even though the check mark "Upload existing files" is checked.

### Server configuration

**Operating system:**  Android 10

**Web server:** Nextcloud running on docker on a Debian server in 10.4

**Database:** Mysql

**Nextcloud version:** 18.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:** From the docker image.

**Comment by AndyScherzinger** [comment]
looping in @tobiasKaminsky @ArisuOngaku @jancborchardt AFAIK this is "by design", changing the server/target location won't trigger another upload of existing images (since we already uploaded them).

IMHO the files would have to be moved to the new location (manually by the user) and then one can change the location.

So for me this is a "won't fix", right?

**Comment by tleydxdy** [comment]
I have a problem where when I set up auto upload, it created a new folder which I don't want, so I canceled the uploads and set up the destination, but now I can't make it upload missing pictures again.

**Comment by ArisuOngaku** [comment]
@AndyScherzinger exactly. Already uploaded files would have to be moved by the user if they want so.

However if you really want to reupload everything, you should be able to simply delete the auto upload folder config and recreate it (maybe you can try to disable/re-enable first, but I have never tested that).

**Comment by Shagequi** [comment]
@ArisuOngaku Hi, the deletion doesn't trigger the upload of old files 😅 I think it's more like a bug.

**Comment by Shagequi** [comment]
@tobiasKaminsky Have you seen this problem ?

**Comment by ArisuOngaku** [comment]
Imho, that is more of a design question.

I thought of 3 alternatives:
- Remove all db entries for the files that where uploaded with an auto-upload config when it is deleted/disabled
- A "force reupload all" button on each auto-upload config
- A general "force reupload all"

**Comment by JorisBodin** [comment]
@ArisuOngaku 
I vote for the second option

**Comment by tobiasKaminsky** [comment]
I fail to find a reason to re-upload everything again?

But if we need it, it should be sub-entry below "also upload existing files", which is only visible if the setting is checked:
"Force re-upload of existing files" as check mark, which is triggered once it is saved.

What do you think?
