### ISSUE TITLE
NC19: Internal Links won't open the Android App any more

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/android#6444]
This function doesn't work with NC19: https://github.com/nextcloud/android/pull/5345
Links are opened in the mobile browser
Tested with the same smartphone. It works with NC18.0.44 but not with NC19.0.0

### Steps to reproduce
1. tip on an internal link
2. the browser opens

### Expected behaviour
The android app should open

**Comment by AndyScherzinger** [comment]
@jakobroehrl which version of the Android client are you using?

Looping in @ezaquarii and @szaimen who recently worked on this feature (not yet released though)

@kesselb if it works with Nc18 and doesn't with Nc19 it could also be the server that breaks this feature ;) So let's see cc @tobiasKaminsky

**Comment by szaimen** [comment]
@jakobroehrl 
What is the Nextcloud Android App version you are using? And what does the link looks like? Could you provide an example link? (Just change the domain to e.g. example.com if you don't want to publish your domain)

**Comment by jakobroehrl** [comment]
Thanks for taking care.
Not working: https://<server19>/f/343591
Working:       https://<server18>/index.php/f/137930

"index.php" is missing in the interal link generation. If I add it manually the link opens in the Android App again. 
3.12.1 is the version

**Comment by szaimen** [comment]
This was already resolved with #6121 and will ship with version 3.13.

**Comment by jakobroehrl** [comment]
@szaimen 
Super! But why is it working with the 3.12.1 Version under NC18 and NC19 not?

**Comment by szaimen** [comment]
I cannot say for sure but I guess it worked with NC18 because internal links on NC18 contained the `index.php` part on your Nextcloud instance and on NC19 not.

**Comment by jakobroehrl** [comment]
Figured the problem out:

Internal Link, created by mobile
https://server/index.php/f/350136

Internal Link, created by web
https://server/f/350136

**Comment by AndyScherzinger** [comment]
@szaimen seems broken again with latest app and our production server on 23-latest

**Comment by AlvaroBrey** [comment]
> @szaimen seems broken again with latest app and our production server on 23-latest
> With what android version do you have this problem? Its working on my latest NC server with Android 11, but not with Android 12

We're tracking this in #9346 for Android 12, for reference
