### ISSUE TITLE
Statusbar overlaps toolbar in media preview activity

### ISSUE THREAD

**Issue by ezaquarii** [nextcloud/android#6448]
### Steps to reproduce
1. play audio file

### Expected behaviour
- Toolbar is below system status bar

### Actual behaviour
- Toolbar is covered by system status bar

![statusbar-overlapping-toolbar](https://user-images.githubusercontent.com/1426823/87094065-269bf900-c236-11ea-88f3-0604d8abeca0.jpg)

### Environment data
Android version: 10
Device model:  OnePlus 6T
Stock or customized system: stock
Nextcloud app version: master
Nextcloud server version: 19
Reverse proxy: not relevant

**Comment by AndyScherzinger** [comment]
ongoing fixing is done via #6437 -> #6441

so cc @tobiasKaminsky that the media preview (like all previews) has the same issue
