### ISSUE TITLE
PR reject by one should lead to a complete rejection

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#645]
If any of our devs reject one PR via PullAprove it should not be possible that this is being overriden by two other 👍 .
This can be done with: http://docs.pullapprove.com/groups/reject_value/
"A single rejection rejects the PR".

This way we make sure that all participating devs are fine with the PR.

@mario @AndyScherzinger

**Comment by mario** [comment]
Sure. Keep in mind this needs to have valid reasoning behind it anyway.

**Comment by AndyScherzinger** [comment]
Sounds good to me, taking into account the necessary reasoning mentioned by @mario

**Comment by tobiasKaminsky** [comment]
Yes of course, a negative pullApproval must always have a correct reason.
Then I will do a PR for our both Repos.

**Comment by tobiasKaminsky** [comment]
https://github.com/nextcloud/android/pull/652
