### ISSUE TITLE
Auto upload not working - not enough space 

### ISSUE THREAD

**Issue by sebeksd** [nextcloud/android#6457]
### Steps to reproduce
1. Enable auto upload for large gallery (5000+files, 35GB)
2. set to override files in case of conflict 

### Expected behaviour
- upload any new files to nextcloud server

### Actual behaviour
- app display error that there is not enough space on the phone but there is few GB space on phone and over 30GB free space on SD card (all privileges granted). Moreover second galery (Screenshots gallery, small, less then 1GB) works fine. I'm trying to make this app to upload my main phone galery for over a week, different configuration show different errors but none of them is working. When selecting to "ask" when conflict occurs app flood my phone with conflict notification for few days...
When configured to overwrite files it says no space available. It work this way for folder that is already full (on cloud side) and for empty folder.

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 8

Device model: Galaxy S7 Edge

Stock or customized system: Stock

Nextcloud app version: 3.12.1

Nextcloud server version: 19.0.0

Reverse proxy: Traefik

### Logs

![Screenshot_20200711-134049_Nextcloud](https://user-images.githubusercontent.com/18705953/87224897-4f80d300-c389-11ea-9327-ff4ec0add441.jpg)
![Screenshot_20200711-144936_Nextcloud](https://user-images.githubusercontent.com/18705953/87224898-50b20000-c389-11ea-97d5-a64662867bf4.jpg)

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
What is your storage path? Is this set to the external sdcard?

**Comment by sebeksd** [comment]
Default, didn't change (probably phone memory), see screenshot.
Additionaly after changing destination directory (cloud path) to empty folder ("\Zdjecia") it seem it start working for new files, but why it didn't work for old path "\[Zdjecia]" maybe brackets ? 
![Screenshot_20200716-142815_Nextcloud](https://user-images.githubusercontent.com/18705953/87675102-3c9a4400-c777-11ea-9fec-d8b15762156d.jpg)
