### ISSUE TITLE
Error when clicking upload conflict notification

### ISSUE THREAD

**Issue by z3ntu** [nextcloud/android#6458]
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{991f576 u0 com.nextcloud.client/com.owncloud.android.files.services.FileUploader}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1746)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6746)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30120090
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: Fairphone
Device: FP3
Model: FP3
Id: 8901.2.A.0120.20200421
Product: FP3

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 04211500

I can't provide much more info than that I've started the camera upload feature (instant upload?) with two folders of around a thousand pictures each and the app is behaving quite basdy ("nextcloud doesn't respond"), including this crash.

**Comment by Openanonwriter** [comment]
Had the same issue, the issue seams to be resolved in the nigtly builds.

**Comment by mhernawan** [comment]
same issue

**Comment by tobiasKaminsky** [comment]
> Had the same issue, the issue seams to be resolved in the nigtly builds or google beta.

Yes, unfortunately some devices have this problem with 3.12.x.
Next week there will be 3.13.0 RC1, available on Gplay beta.
If this then still happens, please re-open.
