### ISSUE TITLE
Add default overwrite options to consequtive (futrure) "File upload conflict", consider a global settings to it

### ISSUE THREAD

**Issue by kofaysi** [nextcloud/android#6459]
### Is your feature request related to a problem? Please describe.
Frustration: When I overwrote all my screenshots (downloaded and reuploaded to device), File upload conflict has been triggered for all of them. The only difference were the dates the files have been created. I had to resolve all of the conflicts individually. I wished to have an option to resolve them _en masse_.

### Describe the solution you'd like
Give option to resolve all consecutive file upload conflicts applying "prefer files by newer date" or "by older date" or similar. This option could be a global settings for cases, when filename and filesize equals, but creation  date differs.

### Describe alternatives you've considered
NA

### Additional context
NA

**Comment by AndyScherzinger** [comment]
The conflict behavior is a per. Folder option in your auto upload settings screen already, so closing since no additional setting on a global level needed.
Other discussions about sync logic is discussed in #285
