### ISSUE TITLE
Bad image/text combo in "Participate" screen

### ISSUE THREAD

**Issue by ldmpub** [nextcloud/android#646]
### Actual behaviour
A phrase is incomplet, it ends by "or" and nothing => see screenshot.

### Expected behaviour
A full sentence.
Need to correct the code or maybe the original english string then all translations based on this eroneous string.
String reference (sorry in french): https://www.transifex.com/nextcloud/nextcloud/translate/#fr/$/96734968
 
### Environment data
Android version:
6.0.1

Nextcloud app version:
20170209
![beaucoup de fautes de francais](https://cloud.githubusercontent.com/assets/1452146/22852621/0aab1a94-f040-11e6-9332-a053f28df1b4.jpg)

**Comment by mario** [comment]
Or is followed by the F-droid icon ...

**Comment by ldmpub** [comment]
Thanks for your extra quick answer.

Strange layout but why not ;-).

**Comment by strugee** [comment]
@mario it's still kinda unclear... would be better with a regular link or maybe a `:` at the end

**Comment by mario** [comment]
I know :( let me think how to approach it better

**Comment by strugee** [comment]
:thumbsup:

**Comment by tobiasKaminsky** [comment]
In english it is a "bit" more clear as it is "download the apk file or [get it on f-droid]" where the latest part is on the button.
What about adding a similar button for APK download? With this we can use a more generic sentence "get it here:" and show "apk button" and "frdoid button".

**Comment by mario** [comment]
Honestly, I also find it weird in english :)

**Comment by tobiasKaminsky** [comment]
And my new idea?

**Comment by mario** [comment]
I would maybe prefer just text links.

**Comment by mario** [comment]
@jancborchardt @eppfel thoughts?

**Comment by jancborchardt** [comment]
Isn’t the beta also available via Google Play? 

> I would maybe prefer just text links.

I’d actually say the reverse. Images are always quicker to recognize. It’s a sea of text at the moment already and we should reduce that.

**Comment by AndyScherzinger** [comment]
> Isn’t the beta also available via Google Play?

No, just release candidates. Also would recommend not to since the "beta feedback" on google play is handled via their dev console so we would have to copy paste everything to the issue tracker while the beta users from f-droid are happily opening issues here :)

> I’d actually say the reverse. Images are always quicker to recognize. It’s a sea of text at the moment already and we should reduce that.

I second that - especially since since I am also rather a visual type of person.

**Comment by eppfel** [comment]
> I’d actually say the reverse. Images are always quicker to recognize. It’s a sea of text at the moment already and we should reduce that.

Third that

I propose the buttons should never be part of a sentence, as it clearly breaks the continuous text and are quite self-explanatory.

**Comment by tobiasKaminsky** [comment]
> me on  https://github.com/nextcloud/android/issues/646#issuecomment-279143116 
What about adding a similar button for APK download? With this we can use a more generic sentence "get it here:" and show "apk button" and "fdroid button". 

Might be missed while discussing ;-)

**Comment by ldmpub** [comment]
Hi,

Any update ?

**Comment by eppfel** [comment]
Not of my knowing, as everything happens on github. Feel free to submit a pull-request yourself @ldmpub . I guess @tobiasKaminsky @AndyScherzinger and @mario are happy to help you.

**Comment by tobiasKaminsky** [comment]
What is the conclusion? I made a suggestion on https://github.com/nextcloud/android/issues/646#issuecomment-280420946 but I do not know if is accepted.

**Comment by mario** [comment]
Sure, fine.

**Comment by tobiasKaminsky** [comment]
Then we have a PR: #716

**Comment by AndyScherzinger** [comment]
#716 has been merged, so closing this issue. Change will be shipped with the next release.

**Comment by ldmpub** [comment]
Thanks!
