### ISSUE TITLE
Images are misaligned at File upload conflict 

### ISSUE THREAD

**Issue by kofaysi** [nextcloud/android#6460]
### Steps to reproduce
1. Trigger a File upload conflict (overwrite a screenshot by downloading and reuploading it to the device a trigger or wait for a sync

### Expected behaviour
- Images and screenshots are aligned to allow comparison.

### Actual behaviour
- The images are not aligned.
![IMG_20200711_230014](https://user-images.githubusercontent.com/17022173/87233832-4f092c00-c3cb-11ea-993b-4029ba08fa62.jpg)

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 7.1.2

Device model: LG G5

Stock or customized system: eOS

Nextcloud app version: NC Dev 20200711

Nextcloud server version: NA

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
What kind of images are those? PNG?
The reason might be that one is rendered on server, the other on Android and both might have a different way of creating thumbnails.

Can you provide us both images?

**Comment by kofaysi** [comment]
You are absolutely correct, the two files have also differing thumbnails in the Gallery app and on the server. It was a screenshot saved as PNG.

Here is the file from the server: https://ecloud.global/s/m2QAkgt5twPWjWR I believe I have only a single image now.

**Comment by tobiasKaminsky** [comment]
File not found. Maybe I was too late?

**Comment by kofaysi** [comment]
Uh, Tobias, I'm sorry, I moved old screenshots and forgot about the link here. Here you go: https://ecloud.global/s/qjm633zn4bb3mRD

I have seen that misalignment so many times. Actually, I do not remember any "file upload conflict", where screenshot would be aligned the same.

**Comment by tobiasKaminsky** [comment]
![image](https://user-images.githubusercontent.com/5836855/88366710-28af9d00-cd8a-11ea-9356-49c9e0504795.png)


Thanks, I am just posting this here, so that we can use it. 



> I have seen that misalignment so many times. Actually, I do not remember any "file upload conflict", where screenshot would be aligned the same.

As Android / server use different thumbnail creation methods this might be really tricky.

**Comment by tobiasKaminsky** [comment]
@nextcloud/server-triage do you know how exactly you create such a thumbnail?
We retrieve this via
`"/index.php/apps/files/api/v1/thumbnail/" + pxW + "/" + pxH + Uri.encode(file.getRemotePath(), "/");`

**Comment by MorrisJobke** [comment]
> @nextcloud/server-triage do you know how exactly you create such a thumbnail?

We don't have an option to move the center of a thumbnail. But it should™ be the center...

**Comment by tobiasKaminsky** [comment]
It would be enough if you can point me to the php code where you generate the thumbnail.
Maybe I can then see how/what is different.

**Comment by MorrisJobke** [comment]
> It would be enough if you can point me to the php code where you generate the thumbnail.
> Maybe I can then see how/what is different.

Should be this one here: https://github.com/nextcloud/server/blob/2a054e6c04e0a40421510eb889cbf59f153c5177/lib/private/Preview/Generator.php#L122

**Comment by tobiasKaminsky** [comment]
I tried it again with NC20 and latest Android version.
![image](https://user-images.githubusercontent.com/5836855/98802236-44ab7d00-2413-11eb-805b-2482d8ec5b54.png)
