### ISSUE TITLE
Android 10: No Nextcloud Storage Device (Files)

### ISSUE THREAD

**Issue by DragonDev1906** [nextcloud/android#6461]
This is probably related to #6387 and might have the same solution.

### Steps to reproduce
1. Update a phone from Android 9 to 10
2. Open the "Files" app

### Expected behaviour
Previously there was a "Nextcloud" entry under "Storage Devices", which could be used like an SD card.

### Actual behaviour
There is no "Nextcloud" storage device. Previously I could use the "Move to" function to move files. 
Now it only possible to upload files to nextcloud using the "Share" functionality but this requires a second step if I want to move the file (e.g. I just downloaded it and want it in Nextcloud, but not in the downloads folder).
It would be nice if the Nextcloud Folder would be shown as an SD card, if this is still possible.

### Environment data
Android version: 10

Device model: BQ Aquaris X2

Stock or customized system: Android One

Nextcloud app version: 3.12.1

**Comment by barthel-eu** [comment]
Same on Android 9. Whereas this works on a Chromebook, it's not available on phones.
Can't access the Nextcloud file storage conveniently from the Files app. So must "share" a file (or photo), then delete it locally. "Moving" is not possible. Nextcloud 3.12.1 on Android 9 (PPOS29.114-134-2) as well as on Android 10 (QPYS30.52-22-2)
Using Nextcloud to also keep the phone's file space small it would be nice to have what we have on the Chromebook also on the "smart" phone.

**Comment by tobiasKaminsky** [comment]
Can you give me a screenshot for "storage devices"?
I fear this this something special from BQ?

**Comment by barthel-eu** [comment]
Not related BQ, my devices are Motorola Moto G7 (Plus/Power).
![Screenshot_20200716-143702](https://user-images.githubusercontent.com/6716935/87671608-eaa2ef80-c771-11ea-97d3-3c89c7d4c461.png)

**Comment by DragonDev1906** [comment]
Looks pretty much the same as the one from @barthel-eu 
![Screenshot_20200716-144642 - Kopie](https://user-images.githubusercontent.com/8270201/87672665-9731a100-c773-11ea-9f83-fe8df30c2360.png)

**Comment by DragonDev1906** [comment]
It seems there are (at least) 2 Apps for showing files on my system, but only one of them is visible. It still seems possible to use the "old" Files app:

- Open a link in google drive
- Download a file
- Wait for the download to finish
- Click on the notification

Then the following dialog shows:

![open_with_select](https://user-images.githubusercontent.com/8270201/88667539-ca642080-d0e1-11ea-9f13-d52389653b65.png)

By selecting "Files" I was able to open the old Files app, which seems to have been replaced by "Files by Google". The last Screenshot was when using "Files by Google", while the Screenshot below is taken using the old "Files" app, which is not easily accessible anymore.

![old_files_app](https://user-images.githubusercontent.com/8270201/88668308-bbca3900-d0e2-11ea-9959-921d7f8e0e4b.png)

@barthel-eu: I guess this is the same reason on your device?

I personally would like to have nextcloud in there but since Google Drive, and Termux are not shown in "Files by Google" either I don't think there is anything Nextcloud can do there. I guess this Issue can be closed now?

**Comment by mpfaff** [comment]
Please reopen this issue. Confirmed on my Pixel 2 XL running Android 10.

**Comment by tobiasKaminsky** [comment]
Have you app protection within Nextcloud enabled?

**Comment by monotok** [comment]
Hi, 
Just got a Xperia 5 II running Android 10 and I noticed the same thing. I mainly use solid explorer but Files is used when opening things from another app. 
Strange thing is; seafile android client does appear in the list along with Google Drive. Their android client doesn't get updated as often as Nextcloud so I guess it is the way they implemented it.

**Comment by rikmeijer** [comment]
I confirm this issue on a sony xperia 5

**Comment by sokai** [comment]
FYI = FAQ:
> The solution ended up being completely unintuitive, but super easy: set "App passcode" to "None" in the Nextcloud Android app settings.

ref: https://github.com/nextcloud/android/issues/10249#issuecomment-1434544013
