### ISSUE TITLE
Killing NextCloud Dev app does not remove the active notification "uploading files"

### ISSUE THREAD

**Issue by kofaysi** [nextcloud/android#6462]
### Steps to reproduce
1. Kill NC dev app (swipe right in active apps manager), when "Uploading files..." notification is on. I managed to have the notification there for longer time, when "File upload conflict" had been generated and had to be resolved by the user.
2. Observe and Click on the notification afterwards.

### Expected behaviour
- notification should be killed or removed,  too.

### Actual behaviour
- Notification stays on and is unlink to the app. No app is open on click. Restart is needed to remove the notification.

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 7.1.2

Device model:  LG G5

Stock or customized system: eOS 0.9

Nextcloud app version: NC Dev 20200711

Nextcloud server version: 18

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Swipe away does not close the app, but only suspends it and thus notifications stay there.
You would have to force close the app.

**Comment by kofaysi** [comment]
So, the link between the notification and the app shall no break, right? "Uploading files..." notification opened the app previously, didn't it?

**Comment by tobiasKaminsky** [comment]
I do not fully understand your question…?

**Comment by kofaysi** [comment]
Issue remains closed. I tried to reproduce the behaviour and create a video screenshot unsuccessfully. The "Uploading files.." does not open the NC app, never. It seems to be its default behaviour of this notification. As for the others, #issuecomment-659378328 remains as answer. Thank you
