### ISSUE TITLE
ChromeOS files mount being disconnected randomly

### ISSUE THREAD

**Issue by hardwareadictos** [nextcloud/android#6464]
Just saw that sometimes when i try to access my nextcloud files on ChromeOS files app i only get an infinite loading bar. Tried by stopping android app and clearing cache, but only restarting the chromebook seems to fix the issue. Mounts are wotking for some minutes since the first access, but rear some minutes it just goes to that infinite loading, white screen. 

![image](https://user-images.githubusercontent.com/20403906/87255482-660f5300-c48b-11ea-9311-db616077bb5b.png)

Not sure if it's really an app issue or a chrome issue, not sure how much time ago is it happening but i considered to report it to see other ChromeOS users thoughts about it, and to know if other ChromeOS users are facing it also.

Tested it on my local network and with my VPN network with the same result.

Thanks in advance.

**Comment by tobiasKaminsky** [comment]
This is indeed hard to reproduce and also hard to verify if is a a problem of this app.
Upon entering NC it should reload any files, so if this times out, can you check if it still works within the real NC app?

**Comment by hardwareadictos** [comment]
> This is indeed hard to reproduce and also hard to verify if is a a problem of this app.
> Upon entering NC it should reload any files, so if this times out, can you check if it still works within the real NC app?

Nextcloud app works fine. Also tried to fix the issue buy opening Nextcloud app to see if that mounted dirs gets refreshed without luck.

I even power washed my Chromebook to try to fix it without success.

Would be nice to see if others have that issue also.

**Comment by hardwareadictos** [comment]
> This is indeed hard to reproduce and also hard to verify if is a a problem of this app.
> Upon entering NC it should reload any files, so if this times out, can you check if it still works within the real NC app?

Nextcloud app works fine. Also tried to fix the issue buy opening Nextcloud app to see if that mounted dirs gets refreshed without luck.

I even power washed my Chromebook to try to fix it without success.

Would be nice to see if others have that issue also.

**Comment by hardwareadictos** [comment]
Tried even more combinations like connecting via VPN or reinstalling the app without success :(
