### ISSUE TITLE
Auto-Upload is not working, after update on version 3.12.1

### ISSUE THREAD

**Issue by 120e314** [nextcloud/android#6469]
### Steps to reproduce
1. take a photo - waiting for auto-upload
2. open the nextcloud-app and go to "Uploads"
3. then refresh - the upload is started

### Expected behaviour
- after taking a photo, the pic should being uploaded automatically. 

### Actual behaviour
- I had configured the auto-upload routine. After taking a photo with the "OpenCamera"-App, Nextcloud should upload the photo from the OpenCamera-Folder (DCIM\OpenCamera) into the destination-folder configured in the Nextcloud-App, only if WiFi is active.

### Environment data
Android version: 9

Device model: Samsung Galaxy XCover 4

Stock or customized system: stock

Nextcloud app version: 3.12.1

Nextcloud server version: 18.0.4

**Comment by tobiasKaminsky** [comment]
Do you have the app excluded from battery saving?

**Comment by mlsxlist** [comment]
Same here with my Huawei P30 Pro. Battery saving is disabled. Automatic upload worked till recently.

**Comment by YouveGotMeowxy** [comment]
I get this every time , with auto upload....

![Screenshot_20200719-221358_One-UI-Home](https://user-images.githubusercontent.com/39491297/87896519-117d5200-ca0e-11ea-9a40-52ecd1d5c734.jpg)

Batt saving is disabled, and I'm not using a VPN.

Using Android app version: 3.12.1
NC version: 18.0.7

**Comment by mlsxlist** [comment]
> I get this every time , with auto upload....
> 
> ![Screenshot_20200719-221358_One-UI-Home](https://user-images.githubusercontent.com/39491297/87896519-117d5200-ca0e-11ea-9a40-52ecd1d5c734.jpg)
> 
> Batt saving is disabled, and I'm not using a VPN.
> 
> Using Android app version: 3.12.1
> NC version: 18.0.7

I doubt this has something to do with what has been reported originally with this ticket. This ticket is about auto upload that does not work. It just does not start automatically after taking a picture. But the upload can be forced manually. Maybe you create a separate issue for what you experience.

**Comment by 120e314** [comment]
Yes the app is exluded from battery saving.

**Comment by majorvin** [comment]
Same here..

**Comment by JenniferJohnson89** [comment]
I noticed that there is a similar problem at https://github.com/nextcloud/android. Perhaps we can refer to [this issue](https://github.com/nextcloud/android/issues/5074) to find more context about the bug (e.g. the Android version, or app version, or their steps to reproduce?).

**Comment by JenniferJohnson89** [comment]
Also similar [here](https://github.com/stefan-niedermann/nextcloud-notes/issues/682). Hope that helps.
