### ISSUE TITLE
Replace full-screen background when viewing films

### ISSUE THREAD

**Issue by pilsnerbeer** [nextcloud/android#6470]
### Is your feature request related to a problem? Please describe.
white background should be replaced with black for better experience when watching videos.
(See screenshot)

### Additional context
Screenshot:
full-screen mode enabled, white croplines visible on top and bottom
(not entirely visible due to white background here on github but you get the idea)
![a](https://user-images.githubusercontent.com/36133540/87329003-a2e45400-c536-11ea-9477-60745aaeb726.jpg)

**Comment by AndyScherzinger** [comment]
@pilsnerbeer what version of the app are you using?

@tobiasKaminsky I only get to see the non full screen version for mp4 and master branch

**Comment by pilsnerbeer** [comment]
3.12.1 from F-Droid. You must tap the screen in order switch to full-screen mode

**Comment by AndyScherzinger** [comment]
> 3.12.1 from F-Droid. 

Thanks

> You must tap the screen in order switch to full-screen mode

... which is what isn't working for my on the latest master code base

**Comment by tobiasKaminsky** [comment]
Multimedia buttons also do not work. :-/
Currently I have no clue what happens there…

**Comment by tobiasKaminsky** [comment]
The PR fixes black background.
Media control is in #7339 
Crashing video in #7340
