### ISSUE TITLE
Display thumbnails for picture files in Activity

### ISSUE THREAD

**Issue by pilsnerbeer** [nextcloud/android#6477]
### Is your feature request related to a problem? Please describe.
Thumbnails should be rendered for pictures (even videos, if possible) in Activity to help recognition. I barely name my pics (see screenshot) so it does help with navigation. Furthermore, thumbnails should be clickable (issue exists).

### Describe the solution you'd like
Replace grey-colored shape (see pic) with actual thumbnail of the photo.

### Additional context
![Screenshot_20200715-150303_1 (1)](https://user-images.githubusercontent.com/36133540/87555316-93d7e000-c6b5-11ea-8443-cea53d4eefb4.jpg)

**Comment by AndyScherzinger** [comment]
Thanks for reporting this @pilsnerbeer, labeled as bug now since this is a regression and has worked before.

@tobiasKaminsky tested against Nc19 in my case. Didn't have the time to debug.

**Comment by tobiasKaminsky** [comment]
That is really strange.
I found out that the content of preview image is correctly retrieved, but then it is not shown…
As we did not changed anything on Glide's side I am currently a bit out of ideas…

**Comment by AndyScherzinger** [comment]
> As we did not changed anything on Glide's side I am currently a bit out of ideas…

@tobiasKaminsky Glide shows the placeholders which would also be the case when glide gets an error, so maybe all these thumbnail calls simply fail?

**Comment by AndyScherzinger** [comment]
shipping with next feature release
