### ISSUE TITLE
20170211 app crash on Configuration

### ISSUE THREAD

**Issue by JSoko** [nextcloud/android#648]
### Actual behaviour
- deinstall 20170209
- install 20170211
- enter credentials
- chose configuration (Einstellungen) in the menue
- app crashes (Nexcloud beta angehalten)

### Expected behaviour
- the configuration menue should open
 
### Steps to reproduce
see above

### Environment data
Android version:
7.0
Device model: 
sgs7

Stock or customized system:
stock
Nextcloud app version:
20170211
Nextcloud server version:
11.0.1.2
#### Web server error log
nothing related

**Comment by tobiasKaminsky** [comment]
This was a mistake made by a wrong merge by me :/
Please download the updated file again: https://github.com/nextcloud/android/blob/beta/apks/latest.apk

**Comment by JSoko** [comment]
@tobiasKaminsky 
Thank You!
It's fixed...
