### ISSUE TITLE
Android APK does not work

### ISSUE THREAD

**Issue by bytus** [nextcloud/android#6482]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
- Tell us what should happen

The problems are the following:

Install the GOOGLE PLAY app.
When installing, credentials are requested.
But, when logging in, a crappy version of WEB APK appears, like the image uploaded by me ( https://extremtec.es/uploads/APK-NEXTCLOUD-ON-MI-SMARTPHONE.jpeg ). It is the page as it looks, if I enter from the browser. But the difference is that from the browser, I can load 1 (only one image at a time) and from its APK the load button does not work. The APK is useless. When selecting multiple images and trying to load it from the APK, a pop-up window appears, saying I don't have an account associated with Nextcloud. You can test Android APK functionality and confirm it. Excuse me but I don't speak English and I use the translator.

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

With the demo account, from https://try.nextcloud.com/ , It works well.
Tested on Android 10 and 7

### Environment data
Android version:

Device model: Xiaomi MI9 Lite & Samsung S6

Stock or customized system: Android 10 & 7

Nextcloud app version: Last version

Nextcloud server version: 10 ( i use php 5.5 )

Reverse proxy: no

#### Web server error log
I do not know how to do it
```
Insert your webserver log here
```
I do not know how to do it
#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
I do not know how to do it
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

I have already solved the problem, I have installed the previous version of APK. Thank you.

**Comment by tobiasKaminsky** [comment]
> With the demo account, from https://try.nextcloud.com/ , It works well.

This then is a problem with server configuration as you are never really using the app, but stay inside the login web view.
Please go to help.nextcloud.com and ask there for help, as this is only for bugs and feature requests, but not for individual support.
