### ISSUE TITLE
Translation via transifex

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#65]
Just a reminder: what is the current situation?

**Comment by AndyScherzinger** [comment]
Has been implemented on transifex, @MorrisJobke is checking the auto push to the repo in combination with the LGTM checks.

**Comment by MorrisJobke** [comment]
It is live -> closing

**Comment by MorrisJobke** [comment]
See 0626040e7bda0b6d3cc5542a07205a20fbb348bc for example :)
