### ISSUE TITLE
@string/etm_background_job_uuid pp in transifex

### ISSUE THREAD

**Issue by JSoko** [nextcloud/android#6502]
### Steps to reproduce
In transifex there are the strings

@string/etm_background_job_uuid
@string/etm_background_job_progress
@string/etm_background_job_state
@string/etm_background_job_user
for translating.

https://www.transifex.com/nextcloud/nextcloud/translate/#de_DE/$/294672883?q=text%3A%40string%2F

Shall they realy be translated? If yes, how?

**Comment by tobiasKaminsky** [comment]
Indeed this are internal description of the background jobs.
They will be removed via #6503
