### ISSUE TITLE
Hide app content in recent apps/apps switcher when app passcode is enabled

### ISSUE THREAD

**Issue by seanthegeek** [nextcloud/android#6508]
### Is your feature request related to a problem? Please describe.
Previews of whatever you are working on are viable in the Android app switcher/recent apps view, even when a the NextCloud app in configured to require a fingerprint or PIN. This raises privacy concerns.

### Describe the solution you'd like
I'm not sure what API does this, but Android apps (e.g. Firefox Focus) are able to hide content from the resents/app switcher. This should be used when an app passcode is configured.

**Comment by tobiasKaminsky** [comment]
This should already be the case.
But indeed with device credentials I do not see this.

**Comment by JenniferJohnson89** [comment]
I noticed that there is a similar problem at https://github.com/Automattic/simplenote-android. Perhaps we can refer to [this issue](https://github.com/Automattic/simplenote-android/issues/602) to find more context about the bug or hints to solve this problem.
