### ISSUE TITLE
App content is breifly visable before being prompted for the app passcode when switching apps

### ISSUE THREAD

**Issue by seanthegeek** [nextcloud/android#6509]
### Steps to reproduce
1.  Enable app passccode with system credentials
2. Open image, video or document
3. Use the recent apps/app switcher in android to switccch to another app, the bacck tp NextClouud

### Expected behaviour
The app should prompt for the app passcode without displaying any content

### Actual behaviour
The previously opened content is visible for a second or two before the user is prompted for the app password

### Can you reproduce this problem on https://try.nextcloud.com?
Not a server issue

### Environment data
Android version: 10

Device model: Pixel 3 XL

Stock or customized system: Stock

Nextcloud app version: 3.12.1

Nextcloud server version: 19.0.1

Reverse proxy: Apache (via the official Docker image)

**Comment by tobiasKaminsky** [comment]
I cannot reproduce it.
It flickers a bit, but does not show any sensitive info.

**Comment by seanthegeek** [comment]
@tobiasKaminsky Ah, it looks like this was related to the issue #6508, and was resolved by the same fix in PR #6996, which is why you couldn't reproduce it.
