### ISSUE TITLE
Invite guests with the Android app

### ISSUE THREAD

**Issue by schiessle** [nextcloud/android#6520]
### Steps to reproduce
1. Install the Guests app on Nextcloud 19.0.1
2. Go to the Android app
3. Try to share a file with "test@foo.com"

### Expected behaviour

I would expect to have a option to create a Guest account and share the file with a guest

### Actual behaviour

Only the federated share option and the share by mail option is shown:

![Screenshot_20200723-133444_Nextcloud](https://user-images.githubusercontent.com/1589737/88284516-d1f48580-cced-11ea-8e71-f08d7ee70363.png)

For a second I saw the "Guest" option after it was replaced with the other two options (federated share and share by mail). Therefore I thought it might be just a limit of max 2. auto-complete options. In another try I disabled federated sharing on the server. But now only the "share by mail" option was shown:

![Screenshot_20200723-134223_Nextcloud](https://user-images.githubusercontent.com/1589737/88284625-0405e780-ccee-11ea-96c6-633c65f89a27.png)

So it seems to be a real issue with Guest account creation here although I wonder why I saw the option for a short time span on my first try.

### Environment data
Android version: 9

Device model: 

Stock or customized system:

Nextcloud app version: 3.12.1

Nextcloud server version: 19.0.1

Reverse proxy:

**Comment by tobiasKaminsky** [comment]
This is not a bug, but a missing feature.
As this requires further input via a dialog and it is "only" an app, this might take a bit.

**Comment by schiessle** [comment]
Ok, so let's close this and followup on the other ticket
