### ISSUE TITLE
App: on device should not list files not on device

### ISSUE THREAD

**Issue by ctrlbrk42** [nextcloud/android#6526]
Using 3.13 RC1 Android

The "on device" is listing all of my folders from the cloud, not just the ones synchronized to my device.

I would expect the "on device" list to only show files/folders that have been marked for synchronization.

This seems to have changed from the last version.

**Comment by tobiasKaminsky** [comment]
It should only show those folders where a file is within any subdirectory.
Can you verify that those folders are really completely empty?

**Comment by ctrlbrk42** [comment]
> It should only show those folders where a file is within any subdirectory.
> Can you verify that those folders are really completely empty?

Hard to show with privacy, but see screenshots that hopefully help. I am seeing 3.6MB used in each folder, but it's definitely a bug. I have not synchronized files from these folders, plus they don't contain the same files (all just happen to be 3.6mb?)

![Screenshot_20200724-152338](https://user-images.githubusercontent.com/1001097/88432740-68927680-cdc2-11ea-9282-2b4909a0e5cd.jpg)
![Screenshot_20200724-152534](https://user-images.githubusercontent.com/1001097/88432744-69c3a380-cdc2-11ea-9d85-3e4de1cbb274.jpg)

**Comment by tobiasKaminsky** [comment]
Oh, wow.
I should have first checked it on my system. 
Indeed there is something wrong.

Sorry! And thanks for filling out the bug report!
