### ISSUE TITLE
3.13 RC1 pin/fingerprint prompt not working

### ISSUE THREAD

**Issue by ctrlbrk42** [nextcloud/android#6527]
After installing 3.13 RC1, I'm finding that switching windows and then returning to Nextcloud, prompts for my fingerprint or PIN -- however, it will not accept any answer (no fingerprint or PIN).

It just keeps asking over and over. Closing the app and re-launching does work as expected.

OnePlus 7 Pro
Android 10
App passcode set to "device credentials"

To reproduce:
- Open app
- Click settings
- Switch to another app, switch back

**Comment by tobiasKaminsky** [comment]
We did not changed anything in this regard from 3.12 -> 3.13 RC1 as far as I know.
Is this working on 3.12?
