### ISSUE TITLE
Problem while building the project 

### ISSUE THREAD

**Issue by Mehdi-git** [nextcloud/android#6543]
There is a problem while building the project, 
            capability.setFilesFileDrop or capability.getFilesFileDrop symbol could not be found.

//
  error: cannot find symbol
            capability.setFilesFileDrop(getBoolean(c, ProviderTableMeta.CAPABILITIES_FILES_DROP));
                             ^
  symbol:   method getFilesFileDrop()
  location: variable mCapabilities of type OCCapability

**Comment by AndyScherzinger** [comment]
Hi @Mehdi-git,

this is something we changed in the library and that led to a change on the master branch. Did you update to the latest master?
See https://github.com/nextcloud/android/pull/6404/files for details
