### ISSUE TITLE
Sync conflict of all files after downloading one file

### ISSUE THREAD

**Issue by jecal22** [nextcloud/android#6548]
### Steps to reproduce
1. Select a fie in Nextcloud app.
2. Menu for the file has Download option, select to download file to devicce.
3. File downloads fine with no issue.
3. Go back to Nextcloud app and refresh file list.
4. All other files (regardless of folder) will show red X.
5. Select another file.  Menu for the file shows only Sync option (Download is now missing)
6. Select Sync option
7. Conflict prompt comes up indicating that there is a conflict and offers to keep the New, Existing, or both local versions of the file.  Comparing the file sizes, you can see that the file size and date of the "New file" matches that of the first downloaded file from step 2.  The "Already existing file" appears to be the correct file selected in step 6.
8. Cancel the conflict message.
9. Select the original file downloaded from step 2 and choose Delete.
10. Choose to delete only the local version of the file.
11. Refresh Nextcloud file list.
12. All Red X's are now cleared from all files.  You can now select any other file and download it normally with the same results as step 3 and onwards.

### Expected behaviour
- Should be able to download multiple individual files without creating a sync conflict with other files.

### Actual behaviour
- Downloading any 1 file results in a conflict with any other file that is attempted to download.

### Can you reproduce this problem on https://try.nextcloud.com?
YES.  I added a try.nextcloud.com account to the mobile app and get the exact same results.

### Environment data
Android version: Android 10 (Build QQ3A.200705.002); Security patch level July 5, 2020; Google Play update May 1, 2020

Device model: Pixel 3 XL

Stock or customized system: 100% Stock.  No root access or any modifications to stock system.

Nextcloud app version: 3.13.0 RC1

Nextcloud server version: 19.0.1

Reverse proxy: None.

LOGS:
When reproducing this issue, no logs are generated on the server.

Judging by the evidence collected from testing, It seems to be an issue with how the app is caching/saving downloaded files.  Instead of creating a separate file for each remote file downloaded, it is overlapping with the same file, thus the client thinks there is a conflict of local versions of files when trying to download a different file after the first file has already been downloaded.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky can you reproduce this? It works just fine for me, Android 10, client 3.13.0RC1, Server 19.0.1

**Comment by miwie** [comment]
Same bug here: Android 10 (2nd device: Android 7.0), client 3.13.0RC1, Server 18.0.7

**Comment by tobiasKaminsky** [comment]
This is a bug within RC1 and will be fixed via #6557.
I will release RC2 tomorrow.
