### ISSUE TITLE
File duplication error part 2

### ISSUE THREAD

**Issue by Siggi0904** [nextcloud/android#6549]
With newly sync client 3.13.0 RC1 the old bug occurs right now.
See https://github.com/nextcloud/android/issues/5599#event-3238317062

I think, with these option in folder configuration, this is fixed. But it comes back with this newly beta.
Sync folder configuration is not changed till stable version.

Thanks for checking and fixing.

**Comment by tobiasKaminsky** [comment]
#5599 is re-opened, thus closing this here.
