### ISSUE TITLE
Rename "remove" to "delete"

### ISSUE THREAD

**Issue by smichel17** [nextcloud/android#655]
"Delete" is a standard word to describe this action and I know what it does already. "Remove" is something new that I have to think about what it does. 

I suspect this wording was used so that "remove from server" and "remove from device" can be options in the dialog, but I think "Delete from device" is just as clear. 

As an added benefit, "Delete" is a lot more visually recognizable in the menu compared to "Remove", which is easy to mix up with "Rename".

Tangentially related: #109

**Comment by tobiasKaminsky** [comment]
Although I am not a native speaker "delete" is more know to me than "remove".
@jancborchardt

**Comment by jancborchardt** [comment]
Totally agree. We should have the wording consistent, and it is "Delete" on the server too.

Can we make sure it is "Delete" everywhere? Also cc @marinofaggiana for the iOS app.

**Comment by AndyScherzinger** [comment]
to be fixed with upcoming PR

**Comment by AndyScherzinger** [comment]
PR is #1618

**Comment by comradekingu** [comment]
I was surprised to find delete at 1158 and remove at 26573 https://corpus.byu.edu/coca/
Still i think remove has its place, for things that can be easily added again. Like removing a filter.
