### ISSUE TITLE
File deletion only at server side

### ISSUE THREAD

**Issue by Siggi0904** [nextcloud/android#6550]
Looks like with newly version 3.13.0 RC1 the app try to delete files on both sides ( local and remote) if "delete file" -> "delete".
In my use case, I'll backup my whole whatsapp folder and an error ocours if I try to delete system files at server side.

Since latest stable it is not possible to delete files only at server side.

Thanks.

**Comment by tobiasKaminsky** [comment]
![image](https://user-images.githubusercontent.com/5836855/88653785-cf6aa500-d0cc-11ea-92b9-3cb8a5d4f161.png)


> Since latest stable it is not possible to delete files only at server side.

This was never possible. As you can see, you can
- keep -> nothing happens
- local only -> server file remains
- delete -> local & server file will be deleted

As the file is on server, and thus synced with device, it would be strange to keep the file only on device.

**Comment by Siggi0904** [comment]
Switch to german language, it's easier.

Ja, die Funktion kenne ich und nutze ich auch.
Nur sichere ich mein komplettes WhatsApp Verzeichnis auf meinen NC Speicher.
Bisher hatten die Ordner von WhatsApp in der Verzeichnisstruktur auf dem Server keinen grünen Haken.
Ich konnte serverseitig Dateien löschen ohne Fehlermeldung.
Mit der neuen Version 3.13 bekomme ich für die lokalen Dateien eine Fehlermeldung, die Serverseite wird gelöscht.
Das ist ja auch richtig, ich will im WhatsApp Verzeichnis auf meinem Handy nichts löschen, nur auf dem Server.

Danke.

**Comment by AndyScherzinger** [comment]
> Das ist ja auch richtig, ich will im WhatsApp Verzeichnis auf meinem Handy nichts lösche

Da der Ordner außerhalb von der App liegt, löschen wir da auch nichts :) Sollte es ein Download sein, dann würden wir ggf etwas löschen, dann lägen die Dateien aber auch innerhalb der App (im Grunde wie eine Kopie nebendran).

Switching back to English
@tobiasKaminsky could this be related to your E2EE change which also led to some strange status icon displays for other users? (can't remember the issue atm).
