### ISSUE TITLE
Label for PR

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#657]
https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#pull-request says:
-   1 to develop
-    2 developing
-    3 to review
-    4 to release

@jancborchardt correctly says in https://github.com/nextcloud/android/issues/623#issuecomment-279707231 that "1. to develop" for a PR is double.
So I would just remove "1. to develop" and rename the remaining starting by 1.

For issues we will still have
-    nothing/no tag
-    approved
-    PR exists (and then the PR# should be shown in first post)

@mario @AndyScherzinger

**Comment by AndyScherzinger** [comment]
Sounds good 👍

**Comment by mario** [comment]
Sure.
