### ISSUE TITLE
Nextcloud FileProvider providers inexisting files?

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/android#6581]
Since a few days (2-3 weeks maybe) I have the following issue

### Steps to reproduce
1. Open Messenger of choice (in this case Line)
2. Try to quickly share an image
3. Only see error placeholders

### Expected behaviour
Preview of latest images

### Actual behaviour
![photo_2020-07-30_13-31-29](https://user-images.githubusercontent.com/213943/88918108-39b84c80-d269-11ea-85de-ad7680054a74.jpg)

### Can you reproduce this problem on https://try.nextcloud.com?
The problem is linked to the "SofortUpload" feature of the Nextcloud files client for Android. When switching to the list view in the quick selection feature it shows that the "images" are all of size 0 Bytes and were placed in the direct upload (?) folder. But they don't exist locally anymore because they got deleted after the upload. But the Nextcloud FileProvider still seems to offer them?

### Environment data
Android version: 10 

Device model: Xiaomi Redmi Note 8 Pro

Stock or customized system: MIUI Global 11.0.5 Stabil

Nextcloud app version: 3.13.0. RC1

Nextcloud server version: 19.0.1

Reverse proxy: No

**Comment by tobiasKaminsky** [comment]
Where do you see these placeholders?
Within NC app? In Line?
