### ISSUE TITLE
Nextcloud beta has stopped

### ISSUE THREAD

**Issue by jasonbayton** [nextcloud/android#659]
### Actual behaviour
- When tapping settings in the app menu the app crashes instantly with the error "Nextcloud beta has stopped"
### Expected behaviour
- Opens settings without issue
 
### Steps to reproduce
1. Open NC and slide out menu
2. Tap settings
3. Watch app crash

### Environment data
Android version: 5.1

Device model: Samsung Galaxy J3

Stock or customized system: Stock

Nextcloud app version: 20170214

Nextcloud server version: 11.0.1

### Logs
Unavailable (since they're in settings)

**Comment by mario** [comment]
Strange. I'll try to open the settings :)

**Comment by JSoko** [comment]
Had that issue some betas before, but not on 20170214 and 20170215.
NC 11.0.2 RC1

**Comment by mario** [comment]
I can't reproduce this :-/

**Comment by jasonbayton** [comment]
I can. Every time :(

**Comment by mario** [comment]
I have managed to reproduce it. It's only in beta and related to the fingerprint PR.

**Comment by jasonbayton** [comment]
Nice job :D 

Let me know when the relevant pr build drops :nerd_face:

**Comment by mario** [comment]
@jasonbayton this one doesn't depend on me :P https://github.com/nextcloud/android/pull/624

**Comment by Nephatiu** [comment]
Confirming this is also happening on my Samsung Galaxy J5 (rooted) stock, btw.

From the very first try, never got into Settings yet.

Funny, as that also was the very first thing I did when I launched the app,... Did not last long... ;p

Anyway, keep up te good work! ;p

Greetings,

 ~ N.d.A.

**Comment by tobiasKaminsky** [comment]
@mario does @Flole998 knows about the crash? Is there a stacktrace?

**Comment by Flole998** [comment]
I know about it and there's even a fix already up, just waiting for approval if I'm not mistaken.

**Comment by tobiasKaminsky** [comment]
Can you give me a link? 
If it is a problem of fingerprint, then you can fix this in your branch and I can merge it into beta?

**Comment by Flole998** [comment]
Its on PR #624 that's referenced above. Fix is already in my branch, I think it just got a little lost because of the discussion about an authentication fallback over at that PR.

**Comment by tobiasKaminsky** [comment]
Ok, merged to beta. 
Will be available tomorrow on fdroid or updatable directly in beta.

**Comment by jasonbayton** [comment]
I'll consider this closed unless I find it still broken when I test later. Thanks! :D
