### ISSUE TITLE
Duplicate entries

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/android#660]
### Actual behaviour
- open the app
- see all file list entries duplicated

![screenshot_20170113-123716](https://cloud.githubusercontent.com/assets/245432/22960045/815c8f66-f300-11e6-8afa-97bba4a6b0f5.png)

### Expected behaviour
- don't see duplicated entries

### Environment data
Android version: ...

Device model: Galaxy S6 

Stock or customized system: stock

Nextcloud app version: last weeks Play store version

Nextcloud server version: 10.0.0

@tobiasKaminsky @AndyScherzinger Have you seen this before? The web UI looks fine. And we can't properly reproduce this, but it happened. Maybe a race condition or maybe you already fixed it. Feel free to close it, if this doesn't contain any useful stuff for you.

**Comment by mario** [comment]
@MorrisJobke have you used filtering/search before that?

**Comment by MorrisJobke** [comment]
> @MorrisJobke have you used filtering/search before that?

Could be ... yes there is one screenshot that seems to trigger the search:

![screenshot_20170113-123513](https://cloud.githubusercontent.com/assets/245432/22963659/c139b7c6-f319-11e6-9566-32b77ba898f7.png)

**Comment by mario** [comment]
Then I'm already working on a fix for this and will be in 1.4.2.

**Comment by tobiasKaminsky** [comment]
#609 for references

**Comment by mario** [comment]
Fixed.

**Comment by MorrisJobke** [comment]
> Fixed.

So it will land in the next maintenance release?

**Comment by AndyScherzinger** [comment]
In case of #661, it has been merged to master, that is a yes for being part of the upcoming release :)

Thanks for all the efforts taken @mario!
