### ISSUE TITLE
Sync downloads to 'me@mynextcloud.comnull' file

### ISSUE THREAD

**Issue by EthanWeegee** [nextcloud/android#6602]
### Steps to reproduce
1. Sync remote folder to phone (In this case, music, which is a few GBs)

### Expected behaviour
Files appear structured in `me@mynextcloud.com` directory. Previously this worked without issue, and I don't know what has changed.

### Actual behaviour
Files are written to a file called `me@mynextcloud.comnull` where the directory should be. Opening this file in VLC confirms that it is indeed an audio file, and it is overwritten with each file synced.

### Can you reproduce this problem on https://try.nextcloud.com?
Syncing Photos, files are synced to `<generated username>@demo2.nextcloud.comnull`. Opening confirms it is an image file.

### Environment data
Android version: 10

Device model: Samsung Galaxy S10e

Stock or customized system: Stock Samsung firmware

Nextcloud app version: Dev 20200724 (**EDIT:** Installed 20200730 and it reports 20200724, perhaps a separate issue?) and Stable 3.13.0 RC1 (**EDIT:** Downgraded to 3.12.0 and then 3.12.1 via F-Droid, issue is not reproducible in these versions.)

Nextcloud server version: 18.0.4

[logs.txt](https://github.com/nextcloud/android/files/5008351/logs.txt)

**Comment by romevi** [comment]
Thought it was just me. Been driving me nuts since yesterday. I can't download files now to my phone. Hope this gets fixed asap.

**Comment by AndyScherzinger** [comment]
Hi folks, please upgrade to 3.13.0 RC2 which should ship a fix for this issue

**Comment by EthanWeegee** [comment]
I am unable to test this as it refuses to install (App not installed.)

**Comment by AndyScherzinger** [comment]
F-droid and gplay versions aren't compatible, not sure when the RC2 will be available via f-droid

**Comment by romevi** [comment]
Thanks; I have 3.13.0 RC1 installed from F-Droid. I'll try the upgrade from here instead.

**Comment by tobiasKaminsky** [comment]
Please re-open if it happens again.
(APK installing problem should be addressed in a different issue)
