### ISSUE TITLE
File conflict dialogue doesn't tell you which file it's talking about

### ISSUE THREAD

**Issue by InfamousUser** [nextcloud/android#6603]
Who thought this is helpful?? How am I supposed to make a decision using this? It is a random file with no data about it shown, it only says how large it is and some date.
![Screenshot_20200731-232529](https://user-images.githubusercontent.com/47887158/89078883-842eeb80-d385-11ea-9f49-2e95ffa085c3.png)

### Steps to reproduce
1. Have file conflict dialogue box appear magically.
2.
3. 

### Expected behaviour
One is supposed to be able to make a decision based on the dialogue box content in majority of cases.

### Actual behaviour
One is unable to make a decision based on the dialogue box content because it does not show the file name.

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 10

Device model: Google Pixel 2

Stock or customized system: stock

Nextcloud app version: 3.13 RC1

Nextcloud server version: 19.0.1

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
cc @tobiasKaminsky @jancborchardt for feedback

@InfamousUser thanks for reporting issues, this is highly appreciated ❤️ One thing though

> Who thought this is helpful?? How am I supposed to make a decision using this?

While I get the frustration when anyone hits an issue with the app people spending their (spare) time on the app don't feel appreciated and it won't raise anyone's motivation to look into it (while we still will look into it). So while I value your reports please avoid such rather mocking statements.

**Comment by InfamousUser** [comment]
> While I get the frustration when anyone hits an issue with the app people spending their (spare) time on the app don't feel appreciated and it won't raise anyone's motivation to look into it (while we still will look into it). So while I value your reports please avoid such rather mocking statements.

I am sorry! It was to be read with a slightly humorous note, I guess it doesn't translate well into text. Thanks for filing that bug report, I will attempt to fix that and be more considerate in the future. I'm just a bit frustrated lately by the sheer amount of bugs encountered in the Android app. But I do appreciate all the hard work put into this by all the good people on here, I certainly did not mean to put anybody down. Keep up the good work!

**Comment by AndyScherzinger** [comment]
Thanks for your reply and understanding, really appreciate your comment. Technically speaking I am pretty sure if we can agree on a solution @tobiasKaminsky @jancborchardt that this can be implemented with a small effort :)

**Comment by tobiasKaminsky** [comment]
When did this popup was shown?
Normally it should pop up once you manually upload a file.

It can also happen via auto-upload, and then indeed, it is not very clear which file it is.

What wonders me is, that this seems to be a file without any mimetype/file ending, so that you really only see a random file.

**Comment by tobiasKaminsky** [comment]
My solution would be 
- always show file name
- show local and remote path

**Comment by InfamousUser** [comment]
Was autoupload, I've no clue which file it is. Filenames and paths would be great.

**Comment by jancborchardt** [comment]
Yup – let’s show the filename above the detail info like date and size, done. :)

**Comment by AndyScherzinger** [comment]
> Yup – let’s show the filename above the detail info like date and size, done. :)

@jancborchardt  The file name is the same for both files so should it be shown twice? Or should it be shown above the comparison (and below the description text)?

**Comment by InfamousUser** [comment]
IMO whenever there's a special case like a single name instead of both files having one it's bound to confuse someone.

**Comment by tobiasKaminsky** [comment]
Conflicting file Document bla.pdf
in Documents/Personal/Paperwork

Choose which file to keep.
If you select both versions,…

@jancborchardt 
I added "Conflicting file" as this provides a bit more context.
