### ISSUE TITLE
app crashes when entering server address

### ISSUE THREAD

**Issue by itnrm** [nextcloud/android#6605]
### Steps to reproduce
1. Open app and select Login
2. Input NextCloud server address and press Next
3. App crashes
I have the issue with a next Hetzner NextCloud server (https://nx***.your-storageshare.de). Interestingly i didn't have the issue with the OPS ONE server I used before to try out NextCloud.

### Expected behaviour
- Tell us what should happen
Shouldn't crash

### Actual behaviour
- Tell us what happens
App crashes

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

**Works fine with the demo server.**

### Environment data
Android version:
Graphene OS QQ3A.200705.002.2020.07.06.20

Device model: 
Google pixel 4

Stock or customized system:
Graphene OS

Nextcloud app version:
version 3.13.0 RC1

Nextcloud server version:
19.0.1

Reverse proxy:

#### Web server error log
```
No logs visible on the server
```

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.StringIndexOutOfBoundsException: length=0; index=0
	at java.lang.String.charAt(Native Method)
	at android.graphics.Color.parseColor(Color.java:1384)
	at com.owncloud.android.authentication.AuthenticatorActivity.lambda$onGetServerInfoFinish$1$AuthenticatorActivity(AuthenticatorActivity.java:893)
	at com.owncloud.android.authentication.-$$Lambda$AuthenticatorActivity$g_zVBViOB26G6xUOhChyojAZ4Ck.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:919)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130051
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: Android
Device: flame
Model: Pixel 4
Id: QQ3A.200705.002
Product: aosp_flame

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 2020.07.06.20

```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
Thanks for the report @itnrm 
This has been fixed/shipped with 3.13.0 RC2, please update 👍 

Fix is #6585 or #6593 respectively
