### ISSUE TITLE
Current nextcloud app is broken with images

### ISSUE THREAD

**Issue by srednax** [nextcloud/android#6606]
### Steps to reproduce
1. go to a nc folder with some images
2. try to view them 
3. you see the last image you synced ALWAYS.

### Expected behaviour
- Tell us what should happen
I used to be able to browse images and optionally save them to  my device

### Actual behaviour
- Tell us what happens
It is broken

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: /e/ os (lineage OS 0.9-2020061158052)

Device model: Fairphone FP 3

Stock or customized system:

Nextcloud app version: 3.13.0 RC1

Nextcloud server version: 17.0.6

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
This should be solved via RC3, please upgrade and re-open if not.
