### ISSUE TITLE
Sharing multiple files/images

### ISSUE THREAD

**Issue by srednax** [nextcloud/android#6607]
### Is your feature request related to a problem? Please describe.
I can't share multiple images from nc ie to instagram. Or anything at all. With multiple files selected, share is not an option

### Describe the solution you'd like
Share should be an option with multiple files selected.

### Describe alternatives you've considered
I download images to my phone using kde connect, but they are already in nc, so double work.

**Comment by mixpc** [comment]
I have been looking for a workaround but no way. Thumbs up for this enhancement!

**Comment by srednax** [comment]
If the images are downloaded/synced in nextcloud it works, because then they show up in the images/galleries on the phone - but that was exactly what I wanted to avoid.However, in gallery apps - I use the open source "Simple Gallery", multiple selected images *can* be shared, though not to instagram as posts - but as stories. Maybe because they are files and not links?

**Comment by tobiasKaminsky** [comment]
This is fixed via https://github.com/nextcloud/android/pull/6990 and will be in next upcoming version.
