### ISSUE TITLE
Option to ignore "not enough space" warning when syncing

### ISSUE THREAD

**Issue by littleboxis** [nextcloud/android#6612]
### Is your feature request related to a problem? Please describe.
I want to sync my music library (around 200 GB). My mobile phone has 250GB of storage. If wifi connection drops and I want to resume the sync at some point I just can't because it calculates with the complete 200 GB library, ignoring what was already synced before. I just can not sync my entire library with the state the app is in now. 

### Describe the solution you'd like
Add another option like "ignore warning, proceed with sync anyway" if the app deems free disk space not enough.

### Describe alternatives you've considered
Only option right now is for me to install an older version of NC for Android and upgrade to the newest after that. 
I also manually copied my music library to mobile phone. However, NC app does not seem to sync changes anymore (e.g. deleted songs etc.)

### Additional context
I get why the free disk space check was implemented, however I know what I am doing with my device.. At least give me an option to ignore, please
This is similar to issue [6446](https://github.com/nextcloud/android/issues/6446)

Cheers guys!

**Comment by datenimperator** [comment]
Same here. IMO synchronizing should not check at all whether the complete storage requirement is met. Esp. when syncing against a target folder that is not empty. (Because it probably already contains parts of the source folder)

**Comment by tobiasKaminsky** [comment]
There was a bug in the computation if enough space is available.
I think this is fixed now and thus we do not need this manual option.

Assumption is now:
if one downloads a file, app needs at least the same size, as the file needs to be stored temporarily, independent if the file is already downloaded.
If one downloads a folder, only diff between actual folder size on Android and total size on server is needed as remaining space.
