### ISSUE TITLE
Rich workspaces: Readme.md markdown is not rendered correctly

### ISSUE THREAD

**Issue by fgtham** [nextcloud/android#6636]
Rendering of inline code spans in Readme.md is broken. Code blocks are not affected.

### Steps to reproduce
1. Create Readme.md containing inline code span.
2. Open folder in App.

### Expected behaviour
- As the Readme.md contents are displayed on top, the inline code span is readable.

### Actual behaviour
- The code span is hidden behind a black bar.

![Screenshot_20200804-114528_Nextcloud](https://user-images.githubusercontent.com/1180356/89282556-ffc1be80-d64b-11ea-8bd5-b36bb4ac834c.png)

When I tap on the note to display its contents, it is rendered ok:
![Screenshot_20200804-114538_Nextcloud](https://user-images.githubusercontent.com/1180356/89282631-1b2cc980-d64c-11ea-9cc6-c13f35792ed5.png)

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger is this maybe due to the shader?
Other than that there is no difference between preview and full view, as far as I remember.

**Comment by AndyScherzinger** [comment]
> @AndyScherzinger is this maybe due to the shader?

Afaik we dropped the shader and started using a overlay image, see https://github.com/nextcloud/android/pull/6222

@fgtham which version of the app are you using?

**Comment by AndyScherzinger** [comment]
Looking at https://github.com/nextcloud/android/pull/6222/commits/94b31a0a3709b45755c1ea924a2888c3be57bf6c this ships with 3.13.0 So if you run an RC (via GPlay) you'l already have the fix.
