### ISSUE TITLE
[3.13.0RC1] Black + sign in sharing dialog

### ISSUE THREAD

**Issue by splitt3r** [nextcloud/android#6647]
### Description
- The + sign in the sharing dialog is black on a very dark background (with dark theme enabled). On the device screen it is very hard to even see it. I think it should be white.

### Environment data
Android version: 10

Device model: OP 6

Stock or customized system: Stock

Nextcloud app version: latest RC from Play Store

Nextcloud server version: 19

Reverse proxy: None

### Screenshot

![image](https://user-images.githubusercontent.com/1869584/89381996-4f5ec380-d6fa-11ea-821e-2525de30fd2b.png)

**Comment by AndyScherzinger** [comment]
Nice catch @splitt3r - fix is on its way 👍

**Comment by AndyScherzinger** [comment]
See the 3-dot icon, it should actually be grey600 for light and dark 👍

**Comment by splitt3r** [comment]
Btw. the new design looks awesome and i love how Deck + Notes + Files app share the design language now. Great work @AndyScherzinger @stefan-niedermann and all the others ❤️

**Comment by AndyScherzinger** [comment]
Thanks! The new design has mainly been implemented by @JorisBodin @Shagequi @sirambd 🎉
