### ISSUE TITLE
20170216 Cachesize

### ISSUE THREAD

**Issue by JSoko** [nextcloud/android#665]
### Actual behaviour
Just a small thing:
- enter 100 as cachesize: cachesize will be set to 100 MB
- enter 0100 as cachesize: cachesize will be set to 64 mb
- enter 0700 as cachesize: cachesize will be set to 448 MB
- enter 018 as cachesize: app crashes 
- enter 008 as cachesize: app crashes 
### Expected behaviour
- Also cachesizes with leading 0 should be handled correct
 
### Steps to reproduce
see above

### Environment data
Android version:
7.0
Device model: 
sgs7
Stock or customized system:
stock 
Nextcloud app version:
beta 20140216
Nextcloud server version:
11.0.2RC1
#### Web server error log
Nothing related
#### Nextcloud log (data/nextcloud.log)
Nothing related

**Comment by JSoko** [comment]
Issue exists also in 270217

**Comment by tobiasKaminsky** [comment]
Yes, as nobody fixed the bug. ;-)
As soon as I (or someone other) fixed it, I will reply and then you can test it.

**Comment by tobiasKaminsky** [comment]
As we want to do cache sizing with a better approach and not setting it manually, I am closing this one.
