### ISSUE TITLE
Storage continuesly increasing, not possible to reclaim file space

### ISSUE THREAD

**Issue by radoeka** [nextcloud/android#6658]
### Steps to reproduce
1. Upload photo's taken with smartphone to PC via Nextcloud file sync (upload files from other app)
2. Move the uploaded photo's at the PC to a different directory outside Nextcloud
3. Sync Nextcloud app again.  Photo's are no longer visible in Nextcloud app (as expected)

Some time later, when the above procedure is used multiple times.  It appears that the Nextcloud file space is the highest on my phone :(

I can get make it (much) lower by removing photo's from: Internal storage > Android > media > com.nextcloud.client > nextcloud > tmp > used@nextcloud.domain.tld > ......

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### See Also
- Report #2532, although closed I still encounter this issue
- https://help.nextcloud.com/t/high-storage-space-usage-by-android-app/53026
- Related to #6558?

### Environment data
Android version: 9
Device model: Samsung Note-8
Stock or customized system: stock
Nextcloud app version: 3.12
Nextcloud server version: 15.10
Reverse proxy: n

**Comment by tobiasKaminsky** [comment]
> I can get make it (much) lower by removing photo's from: Internal storage > Android > media > com.nextcloud.client > nextcloud > tmp > [used@nextcloud.domain.tld](mailto:used@nextcloud.domain.tld) > ......

Which files are in there?
Those you uploaded? Is this affecting all uploads, or only auto upload?

**Comment by radoeka** [comment]
There are the files that I uploaded manually.  I don't have auto upload enabled.  Hence, I can only tell about the manual uploaded files.

**Comment by tobiasKaminsky** [comment]
How do you upload the files?
- open NC, tap + button and select "upload files" (with which options then?) or "upload content from other apps?
- share files from another app to NC app?

**Comment by radoeka** [comment]
Sorry for my slow response!

> How do you upload the files?
> 
> * open NC, tap + button and select "upload files" (with which options then?) or "upload content from other apps?

* Open NC app.  Select folder Photo/Android
* Press '+'
* Upload content from other apps
* Select photo's (many)
* Press Open

That's it.

**Comment by tobiasKaminsky** [comment]
Do all of those files then remain in tmp? 
Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

**Comment by radoeka** [comment]
> Do all of those files then remain in tmp?

That's my impression, indeed.

> Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

I don't have this installed, I can therefor not provide this information sorry.

Isn't this easily reproduceable?  It it reproduceable, or am I the only one experiencing this?

**Comment by tobiasKaminsky** [comment]
> Isn't this easily reproduceable?

No, we rely on deleting/moving files via Android's regular tools.



> It it reproduceable, or am I the only one experiencing this?

Not for me, also not on my productive device, which I use very heavy.
The tmp folder is 1<Mb.

**Comment by tobiasKaminsky** [comment]
Maybe this is some sort of permission problem…
Are you allowed to delete those tmp files?

**Comment by radoeka** [comment]
I'm allowed to remove the files manually.
It's a company device has MS Company Portal installed and activated.  Perhaps that have something to do with it, but I doubt it.

**Comment by tobiasKaminsky** [comment]
If you cannot delete this file, then the app also cannot delete it.

**Comment by radoeka** [comment]
@tobiasKaminsky: I can delete the files, see my previous update to this ticket.

**Comment by tobiasKaminsky** [comment]
Ah, then I misread this…
Then I fear I have no clue, if we cannot get the logcat…
