### ISSUE TITLE
[3.13.0RC3] unable to sort folder name when choosing menu load app file

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/android#6659]
when you choose upload file the folders to browse do not have the button to be sorted in alphabetical order, they are ordered from z to a and you cannot order from a to z only in the choice of files to upload this in nextcloud app 3.13 rc3

![Screenshot_20200806-153507_Nextcloud](https://user-images.githubusercontent.com/35575744/89538134-7a304100-d7fa-11ea-9b52-99acbcd7ada0.jpg)

**Comment by tobiasKaminsky** [comment]
We should also add this for RC4
