### ISSUE TITLE
[Feature request] Automatic Upload of files / directories other then Pics and Video

### ISSUE THREAD

**Issue by hitam4450** [nextcloud/android#666]
Hello to all,

I currently use several logging apps (finance, time-sheet, trip logger, etc ) and they all provide a backup of there input data onto the device (internal or external) storage! Instead of uploading them one by one manually, it would be more advantageous by creating rule(s) to upload them automatically to a specific upload folder in Nexctcloud!

 I am sure many other users feel a similar way  or even the same way !

What is the opinion of the community ?

Best Regards, hitam4450

**Comment by tobiasKaminsky** [comment]
Yes, this is planned and already wished in #21: 
The next step of extending auto upload will be that you can choose any local folder on your device. Every new file will then be auto uploaded to the corresponding server folder (which is already chooseable).

@AndyScherzinger

**Comment by hitam4450** [comment]
@tobiasKaminsky Well, thanks for the feedback and good to know, that this feature is WIP!

Keep up withe good work !

regards, hitam4450

**Comment by JSoko** [comment]
Rule #1, never ask for ETA’s ;-)

It'll come As early as possible and as late as necessary...

**Comment by mario** [comment]
Available in 2.0.0RC9.
