### ISSUE TITLE
[3.13.0 RC4] Unable to display 12-digit mnemonic code in app

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/android#6675]
unable to display 12-digit mnemonic code in app, 

the application crashes when I try to view the 12 digits of my mnemonic in the setup menu.  I attach crash photos

![Screenshot_20200808-072646~2](https://user-images.githubusercontent.com/35575744/89703262-3435c300-d949-11ea-9f9d-b3b79d19b6db.png)

![Screenshot_20200808-072550](https://user-images.githubusercontent.com/35575744/89703268-3d269480-d949-11ea-9601-30c4a8fd1fb1.png)

**Comment by AndyScherzinger** [comment]
Thanks for the report @tigernero79 ❤️ fix is provided via #6701 and should ship with next RC
