### ISSUE TITLE
Folder sync

### ISSUE THREAD

**Issue by proninyaroslav** [nextcloud/android#668]
Hello. Will the implemented ability to folder synchronize, as is done in the client for OwnCloud https://github.com/owncloud/android/issues/1136 ?

**Comment by JSoko** [comment]
It's on the roadmap: #285

**Comment by mario** [comment]
Either that or if I understood the request right, we also have "Set as available offline" already baked in.

**Comment by twixi** [comment]
Very need full sync from Server to phone and vice versa too!

**Comment by tobiasKaminsky** [comment]
This is already planned (and briefly described) here: #285

**Comment by AndyScherzinger** [comment]
Well, the original request referes to oC's "set available offline" functionality for folders not just files which is slightly different. Whenever #285 comes to life for customer folders + 2-way sync we have a comparable offer which works slightly different. It wouldn't be a sync of a server folder to a local folder *within* Nextclouds storage path on the phone but any storage path on the device. 

Still fine with me and even more flexible.

**Comment by natrius** [comment]
I hope https://github.com/nextcloud/android/issues/285 this will be finished soon as it seems it has the potential to solve some syncing problems with some apps as well. If i understand it correctly if 285 is in place, i can just choose to 2way sync the diary folder from https://github.com/billthefarmer/diary/issues/42 and there is no need for billthefarmer to implement a nextcloud sync by himself?

Many thanks for you work!

**Comment by joshtrichards** [comment]
Duplicate of #269
