### ISSUE TITLE
[3.13.0 RC4] Dual loading animation

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/android#6684]
### Steps to reproduce
1. Launch the app.
2. Quickly select "Photos" from the menu while the loading wheel is still visible for "All files".

### Expected behaviour
- **Only** one loading wheel.

### Actual behaviour
- Double load wheel for "Photos" while "All Files" is still loading.

![obraz](https://user-images.githubusercontent.com/47037905/89763647-3dfb2a00-daf3-11ea-80a1-40c60971dcd6.png)

**Double charging also appears when we enter "On device" or "Shared" and refresh by swiping down.**

### Environment data
Android version: 10

Nextcloud app version: 3.13.0 RC4 and Dev 20200809

**Comment by Valdnet** [comment]
Double charging also appears when we enter "On device" or "Shared" and refresh by swiping down.

**Comment by Valdnet** [comment]
In the new **3.13.0** version the problem still occurs on "Shared" and "On device".

![obraz](https://user-images.githubusercontent.com/47037905/90504561-91075980-e151-11ea-9b11-768f092aba22.png)
---

![obraz](https://user-images.githubusercontent.com/47037905/90504654-ae3c2800-e151-11ea-8f20-6cfd8d141bd3.png)

However, in "Photos" no loading animation is displayed now  :stuck_out_tongue_winking_eye:.

![obraz](https://user-images.githubusercontent.com/47037905/90504604-a086a280-e151-11ea-8085-c07655510e6f.png)

App:
Android 10

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger I am thinking about removing the big spinner entirely.
Do you have any objections?
I think we have in all view the tiny spinner?

**Comment by AndyScherzinger** [comment]
Sounds good to me while I can't say for sure if we have the small spinner everywhere, so it's worth a shot 👍
