### ISSUE TITLE
Nextcloud app can't open file with wrong coding standard

### ISSUE THREAD

**Issue by pawlosck** [nextcloud/android#6685]
### Steps to reproduce
1. Upload file with wrong coding (file with polish letters, but with wrong coding standard). Probably file saved under Windows and modified under linux few years ago.
2. Try to open this file under Android - there is only information "loading taking longer than usually". No errors in app, nextcloud logs (server) and in apache logs. File can't be opened.

Nextcloud under Firefox show strange signs instead polish letters. When I removed these signs, android app could open this file.

### Environment data
Android version: 9.0

Device model: Samsung Galaxy S8

Stock or customized system: original Android without modifications

Nextcloud app version: 3.13.0 RC4 - bug exists in previous versions too

Nextcloud server version: 19.0.1

Reverse proxy: no

**Comment by tobiasKaminsky** [comment]
@juliushaertl do you have an idea why Text app makes a difference if opened within Android or within web ui?

**Comment by juliushaertl** [comment]
It should not. @pawlosck Are you able to share an example file that works on the web but not on android?

**Comment by pawlosck** [comment]
@juliushaertl  No problem, but how can I attach this file to issue?
You can try yourself to prepare file.
Try to create file with polish letters and coding "windows-1250" (I used kate - linux text editor)
Save file
upload file into nextcloud via firefox (linux desktop)
File can be opened in firefox (there are no visible polish letters, but file can be opened)
The same file can't be opened in android nextcloud app.

**Comment by juliushaertl** [comment]
Might be a similar issue as https://github.com/nextcloud/text/issues/405 We currently don't have any logic for supporting other encodings, so I'd generally recommend to stick with UTF-8. 

However that still of course doesn't explain why it works in the web then. You can upload a file just by dropping it into the text field of the github issue.

**Comment by pawlosck** [comment]
Yes, I think, these issues are connected.
I understand, that you are support utf-8 only, but should be any info, why file can't be opened if you can't fix it. Message "loading taking longer" is not nice for non technical people. Maybe any timeout with suggestion to check file in web browser.

[test_ąś3.txt](https://github.com/nextcloud/android/files/5142207/test_as3.txt)

**Comment by AndyScherzinger** [comment]
@juliushaertl so close this one in favor of nextcloud/text#405 ?

**Comment by juliushaertl** [comment]
Yep, i think there is nothing that would need to be handled on the android app :+1:
