### ISSUE TITLE
auto-upload distant subfolder configuration

### ISSUE THREAD

**Issue by guillaume-smo** [nextcloud/android#6686]
### Steps to reproduce
1. select a local folder to auto-upload from nextcloud app on Android (/storage/SDCARD/DCIM/Camera for example)
2. select a distant folder (/Photos/ folder)
2. tick "use subfolder" option (it will create a /Photos/2020/08 folder)
3. wait for the auto upload to start and check the directory where the files are saved on the server

### Expected behaviour
- I would expect the folder content (photos in /storage/SDCARD/DCIM/Camera) to be saved directly in the configured destination folder (/Photos/2020/08).

### Actual behaviour
- Instead, the folder to auto-upload is recreated inside the destination folder (/Photos/2020/08/Camera). Is it possible to configure more precisely the distant folder path ? Or would it be possible to add this option please ?
In my case, I would like to backup the pictures from /storage/SDCARD/DCIM/Camera directly in /Photos/2020/08 and not in /Photos/2020/08/Camera.
Thanks. 

### Can you reproduce this problem on https://try.nextcloud.com?
nope (android app needed)

### Environment data
Android version: 10

Device model: Samsung S7

Stock or customized system: Lineage 17.1

Nextcloud app version: 3.12.1

Nextcloud server version: 18.0.7

Reverse proxy: nope

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Can you name an example, with paths, so that I can understand the problem better?

**Comment by guillaume-smo** [comment]
> Can you name an example, with paths, so that I can understand the problem better?

I have updated the issue with examples, I hope it clearer now, thanks !

**Comment by tobiasKaminsky** [comment]
>     1. select a local folder to auto-upload

Is this offered to you by auto-aupload file list?
Or did you create it by your own with "set up a custom folder"?

**Comment by guillaume-smo** [comment]
I added it myself with the "setup a custom folder" option

**Comment by tobiasKaminsky** [comment]
From my tests this seems only to be possible if 
/storage/SDCARD/DCIM
was used instead of
/storage/SDCARD/DCIM/Camera

as then the subfolder structure is recreated.

**Comment by guillaume-smo** [comment]
the problem is that if I select /storage/SDCARD/DCIM as suggested, the folders inside /storage/SDCARD/DCIM (such as "Camera" folder and the photos inside) won't be uploaded (it appears that subfolders inside the selected folders are ignored)

**Comment by tobiasKaminsky** [comment]
> it appears that subfolders inside the selected folders are ignored

That is strange. For me it works fine. (this does not help you much, but it means that it so general issue)
Unfortunately I have no clue what could go wrong…
