### ISSUE TITLE
Nextcloud client leaves empty space at top of list after removing folders to sync

### ISSUE THREAD

**Issue by dodancs** [nextcloud/android#6687]
### Steps to reproduce
1. Add folders and files into your cloud in the span of over a year and a half
2. Remove some folders to gain free space
3. Refresh Android app to see this:
![issue](http://puu.sh/GguLg/440b55cf1b.jpg)

### Expected behaviour
- There should be no empty space where the old folders were, the list should just show the files and folders that are present in the cloud.

### Actual behaviour
- There is a lot of empty space in the app, and even after a refresh and force-kill of the app, it still remains broken (maybe the app thinks there still should be some folders that have been long removed).

### Can you reproduce this problem on https://try.nextcloud.com?
- I cannot reproduce this on the demo nextcloud. I cannot add another account to the Android app.

### Environment data
Android version: 10.3.5

Device model: OnePlus 6

Stock or customized system: Stock OxygenOS

Nextcloud app version: 3.12.1

Nextcloud server version: 18.0.7

Reverse proxy: Nginx

#### Web server error log
```
N/A
```

#### Nextcloud log (data/nextcloud.log)
```
N/A
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
@dodancs can you update to the latest RC4 of 3.13.0? I guess what you actually see is an empty "richspace" (#5803) this is part of Nextcloud 19 I think and would display the first lines of a Readme.md file if present. Unfortunately before the referd fix it might just display an empty area otherwise. So worth a try :)

**Comment by dodancs** [comment]
@AndyScherzinger just tried the 3.13.0 RC4 as a beta tester, and I can report that the issue is still present.
![issue2](http://puu.sh/GgEJm/785f909cf8.jpg)

As you mentioned the Readme.md file. I did not even notice I had one in there. I just deleted it, and the empty space at the top disappeared! So overall, you are correct, it was the Readme rich text block that was showing up. I just had no idea, there was a feature like this. It got me real confused.

**Comment by AndyScherzinger** [comment]
> As you mentioned the Readme.md file. I did not even notice I had one in there. I just deleted it, and the empty space at the top disappeared! So overall, you are correct, it was the Readme rich text block that was showing up. I just had no idea, there was a feature like this. It got me really confused.

Thanks for the feedback @dodancs, I'll close the issue then. App version 3.10 introduced this on the Android client side: https://nextcloud.com/blog/nextcloud-3-10-0-for-android-is-here-bringing-collaborative-tools-dark-mode-rich-workspaces-and-more

**Comment by AndyScherzinger** [comment]
Happy we could clarify this matter 👍
