### ISSUE TITLE
No permission to upload 

### ISSUE THREAD

**Issue by YouveGotMeowxy** [nextcloud/android#6691]
I get this every time , with auto upload...

![Screenshot_20200719-221358_One-UI-Home](https://user-images.githubusercontent.com/39491297/87896519-117d5200-ca0e-11ea-9a40-52ecd1d5c734.jpg)

Batt saving is disabled, and I'm not using a VPN.

### Environment data

Model: SM-N975U1
Brand: samsung
Product: d2que
Device: d2q
Version-Codename: REL
Version-Release: 10 

Nextcloud app version: 3.130 RC4

Nextcloud server version: 18.0.7

Reverse proxy:

#### Nextcloud log (data/nextcloud.log)
```
Nextcloud APP log: https://pastebin.com/p0xrkXiW
```

**Comment by majorvin** [comment]
Same here. Time to time I also get server is on maintenance mode ..

**Comment by tobiasKaminsky** [comment]
No idea what could cause this, but this if server is on maintenance mode, this is server related, not client specific.
