### ISSUE TITLE
App shouldn't ask which version to pick during a file conflict with 0 byte files

### ISSUE THREAD

**Issue by YouveGotMeowxy** [nextcloud/android#6692]
I *constantly* get this error message in my notifications, to the point it's driving me batshet crazy. As soon as I delete the notification, it just returns, incessantly.

### Steps to reproduce
1. No idea, it just happens.

I *think* it happens when I manually delete an image from my gallery, while auto-upload is on.

### Expected behaviour
- Nothing. If the app detects a comparison of a 0 byte file on the server, and locally, just ignore the entire thing.

### Actual behaviour
- 2 things happen, and not predictably;

1. It might show the actual comparison dialog, where it shows both the local and remote files as 0 bytes.

or

2. I just get a small toast notification:

![image](https://user-images.githubusercontent.com/39491297/89976818-2f199200-dc2f-11ea-987e-2ff756aa64f7.png)

### Environment data

Model: SM-N975U1
Brand: samsung
Product: d2que
Device: d2q
Version-Codename: REL
Version-Release: 10 

Nextcloud app version: 3.130 RC4

Nextcloud server version: 18.0.7

**Comment by YouveGotMeowxy** [comment]
I see this ALL the time ....

![image](https://user-images.githubusercontent.com/39491297/90582340-119a7a00-e193-11ea-865a-f5adf67286c9.png)

**Comment by tobiasKaminsky** [comment]
Do you see this file (5 days ago) in your upload queue?

**Comment by bahbarnett** [comment]
FYI, I have this precise same issue.  Yet, both my files list "1969", see attached.

![Screenshot_20200908-074138_Nextcloud](https://user-images.githubusercontent.com/2877914/92519160-0920e680-f209-11ea-971b-8e8d76f9a065.jpg)

A couple of things; there's no filename, for some reason.  And the dates, and of course, 0 bytes.  I'm not sure why it's trying to sync a completely non-existent file, with a non-existent file.

Any info you want?  I literally have this notification constantly there.  I can cancel/overwrite/accept/whatever.  I just keeps coming back.  Over and over.

**Comment by YouveGotMeowxy** [comment]
Just a note, I *think* the error creating dialog might be due to the app needing to be logged into first, and my phone is setup to use my fingerprint for all logins, including the NC app.

I get that error when tapping the notification; it then tries to show the NC app, but first I have to use my fingerprint. Usually if I have the NC app already running in the background and recently used it so the login hasn't timed out yet, and then tap that error notification, that error doesn't show up.

**Comment by tobiasKaminsky** [comment]
In Google Play store there is 3.13.1 RC1 as beta available.
Can you give this a try?

**Comment by 1989gironimo** [comment]
On 3.13.1 is the issue still there.

**Comment by bahbarnett** [comment]
Yes, still there.  It really makes this app look quite bad, when its code is so completely broken.  It's literally a trust issue, in that, I don't even remotely trust it not to delete/turf/lose files.

Before 3.13.1, it would report a 0 byte file for conflicts.  It would also randomly garble the name.  

Now it *seems* to take the new version of the file, but will never, ever be satisfied.  For example:

- I share a file with nextcloud
- file results in a conflict, as a copy already exists
- I say 'take new version', it seems to do so
- within a second or two, it now again prompts for a file conflict, but now it lists two identical files.

It appears that the file is conflicting with itself!

Worse, it never, ever, ever ends. Ever.  No manner of 'cancel', or any 'ok' choice (eg, either file) does anything.  The dialog vanishes, only to re-appear.  Force-stopping nextcloud app doesn't help, it just re-prompts.

The only way to end this pain, is to go into the app, go to uploads, and manually delete the unresolved conflict there.  Yet it says "delete"!  Luckily, it doesn't delete the file, just the reference to the conflict in the upload list.

**Comment by tobiasKaminsky** [comment]
Fixed via #7102 
There is an APK file in this PR, which you can install in parallel to your existing Nextcloud app.
