### ISSUE TITLE
emty line with path / readme.md

### ISSUE THREAD

**Issue by eblasc** [nextcloud/android#6694]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.IllegalArgumentException: No suitable parent found from the given view. Please provide a valid view.
	at com.google.android.material.snackbar.Snackbar.make(Snackbar.java:158)
	at com.owncloud.android.utils.DisplayUtils.showSnackMessage(DisplayUtils.java:649)
	at com.owncloud.android.ui.preview.PreviewTextStringFragment.lambda$edit$1$PreviewTextStringFragment(PreviewTextStringFragment.java:174)
	at com.owncloud.android.ui.preview.-$$Lambda$PreviewTextStringFragment$fDSIsNZagYwxFSLhq1IBY22AQB8.run(lambda)
	at java.lang.Thread.run(Thread.java:818)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30120190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: ZTE
Device: ZTE_BLADE_V0720
Model: ZTE BLADE V0720
Id: MRA58K
Product: P635A32

************ FIRMWARE ************
SDK: 23
Release: 6.0
Incremental: 1486948919

```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Is this file specific, e.g. works it with other text files?
Can you then share/paste the file in question?
