### ISSUE TITLE
.exe files renamed when uploading via android filebrowser

### ISSUE THREAD

**Issue by psyca** [nextcloud/android#6696]
### Steps to reproduce
1. Select an .exe file on your smartphones filebrowser (in my chase "Eigene Dateien" App from Samsung)
2. Choose to share it with nextcloud (app) / choose to upload the file
3. The file gets uploaded but not with its original name. It replaces the name with a 4-dig number and also removes the .exe

### Expected behaviour
- If you upload "filename.exe" it should upload the file as "filename.exe" and not as (e.g.) "8504" or other number

### Actual behaviour
- It uploads it with an filename with 4 numbers and no .exe at the end

### Can you reproduce this problem on https://try.nextcloud.com?
- This happens to me only, if i upload the file over the filebrowser and select "share with" - "nextcloud". If i upload it from the app directly, then everything seems ok.

### Environment data
Android version: 9.0

Device model: Samsung Galaxy S8

Stock or customized system: Stock

Nextcloud app version: 3.12.1

Nextcloud server version: 19.0.1

Reverse proxy: no

---

Note: Maybe its also an behavor of the Samsung Filemanager. Cant check it directly

**Comment by tobiasKaminsky** [comment]
> Note: Maybe its also an behavor of the Samsung Filemanager. Cant check it directly

This indeeds sound like Samsung.
Can you install any other File Manager and try it again?

**Comment by psyca** [comment]
Why i hadnt tested it before with an different one :(
Its samsungs filemanager

*closing*
