### ISSUE TITLE
Auto-upload on WiFi only 

### ISSUE THREAD

**Issue by jesulo** [nextcloud/android#6697]
Hi, I don t find this option in app any more, where is? Auto-upload on WiFi only enabled. Regards

**Comment by AndyScherzinger** [comment]
Choose the config of the respective folder within the auto upload list which opens a dialog with all details regarding the folder's config. This is where you'll find setting.

**Comment by jesulo** [comment]
Before there was a very useful option, in configuration, to enable the load
when only the wifi is on, for when I entered the application and wanted to
upload a photo directly to a folder on the server, not on my mobile.  This
option is no longer available?
I tested now and upload photo without wifi

**Comment by AndyScherzinger** [comment]
@jesulo what do you mean? For manual uploads there has never been a setting for wifi-only, this only exists (and is still there) a setting on each auto upload folder item.

**Comment by jesulo** [comment]
Hi @AndyScherzinger
 I used owncloud previously, maybe there was that option, although currently I can't find it.  Well, I am really interested in it is for example to enter the application and take a photo and that it does not load unless the Wi-Fi is connected.  how can I do this?

**Comment by AndyScherzinger** [comment]
> Well, I am really interested in it is for example to enter the application and select take a photo and that it does not load unless the Wi-Fi is connected. how can I do this?

1. Go to "Auto Upload" in the main menu
2. Click on the 3-dot icon on the respective camera folder (the app lists any folder containing images or videos)
3. Activate is (switch at the top of the opened dialog)
4. See all Auto Upload details and for the upload on unmetered wifi, activate it
5. hit save

Your done :)

**Comment by AndyScherzinger** [comment]
Beware that is is an upload automation for camera photo, taken with the camera app. The app also allows to take images _within_ the app (+ Button) which always be uploaded no matter the connection.

**Comment by jesulo** [comment]
take images *within* the app (+ Button) which always be uploaded no matter
the connection.

I want this, but just for let upload by wifi, not for móvil data(   block
use with data  )is possible?

**Comment by AndyScherzinger** [comment]
I want this, but just for let upload by wifi, not for móvil data(   block
use with data  )is possible?

Not at the moment (also not planned afaik)

**Comment by jesulo** [comment]
I understand, so I must use an older version of owncloud, because that
option is present before.  Thank you

**Comment by AndyScherzinger** [comment]
Happy to help :)
