### ISSUE TITLE
Feature Request: Prevent duplicate uploads

### ISSUE THREAD

**Issue by jasonbayton** [nextcloud/android#67]
## Wanted behaviour

When I attempt to upload a duplicate file, I'd like it to prompt me before it uploads. Maybe a message that states "x with that name and datestamp already exists. Upload another copy?"

In an ideal world it would be able to do this with several files in one go, rather than 1 by 1 so as to agree or disagree with duplicate uploads all at once, but anything would be acceptable at the moment.
## Actual behaviour

Currently uploading duplicates just appends a number in brackets, meaning I then later have to manually remove duplicates.

Context: 
https://help.nextcloud.com/t/is-there-anything-to-stop-duplicates-being-uploaded/1146

**Comment by mar1u5** [comment]
@tobiasKaminsky

**Comment by tobiasKaminsky** [comment]
The datestamp is not reliable on android so I suggest to only use the file name for comparison.
Just like any file browser it should be checked prior to upload if any conflicts occur:
- show a conflict side by side with thumbnail, file name (and file size)
- button: suggest new name (by adding (1,2)), overwrite, skip
- checkbox: do this for x pending conflicts

**Comment by Spacefish** [comment]
Another reason to add a filehash in file_cache table inside the server side php script.. That way it´s possible to detect real duplicates, disregarding the filename or m/ctime

**Comment by mario** [comment]
This will have to work only on filenames, but I can look into it - thanks :)

**Comment by jasonbayton** [comment]
Based on latest RC this isn't implemented - at least on Auto upload?

**Comment by xXSTrikeXx** [comment]
New issues: #1685 
Discussion in #1686

**Comment by jtagcat** [comment]
Please add per-directory defaults (always keep both or only newest or only oldest file).

Every day I get a notification of 'please resolve conflict' for files created by [other app's backups](https://github.com/fedefernandez/MyAppList) or editing an image locally.

**Comment by AndyScherzinger** [comment]
@jtagcat that has been implemented for auto upload with the latest, already released feature release, please update to 3.11 if you haven't already done so and check the auto upload settings.
