### ISSUE TITLE
Nextcloud android app can't connect to OwnCloud server

### ISSUE THREAD

**Issue by gsedej** [nextcloud/android#6705]
### Steps to reproduce
1. install nextcloud app from f-droid (ver 3.12.0)
2. connect to owncloud (e.g. https://demo.owncloud.org/)
3. login

### Expected behaviour
- the app-wise login and app-wise behaviours

### Actual behaviour
- html webpage is displayed when logging in and after (browser experince)

### Environment data
Android version: 10

Device model: Oneplus Nord and Nokia 6.1 tested

Stock or customized system: Oxygenos and Android One tested

Nextcloud app version: 3.12.0

Nextcloud server version: Owncloud 10.0.10

I have already asked on reddit:
https://www.reddit.com/r/NextCloud/comments/i8y1uu/cant_login_from_nextcloudandroid_to_my_owncloud/

I got new phone (Oneplus Nord), installed Nextcloud-android app from f-droid (3.12.0) and tried to login to my self-hosted owncloud server (10.0.10). When I input server address in nextcloud app it takes me to server's webpage and not app.

On my old phone (Nokia 6.1, android 10) I am able to use app, because I logged in long time ago when using android 8 (before upgrade). My user works on Nokia 6.1+android 10, but if I try to add new user, the same happens (html)

The ownloud-app (from f-droid) works as expected, but nextcloud-app is better.

Here is the login screen 
![image](https://user-images.githubusercontent.com/6927198/90306914-04029d00-ded2-11ea-9d31-7d87ee65e148.png)

the "webpage" of owncloud server login inside nextcloud app
![image](https://user-images.githubusercontent.com/6927198/90306919-0b29ab00-ded2-11ea-90bc-aaa45243bee0.png)

owncloud webpage in nextcloud android application
![image](https://user-images.githubusercontent.com/6927198/90306920-0ebd3200-ded2-11ea-8ea9-5f00e4f5c53f.png)

when set address to owncloud andorid app - the user and password fields appear
![owncloud](https://user-images.githubusercontent.com/6927198/90306989-d10cd900-ded2-11ea-8ddb-19dd54b625e8.jpg)

**Comment by splitt3r** [comment]
I think that recent releaes of the Nextcloud app are not compatible with ownCloud anymore. Why don't you upgrade to the latest Nextclpud version on the server?

**Comment by gsedej** [comment]
I taught own/nextcloud is just branding and default addons thing.
I stopped updating my owncloud instance, since I always had to invest multiple hours to fix some issues. I imagine that converting owncloud to nextcloud would trigger even more issues and time to get it running again.

Is it possible to get old apk? (f droid only have last 3 versions)

**Comment by splitt3r** [comment]
No Nextcloud has a lot of new features that ownCloud has not and also vice versa 😄. I think the login flow is the one that's breaking your ownCloud login here. You should really update your ownCloud / Nextcloud version regularly to prevent security issues! You can find all the Nextcloud Android releases here https://github.com/nextcloud/android/releases.

**Comment by gsedej** [comment]
Thanks for info!

WORKAROUND:
I was able to login using version 3.9
https://github.com/nextcloud/android/releases?after=rc-3.9.1-01
apk: https://github.com/nextcloud/android/releases/download/stable-3.9.0/nextcloud-30090090.apk
login using version 3.9
update new apk from github releases page
(it didn't work via f-droid for me this time)

I will try to update my owncloud and switch to nextcloud.

What to do with this issue? it should be mentioned somewhere. I was not able to find this info elsewhere

**Comment by splitt3r** [comment]
I think this won't become an official how to as it is a pretty hacky workaround. But you are totally right it should gain some visiblity for others to find it. Though my tip would be to pick a goog title + add some keywords / clear information to the main issue description. That way others will find it threw Google or GitHub itself 😃.

**Comment by tobiasKaminsky** [comment]
Owncloud is not supported.
this workaroud might work for login, but maybe will create trouble later.
