### ISSUE TITLE
Wrong stoage path

### ISSUE THREAD

**Issue by Spielmops** [nextcloud/android#6707]
### Steps to reproduce
1. Install Nextloud-client 3.12.0
2. Tap on Settings/storage path. You get 4 choices.Take the 3.: 
/data/user/0/com.nextcloud.client/files
3. Restart the app
4. Downlad anything
5. Start the filemanger and try to lcate the downladed file.
6. No luck ...

### Expected behaviour
- Tell us what should happen
At the intenal sdcard should be a folder "com.nextcloud.client", but there is no such folder
### Actual behaviour
- Tell us what happens
The file is stored at
/data/data/com.nextcloud.clent/files
### Can you reproduce this problem: yes

The problem: on unrooted devices you will never get to the downladed files ...

### Environment data
Android version:
Lineage 16.0
Device model: 
Samsung Tab S2
Stock or customized system:
Liage 16
Nextcloud app version:
3.12.0

Spielmops

**Comment by tobiasKaminsky** [comment]
>     2\. /data/user/0/com.nextcloud.client/files

I might be wrong, but this is a symlink to to /data/data

What are the other options? Isn't there one that fits better?

**Comment by Spielmops** [comment]
No, this links to the internal sd-card for user 0. What the app does: it stores at /data/data/com.nextcloud.client/files. I have rooted devices and can see inside /data/data.

Spielmops

**Comment by Spielmops** [comment]
Perhaps it helps, if I tell the problem more clearly:

If I change the storage-path of the app into

/data/user/0/com.nextcloud.client/files

as offered from the app, I should find the files here (if I’m the only user)

/internal_storage/com.netxtcloud.client/files

but instead the files are here:

/data/data/com.nextcloud.client/files

and a) this is not the offered location and b) you have no access to this location at least up to Android 9. Any advice, what to do?

Additional info:
The real problem ist, that normal users do not locate their files, because they are in

/internal_storage/Android/data/com.nextcloud.client/files/

They do not normally use the "Android"-folder. It would be better, if the nextcloud-folder would be in the root of "internal_storage" or "sd-card" or similar, that is

`/internal_storage/com.nextcloud.client/files/

Best would be:

`internal_storage/Nextcloud/`

Spielmops
