### ISSUE TITLE
regression - can't change sort order

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/android#6716]
Hi,

Great work on the new UI in the lastest beta/rc. Looking very nice!

I can't find the 'sort order' button or setting anywhere, however. That makes the app very hard to use as I have many folders with thousands of files and often I have no idea of the file name or such - I just want to see the most recently touched files and folders on top. That helps navigating quickly to where you need to go.

Did this get lost with the new UI?

### Environment data
Android version: Samsung S10e with latest (stable) android. 9, I think.

Nextcloud app version: running test version from Android app store: 3.13.0RC4

**Comment by jospoortvliet** [comment]
Bizarre - the sort button shows up for my private account, as does the view button. Looking VERY good, even ;-)

But for cloud.nextcloud.com, neither shows. Could it be because of the Workspace being used for the root of my company account? The buttons don't show  up in sub folders, though, even in those that have no readme set. And on my personal account, I see the buttons but can't write above (in the space for the Workspace).

**Comment by AndyScherzinger** [comment]
CC @tobiasKaminsky: Works fine for me on my personal server running 19.0.1 for root/folders with and without rich workspaces

**Comment by tobiasKaminsky** [comment]
Can you share a screenshot with me?

**Comment by jospoortvliet** [comment]
well, bad luck - I can't reproduce it anymore. I killed the app, started it again - it now works properly... I... I dunno what to do ;-)

I fiddled with it, killed it, switched accounts etc. Can'r reproduce... I do wonder how to add text to a Workspace without there already being something, but other than that - I'll close this as I can't reproduce :cry: (or is this good news? :tada: )

**Comment by AndyScherzinger** [comment]
> I do wonder how to add text to a Workspace without there already being something

1. _if_ you don't have a README.md in the folder already, create it via the + Button (-> create folder info)
2. _if_ you do have the md file, simply navigate to it, open it by clicking on it, having text on server-side installed it'll open the web view, add text, save, done

**Comment by jospoortvliet** [comment]
Thanks Andy!
