### ISSUE TITLE
SUPER slow loading in Photos view even without photos

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/android#6717]
### Steps to reproduce
1. go to the Photos view
2. watch it take about a minute with no less than TWO spinners
3. until it tells you... No photos here.

### Expected behaviour
It shouldn't take that long... Navigating through folders etc is perfectly fast!

### Actual behaviour
super duper slow

### Can you reproduce this problem on https://try.nextcloud.com?
Haven't tried, but it is both slow with my private instance and cloud.nextcloud.com - though it is faster with my private instance than cloud.nextcloud.com (and I have pictures on my private instance!)

### Environment data
Android version: Samsung S10e with latest (stable) android. 9, I think.

Nextcloud app version: running test version from Android app store: 3.13.0RC4

**Comment by tobiasKaminsky** [comment]
As discussed this is mainly a problem on server and should be fixed there.
Everything else is just a nasty workaround.
