### ISSUE TITLE
Rename Beta to Nightly

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#672]
As the beta is being built (nearly) every night and to avoid confusion with the Goole Play Store Beta (which is in fact release candidates), I suggest to rename the beta to nightly.

If you are fine with it, I would change only the "visible" names, like icon and fdroid name, but keep the app-id as otherwise all user would have to re-install the app (when installed via fdroid).

@mario @AndyScherzinger

**Comment by mario** [comment]
Sure

**Comment by AndyScherzinger** [comment]
Fine with me 👍

**Comment by tobiasKaminsky** [comment]
![ic_launcher](https://cloud.githubusercontent.com/assets/5836855/23220856/8f688d66-f923-11e6-82d4-33c69df4779d.png)

Hope you are fine with this :-)
I will also update the Contribute.md.
