### ISSUE TITLE
Tiny survey about energy aware software practices.

### ISSUE THREAD

**Issue by moraispgsi** [nextcloud/android#6722]
Dear contributors,

would you be willing to fill in a short 5-10 min survey (https://forms.gle/F3YwtLVKtk47yVhC9) about energy-efficient mobile development practices in the context of my master thesis? It's about raising awareness of software energy practices and about introducing a new open-source tool for helping in that regard. Your input would be greatly appreciated. Thanks a lot!

Ricardo Morais.

**Comment by tobiasKaminsky** [comment]
Thanks, I participated.
I will close it as it was long enough open.

**Comment by tobiasKaminsky** [comment]
I also tried the plugin, but it ran without any code modifications.
Which I think is good :-)

**Comment by moraispgsi** [comment]
Yep, that is good news for this project, thanks for participating :D

**Comment by moraispgsi** [comment]
@tobiasKaminsky Since you have tried LeafactorCI would you be so kind as to fill in the feedback questionnaire (very small as well)? https://docs.google.com/forms/d/e/1FAIpQLSfe7AVxwPI_gtUcV_T6wbWdsG1AP_krP-8lIiM_POGP0hlpxQ/viewform
