### ISSUE TITLE
Android Nextcloud app crash

### ISSUE THREAD

**Issue by j75** [nextcloud/android#6729]
### Steps to reproduce
1. the error message was issued at booting-up my Android phone
2. However, the problem is that I cannot log in to my personal account on my own server, it loops on "Grant access"

### Expected behaviour
- Tell us what should happen
1. to be able to connect to my Nextcloud server (please note that I have the Notes app, and the Android app synchronizes very well with it)
2. when an error happens, the application should be able to post all the required infos to devs without asking for an account on github etc...

### Actual behaviour
- The application stays on the screen with "You are about to grant Xiaomi Redmi 5 Plus access to your Nextcloud access"

### Can you reproduce this problem on https://try.nextcloud.com?
- no, it connects

### Environment data
Android version: 9

Device model: Xiaomi Redmi 5 Plus

Stock or customized system: MCAOSP

Nextcloud app version: 3.12.1

Nextcloud server version: 19.0.1

Reverse proxy:

#### Web server error log
```
172.17.0.1 - - [18/Aug/2020:10:31:19 +0200] "GET /inxcloud/login?redirect_url=/inxcloud/login/flow/grant?clientIdentifier%3D%26stateToken%3DMI9h4xnMmoTiyl0X9PevrNWVt6fJSRgGuQYcS1fm0y9WEy2yobPUlZoyji1NNrqZ HTTP/1.1" 200 3481 "-" "Xiaomi Redmi 5 Plus (Android)"
172.17.0.1 - - [18/Aug/2020:10:31:20 +0200] "GET /inxcloud/index.php/login/flow HTTP/1.1" 200 3163 "-" "Xiaomi Redmi 5 Plus (Android)"
172.17.0.1 - - [18/Aug/2020:10:31:22 +0200] "GET /inxcloud/core/js/oc.js?v=ad7bb0a8 HTTP/1.1" 200 11098 "-" "Xiaomi Redmi 5 Plus (Android)"
172.17.0.1 - - [18/Aug/2020:10:31:23 +0200] "GET /inxcloud/core/img/favicon.ico HTTP/1.1" 304 180 "-" "Xiaomi Redmi 5 Plus (Android)"
172.17.0.1 - - [18/Aug/2020:10:31:23 +0200] "GET /inxcloud/cron.php HTTP/1.1" 200 931 "-" "Xiaomi Redmi 5 Plus (Android)"
```

#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"2fi8V2O8Iv3dVjdlt5ob","level":3,"time":"2020-08-18T08:31:19+00:00","remoteAddr":"172.17.0.1","user":"--","app":"PHP","method":"GET","url":"/inxcloud/login?redirect_url=/inxcloud/login/flow/grant?clientIdentifier%3D%26stateToken%3DMI9h4xnMmoTiyl0X9PevrNWVt6fJSRgGuQYcS1fm0y9WEy2yobPUlZoyji1NNrqZ","message":"session_start(): A session had already been started - ignoring at /var/www/html/inxcloud/lib/private/Session/Internal.php#209","userAgent":"Xiaomi Redmi 5 Plus (Android)","version":"19.0.1.1"}
{"reqId":"DvhaD0UPhmIwx8qID9al","level":2,"time":"2020-08-18T08:31:20+00:00","remoteAddr":"172.17.0.1","user":"--","app":"core","method":"GET","url":"/inxcloud/index.php/login/flow","message":"Renewing session token failed","userAgent":"Xiaomi Redmi 5 Plus (Android)","version":"19.0.1.1"}
```

**Comment by AndyScherzinger** [comment]
Please provide some information like steps to reproduce the crash, stack traces, etc. and re-open

**Comment by j75** [comment]
I've managed to take a screenshot of the crash, hope it helps.
![Screenshot_Nextcloud_20201030-213018](https://user-images.githubusercontent.com/1899106/97755961-62ffa780-1afa-11eb-96f1-0bd49692f224.png)

**Comment by AndyScherzinger** [comment]
When does this crash happen?

**Comment by j75** [comment]
When logging in the phone after boot, and from time to time.

**Comment by tobiasKaminsky** [comment]
Can you try to copy the entire stacktrace, as this is only Android, and I cannot see where it is triggered in our app.
