### ISSUE TITLE
Regression: no seek bar in internal video playerin 3.13.0

### ISSUE THREAD

**Issue by elpraga** [nextcloud/android#6767]
### Steps to reproduce
1. Play a video (even downloaded) using the internal player
2. 

### Expected behaviour
- a working seek bar

### Actual behaviour
- no seek bar and the buttons do not work

**Comment by AndyScherzinger** [comment]
@ezaquarii is your player fix also closing this issue? Haven't tested (afk) but I'd guess so.

**Comment by tobiasKaminsky** [comment]
Still exists:
![2020-08-28-072858](https://user-images.githubusercontent.com/5836855/91524714-2ba92a80-e900-11ea-8182-902c5abefe56.png)

**Comment by tobiasKaminsky** [comment]
While we are on it, both bars (top and bottom) should also be black so that they do not distract user, same like on preview image)

**Comment by ezaquarii** [comment]
@AndyScherzinger @tobiasKaminsky no, I did not look at this problem.

**Comment by elpraga** [comment]
BTW, would it be possible to add 10s seek when doubleclicking the left and right side of the video respectively (like YouTube player and other do)?

I know it is quite off topic, and certainly not as important as having the seek bar that can actually tell you about the length of the video, but this feature is soooo addictive! :)

Thank you for looking into the missing seek bar issue so quickly!

**Comment by tobiasKaminsky** [comment]
> I know it is quite off topic

Please open up a new issue for this

**Comment by tobiasKaminsky** [comment]
This is fixed by #7339
