### ISSUE TITLE
Instrumentation tests for DocumentsProvider

### ISSUE THREAD

**Issue by grote** [nextcloud/android#6778]
We should add instrumentation tests for Nextcloud's implementation of `DocumentsProvider` that run as part of the CI pipeline to be sure that the support here doesn't break unexpectedly.

**Comment by tobiasKaminsky** [comment]
> @tobiasKaminsky Are there already some test methods in place to wait until background operations have completed and check if files exist on the server, as well as check their size and mimeType there?

No, but you can get inspired by all the instrumentation tests we already have.
https://github.com/nextcloud/android/blob/78cc80266ab445f1d82d8eb7328cc5a381ff58b2/src/androidTest/java/com/owncloud/android/FileIT.java#L44
https://github.com/nextcloud/android/blob/7f339f9fe0821f1a0bdddaa19d49288094f72fa6/src/androidTest/java/com/owncloud/android/UploadIT.java#L166

If you need any info/help, just ping me :+1:

**Comment by joshtrichards** [comment]
Fixed in #6806
