### ISSUE TITLE
Only uploads of current account will be shown in upload

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#678]
With the really great bugfix of autoUpload @mario has changed the scope of the pending/successful/failed uploads in the upload pane.
The previous behaviour was to show all uploads, independent of the current used account. For each upload the targeted account is shown in the remote folder path.
Now (aka in the next version) the user would only see the uploads for the current account.

Two problems:
If an upload will fail the user sees a notification is shown in the top bar. After clicking on it the upload pane is shown, which might (or might not) show the failing upload, depending on the current account.

If a user wants to see if auto upload is working and he is using the "wrong" account he might think that the auto upload never works.

For me this is a real problem as we did not discussed this properly and it can lead to confusing users.

So my idea is to keep the UI behaviour the same as it is now (showing all uploads) and if we agree to do an account separation we should discuss how it can be done.

@AndyScherzinger 
@jancborchardt @eppfel

**Comment by AndyScherzinger** [comment]
I'd say show all upload independent of the current account, which also means when restarted the still need to go to the original account.

**Comment by mario** [comment]
@jasonbayton @Boballen55 @taaem opinions welcome.

**Comment by taaem** [comment]
I'd go for the same UI design as before as it prevents confusion for the most part especially for new users. So show all uploads in the upload pane and at least I would expect it to work like that.

**Comment by jasonbayton** [comment]
I like the idea of splitting uploads. If I'm smart enough to add multiple accounts, I'm smart enough to figure out what uploads show where - it makes sense _not_ seeing uploads for other accounts in _my_ upload view.

On the other hand, if it's a client upload screen, and the uploads are clearly stated to which account they're going (which could be made more apparent though it's OK as is at the moment) it could be fine.

On the issues raised, if errors/notifications pop up pertaining to an account, it should automatically switch to the account being referenced when the app opens - that shouldn't even need discussion :)

**Comment by Boballen55** [comment]
I think leaving it so all uploads are on the same screen would be simpler. The visual indication of which uploads belong in which account could be done. Bold/larger text on account name, grouping account uploads, use the color coded first letters of account names in the uploads screen. 

If they are separated I'd like to see the drop down selector you get when you select the "hamburger" in the upper left to be always visible in the uploads tab once you have more than one account connected.

**Comment by taaem** [comment]
Okay I've got an idea.
In the navigation menu have to separated parts. One for the Files, Auto Upload for the current user and the other for global things eg. Settings. I would then put Uploads there so it is clear that there are all Uploads grouped together in that view.
The Twitter app kinda does this:

![grafik](https://cloud.githubusercontent.com/assets/7108647/23281426/900f6b54-fa1d-11e6-88cc-6ced389ef926.png)

**Comment by OlivierS1** [comment]
I would like to add some more thoughts which comes to mind:
- If multiple accounts and multi upload sources, I think there should also be consideration about prioritizing uploads.
Larger files might prevent uploads of small files waiting in the queue.

- I would also like to be given an option to suspend and resume an upload with a time delay possibly to help speed up some more critical uploads.

**Comment by jasonbayton** [comment]
@OlivierS1 those would benefit being individual issues as they don't relate to this directly.

**Comment by jancborchardt** [comment]
So as I understand there’s two different things here. One is a bugfix to autoupload, and the other is a change in behavior / interface. These should _always_ be separate.

Bugfixes have priority of course. But behavior changes, especially core ones like this, should be properly discussed and communicated.
@mario this is less about »opinions« than about properly communicating and deciding in the open here on the issue tracker, making sure that the core team (for example @AndyScherzinger, @tobiasKaminsky, @eppfel and me) as well as the wider community are in the know and good with the changes.
Collaboration is at the core of why we are successful with Nextcloud, so let’s continue to make it fun for everyone. :)

**Comment by mario** [comment]
I will revert all changes to the Upload interface - I really just want
users to be happy, and they're currently not. That's it.

**Comment by jancborchardt** [comment]
@mario that’s totally ok, of course we all want that. :) Being a community we just have to make sure all team members are happy too, by communicating openly, and separating bug fixes from feature changes.

**Comment by mario** [comment]
All uploads are now shown in that particular PR.

**Comment by mario** [comment]
So I will soon start working on Activities (basically activities + notifications + uploads) - in that view Uploads must be per-user, since activities and notifications will be per user. Please confirm!

**Comment by AndyScherzinger** [comment]
Yes, absolutely :) :+1:

**Comment by jasonbayton** [comment]
👍

**Comment by tobiasKaminsky** [comment]
Fine for me, if we will still have the current upload view with all uploads?

**Comment by mario** [comment]
No we won't since Activities replaces all, and is definitely per-user.

**Comment by tobiasKaminsky** [comment]
Then we are at the beginning that we need a way to show the user the other pending/failed/successful uploads of the other accounts somehow, or?
Would it possible to add an account switcher into the activities view so that a multi-user can easily switch through the account? (having the user to first switch the complete account in order to see the uploads/activities is too much effort for the user)

**Comment by mario** [comment]
Leaving this up to @jancborchardt to decide.

**Comment by eppfel** [comment]
> Would it possible to add an account switcher into the activities view so that a multi-user can easily switch through the account? (having the user to first switch the complete account in order to see the uploads/activities is too much effort for the user)

The account switching is already quite straight forward. I would expect the view staying the same, so if I'm in the new activity stream, slide out the sidebar and tap another account it should the new activity stream of that account.

We could introduce a little notification counter on of the account avatar, like it is in gmail to let users now about activity?

**Comment by jancborchardt** [comment]
> We could introduce a little notification counter on of the account avatar, like it is in gmail to let users now about activity?

Great point @eppfel :) Also I agree that since account switching is so straightforward in our app, things should be separated.

**Comment by mario** [comment]
Done.
