### ISSUE TITLE
Auto file upload wants to upload existing file multiple time without changes

### ISSUE THREAD

**Issue by strassan** [nextcloud/android#6783]
# Description
I use Nextcloud to backup my WhatsApp messages. I do this by auto uploading the "Databases" Folder, which contains the message databases. There is one file that is called "msgstore.db.crypt12", that gets updated daily at ~2am. There's also files 8 days or so, that have a unique name, containing the date (e.g. "msgstore-2020-08-23.1.db.crypt12").

## Expected behavior
Until the last update, everything worked as it should: I have the settings set to overwrite existing files on the cloud and every morning the new database would be uploaded, as well as a unique-name-version from the day before.

## Actual behavior
For some reason, the app regularly asks me to solve a version conflict for "msgstore.db.crypt12", eventhough it should automatically be overwritten. And even when I manually choose to overwrite the file, a few minutes later the same notification appears again, without the file having changed in the local file system. This is really annoying.

## Thoughts
I don't really know why this is happening only for the "msgstore.db.crypt12". The folder contains a lot more files that are both saved locally and on the cloud. If somehow the version check (if the file has been changed locally) wouldn't work, I would expect a version conflict for all the files in the folder.

Maybe WhatsApp somehow accesses the database without changing it and Nextcloud somehow realises that? If that was the case, something like an md5 check would solve the problem (but maybe that's how it is already implemented?).

# System info
Android v8.0.0 (Samsung Galaxy S7)
Nextcloud App v3.13.0
Nextcloud Server v19.0.0

### The local folder
<img src="https://user-images.githubusercontent.com/62120554/90974866-8709a000-e52f-11ea-99df-7038563ce19a.jpg" alt="1" width="400">

---

### The notification
<img src="https://user-images.githubusercontent.com/62120554/90974886-9f79ba80-e52f-11ea-987e-9678bd198ae7.jpg" alt="2" width="400">

---

### Both files were changed 7h ago
<img src="https://user-images.githubusercontent.com/62120554/90974890-a3a5d800-e52f-11ea-93ac-c50519d208bc.jpg" alt="3" width="400">

---

### Settings set to overwrite existing files
<img src="https://user-images.githubusercontent.com/62120554/90974893-a6a0c880-e52f-11ea-819f-85e48f8f904b.jpg" alt="4" width="400">

**Comment by tobiasKaminsky** [comment]
This should be fixed via https://github.com/nextcloud/android/pull/6771 
You can test the apk in this PR, it can be installed in parallel.
