### ISSUE TITLE
Impossible to switch account/show sidebar in a subdirectory

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/android#6789]
### Steps to reproduce
1. Go to a subdirectory
2. Try to switch account or open the sidebar to go to uploads for example

### Expected behavior
- There should be a way to directly access the sidebar/account switcher

### Actual behavior
- The user needs to navigate to the root folder first

### Environment data

Nextcloud app version: 3.13.0

cc @nextcloud/designers

**Comment by tobiasKaminsky** [comment]
This is somehow the official idea by Android…
You can also compare it with Drive, which has the same "problem".

![2020-08-24-082120](https://user-images.githubusercontent.com/5836855/91010441-ce049d80-e5e2-11ea-873b-f3772e56fd92.png) ![2020-08-24-082116](https://user-images.githubusercontent.com/5836855/91010444-ce9d3400-e5e2-11ea-8cf0-6d324f9c49c4.png)

Any idea is welcome…

**Comment by juliushaertl** [comment]
I see. My first idea would have been a swipe action on the back arrow to slide in the sidebar, but not sure how feasible or common that is. For the account switcher I don't have any idea yet other than putting it back in the sidebar for such scenarios.

**Comment by AndyScherzinger** [comment]
Erm, you always have been able to swipe from left end to the right to open the side bar :)
So that works already. For the account chooser, yeah, that's like all Google Apps these days.

**Comment by juliushaertl** [comment]
> Erm, you always have been able to swipe from left end to the right to open the side bar :)

Ah I see this might be in conflict with the swipe to go back gestures i have enabled.

**Comment by tobiasKaminsky** [comment]
> Ah I see this might be in conflict with the swipe to go back gestures i have enabled.

For this you have be careful how you swipe.
Swipe from left edge in 90° to right: go back
Swipe from left edge in 45° to top/right: open drawer

**Comment by ma12-co** [comment]
Doesn't all that conflict with android gestures? Since I installed android 10 on my phone I've been using gestures for navigation. I see that many apps are dropping swiping for in app navigation because of this OS level stuff.

**Comment by tobiasKaminsky** [comment]
As posted one comment above one have to be careful how to swipe.

**Comment by ma12-co** [comment]
I think that the behavior that you suggested can be confusing @tobiasKaminsky. Shouldn't we just disable swiping and use toggles only if android gestures are enabled?

**Comment by stefan-niedermann** [comment]
As far as i know even the GMail app has [the described behavior](https://github.com/nextcloud/android/issues/6789#issuecomment-679823936) (without a judgment whether or not this is good UX)

**Comment by tobiasKaminsky** [comment]
These gestures are built in by Android.
We also have to take in account that there will always be some modifications that do not have it and for those it it is nice to have the drawer opened this way.

**Comment by juliushaertl** [comment]
OK, let's close this then and consider it being an Android UX issue with the swipe gesture of 45° that is not really discoverable, for the account switcher i guess following the google apps makes sense then.
