### ISSUE TITLE
Move auto upload to settings

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#6793]
Currently we have (too?) many items in sidebar.
We could move auto upload to settings as this is mostly a "one time config and forget" task?

![2020-08-24-101422](https://user-images.githubusercontent.com/5836855/91020303-97368380-e5f2-11ea-9aca-798b30aea3a3.png)

@AndyScherzinger @jancborchardt

**Comment by AndyScherzinger** [comment]
With the actual feature set, sure. In case we ever get to the point of a more feature rich, gallery style, day in history pictures etc than we might bring it back 😊👍

**Comment by schiessle** [comment]
> We could move auto upload to side bar as this is mostly a "one time config and forget" task?

You mean to the settings right? At the moment it is in the sidebar... :wink:

**Comment by AndyScherzinger** [comment]
@nextcloud/designers any feedback? :)

**Comment by jancborchardt** [comment]
I’d agree with @tobiasKaminsky – Auto Upload is unlike any of the other views, more of a setting than a view. :)
