### ISSUE TITLE
Show videos in Photos View

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/android#6795]
### Is your feature request related to a problem? Please describe.
The new Photo View looks very nice, it would be awesome if videos show up there, too. Like in the photos app in the browser.

### Describe alternatives you've considered
Open the activity tab, look if someone uploads a video
Open nextcloud in the mobile browser an navigate to the photo app

### Additional context
Is this hard todo? If not, maybe I can try to do this?

**Comment by tobiasKaminsky** [comment]
Nice idea, why not :-)

@nextcloud/designers shall we then still call it photos? Or maybe media?

**Comment by jakobroehrl** [comment]
On iOS it's called Media, in the Browser "Photos"
@tobiasKaminsky Is this hard to develop or just a config change?

**Comment by tobiasKaminsky** [comment]
As this was somehow quick and it solves a gap in our feature parity, I quickly did this: #6820

**Comment by AndyScherzinger** [comment]
Hard to tell if media is right since that would also include music, sound or else, no? Not a native speaker so maybe someone else is able name the right term?

**Comment by tobiasKaminsky** [comment]
Internal it is called gallery, also not sure if this fits better.

**Comment by AndyScherzinger** [comment]
Hmmm, @jancborchardt @nextcloud/designers what should be the unified term used throughout all clients including web? Right now we have iOS (media), Android (photos) and web(photos) while in case of showing images and video (thumbnails) photos doesn't quite describe it.

**Comment by jakobroehrl** [comment]
@jancborchardt @nextcloud/designers 
🔔 ping

**Comment by Bugsbane** [comment]
I'd suggest that either Media, or Gallery is fine. Yes, technically "Media" could include audio media, but as a native English speaker, when I thought of photos and videos, this was the first word that came to mind. Gallery doesn't suggest audio media, but generally when thinking of the word "Gallery" I think of still images only. This is not a technical description, but just an association with the word from a single native speaker.

Personally though, I would not be surprised if I clicked on something with either name, to find photos and videos and nothing else.

**Comment by juliushaertl** [comment]
I personally think photos is also fine, Google and Apple also call their media management "Photos" and it includes videos in there.

**Comment by juliushaertl** [comment]
cc @skjnldsv for the photos server app
