### ISSUE TITLE
Show last sync time in app

### ISSUE THREAD

**Issue by Bullnados** [nextcloud/android#680]
### Actual behaviour
1. No last synctime is shown.
2. Sync dots in topbar "syncing" every folder I entered. It is very confusing, I dont know if the actual folder im entered is synced or not

### Expected behaviour
1. Last synctime in topbar or sidebar. Perhaps with a manual sync button.
2. Force sync in root, so you can be save, that all other child folders are also synced

**Comment by tobiasKaminsky** [comment]
On every folder entering a sync for this folder is performed.
To have this a little bit clearer I would go the way that it is shown "offline" if no connection can be established.
cc @jancborchardt

**Comment by jancborchardt** [comment]
Good call @tobiasKaminsky. A good example for this is the Netflix app, showing offline state in the top bar.

**Comment by joshtrichards** [comment]
Fixed in #2805
