### ISSUE TITLE
Activity screen 401 does not respect sticky sessions

### ISSUE THREAD

**Issue by kfirfer** [nextcloud/android#6804]
Nextcloud version: 19.0.1
App version: 3.13.0

I have cluster of nextcloud servers, and Im getting 401 when the traffic goes to the server that hasnt open session

Any other screen respect sticky sessions, but it seems Activity screen is missing it, and making a load balance

Nextcloud access logs example:

```
[nextcloud-0] 172.16.207.100 - kfirfer [25/Aug/2020:16:37:48 +0000] "GET /ocs/v2.php/apps/activity/api/v2/activity?format=json&previews=true HTTP/1.1" 401 1539 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.13.0"
```
And when he hit the server that has the sessions, everything alright:
```
[nextcloud-1] 172.16.207.100 - kfirfer [25/Aug/2020:16:37:43 +0000] "GET /ocs/v2.php/apps/activity/api/v2/activity?format=json&previews=true HTTP/1.1" 200 16659 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.13.0" 
```

I already configured Nginx to sticky sessions, I know that because any other screen works properly

Thanks

**Comment by tobiasKaminsky** [comment]
This seems to be more of a server related question, or?

**Comment by kfirfer** [comment]
Mabye it is relating to both the client & server

In the browser he respect the cookies and session

**Comment by kfirfer** [comment]
found this article:
https://www.digitalocean.com/community/tutorials/how-to-set-up-a-redis-server-as-a-session-handler-for-php-on-ubuntu-14-04

as wrote there, the php saving the sessions as a files by default, the cluster I setup is stateless and does not share sessions files between them.
I already setup nginx in front of the apache php server for session stickiness with a cookie+keep-alive

so I think is relating to the android app itself and not server issue

I could make this workaround as the article above said (redis as session holder), but it is not sufficient I rather make the server stateless as possible

**Comment by tobiasKaminsky** [comment]
@nextcloud/server-triage can you help me here?
None of our user/customer even with very large setups seems to have this problem…?

**Comment by kesselb** [comment]
https://github.com/nextcloud/android-library/blob/74ff0bd78fcab0b5d6f169fe9994df92c05321d1/src/main/java/com/nextcloud/common/NextcloudClient.kt#L69-L74

Session stickiness is when a user is always using the same app server. Usually implemented by setting a cookie. Load balancer reads this cookie and forwards the request to the previously used app server. 

`NextcloudClient.kt` seems to be stateless hence the cookie needed by the load balancer is missing. This could affect other features using `NextcloudClient.kt`.

I don't understand how the kotlin client sets the credentials for a request 🤷‍♂️

Sharing the sessions between the app servers is my recommendation. If we keep the session stickiness cookie it's by accident and not intended.

**Comment by tobiasKaminsky** [comment]
> Usually implemented by setting a cookie.

As far as I know we do not store the receiving cookies, not on (new) NextcloudClient, not on (old) OwnCloudClient.



> Sharing the sessions between the app servers is my recommendation.

This sounds like a valid solution.

**Comment by kfirfer** [comment]
Im currently cluster sharing the sessions in the app servers 
Closing the issue
