### ISSUE TITLE
NextCloud Beta 20170222 - Not showing Images from Nextcloud Server

### ISSUE THREAD

**Issue by Rickinfl** [nextcloud/android#681]
My phone upgraded to Android 7. The Nextcloud app stop auto uploading I was told to use the Beta. The Auto Upload works now, But I can't see any of the pictures on the server on the app. Example. On my phone I go into the instantUpload folder > 2017 > 02 - It says I have 143.4 MB in that 02 folder. When I go into that folder I see 1 picture that is 2.9 MB. When I go into Nextcloud on my computer and view that folder I see all 34 of my pictures. I'm Running NextCloud Server 11.

**Comment by mario** [comment]
I assume you have tried refreshing the folder?
:-/

**Comment by tobiasKaminsky** [comment]
Is it working for folders other than auto upload folders (like documents or music)?

**Comment by tobiasKaminsky** [comment]
@Rickinfl do you still experience the issue?

**Comment by tobiasKaminsky** [comment]
No response within the last month, therefore closing.
Please feel free to reopen with additional infos, if the problem still exists.
