### ISSUE TITLE
Sort and list/icon view switchers are shown in details view

### ISSUE THREAD

**Issue by XueSheng-GIT** [nextcloud/android#6818]
### Steps to reproduce
1. Open "Details" view of any file
2. Lock screen
3. Unlock screen
4. Sort and list/icon view switchers are shown. (Same happens if e.g. a pdf file is opened by "open with" in details view, then return back from external app to details view).

### Expected behaviour
- Sort and list/icon view switchers should not appear in details view.

### Actual behaviour
- Sort and list/icon view switchers are shown (see screenshot).
![Screenshot_20200826_101308](https://user-images.githubusercontent.com/4077683/91278709-dac0f700-e784-11ea-85dc-f123a11df6c0.jpg)

### Environment data
Android version: Android 10.1

Device model: Huawei Mate 20 Pro

Stock or customized system: Stock

Nextcloud app version: 3.13

Nextcloud server version: 18.0.7

Reverse proxy: No.

**Comment by tobiasKaminsky** [comment]
Can also be triggered when 
- open file details view
- suspend app
- open app again
