### ISSUE TITLE
swiping down in the photo view doesn't load any photos

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/android#6821]
### Steps to reproduce
1. Open the photo view
2. do a reload with swiping down

### Expected behaviour
- show the photos

### Actual behaviour
- Loading screen stays there forever

### Environment data
Android version: 3.13.0

**Comment by tobiasKaminsky** [comment]
Cannot reproduce it.
I think this was fixed in one of the latest versions.

If not, please re-open.
