### ISSUE TITLE
Pause/restart aborted auto-uploads? 

### ISSUE THREAD

**Issue by chaoscommander** [nextcloud/android#6823]
I have photo and video auto-upload on Wi-Fi enabled. Sometimes I am connected to very slow Wi-Fi connections, like in a mountain hut. When I abort the upload process to stop overloading the weak network with e.g. video files, the files that were already queued never get automatically uploaded. They are subsequently treated as preexisting. I would like to have them uploaded later but there is no pause button. I can only abort them all and later upload them manually, which sucks. Even turning on "upload existing files" doesn't upload them...

Is there a way around this I'm not seeing? Or could this be considered as a feature, please?

**Comment by mathieujobin** [comment]
I would also like an easy way to retry failed upload, or at least make sure it auto-retried on its one.

Here is what I am seeing:
- Nextcloud is list me a few failed upload in my notifications
- I click on it, and I land on Nextcloud uploads page.
- I see hundreds of successful uploads, impossible to find the failed ones through that list
- I click the three-dot menu, I have the option to clear failed uploads. I would prefer to clear the successful one from that list.

How do I make sure all my photos are uploaded.

**Comment by joshtrichards** [comment]
Pausing: Let's track that in #383
Aborted uploads: Let's track that in #1256
