### ISSUE TITLE
Cause of error 

### ISSUE THREAD

**Issue by Bianca339** [nextcloud/android#6826]
************ OORZAAK VAN FOUT ************

 java.lang.IllegalStateException: kan rij 1540, kolom 1 van CursorWindow niet lezen.  Zorg ervoor dat de cursor correct is geïnitialiseerd voordat u er gegevens van opent.
 op android.database.CursorWindow.nativeGetString (native methode)
 op android.database.CursorWindow.getString (CursorWindow.java:469)
 op android.database.AbstractWindowedCursor.getString (AbstractWindowedCursor.java:53)
 op android.database.CursorWrapper.getString (CursorWrapper.java:141)
 op com.owncloud.android.datamodel.UploadsStorageManager.createOCUploadFromCursor (UploadsStorageManager.java:320)
 op com.owncloud.android.datamodel.UploadsStorageManager.getUploads (UploadsStorageManager.java:301)
 op com.owncloud.android.datamodel.UploadsStorageManager.getFailedUploads (UploadsStorageManager.java:372)
 op com.owncloud.android.files.services.FileUploader $ UploadRequester.retryFailedUploads (FileUploader.java:405)
 op com.owncloud.android.utils.FilesSyncHelper.lambda $ restartJobsIfNeeded $ 0 (FilesSyncHelper.java:246)
 op com.owncloud.android.utils .- $$ Lambda $ FilesSyncHelper $ kKNrggliFpEukU1kV4bap8ektCs.run (onbekende bron: 12)
 op java.lang.Thread.run (Thread.java:919)

 ************ APP-INFORMATIE ************
 ID: com.nextcloud.android.beta
 Versie: 20191102
 Build-smaak: versionDev

 ************ APPARAAT INFORMATIE ************
 Merk: OnePlus
 Apparaat: OnePlus7Pro
 Model: GM1913
 Id: QKQ1.190716.003
 Product: OnePlus7Pro_EEA

 ************ FIRMWARE ************
 SDK: 29
 Vrijgeven: 10
 Incrementeel: 2007240000

**Comment by tobiasKaminsky** [comment]
> 20191102

This is heavily outdated, can you update the app and try it again?
