### ISSUE TITLE
Custom delete delay after Instant-Upload

### ISSUE THREAD

**Issue by gsantner** [nextcloud/android#683]
### Actual behaviour
I checked the option to delete pictures after upload. After upload files get immediately deleted

### Expected behaviour
Please add an option to specify a amount of time to wait before deleting the files after upload.
This doesn't have to be specific to a folder, can be a global option. The problem is, the deletion happens sometimes too fast, before I can preview the file. Such a option would be very nice.

Specific use case scenario: I create a screenshot of something, or download some pictures. Want it to be archived on my NextCloud, and don't need them on my device. Mostly I also want to share the stuff with a contact, or want to look at it. Because the auto delete happens mostly very fast, I often cannot view/open/share the file anymore.
As said above, I really like the feature of auto-deletion, and don't want to deactivate it. Adding a short delay for deleting - configurable if possible - would be really handsome.

### Environment data
Android version: 7.0.1

Device model: N5

Stock or customized system: LOS

Nextcloud app version: beta 20170222

Nextcloud server version: 11

**Comment by tobiasKaminsky** [comment]
When using Android 7 you should already have auto upload which is the new upload system.
This one has currently a hardcoded 10s delay and beside that the execution is controlled by androids doze system, so chances are good that the upload will not start immediately...

**Comment by gsantner** [comment]
I'm closing this and switch back to manual backing up pictures  
Delay on Nougat: Yeah, sometime shortly, sometimes never; I setted up everything some time ago and thought it's working good. Now checked my nextcloud folder and noticed that  roughly 3/4 pictures never got uploaded. Seems like the app didn't even try, because the Upload log has not very much entries (but in general manual download/upload with app works, so no auth/net problem). I would post logs, but well, there are none.
