### ISSUE TITLE
Files containing "?" in their filename are not downloaded by the client

### ISSUE THREAD

**Issue by elpraga** [nextcloud/android#684]
### Actual behaviour
If a filename contains "?", the download fails both in 1.4.1 and current Beta apps.

### Expected behaviour
File gets downloaded.
 
### Steps to reproduce
1. Synchronize a file containing a "?" in a name using a desktop client. 
2. Try to download it using Android app.

### Environment data
Android version:
6.0

Device model: 
Huawei Y6II

Stock or customized system:
stock
Nextcloud app version:
1.4.1 and Beta

Nextcloud server version:
11.0.1

**Comment by tobiasKaminsky** [comment]
I have tested it with creating a file "1?2?3.txt" on linux, synced via desktop client.
I downloaded it successfully on my android one plus 3.

Which desktop are you using?

**Comment by elpraga** [comment]
That is weird. I'm using Ubuntu 14.04 running Fluxbox. The file in question was one with Chinese characters mixed with Latin containing ? . The Chinese equivalent of ? Worked fine.

I'll try to find the exact filename and I'll post it here once I find it.

**Comment by tobiasKaminsky** [comment]
@elpraga if this is happening again, please reopen with the exact filename.
