### ISSUE TITLE
nextcloud android login with email 

### ISSUE THREAD

**Issue by lawas2008** [nextcloud/android#6840]
### Steps to reproduce
1. login account with email-address
2. click photo search 
3. return 404 
4. email-address contain char '@'  is transfered '%' like 506873792@qq.com is transfered 506873792%40qq.com
### Expected behaviour
- return result

### Actual behaviour
- return 404

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
>     2\. click photo search

is username also containing "@"? You can find it in settings/users on web as Admin.

**Comment by lawas2008** [comment]
![QQ截图20200829163324](https://user-images.githubusercontent.com/10286773/91632773-add74300-ea15-11ea-894a-ad0842ea0f2f.png)

like this,then login with email-address,then click pthoto  and return 404.

**Comment by tobiasKaminsky** [comment]
@nextcloud/server-triage 
When userId is "test@test", we pass "test%40test" to webdav search: <d:scope><d:href>/files/test%40test</d:href>
Which does return 404, but "files/test@test" would work.

Will the plain text variant work for all other supported userIds?

**Comment by lawas2008** [comment]
hello, steps:
![QQ截图20200831210541](https://user-images.githubusercontent.com/10286773/91723310-2123b500-ebce-11ea-9e63-f0464aee8fe4.png)
![QQ截图20200831210719](https://user-images.githubusercontent.com/10286773/91723318-2254e200-ebce-11ea-97ec-ac0ff254b9ad.png)
![QQ截图20200831210750](https://user-images.githubusercontent.com/10286773/91723321-241ea580-ebce-11ea-8516-99987d44909c.png)

**Comment by lawas2008** [comment]
and I change code,it's useful:
![QQ截图20200831211025](https://user-images.githubusercontent.com/10286773/91723628-a0b18400-ebce-11ea-9786-93f7b1b4bff6.png)

**Comment by lawas2008** [comment]
sorry，I login with email-address by authorize using our accout-system. then our server changes nextcloud‘s Automatic account assignment .  like this. so that's no problem! thanks.
 
![1598926169(1)](https://user-images.githubusercontent.com/10286773/91787135-ba3ce500-ec3b-11ea-8842-af67731bdf9b.jpg)

**Comment by blizzz** [comment]
> Will the plain text variant work for all other supported userIds?

User home storages are "mounted" by user id, there is no transition happening. So, should.

**Comment by tobiasKaminsky** [comment]
Fixed by https://github.com/nextcloud/android-library/pull/497
