### ISSUE TITLE
Login fails in local network

### ISSUE THREAD

**Issue by DrRSatzteil** [nextcloud/android#6849]
### Steps to reproduce
1. Connect to WiFi (same network as the NC server)
2. Open app and try to login
3. Login flow does not continue after trying to grant access (the same applies to the talk app). Spinner spins forever...
4. Close app, disconnect WiFi, restart app and login as usual (via mobile network provider)
5. App seems to work fine when switching back to WiFi after login

Note that this started after the update to 19.0.2 (from 18.0.7 to 18.0.8 to 19.0.2) which I installed today. Access via browser works as usual.

### Expected behaviour
Login should work from any network

### Actual behaviour
After a couple of login attempts with the correct credentials the app says that further login attempts will be delayed by 30 seconds due to too many failed attempts.

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

No, not possible

### Environment data
Android version: 10

Device model: Xiaomi Mi Mix 3

Stock or customized system: Stock

Nextcloud app version: 3.13.0

Nextcloud server version: 19.0.2

Reverse proxy: no

#### Web server error log
```
Nothing
```

#### Nextcloud log (data/nextcloud.log)

I see a lot of suspicious logins but this is probably due to a new ip (accidentally unplugged my router today). XXXXXX stands for my landline IP address. Nothing else that seems related.

```
{"reqId":"WVTKwai1XtcoN5ski0AI","level":2,"time":"2020-08-28T22:50:44+00:00","remoteAddr":"XXXXXX","user":"drrsatzteil","app":"suspicious_login","method":"POST","url":"/index.php/login","message":"Detected a login from a suspicious login. user=drrsatzteil ip=XXXXXXX strategy=ipv4","userAgent":"Xiaomi Mi MIX 3 (Android)","version":"19.0.2.2"}
{"reqId":"2F6dmcpf6dhFj2Cm5R3g","level":2,"time":"2020-08-28T22:55:58+00:00","remoteAddr":"XXXXXX","user":"drrsatzteil","app":"suspicious_login","method":"POST","url":"/index.php/login","message":"Detected a login from a suspicious login. user=drrsatzteil ip=XXXXXXX strategy=ipv4","userAgent":"Xiaomi Mi MIX 3 (Android)","version":"19.0.2.2"}
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by DrRSatzteil** [comment]
I don't really know what is going on... When I open activities it tries to load for some time and then says: operation finished with http status code -1. Downloading files however works...

**Comment by tobiasKaminsky** [comment]
This seems to be more a configuration issue than a bug, please ask at help.nextcloud.com
