### ISSUE TITLE
Directories containing ":" in their filename are not downloaded (synced) by the client

### ISSUE THREAD

**Issue by elpraga** [nextcloud/android#685]
### Actual behaviour
It a directory name contains ":", the download of files within fails both in 1.4.1 and current Beta apps.

### Expected behaviour
Files get downloaded.
 
### Steps to reproduce
1. Synchronize a directory containing a ":" in a name using a desktop client. 
2. Try to download any file within it using an Android app.

### Environment data
Android version:
6.0

Device model: 
Huawei Y6II

Stock or customized system:
stock
Nextcloud app version:
1.4.1 and Beta

Nextcloud server version:
11.0.1

**Comment by tobiasKaminsky** [comment]
Same as in https://github.com/nextcloud/android/issues/684 it worked for me with linux and android 7.
What desktop client are you using?

**Comment by elpraga** [comment]
That is weird. I'm using Ubuntu 14.04 running Fluxbox. The file in question
was one with Chinese characters mixed with Latin containing ? . The Chinese
equivalent of ? Worked fine.

I'll try to find the exact filename and I'll post it here once I find it.

**Comment by tobiasKaminsky** [comment]
Same as #684 , please reopen if it happens again and then post the filename.

**Comment by elpraga** [comment]
Ok @tobiasKaminsky , I ran into this issue again. I have to note that i cannot reproduce it using the dev client, only the __1.4.3__ version. 

My settings:
storage on SD card.
Steps to reproduce:
* upload a file containing a ":" in the name.
* try to download it using the 1.4.3 version of the client.
Download will fail.

**Comment by elpraga** [comment]
P.S. There is no way for me to reopen the issue, but please check if you can reproduce it.

**Comment by elpraga** [comment]
Were you able to reproduce the error @tobiasKaminsky ? I know you mentioned earlier that you were not able to reproduce the behavior..

**Comment by elpraga** [comment]
That's what I thought as well, but I can work just fine with the same file using the dev app. Might it be an issue of in internal storage instead? Doesn't the 1.4.3 download the file first to internal storage and then to the SDcard?

**Comment by tobiasKaminsky** [comment]
As far as I know we did not change the download process, but I will have a look.

**Comment by elpraga** [comment]
One of the apps has to behave like this, because I get a folder called __nextcloud__ created in my internal storage even though I have the SDCard selected as the place to store files in the app.

**Comment by tobiasKaminsky** [comment]
The initial storage is always internal, so on your very first start there will be a nextcloud folder created.

**Comment by elpraga** [comment]
Yes, I guessed so. So I deleted it after setting the SDCard as the storage
device.

It got created again after the SD Card was selected.

**Comment by tobiasKaminsky** [comment]
I tried it with several devices, this is my conclusion:
- internal storage --> no problems
- sdcard mounted/formatted as internal storage -> no problems
- sdcard mounted/formatted as portable storage --> download error

Can you verify with a file explorer where the file (when it is working) gets downloaded? And how the sdcard is formatted/mounted?

**Comment by elpraga** [comment]
I can confirm, internal storaga -> no problem
SD card -> download error in both 1.4.3 and the dev app (the last update of the dev app changed the storage to internal again, and that's why I didn't noticed it)

SD Card:
Storage type: USER_EXTERNAL
DEVICE:  /dev/fuse

That's what I got form FX File manager. Does it help?

**Comment by tobiasKaminsky** [comment]
Thank you for your infos.
A quick search leads me to the impression that the external sdcard is forrmatted as vfat which cannot handle ":" as filename.
I am really sorry but I doubt that we can do anything here. If you really need to have these filenames you will have to use the internal storage, or wait for an android update that allows you to format your sdcard as internal storage.
If you agree, please close.

**Comment by elpraga** [comment]
Ok. Thank you for investigating the issue!
