### ISSUE TITLE
Nextcloud app uses lots of battery when server is unreachable

### ISSUE THREAD

**Issue by axelsimon** [nextcloud/android#6868]
### Steps to reproduce
1. Make your Nextcloud server unreachable (loss of connection, crash, etc.)
2. Let the Android Nextcloud app try to sync
3. Watch your battery drain

### Expected behaviour
- The Nextcloud app should try to sync less and less frequently, using a basic cooldown algorithm such as:
 -- try every 10 seconds 6 times, then
 -- try every 30 seconds 10 times, then
 -- try every minute 5 times, then
 -- try every 5 minute 10 times, then
 -- try every 10 minutes 10 times, etc.

### Actual behaviour
- The Nextcloud app relentlessly tries to contact the server, even when it's evident it's not reachable, keeping the device's CPU awake and using energy in the process, using up the battery.

### Can you reproduce this problem on https://try.nextcloud.com?
- inapplicable

### Environment data
Android version: Android 10

Device model: Pixel 2

Stock or customized system: GrapheneOS QQ3A.200805.001.2020.08.07.01

Nextcloud app version: 3.12.1

Nextcloud server version: inapplicable

Reverse proxy: nginx (inapplicable)

#### Web server error log
```
N/A
```

#### Nextcloud log (data/nextcloud.log)
```
will add as soon as possible
```

**Comment by tobiasKaminsky** [comment]
Which sync mechanism do you refer to? Auto upload, manually sync, etc?

**Comment by axelsimon** [comment]
My server's been offline for a while, so i'm not trying to upload anything manually to it. I think this is auto-upload of pictures relentlessly re-trying to upload some pictures, even though the server is unavailable.
Interestingly, when i go in the Android Nextcloud app, it tells me the server is unavailable with a tasteful little info bar at the top of the file list.

I don't have daily backup of contacts enabled, currently. But i constantly have a notification saying "Upload failed: Could not complete operation. Server unavailable."

**Comment by tobiasKaminsky** [comment]
Do you see any pending uploads?

**Comment by axelsimon** [comment]
@tobiasKaminsky Sorry for the slow answer, yes there are many failed/pending restart uploads in the Uploads section of the app. 

I've now updated to 3.14.0 and i think the problem is less noticeable, if that can help.
