### ISSUE TITLE
Crash on deleting empty password in file share

### ISSUE THREAD

**Issue by kleinhti** [nextcloud/android#6869]
### Steps to reproduce
1. Open the Details of a shared file
2. Switch to "Share"
3. Open the Menu of the Sharelink with a click on the three dots
4. Open die dialog to set a password
5. Click delete

### Expected behaviour
- You should get an error that no password has been set or you should not have the choice to delete it if it does not exist.
Hi, I had an app crash as i tried to delete an not existing share link password.
### Actual behaviour
- If you haven't set a password before the app crashs. Maybe it trys to delete an not existing string? As far as I can see it throws a NullPointerException at this point.

### Environment data
Android version: 7.0 (SDK 24)

Device model: SM-G920F

Nextcloud app version: 30130090

**Comment by tobiasKaminsky** [comment]
This is already fixed and will be in upcoming version.
