### ISSUE TITLE
Autoupload doesn't automatically resolve file conflict.

### ISSUE THREAD

**Issue by maluus** [nextcloud/android#6872]
### Steps to reproduce
1. Setup an autoupload scenario for a folder. (My setup is as follows. Doesn't upload existing files, will keep local files, on conflict will overwrite remote file.
2. Enable auto upload and make it sync.
3. It won't automatically resolve the conflict by overwriting the remote file as indicated at setup. Instead asks for manual resolve but even then doesn't overwrite after uploading file again asks for manual resolve and begins to upload and so on.

### Expected behaviour
- it should overwrite the existing remote file with new local file. (It was working on previous version or may be the one before it not sure about the version but it was working for a while after the feature introduced. Problem arose with latest versions.)

### Actual behaviour
- Asks for manual resolve of the conflict again and again. 

### Environment data
Android version: 10 (but tried on 9 and its the same. So it happens on both 9 and 10

Device model: 
Xperia X Compact

Stock or customized system:
Tried both on LOS 16.1 and AOSP

Nextcloud app version:
3.13.0

Nextcloud server version:
18.0.8 (recently updated. Was happening 18.0.7 too)

**Comment by maluus** [comment]
Just updated server to 19.0.2 will check and report the result.

**Comment by tobiasKaminsky** [comment]
This is fixed already and will be in upcoming version.
