### ISSUE TITLE
Auto bug

### ISSUE THREAD

**Issue by Andrysky** [nextcloud/android#6876]
### Steps to reproduce
1. Share folder
2. Set password
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate
![Screenshot_2020-09-02-08-42-31-388_com.nextcloud.client.jpg](https://user-images.githubusercontent.com/5894390/91936331-4876a100-ecf8-11ea-96f7-04e483d41a87.jpg)

**Comment by tobiasKaminsky** [comment]
Is fixed via #6760 and will be in next version.
