### ISSUE TITLE
Bottom navigation

### ISSUE THREAD

**Issue by mario** [nextcloud/android#688]
For a customized, branded version there should be an option to have bottom navigation in addition to the sidebar. The bottom navigation bar would include the following:

- Home (Currently All Files and "Files" in 1.5)
- Favourites
- Photos
- Settings

Toggling this setting on (during build time) will disable those entries from the sidebar and will show them in bottom navigation.

cc @jancborchardt @tobiasKaminsky @AndyScherzinger

**Comment by AndyScherzinger** [comment]
Sounds good to me! 👍 

..If a customer wants to use the bottom bar and want to use it this way basically moving items from the main menu to a bottom menu, so be it. Happy that it would be a custom build 💃

**Comment by tobiasKaminsky** [comment]
The remaining items would then still be in in the sidebar?
As it is a custom build it is fine for me.
This will be a switch in setup.xml and evaluated on run time? Or do you want (how?) implement this in a fixed way in the code?

**Comment by mario** [comment]
Yes, this will be in setup.xml, and the remaining items would still be in the sidebar.

**Comment by tobiasKaminsky** [comment]
Just came into my mind: If this is something that will want to have other customers as well, we could enhance this by adding any arbitrary layout:
Implement all the common actions as an interface and then have different real activities. 
But it depends if many customers want to have a different layout and how big the difference is...

For now we can do it the way you mentioned, mario.

**Comment by mario** [comment]
I'll probably do it by having two separate layout files with this difference. :)

**Comment by tobiasKaminsky** [comment]
If the differences are small enough it is working this way.
Just came into my mind how to enhance this, when a customer, e.g. wants to have a new button in the bottom bar, or such stuff.

**Comment by MorrisJobke** [comment]
PR for this is #742
