### ISSUE TITLE
Passcode does not remove DocumentsProvider roots right away and app access persists

### ISSUE THREAD

**Issue by grote** [nextcloud/android#6882]
When activating the passcode in app settings, to prevent all local access to Nextcloud files, the DocumentsProvider stops to advertise storage roots. This is fine in principle. However, the system is not notified about this change, so the roots stay available:

See [the docs](https://developer.android.com/reference/android/provider/DocumentsProvider#queryRoots(java.lang.String[])):

> If this set of roots changes, you must call `ContentResolver.notifyChange(Uri, android.database.ContentObserver, boolean)` with `DocumentsContract.buildRootsUri(String)` to notify the system.

This does currently not happen when the app gets locked. There's only a notification when an account gets created or removed.

Note that [outgoing persisted `Uri` permissions](https://developer.android.com/reference/android/content/ContentResolver#getOutgoingPersistedUriPermissions()) will continue to be available to other apps which is good for UX, but it is debatable whether this is a security issue as well.

As for UX, users don't seem to understand that other apps will not be able to interact with Nextcloud's DocumentsProvider when enabling the passcode feature (e.g. https://github.com/stevesoltys/seedvault/issues/82).

One idea to solve this is to at least educate the users when activating this feature. There could be a confirmation dialog when they toggle the switch. Other ideas for how to address this are welcome.

**Comment by AndyScherzinger** [comment]
Looping in @tobiasKaminsky and @nextcloud/designers for feedback, especially UX matters

**Comment by grote** [comment]
Oh and a related issue: When disabling the passcode, the storage doesn't come back right away. I needed to restart the device for that to happen.

**Comment by grote** [comment]
The user/design part of the ticket has been split out into #6916
