### ISSUE TITLE
Resolve file conflict does not disappear once file conflict is resolved

### ISSUE THREAD

**Issue by elpraga** [nextcloud/android#6888]
### Steps to reproduce
1. Upload a file
2. upload a newer version of the file 
3. a "resolve file conflict dialogue" appears (expected behaviour)
4. Resolve the conflict selecting one of the files as the one you want to keep

### Expected behaviour
- "resolve file conflict dialogue" disappears from uploads once file conflict is resolved

### Actual behaviour
- the "resolve file conflict" stays in uploads making it very confusing is the file conflict has been resolved or not

App version 3.13.0

**Comment by Emporea** [comment]
I am also facing this issue.

There is a conflict happens from time to time on my setup and thats pretty normal for me. I resolve it by either choose the new file or the existing one and i think its done now. I can clearly see a difference in size and date to choose the files to keep from.

1 minute later the notification appears again, but both files i can choose from are the same.

**Comment by tobiasKaminsky** [comment]
I think this is fixed via #6771 
After selecting the correct conflict handling, it is getting ignored on upload and thus the dialog happens again.
