### ISSUE TITLE
A file conflict icon appears, yet no file conflict can be found

### ISSUE THREAD

**Issue by elpraga** [nextcloud/android#6889]
### Steps to reproduce
1. I'm not sure how to reproduce this

Possibly related to https://github.com/nextcloud/android/issues/6888
?

https://cloud.tomaskaluza.net/s/T4TTnapX37c66M5 

App version 3.13.0

**Comment by tobiasKaminsky** [comment]
I think this is either if the folder itself or any child inside the folder has a sync conflict.
Can you find one?

**Comment by elpraga** [comment]
That was what I was thinking as well. But I was unsure to find and file conflicts in the subfolders / files.

If a conflict existed in any of the subfolders or files within the directory, I'd expect them to be marked with the same red icon, but that doesn't happen. I cannot find the conflicting file anywhere.

**Comment by elpraga** [comment]
I've even checked the hidden files

**Comment by qwertz22** [comment]
Is your Nextcloud Server version 19.0.0.2?

**Comment by elpraga** [comment]
Yes, it is. I'm sorry, it is by far not the most complete bug report I've given.

What other information might I provide?

**Comment by elpraga** [comment]
Can I provide more information of some kind?

What information would be useful?

**Comment by tobiasKaminsky** [comment]
No idea, unfortunately :-(
Is this happening only in a special file/folder?
What if you install the app on another device and try to access the same file/folder?

**Comment by qwertz22** [comment]
I have this problem, too, since this bug [https://github.com/nextcloud/server/issues/22482](https://github.com/nextcloud/server/issues/22482) exists.

**Comment by elpraga** [comment]
It disappeared after clearing all NC app data.
