### ISSUE TITLE
Switch to disable welcome guide

### ISSUE THREAD

**Issue by mario** [nextcloud/android#689]
There should be a switch in setup.xml to disable the three-step welcome guide.

cc @jancborchardt @tobiasKaminsky @AndyScherzinger

**Comment by AndyScherzinger** [comment]
👍 Yeah, sounds fine with me.

I guess this would also be a customer specific setting, right? As in our own/Nextcloud release would still have this activated (while even then it would only get display the very first time).

**Comment by mario** [comment]
Yes, this would be a customer-specific option.

**Comment by AndyScherzinger** [comment]
👍 perfect :)

**Comment by tobiasKaminsky** [comment]
Fine for me, enabled by default of course ;-)

**Comment by tobiasKaminsky** [comment]
#711

**Comment by thomas-mc-work** [comment]
I couldn't manage to find this parameter in the documentation:

<https://docs.nextcloud.com/server/stable/admin_manual/search.html?q=show_whats_new&check_keywords=yes&area=default>

Maybe it should be added if it isn't existing yet. Also, the keyword `welcome` would be helpful to find this option.

**Comment by AndyScherzinger** [comment]
@thomas-mc-work this is a client-side parameter set at build-time of the Android client, so you won't find such information in the server docs

**Comment by thomas-mc-work** [comment]
Oh please excuse me about that! I came here by a search and totally overlooked that I'm in the android client project.

**Comment by AndyScherzinger** [comment]
@thomas-mc-work no worries! 😃 All good!
