### ISSUE TITLE
A ghost file appears in the app but not in the web interface

### ISSUE THREAD

**Issue by elpraga** [nextcloud/android#6890]
### Steps to reproduce
1. I don't know how to reproduce this

In one of the folders I have a file with a creation date 
01/01/1970 that cannot be neither downloaded nor deleted.

This file does not appear neither in the web interface nor in the actual Nextcloud data directory on the server.

Any ideas how could I get rid of it?

**Comment by tobiasKaminsky** [comment]
Can you clean cache of the app? 
This does not remove any account data.

**Comment by elpraga** [comment]
I've just fine that. But the file is still shown. It is a screenshot from 2019 (guessing from the filename), but the creation date of the file is 01/01/1970. 
Their to open the file details page get me into a loop endlessly asking me for my fingerprint to open my Nextcloud app (showing details of other files works as expected.

**Comment by elpraga** [comment]
I've cleared all NC android app data and I cannot see the file anymore.
