### ISSUE TITLE
Automatic upload an image before screenshot is finished - file version conflict

### ISSUE THREAD

**Issue by qwertz22** [nextcloud/android#6895]
### Steps to reproduce
1. Open an app (e.g. browser) with so much content you have to scroll
2. make scroll-screenshot
3. file upload begins before you are done with scroll-screenshot
4. you will get an file version error notification. Local file is bigger than the server version.

You can see what I mean with "scroll-screenshot": [https://www.youtube.com/watch?v=X5nrh9zNtRc](https://www.youtube.com/watch?v=X5nrh9zNtRc)

### Expected behaviour
- I want to screenshot a large website or long whatsapp conversation and want this bigger image upload automatically after the creation of long screenshot is really done.

### Actual behaviour
- Screenshot gets uploaded before "long-screenshot" is completed.

### Can you reproduce this problem on https://try.nextcloud.com?
- No

### Environment data
Android version: 10

Device model: Samsung Galaxy Note 9

Stock or customized system: Stock

Nextcloud app version: 3.13.0

Nextcloud server version: 19.0.2

Reverse proxy: no

### Logs
logs are not relevant

**Comment by tobiasKaminsky** [comment]
What is a scroll-screenshot?

**Comment by qwertz22** [comment]
Scroll-Screenshot: [https://www.youtube.com/watch?v=X5nrh9zNtRc](https://www.youtube.com/watch?v=X5nrh9zNtRc)

**Comment by tobiasKaminsky** [comment]
So you can combine the screenshots? 
But in between the first part was already uploaded?

Best would be that this app would store the temp file not in the target folder, but in a real temp folder and only moves it to target folder once it is finished.
From our side, a delay would help, but how long should the delay be? 10s? 60s? Then other users might complain that they have to wait too long, so this is also no win…
As a quick fix you can set file conflict handling to overwrite or use auto upload only when charging…

**Comment by qwertz22** [comment]
Yes, I combine screenshots with the builtin feature of Android and the upload starts between the parts.

A customisable delay would help. Sometimes I need 1 sec or up to 60 seconds to finish the scoll-screenshot. Or maybe it helps to mark folders like "screenshot" for a delay.

The quick fix doesn't work at the moment because of https://github.com/nextcloud/server/issues/22482.

**Comment by grhangelone** [comment]
Hi there.
I have a similar problem with my call recordings.
Those are also files, which get created and then populated with data over some time.

The app uploads them, once they are created with say, 20kb after a few secs of talking.
When i'm done talking and hang up, the recording has like 300kb.

The app then tries to upload the file again and I get a sync error which I have to resolve manually.

btw: Setting "always overwrite the file on the server" gets ignored in this case

**Comment by tobiasKaminsky** [comment]
Maybe we can see if a file is still being written, but this might only help with call recording, as there is a continuous stream.
But the screenshot case is more like write, 1-20s wait, write.
There we cannot detect this.

I am unsure how to solve this, as there is no common pattern…

**Comment by grhangelone** [comment]
I'm not sure how the timing goal is here, but it might help, if you sync files after 30sec without change.
From my point of view it syncing from the phone to the server is no time critical thing

**Comment by qwertz22** [comment]
A textfield in the settings to select a delay would be help. I mean something like an integer field with minimum 0 and max 3600? I miss this feature also on the desktop client. Offtopic, but I got a lot of errors when I use my virtual machine hosted in nextcloud.

**Comment by tobiasKaminsky** [comment]
> From my point of view, syncing from the phone to the server is no time critical thing

That is what you say ;-)
Others, especially those that were used to "instant upload" on very early versions, want to have it uploaded directly and were puzzled why it could take up to 15min (as scheduled as background job) on certain devices.

**Comment by uusijani** [comment]
This is still an issue, and always has been for Samsung devices with One UI's scrolling screenshot feature.

**Comment by tobiasKaminsky** [comment]
Unfortunately I do not have a good idea how to solve this
- adding manual delay is strange
- adding automatic delay -> people will complain
- no delay -> this issue

**Comment by qwertz22** [comment]
> 
> 
> > From my point of view, syncing from the phone to the server is no time critical thing
> 
> That is what you say ;-)
> Others, especially those that were used to "instant upload" on very early versions, want to have it uploaded directly and were puzzled why it could take up to 15min (as scheduled as background job) on certain devices.

The best way is to let the user choose the setting: instant upload or wait x minutes

**Comment by qwertz22** [comment]
> 
> 
> Unfortunately I do not have a good idea how to solve this
> 
>     * adding manual delay is strange
> 
>     * adding automatic delay -> people will complain
> 
>     * no delay -> this issue

It would be nice to open the settings page where I can choose "default / instant" (like now) or fill an integer textfield for the manual delay. The really perfect solution for me was to select filetypes (e.g. JPG) for the delay.
