### ISSUE TITLE
in enlarged view mode 3.13.0 : cannot remove sync from images

### ISSUE THREAD

**Issue by rdwrt** [nextcloud/android#6897]
### Steps to reproduce
1. open app (3.13.0)
2. go to all files
3. open a thumbnail - photo enlarges
4. click on option icon, then Cancel sync
5. go back to thumbnail view: sync is still on

### Expected behaviour
- sync is turned off after pressing "Cancel sync" in enlarged photo view

### Actual behaviour
- sync remains on

### Can you reproduce this problem on https://try.nextcloud.com?
- doesn't seems a server side issue: sync is removed when doing the same action in thumbnail view

### Environment data
Android version: 9

Device model: motorola g6

Stock or customized system: stock

Nextcloud app version: 3.13.0

Nextcloud server version: unknown

Reverse proxy: no

#### Nextcloud log (data/nextcloud.log)

**Comment by tobiasKaminsky** [comment]
If you click only on an image it is not getting downloaded, thus you normally could not cancel it (and also do not see the cancel option").
Can you provide us a screenshot?
Is the sync progress also shown in file list?
