### ISSUE TITLE
MP4 Video streaming > 1 GB doesn't work

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/android#6899]
### Steps to reproduce
1. Upload a > 1 GB mp4 video file and try to play it
2. It doesn't play with the build in player, and with stream with VLC/Google Photos

If I download the file it's working. If I use < 1 GB files it works, too.

NC19.0.2
App 3.13

**Comment by tobiasKaminsky** [comment]
Is there any error/info why it does not play?

**Comment by tobiasKaminsky** [comment]
Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

**Comment by jakobroehrl** [comment]
There is no error, it's loading infinte. 
Tried it on try.nextcloud.com, too.
Unfortunately my phone isn't rooted, so I can't provide logs :(

**Comment by szaimen** [comment]
> Unfortunately my phone isn't rooted, so I can't provide logs :(

Also not this way?
https://github.com/nextcloud/android#with-a-computer

**Comment by Derkades** [comment]
App version 3.13.0, NC 19.0.3. Pixel 3a. I've tried a 2.2GB .mp4 and 3.6GB .mkv, both H.264. Nextcloud player works. Streaming to MX-Player and Google Photos works as well. Streaming to VLC Media Player doesn't work.

**Comment by szaimen** [comment]
I've just made a long video where I show that it still doesn't work with 3.13.1 RC1 for me:
https://bit.ly/33mqH8P
Here are some screenshots of the server utilization during the whole process.
![image](https://user-images.githubusercontent.com/42591237/92995664-adef3c80-f505-11ea-874b-eb94f0d9ac6b.png)
![image](https://user-images.githubusercontent.com/42591237/92995667-afb90000-f505-11ea-843c-6450cdbd6176.png)

**Comment by szaimen** [comment]
Could the problem be related to the fact that I am using local external storage?

**Comment by tobiasKaminsky** [comment]
> Could the problem be related to the fact that I am using local external storage?

For some external storage you have to enter your credentials.
Have you entered them? And how are they stored?

**Comment by tobiasKaminsky** [comment]
Can you give us also an info about the type of the external storage?

**Comment by szaimen** [comment]
It is a local external storage (here is a screenshot from the external-storages app):
![image](https://user-images.githubusercontent.com/42591237/93083286-ab6e1d80-f692-11ea-914c-a16eb0172d38.png)
Everything else works fine when using the android app. Only video playback and streaming of videos doesn't work, as you can see in my video.

**Comment by tobiasKaminsky** [comment]
@nextcloud/server-triage do you know anything related to this?

**Comment by szaimen** [comment]
@tobiasKaminsky So you couldn't reproduce this issue with local external storage yourself?

**Comment by Derkades** [comment]
I did another test with local external storage and it works fine. Built-in player, VLC, MX-Player and google photos all work with a 1.3GB H264/AAC mp4 file

**Comment by szaimen** [comment]
> Are you using some kind of proxy?

No, but I just tested it again and it starts playing after a really looong buffer time of I guess around a few minutes.
So this has to get drastically improved (since also downloading is much faster then the buffer time). 
And since I am obviously not the only one with streaming issues, I guess this issue is still valid. 

Maybe @jakobroehrl can provide more Infos on his setup and/or share his experiences with the app?

**Comment by jakobroehrl** [comment]
streaming > 1GB is not working on an absolut basic setup without external storage and other stuff. 
I tried 4 test movies on different servers. < 1 GB is working, > 1 GB not

**Comment by Derkades** [comment]
Possibly related to https://github.com/nextcloud/server/issues/12422

**Comment by szaimen** [comment]
> related to [nextcloud/server#12422](https://github.com/nextcloud/server/issues/12422)

I don't think so. My server is 64bit x86
