### ISSUE TITLE
Replace regular login with a webview

### ISSUE THREAD

**Issue by mario** [nextcloud/android#690]
There should be a customization option to replace regular login/change pass with a webview and a pre-set url.

cc @AndyScherzinger @tobiasKaminsky @jancborchardt

**Comment by AndyScherzinger** [comment]
Sounds good to me.

@ChristophWurst can you join the discussion? :) If I understood you correctly at the conference last year than moving on to a webview (after a URL check) than we could also make use of such an enhancement to support two-factor via this way?

**Comment by mario** [comment]
I'm hoping for a proper OAuth server that would fix the 2factor auth problem. This in particular is for integration with various 3rd party systems.

**Comment by ChristophWurst** [comment]
The idea was to give the user a URL they open in a browser or webview and the app gets an app password in the background once the login process has been finished (including 2fa and accepting the new device). Not sure if this is still the way we want to implement this. @LukasReschke how should we proceed with this?

**Comment by LukasReschke** [comment]
> The idea was to give the user a URL they open in a browser or webview and the app gets an app password in the background once the login process has been finished (including 2fa and accepting the new device). Not sure if this is still the way we want to implement this. @LukasReschke how should we proceed with this?

Depends on what upstream is doing with the desktop client. Let's first wait a bit and see if they implement OAuth2 completely. If yes we copy that.

**Comment by AndyScherzinger** [comment]
Sounds good, but then the web view part initially described could still be implemented to full-fill a customer requirement (this way, for now).

**Comment by MorrisJobke** [comment]
PR for this is #766

**Comment by mario** [comment]
Done.
