### ISSUE TITLE
Crash when deleting InstantUpload 

### ISSUE THREAD

**Issue by Chuckame** [nextcloud/android#6901]
### Steps to reproduce
1. Go to all files
2. Delete InstantUpload directory

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Just the crash, but now I can navigate without any error, and the directory was removed successfully 

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'long com.owncloud.android.datamodel.OCFile.getParentId()' on a null object reference
	at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:413)
	at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:372)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:231)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:360)
	at java.lang.Thread.run(Thread.java:919)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: polaris
Model: Mi MIX 2S
Id: QKQ1.190828.002
Product: polaris

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: V11.0.4.0.QDGMIXM

```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Is this happening reliable, or was it only once?

**Comment by Chuckame** [comment]
After another try on uploading via default dir (InstantUpload), I removed it, and I had no error. But this time there other directories, rather than nothing else at the first time

**Comment by tobiasKaminsky** [comment]
If you see a pattern, how you can reliable reproduce the bug, please re-open.
Otherwise it seems more like a temporary hiccup, which cannot be fixed :/
