### ISSUE TITLE
Send files

### ISSUE THREAD

**Issue by bafen62** [nextcloud/android#6907]
### Steps to reproduce
1. When I wanted to send files inside Nextcloud to my device (Android Smartphone) I could only send one at a time. If i have a lot of files in the same folder and want to send a lot or all of them or want to send the hole folder i can't do that. If I have to send files one at a time that's going to take a hole day and that can't anyone do! I even use Mega cloud  and there I can send hove many files I want, why not here? If you can't fix this problem I can't use your service anymore, if fix I'm going to upgrade for more space.
2. 
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger we had this in, or?
But with new combined send/share it seems to be vanished…?

@bafen62 with "send" you mean sending a downloaded file to another app, or?

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky can't remember if we had this tbh but makes sense to have it 👍

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky remived the PR reference since the issue doesn't state that it is requested for already downloaded files, or is that expected @bafen62 ?

**Comment by tobiasKaminsky** [comment]
>  it is requested for already downloaded files

Problem is that if you select e.g. 10 non-downloaded images and try to send them it would require some time to all download them and after that show sharing dialog.
Sure it is not an ideal solution, but was currently the easiest… ;-)
