### ISSUE TITLE
Remove APK from history

### ISSUE THREAD

**Issue by mario** [nextcloud/android#692]
APKs were built and put into this repository over time. I'd like to completely obliterate them from history as soon as @tobiasKaminsky changes the URLs and everything.

**Comment by AndyScherzinger** [comment]
If I am not mistaken @tobiasKaminsky's scripts only do this for the beta within the beta branch, right Tobias? Or are we keeping any APKs for the builds via master somewhere?

**Comment by mario** [comment]
Yes, he changed this, but there also APKs in the auto-upload-apk branch (had no other easy way to distribute APKs fast at that moment) which I'll completely obliterate once auto upload changes are done.

**Comment by tobiasKaminsky** [comment]
I have changed it now to the nc download server.
Let us wait for the next daily and if everything is working, you can clean the history.
(I do not know how to do this and I am afraid of doing it ;-) )

**Comment by tobiasKaminsky** [comment]
> had no other easy way to distribute APKs fast at that moment

Just use your own nextcloud server and create a public share with password protection ;-)

**Comment by tobiasKaminsky** [comment]
This is not done yet, or?
Fresh checked out repo is 306Mb:
- src 12Mb
- all other < 1Mb
- .git: 285Mb

**Comment by AndyScherzinger** [comment]
Don't think so. Fresh checkout is extremely large regarding the git folder :(

**Comment by mario** [comment]
Ah I will check.

**Comment by tobiasKaminsky** [comment]
```
git log --all --diff-filter=D --summary | grep delete | grep apk -i                                                                                                                1 ↵
 delete mode 100644 apks/nextcloud-beta-20170220.apk
 delete mode 100644 apks/nextcloud-beta-20170219.apk
 delete mode 100644 apks/nextcloud-beta-20161017.apk
 delete mode 100644 apks/nextcloud-beta-20161012.apk
 delete mode 100644 apks/nextcloud-beta-20161006.apk
 delete mode 100644 apks/nextcloud-beta-20160922.apk
 delete mode 100644 apks/nextcloud-beta-20160907.apk
 delete mode 100644 apks/nextcloud-beta-20160903.apk
 delete mode 100644 apks/nextcloud-beta-20160809.apk
 delete mode 100644 apks/nextcloud-beta-20160808.apk
 delete mode 100644 apks/nextcloud-beta-20160802.apk
 delete mode 100644 apks/nextcloud-beta-20160731.apk
 delete mode 100644 apks/nextcloud-beta-20160730.apk
 delete mode 100644 apks/nextcloud-beta-20160728.apk

```

But I doubt that this are all apks?

**Comment by AndyScherzinger** [comment]
Having this cleanup gets quite important to me since when I am not at home but somewhere else I might end up with 100-200Kb/s so this takes forever :(

**Comment by mario** [comment]
Doing it now.

**Comment by mario** [comment]
Roughly 92 MB instead of 300+ MB now :) Enjoy!

Might need a new clone! cc @AndyScherzinger @tobiasKaminsky

**Comment by AndyScherzinger** [comment]
New clone is fine with me :)
