### ISSUE TITLE
Videos uploaded to Nextcloud can't be played in WebDAV

### ISSUE THREAD

**Issue by sukafun** [nextcloud/android#6929]
### Steps to reproduce
1. Auto upload a video or upload a video manually to Nextcloud
2. Play the video from Windows WebDAV
3. Video says corrupted

### Expected behaviour
- The video should play

### Actual behaviour
- I have Auto upload enabled on videos and photos. Both get uploaded to Nextcloud however, when openning any video from WebDAV, it says video is corrupted. If playing video from Nextcloud video plays fine. If downloading video from Nextcloud video plays fine. Nextcloud IOS App does not have this issue. I have this issue since I started to use Nextcloud 2 years ago.

### Can you reproduce this problem on https://try.nextcloud.com?
- No

### Environment data
Android version: 8.0.0

Device model: Samsung Galaxy S7

Stock or customized system: Stock

Nextcloud app version: 3.13.0

Nextcloud server version: 19.0.2

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Can you do a checksum on both files and see if they are identical?

**Comment by sukafun** [comment]
I guess I fixed it by changing a registry key value to increase the file size saved. It's strange as I don't get any errors or issue when using iPhone on same computer.
