### ISSUE TITLE
Adapter library import

### ISSUE THREAD

**Issue by mario** [nextcloud/android#693]
I would like to ask if I can import the following library:

https://github.com/davideas/FlexibleAdapter

It would be good so we can use sticky headers, load more, animations and such without reinventing the wheel.

Thanks!

cc @AndyScherzinger @tobiasKaminsky

**Comment by AndyScherzinger** [comment]
Following up on the discussion on IRC, I vote yes for several reasons:

* the idea is to start integrating it with 1.6 and until then the 5.0 release (of the lib) should be released stable
* it can then replace the SectionedRecyclerViewAdapter lib we use for the auto upload view
* we can make use of load more (for activities), sticky list headers (upload view, sorting orders, etc.)
*`according to the lib description also safe on some boilerplate code (haven't looked at that in detail yet).

**Comment by tobiasKaminsky** [comment]
Fine for me 👍

**Comment by joshtrichards** [comment]
This library is now de facto defunct: https://github.com/davideas/FlexibleAdapter/issues/773#issuecomment-886712464
