### ISSUE TITLE
Incorrect error handling when checking server status

### ISSUE THREAD

**Issue by Equidamoid** [nextcloud/android#6940]
### Steps to reproduce
1. secure the new installation by revoking write permissons to `./apps`
2. forget to set `'appstoreenabled' => false,`, this will make `/status.php` return error 503.
3. install the app and try to login

### Expected behaviour
Ideally - no error at all as nothing login-related is broken.
Realistically - a relevant error message, like "server error 503"

### Actual behaviour
- `server in maintenance mode` is shown and user can't proceed with logging in

### Can you reproduce this problem on https://try.nextcloud.com?
Not applicable

### Environment data
Android version:

Device model: 
samsung s9+
Stock or customized system:
stock
Nextcloud app version:
3.13.0
Nextcloud server version:
19.0.2

#### Web server error log
```
84.241.200.235 - - [12/Sep/2020:14:31:40 +0000] "GET /status.php HTTP/1.1" 503 3116 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.13.0"
```

So, multiple problems here
 - [completely offtopic] insecure writeable `./apps` by default -- NC design decision, okay.
 - [also offtopic] /status.php returning error 503 with a huge html page due to non-critical sanity check failing.
 - Android app hides the actual error behind irrelevant message.

To make things worse, opening `/config.php` in a browser didn't give any error by some reason, making troubleshooting harder.

**Comment by tobiasKaminsky** [comment]
503 is in NC environment a "server is in maintenance mode".
Indeed, it is strange/an error that this is thrown on server side.
Please open up an issue on this in server repo.
