### ISSUE TITLE
Big or Feature Name Spacing change

### ISSUE THREAD

**Issue by 927589452** [nextcloud/android#695]
### Actual behaviour
-Autoupload changed folder structure from
/InstantUpload/Folder/2017/02
to
/InstantUpload/Folder2017/02

### Expected behaviour
-Tell us what should happen
 
### Environment data
Android version:
7.1.1 lineage
Device model: 
Sm g901g
Stock or customized system:
LineageOS
Nextcloud app version:
Nightly 20170223 (Fdroid)
Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

**Comment by mario** [comment]
This should already be fixed. Please update your nightly and test then :)

**Comment by AndyScherzinger** [comment]
Please reopen if still present in the latest nightly :)
