### ISSUE TITLE
Emojis on keyboard in markdown.

### ISSUE THREAD

**Issue by avuton** [nextcloud/android#6950]
When editing a Markdown document in the Nextcloud Android application, I often wish I had access to the system emoji keyboard, instead I usually search a random website for emoji use, then copy & paste into the markdown. Would love the ability to use the emojis palette for the stock keyboard (there must be a hint for this).

**Comment by tobiasKaminsky** [comment]
I assume that this depends on the type of keyboard you have installed.
E.g. for me with SwiiftKey I have an emoji button in each and every app, where the keyboard can be used.

**Comment by avuton** [comment]
> I assume that this depends on the type of keyboard you have installed.
> E.g. for me with SwiiftKey I have an emoji button in each and every app, where the keyboard can be used.

Yeah, that's probably the case; I've tried two AOSP keyboards off F-Droid, and neither have the emoji palette button available.

**Comment by AndyScherzinger** [comment]
closing then

**Comment by avuton** [comment]
Was this fixed?

**Comment by AndyScherzinger** [comment]
No, as mentioedn by Tobais and you, you need to simply use a keyboard that supports emojis

**Comment by avuton** [comment]
![Screenshot_20201106-073753_Signal](https://user-images.githubusercontent.com/396546/98384793-0f61f200-2003-11eb-98bb-845d3aadfd58.png)
![Screenshot_20201106-073757_Signal](https://user-images.githubusercontent.com/396546/98384798-10931f00-2003-11eb-9523-043f1acbb06b.png)

Sorry about my confusion, Signal supports _system_ emoji on my keyboard, and that's my point.

**Comment by AndyScherzinger** [comment]
Just checked:
![Screenshot_20201106-170525_Signal](https://user-images.githubusercontent.com/1315170/98388209-c0dc4400-2052-11eb-83ce-3f8ec8b368d8.png)

It seems to me that this depends on the device. I run LineageOS on an OnePlus 3T and don't have emojis but the icon in the text field launching a dedicated emoji keyboard.

**Comment by avuton** [comment]
For the record, LineageOS on OnePlus 5T here.

**Comment by AndyScherzinger** [comment]
Which keyboard are you using?
Me: Android keyboard AOSP Lineage 17.1 latest nightly

**Comment by avuton** [comment]
Android Keyboard AOSP LineageOS 16.0 latest (Nov 3, 2020) no google services, F-Droid (and Signal sideload) only.

**Comment by AndyScherzinger** [comment]
Hmmm, strange, I do have Google Services, Signal Version 4.76.1

**Comment by AndyScherzinger** [comment]
Ah, found the setting within the app to activate system emojis, so we'll have to take a look into how to do this.

**Comment by AndyScherzinger** [comment]
@avuton if the enter key is replaced with the emoji key how do you add line breaks? (Which I consider far more important than emojis when editing a markdown file)

cc @tobiasKaminsky

**Comment by avuton** [comment]
Well, since you asked it @AndyScherzinger I was thinking long press on enter would be a pretty good solution, and it turns out that's the... solution [without any changes to AOSP](https://gitlab.com/LineageOS/issues/android/-/issues/1247). Years of use and I had no idea. Sorry/thanks for the time!

**Comment by AndyScherzinger** [comment]
Nothing to be sorry for 🙂👍
Most important part is that the discussion got it resolved 🎉

**Comment by AndyScherzinger** [comment]
And thanks for taking the time to report and discuss which is far more important so we get feedback and can improve the app 🙏
