### ISSUE TITLE
Android app using website layout

### ISSUE THREAD

**Issue by Acipenser** [nextcloud/android#6959]
### Steps to reproduce
1. Install app from Play Store on tablet
2. Open app

### Expected behaviour
- **Android app layout** with sliding menu / sync options / ...

### Actual behaviour
- **Website layout** without sliding menu / sync options / ...

### Environment data
Android version: 7.1.2

Device model: Asus Transformer Pad (TF701T)

Stock or customized system: KatKiss ROM - Android 7.1

Nextcloud app version: 3.13.1

Nextcloud server version: 19.0.3

Thanks for your help!

**Comment by tobiasKaminsky** [comment]
Can you provide us a screenshot?
I do not fully understand the issue.

**Comment by Acipenser** [comment]
Sure, here's the mentioned **website layout** that I get:

![Screenshot_20200918-124231](https://user-images.githubusercontent.com/10635522/93589670-783acf80-f9ad-11ea-9f41-48c6fad98c93.png)

Furthermore I was able to reproduce this behaviour on another tablet coming with the manufacturer's Android. 
I found out that it must have something to do with the enabled Two-Factor TOTP Provider. I was able to login to another Nextcloud instance that is not using TOTP and see the correct **Android app layout**:

![Screenshot_20200918-130419](https://user-images.githubusercontent.com/10635522/93590864-943f7080-f9af-11ea-8046-54465d21195a.png)

Unfortunately, disabling TOTP in the user security settings leads to a hanging login page (same in Brave Browser, but after a reload I'm logged in):

![Screenshot_20200918-131243](https://user-images.githubusercontent.com/10635522/93591653-0a90a280-f9b1-11ea-9623-25800021294e.png)


(For privacy reasons I removed my Nextcloud logo and parts of my account name.)

**Comment by Acipenser** [comment]
Hi again, I was able to solve the issue by myself.

After adding `'overwritehost' => 'XXXX.de', 'overwriteprotocol' => 'https',` to config.php as mentioned [here](https://help.nextcloud.com/t/nextcloud-login-issue-google-chrome/65958/4), the hanging login problem with Brave was gone, but also the wrong layout with TOTP enabled disappeared!
