### ISSUE TITLE
Feature request apply AutoUpload to existing Files in Structure

### ISSUE THREAD

**Issue by 927589452** [nextcloud/android#696]
### Actual behaviour
- Files already on device are not synced ( and therefor not removed)

### Expected behaviour
- optional button in menu to "apply auto upload for existing files"

**Comment by AndyScherzinger** [comment]
@927589452 this would basically be handled by v3 of the auto upload implementation (still to be implemented), see #285 

@mario @tobiasKaminsky please correct me if I am wrong but the one-way sync (including the behavior choice) would implemented the requested feature :)

**Comment by tobiasKaminsky** [comment]
Technically this would be the "server -> device" part of the two-way sync.
(I understand that @927589452 wants to have files on the device deleted if they are changed on the server).
But yes, this is covered in #285

**Comment by 927589452** [comment]
Nope, that was not what I was thinking of;
I was thinking of applying the upload settings to folders that are
watched by auto upload, 
eg the device has already taken fotos and I want all fotos to be moved
to the server as soon as they are taken;
currently the fotos until this point in time stay on my device 
and are not synced unless i manually upload them later,
while newer ones are moved to the server.

**Comment by 927589452** [comment]
the requested feature seems to be in v1.1 proposition of #285

**Comment by AndyScherzinger** [comment]
Ah, right, my mistake. You are right v1.1 would cover your request 👍
