### ISSUE TITLE
Nextcloud app crash

### ISSUE THREAD

**Issue by Hysteria1212** [nextcloud/android#6962]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
Please provide some information and re-open

**Comment by Hysteria1212** [comment]
Hi, sorry to bother you. The message was send out to quickly. As soon I get
the error message again I will post it. For the moment I only can tell it
happens when there are two files with the same name on my server and my
phone. I'm getting the notification that there is a conflict. When trying
to open that screen for choosing the file, the nextcloud android app
crashes.

Cheers Norbert

Andy Scherzinger <notifications@github.com> schrieb am Mi., 16. Sept. 2020,
15:03:

**Comment by AndyScherzinger** [comment]
Hi @Hysteria1212, the crash should bring up a dialog which also has the error copied to your clipboard for easier copy&paste 👍

**Comment by Hysteria1212** [comment]
Yes that's was the problem last time I sent an empty report, did not
realize the error log is not been copy automatically. Anyway, I've tried to
force the error log again but it did not work. The notification concerning
the file conflict only shows up. When clicking on it nextcloud starts
telling me the conflict screen can't be created.

Attached a screenshot showing the specs of my phone (in German). It's a
Xiaomi Mi 9T pro.



Andy Scherzinger <notifications@github.com> schrieb am Mi., 16. Sept. 2020,
17:40:

**Comment by AndyScherzinger** [comment]
@Hysteria1212 the Screenshot is missing. I think you need to add it via the web since Mail replies won't work for attachments 😩

**Comment by Hysteria1212** [comment]
![Screenshot_2020-09-16-18-20-08-179_com android settings](https://user-images.githubusercontent.com/25246282/93521932-02911e00-f931-11ea-866a-606ff29c639b.jpg)

**Comment by Hysteria1212** [comment]
Has the error log been saved on the android system, so I can send it to you?

**Comment by AndyScherzinger** [comment]
Not that I am aware of. In case of a crash an error dialog should come up with all the infos 😕

**Comment by Hysteria1212** [comment]
Hello everybody.

The bug did not occur anymore. I was even able to choose between files if there was already one with the same name on my nextcloud server. Thank you.
