### ISSUE TITLE
Again conflict file versions are not removed from failed uploads after choosing file version and upload

### ISSUE THREAD

**Issue by smb500** [nextcloud/android#6963]
### Steps to reproduce
**1.** File version conflict appears, in this case three files from WhatsApp-Folder (ok)
see here:
![Unbenannt-1](https://user-images.githubusercontent.com/71374050/93328476-1008b400-f81c-11ea-919f-e96eefe0811a.jpg)

**2.** Choose which file you want to keep, in my case the newer one (ok)
see here:
![Unbenannt-2](https://user-images.githubusercontent.com/71374050/93328609-3d556200-f81c-11ea-8300-e9df604e4391.jpg)

**3.** The newer file will be uploaded (ok)
see here:
![Unbenannt-3](https://user-images.githubusercontent.com/71374050/93328612-3dedf880-f81c-11ea-8549-3d47e1d210f3.jpg)

**4.** The file version conflict is not removed from the list and still appears (this is the error...)
see here:
![Unbenannt-4](https://user-images.githubusercontent.com/71374050/93328614-3dedf880-f81c-11ea-92fb-ae4a63bb943e.jpg)

**5.** Additional information: If you reupload the existing files from the failed uploads list, you will see that both file versions are equal.
see here:
![Unbenannt-6](https://user-images.githubusercontent.com/71374050/93328618-3e868f00-f81c-11ea-9faa-19021e7d0074.jpg)

---
The problem is **not** the file version conflict. The problem is that the file version conflict popup reappears, even when the version conflict is solved and there are no different versions. When the app is open you can watch the file still remain in the section "failed uploads"

This error occured since last ver 3.13 (maybe June). Even with the new ver 3.13.1 from today/yesterday that error still occures.

The solution by hand is to upload the conflict files, then clear the "failed-uploads-section" (remove failed uploads) and all information popups.

I get the error with different mobile phones, Blackberry (Android), Samsung Galaxy 5 and 7 and 9 and different Android versions.

**Comment by tobiasKaminsky** [comment]
Fixed via #7102 
There is an APK file in this PR, which you can install in parallel to your existing Nextcloud app.

**Comment by ColinFinck** [comment]
@smb500 @tobiasKaminsky I still have this problem with Nextcloud App 3.19.1 and Nextcloud Server 23.0.2. Conflict prompts with overwrite requests are piling up despite having set the auto-upload to overwrite remote files automatically.

Please reopen this bug or #6938 for that. I have no such permissions.
