### ISSUE TITLE
NextCloud error

### ISSUE THREAD

**Issue by MaddHatterHX** [nextcloud/android#6967]
### Steps to reproduce
1. Open email with link to document.
2. Click on link to document.
3. Do NOT profit.

### Expected behaviour
- Tell us what should happen
I should get directed to a linked document.

### Actual behaviour
- Tell us what happens
No document.

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Which link?
Internal link within cloud? Share link?

**Comment by MaddHatterHX** [comment]
Two share links from two separate organizations.  When I click on either link I get redirected into 'Enter your Pin/fingerprint Hell'.  It doesn't matter if I enter my actual pin/fingerprint or both...same resulting 'Enter your....Hell' loop.

**Comment by tobiasKaminsky** [comment]
So something like? https://your.cloud.com/index.php/s/C6Z7DpXqb89jqHP

I tried it, but when clicking on such a link I only get Firefox/Chrome offered.
