### ISSUE TITLE
Full Folder Upload

### ISSUE THREAD

**Issue by 927589452** [nextcloud/android#697]
### Actual behaviour
- no select box on folders in Upload menu

### Expected behaviour
-Option to Upload (and delete) a full substructure from an arbitrary root

**Comment by chymian** [comment]
Is this going to be also an existing files upload, which existed before the time the NC-Client was installed/a folder was added? 
at the moment NC-C.dev 20180927 (fdroid)  does upload only new files, which is an erroneous behavior for a sync-client (IMHO).

**Comment by joshtrichards** [comment]
This is implemented. Closing.
