### ISSUE TITLE
Add account via SSO from 3rd party app results in wrong backstack

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/android#6971]
I think we might have an issue with the SSO on the Files app side.

Scenario:
- Open a 3rd party app
- use SSO to import an account
- choose "Add account" instead of an existing

Expected behavior (used to work some versions ago)
- Files app takes control
- Access granted at some point
- Files app shows the files of this new account
- Pressing back quits the files app and directly returns to the 3rd party app

Actual behavior:
- Like expected but pressing back goes back to the web ui stuff where the "grant permission" button was, each single step is in the back stack and one has to press back multiple times to return to the 3rd party app.

Sugar-candy solution:
- Like expected, but when new account request origins from a 3rd party app, directly return to this app after access was granted.

I can confirm this with Notes & Deck and i don't think it's caused by SSO but by the Files app.

**Comment by tobiasKaminsky** [comment]
>     * Like expected, but when new account request origins from a 3rd party app, directly return to this app after access was granted.

I assumed that we do this already… 🙈

**Comment by stefan-niedermann** [comment]
>  assumed that we do this already… 🙈

We *never* did this 😉. I think you once told me that it is impossible and we therefore always had to press the `back` button at least one time

**Comment by tobiasKaminsky** [comment]
![ssoLogin](https://user-images.githubusercontent.com/5836855/93750737-44091e00-fbfc-11ea-972f-f0fbacc826c2.gif)

**Comment by tobiasKaminsky** [comment]
> We _never_ did this wink.

Never say never :-D
https://github.com/nextcloud/android/pull/6983
