### ISSUE TITLE
Activity icon not scaled

### ISSUE THREAD

**Issue by thgoebel** [nextcloud/android#6976]
### Steps to reproduce
1. Open a file's details screen
2. Comment on the file

### Expected behaviour
- The "comment" icon should be fully visible

### Actual behaviour
- Only the icon's top left is visible, it is not scaled to fit the ImageView (compare it with the comment icon in the web interface)

### Screenshot
<img width=200 src=https://user-images.githubusercontent.com/33295590/93721266-0ae69480-fb8f-11ea-85cc-89c5b3dbf9c5.jpg>

### Environment data
Android version: 10

Device model: OnePlus 7

Stock or customized system: Stock

Nextcloud app version: 3.14.0 alpha 1

Nextcloud server version: 19

Reverse proxy: nginx

**Comment by tobiasKaminsky** [comment]
@nextcloud/designers 

I download svg image, which is in action:
rename -> https://github.com/nextcloud/server/blob/master/apps/files/img/change.svg
comment -> https://github.com/nextcloud/server/blob/master/core/img/actions/comment.svg

![image](https://user-images.githubusercontent.com/5836855/93737787-52e3d680-fbe4-11ea-8b6b-0ff8dfc769e9.png)

Difference I see is that comment.svg has a view viewBox: 0 0 32 32, whereas change.svg has 0 0 16 16.

**Comment by AndyScherzinger** [comment]
again cc/ping @nextcloud/designers for feedback https://github.com/nextcloud/android/issues/6976#issuecomment-695927428

**Comment by jancborchardt** [comment]
So basically for https://github.com/nextcloud/server/blob/master/core/img/actions/comment.svg we need to change the `viewBox="0 0 32 32"` to `viewBox="0 0 16 16"` – correct @skjnldsv (asking since you added that icon)?

**Comment by skjnldsv** [comment]
> So basically for https://github.com/nextcloud/server/blob/master/core/img/actions/comment.svg we need to change the `viewBox="0 0 32 32"` to `viewBox="0 0 16 16"` – correct @skjnldsv (asking since you added that icon)?

No, if you do that it will just crop. We need to fix the activity to make sure we scale icons.

**Comment by tobiasKaminsky** [comment]
With "activity" you mean Android?
I think we already do this, as otherwise we would have with all other svgs (e.g. uploaded images) also problems…

Therefore I had a look into it with Inkscape and there a scale "2" was shown.
I did a resize (quick and dirty).

Now it is shown correctly.
Server:
![image](https://user-images.githubusercontent.com/5836855/99501547-2ea23d00-297c-11eb-8142-214d5f04640d.png)

Android:
![image](https://user-images.githubusercontent.com/5836855/99501565-33ff8780-297c-11eb-9b14-8fece768975c.png)


I'll create a PR on server.

**Comment by skjnldsv** [comment]
No I mean, if you rely on images being always the same it's not ideal. We'll have to repeat the process every time. And we can't ensure any other app will have it properly set to 16px.
This should be addressed directly on the rendering, so any size is properly displayed.

**Comment by tobiasKaminsky** [comment]
Hm. On Android we pass the desired height/width to every decoding of svg.
I think it has its trouble that view box is bigger than the actual height/width specified in the svg (32 32 > 16x16)

**Comment by skjnldsv** [comment]
viewbox and svg sizes are different.
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/svg

height/width on svg root is what the standard use to render. The svg is rendered as 16px even if the viewbox is 32

**Comment by tobiasKaminsky** [comment]
I seem to have a fix.
