### ISSUE TITLE
Filtering: keep results even if opening a file / viewing an image

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#698]
- filter for some term
- open one of the results (view image, open file, show details of a file)
- go back
- it should still show the filter results as long until the user removes the query 

Ref: https://github.com/nextcloud/android/pull/661#issuecomment-282273453

**Comment by mario** [comment]
Like mentioned in that comment, there's already an issue for this, so please close this one as a duplicate @tobiasKaminsky 

https://github.com/nextcloud/android/issues/686
