### ISSUE TITLE
Fails to show contents of directory with ca. 120  PDF files

### ISSUE THREAD

**Issue by bedartha** [nextcloud/android#6988]
I am facing an issue with a large folder of PDF files which currently has ca. 120 files. The app does not crash but it does not proceed beyond the "Loading..." message. I can go to another part of the app without issues (I.e. app is not frozen) and dismiss the "Loading..." notification. It is however not possible to view the contents of the folder.

This does not happen with the Nextcloud web app for Firefox on Android.

### Steps to reproduce
1. Create a directory on Nextcloud and put approximately 120 PDF files in it (without any sub-directories)
2. Navigate to this directory on an Android device (galaxy tab s5e in my case) using the Nextcloud for Android app

### Expected behaviour
- The Nextcloud for Android app should have displayed a listing of the 120 odd PDF files in the directory

### Actual behaviour
- The app does not proceed beyond the "Loading ..." notification
- The app does not crash or freeze however. User can go back, view other files, do other stuff, but the particular directory with the PDFs does not show the file list

### Can you reproduce this problem on https://try.nextcloud.com?
- No, this problem does not occur on try.nextcloud.com
- The problem also does not occur on the web app for my account (using Firefox for Android)
- If not, please verify server setup and ask for help on forum <- I don't know how to do this

### Environment data
Android version: 10

Device model: Samsung Galaxy Tab S5E

Stock or customized system: Stock

Nextcloud app version: 3.13.1

Nextcloud server version: I don't know how to view this

**Comment by tobiasKaminsky** [comment]
Can you try out our dev version (you can install it in parallel): 
https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#developement-release

Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat
