### ISSUE TITLE
Nightly 20170301 Fingerprint support removed

### ISSUE THREAD

**Issue by JSoko** [nextcloud/android#699]
Don't know if that happend intentionally, if yes, than just close...

Fingerprint support was removed in 20170228 and is still absent in 20170301

### Actual behaviour
No Fingerprint support in Configurationmenu

### Expected behaviour
Fingerprint support in Configuration menu
 

### Environment data
Android version: 7.0

Device model:  sgs7

Stock or customized system: stock

Nextcloud app version: 20170301

Nextcloud server version:
11.0.2.5

**Comment by tobiasKaminsky** [comment]
I have re-added it. Must have occured due to a wrong merge.
Can you try it please on the next nightly (20170302)?

**Comment by JSoko** [comment]
Yes, I'll try it tomorrow and report back here...

**Comment by JSoko** [comment]
Fingerprint lock works again in 20170302 :-)
