### ISSUE TITLE
Auto Upload doesnt work properly anymore

### ISSUE THREAD

**Issue by Emporea** [nextcloud/android#7002]
App Version 3.13.1 (problem also in 3.13 i believe)
Server Version 19.0.3

I have several Folders for auto upload, including custom ones and camera / screenshot also.

The "normal" media stuff like camera gets uploaded most of the time. But sometimes even a "pull down refresh" in the Uploads Section wont do it. 

Custom folders wont get uploaded to any time.

That's really frustrating, i haven't changed anything, besides updating the android app.

**Comment by bushrang3r** [comment]
Same issue here.
I only have custom folders set up for autoupload, and brand new files that I add get auto uploaded, but any changed files don't. 
Also, it seems that if take a file out of local, delete it from server, then put the same one back in to local, it won't get auto uploaded.

**Comment by kodxana** [comment]
Same problem one time I managed to upload files to InstaUpload folder, then it stoped working :/

**Comment by Emporea** [comment]
Just for the record, i don't think it's the android based power save function. Nextcloud **_is_** allowed to run in the background.

**Comment by kodxana** [comment]
> 
> 
> Just for the record, i don't think it's the android based power save function. Nextcloud **_is_** allowed to run in the background. Atleast on my side.
> 
> It's more like Nextcloud doesn't recognize newly added files. Even when refreshing the page in Uploads.

That same. It also do not upload existing files.

**Comment by bushrang3r** [comment]
Yes, it's allowed to run in the background on my phone too.
I have gone back to 3.10.1 and autoupload seems to be triggering correctly (as others have also said) for adding new files and for updating changed files.

**Comment by Emporea** [comment]
@bushrang3r really so far as to 3.10.1? whats about 3.12 or something like that? I mean they had this "big" new UI update with 3.13.

**Comment by bushrang3r** [comment]
I saw others say that 3.10.1 was working so I rolled back to that too. I didn't try going back to 3.11.x, 3.12.x etc.

**Comment by tobiasKaminsky** [comment]
That is really strange.
I did not touched auto upload code, especially detecting of new images, for quite a while…

**Comment by bushrang3r** [comment]
Do you have logs on this? Perhaps I can provide some...

**Comment by Emporea** [comment]
It seems to be about custom folders and "non-media" files like for example Signal backup files, for what i am using the Auto Upload function.

Deleting the Custom Folder Upload config and re-enable it has no effect.

Copying a signal.backup file into DCIM/Camera results into nothing.
Copying a signal.backup file into DCIM/Camera and renaming it into signal.backup.jpg results into an successful upload.

Strangely enough I am also using TitaniumBackup files as CustomFolder for AutoUpload on my external sdcard where the files also results into a successful upload. Even Stranger; when I move a signal.backup file into that TitaniumBackup Folder it gets uploaded. Dafuq?


All in all its pretty hard to find a sense in it as it seems to be totally random.

**Comment by bushrang3r** [comment]
I just tried installing the latest dev version (20200927) and autoupload seems to be working correctly for me, for already existing files, newly added files, and updated files.

An empty folder will not be autouploaded (I think this has always been default behaviour) but if a file is put in the folder, both are autouploaded.

**Comment by da-anda** [comment]
as it seems kinda related - should removed pictures from your phone also be removed from NC by the sync logic? If so, it doesn't work for me. So if somebody is looking into autoupload/sync, please also take a look there.

**Comment by Emporea** [comment]
@da-anda  no. Auto Upload does not act like a synced folder. It just uploads any detected files. You can specify what happens with files on your devices after they got updated, tho.

**Comment by da-anda** [comment]
too bad, then NC is not what I am looking for. All I basically want is a cloud backup of my phone data (pictures mostly), but the data should stay on the phone and should stay in sync since I do not want to have to clean up two places.

**Comment by lfchow** [comment]
> @da-anda no. Auto Upload does not act like a synced folder. It just uploads any detected files. You can specify what happens with files on your devices after they got uploaded, tho.

Is there anyway of "flagging" the files manually? Mine seem to be missing one or two photos from time to time. That is not very reliable.

**Comment by lfchow** [comment]
> too bad, then NC is not what I am looking for. All I basically want is a cloud backup of my phone data (pictures mostly), but the data should stay on the phone and should stay in sync since I do not want to have to clean up two places.

NC doesn't have to be synced but it should try to re-upload files that exists on android but not on NC if you know what I mean. If a photo is removed from android then it should not remove from NC. That will allow us to remove those photos on Android for housekeeping and photos will remain on NC. That is pretty much how Google Photo works.

**Comment by da-anda** [comment]
> That is pretty much how Google Photo works.

I also use GooglePhotos (for now) and when I delete a file on my phone which had been synced already, it is also removed from the cloud. At least for me (I do not yet have cloud only files since my SD card is big enough to have everything locally). But IMO a cloud backup solution should differentiate between a regular delete and "delete local version". On regular deletion the file should also vanish from the cloud. In doubt add a setting on what should happen when a file got removed outside the NC app (keep cloud backup / also remove cloud backup).

**Comment by Emporea** [comment]
> 
> 
> > That is pretty much how Google Photo works.
> 
> I also use GooglePhotos (for now) and when I delete a file on my phone which had been synced already, it is also removed from the cloud. At least for me (I do not yet have cloud only files since my SD card is big enough to have everything locally). But IMO a cloud backup solution should differentiate between a regular delete and "delete local version". On regular deletion the file should also vanish from the cloud. In doubt add a setting on what should happen when a file got removed outside the NC app (keep cloud backup / also remove cloud backup).

Google Photos does the same thing as Nextcloud Auto Upload. The only difference is, that the integrated Photo Gallery is more appealing and reliable than Nextcloud's solution, and adds a feature like ( delete allready backed up local files ). You are mixing up Cloud based Photo Gallery ( Google Photos or in Nextcloud App -> Photos ) and the local Gallery app on your phone. 

If you delete any photos in the Nextcloud App Photos section, they are deleted from your Cloud, just like Google Photos does.

**Comment by nickvergessen** [comment]
Still have this in 3.14.0 RC1 in some way.
E.g. when I receive an image in Threema I get an error:
> ![Screenshot_2020-11-04-08-16-03-156_com miui home](https://user-images.githubusercontent.com/213943/98081441-62a73980-1e77-11eb-8763-52105c7194de.jpg)

When I click and select "keep existing one" in the conflict resolution:
> ![Screenshot_2020-11-04-08-16-13-539_com miui home](https://user-images.githubusercontent.com/213943/98081527-8d918d80-1e77-11eb-98fa-dad39993fda1.jpg)

I get another error that the upload failed:
> ![Screenshot_2020-11-04-08-16-28-310_com miui home](https://user-images.githubusercontent.com/213943/98081544-95513200-1e77-11eb-8b3a-e761f2487d58.jpg)

**Comment by tobiasKaminsky** [comment]
This is fixed via #7482 
It will be in todays 3.14.1 RC2, can you test it and report back?

**Comment by bushrang3r** [comment]
Thanks Tobias.
I've been using the new dev versions and they're working perfectly for me, but I will test 3.14.1 RC2 too.

**Comment by nickvergessen** [comment]
Also works much smoother here today
