### ISSUE TITLE
App quits with error on changing Auto upload directory 

### ISSUE THREAD

**Issue by cyberguy999** [nextcloud/android#7004]
### Steps to reproduce
1. Using Nextcloud server at home
2. Then on Android opening the Nextcloud app 20200913
3. On Auto Upload I want to change the photos upload dir from default to dir named "Photo" or "Photos" - It already contains a lot of photos.

### Expected behaviour
Normally it changes the directory

### Actual behaviour
App quits immediately with error. A bug report screen appears (java trackback list - but the text cannot be copied). Otherways the app normally changes the dir if I want use another directory

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 6.0

Device model: 
LGG4 dual (H818)

Stock or customized system: stock

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
> A bug report screen appears

Can you then post a screenshot of it?
