### ISSUE TITLE
Support for Circles needed so we can filter on items within a context/group/circle

### ISSUE THREAD

**Issue by LeeteqXV** [nextcloud/android#7007]
Unless I am missing something obvious, there is no support for Circles in the current app version.
This is sorely missed, as that filtering/context option is crucial for saving time looking for information.

**Comment by LeeteqXV** [comment]
(Without that feature, I most often need to use the mobile browser instead of the mobile app on the same device - which is less than ideal.)

**Comment by tobiasKaminsky** [comment]
You can share to a circle and you see if a file is shared to a circle.
What else do you miss?

**Comment by LeeteqXV** [comment]
The link to circles page, where we can filter content per circle.

**Comment by tobiasKaminsky** [comment]
Ah, you mean management of circles.
There are no plans to include this, as this is only for management, but not for daily usage.
Same like app settings, etc.
