### ISSUE TITLE
Nightly 20170301 pinch zoom doesn't work anymore in grid view

### ISSUE THREAD

**Issue by elpraga** [nextcloud/android#701]
### Actual behaviour
Pinch zoom in grid view doesn't work.

### Expected behaviour
Pinch zoom in grid view works.
 
### Steps to reproduce
1. Try pinch zoom in grid view.
2. 
3. 

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

**Comment by elpraga** [comment]
@AndyScherzinger I guess you were the one who wrote the wonderful pinch-zoom functionality. Do you have any idea why it got removed? Also, the thumbnails disappear almost all the time now, (see https://github.com/nextcloud/android/issues/734) and no new _nightly_ has been up for two weeks. 

Do you have any idea what's going on?

**Comment by AndyScherzinger** [comment]
@elpraga there should definitely be a nightly, at least I see one on f-droud for 20170314 which is 3 days ago. Actually @tobiasKaminsky wrote the pinch-zoom feature, can you have a look at this Tobias?

**Comment by elpraga** [comment]
Strange.. Nightly 20170301 says "No new version available" when checking from within the app. I also didn't find any new apks in the __beta__ branch on GitHub. (And I didn't see any Nightly branch either)

**Comment by AndyScherzinger** [comment]
@elpraga the apks aren't pushed to the repo anymore I think and the beta has been renamed to nightly (while the branch is still named beta). But you should see the new version via f-droid itself.

**Comment by elpraga** [comment]
Hi Andy! Thank you for your reply. It is a pity that the link within the app doesn´t work anymore, it was really useful. Nevertheless, I did try to install `Nightly_20170315`, over `Nightly_20170301`, but I only got a message __Not installed__ 

Unfortunatelly, I cannot investigate why that happened right now. But thank you for pointing out the F-Droid builds for me.

**Comment by AndyScherzinger** [comment]
You are very welcome @elpraga - @tobiasKaminsky can you look into this? :)

**Comment by tobiasKaminsky** [comment]
Next week I will rebuild nightly version from scratch, hoping that this will make everything working again.

**Comment by tobiasKaminsky** [comment]
Pinch zoom is now in master and will be in next release
