### ISSUE TITLE
"Server in maintenance mode" message, when accessing internet through squid proxy and connection from proxy to server failed

### ISSUE THREAD

**Issue by egor-duda** [nextcloud/android#7014]
### Steps to reproduce
1. Client accesses server via squid proxy
2. Block internet connection from proxy to server (via firewall, for example, or just disconnecting proxy from the internet)
3. Try to access server

### Expected behaviour
- Client should show "Server unreachable" message

### Actual behaviour
- Client shows "Server in maintenance mode" message

### Can you reproduce this problem on https://try.nextcloud.com?
not applicable

### Environment data
Android version:
7.1.2
Device model: 
Google Nexus 5
Stock or customized system:
LinageOS 14.1
Nextcloud app version:
3.13.1
Nextcloud server version:
18.0.9
Reverse proxy:
apache2 version 2.4.38-3+deb10u4
### Logs
Local proxy responds to client request with 
< HTTP/1.1 503 Service Unavailable
< Server: squid/4.6
< Mime-Version: 1.0
< Date: Fri, 25 Sep 2020 16:03:59 GMT
< Content-Type: text/html;charset=utf-8
< Content-Length: 3538
< X-Squid-Error: ERR_CONNECT_FAIL 110
< Vary: Accept-Language
< Content-Language: en

And client interprets this http status 503 as "server maintenance mode" instead of connection failure

**Comment by tobiasKaminsky** [comment]
@MorrisJobke I remember that we talked about 503 which can be both unavailable and maintenance mode…
A solution would be to pass "maintenance" with 503 in case of real maintenance mode.
Then clients can check this.
