### ISSUE TITLE
User status

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/android#7016]
### Describe the solution you'd like
Visibility of your status next to the avatar and the possibility of changing it.

**Comment by AndyScherzinger** [comment]
Hi @Valdnet can you elaborate what you mean with status regarding a user in the files app? (or did you mean to post this feature request to the talk client?)

**Comment by Valdnet** [comment]
@AndyScherzinger NC20 allows you to change the user status as standard.

![obraz](https://user-images.githubusercontent.com/47037905/94370852-a6798700-00f2-11eb-8fcc-bef2794c9172.png)

My request for a function is that the user status that you set will be displayed on the avatar in the application.
Something like that:

![obraz](https://user-images.githubusercontent.com/47037905/94370836-88ac2200-00f2-11eb-8b17-73faeb254833.png)

Additionally, so that the current user status can be changed via the Nextcloud Android application.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky do you know if a corresponding API is available? :)

**Comment by tobiasKaminsky** [comment]
Yes, it is. 
Actually I already started working on it, but some Talk related higher priorities crashed my time schedule…
