### ISSUE TITLE
Unable to authenticate without internet access with NextcloudServer on Intranet

### ISSUE THREAD

**Issue by aleadco** [nextcloud/android#7025]
### Steps to reproduce
1. Sign in from the app on my Nextcloud on the Intranet
2. 
3. 

### Expected behaviour

- A successful login

### Actual behaviour
- It is impossible to connect to the nextcloud service that is within the entity's internal network. The interesting thing is that if we enable the device's internet access then the application works.

### Can you reproduce this problem on https://try.nextcloud.com?
NO

### Environment data
Android version: 8

Device model: 
Samsung Galaxy S8 and other devices of various brands and models of high and medium range.

Stock or customized system:

Nextcloud app version: 3.13.1

Nextcloud server version: 19.0.3

Reverse proxy: Yes, but only for access outside the entity and this is not a problem.

**Comment by tobiasKaminsky** [comment]
What is happening when you try to log in?
Which kind of intranet setup do you have?
Can you access your NC via web browser from mobile?
