### ISSUE TITLE
Contacts with umlauts ä / ü / ö etc. are not imported

### ISSUE THREAD

**Issue by 0110101** [nextcloud/android#7026]
### Steps to reproduce

https://help.nextcloud.com/t/kontakte-android-synchronisieren-mit-davx5-in-nur-eine-richtung-one-way-sync/90544/17?u=faulpelz

### Environment data
Android version: 9

Device model: Samsung Galaxy S8+

Nextcloud app version: 3.13.1

Nextcloud server version: 19.0.3

#### Web server error log
```  

webdav | Sabre\DAV\Exception\UnsupportedMediaType: Validation error in vCard: ENCODING=QUOTED-PRINTABLE is not valid for this document type./var/www/nextcloud/3rdparty/sabre/dav/lib/CardDAV/Plugin.php - line 303:Sabre\CardDAV\Plugin->validateVCard()/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php - line 89:Sabre\CardDAV\Plugin->beforeCreateFile()/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 1100:Sabre\DAV\Server->emit()/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 527:Sabre\DAV\Server->createFile()/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php - line 89:Sabre\DAV\CorePlugin->httpPut()/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 474:Sabre\DAV\Server->emit()/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 251:Sabre\DAV\Server->invokeMethod()/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 319:Sabre\DAV\Server->start()/var/www/nextcloud/apps/dav/lib/Server.php - line 320:Sabre\DAV\Server->exec()/var/www/nextcloud/apps/dav/appinfo/v2/remote.php - line 35:OCA\DAV\Server->exec()/var/www/nextcloud/remote.php - line 167:require_once("/var/www/ne ... p")
-- | --
```

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky for a detailed analysis please see the referenced forum post

**Comment by j-ed** [comment]
@tobiasKaminsky I think the given subject reflects only the result of the problem but not the root cause of it. It seems that the contact backup function creates vcf files in vCARD 3.0 format, which still contain vCARD 2.1-specific quoted-printable encoded entries. I've summarized my findings [**here**](https://help.nextcloud.com/t/kontakte-android-synchronisieren-mit-davx5-in-nur-eine-richtung-one-way-sync/90544/18?u=j-ed).

**Comment by AndyScherzinger** [comment]
Well it is even more complicated ;)
We get the export from Android (v2.1= and let the vCard lib convert it ti 3 for importability in Nextcloud) unfortunately the lib doesn't seem to take care of converting the quoted-printable encoded entities :(

maybe this could be achieved by using Apache Commons Codec

**Comment by tobiasKaminsky** [comment]
> lib doesn't seem to take care of converting the quoted-printable

Then please report this upstream.

**Comment by AndyScherzinger** [comment]
> Then please report this upstream.

@tobiasKaminsky Unfortunately I haven't found the time yet to report this to the lib project at https://github.com/mangstadt/ez-vcard/issues

**Comment by j-ed** [comment]
@AndyScherzinger , @tobiasKaminsky I've created the following issue ticket in the given repository for you:

https://github.com/mangstadt/ez-vcard/issues/112

**Comment by AndyScherzinger** [comment]
Thanks a lot @j-ed and it has been fixed by the maintainer already, so hoping for a quick release :)

**Comment by 0110101** [comment]
@AndyScherzinger .... what I am writing now is not meant seriously ;-)

Thanks to me ;-)

I spent hours testing it and posting it on the Nextcloud forum just wanted to mention it ;-)

Thanks to the supervisor and for the info.

**Comment by AndyScherzinger** [comment]
@0110101 I am just happy if it solves the issue (not yet released or tested with Nextcloud...) and yes, you did a magnificent job analyzing the matter and finding the root cause 👏
