### ISSUE TITLE
How to correct reviewed translations on Transifex?

### ISSUE THREAD

**Issue by korelstar** [nextcloud/android#703]
I found some translations (German) where the spelling is not accurate. I'm already translator on Transifex but I can only change strings which are not reviewed yet.

How to proceed for incorrect reviewed strings?
I can add a new suggestion for the string, but will this have any effect (i.e. will somebody ever check and apply this)?

Example: `Kalender &amp; Kontakte Sychronisierung erfolgreich konfiguriert` is not correct German (hyphen missing) and could be improved to `Kalender- &amp; Kontakte-Sychronisierung erfolgreich konfiguriert` or `Synchronisierung der Kalender und Kontakte erfolgreich konfiguriert`. But there are many others, where I would like to improve spelling.

**Comment by JSoko** [comment]
That was in there for over 6 Month, but you're right, it's corrected and you should be able to improve it. 
If you have other translations, wich you would like to edit, just send me the english sentence per pn.

**Comment by korelstar** [comment]
What do you mean by "pn"? Private message? As far as I know, there is no such concept on GitHub.

For now, I have some improvements for the "about" screen. But the last time I went through the translations, I added some "suggestions" to Transifex. But currently, I have no time to search for them. It seems that there is no easy way to list all strings with manual suggestions.

- `participate_testing_headline`: `Helfen Sie uns beim Testen`
- `participate_testing_bug_text`: `Fehler gefunden? Merkwürdiges Verhalten?`
- `participate_testing_version_text`: `Möchten Sie uns beim Testen der nächsten Version unterstützen?` (oder konservativ: `Interessiert, uns beim Testen der nächsten Version zu unterstützen?`)
- `participate_release_candidate_headline`: `Vorabversionen`
- `participate_release_candidate_text`: `Eine Vorabversion, auch Release Candidate (RC) genannt, ist ein stabiler Stand der kommenden, finalen Version. Ein Test in der eigenen Umgebung hilft uns diese Stabilität sicherzustellen. Melden Sie sich als Tester im Play Store an oder suchen und installieren Sie die passende Version bei F-Droid unter „Versionen“.`
- `participate_beta_headline`: `Testen Sie die Beta-Version`
- `participate_beta_text`: `Die Beta-Version beinhaltet neue Funktionalitäten und ist nicht vollumfänglich qualitätsgesichert. Es können daher Fehler auftreten, die Sie uns dann bitte melden.&lt;br/>&lt;a href="%2$s">APK herunterladen&lt;/a> oder`
- `participate_contribute_irc_text`: `An Diskussionen im IRC teilnehmen: &lt;a href="%1$s">#nextcloud-mobile&lt;/a>`

As you can see, these are minor changes. However, I think the changes improve the impression (user experience :stuck_out_tongue_winking_eye:) of the app.

However, I propose to *unlock* all entries on Transifex, because I will probably find more sub-optimal translations. 😁

**Comment by JSoko** [comment]
> What do you mean by "pn"? Private message?

Yes, I ment PN on transifex...

Your changes are in transifex and I'll look at the reviewed entries soon...
