### ISSUE TITLE
Upload folder

### ISSUE THREAD

**Issue by mikrofyr** [nextcloud/android#7032]
Add a way to upload folders. 

It should basically work like "Auto Upload" , but be a one time manual thing. 
The automatic sync in Auto-Upload is not really working as far as I can tell. 

Alternatively: 
1) Rename "Auto Upload" to "Upload", 
2) default to manual one time upload of all files in source, 
3) Let user select what to do with duplicates
4) Let people select auto-sync-thingy if they want to

See also https://github.com/nextcloud/server/issues/23106

**Comment by AndyScherzinger** [comment]
Afaik this can be closed as duplicate(s)

* #6629 as an issue describes manual folder uplaod with #4859 being the stale dev! work
* auto aploading non-media folders are3 already present via the menu being called "custom folders"

**Comment by AndyScherzinger** [comment]
cc @tobiasKaminsky for feedback

**Comment by mikrofyr** [comment]
>auto aploading non-media folders are3 already present via the menu being called "custom folders"
Sure, but the auto-syncing is not really working. Seems to me that it works by timestamp, and does not sync over older files, which it assumes is present on server side.
Anyways, it would be very nice to disable the "auto-functionalty" and sync everything on user action.

PS: The app is otherwise very nice, this is the one thing I feel is missing.

**Comment by AndyScherzinger** [comment]
For media folders (an in non-custom) there is a trigger to upload existing files right when you activate Auto Upload for a folder, for custom folders I am not sure. 

I get the sync argument while that is why we called it upload since this isn't a "real" sync. There are no diffs, checks or else. So that could be closed in favor of #285

**Comment by AndyScherzinger** [comment]
> It should basically work like "Auto Upload" , but be a one time manual thing.

That could simply be achieved by manually uploading files to a folder and when selecting the files to be uploaded just hit "select all"

**Comment by mikrofyr** [comment]
>just hit "select all"

Will this be able to select sub-folders? If not it will only work for folders containing only plain files. I also struggled with picking destination when manually uploading files, but that might be a user error on my side.

If the Auto Upload feature can be improved that sounds like what I need. I'll watch 285 and make some more trials on my side.

**Comment by AndyScherzinger** [comment]
> Will this be able to select sub-folders?

I think (as in guess) that we don't support arbitrary structures, but I am not sure, maybe @tobiasKaminsky can answer that.

**Comment by tobiasKaminsky** [comment]
Select all only applies to files if I remember correctly.

**Comment by mikrofyr** [comment]
OK. 
I don't think it is perfect, but I have found ways to do what I need in the app. Closing ticket and hoping for nice updates in the future. 

Thanks

**Comment by AndyScherzinger** [comment]
Yup, keeping our fingers crossed 👍
