### ISSUE TITLE
Android 11 Progress bar issue loader not display and circular

### ISSUE THREAD

**Issue by sarvaiyajai** [nextcloud/android#7033]
### Steps to reproduce
1. Use the ProgressBar and run the application in Android 11 and check loader will display with the Refresh icon not with the circular icon and it's not loading rotating. You can check this issue in Android 11 device in play store app as well.

Nothing found in Android developer official website link also.

### Expected behaviour
- Same as early OS it will loading circular as per the behaviour

### Actual behaviour
- Currently not display loading icon and not loading. Currently it is display refresh image with nothing happen. 

### Environment data
Android version: 11

Device model: Pixel 2
![device-2020-09-30-173543](https://user-images.githubusercontent.com/4685899/94683051-81c81e00-0343-11eb-9dd7-eb941dbe7b59.png)
![ProgressBar](https://user-images.githubusercontent.com/4685899/94683067-8a205900-0343-11eb-9111-0b14f5c97a41.png)

**Comment by AndyScherzinger** [comment]
@sarvaiyajai can you elaborate a bit more (may also a screenshot of the issue within the Nextcloud app) as to what extend this is related to the Nextcloud Android app?

**Comment by sarvaiyajai** [comment]
Hi @AndyScherzinger this is the generic issue of loader in Android 11. Can you check Nextcloud app in Android 11 with default loader implementation? And see it will look likes my screenshot.

In short in Android 11 ProgressBar is not working. Just check with practically and see the issue.

**Comment by AndyScherzinger** [comment]
Hi @sarvaiyajai  I just checked and everything is fine within our app. Having that said, we themed any progress bar _and_ while the app runs on Android 11 we still use Android 10 as the compile target.
