### ISSUE TITLE
Auto upload

### ISSUE THREAD

**Issue by mikrofyr** [nextcloud/android#7041]
### Steps to reproduce
1 Upload a folder with "Auto Upload" from Android
2. Delete files on  sever
3. Try to upload the same folder from Android again to same or different folder. 

### Expected behaviour
Android app should upload the folder

### Actual behaviour
Android app does not upload folder, nomatter what I try

### Can you reproduce this problem on https://try.nextcloud.com?
Running latest docker image at home. Given the functionality I think this must be an App bug.

### Environment data
Android version: 10

Device model: 
Samsung s10

Stock or customized system:

Nextcloud app version:
3.13.1
Nextcloud server version:
19.0.3
Reverse proxy:
ngnix

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
This is by design

Again a real sync would be #285 and even then we might rather sync the deletion to the client !

The reason for this behavior is that you "re-activate" the auto upload for that folder so we don't trigger another re-upload of the files. The only way is to manually select the missing files and upload them.

cc @tobiasKaminsky - imho to be closed

**Comment by mikrofyr** [comment]
OK, seems that a workaround is to create a new "Auto Sync" folder with the same source and some destination.
I think I'll just have to accept that the app works the way it works, and is not perfect for my workflow. 

Thanks.

**Comment by AndyScherzinger** [comment]
It might work the way you described it some time in the future while even with sync it's hard to say if it would meet you use case.
Deleted files could also be restored via the trash bin, so that might be another solution.

**Comment by AndyScherzinger** [comment]
Thank you for your understanding ❤️
