### ISSUE TITLE
Update Build for Android Studio 2.3

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#705]
At the moment the build is based on Android Studio 2.2 capabilities and with Android Studio 2.3 just been released (https://android-developers.googleblog.com/2017/03/android-studio-2-3.html), we got a mayor upgrade for gradle which should speed up the build process.

A branch has already been created here: https://github.com/nextcloud/android/tree/androidStudio23 for the "code change" while in order for this to work properly we also need to update the corresponding docker image which would also be part of the PR. The PR should then be for Release 1.5 or later leaving the build process of 1.4.2 untouched for stability reasons to not further slow down its release.

cc @tobiasKaminsky @mario

**Comment by mario** [comment]
cc @MorrisJobke for docker magic xD

**Comment by mario** [comment]
You create too many branches. A tree falls if it has too many branches. Some must be cut so others could live!

**Comment by AndyScherzinger** [comment]
This will btw also mean upgrading the build tools version. So while we are at it I'd also propose to move to AppCompat v25.2.0.

We could do this early on so it would be tested and we would be on top of the tool chain versions :)

**Comment by AndyScherzinger** [comment]
@mario we just have to do small and lightweight branches, they don't hurt the tree and can get cut off fast ;)

**Comment by MorrisJobke** [comment]
android-15 is already on 25 😉 

https://github.com/nextcloud/docker-ci/commit/74219a8ba5d917074b5cb713888dff28fc6a8090

**Comment by tobiasKaminsky** [comment]
AppCompat should be done in a separate branch.

**Comment by mario** [comment]
@MorrisJobke this is about Gradle.

**Comment by mario** [comment]
This is not in a PR yet.

Btw. why do you prefer micro-branches? Just like micro-managing it sucks to have to do this and complicates many things and brings ... well, not so many things :D

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky like @mario said there isn't one yet since getting the gradle update right with the image in mind to save download times. As for the AppCompat I'd usually agree but since the image is already in 25.0.0 I'd say let's use this issue/PR to just bump it to 25.2.0. 

@tobiasKaminsky let's make an exception here? :)

**Comment by AndyScherzinger** [comment]
@MorrisJobke at least the build tools are an issue:
```
Checking the license for package Android SDK Build-Tools 25.0.2 in /opt/android-sdk-linux/licenses
Warning: License for package Android SDK Build-Tools 25.0.2 not accepted.
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring root project 'android'.
> You have not accepted the license agreements of the following SDK components:
[Android SDK Build-Tools 25.0.2].
```
--> https://drone.nextcloud.com/nextcloud/android/2513

**Comment by AndyScherzinger** [comment]
maybe we need something like this back?
```
-# currently used image is included in the base image
-RUN cd /opt && /opt/tools/android-accept-licenses.sh "android-sdk-linux/tools/android update sdk --all --no-ui --filter build-tools-25.0.2"
```

**Comment by MorrisJobke** [comment]
> maybe we need something like this back?

This tool doesn't exist anymore :/



> @MorrisJobke at least the build tools are an issue:

Mmmmh ... last time it worked :/

**Comment by AndyScherzinger** [comment]
@MorrisJobke well, the build say: License for package Android SDK Build-Tools 25.0.2 not accepted.

:/

**Comment by AndyScherzinger** [comment]
@mario @tobiasKaminsky @MorrisJobke any idea how to solve this ? 0_o

**Comment by AndyScherzinger** [comment]
Done, while staying with build tools 25.0.0
