### ISSUE TITLE
The forced renaming of photo for photo upload not working

### ISSUE THREAD

**Issue by changemenemo** [nextcloud/android#7057]
### Steps to reproduce
1. Tried to change the parameters for each folder
Maybe I've not set it up right from the beginning 

### Expected behaviour
But the change of parameters should have change the parameters for all current  conflicts of sync 
### Actual behaviour
- I have currently 2730 problems of sync because I guess there is already a version on the server because of a previous version who had problems and I would like to have the parameters applied to all2730 of them. 
Even manually it doesn't work, but that's maybe of timeout because my server is slow (arm board)

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- 

### Environment data
Android version: 10

Device model: fairphone 3

Stock or customized system:  stock from fairphone 3

Nextcloud app version: 3.13.1

Nextcloud server version: 19.03

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
The webapp server nextcloud or nginx?
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
Which log? The app or server?because in the server I have no errors seems to. 
Which folder is it in the phone exactly? It s not in the folder storage in settings. 
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
If you change settings in auto upload after an upload was queued, then this will have the old preferences.
You would then remove all pending uploads and then re-upload them.

We can think about changing this in future…

**Comment by boistordu** [comment]
Okey but does that mean that I need to re-up load the entire photo library? Because how would he detect that he needs to re-upload this photo?

**Comment by tobiasKaminsky** [comment]
Yes, but if configured, it should skip all files with the same name.

**Comment by boistordu** [comment]
That was not my question. I meant that when you skip intentionally a file, then I don't see why the system would retry it. So shouldn't we have a button to ask the app to re-verify the list of files and compare those 2 and upload the missing files?

**Comment by tobiasKaminsky** [comment]
> I meant that when you skip intentionally a file, then I don't see why the system would retry it.

That is currently not planned…
