### ISSUE TITLE
Difference between Nextcloud Nightly and Nextcloud 1.4.2 RC1

### ISSUE THREAD

**Issue by OlivierS1** [nextcloud/android#706]
### Actual behaviour
I am at loss when it comes to understanding the roadmap and bug fixes between both version of Nextcloud app Nightly (Old Beta designation) and 1.4.2 RC1.
I have seen issues related to Autoupload under Nightly that were fixed under 1.4.2 RC1 but remains broken under Nightly.
Also not everything that has been improved, added or fixed in Nightly finds its way into 1.4.2 RC1.

I was under the impression Nightly was the next major release and would replace 1.4.2 after most bugs where fixed.

Can we get some lights to what is happening?
Is Nextcloud Nightly supposed to be incremental update for 1.4.2 RC1 or is it supposed to be targetting the next release.

I am just confused.

**Comment by mario** [comment]
No, nightly is something that includes bunch of branches that are in the works and might never make it into stable.

There is no "stable" 1.4.2 RC1 yet - I only built this for you and a few other people as it was easier for me than building a new nightly.

**Comment by mario** [comment]
Hope that clarifies things?

**Comment by OlivierS1** [comment]
Hi Mario,
It doesn't clarify things much,
I understand 1.4.2 RC1 is not stable but it is targeted to become release version. At least it is the intent, and having beta tester like many like me is to evaluate various issues related to bugs, usability and such.
I understand Beta, now renamed Nightly is an experiment about what Nextcloud app could become.
At the end of the day, only one version should prevail. The Release version, but we are always looking at the future as we are always unsatisfied user, so we need to improve upon the existing work. Hence the beta (Nightly)release, always pushing ourself to make things better..

Considering the above, and having seen some of the discrepancies between Nightly and RC1, how can you manage the various branches and that exist? Isn't it counter productive?
If something works out of the Nightly or RC version, would it make sense to keeps what works best, or is there too many issues due to library or coding technics/practice that prevent seamless transition from one version to the next?

How much work does it take to build the new nightly?
The company I work for does design electronic systems running Android, and I am being told building from scratch requires significant amount of time. however, the task is somewhat automated. So it can be done in a few hours.
What is preventing you from doing this kind of work on a daily basis?

**Comment by tobiasKaminsky** [comment]
The workflow is like this
new feature/idea -> accepted -> developing -> PR -> Code review -> merge
this is done for the master version. If "enough" PRs are merged we release a release candidate (e.g. 1.4.2 RC1).
In parallel every PR that is working (but not 100% tested) will be added automatically to the nightly version. 
If we/you find a bug or decide to do a UI enhancement we do this always in the original PR. Modifying directly the nightly version is not something we do (except for nightly only related code).
With this approach it is not very hard to manage the different versions.

**Comment by tobiasKaminsky** [comment]
To prevent confusion in the future a separately build version, like @mario did for testing new auto upload, maybe should be named like the purpose of it, e.g. "Auto uploading test 20170303". 
With this it is clear that it is not the release candidate (as the RC has many more other branches).

**Comment by OlivierS1** [comment]
@tobiasKaminsky It does make more sense now, I think.
However,one issue I found when trying to install 1.4.2 RC1 from @mario's  APK, was that I couldn't install it because the official Nextcloud app 1.4.1 was installed from the Google play store.
I had to remove the official release to install and test 1.4.2 RC1 from Mario. Hence the confusion.
Following the new naming structure @tobiasKaminsky  you mentioned, both APK and release cannot coexist together because they both use the same directory path which is com.nextcloud.client.
It would make sense a new directory name be used by the non offical apk fle.

**Comment by AndyScherzinger** [comment]
> However,one issue I found when trying to install 1.4.2 RC1 from @mario's APK, was that I couldn't install it because the official Nextcloud app 1.4.1 was installed from the Google play store.

the have the exact same namespace (technically given) and so Android detects different signatures since the play store APK is signed with the release key, while the debug build is not, so Android prevents the update, security measure.

@mario's special build will go away now since the Auto upload changes have been merged to master and been released as 1.4.2 RC1 and RC2 on Google Play. :)
