### ISSUE TITLE
Upload a big file manually or via auto upload with "move to nc folder" 

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#707]
When uploading a big file manually or via auto upload and with the option "move to nc folder" the file is being uploaded and moved correctly to the nc folder. But the app does not show the green downloaded arrow and thus tries to download the file again.

Yesterday I did some research and it seems that the mLocalPath is still set to the source path. But while debugging it the move function in UploadFileOperation.java is used and there mLocalPath is being set correctly. 
But on browsing the files, the value is still wrong in the database...

This was reported by @AndyScherzinger for rewriteAutoUpload branch by @mario 
I tested it against master and there everything is working.
Currently I am out of clue, therefore opening this issue...

**Comment by AndyScherzinger** [comment]
For some reason it is now working with today's state of the branch?! So I'd close it and will re-open in case it comes back.

**Comment by mario** [comment]
Not for some reason lol.

It works because I fixed it.

**Comment by AndyScherzinger** [comment]
Oh cool :)

You are awesome @mario! The string thing?

**Comment by mario** [comment]
https://github.com/nextcloud/android/commit/c9749698fa701ce96a7a8dff6e7f9b8edae4ec65 :)

**Comment by AndyScherzinger** [comment]
👍 great! :)
