### ISSUE TITLE
High Background Data Usage

### ISSUE THREAD

**Issue by vKnmnn** [nextcloud/android#7076]
since the ticket got closed by stale bot, i'm reopening here. see #4511 for details

The android app has used 2.54GB of background data in the past 30 days for me.

**Comment by tobiasKaminsky** [comment]
How many files have you downloaded?
Do you use any app that uses SSO, e.g. Deck or News?

**Comment by vKnmnn** [comment]
The app shows 61 local files on my phone. I have contact sync activated   and automatic photo upload too, although limited to Wi-Fi usage.
I use nextcloud cookbook app, but I installed this only a few days ago.

As far as I can see there are no pending uploads.

**Comment by tobiasKaminsky** [comment]
Can you disable auto upload for 1-2 days and see if this helps?

**Comment by vKnmnn** [comment]
I had high data usage months back before I enabled it the first time. But yeah I can do that.

**Comment by vKnmnn** [comment]
Disabling auto-update helps.

Does this mean there’s somehting wrong with the detection of wifi vs mobile connection?

**Comment by tobiasKaminsky** [comment]
That is surprising.
Can you verify if any uploaded image was uploaded via mobile?

**Comment by vKnmnn** [comment]
No, the photos do not seem to be uploaded. still, there a lot of requests happening. is it possible, that these requests add up to the amounts of data i see?

**Comment by vKnmnn** [comment]
bump

**Comment by motey** [comment]
Here same on one of the devices connected to our Nextcloud running version 3.15.0 connected to Nextcloud 20.0.7

**Comment by vKnmnn** [comment]
bump
