### ISSUE TITLE
Android Whitespace

### ISSUE THREAD

**Issue by 12nick12** [nextcloud/android#7079]
Hi, I created a new admin user and removed my normal account from the admin group. Now when I open Nextcloud I get whitepsace (gray since it's dark themed) at the top. I've made sure to re-install the app and make sure all data from the app is cleared. I also uninstalled the recommendations app thinking it was maybe those. I did have to remove myself from the admin group via CLI since I kept getting some error trying in the GUI. I still got an error using OCC, but it did work. This was the error I received from OCC.

![2020-10-12 12_01_44-Debian](https://user-images.githubusercontent.com/17801285/95767503-d728f700-0c82-11eb-8601-4c5109fb6e17.png)

Here's a picture of the issue in the android app
![Screenshot_20201012-113952](https://user-images.githubusercontent.com/17801285/95767980-9e3d5200-0c83-11eb-8f74-43f8979746f7.png)

**Comment by AndyScherzinger** [comment]
@12nick12 can you check the content of the readme markdown file in that folder (which is what is being displayed at the top as "whitespace" in your case. We do display this file's content in that area (even if it is empty).

**Comment by 12nick12** [comment]
Thank you so much. That fixed my problem.

**Comment by AndyScherzinger** [comment]
Glad we could help :)

**Comment by tobiasKaminsky** [comment]
As this request happens very often, we should think about enhancing this.

At least for empty readme.md I would simply do not show it.

What do you think?
@AndyScherzinger @jancborchardt

**Comment by AndyScherzinger** [comment]
Hiding rich workspace for an empty readme makes sense, yes 👍
