### ISSUE TITLE
File Upload Conflict won't resolve

### ISSUE THREAD

**Issue by hank** [nextcloud/android#7082]
### Steps to reproduce
1. Take a screenshot that gets instant uploaded
2. Crop it and save over the original
3. Use the conflict dialog to pick the new version
4. Observe bug where notification never goes away and conflict never resolves regardless of how many times you pick a version to keep.

### Expected behaviour
- Selected version uploaded replacing original

### Actual behaviour
- Dialog never resolves

### Environment data
Android version: 11

Device model: Pixel 3

Stock or customized system: Stock

Nextcloud app version: 3.13.1

Nextcloud server version: Latest docker

Reverse proxy: Caddy

**Comment by hank** [comment]
I take screenshots on my phone and crop them immediately. This causes Instant Upload to have a conflict when I do it. I try to resolve the conflict with the cropped version, but it never resolves. I keep getting the conflict notification, and the only way to get rid of it is to cancel the upload of that item. Please fix this. Thanks!

**Comment by NicolasGoeddel** [comment]
I do the exact same thing with screenshots and I got exactly the same behaviour. It's really annoying. The notification pops up again and again and again. I only can resolve it when I remove both files on the server and wait until it gets uploaded again. Then the issue goes away.

**Comment by IngoBelka** [comment]
I'm using the app, to synch/share a TiddlyWiki. I can confirm, the bug is still there.
I get the conflict message each time, if the size of a file remains the same but the date is different. Solving the conflict will not work, but one can clear the conflicts via settings->uploads. It should work automatically.

**Comment by tobiasKaminsky** [comment]
There is an APK file in this PR, which you can install in parallel to your existing Nextcloud app.
