### ISSUE TITLE
Ignore .thumbnails folder in Auto Upload

### ISSUE THREAD

**Issue by Peter-JanGootzen** [nextcloud/android#7085]
### Is your feature request related to a problem? Please describe.
Android (at least on MIUI) automatically generates a ".thumbnails" folder where unsurprisingly generated thumbnails are stored. When using Auto Upload one cannot specify that hidden folders and files should be ignored nor can you specify specific sub folders that should be ignored.
These thumbnails are useless to sync to NextCloud and they take up extra bandwidth, time and phone battery.

### Describe the solution you'd like
Some way to ignore the .thumbnails sub folder when using Auto Upload. Be that ignoring specific folders or just ignoring hidden folders in general. I would say that adding a simple checkbox with the option to ignore hidden folders would be the best middleground between effort needed to implement and the usefulness. If other Android distributions generate other hidden folders for things, this would solve that problem as well.

### Describe alternatives you've considered
The only relevant issue I could find was #3177.

**Comment by tobiasKaminsky** [comment]
Indeed, we should change detection in #3177 to check if folder name starts with ".thumbnail", as then also ".thumbnails" would be detected.

**Comment by AndyScherzinger** [comment]
I'll also add this to the ignore list for the folder detection so it won't trigger media detentions and won't show up on its own in the auto upload list, via an extension of #7042
