### ISSUE TITLE
Resized images: zoom behaviour

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#71]
Idea to download the full sized image:
- Zooming a resized image with at least 2x (which can get blurry)
  - show snackbar "automatically download full image on zoom: yes"
  - Clicking "yes" after second time will offer option "always" to prevent showing the question.
- time out the snackbar the second time by just waiting will show "never download full image" -> "yes".
- after both show second snackbar without action "default behaviour can be changed in settings"
- In setting: new entry "click on image downloads ..."
  - full image to storage
  - resized image to cache

**Comment by tobiasKaminsky** [comment]
After rethinking and partially programming it, I think these many snackbars are too much for the user.
So my new suggestion:
On zoom > 2x display a snackbar with "only resized image shown" and as action "change".
When clicking "change" it opens a (blocking) option selection box with
"What happens when zooming, ..."
- show only resized image (default)
- download full image
- immediately download full image (old behaviour)

After setting an option, snackbar "Behaviour can be changed in settings" is shown.

Same is shown if the first snackbar times out (after ~5s).
The first snackbar is shown in total two times, both with second snackbar after timeout. After that no snackbar is shown ever again.

@jancborchardt @AndyScherzinger @mario

**Comment by AndyScherzinger** [comment]
Sounds okay to me (no UX pro though), what about people who want to look at the pictures even on full resolution but still not download? I'd say we stop downloading and do just caching here and _if_ people want to download them then have to explicitly select one/more images in the file list and select download.

What do you think about that?

cc @eppfel

**Comment by tobiasKaminsky** [comment]
In your scenario the user would not have to do anything, as this is the default. The snackbar will vanish after the second time forever.
Manually downloading a specific file is always possible and the preview will be replaced seamless with the full version.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky I think not. If the user wants to preview the original images, then that is not one of the options you offer, at least not according to your list above?

**Comment by tobiasKaminsky** [comment]
This is/can be an independent feature and should, for simplicity reason of this PR, be in a separate issue.

**Comment by mario** [comment]
I think this should be the default behaviour though? Take a look at the full image, but don't download.

**Comment by AndyScherzinger** [comment]
> I think this should be the default behaviour though? Take a look at the full image, but don't download.

Me too, so it would then maybe be another topic and be something we change anyways (maybe for 1.5?). If you agree, can you open an issue for that?

**Comment by tobiasKaminsky** [comment]
Then we cannot trigger the option dialog on zooming, but instead showing a snackbar the first two times a new user is previewing an image. 
The snackbar displays "Full image is shown, but not saved" and a button "Change".

Clicking "change" shows these option dialog:
"Which image should be shown?"
- Full size, not saved (this will be checked as default)
- Full size, saved
- Screen adapted preview
- Preview, full size on zoom

Improvements of the wordings is more than welcome :)

**Comment by tobiasKaminsky** [comment]
> Take a look at the full image, but don't download.

Best is to put the image into cache, otherwise you would have to download it over again if you swipe between two pictures.
Also I will set the cache to 200Mb, but we have a better approach #596 here.

**Comment by eppfel** [comment]
I must admit I have a hard time following. Can we make a good decision on a default use case and then on other ones. And sometimes it is better not giving all possible options and stick with the relevant ones. 

I feel the debate download full size vs storing full size is a question of transfer volume vs storage space and I generally tend to go for saving data transfer.
Cache is a good solution and when someone zooms he wants detail, so the default has to be downloading (not storing) full-res.

Can we retrieve a file from cache, when we download (and save to storage)?

There should be not more than one snackbar to determine default behaviour.

**Comment by tobiasKaminsky** [comment]
@eppfel I think this is a good thing to discuss on meetup.

**Comment by jancborchardt** [comment]
Why even display a snackbar? When you zoom in on an image so it would get blurry, of course the full resolution version should be downloaded automatically. :) Ideally without any disruptions or loading spinners or reloads.

No need for any snackbars, or settings, or extra things. Or am I missing something?

**Comment by tobiasKaminsky** [comment]
@jancborchardt not again this one, please...
Many users do *not* want to have downloaded such a big file without explicit user interaction as they have a very limited data plan.

**Comment by jancborchardt** [comment]
Alright, so then this snackbar would only appear on mobile network use for sure, not on wifi.

But even then - if they previously said "no" to downloading the full size, then do zoom into a picture at a later date … they would need to go to the settings to reactivate it?

This is best just done on a case-by-case basis rather than a setting. And when someone zooms in a considerable amount to a pictureto the point of blurryness, we can pretty much be sure that they would rather like to see the better-resolution version.
Otherwise they also might think that Nextcloud compressed their files, or only shows them in lower quality.

**Comment by jancborchardt** [comment]
(And sorry @TobiasKaminsky :) maybe this is one best discussed in person at a hackweek.)

**Comment by tobiasKaminsky** [comment]
Yes, please postpone it to Hackweek as we already talked about blurry images and therefore discussed to limit the zoom on resized images to 2x to still have a good enough picture... ;-)

**Comment by tobiasKaminsky** [comment]
After leaving this thing some time alone, I think we want to achieve too many things on the same time and therefore the UI (and even talking about UI) is too complicated.

So this is (again) an idea to have far simpler:
Assumptions:
- users do not want to download the whole image, instead just like streaming have only a resized version
- if an user wants to have many images in original quality, he can synchronize the folder

This leads us to
- always show a resized version
- if an user zooms in (> 2x) a snackbar "download full image: yes" will be shown (on every time)
- (to have the old behaviour: add setting "click on image downloads full image" (as checkbox))

To remind us of the benefit of the resized version:
- you can share it to whatsapp, k9, facebook
- it is ~100kb vs 2-5 Mb
- resized images are stored in hard-coded 200Mb cache (see #596 for better cache sizing)

**Comment by jancborchardt** [comment]
Ok, let's go with that for now. :)

Just one thing: Instead of the setting, I would say that specific syncing (via the menu) should also download the full quality.

**Comment by tobiasKaminsky** [comment]
Syncing/Download menu entry will always download the full image.
The resized version will only be shown if you click directly on the image.

**Comment by jancborchardt** [comment]
Great, then we agree. :)

**Comment by tobiasKaminsky** [comment]
Closing this discussion as I integrated the result in #69
