### ISSUE TITLE
Remove horizontal divider lines in share list

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/android#7103]
The file list does not have horizontal lines which looks much better. We should remove them in the share list as well.

Share list with horizontal lines | File list without lines (how it should be)
-|-
![image](https://user-images.githubusercontent.com/5836855/96117472-6e43b800-0eea-11eb-9964-a73aee2223c5.png)|![image](https://user-images.githubusercontent.com/5836855/96117476-713ea880-0eea-11eb-894c-202414db9f9b.png)

**Comment by o3661606** [comment]
May I give it a try?

**Comment by AndyScherzinger** [comment]
@o3661606 yes, please! ❤️

**Comment by AndyScherzinger** [comment]
Fix provided by @o3661606 has been reviewed, tested and merged. Again thanks for contributing to Nextcloud ❤️
