### ISSUE TITLE
No push notifications from the Server

### ISSUE THREAD

**Issue by weinic** [nextcloud/android#7107]
Hello,

The Nextcloud app does not show any push notifications in the status bar of Andoid for the notifications that come from the server. 

Before, everything worked perfectly under Andoid 7 lineageOS. 

Now I have switched to a OnePlus (stock Andoid 10) and now there are comes no push notifications from the server.

To see the server notifications, I now always have to open the app.

**Comment by tobiasKaminsky** [comment]
Do you see any error when you navigate to "notification" screen?
As it worked previously, I highly doubt that it is a problem with server/app, but with your new device…

**Comment by weinic** [comment]
In the Notifications Screen of the NC App i dont see any Errors, only the regulary Notifications.

What I noticed is that the NC app only calls up the notifications when I manually go into the notification window. 
Push notifications about newly found media folders are displayed. 
So that means that these push messages generally work.  

Only the notifications from the server via (app updates, calendar, releases, NC update, etc.) do not arrive.
What I don't understand is why it should be on my new phone?

**Comment by tobiasKaminsky** [comment]
Notifications about new media folders are no push notifications, they are generated by the app.



> What I don't understand is why it should be on my new phone?

That is the big question…
Can you provide us additional infos via logcat during startup and when entering push? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

**Comment by weinic** [comment]
I wanted to run the line of code in Windows, but unfortunately it doesn't work that way. 
`adb logcat | grep "$(adb shell ps | awk '/com.nextcloud.client/{print $2}')" > logcatOutput.txt`
It's written for linux? 
What would the line of code for windows be?

**Comment by tobiasKaminsky** [comment]
Sorry, I have no clue about Windows :S

**Comment by weinic** [comment]
hello 
here is the output from the logcat

[logcatOutput.txt](https://github.com/nextcloud/android/files/5496625/logcatOutput.txt)

I hope this helps

**Comment by tobiasKaminsky** [comment]
I see that you have installed only the dev version, from where have you installed it?

**Comment by weinic** [comment]
No
I have installed both the Beta App from Playstore and the Dev version from F-Droid store.

The Dev version says "The Push Notifications are deactivated due to priority dependencies on Google Play services"
So I understand why it doesn't work here.

**Comment by tobiasKaminsky** [comment]
> I have installed both the Beta App from Playstore

Good :-)

Can you try it again and verify that logcat is about com.nextcloud.client and not "com.nextcloud.andoid.beta" (which is the dev version).

**Comment by weinic** [comment]
Hello,

new good information.
 
On January 5th you released a new NC version 3.14.2 RC1 in the Play Store. 
One of the new functions mentioned was "fix push notifications on some devices". 
Then I immediately installed the new update. 
Unfortunately it didn't work. 
But from experience with other apps I thought to myself, "OK then I'll uninstall the app and download it again" 
Then connected to the server ... And now, the push notifications are working again.  😃 
 
Now the only question is whether it will stay that way in the long term, or whether the Android system may interfere somewhere.
