### ISSUE TITLE
After setting up account using QR code, app ends up in broken state

### ISSUE THREAD

**Issue by Derkades** [nextcloud/android#7116]
### Steps to reproduce
1. Launch app for the first time
2. Log in using QR code

After logging in, I end up in this view: https://user-images.githubusercontent.com/15892014/96621248-b1e25b80-1308-11eb-861d-54789d8359e1.png

The hamburger menu does nothing. When I re-open the app I am at the standard file list and everything works fine.

### Can you reproduce this problem on https://try.nextcloud.com?
Did not try, server does not seem relevant. If you need me to try please let me know

### Environment data
Android version: 11

Device model: Pixel 3a

Stock or customized system: stock

Nextcloud app version: Nextcloud QA 16210

Nextcloud server version: 19.0.4

Reverse proxy: yes, nginx

#### Web server error log
```
N/A
```

#### Nextcloud log (data/nextcloud.log)
```
I was not able to find it
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky I can reproduce this with master too
