### ISSUE TITLE
Nightly: Fresh start

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#712]
- create a "source" branch which can be used for starting a fresh nightly
  - correct app namin
  - proper provider names
  - nightly link, check for new apks
- merge this in a new branch
- rename everything to nightly
- re-add all "ready for nightly" PRs
- make this as a script that it can be done, in theory, everyday.

**Comment by AndyScherzinger** [comment]
👍

**Comment by mario** [comment]
All good, except I'd wait with this until my branding branch is merged, then you'll be able to do this way easier :)

**Comment by AndyScherzinger** [comment]
Branding branch and most things have been merged that have a large impact on structure of the project. So when Tobias is back from vacation it might be a good time to start, as soon as #742 has also been merged since that one also has many changes.

**Comment by tobiasKaminsky** [comment]
#793

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger renaming it to "beta" is problematic as it then will confuse again with play store beta.
Is there something else we can use? "weekly" is also not true, if it is built more frequently...

**Comment by AndyScherzinger** [comment]
Alpha but that is theoretically also available in the play store but unused. We could use "unstable" which is kind of linux like or go for "development" or "test" which would show its testing nature. What I would try is to use a term that doesn't have a time constraint in its name.

**Comment by tobiasKaminsky** [comment]
Then I vote for developement, or shorter dev?
@mario your opinion?

**Comment by AndyScherzinger** [comment]
dev sounds good to me 👍

**Comment by tobiasKaminsky** [comment]
Done as described.
I hope fdroid will compile tomorrow.
