### ISSUE TITLE
For automated uploads, when Ethernet is connected, and Wi-Fi is required, "Waiting for free Wi-Fi" is displayed

### ISSUE THREAD

**Issue by PaulosV** [nextcloud/android#7129]
### Steps to reproduce
1. Set up some Automated uploads in Nextcloud Android app, and require Wi-Fi
2. Connect an Ethernet adapter over USB, and establish a connection
3. Have some content to upload

### Expected behaviour
- The upload progresses over the cable connection

### Actual behaviour
- There is a "Waiting for free Wi-Fi" sign (rough translation from Czech "Čekání na bezplatnou Wi-Fi").

![image-upload](https://user-images.githubusercontent.com/4086023/96996744-b1c4a480-1530-11eb-85bb-7bec49dc442f.png)

My Samsung disconnects the Wi-Fi as soon as the cable is connected.

I know that, technically, this behavior is correct - with anything but Wi-Fi, the upload refuses to progress further. But in my POV, Ethernet should be treated the same as Wi-Fi, if that is possible.

### Environment data
Android version: 10

Device model: SM-J610FN (Samsung Galaxy J6+)

Stock or customized system: Stock

Nextcloud app version: 3.13.1

Nextcloud server version: 19.0.4

**Comment by tobiasKaminsky** [comment]
https://github.com/nextcloud/android/pull/7164

There is an APK file in this PR, which you can install in parallel to your existing Nextcloud app.

**Comment by PaulosV** [comment]
I tested the APK in the PR and it is indeed fixed there! Thanks!
