### ISSUE TITLE
Playing video in android app stalls after n seconds, blocks entire system.

### ISSUE THREAD

**Issue by tilllt** [nextcloud/android#7133]
### Steps to reproduce
Open video from nextcloud server in nextcloud android app
Video plays for n seconds, then Android nextcloud app stalls, gets sluggy
Video doesn't play

### Expected behaviour
Video should play smoothly

### Actual behaviour
Video doesn't play or plays choppy, nc android app blocks entire system

### Can you reproduce this problem on https://try.nextcloud.com?
The demo doesn't show me the password to copy to the android client, so no, I cannot test it there.

### Environment data
Android version: 10

Device model: oneplus 5t

Stock or customized system: stock

Nextcloud app version: 3.13.1

Nextcloud server version: 19.0.4 (official docker image)

Reverse proxy: haproxy

### Logs
There are no problematic entries in either the Webserver or nextcloud logs. This is entirely an issue with the android client.

**Comment by tobiasKaminsky** [comment]
Do you stream, or have you downloaded the video?
