### ISSUE TITLE
Pixel 3XL Android 11 

### ISSUE THREAD

**Issue by Kusteri1** [nextcloud/android#7134]
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.substring(int, int)' on a null object reference
	at com.owncloud.android.datamodel.OCFile.getLocalId(OCFile.java:551)
	at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment.lambda$fetchAndSetData$5$FileDetailActivitiesFragment(FileDetailActivitiesFragment.java:339)
	at com.owncloud.android.ui.fragment.-$$Lambda$FileDetailActivitiesFragment$N7POe6TZvoGcuV2qP-niPxY_7t4.run(Unknown Source:12)
	at java.lang.Thread.run(Thread.java:923)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: google
Device: crosshatch
Model: Pixel 3 XL
Id: RP1A.201005.004
Product: crosshatch

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 6782484

**Comment by rubo77** [comment]
A Simulator Bug

### Steps to reproduce
1. Frech installiert Nextcloud in Samsung s7
2. Login wird Username and Password 
3. Press grant access

### Actual behaviour
- crash:

************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 
 'com.owncloud.android.lib.resources.status.CapabilityBooleanType com.owncloud.android.lib.resources.status.OCCapability.getRichDocuments()' on a null object reference
	at com.owncloud.android.ui.fragment.OCFileListBottomSheetDialog.onCreate(OCFileListBottomSheetDialog.java:128)
	at android.app.Dialog.dispatchOnCreate(Dialog.java:494)
	at android.app.Dialog.show(Dialog.java:342)
	at com.owncloud.android.ui.fragment.OCFileListFragment.lambda$registerFabListener$2$OCFileListFragment(OCFileListFragment.java:442)
	at com.owncloud.android.ui.fragment.-$$Lambda$OCFileListFragment$aYkoWPoxzAOahKL5AVjT06NhcnM.onClick(Unknown Source:4)
	at android.view.View.performClick(View.java:6897)
	at android.view.View$PerformClick.run(View.java:26104)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20201022
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: samsung
Device: herolte
Model: SM-G930F
Id: R16NW
Product: heroltexx

************ FIRMWARE ************
SDK: 26
Release: 8.0.0
Incremental: G930FXXU8ETF2

**Comment by tobiasKaminsky** [comment]
@Kusteri1 do you know which file this was? Do you have special mount folders?

@rubo77 This bug seems to be independent, please create a new issue.

**Comment by Kusteri1** [comment]
Hi Tobias

Thank you for you answer. The problem appears when I will open the folder “Alle Dateien”. Only folder “SofortUpload” will be displayed. If I then refresh display nothing happen but after a while a message will display in Android, application no respond wait/stop/help or smoothing like that.
Today I made Serverupdate to 20.01. Now the other folders will displayed and can be synchd but from time to time it crash. Try to send you next time crash to github again.

Kind regard

Markus



Von: Tobias Kaminsky [mailto:notifications@github.com]
Gesendet: Dienstag, 27. Oktober 2020 12:46
An: nextcloud/android <android@noreply.github.com>
Cc: github <github@betschwuck.ch>; Mention <mention@noreply.github.com>
Betreff: Re: [nextcloud/android] Pixel 3XL Android 11 (#7134)


@Kusteri1<https://github.com/Kusteri1> do you know which file this was? Do you have special mount folders?

@rubo77<https://github.com/rubo77> This bug seems to be independent, please create a new issue.

**Comment by jarvan11** [comment]
> @Kusteri1 do you know which file this was? Do you have special mount folders?
> 
> @rubo77 This bug seems to be independent, please create a new issue.

Reproduce the bug video link：
https://pan.baidu.com/s/1R8pmfaWCWycbWa-jpIAn9A 
Extraction code：6666

**Comment by jarvan11** [comment]
> @Kusteri1 do you know which file this was? Do you have special mount folders?
> 
> @rubo77 This bug seems to be independent, please create a new issue.

@tobiasKaminsky 
Reproduce the bug video link：
https://pan.baidu.com/s/1R8pmfaWCWycbWa-jpIAn9A 
Extraction code：6666

**Comment by jarvan11** [comment]
> ************ CAUSE OF ERROR ************
> 
> java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.substring(int, int)' on a null object reference
> at com.owncloud.android.datamodel.OCFile.getLocalId(OCFile.java:551)
> at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment.lambda$fetchAndSetData$5$FileDetailActivitiesFragment(FileDetailActivitiesFragment.java:339)
> at com.owncloud.android.ui.fragment.-$$Lambda$FileDetailActivitiesFragment$N7POe6TZvoGcuV2qP-niPxY_7t4.run(Unknown Source:12)
> at java.lang.Thread.run(Thread.java:923)
> 
> ************ APP INFORMATION ************
> ID: com.nextcloud.client
> Version: 30130190
> Build flavor: gplay
> 
> ************ DEVICE INFORMATION ************
> Brand: google
> Device: crosshatch
> Model: Pixel 3 XL
> Id: RP1A.201005.004
> Product: crosshatch
> 
> ************ FIRMWARE ************
> SDK: 30
> Release: 11
> Incremental: 6782484
@tobiasKaminsky 
Reproduce the bug video link：
https://pan.baidu.com/s/1R8pmfaWCWycbWa-jpIAn9A 
Extraction code：6666
