### ISSUE TITLE
Crash on click on white blank area of activities

### ISSUE THREAD

**Issue by goldengel** [nextcloud/android#7139]
### Steps to reproduce
1. Start app
2. Files
3. Where recent files should be listet it's blank
4. Klick on blank area
5. Crash of app
6. Forward es to this github page

Version server: 20
Version Android: client: newest 20201014

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.ClassCastException: com.owncloud.android.ui.preview.PreviewTextStringFragment cannot be cast to com.owncloud.android.ui.fragment.OCFileListFragment
	at com.owncloud.android.ui.activity.FileDisplayActivity.getListOfFilesFragment(FileDisplayActivity.java:624)
	at com.owncloud.android.ui.activity.FileDisplayActivity.showFiles(FileDisplayActivity.java:2321)
	at com.owncloud.android.ui.activity.DrawerActivity.onNavigationItemClicked(DrawerActivity.java:332)
	at com.owncloud.android.ui.activity.DrawerActivity.lambda$null$0$DrawerActivity(DrawerActivity.java:291)
	at com.owncloud.android.ui.activity.-$$Lambda$DrawerActivity$WuFXuKRKoNjsgnTzctIqSi-LJ_I.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7397)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20201014
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: Nokia
Device: B2N_sprout
Model: Nokia 7 plus
Id: QKQ1.190828.002
Product: Onyx_00WW

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 00WW_4_15H

```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Can you make a screenshot and show where you click?

**Comment by goldengel** [comment]
![Screenshot_20201027-140552~2](https://user-images.githubusercontent.com/1375893/97305707-c7520b00-185d-11eb-8027-243509beaab3.png)

**Comment by AndyScherzinger** [comment]
@goldengel this is the rich workspace area. Do you by any chance have a readme.md file in that folder (guess it is your root folder) and what is the content of that file? (my guess is it's is empty)

**Comment by goldengel** [comment]
Ok, yes. It was a empty readme.md file. Anyway, App should not crash on using click on that area.

**Comment by AndyScherzinger** [comment]
> Anyway, App should not crash on using click on that area.

Nope it shouldn't 👍 

Just wanted to check if the file was empty or had some invisible/control characters. That's been the reason for my question :)

**Comment by goldengel** [comment]
Yes. And it was the key question to get stuff solved. I did not recognize that file. Very good to know. Thank you!!!

**Comment by tobiasKaminsky** [comment]
Steps to reproduce:
- go into folder with readme.md
- click on it to open preview of rich workspace
- open drawer -> click on "all files"
