### ISSUE TITLE
Autoupload freezing & crashing + settings cannot be saved

### ISSUE THREAD

**Issue by mesili** [nextcloud/android#7141]
### Steps to reproduce
1. Open the app
2. Set auto upload active
3. While uploading, look at the app being irresponsive
4. Randomly get app crashes
5. Turn off wifi so you can use the app, try to change the auto upload settings. 

### Expected behaviour
- I was expecting the UI to be responsive even when background tasks are ongoing.
- I was expecting crashes to not occur so often 
- I was expecting the app to not freeze in random screens (loading spinner frozen, menu not opening, etc...) 
- I was expecting to be able to save my settings (folders, allow even when not on wifi, etc..)

### Actual behaviour
- The exact opposite : irresponsive app, freezing and crashing very often, unusable UI while uploads are ongoing. 
- I cannot save the settings : the save button stays in inactive state. 

### Additional infos 
- Files are being uploaded though. 
- I am able to repeat this behaviour on demand (if you want a video capture, let me know)
- There are ~3400 pictures and ~170 videos in the autou pload folders.

### Can you reproduce this problem on https://try.nextcloud.com?
- I will not upload my pictures to this server.

### Environment data
Android version: 10 (One UI 2.1, Kernel 4.9.118)

Device model: Samsung Note9 SM-N960N (5.9Gb RAM)

Stock or customized system: Stock

Nextcloud app version: 3.13.1 (2020-09-15)

Nextcloud server version: 20.0.0.9

Reverse proxy: nginx

#### Web server error log
```
Nothing particular.
```

#### Nextcloud log (data/nextcloud.log)
```
Nothing particular.
```

**Comment by tobiasKaminsky** [comment]
This will be fixed by #5679
