### ISSUE TITLE
AutoUpload does not work in version 1.4.1

### ISSUE THREAD

**Issue by steve-s-71** [nextcloud/android#715]
### Actual behaviour
Autoupload does not work anymore. It does not do anything if I shoot a photo... 

### Expected behaviour
Photo gets instantly autouploaded as configured
 
### Steps to reproduce
1. configure Autoupload
2. shoot a photo

### Environment data
Android version: 7.0

Device model: Galaxy S7

Stock or customized system:

Nextcloud app version: 1.4.1

Nextcloud server version: 11.0.2

**Comment by AndyScherzinger** [comment]
Hi @steve-s-71 this should be fixed with the latest release candidate 1.4.2 RC2 available now Google Play when registered as a tester, or waiting for the final to come around in about 2 weeks.

**Comment by steve-s-71** [comment]
Don't know how to register as tester and usually I avoid using RCs. In this case it would make sense for me. Can I dowload an apk file somewhere?

**Comment by steve-s-71** [comment]
I managed to subsribe as a tester. With 1.4.2 RC2 the issue is gone. Thanks!

It would be desireable to have a UI item which allows to select "Upload only via Wi-Fi" individually for Videos and Photos.

**Comment by AndyScherzinger** [comment]
You can register here https://play.google.com/apps/testing/com.nextcloud.client and simply unregister after we release the final and than you will be on the stable only release channel.

**Comment by AndyScherzinger** [comment]
For Photo vs Video we are still in discussion how to solve that nicely.

**Comment by AndyScherzinger** [comment]
Glad to hear 1.4.2 solved the issue for you. 

All credits go to @mario for pushing the auto upload fixes :tada:

**Comment by steve-s-71** [comment]
Thank you @AndyScherzinger and @mario 
Appreciate to hear Photo vs Video is in work/discussion.

**Comment by Bullnados** [comment]
For me 1.4.2 RC doesnt solve the problem.
LG G4 @ Stock
Reinstalling the app doesn't solve the problem

**Comment by mario** [comment]
@Bullnados closing as it works for you too :P

**Comment by chefboyct** [comment]
Well done to all developers on this!
