### ISSUE TITLE
[QA] List view

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/android#7157]
Steps:

1. Launch the application.
2. Set view to list.
3. Turn off the application.
4. Restart the application.

If there is an image file in the files and you are set to display the files as a list, the files will look like this:

![obraz](https://user-images.githubusercontent.com/47037905/97308572-4c8aef00-1861-11eb-88d4-6f5abec20483.png)

Only after another change to the list view, the file display is correct until the application is restarted.

### Environment data
Android version: 10

Nextcloud app version: #7098

Nextcloud server version: 20.0.1

**Comment by tobiasKaminsky** [comment]
Is this happening only in apk file of #7098 ?



> If there is an image file in the files and you are set to display the files as a list, the files will look like this:

What does this mean?
You have an image in the list, but on the screenshot I only see two folders?

**Comment by Valdnet** [comment]
> Is this happening only in apk file of #7098 ?

Yes, only with this version.

> You have an image in the list,

Yes. I have jpg and png files.

**Comment by tobiasKaminsky** [comment]
> Yes, only with this version.

Then it might be something odd with only this version…
We will today publish 3.14.0 RC1.
If this then still happens, please re-open.
