### ISSUE TITLE
Apk Android Nome utente o password errati

### ISSUE THREAD

**Issue by Umanoid1** [nextcloud/android#7165]
Impossibile accedere dall'app android nextcloud, ma dal veb si, ho dovuto ricreare un nuovo accaunt, e un bel bug, la vecchia versione prima di formattare il cell funzionava alla grande quindi non capisco che cosa non va, dall' app no accesso, dal web si accesso.

**Comment by tobiasKaminsky** [comment]
Plese translate to english and re-open.
