### ISSUE TITLE
Changing Auto-Upload folder kill the app

### ISSUE THREAD

**Issue by Bullnados** [nextcloud/android#717]
### Actual behaviour
App was killed after selecting new autoupload folder. My folder has the following specs
- 1 Subfolder /Pics/AutoUpload with 4,2GB all Pcis
- 6 pictures under /Pics/

Empty folder or folders with less files in it can be selected. But folder with round about 400Mb ebooks (50-100 files) also let crash the app

### Expected behaviour
No dead app
 
### Steps to reproduce
1. Auto-Upload
2. Menu--> Server folder
3.  Select a full folder

### Environment data
Android version: 6.0

Device model: LG G4

Stock or customized system: Stock

Nextcloud app version: 1.4.2 RC2

Nextcloud server version: 11.0.2

**Comment by mario** [comment]
Already looking - thanks! :)

**Comment by mario** [comment]
Fixed, will be in RC3 - thanks for reporting!

https://github.com/nextcloud/android/pull/718

**Comment by mario** [comment]
Can you try RC3 pls?

**Comment by Bullnados** [comment]
Will test that in 2 hrs :+1:

**Comment by mario** [comment]
Thanks!

**Comment by Bullnados** [comment]
Nope doesnt work with RC3. :cry: 
I do just an update over playstore and a reinstall

**Comment by mario** [comment]
Did you submit the crash? Did it ask you to do it?

**Comment by Bullnados** [comment]
Yes i submited the crash. I think three hours ago with RC2

**Comment by mario** [comment]
I saw that one, and it was related to search when selecting upload folder - that one is fixed for RC3.

**Comment by Bullnados** [comment]
I sent u again the crash reportcreated with RC3

**Comment by mario** [comment]
Got it now, thanks!

**Comment by tobiasKaminsky** [comment]
@mario what is the status with this one?

**Comment by mario** [comment]
@tobiasKaminsky I think it was fixed, but would need to check with a really big folder. Will assign to myself for testing.

**Comment by mario** [comment]
This should work now really.
