### ISSUE TITLE
Photo thumbnails don't save

### ISSUE THREAD

**Issue by axheli** [nextcloud/android#7182]
Is there a way to have the android app save the thumbnails. Once they load and your scrolling up and down the app they gray out and after come back. Is there a way to cache the thumbnails so once download they keep a cache on the phone so they're not always sending requests to the server? 

![image](https://user-images.githubusercontent.com/59488153/97718701-3fa21180-1a94-11eb-8da1-f0d24f95f7f4.png)

**Comment by Derkades** [comment]
Could it be this issue which was recently fixed for 3.14.0? #6196

**Comment by AndyScherzinger** [comment]
That would also be my guess. @axheli can you the thr beta available on gplay a try?

**Comment by axheli** [comment]
@AndyScherzinger I'm in 3.14.0 RC1 and having this issue. #6820 fixes this issue.

**Comment by axheli** [comment]
Sorry yes #6196 dose fix the issue 3.14.0 it's slot more smooth with #6820

**Comment by axheli** [comment]
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{50811eb u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2133)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:245)
	at android.app.ActivityThread.main(ActivityThread.java:7945)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140051
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus8Pro
Model: IN2025
Id: RP1A.201005.001
Product: OnePlus8Pro

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 2010031600

**Comment by Derkades** [comment]
When playing a video? #7185 #7187

**Comment by axheli** [comment]
> When playing a video? #7185 #7187

When viewing photos and app locked up and crashed

**Comment by AndyScherzinger** [comment]
Please don't mix issues within one report since that makes it a lot harder for the devs and designers to get an overview when reading though an issues timeline 🙂

**Comment by axheli** [comment]
Understood!

**Comment by tobiasKaminsky** [comment]
So, this seems to be fixed with 3.14.0
