### ISSUE TITLE
AutoUpload still does not work in version 1.4.2 RC2

### ISSUE THREAD

**Issue by Bullnados** [nextcloud/android#719]
FYI
Auto-Upload still doesnt work. #715 

- try to create new upload folder
- enable/disable Auto-Upload for specific folders
- change path of that folders
- reinstalling App

**Comment by mario** [comment]
What kind of "path" are you changing? remote path?

Can you screenshot your settings for the folder?

What Android version is that phone?

**Comment by Bullnados** [comment]
I changed the server path
6.0
LG G4 @stock 
![inkedcapture _2017-03-05-19-43-59_li](https://cloud.githubusercontent.com/assets/11041576/23590288/3127eda6-01dd-11e7-9da3-0444088a7527.jpg)
![inkedcapture _2017-03-05-19-42-41_li](https://cloud.githubusercontent.com/assets/11041576/23590289/3275525c-01dd-11e7-942f-13a31e7cb513.jpg)

**Comment by mario** [comment]
So what does the Uploads screen says when for example you take a picture? Nothing?

**Comment by Bullnados** [comment]
Okay new pictures seems to get uploaded.
Old pictures don't get uploaded. Wether i select an empty folder for autoupload

**Comment by mario** [comment]
That's normal. Only new pictures are supposed to get uploaded :)

**Comment by Bullnados** [comment]
Okay thanks for info. 
But would it no be better to sync all files if u choose an autoupload folder?
But i think therefore i create a new [Feature Request] cause i have some more wishes for autoupload. Perhaps i shall take that wishes to start java developing xD

**Comment by mario** [comment]
We have that planned already, but I invite you to open all the issues you can think of and we'll tell you if we already have that planned :)
