### ISSUE TITLE
PushNotification integration with Deck Android app will cause issues when targetSdk = 30 or higher

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/android#7194]
Similar to [this reported issue in the SSO library](https://github.com/nextcloud/Android-SingleSignOn/issues/277) i am pretty sure, that we will get an issue regarding the `PushNotification` integration with the [Deck Android app](https://github.com/stefan-niedermann/nextcloud-deck) as soon as the `targetSdk` in your [`build.gradle` file](https://github.com/nextcloud/android/blob/master/build.gradle#L129) will be raised to `30` or higher.

The Nextcloud Files app will then no longer be able to detect whether the Deck Android app is installed or not. As a solution one needs to extend the Nextcloud Files apps `AndroidManifest.xml` and add `<queries>` entries, but i am not entirely sure yet how this has to be done.

Resources:
- https://developer.android.com/about/versions/11/privacy/package-visibility
- https://developer.android.com/training/basics/intents/package-visibility

**Comment by tobiasKaminsky** [comment]
``` 
<manifest package="com.example.game">
    <queries>
        <package android:name="it.niedermann.nextcloud.deck" />
    </queries>
    ...
</manifest>
```

Might do it…

**Comment by stefan-niedermann** [comment]
**If** this works, we would need to add the package ids for the Play Store and the Dev versions, too. (They already are in the integration class, just copy & paste)

**Comment by stefan-niedermann** [comment]
side note: https://android-developers.googleblog.com/2020/11/new-android-app-bundle-and-target-api.html?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed:+blogspot/hsDu+(Android+Developers+Blog)&m=1

**Comment by tobiasKaminsky** [comment]
a bit unrelated, or does the "force" to app bundle (which is only for new apps) affects the query part or our SSO part?

**Comment by stefan-niedermann** [comment]
> From November 2021, updates to existing apps will be required to target API level 30 or above

Also updates of existing apps will need the new API level. So if you publish a new version in November 2021, this issue has to be solved or otherwise the Deck integration will be broken.

Basically this is our due date 😄

**Comment by AndyScherzinger** [comment]
> the "force" to app bundle (which is only for new apps) affects

Nov 2021 this is afaik also true for existing, updated ones. Which leads to another issue: upload bundle and signing happens on gplay side (so you will have to upload the key(s) for the apps...).
