### ISSUE TITLE
Sperrbildschirm nicht deaktivierbar mit 3.14.0RC1

### ISSUE THREAD

**Issue by Siggi0904** [nextcloud/android#7195]
Seit dem Update auf die 3.14.0RC erscheint nach einigen Aktionen (Ordnerwechsel, Datei löschen etc.)
der Sperrbildschirm zum "Muster bestätigen".

Das Eingeben des Fingerabdrucks oder des Musters kann ich aber unbegrenzt oft durchführen.
Die App wird nicht frei gegeben.

Erst ein "Beenden erzwingen" über die App-Verwaltung lässt mich wieder in die App.

Telefon: OnePlus 6
Version: Android 9 Oxygen OS 10.3.6
Nextcloud App: 3.14.0RC1

**Comment by Siggi0904** [comment]
Scheinbar konnte ich die Ursache weiter eingrenzen.
Ich musste einmal den App-Schutz deaktivieren und neu aktivieren.
Seit dem läuft es scheinbar.
Ich teste weiter....

**Comment by Siggi0904** [comment]
Tritt weiterhin auf.
Konnte aber den Fehler fangen:

https://github.com/nextcloud/android/issues/7257

**Comment by tobiasKaminsky** [comment]
Thanks for finding the real cause, I'll close this then now, as it only is a symptom…
