### ISSUE TITLE
3.14.0 RC1 can not upload anything (and is generally just broken)

### ISSUE THREAD

**Issue by uusijani** [nextcloud/android#7196]
### In short
Since updating the Android app to 3.14.0 RC1 (and server to 20.0.1 earlier), I can not upload anything with the app. Desktop client still syncs just fine.

### Steps to reproduce
Try to upload a file (either manually or by taking a photo for auto-upload)

### Expected behaviour
File should get uploaded

### Actual behaviour
There's a notification about "File upload conflict". Selecting the notification results in "[Error creating conflict dialog](https://github.com/nextcloud/android/issues/5755#issuecomment-695328151)". Going to uploads view and selecting "Resolve conflict" for a file just results in "Sync conflict, please resolve manually".

### Can you reproduce this problem on https://try.nextcloud.com?
Trying to add an account in the app [causes the app to crash](https://github.com/nextcloud/android/issues/7199).

### Environment data
Android version: 10
Device model: Samsung Galaxy A9 (2018)
Stock or customized system: stock
Nextcloud app version: 3.14.0 RC1 (from Beta channel)
Nextcloud server version: 20.0.1
Reverse proxy: no

#### Web server error log
Nothing NC-related

#### Nextcloud log (data/nextcloud.log)
Nothing related to the uploads, just

* [fread(): read of 8192 bytes failed with errno=21 Is a directory](https://github.com/nextcloud/server/issues/21578)
* [Undefined offset: 3](https://github.com/nextcloud/server/issues/23595)

**Comment by ProfessorVarox** [comment]
I'm experiencing the same error. I tried to remove my account in the app and login again but that didn't work

**Comment by uusijani** [comment]
Here's a [logcat snippet](https://github.com/nextcloud/android/files/5496265/nc-moto.log) from another device. The result of "Existence check" comes back as "Name collision", for any and all files.

**Comment by uusijani** [comment]
[With more verbose logging server-side](https://github.com/nextcloud/android/files/5496297/nc-Exception.log), there's a "`Deprecated event type`" followed by `"Exception":"Sabre\\DAV\\Exception\\NotFound"` for the file being uploaded. So it's perhaps correctly reporting that the file (about to be uploaded) does not exist (yet), but for some reason the app receiving this message flips it around, thinking the file _does_ exist, and thus reports a conflict.

**Comment by tobiasKaminsky** [comment]
Can you try RC2?

**Comment by uusijani** [comment]
@tobiasKaminsky Yup, tried it and the issue remains. Also found a device with 3.13.1, and it too is affected now, so this now seems more server-related, though it is weird that the desktop client hasn't been affected at any point. I would have assumed both clients employ the same webdav commands (and thus fail or succeed just the same).

Syncing a folder in Android app's "all files" view also still works (i.e. downloading changes causes no issues).

I have another server instance on another host, and there uploading from Android still works. This (working) instance is unencrypted, while the non-working instance has server-side encryption enabled.

**Comment by tobiasKaminsky** [comment]
@MorrisJobke do you have an idea if/how server e2e app could interfere here?

**Comment by MorrisJobke** [comment]
> @MorrisJobke do you have an idea if/how server e2e app could interfere here?

I haven't looked into the e2ee app yet. So I can't answer this for you right now.

**Comment by uusijani** [comment]
I went back in time using [F-droid's dev archive](https://apt.izzysoft.de/fdroid/index/apk/com.nextcloud.android.beta?repo=archive), testing all the way to around when 3.9.2 was released (2019-12-07), and the issue persisted, so this is indeed some weird interaction with the latest server version(s) and particularly the conflicts detection thereof.

Version 20191206 (2019-12-07) exhibited the issue a bit differently, though probably just due to how handling of conflicts on the client end has changed between then and now: one file that did go through got renamed with "(1)" added to it, even though there was no previously existing copy on the server. A previous attempt to upload the same file (using another client version) had failed, so that's one possible explanation for why the server thought that a previous copy did exist.

Another file got seeminly stuck in the (client upload) queue, and watching the server log revealed that it was incrementing the added number continuously, always coming up with the same "could not be located" exception from Sabre\\DAV as above. It had run up to 80 when I cancelled the upload from the client, and would have perhaps run indefinitely if I didn't.

    {"reqId":"SmCGdnw4BzFQ5P25wMGV","level":0,"time":"2020-11-20T17:40:54+02:00","remoteAddr":"REDACTED","user":"testituutti","app":"webdav","method":"HEAD","url":"/varasto/remote.php/webdav/Testidataa/DSC_0003%20(75).JPG","message":{"Exception":"Sabre\\DAV\\Exception\\NotFound","Message":"File with name Testidataa/DSC_0003 (75).JPG could not be located","Code":0,"Trace":[{"file":"REDACTED/www/varasto/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":81,"function":"getNodeForPath","class":"OCA\\DAV\\Connector\\Sabre\\ObjectTree","type":"->"},{"file":"REDACTED/www/varasto/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpGet","class":"Sabre\\DAV\\CorePlugin","type":"->"},{"file":"REDACTED/www/varasto/3rdparty/sabre/dav/lib/DAV/Server.php","line":474,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"REDACTED/www/varasto/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":262,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"REDACTED/www/varasto/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpHead","class":"Sabre\\DAV\\CorePlugin","type":"->"},{"file":"REDACTED/www/varasto/3rdparty/sabre/dav/lib/DAV/Server.php","line":474,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"REDACTED/www/varasto/3rdparty/sabre/dav/lib/DAV/Server.php","line":251,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"REDACTED/www/varasto/3rdparty/sabre/dav/lib/DAV/Server.php","line":319,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"REDACTED/www/varasto/apps/dav/appinfo/v1/webdav.php","line":84,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"REDACTED/www/varasto/remote.php","line":167,"args":["REDACTED/www/varasto/apps/dav/appinfo/v1/webdav.php"],"function":"require_once"}],"File":"REDACTED/www/varasto/apps/dav/lib/Connector/Sabre/ObjectTree.php","Line":173,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Android) Nextcloud-android/20191207","version":"20.0.1.1"}
    {"reqId":"M3RTK4KRuOH3N0xGrp2Q","level":0,"time":"2020-11-20T17:41:00+02:00","remoteAddr":"REDACTED","user":"testituutti","app":"webdav","method":"HEAD","url":"/varasto/remote.php/webdav/Testidataa/DSC_0003%20(76).JPG","message":{"Exception":"Sabre\\DAV\\Exception\\NotFound","Message":"File with name Testidataa/DSC_0003 (76).JPG could not be located","Code":0,"Trace":[{"file":"REDACTED/www/varasto/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":81,"function":"getNodeForPath","class":"OCA\\DAV\\Connector\\Sabre\\ObjectTree","type":"->"},{"file":"REDACTED/www/varasto/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpGet","class":"Sabre\\DAV\\CorePlugin","type":"->"},{"file":"REDACTED/www/varasto/3rdparty/sabre/dav/lib/DAV/Server.php","line":474,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"REDACTED/www/varasto/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":262,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"REDACTED/www/varasto/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpHead","class":"Sabre\\DAV\\CorePlugin","type":"->"},{"file":"REDACTED/www/varasto/3rdparty/sabre/dav/lib/DAV/Server.php","line":474,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"REDACTED/www/varasto/3rdparty/sabre/dav/lib/DAV/Server.php","line":251,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"REDACTED/www/varasto/3rdparty/sabre/dav/lib/DAV/Server.php","line":319,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"REDACTED/www/varasto/apps/dav/appinfo/v1/webdav.php","line":84,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"REDACTED/www/varasto/remote.php","line":167,"args":["REDACTED/www/varasto/apps/dav/appinfo/v1/webdav.php"],"function":"require_once"}],"File":"REDACTED/www/varasto/apps/dav/lib/Connector/Sabre/ObjectTree.php","Line":173,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Android) Nextcloud-android/20191207","version":"20.0.1.1"}
