### ISSUE TITLE
Aktivitäten laden nicht bei ausgelöstem Brute-Force-Schutz 

### ISSUE THREAD

**Issue by weinic** [nextcloud/android#7198]
Hallo zusammen,

ich habe gerade festgestellt, dass bei ausgelöstem Brute-Force-Schutz die Aktivitäten Liste in der Nextcloud App nicht mehr laden und mit dem Fehler `Operation finished with HTTP status code -1 (fail) ` beendet wird.

**Comment by AndyScherzinger** [comment]
Hi @weinic,

Wenn brute force ausgelöst wurde blockiert uns der Server generell. Da können wir nicht gegen machen. 

Cc @tobiasKaminsky

**Comment by weinic** [comment]
Das verstehe ich jetzt nicht...
Wenn der Server generell blockiert, müsste ja alles in der App verzögert funktionieren.
Aber das laden der Ordner und Dateien funktioniert einwandfrei.
Die App ist ja bereits angemeldet...

Bei einem bereits in der Weboberfläche angemeldeten Benutzer greift brute force auch nicht mehr.

**Comment by AndyScherzinger** [comment]
> Aber das laden der Ordner und Dateien funktioniert einwandfrei.

Im Sinne von neu-laden und aktualisieren? Denn bestehende Informationen sind client-seitig gechached

**Comment by weinic** [comment]
Also ich habe jetzt nochmal einige Sachen getestet.
Zuerst habe ich mich über die Weboberfläche absichtlich so lange falsch angemeldet bis der Brute force Schutz ausgelöst hat.

Danach habe ich den Cache der Nextcloud App gelöscht.
Als nächstes habe habe ich dann immer abwechselnd die verschiedenen Kategorien der App ( Dateien, Favoriten, Fotos, Geteilt und Benachrichtigungen ) und Aktivitäten geöffnet.
Es hat alles funktioniert/geladen, bis auf Aktivitäten bei der der besagte Fehler ausgegeben wird.
Um auch jeglichen Cache aus zu schließen, habe ich auch noch eine Datei erstellt. Diese wurde auch sofort und ohne jegliche Verzögerung erstellt und war auch sofort über den Webbrowser abrufbar.

Beim Zugriff über die App funktioniert also alles ganz normal, bis auf die Anzeige der Aktivitäten, auch wenn der Brute force Schutz ausgelöst hat.

**Comment by AndyScherzinger** [comment]
In den Einstellungen ist ggf ein Eintrag für Logs, dort könnte ggf ein Fehlereintrag vorliegen, der mehr Details enthält.
Sofern alles gut ist und brute force protection nicht zuschlägt, lädt dann der activity feed oder auch nicht?
Nur um das Thema weiter einzugrenzen.

**Comment by tobiasKaminsky** [comment]
@nickvergessen as you maintain activity, is there a possibility that bruteforce delays the request?
We are using this "/ocs/v2.php/apps/activity/api/v2/activity" with either "/filter" and fileId or with "since" as parameter.
An we authenticate via "Authorization" request header.

**Comment by weinic** [comment]
Hier die Log Einträge.
Diese habe ich vorher nochmal gelösch, weil es extrem viele waren.
Dann habe ich danach nochmals die Aktivitäten aufgerufen.
[logs.txt](https://github.com/nextcloud/android/files/5480839/logs.txt)

Wenn der Brute force Schutz nicht ausgelöst hat, dann funktioniert das laden der der Aktivitäten ganz normal.

**Comment by nickvergessen** [comment]
well activity has no bruteforce itself. but authentication of course has.

**Comment by tobiasKaminsky** [comment]
No real idea.
I tried it on my test server, but as soon as one successful operation was done on server brute force immediately was removed…
