### ISSUE TITLE
Autoupload: only upload when charging keeps uploading after unplugging

### ISSUE THREAD

**Issue by AllirionX** [nextcloud/android#7206]
### Steps to reproduce
1. Set up a  non-empty autoupload folder /storage/emulated/0/DCIM/Camera to upload files to the /Pictures folder with "only upload when charging" and "also upload existing files" on.
2. Plug the phone in.
3. Nextcloud starts uploading the existing files
4. Unplug the phone

### Expected behaviour
- The files upload should stop

### Actual behaviour
- The files upload continues.
- If updating the autoupload folder to upload to another folder, the old folder keeps being used.

### Environment data
Android version: 9

Device model: Redmi Note 7

Stock or customized system: LineageOs 16.0-20190626-UNOFFICIAL-lavender

Nextcloud app version: 3.13.1

Nextcloud server version: 19.0.4 (nextcloudpi)

Reverse proxy: nginx

**Comment by tobiasKaminsky** [comment]
True, we just check it before starting entire queue and not for each and every job then.

**Comment by tobiasKaminsky** [comment]
@AllirionX from code it should stop after the current upload finishes.
Is this correct?
If so, I think it is ok to keep it that way, as otherwise we might loose the uploaded parts so far (if no chunked upload is in place).

**Comment by AllirionX** [comment]
@tobiasKaminsky Indeed, the upload queue stops after the current upload finishes. I don't feel like that was the case when I submitted the bug report, but it's good like this for me.
