### ISSUE TITLE
[Feature Request] Enable debug logging in beta/nightlies

### ISSUE THREAD

**Issue by Bullnados** [nextcloud/android#721]
At the moment u can just send a crash report. Would be nice if u can see that reports also. F.e create a new menu point in the settings for enabling(reading and coping logs in smartphone)/disabling(normal sending as it is) logging

**Comment by AndyScherzinger** [comment]
It is available in the nightly, just go to settings - > logs 

They are always active on the nightly ;)

**Comment by Bullnados** [comment]
Nightly is to hot for me. So can u enable it in beta too?

**Comment by AndyScherzinger** [comment]
in the release candidates we could, yes. Even though this will need some work, to cleanup when a final/stable release is installed. Other possibility would be to generally offer the possibility to activate logging via the settings screen.

What do you think @mario @tobiasKaminsky ?

**Comment by tobiasKaminsky** [comment]
If we want having it enabled on RC only, and disabling it on stable, it must be possible with build params, otherwise it is too much work.
I remember that we discussed this once upon a time. The opinions varied from "not needed" to "hide it in dev mode" to "always show it".
The regular user should not need it, so I would "hide" it or just put it somewhere real deep ;-)

**Comment by Bullnados** [comment]
Perhaps tipping at app version same Google is doing for developer console? If this is to complexe close that issue, was just an idea.

**Comment by mario** [comment]
We can enable it for nightlies and RCs quite easily once my branding PR is ready.

@tobiasKaminsky is nightly a "Debug" or a "Release" build?

**Comment by AndyScherzinger** [comment]
Well, we would still have to implement some kind of cleanup once a stable release gets installed, so the log file gets removed during stable updates. This way we do not hold such data on the phones of our users.

**Comment by tobiasKaminsky** [comment]
nightly is a regular release.
@AndyScherzinger good point. But if a crash can be reproduced an user should always start with an empty log, so this is maybe not a big problem if we just use the same log (as we have timestamps in it)

So I vote for:
- logs enabled for nightly (done)
- logs enabled for RC (@mario with branding branch)
- logs disabled for stable

**Comment by AndyScherzinger** [comment]
👍 from me :)

**Comment by tobiasKaminsky** [comment]
This is already implemented
