### ISSUE TITLE
No idea, login...

### ISSUE THREAD

**Issue by vdarkobar** [nextcloud/android#7214]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
@vdarkobar just from the subject line... No idea what you mean 😐 can you elaborate a bit more? Does it crash? Could you post the error? Else?

**Comment by vdarkobar** [comment]
Hi, I've tried to login to the android app and after adding user name and password, also to code it happened...
I closed the app and after that it works as it should.
Hope it helps,
Bye

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky I am bit out of ideas, maybe you have any idea?
