### ISSUE TITLE
app ANR after upload over 1500 number of picture

### ISSUE THREAD

**Issue by willpyshan13** [nextcloud/android#7218]
### Steps to reproduce
 if the number of photos is large (over 1500 number ), crash will appear after setting the auto upload mobile phone album

### Expected behaviour
- T if the number of photos is large (over 1500 number ), crash will appear after setting the auto upload mobile phone album

### Actual behaviour
-  if the number of photos is large (over 1500 number ), crash will appear after setting the auto upload mobile phone album

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:
andriod 9.0
Device model: 
huawei honor p20
Stock or customized system:

Nextcloud app version:
3.13.1
Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Hm, I thought this is fixed…

Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

**Comment by willpyshan13** [comment]
i don't have log.so i close it.thanks
