### ISSUE TITLE
Bump Jackrabbit to the latest 2.14 release

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#722]
At the moment we are using 2.12.x which is still using http client 3.1 while the new release 2.14 bumped the version to 4.1, see http://jackrabbit.510166.n4.nabble.com/ANNOUNCE-Apache-Jackrabbit-2-14-0-released-td4666058.html

> The main changes in this release are:
> - Switch WebDAV client components to HttpClient 4.5.x (summary in JCR-2406)
> - Introduction of Commons-VFS Datastore implementation (JCR-3975)
> - Allow use of JDK7 features (JCR-4030) 

cc @mario @tobiasKaminsky

**Comment by mario** [comment]
Isn't this more about the library?

**Comment by AndyScherzinger** [comment]
Right, moved... https://github.com/nextcloud/android-library/issues/48
