### ISSUE TITLE
Update F-Droid Donate link

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#7233]
Currently https://f-droid.org/en/packages/com.nextcloud.client/ still links to bountysource while it should point to https://nextcloud.com/include/

@tobiasKaminsky do you know where to change this?

**Comment by tobiasKaminsky** [comment]
Merge request to https://gitlab.com/fdroid/fdroiddata/

**Comment by AndyScherzinger** [comment]
Openede a merge request: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7693

**Comment by tobiasKaminsky** [comment]
And already merged :-)

**Comment by AndyScherzinger** [comment]
Uuuh, nice
