### ISSUE TITLE
Can't share files deftly to other apps

### ISSUE THREAD

**Issue by pomkos** [nextcloud/android#724]
### Actual behaviour
-Apps can't open files if prompted to do so from within Nextcloud app. I need to manually download the file, then browse to it from a file explorer app, and then use that to open the file with another app.

### Expected behaviour
-When I tap "open with" in Nextcloud and select Word, for example, Word should be able to open the document. Currently it just opens word or gives the error "download file first" despite making the file available offline. Sharing to Solid Explorer should allow me to save the file to another directory, right now nothing happens.
 
### Steps to reproduce
1. Tap "Open with" after downloading a document
2. Select any word processor or printer app
3. Attempt to view the document. Apps will either just open or automatically close.

### Environment data
Android version: 7.1.1

Device model: Moto X Pure 2015

Stock or customized system: Mokee (cyanogen mod based)

Nextcloud app version: 1.4.2RC4

Nextcloud server version: 10.0.1

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
I can't find any log files, the one I found did not log anything beyond Jan 16th.

**Comment by Bullnados** [comment]
FYI
For me all is working normaly

Android version: 6.0
Device model: LG G4
Nextcloud app version: 1.4.2RC4
Nextcloud server version: 11.0.2

**Comment by pomkos** [comment]
I wonder if it's a Nougat thing. Have there been other reports of this issue?

**Comment by AndyScherzinger** [comment]
No, it worked on my Nexus5X and works on my OnePlus3T just fine.

**Comment by Bullnados** [comment]
Checked also on my Nexus 10 with OmniRom 7.1.1 and a PDF file with acrobat reader

**Comment by pomkos** [comment]
Well, looks like it was my fault. I uninstalled and reinstalled from the play store, works like a peach on 7.1.1. 99% sure the app doesn't work well with titanium, no amount of fresh ROM installs made it work if I restored from titanium but a play store install worked wonders every time.

**Comment by krbvroc1** [comment]
Same problem here. Acrobat launches but doesn't load PDF I clicked on. Using Nougat and new Nextcloud install.
