### ISSUE TITLE
I can't use this app under mobile network

### ISSUE THREAD

**Issue by yuanshengdv** [nextcloud/android#7243]
I found that I couldn't use this app on the mobile network，but I try to use it with WiFi or VPN connection，It has no problem.
So I think this problem is related to DNS settings（In general,we can't set the DNS settings of mobile network by ourselves）.
Can you fix this problem? thanks

**Comment by yuanshengdv** [comment]
I am in China, so I can't connect to DNS servers abroad.

**Comment by yuanshengdv** [comment]
I am in China, so I can't connect to DNS servers abroad.

**Comment by yuanshengdv** [comment]
> 我发现我无法在移动网络上使用此应用程序，但是我尝试通过WiFi或VPN连接使用它，这没有问题。
> 因此，我认为此问题与DNS设置有关（通常，我们无法自行设置移动网络的DNS设置）。
> 你能解决这个问题吗？谢谢

**Comment by AndyScherzinger** [comment]
@yuanshengdv maybe try to just use the server's IP address than you wouldn't need DNS. This would of course only work in case your server is reachable via "the internet" (as in via the part of the internet reachable via your Cellular Network provider.

**Comment by AndyScherzinger** [comment]
_If_ the server isn't reachable at all via your cellular network/provider than there is absolutely nothing than can be done :/

**Comment by yuanshengdv** [comment]
> _If_ the server isn't reachable at all via your cellular network/provider than there is absolutely nothing than can be done :/

Thank you, but my server does not use fixed IP, I use dynamic DNS resolution, so it is not convenient for me to use IP address to connect directly.

**Comment by AndyScherzinger** [comment]
We rely on Android's network connections handling so there is no option to manually configure DNS :/

**Comment by yuanshengdv** [comment]
> We rely on Android's network connections handling so there is no option to manually configure DNS :/

Thank you. Maybe there is something wrong with other places, because I can access my server through the browser， I will try to solve it myself.

**Comment by tobiasKaminsky** [comment]
Is this v4 or v6?

**Comment by yuanshengdv** [comment]
Both are enabled，I used httpcanary as a proxy and found that the app worked normally. I don't know why, but I think it should be related to the security settings of the mobile phon.

**Comment by yuanshengdv** [comment]
> Is this v4 or v6?

Both are enabled，I used httpcanary as a proxy and found that the app worked normally. I don't know why, but I think it should be related to the security settings of the mobile phon.

**Comment by tobiasKaminsky** [comment]
Great to hear!
