### ISSUE TITLE
Nextcloud auto upload problem

### ISSUE THREAD

**Issue by janarzz** [nextcloud/android#7244]
Hi,
Nextcloud android app auto upload not working.
I use Samsung S20 and  latest android.
Nextcloud latest version app.

**Comment by laama1** [comment]
Same here. Logcat tells me that I have "Socket timeout" when "Existence check for https://nextcloud.kissala/remote.php/webdav/GSP/filename.gpx targeting for existence: socket timeout exception"

**Comment by tobiasKaminsky** [comment]
Socket timeout just means that there connection is killed due to timeout.
It then should retry…

Have you disabled Samsungs battery protection for this app?

**Comment by janarzz** [comment]
Yes, but still not work.

**Comment by tobiasKaminsky** [comment]
But browsing files, manual up/download is working?

**Comment by janarzz** [comment]
Hi, 
manual upload works great :)

**Comment by tobiasKaminsky** [comment]
@janarzz 
Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

**Comment by Kuemmelklaus** [comment]
Same issue here on my Huawei p20 lite.
manual uploads and downloads work just fine.
But it simply won't upload anything automatically and doesn't give me an error.
But every time I set up a folder it alerts that I may have to ignore the app in power saver options (I only have the German exact wording) even though I already did that.

**Comment by janarzz** [comment]
Everybody knows ? When this bug fixed ?
