### ISSUE TITLE
Access to custom WebDAV server

### ISSUE THREAD

**Issue by bohwaz** [nextcloud/android#7258]
I've read in the doc that the NextCloud Android client can give access to a raw WebDAV server, but it doesn't seem to work with my server.

The message given by the app is just "server not found". On the server side it seems that it is looking for status.php and then remote.php files.

Is its supposed to work or maybe I was mistaken? Is there anything to do on the server to support the NextCloud client?

**Comment by tobiasKaminsky** [comment]
The server can access a raw webdav server as external storage, but not the client.
Our clients are only designed to work with a valid NC server.
