### ISSUE TITLE
Auto upload still not working on WiFi with VPN

### ISSUE THREAD

**Issue by heinhuiz** [nextcloud/android#7259]
Please refer to #6449 and #7017, which have been closed but still exist in RC 3.14.0 RC1.

This is a very annoying bug for me, since I cannot use the 'Only upload over unmetered Wi-Fi option' because I am bound to use a VPN. Am stuck in using version 3.13.0 since.

**Comment by tobiasKaminsky** [comment]
There was a similar bug with blockada 5, where they falsely marked VPN connection as "metered".
Is your http://cloud.com/indexd.php/204 reachable?

**Comment by heinhuiz** [comment]
I don't think I even have that file. My Nextcloud is running on a NAS.
The same bug existed in FairEmail, let me ask the developer how he solved it. In the end it was a simple solution. I will get back to you.

**Comment by heinhuiz** [comment]
Marcel quickly replied, it was not simple at all. He referred me to https://github.com/M66B/FairEmail/blob/master/app/src/main/java/eu/faircode/email/ConnectionHelper.java#L212 for his solution.

**Comment by tobiasKaminsky** [comment]
> I don't think I even have that file.

This is an endpoint that every NC server >14 has.

**Comment by tobiasKaminsky** [comment]
> He referred me to https://github.com/M66B/FairEmail/blob/master/app/src/main/java/eu/faircode/email/ConnectionHelper.java#L212 for his solution.

Nice, this indeed could help, but do you know which part was changed to support the VPN?

**Comment by heinhuiz** [comment]
> > I don't think I even have that file.
> 
> This is an endpoint that every NC server >14 has.

On my system that is .../index.php/204/ without a d and that is (always) reachable indeed.

**Comment by heinhuiz** [comment]
> > He referred me to https://github.com/M66B/FairEmail/blob/master/app/src/main/java/eu/faircode/email/ConnectionHelper.java#L212 for his solution.
> 
> Nice, this indeed could help, but do you know which part was changed to support the VPN?

It's been long since I've been programming, but it seems to me by reading the code that it is pretty straightforward.

He first tries one by one to value all possible connections 

- no connection manager (212)
- no network (219)
- no connection (233)
- etc.

on restrictions, until at line 273 only VPN connections are left, where he tries to establish the network under the VPN: cellular or WiFi.

In the following code from line 280 onwards the status isMetered for all connection types is set, with the underlying VPN networks at line 307 onwards. 

Please note the VPN via USB exception at line 326.

**Comment by tobiasKaminsky** [comment]
> without a d

That was a typo, sorry :-/

**Comment by tobiasKaminsky** [comment]
> Please note the VPN via USB exception at line 326 and all other workarounds in the code.

That is what makes it tricky…  ;-)

Which VPN do you use? So I can try to use that when implementing it…

**Comment by heinhuiz** [comment]
> > Which VPN do you use? So I can try to use that when implementing it…

I'm using NordVPN.

**Comment by tobiasKaminsky** [comment]
If anyone can recommend a free (even only for a short period) vpn where it happens, so I can reproduce it…

**Comment by heinhuiz** [comment]
I have just tested https://protonvpn.com/
They has a free plan with one connection, which gives me the same problem.

**Comment by tobiasKaminsky** [comment]
There is an APK file in PR #7488, which you can install in parallel to your existing Nextcloud app.
It would be great if you can verify the fix.

**Comment by heinhuiz** [comment]
I've tested 4 conditions:

1. WiFi on, VPN on
2. WiFi on, VPN off
3. WiFi off, VPN on
4. WiFi off, VPN off
with, obviously, in cases 3. and 4. mobile data on.

Now case 1. and 2. are correctly identified as unmetered, allowing auto upload. In case 3. and 4. the upload is blocked, which is also correct.

Seems like you have cracked the code 😁
