### ISSUE TITLE
No sorting of files and view settings

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/android#7266]
### Steps to reproduce

1. Launch the app.
2. Select "Media" from the menu.
3. Return to "All Files".

### Expected behaviour
Display file sorting and view settings for "All Files".

![obraz](https://user-images.githubusercontent.com/47037905/98530942-e69a6080-227f-11eb-97f1-85acd4885432.png)

### Actual behaviour
After entering "Media" and returning to "All files" file sorting and view settings are not displayed.

![obraz](https://user-images.githubusercontent.com/47037905/98531063-15b0d200-2280-11eb-96ba-6202d301ad7e.png)

It also lacks sorting and file display settings for "Media". Is it intentional?

![obraz](https://user-images.githubusercontent.com/47037905/98531622-e353a480-2280-11eb-82be-63a7460f9ed7.png)

### Environment data
Android version: 10

Nextcloud app version: 3.14.0 RC1 and Dev 20201108

**Comment by tobiasKaminsky** [comment]
> After entering "Media" and returning to "All files" file sorting and view settings are not displayed.

That is a bug, thanks for finding it!



> It also lacks sorting and file display settings for "Media". Is it intentional?

Yes. As media is always displayed "newest to old".
