### ISSUE TITLE
Default action for resolving file conflict while uploading files

### ISSUE THREAD

**Issue by deepsidhu1313** [nextcloud/android#7273]
### Is your feature request related to a problem? Please describe.
I have set my phone app to backup files from my phone to nextcloud server. Few months ago app stopped overwriting already existing files. Instead prompt for each file which version to keep. It is very annoying when you have 1000's of files you want to keep in sync. Is there a way to provide option to choose default action in this kind of from settings screen. 

### Describe the solution you'd like
Option to choose default action from actions like overwrite existing file, create new file with trailing _NNN where N is real number, don't upload the file, prompt for action. Apart from this if this setting can be directory specific that will be awesome.

### Describe alternatives you've considered
1. Ignoring the prompt. 
2. Spending time on weekend to sync all files by clicking one by one.
3. Using usb to copy files to computer.(legacy)

### Additional context
I am really thankful to the developers working on nextcloud server and apps and giving people a privacy oriented option instead cloud like G suite and MS cloud. Thanks for your hardwork.

**Comment by tobiasKaminsky** [comment]
Auto upload has such an option, if it does not work as expected, please write down a detailed sample and include which file is changed where and when…

**Comment by PVince81** [comment]
For regular manual uploads I didn't find such option.
A few days ago I tried to upload a bunch of pics, knowing that some already existed but some were missing in the target folder, and got flooded by a series of conflict prompts, one by one. An option to say "use this approach for now" would be nice.

Or alternatively, before I start the upload, let me pick an option "upload and overwrite" along with the existing dropdown there.
