### ISSUE TITLE
Empty items in dir list or grid view.

### ISSUE THREAD

**Issue by deepsidhu1313** [nextcloud/android#7274]
### Steps to reproduce
1. Few months ago i refreshed my list view within app and some empty items got created at the top of the list. Three rows are empty in both list and grid view. You can click on these and they open empty directory.

### Expected behaviour
- list and grid view should only show existing files and dirs. 

### Actual behaviour
- 3 rows at the top of grid view and list view are empty.

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 10

Device model: essential ph-1

Stock or customized system: stock

Nextcloud app version:3.13.1

Nextcloud server version: 20

Reverse proxy: yes

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
@deepsidhu1313 what you actually see is the so called rich workspace which is displaying the content of the Readme.md file within that folder. Simply delete that file and the empty space will be gone or add content to the readme file and it will be displayed.
