### ISSUE TITLE
Excessive battery usage on Android 8

### ISSUE THREAD

**Issue by tomwimmenhove** [nextcloud/android#7286]
### Steps to reproduce
1. Install Nextcloud on Android 8.0 (Samsung Galaxy S7)
2. Put phone away
3. Wait 2 hours
4. Battery is at 50%

### Expected behaviour
Not to use excessive battery when phone is not being used.

### Actual behaviour
With the phone inactive, the NextCloud service uses up about 50% of battery in two hours

### Environment data
Android version:
8.0.0

Device model: 
Samsung Galaxy S7

Stock or customized system:
Stock, with syncing and auto-upload enabled.

Nextcloud app version:
3.13.1

Nextcloud server version:
19.0.4

Reverse proxy:
No

**Comment by tobiasKaminsky** [comment]
Can you give us some info, if / how many auto upload you have configured?
Do you see any upload/download notification?
Can you show us the detailed battery report for this app?
