### ISSUE TITLE
Nextcloud beta 20170223: app crashes when open settings

### ISSUE THREAD

**Issue by mr-manuel** [nextcloud/android#729]
### Actual behaviour
- The App crashes when I open the settings in Nextcloud app.

### Expected behaviour
- It should open whitout crash
 
### Steps to reproduce
1. Set the storage path to SD card on Android 7
2. Open settings in Nextcloud

### Environment data
Android version: 7.0

Device model: Samsung Galaxy S7 Edge

Stock or customized system: Stock

Nextcloud app version: 20170223

Nextcloud server version: 11.0.2

#### Nextcloud log (data/nextcloud.log)
```
unfortunately there is no log file :/
```

**Comment by Bullnados** [comment]
Same problm?
#717

**Comment by mr-manuel** [comment]
No, unfortunately not. I can browse all folders with lot of images, big files and so on. The app crashes only when I want to open the settings.

**Comment by Bullnados** [comment]
Can u download 1.4.2 RC4? I think ist newer than 20170223 cause fdroid is broken atm

**Comment by mr-manuel** [comment]
With the latest version from the readme.md file (https://download.nextcloud.com/android/nightly/latest.apk) it works perfectly again.

Thank you :)

**Comment by MagnumGR** [comment]
I have the same problem (crash when i open settings) with my SONY Xperia Z (Android 5.1.1) with all nextcloud beta - nightly versions for over a month now.  
With the the latest 1.4.2 RC4 and all previous version from Google Play there is no problem with it

**Comment by AndyScherzinger** [comment]
@MagnumGR do you have the change to provide a logcat (just asking, would probably mean you would have access to Android Studio)

**Comment by MagnumGR** [comment]
I do not have access to settings -> Create Logfile (if i remember correctly).
I have try to locate any *.log to nextcloud folders without success.

If there is a way to provide any useful information (log, etc) please give me detailed instruction for this.

**Comment by mr-manuel** [comment]
Now the problem is also for me back... app continues to crashing when I open the settings. I have the latest version installed today.
@MagnumGR have you maybe changed the storage to the external SD card?

**Comment by MagnumGR** [comment]
@mr-manuel  This happen only with the beta/nightly version about 2 months now with my SONY Xperia Z (5.1.1).  As already told there is no problem with the 1.4.2. 
I have try to delete and reinstall both versions with the same results !
As i can't access the settings for more of 2 months, it's possible that i had changed the storage to external SD card.

**Comment by tobiasKaminsky** [comment]
@mr-manuel @MagnumGR can you both try to uninstall the nightly version and then re-install it?
The error was fixed a long time ago...

**Comment by MagnumGR** [comment]
@tobiasKaminsky  Uninstalled and re-install the latest nightly version with the same result !
https://postimg.org/image/j8yrr97rn/  
"Application Nextcloud nightly has been stopped"

**Comment by octo777** [comment]
Coolest thing happened today, Mario  saw me complaining about this bug in the Nexcloud mobile IRC room :) ,Hes like, if you install Android studio and some other stuff, ill debug it for you.  Thankfully he didn't get pissed about my first attempt to let him into my win7 VM that was slower than crap and wasn't passing USB through correctly or something. Eventually I rebooted and gave him 4 cores and 16 gig of ram on the metal, and he went to work and it seems, squashed this little bug for us.  It should be fixed in the near future I suppose when it gets built and put in fdroid :)   I was able to get into  settings and set it all up again!   It is really great to know there are a good group of people out there that are in it to help people and build a great community.  Super cool people. Thanks again Mario, and all of the the NC team!

**Comment by AndyScherzinger** [comment]
Awesome work @mario!
Any corresponding PR that needs review? :)

**Comment by mario** [comment]
@AndyScherzinger nah. As soon as F-Droid starts building again it should work. Wasn't that complex :D

**Comment by HammyHavoc** [comment]
Using the 2.0.0RC6 of Nextcloud on Android 4.2.2 (inkBOOK Prime) and it crashes on Settings.

**Comment by tobiasKaminsky** [comment]
@HammyHavoc can you give us a logcat?https://github.com/nextcloud/android/blob/master/README.md#get-debug-infos-via-logcat

**Comment by AndyScherzinger** [comment]
@HammyHavoc does the problem still persist and if so can you give us a logcat?https://github.com/nextcloud/android/blob/master/README.md#get-debug-infos-via-logcat

Until then closing the issue.
