### ISSUE TITLE
Connect to multiple servers?

### ISSUE THREAD

**Issue by magwas** [nextcloud/android#7295]
### Is your feature request related to a problem? Please describe.
I have account on two nextcloud servers. I would like to able to use both accounts from my phone.

### Describe the solution you'd like
A menu item 'add server', where I would be presented with the same screen with which I login to the server

### Describe alternatives you've considered
Logout, and login to another server. In this case it would be nice if the account info would be stored, and could login by just clicking on the server

### Additional context
I tried to look up how to do it, also searched the issues here, but could not find any signs that it is already implemented.

**Comment by tobiasKaminsky** [comment]
This is already possible: click on top right avatar and select "add new account".
