### ISSUE TITLE
App forces logout after sharing a file with the same user twice

### ISSUE THREAD

**Issue by togglecode** [nextcloud/android#730]
### Actual behaviour
-App forces logout after sharing a file (intern) with a user twice

### Expected behaviour
-The user should not be shown in the search list after you have added them in shared.
 
### Steps to reproduce
1. Open App
2. Long press on a file -> share 
3. Add user or Group
4. Search for a user (Let's say user "example")
5. Add the user "example" as a person which you want to share the file with
6. Search again for the user
7. Try to add him again
8. App logs out

### Environment data
Android version: 6.0.1

Device model: Moto G3

Stock or customized system: customized

Nextcloud app version: 1.4.2 RC4

Nextcloud server version: 11.0.1.2

**Comment by AndyScherzinger** [comment]
Didn't have the change yet to look for the cause but tested the issue and can confirm the logout.

**Comment by AndyScherzinger** [comment]
fixed for release 1.5.0
