### ISSUE TITLE
Auo-sync creates "fake" images in gallery app

### ISSUE THREAD

**Issue by antoinevth** [nextcloud/android#7302]
### Expected behaviour
Just auto-sync.

### Actual behaviour
Auto-sync works but it also creates "fake" images in gallery app. In gallery app, the infos of the fake images tells they are stored in `Internal Storage/Pictures/`. In fact, there are no files corresponding in this folder. These "fake" images are only visible from the gallery app.

![signal-2020-11-11-193130](https://user-images.githubusercontent.com/19272875/98850329-e8694d00-2454-11eb-8c14-4fb47277b4e1.jpeg)

### Environment data
Android version: 10

Device model: Huawei Mate 20 Pro

Nextcloud app version: 3.13.1

Nextcloud server version: 19.0.4

**Comment by aqaqsubin** [comment]
I think it is the same issue as the one below.
Duplicate of #6558

**Comment by antoinevth** [comment]
Oh yes ! Thanks, I didn't find it earlier, I'm sorry.
I close this issue then.
