### ISSUE TITLE
Nextcloud android app is not visible in HUAWEI AppGallery China

### ISSUE THREAD

**Issue by Milokita** [nextcloud/android#7303]
### Steps to reproduce
1. Search "nextcloud" in HUAWEI AppGallery using location in China

### Expected behaviour
found the app

### Actual behaviour
No app match result found, however, there is a app found in English version: https://appgallery.huawei.com/#/app/C102503897

perhaps there is a setting error when uploading the app?

**Comment by tobiasKaminsky** [comment]
Indeed, Chinese mainland was not checked.
Next week we will release 3.14.0, then it should be also available.

**Comment by tobiasKaminsky** [comment]
I added it to #6746

**Comment by Milokita** [comment]
the new version is still not show up when searched using keyword "nextcloud" @tobiasKaminsky

**Comment by tobiasKaminsky** [comment]
Huawei demands to have special certificates for distributing on Chinese mainland.
I fear that we will not tackle this…

However you can always use Fdroid version: https://f-droid.org/de/packages/com.nextcloud.client/

**Comment by Milokita** [comment]
If you registered as company in Huawei, it does require to certificates. However, I have verified developer account in Huawei. So maybe I can do the submission for you

**Comment by Milokita** [comment]
you need to submit the exemption letter, stating that it is developed solely by nextcloud and it's free

**Comment by tobiasKaminsky** [comment]
> If you registered as company in Huawei, it does require to certificates.

Yes, we have a company account.

It says:

Upload a PDF file no larger than 5 MB.
> The electronic software copyright registration certificate (electronic copyright certificate) and the paper software copyright registration certificate have the same legal effect and can be verified online. The official application channel can issue both paper and electronic copyright certificates. If your app already has a paper certificate, you can apply for a supplementary electronic copyright certificate free of charge. 

and

> Upload any important documents including copyright and proxy certificates, a disclaimer, etc. Apps being released in the Chinese mainland must have a disclaimer and along with additional supporting documents. 

So if you can guide me what exactly they require, we might can do it.



>  I have verified developer account in Huawei. So maybe I can do the submission for you

Thanks for the offer, but as it is an official app, it must be published under our control / account.

**Comment by Milokita** [comment]
As I remebered, both certificate is not mandantory. You need to find the link for exemption letter, just bellow the certificate requirement, print it and sign it or stamp it. upload the photo. (That's how I did it)

**Comment by Milokita** [comment]
If it  is mandatory, then you would need to file the application to CPCC China copyright centre http://www.ccopyright.com/en<http://www.ccopyright.com/en/mobile/>

  It would cost around 150CNY/RMB to file in the application which would request to submit the source code in hard copy. It was rather easy, I applied one 3 years ago

Sincerely
XINGZ

________________________________

**Comment by tobiasKaminsky** [comment]
Can you try it now? I got confirmation that 3.14.0 is released, also on chinese baseland.

**Comment by Milokita** [comment]
Yes, I can confirm that it is visible on AppGallery. May I ask if you do the same for xiaomi?

**Comment by tobiasKaminsky** [comment]
I am/was not aware that xiaomi also has its own app store.
A quick search does not reveal anything like that for me?

**Comment by Milokita** [comment]
> 
> 
> I am/was not aware that xiaomi also has its own app store.
> A quick search does not reveal anything like that for me?

http://global.developer.mi.com/document?doc=quickStart.aboutGetApps 
here's the link for getting started. As I am aware of, Xiaomi is less strict about the certificates etc.

**Comment by thecch** [comment]
It's gone from huawei app store again

**Comment by Milokita** [comment]
The nextcloud app is missing from the app store while "NC deck" and "NC Notes" are still exists

**Comment by AlvaroBrey** [comment]
Is it still gone?

**Comment by Milokita** [comment]
Yes, it is still gone

Sincerely
XINGZ
________________________________

**Comment by tobiasKaminsky** [comment]
2.23.1 from 23.12.22 is released for chinese mainland, according to what I can see.

**Comment by Milokita** [comment]
> 2.23.1 from 23.12.22 is released for chinese mainland, according to what I can see.

Unfortunately, I just check, the nextcloud app is not visible in the AppGallery mainland when searched with keyword "nextcloud"

**Comment by tobiasKaminsky** [comment]
![image](https://user-images.githubusercontent.com/5836855/213653163-f6dbe3d9-be19-4734-931b-27cf57a6d746.png)


I have no other possibility…
Let us wait for next version, and if it then still does not work, I'll ask Huawei for help.

**Comment by Milokita** [comment]
I checked again in appgallery, it is still not visible while the paid version of "nextcloud deck" is shown
