### ISSUE TITLE
Seek bar and Softkey was overlap

### ISSUE THREAD

**Issue by aqaqsubin** [nextcloud/android#7305]
### Steps to reproduce
1.  Play mp4 video
2. 
3. 

### Expected behaviour
- Tell us what should happen
Seek bar and Softkey should not overlap

### Actual behaviour
- Tell us what happens
Seek bar and Softkey was overlap
![image](https://user-images.githubusercontent.com/28510311/98963366-e1bd0180-254a-11eb-96a8-4c27fcfc8a9a.png)

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 10

Device model: Samsung Galaxy s10 e

Stock or customized system:

Nextcloud app version: 3.13.1

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
Reproducable on latest master

**Comment by tobiasKaminsky** [comment]
Ha, at least it is shown again… 🙈

**Comment by tobiasKaminsky** [comment]
So this is due to our new scrolling toolbar feature.

There is an APK file in this PR #7339, which you can install in parallel to your existing Nextcloud app.
It would be great if you can verify the fix.

**Comment by aqaqsubin** [comment]
@tobiasKaminsky 
There is a concern about the changed UI.
After switching the app, the video will no longer play.
This is not observed in version 3.13.1.

Nextcloud QA : https://drive.google.com/file/d/1abcPvECAGgZwK8eZg1ZXy4ofalXqMhpt/view?usp=sharing
Nextcloud 3.13.1 : https://drive.google.com/file/d/1ahrCa8XfiLg-lrEJMaw1fM-iwip3ApHc/view?usp=sharing
