### ISSUE TITLE
Disappear files After file name modification

### ISSUE THREAD

**Issue by aqaqsubin** [nextcloud/android#7306]
### Steps to reproduce
1. Modify File name (Birdie.jpg)
![image](https://user-images.githubusercontent.com/28510311/98968603-382d3e80-2551-11eb-9d15-7e089f73eeac.png)

2. Clear File name Except Extensions (-> .jpg)
![image](https://user-images.githubusercontent.com/28510311/98968623-3fece300-2551-11eb-93b7-23bd3d6ed62e.png)

3. 

### Expected behaviour
- Tell us what should happen

Not allow such changes or the file name must be changed(Not disappear).

### Actual behaviour
- Tell us what happens

Accepted change file name. 
And the file is not visible within the folder.

Not deleted.
If you try the same thing again for another file,
A notification appears that the name already exists.

![image](https://user-images.githubusercontent.com/28510311/98968659-4c713b80-2551-11eb-909c-01eb16c480e0.png)

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
This is very likely by design @aqaqsubin can you check the app's settings if you activated display of hidden files because: files starting with a dot are legal but are commonly considered "hidden files" and are thus hidden by default. ☺️

**Comment by aqaqsubin** [comment]
Thank you! I didn't know about the hidden file activation feature.
I'm sorry. i close this issue then.

**Comment by AndyScherzinger** [comment]
No worries, happy I could help :)
