### ISSUE TITLE
Empty block in main activity

### ISSUE THREAD

**Issue by Xellor** [nextcloud/android#7320]
### Steps to reproduce
1. Launch application

### Expected behaviour
- See a list of files starting from the top of the screen

### Actual behaviour
- I see a list of files not starting from the top edge of the screen.

### Can you reproduce this problem on https://try.nextcloud.com?
- No
- I believe that regardless of the server settings, this problem should be taken into account.

### Environment data
Android version: 10

Device model: Samsung Galaxy Note 9 (SM-N960F)

Stock or customized system: Stock

Nextcloud app version: 3.13.1

Nextcloud server version: 19.0.4 (stable)

Reverse proxy: ?

#### Web server error log
2020/11/14 14:47:26 [warn] 3340#3340: *42696 an upstream response is buffered to a temporary file /var/cache/nginx/fastcgi_temp/3/00/0000000003 while reading upstream, client: {client_ip}, server: {server_domain}, request: "GET /settings/apps/list HTTP/2.0", upstream: "fastcgi://127.0.0.1:9000", host: "{server_domain}”

Insert your webserver log here
- nothing related to the problem

#### Nextcloud log (data/nextcloud.log)
- nothing related to the problem

### Screenshots link
https://photos.app.goo.gl/E17LuHMEVX5Cab9GA
https://photos.app.goo.gl/zS679KnHUizvtcYy7

**Comment by AndyScherzinger** [comment]
The empty space you see is the so called rich workspace which displays the content of the Readme.md file you have on that folder. So either delete the file or add content to it.

**Comment by tobiasKaminsky** [comment]
Can you tell us what the content of readme.md is?
As we already hide if if readme.md is empty :thinking:
