### ISSUE TITLE
When Google Play description for french will be updated?

### ISSUE THREAD

**Issue by ldmpub** [nextcloud/android#733]
Hi,

Attached is the current description in Google Play Store for Nextcloud.

I made some changes in the french Transifex translation some days ago. Is it the good way to proceed? If so, when the description will be updated in Google Play with the new one?

Regards,
![google play](https://cloud.githubusercontent.com/assets/1452146/23824509/680c37ba-0678-11e7-95a4-e16048deae08.png)

**Comment by AndyScherzinger** [comment]
@ldmpub I just updated the description, it should be available online within the next couple of hours.
Thanks a lot for updating the translation! 🎉

**Comment by ldmpub** [comment]
Confirmed: french description has been updated! Thanks.

**Comment by AndyScherzinger** [comment]
Well, thank you! I just copied it over to the play store :)
