### ISSUE TITLE
Loading shimmer/progress not shown for initial image preview

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#7330]
Follow-Up to  #6757

The Image preview doesn't show a shimmer (added via  #6757) or before that a progress animation when initially loading an thumbnail from the server for preview but instead just shown a black screen + toolbar.

cc @tobiasKaminsky

**Comment by tobiasKaminsky** [comment]
To get this right:
- we want to show always a shimmer effect when loading image
- when a thumbnail is available use this (will be ~1/3 of screen)
- when no thumbnail is available, then show shimmer with default image

(When a resized image is available, this will be shown directly without any shimmer)

**Comment by AndyScherzinger** [comment]
Sounds good! The shimmering element to be shown has already been added to the UI definition, see 
https://github.com/nextcloud/android/pull/6757/files#diff-4e646694bb97cdf4c72cda6801f4474e2595d7054ce14a130933a72e53214b25R86-R106
