### ISSUE TITLE
User status change unification

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/android#7332]
I propose to standardize the user status change. Currently, changing the status in Nextcloud is by clicking the status and closing the window, while in the Android Nextcloud app by tapping on the "Set status message" button.

In my opinion, the status change in Nextcloud and in the Nextcloud Android app should be as follows:

1. Tapping (clicking) on the user status change.
2. Tapping (clicking) on the status change button.
3. Automatic closing of the window after selecting the user status.

Topic mentioned in issue: https://github.com/nextcloud/server/issues/24151.

**Comment by tobiasKaminsky** [comment]
Let us coordinate this in nextcloud/server#24151.
After we agreed on something, I will open up an issue again here.
