### ISSUE TITLE
When switching apps quickly, the password screen does not appear.

### ISSUE THREAD

**Issue by kimminji00** [nextcloud/android#7342]
### Is your feature request related to a problem? Please describe.

When switching apps quickly, the password screen does not appear.
Therefore, the file can be accessed without entering the password.
I think this is an important issue that needs to be improved, especially in security.

![capture (2)](https://user-images.githubusercontent.com/44043952/99384299-8d32d100-2912-11eb-9fdc-3e7404d650cd.gif)

### Describe the solution you'd like

Regardless of time, the password screen should appear when switching apps.
I think It would be better to modify the condition that the password screen is requested.

**Comment by tobiasKaminsky** [comment]
We have a short grace period of 5s to not bother user too often, if they have to switch.
