### ISSUE TITLE
Saving to Nextcloud from Autodesk Sketchbook and Krita is unreliable

### ISSUE THREAD

**Issue by Chemrat** [nextcloud/android#7349]
### Steps to reproduce
1. Create a new file in Autodesk Sketchbook/Krita
2. Go to `File → Share/export` in Sketchbook or `File → Save` in Krita, choose Nextcloud as destination
3. Click save

### Expected behaviour
The file is saved to the Nextcloud instance.

This is how it works if I save to Google Drive.

### Actual behaviour
Exporting from Autodesk Sketchbook either silently fails and results in a 0 byte file on Nextcloud server, or just fails and refuses to save until I close the dialog and try again.
Exporting again & overwriting that file succeeds and results in a correct file.

Saving from Krita fails with an error "Error occured while writing the file" and the file is considered unsaved. However few seconds later saved file appears on the nextcloud server.
Saving again and overwriting that file succeeds.

Usually after initial failure it starts to work as expected.

Behavior on nextcloud demo instance is identical.

## Server configuration detail

**Operating system:** Linux 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64

**Webserver:** Apache/2.4.38 (Debian) (apache2handler)

**Database:** sqlite3 3.27.2

**PHP version:** 

7.4.12
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, apcu, bcmath, exif, gd, gmp, imagick, intl, ldap, memcached, pcntl, pdo_mysql, pdo_pgsql, redis, sodium, zip, Zend OPcache

**Nextcloud version:** 20.0.1 - 20.0.1.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** nextcloud on dockerhub

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.6.0
 - bookmarks: 4.0.0
 - calendar: 2.1.2
 - cloud_federation_api: 1.3.0
 - comments: 1.10.0
 - contacts: 3.4.1
 - contactsinteraction: 1.1.0
 - dashboard: 7.0.0
 - dav: 1.16.0
 - encryption: 2.8.1
 - federatedfilesharing: 1.10.1
 - federation: 1.10.1
 - files: 1.15.0
 - files_external: 1.11.1
 - files_pdfviewer: 2.0.1
 - files_rightclick: 0.17.0
 - files_sharing: 1.12.0
 - files_trashbin: 1.10.1
 - files_versions: 1.13.0
 - files_videoplayer: 1.9.0
 - firstrunwizard: 2.9.0
 - issuetemplate: 0.7.0
 - logreader: 2.5.0
 - lookup_server_connector: 1.8.0
 - nextcloud_announcements: 1.9.0
 - notifications: 2.8.0
 - oauth2: 1.8.0
 - occweb: 0.0.7
 - password_policy: 1.10.1
 - phonetrack: 0.6.5
 - photos: 1.2.0
 - privacy: 1.4.0
 - provisioning_api: 1.10.0
 - recommendations: 0.8.0
 - richdocuments: 3.7.5
 - richdocumentscode: 6.4.13
 - serverinfo: 1.10.0
 - settings: 1.2.0
 - sharebymail: 1.10.0
 - support: 1.3.0
 - survey_client: 1.8.0
 - systemtags: 1.10.0
 - text: 3.1.0
 - theming: 1.11.0
 - twofactor_backupcodes: 1.9.0
 - twofactor_u2f: 6.0.0
 - updatenotification: 1.10.0
 - user_status: 1.0.0
 - viewer: 1.4.0
 - weather_status: 1.0.0
 - workflowengine: 2.2.0
Disabled:
 - activity
 - admin_audit
 - drawio
 - integration_gitlab
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwriteprotocol": "https",
    "dbtype": "sqlite3",
    "version": "20.0.1.1",
    "installed": true,
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_smtpsecure": "ssl",
    "mail_smtpauth": 1,
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "twofactor_enforced": "false",
    "twofactor_enforced_groups": [],
    "twofactor_enforced_excluded_groups": [],
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "apps_paths": [
        {
            "path": "\/var\/www\/html\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/www\/html\/custom_apps",
            "url": "\/custom_apps",
            "writable": true
        }
    ],
    "app_install_overwrite": [
        "occweb"
    ],
    "encryption.legacy_format_support": true,
    "encryption.key_storage_migrated": false
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** 1

**Are you using an external user-backend, if yes which one:** -

## Client configuration

**Android version**: 10
**Device model:** Galaxy Tab S6 Lite
**Stock or customized system:** stock
**Nextcloud app version:** 3.13.1

## Logs

Failures don't seem to generate errors in server logs.

**Comment by tobiasKaminsky** [comment]
@grote have you ever experienced something like that?

**Comment by Chemrat** [comment]
Is there any way I can extract logs from android client itself? Some cursory search says there was an expert mode but it's not there anymore

**Comment by grote** [comment]
> have you ever experienced something like that?

Not this particular issue. The logs of Autodesk Sketchbook/Krita would also be interesting when they fail to save. This is not even document_tree related since it is just a single file and should just work.

**Comment by tobiasKaminsky** [comment]
@Chemrat 
Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

**Comment by Chemrat** [comment]
Log turned out pretty long

Saving a file called `test2.png`, resulted in 0 byte file
22508 is pid of the autodesk sketchbook
18310 is pid of the nextcloud
I seem to have some stuck files on my nextcloud instance, i can try redo this with demo instance if necessary, but it was reproducible there too
[autodesk.txt](https://github.com/nextcloud/android/files/5580294/autodesk.txt)

**Comment by tobiasKaminsky** [comment]
```
11-22 23:15:30.916 18310 20351 E DatabaseUtils: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getMimeType()' on a null object reference
11-22 23:15:30.916 18310 20351 E DatabaseUtils: 	at org.nextcloud.providers.cursors.FileCursor.addFile(FileCursor.java:79)
11-22 23:15:30.916 18310 20351 E DatabaseUtils: 	at com.owncloud.android.providers.DocumentsStorageProvider.queryDocument(DocumentsStorageProvider.java:140)
11-22 23:15:30.916 18310 20351 E DatabaseUtils: 	at android.provider.DocumentsProvider.query(DocumentsProvider.java:913)
11-22 23:15:30.916 18310 20351 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:267)
11-22 23:15:30.916 18310 20351 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:104)
11-22 23:15:30.916 18310 20351 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1056)
11-22 23:15:30.916 18310 20351 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1029)
```

That is strange, it seems that file is null, but we use in L78 e.g file.isFolder() …

**Comment by axllent** [comment]
I'm not sure if this is related (but I believe it is) but I'm getting 0-byte files from several apps when exporting things like settings / backups and using the DocumentsProvider / Document Storage. I use this method to make backups directly from apps (tested and consistently failing on Nova launcher, andAOP, FairEmail, Synchronize Ultimate). If however I open an existing file via Document Storage (such as a kdbx password file with either Keepass2Android or KeePassDX) and save it works as expected.

It seems to be occurring only with newly created or overwritten (not re-saved) files.
