### ISSUE TITLE
Possibility to set storage path

### ISSUE THREAD

**Issue by miska** [nextcloud/android#737]
In storage path settings, I can choose only from predefined paths and in my case, it's limited to default which means only one path is possible. But I would like to download my files for example to SD card and not main memory. This is probably partially issue caused by Android emulation, but even so, it would be nice to allow experienced users to set their own path manually.

### Actual behaviour
- I can choose only Default location for storing files

### Expected behaviour
- I would be able to enter any path I like
 
### Steps to reproduce
1. Run Nextcloud client on Jolla C
2. Try to set storage path

### Environment data
Android version:
Sailfish OS 2.1.0.9

Device model: 
Jolla C

Stock or customized system:
Stock

Nextcloud app version:
1.4.1

Nextcloud server version:
10.0.0.3

**Comment by tobiasKaminsky** [comment]
The real fix is do find out why the other storage card is not shown.
Can you give us some more infos like which card and how it is mounted to your device?

**Comment by tobiasKaminsky** [comment]
No response within the last month, therefore closing.
Please feel free to reopen with additional infos, if the problem still exists.
