### ISSUE TITLE
Problems when rename files with a blank name.

### ISSUE THREAD

**Issue by KwonEunKyung** [nextcloud/android#7373]
### Steps to reproduce
1. Rename the file name of the main screen to blank.(file extension)
   e.g.) (blank).jpg, (blank).pdf
2. Refresh
3. The renamed file is missing from the main screen.
4. The File is displayed when searching by file extension.

### Expected behaviour
A file with a blank name should also appear on the main screen, or a file with an empty name should not be created.

### Actual behaviour
On the main screen, a file with a blank name does not appear but appears when you search with a file extension.

![image](https://user-images.githubusercontent.com/33508558/99663092-707cd180-2aa9-11eb-8bff-d438551fa910.png)

![image](https://user-images.githubusercontent.com/33508558/99663112-75da1c00-2aa9-11eb-9d85-6e60d780842c.png)

### Environment data
Android version: 8.0.0

Device model: Samsung Galaxy S7 edge

Nextcloud app version: 3.14.0

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
@KwonEunKyung the file is hidden by design since it is a "dot-file", simply go to the app's settings and activate "show hidden files"
