### ISSUE TITLE
Gallery - not showing all photos

### ISSUE THREAD

**Issue by pilsnerbeer** [nextcloud/android#7376]
### Steps to reproduce
1. have some photos in your NC (I have a few hundred max)
2.  open gallery 
3.  scroll down. notice not all of them are displayed.

### Expected behaviour
Show all photos in gallery

### Actual behaviour
In my case, 44 photos (out of maybe x hundred) are shown.

### Environment data
Android version: 10

Device model: op5T

Nextcloud app version: 3.13.1

Nextcloud server version: 19.0.*

**Comment by AndyScherzinger** [comment]
@pilsnerbeer still happening with released 3.14.0?

**Comment by pilsnerbeer** [comment]
> @pilsnerbeer still happening with released 3.14.0?

yes :)

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky mentioned this in another post, that it is likely related to the server (android app changes the query with 3.14.0), so I am unsure if a update to 20.0.1 would help :/

**Comment by tobiasKaminsky** [comment]
> so I am unsure if a update to 20.0.1 would help :/

I doubt so. For some reasons we can trigger (on some server) a valid search query that either spins up 100% cpu or shows wrong/incomplete search results.

**Comment by tobiasKaminsky** [comment]
Discussed here: https://github.com/nextcloud/server/issues/20839
