### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by dhrobinson** [nextcloud/android#7379]
Sorry, I cannot give steps to reproduce. Nextcloud on my android (Sony Xperia xz premium, android 9) keeps crashing, or rather needs to be force-closed.

I have a background process that is uploading the contents of my sd card (128GB, mainly audio and photos).

Much of the time, there is a notification of a file uploading, but the % never changes. It could be 48%, it could be 100%.

Rebooting seems to help but only a few files will complete before getting stuck again. 

It finally offered a bug report to post, so here it is:

************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{9bc3342 u0 com.nextcloud.client/com.owncloud.android.files.services.FileUploader}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1743)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:280)
	at android.app.ActivityThread.main(ActivityThread.java:6706)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Sony
Device: G8141
Model: G8141
Id: 47.2.A.10.107
Product: G8141

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 172320177

**Comment by aqaqsubin** [comment]
The cause of the App Crash is being discussed in #2010.
And this error seems to have been solved in #7340 !
