### ISSUE TITLE
App crashes when playing a mp4 video

### ISSUE THREAD

**Issue by jeffyoung729** [nextcloud/android#7386]
### Steps to reproduce
1. Upload mp4 video
2. Attempt to play same video from the same android device it was uploaded with, but within nextcloud.

### Expected behaviour
- Video should play like the other mp4 videos. If the video was not uploaded by the same device it's being attempted to be played on, all is well. 

### Actual behaviour
- app crashes. 

### Can you reproduce this problem on https://try.nextcloud.com?
- According to the report, it's a bug in the app

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{4beb168 u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2068)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7814)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: a50
Model: SM-A505G
Id: QP1A.190711.020
Product: a50ub

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: A505GUBS5BTJ4

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Fix will be in #7340
