### ISSUE TITLE
impossible to upload a file 2 times

### ISSUE THREAD

**Issue by paolomeraviglia** [nextcloud/android#739]
### Actual behaviour
Example: I fixed 50 mb limit  for an account. Trying from android app to load a file of 26 mb, deleting, purging trash and re-uploading is impossible (upload failed error from app when I try to upload the second time).

Trying with other files of 1-2 mb will make it work.

### Expected behaviour
Upload ok if the quota is not reached.

### Steps to reproduce
1. upload a file of at least half the space set by quota
2. delete the file and purge the trash from web app
3. upload the same file

It's not important if the directory where the file is uploaded the second time is the same of the first time. It will not work in any way.

### Environment data
Android version: 6.0.1

Device model: oneplus one A0001

Stock or customized system: stock cyanogenmod 13

Nextcloud app version: latest

Nextcloud server version: latest stable

#### Web server error log
```
Insert your webserver log here
```
no errors there

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
no infos there

HOW I TEMPORARY SOLVED THE ISSUE
_____________

the only way I found was purging cache and data of the app.

**Comment by paolomeraviglia** [comment]
Trying with a different app (oCloud), everything works ok. I'm pretty sure the problem is in nextcloud app.

**Comment by AndyScherzinger** [comment]
@paolomeraviglia did you try it right away with two uploads or did some time go by inbetween, because then it could also be a server-side issue?

**Comment by paolomeraviglia** [comment]
i tried file by file doing:

- upload -> ok
- wait -> ok
- trash -> ok
- delete via web gui from trash -> ok
- reupload -> failed

With oCloud app (not owncloud) all the things are running ok. If needed, please describe me a complete test to do and I'll do it now

**Comment by AndyScherzinger** [comment]
@paolomeraviglia thanks for the detailed description and feedback. The test steps seem detailed enough!

**Comment by AndyScherzinger** [comment]
@mario @tobiasKaminsky I labeled it 1.5.0 since this seems to be a small issue to fix and 1.4.2 is frozen.

**Comment by paolomeraviglia** [comment]
ok, thanks for your great work: I'm testing now if the same problem appear in the beta release

**Comment by mario** [comment]
@AndyScherzinger this should already be fixed in beta.

**Comment by AndyScherzinger** [comment]
That would be awesome! Which PR fixes this one?

**Comment by paolomeraviglia** [comment]
CONFIRMED, the beta version is working right! Awesome!

**Comment by mario** [comment]
@AndyScherzinger one on the library by @tobiasKaminsky.

@paolomeraviglia thanks for the confirmation.

**Comment by AndyScherzinger** [comment]
Sweet! Yeah I guess I then has been the chunking re-upload fix :)
