### ISSUE TITLE
Completly broken on mac after trying 2.3.0rc1

### ISSUE THREAD

**Issue by erwdavid** [nextcloud/android#741]
### Actual behaviour
-Tell us what happens

Nextcloud app tells me there is no connection every time.

### Expected behaviour
-Tell us what should happen

Have a connection 

### Steps to reproduce
1.  Install 2.3.0rc1
2. evrything broken
3. reinstall 2.2.4
4. everything still broken

### Environment data
Android version:
MAC

Device model: 
MAC

Stock or customized system:

Nextcloud app version:
see before

Nextcloud server version:
11.0.1

#### Web server error log
```
No error
Insert your webserver log here
```
173.38.220.43 - erwan [14/Mar/2017:15:19:38 +0100] "GET /status.php HTTP/1.1" 200 157 "-" "Mozilla/5.0 (Macintosh) mirall/2.2.4 (build 1) (Nextcloud)"
173.38.220.43 - erwan [14/Mar/2017:15:19:39 +0100] "GET /status.php HTTP/1.1" 200 157 "-" "Mozilla/5.0 (Macintosh) mirall/2.2.4 (build 1) (Nextcloud)"
173.38.220.43 - erwan [14/Mar/2017:15:20:10 +0100] "GET /status.php HTTP/1.1" 200 157 "-" "Mozilla/5.0 (Macintosh) mirall/2.2.4 (build 1) (Nextcloud)"
173.38.220.43 - erwan [14/Mar/2017:15:20:37 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 499 0 "-" "Mozilla/5.0 (Macintosh) mirall/2.2.4 (build 1) (Nextcloud)"
173.38.220.43 - erwan [14/Mar/2017:15:20:43 +0100] "GET /status.php HTTP/1.1" 200 157 "-" "Mozilla/5.0 (Macintosh) mirall/2.2.4 (build 1) (Nextcloud)"

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
No log at this time

**Comment by mario** [comment]
Hm, is this an Android or Mac client issue? :D

**Comment by erwdavid** [comment]
It is a mac client issue

**Comment by erwdavid** [comment]
Sorry, I followed a link which was given to me on twitter, did not see It was for android issues

**Comment by mario** [comment]
@erwdavid no worries - let me try to get the right link for you :)

**Comment by erwdavid** [comment]
Then I see that after some (quite long time) the app 2.2.4 works again.
I do not understand but won't touch it for now. Seems my machine is at fault...
WIll close.
