### ISSUE TITLE
************ CAUSE OF ERROR ************  android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground() 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1881) 	at android.os.Handler.dispatchMessage(Handler.java:105) 	at android.os.Looper.loop(Looper.java:164) 	at android.app.ActivityThread.main(ActivityThread.java:6944) 	at java.lang.reflect.Method.invoke(Native Method) 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)  ************ APP INFORMATION ************ ID: com.nextcloud.client Version: 30140090 Build flavor: gplay  ************ DEVICE INFORMATION ************ Brand: samsung Device: herolte Model: SM-G930F Id: R16NW Product: heroltexx  ************ FIRMWARE ************ SDK: 26 Release: 8.0.0 Incremental: G930FXXS8ETCM

### ISSUE THREAD

**Issue by emanuelrdantas** [nextcloud/android#7413]
### Steps to reproduce
1. Viewing photos on Android apl
2. 
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
Close the program with the message above 
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Is fixed via #7340
