### ISSUE TITLE
Missing player control buttuns after turn display on

### ISSUE THREAD

**Issue by tioannidis** [nextcloud/android#7416]
If I play a mp3 and the display goes in the standby, after the reactivation the control buttons are not displayed anymore 

Nextcloud App v 3.13.1

Device: pixel 3a with Android 11

![Screenshot_20201121-100843](https://user-images.githubusercontent.com/1592909/99873864-462f2f00-2be3-11eb-8fcc-6089511c944f.png)
![Screenshot_20201121-100859](https://user-images.githubusercontent.com/1592909/99873866-47605c00-2be3-11eb-8642-d5fed3419f72.png)

**Comment by tobiasKaminsky** [comment]
Thanks for the bug report.
I cannot reproduce it on latest master version, so it might be already fixed in 3.14, or will come with 3.15.

**Comment by AndyScherzinger** [comment]
Likely fixed via #7361

**Comment by AndyScherzinger** [comment]
so 3.14.1

**Comment by tioannidis** [comment]
i can reproduce it also on 3.14.0 .
i have to wait for the 3.14.1 release on fdroid to test it again.

**Comment by AndyScherzinger** [comment]
> i have to wait for the 3.14.1 release on fdroid to test it again.

@tioannidis Well, you could install the app from https://github.com/nextcloud/android/pull/7361#issuecomment-729796450 which is then installed in parallel, just to do testing of the fix (it is a QA build)

**Comment by tioannidis** [comment]
> 
> 
> > i have to wait for the 3.14.1 release on fdroid to test it again.
> 
> @tioannidis Well, you could install the app from [#7361 (comment)](https://github.com/nextcloud/android/pull/7361#issuecomment-729796450) which is then installed in parallel, just to do testing of the fix (it is a QA build)

can confirm, that the problem is fixed in version 16807.
thx

**Comment by AndyScherzinger** [comment]
perfect and thanks fore testing 👍
