### ISSUE TITLE
automatic upload - problem with duplicate filenames?

### ISSUE THREAD

**Issue by alexanderdd** [nextcloud/android#7431]
### Steps to reproduce
1. enable automatic upload of the foto folder DCIM/100ANDRO
2. take a photo, it is called DSC_0001.JPG and uploaded automatically, deleted from 100ANDRO
3. take another photo, it is called DSC_0001.JPG again because the other one is already deleted from 100ANDRO and Sony always starts with one if there are no images
1. DSC_0001.JPG gets renamed to DSC_0001 (2).JPG and moved to the Nextcloud Android media folder. Nextcloud Android app shows green checkmark as if it was uploaded
1. it is not uploaded to the server

### Expected behaviour
all images should be automatically uploaded to the server, no matter what

### Actual behaviour
not uploaded

### Can you reproduce this problem on https://try.nextcloud.com?
don't have time to do that right now, maybe later

### Environment data
Android version: 8.0.0

Device model: Sony Xperia Xcompact

Stock or customized system: stock

Nextcloud app version: 3.14.0

Nextcloud server version: 19.0.5

Reverse proxy: ?

Please tell me if you need more info.

**Comment by Files4Simon** [comment]
I seem to have the same problem.
What is realy strange is that as soon as I removed the option to upload preexisting files it started synchronizing and uploadig all files :)

**Comment by tobiasKaminsky** [comment]
What overwrite settings do you have for this auto upload folder?

**Comment by Files4Simon** [comment]
I have the setting on ignore duplicates / don't upload

**Comment by tobiasKaminsky** [comment]
ignore duplicates and then it still uploads it?

**Comment by Files4Simon** [comment]
No it only uploads the ones that didn't exist on the server. But if I check the Nextcloud appstore reviews, many people seem to have problems with automated picture upload right now..

**Comment by tobiasKaminsky** [comment]
Ah, maybe it is a problem that it is exactly the same file name, but then a different image.
Let me try to reproduce it.
