### ISSUE TITLE
App crash when open autoupload screen 

### ISSUE THREAD

**Issue by cschaf** [nextcloud/android#7436]
### Steps to reproduce
1. I set up that remote auto upload photosw will be kept by conflicts
2. I restarted my phone (xiaomi mi 9t pro)  because the app still asking me if I want to keep a image local or remote 
3. After restarting I started the app and try to open autoupload then the app crashed

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- I expected that the autoupload screen to load. 

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:
10 QKQ1.190825.002
Device model: 
MI 9t Pro 
Stock or customized system:
MIUI 12.0.3.0 (QFKEUXM) 
Nextcloud app version:
3.14.0
Nextcloud server version:
15.0.5.3
Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Can you give us more info why it crashes?

Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat
