### ISSUE TITLE
Local file not found after upload

### ISSUE THREAD

**Issue by boistordu** [nextcloud/android#7439]
### Steps to reproduce
1. Activate a gallery in auto-upload to be uploaded 
2. Configure it so the items got deleted after upload
3. Let the auto upload run 

### Expected behaviour
- besides the fact that I always have a message about the fact that the app is too slow to respond.
I would expect that after being uploaded, an item from the library would be deleted and in-between maybe a check of a checksum between the file in the gallery and the file on the server. Being deleted after that and then disappeared from my history of sent items? 

### Actual behaviour
- the list goes on and on and it seems that it is considered as error and so it's being kept in the list as a possible re-try. And from time to time it is put again in the list to be sent again. 

### Can you reproduce this problem on https://try.nextcloud.com?
- it happened on every one of my instances I ve tried to whether it s cloudamo, disroot, hetzner etc so whether it's a managed instance or managed by me. So I didn't really see the point or maybe all those IT's haven't properly done their jobs? And it's not related to the version of nextcloud since it's been forever the case.

### Environment data
Android version: 10

Device model: fairphone 3

Stock or customized system: stock or maybe some customization from fairphone TBD

Nextcloud app version: 3.14 but was also the case for the previous version 

Nextcloud server version: 20.0.2 at the time but was true for all 20 version and 19 version too

Reverse proxy: none

#### Web server error log
```
Insert your webserver log here
```
No error on the server 
#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
Will add it later 
I would prefer to have a secure place to send it because I don't want to spend hours to scrub any sensitive information 

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate
![image](https://user-images.githubusercontent.com/9523075/99908305-c3d56680-2cd9-11eb-9705-020c8d33a804.jpeg)

**Comment by tobiasKaminsky** [comment]
Do you have set up the auto upload twice?
Can you find the image in question on server?

**Comment by boistordu** [comment]
It seems that I have 2 different results for you for now to your questions.
For the telegram video or images I can't find it on the server according to the search tool. 
But I will try to find it manually because I have a different result for the screens hot part.

The screenshot item I can find them on the server as far as I ve tested.


About if I ve set it up twice. At the very beginning I ve set it up twice because of my other bug report which was about the changes not taken into account. So I ve clicked on the cloud image a first time to activate the menu to make the according changes like delete it after upload. Then I deactivate it by clicking on the cloud image again. And then I click on the cloud image a third time and I leave it like that. That s what I do.

**Comment by boistordu** [comment]
By the way I m trying to create a log file on my pc about my two tickets but it doesn't seem to fill anything. Any tips about that? I m following your tutorial on the github Readme

**Comment by boistordu** [comment]
platform-tools>adb logcat | "C:\Program Files (x86)\GnuWin32\bin\grep" "$(adb shell ps | gawk '/com.nextcloud.client/{print $2}')" > logcatOutputnextcloud.txt
