### ISSUE TITLE
When image preview are disabled, it asks a confirmation to download the image (and you need to reopen the image)

### ISSUE THREAD

**Issue by IIPoliII** [nextcloud/android#7445]
### Steps to reproduce
1. Disable image generation preview in the nextcloud server config
2. Try to open an image on mobile
3. And the image isn't shown

### Expected behaviour
- Tell us what should happen

When the preview is disabled it should show the image in it's original resolution and also if a confirmation is asked to download the image, it should instead load.

### Actual behaviour
- Tell us what happens

When I disable the previews on the server then it asks on mobile if I want to download the original file.
If I press yes, then I need to close the image and open it again so that it shows correctly.

### Environment data
Android version: 9.0

Device model: OnePlus 3T

Stock or customized system: Custom

Nextcloud app version: Latest

Nextcloud server version: 20.0.0.2

Reverse proxy: No

**Comment by tobiasKaminsky** [comment]
>     1. Disable image generation preview in the nextcloud server config

Can you give me the config flag? So that I can test it 1:1?

**Comment by IIPoliII** [comment]
> > ```
> > 1. Disable image generation preview in the nextcloud server config
> > ```
> 
> Can you give me the config flag? So that I can test it 1:1?

Sorry to ask, but how can I get that?

If you mean the configuration in config.php it's simply adding this : 
![image](https://user-images.githubusercontent.com/29628512/99948635-051d5300-2d7a-11eb-97c3-b034ad924141.png)

https://docs.nextcloud.com/server/9.0/admin_manual/configuration_files/previews_configuration.html

`  'enable_previews' => false,`

**Comment by tobiasKaminsky** [comment]
> When I disable the previews on the server then it asks on mobile if I want to download the original file.
> If I press yes, then I need to close the image and open it again so that it shows correctly.

Cause is that the snackbar with "download" is not for the current one, but for the next image.
So basically you then download the next image, but not your current one.

See here: https://github.com/nextcloud/android/issues/4971#issuecomment-564454823

It is a duplicate, but unfortunately I did not found a way to prevent it.

**Comment by IIPoliII** [comment]
For my case is it possible to simply, disable the snakbar and directly load the actual image without confirmation? When image previews are disabled?

**Comment by tobiasKaminsky** [comment]
Downloading files automatically is something we wanted to prevent, as this requires too much data.
We could think about adding an "always" to the question if full image should be downloaded.
But how to revert this then, if needed?

**Comment by IIPoliII** [comment]
> Downloading files automatically is something we wanted to prevent, as this requires too much data.
> We could think about adding an "always" to the question if full image should be downloaded.
> But how to revert this then, if needed?

Well, a good idea would be to do it like in telegram if you always download you can simply disable it in the app settings.

However, previews are quite shity I found if you turn them on with S3 since it takes twice the storage for only one image and it isn't counted on the user qota

**Comment by tobiasKaminsky** [comment]
> However, previews are quite shity I found if you turn them on with S3 since it takes twice the storage for only one image and it isn't counted on the user qota

For this I suggest to open an issue on server repo.
