### ISSUE TITLE
App Crash deleting picture from photos tab
    

### ISSUE THREAD

**Issue by axheli** [nextcloud/android#7448]
************ CAUSE OF ERROR ************  android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{7ee3c66 u0 com.nextcloud.client/.media.PlayerService} 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2133) 	at android.os.Handler.dispatchMessage(Handler.java:106) 	at android.os.Looper.loop(Looper.java:245) 	at android.app.ActivityThread.main(ActivityThread.java:7953) 	at java.lang.reflect.Method.invoke(Native Method) 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631) 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)  ************ APP INFORMATION ************ ID: com.nextcloud.client Version: 30140090 Build flavor: gplay  ************ DEVICE INFORMATION ************ Brand: OnePlus Device: OnePlus8Pro Model: IN2025 Id: RP1A.201005.001 Product: OnePlus8Pro  ************ FIRMWARE ************ SDK: 30 Release: 11 Incremental: 2011010100

**Comment by tobiasKaminsky** [comment]
I hope this is just another symptom of the same cause, so it will be fixed with #7340
