### ISSUE TITLE
Put version 1.4.1 and 1.4.2 into downloads on website

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#745]
At the moment 1.4.1 final and 1.4.2 are not available on https://download.nextcloud.com/android/

@mario can you make the APKs available there? I'd say the final releases are enough.

**Comment by mario** [comment]
Are you sure we want to advertise manually downloaded APKs for stable?

**Comment by AndyScherzinger** [comment]
Well, we do so (and so does Signal btw 😄) and want to do so. 
There is also one user on GPlay who wants to downgrade (battery drain reasoning), so  we can then simply solve the user's matter in that case.

**Comment by mario** [comment]
Will be done then.

**Comment by AndyScherzinger** [comment]
Thanks a lot ❤️

**Comment by maltklaus** [comment]
Thanks!

**Comment by tobiasKaminsky** [comment]
I have added this to our generic release roadmap: https://github.com/nextcloud/android/issues/150

**Comment by AndyScherzinger** [comment]
Can anybody take care of this please? :)

**Comment by tobiasKaminsky** [comment]
1.4.2 is also missing, at the moment only mario and lukas can build versions with official key.

**Comment by mario** [comment]
Will be done, will be done.

**Comment by oparoz** [comment]
One more reminder :)

**Comment by tobiasKaminsky** [comment]
@oparoz Fdroid cannot work as those versions have some google related stuff in it.
But 1.5.0 will be google free again and then will also be (automatically) be published on fdroid.

**Comment by mario** [comment]
I will build this first thing on Tuesday and poke @LukasReschke to update the site.

**Comment by mario** [comment]
Built and handed off to @LukasReschke- so closing.
