### ISSUE TITLE
Make PIN activity mimic a dialog

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#7455]
As a follow-up issue to the discussion in https://github.com/nextcloud/android/pull/7370#issuecomment-731143949 and https://github.com/nextcloud/android/pull/7370#issuecomment-731159264 mimic a dialog:

* surround the elements with a card view the PIN activity elements
* center the card view (vertical+horizontal)
* make cancel a borderless-themed button
* make activity background "bg default" so it works for dark/light/night/day

---
* post screenshots (likely available via the screenshot tests anyways) to the PR

**Comment by bguneys** [comment]
Hi @AndyScherzinger , I have added a PR (#7538) for this issue. Does it fit what you mentioned here?

**Comment by AndyScherzinger** [comment]
@bguneys looks pretty good 👍

Unfortunately I am not at my pc over the weekend so I will take a deeper look next week and so might @tobiasKaminsky also afk over the weekend.
