### ISSUE TITLE
app crashes when trying to open the video file 

### ISSUE THREAD

**Issue by cieska** [nextcloud/android#7468]
### Steps to reproduce
1. Android app, brows to mobile video auto upload folder on NC server.
2. Click on one of the videos.
3. Network indicator showing data usage and eventually in few seconds app closes itself with leaving me with this error message I have copied below.

### Expected behaviour
I don't really have success watching videos via Android NC app, but I thought I will try again. Not sure if somehow the new android firmware was upgraded just recently on my phone. 

### Actual behaviour
- app crashes when trying to open the video from server side. 

************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{53265dd u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2039)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7697)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus5T
Model: ONEPLUS A5010
Id: QKQ1.191014.012
Product: OnePlus5T

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 2010292059

**Comment by tobiasKaminsky** [comment]
This should be fixed via 3.14.1 RC2, coming today. You can test it via play beta program.
