### ISSUE TITLE
No auto-upload feature on Android 7

### ISSUE THREAD

**Issue by io-node** [nextcloud/android#747]
### Actual behaviour
Upgraded phone to Android 7 (which meant also reinstall all applications). And settings menu doesn't show the possibility to auto-upload photos/videos

### Expected behaviour
Possibility to set settings to enable auto-upload of photos+videos and specify the destination folder.
 
### Steps to reproduce
1. Install application
2. Login to NextCloud server
3. Go to settings menu

### Environment data
Android version: 7.0
Device model: UMi Super
Stock or customized system: Stock
Nextcloud app version: 1.4.2
Nextcloud server version: 11.0.2

**Comment by AndyScherzinger** [comment]
Hi  @io-node instant upload (in settings) has been replaced with auto upload (in main/drawer menu) 😄 
So I close the issue, if the provided solution within the app doesn't meet your use case, please re-open the issue and let's discuss :)

**Comment by io-node** [comment]
Hi @AndyScherzinger sorry for not seeing that (obvious) change :) I do have a little remark. It looks like now both photos and videos are synced to the same folder. Previously I was able to have them in separate folders. Is there a way of doing this or would this mean a feature enhancement?

**Comment by Bullnados** [comment]
If u save pics and vids in separate folders in sdcard. Than yes

**Comment by io-node** [comment]
OK I see it now. The stock photo app doesn't save it separate. OK Thanks for this tip :)

**Comment by AndyScherzinger** [comment]
> Previously I was able to have them in separate folders. Is there a way of doing this or would this mean a feature enhancement?

At the moment no (at least not for the stock camera app which put both in one folder). Video folders are a soon to come feature and possibly also audio and custom folders. If and how a image/video separation like before can be achieved with the mentioned extension in mind is still not resolved. So it is a feature enhancement with a not yet clear, exact solution.
