### ISSUE TITLE
App crash when deleting files

### ISSUE THREAD

**Issue by playaz44** [nextcloud/android#7477]
### Steps to reproduce
1. Select ~60 files in the folder (not all) 
2. From the menu in the upper right corner, click delete 
3. Wait a few seconds for files to be deleted 
4. App crash in ~3-5sec

I tried to repeat the error, the application every time it is crashed when you try to delete files, delete the same files and upload them again from pc app or www working without problém, and then again removing from the phone brings the same results, app crash

**Edit: The application closes when you try to delete more than 2 files, at 1 file there is no problem, at 2 or more the application dies
Sorry for my English, this is not my language** 

### Expected behaviour
- Tell us what should happen

The application turns off after deleting several files 

### Actual behaviour
- Tell us what happens

App crash

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

No - This is in app on mobile

Device model: Huawei p20 pro 

Stock or customized system: emui 10.0.0

Nextcloud server version: 20.0.2

Reverse proxy: no

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
``

There are no server errors 

Insert your Nextcloud log here
```



************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{f0e0d44 u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2313)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:213)
	at android.app.ActivityThread.main(ActivityThread.java:8178)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWCLT
Model: CLT-L29
Id: HUAWEICLT-L29
Product: CLT-L29

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 10.0.0.171C432

**Comment by tobiasKaminsky** [comment]
This should be fixed in 3.14.1 RC2 coming today. You can test it via play store beta program.
If not, please re-open.
