### ISSUE TITLE
Fdroid old version for release 1.4.1

### ISSUE THREAD

**Issue by Bullnados** [nextcloud/android#749]
On fdroid app version 1.4.1 is the actual main version.
Beta/Nightlies still work. There is a nightly from 20170314

Maybe same #727 or #104

**Comment by AndyScherzinger** [comment]
@Bullnados exactly, #727 is the reason why 1.4.1 is the latest stable on f-droid and we unfortunately have to skip 1.4.2 for f-droid and it is rather likely that 1.5.0 will be the next stable available on f-droid.

**Comment by Bullnados** [comment]
Omfg u are right. Sorry
