### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by sahin-a** [nextcloud/android#7499]
### Steps to reproduce
1. Starting a Stream

### Expected behaviour
- Video starts playing

### Actual behaviour
- loads forever or Crashes, Sometimes IT even Crashes while playing

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 9

Device model: redmi Note 8

Stock or customized system: stock

Nextcloud app version:latest

Nextcloud server version: latest

************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{56b6cf u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1768)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6864)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: xiaomi
Model: Redmi Note 8T

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: V11.0.7.0.PCXEUX

**Comment by tobiasKaminsky** [comment]
This is fixed via 3.14.1 RC2, please check via play store beta program.
