### ISSUE TITLE
New uploader in 1.4.2 doesn't upload existing photos

### ISSUE THREAD

**Issue by ednl** [nextcloud/android#750]
### Actual behaviour
Updated to Play Store version 1.4.2, checked the cloud icon for all photo folders found, waited, nothing started uploading. Removed and re-created Nextcloud account, still nothing.

### Expected behaviour
Existing photos to be auto-uploaded when checking photo folder. Perhaps with an extra check "also upload old photos" or similar.

### Steps to reproduce
1. Have existing photos on your Android device
2. Start using new "Google-like" uploader
3. Existing photos won't upload

### Environment data
Android version: 6.0.1
Device model:  Motorola Moto G (3rd Gen, 2015)
Stock or customized system: Stock
Nextcloud app version: 1.4.2
Nextcloud server version: 11.0.2

**Comment by AndyScherzinger** [comment]
Hi @ednl Thanks for the report, this is part of our Autp Upload roadmap, see #285 and would be covered by either v1.1 of the Auto upload or version 3 of the auto upload.
