### ISSUE TITLE
Samsung S7 Edge NextCloud app crashing

### ISSUE THREAD

**Issue by vasylfarkavets** [nextcloud/android#7506]
![Screenshot_20201126-103542_Nextcloud](https://user-images.githubusercontent.com/61736380/100327001-5b390300-2fd3-11eb-80c4-7fda4cb859bd.jpg)
Hello.
This is second time NexCloud app has crashed.
Basically it is very basic install as i didn`t change anything.
And i was about to delete default files and then app crash happend.

**Comment by tobiasKaminsky** [comment]
This is fixed via 3.14.1 RC2.
