### ISSUE TITLE
limited interface space for tablet version

### ISSUE THREAD

**Issue by maettuu** [nextcloud/android#7512]
### Steps to reproduce
1. open nextcloud on HUAWEI tablet android 9.1.0
2. sign in to nextcloud

### Expected behaviour
- the interface should use up the whole screen of the tablet like in version 3.13.1

### Actual behaviour
- the list of folders/files are cramped up to the left side of the screen leaving a gap on the right half of the screen

this happened in a previous version maybe a year ago, not sure which one exactly. 

### NOW
![nextcloud_version_3 14 0_portrait](https://user-images.githubusercontent.com/67366096/100376018-116e0e00-300f-11eb-840e-0d22a9aeff69.jpg)
![nextcloud_version_3 14 0_landscape](https://user-images.githubusercontent.com/67366096/100376020-129f3b00-300f-11eb-9ffb-5fbc63ac5d42.jpg)
### BEFORE
![nextcloud_version_3 13 1](https://user-images.githubusercontent.com/67366096/100376024-13d06800-300f-11eb-9b63-49cd7f02aa93.jpg)

**Comment by tobiasKaminsky** [comment]
We already discuss how to enhance this in #6769
