### ISSUE TITLE
[Feature Request] Make it possible to create a file from within the app.

### ISSUE THREAD

**Issue by s-p-k** [nextcloud/android#752]
Hello and congratulations for the very nice android app.

I was thinking that it would be nice to be able to create a new files
directly instead of just uploading them(It's already possible to do
that for folders). There are cases where I'm not home and I want
to add some notes(new files) using my phone, so I would be nice
to be able to do that instead of creating locally and then uploading.

**Comment by AndyScherzinger** [comment]
Hi @s-p-k that sounds possible I'd say the question though I would like to raise would be if your use case wouldn't be already covered by the Notes app available, like https://f-droid.org/repository/browse/?fdfilter=Nextcloud&fdid=it.niedermann.owncloud.notes or if you simply want the create "text file" option which is also available in the web frontend. Other than that I'll close the ticket in favor of #417 which has all the already happened discussion on how to provide a basic text editor for the app.
