### ISSUE TITLE
When I play a video in mp4 format, the app crashes directly

### ISSUE THREAD

**Issue by expoli** [nextcloud/android#7520]
### Steps to reproduce
1. The app crashes after playing the video
2. 
3. 

### Expected behaviour
- The video plays normally

### Actual behaviour
- app crashes directly

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:9

Device model: 

Stock or customized system:

Nextcloud app version:3.14.0

Nextcloud server version:20.0.2

Reverse proxy:Nginx

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{265e553 u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(Unknown Source:342)
	at android.os.Handler.dispatchMessage(Unknown Source:21)
	at android.os.Looper.loop(Unknown Source:210)
	at android.app.ActivityThread.main(Unknown Source:107)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:281)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: sagit
Model: MI 6
Id: PKQ1.190118.001
Product: sagit

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: V11.0.5.0.PCACNXM
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Will be fixed with 3.14.1, which is already available as a test version via play store beta program.
