### ISSUE TITLE
Video upload fails from app. Works from chrome on and device

### ISSUE THREAD

**Issue by Danny10W** [nextcloud/android#7522]
### Steps to reproduce
1. Open app
2. Select upload file
3. Choose an mp4

### Expected behaviour
- Tell us what should happen
Video is successfully uploaded
### Actual behaviour
- Tell us what happens
After starting to upload the upload fails tooth server unavailable message. Continues to fail in upload que
### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:
10
Device model: 
Samsung s10
Stock or customized system:
Stock
Nextcloud app version:
3.14.0
Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat
