### ISSUE TITLE
Android client calculates required storage for synchronization wrong 

### ISSUE THREAD

**Issue by daemonkeeper** [nextcloud/android#7523]
### Steps to reproduce

So I'm old fashioned and don't believe in music streaming. Thus, I use Nextcloud to synch my music collection to my phone. Hence, every once in a while I push the synchronize button  in the Android client on my music folder, to get my collection updated in my phone. The problem is, this no longer works for the root folder (e.g. nextcloud-root/music), but it does work by entering the directory, select all folders in the UI and push the synchronize button as a combined action there).

The reasoning is, that the Android client checks the required storage size before synchronizing the data, but it does not take into account already existing files from previous synchronizations. So, while this error message is technically correct that I do not have enough storage available to synch the folder entirely, it does not take into account that the largest fraction of this space is _already occupied_ by this very same previously synched folder. Thus the additional net storage capacity needed is much, much smaller. Thus, the displayed error is giving a false error message, when it shouldn't.  

![Screenshot_20201127-180233_Nextcloud](https://user-images.githubusercontent.com/20989505/100472394-75123d00-30dc-11eb-925a-20dfe401854d.jpg)

### Expected behaviour

You may do more intelligent space consumption calculation, or at very least allow a force override of the warning. 

### Actual behaviour

Synchronization is prevented by a wrongly calculated storage need estimate

### Can you reproduce this problem on https://try.nextcloud.com?

I didn't try, but I'm sure this is a client issue.

### Environment data
Android version: 10
Device model:  SM G970F (Samsung Galaxy S10e)
Stock or customized system: Stock
Nextcloud app version: 3.14.0
Nextcloud server version: 19.0.4
Reverse proxy: None

**Comment by tobiasKaminsky** [comment]
Hm.
We have quite a lot tests for this: https://github.com/nextcloud/android/blob/e0700c376c94553488eefad7beb9f9c1816d045d/src/androidTest/java/com/owncloud/android/ui/fragment/OCFileListFragmentIT.kt#L41

So in your case you have a folder with 84.1G in total on server.
How much of this is downloaded already?

34G are left on device.

**Comment by daemonkeeper** [comment]
Actually all of it. The folder is 84.1G in Nextcloud (online, in the cloud), of which all of it is synchronized to the device already. It's very much the only thing I store on the SD card, I'm not entirely sure why my phone calculcates the size different (maybe you actually meant GiB and not GB?) but it does roughly match the expected size.

![1024-2162](https://user-images.githubusercontent.com/20989505/100882340-5bdc0880-34af-11eb-9969-962fd7f5a2f8.jpg)
![1024-2163](https://user-images.githubusercontent.com/20989505/100882350-5ed6f900-34af-11eb-96ac-783779ce0350.jpg)

By the way, it may be related to the fact that even though I can synchronize the folder in the app, and working around the issue by selecting the subfolders to synchronize, and even though it does actually consume 80+G of space on my SD card, the phone client does not actually list the folder in the "on the device" ("Auf dem Gerät") tab in the app for some reason anymore.

**Comment by daemonkeeper** [comment]
On my last comment, here is to illustrate what I mean

This is the "on the device" tab in the Android App:

![Screenshot_20201202-150641_Nextcloud](https://user-images.githubusercontent.com/20989505/100883254-6d71e000-34b0-11eb-9f43-8803c8d7736e.jpg)

This is "All Files"/Music (no green check mark)/<awesome band folder> (no green check mark)/
![Screenshot_20201202-150553_Nextcloud](https://user-images.githubusercontent.com/20989505/100883268-71056700-34b0-11eb-9f1a-124f8105ebf7.jpg)

Actual files do have a check mark.
