### ISSUE TITLE
Auto upload still erroneous

### ISSUE THREAD

**Issue by clriis** [nextcloud/android#754]
### Actual behaviour
-Tell us what happens
Immediately after a phone reboot the app works as expected. Files are uploaded (in my case pictures).
But after some time (3-4-5.... hours) files no longer uploads. Nothing happens when I take a pic.

When taking a pic I once got message that Smartcard service stopped working

### Expected behaviour
-Tell us what should happen
 
### Steps to reproduce
1. 
2. 
3. 

### Environment data
Android version:
7.0
Device model: 
Sony Xperia Z5 Compact, E5823
Stock or customized system:
Stock
Nextcloud app version:
1.4.2
Nextcloud server version:
ownCloud 9.1.1
#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

**Comment by mario** [comment]
Could you try:

https://github.com/nextcloud/android/raw/small-change/nextcloud-android-debug.apk

**Comment by clriis** [comment]
Sorry, but that link appears to be a 404

**Comment by mario** [comment]
@clriis https://github.com/nextcloud/android/blob/read-access/nextcloud-android-generic-debug.apk

**Comment by mario** [comment]
Also, if that doesn't work, try:

https://github.com/nextcloud/android/blob/fix-issue-with-wifi/nextcloud-android-generic-debug.apk?raw=true

**Comment by clriis** [comment]
Thanks. It now seems to be working

**Comment by mario** [comment]
@clriis what apk did you use? The "fix-issue-with-wifi" one?

**Comment by clriis** [comment]
I did install the "fix-issue-with-wifi" but also the other one and it did not make a difference. To me the difference seemed to show after an Xperia system update on April 10th.
