### ISSUE TITLE
Crash watching video

### ISSUE THREAD

**Issue by Blisk** [nextcloud/android#7546]
### Steps to reproduce
When I want to watch video in neextcloud app it crash everytime.
I tested that on 3 differend phones and it always crash with the same error.

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here

************ CAUSE OF ERROR ************ android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{adc3f8a u0 com.nextcloud.client/.media.PlayerService} at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2400) at android.os.Handler.dispatchMessage(Handler.java:110) at android.os.Looper.loop(Looper.java:219) at android.app.ActivityThread.main(ActivityThread.java:8347) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055) ************ APP INFORMATION ************ ID: com.nextcloud.client Version: 30140090 Build flavor: gplay ************ DEVICE INFORMATION ************ Brand: HUAWEI Device: HWVOG Model: VOG-L29 Id: HUAWEIVOG-L29 Product: VOG-L29EEA ************ FIRMWARE ************ SDK: 29 Release: 10 Incremental: 10.1.0.150C431 
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Will be fixed with 3.14.1, which is already available as a test version via play store beta program.
