### ISSUE TITLE
App Lock can be bypassed by using recents overview on Pixel 5

### ISSUE THREAD

**Issue by MarcelBochtler** [nextcloud/android#7550]
There is a pretty simple way to bypass the fingerprint/PIN app lock.
I disabled Smart Lock and this still works:

### Steps to reproduce
1. Setup App-PIN to System
2. Terminate Nextcloud app
3. Launch Nextcloud app
4. Do not unlock the app using the fingerprint scanner
5. Open the recent apps overview
6. Tap on the Nextcloud app in the overview

### Expected behaviour
- The app should still be locked and demand to unlock it via fingerprint/PIN

### Actual behaviour
- The app is unlocked and my files can be accessed

### Environment data
Android version: Android 11

Device model: Google Pixel 5

Stock or customized system: Stock

Nextcloud app version: 3.14.0 from Play Store

**Comment by tobiasKaminsky** [comment]
Please report these security issues via hackerone.com

In this case I tried to reproduce it and failed.
