### ISSUE TITLE
Cannot connect via Android App anymore - timeout

### ISSUE THREAD

**Issue by matejek** [nextcloud/android#7576]
### Steps to reproduce
1. cannot connect from any Android phone to my Nextcloud server - anymore
2. after storage-deletion, de-installation and re-install - no success
3. error message "der Server braucht zu lange für eine Antwort" => timeout

### Expected behaviour
should connect

### Actual behaviour
error message "der Server braucht zu lange für eine Antwort" => timeout
did work like a charm, .....
does work from any other client (web, Windows)

### Environment data
Android version: 10

Device model: Samsung S20Ulta5G SM-G988B/DS

Stock or customized system: no

Nextcloud app version: 3.14.0

Nextcloud server version: 20.0.2

Reverse proxy: letsencrypt

**Comment by tobiasKaminsky** [comment]
Do you have ipV6? And maybe not correctly configured?
With 3.14 ipv6 is preferred, if available.
It then times out if not correct reachable.

**Comment by matejek** [comment]
@tobiasKaminsky : you are right! I disabled IPV in my home-gateway-router (FritzBox) and I could work like before.
Looks like I have to sort out my IPv6 configuration - no idea why the standard configuration didn't work ootb.
