### ISSUE TITLE
File is not uploaded when it is shared by another app to Nextcloud

### ISSUE THREAD

**Issue by JorisBodin** [nextcloud/android#7587]
Hello :)

I test on emulator android 11, my pixel 5 android 11 and oneplus 8 android 10. Same problem.

![untitled](https://user-images.githubusercontent.com/2796439/100891564-ab273680-34b9-11eb-9cad-938cb13ec128.gif)

If i upload directly in app, no problem.

I test with `stable-3.14` and `master`
I couldn't find any other issue with this same problem.

**Comment by MariusMarek** [comment]
I am experiencing the same issue - Android 10, Nextcloud App Version 3.14.1

- sharing a file from e.g. google photo app (or camscanner which I use to scan PDFs) to nextcloud does not work
- same happens when using "upload content from other apps" in the NC app (error message translates to "error copying file to  temporary folder")
- using the "normal" upload function in NC app (and selecting any locally stored file using the browsing function of NC app) does work fine

**Comment by reekol** [comment]
I have the same issue - Android 10, NextCloud App 3.14.1
Share from other apps not working. Direct upload from Next Cloud App is working.

**Comment by AndyScherzinger** [comment]
same with `master` OP3T running Android 10

**Comment by pikpok** [comment]
I have the same issue with uploading file from another app on version 3.14.1, and I see this exception in logcat after tapping "Upload":
```Exception while copying content://[app bundle + file path] to temporary file
java.lang.IllegalArgumentException: column 'last_modified' does not exist. Available columns: [_data, mime_type, _display_name, _size]
	at android.database.AbstractCursor.getColumnIndexOrThrow(AbstractCursor.java:358)
	at android.database.CursorWrapper.getColumnIndexOrThrow(CursorWrapper.java:91)
	at com.owncloud.android.ui.asynctasks.CopyAndUploadContentUrisTask.doInBackground(CopyAndUploadContentUrisTask.java:156)
	at com.owncloud.android.ui.asynctasks.CopyAndUploadContentUrisTask.doInBackground(CopyAndUploadContentUrisTask.java:49)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
```

**Comment by dajusc** [comment]
Some app-format-combinations apparently still work.
On my Pixel 2 with vanilla Android 11 I am e.g. still able to share an URL from the chrome browser app as *.txt file, or a *.docx from Google Documents.

**Comment by FL550** [comment]
I can also confirm this issue on three different Android devices.

**Comment by rainer042** [comment]
Experiencing the same effect on a Samsung Galaxy S8 (Android 9) with Nextcloud 3.14.1 when sharing eg a photo to nextcloud for upload from the photo viewer. When selecting the very same file directly in Nextcloud for upload it works. I downloaded 3.14.0 and there the bug does not show up.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky also got reported on the forum, and as mentioned happens on master too

**Comment by aoyono** [comment]
Not sure if my comment will help, just adding myself to the pile of "same issue here" comments (Oneplus 6T, version 3.14.1).
As it's my first comment here, I am taking a second to say thanks for your work on this :)

**Comment by Gugiman** [comment]
Don't know if it helps because i have no clue about LogCat and App programming but on my rooted phone i get these lines when share files to nextcloud:

https://pastebin.com/Ntr4M4ka

Not everything seems relevant but look for yourself.

Hope it helps :)

**Comment by AndyScherzinger** [comment]
@Gugiman I'd say your log nails it:
```
12-09 14:51:31.635 E/CopyAndUploadContentUrisTask(31160): Exception while copying content://media/external/images/media/258150 to temporary file
12-09 14:51:31.635 E/CopyAndUploadContentUrisTask(31160): java.lang.IllegalArgumentException: column 'last_modified' does not exist. Available columns: [instance_id, duration, description, picasa_id, latitude, orientation, height, is_drm, bucket_display_name, owner_package_name, volume_name, date_modified, date_expires, _display_name, datetaken, mime_type, _id, _data, _hash, _size, title, width, longitude, is_trashed, group_id, document_id, is_pending, date_added, mini_thumb_magic, primary_directory, secondary_directory, isprivate, original_document_id, bucket_id, relative_path]
12-09 14:51:31.635 E/CopyAndUploadContentUrisTask(31160): 	at android.database.AbstractCursor.getColumnIndexOrThrow(AbstractCursor.java:352)
12-09 14:51:31.635 E/CopyAndUploadContentUrisTask(31160): 	at android.database.CursorWrapper.getColumnIndexOrThrow(CursorWrapper.java:91)
12-09 14:51:31.635 E/CopyAndUploadContentUrisTask(31160): 	at com.owncloud.android.ui.asynctasks.CopyAndUploadContentUrisTask.doInBackground(CopyAndUploadContentUrisTask.java:156)
12-09 14:51:31.635 E/CopyAndUploadContentUrisTask(31160): 	at com.owncloud.android.ui.asynctasks.CopyAndUploadContentUrisTask.doInBackground(CopyAndUploadContentUrisTask.java:49)
12-09 14:51:31.635 E/CopyAndUploadContentUrisTask(31160): 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
12-09 14:51:31.635 E/CopyAndUploadContentUrisTask(31160): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12-09 14:51:31.635 E/CopyAndUploadContentUrisTask(31160): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
12-09 14:51:31.635 E/CopyAndUploadContentUrisTask(31160): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-09 14:51:31.635 E/CopyAndUploadContentUrisTask(31160): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-09 14:51:31.635 E/CopyAndUploadContentUrisTask(31160): 	at java.lang.Thread.run(Thread.java:919)
12-09 14:51:31.659 D/FileActivity(31160): dismiss loading dialog
```

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky #7308 introduced this change. @hochwasser the SAF change for the last modified date crashes in case of files being shared via Android native share feaure, see stack trace in the post above. Any idea and/or time to fix? ❤️

**Comment by sm8ps** [comment]
Thank you so much for working on this!

**Comment by mkukulski** [comment]
Hi, issue is relay annoying more than lack of last modified time. Can you simply revert #7329 or easily fix it by using getColumnIndex instead of getColumnIndexOrThrow and then even last catch block would make sense
`if (lastModified != 0) {
                    try { ...}
catch (IllegalArgumentException e) {
                        Log_OC.e(TAG, "Could not change mtime of cacheFile, mtime is negativ: "+lastModified, e);`

or add this try catch around the mentioned getColumnIndexOr**Throw**  method

**Comment by MarkusPoh** [comment]
Same Problem on Huawei with Android 10.

**Comment by graste** [comment]
Most surprising thing is a missing error message. The sharing just doesn't lead to an upload. The share dialogue closes and instead of the usual short upload notification (depending on upload size/speed) the share dialogue is gone and no upload happened. This leads to surprises when one expects to find the file in one's nextcloud instance and it is missing.

**Comment by dajusc** [comment]
Uploading photos from the gallery app is literally the most often used function for me.
Downgrading to 3.14.0 via clean re-install was not very comfortable.

So the "high" label added four days ago is much appreciated @AndyScherzinger

In addition, if there is such thing as manual release tests, please consider adding this functionality to the list. 
It broke before (#3301) and imho should not break again...

**Comment by ChristianTacke** [comment]
UNTESTED, possible fix:
```diff
-                        lastModified = cursor.getLong(
-                            cursor.getColumnIndexOrThrow(
-                                DocumentsContract.Document.COLUMN_LAST_MODIFIED));
+                        Int32 column_index = cursor.getColumnIndex(
+                            DocumentsContract.Document.COLUMN_LAST_MODIFIED);
+                        if (column_index >= 0) {
+                            lastModified = cursor.getLong(column_index);
+                        }
```

**Comment by AndyScherzinger** [comment]
@ezaquarii opened a PR for the fix 🎉

**Comment by rimeraz** [comment]
I just updated Nextcloud client on my Android to 3.14.3 and now the sharing from an application to Nextcloud seems to be working again.

**Comment by sm8ps** [comment]
Confirming that version 3.14.3 from January 13th 2021 does work as expected on Android 10. Thanks a lot for taking care of this issue and for providing this useful application in general!

**Comment by ishmadrad** [comment]
It is possibile I have this problem on Android 12 smartphone and 2025 updated 3.30.7 Nextcloud app?
I'd love to share from Google Photos to Nextcloud app my pictures, but no Upload is starting...
