### ISSUE TITLE
Server isn't avaible

### ISSUE THREAD

**Issue by DanielSchwaeger** [nextcloud/android#7588]
### Steps to reproduce
1. Sign in with own Server
2. 
3. 

### Expected behaviour
- It funktions

### Actual behaviour
- Server isn't avaible (With other Divices it's running)

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 11

Device model: Samsung Galaxy S20 Ultra 5G (SM-G988B/DS)

Stock or customized system: Stock (Andoid 11)

Nextcloud app version:3.14.1

Nextcloud server version:?

Reverse proxy:?

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by modem** [comment]
There's not much information on this bug, but seems the same issue I'm having.

With the version 3.14.0 and 3.14.1, I can't add my server using an URL in the home wifi network, but it works if I use the IP address. It also works with the URL using the mobile network. 
I also have no issues with the Windows client, neither on Android connecting with the browser using the URL.

I tested with the previous version 3.13.1 and it works as expected, so the new version 3.14 introduced this issue.

**Comment by AndyScherzinger** [comment]
My guess: #7400 you are having an ipv6 config issue (likely with DNS records)

**Comment by modem** [comment]
My server had IPv6 deactivated, so I activated it and it still fails. Then I deactivated it, and removed the IPv6 address from the DuckDNS configuration and it works. Seems the app is having the issue, but maybe my ISP configuration also have some issue.
To be tested once the app has a workaround...

**Comment by tobiasKaminsky** [comment]
Thanks for replying, closing as it is dicussed in #7400
