### ISSUE TITLE
Video stream playback crash

### ISSUE THREAD

**Issue by citizenserious** [nextcloud/android#7590]
### Steps to reproduce
1. open Video inside the App for streaming (not downloaded)

### Expected behaviour
- the Video should stream

### Actual behaviour
- option 1. Video streams for a few seconds then the screen turns fully black and the APP crashes.
-  Option 2. Video streams if you tap the screen it turns black, it took a few seconds than the Video starts again and the the APP crashes.

### Can you reproduce this problem on https://try.nextcloud.com? 
--> Yes, i connected the test server via app password. Same result.

Reinstallation and/ or storage space and cache  clean didn't help.

#### Web server error log
```
not an server related issue
```

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{854ae8d u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1945)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140090
Build flavor: generic

same happens with the 3.13.1 RC2 Version

************ DEVICE INFORMATION ************
Brand: samsung
Device: starlte
Model: SM-G960F
Id: XX
Product: starltexx

same happens with another Samsung device.

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: XX

**Comment by tobiasKaminsky** [comment]
Please update to 3.14.1
