### ISSUE TITLE
************ CAUSE OF ERROR ************  java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.net.NetworkCapabilities.hasCapability(int)' on a null object reference 	at com.nextcloud.client.network.ConnectivityServiceImpl.getConnectivity(ConnectivityServiceImpl.java:121) 	at com.owncloud.android.utils.FilesSyncHelper.lambda$restartJobsIfNeeded$0(FilesSyncHelper.java:207) 	at com.owncloud.android.utils.-$$Lambda$FilesSyncHelper$78U1WN_nzr5HiGIrRZMThSEamz8.run(Unknown Source:10) 	at java.lang.Thread.run(Thread.java:764)  ************ APP INFORMATION ************ ID: com.nextcloud.android.beta Version: 20201127 Build flavor: versionDev  ************ DEVICE INFORMATION ************ Brand: bq Device: yamcha Model: Aquaris U2 Id: OPM1.171019.026 Product: yamcha  ************ FIRMWARE ************ SDK: 27 Release: 8.1.0 Incremental: 2011

### ISSUE THREAD

**Issue by rafa-oss** [nextcloud/android#7595]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
This is fixed with 20201202 dev version, please upgrade.
