### ISSUE TITLE
Change allow editig does not effect 

### ISSUE THREAD

**Issue by weinic** [nextcloud/android#7601]
The Button " Allow Editig " takes not effect.
I must deaktivate the Create and Delete button, then the Allow editig is also disabled.
The allow editig button disabled not automatic the create and delete Button.

![Screenshot_20201204-121855__02](https://user-images.githubusercontent.com/57099502/101158790-a1721000-362c-11eb-979d-808a14ceec23.jpg)

Android App Version 3.14.1

**Comment by tobiasKaminsky** [comment]
This sharing interface looks old.
Are you sure you use 3.14.1?
