### ISSUE TITLE
issue with upload pictures frome android

### ISSUE THREAD

**Issue by caribou90** [nextcloud/android#7606]
Hello
i have a problem from the app andoird nextcloud to upload pictures (android10) with the last app. i use wifi and @ip of the server

on nextcloud.log i have this informations but i not sure if itwas exactly the issue.

Thanks for your assistance.

_```
"reqId":"X8ptc5wth-QDtbSZ2oatfAAAAAg","level":2,"time":"2020-12-04T17:10:11+00:00","remoteAddr":"192.168.1.74","user":"--","app":"no app in context","method":"PUT","url":"/remote.php/dav/uploads/stephane/87252a8bdbdf37ed892e9e2e2f9c82c7/0000000000000000-0000000006572782","message":"Temporary directory /var/www/nextcloud/data/tmp is not present or writable","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.14.1","version":"19.0.5.2"}
{"reqId":"X8ptc5wth-QDtbSZ2oatfAAAAAg","level":2,"time":"2020-12-04T17:10:11+00:00","remoteAddr":"192.168.1.74","user":"--","app":"no app in context","method":"PUT","url":"/remote.php/dav/uploads/stephane/87252a8bdbdf37ed892e9e2e2f9c82c7/0000000000000000-0000000006572782","message":"Temporary directory /var/www/nextcloud/data/tmp is not present or writable","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.14.1","version":"19.0.5.2"}
{"reqId":"X8ptc5wth-QDtbSZ2oatfAAAAAg","level":2,"time":"2020-12-04T17:10:11+00:00","remoteAddr":"192.168.1.74","user":"--","app":"no app in context","method":"PUT","url":"/remote.php/dav/uploads/stephane/87252a8bdbdf37ed892e9e2e2f9c82c7/0000000000000000-0000000006572782","message":"Temporary directory /var/www/nextcloud/data/tmp is not present or writable","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.14.1","version":"19.0.5.2"}
{"reqId":"X8ptc7uQ@lWnftV8z7W2EAAAAE4","level":2,"time":"2020-12-04T17:10:11+00:00","remoteAddr":"192.168.1.74","user":"--","app":"no app in context","method":"GET","url":"/index.php/204","message":"Temporary directory /var/www/nextcloud/data/tmp is not present or writable","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.14.1","version":"19.0.5.2"}
{"reqId":"X8ptc7uQ@lWnftV8z7W2EAAAAE4","level":2,"time":"2020-12-04T17:10:11+00:00","remoteAddr":"192.168.1.74","user":"--","app":"no app in context","method":"GET","url":"/index.php/204","message":"Temporary directory /var/www/nextcloud/data/tmp is not present or writable","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.14.1","version":"19.0.5.2"}
{"reqId":"X8ptc7uQ@lWnftV8z7W2EAAAAE4","level":2,"time":"2020-12-04T17:10:11+00:00","remoteAddr":"192.168.1.74","user":"--","app":"no app in context","method":"GET","url":"/index.php/204","message":"Temporary directory /var/www/nextcloud/data/tmp is not present or writable","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.14.1","version":"19.0.5.2"}
{"reqId":"X8ptc5wth-QDtbSZ2oatfAAAAAg","level":3,"time":"2020-12-04T17:10:11+00:00","remoteAddr":"192.168.1.74","user":"stephane","app":"PHP","method":"PUT","url":"/remote.php/dav/uploads/stephane/87252a8bdbdf37ed892e9e2e2f9c82c7/0000000000000000-0000000006572782","message":{"Exception":"Error","Message":"fread(): file created in the system's temporary directory at /var/www/nextcloud/3rdparty/icewind/streams/src/Wrapper.php#91","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[8,"fread(): file created in the system's temporary directory","/var/www/nextcloud/3rdparty/icewind/streams/src/Wrapper.php",91,{"count":8192}]},{"file":"/var/www/nextcloud/3rdparty/icewind/streams/src/Wrapper.php","line":91,"function":"fread","args":[null,8192]},{"file":"/var/www/nextcloud/lib/private/Files/Stream/HashWrapper.php","line":64,"function":"stream_read","class":"Icewind\\Streams\\Wrapper","type":"->","args":[8192]},{"function":"stream_read","class":"OC\\Files\\Stream\\HashWrapper","type":"->","args":[8192]},{"file":"/var/www/nextcloud/3rdparty/icewind/streams/src/Wrapper.php","line":91,"function":"fread","args":[null,8192]},{"file":"/var/www/nextcloud/lib/private/Files/Stream/HashWrapper.php","line":64,"function":"stream_read","class":"Icewind\\Streams\\Wrapper","type":"->","args":[8192]},{"function":"stream_read","class":"OC\\Files\\Stream\\HashWrapper","type":"->","args":[8192]},{"file":"/var/www/nextcloud/3rdparty/icewind/streams/src/Wrapper.php","line":91,"function":"fread","args":[null,8192]},{"file":"/var/www/nextcloud/lib/private/Files/Stream/HashWrapper.php","line":64,"function":"stream_read","class":"Icewind\\Streams\\Wrapper","type":"->","args":[8192]},{"function":"stream_read","class":"OC\\Files\\Stream\\HashWrapper","type":"->","args":[8192]},{"file":"/var/www/nextcloud/3rdparty/icewind/streams/src/Wrapper.php","line":91,"function":"fread","args":[null,8192]},{"file":"/var/www/nextcloud/3rdparty/icewind/streams/src/CallbackWrapper.php","line":98,"function":"stream_read","class":"Icewind\\Streams\\Wrapper","type":"->","args":[8192]},{"function":"stream_read","class":"Icewind\\Streams\\CallbackWrapper","type":"->","args":[8192]},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Local.php","line":559,"function":"file_put_contents","args":["/var/nextcloud/data/stephane/uploads/87252a8bdbdf37ed892e9e2e2f9c82c7/0000000000000000-0000000006572782.ocTransferId243179944.part",null]},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php","line":631,"function":"writeStream","class":"OC\\Files\\Storage\\Local","type":"->","args":["uploads/87252a8bdbdf37ed892e9e2e2f9c82c7/0000000000000000-0000000006572782.ocTransferId243179944.part",null,null]},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php","line":206,"function":"writeStream","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["uploads/87252a8bdbdf37ed892e9e2e2f9c82c7/0000000000000000-0000000006572782.ocTransferId243179944.part",null]},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php","line":154,"function":"put","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->","args":[null]},{"file":"/var/www/nextcloud/apps/dav/lib/Upload/UploadFolder.php","line":46,"function":"createFile","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->","args":["0000000000000000-0000000006572782",null]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1104,"function":"createFile","class":"OCA\\DAV\\Upload\\UploadFolder","type":"->","args":["0000000000000000-0000000006572782",null]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":527,"function":"createFile","class":"Sabre\\DAV\\Server","type":"->","args":["uploads/stephane/87252a8bdbdf37ed892e9e2e2f9c82c7/0000000000000000-0000000006572782",null,null]},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpPut","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":474,"function":"emit","class":"Sabre\\DAV\\Server","type":"->","args":["method:PUT",[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":251,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":319,"function":"start","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/dav/lib/Server.php","line":320,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/remote.php","line":167,"args":["/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.14.1","version":"19.0.5.2"}
{"reqId":"X8ptc5wth-QDtbSZ2oatfAAAAAg","level":3,"time":"2020-12-04T17:10:11+00:00","remoteAddr":"192.168.1.74","user":"stephane","app":"PHP","method":"PUT","url":"/remote.php/dav/uploads/stephane/87252a8bdbdf37ed892e9e2e2f9c82c7/0000000000000000-0000000006572782","message":{"Exception":"Error","Message":"fread(): Unable to create temporary file, Check permissions in temporary files directory. at /var/www/nextcloud/3rdparty/icewind/streams/src/Wrapper.php#91","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[2,"fread(): Unable to create temporary file, Check permissions in temporary files directory.","/var/www/nextcloud/3rdparty/icewind/streams/src/Wrapper.php",91,{"count":8192}]},{"file":"/var/www/nextcloud/3rdparty/icewind/streams/src/Wrapper.php","line":91,"function":"fread","args":[null,8192]},{"file":"/var/www/nextcloud/lib/private/Files/Stream/HashWrapper.php","line":64,"function":"stream_read","class":"Icewind\\Streams\\Wrapper","type":"->","args":[8192]},{"function":"stream_read","class":"OC\\Files\\Stream\\HashWrapper","type":"->","args":[8192]},{"file":"/var/www/nextcloud/3rdparty/icewind/streams/src/Wrapper.php","line":91,"function":"fread","args":[null,8192]},{"file":"/var/www/nextcloud/lib/private/Files/Stream/HashWrapper.php","line":64,"function":"stream_read","class":"Icewind\\Streams\\Wrapper","type":"->","args":[8192]},{"function":"stream_read","class":"OC\\Files\\Stream\\HashWrapper","type":"->","args":[8192]},{"file":"/var/www/nextcloud/3rdparty/icewind/streams/src/Wrapper.php","line":91,"function":"fread","args":[null,8192]},{"file":"/var/www/nextcloud/lib/private/Files/Stream/HashWrapper.php","line":64,"function":"stream_read","class":"Icewind\\Streams\\Wrapper","type":"->","args":[8192]},{"function":"stream_read","class":"OC\\Files\\Stream\\HashWrapper","type":"->","args":[8192]},{"file":"/var/www/nextcloud/3rdparty/icewind/streams/src/Wrapper.php","line":91,"function":"fread","args":[null,8192]},{"file":"/var/www/nextcloud/3rdparty/icewind/streams/src/CallbackWrapper.php","line":98,"function":"stream_read","class":"Icewind\\Streams\\Wrapper","type":"->","args":[8192]},{"function":"stream_read","class":"Icewind\\Streams\\CallbackWrapper","type":"->","args":[8192]},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Local.php","line":559,"function":"file_put_contents","args":["/var/nextcloud/data/stephane/uploads/87252a8bdbdf37ed892e9e2e2f9c82c7/0000000000000000-0000000006572782.ocTransferId243179944.part",null]},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php","line":631,"function":"writeStream","class":"OC\\Files\\Storage\\Local","type":"->","args":["uploads/87252a8bdbdf37ed892e9e2e2f9c82c7/0000000000000000-0000000006572782.ocTransferId243179944.part",null,null]},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php","line":206,"function":"writeStream","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["uploads/87252a8bdbdf37ed892e9e2e2f9c82c7/0000000000000000-0000000006572782.ocTransferId243179944.part",null]},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php","line":154,"function":"put","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->","args":[null]},{"file":"/var/www/nextcloud/apps/dav/lib/Upload/UploadFolder.php","line":46,"function":"createFile","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->","args":["0000000000000000-0000000006572782",null]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1104,"function":"createFile","class":"OCA\\DAV\\Upload\\UploadFolder","type":"->","args":["0000000000000000-0000000006572782",null]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":527,"function":"createFile","class":"Sabre\\DAV\\Server","type":"->","args":["uploads/stephane/87252a8bdbdf37ed892e9e2e2f9c82c7/0000000000000000-0000000006572782",null,null]},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpPut","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":474,"function":"emit","class":"Sabre\\DAV\\Server","type":"->","args":["method:PUT",[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":251,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":319,"function":"start","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/dav/lib/Server.php","line":320,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/remote.php","line":167,"args":["/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.14.1","version":"19.0.5.2"}
{"reqId":"X8ptc5wth-QDtbSZ2oatfAAAAAg","level":3,"time":"2020-12-04T17:10:11+00:00","remoteAddr":"192.168.1.74","user":"stephane","app":"no app in context","method":"PUT","url":"/remote.php/dav/uploads/stephane/87252a8bdbdf37ed892e9e2e2f9c82c7/0000000000000000-0000000006572782","message":{"Exception":"Sabre\\DAV\\Exception\\BadRequest","Message":"Expected filesize of 6572782 bytes but read (from Nextcloud client) and wrote (to Nextcloud storage) 8192 bytes. Could either be a network problem on the sending side or a problem writing to the storage on the server side.","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php","line":154,"function":"put","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->","args":[null]},{"file":"/var/www/nextcloud/apps/dav/lib/Upload/UploadFolder.php","line":46,"function":"createFile","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->","args":["0000000000000000-0000000006572782",null]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1104,"function":"createFile","class":"OCA\\DAV\\Upload\\UploadFolder","type":"->","args":["0000000000000000-0000000006572782",null]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":527,"function":"createFile","class":"Sabre\\DAV\\Server","type":"->","args":["uploads/stephane/87252a8bdbdf37ed892e9e2e2f9c82c7/0000000000000000-0000000006572782",null,null]},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpPut","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":474,"function":"emit","class":"Sabre\\DAV\\Server","type":"->","args":["method:PUT",[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":251,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":319,"function":"start","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/dav/lib/Server.php","line":320,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/remote.php","line":167,"args":["/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php","Line":245,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.14.1","version":"19.0.5.2"}
{"reqId":"X8ptc5wth-QDtbSZ2oatfAAAAAg","level":4,"time":"2020-12-04T17:10:11+00:00","remoteAddr":"192.168.1.74","user":"stephane","app":"webdav","method":"PUT","url":"/remote.php/dav/uploads/stephane/87252a8bdbdf37ed892e9e2e2f9c82c7/0000000000000000-0000000006572782","message":{"Exception":"Sabre\\DAV\\Exception\\BadRequest","Message":"Expected filesize of 6572782 bytes but read (from Nextcloud client) and wrote (to Nextcloud storage) 8192 bytes. Could either be a network problem on the sending side or a problem writing to the storage on the server side.","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php","line":154,"function":"put","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->","args":[null]},{"file":"/var/www/nextcloud/apps/dav/lib/Upload/UploadFolder.php","line":46,"function":"createFile","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->","args":["0000000000000000-0000000006572782",null]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1104,"function":"createFile","class":"OCA\\DAV\\Upload\\UploadFolder","type":"->","args":["0000000000000000-0000000006572782",null]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":527,"function":"createFile","class":"Sabre\\DAV\\Server","type":"->","args":["uploads/stephane/87252a8bdbdf37ed892e9e2e2f9c82c7/0000000000000000-0000000006572782",null,null]},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpPut","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":474,"function":"emit","class":"Sabre\\DAV\\Server","type":"->","args":["method:PUT",[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":251,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":319,"function":"start","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/dav/lib/Server.php","line":320,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/remote.php","line":167,"args":["/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php","Line":245,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.14.1","version":"19.0.5.2"}
{"reqId":"X8ptc5wth-QDtbSZ2oatfAAAAAg","level":3,"time":"2020-12-04T17:10:11+00:00","remoteAddr":"192.168.1.74","user":"stephane","app":"PHP","method":"PUT","url":"/remote.php/dav/uploads/stephane/87252a8bdbdf37ed892e9e2e2f9c82c7/0000000000000000-0000000006572782","message":{"Exception":"Error","Message":"Cannot modify header information - headers already sent by (output started at /var/www/nextcloud/3rdparty/sabre/http/lib/Sapi.php:132) at /var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php#690","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[2,"Cannot modify header information - headers already sent by (output started at /var/www/nextcloud/3rdparty/sabre/http/lib/Sapi.php:132)","/var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php",690,{"string":"X-Hash-SHA256: e721f1f5e890ddc087b9dd0617e4dfdc9c18ddc9f18c67b2fcbe3744fd1a2682"}]},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php","line":690,"function":"header","args":["X-Hash-SHA256: e721f1f5e890ddc087b9dd0617e4dfdc9c18ddc9f18c67b2fcbe3744fd1a2682"]},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php","line":194,"function":"header","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->","args":["X-Hash-SHA256: e721f1f5e890ddc087b9dd0617e4dfdc9c18ddc9f18c67b2fcbe3744fd1a2682"]},{"function":"OCA\\DAV\\Connector\\Sabre\\{closure}","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/Files/Stream/HashWrapper.php","line":71,"function":"call_user_func","args":[{"__class__":"Closure"},"*** sensitive parameter replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":319,"function":"stream_close","class":"OC\\Files\\Stream\\HashWrapper","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/dav/lib/Server.php","line":320,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/remote.php","line":167,"args":["/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.14.1","version":"19.0.5.2"}
{"reqId":"X8ptc5wth-QDtbSZ2oatfAAAAAg","level":3,"time":"2020-12-04T17:10:11+00:00","remoteAddr":"192.168.1.74","user":"stephane","app":"PHP","method":"PUT","url":"/remote.php/dav/uploads/stephane/87252a8bdbdf37ed892e9e2e2f9c82c7/0000000000000000-0000000006572782","message":{"Exception":"Error","Message":"Cannot modify header information - headers already sent by (output started at /var/www/nextcloud/3rdparty/sabre/http/lib/Sapi.php:132) at /var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php#690","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[2,"Cannot modify header information - headers already sent by (output started at /var/www/nextcloud/3rdparty/sabre/http/lib/Sapi.php:132)","/var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php",690,{"string":"X-Hash-SHA1: 7c8be44e6b8ac95865c11895df5ea665710f7ddb"}]},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php","line":690,"function":"header","args":["X-Hash-SHA1: 7c8be44e6b8ac95865c11895df5ea665710f7ddb"]},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php","line":191,"function":"header","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->","args":["X-Hash-SHA1: 7c8be44e6b8ac95865c11895df5ea665710f7ddb"]},{"function":"OCA\\DAV\\Connector\\Sabre\\{closure}","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/Files/Stream/HashWrapper.php","line":71,"function":"call_user_func","args":[{"__class__":"Closure"},"*** sensitive parameter replaced ***"]},{"function":"stream_close","class":"OC\\Files\\Stream\\HashWrapper","type":"->","args":[]},{"file":"/var/www/nextcloud/3rdparty/icewind/streams/src/Wrapper.php","line":132,"function":"fclose","args":[null]},{"file":"/var/www/nextcloud/lib/private/Files/Stream/HashWrapper.php","line":75,"function":"stream_close","class":"Icewind\\Streams\\Wrapper","type":"->","args":[]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":319,"function":"stream_close","class":"OC\\Files\\Stream\\HashWrapper","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/dav/lib/Server.php","line":320,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/remote.php","line":167,"args":["/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.14.1","version":"19.0.5.2"}
{"reqId":"X8ptc5wth-QDtbSZ2oatfAAAAAg","level":3,"time":"2020-12-04T17:10:11+00:00","remoteAddr":"192.168.1.74","user":"stephane","app":"PHP","method":"PUT","url":"/remote.php/dav/uploads/stephane/87252a8bdbdf37ed892e9e2e2f9c82c7/0000000000000000-0000000006572782","message":{"Exception":"Error","Message":"Cannot modify header information - headers already sent by (output started at /var/www/nextcloud/3rdparty/sabre/http/lib/Sapi.php:132) at /var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php#690","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[2,"Cannot modify header information - headers already sent by (output started at /var/www/nextcloud/3rdparty/sabre/http/lib/Sapi.php:132)","/var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php",690,{"string":"X-Hash-MD5: 574e5ff6d90ded5bdc618ab8644e2847"}]},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php","line":690,"function":"header","args":["X-Hash-MD5: 574e5ff6d90ded5bdc618ab8644e2847"]},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php","line":188,"function":"header","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->","args":["X-Hash-MD5: 574e5ff6d90ded5bdc618ab8644e2847"]},{"function":"OCA\\DAV\\Connector\\Sabre\\{closure}","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/Files/Stream/HashWrapper.php","line":71,"function":"call_user_func","args":[{"__class__":"Closure"},"*** sensitive parameter replaced ***"]},{"function":"stream_close","class":"OC\\Files\\Stream\\HashWrapper","type":"->","args":[]},{"file":"/var/www/nextcloud/3rdparty/icewind/streams/src/Wrapper.php","line":132,"function":"fclose","args":[null]},{"file":"/var/www/nextcloud/lib/private/Files/Stream/HashWrapper.php","line":75,"function":"stream_close","class":"Icewind\\Streams\\Wrapper","type":"->","args":[]},{"function":"stream_close","class":"OC\\Files\\Stream\\HashWrapper","type":"->","args":[]},{"file":"/var/www/nextcloud/3rdparty/icewind/streams/src/Wrapper.php","line":132,"function":"fclose","args":[null]},{"file":"/var/www/nextcloud/lib/private/Files/Stream/HashWrapper.php","line":75,"function":"stream_close","class":"Icewind\\Streams\\Wrapper","type":"->","args":[]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":319,"function":"stream_close","class":"OC\\Files\\Stream\\HashWrapper","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/dav/lib/Server.php","line":320,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/remote.php","line":167,"args":["/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.14.1","version":"19.0.5.2"}
```_

**Comment by tobiasKaminsky** [comment]
> Temporary directory /var/www/nextcloud/data/tmp is not present or writable"

This seems to be a server related issue, please ask over at help.nextcloud.com
