### ISSUE TITLE
When using the app to connect to the nextcloud server, the authorization cannot be completed.

### ISSUE THREAD

**Issue by expoli** [nextcloud/android#7609]
### Steps to reproduce
1. Enter server address
2. new drivers login
3. Authorized login

### Expected behaviour
- login complete

### Actual behaviour
- it always loading..

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 9

Device model: 

Stock or customized system:

Nextcloud app version:3.14.1

Nextcloud server version:20.0.2

Reverse proxy:nginx

#### Web server error log
```
No errors

172.23.0.1 - - [05/Dec/2020:01:58:20 +0000] "GET /ocs/v2.php/search/providers?from=%2Fsettings%2Fuser%2Fsecurity HTTP/1.1" 200 248 "-" "Mozilla/5.0 (Linux; Android 9; MI 6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Mobile Safari/537.36" "172.23.0.1"
172.23.0.1 - - [05/Dec/2020:01:58:21 +0000] "GET /ocs/v2.php/apps/user_status/api/v1/user_status HTTP/1.1" 200 151 "-" "Mozilla/5.0 (Linux; Android 9; MI 6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Mobile Safari/537.36" "172.23.0.1"
172.23.0.1 - - [05/Dec/2020:01:58:50 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Linux; Android 9; MI 6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Mobile Safari/537.36" "172.23.0.1"
172.23.0.1 - - [05/Dec/2020:01:59:20 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Linux; Android 9; MI 6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Mobile Safari/537.36" "172.23.0.1"
172.23.0.1 - - [05/Dec/2020:01:59:50 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Linux; Android 9; MI 6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Mobile Safari/537.36" "172.23.0.1"
172.23.0.1 - - [05/Dec/2020:02:00:20 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Linux; Android 9; MI 6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Mobile Safari/537.36" "172.23.0.1"
172.23.0.1 - - [05/Dec/2020:02:00:50 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Linux; Android 9; MI 6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Mobile Safari/537.36" "172.23.0.1"
172.23.0.1 - - [05/Dec/2020:02:01:20 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Linux; Android 9; MI 6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Mobile Safari/537.36" "172.23.0.1"
172.23.0.1 - - [05/Dec/2020:02:01:51 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Linux; Android 9; MI 6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Mobile Safari/537.36" "172.23.0.1"
172.23.0.1 - - [05/Dec/2020:02:02:20 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Linux; Android 9; MI 6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Mobile Safari/537.36" "172.23.0.1"
172.23.0.1 - - [05/Dec/2020:02:02:50 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Linux; Android 9; MI 6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Mobile Safari/537.36" "172.23.0.1"
172.23.0.1 - - [05/Dec/2020:02:03:20 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Linux; Android 9; MI 6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Mobile Safari/537.36" "172.23.0.1"
172.23.0.1 - - [05/Dec/2020:02:03:21 +0000] "PUT /apps/user_status/heartbeat HTTP/1.1" 204 0 "-" "Mozilla/5.0 (Linux; Android 9; MI 6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Mobile Safari/537.36" "172.23.0.1"
172.23.0.1 - - [05/Dec/2020:02:03:21 +0000] "GET /ocs/v2.php/apps/user_status/api/v1/user_status HTTP/1.1" 200 151 "-" "Mozilla/5.0 (Linux; Android 9; MI 6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Mobile Safari/537.36" "172.23.0.1"
```

#### Nextcloud log (data/nextcloud.log)
```
172.22.0.6 -  05/Dec/2020:01:58:04 +0000 "GET /index.php" 200
172.22.0.6 -  05/Dec/2020:01:58:05 +0000 "GET /index.php" 200
172.22.0.6 -  05/Dec/2020:01:58:06 +0000 "GET /ocs/v2.php" 200
172.22.0.6 -  05/Dec/2020:01:58:06 +0000 "GET /index.php" 304
172.22.0.6 -  05/Dec/2020:01:58:06 +0000 "PUT /index.php" 204
172.22.0.6 -  05/Dec/2020:01:58:06 +0000 "GET /ocs/v2.php" 200
172.22.0.6 -  05/Dec/2020:01:58:06 +0000 "GET /index.php" 200
172.22.0.6 -  05/Dec/2020:01:58:06 +0000 "GET /ocs/v2.php" 200
172.22.0.6 -  05/Dec/2020:01:58:18 +0000 "GET /index.php" 200
172.22.0.6 -  05/Dec/2020:01:58:19 +0000 "GET /ocs/v2.php" 200
172.22.0.6 -  05/Dec/2020:01:58:20 +0000 "PUT /index.php" 204
172.22.0.6 -  05/Dec/2020:01:58:20 +0000 "GET /ocs/v2.php" 200
172.22.0.6 -  05/Dec/2020:01:58:21 +0000 "GET /ocs/v2.php" 200
172.22.0.6 -  05/Dec/2020:01:58:50 +0000 "GET /ocs/v2.php" 304
172.22.0.6 -  05/Dec/2020:01:59:20 +0000 "GET /ocs/v2.php" 304
172.22.0.6 -  05/Dec/2020:01:59:50 +0000 "GET /ocs/v2.php" 304
172.22.0.6 -  05/Dec/2020:02:00:20 +0000 "GET /ocs/v2.php" 304
172.22.0.6 -  05/Dec/2020:02:00:50 +0000 "GET /ocs/v2.php" 304
172.22.0.6 -  05/Dec/2020:02:01:20 +0000 "GET /ocs/v2.php" 304
172.22.0.6 -  05/Dec/2020:02:01:50 +0000 "GET /ocs/v2.php" 304
172.22.0.6 -  05/Dec/2020:02:02:20 +0000 "GET /ocs/v2.php" 304
172.22.0.6 -  05/Dec/2020:02:02:50 +0000 "GET /ocs/v2.php" 304
172.22.0.6 -  05/Dec/2020:02:03:20 +0000 "GET /ocs/v2.php" 304
172.22.0.6 -  05/Dec/2020:02:03:21 +0000 "PUT /index.php" 204
172.22.0.6 -  05/Dec/2020:02:03:21 +0000 "GET /ocs/v2.php" 200
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

There's the screenshot

![Screenshot_2020-12-05-09-57-45-606_com.nextcloud.client.jpg](https://user-images.githubusercontent.com/31023767/101230794-6cc09000-36e2-11eb-91e2-17a644d9dcdf.jpg)

![Screenshot_2020-12-05-10-14-08-109_com.miui.gallery.jpg](https://user-images.githubusercontent.com/31023767/101230821-ac877780-36e2-11eb-86b5-4b590441131c.jpg)

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky any hints? It seems the redirects don't work (server-side issue) and so we never return to the app but stay within the web UI.

**Comment by expoli** [comment]
> @tobiasKaminsky any hints? It seems the redirects don't work (server-side issue) and so we never return to the app but stay within the web UI.

I don't know why, today when I tried again, I found that I scan the QR codes, I can login success.

The nextcloud app version is 3.14.1.

**Comment by tobiasKaminsky** [comment]
No idea…
Can you create us a test account, test if the problem occurs also there and if so send the credentials to tobias at nextcloud dot com with a reference to this issue?

**Comment by expoli** [comment]
sorry! Because I can't resolve it, so I uninstalled it.

It has occupied me for a long time, and nextcloud's webdav is not very convenient to use, and it feels that it runs too slowly.

Thank you very much for your reply.

I will close this issue.

**Comment by fungos** [comment]
- Ubuntu 18.04.5 LTS with NextCloud 20.0.4snap2.

I got the same issue after installing a reverse proxy nginx to be public facing with different servers in the same machine, so nginx could redirect to the correct service (blog, nextcloud, others) based on subdomains and then keeping a unified front with the same ssl certificate.

During this transition, I had to disable the SSL on the nextcloud server as internally from public facing NGINX SSL to NextCloud SSL is not needed. This is where the issue appeared, nextcloud server is just plainly refusing login on HTTP for some reason, it keeps redirecting to itself. Reenabling SSL on the server fixed the issue.

Unfortunately, this nextcloud issues makes it unusable for me and I just uninstalled everything. But the information is there, very easy to reproduce.

**Comment by Tameiki** [comment]
>     * Ubuntu 18.04.5 LTS with NextCloud 20.0.4snap2.
> 
> 
> I got the same issue after installing a reverse proxy nginx to be public facing with different servers in the same machine, so nginx could redirect to the correct service (blog, nextcloud, others) based on subdomains and then keeping a unified front with the same ssl certificate.
> 
> During this transition, I had to disable the SSL on the nextcloud server as internally from public facing NGINX SSL to NextCloud SSL is not needed. This is where the issue appeared, nextcloud server is just plainly refusing login on HTTP for some reason, it keeps redirecting to itself. Reenabling SSL on the server fixed the issue.
> 
> Unfortunately, this nextcloud issues makes it unusable for me and I just uninstalled everything. But the information is there, very easy to reproduce.

Hello,

Same here. Behind a nginx reverse proxy to have https and few websites on the same machine.
I can use the web version without problem, but can't connect via any app. (nextcloud android, nextcloud talk, nextcloud notes, etc...).
But I can connect to it when I'm at home, on the same network, via http, directly on the http port of the nextcloud. (not the proxy).

Did someone found a way to fix this ?
Maybe Nextcloud checking which proto is used, and mess up with http answer on https request in the app ?

**Comment by AndyScherzinger** [comment]
@Tameiki because the qr code likely also uses your local address? Did you check e.g. https://help.nextcloud.com/t/solved-android-client-grant-access-freeze-android-client-cant-create-account-on-device/88693 (override config param since you use a reverse proxy?)

**Comment by Tameiki** [comment]
> @Tameiki because the qr code likely also uses your local address? Did you check e.g. https://help.nextcloud.com/t/solved-android-client-grant-access-freeze-android-client-cant-create-account-on-device/88693 (override config param since you use a reverse proxy?)

Hello,
I used the QRcode on mobile network (not on WiFi).
On mobile network, I can't connect via server address > login/password > Authorize new device (as shown by expoli). But if I scan the QRcode, it immediately connect on it.


`<?php
$CONFIG = array (
  'htaccess.RewriteBase' => '/',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/html/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/var/www/html/custom_apps',
      'url' => '/custom_apps',
      'writable' => true,
    ),
  ),
  'instanceid' => 'Well no',
  'passwordsalt' => 'Well no',
  'secret' => 'Well no',
  'trusted_domains' => 
  array (
    0 => 'nextcloud.DOMAIN.TLD',
    1 => '192.168.1.100:803',
    2 => '192.168.1.100',
  ),
  'datadirectory' => '/var/www/html/data',
  'dbtype' => 'sqlite3',
  'version' => '20.0.6.1',
  'overwrite.cli.url' => 'https://nextcloud.DOMAIN.TLD',
  'installed' => true,
  'maintenance' => false,
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'ssl',
  'mail_sendmailmode' => 'smtp',
  'mail_from_address' => 'Well no',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_domain' => 'Well no',
  'mail_smtphost' => 'Well no',
  'mail_smtpauth' => 1,
  'mail_smtpport' => '465',
  'mail_smtpname' => 'Well no',
  'mail_smtppassword' => 'Well no',
  'loglevel' => 2,
);
`

**Comment by Tameiki** [comment]
GOT IT !
@expoli @AndyScherzinger 

Working with 'overwriteprotocol' => 'https', , as mention on [this link](https://help.nextcloud.com/t/android-app-cant-connect-to-my-instance-on-kubernetes/88495)
![image](https://user-images.githubusercontent.com/17551010/107519037-065b6080-6bb0-11eb-8b16-e1fc11698ac4.png)
