### ISSUE TITLE
Android auto upload doesn't do anything

### ISSUE THREAD

**Issue by CharlesKrzysik** [nextcloud/android#761]
### Actual behaviour
Enabled auto upload to nextcloud server

### Expected behaviour
pictures are shown in nextcloud nothing happens
 
### Steps to reproduce
1. Configure
2. Take a picture
3. 

### Environment data
Android version: 7.1.1 February security

Device model: Pixel XL and a Nexus 5X 

Stock or customized system: Stock

Nextcloud app version: 1.4.2

Nextcloud server version: 11.0.1

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

**Comment by shieldwed** [comment]
Did you configure Nextcloud to upload only on Wi-Fi?

**Comment by CharlesKrzysik** [comment]
Yes exactly. My data plan is rather limited:-(. Anything I can change ?

**Comment by shieldwed** [comment]
I can share you my experiences:
  * If you switch of uploading via Wi-Fi only, it is going to work
  * If you stick with your configuration and restart your phone, the photos will be uploaded (if you got Wi-Fi connection)
Therefore it seems to me like Nextcloud is not receiving notifications on when Wi-Fi connections become available, because if you open the uploads view of Nextcloud, you'll see them "waiting" for something.

**Comment by CharlesKrzysik** [comment]
you're right this works. How do I get this fixed for wifi though?

**Comment by shieldwed** [comment]
Well, I guess, there is little you can do to fix this (except if you are a developer 😉). Since we are experiencing the same issue, it might be a bug in the software. So far, I cannot relate it to any other open bug for the auto upload.

### Environment data
  * Android version: 7.0 March 1, 2017 Security patch level
  * Device model: Sony Xperia XZ
  * Stock or customized system: Stock
  * Nextcloud app version: 1.4.2
  * Nextcloud server version: 11.0.2

**Comment by xadox-1st** [comment]
Same for me. WiFi uploads are only done after rebooting the device.

**Comment by mario** [comment]
Do you have the app installed on SD card by any chance?

**Comment by CharlesKrzysik** [comment]
No. Internally only.

Sent via Pixel XL

On Mar 22, 2017 4:27 PM, Mario Đanić <notifications@github.com> wrote:

Do you have the app installed on SD card by any chance?

**Comment by mario** [comment]
Wish I had access to the device to test :-/

Anyway, will have a test build for you soon...

**Comment by mario** [comment]
Please try this and let me know. Thanks.

https://github.com/nextcloud/android/blob/new-branched/nextcloud-android-generic-debug.apk?raw=true

**Comment by shieldwed** [comment]
Just installed and tried the new version. While being logged into a Wi-Fi network, I shot a photo after setting up Nextcloud auto upload, but the new picture didn't get uploaded. Even after waiting for about ten minutes with the app open and screen turned on, nothing happened.

BTW: I think this issue and issue #759 are the same.

**Comment by CharlesKrzysik** [comment]
Tested new version. Same as the official one.
Initially works then fails after a while.

Charles

Sent via Pixel XL

On Mar 22, 2017 20:06, Daniel Wilhelm <notifications@github.com> wrote:

Just installed and tried the new version. While being logged into a Wi-Fi network, I shot a photo after setting up Nextcloud auto upload, but the new picture didn't get uploaded. Even after waiting for about ten minutes with the app open and screen turned on, nothing happened.

BTW: I think this issue and issue #759<https://github.com/nextcloud/android/issues/759> are the same.

**Comment by CharlesKrzysik** [comment]
Interesting though: in my case nextcloud is sitting behind NATTED firewall. I reset the banned IP and so far both clients are working really well. I will update thread as I use it more.

Charles

Sent via Pixel XL

On Mar 22, 2017 20:08, Charles Krzysik <ckrzysik@eoas.ubc.ca> wrote:
Tested new version. Same as the official one.
Initially works then fails after a while.

Charles

Sent via Pixel XL

On Mar 22, 2017 20:06, Daniel Wilhelm <notifications@github.com> wrote:

Just installed and tried the new version. While being logged into a Wi-Fi network, I shot a photo after setting up Nextcloud auto upload, but the new picture didn't get uploaded. Even after waiting for about ten minutes with the app open and screen turned on, nothing happened.

BTW: I think this issue and issue #759<https://github.com/nextcloud/android/issues/759> are the same.

**Comment by mario** [comment]
Do you maybe wifi flagged as mobile hotspot in settings?

**Comment by CharlesKrzysik** [comment]
No I don't. I reset my phone and did fresh setup. After unbanning IP address yesterday it seems to be working so far. Let you know more as time goes.

Charles

Sent via Pixel XL

On Mar 23, 2017 4:22 PM, Mario Đanić <notifications@github.com> wrote:

Do you maybe wifi flagged as mobile hotspot in settings?

**Comment by shieldwed** [comment]
What do you mean by unbanning? I've got no bans in place and am still not able to have a successful Wi-Fi upload without restarting the phone.

@mario: No I haven't flagged my networks as mobile hotspot either.

Meanwhile I grabbed the log from my phone: [currentLog.txt](https://github.com/nextcloud/android/files/866937/currentLog.txt)
It looks like connecting to Wi-Fi events are not logged or fired for Nextcloud.

**Comment by mario** [comment]
@shieldwed while that's probably a bug of some kind, it's only related to Instant Upload, so I'm not worried about it.

Could you setup Android studio, download the code, prepare TeamViewer and Vysor and I can connect and we can debug? :)

**Comment by mario** [comment]
@shieldwed I've built a special apk for you, can you please try it?

https://github.com/nextcloud/android/blob/fix-issue-with-wifi/nextcloud-android-generic-debug.apk?raw=true

**Comment by mario** [comment]
@xadox-1st you too: https://github.com/nextcloud/android/blob/fix-issue-with-wifi/nextcloud-android-generic-debug.apk?raw=true

**Comment by xadox-1st** [comment]
Same problem for me with the debup apk. Right after reboot upload is starting.
But after taking some more pictures autoupload does not start.

**Comment by mario** [comment]
Got time today for debugging via teamviewer?

**Comment by mario** [comment]
@xadox-1st also which one did you try? First or the second?

**Comment by xadox-1st** [comment]
No time at the moment.

**Comment by shieldwed** [comment]
@mario: I can't give you a timeframe when we could debug this issue together as my schedule is very dynamic currently. However, if you could point out the relevant code lines for me, I could try to find out what is happening (or not, in this case).

**Comment by witteschnitte** [comment]
Hi,
I think i was to fast with my working comment.
The new Autoupload now puts all my Pictures in the Queue but don´t upload.
In the new autoupload Settings i set only to upload if the Smartphone is at the power suply.
If i connect it with my power suply, nowthing happens.
With wifi only without power suply Option it work. But this does not fit to me. 

Also i missed the Video upload function. my Videos will not recognized anymore.
Dear nextcloud Team. what have you done to a well working app Feature.
Regards.
Felix

**Comment by loxK** [comment]
The instant upload is totally unreliable. My yesterday's mother day photos didn't upload. If I take a photo now it uploads leaving a gap of not uploaded photos. Galaxy S7, stock, unrooted.

**Comment by seuffert** [comment]
same for me. took a bunch of photos yesterday - some are missing even NC app says all is fine and uploaded :(

**Comment by WebSpider** [comment]
Same issue with me, Android 7.1.1, OnePlus 3, let me know what you need to debug, i got time for screensharing session as well

**Comment by mario** [comment]
Dear users,

thank you for your patience. After lots of work, we’re super excited to be able to give you a test version with new auto upload implementation. Keep in mind we will only accept bugs related to Auto Upload in this APK, as other things might be broken.

https://cloud.nextcloud.com/s/ftZraTruRQjTe0R

This is a dev APK so it will not overwrite your existing play store/f-droid APK unless you’re already running dev version. Also, you might need to remove your existing dev version before installing this one.

Explanation of the current functionality:
- added support for custom folders
- separated image and video folders
- checks for new files happens every 15-20 minutes
- automatic retry every 15-20 minutes or when you force close/open the app
- automatic pause once network is changed (untested!)
- significantly less battery usage

All and any testing is more than appreciated, especially with large and ever-going files like Videos. (like, try to record a 30 min video).

Let me know if you’ve got any questions.

Cheers,
Mario

**Comment by xadox-1st** [comment]
I am testing your Dev Release.
It seems to work while uploading new made photos or videos.

But only new taking photos are uploaded. All existing photos or video will not be uploaded for me.

**Comment by mario** [comment]
This is expected.

**Comment by xadox-1st** [comment]
Ok, I see.

For start in using this app this could be very annoying for someone who does not now how to solve this manually.

I will take some more photos and videos and will see I it still works after several days of use.

**Comment by xadox-1st** [comment]
Now already after one hour of wait no more made pictures where uploaded automaticly.
Had to use the _force_ option.

**Comment by mario** [comment]
That sounds strange... what phone and os?

**Comment by xadox-1st** [comment]
`Huawei P9 Lite (MM 6.0)`

**Comment by xadox-1st** [comment]
@mario some more findings about the prob?

**Comment by mario** [comment]
@xadox-1st I've looked and looked, and the only reason jobs would not run is if Google stopped them somehow. But they will eventually run and your images will be recognized (as you can see by running Force re-scan).

**Comment by xadox-1st** [comment]
Once I am on **Nougat** I will test again.
Maybe its related to some _Huawei_ thing.

**Comment by WebSpider** [comment]
I've tested this on a OnePlus 3, full patched Android 7. The auto-upload works now! I've tested with multiple folders and pictures, video's (up to 500Mb in size) and binary files. Just a few comments:

- The 'upload only on Wifi' setting, set per auto-upload folder seems to be ignored. Files are just uploading when on 4G regularly. Takes up quite some data from my bundle.
- When rebooting the phone, you have to open the app at least once to enable auto-uploading. If you forget it, you have quite a backlog after a few days being on an event, taking pictures and videos.
- This dev release makes my Android complain about powerusage. ¯\_(ツ)_/¯

**Comment by mario** [comment]
Can you please switch to GPlay beta channel?

- should have wifi fixed
- this should be fixed too (but is dependant on Android platform, really)
- also should be fixed

Please try this, and thank you! :)

https://play.google.com/apps/testing/com.nextcloud.client

**Comment by mario** [comment]
(Btw. important thing here is reliability, not INSTANT sync)

**Comment by WebSpider** [comment]
Is this the same as nextcloud-dev 20170807 on f-droid?

**Comment by mario** [comment]
Unsure, @tobiasKaminsky would probably know. But I don't think so :)

**Comment by tobiasKaminsky** [comment]
20180807 is way too old, a newer version would have auto upload included, but currently fdroid fails to build (for the same reason we do not have a RC on fdroid).
So to help/test this release, please try the play store beta .

**Comment by WebSpider** [comment]
Ok, will do! 

On 14 August 2017 11:14:56 CEST, Tobias Kaminsky <notifications@github.com> wrote:
>20180807 is way too old, a newer version would have auto upload
>included, but currently fdroid fails to build (for the same reason we
>do not have a RC on fdroid).
>So to help/test this release, please try the play store beta .
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/nextcloud/android/issues/761#issuecomment-322138955

-- 
Sent from my mobile device. Please excuse my brevity.

**Comment by WebSpider** [comment]
After testing a few days with the beta app, the main functionality seems to be working. There is one annoying bug though: 
I have my auto-upload set to function on wifi only, with no charger limitations.
Whenever you connect to a wifi network that is captive-portaled, the app doesn't wait until internet connectivity is made via wifi, but just starts uploading via 4G, pending the <OK> on the captive portal.

**Comment by mario** [comment]
@WebSpider please open a separate issue for that. It's rather a complex issue that I still have to think about.
