### ISSUE TITLE
Android Client refuses to obey disabled Non metered wifi settings

### ISSUE THREAD

**Issue by Oclair** [nextcloud/android#7610]
### Steps to reproduce
1. install nextcloud app from google play app store
2. set auto upload folder to upload regardless of battery or network
3. take a photo

### Expected behaviour
photo uploads to nextcloud

### Actual behaviour
uploads lists either waiting for non-metered wifi or charging battery, clicking image switches from waiting to charge battery to waiting for non-metered wifi

### Can you reproduce this problem on https://try.nextcloud.com?
Other clients (mobile and desktop) never and still do not have this issue including android clients

This issue is completely limited to a malfunction within the Android app as the auto upload directory is set to OFF for Only upload on unmetered Wi-Fi

### Environment data
Android version: 10 November 1 2020 patch
Baseland: G975FXXU9DTJA
Build: QP1A.190711.020.G975FXXU9DTJA

Device model: Samsung Galaxy S10+ SM-G975F

Stock or customized system: Stock

Nextcloud app version: 3.14.1

Nextcloud server version: 19.0.5 Stable FreeBSD nextcloud source version

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
What kind of wifi do you have? VPN? etc?

**Comment by ferdiga** [comment]
similar here.
wifi was "metered" - auto upload was waiting for non metered.
- set wifi to non metered  - auto upload was waiting for non metered. Android 9  - Nokia 8
- set setting /  "auto upload" / configure / "Only upload on unmetered wifi" to OFF - auto upload was waiting for non metered.
- switched to a non metered wifi - upload starts

**Comment by tobiasKaminsky** [comment]
It might be that existing "waiting for non-metered" are not re-checked.
It then however should work for new jobs…

**Comment by Oclair** [comment]
omg this metered wifi setting is a huge mess and should be only enabled via user intervention instead of leaking into defaults where unassuming users will be tortured by it

**Comment by jeffWelling** [comment]
@ferdiga If you reboot your phone, does it still wait for non metered wifi, or does it begin uploading?

**Comment by ferdiga** [comment]
sorry, moved to iphone now

**Comment by chenyhsu** [comment]
still happend on androud client 3.34
