### ISSUE TITLE
inaccurate metadata

### ISSUE THREAD

**Issue by joho1001** [nextcloud/android#7613]
### Steps to reproduce
1. Deleted a folder that does not exist on Server side (Just it's metadata seems to exist, because it is displayed)

### Expected behaviour
- folder should be removed, or nextcloud should detect that the folder is missing and fix it's metadata automatically. This error situation could be the trigger to sync metadata from filesystem.

### Actual behaviour
- metadata is not updated. Nextcloud displays non existing records.

### Environment data

************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{801a373 u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1970)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7386)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140090
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: Nokia
Device: ES2N_sprout
Model: Nokia 3.1
Id: QP1A.190711.020
Product: Essential2_00WW

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 00WW_4_16B

**Comment by tobiasKaminsky** [comment]
> android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground():

This is a different error, please upgrade to 3.14.1 and try again.
