### ISSUE TITLE
Android client: Conflict window creation error

### ISSUE THREAD

**Issue by huburtx** [nextcloud/android#7614]
### Steps to reproduce
1. Upload large file with Android client (ex. Internal storage/Download path)
2. After upload appear the notify "file upload conflict - choose which version to keep of (file)"
3. Tap on notify and have error "Conflict window creation error"

### Expected behaviour
- file selection panel appear.

### Actual behaviour
- Error notification and reopen app.

### Environment data
Android version: 11

Device model: Xiaomi mi 10 5g

Stock or customized system: MIUI Global 12.2.1

Nextcloud app version: 3.14.1

Nextcloud server version: 20.0.2

Reverse proxy: Apache 2.4.37 (centos)

#### Web server error log

[webserver log here](https://huburt.ngrok.io/index.php/s/zEkMefgQgs2J7zf)

#### Nextcloud log (data/nextcloud.log)

[Nextcloud log here](https://huburt.ngrok.io/index.php/s/FGg73FacCHfNZT5)

**Comment by tobiasKaminsky** [comment]
Does the file in question already exists on server?
In your example it is a path, but you mean a file, or?

**Comment by XaverXN** [comment]
Same here (3.14.1 on Android 10). I use Autoupload for my photos and I am not sure why I am frequently asked which version to keep. But I would not be bothered so much, the worse thing is that the conflict dialog cannot be displayed (as described above).
So, yes, data ist already present on the Server.
