### ISSUE TITLE
F-Droid: 'Build.py failed on server for com.nextcloud.client:1.4.2' 

### ISSUE THREAD

**Issue by supremesyntax** [nextcloud/android#762]
1.4.2
We can't build this version: The build for this version appears to have failed. Check the build log.
Version code: 10040299 

Check here: https://f-droid.org/wiki/page/com.nextcloud.client/lastbuild_10040299

**Comment by Seferi** [comment]
I have been waiting on F-Droid update as well. Hope it gets fixed soon..

**Comment by supremesyntax** [comment]
Next problem...

1.4.2
We can't build this version: The build for this version was manually disabled. Reason: play-services, see https://github.com/nextcloud/android/commit/e245b1f91dd30994f182892255d963a62dc6429c#commitcomment-21381828

**Comment by Seferi** [comment]
If nextcloud is not fully open source , it kinda beats the purpose.. Dependency on play-services should be resolved imho..

**Comment by AndyScherzinger** [comment]
Hi everybody,

getting up a nonGCM build is on our agenda and something we are working on.

**Comment by Seferi** [comment]
@AndyScherzinger Thanks for the info mate. Looking forward to the release.

**Comment by tobiasKaminsky** [comment]
Labelling it as bug and high as this must be the next thing we focus on, after doing the current things of our roadmap.

**Comment by mario** [comment]
This is fixed.

**Comment by supremesyntax** [comment]
will it be in 1.4.3 or can 1.4.2 be build with this change for f-droid?

**Comment by tobiasKaminsky** [comment]
@supremesyntax will be in next version, 1.5.0
