### ISSUE TITLE
Problem connecting server

### ISSUE THREAD

**Issue by yopsolo79** [nextcloud/android#763]
I run an instance of NC11 on Univention as docker. 
Their config doesn't allow access to https://ncserver/nextcloud, only with a trailing slash : https://ncserver/nextcloud/
This instance is reachable through webbrowser on the phone but not from the app.
Entering the url gives an ok but validating the password time out.
With another of NC11 on Centos7 which can be reached without the trailing slash (https://ncserver/nextcloud) the app works well.

### Environment data
Android version:7
Device model: Sony Xperia X F5121

Stock or customized system:
Nextcloud app version: 1.4.2
Nextcloud server version: 11.0.1

**Comment by Bullnados** [comment]
Wlan or mobile connection?

**Comment by yopsolo79** [comment]
Tested with wlan and mobile. Both work with chrome browser but cannot be added to the app.

**Comment by yopsolo79** [comment]
I cannot seem to find the log for the app on android.
Anyone where it can be found ?

**Comment by AndyScherzinger** [comment]
@yopsolo79 the stable releases don't have logging, in order to find a log you would need to install the night build, e.g. via f-droid (ca be installed in parallel): https://f-droid.org/repository/browse/?fdfilter=Nextcloud&fdid=com.nextcloud.android.beta

**Comment by yopsolo79** [comment]
Thanks for the info. 
It's not very clear why but the problem is solved by now. I had to add hostnames as approved one and that was probably missing or blocking (for example myname.localdomain)
