### ISSUE TITLE
Invisible "Cancel" button

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/android#7633]
### Steps to reproduce

1. Launch the app.
2. Go to app settings.
3. Select data locations from general settings.

### Expected behaviour
- Visible `Cancel` button.

### Actual behaviour
- Invisible `Cancel` button.

![obraz](https://user-images.githubusercontent.com/47037905/101515882-220f7400-397f-11eb-9dda-ff49dc5e63ff.png)

![obraz](https://user-images.githubusercontent.com/47037905/101515967-394e6180-397f-11eb-8325-876177a5200e.png)

### Environment data
Android version: 10

Nextcloud app version: 3.14.1 and Dev 20201208

Nextcloud server version: 20.0.2

**Comment by AndyScherzinger** [comment]
true for all other addition selection dialogs within the settings screen (they make use of the fallback theme)
