### ISSUE TITLE
Android can not download any file

### ISSUE THREAD

**Issue by johnwmail** [nextcloud/android#764]
### Actual behaviour
I installed nextcloud client on my android phone, then connect to my nextcloud 11.x server,
I can see the file/directory structure,
I can upload file or create directory,
but cat NOT donwload any file,

### Expected behaviour
It can download file
 
### Steps to reproduce
1. install nextcloud android client from googke market/app store.
2. connect to nextcloud server
3. download any file.

I can download any file with firefox/chrome on both desktop or android.

### Environment data
Android version: Android 5.x

Device model: Samsumg Note3

Stock or customized system: Stock

Nextcloud app version: 1.4.2

Nextcloud server version: 11.0.2

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

**Comment by johnwmail** [comment]
Same problem to
https://github.com/nextcloud/android/issues/113
or
https://github.com/owncloud/android/issues/1128

**Comment by tobiasKaminsky** [comment]
Then I am closing this in favour of #113
