### ISSUE TITLE
android app: documente path in detail (after search)

### ISSUE THREAD

**Issue by lwbr** [nextcloud/android#7641]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by AndyScherzinger** [comment]
@lwbr can you provide any details except the issue headline?

**Comment by lwbr** [comment]
@AndyScherzinger sorry. when I search for a document (mobile app) and the search results are displayed, it is not possible to see in which path the file is located. so it would be good if you can see the path under document details. maybe an additional option to switch to the appropriate folder.

**Comment by AndyScherzinger** [comment]
thanks for the feedback, closed in favor of #4432
