### ISSUE TITLE
Where do I find Instructions to Customize and Build Android app!

### ISSUE THREAD

**Issue by hfomar-nafcs** [nextcloud/android#7642]
Where do I find Instructions to Customize and Build Android app With Custom Branding and Icon and no URL selector!

**Comment by AndyScherzinger** [comment]
please check `setup.xml` for customization possibilities as well as `ic_lauincher.xml` for the launcher/app icon definition. Custom Branding is implemented on top the this app's repository by Nextcloud as a company (not as an open source project/community) so there is no documentation/instructions on how to do this.
