### ISSUE TITLE
Next cloud crashes.

### ISSUE THREAD

**Issue by Arkinpol** [nextcloud/android#7644]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Please fill out template and re-open.

**Comment by Arkinpol** [comment]
Hi, I am currently using Developer version and is working fine for now. Waiting for the updates on Android phone. Thank you 

Sent from AT&T Yahoo Mail on Android 
 
  On Fri, Dec 18, 2020 at 1:32 AM, Tobias Kaminsky<notifications@github.com> wrote:   


Please fill out template and re-open.
