### ISSUE TITLE
Help-item in "Setting" points to deprecated page

### ISSUE THREAD

**Issue by Spielmops** [nextcloud/android#7646]
### Steps to reproduce
1. Tap on Menu ->  Settings -> Help
2. Your browser calls: https://help.nextcloud.com/c/feature/8
3. That page tells us:  feature (DEPRECATED) category

### Expected behaviour
- Tell us what should happen
the first page of the documentation of the Nextcloud-client for Android should appear

### Environment data
Android version: LineageOS 14,16

Nextcloud app version:
3.14.1

Spielmops

**Comment by AndyScherzinger** [comment]
Should be 
https://help.nextcloud.com/c/clients/android/

**Comment by Spielmops** [comment]
Did you call this address? I'm landing here: https://help.nextcloud.com/c/clients/android/29
Spielmops

**Comment by AndyScherzinger** [comment]
I did and my shorter url redirects to the one you posted :)

**Comment by Spielmops** [comment]
Sorry to disturb again: Do I see it correctly that the menu item "Help" should not point to "Help documentation". but to a forum section?

**Comment by AndyScherzinger** [comment]
Hi @Spielmops, that's correct, yes. There is no (up-to-date) user docs and also no plan to provide such.
