### ISSUE TITLE
streaming with vlc or other independent apps doesn't work

### ISSUE THREAD

**Issue by MrJaypot** [nextcloud/android#7647]
after logging to the server, picking a video (tried many different formats of video), I am unable to "stream with" any app I have on the android (8.0) phone (tried mx player, vlc, and more). No error is seen, it only tries forever...

**Comment by tobiasKaminsky** [comment]
Can you stream it on any other device?

**Comment by kuzmos** [comment]
Experiencing same issue. Videos are unplayable on Samsung s10, latest android, latest app. Can't play them (loading indefinitely), can't stream them to an external app - tried google photos, vlc, samsung default gallery. Same videos play as expected when viewing gallery on firefox.

**Comment by MrJaypot** [comment]
I found partial explanation for my issue: my nextcloud server was signed
with self-signed certificate, and vlc got ssl- authentication error because
of that. I changes the certificate to be signed by CA, and now vlc stil
takes unreasonably long time to start streaming.
other apps manage to stream (a bit faster).
So now it is just a performance issue...

Thanks!

**Comment by kuzmos** [comment]
I've managed to accept my self-signed certificate when streaming to VLC and the video is playing, but the performance is not great. The internal nextcloud video player is not working though. When playing the same video from nextcloud web, it all works great, better than streaming to vlc.

**Comment by tobiasKaminsky** [comment]
> but the performance is not great.

What does happen? Is is buffering? Hanging?
If it is working at all, then it might be "only" a caching problem?

**Comment by tobiasKaminsky** [comment]
There is an experimental switch to another video player in https://github.com/nextcloud/android/pull/8132#issuecomment-792722526

This apk can be installed in parallel. 
It would be great if you can give this a test, if it helps in your scenario.

**Comment by szaimen** [comment]
Unfortunatley, this doesn't solve the streaminging with VLC but I can report that the video streaming with the built-in player works now :) Though I found a bug: Playing a sound file e.g. MP3 is missng now any control buttons!

**Comment by tobiasKaminsky** [comment]
For streaming I guess we can track it in #4903.
