### ISSUE TITLE
"Open with" and "share" fails with NC on server subfolder

### ISSUE THREAD

**Issue by MrManuel** [nextcloud/android#765]
### Actual behaviour
- NextCloud (NC) is installed in a sub-directory on the server (i.e. https://myDomain.de/nc)
- Accessing an image file with the NC-App (v1.4.2) works fine
- Sharing the image (with IM-App) does not work. Error-Message: "Teilen fehlgeschlagen, bitter versuche es erneut" (in german, translates to EN like "Sharing failed, please try again")
- Open the file with Gallery-App doesn't work either. Same error as above
- The file is accessable within the cache. I can navigate there using Astro File Manager. In the Path, the "/" of "myDomain.de/nc" is encoded as "%2F". Sharing the cached file doesn't work either. I assume, that the path encoding ("%2F") is the cause. However, copying the file to another location with the Astro File Manger allows sharing with the Astro File Manager app.

### Expected behaviour
-Sharing/Opening with should work from within the NC-App
 
### Steps to reproduce
1. Install NC to a webserver location which is not the root directory
2. Try to share/open with an image

### Environment data
Android version: 7.9

Device model: SM-G930F (Galaxy Note 7)

Stock or customized system: none

Nextcloud app version:1.4.2

Nextcloud server version: 11.0.2 (stable)

#### Web server error log
does not apply

#### Nextcloud log (data/nextcloud.log)
is empty

**Comment by AndyScherzinger** [comment]
@mario since you have a test installation with a subfolder, can you reproduce this behavior?

**Comment by MrManuel** [comment]
Yesterday I did some testing on my own and configured a subdomain for the NC Server.
Now it is running on https://nc.myDomain.de.
I did add an account with the new url in NC Android App.
Still, I am unable to directly "open with" or "share" an image. However, sharing from the new cache-location with astro file manager works.

Is there anything I can do to trace the error back?

**Comment by AndyScherzinger** [comment]
Don't have an idea right away.

> Android version: 7.9

As for the Android Version, do you know to which "real" Android Version 7.9 maps? Since the newest version released by Google is 7.1. So it seems this is a Samsung version number :(

**Comment by MrManuel** [comment]
Sorry, it was a Typo. It is Android v 7.0

**Comment by MrManuel** [comment]
Tested it with another Device (LG G5, Android 7.0). Same issue there.

**Comment by tobiasKaminsky** [comment]
@MrManuel can you create us a test account and send the credentials to android at nextcloud dot com?

**Comment by tobiasKaminsky** [comment]
@MrManuel can you try the dev version https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#dev-release
This one has logs enabled. 
Right after the failing share please go to settings -> logs -> send log and send it to android at nextcloud dot com with a reference to this issue

Meanwhile I have tested it on some devices and with/without subdomain/subfolder and had no problems.
"%2F" should also be no problem as on android no direct file path is used, but instead a content uri is used.

**Comment by tobiasKaminsky** [comment]
No response within the last month, therefore closing.
Please feel free to reopen with additional infos, if the problem still exists.
