### ISSUE TITLE
Cname DNS record not support well for android webview

### ISSUE THREAD

**Issue by yanggs07** [nextcloud/android#7650]
### Steps to reproduce
1. fetched the latest app from google play
2. login my server with https://example.org:12345 (with/without '/' at last is the same) fail, notice '找不到主机'(unable to find the server for origin i18n, i guessed)
3. at the same network use the browser is ok

### Expected behaviour
- Tell us what should happen
connect it, of course
### Actual behaviour
- Tell us what happens
failed
### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum
no, not related to account
### Environment data
Android version:
10
Device model: 
sm-g9860 (samsung s20+)
Stock or customized system:

Nextcloud app version:
3.14.1
Nextcloud server version:
20.0.3
Reverse proxy:
nginx-apache2.4
#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
@yanggs07 the latest version of the app prefers ipv6 over ipv4 so you likely have a ipv6 config issue (within your dns record)

**Comment by yanggs07** [comment]
> @yanggs07 the latest version of the app prefers ipv6 over ipv4 so you likely have a ipv6 config issue (within your dns record)

yep, i guessed maybe relating with ipv6

and what should i do for this, the address of nextcloud server dns record is only ipv4,

so, how come?

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky any idea? If the server is ipv4 only it should simply Fallback which it does according to other reports

**Comment by yanggs07** [comment]
> @tobiasKaminsky any idea? If the server is ipv4 only it should simply Fallback which it does according to other reports

thanks for considering this issue.
i tried the latest version of osx client, which seems noting having this issue and works perfect.
and the iOS client from app store also works well.

and would you please tell me if there is a older release might work?

thanks a lot again~

**Comment by AndyScherzinger** [comment]
> and would you please tell me if there is a older release might work?

3.13.x should work for you

**Comment by yanggs07** [comment]
> > and would you please tell me if there is a older release might work?
> 
> 3.13.x should work for you

emmm 3.13.1 still has this issue (fetched from app pure)

i even tried 3.6, the same.

so i am wondering if there is another problem related to this.

ios/windows/mac app are all ok with it.

**Comment by AndyScherzinger** [comment]
@yanggs07 My guess is that you are facing a server-side config issue with configured routes :/

**Comment by yanggs07** [comment]
> @yanggs07 My guess is that you are facing a server-side config issue with configured routes :/

thanks for reply me that much.

it is not related with ipv6 issue, nor the custom port within the url

the dns record i used for nextcloud service is cname record, not A-record, as i us ddns service.

the outgoing ip i created a dns record like foo.bar.com
and nextcloud.bar.com i use a cname dns record point to foo.bar.com, so there would be only one record i would change if the ip changed.

so, with the cname dns record, the android webview -- not only in nextcloud app, does not resolve the correct dns result

this might not be the issue of nextcloud.

thanks.

**Comment by tobiasKaminsky** [comment]
I fear then that we cannot help that much, as we only use regular webView. :S
