### ISSUE TITLE
Cannot connect to server with proxy-autocofig

### ISSUE THREAD

**Issue by AMajor-C** [nextcloud/android#7652]
### Steps to reproduce
1. Connect to internet via wifi
2. Set option "Proxy auto-config" to your "proxy.pac" where your server gets connection DIRECT (yes, not trough proxy)
3. Reconnect to the network to apply
4. Kill all processes of the app and clean memory cache
5. Now in app server comes to unavailable

### Expected behaviour
- Installing a "proxy.pac" config shouldnt do matter

### Actual behaviour
- App cannot connect to server

### Environment data
Android version: 7.1.2

Device model: redmi 4x

Stock or customized system: miui 11.0.2

Nextcloud app version: last 

Nextcloud server version: last

**Comment by tobiasKaminsky** [comment]
Where do you add your proxy.pac? And what is in it?

**Comment by Psych3s** [comment]
> 
> 
> Where do you add your proxy.pac? And what is in it?

In wifi senntigs, the script is anticensorshipment solution https://antizapret.prostovpn.org/proxy.pac 
ofc im using my own copy where proxy servers is changet to mine (and yes same problem on both)

**Comment by Psych3s** [comment]
Btw the Nextclous SMS app works normally

**Comment by tobiasKaminsky** [comment]
Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

**Comment by Psych3s** [comment]
> 
> 
> Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

Ok,  ill try

**Comment by Psych3s** [comment]
> 
> 
> Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

12-20 18:04:35.007  1508  7876 I ProcessManager: SwipeUpClean: kill com.nextcloud.client Adj=400 State=9
12-20 18:04:35.008  1508  7876 I ActivityManager: Killing 8679:com.nextcloud.client/u0a265 (adj 400): SwipeUpClean
12-20 18:04:35.074  1508  2629 I WindowManager: WIN DEATH: Window{c8d78f9 u0 com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}
12-20 18:04:42.728  8460  8460 I Timeline: Timeline: Activity_launch_request time:1213856708 intent:Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity bnds=[56,898][212,1051] }
12-20 18:04:42.731  1508  1966 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity bnds=[56,898][212,1051]} from uid 10167 on display 0
12-20 18:04:42.811  1508  1966 I ActivityManager: Start proc 11530:com.nextcloud.client/u0a265 for activity com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity caller=com.microsoft.launcher
12-20 18:04:42.811  5306  5409 D PowerKeeper.Event: notifyAMProcStart processName: 10265 reason: com.nextcloud.client, pid:0
12-20 18:04:42.829 11530 11530 I chatty  : uid=10265(com.nextcloud.client) expire 153 lines
12-20 18:04:43.385 11530 11562 I chatty  : uid=10265(com.nextcloud.client) expire 11 lines
12-20 18:04:43.592 11530 11569 I chatty  : uid=10265(com.nextcloud.client) expire 5 lines
12-20 18:04:43.861 11530 11570 I chatty  : uid=10265(com.nextcloud.client) expire 1 line
12-20 18:04:43.890 11530 11572 I chatty  : uid=10265(com.nextcloud.client) expire 13 lines
12-20 18:04:43.930 11530 11574 I chatty  : uid=10265(com.nextcloud.client) expire 12 lines
12-20 18:04:43.958 11530 11565 I chatty  : uid=10265(com.nextcloud.client) expire 9 lines
12-20 18:04:43.959  1508  1966 I ActivityManager: START u0 {flg=0x20000000 cmp=com.nextcloud.client/com.owncloud.android.ui.activity.RequestCredentialsActivity} from uid 10265 on display 0
12-20 18:04:44.320 11530 11580 I chatty  : uid=10265(com.nextcloud.client) expire 5 lines
12-20 18:04:44.359 11530 11581 I chatty  : uid=10265(com.nextcloud.client) expire 11 lines
12-20 18:04:44.359 11530 11582 I chatty  : uid=10265(com.nextcloud.client) expire 11 lines
12-20 18:04:44.389 11530 11583 I chatty  : uid=10265(com.nextcloud.client) expire 11 lines
12-20 18:04:44.393 11530 11584 I chatty  : uid=10265(com.nextcloud.client) expire 14 lines
12-20 18:04:44.546 11530 11588 I chatty  : uid=10265(com.nextcloud.client) expire 94 lines
12-20 18:04:44.687 11530 11564 I chatty  : uid=10265(com.nextcloud.client) expire 1 line
12-20 18:04:44.984  1508  2507 I ActivityManager: Start proc 11596:com.android.settings/1000 for activity com.android.settings/.ConfirmDeviceCredentialActivity caller=com.nextcloud.client
12-20 18:04:45.004 11530 11595 I chatty  : uid=10265(com.nextcloud.client) expire 3 lines
12-20 18:04:45.213 11530 11551 I chatty  : uid=10265(com.nextcloud.client) expire 1 line
12-20 18:04:45.902 11530 11588 V UploadsStorageManager: Updating /data/user/0/com.nextcloud.client/cache/2020-12-19_10-55-39.vcf with status:UPLOAD_FAILED and result:NETWORK_CONNECTION (old:/data/user/0/com.nextcloud.client/cache/2020-12-19_10-55-39.vcf status:UPLOAD_IN_PROGRESS result:-1)
12-20 18:04:45.902 11530 11588 V UploadsStorageManager: Updating /data/user/0/com.nextcloud.client/cache/2020-12-19_10-55-39.vcf with status=UPLOAD_FAILED
12-20 18:04:45.924 11530 11588 D UploadsStorageManager: updateUpload returns with: 1 for file: /data/user/0/com.nextcloud.client/cache/2020-12-19_10-55-39.vcf
12-20 18:04:45.957 11530 11588 V UploadsStorageManager: Updating /data/user/0/com.nextcloud.client/cache/2020-12-18_10-54-05.vcf with status:UPLOAD_IN_PROGRESS and result:UNKNOWN (old:/data/user/0/com.nextcloud.client/cache/2020-12-18_10-54-05.vcf status:UPLOAD_IN_PROGRESS result:-1)
12-20 18:04:45.957 11530 11588 V UploadsStorageManager: Updating /data/user/0/com.nextcloud.client/cache/2020-12-18_10-54-05.vcf with status=UPLOAD_IN_PROGRESS
12-20 18:04:45.982 11530 11588 D UploadsStorageManager: updateUpload returns with: 1 for file: /data/user/0/com.nextcloud.client/cache/2020-12-18_10-54-05.vcf
12-20 18:04:46.052 11530 11588 V UploadsStorageManager: Updating /data/user/0/com.nextcloud.client/cache/2020-12-18_10-54-05.vcf with status=UPLOAD_IN_PROGRESS
12-20 18:04:46.107 11530 11588 D UploadsStorageManager: updateUpload returns with: 1 for file: /data/user/0/com.nextcloud.client/cache/2020-12-18_10-54-05.vcf
12-20 18:04:46.504 11530 11588 V UploadsStorageManager: Updating /data/user/0/com.nextcloud.client/cache/2020-12-18_10-54-05.vcf with status=UPLOAD_IN_PROGRESS
12-20 18:04:46.532 11530 11588 D UploadsStorageManager: updateUpload returns with: 1 for file: /data/user/0/

**Comment by Psych3s** [comment]
Also PhoneTrack app doesnt have same problem

**Comment by AMajor-C** [comment]
This bug is still exsists

**Comment by anisite** [comment]
Same on android 13, pixel 6

**Comment by AMajor-C** [comment]
Same on Android 12, Sharp AQUOS R5G
