### ISSUE TITLE
Photo upload file conflicts issue: UI hangs after a single conflict is solved

### ISSUE THREAD

**Issue by leo-recover** [nextcloud/android#7659]
### Steps to reproduce
1. Have many photos (I have more than 150) in conflict state 
2. Try to solve a conflict by following the notification, choosing to overwrite the remote version

### Expected behaviour
UI / App should not hang, and it should follow the setting to just overwrite the remote version

### Actual behaviour
For each decision taken on a single photo (i.e. overwrite the remote version), the app will re-scan the files in conflict, and it will produce as many notifications as the photos still in conflict. When in this state, the UI will not be responsive, often producing the Android system dialog to close the app or wait for it.  

### Environment data
Android version: 9

Device model: OnePlus3

Stock or customized system: Stock, OxygenOs 9.0.6

Nextcloud app version: 3.14.1

Nextcloud server version: 20.0.2

**Comment by maanloper** [comment]
I would like to add, that next to having the same problem (with 600+ conflicts), the general setting in AutoUpload to overwrite remote files is not honored.

This all used to work fine up to about a month ago, then AutoUpload just disabled itself, and on reenabling it manually, the problems started. Also the folder to write to on the server was reset to the default location, instead of my custom path.

**Comment by tobiasKaminsky** [comment]
This conflict dialog is currently only for one file, then the next file conflict is shown.
In Auto upload you can set the desired conflict resolution strategy.

**Comment by maanloper** [comment]
As mentioned in my previous comment, that did not seem to work. I had to uninstall and reinstall the Nextcloud app for it work again.

**Comment by leo-recover** [comment]
I confirm that the Auto upload general setting was not honored in my case as well.
The main point of this usability issue is the UI freezes that follow after a single resolution option has been chosen by the user, which make the app almost unusable in this state. 
By the way, my workaround was to select to hide all the notifications about conflicts from the app.

**Comment by kangaroo72** [comment]
I can confirm. I have 150+ conflicts in queue... annoying :-|

**Comment by leo-recover** [comment]
I was reading through some other issues and I think that at least for the UI freezes the root cause is very well captured in #7441 .
When a lot of conflicts are present probably it simply amplifies the issue due to the additional computation.
The missing point is why the general auto upload conflict resolution was not honored.
