### ISSUE TITLE
automatic contacts backup never starts (combined with cloud provider)

### ISSUE THREAD

**Issue by ippocratis** [nextcloud/android#7666]
### Steps to reproduce
-sign app with ops one account on https://nextcloud.com/signup/

-verify account on your email

-open nextcloud 

-select url

-https://shared02.opsone-cloud.ch

-use your username(email), password

-on nextcloud>setting>contacts sync>crate account with davx⁵

-on nextcloud>contacts back up>set auto backup toggle on 

-nextcloud>contacts back up>back up now works as it should

BUT

Auto backup is not

2. 
3. 

### Expected behaviour
- contacts should auto backed up in time intervals setup in davx⁵ account settings

### Actual behaviour
- only manual back up works

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:11

Device model: redmi note 9s 

Stock or customized system:lineage os 18

Nextcloud app version: 3.14.1

Nextcloud server version: -

Reverse proxy: -

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Might be that your device is preventing those backups in background.
Can you exclude the app from battery optimization?

**Comment by ippocratis** [comment]
Looks like it was a davx⁵ kinda issue.
I had the backup interval to 4 hours. When i changed that to "every 24 hours"automatic contacts and calendar backup works as it should.
