### ISSUE TITLE
Downloading instead of streaming only in app.

### ISSUE THREAD

**Issue by socr2121** [nextcloud/android#768]
### Actual behaviour
-Tell us what happens
Downloading instead of streaming only in app.
### Expected behaviour
-Tell us what should happen
 Expected to stream instead of download to phone.
### Steps to reproduce
1. Try to play any video from the app.
2. Try to long hold so that you can open it with another video player and there is no open with option.
3. 

### Environment data
Android version:
Nougat
Device model: 
LG v20
Stock or customized system:
Stock
Nextcloud app version:
Both the Play Store version and the beta
Nextcloud server version:
Latest version
#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

**Comment by godfuture** [comment]
I have exactly the same issue. The currently multi-media capabilities of Nextcloud for Android (1.4.1) are pretty slow. Especially slower than expected compared to given bandwith (local server and WLAN-ac) and given ressources (8 cores on Android 6.0.1 with ARM big.Little, flash memory, 3GB RAM):
1) thumbnail download is pretty slow
2) download seems to have idle time
3) even if the thunmbnail and the image itself is downloaded, the opening of this image seems to delay too much

 I would like to simply stream the photo, not download and open it. Hoping that all these steps are getting a looot faster. For images and videos I use [QuickPic ](https://play.google.com/store/apps/details?id=com.alensw.PicFolder) which I can highly recommend.

**Comment by tobiasKaminsky** [comment]
For video we have #183 and for images we have #69 to cover streaming, which are both in development.
I think we can discuss further in these particular issues if needed, therefore closing (feel free to re-open if you disagree).
