### ISSUE TITLE
Target folder after auto upload

### ISSUE THREAD

**Issue by kvoit** [nextcloud/android#769]
I really like the feature to move auto uploaded files after successful upload. It is very helpful to keep track of what is uploaded and what failed. Right now, I only have upload failures due to the net breaking away and tgat sort of jazz, but it happens and I still don't fully trust that feature.
It also helps not reloading images that are actually still on the device when browsing in the Nextcloud app.

The issue is where the images are moved. /storage/emulated/0/Android/data/com.nextcloud.android.beta/files/nextcloud/myaccount@myserver/SofortUpload/Camera2017/03 is just ridiculous. There even seems to be a .nomedia somewhere, I cannot see the images in the Photo app anymore. I can only properly use them with the Nextcloud app.

I am not sure what the best solution would be. Perhaps not put the synced folders into Android/data? I don't really see a reason for that. I would like to see it in [configurable path, mostly /sdcard]/nextcloud.

**Comment by AndyScherzinger** [comment]
@kvoit if you have a sd card you should be able to choose it in the settings view of the app as the to be used storage path.

**Comment by kvoit** [comment]
It is not about getting the files to a certain storage. It is about getting them to a place that is still useful for other apps. The Android/data/com.nextcloud.android.beta/files/nextcloud/myaccount@myserver/ seems to have an explicit or implicit (is the Android/data folder possibly always excluded?) .nomedia, so the stuff does not show up in the Gallery app.

**Comment by mario** [comment]
Yes, android/data is always excluded. We do have to think about this issue in depth I guess...

**Comment by kvoit** [comment]
Well on Linux, my Nextcloud data isn't forced into ~/.config/com.nextcloud.android.beta/files/nextcloud/myaccount@myserver/ and under Windows it is no in %APPDATA%\com.nextcloud.android.beta\files\nextcloud\myaccount@myserver\
So I cannot really see why it should be on /storage/emulated/0/nextcloud on Android. Ask for the folder when setting up the server and reject folders that are already used for other servers.

**Comment by tobiasKaminsky** [comment]
I thought I had changed this for external storage to use the media directory, which then would be public available...

**Comment by kvoit** [comment]
You mean if SD card is selected? I don't know. I don't have an SD card slot and I don't see one coming up for me as long as one usually has to choose between SD or DualSIM usage. I would like to see an alternative also for internal storage.

**Comment by tobiasKaminsky** [comment]
This is changed for next version, so that other apps can access the downloaded/uploaded files again.
