### ISSUE TITLE
Happy Xmas 🎉 🤶 🎅 🚀

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#7693]
End of year is near and I want to wish the whole Android Files community a nice and relaxing Xmas vacation and a good start into 2021 :tada: :mrs_claus: :santa: :rocket: 

Thank you for being such a nice community,
thank you for all your contributions (code wise, bug reports, ideas, feature requests,…)
thank you for using Nextcloud!

**Comment by InfamousUser** [comment]
How nice! Merry Christmas everybody!

**Comment by Fanboy-Studios** [comment]
Merry Christmas!

Lol fix this on New Years 🤣

**Comment by InfamousUser** [comment]
Ah damn
