### ISSUE TITLE
1.4.2 Video upload folder destination incorrect 

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#770]
see https://help.nextcloud.com/t/1-4-2-video-upload-folder-destination-incorrect/10432

There is an option to have it upload to ```<folder>/<year>/<month>``` (folder being user selected) this is broken in 1.4.2

In this case my destination folder for my videos is "video".

In 1.4.2. it creates a folder called ```<folder>+<year>/<Month>```  i.e.  ```video2017/03```  when the path should have been ```video/2017/03```

-----

I haven't tested this personally but know that we fixed this issue pre-1.4.2 final for images, but am not sure if this is then also automatically fixed for video uploads (but would think so).

**Comment by AndyScherzinger** [comment]
probably fixed by #774 - waiting for the user feedback on the Android version in use.

**Comment by DaveBurkhardt** [comment]
![screenshot_2017-03-19-17-04-25](https://cloud.githubusercontent.com/assets/23338339/24314429/8c1aa13c-10af-11e7-88d6-14792fdd4b1f.png)
![screenshot_2017-03-24-16-27-38](https://cloud.githubusercontent.com/assets/23338339/24314430/8dca2868-10af-11e7-856d-89d83a2d560b.png)

Validation images.

**Comment by mario** [comment]
@DaveBurkhardt thanks. weather doesn't help though :D

**Comment by mario** [comment]
This will either be fixed in the next release or we'll replace instant upload with auto upload which doesn't have separation between images and videos. Thanks for reporting.

**Comment by DaveBurkhardt** [comment]
@mario haha, sorry!  Fixed above

**Comment by mario** [comment]
@DaveBurkhardt all good! :)

**Comment by AndyScherzinger** [comment]
PR has been merged, to be shipped with 1.5.0
