### ISSUE TITLE
Auto upload fails when uploading to encrypted folder from a local folder with subfolders

### ISSUE THREAD

**Issue by xaled** [nextcloud/android#7719]
### Steps to reproduce
1. Activate E2E encryption
2. Create a destination folder and set it as encrypted
3. In Auto upload set up a custom folder
4. Set the encrypted folder as the remote folder 
3. Either:
   - Choose a local folder with subfolders,
   - or, check the subfolders option

### Expected behaviour
- Auto upload and encrypt files to the remote folder and auto create new folders if necessary.

### Actual behaviour
- Fails to upload with the message "Connection error".
- The destination folders become impossible to delete even if they are empty.
- This problem does not occur if the local folder contains only files and doesn't contains any subfolders.

### Can you reproduce this problem on https://try.nextcloud.com?
I could not create a test account in try.nextcloud.com; when i click on "Take me there!" button an ajax error is returned (status_code=500; response: {"message": "Slim Application Error"}):
![Selection_001](https://user-images.githubusercontent.com/2602329/102984370-c7911e80-450d-11eb-993b-173221b4a396.png)

### Environment data
Android version: 10

Device model:  Samsung A51

Stock or customized system: Stock

Nextcloud app version: 3.14.1

Nextcloud server version: 19.0.4

Reverse proxy: no

#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"isupbjbI94Bwb8U6FgCL","level":3,"time":"2020-12-23T08:05:21+00:00","remoteAddr":"192.168.1.17","user":"xaled","app":"no app in context","method":"DELETE","url":"/ocs/v2.php/apps/end_to_end_encryption/api/v1/lock/15579","message":{"Exception":"OCA\\EndToEndEncryption\\Exceptions\\MissingMetaDataException","Message":"Intermediate meta-data file missing","Code":0,"Trace":[{"file":"/var/www/html/custom_apps/end_to_end_encryption/lib/Controller/LockingController.php","line":146,"function":"saveIntermediateFile","class":"OCA\\EndToEndEncryption\\MetaDataStorage","type":"->","args":["xaled",15579]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"unlockFolder","class":"OCA\\EndToEndEncryption\\Controller\\LockingController","type":"->","args":[15579]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\EndToEndEncryption\\Controller\\LockingController"},"unlockFolder"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":137,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\EndToEndEncryption\\Controller\\LockingController"},"unlockFolder"]},{"file":"/var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\EndToEndEncryption\\Controller\\LockingController","unlockFolder",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"id":"15579","_route":"ocs.end_to_end_encryption.Locking.unlockFolder"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"id":"15579","_route":"ocs.end_to_end_encryption.Locking.unlockFolder"}]},{"file":"/var/www/html/lib/private/Route/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"id":"15579","_route":"ocs.end_to_end_encryption.Locking.unlockFolder"}]},{"file":"/var/www/html/ocs/v1.php","line":88,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/ocsapp/apps/end_to_end_encryption/api/v1/lock/15579"]},{"file":"/var/www/html/ocs/v2.php","line":24,"args":["/var/www/html/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/html/custom_apps/end_to_end_encryption/lib/MetaDataStorage.php","Line":190,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.14.1","version":"19.0.4.2"}
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Does the sub folder exists?

**Comment by xaled** [comment]
Yes, but not initially.

For example:
* The local file is /storage/emulated/0/test that contains a sub folder subfolder with files
* The remote folder is /Backup/test, initially empty and encrypted

After configuring Autoupload, /Backup/test/subfolder is created. However, files under this sub folder fail to upload.
