### ISSUE TITLE
Save the rename of a file's

### ISSUE THREAD

**Issue by KwonEunKyung** [nextcloud/android#7722]
### Is your feature request related to a problem? Please describe.
I know that “dot-file” can be viewed by activating “Show hidden files” in the settings.

However, I think there is a problem that a file cannot be easily found when a user does not know this fact or accidentally saves a file name as space.

### Describe the solution you'd like
Therefore, I think the user’s intended “dot-file” name should be at least 1 character long except for dot+extension. That is, I think it would be better to prevent users from saving their files rename as spaces.

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Can you give us an example, I fear that I fail to understand what should be changed.
