### ISSUE TITLE
uploading files using "share with..." function doesn't works

### ISSUE THREAD

**Issue by jkumeboshi** [nextcloud/android#7731]
When I try to upload a photo to nextcloud using the Android share function of gallery app (but from WhatsApp Is the same) the nextcloud app asks me where ti save the file. But then Notting happens, the file Is not uploaded at all. I've tried with many app's share button, with exactly same results.

I can upload a file if I use the upload function inside the app or if I use the "send a Copy" function of Google drive app.

I'm using android 10 MIUI 12 and nextcloud client from F-droid.

**Comment by AndyScherzinger** [comment]
This is a known issue. Fix will ship with upcoming release.

**Comment by AndyScherzinger** [comment]
Duplicate of #7587
