### ISSUE TITLE
upload over share button not working

### ISSUE THREAD

**Issue by ka223** [nextcloud/android#7735]
### Steps to reproduce
Select a picture/file via gallery (Simple Gallery Pro) to upload.

### Expected behaviour
- File is uploaded.
- I can see upload notification.
- I can see upload in activity.

### Actual behaviour
- Nothing, it is ignored? No error or anything else. The picture is not uploaded.

### Can you reproduce this problem on https://try.nextcloud.com?
- It is an nextcloud app @ android problem. I can select a picture inside nextcloud app and upload it, but not by using the share button for example in gallery or file manager.

### Environment data
Android version: MIUI 11.0.3 (Android 10)

Device model: 
Xiaomi Redmi 8A

Stock or customized system: Stock

Nextcloud app version: 3.14.1

Nextcloud server version: 18.0.12

Reverse proxy:

### Logs
there are no logs

**Comment by alexandrebln** [comment]
Exactly the same issue. Work-around for me : go back to NextCloud Android version 3.13.1 from F-Droid.

Android version: 8.0.0

Device model: SM-G903F (Samsung Galaxy S7)

Stock or customized system: Stock

Nextcloud app version: 3.14.1

Nextcloud server version: 19.0.6

Reverse proxy: Nginx (cf this docker-compose : https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/with-nginx-proxy/mariadb/fpm)

**Comment by AndyScherzinger** [comment]
Fix will ship with 3.14.2
