### ISSUE TITLE
Low contrast of home and history buttons on /e/

### ISSUE THREAD

**Issue by kofaysi** [nextcloud/android#7736]
### Steps to reproduce
1. Open NextCloud Dev on /e/OS
2. Observe contrast of Home and history buttons (native Android)

### Expected behaviour
- Buttons are of low contrast (white font on white bg)

### Actual behaviour
- Buttons should be better visible, see the other screenshot for comparison

![Screenshot_20201226-205131](https://user-images.githubusercontent.com/17022173/103158916-7dd15e00-47c3-11eb-9d8d-180da5cc3afb.png)
![Screenshot_20201226-213740](https://user-images.githubusercontent.com/17022173/103158918-83c73f00-47c3-11eb-975b-400162fc9000.png)

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 7.1.2

Device model: LG-H850

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
I fear that we cannot do that much on this, as this is handled via Android, as far as I know.
It also depends on Android version, e.g. this does not happen for me on an Android 8 device.

@AndyScherzinger @dan0xii as you both are also in design/theming area :)

**Comment by AndyScherzinger** [comment]
I agree with you @tobiasKaminsky this depends on the Android version or rather the OEMs way of handling it 🙁

**Comment by uusijani** [comment]
Nextcloud is somehow different from other apps in this regard, as no other light (white) apps on the same device have this issue. For instance, here's Play Store on my affected device (running Android 6.0.1):

![Screenshot_20210206-124828](https://user-images.githubusercontent.com/4244772/107116505-4ce15000-687c-11eb-8076-c2ec33bf3404.png)

Also, I seem to recall this only having started to affect Nextcloud quite recently, perhaps sometime in the past month or so.

Switching to dark mode is a workaround on my device at least (there the Android buttons are light-on-black). I can also confirm that the issue doesn't affect my newer devices with newer Android.

**Comment by kofaysi** [comment]
The issue is not present in Android 10 /e/OS

**Comment by uusijani** [comment]
[Android 7.1.2 (LineageOS 14.1) is affected](https://user-images.githubusercontent.com/4244772/110821216-8866a400-8298-11eb-81d7-2b4a0e07f0c2.png).
