### ISSUE TITLE
Problem in auto upload

### ISSUE THREAD

**Issue by selva-1106** [nextcloud/android#7739]
When i click some folder autoupload and config it to upload in mobile data also.
But still it is searching for non meteric wifi. What can i do. In beta version works well but not even working 2 mins and it crashef

### Environment data
Android version:

Device model: a30

Stock or customized system: android 10

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
> In beta version works well but not even working 2 mins and it crashef

Which stable version do you use?
What crashes?

Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat
