### ISSUE TITLE
Logo is not changed in the Android application

### ISSUE THREAD

**Issue by borjapazr** [nextcloud/android#7746]
### Steps to reproduce
When I set the custom logo, in the web application it is changed correctly, but in the Android application the default Nextcloud logo is displayed.

![image](https://user-images.githubusercontent.com/9295713/103247844-8fa03600-4968-11eb-94b7-e77fcc985784.png)
![image](https://user-images.githubusercontent.com/9295713/103247968-09382400-4969-11eb-8059-c179804ae70d.png)

I have installed imagick to be able to use SVG images, but it does not work either.

Is it possible to change the logo displayed in the Android application? The colors do change, but the logo does not.

### Expected behaviour
The logo should also be changed in the Android application.

### Actual behaviour
The logo is not changed in the Android application.

### Environment data
Android version: 10

Device model: Xiaomi MI8

Stock or customized system: Stock

Nextcloud App version: 3.14.1
Nextcloud Server version: 20.0.4

Reverse proxy: nginx

**Comment by AndyScherzinger** [comment]
Cc @tobiasKaminsky

At the moment the Android client doesn't support custom logos while I can't say if this will be implemented, guess if it is contributed as a PR it is likely otherwise it is probably a rather low priority. 😔

**Comment by tobiasKaminsky** [comment]
Hm. I thought we had this in and I re-activate it? It was removed while switching to new layout.
