### ISSUE TITLE
Nightly APK are not updated since march the 17th

### ISSUE THREAD

**Issue by ldmpub** [nextcloud/android#775]
Hi,

I'm running the nightly of the Android app to check my translations. It was working fine until March 17h.
Since a week there are no update available from the app (menu Settings > Download latest nightly version). 

See changlog:
https://raw.githubusercontent.com/nextcloud/android/beta/CHANGELOG.md

Is there a reason, are the nightlies available somewhere else?

**Comment by Bullnados** [comment]
See last posts here
https://github.com/nextcloud/android/issues/727#issuecomment-289003544

**Comment by ldmpub** [comment]
Thanks for the link to the thread.

I've read it but it's still not clear:
- on one hand: "So, I am closing this one as finally new nightlies are available again." see https://github.com/nextcloud/android/issues/727#issuecomment-287523572
- but on the other hand last nightly is from 2017-03-16 23:38 (more than 12 days old), seehttps://download.nextcloud.com/android/nightly/?C=M;O=D

Can you confirm it's because automatic processes didn't detect a change on the list of watched branches? So there is no new nightly release ...

**Comment by ldmpub** [comment]
Thanks for the link to the thread.

I've read it but it's still not clear:
- on one hand: "So, I am closing this one as finally new nightlies are available again." see https://github.com/nextcloud/android/issues/727#issuecomment-287523572
- but on the other hand last nightly is from 2017-03-16 23:38 (more than 12 days old), see https://download.nextcloud.com/android/nightly/?C=M;O=D

Can you confirm it's because automatic processes didn't detect a change on the list of watched branches? So there is no new nightly release ...

**Comment by tobiasKaminsky** [comment]
Yes, check for nightly build is done every night on 00:30, you can have a look on the branches which can be included and its merge status here: 
https://raw.githubusercontent.com/nextcloud/android/beta/CHANGELOG.md

**Comment by Bullnados** [comment]
Pls link that in fdroid, with an explination. Didn't know that

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger @mario since I do not find the other issue: how to rename the nightly app?
I remember "dev"?

@Bugsbane I will update the fdroid/all descriptions accordingly.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky "dev" is correct, the issue you are looking for is #712 - https://github.com/nextcloud/android/issues/712#issuecomment-291155532

**Comment by Bugsbane** [comment]
@tobiasKaminsky - Uh, ok. Was I part of this discussion somehow? o.O

**Comment by tobiasKaminsky** [comment]
@Bugsbane "Bullnados" or "Bugsbane" seems to be just too similar ;-)

**Comment by Bullnados** [comment]
^^ Sure

**Comment by Bugsbane** [comment]
Ah, got it. :)

**Comment by tobiasKaminsky** [comment]
I have started nightly as "dev" version from scratch and also included some words that it is not a daily build anylonger.

**Comment by JSoko** [comment]
Works...
