### ISSUE TITLE
Nextcloud app for Android crashes after reinstalling during startup.

### ISSUE THREAD

**Issue by arminbl** [nextcloud/android#7750]
### Steps to reproduce
1. Deinstall Nextcloud
2. Install Nextcloud 
3. Start Nextcloud

### Expected behaviour
- Nextcloud should start

### Actual behaviour
- Nextcloud crashes

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

**Comment by arminbl** [comment]
Sorry I don't have any further information.
It seems that this was an one-time issue which did not happen again.

Am 2021-01-13 13:50, schrieb Tobias Kaminsky:

> Can you provide us additional infos via logcat?
> https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe
> [2].


Links:
------
[1]
https://github.com/nextcloud/android/issues/7750#issuecomment-759428337
[2]

**Comment by tobiasKaminsky** [comment]
I'll close it then.
But feel free to re-open it, once it happens again.
