### ISSUE TITLE
unable to send files from App

### ISSUE THREAD

**Issue by arsistemi** [nextcloud/android#7756]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 10

Device model: Realme x2 pro

Stock or customized system:

Nextcloud app version:3.14.1

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
Any crash logs you are seeing? What do you mean by send files from app? Share from within the Nextcloud app or to the Nextcloud app?

**Comment by bugariu** [comment]
Same(?) problem here:
## App 3.14.1 from F-Droid (on LineageOS 17.1):
### image upload from gallery
- open picture gallery
- select one file
- click share
- select account and directory
- OK
- for a few ms a text "keine Dateien...." is shown (cannot read that quick...)
- no image uploaded
### file upload from file explorer
- works as expected
## App 3.14.1 from GooglePlay (on Android v. ???):
### share video from WhatsApp
- select video in whatsapp
- share
- select account an directory
- OK
- for a few ms a text "keine Dateien...." is shown (cannot read that quick...)
- no video uploaded
### file upload from file explorer
- did not try yet.



Hope this helps...

**Comment by AndyScherzinger** [comment]
@bugariu don't know if it is the same issue but yours has been fixed and will ship with the next release 👍

**Comment by bugariu** [comment]
Sounds good. Thanks!

**Comment by tobiasKaminsky** [comment]
3.14.2 released today.
