### ISSUE TITLE
Instant upload: unwanted upload from subfolder of selected folder (../DCIM/Camera/cache/latest/*.thumbnail)

### ISSUE THREAD

**Issue by Bazon** [nextcloud/android#776]
### Actual behaviour

I want instant upload for ../DCIM/Camera and that works. 
But: For each and every image, a additional file with type .thumbnail instead of .jpg is uploaded, too! I was able to locate the source of that .thumbnail file, and it is ../DCIM/camera/latest/*.thumbnail. In the ../DCIM/camera/latest/ folder there is always exactly one file, the - guess what - latest thumbnail. I suppose its produced by the camera app. (Hardware: Huawei P10)

### Expected behaviour
These *.thumbnail files should not be uploaded.
I don't know whether it's best to exclude subfolders in general, but maybe that is an easy solution.
 
### Steps to reproduce
1. (a) Get a Huawei P10 OR
1. (b) Get an Camera App which generates thumbnail files(s) in a subfolder. (Huawei Camera App unfortunately not in the Google Play store. But you'll find the .apk, if you trust other sources...) OR
1. (c) Generate a file in a subfolder of an instant upload folder by hand.  
2. Wait for the upload delay
3. See that two new files arrived on server instead of one.

### Environment data
Android version: 7.0

Device model: Huawei P10 (VTR-L09)

Stock or customized system: stock

Nextcloud app version: 1.4.2

Nextcloud server version: problem not related to server

**Comment by AndyScherzinger** [comment]
@mario @tobiasKaminsky do you recall if we already fixed this for the upcoming feature release or if this still needs fixing?

**Comment by mario** [comment]
Thumbnail is a real file. How would you solve it?

I guess we could introduce a hard coded blacklist?

**Comment by AndyScherzinger** [comment]
I thought Tobias already added some hardcoded blacklist, to skip temporary files, at least the one that have been reported to us, so this should then be just another one.

**Comment by mario** [comment]
When I rewrote it I included a file filter that skips all DOT files.

Guess I can add this one too, but how do you know what all to exclude?

**Comment by AndyScherzinger** [comment]
We don't I guess, whenever files get reported to be excluded we need to decide if we agree on excluding it or if we don't.

**Comment by mario** [comment]
Do you think this needs to be blacklisted?  If yes, assign it to me.

**Comment by AndyScherzinger** [comment]
I'd say yes, since it is a file onyl of use to the system where it got created, so it's say blacklist it :)
