### ISSUE TITLE
Unable to remove account under restricted user profile

### ISSUE THREAD

**Issue by openhs** [nextcloud/android#7760]
### Steps to reproduce

1. Create a restricted user profile
  1.1 Settings -> Cloud and accounts -> Users -> Add user profile -> User (Restricted profile)
2. Switch to the new user and install Nextcloud
3. Start Nextcloud
4. Add an account, log in.
5. Try to remove the account in Manage accounts screen.

### Expected behaviour
- Account removed

### Actual behaviour
- Account was not removed.  Action was silently ignored, no error messages appear.

Issue was observed during retesting of #1819 and also mentioned in #7759.

### Environment data
Android version: 8.1.0 (Samsung flavor)

Device model: Samsung Galaxy Tab A 10.1

Stock or customized system: stock

Nextcloud app version: 3.14.1 (F-Droid)

Nextcloud server version: 19.0.2

Reverse proxy: nginx

**Comment by tobiasKaminsky** [comment]
I would need to find a Samsung device for this…
