### ISSUE TITLE
File not uploded when shared from outside to nextcloud app

### ISSUE THREAD

**Issue by sagialcide** [nextcloud/android#7761]
### Steps to reproduce
1. open file with its supported app (image with gallery, pdf with pdf viewer, etc..).
2. click on the share button and choose to share to nextcloud.
3. select and folder or user root and upload
4. look for the file you just uploaded, it's missing :(

### Expected behaviour
- The file will be successfully uploded

### Actual behaviour
- the file doesn't upload

### Can you reproduce this problem on https://try.nextcloud.com?
- yes. it reproduces in demo server.

### Environment data
latest android apps both on 1P7 mobile and galaxy tab s6 lite

#### Web server error log
```
no logs
```

#### Nextcloud log (data/nextcloud.log)
```
no log
```

it looks like happening to additional users https://www.reddit.com/r/NextCloud/comments/kn7x4g/cant_send_to_nextcloud_from_android_app/

**Comment by ezaquarii** [comment]
Fixed by https://github.com/nextcloud/android/pull/7649
