### ISSUE TITLE
Sharing from another App into the nextcloud App does not work

### ISSUE THREAD

**Issue by stamfest** [nextcloud/android#7762]
### Steps to reproduce
1. Open the standard Gallery App
2. Long-tap an image and select to share it
3. Select nextcloud as the target
4. Select a target folder within the nextcloud App and press the upload button

### Expected behaviour
- Data should be uploaded from the source app into the selected folder - in this case the selected image should be uploaded

### Actual behaviour
- Nothing happens. Not even an error is shown.
- Also: Initiating an upload from within the nextcloud App FROM another App (eg. the gallery) also does not work. In this case an error pops up ("Es ist ein Fehler beim Kopieren dieser Dateien in einen temporären Ordner aufgetreten. Bitte versuchen Sie erneut die Datei zu senden.")
- Only explicitly uploading files seems to work - initiated from within the nextcloud App.

### Can you reproduce this problem on https://try.nextcloud.com?
- Have not tried this
### Environment data
Android version: 10

Device model: LG G7 Thinq (LM-G710EM)

Stock or customized system: Stock OS from LG; SW Version V30b-EUR-XX

Nextcloud app version: 3.14.1

Nextcloud server version: 20.0.4

Reverse proxy: no

#### Web server error log
```
(empty)
```

#### Nextcloud log (data/nextcloud.log)
```
(empty)
```

**Comment by AndyScherzinger** [comment]
Fixed via #7649 and ship with the next release
