### ISSUE TITLE
on Android Nextcloud app not uploadimg files from share button in other apps ot directly

### ISSUE THREAD

**Issue by kellnerp** [nextcloud/android#7763]
### Steps to reproduce
1. Attempt to upload photos from any of my Android devices.
2. Select photos (or any other file.)
3. Nextcloud dialog closes without uploading.

### Expected behaviour
- Tell us what should happen
- selected photos should upload   

### Actual behaviour
- Tell us what happens
- Nothing. No files are uploaded.

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum
- cannot duplicate there. Problem is in Android app.

### Environment data
Android version:

Device model: Samsung Note 4

Stock or customized system: stock

Nextcloud app version:

3.14.1
Nextcloud server version:
3.1.0

Reverse proxy:

None

#### Web server error log
dna
Insert your webserver log here
Dna

#### Nextcloud log (data/nextcloud.log)`
Does not exist
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
This issue has been fixed and will ship with the next release

**Comment by kellnerp** [comment]
Next release of the app?Sent from my Samsung device

-------- Original message --------

**Comment by AndyScherzinger** [comment]
Not sure I understand the question. The next release will have this fixed while I can't say when this release will happen sind the person in charge is on vacation at the moment. I hope it'll be next week, at least a release candidate.
