### ISSUE TITLE
Photo upload throws Java backtrace

### ISSUE THREAD

**Issue by rakoenig** [nextcloud/android#7765]
Tried to upload photos from my Galaxy S8. But didn't work, instead I got this screen:

************ CAUSE OF ERROR ************

java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 2739808 bytes
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:160)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7050)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
Caused by: android.os.TransactionTooLargeException: data parcel size 2739808 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(Binder.java:1145)
	at android.app.IActivityManager$Stub$Proxy.activityStopped(IActivityManager.java:3891)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:144)
	... 7 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: dreamlte
Model: SM-G950F
Id: PPR1.180610.011
Product: dreamltexx

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: G950FXXSBDTJ1

**Comment by ezaquarii** [comment]
@rakoenig Can you tell us how did you trigger the upload exactly, and in particular how many photos did you try to upload? Are you able to reproduce this issue?

This crash suggests that something tried to send 2.9MB of data to the application via IPC mechanism, while the operating systems impose a limit of 1MB per message.

2 things that come to my mind:
1. platform `Intent` API has a bug resulting in rubbish intent contents (seen this few times, although it's a rare problem).
2. list of attached photos is so big that it exceeds maximum allowed size

**Comment by rakoenig** [comment]
@ezaquarii This is quite strange. I tried again now. 

First I tried like I usually did before:
- Open the Gallery, mark some photos and press the "Share" butten. 
- Then select "Nextcloud", it will take me to my Photos directory. 
- When I press upload then, nothing happens. 

Next try, because I didn't even see the backtrace with the first try:
- Go to "Nextcloud" app. Files. Press the "+" button. 
- Select "Files from other apps", select my photo. 
- **Strange: Now it uploads the photo to the root folder in my Nextcloud space, no Stacktrace, just works**

Third try:
- Go to "Nextcloud" app. 
- Open the folder "Photos" hat holds all my pictures. 
- Press "+" button.
- Seelct "Files from other apps". 
- **Now I can't even select any file, I directly get the stack trace**

So somehow the same workflow behaves different when I do it in the Nextcloud root or when I do it in my "Photos" directory. 

I don't think that a file size limit applies, I got lots of uploaded photos already with the method described as "first try" and they are all between 2,5 and 4 MB of size. I could even upload a panorama picture with 11,4 MB 4 months ago.

**Comment by ezaquarii** [comment]
@rakoenig 
> First I tried like I usually did before:
> * Open the Gallery, mark some photos and press the "Share" butten.

Sharing from 3rd party apps to nextcloud is currently broken, but the fix is already merged and awaits next bugfix release:
https://github.com/nextcloud/android/pull/7649

> I don't think that a file size limit applies

No, the file size does not matter. When sharing a file, the app receives a link to a file, not the file contents.

When sharing multiple files, the app receives a list of file links. It's only when we try to share a lot of files and the list grows > 1MB in size, it crashes.

Since you try to share 1 file only, it looks like this is not the case. 

I'll try to reproduce 3rd described case.

**Comment by rakoenig** [comment]
Tried out, works fine now. Thanks.
