### ISSUE TITLE
[Deprecation] kotlin-android-extensions is now deprecated

### ISSUE THREAD

**Issue by Doomsdayrs** [nextcloud/android#7766]
Working on some features on my own branch, I noticed the compiler warning about 'kotlin-android-extensions' being deprecated. 
It's a good idea to remove usages of it and swap over to ViewBinding

**Comment by AndyScherzinger** [comment]
@Doomsdayrs we are already moving to native view binding to be able to drop the kt extension, since I am on the phone it is hard to find the original GH issue. 😔
