### ISSUE TITLE
ip address not supported in the address field

### ISSUE THREAD

**Issue by supagu** [nextcloud/android#777]
### Actual behaviour
Cannot connect to server error

### Expected behaviour
it shouldnt matter if i use a url or ip. I want to use it on my lan, so an ip is easy.
 
### Steps to reproduce
1. Enter an ip address in the the server field, user and pass. It errors

### Environment data
Android version: 7.1

Device model:  LG G2

Stock or customized system:

Nextcloud app version: latest

Nextcloud server version: latest

**Comment by mario** [comment]
I use an IP and it works. If it's a local IP it might not work, but that's a whole other issue unfortunately ...

cc @AndyScherzinger

**Comment by AndyScherzinger** [comment]
Not an idea right away. Really depends on the "internal ip", if it is IPv6, then that is unsupported at the moment, maybe the brute force protection in Nextcloud (server-side database table) blacklisted the client. Other than that it should work or seems to be a network/server-config problem, not an app problem.
