### ISSUE TITLE
[Cleanup] .gitignore has a duplicate entry

### ISSUE THREAD

**Issue by Doomsdayrs** [nextcloud/android#7770]
`*.iml` is duplicated in the .gitignore

I'm not sure if I should let someone do this, or does it even constitute a singular PR?

I can do a PR, like rn for it.

**Comment by AndyScherzinger** [comment]
PR sizes may vary and yes single line change PRs are just fine. It's rather super large PRs we try to avoid since they are hard to review and resolve conflicts against master...

**Comment by tobiasKaminsky** [comment]
Fixed via https://github.com/nextcloud/android/pull/7772

Thanks :+1:
