### ISSUE TITLE
Nextcloud Upload to an encrypted folder

### ISSUE THREAD

**Issue by RedSkin9028** [nextcloud/android#7776]
### Steps to reproduce
1.  Encrypt folder
2. Upload a Ubuntu Image File "ubuntu-20.04.1-preinstalled-server-arm64+raspi.img.xz" (size about 700 MB) or file "richdocumentscode_arm64.tar.gz" (size about 400 MB)

### Actual behaviour
1. Afterwards no Upload to the same folder posible
2. If there ist already a File in the folder, File can't deleteted
3. Both Files are  posible to Upload to an nonencrypted folder

### Can you reproduce this problem on https://try.nextcloud.com
Iş not possible to ise "end to end encription" on the browser

### Environment data
Raspberry Pi 4b 4GB 
Android version:

Device model: 
Android
Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.owncloud.android.lib.common.operations.RemoteOperationResult.isCancelled()' on a null object reference
	at com.owncloud.android.datamodel.UploadsStorageManager.updateDatabaseUploadResult(UploadsStorageManager.java:561)
	at com.owncloud.android.files.services.FileUploader.uploadFile(FileUploader.java:652)
	at com.owncloud.android.files.services.FileUploader$ServiceHandler.handleMessage(FileUploader.java:1404)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.os.HandlerThread.run(HandlerThread.java:65)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: iWaylink
Device: MC401_GWL
Model: MC401_GWL
Id: PKQ1.190626.001
Product: MC401

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 191105.PR031.003

**Comment by tobiasKaminsky** [comment]
To verify if this is happening due to the big file, does this also happen with a smaller one? E.g. a text file?
