### ISSUE TITLE
Nextcloud on Android

### ISSUE THREAD

**Issue by nuno-rx** [nextcloud/android#7797]
### Steps to reproduce
1. Select a file(photo) from Android native app gallery or file explorer
2. Share the file (photo) with nextcloud folder to upload to NC
3.

### Expected behaviour
- it should upload the file (photo) to NC selected folder

### Actual behaviour
- After click "send", nothing happens. No message from NC app on notification android bar and the destination folder keep without file.

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum.
- Important note: I've tried the RC app version 3.14.2rc1) and the issue seems to be solved the file sharing seems to be working again.

### Environment data
Android version: 10

Device model: Huawei p30 (ELE-L29)

Stock or customized system: stock

Nextcloud app version: 3.14.1

Nextcloud server version: 20.0.4

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
As you stated this is a known issue with a fix coming with 3.14.2
