### ISSUE TITLE
Sending multiple photos from Android

### ISSUE THREAD

**Issue by nuno-rx** [nextcloud/android#7798]
### Steps to reproduce
1. Select 100 photos and 2 videos from Android app gallery, around 900MB
2. Share with a folder on nextcloud, to send this files to NC
3. 

### Expected behaviour
- should send all files to NC server

### Actual behaviour
- After send around 25 photos the process stops and no more sync...
- I was using WiFi strong connection and with LTE as backup, so does no look to be related with internet connection

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: Huawei p30 (ELE-L29)

Stock or customized system: stock

Nextcloud app version: 3.14.2 rc1

Nextcloud server version: 20.0.4 snap01

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
I do not find this issue currently, but I know this is a duplicate, and reason is that the Android kills the receiving part, as this just takes too long.
My solution, which needs to be tested, is that our app opens an activity, so that Android knows that the receiving app (our) is not yet finished with processing incoming files.
