### ISSUE TITLE
New Autoupload feature kills battery

### ISSUE THREAD

**Issue by maybeageek** [nextcloud/android#780]
### Actual behaviour
-After the rewrite of the autoupload feature, autoupload stopped working. Configuring it new, working as expected. However, it kills the battery in a matter of hours. 100% to 1% in 3-5h.
This didn't happen in the previous version

### Expected behaviour
-Tell us what should happen
Battery should last longer
 
### Steps to reproduce
1. 
2. 
3. 

### Environment data
Android version:
6.0.1 (Samsung A3 2017, Stock)
7.1.1 (Galaxy S4 - LineageOS)
Device model: 

Stock or customized system:

Nextcloud app version:
newest. 
Nextcloud server version:
11.0.2
#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

**Comment by DavidMernin** [comment]
Same issue

**Comment by SigLinJo** [comment]
Hi. I'm experiencing similar symptoms on my Cat S60 running Android 6.0.1. Ever since I upgraded to the latest version of the Nextcloud Android app (1.4.2) the highest battery consumer each day has been nextcloud. I have multiple folders selected for auto upload, maybe that can influence it?

**Comment by DavidMernin** [comment]
I personally experienced that problem with just one folder selected, the main camera folder.

**Comment by tobiasKaminsky** [comment]
Do you have enabled nextcloud sync on android system settings -> accounts -> nextcloud?

**Comment by maybeageek** [comment]
> Do you have enabled nextcloud sync on android system settings -> accounts -> nextcloud?
no, this setting is disabled for me.

**Comment by SigLinJo** [comment]
It was disabled for me too. I just activated it now and will report back if there is any change in a day or two. Thanks for looking in to this! Love what you are doing with the app! To be able to upload from more folders is amazing!

**Comment by snicke** [comment]
Same issue. Samsung Galaxy S7 Edge with Android 7.0. The samsung system is identifying Nextcloud every day as the only app draining the battery and ask me if I want to put it in sleep mode.

**Comment by CroneKorkN** [comment]
Autoupload drains my battery, too. Stock 7.0 on Galaxy S6.

**Comment by Doloros** [comment]
Hi,
Same issue here : Nextcloud draining battery on Galaxy s7 android 7.0. The samsung system is identifying Nextcloud every day as the only app draining the battery and ask me if I want to put it in sleep mode.

**Comment by mario** [comment]
Dear users,

thank you for your patience. After lots of work, we’re super excited to be able to give you a test version with new auto upload implementation. Keep in mind we will only accept bugs related to Auto Upload in this APK, as other things might be broken.

https://cloud.nextcloud.com/s/ftZraTruRQjTe0R

This is a dev APK so it will not overwrite your existing play store/f-droid APK unless you’re already running dev version. Also, you might need to remove your existing dev version before installing this one.

Explanation of the current functionality:
- added support for custom folders
- separated image and video folders
- checks for new files happens every 15-20 minutes
- automatic retry every 15-20 minutes or when you force close/open the app
- automatic pause once network is changed (untested!)
- significantly less battery usage

All and any testing is more than appreciated, especially with large and ever-going files like Videos. (like, try to record a 30 min video).

Let me know if you’ve got any questions.

Cheers,
Mario

**Comment by aPollO2k** [comment]
I installed this dev app. But now my auto upload has stopped working. I enabled The sync in the android account settings. Not working.
I taken some photos and videos. Switched off the phone and waited a bit. But it does not upload anything :(

**Comment by tobiasKaminsky** [comment]
@aPollO2k which version have you installed?
There is now a release candidate for the upcoming version available at beta channel on google play store:
https://play.google.com/apps/testing/com.nextcloud.client

Please try this one as this includes the latest fixes.

**Comment by shanness** [comment]
I'm having the same issue, and am running 2.0.0 (seems beta and production versions are the same, I wasn't upgraded after joining the testing program).

I'm getting constant warnings it's draining over 1% of my battery per hour.  And the only thing I want the android app for is auto uploading my pics..  Any update on a fix for this?

**Comment by olenz** [comment]
I also must confirm, since 3.0.1, upload seems to drain battery. Problem with android 8.1 on Nexus 6p.

**Comment by mario** [comment]
Upload or the notification that's persistently there?

**Comment by zdichev** [comment]
@olenz same on Samsung s8

**Comment by gubagu** [comment]
Same here

**Comment by gubagu** [comment]
Same here

**Comment by msundin** [comment]
Any progress on this? Unfortunately I need to uninstall and stop using the app. Draining my battery very fast. The same with my partners phone.

**Comment by r2p2** [comment]
Nextcloud is draining my battery too.

**Comment by Rayn0r** [comment]
Same problem here...
I am using Wakelock Detector on a Stock ROM of a Galaxy S7 to monitor battery usage.

3h45m after turning on my phone, the Nextcloud app was active for 35m11s.
No other app is remotely close to the Nextcloud app's runtime. The second app in line ran for 36s during that time.
The battery is down to 87% while the phone was sitting idle on my desk.

**Comment by tobiasKaminsky** [comment]
I am testing right now with a S5 Neo with Wakelock Detector if and how often our app requests wakelock.

**Comment by tobiasKaminsky** [comment]
@Rayn0r this is strange. 
According to our code we do not acquire wake lock if the device is at least Lollipop (Android 5.0).

What exactly is it in WakeLock Detector?
- Screen WakeLock
- Cpu WakeLock
- WakeUp Trigger?

**Comment by Rayn0r** [comment]
I let the phone sit on my desk this morning again.
This is a screenshot of the CPU Wakelock:
![image](https://user-images.githubusercontent.com/4147858/61855425-5684ac00-aec0-11e9-835a-2ee6537d9fa5.png)

**Comment by msundin** [comment]
> Still draining the battery on Galaxy S7 Edge. Taking 10% of the battery usage in the current use cycle for instance according to battery usage stats. No other app even close. Screen and Android System only processes using more battery (16 and 13% respectively).
> 
> ![screenshot_20180412-163024](https://user-images.githubusercontent.com/28703270/38683981-f750a094-3e6e-11e8-820a-df381de4d817.png)
> 
> ![screenshot_20180412-162647](https://user-images.githubusercontent.com/28703270/38683797-945e9b26-3e6e-11e8-81b0-3cc7005bc663.png)

Any update on this? Now, almost 2 years later, I'm on a Galaxy S10 with Android 10 and Nextcloud auto upload is still (!) draining the battery pretty much like in the picture above. I auto upload both camera images, videos etc. but also custom folders like WhatsApp images. I have the setting to only auto upload when charging and on wifi, still Nextcloud is draining my battery all day long. Why? It should only be activated when plugged in and on wifi.

Only way to stop the battery drain is:
1. Enable battery optimization for the Nexcloud app in Android (i.e. don't let Nextcloud run in the background) but then the auto upload obviously never starts when you plug in the charger.
2. Disable auto upload

I think the solution here is to find the issue in the code that makes the Nextcloud app check for uploadable items all the time (keeping the phone awake) **even if it should only do so when charging according to the user settings**. In pseudo code just to clarify what I'm meaning:

    If (notCharging && onlyAutoUploadWhileChargingUserSetting) {
        skipCheckForFilesToAutoUpload = true;
    }

Then the battery should probably not drain.

**Comment by Larx** [comment]
I can't believe this bug is still open after three years. Every now and then I try the Nextcloud app, and always I give it up because it kills the battery (several Samsung phones running LineageOS). However, the only WebDAV sync alternative (FolderSync) for Android is kind of dead, so the need for a client gets more urgent.

As mentioned above, even using restrictive conditions for upload does not help, as Nextcloud seems to start nevertheless if any media is changed on the configured folders.

I would even go with a periodic sync or a manual sync (controllable e.g. by Tasker) if it is not possible to restrain the battery usage of the app itself.

**Comment by xdaWhitealien** [comment]
Looks like guys are short handed if even after three years bug is still open :(
47% battery drain in a day. For now I see - only one option: 
- disable entirely autoupload and background tasks
- use alternative sync app

**Comment by vthuongt** [comment]
@xdaWhitealien 
> * disable entirely autoupload and background tasks

I can't find such an option in the app. Can you explain how to do this?

> * use alternative sync app
Can you recommend one?

**Comment by tobiasKaminsky** [comment]
How many files are getting uploaded?
Roughly how many files do you have on your device? It might be that scanning takes too long.

I would need one person who is suffering from this, and is willing to test a few apks and give me logcat info.

**Comment by pankewen** [comment]
Hello, I just instaled the latest app App on my Samsung Galaxy yesterday and experienced the issues described in this issue: mobile phone temperature was increasing and battery was empty after few hours.
I like nextcloud, thanks for your efforts on spending time and effort on it. I am willing to support in any way to resolve this issue. Pls let me know, how I can help.

**Comment by Larx** [comment]
This problem persists since years without any progress. I therefore gave up on this feature and disabled all auto sync functionality. I now use FolderSync Pro for syncing with my cloud. This app is also *much* more versatile concerning which folders to sync in which way.

**Comment by tobiasKaminsky** [comment]
Problematic is not only dev power, but also having such a weird device.
On all our test devices there is no problem, also not in any device used by our colleagues, friends, etc.

**Comment by Larx** [comment]
I had the problem on at least four different Samsung mainstream devices running LineageOS, which I don't consider weird :-). However, I personally am not bothered too much by this bug any longer, as using an alternative sync app for WebDAV is not only a workaround, but also provides much more options (custom folders to sync etc.).

**Comment by arcane47** [comment]
Also running lineage, with a terrible battery drain. Much like the other posters, I have autoupload against large folder bases; camera folder (1k files), WhatsApp folder (many files, 8GB of data). Willing to test any APK. 

Current workaround is to disable the app when not in use.

**Comment by tobiasKaminsky** [comment]
@arcane47 do you see many uploads? 
Is it getting better if you only have one auto upload?

**Comment by arcane47** [comment]
> @arcane47 do you see many uploads?
> Is it getting better if you only have one auto upload?

It doesn't upload many files daily. Whatever new photos, and WhatsApp media daily.
You mention one auto upload, as in only one folder for autoupload? Not tested, but if that is what you are asking I can test.

**Comment by AI-ien** [comment]
I will just reconfirm what I wrote in June. Current state - nothing have changed, insane battery drain persists, somewhere around 30% to 40%.
My conditions:
Sync two folders: Camera and Office lens. Last have around 10 files, Camera folder have over 2000 files. 
Phone: Samsung S9
Android version: 10
Kernel: 4.9.118
I haven't tested with latest app 3.15. Also, I'm not sure I could, because autoupload feature in last version is removed. 

I have tested this on another phone Google Pixel 3 and battery drain issue is also there. Lastly, I'm using self hosted Nextcloud. It's up to date and running on Ubuntu, maybe issue is there, but I doubt that.

**Comment by LSchober** [comment]
I can confirm as well...massive battery drain persists. 
Active while in background: 4hr 3min -> 31% Battery Usage
Sync two folders: Camera and Download-Folder
Phone: Pixel 4a 5G
Android version: 10
Nextcloud-Version: 3.15.0 (@AI-ien autoupload-feature is now in Nextcloud-Settings "Auto upload")

**Comment by LSchober** [comment]
#7663 corresponding issue.

**Comment by jagjordi** [comment]
Hello @tobiasKaminsky , thank you for your work with nextcloud, it is an amazing platform. 

I am willing to try different APK and report the behaviors to help fix this issue.

I am suffering the same problem with autoupload feature, I use BetterBatteryStats app and I can see wakelocks that last for several hours. Other apps have just a few minutes of wakelocks.

Please let me know what other info you need from my side.

**Comment by zyeborm** [comment]
Confirming this on a note 20 Ultra 5g
Multiple folders to upload. 
It was detecting all pictures as conflicts until I set it to skip existing. Now it's using about 30% battery a day

**Comment by panomitrius** [comment]
I'm using Samsung S10E with Android 11 and nextcloud client uses around 20% of battery a day.

**Comment by Croydon** [comment]
Hi! This is my generic reply for every issue which is still relevant and is on the edge of getting closed by a stale bot.

**Comment by J4gQBqqR** [comment]
![IMG_20210805_184950](https://user-images.githubusercontent.com/77554817/128431539-13c11ae1-204b-4e87-b2db-4c6da4f098fa.jpg)

The number one battery drainer on my phone.
Lineage OS 18.1, Nextcloud 3.16.1
Nothing synced, nothing turned on.
All background use. Never opened it foreground.

**Comment by zyeborm** [comment]
Hi! This is my generic reply for every issue which is still relevant and is on the edge of getting closed by a stale bot.

**Comment by LSchober** [comment]
Hi! This is my generic reply for every issue which is still relevant and is on the edge of getting closed by a stale bot.

**Comment by AlvaroBrey** [comment]
I've setup the bot so that it doesn't auto-close this issue. There is a rework of the autoupload feature in the horizon although we can't give any timeframe. When that happens we'll look at this issue too.

**Comment by b-pfl** [comment]
@AlvaroBrey this would be great. 
I just remembered that I had NC-related battery issues on my phone some months ago. As a consequence, I had enabled  Android battery optimization (Samsung Galaxy S9, Android 10) to put NC to sleep when not in use, which solved my problem. However, this obviously killed the auto upload feature and (as I realized today) using the NC app as a 2nd factor for authentication also does not work in that case. 
Today, I re-enabled it and the problem appeared again (Android client 3.18.0). Some additional observations:
- Despite having disabled auto-upload if neither a wifi connection nor a charger are connected, it looks like the client tries to do some batter-draining activities even while not charging. 
- There seems to be an issue with the auto upload settings screen. a) it seems to not be able to deal with larger local directories (my phone has more than 10000 photos) as the screen freezes for quite a few seconds. b) using the latest version, instead of only seeing a few pictures per folder (with a +XYZ photos placeholder), the placeholder seems to repeat multiple in the upload folder view.

**Comment by fvlaicu** [comment]
I think I may have found a fix for the drain issue: Uncheck "Also upload existing files". I have about 10k items that sync and before the only way for my phone to survive the night was to enable power saving mode ;).
![Screenshot 2021-12-08 092937](https://user-images.githubusercontent.com/19238716/145166795-18953863-0423-45dc-b83f-41dfedd01f33.jpg)

**Comment by AlvaroBrey** [comment]
I believe this should have been greatly reduced by https://github.com/nextcloud/android/pull/10448, can anyone verify?
