### ISSUE TITLE
Share files to Nextcloud not working

### ISSUE THREAD

**Issue by Demian98** [nextcloud/android#7800]
### Steps to reproduce
1. Select files in any app. For example images in your gallery. I have the same issue with all apps and file types. Not just images.
2. Share the files with nextcloud
3. Select the target location in your nextcloud account
4. Select Upload and nextcloud app in the background
5. But nothing happens. No Upload. No Error. Nothing.

### Expected behaviour
- Files should be uploaded

### Actual behaviour
- Nothing happens. Also no Error.
- If I select Upload File in the nextcloud App, I'm able to chose any file and Upload it successfully. So from inside the nextcloud app is no issue and uploading files in general is also no issue.

### Note
Two friends of me (also Samsung Phones) have the same Problem.

### Environment data
Android version: 10

Device model: Samsung Galaxy Note 10+

Stock or customized system: Stock

Nextcloud app version: 3.14.1

Nextcloud server version: 20.0.4

Reverse proxy: None

**Comment by AndyScherzinger** [comment]
This bug had been fixed and is available with 3.14.2 RC1, available via the GPlay Beta Programm
