### ISSUE TITLE
Client crash

### ISSUE THREAD

**Issue by Somebodyisnobody** [nextcloud/android#7803]
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke interface method 'com.owncloud.android.ui.helpers.FileOperationsHelper com.owncloud.android.ui.fragment.FileFragment$ContainerActivity.getFileOperationsHelper()' on a null object reference
	at com.owncloud.android.ui.preview.PreviewTextStringFragment.lambda$edit$1$PreviewTextStringFragment(PreviewTextStringFragment.java:159)
	at com.owncloud.android.ui.preview.-$$Lambda$PreviewTextStringFragment$fDSIsNZagYwxFSLhq1IBY22AQB8.run(lambda)
	at java.lang.Thread.run(Thread.java:761)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: google
Device: shamu
Model: Nexus 6
Id: N6F27M
Product: shamu

************ FIRMWARE ************
SDK: 25
Release: 7.1.1
Incremental: 4299435

Accessed phone via scrcpy when the display went black (display timeout). Pressing ESC didn't help so I pressed the hardware power button to turn on the screen. In this second I saw nextcloud closing.

**Comment by tobiasKaminsky** [comment]
Do you know when this happens? Can you reproduce it?

**Comment by Somebodyisnobody** [comment]
Non reproducable, just reporting the error as asked by the app. But such an unchecked exception should be found.
