### ISSUE TITLE
renaming a file doesn't force an update/a refresh of the view

### ISSUE THREAD

**Issue by j-ed** [nextcloud/android#7804]
### Actual behavior
If you rename a file using the app, the file is renamed but the currently selected view isn't instantly updated and still shows the previous file name. Currently you have to manually updated/refresh the directory to get the changed file name displayed.

### Expected behavior
If you rename a file using the app, the file should be renamed and the selected view should instantly be updated so that the new file name is shown.
 
### Steps to reproduce
1. Open the Nextcloud app and navigate to a folder which contains at least one file.
2. Select a file and rename it.
3. Check the list of displayed files.
-> There is original file name is displayed until you manually update/refres hthe directory view.

### Environment data
Android version: 11.0
Device model: Samsung Galaxy S20
Stock or customized system: Stock ROM
Nextcloud app version: 3.14.2 RC1
Nextcloud server version: 20.0.4

I've found the following related issue ticket which has already been closed although the issue itself seems not be fixed yet:

https://github.com/nextcloud/android/issues/7299

**Comment by jonasburian** [comment]
I've noticed the same problem. It happens in the detail view as well as in the list view. Within the list view, a pull down refresh will do it but in the detail view, you would need to exit the view and enter it again. For a user, it may be better to see the changes immediately.

**Comment by tobiasKaminsky** [comment]
After debugging: decryptedRemotePath is not updated in RenameFileOperation: 102

**Comment by joshtrichards** [comment]
Fixed in #9475
