### ISSUE TITLE
Sharing files to Nextcloud from other apps doesn't work anymore

### ISSUE THREAD

**Issue by KopfKrieg** [nextcloud/android#7805]
### Steps to reproduce
1. On your phone open any app that is able to share documents, images, etc.
2. Press the share button
3. Select Nextcloud
4. Press "Upload"
5. For a split second the message "Kopiere Datei vom privatem Speicher" (copy file from private storage) is shown
6. Nextcloud closes, and you get back to the sharing screen of whatever app you tried

### Expected behaviour
The selected file(s) should be uploaded to Nextcloud

### Actual behaviour
Nothing. After you press "Upload" a message is shown for a split second as mentioned in step 5, and then Nextcloud closes (without any error message!). No files are uploaded.

### Can you reproduce this problem on https://try.nextcloud.com?
The issue persists on multiple servers, and even on a newly created account on try.nextcloud.com. I tried sharing different types of files with various apps, and also single files and multiple files. Not even once the sharing to Nextcloud was successful.

### Environment data
Android version: 10
Device model: Motorola G8+
Stock or customized system: Stock ROM
Nextcloud app version: 3.14.1, installed through F-Droid
Nextcloud server version: 20.0.4
Reverse proxy: Caddy

### Logs
There are no logs on the server indicating any issue, it's probably client side. Not sure how to extract logs from the Nextcloud Android app, sorry.

**Comment by AndyScherzinger** [comment]
This is a known bug and has been fixed. Will ship with the next release 3.14.2
