### ISSUE TITLE
[3.14.2 RC1] folder move operation causes error message although it succeeds without a problem

### ISSUE THREAD

**Issue by j-ed** [nextcloud/android#7806]
### Actual behavior
If you select multiple folders, which all contain files, and move them to a different directory, the following error message is displayed at the bottom of the app, although the move operation is still ongoing in the background and all files and folders are correctly moved to the new destination.

-> "The operation cannot be completed. The server is unreachable".
   (German: Die Operation kann nicht abgeschlossen werden. Der Server ist nicht erreichbar.)

### Expected behavior
No error message should be shown on a move operation, if it is still processed in the background and successfully been completed at the end.

### Steps to reproduce
1. Open the Nextcloud app and navigate to a folder which contains folders with file content.
2. Select multiple folders and move them to a different directory.
3. The mentioned error message is should although the move operation is still ongoing in the background.
-> The move operation succeeds without any problem.

### Environment data
Android version: 11.0
Device model: Samsung Galaxy S20
Stock or customized system: Stock ROM
Nextcloud app version: 3.14.2 RC1
Nextcloud server version: 20.0.4

**Comment by tobiasKaminsky** [comment]
Does this also happen with only one folder?

**Comment by j-ed** [comment]
@tobiasKaminsky I wasn't able to reproduce the problem with only one folder.

**Comment by tobiasKaminsky** [comment]
Can you test latest beta (3.15.1 RC2?), available via beta play store?

**Comment by j-ed** [comment]
@tobiasKaminsky I'm unable to reproduce the problem with the latest app version too.
