### ISSUE TITLE
Automatic upload should not show error when obviously offline

### ISSUE THREAD

**Issue by PVince81** [nextcloud/android#7809]
### Steps to reproduce
1. Setup automatic upload
2. Go offline by disabling both wifi and mobile network
3. Take a picture

### Expected behaviour
No error.
Once going back online, the picture is uploaded.

### Actual behaviour
An error appears about being unable to upload.

### Version
Nextcloud app 3.14.1
Android 10
Nokia 6.1

**Comment by tobiasKaminsky** [comment]
Where is this error shown?
