### ISSUE TITLE
add icons to website/twitter on user info screen

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#781]
As described in https://github.com/nextcloud/android/pull/585#issuecomment-289394805 also 

* use icons for the entries: website and twitter
* remove http:// and https:// from the shown URL
* make sure the twitter handle starts with an ```@```

**Comment by jancborchardt** [comment]
Cool! :) 

@schiessle maybe on the server we should also make sure that the Twitter handle starts with an `@` and also for the placeholder use `@…` to make sure people know which format we want it in.

**Comment by AndyScherzinger** [comment]
PR has been opened for review: #782

**Comment by mario** [comment]
Closing, merged
