### ISSUE TITLE
Separate notification channel for upload/sync/download failures

### ISSUE THREAD

**Issue by Webbeh** [nextcloud/android#7814]
I am using Instant Upload a lot, and on multiple devices.

I get thousands of pictures uploaded, and we get spammed with notifications (I get an average of 1929 a day from the Upload channel).

Usually, I turn that channel off, but by doing so, I miss the upload failure notifications.
Separating the failures in a new channel could allow us to disable the upload notification (which is mostly not needed when the app works properly), while still being able to keep the failure/conflict notifications.

**Comment by leofabri** [comment]
I think this app needs to handle sync (uploads) differently. 

When I'm sincing files, the notification keeps disappearing and reappearing for every single file that is being uploaded, that's frustrating. 
I would prefer it to show a progress bar instead.

**Comment by shtrom** [comment]
Sounds related to #261.

**Comment by jancborchardt** [comment]
Let’s switch this to https://github.com/nextcloud/android/issues/261 instead indeed, closing this as duplicate :)
