### ISSUE TITLE
Proposal: Add create file button

### ISSUE THREAD

**Issue by BikingGlobetrotter** [nextcloud/android#785]
Hi, 
this is not a bug report, but a feature proposal. When using the nextcloud app on android, I can press the plus button in the right lower corner. After that, I have the possibility to create a folder and two different options to upload a file. 
This is absolutely fine, but I am missing a functionality to create a file. Creating a file is specially useful in the Notes folder when using the Notes App. Having an option to create a file will also allow to paste simple text you received via WhatsApp etc. to your cloud. 
I attached possible future design.

![addfile](https://cloud.githubusercontent.com/assets/988227/24523728/52bfb492-1594-11e7-98b9-7c3881d9d2e5.png)

Best regards
Mischa

**Comment by mario** [comment]
Hi,

I don't think this is likely to happen as we want to keep minimal feature-list and not bloat the app. There are other applications that specifically work with NC Notes that might help you however.

What do you think @AndyScherzinger ?

**Comment by tobiasKaminsky** [comment]
You can already send text snippets to our app. You will see the regular upload chooser dialog and then can add a file name.
I hope this is enough? If we would include a text editor then this idea can be done on same time, I guess.

**Comment by AndyScherzinger** [comment]
I see it the same way as @tobiasKaminsky it might come at some point depending on the implementation of a basic text editor which @jancborchardt already proposed. So it could be done at that time while I also wouldn't position it that prominent by putting it into the FAB since it is not such a central feature. Plus like @mario mentioned there are native apps focusing on notes which are streamlined towards this topic.

**Comment by BikingGlobetrotter** [comment]
@tobiasKaminsky, I did not know about a feature sending selected text to NextCloud, but I tested it today and for my purpose, it is enough. Thank you. @AndyScherzinger, I agree that a feature to create text file might make sense as soon as / if we might have a basic text editor in NextCloud. I'm looking forward to that. Thanks all.

**Comment by tobiasKaminsky** [comment]
@BikingGlobetrotter glad to hear :-)
Closing it for now as discussed above, coming with text editor.
