### ISSUE TITLE
App automatically syncing without auto upload set

### ISSUE THREAD

**Issue by GemzzK** [nextcloud/android#7857]
### Steps to reproduce
1. Install app on android 10
2. Let it sit for few hours dont set any auto upload
3. App will start syncing root folders DCIM and Pictures including all sub folders.

### Expected behaviour
- we should select folders in auto upload to upload that folders.
### Actual behaviour
- without setting any auto upload folders app starts syncing and eats out all space because same folders are synced at two locations in server. Folders it auto syncs auto sets its path instant upload/0/DCIM. Path i set to auto sync folders is instant upload/DCIM. Its clearly app side issue not server.

### Environment data
Android version:

Device model: MI A2

Stock or customized system:
Stock
Nextcloud app version: 3.14.3

Nextcloud server version:20.0.5

Reverse proxy:no

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
I never heard about this, sorry to hear.
Can you see those folder configured in auto upload?
Maybe those config options are restored automatically via a backup?
