### ISSUE TITLE
"Share with" nextcloud option not usable anymore

### ISSUE THREAD

**Issue by orsotron** [nextcloud/android#7858]
It's no more possible to upload photo to nexctloud directly with the share option (from album app, etc.). 
When trying to upload with the share option, no error is returned and no upload is performed. This happens on SONY experia F5121 and Samsung A51 as well, both on 3.14.3 app version.
The only way possible is to use the add "+" button inside nexcloud app.

**Comment by ezaquarii** [comment]
Duplicate: https://github.com/nextcloud/android/issues/7859
