### ISSUE TITLE
SHARE WITH Option not allowed with nextcloud

### ISSUE THREAD

**Issue by orsotron** [nextcloud/android#7859]
### Steps to reproduce
1.  select any photo from album and click the share button (lesser sign with big dots on the tip);
2.  select nextcloud icon and select any folder on the nc account
3.  browser window is closed but no upload starts and no error message is displayed

### Expected behaviour
- in previous versions a background process was started, showing the NC icon in the toolbar and file was actually loaded in selected folder

### Actual behaviour
- Sadly, nothing hapens

### Can you reproduce this problem on https://try.nextcloud.com?
I could not be able to add the server in a new account (server not reachable)

### Environment data
Android version:
8.0.0
Device model: 
Sony Xperia F5121
Stock or customized system:
stock
Nextcloud app version:
3.14.3
Nextcloud server version:
19.0.5
Reverse proxy:

#### Web server error log
no log produced 

#### Nextcloud log (data/nextcloud.log)
no log produced 

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by ezaquarii** [comment]
Cannot reproduce on 3.14.3, OnePlus 6T.

We fixed an identical issue recently in 3.14.3, but it seems that this might be something different.

**Comment by orsotron** [comment]
it happens on samsung a51, android 10 as well

**Comment by meltzow** [comment]
can't reproduced on samsung S10, android 10, NC 3.14.3, on a nextcloud server 20.0.5

**Comment by GambaJo** [comment]
Dito on Samsung Galaxy S10 and Android 10 and Nextcloud App 3.14.1

**Comment by szaimen** [comment]
> Same problem on Samsung Galaxy S10 and Android 10 and Nextcloud App 3.14.1

Please update to at least version 3.14.3

**Comment by GambaJo** [comment]
Now it seems to work. Thx.
