### ISSUE TITLE
Camera auto upload has a significant delay before actually uploading ("Waiting to upload")

### ISSUE THREAD

**Issue by smkent** [nextcloud/android#786]
### Actual behaviour
I just migrated from ownCloud to Nextcloud. I enabled the automatic upload feature for camera photos, which I was also using previously in the ownCloud Android app. When I take photos with the camera, the new photos are placed in Nextcloud's uploads list and labeled "Waiting to upload" where they sit for some time before actually uploading.

I frequently used the automatic upload feature in ownCloud to take a photo with my phone and quickly have it available on my computer. The upload delay in the Nextcloud app is frustrating.

### Expected behaviour
New photos taken with the camera app should begin uploading immediately, as they did in the ownCloud app.
 
### Steps to reproduce
1. Enable auto upload for Camera photos
2. Take a photo
3. Observe the newly taken photo(s) are stuck in the Nextcloud app Uploads queue, labeled "Waiting to upload"

### Environment data
Android version: 6.0.1

Device model: Moto G4 Plus

Stock or customized system: Stock

Nextcloud app version: 1.4.2

Nextcloud server version: 11.0.2

### Screenshot

![screenshot_20170330-183347](https://cloud.githubusercontent.com/assets/2831985/24532933/0c8995a8-1579-11e7-97b0-d87bf1fa11de.png)

**Comment by Bullnados** [comment]
It's a feature not a bug.
This is intended.

**Comment by mario** [comment]
With Android 7, you cannot really decide anymore when to upload things. In addition, the delay is needed for HDR images and videos - otherwise they would not be uploaded properly.

This makes it more reliable, and reliability > speed - always.

**Comment by Bullnados** [comment]
Perhaps an option would be nice. "Save upload"(HDR), unsave(AsFastAs it is possible)

**Comment by AndyScherzinger** [comment]
we might finetune the wait in the future but it'll stay like that, here is a thought on Android development v6 to upcoming 9: Instant is dead! As hard as this may sound, it started with Doze in Android 6, got more aggressive in Android 7 also adding Jobs and killing instant right away and Android 8 will even stronger enforce this, so apps don't decide on this anymore, the OS does. So whenever you buy a device with Android 7 you will kind of have to say goodby to instant...

An option (happy to have @jancborchardt commenting on this) is something I don't see happening, it solves a problem that isn't really there, adds complexity to the UI and code to the code base that needs to be maintained, so except support an imho edge case there are only downsides in doing so.

Just my 2 cents....

**Comment by Bullnados** [comment]
This sounds logical for me. Thanks for this detailed description
