### ISSUE TITLE
UPLOAD CREATES TEMPORARY COPIES OF UPLOADED FILE, NEVER DELETED

### ISSUE THREAD

**Issue by orsotron** [nextcloud/android#7860]
### Steps to reproduce
1. browse to any folder of nc server in nc client app
2.  tap the add button and select any file; 
3.  upload starts and a copy of the file is created in the local app folder

### Expected behaviour
- temporary files (copy of the uploaded ones) should be deleted after upload

### Actual behaviour
- files are duplicated and never deleted

### Can you reproduce this problem on https://try.nextcloud.com?
Not able to connect app to the server

### Environment data
Android version:
8.0.0 and 10
Device model: 
Sony Xperia F5121 and Samsung A51
Stock or customized system:
Stock
Nextcloud app version:
3.14.3
Nextcloud server version:
19.0.7
Reverse proxy:

#### Web server error log
NA
#### Nextcloud log (data/nextcloud.log)
NA

**Comment by tobiasKaminsky** [comment]
Where do you see those files? 
For me /sdcard/Android/media/com.nextcloud.client/nextcloud/tmp/tobi@10.0.2.2%2Fnc/ is always empty after upload.

**Comment by z3ntu** [comment]
@tobiasKaminsky Maybe it's a different issue but I'm seeing copies of all uploaded files in Internal storage `Android/media/com.nextcloud.client/nextcloud/tmp/myuser@myserver/` 

The "On this device" tab in the sidebar only covers `Android/media/com.nextcloud.client/nextcloud/myuser@myserver/` 

I'm uploading my files via "Upload content via other apps" (rough translation), then select Google Photos app and select >100 photos/videos there at once.

If wanted I can also open a new issue for this.

**Comment by tobiasKaminsky** [comment]
@z3ntu yes, please create a new one and fill out entire template.

**Comment by z3ntu** [comment]
@tobiasKaminsky Thanks, created https://github.com/nextcloud/android/issues/10715
