### ISSUE TITLE
Recursive sync of folders

### ISSUE THREAD

**Issue by vojtapolasek** [nextcloud/android#7861]
### Is your feature request related to a problem? Please describe.

The desktop client can do two-way sync of whole folders with recursion. Is this planed also for the Android app? I have to use third party apps to do that and I think it is a pitty.

### Describe the solution you'd like
I would expect that in context menu on a folder or any file would be "sync" and if you enable it, then if anything is changed on the client or server, it would get synced.

### Describe alternatives you've considered
I am currently using third party app "Synchronize ultimate".

**Comment by cieska** [comment]
*

**Comment by TomasTokaMrazek** [comment]
AFAIK it is planned, the issue is 5 years old tho... On a bright side there has been some progress.

https://github.com/nextcloud/android/issues/285

Possible duplicate of  https://github.com/nextcloud/android/issues/19

**Comment by joshtrichards** [comment]
Duplicate of #269
