### ISSUE TITLE
{Bug} Photo never loads in Photo Gallery

### ISSUE THREAD

**Issue by omnath0** [nextcloud/android#7875]
Steps to Reproduce:-
+ Open the Nextcloud App
+ Go to the Photo tab from the top left side menu
+ Pull down the page to update

Expected Result:-
+ The photo gallery should update

Current Behaviour:-
+ It keeps on loading the page but never loads

NC Version:- Latest version (3.14.3) from play store (Released on 13th Jan 2021)
Phone:- S20 (Android 11)

**Comment by tobiasKaminsky** [comment]
Duplicate of #7376
