### ISSUE TITLE
Automatic upload is broken if subfolders shall be used

### ISSUE THREAD

**Issue by dajusc** [nextcloud/android#7879]
### Steps to reproduce
1. Configure Automatic Upload, enabling "Use subfolder"
2. If the subfolder already exists, everything works fine 
3. If the subfolder does **not** exists, upload fails with message "Conflict"

### Expected behavior
- Subfolder should be created if it does not exist and automatic upload should work

### Actual behavior
- Upload fails with message "Conflict"

### Environment data
Android version: 
11

Device model: 
Pixel 5

Stock or customized system:
Stock

Nextcloud app version:
3.14.3

Nextcloud server version:
20.0.5

Reverse proxy:
---

#### Web server error log
No related entries

#### Nextcloud log (data/nextcloud.log)
No related entries

### Additional info
Tested only for automatic upload with settings: "only on wifi" and "only during charging". Not  sure if this make any difference.

**Comment by tobiasKaminsky** [comment]
This works for me and others.
For each month there is automatically a new subfolder created.

So I fear this is something with your setup:
- which upload directory is specified?
- can you see something in nextcloud.log on server?

**Comment by dajusc** [comment]
The remote directory for upload is the default "/SofortUpload/Camera".
In nextcloud.log there were no related entries (as stated above).

Meanwhile I disabled "Use subfolder" and updated to App version 3.15.0.
So for testing I just re-enabled it, took a photo, plugged in the charger, and now it works as expected. :+1:
