### ISSUE TITLE
Update to Job lib version 1.1.9 when ready

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#788]
Auto uploads don't work when the phone is roaming and connected to an unmetered wifi, see https://github.com/evernote/android-job/issues/166

So whenever the stable is release we should upgrade right away.

**Comment by mario** [comment]
Ah, I just fixed this :-/

https://github.com/evernote/android-job/pull/167

**Comment by mario** [comment]
@AndyScherzinger I also think the guy reporting it misdiagnosed the issue, but we will see.

**Comment by danielkucera** [comment]
It's released! :) https://github.com/evernote/android-job/releases/tag/v1.1.9
