### ISSUE TITLE
[Feature Request] Option to disable notifications.

### ISSUE THREAD

**Issue by zion2k** [nextcloud/android#7882]
Hi,
it would be nice if there is an option in the settings to disable the notifications for this client.
Background: I am using the client on my Android car audio and I don't need the notifications on the radio, they are rather annoying  in this case.

Thanx in advance.

**Comment by AndyScherzinger** [comment]
The notifications are separated into different channels which you can individually disable via Android it self through Android's Application settings. Would that do the trick for you?

**Comment by zion2k** [comment]
Thank you for the quick help. This solved my "problem".
I haven't thought of the Android notification setting.
