### ISSUE TITLE
App does not ask for a passcode

### ISSUE THREAD

**Issue by dcharalambous** [nextcloud/android#7886]
### Steps to reproduce
1. Launch app on Android 

### Expected behaviour
- The app should ask for a password (has already been set)

### Actual behaviour
- Occasionally, the app does not ask for a pass code. This happens randomly, and is not consistent behavior. 

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 10

Device model: Samsung Galaxy S9+

Stock or customized system:

Nextcloud app version: 3.14.3

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Is this about pin (built in credential check) oder passcode?

**Comment by dcharalambous** [comment]
Yes, it's about the 4-digit PIN.

**Comment by tobiasKaminsky** [comment]
There is a fix, where the app does not ask for it at first opening after restart.
Can you try 3.15.1 RC1 available via beta program of Gplay?
