### ISSUE TITLE
2FA via notifications are complex to negotiate

### ISSUE THREAD

**Issue by politas** [nextcloud/android#7895]
### Problem

Using NextCloud notifications 2FA method pops up an Android notification telling you that there is a "NEW NOTIFICATION". Clicking on that Android notification opens the main NextCloud view, so you have to then click on Notifications, and then finally click the "approve" button.
 
![Screenshot_20210125-161041~2.png](https://user-images.githubusercontent.com/2109967/105664340-88008c80-5f28-11eb-8091-22d40f0c40bd.png)

### Describe the solution you'd like

Ideally, the Android notification would contain all the information about the login request and allow approval directly without having to open the NextCloud app at all.

### Describe alternatives you've considered

Alternatively, at least open the the app's Notifications view directly when the Android notification is selected.

**Comment by tobiasKaminsky** [comment]
This is a bug in our current 3.14.x version, which will be fixed with 3.15.0.
