### ISSUE TITLE
No instant update of folder list when changing active account (Nextcloud beta Android-App 20160621)

### ISSUE THREAD

**Issue by jgrete** [nextcloud/android#79]
### Actual behaviour

No "instant" update of the files list after choosing a different account from the dropdown. 

One have to wait until the screen gets locked. After unlocking the screen the files list is getting updated (caused by an event ?). Manually updating the account (via '...' menu) works well. In no case there's any visual feedback (except the changing files list) which might be suboptimal.
### Expected behaviour

Choosing a different account should lead to an instant update of the files list so one can see the directory structure of the recently choosen account 
### Steps to reproduce
1. Have two different accounts ready to use with different files/directories
2. have a look on the current files list
3. choose the other account
4. have a look on the current files list and notice it's **NOT** the files list of the current but the previous account
5. wait until the lock screen appears
6. unlock the screen and notice that now you see the proper list
### Environment data

Android version: Android 6.0.1

Device model: Samsung SM-G900F  (S5 klte)

Stock or customized system: customized CM 13.0

Nextcloud app version: Nextcloud beta Android-App 20160621

Nextcloud server version: 9.0.50
#### Web server error log

```
Insert your webserver log here
```
#### Nextcloud log (data/nextcloud.log)

```
Insert your Nextcloud log here
```

**Comment by tobiasKaminsky** [comment]
Is this still happening with latest dev version for you?

**Comment by jgrete** [comment]
Ohh, sorry just forgotten that case.
No, it's ok with version 20171220
Thanks alot
Juergen
