### ISSUE TITLE
Remove Auto upload

### ISSUE THREAD

**Issue by levster69** [nextcloud/android#790]
I posted this on Nextcloud site, but this is probably more appropriate.

I have recently updated my Samsung S7 to Android 7.0 and with it the Nextcloud app somehow also "updated".

The recent 1.4.2 update added the Auto upload feature, which I dislike very much. I do not want my Videos and Photo files to be going to the same directory. I cannot now separate the upload of video to wifi only. I want the pics to be uploaded at all times, while video only on wifi. 1.4.2 broke that. Before android 7.0 came out, I downgraded the nextcloud to 1.4.1 and restored the ability to upload separately. However, now that the system updated I "gained" the auto upload, no matter what I do. I even tried to downgrade to 1.4.0, and still see that retched auto upload feature.

So, my question is, how do I re-enable the ability to select separate folders for video and photo, AND the ability to upload different files over cellular or wifi?

Thank you,

Lev

**Comment by mario** [comment]
Hello,

I am sorry, but "Auto Upload" is here to stay, in one way or another (might be renamed once we have real sync functionality). We are already thinking how to separate photos and video for the Auto Upload in a meaningful way.

Cheers,
Mario

**Comment by levster69** [comment]
Understood. However, is there a way to revert and be able to use an older APK with 7.0? I could stick with the older version till the next update hits.

**Comment by AndyScherzinger** [comment]
@levster69 unfortunately no, since the old instant upload mechanism doesn't work anymore on Android 7 due to changes within the OS the mechanism doesn't work anymore (New Picture/Video broadcasts aren't sent to applications anymore and a limited to the OS for processing). 

I do hope though that images/video will be separated in the upcoming release.

**Comment by tobiasKaminsky** [comment]
We had already a discussion how to handle different file types or file sizes.
I try to find this...

**Comment by tobiasKaminsky** [comment]
https://github.com/nextcloud/android/issues/486
@levster69 maybe you want to join the discussion over there?
