### ISSUE TITLE
Lost all notes on device after reactivating app on server ... sad day.

### ISSUE THREAD

**Issue by Schrebergarten03-links** [nextcloud/android#7900]
So the notes app was deleted on the server by mistake or update i dont know. But i used the app on mobile with existing account for a year or longer without noticing.

And since the connection error pops up only for a second and is very small i missed it on slow device.
As i was starting to use notes app on a 2nd mobile i realized that notes on server wasnt working anymore.

Reactivated notes on server. Notes folder was missing too.

After that my mobile notes app reconnected with server and deleted all notes of 3+ years i had without any warning or asking.
And since the notes folder on server was empty i cant undelete.
Thats very bad for me and imho this should not be possible.

### Expected behaviour
When resyncing account on mobile app and there is a big difference in notes, like time or amount ask what to do and never just delete !

### Actual behaviour
All notes on mobile get deleted. :(

ps: is there a possibility to undelete notes on mobile android app ? Didnt find out where cache is saved ...

**Comment by InfamousUser** [comment]
I was alwyas scared of losing notes, that's why I still haven't moved to Nextcloud. This sort of thing should be impossible, there should be multiple safeties to prevent this sort of thing, also any bulk deletion should require explicit user confirmation, including when syncing - never sync if there's a significantly-out-of-the-ordinary amount of changes, at best copy the data and mark it as such.

**Comment by szaimen** [comment]
cc @stefan-niedermann

**Comment by stefan-niedermann** [comment]
First of all: Sorry for the inconveniences. We try to support each and every environment, but this is not Google or Amazon, where we have a*single* server and always know the environment.

Have you checked the trashbin of your Nextclouf instance? The Android app does not *delete* any note on your server. It asks the server app to do it and then they are moved to the trashbin.

> Reactivated notes on server. Notes folder was missing too.

Then how should the android app display any notes? If the notes folder on the server is empty, the Android app of course can't display any notes.

> When resyncing account on mobile app and there is a big difference in notes, like time or amount ask what to do and never just delete !

Again: The Android app does not delete anything. When syncing the first time and the app **asks** for the list of notes. It does *not* say "uuh, give me a list of your notes then i can send a delete message for each".

> I was always scared of losing notes, that's why I still haven't moved to Nextcloud. This sort of thing should be impossible, there should be multiple safeties to prevent this sort of thing, also any bulk deletion should require explicit user confirmation, including when syncing - never sync if there's a significantly-out-of-the-ordinary amount of changes, at best copy the data and mark it as such.

This is unfortunately not helpful in any way. You are welcome to improve the behavior, it's all open source. We are doing our best to check any environment, but as i said - your comment does not help in any way.

So, i suppose to calm down, check the trashbin for the Notes and then check your server logs for a hint why the notes might have been deleted. They aren't just fallen down a rabbit whole. There's a reason why they were gone and any hint about what went wrong or unexpected will help to prevent this case in the future.

**Comment by AndyScherzinger** [comment]
@stefan-niedermann the reason from what I interpret form the description is that the  removal of the notes app on the server deleted the notes folder which of course clients will sync too. So the real issue would be that a notes-serverside-app removal should not delete files.

Other than that 
* does the server admin do backups which could bring back your notes files?
* files on the Android client are stored in the place you can see in the settings screen (storage path)

**Comment by stefan-niedermann** [comment]
> files on the Android client are stored in the place you can see in the settings screen (storage path)

I was referring to the Notes Android app, which stores the notes in a database 😉  Not the Nextcloud Android app

**Comment by stefan-niedermann** [comment]
cc @korelstar for information (maintainer of the server side notes app)

**Comment by korelstar** [comment]
> @stefan-niedermann the reason from what I interpret form the description is that the removal of the notes app on the server deleted the notes folder which of course clients will sync too. So the real issue would be that a notes-serverside-app removal should not delete files.

The removal of the server-side notes app does not delete any notes! There is no such behavior. Notes are stored as files in the filesystem. All files are kept, even if you remove the app. You will still have access to your notes using any Text editor, even if the notes app is not installed.

**Comment by Schrebergarten03-links** [comment]
> @stefan-niedermann the reason from what I interpret form the description is that the removal of the notes app on the server deleted the notes folder which of course clients will sync too. So the real issue would be that a notes-serverside-app removal should not delete files.
> 
That the point ...
The data loss isnt tragic for me just inconvinient but this should not happen. This is a case that is hard to predict ... (DAU) ;)
But should be "fixed"

What happen in short order:

1. Used Notes App on android and installed on server worked fine. Was using account xy.
2. deinstalled notes app on server and folder was deleted. Account xy wasnt deleted.
3. used notes app on android with accocunt xy as if notes app on server was still installed ... connection error was to small and short never noticed it for ~1.5 years.
4. new Phone with bigger screen noticed error first time .... checked server found notes app missing.
5. reinstalled netes app on server... notes folder empty and too long deleted no backup or trashcan.
6. App on android actually synced with acc xy first time in 1.5 years.  Folder empty on server ...
7. Notes on android app instantly gone - no warning nothing. ... This should be fixed ;)

So i hope u could understand the problem ...  As is said ... im posting here for a future solution not with anger ;)

I love what you do and im a OSS migrator.
thx for your work ;)

**Comment by korelstar** [comment]
>     2. deinstalled notes app on server and folder was deleted. Account xy wasnt deleted.

As said, there is no automatism for this. Did you deleted the notes folder manually? Maybe by accident?

**Comment by Schrebergarten03-links** [comment]
1.5 years ... i really dont remember ...  doesnt matter imho ... 

The app should still ask if it should delete all notes.
At least there should be a setting for this behaviour ... 

There may be a usecase  to remotly delete notes on mobile device without asking if device is stolen or lost.

But this could be an option ;)
