### ISSUE TITLE
Force Close App After Second Login

### ISSUE THREAD

**Issue by antarezaghifary** [nextcloud/android#7904]
### Steps to reproduce
1. When I logged in first and already entered the dashboard of the application
2. I tried to exit the application by removing the account and after successfully logging out I tried to log in again
3. After I click the application login button tries to enter the dashboard page after that the application exits and force close itself and there is an error that is listed like this
### Expected behaviour
- Can enter perfectly without any force close

### Actual behaviour
- After second login force close apps by itseft
![aa9889aa13a3557bae424ea7343fa20ad0447727](https://user-images.githubusercontent.com/27753675/106106481-2cc4d900-6178-11eb-8586-09a3fd2e5dca.png)

### Environment data
Android version: 8 and 10

Device model:  Asus MPM1 and PIXEL 3A XL

Stock or customized system:

Nextcloud app version: Latest Version 3.14.3

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by szaimen** [comment]
@antarezaghifary which Nextcloud version is installed on your server?

**Comment by antarezaghifary** [comment]
@szaimen  version 13.0.7

**Comment by szaimen** [comment]
Hm... I thought it would be https://github.com/nextcloud/android/issues/7075#issuecomment-706900209 but doesnt seem to be the case.
@AndyScherzinger any idea what it could be?

**Comment by antarezaghifary** [comment]
@szaimen  wow thank you sir. 
Should I go back to version 3.13.0? And what many features are not ready in version 3.13.0? if so, what features?

**Comment by szaimen** [comment]
> Should I go back to version 3.13.0?

If version 3.13.0 works for you, I would suggest to do so, yes 👍

**Comment by AndyScherzinger** [comment]
Afaik @tobiasKaminsky worked on the client lib recently and @ezaquarii on the user/account object so they might be able to shed some light on this. Other than that looking at https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule Server v13 is end-of-life since 2019 (!) So the client might break at any point in time anyways (!)

**Comment by antarezaghifary** [comment]
Okey thanks you All..

**Comment by ezaquarii** [comment]
@AndyScherzinger 

It crashes calling this semi-legacy API:

```
public static NextcloudClient createNextcloudClient(Account account, Context appContext)
```

It does not use `User` API, but the platform `Account`. Inside the call, it tries to obtain an account name, but the account manager returns `null`, which in turn blows up a `Credentials.basic()` constructor that has non-nullable arguments.

> I tried to exit the application by removing the account

TBH, I'm not sure what does it mean. Normally you exit the application by swiping the window off recent apps view or by using force close. Did the author remove account from Android settings view and try login again?

Anyway, if account removal was involved at runtime, it could explain why suddenly `AccountManager` cannot resolve `Account` into account name.
