### ISSUE TITLE
after choosing an as "favourite" marked FILE from the top level favourite section, the file contents remain visible even after choosing the "all files" top section.

### ISSUE THREAD

**Issue by sby68** [nextcloud/android#7906]
### Steps to reproduce
1. mark a text file - in my case a markdown-file - as favourite ("add to favourites")
2. move to the "favourites" top level section
3. open the text file from there
4. leave the file again via the "back" button (top left arrow)
5. the content of the text file remains visible
6. choose the "all files" top level section
7. the content of the text file still remains visible

### Expected behaviour
the text file contents should be replaced after leaving the file ...
 - by the main menu after leaving the file 
 - by the list of directories/files after choosing the "all files" section

### Actual behaviour
the text file contents remain visible even after choosing the "all files" section

### Can you reproduce this problem on https://try.nextcloud.com?
I tried, but this problem can't be reproduced there because Android uses a different app to edit the text file than the server.

### Environment data
Android version:
8.1.0

Device model: 
Blackberry KeyOne

Stock or customized system:

Nextcloud app version:
3.15.0 RC1
(same behavior as 3.14.1)

Nextcloud server version:
NC 20
(same behavior as NC 19)

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
What happened when you clicked on the file?
Was it only shown (read-only) or was it opened in Nextcloud Text, so you could collaborate with other?
Does this happen only with favorited files?

I ask, so that I can try to reproduce it.

**Comment by sby68** [comment]
Hi Tobias,

After clicking on the file it opens, just as expected.
It is opened "read only". To edit it I have to explicitly choose to do so.

This happens only to files opened from the favourite section.
Text files opened elsewhere show the correct main menu after leave.

Cheers,
Ingo

**Comment by tobiasKaminsky** [comment]
I thought i understood the problem, but it seems to work for me:
- mark a text file as favorite
- open drawer, choose "favorites"
- wait until all favorited files are loaded
- click on said text file
--> it opens in NC text editor
![2021-02-25-083138](https://user-images.githubusercontent.com/5836855/109118660-e2695480-7743-11eb-846f-038441992470.png)

**Comment by sby68** [comment]
The problem is not the opening.
Opening works well.
Entering Edit mode, editing, everything is fine.

The/my problem comes with leaving the file.
The top of the screen gives me the "hamburger" menu, the search field and the accounts icon.
But the main screen still shows the contents of my file.

It doesn't show my favourites, where I came from. It's still the content of my file what I see.

I can use the hamburger menu.
When I "initialize" the content area by
- choosing "activities": the content area is replaced by the activities content
- choosing "favourites": the content area is replaced by the favourites content

So the initialization of the content area doesn't work under the said circumstances.
At least for me.

I am sure you'd see immediately what I face, if it happened at your phone.

BTW, I tested the Nextcloud Notes App (Version 3.1.3)
Entering and leaving a file marked as favourite, works there.
But ... Entering and leaving a file marked as favourite, works as well with the NC text editor, if I open it elsewhere, NOT from the favourites-section!

Please have a look at the screenshot, taken immediately after leving the text editor.
Hope this helps.

**Comment by tobiasKaminsky** [comment]
Can you illustrate this with some screenshots?

**Comment by sby68** [comment]
yes, sure.

At the 4th picture you can see the nextcloud "heading"-line with the search widget.
The (what I call) content section is still showing my file contents.

Do you need more pictures?
May we have a Jitsi-meeting where we could have a live demonstration?

**Comment by tobiasKaminsky** [comment]
Seems that there are no images :/

**Comment by AndyScherzinger** [comment]
Images are lost on email replies, so this needs to be done via Githubs web interface!

**Comment by sby68** [comment]
... better now?

05.03.2021 08:47:02 Tobias Kaminsky <notifications@github.com>:

**Comment by AndyScherzinger** [comment]
No, you still reply by mail...

**Comment by sby68** [comment]
![40 after choosing favourites again](https://user-images.githubusercontent.com/76809717/110086716-03a8f100-7d93-11eb-9fdf-017551140594.png)
![20 just opened the file](https://user-images.githubusercontent.com/76809717/110086721-04418780-7d93-11eb-9988-ebf3ddbc4eb2.png)
![10 my favourites](https://user-images.githubusercontent.com/76809717/110086726-04418780-7d93-11eb-806b-2ce25c27145f.png)
![30 left file immediately by clicking top left arrow](https://user-images.githubusercontent.com/76809717/110086727-0572b480-7d93-11eb-8950-76ec9da7566e.png)

**Comment by sby68** [comment]
right, Andy!
read your mail too late.
Strictly fifo 😏

**Comment by AndyScherzinger** [comment]
Thanks @sby68 🙏

**Comment by tobiasKaminsky** [comment]
For me it is like this:
![2021-03-08-081851](https://user-images.githubusercontent.com/5836855/110287509-ed936e80-7fe6-11eb-87c2-bf9f4eb4d7c9.png)
![2021-03-08-081848](https://user-images.githubusercontent.com/5836855/110287524-f4ba7c80-7fe6-11eb-9ea9-f2342f0b8763.png)
 ![2021-03-08-081844](https://user-images.githubusercontent.com/5836855/110287523-f3894f80-7fe6-11eb-9a14-bbe163f8ac7c.png)

So, opening file, going back and see file list again.

**Comment by sby68** [comment]
Hi Tobias,
it seems, I am the only one facing this behaviour.
That somehow gave rise to the idea to try a reinstall of the nextcloud client.
And - what can I say - **it solved my problem** :-)
Thank you very much for your support!
I appreciated very much to have company to solve the "bug".
Thanks again,
Ingo
