### ISSUE TITLE
Auto Upload: IPv6 fallback to IPv4 does not work

### ISSUE THREAD

**Issue by mm28ajos** [nextcloud/android#7907]
### Steps to reproduce
1. Have a nextcloud instance running which is accessible by a domain's A-record IPv4.
2. The same domain has a AAAA-record which does not represent an IPv6 address by which the nextcloud instance is accessible.
3. The android device with the nextcloud app has both, an IPv4 address which allows connection to the nextcloud instance IPv4 network and a GUA IPv6 address.
4. A folder is marked to be synced with the nexcloud instance in the app e.g. the camera folder.
5. Capture an image which is then automatically tried to be uploaded to the nextcloud instance.

### Expected behaviour
- The upload should work i.e. the upload should recognize that the IPv6 connection does not work and should fallback to the working IPv4 connection.

### Actual behaviour
- The upload is stuck and only proceeds if the GUA IPv6 is removed from the android devices network interface.

### Can you reproduce this problem on https://try.nextcloud.com?
How can I get the password of the test account?

### Environment data
Android version: 11

Device model: Pixel 3a

Stock or customized system: stock

Nextcloud app version: 3.14.3

Nextcloud server version: 20.0.5

Reverse proxy: nginx 1.19.6

**Comment by PVince81** [comment]
Both my wife and my phone started to not be able to connect to my IPv4 only server. But this is only when on Wifi inside our network.

When accessing via mobile network it works fine.

@mm28ajos have you tried both from inside and outside ?

**Comment by PVince81** [comment]
my app version is 3.15.0

**Comment by mm28ajos** [comment]
Yes from my mobile connection, which does not provide an IPv6 address, it works fine. 

Do you have an AAAA record set for your nextcloud domain and does your homework is ipv6 capable? If so, try removing the AAAA record from the nextcloud domain. This worked for me but I lost the ability to have ipv6 connections :( I assume the app prefers to establish an IPv6 connection but is not able to fallback to ipv4 in case the ipv6 connection can not be established.

**Comment by mm28ajos** [comment]
I spotted the issue because my ipv6 AAAA record update script was broken but ipv4 A record was still correct. In this situation, the upload only worked if the phone did not have an IPv6 address by it self and so could not try to make an IPv6 connection.

**Comment by tobiasKaminsky** [comment]
If your NC server is reachable via v6 it also must be configured to work correctly with it.

**Comment by PVince81** [comment]
for the record: I was able to debug today by looking at logcat and found out that my issue wasn't related to ipv6 but was just DNS caching issue on Android of my old ipv4 public address.

**Comment by mm28ajos** [comment]
@tobiasKaminsky so it's not intended that the app can fallback from ipv6 to ipv4 in case the domain has both DNS records set?

**Comment by KopfKrieg** [comment]
> If your NC server is reachable via v6 it also must be configured to work correctly with it.

IPv4 should be used as fallback if IPv6 is not working (and vice-versa). Things like this can happen, and the software should be able to work with it (and usually do, e.g. browsers).
