### ISSUE TITLE
NextCloudDev crash

### ISSUE THREAD

**Issue by Tryweirder** [nextcloud/android#7909]
### Steps to reproduce
1. Open NextCloudDev App
2. Let files load
3. Move privacy policy.txt to notes folder

### Expected behaviour
Crash

### Actual behaviour
Crash

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 10

Device model: a10e

Stock or customized system:custom build rev1.0

Nextcloud app version:?

Nextcloud server version:?

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
@Tryweirder can you please post the crash log? In case of a crash it should have been copied to your clipboard 🙏
