### ISSUE TITLE
Improvement: arbitrary synced folders

### ISSUE THREAD

**Issue by realulli** [nextcloud/android#791]
### Actual behaviour
- The defined folders sync fine. However, there doesn't seem to be a way to define a custom folder to autoupload (or sync) to the server.

### Expected behaviour
- I would like the ability to define a folder that is not just images or videos but other files to be automatically uploaded to the server.
- The client should monitor that folder (or even check every couple of minutes) if files have changed or have been added.
- When a file has been stable for a configurable time span, it gets uploaded to the associated folder on the server.
### Rationale
I'm running the GpxPod plugin on the server, my devices record GPX tracks when I'm using OSMAnd. I'd like to upload the generated tracks automatically. 

I can imagine there are other applications that generate data files that someone might want to upload, e.g. backup files from some application that isn't in the cloud.

### Environment data
Nextcloud app version:
1.4.1
Nextcloud server version:
11.0.2

**Comment by tobiasKaminsky** [comment]
This is already planned in https://github.com/nextcloud/android/issues/285 but unfortunately we currently do not have an ETA.

**Comment by mario** [comment]
This is available in 2.0 RC9.
