### ISSUE TITLE
Cannot download anything

### ISSUE THREAD

**Issue by Orybon** [nextcloud/android#7914]
Hi,

Both and my wife cannot use anymore the app on our Android devices.

I checked the permissions, the app autorisation to write medias on phone is enabled.

### Steps to reproduce
1. Try to download any file
2. Get an error in french as it's my language "Impossible de télécharger <file>" meaning "Cannot download <File>"

### Expected behaviour
- The file should be downloaded

### Actual behaviour
- The file isn't downloaded and i get an error notification from nextcloud app

### Can you reproduce this problem on https://try.nextcloud.com?
Exactly the same behaviour with the demo instance.

### Environment data
Android version: 11
Device model: Google Pixel 4a
Stock or customized system: Stock
Nextcloud app version: 3.14.3
Nextcloud server version: 20.0.2.2
Reverse proxy: Traefik 2.2.1

#### Web server error log
```
Everything is fine there.
```

#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"hV0uhGTqV2TYgTl76fqE","level":1,"time":"2021-02-02T07:42:35+00:00","remoteAddr":"REMOVED","user":"REMOVED","app":"no app in context","method":"GET","url":"/remote.php/webdav/Documents/53878246.pdf","message":"Deprecated event type for {\"[object] (OCP\\SabrePluginEvent)\":{\"*statusCode\":200,\"*message\":\"\",\"*server\":{\"[object] (OCA\\DAV\\Connector\\Sabre\\Server)\":{\"tree\":\"[object] (OCA\\DAV\\Connector\\Sabre\\ObjectTree)\",\"*baseUri\":\"/remote.php/webdav/\",\"httpResponse\":\"[object] (Sabre\\HTTP\\Response)\",\"httpRequest\":\"[object] (Sabre\\HTTP\\Request)\",\"sapi\":\"[object] (Sabre\\HTTP\\Sapi)\",\"*plugins\":[],\"transactionType\":null,\"protectedProperties\":{\"...\":\"Over 20 items, aborting normalization\"},\"debugExceptions\":false,\"resourceTypeMapping\":[],\"enablePropfindDepthInfinity\":true,\"xml\":\"[object] (Sabre\\DAV\\Xml\\Service)\",\"*listeners\":{\"...\":\"Over 20 items, aborting normalization\"},\"*wildcardListeners\":[],\"*listenerIndex\":[],\"*logger\":null}},\"Symfony\\Contracts\\EventDispatcher\\EventpropagationStopped\":false}}: null","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.14.3","version":"20.0.2.2"}
```

**Comment by stemy2** [comment]
Same problem. I can view the files,  audio files can be played, i can see the download progress but then i see the message "download failed".

**Comment by tobiasKaminsky** [comment]
It works on my Android 11, which makes it hard to fix :S

Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

**Comment by Orybon** [comment]
This issue seems to be "magically" solved. No idea How.

**Comment by stemy2** [comment]
The problem is still there for me. I made a logcat during a failed download.

[logcat.txt](https://github.com/nextcloud/android/files/6029536/logcat.txt)

**Comment by tobiasKaminsky** [comment]
> 02-23 15:32:17.360 29794 32026 I DownloadFileOperation: Download of /Musique/ I Get Around.mp3 to /storage/emulated/0/Android/media/com.nextcloud.client/nextcloud/pierre@nextcloud.domain.com/Musique/ I Get Around.mp3: Error while moving file to final directory

Does this folder exist? 
Is there enough space?

**Comment by stemy2** [comment]
Yes, the folder exists and i have enough space.

**Comment by tobiasKaminsky** [comment]
Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

**Comment by stemy2** [comment]
Why are you asking me my logcat since i already gave it to you ?

**Comment by tobiasKaminsky** [comment]
Ah, right…I mixed up issues…

On settings within the app you can choose another storage location.
Can you try others please? 
It might be something with Android 11…
