### ISSUE TITLE
Latest nightly Android client upload issues with MP4 and jpg images

### ISSUE THREAD

**Issue by WzL** [nextcloud/android#792]
### Actual behaviour
-Using the instantupload feature, and also, using the manual upload of JPG pictures and MP4 movies to my private NextCloud server I am not able to view the iconized listed inividual file preview of JPG files in the Android nightly client nor am i able to play the MP4 movies uploaded by the nightly android nextcloud client. Onscreen Message when opening the files using the Nextcloud nightly android client: large black exclamation icon with the message "Picture could not be displayed" or with the MP4 movies i can open the MP4 file using the android nightly client but after 5 seconds it presents the following message: "Media could not be displayed using the default mediaplayer". The messages could be slightly different  because they are presented in an other language then English, being Dutch, which is the default language on my phone.
What is also strange is that other content (both pictures and Movies) uploaded using the stable android Nextcloud client are displayed correct by the Nextcloud nightly android client, listed individual iconized preview is displayed, and content uploaded bij the nextloud android stable client can be opened and played. The issue here is that I am not able to open or play Content uploaded by the Android nightly client using the nextloud android nightly client.  All Pictures which I am not able to open with the nightly Android client also have the same file icon: a grey icon with gray mountain tops and grey circle (sun?) for pictures. 

Also i noticed that, when I close the nightly Nextcloud android client en open the latest stable NextCloud android client, I can see the all the pictures being displayed correctly (listed miniatures preview icons) and i can also view and play both the pictures and the MP4 movies which i was not able to see and play using the, and uploaded by, the nightly Nextcloud android client. 

### Expected behaviour
-Uploaded pictures (JPG) should be listed correctly in the internal file viewer by small preview icon of movie and picture using the nightly Nextcloud android client. Also when selecting and opening the JPG  picture or MP4 movie it should open and display the photo or open and start to play the MP4 file using the internal movie player.
 
### Steps to reproduce
1. Open Nightly Nextcloud android client 
2.  Upload content (JPG or MP4)
3. Try to open/view the uploaded content (of step 2)  in the nightly Android Nextcloud client, notice failure.
4. close nightly nextcloud android client
5. Open stable nextcloud android client
6. Try to open the uploaded content of step 2, notice succes. 

### Environment data
Android version: Lineage OS - android 7.1.1

Device model: 
Lenovo ZUK Z2

Stock or customized system:
Customized

Nextcloud app version:
Latest stable 1.4.2 and ~~latest~~ nightly 20170317

Nextcloud server version:
Nextcloud 11.0.2 (stable)

#### Web server error log
To be determined - open

Insert your webserver log here
To be determined - open

#### Nextcloud log (data/nextcloud.log)
To be determined - open

Insert your Nextcloud log here
To be determined - open

**Comment by mario** [comment]
Dear users,

thank you for your patience. After lots of work, we’re super excited to be able to give you a test version with new auto upload implementation. Keep in mind we will only accept bugs related to Auto Upload in this APK, as other things might be broken.

https://cloud.nextcloud.com/s/ftZraTruRQjTe0R

This is a dev APK so it will not overwrite your existing play store/f-droid APK unless you’re already running dev version. Also, you might need to remove your existing dev version before installing this one.

Explanation of the current functionality:
- added support for custom folders
- separated image and video folders
- checks for new files happens every 15-20 minutes
- automatic retry every 15-20 minutes or when you force close/open the app
- automatic pause once network is changed (untested!)
- significantly less battery usage

All and any testing is more than appreciated, especially with large and ever-going files like Videos. (like, try to record a 30 min video).

Let me know if you’ve got any questions.

Cheers,
Mario

**Comment by tobiasKaminsky** [comment]
No response within the last month, therefore closing.
Please feel free to reopen with additional infos, if the problem still exists.
