### ISSUE TITLE
Shares wrong folder

### ISSUE THREAD

**Issue by Jebop** [nextcloud/android#7925]
Hello, 

I have a folder (A). This Folder contains a subfolder (B). 
If i want to share the subfolder (B) by pressing the symbol to the right of the the subfolder name and typing in a E-Mail adress and select the Email option that pops up after a few seconds, the auto generated Email contains a Link to the Folder (A) and the subject of the Email is "(Username) has shared »(A)« with you" (translated from german) instead of the actual selcted file (B). 

### Steps to reproduce
1. Create a Folder (A)
2. create a subfolder (B)
3. share the the subfolder (B) by E-Mail 
4. type in the email and select the Email option that pops up

### Expected behaviour
- a email is generated that contains a Link to folder (B) and the subject "(Username) has shared »(B)« with you"
- worked on 3.14.3

### Actual behaviour
- a email is generated that contains a Link to folder (A) and the subject "(Username) has shared »(A)« with you"

### Can you reproduce this problem on https://try.nextcloud.com?
- works as expected on the Nextcloud server version 

### Environment data
Android version: 8.1.0

Device model: Galaxy Tab A (2016) SM-T580

Stock or customized system: 

Nextcloud app version: 3.15.0

Nextcloud server version: 20.0.6

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```
no logs 

```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Can you test #7992  ?

**Comment by Jebop** [comment]
Thanks for your answer 
Sharing works as expected again with the new #7992 .apk but i also get the errors instead of the names.

**Comment by tobiasKaminsky** [comment]
I think this is about having both apps installed in parallel.
Today there will be a 3.15.1 RC1, available on Play Store, which you can test again.
