### ISSUE TITLE
Stable F-Droid release is 2 months old & broken

### ISSUE THREAD

**Issue by DragonQ** [nextcloud/android#7926]
I use the F-Droid release so that I can easily revert to old versions. This helps avoid the unfortunate situation where a buggy version has been pushed to Google Play and not remedied for days or weeks.

The latest stable release available on F-Droid (3.14.1) is now 2 months old and very broken, given a fundamental feature (sharing to Nextcloud) doesn't work. This was fixed in 3.14.2 but that version is not available via F-Droid. Neither are 3.14.3 or 3.15.0. Why is this?

**Comment by AndyScherzinger** [comment]
Because f-droid builds and releases the app itself this is nothing a project can do

https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8294 pushed for 3.15.0 and should become available in the next days.
