### ISSUE TITLE
Auto upload by date

### ISSUE THREAD

**Issue by Doomsdayrs** [nextcloud/android#7927]
### Is your feature request related to a problem? Please describe.
I don't want to auto upload data that I consider new and often used

### Solution
Option to limit auto upload by date

### Alternatives
Better multi selection options, such as in between or fitting to a certain criteria

**Comment by Derkades** [comment]
Or another example: upload photos immediately so they're safe, but only delete them from the device after x days/months

**Comment by cieska** [comment]
> Or another example: upload photos immediately so they're safe, but only delete them from the device after x days/months

I would like to have that function too. It could be an option to release the phone memory from selected folder to files that older than...

**Comment by joshtrichards** [comment]
Duplicate of #2323 

I suggest subscribing to that issue to track progress and/or giving it an upvote :+1:
