### ISSUE TITLE
Rebuild beta branch

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#793]
@tobiasKaminsky with all the latest structural changes done to master, would it make sense that recreate a beta branch based on the master, or do you think it is possible to actually update the existing beta branch with the master? Due to the structural changes basically all branches will have conflicts with the beta branch.

**Comment by tobiasKaminsky** [comment]
I have this on my roadmap, the idea is
- have a new branch "nightly base" or something like that with all the needed changes, like app name, provider names, ...
- rewrite my build scripts to include this branch
- make the possibility to start with one command from scratch / new

It is scheduled for next week.

**Comment by mario** [comment]
@tobiasKaminsky provider names are now changed via setup.xml - just fyi, so that makes it easier.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky nice, while with all the latest reports and confusions I think we should rename it back to beta since with nightly people expect a build every night with a publish every night. So beta released numerous times a week than having to explain this over and over again until the end of time. ;)

**Comment by tobiasKaminsky** [comment]
Closing this one as #712 has a more detailled description.
