### ISSUE TITLE
Will not upload pictures or videos on mobile data even when "Only upload in unmetered WiFi" not checked

### ISSUE THREAD

**Issue by Rudder2** [nextcloud/android#7934]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
- Should upload with mobile data

### Actual behaviour
- Says "Waiting on Unmetered WiFi to upload"
![Screenshot_20210204-133506_Nextcloud.jpg](https://user-images.githubusercontent.com/43488150/106948343-3490fa00-66f1-11eb-813e-01bbdcc2b2d1.jpg)
![Screenshot_20210204-133417_Nextcloud.jpg](https://user-images.githubusercontent.com/43488150/106948387-41ade900-66f1-11eb-81bd-c082d6a3ef20.jpg)

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:
10
Device model: 
OnePlus 6t
Stock or customized system:

Nextcloud app version:
3.14.3
Nextcloud server version:
20.0.6
Reverse proxy:
CloudFlare
#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
What kind of wifi do you connect to?

**Comment by Rudder2** [comment]
I never connect to WiFi. I will never connect to WiFi. I need the stuff to
upload in mobile data only. No WiFi.

**Comment by tobiasKaminsky** [comment]
You are connected via a normal mobile data plan?
Nothing special? 

I see that you are connected via cloudFlare as a reverse proxy.
Is this needed, or is there a chance to test it without? If not, please test it with try.nextcloud.com

**Comment by Rudder2** [comment]
Yes, phone connected to mobile network. Yes, CloudFlare is required for my setup. My phone uploads all other file types fine over Mobile Data... Just will not upload photos or videos... Says waiting on unmetered WiFi.

**Comment by tobiasKaminsky** [comment]
I read somewhere that CloudFlare is limiting put http requests in their free plan…
Can you check this?

**Comment by Rudder2** [comment]
How could this be the problem if all other file types upload fine. Also, the APP States waiting for unmetered WiFi for photos and videos only in the DCMA folder... I've upload hundreds of gig of other file types with out a problem.

**Comment by tobiasKaminsky** [comment]
Oh, I overread this, sorry!
So auto upload of other file types than images/videos are working?
What about manual upload from this specific folder?

When doing auto-upload:
Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

**Comment by antoine-gu** [comment]
I have the same problem here. Still not solved

**Comment by GreenClaw2001** [comment]
I have the same Problem. Im using Android 13.

**Comment by nicolaspallin-creator** [comment]
Still not fixed. No problem when I turn WiFi on but impossible to get it going on mobile network.
