### ISSUE TITLE
Share in app does no longer work

### ISSUE THREAD

**Issue by fgtham** [nextcloud/android#7936]
### Steps to reproduce
1. Open app, tap on share icon next to file
2. Select "Share" in order to share the file with another NC user
3. 

### Expected behaviour
- The share dialog should open, allowing to select a user to share with.

### Actual behaviour
- The share dialog is not shown. Instead I am returned to the file browser.

Sharing worked fine until version 3.14.3. Sharing directories is still possible, it only affects files.

### Environment data
Android version:

Device model: 

Stock or customized system: LineageOS

Nextcloud app version: 3.15.0

Nextcloud server version: 20.0.7

**Comment by tobiasKaminsky** [comment]
Fix is in #7937
