### ISSUE TITLE
Sync Files to custom folders

### ISSUE THREAD

**Issue by shockergit** [nextcloud/android#7939]
It would have been great to sync Notes if You allow to sync my txt files between a custom local folder and cloud folder.
eg; phone/notes to
 cloud/notes

**Comment by radry** [comment]
To expand this issue as OP doesn't explain well.

**The app can't sync a custom local folder with a custom remote folder the same way the windows client can.**

Currently it's only possible to set up a "auto upload" folder but that does not download files from the remote folder but only uploads the local folder.
Furthermore "Synchronizing" a remote folder in the app is pretty much useless as it's not a real sync but only a "make available offline" feature. It will download the folder into the default Nextcloud data directory (which cannot be set to a custom folder but only allows 3 preset options), but not keep it syncronized afterwards.

**Comment by shockergit** [comment]
> To expand this issue as OP doesn't explain well.
> 
> **The app can't sync a custom local folder with a custom remote folder the same way the windows client can.**
> 
> Currently it's only possible to set up a "auto upload" folder but that does not download files from the remote folder but only uploads the local folder.
> Furthermore "Synchronizing" a remote folder in the app is pretty much useless as it's not a real sync but only a "make available offline" feature. It will download the folder into the default Nextcloud data directory (which cannot be set to a custom folder but only allows 3 preset options), but not keep it syncronized afterwards.

It is possible im using  Folder sync app now it works perfectly it syncs the files between cloud and local. Their are lot of other apps that works with nextcloud. Why doest the official client dont support this.

**Comment by shockergit** [comment]
https://play.google.com/store/apps/details?id=dk.tacit.android.foldersync.lite

**Comment by radry** [comment]
@shockergit thanks, I think the official app should support this too.

**Comment by shockergit** [comment]
No i checked it doesnt support

**Comment by tobiasKaminsky** [comment]
We have #285, which covers two way sync.
Auto upload is as the name suggests only for upload.

Unfortunately I cannot give you an estimation when the real 2 way sync will come.

**Comment by RoyalCyan** [comment]
@tobiasKaminsky I am sorry for resurrecting this old issue, but I don't understand why it was closed as completed? This feature is still not present in Nextcloud app for Android devices. I find it very important to being able to choose what folder to sync with the Nextcloud. Currently there is no such option.
