### ISSUE TITLE
Server connection lost

### ISSUE THREAD

**Issue by srimpau** [nextcloud/android#7943]
### Steps to reproduce
1. Use Android app >3.13.x
2. Try to connect from an IPV6 enabled WiFi or mobile provider
3. NC server is on version 20.x on a IPV4 and 6 enabled LAN, behind a router with port openings and DynDNS

### Expected behaviour
Android app should connect to server

### Actual behaviour
Android App loses connection, whereas all browser connections are working well.

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 10

Device model: Sharp Aquos R3

Stock or customized system: stock

Nextcloud app version: >=3.14

Nextcloud server version: 20.x

Reverse proxy: none

#### Web server error log
no web server log entries from Android app

#### Nextcloud log (data/nextcloud.log)
no connection attempts from the Android app logged

**Comment by mepreston** [comment]
i also had to downgrade to 3.13.1 to get a working client with my nextcloud 20.0.7 ipv4/ipv6 server.

**Comment by tobiasKaminsky** [comment]
Is your server really reachable via v6?
