### ISSUE TITLE
Support for Nextcloud internal links

### ISSUE THREAD

**Issue by godfuture** [nextcloud/android#795]
### Actual behaviour
The Nextcloud internal link (NCILs) are not accessable from my Nextcloud app share dialog. NCILs are opened with my default browser.

### Expected behaviour
NCILs shall be accessable in Nextcloud app share dialog. NCILs should be opened with my Android app.
 
### Steps to reproduce
1. Share a folder in web client (in Anroid app this link is not accessable at all)
2. Open this internal link on your phone
3. Expect the browser to open (instead of the Nextcloud Android app)

### Environment data
Android version: 6.0.1

Device model: BQ Aquaris x5 plus

Stock or customized system: Stock

Nextcloud app version: 1.4.1

Nextcloud server version: 11.0.2

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

**Comment by tobiasKaminsky** [comment]
Thank you for your idea!
For developing this we need an extension of the server part, so once this is available we can implement this.

**Comment by tobiasKaminsky** [comment]
Server side is now done.

**Comment by godfuture** [comment]
Is there any plan to bring the internal link to Android app? I would love to link files in messengers instead of sending them or handling hundred of (new) share links...

**Comment by tobiasKaminsky** [comment]
@nextcloud/designers do you have an idea how/where to put this?
In webUI this is explained via an overlay, but this is not possible on Android.

![2018-10-25-164105](https://user-images.githubusercontent.com/5836855/47508643-c7852d80-d874-11e8-8fc2-d53ca44f8c54.png)

**Comment by tobiasKaminsky** [comment]
Internal links are done.
