### ISSUE TITLE
Instant Upload photos not showing in media folder.

### ISSUE THREAD

**Issue by Exist2Resist** [nextcloud/android#7952]
EDIT: Wow this app is so f***ed up.  Do you guys test this at all or just push and hope for the best?
I have the app now constantly crashing and showing 3x the documents but still no images in the app while they exist on the web.
I now have to find the 3.14 apk and install that, this is not usable at all.

### Steps to reproduce
1. Install new android app
2. Open app and navigate to Media
3. Instant Upload photos are missing

### Expected behaviour
- I should see all my instant upload photos from my phone in the Android app Media section

### Actual behaviour
- I only see some random pictures which are not in the Instant Upload folder

### Can you reproduce this problem on https://try.nextcloud.com?
- Not applicable

### Environment data
Android version:
- Android 10 (Lineage OS v 17 latest)

Device model: 
- Pixel 3 XL

Stock or customized system: 
- Stock Lineage OS

Nextcloud app version: 
- 3.15.0

Nextcloud server version:
- 20.0.7 also tested on version 19.0.8

Reverse proxy: 
- Nginx
- didn't have issues prior to Adroid App update

#### Web server error log
```
https://1drv.ms/t/s!AmJFMS-_A33iqRjcVttxaZIQ8g6m?e=3eSicu
```

#### Nextcloud log (data/nextcloud.log)
```
https://1drv.ms/t/s!AmJFMS-_A33iqRfhPQxYEzVKdssA?e=3YSsu5
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
> EDIT: Wow this app is so f***ed up. Do you guys test this at all or just push and hope for the best?

May I friendly remind you on our code of conduct? https://nextcloud.com/contribute/code-of-conduct/



> * Open app and navigate to Media

This might take  some time, but it is a server side search and needs to be increased there.
The more files you have the longer the search takes…

> * Instant Upload photos are missing

What does this mean? Are the images not uploaded, or don't you see the folders to set up upload?

**Comment by Exist2Resist** [comment]
> May I friendly remind you on our code of conduct? https://nextcloud.com/contribute/code-of-conduct/
Sorry I'm very frustrated with this. I do use Nextcloud on a daily basis and first the app update and now a server update have broken some functionality of it. 

>This might take some time, but it is a server side search and needs to be increased there.
>The more files you have the longer the search takes…
Yes I am aware of this images from a different folder load, and the images also load on version 3.14 of the app, but not on version 3.15
Having said this I am in the process of clearing my preview generator and file cache. 

> What does this mean? Are the images not uploaded, or don't you see the folders to set up upload?
Upload works fine. I can not see the images that are uploaded to the server. I checked and they are there.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky like mentioned on a other issue I think this is related to the changed query we send to the server where other reports mentioned that the sorting is not newest to oldest file. Since I can't find the PR atm the moment (commenting via my phone...) I can't say for sure 8fnthe change came with 3.15.0 but I think so.

**Comment by Exist2Resist** [comment]
> @tobiasKaminsky like mentioned on a other issue I think this is related to the changed query we send to the server where other reports mentioned that the sorting is not newest to oldest file. Since I can't find the PR atm the moment (commenting via my phone...) I can't say for sure 8fnthe change came with 3.15.0 but I think so.

It must be becuase as soon as I downgraded to version 3.14.x I was able to view the photos again. In the app. 
For now I disabled auto updates on the app, however I would like to move to the latest at some point in the near future.

**Comment by saywebsolutions** [comment]
maybe it's a good idea to rollback the problematic updated server side query stuff and any updates on the photos/media tab of the app (if any) until more testing can be done, doesn't seem like these updates are ready for production

**Comment by Exist2Resist** [comment]
I've been doing extensive testing over the last few days and I can confirm 3.14 works as intended, 3,15 creates a mess in the media folder.

**Comment by tobiasKaminsky** [comment]
Ah, I was a bit on wrong track.
So this is purely about media view, which should show all images and videos on your cloud, sorted from newest to oldest.
And instant upload photos is just an example that those new images are missing.

What exactly is the outcome? Wrong order, missing images/videos, timeout/no result at all?

**Comment by Exist2Resist** [comment]
> Ah, I was a bit on wrong track.
> So this is purely about media view, which should show all images and videos on your cloud, sorted from newest to oldest.
> And instant upload photos is just an example that those new images are missing.
> 
> What exactly is the outcome? Wrong order, missing images/videos, timeout/no result at all?

They are all missing, nothing is showing from InstantUpload in photots/media.
It shows content from other folders just not that one.  
Having said this I found another bug with the app. 
I can not open documents for editing. I am using Onlyoffice Document server. Official docker. As soon as I downgraded to version 3.14.1 I can open documents again. 
Note that I keep upgrading and downgrading the app to test for functionality.

**Comment by tobiasKaminsky** [comment]
> Having said this I found another bug with the app.
> I can not open documents for editing. I am using Onlyoffice Document server. Official docker. As soon as I downgraded to version 3.14.1 I can open documents again.
> Note that I keep upgrading and downgrading the app to test for functionality.

Please open a new issue for this.

**Comment by tobiasKaminsky** [comment]
Let us track this in #7245
