### ISSUE TITLE
Sharing ("Senden/Teilen") of unsynchronised objects (images) leads to strange (erroneous) behavior

### ISSUE THREAD

**Issue by DTMW2** [nextcloud/android#7958]
### Steps to reproduce
1. click on an unsynchronised image via the app and choose the option to share it ("Senden/Teilen") 
2. choose the "target app" (e.g. threema)
3. now in many (most?) cases the image will either be incomplete or rotated by some degrees

### Expected behaviour
- An image which is stored on a remote nextcloud share but accessible via the app should be downloaded in the background an then handed over to the target app 1:1 unaltered
- I am convinced that it is not a good idea to "force" users to systematically synchronise images. Say one has thousands of images (e.g. 100 GB of data) stored in an own nextcloud server instance and every now and then wants to share one of those pictures via threema/signal/telegram/...

### Actual behaviour
- synchronised images which are already downloaded on the android device: unaltered, everything fine
- unsynchronised images which are noch already downloaded on the android device: in many (most?) cases the image will either be incomplete or rotated by some degrees

### Environment data
This bug persists since many versions both server-side and client-side (beginning at 2019 I think)

**Comment by tobiasKaminsky** [comment]
Can you post an example of an incomplete image?
Is this also shown wrong in internal viewer?

Regarding rotation: we rely on server, so I am not sure if this is a bug on server side, or the receiving app is handling it wrong. what if you send it to you via mail and look into it on Desktop? There you can see also if exif orientation is correct.
