### ISSUE TITLE
No U2F support

### ISSUE THREAD

**Issue by AquaL1te** [nextcloud/android#796]
### Actual behaviour
I enabled U2F (Yubikey Neo) on my Nextcloud for my user account. Now I can't use the app anymore, only with the Chrome browser.

### Expected behaviour
An option to scan my Yubikey Neo to gain access.
 
### Steps to reproduce
1. Enable U2F addon in Nextcloud
2. In the Personal account menu, enable the U2F option
3. Touch the Yubikey
4. Try to log in with the app

### Environment data
Android version: 7.1

Device model: OnePlus One

Stock or customized system: LineageOS 14.1-20170327

Nextcloud app version: 1.4.2

Nextcloud server version: 11.0.2

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
No entries.

**Comment by rullzer** [comment]
The new login flow catches this use case. If you have 2FA methods that you can't use on your phone from the app (for example your U2F key) use the "Login with apptoken" approach.
