### ISSUE TITLE
No Fingerprint Check on First Start after reboot

### ISSUE THREAD

**Issue by mstoeppler** [nextcloud/android#7972]
### Steps to reproduce
1. Reboot Android phone (mi 9t pro in my Case)
2. Start NC app
3. Access app without fingerprint check

### Expected behaviour
- Fingerprint Check should come up on EVERY start of the app

### Actual behaviour
- as mentioned above: App starts without any security check on first start after reboot

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 10

Device model: mi 9t pro

Stock or customized system: stock

Nextcloud app version: 3.15.0 and earlier

Nextcloud server version: current stable 20.x

Reverse proxy: no

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Fingerprint is using Androids built in security system.
If you boot up, you have to authenticate, and if you directly open up the app, there is a grace period, when you do not have to authenticate again.

To verify you can try:
- boot 
- wait 30s
- open app (should then prompt for authentication)

**Comment by mstoeppler** [comment]
No, I can't confirm that.

Restarted my phone yesterday and right now I opened the app for the
first time after reboot.

Unfortunately there was NO fingerprint check.

Opened the app again after a few minutes and everything was fine,
fingerprint was checked.

Please fix that.



Am 18.02.2021 um 09:45 schrieb Tobias Kaminsky:
