### ISSUE TITLE
Get rid of firebase messaging?

### ISSUE THREAD

**Issue by szaimen** [nextcloud/android#7975]
Hey,

I wonder if, now that [notify_push](https://github.com/nextcloud/notify_push#clients) is available, you could get rid of firebase messaging?

Greetings, szaimen

**Comment by tobiasKaminsky** [comment]
Unfortunately not, as Android will kill any long running web socket connection when the app is in background.
Thus we have to stay with FCM.

**Comment by szaimen** [comment]
@tobiasKaminsky But would this be an alternative to FCM on Custom ROMs without play services?

**Comment by tobiasKaminsky** [comment]
In theory a custom rom could built in some sort of long-running push system on their own. But then it should be not only bound to NC, but also e.g. possible for Signal, etc. to be used.
But then the question is who should maintain such a infrastructure?

It would also then only be limited to certain roms, only for experienced users, etc.
So I doubt that any self-made solution will gain the critical mass that is needed…

**Comment by SunnyDaze** [comment]
It looks like Android Nextcloud Talk will never be implementing private push notifications with something like UnifiedPush,org (https://apps.nextcloud.com/apps/uppush). That's too bad.  Google's Firebase spyware is not an option, and using Firebase may violate European privacy rules. I'll keep checking in to see if this much needed feature gets added.
