### ISSUE TITLE
App Crashed 

### ISSUE THREAD

**Issue by Tryweirder** [nextcloud/android#7986]
Attempting to upload a bug report taken on my custom build Android 10 [Q] (Samsung Galaxy A10e) to NextCloudDev @ nl.nd.tab.digital (Zurich).  I landed in the talk directory, attempting to go up one level, was challenged for my pin ( which should have already happened).  I entered the correct pin then the  app crashed.

-Tryweirder
aka. Timothy Bergstresser

**Comment by tobiasKaminsky** [comment]
I fail to understand when and what happens.
Can you reproduce it and please explain it step by step? :-)
