### ISSUE TITLE
Bigger ratios

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#799]
Read it as a hint on googles dev console, and I am unsure if we need it:
https://android-developers.googleblog.com/2017/03/update-your-app-to-take-advantage-of.html

> Note: if you don't set a value, and android:resizeableActivity is not true, then the maximum aspect ratio defaults to 1.86 (roughly 16:9) and your app will not take advantage of the extra screen space.

If we have time... ;-)

**Comment by AndyScherzinger** [comment]
handled via #943
