### ISSUE TITLE
Improve Usability of Create-New-Document Dialog

### ISSUE THREAD

**Issue by thgoebel** [nextcloud/android#7991]
### Is your feature request related to a problem? Please describe.
I'm always frustrated when [...]
... I'm creating new text documents, enter the title and then hit the button in the bottom right of the dialog to confirm.
Because that's where my thumb is trained to find the confirm/ok/yes button!

Furthermore, figuring out that you need to click on the template to actually create the file (and finish the dialog) is somewhat unintuitive.

### Describe the solution you'd like

1. Move the *Cancel* button (negative action) to the left, introduce a *Create* button (positive action) on the right.
2. Introduce a "selected" state for the possible templates. At most one can be selected at the time.

I'm not sure on the 2nd point, whether this is a good suggestion. I haven't seen any cases where there actually ever is a choice between 2 or more templates. Thus I'm not 100% sure what the current functionality/flow here is.

### Describe alternatives you've considered
Keep it like this? Dunno.

### Additional context
<img src=https://user-images.githubusercontent.com/33295590/108031739-a8a49980-7031-11eb-97c8-577ee7d7eb91.png height=300>

cc @nextcloud/designers

**Comment by AndyScherzinger** [comment]
Looping in @tobiasKaminsky and @juliushaertl for further feedback

I'd also say create should be a (borderless) button and not be triggered by clicking on template since filling out the file name is a second action besides choosing the template thus it is not a "typical"™️ chooser dialog. I'd also agree on the chosen-state visualization, in case there can be more than one template to choose from.

**Comment by tobiasKaminsky** [comment]
Totally true.



> I haven't seen any cases where there actually ever is a choice between 2 or more templates.

This will come with one of the next updates (of Text or OnlyOffice).

**Comment by juliushaertl** [comment]
For reference this is the unified template picker we have come up with 21 now 

![image](https://user-images.githubusercontent.com/3404133/108201078-a28ce680-711f-11eb-815e-5c01345879ad.png)

There we have a primary color border to indicate the current selection and always require an actual click on the Create button. I think that especially makes sense in the android app where the name input might not be filled out properly yet, so having an active confirm here on the creation would be the optimal way for me.

cc @jancborchardt

**Comment by tobiasKaminsky** [comment]
PR and screenshots are in: https://github.com/nextcloud/android/pull/8005

**Comment by AndyScherzinger** [comment]
![device-2021-02-17-142812](https://user-images.githubusercontent.com/1315170/108211774-6a8ca000-712d-11eb-9d8b-8dd0a67aaf97.png)

**Comment by AndyScherzinger** [comment]
Also note the button alignments, it is rather typical on android to have them right/end aligned and not split left/right (!)

**Comment by stefan-niedermann** [comment]
> it is rather typical on android to have them right/end aligned and not split left/right

It depends, android has for dialogs a neutral, positive and negative button. So it depends whether "cancel" is a negative or a neutral action in your eyes.

At the deck app we usually have "cancel" actions at the left/start, because it doesn't change anything about the state.

**Comment by AndyScherzinger** [comment]
@stefan-niedermann true, while https://material.io/components/dialogs/android#using-dialogs doesn't make this any easier since even their examples don't do this in a consistent way :( 

--> But I'd be totally fine with adapting the Deck-way so it is consistent between the Android apps and also matches the webUI.

**Comment by AndyScherzinger** [comment]
![device-2021-02-17-144941](https://user-images.githubusercontent.com/1315170/108213507-65c8eb80-712f-11eb-9aa7-228cda271ad0.png)

@stefan-niedermann @tobiasKaminsky moved to use the neutral button 👍
