### ISSUE TITLE
On folder share, the parrent folder is shared.

### ISSUE THREAD

**Issue by Grotax** [nextcloud/android#7998]
### Steps to reproduce
1. create folder Test
2. create nested folder Test2
3. share Test2 to some local user

### Expected behaviour
- Only Test2 is shared with the user

### Actual behaviour
- Test is shared with the nested Test2

### Can you reproduce this problem on https://try.nextcloud.com?
Yes I can, created two accounts and could reproduce it.

### Environment data
Android version: 10

Device model: Nokia 7.2

Stock or customized system: Stock

Nextcloud app version: 3.15.0

Nextcloud server version: 21.0.0-rc2, 19.0.8, 20.0.7. 

Reverse proxy: no

#### Web server error log
no data

#### Nextcloud log (data/nextcloud.log)
Nothing related

**Comment by tobiasKaminsky** [comment]
Fix is in #7992, can you test it?
