### ISSUE TITLE
XLS/DOC files do not open with OnlyOffice

### ISSUE THREAD

**Issue by belzebub40k** [nextcloud/android#8004]
### Steps to reproduce
1. Create .xls or .doc file
2. Try to open file with OnlyOffice in Android App
3. The App complains about that no matching App is found for the file format or opens it externally if one is found.

### Expected behaviour
OnlyOffice should open XLS and DOC files like it is in the webbrowser. The best would be if all files selected in the OnlyOffice settings within Nextcloud open with OnlyOffice.

### Actual behaviour
Only modern formats like OOXML open with OnlyOffice in the Android App.

### Can you reproduce this problem on https://try.nextcloud.com?
Can't try as try.nextcloud.com uses Collabora Online instead of OnlyOffice.

### Environment data
Android version: Android 11

Device model: Mi 9T Pro

Stock or customized system: LineageOS 18.1

Nextcloud app version: 3.15.0

Nextcloud server version: 20.0.7

Reverse proxy: yes (nginx)

**Comment by tobiasKaminsky** [comment]
Do you have OnlyOffice or Collabora installed on your server?

**Comment by belzebub40k** [comment]
@tobiasKaminsky Yes, OnlyOffice is installed on the server and working fine for OOXML file types in the Android App. In the Web App it is working for the old formats like doc and xls as well.

**Comment by tobiasKaminsky** [comment]
Can you or your admin check the settings for OnlyOffice in Nextcloud:
![image](https://user-images.githubusercontent.com/5836855/108478170-72b31f80-7294-11eb-8791-db289024601e.png)

**Comment by belzebub40k** [comment]
The types are selected and work properly in the Web App but not for the Android App.

![2021-02-19_09-34](https://user-images.githubusercontent.com/915117/108479152-aa6e9700-7295-11eb-983b-d786fafe4886.png)

**Comment by tobiasKaminsky** [comment]
@juliushaertl do you have an idea?

**Comment by juliushaertl** [comment]
I don't know the reasoning but onlyoffice is not exposing those mimetypes to the direct editing endpoint even when doc is checked:

```
curl --request GET \
  --url 'https://admin:admin@nextcloud.local.dev.bitgrid.net/ocs/v2.php/apps/files/api/v1/directEditing?format=json' \
  --header 'OCS-APIRequest: true'

...
"onlyoffice": {
          "id": "onlyoffice",
          "name": "ONLYOFFICE",
          "mimetypes": [
            "application\/vnd.openxmlformats-officedocument.wordprocessingml.document",
            "application\/vnd.openxmlformats-officedocument.presentationml.presentation",
            "application\/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
          ],
...

```

I'd suggest to check back with them on their issue tracker: https://github.com/ONLYOFFICE/onlyoffice-nextcloud/

**Comment by tobiasKaminsky** [comment]
Thanks for pointing out, Julius.
Then I close it here, as it seems to be a bug in OO.
