### ISSUE TITLE
After merged pull request you receive kind of spam

### ISSUE THREAD

**Issue by hannesa2** [nextcloud/android#8013]
After a merged pull request you receive a lot of spam mails, because it looks like, that nobody takes care of it

<img width="740" alt="image" src="https://user-images.githubusercontent.com/3314607/108474401-9d4ea980-728f-11eb-981a-567f52aea662.png">

Ok, it looks like it was merged with failing tests. Maybe with reason, but as long as nobody takes care, it's just spam and I would love to see one of the three solutions
* fix it
* remove it
* suppress it

This issue is just to point it out. After read you can close it

**Comment by tobiasKaminsky** [comment]
I configured GitHub to not send me any email, so I guess I just missed this.

It is our aim to have 100% reliable tests, but especially those screenshot test, that run on GitHub actions are very flaky.
Sometimes they fail, and once you restart them, the exact same job works.

https://github.com/settings/notifications
here you can at least limit emails:

![image](https://user-images.githubusercontent.com/5836855/108476616-852c5980-7292-11eb-9b98-f0acd3084642.png)

If you have time and knowledge, it would be great if you can have a short look why those tests are that unreliable.

**Comment by hannesa2** [comment]
Sorry, fixing flaky tests is a full time job

**Comment by newhinton** [comment]
I have to agree, it is not good to recieve like 30 Mails without getting the chance to even look at the issues a pr might have created. It's kinda bad that you have to change settings for that, the optimal way for this would be to recieve a single mail per full testrun, and not for each and every test.

Instead of multiple mails with apk's, codacy and whatever else runs, it would be good if only a single report listing everything would be good. (While writing this, i recieved 3 additional mails)

**Comment by AndyScherzinger** [comment]
@newhinton I feel your pain which is why (like Tobias) I simply turned of mail notifications because Github simply sends a single mail per executed Github action. Having ~10 actions in place means in case of a general error throughout 3 git pushes to the github remote I'd get 30 mails and all these workflow executions are managed bay Github itself.

So this means either no mails or no Github actions 😞

**Comment by hannesa2** [comment]
I don't agree to the conclusion "_no mails or no Github actions_" 
**This is the worst suggestion**

I already recommended 

> * fix it
> * remove it
> * suppress it

Maybe I'm wrong, but I only observe this multi-email thing only on split *.yaml 

eg, why not go with a matrix here ?

<img width="1125" alt="image" src="https://user-images.githubusercontent.com/3314607/108869808-da040300-75f7-11eb-970f-3e2bf4f69fd5.png">

I guess you can reduce *.yaml count by the half

**Comment by AndyScherzinger** [comment]
> Maybe I'm wrong, but I only observe this multi-email thing only on split *.yaml

True, yes

> eg, why not go with a matrix here ?

no reason, afaik @tobiasKaminsky wanted to change it in this way

> I guess you can reduce *.yaml count by the half

at least all screenshot test can be merged into a single action definition like you suggested and that'll probably something 30-50% yes.

**Comment by hannesa2** [comment]
Here you go https://github.com/nextcloud/android/pull/8034 ...let's see if it works with less mails.
At least it reduce boilerplate code

**Comment by hannesa2** [comment]
Btw, I would harmonize `detect` and `ktLint` too. Maybe more could be done as well

**Comment by hannesa2** [comment]
I guess it reduce the failing tests https://github.com/nextcloud/android/pull/8034#issuecomment-784487110

**Comment by tobiasKaminsky** [comment]
To be honest, I just did not thought about this.
When I switched from drone/added those actions, I already had everything via GitHub, so no emails, and thus I was just not aware that this happens.

Thanks for your great help, @hannesa2 and of course we are up to any suggestions that help you as a community to ease the pain :-)

**Comment by hannesa2** [comment]
I observed a lot of queued jobs and pull request run **very long**, that's why I asked Github support, what's wrong.

This is the answer:

```
It appears that the organization is hitting their concurrency limit:

https://docs.github.com/en/actions/reference/usage-limits-billing-and-administration

These jobs should continue once the job queue starts clearing up.

In the meantime, if the organization's owners have any questions regarding their plan, please ask them to reach out directly and we'll do our best to help.

Cheers,
GitHub Support
```

Hmm, I don't know exactly what to reduce, it's more your question. 
* One thing is to reduce failing test, to have a faster run ?
* Maybe less color screenshot tests/flavors
* Maybe instead of flavor `assembleXXXDebug` , simply a `assembleDebug` , I guess it's overall faster
* run tests only on code changes ? (Currently, I don't know how to do this) eg changelog ?
* Why run a pull request and a second same pull request from reviewer ? eg #8034 and #8035
* ... more ideas ?

If nobody has a pain, then it's no issue

**Comment by AndyScherzinger** [comment]
The reviewer PR is something I created to see if the CI is still working since some stuff relies on secrets.

I checked the Screenshot tests and the largest time consuming part is that actual upload (15h minutes for each combination...)

For some checks Tobias implemented a logic to filter out certain changes.

**Comment by hannesa2** [comment]
Maybe we should run development/work-in-progress/try-out/collect-info of something in personal forks where it's possible ?

**Comment by tobiasKaminsky** [comment]
> * One thing is to reduce failing test, to have a faster run ?
> 
> * Maybe less color screenshot tests/flavors

Those are our most problematic colors, and complexity increased with dark mode.
E.g. primary button with NC blue and white color looks good, but white primary color, on light mode might looks strange.
We could try to limit those screenshot tests to only those PRs, that actually changes code on xml or theming code.

> 
> * Maybe instead of flavor `assembleXXXDebug` , simply a `assembleDebug` , I guess it's overall faster

Right, for only checking if it builds, it should be enough to rely only on assembleGplay or use assembleDebug :+1: 

> 
> * run tests only on code changes ? (Currently, I don't know how to do this) eg changelog pull request ?
> 
> * Why run a pull request and a second same pull request from reviewer ? eg #8034 and #8035
> 
> * Maybe it's not only related to Android repo ?

**Comment by AndyScherzinger** [comment]
> We could try to limit those screenshot tests to only those PRs, that actually changes code on xml or theming code.

Can we do this via the `Design` label?
