### ISSUE TITLE
WebP support

### ISSUE THREAD

**Issue by L-as** [nextcloud/android#8017]
### Is your feature request related to a problem? Please describe.
Whenever I open a WebP image, it asks me "No resized image available. Download full image?" 2~3 times, but even if I say "yes" it doesn't actually show the image, it just downloads it without showing it. You can view it if you go back to the directory tree and click on it again, but it's quite a PITA.

### Describe the solution you'd like
Optimally WebP would have the same level of support as JPEG and such.

### Describe alternatives you've considered
I took a look around, and I can see that normally images are resized before being sent (which also explains why I see no thumbnails), but if supporting resizing is non-trivial, you could have it automatically ephemerally download the full image and show that. Perhaps this could be a setting in the app, since it could be useful for JPEG and such too, if you don't care about how much data you're using and just want the highest quality image.

A personal solution for me would be to convert all my images to JPEG, but I don't have the storage space for that...

**Comment by tobiasKaminsky** [comment]
@nextcloud/server-triage for the resized image feature we rely on server capability to show wepg images, is this somehow supported?

On my Android 10 I can see downloaded webp image as like any other image.
What Android version do you use?

**Comment by L-as** [comment]
I am on Android 6, though I **can** see the downloaded webp image, it's just buggy in the sense that clicking "yes" when it gives the pop-up doesn't actually show it even though it downloads it. I need to exit the viewer and try to view the image again for it to actually show it.

**Comment by tobiasKaminsky** [comment]
This also works for me.
The image previewer is loading next two upcoming images in background.
If one of those cannot be displayed, this "do you want to download" question is also shown.
So if it this the case and you click on yes, then you do not download the current image, but one of the next two.

You can check this, if you copy/move a webp image into a new folder, only containing this file.
If this then still fails, it is a new bug, otherwise it is the old one.

**Comment by L-as** [comment]
You seem to be correct.
I tried with a single webp in a folder, and it asked me if I wanted the full image, which after accepting caused it to download and show it correctly.

I tried my folder with a lot of pictures again, and it does seem that it shows me the pop-up once for each picture it wants to download, and I could view the next (not the current) picture after clicking "yes" to the popup, but after swiping a bit around it crashed...

Would it be hard to have a setting where you can make it "yes" by default for the pop-up, so that one can view many pictures smoothly without rapidly accepting the pop-ups?

Thanks

**Comment by tobiasKaminsky** [comment]
Thanks for confirmation.
So there are two issues:
Bug about wrong error handling: https://github.com/nextcloud/android/issues/8054
Enhancement: https://github.com/nextcloud/android/issues/8055

Therefore I close this now.

**Comment by L-as** [comment]
Thanks for the help.
