### ISSUE TITLE
Image in /storage/emulated/0 breaks auto upload

### ISSUE THREAD

**Issue by delbonis** [nextcloud/android#8019]
I'm not 100% sure what I think is happening is actually the source of the issue, but this is what my understanding of it is.  I ran into this situation because I used the VeoRide app to rent an electric scooter in my city (it's the kind it charges you like 5 cents per minute and you use it for like 20 minutes), and when you finish riding the scooter it has you take an image of where you left the scooter, but they don't clean up the temporary file it generated when you take the picture.

### Steps to reproduce
1. Put an image (for me it was named like `image.jpeg`) in `/storage/emulated/0`, not in any subdirectory.  You don't have to try to make the app sync that dir to cause the issue.
2. Try to use auto-upload with any other directories, like `/storage/emulated/0/Pictures`.

### Expected behaviour
- It should start automatically uploading files

### Actual behaviour
- It doesn't
- In the auto upload menu in the settings menu in the app it will show the picture in a nameless section
- It seems like it doesn't even try to connect with the server at all, which makes me think that the issue has to do with indexing

### Environment data
Android version: 10

Device model: Pixel XL (2016)

Stock or customized system: stock

Nextcloud app version: 3.15.0

Nextcloud server version: 19.0.7

Reverse proxy: nginx, whatever the current version from Debian is.

### Logs
There wasn't anything relevant on the server (since it seems like purely client issue).  I can probably try to recreate the problem and share logcat if that's needed.

**Comment by tobiasKaminsky** [comment]
Does AutoUpload work with a subdirectory?

**Comment by delbonis** [comment]
The UI doesn't show any issues and lets you configure auto-upload on all the subdirectories you'd expect it to (like Downloads, the actual camera pictures dir, etc.), but it never actually does anything.  When you delete the bugged picture in the root it goes back to behaving normally.

**Comment by tobiasKaminsky** [comment]
![image](https://user-images.githubusercontent.com/5836855/110089703-b62e8300-7d96-11eb-8470-6557580e29e3.png)


First is /storage/emulated/0
Second is /storage/14E8-2E10 (sdcard)

Still upload works fine.

**Comment by delbonis** [comment]
That's interesting, I can try to recreate the issue and get back to you with an actual logcat.

**Comment by jeffWelling** [comment]
@delbonis Can you share how many files are in the directory you're trying to auto upload? AutoUpload is failing for me as well and I'm wondering if it's related to the number of files in the directory. In another ticket it's mentioned that they might not run tests against directories with lots and lots of files already in there. (https://github.com/nextcloud/android/issues/8119)

**Comment by delbonis** [comment]
@jeffWelling There was on the order of 5000 files total between each sync group.  Split up there were fewer in each once I had deleted the image directly in /storage/emulated/0, so that might have had something to do with it.
