### ISSUE TITLE
OrderBy in Media

### ISSUE THREAD

**Issue by rscata** [nextcloud/android#8023]
### Describe the solution you'd like
In **Media menu** would be nice to be able to order content after the latest added.

**Comment by sureloc** [comment]
Yes, definitely! Also subcategories such as Photos and Videos would be good.

**Comment by tobiasKaminsky** [comment]
> In **Media menu** would be nice to be able to order content after the latest added.

This should already be the case: media should show all images / videos from newest first to oldest…

**Comment by sureloc** [comment]
For me (on my Nextcloudpi install) it shows a bunch of old album art pics first. I have a music collection with a couple thousand songs, and have put both a .nomedia and .noimage in my music folder, but that dpesn't seem to hide the images (a known bug apparently).

**Comment by sureloc** [comment]
There could be an option for selecting which folders are shown under the Media category?

**Comment by saywebsolutions** [comment]
The new "Media" section (formerly "Photos") in the android app has been broken for a few months now for a lot of people; seems to be ordered oldest to newest and people report being unable to load additional photos, among other issues

**Comment by joshtrichards** [comment]
No longer the case and, in any case, replaced by #10050
