### ISSUE TITLE
Bug when opening files after moving to SD

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#803]
via email: 
When using the latest android app once I set it up to store files to my SD,  when trying to open files (pdf, odt, docx...) The client says it cannot find any associated app. It works before selecting the SD.

**Comment by mr-manuel** [comment]
Have the same issue on build 20170317. With files on internal storage all works fine

**Comment by mario** [comment]
There's a fix available now.

**Comment by bekl101** [comment]
will there ba a beta/nighly apk when the fix is implemented?

**Comment by mr-manuel** [comment]
In the latest apk 20170417 it works :D

**Comment by mario** [comment]
Thanks!
