### ISSUE TITLE
AutoUpload misses many files

### ISSUE THREAD

**Issue by leo-b** [nextcloud/android#804]
I enabled AutoUpload for automatically uploading new camera images.
Settings are:
- Local Directory: ``/storage/0000-0000/DCIM/Camera``
- Remote Directory: ``/AutoUpload/Camera``
- Only on WIFI: yes
- Only when charging: no
- Use subfolders: yes
- Keep original files: in original folder

(Maybe the english option-names are a little bit different, I am using the german UI.)

When shooting several pictures, only some of them are transferred.
E.g. from the following files that were taken this morning, only the checked ones got synced:

- [ ] 20170405_072003.jpg
- [ ] 20170405_072008.jpg
- [ ] 20170405_072054.jpg
- [ ] 20170405_072147.jpg
- [x] **20170405_072154.jpg**
- [ ] 20170405_072349.jpg
- [ ] 20170405_072547.jpg
- [ ] 20170405_072549.jpg
- [ ] 20170405_072728.jpg
- [x] **20170405_072738.jpg**
- [x] **20170405_072941.jpg**
- [x] **20170405_072948.jpg**
- [ ] 20170405_073141.jpg
- [ ] 20170405_073143.jpg
- [ ] 20170405_073242.jpg
- [x] **20170405_073248.jpg**
- [x] **20170405_073338.jpg**
- [x] **20170405_073341.jpg**
- [ ] 20170405_073511.jpg
- [x] **20170405_073515.jpg**
- [x] **20170405_073520.jpg**
- [x] **20170405_073602.jpg**

The `Uploads` menu doesn't show any transmission attempt for the missing files.

Android version:
6.0.1

Device model: 
Samsung Galaxy S5

Stock or customized system:
Custom ROM (Phoenix ROM)

Nextcloud app version:
1.4.2

Nextcloud server version:
11.0.2

Unfortunately I couldn't find a log file. (The only file I found is already some months old and doesn't contain current information.)
```
# ls -l /storage/0000-0000/Android/data/com.nextcloud.client/files/nextcloud_log/log/currentLog.txt
-rwxrwx--x u0_a297  sdcard_rw      420 2016-12-09 16:56 currentLog.txt
```

**Comment by mario** [comment]
1) Are you doing them in burst? Really fast one after another?
2) Can you confirm this is SD card?

**Comment by leo-b** [comment]
>    Are you doing them in burst? Really fast one after another?

The filenames above are timestamps. So as you can see there are several seconds to minutes between the photos.

>   Can you confirm this is SD card?

Yes, storage location for the camera is set to the external SD card.

**Comment by mario** [comment]
Would you be open to doing live debugging?

You'd need android studio with all SDKs, tarball of client master, and Vysor working so I can see what's happening with the phone.

**Comment by leo-b** [comment]
> Would you be open to doing live debugging?
> You'd need android studio with all SDKs, tarball of client master, and Vysor working so I can see what's happening with the phone.

Sorry. I won't find the time to setup this environment in the near future. :-( However, if there are any simpler ways to provide additional information, I'd be happy to provide it.

**Comment by witteschnitte** [comment]
Hi,
I think i was to fast with my working comment.
The new Autoupload now puts all my Pictures in the Queue but don´t upload.
In the new autoupload Settings i set only to upload if the Smartphone is at the power suply.
If i connect it with my power suply, nothing happens.

Also i missed the Video upload function. my Videos will not recognized anymore.
Dear nextcloud Team. what have you done to a well working app Feature.
Regards.
Felix

**Comment by mario** [comment]
Dear @witteschnitte, aware of the issue and working on it :)

**Comment by witteschnitte** [comment]
Ok thank you Mario,

this is the first answer about a Long time. As I said With power suply it wont work and if i turn it to only WLAN with no power suply it only works some times but very often nothing happens. (over days)

**Comment by mario** [comment]
@witteschnitte can you please link me to an issue where you tell us which phone and operating system version?

**Comment by witteschnitte** [comment]
@Mario i wrote a Long time ago about the new upload Feature in the issue https://github.com/nextcloud/android/issues/462
Hey. I used android 6.0.1 on my galaxy s6. But it also tested it under android 4 and 5 with galaxy tab 3 and galaxy tab s2.
--------------------
Once i said it worked but this was to early. now i had the Problems i discribed above.

**Comment by koarlmichael** [comment]
The same Problems here at Android 6.0 Huawei P9 lite and Android 7.0 Moto G5. Only some images are transferred. Then the auto upload does not work. A manual upload of the images works.

**Comment by witteschnitte** [comment]
Ok now i have the same issue!

**Comment by xenithorb** [comment]
LineageOS 14.1 (7.1.1) is not working with Next cloud 1.4.1. I opened nextcloud verified the auto settings were correct, flipped over to the camera, and nothing happened. Could it be the  fdroid build, that's the one I'm using

**Comment by snicke** [comment]
Can confirm the same problem as OP: Only a part of the newly taken photos are uploaded automatically. Some days no photos at all are uploaded. Some days all. Some days o few of them.

Android version:
7.0

Device model:
Samsung Galaxy S7 Edge

Stock or customized system:
Stock

Nextcloud app version:
1.4.2

Nextcloud server version:
11.0.3

Upload settings:
Only on WIFI: yes
Only when charging: yes
Use subfolders: yes
Keep original files: in original folder

**Comment by DaveBurkhardt** [comment]
Same issue going on here with multiple devices.  Same versions slightly different settings.

**Comment by Spiritdude** [comment]
Same here: Android 5.1.1 with 1.4.3. InstantUpload misses files, don't know how rescan photos? There has be to a failsafe sync between camera folder(s) and the InstantUpload folder.

**Comment by mario** [comment]
Dear users,

thank you for your patience. After lots of work, we’re super excited to be able to give you a test version with new auto upload implementation. Keep in mind we will only accept bugs related to Auto Upload in this APK, as other things might be broken.

https://cloud.nextcloud.com/s/ftZraTruRQjTe0R

This is a dev APK so it will not overwrite your existing play store/f-droid APK unless you’re already running dev version. Also, you might need to remove your existing dev version before installing this one.

Explanation of the current functionality:
- added support for custom folders
- separated image and video folders
- checks for new files happens every 15-20 minutes
- automatic retry every 15-20 minutes or when you force close/open the app
- automatic pause once network is changed (untested!)
- significantly less battery usage

All and any testing is more than appreciated, especially with large and ever-going files like Videos. (like, try to record a 30 min video).

Let me know if you’ve got any questions.

Cheers,
Mario

**Comment by letitfly** [comment]
The upload speed is much faster now! What changed?

**Comment by mario** [comment]
@letitfly there was a small change, but it didn't pass the review yet so it won't be in 2.0.0. Maybe in 2.0.1. But glad you like it! :)

**Comment by Fmstrat** [comment]
@mario Is this still open? I'm experiencing this issue with latest Play Store Nextcloud on a Galaxy S9+. A series of photos taken across a day, only some uploaded, no videos uploaded, and no attempts in the uploads list.

**Comment by mario** [comment]
@Fmstrat I've heard of issues on S9 but don't have it so can't try.

@stlord how do you do that? Via auto upload? Are you sure? That would mean you're using custom folders?

**Comment by stlord** [comment]
https://github.com/mario Sorry, I've missed topic. Via direct upload. I have not necessarities to use autoupload, but can test it.

**Comment by mario** [comment]
Ha, this would be another issue @stlord. Could you please file it separately? :)

**Comment by Fmstrat** [comment]
@mario Anything I can do with the S9+ to help debug?

**Comment by mario** [comment]
@Fmstrat Come to hackweek and borrow me your phone for a few hours? :P

**Comment by Fmstrat** [comment]
@mario Hah, I wish. A trip overseas to fix Autoupload may be tough.

**Comment by mario** [comment]
What about installing Android Studio, git, fresh checkout of nextcloud android master, Vysor and TeamViewer? :)

**Comment by Fmstrat** [comment]
That might be feasible. Let me see if I can reliably reproduce the issue.

**Comment by stlord** [comment]
@mario what do you mean? If I try to upload these files separately, everything goes ok.

**Comment by mario** [comment]
@stlord I understand. But this issue is about Auto Upload. I was merely asking you to open a new issue stating your problem :) What version of the app do you have? I remember we used to trim the uploads list to 30 items (yet everything was handled actually)

**Comment by stlord** [comment]
@mario thanks. I'll try to reproduce that issue and then post it with detailed description.

**Comment by Fmstrat** [comment]
@mario OK, so it's totally reproducible. The problem is it's not consistent. The first time, I took 3 pictures in 9 seconds. Two uploaded even though I wasn't on Wifi or charging (as my settings dictate). The next time, none uploaded. Next time, one when charging. Next, none. Is there something specific you are looking for? Like an ADB log while it's happening when a DEBUG version is running? Might be easier than getting all the rest set up.

**Comment by mario** [comment]
@Fmstrat but do they all end up in the upload queue or not?

**Comment by Fmstrat** [comment]
@mario No, the only thing in the queue are the ones mentioned that upload. So the uploads succeed, they're just not detected. A force rescan does not add them, and SD-card vs Internal Storage does not impact things. Nextcloud is listed in the "don't manage power" in Settings/Device Maintenance/Battery, and I've tried rebooting.

**Comment by peterdey** [comment]
I'm having this issue too.  Example - took four videos yesterday:

1. VID_20190724_190210.mp4 (451.8 MB)
2. VID_20190724_190607.mp4 (349.3 MB)
3. VID_20190724_191015.mp4 (320.8 MB)
4. VID_20190724_101331.mp4 (615.7 MB)

Only one was auto-uploaded (2 above).
File 2 above shows in the "Uploads" screen as successful.  The other three don't show as Failed or Pending.

Auto upload settings:
> Preferences for auto uploading [on]
> For /storage/XXXX-XXXX/DCIM/Camera
> Remote folder: /PhoneBackup/Camera/
> Only on unmetered Wi-Fi [X]
> Only upload when charging [X]
> Use subfolders: [ ]
> Original file will be... [kept in original folder]

NextCloud Android app Version 3.7.0
Phone: Nokia 8 TA-1004
Android version: 9 / Patch level 1 June 2019
Andoid Build number: 00WW_5_150_SP02

**Comment by kab01m** [comment]
I have this problem with 3.10.0 on Sony Xperia IV 5 with Android 14. I wish to diagnose it. Is there any guideline to debug the application? I can use Android studio if its what needed.
