### ISSUE TITLE
Can't display image normally after removing local copy. Even stopping application doesn't help.

### ISSUE THREAD

**Issue by dariuszszyc** [nextcloud/android#8040]
First of all, I use NextCloud Android app with FileRun server. I have a folder with photos - all of them are on remote location, not on the phone. When I click a photo - I see a smaller  version of the image (probably lower resolution for quicker opening). That preview is replaced when I download photo from the server. Then I remove the local copy only of this picture and when I open it again (remote picture) - the preview is broken as it shows only some (sometimes random) part of the big-res picture. Not what I saw initially (full low-res picture). One way to workaround it is downloading the full picture again as then it is always opened correctly.

### Steps to reproduce
1. Open any photo from remote location via NextCloud android app.
2. Select menu > Download (Image will be reloaded with the downloaded image file)
3. Open the picture and go back to the list of images (still within NextCloud app)
4. From the list of images - open menu of the downloaded image > Remove/Delete > Only local copy
5. Open the picture again - it will be displayed always as zoomed in without possibility to zoom out to see entire image.

### Expected behaviour
- I should see again the lower-res full image.

### Actual behaviour
- I see only some part of the big-res picture, but zoomed-in. Cannot zoom out.

### Can you reproduce this problem on https://try.nextcloud.com?
Can't say - I'd need login & pass to test.

### Environment data
Android version:10

Device model: Huawet Mate 20 Pro(LYA-L29)

Stock or customized system:Stock (EMUI 10.1.0)

Nextcloud app version:3.15.0

Nextcloud server version: FileRun 2020.11.21

Reverse proxy:Traefik 2.4.2 (I doubt that matters)

**Comment by tobiasKaminsky** [comment]
Thanks for this detailed bug report :+1:

**Comment by joshtrichards** [comment]
Fixed in #11851
