### ISSUE TITLE
Sharing single file -> no window

### ISSUE THREAD

**Issue by hul51u** [nextcloud/android#8052]
### Steps to reproduce
1. Click on the sharing symbol of a single file that is not shared with or by another user.
2. Click on "Sharing" (german "Teilen").
3. No extra window appers. 

### Expected behaviour
- I expect the popup/window that opens when I click on the sharing symbol of an folder (for example)

### Actual behaviour
- window/popup does not open

### Environment data
Android version: 10

Device model: Fairphone 3

Stock or customized system: no

Nextcloud app version: 3.15.0

Nextcloud server version: 20.0.6.1

**Comment by tobiasKaminsky** [comment]
This should be fixed with 3.15.1 RC1, available in beta program on gplay.
Can you test this? Else the stable 3.1.1. will be released next week.
