### ISSUE TITLE
"Auto upload" twice

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/android#8057]
### Steps to reproduce
1. Select "Settings" from the menu.
2. Quickly tap twice on "Auto upload".

### Expected behaviour
- Only open one window for "Auto upload".

### Actual behaviour
- Open the "Auto upload" window twice.

### Environment data
Android version: 10

Nextcloud app version: 3.15.1 RC1 and dev 20210225

**Comment by tobiasKaminsky** [comment]
Can you provide us a video? 
I cannot reproduce it on different devices.
Also from code there should be only one activity started.

**Comment by Valdnet** [comment]
@tobiasKaminsky I sent you @ with a video of this problem 😉.

**Comment by tobiasKaminsky** [comment]
Thanks for the video, indeed very strange.

@AndyScherzinger do you have an idea what we can do here?
In theory this could happen everywhere, were we fire up a new activity on click.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky the only thing I can think of atm would be to lock the item to prevent a second firing of the event :/

**Comment by tobiasKaminsky** [comment]
That is not a feasible approach, I fear, as this can happen literally everywhere, e.g. "+" button or rename, …

**Comment by AndyScherzinger** [comment]
Yes, I don't think there is a truely feasable approach. So I'd say "way have to live with this behavior"

**Comment by tobiasKaminsky** [comment]
Ok. I also think this is the way to go, even if it is not a solution, nor perfect…

**Comment by Valdnet** [comment]
@tobiasKaminsky Has it been fixed? Because in dev 20210327 this is still happening.
