### ISSUE TITLE
Screenshot tests upload 40Mb on error

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#8062]
### Steps to reproduce
1. have a failing screenshot test, e.g. https://www.kaminsky.me/nc-dev/android-integrationTests/8060-Screenshot-white-Light-14-58/
2. see that this is 40mb

### Expected behaviour
- should only contain those failing images
- I created a ticket: https://github.com/Karumi/Shot/issues/195 and will take care of it next week

@AndyScherzinger @hannesa2 just fyi (and that I do not forget it)
This and #8060 will help us to have uploads of failing screenshot test in < ~30s per each test, which is reasonable fast.

**Comment by tobiasKaminsky** [comment]
PR is in https://github.com/Karumi/Shot/issues/195

**Comment by joshtrichards** [comment]
Fixed by https://github.com/pedrovgs/Shot/pull/196
