### ISSUE TITLE
Nextcloud 3.15.1 Rc1 copy button does not work

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/android#8071]
@AndyScherzinger 

I decided to participate in the beta program to have version 3.15.1 RC1 which solves the bug of the share button, but unfortunately when I go to click on the square icon to copy the link it does not produce any effect, nor does it come out copied url entry, it actually puts  in memory url.

![Screenshot_20210226-125722_Nextcloud](https://user-images.githubusercontent.com/35575744/109297742-c55f7f00-7832-11eb-8fb6-9f3d01e95fe9.jpg)

**Comment by tigernero79** [comment]
false alarm, restarted application everything worked

**Comment by AndyScherzinger** [comment]
> false alarm, restarted application everything worked

@tigernero79 could you maybe retest (without the restart) sinc eI'd guess it might only happen when you create a share and copy the link within the same "transaction"

**Comment by tigernero79** [comment]
@AndyScherzinger 

yes in fact I opened nextcloud 3.15.1 RC1 tried with another file I click on share (the 3 dots) then on the circle share and nothing happens the screen disappears, I restart and then I have a problem with the copy button.  this in the same transaction you are right

**Comment by tobiasKaminsky** [comment]
Sorry, I fail to understand if this is still an issue?

**Comment by tigernero79** [comment]
I close it because everything seems to be fine.
