### ISSUE TITLE
Android 10: Media file scanning fails from InstantUpload/Camera -folder

### ISSUE THREAD

**Issue by pokaalinkanssayohon** [nextcloud/android#8079]
### Steps to reproduce
1. Set Auto upload folder to InstantUpload/Camera (might be, that this was default)
2. Upload your photos/videos
3. Go to Nexctloud app menu and select Media

### Expected behaviour
- All photo and video files should be listed in your instance/account in Media view.

### Actual behaviour
- Some photos are listed, 72 actually but I have hundreds of pictures and videos

### Environment data
Android version: Android 10

Device model: Nokia 8 Sirocco (TA-1005)

Stock or customized system:

Nextcloud app version:3.15.0

Nextcloud server version: 20

**Comment by tobiasKaminsky** [comment]
Duplicate / discussed in #7245
