### ISSUE TITLE
Auto Upload "Original file will be deleted" setting not working with external sdcard

### ISSUE THREAD

**Issue by Netti93** [nextcloud/android#808]
### Actual behaviour
"Original file will be..." set to 
- "moved to app folder": file is **copied** to the app folder and if I delete the file in the original folder manually the picture won't show up in Gallery ( #769 & #807  )
- "deleted": the file is kept in the original folder

### Expected behaviour
"Original file will be..." set to 
- "moved to app folder": file is **moved** to app folder and visible in Gallery
- "deleted": file is deleted from device
 
### Steps to reproduce
- "Original file will be..." set to "moved to app folder":
1. Take a picture
2. Wait for upload
3. Find file stored in the original folder as well as in the app folder
4. Picture is shown in Gallery
5. Delete file from original folder
6. Picture isn't shown in Gallery any more

- "Original file will be..." set to "deleted":
1. Take a picture
2. Wait for upload
3. Find file still stored in the original folder

### Environment data
Android version: 7.0

Device model: Samsung Galaxy S7 & S7 Edge

Stock or customized system: Stock

Nextcloud app version: 1.4.2

Nextcloud server version: 11.0.2 (stable)

Nextcloud Folder: /storage/9C33-6BBD/Android/data/com.nextcloud.client/files (= SD-Card)

Auto Upload Settings:
![screenshot_20170406-175351 1](https://cloud.githubusercontent.com/assets/25515660/24764027/5f941730-1af3-11e7-9b83-770518df7318.jpg)

**Comment by Bertel3** [comment]
I have almost the same problem. I want to upload some pictures from my SD-Card and delete them from my phone.  They are uploaded without problem but they are not deleted. I don't use the auto upload and instead I upload them manually.  I also have Android 7 but on a Sony device. I use the latest official release of the app and the server (1.4.2 / 11.0.2). Could this be the same problem?

**Comment by tobiasKaminsky** [comment]
I have updated dev version. 
Do you have time to try it? It is either on fdroid (might be 1-2 days delay) or https://download.nextcloud.com/android/nightly/latest.apk

**Comment by Netti93** [comment]
It seems that the option "deleted" still isn't working, but "moved to app folder" is.
Also the moved files are shown in gallery now.

**Comment by tobiasKaminsky** [comment]
@Netti93 do you store the content on an external sdcard?

**Comment by Netti93** [comment]
@tobiasKaminsky  Yes, I do

**Comment by tobiasKaminsky** [comment]
@Netti93 @Bertel3 
can you both give us some more infos about your device? android and device version?

**Comment by Netti93** [comment]
@tobiasKaminsky You can find that information in my first post. Android Version 7.0 on a Samsung Galaxy S7 Edge (SM-G935F) and a Galaxy S7. Also I've updated Nextcloud Android App to Dev Version 20170504 and Nextcloud Server to 11.0.3. What else do you need to know?

**Comment by tobiasKaminsky** [comment]
@mario @AndyScherzinger 
As of Android 5 the access to external/removable storage has been changed.
https://developer.android.com/training/permissions/requesting.html

I checked if we have the write_external_storage permission on UploadFileOperation:449 and 
```
ContextCompat.checkSelfPermission(mContext, android.Manifest.permission.WRITE_EXTERNAL_STORAGE) == PackageManager.PERMISSION_GRANTED
``` was true.

So, currently I have no real idea, what the problem is.
(tested with samsung s5 neo and external storage)

**Comment by tobiasKaminsky** [comment]
I have added some debug code, can you please test the dev version of tomorrow:
- go to settings -> logs
- clear logs
- set auto upload to delete
- take a picture
- open logs and search for "Deletion of": this will only be shown if it fails, but with (hopefully) an exception message

**Comment by Netti93** [comment]
I tested this with the Dev version 20170623 but neither is the picture deleted or copied nor can I see any entry in the logs

**Comment by tobiasKaminsky** [comment]
Strange. As I only have a S5 with 6.0.1 I cannot replicate your exact settings.
For S5 it is working...
@Netti93 do you use the external sdcard as internal storage or portable storage?

**Comment by tobiasKaminsky** [comment]
No response within the last month, therefore closing.
Please feel free to reopen with additional infos, if the problem still exists.
