### ISSUE TITLE
Can't see any file

### ISSUE THREAD

**Issue by billypon** [nextcloud/android#8087]
### Steps to reproduce
1. Login with any account
2. Create a directory
3. Share the newly created directory to any LDAP user
4. Login with the LDAP user in app

### Expected behaviour
Should see the directory you just created

### Actual behaviour
If all my directories are shared, I can't see anything

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: MIUI 12.0.3

Device model: Xiaomi 9 SE

Stock or customized system:

Nextcloud app version: 3.15.0

Nextcloud server version: 21.0.0

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Can the ldap user see the share via another client or via web?

**Comment by billypon** [comment]
@tobiasKaminsky Can see via web, but webdav can't

**Comment by tobiasKaminsky** [comment]
> Webdav can't?

Then it is some sort of server problem, as Android/all clients are "only" smart webdav clients.

Can you re-open this on server repo?
