### ISSUE TITLE
Slow responses load times

### ISSUE THREAD

**Issue by tbunday** [nextcloud/android#8089]
### Steps to reproduce
1.  Open app
2.  Connects to cloudamo account
3. Waiting twirls for awhile until use. 
4. Click folder takes awhile to load
5. Click picture takes awhile to load

### Expected behaviour
- was hoping to be more responsive instead of having to wait 15 seconds on a response/load.  Server cloudamo issue maybe?

### Actual behaviour
- Takes 15 or more seconds to load folder, picture, document. 

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum
- 
Yes

### Environment data
Android version: 10

Device model: motog7

Stock or customized system: lineage 17.1

Nextcloud app version:3.14.1

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
Us.cloudamo.com
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

N/a

**Comment by tobiasKaminsky** [comment]
If it is working, it is more a server side configuration problem, which leads to slow response times.
I opened up the website and even showing the login side took 3s…
