### ISSUE TITLE
Inverted sharing inheritance

### ISSUE THREAD

**Issue by Grokenberger** [nextcloud/android#8090]
### Steps to reproduce
1. Have a nextcloud instance running with some users
2. Create a new folder, i.e. "parent"
3. Inside "parent" create a new folder, i.e. "child"
4. Inside "child" create a new folder, i.e. "grandchild"
4. Share "grandchild" with some user

### Expected behaviour
- "grandchild" should be shared

### Actual behaviour
- "child" is shared, "grandchild" also, inherited by "parent", "parent left untouched

### Can you reproduce this problem on https://try.nextcloud.com?
- Yes. 

### Environment data
Android version: 10, 11
Device model: lilac, beyond0lte
Stock or customized system: LineageOS 17.1, Stock
Nextcloud app version: 3.15.0
Nextcloud server version: 20.0.7, unknown on https://try.nextcloud.com

### Logs
The activity log says clearly "child" has been shared. Nothing suspicious on server logs, but I didn't investigated php logs to deeply.

### Further checks
Everything works perfect if using the "share link" function instead. I use the Android app since years, but the behaviour has appeared just a few days or weeks ago, maybe since the last update of the app. 

Also no troubles so far with the webapp. Further checked recently with IpadOS 12.0 and their nextcloud app version 3.3.0 and everything works smooth as expected.

### Conclusion
Now I'm quite sure to say: **This is a serious bug!**

**Comment by tobiasKaminsky** [comment]
Can you test this with 3.15.1 RC1 available via play store beta program?
If this still happens, please re-open.

**Comment by Grokenberger** [comment]
Cool. Fixed!
