### ISSUE TITLE
Shared link disappears after update

### ISSUE THREAD

**Issue by cagial** [nextcloud/android#8093]
### Steps to reproduce
1. Long press on any folder
2. three dot-menu and select Details
3. Select sharing
4. Share Link +
5. set expire date

### Expected behaviour
- Shared link should be updated and displayed

### Actual behaviour
- Shared link disappears as if there had never been one

### Environment data
Android version: 10

Device model: OnePlus Nord

Stock or customized system: Stock

Nextcloud app version: 3.15.0

Nextcloud server version: 20.0.8

Reverse proxy: no

No logs available

**Comment by tobiasKaminsky** [comment]
Can you test this with latest beta, available via play store / Fdroid.
If this still happens, please re-open.
