### ISSUE TITLE
Error Uploading files with character "\" in filename

### ISSUE THREAD

**Issue by hul51u** [nextcloud/android#8097]
### Steps to reproduce
1. Upload a file with an "\\" backspace in its name.
(My phone sometimes automatically adds an "\\" to a new photo's filename, I don't know why... Several photos that should be auto uploaded remain local)

### Expected behaviour
- The uploaded file name should replace all "\\" with "".
- Should not throw an "unknown error"

### Actual behaviour
- Upload fails: "unknown error" (German: "Unbekannter Fehler")

### Environment data
Android version: 10

Device model: Fairphone 3

Stock or customized system: no

Nextcloud app version: 3.15.1 RC1 (also older versions)

Nextcloud server version: 20.0.8 (also older versions)

ext4 file system on server

**Comment by tobiasKaminsky** [comment]
Can you post an example how it looks like?
I tried to rename an existing file to "IMG\123\123.png" but this does not work.

**Comment by hul51u** [comment]
![Screenshot_20210305-091331](https://user-images.githubusercontent.com/78090961/110086987-5c788980-7d93-11eb-85a3-0875fe1fec30.png)

**Comment by tobiasKaminsky** [comment]
@nextcloud/server-triage do we allow such names?

**Comment by AndyScherzinger** [comment]
Waiting for server team reply

**Comment by blizzz** [comment]
> @nextcloud/server-triage do we allow such names?

Nope, slashes and backslashes are not allowed, as they'd mess with filesystems. https://github.com/nextcloud/server/blob/stable21/lib/private/Files/Storage/Common.php#L556-L575
