### ISSUE TITLE
Not showing files

### ISSUE THREAD

**Issue by chagai95** [nextcloud/android#8098]
### Steps to reproduce
1. Record a video screen on xiaomi
2. See it in the folder and on Google photos
3. Can not see it on next cloud

### Expected behaviour
- should immediately show

### Actual behaviour
- sometimes shows after a while

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

This is the android app that has nothing to do with the server...

### Environment data
Android version:
MIUI 12

Device model: 
XIAOMI 8

Stock or customized system:
Stock MIUI

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Where do you not see it?
Have you seen that it is uploaded without problems?

**Comment by chagai95** [comment]
yes I have seen it work I guess it just takes time sometimes and sometimes does not show at all on google photos it's instantly there...

**Comment by chagai95** [comment]
Maybe google photos is blocking it from being shown?

**Comment by tobiasKaminsky** [comment]
No idea about google photos.
Great that you now see your images 👍
