### ISSUE TITLE
Grid view > back while folder is loading crashes app

### ISSUE THREAD

**Issue by Bugsbane** [nextcloud/android#81]
### Actual behaviour

If "Show grid view" and then the back arrow in the top left corner are clicked, while a folders contents are still loading, the nextcloud app crashes.
### Expected behaviour

The app should just go back to the previous folder without crashing.
### Steps to reproduce
1. Open a folder with many files (I used my instant upload folder, and tested with others)
2. While it's loading, click the three dot menu in the top right
3. Click "Grid view" (going the opposite direction and choosing "List view" won't crash the app)
4. Click the left/back arrow in the top, left corner of the app

Works every time.
### Environment data

Android version:
5.1.1

Device model: 
Samsung galaxy prime

Stock or customized system:
Stock for Samsung

Nextcloud app version:
1.1.0

Nextcloud server version:
ownCloud 9.0.2

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger please see #87

**Comment by AndyScherzinger** [comment]
Fixed by #87 - will be shipped with 1.1.0 RC2

**Comment by tobiasKaminsky** [comment]
We should keep this open as the fix is mainly a workaround not a real bug fix.
But it is now not time critically.

**Comment by AndyScherzinger** [comment]
Okay :+1:

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky should we then add a copy of the issue? So we can keep the issue but don't have an issue within a release we will most likely do before we have a proper fix instead of a workaround.

**Comment by tobiasKaminsky** [comment]
To simplify it I just would remove the milestone and keep this issue open.
It is mentioned in this issue that there is a workaround available.

**Comment by AndyScherzinger** [comment]
Fine with me :+1:

**Comment by tobiasKaminsky** [comment]
As we will sooner or later switch to RecyclerView with its on GridView I am closing this right now.
