### ISSUE TITLE
Preview Media Issue 

### ISSUE THREAD

**Issue by aleister09** [nextcloud/android#810]
### Actual behaviour
-When the user selects an MP3 File the Fragment will start to play the song but in the view shows "loading" all the time  and with that in mind the user can't stop the music and even if the app is closed the song will keep on playing until the end 

 
### Expected behaviour
-The fragment need to show the media controls 
-When the app is close the music will have to stop 
 
### Steps to reproduce
1. Open the app
2. Play a song
3. Wait until the music starts 
4. Press back until the app is closed 

### Environment data
Android version: 4.4.2 and 7.1.2

Device model: Moto X 1º Gen and Nexus 5X

Stock or customized system:

Nextcloud app version: master

Nextcloud server version: 11

The view shows "loading" all the time
![device-2017-04-06-181140](https://cloud.githubusercontent.com/assets/25756086/24779218/89cf66ac-1af4-11e7-9a59-773c7011f46a.png)

The App is closed and the music is playing 
![device-2017-04-06-183836](https://cloud.githubusercontent.com/assets/25756086/24779831/5facc492-1af8-11e7-97dd-c6bde8cf439b.png)

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

PR: #825

**Comment by aleister09** [comment]
@tobiasKaminsky I think the revert also deleted the code in the master and the issue is there again

**Comment by tobiasKaminsky** [comment]
Thank you for mentioning this :-)
I have created a new PR.
