### ISSUE TITLE
Download latest version doesn't work

### ISSUE THREAD

**Issue by bapjg** [nextcloud/android#8100]
### Steps to reproduce
1. I use the  development android client downloaded on 28th feb
2. Yesterday, a button appears saying download more recent version. 
3. When I click on the button, it send me to the site where my nextcloud server is (in house server). 

### Expected behaviour
- I would have expected to send me to a github download site, or anywhere other than my personal documents in house nc server

### Actual behaviour
- see above

### Can you reproduce this problem on https://try.nextcloud.com?
- happens every time
- if I use get latest version from the settings menu, I get the same erroneous result

### Environment data
Android version: 9

Device model: honor v10

Stock or customized system:

Nextcloud app version:

Nextcloud server version: 21

Reverse proxy:

#### Web server error log
Not relevant
Insert your webserver log here
```Not relevant


#### Nextcloud log (data/nextcloud.log)
```Not relevant

Insert your Nextcloud log here
```Not relevant

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
>     * if I use get latest version from the settings menu, I get the same erroneous result


Can you test this without being in your local wifi?

I have no idea what happen, but the url is hardcoded:
https://github.com/nextcloud/android/blob/0e66e8ea860cd646fd8c1688d6eb16b92e0122ea/src/main/res/values/setup.xml#L119-L120

**Comment by bapjg** [comment]
Tried it yesterday while I was in town.
In fact it seems to just open the Chrome explorer which displays the last (previous) page opened.
While I was at home, the fact that it showed up my internal server nc instance was a coincidence : it just happened to be the last use of chrome before pressing “the button”.


Cordialement

André Davis
andre@bapjg.com
Dom :             +33 4 7928 5014
GSM :             +33 6 8290 7233

De : Tobias Kaminsky <notifications@github.com>
Envoyé : vendredi 5 mars 2021 07:43
À : nextcloud/android <android@noreply.github.com>
Cc : Andre Davis <Andre.Davis@Bapjg.com>; Author <author@noreply.github.com>
Objet : Re: [nextcloud/android] Download latest version doesn't work (#8100)


* if I use get latest version from the settings menu, I get the same erroneous result

Can you test this without being in your local wifi?

I have no idea what happen, but the url is hardcoded:
https://github.com/nextcloud/android/blob/0e66e8ea860cd646fd8c1688d6eb16b92e0122ea/src/main/res/values/setup.xml#L119-L120

**Comment by tobiasKaminsky** [comment]
Maybe it directly starts download for you?
I use Firefox and there I see a new tab with the download url and then download starts.

**Comment by bapjg** [comment]
Thanks for spending time trying to resolve this issue.
It seems that my Android was a bit screwed up : I noticed yesterday other apps not performing as usual.
I have reset my phone to manufacturer config this morning and have installed NextCloud client. Everything seems to be working normally now.
I think this incident can be closed under "user error" or "faulty device".

Again thanks,

Cordialement

André Davis
andre@bapjg.com
Dom :             +33 4 7928 5014
GSM :             +33 6 8290 7233

De : Tobias Kaminsky <notifications@github.com>
Envoyé : lundi 8 mars 2021 08:08
À : nextcloud/android <android@noreply.github.com>
Cc : Andre Davis <Andre.Davis@Bapjg.com>; Author <author@noreply.github.com>
Objet : Re: [nextcloud/android] Download latest version doesn't work (#8100)


Maybe it directly starts download for you?
I use Firefox and there I see a new tab with the download url and then download starts.

**Comment by tobiasKaminsky** [comment]
Thanks for feedback, I'll close it then.
