### ISSUE TITLE
Mark external link item in drawer

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#811]
Bug in PR #806 
When an external link is opened, it should be marked grey in the drawer.

**Comment by MorrisJobke** [comment]
Maybe @aleister09 wants to look into this 😉

**Comment by aleister09** [comment]
The issue was Fixed
![device-2017-04-11-173543](https://cloud.githubusercontent.com/assets/25756086/24934012/ecf45a9c-1ede-11e7-8c62-73719e2f18f1.png)

**Comment by tobiasKaminsky** [comment]
@aleister09 great, thank you for your help!
