### ISSUE TITLE
Add Account not an option anymore?

### ISSUE THREAD

**Issue by diemelone** [nextcloud/android#8111]
### Is your feature request related to a problem? Please describe.
I have multiple Nextclouds for different purposes and want to use them on my smartphone

### Describe the solution you'd like
Add the "Add Account" feature again like in the manual or the current owncloud version
[https://docs.nextcloud.com/android/android_app.html](https://docs.nextcloud.com/android/android_app.html)

### Describe alternatives you've considered
Switching back to owncloud

### Additional context
look at the manual
[https://docs.nextcloud.com/android/android_app.html](https://docs.nextcloud.com/android/android_app.html)

If the feature is still there please tell me where to find it and update the helppage

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
This feature is still there:

Click on the avatar in the top bar (on the right) and choose "Add account"
