### ISSUE TITLE
Application is silently ignoring missing server

### ISSUE THREAD

**Issue by mikini** [nextcloud/android#8113]
### Steps to reproduce
1. Setup Nextcloud server on nextcloud.example.com
2. Add account to Android application
3. Move Nextcloud server to nextcloud.other.example.com

### Expected behaviour
- Android client detects missing Nextcloud instance on nextcloud.example.com and somehow indicates this to user
- only indication is an error message when accessing Trash/Deleted files

### Actual behaviour
- Application shows a loading spinner when navigating the cached folders but never detects or warns that the instance is not responding as expected

### Can you reproduce this problem on https://try.nextcloud.com?
N/A

### Environment data
Android version:
9

Device model:
Samsung Galaxy S8

Stock or customized system:
Stock

Nextcloud app version:
3.15.1 RC1

Nextcloud server version:
20.0.7

#### Web server error log
N/A

#### Nextcloud log (data/nextcloud.log)
N/A

### Screenshots

Spinner
![Screenshot_20210304-215945_Nextcloud](https://user-images.githubusercontent.com/1330166/110036843-89964f00-7d35-11eb-9ca3-cda1c61f91f1.jpg)

Trash
![Screenshot_20210304-043856_Nextcloud](https://user-images.githubusercontent.com/1330166/110036889-987d0180-7d35-11eb-9df0-07b27faee768.jpg)

**Comment by tobiasKaminsky** [comment]
It should show "server is unreachable" on top of folder listing.
Can you try to kill/stop app and start app, to see if it then is shown?

**Comment by mikini** [comment]
I wish it was as simple. Tried that of course. Just retried again force killing it from "Apps" setting. Same result.

Maybe complicating matters is; I stopped updating the dynamic DNS service so the domain now resolves to some random IP where traffic to 443 is not routed and experiencing timeout;

```
$ nc -zv nextcloud.example.com 443
Ncat: Version 7.80 ( https://nmap.org/ncat )
Ncat: TIMEOUT.
$
```

I could try updating it once more to see what will then happen.

**Comment by mikini** [comment]
No difference;

Server is now answering on ip:port (but not to virtual host nextcloud.example.com):
```
$ nc -zv nextcloud.example.com 443
Ncat: Version 7.80 ( https://nmap.org/ncat )
Ncat: Connected to ip.ip.ip.ip
Ncat: 0 bytes sent, 0 bytes received in 0.20 seconds.
$
```

Same reaction from application:

![Screenshot_20210305-082740_Nextcloud](https://user-images.githubusercontent.com/1330166/110081968-9ee69a00-7d84-11eb-9615-f6b0840494b2.jpg)

**Comment by tobiasKaminsky** [comment]
NC app is expecting that url either resolves to a valid NC server (as this was checked during setup) or it does not resolve at all, e.g. no internet, server down, etc.
But having "suddenly" a total different server behind the same url is not handled by the app.
In a valid setup this also should never happen.

**Comment by mikini** [comment]
I agree, in this scenario it is not a valid server anymore. But change and invalidity is one of the only constants of the universe and how fringe situations like this is handled is very much an indication of a piece of software`s maturity.

With users deploying NC on consumer internet connections having dynamic IP allocations I would expect the chance of a similar situation happening is relatively high.

If you are having troubles detecting the presence of NC and the API on a specific host maybe a solution would be to expose some metadata about it in a [RFC 8615 .well-known location](https://tools.ietf.org/html/rfc8615), see also [wikipedia article](https://en.m.wikipedia.org/wiki/List_of_/.well-known/_services_offered_by_webservers).
