### ISSUE TITLE
Android share dialog for shared files

### ISSUE THREAD

**Issue by OdinsAuge** [nextcloud/android#8116]
### Is your feature request related to a problem?

I'm not sure if this is just a missing feature or if there are limitations on android, but I'm missing sharing/sending files via Androids share dialog.

On any of my files I see the share icon. The Icon oens the NC share options and additionally the Android share dialog, where I can select different apps (social media, messenger, etc.).
On files that other users shared with me, I see the user circle. This opens the NC share options but not the Android share dialog.

### Describe the solution you'd like
It would be great to get the Android share dialog also shared files so I can e.g. send them via messenger or post them on social media.

**Comment by tobiasKaminsky** [comment]
Which version do you run?
I think we enhanced this with 3.15.0

**Comment by OdinsAuge** [comment]
This is exactly the version I use.
I can reshare it with other users and I can share the link, but there is no Android share dialog.
The app blocks screenshots, but I can take a picture of the whole phone if this helps.

**Comment by tobiasKaminsky** [comment]
Tomorrow there will be 3.15.1.
If this does not help, then please take a screenshot.
(If you disable app protection, you can also take screenshots)

**Comment by OdinsAuge** [comment]
Works now, thanks!
