### ISSUE TITLE
Nextcloud app is crashing or not responding while uploading files in the background.

### ISSUE THREAD

**Issue by florinandrus** [nextcloud/android#8119]
### Steps to reproduce
1. Install Nextcloud app
2. Mark for Auto Upload photos (~60GB) 
3. Close/Open the app (it has become absolutely unusable)

### Expected behaviour
- App running wile the uploading photos

### Actual behaviour
- Not responding (stuck) or even crashes

### Can you reproduce this problem on https://try.nextcloud.com?
- Not applicable

### Environment data
Android version: 10.0.0.185

Device model: Huawei P20 Pro

Stock or customized system:

Nextcloud app version: 3.15.0

Nextcloud server version: 20.0.5

Reverse proxy:

#### Nextcloud log (data/nextcloud.log)
[log3.log](https://github.com/nextcloud/android/files/6095641/log3.log)
[log4.log](https://github.com/nextcloud/android/files/6095642/log4.log)
[log2.log](https://github.com/nextcloud/android/files/6095643/log2.log)

**Comment by tobiasKaminsky** [comment]
Can you see how many items to upload are queued?
I fear that the upload mechanism was not tested with 60Gb…

**Comment by jeffWelling** [comment]
Could I ask that such a test be included?

With Google's change to google photos I don't think it's unreasonable to presume that people with large camera rolls are looking for alternatives and at least so far in my experience, the autoupload feature falls flat for large directories and I'm unsure what information to include to help resolve this as there is no visible output from the webserver about the client trying to upload at all.

**Comment by florinandrus** [comment]
> 
> 
> Can you see how many items to upload are queued?
> I fear that the upload mechanism was not tested with 60Gb…

How can I check this? DCMI folder contains around 15500 items (pictures and videos).

**Comment by tobiasKaminsky** [comment]
> Can you see how many items to upload are queued?

Just open the app and go to upload queue, if this is possible, depending on when the app does not respond.

**Comment by jeffWelling** [comment]
@florinandrus Any chance you have a moment to review https://github.com/nextcloud/android/issues/8154 and see if it lends any context to what you're seeing?

Specifically, I suspect there is a delay between when you ask NextCloud to autoupload a large directory, and when those items begin to appear in the Upload section. In my testing autoupload has worked after a day or two for my phone which also had ~60GB to process.

**Comment by SGCMarkus** [comment]
Having the same issue, sync takes ages (its been over 12H now, and it synced 2.3GB over (W)LAN).
Talking about around 10k files to be synced, multiple directories though. In total around 20GB.
Cant open the app anymore either to check the upload queue, or (temporarily) disable the sync for other folders. Just hangs on the splash screen there, till Android says the app doesnt respond anymore (killing, and trying to instantly start it again also doesnt help to atleast get into the app).

Now im stuck with a constant popup of "Nextcloud is not responding" Dialog, which, after the phone locked itself, seems to have blocked the overall UI thread, and the phone doesnt respond at all anymore (and after plugging in USB it just soft rebooted, meaning bootanimation came up again)
