### ISSUE TITLE
Sharing a folder, parent folder is shared

### ISSUE THREAD

**Issue by DavidMndz** [nextcloud/android#8120]
### Steps to reproduce
1. Create a folder called A
2. Inside folder A, create a folder called B ([nextcloud]/A/B)
3. Share using the Android App the folder B with some user(s).

### Expected behaviour
The folder B should be shared and visible to the users, but folder A (parent folder) should not be shared.

### Actual behaviour
In Android version 3.15.0 from Google Play, when folder B is shared with some users, automatically folder A is shared as well. Sometimes we only need or want to share one folder but not its parent directory. This happens at least when sharing as an admin user in Nextcloud.

### Can you reproduce this problem on https://try.nextcloud.com?
I can not create multiple user accounts there to test this issue, sorry.

### Environment data
Android version: 11 (UI 3.0)

Device model: Samsung Note 10+

Stock or customized system: Stock, last Samsung patches applied.

Nextcloud app version: 3.15.0

Nextcloud server version: 20.0.8

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
No errors found in the log related to this.

**Comment by clunst** [comment]
Can confirm this. Same for me with App Version 3.15.0

**Comment by clunst** [comment]
And it is fixed in 3.15.1RC1

**Comment by tobiasKaminsky** [comment]
3.15.1 final will be this week.
