### ISSUE TITLE
nextcloud dev opening error

### ISSUE THREAD

**Issue by devmalick** [nextcloud/android#8123]
### Steps to reproduce
1. ************ CAUSE OF ERROR ************

java.lang.UnsupportedOperationException: Not used anymore
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:99)
	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:139)
	at com.owncloud.android.ui.activity.DrawerActivity.lambda$getAndDisplayUserQuota$4$DrawerActivity(DrawerActivity.java:734)
	at com.owncloud.android.ui.activity.-$$Lambda$DrawerActivity$drdUCYgYHawhhF_lMrqiK8ir7OE.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:919)

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20210307
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: beryllium
Model: POCO F1
Id: QKQ1.190828.002
Product: beryllium

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: V12.0.3.0.QEJMIXM

2. 
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
This is fixed via https://github.com/nextcloud/android/pull/8106 and will be available in tomorrows dev version.
I merged a library change too early and thus app was not ready…

If it still happens on dev version 20210309, then please re-open.
