### ISSUE TITLE
Stuck in "Nextcloud dev crashed" activity

### ISSUE THREAD

**Issue by winny-** [nextcloud/android#8127]
### Steps to reproduce
1. Crash nextcloud client on android
2. Reopen nextcloud
3. Hit report and try to report the issue / hit share button -- I really don't know what exactly I did other than I think I pressed everything I could trying to figure out how to share the crash properly.
4. Then try to dismiss the "Nextcloud dev crashed" activity.  Note the "Loading..." overlaid text in the screenshot (see bottom of this issue)

### Expected behaviour
- Maybe back button dismisses the activity, or there is a dismiss button.  I can't remember how I got out of this activity before, but it seemed self evident and can't remember how.

### Actual behaviour
- Stuck in the activity

### Environment data

(Not exactly sure where to get all the data from, so this is data from the stack trace in the activity.)

```
************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20210304
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: motorola
Device: channel
Model: moto g(7) play
Id: QPYS30.85-18-9
Product: channel

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 767ff
```

![signal-2021-03-07-145416](https://user-images.githubusercontent.com/3893828/110254514-1c610480-7f55-11eb-8050-531b731da05d.png)

**Comment by tobiasKaminsky** [comment]
This is fixed via https://github.com/nextcloud/android/pull/8106 and will be available in tomorrows dev version.
I merged a library change too early and thus app was not ready…

If it still happens on dev version 20210309, then please re-open.
