### ISSUE TITLE
No connection with WiFi 

### ISSUE THREAD

**Issue by thomas2345** [nextcloud/android#813]
### Actual behaviour
- it is only one connection possible with mobile radio button not with WIFI

### Expected behaviour
-Tell us what should happen
 
### Steps to reproduce
1. 
2. 
3. 

### Environment data
Android version:1.4.2

Device model: Sony Xperia z5 compact 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by JSoko** [comment]
Do You use IPv6? Use IPv4
Have a look in your database regarding the brutforce-table and your wifi-IP; delete those entries...

**Comment by tobiasKaminsky** [comment]
@thomas2345 can you answer the questions above to help you?

**Comment by tobiasKaminsky** [comment]
No response within the last month, therefore closing.
Please feel free to reopen with additional infos, if the problem still exists.
