### ISSUE TITLE
Cannot create or open notes text file with Android app

### ISSUE THREAD

**Issue by pokaalinkanssayohon** [nextcloud/android#8135]
### Steps to reproduce
1. Open Notes folder.
2. Tap + and select ”Create new text document”.
3. Select empty template and give name for document, e.g. Test.md

### Expected behaviour
- Empty Test.md document should be created and opened.

### Actual behaviour
- App hangs on document creation. When you tap Back button after several minutes waiting, 0B size file is listed but cannot be opened.

### Environment data
Android version: Android 10

Device model: Nokia 8 Sirocco (TA-1005)

Stock or customized system:

Nextcloud app version: 3.15.0

Nextcloud server version: 20

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
App is requesting templates/info from server to create such a note. 
Maybe there it hangs. 
Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

**Comment by pokaalinkanssayohon** [comment]
[logcatOutput_N8Sirocco.txt.zip](https://github.com/nextcloud/android/files/6108306/logcatOutput_N8Sirocco.txt.zip)
Thanks @tobiasKaminsky for your quick response! I tested with iOS 14.4 and iPadOS 14.4 Nextcloud apps the same scenario as well and they were working ok. I will attach Android logcat file, maybe something will be found.

**Comment by pokaalinkanssayohon** [comment]
> Hm. I cannot find anything in the log, which helps.
> Can you open existing files?

I created note file via browser and Android app cannot open it.

**Comment by tobiasKaminsky** [comment]
If there is nothing on Android side, do you see something in nextcloud.log on server?

**Comment by pokaalinkanssayohon** [comment]
I have this nextcloud.log file in primary USB drive (nextcloudpi) but I cannot see any new lines when I was tailing it and tried to create new memo file with my Android phone. Interesting...

**Comment by tobiasKaminsky** [comment]
@juliushaertl do you have an idea?

**Comment by juliushaertl** [comment]
You could try to generate a direct editing link through a manual HTTP request like this for a new/existing file and see if the link properly opens the text editor in an anonymous browser session:

```
# open an existing file
curl --request POST \
  --url 'https://admin:password@nextcloud.local/ocs/v2.php/apps/files/api/v1/directEditing/open?editorId=text&creatorId=text&format=json' \
  --header 'OCS-APIRequest: true' \
  --data path=/MyExistingFile.md

# creating a new file
curl --request POST \
  --url 'https://admin:password@nextcloud.local/ocs/v2.php/apps/files/api/v1/directEditing/create?editorId=text&creatorId=textdocument&format=json' \
  --header 'Content-Type: multipart/form-data' \
  --header 'OCS-APIRequest: true' \
  --form path=/test1.md
```

**Comment by pokaalinkanssayohon** [comment]
Thanks juliushaertl and tobiasKaminsky! I tried to create new file with curl. Interesting, that curl resolving url address nextcloud.local fails, although I can use it via browser (i hide my user and password). 

$ curl --request POST --url 'https://<myadmin>:<mypassword>@nextcloud.local/ocs/v2.php/apps/files/api/v1/directEditing/create?editorId=text&creatorId=textdocument&format=json' --header 'OCS-APIRequest: true' --form path=/test1.md
curl: (6) Could not resolve host: nextcloud.local
