### ISSUE TITLE
High data consumption on mobile data

### ISSUE THREAD

**Issue by Pixdigit** [nextcloud/android#8146]
### Is your feature request related to a problem? Please describe.
Apps the access or create files in the Nextcloud folder cause automatic uploads.
I have Seedvault configured to back up to Nextcloud and it causes massive data consumption when I am on mobile data.

### Describe the solution you'd like
Allow for option to disable networking completely when not connected to WiFi

**Comment by tobiasKaminsky** [comment]
> I have Seedvault configured to back up to Nextcloud and it causes massive data consumption when I am on mobile data.

If this is about Seedvault, please ask them to have a switch to only allow it via Wifi.
Our app "only" provides the storage access framework, and this can be used by any app, so we cannot limit this to wifi only.

**Comment by Pixdigit** [comment]
No. Seedvault ist just an example. As Nextcloud is just a storage provider, apps can not determine, weather mobile data will be used or not.

**Comment by tobiasKaminsky** [comment]
True, and therefore this needs to be handled on app side.
I am sure that e.g. Seedvault will heavily crash if NC suddenly refuses to upload files due to changed wifi settings.

**Comment by Pixdigit** [comment]
I don't know how NC handles synchronization, but wouldn't it be possible to store them on the SD card and upload them later, when a WiFi connection is established?

**Comment by tobiasKaminsky** [comment]
That is not possible as the other apps would expect to have up to date date, and not something cached.

**Comment by Pixdigit** [comment]
What about if I do not have an Internet connection at all. Apps would have to deal with that anyway, so couldn't the NC app pretend to not have Internet access?
