### ISSUE TITLE
Autoupload not working

### ISSUE THREAD

**Issue by socr2121** [nextcloud/android#815]
### Actual behaviour
-Tell us what happens
The files act as if they are being transferred and even show a file size but are unviewable once on the server. Occurs when you select the option to delete after move.
### Expected behaviour
-Tell us what should happen
 The files transfer are deleted are available and viewable from the server.
### Steps to reproduce
1. Open the auto upload
2. Select to delete the original file after it has been uploaded
3. 

### Environment data
Android version:
Multiple versions
Device model: 
Multiple models
Stock or customized system:
Stock image
Nextcloud app version:
Official version and nightly
Nextcloud server version:
11.0.2
#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by socr2121** [comment]
Another interesting thing is that I can view the files on different devices such as Windows or Android after I upload as long as I don't choose to delete but it is NOT viewable on the Linux server that hosts the files

**Comment by tobiasKaminsky** [comment]
Which app version do you use?
Which android and device?
Do you store the nc app or the dcim on external storage card?

**Comment by mario** [comment]
Dear users,

thank you for your patience. After lots of work, we’re super excited to be able to give you a test version with new auto upload implementation. Keep in mind we will only accept bugs related to Auto Upload in this APK, as other things might be broken.

https://cloud.nextcloud.com/s/ftZraTruRQjTe0R

This is a dev APK so it will not overwrite your existing play store/f-droid APK unless you’re already running dev version. Also, you might need to remove your existing dev version before installing this one.

Explanation of the current functionality:
- added support for custom folders
- separated image and video folders
- checks for new files happens every 15-20 minutes
- automatic retry every 15-20 minutes or when you force close/open the app
- automatic pause once network is changed (untested!)
- significantly less battery usage

All and any testing is more than appreciated, especially with large and ever-going files like Videos. (like, try to record a 30 min video).

Let me know if you’ve got any questions.

Cheers,
Mario

**Comment by tobiasKaminsky** [comment]
No response within the last month, therefore closing.
Please feel free to reopen with additional infos, if the problem still exists.
