### ISSUE TITLE
InstantUpload: some files hang at "waiting"

### ISSUE THREAD

**Issue by woozalia** [nextcloud/android#816]
### Actual behaviour
-Tell us what happens

Some files show perpetually as "waiting to upload". No apparent way to get them moving.

### Expected behaviour
-Tell us what should happen

Top file should resume uploading when there are no other uploads in process.
 
### Steps to reproduce

Can't reproduce on command; happens sporadically. I currently have 3 photos and a video stuck in that state. (I think I already manually offloadef the vidro, which suggests another issue: files should be removed from queue when no longer present.)

### Environment data
Android version:
7.0
Device model: 
Moto G4
Stock or customized system:
Stock, from Republic Wireless
Nextcloud app version:
1.4.2
Nextcloud server version:
OwnCloud 9.1 (might be partly an owncloud issue, but client still should not behave like this)
#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by asychev** [comment]
Same for me, Huawei P9 Lite, android 7.0.

**Comment by mario** [comment]
Once the uploads "starts", if the file doesn't exist it will expire - so that's not an issue.

There is indeed an issue with some Huawei and Motorola phones but I cannot diagnose since nobody wants to install the test environment and let me connect to it :-/

**Comment by mario** [comment]
Will be fixed in 1.5.

**Comment by depassp** [comment]
This is affecting me too.

Nextcloud 1.4.3 running on Motorola Nexus 6 running Android 7.1.1 (Build N6F26Y)

**Comment by jdamgov** [comment]
same issue with LG G6 android 7.0 (H87110c) and Nextcloud 1.4.3

**Comment by mario** [comment]
Dear users,

thank you for your patience. After lots of work, we’re super excited to be able to give you a test version with new auto upload implementation. Keep in mind we will only accept bugs related to Auto Upload in this APK, as other things might be broken.

https://cloud.nextcloud.com/s/ftZraTruRQjTe0R

This is a dev APK so it will not overwrite your existing play store/f-droid APK unless you’re already running dev version. Also, you might need to remove your existing dev version before installing this one.

Explanation of the current functionality:
- added support for custom folders
- separated image and video folders
- checks for new files happens every 15-20 minutes
- automatic retry every 15-20 minutes or when you force close/open the app
- automatic pause once network is changed (untested!)
- significantly less battery usage

All and any testing is more than appreciated, especially with large and ever-going files like Videos. (like, try to record a 30 min video).

Let me know if you’ve got any questions.

Cheers,
Mario

**Comment by tobiasKaminsky** [comment]
Meanwhile we enhanced the app. Can you please try and report back if the bug still exists on latest official version or even try our [dev version](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#dev-release)?

**Comment by tobiasKaminsky** [comment]
No response within the last month, therefore closing.
Please feel free to reopen with additional infos, if the problem still exists.
