### ISSUE TITLE
AutoUpload partially broken

### ISSUE THREAD

**Issue by jeffWelling** [nextcloud/android#8162]
### Steps to reproduce
1. Start with an Android phone, and take about 60GB worth of pictures in the camera roll
2. Also have a directory with a handful of photos in it.
3. Tell NextCloud app to auto upload the small directory, observe it working
4. Tell NextCloud app to autp upload the large directory, observe nothing happening

### Expected behaviour
- NextCloud should upload all of the directories it was told to auto upload

### Actual behaviour
- NextCloud stops all auto uploads, including on other directories containing a handful of files, even after disabling auto upload on the large directory

### Can you reproduce this problem on https://try.nextcloud.com?
Using the hosted version isn't an option for me, I need this to work in the self hosted version. 

### Environment data
Android version: 10

Device model: SM-G965W

Stock or customized system: .... What? What are you asking for here, you're gunna have to offer more context to help me out here. It's an unrooted android phone. 

Nextcloud app version: 3.15.1

Nextcloud server version: 21.0.0

Reverse proxy: No

#### Web server error log
I can find no relevant logs. This is a sample of the logs that I see immediately after telling the app to auto upload a folder. When the app succeeds I can see it uploading files, when it's not working I don't even see an attempt from the app to list the InstantUpload directory.
```
192.168.0.48 - jeff [11/Mar/2021:16:29:37 +0000] "GET /nextcloud/ocs/v2.php/apps/serverinfo/api/v1/info HTTP/1.1" 200 2687 "-" "nextcloud-exporter/"
192.168.0.212 - - [11/Mar/2021:16:29:38 +0000] "GET /nextcloud/index.php/apps/facerecognition/process HTTP/1.1" 200 880 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0"
192.168.0.48 - jeff [11/Mar/2021:16:29:39 +0000] "GET /nextcloud/ocs/v2.php/apps/serverinfo/api/v1/info HTTP/1.1" 200 2691 "-" "nextcloud-exporter/"
192.168.0.48 - jeff [11/Mar/2021:16:29:41 +0000] "GET /nextcloud/ocs/v2.php/apps/serverinfo/api/v1/info HTTP/1.1" 200 2697 "-" "nextcloud-exporter/"
192.168.0.212 - - [11/Mar/2021:16:29:43 +0000] "GET /nextcloud/index.php/apps/facerecognition/process HTTP/1.1" 200 880 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0"
192.168.0.48 - jeff [11/Mar/2021:16:29:43 +0000] "GET /nextcloud/ocs/v2.php/apps/serverinfo/api/v1/info HTTP/1.1" 200 2691 "-" "nextcloud-exporter/"
192.168.0.48 - jeff [11/Mar/2021:16:29:45 +0000] "GET /nextcloud/ocs/v2.php/apps/serverinfo/api/v1/info HTTP/1.1" 200 2685 "-" "nextcloud-exporter/"
192.168.0.48 - jeff [11/Mar/2021:16:29:47 +0000] "GET /nextcloud/ocs/v2.php/apps/serverinfo/api/v1/info HTTP/1.1" 200 2688 "-" "nextcloud-exporter/"
192.168.0.212 - - [11/Mar/2021:16:29:48 +0000] "GET /nextcloud/index.php/apps/facerecognition/process HTTP/1.1" 200 880 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0"
192.168.0.48 - jeff [11/Mar/2021:16:29:49 +0000] "GET /nextcloud/ocs/v2.php/apps/serverinfo/api/v1/info HTTP/1.1" 200 2691 "-" "nextcloud-exporter/"

```

#### Nextcloud log (data/nextcloud.log)

This is identical to the webserver logs on my system.

More Info:
```
root@nextcloud:~# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by tobiasKaminsky** [comment]
I think you reported this already or at least mentioned the same problem in a different issue, or?

**Comment by jeffWelling** [comment]
Indeed, my apologies. 

This did end up working, I think the problem was that I had so many pictures in my camera roll that the app took so long to 'process' them before it even began uploading that I and I suspect many others just thought the feature was broken. 

They are related, though that wasn't obvious to me when I filed them. 
There is no bug, there is only a need to communicate more clearly with the user, which we're discussing in https://github.com/nextcloud/android/issues/8154

Let's continue this discussion there, I'll close this out for now.
