### ISSUE TITLE
App crashes on start

### ISSUE THREAD

**Issue by MultiCoreNop** [nextcloud/android#8164]
### Steps to reproduce
1. start app
2. 
3. 

### Expected behaviour
- app starts

### Actual behaviour
after last update:
- app crashes

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

### Logs
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.ArrayList.get(int)' on a null object reference
	at com.owncloud.android.lib.common.operations.RemoteOperationResult.getSingleData(RemoteOperationResult.java:527)
	at com.owncloud.android.operations.RefreshFolderOperation.updatePredefinedStatus(RefreshFolderOperation.java:339)
	at com.owncloud.android.operations.RefreshFolderOperation.updateCapabilities(RefreshFolderOperation.java:304)
	at com.owncloud.android.operations.RefreshFolderOperation.updateOCVersion(RefreshFolderOperation.java:276)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:229)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:359)
	at java.lang.Thread.run(Thread.java:919)

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20210304
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus3T
Model: ONEPLUS A3003
Id: QQ2A.200501.001.B2
Product: lineage_oneplus3

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: eng.nomahl.20200605.115231

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by hlovdal** [comment]
>ID: com.nextcloud.android.beta
>Version: 20210304

Have you tested with the latest<sup>1</sup> 20210309 version? The reason for asking is that the last stack trace line is from the library code base and not the application code base, and the release notes for 20210309 says "Update Nextcloud Android library". Thus it could be that those changes fixes or does not trigger the problem you observe.

----

<sup>1</sup> At least 20210309 is the latest on [F-Droid](https://f-droid.org/en/packages/com.nextcloud.android.beta/) as of writing this, although there is [another issue](https://github.com/nextcloud/android/issues/8163) that references version 20210310. Maybe there is a slightly newer one on Google's playstore?

**Comment by MultiCoreNop** [comment]
I just tried the 20210309 - that fixes the problem. App starts again. Thanks for the pointer!
