### ISSUE TITLE
Thanks for the update and for the record 👍👍😁

### ISSUE THREAD

**Issue by bludya1986** [nextcloud/android#8165]
### Additional context

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by bludya1986** [comment]
`@bludya1986 `🛠️🧱🕛👍🤣💣

**Comment by tobiasKaminsky** [comment]
Thanks maybe? 🙈🎉
