### ISSUE TITLE
Grid view doesn't show thumbnails

### ISSUE THREAD

**Issue by kvoit** [nextcloud/android#817]
### Actual behaviour
-Switching the app to grid viewonly shows generic grey images for pictures, while list view has actual tumbnails. Images in question are synchronized to the phone (green tick).

### Expected behaviour
- Grid view should show thumbnails. I feel that is kind of the purpose of a grid view ...
 
### Steps to reproduce
1. Open a synchronized folder with images in app
2. Switch to grid view
3. Notice that only generic grey icons are shown

### Environment data
Android version: 7.1.1

Device model: Oneplus Three

Stock or customized system: Stock Community Edition

Nextcloud app version: 20170317

Nextcloud server version: 11.0.2.7

**Comment by kvoit** [comment]
![screenshot_20170409-091225](https://cloud.githubusercontent.com/assets/1532745/24835547/60c0c9e6-1d05-11e7-9ed4-411a85eff516.png)

**Comment by tobiasKaminsky** [comment]
I will soon update the nightly version and take care of this.

**Comment by tobiasKaminsky** [comment]
This is working again.
