### ISSUE TITLE
Grid view toolbar gone when opening app first time after update

### ISSUE THREAD

**Issue by Derkades** [nextcloud/android#8176]
The grid view button is no longer present in the files section, has it been (re)moved? The media section still has the grid view but it is not usable for navigating folders, images are displayed in a seemingly random order.

It could have been caused by a previous update, I don't use it that often.

**Comment by tobiasKaminsky** [comment]
Is this button also gone directly when you start the app?
I can see the button and it it still working.

**Comment by Derkades** [comment]
It's back now, same for sorting. That row with controls was just gone before, not sure why

**Comment by Derkades** [comment]
Apparently this happens after setting up the app for the first time. Force closing and re-opening the app makes it show up.

**Comment by Derkades** [comment]
I would test again but I have to wait for a new update first

**Comment by Derkades** [comment]
See previous comment

**Comment by Derkades** [comment]
Waiting for it to appear on F-Droid

**Comment by Derkades** [comment]
Maybe fixed coincidentally, it didn't happen on the 3.16.1 -> 3.17.0 update. Fingers crossed I guess.
