### ISSUE TITLE
old user credentials not deleted

### ISSUE THREAD

**Issue by jookk** [nextcloud/android#8178]
Recently I moved to Nethserver and I had to change my usernames and passwords. 
So steps:
1. Removed account from Accounts menu on os settings.
2. logged in with new login and password

Syncing worked, but I had blocking with fail2ban, because nc client logging on background  with old username and pass. 
I had this on all my devices, and one device awaiting next steps, which helped me to resolve:
1. Remove account from os settings
2. Go to app manager, than nextcloud -> Remove all data and cache, force close app by button
3. Next new login with new user credentials. 

Can you look at? Seems bug, now at this pandemics time I must go person by person re-move and re-login again. 

App 3.15.
android 10, 8, 7

**Comment by tobiasKaminsky** [comment]
Preferred way is to remove the account while being in the app.
Can you test this?

**Comment by jookk** [comment]
I changed password on server and after first app open, client offered me to enter new server url. 
I pushed back button and force close. After app open again, fc and so on. 
So I can not remove account from the app. 
Im going to remove account from os settings and purge app data, because no other way to go.
