### ISSUE TITLE
Nextcloud App 3.16.0 RC1 the drain bar remains active

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/android#8179]
when a file is synchronized with nextcloud 3.16.0 RC1 the unloading bar after reaching 100% does not disappear but remains fixed between the android notifications.  I am attaching screenshots

![Screenshot_20210317-143959](https://user-images.githubusercontent.com/35575744/111477232-322db100-872f-11eb-9366-76476aae5f78.png)

**Comment by AndyScherzinger** [comment]
pinging @newhinton and @tobiasKaminsky - I guess this came in with #7949 where we stop dismissing the notification after each up/download while we should dismiss it with the last completed up/download 😉

**Comment by newhinton** [comment]
Ah yes, my bad. I was not sure if that was actually a bug in this app or if my phone acted up, but i fixed that.

Is it okay to just show nothing when all downloads succeeded? If yes, i'll just push my branch with a fix

**Comment by newhinton** [comment]
I forgot, my 'fix' brought back the issue with the not reused notification. I'll have to write a small handler that delays the dismiss for a few seconds, so that it only gets dismissed when no new download starts.

**Comment by newhinton** [comment]
Actually, i think i have to reopen this. On my device at least, i still get the notification stuck when the app was not opened recently and a file updated. I am not sure how to debug this, because as soon as i add a debugger, the fix works as expected. Can anyone confirm this?

**Comment by af7567** [comment]
I also have this bug still with 3.16.0 RC2 installed from the play store beta. 
It seems to happen when I modify a "favourite" file on my PC and the Android app later downloads it in the background automatically. Then the notification will stay at 100% until I force stop the app.

**Comment by calvinrw** [comment]
I am seeing this behavior in 3.16.0 installed via F-Droid. I have a file in my Nextcloud account that is set to sync to my phone, but modifications to it usually happen on various computers. Starting with the most recent update, any time this file is modified the Android client will successfully synchronize the new version of the file, but the download notification doesn't get dismissed automatically, not can it be manually dismissed. Short of rebooting the phone, the only way I've found to dismiss the notification is to force stop Nextcloud.

**Comment by calvinrw** [comment]
Following up, this is still an issue on version 3.16.1 via F-Droid.

![Screenshot_20210618-063817_Trebuchet_resize](https://user-images.githubusercontent.com/687129/122607125-b3068c80-d03f-11eb-9f35-f20d16f863fd.png)

**Comment by newhinton** [comment]
There are multiple issues for this, i am closing this in favor of #8308
If this is not solved with #8308, please reopen.
