### ISSUE TITLE
Upload waiting queued items on click

### ISSUE THREAD

**Issue by kvoit** [nextcloud/android#818]
Especially due to #486 I regularly have e.g. images in my upload queue waiting for a wifi to autoupload. there doesn't seem to be a way to manually start the upload, e.g. to share it. I suggest that clicking on a waiting file should start the upload, regardless if it was queued as a wifi-only upload or not.

**Comment by joshtrichards** [comment]
Let's consolidate tracking for this into #7019 where most of the voting/discussion has occurred.
