### ISSUE TITLE
SAF documentsprovider fails when client application is updated 

### ISSUE THREAD

**Issue by lpaatero** [nextcloud/android#8180]
### Steps to reproduce

1. Install application in https://github.com/lpaatero/SAFtest. It allows viewing a directory tree in SAF documensproviders.
2. Open non-empty directory from nextcloud using SAFtest. Directory content is listed.
3. Update the SAFtest application (no real change needed, just update).
4. Start the SAFtest application. Opened directory is not accessible, even though permissions to access it is present.
(5. Reboot device. Content of directory is again visible to SAFtest application.)

### Expected behaviour

- When SAF client has persisted SAF permissions to access a directory tree provided by nextcloud app, the permissions should works even after client application is updated.

### Actual behaviour

- The client app cannot access the tree after the client application is updated. (Access again possible once the device is rebooted)
- Android's default documentsProvider work as expected with SAFtest app.

### Environment data

Android version: Android 11

Device model: Pixel 2 and Pixel 4a

Stock or customized system: Stock

Nextcloud app version: 3.15.1

Nextcloud server version:

Reverse proxy: None

**Comment by tobiasKaminsky** [comment]
Thanks for this bug report, as you seem to be a bit into SAF ;-) 
Do you have an idea why this happens?

Is this also happening with another SAF app?

**Comment by lpaatero** [comment]
SAF may not be the most beautiful thing in the world, but seems to become mandatory...
I am updating my app to use SAF, and nextcloud seems to be the only cloud storage that support directory tree; Big thanks for that!

Only other SW supporting the SAF tree opening is the android default documentsprovider, as far as I know. It seems to not have this problem. I may use trees from android default documentsprovider and nexcloud at the same time, and android provider works while nextcloud does not.

I have no idea why the problem happens, and I do not know contentproviders so well.

Some notes when error happens:
- it looks like android OS thinks that the permissions are still there, as they are listed in getPersistedUriPermissions() return values
- But nextcloud content provider is not listed in content providers, if listed using queryIntentContentProviders(), and error messages indicates content provide does not exist
- If I restart device, or add new nextcloud SAF tree permission, problem goes away, and all looks normal

So it looks like somehow the nextcloud contentprovider is invisible to updated application, until some event corrects the problem. Perhaps there is something cached about the application in nextcloud side?
