### ISSUE TITLE
Auto upload menu completely disappeared

### ISSUE THREAD

**Issue by thenickname** [nextcloud/android#8181]
Auto upload functionality just vanished?? Upload is not working and the menu is gone.

![IMG_20210317_220418](https://user-images.githubusercontent.com/1009726/111538394-e8fc5200-876c-11eb-8e16-39eda269a4ca.jpg)

**Comment by thenickname** [comment]
*Android 11,  Xiaomi MIUI 12

Auto upload functionality is missing from both fdroid and play store versions

**Comment by AndyScherzinger** [comment]
Since 3.15.0 the auto upload can be found in the settings screen.

**Comment by thenickname** [comment]
whoops thanks for clarifying 😳

**Comment by AndyScherzinger** [comment]
Happy to help ❤️
