### ISSUE TITLE
AutoUpload: "Failed to create conflict dialog"

### ISSUE THREAD

**Issue by muellert** [nextcloud/android#8198]
### Steps to reproduce
1. Try uploading images into an existing Nextcloud instance.
2. Find a conflict
3. See this message appear in the notifications section

### Expected behaviour
- A dialogue would appear that allows me to decide how to proceed (keep server file, rename copy etc.)

### Actual behaviour
- A notification appears that indicates that this part of the UI does not work.

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 11

Device model: OnePlus 8Pro IN2020

Stock or customized system: LineageOS 18.1

Nextcloud app version: 3.15.1

Nextcloud server version: 20.0.8

Reverse proxy: nginx

But this is all not applicable since the problem is with the UI of the app.

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

**Comment by muellert** [comment]
Checking...

**Comment by cjdg** [comment]
i have the same issue

**Comment by cjdg** [comment]
Recently update to 3.16 and still happens the same

**Comment by WarmChocolateCake** [comment]
Just to add that this has happened to me too, but it was during resolution of a failed auto-upload... if / when it happens again, I'll see if I can dig into the logs.
