### ISSUE TITLE
Android app synchronise works but not unsync

### ISSUE THREAD

**Issue by Topkif** [nextcloud/android#8209]
### Steps to reproduce
1. Choose a folder or a file
2. Click the three dots
3. Click Synchronise
4. Do it again on the same file

### Expected behaviour
- The sync option shoud have disappear and a desync button should appear

### Actual behaviour
- The sync button stays and you cannot unsync anything

### Can you reproduce this problem on https://try.nextcloud.com?
- doesn't work on adroid

### Environment data
Android version: 11

Device model: SM-G781B/DS

Stock or customized system: Stock

Nextcloud app version: 3.15.1

Nextcloud server version: 21, plugin on Truenas Core 12

Reverse proxy: No

**Comment by tobiasKaminsky** [comment]
What is "desync" / unsync?

**Comment by Topkif** [comment]
You can sync your folder but I havn't found any way except reinstalling the
app to stop the synchronisation of the folder. I am afraid I can't give you
any mode details as I am currently changing my hardware and my server will
be down for a while.
Hope this helped.

**Comment by SeWieland** [comment]
Folders are not kept in sync. It's a "one-time" sync. If I change any the file on the device after the sync, it will not be uploaded immediately to the server. If the same file is modified server-side then, the file will appear out-of-sync in the app.

Therefore no unsync.

**Comment by Topkif** [comment]
Ok I got it, this isn't the feature I was thinking about then. What I would
have liked is a feature to access the files you have previously chosen even
if you are offline. It would keep the latest version of a file or folder
downloaded on the phone. Don't you think it would be nice to have such a
feature?
What should I do with the issue page on github?
Thanks for your answer.

**Comment by SeWieland** [comment]
@Topkif The feature you are talking about is indeed very often requested and even dates back to two oldest open issues: #19 and #21 as well several "newer" ones like #3673 and others..

So just keep an eye on those I guess or if you do not want to wait start learning JAVA and implement it yourself (jk)^^

**Comment by Topkif** [comment]
Thank you very much for the advice and the reply.

Good luck
