### ISSUE TITLE
Dev "App not installed" messsage

### ISSUE THREAD

**Issue by kofaysi** [nextcloud/android#8215]
### Steps to reproduce
1. Receive notification on update on the Dev channel in NextCloud Dev app
2. Download and run apk

### Expected behaviour
- App shall install successfully

### Actual behaviour
- App not installed + the same message
- the app can be and is successfully updated using F-Droid, if update is available there.

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 10

Device model: LG-H850

Stock or customized system: eOS 0.15-q

Nextcloud app version: 20210320

Nextcloud server version: NA

Reverse proxy: NA

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
No log or error code produced
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
You can either install manually dev  version via apk or via fdroid, but you cannot mix it as both have different signatures.
