### ISSUE TITLE
Auto-send does not work

### ISSUE THREAD

**Issue by talesam** [nextcloud/android#8216]
I have a Mi5 running a Custom ROM, running Pixel with android 10. The Nextcloud is without battery optimization, but the auto-sending does not work.

Another problem that I discovered is the following:
There is an option to configure a custom folder globally or separately, this global (custom) configuration does not work. I configure and save, when I enter the configuration again it appears without being configured.

![photo_2021-03-28_13-40-04](https://user-images.githubusercontent.com/981368/112759837-2cf02200-8fcb-11eb-8ade-5ab5aa5b87ea.jpg)

where can i send the log file?

**Comment by tobiasKaminsky** [comment]
> The Nextcloud is without battery optimization, but the auto-sending does not work.

Probably there is another battery saving mechanism.
Custom RMs are hard to test…

**Comment by talesam** [comment]
> > The Nextcloud is without battery optimization, but the auto-sending does not work.
> 
> Probably there is another battery saving mechanism.
> Custom RMs are hard to test…

I am using the DEV version and it works normally and does not eat as much battery as the stable version.
