### ISSUE TITLE
Window with "Auto upload" in "On device"

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/android#8219]
### Steps to reproduce

1. Select "Upload files".
2. Go to "Auto upload".
3. Select "On device" from the menu.

After selecting "On device" the window with "Auto upload" remains.

- After selecting "Auto upload" from the menu:

![obraz](https://user-images.githubusercontent.com/47037905/112764213-cccba100-9007-11eb-9fe2-13d7315eb3ce.png)
---

- After selecting "On device" from the menu:

![obraz](https://user-images.githubusercontent.com/47037905/112764187-b4f41d00-9007-11eb-928e-d7abfe83beb0.png)

- The same happens without uploading the file.

### Environment data
Android version:
10
Nextcloud app version:
3.16.0 RC2

**Comment by tobiasKaminsky** [comment]
> * Select the file to send.
> 
> *

What does this mean?

**Comment by Valdnet** [comment]
@tobiasKaminsky Corrected 😉. It's about selecting the file to upload.
