### ISSUE TITLE
[Feature request] get login data from qrCode

### ISSUE THREAD

**Issue by Mannshoch** [nextcloud/android#822]
Inlude a barcode scanner to add accounts to the app.
![qrcode-calendar](https://cloud.githubusercontent.com/assets/7795891/24918446/ba0c4372-1ee0-11e7-87c6-a8943c4944cb.png)

maybe this code could be useful: @zxing/zxing
see Feature request on: [https://github.com/nextcloud/server/issues/4305](https://github.com/nextcloud/server/issues/4305)
see Feature request on: [DavDroid](https://forums.bitfire.at/topic/1406/feature-request-allow-to-get-address-and-credentials-from-qrcode)

So I'm able to handout Caldav/Carddav/Webdav/Federation Links.
Our Club has many people without any Computer knowledge. If I setup their nextcloud access I could generate this codes to get them easy access by mobile-phone without have to deal with user names and passwords, also If **I** have to setup their phone.

**Comment by AndyScherzinger** [comment]
https://nextcloud.com/blog/nextcloud-android-client-1.4.0-has-been-released/

The client already supports this since version 1.4.0, see blog post above while this supports logins including all credentials but no special links to shares etc but general account logins.

**Comment by tobiasKaminsky** [comment]
@Mannshoch is this enough or is it needed to enhance this?
For davdroid at least it is sufficient to handle the server url and login/password, if I remember correctly.
