### ISSUE TITLE
Next Cloud is not letting  me in to the app. Doesn't send me any email for password or anything else.  I have 2GB uploaded in the App videos and photos that I need to download from it.

### ISSUE THREAD

**Issue by Vinz719** [nextcloud/android#8234]
### Steps to reproduce
1. Next Cloud is not letting  me in to the app. Doesn't send me any email for password or anything else.  I have 2GB uploaded in the App videos and photos that I need . Doesn't  open. Keeping my photos inside the app.
2. @vinz719
3. vinicioreinaluther77@gmail.com 
4. +34657585123
My phone #

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by Vinz719** [comment]
I need my files. Don't belong to Next Cloud. It Appears to my as corruption

**Comment by Spartachetto** [comment]
You are not providing enough information to help you, yet you are complaining in the wrong place.

This is the place where the code of Nextcloud **android app** is developed.
If you are using this app, the app uploads your data on a Nextcloud server. 
The server is not managed by Nextcloud (the company) nor by the community.
A server can be installed on one of your computers and managed by you (or a friend of yours),or by a provider (there are a lot of them, you have a partial list here: https://nextcloud.com/signup/ ),or by  your employer, ....

If you need your data back, you have to talk to whoever manages the specific server you uploaded your data to.

Hope that helps!
