### ISSUE TITLE
Activities do not work on Android App. As it seems it tries to use port 80. Why not use 443, too

### ISSUE THREAD

**Issue by Fantomas200** [nextcloud/android#8237]
### Steps to reproduce
1. Just tap on "Aktivitäten" 
2. 
3. 

### Expected behaviour
- show the recent activities

### Actual behaviour
- Http status code -1 (fail)

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by Mic-Pod** [comment]
I have the same issue. NC 21.0.1, APP 3.15.1.
Error in apache log:
`GET /ocs/v1.php/cloud/user?format=json HTTP/1.1" 200 1739 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.15.1`
![Screenshot_20210419-142635_Nextcloud](https://user-images.githubusercontent.com/57563877/115237442-dcc53500-a11c-11eb-954b-baf45466cd16.jpg)

**Comment by Mic-Pod** [comment]
I have deployed completely new, clean instance - same issue.

**Comment by Mic-Pod** [comment]
@tobiasKaminsky Yes, correct. Not an error, but the only thing that appears in logs during opening Activity in app.
Maybe it is related to the data directory being moved outside Nextcloud directory?
After a clean install, Activity in app was working, but after few, standard customizations in config.php it was broken again.

**Comment by Fantomas200** [comment]
> @Fantomas200 where do you see port 80?
> App should always use the connection which was specified during login.

I saw it on the error text. And as it states the no connection via http the easiest explanation is port80![Screenshot_20210430-122037_Nextcloud.jpg](https://user-images.githubusercontent.com/37751153/116682582-b91cad00-a9ae-11eb-9c59-0185487995f7.jpg)

**Comment by AndyScherzinger** [comment]
> I saw it on the error text. And as it states the no connection via http the easiest explanation is port80

This should have nothing todo with http/https since the message says "http status code" which a a fixed standard set of codes that are defined for http/s connections. But I get why this might be misleading... :/

**Comment by Mic-Pod** [comment]
App Version 3.16.0 and issue is still there. Any ideas?

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky any ideas? I guess we can't tell without a test account to debug from the client side.

**Comment by Fantomas200** [comment]
Error progresses... Tried to reinstall the App. Now I get a http -1 error on login, too. (Even App Token does not work / shows same error)![Screenshot_20210510-090106_Nextcloud.jpg](https://user-images.githubusercontent.com/37751153/117618461-46f65600-b16e-11eb-9a47-963dad589a38.jpg)

**Comment by Fantomas200** [comment]
> @tobiasKaminsky any ideas? I guess we can't tell without a test account to debug from the client side. 

Where shoud I send you the login credentials?

**Comment by vthg2themax** [comment]
Try turning on TLS1.2. It was the only thing I could get to make the Android app work. The HTTP status code -1 (fail) is probably a result of an unsupported security configuration, such as only allowing TLS1.3.

**Comment by Mic-Pod** [comment]
> Try turning on TLS1.2. It was the only thing I could get to make the Android app work. The HTTP status code -1 (fail) is probably a result of an unsupported security configuration, such as only allowing TLS1.3.

@vthg2themax Thank You! You are awesome! :) Finally we know why it was not working. After enabling TLS 1.2 (previously only 1.3 was enabled) Activity is loading properly. Weird thing is that everything else in App is working fine with TLS 1.3.

Can it be fixed now?

**Comment by vthg2themax** [comment]
> > Try turning on TLS1.2. It was the only thing I could get to make the Android app work. The HTTP status code -1 (fail) is probably a result of an unsupported security configuration, such as only allowing TLS1.3.
> 
> @vthg2themax Thank You! You are awesome! :) Finally we know why it was not working. After enabling TLS 1.2 (previously only 1.3 was enabled) Activity is loading properly. Weird thing is that everything else in App is working fine with TLS 1.3.
> 
> Can it be fixed now?

@Mic-Pod I am not the developer of this app, so I cannot provide a fix. I just noticed this issue on my own instance, and after a ton of research eventually found the culprit. I believe that there needs to be a lot of changes in the app to make this work. I don't want to enable TLS1.2 at all, but I am stuck with this option until there is a proper fix. I am not familiar with Java Android development, so I would not be able to offer any guesses as to how tough this may be.

**Comment by szaimen** [comment]
@tobiasKaminsky wasn't this issue alredy fixed with https://github.com/nextcloud/android-library/pull/618 or does that fix a different issue?

**Comment by AndyScherzinger** [comment]
@szaimen you are right, the fix you are referring to applies here as well 👍

**Comment by AndyScherzinger** [comment]
Fix shipping with next release. Workaround for the time being would be to also allow for tls1.2
