### ISSUE TITLE
Nextcloud Android App fails connect to Nextcloud 20 docker container behind SSL proxy

### ISSUE THREAD

**Issue by HiranChaudhuri** [nextcloud/android#8242]
### Steps to reproduce
1. Install Nextcloud docker container
2. Install Apache httpd as reverse proxy to perform SSL (the SSL certificate's root is part of the Android truststore)
3. Install Nextcloud android app
4. Start Nextcloud android app
5. Click "Anmelden" -> Login?
6. Enter server address https://nextcloud.fritz.box
7. Confirm "Anmelden" -> Login?
8. Enter username and password
9. Confirm "Zugriff gewähren" -> "approve access"?

### Expected behaviour
- I'd expect I am able to synchronize data

### Actual behaviour
- In the android app, having approved the access it seems the app is stuck. The loading cursor never goes away. Data cannot be synchronized. What is the app waiting for?

### Can you reproduce this problem?
If I enter the URL of the nextcloud installation directly (http://nextcloud.fritz.box, without going via reverse proxy) I can synchronize data as expected - however the data is not encrypted.

### Environment data
Android version: 10 (Kernel 4.14.141, patches 05NOV20)

Device model: Gigaset GS4

Stock or customized system: ?probably stock?

Nextcloud app version: 3.15.1

Nextcloud server version: 20.0.8.1

Reverse proxy: Apache httpd

#### Reverse proxy error log
```
nextcloud.fritz.box 192.168.178.72 - - [04/Apr/2021:22:16:09 +0000] "GET /index.php/login?redirect_url=/index.php/login/flow/grant?clientIdentifier%3D%26stateToken%3DhszlyW4HNxYiwipLvPb8PlIRG7FJt2VQFzS8MESDDgXMNyuPBYxb1NZ9qipXYyYb HTTP/1.1" 303 - "-"
nextcloud.fritz.box 192.168.178.72 - - [04/Apr/2021:22:16:09 +0000] "GET /index.php/login/flow HTTP/1.1" 200 3959 "-"
nextcloud.fritz.box 192.168.178.72 - - [04/Apr/2021:22:16:11 +0000] "GET /index.php/core/js/oc.js?v=3c116af8 HTTP/1.1" 200 4433 "-"
nextcloud.fritz.box 192.168.178.72 - - [04/Apr/2021:22:16:12 +0000] "GET /cron.php HTTP/1.1" 200 20 "-"
```

#### Nextcloud log (data/nextcloud.log)
```
172.19.0.13 - - [04/Apr/2021:22:16:09 +0000] "GET /index.php/login?redirect_url=/index.php/login/flow/grant?clientIdentifier%3D%26stateToken%3DhszlyW4HNxYiwipLvPb8PlIRG7FJt2VQFzS8MESDDgXMNyuPBYxb1NZ9qipXYyYb HTTP/1.1" 303 930 "-" "Gigaset E940-2795-00 (Android)"
172.19.0.13 - - [04/Apr/2021:22:16:09 +0000] "GET /index.php/login/flow HTTP/1.1" 200 4963 "-" "Gigaset E940-2795-00 (Android)"
172.19.0.13 - - [04/Apr/2021:22:16:11 +0000] "GET /index.php/core/js/oc.js?v=3c116af8 HTTP/1.1" 200 5861 "-" "Gigaset E940-2795-00 (Android)"
172.19.0.13 - - [04/Apr/2021:22:16:12 +0000] "GET /cron.php HTTP/1.1" 200 931 "-" "Gigaset E940-2795-00 (Android)"
172.19.0.13 - - [04/Apr/2021:22:16:37 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 304 286 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0"
172.19.0.13 - - [04/Apr/2021:22:17:07 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 304 286 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0"
172.19.0.13 - - [04/Apr/2021:22:17:13 +0000] "PUT /index.php/apps/user_status/heartbeat HTTP/1.1" 204 723 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0"
172.19.0.13 - - [04/Apr/2021:22:17:13 +0000] "GET /ocs/v2.php/apps/user_status/api/v1/user_status HTTP/1.1" 200 955 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0"
172.19.0.13 - - [04/Apr/2021:22:17:33 +0000] "GET /index.php/settings/user HTTP/1.1" 200 19291 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0"
172.19.0.13 - - [04/Apr/2021:22:17:34 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 2322 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0"
172.19.0.13 - - [04/Apr/2021:22:17:34 +0000] "GET /ocs/v2.php/search/providers?from=%2Fsettings%2Fuser HTTP/1.1" 200 1056 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0"
172.19.0.13 - - [04/Apr/2021:22:17:34 +0000] "PUT /index.php/apps/user_status/heartbeat HTTP/1.1" 204 723 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0"
172.19.0.13 - - [04/Apr/2021:22:17:34 +0000] "GET /cron.php HTTP/1.1" 200 932 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0"
172.19.0.13 - - [04/Apr/2021:22:17:34 +0000] "GET /ocs/v2.php/apps/user_status/api/v1/user_status HTTP/1.1" 200 955 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0"
172.19.0.13 - - [04/Apr/2021:22:18:04 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 304 286 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0"
172.19.0.13 - - [04/Apr/2021:22:18:34 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 304 286 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0"
```

**Comment by AndyScherzinger** [comment]
Hi @HiranChaudhuri, please search the forum, e.g. https://help.nextcloud.com/t/mobile-app-cant-login-with-reverse-proxy/111050/2

The reason is most likely a server configuration parameter missing. The login flow is waiting for the redirect which won't work if the server isn't properly configured.

**Comment by HiranChaudhuri** [comment]
I agree everything is pointing to an inproperly configured reverse proxy. Unfortunately there seems no known way to check if a server is configured properly or not: https://help.nextcloud.com/t/apache-reverse-proxy-setup-and-android-app-how-to-verify/110841/7

I reconfigured my nextcloud installation from this:
```
[root@homeserver nextcloud]# grep -ri overwritep *
config/config.sample.php:'overwriteprotocol' => '',
config/others.config.php:'overwriteprotocol' => '',
[root@homeserver nextcloud]#
```

to this:
```
[root@homeserver nextcloud]# grep -ri overwritep *
config/config.sample.php:'overwriteprotocol' => '',
config/others.config.php:'overwriteprotocol' => 'https',
[root@homeserver nextcloud]#
```
(which should have the desired effect according to https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html)

Unfortunately the behaviour towards the nextcloud app is unchanged. I do not expect you to fix my reverse proxy, but is there any way to find out what the app is missing? What requests need a response to continue? Are there logfiles on client side?

**Comment by AndyScherzinger** [comment]
Unfortunately no, but maybe other user might be able to help in the forum: https://help.nextcloud.com/

**Comment by HiranChaudhuri** [comment]
I believe this issue essentially the same as
https://github.com/nextcloud/android/issues/6576

And I totally agree if the Nextcloud App does not show errors and has no logfile it does not allow for educated troubleshooting. Hence there are so many attempts that just poke in the dark.
