### ISSUE TITLE
Server

### ISSUE THREAD

**Issue by Vinz719** [nextcloud/android#8243]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is. Ex. I'm always frustrated when [ I try to enter. The server address is Empty. I can not get in to the Cloud.  I have 2 GB of Files inside. I need my Files. Nobody seems to help here. It's a disgrace and an abuse. This has no limits. I just upload the 2 gb and then after some days the server and everything dissapeared .

### Additional context

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by Vinz719** [comment]
Shit Cloud  i shouldn't trust The Google Play Safety...they have too many Apps Like This this That just gather info and then don't release it....Google has the fault.  They own Android and they just fuck the people for no reason

**Comment by jancborchardt** [comment]
I’m closing this one so we can focus on finding the solution in issue https://github.com/nextcloud/android/issues/8270
