### ISSUE TITLE
Log in hangs on Grant Access

### ISSUE THREAD

**Issue by brjhaverkamp** [nextcloud/android#8246]
### Steps to reproduce
1. Install android client beta 3.16-RC2
2.  Try to log in on an existing (self hosted in my case) nextcloud server

### Expected behaviour
After granting access by the server the client is logged in
### Actual behaviour
A spinning wheel while remaining on the "grant access" page.
When I downgraded to client 3.15.1, Login  went smoothly, so it seems to be particular to 3.16!

### Environment data
Android version: 7

Device model: 
Huawei-VIE9 (P9plus)
Stock or customized system:
Ubuntu 20.04 + Apache2+ Nextcloud 20.0.8
Nextcloud app version:
3.16-rc2
Nextcloud server version:
20.0.8
Reverse proxy:
Apache2
### Logs
There is nothing in the logs about this.
#### Web server error log
```
Insert your webserver log here
```

**Comment by tobiasKaminsky** [comment]
Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

**Comment by vthg2themax** [comment]
I can confirm downgrading to 3.15.1 from Fdroid works perfectly with QR code. Thank you for the solution!

**Comment by JayBeRayBearGun** [comment]
I have the same problem with 3.16.0 but using QR works great (and fast)

PS: i tried from different networks and white listed IPs just to see if that might have been an issue

**Comment by vthg2themax** [comment]
My issue was that TLS1.2 was not being allowed in my nginx configuration, and so once i re-enabled that, everything worked correctly in the Android app. My guess is that somehow TLS1.3 is not being accepted in a global way, and is therefore only affecting certain parts of the program. Just a guess, but if anyone hasn't tried to turn on TLS1.2, it may very well be the key you need!

**Comment by JCfrW** [comment]
Same problem here with both a Mi9t (Android 11) and a Lenovo Tab P11 (Android 10)
With version 3.15.x, everything is fine
QR code is not working either

[logcatOutput.txt](https://github.com/nextcloud/android/files/6503237/logcatOutput.txt)

thanks for your support.
