### ISSUE TITLE
Cannot reset app pin

### ISSUE THREAD

**Issue by jk111** [nextcloud/android#8248]
Is there any way to reset the Android app pin? Uninstalling the nextcloud client and re-installing from Play store does not remove the pin.

Using Android 11 on a Samsung S20+

**Comment by tobiasKaminsky** [comment]
The app pin is either a self chosen pin or Android's built in credentials.
Uninstalling the app should help in both cases, as all settings are deleted.
Or do you have some kind of backup which is automatically restored?
