### ISSUE TITLE
Nextcloud Doesn't Open To my Account 

### ISSUE THREAD

**Issue by Vinz719** [nextcloud/android#8249]
### Is your feature request related to a problem? Please describe.
I Try to opened but SERVER is in blank.
### Describe the solution you'd like
A clear and concise description of what you want to happen.  It doesn't have a Server. I Need A Server name.

### Additional context

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by jancborchardt** [comment]
I’m closing this one so we can focus on finding the solution in issue #8270
