### ISSUE TITLE
应用无响应，卡死

### ISSUE THREAD

**Issue by SuperApollo** [nextcloud/android#8255]
### 应用程序经常无响应，是不是在主线程做了太多操作？
![Screenshot_20210409-170031_Nextcloud](https://user-images.githubusercontent.com/17996455/114158507-527c1480-9957-11eb-9b14-385f63965e98.png)

**Comment by AndyScherzinger** [comment]
Hi @SuperApollo please post any issue/ticket in English. Thanks for your efforts! ❤️
