### ISSUE TITLE
已经上传成功了，但是状态栏提示上传失败

### ISSUE THREAD

**Issue by SuperApollo** [nextcloud/android#8256]
### 上传已经成功，从web端可以看到，后台数据里也可以看到文件，但是安卓客户端提示上传失败，而且很频繁，iOS就没有这个错误
![Screenshot_20210409-171158_Nextcloud](https://user-images.githubusercontent.com/17996455/114158686-8ce5b180-9957-11eb-9dca-905da2fd1524.png)

**Comment by AndyScherzinger** [comment]
Hi @SuperApollo please post any issue/ticket in English. Thanks for your efforts! ❤️
