### ISSUE TITLE
Concurrent Uploads

### ISSUE THREAD

**Issue by SuperApollo** [nextcloud/android#8257]
- 安卓客户端上传问价貌似是单线程的，每次只能上传一个文件，而iOS客户端是可以5个文件同时上传，速度快很多
- 希望安卓客户端能够像iOS那样并发上传文件，提升效率

**Comment by AndyScherzinger** [comment]
Hi @SuperApollo please post any issue/ticket in English. Thanks for your efforts! ❤️

**Comment by sirliu** [comment]
> Hi @SuperApollo please post any issue/ticket in English. Thanks for your efforts! ❤️

He said hope the Android NextCloud client support Concurrent uploading which the iOS client already supported，so do I。Hope you can understand my poor English。

**Comment by AndyScherzinger** [comment]
Perfect, thanks @sirliu ❤️

**Comment by szaimen** [comment]
Duplicate of https://github.com/nextcloud/android/issues/6794
