### ISSUE TITLE
Cannot login after upgrade to server v21 on a server that changed its dns name since user creation

### ISSUE THREAD

**Issue by fondemen** [nextcloud/android#8259]
After upgrading my server, android app could no longer connect. I tried to create a brand new cluster with another (older) domain: the app can connect. But as soon as I import my data (database + files), the app can no longer connect. When trying to recreate registration (after deleting app data), I can enter my password, accept that the app uses my account, and then the app comes back to the first step of the connection process. After a lot of different experiments I found out that my user was created using an OLD domain name (I changed my server domain a while ago). I was able to connect again when I re-enabled my OLD domain and connect the android app using that old domain name (despite the fact that in my server the overwrite.cli.url is still using the new domain). From the database dumps, it seems that the domain name is appended to the actual user id (myuser@mydomain.tld) ; it sounds that the android app is "lost" when the user domain mismatches the actual domain.

### Steps to reproduce
1. Create a server v20
2. Create user
3. Change domain name for server
3. Login using Android app
4. Upgrade server to 21

### Expected behaviour
- Nothing : app should work seamlessly

### Actual behaviour
- App cannot login anymore
- Cannot recreate the account using user id
- Cannot recreate the account using QR-code

### Can you reproduce this problem on https://try.nextcloud.com?
- No (user is created using the proper domain)

### Environment data
Android version: 7

Device model:  FP2

Stock or customized system:

Nextcloud app version:

Nextcloud server version: 21 (docker)

Reverse proxy: nginx

**Comment by szaimen** [comment]
Hi, if I understand your issue correctly, it is the same like: https://github.com/nextcloud/android/issues/4157

**Comment by fondemen** [comment]
It might be the case yes, though I think it worked properly before the upgrade despite the fact domain was changed already.
Still, behavior is weird : a new user can access the android app, and the day after, it does not work anymore for him.
I've made a database dump, replaced in the dum every occurence of my old domain to the new domain, drop the DB and load it with upgraded data : same problem bites again...

**Comment by tobiasKaminsky** [comment]
Changing server domain for existing account is not supported.
In this case you have to setup a new account.

**Comment by fondemen** [comment]
OK. I've dumped the database and changed any occurence of the old domain to the new one, then recreated the database with new data. It didn't solve the issue... until I've retried yesterday !
So... problem solved (by the update ?)
Thanks !
