### ISSUE TITLE
[3.16.0 RC2] black window is shown when selecting the breadcrumb menu after a search

### ISSUE THREAD

**Issue by j-ed** [nextcloud/android#8261]
### Actual behavior
If you enter a keyword in the search window and confirm the input, the search result is shown on the screen. If you now select the breadcrumb menu behind a file, a black window is shown instead of the available menu entries.

![20210410-nc-search-black-box](https://user-images.githubusercontent.com/2572764/114267018-ccfd7080-99f9-11eb-86ad-2b5f9181b5c2.jpg)

### Expected behavior
If you enter a keyword in the search window and confirm the input, the search result should be shown on the screen and if you select the breadcrumb menu behind a file name, the available menu entries should instantely been shown. 

### Steps to reproduce
1. Open the Nextcloud app and enter a search term
2. Select the breadcrumb menu behind a file name of the search result.
-> A black window is shown instead of the menu entries.

### Environment data
Android version: 11.0
Device model: Samsung Galaxy S20
Stock or customized system: Stock ROM
Nextcloud app version: 3.16.0 RC2
Nextcloud server version: 20.0.9

**Comment by tobiasKaminsky** [comment]
Is this only happening upon search?
As search uses the same file listing mechanism (and therefore also for the option menu), I am a bit surprised.
Locally tests of course work… :/

**Comment by j-ed** [comment]
I must admit that, after deleting and reinstalling the Nextcloud app, I'm not able tp reproduce the problem anymore. Thank you for looking on it.
