### ISSUE TITLE
Update search list after a file has been deleted

### ISSUE THREAD

**Issue by j-ed** [nextcloud/android#8263]
### Actual behavior
If you enter a keyword and execute a search, the result is displayed on the screen. If you now select a file and delete it, the displayed file list isn't updated and the already deleted 'ghost' file is still displayed.

### Expected behavior
If you select to delete file which has previously found using the search function, the list of displayed files should instantely been updated.

### Steps to reproduce
1. Open the Nextcloud app and use the search function to find matching files.
2. Select one of the displayed files and delete it.
-> The deleted file will still be displayed although it doesn't exist anymore.

### Environment data
Android version: 11.0
Device model: Samsung Galaxy S20
Stock or customized system: Stock ROM
Nextcloud app version: 3.16.0 RC2
Nextcloud server version: 20.0.9

**Comment by joshtrichards** [comment]
No longer applicable with Unified Search added in #7568
