### ISSUE TITLE
[3.16.0 RC2] "On the device" folder doesn't contain anything although files have been downloaded

### ISSUE THREAD

**Issue by j-ed** [nextcloud/android#8264]
### Actual behavior
If you've navigated through your folders and have opened several files, these are downloaded to the device, marked with a small check mark and then displayed on the screen. If you later want to open one of these files again and navigate to the "On the device" folder, non of these files are displayed.

### Expected behavior
Already downloaded and locally stored files should be display if the "On the device" folder is selected.

### Steps to reproduce
1. Open the Nextcloud app.
2. Select/open several files so that they're download to the device.
2. Open the "On the device" folder and check of the previously opened files are displayed.
-> The file list stays empty.

### Environment data
Android version: 11.0
Device model: Samsung Galaxy S20
Stock or customized system: Stock ROM
Nextcloud app version: 3.16.0 RC2
Nextcloud server version: 20.0.9

**Comment by tobiasKaminsky** [comment]
Can you see those files via a file explorer app?

**Comment by j-ed** [comment]
Yes, I'm able to see the downloaded files using the file explorer app. Nevertheless I decided do deinstall the Nextcloud app completely, deleted all kind of abandoned directories and reinstalled the app on my mobile phone. After that all selected files are now correctly displayed in the "On the device" folder. I don't know how the data discrepancy has been caused but now it seems to be ok again, so I will close this issue ticket. Thank you!
