### ISSUE TITLE
Server

### ISSUE THREAD

**Issue by Vinz719** [nextcloud/android#8270]
### Is your feature request related to a problem? Please describe.
You have leaving me without Server. I can not log into my files. I am not able to enter without the Server😡🤬 what's is going on with all of you? Are you stealing data just for your fun? What a kind of Technical Department are you? You are disgusting.  
I don't have copies of my data. I will go to the Police and file a Report of your App. Google has fault in this too. 
My Account has this email vinicioreinaluther77@gmail.com 

I expect you to load a server to my account. Why are you deceiving people?. I need my files. Videos and photos..you don't need them..you are just harming people. 

### Describe the solution you'd like
To have a Server like When I upload my photos to get them back.
### Describe alternatives you've considered
It keep on asking me for Server.

### Additional context

It doesn't let me.

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by jancborchardt** [comment]
@Vinz719 we do not manage accounts or data of anyone, we only write the software. If you forgot your password, try resetting it. If that does not work, contact the administrator of your server. Which link do you go to to access your Nextcloud?

**And considering the other issues and comments you posted: This is your last warning to adjust your tone to be friendly, otherwise we will ban you from the Nextcloud GitHub organization. Thanks**

**Comment by Vinz719** [comment]
Tired on the Explanation.
The Password works. But then the Server has disappeared.  So the app of
nextcloud ask me for a server.
The space is in blank.
I can get into my files. Videos and photos that are into the Cloud.

Got it?

**Comment by jancborchardt** [comment]
@Vinz719 what was the link to the server when you put it in the first time?

**Comment by Vinz719** [comment]
It Came with The App..from Google Play automatically

**Comment by Vinz719** [comment]
As any other App that you download from Google Play store. It's ready to
play.

Now when I found that it won't work ..bcz has no server and can not
open...I though to download it Again...so I uninstall the Nextcloud App And
Reinstall it after one day..but it comes without any Server AGAIN. And my
files are into it...as you know those files are important to me. Videos and
photos. 2 GB is a big ammount of photos and videos. I wish to get them
back..I have no copies. Please help

**Comment by jancborchardt** [comment]
During your first time using the app, which of these providers did you pick?
![image](https://user-images.githubusercontent.com/925062/114527280-1511d280-9c48-11eb-8a51-6ed47ce3b1f0.png)![image](https://user-images.githubusercontent.com/925062/114527312-21962b00-9c48-11eb-953a-5d4d1d0ed39e.png)

**Comment by Vinz719** [comment]
Yes, I did. Wolkli

**Comment by szaimen** [comment]
So in this case is the domain that the app asks you for probably [cloud.woelkli.com](https://cloud.woelkli.com/). Just enter this domain into the app and log in using your mail-address and the password that you've used when you initially set up your account.

**Comment by Vinz719** [comment]
Ok, I'll check it out.

**Comment by tobiasKaminsky** [comment]
closing.

**Comment by Vinz719** [comment]
Fuck you
