### ISSUE TITLE
AutoUpload using mobile data when it shouldn't

### ISSUE THREAD

**Issue by hmnd** [nextcloud/android#8273]
### Steps to reproduce
1. Enable AutoUpload, with "only on unmetered wifi enabled".
2. Disable wifi and enable mobile data on device.

### Expected behaviour
- AutoUpload doesn't upload over mobile data.

### Actual behaviour
- AutoUpload uploads over mobile data at full speed.

### Can you reproduce this problem on https://try.nextcloud.com?
N/A

### Environment data
Android version:
11, build RQ2A.210405.005
Device model: 
Google Pixel 5
Stock or customized system:
Stock
Nextcloud app version:
3.15.1
Nextcloud server version:
21.0.1
Reverse proxy:
Caddy
### Logs
Had to uninstall app because it used 700mb of mobile data in the span of a couple hours:
![Screenshot_20210412-125557~2](https://user-images.githubusercontent.com/12853597/114455303-737b7a00-9b90-11eb-9366-7c766789867a.png)

**Comment by tobiasKaminsky** [comment]
Have you disabled wifi while upload?
