### ISSUE TITLE
Crash on contact, usb debugging enabled

### ISSUE THREAD

**Issue by marscher** [nextcloud/android#8275]
### Steps to reproduce
0. USB debugging connected
1. enable daily backup of contacts
2. Force update
3. Remove cable, nextcloud crashes

### Expected behaviour
-  sync should start, abort gracefully

### Actual behaviour
- see above

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 18.1

Device model: discovery

Stock or customized system: lineage os

Nextcloud app version: 3.15.1

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat
