### ISSUE TITLE
Long filenames

### ISSUE THREAD

**Issue by mgazzin** [nextcloud/android#8281]
### Steps to reproduce
1. Use nextcloud app with a tablet
2. Keep tablet in landscape
3. You will see long filenames are truncated while most of the screen is not used

### Expected behaviour
- Dynamically adjust the length of filename displayed

### Actual behaviour
- Filename is truncated even if there is more room to display it

### Can you reproduce this problem on https://try.nextcloud.com?
- I don't see this problem with the browser. I only see it in Android app

### Environment data
Android version: 10

Device model: Lenovo P11 Pro

Stock or customized system:

Nextcloud app version: 3.15.1

Nextcloud server version: 19.0.5

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by lunarcontrol** [comment]
I installed a beta version of the nextcloud app from the Play Store and this was fixed on my tablet. The file browser uses the full width now.
3.16.0 RC2

**Comment by mgazzin** [comment]
Yes you are right @lunarcontrol .
Thanks.

**Comment by AndyScherzinger** [comment]
Let's close it then and re-open if it still happens with the release of 3.16.0 stable
