### ISSUE TITLE
Out of memory error with automatic image upload (also data loss)

### ISSUE THREAD

**Issue by MerzDaniel** [nextcloud/android#8287]
### Steps to reproduce
1. Make 5000 pictures
2. Setup automatic syncing of images for all picture folders
    - only upload with wifi and cable plugged in
    - sort images by year
    - All picture folders from the phone are synced into one phone specific target folder
    - retry on duplicates (with "replace" option, "keep existing" produced corrupted images for me)

### Expected behaviour
- Images are uploaded without limiting me in using my phone
- (the initial upload of all my images occurs in a reasonable time)

### Actual behaviour
- Main memory fully consumed by nextcloud
- => Phone is very slow to the point I sometimes have to unplug it from power supply (to stop uploading) in order to use it
- => I get continuous warnings by Android "Nextcloud does not react" which I always accept with "Wait"
- => Sometimes the app crashes due to full main memory consumption
- => I get a lot "duplicated image" errors. If I resolve them with "keep existing" I sometimes lose data (the existing image is corrupted)
- (the initial upload takes ages. The app is installed for two weeks  now but the initial images still aren't uploaded fully. On a very good day 1000 images are uploaded through wifi. But only if I have opened the app, connected to power supply and don't touch my phone. Today is a bad day and not a single image was uploaded after 2h)

It feels like Nextcloud is collecting all images for upload at once without caring about the resources. The actual upload then only processes one image at a time. I have (kinda) unlimited network by uploading through wifi but I don't have unlimited main memory so the priority of the scan should be otherway round.

The data corruption of images could be a result of an incomplete communication with the backend due to the memory issues of the app

### Environment data
Android version: 7.0

Device model: HTC One M9

Stock or customized system: Stock

Nextcloud app version: 3.15.1

Nextcloud server version: 21.0.0.18

Reverse proxy: Apache

**Comment by MerzDaniel** [comment]
************ CAUSE OF ERROR ************

java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw OutOfMemoryError; no stack trace available

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30150190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: htc
Device: htc_himauhl
Model: HTC One M9
Id: NRD90M
Product: himauhl_htc_europe

************ FIRMWARE ************
SDK: 24
Release: 7.0
Incremental: 869604.3

**Comment by MerzDaniel** [comment]
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.owncloud.android.lib.common.operations.RemoteOperationResult.isCancelled()' on a null object reference
	at com.owncloud.android.datamodel.UploadsStorageManager.updateDatabaseUploadResult(UploadsStorageManager.java:561)
	at com.owncloud.android.files.services.FileUploader.uploadFile(FileUploader.java:652)
	at com.owncloud.android.files.services.FileUploader$ServiceHandler.handleMessage(FileUploader.java:1404)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:173)
	at android.os.HandlerThread.run(HandlerThread.java:61)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30150190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: htc
Device: htc_himauhl
Model: HTC One M9
Id: NRD90M
Product: himauhl_htc_europe

************ FIRMWARE ************
SDK: 24
Release: 7.0
Incremental: 869604.3

**Comment by tobiasKaminsky** [comment]
> It feels like Nextcloud is collecting all images for upload at once without caring about the resources. The actual upload then only processes one image at a time.

Do you see all 5000 images in upload queue?

**Comment by MerzDaniel** [comment]
Yes, collecting the upload candidates works fine.

In the month since I have the app installed I got now 4000/5000 images uploaded. Since one week there is nearly no progress. 

 Additional observations (Important first): 
- the candidates are moved from upload to failed queue forth and back multiple times ("App crashed", "App was closed", ...)
- After each app crash, I have the feeling that all images get indexed again => app gets slow again and sometimes crashes again 
- upload often doesn't start, even if the requirements are met ("Waiting for upload", "Waiting for charging the phone", ...)
- I have to continuously watch the app and click on images in the upload queue in order to remind nextcloud of uploading them
- the requirements for uploading an image aren't updated even if I update the "Autoupload" configurations (I removed the phone charging requirement, but it does not show an effect)

**Comment by MerzDaniel** [comment]
After 1.5 months still not all of my images have been uploaded. Currently I'm left with more than 1000. Trying out workarounds (like recreating a file upload) is nearly impossible because the app is just frozen all of the time because of this bug

**Comment by MerzDaniel** [comment]
Also a way to get rid of open tickets for continues issues. I'm still getting errors. will there be a fix release any time soon?
