### ISSUE TITLE
 Open Office documents via MS Office Online

### ISSUE THREAD

**Issue by shaensel-ito** [nextcloud/android#8288]
It should be possible to open Office documents (doc, docx, xls, xlsx ...) via the app if MS Office Online is used as the collobaration variant.

**Comment by joshtrichards** [comment]
This requires the `officeonline` integration app to add a a direct editing api.

See nextcloud/officeonline#231

**Comment by joshtrichards** [comment]
Duplicate of nextcloud/officeonline#231
