### ISSUE TITLE
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1245708 bytes

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#831]
Happens when sending a very large (> 1Mb) log while.

Workaround: if file is > 1 mb truncate it so that it fits. 
AFAIK the newest entries are on top, therefore truncate from the end.

**Comment by mario** [comment]
Perhaps we can serve the file via content provider and that way it'll work no matter the size?

**Comment by tobiasKaminsky** [comment]
I am unsure if the file is readable as it is in /mnt/sdcard/nextcloud/log/currentLog.txt

**Comment by tobiasKaminsky** [comment]
I do not get it...I tried just a plain 
Intent intent = new Intent(Intent.ACTION_SEND_MULTIPLE);
intent.setType(MAIL_ATTACHMENT_TYPE);
startActivity(intent);

and it still gives me 
```java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 2294796 bytes```
