### ISSUE TITLE
timestamps aren't preserved when uploading (re-open)

### ISSUE THREAD

**Issue by EngelPika32** [nextcloud/android#8314]
The issue ( #7792 ) still exists and isn't solved at all. 

Nextcloud app version: 3.15.1 (from F-Droid)
Nextcloud server version: 21.0.1 (docker:fpm)

Additionally, it seems to be not a good idea to edit files on the phone as the timestamp might corrupt due to later upload (no wifi) leading to incorrect files when editing the files somewhere else again. Luckily, I have versioning enabled allowing me to merge the difference again.

\
Adding to a previously mentioned behavior which I first saw as "okay"…
> We try to read the modification time, but if this fails, the current date is used.
The question is now why does it fail.

If it fails, it fails – then it should give proper feedback to the user and not silently ignore the issue.
The user should decide whether these files should be uploaded as "newly created" (aka. ignore the issue) or not.  

\
PS: Please do not close issues like these (bugs) automatically. They aren't solved simply because nobody had time to look into them / fix them and sending a "bump" message every few weeks would be stupid and spammy.
edit.: Oh, it doesn't re-open automatically? Guess I have to open a new issue… but I'll wait for some response before doing that.

PPS: As of now, I can't root my device to gather additional log information. However, this issue doesn't seem to be "very new" when looking back. Hopefully, someone else can add more info.

_Originally posted by @EngelPika32 in https://github.com/nextcloud/android/issues/7792#issuecomment-824274994_

*Note: I waited 6 days for a re-open and/or reply before creating this new issue ;)*

**Comment by EngelPika32** [comment]
I did some more digging and I don't understand it.
First I thought, it only happens with files on the sd-card; then I thought it only happens on large files or jobs. But now I have a mix of everything, correct & incorrect files both from sd-card and both small and large.


First of all, I did not test any folders belonging to another app.
And here some stuff I did:
1. Add internal folder for auto-upload (~4MB) – okay
2. Add internal folder for auto-upload (still small) – okay
3. Add another internal folder, being the parent folder of (2) – not quite okay. It tries to re-upload all the files again [Q4] (as well some which aren't in the auto-upload right now, but exist on the server from an earlier upload). But the files are identical and the timestamps are correct (some were literally uploaded some minutes ago). It was a small pain to  "resolve" the problems/duplicates [Q1; Q2; Q3].
4. Remove auto-upload for (2).
5. Open Filemanager and try the share to nextcloud dialog for some files (4 small images to be certain; sd-card). I chose a totally different folder on the server, which isn't related to any auto-upload nor sync. – All timestamps are corrupt.
6. Add sd-card folder for auto-upload (164MB; a bunch of very small images and 4 vids; 78 files in total) – the images are fine and kept unexpectedly their timestamps, but all the videos have incorrect timestamps (smallest 5,9MB, largest 90,4MB)[Q5].
7. Add the folder with the images from (5) as auto-upload as well (upload to different, empty folder) – timestamps are correct (?).

Conclusion: 
(1)(2)(7) worked as expected / as it should be.
(3) had some issues but the files aren't corrupt.
(4) doesn't change files.
(5)(6) caused file corruption (incorrect timestamps/metadata).

(1)(2)(3)(4) were on the internal storage
(5)(6)(7) were on the sd-card

Hint: "small images" mean under 1MB per image
Hint2: Whenever I'm auto-uploading, I'm reconstructing the folder structure on the server for convenience. Idk, if this matters in any way. The only exception here was (5), as this was a manual upload.
Hint3: I always waited for the files to complete / uploads being finished between the steps →(4) was done after (3) completed (including problem-resolving).

Q1: Why isn't there an option to select multiple files or a folder to resolve the same way?
Q2: After resolving a few of the files, the app simply stuck completely as it tried every failed file again. (why? It's been like 5 sec since you last tried!?)
Q3: Why isn't this recognized? The checksums are identical, timestamps as well. It shouldn't ignore this, but there should be an option to select what to do in such a case. 
When I'm replacing the file on the server, it uploads it again (correct), when I choose to keep the server file, it downloads it (correct as well). But I can't select: "Files are the same, keep as it and link them/recognize them like this." [May I create a new issue for this?]
Q4: Missing option to change auto-upload to a parent directory, as the duplicated auto-upload wasn't recognized. Unfortunately, when selecting folders for auto-upload (local), there aren't any icons or such to identify already added folders. Handling duplicated auto-upload paths/entries would be preferred.
Q5: Is there something special for large files, ex. caching in between?

Reference-Note: It still might be smth. mentioned earlier by @johannestophoj :
> Could this be due to some caching that only happens for large jobs - and that the copy to the cache does not preserve the time stamps?

**Comment by AndyScherzinger** [comment]
@EngelPika32 what happens for images >1MB and are you uploading on cellular or wifi? Cellular has a chunk size of 1MB and wifi 10;B so files larger than 1MB/10MB are uploaded in chunks and put together by the server when all parts have been transferred.

**Comment by tobiasKaminsky** [comment]
Please split this up and follow the bug template, otherwise this cannot be reproduced.

**Comment by EngelPika32** [comment]
@AndyScherzinger 
> cellular or wifi

wifi only, cellular would take hours.

> what happens for images >1MB

I suppose, you mean when on the sd-card.

8. Add sd-card folder for auto-upload (images only; 115MB; smallest 141KB, largest 42,5MB; but most were around 1-3MB; 25 files total) – files smaller than 1MB have the correct timestamp, files larger than 1MB are incorrect, see image.
![image](https://user-images.githubusercontent.com/41995155/116412070-99627900-a836-11eb-9829-fbe7c67e7f99.png)

**Comment by EngelPika32** [comment]
@tobiasKaminsky I'm not quite sure which "split" you mean. Have you even read my messages?
The whole issue is about incorrect timestamps. I just described in detail what happened and what I noticed during this. I even asked for Q3 whether I should create a separate issue for this. 

Please don't close this issue but refer to which part of this issue should move into a new one (ex. Q3, Q4?), so this one can focus on the timestamps further 

> follow the bug template

Additionally, please keep in mind, this is a follow-up issue of a falsely closen issue. 
If you prefer, I can copy the information from there and edit the first message of this ("new") issue.

**Comment by EngelPika32** [comment]
Please re-open this ticket as it's falsely closed and I haven't got an answer about what I should "split up". 

I'll give you 2 more days. If there is no reply I'll simply create a ticket for Q1, Q2, Q3, Q4, and Q5 + the original ticket as I truly have no idea what @tobiasKaminsky s problem is :unamused:  (the first ticket follows the bug template and explains everything. This is, after all, a re-open with continued conversation. And I offered to edit the first message here formerly). 

Additionally, I'd create a ticket about the bad behavior with obvious bugs (aiming against the bot which originally closed the ticket "due to inactivity"; bugs aren't soölved because nobody had time to look at them!).
