### ISSUE TITLE
Webview: obey self-signed cert

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#8322]
### Steps to reproduce
1. have a server with self signed cert
2. accept it during login
3. try to online edit a text file
-> breaks due to self signed cert
(from https://github.com/nextcloud/text/issues/742)

### Expected behaviour
- Should work as cert already was accepted

### Actual behaviour
- just hangs

**Comment by mathmaniac43** [comment]
Just set up NextCloud server newest and have this same problem. I have created my own certificate authority and installed the root public certificate on all of my devices including my Android 9 phone. Connecting to the server was seamless, and I can download and create files, buy I cannot edit them within the NextCloud app.

**Comment by binarious** [comment]
Wouldn't [overwriting `onReceivedSslError` of `WebView` and adding a prompt](https://stackoverflow.com/a/38389276/782746) be a solution?

**Comment by joshtrichards** [comment]
Fixed in #9881
