### ISSUE TITLE
swiping down in «on the device» view does not synchnonize, only refreshes part of existing data, and only from server to device

### ISSUE THREAD

**Issue by hobbes** [nextcloud/android#8324]
### Steps to reproduce
1. synchronize a directory tree with your device
2. go to the «on the device» view
3. enter any directory and make modifications
4. swipe down

### Expected behaviour
- it should synchronize any modification both ways for the whole current tree

### Actual behaviour
- it refreshes part of what has been modified on the server: no new directories, no new files, no synchronization from device to server (modified files on the device). Only existing files that have been modified on the server are updated on the device.

### Can you reproduce this problem on https://try.nextcloud.com?
yep

### Environment data
Android version: 10 (LOS 17.1 and Samsung Stock)

Device model: oneplus3, samsing s6 lite, samsung s7

Stock or customized system: samsung stock and LOS

Nextcloud app version: 3.15.1

Nextcloud server version: 20.0.7, 21.0.1, try.nextcloud.com

Reverse proxy: haproxy and apache

### Logs
I don't think that they are relevant here, but don't hesitate to ask if you feel that they are

**Comment by tobiasKaminsky** [comment]
>     * it should synchronize any modification both ways for the whole current tree

That is not what it should to. Expected behaviour is to update file list.
If you want to sync a folder, you have to click on three dots next to it and set sync.

On device is a narrowed down view of all files/folders, but does only show those file/folders that are not already downloaded.

**Comment by hobbes** [comment]
ok maybe not the whole tree, that was my expectation but I can understand that it's too wide. 

But most users here did expect that it synchronize the current directory both ways: new and modified files would be synchronized to and from the server. 

For example any mail application does that when you swipe down the list of messages: it completely synchronizes the list, not only the new messages from the server.

**Comment by hobbes** [comment]
@tobiasKaminsky I don't know if you receive notifications for new comments on closed issues, and I can't reopen the issue to discuss it, so I mention you, just in case. Sorry for the noise if you did receive the notification.
