### ISSUE TITLE
Timestamp of activity looks strange

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#8332]
- open up activity stream
- see ![2021-04-30-111134](https://user-images.githubusercontent.com/5836855/116674415-e8c6b780-a9a4-11eb-9ad3-3a570a049731.png)

@AndyScherzinger I fiddled around a bit with xml, but all layout_width are "match_parent".

I am a bit clueless…

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky see #8340 with the fix, the inflate call should be handing over the parent view, else th e"match_parent" can't be calculated correctly :)
