### ISSUE TITLE
Moving files crash app

### ISSUE THREAD

**Issue by computersalat** [nextcloud/android#8341]
### Steps to reproduce
1. Select files 
2. Move to different fokder
3. Wait for crash 

### Expected behaviour
- app should not crash. Instead files should be moved

### Actual behaviour
- app did not move any file, just crashed after 

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum
So you expect me to upload private data (pictures and movies) to public cloud? 
Sorry, but no. 

### Environment data
Android version: 10

Device model: OnePlus6 

Stock or customized system: Stock

Nextcloud app version: current 

Nextcloud server version:

Reverse proxy: none

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat
