### ISSUE TITLE
backups with nextcloud + seedvault are very slow and use a lot of cpu on the client + server

### ISSUE THREAD

**Issue by abma** [nextcloud/android#8347]
### Steps to reproduce
1.  use lineageos
2.  install + configure the nextcloud client
3.  configure seedvault

### Expected behaviour
- it just works nice + fast with low cpu load on server + client. only the progress bar of the backup is shown. as very few data is sent, the backup should take ~1 minute.

- no notifications of uploads should be shown, the backup progress bar is enough.
- no activities of files of backups are shown

### Actual behaviour
- when the backup starts, the mobile cpu load is high (top shows ~1 core is used) and the nextcloud server uses a lot of cpu, too. notifications of uploads are spammed. in activities ~30 changes are per minute which basicly contains no information. the backup takes ~20 minutes.

### Environment data
Android version: lineageos 18.1

Device model: enchilada

Nextcloud app version: 3.15.1

Nextcloud server version: 20.0.9

Reverse proxy: -

it should be possible to disable upload notifications in the client app and activities on the server side: it contains no value data for me and IMHO it really makes things slow and annoying. showing error notifications is fine.

i'm pretty sure this heavily slows down backups as A LOT of tiny files are uploaded.

**Comment by tobiasKaminsky** [comment]
@grote apart from notification, do you have any enhancement idea? :-)

**Comment by grote** [comment]
There's #8290 which might improve things a bit.

Maybe Nextcloud is used with client-side encryption which would cause high CPU load because of double encryption? Maybe the phone used doesn't support hardware acceleration for the crypto primitives used?

The backup has lots of small files which have a high overhead and make the upload slow.
