### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by logicos94** [nextcloud/android#835]
### Actual behaviour
I can't upload any documents from my Android phone to Nextcloud server.

### Expected behaviour
Android app entering in infinte loop.
Nginx log show infinite "HEAD" request with numbered file name.
 
### Steps to reproduce
1. Install Nextcloud 11.0.2 + Debian Jessie + Nginx
2. Install App Android 
3. Try to upload any document from App Android to Nextcloud server.

### Environment data
Android version: 7.0

Device model: SM-G930F

Stock or customized system: Stock?

Nextcloud app version: 1.4.2

Nextcloud server version: 11.0.2

### Logs
?
#### Web server error log

<IP ADDRESS> - thierry [17/Apr/2017:01:10:01 +0200] "HEAD /remote.php/webdav/Yoi/ HTTP/1.0" 200 0 "-" "Mozilla/5.0 (Android) ownCloud-android/1.4.2"
<IP ADDRESS> - thierry [17/Apr/2017:01:10:01 +0200] "HEAD /remote.php/webdav/Yoi/20170416_221047.jpg HTTP/1.0" 200 0 "-" "Mozilla/5.0 (Android) ownCloud-android/1.4.2"
<IP ADDRESS> - thierry [17/Apr/2017:01:10:02 +0200] "HEAD /remote.php/webdav/Yoi/20170416_221047%20(2).jpg HTTP/1.0" 200 0 "-" "Mozilla/5.0 (Android) ownCloud-android/1.4.2"
<IP ADDRESS> - thierry [17/Apr/2017:01:10:02 +0200] "HEAD /remote.php/webdav/Yoi/20170416_221047%20(3).jpg HTTP/1.0" 200 0 "-" "Mozilla/5.0 (Android) ownCloud-android/1.4.2"
<IP ADDRESS> - thierry [17/Apr/2017:01:10:02 +0200] "HEAD /remote.php/webdav/Yoi/20170416_221047%20(4).jpg HTTP/1.0" 200 0 "-" "Mozilla/5.0 (Android) ownCloud-android/1.4.2"
<IP ADDRESS> - thierry [17/Apr/2017:01:10:03 +0200] "HEAD /remote.php/webdav/Yoi/20170416_221047%20(5).jpg HTTP/1.0" 200 0 "-" "Mozilla/5.0 (Android) ownCloud-android/1.4.2"
<IP ADDRESS> - thierry [17/Apr/2017:01:10:03 +0200] "HEAD /remote.php/webdav/Yoi/20170416_221047%20(6).jpg HTTP/1.0" 200 0 "-" "Mozilla/5.0 (Android) ownCloud-android/1.4.2"
<IP ADDRESS> - thierry [17/Apr/2017:01:10:04 +0200] "HEAD /remote.php/webdav/Yoi/20170416_221047%20(7).jpg HTTP/1.0" 200 0 "-" "Mozilla/5.0 (Android) ownCloud-android/1.4.2"
<IP ADDRESS> - thierry [17/Apr/2017:01:10:04 +0200] "HEAD /remote.php/webdav/Yoi/20170416_221047%20(8).jpg HTTP/1.0" 200 0 "-" "Mozilla/5.0 (Android) ownCloud-android/1.4.2"
<IP ADDRESS> - thierry [17/Apr/2017:01:10:04 +0200] "HEAD /remote.php/webdav/Yoi/20170416_221047%20(9).jpg HTTP/1.0" 200 0 "-" "Mozilla/5.0 (Android) ownCloud-android/1.4.2"
<IP ADDRESS> - thierry [17/Apr/2017:01:10:05 +0200] "HEAD /remote.php/webdav/Yoi/20170416_221047%20(10).jpg HTTP/1.0" 200 0 "-" "Mozilla/5.0 (Android) ownCloud-android/1.4.2"
<IP ADDRESS> - thierry [17/Apr/2017:01:10:05 +0200] "HEAD /remote.php/webdav/Yoi/20170416_221047%20(11).jpg HTTP/1.0" 200 0 "-" "Mozilla/5.0 (Android) ownCloud-android/1.4.2"
<IP ADDRESS> - thierry [17/Apr/2017:01:10:06 +0200] "HEAD /remote.php/webdav/Yoi/20170416_221047%20(12).jpg HTTP/1.0" 200 0 "-" "Mozilla/5.0 (Android) ownCloud-android/1.4.2"
<IP ADDRESS> - thierry [17/Apr/2017:01:10:06 +0200] "HEAD /remote.php/webdav/Yoi/20170416_221047%20(13).jpg HTTP/1.0" 200 0 "-" "Mozilla/5.0 (Android) ownCloud-android/1.4.2"
<IP ADDRESS> - thierry [17/Apr/2017:01:10:06 +0200] "HEAD /remote.php/webdav/Yoi/20170416_221047%20(14).jpg HTTP/1.0" 200 0 "-" "Mozilla/5.0 (Android) ownCloud-android/1.4.2"
<IP ADDRESS> - thierry [17/Apr/2017:01:10:07 +0200] "HEAD /remote.php/webdav/Yoi/20170416_221047%20(15).jpg HTTP/1.0" 200 0 "-" "Mozilla/5.0 (Android) ownCloud-android/1.4.2"
<IP ADDRESS> - thierry [17/Apr/2017:01:10:07 +0200] "HEAD /remote.php/webdav/Yoi/20170416_221047%20(16).jpg HTTP/1.0" 200 0 "-" "Mozilla/5.0 (Android) ownCloud-android/1.4.2"
<IP ADDRESS> - thierry [17/Apr/2017:01:10:07 +0200] "HEAD /remote.php/webdav/Yoi/20170416_221047%20(17).jpg HTTP/1.0" 200 0 "-" "Mozilla/5.0 (Android) ownCloud-android/1.4.2"
<IP ADDRESS> - thierry [17/Apr/2017:01:10:08 +0200] "HEAD /remote.php/webdav/Yoi/20170416_221047%20(18).jpg HTTP/1.0" 200 0 "-" "Mozilla/5.0 (Android) ownCloud-android/1.4.2"
...

#### Nextcloud log (data/nextcloud.log)

None related.
```

I must kill Android App to stop log flooding.

Regards

**Comment by tobiasKaminsky** [comment]
Can you test this with the demo cloud on demo.nextcloud.com?
This way we can limit the problem to either your device or the server.

**Comment by logicos94** [comment]
I have no issue with demo.nextcloud.com .
I will check (again) the installation of my server.
Thank's for your support.

**Comment by tobiasKaminsky** [comment]
If you need assistance just reply here and we are trying to help yo.
