### ISSUE TITLE
Error creating conflict window

### ISSUE THREAD

**Issue by cjdg** [nextcloud/android#8354]
### Steps to reproduce
1. Wait until a sync conflict appears
2. touch notification
3. Error on creating conflict window

### Expected behaviour
- It should open conflict window
- 
### Actual behaviour
- Application crases
-

### Environment data
Android version: 10

Device model: Moto G9 Plus

Stock or customized system:

Nextcloud app version:3.15.1

Nextcloud server version:19

**Comment by tobiasKaminsky** [comment]
Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

**Comment by droogi** [comment]
same error with nextcloud app 3.16.0 and 21.0.1, i have no root on my device..

**Comment by hunggioi** [comment]
same error with nextcloud app 3.15.1 .Looking forward to help

**Comment by cjdg** [comment]
> Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

there iis a big issue, unfortunally my mobile can only charge via usb, there is any other way we can debug?

**Comment by desigi** [comment]
> 
> 
> Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

I'm also experiencing the same issue. My specs are:

Android version: 10
Device model: Pixel 4a
Stock or customized system: Stock
Nextcloud app version: 3.16
Nextcloud server version: 21.0.1

Here is my logcat 
[logcatOutput.txt](https://github.com/nextcloud/android/files/6476041/logcatOutput.txt)
