### ISSUE TITLE
Current version not available in F-Droid Store

### ISSUE THREAD

**Issue by Krawei** [nextcloud/android#8361]
Dear team,

when I take a look on google play store the current version is 3.16.0 in the F-Droid store the current version is 3.15.1.

What's the reason for this gap? Is there a bug in the build process?

Please fix this.

Kind Regards,

Krawei

### Steps to reproduce
1.  Open F- Droid and check NC's Version
2. Open Play Store and check NC's Version
3. Check Release Notes and compare their versions

### Expected behaviour
- No differ versions

### Actual behaviour
- Different version numbers

### Environment data
Android version: Android 10, Patchlevel April 2021

Device model:  Realme 7 Pro

Stock or customized system: ColorOS v7

Nextcloud app version: 4.15.0

**Comment by AndyScherzinger** [comment]
As always stated f-droid builds and publishes the app themselves, there is absolutely nothing we can do on out side, see https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8919 has been merged by the f-droid team, so they "just" need to publish...
