### ISSUE TITLE
When multiple notifications are shown only the latest triggered can be displayed

### ISSUE THREAD

**Issue by af7567** [nextcloud/android#8363]
I originally opened the issue here https://github.com/stefan-niedermann/nextcloud-deck/issues/952 as a Deck app bug, but it seems to happen for all nextcloud android app notifications.

When multiple notifications which are to be opened in the same activity are shown, only one of these notifications can be tapped on to open it. The others will just disappear without doing anything when tapped.

### Steps to reproduce
1. Have multiple notifications displayed
2. Tap one to display it then close the activity
3. Tap another notification

### Expected behaviour
- Each notification should open up the app it was meant to

### Actual behaviour
- Nothing happens after the first one is opened.

If the notifications are to be handled by different apps, then it seems to work OK. For example you have 1 notification about a nextcloud server update, and another one about a Deck card due date (and you have the android Deck app installed). Tapping the update one will open in the nextcloud app and then tapping the Deck one will open in the Deck app.

**Comment by af7567** [comment]
I have had a look at why this is happening and it seems to be because the requestcode used for the PendingIntent is always 0, in both the Deck integration code and the default app notification handler. 

https://github.com/nextcloud/android/blob/33a70e53e7e1d83302e27db306460a83fcc906f9/src/main/java/com/nextcloud/client/integrations/deck/DeckApiImpl.java#L79
and
https://github.com/nextcloud/android/blob/33a70e53e7e1d83302e27db306460a83fcc906f9/src/main/java/com/nextcloud/client/jobs/NotificationWork.kt#L159

I tried changing the requestcode from 0 to notification.getNotificationId() in the Deck notification handler and that seems to work OK. I guess it should also work for the default notification hander too.

**Comment by joshtrichards** [comment]
Fixed in #8365 (but inadvertently left open here; closing).
