### ISSUE TITLE
Password reset issue 

### ISSUE THREAD

**Issue by deep0808** [nextcloud/android#8371]
I'm sorry for opening this issue but I had to because I wanted to access my nextcloud account which I created one year ago but I didn't used for several months. And now it doesn't recognise my credential i don't even received an email after an hour of password reset request. Please help I many important documents in there🙏 Here the screenshots👇
![403b152c-c922-49f7-bb27-f2c59f0a04fa.jpg](https://user-images.githubusercontent.com/81495925/117554382-8e3df300-b057-11eb-80fc-43da52704bf9.jpg)
![a1908810-c95c-4ecb-8032-a36c3a9897f3.jpg](https://user-images.githubusercontent.com/81495925/117554392-95fd9780-b057-11eb-9d83-d334a33675ec.jpg)

**Comment by tobiasKaminsky** [comment]
We, at Nextcloud, only provide source code / app, but do not offer hosting.
This seems to be webo.hosting, so please contact them.
