### ISSUE TITLE
Android client upload speed slow than web！

### ISSUE THREAD

**Issue by sirliu** [nextcloud/android#8372]
When uploading a single large file under the same network environment and configuration, the upload speed of the Android client is less than 8M/s, and the upload speed of the web client is 28+M/s.
And, I found that when `Filerun` uploads the same file, the CPU and memory consumption is almost zero, while the CPU of `NextCloud` is almost full , and the memory consumption is also obvious(both applications are run by docker).

**Comment by NaXal** [comment]
Hello,

I am using NextCloud (Ubuntu / Snap install) for a home server project and I am facing the same issue.

- Clean and up to date installation of Ubuntu 20.04 LTS Server
- NextCloud Installation done via Snap
- Checked with both, self signed and my own domain SSL Certificate
- Server (running in a Laptop) Spec (Intel Pentium Quad Core N3530 / 4GB DDR3 / 500GB HDD)
- Network -> Tenda / TP -Link Dual Band Gigabit Port Router connected to Server using 1000mbps Ethernet link
- Client -> Tested with Multiple Android 12 and 11 devices with 5Ghz WiFi

Issue is as described by OP, NextCloud Android app is painfully slow (10 MBits) to upload where as from the same phone, if I use browser, the upload speeds are like 20 times better and getting 200+ MBits

All configurations are untouched and as default at the time of snap installation.

Thanks.

**Comment by mark-jiang-1470** [comment]
I think it's because it's uploading files one by one
