### ISSUE TITLE
Invalid query (syntax error?) when asking for files_sharing/api/v1/shares

### ISSUE THREAD

**Issue by fs1** [nextcloud/android#8382]
### Steps to reproduce
1. install nextcloud app
2. whenever I open the app it produces an error in the webserver log

### Expected behaviour
- no errors in server log

### Actual behaviour
- I see a lot of 404 errors in my webserver log like this one: `0.0.0.0 - - [11/May/2021:23:23:44 +0200] "GET /nextcloud/ocs/v2.php/apps/files_sharing/api/v1/shares?path=%2F&reshares=true&subfiles=true HTTP/1.1" 404 286 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.16.0" 80839`

### Can you reproduce this problem on https://try.nextcloud.com?
- No since I have no access to the webserver log

### Environment data
Android version: 9

Device model: Umidigi F1

Nextcloud app version: 3.16.0

Nextcloud server version: 21.0.1
files_sharing version: 1.13.1

#### Web server error log
`0.0.0.0 - - [11/May/2021:23:23:44 +0200] "GET /nextcloud/ocs/v2.php/apps/files_sharing/api/v1/shares?path=%2F&reshares=true&subfiles=true HTTP/1.1" 404 286 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.16.0" 80839`

If I try to call this URL on a command line (using curl), I get the same result:
`192.168.2.2 - - [11/May/2021:23:24:17 +0200] "GET /nextcloud/ocs/v2.php/apps/files_sharing/api/v1/shares?path=%2F&reshares=true&subfiles=true HTTP/2.0" 404 286 "-" "curl/7.64.0" 91643`

But this way I see a reason for this error:
```
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>failure</status>
  <statuscode>404</statuscode>
  <message>Invalid query, please check the syntax. API specifications are here: http://www.freedesktop.org/wiki/Specifications/open-collaboration-services.
</message>
 </meta>
 <data/>
</ocs>
```

#### Nextcloud log (data/nextcloud.log)
empty

Please also have a look at https://github.com/nextcloud/desktop/issues/3306, as it's pretty the same.

**Comment by tobiasKaminsky** [comment]
Please ask at server, as if this happens with curl it is not related to Android.
I tested it also locally and it works.
