### ISSUE TITLE
file upload conflict

### ISSUE THREAD

**Issue by DuganFairview** [nextcloud/android#8383]
### Steps to reproduce
1. Move files into instant upload folder
2. Resolve 47 file upload conflicts
3. Repeat 47 times
4. Ask for help

### Expected behaviour
- Tell us what should happen
     When I resolve the conflict, I expect to be done with it
### Actual behaviour
- Tell us what happens
   I resolve the conflicts, resolve the conflicts, resolve the conflicts. But conflicts are never resolved
### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:
11
Device model: 
Pixel 3a xl
Stock or customized system:
Googles one and only
Nextcloud app version:
It's been updated monthly
Nextcloud server version:
Who knows
Reverse proxy:
What? Who?
#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
@DuganFairview just for clarification: You "expect" when you have 47 conflicts due to 47 files that when you choose a resolving strategy it be aplies to the other 46 files?

**Comment by DuganFairview** [comment]
I "expect" when I resolve 47 file conflicts (47 times) they are resolved and I don't have to repeat 47 resolutions time after time for months

May 12, 2021 06:30:04 Andy Scherzinger ***@***.***>:

**Comment by AndyScherzinger** [comment]
> I "expect" when I resolve 47 file conflicts (47 times) they are resolved and I don't have to repeat 47 resolutions time after time for months

Thanks for the clarification and yes, makes absolute sense 👍

**Comment by DuganFairview** [comment]
You got me thinking... about file type. All these conflicts are images, (I'll double check that statement) many of which have been 'tweaked' by google photos either for cropping, color filter etc (occasional mp4's are not tweaked). G.photos claims these are reversible to the original--but I rarely reverse photo tweaks. Many of the new file's (not all) have been given a creation date of 12/31/1969. This time around I'm trying the option of "save both". The sun will still rise tomorrow if I have some duplicate files, but after creating 40,000+ duplicate photos I try diligently to squash duplicates.

May 12, 2021 06:58:49 Andy Scherzinger ***@***.***>:

**Comment by tobiasKaminsky** [comment]
If the file is changed, then it will be detected as "new" again, so in this case it is correct.
As the new and old file have the same file name, it then asks you for resolving the conflict.

**Comment by DuganFairview** [comment]
Thanks Tobias. What is it detecting? The file size? With 67,000 photos, I guess NextCloud won't work. I'll spare you my grudge with Google, Apple and Adobe Photoshop. They deliberately snare people in their mess.

May 17, 2021 23:21:04 Tobias Kaminsky ***@***.***>:
