### ISSUE TITLE
Autoupload Images are continuously moved forth and back from failed queue. Is there a known workaround?

### ISSUE THREAD

**Issue by MerzDaniel** [nextcloud/android#8388]
I have big troubles with the autoupload of images (see #8287 ).

Now I'm left with more than 1000 pictures that just cannot be uploaded since weeks. They always are moved to the failed queue because of "duplicated image". Then after some time they get picked up again by the upload only to be moved to the failed queue again

All my autouploads are configured with "on conflict/duplicate reupload" (because the other option caused data loss). But this doesn't seem to be applied. 

Is there any known Workaround that could make this work? 
Is this related to a bug that is already fixed in source code and I need to compile my own fixed version of the app?

**Comment by tobiasKaminsky** [comment]
Do you move those files once the upload is done?

**Comment by MerzDaniel** [comment]
No, I'm just still waiting for the initial set of images to be uploaded. I haven't done any changes to the images on my phone. My plan was to setup Nextcloud, let the images upload and then delete the old images. But I'm still waiting for step 2 ^^

New images seem to be processed correctly. So although I have these 1300 images that continuously fail to upload, from time to time new images get uploaded (only new ones). I have the feeling that these "uploadCandidates" are in some corrupt state in the app. Probably this could be fixed by recreating the autoupload for my image folders. But this I'd only try as last resort, because this will cause me out of memory errors for the next month again...

Do you have any suggestion what I could try to get these uploaded?

**Comment by MerzDaniel** [comment]
Maybe nextcloud moved these images... In the beginning I had the "onConflict" option set to Keep existing (which for some reason deletes the local image and downloads the remote one)
