### ISSUE TITLE
InstantUpload: obey acccount

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#839]
When enabling instant upload on account a, it should always upload files to account a, whether account a or b is currently in use.

**Comment by tobiasKaminsky** [comment]
@mario Can we replace InstantUpload on all android versions (back to SDK14)?
Then we can close this as it is working already in AutoUpload.

**Comment by mario** [comment]
@tobiasKaminsky yes, this will be done for 1.5
