### ISSUE TITLE
App's external conncetions list

### ISSUE THREAD

**Issue by forofo** [nextcloud/android#8391]
Nextcloud for android 3.15.1 fails to load when setting iptables restriction to allow only the IP cloud destination server.

Why it happens?

I cannot find in the documentation the requeriments for third servers communications.

**Comment by ezaquarii** [comment]
Do you run `iptables` on your Android phone?
Can you describe your setup?

There is very little anybody can do to help you without understanding your setup.

**Comment by forofo** [comment]
I have AfWall and a common iptables option to restrict Nextcloud communication only with the IP server. And it doesn't work.   

Thanks so much. Not my intention, I don't expect support to configure my phone. Just I expect an answer to know where is the problem

Please, just tell me if NextCloud for Android needs connection with third servers to work.

thanks!

**Comment by AndyScherzinger** [comment]
@forofo are you using the f-droid or the Google Play release?

**Comment by forofo** [comment]
F-droid release

**Comment by forofo** [comment]
connection is established but when I try move inside the app (navigation inside folders, etc) the spinning wheel never ends and nothing happens. Perhpaps some JS routines or similiar are needing third servers connection or similar?

**Comment by AndyScherzinger** [comment]
Of you navigate within the application then it is simply dav and json calls over http(s). JS is just for the login flow which is web based.
Does your afwall give you any info on blocked requests?

**Comment by forofo** [comment]
no, no info on blocked requests. Although when I disable the restriction all works normally again. 
Do you mean NextCloud don't do requests to third servers?.   Just I need this simple answer but still nobody answer in a simple way.

Thank you so much for your help. Although I pray you a clear answer in order to discard other causes because I cannot send my phone in an attachment.  

NextCloud do requests to third servers to work?.

**Comment by AndyScherzinger** [comment]
To answer in a simple way, no the app doesn't call any other server(s).

**Comment by forofo** [comment]
thanks!. Then it can be another reason. 

If you want to reproduce the issue, install AfWall then apply rules in custom script rules, for allow and restrict by means the app user ID belonging to Nextcloud (10030 or similar). I.e: 

`iptables -A OUTPUT -p tcp -m tcp -d server.com --dport 443 -m owner --uid-owner (APPuserID) -j ACCEPT`

**Comment by tobiasKaminsky** [comment]
> thanks!. Then it can be another reason.

Would be interesting if you can tell us what it is, once you found it.
Meanwhile closing it :)
