### ISSUE TITLE
Data Messed Up

### ISSUE THREAD

**Issue by muellert** [nextcloud/android#8392]
### Steps to reproduce
1. I don't really know - it started somewhere in between, and I just noticed today.
2. 
3. 

### Expected behaviour

When I configure auto upload, I expect the data set on my phone to be synced to my Nextcloud server once.
If there is a conflict, then the configured action (rename or overwrite) should occur. After that, new data on my phone (photos, calendar entries) should incrementally be uploaded to my Nextcloud server.

### Actual behaviour

For some odd reason, my photos are strewn over a gazillion of folders on my phone (why? I have no idea). I configured that files should be renamed on conflict. But that should still be a single-shot operation. Instead, Nextcloud repeatedly walks through all my data and then "updates" photos or other files, which are sometimes years old, but now has also stopped uploading new photos, or uploads them to places where I can't seem to find them. Searching by date does not help, since the dates are constantly being messed up by this process. Now I am afraid that I will lose data, due to Nextcloud overwriting them. 

I've just checked, and my phone has a gazillion "uploads" of age-old data going on, that it is very hard to track what it is really doing. Incidentally, Nextcloud is also the one app on my phone that eats the most battery by far (15% or more), although, given the actual changes it should sync, battery usage should be more like <1%.

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

No - I can't imagine configuring your Nextcloud server on my phone and then uploading gigabytes of photos to it.

### Environment data
Android version: 11

Device model: IN2020

Stock or customized system: I run LineageOS.

Reverse proxy: nginx

I am running Nextcloud for Android 3.15.1 and  20.0.8.1 on the server.

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
> For some odd reason, my photos are strewn over a gazillion of folders on my phone (why? I have no idea).

Can you give us some examples?
