### ISSUE TITLE
Ability to disable transfers (auto uploads/etc) temporarily

### ISSUE THREAD

**Issue by muellert** [nextcloud/android#8393]
### Is your feature request related to a problem? Please describe.

Sometimes, when I am not sure things are working well, or when I would like to re-organize stuff, I would like to have an "emergency sync stop" for the entire app, so I can then just switch syncing off for a device, then turn it back on later.

Currently, the sync settings are scattered across more than 20 individual folders/items, which makes it very tedious to get things into order.

### Describe the solution you'd like

I would like to have a button that would allow me to turn syncing for everything on and off, preferably directly in the hamburger menu.

### Describe alternatives you've considered

None.

### Additional context
n/a

**Comment by joshtrichards** [comment]
Let's consolidate this into #383.
I encourage you to subscribe to that issue for tracking and/or to upvote :+1: it.
