### ISSUE TITLE
Raise CHUNK_SIZEs

### ISSUE THREAD

**Issue by szaimen** [nextcloud/android#8398]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
The default chunk size of 1MB for mobile networks and 10MB for WIFI networks are much too low for current file sizes.
Please consider to change it to 10MB or 100MB, respictively.

**Describe the solution you'd like**
I am sure that this will tremendously speed up the file sync process and will prevent/fix issues like #5609

**Describe alternatives you've considered**
Maybe change it to 100MB/1000MB but thats probably already too much.

**Comment by ne20002** [comment]
I disagree. Chunk size is more about connection stability than file size.
I have a friend in India and there connections are mostly instable (mobile) so uploads are often interruppted (even with 5M files it usually needs multiple tries).

Would it be a idea to set up a chunk upload API v2 with something like this:

- chunk size by 50MB
- resume of interruppted chunk upload by using rsync mechanism

That way there would be less waste of transfer and 50MB chunks would keep rsync overhead (extra transfer and cpu) at a minimum.

**Comment by tobiasKaminsky** [comment]
There might be room to improve the chunk size, but currently I fail to understand the idea.


> The default chunk size of 1MB for mobile networks and 10MB for WIFI networks are much too low for current file sizes.

Why do you think this?



> I am sure that this will tremendously speed up the file sync process and will prevent/fix issues like #5609

Why are you so sure about this?
As far as I understand the problem, this is about assembling the file.
So if you want to upload a 1 Gb file, it will now be split into 10Mb chunks, so there is 103 chunks.
If you would use 50mb chunks, it would be 21 chunks.

But this is not the problem, as the file size is the same. The problem is to concatenate all 1gb into one file, which is on some server just too slow (maybe due to io of hdd) and thus this takes longer than 60s and thus it times out.

**Comment by ne20002** [comment]
May I suggest the following:

As far as I see, the chunks are (single) files uploaded by and under the control of the client. The client sets the byte offesets in the filenames and marks a chunk as uploaded if the upload succeeded. Thus, if a chunk is interrupted, only a part of the chunk is stored on the server, but the client will retry the complete chunk from its beginning. The more interruptions occure, the more upload data volume is wasted.

Looking at the API for the chunked upload, a small addition may increase upload stability and reduce waste of data volume. This would be another API method for the following:

If the last chunk upload did not succeed, call a method in the API requesting the server, to correct the byte offset of the chunk to the actual size of the chunk and return that value to the client, so it can start the next chunk on this postition.

Something like this:

1: first chunk uploaded:   file_00000-00100.tmp, size is 100
2: second chunk uploaded:   file_00101-00200.tmp, size ist 100
3. third chunk is interrupted:   file_00201-00300.tmp, but filesize is 44

4. When client resumes, it asks the server for the actual size and correcting of the last chunk (client knows it is file_00201-00300.tmp). The server renames the file file_00201-00300.tmp to file_00201-00245.tmp and returns the 44 as size of the chunk or 00245 as end point of the chunk.

Client sends next chunk as file_00246_00300.tmp to complete the former interrupted upload.

5. Client resumes with 'normal' chunks, next would be file_00301-00400.tmp.

This can be achieved by

- adding the mentioned method without changing anything on the current API, so the previous way with retrying the complete chunk will still work.
- The server must simply be able to concat the files based on the byte offsets in the filenames. I think, this is already the case.

With this approach, chunk size wouldn't really matter so much.

**Comment by ezaquarii** [comment]
@tobiasKaminsky 
> As far as I understand the problem, this is about assembling the file.
> So if you want to upload a 1 Gb file, it will now be split into 10Mb chunks, so there is 103 chunks.
> If you would use 50mb chunks, it would be 21 chunks.

Unless the number of files in the directory is ridiculous or chunks are microscopic, chunk size doesn't matter when concatenating the files, as `open()/close()/mmap()` overhead is negligible. The most significant overhead comes from listing the directory, but an event that should not become prohibitively expensive for file sizes reasonably expected on mobile devices (< 10GB).

Additionally, @ne20002 is right - large chunk size will have vastly detrimental effect in poor connectivity situations.

I do believe we could improve the situation for those less connected users by using smaller chunks, tailored to the uploaded file size. Having a fixed size 10 MB chunk size will yield no benefit in most cases, such as syncing documents or photos, which are typically smaller.

Generally, there are situations where the number of chunks will matter tho. For example, this script will be affected by number of files:
```bash
#!/bin/bash

for i in *; do
    cat $i >> out
done
```
Invoking cat binary has significant overhead.

But if you run this benchmark in Golang, it won't:
```go
package main

import (
	"io"
	"io/ioutil"
	"os"
)

func main() {

	l, _ := ioutil.ReadDir(".")

	out, _ := os.Create("out")
	for _, fname := range l {
		chunk, _ := os.Open(fname.Name())
		_, _ = io.Copy(out, chunk)
		chunk.Close()

	}
	out.Close()
}
```

Here is a quick benchmark made on my machine, using NVMe drive. Subject is 1GB file divided in 100kB, 1MB or 50MB chunks. Mechanical drives should not have a vastly different scalability profile, but a benchmark proving me wrong is welcome.

| chunk size | bash loop | compiled go |
|---|---|---|
| 100000 x 100kB | 12s | 0.75s |
| 1000 x 1MB | 3.5s | 0.5s |
| 20 x 50MB | 0.5s | 0.5s |

If the server displays a scalability problem similar to the example bash script, the fix belongs to the server.

**Comment by neufeind** [comment]
On platforms that support it, could we maybe even use sparse-files for storing the chunks? We'd need to keep track all chunks are complete - but once you uploaded all chunks the sparse-file (first with holes in it) will finally be complete and would not require copying it again.
