### ISSUE TITLE
Nextcloud Dev 20170415:  Phone is becoming warmer than usual.

### ISSUE THREAD

**Issue by OlivierS1** [nextcloud/android#840]
### Actual behaviour
-Tell us what happens
After installing "Nexctloud Dev: 20170415" the phone as been running warmer than usual.
While taking a video to test "Autoupload", I let the video being recorded for the full 5mintues, then on the second video being recorded, the camera app terminated the recording complaining the phone was getting too hot.
I don't know if Nextcloud Dev is doing some intensive work in the background trying to sync up with the server or there is bug  causing excessive CPU usage.

### Expected behaviour
-Tell us what should happen
 
### Steps to reproduce
1. "Autoupload" must be enabled and target the camera folder.
2. Taking more than one video.
3. During upload of the video and recording the phone will get warmer and cause the camera app to cancel recording.

### Environment data
Android version:
6.0

Device model: 
LG3
Stock or customized system:
Stock

Nextcloud app version:
Nextcloud Dev 20170415

Nextcloud server version:
11.0.2

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Is it still happening? It seems still a bit strange that camera is cancelling recording due to warm device...

**Comment by mario** [comment]
@tobiasKaminsky that's normal. Whenever your phone gets hot, it will either cancel stuff or shut itself down.

Not 100% sure this is a NC app bug ...

**Comment by OlivierS1** [comment]
@tobiasKaminsky @mario For this particular case, the sync process caused the phone to run hotter. I didn't record video back then when it first happened but did try after that.
My phone will always record video with a maximum of 5 minutes. But when I tried to record, the already hot phone caused by the sync caused the camera app to shut down almost immediately.
It is possible this issue was only related to Dev 20170415. 
With the newer Dev releases, I update them almost on a daily basis, I haven't noticed the phone running excessively hot. It does get warm when I sync everything from scratch but not that hot.

**Comment by mario** [comment]
Dear users,

thank you for your patience. After lots of work, we’re super excited to be able to give you a test version with new auto upload implementation. Keep in mind we will only accept bugs related to Auto Upload in this APK, as other things might be broken.

https://cloud.nextcloud.com/s/ftZraTruRQjTe0R

This is a dev APK so it will not overwrite your existing play store/f-droid APK unless you’re already running dev version. Also, you might need to remove your existing dev version before installing this one.

Explanation of the current functionality:
- added support for custom folders
- separated image and video folders
- checks for new files happens every 15-20 minutes
- automatic retry every 15-20 minutes or when you force close/open the app
- automatic pause once network is changed (untested!)
- significantly less battery usage

All and any testing is more than appreciated, especially with large and ever-going files like Videos. (like, try to record a 30 min video).

Let me know if you’ve got any questions.

Cheers,
Mario

**Comment by tobiasKaminsky** [comment]
No response within the last month, therefore closing.
Please feel free to reopen with additional infos, if the problem still exists.
