### ISSUE TITLE
Visual issue with auto upload

### ISSUE THREAD

**Issue by storm1er** [nextcloud/android#8407]
### Steps to reproduce
1. Set a folder for auto upload
2. Put a heavy file in it ( >100mb)
3. With app close, look at notification, open app using notification

### Expected behaviour
- the inapp upload status should match notification

### Actual behaviour
- upload status not in sync

### Environment data
Android version: 10

Device model: OnePlus 6

Stock or customized system: stock

Nextcloud app version: latest on 2021-05-14

Nextcloud server version: 21.0.1

Reverse proxy: traefik

#### Web server error log
```
Not relevant
```

#### Nextcloud log (data/nextcloud.log)
```
Not relevant
```

#### Screenshot

![Screenshot_20210514-202855](https://user-images.githubusercontent.com/9821946/118314075-e95a6480-b4f3-11eb-916d-9e507a6d9da6.jpg)
![Screenshot_20210514-202900](https://user-images.githubusercontent.com/9821946/118314084-ebbcbe80-b4f3-11eb-9093-2362e0a78f88.jpg)

**Comment by tobiasKaminsky** [comment]
Is this all the time not matching?
As far as I know upload queue is updated every 10s, so it might just take a bit?

**Comment by storm1er** [comment]
After multiple tries, the 10s story seems right.
I find this weird but I can deal with it.

I still consider this issue valid from an UX point of view.
@tobiasKaminsky close this if you want.
