### ISSUE TITLE
Nextcloud Dev 20170415: Autouploads of video breaks files.

### ISSUE THREAD

**Issue by OlivierS1** [nextcloud/android#841]
### Actual behaviour
-Tell us what happens
When Autoupload is enabled for Camera folder,  video file being recorded will become corrupted.
Behavior is identical to the previous ticket, however, there is still corruption even though the file remains in its original forlder:
Beta 20170221: Autoupload of video corrupts files #673

### Expected behaviour
-Tell us what should happen
 Nextcloud app should detect when the file has been finalized before moving ahead with the autoupload.

### Steps to reproduce
1. Have Autoupload for Camera to be enabled.
2. Open Camera app and take a video. I was running the test for the maximum length of recording which is 5 minutes on my phone.
3. Transfer is probably underway while video is in progress
4. File sent to server is truncated and damaged because it is incomplete. 107MB out of 600MB file would only be uploaded.

### Environment data
Android version:
6.0
Device model: 
LG-3

Stock or customized system:
Stock

Nextcloud app version:
Nextcloud Dev 20170415

Nextcloud server version:
11.0.2

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
@mario do you have an idea regarding upload? Could this be as android is cancelling long running background jobs if the device is idle?

**Comment by mario** [comment]
@tobiasKaminsky it shouldn't even start uploading while recording is in progress - this was tested on number of phones and it worked quite ok :-/

@jasonbayton can you confirm?

**Comment by jasonbayton** [comment]
On your recommendation I switched from Dev. I'll have a look in a bit and get back to you

**Comment by OlivierS1** [comment]
With Nextcloud dev version 20170515 the issue still remain.
I have tried the various scenario:
5 minute recording leads to about 1GB video file.

Nextcloud storage on internal SD with both video recorder internal or on the external SD card.
Nextcloud storage on external SD with both video recorder internal or on the external SD card.

Both solutions (4 different configuration) fail.
Transfer seems to start about 2 minutes after the movie has started recording. Out of the few video trials, the files uploaded would range between 8MB up to 148MB.
I am not able to send Log file has the app is crashing trying to do so.

**Comment by tobiasKaminsky** [comment]
> I am not able to send Log file has the app is crashing trying to do so.

You can try to delete the log, reproduce it and then send the log.
(if the log file is > 1 mb android cannot handle it).

**Comment by jasonbayton** [comment]
Nextcloud dev immediately quits on my Motorola(s) so I can't do any testing :(

**Comment by tobiasKaminsky** [comment]
Same here, a new version is now available.

**Comment by jasonbayton** [comment]
![image](https://cloud.githubusercontent.com/assets/3178412/26111982/89885ed2-3a4e-11e7-8cd2-1e0fa02df3d5.png)

Absolutely no issue at all. Moto G Play, Moto Z & Zyro.

**Comment by OlivierS1** [comment]
No success with version 20170516.
Is it possible the update process has left some remnant files or corrupted some files which are causing those issues?
What is the location of the log files?  I found some old ones which I deleted, but I haven't seen new ones created. The Nextcloud_log folder seem to be created but are empty.
Could it be something to do with having migrated the location of the data from the internal SD to the external SD card and back? Could this have been broken somehow?
If one of the above issue is at play, what would be the best way to clean up the mess?
I am without clue right now.

**Comment by tobiasKaminsky** [comment]
@OlivierS1 there was some time ago a bug with upload, but this affects only files that were already uploaded: it failed on every second try.

The log folder is: /data/user/0/com.nextcloud.android.beta/files/log
It is in the private folder of the app to ensure that log files can be written without any permission to external files / files at all.

Upload should be independent from storage location. 
It should be enough to remove the app and install it fresh via fdroid/apk to get a clean new config.

Meanwhile here is a new dev version with log (hopefully) https://kaminsky.me/nc-nightly/latest.apk
Thank you for testing!

**Comment by jasonbayton** [comment]
> @OlivierS1 there was some time ago a bug with upload, but this affects only files that were already uploaded: it failed on every second try.

I really liked that bug, I could upload the whole contents of a folder and be sure it'd only upload those that aren't already there 👍

**Comment by tobiasKaminsky** [comment]
Never thought of abusing the bug in this way :-D

**Comment by jasonbayton** [comment]
I think I mentioned to @AndyScherzinger it was one of my favourite _features_ ;)

**Comment by OlivierS1** [comment]
Hi,

Updated with your latest APK, not doing a fresh install. Log is now available again.
I am still experiencing video file corruption but I have the log this time.
Is there a better way to send you the content of the log, other than posting it on the forum?

**Comment by mario** [comment]
Mario@ nextcloud Dot com :)

**Comment by OlivierS1** [comment]
log sent via email.

**Comment by mario** [comment]
Never got it...

**Comment by tobiasKaminsky** [comment]
@OlivierS1 can you resend it to android at nextcloud dot com?

**Comment by mario** [comment]
Dear users,

thank you for your patience. After lots of work, we’re super excited to be able to give you a test version with new auto upload implementation. Keep in mind we will only accept bugs related to Auto Upload in this APK, as other things might be broken.

https://cloud.nextcloud.com/s/ftZraTruRQjTe0R

This is a dev APK so it will not overwrite your existing play store/f-droid APK unless you’re already running dev version. Also, you might need to remove your existing dev version before installing this one.

Explanation of the current functionality:
- added support for custom folders
- separated image and video folders
- checks for new files happens every 15-20 minutes
- automatic retry every 15-20 minutes or when you force close/open the app
- automatic pause once network is changed (untested!)
- significantly less battery usage

All and any testing is more than appreciated, especially with large and ever-going files like Videos. (like, try to record a 30 min video).

Let me know if you’ve got any questions.

Cheers,
Mario

**Comment by tobiasKaminsky** [comment]
No response within the last month, therefore closing.
Please feel free to reopen with additional infos, if the problem still exists.
