### ISSUE TITLE
Nextcloud Dev 20170415: clicking on a thumbnail downloads the file.

### ISSUE THREAD

**Issue by OlivierS1** [nextcloud/android#842]
### Actual behaviour
-Tell us what happens
On Nextcloud Beta, there was the ability of clicking on a thumbnail of a photo and be able to display the thumbnail in full screen. At the same time, it was also possible to scroll through the photos without downloading the files themselves. This was a nice feature to have as the downloading the picture was done in the background and when download was complete, the thumbanil in the scroll mode would show the full size image.

Should we expect Nextcloud Dev to have the same behavior found in Beta?

**Comment by tobiasKaminsky** [comment]
If/when I have time I resume work on #69 and then it will be again first be available on dev.

**Comment by OlivierS1** [comment]
@tobiasKaminsky This feature returned somewhere along NC Dev 20170801 but doesn't seem to be made available for NC 2.0.0RC2.
I didn't want to add to #69 not to crowd the post.
Any chance of having it on 2.0? It just plain works.

**Comment by tobiasKaminsky** [comment]
No, this needs code review and thus we can only get in 2.1.
