### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by hodev-dev** [nextcloud/android#8421]
### Steps to reproduce
1. Start a video 
2.  Push back button using native android navigation gesture
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
*********** CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to read from field 'android.widget.VideoView com.owncloud.android.databinding.FragmentPreviewMediaBinding.videoPreview' on a null object reference
	at com.owncloud.android.ui.preview.PreviewMediaFragment$LoadStreamUrl.onPostExecute(PreviewMediaFragment.java:485)
	at com.owncloud.android.ui.preview.PreviewMediaFragment$LoadStreamUrl.onPostExecute(PreviewMediaFragment.java:456)
	at android.os.AsyncTask.finish(AsyncTask.java:755)
	at android.os.AsyncTask.access$900(AsyncTask.java:192)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: starlte
Model: SM-G960F
Id: QP1A.190711.020
Product: starltexx

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: G960FXXUFFUC6

```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
@hodev-dev did the video start already or did you navigate away before that?

**Comment by hodev-dev** [comment]
Aftet watching video, as i use back button on app bar to navigate back it opens menu bar instead and crashes . But using soft back button is just fine .
I just removed app btw because i had mqny problem with it . So if you want you can close the issue . But problem atill persist tho.
 Thank you for support anyway

**Comment by AndyScherzinger** [comment]
Thanks for the update @hodev-dev. I'll leave it up to @tobiasKaminsky to keep it opened or close it. Since he is working on a new video player integration.

**Comment by tobiasKaminsky** [comment]
We have a check in place for this. 
Let me close it, but of course feel free to re-open once you use the app again.
