### ISSUE TITLE
problem with renewal of mnemonic code in application

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/android#8424]
I had to reinstall the nextcloud 20.0.1 server on my raspberry again, using the same domain as: pippo.it.

I re-installed end to end application and then it created me new e2e private and public keys. 

now when I removed the old nextcloud account from my android and went to enter the new user called Tiger, the application automatically sets the mnemonic code of the old server installation and does not take the new mnemonic code that the new nextcloud installation should give us. on a new phone it worked. 

but on another phone where there was an old server installation how can I tell him that he has to get back the new mnemonic code? i also uninstalled and reinstalled apps. is there a folder where the e2e keys reside on android that I can delete?

@AndyScherzinger 

how can i completely reset nextcloud application on android so that it gets the mnemonic code right?

**Comment by szaimen** [comment]
> i also uninstalled and reinstalled apps. is there a folder where the e2e keys reside on android that I can delete?

You most likely need to reset the applications storage. just navigate to the apps settings, go to storage options and clear the apps storage.

**Comment by tigernero79** [comment]
@szaimen I tried but same result when I put account it always brings me old application mnemonic code and does not take the new one generated by a new server installation

**Comment by szaimen** [comment]
Maybe the accounts don't get removed completely this way? Did you try to remove them from the android account settings?

**Comment by AndyScherzinger** [comment]
Looping in @tobiasKaminsky since he did the Android client part for e2ee.

**Comment by tigernero79** [comment]
I solved it by logging into the application with another server user to whom created e2e folder and generating mnemonic code. when I disconnected it and put it back my user again the mnemonic code was gone and then entering the e2e folder he asked me for the 14 words.

solved like this, but it is a bug that removing the account does not remove the keys or the mnemonic code. I am an administrator and I could create a different user to log in and then log out and reconnect with mine, but if I were not an administrator I would have had problems

**Comment by tigernero79** [comment]
@AndyScherzinger another thing that I do not understand because on the nextcloud server it is not possible to rename a user

**Comment by tobiasKaminsky** [comment]
> solved like this, but it is a bug that removing the account does not remove the keys or the mnemonic code.

According to code we remove the keys upon account removal:
https://github.com/nextcloud/android/blob/7b57950abfed721ce1e4d4529d7ed080bc11dd44/src/main/java/com/nextcloud/client/jobs/AccountRemovalWork.kt#L118

**Comment by tigernero79** [comment]
yes, it happens that if you reset the server with a fresh installation and then reinstall end to end as an application.  even if the android client is uninstalled and reinstalled, it will always carry old mnemonic code.  I solved it by logging in with another user created by me, but the mnemonic codes should also be deleted by deleting the account

**Comment by tigernero79** [comment]
@tobiasKaminsky strange because on s10 the mnemonic code was not deleted, both after deleting the account and after a clear cache, and after complete uninstallation of the application.  I solved it only by logging in with a different user to which I created cartrlla e2e, and then returning with my user, only then the old mnemonic code was no longer there and the correct ds transcribed
