### ISSUE TITLE
Auto upload uploads by 4G when connected to a wifi network without internet

### ISSUE THREAD

**Issue by elangelo** [nextcloud/android#844]
### Actual behaviour
-Auto upload starts uploading through my 4G when the wifi network it's connected to does not have a connection to the internet (imagine hotel networks where you regurarly need to login again on a web page)

### Expected behaviour
-Auto upload should detect that it doesn't have a proper internet connection by wifi and should just not upload
 
### Steps to reproduce
1. 
2. 
3. 

### Environment data
Android version:
6
Device model: 
moto x play
Stock or customized system:
stock
Nextcloud app version:
1.4.2
Nextcloud server version:
11.0.2

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by mario** [comment]
Is the wifi connection dropped in this case?

**Comment by elangelo** [comment]
No. The wifi connection stays on.

**Comment by mario** [comment]
K, would you be willing to test when I finally get the time to come around to this? (aka, do you have regular access to captive-portal protected wifis?)

**Comment by elangelo** [comment]
Yep I have access to such a thing, so yes I can test this

**Comment by mario** [comment]
Great, thanks! :)

**Comment by mario** [comment]
Dear users,

thank you for your patience. After lots of work, we’re super excited to be able to give you a test version with new auto upload implementation. Keep in mind we will only accept bugs related to Auto Upload in this APK, as other things might be broken.

https://cloud.nextcloud.com/s/ftZraTruRQjTe0R

This is a dev APK so it will not overwrite your existing play store/f-droid APK unless you’re already running dev version. Also, you might need to remove your existing dev version before installing this one.

Explanation of the current functionality:
- added support for custom folders
- separated image and video folders
- checks for new files happens every 15-20 minutes
- automatic retry every 15-20 minutes or when you force close/open the app
- automatic pause once network is changed (untested!)
- significantly less battery usage

All and any testing is more than appreciated, especially with large and ever-going files like Videos. (like, try to record a 30 min video).

Let me know if you’ve got any questions.

Cheers,
Mario

**Comment by xordspar0** [comment]
@mario Were the changes in that dev apk merged into master?
