### ISSUE TITLE
Make haptic feedback optional when navigating within the app

### ISSUE THREAD

**Issue by gerdablum** [nextcloud/android#8440]
### Is your feature request related to a problem? Please describe.
When I navigate through the app, there is a short vibration on every screen change. I cannot disable this in the settings.

### Describe the solution you'd like
An option in settings which disables haptic feedback

### Describe alternatives you've considered
Another solution would be to disable the vibration generally. I wouldn't suggest that, as some people already got used to the haptic feedback and might miss it when it's gone.

**Comment by AndyScherzinger** [comment]
@gerdablum which version of the app and which device/Android version are you using? I tried any setting on my phone silent/vibrate/sound and have no vibration anywhere (Running Android 11).

**Comment by lunarcontrol** [comment]
I'm on a Samsung s8 with version 3.16.0 of the app and I don't feel any haptic feedback (vibration)

**Comment by AndyScherzinger** [comment]
Seems this is a edge case specific to your phone/oem-android-version, so closing for now
