### ISSUE TITLE
android app unable to grant access

### ISSUE THREAD

**Issue by moritz81** [nextcloud/android#8444]
hi,

new installtion of the current nextcloud-app from google-appstore (version 3.16.0) is unable to grant access for the smartphone (error code -1).
login wokrs but not grant access, also vie app-token it doesnt work.
server version is 21.0.1

login with browser is no problem.

**Comment by airvb** [comment]
Same even with 21.0.2

**Comment by AndyScherzinger** [comment]
Hi @moritz81 and @airvb are you by any chance running a server on TLS-1.3-only? --> #8355

**Comment by moritz81** [comment]
the server is running on tls 1.3 only

**Comment by moritz81** [comment]
with enabled tls 1.2 it works. 
also the auto-upload in wifi works with enabled tls 1.2.

if only tls 1.3 is enabled auto-upload also wont work in wifi.

**Comment by airvb** [comment]
hello
working great after re authorize tlsv1.2 on my nextcloud server !

Thanks for yr help :)

**Comment by AndyScherzinger** [comment]
See referenced issue. So this'll ship with the next release.
