### ISSUE TITLE
Undismissable, constant "Downloading" notification

### ISSUE THREAD

**Issue by zingmars** [nextcloud/android#8452]
### Steps to reproduce
1. Have a file that's set to be automatically synced and is constantly updated
2. Update the file from another device

### Expected behaviour
- Nextcloud downloads the file and does not leave behind a notification

### Actual behaviour
- There's a stuck notification that displays the file download being @ 100% that cannot be dismissed without either killing app or deleting the file locally and redownloading it. Either way it will happen again in a couple of minutes.

![image](https://user-images.githubusercontent.com/917126/119115786-3a0c1900-ba30-11eb-9252-a2bf9f0c1979.png)

### Can you reproduce this problem on https://try.nextcloud.com?
I'll try this later...

### Environment data
Android version: 10 (OxygenOS 10.3.10)

Device model:  OnePlus 6T

Stock or customized system: Stock

Nextcloud app version: 3.16.0 (Google Play)

Nextcloud server version: 21.0.2

Reverse proxy: no

#### Web server error log
No errors on web server's side

#### Nextcloud log (data/nextcloud.log)
This even relevant to the android app? I can't find any logs.

**Comment by Kaerbr** [comment]
Same here.

**Environment data**
Android version: 12 beta1 (SPB1.210331.013)
Device model: Pixel 5
Stock or customized system: Stock
Nextcloud app version: 3.16.0 (Google Play)
Nextcloud server version: 20.0.8.1
Reverse proxy: no

**Comment by szaimen** [comment]
Duplocate of https://github.com/nextcloud/android/issues/8308

**Comment by froschl** [comment]
same here:

Environment data
Android version: 7.1.2
Device model: Samsung Galaxy A5(2017)
Stock or customized system: custom
Nextcloud app version: 3.16.0
Nextcloud server version: 19.0.12
Reverse proxy: no
