### ISSUE TITLE
Can't build APK due to task ":processGenericDebugResources"

### ISSUE THREAD

**Issue by camdenorrb** [nextcloud/android#8453]
### Steps to reproduce
1. Use release build of Android Studio
2. Clone project
3. Follow SETUP.MD
3. Build

### Expected behaviour
- To build the APK without errors

### Actual behaviour
Build error stacktrace: https://gist.github.com/camdenorrb/40d65cca035f6bd55afbc566c1f34340

### Environment data
Java Version: Android Studio's JDK 11.0.8

**Comment by tobiasKaminsky** [comment]
Which platform do you use?
Which Android Studio version?

**Comment by camdenorrb** [comment]
Recloned and all seems fixed now :)
