### ISSUE TITLE
Replace ListView by RecyclerView, use Glide for caching images

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#846]
To speedup displaying large folders all instances of ListView should be replaced by RecyclerViews.

**Comment by AndyScherzinger** [comment]
👍 +1 for that :)

**Comment by AndyScherzinger** [comment]
image thumbnails should then be fetched using glide imho

**Comment by AndyScherzinger** [comment]
obsolete

**Comment by AndyScherzinger** [comment]
obsolete
