### ISSUE TITLE
Upload view: clicking on an pending/uploaded item should do something

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#847]
When clicking on an pending/uploaded item in upload view it should do something
- opening file detail view
- open file (play music, show image, ...)
- ~~open target folder~~

**Comment by AndyScherzinger** [comment]
What should happen in which situation?

- open file if file type is supported by preview mode (would also need resized images support, to save bandwidth in case "delete after upload" has been chosen
- open details view for all other files
- target folder shouldn't be needed since uploads would always be files, right?

**Comment by tobiasKaminsky** [comment]
or a little bit easier:
show image if it is available, in all other cases show detail view?

You are correct with target folder.

**Comment by mario** [comment]
I don't really like the detail view in general :-/

**Comment by AndyScherzinger** [comment]
I'd say always open file if available :D Either in-app for types we support or with other apps (worst case there is none but Android will tell that to the user).

**Comment by mario** [comment]
IMHO, I wouldn't touch upload view. I know, I'm complicated ... but Upload
view server one purpose, and it is not opening a file or viewing its
details.

**Comment by tobiasKaminsky** [comment]
When you are in the upload pane and you are wondering what file you have uploaded as you cannot see it from the thumbnail, you would have remember the name and folder and go to this folder, search the file and click on it...
Yes, the main purpose of this view is to see the upload(ed) queue, but why not make it for some people easier ;-)

**Comment by tobiasKaminsky** [comment]
As we had many different ideas, I would go with
- open file, if any app can handle this
- if not: nothing, do nothing, as we do not have a file detail view for local files

**Comment by AlvaroBrey** [comment]
IMO we should only do that for files that are in the Uploaded group. For files pending upload I think it's confusing to add another action besides the "cancel" button in this view.

**Comment by tobiasKaminsky** [comment]
It is about clicking on it, there will be no button.
But then we have mixed behaviour:
- failed: click on it restarts it
- pending/completed: click on it opens file

🤷

**Comment by AlvaroBrey** [comment]
What about:

* Single tap: restarts failed, does nothing on pending or completed
* Long tap: shows dropdown with options:
    *  For failed: "restart", "open"
    *  For pending: "open", "cancel"
    *  For uploaded: just "open"
    
Or maybe just always show the dropdown, even with single click
