### ISSUE TITLE
Update docker-ci image java8->java11

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#8474]
Since we moved to Android Studio 4.2 which uses 11 by default we should update the CI image to java 11 too and also remove the java8 GH action assembly flavor.

https://github.com/nextcloud/docker-ci/blob/master/android/Dockerfile#L4

**Comment by tobiasKaminsky** [comment]
https://github.com/nextcloud/docker-ci/pull/281

**Comment by tobiasKaminsky** [comment]
Waiting for docker to finish android61: https://hub.docker.com/r/nextcloudci/android8/builds/
