### ISSUE TITLE
Setting to start auto-upload only in favorite WIFI

### ISSUE THREAD

**Issue by schbrongx** [nextcloud/android#8481]
In this case the title says it all: Give users zhe option to fav a Wifi and restrict auto-upload to that specific Wifi.

Use-case: Users zhat have not enabled external access to their cloud.

**Comment by tobiasKaminsky** [comment]
A current workaround would be to restrict auto upload to non metered wifi and set only your favorite wifi to non-metered.

**Comment by joshtrichards** [comment]
Duplicate of #3671
