### ISSUE TITLE
Storage path ignored / unstable

### ISSUE THREAD

**Issue by Olangu** [nextcloud/android#8487]
I set my storage path to be located on my sd-card and then started a full syncronization of my 30gig+ file cloud.

As expected the files started to show up on sdcard.

But checking back later i found out that files had been put on internal storage.

My directory structure is something like this:
Folder1:
 Folder1_2010
 Folder1_2011
 Folder1_2012

Folder2:
 Folder2_2011
 Folder2_2012
 Folder2_2013

Folder3:
 Folder3_2011
 Folder3_2015
 Folder3_2016

What made this even more strange was how they ended up to be stored on the phone.

So for example everything in Folder1 might end up on the sdcard, half of Folder2 and none of Folder3.
But looking for "local files" in nextcloud all root folders where available, but the directory that was split, I could only see the ones that ended up on internal storage. So somehow the program have individual information of where the root folder is stored, this information is hidden from the user. And in the main release there is no logs to be shown.

I'm running the F-Droid version 3.16.0.

**Comment by AndyScherzinger** [comment]
@Olangu did you have a larger amount of files stored on the device before you synced the 30+ Gig? When you change the storage path in the settings a migration is triggered in the background so maybe that wasn't finished when the sync has been triggered but I can't say for sure, so just guessing here.

**Comment by Olangu** [comment]
I tried that at first, but all moved files got the wrong timestamp on migration (I should probably try to reproduce that and file another bug report).

So for this I removed all local files, on both sdcard and internal storage.

**Comment by AndyScherzinger** [comment]
Did you remove the files via the app itself? Else the client still has references to already downloaded/synced files in its database which might lead to other problems down the road.

**Comment by AndyScherzinger** [comment]
Also if a migraion fails at some point I think the clients reverts to the old/former storage path

**Comment by Olangu** [comment]
I would never dare to, the interface is too error prone, too easy to do wrong, might end up deleting all the files on the server.

Ok, I'll try remove all data from the app and try again.

Why is there no interface for editing this?

**Comment by Olangu** [comment]
Ah, yeah, the remove all data from app did not work either.
Had to remove and install anew.

**Comment by AndyScherzinger** [comment]
> Why is there no interface for editing this?

Editing what?

> Had to remove and install anew.

Did that help as in solving the original issue and putting all files in the right/expected place?

**Comment by Olangu** [comment]
Editing the references. Or atleast have some kind of db cleanup if files are removed.

Yes, after reinstallation the files ended up in the expected place.

So this should probably be a migration bug.
