### ISSUE TITLE
App not staying sign in with ldap account

### ISSUE THREAD

**Issue by docfactory37** [nextcloud/android#8497]
### Steps to reproduce
1. Sign in with ldap account, dose not sign in correctly 

### Expected behaviour
- Tell us what should happen
When signing with ldap user should stay signed in as would a local account

### Actual behaviour
- Tell us what happens

I have tested with signing in with an ldap account,when you sign in with and ldap user it signs in with website view, and once you close the app and reopen it will ask you to setup the account again.

If you sign in with a local account the app works as expected and signs in and stays sign in after closing and reopening the app.

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: latest version of Android

Device model: pixel 4xl

Stock or customized system:

Nextcloud app version: latest version

Nextcloud server version: 21.0.2

Reverse proxy: yes

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
> I have tested with signing in with an ldap account,when you sign in with and ldap user it signs in with website view

This does mean that there is no valid redirect after successful login.
What kind of ldap / SSO / setup do you use?

**Comment by docfactory37** [comment]
I have and openldap docker container running with no ssl and on standard 389 port.

The ldap users works fine in the desktop client

**Comment by docfactory37** [comment]
@tobiasKaminsky is this an issue with the app it self as it used to be fine and only start after up dating the app?

**Comment by docfactory37** [comment]
The issues is still happening why is it close and no response I have ask a question about no one has responded?

**Comment by AndyScherzinger** [comment]
> The issues is still happening why is it close and no response

It isn't see history. I closed if by accident and re-opened
