### ISSUE TITLE
Autupload settings not being applied

### ISSUE THREAD

**Issue by sprnza** [nextcloud/android#8502]
### Steps to reproduce
1. Set up autoupload to custom location on the server, 
2. disable "Sync only on WiFi"

### Expected behaviour
- Setting are being applied.

### Actual behaviour
- The app keeps to autoupload to default "Autoupload" folder only on WiFi.

### Environment data
Android version: 10
Device model:Sony XZ1 compact 
Stock or customized system: Leanege OS
Nextcloud app version: 3.16.0

**Comment by tobiasKaminsky** [comment]
Hm. I cannot reproduce it.
Please note that those settings only apply for new uploads.
