### ISSUE TITLE
DEV 20170419 Download lastedt dev

### ISSUE THREAD

**Issue by JSoko** [nextcloud/android#851]
In DEV 20170419 and before

clicking on Download latest dev version leads toNo information available

### Expected behaviour
-should state that the version is the newest or download a newer version
 
### Steps to reproduce
1.  click on Download latest dev version 

### Environment data
Android version: 7.0

Device model: sgs7

Stock or customized system: stock

Nextcloud app version: 20170419

Nextcloud server version: 11.0.3.1

**Comment by tobiasKaminsky** [comment]
Is fixed now.
Please test and if not, reopen.

**Comment by JSoko** [comment]
Yes, shows now "No new version availabe!"

Thanks!
