### ISSUE TITLE
auto upload problem

### ISSUE THREAD

**Issue by prolibre** [nextcloud/android#8517]
I often have problems with the automatic download. In fact, it works from time to time, but often the files are not sent.
Often the uploads are marked with an error.
In this case, there is a good connection on my nextcloud server. In the logs I only have :

_IP - - [02/Jun/2021:10:40:59 +0200] "GET /index.php/204 HTTP/1.1" 204 5340 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.16.0"
IP - - [02/Jun/2021:10:40:59 +0200] "GET /index.php/204 HTTP/1.1" 204 5342 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.16.0"
IP - - [02/Jun/2021:10:40:59 +0200] "GET /index.php/204 HTTP/1.1" 204 5340 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.16.0"_

but nothing more.
If I force the stop of the application and I restart it I can restart the upload and it works.
This happens for one or more files.

### Environment data
Android version: 7.0 NRD90M (MIUI Global 11.0.2)

Device model: Xiamo redmi note 4

Nextcloud app version: Nextcloud-android/3.16.0

Nextcloud server version: 21.0.2

Reverse proxy: no

**Comment by tobiasKaminsky** [comment]
What error do you see?
