### ISSUE TITLE
AutoUpload Android 3.16.1 showing 'Connection error'

### ISSUE THREAD

**Issue by maanloper** [nextcloud/android#8518]
### Problem
Still same problem as on 3.16.0; AutoUpload does not work. When I make a picture, it shows up in the upload que under failed uploads with error: 'Connection error'. My NC instance works fine using desktop app and browser, and AutoUpload used to work before 3.16.0 when the problem was introduced.
How can I help debug this, I cannot find a logs option in de android app?

### Setup
Server 20.0.6
Android 10
Nextcloud app 3.16.1

**Comment by maanloper** [comment]
To update:
When enabling TLS1.2 on the server, I can upload. But when disabling TLS1.2 and only enabling TLS1.3, the app throws a connection error.

**Comment by maanloper** [comment]
@AndyScherzinger or @tobiasKaminsky can you provide any update on why after apparent fixes in 3.16.1 the same behaviour with TLS1.2 on is still seen?
Related:
https://github.com/nextcloud/android/issues/8197
https://github.com/nextcloud/android/issues/8387
https://github.com/nextcloud/android/issues/8355

Might I suggest a **roll-back** to 3.15 until problems have been properly fixed?

**Comment by d0b3rm4n** [comment]
In my nginx configuration I had:
`ssl_protocols TLSv1.3;`

And with Nextcloud app 3.16.1 on Android 10, uploads over WIFI did not work, also set the WIFI explicitly to _unmetered_ but it did not work, just upload errors.

But it worked with 4G connection!?

After switching the nginx config to:
`ssl_protocols TLSv1.3 TLSv1.2;`

Upload over WIFI started to work.

**Comment by AndyScherzinger** [comment]
> Might I suggest a roll-back to 3.15 until problems have been properly fixed?

I don't see any link to 3.15. The TLS1.3 wouldn't have worked with 3.15 either

**Comment by maanloper** [comment]
Well, I ran my server using TLSv1.3 only for over 2 years without a problem. So an older android version worked flawlessly. I would suggest a roll-back to the latest stable version (whichever version that might be) before 3.16.0 (when the problem was introduced) untill testing has solved the problem.

But that's just me 2 cents. If something breaks, that can happen, but either fix it, or revert back to when the problem didn't exist :)

**Comment by 53c70r** [comment]
I can reproduce it.
3.16.1 is not handling tls 1.3 correctly which I find really odd.
I hand the exact same warning and "ssl_protocols TLSv1.3;" in my Nginx config.
Adding TLSv1.2 support again "fixed" the problem.

**Comment by tobiasKaminsky** [comment]
Tls 1.3 is since 12.05.21 in master: https://github.com/nextcloud/android-library/pull/618
But this was only for our NextcloudClient.
For checking if upload can be done over unrestricted wifi we use a plain client, which was limited to TLS1 only.

I fixed this with https://github.com/nextcloud/android-library/pull/645 and in #8594 will soon be an APK which you can test.

**Comment by djibux** [comment]
Hello.
Any update on an APK to solve that issue?
Thanks.

**Comment by Sp3ct21** [comment]
Why

**Comment by djibux** [comment]
I guess my message wasn't clear enough sorry.  I was wondering if an APK existed that solves the issue, even if it's still in beta testing.  I am experiencing the issue reported by OP.

**Comment by AlvaroBrey** [comment]
Hello, please confirm if this issue is still present in 3.18.0. Thank you!

**Comment by 53c70r** [comment]
Problem is solved for me on 3.18.0!
