### ISSUE TITLE
Pass dark mode setting to Nextcloud Text app

### ISSUE THREAD

**Issue by splitt3r** [nextcloud/android#8524]
### Is your feature request related to a problem? Please describe.
I hace activated the dark mode in my system setting and the Nextcloud app is set to follow the system setting. Now if i open a Markdown file in the app it opens up the Nextcloud Text app in light mode. In the iOS app the Nextcloud Text app opens in dark mode so it looks likeaproblem related to the android app.

### Describe the solution you'd like
The dark version of the Nextcloud Text server app should open up in the webview.

### Describe alternatives you've considered
Ths Nextcloud Notes app 😄 

### Additional context
Android 10 + latest stable Nextcloud App + Nextcloud 20

**Comment by AndyScherzinger** [comment]
@juliushaertl is there a flag that can be set for Nc Text dark/light? Or how do you achieve this @marinofaggiana. I did a short check of the iOS code but couldn't find any line that takes care of this :S

**Comment by marinofaggiana** [comment]
@AndyScherzinger should  be prefers-color-scheme e.g.:

According to Mozilla, here is the preferred method as of 2020

@media (prefers-color-scheme: dark) {
  body {
    background: #000;
  }
}
@media (prefers-color-scheme: light) {
  body {
    background: #fff;
  }
}

For Safari/Webkit you can use

@media (prefers-dark-interface) { background: #000; }

**Comment by AndyScherzinger** [comment]
@marinofaggiana do you set anything of this on the iOS client side yourself?

**Comment by marinofaggiana** [comment]
Nothing

**Comment by juliushaertl** [comment]
The dark mode is coming from the server there and is not text related (was introduced in https://github.com/nextcloud/server/pull/21366). From a quick search it seems that on Android this is not picked up automatically: https://stackoverflow.com/questions/57449900/letting-webview-on-android-work-with-prefers-color-scheme-dark

**Comment by AndyScherzinger** [comment]
Thanks for the infos and hints: #8543 ships the logic for it
