### ISSUE TITLE
Going back from a video in Media shows '+'

### ISSUE THREAD

**Issue by siccovansas** [nextcloud/android#8528]
### Steps to reproduce
1. Open the Media tab and play a video (wait till it plays)
2. Hit your back button
3. Scroll up and down in the Media screen and notice that there is a '+'-sign in the button right and that the name at the top is no longer 'Media'

### Expected behaviour
- Show the same Media screen as before I open a video, i.e.: no '+'-sign and 'Media' as title at the top

### Actual behaviour
- A '+'-sign in the button right and that the name at the top is no longer 'Media' (but the name of the folder the video is in?)

### Environment data
Android version: 11

Device model: Samsuns Galaxy S10

Stock or customized system: Stock

Nextcloud app version: 3.16.1

Nextcloud server version: 21.0.2

![Screenshot_20210605-174048_Nextcloud_1](https://user-images.githubusercontent.com/696839/120897687-bead8880-c627-11eb-8b95-f788a03722a5.jpg)

**Comment by svenb1234** [comment]
Same issue when you open a picture, pick details from the menu and then hit back. The app shows the name of the folder the picture resides in but displays the content the media tab would show.

**Comment by siccovansas** [comment]
Just checked and this is still an issue on:

Android: 12
Nextcloud Android app version: 3.19.0
Nextcloud server version: 23.0.2
