### ISSUE TITLE
"search fragment": no fab?

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#855]
When entering "photo" or "favorites" there should be no FAB as these actions do not work there?

@mario @AndyScherzinger

**Comment by tobiasKaminsky** [comment]
![screenshot_1492680671](https://cloud.githubusercontent.com/assets/5836855/25223828/dd33c93c-25bc-11e7-9746-6f55f67c628a.png)

**Comment by AndyScherzinger** [comment]
jepp, that is true imho! 👍
