### ISSUE TITLE
How to set VERSION_CODE when I build from source code

### ISSUE THREAD

**Issue by writingdeveloper** [nextcloud/android#8552]
I download source code from github and build it in Android Studio and it seems that the VERSION_CODE is set to 30170000 and VERSION_NAME is set to 3.1.7.0 Alpha 1.

I want to rebuild it and upload to Google Playstore but, first app version is uploaded well but after When I rebuild it and upload to Google PlayStore and it got an error because of version code should be higher than before version.

But I don't know where can I set VERSION_CODE and VERSION_NAME. I use Ctrl + Shift + F and find '3017000' and it is in BuildConfig.java file but it seems that it is generated by build and it should not be edited.

Where can I set version code. I already searched in AndroidManifest.xml and other setting files but I don't know where can I find it.

**Comment by AndyScherzinger** [comment]
Please see https://github.com/nextcloud/android/blob/master/build.gradle#L89-L92
