### ISSUE TITLE
Notifications on home screen can't be removed

### ISSUE THREAD

**Issue by mburnicki** [nextcloud/android#8568]
### Steps to reproduce
1. On the server, update a file that is automatically sync'ed to the smartphone
2. Due to a network error, the server becomes unreachable during sync
3. The app creates a notification with a progress bar on the smartphone, under "Sonstige Benachrichtigungen" (German version).

### Expected behaviour
When the network error disappears and the file can be synchronized successfully, the notification should be removed, or it should at least be possible to remove it manually by wiping it to the side.

### Actual behaviour
After the network error has disappeared, and the file can be synchronized successfully, the notification remains, even if I manually check once more that the file can be synchronized (by opening the smartphone app, and wiping down to force checking of synchronization).
I've found no way to remove the notification. Even if I click on the field that removes all other notifications from "Sonstige Benachrichtigungen", this one remains. Only if I reboot the smartphone, this notification disappears.

This screenshot shows the problem, where the notification persists for 22 hours even though the file could already by synchronized a long time ago:
https://burnicki.net/martin/tmp/Screenshot_20210611-113237_v1.jpg

### Environment data
Android version:
Oxygen 10.3.11

Device model: 
Oneplus 6 (A6003)

Stock or customized system:
Stock

Nextcloud app version:
3.16.1

Nextcloud server version:
20.0.10

Reverse proxy:
No.

**Comment by WeirdCircumstances** [comment]
Better as a reboot is to go to Settings -> Apps -> Nextcloud -> Force Stop (Beenden erzwingen).

**Comment by mburnicki** [comment]
Thanks for the tip. I'm going to retry next time (yes, the problem pops up every couple of days).
It would be better, however, if the app could be fixed ...

**Comment by bigtreiber** [comment]
I can confirm the bug with Nextcloud App 3.16.1 and Server 21.0.2

Force Stop works but is not the expected behaviour. Please fix this.

**Comment by mstaz** [comment]
Can confirm this as well with Nextcloud App 3.16.1 running on Android 10.
Synchronization seems to work fine, only notification stays at 100% and doesn't disappear.

**Comment by newhinton** [comment]
There are multiple issues for this, i am closing this in favor of #8308
If this is not solved with #8308, please reopen.
