### ISSUE TITLE
buil-in Video Player ist slow in loading videos

### ISSUE THREAD

**Issue by svenb1234** [nextcloud/android#8573]
### Steps to reproduce
1. Tap on a video file, which is saved on the nextcloud server, in the android app and watch how the video loads. 
2. Select the same video and use the "Stream with..." option, e.g. Google Fotos App.

### Expected behaviour
- both apps should load and play the video at the same speed

### Actual behaviour
- the built-in player gets stuck, eventually plays a bit and then does not load any further data or really, really slow, while the "Stream with..." option loads the same video on the same network, in the same device without any problems and plays it instantly.

### Environment data
Android version: 11

Device model: pixel 4a

Stock or customized system: stock

Nextcloud app version: 3.16.1

Nextcloud server version: 20.0.10

Reverse proxy: nope

**Comment by tobiasKaminsky** [comment]
We enhanced this for upcoming version. 
Maybe you want to try out our dev version (you can install it in parallel): 
https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#developement-release

If it then still happens, please re-open.
