### ISSUE TITLE
Context menu is black on Samsung Galaxy Tab S7

### ISSUE THREAD

**Issue by PVince81** [nextcloud/android#8576]
### Steps to reproduce
1. Setup NC client with an account containing existing files
2. Browse the file list in the app
3. Click the three dots menu behind a file

### Expected behaviour
Menu entries are visible

### Actual behaviour
No menu entries, the box is here but is empty, or it's black on black.
A workaround is possible: long press on the one item and use the three dots menu on the top right

![image](https://user-images.githubusercontent.com/277525/121854602-ac4fe080-ccf2-11eb-811b-10ac9b77e773.png)

Also, I noticed that in another view, the menu items are a bit more visible but still black on grey:

![image](https://user-images.githubusercontent.com/277525/121854644-ba056600-ccf2-11eb-9265-2fab9e787a69.png)

Note: I'm not using dark mode of any kind, but for whatever reason the menus appear with black background.
On a different device (Nokia 6.1, Android 10) the menus have a white background.

### Environment data
Android version: 11
One-UI-Version: 3.1

Device model: Samsung Galaxy Tab S7

Nextcloud app version: 3.16.1

Nextcloud server version: 21.0.2

Reverse proxy: None

### Logs
Not applicable

**Comment by AndyScherzinger** [comment]
@Valdnet is this working for you? Just asking since you have issues with the pop-up menu theming on the latest talk alphas. So just checking if this is related to a certain constellation.

**Comment by Valdnet** [comment]
@AndyScherzinger For me, on Android 10, the menu for the file is displayed correctly. I didn't notice any problem with the theme 😉.

**Comment by tobiasKaminsky** [comment]
I fear that this is coming from Samsung, where they might have customized their theme and thus our "white" is not correct.
@PVince81 can you switch themes / ui colors on your device?

**Comment by PVince81** [comment]
Hmmm, very strange. Just now when I activated the tablet the context menu looked fine.
Then I force-stopped the Nextcloud app and opened it again, and now the context menus are black again as per my report.

Not sure what condition was in place that allowed the app to "fix itself" for a short moment.

Considering the latter, I suspect that this is not theme related and rather some kind of glitch.

**Comment by PVince81** [comment]
I caught it working again yesterday: the tablet actually has two user accounts, my account (the main account) and one for my wife.

And the two times where the colors magically fixed themselves was when I just had switched back from my wife's account to my own, and then directly opened the Nextcloud app. Yesterday I had the Nextcloud app directly in focus when I switched back. I saw the logo appear after unlocking the screen and directly the file list. At this stage the context menu from the list had the correct black on white colors.

Now... what's going on ??
I wonder if maybe at this early time of user switching, that maybe some theme/color info provided by the tablet is different in some way, and maybe the Nextcloud app is detecting this at load time ? And maybe after a few seconds after logging in, the tablet switches to whatever different internal theme, which means that if the app is started later it would get different colors ?

By the way, I'm not using any special theme of any kind, it's just the tablet's default.

Weird stuff, I'll continue to keep an eye for more clues...

**Comment by PVince81** [comment]
the "magically fixes itself" only happened twice for now, and in both occurrences I was shortly switching back from my wife's account

**Comment by fracklaus** [comment]
I can confirm this issue with Tab S7 and NC app version 16.1.
The issue did not appear in android dark mode, but switching back to light mode triggers it again. 
I have this constantly on my Tab S7.

**Comment by RafalSkolasinski** [comment]
Same here. Also present on Samsung Tab S7

**Comment by PVince81** [comment]
I've retested now, just in case: since I was switching from wife's account very often, the problem did not occur and the menus were always available.

And just now I stopped the app and started it again, and now the bug is present again, some menus are dark.

I'll see if I can provide some logs from both scenarios for comparison and hope it can help pinpoint the issue.
