### ISSUE TITLE
Enhance fingerprint support

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#859]
#624 adds support for fingerprint as an alternative for PIN protection for accessing the app.

some (minor) enhancements should be implemented:

- deactivating PIN (in the preferences) if you activated fingerprinting
- deactivating fingerprint (in the preferences) if you have activated PIN
- ask for fingerprint if you deactivate fingerprint
- some "next 5 tries" mechanism/reset (incorrect finger(print), e.g. 5 times wrong fingerprint and the app is locked and to get another chance at fingerprinting your way into the app you need to wait for e.g. 10 seconds (should be enough imho)

cc @mario @tobiasKaminsky @Flole998

**Comment by tobiasKaminsky** [comment]
👍 
@Flole998 if you have the time if would be really cool if you can do it 👍 
(I promise that we (or at least me) react a lot faster this time)

**Comment by mr-bolle** [comment]
Hi, the unlocking over the fingerprint works great (Sony Xperia Z5 v7.1.1).

I have a desire, is it possible to memorize successful unlocking for the next 10 minutes or until the display is turned off? If for example, individual files are uploaded to the Nextcloud, it is always necessary to unlock them.

**Comment by Flole998** [comment]
Fingerprint unlocking should work just the way PIN unlocking works, it should "remember" that it was unlocked for a while, I'm not sure about the exact timing there though. If I'm not mistaken the PIN unlocking memorizes that for a while and so should fingerprint unlocking.

**Comment by joshtrichards** [comment]
Fixed long ago in #1657 as part of #1286.

Also just tested all the listed items in this issue in latest master.

**Comment by joshtrichards** [comment]
@mr-bolle #3754
