### ISSUE TITLE
Option to turn off automatic media folder discovery and auto upload

### ISSUE THREAD

**Issue by J4gQBqqR** [nextcloud/android#8616]
### Is your feature request related to a problem? Please describe.
This is related to battery draining problem as described in #7663 
In a typical day of usage, I've never ever opened the Nextcloud app. However, Nextcloud is using 10% ~ 20% of all battery without any syncing, auto-upload turned on. Yet, the DavX5, which actually handled my syncing for my contacts, calendar and tasks, only uses less than 1% battery.
As an end user, the behavior does not make any sense to me. 

### Describe the solution you'd like
For some users, the periodic media folder discovery and auto upload feature is not needed. Background activities mean nothing but battery draining for such use scenarios. A toggle to turn off all these features and limit background activity will serve the user well.

### Describe alternatives you've considered
Or an option to auto scan phone's media folder only when the app is opened by the user in foreground, like what VLC player did. Currently, there is no option given to the user to limit background activity.

**Comment by J4gQBqqR** [comment]
Also related to issue #780

**Comment by AndyScherzinger** [comment]
@J4gQBqqR at least for the media folder discovery you can expand the notification and deactivate that mechanism. If you have no auto upload fodlers configured there is no work being triggered. Depending on the size of your user account (as in files and folders) it might take the app quite a while to sync the meta data. So the battery draining should go away after some time.

**Comment by J4gQBqqR** [comment]
I'm sorry, but turning off notification does not resolve battery draining issue. Nextcloud is still running in background doing all the tasks and get 20% battery off of my device without notification. 

Truely, there is nothing configured, notified and uploaded, but the background job is there. The Nextcloud Android client is asking Android system to "scan" and "let me know" about new media folders discovered in Android **periodically**. 

Developers might justify themselves saying that the media file discovery service is not provided by Nextcloud and the battery drain is not contributed by Nextcloud's source code.

But there is one thing that can be changed: the frequency of querying Android.

In this issue, what proposed been to give user the option to adjust the frequency, to turn it off, and to scan media file change only when the app is opened in foreground.

**Comment by J4gQBqqR** [comment]
![IMG_20210805_184950](https://user-images.githubusercontent.com/77554817/128431249-dca5e809-bef0-48d9-8e02-67efd36299fa.jpg)
The number one battery drainer on my phone.
Lineage OS 18.1, Nextcloud 3.16.1
Nothing synced, nothing turned on. 
All background use. Never opened it foreground.

**Comment by J4gQBqqR** [comment]
For anyone having the same issue with me browsing this issue:
If you have your phone rooted, you can turn off services using the "App Manager" app in F-droid.
https://f-droid.org/en/packages/io.github.muntashirakon.AppManager/

Here is screenshots of services that I turned off to keep Nextcloud from draining my battery. Before turning these services off, Nextcloud cannot be "forced stopped", "dozed", killed. After turning them off, I can kill Nextcloud from the foreground and background once and for all. I don't know why Nextcloud Android is made in this way. It behaves like those Chinese app which cannot be killed and drains a lot of battery.

![Screenshot_20210818-084701_App_Manager](https://user-images.githubusercontent.com/77554817/129902183-7d027995-71d5-4a3a-a04b-681f7cea3bc4.png)

![Screenshot_20210818-084730_App_Manager](https://user-images.githubusercontent.com/77554817/129902210-74cdb3d2-ab3a-4e10-b954-e3d1d3ef6918.png)

![Screenshot_20210818-084722_App_Manager](https://user-images.githubusercontent.com/77554817/129902238-b7c0e53e-85a8-4a68-8b28-bc87d2ba0a92.png)

**Comment by joshtrichards** [comment]
Let's consolidate this discussion into #6505. I encourage you to subscribe and/or upvote that issue.
