### ISSUE TITLE
Re-enable autofill for the host URL field

### ISSUE THREAD

**Issue by carlgreen** [nextcloud/android#8617]
I use a custom nextcloud instance and have previously used a password manager to not only complete the username and password, but also the host URL. However as of a commit in February (c8144a08d5f539fe295babce38aa03d4a5e9dde8) android:importantForAutofill="no" was added to src/main/res/layout/account_setup.xml and src/main/res/layout-land/account_setup.xml. This appears to be preventing the manager from autofilling the field

Unless there is a good reason to disable this, it would good to have this removed.

**Comment by AndyScherzinger** [comment]
I'll havew to check why I added it, maybe for alignment with the talk android client, can't quite remember while I agree. If there is no good/real reason we/I put it in then we should remove it

**Comment by joshtrichards** [comment]
Seems fine to me. I see no downside. I'll tag it as a "good first issue"

**Comment by Mouzzamsddq** [comment]
@joshtrichards I would like to work on this. Could you assign this issue to me?

**Comment by Mouzzamsddq** [comment]
@joshtrichards I have created a PR. Please review my code and let me know if there are any changes required.
