### ISSUE TITLE
Media tab - support external storage?

### ISSUE THREAD

**Issue by szaimen** [nextcloud/android#8618]
Now that https://github.com/nextcloud/server/pull/27561 was merged and the photos app implemented support for external storage, too, can we also make the media tab support external storage, too? :)
See https://github.com/nextcloud/photos/pull/804 for inspiration.

cc @tobiasKaminsky @skjnldsv

**Comment by alturismo** [comment]
+1 from here, after some digging i also figured that the Media Tab on Android only shows Photos which are  located inside the personal folder while the web Interface is working properly.

**Comment by szaimen** [comment]
Should probably be fixable somewhere here:
https://github.com/nextcloud/android-library/blob/23f7225766d489ec89a139c641d5dbc15bc96b53/src/main/java/com/owncloud/android/lib/resources/files/NcSearchMethod.java#L288-L302
Problem is I don't understand the syntax at all

**Comment by tobiasKaminsky** [comment]
Query is in https://github.com/nextcloud/photos/blob/master/src/services/PhotoSearch.js
