### ISSUE TITLE
Contact backup fragment replace issue

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#862]
When in contact backup setting and selecting a file to restore, fragment is not correctly replaced
This should have been fixed before merging the branch ;-)

**Comment by mario** [comment]
That's why we have PRs and bugs :P

**Comment by tobiasKaminsky** [comment]
Can you have a look into this? I am still a little bit out of clue...

**Comment by mario** [comment]
@tobiasKaminsky sure.
