### ISSUE TITLE
Weird images appear in the Auto upload interface

### ISSUE THREAD

**Issue by ghost** [nextcloud/android#8624]
![Screenshot_20210624-194800_Nextcloud](https://user-images.githubusercontent.com/80743272/123311131-181e1e80-d527-11eb-98ff-ad4a13ee60db.png)

### Environment data
Android version: Android 11

Device model:  Nextbit Robin

Stock or customized system: LineageOS 18.1

Nextcloud app version: 3.16.1 (F-Droid)

Nextcloud server version: No idea

Reverse proxy: No idea

**Comment by Derkades** [comment]
Same issue here
![Screenshot_20211004-235045](https://user-images.githubusercontent.com/15892014/135929753-3273e1b0-2d1d-46eb-8e8b-210b2fec7b42.png)

**Comment by AlvaroBrey** [comment]
Closed as it can't be reproduced and reporter is deleted account

**Comment by Derkades** [comment]
It indeed seems to have been fixed now
