### ISSUE TITLE
crash on selecting Auto Upload in settings

### ISSUE THREAD

**Issue by cpnfeeny** [nextcloud/android#8626]
### Steps to reproduce
1. Go to Settings > Auto Upload
2. 
3. 

### Expected behaviour
Auto upload settings should appear

### Actual behaviour
Screen goes black after a long delay, then the Nextcloud splash screen appears, and then it opens my files page

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 11

Device model: realme X2 pro

Stock or customized system: realme ui 2.0 Beta

Nextcloud app version: dev 20210624 and 3.16.1

Nextcloud server version: 

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by cpnfeeny** [comment]
This crash occured on the standard Nextcloud app, the beta through Google Play, the dev version, and the beta on F-Droid. Which suggests maybe it's my rom? Clearing cache, rebooting, reinstalling, none of that solved the problem. 

Thanks!

**Comment by AndyScherzinger** [comment]
So you have a very large amount of images and/videos on your device?

**Comment by cpnfeeny** [comment]
I only have around 10 images in my Camera folder. But what I do have are lots of folders in my Music directory that each have a cover.jpg.

Can I exclude them somehow from being scanned, and that would solve the problem?

The strange thing is, however, I had more images and the same number of folders in a different rom and I was able to use the Auto Upload settings menu just fine.

**Comment by AndyScherzinger** [comment]
Maybe you can try to reproduce the crash and grab the logs, see https://github.com/nextcloud/android#getting-debug-info-via-logcat-mag

**Comment by cpnfeeny** [comment]
Deleting the Music folder allowed me to access the Auto Upload settings. So it seems the Auto Upload dialogue can't handle too many media folders at once.
