### ISSUE TITLE
Android compiler issues

### ISSUE THREAD

**Issue by simonaaba** [nextcloud/android#8629]
### Steps to reproduce
1. download the android-master.zip from git
2. android studio 4.2.1+jdk 11
3. Compile error, non-mappable character

### Actual behaviour
![image](https://user-images.githubusercontent.com/10238686/123384654-3e939680-d5c7-11eb-9f04-0c82d19aa208.png)
  
4.in terminal command line ,run the command "gradlew compileDebugSource --stacktrace -info "
![image](https://user-images.githubusercontent.com/10238686/123384780-62ef7300-d5c7-11eb-853c-6339771d8d60.png)
 how to find the problem?

**Comment by ezaquarii** [comment]
There is no target `compileDebugSource`, so the command in step 4 cannot yield any effect.
You can try `./gradlew tasks` to list available targets.

**Comment by simonaaba** [comment]
the question disappeared suddenly , I didn't do anything !Just compile........ 
I think the question occered when the network  cannot be connected to github.com. 
In the build.gradle line one,the android studio remind me "Cannot resolve symbol 'spotbugs'"
![image](https://user-images.githubusercontent.com/10238686/123565672-42eec800-d7f0-11eb-93c2-e3a08d7dbda1.png)

**Comment by AndyScherzinger** [comment]
> I think the question occered when the network cannot be connected to github.com.

Yeas, without an internet connection resolving the dependencies like the one you mentioned above are a problem and lead to errors during the build.
