### ISSUE TITLE
Auto upload from `/android/data` private/protected folders

### ISSUE THREAD

**Issue by tiptruck** [nextcloud/android#8650]
Cannot access android/data through the Nextcloud app and therefore cannot backup files located there.  Choose: Create new custom folder, choose local folder, navigate to android/data and directory is shown as empty.

### Describe the solution you'd like
Files in android/data can be selected from within the app.

This is an issue with Android 11 and the storage policy but I believe cloud sync apps and file manager apps are able to gain approval to access this location.

**Comment by joshtrichards** [comment]
Related: #9988

**Comment by joshtrichards** [comment]
Duplicate of #9988
