### ISSUE TITLE
.Calendar-Backup ?

### ISSUE THREAD

**Issue by tamis-laan** [nextcloud/android#8673]
Currently the NC android app does an automatic backup of your contacts. Just wondering why not backup the users calendar also? This would be a great feature to have :-)

**Comment by AndyScherzinger** [comment]
@tamis-laan why would you backup a calendar? (out of interest). If synchronization is the use case then please check out davx5: https://play.google.com/store/apps/details?id=at.bitfire.davdroid or https://f-droid.org/de/packages/at.bitfire.davdroid/

**Comment by tamis-laan** [comment]
Well two reasons:
1. Not all calendars are hosted by Nextcloud and could even be local to the device.
2. If my Nextcloud server breaks down, the data is corrupted or my house burns down, then I have a backup on all devices that sync data (nextcloud android and nextcloud desktop) including my calendar.

**Comment by AndyScherzinger** [comment]
Did you search of any application which might support scheduled exports (+ backup to some service e.g. via WebDAV)?

**Comment by tamis-laan** [comment]
> Did you search of any application which might support scheduled exports (+ backup to some service e.g. via WebDAV)?

I'm sure it's possible to hack together something. But I think this should be part of the core functionality. This way all data: folders, contacts and calendar are backed up across multiple devices: mobile, laptop, desktop and server.

**Comment by Discostu36** [comment]
This feature is now implemented.

**Comment by tamis-laan** [comment]
> This feature is now implemented.

That's great!!!
