### ISSUE TITLE
Garbage characters

### ISSUE THREAD

**Issue by simonaaba** [nextcloud/android#8674]
![image](https://user-images.githubusercontent.com/10238686/124734566-d5f1d580-df47-11eb-9f29-d315f112ea14.png)
![image](https://user-images.githubusercontent.com/10238686/124734608-ddb17a00-df47-11eb-95b5-1752bc67fa52.png)
![image](https://user-images.githubusercontent.com/10238686/124734666-ef931d00-df47-11eb-9070-865e5985196f.png)
this problem occurs time after time ,how to resolve it?

**Comment by tobiasKaminsky** [comment]
This is from auto generated code (databinding).
I never saw this before. 
Can you do a "build" -> "clean project"?

**Comment by simonaaba** [comment]
thank you for reply,i did "clean project " and "file" -> "invalidate caches / Restart",It didn't work .
Android studio vsersion is 4.2.2 ,kotlin_version from 1.4.32 to 1.5.20 all didn't work
