### ISSUE TITLE
3.17.0 RC1: Internal links from talk do not navigate to file

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/android#8675]
Oneplus 7T und 5T

![image](https://user-images.githubusercontent.com/24530680/125114007-b0043680-e0e9-11eb-93bd-e38779b2b6b0.png)

**Comment by szaimen** [comment]
I can reproduce that unfortunately.
cc @ezaquarii any idea what changed regarding this feature?

**Comment by ezaquarii** [comment]
@szaimen 
Nothing. [`DeepLinkHandler`](https://github.com/nextcloud/android/blob/247d422b3748f0c2b6ea270bdf3613dba0abe6cc/src/main/java/com/nextcloud/client/files/DeepLinkHandler.kt#L33) haven't changed for a year.

Looking at the code path, 2 things can go wrong there:
1) link might not match the regular expression
2) user ID could be invalid

@jakobroehrl Any chance you could generate a test link for us and share full URL with us?

**Comment by ezaquarii** [comment]
This 207 is not coming from `DeepLinkHandler`, but probably from one of the `RemoteOperation` things.
207 means multi-status. This in turn means that it would be appropriate to investigate the real response.

If you can reproduce it, I'd trace the failing operation, put a breakpoint there and investigate the body.

**Comment by szaimen** [comment]
@ezaquarii Thanks for the respond! Are you missing the steps how to reproduce the issue?

**Comment by ezaquarii** [comment]
@szaimen I don't use Talk.

**Comment by szaimen** [comment]
Okay, but the same issue also appears if you open an internal link that you've copied from the Nextcloud Android (not talk) app or web interface...

**Comment by jakobroehrl** [comment]
> @jakobroehrl Any chance you could generate a test link for us and share full URL with us?

@ezaquarii This is on every internal link. Tested with 2 different servers. If I install the old android version it's working again. 
It a example link could help, I can send one.

**Comment by szaimen** [comment]
cc @tobiasKaminsky @AndyScherzinger

**Comment by jakobroehrl** [comment]
fixed with 3.17.0 RC2

**Comment by AndyScherzinger** [comment]
Interesting... Did you fix anthing related to this issue @tobiasKaminsky ?
