### ISSUE TITLE
3.17.0 RC1: Video doesn't stop when minimizing the app

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/android#8677]
Oneplus 7T und 5T
It playes in Background, I can head the sound until I kill the nextcloud Appp

**Comment by jakobroehrl** [comment]
Not fixed with 3.17.0 RC2

**Comment by XueSheng-GIT** [comment]
Updated to 3.18.1 RC2. Video plays when app is minimized. When opening the app again audio is played twice (stream seems to get started again in background. Same happens when fullscreen playback is enabled and disabled again.
For me the internal player is unusable.

**Comment by jakobroehrl** [comment]
In the file view the video time slider is not shown, in the medien view it's working:
![image](https://user-images.githubusercontent.com/24530680/146333078-9b053acf-febd-4cb3-bce7-097198678777.png)
