### ISSUE TITLE
 Android 11 adapter for access to `/android/data`

### ISSUE THREAD

**Issue by moshengrenzenme** [nextcloud/android#8681]
### Is your feature request related to a problem? Please describe.
Android 11 permission problem, Android/data/ directory can't be accessed, I hope you can add an adapter

### Additional context

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by joshtrichards** [comment]
Duplicate of #9988
