### ISSUE TITLE
DCO keeps failing to due invalid email

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#8694]
See
https://github.com/nextcloud/android/commit/1d563cd69e5d4e98f40b8793ba8e40abe0dd0596

We still seem to use the "wrong" user/email when commiting/pushing code check scores, even though the code sets a local config (which seems to not work or is somehow ignored, maybe due to the input parameter git_user?)

**Comment by AlvaroBrey** [comment]
Fixed by #9098
