### ISSUE TITLE
Download notification/progress bar stays at 67%

### ISSUE THREAD

**Issue by user23498723452** [nextcloud/android#8695]
This may be a duplicate of issue/bug #8651, but I'm reporting it as it isn't identical.  And the fix is in a non-release version not yet available for download.

My example file is 299Kb in size.

### Steps to reproduce
1. Synchronize a file (e.g. .md) on device (green check-mark on the file in the Nextcloud App).
2. Change the file on your computer or in the Nextcloud Web-Interface.
3. Nextcloud App automatically synchronizes the file and the download indicator/notification stays at 67% (and doesn't disappear) until another synchronized file is changed off-device and synchronized or the App is stopped via the App-Info menu.
    
    
### Expected behavior
- The download notification should disappear as soon as the file is synchronized.

### Actual behavior
- The download notification stays in the pull-down notification bar.  
- The notification disappears if you stop the app from the App-Info menu or a different file gets changed off device and is synchronized.

### Can you reproduce this problem on https://try.nextcloud.com?
- Didn't try

### Environment data
Android version: 11

Device model: Google Pixel 4

Stock or customized system: Stock

Nextcloud app version: 3.16.1

Nextcloud server version: 20.0.11

Reverse proxy: n/a

**Comment by tobiasKaminsky** [comment]
Can you check latest 3.17.0 RC2?

**Comment by user23498723452** [comment]
I'm testing now.  Its unclear if its working better. I am now noticing a Red error icon on the file after it should sync (automatically),  but I never go inspect this.  It just auto-updates the file for me usually.
I will need to monitor for another few days to see if it is fixed.
