### ISSUE TITLE
Android app crashes after selecting folders to auto-upload

### ISSUE THREAD

**Issue by diogocardoso28** [nextcloud/android#8699]
************ CAUSE OF ERROR ************
Now the the app only freezes/crashes on wifi, on mobile data it works fine.
Here's what the app produced 
![image](https://user-images.githubusercontent.com/65686179/126061869-3458f200-62f5-4fbc-9b23-be63801c88c6.png)
Edit 2:
Now the app also crashes in mobile data. 

### Steps to reproduce
1.  Select camera folders to auto upload
2.  Wait for them to load
3.  Try re opening the app

### Expected behaviour
- Whilst on background activity the pictures and videos should keep uploading and the app should work normally

### Actual behaviour
- App doesn´t open and crashes randomly, also the file upload stops

### Can you reproduce this problem on https://try.nextcloud.com?
- Not sure can´t add another account since my app crashes

### Environment data
Android version:
11 
Device model: 
Samsung Galaxy s10+
Stock or customized system:
Samsung ONE UI 3.1
Nextcloud app version:
3.16.1
Nextcloud server version:
21.03
Reverse proxy:
NGINX 
#### Web server error log
```
Doesn't show anything from an android connection
```

#### Nextcloud log (data/nextcloud.log)
```
Also nothing shows up here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by strugee** [comment]
Is the crash consistent or does it happen randomly? Please include the debug information produced by the app when it crashes (it includes the text `************ CAUSE OF ERROR ************` at the top).

**Comment by diogocardoso28** [comment]
> Is the crash consistent or does it happen randomly? Please include the debug information produced by the app when it crashes (it includes the text `************ CAUSE OF ERROR ************` at the top).
Done that, thanks!

**Comment by strugee** [comment]
@diogocardoso28 thanks for editing. Is that the whole thing? Can you copy and paste instead of taking a screenshot?

**Comment by diogocardoso28** [comment]
@strugee It's not letting me copy, what I could do instead is paste here my logcat output if you prefer.

**Comment by AndyScherzinger** [comment]
@diogocardoso28 the whole thing should already be auto-copied to your clipboard :)

**Comment by diogocardoso28** [comment]
Not shure but its not going to clipboard so here's the logcat error output (using LogCatch)
`7-19 20:18:52.793  1018 19821 E ActivityManager: ANR in com.nextcloud.client
07-19 20:18:52.793  1018 19821 E ActivityManager: Reason: executing service com.nextcloud.client/androidx.work.impl.background.systemjob.SystemJobService
07-19 20:18:52.793  1018 19821 E ActivityManager:   124% 18683/com.nextcloud.client: 96% user + 27% kernel / faults: 4939 minor 1 major
07-19 20:18:52.793  1018 19821 E ActivityManager:   125% 18683/com.nextcloud.client: 100% user + 25% kernel / faults: 76 minor
07-19 20:18:54.100  1018  4076 E NotificationService: Package enqueue rate is 7.4891734. Shedding 0|com.nextcloud.client|411|null|10593. package=com.nextcloud.client
07-19 20:18:59.347  1018  1064 E NotificationService: Package enqueue rate is 6.9582334. Shedding 0|com.nextcloud.client|411|null|10593. package=com.nextcloud.client
07-19 20:19:01.355   629  2361 E BufferQueueProducer: [Application Not Responding: com.nextcloud.client#0](id:275000036b5,api:0,p:-1,c:629) disconnect: not connected (req=1)
07-19 20:19:04.392  1018  1064 E NotificationService: Package enqueue rate is 5.416999. Shedding 0|com.nextcloud.client|411|null|10593. package=com.nextcloud.client
07-19 20:19:09.617  1018  1064 E NotificationService: Package enqueue rate is 5.5385623. Shedding 0|com.nextcloud.client|411|null|10593. package=com.nextcloud.client
07-19 20:19:14.638  1018  1064 E NotificationService: Package enqueue rate is 5.0241776. Shedding 0|com.nextcloud.client|411|null|10593. package=com.nextcloud.client
07-19 20:19:19.701  1018  1064 E NotificationService: Package enqueue rate is 8.208579. Shedding 0|com.nextcloud.client|411|null|10593. package=com.nextcloud.client
07-19 20:19:24.819  1018  1018 E NotificationService: Package enqueue rate is 5.0341597. Shedding 0|com.nextcloud.client|411|null|10593. package=com.nextcloud.client
07-19 20:19:29.943  1018  1064 E NotificationService: Package enqueue rate is 6.014574. Shedding 0|com.nextcloud.client|411|null|10593. package=com.nextcloud.client
07-19 20:19:35.686  1018  1064 E NotificationService: Package enqueue rate is 5.177932. Shedding 0|com.nextcloud.client|411|null|10593. package=com.nextcloud.client
07-19 20:19:39.602  1018 21583 E ActivityManager: ANR in com.nextcloud.client
07-19 20:19:39.602  1018 21583 E ActivityManager: Reason: executing service com.nextcloud.client/androidx.work.impl.background.systemjob.SystemJobService
07-19 20:19:39.602  1018 21583 E ActivityManager:   47% 18683/com.nextcloud.client: 32% user + 15% kernel / faults: 5009 minor 37 major
07-19 20:19:39.602  1018 21583 E ActivityManager:   111% 18683/com.nextcloud.client: 72% user + 39% kernel / faults: 62 minor
07-19 20:19:40.689  1018  1064 E NotificationService: Package enqueue rate is 6.3113513. Shedding 0|com.nextcloud.client|411|null|10593. package=com.nextcloud.client
07-19 20:19:44.131   629  2361 E BufferQueueProducer: [Application Not Responding: com.nextcloud.client#0](id:275000036ba,api:0,p:-1,c:629) disconnect: not connected (req=1)
07-19 20:20:27.561  2749 23766 E pageboostd: active launch start : app comnextcloudclient
07-19 20:20:27.621  2749 23766 E pageboostd: comnextcloudclient, amt 20491712 scnt 3 fcnt 0
07-19 20:20:27.621  2749 23766 E pageboostd: active launch end : app comnextcloudclient data_amount 20491712
07-19 20:20:27.621  2749 23766 E pageboostd: active launch halted comnextcloudclient
07-19 20:20:36.815  1018  1064 E NotificationService: Package enqueue rate is 5.107662. Shedding 0|com.nextcloud.client|411|null|10593. package=com.nextcloud.client
07-19 20:20:41.843  1018  1064 E NotificationService: Package enqueue rate is 5.998596. Shedding 0|com.nextcloud.client|411|null|10593. package=com.nextcloud.client
07-19 20:20:46.883  1018  1064 E NotificationService: Package enqueue rate is 6.823625. Shedding 0|com.nextcloud.client|411|null|10593. package=com.nextcloud.client
07-19 20:20:51.897  1018  1064 E NotificationService: Package enqueue rate is 7.2005997. Shedding 0|com.nextcloud.client|411|null|10593. package=com.nextcloud.client
07-19 20:20:57.107  1018  1018 E NotificationService: Package enqueue rate is 5.1184244. Shedding 0|com.nextcloud.client|411|null|10593. package=com.nextcloud.client
07-19 20:21:02.134  1018  1064 E NotificationService: Package enqueue rate is 12.613048. Shedding 0|com.nextcloud.client|411|null|10593. package=com.nextcloud.client
07-19 20:21:07.135  1018  1064 E NotificationService: Package enqueue rate is 26.62947. Shedding 0|com.nextcloud.client|411|null|10593. package=com.nextcloud.client
07-19 20:21:12.144  1018  1064 E NotificationService: Package enqueue rate is 14.361805. Shedding 0|com.nextcloud.client|411|null|10593. package=com.nextcloud.client
07-19 20:21:17.145  1018  1064 E NotificationService: Package enqueue rate is 6.680434. Shedding 0|com.nextcloud.client|411|null|10593. package=com.nextcloud.client
07-19 20:21:22.153  1018  1064 E NotificationService: Package enqueue rate is 5.2470236. Shedding 0|com.nextcloud.client|411|null|10593. package=com.nextcloud.client
07-19 20:21:27.181  1018  1064 E NotificationService: Package enqueue rate is 12.274792. Shedding 0|com.nextcloud.client|411|null|10593. package=com.nextcloud.client
07-19 20:21:32.187  1018  1064 E NotificationService: Package enqueue rate is 7.4192495. Shedding 0|com.nextcloud.client|411|null|10593. package=com.nextcloud.client`

**Comment by AndyScherzinger** [comment]
Ah, my mistake, the app didn't crash but hit an ANR (application not responding) which is likely due to auto upload of many (existing) files which leads to very long processing times to queue all the files :/

Does the folder you added for auto upload on your device contain many files? Or how many does it contain?

**Comment by diogocardoso28** [comment]
![Screenshot_20210718-094617_Nextcloud.jpg](https://user-images.githubusercontent.com/65686179/126220340-659078fb-dd12-4cbf-ac2c-c3456ca6e8fc.jpg)
Around 10k (3 or 4 folders), but all have failed by now 🤔

**Comment by diogocardoso28** [comment]
Any sugestions on how to fix this?

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky any ideas? Having that many files in the queue could one simply restart the uploads and they'd be done via async background workers and not lad to a ANR scenario?

**Comment by ukrolelo** [comment]
Same situation i have reinstalled the app and the uploads started to work. But it is not uploading old photos :-/ total 6K of them

**Comment by diogocardoso28** [comment]
Any updates on this issue ?

**Comment by diogocardoso28** [comment]
@ukrolelo Is it still going? Yesterday mine did the same thing uploaded for a while and then stopped. Not sure what caused it to start/stop :/. Weird behavior.

**Comment by ukrolelo** [comment]
> @ukrolelo Is it still going? 
Same situation!
Will see in the evening when i put on charger.
For now i have 48.5GB from 65.05GB
I guess some old stuff cant be copied,or it is taking so long idk...

**Comment by diogocardoso28** [comment]
@ukrolelo Mine uploaded like 300 files and failed, prob around 3/4 gb

**Comment by ukrolelo** [comment]
I have it for 2weeks. I thought its finished already. But definetly there is a problem.
Till it is fixed im using syncthing also. It is working without any problem. Its just by usability the nextcloud is better that i can share home videos with the whole family.

**Comment by diogocardoso28** [comment]
@ukrolelo so you use syncthing to upload to nextcloud?

**Comment by ukrolelo** [comment]
No, i have it as seperate instance in seperate server.
It does not have any connection between. Just as a backup for the time that nextcloud doesnt work.
BUT! I gave me a good idea xD thank you! ))))))

**Comment by diogocardoso28** [comment]
@ukrolelo I mean any webdav client should do the trick to handle the upload right?

**Comment by diogocardoso28** [comment]
@ukrolelo Found this app that supports nextcloud, will see how this turns out

![Screenshot_20210804-112830_Google Play Store.jpg](https://user-images.githubusercontent.com/65686179/128166248-f732514a-f3ad-491e-8df2-fd1129a25e02.jpg)

**Comment by ukrolelo** [comment]
Thx for link.
Actually i can just make an smb share and put it inside. That should work just fine. Doesnt need any fancy apis )))

**Comment by diogocardoso28** [comment]
@ukrolelo wont nextcloud be "confused" bc the files are not present in the database, or it autoscans every x amount of time?

**Comment by ukrolelo** [comment]
Let me try xD

**Comment by diogocardoso28** [comment]
@ukrolelo here, rede this, not shure if it has changed since then :) 
https://help.nextcloud.com/t/nextcloud-folder-shared-via-samba/9907
What I do remember is reading on a forum that a guy was running a cron with an occ command to scan the folder and update db ;)

**Comment by diogocardoso28** [comment]
@ukrolelo  on the other hand folderSync its working like a charm on a pretty big folder 2k+ images 

![Screenshot_20210804-114102_FolderSync.jpg](https://user-images.githubusercontent.com/65686179/128167773-ebe66821-0a33-422e-8f86-01e917162983.jpg)

**Comment by ukrolelo** [comment]
@diogocardoso28 
You are correct.
Will check after some time if it does some magic by it self

**Comment by ukrolelo** [comment]
> @ukrolelo  on the other hand folderSync its working like a charm on a pretty big folder 2k+ images 
> 
> ![Screenshot_20210804-114102_FolderSync.jpg](https://user-images.githubusercontent.com/65686179/128167773-ebe66821-0a33-422e-8f86-01e917162983.jpg)

Waw thank you! Will try!!!

**Comment by diogocardoso28** [comment]
@ukrolelo if the magic doesn't happen by itself everyday at midnight or something you could run the occ files:scan to put everything where it should in the database, might be a little too resource intensive but shouldn't matter since its happening night time and will get the job done :)

**Comment by ukrolelo** [comment]
I would love to avoid any additional programmong scans crons )) life is to complicated.i am now tryong to minimize all the stuff that i am working on. Too much. So it mist be simple and straightforward right away. I will try next week the foldersync that is integrated woth nextcloud )))

**Comment by diogocardoso28** [comment]
@ukrolelo agreed! 🤣🤣

I will update you on the folder sync app as the week goes by :D

**Comment by diogocardoso28** [comment]
@ukrolelo off topic question, what hardware are you using?

**Comment by ukrolelo** [comment]
@diogocardoso28 
1server
Mid tower some old intel, 1xssd for host os, 1x ssd for vms, 6x4TB for data raidz2
Proxmox 6vms

2server
Miniatx some intel 11gen cpu
1x ssd host os and vms, 1x8TBhdd for data.
1x pci with google coral AI
For AI video surveilance Home assistant+Frigate
Proxmox 2vms 2containers

They are cross backuping ich other essential data for recovery,in case of data lost

**Comment by diogocardoso28** [comment]
@ukrolelo That's kind of what I'm running, just on much lower specs 😢 (for now at least ). Best of luck with your servers 🤞

**Comment by ukrolelo** [comment]
@diogocardoso28 thx! :) U2!

**Comment by diogocardoso28** [comment]
@ukrolelo Folder Sync update!! I have successfully uploaded 3k + files and selected folders with 2k + images and videos and no hickups yet, only syncs a folder at a time though but gets the job done. I will keep using this app untill nextcloud app gets fixed 👍.
