### ISSUE TITLE
3.17.0 RC2: Media view issues

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/android#8702]
1. Watch a video and go back, now the title bar has the foldername and the pics on the top are covered
2. Sharing is not possible. It says: "sharing is not allowed", but I can share the same file in the file view of the app
3. there is no possibity to share/send pics. In the file view it works
4. Sometimes all photos and videos are twice shown and sometimes all the videos are mission after watching a video and go back to the media view

Oneplus 7T und 5T

**Comment by AlvaroBrey** [comment]
Should be fixed in latest versions due to big overhaul of media screen.
