### ISSUE TITLE
Only "shared with others"

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#873]
Currently we have only "shared with others".
To have the same as the webUI we should add
- rename "shared" to "shared with others"
- add "shared with you"
- add "shared by link"

The drawer is getting quite full/long...
Something like that for the whole share section: expandable section in item4:
![grafik](https://cloud.githubusercontent.com/assets/5836855/25280315/ce10f324-26a9-11e7-933b-272bff695db2.png)
https://stackoverflow.com/questions/22656081/how-to-create-drawer-navigation-like-this

@mario @AndyScherzinger 
for design: @jancborchardt @eppfel

**Comment by jancborchardt** [comment]
To be quite honest I’m not happy how we did it in the web interface – it’s too many entries. Most of the time you want to simply see what’s shared, and that’s why the sidebar entry should simply be called »Shared« and list all shares, be it from others, to others, or by link.

In the future we can think about some kind of tabbed control or submenu to filter that, but we should keep it simple first.

cc @nextcloud/sharing

**Comment by tobiasKaminsky** [comment]
> In the future we can think about some kind of tabbed control or submenu to filter that

That's why I thought of this expandable navigation ;-)

**Comment by mario** [comment]
I'd go with just "Shared" too. No expandable stuff.

**Comment by jancborchardt** [comment]
> That's why I thought of this expandable navigation ;-)

Yeah I know, and it's a good idea. :)

This is about the first step though, and since we're on mobile where people are busy with other things, we should definitely have one simple "Shared" view.
(Not having it is what I currently consider a shortcoming of the server, but we can improve. :)

**Comment by tobiasKaminsky** [comment]
Conclusion is then:
- rename to "shared" --> showing all shares directly
- use expandable navigation drawer to show 
  - shared with others 
  - shared with you
  - shared by link

(this way we have it the same like in web UI, according to https://github.com/nextcloud/server/issues/4448)

**Comment by tobiasKaminsky** [comment]
Another way is to use a dropdown menu in the "shared view" to "filter", similar to this:
![filentxojn](https://cloud.githubusercontent.com/assets/5836855/25324032/a8d17798-28c3-11e7-8f99-57e8b81cca2a.png)

![fileaxbibc](https://cloud.githubusercontent.com/assets/5836855/25324033/a8d96098-28c3-11e7-935d-e7c8f3e3908d.png)

**Comment by jancborchardt** [comment]
@tobiasKaminsky just saw this now: Let’s definitely use the solution with »Shared« showing all, and then in the future expandable navigation. But not in the header, that’s a bit strange and doesn’t reflect how we do it in the server. (also cause that usually shows the parent folders)

**Comment by tobiasKaminsky** [comment]
Closing in favor of https://github.com/nextcloud/android/issues/5301
