### ISSUE TITLE
Could andriod App support multiple files upload?

### ISSUE THREAD

**Issue by nanjunyu** [nextcloud/android#8743]
When I synchronize my photots between nextCloud, I found the photos can only be upload one by one.  Could andriod App support multiple files upload?

**Comment by mnalis** [comment]
see also https://github.com/nextcloud/android/issues/10937

**Comment by joshtrichards** [comment]
@nanjunyu Are you referring to sharing files to/from other apps or to the ability for the NC client while uploading to your NC server to make multiple parallel connections for performance reasons?

**Comment by joshtrichards** [comment]
Closing due to no clarification received after almost a year. Presumably this is referring to #10937 or similar.
