### ISSUE TITLE
Re-design icons in add button/menu ("+")

### ISSUE THREAD

**Issue by spectas** [nextcloud/android#875]
Hello everybody,

first of all, thank you for this great software suite!

Right now the add-button opens a menu with icons, which is imho not self explaining. The upper two symbols (upload file and upload from external app) would also fit the other way around. You have to do try and error to know, which one is what for:
![image1563907354](https://cloud.githubusercontent.com/assets/3306424/25313532/9d04bf94-2830-11e7-9ab3-542495447c01.jpg)
What I would suggest is to take the same icon twice, only with a small difference. I am not a designer, so sorry for the quality of this small gimp project. But perhaps something like this:
![image1563907354-edit](https://cloud.githubusercontent.com/assets/3306424/25313563/09e8b39a-2831-11e7-9b6e-ad84dc857f44.jpg)
Imho it would be clearer, as it is something people know from the differentiation between "open" and "open with" buttons.

Thanks and greetings,
Spectas

**Comment by jancborchardt** [comment]
Hey @spectas! :)

> Right now the add-button opens a menu with icons, which is imho not self explaining.

Te first time that menu is opened, it should show with text. Maybe we should show that text always to be completely clear also to people who don't use the app that often. :)

I think the icons are well-chosen. Upload, Open from, Create folder.

**Comment by tobiasKaminsky** [comment]
If there is no explanation you still can long press on the FAB to get a description.
