### ISSUE TITLE
Add app title to webview welcome pages

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/android#876]
In the header of the webview welcome pages (see https://github.com/nextcloud/android/pull/827) the app name should be in the header, centered, to give context.

In the usual case simply "Nextcloud", or the relevant name if branded.

**Comment by mario** [comment]
Android apps do not have the title centered. While we can add the header for sure, I vote against having it centered.

cc @AndyScherzinger @tobiasKaminsky

**Comment by AndyScherzinger** [comment]
I agree with @mario to set the title "the Android way" which would be left aligned next to the drawer/back icon like on all other screens. My guess would be the centered idea came from the iOS context ;)

**Comment by jancborchardt** [comment]
Ok, left-aligned is fine too. :)
