### ISSUE TITLE
Create new text file from within NC

### ISSUE THREAD

**Issue by spectas** [nextcloud/android#877]
Hi everybody and thank your for this app!

What I am missing is a simple way to create a new text file from within the NC app.

If you want to do it today, there are severals steps necessary:
- open your favorite text editor, write text and save it to a new local file
- open NC app, navigate to the destination folder
- click on "add" buttton ("+") at the bottom right
- click on the first upload button
- navigate through your local files and select the desired text file
- choose "move to next cloud" and click on "upload"

What I would suggest is to add a "add text file" button to this small menu (sorry for my bad gimp skills):
![image1563907354-445](https://cloud.githubusercontent.com/assets/3306424/25313696/f2ae1780-2833-11e7-957e-0870f46bf9d1.jpg)
Thanks! Spectas

**Comment by joshtrichards** [comment]
Unless I'm mistaken this is fully implemented today and this issue just got left open.
