### ISSUE TITLE
andoid app crashes when nextcloud server is destoryed

### ISSUE THREAD

**Issue by rtisma** [nextcloud/android#8772]
### Steps to reproduce
1. Create nextcloud server
2. Connect android app to it
3. Destroy nextcloud server
4. Go back to the app and it crashes with NPE.

### Expected behaviour
- should invalidate any sessions and go back to login scree 

### Actual behaviour
- just crashes

### Can you reproduce this problem on https://try
No

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
@rtisma thaqnks for the report, could you post the crash report that should be copied to your clipboard? That would help us a lot. Thanks in advance and also thanks for your efforts in reporting this!
