### ISSUE TITLE
Auto upload uploads the same file several times

### ISSUE THREAD

**Issue by fracklaus** [nextcloud/android#8773]
### Steps to reproduce
1. Setup nextcloud server and connect android client
2. Enable auto upload for a folder. Set upload only while charging.
3. Disconnect power
3. Create a file in the auto upload folder. Modify it several times (for me this is a GPS logger constantly updating a gpx file)
4. Check "uploads" in nextcloud app. File is scheduled for upload several times
5. Connect charger
6. Experience the same file being uploaded multiple times

### Expected behaviour
- File should only be uploaded once

### Actual behaviour
- Same file is uploaded multiple times

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 11

Device model: Galaxy S21

Stock or customized system:Stock

Nextcloud app version: 3.16.1

Nextcloud server version: 21.0.3.1

Reverse proxy: 

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AlvaroBrey** [comment]
This is configurable in the autoupload settings for each folder. See image below.


![image](https://user-images.githubusercontent.com/8677743/177727755-6fe41bc7-182b-4d17-a9f8-841a85acb50a.png)

**Comment by major-mayer** [comment]
I don't think this will fix the problem.
If the file doesn't change, it shouldn't be uploaded again, even if "Rename new version"  is activated.
I switched to "skip uploading" now and will monitor if this happens again.

**Comment by AlvaroBrey** [comment]
> I don't think this will fix the problem. If the file doesn't change, it shouldn't be uploaded again, even if "Rename new version" is activated. I switched to "skip uploading" now and will monitor if this happens again.

The original issue was about a file being modified several times, not an unchanged file. Are you sure all of your signal backups are identical? If so please open another issue
