### ISSUE TITLE
Video Preview in the Android App extremly slow

### ISSUE THREAD

**Issue by MrLoverLoverMMMM** [nextcloud/android#8777]
+ Steam with the android app very very slow. It seems it needs to download everything to get the video playing. It does not stream like in the web client.

**Comment by tobiasKaminsky** [comment]
Which version do you use?
We enhanced this recenty with 3.17.

**Comment by MrLoverLoverMMMM** [comment]
Hello!Yes its works bettet with the current version, but with videos its still slow.I use Version: 3.17.0 and latest server 21.0.4Best regardsPatrick
-------- Ursprüngliche Nachricht --------Von: Tobias Kaminsky ***@***.***> Datum: 30.08.21  08:22  (GMT+01:00) An: nextcloud/android ***@***.***> Cc: MrLoverLoverMMMM ***@***.***>, Author ***@***.***> Betreff: Re: [nextcloud/android] Video Preview in the Android App extremly
  slow (#8777) 
Which version do you use?
We enhanced this recenty with 3.17.
