### ISSUE TITLE
Uploading shows when not on WiFi 

### ISSUE THREAD

**Issue by iptvcld** [nextcloud/android#8794]
When I have my andriod Nextcloud app set to auto upload on WiFi and while charging. When I take a pic why does it say uploading on the andriod status bar? Then when I go into NC under the upload tab it still says waiting for Ac. But just don't get why showing uploading. And if on airplane mode and take a pic it shows connection error..

**Comment by markginter31** [comment]
I also see this same behavior.

**Comment by fto77533** [comment]
Go to the browser and at the top of the list with the bio betrayer click and go to download press the download button un download via Wi-Fi

**Comment by joshtrichards** [comment]
Can't reproduce this any longer. I recall this being the case a bit back, but it was fixed at some point along the way. Re-open if the notification re-appears while it's still waiting for a charge or wifi.
