### ISSUE TITLE
Enhance contacts backup

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#880]
To enable contacts backup in public version some points needs to be discussed
(this was a customer feature and we want to have it also in regular version)

- [x] support multiple accounts
- [x] where to put it
  - settings is not the best place (as @mario pointed out) as it is an account specific setting (same for davdroid)
  - navigation drawer is somehow a too prominent place
- more explanation / config
  - [x] change target folder
  - [x] show current target folder
  - [x] explain that backup is done once a day
  - [x] custom deletion of old backups (currently disabled, should be adjustable?)
  
![filezskujf](https://cloud.githubusercontent.com/assets/5836855/25325359/7e9da1ba-28cb-11e7-8478-9995b1d95a27.png)

@mario @jancborchardt @eppfel

**Comment by eppfel** [comment]
You Android contacts are not nextcloud-account specific. So, it could be in the settings as long as you can selected the cloud to store it in, right?

**Comment by mario** [comment]
@eppfel what if you wanted it stored in multiple accounts? There's also a checkbox-based approach to that - sure, but do we want to go that way and hide things like Contacts backup inside settings?

What about this:

- keep it in the drawer, but in the "global" part of it (before settings)
- either directly in the backup screen have an "Accounts to backup to" section either below it all, or hidden behind a cog

Thoughts?

**Comment by eppfel** [comment]
> hide things like Contacts backup inside settings?

Sry, but for what else are the settings good then? A backup is something for the background or do you expect users to use this feature on a weekly basis???

And the drawer is already pretty crammed... I don't object it generally, I just give my thoughts.

**Comment by tobiasKaminsky** [comment]
I vote also for putting it into settings and then have an account chooser (multi select) in contacts backup settings. We wanted to do it this way for instant upload, so I guess it is also a good approach for this case.

**Comment by tobiasKaminsky** [comment]
@jancborchardt @eppfel we want to get this in 1.5.0 which is soon to be released.
What do you think needs to be changed UI/UV wise?
Please see and answer to the bullet points above.

**Comment by jancborchardt** [comment]
Agree it should be in the settings with an account chooser.

A confusion which arises from the current screeshot above is: What’s the difference between checking the »Contacts backup« radio control to on, and clicking »Back up now«?

**Comment by tobiasKaminsky** [comment]
Contacts backup is a periodic (once a day) job which automatically backups the contacts.

**Comment by jancborchardt** [comment]
Ok, then the wording should be »Automatic backup«. »Contacts backup« is already in the header.

And the buttons below could be in one row (if possible), left »Back up now« and right »Restore from date«. Only »Back up now« should be a primary/colored button. No need for the extra »Restore« header cause it should be part of the button label. :)

**Comment by eppfel** [comment]
How easy would it be to give some info, about the existing backups.
"last backup 13:25"
"oldest backup 01.04.17"

?

**Comment by tobiasKaminsky** [comment]
You will see this if you click "restore": then a date picker opens with the all available dates marked.

**Comment by tobiasKaminsky** [comment]
![filexjwcxy](https://cloud.githubusercontent.com/assets/5836855/26244409/c7a6498e-3c8f-11e7-8814-4670c9bdeb0d.png)

**Comment by tobiasKaminsky** [comment]
@jancborchardt @eppfel any idea (UI) how and where to do the account switcher?
Should it be an switcher (only one account) or should upload to multiple accounts be possible (not yet implemented)?

It will only be shown if >1 account is set.

**Comment by tobiasKaminsky** [comment]
![fileiu96tz](https://cloud.githubusercontent.com/assets/5836855/26244782/a520840e-3c91-11e7-953a-5e14b4f077c4.png)

This is customizable and will only be shown if it not in the drawer, and vice vera.

**Comment by tobiasKaminsky** [comment]
I would like to remove the idea to change the target folder, @jancborchardt ?

**Comment by jancborchardt** [comment]
Nice!

- The blue header text "Backup" can be removed as its duplicate
- Wording on the entry and in the heading and in the button needs to be "Back up" with a space as it's the verb form and two separate words. "Backup" is the noun form. :) a backup / to back up
- Account switcher can be on the top in that view.

What do you mean with "I would like to remove the idea to change the target folder"? Just by default drop it into the root folder? Seems fine.

**Comment by tobiasKaminsky** [comment]
To get this done, how shall we handle multiple accounts? 
In auto upload this is done "invisible", e.g. when you enable a folder the current active account will be used for every upload, no matter what account you are currently using.
I want to do the same for this? The enabled/disabled state will be reflected to the current account:
- enable on account a
- switch to account b: turned off

**Comment by AndyScherzinger** [comment]
If done the same way, it would still have to work even when you switch to account b, while still uploading to account a simply because when activated it is tied to the account that is has been active during the time of activation and will stay active until deactivated, so account switching shouldn't have any effect.

**Comment by tobiasKaminsky** [comment]
Correct :+1: Just the same as in auto upload, right? :-)

**Comment by AndyScherzinger** [comment]
exactly 👍

**Comment by tobiasKaminsky** [comment]
This is already done as backupSwitch.setChecked(arbitraryDataProvider.getBooleanValue(account, PREFERENCE_CONTACTS_AUTOMATIC_BACKUP)); is account specific.

**Comment by tobiasKaminsky** [comment]
This is done in #1027
