### ISSUE TITLE
Autoupload conflict loop for screenshots folder

### ISSUE THREAD

**Issue by bjo81** [nextcloud/android#8816]
### Steps to reproduce
1. enable autoupload for the screenshots folder
2. create a screenshot

### Expected behaviour
* screenshot gets uploaded to the correct folder (/Screenhots)
* nothing else happens

### Actual behaviour
* screenshots get uploaded to the correct folder (/Screenhots)
* the app complains there is a conflict uploading the file to /Photos/2021/08/Screenshots
* nothing gets really uploaded to /Photos/2021/08/Screenshots

### Can you reproduce this problem on https://try.nextcloud.com?
* I think it's a client problem

### Environment data
Android version:
11
Device model: 
Redmi Note 7
Stock or customized system:
Lineage OS 18.1
Nextcloud app version:
3.17 RC2
Nextcloud server version:
 22.0.0
Reverse proxy:
nginx

#### Web server error log
nothing

#### Nextcloud log (data/nextcloud.log)
nothing related

**Comment by bjo81** [comment]
Additional observation: After creating a /Photos/2021/08/Screenshots folder, the screenshots get uploaded to /Screenshots and also to /Photos/2021/08/Screenshots (where there shouldn't be uploaded).

**Comment by AlvaroBrey** [comment]
Closing in favor of #9026 as that one has more info

**Comment by AlvaroBrey** [comment]
Duplicate of #9026
