### ISSUE TITLE
ExternalLink Improvement  

### ISSUE THREAD

**Issue by aleister09** [nextcloud/android#882]
### Actual behaviour
If the user open a external link without network the app shows a 404 WebPage 

### Expected behaviour
It would be nice that the app can load a custom error page instead of the 404 WebPage 

- The Error Page can be loaded from assets or raw 
- It can be the same to WebLogin and Welcome page 

### Steps to reproduce
1. Enable Airplane Mode
2. Open the app
3. Open an external link

### Environment data
Android version: 7.1.2

Device model: Nexus 5

Stock or customized system:

Nextcloud app version: Master

Nextcloud server version: 12

### Logs
![device-2017-04-24-113139](https://cloud.githubusercontent.com/assets/25756086/25349076/17a1151c-28e6-11e7-9931-a37f8b728d83.png)

**Comment by tobiasKaminsky** [comment]
@aleister09 please test it with your custom error html page.
