### ISSUE TITLE
Selected item in the top-left 3-LINE menu is too dark in the dark theme.

### ISSUE THREAD

**Issue by SuperdukeGates** [nextcloud/android#8826]
### Steps to reproduce
1. Tap 3-LINE menu and then tap the settings
2. Tap Theme and then tap the Dark
3. Back to main screen and then tap 3-LINE menu

### Expected behaviour
- Expecting that the selected item should be easier to read. That is it should use the lighter foreground color for the selected (highlighted) item.

### Actual behaviour
- You can see that the foreground color of the selected (highlighted) item is too dark to tell what is selcected.
- 
![scr01](https://user-images.githubusercontent.com/28051715/128627128-d6abd777-f127-4efe-9f2e-27051274627d.jpg)

### Can you reproduce this problem on https://try.nextcloud.com?
- If this is necessary for this issue, please tell me.

### Environment data
Android version: 10.0
Device model:  Nokia 5.1 Plus
Stock or customized system: Android One
Nextcloud app version: 3.16.1
Nextcloud server version: 22.0.0.11
Reverse proxy: None

#### Web server error log
No error
Insert your webserver log here
Not necessary

#### Nextcloud log (data/nextcloud.log)
Not necessary
Insert your Nextcloud log here
Not necessary

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AlvaroBrey** [comment]
@SuperdukeGates The active element should be colored with the primary color. Have you defined your server color as dark grey? If so, that's the reason.

Here's how it looks with default server colors:
![Screenshot_1646322761](https://user-images.githubusercontent.com/8677743/156601106-2aa84315-4351-497d-810c-e3452e8dd64a.png)
