### ISSUE TITLE
TLS 1.3 only don't working anymore with version 3.16.1

### ISSUE THREAD

**Issue by mickael067** [nextcloud/android#8835]
TLS 1.3 only don't working anymore with version `3.16.1`

I see the problem when I see errors with use "Contacts Backup" feature.

Don't working with apache option:
`SSLProtocol all -SSLv3 -TLSv1 -TLSv1.1 -TLSv1.2`
Working again with apache option:
`SSLProtocol all -SSLv3 -TLSv1 -TLSv1.1`

_Originally posted by @mickael067 in https://github.com/nextcloud/android/issues/8355#issuecomment-895201967_

**Comment by szaimen** [comment]
Which android version are you using and did you try if `SSLProtocol -all +TLSv1.3` works for you?

**Comment by mickael067** [comment]
Samsung Galaxy S9+ (SM-G965F) - Version` *UG4` - Android Q (Android 10)
App version `3.17.0` (new version, initial problem on `3.16.1`)
Server Version `21.0.4`

Test 1 : `Apache` with `SSLProtocol all -SSLv3 -TLSv1 -TLSv1.1`
Backup Contacts : Backup now ==> No issue

Test 2 : `Apache` with `SSLProtocol all -SSLv3 -TLSv1 -TLSv1.1 -TLSv1.2`
Backup Contacts : Backup now ==> No more issue

Test 3 : `Apache` with `SSLProtocol -all +TLSv1.3`
Backup Contacts : Backup now ==> No more issue

Thanks for the correction.

Remark : 

The version : `SSLProtocol -all +TLSv1.3`
allow only `TLSv1.3` it is good, but one day `TLSv1.4` (or others) come and will not be automatically included by an update.

I prefer the version : `SSLProtocol all -SSLv3 -TLSv1 -TLSv1.1 -TLSv1.2`
allows only `TLSv1.3` and future version of protocol.

**Comment by jannh** [comment]
I think I have to withdraw my previous comment. Tested again with Nextcloud 21.0.4 on Debian Bullseye (Nginx 1.18.0). Android 11 with Nextcloud App v3.17.0 . Using `ssl_protocols TLSv1.3;` I seem to have no more issues.

**Comment by tobiasKaminsky** [comment]
Do I understand correctly that this is fixed?
If not, please reply / re-open.
