### ISSUE TITLE
App crashes when returning to ui a day later

### ISSUE THREAD

**Issue by zell-mbc** [nextcloud/android#8840]
### Steps to reproduce
1. Start app, navigate to video stored locally
2. Watch the video
3. Dont close the video but keep on doing other stuff
4. return to ui to watch another video (in my case a day later)
5. ui is showing still of previous video but is unresponsive and crashes eventually

### Expected behaviour
- Either show the Filesystem or continue with the old video

### Actual behaviour
- App crashes when trying to continue to play the video

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
I'm using my tablet, will add these details later when at my PC
Android version: 

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AlvaroBrey** [comment]
This looks like a duplicate of #8686, since it's still media player related. Can you try to get some logs, or reproduce it with the steps defined in #8686? (Play a short MP3 file until it ends, and then hit Back)

**Comment by zell-mbc** [comment]
Things reliably crashed for a while until I finally decided to log an error, but ever since I haven't seen another one?
Maybe an update came along since, I can't remember. But given that things were working for a month now I think it's fair to close this issue for now. I can always reopen (with a proper log) in case it comes back again.
