### ISSUE TITLE
Download upload issues

### ISSUE THREAD

**Issue by ghost** [nextcloud/android#8843]
### Steps to reproduce
1. Try to download/upload
2.  If you left the app in bg task will failed
3. Or sometime  (especially when downloading) they can error without our interactions

### Expected behaviour
Those thingy should work

### Actual behaviour
App failed to download/upload

### Can you reproduce this problem on https://try.nextcloud.com?
- issues happend on android client apps :(

### Environment data
Android version: 10

Device model: Realme 5i

Stock or customized system: stock realme UI 1.0

Nextcloud app version: 3.16.1

Nextcloud server version:
How do i find nextcloud sv version?
Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

edit:
sorry for my offensive words it's removed 🙏
also this bug still exist in latest version of Nexcloud apps from f droid build
@nextcloud-android-bot

**Comment by gabrywu** [comment]
same issue

**Comment by joshtrichards** [comment]
What are the specific error messages you're seeing? Any stack traces?
