### ISSUE TITLE
End of longer text files not shown in built-in viewer

### ISSUE THREAD

**Issue by billie80** [nextcloud/android#8857]
### Steps to reproduce
1. Create a text file (within the Nextcloud App) which is also synchronised locally (otherwise it is not opened with the viewer). It has to contain some lines so scrolling is required to reach the bottom of the file.
![01_downloaded_text_file](https://user-images.githubusercontent.com/9938306/129438925-5730dfd2-1c34-4390-acc9-3fa3383f6480.png)
2. When opening the file in the viewer it is not possible to scroll to the very bottom of the file. Almost two lines are missing in the example below. Half of the penultimate line which contains a link is visible.
![02_bottom_viewer](https://user-images.githubusercontent.com/9938306/129439462-dade3720-3829-48ff-8818-bb17ef6129fb.png)
3. Strangely the end of the file can be reached when clicking the link to open it in a browser and afterwards returning to the Nextcloud App. It only works when the link is at the visible bottom.
![03_after_link](https://user-images.githubusercontent.com/9938306/129439463-faa6bb2f-8241-428e-9420-52eec30bb1ab.png)
4. When opening the link in the built-in editor there is no problem with accessing the end of the file.
![04_bottom_editor](https://user-images.githubusercontent.com/9938306/129439465-2269c463-1d7d-4f39-8327-bde27f470c08.png)

### Attachments
I tried to attach the test txt file but for some reason Github did not accept it. However it should not be difficult to recreate a similar file.

### Expected behaviour
- End of text files not visible in built-in viewer.

### Actual behaviour
- The complete file should be viewable.

### Environment data
Android version: 10
Device model: Shift6mq
Stock or customized system: Stock
Nextcloud app version: 3.16.1
Nextcloud server version: 20.0.11

**Comment by billie80** [comment]
Any news here? For some reason I don't see this in the list of my open issues.

**Comment by joshtrichards** [comment]
Hi @billie80 - I can't reproduce this behavior today. There have been a bunch of changes to the text file preview code since your report. Are you still experiencing this or can I close this out?

**Comment by billie80** [comment]
You are right. I can not reproduce with 3.26.0 either.
