### ISSUE TITLE
A lot problems with android app. Is it only me?

### ISSUE THREAD

**Issue by godfuture** [nextcloud/android#8860]
Hi,
there are quite a lot issues while (trying) to use the Nextcloud android app. To me it feels still beta.

1) Android sharing dialog navigation knows just back and forth. Only nextcloud app file upload dialog has a dropdown. The share dialog always starts where last sharing happened. This can help, or not at all. Why not always a quick way to switch path?
2) Navigation in app is sluggish. Folder sync pro is much quicker in navigation response time. Every click/tipp takes a few seconds.
3) Every file conflict gets an own android natification entry. Why? It feels so overboarding to wipe aways many conflicts. You ask yourself: why uploading files many times? Lets get to next point...
4) Uploading by share dialog is not always successful. I tried to upload 10 pics from last fridays party at the river. I noticed I have a duplicate on server after uploading (noticed by checking thumbnails), but overall number is correct...weird...this means one picture is missing, because one is doubled. Even reselecting all 10 pics in android gallery and sharing again did not correct the situation. The duplicate was never overwritten, or I never got 11 pics uploaded (10 + 1 dup). I deleted all and reuploaded again all 10 pictures. Then it worked. Is my case important? No, but it shows that the upload is still not 100% safely working.
5) Thumbnail loading is still a pita. I guess Nextcloud does not focus on that...I am a poor private user. This issue lives since...ever.

I would like to know your experience with android app. Is there someone using this app for private use and all the points above are working fine?

Server: 21.0.4
Android: 3.16.1

**Comment by storm1er** [comment]
Hi,

> 1. Android sharing dialog navigation knows just back and forth.

I do not have this problem, may be related to server configuration issue?

> 2. Navigation in app is sluggish.

Neither, it's quite slow when I'm loading a new folder (created from web) but everything else is fine.

> 3. Every file conflict gets an own android natification entry.

God damn it, I agree, this is frustrating AND useless :( 

> 4. Uploading by share dialog is not always successful.

Duh, that's weird :/ Never had the problem, uploads work or get conflicts when file already exists on my side.

> 5. Thumbnail loading is still a pita.

I use an app called "preview" which you can install easily. You need to install a line in a cron to ensure thumbnails are always up to date. https://apps.nextcloud.com/apps/previewgenerator
I wish this app would be native :/

**Comment by tobiasKaminsky** [comment]
Please open up separate issues for those problems, otherwise this will end up in one giant thread, where we loose focus :)

Some of your ideas / problems are already addressed here, so please check them and if possible add new information to them :)
