### ISSUE TITLE
App restarts when opening the AutoUpload Settings

### ISSUE THREAD

**Issue by loetermann** [nextcloud/android#8863]
### Steps to reproduce
1. Go to Settings, Auto Upload -> Works as expected
2. Enable Sync for a Folder with ~200 Files (upload of existing files even disabled)
3. Go back to Main Screen
4. Go to Settings, Auto Upload again -> Activity opens noticeably slower (~ 2 sec)
5. Enable Sync for a Folder with ~400 Files
6. Go back to Main Screen
7. Go to Setting, Auto Upload again -> App freezes for ~5 sec, then is restarted

### Expected behaviour
- Auto Upload Settings can be opened and modified

### Actual behaviour
- App automatically restarts without any Error Log (probably runs into ANR, though nothing is reported by the system)
- There is no way to recover/modify the Auto Upload Settings once broken
  - Only solution is to remove the Account and relogin
- Additional Information:
  - Marking Folders as hidden from the AutoUpload List also noticeably prolongs the time the Activity loads
  - I switched from a Redmi to a Realme Device recently, issue does not occur on old phone
    - Old Phone is running Nextcloud 3.13.1 and new one 3.16.1
    - going to try with 3.13.1 on new phone later on

### Can you reproduce this problem on https://try.nextcloud.com?
- Not tested yet (does not look like a Server Side issue)

### Environment data
Android version:
- Android 11 (Security Update from 2021-06-05)

Device model: 
- realme 8 (RMX3085)

Stock or customized system:
- Stock system
  - realm UI 2.0

Nextcloud app version:
- 3.16.1
- also tested with 3.17.0 RC3, same behaviour

Nextcloud server version:
 - 20.0.4

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
No error log is shown, App just restarts. Is there a way to retrieve the App log anyway?

**Comment by loetermann** [comment]
Update:
 - With Nextcloud App 3.13.1 on realme UI 2.0 it works fine
   - I also don't notice any delays opening the Activity, even when enabling a lot of syncs
   - Please note, that the location of the Auto Upload Button changed between these versions (moved from the sidebar in 3.13 to the settings menu in 3.16)
 - With Nextcloud App 3.16.1 on Redme (old phone) I could reproduce the slow loading of the Activity, but after ~5 seconds it opened.
   - So I guess it's just slow and that realme is to impatient and restarts the app after ~ 5 seconds

**Comment by tecnicx15** [comment]
Same is happening with my phone:
S10e 
Android 11 
July 1 2021 Security patch
App version: 3.17.0
Nextcloud server 22.1.0

As reported if version 3.13.1 is installed via apkmirror everything works as intended except we do not have the "skip file" if exists option which prevents duplicate uploads.

I hope this gets fixed soon.

**Comment by AndyScherzinger** [comment]
Are you seeing any error in the logcat?

**Comment by ne20002** [comment]
I can cofirm the problem (same configuration and device).
App restarts one time. On second try, screen is black and not respnsive, after some time the 'App is not responding' message pops up. When clicking 'wait', it takes another 4 minutes until the list of upload folders appear. From there on it works as normal.
This behaviour is repeating.
There is no errors log.

**Comment by AndyScherzinger** [comment]
@ne20002 thanks for the info. How many folders with roughly how many pictures are display in the auto upload view?

**Comment by ne20002** [comment]
@AndyScherzinger 
It's not that much images on the mobile as pictures are deleted after auto upload. It's listing 8 folders (camera, opencamera, whatsapp) plus a number of foders I've hidden (only album covers in music, 12 albums).
As the mobile is not responsive it's hard to tell what is going on. But it seems as if there is much traffic (icon in status bar).
On the server there are 16k pictures organized in sub folders, only a very few on top level folders (the folders used for auto upload).
The behavior came up with V 3.17. It worked without problems before.

**Comment by copecu** [comment]
Same problem on my Android 11 OnePlus 7T Pro, but no on my Android 10 Oneplus 5T.

Also I can't manually configure auto upload for folders on root internal storage, but I can configure automatic detected DCIM folder camera photos and videos, for example. 


In the attatched image, for example, the button "Selecciona" does nothing. It doesn't allow me to continue.

![photo_2021-08-29_11-40-11](https://user-images.githubusercontent.com/5006044/131245987-c4cb0821-bf35-417c-bd19-715fa099b1c5.jpg)

Can it be related with how Android 11 manage permissions?

**Comment by ne20002** [comment]
Problem persists with Version 3.18

**Comment by thehaguefreek** [comment]
I have the same issue:
Fairphone 4
nextcloud: 3.18.0
Android: 11
Kernel: 4.19.157-perf+

Summery:
After installation I could add auto upload folders without issue. It uploaded all 700 pictures that were already present without a problem.
But when returning to the auto upload settings later, the screen turned black and after a couple of seconds I get the ANR message from android.
This issue has been persistant.

I run the nextcloud app in both my personal as well as work profile. My work profile doesn't have this issue. But then, it didn't have any initial pictures to upload.

**Comment by ne20002** [comment]
The issue still exists on Samsung S10e with latest Android 12 / OneUI 4.0. It does not exist on Huawei Tablet with Android 10 and Samsung S9 with /e/-OS.
All devices with Nextcloud 1.18.1.
