### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by hzbb2221** [nextcloud/android#8879]
复制步骤1。2．3．####期望行为－告诉我们应该发生什么####实际行为－告诉我们发生了什么###你能在https：／／try．nextcloud．com上重现这个问题吗？－请创建一个测试演示帐户，看看那里是否仍然发生这种情况。－如果是，请打开错误报告－如果不是，请验证服务器设置，并在论坛# #环境数据Android版本：设备型号：股票或定制系统：nextcloud应用程序版本：nextcloud服务器版本：反向代理：### Logs #### Web服务器错误日志' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' '您可以使用问题模板应用程序预填一些所需的信息：https：／／apps．nextcloud．com／apps／issuettemplate

**Comment by AndyScherzinger** [comment]
please f8ill-out the issue template and re-open
