### ISSUE TITLE
PreviewMedia is closed when rotate

### ISSUE THREAD

**Issue by aleister09** [nextcloud/android#888]
### Actual behaviour
PreviewMediaFragment is replaced by FileDetailFragment when the user rotate the app
I happens because in the method ```FileDisplayActivity.chooseInitialSecondFragment()``` the property ```file.getLastSyncDateForProperties()``` is ```0``` and return FileDetailFragment
### Steps to reproduce
1. Open App
2. Open Favorites Section
3. Open a Video
4. Rotate the App

### Environment data
Android version: 7.1.2

Device model: Nexus 5X

Nextcloud app version: Master

Nextcloud server version:12

![ezgif com-video-to-gif 4](https://cloud.githubusercontent.com/assets/25756086/25397449/ecf5e6b2-29ad-11e7-9abb-3b4f66dd2096.gif)

**Comment by mario** [comment]
Thanks for the report. Wanna fix? :)

**Comment by mario** [comment]
@aleister09 also, do you think you could mail me? I need assistance with something since I see you have 7.1 :) (mario AT nextcloud DOT com)

**Comment by aleister09** [comment]
Sure!

I can fix it but i don't understand why the method check getLastSyncDateForProperties also the line has the comment ```// temporal fix``` I think it isn't necessary now, what do you think?

**Comment by mario** [comment]
Never touched that part .. @AndyScherzinger or @tobiasKaminsky , maybe you know what's this for? :)

**Comment by AndyScherzinger** [comment]
Unfortunately no, never worked on that part

**Comment by tobiasKaminsky** [comment]
This was introduced back in the old days with this commit message "Fixed: details about progress are shown when the notification of an upload is clicked"
https://github.com/nextcloud/android/commit/19bcc995386f6fbd0803d2a5bb506e8a40686b3c
