### ISSUE TITLE
Auto-upload prompts file version conflict over and over again.

### ISSUE THREAD

**Issue by 7th-heaven** [nextcloud/android#8880]
### Steps to reproduce
1. upload a part of your photos using auto-upload
2. uninstall nextcloud android client
3. switch on auto-upload function.

### Expected behaviour
- Skip the photos already uploaded.

### Actual behaviour
- All the uploaded photos before you uninstall, client prompts file version conflict over and over and over and over and over again.

### Can you reproduce this problem on https://try.nextcloud.com?
Yes! It happens again.

### Environment data
Android version: 11

Device model: Xiaomi 9

Stock or customized system: stock

Nextcloud app version: 3.17.0

Nextcloud server version: 22.0.0

Reverse proxy: 

#### Web server error log
```
No related logs
```

#### Nextcloud log (data/nextcloud.log)
```
No related logs
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by Oriann** [comment]
Same for me. I own Samsung Galaxy S21

**Comment by ogasser** [comment]
I am facing the same issue on a Oneplus 3. Currently I have an annoying number of 49 Nextcloud conflict notifications.

**Comment by ryanwalb** [comment]
I'm having the same issue on my Motorola One 5G Ace phone.

**Comment by klaus1k** [comment]
I habe the same issue in Xiaomi mi 9T Pro in Android 11.

**Comment by fqdb** [comment]
This also occurs for manual uploads
![image](https://user-images.githubusercontent.com/2826336/144009594-e8740f2b-77d3-483c-8dc7-1b96358b26ba.png)
![image](https://user-images.githubusercontent.com/2826336/144009644-e96ce73a-9c36-466a-afd5-04ef2088e801.png)

**Comment by t3kg33k** [comment]
I have the same problem with it giving notification over and over of file conflict of the same file.
Android 12. Nextcloud Android App 3.19.1

![Screenshot_20220325-101055](https://user-images.githubusercontent.com/4992046/160139177-75532f30-96b1-4137-b6c9-4aef7c43035a.png)

**Comment by mauricioph** [comment]
Same behavior Xiaomi Mi 11 Pro
![Screenshot_2022-09-07-10-15-02-878_com android chrome](https://user-images.githubusercontent.com/22575408/188840885-22932ad0-0438-407b-bd47-863267fd5050.jpg)

**Comment by ljep42** [comment]
Same issue on pixel 5 w NC 3.26.0

**Comment by joshtrichards** [comment]
May have been #10423 or some other possibilities.

There have been different reports with similar, but different root causes over time. In addition, in terms of the Android app, a lot of code has changed in these areas since these reports. This issue hasn't seen traffic >1 year. If you're experiencing anything resembling this today, please create a dedicated Issue with your individual details. Thanks.
