### ISSUE TITLE
"Select all" option for contacts restore

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/android#889]
* in the contacts restore panel you should be able to select all users

cc @tobiasKaminsky

**Comment by tobiasKaminsky** [comment]
@mario @AndyScherzinger this is ready now and in #874 included.

![file7hmnzb](https://cloud.githubusercontent.com/assets/5836855/25479293/a5aae774-2b44-11e7-9fdc-374ba48e857f.png)
![file3mdetn](https://cloud.githubusercontent.com/assets/5836855/25479294/a5cec374-2b44-11e7-94bc-d8ee4d04b9f8.png)
