### ISSUE TITLE
switching between network does not work

### ISSUE THREAD

**Issue by MrLoverLoverMMMM** [nextcloud/android#8891]
if their is happening a switch between wifi and celular, the app won't get a connection to the server.
to make it work, the app needs to be manually closed and reopend, everytime the network is changing.

my device: galaxy z fold 2
android version: 11
nextcloud version:21.0.4
nextcloud app version: 3.17.0

this had the negative effect, that all apps authorized though the nextcloud app won't work either (talk, passwords, deck,..)

**Comment by AlvaroBrey** [comment]
Should be fixed in 3.19.0. Can you still reproduce this @MrLoverLoverMMMM ?

**Comment by MrLoverLoverMMMM** [comment]
it seems to work for now :)
Thank you
