### ISSUE TITLE
Android 11 / Nextcloud App 3.17.0 [Aug 2021]  Audio file playing can't be stopped unless app is closed.  No media controls to be found.

### ISSUE THREAD

**Issue by CommunityHelper6** [nextcloud/android#8905]
### Steps to reproduce
1.  Open Nextcloud App
2.  Browse to any media file, audio in my case, press icon to start Play and switch to other app
3. 

### Expected behaviour
- Tell us what should happen

Media player controls should be present in taskbar or at least when one opens the app again.

### Actual behaviour
- Tell us what happens

No media controls to be found.  Media continues to play until App is swiped closed through the system.

If same file playing is selected, it starts playing without stopping the previous file.  It starts a separate player thread 

Additional note regarding test on demo server:  Media file continues playing even after removing demo account.  Eventually, screen pops up asking if I want to force close app.  That's when the media file stops playing.

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

Verified to still happen using demo account via try.nextcloud.com

### Environment data
Android version:  11

Device model:   Samsung Galaxy

Stock or customized system:  Stock

Nextcloud app version:  3.17.0 

Nextcloud server version:  21

Reverse proxy:  None

#### Web server error log

Not needed.  Problem is with the app not the server

Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here

Not needed.  Problem is with the app not the server
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AlvaroBrey** [comment]
I believe this has been solved by recent player fixes. @CommunityHelper6 Is this still happening in the latest version? There should be a notification with the player controls.
