### ISSUE TITLE
All Files is replaced by Other Section

### ISSUE THREAD

**Issue by aleister09** [nextcloud/android#892]
### Actual behaviour
After SwipeRefresh the app replace the section with the last visited 

### Steps to reproduce
1. Open App
2. Open Favorites or Photos or Shared
3. Go back to All Files
4. SwipeRefresh 

### Environment data
Android version:7.1.2

Device model: Nexus 5X

Nextcloud app version:Master

Nextcloud server version:12

**Comment by tobiasKaminsky** [comment]
Should be working due to the latest changes of #896

**Comment by tobiasKaminsky** [comment]
@aleister09 can you confirm that this is solved?

**Comment by aleister09** [comment]
Now is working fine =)

**Comment by tobiasKaminsky** [comment]
Thank you :-)
