### ISSUE TITLE
Autoupload doesn't allow for subfolder selection

### ISSUE THREAD

**Issue by olipinski** [nextcloud/android#8940]
This issue could be connected to #8927, however this one is more specific.

### Steps to reproduce
1. Attempt to create a new custom auto-upload
2.  Select/Tick a subfolder within a folder
3. Upon confirming the folder, the actual path will be one folder up

### Expected behaviour
- The subfolder should be selected

### Actual behaviour
- The subfolder is ignored, and the parent directory is selected instead

### Can you reproduce this problem on https://try.nextcloud.com?
N/A

### Environment data
Android version: 9

Device model: Xiaomi Mi Mix 3 5G

Stock or customized system: Stock MIUI 12.0.7

Nextcloud app version: 3.17.0

Nextcloud server version: 22.1.1

Reverse proxy: NGINX

#### Web server error log
N/A

#### Nextcloud log (data/nextcloud.log)
N/A

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by lbdroid** [comment]
I'm not sure what the purpose is of the checkboxes, unless its able to make a complex rule to upload several folders within the current into a single location on the server.

I think it really should just pick whatever folder you happen to be IN at the moment.

**Comment by AlvaroBrey** [comment]
> I'm not sure what the purpose is of the checkboxes, unless its able to make a complex rule to upload several folders within the current into a single location on the server.
> 
> I think it really should just pick whatever folder you happen to be IN at the moment.

Already in the works at #9920, without the checkboxes.
