### ISSUE TITLE
MUSIC

### ISSUE THREAD

**Issue by Lamune1985** [nextcloud/android#8978]
If the song is over and you want to hear it again, this error comes up.

************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{6b6f1d9 u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2250)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8595)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30170090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: y2s
Model: SM-G985F
Id: RP1A.200720.012
Product: y2seea

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: G985FXXSADUH5

**Comment by AlvaroBrey** [comment]
Needs more information, we can't do anything with just "Music". Please give at least a description of the error and steps to reproduce.

**Comment by Lamune1985** [comment]
If the song is over and you want to hear it again, this error comes up.

**Comment by akileos** [comment]
Same error here, stack trace is identical but line number differ, same app version. Happens everytime you press play on a just played song.
After play the progress slider is stuck slighty before 100%. Issue does not arise with every file, I can share one if needed.

**Comment by Lamune1985** [comment]
The app always crashes after the song is over. If you want to listen to it again, the player says it can't be played, then I go back and then the app crashes.
