### ISSUE TITLE
Can't select files and update problem

### ISSUE THREAD

**Issue by crashcoq** [nextcloud/android#8980]
### Steps to reproduce
1. All create a save directory or files
2. 
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:
10
Device model: 
Motorola G9+

Stock or customized system:
None, android standard

Nextcloud app version:
Latest 3.17.0

Nextcloud server version:
22.1.0

Reverse proxy:
None
#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

Can't update only files, I can select only directory and this selected it's not correct
Many time update files after create or change
All optimisation android are disable.
But this version work fine on Android 8, not update file correctly on Android 10
![Screenshot_20210915-103911](https://user-images.githubusercontent.com/8464834/133401628-1ab6e795-68a7-4dcf-aded-94b84eac3c8b.png)
![Screenshot_20210915-103818](https://user-images.githubusercontent.com/8464834/133401821-b9394e18-170f-48e2-a610-2e7bf160cad2.png)
![Screenshot_20210915-103729](https://user-images.githubusercontent.com/8464834/133401829-fe61a8f9-dc2e-4f61-9a8b-e8f6aae65207.png)
![Screenshot_20210915-103911](https://user-images.githubusercontent.com/8464834/133401834-42367111-8c62-4c16-8407-1d4fa26e49ed.png)
![Screenshot_20210915-103840](https://user-images.githubusercontent.com/8464834/133401837-0a3947bb-bea8-4b3f-9cce-8474a8c93a94.png)
![Screenshot_20210915-103835](https://user-images.githubusercontent.com/8464834/133401838-5def471a-a876-4aac-982d-357f82992cd3.png)
![Screenshot_20210915-103758](https://user-images.githubusercontent.com/8464834/133401841-47ab2542-1c08-455f-bb97-169268151ee1.png)
![Screenshot_20210915-103744](https://user-images.githubusercontent.com/8464834/133401842-5573e7c3-97e8-4609-84ef-fd8dcdd20c22.png)
![Screenshot_20210915-103737](https://user-images.githubusercontent.com/8464834/133401844-47c92e81-4799-4481-9b9b-60bc7735c014.png)

**Comment by joshtrichards** [comment]
Hi @crashcoq - This is an old report. I hope you were able to figure out a solution since this was reported. I'm not able to fully follow your report. Are you still experiencing this behavior?

**Comment by crashcoq** [comment]
Work fine with the l'attestation version

**Comment by crashcoq** [comment]
Work fine with lastest version
