### ISSUE TITLE
FileDetailFragment is replaced 

### ISSUE THREAD

**Issue by aleister09** [nextcloud/android#899]
### Actual behaviour
FileDetailFragment is replaced by PreviewTextFragment when the app rotate 

### Steps to reproduce
1. Open App
2. Select a Text File and open details
3. Rotate the app

### Environment data
Android version:7.1.2

Device model: Nexus 5X

Nextcloud app version:Master

Nextcloud server version:12

**Comment by tobiasKaminsky** [comment]
Postponing this as it is in direct affect to #912 and I do not want to do work twice.

**Comment by tobiasKaminsky** [comment]
Not happening.
