### ISSUE TITLE
  Synchronization function

### ISSUE THREAD

**Issue by wangyifan349** [nextcloud/android#8996]
Nextcloud synchronization function, only upload new pictures. Do not upload old pictures.
If the upload fails and you click Clear Failure Record, nextcloud will never upload these files

I recommend that you modify these strange strategies later

**Comment by InfamousUser** [comment]
Strange strategies ahahahah! Definitely strange, autoupload is fractured, it never worked correctly since its release.

**Comment by joshtrichards** [comment]
> Nextcloud synchronization function, only upload new pictures. Do not upload old pictures.

It will if you configure it to do so.

> If the upload fails and you click Clear Failure Record, nextcloud will never upload these files

Duplicate of #3931
