### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/android#8999]
### Steps to reproduce

1. Installing the application on the new Dev.
2. Launching the application.
3. Long connection to the Nextcloud instance.

### Expected behaviour
Launching the application on a previously configured user account.

### Actual behaviour
The application cannot log into the Nextcloud instance. After a short time, it goes to the new account creation window. After re-entering the address to the instance and trying to log in, I get a message about many failed login attempts. Lots of new entries exist in the database `oc_bruteforce_attempts`.

### Environment data
Android version: 10

Nextcloud app version: dev-20210921

Nextcloud server version: 22.1.1

#### Nextcloud log (data/nextcloud.log)
```
"reqId":"xxx","level":3,"time":"2021-09-23T06:19:04+00:00","remoteAddr":"xx.xxx.xx.xx","user":"--","app":"no app in context","method":"GET","url":"/ocs/v2.php/cloud/user?format=json","message":"App token login name does not match","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/20210921","version":"22.1.1.2","id":"xxxx"
```

**Comment by joshtrichards** [comment]
This is an older issue and I'm not sure there's enough here to reproduce this or confirm with certainty it's no longer the case but:

- any idea what type of credentials were you using to log in with? [1]
- relates to:
  - nextcloud/server#28413
  - nextcloud/documentation#7036
  - recent nextcloud/server#42971

[1] This is the server code triggered:

https://github.com/nextcloud/server/blob/946fc76d01ee1e9e96d13b8fc699bcf9cea17fcb/lib/private/User/Session.php#L800-L808
