### ISSUE TITLE
crash when listening to music

### ISSUE THREAD

**Issue by debian-user-france1** [nextcloud/android#9000]
![Screenshot_20210923-122243_Nextcloud](https://user-images.githubusercontent.com/72965843/134491653-ea6ad6e7-c7aa-4742-ad6d-c45d10c01bef.png)

I was listening to a 201KB hook from stay - The Kid Laroy
After pressing the button to go back this happened .. It doesn't matter if I press the triangle on the bottom or the button from Nextcloud

**Comment by debian-user-france1** [comment]
Happens every time

**Comment by AlvaroBrey** [comment]
Duplicate of #8686
