### ISSUE TITLE
Support text file creation

### ISSUE THREAD

**Issue by bes1002t** [nextcloud/android#9001]
### Is your feature request related to a problem? Please describe.
Webgui provides a way to create text file, android app does not.

### Describe the solution you'd like
Also provide a way to create simple text files in Android.

### Meta Information
Device: LGG4 (H815)
Android: 7.1.2
Nextcloud App: 3.17.0
Nextcloud Server: 21.0.3

![webgui](https://user-images.githubusercontent.com/3890580/134510611-d7811cb0-e7a9-4ec6-a7f4-dd5f0e9794bf.png)

![android](https://user-images.githubusercontent.com/3890580/134510607-6ea678d9-87d8-4ecc-b428-cb2162c18207.png)

**Comment by AndyScherzinger** [comment]
@bes1002t this is already available but might depend or your server-setup (maybe @tobiasKaminsky knows which ones excactly)
![device-2021-09-23-174914](https://user-images.githubusercontent.com/1315170/134541508-6ac5bf80-4c94-47f3-934e-a40dfeecec56.png)

**Comment by AndyScherzinger** [comment]
also what is your server/device config, versions of app/nextcloud/nextcloud-Android ?

**Comment by AndyScherzinger** [comment]
especially in case the bottom sheet you are seeing is simply "too small" which might be related to your device resolution and would then be a bug. But for that we need more info from you about your setup, client/server.

**Comment by bes1002t** [comment]
@AndyScherzinger you're completely right, sorry. I've added the information to my initial post. If you need further information please let me know! :)

**Comment by AndyScherzinger** [comment]
@bes1002t there are several models of your phone, like: https://de.wikipedia.org/wiki/LG_G4 do you know which one? As in display in inch and pixel resolution height/width ?

**Comment by AndyScherzinger** [comment]
Good to know, the different models do differ quite a bit regarding resolution of the display and thus pixel density.

**Comment by joshtrichards** [comment]
This is scrollable today, no?

I recall folks mentioning in other Issues sometimes needing to scroll to see all the menu choices available.

I can't tell whether this discussion was simply about that or an actual bug preventing accessing the additional menu choices entirely. 

How is this looking for you today, @bes1002t?

**Comment by joshtrichards** [comment]
@bes1002t I didn't hear back from you. I'm going to close this out as a presumed fixed, but feel free to respond/reopen.
