### ISSUE TITLE
Whatsapp folder backup

### ISSUE THREAD

**Issue by carallo** [nextcloud/android#9017]
I am trying to set up auto-upload for Whatsapp's data folder, but I cannot seem to manage to do it. 
If I copy the folder in another location it seems to be uploaded correctly. But when I select the folder in its real directory (Android/media/com.whatsapp) it does not seem to upload anything. Am I doing something wrong here? Is it due to some new Android file accessibility policy changes? Nextcloud has permission to access all files on my phone.

**Comment by AlvaroBrey** [comment]
Hi @carallo , what is your Android version?

**Comment by carallo** [comment]
> 
> 
> Hi @carallo , what is your Android version?

Sorry for the delay, I'm on Android 11. But I have to say that it finally started syncing after some time. Maybe the size and number of files was so high that it needed some time to process the folder and start syncing. I'd say we could close the issue.... Sorry for jumping to a conclusion too fast!

**Comment by AlvaroBrey** [comment]
No problem, thank you!
