### ISSUE TITLE
compatibility table with Android minim version

### ISSUE THREAD

**Issue by crisc2000** [nextcloud/android#9023]
### Is your feature request related to a problem? Please describe.
Hello. I have a Samsung Galaxy S4 that have a Android maximum version official support 5.0.1
Latest version of Nextcloud suport a Android minimum version 5.1+.
I have found older versions of Nextcloud apk but I did not found a compatibility table for what is the minimum Android version. So I need to check all the versions manually and find the last one that is compatible with my Android 

### Describe the solution you'd like
Please add a Nexcloud compatibility with Android minim version

**Comment by AndyScherzinger** [comment]
see: https://github.com/nextcloud/android/blob/master/CHANGELOG.md --> 3.16.1

**Comment by AndyScherzinger** [comment]
APK: https://github.com/nextcloud/android/releases/tag/stable-3.16.1

**Comment by AndyScherzinger** [comment]
For the request, compatibility as in dropping support for a version is announced in the changelog.

**Comment by crisc2000** [comment]
Thanks for the link.
