### ISSUE TITLE
Multiple accounts: one is marked

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#903]
### Actual behaviour
- An account is marked

### Expected behaviour
- No account should be marked
 
### Steps to reproduce
1. Create multiple accounts
2. open drawer
3. switch to accounts

User test1 is currently logged in.
![file7mhyle](https://cloud.githubusercontent.com/assets/5836855/25469478/b2790972-2b1c-11e7-81a3-3a22cfb0c725.png)

**Comment by AndyScherzinger** [comment]
Actually this shouldn't happen and I also can't reproduce it and the expected behavior the actual behavior on my phone (running master)

**Comment by tobiasKaminsky** [comment]
Steps to reproduce:
- install regular app with tobi and test account
- switch to test account
- install branded version
- then this seems to be logged in as tobi, but highlights also test

@mario we need to make sure that both variants are not influence each other, although this will be adjusted for each branding, the default must also be totally separately, includes:
- independent account
- independent storage folder
