### ISSUE TITLE
automatically delete local copies of files which are older than 30 days

### ISSUE THREAD

**Issue by alexanderdd** [nextcloud/android#9037]
### Is your feature request related to a problem? Please describe.
I want local copies of my recent pictures on my device, so I choose "move to application folder" for automatic upload. But then it fills up my device storage and I have to manually delete local copies regularily.

### Describe the solution you'd like
new setting (_either_ only for automatic upload _or_ for the whole android app): automatically delete local copies of files which are older than 30 days
I think this is a sensible default (see design guidelines of Nextcloud), so it should be enabled by default?!

### Describe alternatives you've considered
-

### Additional context
-

**Comment by kerlue** [comment]
I would like to work on this if approved.

**Comment by sanchosk** [comment]
I would volunteer to test the feature and buy a coffee for the dev doing this.

**Comment by joshtrichards** [comment]
Duplicate of #2323 

I suggest subscribing to that issue to track progress and/or giving it an upvote :+1:
