### ISSUE TITLE
UI Glitch when "search/filters" are used

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#905]
### Actual behaviour
- see screenshots

### Expected behaviour
-depending on the state, just the loader and the right text
 
### Steps to reproduce
1. open shared or favorites
2. rotate the screen (for as many times as you like, >= 1)

![device-2017-04-27-121914](https://cloud.githubusercontent.com/assets/1315170/25479119/0c439540-2b44-11e7-94ed-1a5f50d59e93.png)

![device-2017-04-27-121924](https://cloud.githubusercontent.com/assets/1315170/25479125/0f723e4c-2b44-11e7-8cb3-5f12b10e363b.png)

cc @mario @tobiasKaminsky 

### Environment data
Android version: 7.1.1

Device model: OP3T

Stock or customized system: stock

Nextcloud app version: latest master

Nextcloud server version: 11.0.2

**Comment by tobiasKaminsky** [comment]
Please test with latest https://github.com/nextcloud/android/pull/896

**Comment by tobiasKaminsky** [comment]
@mario @AndyScherzinger friendly reminder for testing with latest #896

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky i can confirm that the original issue is fixed by #896 now 👍 Issue I found though it that a screen rotation triggers a new search which imho it shouldn't. Should I open another issue for that or is this fixed by another PR already? cc @mario

**Comment by AndyScherzinger** [comment]
fixed by #896
