### ISSUE TITLE
Unable to access menu

### ISSUE THREAD

**Issue by CCarlo1** [nextcloud/android#9051]
### Steps to reproduce
1. Install EduYGO and select SD storage, on your phone Xiaomi Redmi 9a
2. Play with it for a few days, and try to download images or anything until it shows an error
3. Now use Nextcloud and press the three lines on the upper left screen

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AlvaroBrey** [comment]
This is unfortunately not enough information to know what the bug is coming from. I'd guess it's a duplicate of #8862 , but without android crash logs we can't be sure. If possible, please attach android logs (logcat) in which the crash is shown.
