### ISSUE TITLE
Status bar with sorting/view mode disappears after playing video

### ISSUE THREAD

**Issue by Derkades** [nextcloud/android#9060]
### Steps to reproduce
1. Navigate to directory
2. Tap video file
3. Go back
4. Bar is goke, and title bar covers the first file
5. Press back again
6. Bar is back

app version 3.17.0

sorry not much time to create an issue right now, hopefully this is enough

**Comment by AlvaroBrey** [comment]
This has been fixed on master, although I'm not sure where. A lot of minor bugfixes regarding toolbar have been merged since 3.17.
