### ISSUE TITLE
Time Scheduled Auto-Upload

### ISSUE THREAD

**Issue by Emporea** [nextcloud/android#9071]
I know this sounds like a strange, over-specific and risky request backup-wise, but considering one using slow or metered connection while handling daily big new files (~1.5GB each day) this might come in handy. Some uploads need an hour to finish and literally "blocks" the connection for other stuff.

Timed Backup, only check / queue new files to upload after a certain amount of hours / days for different Folders. Maybe a timeframed or late-night only upload mode.
Deactivating Android's Sync Option isn't sufficient for this.

This option could be added to the settings 'only unmetered WI-FI, only charging'.

**Comment by Th0masL** [comment]
:+1:  I'd also like to be able to schedule the Upload of a specific folder every day at a specific time.

**Comment by joshtrichards** [comment]
Duplicate of #2323
