### ISSUE TITLE
Android app gets stuck in "On Device" files

### ISSUE THREAD

**Issue by erahhal** [nextcloud/android#9078]
### Steps to reproduce
1. Load app. Notice that search box says "Search in Nextcloud", and folder list is list from server
2. Select "On Device"
3. Select "Deleted files"
4. Select "All Files"
5. Notice that search box and file list are still for "On Device". No way to get back to server file list without exiting and restarting the app

### Expected behaviour
- selecting "All Files" should show the list of files on the server

### Actual behaviour
- it gets stuck on "On Device" files

### Can you reproduce this problem on https://try.nextcloud.com?
- Couldn't get the app to connect to a demo account.

### Environment data
Android version: LineageOS 18.1 (android 11)

Device model: OnePlus 7 pro

Stock or customized system: custom

Nextcloud app version: 3.17.0

Nextcloud server version: 22.2.0

Reverse proxy: nginx

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by joshtrichards** [comment]
Hi @erahhal - Thanks for reporting.

I can't replicate this today. I don't know the PR, but it seems fixed (at least as of v3.26.0). 

If you disagree feel free to follow-up and I'll reopen to investigate.
