### ISSUE TITLE
Dismiss original file folder dialog on rotation

### ISSUE THREAD

**Issue by imjarp** [nextcloud/android#910]
### Actual behaviour
When you pick a remote folder in the preference auto upload dialog and rotate the device the dialog does not show 

### Expected behaviour
-When rotating the device keep the UI state
 
### Steps to reproduce
1.Select Upload from menu 
2.In any header view click the settings Image Button
3.Click on "Original file will be..."
4.Rotate the device

### Environment data
Android version: 6.0

Device model: LG-G4 Stylus

Stock or customized system: Stock

Nextcloud app version: 1.4.2

Nextcloud server version: 12

![bug](https://cloud.githubusercontent.com/assets/5035158/25497272/a6a61e28-2b49-11e7-9b6d-80d8601fe81b.gif)

PR: #1138

**Comment by AndyScherzinger** [comment]
I created a branch, so fix this collaboratively

**Comment by AndyScherzinger** [comment]
https://github.com/nextcloud/android/tree/910_dialogRotation

**Comment by AndyScherzinger** [comment]
merged to master for 1.5.0
