### ISSUE TITLE
Tile view for favorites

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/android#9130]
In the tile view for favorite directories or files, its description is truncated:

![obraz](https://user-images.githubusercontent.com/47037905/138560522-6f1bcf05-34ed-4d95-a4b8-f10ef43f8a12.png)

### Environment data
Android version: 10
Nextcloud app version: 3.17.1

**Comment by gmotzespina** [comment]
I wasn't able to reproduce it in a Pixel 3 phone. 

Could you please specify the device you used to reproduce the issue? I believe it might be related to the aspect ratio of the screen. Large phones don't show the chopped labels.

**Comment by Valdnet** [comment]
> Could you please specify the device you used to reproduce the issue?

My device is Huawei with display 6.21".

**Comment by malik0011** [comment]
is it still open, i want to work on it

**Comment by AlvaroBrey** [comment]
Yes @malik0011, we haven't worked on it yet

**Comment by Valdnet** [comment]
As of 3.18.x, the display of favorites is correct. Maybe it was corrected without even knowing it:

![obraz](https://user-images.githubusercontent.com/47037905/149299169-a4d21ddc-2793-42b6-ae26-78bbe29e41ec.png)

@malik0011 I think it can be checked 😉. If this is correct then I can close the issue.

**Comment by simunde** [comment]
If the issue is still persisting may I work on it ?

**Comment by Valdnet** [comment]
Issue has been fixed (maybe with other changes).
