### ISSUE TITLE
Can't upload files with E2E Encryption

### ISSUE THREAD

**Issue by arch-user-france1** [nextcloud/android#9132]
************ CAUSE OF ERROR ************
```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.owncloud.android.lib.common.operations.RemoteOperationResult.isCancelled()' on a null object reference
	at com.owncloud.android.datamodel.UploadsStorageManager.updateDatabaseUploadResult(UploadsStorageManager.java:562)
	at com.owncloud.android.files.services.FileUploader.uploadFile(FileUploader.java:661)
	at com.owncloud.android.files.services.FileUploader$ServiceHandler.handleMessage(FileUploader.java:1402)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.os.HandlerThread.run(HandlerThread.java:67)
```
************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30170090
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: Fairphone
Device: FP3
Model: FP3
Id: QQ3A.200805.001
Product: FP3

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: eng.root.20210827.151157

When uploading a file into an encrypted folder (in my case a 200MB zip archive) the app crashes or just says an unknown problem occured while uploading (happens immediate)

**Comment by ezaquarii** [comment]
@debian-user-france1 not really, the root cause is that the upload operation result seems to be `null`. Even if there was an upload error, the result should never be `null`, so we need to dig into that first.

**Comment by ezaquarii** [comment]
After looking at the code, the only viable path that can produce `null` is here:
https://github.com/nextcloud/android/blob/ea92f8432cbae6ff49a9bc07706717c5aec901e9/src/main/java/com/owncloud/android/files/services/FileUploader.java#L644

@tobiasKaminsky is it possible that operation returns null during some e2e failure? I'd not expect this, so maybe there is a bug somewhere in the ops.

**Comment by PanRe** [comment]
I have the same error but with a 7MB file.

**Comment by joshtrichards** [comment]
There have been substantial changes made to the E2EE code base since this report. Are you still experiencing the matter covered in this report?

**Comment by arch-user-france1** [comment]
I can not reproduce the problem anymore, tested with a 50 MB file instead of a 200 MB file.
