### ISSUE TITLE
Allow accessing downloaded documents while offline through SAF

### ISSUE THREAD

**Issue by Derkades** [nextcloud/android#9134]
### Is your feature request related to a problem? Please describe.
I want to switch from Keepass2Android to KeepassDX, which relies on the storage access framework. Unfortunately, even when the file is downloaded and available through the Nextcloud app, even though it is visible in SAF, trying to open or copy it will result in an error.

### Describe the solution you'd like
Allow opening these files. Modifying it might not be possible, not sure if Nextcloud has a 2 way sync system like on desktop.

### Describe alternatives you've considered
* Keep using Keepass2Android which has native WebDAV sync support
* Use some sync tool
* Open the file from Android/Media

**Comment by joshtrichards** [comment]
As far as I can tell this enhancement request came in 3 days after this functionality was released in v3.18. It was implemented in #8925.
