### ISSUE TITLE
Feature Requst: Music App

### ISSUE THREAD

**Issue by ArthurVardevanyan** [nextcloud/android#914]
Styled music player inside the android app.

**Comment by eperezv** [comment]
+1. It would be a great feature!

**Comment by tobiasKaminsky** [comment]
Currently we are focusing on files with the app. 
We need to think if we want to enhance the audio/video functionality or if the app should "just" serve as a sync client between NC and device and that video/music will be done with native apps.

**Comment by jakobroehrl** [comment]
Hi @tobiasKaminsky 
Are there any news an this? Will Nextcloud serve only as sync client or will it be enhanced with audio/video streaming functionality?

**Comment by ezaquarii** [comment]
@jakobroehrl There is a limited streaming support for now. I don't think we're planning a full-featured media player - this is a mammoth task.

You can however point other media players to Nextcloud synced folder.

**Comment by jakobroehrl** [comment]
@ezaquarii 
Thanks for your reply. So I have to sync me complete song folder to the phone, wright?
Is it possible to have a folder that is automatic synconized to mobile when the server content has changed?
