### ISSUE TITLE
File conflict resolution between local device and server has misleading name choices

### ISSUE THREAD

**Issue by cidetraq** [nextcloud/android#9148]
### Is your feature request related to a problem? Please describe.
When there is a conflict between a local (on-device) file and the same file stored on the sever, the prompt to select which file to keep misleads with its name choices a bit.

You can select - keep "New file", or keep "Already existing file", or "both". Only through trial and error did I discover that "Already existing file" refers to the file on the server, regardless of which file has a newer timestamp. Meanwhile, "keep new" replaces the file on the server with the version from the local device. In my situation, I had edited the server version LATER by one minute than the server on the local android device, so calling the Android version of age 2 minutes "newer" while the server version was only one minute old, was very misleading.

### Describe the solution you'd like
Rename "New file" to "Local device flie" and "Already existing file" to "File found on server"

### Describe alternatives you've considered
Many others have already mentioned hashing to tell versions apart and I think this is also a good idea.

### Additional context
It would be nice if there were an option to simply replace whatever file you're browsing with the newest possible version, no matter if the source were the local device or the server.

**Comment by acidicX** [comment]
Oh yes please, this is so counter-intuitive, I've just hat this user error due to bad naming multiple times. If someone can point me to the right language string I can change it in Transifex. I've searched the values files for the correct string in `string.xml` but I can't find it for some reason.

**Comment by AlvaroBrey** [comment]
This has been done  already (https://github.com/nextcloud/android/commit/5500585c1aaa578ef36d619efba9c7f99ed14fcb).

**Comment by acidicX** [comment]
@AlvaroBrey it is definitely still wrong as described by @cidetraq in the German version, and I can't find those strings in https://github.com/nextcloud/android/blob/master/app/src/main/res/values/strings.xml anymore...?

**Comment by AlvaroBrey** [comment]
>  I can't find those strings in https://github.com/nextcloud/android/blob/master/app/src/main/res/values/strings.xml anymore...?

https://github.com/nextcloud/android/blob/master/app/src/main/res/values/strings.xml#L910-L911

> @AlvaroBrey it is definitely still wrong as described by @cidetraq in the German version

Which version of the app do you have? The string is properly translated in Transifex to German, and the old string should not be there anymore since it was renamed (not just changed)

**Comment by acidicX** [comment]
@AlvaroBrey that is really weird. For me it still shows the old strings (newer / older instead of local / server), although the last time I've seen the screen it was while trying to edit a markdown file. Maybe thats another component of the app?

I'm on the latest F-Droid stable build (3.20.1).

**Comment by AlvaroBrey** [comment]
> @AlvaroBrey that is really weird. For me it still shows the old strings (newer / older instead of local / server), although the last time I've seen the screen it was while trying to edit a conflicted markdown file. Maybe thats another component of the app?
> 
> I'm on the latest F-Droid stable build (3.20.1).

Can you paste the exact words that you saw (in German) so that I can search for them in case they're somewhere else?

**Comment by acidicX** [comment]
@AlvaroBrey  while trying to replicate the behaviour, I saw that the non-markdown conflict dialogue looks completely different (material design) and shows the correct language strings as described in `strings.xml`.

So the "wrong" strings must be limited to markdown conflict resolution only (side-by-side view with round buttons). I've also noticed that this dialogue is broken (only the "old version" button works).

Sadly the app prevents doing screenshots without any option to disable this (https://github.com/nextcloud/android/issues/1924 *sigh*) and it's really hard to reproduce to get the message to show inside the markdown editor again. I think it was something with "Neuere Version" and "Alte Version"

**Comment by AlvaroBrey** [comment]
> @AlvaroBrey while trying to replicate the behaviour, I saw that the non-markdown conflict dialogue looks completely different (material design) and shows the correct language strings as described in `strings.xml`.
> 
> So the "wrong" strings must be limited to markdown conflict resolution only (side-by-side view with round buttons). I've also noticed that this dialogue is broken (only the "old version" button works).
> 
> Sadly the app prevents doing screenshots without any option to disable this (#1924 _sigh_) and it's really hard to reproduce to get the message to show inside the markdown editor again. I think it was something with "Neuere Version" and "Alte Version"

I've confirmed that those strings are not in the app. Between that and the different dialog styles, I assume this dialog is shown by the editor app (the editor is an embedded webview). Not sure what we can do about it, since in this case it can mean that the same file is edited at the same time by other people (not just local vs server)

**Comment by acidicX** [comment]
@AlvaroBrey thanks for checking it out. Do you know which project contains this web view, so I can raise the issue there?
