### ISSUE TITLE
What happened to Auto Backup?

### ISSUE THREAD

**Issue by NuxRo** [nextcloud/android#919]
Hello, I have Nextcloud 1.4.2 from Fdroid and I have an auto backup feature for dirs with images (not only camera taken, but also screenshots, downloads etc).

See https://m.imgur.com/6xwDGNh

I have installed Nextcloud 1.4.2 from Google Play on my wife's phone and the feature is missing.

I am very much interested on the feature as we want all images saved to nextcloud, not only camera snaps.

thanks!

**Comment by tobiasKaminsky** [comment]
Auto Upload is currently for Android 6 and above, but with 1.5.0 it will replace InstantUpload on all devices. So for now you can use the (limited) InstantUpload on your wife's phone only.

**Comment by NuxRo** [comment]
Ah, right, makes sense, thanks.

**Comment by AndyScherzinger** [comment]
> Auto Upload is currently for Android 6 and above, but with 1.5.0

@tobiasKaminsky can you open an issue for that, since we need to do that change (at least to activate it for Android 5). Below to even support 4.x we might need more/further changes...

**Comment by tobiasKaminsky** [comment]
Autoupload will be rewritten once again this and next week. Mario and me have this in mind.
