### ISSUE TITLE
Add more options to send/share

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/android#9214]
Add option to select more app like messengers, WhatsApp etc only option is now are from the below image really hard to send a picture or file from the Nextcloud android app ![image](https://user-images.githubusercontent.com/59488153/140628343-5d3132f5-520a-4675-8078-0bf5d6c4f436.jpeg)

**Comment by AlvaroBrey** [comment]
This is actually a bug, as all applications capable of sharing the file should be shown.

**Comment by andyxheli** [comment]
Thank you!
