### ISSUE TITLE
AutoUpload don't work correctly at latest RC4

### ISSUE THREAD

**Issue by Siggi0904** [nextcloud/android#9218]
Since Nextcloud Android app 13.18.0 RC4 only pictures and videos are uploaded at configured auto upload.

In my case, a configured the complete whatsapp folder for auto upload.
With latest version no *.crypt14 and other files (no media files) are uploaded automatically.

Thanks for fixing at final release.

**Comment by AndyScherzinger** [comment]
@AlvaroBrey will RC5 fix this issue?

**Comment by AlvaroBrey** [comment]
> @AlvaroBrey will RC5 fix this issue?

Unfortunately I think not. Ref: https://developer.android.com/training/data-storage/manage-all-files

In short, Android 11 enforces that no app can access other apps' private data directory (under `sdcard/Android/data`), and there's no way around it.

**Comment by Siggi0904** [comment]
Then don't use MANAGE_EXTERNAL_STORAGE

See:

- When an app has the MANAGE_EXTERNAL_STORAGE permission, it can access these additional files and directories using either the MediaStore API or direct file paths. **When you use the Storage Access Framework, however, you can only access a file or directory if you could do so without having the MANAGE_EXTERNAL_STORAGE permission.**

**Comment by AlvaroBrey** [comment]
> Then don't use MANAGE_EXTERNAL_STORAGE
> 
> See:
> 
>     * When an app has the MANAGE_EXTERNAL_STORAGE permission, it can access these additional files and directories using either the MediaStore API or direct file paths. **When you use the Storage Access Framework, however, you can only access a file or directory if you could do so without having the MANAGE_EXTERNAL_STORAGE permission.**

Not sure we're understanding the same from that bold part. It explicitly says that the SAF can only access files that would've been accessible anyway without `MANAGE_EXTERNAL_STORAGE` (in other words, `MANAGE_EXTERNAL_STORAGE` provides access to the files that the SAF can see, and then some more).

To be clear, `MANAGE_EXTERNAL_STORAGE` is the absolute highest level of access that apps can now get on Android 11+, and we can't do anything about it. As far as I know, there is no workaround for accessing private app directories on Android 11+, short of root access which is a whole different can of worms.

**Comment by Siggi0904** [comment]
okay, sound bad for users, with security reasons I can understand googles point of view.

Then hopfully apps like Autosync will work for that backup feature.

**Comment by Siggi0904** [comment]
And this point should be described for all users at version upgrade,
And folder selection at auto upload feature should be not possible for this folder  root.

Actually I can select these folder.

**Comment by Siggi0904** [comment]
Okay, got RC5 right now.

Full access granted in newly window and auto upload started correctly.
Works great, thanks.
