### ISSUE TITLE
Remove google.gms play-services dependency

### ISSUE THREAD

**Issue by sedrubal** [nextcloud/android#922]
### Actual behaviour
Since you added `com.google.android.gms:play-services` to the `dependencies` in e245b1f91dd30994f182892255d963a62dc6429c, f-droid can't build and distribute this app anymore.

### Expected behaviour
Please remove this dependency.

### Environment data
Nextcloud app version: `1.4.2`

**Comment by mario** [comment]
Has been done already.

**Comment by AndyScherzinger** [comment]
Like mentioned,this has been fixed in development already and will be shipped with the next release v1.5.0.

**Comment by sedrubal** [comment]
Oh sorry 🙈

**Comment by AndyScherzinger** [comment]
No worries :) it's all well :)
