### ISSUE TITLE
[3.18.0 RC4] "Es wurde keine App für den Dateityp gefunden" (An app for this file type couldn't be found)

### ISSUE THREAD

**Issue by j-ed** [nextcloud/android#9227]
### Actual behavior
If you try to open a pdf file using the app, it is downloaded but not opened afterwards. Instead the message "**Es wurde keine App für den Dateityp gefunden**" (An app for this file type couldn't be found) is displayed. This problem appears independently if a file has already been downloaded to the mobile phone or if you're downloading it directly from the server. 

### Expected behavior
If you try to open a pdf file using the app, it should downloaded and the related app to display the file should be opened automatically.

### Steps to reproduce
1. Open the Nextcloud app and navigate to a folder which contains a pdf file.
2. Select a pdf file.
-> The file is downloaded but not displayed anymore. (This worked before the last update). Instead of opening the related pdf viewer app, the message "Es wurde keine App für den Dateityp gefunden" (An app for this file type couldn't be found) is displayed.

### Environment data
Android version: 11.0
Device model: Samsung Galaxy S20
Stock or customized system: Stock ROM
Nextcloud app version: 3.18.0 RC4
Nextcloud server version: 21.0.5

**Comment by AndyScherzinger** [comment]
regression - reproduced successfully with latest master
