### ISSUE TITLE
Research: open calendar/contact directly from unified search

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#9229]
Is it possible to open a calendar/contact from unified search local on device?

Idea
- there must be an unique id
- "just" open this via intent on Android
  - either it works
  - or it fails with correct error message
 
Ref: https://itnext.io/android-calendar-intent-8536232ecb38

**Comment by tobiasKaminsky** [comment]
@miaulalala as you are an expert on calendar.
Do we have a unique id, which unified search could send, and Android then can use to view this event?

**Comment by tobiasKaminsky** [comment]
Open via intent on Android: https://developer.android.com/guide/topics/providers/calendar-provider#intent-view

**Comment by miaulalala** [comment]
yes, calendar events / vcards have a unique id (UID):

See for example in the widgets: https://github.com/nextcloud/calendar/blob/babc444245f6e6cef2fd1a88773532074c9cad0e/lib/Dashboard/CalendarWidget.php#L176
