### ISSUE TITLE
[3.18.0 RC5] Trapped in an app unlock loop after executing a search 

### ISSUE THREAD

**Issue by j-ed** [nextcloud/android#9244]
### Actual behavior
If you search for a specific file on your Nextcloud server and you've activated the device app pin unlock function, the Nextcloud app is instantly locked and if you try to unlock it, the dialog appears again and again. (This problem didn't happen in RC4)

### Expected behavior
If you search a specific file on your Nextcloud server, the search should be executed and the result should be displayed afterwards.

### Steps to reproduce
1. Open the Nextcloud app and unlock it with the device pin unlock function or your fingerprint etc.
2. Select the search bar on top of the app, enter the search term and execute the search.
-> The Nextcloud app is instantly been locked. If you unlock it, you're trapped in an unlock loop. The only way to open the app again is, to kill it first in Settings > Apps.

### Environment data
Android version: 11.0
Device model: Samsung Galaxy S20
Stock or customized system: Stock ROM
Nextcloud app version: 3.18.0 RC5
Nextcloud server version: 21.0.5

**Comment by AndyScherzinger** [comment]
pinging @AlvaroBrey and @tobiasKaminsky maybe related to search changes?

**Comment by AlvaroBrey** [comment]
> pinging @AlvaroBrey and @tobiasKaminsky maybe related to search changes?

This is a bug in unified search. Working on it.
