### ISSUE TITLE
Android App stuck on Testing connection

### ISSUE THREAD

**Issue by oXyiGYJ** [nextcloud/android#9245]
### Steps to reproduce
1. Hit “Log In” on the App
2. Enter server URL or scan the QR code from the Admin section
3. …

### Expected behaviour
Login should bring up my login page.

### Actual behaviour
When trying to use the Nextcloud Sync app on Android 12, it gets stuck at “Testing Connection”. I have this running with a Lets Encrypt SSL cert, the server has both an IPv4 and IPv6 address, and has worked in the past. When I check /var/log/nginx/access.log while trying to connect, it shows nothing other than my Windows and Linux connections. However, if I open up Chrome or Firefox on my Android 12 device, it will connect to the web page just fine and allow me to login, and I see that reflected in the access log.

I updated my phone to Android 12 around the same time I updated my Nextcloud instance to 22.2.0, so I cannot say for certain that one or the other is the culprit. It worked before upgrading these 2, and has continued to work just fine on Windows, Linux as well as in the mobile browser without issue. I also do not have any apps on the device that would block connections, and have tried this with or without WiFi, and get the same result.

The issue was noticed when no files would update or sync on the device, so i decided to clear all data and set it up again, and it will not connect. I can, however, get the app to show that no instance could be found by typing in some random URL, and it will say “Could not find host”, so its able to find that my instance is a host.

### Can you reproduce this problem on https://try.nextcloud.com?
I can connect to demo1.nextcloud.com. However, I have posted this on the forums and have not gotten a response in over a week. Forum link https://help.nextcloud.com/t/android-app-stuck-on-testing-connection/126567

### Environment data
Android version: 12 Build SP1A.211105.002.A1

Device model: Pixel 5

Stock or customized system: Stock

Nextcloud app version: 3.17.0, 3.17.1, 3.18.0 RC4, Dev 2021106

Nextcloud server version: 22.2.0.2

Reverse proxy: No

#### Web server error log
```
There are no errors when connecting from the app. Nothing shows up in access.log nor error.log when trying to connect, however I can see all connections in access.log from the browser on the phone (either Chrome or Firefox) as well as on the desktop (Linux and Windows) and both sync clients on those desktops.
```

#### Nextcloud log (data/nextcloud.log)
```
There is literally 0 information in that file. No data (shows 0 for size) and cat produces no output. Editing it shows nothing.
```

**Comment by aweinert** [comment]
Same issue occurs at https://nextcloud.alexanderweinert.net. When attempting to connect using the app, neither `access.log` nor `error.log` nor `nextcloud.log` show any activity. I have created a test account and would be happy to provide the password for debugging this issue.

Connecting to `demo2.nextcloud.com` proceeds past the "testing connection" step.

# Environment data

- Android version: 11
- Device model: Samsung A52s 5G
- Stock or customized system: Stock
- Nextcloud app version: 3.17.1
- Nextcloud server version: 22.2.2
- Apache2 v2.4.41
- PHP 7.4
- Reverse proxy: No

**Comment by wylel** [comment]
Not sure what is going on, but the only thing that has changed since it did not work and did was an update to News for Nextcloud. I tried yesterday again, and it did not work, today I had an update for the News app in Nextcloud, so I updated it this morning, just tried again to login to the Nextcloud app and it worked.

**Comment by aweinert** [comment]
Issue persists for me after updating Nextcloud to 22.2.3 as well as after installing version 3.18.0 RC 5 of the app from f-droid

**Comment by aweinert** [comment]
Cannot reproduce this issue using revision 8eff4f7d on android emulator using Android 11.0. I'll see if the issue persists on my actual hardware using that revision

**Comment by aweinert** [comment]
Also, Issue persists using actual hardware and Nextcloud App version 3.18.0 from the play store after switching to mobile data instead of my local WiFi. Thus, I feel confident in ruling out local network misconfiguration as the source of the issue

**Comment by aweinert** [comment]
After some debugging, the issue appears to lie with the apache-commons `HttpClient`. I was able to reproduce the issue using the following code snippet:

```
final HttpMethod method = new GetMethod("https://nextcloud.alexanderweinert.net/status.php");
final HttpParams params = HttpMethodParams.getDefaultParams();
params.setParameter(HttpMethodParams.USER_AGENT, "Mozilla/5.0 (Android) Nextcloud-android/3.19.0 Alpha1");
method.getParams().setDefaults(params);
final HttpClient client = new HttpClient();
try {
    return client.executeMethod(method);
} catch (IOException e) {
    e.printStackTrace();
}
return null;
```

The call to `client.executeMethod(method);` hangs indefinitely when executed on my device. I'll see whether a more recent version of `HttpClient` resolves the issue. If I read the dependencies correctly, there are plans to migrate away from using `commons-httpclient:3.1`, right?

**Comment by aweinert** [comment]
Issue persists with the following code using `httpclient` v4.3

```
final HttpGet method = new HttpGet("https://nextcloud.alexanderweinert.net/status.php");
method.addHeader("User-Agent", "Mozilla/5.0 (Android) Nextcloud-android/3.19.0 Alpha1");
final HttpClient client = HttpClients.createDefault();
try {
    ResponseHandler<Integer> responseHandler = new ResponseHandler<Integer>() {
        @Override
        public Integer handleResponse(HttpResponse response) throws ClientProtocolException, IOException {
            return response.getStatusLine().getStatusCode();
        }
    };
    return client.execute(method, responseHandler);
} catch (IOException e) {
    e.printStackTrace();
}
return null;
```

**Comment by oXyiGYJ** [comment]
I am having this issue again. It worked for a while and then all of the sudden stopped working. Do we have any idea on what could fix this issue?

**Comment by Rexaris** [comment]
I have the same Issue too. It occured after i made a clean install of my complete server setup to a newer debian version.
I also tried the URL of @aweinert with the same result. 

demo2.nextcloud.com is working fine.


#### Environment data

- Android version: 11 (MIUI Global 12.5.6)
- Device model: Xiaomi Redmi Note 9 Pro
- Stock or customized system: Stock
- Nextcloud app version: 3.18.1
- Nextcloud server version: 23.0.0
- Apache2 v2.4.51
- PHP 7.4
- Reverse proxy: No

**Comment by bpgerber** [comment]
I have this exact same issue. 

Absolutely no nextcloud domain works in the login phase. Not demo2, not my domain, nothing. From any web browser: phone, desktop, work laptop, they all connect just fine. Just the app is completely borked

**System**

Android version: 11 (Sony 58.1.A.5.222)
Model: Sony Xperia 5 ii
Stock system
Nextcloud app version: 3.18.1.30180190
Nextcloud server version: 20.0.14
PHP 7.4.26
Reverse Proxy: Yes

**Comment by AlvaroBrey** [comment]
> This is the same [IPV4 issue](https://github.com/nextcloud/android/issues/7400#issuecomment-732172396) because it will work over a mobile (3G/LTE) data connection, but just not over wifi.

If you think that's the case, please test the QA apk linked in [this comment](https://github.com/nextcloud/android/pull/9685#issuecomment-1011900034) and post back in #7400 if it solves your issue. 

@aweinert : I've tested the provided URL in two separate physical devices and an emulator and it doesn't hang for me at all. It might be indeed something related to IPv6 (I don't have a working IPv6 at home).

Other people in this thread: also test the above APK and see if there's any improvement.

**Comment by Bengele2** [comment]
i can confirm the same issue with one of my devices.
Device: XPower2 Android 8.1.0

It works completly fine with a IPv4 Nextcloud and is stuck in "Testing Connection" for a IPv6 Nextcloud.
via the Browser everthing works just fine.

**Comment by AlvaroBrey** [comment]
I've marked this issue for auto-stale, because the IPv6 issue has been fixed and will be released soon (has already been released in 3.19.0 RC2). If anyone tests 3.19.0/RC2 and still has this same issue, please reply and we'll look into it some more.

**Comment by muava12** [comment]
still have this issue

**Comment by kekersdev** [comment]
Experiencing the same issue

**Comment by iamtherobin** [comment]
I am experiencing this issue. My Nextcloud app will not connect if my android device is connected on Wifi with an IPv6 address.

Both my android and host machine have working IPv6 connectivity. I can connect on my android via the web browser perfect fine. But the app will stall out when trying to establish connection over IPv6.

Meanwhile, Nextcloud Talk app is not suffering from this issue.
