### ISSUE TITLE
Stop music when bluetooth headset disconnects

### ISSUE THREAD

**Issue by jsilence** [nextcloud/android#925]
### Actual behaviour
- Playing music straight out of the app is awesome!  There is just one minor nitpick: When a bluetooth headset is turned off, the playback does not stop, but it continues over the internal speaker of the mobile phone. 

### Expected behaviour
- When disconnecting the BT device, stop/pause playback.
 
### Steps to reproduce
1. Upload a sound file via nextcloud sync
2. Pair a BT headset with the phone
3. Start playback by clicking on the file in nextcloud app
4. enjoy playback
5. turn off BT headset
6. Experience mobile phone speakers blaring at you

### Environment data
Android version: 7.1

Device model: Nexus 6P

Stock or customized system:  Stock Android

Nextcloud app version: 1.4.2

Nextcloud server version: current

**Comment by tobiasKaminsky** [comment]
I am unsure if this can be handled by the app.
If you are playing a music file and then pair the BT heandset, it will also switch sound from internal to BT without an user interaction, or?
So I guess the opposite way is also done via android itself..

**Comment by jsilence** [comment]
Other music playing apps like Spotify or VLC work the expected way: If the BT headset is turned off, playback of music pauses rather than switching to the internal speakers.

**Comment by AndyScherzinger** [comment]
@esafirm from my point of view, sure, go ahead! :+1:
