### ISSUE TITLE
Cannot download a video.

### ISSUE THREAD

**Issue by fairking** [nextcloud/android#9252]
The Android Nextcloud app. Please guys, how on earth am able to download a file to be able to attach to other app (eg. sending a video via messenger). Is the any option Save As to copy the file to home location (eg Documents, Downloads, Video, Music, etc.)???

Thanks.

**Comment by AndyScherzinger** [comment]
Please @fairking be nice and when reporting things fill out the issue template and tell us what you run???

If it is 3.18.0 RC than RC5 will fix it which you would have found out yourself when using the search field for issues.

Cheers.

**Comment by fairking** [comment]
Pleas feel free to close the ticket it's been fixed in RC5. Thank you so much. 💯

**Comment by AndyScherzinger** [comment]
Happy to hear 🎉
