### ISSUE TITLE
add a command to go back to root folder

### ISSUE THREAD

**Issue by jkumeboshi** [nextcloud/android#9255]
In the main view, just nearby the floating "add new" button (+), if would be useful to add add another button to navigate back to the root/home folder.
This would be quite useful when you in a very deep sub folder.
An alternative would be to replace the current folder Label with a combo box that if clicked allow you to chose any of the parent folders.
![immagine](https://user-images.githubusercontent.com/25344258/141494288-62acc68e-d3cf-4714-a280-347d82ffa290.png)

**Comment by AndyScherzinger** [comment]
@jkumeboshi looking at your screenshot, your app version is suuuuper old and also custom sicne we do not have this "H" button in our app, so this is not the official App. On our app you could just swipe from the very left to right opening the main menu and click on "all files" and you will be put back into the root folder.

**Comment by jkumeboshi** [comment]
Ehm, sorry... the screenshot was from the one in github project home, too lazy to transfer an updated one from my phone -_-
Actually, I didn't notice that one could recall the main menu sliding left to right...

**Comment by AndyScherzinger** [comment]
Ah, yeah, the screenshots in the project are very old didn't realize that when looking at the screenshot you posted :D
