### ISSUE TITLE
going back from file details in a search result shows "no items"

### ISSUE THREAD

**Issue by jkumeboshi** [nextcloud/android#9256]
In the search result you can select item->menu->details. When you get back, search result shows "no items"

### Steps to reproduce
1. from home/root screen enter a term in the search box
2. from result list click on the "..." menu and chose details
3. from details item click on the back button (either the app "<-" button or android's back)

### Expected behaviour
- I expect to get back to search results

### Actual behaviour
- the view shows "no items"
- 
### Environment data
Android version:
Androdi 11 (MIUI 12.5.1)

Device model: 
Mi 9T Pro

Stock or customized system:
MIUI 12.5.1

Nextcloud app version:
3.17.1

Nextcloud server version:
22.2.0

Reverse proxy:
Traefik

**Comment by joshtrichards** [comment]
While this was before Unified Search, it's still valid. Let's keep tracking it in #686 (which also predates Unified Search but since the behavior is still happening we kept it around to track it).
