### ISSUE TITLE
Nextcloud won't open https links

### ISSUE THREAD

**Issue by daywalk3r666** [nextcloud/android#9269]
### Steps to reproduce
1. Open the app and tap on To the source code
2. Same as if you check for update
3. 

### Expected behaviour
A browser should open the ooen the link

### Actual behaviour
Nextcloud says there no app available for opening links

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:11

Device model: Oneplus 5t

Stock or customized system: LineageOS 18.1

Nextcloud app version: Nextcloud dev 20211111

Nextcloud server version: 21.0.1.1

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AlvaroBrey** [comment]
https://github.com/nextcloud/android/pull/9242 fixes this
