### ISSUE TITLE
3.18.0 RC5: upload from camara doesn't work

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/android#9270]
![Screenshot_20211114-194605_1](https://user-images.githubusercontent.com/24530680/141737740-ba8991ec-7367-458d-b67b-61bca38bf628.jpg)

leads to: (but camara rights are assigned)

![Screenshot_20211114-194634_1](https://user-images.githubusercontent.com/24530680/141737748-4a7e8469-abca-4d1c-a842-4a97e7aa54a5.jpg)

**Comment by AndyScherzinger** [comment]
pinging @AlvaroBrey

**Comment by AlvaroBrey** [comment]
Thanks @jakobroehrl, nice catch. Fixed by https://github.com/nextcloud/android/commit/e0fb95fb55b4f3c28687980fd796fc7c71e36195, which will be merged in #9242 before the next release.
