### ISSUE TITLE
[GPlay] Fill-out data safety form

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#9278]
See gplay dev console inbox.

* This info will be displayed starting February 2022
* It gets checked/approved by Google
* Lack of having it by April 2022 will get the app removed

References
https://android-developers.googleblog.com/2021/07/new-google-play-safety-section.html
https://android-developers.googleblog.com/2021/10/launching-data-safety-in-play-console.html

**Comment by AndyScherzinger** [comment]
Pinging @tobiasKaminsky 😉

**Comment by tobiasKaminsky** [comment]
Done.
