### ISSUE TITLE
SSO Dialog looks strange with `3.18` RCs

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/android#9284]
### Steps to reproduce
1. Install any 3rd party Android app like Notes, News, Deck or the sample app from the SSO repository
2. import your account
3. everything is functional, but the dialog looks like it's missing padding

### Expected behaviour
- Dialog should look like with the files app `3.17.1`
![grafik](https://user-images.githubusercontent.com/4741199/142020960-d94c15f7-fdb9-4a7d-ba35-c2536839298f.png)

### Actual behaviour
![sso-dialog](https://user-images.githubusercontent.com/4741199/142020714-6baf4b53-d7a5-4bd8-a35b-939dd4f51bf5.png)

### Environment data
Android version: Android 12

Device model: Emulator

Stock or customized system: Stock with Play Services

Nextcloud app version: `3.18.1-RC6`

Nextcloud server version: Unrelated

Reverse proxy: None

#### Web server error log
Haven't seen anything suspicious in Logcat....

**Comment by AndyScherzinger** [comment]
Seems padding or margin is gone 🤔

**Comment by AndyScherzinger** [comment]
PR is #9290 (replace margin with padding...seems some sdk30 change in how alert dialog styles are handled)
