### ISSUE TITLE
Push notification disabled due to dependencies on google play services

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/android#9285]
### Steps to reproduce
1. Open Nextcloud app
2. Click on Notification tab

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:
Oxygen OS 11.0.3.0.DE17AA "Android 11"
Device model: 
OnePlus N200 5G
Stock or customized system:
Stock
Nextcloud app version:
3.18.0 RC6
Nextcloud server version:
22.2.3
Reverse proxy:
No

https://user-images.githubusercontent.com/59488153/142034223-89704546-2f37-44a8-bcd9-0d497a7f7261.mp4

**Comment by tobiasKaminsky** [comment]
From where have you installed the app?

**Comment by andyxheli** [comment]
I installed it from Nextcloud GitHub rep. Looks like that's the issu I uninstalled it and installed it from Play store and it works.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by AlvaroBrey** [comment]
@andyxheli In our github releases we publish both the google services-enabled APK (`gplay-release-{version}.apk`) and the version without Google Services (`nextcloud-{version}.apk`). This is so people who don't want to use Google Services have a choice.

I'll be closing this as it's solved.

**Comment by stoneubi** [comment]
Same here. I do have my own hosted nextcloud server. On my mobile phone I try everything to disconnect from Google services. I use FoxyDroid to download nextcloud client, nextcloud talk from fdroid. Both apps do not support push notifications? Why? I also use different other apps like signal or k9 and so on. I don't have any Google account activated in my mobile and k9 and signal provide push notifications. Only nextcloud not. Why? I would like to have push notifications please. Thank you.
