### ISSUE TITLE
On Device Section has different title

### ISSUE THREAD

**Issue by aleister09** [nextcloud/android#929]
### Actual behaviour
The Title is changed by the last visited section
 
### Steps to reproduce
1. Open App
2. Open Photos
3. Open On Devices (Title = Photos)

### Environment data
Android version:7.1.2

Device model: Nexus 5X

Stock or customized system:

Nextcloud app version:Master

Nextcloud server version:12

**Comment by tobiasKaminsky** [comment]
Can you try it again with latest master? I cannot confirm this.

**Comment by aleister09** [comment]
Sure, It's happening in the latest master
![ezgif com-video-to-gif 6](https://cloud.githubusercontent.com/assets/25756086/25668790/4ee44cfc-2fed-11e7-845d-b57f803eed20.gif)

**Comment by tobiasKaminsky** [comment]
Now it shall working

**Comment by AndyScherzinger** [comment]
merged to master to be shipped with 1.5.0
