### ISSUE TITLE
Multiple Selection is not enable

### ISSUE THREAD

**Issue by aleister09** [nextcloud/android#930]
### Actual behaviour
On Fotos and Favorites the User can't select more than one file and the title says "2 selected"

### Steps to reproduce
1. Open App
2. Open Photos
3. Click and hold a photo to show multiple selection
4. Select another Photo 

### Environment data
Android version:7.1.2

Device model: Nexus 5X

Nextcloud app version:Master

Nextcloud server version:12

**Comment by tobiasKaminsky** [comment]
We are currently enhancing the search (photos and favorites), if you want you can try #896 
This is working on #896
