### ISSUE TITLE
Linuxfabrik/ Nextcloud 

### ISSUE THREAD

**Issue by Halilb1978** [nextcloud/android#9309]
I am not able to access my files in linuxfabrik . I got this e-mail from linuxfabrik today. Our files gone???

The free Nextcloud service is still not available. The problem is a connected storage system that stopped working after an update. We are still waiting for a feedback from the manufacturer, but we fear that the uploaded files are lost. In the case of Nextcloud, this is usually not a problem, since mostly local files are synced with a Nextcloud server, and they are still available locally.

To be clear, the disruption only affects this free service. Our commercial offerings are not affected, as they run on a completely different infrastructure.

We apologize for the inconvenience.

**Comment by AlvaroBrey** [comment]
This sounds like something you should talk about with Linuxfabrik, not a github repo for the Nextcloud Android App. Best of luck with your files though!

**Comment by AndyScherzinger** [comment]
@Halilb1978 also as stated in the texts to posted, it is an issue with the storage itself, so this is not directly related to Nextcloud itself and there is nothing Nextcloud can do, so files synced to any of your devices are then "backed up" anything else if the storage is lost and there is no backup - is gone. And like Alvaro said, best of luck for your files.

**Comment by Halilb1978** [comment]
I were syncing on the phone. But i only have folders no files in them. :(

**Comment by AndyScherzinger** [comment]
Then unfortunately you never opened / downloaded files. The mobile clients download on demand only.
