### ISSUE TITLE
nextcloud client v3.18.0RC5

### ISSUE THREAD

**Issue by akaro1** [nextcloud/android#9310]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
- Tell us what should happen

see only old files (a part) in the client app v318 from the server v22.2.1

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 8.1 

Device model: blackview

Stock or customized system: custom.

Nextcloud app version:
nc v3.18
Nextcloud server version: 22.2.1
in config.php show 22.2.1.2

Reverse proxy: no

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AlvaroBrey** [comment]
Please give a detailed description of the error, with steps to reproduce if possible.

**Comment by akaro1** [comment]
I am sorry i can only describe the NO FUNCTION. How can i see error? Please explain me how. 
with client app v318 i can not see all file. How can i find errror

**Comment by AlvaroBrey** [comment]
Please describe "I can not see all files" in more detail. I understand that you're missing some files from the "All Files" list?

 If so, do those files appear after a refresh (pull down on list)? Is it something different? 
 
 Also are you using 3.18RC5 (as your title suggests) or the stable 3.18.0 release? If you're using the RC, please update to the stable version.

**Comment by akaro1** [comment]
Ok

 

Thx 4 feedback

 

stable 3.18.0 was not avable, i will check this

 

have good healthy day

 

ALESANDER

mail crypted

 
 

Gesendet: Mittwoch, 01. Dezember 2021 um 09:26 Uhr
Von: "Álvaro Brey" ***@***.***>
An: "nextcloud/android" ***@***.***>
Cc: "akaro1" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [nextcloud/android] nextcloud client v3.18.0RC5 (Issue #9310)


 

Please describe "I can not see all files" in more detail. I understand that you're missing some files from the "All Files" list?

If so, do those files appear after a refresh (pull down on list)? Is it something different?

Also are you using 3.18RC5 (as your title suggests) or the stable 3.18.0 release? If you're using the RC, please update to the stable version.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
