### ISSUE TITLE
Selecting a folder at "Create your own folder" for automatic upload does not work.

### ISSUE THREAD

**Issue by weinic** [nextcloud/android#9334]
Selecting a folder at "Create your own folder" for automatic upload does not work.
See the attached Video.

I would like to select the folder "Katharina", but this does not work.

https://user-images.githubusercontent.com/57099502/142742526-a32f2699-d3eb-4ae2-95d3-ed418a95ac45.mp4

**Comment by AlvaroBrey** [comment]
Duplicate of #8940
