### ISSUE TITLE
Android client deletes local files on server config removal

### ISSUE THREAD

**Issue by realies** [nextcloud/android#9336]
### Steps to reproduce
1. Connect to server
2. Setup folder for auto upload
3. Make server inaccessible (i.e. expired or no longer accessible domain)
4. Remove the server from the app while there's an existing auto-upload queue

### Expected behaviour
- Remove server config

### Actual behaviour
- Remove server config and delete the auto-upload queue of files on the local filesystem

### Environment data
Android version: 11

Device model: S10+

Stock or customized system: No

Nextcloud app version: 3.18.0 RC6

Nextcloud server version: 22.2.3

Reverse proxy: Yes

#### Web server error log
N/A

#### Nextcloud log (data/nextcloud.log)
N/A

This data loss was preventable if the lack of an ability to modify a domain name in the server config was not considered a "sEcUrItY fEaTuRe" by the big brains in #4157. This reconfiguration is very easily possible on desktops, unfortunately requiring rooting on Android, which I was to prefer if I knew about this easter egg ahead of time.

**Comment by AlvaroBrey** [comment]
@realies Sorry that you've had data loss. Was the auto-upload queue configured to delete files on upload?

As a side note, we don't appreciate passive-agressive renames or thinly veiled insults here. If you want people to help, you'll have respect our [Code of Conduct](https://github.com/nextcloud/android/blob/master/CODE_OF_CONDUCT.md), just like everyone else.

**Comment by GAS85** [comment]
> ## Expected behaviour
> 
>     Remove server config
> 
> ## Actual behaviour
> 
>     Remove server config and delete the auto-upload queue of files on the local filesystem

But why you expect that Application will keep this queue if you delete config - whole server from it?

My understanding is that flow if different:
1. Connect to server
2. Setup folder for auto upload
3. Make server inaccessible (i.e. expired or no longer accessible domain)
4. Remove the server from the app while there's an existing auto-upload queue - all will drop
5. Add New Server
6. Configure Auto Upload again
7. Force manual upload of non existing files **or** upload whole folder and Resolve conflicts.

Yes, #4157 could help you in this case, but not with Point 3 - you can't perform redirect if "server inaccessible".
