### ISSUE TITLE
Problem logging in with server address in `ip:port` format

### ISSUE THREAD

**Issue by KrisZurawski** [nextcloud/android#9338]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate
![Screenshot_2021-11-21-14-26-29-144_com nextcloud client](https://user-images.githubusercontent.com/94801437/142774187-4eb569d2-eb62-465d-963b-9063cff13033.jpg)

**Comment by AlvaroBrey** [comment]
Hello @KrisZurawski, please fill in the template with server/app/android versions. Adittionally, does your username contain spaces or special characters?
