### ISSUE TITLE
Allow app to function partially without All Files access on Android 10+

### ISSUE THREAD

**Issue by AlvaroBrey** [nextcloud/android#9343]
On https://github.com/nextcloud/android/issues/9327, users are upset that All Files access is now required on Android 10+ devices.  We should be able to make the app work without this access, although with limited functionality.

## User perspectives

We have the clashing needs of

* Users who want to upload files that normal apps can't access (such as other apps' data. a common one is Whatsapp backups). These users need All Files permission.
* Users who don't want to grant Nextcloud access to their data. These users need the app to function without storage access.
* Finally, less savvy users may just want to upload photos and videos (media collections). This should still work with scoped storage (only READ_EXTERNAL_STORAGE).

### Option A
Implement logic to detect that the permission has been denied and not ask for it again on app startup. **BUT**, we should always ask for the permission again if the user attempts to do something that requires it (setup auto-upload, select files for upload...)

With this option, uploads will be almost completely non-functional without the permission. Browsing server content and downloading/sharing files should still work.
   
### Option B
* Use READ_EXTERNAL_STORAGE so that scoped storage provides access to at least some of the data on external storage
* Allow users to request this permission the first time they try to upload files or setup autoupload (or other access-sensitive tasks)
* Add a shortcut in Settings/Extra to request the  All Files permission later, if the user so desires.

With this option, users would get a choice to let Nextcloud access only media files or all files. It gives the users more choice but is also a bit more confusing (and harder to implement).

This option could also be implemented AFTER option A (first let the app work without uploads, and later get the app to work with the reduced, media-only access).

## Technical context:

Since November, all apps must abide by the new storage rules in Android 10+. These rules mostly consist of:

* The old "access external storage read-write"  permission is no longer available.
* The old "READ_EXTERNAL_STORAGE" permission now only allows access to media collections (mostly photos and videos).
* There is a new "All files" permission, that requires approval by Google and allows similar access to what we had before. This is what we're currently using.
   * Additionally we *require* this permission for the app to work now. It isn't optional, as some stuff was broken without it.
* The new "All files" permission grant UX is scarier for the user. They get taken to a system dialog where they have to manually flip a switch and read that Nextcloud will have access to all data. This is an intentional privacy-aware change on Google's part.
* Downloads to our private storage should still function without All Files access.

**Comment by AlvaroBrey** [comment]
@AndyScherzinger @tobiasKaminsky @jancborchardt input is appreciated!

**Comment by Shrizt** [comment]
vote for opt B
it's common for any app to request access to media files, and feels much more harmless than access to all files on device.

**Comment by AndyScherzinger** [comment]
Well, to me option be would be the nicer way to deal with it while having A first and then be sounds nice but for me depends on if A would be a low hanging fruit and can be done quickly. If not I'd go straight for option B.

**Comment by silsha** [comment]
For reference, this is what it looks like when I don't agree to access Photos on iOS and want to enable auto-upload.
(On iOS, it's not possible to ask for permissions a second time. The user has to go to the system settings).

![IMG_2701](https://user-images.githubusercontent.com/31850/143209227-a8d2c223-01cc-40c4-97f8-105db769e8f4.PNG)

**Comment by AndyScherzinger** [comment]
Yeah, but iOS is different and so is Android with Android 11 where there are still the "mild" permissions which you can simply ask for with the standard OS dialog popping up and the "broader, wider permissions" that now need to refer you to the system's apps settings, which is what we do right now.

**Comment by dznsm** [comment]
Is there a reason you cant just use ACTION_OPEN_DOCUMENT_TREE to allow the user to pick (almost) any directory that they want Nextcloud to be able to access/write/edit rather that having to use 'all files'?

**Comment by jancborchardt** [comment]
@AlvaroBrey from the sound of it, it’s less "Option A" and "Option B" but rather "Step 1" and "Step 2" in a process, right? So it would make sense to start with step 1? Ideally we would then have the permission question modal ask for:
- All files (default selected?)
- Media files only
- Reject
(Or how would that modal look like?)


> Is there a reason you cant just use ACTION_OPEN_DOCUMENT_TREE to allow the user to pick (almost) any directory that they want Nextcloud to be able to access/write/edit within, rather than having to use the 'all files' permission?

@dznsm yes, because Nextcloud aims to be easy to use for a general audience, and showing a whole document tree is much too complicated, time-consuming and not really necessary considering there will be the 3 options eventually.
