### ISSUE TITLE
Deep links to Nextcloud not working in android 12

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/android#9346]
I am afraid this is not working with Android 12 anymore. 
Tested with a Pixel smartphone. 
Removed NC App and installed it again, no change.

**Comment by AlvaroBrey** [comment]
Hi @jakobroehrl. Can you give steps to reproduce and expected result? I am not entirely sure what you're referring to in this issue.

**Comment by jakobroehrl** [comment]
Sure. 
There is a function to recognize nextcloud links and instead of open this in a browser the andoid app will be opened. 
But since Android 12 only the browser opens. 
@szaimen

**Comment by szaimen** [comment]
I can't reproduce that. It works for me on Android 11 with 3.18.0. But it is definitely possible that something changes on Android 12 that breaks the feature.

**Comment by szaimen** [comment]
@jakobroehrl maybe you could add some steps to reproduce so that Alvaro is able to try to reproduce it?

**Comment by AlvaroBrey** [comment]
Most likely related: https://developer.android.com/about/versions/12/behavior-changes-all#web-intent-resolution

If this is behaving as described, we likely will have to implement domain association logic in Android 12 (as in, ask the user to confirm that the domain should be opened with the Nextcloud app). This probably should be done when the account is configured.

Ref:  https://developer.android.com/training/app-links/verify-site-associations#request-user-associate-app-with-domain

**Comment by jakobroehrl** [comment]
> @jakobroehrl maybe you could add some steps to reproduce so that Alvaro is able to try to reproduce it?

Take a Android 12 phone, tip on a deep link, the link will be open in the android app (if not, reinstall the android app)
Take a Android > 12 phone, tip on a deep link, the link will be open in the browser

**Comment by AndyScherzinger** [comment]
cc @schiessle this is from yesterday, so yes issue with Android 12 (his and my phone run Android 12)

**Comment by InQuize** [comment]
Too bad such a fundamental feature does not deserve a uniform experience priority.
Seamless transition between web and native apps is a must for file-sharing tool.

**As a crude workaround**, normal `https://` links open in Android app using `Share` button to `Open Link With...` [Android app](https://play.google.com/store/apps/details?id=com.tasomaniac.openwith)
Alternatively, this 3rd party app may act as a (default) browser itself and redirect to native apps for each domain according to your choice (once / every time).

In my case, I was hoping to use Nextcloud sub-folder as a root for catalog of electronic component stock. To be able to print QR encoded local links to the corresponding storage places (NC folders) and individual items (NC files). It was a bad start.

**Comment by tobiasKaminsky** [comment]
Investigated and spent a lot of time in it.
With Android 12 we are not allowed to use "*" to catch any domain, which is needed.
We can only add specific domains during build time, which is not feasible for self hosted servers.

Thus this is unfortunately a feature that is now broken by Android.
