### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by maxcodeir** [nextcloud/android#937]
I load a project I get these errors:
Error:A problem occurred configuring root project 'android-master'.
> Could not resolve all dependencies for configuration ':_modifiedDebugApkCopy'.
   > Could not find com.android.support:multidex:1.0.1.
     Required by:
         project :
   > Could not find com.android.support:support-v4:25.0.0.
     Required by:
         project :
   > Could not find com.android.support:design:25.0.0.
     Required by:
         project :
   > Could not find com.android.support:appcompat-v7:25.0.0.
     Required by:
         project :
   > Could not find com.android.support:cardview-v7:25.0.0.
     Required by:
         project :
   > Could not find com.android.support:support-annotations:25.0.0.
     Required by:
         project : > com.getbase:floatingactionbutton:1.10.1
   > Could not find com.android.support:support-annotations:25.0.0.
     Required by:
         project : > com.github.evernote:android-job:v1.1.9
   > Could not find com.android.support:support-annotations:25.0.0.
     Required by:
         project : > com.jakewharton:butterknife:8.4.0
         project : > com.jakewharton:butterknife:8.4.0 > com.jakewharton:butterknife-annotations:8.4.0
   > Could not find com.android.support:support-annotations:25.0.0.
     Required by:
         project : > com.github.evernote:android-job:v1.1.9 > net.vrallev.android: cat:1.0.5

**Comment by mario** [comment]
You should switch to a generic build target - that will solve the issues.

**Comment by tobiasKaminsky** [comment]
Note: generic should be the default as the flavours are sorted alphabetically and the first one is used.
If you want to use modified, you have to uncomment two lines in build.gradle, just search for modified.
