### ISSUE TITLE
Search placeholders don't make sense in Unified search

### ISSUE THREAD

**Issue by AlvaroBrey** [nextcloud/android#9371]
Search placeholders reference "this folder". As unified search is global, that doesn't make much sense.

**Comment by joshtrichards** [comment]
Can you describe a scenario where this happens? Or perhaps this was already addressed (I'm not seeing it anywhere).

**Comment by AlvaroBrey** [comment]
It seems fixed 👍  Placeholder in searchbar is just `Search...` now
