### ISSUE TITLE
Sharing: expiration date calendar doesn't fit in dialog properly

### ISSUE THREAD

**Issue by AlvaroBrey** [nextcloud/android#9377]
### Steps to reproduce
1. Try to share a file with another user
2. Set an expiration date, and click the calendar

### Expected behaviour
- The calendar is appropriately sized to the dialog it appears in

### Actual behaviour
- The calendar either has weird margins or is moved to a side and compressed. This is specially noticeable after rotating the screen.

### Environment data
Android version: 11

Device model: emulator

Stock or customized system: stock

Nextcloud app version: 3.18.0

Nextcloud server version: 22

**Comment by tobiasKaminsky** [comment]
I tried to recreate dialog, but then it fails when opening dialog in portrait and then switching to landscape.
