### ISSUE TITLE
Android lint

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#938]
Run target "android lint" and fix issues.

This is a nice way to do it:
https://medium.com/yplan-eng/stop-ignoring-android-lint-use-it-8a8ee2ca6af8

It consists of multiple steps:
- enable lint to break on any lint errors
- configure lint.xml to treat warnings step by step as errors
  - fix one warning category
  - treat them as error in lint.xml
  - repeat with remaining categories

So if you are fine with this, I will start soon to fix all lint errors and enable lint on drone.

**Comment by tobiasKaminsky** [comment]
@mario @AndyScherzinger
explained idea a bit more, please confirm if you agree.

**Comment by AndyScherzinger** [comment]
:+1: Agreed

**Comment by tobiasKaminsky** [comment]
Additional we can add this one: https://github.com/tir38/android-lint-entropy-reducer
It is a script which fail if new errors/warnings arise.
With this we can omit the upper approach, but still fix errors/warnings from time to time.

**Comment by tobiasKaminsky** [comment]
Implemented the second way in #982
