### ISSUE TITLE
Empty placeholders improperly positioned in landscape

### ISSUE THREAD

**Issue by AlvaroBrey** [nextcloud/android#9392]
### Steps to reproduce
1. Have no files
2. Put the phone in landscape

### Expected behaviour
- Empty placeholder is shown in the middle of the screen, or at least is scrollable

### Actual behaviour
- Empty placeholder is either cut off, or has no margin at the bottom, and scroll doesn't work

### Environment data
Android version: 11

Device model: emulator (pixel4)

Stock or customized system: stock

Nextcloud app version: 3.18.0

Nextcloud server version: 22

Reverse proxy: no

**Comment by tobiasKaminsky** [comment]
First attempt for a solution: https://github.com/nextcloud/android/pull/9478
