### ISSUE TITLE
Problem synching a folder from Nextcloud on mobile android device

### ISSUE THREAD

**Issue by ChibiYuzu** [nextcloud/android#9401]
### Steps to reproduce
- open the nextcloud app in an android mobile device
- select a folder
- ask for the sync

### Expected behaviour
- the sync should start so that I can access the folder's content from my mobile device

### Actual behaviour
- I receive the following error message when trying to sync the folder:

************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object com.nextcloud.java.util.Optional.get()' on a null object reference
	at com.owncloud.android.files.services.FileDownloader.downloadFile(FileDownloader.java:486)
	at com.owncloud.android.files.services.FileDownloader.access$500(FileDownloader.java:87)
	at com.owncloud.android.files.services.FileDownloader$ServiceHandler.handleMessage(FileDownloader.java:422)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.os.HandlerThread.run(HandlerThread.java:67)

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20211119
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: samsung
Device: o1s
Model: SM-G991B
Id: RP1A.200720.012
Product: o1sxxx

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: G991BXXS3AUJ7

### Can you reproduce this problem on https://try.nextcloud.com?
I tried but I can't even launch it. 
- 
- ### Environment data
Android version:
11
Device model: SM-991B

Stock or customized system:

Nextcloud app version:20211119

Nextcloud server version: NA

Reverse proxy: NA

**Comment by AlvaroBrey** [comment]
This was only in the dev version and has been fixed since ([#download cra](https://github.com/nextcloud/android/pull/9350). Please update your app and reopen if the error persists.

**Comment by ChibiYuzu** [comment]
Hello!

Thank you for the feedback. I switched to the regular version and it works fine.

Ariane Beldi

Le 30 novembre 2021 14:08:22 GMT+01:00, "Álvaro Brey" ***@***.***> a écrit :
