### ISSUE TITLE
Does not scan new files added to filesystem

### ISSUE THREAD

**Issue by thephm** [nextcloud/android#9410]
### Steps to reproduce
1. Install Nextcloud on Android
2. Install Obsidian on Android
3. Create a Vault in Obsidian that uses Nextcloud Notes folder (see attachment) 
4. Add a note in Obsidian

### Expected behaviour
- file appears in Nextcloud app and is sync'd to the server

### Actual behaviour
- file never appears and I have to manually upload it
![Screenshot_20211130-233409_My Files](https://user-images.githubusercontent.com/8527588/144173882-a18a1dc0-3837-43a1-a58f-2b3ca8b72e62.jpg)

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 11

Device model: Samsung S20 5G

Stock or customized system: Stock

Nextcloud app version: 3.18.0

Nextcloud server version: 22.2.3

Reverse proxy: 

#### Web server error log
```
n/a
```

#### Nextcloud log (data/nextcloud.log)
```
n/a
```

**Comment by iGadget** [comment]
Correct me if I'm wrong, but apart from photo / video folders which can be used with the 'auto upload' feature, I don't believe the mobile apps sync any content automatically which is added locally.

**Comment by AlvaroBrey** [comment]
You need to setup an autoupload folder in order for things to be uploaded automatically. You can do this from Settings, although there's a couple of bugs with it currently.

**Comment by thephm** [comment]
I'm not looking to add auto upload folder. My thinking is the app should recognize when a file is added to existing syncd folders even if added outside. Maybe that could be an enhancement. Adding the Notes folder as an Auto sync folder worked so that's an acceptable workaround for me thanks! One odd thing is that the file is syncd but doesn't show up in the Nextcloud app. It does however show up in the Nextcloud Notes app. 
![20211201_073402](https://user-images.githubusercontent.com/8527588/144235259-7da5b0a1-9cf3-4ea6-81c5-483e14562692.jpg)

**Comment by thephm** [comment]
Actually, it's not acceptable since it's only an upload when what is needed is a sync

**Comment by thephm** [comment]
Can this be re-opened please or do I need to submit it separately as a feature request?

**Comment by stevenre3d** [comment]
The default behavior of Nextcloud all other platforms (that I've used it on) is: if you add a new file to a Nextcloud folder -> it is automatically synced. Why on android is that behavior considered an optional feature request? Is this an android limitation?

Also using Two-Way Sync isn't an option because it doesn't work recursively: #269. As noted in that thread, you can't even add every subfolder individually, because selecting Sync on a parent will check the Sync box for the children, yet they won't be periodically synced.
