### ISSUE TITLE
Device trigger brute force protection when token is invalidated in the server

### ISSUE THREAD

**Issue by CarlSchwan** [nextcloud/android#9412]
### Steps to reproduce
1. Connect to a nextcloud server
2. In the nextcloud server, remove the token for the new android device

### Expected behaviour
- The android device ask the user to log again
- 
### Actual behaviour
- The android device tries to reconnect and triggers brute-force protection

### Environment data
Android version: unknow

Device model: unknow

Stock or customized system: I guess stock

Nextcloud app version: 3.18.0

Nextcloud server version: 20

Reverse proxy: unknow

**Comment by AlvaroBrey** [comment]
Reproduced with NC22 and app 3.18.0 in any emulator

**Comment by AlvaroBrey** [comment]
@tobiasKaminsky did we fix this? I tested it today with app&server master and it seems to work properly (login screen shows up)

**Comment by AlvaroBrey** [comment]
It seems like this was fixed at some point between 3.18.0 and 3.19.1, but I can't bisect to find the exact commit due to the snapshot dependencies in build.gradle.

@CarlSchwan Can you still reproduce this in current versions?

**Comment by AlvaroBrey** [comment]
Apparently bruteforce protection is still triggered if account is disabled entirely
