### ISSUE TITLE
Update app to take advantage of the larger aspect ratio on latest Android devices

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#943]
see https://android-developers.googleblog.com/2017/03/update-your-app-to-take-advantage-of.html

The recommendation is to add
```
<meta-data android:name="android.max_aspect" android:value="2.1" />
```
to support aspect ratios of 2.1 or higher. Else if we don't set a value, and ```android:resizeableActivity``` is not ```true```, then the maximum aspect ratio defaults to 1.86 (roughly 16:9) and the app will not take advantage of the extra screen space. This would be the case for a Samsung Galaxy S8 for example.

**Comment by tobiasKaminsky** [comment]
Is there then a space between our app and the edge of the display?

**Comment by AndyScherzinger** [comment]
yes, see the screenshot in the article I referenced

**Comment by tobiasKaminsky** [comment]
Then let us do this and test it on an emulator, as I doubt that anyone has an S8.

**Comment by AndyScherzinger** [comment]
Not sure if we can test it in an emulator since we would need a device image with that aspect ratio :/

**Comment by mario** [comment]
@AndyScherzinger you can create emulators with custom resolution / aspect ratio.

**Comment by mario** [comment]
We actually already have an issue for this: #799 
Anyway, I believe this needs to be done for 1.5 so marking it as such.

**Comment by AndyScherzinger** [comment]
Argh, missed that issue, sorry for the duplicate. Closing #799 in favor of this one.

**Comment by tobiasKaminsky** [comment]
So, I wanted to get rid of the outstanding 1.5 issues, but I cannot verify this on an emulator.
Every app (e.g. amaze, fdroid, nextcloud) is working out of the box with a 800x1800 (2.2:1) ratio.

Three options:
- create a PR and put it in dev and see if someone gives feedback
- do nothing
- give me such a device

**Comment by tobiasKaminsky** [comment]
How to proceed with this?

**Comment by AndyScherzinger** [comment]
No idea really. I tried to reproduce the behavior described in Google's article but couldn't so I'd be fine with postponing it.

**Comment by mario** [comment]
Moving to 1.5.1 since we have no idea right now.

**Comment by AndyScherzinger** [comment]
> Images getting cropped on the right side when previewing.

Reported via the developer console as a user review where my guess is that this is related to the aspect ratio.

**Comment by mario** [comment]
I've set the value to 10 just in case for Talk.

Though with newer SDKs android:resizeableActivity is true by default.

**Comment by joshtrichards** [comment]
No longer applicable w/ targetSdkVersion >= 24
