### ISSUE TITLE
"Server not available" when username is email address

### ISSUE THREAD

**Issue by liam-p-23** [nextcloud/android#9439]
### Steps to reproduce
1. Run the Nextcloud project cloned from Github on an emulator using Android Studio
2. In the app, log in using a provider (e.g. CloudFiles)
3. After logging in and being taken to the main 'All Files' screen, the app shows the 'Server not available' message

### Expected behaviour
- The app should connect to the provider and display the files

### Actual behaviour
- The app fails to connect to the provider and shows the 'Server not available' message
- I have been encountering this issue for several days now and it is not localized to a single provider
- If using the Nextcloud app from Google Play on the same device, files are retrieved from the provider without issue

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 30

Device model: Pixel 2 Emulator (issue also appears on a physical device)

Stock or customized system:

Nextcloud app version: Latest version cloned from GitHub

Nextcloud server version: Issue appearing with Woelkli and CloudFiles

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
com.nextcloud.client E/ReadFileRemoteOperation: Read file / failed: Unexpected exception
com.nextcloud.client E/RefreshFolderOperation: Checked my_email@free.files.cnow.at/ : Unexpected exception
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AlvaroBrey** [comment]
Do you have spaces or other non-alphanumeric characters in your username? There is a known issue (#9331) with that which will be fixed in the next bugfix release

**Comment by liam-p-23** [comment]
@AlvaroBrey The Woelkli account that I am using to log in with has an email address as the username.

**Comment by AlvaroBrey** [comment]
Verified happening only with email usernames

**Comment by liam-p-23** [comment]
@AlvaroBrey In the meanwhile, do you know of any temporary workarounds I could use that would enable the app to read from the server?

**Comment by AlvaroBrey** [comment]
@liam-p-23 fixed in https://github.com/nextcloud/android-library/pull/773 which we will merge shortly to library master. Once that happens, just rebuilding should fix the issue as the `master-SNAPSHOT` version should get updated.
