### ISSUE TITLE
Title bar covers top of video when not full screen

### ISSUE THREAD

**Issue by seanthegeek** [nextcloud/android#9453]
### Steps to reproduce
1. Start playing a video without making it full screen (you may need to rotate your phone to reproduce this

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Environment data
Android version: 11

Device model: Samsung Galaxy S20

Stock or customized system: Stock

Nextcloud app version: 3.18.20

**Comment by AlvaroBrey** [comment]
Should be fixed by now, as there have been UI updates to the player screen
