### ISSUE TITLE
Android app Media section loading issues (maximum 15 rows of photos)

### ISSUE THREAD

**Issue by nonyhaha** [nextcloud/android#9473]
### Steps to reproduce
1. open latest version of nextcloud Android app (3.18.0)
2. go to media section
3. let photos load
4. only 15 rows of photos are laoded per folder!
5. if I resize the columns per row, it will load fewer/more photos, but in total there will always be 15 rows!

### Expected behaviour
- all photos from one folder should be loaded

### Actual behaviour
- only 15 rows * columns of photos are laoded. So either 15, 30, 45, 60 or 75 photos maximum,

### Can you reproduce this problem on https://try.nextcloud.com?
- on the browser version of media, all photos are laoded correctly. 

### Environment data
Android version: 11
Device model: 
Galaxy S10
Stock or customized system:
Stock
Nextcloud app version:
3.18.0
Nextcloud server version:
22.2
Reverse proxy:
HAproxy

I am not sure if this should be tied to #7245. I did not find anybody discussing about this 15 rows limit?

**Comment by nonyhaha** [comment]
I just upgraded the server to v23 stable also, issue persists on android app.

**Comment by AlvaroBrey** [comment]
Should be fixed by new media view on 3.20+
