### ISSUE TITLE
checking for update steals focus/clears the search bar

### ISSUE THREAD

**Issue by svenb1234** [nextcloud/android#9481]
If one opens the app a turning circle tells me that the app is checking for updates. This takes some seconds. While it is turning one can already type in the search bar at the top of the app. However, as soon the check has finished and the turning circle disappears, the app also clears the search bar and steals the focus.

Expected behaviour would be to not clear the search bar, i.e. the text in it, and not steal the focus. That way one could continue typing and start the search.

**Comment by siccovansas** [comment]
I used to have this problem as well, but I can't reproduce it anymore. I think this issue was solved in a recent update.

**Comment by svenb1234** [comment]
Yep, seems fixed. Thanks!
