### ISSUE TITLE
Easy way to Download Files on Android

### ISSUE THREAD

**Issue by woodboy12** [nextcloud/android#9519]
### Is your feature request related to a problem? Please describe.
Trying to download a picture to use as a contact picture on Android. Tried every way I could see with the app.  Appears to be no easy way to just download a picture to my phone. I tried share to contacts and it failed. When I thought I downloaded the picture, when I used the native samsung file explorer, a folder was there, but no file. A folder took on the name of the picture file. But no pictures we in the folder. I tried to share to the gallery, it looks like it did,  but then no picture was in the gallery from the NextCloud app was there

### Describe the solution you'd like
Download files to an easy to find location on my android phone. Like the download folder
### Additional context

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by Extarys** [comment]
I got a new phone today and I also had some issues with this too. On my nextcloud instance I have a folder called Ringtones. I downloaded one file and had to go through a lot of steps to take the file and move it in the android `/Ringtones` directory.

- Open Nextcloud and navigate to the file
- Download the file
- Open File manager
- Can't find file
- Go in Nextcloud settings
- Find the path
- Open File manager
- Go to `/Internal/Android/media/com.nextcloud.client/nextcloud/myusername@nextcloud/FolderA/FolderB/Ringtones`
- Long press > Copy then select the destination

I would like an option like `Download to`. I believe it would solve most headaches. When you select `Download to...` and its a picture, the default folder inside the file manager could be `/Pictures`.

Note that I use AOSP, so I believe a nice approach would be to ask the user for the File Manager app they prefer. Or maybe this can be all done inside the Nextcloud app directly?
The basic DocumentsUI have a `Nextcloud` item for easy navigation, but I use https://github.com/zhanghai/MaterialFiles as it allows adding SMB shares, but Nextcloud isn't there. I even asked the author why as I'm not familiar with how Android works in the backend. (https://github.com/zhanghai/MaterialFiles/issues/640)

**Comment by major-mayer** [comment]
I can confirm this on my POCO F3 using AOSP.
Neither Google Photos nor any other app is able to discover images that i downloaded with the Nextcloud app.

I don't know why, but when i download files from Nextcloud to my device, it saves them in /internalStorage/nextcloud/user@nextcloud.com/path/to/file. 
But even then, no other app is able to find the downloaded files (especially images).
I always have to move them with a file manager from /internalStorage/nextcloud/user@nextcloud.com/... to something like /internalStorage/Downloads/ and then they appear.

This is very frustrating and way too complicated for most users.

**Comment by DaleJP** [comment]
I assumed this feature would be present, and spent months researching and preparing to deploy Nextcloud in a school. Having finally deployed it yesterday, I have found that the lack of this feature has ruined my life and the perception of the new system for the users🤣. 
The teachers need to be able to share media with each other in the Talk app and then upload them to another learning journal app for the parents.
Not being able to download the image to their camera roll or have it detected in Pictures basically means they won't use it and I have completely wasted my time.

And no, I will not be asking them to install another random app on their phone for this functionality. They will laugh at me.

Dammit, dammit, dammit.

Just give me a "Save to Camera Roll" option, please....... pretty please?

**Comment by tobiasKaminsky** [comment]
We are working on this.

> The teachers need to be able to share media with each other in the Talk app and then upload them to another learning journal app for the parents.

Meanwhile you can recommend them to use the regular Android way and share the specific file from Android Files to the other app.
That is similar to the same when you e.g. want to sent an image received in Whatsapp via Email.
Then one also does not save the image from Whatsapp to some download location, then open up email and try to find the image, but rather share the image directly to the email app.
(this way also no outdated / duplicated files lay around on device)



> Just give me a "Save to Camera Roll" option, please....... pretty please?

Downloaded images are already shown in "camera roll" (which is more of an iOS term), but right now only <=Android 10.

**Comment by DaleJP** [comment]
Thank you Tobias for replying, I didn't expect it.

I am very glad to hear this is something you are working on. I thought it might be like the issue I have with live transcoding of shared videos (for students and parents to watch on phones etc.) and just end up being something not perceived as necessary.

> Meanwhile you can recommend them to use the regular Android way and share the specific file from Android Files to the other app.
This works on my phone (Galaxy Flip 3) for individual photos/videos but not on the lead teacher's phone (an s20). He is also the one most resistant to Nextcloud and it was really frustrating to hear him be able to say "See, it doesn't work." Our usual workflow for pictures taken on the camera or downloaded via another app is to write the observation in the other app, tap "upload images" and they are just there. This doesn't happen with Talk.

> Downloaded images are already shown in "camera roll" (which is more of an iOS term), but right now only <=Android 10.

Sorry, I mean Gallery/Photos/Camera/DCIM/Files. How do you download the images? Isn't that the very feature I'm requesting? "Share" is the only option I see.

**Comment by major-mayer** [comment]
Great work, thank you Tobias ❤️

**Comment by DaleJP** [comment]
Wow. Fantastic, thank you!
