### ISSUE TITLE
App stuck in Loading spinner while thumbnails are being generated

### ISSUE THREAD

**Issue by timtierney** [nextcloud/android#955]
### Actual behaviour
When the android app is generating/loading thumbnails, I click on an image (even one with a thumbnail already generated).  When the download progress bar completes, the app shows a Loading spinner and gets stuck loading.

If I Force Close and restart the app and navigate to the same folder and stay in a section where all the thumbnails are already generated, pictures load just fine.

### Expected behaviour
Pictures should download, loading screen should show (I assume) and the picture should become visible when the app is finished loading
 
### Steps to reproduce incorrect behavior
1. Enter Photos folder
2. Scroll to section with missing thumbnails and wait for the app to start generating thumbnails.
3. Click on a picture to start loading (this can be a picture that's already cached on the phone.  It doesn't matter which picture)
4. Wait for the picture to finish downloading and the white Loading spinner screen appears.  That's where it gets stuck!

### Steps to reproduce expected behavior
1. Enter Photos folder
2. Keep grid scrolling position in an area where all thumbnails are already generated.  (None need to be generated)
3. Click on a picture to start loading (this can be a picture that's already cached on the phone.  It doesn't matter which picture)
4. Picture loads just fine!  Almost instantly after the download process.

### Environment data
Android version:
6.0.1
Device model: 
Galaxy S6 Phone and Galaxy Tab S2
Stock or customized system:
Stock
Nextcloud app version:
Tested with current stable version 4.4.2 in Play store and dev version:  20170430
Nextcloud server version:
11.0.3
#### Web server error log
N/A - None since mid April.  I was able to reproduce the error today and no web server log entries were made.

#### Nextcloud log (data/nextcloud.log)
See attached file from April - May
[nextcloud.txt](https://github.com/nextcloud/android/files/976711/nextcloud.txt)

**Comment by timtierney** [comment]
Still an issue in 20170527 on tablet and phone.

**Comment by tobiasKaminsky** [comment]
Right, this happens as both, loading image and downloading thumbnail, are async tasks which are executed in the way they are added (fifo).

I'll try to set a higher priority to loading task.

**Comment by tobiasKaminsky** [comment]
PR is #1149

**Comment by timtierney** [comment]
I saw the merge, milestone, "Ready for Dev" label on #1149.  When would this be ready for release on the dev version of the app?  I'm excited to try the fix.

**Comment by tobiasKaminsky** [comment]
it should be in dev version since the last few days.
Please let us know if it is working as expected.
Note that it can still have a little delay as the current thumbnail downloading process may have to be completed.

**Comment by tobiasKaminsky** [comment]
@timtierney have you tried it? what is your experience?

**Comment by timtierney** [comment]
Sorry for the delay checking this out.  Running 20170701, it works great.  Don't know what else got changed but the whole app seems quicker/smoother.  I like it!  :)
