### ISSUE TITLE
Files don't get properly downloaded when external storage is selected

### ISSUE THREAD

**Issue by Thovi98** [nextcloud/android#9557]
### Steps to reproduce
1.  Choose external storage location
2.  Download a file (I tried with photos)

### Expected behaviour
Successful download in the right location.

### Actual behaviour
When external storage is selected, files fail to download. They do get downloaded to the tmp folder in the external storage, but they don't get transferred to the main external directory and download ends with Failed message.

### Environment data
Android version: 11 MIUI 12.5.3

Device model: Xiaomi Redmi Note 10

Stock or customized system: stock

Nextcloud app version: 3.18.0 (and 3.18.1RC2)

Nextcloud server version: 22.2.3

Reverse proxy: nginx

**Comment by Thovi98** [comment]
Mmh I couldn't reproduce on latest Fdroid Nextcloud Dev build !
I don't know if it's resolved or if it's stable release specific ?

**Comment by Thovi98** [comment]
In the logs inside the app, there is:

```
2021-12-16-20:07:18 | DownloadFileRemoteOperation
Download of [server directory] to [storage/04DD-AF66/Android/media/com.nextcloud.client/nextcloud/tmp/[Android directory]/[file.jpg]]: Operation finished with HTTP status code 200 (success)

```
```
2021-12-16-20:07:18 | DownloadFileOperation
Download of [server directory] to [storage/emulated/0/Android/media/com.nextcloud.client/nextcloud/[directory]/file.jpg]]: Error while moving to final directory

```

**Comment by Thovi98** [comment]
After reinstalling the stable app, it works great, strange 🤔

**Comment by AlvaroBrey** [comment]
If this failed after the upgrade to 3.18.0, it's possible that there was a problem with permission migration. Some users reported similar problems that were solved by removing and re-approving the Files Access permission for the app.

In any case, thanks for your report, but if it's not reproducible anymore, we should close this.

**Comment by HellsBells24** [comment]
I'm not sure I if this is the same issue but I've noticed that on my OnePlus 9 Pro running Lineage with MicroG, a folder named (invalid) where a folder named after the photo in question is created and appears as an empty file in my gallery. Does not happen with non photos.
Downloaded the app from F-Droid.

**Comment by AlvaroBrey** [comment]
@HellsBells24 no, that is a duplicate of #9328

**Comment by Thovi98** [comment]
> but if it's not reproducible anymore, we should close this.

I didn’t close until now to be sure it still works, and it is !
Thanks for all you are doing and for your kind support @AlvaroBrey 🤩
