### ISSUE TITLE
"Unvailable server" on Android Nextcloud app with framagenda.org account

### ISSUE THREAD

**Issue by Audrex** [nextcloud/android#9573]
### Steps to reproduce
1. Download last version (3.18.0) of Android Nextcloud app on my smartphone (BQ aquaris X) with Android version 8.1.0
2. Connect with my framagenda.org account
3. Synchronize some files and notes

### Expected behaviour
- The app should synchronize files and notes from the web app framagenda (on browser) to the Nextcloud app on my smartphone.
- I reinstalled the last version (3.17.1) and it works perfectly

### Actual behaviour
- Nextcloud app on smartphone does not synchronize files and notes and states "unvailable server" (but I can access my framagenda account on my browser)

### Can you reproduce this problem on https://try.nextcloud.com?
- Need a phone to do that

### Environment data
Android version: 8.1.0

Device model: BQ Aquaris X

Stock or customized system: Stock (I guess)

Nextcloud app version: 3.18.0

Nextcloud server version: Nextcloud 21.0.5.1 (using https://scan.nextcloud.com/ and testing framagenda.org)

Reverse proxy: I don't know

#### Web server error log
```
Insert your webserver log here
```
I don't know where to find that 

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
I don't know where to find that

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AlvaroBrey** [comment]
Hi @Audrex, do you have spaces in your username or other special characters?

**Comment by Audrex** [comment]
Hi @AlvaroBrey,
Yes my username is a mail adress (myadress@gmail.com)
And in the Nextcloud app my account name is into this format : "FirstName LastName@framagenda.org"

**Comment by AlvaroBrey** [comment]
@Audrex in that case, can you try [3.18.1 RC2](https://github.com/nextcloud/android/releases/tag/rc-3.18.1-02)? There were some login bugs in 3.18.0 that were fixed in .1.

**Comment by Audrex** [comment]
@AlvaroBrey thank you for the suggestion. So I tried the version you suggested 3.18.1 (which is now the latest one available I guess), and it work perfectly now ! Thanks again !
