### ISSUE TITLE
App Crash full screen video

### ISSUE THREAD

**Issue by BKL42** [nextcloud/android#9574]
### Steps to reproduce
1. run application
2. start video .mp4 type
3. go full screen 

### Expected behaviour
- video go full screen 

### crash
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 8.0.0

Device model: Galaxy A5 (2017)

Stock or customized system: Stock (plain)

Nextcloud app version: Magenta CLOUD 

Nextcloud server version: 22.0.2

Reverse proxy: none

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AlvaroBrey** [comment]
Hello and thanks for taking the time to report a bug.  However more information is required; please fill in the issue template with a description of the error, version info, and steps to reproduce, and reopen this issue when that's done. 

Please also make sure that the issue title is descriptive of the issue and not just "Bug" or "Crash" or similar.

Thank you!

**Comment by AlvaroBrey** [comment]
@BKL42 Please fill in the "Environment data" section. Additionally, what format is the video? (mp4, avi, flv...)
