### ISSUE TITLE
Android app - Can't access relevant folders

### ISSUE THREAD

**Issue by jappish84** [nextcloud/android#9575]
### Steps to reproduce
1.  Go to auto upload in the app
2.  Create custom folder
3. Try to select relevant folder on emulated storage 

### Expected behaviour
- the relevant folder should appear with it's contents, I.e DCIM folder should appear with the Camera folder inside, instead empty folders are displayed and there is nothing to upload. 

### Actual behaviour
- see above. I can also mention that I'm seeing expected behavior on another device, specifically huawei p20 pro with Android 10

### Can you reproduce this problem on https://try.nextcloud.com?
Can't connect app to demo account since I can't change password as it's not known 

### Environment data
Android version:
10
Device model: 
Huawei p30 pro

Stock or customized system:
Stock

Nextcloud app version:
3.18.0

Nextcloud server version:
23.0.0

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AlvaroBrey** [comment]
The app likely lacks permissions for external storage. Can you reproduce this behaviour in 3.19.0?

**Comment by dazzzl** [comment]
I have the same problem with lineageos 18.1 on z3c... It seems that the app is not asking for the external storage permission. How can I give the permission to the app?

**Comment by jappish84** [comment]
I have made sure the app has all permissions avaliable to grant. That's not the issue.

I have also tried it out on v3.19 but unfortunately the issue  still persists.

**Comment by dazzzl** [comment]
I tried to grant the permission with pm ... no luck!

Package com.nextcloud.client has not requested permission android.permission.READ_EXTERNAL_STORAGE
Package com.nextcloud.client has not requested permission android.permission.WRITE_EXTERNAL_STORAGE
Permission android.permission.MANAGE_EXTERNAL_STORAGE requested by com.nextcloud.client is not a changeable permission type

**Comment by AlvaroBrey** [comment]
> I have the same problem with lineageos 18.1 on z3c... It seems that the app is not asking for the external storage permission. How can I give the permission to the app?

delete and reinstall the app, it should ask for permissions again.

**Comment by AlvaroBrey** [comment]
> I have made sure the app has all permissions avaliable to grant. That's not the issue.
> 
> I have also tried it out on v3.19 but unfortunately the issue still persists.

Check `Settings -> Apps and notifications -> Special app access -> All files access`

**Comment by dazzzl** [comment]
I checked this, yes this permission is granted. 

We are talking about Android 11. Do you know if this will work in general, since Android 11 has more restrictions for the storage. Is it possible to upload general files with nextcloud client in Android 11?

**Comment by AlvaroBrey** [comment]
> I checked this, yes this permission is granted.
> 
> We are talking about Android 11. Do you know if this will work in general, since Android 11 has more restrictions for the storage. Is it possible to upload general files with nextcloud client in Android 11?

Should work for most files and folders with the All Files permission, so I don't know what is happening. 

Can you also not upload files from the manual upload? (press the + button -> upload files) What about from SAF? (press the + button -> upload content from other apps)

**Comment by jappish84** [comment]
Huawei p30 pro does not seem to have the "all files access"  under special access, it has a bunch of other options, just not that.

Upload is no different, the partition with photos and files isn't accessible.

Nextcloud does not show up in the share menu when choosing a photo for example.

I have temporarily solved the issue by using the foldersync app instead which connects to nextcloud and works with all folders.

**Comment by dazzzl** [comment]
Yes, I can manual upload files, but not from Android/data ... But the automatic upload does not work, even if it is not in Android/data

With SAF, the lineageos file browser appear and I can also not access Android/data

**Comment by AlvaroBrey** [comment]
> Yes, I can manual upload files, but not from Android/data ... But the automatic upload does not work, even if it is not in Android/data
> 
> With SAF, the lineageos file browser appear and I can also not access Android/data

Not being able to access `Android/data` is normal, and will never work without root in Android 11+. It's a restriction on Android's side.

However @jappish84 can't access any files, which is a different problem. 

@jappish84 can you try the QA apk in [#9873 ](https://github.com/nextcloud/android/pull/9873#issuecomment-1062650837) and see if it helps?

**Comment by dazzzl** [comment]
Right, I can access files, but these files are never uploaded automatically (maybe another issue?)

**Comment by GoodEnoughComputing** [comment]
> > Yes, I can manual upload files, but not from Android/data ... But the automatic upload does not work, even if it is not in Android/data
> > With SAF, the lineageos file browser appear and I can also not access Android/data
> 
> Not being able to access `Android/data` is normal, and will never work without root in any app in Android 11+. It's a restriction on Android's side.


So only working auto uploads are camera videos and photos taken by camera? 
This seems to me that Android 11 Nextcloud auto upload is effectively broken. I can't even change to lineage because of work reasons.  sigh.

**Comment by dazzzl** [comment]
Yes, media folders are all working. I have not checked, if no photo files are also auto uploaded in media folders. In other folders, the files are displayed in the auto upload view in settings and manual upload also work, but no auto upload.

**Comment by SebastianRusek** [comment]
We are still unable to automatically upload files from android/data :(
