### ISSUE TITLE
Trouble logging in to the phone app

### ISSUE THREAD

**Issue by Mattajaz** [nextcloud/android#9583]
### Steps to reproduce
1. Logging in to the phone app

### Actual behaviour
- After pressing the authorize button for that device i get this error

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 11

Device model: XQ-AT51

Stock or customized system: Stock

Nextcloud app version: 3.18.0

Nextcloud server version: 22.2.3

Reverse proxy: No

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by Mattajaz** [comment]
![Uploading Screenshot_20211217-170336.png…]()

**Comment by Mattajaz** [comment]
![Screenshot_20211217-170336](https://user-images.githubusercontent.com/48929869/146574153-67ce9a72-6be4-4844-87a7-8f25bed585a5.png)

**Comment by sgutermann** [comment]
same here https://github.com/nextcloud/android/issues/9628#issue-1089784714

**Comment by Mattajaz** [comment]
Any fix for this yet?

**Comment by sgutermann** [comment]
Sorry for adding confusion. This error was fixed and works just fine for me now.

If however you have something messed up on your set up on the proxy headers you will get the same error.

**Comment by Mattajaz** [comment]
Hmm im running the nextcloud instance on my cpanel so it makes my proxy headers for me

**Comment by AlvaroBrey** [comment]
@Mattajaz can you check the QA build in https://github.com/nextcloud/android/pull/9607 ?
