### ISSUE TITLE
Was testing to play audio file (.MP3) on android app. Rest, please look into the crash log

### ISSUE THREAD

**Issue by Uday083** [nextcloud/android#9588]
### Steps to reproduce
1. Did setup nextcloudpi on docker which is in armbian
2. Did setup user, domain, etc. 
3. Installed the app, tried uploading 2 MP3 files and tried to play them. 

### Expected behaviour
- if the player plugin was not present, the app could have looked for external MP3 players or give out a message saying nextcloud doesn't recognise the file

### Actual behaviour
- struggled to play it for some time with just nextcloud logo and got a crash report after some time.

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: color os 11 (android 11)

Device model: Reno 6 5g (global edition)

Stock or customized system: 

Nextcloud app version: 

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AlvaroBrey** [comment]
Please fill in the remaining fields of the template (app version and server version specially), and try to get some logs.
