### ISSUE TITLE
Open file directly from search result

### ISSUE THREAD

**Issue by j-ed** [nextcloud/android#9592]
### Actual behavior
If I search a file by entering a keyword, all matching files are correctly shown. If I select one of the displayed files to for viewing the app changes to the directory in which the file has been found instead of opening it.

### Expected behavior
If I select a searched file for viewing the app should directly open it instead of changing to the directory in which the file has been found.

### Steps to reproduce
1. Open the Nextcloud app
2. Enter a search criteria
3. Select one of the matching files
-> The file isn't opened but the directory content is shown in which the file resides. If you then select the file again for viewing, it is correctly displayed.

### Environment data
Android version: 11.0
Device model: Samsung Galaxy S20
Stock or customized system: Stock ROM
Nextcloud app version: 3.18.1 RC2
Nextcloud server version: 22.2.3

**Comment by AlvaroBrey** [comment]
This is the expected behaviour with the new unified search. It shows the file in its context and highlights it.

**Comment by j-ed** [comment]
@AlvaroBrey I understand but I think here is still some room for improvements 😉 
If I execute a search and **pick a file** from the result list, I'm usually expecting that this file is directly opened.
If I execute a search and **pick a directory** from the result list, I'm usually expecting to jump to that directory.

**Comment by joshtrichards** [comment]
Fixed in #12209 & #12092
