### ISSUE TITLE
On device has "Nextcloud" as title?

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#961]
Ref: https://github.com/nextcloud/android/pull/896#issuecomment-299630019

When switching to show only the downloaded files the title should show "on device".
Similar to this should the "all files" view also called "all files"?
Then we would have the app name not shown anymore.

**Comment by tobiasKaminsky** [comment]
@mario @jancborchardt @AndyScherzinger

**Comment by jancborchardt** [comment]
Yeah, any different view (when in root) should show the view name in the title. Except All files, there show "Nextcloud" (or + "beta").

**Comment by lavigne958** [comment]
Gave it a try, on version 3.4.2 from Google Play, when on the "on device" view, it shows "on device" title.
May be want to close this issue ? :thinking:
