### ISSUE TITLE
Empty view appears before it even started loading the data

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#962]
Ref: https://github.com/nextcloud/android/pull/896#issuecomment-299439110
Empty view appears before it even started loading the data - this should not happen (everywhere)

Can you describe me when this happens? On the very very first app start?
Or is this related to e.g. favorites?

**Comment by tobiasKaminsky** [comment]
Forgot to mention @mario  ;-)

**Comment by mario** [comment]
It happens in every view ... on app start, favorites, shared, etc.

**Comment by tobiasKaminsky** [comment]
This is an even more general problem:
If you load a folder with very large content, you will also see the wrong "empty message".
Ref: #224

As this might require some more changes I want to do that not in "searchView" branch, but later for 1.5 in a new PR/branch. Are you fine with this @mario?

**Comment by mario** [comment]
Ok, but please make sure this is done for 1.5.

**Comment by tobiasKaminsky** [comment]
Right after seach view is merged I will try to fix it.

**Comment by AndyScherzinger** [comment]
@mario @tobiasKaminsky is this still an issue?

**Comment by mario** [comment]
I fixed this already
