### ISSUE TITLE
Rotate while show favorites

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#963]
Ref: https://github.com/nextcloud/android/pull/896#issuecomment-299439110
When in favorites, and you rotate I get both favorites and non-favorites (and also issues with UI?). This could happen in other "search" parts as well

Can you retest this please @mario? I have only 6 favs and I get only these ones.

**Comment by mario** [comment]
Retested, same happens...

**Comment by tobiasKaminsky** [comment]
Strange that I cannot reproduce it...
What I did:
- rotate while loading
- rotate, refresh, rotate
- refresh in both landscape and portrait

Both on emulator and real device (nexus 4)
