### ISSUE TITLE
Cannot display media files

### ISSUE THREAD

**Issue by zs12593** [nextcloud/android#9635]
### Steps to reproduce
Open Media tab

### Expected behaviour
Cannot display any media files.

### Environment data
Android version:
3.18 and 3.19.0 Alpha1

Device model: 
oppo A11 HUAWEI etc.

Nextcloud server version:
22.2.3

### Some Problems
Forgive me for my poor English.

1. NetworkOnMainThreadException
The debug mode uses enableStrictMode in MainApp.java, so there is no Exception
But in release mode, an error will be reported NetworkOnMainThreadException, because onPostExecute in GallerySearchTask.java executed adapter.setData (OCFileListAdapter.java),
The trace finally found that ReadFileRemoteOperation was called in FileDataStorageManager.saveFileWithParent

2. The media files in the shared folder cannot be obtained, but the iPhone can be obtained
The main reason is that when searchType == SearchRemoteOperation.SearchType.GALLERY_SEARCH in com.owncloud.android.lib.resources.files.NcSearchMethod.java, tags such as <d:eq>, <oc:owner-id> are added

**Comment by szaimen** [comment]
Hello, you might be interested in this feature request: https://github.com/nextcloud/android/issues/8618

**Comment by zs12593** [comment]
> Hello, you might be interested in this feature request: #8618

It is different, I mean that "user1" shares the folder with "user2", and "user2" cannot view the media files in the shared folder through media tab.
