### ISSUE TITLE
Custom Theme or use the colors from the website

### ISSUE THREAD

**Issue by Gamemap** [nextcloud/android#9643]
### Is your feature request related to a problem? Please describe.
I want the client to have the same theme as the nextcloud instance on my server. (or the same colors) (It is not a real problem)

### Describe the solution you'd like
The login page on the client is the login page of the server. Maybe it is possible to save the colors in a file and use them instead of the normal ones.

### Describe alternatives you've considered
Add option fields to change the colors of the buttons and backgrounds.

-------

If someone has already asked about it please excuse me for writing it again... (I have searched and found nothing...)

**Comment by Gamemap** [comment]
> The app should already be using the theme colors from server? Are you not seeing this?

No. I used the Design Tab and Breeze Dark Design.
As an example I changed the color to green and added an image of an cup as the logo. (The last mobile phone picture is the login page)

Server:
- Debian 11 (bullseye)
- Apache2
- Nextcloud 23.0.0

Webprogramm:
- Firefox

Mobile phone:
- Android 11


## Mobile phone:

![Screenshot_20220103-184603_Nextcloud](https://user-images.githubusercontent.com/71942164/147962863-c1a2fd8e-919b-44e5-9653-f7595864bf2e.jpg)
![Screenshot_20220103-184517_Nextcloud](https://user-images.githubusercontent.com/71942164/147962867-8ad2321b-dc7d-4f92-b135-48b2fb82af96.jpg)
![Screenshot_20220103-185716_Nextcloud](https://user-images.githubusercontent.com/71942164/147963522-a4434aaf-31b5-4ee5-bc60-344ca7d10129.jpg)
## Desktop (Website):
![Screenshot 2022-01-03 185112](https://user-images.githubusercontent.com/71942164/147962870-15e010ee-25cd-4084-87f6-14e15f509b46.png)

**Comment by AndyScherzinger** [comment]
The Android app respects the color setting of the server's theme app, nothing else.

**Comment by Gamemap** [comment]
> The Android app respects the color setting of the server's theme app, nothing else.

@AndyScherzinger But won't the folder colors (1st image) and logo/name (2nd image) be changed?
I disabeled Breeze Dark Design and reloadedall, but nothing changed.

**Comment by AndyScherzinger** [comment]
@Gamemap I don't see any images in this ticket. Other than that _if_ you set the color and logo in the theming app than this would be fetched by the client while I can't say if there is some caching involved on the client side.

So did you set these settings in Nextcloud's theming settings?

**Comment by Gamemap** [comment]
@AndyScherzinger I had them hidden under "Show Pictures" in https://github.com/nextcloud/android/issues/9643#issuecomment-1004258614 .  I have reinstalled and reconfigured the app, but it dosn't solve the problem.

Thank you for helping my with this problem!

This is my server configuration:
![nc_1](https://user-images.githubusercontent.com/71942164/148298604-f0e38512-0ba9-43e9-83dc-7e0b7d309083.png)

**Comment by AndyScherzinger** [comment]
This looks fine, so does it paint the folders green on the Android app now?

**Comment by Gamemap** [comment]
Sadly, no. Also the logo and the name are not changed.

**Comment by AndyScherzinger** [comment]
Since it says local host as in 127.0. 0.1 you can't provide us with a test account, no?

**Comment by Gamemap** [comment]
I can try to do port forwarding, but I have a dynamic IP.

**Comment by Gamemap** [comment]
If I can't get it to work over the weekend, would it be helpful to upload the nextcloud website folder to github?

**Comment by Gamemap** [comment]
Sadly I couldn't do a port forwarding, because I use a virtual maschiene and there is a port forwarding bug.
I uploaded my nextcloud web folder to github (https://github.com/Gamemap/nextcloud_android)
I used Apache2, Debian 11 (bullseye), VirtualBox (Host: Windows 11) and Android 11. (and downloaded many nextcloud apps)

If this does not work, could you provide me with a test account on a nextcloud server so we can test if it is a configuration error on my side or an unsupported version?

**Comment by AndyScherzinger** [comment]
I don't have a setup to spin a server, but you could get a 1 hour account via try.nextcloud.com and set the color there in the theming and then log in via the app to check.

**Comment by Gamemap** [comment]
Unfortunately, I "only" have a default user at try.nextcloud.com, so I can't change the color settings.

If you don't have any other idea, I guess we will have to wait until another user has this problem or until I have the possibility to set up an online server.

**Comment by AndyScherzinger** [comment]
Ah, just checked, yes, unfortunately not a admin account, so no permissions to change the color server-side.

**Comment by Gamemap** [comment]
Faster than I thought, I found an old PC that can run nextcloud online with dynamic IP address. The problem still exists.

dynamic IP (currently): [2a02:8109:b540:3b48::e1c4]

Username: admin
Password: root

I hope it is working.

**Comment by Gamemap** [comment]
New ip: http://[2a02:8109:b540:3b48::6d4e]

**Comment by Gamemap** [comment]
Newer ip: http://[2a02:8109:b540:3b48::9364]

**Comment by AndyScherzinger** [comment]
Unreachable 😞

**Comment by Gamemap** [comment]
Sorry, I had to restart the pc.
In a few minutes it should work...

**Comment by Gamemap** [comment]
IP: http://[2a02:8109:b540:3b48::4dde]

**Comment by Gamemap** [comment]
I'm able to connect with the nextcloud app to my server (without WLAN)

**Comment by AndyScherzinger** [comment]
I keep getting address unreachable

**Comment by Gamemap** [comment]
Unfortunately I have no further idea what else I could do.
Thank you for helping me so far....

P.S.: Maybe I can try to reach my server from a friends pc but this will take a longer time...

**Comment by AndyScherzinger** [comment]
> P.S.: Maybe I can try to reach my server from a friends pc but this will take a longer time...

Sounds like a plan 👍

**Comment by Gamemap** [comment]
Sadly I can't reach my server outside of my network but I found a demo nextcloud with an admin account.
I changed the color and the icon and both are working on my mobile phone.

I close this because the app is working. 
(I will check my configuration and write if I get this on my server working.)

Thank you very much for helping me.

**Comment by Gamemap** [comment]
@AndyScherzinger Somehow I managed to get the Color work. (at random trying)
Maybe my server is too slow to response the data. (Image not loaded and name only in the searchbar)
Could you tell me if the theme is loaded every time you open the nextcloud app or only when you log in?

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky might know that. AFAIK the theme parts are cached so they don't refresh instantly.

**Comment by tobiasKaminsky** [comment]
Info about theme is loaded if you open up app or if you manually refresh root folder.

**Comment by Gamemap** [comment]
Thank you
