### ISSUE TITLE
Mutimedia -> Multimedia on spanish translate

### ISSUE THREAD

**Issue by juanjosepablos** [nextcloud/android#9654]
Wrong String on the Spanish translation. Try to use transifex, but it did not work no my browser.
https://github.com/nextcloud/android/blob/8acf55d0f13b0cf3eaa45f94c4b448a0bcd2b08b/src/main/res/values-es/strings.xml#L222

 --- <string name="drawer_item_gallery">Mutimedia</string>
+++  <string name="drawer_item_gallery">Multimedia</string>

**Comment by AlvaroBrey** [comment]
Fixed on Transifex. Thanks @juanjosepablos!
