### ISSUE TITLE
AutoUpload: cannot choose local folder ind manual folder setup

### ISSUE THREAD

**Issue by bene64** [nextcloud/android#9669]
### Steps to reproduce
1. Go to settings -> auto upload -> own folder
2. local folder: Select a folder (for example /storage/emulated/0/Test) -> "choose" does not work

### Expected behaviour
- The folder should be selected

### Actual behaviour
- The folder cannot be selected
- As workaround: 
  - create a second folder dummy inside the folder
  - select "dummy" via combo box -> now the choose button works. In the result "dummy" then gets stripped from the path

### Can you reproduce this problem on https://try.nextcloud.com?
Yes

### Environment data
Android version: 12

Device model: Pixel 4a (sunfish)

Stock or customized system: Stock

Nextcloud app version: 3.18.1 (F-Droid)

Nextcloud server version: 22.2.0

Reverse proxy: /

**Comment by Penumbra69** [comment]
Having the exact same issue here.. Can't choose an empty directory.
It actually DID choose it once, IDK why - but I haven't been able to get it to do it again.

I'm trying to upload automated backups and delete them when done, resulting in an empty directory every time it completes.

Choosing an empty directory should be possible - and then upload anything that appears in there.

Please advise.

**Comment by Penumbra69** [comment]
If nothing else, at least honor the directory that is checked when hitting "choose" -- as I have also tried to select the folder I want, and then hit "choose" - but it just selects the current directory.. I can't make it select the right one unless there's a file or more directories inside it.

**Comment by AlvaroBrey** [comment]
Possibly duplicate of #8940 ? Please check if that issue matches what you're seeing and close this one if so.

**Comment by bene64** [comment]
Oh yes, seems I didn't find this issue. Yes, same behavior, so it's a duplicate.
