### ISSUE TITLE
Feature request: Auto-Upload only for specific file types

### ISSUE THREAD

**Issue by Endogen** [nextcloud/android#967]
When i record videos on my phone then they end up in the same folder as my pictures. I have Auto-Upload active for this folder but i don't want to upload videos since they are to big. Currently there doesn't seem to be the possibility to select which file types inside a folder should be uploaded.

**Comment by mario** [comment]
You will be able to differentiate between images and videos in 1.5.

**Comment by tobiasKaminsky** [comment]
Ref: #797

**Comment by mario** [comment]
Done in a specific branch, so closing. If you feel it's too early, please feel free to re-open.
