### ISSUE TITLE
Synchronize calendar and contact

### ISSUE THREAD

**Issue by R7JANV1** [nextcloud/android#9670]
Calendar and contact synchronization not only from the Nextcloud to the mobile phone with DAVx5 but also without an additional app from the mobile phone to synchronize contacts and calendar to the Nextcloud and vice versa

**Comment by AlvaroBrey** [comment]
Does DAVx5 not sync contacts and calendar back to the server?

**Comment by R7JANV1** [comment]
no. only from the server to the mobile phone

**Comment by AlvaroBrey** [comment]
For reference, https://www.davx5.com/faq/existing-contacts-are-not-synced

**Comment by R7JANV1** [comment]
Please have an option to synchronize contacts and calendar with the nextcloud. Without an additional app other than nextcloud.

**Comment by R7JANV1** [comment]
Doesn't work with davx5 in the meantime with two apps but not a nice solution
