### ISSUE TITLE
Auto upload corrupts pictures on phone when using Samsung Camera app

### ISSUE THREAD

**Issue by andromedar** [nextcloud/android#9671]
My setup:
Server: Nextcloudpi 22
Phone Galaxy A40 / Android 11
Camera App: Samsung official Camera App v 11.0.16.16
NC phone App version: 3.18.1

I have AutoUpload enabled on my phone. So, if i'm on Wifi and take a picture with my Samsung camera app, the picture gets corrupted on the phone. The files are not readable by any app. If i sake a series of pictures, only the last one is not corrupted (the corrupted file is on the phone and also uploads corrupted).
If i turn off wifi, then take the pictures, everything is ok. The pictures get saved normally to the phone. If i later turn on wifi to upload the pictures, everything is ok also - no corruption.
So, the corruption only occurs if wifi is on at the time of taking the photos.
I also tried another Camera app - Camera Zoom FX, and everythins is working fine there. No corruption. But the Camera Zoom FX app is vastly inferior, so not a solution.

**Comment by AlvaroBrey** [comment]
How is your autoupload configured? Is it supposed to move or delete the files when uploaded?

**Comment by andromedar** [comment]
@AlvaroBrey  thanks for the quick response. I can't seem to find such a setting in my phone app, but until now, the pictures stayed in the phone gallery after uploading to NC server. 
Can you direct me to this setting in the phone app?
Thanks

**Comment by AlvaroBrey** [comment]
Ok, that's weird. I'm guessing that Samsung Camera writes the file asynchronously and Nextcloud is uploading before it's finished saving.

**Comment by andromedar** [comment]
Yes, the local file on the phone gets corrupted. Also, the uploaded file is corrupt.
If wifi is off (so nc does not try to upload), everything is fine. Later, when switching ON wifi, the files upload with ho problem.

**Comment by andromedar** [comment]
Update: the problem in not linked to the Samsung Camera App, but any app that is writing to SD card. If an app writes the pictures to internal storage, the problem vanishes.
Also, when i disable background data for the Nextcloud phone app, the problem is gone.

**Comment by AlvaroBrey** [comment]
> Update: the problem in not linked to the Samsung Camera App, but any app that is writing to SD card. If an app writes the pictures to internal storage, the problem vanishes. Also, when i disable background data for the Nextcloud phone app, the problem is gone.

Is this is an actual, physical SD card?

**Comment by andromedar** [comment]
I am sorry, but it turned out the SD card was somehow corrupt. I don't know why, but after the problem mentioned here, my phone started complaining about the SD card. Nextcloud auto-upload was the first symptom. the phone flagged the card read-only, to prevent data loss. I bought a new SD card and every thing works fine now. But interestingly, the old SD card seems to be fine too...in other devices. It is an old no-name (really no-name) 64 GB sd card (that i tested with h2testw and is the correct capacity). Who knows what it was...
Thanks anyways
Keep up the good work!

**Comment by AlvaroBrey** [comment]
> I am sorry, but it turned out the SD card was somehow corrupt. I don't know why, but after the problem mentioned here, my phone started complaining about the SD card. Nextcloud auto-upload was the first symptom. the phone flagged the card read-only, to prevent data loss. I bought a new SD card and every thing works fine now. But interestingly, the old SD card seems to be fine too...in other devices. It is an old no-name (really no-name) 64 GB sd card (that i tested with h2testw and is the correct capacity). Who knows what it was... Thanks anyways Keep up the good work!

No problem! Happy that it's working now.
