### ISSUE TITLE
"Error during migration" move to SD card

### ISSUE THREAD

**Issue by ghost** [nextcloud/android#968]
### Actual behaviour
Error message: "Error during migration" when changing storage path to SD card.
Fails to use the SD card as default storage

### Expected behaviour
When selecting storage to external it should use the SD card as storage path
 
### Steps to reproduce
1. Download Nextcloud android app on android 4.4.4
2. change storage path to SD card
3. Error during migration

### Environment data
Android version:
4.4.4
Device model: 
Samsung S3 LTE I1905
Stock or customized system:
Stock (not rooted)
Nextcloud app version:
1.4.2
Nextcloud server version:
11.0.3
#### Web server error log
N/A
Insert your webserver log here
N/A

**Comment by prilly** [comment]
So.. i cant belive iam the only one that has this issue, i hope anybody can get it fixed

**Comment by OlivierS1** [comment]
This was fixed I believe.
Try rebooting your phone.

**Comment by AndyScherzinger** [comment]
Afaik @tobiasKaminsky did some changes for the upcoming release, so you can also give the dev version (can be installed in parallel) and check if that one resolves the issue for you and would be sure that 1.5.0 will fix it for you. It an be found here: https://f-droid.org/repository/browse/?fdfilter=Nextcloud&fdid=com.nextcloud.android.beta

**Comment by tobiasKaminsky** [comment]
Additionally the dev version has logging (of course only non-private data) enabled which could help to trace down the problem.

**Comment by tobiasKaminsky** [comment]
@prilly can give the dev version a try and if it fails send us the logs?

**Comment by tobiasKaminsky** [comment]
No response within the last month, therefore closing.
Please feel free to reopen with additional infos, if the problem still exists.

**Comment by bastienbc** [comment]
I have the same issue.
If I found time I will use the dev version and send the logs, but I cannot make any promises.

**Comment by tobiasKaminsky** [comment]
@bastienbc this would be great. As there are so many devices/vendors we cannot reproduce every error on our own, so looking forward to your log :+1:

**Comment by prilly** [comment]
Just a update, this is the problem: https://androidcentral.com/kitkat-sdcard-changes

Nextcloud app is storing on a folder it has not write permission to.

To solve thus the app needs to be moved to sd card to creat the folder it has write permission to, the storage it can store to is then inside the app folder, the nextcloud app will never have write permission outside this directory.

**Comment by tangofranz** [comment]
The same issue with nextcloud 2.0.0 on Android 5.01 on Samsung GT-I9505 (Galaxy S4).
Same error message. 
Does anybody in this forum now, if the kitkat restrictions are also valid for Android 5 ? THX
