### ISSUE TITLE
"Server not available" when username is email address containing a plus sign

### ISSUE THREAD

**Issue by csware** [nextcloud/android#9681]
### Steps to reproduce
1. Have a Nextcloud username (looking like a email-addres) containing a plus sign (yes, it's a very old installation coming from owncloud, e.g. `username+extension@domain.de`)
2. The main 'All Files' screen, the app shows the 'Server not available' message

### Expected behaviour
- The app should connect to the provider and display the files (as before 3.18)

### Actual behaviour
- Shows "Server not available"

Relates to issue #9439. I suppose no proper encoding is used. Other providers with other usernames do work.

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 11

Device model: Galaxy Tab S7

Stock or customized system: stock

Nextcloud app version: 3.18.1

Nextcloud server version: 22.2.3

Reverse proxy: no

#### Web server error log
```
IP - - [11/Jan/2022:10:38:55 +0100] "PROPFIND /remote.php/dav/files/user%2Bextension@domain.de//exchange/Tablet/ HTTP/1.1" 207 1637 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.18.1"
```

Here, the problem exists, `+` should not be encoded as `%2B` - the nextcloud desktop version does not encode it.

#### Nextcloud log (data/nextcloud.log)
```
No entries
```

**Comment by AlvaroBrey** [comment]
@csware Can you test the QA apk in this comment? https://github.com/nextcloud/android/pull/9682#issuecomment-1009902228

**Comment by csware** [comment]
Thanks!

Sorry, I didn't had the time last week to test it.
