### ISSUE TITLE
Share image does not always show buttons

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#9683]
### Steps to reproduce
1. click on details of an image with preview
2. share it to an user
3. see ![2022-01-12-071001](https://user-images.githubusercontent.com/5836855/149073498-20ebc5e0-9718-487a-8f03-31d0830a277d.png)

### Expected behaviour
- buttons should be visible

### Actual behaviour
- user has to scroll to find buttons:
![2022-01-12-071043](https://user-images.githubusercontent.com/5836855/149073562-8b0768c0-d6ee-4ce6-8be6-ba615cbf6699.png)

**Comment by joshtrichards** [comment]
This looks fixed. Closing.

I can't find the relevant PR to reference so if someone is still seeing this free to reference this issue.
