### ISSUE TITLE
[dev] don't delete tags

### ISSUE THREAD

**Issue by krt16s** [nextcloud/android#969]
### Actual behaviour
Building old development snapshots fails because tags seem to get removed.

### Expected behaviour
- I expect to build development snapshots from tags even some time has passed.
 
### Steps to reproduce
1. Try to build from old dev- tag.
2. Tag is gone.
3. Build fails.

**Comment by tobiasKaminsky** [comment]
I am removing them to not clutter the tags as there is nearly daily a new "dev" tag and it is not really useful to build an old rev...
Is this related to fdroid?

**Comment by krt16s** [comment]
Yes, this is somewhat related to F-Droid: I had to crunch through quite a lot error messages when I tried to setup my own buildserver to verify official binaries. It's not a big deal.. iirc we store the commit hash anyway, just need to expose it... Sorry for the noise :)

**Comment by tobiasKaminsky** [comment]
Ok, but if you still need them, just ping me here.
