### ISSUE TITLE
Add Trash Can Delete Option To Top Bar

### ISSUE THREAD

**Issue by cwmke** [nextcloud/android#97]
### Environment data
Android version: 6.0.1
Device model: Nexus 6p
Stock or customized system: customized
Nextcloud app version: fdroid Nextcloud beta version 20160621

I delete stuff fairly frequently and it seems like it would be more convenient (I believe) to have the standard trash can icon appear when files and/or folders are selected.  This is one of the little things that always bothered me with ownCloud's app.  

Thanks either way.  I already enjoy nextCloud's app and software more!

**Comment by AndyScherzinger** [comment]
Hi @cwmke can you go a bit more into detail. There is a remove menu item, it is in the top right three-dot menu. It that what you meant?

**Comment by cwmke** [comment]
Sure!  I am suggesting the 'remove' option be moved from the hamburger menu to a trash can icon in the upper bar as demonstrated in this F-droid screenshot.

![screensho](https://cloud.githubusercontent.com/assets/1923967/16593371/94063592-42aa-11e6-8704-3fc16c628cf4.png)

**Comment by AndyScherzinger** [comment]
@jancborchardt you are the UI guru :) technically it is possible, question is which action show be explicitly put into the top bar during multi select and which should be put into the three dot menu.

Cc @tobiasKaminsky since you are the master of the multi select feature.

**Comment by jancborchardt** [comment]
We already have 3 actopms in the top right there:
- for single files: share, download, more
- for multiple: download, open with, more

Having a fourth there would be too much, especially a destructive action like delete right next to the others.

**Comment by AndyScherzinger** [comment]
Thanks for the feedback @jancborchardt. I agree with the argument especially the destructive character of the action. Thus closing the issue. Sorry @cwmke :(

**Comment by cwmke** [comment]
@AndyScherzinger No problem!  I just thought I'd try. ;-)

**Comment by AndyScherzinger** [comment]
Thanks! You are of course always welcome to try since we highly value any feedback and ideas. Even if they don't make it into the app we honor the time and thought put into it!
