### ISSUE TITLE
Allow to click the entries in Activity to show them in the app

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/android#971]
* refinement to the existing activity view
* maybe also show the preview of the files

cc @nextcloud/designers @oparoz @mario @aleister09 @tobiasKaminsky @AndyScherzinger

**Comment by aleister09** [comment]
But what about when the activity entry has more than one file?
Like this
![more files](https://cloud.githubusercontent.com/assets/25756086/25909071/9ef1653e-3571-11e7-8b99-c8849bdb6794.png)

**Comment by MorrisJobke** [comment]
> But what about when the activity entry has more than one file?

Of course the file name itself should be clickable.

Ultimate goal is to have something like this on Android as well:

<img width="502" alt="bildschirmfoto 2017-05-10 um 11 41 20" src="https://cloud.githubusercontent.com/assets/245432/25910343/a64ed682-3575-11e7-8beb-35f2cf3845db.png">

**Comment by AndyScherzinger** [comment]
implemented and merged
