### ISSUE TITLE
Show indicator for notifications in sidebar

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/android#974]
* show a little indicator in the sidebar that there are new notifications (like the little red dot in our web UI)

<img width="185" alt="bildschirmfoto 2017-05-09 um 18 28 01" src="https://cloud.githubusercontent.com/assets/245432/25876812/4155ff66-34e5-11e7-9548-e8ff8fb202a4.png">

cc @nextcloud/designers

**Comment by mario** [comment]
Not sure when can this be done atm. We'd have to store things in the database and compare to that + change the way we fetch notifications. Push shows a notification in the mobile notification area.

**Comment by joshtrichards** [comment]
Fixed in #13610
