### ISSUE TITLE
Showing deleted files

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/android#975]
It should be possible in the Android app to restore deleted files from the trashbin. For this a public API on the server is needed.

cc @schiessle @rullzer for the server - I would like to have then in the DAV interface

cc @nextcloud/designers

**Comment by rullzer** [comment]
Yes should be in DAV. Agreed.

**Comment by AndyScherzinger** [comment]
implemented by @tobiasKaminsky and part of 3.3.0
