### ISSUE TITLE
Number parsing mixes up alphabetical sorting

### ISSUE THREAD

**Issue by pludi** [nextcloud/android#9756]
When using alphabetical sorting and there are files starting with numbers it seems that these are parsed and the files sorted by numerical value.

In the screenshot `8d…` is sorted before `6064b…` and `11079e…`

I can see this being advantageous for directories with non-padded numerical file names, but it's not what I'd expect with alphabetical sorting.

![Screenshot_20220126-001922](https://user-images.githubusercontent.com/2112148/151076501-6f8bbd99-78a1-4605-918e-185bc3595185.png)

**Comment by pludi** [comment]
Given the label: do you need additional information from my side?

**Comment by AlvaroBrey** [comment]
> Given the label: do you need additional information from my side?

No, sorry, I did that by mistake. It does seem like the natural sort implementation is parsing the hex numbers and sorting on their value, which is not really a case that was thought of.

**Comment by AlvaroBrey** [comment]
This is consistent with the natural sort implementation in the server. I've replicated the filenames in the web UI and the order is the same. Not sure what to do about this.

**Comment by AlvaroBrey** [comment]
I'm closing this as expected behaviour for now. If this is to change it would have to be discussed in the server repo first.
