### ISSUE TITLE
Failed to connect using the Android client

### ISSUE THREAD

**Issue by hannandor** [nextcloud/android#9780]
### Steps to reproduce
1.  Start NextCloud client on Android
2. Fill in server data and log in

### Expected behaviour
The application should successfully login

### Actual behaviour
The application verifies my identify couple of times in a row (>5) and is crashing.
************ CAUSE OF ERROR ************

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:354)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.RuntimeException: Accessing result data after operation failed!
	at com.owncloud.android.lib.common.operations.RemoteOperationResult.getResultData(RemoteOperationResult.java:503)
	at com.owncloud.android.authentication.AuthenticatorAsyncTask.doInBackground(AuthenticatorAsyncTask.java:80)
	at com.owncloud.android.authentication.AuthenticatorAsyncTask.doInBackground(AuthenticatorAsyncTask.java:45)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30180190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: dreamlte
Model: SM-G950F
Id: PPR1.180610.011
Product: dreamltexx

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: G950FXXUCDUD1

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AlvaroBrey** [comment]
@hannandor Can you try 3.19.0 RC2? I believe this issue has been fixed

**Comment by hannandor** [comment]
Sure, I will try this and let you know.

**Comment by hannandor** [comment]
I did try the 3.19.0 RC2 version and it doesn't crash anymore. However the application fails to connect returning the error HTTP 401 (Due the security policy I cannot make a screenshot and the message is displayed only 2,3 seconds). I do mention that I'm able to successfully login from my desktop.

**Comment by AlvaroBrey** [comment]
@hannandor does login work with the app version 3.17.1?

**Comment by hannandor** [comment]
Unfortunately I can't tell because that was crashing before reaching that step.

**Comment by AlvaroBrey** [comment]
@hannandor I'm guessing version 3.19.0 (non RC) still doesn't work? It contained some last-minute login patches, so try it just in case, if possible

**Comment by hannandor** [comment]
@AlvaroBrey I did test the 3.19.0 and seems that is still failing with the same HTTP 401 error.

**Comment by AlvaroBrey** [comment]
@hannandor is this a public server that I can test somehow? otherwise this is very difficult (if not impossible) to debug, I'm afraid :(

**Comment by sttrebo** [comment]
@AlvaroBrey I self host (currently running 23.0.0) and I can set up a guest account for you to try if it'll help at all.

**Comment by sttrebo** [comment]
info sent.  question:  could the use (or not) of a VPN complicate this issue?  On my tablet (Samsung S7) i don't seem to have any issues (VPN or not) but on my phone (Samsung S21) i have to disable my VPN then it generally works.

**Comment by AlvaroBrey** [comment]
@sttrebo well, if it works with no VPN but it doesn't work with a VPN, I would say it's pretty clear that the VPN is causing the problem... not sure how to reproduce this then

**Comment by sttrebo** [comment]
Traced this one down to my VPN protocol that I was using.  Switched to TCP and my connection problems went away.

**Comment by AlvaroBrey** [comment]
@hannandor are you using a VPN too?

**Comment by hannandor** [comment]
(sorry for the long delay) I'm not using VPN...my tests were done using my local network. 

@AlvaroBrey I can try to make a guest account, were should I sent the credentials?

**Comment by AlvaroBrey** [comment]
> (sorry for the long delay) I'm not using VPN...my tests were done using my local network.
> 
> @AlvaroBrey I can try to make a guest account, were should I sent the credentials?

my email address, alvaro.brey@nextcloud.com
