### ISSUE TITLE
Upload Files from Autoupload are duplicated

### ISSUE THREAD

**Issue by hechi** [nextcloud/android#979]
Hey,

first thanks for your hard work :) and improving the nextcloud android app :+1: 

### Actual behaviour
- Created an Autoupload for instant messaging app folder
- everytime i receive an image form the messaging app, it should be uploaded to my cloud
- if i install a new dev version, he starts to upload all images again (>700)
- if i reboot my device, he starts to upload all images again
- it creates new images like IMG-xys (1).jpg IMG-xys (2).jpg everytime, he start to upload it again.

### Expected behaviour
- Only upload images once
 
### Steps to reproduce
1. Create a Autoupload folder for an instant messaging app
2. Upload images
3. install new dev app or reboot device

### Environment data
Android version: 6.0.1

Device model: Moto 4G

Stock or customized system: Stock + Root

Nextcloud app version: 20170430

Nextcloud server version: 11.0.3

#### Web server error log
```
i can provide them if needed
```

#### Nextcloud log (data/nextcloud.log)
```
i can provide them if needed
```

No logs in AndroidApp under Settings->Logs. Can i activate theme somewhere?

![screenshot_20170511-093358](https://cloud.githubusercontent.com/assets/3808354/25938453/8298731e-362f-11e7-8337-e3f2c3d44fe6.png)

Everytime i change the Storagepath he change it back to unknown :(

![screenshot_20170511-093427](https://cloud.githubusercontent.com/assets/3808354/25938452/829866a8-362f-11e7-9f96-50cb55d1f7b9.png)

**Comment by hechi** [comment]
With nightly 20170509 the storage problem is gone :) nice thx for your hard work :+1:

**Comment by AndyScherzinger** [comment]
Hi Andreas,

are both issues fixed with 20170509 or just the later one? Logs should be shown if not it might be related to storage (as in on device vs. SD cards, etc.) where @tobiasKaminsky might be the best to take a look :)

**Comment by hechi** [comment]
probably its fixed ^^ i close the issue, i will reopen it if it pops up again.

**Comment by hechi** [comment]
Hey @AndyScherzinger 
sry it appeared again :( after connecting at my home wifi he started to sync over 1400 images :(
![screenshot_20170512-225828](https://cloud.githubusercontent.com/assets/3808354/26024596/c69e82be-37d4-11e7-9bd2-869aee7b2f0f.png)

**Comment by AndyScherzinger** [comment]
Calling @mario to the rescue :)

**Comment by mario** [comment]
All will be fixed :P

**Comment by strenker** [comment]
Hi,
the Nextcloud App (1.4.3) for Android is really good overall. Much better than the Owncloud App I used before I migrated from Owncloud Server to Nextcloud Server. Many thanks! But this bug is really annoying. Each reboot of my Android phone causes a reload of all my automatically uploaded images (>1000).
Kind regards, Stefan

**Comment by mario** [comment]
I know. Sorry about that - very annoying platform bug that we need to
workaround :(

I'll fix it for 1.5.

**Comment by marvinwankersteen** [comment]
@mario When will be 1.5 available?

**Comment by mario** [comment]
Beta in 1 - 1.5 months.

**Comment by mario** [comment]
Dear users,

thank you for your patience. After lots of work, we’re super excited to be able to give you a test version with new auto upload implementation. Keep in mind we will only accept bugs related to Auto Upload in this APK, as other things might be broken.

https://cloud.nextcloud.com/s/ftZraTruRQjTe0R

This is a dev APK so it will not overwrite your existing play store/f-droid APK unless you’re already running dev version. Also, you might need to remove your existing dev version before installing this one.

Explanation of the current functionality:
- added support for custom folders
- separated image and video folders
- checks for new files happens every 15-20 minutes
- automatic retry every 15-20 minutes or when you force close/open the app
- automatic pause once network is changed (untested!)
- significantly less battery usage

All and any testing is more than appreciated, especially with large and ever-going files like Videos. (like, try to record a 30 min video).

Let me know if you’ve got any questions.

Cheers,
Mario

**Comment by Marcwa19197** [comment]
Okay, thanks for this bug report, now i know why i have ~80GB Media Files uploaded in my nextCloud :)
I removed all duplicates with brackets and numbers in it via windows explorer.

any new information when this update 1.5 will come over to the play-store?

thanks in advice.
