### ISSUE TITLE
Media screen doesn't refresh on delete or download

### ISSUE THREAD

**Issue by AlvaroBrey** [nextcloud/android#9790]
### Steps to reproduce
1. Open media screen
2. Long tap to select a file
3. Tap "delete" or "download" in the overflow menu

### Expected behaviour
- After deleting or downloading the file, the layout should be updated (removing the file or marking it as downloaded, respectively)

### Actual behaviour
- File is deleted or downloaded but layout isn't refreshed.

### Environment data
Android version: 12

Device model: emulator

Stock or customized system: stock

Nextcloud app version: 3.19.0 RC2

Nextcloud server version: 23

Reverse proxy: no

**Comment by joshtrichards** [comment]
Fixed in #12146
