### ISSUE TITLE
Don't try to preview unsupported media codecs

### ISSUE THREAD

**Issue by AlvaroBrey** [nextcloud/android#9804]
### Steps to reproduce
1. Have a file with a media codec that ExoPlayer can't reproduce (for example, a `.avi` video) -> nope, https://github.com/nextcloud/android/pull/10413 seems to add AVI support. we'll need to find a different format.
2. Tap on it

### Expected behaviour
- An error should show up and explain that the codec is unsupported

### Actual behaviour
- The app tries to unsuccessfully open a video preview, which of course doesn't play anything.

### Environment data
Android version: any

Device model: emulator

Stock or customized system: stock

Nextcloud app version: any

Nextcloud server version: any

Possible idea: use `MediaCodecList` to get the available codecs and check against file codec.

**Comment by AlvaroBrey** [comment]
Additional: app should also show an error (maybe a toast?) if previewing a supported video with unsupported audio codec. See #4903 for reference.

**Comment by mayanksony** [comment]
i would like to contribute

**Comment by AlvaroBrey** [comment]
Unsupported codec handling was added in https://github.com/nextcloud/android/pull/11069
