### ISSUE TITLE
Theming in the Android App

### ISSUE THREAD

**Issue by Memes11** [nextcloud/android#9818]
in the left menu in the Android App, in the top, instead of having the Nextcloud logo, the Nextcloud word and the signature blue, it would be interesting to have the logo name and base colour of the server it is connected too.

In case you use multiple accounts, that could help.

**Comment by AlvaroBrey** [comment]
This should already happen if the server is properly configured

**Comment by tobiasKaminsky** [comment]
Might be, as we use a different image library for this.
Please fix this and then re-open, if needed *and* if it does not work on another system e.g. try.nextcloud.com
