### ISSUE TITLE
Instrumented tests don't run with gradle plugin 7.1.x from Android Studio

### ISSUE THREAD

**Issue by freelon** [nextcloud/android#9824]
### Steps to reproduce
1. Check out master and open it in a freshly installed Android Studio 2021.1.1
2. Try to run the instrumented tests

### Expected behaviour
- The gradle job should run and the tests should start like they to if I change the plugin back to `com.android.tools.build:gradle:7.0.4`

### Actual behaviour
- Gradle fails with `Project 'Nextcloud' not found in root project 'Nextcloud'.`

I also filed an issue at Google for this: https://issuetracker.google.com/issues/219164389

I don't know if this is a problem for anyone else in the development, I guess if running the tests via CLI it works? (I couldn't get it to run since my android dev skills have become a bit rusty)

**Comment by AlvaroBrey** [comment]
@freelon this is because this project doesn't follow the modern "standard" gradle project structure with the app sources in a subproject. There's plans to fix this (and we already started working on #9798 ) but we are waiting until after the 3.19.1 release to do the changes.

**Comment by freelon** [comment]
Thanks for the info!

**Comment by joshtrichards** [comment]
Fixed in #9960
