### ISSUE TITLE
On device: show only folders containing downloaded files

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#983]
Suggestion via email: Show only those folders that contain downloaded files.

~~This can be a little tricky if you have something like root -> folder a (no files) -> folder b (with files) then you would have to show folder a. 
Currently we would have to scan this manually as we do not store something like that in the database.~~

**Comment by tobiasKaminsky** [comment]
#1143 

After thinking about it, this is rather easy: While iterating over the children of a folder:
- if the file/folder exists on local file system -> show
- otherwise: hide
This work as the folder "inbetween" (folder a in above example) are also created even if they only contain a subfolder.

**Comment by jsrck** [comment]
I created pull request #1220 for this issue.

**Comment by AndyScherzinger** [comment]
merged to master for 1.5.0
