### ISSUE TITLE
Audio starts playing on device rotation

### ISSUE THREAD

**Issue by strugee** [nextcloud/android#984]
STR:

1. Open an audio file
2. Wait for it to start playing
3. Pause
4. Rotate device
5. Audio starts playing, even though it shouldn't

Nexus 6P, CyanogenMod 13, dev version 20170430.

**Comment by tobiasKaminsky** [comment]
Thank you for your bug report!
This also applies to the regular version, thus removing dev label.
It will be soon in the dev version.
If you have time, please try it and report if it working.

**Comment by strugee** [comment]
Sure thing @tobiasKaminsky :)

By "soon" I'm assuming you mean "in the next release"? Happy to test this whenever a fix gets merged.

**Comment by tobiasKaminsky** [comment]
"soon" depends on fdroid.
Here you can find it without delay: https://download.nextcloud.com/android/nightly/

**Comment by squadramunter** [comment]
Hi I got a bug on my android phone. I have Cyanogenmod installed on it but when i open the app the video resolution is not correct. when rotating the screen it's not fitted full screen. may a feature for the next release to add support for aspect ratio. I have a samsung galaxy s5.

**Comment by strugee** [comment]
I can still reproduce with the 20170511 build.

**Comment by tobiasKaminsky** [comment]
Sorry, used the wrong label for the PR and thus it was not merged automatically.
This is now merged into "dev version" and you can download it this night.

**Comment by strugee** [comment]
Whoops, sorry - totally forgot about this issue! I can confirm that this is fixed :)

Thanks for working on this <3
