### ISSUE TITLE
Can't see bottom of markdown document

### ISSUE THREAD

**Issue by BenceBakos** [nextcloud/android#9840]
### Steps to reproduce
1. create a markdown document(on desktop) that will exceed your phone's screen height
2. sync it with nextcloud mobile app
3. open it inside the app

### Expected behaviour
be abel to scroll down to the bottom  of the text

### Actual behaviour
cant see last paragraph, can't scroll down enough.

### Environment data
Android version:10

Device model: redmi note 8 pro

Nextcloud app version: 3.19.0

Nextcloud server version: 22.2.3

**Comment by Discostu36** [comment]
Cannot reproduce with app version 3.26.0 on Android 12. Do you still have this issue?
