### ISSUE TITLE
Root

### ISSUE THREAD

**Issue by 250416** [nextcloud/android#9841]
### Additional context

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AlvaroBrey** [comment]
Hello and thanks for taking the time to report a bug.  However more information is required; please fill in the issue template with a description of the error, version info, and steps to reproduce, and reopen this issue when that's done. 

Please also make sure that the issue title is descriptive of the issue and not just "Bug" or "Crash" or similar.

Thank you!

**Comment by 250416** [comment]
ok soy muy nuevo en esto ahora mismo lo arreglo

**Comment by 250416** [comment]
ok im very new to this i fix it right now
