### ISSUE TITLE
Split builds

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#9848]
Ref: https://github.com/nextcloud/android/pull/9717#discussion_r806578925

- [ ] add split build support for APK
- [ ] still build one APK for Github Releases
- [ ] create QA version 
  -  without scan library ~~or~~
  - ~~with only ARM support, but then remove scan button~~

**Comment by AlvaroBrey** [comment]
>     * [ ]  create QA version
>       
>       * without scan library or
>       * with only ARM support, but then remove scan button

Probably better without scan library
