### ISSUE TITLE
Only One URL

### ISSUE THREAD

**Issue by felischmi2003** [nextcloud/android#9875]
Hello,

i want to customnize the App.
My question:
How i can use only one  URL or how i find the URL variable?

please help,
Felix Schmitt

**Comment by AlvaroBrey** [comment]
Take a look at `setup.xml` both in this repo and in the `android-library` repo ([github.com/nextcloud/android-library](github.com/nextcloud/android-library)). There you will find the resources you need to override.

Also please remember that this is a GPL app and as such, a modified version's source must be published under the same license. Cheers!
