### ISSUE TITLE
Aspect ratio not correct on cyanogenmod galaxy s5

### ISSUE THREAD

**Issue by squadramunter** [nextcloud/android#988]
Hi I got a bug on my android phone. I have Cyanogenmod installed on it but when i open the app the video resolution is not correct. when rotating the screen it's not fitted full screen. may a feature for the next release to add support for aspect ratio. I have a samsung galaxy s5.

**Comment by tobiasKaminsky** [comment]
Is the video stretched? Or is it just not fullscreen, e.g. if you play a 4:3 video on a 16:9 device?
Can you give us a screenshot of it?

**Comment by tobiasKaminsky** [comment]
No response within the last month, therefore closing.
Please feel free to reopen with additional infos, if the problem still exists.
