### ISSUE TITLE
Enhance maintenance recognition

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#989]
With #502 we have a recognition of maintenance mode for
- create, rename, move, delete of files/folders
- upload new files

But you can still browse the file list and refresh the folder listing without any knowledge that the server is currently in maintenance mode.

@jancborchardt @eppfel please give us an hint how to show it to the user.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky I'd say the same way we will show client being offline (no connection) 😄

**Comment by tobiasKaminsky** [comment]
Maybe you want to assign it to yourself?

**Comment by AndyScherzinger** [comment]
Initially, yeah. At least for the mockup

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky here are your mockups, the inital implementation can be found here :)
https://github.com/nextcloud/android/tree/offlineDisplay

**Comment by AndyScherzinger** [comment]
![device-2017-07-23-211316](https://user-images.githubusercontent.com/1315170/28502125-ec2fd344-6feb-11e7-9b16-1c36a8a310e3.png)
![device-2017-07-23-211212](https://user-images.githubusercontent.com/1315170/28502126-ec54134e-6feb-11e7-8e06-54783b7adb32.png)

**Comment by AndyScherzinger** [comment]
feel free to utilize the UI part @tobiasKaminsky :)

**Comment by tobiasKaminsky** [comment]
Looks great, should be part of #1143

**Comment by AndyScherzinger** [comment]
reposting the branch just in case, since it is not just a mockup but a UI implementation already in place but not in use yet: https://github.com/nextcloud/android/tree/offlineDisplay

**Comment by tobiasKaminsky** [comment]
Oh, I missed that.
Really cool :+1:
