### ISSUE TITLE
Automatic upload > set a custom folder > local folder > when a folder is checked, it returns a parent directory

### ISSUE THREAD

**Issue by pgy866** [nextcloud/android#9891]
Automatic upload > set a custom folder > local folder > when a folder is checked, it returns a parent directory

For example:  is selected `/storage/emulated/0/DCIM/Camera/cache`
The actual path returned is: `/storage/emulated/0/DCIM/Camera/`

**Comment by AlvaroBrey** [comment]
Duplicate of #8940
