### ISSUE TITLE
nextcloud server Centos+Apache+php open https, Android Client Unable to play videos，Windows web and ios clients Can play videos,Please help me！

### ISSUE THREAD

**Issue by ShaKaLaKaaaa** [nextcloud/android#9892]
nextcloud server Centos+Apache+php open https, Android Client Unable to play videos，Windows web and ios clients Can play videos,Please help me！!

**Comment by AlvaroBrey** [comment]
Please open the issue using [the "bug" template](https://github.com/nextcloud/android/issues/new?assignees=&labels=bug&template=bug_report.md) and fill in the required fields.
