### ISSUE TITLE
Multi Select on Files Operation

### ISSUE THREAD

**Issue by hitam4450** [nextcloud/android#99]
Hi, I just downloaded Version 1.1 and I like it! 
Especially I like the option to create Sub folders to be able  to organize files by year-month. 
However, currently the option to select "multiple" files prior to take any selected action e.g. moving files "within the server" to a new location, is missing!
This option facilitates files operation considerably !

regards, hitam4450

**Comment by AndyScherzinger** [comment]
Hi @hitam4450 not sure I got it right so I just ask :)
My guess is you are looking for the multi select feature which we are planning to implement next #61. You can try it out with our beta which can be installed in parallel, see https://f-droid.org/repository/browse/?fdfilter=com.nextcloud&fdid=com.nextcloud.android.beta

**Comment by hitam4450** [comment]
Hi Andy! Thanks for your quick reply. I appreciated it vey much! I will follow your suggestion, and will test the beta version and will report back here !

regards, hitam4450

**Comment by hitam4450** [comment]
Hi Andy,

see my first comments : https://github.com/nextcloud/android/issues/101
regards, hitam4450

**Comment by AndyScherzinger** [comment]
Hi @hitam4450 
Thanks for all the feedback. Regarding the beta check, does the multi select you see in the beta fulfill the requirement described in this issue?

**Comment by hitam4450** [comment]
Yes, this fulfills the requirement and my idea, as well!  :)

regards, hitam4450

**Comment by AndyScherzinger** [comment]
Glad to hear that and hopefully we can bake this in to the app in the near future!
