### ISSUE TITLE
Video streaming not working with self-signed certificate

### ISSUE THREAD

**Issue by ShaKaLaKaaaa** [nextcloud/android#9908]
### Expected behaviour
- Tell us what should happen
- nextcloud server Centos+Apache+php open https, Android Client can play videos

### Actual behaviour
- Tell us what happens
- nextcloud server Centos+Apache+php open https, Android Client Unable to play videos，Windows web and ios clients Can play videos,Please help me！

### Can you reproduce this problem on https://try.nextcloud.com?
- demo address  https://pancloud.tpddns.cn:8443/
-Test account： test  test@12345678

### Environment data
Android version: Android 10

Device model: 

Stock or customized system:

Nextcloud app version: 3.19.0

Nextcloud server version: 23.0.2

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```no nextcloud.log
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AlvaroBrey** [comment]
Trace: 

```java
  ExoPlayerImplInternal  E  Playback error
                         E    com.google.android.exoplayer2.ExoPlaybackException: Source error
                         E        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:640)
                         E        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:612)
                         E        at android.os.Handler.dispatchMessage(Handler.java:102)
                         E        at android.os.Looper.loop(Looper.java:223)
                         E        at android.os.HandlerThread.run(HandlerThread.java:67)
                         E    Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
                         E        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:365)
                         E        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:258)
                         E        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
                         E        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1009)
                         E        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
                         E        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                         E        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                         E        at java.lang.Thread.run(Thread.java:923)
                         E    Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
```

Streaming isn't working due to the server's self-signed certificate.

Alternatives until it's fixed:

* Download the file prior to playing it. Only streaming is failing, but if you download via the three-dot menu, you can play the video.
* Get a proper certificate for your server. Let's Encrypt offers free, valid certificates.

**Comment by ShaKaLaKaaaa** [comment]
Is there a plan to fix this problem

**Comment by AlvaroBrey** [comment]
> Is there a plan to fix this problem

Will probably fix it at some point, but no ETA I'm afraid. This is a very narrow use case.

Dev reference for whoever picks up this issue: https://github.com/google/ExoPlayer/issues/1819

**Comment by ShaKaLaKaaaa** [comment]
I think it is a very typical problem. Self signed certificates are widely used. Some users will not apply for free SSL certificates with a short validity period. If they want to use HTTPS in the Internet environment, they can only use self signed certificates. Please include this problem in the repair plan. be deeply grateful!!

**Comment by lbdroid** [comment]
> I think it is a very typical problem. Self signed certificates are widely used. Some users will not apply for free SSL certificates with a short validity period. If they want to use HTTPS in the Internet environment, they can only use self signed certificates. Please include this problem in the repair plan. be deeply grateful!!can you use local video player to avoid this problem？

There is no justification for users being unwilling to "apply for free SSL certificates with a short validity period". Letsencrypt (and others) offer free certificates with a validity period of 3 months, and do not require any weird "application process". Just set up a cron to run certbot and reload apache at 2AM on the first day of every month to automatically renew it indefinitely.

**Comment by AlvaroBrey** [comment]
@ShaKaLaKaaaa you can test the QA APK in #9945 to test if it fixes your issue. It's meant for a different fix, but it should fix your case too.

However, I agree with @lbdroid, just install certbot and let it autorenew your certificates. It's way easier in the long term.

**Comment by ShaKaLaKaaaa** [comment]
Enable HTTPS mode with self signature, play video online with #9945 QA APK, and the test is successful. Thank you. Public IP port 80 is not open and cannot be used. Let's encrypt cannot verify whether the domain name is available. Consider incorporating this bug into the next APK version?

**Comment by AlvaroBrey** [comment]
> Enable HTTPS mode with self signature, play video online with #9945 QA APK, and the test is successful. Thank you. Public IP port 80 is not open and cannot be used. Let's encrypt cannot verify whether the domain name is available. Consider incorporating this bug into the next APK version?

Too late for 3.19.1, but will be in 3.20

**Comment by ShaKaLaKaaaa** [comment]
When will version 3.20 be released?

**Comment by AlvaroBrey** [comment]
> When will version 3.20 be released?

RC1 this week, final version in 2 weeks if all goes well.
