### ISSUE TITLE
Auto Upload: add month name

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#991]
If you have multiple months, you will see "02" , "05" in gallery app.
To distinguish this from other random/temporary folder names I suggest to add " - monthname" to it:
"01 - january"
"02 - february"
...
To avoid more options this should be "just" changed.

**Comment by AndyScherzinger** [comment]
In general I am fine with it since it doesn't make a difference to the functionality, but who is creating random, temporary folders within our upload folder structure?!

**Comment by mario** [comment]
I am against this. It complicates folder naming for no real reason.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky @mario If we find the cuase for the random/temp folders created within our auto upload structure (don't have an idea who/what should do that) there wouldn't be a reason anymore for a fix since there is no issue anymore 😆

**Comment by mario** [comment]
I think it's more about seeing folders named "02" in gallery, and you can see various other folders in gallery too (which is an external app). But meh ...

**Comment by tobiasKaminsky** [comment]
The random folder names are/can be created by the user, e.g. /sdcard/02 or such.
This will then "conflict" with our /InstantUpload/2017/02/ as the gallery app only shows the parent folder name, in both cases "02".
For seeing the foldername in gallery app something like "2017 - 02 - February" would be the best, but then it is redundant to our folder structure...

**Comment by AndyScherzinger** [comment]
Wouldn't it then be better in general to change this in the gallery app itself since we would then just be working around the display logic of the gallery app instead of changing the gallery app?

What do you think @oparoz ?

**Comment by tobiasKaminsky** [comment]
We are talking about the gallery app in android, the default app to view pictures.

**Comment by AndyScherzinger** [comment]
Ah, okay. I thought we are talking about the server side app...

**Comment by jasonbayton** [comment]
As long as it doesn't impact serverside, I've got 5 years worth of pictures organised beautifully in NC's default YYYY/MM structure and I really don't want that to change :)

Indifferent on the gallery side, doesn't particularly bother me.

**Comment by tobiasKaminsky** [comment]
Well, it would affect all new uploaded files and thus all new folders.
This should either be an option (oO not an option, I hear Jan yelling ;-) ) or we just leave it this way.

**Comment by mario** [comment]
We leave it the current way.

**Comment by tobiasKaminsky** [comment]
Ok :+1:

**Comment by AndyScherzinger** [comment]
👍
