### ISSUE TITLE
Handling bugs

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#992]
To have a better overview about our outstanding bugs, I would like to enhance our bug processing like this:
- new bug is reported 
- at least one other needs to be able to reproduce it -> "approved"
- if not, then ask for steps -> "needs info"
- if bug is fixed -> "pr exists"

Bugs that have "needs info" and no response after 1 month can be closed.

**Comment by AndyScherzinger** [comment]
Sounds good to me 👍

**Comment by tobiasKaminsky** [comment]
@mario?

**Comment by tobiasKaminsky** [comment]
@mario?

**Comment by mario** [comment]
Sure

**Comment by tobiasKaminsky** [comment]
Added to contributing.md
