### ISSUE TITLE
Opening a folder on an external share shows "no data available"

### ISSUE THREAD

**Issue by j-ed** [nextcloud/android#994]
### Actual behaviour
If I open a folder which resides on an external WebDAV share, its content is not displayed but "no data available". Surprisingly this behavior does not happen on all folders but most of them. I've not yet found a template which justifies the different handling of the folders. 
The content itself is viewable using the normal Web-GUI or using an alternative app like e.g. ES File Explorer.

### Expected behaviour
The content of a folder should instantly been shown.
 
### Steps to reproduce
1. Open the Nextcloud app.
2. Access a folder which contains several files and folders.
3. The message "no data available" is shown.

### Environment data
Android version: 7.1.1

Device model: Jiayu S3 Adv.

Stock or customized system: MadOS ROM

Nextcloud app version: v1.4.2 beta

Nextcloud server version: 11.0.3 

#### Web server error log

Nothing special has been logged related to this problem.

**Comment by AndyScherzinger** [comment]
@mario @tobiasKaminsky do we have a setup anywhere to reproduce, debug this behavior?

**Comment by j-ed** [comment]
I think it would be nice to have a kind of trace log function in the Nextcloud app to be able to track the requests and answers to/from the server. This would allow to provide more detailed feedback on such kind of communication issues.

**Comment by j-ed** [comment]
The following lines are written to the log right after I've pressed the Install button:
```
{"reqId":"9GqYivNTxYOlxqFwbzi4","level":3,"time":"2017-05-26 15:34:15+02:00","remoteAddr":"10.0.2.2","user":"admin","app":"PHP","method":"POST","url":"\/owncloud\/index.php\/apps\/market\/apps\/gallery\/install","message":"Undefined variable: undefinedVariable at \/var\/www\/htdocs\/owncloud\/lib\/composer\/nikic\/php-parser\/lib\/PhpParser\/Lexer.php#70"}
{"reqId":"TdeBq8QJjRDVuc9MeYIt","level":3,"time":"2017-05-26 15:34:16+02:00","remoteAddr":"10.0.2.2","user":"admin","app":"PHP","method":"GET","url":"\/owncloud\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","message":"You are using a fallback implementation of the intl extension. Installing the native one is highly recommended instead. at \/var\/www\/htdocs\/owncloud\/lib\/composer\/patchwork\/utf8\/src\/Patchwork\/Utf8\/Bootup\/intl.php#18"}
```

**Comment by j-ed** [comment]
**Upgraded to:**
Nextcloud app version: v1.4.3
Nextcloud server version: 12.0.0

The problem still persists with the Nextcloud app. As a cross-check I've tried to
access Nextcloud from the ES File Explorer app on Android usind WebDAV and
the Owncloud app on IOS. Both are displaying the files properly.
I've also deleted and reinstalled the whole Nextcloud app and its data but
without getting any improvement of the situation.

**Comment by j-ed** [comment]
Today I've installed the latest Nextcloud desktop sync to investigate if the described behavior is a general one or a Nextcloud Android app specific one. Against my expectation I was able to synchronize all folders to my desktop without any problem which are not shown in the Android app.

**Comment by j-ed** [comment]
Another update: Today I've tested to access my Nextcloud files with the latest ownCloud iOS v3.6.2 app. The app worked like a charm and all available files and folders were displayed without any problems.

**Comment by tobiasKaminsky** [comment]
I tried it with a local external storage on my dev system and there all files were accessible, both on webUI and android.

Ping @icewind1991 if he has an idea?

**Comment by tobiasKaminsky** [comment]
Can you send us a test account to android at nextcloud dot com with some folders where this is happening?

**Comment by j-ed** [comment]
Unfortunately my server is not reachable over the Internet, that's the reason why I've asked for an app with debug trace enabled etc. I will try to replicate it with a test account and come back to you as soon as the problem is reproducible.

**Comment by tobiasKaminsky** [comment]
Closing this one in favor of #468 as there is more description.
