### ISSUE TITLE
BUG: when using the share menu to upload multiple file to Nextcloud, the app uploads only one file, and forgets to upload the rest of the selections.

### ISSUE THREAD

**Issue by BugRMSys** [nextcloud/android#9964]
### Expected behaviour
- upload all files

### Actual behaviour
-  just upload one file

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 12

Device model: MI 11 Ultra

Stock or customized system:

Nextcloud app version: 3.19.1

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AlvaroBrey** [comment]
@BugRMSys can you fill in the "steps to reproduce" section, please?

**Comment by BugRMSys** [comment]
> @BugRMSys can you fill in the "steps to reproduce" section, please?
Hi, bro,  do you know why I can not get the login page when reinstall the app?

**Comment by AlvaroBrey** [comment]
> Hi, bro,  do you know why I can not get the login page when reinstall the app?

Open another issue describing your problem, as it is unrelated to this one. And please fill in the template properly, both in this issue and in the new one.

**Comment by BugRMSys** [comment]
> why I can not get the login page when r

Okay, thank you very much .  I will rewrite them.
