### ISSUE TITLE
Can not open doc file in nextcloud

### ISSUE THREAD

**Issue by BugRMSys** [nextcloud/android#9965]
### Steps to reproduce
1. click any doc file uploaded in nextcloud
2. there is nothing to choose, just waiting for a long time (the network is great)
3. 

### Expected behaviour
- view the file

### Actual behaviour
- just loading and nothing happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:12

Device model: Mi11 Ultra

Stock or customized system:

Nextcloud app version:3.19.1

https://user-images.githubusercontent.com/15137182/158205449-8324c20e-5852-4813-a1f0-71195e31ff1e.mp4

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AlvaroBrey** [comment]
@BugRMSys in your video you can clearly see an "open with" dialog pop up from the button. The Nextcloud app won't open DOCx files on its own, you'll need an app installed in your device that can handle them.

The loading animation _should_ stop, but that's a different bug.

**Comment by BugRMSys** [comment]
Thank you for your information.
Do you why when I reinstall nextcloud, I cannot get the page of log in ?
