### ISSUE TITLE
Where is the login page with email and password?

### ISSUE THREAD

**Issue by BugRMSys** [nextcloud/android#9966]
### Is your feature request related to a problem? Please describe.
I have signed a account, but I cannot find the login page to type in  email and passpord

### Describe the solution you'd like
provide login in page that I can login with email and password

https://user-images.githubusercontent.com/15137182/158211569-c3da693f-da5e-473a-9105-ee177db687ed.mp4

### Additional context

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AlvaroBrey** [comment]
You need to enter your server address after clicking "Login", and then you will be shown the user+password form.
