### ISSUE TITLE
DAVx5 nextcloud login flow should support using an access token

### ISSUE THREAD

**Issue by jondo** [nextcloud/android#9973]
When DAVx5 is installed, selecting "sync calendar & contacts" in the nextcloud app settings leads to a nextcloud login flow that should support using an access token for the password. Currently, it only  supports logging in with the nextcloud password, as described [here](https://github.com/nextcloud/android/issues/9339#issuecomment-1008572200).

I see this with 3.19.0 on Android 10 (Lineage OS).

**Comment by coelner** [comment]
Currently there is another problem related to this: As soon as the account runs into a bruteforce delay, the davx5 login tries again and again. And this leads to a locked account. 
(The reason why the account is running into the bruteforce delay is somewehere between 2fa-webauthn plugin and DNS resolving issues)

**Comment by muekno** [comment]
Bis vor kurzen (2 Wochen) konnte ich mit meinen älteren Android 7 handy 1a Kontakte Syncen, Nextcloud war immer aktuell. Nach einem Server crash musste ich alles ne Aufsetzen, Auch auf dem Handy habe ich alles neu installiert.
Seit dem kann ich nur noch Dateien syncen aber keine Kontake mehr

**Comment by joshtrichards** [comment]
Hi @jondo - We definitely support the trigger the Login Flow that supports tokens (see (#4716). I just checked the current code and tested as well to confirm. Are you still experiencing this in current versions of the software?

**Comment by jondo** [comment]
I think this can be closed.
