### ISSUE TITLE
Transifex: 'quote' character should be escaped for Android String resource

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#998]
```
Review, amend and write code, see 
&lt;a href="https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md">CONTRIBUTING.md&lt;/a> 
for details
```
can't be translated on transifex with the error:
```
'quote' character should be escaped for Android String resource
```

any idea @tobiasKaminsky , since you made the last config changes to transifex :)
Alternatively we could go for 
```
Review, amend and write code, see %1$s for details
```
and add the hyperlink via string formatting in code...

**Comment by tobiasKaminsky** [comment]
I have enabled a check that verifies that exery UTF8-char from source is also translated into destination string.
The check is described as "Content of placeholder delimiters &...;  is preserved in the translation."

Your idea to extarct the hyperlink to code is cleaner as then the url in setup.xml can be used.

**Comment by AndyScherzinger** [comment]
Right, didn't think about ```setup.xml``` but that is nicer and more flexible too 👍

**Comment by tobiasKaminsky** [comment]
I read it completely wrong: it is not about utf8-chars but about " (quote sign) which is suggested to be quoted.
Anyway, a PR is here: #1001

**Comment by AndyScherzinger** [comment]
@comradekingu the last remaining en_GB string will be translatable tomorrow. Thanks for the hint 👍
