### ISSUE TITLE
Creating a shareable link creates a link to the top level folder, instead of the selected folder (Android dev version of app) 

### ISSUE THREAD

**Issue by AlertSubject** [nextcloud/android#9982]
### Steps to reproduce
1. Create a subfokder of a folder 
2. Create a shareable link 
3. Link that's created will give access to the folder that contains the sub folder, instead of the sub folder itself

### Expected behaviour
- link should lead to sub folder that was selected

### Actual behavior 
- link gives access to the folder that contains the sub folder 

### Environment data
Android version: 11
 
Device model: oneplus 9 pro

Stock or customized system: oxygenOS

Nextcloud app version: 22.03.11

Nextcloud server version: beta version of nextcloud hub

Reverse proxy: no idea what that is 

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AlvaroBrey** [comment]
Fixed by https://github.com/nextcloud/android/pull/9970, will be out in next release. Thank you for your report!
