### ISSUE TITLE
'Set up a custom folder' selects parent folder instead

### ISSUE THREAD

**Issue by timosturm** [nextcloud/android#9986]
### Steps to reproduce
1. `Settings` -> `Auto Upload` -> `Set up a custom folder` -> `Local Folder` 
2. Select some folder to sync
3.  Finish setting up the auto upload
4. Sync folder

### Expected behaviour
When selecting the local folder, the selected folder should be used for syncing.

### Actual behaviour
The **parent** folder of the selected folder is selected instead.

E.g., local folder selected is `storage/emulated/0/MyData` will yield `storage/emulated/0` to be synced. This can be circumvented by creating a subfolder in `MyData` and selecting it when setting up the sync.

### Environment data
Android version: 12

Stock or customized system: LineageOS 19

Nextcloud app version: 3.19.0, F-Droid

**Comment by codereptile** [comment]
This can be avoided, if you select the folder (click the box next to it), then go into it and then select it (this time using the button in the lower part of the screen). Yes, this is a bug, but it has this workaround.

**Comment by AlvaroBrey** [comment]
Fixed by #9920 , will be in next release.
