### ISSUE TITLE
Bump targetSDK to 31

### ISSUE THREAD

**Issue by AlvaroBrey** [nextcloud/android#9997]
Let's not wait until it's compulsory.

Behaviour changes to be addressed: https://developer.android.com/about/versions/12/behavior-changes-12

Things to pay attention to:
- App Links verification (https://developer.android.com/about/versions/12/behavior-changes-12#android-app-links-verification-changes). On Android 12+ we need to ask for permission for the app to open links to the Nextcloud instance. It's already broken, even if it theoretically should work before the targetSDK bump (#9346 )
- Changes in notifications with custom styles (https://developer.android.com/about/versions/12/behavior-changes-12#custom-notifications)
- Toasts can only show 2 lines max (https://developer.android.com/about/versions/12/behavior-changes-12#toast-redesign)
- Restrictions for foreground services (https://developer.android.com/about/versions/12/behavior-changes-12#foreground-service-launch-restrictions). We use them for music playing, at least.

**Comment by tobiasKaminsky** [comment]
as of 01.08 this is needed for new apps
as 01.11. for app updates

https://support.google.com/googleplay/android-developer/answer/11926878

**Comment by AlvaroBrey** [comment]
FileUploader crashes on background uploads, see #10692

**Comment by AlvaroBrey** [comment]
Reverted in #10693, pending #10696
